### ISSUE TITLE
[API DESIGN REVIEW] A contribution of a convolutional GRU layer (ConvGRU2D)

### ISSUE THREAD

**Issue by NivNayman** [keras-team/keras#10009]
Well I wasn't sure if this is the right place to ask for permission for PR, but here is the template describing it:
https://docs.google.com/document/d/1Z_2Yd9N_Vj7Lh5Zt2ftuj5d3_m5Z6QQi-dsABxPPd70/edit?usp=sharing

**Comment by harshini-gadige** [comment]
Please submit a PR in the Pull Requests section and it will be reviewed there. Thank you !
