### ISSUE TITLE
Why an when to use ImageGenerator.random_transform() ?

### ISSUE THREAD

**Issue by Geek-Peng** [keras-team/keras#10002]
I'm new person of  Machine Learning,And i will  appreciate for your answer

**Comment by birolkuyumcu** [comment]
this is not an issue
ask this keras user groups
## Support

You can ask questions and join the development discussion:

- On the [Keras Google group](https://groups.google.com/forum/#!forum/keras-users).
- On the [Keras Slack channel](https://kerasteam.slack.com). Use [this link](https://keras-slack-autojoin.herokuapp.com/) to request an invitation to the channel.

You can also post **bug reports and feature requests** (only) in [GitHub issues](https://github.com/keras-team/keras/issues).
