### ISSUE TITLE
How can I change active_class_ids for batch more than 1

### ISSUE THREAD

**Issue by 5730279821-TA** [keras-team/keras#10011]
from function -> def mrcnn_class_loss_graph

# TODO: Update this line to work with batch > 1. Right now it assumes all
#       images in a batch have the same active_class_ids 
pred_active = tf.gather(active_class_ids[0], pred_class_ids)

If I use batch = 16 , How can I change pred_active to use all 16 batch size ?

**Comment by darshan-majithiya** [comment]
Hi, I'm stuck on the same issue. Please let me know if you found a solution.

**Comment by AndreyStille** [comment]
> Hi, I'm stuck on the same issue. Please let me know if you found a solution.

Hi
Have you solved the problem? Please help if you have solution. I have same problem.
