### ISSUE TITLE
Error in Lambda layer when wrapped function expects non-float argument

### ISSUE THREAD

**Issue by afourast** [keras-team/keras#10021]
The Lambda layer runs the wrapped function on a float placeholder to infer the output shape.
(no dtype is passed on placeholder creation)
https://github.com/keras-team/keras/blob/b09ec1c9bf827622a5eebb94ba0af5bf202ca359/keras/layers/core.py#L650

example where the function expects complex input:
```python
from keras.layers import Lambda, Input
import tensorflow as tf

complex_tensor = Input(shape=(1,),dtype='complex64')

imag_part = Lambda( lambda x: tf.imag(x) )(complex_tensor)
```
TypeError: Value passed to parameter 'input' has DataType float32 not in list of allowed values: complex64, complex128

**Comment by erbian** [comment]
fyi i just ran into this as well.  it's a pretty weird "feature".  if there's any way in the interim to catch `TypeError` in `Lambda` layers and suggest this could be happening that would have been nice.

**Comment by shahruk10** [comment]
Ran to the same problem here. A solution to this will be much appreciated !

Would it be solved by allowing a dtype parameter in Lambda, and the placeholder dtype will be chosen accordingly?
