### ISSUE TITLE
python autogen.py fails

### ISSUE THREAD

**Issue by nl19856** [keras-team/keras#10025]
Hi,
When running python autogen.py it fails with:
/u01/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "autogen.py", line 273, in <module>
    (preprocessing.image.ImageDataGenerator, '*')
AttributeError: module 'keras.preprocessing' has no attribute 'image'

I cloned keras just a couple of minutes ago.
git clone https://github.com/keras-team/keras.git

**Comment by Dref360** [comment]
```
export PYTHONPATH=$KERAS_ROOT
cd docs
python autogen.py
```

This should fix your issue
