### ISSUE TITLE
Dense(img_gen.get_output_size(), kernel_initializer='he_normal', name='dense2')(x)

### ISSUE THREAD

**Issue by EmanuelaBoros** [keras-team/keras#10043]
keras/examples/image_ocr.py

ValueError: Dimensions must be equal, but are 32 and 28 for 'dense2_1/add' (op: 'Add') with input shapes: [?,32,28], [1,28,1].

Keras==2.1.6

**Comment by Dref360** [comment]
Hi!
This issue isn't related to a bug/enhancement/feature request or other accepted types of issue.

To ask questions, please see the following resources : 
* https://keras.io/
* https://keras.io/#support
* https://gitter.im/Keras-io/Lobby

Thanks!

If you think I made a mistake, please re-open this issue.
