### ISSUE TITLE
An attention mechanism implementation

### ISSUE THREAD

**Issue by jmvalin** [keras-team/keras#10041]
I recently spent some time implementing the attention mechanism from
D. Bahdanau, K.H. Cho, Y. Bengio, Neural machine translation by jointly learning to align and translate, 2015.
before realizing that it wasn't really suitable for my problem. Since I don't have a suitable problem, I'm not sure all the code is correct, but I still thought it could be useful for someone. 

My implementation adds an AttnRNN class that inherits from RNN and can directly reuse both GRUCell and LSTMCell to make an AttnGRU or an AttnLSTM (only AttnLSTM was briefly tested).

Here's the implementation: [attnrnn.py](https://jmvalin.ca/misc_stuff/attnrnn.py)

Let me know if you find this useful or if you find any problems with the code. In general, it seems like making this kind of changes easier in Keras would be useful.

**Comment by cuiqiongjie** [comment]
Could you give an example of your implementation?

**Comment by andhus** [comment]
@jmvalin Please see this ongoing work https://github.com/keras-team/keras/pull/11421 for a more modular approach.
