### ISSUE TITLE
Simple weighted embedding network

### ISSUE THREAD

**Issue by yftah89** [keras-team/keras#10048]
I have several embeddings matrices, lets say E1 matrix is for Glove and E2 is for Word2vec.
I would like to build a simple sentiment classifier which takes trainable weighted sum of this embeddings.
For example, for the word "dog" I would like to get x["dog"]*E1["dog"] + y["dog"]*E2["dog"] when x and y are learned parameters (notice that I want to learn x and y _**for each word**_
I know I need to somehow learn the X vector and Y vector and use merge with "add", but I have no idea how to actually do it, help will be highly appreciated

**Comment by harshini-gadige** [comment]
Hi

Since this is not a bug/feature request, request you to post these kind of questions in any of the following.

https://keras.io/
https://keras.io/#support
https://gitter.im/Keras-io/Lobby

Thanks!
