### ISSUE TITLE
ValueEroor () vs (?, ?) with binary_crossentropy  and  Lambda 

### ISSUE THREAD

**Issue by ghost** [keras-team/keras#10057]
Maybe it is a bug .
When I use a Dense(1) layer as output,  the output shape is (None,1) in the model summary.
And it works OK.
If I use a Lamda layer with output_shape=(1,) , output shape in the model summary is the same as  above (None,1).It's OK, but when training, the error comes out.

`ValueError: Shapes (?, ?) and () are not compatible`
`ValueError: logits and labels must have the same shape (() vs (?, ?))`

Is it a bug?

Python 3.6.2
Tensorflow 1.7
Keras 2.1.6
Window10

**Comment by fidelechevarria** [comment]
I am having the same issue.

**Comment by eldanch** [comment]
Same here

**Comment by ericvoots** [comment]
same here in a later version

python 3.8
Tensorflow 2.2
Windows 10
CUDA 10.1
