### ISSUE TITLE
regarding the testing

### ISSUE THREAD

**Issue by champaka9535528677** [keras-team/keras#10051]
sir i have trained cnn with 3 classes of data containing fish flower and birds but im not getting how to test it...please send me the link to test the trained cnn in python

**Comment by Dref360** [comment]
Hi!
This issue isn't related to a bug/enhancement/feature request or other accepted types of issue.

To ask questions, please see the following resources : 
* https://keras.io/
* https://keras.io/#support
* https://gitter.im/Keras-io/Lobby

Thanks!

If you think I made a mistake, please re-open this issue.
