### ISSUE TITLE
about cnn

### ISSUE THREAD

**Issue by champaka9535528677** [keras-team/keras#10050]
sir i have added only pooling and convolution layer in my main code. i have not used fully connected layer yet but still it is training...and i have not started to train also

**Comment by Dref360** [comment]
Hi!
This issue isn't related to a bug/enhancement/feature request or other accepted types of issue.

To ask questions, please see the following resources : 
* https://keras.io/
* https://keras.io/#support
* https://gitter.im/Keras-io/Lobby

Thanks!

If you think I made a mistake, please re-open this issue.
