### ISSUE TITLE
PyPi: Keras Description

### ISSUE THREAD

**Issue by TimZaman** [keras-team/keras#10076]
Hi @fchollet , I think the recent PyPi redesign has nuked the description of Keras, you might want to re-add that:
https://pypi.org/project/Keras/

![image](https://user-images.githubusercontent.com/7721540/39447490-bfff1e48-4c76-11e8-96e3-b2a84bd9a300.png)

**Comment by fchollet** [comment]
Indeed, noticed this last week when I uploaded Keras 2.1.6. I will take care of it.

**Comment by fchollet** [comment]
Specifically, we will fix it with the next release.
