### ISSUE TITLE
Create a Local version of the library with some modifications to the library

### ISSUE THREAD

**Issue by elhenceashima** [keras-team/keras#10070]
I am currently experimenting with certain modifications to the basic Neural Network cells and while I have found the corresponding source code and made the requisite changes, how do I make these changes effective in my local environment(build/change in the other files in the source code folder) so that I could check and compare my versions with the original implementations in the library.

Do i have to reinstall it from the sources, the source code being the folder with my modified code.
Also could someone lease enumerate the required steps and requirements to make such changes available locally atleast for the time being.

**Comment by Dref360** [comment]
remove keras from your environment and add the root of the package (cloned from Github) to your PYTHONPATH. This way, your environment will directly look at the source file.
