### ISSUE TITLE
Error when load model with h5 file

### ISSUE THREAD

**Issue by ThorPham** [keras-team/keras#10075]
I run model in colab with gpu and save file with code "model.save("shape_detection.h5")" . Then i download this file an run in my computer but have error  TypeError: ('Keyword argument not understood:', 'data_format')
Any one help me fix it

**Comment by RaphaelMeudec** [comment]
@ThorPham Can you share the file itself and a gist?

**Comment by BharathSD** [comment]
Facing the same issue. 
Have attached the model file below
[model.zip](https://github.com/keras-team/keras/files/1963074/model.zip)

Anaconda : 3
Python : 3.5.4
Keras Version : 2.1.2
Tensorflow : 1.8.0

**Comment by ThorPham** [comment]
i done fix it. You should check version library on colab and in your computer has same.

**Comment by syaffers** [comment]
Is there a way to check which version of Keras was used to train the model in the `.h5` file? I'm facing this problem but I can't recall the version of Keras on my other computer.

**Comment by selimelawwa** [comment]
@ThorPham 
Hi Can you please tell me how you fixed this issue and version of what should I check on my Colab and same on my Computer. I am using same python version ? what should I fix

thanks

**Comment by syaffers** [comment]
@selimelawwa I managed to get this working. You should make sure that both Keras versions, on Colab and on your computer, is the same so that the model can be loaded by one system or the other. The way to check the version of Keras used to train a saved model is

    import h5py

    f = h5py.File('Model.h5', 'r')
    print(f.attrs.get('keras_version'))

I'm not sure about the python versions, but I reckon it shouldn't matter. In any case, my computer has python 3.6

**Comment by selimelawwa** [comment]
Thanks alot, after I updated my Keras to be same version of Colab (both 2.1.6), then I got this error,


  File "D:\Anaconda3\envs\Tensorflow\lib\site-packages\keras\layers\convolutional.py", line 445, in __init__
    kernel_constraint=None,

TypeError: super(type, obj): obj must be an instance or subtype of type

Do you have any idea about it?

**Comment by flagshipdynamics** [comment]
selimelawwa - I get the apply_op_helper error too.

**Comment by selimelawwa** [comment]
@flagshipdynamics I think updating the h5py and hdf5 will splve this issue, update them to be with same version you used to create your model and it should work

**Comment by Flock1** [comment]
Hey, can someone tell me how to solve this issue? I am getting the same one and I didn't do anything with the version of keras or any of the libraries. Simply trained the model in jupyter notebook and imported the model in a python code.

**Comment by Flock1** [comment]
@selimelawwa, also, updating Keras also helps.

**Comment by selimelawwa** [comment]
@Flock1  Yes you have to make sure you have same versions of keras, tensorflow, h5py, hdf5 and python (plus any other related package) on both machines to avoid such problems

**Comment by Flock1** [comment]
What I don't understand is compatibility? I wonder if keras 2.2 is compatible with tf 1.5? Because > TF 1.5 requires CUDA 9 and that's a nightmare.

**Comment by selimelawwa** [comment]
Well I updated to Keras 2.1.6 and user TF 1.8, but I dont use GPU on my computer, so I didnt face this issue of CUDA . 

I use google Colab machine with GPU to train my model and then download it on my computer later

**Comment by Flock1** [comment]
@selimelawwa, that's actually a good idea.

**Comment by ananya53255** [comment]
> Is there a way to check which version of Keras was used to train the model in the .h5 file? I'm facing this problem but I can't recall the version of Keras on my other computer.
*******************************************************************************************
I created a GPU environment in my PC and tried to run the code (written by someone else) with anaconda, I got the same error. I am using-
anaconda 3, 
python 3.7.4 (but downgraded to 2.7.0 in the GPU environment), 
keras 2.2.4, 
tensorflow 2.0.0.
How can I check the version of keras used to create the h5 file? And how can I downgrade my keras to make it compatible? Thanks in advance.
