### ISSUE TITLE
Issue loading Keras LSTM in subprocess

### ISSUE THREAD

**Issue by bglick13** [keras-team/keras#10095]
I'm trying to train an RL model in parallel than relies on the output of a pre-trained Keras model. I'm trying to construct the Keras model in each subprocess and then set the weights from a saved file. The model is initialized as below:

```
print("building...")
x = Input(shape=(None, self.z_dim+self.action_dim))
print('input done')
lstm = LSTM(self.hidden_units, return_sequences=True, return_state=True)
print('lstm done')
lstm_out, _, _ = lstm(x)
print('dense started')
mdn = Dense(self.n_mixtures * (3*self.z_dim))(lstm_out)
print('dense done')
rnn = Model(x, mdn)
```

However, the execution hangs on the line `lstm_out, _, _ = lstm(x)`. The model initializes without problems in the main module. I am also able to initialize other models (that don't have LSTM layers) in subprocesses without problem. Does anyone have any idea what the problem could be?

Let me know if there's any other relevant info I can provide. I'm up to date on Keras and TF, and I've only tested this issue on Mac OS.

Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by jlopezpena** [comment]
In my experience, Keras hangs on multiprocessing whenever you import stuff **before** forking the processes (trying to sort out a similar issue on my code right now, but with sequential netowrks). Probably this is due to some staful variables in tensorflow low level library.

Try to move all the keras/tensorflow imports inside each subprocess without initializing it in the main process prior to forking.

**Comment by bglick13** [comment]
Thanks for the response! Yeah I've seen people having success trying to move imports, but it hasn't done the trick for me, unless I'm missing an import or something.

I'm using Celery to handle my multiprocessing, and here's more or less how it looks:

`
@app.task(name='eval_model')
def eval_model():
    import tensorflow as tf
    session = tf.Session()
    from vae.vae_models import ConvVAE
    from rnn.mdn_rnn import MDN
# Make the models and do stuff
`

I've checked if tensorflow or Keras is getting imported somewhere else by looking through sys.modules in my main script and they don't seem to be present by the time eval_model gets called.

**Comment by jlopezpena** [comment]
Celery might be trying to reuse processes; if it is so, the hanging would happen the second time a process is used (hint: if there are less jobs than processes then it would work)
I have had some success by isolating code from some function calls before defining and compiling the models. I am using this decorator for that:

```python
from functools import wraps
from multiprocessing import SimpleQueue, Process

def isolated(func):
    """Decorator to isolate a function call in a separate process.
    Will *NOT* work with generator functions.
    """
    @wraps(func)
    def wrapped_function_(*args, **kwargs):
        q = SimpleQueue()
        def f_(q, *args, **kwargs):
            q.put(func(*args, **kwargs))

        # Create a process on the helper function
        p = Process(target=f_, args=(q, *args), kwargs=kwargs)
        # Run the process...
        p.start()
        # Note that we call join right away, so this is NOT an asynchronous call
        p.join()
        # Extract the result from the queue.
        result = q.get()
        return result

    return wrapped_function_
```

In your code, I would make a `safe_eval` function like this:

```python
@isolated
def safe_eval_model():
    import tensorflow as tf
    session = tf.Session()
    ...
```

and then call that from your celery task:

```python
@app.task(name='eval_model')
def eval_model():
   safe_eval_model()
```

**Comment by bglick13** [comment]
I appreciate the follow-up. I tried your suggestion and got a "daemonic processes cannot have children" error. I assume Celery doesn't like me spinning up a process inside its subprocess.

**Comment by jlopezpena** [comment]
Same here. Some parts of my code now work fine with the decorator trick from above, others fail when using `multiprocessing` as a backend, but work when using `loky` (in the devel branch of `joblib`. These hanging errors are truly a pain in the neck...

Have you tried clearing the tensorflow session after your evaluation is done?
`tf.keras.backend.clear_session()`
 
There is little chance it will work, but it is worth giving it a try...

**Comment by bglick13** [comment]
I'm actually having some positive results using multiprocessing and making sure I run

`
multiprocessing.set_start_method('spawn')
`

At the start of my main script! Seems to allow me to get past the tensorflow locking issue. I'll be curious to hear if it works for you as well.
