### ISSUE TITLE
Speed regression with change of tensorflow backend version

### ISSUE THREAD

**Issue by jlopezpena** [keras-team/keras#10096]
We have observed some massive slowdowns in some Keras/tensorflow models with tensorflow versions newer than 1.4.1.
Not sure if the issue is with tensorflow or with the way keras creates the tensorflow models, so I am cross-posting these issue to both repos.

Here is a script reproducing the issue:

## Setup
```python
from pandas import get_dummies
from sklearn.datasets import make_classification

from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.callbacks import EarlyStopping

X, y = make_classification(n_samples=10000, n_features=10, n_informative=8,
                           n_classes=5, n_clusters_per_class=1, random_state=0)

model = Sequential()
model.add(Dense(10, input_dim=10, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(5, activation='sigmoid'))
model.add(Dropout(0.1))
model.add(Dense(5, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='rmsprop', metrics=['acc'])

yk = get_dummies(y)
```

## Fitting

```python
model.fit(X, yk, epochs=10, batch_size=50, 
               callbacks=[EarlyStopping(monitor='loss', patience=2)])   
```

Here are some timings for the fit method:
* Tensorflow 1.4.1:  **2.91 s ± 452 ms** per loop  (obtained using ipython's `%%timeit` magic, 7 loops)
* Tensorflow 1.5.0:  CPU times: user **2min 19s**, sys: 5min 22s, total: 7min 41s Wall time: 1min 2s
* Tensorflow 1.6.0: CPU times: user **5min 5s**, sys: 12min 31s, total: 17min 36s Wall time: 2min 37s
* Tensorflow 1.7.0: CPU times: user **5min 5s**, sys: 12min 39s, total: 17min 45s Wall time: 2min 39s

So, it seems there was a massive slowdown in version 1,5, and then a further one in 1.6 (which similar speed in 1.7). All the tests are run on a conda environment with python 3.6.5 and keras 2.1.5, with the corresponding tensorflow versions all coming from the anaconda `defaults` channel.

The GPU accelerated version of keras/tensorflow (`keras-gpu` conda package) does not present the issue.

Thanks in advance!

**Comment by Dref360** [comment]
Your test is biased.
This network will always be faster on CPU.
I suspect that your time 2.91s was using CPU. I get similar results when using tensorflow and not tensorflow-gpu.

using tensorflow-gpu 1.6 and 1.8, I added `with tensorflow.device('/cpu:0'):` and I get a similar runtime on Keras master branch.

**Comment by fchollet** [comment]
Anyway, going from 2.91 s to 2min 19s indicates a fundamental runtime issue such as running with/without a BLAS. It is not Keras-related and comes from differences in setups (such differences can sometimes be introduced when upgrading TF).

**Comment by jlopezpena** [comment]
> Doesn't that explain your problem?

What do you mean? To me it just suggests that the issue is in some CPU specific code, as the GPU code does not have the regression. The code will still run slow on recent versions if I don't have a GPU available (eg, in AWS instances or some Docker containers).

> Anyway, going from 2.91 s to 2min 19s indicates a fundamental runtime issue such as running 
> with/without a BLAS. It is not Keras-related and comes from differences in setups (such
> differences can sometimes be introduced when upgrading TF).

All the anaconda versions should be compiled/linked against Intel MKL; the way I see it there are (at least) three possible sources of the problem:

1. A compilation issue on the anaconda side (eg incorrectly passing the MKL flags)
2. Some regression introduced by tensorflow
3. An issue with the way Keras is translating the functional API code into tensorflow operations (perhaps due to a change in tensorflow API?)

I am trying to figure out which one it is, but it is tricky as I am not familiar with the internals of either keras or tensorflow, hence my cross-posting to both github pages (and support request sent to anaconda). These issues are hard to deal with because they show up in real life situations through the interaction of many software pieces, instead of an isolated testing environment.

Any type of help is appreciated, if you can compare the timings on different keras/tensorflow versions compiled from source (not coming from the anaconda packages) and don't see the slowdown, then it is likely an anaconda problem.

**Comment by jlopezpena** [comment]
Latest anaconda package for tensorflow 1.8 does not present the slowdown. Closing the issue.
