### ISSUE TITLE
TensorBoard callback runs the whole validation again (inefficient)

### ISSUE THREAD

**Issue by David-Taub** [keras-team/keras#10091]
The way tensorboard callback is currently implemented is that after one epoch, after the validation run is done, the post epoch tensorboard callback runs on the validation dataset again with the Tensorflow summaries, which is inefficient. 
A possible solution might include deleting the current implementation of TensorBoard callback and adding a Tensorboard flag that in training.py  _make_test_function() will cause the creation of the summaries similarly to the current callback implementaion, but then it will pass the tf.summary.merge_all() to the K.function.

**Comment by R1j1t** [comment]
I totally agree. When I am using tensorboard callback, my training is slowed drastically. Also 1 more thing i noticed, it takes quite a lot time (on GPU as well) to start the training i.e. for the callbacks to be loaded in the `fit_generator`

**Comment by gabrieldemarmiesse** [comment]
@fchollet , on a high-level, would you have any plans/advices/thoughts/wishes about how to solve this issue? This would help a lot a readers who would like to fix this since this is not trivial at all and will require a lot of changes to the codebase.
