### ISSUE TITLE
[DEV] Fixing stalling CI build for TF

### ISSUE THREAD

**Issue by fchollet** [keras-team/keras#10100]
# Position of the problem

- Both TF CI builds started timing out a couple days ago. The last passing build was [this one](https://travis-ci.org/keras-team/keras/builds/371831320) (besides the passing build, the corresponding PR passed the checks twice consecutively and didn't ever time out, which indicates with extremely high confidence that it did not cause the issue.
- The builds fails after 25-50 min with the error "No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself."
- Other builds are fine.

# What we know

- The failure is stochastic; sometimes one of the two TF builds (for Python 2.7 and 3.6) fails while the other passes. Most common case is that both fail, indicating that `P(failure)` is high.
-  There are cases where TF Py 2.7 fails while 3.6 passes and cases where 3.6 fails while 2.7 passes, so the issue is not specific to a Python version.
- We did not merge any changes that did not pass the CI checks, hence the failure is not caused by a change on our end in isolation. It is all or in part due to something that changed on the Travis side or in the build dependencies (e.g. TF).
- Timing variance for the TF builds has greatly increased as a result of this issue (now 20-40 min, before it was about 20-25 min).
- The issue is not due to large tests taking too long to run.
- [The issue is not due to multiprocessing tests](https://github.com/keras-team/keras/pull/10082).
- [The issue is not due to image preprocessing tests](https://github.com/keras-team/keras/pull/10088).
- [The issue is not due to timeout configuration of Travis](https://github.com/keras-team/keras/pull/10093).

# My opinion

The timing of the failure makes me think that the breaking change is the upgrade to TF 1.8 (the build installs TF via `pip install tensorflow`, which would have switched from 1.7 to 1.8 in the past few days).

1.8 might be using too much RAM or suffer from multiprocessing issues.

I will try reverting to TF 1.7 until we can figure it out.

# CC

@Dref360 @taehoonlee @DavidAriel

**Comment by fchollet** [comment]
Update: reverting to TF 1.7 fixes the build. https://github.com/keras-team/keras/pull/10101

**Comment by DavidAriel** [comment]
I think that it actually is a Travis CI timeout, but this is a symptom of a deeper performance issue you mentioned that causes the timeout to begin with. I wasn't able to change the Travis 10 minutes default timeout, but even if it was changed the TF rollback sounds reasonable.

**Comment by fchollet** [comment]
The problem isn't that the tests are taking too long to run, it's that execution is stalling (no output whatsoever) for over 10 min. Could it be that a single test has started taking over 10 min to run?

**Comment by DavidAriel** [comment]
Actually, I think that there is a test that takes more than 10 minutes and causing the timeout error:
`test_serialization` in the `keras/activations_test.py`

The reason I say that is after examining [this ](https://travis-ci.org/keras-team/keras/jobs/373899975) Travis log I noticed that only gw0 worker thread does all the work and gw1 get stuck. The last print the gw1 lets out before it enters the test that times out is that `test_saving_recurrent_layer_without_bias` has passed. 

The next test (that times out) for gw1 is `test_serialization` since files are ordered alphabetically, and it is the first in the file. Also, you can see no "passed" printed for this test. The rest of the tests in `keras/activations_test.py` and in the `tests` folder are done solely by gw0. 

After that, eventually Travis kills gw1 and fails the build.

**Comment by fchollet** [comment]
`test_serialization` takes a few seconds normally (with TF 1.7). What about TF 1.8 would cause it to stall? And is this indicative of an actual bug? Can you reproduce this locally?

**Comment by taehoonlee** [comment]
The `test_serialization` looks good in my local PC:

```
 $ pip show tensorflow
Name: tensorflow
Version: 1.8.0
Summary: TensorFlow helps the tensors flow
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: opensource@google.com
License: Apache 2.0
Location: /home/taehoonlee/miniconda2/envs/taehoonlee/lib/python2.7/site-packages
Requires: protobuf, tensorboard, absl-py, grpcio, enum34, six, termcolor, gast, wheel, backports.weakref, astor, mock, numpy
Required-by: 



 $ KERAS_BACKEND=tensorflow pytest tests/keras/activations_test.py -k test_serialization
=================================== test session starts ====================================
platform linux2 -- Python 2.7.13, pytest-3.5.0, py-1.5.3, pluggy-0.6.0 -- /home/taehoonlee/miniconda2/envs/taehoonlee/bin/python
cachedir: .pytest_cache
rootdir: /home/taehoonlee/keras, inifile: pytest.ini
plugins: pep8-1.0.6
collected 14 items / 13 deselected                                                         

tests/keras/activations_test.py::test_serialization PASSED                           [100%]

========================= 1 passed, 13 deselected in 0.80 seconds ==========================
```

**Comment by Dref360** [comment]
It's not a particular test imo.

For exemple : 
In this PR, https://travis-ci.org/keras-team/keras/jobs/373965739
tests/test_multiprocessing.py::test_multiprocessing_training_from_file 

is blocked.


Tf release note : https://github.com/tensorflow/tensorflow/releases
Looking at TF 1.8 release note. I don't see anything that would cause this issue.

* Update nsync synchronization library to avoid slow primitives on Linux.
* Low-level graph construction now calls the TensorFlow C API.

For info, the CPU optimizations are the same as 1.7.

**Comment by DavidAriel** [comment]
I agree that `test_multiprocessing_training_from_file` is blocked in the log you linked, I misread the log files I read, they show the same thing.
Specifically it is like so in the log file I linked in my previous comment, so I carefully assume it is like so in all build logs that failed.
So my current hypothesis is that the stalling test is `test_multiprocessing_training_from_file` and not `test_serialization`

@taehoonlee, did `test_multiprocessing_training_from_file` also run fine on your setup?

**Comment by Dref360** [comment]
As I said, it's not a particular test. It's purely random.
In this build.
https://travis-ci.org/keras-team/keras/jobs/373577762

It passes.

**Comment by DavidAriel** [comment]
OK I agree, it is random.
