### ISSUE TITLE
ImportError: cannot import name 'LinearNDInterpolator'

### ISSUE THREAD

**Issue by djokester** [keras-team/keras#10116]
Tried to import keras.
Faced the following error. 

> Python 3.6.3 |Anaconda, Inc.| (default, Oct 13 2017, 12:02:49) 
> [GCC 7.2.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import keras
> /home/fractaluser/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
>   from ._conv import register_converters as _register_converters
> Using TensorFlow backend.
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/fractaluser/anaconda3/lib/python3.6/site-packages/keras/__init__.py", line 7, in <module>
>     from . import datasets
>   File "/home/fractaluser/anaconda3/lib/python3.6/site-packages/keras/datasets/__init__.py", line 4, in <module>
>     from . import imdb
>   File "/home/fractaluser/anaconda3/lib/python3.6/site-packages/keras/datasets/imdb.py", line 8, in <module>
>     from ..preprocessing.sequence import _remove_long_seq
>   File "/home/fractaluser/anaconda3/lib/python3.6/site-packages/keras/preprocessing/__init__.py", line 1, in <module>
>     from . import image
>   File "/home/fractaluser/anaconda3/lib/python3.6/site-packages/keras/preprocessing/image.py", line 13, in <module>
>     import scipy.ndimage as ndi
>   File "/home/fractaluser/anaconda3/lib/python3.6/site-packages/scipy/ndimage/__init__.py", line 161, in <module>
>     from .filters import *
>   File "/home/fractaluser/anaconda3/lib/python3.6/site-packages/scipy/ndimage/filters.py", line 37, in <module>
>     from scipy.misc import doccer
>   File "/home/fractaluser/anaconda3/lib/python3.6/site-packages/scipy/misc/__init__.py", line 53, in <module>
>     from scipy.interpolate._pade import pade
>   File "/home/fractaluser/anaconda3/lib/python3.6/site-packages/scipy/interpolate/__init__.py", line 188, in <module>
>     from .ndgriddata import *
>   File "/home/fractaluser/anaconda3/lib/python3.6/site-packages/scipy/interpolate/ndgriddata.py", line 10, in <module>
>     from .interpnd import LinearNDInterpolator, NDInterpolatorBase, \
> ImportError: cannot import name 'LinearNDInterpolator'
>

**Comment by ramanpreet9** [comment]
Did you find a solution to this?  facing the same problem

**Comment by passion3394** [comment]
anyone solved the problem? I faced the same problem.

**Comment by esa-prakasa** [comment]
I got same problems as well, no answer yet
