### ISSUE TITLE
Missing several .md files in keras/docs/templates/layers

### ISSUE THREAD

**Issue by pcko1** [keras-team/keras#10114]
I am trying to build the documentation using the instructions under keras/docs and the build fails because the keras/docs/templates/layers is almost empty (lacks the md files for all layers).

Any fix?

tyvm
/t

**Comment by Dref360** [comment]
They are built automatically from the documentation. (in autogen.py)

**Comment by pcko1** [comment]
Thank you for the reply :)

I realized that autogen.py was complaining about line 559 because of `../` Unix syntax of the path. I have been running the file on a Windows machine, therefore this syntax is not recognized. After removing the `../` prefix, the script ran smoothly.

I hope this is useful for Windows users.

Best regards!
/t
