### ISSUE TITLE
model.fit_generator() combined with tf.profile.profile

### ISSUE THREAD

**Issue by pure-water** [keras-team/keras#10119]
I have a keras model  YOLO detection network with mobilenet as the backend which works y well. However, when I want to profile a bit further ( in terms of flops) for the training (fit_generator())   with tf.profile.profile 
. I would not find anywhere I can find the graph/session  to finish the following core. Or where I should put this code snippet in? 

```
run_metadata = tf.Runmeta()
    opts = tf.profiler.ProfileOptionBuilder.float_operation()    
    flops = tf.profiler.profile(g, run_meta=run_meta, cmd='op', options=opts)
```

**Comment by happyprotean** [comment]
@pure-water Hi, any solution now?
