### ISSUE TITLE
Possibility to make only specific (multiple) GPUs visible?

### ISSUE THREAD

**Issue by elmerehbi** [keras-team/keras#10115]
I have access to 5 GPUs. One of them is a different model than the other 4.

I tried using the following code to use only one GPU:
```
nb_gpu = '1'
from keras import backend as K
if 'tensorflow' == K.backend():
    import tensorflow as tf
    from keras.backend.tensorflow_backend import set_session
    config = tf.ConfigProto()
    config.gpu_options.allow_growth = True
    config.gpu_options.visible_device_list = nb_gpu
    #session = tf.Session(config=config)
    set_session(tf.Session(config=config))
```

Can I instead "hide" one GPU or maybe pass a list of GPUs to be visible?

**Comment by Dref360** [comment]
export CUDA_VISIBLE_DEVICES='GPUID'


This issue isn't related to a bug/enhancement/feature request or other accepted types of issue.

To ask questions, please see the following resources : 
* https://keras.io/
* https://keras.io/#support
* https://gitter.im/Keras-io/Lobby

Thanks!

If you think I made a mistake, please re-open this issue.
