### ISSUE TITLE
MobileNet Model  Input-tensor  input clarification

### ISSUE THREAD

**Issue by pure-water** [keras-team/keras#10126]
MobileNet has an input_tensor as one input which has an implication 4-d. I assume this corresponds to (N,H,W,C) . But I am a bit confused why the input layer will have to be one dimension less. E.g for the following code.  It works as it is now. 

```
     input_image = Input(shape=(input_size, input_size, 3)) //Real Input Tensor
     mobilenet = MobileNet(input_tensor=tf.placeholder('float32',shape=(1,224,224,3)),include_top=False,)(input_image)
```
But if I change the input tensor dim  to 4 d then it does not work. 

  `input_image=Input(shape=(1,input_size,input_size,3))` 

Any ideas why ?

**Comment by vkk800** [comment]
From the documentation of the `Input` layer (emphasis mine):

> shape: A shape tuple (integer), **not including the batch size**. For instance, shape=(32,) indicates that the expected input will be batches of 32-dimensional vectors.

It is working as intended and I don't think there's any ambiguity there.

**Comment by pure-water** [comment]
Thanks for that. Basically it clarifies the shape excluding the "batch size".
