### ISSUE TITLE
How to train multi-output models

### ISSUE THREAD

**Issue by GKalliatakis** [keras-team/keras#10120]
I am using the functional API to build **a model with multiple (five) outputs and the same input,** in order to simultaneously predict different properties of the data (images in my case). 

The summary of that model is the following (with capitals are the layers that have been added on top of the pre-trained VGG16) : 
![multi_output_model](https://user-images.githubusercontent.com/860417/39635810-7125c464-4fb6-11e8-82bd-ae9f5b9e82f4.png)

The shape of the data being fed to the CNN are the following:

```python
# input images
('x_train shape:', (23706, 224, 224, 3))

('Head_1 shape:', (23706, 26))
('Head_2 shape:', (23706,))
('Head_3 shape:', (23706,))
('Head_4 shape:', (23706,))
('Head_5 shape:', (23706,))
```

**When I put only a single output to my network the training is carried out without problems, but when all the outputs (or even 2 of them) are present, I am receiving the following error:** 

```
Traceback (most recent call last):
    history = model.fit_generator(datagen.flow(x_train, train_targets_list, batch_size=batch_size)
    .
    .
    .
    .

ValueError: could not broadcast input array from shape (23706,26) into shape (23706)
```

Any idea what I am doing wrong? 

Also is there any working example in the documentation that describes a similar case for multi-output models?

**Comment by maderafunk** [comment]
How's the output of your datagen.flow ? Are you sure that the shape of train_tragets_list is correct?

**Comment by GKalliatakis** [comment]
Following [this question on stackoverflow](https://stackoverflow.com/questions/50333532/load-images-and-annotations-from-csv-and-use-fit-generator-with-multi-output-mod/50406642#50406642), this is my working code for that (in case someone else is interested as well).

```python
def multi_output_generator(hdf5_file, nb_data, batch_size):
    """ Generates batches of tensor image data in form of ==> x, [y1, y2, y3, y4, y5] for use in a multi-output Keras model.

        # Arguments
            hdf5_file: the hdf5 file which contains the images and the annotations.
            nb_data: total number of samples saved in the array.
            batch_size: size of the batch to generate tensor image data for.

        # Returns
            A five-output generator.
    """

    batches_list = list(range(int(ceil(float(nb_data) / batch_size))))

    while True:

        # loop over batches
        for n, i in enumerate(batches_list):
            i_s = i * batch_size  # index of the first image in this batch
            i_e = min([(i + 1) * batch_size, nb_data])  # index of the last image in this batch

            x = hdf5_file["x_train"][i_s:i_e, ...]

            # read labels
            y1 = hdf5_file["y1"][i_s:i_e]
            y2 = hdf5_file["y2"][i_s:i_e]
            y3 = hdf5_file["y3"][i_s:i_e]
            y4 = hdf5_file["y4"][i_s:i_e]
            y5 = hdf5_file["y5"][i_s:i_e]

        yield x, [y1, y2, y3, y4 ,y5]
```

**Comment by GKalliatakis** [comment]
Another consideration are the different metrics that need to be used in the case of multi-output models. 
As written in Keras documenation 

> To specify different metrics for different outputs of a
                multi-output model, you could also pass a dictionary,
                such as `metrics={'output_a': 'accuracy'}` 


I am doing something similar with the following : 

```python
    metrics ={'output_a': 'crossentropy',
              'output_b': 'mse',
              'output_c': 'mse',
              'output_d': 'mse',
              'output_e': 'categorical_accuracy'}
```

**But when I start training the model, the overall accuracy is nowhere to be seen at the logs.** 
Any thoughts on this?

**Comment by mthnakdag** [comment]
I have same problem and  don't solve it. do you find any solution for this ?
