### ISSUE TITLE
keras nasnet pretrain weight imagenet gives "You are trying to load a weight file containing 533 layers into a model with 527 layers."

### ISSUE THREAD

**Issue by ayushmangupta1990** [keras-team/keras#10138]
from keras.applications import NASNetLarge

model = NASNetLarge(weights='imagenet')

ValueError: You are trying to load a weight file containing 533 layers into a model with 527 layers.

**Comment by trueProgrammer** [comment]
The same issue, I'm trying to do NASNetLarge(include_top=False, pooling="max").

**Comment by trueProgrammer** [comment]
Solution for VGG16 also helps and for NasNet
https://github.com/keras-team/keras/issues/8998
I added additional parameter model.load_weights(weights_file, **by_name=True**) in nasnet.py
and it works.
