### ISSUE TITLE
to_categorical num_values issue

### ISSUE THREAD

**Issue by mikkokotila** [keras-team/keras#10135]
Why does the below code return an error (below trace):

```
cols = [8, 4, 6, 3, 5, 9, 7, 2]
arr = to_categorical(cols, num_classes=len(cols))

```

The point here is that it does not accept any value below 10. Then if I add numbers to the list, for example so that there are 11 values, now it only accept 16. 

It seems useful to be able to actually decide the number of num_classes to be exactly the number of unique values in the array. 

```

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-217-223c25687e9e> in <module>()
      1 cols = [8, 4, 6, 3, 5, 9, 7, 2]
----> 2 arr = to_categorical(cols, num_classes=len(cols))

~/dev/a_test/lib/python3.6/site-packages/keras/utils/np_utils.py in to_categorical(y, num_classes)
     29     n = y.shape[0]
     30     categorical = np.zeros((n, num_classes), dtype=np.float32)
---> 31     categorical[np.arange(n), y] = 1
     32     output_shape = input_shape + (num_classes,)
     33     categorical = np.reshape(categorical, output_shape)

IndexError: index 8 is out of bounds for axis 1 with size 8
```

**Comment by mikkokotila** [comment]
ah ok I understood it already, it's done based on the max value so that it can be reversed back with argmax() ... my bad. Closing.

**Comment by amnahayajneh** [comment]
Can you explain what is the problem and how to fix it I am having the same error?
