### ISSUE TITLE
examples/mnist_cnn.py gives TypeError: only integer scalar arrays can be converted to a scalar index

### ISSUE THREAD

**Issue by Mukundan314** [keras-team/keras#10142]
- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

https://github.com/keras-team/keras/blob/master/examples/mnist_cnn.py

running it gives error

```TypeError: only integer scalar arrays can be converted to a scalar index```

**Comment by makeitai** [comment]
Which version of python were you using? Did this error occur before training or during training ?

**Comment by Mukundan314** [comment]
using Python 3.6.4

this occurs at line 31.
