### ISSUE TITLE
Batch_size scheduler: successful update of batch_size value in params, but no effect on training

### ISSUE THREAD

**Issue by iexarch** [keras-team/keras#10143]
I want to create a batch_size scheduler using callback on keras (in a manner similar to the learning rate scheduler, which I try to imitate in my code) but, although I'm able to change the batch_size in self.params, this does not seem to affect the actual batch_size implemented during training. Here is what I have tried: 

    class BatchSizeScheduler(Callback):
          """Batch size scheduler.
          # Arguments
            schedule: a function that takes an epoch index as input
            (integer, indexed from 0) and current batch size
            and returns a new batch size as output (int).
            verbose: int. 0: quiet, 1: update messages.
         """
        def __init__(self, schedule, verbose=1):
             super(BatchSizeScheduler, self).__init__()
             self.schedule = schedule
             self.verbose = verbose

         def on_epoch_begin(self, epoch, logs=None):
        
             
             print(self.params)
             bs = self.params['batch_size']
        
             try:  # new API
                bs = self.schedule(epoch, bs=bs)
             except TypeError:  # old API for backward compatibility
                bs = self.schedule(epoch)
             if not isinstance(bs, (int, np.int32, np.int64)):
                raise ValueError('The output of the "schedule" function '
                             'should be integer.')
             
             self.params['batch_size'] =  bs 

             if self.verbose > 0:
                 print('\nEpoch %05d: BatchSizeScheduler increasing batch '
                     'size to %s.' % (epoch + 1, self.params['batch_size']))

The problem is, this does not seem to update the batch size during training. I get no errors, the print(self.params) shows an increasing batch size, but I can tell from the training progress bar that the algorithm keeps using the same, initial batch size, despite the increased value in self.params. What's the cause of this? I suspect the way I update the parameter (self.params['batch_size']=bs) is wrong?

**Comment by zachmayer** [comment]
I just want to ping this issue: It'd be awesome to have a callback I could use to change batch sizes

**Comment by Dref360** [comment]
You should implement a keras.utils.Sequence with a variable batch size.

```python
class MySequence(keras.utils.Sequence):
    def __init__(self):
		self.batch_size = 10
		...
	def on_epoch_end(self):
		self.batch_size = 15

	def __getitem__(self,idx):
		...
	def __len__(self):
		...
```

**Comment by Dref360** [comment]
Yeah kinda.

An issue would be that the number of steps per epoch would stay the same. So the epoch would progressively get longer.

**Comment by zachmayer** [comment]
Could I halve the number of steps each epoch too?

**Comment by Dref360** [comment]
This is not currently possible.

________________________________
De : Zach Mayer <notifications@github.com>
Envoyé : 18 décembre 2018 09:35:26
À : keras-team/keras
Cc : Frédéric Branchaud-Charron; Comment
Objet : Re: [keras-team/keras] Batch_size scheduler: successful update of batch_size value in params, but no effect on training (#10143)

Could I halve the number of steps each epoch too?

**Comment by zachmayer** [comment]
Ok thanks!

**Comment by moorejee** [comment]
So, how can I change the batch size in training? For example, in the beginning 10 epochs, using a smaller batch size, in the remaining epochs, using a larger batch size. Is there a solution?

**Comment by zachmayer** [comment]
@moorejee train 1 epoch at a time, in a loop.  e.g.:

````python
for i in range(10):
    model.fit(x, y, batch_size = i*10001)
````

**Comment by moorejee** [comment]
@zachmayer OK, that is a trade-off method, thanks




> @moorejee train 1 epoch at a time, in a loop. e.g.:
> 
> ```python
> for i in range(10):
>     model.fit(x, y, batch_size = i*10001)
> ```

**Comment by maxpv** [comment]
> This is not currently possible.

How can I help with this?

Two papers supporting this method: [Don't Decay the Learning Rate, Increase the Batch Size](https://arxiv.org/abs/1711.00489) and [On Large-Batch Training for Deep Learning: Generalization Gap and Sharp Minima](https://arxiv.org/abs/1609.04836).

**Comment by Dref360** [comment]
This is quite simple, we just need to recompute the number of step after each epoch. (`len(sequence)` if the data is a Sequence otherwise stay the same.)
