### ISSUE TITLE
How directly get BestModel, not by saving?

### ISSUE THREAD

**Issue by shlpu** [keras-team/keras#10151]
As the **title** say, thank you!

### Checkpoint the weights for best model
from keras.callbacks import ModelCheckpoint

### checkpoint
filepath="weights.best.hdf5"
checkpoint = ModelCheckpoint(filepath, monitor='val_acc', verbose=1, save_best_only=True, mode='max')
callbacks = [checkpoint]

### Fit the model
model.fit(X, Y, validation_split, epochs, batch_size, callbacks=callbacks, verbose=0)

**Comment by achalshah20** [comment]
https://stackoverflow.com/

**Comment by shlpu** [comment]
Are there anybody could favor me? really thanks!

**Comment by shlpu** [comment]
Of course, we could save and load timely, the question is for the custom layer/model (not built-in), somwhat inconvenient, sorry for this feeling, really expect your reply.
