### ISSUE TITLE
Custom Layer : 'Node' object has no attribute 'output_masks'

### ISSUE THREAD

**Issue by Ahleroy** [keras-team/keras#10152]
I am trying to build a custom layer with Keras with Tensorflow backend in order to process images.

The process fails when using Keras but works with tensorflow (partially).

To understand better the issue I implemented an Identity layer and had the same issue :

'Node' object has no attribute 'output_masks'

Here is my code :

```python
from tensorflow.python.keras.layers import *
from tensorflow.python.keras import Model
from tensorflow.python.keras import  optimizers

import cv2

from keras.engine.topology import Layer # This Layer does not work

#
# USE KERAS IMPLEMENTED INTO TENSORFLOW TO MAKE IT WORK
#

#from tensorflow.python.keras._impl.keras.engine.base_layer import Layer

import numpy as np


class Identity(Layer):

    def __init__(self, **kwargs):

        super(Identity, self).__init__(**kwargs)

    def build(self, input_shape):

        super(Identity, self).build(input_shape)  # Be sure to call this somewhere!


    def call(self, x):

        return x


    def compute_output_shape(self, input_shape):

        return tuple(input_shape)




height = 12
width = 18
channels = 3

image_original = cv2.imread("./predict_base.png")
input_data = np.zeros((2, 12, 18, 3))
input_data[0] = image_original
input_data[1] = image_original

input_shape = (height, width, channels)

input = Input(shape=input_shape)
output = Identity()(input)

# add the model on top of the convolutional base
model = Model(inputs=input, outputs=output)

adam = optimizers.Adam()
model.compile(loss='mean_squared_error', optimizer=adam)

model.summary()
image = model.predict(input_data)

cv2.imshow("result", image[0])
cv2.waitKey(0)
```

Whereas the layer works when using directly tensorflow, it fails to compute the output shape correctly.

If I introduce an error in the output shape computation such as :

```python
def compute_output_shape(self, input_shape):
    output_shape = []
    output_shape[0] = input_shape[0]
    output_shape[1] = input_shape[1]
    output_shape[2] = input_shape[2]
    output_shape[3] = 4                     #Here is the error I added

    return tuple(output_shape)
```
The output shape is still the same, tensorflow does not compute the output correctly.
When creating a more complex layer the output becomes (None, None, None, 3)

Do you have any idea how to fix this ?

Many thanks.

**Comment by gavinfernandes2012** [comment]
For your output shape computation, I think tensorflow infers the output shape, while theano needs a function to calculate it for it. Moreover, I think the name of the compute_output_shape function should be get_shape, according to an error message I got before but I'm not sure.

I got past the error by using `class Identity(tf.layers.Layer):`  instead of  `class Identity(Layer):`
