### ISSUE TITLE
Verbose logging should go to STDERR

### ISSUE THREAD

**Issue by CMCDragonkai** [keras-team/keras#10165]
The stderr is meant to be used for debugging or other metadata. Whereas stdout should be used for the actual output of a program.

At the moment I am using `contextlib.redirect_stdout()` to redirect Keras logging to stderr.

**Comment by CMCDragonkai** [comment]
I just want to point out another issue.

The verbosity levels is currently 0, 1, and 2.

The 1 verbosity actually only really works if STDERR is connected to a real TTY.

If it's a pipe, it doesn't look good.

I think there needs also to be a switch to detect if STDERR is actually a pipe or tty, and adjust the logging accordingly. Basically if it's a pipe, we shouldn't be using special control characters to manipulate  adjust the progress bar. Instead every log message will need to be self-contained message telling the pipe what status of the training is at.

Right now since I'm using pipes, I'll need to switch to level 2 logging, but that loses per-batch status and only reports on the epoch.

**Comment by CyberShadow** [comment]
Looks like this regressed - `ProgbarLogger` is even documented to print to stdout, which is not great.
