### ISSUE TITLE
Error with deep_dream.py

### ISSUE THREAD

**Issue by abouquin** [keras-team/keras#10176]
Hi, 
I've been trying to run this 
keras/example/deep_dream.py 
but it does not work and gives me the following error:

```
Traceback (most recent call last):
  File "deep_dream.py", line 13, in <module>
    from keras.preprocessing.image import load_img, save_img, img_to_array
ImportError: cannot import name 'save_img'
```

because, well, the "save_img" function is not in keras.preprocessing.image any longer...
Obviously, if I skip loading the "save_img" function in the beginning, 
it all works fine until the last line...

```
..Loss value at 8 : 9.004611
Traceback (most recent call last):
  File "deep_dream.py", line 188, in <module>
    save_img(result_prefix + '.png', deprocess_image(np.copy(img)))
NameError: name 'save_img' is not defined
```

Is there a workaround to save the image?

**Comment by Dref360** [comment]
Update to the latest Keras version.

**Comment by abouquin** [comment]
I'm using keras '2.1.6'...

**Comment by Dref360** [comment]
This feature is available on master.
You can see the example for your version here : https://github.com/keras-team/keras/blob/2.1.6/examples/deep_dream.py

________________________________
De : Alexandre Bouquin <notifications@github.com>
Envoyé : 11 mai 2018 11:30:57
À : keras-team/keras
Cc : Frédéric Branchaud-Charron; State change
Objet : Re: [keras-team/keras] Error with deep_dream.py (#10176)


I'm using keras '2.1.6'...

**Comment by abouquin** [comment]
My bad... I was using an older version of the deep_dream.py code. 
It's working perfectly now! 
Thank you very much for pointing that out!
