### ISSUE TITLE
keras.utils.sequence loads entire dataset into memory

### ISSUE THREAD

**Issue by FirefoxMetzger** [keras-team/keras#10170]
https://github.com/keras-team/keras/blob/0ba6d95e768eb7a0d74a6fda3ea893e7fb2d7a67/keras/utils/data_utils.py#L372

Looking at `keras.utils.Sequence` as a possibility to feed a large dataset into a model I came across this line. I might misjudge the context, but it looks to me as if Sequence will pre-fetch the entire dataset (as batches) and then yield single batches from memory.

This makes me wonder, what is the intended use case of Sequence? I think there are more convenient ways to feed a dataset into Keras if it is in memory anyway. I wonder if this is a bug or intended behavior, but I can't tell from the information I have. Please advise.

I can always overwrite `__iter__` and create something that actually loads batches from disk, but since this is not recommended anywhere or talked about, I'm not sure if this is the intended approach.

**Comment by FirefoxMetzger** [comment]
Sorry for the noise, I figured it out. 

This is actually a generator comprehension, rather then a list comprehension or dict comprehension. I thought above line would be a "tuple comprehension" which doesn't exist in Python. You never stop learning...

As expected the generator comprehension returns a generator which yields the elements from the comprehension

    >>> (idx for idx in range(10))
    <generator object <genexpr> at 0x7fc7569a38c0>

so my world is sane again :)

**Comment by zh794390558** [comment]
Also sane for me.
