### ISSUE TITLE
TypeError: object of type 'ImageDataGenerator' has no len()

### ISSUE THREAD

**Issue by scstu** [keras-team/keras#10186]
I'm running to this issue and tried lots of things but it didn't work 
"TypeError: object of type 'ImageDataGenerator' has no len() "

my code is 

`train_generator = ImageDataGenerator(rescale=1. / 255, preprocessing_function=preprocess_input)
train_generator.flow_from_directory(train_data_dir,
                                  target_size=(224, 224),
                                  class_mode='categorical', 
                                  batch_size=32,
                                  shuffle=True)

validation_generator = ImageDataGenerator(rescale=1. / 255, preprocessing_function=preprocess_input)
validation_generator.flow_from_directory(validation_data_dir,
                                  target_size=(224, 224),
                                  class_mode='categorical', 
                                  batch_size=32)

model = vgg16_model(img_rows, img_cols, channel, num_classes)
history = model.fit_generator(
    train_generator,
    steps_per_epoch=nb_train_samples//32,
    epochs=nb_epoch,
    validation_data=validation_generator,
    validation_steps = nb_validation_samples//32)

`

Thank you for help!

**Comment by Dref360** [comment]
As stated in the documentation: https://keras.io/preprocessing/image/

flow_from_directory returns an Iterator. You need to feed this Iterator to fit_generator.

**Comment by smivv** [comment]
@Dref360 if you look at the code, that's exactly what he did.

I have the same problem, please look at this https://github.com/keras-team/keras/issues/12188

**Comment by jiayiliu** [comment]
In this page under fit_generator, it says: "if unspecified, will use the len(generator) as a number of steps."  However, it seems that the generator doesn't have len() defined.

**Comment by ytliang97** [comment]
@jiayiliu same question.

**Comment by ham952** [comment]
Got stuck with the same issue, i followed these steps and it worked for me, Hope this works for you too .. Have a Good day :) 


### Step 1 : Create data generator for validation set and training set

```
def validation_generator(test_csv, test_dir):
    
    df = pd.read_csv(test_csv)
    gen = keras.preprocessing.image.ImageDataGenerator(
                             rescale=1.4)
    return gen.flow_from_dataframe(dataframe=df,
                                   directory=test_dir,
                                   x_col='uuid',
                                   y_col='labels',
                                   batch_size=BATCH_SIZE,
                                   shuffle=False,
                                   seed=RANDOM_SEED,
                                   class_mode="categorical",
                                   target_size=(128, 128))


def augment_data(df, in_dir):

    df = df.replace({"labels" : damage_intensity_encoding })
    gen = keras.preprocessing.image.ImageDataGenerator(horizontal_flip=True,
                             vertical_flip=True,
                             width_shift_range=0.1,
                             height_shift_range=0.1,
                             rescale=1.4)
    return gen.flow_from_dataframe(dataframe=df,
                                   directory=in_dir,
                                   x_col='uuid',
                                   y_col='labels',
                                   batch_size=BATCH_SIZE,
                                   seed=RANDOM_SEED,
                                   class_mode="categorical",
                                   target_size=(128, 128))
```
### Step 2: Augument the training data and validation data
```
train_gen_flow = augment_data(df, train_data)
validation_gen = validation_generator(test_csv, test_data)
```
### Step 3: Finally compile model and apply fit operator 
    model.fit_generator(generator=train_gen_flow,
                        steps_per_epoch=steps,
                        epochs=NUM_EPOCHS,
                        workers=NUM_WORKERS,
                        use_multiprocessing=False,
                        class_weight=d_class_weights,
                        validation_data=validation_gen,
                        validation_steps = val_steps,
                        verbose=2)
