### ISSUE TITLE
Loading Fails with Nested Models - Minimum Example Provided

### ISSUE THREAD

**Issue by N-McA** [keras-team/keras#10180]
at cbadaf00e28f7fe42762b55f52294e3a7bb90515 the following example fails as shown
at a637960fab61b66848a36e6a5caf0204c155af01 it works
backend is tensorflow version 1.8.0

Looks very much like a logic bug.

```
from keras.models import Model
from keras.layers import BatchNormalization, Conv2D, Input

img_shape = (224, 224, 3)

# Nest level 0
img_input = Input(img_shape)
x = img_input
x = Conv2D(10, (3, 3))(x)
x = BatchNormalization()(x)
model_0 = Model(img_input, x)

# Nest level 1
img_input = Input(img_shape)
model_1 = Model(img_input, model_0(img_input))

# (Works)
test_model = model_1
test_model.save_weights('test.h5')
test_model.load_weights('test.h5')

# Nest level 2
img_input = Input(img_shape)
model_2 = Model(img_input, model_1(img_input))

# (Fails)
test_model = model_2
test_model.save_weights('test.h5')
test_model.load_weights('test.h5')
```

The error is `ValueError: axes don't match array` ; looks like an off-by-one.
Full output is on [pastebin](https://pastebin.com/NtgY7ivS)

I need this to work for a deadline, so will possibly not have time to investigate properly. @bzamecnik I believe you were altering the save/load code, so might be interested in the failure case.

**Comment by bzamecnik** [comment]
Interesting. What I see in debugger:
```
layer_weights_shape==(3, 3, 3, 10)
weights[0].shape==(10,)

 [w.shape for w in model_2.get_weights()]==[(3, 3, 3, 10), (10,), (10,), (10,), (10,), (10,)]
```

It seems that the first 4 weight matrices get cut off.
