### ISSUE TITLE
evaluate_generator save outputs?

### ISSUE THREAD

**Issue by kmader** [keras-team/keras#10200]
It would be useful to have an option for evaluate_generator to save and return the outputs. The primary use case for this is for making more useful diagnostic plots (like a confusion matrix for a classifier, or a scatter for a regressor) without having to re-run the evaluation/prediction.

**Comment by kmader** [comment]
so it looks like to implement this, it would either require changing the way `test_on_batch` works https://github.com/keras-team/keras/blob/24e7ac0756aeba06ce1cf7f7e72219a11b14b101/keras/engine/training.py#L1220 and making a `test_and_predict_function` or adding an additional line to predict_on_batch if an argument `save_predictions = True` in `evaluate_generator`. The later is less efficient as the model gets called twice

**Comment by vkk800** [comment]
My suggestion for this - which would be more work but neater - would be to 1) add support for callbacks to evaluate_generator (while calling `on_batch_begin()` and `on_batch_end()` on each evaluation step) and 2) add support for passing batch inputs and outputs to the callback functions. This would allow the user to write a custom callback to save, and also do whatever other operations they can think of, on the generator outputs and model predictions on each batch.

Any thoughts on this?
