### ISSUE TITLE
Is there a way like KERAS_DATA_FORMAT to switch format 

### ISSUE THREAD

**Issue by ghostplant** [keras-team/keras#10229]
Currently, many old examples will fail with NCHW format, and new examples are also possible fail with NHWC format. Changing `~/.keras/keras.json` manually is annoying since it is shared by different model with different preferences. I think something like KERAS_BACKEND for `image_data_format` is needed to conveniently switch format modes without changing users' code and shared config file.

**Comment by Dref360** [comment]
You mean keras.backend.set_image_data_format?

**Comment by ghostplant** [comment]
Does it work when added to application codes?
