### ISSUE TITLE
_nodes_by_depth attribute error when inheriting from Sequential model

### ISSUE THREAD

**Issue by yagotome** [keras-team/keras#10234]
I got exactly the same error as the one described in  #7096

Should I avoid inheriting `keras.models.Sequential`?

Versions I am using:
* Keras : 2.1.6
* tensorflow-gpu: 1.8.0

**Comment by AlexanderMath** [comment]
I got the same error with Keras 2.2 and tf-gpu 1.11, please see code below to reproduce: 

``from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD
import numpy as np

class SequentialChild(Sequential): 
	def __init__(self): 
		self._output_tensor_cache = [] # This list was not initialized as empty and also caused a bug. 
		super(SequentialChild, self).__init__()


model = SequentialChild()
model.add(Dense(10))
model.compile(optimizer=SGD())

model.predict(np.random.normal(0, 1, size=(64, 10)))``

**Comment by dominique-nshimyimana** [comment]
I got same error ...
