### ISSUE TITLE
ImportError                               Traceback (most recent call last) <ipython-input-1-30b843da4e08> in <module>()       1 # Plot ad hoc mnist instances ----> 2 from keras.datasets import mnist       3 import matplotlib.pyplot as plt       4 # load (downloaded if needed) the MNIST dataset       5 (X_train, y_train), (X_test, y_test) = mnist.load_data()  ImportError: No module named 'keras'

### ISSUE THREAD

**Issue by margi212** [keras-team/keras#10237]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [ ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [ ] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by deeiip** [comment]
You need to install `keras`
`$ pip install keras`

**Comment by margi212** [comment]
Thanks
It works.

**Comment by engenheirovitormartins** [comment]
I have a problem when importing:

[https://github.com/engenheirovitormartins/issueJupyter/issues/1#issue-691093923](url)

**Comment by zubairmd** [comment]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-060130db9ff2> in <module>
      5 from scipy.constants import mu_0
      6 # simpeg and related packages
----> 7 from pymatsolver import pardiso  as  solver
      8 from SimPEG import (mesh,maps,utils,DataMisfit,Regularization,Optimization,Inversion,Invproblem,Directives)
      9 from SimPEG.EM import TDEM

ImportError: cannot import name 'pardiso' from 'pymatsolver' (C:\Users\IITR\anaconda3\lib\site-packages\pymatsolver\__init__.p



please solve this error

**Comment by Antonytm** [comment]
> You need to install `keras` `$ pip install keras`

![image](https://user-images.githubusercontent.com/647813/167795474-79d7e29c-2dc6-48ea-99ce-1fd590e31a1b.png)

Same issue after Keras installation

**Comment by REALDEVELOPER9292** [comment]
I think you have to change kernel in top right.

**Comment by ademai27** [comment]
UnicodeDecodeError                        Traceback (most recent call last)
[<ipython-input-14-179c95165af5>](https://localhost:8080/#) in <cell line: 2>()
      1 #Mengimpor data set
----> 2 dataset = pd.read_csv('/content/Data Set Cuaca-set mentah.csv')
      3 dataset.head()

10 frames
/usr/local/lib/python3.10/dist-packages/pandas/_libs/parsers.pyx in pandas._libs.parsers.raise_parser_error()

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 2048: invalid continuation byte

**Comment by ruchitiwari20012** [comment]
# Test the traced model
total = 0
correct = 0
start = time.time()

with torch.no_grad():
    for data in testloader:
        images, labels = data
        images, labels = images.to(device), labels.to(device)
        
        outputs = model(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()
no wroking my code not able to tested on my testdataset on mnist with quantized model
