### ISSUE TITLE
ValueError: Error when checking target: expected dense_20 to have shape (3,) but got array with shape (22,)

### ISSUE THREAD

**Issue by rahuls321** [keras-team/keras#10239]
I m getting this error::   
Here is my code

#Create The model
def baseline_model():
    model = Sequential()
    model.add(Dense(4, activation='relu', input_shape=(4,)))
    model.add(Dense(3, activation='sigmoid'))
    #compile the model
    model.compile(optimizer='adam', loss='categorical_crossentropy',metrics = ['accuracy'] )
    return model
#in order to fit the model
estimator = KerasClassifier(build_fn=baseline_model, nb_epoch=200, verbose=0, batch_size=5)
kfold = KFold(n=len(X), n_folds=10, shuffle=True, random_state=seed)
results = cross_val_score(estimator, X, dummy_y, cv=kfold)
print("Accuracy: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))

**Comment by Rgui** [comment]
your activation is "sigmoid"- change that and it should work I think.
