### ISSUE TITLE
ConvLSTM2D reads the 5 dim inputs as 6 dim

### ISSUE THREAD

**Issue by hbake001** [keras-team/keras#10235]
I have the following code

```
 model = Sequential()
 model.add(ConvLSTM2D(lstm_out, dropout=0.2, input_shape=x_train.shape, kernel_size=(5, 1), return_sequences=0))
 
```

where x_train.shape=(668, 677, 1, 1, 676)

Keras gave me the following error: 
`ValueError: Input 0 is incompatible with layer conv_lst_m2d_4: expected ndim=5, found ndim=6
`

I tried to input a 4 dimensional like this: 

`  model.add(ConvLSTM2D(lstm_out, dropout=0.2, input_shape=features.shape, kernel_size=(5, 1), return_sequences=0))`

where
`features.shape = (668, 677, 1, 676)
`
However, an error showed up saying: 
`ValueError: Error when checking input: expected conv_lst_m2d_1_input to have 5 dimensions, but got array with shape (668, 677, 1, 676)`

when executing: 
```
history = model.fit(x_train, y_train,
                    batch_size=batch_size,
                    epochs=epochs,
                    verbose=1,
                    validation_data=(x_test, y_test),
                    callbacks=[
                        EarlyStopping(monitor='val_loss',
                                      min_delta=0,
                                      patience=10,
                                      verbose=0, mode='auto')]
                    )
```

where x_train.shape = features.shape

keras.__version__
Out[5]: '2.1.5'

**Comment by helloworldlxb** [comment]
When x_train.shape=(668,677,1,1,676), the requirement of tha layer is satisfied. But you input data does not fit the shape because there must be a dimension for batch size. That is to say, you x_train should with shape (batch_size, 668, 667, 1, 1, 676)
