### ISSUE TITLE
How to reshape my dataset for RNN/LSTM model?

### ISSUE THREAD

**Issue by deerdodo** [keras-team/keras#10243]
My dataset is 1415684 for training and 502203 for testing with 6 features ..
A sample of my dataset is as follows

> (patient number, time in mill/sec., normalization of X Y and Z, kurtosis, skewness, pitch, roll and yaw, label) respectively.
> 
> 1,15,-0.248010047716,0.00378335508419,-0.0152548459993,-86.3738760481,0.872322164158,-3.51314800063,0
> 
> 1,31,-0.248010047716,0.00378335508419,-0.0152548459993,-86.3738760481,0.872322164158,-3.51314800063,0
> 
> 1,46,-0.267422664673,0.0051143782875,-0.0191247001961,-85.7662354031,1.0928406847,-4.08015176908,0
> 
> 1,62,-0.267422664673,0.0051143782875,-0.0191247001961,-85.7662354031,1.0928406847,-4.08015176908,0 

so i need to reshape it for an RNN/LSTM model ..
i have tried the following code..

train = np.loadtxt("featwithsignalsTRAIN.txt", delimiter=",")
test = np.loadtxt("featwithsignalsTEST.txt", delimiter=",")

x_train = train[:,[2,3,4,5,6,7]]
x_test = test[:,[2,3,4,5,6,7]]
y_train = train[:,8]
y_test = test[:,8]

```
model = Sequential()
model.add(LSTM(30, return_sequences=True,
               input_shape=(1, 6)))  # returns a sequence of vectors of dimension 30
model.add(LSTM(30, return_sequences=True))  # returns a sequence of vectors of dimension 30
model.add(LSTM(30))  # return a single vector of dimension 30
model.add(Dense(1, activation='softmax'))

model.compile(loss='binary_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

model.fit(x_train, y_train, batch_size = 200, epochs = 20, verbose = 1)
```
but it gives me the following error

> Error when checking input: expected lstm_1_input to have 3 dimensions, but got array with shape (1415684, 6)

so i tried to reshape my dataset .. so i type the following code
`x_train = x_train.reshape((1415684,5,6))`

but it gives me the following error 

> x_train = x_train.reshape((1415684,5,6))
> ValueError: total size of new array must be unchanged

**Comment by deeiip** [comment]
Although my understanding is that the question is better suited for stackoverflow. You need to do
`x_train = x_train.reshape((1415684,1,6))`
or
`x_train = x_train.reshape((1415684,6,1))`
as per your input shape is wheather, `(1,6)` or `(6,1)`
