### ISSUE TITLE
keras installed by conda has no keras.utils.Sequence?

### ISSUE THREAD

**Issue by xiaohk** [keras-team/keras#10249]
I use miniconda to install keras as below:

```
conda create --yes --name project python=3.6 tensorflow scikit-learn scikit-image libtiff pandas keras h5py
```

I called `keras.utils.Sequence` in Python, then there is an error:

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'keras.utils' has no attribute 'Sequence'

The version of Keras is 2.0.5.

**Comment by JamesTrick** [comment]
Hi @xiaohk 

You're using a slightly outdated version of Keras, here's the code that I ran to re-produce:


```python
pip install keras=2.0.5

import keras; print(keras.__version__)

> 2.0.5

seq = keras.utils.Sequence

>Traceback (most recent call last):
>File "", line 1, in 
>AttributeError: module 'keras.utils' has no attribute 'Sequence'
```

From here, you have two options. I would recommend updating Keras, `pip install keras --upgrade`, you'll then have no issues importing the `keras.utils.Sequence`

Alternatively, based off this issue #3726, it looks as though Sequence used to be in the Preprocessing module in previous versions, so following those steps worked for me when testing your issue.

Let me know if you have any other questions.

Cheers
James

**Comment by xiaohk** [comment]
@JamesTrick Thank you so much! Yeah it works now after using pip to install keras. I guess the conda's keras' version is outdated 😅

**Comment by VanitarNordic** [comment]
Now, You can use `conda install -c hesi_m keras` to install the latest version of **Keras (2.2.0)** and **Tensorflow(1.8.0)** for you.
