### ISSUE TITLE
Use intermediate layer values to fit model?

### ISSUE THREAD

**Issue by liamhawkins** [keras-team/keras#10245]
I tried posting this to [stackoverflow](https://stackoverflow.com/questions/50381504/use-intermediate-layer-values-to-fit-model), but didn't recieve a response.

I am trying to train an autoencoder whose input is some dense features concatenated with the output of an embedding layer. I therefore want to use the output of the concatenation layer for both the input and the labels to train the autoencoder:

```
# Inputs
dense = Input(shape=(train_dense_scaled.shape[1],))
sequences = Input(shape=(train_embed.shape[1],))

# Embedding layer
embed = Embedding(vocab_size, 20, input_length=num_embed_cols)(sequences)
flatten = Flatten()(embed)

ae_input = concatenate([dense, flatten])    

# Autoencoder
e_128 = Dense(units=128, activation='relu', kernel_initializer=initializer)(ae_input)
e_64 = Dense(units=64, activation='relu', kernel_initializer=initializer)(e_128)
decoded = Dense(units=128, activation='relu', kernel_initializer=initializer)(e_64)

model = Model(inputs=[sequences,dense], outputs=decoded)
model.compile(loss='mse', optimizer='adam')
model.fit(x=[train_dense_scaled,train_embed], y=ae_input, epochs=200, batch_size=128)
```

I get the following error:

```
AttributeError                            Traceback (most recent call last)
<ipython-input-25-f29037b9f7ab> in <module>()
---> 50 model.fit(x=[train_dense_scaled,train_embed], y=ae_inputs, epochs=200, batch_size=128)
...
AttributeError: 'Tensor' object has no attribute 'ndim'
```

The output of the concatenation layer `ae_input` is the input into the autoencoder, and thus what I want to use as labels to train the model. I'm assuming this is where I'm going wrong and not properly feeding the output of this intermediate layer to the `model.fit()` method. Also I am using the tensorflow backend.

**Comment by mathgaming** [comment]
I have the same problem and have been looking for a solution for a few hours. I have sadly not been able to find one. It have been a while since you asked the question. Did you manage to find a solution?

**Comment by liamhawkins** [comment]
@mathgaming It has been a while, but I believe I didn't end up finding a solution
