### ISSUE TITLE
Face recognition in keras on flask server

### ISSUE THREAD

**Issue by hunnain** [keras-team/keras#10253]
Hi
I want to build an Face recognition app AI based on web.Firstly when user come to signup then webcam open and model train automatically of his image and his given name and then user goes to login then webcam open and they can verify that this user is exist means they recognize his face.so please please help me i want to build this app on keras  in only 4 to 5 days please please help me iam very beginner in keras help me.

**Comment by JamesTrick** [comment]
Hi Hunnain

I think this question might be more suitable for StackOverflow generally.

To point you in the right direction, Keras.io has a blog post that relates to building a [Flask REST API around a Keras model](https://blog.keras.io/building-a-simple-keras-deep-learning-rest-api.html), which you can call from your website. That blog post will probably get you off to a good start.

Keras models can be saved and loaded in `.h5` format, steps in the documentation [here](https://keras.io/getting-started/faq/#how-can-i-save-a-keras-model)

Best of luck!

James
