### ISSUE TITLE
"AttributeError: 'int' object has no attribute 'dtype'" when using clipnorm option and TensorFlow backend

### ISSUE THREAD

**Issue by MarcelWiedenmann** [keras-team/keras#10251]
I ran into the above problem while fitting a model which was compiled to use an optimizer that uses `clipnorm` for gradient clipping. The problem only occurs when using TensorFlow.

Here's the traceback:
> Traceback (most recent call last):
  File "clipnorm_issue.py", line 21, in <module>
    m.fit(x,y)
  File "/home/..../keras/engine/training.py", line 1008, in fit
    self._make_train_function()
  File "/home/..../keras/engine/training.py", line 497, in _make_train_function
    loss=self.total_loss)
  File "/home/..../keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/..../keras/optimizers.py", line 367, in get_updates
    grads = self.get_gradients(loss, params)
  File "/home/..../keras/optimizers.py", line 86, in get_gradients
    norm = K.sqrt(sum([K.sum(K.square(g)) for g in grads]))
  File "/home/..../keras/backend/tensorflow_backend.py", line 1473, in sqrt
    zero = _to_tensor(0., x.dtype.base_dtype)
AttributeError: 'int' object has no attribute 'dtype'

And here's a snippet to reproduce the problem:
```
import os
os.environ['KERAS_BACKEND'] = 'tensorflow'

from keras.models import Sequential
from keras.layers import Lambda
from keras.optimizers import Adadelta
import numpy as np

m = Sequential()
# Training such a network does not make sense of course,
# but this causes the error immediately.
m.add(Lambda(lambda x : x, input_shape=[1]))

# Clipnorm enabled.
m.compile(optimizer=Adadelta(clipnorm=1.), loss='mse', metrics=['acc'])

x = np.random.rand(100)
y = np.random.rand(100)

# Calling fit leads to an exception being raised.
m.fit(x,y)
```

* * *
- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] ~~If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps~~

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by MatteoGambara** [comment]
Hi Marcel,
I got the same problem. Did you find a solution?

**Comment by MarcelWiedenmann** [comment]
Hi Matteo, unfortunately no. I didn't really pursue that any further after creating this issue, since using clipnorm fortunately wasn't essential for my undertaking. Sorry to hear that this is still a problem a year later.

**Comment by philipperemy** [comment]
I have the same issue too. It seems related to clipnorm.

**Comment by philipperemy** [comment]
Ok it turned out that I made a mistake in my graph. I was feeding the input at the beginning and also lower in the graph. So it was my mistake, although I agree that the error could be more explicit.
