### ISSUE TITLE
Keras CPU Usage

### ISSUE THREAD

**Issue by Naghipourfar** [keras-team/keras#10250]
Hi, I have written a sample MLP code with TensorFlow. When I ran the code, it use just 1 core of my CPU to be trained. I wrote that sample with Keras and checked CPU Statistics. Keras was using must of my CPU cores. How is that? 
Thanks

**Comment by deeiip** [comment]
Keras should use configuration of your backend e.g. `Theano` or `tensorflow`. So you should make sure your backend is configured to use GPU or whatever you want

**Comment by Naghipourfar** [comment]
I was wondering how keras backend is using more than 1 core while, if you write code on your own, it'll use just one core. I don't have any GPU to be used.
