### ISSUE TITLE
Issue while loading Tiff File with load_img()

### ISSUE THREAD

**Issue by Jodahr** [keras-team/keras#10268]
Hello everyone, 

I have a problem while loading a certain tiff image file. The Tiff file dan be downloaded here: 
https://www.dropbox.com/s/0lw6i0yc9xmctrn/SOE4630.tif?dl=0

When I try to load it with the command:
`from keras.preprocessing.image import load_img`

`load_img(path_to_tiff)`

I get the following error: 

------ERROR--------

ValueErrorTraceback (most recent call last)
<ipython-input-4-dd8f18b28a08> in <module>()
----> 1 load_img('/opt/hdp/share/data/wertermittlung/newData/Ausbau/train/ausbau/GT12113.tif')

/opt/hdp/anaconda2/lib/python2.7/site-packages/keras/preprocessing/image.py in load_img(path, grayscale, target_size, interpolation)
    351     else:
    352         if img.mode != 'RGB':
--> 353             img = img.convert('RGB')
    354     if target_size is not None:
    355         width_height_tuple = (target_size[1], target_size[0])

/opt/hdp/anaconda2/lib/python2.7/site-packages/PIL/Image.pyc in convert(self, mode, matrix, dither, palette, colors)
    855                 return self.copy()
    856 
--> 857         self.load()
    858 
    859         if matrix:

/opt/hdp/anaconda2/lib/python2.7/site-packages/PIL/TiffImagePlugin.pyc in load(self)
   1009         if self.use_load_libtiff:
   1010             return self._load_libtiff()
-> 1011         return super(TiffImageFile, self).load()
   1012 
   1013     def load_end(self):

/opt/hdp/anaconda2/lib/python2.7/site-packages/PIL/ImageFile.pyc in load(self)
    202                                       args, self.decoderconfig)
    203                 seek(offset)
--> 204                 decoder.setimage(self.im, extents)
    205                 if decoder.pulls_fd:
    206                     decoder.setfd(self.fp)

ValueError: tile cannot extend outside image
----- ERROR -----

However, I can easily load the image by using the libtiff library. I guess the problem is the shape of the tiff file, which is (x,y,4). When I drop the fourth dimension to get a shape of (x,y,3) I can pass it to Keras. Usually the fourth dimension contains something like an alpha for transparency or other further information. Is there a way to get native support in Keras for such images?

I get a similar error message in Keras with Python 3.

Cheers,

Marcel

**Comment by Jodahr** [comment]
Hello,

actually since Keras uses PIL, I guess I should have posted it on the PIL page. However, I found out that I can load the image if I use ImageMagick:

$ convert in.tiff out.tiff

The outout of identify looks similar. Only this has changed:

old:
Properties:
    date:create: 2018-05-24T16:32:37+02:00
    date:modify: 2018-05-24T16:32:07+02:00
    signature: b24dd796543cc9a1be794ed31153c417cf3f32f460fcbc6ca8a7dc30171ceb92
    tiff:alpha: unspecified
    tiff:endian: lsb
    tiff:photometric: RGB
  Artifacts:
    filename: SOE4630.tif
    verbose: true
  Tainted: False
  Filesize: 705KB
  Number pixels: 442K
  Pixels per second: 11.04MB
  User time: 0.040u
  Elapsed time: 0:01.040
  Version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org

new:
  Properties:
    date:create: 2018-05-24T17:03:55+02:00
    date:modify: 2018-05-24T17:03:55+02:00
    signature: b24dd796543cc9a1be794ed31153c417cf3f32f460fcbc6ca8a7dc30171ceb92
    tiff:alpha: unassociated
    tiff:endian: lsb
    tiff:photometric: RGB
    tiff:rows-per-strip: 909
  Artifacts:
    filename: test.tif
    verbose: true
  Tainted: False
  Filesize: 478KB
  Number pixels: 442K
  Pixels per second: 14.73MB
  User time: 0.030u
  Elapsed time: 0:01.030
  Version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org

Maybe it the tiff alpha?

Cheers,

Marcel

**Comment by vkk800** [comment]
I tried loading your example image using PIL and I find that it is not an RGBA image, but an RGBX image, which seems to mean "RGB image with padding" (something that I have not encountered before). Opening the image with some other image manipulation library (I used opencv) and saving it as an RGBA image seems to fix the issue. The `convert()` function in PIL is not able to to do the job for whatever reason. This suggests that we are looking at a bug in PIL. I suggest you try submitting a bug report to them.

In the meantime, we should probably work around this by giving the user an informative error message if they try to load an RGBX image.

**Comment by Jodahr** [comment]
Hello, thanks for your answer. I will open the issue in PIL. BTW, I got the image from a GIS program. Actually, I am not interested in the X dimension. Hence, I used libtiff (which can load the image) as a workaround for a MonkeyPatch.

Cheers,

Marcel

**Comment by Jodahr** [comment]
Hm, actually. Keras is using PIL not pillow, right? Do you know the exact github project where I should open the issue?

Thanks in advance and cheers,

Marcel
