### ISSUE TITLE
What is the LSTM structure used in Keras?

### ISSUE THREAD

**Issue by zhjmcjk** [keras-team/keras#10272]
Refer to this article：
[LSTM: A Search Space Odyssey](https://arxiv.org/pdf/1503.04069.pdf?utm_content=buffereddc5&utm_medium=social&utm_source=plus.google.com&utm_campaign=buffer)

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short

>

**Comment by deeiip** [comment]
I think you can get all the details about LSTM cell from 
[keras/layers/recurrent.py](https://github.com/keras-team/keras/blob/49f5b931410bc2e56378f20a15e8ac919e0efb88/keras/layers/recurrent.py#L1689) file.
And LSTM layer is defined [here](https://github.com/keras-team/keras/blob/49f5b931410bc2e56378f20a15e8ac919e0efb88/keras/layers/recurrent.py#L1957)

**Comment by zhjmcjk** [comment]
I'm sorry to bother you. Is it as described in this picture?
[LSTM](https://i.stack.imgur.com/RHNrZ.jpg)

**Comment by wwmmqq** [comment]
@zhjmcjk  may this question  #10179  can help you, which translated the tensorflow's lstm to keras's lstm.

**Comment by KuzMenachem** [comment]
@zhjmcjk It appears to work exactly as in the picture, with the exception that the sigmoids are by default replaced by "hard sigmoids" which are slightly different, simpler to compute version of sigmoids
