### ISSUE TITLE
ruby

### ISSUE THREAD

**Issue by letarg0** [keras-team/keras#10283]
When keras ruby?

**Comment by dynamicwebpaige** [comment]
I don't believe that Ruby bindings are on the roadmap for Keras, but a TensorFlow Ruby API was created a while back.

- [`tensorflow.rb` GitHub repo](https://github.com/somaticio/tensorflow.rb)
- [TensorFlow Ruby API Medium post](https://medium.com/@Arafat./introducing-tensorflow-ruby-api-e77a477ff16e)
