### ISSUE TITLE
I can get flatten input size, however, the output size is unknown.

### ISSUE THREAD

**Issue by FrancisYizhang** [keras-team/keras#10297]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [Y] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [Y] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [N] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [Y] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

I run [cifar10_resnet.py](https://github.com/keras-team/keras/blob/master/examples/cifar10_resnet.py), I want to get flatten layer output size but the the result is unknown.
```
model.get_layer('flatten_1').output
<tf.Tensor 'flatten_1/Reshape:0' shape=(?, ?) dtype=float32>

```
however, the input is known
```
model.get_layer('flatten_1').input
<tf.Tensor 'average_pooling2d_1/AvgPool:0' shape=(?, 1, 1, 64) dtype=float32>
```

Is it bug?
@fchollet

**Comment by Dref360** [comment]
It's not a bug. We do not compute the actual shape in a Flatten layer. You can compute it yourself with a Reshape layer.

Note : Dont @ people please.
