### ISSUE TITLE
Multi GPU Model with Checkpoints: TypeError: cannot serialize '_io.TextIOWrapper' object

### ISSUE THREAD

**Issue by ghost** [keras-team/keras#10295]
Hello,

I am using Keras 2.1.5 and TensorFlow 1.7.0.  (Cannot upgrade to 1.8.0)

I am trying to run a multiple GPU model

    # Define a general purpose convolutional layer layer
    def Conv2DReluBatchNorm(num_filters, filter_width, filter_height, inputs):
        return Activation('relu')\
            (BatchNormalization()
             (Convolution2D(num_filters, (filter_width, filter_height), padding='same')
              (inputs)))

    inputs = Input(shape=(250, 250, 3))

    conv1 = Conv2DReluBatchNorm(32, 5, 5, inputs)
    maxp1 = AveragePooling2D((2, 2), strides=(2, 2))(conv1)

    conv2 = Conv2DReluBatchNorm(16, 5, 5, maxp1)
    maxp2 = AveragePooling2D((2, 2), strides=(2, 2))(conv2)

    conv3 = Conv2DReluBatchNorm(8, 5, 5, maxp2)
    maxp3 = AveragePooling2D((2, 2), strides=(2, 2))(conv3)

    conv4 = Conv2DReluBatchNorm(4, 5, 5, maxp3)
    maxp4 = AveragePooling2D((2, 2), strides=(2, 2))(conv4)

    conv5 = Conv2DReluBatchNorm(4, 5, 5, maxp4)
    avpl5 = AveragePooling2D((2, 2), strides=(2, 2))(conv5)

    flat1 = Flatten()(avpl5)

    dens1 = Dense(128, activation='relu')(flat1)

    drop2 = Dropout(0.05)(dens1)
    dens2 = Dense(2, activation='softmax')(drop2)

    model = Model(inputs, dens2)

    model = multi_gpu_model(model, gpus=4)

    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

But when I train

     model.fit(training_images, training_labels,
          epochs=5,
          batch_size=64,
          shuffle=True,
          validation_data=(validation_images, validation_labels),
          callbacks=[ModelCheckpoint(filepath="face_detector.h5", save_best_only=True, 
                                     monitor='val_loss', mode='min')])
 
I get this error, which seems checkpoint related.  Do I need to do something different with the checkpointing?

      TypeError                                 Traceback (most recent call last)
      <ipython-input-374-85e2316f74b0> in <module>()
          5           validation_data=(validation_images, validation_labels),
          6           callbacks=[ModelCheckpoint(filepath="face_detector.h5", save_best_only=True, 
    ----> 7                                      monitor='val_loss', mode='min')])
    
    /usr/local/lib/python3.5/dist-packages/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, **kwargs)
       1703                               initial_epoch=initial_epoch,
       1704                               steps_per_epoch=steps_per_epoch,
    -> 1705                               validation_steps=validation_steps)
       1706 
       1707     def evaluate(self, x=None, y=None,
    
    /usr/local/lib/python3.5/dist-packages/keras/engine/training.py in _fit_loop(self, f, ins, out_labels, batch_size, epochs, verbose, callbacks, val_f, val_ins, shuffle, callback_metrics, initial_epoch, steps_per_epoch, validation_steps)
       1253                             for l, o in zip(out_labels, val_outs):
       1254                                 epoch_logs['val_' + l] = o
    -> 1255             callbacks.on_epoch_end(epoch, epoch_logs)
       1256             if callback_model.stop_training:
       1257                 break
    
    /usr/local/lib/python3.5/dist-packages/keras/callbacks.py in on_epoch_end(self, epoch, logs)
         75         logs = logs or {}
         76         for callback in self.callbacks:
    ---> 77             callback.on_epoch_end(epoch, logs)
         78 
         79     def on_batch_begin(self, batch, logs=None):
    
    /usr/local/lib/python3.5/dist-packages/keras/callbacks.py in on_epoch_end(self, epoch, logs)
        445                             self.model.save_weights(filepath, overwrite=True)
        446                         else:
    --> 447                             self.model.save(filepath, overwrite=True)
        448                     else:
        449                         if self.verbose > 0:
    
    /usr/local/lib/python3.5/dist-packages/keras/engine/topology.py in save(self, filepath, overwrite, include_optimizer)
       2578         """
       2579         from ..models import save_model
    -> 2580         save_model(self, filepath, overwrite, include_optimizer)
       2581 
       2582     def save_weights(self, filepath, overwrite=True):
    
    /usr/local/lib/python3.5/dist-packages/keras/models.py in save_model(model, filepath, overwrite, include_optimizer)
        109         f.attrs['model_config'] = json.dumps({
        110             'class_name': model.__class__.__name__,
    --> 111             'config': model.get_config()
        112         }, default=get_json_type).encode('utf8')
        113 
    
    /usr/local/lib/python3.5/dist-packages/keras/engine/topology.py in get_config(self)
       2419             model_outputs.append([layer.name, new_node_index, tensor_index])
       2420         config['output_layers'] = model_outputs
    -> 2421         return copy.deepcopy(config)
       2422 
       2423     @classmethod
    
    /usr/lib/python3.5/copy.py in deepcopy(x, memo, _nil)
        153     copier = _deepcopy_dispatch.get(cls)
        154     if copier:
    --> 155         y = copier(x, memo)
        156     else:
        157         try:
    
    /usr/lib/python3.5/copy.py in _deepcopy_dict(x, memo)
        241     memo[id(x)] = y
        242     for key, value in x.items():
    --> 243         y[deepcopy(key, memo)] = deepcopy(value, memo)
        244     return y
        245 d[dict] = _deepcopy_dict
    
    /usr/lib/python3.5/copy.py in deepcopy(x, memo, _nil)
        153     copier = _deepcopy_dispatch.get(cls)
        154     if copier:
    --> 155         y = copier(x, memo)
        156     else:
        157         try:
    
    /usr/lib/python3.5/copy.py in _deepcopy_list(x, memo)
        216     memo[id(x)] = y
        217     for a in x:
    --> 218         y.append(deepcopy(a, memo))
        219     return y
        220 d[list] = _deepcopy_list
    
    /usr/lib/python3.5/copy.py in deepcopy(x, memo, _nil)
        153     copier = _deepcopy_dispatch.get(cls)
        154     if copier:
    --> 155         y = copier(x, memo)
        156     else:
        157         try:
    
    /usr/lib/python3.5/copy.py in _deepcopy_dict(x, memo)
        241     memo[id(x)] = y
        242     for key, value in x.items():
    --> 243         y[deepcopy(key, memo)] = deepcopy(value, memo)
        244     return y
        245 d[dict] = _deepcopy_dict
    
    /usr/lib/python3.5/copy.py in deepcopy(x, memo, _nil)
        153     copier = _deepcopy_dispatch.get(cls)
        154     if copier:
    --> 155         y = copier(x, memo)
        156     else:
        157         try:
    
    /usr/lib/python3.5/copy.py in _deepcopy_dict(x, memo)
        241     memo[id(x)] = y
        242     for key, value in x.items():
    --> 243         y[deepcopy(key, memo)] = deepcopy(value, memo)
        244     return y
        245 d[dict] = _deepcopy_dict
    
    /usr/lib/python3.5/copy.py in deepcopy(x, memo, _nil)
        153     copier = _deepcopy_dispatch.get(cls)
        154     if copier:
    --> 155         y = copier(x, memo)
        156     else:
        157         try:
    
    /usr/lib/python3.5/copy.py in _deepcopy_tuple(x, memo)
        221 
        222 def _deepcopy_tuple(x, memo):
    --> 223     y = [deepcopy(a, memo) for a in x]
        224     # We're not going to put the tuple in the memo, but it's still important we
        225     # check for it, in case the tuple contains recursive mutable structures.
    
    /usr/lib/python3.5/copy.py in <listcomp>(.0)
        221 
        222 def _deepcopy_tuple(x, memo):
    --> 223     y = [deepcopy(a, memo) for a in x]
        224     # We're not going to put the tuple in the memo, but it's still important we
        225     # check for it, in case the tuple contains recursive mutable structures.
    
    /usr/lib/python3.5/copy.py in deepcopy(x, memo, _nil)
        153     copier = _deepcopy_dispatch.get(cls)
        154     if copier:
    --> 155         y = copier(x, memo)
        156     else:
        157         try:
    
    /usr/lib/python3.5/copy.py in _deepcopy_tuple(x, memo)
        221 
        222 def _deepcopy_tuple(x, memo):
    --> 223     y = [deepcopy(a, memo) for a in x]
        224     # We're not going to put the tuple in the memo, but it's still important we
        225     # check for it, in case the tuple contains recursive mutable structures.
    
    /usr/lib/python3.5/copy.py in <listcomp>(.0)
        221 
        222 def _deepcopy_tuple(x, memo):
    --> 223     y = [deepcopy(a, memo) for a in x]
        224     # We're not going to put the tuple in the memo, but it's still important we
        225     # check for it, in case the tuple contains recursive mutable structures.
    
    /usr/lib/python3.5/copy.py in deepcopy(x, memo, _nil)
        180                             raise Error(
        181                                 "un(deep)copyable object of type %s" % cls)
    --> 182                 y = _reconstruct(x, rv, 1, memo)
        183 
        184     # If is its own copy, don't memoize.
    
    /usr/lib/python3.5/copy.py in _reconstruct(x, info, deep, memo)
        295     if state is not None:
        296         if deep:
    --> 297             state = deepcopy(state, memo)
        298         if hasattr(y, '__setstate__'):
        299             y.__setstate__(state)
    
    /usr/lib/python3.5/copy.py in deepcopy(x, memo, _nil)
        153     copier = _deepcopy_dispatch.get(cls)
        154     if copier:
    --> 155         y = copier(x, memo)
        156     else:
        157         try:
    
    /usr/lib/python3.5/copy.py in _deepcopy_dict(x, memo)
        241     memo[id(x)] = y
        242     for key, value in x.items():
    --> 243         y[deepcopy(key, memo)] = deepcopy(value, memo)
        244     return y
        245 d[dict] = _deepcopy_dict
    
    /usr/lib/python3.5/copy.py in deepcopy(x, memo, _nil)
        180                             raise Error(
        181                                 "un(deep)copyable object of type %s" % cls)
    --> 182                 y = _reconstruct(x, rv, 1, memo)
        183 
        184     # If is its own copy, don't memoize.
    
    /usr/lib/python3.5/copy.py in _reconstruct(x, info, deep, memo)
        295     if state is not None:
        296         if deep:
    --> 297             state = deepcopy(state, memo)
        298         if hasattr(y, '__setstate__'):
        299             y.__setstate__(state)
    
    /usr/lib/python3.5/copy.py in deepcopy(x, memo, _nil)
        153     copier = _deepcopy_dispatch.get(cls)
        154     if copier:
    --> 155         y = copier(x, memo)
        156     else:
        157         try:
    
    /usr/lib/python3.5/copy.py in _deepcopy_dict(x, memo)
        241     memo[id(x)] = y
        242     for key, value in x.items():
    --> 243         y[deepcopy(key, memo)] = deepcopy(value, memo)
        244     return y
        245 d[dict] = _deepcopy_dict
    
    /usr/lib/python3.5/copy.py in deepcopy(x, memo, _nil)
        180                             raise Error(
        181                                 "un(deep)copyable object of type %s" % cls)
    --> 182                 y = _reconstruct(x, rv, 1, memo)
        183 
        184     # If is its own copy, don't memoize.
    
    /usr/lib/python3.5/copy.py in _reconstruct(x, info, deep, memo)
        295     if state is not None:
        296         if deep:
    --> 297             state = deepcopy(state, memo)
        298         if hasattr(y, '__setstate__'):
        299             y.__setstate__(state)
    
    /usr/lib/python3.5/copy.py in deepcopy(x, memo, _nil)
        153     copier = _deepcopy_dispatch.get(cls)
        154     if copier:
    --> 155         y = copier(x, memo)
        156     else:
        157         try:
    
    /usr/lib/python3.5/copy.py in _deepcopy_dict(x, memo)
        241     memo[id(x)] = y
        242     for key, value in x.items():
    --> 243         y[deepcopy(key, memo)] = deepcopy(value, memo)
        244     return y
        245 d[dict] = _deepcopy_dict
    
    /usr/lib/python3.5/copy.py in deepcopy(x, memo, _nil)
        180                             raise Error(
        181                                 "un(deep)copyable object of type %s" % cls)
    --> 182                 y = _reconstruct(x, rv, 1, memo)
        183 
        184     # If is its own copy, don't memoize.
    
    /usr/lib/python3.5/copy.py in _reconstruct(x, info, deep, memo)
        295     if state is not None:
        296         if deep:
    --> 297             state = deepcopy(state, memo)
        298         if hasattr(y, '__setstate__'):
        299             y.__setstate__(state)
    
    /usr/lib/python3.5/copy.py in deepcopy(x, memo, _nil)
        153     copier = _deepcopy_dispatch.get(cls)
        154     if copier:
    --> 155         y = copier(x, memo)
        156     else:
        157         try:
    
    /usr/lib/python3.5/copy.py in _deepcopy_dict(x, memo)
        241     memo[id(x)] = y
        242     for key, value in x.items():
    --> 243         y[deepcopy(key, memo)] = deepcopy(value, memo)
        244     return y
        245 d[dict] = _deepcopy_dict
    
    /usr/lib/python3.5/copy.py in deepcopy(x, memo, _nil)
        180                             raise Error(
        181                                 "un(deep)copyable object of type %s" % cls)
    --> 182                 y = _reconstruct(x, rv, 1, memo)
        183 
        184     # If is its own copy, don't memoize.
    
    /usr/lib/python3.5/copy.py in _reconstruct(x, info, deep, memo)
        295     if state is not None:
        296         if deep:
    --> 297             state = deepcopy(state, memo)
        298         if hasattr(y, '__setstate__'):
        299             y.__setstate__(state)
    
    /usr/lib/python3.5/copy.py in deepcopy(x, memo, _nil)
        153     copier = _deepcopy_dispatch.get(cls)
        154     if copier:
    --> 155         y = copier(x, memo)
        156     else:
        157         try:
    
    /usr/lib/python3.5/copy.py in _deepcopy_dict(x, memo)
        241     memo[id(x)] = y
        242     for key, value in x.items():
    --> 243         y[deepcopy(key, memo)] = deepcopy(value, memo)
        244     return y
        245 d[dict] = _deepcopy_dict
    
    /usr/lib/python3.5/copy.py in deepcopy(x, memo, _nil)
        180                             raise Error(
        181                                 "un(deep)copyable object of type %s" % cls)
    --> 182                 y = _reconstruct(x, rv, 1, memo)
        183 
        184     # If is its own copy, don't memoize.
    
    /usr/lib/python3.5/copy.py in _reconstruct(x, info, deep, memo)
        295     if state is not None:
        296         if deep:
    --> 297             state = deepcopy(state, memo)
        298         if hasattr(y, '__setstate__'):
        299             y.__setstate__(state)
    
    /usr/lib/python3.5/copy.py in deepcopy(x, memo, _nil)
        153     copier = _deepcopy_dispatch.get(cls)
        154     if copier:
    --> 155         y = copier(x, memo)
        156     else:
        157         try:
    
    /usr/lib/python3.5/copy.py in _deepcopy_dict(x, memo)
        241     memo[id(x)] = y
        242     for key, value in x.items():
    --> 243         y[deepcopy(key, memo)] = deepcopy(value, memo)
        244     return y
        245 d[dict] = _deepcopy_dict
    
    /usr/lib/python3.5/copy.py in deepcopy(x, memo, _nil)
        180                             raise Error(
        181                                 "un(deep)copyable object of type %s" % cls)
    --> 182                 y = _reconstruct(x, rv, 1, memo)
        183 
        184     # If is its own copy, don't memoize.
    
    /usr/lib/python3.5/copy.py in _reconstruct(x, info, deep, memo)
        295     if state is not None:
        296         if deep:
    --> 297             state = deepcopy(state, memo)
        298         if hasattr(y, '__setstate__'):
        299             y.__setstate__(state)
    
    /usr/lib/python3.5/copy.py in deepcopy(x, memo, _nil)
        153     copier = _deepcopy_dispatch.get(cls)
        154     if copier:
    --> 155         y = copier(x, memo)
        156     else:
        157         try:
    
    /usr/lib/python3.5/copy.py in _deepcopy_dict(x, memo)
        241     memo[id(x)] = y
        242     for key, value in x.items():
    --> 243         y[deepcopy(key, memo)] = deepcopy(value, memo)
        244     return y
        245 d[dict] = _deepcopy_dict
    
    /usr/lib/python3.5/copy.py in deepcopy(x, memo, _nil)
        172                     reductor = getattr(x, "__reduce_ex__", None)
        173                     if reductor:
    --> 174                         rv = reductor(4)
        175                     else:
        176                         reductor = getattr(x, "__reduce__", None)
    
    TypeError: cannot serialize '_io.TextIOWrapper' object

**Comment by drsxr** [comment]
Interesting.  I got the same error.  Its from not saving your multi-GPU session correctly.
1.  I was using the appropriate workaround for multi-gpu checkpointing with:
`class MultiGPUCheckpoint(ModelCheckpoint):

    def set_model(self, model):
        if isinstance(model.layers[-2], Model):
            self.model = model.layers[-2]
        else:
            self.model = model
            
save_best_callback=MultiGPUCheckpoint(filepath=saved_model_dir+Run+"ResNet50-{epoch:02d}-{val_acc:.5f}.h5",
                                                 monitor='val_loss', save_best_only=True)

history = model.fit_generator(
      train_generator,
      steps_per_epoch=Training_case_number/Training_batch_size,
      epochs=epochs,
      validation_data=validation_generator,
      validation_steps=validation_steps,
      callbacks = [save_best_callback])                   `

But since you are using Multi-GPU, you can't just use model.save().  You have to roll back 2 layers. 

Resolved it by:
`from keras.models import load_model
save_model = model.layers[-2]
save_model.save(saved_model_dir+'Filename.h5')  # creates a HDF5 file 'my_model.h5'`
