### ISSUE TITLE
Tensorflow > GPU sync failed

### ISSUE THREAD

**Issue by joamla96** [keras-team/keras#10304]
Hi

Im just getting started with Neural Networks, and I'm encountering an issue. See full log here: https://pastebin.com/vxVfScwY

I've more or less followed another keras example to try and build, which works fine, so my cuda installation seems ok. 

I have no idea whats going on here, so I'm not sure what other information to post.

Trying to prototype on my laptop, but gonna run the full training on my desktop when i get home.

OS: Windows 10 Build 17134
CPU: Intel i7 4core/ht
GPU: nVidia GTX 850M
Enviroment: Pytohn 3.6.5
tensorflow==1.8.0
tensorflow-gpu==1.8.0
nVidia Cuda Toolkit 9.0 with cuDNN 9.0

**Comment by jona8690** [comment]
So, I just trired reducing my dataset by a large margin, which works fine now. 

Problem is, i need the larger dataset, and now i dont know what to do.

**Comment by deeiip** [comment]
This is unlikely to be a keras issue itself. There is a high chance the issue is with tf backend. Either way, if you need large dataset you can always use [fit_generator](https://keras.io/models/sequential/#fit_generator) to train in batches.

**Comment by wayanAI** [comment]
@jona8690 you can use Google Colab, because they have GPU Tesla K30. Thanks
