### ISSUE TITLE
Can I Convert a Trained Model to Quantized 8-bit Model for Interfere?

### ISSUE THREAD

**Issue by yanhaoy** [keras-team/keras#10301]
I have seen there's an api to convert a trained model into a quantized one for faster interfere in keras.js.
[Model Conversion](https://transcranial.github.io/keras-js-docs/conversion/)
So can i do this in keras without use a new custom-layer and retrain my model?

Thank you !!

**Comment by raghavgurbaxani** [comment]
Yeah, I have the same doubt. 

Can a model trained and saved on 32 bit float format be quantized into 8 bit integer or 16 bit float ?
