### ISSUE TITLE
ValueError: It seems that you are using the Keras 2 and you are passing both `kernel_size` and `strides` as integer positional arguments. For safety reasons, this is disallowed. Pass `strides` as a keyword argument instead.

### ISSUE THREAD

**Issue by NihilisticEngineer** [keras-team/keras#10300]
Hello, I am trying to "fix" some code that was built using Keras 1 instead of Keras 2. I am still currently very new so I do not have much knowledge on this. If anyone could point me in the right direction or help me solve and understand the issue that would be great. 

The current error I am receiving is this "ValueError: It seems that you are using the Keras 2 and you are passing both `kernel_size` and `strides` as integer positional arguments. For safety reasons, this is disallowed. Pass `strides` as a keyword argument instead."

I was having a different error regarding with boarder_mode, but then changed it to padding. 

Here is my code:

`model = Sequential()

# Convolution2D(number_filters, row_size, column_size, input_shape=(number_channels, img_row, img_col))

model.add(Convolution2D(6, 5, 5, input_shape=(1, img_rows, img_cols), padding='same'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Convolution2D(16, 5, 5, padding='same'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Convolution2D(120, 5, 5))
model.add(Activation('relu'))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(84))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(10))
model.add(Activation('softmax'))`

I can provide more if needed.  Thak you for your time and help!

**Comment by Dref360** [comment]
Are you sure you want a stride of 5?
If so, just change all your Convolution2D to the following.
`Convolution2D(6, 5, strides=5, ...)`

But maybe you wanted a 5x5 filter?
`Convolution2D(6, (5,5), ...)`
