### ISSUE TITLE
How do we know which backend functions are differentiable / not?

### ISSUE THREAD

**Issue by JunShern** [keras-team/keras#10321]
Hi, I'm trying to define custom loss functions for my model but have come across this error several times during development:

```
ValueError: An operation has `None` for gradient. Please make sure that all of your ops have a gradient defined (i.e. are differentiable). Common ops without gradient: K.argmax, K.round, K.eval.
```

I understand the need for differentiable loss functions, but I was wondering if there is any documentation on which functions in Keras are differentiable and which functions are not. My first instinct was that any of the [Keras backend](https://keras.io/backend/) functions are differentiable and hence usable in my loss functions, but clearly (as seen in the error message) that is not the case. 

I feel like it would be very helpful to have a list I can refer to, instead of discovering by trial and error as I have been doing so far. Does such a resource already exist, and if not, can we make one?

**Comment by KrishnanParameswaran** [comment]
@JunShern Did you get to know how to verify whether a function is differentiable or not ?

**Comment by Dref360** [comment]
Can we close this?

**Comment by JunShern** [comment]
Yes, I don't see a need to have this open for now.

**Comment by KrishnanParameswaran** [comment]
Thanks for your response @JunShern . I'm trying to use model weights and a C library (which needs to be compiled after every batch) in the loss function and wondering if there is a possibility at all.

**Comment by JunShern** [comment]
@KrishnanParameswaran As I understand it, I don't think this is possible since the Keras optimizers need to know how to propagate gradients through your loss function, which wouldn't be possible with your compiled C code. But I'm no expert on the library, perhaps the Keras developers may have a better answer for you.

**Comment by miselico** [comment]
I would want to reopen this issue. I understand @JunShern did get his problem solved, but in general this information should be in the backend documentation.
Besides, it would be wonderful if the error message could tell which operation is exactly offending.
I am now facing the same error message, but I am not using any of the operations in the 'black list' above. I do use concatenate, though, but that is used in many layers in keras.
@JunShern  could you reopen until this gets added to the documentation?

**Comment by mkagenius** [comment]
For me, the model got trained fine. But when I tried to load_model it started crying about differentiability. Certainly if it was trained that means it would have been differentiable but no, now there is some magic happening while I am doing load_model. Suddenly it has problems with differentiability.

**Comment by roya90** [comment]
Hey, 
Is K.cast for float64 to float32 differentiable?

**Comment by phao5814** [comment]
I'm trying to implement the following custom loss function; however, I'm getting `ValueError: An operation has `None` for gradient.`. I understand K.cast might be the offending operation per @JunShern's post; however, if I remove `kappa = K.cast(kappa, 'float32')` I get the error `TypeError: Input 'y' of 'Mul' Op has type float32 that does not match type float64 of argument 'x'.` Any ideas on how I can resolve this dilemma?

```
import tensorflow as tf
import keras.backend as K

def _cohen_kappa(y_true, y_pred, num_classes=5, weights=None, metrics_collections=None, updates_collections=None, name=None):
    kappa, update_op = tf.contrib.metrics.cohen_kappa(y_true, y_pred, num_classes, weights, metrics_collections, updates_collections, name)
    kappa = K.cast(kappa, 'float32')
    K.get_session().run(tf.local_variables_initializer())
    with tf.control_dependencies([update_op]):
        kappa = tf.identity(kappa)
    return kappa

def cohen_kappa_loss(num_classes=5, weights=None, metrics_collections=None, updates_collections=None, name=None):
    def cohen_kappa(y_true, y_pred):
        y_true = K.cast(y_true, 'int32')
        y_pred = K.cast(y_pred + 0.5, 'int32')

        y_true = K.sum(y_true, axis=1)
        y_pred = K.sum(y_pred, axis=1)

        return -_cohen_kappa(y_true, y_pred, num_classes, weights, metrics_collections, updates_collections, name)
    return cohen_kappa
```

**Comment by ludomitch** [comment]
@phao5814 did you ever resolve this? I am having a similar problem trying to implement cohen's kappa in keras.

**Comment by vedanshthakkar** [comment]
For a custom loss function, every expression in the code must be differentiable (or have gradient). Most of the function are differentiable if you use tf.raw_ops.operation, instead of just tf.operation.

For example, tf.cast() is not differentiable, but tf.raw_ops.Cast() is differentiable. See more at https://docs.w3cub.com/tensorflow~2.3/raw_ops

There you can see which tf operations has gradients and which does not. Hope this helps.
