### ISSUE TITLE
CTC gives sequence length error in Tensorflow but works in Theano

### ISSUE THREAD

**Issue by aayushee** [keras-team/keras#10326]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [+ ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [ +] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ +] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ +] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

I get a sequence length error when using ctc with tensorflow background but the same code runs while I am on theano background. I am using CTC to recognize online handwriting strokes and have modified the image_ocr.py example for this. My input shape is (1000,1586,4) and output shape (1000,56). All sequences a padded to 1586 length and I don't understand why sequence length error comes up and input sequence length is always greater than the output labels length. Following is the model and part of code:
``inputs = Input(name='the_input', shape=x_train.shape[1:], dtype='float32')``
``rnn_encoded=Bidirectional(LSTM(64,return_sequences=True,kernel_initializer='lecun_normal'),name='bidirectional_1',merge_mode='concat',trainable=trainable)(inputs)``
``birnn_encoded=Bidirectional(LSTM(32,return_sequences=True,kernel_initializer='lecun_normal'),name='bidirectional_2',merge_mode='concat',trainable=trainable)(rnn_encoded)``
``output = TimeDistributed(Dense(28, name='dense',kernel_initializer='lecun_normal'))(birnn_encoded)``
``y_pred = Activation('softmax', name='softmax')(output)``
``model=Model(inputs=inputs,outputs=y_pred)``
``labels = Input(name='the_labels', shape=[max_len], dtype='int32') ``
``input_length = Input(name='input_length', shape=[1], dtype='int64')``
``label_length = Input(name='label_length', shape=[1], dtype='int64')``
``loss_out = Lambda(ctc_lambda_func, output_shape=(1,), name='ctc')([y_pred, labels, input_length, label_length])``
``model = Model(inputs=[inputs, labels, input_length, label_length], outputs=loss_out)``
``batch_size=10``
``ada=RMSprop(lr=0.001,clipnorm=1.)``
``model.compile(loss={'ctc': lambda y_true, y_pred: y_pred}, optimizer=ada)``
``my_generator = generator(x_train,y_train,batch_size)``
``model.fit_generator(my_generator,steps_per_epoch=100,epochs=21,use_multiprocessing=False,shuffle=True)``

The full code is here: [(https://github.com/aayushee/HWR/blob/master/CTC4D.py)]
If anyone can explain what's wrong while running the code on Tensorflow that would be great. This is the error I am getting:

InvalidArgumentErrorTraceback (most recent call last)
<ipython-input-14-6e8f5dd35a11> in <module>()
     56 
     57 my_generator = generator(x_train,y_train,batch_size)
---> 58 model.fit_generator(my_generator,steps_per_epoch=steps,epochs=epoch,shuffle=True)
     59 
     60 test_func = K.function([inputs], [y_pred])

/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.pyc in wrapper(*args, **kwargs)
     89                 warnings.warn('Update your `' + object_name +
     90                               '` call to the Keras 2 API: ' + signature, stacklevel=2)
---> 91             return func(*args, **kwargs)
     92         wrapper._original_function = func
     93         return wrapper

/usr/local/lib/python2.7/dist-packages/keras/engine/training.pyc in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   2228                     outs = self.train_on_batch(x, y,
   2229                                                sample_weight=sample_weight,
-> 2230                                                class_weight=class_weight)
   2231 
   2232                     if not isinstance(outs, list):

/usr/local/lib/python2.7/dist-packages/keras/engine/training.pyc in train_on_batch(self, x, y, sample_weight, class_weight)
   1881             ins = x + y + sample_weights
   1882         self._make_train_function()
-> 1883         outputs = self.train_function(ins)
   1884         if len(outputs) == 1:
   1885             return outputs[0]

/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.pyc in __call__(self, inputs)
   2480         session = get_session()
   2481         updated = session.run(fetches=fetches, feed_dict=feed_dict,
-> 2482                               **self.session_kwargs)
   2483         return updated[:len(self.outputs)]
   2484 

/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.pyc in run(self, fetches, feed_dict, options, run_metadata)
    898     try:
    899       result = self._run(None, fetches, feed_dict, options_ptr,
--> 900                          run_metadata_ptr)
    901       if run_metadata:
    902         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.pyc in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1133     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1134       results = self._do_run(handle, final_targets, final_fetches,
-> 1135                              feed_dict_tensor, options, run_metadata)
   1136     else:
   1137       results = []

/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.pyc in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1314     if handle is None:
   1315       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1316                            run_metadata)
   1317     else:
   1318       return self._do_call(_prun_fn, handle, feeds, fetches)

/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.pyc in _do_call(self, fn, *args)
   1333         except KeyError:
   1334           pass
-> 1335       raise type(e)(node_def, op, message)
   1336 
   1337   def _extend_graph(self):

InvalidArgumentError: sequence_length(0) <= 1584
	 [[Node: ctc_1/CTCLoss = CTCLoss[_class=["loc:@training_1/RMSprop/gradients/ctc_1/CTCLoss_grad/mul"], ctc_merge_repeated=true, ignore_longer_outputs_than_inputs=false, preprocess_collapse_repeated=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ctc_1/Log, ctc_1/ToInt64, ctc_1/GatherNd, ctc_1/ToInt32_1)]]

Thanks!

**Comment by Zappyford** [comment]
Hi ! I have the same issue here, does anyone have any info on this ? Did you eventually make it work on Tensorflow ?
Thanks !
