### ISSUE TITLE
Tie - Share weights between different layers

### ISSUE THREAD

**Issue by iliaschalkidis** [keras-team/keras#10333]
I would like to know if there is any straight-forward way on how you can train 2 different layers with the same weights matrix (e.g. use 2 LSTMs that "learn" the exact same transformations).

So far I investigated to different options, which lead to errors:

**A single shared layer**
```
input_1 = Input()
input_2 = Input()
lstm = LSTM()
output_1 = lstm(input_1)
output_2 = lstm(input_2)
```

Error: Graph disconnected: cannot obtain value for tensor Tensor [...]

**Two layers sharing weights**
```
input_1 = Input()
input_2 = Input()
lstm_1 = LSTM()
lstm_2 = LSTM()
output_1 = lstm(input_1)
output_2 = lstm(input_2)
lstm_1.set_weights(lstm_2.weights)
```

Error: ValueError: setting an array element with a sequence.

@farizrahman4u it is highly possible that you already know the right way :)

**Comment by tRosenflanz** [comment]
```input_1 = Input()
input_2 = Input()
lstm = LSTM()
output_1 = lstm(input_1)
output_2 = lstm(input_2)```

is the correct way - just don't forget to fill in the input shapes for Input layers and size for the LSTM one

**Comment by brge17** [comment]
import keras
from keras.models import Model
from keras.layers import LSTM, Input, Flatten, Dense

seq_shape = (007, 007)

# Defined a shared model, 2 LSTM layers
input_seq = Input(seq_shape)
lstm_1 = LSTM(10, return_sequences=True)(input_seq)
lstm_2 = LSTM(10)(lstm_1)
shared_lstm = Model(input_seq, lstm_2, name="shared_lstm")

# Define two input sequences
seq_1 = Input(seq_shape)
seq_2 = Input(seq_shape)

encoded_1 = shared_lstm(seq_1)
encoded_2 = shared_lstm(seq_2)

# Let's do classification for fun
num_classes = 3
cat = keras.layers.concatenate([encoded_1, encoded_2], axis=-1)
softmax = Dense(num_classes, activation="softmax")(cat)

m = Model([seq_1, seq_2], softmax)

from keras.utils import plot_model
plot_model(m, to_file='model.png')

**Comment by iliaschalkidis** [comment]
@brge17 thanx a lot! I did not have a good understanding of the Input Layers so far. As you show you in this case we need a "mock-up" Input Layer in order to describe how we feed the shared layer (or even a deeper component) and finally we need to define the actual Input layers.

I tested this code pattern with a much deeper shared sub-network (a hierarchical RNN with attention) and it worked like a charm!


```
Layer (type)                     Output Shape          Param #     Connected to                     
====================================================================================================
input_1 (InputLayer)            (None, 10, 100, 50)   0                                            
____________________________________________________________________________________________________
input_2 (InputLayer)            (None, 10, 100, 50)   0                                            
____________________________________________________________________________________________________
hierarchical_encoder (Model)       (None, 50)         60910       input_1[0][0]                  
                                                                  input_2[0][0]                  
____________________________________________________________________________________________________
final_representation (Subtract)     (None, 50)          0      hierarchical_encoder[1][0]            
                                                               hierarchical_encoder[2][0]            
____________________________________________________________________________________________________
output (Dense)                   (None, 1)             51      final_representation[0][0]          
====================================================================================================
Total params: 60,961
Trainable params: 60,961
Non-trainable params: 0
____________________________________________________________________________________________________
```

**Comment by Dok11** [comment]
@brge17 I lost much time tring to repeat your code for my model. You did not point out what here
`shared_lstm = Model(input_seq, lstm_2, name="shared_lstm")`
name in argument and name of variable MUST be equal. Ohhh
