### ISSUE TITLE
Feature request : ProgBarLogger updates one every X batches

### ISSUE THREAD

**Issue by GuillaumeDesforges** [keras-team/keras#10343]
When instanciating a https://keras.io/callbacks/#progbarlogger, it should be possible to print less often (ratio or length based ?) the progress bar.

from
```
keras.callbacks.ProgbarLogger(count_mode='steps', stateful_metrics=None)
```
to
```
keras.callbacks.ProgbarLogger(count_mode='steps', stateful_metrics=None, every=32)
```

Would be especially useful when batch of size 1.

**Comment by Wheelspawn** [comment]
Sounds useful. I can work on this.

**Comment by Wheelspawn** [comment]
https://github.com/keras-team/keras/pull/10344
