### ISSUE TITLE
keras.applications Visualization

### ISSUE THREAD

**Issue by lsh1994** [keras-team/keras#10362]
I am using the  model with `keras.applications.vgg16`. How should I visualize each layer of this vgg16?

**Comment by chinmayshah99** [comment]
Hey @lsh1994 you can use `model.summary()` to get  details about each layer. 
```
keras.applications.vgg16 import VGG16
model = VGG16(weights=None, include_top=False)
model.summary()
```
If you're looking for plotting the model, you can try: 
```
from keras.utils import plot_model
plot_model(model, to_file='model.png')
```

**Comment by lsh1994** [comment]
@chinmayshah99 Thanks anyway. It is not for me but I have found a complicated method. https://blog.csdn.net/nima1994/article/details/80613588
