### ISSUE TITLE
Bad Error Message for Incorrect Input Shape for 2D Layers

### ISSUE THREAD

**Issue by justinkterry** [keras-team/keras#10360]
I accidentally did the following for a 2D layer at the start of a neural net:

s = np.shape(X)
model.add(Conv2D(10,kernel_size = (5,5),activation = 'relu',input_shape = s))

Where s= (60000, 28, 28, 1)

I know it should've been s=(28,28,1), but the error message seems to contradict that:
 ValueError: Input 0 is incompatible with layer conv2d_4: expected ndim=4, found ndim=5

It should say found 4 dimensions and expected 3, and that makes noticing the error super hard.

This occurs in the current version of keras in PyPi as of 10 minutes ago.

**Comment by brge17** [comment]
The layers have a placeholder dimension (None,) + (input_shape) where the (None,) corresponds to the batch size.

The layer does take 4 dimensions.

**Comment by fchollet** [comment]
yes, as stated by @brge17, the `input_shape` argument in layers refers to the shape of a single sample that will go through the layer, not the shape of a batch: that shape tuple doesn't have a batch axis.

In your case the correct argument is `input_shape=(28, 28, 1)`.

In rare cases you may need to specify the full batch size (e.g. when working with stateful RNNs). In these cases you can do so using the `batch_input_shape=(batch_size, ...)` argument.

**Comment by justinkterry** [comment]
My issue isn't that the error message is technically wrong, I'm aware it isn't, sorry. My point is it's needlessly confusing for a really easiy/common mistake I've seen. A custom, more clear, error message for this is warranted.
