### ISSUE TITLE
How are Lambda layers serialized to JSON?

### ISSUE THREAD

**Issue by philtomson** [keras-team/keras#10368]
Are Lambda layers serialized to Python bytecode? We have a GSoC student trying to read in the Keras models that have been serialized to JSON into a Julia based framework and running into issues (not surprisingly) with Lambda layers - I would guess the function in the JSON is serialized to Python bytecode and that crossing the language barrier would not be possible (without doing some sophisticated compiler-ish type things)

The example JSON code (exported from Keras) is:

```
{

            "name": "block35_2",

            "class_name": "Lambda",

            "config": {

                "name": "block35_2",

                "trainable": true,

                "function": ["4wIAAAAAAAAAAgAAAAMAAABTAAAAcxQAAAB8AGQBGQB8AGQCGQB8ARQAFwBTACkDTukAAAAA6QEA\\nAACpACkC2gZpbnB1dHPaBXNjYWxlcgMAAAByAwAAAPpdL2hvbWUvYXl1c2g5OS9hbmFjb25kYTMv\\nbGliL3B5dGhvbjMuNi9zaXRlLXBhY2thZ2VzL2tlcmFzL2FwcGxpY2F0aW9ucy9pbmNlcHRpb25f\\ncmVzbmV0X3YyLnB52gg8bGFtYmRhPqgAAADzAAAAAA==\\n", null, null],

                "function_type": "lambda",

                "output_shape": [null, null, 320],

                "output_shape_type": "raw",

                "arguments": {

                    "scale": 0.17

                }
...
```

I'm guessing this bit: 

 `            "function": ["4wIAAAAAAAAAAgAAAAMAAABTAAAAcxQAAAB8AGQBGQB8AGQCGQB8ARQAFwBTACkDTukAAAAA6QEA\\nAACpACkC2gZpbnB1dHPaBXNjYWxlcgMAAAByAwAAAPpdL2hvbWUvYXl1c2g5OS9hbmFjb25kYTMv\\nbGliL3B5dGhvbjMuNi9zaXRlLXBhY2thZ2VzL2tlcmFzL2FwcGxpY2F0aW9ucy9pbmNlcHRpb25f\\ncmVzbmV0X3YyLnB52gg8bGFtYmRhPqgAAADzAAAAAA==\\n", null, null],
`
... is python bytecode?

**Comment by fchollet** [comment]
That's right, they're serialized as bytecode. And you're right, you couldn't load such a layer in a different environment (such as TensorFlow.js). In such cases, you should write a serializable custom layer (one implementation per environment you want to support, e.g. Python and JS), implementing `get_config` and `from_config` (you will also need to use a `CustomObjectScope` when loading a model using such a custom layer).
