### ISSUE TITLE
Typo in lstm_seq2seq example documentation

### ISSUE THREAD

**Issue by wpm** [keras-team/keras#10378]
In the documentation at the top of the file the following sentence appears:

> - We start with input sequences from a domain (e.g. English sentences)
>     and correspding target sequences from another domain
>     (e.g. French sentences).

There is a typo in "correspding". It should be "corresponding".

**Comment by JamesTrick** [comment]
Hey @wpm 

I'm sure Keras wouldn't be opposed to a PR for this, I believe the relevant file you're referring to is [keras/examples/lstm_seq2seq.py](https://github.com/keras-team/keras/blob/4cde148de0c37981c50f3a8e4a59fa4e5f653e17/examples/lstm_seq2seq.py).

Let me know if you want to do it, or else I'll take it up. 

Cheers
James
