### ISSUE TITLE
Concatenating the output of 2 encoders

### ISSUE THREAD

**Issue by SaheliDe** [keras-team/keras#10379]
I am trying to create an RNN for miRNA target prediction. And I have 2 encoder output that I need to concatenate before i feed it into the RNN.

I tried" final_weight = concatenate([miRNA_encodings, mRNA_encodings],axis=-1)"

But i am getting the error :
ValueError: Layer concatenate_1 was called with an input that isn't a symbolic tensor. Received type: <class 'numpy.ndarray'>.

**Comment by F0lha** [comment]
I believe that miRNA_encodings and/or mRNA_encodings are not Tensor as required by the [API](https://keras.io/layers/merge/#concatenate_1). Check for possible typos. Provide more code if you still haven't figure out the answer.

**Comment by SaheliDe** [comment]
@F0lha 

this is my autoencoder:
import keras
from keras import backend as K
from keras.models import Sequential, Model
from keras.layers import Input, LSTM, RepeatVector
from keras.layers.core import Flatten, Dense, Dropout, Lambda
from keras.optimizers import SGD, RMSprop, Adam
from keras import objectives


def create_lstm_autoencoder(input_dim, timesteps, latent_dim):
    """
    Creates an LSTM Autoencoder (VAE). Returns Autoencoder, Encoder, Generator.
    (All code by fchollet - see reference.)

    # Arguments
        input_dim: int.
        timesteps: int, input timestep dimension.
        latent_dim: int, latent z-layer shape.

    # References
        - [Building Autoencoders in Keras](https://blog.keras.io/building-autoencoders-in-keras.html)
    """

    inputs = Input(shape=(timesteps, input_dim,))
    encoded = LSTM(30, return_sequences=True)(inputs)
    encoded = Dropout(0.8)(encoded)
    encoded = LSTM(latent_dim)(encoded)

    decoded = RepeatVector(timesteps)(encoded)
    decoded = LSTM(input_dim, return_sequences=True)(decoded)

    sequence_autoencoder = Model(inputs, decoded)
    encoder = Model(inputs, encoded)

    autoencoder = Model(inputs, decoded)
    autoencoder.compile(optimizer='adam', loss='msle')
    return autoencoder, encoder, sequence_autoencoder

and this is my run file 

 miRNA_train = pp.prepare_data(config["miRNA_file_raw"])
    mRNA_train = pp.prepare_data(config["mRNA_file_raw"])
    miRNA_weights = config["miRNA_weights"]
    mRNA_weights= config["mRNA_weights"]
    mRNA_miRNA_weights = config["mRNA_miRNA_weights"]
    miRNA_input_dim = miRNA_train.shape[-1]
    miRNA_timesteps = miRNA_train.shape[1]
    mRNA_input_dim = mRNA_train.shape[-1]
    mRNA_timesteps = mRNA_train.shape[1]


    latent_dim = 4
    batch_size = 32
    epochs = 10


    #########
    # miRNA #
    #########
    print("creating miRNA encodings...")
    autoencoder, encoder, decoder = create_lstm_autoencoder(miRNA_input_dim, miRNA_timesteps, latent_dim)
    if os.path.exists(miRNA_weights): autoencoder.load_weights(miRNA_weights)
    autoencoder.fit(miRNA_train, miRNA_train, epochs=epochs, verbose=1)
    autoencoder.save_weights(miRNA_weights)
    miRNA_encodings = encoder.predict(miRNA_train)


    ########
    # mRNA #
    ########
    print("creating mRNA encodings...")
    autoencoder, encoder, decoder = create_lstm_autoencoder(mRNA_input_dim, mRNA_timesteps, latent_dim)
    if os.path.exists(mRNA_weights): autoencoder.load_weights(mRNA_weights)
    autoencoder.fit(mRNA_train, mRNA_train, epochs=epochs, verbose=1)
    autoencoder.save_weights(mRNA_weights)
    mRNA_encodings = encoder.predict(mRNA_train) 

    **merged_vector = concatenate([mRNA_encodings, miRNA_encodings], axis=-1)**

Couldn't figure out the answer yet :(

**Comment by F0lha** [comment]
If you check the [Sequential API](https://keras.io/models/sequential/) you can see that predict returns a numpy of predictions. Just concatenate both predicitons using [numpy's concatenate funciton](https://docs.scipy.org/doc/numpy/reference/generated/numpy.concatenate.html).

**Comment by SaheliDe** [comment]
@F0lha thanks a lot ! it worked 👍
