### ISSUE TITLE
update your dense call to the keras 2

### ISSUE THREAD

**Issue by ghost** [keras-team/keras#10395]
import keras from keras.models import Sequential from keras.layers import Dense

classifier = Sequential()

classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 11))

classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))

This is my code when ever im trying to run it it shows me error like this

C:\Users\Amir Ali\Anaconda3\lib\site-packages\ipykernel__main__.py:2: UserWarning: Update your  Dense call to the Keras 2 API: Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform") from ipykernel import kernelapp as app

**Comment by deeiip** [comment]
This should work fine,
```
classifier.add(Dense(6, init = 'uniform', activation = 'relu', input_dim = 11))
classifier.add(Dense(6, init = 'uniform', activation = 'relu'))
```

**Comment by amiralicheema** [comment]
not working this code same error deeiip sir!

**Comment by deeiip** [comment]
```
classifier = Sequential()
classifier.add(Dense(6, kernel_initializer="uniform", activation = 'relu', input_dim = 11))
classifier.add(Dense(6, kernel_initializer="uniform", activation = 'relu'))
```

This seems to be working fine.

**Comment by rekhitdroid** [comment]
i have got an error as
 Unknown activation function: relu
what would i do next

**Comment by Satyam-Bhalla** [comment]
Change the `init` parameter to `kernel_initializer` and the error will be removed, and @rekhitdroid you must check whether you have installed all the necessary libraries(version) correctly or not.

**Comment by rekhitdroid** [comment]
It worked by kernel_initializer . thankyou @Satyam-Bhalla

**Comment by kotharisoumya24** [comment]
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 11))


while executing this code i have an error 

InvalidArgumentError: Operation 'dense_18/kernel' has no attr named '_class'.

what should i do?

**Comment by shubh1312** [comment]
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 11))


while executing this code i have an error 

InvalidArgumentError: Operation 'dense_18/kernel' has no attr named '_class'.

what should i do?

**Comment by jogeshpi03** [comment]
I tried the following, maybe this helps you

```classifier.add(Dense(units=6, activation="relu", input_dim=11, kernel_initializer="uniform"))```

**Comment by guntharahul** [comment]
classifier=Sequential()
classifier.add(Dense(6, kernel_initializer='uniform' , activation= 'relu', input_dim=11))

this should work fine

**Comment by Abhishek-31** [comment]
I am also having this issue of `update your dense call to the keras 2`. Is there any solution I can break through?

**Comment by Spawnfile** [comment]
This is a warning not an error. If you modify your code like shown at the end of the warning line, warning will disappear.

`classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))`

**Comment by FurkanCpr** [comment]
> This is a warning not an error. If you modify your code like shown at the end of the warning line, warning will disappear.
> 
> `classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))`

Thank you sir!

**Comment by majidbhatti** [comment]
`from tensorflow.keras.models import Sequential
        from tensorflow.keras.layers import Dense
        import tensorflow.keras.backend
        classifier = Sequential()
        classifier.add(Dense(output_dim=6, init='uniform', activation = 'relu', input_dim = 11))`


the above code shows following error


TypeError: __init__() missing 1 required positional argument: 'units'

**Comment by krshashank963** [comment]
just modify it to 
Dense(6,activation= 'relu',input_dim=11,kernel_initializer='uniform'))
and try
 hope it works

**Comment by sarathsp1729** [comment]
I get the warning message. But I am using functional API. 

inp = Input(shape=(2,))
l3 = Dense(64, activation='relu',kernel_initializer='glorot_uniform')(inp)
l4 = Dense(32, activation='relu',kernel_initializer='glorot_uniform')(l3)
l5 = Dense(16, activation='relu',kernel_initializer='glorot_uniform')(l4)
out = Dense(1, activation='sigmoid',kernel_initializer='glorot_uniform')(l5)
model = Model(inputs=[inp], outputs=[out])

**Comment by MrStonkus** [comment]
I resolved this problem by change all output_dim:

```
output_dim=6 // old output

units=6 // updated output

```
warning gone :)

**Comment by BhargavaCreates** [comment]
`output_dim=6 // old output

units=6 // updated output`

and 

`init = 'uniform' // old wights initializer
 kernel_initializer = 'uniform' // new initializer`

i am not sure about the `input_dim=11`
does it have a updated version as well???

**Comment by ajaykumar2017** [comment]
Try to update the code like this and the warning will be removed:
`Dense(kernel_initializer="uniform", units=6, activation="relu", input_dim=11)`
