### ISSUE TITLE
Keras 2.2.0 bug in keras.legacy

### ISSUE THREAD

**Issue by iliaschalkidis** [keras-team/keras#10409]
I tried to install Keras 2.2.0 and it breaks my codebase when I try to use the legacy submodule 

Installing with pip:

`sudo pip install --upgrade keras
`
or

```
sudo uninstall keras
sudo pip install keras
```

leads to the following error:

```
    from keras.legacy import models as legacy_models
  File "/Users/kiddo/anaconda/lib/python3.6/site-packages/keras/legacy/models.py", line 5, in <module>
    from .layers import Merge
ImportError: cannot import name 'Merge'
```

I do not use Merge at all, but if Merge is removed, you better completely remove it from keras code.

Installing directly from github repo:

```
git clone https://github.com/keras-team/keras.git
cd keras
sudo python setup.py install
```

leads to the following error:

```
    from keras.legacy import models as legacy_models
ImportError: cannot import name 'models'
```

Here the whole submodule (folder) is missing...

I removed calls to legacy from my codebase, but still keras code should be able to load correctly.

**Comment by Dref360** [comment]
keras.legacy.models is deprecated and has been removed from the codebase. Code relying on this module is expected to break.

There is no mention of the Merge layer anywhere in the codebase.
https://github.com/keras-team/keras/search?p=1&q=Merge&unscoped_q=Merge

https://github.com/keras-team/keras/tree/master/keras/legacy

**Comment by iliaschalkidis** [comment]
@Dref360 then both errors shouldn't even occur... I did not complain about legacy support, I just mention that at least the main installation process through pip does not offer the updated codebase, as you mention. It does not seem aligned, although it is tagged as 2.2.0

Thanx for the info!
