### ISSUE TITLE
ValueError: Error when checking target: expected concatenate_1 to have shape (20,) but got array with shape (10,)

### ISSUE THREAD

**Issue by digitalized-hfut** [keras-team/keras#10407]
I want to train two networks meanwhile, and merge(concatenate) the last layer as one to output.
But,there is something wrong that i could not debug.
The code as follow:

import keras
from keras.models import Model
from keras.layers import Input, Dense, Dropout, Activation, Concatenate
from keras.optimizers import SGD
import numpy as np

x_train = np.random.random((1000, 20))
y_train = keras.utils.to_categorical(np.random.randint(10, size=(1000, 1)), num_classes=10)
x_test = np.random.random((100, 20))
y_test = keras.utils.to_categorical(np.random.randint(10, size=(100, 1)), num_classes=10)

input_1 = Input(shape=(20, ))
x_1 = Dense(64, activation='relu')(input_1)
x_1 = Dropout(0.5)(x_1)
x_1 = Dense(64, activation='relu')(x_1)
x_1 = Dropout(0.5)(x_1)
x_1 = Dense(10, activation='softmax')(x_1)

input_2 = Input(shape=(20, ))
x_2 = Dense(64, activation='relu')(input_2)
x_2 = Dropout(0.5)(x_2)
x_2 = Dense(64, activation='relu')(x_2)
x_2 = Dropout(0.5)(x_2)
x_2 = Dense(10, activation='softmax')(x_2)

concat = Concatenate(axis=-1)([x_1, x_2])

model = Model(inputs=[input_1, input_2], outputs=concat)

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy',
              optimizer=sgd,
              metrics=['accuracy'])

model.fit([x_train, x_train], y_train,
          epochs=20,
          batch_size=128)
score = model.evaluate([x_test,x_test], y_test, batch_size=128)

ValueError: Error when checking target: expected concatenate_1 to have shape (20,) but got array with shape (10,)

**Comment by DeepakLabh** [comment]
I am also getting similar issue.
Any developments?
