### ISSUE TITLE
How to pass two inputs into TimeDistributed

### ISSUE THREAD

**Issue by bayou3** [keras-team/keras#10404]
Hello all,
I want to build an essay model. Here I have an essay and a query. For the essay, it has many sentences, and a sentence has many words. For the query, it can consists of several words or a description of two/three sentences.
Firstly, I want to build for essay sentence's words and query's words. For this, I use Input, Embedding and BiLSTM:

            input_essay_words = Input( num_e_words, ), dtype='int32' )
            input_query_words = Input( num_q_words, ), dtype='int32' )

Then get their embeddings:

            essay_words_emb  = Embedding( vocab_size, emb_dim, weights = self.weights, trainable=False)(input_essay_words )
            essay_query_emb  = Embedding( vocab_size, emb_dim, weights = self.weights, trainable=False)(input_query_words )

Then put them into BiLSTM:

            essay_words_bilstm = Bidirectional( LSTM( hidden_dim, return_sequences = False), merge_mode = 'concat' ) (essay_words_emb)
            essay_query_bilstm = Bidirectional( LSTM( hidden_dim, return_sequences = False), merge_mode = 'concat' ) (essay_query_emb)

Next, I merge them:

            words_and_q = merge( [essay_words_bilstm , essay_query_bilstm ], mode='concat')

So now a sentence consists of its words and the query ( please ignore why I put them together, I want to do sth to them), then a new sentence can be modeled by:

            sentence = Model( inputs = [ input_essay_words , input_query_words], outputs = words_and_q )

If I have no query here, I can just pass all essays into TimeDistributed like the followed:

            input_essay = Input(shape=(None,  num_e_words), dtype='int32')
            timedis_essay = TimeDistributed(sentence)(input_essay)

But now, I need to pass the query into TimeDistributed, how can I do to Input(shape=(None,  num_e_words), dtype='int32') to have the two inputs at the same time, or how to pass two inputs and then merge them and pass the merged result into TimeDistributed ?

**Comment by tRosenflanz** [comment]
Concatenate them into 1 input
