### ISSUE TITLE
Programme gives ValueError for keras model

### ISSUE THREAD

**Issue by tuncelbrk** [keras-team/keras#10423]
Hi im working on training a model and when i run code it gives me error :"ValueError: Error when checking input: expected dense_5_input to have shape (None, 4096) but got array with shape (19136, 1)"

Actually i'm trying to do image captioning and,

Here is my model:
image_model = Sequential()

image_model.add(Dense(embedding_size, input_shape=(4096,), activation='relu'))
image_model.add(RepeatVector(max_len))

image_model.summary()

language_model = Sequential()

language_model.add(Embedding(input_dim=vocab_size, output_dim=embedding_size, input_length=max_len))
language_model.add(LSTM(256, return_sequences=True))
language_model.add(TimeDistributed(Dense(embedding_size)))

language_model.summary()

model = Sequential()

model.add(Merge([image_model, language_model], mode='concat', concat_axis=-1))
model.add(LSTM(1000, return_sequences=False))
model.add(Dense(vocab_size))
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy', optimizer=Nadam(), metrics=['accuracy'])
print("function fit")
model.fit([images, captions], next_words, batch_size=512, epochs=50)

**Comment by anj-s** [comment]
Can you print out the model summary? What is the shape of images and captions? Can you print out the shape of the inputs and compare them with the model's input tensor shape(model.inputs should help you with that)?
