### ISSUE TITLE
Image Preprocessing corrupts some greyscale images

### ISSUE THREAD

**Issue by alexzubiaga** [keras-team/keras#10437]
While training an Inception Model with a mix of color and greyscale images I've noticed that some of the greyscale images were loosing most of the details when loading them with `flow_from_directory`.

The cause is  the RGB conversion from Pillow used in `load_img` as described in this issue [Pillow-2574](https://github.com/python-pillow/Pillow/issues/2574)

In my case the suggested workaround fixed the conversion.

This is the code I've used to handle the RGB conversion:
```python
if img.mode != 'RGB':
    if img.mode == 'I':
        from PIL import ImageMath
        img = ImageMath.eval('im/256', {'im': img})
    img = img.convert('RGB')
```

**Comment by keck-in-space** [comment]
Super super helpful. Thank you!

**Comment by alexzubiaga** [comment]
And I thought I was the only one working with greyscale images. Glad to be of help.

**Comment by ronz0215** [comment]
Hello,
I have similar issue, I'm using mode 'I' too, however my images are saved as uint16 so scaling by 256 losses too much info.  I noticed the numpy array can be a float32...has anyone tried to normalize to 16k?

Also, I'm not super familiar with Python and my understanding is you can't overload classes...so where did you make your changes?  Did you make changes to the keras modules in your site-packages dir or is there some other way to make these changes without modifying the downloaded code?
