### ISSUE TITLE
Tensor Tensor("dense_2/Sigmoid:0", shape=(?, 1), dtype=float32) is not an element of this graph.

### ISSUE THREAD

**Issue by ru8anraj** [keras-team/keras#10431]
I am facing this issue. I am running the model inside a flask server. This error happens in the model.predict() line which is inside a route.

**Comment by hgaiser** [comment]
Assuming you're using tensorflow, try this:

```python
import keras
import tensorflow as tf
model = keras.models.load_model(<model_file>)
model._make_predict_function()
graph = tf.get_default_graph()

def some_route(...):
	...
	global graph
	with graph.as_default():
		outputs = model.predict(inputs)
	...
```

**Comment by ru8anraj** [comment]
no im using conv2d sequential model from keras

**Comment by ru8anraj** [comment]
i have 2 dense  in my model
 model.add(Dense(units = 128, activation = 'relu'))
 model.add(Dense(units = 1, activation = 'relu'))

this second dense is causing the trouble i guess.. 
but this is completely working fine without server

**Comment by hgaiser** [comment]
> no im using conv2d sequential model from keras

Your Keras is probably using tensorflow as backend, which is what I was referring to. Did you try the code I mentioned earlier?

**Comment by ru8anraj** [comment]
@hgaiser ur suggestion fixed my error. tanx a lot brother.

**Comment by hgaiser** [comment]
:+1: 

Can you close the issue then?

**Comment by sulhicader** [comment]
I got below error when i tried the above code

tensorflow.python.framework.errors_impl.FailedPreconditionError: Error while reading resource variable dense_2/bias from Container: localhost. This could mean that the variable was uninitialized. Not found: Container localhost does not exist. (Could not find resource: localhost/dense_2/bias)
	 [[{{node dense_2/BiasAdd/ReadVariableOp}}]]

**Comment by tngan** [comment]
@sulhicader I have encountered the same issue. Have you resolved it ?
