### ISSUE TITLE
model save error--TypeError: can't pickle NotImplementedType objects

### ISSUE THREAD

**Issue by songjuneseok** [keras-team/keras#10433]
-in ubuntu16.04.1
-in keras 2.1.6

here is my try

model =Sequential()
model.add(Dense(4096, input_shape=(3,), activation='relu'))
model.add(Dense(2048, activation='relu'))
model.add(Dense(1024, activation='relu'))
model.add(Dense(512, activation='relu'))
model.add(Dense(256, activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(4, activation='relu'))
model.add(Dense(2, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
parallel_model = multi_gpu_model(model, gpus=4)
parallel_model.compile(loss='binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])
parallel_model.fit(x_train,y_train,epochs = 1, batch_size =2000)
model.save('test_train_model_re_re.h5')

and save moment, this error is occur.

TypeError: can't pickle NotImplementedType objects

i didn't use call_back method.

why this error is occur and please give some solution

**Comment by hgaiser** [comment]
```python
from keras.layers import Dense
from keras.models import Sequential
model =Sequential()
model.add(Dense(4096, input_shape=(3,), activation='relu'))
model.add(Dense(2048, activation='relu'))
model.add(Dense(1024, activation='relu'))
model.add(Dense(512, activation='relu'))
model.add(Dense(256, activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(4, activation='relu'))
model.add(Dense(2, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.save('test_train_model_re_re.h5')
```
Runs fine for me on Arch, Keras 2.2.0, tensorflow 1.8.0.

**Comment by songjuneseok** [comment]
is run multi-gpu environment???
