### ISSUE TITLE
ERROR: "Model has not attribute name"

### ISSUE THREAD

**Issue by Saisuchith** [keras-team/keras#10434]
i have written this code and got the error "model has no attribute name"
![code](https://user-images.githubusercontent.com/28287182/41410192-4441909e-6ff6-11e8-9091-cb9e64857fd3.png)

and the error is
![error](https://user-images.githubusercontent.com/28287182/41410221-610546bc-6ff6-11e8-8b7f-53ebb2dc3e19.png)

Thanks in advance

**Comment by hgaiser** [comment]
Could you print `decoder_inputs` before passing it to `Model`? Looking at the code and the error, it would seem that `decoder_inputs` is of type `Model`. I cannot see why this would be the case, based on the code you provided, but the error would indicate that.

**Comment by hgaiser** [comment]
Interestingly, when looking at this issue, I made this fix: https://github.com/keras-team/keras/pull/10435

However, the unit test fails with exactly your error.. I haven't looked further yet, I'm busy with other things at the moment.

**Comment by Saisuchith** [comment]
i inserted print(decoder_inputs) statement before the Model and i got this as ouput
`Tensor("embedding_4/embedding_lookup:0", shape=(?, ?, 300), dtype=float32)`

**Comment by hgaiser** [comment]
Yeah that seems fine. I suggest to keep an eye out for #10435 since it is likely to fix your issue.

**Comment by Saisuchith** [comment]
thanks for replying!!

**Comment by fchollet** [comment]
I've fixed the error reported by @hgaiser. As for your error: the problem is that the `inputs` arguments to your `Model` should come from a call to `Input()`. In your case, you're writing:

```python
decoder_inputs = Input(...)
decoder_inputs = Embedding(...)(...)
```

Thus your `decoder_inputs` don't come from `Input()` but from `Embedding()`. Just rename the output of `Embedding` and you'll be fine.

**Comment by Saisuchith** [comment]
I changed the name and it worked. 

Thank you very much. You guys helped me a lot !!
