### ISSUE TITLE
keras.utils.get_file(..., extract=True) will extract original file every time it is called.

### ISSUE THREAD

**Issue by ywwynm** [keras-team/keras#10436]
`keras.utils.get_file(..., extract=True)` will extract original zipped file every time it is called, if parameter `fname` is just a file name, which means the file will be downloaded to default cache directory of Keras (`~/.keras` on Linux).

I think it's better to check if the file has been extracted successfully under this situation, because it's not the caller's responsibility to decide whether he or she should set `extract` to `True` or `False`. From the caller's perspective, he should always set `extract` to `True` if the file to get is zipped. On the other hand, in fact, the caller cannot know when to set it to `False` because the cache directory is owned by Keras and should be a black box to outside, which means the judgement of something like `is_downloaded_file_extracted_successfully_before`(the simplest way is to check if directory with same name exists) should not be made by the caller but Keras.

I met this problem from TensorFlow's official tutorial at [this page](https://www.tensorflow.org/tutorials/text_classification_with_tf_hub). On section Getting Started - data, they use following code to load the [Large Movie Review Dataset v1.0](http://ai.stanford.edu/~amaas/data/sentiment/)
```
dataset = tf.keras.utils.get_file(
      fname="aclImdb.tar.gz", 
      origin="http://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz", 
      extract=True)
```
And this dataset contains **50000 sporadic text files**. Every time we call it, it will cost a very long time extracting the original file. Considering the influence of Keras is increasing quickly and we now have a good relationship with TensorFlow like the example above, I hope Keras can do a check before extraction. Thanks.

**Comment by yanboliang** [comment]
@ywwynm You have a good point, but I think it's hard to check whether the file is extracted successfully before, it's too tricky to just check the filename. Do you know some better way can handle it?

**Comment by ywwynm** [comment]
@yanboliang Maybe we can open the zip file, select some directories/files randomly (not for every files because we should not spend a lot of time on this validation) and check their hashes. Then we can see if corresponding unzipped file exists outside and if their hashes are the same with unzipped ones.

**Comment by garikhgh** [comment]
Hello.
How can a file be loaded via keras, if the file is stored in the machine.
is there any method?
