### ISSUE TITLE
Why Flatten layer force to turn image_format to NHWC?

### ISSUE THREAD

**Issue by ghostplant** [keras-team/keras#10449]
The configuration of keras.json sets image_format to channels_first. However, the Flatten Layer in a model will turn the data into NHWC format as the input of following layers. Any reasons?

**Comment by raymond-yuan** [comment]
The [`Flatten`](https://keras.io/layers/core/#flatten) layer should default to the `image_data_format` value set in your Keras config file. The keyword `image_format` might be deprecated? the default keras config looks like: 
```
{
    "image_data_format": "channels_last",
    "epsilon": 1e-07,
    "floatx": "float32",
    "backend": "tensorflow"
}
```

You can also explicitly set the `data_format` of the layer by specifying `keras.layers.Flatten(data_format='channels_first)` if you don't want to change your config (e.g. if your switching a model from one data format to another)

**Comment by ghostplant** [comment]
Hi @raymond-yuan , I checked my settings and it is `image_data_format`, so if I prefer NCHW and uses a Flatten layer, the Flatten output will be changed into NHWC, if I use two, the format will be changed twice and results in illegal: NCHW -> NHWC -> NWCH. How to disable this transform calculation?
