### ISSUE TITLE
Error by saving a model: TypeError: ('Not JSON Serializable:', Dimension( ))

### ISSUE THREAD

**Issue by ussaema** [keras-team/keras#10463]
I am trying to save a model with the model.save( ) but I am getting the following error:
> <ipython-input-72-2da0ffaf5447> in <module>()
> ----> 1 train()
> 
> <ipython-input-71-07b1091d03bc> in train()
>      68         if models_h5_save:
>      69           for model_name in models:
> ---> 70             model_h5_file= save_model(model=models[model_name], file_name=model_name, dir=models_h5_dir)
>      71             if save2local:
>      72               send2local(file_dir=model_h5_file)
> 
> <ipython-input-58-9097a38c6b21> in save_model(model, file_name, dir)
>       8 
>       9   if not file_name: raise AssertionError()
> ---> 10   model.save(dir+file_name+".h5")
>      11   return dir+file_name+".h5"
> 
> /usr/local/lib/python3.6/dist-packages/keras/engine/topology.py in save(self, filepath, overwrite, include_optimizer)
>    2589         """
>    2590         from ..models import save_model
> -> 2591         save_model(self, filepath, overwrite, include_optimizer)
>    2592 
>    2593     def save_weights(self, filepath, overwrite=True):
> 
> /usr/local/lib/python3.6/dist-packages/keras/models.py in save_model(model, filepath, overwrite, include_optimizer)
>     125             'class_name': model.__class__.__name__,
>     126             'config': model.get_config()
> --> 127         }, default=get_json_type).encode('utf8')
>     128 
>     129         model_weights_group = f.create_group('model_weights')
> 
> /usr/lib/python3.6/json/__init__.py in dumps(obj, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
>     236         check_circular=check_circular, allow_nan=allow_nan, indent=indent,
>     237         separators=separators, default=default, sort_keys=sort_keys,
> --> 238         **kw).encode(obj)
>     239 
>     240 
> 
> /usr/lib/python3.6/json/encoder.py in encode(self, o)
>     197         # exceptions aren't as detailed.  The list call should be roughly
>     198         # equivalent to the PySequence_Fast that ''.join() would do.
> --> 199         chunks = self.iterencode(o, _one_shot=True)
>     200         if not isinstance(chunks, (list, tuple)):
>     201             chunks = list(chunks)
> 
> /usr/lib/python3.6/json/encoder.py in iterencode(self, o, _one_shot)
>     255                 self.key_separator, self.item_separator, self.sort_keys,
>     256                 self.skipkeys, _one_shot)
> --> 257         return _iterencode(o, 0)
>     258 
>     259 def _make_iterencode(markers, _default, _encoder, _indent, _floatstr,
> 
> /usr/local/lib/python3.6/dist-packages/keras/models.py in get_json_type(obj)
>     102             return obj.__name__
>     103 
> --> 104         raise TypeError('Not JSON Serializable:', obj)
>     105 
>     106     from . import __version__ as keras_version
> 
> TypeError: ('Not JSON Serializable:', Dimension(14))

how can I solve it ?

**Comment by shubham8garg** [comment]
Facing the same issue
