### ISSUE TITLE
CuDNNGRU no keyword input_dim

### ISSUE THREAD

**Issue by NumesSanguis** [keras-team/keras#10471]
My understanding of CuDNNGRU is that it should have the same interface as GRU, except that it only runs on a GPU with TensorFlow.

The following code works:

    model = Sequential()
    model.add(GRU(n_hidden_nodes, return_sequences=True, input_dim=17))

However the following code

    model = Sequential()
    model.add(CuDNNGRU(n_hidden_nodes, return_sequences=True, input_dim=17))

gives the error: `TypeError: ('Keyword argument not understood:', 'input_dim')`

System:

- Ubuntu 16.04
- Nvidia 1080TI
- Keras v2.1.6
- TensorFlow v1.7.0

<details>
  <summary>Full error code (Click to expand)</summary>

    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    <ipython-input-33-bf582dcd9cbe> in <module>()
         31     return model
         32 
    ---> 33 model = create_model3(n_input_nodes=17, n_hidden_nodes=512)  # p1_matrix.shape[1]
         34 print(model.inputs)

    <ipython-input-33-bf582dcd9cbe> in create_model3(n_input_nodes, n_hidden_nodes)
         22     #model.add(Embedding(n_input_nodes, n_hidden_nodes, input_length=17))
         23     #input_layer = Input(shape=(n_input_nodes,))
    ---> 24     model.add(CuDNNGRU(n_hidden_nodes, return_sequences=True, input_dim=17))  # , input_dim=17
         25     model.add(CuDNNGRU(n_hidden_nodes, return_sequences=True))  # CuDNNGRU
         26     model.add(Dropout(0.5))

    ~/anaconda3/envs/env/lib/python3.6/site-packages/keras/layers/cudnn_recurrent.py in __init__(self, units, kernel_initializer, recurrent_initializer, bias_initializer, kernel_regularizer, recurrent_regularizer, bias_regularizer, activity_regularizer, kernel_constraint, recurrent_constraint, bias_constraint, return_sequences, return_state, stateful, **kwargs)
        197             return_state=return_state,
        198             stateful=stateful,
    --> 199             **kwargs)
        200 
        201         self.kernel_initializer = initializers.get(kernel_initializer)

    ~/anaconda3/envs/env/lib/python3.6/site-packages/keras/layers/cudnn_recurrent.py in __init__(self, return_sequences, return_state, go_backwards, stateful, **kwargs)
         37             raise RuntimeError('CuDNN RNNs are only available '
         38                                'with the TensorFlow backend.')
    ---> 39         super(RNN, self).__init__(**kwargs)
         40         self.return_sequences = return_sequences
         41         self.return_state = return_state

    ~/anaconda3/envs/env/lib/python3.6/site-packages/keras/engine/topology.py in __init__(self, **kwargs)
        291         for kwarg in kwargs:
        292             if kwarg not in allowed_kwargs:
    --> 293                 raise TypeError('Keyword argument not understood:', kwarg)
        294         name = kwargs.get('name')
        295         if not name:

    TypeError: ('Keyword argument not understood:', 'input_dim')

</details>

**Comment by raymond-yuan** [comment]
CuDNNGRU's are actually the [cudnn](https://developer.nvidia.com/cudnn) implementation of the GRU layer, it's not just that it runs on a GPU with TensorFlow. It also has less features than the regular GRU layer (no dropout, recurrent dropout, etc.) but (should) have considerable speed up. As such, they have different interfaces.  

See [here](https://keras.io/layers/recurrent/#cudnngru) for more in depth documentation.

**Comment by NumesSanguis** [comment]
Thank you for your explanation.

Is there a reason not to support `input_dim` directly though? Seems like it would be a small change that would make Keras slightly more user-friendly. Pointing to the Guiding principles:

> **User friendliness**. Keras is an API designed for human beings, not machines. It puts user experience front and center. Keras follows best practices for reducing cognitive load: it offers consistent & simple APIs, it minimizes the number of user actions required for common use cases, and it provides clear and actionable feedback upon user error.
