### ISSUE TITLE
Convert keras model to pb file

### ISSUE THREAD

**Issue by pd1316** [keras-team/keras#10488]
I am doing a project to run keras model on Android.  When I convert the keras model to pb file using 
freeze_graph. There is an error that :
***************************************************************************************************
    assert d in name_to_node, "%s is not in graph" % d
AssertionError: output/Linear_ is not in graph.
**************************************************************************************************
But the jason file displays that the name of last layer is "output", and the activation function is "linear".
However, when I set another layer as the output node with the activation function of "relu".  The model is converted successfully. 
How to solve this problem.
Thanks.

**Comment by raymond-yuan** [comment]
Can you try setting the output node name to `model.output.name.split(":")[0]`?

**Comment by pd1316** [comment]
@raymond-yuan  Thanks!  It works.
