### ISSUE TITLE
pipdeptree finds cyclic dependencies

### ISSUE THREAD

**Issue by bersbersbers** [keras-team/keras#10505]
The newly introduced packages `keras-preprocessing` and `keras-applications` lead to cyclic-dependencies warnings in `pipdeptree`:

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

```
C:\Users\me>pipdeptree
Warning!! Cyclic dependencies found:
* Keras => keras-preprocessing => Keras
* Keras => keras-applications => Keras
* Keras-Preprocessing => keras => Keras-Preprocessing
* Keras-Applications => keras => Keras-Applications
...
```

This causes Keras and its dependencies to be hidden in the `pipdeptree` output. I just spent half an hour figuring out why pyYAML was updated in my system, although I had never installed it and `pipdeptree` did not list it at all (`pipdeptree --all` finally did).

**Comment by scele** [comment]
We're also struggling to use the latest version of Keras due to this issue. The circular dependencies are causing trouble when using keras through bazel rules.

**Comment by erwa** [comment]
We also encountered this same issue trying to import the Keras, Keras-Applications, and Keras-Preprocessing artifacts into our internal artifact repository. Would it be possible to remove the circular dependencies (I agree with @bersbersbers that Keras should probably not depend on Keras-Applications and Keras-Preprocessing).

**Comment by erwa** [comment]
Seems like Keras-Applications and Keras-Preprocessing just require Keras >= 2.1.6, and Keras 2.1.6 doesn't have any dependencies on Keras-Applications or Keras-Preprocessing so we can use Keras 2.1.6 for now with the latest versions of Keras-Applications and Keras-Preprocessing.
