### ISSUE TITLE
High CPU Usage and low GPU-Util but high GPU Memory Usage

### ISSUE THREAD

**Issue by XSeaty** [keras-team/keras#10504]
I run a keras model on Ubuntu with cuda8.0.
KerasModel: I do not have such problem with some model but with the model that have a custom layer which take list of tensor as input and list of tensor as output. And I use keras.backend.prod.
package info : Keras 2.1.0 ; Tensorflow-Gpu 1.4.0
GPU info: Tesla K40m
![image](https://user-images.githubusercontent.com/40487989/41767324-e4724ad6-763b-11e8-8f3b-85b7b6c8772f.png)
![image](https://user-images.githubusercontent.com/40487989/41767775-17960e06-763d-11e8-811d-57e572ba46e6.png)

Are there anybody know about how to fix this?

**Comment by XSeaty** [comment]
The keras.backend.prod is just what causes such problem

**Comment by lilaczhou** [comment]
@XSeaty what do you mean?my gpu memory usage is high but low gpu util,I guess it results from 
gpu -->cpu-->gpu,but I donot know how to judge if the code uses gpu and how to make it use gpu.
![image](https://user-images.githubusercontent.com/45725450/64153145-c6436a80-ce60-11e9-92bc-bc6ded7ffa37.png)
I think line 127 donot use gpu,and in landmark_block,there are some loops ,but I have put them in keras.layer,however, it seems make no sense.
![image](https://user-images.githubusercontent.com/45725450/64153273-17535e80-ce61-11e9-8d74-07938588f657.png)
