### ISSUE TITLE
Keras to ONNX Converter

### ISSUE THREAD

**Issue by wschin** [keras-team/keras#10511]
Not sure if Keras community is interested in an ONNX exporter now. I noticed an old issue where not everyone likes this idea. As we have implemented [a Keras-to-ONNX converter](https://github.com/onnx/onnxmltools), I'd like to know if you have any new comments and if this tool can help others. Note that our tool's examples can be found [here](https://github.com/onnx/onnxmltools/blob/401354a4136ba3c6cd62e1978adf7e711ed6a733/tests/end2end/test_single_operator_with_cntk_backend.py#L407).

Thank you for reading this message.

Wei-Sheng

**Comment by mohankumarSriram** [comment]
Hi @wschin, Thank you for the implementation. I'm trying to convert my keras model below to ONNX,
```
model = keras.Sequential([
     keras.layers.Dense(64, activation=tf.nn.sigmoid, 
                       input_shape=(train_data.shape[1],), name="layer1"),
    keras.layers.Dense(64, activation=tf.nn.sigmoid, name="layer2"),
    keras.layers.Dense(1, name="layer3")
  ])
onnx_model = onnxmltools.convert_keras(model)
```
But I get the following error:
  onnx_model = onnxmltools.convert_keras(model)
  File "~/.local/lib/python3.6/site-packages/onnxmltools/convert/main.py", line 38, in convert_keras
    doc_string, targeted_onnx, custom_conversion_functions, custom_shape_calculators)
  File "~/.local/lib/python3.6/site-packages/onnxmltools/convert/keras/convert.py", line 47, in convert
    onnx_model = convert_topology(topology, name, doc_string, targeted_onnx)
  File "~/.local/lib/python3.6/site-packages/onnxmltools/convert/common/_topology.py", line 701, in convert_topology
    _registration.get_converter(operator.type)(scope, operator, container)
  File "~/.local/lib/python3.6/site-packages/onnxmltools/convert/keras/operator_converters/Dense.py", line 44, in convert_keras_dense
    apply_activation_function = _activation_map[operator.raw_operator.activation]
KeyError: <function sigmoid at 0x7f14600657b8>

Can you please check if I'm missing something here?

**Comment by wschin** [comment]
Could you try `activation='sigmoid'` when creating those dense layers? The reason is that currently onnxmltools expects standard keras activation parameters because of [this](https://github.com/onnx/onnxmltools/blob/c2c14e608a7abb0ea3e742814564e0504d040fcf/onnxmltools/convert/keras/operator_converters/Dense.py#L13). Thanks a lot for your feedback!

**Comment by mohankumarSriram** [comment]
It worked! Thank you @wschin. I need to load my keras trained model onto a microcontroller for inference. But right now, CMSIS NN lib only supports weight quantization for caffe models. So I decided to do the following conversion keras -> onnx -> caffe.

**Comment by ADV-LUT** [comment]
Hello @wschin ,
I hope you can help me with my problems too. I try to save a simple model in ONNX, but have several problems. Here is my current model:
```
import tensorflow as tf
from tensorflow import keras

from keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

train_images = train_images / 255.0

from keras import models
from keras import layers

network = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(32, activation='sigmoid'),
    keras.layers.Dense(32, activation='sigmoid'),
    keras.layers.Dense(32, activation='sigmoid'),
    keras.layers.Dense(10, activation='softmax')
])

network.compile(optimizer='Adam', 
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

network.fit(train_images, train_labels, epochs=5)

import onnxmltools
from keras.models import Model
onnx_model = onnxmltools.convert_keras(network)
```

But I get following error:

RuntimeError                              Traceback (most recent call last)
<ipython-input-7-6745b902d332> in <module>
      1 import onnxmltools
      2 from keras.models import Model
----> 3 onnx_model = onnxmltools.convert_keras(network)

/usr/local/lib/python3.5/dist-packages/onnxmltools/convert/main.py in convert_keras(model, name, initial_types, doc_string, target_opset, targeted_onnx, channel_first_inputs, custom_conversion_functions, custom_shape_calculators, default_batch_size)
     28     from .keras.convert import convert
     29     return convert(model, name, default_batch_size, initial_types, doc_string, target_opset, targeted_onnx,
---> 30                    channel_first_inputs, custom_conversion_functions, custom_shape_calculators)
     31 
     32 

/usr/local/lib/python3.5/dist-packages/onnxmltools/convert/keras/convert.py in convert(model, name, default_batch_size, initial_types, doc_string, target_opset, targeted_onnx, channel_first_inputs, custom_conversion_functions, custom_shape_calculators)
     39     target_opset = target_opset if target_opset else get_opset_number_from_onnx()
     40     topology = parse_keras(model, default_batch_size, initial_types, target_opset,
---> 41                            custom_conversion_functions, custom_shape_calculators)
     42 
     43     topology.compile()

/usr/local/lib/python3.5/dist-packages/onnxmltools/convert/keras/_parse.py in parse_keras(model, default_batch_size, initial_types, target_opset, custom_conversion_functions, custom_shape_calculators)
    118     # model/layer sharing.
    119     for node in _extract_inbound_nodes(model):
--> 120         _parse_keras(topology, scope, model, node)
    121 
    122     topology.root_names = [variable.onnx_name for variable in scope.variables.values()]

/usr/local/lib/python3.5/dist-packages/onnxmltools/convert/keras/_parse.py in _parse_keras(topology, parent_scope, model, inbound_node)
    179 
    180     else:
--> 181         raise RuntimeError('Unsupported Keras component %s' % type(model))

RuntimeError: Unsupported Keras component <class 'tensorflow.python.keras.engine.sequential.Sequential'>

Can you please check if I'm missing something, with save in the h5-format I have no problems, but I want to use the ONNX in the future.

**Comment by tlc10** [comment]
Hi!
When I'm running this code :
"import onnxmltools

onnx_model = onnxmltools.convert_keras(nn) 

onnxmltools.utils.save_model(onnx_model, 'keras_example.onnx')"

I've this error, 

 File "C:\Users\...\lib\site-packages\onnxmltools\convert\main.py", line 26, in convert_keras
    raise RuntimeError('keras2onnx is not installed. Please install it to use this feature.')
RuntimeError: keras2onnx is not installed. Please install it to use this feature.

Can you help me please ?

**Comment by jiafatom** [comment]
@tlc10 Can you `pip install keras2onnx` ? onnxmltools is a wrapper of several converters.

**Comment by tlc10** [comment]
@jiafatom yes I've already done it ... but the requierement is "already satisfied"

**Comment by ge-haoyue** [comment]
@tlc10 Same problem..
