### ISSUE TITLE
Can I use a binary index to the embedding layer instead of using integer index

### ISSUE THREAD

**Issue by moe-iq** [keras-team/keras#10515]
The current embedding layer implementation accepts inputs as integer numbers. My question is, can I use binary numbers as inputs to the embedding? and if yes, how?

**Comment by chrishna1** [comment]
why don't you convert those binary numbers to integer then feed it. you can use `int('10001', 2)` to convert binary to integer in python.

**Comment by moe-iq** [comment]
defenitley I can convert them to integer, but I am working on a project and need to use binary numbers.
