### ISSUE TITLE
InvalidArgumentError when using tensorboard in keras

### ISSUE THREAD

**Issue by hannahawalsh** [keras-team/keras#10512]
I am training a sequence-to-sequence encoder-decoder model using Keras with a tensorflow backend. everything is up to date. I tried adding in the TensorBoard callback like this: 

`
earlystopping = EarlyStopping(monitor='val_loss', patience=3)
tensorboard = TensorBoard(log_dir="log/{}".format(time()),
                            histogram_freq=1, embeddings_freq=1)
his = model.fit([training_encoder_input, training_decoder_input],
                [training_decoder_output],
                batch_size=BATCH_SIZE,
                epochs=EPOCHS,
                validation_split=0.2,
                callbacks=[earlystopping, tensorboard])
` 

However, when I try to run the code, it gives me the error:

InvalidArgumentError: indices[11,17] = 1265 is not in [0, 256)
	 [[Node: embedding_1/embedding_lookup = GatherV2[Taxis=DT_INT32, Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@training/Adam/Assign_2"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](embedding_1/embeddings/read, embedding_1/Cast, training/Adam/gradients/embedding_1/embedding_lookup_grad/concat/axis)]]

I am not sure what is wrong. It works perfectly without it.

**Comment by Hanszhuang** [comment]
the same issue,wait for help
