### ISSUE TITLE
how to convert channels_first model to channels_last model or Vice versa?

### ISSUE THREAD

**Issue by aligoglos** [keras-team/keras#10522]
i have model trained with channels_first  input shape ( 1 * 32 * 32)  and store it. but now i want change order of model and my model become channels_last with out retrain it.
how can i do it?

**Comment by wschin** [comment]
Maybe add a numpy permute (to change [N, C, H, W] to [N, H, W, C]) before feeding your new inputs into your old model?

**Comment by aligoglos** [comment]
i guess must change ordering of weights and architects of model before feeding new input.
but i don't know haw do it.

**Comment by wschin** [comment]
You need to do something like np.transpose(your_old_input, [0, 2, 3, 1]) if your old input is a 4-D, [N, C, H, W] tensor.

**Comment by yanboliang** [comment]
@aligoglos What about writing preprocessing code to convert input data into correct format? You can refer [this simple example](https://github.com/keras-team/keras/blob/master/examples/mnist_cnn.py):
```
(x_train, y_train), (x_test, y_test) = mnist.load_data()

if K.image_data_format() == 'channels_first':
    x_train = x_train.reshape(x_train.shape[0], 1, img_rows, img_cols)
    x_test = x_test.reshape(x_test.shape[0], 1, img_rows, img_cols)
    input_shape = (1, img_rows, img_cols)
else:
    x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
    x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)
    input_shape = (img_rows, img_cols, 1)
```

**Comment by aligoglos** [comment]
this good for python side, but i want use keras models in c++ and library i use it, just accept channels_last models. for this reason i need to modify the pre-trained mode.

**Comment by wschin** [comment]
You need to implement my python example (np.transpose). Conceptually, model cannot be modified, but you can change the input format by your code.
