### ISSUE TITLE
Variable target_size for ImageDataGenerator

### ISSUE THREAD

**Issue by The-Gupta** [keras-team/keras#10539]
I want to use image augmentation (with ImageDataGenerator) and have images retain its original dimensions or at least the shape when I decide to divide dimensions by a common factor. How do I do that - I could not find a way?

**Here's the complete code**

```
from keras.models import Sequential
from keras import optimizers
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, GlobalMaxPooling2D


numClass = 4

classifier = Sequential()


classifier.add(Conv2D(64, (3, 3), input_shape = (None, None, 3), activation = 'relu'))
classifier.add(MaxPooling2D(pool_size = (2, 2)))
#classifier.add(Dropout(0.2))

classifier.add(Conv2D(128, (3, 3), activation = 'relu'))
classifier.add(MaxPooling2D(pool_size = (2, 2)))
#classifier.add(Dropout(0.2))

classifier.add(Conv2D(256, (3, 3), activation = 'relu'))
classifier.add(MaxPooling2D(pool_size = (2, 2)))
#classifier.add(Dropout(0.3))


classifier.add(GlobalMaxPooling2D())


classifier.add(Dense(units = 512, activation = 'relu'))
#classifier.add(Dropout(0.5))
classifier.add(Dense(units = numClass, activation = 'softmax'))


classifier.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])
#classifier.compile(optimizer = 'rmsprop', loss = 'categorical_crossentropy', metrics = ['accuracy'])



from keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(rescale = 1./255)
test_datagen = ImageDataGenerator(rescale = 1./255)

training_set = train_datagen.flow_from_directory('Dataset/train',
                                                 target_size = (None, None),
                                                 batch_size = 16, 
                                                 class_mode = 'categorical')

test_set = test_datagen.flow_from_directory('Dataset/test',
                                            target_size = (None, None),
                                            batch_size = 16,
                                            class_mode = 'categorical')

classifier.fit_generator(training_set,
                         steps_per_epoch = 444,
                         epochs = 20,
                         validation_data = test_set,
                         validation_steps = 80)
```

**ERROR:**
Traceback (most recent call last):

  File "<ipython-input-36-f6606b226f74>", line 61, in <module>
    validation_steps = 80)

  File "F:\SumeshData\PANDIT\Anaconda3\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)

  File "F:\SumeshData\PANDIT\Anaconda3\lib\site-packages\keras\engine\training.py", line 1426, in fit_generator
    initial_epoch=initial_epoch)

  File "F:\SumeshData\PANDIT\Anaconda3\lib\site-packages\keras\engine\training_generator.py", line 155, in fit_generator
    generator_output = next(output_generator)

  File "F:\SumeshData\PANDIT\Anaconda3\lib\site-packages\keras\utils\data_utils.py", line 584, in get
    six.raise_from(StopIteration(e), e)

  File "<string>", line 3, in raise_from

StopIteration: 'NoneType' object cannot be interpreted as an integer

**Comment by reckdk** [comment]
For keep_aspect_ratio function, you can refer to the discussion in #4987.
