### ISSUE TITLE
how to put part of the Input tensor into the keras layer

### ISSUE THREAD

**Issue by suchen-sci** [keras-team/keras#10546]
Suppose i have a input tensor with shape of batch_size * 10 * 10, and i want to put the shape of batch_size * 10 into the layers for 10 times, is that means the only way to do this is to make 10 Input? 

for example, 
x = Input(batch_shape = (batch_szie, 10, 10))
I try Dense()(x[:,0,:]) but it says no tensor history

Can some one help me with this?

Best wishes

**Comment by yanboliang** [comment]
I think the simplest way is to repeat input batch 10 times, but does it make a lot of sense to use in this way?

**Comment by tomastheod-ITI** [comment]
Using your definition of x, this should work:
```
from keras.layers import Lambda
x_elem = Lambda(lambda x: x[:, 0, :])(x)
```
