### ISSUE TITLE
train two CNN jointly? 

### ISSUE THREAD

**Issue by scstu** [keras-team/keras#10557]
is there a way to train Two-stream convolutional neural network jointly in keras? 
for example I want to train two AlexNet without top layers then add Fc layers to learn late fusion, those two CNN get images from different modality (different images source for each CNN) ?

**Comment by Inferno-P** [comment]
Interesting! May I ask what's your objective? Is it regarding video conceptualisation ?

**Comment by scstu** [comment]
No, it's not. My objective is to take advantage of different sensors available and extract features for the same scene from different modality.

**Comment by brge17** [comment]
Yes, Keras supports single/multiple input & single/multiple output.

Use the function API, with two inputs and a merge layer.

**Comment by scstu** [comment]
I did this but still have a problem with `model.fit_generator` 
`train_datagen = ImageDataGenerator(rescale=1. / 255, preprocessing_function=preprocess_input)
train_generator_colored = train_datagen.flow_from_directory(train_data_dir_colored,
                                  target_size=(224, 224),
                                  class_mode='categorical', 
                                  batch_size=32,
                                  shuffle=True)

valid_datagen = ImageDataGenerator(rescale=1. / 255, preprocessing_function=preprocess_input)
validation_generator_colored = valid_datagen.flow_from_directory(validation_data_dir_colored,
                                  target_size=(224, 224),
                                  class_mode='categorical', 
                                  batch_size=32)


## create data generator 


train_datagen = ImageDataGenerator(rescale=1. / 255, preprocessing_function=preprocess_input)
train_generator = train_datagen.flow_from_directory(train_data_dir,
                                  target_size=(224, 224),
                                  class_mode='categorical', 
                                  batch_size=32,
                                  shuffle=True)

valid_datagen = ImageDataGenerator(rescale=1. / 255, preprocessing_function=preprocess_input)
validation_generator = valid_datagen.flow_from_directory(validation_data_dir,
                                  target_size=(224, 224),
                                  class_mode='categorical', 
                                  batch_size=32)`
`history = model.fit_generator(
    [train_generator, train_generator_colored],
    steps_per_epoch=nb_train_samples//32,
    epochs=nb_epoch,
    validation_data=validation_generator,
    validation_steps = nb_validation_samples//32,
    callbacks=[reduce_lr])`

I got this error : 

`TypeError                                 Traceback (most recent call last)
<ipython-input-13-2726c4a8ad9b> in <module>()
     18     validation_data=validation_generator,
     19     validation_steps = nb_validation_samples//32,
---> 20     callbacks=[reduce_lr])
     21 
     22 

/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.pyc in wrapper(*args, **kwargs)
     89                 warnings.warn('Update your `' + object_name +
     90                               '` call to the Keras 2 API: ' + signature, stacklevel=2)
---> 91             return func(*args, **kwargs)
     92         wrapper._original_function = func
     93         return wrapper

/usr/local/lib/python2.7/dist-packages/keras/models.pyc in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   1254                                         use_multiprocessing=use_multiprocessing,
   1255                                         shuffle=shuffle,
-> 1256                                         initial_epoch=initial_epoch)
   1257 
   1258     @interfaces.legacy_generator_methods_support

/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.pyc in wrapper(*args, **kwargs)
     89                 warnings.warn('Update your `' + object_name +
     90                               '` call to the Keras 2 API: ' + signature, stacklevel=2)
---> 91             return func(*args, **kwargs)
     92         wrapper._original_function = func
     93         return wrapper

/usr/local/lib/python2.7/dist-packages/keras/engine/training.pyc in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   2143                 batch_index = 0
   2144                 while steps_done < steps_per_epoch:
-> 2145                     generator_output = next(output_generator)
   2146 
   2147                     if not hasattr(generator_output, '__len__'):

/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.pyc in get(self)
    768             success, value = self.queue.get()
    769             if not success:
--> 770                 six.reraise(value.__class__, value, value.__traceback__)

/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.pyc in _data_generator_task(self)
    633                             # => Serialize calls to
    634                             # infinite iterator/generator's next() function
--> 635                             generator_output = next(self._generator)
    636                             self.queue.put((True, generator_output))
    637                         else:

TypeError: list object is not an iterator`

any suggestions please!

**Comment by AZweifels** [comment]
@scstu You have to provide a generator that yields something of the form ([x1, x2], y)
See here: https://github.com/keras-team/keras/issues/8130
