### ISSUE TITLE
Custom loss function which can save model weights, support subprocess calls and numpy operations

### ISSUE THREAD

**Issue by KrishnanParameswaran** [keras-team/keras#10556]
**Trying to create a custom loss function, which includes saving updated model weights, subprocess calls and numpy operations based on the updated weights after training of every batch. The loss function is defined as given below:**

def process():    
    model.save("path to updated weights' .hdf5 file")
    subprocess.call(["path to .py code which writes weights into .c code", \
    "path to updated weights' .hdf5 file", "path to .c code", \
    "path to header file of .c code"])    
    subprocess.call(["cd", "path to project directory"])
    subprocess.call(["make", "clean", "&", "make"])
    subprocess.call(["path to executable that converts input pcm file to output pcm file based on updated weights", "path to input file","path to output file"])
    data1 = np.memmap("path to output pcm file", dtype = 'h', mode = 'r')
    data2 = np.memmap("path to reference pcm file", dtype = 'h', mode = 'r')
    return data1, data2

def myloss(y_true, y_pred):
    d, c = process()
    return K.mean(K.square(d - c))

**This causes the code to keep building the model as below:**

/home/<user>/.local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Build model...
2018-06-27 23:11:45.873601: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
/home/<user>/.local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Build model...
2018-06-27 23:11:47.195850: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary wacustom loss functions not compiled to use: AVX2 FMA
/home/<user>/.local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.

**Read elsewhere that Keras loss functions accommodate only tensor/theano/CNTK operations and typically take only y_true and y_pred as arguments. Is there still a workaround to save model weights, make subprocess calls and perform numpy operations within the loss function ? Appreciate your help.**

**Comment by KrishnanParameswaran** [comment]
**So, I introduced a callback function at the end of every batch which does the subprocess calls as below:**

def on_batch_end(self, batch, model, logs = {}):
        self.model.save_weights('path to weights .hdf5 file')
        subprocess.call(["path to .py script which writes weights into .c code", "path to weights .hdf5 file", "path to .c code", "path to header file 		of .c code"])    
        subprocess.call(["cd", "path to project directory"])
        subprocess.call(["make", "clean", "&", "make"])
        subprocess.call(["path to executable that converts input pcm file to output pcm file based on updated weights", "path to input file", "path to 		output file"])
        d_data = np.memmap("path to output pcm file", dtype = 'h', mode = 'r')
        c_data = np.memmap("path to reference pcm file", dtype = 'h', mode = 'r')
        sess = tf.Session()
        with sess.as_default():
            d_tensor = tf.constant(np.array(d_data[:113280, ]).astype("float32"))
            c_tensor = tf.constant(np.array(c_data[:113280, ]).astype("float32"))
        return d_tensor, c_tensor

**And the loss function is changed not to include the subprocess calls directly in loss function (since these subprocess calls are taken care in callback function)** 

def process():    
    d_data = np.memmap("path to output pcm", dtype = 'h', mode = 'r')
    c_data = np.memmap("path to reference pcm", dtype = 'h', mode = 'r')
    sess = tf.Session()
    with sess.as_default():
        d_tensor = tf.constant(np.array(d_data[:113280, ]).astype("float32"))
        c_tensor = tf.constant(np.array(c_data[:113280, ]).astype("float32"))
    return d_tensor, c_tensor
    
def myloss(y_true, y_pred):
    d = K.placeholder(shape = (None, ))
    c = K.placeholder(shape = (None, ))
    d, c = process()
    return (K.mean(K.square(K.eval(d) - K.eval(c))))

**And the code doesn't keep building the model now :)
But there is this error which says there is an operation which has 'None' for gradient. Could you please help in identifying the operation in loss function which has no gradient and how to make it differentiable.**

Traceback (most recent call last):
  File "path to the python script", line 182, in <module>
    validation_split=0.1, callbacks=[histories])
  File "/home/user/.local/lib/python2.7/site-packages/keras/engine/training.py", line 1682, in fit
    self._make_train_function()
  File "/home/user/.local/lib/python2.7/site-packages/keras/engine/training.py", line 992, in _make_train_function
    loss=self.total_loss)
  File "/home/user/.local/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/keras/optimizers.py", line 445, in get_updates
    grads = self.get_gradients(loss, params)
  File "/home/user/.local/lib/python2.7/site-packages/keras/optimizers.py", line 80, in get_gradients
    raise ValueError('An operation has `None` for gradient. '
ValueError: An operation has `None` for gradient. Please make sure that all of your ops have a gradient defined (i.e. are differentiable). Common ops without gradient: K.argmax, K.round, K.eval.

**Comment by Dref360** [comment]
You **can't** use numpy operations. TF is using a 2 step process : graph creation and graph computation. The loss is called **only** during the graph creation part. After that, only the ops in the graph are called. 

This issue isn't related to a bug/enhancement/feature request or other accepted types of issue.

To ask questions, please see the following resources : 
* https://keras.io/
* https://keras.io/#support
* https://gitter.im/Keras-io/Lobby

Thanks!

If you think I made a mistake, please re-open this issue.

**Comment by KrishnanParameswaran** [comment]
Appreciate your feedback. I did not see any **complete guideline** to create a custom loss function yet. Is there one that explains the list of operations allowed in loss function, which of those are differentiable, can those which are not differentiable still be used, options to use model weights or any other parameters as arguments instead of y_true and y_pred, how to deal with numpy or subprocess calls and so on. I would be happy to close this issue right away if answers to these questions are available in keras documentation. Thanks!

**Comment by KrishnanParameswaran** [comment]
@Dref360 Could you please reopen this issue, as I'm yet to get answers ?

**Comment by Dref360** [comment]
This issue isn't related to a bug/enhancement/feature request or other accepted types of issue.

To ask questions, please see the following resources : 
* https://keras.io/
* https://keras.io/#support
* https://gitter.im/Keras-io/Lobby

Thanks!
