### ISSUE TITLE
Printing metrics for every epochs

### ISSUE THREAD

**Issue by Mechanix12** [keras-team/keras#10564]
Hi!
While i training my model, it starts printing metrics for every epochs separately.
I set verbose = 1.
What it can be?
Thanks.
![default](https://user-images.githubusercontent.com/32762250/42079138-8e049978-7b87-11e8-8be1-7a2ed0c33c97.png)

**Comment by anmolsjoshi** [comment]
This happen from time to time. Just restart your kernel on jupyter and try again. Also, maybe resolve that warning.

**Comment by Mechanix12** [comment]
@anmolsjoshi 
It didn't help...

**Comment by amppumas** [comment]
Have you tried using the API v2 call, in my experience Jupyter and running it on IDE's mess up the output.
