### ISSUE TITLE
Can't Change layer.name Attribute

### ISSUE THREAD

**Issue by joaogantunes** [keras-team/keras#10560]
Hello,

I have trained 2 separate CNN models, one for RGB and one for Optical flow. I am now trying to fuse them into a single network. I load the RGB weights, and the optical flow weights and then need to change the names on the optical flow stream to have unique names on all layers I use this code:

`

        for layer in original_flow_stream.layers:
            # Change layer names (add an of for the optical flow layers)
            layer.name = layer.name + str("of")
            layer.trainable = False
        return original_flow_stream
`
I get the following error: 
   layer.name = layer.name + str("of")
AttributeError: can't set attribute

Saying I can't set the name of the layer. Why am I getting this error? I'm using Keras 2.1.5 with a Tensorflow backend.

Thank you!

**Comment by yanboliang** [comment]
@joaogantunes Can you provide more clues? I can't reproduce this bug in Keras 2.2 + TF 1.9 . Set with new name work well in my environment.

**Comment by spate141** [comment]
@joaogantunes @yanboliang I'm having same error! I'm on Keras 2.2 + TF 1.7
```
>> model.input.name
'embedding_1_input_3:0'
>> model.input.name = 'embd'
AttributeError: can't set attribute
```

**Comment by wjakobw** [comment]
@spate141 In my experiments, model.input returns a Tensor object (which can not be renamed), while model.layers[0] returns an InputLayer object (which can be renamed). 

    >> print(model.input.name)
    'Input_app:0'
    >> print(type(model.input))
    '<class 'tensorflow.python.framework.ops.Tensor'>'
    >> model.input.name = "some_name"
    AttributeError: can't set attribute
    
    >> print(model.layers[0].name)
    'Input_app'
    >> print(type(model.layers[0]))
    '<class 'keras.engine.topology.InputLayer'>'
    >> model.layers[0].name="some_name"
    >> print(model.layers[0].name)
    'some_name'

But I don't see how this observation could explain the behavior in the first post in this issue, unless the object `original_flow_stream` is something else than a Keras model.

**Comment by Nitinsiwach** [comment]
same issue

**Comment by elimereu** [comment]
Hi, I also have this problem but in Keras for R. Any advice? 
Thanks in advance!
