### ISSUE TITLE
Is there a way to save batches of ImageDataGenerator as it is kept in RAM?

### ISSUE THREAD

**Issue by Golbstein** [keras-team/keras#10575]
Hi guys,

I've a dataset of over million images saved in directories. Every time I start my python kernel, I've to load this batches using flow_from_directory method, and it takes me ~15 minutes each time. 

There must be a better way to do it..

**Comment by AlexZot** [comment]
I use this snippet. 

```
%%time
X = np.zeros((len(images_gen), IMAGE_WIDTH, IMAGE_HEIGHT, IMAGE_CHANNELS))
y = np.zeros((len(images_gen), len(images_gen.class_indices)))
for i in tqdm_notebook(range(len(images_gen))):  # tqdm completely optional 
    data = next(images_gen)
    X[i] = data[0]
    y[i] = data[1]
```
After that you may like to save X and y to drive as tensor.
`np.save(FILE_NAME, X)`
Loading file:  `X = np.load(FILE_NAME)`
