### ISSUE TITLE
it's possible? layer for utf-strings

### ISSUE THREAD

**Issue by nex0ma** [keras-team/keras#10582]
keras.engine.input_layer.InputUTF(utf_string, max_length=max_length)

**Comment by JamesTrick** [comment]
Hi @nex0ma 

You can't directly pass strings or text into Keras models, or really any DL/ML models. Instead, look at tokenizing the string, so you're passing a vector into the model. Keras does have a text preprocessing module that may be of interest to you [here](https://keras.io/preprocessing/text/).

Let me know if you have any further questions.

Cheers
James

**Comment by nex0ma** [comment]
i mean that any string auto-tokenized by this layer. this is more simplest. char-embedding with tokenizer in examples is a bad way, using same tokenizer for another text experiment. 
for deep learning i need one char-dictionary for YEARS of works with many texts on any languages.
so, any utf8 char will be encoded to integer automatically and will be one for all trainings.

thanks.
