### ISSUE TITLE
Matrix multiplication for trainable weights

### ISSUE THREAD

**Issue by harewei** [keras-team/keras#10583]
EDIT: it seems I was mistaken in my original question, but here's another one that spawned from it.
Is there a way for Keras to do matrix multiplication for trainable weights? (or in fact, a lot of operations)
For example, 
```
LSTM_layer = LSTM(1, return_sequences='True')
output = LSTM_layer(input)
output = Lambda(lambda x: K.reshape(x, (1, 64)))(output)
self.w_attn_2 = K.variable(np.random.random((64, 64)), dtype='float32')
z = Lambda(lambda x: K.dot(x, self.w_attn_2))(output) # Need the lambda to maintain Keras tensor
```
It seems I would probably need to use custom layers for trainable weights for simple arithmetic.  It would be a lot easier if I didn't have to.

**Comment by tRosenflanz** [comment]
Operation you have outlined is just a Dense layer without bias.

**Comment by harewei** [comment]
@tRosenflanz yeah I noticed that earlier as well, but the actual model I'm building has expanding dimension, which forces me to use placeholders and tf functions, so I can't use a simple Dense layer here.

Anyway, the solution I ended up using is to create a custom layer in Keras, and use tf.matmul operation in there.
