### ISSUE TITLE
Train on large npy files 

### ISSUE THREAD

**Issue by zaidalyafeai** [keras-team/keras#10584]
I have a folder which contains 100 .npy files each file corresponds to a different class. The shape of each file when loaded is [L, 28 * 28] where L is of variable length.  I use np.load to load the data but since I have memory limitations I have to discard some of the data. I want to train my model on all the data. From my understanding I can use flow_from_directory to load batches but I am not sure how to inform keras to load data as chunks of that format. 

How to inform keras to load chunks from npy files ?

**Comment by HemersonTacon** [comment]
I am interested in this functionality too. In my case I preprocessed videos and created "images" with more than 3 channels and because of that I needed to save the files as npy. I will keep looking for a working around and post here any news.

**Comment by Dref360** [comment]
This is a pretty limited use case so I don't think we will work on it.
You can create your own keras.utils.Sequence as many people do.

If you really need this feature, feel free to submit a PR.
