### ISSUE TITLE
callbacks.EarlyStopping should accept a function to compute the monitored quantity

### ISSUE THREAD

**Issue by giuscri** [keras-team/keras#10587]
I imagine something like `EarlyStopping(..., monitor_function=monitor_function)` where `monitor_function` is a functions that takes the model as argument and returns a number. This way one can monitor other quantities, computed by Python functions.

**Comment by giuscri** [comment]
My use-case just disappeared. If no one else is interested this can be closed.

**Comment by giuscri** [comment]
@talhasaruhan, would you find this feature helpful? What's a use-case you imagine?

**Comment by talhasaruhan** [comment]
@giuscri Honestly I don't think this is the most pressing issue, but it sounds like it could come in handy in rare circumstances. Since I believe it's not that hard to implement, I'd say it's worth adding.

**Comment by joelthchao** [comment]
@giuscri This feature is implemented. If it fits to your need, you may close this issue.
