### ISSUE TITLE
Getting "This model has never been called, thus its weights have not yet been created" when using models with TimeDistributed wrapper.

### ISSUE THREAD

**Issue by cbuffevant** [keras-team/keras#10581]
I'm facing an issue trying to create the following model (https://gist.github.com/cbuffevant/aa2065f4e49221b13585d073f1b7e140):

```
import keras
from keras.models import Sequential
from keras.layers import Dense, Conv1D, LSTM, TimeDistributed, Flatten

model = Sequential()
model.add(TimeDistributed(Conv1D(filters=64, kernel_size=64, activation='relu', input_shape=(8, 100))))
model.add(TimeDistributed(Flatten()))
model.add(LSTM(1000, activation='relu', recurrent_activation='hard_sigmoid', dropout=0.2))
model.add(Dense(3, activation='softmax'))

model.summary()
```

Call to `model.summary()` fails with the error message: 

```
This model has never been called, thus its weights have not yet been created, so no summary can be displayed. Build the model first (e.g. by calling it on some test data).
```

If I remove the TimeDistributed wrapper the call to `model.summary` works as expected. 
I ran that script using Python 3.6, Keras (master), TensorFlow 1.10.

Is this the exptect behaviour? Am I missing something related to TimeDistributed wrapper? 

I will really appreciate any help.

**Comment by oliviersoares** [comment]
@cbuffevant did you figure out the problem?

Compiling the model before calling summary() does not solve the problem.
(e.g. adding: model.compile(optimizer='rmsprop', loss='mse') before summary())

Same when using a generator (using fit_generator()) triggers this error.
However, using fit() works fine.

**Comment by StealthySemicolon** [comment]
Wait, what happened? This is happening to me too...

**Comment by EmreOzkose** [comment]
How did you solve? I have this problem, too.

**Comment by rameshjesswani** [comment]
Same problem I am also facing. Could you please tell the solution?

**Comment by ParasKaushik** [comment]
Same problem I am also facing. Could you please tell the solution?

**Comment by hemikak** [comment]
How was this solved ?

**Comment by oliviersoares** [comment]
You need to make sure you're specifying the input_shape of these TimeDistributed layers.

Something like this:

```python
import keras
from keras.models import Sequential, Model
from keras.layers import Dense, Conv1D, LSTM, TimeDistributed, Flatten, Input

model = Sequential()
x_input = Input(shape=(8, 100))
x_output = Conv1D(filters=64, kernel_size=4, activation='relu')(x_input)
base_model = Model(x_input, x_output)
model.add(TimeDistributed(base_model, input_shape=base_model.input_shape))
model.add(TimeDistributed(Flatten(input_shape=base_model.input_shape[1:])))
model.add(LSTM(1000, activation='relu', recurrent_activation='hard_sigmoid', dropout=0.2))
model.add(Dense(3, activation='softmax'))

model.summary()
```

**Comment by maxisawesome** [comment]
@oliviersoares's answer fixed the problem for me - I added input_shape=tuple to my first Conv2D layer and my model successfully printed a summary w/o compiling or training.

**Comment by amay1212** [comment]
@oliviersoares , Iam getting this error.

"Tensor objects are not iterable when eager execution is not "
TypeError: Tensor objects are not iterable when eager execution is not enabled. To iterate over this tensor use tf.map_fn.


Here is my code...


model = Sequential()
    print('env' , (num_last_frames, ) +  env.observation_shape)
    #Printing the model params 

    #Output => env (4,) ObservationSHape (10, 10)

    # Convolutions.()
    model.add(TimeDistributed(Conv2D(
        16,
        kernel_size=(3, 3),
        strides=(1, 1),
        data_format='channels_first',
        input_shape= (num_last_frames, ) +  env.observation_shape
    )))
    model.add(TimeDistributed(Activation('relu')))
    model.add(TimeDistributed(Conv2D(
        32,
        kernel_size=(3, 3),
        strides=(1, 1),
        data_format='channels_first'
    )))
    model.add(TimeDistributed(Activation('relu')))

    # Dense layers.
    model.add(TimeDistributed(Flatten()))
    #Timedistributed changes and the below 1 liner code change by me.
    model.add(Dropout(0.25))
    

    ##Adding Lstm layer to the model MY CHANGE on 24/12/2018.

    #regressor.add(LSTM(units = 50, return_sequences = True, input_shape = (X_train.shape[1], 1)))
    #regressor.add(Dropout(0.2))

    model.add(LSTM(units = 200 , return_sequences = True))
    model.add(Dropout(0.25))
    model.add(LSTM(units = 200 , return_sequences = True))
    model.add(Dropout(0.25))
    model.add(LSTM(units = 200))

    #My code change END#####
        
    model.add(Dense(256))
    model.add(Activation('relu'))
    model.add(Dense(env.num_actions))

    model.summary()
    model.compile(RMSprop(), 'MSE')
