### ISSUE TITLE
Differences in weight data structures for the Sequential and functional API?

### ISSUE THREAD

**Issue by canthonissen** [keras-team/keras#10591]
I just had an interesting situation where I built the same network architecture using the Sequential and the functional api, however if I train the one and transfer the weights to the other like so:
model2.set_weight(model1.get_weight())
and I don't get the same outputs.
I used the following code to construct the models:

# Using Sequential
model1 = Sequential()
model1.add(GRU(15, activation="relu", input_shape=(1052,12), return_sequences=True))
model1.add(Dense(1))

# Using the functional API
inlayer= Input(shape=(1052,12))
hidden= GRU(15, activation="relu", return_sequences=True)(inlayer)
outlayer = Dense(1)(hidden) 
model2 = Model(inputs=inlayer, outputs=outlayer)

It is easy to get around this by sticking to the functional API, but why would this situation occur, and is it as intended?

**Comment by Dref360** [comment]
Have you compiled your model after setting the weights?
This works for me.
```python
import numpy as np

from keras import Sequential, Input, Model
from keras.layers import GRU, Dense

model1 = Sequential()
model1.add(GRU(15, activation="relu", input_shape=(1052, 12), return_sequences=True))
model1.add(Dense(1))
model1.compile('sgd', 'mse')
model1.fit(np.random.normal(size=[40, 1052, 12]), np.random.normal(size=[40, 1052, 1]), batch_size=10, epochs=1, verbose=0)

dummy = np.random.normal(size=[10, 1052, 12])
model1_pred = model1.predict_on_batch(dummy)

inlayer = Input(shape=(1052, 12))
hidden = GRU(15, activation="relu", return_sequences=True)(inlayer)
outlayer = Dense(1)(hidden)
model2 = Model(inputs=inlayer, outputs=outlayer)
model2.set_weights(model1.get_weights())
model2.compile('sgd', 'mse')
model2_pred = model2.predict_on_batch(dummy)

np.testing.assert_allclose(model1_pred, model2_pred)
```
