### ISSUE TITLE
OSError: Unable to open file (unable to open file: name = 'D:/G/WORK/MODEL_OP/TfLearn.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

### ISSUE THREAD

**Issue by gssingadkar** [keras-team/keras#10592]
I am trying to save the model in hdf5 or h5 format, but I am getting error. I Have tried to install and upgrade packages but still getting same error again and again.
Tried all solutions available in google, git, etc.

  with h5py.File(filepath, mode='r') as f:
  File "C:\Users\admin\Anaconda3\envs\gss1\lib\site-packages\h5py\_hl\files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "C:\Users\admin\Anaconda3\envs\gss1\lib\site-packages\h5py\_hl\files.py", line 142, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = 'D:/G/WORK/MODEL_OP/TfLearn.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

Please help me to solve this problem.
Thanks in advance

**Comment by ZZM37** [comment]
I get the same error and I am interested in how to deal with it 
Thank you!

**Comment by luisito93** [comment]
me too

**Comment by AvaMAA8** [comment]
This happens to me too. Has anyone solved this yet?
I noticed this error happening lately, it didn't happen before. My .h5 files used to load normally. I think it has to do with the hdf5 or h5 version or something.
Still trying to figure it out as I need to load the weights.

**Comment by chuxiaoyi2018** [comment]
me too

**Comment by ash9swaika** [comment]
me too

**Comment by sys0419** [comment]
I did it when I change the model file (xx.h5) into another disk directory(not local disk, C:/)

**Comment by sys0419** [comment]
![02](https://user-images.githubusercontent.com/45556489/84737597-cde09400-afda-11ea-96a6-39216258abb8.PNG)

**Comment by alanlivio** [comment]
Just to registred here I was able to bypass the error by using the variable HDF5_USE_FILE_LOCKING='FALSE' from the command line.
