### ISSUE TITLE
Multiple inputs fusion model not working

### ISSUE THREAD

**Issue by Neehal-Lingayat** [keras-team/keras#10639]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

Hi everyone , i am new to this field  and trying to make a model which will do the fusion of visible and thermal image to help improve the object detection results during night. 
my code is as follows:

**********************CODE****************************************
from keras.layers import Activation
from keras.models import Sequential
from keras.optimizers import SGD,Adam
from keras.layers import Dense, Input,Conv2D,MaxPooling2D,Dropout
from keras.layers.core import Flatten
from keras.optimizers import Adam
from keras.metrics import categorical_crossentropy
import numpy as np
from keras.models import load_model
from keras.datasets import mnist
from keras.models import Model
from keras.preprocessing.image import ImageDataGenerator, array_to_img, img_to_array, load_img
import pandas
from pandas import DataFrame
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

​
data_path1 = 'C:\tensorflow1\models\research\object_detection\images\csv1.tfrecords'  # address to save the hdf5 file
with tf.Session() as sess:
    feature = {'train/image': tf.FixedLenFeature([], tf.string),
               'train/label': tf.FixedLenFeature([], tf.int64)}
    # Create a list of filenames and pass it to a queue
    filename_queue = tf.train.string_input_producer([data_path1], num_epochs=1)
    # Define a reader and read the next record
    reader = tf.TFRecordReader()
    _, serialized_example = reader.read(filename_queue)
    # Decode the record read by the reader
    features = tf.parse_single_example(serialized_example, features=feature)
    # Convert the image data from string back to the numbers
    image = tf.decode_raw(features['train/image'], tf.float32)
    
    # Cast label data into int32
    label = tf.cast(features['train/label'], tf.int32)
    # Reshape image data into the original shape
    image = tf.reshape(image, [150, 150, 1])
    images, labels = tf.train.shuffle_batch([image, label], batch_size=10, capacity=30, num_threads=1, min_after_dequeue=10) 

train_x1=image
train_y1=label
​

​
data_path2 = 'C:\tensorflow1\models\research\object_detection\images\csv2.tfrecords'  # address to save the hdf5 file
with tf.Session() as sess:
    feature = {'train/image': tf.FixedLenFeature([], tf.string),
               'train/label': tf.FixedLenFeature([], tf.int64)}
    # Create a list of filenames and pass it to a queue
    filename_queue = tf.train.string_input_producer([data_path2], num_epochs=1)
    # Define a reader and read the next record
    reader = tf.TFRecordReader()
    _, serialized_example = reader.read(filename_queue)
    # Decode the record read by the reader
    features = tf.parse_single_example(serialized_example, features=feature)
    # Convert the image data from string back to the numbers
    image = tf.decode_raw(features['train/image'], tf.float32)
    
    # Cast label data into int32
    label = tf.cast(features['train/label'], tf.int32)
    # Reshape image data into the original shape
    image = tf.reshape(image, [150,150,1])
    images1,labels1 = tf.train.shuffle_batch([image, label], batch_size=10, capacity=30, num_threads=1, min_after_dequeue=10)

train_x2=images1
train_y2=labels1

input1=Input(shape=(150,150,1))
x=Conv2D(32, kernel_size=(3,3), activation='relu',padding='same')(input1)
x=MaxPooling2D((2,2),padding='same')(x)
x=Dropout(0.25)(x)
x=Conv2D(64, kernel_size=(3,3), activation='relu',padding='same')(x)
x=MaxPooling2D((2,2),padding='same')(x)
x=Dropout(0.25)(x)
x=Conv2D(128, kernel_size=(3,3), activation='relu',padding='same')(x)
x=MaxPooling2D((2,2),padding='same')(x)
x=Dropout(0.25)(x)
x=Conv2D(64, kernel_size=(3,3), activation='relu',padding='same')(x)
x=MaxPooling2D((2,2),padding='same')(x)
x=Dropout(0.25)(x)
x=Conv2D(32, kernel_size=(3,3), activation='relu',padding='same')(x)
x=MaxPooling2D((2,2),padding='same')(x)
branch1=Flatten()(x)
model1=Model(inputs=input1,outputs=branch1)
​

input2=Input(shape=(150,150,1))
x=Conv2D(32, kernel_size=(3,3), activation='relu',padding='same')(input2)
x=MaxPooling2D((2,2),padding='same')(x)
x=Dropout(0.25)(x)
x=Conv2D(64, kernel_size=(3,3), activation='relu',padding='same')(x)
x=MaxPooling2D((2,2),padding='same')(x)
x=Dropout(0.25)(x)
x=Conv2D(128, kernel_size=(3,3), activation='relu',padding='same')(x)
x=MaxPooling2D((2,2),padding='same')(x)
x=Dropout(0.25)(x)
x=Conv2D(64, kernel_size=(3,3), activation='relu',padding='same')(x)
x=MaxPooling2D((2,2),padding='same')(x)
x=Dropout(0.25)(x)
x=Conv2D(32, kernel_size=(3,3), activation='relu',padding='same')(x)
x=MaxPooling2D((2,2),padding='same')(x)
x=Dropout(0.25)(x)
branch2=Flatten()(x)
model2=Model(inputs=input2,outputs=branch2)
​

from keras.layers.merge import concatenate
model_list=[branch1, branch2]
merged = concatenate(model_list,axis=1)
x=Dense(10, activation='relu')(merged)
x=Dense(10, activation='relu')(x)
output= Dense(3, activation='softmax')(x)
final_model=Model(inputs=[input1,input2],outputs=output)
​

# compile the model
Adam = Adam(lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=None, decay=0.0, amsgrad=False)
final_model.compile(optimizer=Adam, loss='categorical_crossentropy', metrics = ['accuracy'])
​
​

final_model.fit([train_x1,train_x2],[train_y1,train_y2],steps_per_epoch=20,epochs=10,verbose=1)
*******************************************************************************8
the error i am getting is:
*************************Traceback********************************
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-56-08faef6da389> in <module>()
----> 1 final_model.fit([train_x1,train_x2],[train_y1,train_y2],steps_per_epoch=20,epochs=10,verbose=1)

c:\users\neehal lingayat\anaconda3\envs\tensorflow1\lib\site-packages\keras\engine\training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, **kwargs)
    953             sample_weight=sample_weight,
    954             class_weight=class_weight,
--> 955             batch_size=batch_size)
    956         # Prepare validation data.
    957         do_validation = False

c:\users\neehal lingayat\anaconda3\envs\tensorflow1\lib\site-packages\keras\engine\training.py in _standardize_user_data(self, x, y, sample_weight, class_weight, check_array_lengths, batch_size)
    790                 feed_output_shapes,
    791                 check_batch_axis=False,  # Don't enforce the batch size.
--> 792                 exception_prefix='target')
    793 
    794             # Generate sample-wise weight values given the `sample_weight` and

c:\users\neehal lingayat\anaconda3\envs\tensorflow1\lib\site-packages\keras\engine\training_utils.py in standardize_input_data(data, names, shapes, check_batch_axis, exception_prefix)
     88         data = data.values if data.__class__.__name__ == 'DataFrame' else data
     89         data = [data]
---> 90     data = [standardize_single_array(x) for x in data]
     91 
     92     if len(data) != len(names):

c:\users\neehal lingayat\anaconda3\envs\tensorflow1\lib\site-packages\keras\engine\training_utils.py in <listcomp>(.0)
     88         data = data.values if data.__class__.__name__ == 'DataFrame' else data
     89         data = [data]
---> 90     data = [standardize_single_array(x) for x in data]
     91 
     92     if len(data) != len(names):

c:\users\neehal lingayat\anaconda3\envs\tensorflow1\lib\site-packages\keras\engine\training_utils.py in standardize_single_array(x)
     17     elif K.is_tensor(x):
     18         shape = K.int_shape(x)
---> 19         if shape is None or shape[0] is None:
     20             raise ValueError(
     21                 'When feeding symbolic tensors to a model, we expect the'

IndexError: tuple index out of range

​

**Comment by Neehal-Lingayat** [comment]
#148

**Comment by Neehal-Lingayat** [comment]
@fchollet

**Comment by anbhimi** [comment]
Hi,
I am facing the same issue with a similar code snippet. Did you have a fix for this issue? Please include the fix if possible.
Thanks.

**Comment by Neehal-Lingayat** [comment]
Hi, we actually stopped working on it long ago and no , we cudnt find
anything to solve it but mostly because our input data was of wrong format
or something to do with the dataset ....so I suggest looking into that I
haven't worked on it while but I might give it a try ......will let u know
if I figure something out.

**Comment by anbhimi** [comment]
In my case, by converting the labels into a pandas Series rather than a TensorFlow tensor had fixed the problem and the model training began. Please check for the type of train_y1, train_y2 and change them to pandas Series. That should be a quick fix.
