### ISSUE TITLE
 ValueError: Negative dimension size caused by subtracting 3 from 2 for 'conv2d_1/convolution'

### ISSUE THREAD

**Issue by subhaamalraj8** [keras-team/keras#10641]
Hello,

I'm using Keras (2.2) with Tensorflow(1.9.0rc2) backend
I'm trying to create a model with conv2D
My code is as below:

 with tf.device('/gpu:0'):
            model = Sequential()
            model.add(Conv2D(64,(3,3),input_shape=(1,2,18),data_format='channels_first',activation='relu'))
            model.add(MaxPooling2D())
            model.add(Conv2D(32,(4,4), activation='relu'))
            model.add(MaxPooling2D())
            model.add(Dropout(0.2))
            model.add(Flatten())
            model.add(Dense(3, activation='softmax'))

But I'm getting the following error,
ValueError: Negative dimension size caused by subtracting 3 from 2 for 'conv2d_1/convolution' (op: 'Conv2D') with input shapes: [?,2,18,1], [3,3,1,64].

Please help me solve this. Thanks in advance

**Comment by Dref360** [comment]
Hi!
This issue isn't related to a bug/enhancement/feature request or other accepted types of issue.

To ask questions, please see the following resources : 
* https://keras.io/
* https://keras.io/#support
* https://gitter.im/Keras-io/Lobby

Thanks!

If you think I made a mistake, please re-open this issue.
