### ISSUE TITLE
Stateful RNN has wrong tensor shape in Keras Functional model

### ISSUE THREAD

**Issue by joshuafishman** [keras-team/keras#10643]
I defined a Keras functional model containing a block with a stateful LSTM, as follows:

    import numpy as np
    from tensorflow.python import keras
    
    
    data = np.ones((1,2,3))
    
    input_shape = data.shape  # batch size, step size, input size
    output_units = 2
    
    ### input block ###
    inputs = keras.layers.Input(batch_shape=input_shape, name="inputs")
    
    
    ### model block with stateful RNN ###
    dummy_inputs_1 = keras.layers.Input(batch_shape=input_shape, name="dummy_inputs_1")
    recurrent_1 = keras.layers.LSTM(units=input_shape[-1], batch_input_shape=input_shape,
                                    return_sequences=True, stateful=True,
                                    name="recurrent_1")(dummy_inputs_1)
    
    dense_1 = keras.layers.Dense(output_units, batch_input_shape=(
        input_shape[0], input_shape[-1], input_shape[1]),
                                 name="dense_1")
    output_1 = keras.layers.TimeDistributed(dense_1, input_shape=input_shape, name="output_1")(recurrent_1)
    
    model_1 = keras.models.Model(inputs=[dummy_inputs_1], outputs=[output_1], name="model_1")
    model_1.compile(loss='mean_squared_error',
                    optimizer='Nadam',
                    metrics=['accuracy'])
    
    ### add model block to model ###
    model_block = model_1(inputs)
    model = keras.models.Model(inputs=[inputs], outputs=[model_block], name="model")
    model.compile(loss='mean_squared_error',
                    optimizer='Nadam',
                    metrics=['accuracy'])
    
    
    model_1.predict(data) #works
    
    model.predict(data)  #fails

As written, the first `predict()` call (to the inner model block containing the stateful LSTM layer) works fine, but the second fails with this error:

     Traceback (most recent call last):
      File ".../functional_stateful.py", line 38, in <module>
        model_1.predict(data)
      File ".../local/lib/python2.7/site-packages/tensorflow/python/keras/engine/training.py", line 1478, in predict
        self, x, batch_size=batch_size, verbose=verbose, steps=steps)
      File ".../local/lib/python2.7/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 363, in predict_loop
        batch_outs = f(ins_batch)
      File ".../local/lib/python2.7/site-packages/tensorflow/python/keras/backend.py", line 2897, in __call__
        fetched = self._callable_fn(*array_vals)
      File ".../local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1454, in __call__
        self._session._session, self._handle, args, status, None)
      File ".../local/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
        c_api.TF_GetCode(self.status.status))
    tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'inputs' with dtype float and shape [1,2,3]
    	 [[Node: inputs = Placeholder[dtype=DT_FLOAT, shape=[1,2,3], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

With `stateful=True` commented out in the LSTM definition, the whole thing runs fine. Does anyone know what's happening?

stackoverflow link here https://stackoverflow.com/questions/51268504/stateful-rnn-has-wrong-tensor-shape-in-keras-functional-model

**Comment by wiewel** [comment]
I have a similar issue. When reusing a stateful LSTM model in another model, it crashes as soon as I call predict. Training the network with the combined network is possible on the other hand.

The following is a minimal example to reproduce the error.

1) When setting "stateful" to False the execution works, after setting it to True it fails.
2) When "model_A.predict" is called before creating "model_B", it is possible to call predict on "model_A" again after creation of "model_B" without an error. If "model_A.predict" is not called before "model_B" is created, the call of "model_A.predict" after the creation of "model_B" will fail.

```
import tensorflow as tf
import keras as keras
from keras.optimizers import Adam
from keras.layers import *
from keras.models import Model
import keras.backend as K
import numpy as np

#---------------------------------------------------------------------------------
if __name__ == "__main__":
    batch_num = 8
    stateful = True # 1) False 

    A_inputs = Input(batch_shape=(batch_num, 1, 10), dtype="float32", name="A_in")
    A_out = LSTM(units=10, return_sequences=True, stateful=stateful)(A_inputs)
    model_A = Model(name="A", inputs=A_inputs, outputs=[A_out])
    model_A.summary()
    model_A.compile(loss="mse", optimizer=Adam())

    model_A.predict(np.random.rand(batch_num, 1, 10), batch_size=8) # 2) Make comment of those two lines...
    print("Predict A done")


    B_inputs = Input(batch_shape=(batch_num, 1, 10), dtype="float32", name="B_in")
    B_out = model_A(B_inputs)
    model_B = Model(name="B", inputs=B_inputs, outputs=[B_out])
    model_B.summary()
    model_B.compile(loss="mse", optimizer=Adam())

    #model_A.predict(np.random.rand(batch_num, 1, 10), batch_size=8) # 2) ... then this code will fail. If predict was already called on model_A before the creation of model_B, it will work.
    #print("Predict A done")
    model_B.predict(np.random.rand(batch_num, 1, 10), batch_size=8)
    print("Predict B done")
```

The trace looks like this:

```
Traceback (most recent call last):
  File "keras_minimal_test.py", line 32, in <module>
    model_B.predict(np.random.rand(batch_num, 1, 10), batch_size=8)
  File ".../tensorflow1.11/lib/python3.6/site-packages/keras/engine/training.py", line 1170, in predict
    steps=steps)
  File ".../tensorflow1.11/lib/python3.6/site-packages/keras/engine/training_arrays.py", line 295, in predict_loop
    batch_outs = f(ins_batch)
  File ".../tensorflow1.11/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2933, in __call__
    return self._call(inputs)
  File ".../tensorflow1.11/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2891, in _call
    fetched = self._callable_fn(*array_vals)
  File ".../tensorflow1.11/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1399, in __call__
    run_metadata_ptr)
  File ".../tensorflow1.11/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 526, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'A_in' with dtype float and shape [8,1,10]
         [[{{node A_in}} = Placeholder[dtype=DT_FLOAT, shape=[8,1,10], _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
         [[{{node A/lstm_1/transpose_1/_55}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_376_A/lstm_1/transpose_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
```

Tested on different machines with different hardware and Tensorflow versions (1.11 and 1.12) with the latest Keras version installed with pip from this git repository.
One machine uses a self compiled version of Tensorflow 1.11 with CUDA10 support (cuDNN 7.3.1). The other uses Tensorflow 1.12 with CUDA9 support (cuDNN 7.4.1).
On both I use Python 3.6.

Any help or hints would be appreciated since I really need the stateful property to work with multiple models... :/
Thanks in advance!
