### ISSUE TITLE
Use get_shape() in loss function

### ISSUE THREAD

**Issue by rodriguel** [keras-team/keras#10651]
Hello everyone. I have written the following loss function, but it doesn't seem to suit Keras requirement. 

```
def custom_loss_(y_true, y_pred):
	bool_mask = K.greater(y_true[..., 2] * y_true[..., 3], 	0)
	e0 = np.zeros(y_true.get_shape().as_list()) # BUG /!\ # 
	e1 = np.zeros(y_true.get_shape().as_list())
	e0[..., 0:4] = np.sqrt(5) 
	e0[..., 4:] = 1
        e0 = tf.constant(e0)
        e1 = tf.constant(e1)
	mask_coord = K.switch(bool_mask, e0, e1)


	bool_mask = K.equal(y_true[..., 2] * y_true[..., 3], 0)
	e0 = np.zeros(y_true.get_shape().as_list())
	e1 = np.zeros(y_true.get_shape().as_list())
	e0[...,5] = np.sqrt(0.5)
        e0 = tf.constant(e0)
        e1 = tf.constant(e1)
	conf_coord = K.switch(bool_mask, e0, e1)

	mask = mask_coord + conf_coord
	return tf.reduce_mean(K.square(K.multiply(y_true - y_pred, mask)), axis = 0)
```
At run time, I get the following error:

> TypeError                                 Traceback (most recent call last)
> ~/MFG/YOLO/Y2K/network.py in <module>()
>      70 yolo = buildYolo()
>      71 yolo.summary()
> ---> 72 yolo.compile(loss = custom_loss, optimizer = 'adadelta')
>      73
>      74
> 
> ~/anaconda3/lib/python3.6/site-packages/keras/engine/training.py in compile(self, optimizer, loss, metrics, loss_weights, sample_weight_mode, weighted_metrics, target_tensors, **kwargs)
>     330                 with K.name_scope(self.output_names[i] + '_loss'):
>     331                     output_loss = weighted_loss(y_true, y_pred,
> --> 332                                                 sample_weight, mask)
>     333                 if len(self.outputs) > 1:
>     334                     self.metrics_tensors.append(output_loss)
> 
> ~/anaconda3/lib/python3.6/site-packages/keras/engine/training_utils.py in weighted(y_true, y_pred, weights, mask)
>     401         """
>     402         # score_array has ndim >= 2
> --> 403         score_array = fn(y_true, y_pred)
>     404         if mask is not None:
>     405             # Cast the mask to floatX to avoid float64 upcasting in Theano
> 
> ~/YOLO/Y2K/network.py in custom_loss(y_true, y_pred)
>      48
>      49         bool_mask = K.greater(y_true[..., 2] * y_true[..., 3],  0)
> ---> 50         e0 = np.zeros(y_true.get_shape().as_list())
>      51         e1 = np.zeros(y_true.get_shape().as_list())
>      52         e0[..., 0:4] = np.sqrt(5)
> 
> TypeError: 'NoneType' object cannot be interpreted as an integer

I would greatly appreciate if someone can help understand why this function doesn't work / and how to fix this. Thank you a LOT !

**Comment by Dref360** [comment]
Hi!
This issue isn't related to a bug/enhancement/feature request or other accepted types of issue.

To ask questions, please see the following resources : 
* https://keras.io/
* https://keras.io/#support
* https://gitter.im/Keras-io/Lobby

Thanks!

If you think I made a mistake, please re-open this issue.
