### ISSUE TITLE
Dropout after embedding layer 

### ISSUE THREAD

**Issue by xun468** [keras-team/keras#10650]
I am attempting to use dropout after an embedding layer. The usewarning says that the embedding layer no longer supports dropout but adding SpatialDropout1D afterwards will have the same behavior. However when I attempt to call SpatialDropout1D I get the error 

ValueError: Layer spatial_dropout_1d_1 was called with an input that isn't a symbolic tensor. Received type: <class 'keras.layers.embeddings.Embedding'>

My code is 
```
input_emb = Embedding(seq_len,dim_emb,trainable=False,weights=pre_train) 
input_emb = SpatialDropout1D(dropout)(input_emb)
```

I am using keras version 2.2 and tensorflow version 1.9.0. Is the usewarning outdated?

**Comment by yanboliang** [comment]
@xun468 In your code, ```input_emb``` is an object of ```Embedding```, not a tensor, so you can't feed it into the downstream layer. You need to call ```input_emb(input_tensor)``` to get the output tensor, and then feed it to ```SpatialDropout1D```. You can refer [this](https://github.com/keras-team/keras/blob/master/examples/pretrained_word_embeddings.py#L127) example.

**Comment by xun468** [comment]
Thank you!
