### ISSUE TITLE
a '{}' in the filename gives IndexError: tuple index out of range

### ISSUE THREAD

**Issue by jfilter** [keras-team/keras#10652]
> filepath = self.filepath.format(epoch=epoch + 1, **logs)
> IndexError: tuple index out of range

I made the mistake of accidentally adding "{}" (with `str(some_empty_dict)`) to the file path of a checkpoint file. It took me while to figure out that this was the cause for the `IndexError`. This is not a bug with keras but a better error message would have helped me. If you are okay with it, I would send a PR with an improved error handling for this case.

**Comment by nbro** [comment]
In my case, I had written the following

```
weights_file_path = path.join(weights_folder_path, "epoch{:03d}-{val_loss:.4f}.hdf5")
```

rather than

```
weights_file_path = path.join(weights_folder_path, "{epoch:03d}-{val_loss:.4f}.hdf5")
```
