### ISSUE TITLE
apply_transform not in keras.preprocessing.image anymore. DOC update needed.

### ISSUE THREAD

**Issue by ghost** [keras-team/keras#10662]
According to [https://keras.io/preprocessing/image/#apply_transform](url) , apply_transform is still under  keras.preprocessing.image which is not the case.

**Comment by Dref360** [comment]
In the doc: https://keras.io/preprocessing/image/#imagedatagenerator-methods
In the code: https://github.com/keras-team/keras-preprocessing/blob/master/keras_preprocessing/image.py#L1095

I'm not sure I get your issue?

**Comment by samiatwork** [comment]
Interesting. Trying from keras.preprocessing.image import apply_transform gives me a name error! (Using python3 - Anaconda - Tensorflow backend)

**Comment by Dref360** [comment]
it's part of ImageDataGenerator now

**Comment by mkaze** [comment]
@Dref360 No, it is not resolved. Apparently, the documentation is wrong. Please look at the referenced pull request.

**Comment by Dref360** [comment]
Yes, you're right! I was talking about the fact that apply_transform was not under ImageDataGenerator methods, I didn't look at the signature.
