### ISSUE TITLE
How to use two image generators to combine multiple images as one record?

### ISSUE THREAD

**Issue by search4mahesh** [keras-team/keras#10676]
Hi,

Is there any way if we can combine two or more images which are related , as one record 
e.g like two generators for two images and then combine using zip and passing it two classification or regression model?
Please let me know if anybody have done this before

Thanks
Mahesh

**Comment by shsshs** [comment]
If your model accept both images as one input this should be no problem(e.g. concatenate)

If you want to combine 2 analysis and compute the gradient with respect to both (e.g. as average) this is more complicated and i would be grateful if you post your solution when you find one.
