### ISSUE TITLE
How to customize the LSTM layer

### ISSUE THREAD

**Issue by yzzhang2008** [keras-team/keras#10671]
Hello there!
I have known how to modify the cell state in recurrent.py, like plus one value, define new arguments, but usually this operation will affect all training samples.
Now if I wanna modify the layer based on each training sample, for example, for train_data 1, I wanna make the cell gate plus value1, while for train_data 2, I wanna make the cell gate plus value2...
I don't know how to do that. maybe using a loop?
Hope someone could give me some pointers.

**Comment by tRosenflanz** [comment]
Define a layer that takes 2 inputs and provide this custom parameter as the 2nd input to your custom layer
