### ISSUE TITLE
How to setup 1D-Convolution and LSTM in Keras

### ISSUE THREAD

**Issue by nxthuan512** [keras-team/keras#10683]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by nxthuan512** [comment]
I would like to use 1D-Conv following by LSTM to classify a 16-channel 400-timestep signal.

The input shape is composed of: - X = (n_samples, n_timesteps, n_features), where n_samples=476, n_timesteps=400, n_features=16 are the number of samples, timesteps, and features (or channels) of the signal. - y = (n_samples, n_timesteps, 1). Each timestep is labeled by either 0 or 1 (binary classification).

I use the 1D-Conv to extract the temporal information, as shown in the figure below. F=32 and K=8 are the filters and kernel_size. 1D-MaxPooling is used after 1D-Conv. 32-unit LSTM is used for signal classification. The model should return an y_pred = (n_samples, n_timesteps, 1).

![signals](https://user-images.githubusercontent.com/4446300/42729688-22690b9e-87ae-11e8-9882-ee3639aca845.png)

The code snippet is shown as follow

`input_layer = Input(shape=(dataset.n_timestep, dataset.n_feature))`
    `conv1 = Conv1D(filters=32,`
                   `kernel_size=8,`
                  ` strides=1,`
                   `activation='relu')(input_layer)`
    `pool1 = MaxPooling1D(pool_size=4)(conv1)`
    `lstm1 = LSTM(32)(pool1)`
    `output_layer = Dense(1, activation='sigmoid')(lstm1)`
    `model = Model(inputs=input_layer, outputs=output_layer) `

The model summary is shown below
![model](https://user-images.githubusercontent.com/4446300/42729690-5a7a4a66-87ae-11e8-9709-20036c65b55e.png)

However, I got an error ValueError: Error when checking target: expected dense_15 to have 2 dimensions, but got array with shape (476, 400, 1).

I guess the problem was the incorrect shape. Please let me know how to fix it.

Another question is the number of timesteps. Because the input_shape is assigned in the 1D-Conv, how can we let LSTM know the timestep must be 400?

Thank you,

**Comment by izikgo** [comment]
can you post your `fit`/`fit_generator` call?

**Comment by tsterbak** [comment]
Looks like your labels y have the wrong dimensions. Can you try to reshape y to (476, 400)? This should be possible with numpy.reshape. 
Does this work for you?

**Comment by nxthuan512** [comment]
Hi @tsterbak , y is a 3-dimensional vector because I'd like to label each timestep, not each sample. 
I found a way to make it work by using pad='same'. Please find a code below. Thanks.
Hi @izikgo , please find the code below. Thanks.

```
input_layer = Input(shape=(400, 16))
conv1 = Conv1D(filters=32,
               kernel_size=8,
               strides=1,
               activation='relu',
               padding='same')(input_layer)
lstm1 = LSTM(32, return_sequences=True)(conv1)
output_layer = Dense(1, activation='sigmoid')(lstm1)
model = Model(inputs=input_layer, outputs=output_layer)

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['acc'])
history = model.fit(X_train, 
                              y_train, 
                              epochs=1000, 
                              batch_size=batch_size, 
                              verbose=1, 
                              shuffle=True, 
                              callbacks=callbacks,
                              class_weight=class_weights,
                              validation_data=(X_test, y_test))
```

There is one approach I'd like to try is to perform the convolution among channels, instead of timesteps? For example, a filter (2, 1) traverses each timestep, as shown in figure below. I don't know if we can do it with conv1D or conv2D.
![v2ryb](https://user-images.githubusercontent.com/4446300/42902908-27d7f8f4-8a9e-11e8-8de3-e2b352454969.png)

**Comment by izikgo** [comment]
In order to label each timestep you need to set the `return_sequences` flag in the LSTM layer and wrap the `Dense` layer with the `TimeDistributed` wrapper layer

**Comment by nxthuan512** [comment]
Hi @izikgo , I found that there was no problem without using TimeDistributed wrapper layer. Do you think we should apply it? Will it improve the AUC score? Also, do you have any idea of implementing convolution in all channels/timestep shown above? Thanks.

**Comment by izikgo** [comment]
You are right. Since Keras 2.0, `TimeDistributed(Dense)` and `Dense` are equivalent.
Regarding you second question, I'm not quite sure I understand your objective. In your figure, every color is a different 2x1 filter which only moves to the right? Or is it the same filter which moves across channels **and** across the timesteps?
