### ISSUE TITLE
Variable assignment memory leak (TF backend)

### ISSUE THREAD

**Issue by asmith33** [keras-team/keras#10697]
During batch training, I noticed that memory usage was growing with each loop. I reduced the issue to the tensor assignment and recreated the minimal code below.

Windows 10
Keras 2.2.0
tensorflow 1.8.0

```
import keras
import numpy as np
import psutil
import os

def get_mem_usage():
    process = psutil.Process(os.getpid())
    info = process.memory_info()
    return "rss={} vss={}".format(info.rss >> 20, info.vms >> 20)

X = keras.backend.variable(value=np.empty((int(1E8),1), dtype=np.float32))

for i in range(3):
    
    X.assign(np.empty((int(1E8),1)))
    
    print("i: {} {}".format(i, get_mem_usage()))
```

Which outputs

```
Using TensorFlow backend.
i: 0 rss=907 vss=889
i: 1 rss=1288 vss=1271
i: 2 rss=1670 vss=1653
```

**Comment by asears** [comment]
It appears as though variables being initialized in Tensorflow use the same size memory, at least in this case.  For the 3 variables initialized, it ate almost 400MB RAM each time if I am reading VMMap correctly, that was not freed until Python thread ended.

![memory](https://user-images.githubusercontent.com/7253192/42809998-e552558e-8984-11e8-821e-8e16d6ca614f.png)

It could be related to these:
https://github.com/tensorflow/tensorflow/issues/19093
https://github.com/keras-team/keras/issues/7992

It seems to match similar instances where we make predictions in a loop.  Eventually the initialized Tensorflow backend (or Keras?) will starve the resources of the machine.

Have tried combinations of these to no effect

```
  tf.initialize_all_variables()
     sess.close()
     K.clear_session()
     tf.reset_default_graph()
     tf.contrib.keras.backend.clear_session()
     del X
     gc.collect()
     objgraph.show_most_common_types(limit=50)
     for w in model.trainable_weights:
         K.set_value(w, [[0]])
     tf.reset_default_graph() 
     K.tensorflow_backend.clear_session()
```

**Comment by asears** [comment]
From the Tensorflow web site, may apply to this scenario.

http://www.riptutorial.com/tensorflow/example/13427/use-the-tcmalloc-allocator
http://www.riptutorial.com/tensorflow/example/13426/use-graph-finalize---to-catch-nodes-being-added-to-the-graph
