### ISSUE TITLE
cannot install keras on raspberry pi 3 python=3.5.3

### ISSUE THREAD

**Issue by brownpanther** [keras-team/keras#10699]
Using `pip install keras` I run into a 404 error on PyPi because there is no arm7 wheel for pyYAML. 

`Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting keras
  Using cached https://files.pythonhosted.org/packages/68/12/4cabc5c01451eb3b413d19ea151f36e33026fc0efb932bf51bcaf54acbf5/Keras-2.2.0-py2.py3-none-any.whl
Collecting pyyaml (from keras)
  HTTP error 404 while getting https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl#sha256=a5b125a24244830d574ccfd8fab861198d2ffe491b73179ffd75abf78caee6ff (from https://www.piwheels.org/simple/pyyaml/)
  Could not install requirement pyyaml from https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl#sha256=a5b125a24244830d574ccfd8fab861198d2ffe491b73179ffd75abf78caee6ff (from keras) because of error 404 Client Error: Not Found for url: https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl
Could not install requirement pyyaml from https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl#sha256=a5b125a24244830d574ccfd8fab861198d2ffe491b73179ffd75abf78caee6ff (from keras) because of HTTP error 404 Client Error: Not Found for url: https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl for URL https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl#sha256=a5b125a24244830d574ccfd8fab861198d2ffe491b73179ffd75abf78caee6ff (from https://www.piwheels.org/simple/pyyaml/)`

I've tried to just install Keras from this git repo using
`pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps`

but when I try to import the library I have other dependency issues 
`>>> import keras
Using TensorFlow backend.
/home/pi/.virtualenvs/keras_tf/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.4 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.5
  return f(*args, **kwds)
/home/pi/.virtualenvs/keras_tf/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: builtins.type size changed, may indicate binary incompatibility. Expected 432, got 412
  return f(*args, **kwds)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.virtualenvs/keras_tf/lib/python3.5/site-packages/keras/__init__.py", line 5, in <module>
    from . import applications
  File "/home/pi/.virtualenvs/keras_tf/lib/python3.5/site-packages/keras/applications/__init__.py", line 11, in <module>
    import keras_applications
ImportError: No module named 'keras_applications'
>>> import keras_applications.io
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'keras_applications'`

Can somebody suggest a fix to install keras with tensorflow backend?

**Comment by stabgan** [comment]
install keras 1.2.2

**Comment by brownpanther** [comment]
I still get the same 404 not found error on PyPI for PyYAML
`(keras) pi@raspberrypi:~ $ pip install keras==1.2.2
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting keras==1.2.2
  Downloading https://www.piwheels.org/simple/keras/Keras-1.2.2-py3-none-any.whl (210kB)
    100% |████████████████████████████████| 215kB 2.2MB/s 
Requirement already satisfied: six in ./.virtualenvs/keras/lib/python3.5/site-packages (from keras==1.2.2) (1.11.0)
Collecting pyyaml (from keras==1.2.2)
  HTTP error 404 while getting https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl#sha256=a5b125a24244830d574ccfd8fab861198d2ffe491b73179ffd75abf78caee6ff (from https://www.piwheels.org/simple/pyyaml/)
  Could not install requirement pyyaml from https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl#sha256=a5b125a24244830d574ccfd8fab861198d2ffe491b73179ffd75abf78caee6ff (from keras==1.2.2) because of error 404 Client Error: Not Found for url: https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl
Could not install requirement pyyaml from https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl#sha256=a5b125a24244830d574ccfd8fab861198d2ffe491b73179ffd75abf78caee6ff (from keras==1.2.2) because of HTTP error 404 Client Error: Not Found for url: https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl for URL https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl#sha256=a5b125a24244830d574ccfd8fab861198d2ffe491b73179ffd75abf78caee6ff (from https://www.piwheels.org/simple/pyyaml/)`

**Comment by brownpanther** [comment]
Seeing as this issue might become stale, the fix that worked for me was: 
the `keras-preprocessing` and `keras.applications` have to be installed seperately
Not sure what the issue with `pip install keras` but I am using a fresh install of Raspbian.

```
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps
pip install keras-preprocessing
pip install keras.applications 
```
