### ISSUE TITLE
how to predict using the model saved in seq2seq example?

### ISSUE THREAD

**Issue by scut-salmon** [keras-team/keras#10709]
Hi,
I have run the model in [lstm_seq2seq.py](https://github.com/keras-team/keras/blob/master/examples/lstm_seq2seq.py), and predict the sequence the with the mdoel online. Now I want to predict the sequence using the model saved in the disk, how can I implement with it?
I have tried the load_model function, but find that the result is not true(just like I have not trained)
Any suggestion would be  appreciated
Thanks,
Zhang

**Comment by scut-salmon** [comment]
The problem has been solved and save both the encoder_model and decoder_model would be work(not just save the model trained).

**Comment by nixon-nyx** [comment]
but it seems like the state is not saved and the model is not returning anything good @scut-salmon
