### ISSUE TITLE
Batchwise Conv2D backend operation

### ISSUE THREAD

**Issue by LeonLIU08** [keras-team/keras#10712]
Target:
Calculating the convolution of two inputs (A, B) based on their first axis. 
A : (Bn, H, W, C)
B : (Bn, K, K, C)
where the "B" can be considered as the kernel, so "H">=K, "W">=K. 
The output should be (Bn, H, W).
It can be done by a "for" loop, like below:
`out = []`
`for i in range(Bn):`
      `.    out.append(K.conv2D(A[i:i+1, :, :, :], B[i, :, :, :, newaxis]))`
`out = K.stack(out, axis=0)`
But it really slow. 

Dose Keras contains a backend operation like this? Or anyone can help me to get a good idea on implement this?

**Comment by csxeba** [comment]
+1
