### ISSUE TITLE
{TypeError: 'NoneType' object is not subscriptable} by using TimeDistributed(Dense( output_dim , activation='softmax')) in theano backend

### ISSUE THREAD

**Issue by dongfang91** [keras-team/keras#10726]
I got an error when I created the multi-input sequential labeling GRU model. The error seems to come from TimeDistributed(Dense(type_size_interval, activation='softmax', kernel_regularizer=l2(.01), name='timedistributed_1')). I used python3.6.2 with Keras/2.2.0 and  theano/1.0.2 .

    char_input = Input(shape=(seq_length,), dtype='int8', name='character')

    pos_input = Input(shape=(seq_length,), dtype='int8', name='pos')

    CharEmbedding = Embedding(output_dim=embedding_size_char, input_dim=n_char, input_length=seq_length,
                              embeddings_regularizer=l2(.01), mask_zero=True)

    PosEmbedding = Embedding(output_dim=embedding_size_pos, input_dim=n_pos, input_length=seq_length,
                             embeddings_regularizer=l2(.01), mask_zero=True)

    Gru_out_1 = Bidirectional(GRU(gru_size1, return_sequences=True))

    Interval_output = TimeDistributed(Dense(type_size_interval, activation='softmax', kernel_regularizer=l2(.01), name='timedistributed_1'))

    char_em = CharEmbedding(char_input)

    pos_em = PosEmbedding(pos_input)

    input_merge = concatenate([char_em, pos_em])

    gru_out1 = Gru_out_1(input_merge)

    interval_output = Interval_output(gru_out1)

    model = Model(inputs=[char_input, pos_input],
                  outputs=[interval_output])

    model.compile(optimizer='rmsprop',
                  loss='categorical_crossentropy',
                  metrics=['categorical_accuracy'],
                  sample_weight_mode='temporal')

Using Theano backend.
Traceback (most recent call last):
  File "C:\Anaconda2\envs\python36\lib\site-packages\keras\engine\base_layer.py", line 458, in __call__
    output_mask = self.compute_mask(inputs, previous_mask)
  File "C:\Anaconda2\envs\python36\lib\site-packages\keras\layers\wrappers.py", line 300, in compute_mask
    inner_mask_shape = self._get_shape_tuple((-1,), mask, 2)
  File "C:\Anaconda2\envs\python36\lib\site-packages\keras\layers\wrappers.py", line 184, in _get_shape_tuple
    int_shape = K.int_shape(tensor)[start_idx:]
TypeError: 'NoneType' object is not subscriptable

**Comment by yanboliang** [comment]
@dongfang91 This exceptions is caused by ```Concatenate``` layers ```compute_mask``` output a tensor without ```_keras_shape```, for theano backend, we don't have other ways to get ```K.int_shape``` for the mask, so we should fall back to ```K.shape```. I sent #10826 to fix this, wish it can help.
For tensorflow backend, if there is no ```_keras_shape```, we still can get ```K.int_shape``` from ```tensor.get_shape```, so it would work well. We can't add ```_keras_shape``` for all theano operations, so I think we fall back to ```K.shape``` is the best way to fix it.
