### ISSUE TITLE
R ValueError: Error when checking input: expected simple_rnn_input to have 3 dimensions, but got array with shape (1661, 3)

### ISSUE THREAD

**Issue by JoeyBlack** [keras-team/keras#10722]
Here is my code:

```
used_time_period = "2009-01-01::2017-04-01"

data_used = data_input[used_time_period,]

split_coefficient = 0.8

train_set_rate = round(nrow(data_used) * split_coefficient)

data_train = data_used[1:train_set_rate,]

data_test = data_used[(train_set_rate + 1):nrow(data_used),]
################## keras model #############################################
model = keras_model_sequential() %>%
  
  layer_simple_rnn(units = 75, input_shape = dim(data_train[,1:3]), activation = "relu", return_sequences = TRUE) %>%
  layer_dense(units = 2, activation = "relu")

model %>% compile(optimizer = "adam", loss = "binary_crossentropy", metrics = "binary_accuracy")

history = model %>% fit(x = data_train[,1:3], y = data_train[,4:5], epochs = 40, batch_size = 20)
```

the error i'm getting is this:  ValueError: Error when checking input: expected simple_rnn_input to have 3 dimensions, but got array with shape (1661, 3)

dim(data_train[,1:3]) = (1661, 3)
dim(data_train[,4:5]) = (1661, 2)

What am I doing wrong?

**Comment by Dref360** [comment]
Hi!
This issue isn't related to a bug/enhancement/feature request or other accepted types of issue.

To ask questions, please see the following resources : 
* https://keras.io/
* https://keras.io/#support
* https://gitter.im/Keras-io/Lobby

Thanks!

If you think I made a mistake, please re-open this issue.

**Comment by JoeyBlack** [comment]
how can I reopen it?
