### ISSUE TITLE
how can i train faster R-CNN using a new customised network model?

### ISSUE THREAD

**Issue by MjdMahasneh** [keras-team/keras#10738]
I would like to know, If it is possible to train faster R-CNN using a new customised network model?

for example: i want to create a model that takes multiple inputs (2 images per class object), can i adapt this model to faster R-CNN? if so, what do i need to modify in the implementation to achieve it?

**Comment by Dref360** [comment]
Hi!
This issue isn't related to a bug/enhancement/feature request or other accepted types of issue.

To ask questions, please see the following resources : 
* https://keras.io/
* https://keras.io/#support
* https://gitter.im/Keras-io/Lobby

Thanks!

If you think I made a mistake, please open another issue.
