### ISSUE TITLE
In Keras, Unable to save model checkpoints when using Lambda in model. it gives us Value error ValueError: can only convert an array of size 1 to a Python scalar

### ISSUE THREAD

**Issue by rajeev0306** [keras-team/keras#10748]
Code is as below

  model1 = Sequential()
  model1.add(Embedding(MAX_NUM_WORDS,
                 EMBEDDING_DIM,
                 weights=[embedding_matrix],
                 input_length=MAX_SEQUENCE_LENGTH,
                 trainable=False))

  model1.add(TimeDistributed(Dense(300, activation='relu')))
  model1.add(Lambda(lambda x: K.sum(x, axis=1), output_shape=(300,)))
  #model1.add(Lambda(lambda x: func(x), output_shape=(300,)))

  model1_input = Input(shape=(MAX_SEQUENCE_LENGTH,), dtype='int32', 
                 name='model1_input')
  model1_output = model1(model1_input)

Not able to save model also give me same error that  Value error ValueError: can only convert an array of size 1 to a Python scalar

**Comment by yanboliang** [comment]
It seems this bug has been fixed by #10727, can you verify it?

**Comment by rajeev0306** [comment]
in my case, problem is given by the Lambda layer   model1.add(Lambda(lambda x: K.sum(x, axis=1), output_shape=(300,)) if I comment it then I'm able to save the Model. I tried different approach by using def func(x): x = K.sum(x,axis=1) return x
then using it inside Sequential API 
model1.add(Lambda(lambda x: func(x), output_shape=(300,)))

then calling Sequential API inside Functional API
model1_input = Input(shape=(MAX_SEQUENCE_LENGTH,), dtype='int32',
name='model1_input')
model1_output = model1(model1_input) but still I get the same error ValueError: can only convert an array of size 1 to a Python scalar
Somehow it is not able to serialize Lambda layer

What is the equivalent code to avoid LAMBDA layer

**Comment by yanboliang** [comment]
@rajeev0306 Using the functional API to build the model, and then save model, it can work well (Keras master code + TF 1.9), please refer the following code:
```
sequence_input = Input(shape=(MAX_SEQUENCE_LENGTH,), dtype='int32')
embedding_layer = Embedding(MAX_NUM_WORDS, EMBEDDING_DIM, weights=[embedding_matrix], input_length=MAX_SEQUENCE_LENGTH, trainable=False)
embedded_sequences = embedding_layer(sequence_input)
x = TimeDistributed(Dense(300, activation='relu'))(embedded_sequences)
x = Lambda(lambda x: K.sum(x, axis=1), output_shape=(300,))(x)
model = Model(sequence_input, x)
model.to_json()
save_model(model, "/tmp/test")
```

**Comment by rajeev0306** [comment]
thanx, my tensor flow version is 1.8. Is this the culprit

**Comment by rajeev0306** [comment]
With Keras master code + TF 1.9 , Im able to save model but during load I'm getting error
    w_att_2 = Permute((2,1))(Lambda(lambda x: softmax(x, axis=2),
NameError: name 'softmax' is not defined


**Here is the code**
def soft_attention_alignment(input_1, input_2):
    "Align text representation with neural soft attention"
    attention = Dot(axes=-1)([input_1, input_2])
    w_att_1 = Lambda(lambda x: softmax(x, axis=1),
                     output_shape=unchanged_shape)(attention)
    w_att_2 = Permute((2,1))(Lambda(lambda x: softmax(x, axis=2),
                             output_shape=unchanged_shape)(attention))
    in1_aligned = Dot(axes=1)([w_att_1, input_1])
    in2_aligned = Dot(axes=1)([w_att_2, input_2])
    return in1_aligned, in2_aligned

def esim(maxlen=MAX_LEN, 
         lstm_dim=300, 
         dense_dim=300, 
         dense_dropout=0.5):
             
  
    q1 = Input(name='q1',shape=(maxlen,))
    q2 = Input(name='q2',shape=(maxlen,))
    
   
    bn = BatchNormalization(axis=2)
    q1_embed = bn(embedding_layer(q1))
    q2_embed = bn(embedding_layer(q2))

    # Encode
    encode = Bidirectional(LSTM(lstm_dim, return_sequences=True))
    q1_encoded = encode(q1_embed)
    q2_encoded = encode(q2_embed)
    
    # Attention
    q1_aligned, q2_aligned = soft_attention_alignment(q1_encoded, q2_encoded)
    
    # Compose
    q1_combined = Concatenate()([q1_encoded, q2_aligned, submult(q1_encoded, q2_aligned)])
    q2_combined = Concatenate()([q2_encoded, q1_aligned, submult(q2_encoded, q1_aligned)]) 
       
    compose = Bidirectional(LSTM(lstm_dim, return_sequences=True))
    q1_compare = compose(q1_combined)
    q2_compare = compose(q2_combined)
    
    # Aggregate
    q1_rep = apply_multiple(q1_compare, [GlobalAvgPool1D(), GlobalMaxPool1D()])
    q2_rep = apply_multiple(q2_compare, [GlobalAvgPool1D(), GlobalMaxPool1D()])
    
    # Classifier
    merged = Concatenate()([q1_rep, q2_rep])
    
    dense = BatchNormalization()(merged)
    dense = Dense(dense_dim, activation='elu')(dense)
    dense = BatchNormalization()(dense)
    dense = Dropout(dense_dropout)(dense)
    dense = Dense(dense_dim, activation='elu')(dense)
    dense = BatchNormalization()(dense)
    dense = Dropout(dense_dropout)(dense)
    out_ = Dense(heuristic_score, activation='softmax')(dense)
    
    model = Model(inputs=[q1, q2], outputs=out_)
    model.compile(optimizer=Adam(lr=1e-3), loss='categorical_crossentropy', metrics=['categorical_crossentropy','accuracy'])
    return model
