### ISSUE TITLE
keras fit_generator does not progress.

### ISSUE THREAD

**Issue by fatemeh70** [keras-team/keras#10744]
Hi 
I tried to run the "nn_hierarchical_seq.py"  script  from the following path:
https://github.com/bio-ontology-research-group/deepgo
It is a keras code from API v1 and I changed it to be compatible with API v2.  I have tensorflow-gpu1.7  and keras2.2.1. When I try to train the model with fit_generator, it does not progress and it is stayed in the first epoch for a long time until the program is killed. 
The main author of the code trained the model with a system which is not better than mine. Its training time is lower than 3 hours. Does anybody know what is the problem. 

The code: 
![22](https://user-images.githubusercontent.com/41514702/43036513-f9734624-8cf2-11e8-9b37-8f330abd451d.png)

When I run it, it freezes in epoch 1. It doesn't show the progress bar while I set the verbose=2.
![111](https://user-images.githubusercontent.com/41514702/43036547-8851352c-8cf3-11e8-84e0-8dc77b94b061.png)

**Comment by Dref360** [comment]
Hi,
We could work on this better if you could provide a standalone reproducible example.
Some advices:
* Don't use custom data or custom paths.
* Use random arrays or even np.ones, np.zeros.
* The example should run with Keras (and deps) alone.
* Should be Python3 compatible.
* Should not be OS specific.
* The file should reproduce the bug with **high* fidelity.
* Link to a gist would be appreciated.

Thanks!
Dref360

**Comment by KIC** [comment]
I had the same symptom. for me it was a shape mismatch of the output layer. for some wired reason the no error message was thrown but the training just did nothing after printing epoch 1/x
