### ISSUE TITLE
" Tensor objects are not iterable ..." When buildin custom Layer 

### ISSUE THREAD

**Issue by rjpg** [keras-team/keras#10767]
Hello,

I would like to transform the output of a CNN layer adding info on the beginning and end of the "generated filtered images"...  so it can be included for the next CNN layer for the "kernel" process when on the (lateral) edges of the images (using valid padding on this next CNN layer).

The goal is to do a "cylindrical" padding, like roll the image so half of the kernel in the next layer work with the other side of the image when on the edge. 

the method to transform the CNN output is implemented like this (image_dim_ordering("th")): 
```
def transform(element,n):
    batchResultFlat=[]
    for batchElement in element:
        resultFlat=[]
        for cnnFilterImage in batchElement:
            firstColumns=cnnFilterImage[:,list(range(n))]
            result=np.concatenate((cnnFilterImage,np.array(firstColumns)),axis=1)
            lastColumnsReverse=cnnFilterImage[:,list(range(cnnFilterImage.shape[1]-n,cnnFilterImage.shape[1]))]
            result=np.concatenate((np.array(lastColumnsReverse),result),axis=1)
            resultFlat.append(result)
        batchResultFlat.append(np.array(resultFlat))
    newElement = np.array(batchResultFlat)
    return newElement

```

I have also explain here :  https://stackoverflow.com/questions/51459715/keras-lambda-function-to-change-info-for-the-next-layer

the complete code is here : https://github.com/rjpg/bftensor/blob/master/Autoencoder/src/rollCNN.ipynb

But I have the error : TypeError: Tensor objects are not iterable when eager execution is not enabled. To iterate over this tensor use tf.map_fn.

Have try with lambda function also has it show on the notebook. 

How to deal with this error ? 

Thanks !

**Comment by Dref360** [comment]
Hi!
This issue isn't related to a bug/enhancement/feature request or other accepted types of issue.

To ask questions, please see the following resources : 
* https://keras.io/
* https://keras.io/#support
* https://gitter.im/Keras-io/Lobby

Thanks!

If you think I made a mistake, please open another issue.
