### ISSUE TITLE
How to upsample or downsample the builtin datasets like CIFAR-10, CIFAR-100, MNIST to some other dimension?

### ISSUE THREAD

**Issue by shabbeersh** [keras-team/keras#10764]
How to upsample or downsample the builtin datasets (like CIFAR-10, CIFAR-100, MNIST) to some other dimension? For example from 32x32x3 to 64x64x3.
Thank you!

**Comment by kgrm** [comment]
Use an image processing library such as PIL or openCV.

**Comment by chriskoups** [comment]
Hello.
This issue isn't related to a bug/enhancement/feature request and you get an answer.
Can you close the so that developers will focus on the bugs or features?
There is a close button under the reply-comment section.
