### ISSUE TITLE
Non-deterministic order of updates

### ISSUE THREAD

**Issue by jlherren** [keras-team/keras#10769]
The following short program uses the functional API to swap two shared variables inside a function:

```
import numpy
from keras import Input, backend as K

inputs = Input(shape=(1,))
var1 = K.variable(numpy.ones(()))
var2 = K.variable(numpy.ones(()) * 2)
updates = [
    K.update(var1, var2),
    K.update(var2, var1),
]
f = K.function([inputs], [inputs + 1], updates)
f([numpy.zeros((1, 1))])
print(K.get_value(var1), K.get_value(var2))
```

Ignore the dummy input and output, I currently only care about the updates. It seems that the order in which the updates are applied is not deterministic when using the tensorflow backend.  I sometimes receive the output "1.0 1.0", "2.0 1.0" or "2.0 2.0" on the CPU and seemingly always "2.0 2.0" on a GPU.

With theano I get "2.0 1.0" consistently on both devices, which is also what I expect as the correct output. I was under the impression that all variables always refer to their value *before* the update, which should make such swapping possible. How can I control such updates that depend on each other?

This is on keras 2.2.0, tensorflow 1.9.0 and theano 1.0.2

**Comment by HughKu** [comment]
Hi @jlherren, I'm quite interested in your question and I do some experiments.

First, I turn your example code into tensorflow's equivalent and find that it does sometimes produces "2.0 1.0". From what I understand it should always output either "1.0 1.0" or "2.0 2.0". Check out this thread [(stackoverflow)](https://stackoverflow.com/questions/41780655/what-is-the-difference-between-tf-group-and-tf-control-dependencies). 

However from this experiment, this is not the case. Now I am confused and would you like to elaborate more on this "_I was under the impression that all variables always refer to their value before the update, which should make such swapping possible_".

```python
import numpy as np
import tensorflow as tf

tf.reset_default_graph()

# define tensors
var1 = tf.Variable(np.ones(())*1, dtype=tf.float32)  # 1
var2 = tf.Variable(np.ones(())*2, dtype=tf.float32)  # 2

init = tf.global_variables_initializer()

# define ops
op1  = tf.assign(var1, var2)
op2  = tf.assign(var2, var1)

# group ops
grp = tf.group([op1, op2]);
    
with tf.Session() as sess:
    sess.run(init)
    
    sess.run(grp)
    
    print(var1.eval(), var2.eval())
```

Back to your question **How can I control such updates that depend on each other?** I'm not sure if there is a better way so here I add some native tensorflow flavor:
- extra variable `tmp` to make swap possible
- tf control dependency to ensure execution dependency
```python
import numpy as np
import tensorflow as tf
from keras import Input, backend as K

inputs = Input(shape=(1,))
var1 = K.variable(np.ones(()))
var2 = K.variable(np.ones(()) * 2)
tmp  = K.variable(np.zeros(()))

op1  = K.update(tmp, var2)

with tf.control_dependencies([op1]):
    op2  = K.update(var2, var1)
    
    with tf.control_dependencies([op2]): 
        op3 = K.update(var1, tmp)
        
updates = [op1, op2, op3]

f = K.function([inputs], [inputs + 1], updates)
f([np.zeros((1, 1))])
print(K.get_value(var1), K.get_value(var2))
```
Hope this helps and please correct me if you find something wrong, thanks.

**Comment by yanboliang** [comment]
@HughKu gave a fair explanation, I have a little bit to add. ```K.function``` use ```tf.group``` underlying, and ```tf.group``` doesn't guarantee execution order. You can image it like multi-thread program, so "2.0 1.0" is also possible result.

**Comment by HughKu** [comment]
@yanboliang, thank you for the great feedback, so I suppose the user must be very careful dealing with such case.

FYI, I also find this thread ([Quora](https://www.quora.com/Does-TensorFlow-evaluate-common-nodes-to-multiple-ops-multiple-times)) provides a good view on this topic, in which two key points are made:  

- TensorFlow executes the minimal subgraph of its computational graph that is needed to compute all your fetches. Everything in the subgraph is executed once per call to sess.run().

- Other than the order defined and required by computational dependencies, computations can happen in any order.

**Comment by jlherren** [comment]
Thanks for all the insight. So it turns out I have three options:
* (a) Write code that does not rely on the order in which updates are executed
* (b) Write some native tensorflow code and stop supporting all backends
* (c) Write awkward code for handling this in all backends correctly

For my particular use-case I went with (a) and used K.get/set_value() from within a callback to avoid depending on the update order. So far so good.

**BUT:**

It seems that this affects some optimizers and causes them to behave in a non-deterministic way, here's an example for `SGD` with the decay param set:

```
import numpy
from keras import backend as K
from keras.optimizers import SGD

for _ in range(10):
    param = K.variable(value=numpy.ones(shape=()))
    loss = K.square(param)
    updates = SGD(decay=1).get_updates(loss, [param])

    f = K.function([], [loss], updates=updates)
    f([])
    print(K.get_value(param))
```

Outputs:
Theano, CPU: Always 0.98
Theano, GPU: Always 0.98
Tensorflow, CPU: Randomly 0.98 or 0.99
Tensorflow, GPU: Always 0.99

YMMV with tensorflow. I haven't investigated this thoroughly, but I suspect it's `K.update_add(self.iterations, 1)` that causes the issue, because the code following it uses `self.iterations`, which is sometimes the value before the update and sometimes the value after the update.

Given that this might affect learning performance, it seems quite an issue to me. Something similar happens with the `Adam` optimizer.
