### ISSUE TITLE
I have long sequence how to break up to subsequence for LSTM usage

### ISSUE THREAD

**Issue by georgekibirige** [keras-team/keras#10778]
My dataset have the following shape 
x_train = (8758, 13, 40,48)...input
y_train = (8758,18)..target

In more detail 8758 is the samples, 13 is features and each feature has values in 20,28 as image data.
The challenge is to convert that input into [samples, timesteps, features]

I try to flat the last two parts to become (8758,13, 1920) so that the input shape to lstm could be (1,13,1920) and output (1,18)

I am looking for advice how to break input dataset into right shape to get good generalization and good results

thanks

**Comment by chriskoups** [comment]
Hello.
Github is a development place and you submit an advice question in an issue section.
Please use programmer forums like stackoverflow to get advises.
For your advice, there is no right and wrong solution/division of your data if you understand what you are doing. If you don't then read some papers that are free.
Please close the issue with the button under the comment/reply box.
