### ISSUE TITLE
Value Error while loading model

### ISSUE THREAD

**Issue by savageyusuff** [keras-team/keras#10771]
Hi, I was training a mobilenet model for image classification. When i load the trainned model, it gave me this error: ValueError: Layer conv_pad_1 was called with an input that isn't a symbolic tensor. Received type: <class 'keras.layers.advanced_activations.ReLU'>. Full input: [<keras.layers.advanced_activations.ReLU object at 0x7f51501b7690>]. All inputs to the layer should be tensors.

I am not sure why it producing this error. I have update tensorflow and keras to its latest version
Keras 2.2.0
tensorflow-gpu 1.9.0

**Comment by savageyusuff** [comment]
[Github.zip](https://github.com/keras-team/keras/files/2226153/Github.zip)

This are the files

**Comment by raymond-yuan** [comment]
You're running into this issue because `keras.layers.ReLU` is the class module, you need to change it to `keras.layers.ReLU()` to create an instance

Changing this will make it work. 
```
with CustomObjectScope({'relu6': keras.layers.ReLU()}):
	model = load_model("mobilenet_v1_0.25_32_2class_batchsize1_eyes.h5")
```

**Comment by savageyusuff** [comment]
Thanks, it works
