### ISSUE TITLE
How to get the name of each layer in the keras model

### ISSUE THREAD

**Issue by songpeng326** [keras-team/keras#10774]
I am looking for a piece of code to get the name of each layer in the model that comes from keras.

**Comment by tRosenflanz** [comment]
This forum is for issues only and not implementation questions: please open stackoverflow issue and I will be happy to help you there.

**Comment by Dref360** [comment]
Hi!
This issue isn't related to a bug/enhancement/feature request or other accepted types of issue.

To ask questions, please see the following resources : 
* https://keras.io/
* https://keras.io/#support
* https://gitter.im/Keras-io/Lobby

Thanks!

If you think I made a mistake, please open another issue.
