### ISSUE TITLE
Using Decay in an optimizer brings up TF warning regarding deprecation of *=

### ISSUE THREAD

**Issue by istavnit** [keras-team/keras#10785]
There is a *= used in calculation of effective LR in the epoch, that makes TF complain.
![image](https://user-images.githubusercontent.com/7511567/43270570-63bcfa74-90c3-11e8-82b1-277f981cc5f1.png)

**Comment by chriskoups** [comment]
Hello.
Nice point out but, tenfsorflow and keras are updating quite fast.
However, it takes 3-6 months to remove something completely. In your case, you have a warning for something tensorflow will deprecate. There is no problem with your algorithm (I assume) and most probably, keras will be updated before the variable *= will be completely removed from tensorflow.
Please close the issue by pressing the close button under the reply/comment box.

**Comment by ymodak** [comment]
Closing issue since its resolved with the latest version of TensorFlow. Feel free to reopen if the problem still persists. Thanks!
