### ISSUE TITLE
Output_padding param in Conv2dTranspose Inaccessible

### ISSUE THREAD

**Issue by christianayala10** [keras-team/keras#10793]
Output_padding parameter is in the oficial Keras documentation but when I try to use it throws the following error:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-20-9f3a8f8cc782> in <module>()
----> 1 fcsiamese = create_siamese_fully_connected( (634,774,3), 500 )
      2 fcsiamese.summary()

<ipython-input-19-8ce71feefffb> in create_siamese_fully_connected(input_shape, features)
     45 
     46     # Padding + 1
---> 47     deconv1 = keras.layers.Conv2DTranspose(1024, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal', output_padding=(1,0))(distance)
     48     #deconv2 = Conv2DTranspose(1024, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal') (deconv1)
     49     #dout1 = Dropout(0.5) (deconv2)

~\AppData\Local\Continuum\anaconda3\envs\DeepLearning\lib\site-packages\keras\legacy\interfaces.py in wrapper(*args, **kwargs)
     89                 warnings.warn('Update your `' + object_name +
     90                               '` call to the Keras 2 API: ' + signature, stacklevel=2)
---> 91             return func(*args, **kwargs)
     92         wrapper._original_function = func
     93         return wrapper

~\AppData\Local\Continuum\anaconda3\envs\DeepLearning\lib\site-packages\keras\layers\convolutional.py in __init__(self, filters, kernel_size, strides, padding, data_format, activation, use_bias, kernel_initializer, bias_initializer, kernel_regularizer, bias_regularizer, activity_regularizer, kernel_constraint, bias_constraint, **kwargs)
    741             kernel_constraint=kernel_constraint,
    742             bias_constraint=bias_constraint,
--> 743             **kwargs)
    744         self.input_spec = InputSpec(ndim=4)
    745 

~\AppData\Local\Continuum\anaconda3\envs\DeepLearning\lib\site-packages\keras\legacy\interfaces.py in wrapper(*args, **kwargs)
     89                 warnings.warn('Update your `' + object_name +
     90                               '` call to the Keras 2 API: ' + signature, stacklevel=2)
---> 91             return func(*args, **kwargs)
     92         wrapper._original_function = func
     93         return wrapper

~\AppData\Local\Continuum\anaconda3\envs\DeepLearning\lib\site-packages\keras\layers\convolutional.py in __init__(self, filters, kernel_size, strides, padding, data_format, dilation_rate, activation, use_bias, kernel_initializer, bias_initializer, kernel_regularizer, bias_regularizer, activity_regularizer, kernel_constraint, bias_constraint, **kwargs)
    481             kernel_constraint=kernel_constraint,
    482             bias_constraint=bias_constraint,
--> 483             **kwargs)
    484         self.input_spec = InputSpec(ndim=4)
    485 

~\AppData\Local\Continuum\anaconda3\envs\DeepLearning\lib\site-packages\keras\layers\convolutional.py in __init__(self, rank, filters, kernel_size, strides, padding, data_format, dilation_rate, activation, use_bias, kernel_initializer, bias_initializer, kernel_regularizer, bias_regularizer, activity_regularizer, kernel_constraint, bias_constraint, **kwargs)
    102                  bias_constraint=None,
    103                  **kwargs):
--> 104         super(_Conv, self).__init__(**kwargs)
    105         self.rank = rank
    106         self.filters = filters

~\AppData\Local\Continuum\anaconda3\envs\DeepLearning\lib\site-packages\keras\engine\base_layer.py in __init__(self, **kwargs)
    126         for kwarg in kwargs:
    127             if kwarg not in allowed_kwargs:
--> 128                 raise TypeError('Keyword argument not understood:', kwarg)
    129         name = kwargs.get('name')
    130         if not name:

TypeError: ('Keyword argument not understood:', 'output_padding')

**Comment by GregBd20** [comment]
I am also having a similar issue. I actually noticed that the documentation
https://keras.io/layers/convolutional/
 says, "The amount of output padding along a given dimension must be lower than the stride along that same dimension", so it seems it would not work if stride=1. But why is it?

**Comment by Dref360** [comment]
@christianayala10 Are you on the latest version of Keras? This works on master.


@GregBd20 you can get more information here: https://stackoverflow.com/a/37927114/3784713

**Comment by CalinTimbusLucian** [comment]
I also get the same error, both with Keras 2.2.2 and 2.2.3.
Any solution to this problem?

**Comment by UdonDa** [comment]
I also get the same error with Keras 2.1.6.

**Comment by abtExp** [comment]
having the same error on keras 2.2.4
