### ISSUE TITLE
a

### ISSUE THREAD

**Issue by tomkake** [keras-team/keras#10796]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [ ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [ ] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by zchrissirhcz** [comment]
I'm in same problem here. I just read the official keras documentation and installed keras 2.2.2 and tensorflow 1.9. Those are all latest versions, but since the documentation is not upgraded, the problem is there. 

Reproducable code is:
```python
      # build the model
      model = Sequential()
      model.add(Dense(32, activation='relu', input_dim=100))
      model.add(Dense(10, activation='softmax'))                                                       
  
      # compile the model
      model.compile(optimizer='rmsprop',
            loss='categorical_crossentropy',
            metrics=['accuracy'])
  
      # prepare the data
      data = np.random.random((1000, 100))
      labels = np.random.randint(10, size=(1000, 1)) 
      one_hot_labels = keras.utils.to_categorical(labels, num_classes=10)
  
      # train the model
      model.fit(data, one_hot_labels, epochs=10, batch_size=32)
```

Which gives:
```
Using TensorFlow backend.
Traceback (most recent call last):
  File "demo1.py", line 47, in <module>
    demo_multiclass_cls()
  File "demo1.py", line 30, in demo_multiclass_cls
    model.add(Dense(10, activation='softmax'))
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/sequential.py", line 185, in add
    output_tensor = layer(self.outputs[0])
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 878, in call
    output = self.activation(output)
  File "/usr/local/lib/python2.7/dist-packages/keras/activations.py", line 29, in softmax
    return K.softmax(x)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 3154, in softmax
    return tf.nn.softmax(x, axis=axis)
TypeError: softmax() got an unexpected keyword argument 'axis'

```
