### ISSUE TITLE
Error when checking target: expected dense_2 to have shape (20,) but got array with shape (1000,) while running pretrained_word_embeddings.py

### ISSUE THREAD

**Issue by jonanem** [keras-team/keras#10791]
Error when checking target: expected dense_2 to have shape (20,) but got array with shape (1000,) while running pretrained_word_embeddings.py

https://github.com/keras-team/keras/blob/master/examples/pretrained_word_embeddings.py

**Comment by chriskoups** [comment]
the error is related to your network as far as I can understand.
Can you post your code or the initial part?
I can assume that you did not divided the network as it must be. You have a shape of 20 but you try to pass 1000 without batches.

**Comment by chriskoups** [comment]
I am not sure what is costing that problem.
Wild guess will be that the lables_index is 20 and that is creating the problem. Can you confirm the output of len(labels_index)?

**Comment by jonanem** [comment]
output is 20 to predict 20 Categories

**Comment by tRosenflanz** [comment]
Github is for issues in Keras while this is just an implementation error. In future please open stackoverflow questions instead of posting on Github:
```
x_train = data[:-num_validation_samples]
y_train = data[:-num_validation_samples] .  # supposed to be labels
x_test = data[-num_validation_samples:]
y_test = data[-num_validation_samples:] .  # supposed to be lablels
```

**Comment by jonanem** [comment]
Thank you so much for your help

**Comment by johnbond2** [comment]
I have a similiar error message: "ValueError: Error when checking target: expected dense_2 to have shape (10,) but got array with shape (1,)", and it seems that what is causing this problem is the loss parameter in the model architecture, when I use `loss = 'sparse_categorical_crossentropy'` gives me no error but when using this one, it does `loss = 'categorical_crossentropy'`

**Comment by RaviChandraMadipadiga** [comment]
> 
> 
> I have a similiar error message: "ValueError: Error when checking target: expected dense_2 to have shape (10,) but got array with shape (1,)", and it seems that what is causing this problem is the loss parameter in the model architecture, when I use `loss = 'sparse_categorical_crossentropy'` gives me no error but when using this one, it does `loss = 'categorical_crossentropy'`

But even after i changed that still i got that error but with less error shape
