### ISSUE TITLE
how to add  a two-level custom loss function into custom_objects when load_model ?

### ISSUE THREAD

**Issue by ipp123456** [keras-team/keras#10805]
Hi, i defined a two-level custom loss function in my model , it works well in training. But when i try to load saved model, keras shows: 
```
    def customLoss(self, weight, graph_dis, lamda1=0.2):
        def lossFunction(y_true,y_pred):  
            loss1 = categorical_crossentropy(y_true, y_pred)
            loss2 =K.mean(K.mean(multiply([(K.ones_like(weight) - weight), graph_dis])))
            loss = loss1 + lamda1 * loss2
            return loss
        return lossFunction
```
ValueError: Unknown loss function:lossFunction
and, How do I solve this error?  thanks.

**Comment by piyush-kgp** [comment]
Can you share the line of code that outputs the error. It seems like you are writing all this inside a class but then never use the object (I can't see a self inside any function definition) inside the function customLoss.

**Comment by akbacak** [comment]
You can  import loss function by
from 'trained_model_name.h5'  import custom_loss_func_name

Then you should load the saved model by 
model = load_model('trained_model_name.h5', custom_objects={'custom_loss_func_name': custom_loss_func_name} )

This will work !! BUT when you  load pretrained model in that way TRAINING stage is starting !!!  

I still keep searching this issue why is like that ?

**Comment by ipp123456** [comment]
I have solved this problem by referring to:
(https://stackoverflow.com/questions/48373845/loading-model-with-custom-loss-keras)
The following is my realization.
```
    def customLoss(weight, graph_dis, lamda1=0.2):
        def lossFunction(y_true,y_pred):  
            loss1 = categorical_crossentropy(y_true, y_pred)
            loss2 =K.mean(K.mean(multiply([(K.ones_like(weight) - weight), graph_dis])))
            loss = loss1 + lamda1 * loss2
            return loss
        return lossFunction
```
when you load model, the following code is working!
```
from lstm_model import LSTM_MODEL, customLoss
from keras import backend as K
from keras.models import load_model

model = load_model(file_path, custom_objects={"lossFunction":customLoss(K.variable(np.ones((1,1))),
                                 K.variable(np.ones((1,1))), 0.2) })
```
