### ISSUE TITLE
Why 2 is subtracted from number of time-steps

### ISSUE THREAD

**Issue by kaleeswaranm** [keras-team/keras#10840]
https://github.com/keras-team/keras/blob/e77a4cf3f85b45ad4275dfd661073ace1cc06e5a/examples/image_ocr.py#L272

https://www.tensorflow.org/api_docs/python/tf/keras/backend/ctc_batch_cost

tensorflow documentation mentions input length to be equal to number of time-steps

**Comment by Heisenberg0391** [comment]
because they think the first couple outputs of the RNN tend to be garbage, so they removed them in ctc_lambda_func(), y_pred = y_pred[:, 2:, :], so you will get a equal sequence for ctc
