### ISSUE TITLE
set_keras_submodules() missing 1 required positional argument: 'engine'

### ISSUE THREAD

**Issue by pezzati** [keras-team/keras#10851]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [ ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [ ] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by karolbadowski** [comment]
This is the top searched page when looking for solution of a problem "set_keras_submodules() missing 1 required positional argument: 'engine'".

The fact that this issue exists and is closed without the solution is unnecessary spam that makes it harder to find the actual solution.

Please link the url to solution or delete the issue.

**Comment by TanayKarve** [comment]
I uninstalled Keras and all its dependencies completely and reinstalled the latest one.
Fixed it for me.

**Comment by loomcode** [comment]
Tensorflow 1.12.0, Keras 2.2.4  

I won't just upgrade to the "most recent" versions because those will come with their own problems.  For one, they won't even run on my hardware.  Additionally, the stored model I am using was built on a different machine so I have to match the versions or I can be certain it won't run.  Why is this closed without a solution?
