### ISSUE TITLE
Is there a way in Keras to apply different weights to a cost function in different examples?

### ISSUE THREAD

**Issue by Larrykouyl** [keras-team/keras#10853]
I have a similar question like https://github.com/keras-team/keras/issues/2115.

However things are more complicated. 
This is the orginal question.
> 
"I am trying to implement a classification problem with three classes: 0,1 and 2. I would like to fine tune my cost function so that missclassification is weighted some how. In particular, predicting 1 instead of 2 should give twice the cost than predicting 0. "
> 
My problem has 4 classes and I want to fine tune my cost function so that missclassification is weighted **in different training data based on a list**. 
In the first example, predicting 3 instead of 2 should give twice the cost than predicting 1 or 0 instead of 2. 

Target | Most Unwanted Result | Unwanted Result | Unwanted Result
-- | -- | -- | --
2 | 3 | 1 | 0
3 | 2 | 1 | 0
1 | 3 | 0 | 2
2 | 0 | 1 | 3
3 | 2 | 1 | 0

**Comment by davideboschetto** [comment]
This is quite a big problem, conceptually. 
I'm very interested in finding a solution, too.
