### ISSUE TITLE
ImageDataGenerator returns empty/white images

### ISSUE THREAD

**Issue by ghost** [keras-team/keras#10869]
So I'm following this tutorial: https://blog.keras.io/building-powerful-image-classification-models-using-very-little-data.html

When I try and see the transformations applied to my image, I keep getting white images / empty images with no transformations applied to them.

Here is my code below:

```
from keras.preprocessing.image import ImageDataGenerator, array_to_img, img_to_array, load_img

datagen = ImageDataGenerator(
        rotation_range=40,
        width_shift_range=0.2,
        height_shift_range=0.2,
        shear_range=0.2,
        zoom_range=0.2)

path = 'C:\\Users\\merpmerp\\Desktop\\test\\Resized\\test\\bad\\'

img = load_img(path + 'batch4 (1) resized.png')  # this is a PIL image
x = img_to_array(img)  # this is a Numpy array with shape (3, 150, 150)
x = x.reshape((1,) + x.shape)  # this is a Numpy array with shape (1, 3, 150, 150)

# the .flow() command below generates batches of randomly transformed images
# and saves the results to the `preview/` directory
i = 0
for batch in datagen.flow(x, batch_size=1,
                          save_to_dir=path, save_prefix='test', save_format='png'):
    i += 1
    if i > 20:
        break  # otherwise the generator would loop indefinitely
```

Any help?

**Comment by TheShazam** [comment]
So I get this behaviour when I try the generator on large image file sizes (55 mb). However, it works just fine for smaller file sizes. 

Is there anyway I can override the file size limit or something?

**Comment by KeironO** [comment]
I'm unable to reproduce this bug.

Would you be willing to share some of your data for testing purposes?

**Comment by wrrogers** [comment]
OMG, I have the same problem.

**Comment by wrrogers** [comment]
I tried only applying, horizontal_flip=True.  I get every image the same piece (corner) show up from the edge way larger than the original.  The image somehow got enlarged and shifted, so that I can no longer see anything.

**Comment by KeironO** [comment]
I've just been able to reproduce this bug using the following script.

```python
from keras.datasets import mnist

from keras.preprocessing.image import ImageDataGenerator
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import numpy as np

(X, y), _ = mnist.load_data()
X = X.reshape(X.shape[0], 1, 28, 28)
X = X[:100]


datagen = ImageDataGenerator(width_shift_range=0.2)
datagen.fit(X)


imgs = []
batches = 0
for i in datagen.flow(X, batch_size=32):
    batches += 1
    for x in i:
        img = np.asarray(x).reshape((28, 28))
        imgs.append([plt.imshow(img, cmap='gray', animated=True)])
    print"Completed batch : %i" % (batches)
    if batches >= len(X) / 32:
        break

fig = plt.figure()
ani = animation.ArtistAnimation(fig, imgs, interval=50, blit=True,
                                repeat_delay=1000)
ani.save("test.gif", writer="imagemagick")
```

Which produces the following (blank) gif:

![blankgif](https://i.imgur.com/nOS12d6.gif)

**Comment by cfusterb** [comment]
I know this was asked a long time ago but it happened to me today and the error was that I needed to rescale images. If it happens to someone try to divide your image into 255 before printing it. If it works, apply it to all images. 

For me was:
one_picture = batchX[1,:,:,:]/255 
plt.imshow(one_picture)

And it worked!

**Comment by peternasser99** [comment]
same here
