### ISSUE TITLE
Question image format flow_from_directory

### ISSUE THREAD

**Issue by ellipfaehlerUMCG** [keras-team/keras#10867]
Dear all,

I have a question about the function flow_from_directory. 
I am working with medical images. These images are coming in nifti format (ending .nii). I would like to rotate/scale these images. So, I would like to use the datagenerator. 
Is that possible to use the data generator with these images? I could only find examples that worked with .jpg and .png images... 

Thanks a lot for your answer,

regards

**Comment by Dref360** [comment]
We do not support .nii. I don't think we should support it since it adds a dependency (nibabel) and it's not widely used. Feel free to inherit ImageDataGenerator to allow your usecase.

**Comment by ymodak** [comment]
Closing this issue since Dref360's comment resolves this issue. Feel free to reopen if have any follow up questions. Thanks!

**Comment by umitkilic** [comment]
Hi @ellipfaehlerUMCG , I have the same problem. How did you manage it? I use nifti file and want to use ImageDataGenerator for deep learning implementation. Converting .nii into .jpeg or .png may cause to lose information.
