### ISSUE TITLE
InvalidArgumentError! Problem with weights/indices when using a model trained in windows/python3.6 on a mac

### ISSUE THREAD

**Issue by bsugerman** [keras-team/keras#10877]
I have a CNN that I made using character embedding on my windows 10 machine using python 3.6 and keras 2.2.0. I put that same version on my mac and I can't run it because of an error with the embedding.

My embedding layer uses an input dim of 101, which is the size of my weights matrix; I also use zero masking. Everything works perfectly within windows, but on my mac, when it gets to a character that is indexed at 101, I get the following error:

`InvalidArgumentError: indices[26,6] = 101 is not in [0, 101)`

This happens with python 2.7 and 3.6. But the model runs perfectly on windows. I am using the exact same input files. Any ideas what is going on, and what I can do about it?

more details: here is info about the weights matrix and how I use it
   
    weights.shape = (101,101)
    inputs=L.Input(shape=(length,))                                 `
    embedding=L.Embedding(input_dim=weights.shape[0],
                          output_dim=weights.shape[1],
                          input_length=length,
                          weights=[weights],
                          mask_zero=True,trainable=False)(inputs)
   The error:

> InvalidArgumentError: indices[31,60] = 101 is not in [0, 101)
> [[Node: embedding_2/embedding_lookup = GatherV2[Taxis=DT_INT32, Tindices=DT_INT32, Tparams=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](embedding_2/embeddings/read, embedding_2/Cast, embedding_2/embedding_lookup/axis)]]

**Comment by bsugerman** [comment]
The "solution" seems to be that tensorflow-gpu doesn't mind if the weights array is smaller than a feature, while tensorflow-cpu does. So this isn't a keras issue.

**Comment by SouthBay1005** [comment]
> The "solution" seems to be that tensorflow-gpu doesn't mind if the weights array is smaller than a feature, while tensorflow-cpu does. So this isn't a keras issue.

so if I use the tensorflow-cpu, is there an effective way to solve the problem?
