### ISSUE TITLE
Multi-thread online training for multiple copies of a model

### ISSUE THREAD

**Issue by link-er** [keras-team/keras#10875]
Hello.
My task is to create cetrain amount of copies of the same network and run each in a separate thread, where they are waiting for data given batch at a time and once they received the data they should make a training step. I am using Keras + Tensorflow on GPU.

First problem that I ran into that simply creating a model in one thread and then trying to train it in another has to be handled with setting a graph and a session, otherwise I was getting an exception of trying to work with nodes from one graph summing up to nodes of another.
When I created separate sessions and graphs for each of the nodes and was specifying it with session.as_default and graph.as_default it was working, but the more processes I am running, the more TF sessions are created and they are completely slowing down the calculations. So I returned to the idea of having one session only, that I am getting via keras.backend.get_session() and using everywhere together with graph of this session.
But here the behavior becomes completely random. It might run without errors (for 1 and 2 workers), it might give an error of initialization

```
lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 322, in _init_from_args
    "initializer." % name)
ValueError: Initializer for variable dense_4/BiasAdd/training/SGD/Assign_11/training/SGD/gradients/Fill/dense_9/kernel/ is from inside a control-flow construct, such as a loop or conditional. When creating a variable inside a loop or conditional, use a lambda as the initializer.

```
 or 

```
File "/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3665, in colocate_with
    self._colocation_stack.pop()
IndexError: pop from empty list
```

depending on how fast it starts the threads.

Network creation:

```
import tensorflow as tf
from keras.models import Model
from keras.layers import Input, Dense, Dropout, Conv2D, MaxPooling2D, Flatten
from keras.initializers import glorot_uniform
from keras import optimizers
import numpy as np
from keras import backend as K

_SESSION = K.get_session()

class LearnerFactory():
    def getKerasNN(self, updateRule, learningRate, lossFunction, batchSize):
        with _SESSION.as_default():
            with _SESSION.graph.as_default():
                # network creation
```

Then the update step looks like this:

```
        with self._session.as_default():
            with self._session.graph.as_default():
                metrics = self._core.train_on_batch(np.asarray([record[0] for record in data]), np.asarray([record[1] for record in data]))
```

What is the correct solution for using sessions and graphs in this situation?

**Comment by wangyexiang** [comment]
Do you sovle your problem？ @link-er
