### ISSUE TITLE
Error loading saved model with renamed layers

### ISSUE THREAD

**Issue by tsampazk** [keras-team/keras#10894]
I ran into this problem, but i'm not 100% sure if it is a bug or there is something wrong with my code, renaming layers like that. 

I have keras 2.2.2 and tensorflow 1.9.0 installed through conda, using Pycharm 2017.3.3

Here a simple example reproducing the error:

```
from keras import *
import numpy as np

trainSet = [[0,0], [1,0], [0,1], [1,1]]
trainLabels = [0, 1, 1, 0]

modelInp = layers.Input(shape=(2,))
h = layers.Dense(4, activation="sigmoid")(modelInp)
modelOut = layers.Dense(1, activation="linear")(h)
model1 = models.Model(inputs=modelInp, outputs=modelOut)
model1.compile(loss="mse", optimizer=optimizers.Adam())

for e in range(10):
    model1.fit(np.array(trainSet), np.array(trainLabels), verbose=False)

model1.name = "m1"
# Layer renaming causes the bug, if you comment the for loop out it works correctly
for l in model1.layers:
    l.name = l.name + "m1"

print(model1.predict(np.array([[0,0]])))
print(model1.predict(np.array([[1,0]])))

model1.save("m1.h5")

del model1

model1 = models.load_model("m1.h5")

print(model1.predict(np.array([[0,0]])))
print(model1.predict(np.array([[1,0]])))
```

When i rename the layers, during loading i get this error:

Traceback (most recent call last):
  File "saveloadtest.py", line 39, in <module>
    m1 = models.load_model("m1.h5")
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\saving.py", line 263, in load_model
    load_weights_from_hdf5_group(f['model_weights'], model.layers)
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\saving.py", line 900, in load_weights_from_hdf5_group
    str(len(filtered_layers)) + ' layers.')
ValueError: You are trying to load a weight file containing 2 layers into a model with 0 layers.

I saved the model with and without the renaming at a json file and the renamed layers json file inbound nodes for both dense layers and the general input/output layers of the model are empty.

**Comment by tsampazk** [comment]
In my original code i am stacking different models loaded from h5 files. I needed to rename the models from their default names because they all had the same one, so they couldn't be connected (needed to have unique names or something). 

To solve this i renamed the models. I also renamed the layers to avoid any further names being the same (like layers from different models having the same name, "Dense1", etc). I just added the name of the model at the end of the layer name like in the example. Apparently for my code it wasn't necessary and caused this error when loading.

**Comment by wjakobw** [comment]
In my opinion it would be very good if the saving and loading were improved so that renamed layers are loaded correctly. 

To demonstrate how it breaks down for the user I did some tests based on this first example using the functional api ["First example: a densely-connected network"](https://keras.io/getting-started/functional-api-guide/)

Keras version: 2.1.6
Tensorflow version: 1.8.0

```python
from keras.layers import Input, Dense
from keras.models import Model
from keras.models import load_model
inputs = Input(shape=(784,))

x = Dense(64, activation='relu')(inputs)
x = Dense(64, activation='relu')(x)
predictions = Dense(10, activation='softmax')(x)

model = Model(inputs=inputs, outputs=predictions)
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Rename 1 layer (I tried with all of these).
# model.layers[0].name = "layer0"
# model.layers[1].name = "layer1"
# model.layers[2].name = "layer2"
model.layers[3].name = "layer3"
assert len(model.layers) == 4  # Didn't forget any layer.

filepath = '/home/ubuntu/saved_neural_networks/1_test/temp.h5'
model.save(filepath)

loaded_model = load_model(filepath)
```

If the output layer (layers[3]) is renamed, the program crashes on load.

    File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/models.py", line 273, in load_model
      topology.load_weights_from_hdf5_group(f['model_weights'], model.layers)
    File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/engine/topology.py", line 3365, in load_weights_from_hdf5_group
      str(len(filtered_layers)) + ' layers.')
    ValueError: You are trying to load a weight file containing 3 layers into a model with 0 layers.

If the input layer (layers[0]) is renamed, the program crashes with another error on load:

    File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/models.py", line 270, in load_model
      model = model_from_config(model_config, custom_objects=custom_objects)
    File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/models.py", line 347, in model_from_config
      return layer_module.deserialize(config, custom_objects=custom_objects)
    File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
      printable_module_name='layer')
    File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 144, in deserialize_keras_object
      list(custom_objects.items())))
    File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/engine/topology.py", line 2552, in from_config
      return cls(inputs=input_tensors, outputs=output_tensors, name=name)
    File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
      return func(*args, **kwargs)
    File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/engine/topology.py", line 1811, in __init__
      str(layers_with_complete_input))
    RuntimeError: Graph disconnected: cannot obtain value for tensor Tensor("layer0:0", shape=(?, 784), dtype=float32) at layer "layer0". The following previous layers were accessed without issue: []


If an intermediary layer is renamed, the loading gets stuck in an infinite while loop:
	(line 2530 in my topology.py, seems to be moved [here](https://github.com/keras-team/keras/blob/244546c2fe5165b6770eb456afd5fac8878473c5/keras/engine/network.py#L1024) in master)

```python
# Then we process nodes in order of layer depth.
# Nodes that cannot yet be processed (if the inbound node
# does not yet exist) are re-enqueued, and the process
# is repeated until all nodes are processed.
while unprocessed_nodes:
    for layer_data in config['layers']:
        layer = created_layers[layer_data['name']]
        if layer in unprocessed_nodes:
            for node_data in unprocessed_nodes.pop(layer):
                process_node(layer, node_data)
```

Here is a simple workaround. It relies on model.layers having constant ordering even after model load, which I assume it has. I did some experiments which didn't disprove this and checked the source at obvious places which might break this assumption, it looked good to me.

```python
import json

# When new layer names are needed:
original_layer_names = [layer.name for layer in model.layers]
new_layer_names = ['layer0', 'layer1', 'layer2', 'layer3']
for i, layer in enumerate(model.layers):
    layer.name = new_layer_names[i]
with open('new_layer_names.json', 'w') as f:
    json.dump(new_layer_names, f)

# When saving:
for i, layer in enumerate(model.layers):
    layer.name = original_layer_names[i]
model.save(filepath)

# When loading:
with open('new_layer_names.json', 'r') as f:
    new_layer_names = json.load(f)
loaded_model = load_model(filepath)
for i, layer in enumerate(loaded_model.layers):
    layer.name = new_layer_names[i]
```
