### ISSUE TITLE
Mask Zero padding in Embedding layer

### ISSUE THREAD

**Issue by borisRa** [keras-team/keras#10895]
Hi,

The goal is to transform each index to a embedded vector and then average all vectors to a single one. 
 **I must  to ignore padded zeros !**

The averaged vector should be transferred to next layers.

Tried several approaches with no success :( 

This is my code :
```


from keras.layers import Embedding,Input,AveragePooling1D
from keras.models import Model
from keras.preprocessing.text import Tokenizer as Keras_Tokenizer
from keras.preprocessing.sequence import pad_sequences

import numpy as np

embedding_size = 4
vocab_size = 9 + 1
max_sequence_length = 5 


my_input = Input(shape=(max_sequence_length,), name='input')

embedding_layer = Embedding(output_dim=embedding_size, input_dim=vocab_size,input_length=1, mask_zero=True,name='my_embedding')
embedding = embedding_layer(my_input)

#Calc average off all embedding vectors
avg=AveragePooling1D(pool_size=max_sequence_length)(embedding)
model = Model(inputs= [my_input], outputs=avg)

model.get_weights() 


####################
#Sanity check
####################

aa = np.array([[0,0,2,4]])
model.predict(aa)[0][0] 
```
And getting this error :

```
TypeError: Layer average_pooling1d_1 does not support masking, but was passed an input_mask: Tensor("my_embedding_9/NotEqual:0", shape=(?, 5), dtype=bool)
```
Any one can assist  ? 

Many thanks,
Boris

**Comment by yanboliang** [comment]
@borisRa It makes a lot of sense to support masking in your scenario. But I think you should use ```GlobalAveragePooling1D``` rather than ```AveragePooling1D````, as you want to compute average on all words representation vectors in a sentence. I sent #10913 to make ```GlobalAveragePooling1D``` support masking, wish it can help you.

**Comment by borisRa** [comment]
Thanks !  GlobalAveragePooling1D is also a solution ! 

Though it doesn't support masking too :(

`TypeError: Layer global_average_pooling1d_2 does not support masking, but was passed an input_mask:`
Do you know when this functionality will be available (#10913 ) ?

**Comment by yanboliang** [comment]
@borisRa Your code works well in my local environment with #10913 , can you check your python environment? Do you imported ```tf.keras``` as well? If so, it would throw exceptions as you describe. FYI https://stackoverflow.com/questions/51821537/attributeerror-node-object-has-no-attribute-output-masks/51831434 .

**Comment by borisRa** [comment]
@yanboliang  Sorry for the delay in my response .  I have downloaded the pooling.py file from [here](https://github.com/yanboliang/keras/blob/9461834ef39e92404e4bb14913cd8a7e20dcabd3/keras/layers/pooling.py)   and replaced it with this one : /anaconda/lib/python3.6/site-packages/keras/layers/pooling.py

With 
`avg= GlobalAveragePooling1D()(embedding)` I am getting this error : 
`Traceback (most recent call last):`

 ` File "<ipython-input-66-4965d71f0838>", line 1, in <module>`
 ` model.predict(aa) File "/anaconda/lib/python3.6/site-packages/keras/engine/training.py", line 1167, in predict    steps=steps)`

  `File "/anaconda/lib/python3.6/site-packages/keras/engine/training_arrays.py", line 302, in predict_loop
   outs[i][batch_start:batch_end] = batch_out`

`ValueError: could not broadcast input array from shape (3,4) into shape (1,4)`

The same code with :` avg=AveragePooling1D(pool_size=max_sequence_length)(embedding)`
does work .

any ideas ?

**Comment by yanboliang** [comment]
@borisRa Can you share the minimum code snippet to reproduce this? Because I can't reproduce it.

**Comment by borisRa** [comment]
@yanboliang 
Sure the code is attached : 

[Masking_GlobalAverage1D.txt](https://github.com/keras-team/keras/files/2344554/Masking_GlobalAverage1D.txt)

**Comment by yanboliang** [comment]
@borisRa After checking your code, I found you set ```input_length``` incorrectly. In your case, ```input_length``` should be 3 rather than 1. That leads the error in the downstream layer(```GlobalAveragePooling1D```). Your code can run well if you change ```input_length``` to correct value(3). Actually, ```Embedding``` should throw exceptions if you set ```input_length```  incorrectly, but there is a bug and I sent #11091 to fix it.

**Comment by borisRa** [comment]
@yanboliang
It does worked ! thanks ! the most simple way is just remove the input_length parameter .  Now I have the same error for flatten layer :( 

`TypeError: Layer Flatten_Items does not support masking, but was passed an input_mask: Tensor("Item-Embedding/NotEqual:0", shape=(?, 1), dtype=bool)
`

**Comment by yanboliang** [comment]
@borisRa It seems flatten layer doesn't support masking. Do you have a real use case can show the necessary? If yes, I can figure out a way to make it supports. Thanks.

**Comment by borisRa** [comment]
@yanboliang I do have a real use case which is related to the GlobalAveragePooling1D with masking as well.

I have embedding layer that gets as an input item ID and the output dimension is : `TensorShape([Dimension(None), Dimension(1), Dimension(12)])`   I have another Embeed layer that gets as input user ID with the same output shape.

Then I apply matrix multiplication between the two. 
To do this I FLAT the both outputs to `TensorShape([Dimension(None), Dimension(None)])` and just then apply the multiplication  (The error comes here `TypeError: Layer Flatten_Items does not support masking, but was passed an input_mask: Tensor("Item-Embedding/NotEqual:0", shape=(?, 1), dtype=bool)`).

Additionally I use the **same** Item embedding layer to calculate `GlobalAveragePooling1D `  over set of items  ( this is related to the request above ).

Thank you !

**Comment by yanboliang** [comment]
@borisRa 
It's not easy to implement general masking in ```Flatten``` layers, as you don't know exactly the number of dimension, any dimension great than 3 is legal to be input of ```Flatten``` layer. However, the masking is only used for a sequence to skip time steps, which is usually a fixed number of dimension 3(batch, timesteps, dim). I think you can define a custom ```Lambda``` layer to meet your requirement.

**Comment by borisRa** [comment]
@yanboliang 
> BTW, why are you make `Flatten` follow `Embedding`, I don't think this design makes a lot of sense.

These two flows are mathematically the same ? 
Flow #1 : (None,12)   dot  (None,12) => (None,1)
Flow #2 : (None,1,12) dot (None,1,12) => (None,1,1) => Flatten => (None,1)

**Comment by MTDzi** [comment]
I'm curious if this Issue was somehow resolved -- I'm facing a similar problem.

**Comment by GoingMyWay** [comment]
Same under TF 1.x. Not solved
