### ISSUE TITLE
VGG19's preprocess_input - Cast error

### ISSUE THREAD

**Issue by danmoller** [keras-team/keras#10902]
The preprocessing function for VGG19 can't deal with "uint" arrays:

    /opt/conda/lib/python3.6/site-packages/Keras-2.1.5-py3.6.egg/keras/applications/imagenet_utils.py in _preprocess_numpy_input(x, data_format, mode)      
          80                 x[:, 2, :, :] /= std[2]      
          81 else: 
    ----> 82     x[..., 0] -= mean[0]      
          83     x[..., 1] -= mean[1]      
          84     x[..., 2] -= mean[2]

     TypeError: Cannot cast ufunc subtract output from dtype('float64') to dtype('uint8') with casting rule 'same_kind'

**Comment by yanboliang** [comment]
@danmoller Can you share the code which can reproduce the error? It seems we have converted numpy array to ```dtype = float``` inside keras functions.

**Comment by DevashishPrasad** [comment]
@yanboliang That just worked for me
