### ISSUE TITLE
Error: Graph disconnected when it really isn't...

### ISSUE THREAD

**Issue by ale152** [keras-team/keras#10904]
Hello!
I'm having an issue with Keras giving me and error of "Graph disconnected", while I think the graph is not really disconnected...

I've got a certain network doing some features extraction:
```
net = Conv Conv Conv...
net = Flatten()(net)
```

I then want to calculate the parameters of a Gaussian function using a Dense layer. This Gaussian function will be used in parallel with the rest of the network:

```
gauss_par = Dense(2, activation='relu')(net)
# Define a vector from 1 to n_frames
x1d = K.tf.range(0, n_frames, dtype='float32')
# Transform the vector into a tensor of shape [batch_size, n_frames]
x = K.tf.tile(K.tf.reshape(x1d, [1, -1]), [K.tf.shape(inputs)[0], 1])
# Gaussian function
gaussian = K.tf.exp(-K.tf.pow(x - gauss_par[:, 0], 2) / 2 / K.tf.pow(gauss_par[:, 1], 2))
# Transform the tensorflow tensor into a keras tensor
gaussian_layer = Input(tensor=gaussian, name='tf')
```

This gaussian_layer is then multiplied with the rest of the network.
The error I'm getting is:

> RuntimeError: Graph disconnected: cannot obtain value for tensor Tensor("Exp_2:0", shape=(?, 100), dtype=float32) at layer "tf". The following previous layers were accessed without issue: ['input_1']

It looks like keras is unable to see the tensorflow tensor which is generated as input. I'm really sure I even need to use the Input layer to transform the tensorflow tensor into a keras tensor, but that's what I've found in the doc. Am I doing this wrong?

Thank you,
Alessandro

Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by ale152** [comment]
Sure! The input_1 is my real input, where i feed my images:
inputs = Input(shape=(frame_size[0], frame_size[1], n_frames))

If I train the network without the extra Gaussian layer, everything works fine. However, I need to introduce this additional tensor multiplication in my architecture. Is this a bug?

**Comment by ale152** [comment]
I wrote a full script that demonstrate this problem (based on the MNIST cnn example):

```python
'''Trains a simple convnet on the MNIST dataset.

Gets to 99.25% test accuracy after 12 epochs
(there is still a lot of margin for parameter tuning).
16 seconds per epoch on a GRID K520 GPU.
'''

from __future__ import print_function
import keras
from keras.datasets import mnist
from keras.models import Model, Input
from keras.layers import Dense, Dropout, Flatten, Multiply
from keras.layers import Conv2D, MaxPooling2D
from keras import backend as K

batch_size = 128
num_classes = 10
epochs = 12

# input image dimensions
img_rows, img_cols = 28, 28

# the data, split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

if K.image_data_format() == 'channels_first':
    x_train = x_train.reshape(x_train.shape[0], 1, img_rows, img_cols)
    x_test = x_test.reshape(x_test.shape[0], 1, img_rows, img_cols)
    input_shape = (1, img_rows, img_cols)
else:
    x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
    x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)
    input_shape = (img_rows, img_cols, 1)

x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255
print('x_train shape:', x_train.shape)
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

# convert class vectors to binary class matrices
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

inputs = Input(shape=input_shape)
net = Conv2D(32, kernel_size=(3, 3),
                 activation='relu')(inputs)
net = Conv2D(64, (3, 3), activation='relu')(net)
net = MaxPooling2D(pool_size=(2, 2))(net)
net = Dropout(0.25)(net)
net = Flatten()(net)

gauss_par = Dense(2, activation='relu')(net)
# Define a vector from 1 to n_frames
x1d = K.tf.range(0, 9216, dtype='float32')
# Transform the vector into a tensor of shape [batch_size, n_frames]
x = K.tf.tile(K.tf.reshape(x1d, [1, -1]), [K.tf.shape(inputs)[0], 1])
# Gaussian function
gaussian = K.tf.exp(-K.tf.pow(x - gauss_par[:, 0], 2) / 2 / K.tf.pow(gauss_par[:, 1], 2))
# Transform the tensorflow tensor into a keras tensor
gaussian_layer = Input(tensor=gaussian, name='tf')

net = Multiply()([net, gaussian_layer])
net = Dense(128, activation='relu')(net)
net = Dropout(0.5)(net)
outputs = Dense(num_classes, activation='softmax')(net)

model = Model(inputs=inputs, outputs=outputs)
model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer=keras.optimizers.Adadelta(),
              metrics=['accuracy'])

model.summary()
model.fit(x_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          validation_data=(x_test, y_test))
score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])
```

The error is:
```
RuntimeError: Graph disconnected: cannot obtain value for tensor Tensor("Exp_2:0", shape=(?, 9216), dtype=float32) at layer "tf". The following previous layers were accessed without issue: ['input_2', 'conv2d_3', 'conv2d_4', 'max_pooling2d_2', 'dropout_3', 'flatten_2']
```

**Comment by Dref360** [comment]
You shouldn't use an Input for this.

```
def my_lambda(x):
    inputs, net = x
    gauss_par = Dense(2, activation='relu')(net)
    # Define a vector from 1 to n_frames
    x1d = K.tf.range(0, 9216, dtype='float32')
    # Transform the vector into a tensor of shape [batch_size, n_frames]
    x = K.tf.tile(K.tf.reshape(x1d, [1, -1]), [K.tf.shape(inputs)[0], 1])
    # Gaussian function
    gaussian = K.tf.exp(-K.tf.pow(x - gauss_par[:, 0], 2) / 2 / K.tf.pow(gauss_par[:, 1], 2))
    # Transform the tensorflow tensor into a keras tensor
    return gaussian

gaussian_layer = Lambda(my_lambda)([inputs, net])
```

You seem to have a problem with the shape of `gaussian_layer`.
