### ISSUE TITLE
ValueError: Error when checking target: expected dense_8 to have 2 dimensions, but got array with shape (X, 172800, 3)

### ISSUE THREAD

**Issue by AliRaza21918** [keras-team/keras#10915]
here is my model:

X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255

Y_train = np_utils.to_categorical(y_train, 3)
Y_test = np_utils.to_categorical(y_test, 3) 

model = Sequential()

model.add(Convolution2D(32, (3, 3), activation='relu', input_shape=(360,480,3)))
model.add(Convolution2D(32, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Convolution2D(16, (3, 3), activation='relu'))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(172800, activation='softmax')) 
         
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()
model.fit(X_train, Y_train, 
        batch_size=8, nb_epoch=10, validation_data=(X_test, Y_test), verbose=1)

score = model.evaluate(X_test, Y_test, batch_size=8,verbose=1)
model.save('car_road_weights1.mdl')

**Comment by AliRaza21918** [comment]
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
conv2d_10 (Conv2D)           (None, 358, 478, 32)      896       
_________________________________________________________________
conv2d_11 (Conv2D)           (None, 356, 476, 32)      9248      
_________________________________________________________________
max_pooling2d_4 (MaxPooling2 (None, 178, 238, 32)      0         
_________________________________________________________________
conv2d_12 (Conv2D)           (None, 176, 236, 16)      4624      
_________________________________________________________________
dropout_7 (Dropout)          (None, 176, 236, 16)      0         
_________________________________________________________________
flatten_4 (Flatten)          (None, 664576)            0         
_________________________________________________________________
dense_7 (Dense)              (None, 128)               85065856  
_________________________________________________________________
dropout_8 (Dropout)          (None, 128)               0         
_________________________________________________________________
dense_8 (Dense)              (None, 172800)            22291200  
=================================================================
Total params: 107,371,824
Trainable params: 107,371,824
Non-trainable params: 0
_________________________________________________________________

**Comment by yanboliang** [comment]
Please check the shape of your ```Y_train```, it should be [None, 172800] according your model definition, but ```Y_train = np_utils.to_categorical(y_train, 3)``` produce the shape of [None, 172800, 3], they are mismatched.
