### ISSUE TITLE
With Keras master code + TF 1.9 , Im  not able to load model ,getting error w_att_2 = Permute((2,1))(Lambda(lambda x: softmax(x, axis=2), NameError: name 'softmax' is not defined

### ISSUE THREAD

**Issue by rajeev0306** [keras-team/keras#10928]
With Keras master code + TF 1.9 , Im able to save model but during load I'm getting error
w_att_2 = Permute((2,1))(Lambda(lambda x: softmax(x, axis=2),
NameError: name 'softmax' is not defined

Here is the code
def soft_attention_alignment(input_1, input_2):
"Align text representation with neural soft attention"
attention = Dot(axes=-1)([input_1, input_2])
w_att_1 = Lambda(lambda x: softmax(x, axis=1),
output_shape=unchanged_shape)(attention)
w_att_2 = Permute((2,1))(Lambda(lambda x: softmax(x, axis=2),
output_shape=unchanged_shape)(attention))
in1_aligned = Dot(axes=1)([w_att_1, input_1])
in2_aligned = Dot(axes=1)([w_att_2, input_2])
return in1_aligned, in2_aligned

def esim(maxlen=MAX_LEN,
lstm_dim=300,
dense_dim=300,
dense_dropout=0.5):

q1 = Input(name='q1',shape=(maxlen,))
q2 = Input(name='q2',shape=(maxlen,))

bn = BatchNormalization(axis=2)
q1_embed = bn(embedding_layer(q1))
q2_embed = bn(embedding_layer(q2))

# Encode
encode = Bidirectional(LSTM(lstm_dim, return_sequences=True))
q1_encoded = encode(q1_embed)
q2_encoded = encode(q2_embed)

# Attention
q1_aligned, q2_aligned = soft_attention_alignment(q1_encoded, q2_encoded)

# Compose
q1_combined = Concatenate()([q1_encoded, q2_aligned, submult(q1_encoded, q2_aligned)])
q2_combined = Concatenate()([q2_encoded, q1_aligned, submult(q2_encoded, q1_aligned)]) 
   
compose = Bidirectional(LSTM(lstm_dim, return_sequences=True))
q1_compare = compose(q1_combined)
q2_compare = compose(q2_combined)

# Aggregate
q1_rep = apply_multiple(q1_compare, [GlobalAvgPool1D(), GlobalMaxPool1D()])
q2_rep = apply_multiple(q2_compare, [GlobalAvgPool1D(), GlobalMaxPool1D()])

# Classifier
merged = Concatenate()([q1_rep, q2_rep])

dense = BatchNormalization()(merged)
dense = Dense(dense_dim, activation='elu')(dense)
dense = BatchNormalization()(dense)
dense = Dropout(dense_dropout)(dense)
dense = Dense(dense_dim, activation='elu')(dense)
dense = BatchNormalization()(dense)
dense = Dropout(dense_dropout)(dense)
out_ = Dense(heuristic_score, activation='softmax')(dense)

model = Model(inputs=[q1, q2], outputs=out_)
model.compile(optimizer=Adam(lr=1e-3), loss='categorical_crossentropy', metrics=['categorical_crossentropy','accuracy'])
return model

**Comment by rajeev0306** [comment]
I'm saving as  model.save('my_model.h5') and loading as model = load_model('my_model.h5') I checked #8612 but could not follow all.  could you pls suggest the code for this using custom_objects and pls also suggest the corresponding code for Activation layer with softmax performing the same functionality

Thanx

**Comment by AndreGuerra123** [comment]
If you want implementation answers, post this in StackOverflow and provide the embedding layer and softmax functions and all the imports as well.
Something like this I think is enough, otherwise, you have to define the functions:
 
w_att_2 = Permute((2,1))(Activation('softmax',output_shape=unchanged_shape)(attention))

PS: Didn't check for shape/axis or test it since I was missing functions on example.

**Comment by rajeev0306** [comment]
thanx. Here is the complete code


embedding_layer = Embedding(MAX_NUM_WORDS,
                            EMBEDDING_DIM,
                            embeddings_initializer=Constant(embedding_matrix),
                            input_length=MAX_SEQUENCE_LENGTH,
                            trainable=False)


MAX_LEN = 235



def unchanged_shape(input_shape):
    "Function for Lambda layer"
    return input_shape


def substract(input_1, input_2):
    "Substract element-wise"
    neg_input_2 = Lambda(lambda x: -x, output_shape=unchanged_shape)(input_2)
    out_ = Add()([input_1, neg_input_2])
    return out_


def submult(input_1, input_2):
    "Get multiplication and subtraction then concatenate results"
    mult = Multiply()([input_1, input_2])
    sub = substract(input_1, input_2)
    out_= Concatenate()([sub, mult])
    return out_


def apply_multiple(input_, layers):
    "Apply layers to input then concatenate result"
    if not len(layers) > 1:
        raise ValueError('Layers list should contain more than 1 layer')
    else:
        agg_ = []
        for layer in layers:
            agg_.append(layer(input_))
        out_ = Concatenate()(agg_)
    return out_


def time_distributed(input_, layers):
    "Apply a list of layers in TimeDistributed mode"
    out_ = []
    node_ = input_
    for layer_ in layers:
        node_ = TimeDistributed(layer_)(node_)
    out_ = node_
    return out_


def soft_attention_alignment(input_1, input_2):
    "Align text representation with neural soft attention"
    attention = Dot(axes=-1)([input_1, input_2])
    w_att_1 = Lambda(lambda x: softmax(x, axis=1),
                     output_shape=unchanged_shape)(attention)
    w_att_2 = Permute((2,1))(Lambda(lambda x: softmax(x, axis=2),
                             output_shape=unchanged_shape)(attention))
    in1_aligned = Dot(axes=1)([w_att_1, input_1])
    in2_aligned = Dot(axes=1)([w_att_2, input_2])
    return in1_aligned, in2_aligned


def esim(maxlen=MAX_LEN, 
         lstm_dim=300, 
         dense_dim=300, 
         dense_dropout=0.5):
             
    
    q1 = Input(name='q1',shape=(maxlen,))
    q2 = Input(name='q2',shape=(maxlen,))
    
    # Embedding
    bn = BatchNormalization(axis=2)
    q1_embed = bn(embedding_layer(q1))
    q2_embed = bn(embedding_layer(q2))

    # Encode
    encode = Bidirectional(LSTM(lstm_dim, return_sequences=True))
    q1_encoded = encode(q1_embed)
    q2_encoded = encode(q2_embed)
    
    # Attention
    q1_aligned, q2_aligned = soft_attention_alignment(q1_encoded, q2_encoded)
    
    # Compose
    q1_combined = Concatenate()([q1_encoded, q2_aligned, submult(q1_encoded, q2_aligned)])
    q2_combined = Concatenate()([q2_encoded, q1_aligned, submult(q2_encoded, q1_aligned)]) 
       
    compose = Bidirectional(LSTM(lstm_dim, return_sequences=True))
    q1_compare = compose(q1_combined)
    q2_compare = compose(q2_combined)
    
    # Aggregate
    q1_rep = apply_multiple(q1_compare, [GlobalAvgPool1D(), GlobalMaxPool1D()])
    q2_rep = apply_multiple(q2_compare, [GlobalAvgPool1D(), GlobalMaxPool1D()])
    
    # Classifier
    merged = Concatenate()([q1_rep, q2_rep])
    
    dense = BatchNormalization()(merged)
    dense = Dense(dense_dim, activation='elu')(dense)
    dense = BatchNormalization()(dense)
    dense = Dropout(dense_dropout)(dense)
    dense = Dense(dense_dim, activation='elu')(dense)
    dense = BatchNormalization()(dense)
    dense = Dropout(dense_dropout)(dense)
    out_ = Dense(heuristic_score, activation='softmax')(dense)
    
    model = Model(inputs=[q1, q2], outputs=out_)
    model.compile(optimizer=Adam(lr=1e-3), loss='categorical_crossentropy', metrics=['categorical_crossentropy','accuracy'])
    return model


model = esim(maxlen=MAX_LEN, 
                   lstm_dim=300, 
                   dense_dim=300, 
                   dense_dropout=0.5)
        
        checkpoint = ModelCheckpoint('../output/'+key+'_'+'modelcheckpoint_esim.h5', monitor='val_loss', save_best_only=True, verbose=1, mode='min')
        #checkpoint = ModelCheckpoint('new1_weights.h5', monitor='val_loss', verbose=1, mode='min')
        model.fit([x_train[:,:235], x_train[:,235:]], \
                  y=y_train_ohc, batch_size=128, epochs=15, \
                  validation_data=([x_valid[:,:235], x_valid[:,235:]], y_valid_ohc),
                  callbacks=[checkpoint,EarlyStopping(monitor='val_loss', patience=4)])
        
        score = model.evaluate([x_test[:,:235],x_test[:,235:]], y_test_ohc, verbose=0)

        
      
        pred = model.predict([x_test[:,:235],x_test[:,235:]],  verbose=0)
        # save model
        model.save('../output/'+key+'_'+'model_esim.h5')
        #load model
        model = load_model('../output/'+key+'_'+'model_esim.h5')

**Comment by rajeev0306** [comment]
can you  suggest the alternate code for this pls

**Comment by rajeev0306** [comment]
question code has been used twice as below
w_att_1 = Lambda(lambda x: softmax(x, axis=1),
output_shape=unchanged_shape)(attention)
w_att_2 = Permute((2,1))(Lambda(lambda x: softmax(x, axis=2),
output_shape=unchanged_shape)(attention))

pls suggest
