### ISSUE TITLE
load_model ValueError: axes don't match array

### ISSUE THREAD

**Issue by phonygene** [keras-team/keras#10949]
I'm studying gan with [keras-gan/wgan-gp](https://github.com/eriklindernoren/Keras-GAN/tree/master/wgan_gp) example with my own dataset. I save models with
`wgan.generator.save('generator.h5')`
`wgan.critic.save('critic.h5')`
and load with
`model = load_model('generator.h5')`
`model = load_model('critic.h5')`

But this only works fine at the fist time.When I save the models again after the second training and run 
`model = load_model('generator.h5')`
`model = load_model('critic.h5')`
again, the error occur ：

> ValueError                                Traceback (most recent call last)
> <ipython-input-13-ffec27061627> in <module>()
> ----> 1 model = load_model('generator.h5')
> 
> D:\keras\engine\saving.py in load_model(filepath, custom_objects, compile)
>     262 
>     263         # set weights
> --> 264         load_weights_from_hdf5_group(f['model_weights'], model.layers)
>     265 
>     266         if compile:
> 
> D:\keras\engine\saving.py in load_weights_from_hdf5_group(f, layers, reshape)
>     914                                                        original_keras_version,
>     915                                                        original_backend,
> --> 916                                                        reshape=reshape)
>     917         if len(weight_values) != len(symbolic_weights):
>     918             raise ValueError('Layer #' + str(k) +
> 
> D:\keras\engine\saving.py in preprocess_weights_for_loading(layer, weights, original_keras_version, original_backend, reshape)
>     555         weights = convert_nested_time_distributed(weights)
>     556     elif layer.__class__.__name__ in ['Model', 'Sequential']:
> --> 557         weights = convert_nested_model(weights)
>     558 
>     559     if original_keras_version == '1':
> 
> D:\keras\engine\saving.py in convert_nested_model(weights)
>     543                     weights=weights[:num_weights],
>     544                     original_keras_version=original_keras_version,
> --> 545                     original_backend=original_backend))
>     546                 weights = weights[num_weights:]
>     547         return new_weights
> 
> D:\keras\engine\saving.py in preprocess_weights_for_loading(layer, weights, original_keras_version, original_backend, reshape)
>     555         weights = convert_nested_time_distributed(weights)
>     556     elif layer.__class__.__name__ in ['Model', 'Sequential']:
> --> 557         weights = convert_nested_model(weights)
>     558 
>     559     if original_keras_version == '1':
> 
> D:\keras\engine\saving.py in convert_nested_model(weights)
>     531                     weights=weights[:num_weights],
>     532                     original_keras_version=original_keras_version,
> --> 533                     original_backend=original_backend))
>     534                 weights = weights[num_weights:]
>     535 
> 
> D:\keras\engine\saving.py in preprocess_weights_for_loading(layer, weights, original_keras_version, original_backend, reshape)
>     673             weights[0] = np.reshape(weights[0], layer_weights_shape)
>     674         elif layer_weights_shape != weights[0].shape:
> --> 675             weights[0] = np.transpose(weights[0], (3, 2, 0, 1))
>     676             if layer.__class__.__name__ == 'ConvLSTM2D':
>     677                 weights[1] = np.transpose(weights[1], (3, 2, 0, 1))
> 
> c:\users\administrator\appdata\local\programs\python\python35\lib\site-packages\numpy\core\fromnumeric.py in transpose(a, axes)
>     596 
>     597     """
> --> 598     return _wrapfunc(a, 'transpose', axes)
>     599 
>     600 
> 
> c:\users\administrator\appdata\local\programs\python\python35\lib\site-packages\numpy\core\fromnumeric.py in _wrapfunc(obj, method, *args, **kwds)
>      49 def _wrapfunc(obj, method, *args, **kwds):
>      50     try:
> ---> 51         return getattr(obj, method)(*args, **kwds)
>      52 
>      53     # An AttributeError occurs if the object does not have
> 
> ValueError: axes don't match array`

I'm using 

`Python     3.5.3`
`Keras        2.2.2`
`h5py         2.8.0`
`tensorflow-gpu 1.9.0`
`keras-contrib     2.0.8`
`Keras-Applications   1.0.4`
`Keras-Preprocessing 1.0.2`

Any advice and suggestions will be appreciated.

**Comment by chestnut111** [comment]
i have the same question

**Comment by NotF404** [comment]
hi, how do u fix this problem

**Comment by chestnut111** [comment]
> hi, how do u fix this problem

i try desnet, xception , resnext,.... all have this pro, it is keras's bug

**Comment by pearsonkyle** [comment]
bump, am having the same bug

**Comment by treder** [comment]
_In case you use the Tensorflow implementation of Keras (tensorflow.keras)_

I get the same error with a modified version of the WGAN GP if I save the model weights in keras's `h5` file format. However, switching to tensorflow format solves the issue for me:

```
model.save_weights('path_to_my_weights', save_format='tf')
model.load_weights('path_to_my_weights')
```



See [tensorflow docu on saving subclassed models](https://www.tensorflow.org/beta/guide/keras/saving_and_serializing#saving_subclassed_models) for more details.

**Comment by sinclairnick** [comment]
For reference, as Crispy13 mentions in his [reply to this SO answer](https://stackoverflow.com/a/57780517/9604722):
The same layers that were frozen when training the model must be frozen before loading the weights. I will experiment with unfreezing these weights after loading the weights. Any ideas why this is happening @fchollet? If I get time I might peep the source and create a PR
