### ISSUE TITLE
[API DESIGN REVIEW] data_format argument for *Pooling1D layers

### ISSUE THREAD

**Issue by hsgkim** [keras-team/keras#10960]
While Convolution1D and other types of 1D layers support specifying the data format of the input data, *Pooling1D layers such as MaxPooling1D do not. This has been brought up as a GitHub issue #10570 and StackOverflow questions ([example](https://stackoverflow.com/questions/51962106/keras-model-with-maxpooling1d-and-channel-first)). I propose a fix that addresses this problem:

https://docs.google.com/document/d/1anjTpeJY5yJCBCha9McYVqv0OxydrlaMBSHAxKttW_c/edit?usp=sharing

I have coded everything already (all changes written in Google Docs; not that big of a change) and tests for the modified layers pass. I would appreciate any comment/feedback regarding the proposal.

**Comment by fchollet** [comment]
That sounds reasonable, you can submit a PR for this change.

**Comment by hsgkim** [comment]
PR merged.
