### ISSUE TITLE
RNN stateful is incompatible with initial_state

### ISSUE THREAD

**Issue by bchu** [keras-team/keras#10965]
If `stateful=True` is being used with an RNN (e.g. LSTM), if you pass in an initial_state (either with `initial_state=` kwarg or as a list of tensors in the argument when calling the layer (`.call()`), the initial state overrides the stored states in the stateful RNN.

**Comment by seandaug** [comment]
This still fails with Tensorflow 2.0.0-rc0.

@gowthamkpr would you mind labeling this issue so this bug might get more visibility?

**Comment by seandaug** [comment]
See https://github.com/tensorflow/tensorflow/issues/32299
