### ISSUE TITLE
This model has never been called, thus its weights have not yet been created, so no summary can be displayed. Build the model first (e.g. by calling it on some test data).

### ISSUE THREAD

**Issue by aligoglos** [keras-team/keras#10970]
this issue occur when i trying to create the following model :
```
 embedding_size = 300
    image_model = Sequential([
        Dense(embedding_size, input_shape=(2048,), activation='relu'),
        RepeatVector(max_len)
    ])
    caption_model = Sequential([
        Embedding(vocab_size, embedding_size, input_length=max_len),
        LSTM(256, return_sequences=True),
        TimeDistributed(Dense(300))
    ])
    final_model = Sequential([
        Concatenate([image_model, caption_model]),
        Bidirectional(LSTM(256, return_sequences=False)),
        Dense(vocab_size),
        Activation('softmax')
    ])
    final_model.compile(loss='categorical_crossentropy', optimizer=RMSprop(), metrics=['accuracy'])
    final_model.summary()
```
Call to model.summary() fails with the error message:
`ValueError: This model has never been called, thus its weights have not yet been created, so no summary can be displayed. Build the model first (e.g. by calling it on some test data).`

**Comment by ss87021456** [comment]
I've also encountered this problem, but after I trained my model and then print out model.summary(), it worked. Therefore, it might be a bug recently in keras I guess.

**Comment by RashmiGHegde** [comment]
I too got the same error.Can u explain the syntax for training...(I am new to this and couldnt decide the parameters )

**Comment by gabrieldemarmiesse** [comment]
Closing as the error message was improved.

**Comment by sthitpragyan** [comment]
hi...how you solved this issue?
I am facing the same error:

from keras.models import Sequential
from keras.layers import merge,Concatenate

model = Sequential()

model.add(Concatenate([image_model, language_model]))
model.add(LSTM(1000, return_sequences=False))
model.add(Dense(vocab_size))
model.add(Activation('softmax'))

model.load_weights("./model_weights.h5")
model.compile(loss='categorical_crossentropy', optimizer=Nadam(), metrics=['accuracy'])
model.summary()

ValueError: This model has never been called, thus its weights have not yet been created, so no summary can be displayed. Build the model first (e.g. by calling it on some test data).
