### ISSUE TITLE
Add a Dense after conv layer

### ISSUE THREAD

**Issue by foreverzzx** [keras-team/keras#11001]
import keras.layers as KL
input_image = KL.Input([None, None, 3], name = 'input_image')
x = KL.Conv2D(64, (3,3), padding='same')(input_image)

after Conv, I want to add a dense as below:
KL.Dense(2)(KL.Flatten()(x))
but there will be an error:
ValueError: The shape of the input to "Flatten" is not fully defined (got (None, None, 64). Make sure to pass a complete "input_shape" or "batch_input_shape" argument to the first layer in your model.

So if I want a model contained conv followed by dense which can accept any size of input, how should I do?

**Comment by mak4alex** [comment]
Flatten layer requires  a shape. you can use GlobalMaxPooling2D instead.
see https://stackoverflow.com/questions/46204569/how-to-handle-variable-sized-input-in-cnn-with-keras for details

you example:
`
import keras
import keras.layers as KL
import keras.backend as K

input_image = KL.Input(shape=(None, None, 3), name = 'input_image')
x = KL.Conv2D(64, (3,3), padding='same')(input_image)
x = KL.GlobalMaxPooling2D()(x)
x = KL.Dense(64)(x)
model = keras.models.Model(inputs=input_image, outputs=x)
model.summary()
`
