### ISSUE TITLE
Make adversarial training work with models.fit_generator()

### ISSUE THREAD

**Issue by veqtor** [keras-team/keras#11018]
### Problem:
Training GAN's in Keras is cumbersome at best, with the need to implement training loops such as:

```
def train(steps=x):
   for i, real_imgs in enumerate(loader.load_batch):
     d_loss = discriminator.train_on_batch([real_imgs, random.random((batch_size,32)], [valid, fake])
     g_loss = generator.train_on_batch(random.random((batch_size,32), valid)
```

Not to mention how terrible it becomes when you also try to log, tensorboard needs custom logic, etc
Furthermore, some GAN's require discriminators to be trained 5x as often as the generator.

### Proposal:
Thus, we need a way to define a "differential" training model, something like this:
`dModel = DifferentialModelWrapper([generator, discriminator], training_ratios=[1,5])`

Now, for training, there are two approaches, one would be a single function:
```
def differentialGenerator(models, batchModel):
  while True:
     if batchModel.name == 'generator':
        yield np.random.random((batch_size, 32)), valid
     if batchModel.name == 'discriminator':
        yield [dataloader.load(batch_size), models[0].predict_on_batch(np.random.random((batch_size, 32))], [valid, fake]
```
or a set of functions passed to fit_generator:
```
dModel.fit_generator([g_generator, d_generator],
             steps_per_epoch=100,
             epochs=100,
             callbacks=[sample_images, tensorboard])
```
Which could actually be nicer, since it doesn't break normal generator specification too much.

This way, by using various tricks, and by also registering on_batch_end callbacks, etc, very advanced training schemes could be created, without too much boiler-plate code.

**Comment by Abhijit-2592** [comment]
@veqtor any updates on this?
