### ISSUE TITLE
self.stateful is not set by params but directly set to False in class Layer.

### ISSUE THREAD

**Issue by thuzhf** [keras-team/keras#11017]
https://github.com/keras-team/keras/blob/ff87f16b2a97fe7c0aedb66449e436a502bbe1a8/keras/engine/base_layer.py#L97

**Comment by jlherren** [comment]
It will be set to `True` in actually stateful sub-classes, what you see here is just the default. One such example would be `LSTM(stateful=True)`.

What is the issue you are experiencing?

**Comment by thuzhf** [comment]
Yes, but why don't you write the default in `def __init__(self, stateful=False)`, otherwise if you want to make `LSTM(stateful=True)` effective, you have to call `super(RNN, self).__init__(**kwargs)` before `self.stateful = stateful` in `class LSTM(Layer)`. What's more, every layer that inherit `Layer` have to do this to make its `stateful` attribute effective.

For example, if I custom a stateful layer like this: 
class MyLayer(Layer): 
    def __init__(self, stateful=True, **kwargs): 
        self.stateful = stateful
        super().__init__(**kwargs)

Then the stateful attribute will be reset to False in the call of `super().__init__(**kwargs)`. This can be easily avoided if you put the default behavior inside `def __init__(self, ...)`. And this can also improve the readability of the code.

**Comment by jlherren** [comment]
Calling `super(...).__init__(...)` should be the first line anyway. Anything else is bad practice. Your proposed approach would allow to do `Dense(stateful=True)` which is silly.

**Comment by thuzhf** [comment]
@jlherren The points are:
1. It counters intuition that the default values of parameters are not placed in the "default position" of python functions. This may bing misleadings for new comers.
2. If you want to disallow `Dense(stateful=True)`, you can easily check this flag when you write the logic of `Dense(...)` function. This is the responsibility of the `Dense(...)` function instead of the users if you really think this is illegal. Thus this is not the concern. 
3. Explicit is better than implicit if you don't want to make your program more prone to bugs and make your program more user-friendly. Actually I searched it on TensorFlow's repository, and found there are many cases when you write other code before `super().__init__()`.
4. Everyone is silly when s/he is making bugs. This is not the point.

Anyway, this may be not an important thing. Never mind.
