### ISSUE TITLE
Documentation doesn't explain how to make a lamda layer with multiple inputs/outputs

### ISSUE THREAD

**Issue by dimargn** [keras-team/keras#11020]
Hi,

I'm trying to save Keras model that contains Lambda layer for resizing image - 

```python
def resize_like(input_tensor, ref_tensor): 
    H, W = ref_tensor.get_shape()[1], ref_tensor.get_shape()[2]
    return K.tf.image.resize_images(input_tensor, [H.value, W.value])

x = _inverted_res_block(x, filters=320, alpha=alpha, stride=1, rate=4,
                                expansion=6, block_id=16, skip_connection=False)  #x is 2D tensor object

b4 = Lambda(resize_like, arguments={'ref_tensor': x})(b4)                 #b4 is 2D tensor object
###some more operation here#####
x = Lambda(resize_like, arguments={'ref_tensor': img_input})(x)           #img_input is 2D tensor object

model = Model(inputs, x, name='model1')
model.save(filePath, overwrite=True)
```

Each run I get one of those four errors - 

1)  File "T:\Conda\Envs\Kitov-38842-DKtv\lib\copy.py", line 297, in _reconstruct
    state = deepcopy(state, memo)
  File "T:\Conda\Envs\Kitov-38842-DKtv\lib\copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "T:\Conda\Envs\Kitov-38842-DKtv\lib\copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "T:\Conda\Envs\Kitov-38842-DKtv\lib\copy.py", line 174, in deepcopy
    rv = reductor(4)
TypeError: can't pickle SwigPyObject objects

  2)File "T:\Conda\Envs\Kitov-38842-DKtv\lib\copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "T:\Conda\Envs\Kitov-38842-DKtv\lib\copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "T:\Conda\Envs\Kitov-38842-DKtv\lib\copy.py", line 174, in deepcopy
    rv = reductor(4)
TypeError: cannot serialize '_io.TextIOWrapper' object

  3)File "T:\Conda\Envs\Kitov-38842-DKtv\lib\copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "T:\Conda\Envs\Kitov-38842-DKtv\lib\copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "T:\Conda\Envs\Kitov-38842-DKtv\lib\copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "T:\Conda\Envs\Kitov-38842-DKtv\lib\copy.py", line 306, in _reconstruct
    y.__dict__.update(state)
AttributeError: 'NoneType' object has no attribute 'update'

  4)File "T:\Conda\Envs\Kitov-38842-DKtv\lib\copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "T:\Conda\Envs\Kitov-38842-DKtv\lib\copy.py", line 223, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "T:\Conda\Envs\Kitov-38842-DKtv\lib\copy.py", line 223, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "T:\Conda\Envs\Kitov-38842-DKtv\lib\copy.py", line 151, in deepcopy
    cls = type(x)
RecursionError: maximum recursion depth exceeded while calling a Python object

How can i save the model with Lambda layer?

The python version in 3.5, Keras is 2.2.2, tensorflow is 1.10.0

Thank You!

**Comment by sidharths** [comment]
i would like to know if you found a solution

**Comment by gabrieldemarmiesse** [comment]
This isn't the right usage of a lambda layer. You shouldn't use the argument `argument` and you should apply the layer on a list of tensors. Also, resize_like should have only one argument, which is a list of tensors.

The fault isn't on you, it's just the documentation which doesn't explain how to make a lambda layer with multiple inputs. PR welcome to update it.

**Comment by saurabhgoel1985** [comment]
Hi,
I am looking start my journey to contribute to ML/AL open source projects. I came across this issue and seems like this can be a good first time issue for me to get the ball rolling. I will read up the contributing guidelines etc today to understand the overall mechanism of contribution. @gabrieldemarmiesse  can you help me fixing this issue. I would want to take up this issue.

**Comment by gabrieldemarmiesse** [comment]
Thanks for that :) what would you need help about?

**Comment by saurabhgoel1985** [comment]
Thanks @gabrieldemarmiesse  for prompt reply, I read on various blogs that one would should have a mentor in the initial phase so as to get the basic understanding about the entire process. So in case you can give me some idea about what changes needs to be done in the documentation. I will do other homework today and get back to you accordingly.

**Comment by gabrieldemarmiesse** [comment]
I think `keras/README.md` and `keras/docs/README. md` have all the info you need about keras PRs. You'll need to learn how to do PRs on github in general too. I don't have much time to give, but I'll be able to answer questions here and there if needed.

**Comment by saurabhgoel1985** [comment]
Sure let me go through these files and will get back to you in case of any specific doubts. Thanks so much. Hopefully I will be able to make my first contribution to keras soon!!

**Comment by sidharths** [comment]
@gabrieldemarmiesse 
Bit confused about your message. resize_like should have first argument as the input tensor as per documentation.  Are you saying the documentation should say that function should have **only** one argument?

**Comment by gabrieldemarmiesse** [comment]
The problem is that the documentation doesn't explain how to deal with multiple input tensors. For this, see https://gist.github.com/akshaychawla/02849170e190fbd7fa9d431450e8d6ef

**Comment by gabrieldemarmiesse** [comment]
If someone could modify the documentation, that would be nice.

**Comment by manasbedmutha98** [comment]
@GabrielBianconi , I would like to try this.

**Comment by saurabhgoel1985** [comment]
@gabrieldemarmiesse  will take up this issue... will let you know in case i face any  issues.

**Comment by gabrieldemarmiesse** [comment]
Any update on this?

**Comment by greed2411** [comment]
Hey, seems like it needs to be updated over here https://github.com/keras-team/keras/blob/master/keras/layers/core.py#L597 where it can be changed to 

> function: The function to be evaluated.
Takes input tensor or list of tensors as first argument.

Is that okay?

**Comment by gabrieldemarmiesse** [comment]
Yes, you need to modify the description of the arguments and a simple example would be nice too since there is already an examples section.  You can add a new example with a simple dummy function.

**Comment by greed2411** [comment]
Just made a simple [gist](https://gist.github.com/greed2411/f1d11d4152ebc8011391a79c9b5edd4c), based on the above one for example. It's just hadamard product. 

as of description, you happen to be okay with this? 
>function: The function to be evaluated.
Takes input tensor or list of tensors as first argument.

If you are okay with the gist, let me know what else to do.

**Comment by gabrieldemarmiesse** [comment]
please do a pull request, it doesn't matter if it's not good at the first try. It's easier to discuss code and modifications when a PR is done (github is made for this).

**Comment by greed2411** [comment]
Since this is fixed, I think it can be closed.

**Comment by gabrieldemarmiesse** [comment]
@greed2411 for future PRs, you can use keywords in your PR description to automatically close the corresponding issue. See https://github.com/keras-team/keras/pull/11514 as an example.

**Comment by greed2411** [comment]
@gabrieldemarmiesse oh I didn't know that. Thanks!
