### ISSUE TITLE
keras.models.clone_model doesn't save trainable flag

### ISSUE THREAD

**Issue by stsykin** [keras-team/keras#11022]
Method [`clone_model()`](https://github.com/keras-team/keras/blob/f6ed1c8712e5b69ea35bcad3bd33d39d0d0b554c/keras/models.py#L226) from `keras.models` doesn't save `trainable`.

What I mean: 
```
>>> model.trainable = False
>>> n_model = clone_model(model)
>>> print(n_model.trainable)
True
```

**Comment by bmiselis** [comment]
I have the same problem. Does anyone know how to solve this?
