### ISSUE TITLE
batch_dot() behavior inconsistent between different backends

### ISSUE THREAD

**Issue by Giszy** [keras-team/keras#11035]
The following code worked well using the backend of tensorflow.
```python
import numpy as np
np.random.seed=0
a=np.random.uniform(0,100,[2,4,3])
b=np.random.uniform(0,100,[2,3,5])
import keras
k=keras.backend
ka=k.variable(a)
kb=k.variable(b)
kc=k.batch_dot(ka, kb, (2,1))
k.eval(kc)
```
But it returned incorrect result using the backend of cntk: kc.shape=[2,4,2,5].

**Comment by farizrahman4u** [comment]
See #11059. There is an edge case missing, which is why its closed. Will be fixing it soon.
