### ISSUE TITLE
`zca_whitening` causes memory leak in `ImageDataGenerator.fit`

### ISSUE THREAD

**Issue by wottpal** [keras-team/keras#11058]
* Keras `2.2.2`
* TensorFlow `1.10.1`
* Python `3.6.6`
* macOS `10.13.6`

I'm trying to generate augmentations of my training data with `zca_whitening` and an `ImageDataGenerator`. But when I try to fit the generator (which is mandatory when using `zca_whitening`) the python process eats more and more memory (100Gb+) until it gets killed by the system.

This small example can cause the leak:

```
import numpy as np
from keras.preprocessing.image import ImageDataGenerator

def cause_leak():
    idg = ImageDataGenerator(zca_whitening = True)
    random_sample = np.random.random((1, 250, 250, 3))
    idg.fit(random_sample)

cause_leak()
```

The terminal output only consists of a warning saying that `featurewise_center` is overwritten when enabling `zca_whitening`. I don't think this is related to the problem but who knows.

**Comment by graffam** [comment]
Would like to bump this. I can't get a single image to be fit with zca_whitening=True :(

**Comment by graffam** [comment]
```
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-12-18f659183331> in <module>()
----> 1 g.fit(X_train[:1])

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras_preprocessing/image.py in fit(self, x, augment, rounds, seed)
   1247                 x, (x.shape[0], x.shape[1] * x.shape[2] * x.shape[3]))
   1248             sigma = np.dot(flat_x.T, flat_x) / flat_x.shape[0]
-> 1249             u, s, _ = scipy.linalg.svd(sigma)
   1250             s_inv = 1. / np.sqrt(s[np.newaxis] + self.zca_epsilon)
   1251             self.principal_components = (u * s_inv).dot(u.T)

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/scipy/linalg/decomp_svd.py in svd(a, full_matrices, compute_uv, overwrite_a, check_finite, lapack_driver)
    127     # perform decomposition
    128     u, s, v, info = gesXd(a1, compute_uv=compute_uv, lwork=lwork,
--> 129                           full_matrices=full_matrices, overwrite_a=overwrite_a)
    130 
    131     if info > 0:

MemoryError: 
```

**Comment by wottpal** [comment]
@gabrieldemarmiesse Thanks for your action on this, do you know a current workaround?

**Comment by wottpal** [comment]
https://github.com/keras-team/keras-preprocessing/issues/55

Should this be closed then?

**Comment by gabrieldemarmiesse** [comment]
Closing this issue as it has been migrated to keras-team/keras-preprocessing#55.
