### ISSUE TITLE
You are trying to load a weight file containing 3 layers into a model with 0 layers.

### ISSUE THREAD

**Issue by erfannariman** [keras-team/keras#11072]
Hi guys, I have the following issue. I tried to check other issues, but none of the solutions helped me. I have the following code:

```
mnist = tf.keras.datasets.mnist # 28x28 resolutie images van handgeschreven nummers 0-9

(x_train, y_train), (x_test, y_test) = mnist.load_data()

x_train = tf.keras.utils.normalize(x_train, axis=1)
x_test = tf.keras.utils.normalize(x_test, axis=1)

model = tf.keras.models.Sequential()

model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(128, activation=tf.nn.relu))
model.add(tf.keras.layers.Dense(128, activation=tf.nn.relu))
model.add(tf.keras.layers.Dense(10, activation=tf.nn.softmax))

model.compile(optimizer='adam',
             loss='sparse_categorical_crossentropy',
             metrics=['accuracy'])

model.fit(x_train, y_train, epochs=3)

model.save('num_read.model')

new_model = tf.keras.models.load_model('num_read.model')
```

**And after the last line I get the following error:**

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-23-491b2789a9b5> in <module>()
----> 1 new_model = tf.keras.models.load_model('num_read.model')

~\Anaconda3\envs\deeplearning\lib\site-packages\tensorflow\python\keras\engine\saving.py in load_model(filepath, custom_objects, compile)
    230 
    231     # set weights
--> 232     load_weights_from_hdf5_group(f['model_weights'], model.layers)
    233 
    234     if compile:

~\Anaconda3\envs\deeplearning\lib\site-packages\tensorflow\python\keras\engine\saving.py in load_weights_from_hdf5_group(f, layers)
    730                      'containing ' + str(len(layer_names)) +
    731                      ' layers into a model with ' + str(len(filtered_layers)) +
--> 732                      ' layers.')
    733 
    734   # We batch weight value assignments in a single backend call

ValueError: You are trying to load a weight file containing 3 layers into a model with 0 layers.

**Comment by jlherren** [comment]
When a model claims to have no weights it usually means it hasn't been built yet. Your first layer doesn't provide the `input_shape` parameter and that's why the reloaded model will be lazily built on first use, which never happens in your code (new feature in Keras 2.2 I believe). Try adding the input shape explicitely.

**Comment by yanboliang** [comment]
@ErfPy Your code works well on my machine with TF 1.10.1.

**Comment by ErfPy** [comment]
@jlherren I tried your suggestion by changing the following with `input_shape`

```python
model = tf.keras.models.Sequential()

model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(128, input_shape=(28,28), activation=tf.nn.relu))
model.add(tf.keras.layers.Dense(128, activation=tf.nn.relu))
model.add(tf.keras.layers.Dense(10, activation=tf.nn.softmax))
```

I added the input_shape 28 by 28 because the images have a resolution of 28x28 (not sure if this though process is correct. 

Still getting the same error.

@yanboliang Yes, it's an error with the newer versions of Keras.

**Comment by jlherren** [comment]
The first layer is `Flatten()` and not `Dense()`. This works for me on TF 1.9.0:

```python
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Flatten(input_shape=x_train.shape[1:]))
model.add(tf.keras.layers.Dense(128, activation=tf.nn.relu))
model.add(tf.keras.layers.Dense(128, activation=tf.nn.relu))
model.add(tf.keras.layers.Dense(10, activation=tf.nn.softmax))
```
