### ISSUE TITLE
Add Gate Linear Unit (GLU) non-linearity

### ISSUE THREAD

**Issue by hadifar** [keras-team/keras#11088]
In [ConvS2S](https://arxiv.org/pdf/1705.03122.pdf) there is a GLU non-linearity. The idea first introduced in [this paper](https://arxiv.org/abs/1612.08083). It also exist on [pytorch codebase](https://pytorch.org/docs/stable/_modules/torch/nn/modules/activation.html). 

I would like to add it into the `advanced_activations`. Do you have any comment on that? 

---
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by tarpalsus** [comment]
Hi, is anyone working on this feature?
