### ISSUE TITLE
How to convert FC-layers to equivalent matrix in keras? 

### ISSUE THREAD

**Issue by csitaula** [keras-team/keras#11109]
I am trying to convert my FC-layers into equivalent matrix of 64*64 matrices for further processing and perform operation. How to do it? Any idea? Thanks

**Comment by HarshVardhanSh** [comment]
how many fully connected layers and whats their dimensions?

**Comment by csitaula** [comment]
I did it by the the help of reshape function defined in keras. I use fc2 layer and reshaped to <?,64,64,1> by the help of reshape function. It worked!
