### ISSUE TITLE
How to do recurrent dropout on cudnn-gated-rnn?

### ISSUE THREAD

**Issue by nlpjoe** [keras-team/keras#11111]
I want to do recurrent dropout on CudnnLSTM or CudnnGRU, can it work now?

**Comment by tedyu** [comment]
Seems tenforflow forum is better place to get answer.

**Comment by jlherren** [comment]
Looking at the code it seems this is not implemented yet.

**Comment by tRosenflanz** [comment]
See discussion here https://github.com/keras-team/keras/issues/8935
