### ISSUE TITLE
Keras Multiprocessing Process Tree Does not Cleanly Terminate on Interrupts

### ISSUE THREAD

**Issue by CMCDragonkai** [keras-team/keras#11126]
I'm using Keras 2.1.4 with tensorflow 1.5.0 with CPU and GPU versions.

I've noticed this several times. But every once and a while, when sending a Ctrl + C or SIGINT, not all processes under the process tree of a Keras process terminates. We are left with a "child process leak". This can be quite annoying, I later have to find the Process Group ID, and then explicitly send `kill -TERM -PGID`, and I think even once I had to send `kill -KILL -PGID`.

My suggestion is to incorporate tests into Keras that tests multiprocessing shutdown behaviour. That is run multiprocessing and test "chaotically" sending SIGINT, SIGTERM, SIGQUIT... etc to the process tree at random points in time and observe the behaviour.

**Comment by gabrieldemarmiesse** [comment]
With a bit of search, it seems that it's not specific to keras. Python multiprocessing doesn't play nicely with ctrl-c and other interrupt signals. But patches exist. Could you submit a patch as a PR for keras?

**Comment by CMCDragonkai** [comment]
I wanted to find out what these orphan processes are actually doing. Running strace on them shows that they are just waiting on futex:

```
fuex(0x21fc1d0, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, 0xffffffff
```

So I then sent `kill -INT 9643` to see what happens:

```
strace: Process 9463 attached
futex(0x21fc1d0, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, 0xffffffff) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGINT {si_signo=SIGINT, si_code=SI_USER, si_pid=28163, si_uid=1000} ---
getpid()                                = 9463
rt_sigreturn({mask=[]})                 = -1 EINTR (Interrupted system call)
futex(0x21fc1d0, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, 0xffffffff
```

It just ignores the signal and returns the futex syscall. The same thing happens with SIGTERM. The only way to kill these orphan processes is SIGKILL.

Finding out why these child processes launched by Keras is running futex while ignoring SIGINT or SIGTERM is probably a good place to start. I know there can be deadlocks and complexities with signal handling when using blocking syscalls as I dealt with them in other applications before.
