### ISSUE TITLE
[Sequence][fit_generator] fit_generator not calling sequence.on_epoch_end() if steps_per_epoch is used

### ISSUE THREAD

**Issue by Wirg** [keras-team/keras#11122]
Hi Keras Team, and thank you for your work.

I am currently using `utils.Sequence` with `fit_generator` and having troubles with `on_epoch_end`.
It seems to me like `on_epoch_end` is called when `__len__` batches have been called and not when the epoch finishes according to `steps_per_epochs` of the `fit_generator`.

I haven't found any issues on that and I find it a bit misleading. :/
Right now, the workarounds I can think of are: 
- forcing the `__len__` to be `steps_per_epochs`
- using a callback to change my Sequence when an epoch end
Is there a better solution or am I doing something wrong?

Here is a snippet to reproduce that.

```python
from keras.utils import Sequence
import numpy as np


class ZerosFirstEpochOnesAfter(Sequence):
    def __init__(self):
        self.is_epoch_0 = True

    def __len__(self):
        return 4

    def on_epoch_end(self):
        print('on_epoch_end')
        self.is_epoch_0 = False

    def __getitem__(self, item):
        if self.is_epoch_0:
            return np.zeros((16, 1)), np.zeros((16,))
        else:
            return np.ones((16, 1)), np.ones((16,))


if __name__ == '__main__':
    from keras import Sequential
    from keras.layers import Dense

    model = Sequential()
    model.add(Dense(1, input_dim=1, activation="softmax"))

    model.compile(optimizer='Adam',
                  loss='binary_crossentropy',
                  metrics=['accuracy']
                  )

    model.fit_generator(ZerosFirstEpochOnesAfter(), epochs=5, steps_per_epoch=1)

```

**Comment by gabrieldemarmiesse** [comment]
It would seem logical that `step_per_epoch` overrides `__len__` when used to know when `on_epoch_end` should be called (the name implies it).

Or we could change `Sequence.on_epoch_end` to `Sequence.on_sequence_end` or `Sequence.on_loop_finished`?

But I would say that often, an epoch is a full loop over the dataset so your case can maybe be considered as an edge case?

I don't know, really. And since this is an API matter, maybe we should get the opinion of @fchollet .

**Comment by Wirg** [comment]
Hi Gabriel and thank you for your answer.

Changing the name could be a good thing but I guess it would impact a lot of people.
I guess the short-term answer would be to add a hint about this in the docs.

To give you some hint about my use case which is not that edgy.
I am working on siamese-like architectures so my dataset size is at least around n^2 (number of pairs I can generate) for n single elements in my dataset. 
I don't want to train through all of those:
- it takes a lot of time and I love to keep my callbacks frequent
- it's probably not worth it as a lot of those pairs are not that worth anyway.

I am willing to use `on_epoch_end` to change the behavior of my sampler for different reasons (mainly preprocessing of the data and choosing the best pairs).

I guess the best solution fix for me right now is to set the `__len__` of the sampler according to the number of steps I actually intend to do.
In a way, it's probably semantically right.
