### ISSUE TITLE
Using tensorflow.py_func in keras loss function !

### ISSUE THREAD

**Issue by ayoubBouziane** [keras-team/keras#11137]
Hi ,

I am trying to use a python function 'IoU' as a keras loss function using tensorflow.py_func ... as follows:

 def loss_fn(label, pred):
    return tensorflow.py_func(IoU, (label, pred), tf.float64)

But unfortunately i got the following error : TypeError: 'NoneType' object cannot be interpreted as an integer.

I am using Keras 2.2.2 & tensorflow 1.10.0.

can you help me please to overcome this issue ??

Thanks in advance.

**Comment by tedyu** [comment]
Can you post the full trace of the error ?
