### ISSUE TITLE
Set weights manually

### ISSUE THREAD

**Issue by mozzielol** [keras-team/keras#11143]
For some reason, I want to set the weights manually. After calculating the weights by gradient, I print the type of the weights

`<class 'tensorflow.python.framework.ops.Tensor'>`

I  cannot set the weight by model.set_weights because of the error:
`TypeError: object of type 'Tensor' has no len()`

I found it in the doc that, set_weights can only set the value with numpy array. So I want to conver the weights to numpy array by K.eval() and got the error:
`InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'dense_1_sample_weights' with dtype float and shape [?]
 [[Node: dense_1_sample_weights = Placeholder[dtype=DT_FLOAT, shape=[?], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]`

After testing, I found that I can use `K.eval` only on the weights but not the gradients. If I do `K.eval(gradients)`, it throws the same error as above. I think that because of that gradients only accessible when there are loss and weights. But in my approach, I need to compute the gradients in several batches. I'm trying to update the gradients in the batch end but it does not change. `set_value`   does not work with tensor as well. Could anyone tell me how can I set the weights with a tensor, or how to convert the gradients into numpy array? Thanks in advance.

**Comment by gabrieldemarmiesse** [comment]
`layer.get_weights()` and `layer.set_weights()` use numpy arrays. Those functions are documented somewhere in the docs.

**Comment by mozzielol** [comment]
> `layer.get_weights()` and `layer.set_weights()` use numpy arrays. Those functions are documented somewhere in the docs.

Thanks for your reply. I've tried `layers.set_weights()`. Unfortunately, the result I produced is a tensor instead of a numpy array. And I cannot convert it to numpy array by K.eval() because of the gradients included. It throws an error as I mentioned in my previous comments.

**Comment by gabrieldemarmiesse** [comment]
I've never tried to manipulate the gradients directly. Sorry, I won't be able to help you with this.

**Comment by mozzielol** [comment]
> I've never tried to manipulate the gradients directly. Sorry, I won't be able to help you with this.

Thank you anyway.

**Comment by tomastheod-ITI** [comment]
@mozzielol Try using `K.get_value(x)`. It returns a numpy array representation of the given tensor x.

**Comment by mozzielol** [comment]
> @mozzielol Try using `K.get_value(x)`. It returns a numpy array representation of the given tensor x.

Thanks for your reply. It still gets the same error.  I'm not sure if there is anything wrong with the way I return gradients.

`def get_gradients(model):
    '''
    Return the gradient of every trainable weight in model
    '''
    weights = [tensor for tensor in model.trainable_weights]
    optimizer = model.optimizer

    return optimizer.get_gradients(model.total_loss, weights)
`

This is the function that I get gradients. I'm not sure about this. Could you give me some advice? Thanks.

**Comment by programmin1** [comment]
What do you mean by, you can't edit it? I made a and/or networks for fun earlier and I found that you can actually reload the hdf file back into keras after editing it.
The NN generator:

```

# import the necessary packages
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Activation
from keras.optimizers import SGD
from keras.layers import Dense
from keras.utils import np_utils
from imutils import paths
import numpy as np
import argparse
import cv2
import os

# construct the argument parse and parse the arguments
ap = argparse.ArgumentParser()
ap.add_argument("-m", "--model", required=True,
	help="path to output model file")
args = vars(ap.parse_args())

data = [[0,0],[0,1],[1,0],[1,1]]
labels = [0,0,0,1]

# encode the labels, converting them from strings to integers
le = LabelEncoder()
labels = le.fit_transform(labels)

# scale the input image pixels to the range [0, 1], then transform
# the labels into vectors in the range [0, num_classes] -- this
# generates a vector for each label where the index of the label
# is set to `1` and all other entries to `0`
data = np.array(data)
labels = np_utils.to_categorical(labels, 2)

# partition the data into training and testing splits, using 75%
# of the data for training and the remaining 25% for testing
print("[INFO] constructing training/testing split...")
(trainData, testData, trainLabels, testLabels) = train_test_split(
	data, labels, test_size=0.0, random_state=42)
print('train')
print(trainData)
print(trainLabels)
print('test')
print(testData) #oopse, empty...
print(testLabels)
testData = trainData
testLabels = trainLabels

# define the architecture of the network
model = Sequential()
model.add(Dense(2, input_dim=2, kernel_initializer="uniform",
	activation="relu"))
model.add(Activation("softmax"))

# train the model using SGD
print("[INFO] compiling model...")
sgd = SGD(lr=0.35)
model.compile(loss="binary_crossentropy", optimizer=sgd,
	metrics=["accuracy"])
print(model.fit.__doc__)
model.fit(trainData, trainLabels, epochs=50, batch_size=128,
	verbose=False)

print(model.predict(np.array([[0,1]])))
print('Should be [1,0]')#false
print(model.predict(np.array([[1,0]])))
print('Should be [1,0]')#false
print(model.predict(np.array([[0,0]])))
print('Should be [1,0]')#false
print(model.predict(np.array([[1,1]])))
print('Should be [0,1] true.')
# show the accuracy on the testing set
print("[INFO] evaluating on testing set...")
(loss, accuracy) = model.evaluate(testData, testLabels,
	batch_size=128, verbose=1)
print("[INFO] loss={:.4f}, accuracy: {:.4f}%".format(loss,
	accuracy * 100))

# dump the network architecture and weights to file
print("[INFO] dumping architecture and weights to file...")
model.save(args["model"])

```



Now you can load up the model later, say you ran it with output set to 'outputand' file in the Python terminal:

```
import numpy as np
from keras.models import load_model
model = load_model('outputand')
print(model.save.__doc__) # a handy howto
model.predict((np.array([[1,1]])))
```

**Comment by choltz95** [comment]
@mozzielol did you figure this out? I am trying to do something similar...I can not convert my weight tensor to a numpy array either since I want fine control over the gradient flow. Have you tried setting the kernel_initializer parameter?
