### ISSUE TITLE
Predicting a conv1d model in keras that takes index of words in a sentence as input

### ISSUE THREAD

**Issue by sushiboo** [keras-team/keras#11168]
So I have prepared a sentiment analysis model and I am trying to predict it with new input but I am faced with an error:

```
data = getFile('Cleaned Data.xlsx')

data['Description'] = data['Description'].apply(lambda x: x.lower())
data['Description'] = data['Description'].apply((lambda x: re.sub('[^a-zA-z0-9\s]','',x)))

print(data[ data['Classification'] == 1].size)
print(data[ data['Classification'] == 0].size)

for idx,row in data.iterrows():
    row[1] = row[1].replace('rt',' ')

tokenizer = Tokenizer(split=' ')
tokenizer.fit_on_texts(data['Description'].values)

#vectorizer = CountVectorizer()
#X = vectorizer.fit_transform(jobSpec['Description']).toarray()

X = tokenizer.texts_to_sequences(data['Description'].values)
X = pad_sequences(X, maxlen=100, value=0.)

display(X.shape)

vocab_size = len(tokenizer.word_index) + 1
max_length = max([len(s.split()) for s in data['Description']])

Y = pd.get_dummies(data['Classification']).values
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.33, random_state = 42)


tokens_docs = [doc.split(" ") for doc in data['Description'].values]
all_tokens = itertools.chain.from_iterable(tokens_docs)
my_dict = {token: token if token.isdigit() else idx for idx, token in enumerate(set(all_tokens))}

print(X_train.shape,Y_train.shape)
print(X_test.shape,Y_test.shape)

raw_embedding = load_embedding('glove.6B.100d.txt')

embedding_vectors= get_weight_matrix(raw_embedding, tokenizer.word_index)
embedding_layer = Embedding(vocab_size, 100, weights=[embedding_vectors], input_length = X.shape[1], trainable=False, name="Embeddings")

display(embedding_vectors.shape)

# define model
sequence_input = Input(shape=(100,), dtype='int32')
embedded_sequences = embedding_layer(sequence_input)
x = Conv1D(128, 5, activation='relu')(embedded_sequences)
x = MaxPooling1D(2)(x)
x = Conv1D(128, 5, activation='relu')(x)
x = MaxPooling1D(2)(x)
x = Conv1D(128, 5, activation='relu')(x)
x = MaxPooling1D(18)(x)
x = Flatten()(x)
x = Dense(128, activation='relu')(x)
preds = Dense(2, activation='softmax')(x)
model = Model(sequence_input, preds)
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['acc'])


# input for which we need the embedding
input_str = "the company our client is a renowned civil actor who have consistently and safely delivered major civil infrastructure  ts across a"

# build index based on our `vocabulary`
word_to_idx = OrderedDict({w:all_tokens.index(w) for w in input_str.split() if w in all_tokens})

ynew = model.predict([1],[3],[5],[7])
display(ynew)
```
when I try to predict this model with new input:

```
ynew = model.predict([1],[3],[5],[7])
display(ynew)
```
it gives me an error message:

`ValueError: Error when checking input: expected input_29 to have shape (100,) but got array with shape (1,)`
I have tried to change the shapes of the model to None and 1 but it gives me other new errors. I am quite new to the machine learning stuff so really not sure how to fix this one.

Any help will be appreciated

**Comment by bileschi** [comment]
Your shape error is because your model is expecting an input of size 100.  You should pass in a tensor of size [batch_size, 100]

**Comment by sushiboo** [comment]
Thank you. I managed to fix it by adding paddings to the input data. 

```
text = ['Construction workers needed for this company who has qualifications ']
#vectorizing the tweet by the pre-fitted tokenizer instance
text = tokenizer.texts_to_sequences(text)

text = pad_sequences(twt, maxlen=100, dtype='int32', value=0)
print(text)
sentiment = model.predict(text, batch_size=1)[0]
display(sentiment)
```

This solved my problem. I was wondering what you meant by changing the input size to 100 but I see that padding it with the 0 allows me to make up for the empty sequence values.

**Comment by sushiboo** [comment]
I have a question regarding this input on android now I will be using this on Android. So, let's say I have an input of some text sequences of a sentence but some words in the sentence are not in the sequence dictionary that I saved in a JSON format from this model's whole text data. So, for the words that are not in the dictionary, would I need to add a 0 in their place or can I just remove that word from the sequence and add only the sequence ID of the words that exist in the dictionary then filling the rest with 0?

**Comment by bileschi** [comment]
The typical solution is to use an "Out of Vocabulary" (OOV) integer.  Sometimes developers will use exactly one integer for their OOV tokens.  Other times developers will use a hash function to map words to one of several "OOV buckets"

**Comment by sushiboo** [comment]
> The typical solution is to use an "Out of Vocabulary" (OOV) integer. Sometimes developers will use exactly one integer for their OOV tokens. Other times developers will use a hash function to map words to one of several "OOV buckets"

Okay, for now, I will use 0 for all of my Out of vocabulary Tokens. Thank you for your assistance.
