### ISSUE TITLE
convolution from 64 to 32

### ISSUE THREAD

**Issue by feiwu77777** [keras-team/keras#11165]
hello everyone,

I'm wondering how does the CNN handle a convolution of 64 filtered images into 32 filtered images.
Here is an example:

input_img = Input( shape = (64, 64, 1))
x = Conv2D(64 , (3,3) , activation = '...' , padding = '...' , name = 'layer1')(input_img)
x = Conv2D(32 , (3,3) , activation = '...' , padding = '...' , name = 'layer2')(x)

So you give the network an 64*64 grayscale image and the first layer will apply 64 filters to this image and output 64 differents versions of the input image. But then in the second layer it should output 32 filtered images, so does layer2 apply 64 times the same filter on the ouput of layer1 and select 32 filtered images at random ?

**Comment by kgrm** [comment]
Each output channel of an channel convolutional layer is basically generated through a weighted sum of N convolutional filters of every input channels. So you can think of a Conv2D layer with 64 input channels and 32 output channels as consisting of 64 \* 32 2d convolutional filters.
