### ISSUE TITLE
No documentation available for which version of Keras is compatible with which version of Tensorflow, Theano, CNTK

### ISSUE THREAD

**Issue by abdelrahmanmohamed** [keras-team/keras#11176]
No Documentation Available for which version of Keras Compatible with Tensorflow, Theano, CNTK

**Comment by gabrieldemarmiesse** [comment]
You are totally right. Currently your best bet is to dig it from the travis.yml. https://github.com/keras-team/keras/blob/master/.travis.yml

**Comment by gabrieldemarmiesse** [comment]
I think this issue is also coupled with https://github.com/keras-team/keras/projects/1#card-2095483 if someone wants to take a stab at it.

**Comment by NeelShah18** [comment]
I finish about tensorflow compatibility list with keras and doing for cntk. I will submit the pull request today for tensorflow and keras compatibility documentation.
