### ISSUE TITLE
question about imdb.load_data(num_words=max_features)

### ISSUE THREAD

**Issue by kimcho30** [keras-team/keras#11178]
imdb.load_data(num_words=max_features)
Excuse me, could anybody tell me what the "num_words" in this means?
Thank you !

**Comment by tedyu** [comment]
Please take a look at the doc for load_data, starting at line 21 in:

./keras/datasets/imdb.py

**Comment by tedyu** [comment]
See also example on page 187 of Francois' book.

**Comment by BhargavB05** [comment]
![Screenshot (42)](https://user-images.githubusercontent.com/40090417/56706834-0fa5df80-6734-11e9-86f0-faf912ac655e.png)

value error while loading the data
