### ISSUE TITLE
print_tensor bug on CNTK ?

### ISSUE THREAD

**Issue by christopher5106** [keras-team/keras#11173]
I'm not sure to understand how the tensor is printed in 
https://github.com/keras-team/keras/blob/master/keras/backend/cntk_backend.py#L2139-L2143

since the underlying function is lambda x : print(message) 
which does not cite x....

Thank you

**Comment by gabrieldemarmiesse** [comment]
x is used at line 2141. I agree that it's a poor choice to use also x as the lambda argument.

**Comment by christopher5106** [comment]
So you say that x is placed into self.execute(argument) 
This will execute lambda z: print(message) which will not print the argument but message which is "" by default

**Comment by tedyu** [comment]
Looks like the tensor is not printed, only the message is printed.

**Comment by gabrieldemarmiesse** [comment]
My apologies. You are right. And we don't have currently a test for the correctness of `K.print_tensor()` in https://github.com/keras-team/keras/blob/master/tests/keras/backend/backend_test.py . I think this is the main issue. I'll change the label of this issue. Do you think you would be able to do a PR for this?

**Comment by gabrieldemarmiesse** [comment]
We should be able to check that the values of the tensor are really printed in our test suite.

**Comment by christopher5106** [comment]
I have no idea how to print a tensor, do you know how to convert it to get its value in the middle of CNTK graph ?

**Comment by gabrieldemarmiesse** [comment]
I'm not an expert at CNTK, and with a bit of search, I can't find an easy way to print the values of a tensor. Maybe @souptc or @yanboliang can help with those? Or at least tell us if they know it's not feasable.
