### ISSUE TITLE
gpus training using keras with tensorflow backend on separate machines

### ISSUE THREAD

**Issue by karolszk** [keras-team/keras#11185]
Hello,

I am trying to use Keras with TF to train RNN in the following distributed cluster configuration:

 1) worker 1st machine with 2 NVIDIA GPUs
 2) worker 2nd machine with 2 NVIDIA GPUs
 3) parameter server 3rd machine with CPU

it will be possible in the future use keras.multi_gpu_model with such configuration? 

Currently I ve got the following error:

  File "tf_gpu_on_multiple_nodes.py", line 122, in rnn_train
    model=multi_gpu_model(model, gpus=4)
  File "/net/software/local/python/3.6.5/lib/python3.6/site-packages/keras/utils/multi_gpu_utils.py", line 180, in multi_gpu_model
    available_devices))
ValueError: To call `multi_gpu_model` with `gpus=4`, we expect the following devices to be available: ['/cpu:0', '/gpu:0', '/gpu:1', '/gpu:2', '/gpu:3']. However this machine only has: ['/cpu:0', '/gpu:0', '/gpu:1', '/cpu:0', '/gpu:0', '/gpu:1', '/cpu:0']. Try reducing `gpus`.

Is now Keras only supports multiple gpus on single machine? 

Thank you and regards, Karol

**Comment by gabrieldemarmiesse** [comment]
Keras does support multiple GPUs on a single machine. I don't think it supports distributed training among multiple machines. You can always define layers with keras in Tensorflow for sure, but I don't think that the `fit` and `fit_generator` will work.

**Comment by karolszk** [comment]
Thank you. But I am wondering are they any plans for development it in keras?

**Comment by gabrieldemarmiesse** [comment]
That I don't know. We can only suggest. @fchollet is the one deciding which features can go in the project. I can add a feature request label for visibility and upvotes.
