### ISSUE TITLE
batch_size dangerous default

### ISSUE THREAD

**Issue by pannous** [keras-team/keras#11194]
Please give a warning when using default `batch_size` parameter in `model.predict`.

I just spent an hour debugging a magic number '32' in the model, which did not occur anywhere in my code.  
After successfully training, the following failed on the *same* input sample:  
`model.predict(sample)` 

finally found the culprit:  
https://keras.io/models/model/#predict  
batch_size: Integer. If unspecified, it will default to 32.

`predict` should either use the shape of the sample as batch_size, or the same one as the model in training or use '1' as default (usually we just want to predict one item anyways), but don't fallback to an arbitrary default value without a warning please.

**Comment by gabrieldemarmiesse** [comment]
Could you please give a sample script and the stacktrace to reproduce the error? Thank you.
