### ISSUE TITLE
keras-applications required==1.0.4 rather than >=

### ISSUE THREAD

**Issue by whyboris** [keras-team/keras#11193]
This may be intentional, but the Keras `setup.py` install requires `'keras_applications==1.0.4',`

see: https://github.com/keras-team/keras/blob/master/setup.py#L40

`keras-applications` version 1.0.5 is out (and is auto-installed when you install _tensorflow==1.11.0rc0_ because _it_ requires >=1.0.5).

The issue appears because I'm installing _keras_ and _tensorflow_ with `pipenv` which can't create a lock file because of incompatible requirements:
```
Could not find a version that matches keras-applications==1.0.4,>=1.0.5
```

This is not a big problem -- everything works on my end, but I thought it might not have been intentional to make the requirement `==` rather than `>=`

**Comment by tedyu** [comment]
It seems >= makes sense.

**Comment by abhi-jha** [comment]
Has this fix been made? I am getting the same issue as the OP.

**Comment by tedyu** [comment]
@whyboris 
Mind sending out a PR ?

I can do it if you're busy.

Thanks

**Comment by chasebrignac** [comment]
I put in a PR real quick because I hit this issue today https://github.com/keras-team/keras/pull/11238

**Comment by darophi** [comment]
I hope that a quick minor release is issued.

**Comment by Overdrivr** [comment]
I'm suddenly getting this error with tensorflow 1.10.0 and keras 2.2.2. I cannot update my Pipfile. Has anyone been updating packages for those versions ?

```
Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
Could not find a version that matches keras-applications==1.0.4,>=1.0.6
Tried: 1.0.0, 1.0.0, 1.0.1, 1.0.1, 1.0.2, 1.0.2, 1.0.4, 1.0.4, 1.0.5, 1.0.5, 1.0.6, 1.0.6
There are incompatible versions in the resolved dependencies.
```

**Comment by abhi-jha** [comment]
@Overdrivr Were you able to generate the lock file?

**Comment by Overdrivr** [comment]
I was, by running `pipenv lock --clear` if I remember correctly.
However, something must have change remotely, maybe in the pypi repositories, because I suddenly faced this issue on three different machines

**Comment by gabrieldemarmiesse** [comment]
Closing this issue since it was solved.
