### ISSUE TITLE
Can't use multiple GPUs with GANs

### ISSUE THREAD

**Issue by emilwallner** [keras-team/keras#11204]
**Test:** wrap the combined generator and discriminator in the multiple_gpu_model API
**Syntax:** `combined = multi_gpu_model(combined)`
**Reproduce issue:** https://gist.github.com/emilwallner/f2c411b83c499c1834fd1be6646f7389
**Error:** ValueError: The name "model_1" is used 2 times in the model. All layer names should be unique.

**Comment by yanboliang** [comment]
@emilwallner You code works well on my node with 2 GPUs. Can you share the whole error stack?

**Comment by emilwallner** [comment]
@yanboliang My bad, it works when I use the latest master.
