### ISSUE TITLE
Trasnfer Learning(VGG16) using MNIST

### ISSUE THREAD

**Issue by hasibzunair** [keras-team/keras#11208]
I want to perform transfer learning using VGG16.
Facing issue with the input shape in vgg which is (48,48,3). How do i change the dimensions so that i can fed it in the vgg model?

**Comment by hasibzunair** [comment]
Solved! 

```rgb_list_test = []
#convert X_train data to 48x48 rgb values
for i in range(len(X_test)):
    rgb = to_rgb(X_test[i])
    rgb_list_test.append(rgb)
    #print(rgb.shape)
rgb_arr_test = np.stack([rgb_list_test],axis=4)
rgb_arr_to_3d_test = np.squeeze(rgb_arr_test, axis=4)
print(rgb_arr_to_3d_test.shape)
print(type(rgb_arr_to_3d_test))

```

**Comment by hasibzunair** [comment]
@gabrieldemarmiesse is implementing transfer learning using mnist worth a PR? Wrote a small pre processing program before feeding it to the pre-trained model.

**Comment by gabrieldemarmiesse** [comment]
I don't think a PR is necessary, thanks for the proposition.
For future readers, you can put you your code in this issue. Maybe that
will help others :)

**Comment by hasibzunair** [comment]
Code snippet for pre processing mnist data to feed in vgg16

```
#convert X_train data to 48x48 rgb values
for i in range(len(X_test)):
    rgb = to_rgb(X_test[i])
    rgb_list_test.append(rgb)
    #print(rgb.shape)
rgb_arr_test = np.stack([rgb_list_test],axis=4)
rgb_arr_to_3d_test = np.squeeze(rgb_arr_test, axis=4)
print(rgb_arr_to_3d_test.shape)
print(type(rgb_arr_to_3d_test))

```

**Comment by hasibzunair** [comment]
@gabrieldemarmiesse tested VGG16 with different configurations on MNSIT with some fine tuning and pre processing, are these test helpful enough to be added in [ keras/exampls](https://github.com/keras-team/keras/tree/master/examples)

**Comment by hasibzunair** [comment]
@gabrieldemarmiesse, implemented grayscale to multi-channel conversion(28, 28) -->> (28, 28, 3) and fed it to a VGG16 pre-trained model, worked(~99.87% on MNIST)! Hope it's useful. Requesting a review.

**Comment by hasibzunair** [comment]
Found interest on this [here](https://forums.fast.ai/t/using-vgg-with-greyscale-images/854/9)

**Comment by gabrieldemarmiesse** [comment]
Thanks for posting your work here. We try not to bloat too much the examples directory (it's already pretty full). MNIST and transfer learning are already well documented in keras. Putting your work on a personal repo is a better approach in my opinion.

**Comment by hasibzunair** [comment]
Alright, I will do that then. Thanks for the suggestion.

**Comment by lenalana** [comment]
@hasibzunair , I have question on using SRGAN with grayscale images, how can I contact with you please?
