### ISSUE TITLE
load_model() couldn't work on multipe same Custom layers

### ISSUE THREAD

**Issue by King-Of-Knights** [keras-team/keras#11210]
Like what is described in [#6900](https://github.com/keras-team/keras/issues/6900), 
The code  `load_model()` for a single custom layer works well:
`model = load_model('Network.hdf5', custom_objects= {'Myclass': Myclass})`

but not works for the Model which contains multipe same Custom layers, like AlexNet, which contains
3 LRN, and LRN is my custom layer.

 Since I will get something like that:

 ```
File "D:/AlexNet.py", line 114, in <module>
    model = load_model('AlexNet.h5', custom_objects= {'LRN': LRN})
  File "E:\Anaconda3\lib\site-packages\keras\engine\saving.py", line 260, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "E:\Anaconda3\lib\site-packages\keras\engine\saving.py", line 334, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "E:\Anaconda3\lib\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "E:\Anaconda3\lib\site-packages\keras\utils\generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "E:\Anaconda3\lib\site-packages\keras\engine\sequential.py", line 293, in from_config
    model.add(layer)
  File "E:\Anaconda3\lib\site-packages\keras\engine\sequential.py", line 193, in add
    self.build()
  File "E:\Anaconda3\lib\site-packages\keras\engine\sequential.py", line 233, in build
    name=self.name)
  File "E:\Anaconda3\lib\site-packages\keras\engine\network.py", line 237, in _init_graph_network
    self.inputs, self.outputs)
  File "E:\Anaconda3\lib\site-packages\keras\engine\network.py", line 1442, in _map_graph_network
    ' times in the model. 
ValueError: The name "LRN2D" is used 2 times in the model. All layer names should be unique.
```

Which is caused by multipe same Custom layers
Since I am working on network prune experiment, it is a little complicated  to use `model.load_weights()`,
because the model architecture is always changing. 
Any idea about this? Appreciation in advance!

**Comment by King-Of-Knights** [comment]
@gabrieldemarmiesse 
After I did some research, I found something may potentially cause this issue in: 
[keras/keras/engine/saving.py](https://github.com/keras-team/keras/blob/4fc8cf281e0d5fa248701708c03d5075f4914bcd/keras/engine/saving.py):
    ```
def convert_custom_objects(obj):
        """Handles custom object lookup.
        # Arguments
            obj: object, dict, or list.
        # Returns
            The same structure, where occurrences
                of a custom object name have been replaced
                with the custom object.
        """
        if isinstance(obj, list):
            deserialized = []
            for value in obj:
                deserialized.append(convert_custom_objects(value))
            return deserialized
        if isinstance(obj, dict):
            deserialized = {}
            for key, value in obj.items():
                deserialized[key] = convert_custom_objects(value)
            return deserialized
        if obj in custom_objects:
            return custom_objects[obj]
        return obj
```
"convert_custom_objects" returns "The same structure, where occurrences of a custom object name have been replaced with the custom object", it means  no matter how we name our custom layer, such as 'Custom_layer1',  'Custom_layer2' or  'Custom_layer3', it will just give the name 'Custom_layer'. Maybe we should load our custom_layer by the our custom layer name not the layer name. Any idea about this? Thanks!

**Comment by gabrieldemarmiesse** [comment]
Tagging @farizrahman4u as he worked on models saving/loading recently and must know the best course of action about this.

**Comment by farizrahman4u** [comment]
This is probably an issue with the Custom Layer. Make sure that the Custom Layer class is not explicitly setting the `.name` attribute. 

For e.g, the following code works:

```python
from keras.layers import *
from keras.models import *

class CustomLayer(Layer):
    def __init__(self, dim=10, **kwargs):
        self.dim = dim
        super(CustomLayer, self).__init__(**kwargs)

a = Input((2,))
b = CustomLayer(3)(a)
c = CustomLayer(4')(b)
model = Model(a, c)

model.save('test.h5')
model2 = load_model('test.h5')
```

This will raise `ValueError: The name "Custom_Layer" is used 2 times in the model. All layer names should be unique.`:

```python
from keras.layers import *
from keras.models import *

class CustomLayer(Layer):
    def __init__(self, dim=10, **kwargs):
        self.dim = dim
        super(CustomLayer, self).__init__(**kwargs)
        self.name = 'CustomLayer'   ### DONT DO THIS!

a = Input((2,))
b = CustomLayer(3)(a)
c = CustomLayer(4')(b)
model = Model(a, c)

model.save('test.h5')
model2 = load_model('test.h5')
```

```

**Comment by King-Of-Knights** [comment]
@farizrahman4u Thanks, I will try and report back!

**Comment by King-Of-Knights** [comment]
@farizrahman4u Thanks for your reply! Your code below needs to be modified :
```
from keras.layers import *
from keras.models import *

class CustomLayer(Layer):
    def __init__(self, dim=10, **kwargs):
        self.dim = dim
        super(CustomLayer, self).__init__(**kwargs)

a = Input((2,))
b = CustomLayer(3)(a)
c = CustomLayer(4)(b)
model = Model(a, c)

model.save('test.h5')
model2 = load_model('test.h5', custom_objects={'CustomLayer': CustomLayer})
```
And this works. inspired by your reply ,in general, you need to remove `"name": self.__class__.__name__ `  in your custom layer if you want to use `load_model`:
```
def get_config(self):
    return {"name": self.__class__.__name__,  # Remove it
            "alpha": self.alpha,
            "k": self.k,
            "beta": self.beta,
            "n": self.n}
```
But you will lose your right to name your CustomLayer. I believe it is still a bug where we should throw our eyes on.

**Comment by farizrahman4u** [comment]
Note that the recommend way to write `get_config()` is by first calling the base class's `get_config()` and the adding items to it:

```python
def get_config(self):
   config = super(CustomLayer, self).get_config()
    config['alpha'] = self.alpha
    config['k'] = self.k
    return config
```

**Comment by King-Of-Knights** [comment]
@farizrahman4u thanks!
