### ISSUE TITLE
Python 2 and 3 get_layer differences.

### ISSUE THREAD

**Issue by balbok0** [keras-team/keras#11212]
Hi, 
I was trying to call a get_layer on a given index of it, and while it worked like charm in python 3, there was something with with topology.InputLayer layer in python2. I'm running keras on top of tensorflow in both cases, however in case on python3 it's on cpu (with AVX and SSE4.2), and in case of python2 on gpu (I'm not sure with what flags tensorflow was build, since it's on a server).
I believe output should be the same, and not depending on version of python/tensorflow used.

Code to reproduce:
```
from keras.models import Sequential
from keras.layers import Conv2D, MaxPool2D, Dense, Dropout, Activation, Flatten

m = Sequential()
m.add(Activation('linear', input_shape=[25, 25, 1]))
m.add(Conv2D(16, (3, 3), padding='same'))
m.add(MaxPool2D())
m.add(Flatten())
m.add(Dense(20))
m.add(Dropout(0.5))
m.add(Dense(2))
for i in range(len(m.layers)):
        print(m.get_layer(index=i))
```

Output in python3 (as expected):
```
<keras.layers.core.Activation object at 0x7f8bd37b8c18>
<keras.layers.convolutional.Conv2D object at 0x7f8ba30acd68>
<keras.layers.pooling.MaxPooling2D object at 0x7f8ba30acc50>
<keras.layers.core.Flatten object at 0x7f8ba30acbe0>
<keras.layers.core.Dense object at 0x7f8ba30d3748>
<keras.layers.core.Dropout object at 0x7f8ba3069f60>
<keras.layers.core.Dense object at 0x7f8ba3069e10>
```

Output in python2:
```
<keras.engine.topology.InputLayer object at 0x7fbcac623850>
<keras.layers.core.Activation object at 0x7fbcac623810>
<keras.layers.convolutional.Conv2D object at 0x7fbcac6239d0>
<keras.layers.pooling.MaxPooling2D object at 0x7fbcac623950>
<keras.layers.core.Flatten object at 0x7fbcac623a90>
<keras.layers.core.Dense object at 0x7fbcac5c36d0>
<keras.layers.core.Dropout object at 0x7fbcac5f4250>
```

**Comment by gabrieldemarmiesse** [comment]
Can you give the output of pip freeze for both python 2 and 3? Thank you.

**Comment by balbok0** [comment]
<details>
<summary>Python 2</summary>
<br>

- absl-py==0.1.12
- adium-theme-ubuntu==0.3.4
- astor==0.6.2
- atomicwrites==1.2.1
- attrs==18.2.0
- backports-abc==0.5
- backports.functools-lru-cache==1.5
- backports.shutil-get-terminal-size==1.0.0
- backports.weakref==1.0.post1
- bleach==1.5.0
- configparser==3.5.0
- cycler==0.10.0
- decorator==4.0.6
- entrypoints==0.2.3
- enum34==1.1.6
- funcsigs==1.0.2
- functools32==3.2.3.post2
- futures==3.2.0
- gast==0.2.0
- grpcio==1.10.0
- h5py==2.8.0
- horovod==0.12.0
- html5lib==0.9999999
- ipykernel==4.8.2
- ipyparallel==6.1.1
- ipython==5.5.0
- ipython-genutils==0.2.0
- ipywidgets==7.1.2
- Jinja2==2.10
- jsonschema==2.6.0
- jupyter==1.0.0
- jupyter-client==5.2.2
- jupyter-console==5.2.0
- jupyter-core==4.4.0
- Keras==2.1.5
- kiwisolver==1.0.1
- Markdown==2.6.11
- MarkupSafe==1.0
- matplotlib==2.2.2
- mistune==0.8.3
- mock==2.0.0
- more-itertools==4.3.0
- mpi4py==3.0.0
- nbconvert==5.3.1
- nbformat==4.4.0
- notebook==5.4.0
- numpy==1.15.1
- pandocfilters==1.4.2
- pathlib2==2.3.2
- pbr==3.1.1
- pexpect==4.0.1
- pickleshare==0.7.4
- Pillow==5.0.0
- pluggy==0.7.1
- prompt-toolkit==1.0.15
- protobuf==3.5.2.post1
- psutil==5.4.7
- ptyprocess==0.5
- py==1.6.0
- Pygments==2.2.0
- pyparsing==2.2.0
- pytest==3.8.1
- python-dateutil==2.6.1
- pytz==2018.3
- PyYAML==3.12
- pyzmq==17.0.0
- qtconsole==4.3.1
- scandir==1.9.0
- scikit-learn==0.19.2
- scipy==1.0.0
- Send2Trash==1.5.0
- simplegeneric==0.8.1
- singledispatch==3.4.0.3
- six==1.11.0
- sklearn==0.0
- subprocess32==3.2.7
- tensorboard==1.6.0
- tensorflow-gpu==1.6.0
- termcolor==1.1.0
- terminado==0.8.1
- testpath==0.3.1
- torch==0.3.1
- torchvision==0.2.0
- tornado==5.0
- traitlets==4.3.2
- typing==3.6.6
- ufw==0.35
- unity-lens-photos==1.0
- wcwidth==0.1.7
- Werkzeug==0.14.1
- widgetsnbextension==3.1.4

</details>
<details>
<summary>Python 3</summary>

- absl-py==0.4.0
- alabaster==0.7.11
- apt-clone==0.2.1
- apturl==0.5.2
- astor==0.7.1
- atomicwrites==1.2.0
- attrs==18.1.0
- Babel==2.6.0
- backcall==0.1.0
- beautifulsoup4==4.6.3
- bleach==2.1.4
- Brlapi==0.6.6
- certifi==2018.8.13
- cffi==1.11.5
- chardet==3.0.4
- click==6.7
- cloudpickle==0.5.5
- command-not-found==0.3
- configobj==5.0.6
- coverage==4.5.1
- cupshelpers==1.0
- cycler==0.10.0
- Cython==0.28.5
- dask==0.18.2
- decorator==4.3.0
- defer==1.0.4
- docutils==0.14
- entrypoints==0.2.3
- first==2.0.1
- gast==0.2.0
- grpcio==1.14.1
- h5py==2.8.0
- html5lib==1.0.1
- httplib2==0.11.3
- hypothesis==3.69.2
- idna==2.7
- imagesize==1.0.0
- ipykernel==4.9.0
- ipython==6.5.0
- ipython-genutils==0.2.0
- ipywidgets==7.4.1
- jedi==0.12.1
- Jinja2==2.10
- joblib==0.12.5
- jsonschema==2.6.0
- jupyter==1.0.0
- jupyter-client==5.2.3
- jupyter-console==5.2.0
- jupyter-core==4.4.0
- Keras==2.2.2
- Keras-Applications==1.0.4
- Keras-Preprocessing==1.0.2
- keras-tqdm==2.0.1
- kiwisolver==1.0.1
- louis==1.3
- macaroonbakery==1.1.4
- Mako==1.0.7
- Markdown==2.6.11
- MarkupSafe==1.0
- matplotlib==2.2.3
- mistune==0.8.3
- more-itertools==4.3.0
- nbconvert==5.3.1
- nbformat==4.4.0
- networkx==2.1
- notebook==5.6.0
- numexpr==2.6.8
- numpy==1.15.1
- onboard==1.4.1
- packaging==17.1
- pam==0.1.4
- pandas==0.23.4
- pandocfilters==1.4.2
- parso==0.3.1
- pexpect==4.6.0
- pickleshare==0.7.4
- Pillow==5.2.0
- pip-tools==2.0.2
- pluggy==0.7.1
- prometheus-client==0.3.1
- prompt-toolkit==1.0.15
- protobuf==3.6.1
- psutil==5.4.2
- ptyprocess==0.6.0
- py==1.5.4
- pycairo==1.16.2
- pycparser==2.18
- pycrypto==2.6.1
- pycups==1.9.73
- pycurl==7.43.0.1
- pygame==1.9.4
- Pygments==2.2.0
- pygobject==3.26.1
- PyICU==1.9.8
- pyinotify==0.9.6
- pymacaroons==0.13.0
- PyNaCl==1.2.1
- pyparsing==2.2.0
- pyRFC3339==1.1
- pytest==3.7.2
- python-apt==1.6.2
- python-dateutil==2.7.3
- python-debian==0.1.33
- python-xapp==1.2.0
- python-xlib==0.23
- pytz==2018.5
- PyWavelets==0.5.2
- pyxdg==0.26
- PyYAML==3.13
- pyzmq==17.1.2
- qtconsole==4.4.1
- readline==6.2.4.1
- reportlab==3.5.6
- requests==2.19.1
- requests-unixsocket==0.1.5
- root-numpy==4.7.3
- rootpy==1.0.1
- scikit-image==0.14.0
- scikit-learn==0.19.2
- scipy==1.1.0
- Send2Trash==1.5.0
- sessioninstaller==0.0.0
- setproctitle==1.1.10
- simplegeneric==0.8.1
- six==1.11.0
- sklearn==0.0
- snowballstemmer==1.2.1
- Sphinx==1.7.7
- sphinxcontrib-websupport==1.1.0
- system-service==0.3
- systemd-python==234
- tables==3.4.4
- tensorboard==1.10.0
- tensorflow==1.10.0
- termcolor==1.1.0
- terminado==0.8.1
- testpath==0.3.1
- Theano==1.0.2
- toolz==0.9.0
- tornado==5.1
- tqdm==4.25.0
- traitlets==4.3.2
- ubuntu-drivers-common==0.0.0
- ufw==0.35
- urllib3==1.23
- wcwidth==0.1.7
- webencodings==0.5.1
- Werkzeug==0.14.1
- widgetsnbextension==3.4.1
- xkit==0.0.0

</details>

**Comment by balbok0** [comment]
I also tried to run it on python2 on personal laptop (cpu), not the server and it also worked, so it's not the issue with python version. I am suspecting that it might be due to some flag with which tensorflow was compiled on server.

**Comment by gabrieldemarmiesse** [comment]
It seems that you have a different version of keras for python 2 and 3.
Which might explain the difference. Can you update keras and check? Thank
you.
