### ISSUE TITLE
Cant load keras 

### ISSUE THREAD

**Issue by paulgureghian** [keras-team/keras#11230]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!
![capture2](https://user-images.githubusercontent.com/8146561/46105848-f59b2300-c18b-11e8-80c4-fc5b969a0361.PNG)

- [ ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [ ] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by paulgureghian** [comment]
I have the current version of keras and tensorflow in a conda py3 env.

**Comment by yimingpeng** [comment]
Please make sure that you use the right Python interpreter where Keras is installed.
<img width="1658" alt="screen shot 2018-09-27 at 4 11 51 pm" src="https://user-images.githubusercontent.com/5914252/46123110-9c58ef80-c270-11e8-8f91-9136cf0f39f2.png">

**Comment by VanitarNordic** [comment]
Have you installed the keras correctly? You can use this package: https://anaconda.org/hesi_m/keras
