### ISSUE TITLE
Specify initial state for stateful RNN

### ISSUE THREAD

**Issue by jingyuanz** [keras-team/keras#11241]
Hi guys, just curious about how to code in keras for the following senario:

have a stateful LSTM -> reset states every x epochs -> on each reset, specify a random initial state for the first input of the stateful LSTM.

my first thought is to feed the random state 's' as an input to the model and set the parameter initial_state=s for the LSTM. In this case, I am not sure if this specified initial state will override the initial state arise from the stateful property for all time steps instead of just the first step.

Is this method correct? or is there any better way to do this.

**Comment by partoptr** [comment]
Hello, I'm using RNN and kinda need the same answer here. did you by any chance figure it out already?
