### ISSUE TITLE
Keras-applications/preprocessing  and keras are mutually dependent

### ISSUE THREAD

**Issue by roywei** [keras-team/keras#11243]
Currently keras and keras-preprocessing depends on each other.
Since it's already a separate module with it's own pip package, shouldn't we be able to use keras-preprocessing as an independent tool that does not depends on keras?
Having these two modules mutually depends on each other is causing conflicts at keras-mxnet (a keras fork) awslabs/keras-apache-mxnet#129

same applies to keras-applications

**Comment by gabrieldemarmiesse** [comment]
We are working to make this separation of repos as smooth as possible. Linking to #11238 and #11203 and #10952

**Comment by gabrieldemarmiesse** [comment]
This issue has been resolved in https://github.com/keras-team/keras-preprocessing/commit/f010ca55334b3cbb2cf20289cf661b5430232810 Thanks for reporting this issue.
