### ISSUE TITLE
Adding a 'Tensorflow compatibility features' page in the documentation. 

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [keras-team/keras#11250]
The keras documentation lacks a page about all the features which make keras integrate well in Tensorflow workflows. Things that we would like to see in this page:

* Using native TF optimizers
* Using the dataset API and the input tensors.
* How to get the tensorflow tensors out of a keras model
* How to use `session.run` in keras
* Using keras layers in a tensorflow graph
* ... 

Help would be appreciated. For examples of code, you can look in the keras test directory, all the functions which have the decorator `@pytest.mark.skipif(K.backend() != 'tensorflow') `

@rohit-gupta

**Comment by HughKu** [comment]
Any update here? @rohit-gupta, I'd like to help on this if you need, thanks.

**Comment by rohit-gupta** [comment]
Hey @HughKu, I am working on this currently, will send out a PR when I am done, but would love any help from you.


Currently I am looking at:

How to use Tensorflow optimizers:

https://github.com/keras-team/keras/pull/11229/files


Francois's guide to using Keras with TF:

https://blog.keras.io/keras-as-a-simplified-interface-to-tensorflow-tutorial.html

Zach Moshe's documentation of some common pitfalls when using Keras models with TF:

http://zachmoshe.com/2017/11/11/use-keras-models-with-tf.html

If you have any other ideas or suggestions regarding scope, would love to hear that.

**Comment by gabrieldemarmiesse** [comment]
I would not recommend using methods presented in http://zachmoshe.com/2017/11/11/use-keras-models-with-tf.html.

Notably:

* use `K.get_session()` instead of creating a new session, so that you don't have to reload the weights.

* to get the paceholder and the output tensorflow tensors of a keras model, there is no need to create a second placeholder and apply the model on it. Just do `model.inputs` and `model.outputs`.

It shows that this page is really needed in the documentation. There is a lot of confusion on it.

**Comment by gabrieldemarmiesse** [comment]
The learning phase is important, true, notably the `training` argument present when calling a layer like dropout or batchnorm.

Thanks for working on it, that's a great help!

**Comment by gabrieldemarmiesse** [comment]
Any update on this?

**Comment by rohit-gupta** [comment]
Hi @gabrieldemarmiesse sorry about the delay, I was on vacation last week. 

But I have been carrying out some experiments, and I think I found a bug. Seems like the Callbacks breaks when using a Tensorflow optimizer:

```
Epoch 1/100
856/856 [==============================] - 1748s 2s/step - loss: 6.0733
Traceback (most recent call last):
  File "train_attention.py", line 164, in <module>
    verbose=1, shuffle=True)
  File "/home/deepromay/anaconda2/envs/tensorflow110/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/deepromay/anaconda2/envs/tensorflow110/lib/python2.7/site-packages/keras/engine/training.py", line 1415, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/deepromay/anaconda2/envs/tensorflow110/lib/python2.7/site-packages/keras/engine/training_generator.py", line 247, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/deepromay/anaconda2/envs/tensorflow110/lib/python2.7/site-packages/keras/callbacks.py", line 77, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/deepromay/anaconda2/envs/tensorflow110/lib/python2.7/site-packages/keras/callbacks.py", line 1037, in on_epoch_end
    logs['lr'] = K.get_value(self.model.optimizer.lr)
AttributeError: 'TFOptimizer' object has no attribute 'lr'
```

**Comment by gabrieldemarmiesse** [comment]
Thank you for the bug report! I think this is related to some code that I found in the codebase. See: 
https://github.com/keras-team/keras/blob/590aa832680641218b233b22fa8b3bd7fdc0287e/keras/engine/saving.py#L116

Could you open an issue with this bug. At least, if we can't handle it, we should have a meaningful error message. So I would consider what you found a bug. 

Thank you for your hard work!

**Comment by gabrieldemarmiesse** [comment]
I would say that you are sailing in uncharted waters :)

**Comment by gabrieldemarmiesse** [comment]
Very interesting. It seems that we'll need to update this page quite a bit once TF 2.0 is out.
