### ISSUE TITLE
TfRecord MNIST example copies weights without it being necessary

### ISSUE THREAD

**Issue by dmaniry** [keras-team/keras#11268]
https://github.com/keras-team/keras/blob/b09ec1c9bf827622a5eebb94ba0af5bf202ca359/examples/mnist_tfrecord.py#L89

This line does nothing, because both models already access the same weights.

**Comment by tedyu** [comment]
Wouldn't subsequent operations in on_epoch_end change the weights of self.val_model ?

**Comment by dmaniry** [comment]
> Wouldn't subsequent operations in on_epoch_end change the weights of self.val_model ?

Any change to the weights of any of the two model objects will change

**Comment by dmaniry** [comment]
Actually, I'm wrong and it's not the case in the way this is example is set up. But it would be possible and much cleaner to rewrite this example in a way that both models share all layers except the input layer, and thus avoid keeping around a second copy of the model and copy all the weights. You will get this behavior if you take the train model and call it with the test data input tensor instead of building the model a second time.
