### ISSUE TITLE
Apply a dense layer on a batch

### ISSUE THREAD

**Issue by basma-b** [keras-team/keras#11277]
Suppose I have model that takes two inputs x and y and produces z where z is a probability. Given batch size of 100, then the size of output z is (100, 1). I want to apply a dense layer on each batch so I obtain an output of size (1) per batch.

How can I do this in Keras ?

**Comment by farizrahman4u** [comment]
```python
input1 = Input(shape=(10,))
input2 = Input(shape=(10,))

out = concatenate([input1, input2])
out = Dense(1, activation='sigmoid')

model=Model([input1, input2], out)
```
