### ISSUE TITLE
how to use resnet/densenet backbones for segmentation?

### ISSUE THREAD

**Issue by nabsabraham** [keras-team/keras#11282]
I want to use different backbones in a U-Net fashion segmentation but cannot find a simple example of this - the complicated part for me is adding the skip connections because I cannot see the encoder layers. Is there a good example someone can point me to?

**Comment by harshini-gadige** [comment]
Hi

Since this is not a bug/feature request, request you to post these kind of questions in any of the following.

https://keras.io/
https://keras.io/#support
https://gitter.im/Keras-io/Lobby

Thanks!
