### ISSUE TITLE
`TimeseriesGenerator` for multi-step prediction

### ISSUE THREAD

**Issue by minhtriet** [keras-team/keras#11293]
`TimeseriesGenerator` seems to not support multi-step prediction, i.e I cannot find a method to specify the length of the output, it is set to 1 by default. Can we create a new future for this?

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps`

- [x] Check that your version of TensorFlow is up-to-date. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

**Comment by noklam** [comment]
any update on this?  Do you happen to find a solution around this @minhtriet

**Comment by lambdabr** [comment]
Pretty please?

**Comment by kopytjuk** [comment]
@gabrieldemarmiesse 

I am working on this feature in https://github.com/keras-team/keras-preprocessing/compare/master...kopytjuk:ts-generator-returnseq.

Will it find its way into keras codebase or should I contribute to tf/keras codebase?

**Comment by gabrieldemarmiesse** [comment]
For any API change, you should make an RFC here: https://github.com/keras-team/governance 

note that the team is currently very busy with the tf.keras migration to keras-team/keras, which will take several months, so it might take a while before the RFC is reviewed.

**Comment by lambdabr** [comment]
I found a way around this issue. If you feed the timeseriesgenerator a tuple of results for each result you can actually make it multistep.
