### ISSUE TITLE
while running the code for vgg16 from keras implementation  img = image.load_img(img_path, target_size=(224, 224)) i got the error IOError: [Errno 2] No such file or directory: 'elephant.jpg' how can i solve it

### ISSUE THREAD

**Issue by prativadas** [keras-team/keras#11298]
Please make sure that the boxes below are checked before you submit your issue.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps`

- [x] Check that your version of TensorFlow is up-to-date. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by gabrieldemarmiesse** [comment]
This error seems unrelated to keras. It seems that the path that you are giving is not the one of the image that you want to load.

**Comment by prativadas** [comment]
> This error seems unrelated to keras. It seems that the path that you are giving is not the one of the image that you want to load.

thank you. i was not giving the right path. thanks
