### ISSUE TITLE
Visualizing Keras Dense layer with Tensorboard Embedding Projector ? 

### ISSUE THREAD

**Issue by raghavgurbaxani** [keras-team/keras#11297]
Hi 

Any idea on how to visualize the Dense layer of a keras model using Tensorboard embedding projector ?

**Comment by MartinNowak** [comment]
See the tensorboard example https://github.com/keras-team/keras/blob/36b9e4c055f32718a036cabaf767325b010c7485/examples/tensorboard_embeddings_mnist.py#L76, simply explicity list the layer's name.
