### ISSUE TITLE
NoneType' object has no attribute '_inbound_nodes'

### ISSUE THREAD

**Issue by rdulmina** [keras-team/keras#11302]
I'm trying to solve this problem for hours but sill getting the NoneType' object has no attribute '_inbound_nodes' error.I think the issue is in **tf.add(layer3_1_out,layer3_2_out).** please help
![image](https://user-images.githubusercontent.com/26381349/46517262-12221400-c88c-11e8-8b63-31da0b22ca88.png)

I tried to attach the code snippet but it didn't detect my code as snippet,sorry for that.please help
Thank you.

**Comment by gabrieldemarmiesse** [comment]
Keras can't create model if you used a tensorflow operation without wrapping it into a layer. You have multiple options:
* use https://keras.io/layers/merge/#add instead of tf.add
* put tf.add into a lambda layer.

**Comment by rdulmina** [comment]
thank you very much.it working fine now :-)

**Comment by BryanBo-Cao** [comment]
I had a similar error before using Multiply(). However, using ```Lambda``` layer solved my issue. @gabrieldemarmiesse thanks!
