### ISSUE TITLE
Keras documentation of multi_gpu_model: example 2 can be misleading 

### ISSUE THREAD

**Issue by darteaga** [keras-team/keras#11307]
In the Keras documentation for `multi_gpu_model`, it is stated:

> To save the multi-gpu model, use .save(fname) or .save_weights(fname) with the template model (the argument you passed to multi_gpu_model), rather than the model returned by multi_gpu_model.

However in example 2 the template model is overwritten by the multi-gpu model:

```python
         ..
         # Not needed to change the device scope for model definition:
         model = Xception(weights=None, ..)
         try:
             model = multi_gpu_model(model, cpu_relocation=True)
             print("Training using multiple GPUs..")
         except:
             print("Training using single GPU or CPU..")
         model.compile(..)
         ..
```

This means that in this example it would not be possible to save the weights of the template model. I suggest rewritting to something like:

```python
         ..
         # Not needed to change the device scope for model definition:
         model = Xception(weights=None, ..)
         try:
             parallel_model = multi_gpu_model(model, cpu_relocation=True)
             print("Training using multiple GPUs..")
         except ValueError:
             parallel_model = model
             print("Training using single GPU or CPU..")
         parallel_model.compile(..)
         ..
```

(I take this opportunity to except only a specific error)

**Comment by gabrieldemarmiesse** [comment]
You are totally right. Thanks!
