### ISSUE TITLE
report_tensor_allocations_upon_oom causes model to crash

### ISSUE THREAD

**Issue by robertmaxton42** [keras-team/keras#11322]
I have a model that is much, much larger on the GPU than I expected it to be -- sufficiently so as to end up throwing an Out of Memory exception. I'm trying to debug by setting `report_tensor_allocations_upon_oom = True`, but if I do so my model never seems to make it onto the GPU in the first place - `nvidia-smi` reports no RAM usage -- and then after a few minutes the process dies. 

Minimal reproduction:

```
import numpy as np

from keras.layers import Input, Dense
from keras.models import Model

import tensorflow as tf

inp = Input((100,))

dense = Dense(100)(inp)

model = Model(inp, dense)

run_opts = tf.RunOptions(report_tensor_allocations_upon_oom = True)

model.compile('adadelta', 'binary_crossentropy', options=run_opts)

data = np.random.randint(3, size=(1000, 100))
labels = 5 * data

model.fit(data, labels, 100, 10)
```

returns `Epoch 1/10` and then hangs. Changing `True` to `False` makes the code work.

**Comment by robertmaxton42** [comment]
... ping? 

Sorry, it's been a full work week and I don't know how to debug my memory issues without something like this...

**Comment by yorickvP** [comment]
Encountered this same problem. I tend to find memory issues with `model.summary()`

**Comment by yorickvP** [comment]
```
[2599569.770595] python3.7[10090]: segfault at 28 ip 00007f2e51c1f177 sp 00007ffd6dade2d0 error 4 in _pywrap_tensorflow_internal.so[7f2e4d386000+35dc6000]
[2599569.770603] Code: ff ff 48 85 ff 0f 85 40 fa ff ff 48 8b bd e0 fa ff ff 48 85 ff 0f 85 42 fa ff ff e9 56 fa ff ff 0f 1f 00 48 8b 85 80 fa ff ff <4c> 8b 70 28 4d 85 f6 0f 84 8c 0d 00 00 bf 68 00 00 00 e8 02 e5 50
```

**Comment by ajyeager** [comment]
I'm also having the same problem, when setting report_tensor_allocations_upon_oom, but also when setting trace for profiling too.

**Comment by kehuantiantang** [comment]
The same to me, if `report_tensor_allocations_upon_oom = FALSE`, the model can fit properly.  otherwise, it just show that `process finished with exit code -1`

**Comment by zaccharieramzi** [comment]
Same problem here with a minimal example close to @robertmaxton42 's one. I can provide it if needed. 
The end of the stack trace is:
```
2019-07-31 13:50:51.867822: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
[1]    33814 segmentation fault  python personal_experiments/exp_oom_model.py
```
To me the crash is definitely linked to a segfault.

Pretty annoying because I wanted to debug something related to an OOM (that I can't see in `model.summary()`). Has anyone got any update on what's happening here?

**Comment by vinsunkavalli** [comment]
The only workaround I have found to avoid this problem is to downgrade your keras lib to an earlier version (I believe keras needs to be 2.1.6 or less) and then run the code. However, this means that you can't use the newer features. I hope that this can be fixed soon.

**Comment by bjtho08** [comment]
Any new progress on this for us who are still stuck on tf<2.0 and keras 2.3.0?
