### ISSUE TITLE
TimeDistributed with list of inputs

### ISSUE THREAD

**Issue by dyowee** [keras-team/keras#11330]
Is there a working example code or workaround to be able to pass multiple inputs to the TimeDistributed layer?

**Comment by robertmaxton42** [comment]
Not a `keras` developer, but I'm just concatenating my inputs with a TimeDistributed Merge layer.

**Comment by dyowee** [comment]
My code is similar to this, which generates an error:

model = Sequential()
model.add(Dense(32, input_dim=784))

inputs = [Input(shape=(32,)) for i in range(3)]
temps=[model(x) for x in inputs]
merged=merge(temps, mode='concat')
merged_model=Model(input=inputs, output=merged)

seq_inputs = (Input(shape=(20, 32)) for i in range(3))
outputs=TimeDistributed(merged_model)(*seq_inputs)

**Comment by robertmaxton42** [comment]
Mm. I don't quite know why it'd make a difference, but try `merged = Concatenate()(temps)` instead?

**Comment by dyowee** [comment]
Nope, the issue is the last line, passing a list of inputs to the TimeDistributed layer/wrapper

**Comment by robertmaxton42** [comment]
Oh, whoops. Um... as far as I know, `TimeDistributed` only works on *layers*, not models - you either want to wrap each individual Layer with `TimeDistributed`, or define a sequence of Layers as a custom Layer and wrap that.

**Comment by dyowee** [comment]
So, it is not possible with the current code I have posted earlier? 
Would you be able to show a snippet of what you mean?

**Comment by robertmaxton42** [comment]
I would suggest using `model.add(TimeDistributed(Dense(32, input_dim=784)))`, for example. Though I'm not entirely sure I understand your code snippet as written, so take that with a grain of salt.

**Comment by dyowee** [comment]
Doesn't really solve the issue. Really frustrating that Keras has this limitation. :(
