### ISSUE TITLE
Keras backend package uses a print call at initialisation time.

### ISSUE THREAD

**Issue by sarusso** [keras-team/keras#11332]
The backend package uses a `print` call in its `__init__.py` file to inform about which backend is going to be used (the "Using X backend." messages).

This is bad design, keras is a library and libraries should never ever call a print function.

To reproduce just type:

    import keras

A variant of this issue is #1406, where the nature of the problem has been misdiagnosed as directing that `print` function output to stdout, and the issue has been "fixed" in 83aaadaa9d69214880d20b1e2bd9715a6c37fbe6 by directing the output to stderr.

The state now, with that `print` output directed to stderr, is the worst behaviour ever: stderr is used by the Python logging module, and thereofore the "Using X backend." messages get mixed with the log messages of the application(s) using keras.

This is a **major issue** for a library: in complex applications it is common practice to aggregate logs on a central server or on online services, and having a line printed like this on stderr, without the same format as the other log messages (i.e. timestamp [severity] - module - message), is messing everything up.

I propose to either start using the Python logging module instead of the `print` function (which is the right approach, and for which I will shortly submit a pull request), or at least to move back to printing that line to stdout (not nice, but acceptable).

**Comment by sarusso** [comment]
Added pull request #11333 as potential fix.

**Comment by gabrieldemarmiesse** [comment]
Closing as the PR was rejected.

**Comment by sarusso** [comment]
If the pull request has been rejected (not sure about the reason though), why not reverting to printing to stdout instead of stderr, at least?
