### ISSUE TITLE
A preprocessing_function with parameters for ImageDataGenerator 

### ISSUE THREAD

**Issue by JeniaNovellusDx** [keras-team/keras#11339]
Hi, I'm training a semantic segmentation keras model on the COCO data-set. I want to create a custom preprocessing function that resets irrelevant objects to zero in the mask image, e.g. I want to train segmentation training and I only care of correctly segmenting 'cars', so I want to set to zero all other labels:

**The preprocessing function:**
```
def preprocess_mask(x, label):
    x = x.astype('int16')
    x[x!=label] = 0
    return x
```

The desired generator:

```
datagen = ImageDataGenerator(
        preprocessing_function = preprocess_mask(label=4),
        rescale=1./255,
        horizontal_flip=True)
```

But it doesn't work

**Comment by Dref360** [comment]
You need to implement a Functor in this case.

```
class MyFunctor():
    def __init__(self, label):
        self.label = label
    def __call__(self, x):
        ...
```

**Comment by epignatelli** [comment]
Do you then pass an instance or the schema?

**Comment by 100rab-S** [comment]
I also have the same issue, how do we solve it?

**Comment by Dref360** [comment]
As mentionned above, you can make a Functor or use `functools.partial`

**Comment by nicolasperezdeo** [comment]
I wanted to do something similar to @Golbstein. The solution proposed by @Dref360 is what you need. Just pass the arguments you need to the Functor class in the init method and you are good to go. In the call of the ImageDataGenerator then instance your new Functor class. In your case:


```
datagen = ImageDataGenerator(preprocessing_function = NewFunctorClass(4),
                             rescale=1./255,
                             horizontal_flip=True)

```

Hope this clarifies @Dref360 comment!

**Comment by Young1906** [comment]
What if I want to apply a different preprocessing function to each split? Ie. Augmentation on Train split but not on validation split?
