### ISSUE TITLE
Possible to use keras “flow_from_directory” with “.mat” files?

### ISSUE THREAD

**Issue by MikeDoho** [keras-team/keras#11344]
I would love to be able to use keras' .flow_from_directory() but have the directories contain ".mat" files containing arrays. The shape of these files are (48, 48, 32, 2); [:,:,:,0] = volume from PET imaging and [:,:,:,1] = volume from CT imaging.

When I have ".mat" files it says 0 images with 3 classes found (or something like that). I know this is because the .mat files arent images and arent on the list of recognized files but is there a way to do this with solely arrays?

**Comment by szymko1995** [comment]
Since matlab v7.3 .mat files are actually hdf5 files. I think it should be possible to load them with `keras.utils.HDF5Matrix` and use like np.array objects.

**Comment by MikeDoho** [comment]
Thank you I will try this!

Mike Dohopolski

**Comment by MikeDoho** [comment]
Again thank you for your answer.

I guess what I dont understand is how I would alter how the data is loaded. Would I have to create my own generator and then use/make my own flow_from_directory?

I tried to make my own generator but I dont think I am headed in the right direction

```
def load_train_data_batch_generator(self, batch_size=32, rows_in=48, cols_in=48,  zs_in=32,
                                        channels_in=2, num_classes=3,
                                        dir_in_train=None, dir_out_train=None):

        # dir_in_train = main_dir + '/test_CT_PET_combo'

       #example '1.mat'

        fnames = ['{}.mat'.format(i) for i in range(1,len(os.listdir(dir_in_train))+1)]

        y_train = np.zeros((len(os.listdir(dir_in_train)), num_classes))
        x_train = np.zeros((len(os.listdir(dir_in_train)), rows_in, cols_in, zs_in, channels_in))

        while True:
            count = 0
            for fname in np.random.choice(fnames, batch_size, replace=False):

                # loads one hot encoding
                data_label = scipy.io.loadmat(os.path.join(dir_out_train, fname))['output']


                y_train[count,:] = data_label

                # Loading train ct w/ c and pet/ct combo that will be saved  directory
                train_combo = scipy.io.loadmat(os.path.join(dir_in_train, fname))[fname]
                x_train[count,:,:,:,:] = train_combo

                count += 1

            yield(x_train, y_train)
```

**Comment by szymko1995** [comment]
I would rather inherit from `keras.utils.Sequence` and implement own __data_generation method.
Here's detailed example how to do it: https://stanford.edu/~shervine/blog/keras-how-to-generate-data-on-the-fly
It will allow you to fully utilize fit_generator method of your model without taking care of things other than data preprocessing pipeline and few other mandatory methods.
