### ISSUE TITLE
Create MobileNet_V2 model “AttributeError”

### ISSUE THREAD

**Issue by Arcyno** [keras-team/keras#11341]
Those two lines raise an error :

` from keras.applications.mobilenet_v2 import mobilenet_v2`
`base_model = mobilenet_v2.MobileNetV2(weights='imagenet', include_top=False) `

I get the following error : `AttributeError: 'NoneType' object has no attribute 'image_data_format'` in 
 keras_applications\mobilenet_v2.py, line 282,

**Comment by gabrieldemarmiesse** [comment]
```python
from keras.applications import MobileNetV2
m = MobileNetV2(weights='imagenet', include_top=False)
```
This works. It's weird that the imports that you are making are possible. But I think that we shoudn't consider this a bug if users stick to the documentation.

**Comment by suryavanshi** [comment]
@gabrieldemarmiesse I tried the exact same code and I am getting the below error. I am on Windows 10, using Keras 2.2.2 with Python 3.6.
This is my code - 
from keras.applications import MobileNetV2
model = MobileNetV2(weights='imagenet', include_top=False)
-----------------------
Error-
C:\Users\msurya\AppData\Local\Programs\Python\Python36\lib\site-packages\keras_applications\mobilenet_v2.py:310: UserWarning: MobileNet shape is undefined. Weights for input shape(224, 224) will be loaded.
  warnings.warn('MobileNet shape is undefined.'
Traceback (most recent call last):
  File "keras_mobilenetv2_info.py", line 7, in <module>
    model = MobileNetV2(weights='imagenet', include_top=False)
  File "C:\Users\msurya\AppData\Local\Programs\Python\Python36\lib\site-packages\keras_applications\mobilenet_v2.py", line 355, in MobileNetV2
    expansion=1, block_id=0)
  File "C:\Users\msurya\AppData\Local\Programs\Python\Python36\lib\site-packages\keras_applications\mobilenet_v2.py", line 461, in _inverted_res_block
    in_channels = inputs._keras_shape[-1]
AttributeError: 'Tensor' object has no attribute '_keras_shape'
