### ISSUE TITLE
Keras model serialization error (Pyspark)

### ISSUE THREAD

**Issue by anishsharma** [keras-team/keras#11360]
Spark driver creates an RDD of timeseries data having 49 timesteps. I am trying to make prediction on executor for which I have to pass keras model to executors. I have tried few things as below:

1. Created a separate class where store the model architecture and weights as a dictionary object.

`def serialize_keras_model(self, model):`
        `dictionary = {}`
        `dictionary['model'] = model.to_json()`
        `dictionary['weights'] = model.get_weights()`
        `return dictionary`

  `def __init__(self, keras_model):`
        `self.model = self.serialize_keras_model(keras_model)`

 When required I just created the model inside predict method of this class.

 `def _predict(self, iterator):`
        `model = self.deserialize_keras_model(self.model)`
        `for data in iterator:`
            `model.predict(data)`

The issue here is self.deserialize_keras_model took near about 2-3 seconds which is far from our make whole flow execute in 1 sec and this is happening for each job.

2. I also tried broadcasting keras model but got pickle serialization error.

`broadcasted_model = sc.sparkContext.broadcast(model)`

Any advice how can I pass keras model efficiently to executors only once. I don't want this to happen for each job because that just defeat the purpose of processing under 1 sec.

**Comment by ymjain** [comment]
Please share the solution if you've already found it!
