### ISSUE TITLE
Using 'initial_state' with a TimeDistributed Layer

### ISSUE THREAD

**Issue by Youmna-H** [keras-team/keras#11367]
I have a heirarchical model of words that compose sentences then these sentences compose the document. In one part of the model, I generated sentence representations with an LSTM over the words in each sentence, so now I have sentence representations as [S,S2,...Sn] where n is the # of sentences in the document:
`lstm1 = TimeDistributed(LSTM(100, return_sequences=False, name='lstm1'))(word_embed) #word_embed is the word embedding layer`
What I want to do next is to have another part of the model where I build an LSTM on top of the words in each sentence and use the previous sentence encoding (in [S,S2,...Sn]) to initialize the hidden states in this second LSTM. So for each sentence in this LSTM I have:
`LSTM(100, return_sequences=True, name='lstm2')(word_embed)`
But as this is done for each sentence I need to wrap it in a TimeDistributed layer:
`lstm2 = TimeDistributed(LSTM(100, return_sequences=True, name='lstm2'))(word_embed)`

The problem is I want to initiallize the hidden state of lstm2 with lstm1 but I cannot use the 'initial_state' key used with RNNs because it is wrapped withing the TimeDistributed layer and TimeDistributed doesn't accept that key.

**Comment by farizrahman4u** [comment]
Did you try just passing the 'initial_state' arg to the LSTM like this?
```
lstm2 = TimeDistributed(LSTM(100, return_sequences=True, name='lstm2', initial_state=.....))(word_embed)
```

**Comment by Youmna-H** [comment]
This won't work because I want the hidden state of the first word in each sentence to be initalized with the representation of the sentence before. I think passing initial_state to the LSTM would just copy the same state to all the sentences.

**Comment by Youmna-H** [comment]
Also, another related question. if pre-padding is used in a sentence, would using 'initial_state' initialize the hidden layer of the first 'non-zero' value in the sentence, or would it be for the padding zeros? In other words, how does masking work in that case?
