### ISSUE TITLE
Error when using HDF5Matrix to fit the model

### ISSUE THREAD

**Issue by jdevoldere** [keras-team/keras#11372]
So I define my data like this:
```
x_train = keras.utils.io_utils.HDF5Matrix('dataset.h5', 'x_train')
y_train = keras.utils.io_utils.HDF5Matrix('dataset.h5', 'y_train')
x_test = keras.utils.io_utils.HDF5Matrix('dataset.h5', 'x_test')
y_test = keras.utils.io_utils.HDF5Matrix('dataset.h5', 'y_test')
```
But then when I try to fit the model like this:
`model.fit(x_train, y_train, epochs=epochs, validation_data=(x_test, y_test), callbacks=[tensorboard, modelcheckpoint], batch_size=batch_size, shuffle=False)`
I get this error:

>   File "G:\CryptoForecast\cryptomodel.py", line 34, in train_model
    model.fit(x_train, y_train, epochs=epochs, validation_data=(x_test, y_test), callbacks=[tensorboard, modelcheckpoint], batch_size=batch_size, shuffle=False)
  File "C:\ProgramData\Anaconda3\envs\TradingBot\lib\site-packages\keras\engine\training.py", line 952, in fit
    batch_size=batch_size)
  File "C:\ProgramData\Anaconda3\envs\TradingBot\lib\site-packages\keras\engine\training.py", line 670, in _standardize_user_data
    'You passed: x=' + str(x))
ValueError: Please provide as model inputs either a single array or a list of arrays. You passed: x=<keras.utils.io_utils.HDF5Matrix object at 0x000002342575E4E0>

But it should be working, no?

**Comment by jdevoldere** [comment]
Does model.fit() work for anyone else with HDF5Matrixes? Or am I the only one using it?

**Comment by mrtj** [comment]
I successfully trained a model directly from hdf5 files using `ImageDataGenerator.flow` with `HDF5Matrix` instances in place of the numpy arrays.
