### ISSUE TITLE
Making lines shorter in five different files.

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [keras-team/keras#11383]
We are trying to make all the files in the codebase have a line lenght below 85. This has been done to nearly all files. Just five are not done yet:

* keras/backend/cntk_backend.py
* keras/backend/common.py
* keras/backend/tensorflow_backend.py
* keras/backend/theano_backend.py
* tests/keras/backend/backend_test.py

If you want to take up this issue, please make one Pull request per file (you don't have to do all five pull requests at once). And once the lines are shorter for one file, you can remove the corresponding exception in the https://github.com/keras-team/keras/blob/master/pytest.ini to enable the tests.

**Comment by mechaprabal** [comment]
HI!
I am chasing to complete my first PR.
I would like to know that what to be exactly mean by reducing line length below 85.  

Thanks!

**Comment by gabrieldemarmiesse** [comment]
PEP8 recommend a maximum line lenght of 79 characters, we aim for 85. So we need to make some lines shorter in those files. See https://www.python.org/dev/peps/pep-0008/#maximum-line-length

**Comment by JustLou** [comment]
I've had a go at:

* keras/backend/common.py
* keras/backend/theano_backend.py

Still 3 more for others to do.

Thank you, was an interesting learning exercise (also thanks to @iwillspeak for talking me through the harder bits).

**Comment by mechaprabal** [comment]
I would like to work on `keras/backend/cntk_backend.py`

**Comment by daten-kieker** [comment]
I attempted to fix `tests/keras/backend/backend_test.py`.

**Comment by daten-kieker** [comment]
@GabrielBianconi Just found your [PR #11184](https://github.com/keras-team/keras/pull/11184) doing the same for `backend_test.py`. [Mine](https://github.com/keras-team/keras/pull/11407) would be a duplicate but has no conflicts with master.

Should I close mine?

**Comment by nbuhagiar** [comment]
I've just submitted a PR for keras/backend/tensorflow_backend.py.

I hope this helped!
