### ISSUE TITLE
keras.datasets.fashion_mnist.py cannot config path to hold the dowloaded files

### ISSUE THREAD

**Issue by weiyinfu** [keras-team/keras#11385]
Other datasets under the package `keras.datasets` has a load_data function which has a ·path· parameter. The fashion mnist dataset is the only special case . This is inconsistent.
So I think the better way is to give freedom to users to config where to put the downloaded data .

this is the reuter datasets use case:
```python
(x_train, y_train), (x_test, y_test) = reuters.load_data("/data/reuters.npz",num_words=max_words,test_split=0.2)
```

fashion mnist is different from other dataset, it's very ugly.
And I cannot think up why don't give freedom to users.

this is the fashion mnist code:
```python

def load_data():
    """Loads the Fashion-MNIST dataset.

    # Returns
        Tuple of Numpy arrays: `(x_train, y_train), (x_test, y_test)`.
    """
    dirname = os.path.join('datasets', 'fashion-mnist')
    base = 'http://fashion-mnist.s3-website.eu-central-1.amazonaws.com/'
    files = ['train-labels-idx1-ubyte.gz', 'train-images-idx3-ubyte.gz',
             't10k-labels-idx1-ubyte.gz', 't10k-images-idx3-ubyte.gz']

```

**Comment by weiyinfu** [comment]
I still don't understand your mean . There are tow explanations of your words.
* First ,you don't think it's a problem because other datasets have the same problem
* Second ,you think all of the three datasets should be modified.

Certailly,the three is different from other datasets. And mnist-fashion is not the only one.
But the three datasets are still different from other datasets.
Keras provided 8 datasets only three of them are different from others.
Don't you think we should modify it ?

**Comment by weiyinfu** [comment]
I still don't understand your mean . There are tow explanations of your words.
* First ,you don't think it's a problem because other datasets have the same problem
* Second ,you think all of the three datasets should be modified.

Certailly,the three is different from other datasets. And mnist-fashion is not the only one.
But the three datasets are still different from other datasets.
Keras provided 8 datasets only three of them are different from others.
Don't you think we should modify it ?

**Comment by weiyinfu** [comment]
I still don't understand your mean . There are tow explanations of your words.
* First ,you don't think it's a problem because other datasets have the same problem
* Second ,you think all of the three datasets should be modified.

Certailly,the three is different from other datasets. And mnist-fashion is not the only one.
But the three datasets are still different from other datasets.
Keras provided 8 datasets only three of them are different from others.
Don't you think we should modify it ?

**Comment by weiyinfu** [comment]
I still don't understand your mean . There are tow explanations of your words.
* First ,you don't think it's a problem because other datasets have the same problem
* Second ,you think all of the three datasets should be modified.

Certailly,the three is different from other datasets. And mnist-fashion is not the only one.
But the three datasets are still different from other datasets.
Keras provided 8 datasets only three of them are different from others.
Don't you think we should modify it ?

**Comment by jacquerie** [comment]
I meant that

> [...] all of the three datasets should be modified.

In fact, I sent https://github.com/keras-team/keras/pull/11454 that does exactly that!

**Comment by gabrieldemarmiesse** [comment]
Closing this issue as #11454 was closed
