### ISSUE TITLE
Explaining how to load external backends in the documentation.

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [keras-team/keras#11384]
In keras, it's possible to load other backends than tensorflow, theano or CNTK. Let's suppose there is a python file called `mxnet_backend.py` (for example), it's possible to load it as a backend by doing "backend" : "mxnet_backend" in keras.json.

See this file for more info: https://github.com/keras-team/keras/blob/161f0a876db4f8aa9d57161c13d366f081369601/keras/backend/__init__.py#L91 

This should be documented there: https://keras.io/backend/#switching-from-one-backend-to-another

**Comment by JoshuaRM** [comment]
I am on this issue
