### ISSUE TITLE
multi_gpu_model seems not to work

### ISSUE THREAD

**Issue by emergix** [keras-team/keras#11408]
#simple code : 

from keras.models import Sequential
from keras.layers import Dense, Activation
model = Sequential()
model.add(Dense(32, input_dim=784))
model.add(Activation('relu'))
parralelmodel =tf.keras.utils.multi_gpu_model(model, gpus=4)

gives me 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py in __init__(self, outbound_layer, inbound_layers, node_indices, tensor_indices, input_tensors, output_tensors, arguments)
   1758         # For compatibility with external Keras, we use the deprecated
   1759         # accessor here.
-> 1760         layer.outbound_nodes.append(self)
   1761     # For compatibility with external Keras, we use the deprecated
   1762     # accessor here.

AttributeError: 'InputLayer' object has no attribute 'outbound_nodes'

I use keras 2.2.4 and tensorflow 1.11.0 on cuda 9.0

**Comment by DavidTorresOcana** [comment]
Hello

I think I solved this issue by changing line 1376 of file _pythonx.x/dist-packages/tensorflow/python/layersfrom/base.py_ from :
`        layer.outbound_nodes.append(self)
`
to
`        layer._outbound_nodes.append(self)
`
Latest release of Keras deprecated _outbound_nodes_ and uses __outbound_nodes_

**Comment by jvishnuvardhan** [comment]
Is this still an issue with latest versions of TF and keras? Thanks.

**Comment by benman1** [comment]
tensorflow version 0.13.1

from tensorflow.python.keras.utils import multi_gpu_model
parallel_model = multi_gpu_model(model, gpus=2)

> ...
/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   1424         use_multiprocessing=use_multiprocessing,
   1425         shuffle=shuffle,
-> 1426         initial_epoch=initial_epoch)
   1427 
   1428   def evaluate_generator(self,

/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training_generator.py in model_iteration(model, data, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch, mode, batch_size, **kwargs)
    123 
    124   batch_function = _make_execution_function(
--> 125       model, mode, class_weight=class_weight)
    126 
    127   # Create the queue for the generator.

/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training_generator.py in _make_execution_function(model, mode, class_weight)
    425   if mode == 'train':
    426     if not context.executing_eagerly():
--> 427       model._make_fit_function()
    428     f = functools.partial(model.train_on_batch, class_weight=class_weight)
    429   elif mode == 'test':

/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training.py in _make_fit_function(self)
   1924     ]
   1925     self._make_train_function_helper(
-> 1926         '_fit_function', [self.total_loss] + metrics_tensors)
   1927 
   1928   def _make_test_function_helper(self, fn_name, outputs, metric_updates=None):

AttributeError: 'Model' object has no attribute 'total_loss'

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will open a new issue. Thanks!

**Comment by UpCoder** [comment]
In TF 1.13.1 same errors.
