### ISSUE TITLE
Which structure of RNN is implemented by SimpleRNN in keras?

### ISSUE THREAD

**Issue by nnb95baddi** [keras-team/keras#11403]
Two types of RNN can be used:

Type1: The output is being used as state

  h(t) = g(W<sub>1</sub>.x(t) + W<sub>2</sub>.h(t-1) + b<sub>1</sub>)

Type2: There is a state in addition to the output
 
  a(t) = g(W<sub>1</sub>.x(t) + W<sub>2</sub>.a(t-1) + b<sub>1</sub>)

  h(t) = g(W<sub>3</sub>.a(t) + b<sub>2</sub>)

I know both of them can be used, but I want to be sure which one is imlemented in keras. So, which of the above mathematical structure is implemented by SimpleRNN in keras? I tried looking at the documentation, but its unclear.

**Comment by lvapeab** [comment]
Looking into [the code](https://github.com/keras-team/keras/blob/590aa832680641218b233b22fa8b3bd7fdc0287e/keras/layers/recurrent.py#L910), the `SimpleRNN`  is your Type1.

For achieving your Type2 (aka, [Elman network](https://en.wikipedia.org/wiki/Recurrent_neural_network#Elman_networks_and_Jordan_networks)), one could add a `TimeDistributed(Dense(...))` layer on top of the `SimpleRNN`.
