### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by hasibzunair** [keras-team/keras#11410]
Getting this error when I try to load resnet50:

`ConnectionResetError: [Errno 104] Connection reset by peer`

And when I try to load xception i get this:

`ValueError: Input size must be at least 71x71; got `input_shape=(48, 48, 3)``

Please check the code sample [here](https://gist.github.com/hasibzunair/606c9037abed51836e5dc6059141bfff)

**Comment by gabrieldemarmiesse** [comment]
Connection reset by peer is your internet network not working, the xception error message is already very clear and explicit. You cannot set this input shape with the network.

**Comment by hasibzunair** [comment]
@gabrieldemarmiesse thank you.
