### ISSUE TITLE
how to run tests

### ISSUE THREAD

**Issue by lhk** [keras-team/keras#11414]
I'm developing a custom layer and would like to extend the existing testsuite.
To work on the source, I have installed it like this:

 - `pip install keras-preprocessing`
 - `pip install keras-applications`
 - `git clone https://github.com/keras-team/keras`
 - `cd keras`
 - `export PYTHONPATH=$PWD:$PYTHONPATH`

The cloned repository is the working directory for the code below.

To begin with, I would like to run the existing tests and see what they do. [It looks like][1] they can simply be run as a python file:

    if __name__ == '__main__':
        pytest.main([__file__])

But this: 

    python tests/keras/layers/wrappers_test.py

produces the following output, and doesn't run any tests

    Using TensorFlow backend.
    usage: wrappers_test.py [options] [file_or_dir] [file_or_dir] [...]
    wrappers_test.py: error: unrecognized arguments: -n tests/keras/layers/wrappers_test.py
      inifile: /home/lhk/programming/keras/pytest.ini
      rootdir: /home/lhk/programming/keras

So I tried explicitly calling pytest next: 

    pytest tests/keras/layers/wrappers_test.py

Exactly the same response (without the tensorflow log):

    usage: pytest [options] [file_or_dir] [file_or_dir] [...]
    pytest: error: unrecognized arguments: -n tests/keras/layers/wrappers_test.py
      inifile: /home/lhk/programming/keras/pytest.ini
      rootdir: /home/lhk/programming/keras

I'm using PyCharm, and if I run the tests from within pycharm (which I admittedly tried first), it only produces the messages above.

Apparently, I'm not configuring it correctly. Pytest is not able to pick up the test suite. To find a reference configuration, I looked at your CI setup. More specifically, this Travis config: https://travis-ci.org/keras-team/keras/jobs/442252422/config

It looks like I have all the dependencies installed. And the actual test command is basically what I have already tried:

    PYTHONPATH=$PWD:$PYTHONPATH py.test tests/ --ignore=tests/integration_tests --ignore=tests/test_documentation.py --ignore=tests/keras/legacy/layers_test.py --cov-config .coveragerc --cov=keras tests/

It produces the exact same output as above.

I assume that the problem lies with pytest. But the installation section of the automated testing simply shows `pip install pytest pytest-pip8`. I ran this, but sure enough, `requirement already satisfied`.

How can I execute the keras pytests ?
I'm running ubuntu 18.04.1, python 3.6.5 with anaconda 64bit.

[1]: https://github.com/keras-team/keras/blob/590aa832680641218b233b22fa8b3bd7fdc0287e/tests/keras/layers/wrappers_test.py#L636

**Comment by Dref360** [comment]
You do have some missing dependencies.
You need those :
'tests': ['pytest',
          'pytest-pep8',
          'pytest-xdist',
          'pytest-cov',
          'pytest-timeout',
          'pandas',
          'requests'],

This is highlighted in the CONTRIBUTING.md
