### ISSUE TITLE
Name Error-" name 'Flatten' is not defined ", when i try to fine tune the pretrained model on InceptionV3

### ISSUE THREAD

**Issue by tejasri19** [keras-team/keras#11415]
NameError                                 Traceback (most recent call last)
<ipython-input-46-095f9679650a> in <module>()
      1 # set up transfer learning on pre-trained ImageNet Inception_V3 model - remove fully connected layer and replace
      2 # with softmax for classifying 10 classes
----> 3 incepV3_model = InceptionV3(weights = 'imagenet', include_top = False, input_shape=(299,299,3))
      4 x = incepV3_model.output
      5 x = Flatten(name='flatten')(x)

~/anaconda3/envs/tensorflow-venv/lib/python3.6/site-packages/keras_applications/inception_v3.py in InceptionV3(include_top, weights, input_tensor, input_shape, pooling, classes)
    362         elif pooling == 'max':
    363             x = layers.GlobalMaxPooling2D()(x)
--> 364         x = Flatten(name='flatten')(x)
    365  # Ensure that the model takes into account
    366  # any potential predecessors of `input_tensor`.

NameError: name 'Flatten' is not defined

**Comment by gabrieldemarmiesse** [comment]
name xxx is not defined in python means that this variable does not exist. It's very likely unrelated to keras. Maybe you forgot to import Flatten?

**Comment by tejasri19** [comment]
I have imported Flatten from keras.layers , even though the error occurs

**Comment by nader-chmait** [comment]
import keras.utils
