### ISSUE TITLE
sparse_top_k_categorical_accuracy raises ValueError for temporal outputs.

### ISSUE THREAD

**Issue by bharris47** [keras-team/keras#11436]
Please make sure that the boxes below are checked before you submit your issue.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps`

- [x] Check that your version of TensorFlow is up-to-date. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

Hi, I have a sequence classification problem and want to use top-k accuracy as a metric, but the function does not seem to like 3D arrays for predictions. The normal accuracy metric works fine, so I would expect this one should too.

Here is a minimal example to reproduce the issue.
```python
from keras import Sequential
from keras.layers import Dense

model = Sequential()
model.add(Dense(8, activation='softmax', input_shape=(None, 2)))
model.compile('adam', loss='sparse_categorical_crossentropy', metrics=['sparse_top_k_categorical_accuracy'])
```

Outputs:
`ValueError: Shape must be rank 2 but is rank 3 for 'metrics/sparse_top_k_categorical_accuracy/in_top_k/InTopKV2' (op: 'InTopKV2') with input shapes: [?,?,8], [?,?], [].`

I have hacked around this particular issue for now by implementing this method based on the original.

```python
def sparse_temporal_top_k_categorical_accuracy(y_true, y_pred, k=5):
    original_shape = K.shape(y_true)
    y_true = K.reshape(y_true, (-1, K.shape(y_true)[-1]))
    y_pred = K.reshape(y_pred, (-1, K.shape(y_pred)[-1]))
    top_k = K.in_top_k(y_pred, K.cast(K.max(y_true, axis=-1), 'int32'), k)
    return K.reshape(top_k, original_shape[:-1])
```

**Comment by sbecon** [comment]
I am having the same issue.
