### ISSUE TITLE
ImageDataGenerator inherits wrong class from TF 1.11, causing fit_generator to assume it isn't a Sequence

### ISSUE THREAD

**Issue by SteffenBauer** [keras-team/keras#11452]
Tensorflow 1.11.0
Keras 2.2.4
Keras-Preprocessing 1.0.5
Ubuntu 16.04
Python 2.7.12

Example code:

```
from keras import models, layers
from keras_preprocessing.image import ImageDataGenerator
from keras_applications.imagenet_utils import preprocess_input

train_dir = '/tmp/workspace/Pet_Dataset/train/'
height, width, channels = (128, 128, 3)
batch_size=32

train_datagen = ImageDataGenerator(rescale=1.0/255)
train_generator = train_datagen.flow_from_directory(
              train_dir, target_size=(height, width),
              batch_size=batch_size, class_mode='categorical')

network = models.Sequential()
network.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(height, width, channels)))
network.add(layers.MaxPooling2D((2, 2)))
network.add(layers.Conv2D(64, (3, 3), activation='relu'))
network.add(layers.MaxPooling2D((2, 2)))
network.add(layers.Conv2D(128, (3, 3), activation='relu'))
network.add(layers.MaxPooling2D((2, 2)))
network.add(layers.Conv2D(256, (3, 3), activation='relu'))
network.add(layers.GlobalAveragePooling2D())
network.add(layers.Dense(train_generator.num_classes, activation='softmax'))

network.compile(optimizer='RMSProp',
                   loss='categorical_crossentropy',
                   metrics=['accuracy'])
network.summary()

history = network.fit_generator(train_generator, epochs=10) 
```

breaks with Tensorflow 1.11.0 with `ValueError: steps_per_epoch=None is only valid for a generator based on the keras.utils.Sequence class. Please specify steps_per_epoch or use the keras.utils.Sequence class.`. 

Tensorflow 1.10.0 and below works.

Furthermore, providing steps_per_epoch and applying multiprocessing with workers > 1:
```
history = network.fit_generator(train_generator, epochs=10, 
    steps_per_epoch=train_generator.n/batch_size,
    use_multiprocessing=True, workers=2)
```
causes a UserWarning about multiple workers duplicate data.

I think this is caused by wrong inheritance of ImageDataGenerator. 

When printing the exact class that is used in `keras_preprocessing/image.py`, I get `<class 'tensorflow.python.keras.utils.data_utils.Sequence'>`.

But `fit_generator()` checks if the generator is a subclass of `<class 'keras.utils.data_utils.Sequence'>`, so it seems to assume that the ImageDataGenerator instance is not of type Sequence, causing above problems.

**Comment by Dref360** [comment]
Could you try using : 
`from keras.preprocessing.image import ImageDataGenerator`

instead of : 
`from keras_preprocessing.image import ImageDataGenerator`

**Comment by SteffenBauer** [comment]
@Dref360: Same result:

```
Using TensorFlow backend.
Found 7200 images belonging to 2 classes.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
conv2d_1 (Conv2D)            (None, 126, 126, 32)      896       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 63, 63, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 61, 61, 64)        18496     
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 30, 30, 64)        0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 28, 28, 128)       73856     
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 14, 14, 128)       0         
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 12, 12, 256)       295168    
_________________________________________________________________
global_average_pooling2d_1 ( (None, 256)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 514       
=================================================================
Total params: 388,930
Trainable params: 388,930
Non-trainable params: 0
_________________________________________________________________
Traceback (most recent call last):
  File "./imagedatagenerator.py", line 32, in <module>
    history = network.fit_generator(train_generator, epochs=10) 
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training_generator.py", line 55, in fit_generator
    raise ValueError('`steps_per_epoch=None` is only valid for a'
ValueError: `steps_per_epoch=None` is only valid for a generator based on the `keras.utils.Sequence` class. Please specify `steps_per_epoch` or use the `keras.utils.Sequence` class.
```

**Comment by Dref360** [comment]
Between 1.10 and 1.11 this PR got merged:
https://github.com/tensorflow/tensorflow/commit/f6c3c9733ed39f14ee3c32bc51ec62315b48ad31#diff-09395f6eebca1f408ed2e91c63477511

which defines a bunch of things related to this issue.

When we debug and get inside keras.preprocessing, the Iterator type is from TF for some reason. I'll try to dig further.

**Comment by gabrieldemarmiesse** [comment]
I've never dug too much into this part of the codebase. So I don't think I can give any hindsight. If I have the time, I'll try to look into it this week. It seems like a big bug so I'll try to help as much as possible.

Just for clarify @Dref630, are you sure that the PR you are mentioning created the bug, or you think it created the bug? It's not very clear from your message and it's pretty important for later on.

**Comment by Dref360** [comment]
It's the only PR that affected tf.keras.applications and tf.keras.preprocessing between those 2 releases.

**Comment by Sebb767** [comment]
In case someone is stuck with an old version of Keras: One can avoid this issue by changing the line
`history = network.fit_generator(train_generator, epochs=10)` to `history = network.fit_generator(train_generator, steps=len(train_generator), epochs=10)`.

**Comment by nicaogr** [comment]
There is the same problem with the keras API inside Tensorflow 1.14. The tf.keras.preprocessing.image.ImageDataGenerator is not a Sequence.
