### ISSUE TITLE
load_model does not recognize pathlib

### ISSUE THREAD

**Issue by qinst64** [keras-team/keras#11459]
keras version 2.2.4 does not recognize pathlib
```
from pathlib import Path
h5filepath = ...
load_model(h5filepath) # OK
load_model(Path(h5filepath)) # ERR
```
saying `TypeError: Required Group, str or dict. Received: <class 'pathlib.WindowsPath'>.`

The previous version (2.2.2 or so) was running flawlessly: guess the type assert is now missing in the new version 2.2.4

**Comment by qinst64** [comment]
The same thing happens on `model.save`, pls also fix.

**Comment by jacquerie** [comment]
> Is anyone working on this? If not, I would like to work on it .

I already have a PR open: https://github.com/keras-team/keras/pull/11466
