### ISSUE TITLE
use fit_generator() and customize callback but error came out when using validation_data 

### ISSUE THREAD

**Issue by dayhee** [keras-team/keras#11450]
I'm using fit_generator() and custimize a callback ,but when it processing 
val_predict = (np.asarray(self.model.predict(self.validation_data[0]))).round()
here comes error
TypeError: 'NoneType' object is not subscriptable

**Comment by gabrieldemarmiesse** [comment]
You should provide a script to reproduce the issue. Otherwise, we have no way of knowing what is happening.
