### ISSUE TITLE
TypeError: softmax() got an unexpected keyword argument 'axis' 

### ISSUE THREAD

**Issue by ameicler** [keras-team/keras#11479]
As explained in [9621](https://github.com/keras-team/keras/issues/9621#issuecomment-411816766) - error is not fixed for keras-2.2.4 and tensorflow-1.4.0

Editing `tensorflow_backend.py` from `return tf.nn.softmax(x, axis=axis)` to `return tf.nn.softmax(x, axis)`  should solve it

**Comment by gabrieldemarmiesse** [comment]
Tensorflow 1.4 is now one year old. We can't support all versions of all dependencies that are required for keras. You can make a fork of `keras-team/keras` if you want to have a keras version which supports TF 1.4.

**Comment by afonsoblneto** [comment]
Great tip. It worked for me.

Thanks
