### ISSUE TITLE
Bug in masking of output in K.rnn(..., unroll=False) (for tensorflow and cntk)

### ISSUE THREAD

**Issue by andhus** [keras-team/keras#11472]
**Summary**
Outputs are not masked correctly in `tensorflow_backend.rnn(..., unroll=False)`. The issue is that `states[0]` is assumed to be equal to the `output` of the `step_function` in this [line](https://github.com/keras-team/keras/blob/master/keras/backend/tensorflow_backend.py#L2976) (not so in other backends or with `unroll=True`). This holds for the built-in RNNCells, which is the reason the bug has gone undetected. Especially since the [introduction of `output_size` in the RNNCell](https://github.com/keras-team/keras/commit/66f8cc7ac4942f7f9fe0164a2a854a6264b87735) it is clear that this should not generally be assumed.

**Implications**
1) `RNN` returns the wrong output when mask is used and the `output` is not equal to `states[0]` _but has same size_ - i.e. a **quiet error**:
```
class Cell(keras.layers.Layer):

    def __init__(self):
        self.state_size = None
        self.output_size = None
        super(Cell, self).__init__()

    def build(self, input_shape):
        self.state_size = input_shape[-1]
        self.output_size = input_shape[-1]

    def call(self, inputs, states):
        return inputs, [s + 1 for s in states]

x = Input((3, 1), name="x")
x_masked = Masking()(x)
s_0 = Input((1,), name="s_0")
y, s = recurrent.RNN(Cell(),
                     return_state=True,
                     unroll=False)(x_masked, initial_state=s_0)
model = Model([x, s_0], [y, s])
model.compile(optimizer='sgd', loss='mse')

# last time step masked
x_arr = np.array([[[1.],[2.],[0.]]])
s_0_arr = np.array([[10.]])
y_arr, s_arr = model.predict([x_arr, s_0_arr])

# 1 is added to initial state two times
assert_allclose(s_arr, s_0_arr + 2)
# expect last output to be the same as last output before masking
assert_allclose(y_arr, x_arr[:, 1, :])  # Fails!
```
Gives:
```
       AssertionError: 
       Not equal to tolerance rtol=1e-07, atol=0
       
       (mismatch 100.0%)
        x: array([12.], dtype=float32)
        y: array([2.])
```

2) Exception is raised when trying to apply an RNN with a cell which `output_size != state_size[0]`
```
class Cell(keras.layers.Layer):

    def __init__(self):
        self.state_size = None
        self.output_size = None
        super(Cell, self).__init__()

    def build(self, input_shape):
        self.state_size = input_shape[-1]
        self.output_size = input_shape[-1] * 2

    def call(self, inputs, states):
        return keras.layers.concatenate([inputs]*2), [s + 1 for s in states]

x = Input((3, 1), name="x")
x_masked = Masking()(x)
s_0 = Input((1,), name="s_0")
y, s = recurrent.RNN(Cell(),
                     return_state=True,
                     unroll=False)(x_masked, initial_state=s_0)  # Fails!
```
Gives:
```
ValueError: Dimension 1 in both shapes must be equal, but are 2 and 1. Shapes are [?,2] and [?,1]. for 'rnn_1/while/Select' (op: 'Select') with input shapes: [?,?], [?,2], [?,1].
```

**Comment by andhus** [comment]
Hi @qlzh727, since you came with the (great 👍) addition of [explicit output_size](https://github.com/keras-team/keras/pull/11021), you might want to be aware of this issue.

**Comment by andhus** [comment]
Is this only considered a "minor" bug @gabrieldemarmiesse? It quietly breaks the promise of the `RNN` api (even if it is not that well documented) and gives inconsistent behaviour depending on backend and unroll True/False. This can cause a lot of confusion.

**Comment by andhus** [comment]
As of @souptc's comment [here](https://github.com/keras-team/keras/pull/11021#issuecomment-417820320):

> My understanding is that cntk does not support multiple input/output variables, so we can't handle the case that input and state has different shape. The current "RNN" api implementation in cntk_backend is kind of compromise to Keras api, base on the assumption that the last states is the output.

I understand that we can't (there is not ambition to) solve this for cntk? But it shouldn't return the wrong output quietly?

**Comment by qlzh727** [comment]
Thanks for the notice. If the cause of the issue is that customized cell does not hold the contract of state_size[0] == output_size, shouldn't the fix be applied to those cells? Maybe a check of state_size[0] == output_size could be added before the return of call() so that the error message could be more explicit.

Also adding @fchollet here who did the original review of my PR.

**Comment by andhus** [comment]
> First of all, I don't see any reason to enforce that

I mean, why should cell/step function return `outputs` AND `states` at all if output should always be equal to `states[0]`? 

> Maybe a check of state_size[0] == output_size could be added before the return of call() so that the error message could be more explicit

Note that is not only a problem with shapes, as stated in implication 1) it is also about getting _the wrong output_ when shapes are equal - at least different output with unroll=True/False (so one must be wrong).

**Comment by qlzh727** [comment]
Sorry for the confusion. There are three items in the scope right now.

a. cell.state_size[0]
b. cell.output_size
c. Actual size for the returned tensor from the cell.call() method.

The original contract was a == c, and I introduced b in my PR to make it more explicit. We want to have a == b == c. We would prefer strict b == c, and if b is not defined, then at least a == c should hold. For any of the cell that does not even hold a == c, then those cell should be updated. We could add an more explicit error message to make this contract more clear in the call() method.

Hope this clarify my previous message.

**Comment by qlzh727** [comment]
I think the original reason to have state_size[0] == output_size is because of LSTM which has two states. For historical reason, I think most of the RNN implementation has its state same as the output, but its not necessary always True for all the cells. This is also why I added cell.output_size to make the output shape more explicit.

In the case that unroll = True/False, they should return same shape of output, regardless of the state_size/output_size.

**Comment by qlzh727** [comment]
The output content should be same given the same input/initial state when unroll = True and False. unroll flag only control how the graph is generated (eg, tf.while loop) and should not have behavior difference. If the output returns different content when toggle the unroll flag, then there must be some bug on either code path.

**Comment by andhus** [comment]
Thanks for the clarification @qlzh727, however, I'm still not sure about your position, these statements are conflicting to me:

> We want to have a == b == c. We would prefer strict b == c, and if b is not defined, then at least a == c should hold. For any of the cell that does not even hold a == c, then those cell should be updated

> I think most of the RNN implementation has its state same as the output, but its not necessary always True for all the cells. This is also why I added cell.output_size to make the output shape more explicit.

**Summary**:
1) Right now it is required that `output == states[0]` for `output, states = cell.call(inputs, states_tm1)` when using `layers.RNN` for masking to work accurately/consistently.

This "contract" _is not stated in docs_ of `layers.RNN`. In docs of `cell.state_size` it says that "(which should be the same as the _size_ of the cell output)" but nothing else. 

2) Right now it is required that `output == states[0]` for `output, states = step_function(inputs, states_tm1)` when using `K.rnn` for masking to work accurately/consistently.

Here, the "contract"  _is stated_ in the docs of `K.rnn`: "The first state in the list must be the output tensor at the previous timestep" - So strictly speaking there is not a bug in `K.rnn` but rather in `layers.RNN` or just missing docs. 

My question is: why do we need/want this contract? And why then even let the cell/step_function return `output` separately so that it is possible to break the contract? @fchollet.

If it is absolutely certain that we want this contract, then this issue can be closed with an update of documentation of `layers.RNN` (and prefereably some better verification and error messages) and some clarification of what `cell.output_size` is used for and why it can differ from `cell.state_size[0]`.

**Comment by qlzh727** [comment]
Ah, I see your point.

My intention for introduce b) is to replace the contract of a == c, so that state size can be different from output size. For any existing cell without cell.output_size defined, a == c should still hold. cell.state_size[0] is just a fallback for any existing custom cell without cell.output_size.

> This "contract" is not stated in docs of layers.RNN. In docs of cell.state_size it says that "(which should be the same as the size of the cell output)" but nothing else.

I think it might just be a doc issue but the contract should still holds. Otherwise the method for compute_output_shape probably won't be able to compute the correct shape for output tensor. In your proposal (no contract), what will be logic for compute_output_shape?

**Comment by andhus** [comment]
Please note that I'm not only/primarily talking about the contract of **shapes**, I'm talking about the **actual values** of the tensors, please read "Implication 1" in my orginal description of this issue. If the shape of `output`  is allowed to differ from shape of `states[0]` where `output, states = cell.call(inputs, states_tm1)` then it follows that there cannot be a contract saying that `output == states[0]` (again, including actual values) - in which case there is a bug **when using masks** in `layers.RNN`.

> In your proposal (no contract), what will be logic for compute_output_shape?

I suggest **no changes** in how output shape is computed. I.e. `cell.output_size` is by default `cell.state_size[0] if hasattr(self.cell.state_size, '__len__') else cell.state_size` if the `cell.output_size` is not implemented. This is not what I refer to as the "contract" this is just the reasonable "special case" to deal with backward compatibility.

The reason I really appriciate your addition of `output_size` is that there is no longer anything blocking us from removing the artifificial constraint (what I refer to as the "contract") that `output == states[0]`

**Comment by qlzh727** [comment]
Ah, Thank for the detail explanation.

I think the line in question for implication 1 is at https://github.com/keras-team/keras/blob/master/keras/backend/tensorflow_backend.py#L3055.

It uses the value from state[0] to mask the output, whereas in the unroll == True, it uses the output from previous timestep or zeros for timestep0. 

I think the proper fix is to read the output_ta_t for previous timestep or generate zeros instead of use state[0] if timestep is 0.

**Comment by andhus** [comment]
Yes, thanks, that was the fix I made in the PR I opened together with this issue ;)
