### ISSUE TITLE
Conv2DTranspose vs. tf.nn.conv2d_transpose 

### ISSUE THREAD

**Issue by getaleks** [keras-team/keras#11477]
Hi,

I am implementing a deconvolution in my project. I had used tf.nn.conv2d_transpose, but using Keras layers proved to be more efficient. I replaced tf.nn.conv2d_transpose with Keras layer Conv2dTranspose.

From the documentation they seem to do the same, however I am getting different results. Are the underlying operations the same? Has anybody already tried using both? Is there anything that has to be done different with Keras Conv2dTranspose?

Thanks.

**Comment by gabrieldemarmiesse** [comment]
You can look the implementation into `tensorflow_backend.py`

**Comment by getaleks** [comment]
Hi Gabriel,

I looked up the implementation of both functions:
https://github.com/tensorflow/tensorflow/blob/c19e29306ce1777456b2dbb3a14f511edf7883a8/tensorflow/python/ops/nn_ops.py#L1248

and

https://github.com/keras-team/keras/blob/36b9e4c055f32718a036cabaf767325b010c7485/keras/layers/convolutional.py#L847

Both call some functions in the backend, however it is my understanding that there is no way to look into these backend functions unless you build from souce?

**Comment by jvishnuvardhan** [comment]
@getaleks Could you try latest version of TF and keras and check whether the bug persists? Could you also provide  a code to reproduce the bug? Another thing is every code is open sourced, so you can look into all the codes and debug if you want. Thanks!
