### ISSUE TITLE
TimeDistributed layer with multiple inputs

### ISSUE THREAD

**Issue by Andrea-V** [keras-team/keras#11476]
Hello everbody,
I'm trying to make the following lines of code working:
`
low_encoder_out = TimeDistributed( AutoregressiveDecoder(...) )([X_tf, embeddings])
`
Where AutoregressiveDecoder is custom layer that takes two inputs.
After a bit of googling, the problem seems to be that the TimeDistributed wrapper doesn't accept multiple inputs. There are solutions that proposes to merge the two inputs before feeding it to the layer, but since their shape is
`
X_tf.shape:  (?, 16, 16, 128, 5)
embeddings.shape: (?, 16, 1024)
`
I really don't know how to merge them.
Is there a way of having the TimeDistributed layer to work with more than one input?
I think it's a quite common use case and would be nice if Keras will support multiple-inputs TimeDistributed layers in the future.

**Comment by tiamiceli** [comment]
I also have two input tensors that don't have a good way to merge. Please add this feature to TimeDistributed.
