### ISSUE TITLE
Using keras without backend

### ISSUE THREAD

**Issue by lsvih** [keras-team/keras#11483]
Hi there,

In some cases, I just want to use awesome tools in keras without any backend framework. But I notice that there are mandatory conditions to run backend in `keras/__init__.py` and `backend/__init__.py`.

Is it possible to cancel or loosen those restrictions? 

For example, allowing user to set `_BACKEND = NONE`.

**Comment by gabrieldemarmiesse** [comment]
It's not possible right now. But you can do a dummy backend and load it. To do that, you need to load an external backend. There is a PR to update the documentation to explain how to do that. See #11405
