### ISSUE TITLE
a question about ,node naming rules of model network

### ISSUE THREAD

**Issue by zkl99999** [keras-team/keras#11484]
```
from keras import backend as K
In [40]: input = K.placeholder(ndim=3,name='x')

In [41]: input
Out[41]: <tf.Tensor 'x:0' shape=(?, ?, ?) dtype=float32>

In [42]: input2 = K.placeholder(ndim=3,name='x')

In [43]: input2
Out[43]: <tf.Tensor 'x_1:0' shape=(?, ?, ?) dtype=float32>
```
the name 'x:0' and 'x_1:0', the ':0' what mean, how to change it?

**Comment by ymodak** [comment]
Hi!
This issue isn't related to a bug/enhancement/feature request or other accepted types of issue.

To ask questions, please see the following resources :

https://keras.io/
https://keras.io/#support
https://gitter.im/Keras-io/Lobby
Thanks!

If you think I made a mistake, please open another issue.
