### ISSUE TITLE
_pickle.UnpicklingError: pickle data was truncated for loading CIFAR100

### ISSUE THREAD

**Issue by nbansal90** [keras-team/keras#11503]
Hello Guys,

I am trying to load CIFAR100 using cifar100.load_data() using keras. But I am encountering an error which says:
```
Using TensorFlow backend.
Traceback (most recent call last):
  File "resnet_cifar_new100.py", line 52, in <module>
    (x_train, y_train), (x_test, y_test) = cifar100.load_data()
  File "/home/bansa01/anaconda3/envs/keras/lib/python3.6/site-packages/keras/datasets/cifar100.py", line 34, in load_data
    x_train, y_train = load_batch(fpath, label_key=label_mode + '_labels')
  File "/home/bansa01/anaconda3/envs/keras/lib/python3.6/site-packages/keras/datasets/cifar.py", line 27, in load_batch
    d = cPickle.load(f, encoding='bytes')
_pickle.UnpicklingError: pickle data was truncated
```

I have made no changes whatsoever in the respective file. And the version of Keras and Tensorflow I am using are:

```
(keras) bansa01@vita2:/ssd2/home/bansa01/resnet_final/tmp_spectral_new$ python -c 'import keras; print(keras.__version__)'
Using TensorFlow backend.
```
**2.2.4**
```
(keras) bansa01@vita2:/ssd2/home/bansa01/resnet_final/tmp_spectral_new$ python -c 'import tensorflow; print(tensorflow.__version__)'
```
**1.11.0**

Please suggest what should be done.

Regards
Nitin

**Comment by AminJun** [comment]
I have the same issue ! Using 
```bash
tensorflow==1.12.0
```

**Comment by xscharlie** [comment]
I had the same error, try with this https://stackoverflow.com/a/52496786
it worked for me.

**Comment by AayushTyagi1** [comment]
I have the same error. @xscharlie It didn't work for me. I have tried so many times. 
UnpicklingError: pickle data was truncated

**Comment by SGQ-py** [comment]
Has anyone solved it now?

**Comment by AminJun** [comment]
For me the @xscharlie did work. The issue was that the downloaded files were broken, so it couldn't load it. Erased them and downloaded them again and it worked. But I guess since it didn't work for @AayushTyagi1 , the issue still remains open.

**Comment by SGQ-py** [comment]
Thank you for your reply, it helped me.
                                              


| |
wxxd
|
|
17806259143@163.com
|
签名由网易邮箱大师定制
On 10/8/2020 21:55，AminJun<notifications@github.com> wrote：

For me the @xscharlie did work. The issue was that the downloaded files were broken, so it couldn't load it. Erased them and downloaded them again and it worked. But I guess since it didn't work for @AayushTyagi1 , the issue still remains open.
