### ISSUE TITLE
Keras 2.0 release notes is misleading

### ISSUE THREAD

**Issue by eduidl** [keras-team/keras#11517]
about https://github.com/keras-team/keras/wiki/Keras-2.0-release-notes#training

>  samples_per_epoch was renamed steps_per_epoch in fit_generator.

This description is misleading for me. This is because meaning of steps_per_epoch is totally different from of samples_per_epoch, and this is not just renaming, I think. (However, I can not propose alternative description, sorry)

**Comment by gabrieldemarmiesse** [comment]
I actually don't know if contributors can modify the wiki. Can someone try?

**Comment by gabrieldemarmiesse** [comment]
@jacquerie Can you fix this issue then? Do samples_per_epoch refers to the number of samples, the other one to the number of batches.

**Comment by DecentMakeover** [comment]
I would like to get this fixed, can i edit the wiki to say, 1.Steps per epoch refers to the number of data points in the batch ?

Any suggestions?

**Comment by vineetred** [comment]
I've just added some clarification. Let me know if it's okay? 0969a0f[](https://github.com/keras-team/keras/wiki/Keras-2.0-release-notes/0969a0ff30fa15fe632a08e465342f8732753350)

**Comment by eduidl** [comment]
It looks okay to me!

**Comment by andy6975** [comment]
Is this issue still open? I would like to work on it.

**Comment by naveen8801** [comment]
Hii , i am new to open source , can i contribute here ?
