### ISSUE TITLE
Chekpoint can not be loaded after fine tuning.

### ISSUE THREAD

**Issue by robert-fuess** [keras-team/keras#11515]
Hello,

i use the VGG16 pretrained model like this:

```
conv_base = VGG16(weights='imagenet', include_top=False, input_shape=(IMAGE_SIZE, IMAGE_SIZE, IMAGE_CHANNELS))

model = models.Sequential()
model.add(conv_base)
model.add(layers.Flatten())
model.add(layers.Dense(NEURONS, activation='relu'))
model.add(layers.Dropout(DROPOUT_FACTOR))
model.add(layers.Dense(CLASSES, activation='softmax'))
conv_base.trainable = False
```

Training, saving and loading models works fine in mode feature extraction:
`model.load_weights(CHECKPOINT)`

If i use fine-tuning and unfreeze some layer

```
model.load_weights(CHECKPOINT)
conv_base.trainable = True
set_trainable = False

        for layer in conv_base.layers:
            if layer.name == 'block5_conv1':
                set_trainable = True
            if set_trainable:
                layer.trainable = True
            else:
                layer.trainable = False
```

the training works fine but the new checkpoints can not be loaded again. The new checkpoint is not as large as the previos one.

This is the thrown exception:
 File "-----\anaconda3\lib\site-packages\keras\models.py", line 719, in load_weights
    topology.load_weights_from_hdf5_group(f, layers)
  File "-----\anaconda3\lib\site-packages\keras\engine\topology.py", line 3095, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "-----\anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 2193, in batch_set_value
    get_session().run(assign_ops, feed_dict=feed_dict)
  File "-----\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 889, in run
    run_metadata_ptr)
  File "-----\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1096, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (3, 3, 512, 512) for Tensor 'Placeholder:0', which has shape '(3, 3, 3, 64)'

What am I doing wrong?
Thank You

**Comment by gabrieldemarmiesse** [comment]
I think this is because internally, the model doesn't have the same topology if you freeze layers (variables become constants, etc...). So it's impossible to load the weights in the same manner. You can have two version of the model (one frozen and the other not) by compiling twice the same model. Then you'll be able to load whatever weights easily. You can also unfreeze, load, and freeze the model again. That should also work.
