### ISSUE TITLE
How to handle unlabelled pixels?

### ISSUE THREAD

**Issue by Mithosk93** [keras-team/keras#11528]
I've my own dataset with 2 classes and a lot of pixels don't belong to either of the classes. 
I have assigned 0 to such pixels in the label image and 1,2 to the classes. I would like to train only for labels 1,2 and not 0. 
I was wondering if there is a way, like in Caffe, to express the concept of "ignore_label" in Keras? Or there is an appropriate way to handle unlabeled pixels during the training phase?
Could be a good solution  to use one-hot class vectors with the dimension 2, (corresponding to my two classes) and for the "don't-care pixels", set all the elements in the vector to 0?

Thank you!

**Comment by gabrieldemarmiesse** [comment]
I think it needs to be coded internally in the network for that (not really difficult, just not very clean). There is a PR for that, see #10775

**Comment by Mithosk93** [comment]
Thank you so much!
So for example in a case with three classes I can pass a dictionary like this:  {0: 0, 1: 1, 2: 1}
if I want to skip the pixels of class 0?
