### ISSUE TITLE
TimeseriesGenerator object is not an iterator on Python 2.7

### ISSUE THREAD

**Issue by srigv** [keras-team/keras#11531]
hello,

I see an issue with TimeSeriesGenerator for Python 2.7 but the same code works for Python 3.6.
Here are the keras and dependencies versions that I have.

tensorflow                         1.11.0
Keras                              2.2.2
Keras-Applications                 1.0.6
Keras-Preprocessing                1.0.5

I am using the following code to test the TimeseriesGenerator 
```WINDOW_LENGTH = 4
data = np.arange(0,100).reshape(-1,1)
data_gen = TimeseriesGenerator(data, data, length=WINDOW_LENGTH,
                               sampling_rate=1, batch_size=1)


data_dim = 1
input1 = Input(shape=(WINDOW_LENGTH, data_dim))
lstm1 = LSTM(100)(input1)
hidden = Dense(20, activation='relu')(lstm1)
output = Dense(data_dim, activation='linear')(hidden)

model = Model(inputs=input1, outputs=output)
model.compile(loss='mse', optimizer='rmsprop', metrics=['accuracy'])

model.fit_generator(generator=data_gen,
                    steps_per_epoch=32,
                    epochs=10)
```
here is the stacktrace.

```
TypeErrorTraceback (most recent call last)
<ipython-input-55-ad7e35e8fffd> in <module>()
     16 model.fit_generator(generator=data_gen,
     17                     steps_per_epoch=32,
---> 18                     epochs=10)

/usr/lib/python2.7/site-packages/keras/legacy/interfaces.pyc in wrapper(*args, **kwargs)

/usr/lib/python2.7/site-packages/keras/engine/training.pyc in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)

/usr/lib/python2.7/site-packages/keras/engine/training_generator.pyc in fit_generator(model, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)

/usr/lib/python2.7/site-packages/keras/utils/data_utils.pyc in get(self)

/usr/lib/python2.7/site-packages/keras/utils/data_utils.pyc in _data_generator_task(self)

TypeError: TimeseriesGenerator object is not an iterator

```

**Comment by gabrieldemarmiesse** [comment]
Thanks for the report, it looks like a bug at first sight, but I'm not sure. Can you open the same issue in this repo? https://github.com/keras-team/keras-preprocessing. Thanks a lot.

**Comment by srigv** [comment]
Thanks! Will do. I did some more experimenting with the package update, now I see the issue with Python 3.6 too. So, I am guessing it's something to do with the package mismatch or something, I'll investigate some more and raise a bug with more details.

**Comment by maravenag** [comment]
i'm facing the same issue with python 3.6, using Keras 2.1.6

**Comment by mai-lg** [comment]
You might be importing the wrong class.
The solution, use:
from **keras.preprocessing.sequence** import TimeseriesGenerator

instead of:
from **keras_preprocessing.sequence** import TimeseriesGenerator
