### ISSUE TITLE
Image augmentation for images with two channels

### ISSUE THREAD

**Issue by jingweimo** [keras-team/keras#11538]
I performed data augmentation (with keras 2.2) for images with two channels. My data set is formatted in the shape of `(image_Numbers, image_height, image_weights, image_channels)`, where `image_channels = 2`.

In performing data augmentation using datagen (created by ImageDataGenerator), a userwarining message is generated:

```
UserWarning: NumpyArrayIterator is set to use the data format convention     
"channels_last" (channels on axis 3), 
i.e. expected either 1, 3 or 4 channels on axis 3. 
However, it was passed an array with shape (1, 150, 150, 2) (2 channels).
```

Does the warning imply the data augmentation was unsuccessful? Was it only performed for one channel images? If so, how to perform data augmentation for two-channels of images?

**Comment by celiagarcia** [comment]
I have the same question. Is anything known about it?
thanks
