### ISSUE TITLE
Getting intermediate layer output from predefined keras models

### ISSUE THREAD

**Issue by mremad** [keras-team/keras#11533]
Hi,

So I trained a MobileNet model using my custom 64x64x1 images. Now, I am trying to load the model weights and cut out the last layer from the network, and I keep getting:
AttributeError: 'Tensor' object has no attribute '_keras_shape'

stack trace:
File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/network.py", line 93, in _init_
    self._init_graph_network(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/network.py", line 253, in _init_graph_network
    input_shapes=[x._keras_shape for x in self.inputs]

here's a snippet of my code:

mobilenet = MobileNet(input_shape=(64, 64, 1,), alpha=1., weights=None, classes=340)
mobilenet.load_weights(weights_path)
mobilenet_hidden_features = Model(inputs=mobilenet.input, outputs=mobilenet.get_layer('global_average_pooling2d').output)

Am I doing something wrong?

- [X] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps`

- [X] Check that your version of TensorFlow is up-to-date. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [X] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by ymodak** [comment]
Please take a look at https://keras.io/getting-started/faq/#how-can-i-obtain-the-output-of-an-intermediate-layer to know more. Hope this helps. Thanks!
