### ISSUE TITLE
Cannot start the training

### ISSUE THREAD

**Issue by IFeelBloated** [keras-team/keras#11534]
I am trying to train a complex model with 2000+ layers on 8 GPUs with multi_gpu_model
It seems that the training could not get started, instead it got stuck like forever at "Epoch 1/xxx"
![](https://i.imgur.com/FwDlUpN.png)
seems like one CPU core is freaking out and other cores are just idle, what is happening here?
![](https://i.imgur.com/9yTkd43.png)

or more specifically, where is this thing getting stuck and how do I fix it?

**Comment by gabrieldemarmiesse** [comment]
2000+ layers is quite a lot. Especially since the model is cloned for using multiple gpus. Can you provide a script to reproduce?

**Comment by IFeelBloated** [comment]
>           2000+ layers is quite a lot. Especially since the model is cloned for using multiple gpus. Can you provide a script to reproduce?

yes, I made a script that fits on zeros to reproduce the problem
https://gist.github.com/IFeelBloated/6e85b251f66941b7eb50f987c95ce69b
