### ISSUE TITLE
how to train imagenet by keras from scratch

### ISSUE THREAD

**Issue by yao-ying** [keras-team/keras#11537]
Hi everyone.
I need train imagenet from scratch.I am a new user to keras.I found it litter material about use keras to train imagenet.
my conifguration is。
1、keras 2.20
2、tensorflow 1.9.0

Thank you!
有没哪位老铁指导下呀。本人QQ 571205937，谢谢！

**Comment by ymodak** [comment]
Hi!
This issue isn't related to a bug/enhancement/feature request or other accepted types of issue.

To ask questions, please see the following resources :

https://keras.io/
https://keras.io/#support
https://gitter.im/Keras-io/Lobby
Thanks!

If you think I made a mistake, please open another issue.
