### ISSUE TITLE
FailedPreconditionError Problem when exporting keras model to tf serving

### ISSUE THREAD

**Issue by spencerlisp** [keras-team/keras#11544]
we define  model with the keras , train with tf.train.Supervisor and export with tf.saved_model.builder.SavedModelBuilder. 
there is no problem when we used keras 2.0.6 and tensorflow 1.3
Recently we update the tensorflow version to 1.11 and keras  2.2.4, we met the FailedPreconditionError problem when call builder.add_meta_graph_and_variables()

**our export code:**
legacy_init_op = tf.group(tf.tables_initializer(),  name='legacy_init_op')
builder.**add_meta_graph_and_variables**(
                        session, [tf.saved_model.tag_constants.SERVING],
                        signature_def_map={
                            'predict_images':prediction_signature,
                            tf.saved_model.signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY: 
                            classification_signature
                        },
                        clear_devices=True,
                        main_op=legacy_init_op,
                        strip_default_attrs=True)

**and the trace log:**

FailedPreconditionError: Attempting to use uninitialized value batch_normalization_1_1/moving_mean/biased
	 [[{{node batch_normalization_1_1/moving_mean/biased_G6466}} = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:worker/replica:0/task:0/device:CPU:0", send_device="/job:worker/replica:0/task:0/device:GPU:0", send_device_incarnation=2117442821459965421, tensor_name="edge_158_batch_normalization_1_1/moving_mean/biased", _device="/job:worker/replica:0/task:0/device:GPU:0"](batch_normalization_1_1/moving_mean/biased)]]
	 [[{{node batch_normalization_88_1/moving_variance/local_step_G8661}} = _Recv[_start_time=0, client_terminated=false, recv_device="/job:worker/replica:0/task:0/device:CPU:0", send_device="/job:worker/replica:0/task:0/device:GPU:0", send_device_incarnation=2117442821459965421, tensor_name="edge_1255_batch_normalization_88_1/moving_variance/local_step", tensor_type=DT_FLOAT, _device="/job:worker/replica:0/task:0/device:CPU:0"](^save_1/ShardedFilename, ^save_1/SaveV2/tensor_names, ^save_1/SaveV2/shape_and_slices)]]

**Comment by harshini-gadige** [comment]
Closing as it is in "awaiting response" status for long time. Feel free to repost the information asked above and we will reopen. Thanks !
