### ISSUE TITLE
About the version of keras

### ISSUE THREAD

**Issue by GengXieBo** [keras-team/keras#11581]
Hello ， I want to ask if the version of keras has an impact on the results of my network operation. I wrote a residual network, adding some modules I wrote myself, with the goal of doing a second classification. But I found that when my version of keras is different, the predicted results are different. I used the same configuration on the same computer, and the weight I load is the same. Only the version of keras is different. I used keras2.2.4 and 2.1.2. So I want to ask, the different versions of keras will affect the results of my network predictions?

**Comment by gabrieldemarmiesse** [comment]
Keras doesn't break compatibility with saved models when you upgrade it. When it does, it's a bug. If you are sure that it's due to the version of keras, file a bug with a standalone python script to reproduce. Thanks!
