### ISSUE TITLE
Why? Model() API doesn't support predict_proba(), while Sequential API does.

### ISSUE THREAD

**Issue by scofield7419** [keras-team/keras#11598]
Well, I believe this to be a deficit for Keras that, **Model()** API doesn't support **predict_proba()**, while **Sequential()** API does.

It's just so normal to use the  **predict_proba()** function, whenever in **Sequential()** or **Model()**. 

Or, is it the knowledge shadow that I don't know about how to _predict prob_ with Keras by **Model()** API ? Then, anybody help to remind me the right way. ☺

**Comment by gabrieldemarmiesse** [comment]
Can you provide a minimal script ? I don't see why it would be the case since Sequential is subclassing Model.

**Comment by zshancock** [comment]
predict in the model() api by default outputs the predicted probabilities. 

To get classes from predict in model() api 

```
# single output
y_predict = model.predict(X_test) # this is a list
y_classes = y_predict.argmax(axis=-1)

# Multiple outputs
y1_predict = model.predict({'first_Input': X_test, 'second_Input': X_test})[0] # this is a list
y1_classes = y_predict.argmax(axis=-1)

y2_predict = model.predict({'first_Input': X_test, 'second_Input': X_test})[1] # this is a list
y2_classes = y_predict.argmax(axis=-1)
```
