### ISSUE TITLE
why preprocess_input of applications changes the input data?

### ISSUE THREAD

**Issue by bojone** [keras-team/keras#11591]
for example
```
from keras.applications.inception_v3 import preprocess_input
y = preprocess_input(x)
```
but the x has been change too.

I think it is unreasonable.

**Comment by gabrieldemarmiesse** [comment]
There has been a debate over this at some point in an issue or a PR. I don't remember where. My personal advice would be to include the preprocessing in the model (much more portable and less error prone).

**Comment by bojone** [comment]
i think it required a inplace=True/False at least.
