### ISSUE TITLE
_keras_shape mismatch due to difference in dimensions between state and output of custom RNN

### ISSUE THREAD

**Issue by JeroenT1** [keras-team/keras#11615]
Executing the code below demonstrates the mismatch.
MY output of my RNN is not the same size as the state of the RNN.
In my real code the output is a function(and not just a selection) of the state.

Maybe the output dimension can be passed in the kwargs? I did not find anything like that online.

This is just for demonstrating the bug (if it is a bug). Because the problem is easily fixed by taking the state as output and using a lambda layer with the selection to get the real output.

    import keras
    from keras import backend as K
    from keras.layers.recurrent import RNN
    
    #Example from https://keras.io/layers/recurrent/
    #only the last part of call is changed
    
    class MinimalRNNCell(keras.layers.Layer):
    
        def __init__(self, units, **kwargs):
            self.units = units
            self.state_size = units
            super(MinimalRNNCell, self).__init__(**kwargs)
    
        def build(self, input_shape):
            self.kernel = self.add_weight(shape=(input_shape[-1], self.units),
                                          initializer='uniform',
                                          name='kernel')
            self.recurrent_kernel = self.add_weight(
                shape=(self.units, self.units),
                initializer='uniform',
                name='recurrent_kernel')
            self.built = True

        def call(self, inputs, states):
            prev_output = states[0]
            h = K.dot(inputs, self.kernel)
            state = h + K.dot(prev_output, self.recurrent_kernel)
            output = state[:,:2]                                                    #NEW
            return output, [state]

    cell = MinimalRNNCell(5)
    x = keras.Input((None, 5))
    layer = RNN(cell,return_state=True)
    output,state = layer(x)

    print('tensorflow shape:',output.shape)
    print('keras shape:',output._keras_shape)

**Comment by gabrieldemarmiesse** [comment]
see https://keras.io/layers/recurrent/

I think you forgot to add `output_size`.

**Comment by JeroenT1** [comment]
I tried it but the result is an error:


      File ".....\Anaconda3\lib\site-packages\keras\engine\base_layer.py", line 128, in __init__
        raise TypeError('Keyword argument not understood:', kwarg)

    TypeError: ('Keyword argument not understood:', 'output_size')   

The code i used is this:

    import keras
    from keras import backend as K
    from keras.layers.recurrent import RNN,SimpleRNNCell
    import tensorflow as tf

    #Example from https://keras.io/layers/recurrent/
    #only the last part of call is changed

    class MinimalRNNCell(keras.layers.Layer):

        def __init__(self, units, **kwargs):
            self.units = units
            self.state_size = units
            super(MinimalRNNCell, self).__init__(**kwargs)

        def build(self, input_shape):
            self.kernel = self.add_weight(shape=(input_shape[-1], self.units),
                                          initializer='uniform',
                                          name='kernel')
            self.recurrent_kernel = self.add_weight(
                shape=(self.units, self.units),
                initializer='uniform',
                name='recurrent_kernel')
            self.built = True
        
        def call(self, inputs, states):
            prev_output = states[0]
            h = K.dot(inputs, self.kernel)
            state = h + K.dot(prev_output, self.recurrent_kernel)
            output = state[:,:2]     #NEW
            return output, [state]


    cell = MinimalRNNCell(5,output_size=tf.TensorShape([None,2]))
    x = keras.Input((None, 5))
    layer = RNN(cell,return_state=True)
    output,state = layer(x)
    
    print('tensorflow shape:',output.shape)
    print('keras shape:',output._keras_shape)


i'm pretty sure i have the newest versions installed.

Conda list gives this:
_ipyw_jlab_nb_ext_conf    0.1.0                    py36_0
alabaster                 0.7.12                   py36_0
anaconda-client           1.7.2                    py36_0
anaconda-navigator        1.9.2                    py36_0
anaconda-project          0.8.2                    py36_0
appdirs                   1.4.3            py36h28b3542_0
asn1crypto                0.24.0                   py36_0
astroid                   2.0.4                    py36_0
astropy                   3.0.5            py36he774522_0
atomicwrites              1.2.1                    py36_0
attrs                     18.2.0           py36h28b3542_0
automat                   0.7.0                    py36_0
babel                     2.6.0                    py36_0
backcall                  0.1.0                    py36_0
backports                 1.0                      py36_1
backports.os              0.1.1                    py36_0
backports.shutil_get_terminal_size 1.0.0                    py36_2
beautifulsoup4            4.6.3                    py36_0
bitarray                  0.8.3            py36hfa6e2cd_0
bkcharts                  0.2              py36h7e685f7_0
blas                      1.0                         mkl
blaze                     0.11.3                   py36_0
bleach                    3.0.2                    py36_0
blosc                     1.14.4               he51fdeb_0
bokeh                     1.0.1                    py36_0
boto                      2.49.0                   py36_0
bottleneck                1.2.1            py36h452e1ab_1
bzip2                     1.0.6                hfa6e2cd_5
ca-certificates           2018.03.07                    0
certifi                   2018.10.15               py36_0
cffi                      1.11.5           py36h74b6da3_1
chardet                   3.0.4                    py36_1
click                     7.0                      py36_0
cloudpickle               0.6.1                    py36_0
clyent                    1.2.2                    py36_1
colorama                  0.4.0                    py36_0
comtypes                  1.1.7                    py36_0
conda                     4.5.11                   py36_0
conda-build               3.16.2                   py36_0
conda-env                 2.6.0                h36134e3_1
console_shortcut          0.1.1                         3
constantly                15.1.0           py36h28b3542_0
contextlib2               0.5.5            py36he5d52c0_0
cryptography              2.3.1            py36h74b6da3_0
curl                      7.61.0               h7602738_0
cycler                    0.10.0           py36h009560c_0
cython                    0.29             py36ha925a31_0
cytoolz                   0.9.0.1          py36hfa6e2cd_1
dask                      0.20.0                   py36_0
dask-core                 0.20.0                   py36_0
datashape                 0.5.4                    py36_1
decorator                 4.3.0                    py36_0
defusedxml                0.5.0                    py36_1
distributed               1.24.0                   py36_0
docutils                  0.14             py36h6012d8f_0
entrypoints               0.2.3                    py36_2
et_xmlfile                1.0.1            py36h3d2d736_0
fastcache                 1.0.2            py36hfa6e2cd_2
filelock                  3.0.10                   py36_0
flask                     1.0.2                    py36_1
flask-cors                3.0.6                    py36_0
freetype                  2.9.1                ha9979f8_1
get_terminal_size         1.0.0                h38e98db_0
gevent                    1.3.7            py36he774522_1
glob2                     0.6                      py36_1
greenlet                  0.4.15           py36hfa6e2cd_0
h5py                      2.8.0            py36h3bdd7fb_2
hdf5                      1.10.2               hac2f561_1
heapdict                  1.0.0                    py36_2
html5lib                  1.0.1                    py36_0
hyperlink                 18.0.0                   py36_0
icc_rt                    2017.0.4             h97af966_0
icu                       58.2                 ha66f8fd_1
idna                      2.7                      py36_0
imageio                   2.4.1                    py36_0
imagesize                 1.1.0                    py36_0
importlib_metadata        0.6                      py36_0
incremental               17.5.0                   py36_0
intel-openmp              2019.0                      118
ipykernel                 5.1.0            py36h39e3cac_0
ipython                   7.1.1            py36h39e3cac_0
ipython_genutils          0.2.0            py36h3c5d0ee_0
ipywidgets                7.4.2                    py36_0
isort                     4.3.4                    py36_0
itsdangerous              1.1.0                    py36_0
jdcal                     1.4                      py36_0
jedi                      0.13.1                   py36_0
jinja2                    2.10                     py36_0
jpeg                      9b                   hb83a4c4_2
jsonschema                2.6.0            py36h7636477_0
jupyter                   1.0.0                    py36_7
jupyter_client            5.2.3                    py36_0
jupyter_console           6.0.0                    py36_0
jupyter_core              4.4.0                    py36_0
jupyterlab                0.35.3                   py36_0
jupyterlab_launcher       0.13.1                   py36_0
jupyterlab_server         0.2.0                    py36_0
Keras                     2.2.4                     <pip>
Keras-Applications        1.0.6                     <pip>
Keras-Preprocessing       1.0.5                     <pip>
keyring                   16.0.0                   py36_0
kiwisolver                1.0.1            py36h6538335_0
lazy-object-proxy         1.3.1            py36hfa6e2cd_2
libarchive                3.3.3                h798a506_1
libcurl                   7.61.0               h7602738_0
libiconv                  1.15                 h1df5818_7
libpng                    1.6.34               h79bbb47_0
libsodium                 1.0.16               h9d3ae62_0
libssh2                   1.8.0                hd619d38_4
libtiff                   4.0.9                h36446d0_2
libxml2                   2.9.8                hadb2253_1
libxslt                   1.1.32               hf6f1972_0
llvmlite                  0.25.0                   py36_0
locket                    0.2.0            py36hfed976d_1
lxml                      4.2.5            py36hef2cd61_0
lz4-c                     1.8.1.2              h2fa13f4_0
lzo                       2.10                 h6df0209_2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markupsafe                1.0              py36hfa6e2cd_1
matplotlib                3.0.0            py36hd159220_0
mccabe                    0.6.1                    py36_1
menuinst                  1.4.14           py36hfa6e2cd_0
mistune                   0.8.4            py36he774522_0
mkl                       2019.0                      118
mkl-service               1.1.2            py36hb217b18_5
mkl_fft                   1.0.6            py36hdbbee80_0
mkl_random                1.0.1            py36h77b88f5_1
more-itertools            4.3.0                    py36_0
mpmath                    1.0.0                    py36_2
msgpack-python            0.5.6            py36he980bc4_1
msys2-conda-epoch         20160418                      1
multipledispatch          0.6.0                    py36_0
navigator-updater         0.2.1                    py36_0
nbconvert                 5.4.0                    py36_1
nbformat                  4.4.0            py36h3a5bc1b_0
networkx                  2.2                      py36_1
nltk                      3.3.0                    py36_0
nose                      1.3.7                    py36_2
notebook                  5.7.0                    py36_0
numba                     0.40.0           py36hf9181ef_0
numexpr                   2.6.8            py36h9ef55f4_0
numpy                     1.15.4           py36ha559c80_0
numpy-base                1.15.4           py36h8128ebf_0
numpydoc                  0.8.0                    py36_0
odo                       0.5.1            py36h7560279_0
olefile                   0.46                     py36_0
openpyxl                  2.5.9                    py36_0
openssl                   1.0.2p               hfa6e2cd_0
packaging                 18.0                     py36_0
pandas                    0.23.4           py36h830ac7b_0
pandoc                    1.19.2.1             hb2460c7_1
pandocfilters             1.4.2                    py36_1
parso                     0.3.1                    py36_0
partd                     0.3.9                    py36_0
path.py                   11.5.0                   py36_0
pathlib2                  2.3.2                    py36_0
patsy                     0.5.1                    py36_0
pep8                      1.7.1                    py36_0
pickleshare               0.7.5                    py36_0
pillow                    5.3.0            py36hdc69c19_0
pip                       18.1                      <pip>
pip                       18.1                     py36_0
pkginfo                   1.4.2                    py36_1
pluggy                    0.8.0                    py36_0
ply                       3.11                     py36_0
prometheus_client         0.4.2                    py36_0
prompt_toolkit            2.0.7                    py36_0
psutil                    5.4.8            py36he774522_0
py                        1.7.0                    py36_0
pyasn1                    0.4.4            py36h28b3542_0
pyasn1-modules            0.2.2                    py36_0
pycodestyle               2.4.0                    py36_0
pycosat                   0.6.3            py36hfa6e2cd_0
pycparser                 2.19                     py36_0
pycrypto                  2.6.1            py36hfa6e2cd_9
pycurl                    7.43.0.2         py36h74b6da3_0
pyflakes                  2.0.0                    py36_0
pygments                  2.2.0            py36hb010967_0
pyhamcrest                1.9.0                    py36_2
pylint                    2.1.1                    py36_0
pyodbc                    4.0.24           py36h6538335_0
pyopenssl                 18.0.0                   py36_0
pyparsing                 2.3.0                    py36_0
pyqt                      5.9.2            py36h6538335_2
pysocks                   1.6.8                    py36_0
pytables                  3.4.4            py36he6f6034_0
pytest                    3.10.0                   py36_0
pytest-arraydiff          0.2              py36h39e3cac_0
pytest-astropy            0.4.0                    py36_0
pytest-doctestplus        0.1.3                    py36_0
pytest-openfiles          0.3.0                    py36_0
pytest-remotedata         0.3.1                    py36_0
python                    3.6.6                hea74fb7_0
python-dateutil           2.7.5                    py36_0
python-libarchive-c       2.8                      py36_6
pytz                      2018.7                   py36_0
pywavelets                1.0.1            py36h8c2d366_0
pywin32                   223              py36hfa6e2cd_1
pywinpty                  0.5.4                    py36_0
pyyaml                    3.13             py36hfa6e2cd_0
pyzmq                     17.1.2           py36hfa6e2cd_0
qt                        5.9.6            vc14h1e9a669_2  [vc14]
qtawesome                 0.5.2                    py36_0
qtconsole                 4.4.2                    py36_0
qtpy                      1.5.2                    py36_0
requests                  2.20.0                   py36_0
rope                      0.11.0                   py36_0
ruamel_yaml               0.15.46          py36hfa6e2cd_0
scikit-image              0.14.0           py36h6538335_1
scikit-learn              0.20.0           py36heebcf9a_1
scipy                     1.1.0            py36h4f6bf74_1
seaborn                   0.9.0                    py36_0
send2trash                1.5.0                    py36_0
service_identity          17.0.0           py36h28b3542_0
setuptools                40.5.0                   py36_0
simplegeneric             0.8.1                    py36_2
singledispatch            3.4.0.3          py36h17d0c80_0
sip                       4.19.8           py36h6538335_0
six                       1.11.0                   py36_1
snappy                    1.1.7                h777316e_3
snowballstemmer           1.2.1            py36h763602f_0
sortedcollections         1.0.1                    py36_0
sortedcontainers          2.0.5                    py36_0
sphinx                    1.8.1                    py36_0
sphinxcontrib             1.0                      py36_1
sphinxcontrib-websupport  1.1.0                    py36_1
spyder                    3.3.1                    py36_1
spyder-kernels            0.2.6                    py36_0
sqlalchemy                1.2.13           py36he774522_0
sqlite                    3.24.0               h7602738_0
statsmodels               0.9.0            py36h452e1ab_0
sympy                     1.3                      py36_0
tblib                     1.3.2            py36h30f5020_0
terminado                 0.8.1                    py36_1
testpath                  0.4.2                    py36_0
tk                        8.6.8                hfa6e2cd_0
toolz                     0.9.0                    py36_0
tornado                   5.1.1            py36hfa6e2cd_0
tqdm                      4.28.1           py36h28b3542_0
traitlets                 4.3.2            py36h096827d_0
twisted                   18.9.0           py36he774522_0
typed-ast                 1.1.0            py36hfa6e2cd_0
unicodecsv                0.14.1           py36h6450c06_0
urllib3                   1.23                     py36_0
vc                        14.1                 h0510ff6_4
virtualenv                16.1.0                    <pip>
vs2015_runtime            14.15.26706          h3a45250_0
wcwidth                   0.1.7            py36h3d5aa90_0
webencodings              0.5.1                    py36_1
werkzeug                  0.14.1                   py36_0
wheel                     0.32.2                   py36_0
widgetsnbextension        3.4.2                    py36_0
win_inet_pton             1.0.1                    py36_1
win_unicode_console       0.5              py36hcdbd4b5_0
wincertstore              0.2              py36h7fe50ca_0
winpty                    0.4.3                         4
wrapt                     1.10.11          py36hfa6e2cd_2
xlrd                      1.1.0                    py36_1
xlsxwriter                1.1.2                    py36_0
xlwings                   0.14.0                   py36_0
xlwt                      1.3.0            py36h1a4751e_0
xz                        5.2.4                h2fa13f4_4
yaml                      0.1.7                hc54c509_2
zeromq                    4.2.5                he025d50_1
zict                      0.1.3                    py36_0
zlib                      1.2.11               h8395fce_2
zope                      1.0                      py36_1
zope.interface            4.6.0            py36he774522_0
zstd                      1.3.3                hfe6a214_0
