### ISSUE TITLE
How do I feed output of an attention block to the input of a decoder?

### ISSUE THREAD

**Issue by bhawmik** [keras-team/keras#11614]
I am trying to create an Seq2Seq translation model with attention in Keras. 

This is what I am trying to implement. 

encoder_input -> ENCODER -> encoder_output, state_h
decoder_input, state_h, context_vector - > DECODER -> decoder_output 
encoder_output, decoder_output -> ATTENTION -> context_vector 

As you can see, the context_vector is not defined until I define the ATTENTION block. 

How do I define the model and train? 

(Trying teacher enforcing training)

**Comment by harshini-gadige** [comment]
Hi

This issue isn't related to a bug/enhancement/feature-request or other accepted types of issue.

To ask questions, please see the following resources :

https://keras.io/
https://keras.io/#support
https://gitter.im/Keras-io/Lobby

Thanks!
