### ISSUE TITLE
Extra Flexibility 

### ISSUE THREAD

**Issue by slerman12** [keras-team/keras#11620]
Keras could potentially supplant all other NN frameworks with just a little extra flexibility. Of all deep learning domains, reinforcement learning is the most tricky because in addition to training once every episode, model updates happen from experiences throughout an episode. These updates may involve modifying internal states which in turn might affect the training routine.

It's confusing - first the model needs to have some method for passing updates to internal configurations such as layer-specific states/variables without training or necessarily feeding forward. Second, the fit function needs access to these variables as well and be customizable by users.

For instance, imagine using model variables for your RL experience replay. In that case, these variables would have to be assigned new values with every new experience. Furthermore, the fit function would not take as input _anything_ in this case, since training would draw directly from the experiences saved in the internal experience replay.

(This example is unlikely in practice, but it's a straightforward example that relates to other RL needs). 

Keras is so close to affording the level of flexibility needed to overtake any other library. My suggestion, humbly, is that layers be equipped with a kind of `layer.update()` function that can be defined in custom subclassed layers. The idea is to enable easy access to internal states such that modifications to the model via `model.get_layer("name").update(args)` can be made outside of training. I believe this is already possible, though maybe not in a pretty way. Secondly, and more importantly, a more flexible `fit()` function  is needed, one that can be customized by a user. In the experience replay example, no input would even need be passed into this function in order to train the model; the training would just depend on internally stored variables. 

Keras is the most accessible and clean framework for composable/modular deep learning. RL is in desperate need for such a framework. (Although Sonnet might be great, it's documentation is still severely lacking). I hope the amazing team at Keras could consider these suggestions.

**Comment by gabrieldemarmiesse** [comment]
Thanks for the recommendations. We are open to API changes if you want to push your use case. Please make a google docs explaining what functions/methods you propose and we'll review it. See https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md#pull-requests for the whole process.
