### ISSUE TITLE
Wrong shape inference for internal state in a Feed Forward NN

### ISSUE THREAD

**Issue by LuCeHe** [keras-team/keras#11633]
With the purpose of initializing a learnable internal state for a feed forward NN I define a layer like follows

```python
class InternalStateInitializer(Layer):
    def __init__(self, d_dim, **kwargs):        
        super(InternalStateInitializer, self).__init__(**kwargs)
        self.d_dim = d_dim

    def build(self, input_shape):
        
        initial_internal_d_value = np.random.uniform(0, 1, size=[self.d_dim])
        self.i_d   = K.variable(initial_internal_d_value)

        self.trainable_weights = [self.i_d]
        super(InternalStateInitializer, self).build(input_shape)  
  
    def call(self, inputs, mask=None):
        batchSize = K.shape(inputs)[0]
        
        zeros = K.zeros((batchSize, self.d_dim))
        i_d = K.bias_add(zeros, self.i_d, data_format=None)  
        
        print(K.int_shape(i_d))
        
        return i_d  
  
    def get_output_shape_for(self, input_shape):
        return self.d_dim
```

The problem is, when I do the `print(K.int_shape(i_d))` inside the call, it gives (None, 2) if I chose d_dim = 2, but when I `print(K.int_shape(i_d))` right after that layer has been called in the model, what I get is (None, None). That implies a chain of problems in a larger network where the tensors need to go through some assertions.

What is it that I am missing? Here the minimal example that reproduces the problem:

``` python
d = 3

inputs_questions = Input(shape=(None,), name='question')
c = InternalStateInitializer(d_dim = d)(inputs_questions)
print('c:                      ', K.shape(c))
print('c:                      ', K.int_shape(c))    
model = Model(inputs_questions, c)
```

Now I understand that is copying the shape of inputs_questions, since when `inputs_questions = Input(shape=(20,), name='question')` it gives `K.int_shape(c) = (None, 20)` when I want `K.int_shape(c) = (None, 3)`. @carmelrabinov @fchollet @farizrahman4u @andhus @Dref360 @bstriner ?

**Comment by gabrieldemarmiesse** [comment]
I think the output of `get_output_shape_for` is supposed to be a tuple.
