### ISSUE TITLE
InvalidArgumentError when calling model as layer with ConvLSTM2D

### ISSUE THREAD

**Issue by baiztencale** [keras-team/keras#11647]
Hey guys,

I have problems when I call a model that contains a ConvLSTM2D layer. The code works fine when I do not hand over the initial states for the ConvLSTM2D layer, but when I do I get an `InvalidArgumentError` error. 
Here is an minimal example to reproduce the error:

```
import keras.backend as K
from keras.layers import Input, ConvLSTM2D
from keras.models import Model
import numpy as np

# create actual network
network_input = Input(batch_shape=(1, 1, 3, 3, 1), dtype='float32', name='network_input')
initial_state_1 = Input(batch_shape=(1, 3, 3, 1), dtype='float32', name='initial_state_1')
initial_state_2 = Input(batch_shape=(1, 3, 3, 1), dtype='float32', name='initial_state_2')
conv_lstm_out = ConvLSTM2D(filters=1,
                            kernel_size=(2, 2),
                            padding='same',
                            return_sequences=True,
		            #stateful=True)(network_input) # with this line instead the code works
                            stateful=True)([network_input, initial_state_1, initial_state_2])
main_network = Model([network_input, initial_state_1, initial_state_2], conv_lstm_out)

# create input placeholders and call network as layer
net_input = K.placeholder(shape=(1, 1, 3, 3, 1), name='net_input')
net_states_1 = K.placeholder(shape=(1, 3, 3, 1), name='net_states_1')
net_states_2 = K.placeholder(shape=(1, 3, 3, 1), name='net_states_2')
network_op = main_network([net_input, net_states_1, net_states_2])

# create output function to run 'network_op'
predict_function = K.function([net_input, net_states_1, net_states_2], [network_op])

# create input data
net_input_data = np.arange(9, dtype=np.float32).reshape([1, 1, 3, 3, 1])
net_states_1_data = np.arange(9, dtype=np.float32).reshape([1, 3, 3, 1])
net_states_2_data = np.arange(9, dtype=np.float32).reshape([1, 3, 3, 1])

# run output functions (here the error occures)
net_output = predict_function([net_input_data, net_states_1_data, net_states_2_data])[0]
print('output', np.squeeze(net_output))
```

The exception that is thrown is:
`tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'initial_state_2' with dtype float and shape [1,3,3,1]
[[{{node initial_state_2}} = Placeholder[dtype=DT_FLOAT, shape=[1,3,3,1], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
`

Does anyone knows a fix to this? Is this a bug in keras itself or in my code?

Keras: 2.2.4
TensorFlow: 1.12.0

PS:
In general, if you want to pass the initial states to a ConvLSTM2D layer as symbolic tensors you need to uncomment the first two lines in `__call__` method of class `ConvRNN2D(RNN)` in  keras/layers/convolutional_recurrent.py so that the code looks as following:

```
def __call__(self, inputs, initial_state=None, constants=None, **kwargs):
        #inputs, initial_state, constants = _standardize_args(
        #    inputs, initial_state, constants, self._num_constants)
```

See [#9761](https://github.com/keras-team/keras/issues/9761#issuecomment-381058540) for more information.

**Comment by luochuyao** [comment]
I also meet this bug and cannot feed state as initial_state even using reset_state() or the parameter of initial_state. There is _standardize_args() should be passed at least twice when Using ConvLSTM2D. I find the initial_state would  get the value from input as the following code at first _standardize_args() because the type of initial_state is a list . 

    if isinstance(inputs, list):
        assert initial_state is None and constants is None
        if num_constants is not None:
            constants = inputs[-num_constants:]
            inputs = inputs[:-num_constants]
        if len(inputs) > 1:
            initial_state = inputs[1:]
        inputs = inputs[0]

But at second _standardize_args() , the type of inputs is still list and the inital_state is not None because it has been get value at first _standardize_args(). then  isinstance(inputs, list) is True but the initial_state  is not None. I guess this is the reason that the assert is error

**Comment by luochuyao** [comment]
I modify source code : 'output = super(RNN, self).__call__(full_input, **kwargs)' to replace 'output = super(ConvRNN2D, self).__call__(full_input, **kwargs)'  at keras.layer.convolutional_recurrent.py 321th line so that it can run without any error information.
