### ISSUE TITLE
QoL Request: Add a way to suppress the "on_batch_end() is slow" warning

### ISSUE THREAD

**Issue by kieran-lemayai** [keras-team/keras#11655]
- [x ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [x ] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

-------------------

I'm essentially running into the same "issue" as #2603 - I'm training a relatively small model on very small batches, so the update is basically instant, and flushing metrics to stdout+file is relatively large. The "problem" is that this is deliberate behavior, but I still get these lengthy warning messages cluttering my console.

I'd like to be able to suppress these warnings, without suppressing any other potentially useful warning messages. If there's already a way to do this, or if it's not too much trouble to slip in that behaviour, that would be *amazing*.

Thank you!

**Comment by gabrieldemarmiesse** [comment]
Would this work for you? https://docs.python.org/3/library/warnings.html#temporarily-suppressing-warnings

**Comment by kieran-lemayai** [comment]
No, but the related documentation does. Sorry to bother you.
