### ISSUE TITLE
Deactivating keras pyenv virtual enviornment 

### ISSUE THREAD

**Issue by sbhakat** [keras-team/keras#11666]
I installed keras using the steps mentioned by @purificant in this thread https://github.com/keras-team/keras/issues/11628

Which is like following:
```
pyenv virtualenv 3.6.7 keras-test
pyenv local keras-test
pip install keras tensorflow
echo 'from keras.callbacks import TensorBoard, ModelCheckpoint' > test.py

$ python test.py 
Using TensorFlow backend.
```

However now I can't deactivate the virtual environment. This issue was also posted here https://github.com/pyenv/pyenv-virtualenv/issues/289

Any help will be highly appreciated.

**Comment by purificant** [comment]
@sbhakat pyenv automatically activates / deactivates the virtual environment when you enter / leave the `keras-test` folder. See docs: https://github.com/pyenv/pyenv-virtualenv#activate-virtualenv

You can also deactivate manually with `pyenv deactivate` command.

**Comment by ymodak** [comment]
Closing this issue since solution is provided above. Please feel free to reopen the issue if the problem still persists. Thanks!
