### ISSUE TITLE
could keras.REAHPE function support  unknown size; I just need to reshape a tensor (M * N) to (1， M *N),  neither of M or N is fixed

### ISSUE THREAD

**Issue by Intsigstephon** [keras-team/keras#11686]
Please make sure that the boxes below are checked before you submit your issue.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.

Thank you!

- [ ] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps`

- [ ] Check that your version of TensorFlow is up-to-date. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by Intsigstephon** [comment]
code below: 
         **keras: m = Reshape((1, -1, 512))(m)**
but the tensor m's shape is not fixed.  network structure is a little bit like FCN

**Comment by pachpandepriti** [comment]
@Intsigstephon Did you solve this issue?
