### ISSUE TITLE
when will keras support python 3.7

### ISSUE THREAD

**Issue by enlighter** [keras-team/keras#11690]
Please make sure that the boxes below are checked before you submit your issue.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.

Thank you!

- [ ] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps`

- [ ] Check that your version of TensorFlow is up-to-date. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

The documentation mentions that Keras is compatible with Python 2.7-3.6. When will Keras support Python 3.7?

**Comment by gabrieldemarmiesse** [comment]
keras is compatible with 3.7 as far as I know. It's just that we don't test against 3.7 yet. You can try and report bugs if you see some! I'm not sure tensorflow supports 3.7 though. But we can't really fix that.

**Comment by enlighter** [comment]
@GabrielBianconi  In that case, the documentation should be updated to reflect that. `Python 2.7-3.6` -> `Python 2.7-3.7`

**Comment by gabrieldemarmiesse** [comment]
We can't put it in the documentation because we don't test against 3.7. So
we have no way to garantee it's going to work. You can think of it like
that: the support for 3.6 is official while the support for 3.7 is not.

**Comment by fchollet** [comment]
I think we should upgrade the test suite to 3.7 (and then update the docs too), since it is fairly mature now and quite a few people are using this Python version. There are good guarantees that code that can run on 3.7 can also run on 3.6, but the reverse isn't true.

What do you think @gabrieldemarmiesse ?

**Comment by gabrieldemarmiesse** [comment]
I think the main pain point is that tensorflow on pypi doesn't support python 3.7.

**Comment by fchollet** [comment]
Good point, let me see what the timeline for support is in TF.

**Comment by brandonschabell** [comment]
@fchollet TensorFlow supports 3.7 now, but CNTK does not. The CNTK developers also do not appear to be responding to inquiries regarding Python 3.7 support: https://github.com/Microsoft/CNTK/issues/3522.

I had created a PR for adding Python 3.7 support, but the tests fail when attempting to install CNTK on a Python 3.7 container.

**Comment by tjrileywisc** [comment]
I wouldn't hold your breath for CNTK to adopt python 3.7 anytime soon, looks like there are no plans for major changes anymore after their most recent update:

https://github.com/Microsoft/CNTK#disclaimer

**Comment by anubha17pearl** [comment]
I would like to run MobileNetV3 model for my application. I have python 3.7 supported. Which versions of keras, tensorflow and tensorflow-gpu are required to run the code. newest versions have some compatibility issue
