### ISSUE TITLE
Custom augmentation for ImageDataGenerator 

### ISSUE THREAD

**Issue by shbsafi** [keras-team/keras#11691]
Are there any plans to add a custom augmentation to the imagedatagenerator? If we define an augmentation as a function and pass it to the imagedatagenerator. Right now, If we want to add new augmentation, one is way to change the image.py as described in this artilce and kind of create our own custom generator:

https://towardsdatascience.com/image-augmentation-for-deep-learning-using-keras-and-histogram-equalization-9329f6ae5085

```
def equalize_histogram(x):
    x_processed = do something here.
    return x_processed 
```

`imagegen = ImageDataGenerator(custom_aug = equalize_histogram)`

**Comment by gabrieldemarmiesse** [comment]
Can you open this issue in keras-team/keras-preprocessing? Thanks!
