### ISSUE TITLE
LSTM inputs shape for data with multiple time series 

### ISSUE THREAD

**Issue by SoufianeDataFan** [keras-team/keras#11695]
I know this question is asked many times, but I'm getting really tripped up on the input / output for LSTM. 

```
x_train.shape  # (5523000, 13) & (13 timeseries of length 5523000)

y_train.shape #  (5523000, 1)  & number of classes == 2

```
To reshape the x_train and y_train:

```
x_train= x_train.values.reshape(27615,200,13)  # 5523000/200 = 27615
y_train= y_train.values.reshape((5523000,1))   # I know I have a problem here but I dont know how to fix it
```
Here is my lstm network :
```
def lstm_baseline(x_train, y_train):
    batch_size=200
    model = Sequential()
    model.add(LSTM(batch_size, input_shape=(27615,200,13),
                   activation='relu', return_sequences=True))
    model.add(Dropout(0.2))

    model.add(LSTM(128, activation='relu'))
    model.add(Dropout(0.1))

    model.add(Dense(32, activation='relu'))
    model.add(Dropout(0.2))

    model.add(Dense(1, activation='softmax'))

    model.compile(
        loss='categorical_crossentropy',
        optimizer='rmsprop',
        metrics=['accuracy'])

    model.fit(x_train,y_train, epochs= 15)

    return model
```
Whenever I run the code I get this error :

ValueError: Input 0 is incompatible with layer lstm_10: expected ndim=3, found ndim=4

- **My question is what I am missing here?**

PS :

 Here is [ a sample of my data](https://drive.google.com/file/d/1L5DmoCUNs7cBb_3wEeqDjoMSRxDYt8Ui/view) only first 2000 rows.

Thank you !

**Comment by DaemonHell** [comment]
1.
>input_shape=(27615,200,13)
This line is wrong - keras do not expect the number of samples here. So just omit it.
2. Your input and output shapes do not match - LSTM will produce exactly as many steps as you fed to it - 200 in this network, so your output should probably be resized to (27615,200,1)
3. Using softmax with one output does not make any sense - output will be always equal to 1. You should either use 2 outputs and hot encode your data or consider different activation (probably sigmoid)

 One more thing to consider - is 200 steps enough for your problem? If your sequence is **really** long - you should probably look into stateful networks.
