### ISSUE TITLE
Wrong definition of secs/step in Keras progress bar?

### ISSUE THREAD

**Issue by jimmy15923** [keras-team/keras#11706]
I was trying to get the images/sec from  training Keras model.
```python
import numpy as np
import tensorflow as tf

x = np.random.randint(0, 1, size=(512, 224, 224, 3))
y = np.random.randint(0, 1000, size=512)
y = tf.keras.utils.to_categorical(y, 1000)

model = tf.keras.applications.resnet50.ResNet50(input_shape=(224, 224, 3), weights=None)
model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.Adam())

res = model.fit(x, y, batch_size=128, epochs=10)
```

As code above, I used 128 batch size to fit into model. So there should be 4 steps to complete one epochs. To the best of my knowledge, one step means update weights by one batch of data. But figure below shows that one step only cost **5ms**, which means the training speed of my model is  (128 / 0.005) images/sec = 25,600 images/sec (unreasonable number). 
The model takes about 3 sec to finish an epoch, so the time/step should be 3/4 = 0.75s?

It looks like **5ms / step** represent that an image took 5ms to train. Is that correct?

![image](https://user-images.githubusercontent.com/20395242/48886572-6d718b00-ee67-11e8-83bf-f3c331aea83a.png)

**Comment by msymp** [comment]
Hello @jimmy15923 ,
Batch size of 128 (images/step), and if N is total number of images, 
[Steps per Epoch] S = N / 128
Except for first epoch: .005 sec / Step ; 3 sec / Epoch (approx)
3000/5 Step per Epoch = 600 Steps per Epoch (approx)
N = 600 x 128 images trained over 10 Epochs (approx)
Training speed = 600 x 128 / 10 x 3 = 20 x 128 = **_2560 images/sec (approx)_**
