### ISSUE TITLE
Keras breaks tensorflow installation

### ISSUE THREAD

**Issue by isaacgg** [keras-team/keras#11704]
I have just installed the last version of Keras with conda like this.  

`(machine_learning) C:\Users\isaac>conda install -c anaconda keras
Solving environment: done

## Package Plan ##

  environment location: D:\Programs\Anaconda3\envs\machine_learning

  added / updated specs:
    - keras

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    numpy-base-1.15.4          |   py36h8128ebf_0         3.9 MB  anaconda
    tensorboard-1.12.0         |   py36he025d50_0         3.1 MB  anaconda
    keras-2.2.4                |                0           5 KB  anaconda
    tensorflow-base-1.12.0     |gpu_py36h6e53903_0       180.8 MB  anaconda
    yaml-0.1.7                 |       hc54c509_2         103 KB  anaconda
    numpy-1.15.4               |   py36ha559c80_0          36 KB  anaconda
    pyyaml-3.13                |   py36hfa6e2cd_0         148 KB  anaconda
    keras-preprocessing-1.0.5  |           py36_0          52 KB  anaconda
    h5py-2.8.0                 |   py36h3bdd7fb_2         835 KB  anaconda
    tensorflow-1.12.0          |gpu_py36ha5f9131_0           4 KB  anaconda
    mkl_random-1.0.1           |   py36h77b88f5_1         268 KB  anaconda
    keras-base-2.2.4           |           py36_0         458 KB  anaconda
    keras-applications-1.0.6   |           py36_0          49 KB  anaconda
    scipy-1.1.0                |   py36h4f6bf74_1        13.6 MB  anaconda
    mkl_fft-1.0.6              |   py36hdbbee80_0         120 KB  anaconda
    ------------------------------------------------------------
                                           Total:       203.4 MB

The following NEW packages will be INSTALLED:

    keras:               2.2.4-0                   anaconda
    keras-base:          2.2.4-py36_0              anaconda
    pyyaml:              3.13-py36hfa6e2cd_0       anaconda
    yaml:                0.1.7-hc54c509_2          anaconda

The following packages will be UPDATED:

    h5py:                2.8.0-py36h3bdd7fb_2                  --> 2.8.0-py36h3bdd7fb_2      anaconda
    keras-applications:  1.0.6-py36_0                          --> 1.0.6-py36_0              anaconda
    keras-preprocessing: 1.0.5-py36_0                          --> 1.0.5-py36_0              anaconda
    mkl_fft:             1.0.6-py36hdbbee80_0                  --> 1.0.6-py36hdbbee80_0      anaconda
    mkl_random:          1.0.1-py36h77b88f5_1                  --> 1.0.1-py36h77b88f5_1      anaconda
    numpy:               1.15.4-py36ha559c80_0                 --> 1.15.4-py36ha559c80_0     anaconda
    numpy-base:          1.15.4-py36h8128ebf_0                 --> 1.15.4-py36h8128ebf_0     anaconda
    scipy:               1.1.0-py36h4f6bf74_1                  --> 1.1.0-py36h4f6bf74_1      anaconda
    tensorboard:         1.11.0-py36he025d50_0                 --> 1.12.0-py36he025d50_0     anaconda
    tensorflow:          1.11.0-gpu_py36h5dc63e2_0             --> 1.12.0-gpu_py36ha5f9131_0 anaconda
    tensorflow-base:     1.11.0-gpu_py36h6e53903_0             --> 1.12.0-gpu_py36h6e53903_0 anaconda

The following packages will be DOWNGRADED:

    ca-certificates:     2018.10.15-ha4d7672_0     conda-forge --> 2018.03.07-0              anaconda
    certifi:             2018.10.15-py36_1000      conda-forge --> 2018.10.15-py36_0         anaconda
    openssl:             1.0.2p-hfa6e2cd_1001      conda-forge --> 1.0.2p-hfa6e2cd_0         anaconda

Proceed ([y]/n)? y`

After that Keras is unusable as so is tensorflow, even if I go back to my previous tf version (1.11) and uninstall keras. Tensorflow still unusable, I always get this error.

`TypeError: descriptor '_fields' for 'OpDef' objects doesn't apply to 'OpDef' object`

just when creating an Input like  `Input(shape=(None, None, 26))` or with a placeholder in tf

EDIT: Seems like it is solved after a kernel restart. You can close this issue

**Comment by ymodak** [comment]
Closing this issue since its solved. Feel free to reopen if the issue still persists. Thanks!
