### ISSUE TITLE
How to create a tensor without knowing shape upfront in Keras/TF?

### ISSUE THREAD

**Issue by ParikhKadam** [keras-team/keras#11711]
I am currently stuck at a problem. I need to create a temporary variable (of tensor type) for holding values when my custom layer is processing the input. The problem is, the layer gets its inputs in a batch. Batch size is variable. Also, one other dimension of the input is variable which will be provided at the time of running the model.

So, how can I create a tensor of variable dimension every time for a new input. Surely there is a way to do this because built-in layers also take input as a batch whose size is variable and also the shape of output tensor varies as it outputs the whole processed batch. But I don't know how to do it.

Here's the piece of my code:

```
similarity_matrix = K.zeros(shape=(int_shape(context_vectors)[0], int_shape(context_vectors)[1], int_shape(query_vectors)[1]), dtype='float32')
for i, context_vector in enumerate(modified_context_vectors):
    for j, query_vector in enumerate(modified_query_vectors):
        concatenated_vector = concatenate_and_multiply(context_vector, query_vector)
        result = dot(concatenated_vector, self.kernel)
        similarity_matrix[:, i, j] = result
return similarity_matrix
```

Here, context_vectors and query_vectors are of shape (None, None, 600). The first dimension is batch_size which is same for both. The second dimension is the number of words in context and query and hence will differ for both.

The problem in the code is, K.zeros() throws an error which says that it cannot work with 'None' in the shape.

**Comment by ParikhKadam** [comment]
I am calculating a similarity count between words in context and words in query. So, if there are m words in context and n words in query, it should return a matrix of size m*n. The cell ij indicates the similarity between ith context word and jth query word.

My inputs are context and query vectors. Context vector is of the shape (batch_size=None, number_of_words_in_context=None, vector_of_each_word=600). Query vector is of the shape (batch_size=None, number_of_words_in_query=None, vector_of_each_word=600). Note that number of words in context and query need not be the same. Also, number of words in every context varies.

Now, I have implemented this in the above code. I created a similarity_matrix of shape (batch_size, number_of_words_in_context, number_of_words_in_query) and then updated batch of each cell after computing the similarity value.

The problem lies with the creation of similarity_matrix. K.zeros throws an error saying it cannot create a tensor with shape None. It only needs integers but the integer values are only available at runtime and not while building the model.

I read a thread on stackoverflow where someone suggested to use tf.stack() along with tf.fill(). Link is here - https://stackoverflow.com/a/34725458

But I am using keras and I don't know why but it cannot find definition of tf.fill() while it can find definition of tf.stack(). So, I couldn't use this method as the K.fill() isn't available in keras (I don't know why). Also, I don't know if this method works as I haven't implemented it yet..

Now, I started posting on forums but no response. Only downvotes.. I don't know where I made a mistake. The question is legitimate and it should have an answer. I am kind of frustrated by now..

**Comment by ParikhKadam** [comment]
I didn't get responses on stackoverflow or reddit. Same thing is happening here. Any updates? Still confused.

**Comment by farizrahman4u** [comment]
You can compute similarity directly:

```python
# context_vectors  : (batch_size, context_length, dim)
# query_vectors: (batch_size, query_length, dim)

similarty_matrix = K.batch_dot(context_vectors, query_vectors, 2)  # (batch_size, context_length, dim)
```

**Comment by ParikhKadam** [comment]
Reopen this issue.. it isn't solved and I ain't dumb so don't give an alternative way for what I should  do if you don't know why I really need to do this. I didn't expect this from keras team. And today I knew why people asked me to use tensorflow instead of keras.
