### ISSUE TITLE
Using functions from tf.keras.backend to replace the implementations in tensorflow_backend.py

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [keras-team/keras#11720]
This discussion is to present pros and cons of using functions from tf.keras.backend to alleviate the maintenance burden of `tensorflow_backend.py`.

What is meant is this:

```python
def batch_dot(x, y) : 
    return tf.keras.backend.batch_dot(x, y)
```
For example. This can be any backend function. 

Inputs welcome.

**Comment by gabrieldemarmiesse** [comment]
I would be in favor of migrating progressively. Such that we can stop and come back if we see that something is not right. Starting with functions which were relatively un-problematic in the past. We can use the git blame for that. For example, `var`, `std`, `any` are good candidates.

**Comment by gabrieldemarmiesse** [comment]
The pros I see are:
* easier migration to TF eager
* We let the tensorflow team perform the optimisations they want.
* We don't need to port PRs about the tensorflow backend back and forth between `tensorflow.keras` and `keras-team/keras`.
* Since `tf.keras.backend` is part of the TF public API, there shouldn't be big compatibility issue (in theory. In practice, that will be different).

I would let @farizrahman4u expose the cons if you may.

**Comment by farizrahman4u** [comment]
Lets wait for @fchollet to weigh in. TBH, I am highly skeptical of this. All external entities have to be considered "hostile". For e.g, so far whenever a user complaints about a bug here, I am able to quickly patch it up and send a PR. But if half of the code base is in a different repo (which we dont have any control over, except the Francois happens to be at Google), the process can be quite confusing. Where will the user post the issue? Do they post all issues here? Or should backend specific issues be posted in TF repo ? There could be cases where the user is not capable of identifying if its a backend issue or not. Another major issue I could foresee is TF maintainers delaying merges and PRs going stale. Note that these are all control/ownership issues and not versioning/compatibility related.

**Comment by fchollet** [comment]
One thing we need to be careful with, is that any function that access the global backend config internally (epsilon, floatx) needs to be reimplemented, since tf.keras and keras-team/keras have independent configurations.

**Comment by gabrieldemarmiesse** [comment]
Of course, I'll be careful about that.

**Comment by fchollet** [comment]
An alternative is to sync the configs, e.g. have `get_session` redirect to `tf.keras.backend.get_session` (inversely for `set_session`, it would delegate to `tf.keras.backend.set_session`).

This might also help alleviate confusion that arises when people import both tf.keras and keras at the same time (albeit they are not supposed to be compatible at all).

There is a possibility that this is dangerous though. I am not 100% sure either way.
