### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shape must be rank 1 but is rank 0 for 'bn_conv1/cond/Reshape_4' (op: 'Reshape') with input shapes

### ISSUE THREAD

**Issue by greatken999** [keras-team/keras#11732]
Please make sure that the boxes below are checked before you submit your issue.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps`

- [x] Check that your version of TensorFlow is up-to-date. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

I got this error crash at creatmodel func after update to keras 2.2.4 from 2.2.2
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shape must be rank 1 but is rank 0 for 'bn_conv1/cond/Reshape_4' (op: 'Reshape') with input shapes

import line:
from keras.layers import Dense, Dropout, Input, Reshape,add, BatchNormalization

crash line:
x = BatchNormalization(axis=1, name='bn_conv1')(x)

**Comment by greatken999** [comment]
I checked tensorflow from 1.5 to 1.12 had this error when keras is 2.2.4
but 2.2.2 is ok.

**Comment by gabrieldemarmiesse** [comment]
Can you provide a standalone script to reproduce?

**Comment by greatken999** [comment]
(x) == [] when creat model .

**Comment by gabrieldemarmiesse** [comment]
An empty list is not a tensor. This is why you get the error.
