### ISSUE TITLE
Request Not a Issue -  Improve readability in Keras Documentation

### ISSUE THREAD

**Issue by rajeshkumargp** [keras-team/keras#11741]
While searching for Keras Callbacks, I found the link as below:

https://keras.io/callbacks/.

There, the Arugments for every callbacks is described with couple of sentences. 
Especially The Arguments description for  ModelCheckpoint,Tensorboard is specified with paragraphs. 

It would be better , if sufficient new lines are added so that the document gives better readability. 

Thanks

**Comment by gabrieldemarmiesse** [comment]
I see what you mean. It's a rendering issue. We have this problem with the docs on keras 2.2.4. I don't remember if it has been fixed on master. The arguments should be in bold, with a new line every time. We have had frequent issues with the rendering of the docs and I'm working on it. I believe other issues are open for this.

**Comment by donkirkby** [comment]
Also on the same page, the `[source]` links don't link to the right line numbers.
