### ISSUE TITLE
Why does Keras have merged layers like multiply, concatenate, dot etc. if these functionality can also be accessed through backend

### ISSUE THREAD

**Issue by ParikhKadam** [keras-team/keras#11742]
It is a query and not an issue but I didn't find a place to ask such questions as on stackoverflow, they just downvote saying the question is unclear.

By the way.. I had this query from many days and then looking at backend modules I found that some functions are named differently in different modules like concat in tensorflow and concatenate in cntk. Maybe this is the reason of providing such merged layers.

Also, I found that these layers and backend functions both provide same answers and hence gave a thought of asking it here.

By the way.. just curious to know if there are any processing overheads while using layers instead of backend funcitons? I need to use backend.batch_dot in my project and this can also be done with layers.dot. So, this is also a query for me.

Thank you...

**Comment by farizrahman4u** [comment]
The merge layers/methods operate on Keras tensors. You use them when building a Keras model using existing layers. You use the backend methods when writing custom layers, and is also used internally by Keras to implement its layers (Dense, LSTM etc). In fact the merge layers/methods are wrappers for the corresponding backend functions such that it doesnt break Keras's topology graph (and additional functionality like batched broadcasting).
