### ISSUE TITLE
Cannot access training images inside on_batch_end callback

### ISSUE THREAD

**Issue by 4sfaloth** [keras-team/keras#11756]
I am training a CNN using keras with TensorFlow backend, using imgaug for image augmentation.

I am also using Tensorboard to visualize training progress and results.

Since imgaug is applying (random) transformations to the input images, I would like to send (some of) the augmented images over to Tensorboard, so that I can visualize them and verify that everything is correct (eg: to check if I am applying too large translations, or blurring the images too much). 

For this I created a custom Keras callback and am trying to input my logic in the on_batch_end method. I can send images to tensorboard alright, but can't find where I can access the augmented input images. Any tips on how to achieve this?

Thanks in advance

**Comment by gabrieldemarmiesse** [comment]
Please refer to the documentation. It's written in https://keras.io/callbacks/#create-a-callback
