### ISSUE TITLE
tensorboard callback error when showing embedding which has multiple inputs

### ISSUE THREAD

**Issue by WangHexie** [keras-team/keras#11761]
- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps`

- [x] Check that your version of TensorFlow is up-to-date. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**link**: [ code and error information(Able to recreate the error by clicking the run button)](https://colab.research.google.com/gist/WangHexie/006358256307b9aac115c4861ae22b54/keras_error.ipynb)

AttributeError                            Traceback (most recent call last)
<ipython-input-2-fc886fb28c63> in <module>()
    191 
    192 if __name__ == '__main__':
--> 193     train()
    194     # data = load_data()
    195     # model = keras.models.load_model("model.h5")

<ipython-input-2-fc886fb28c63> in train()
    169                                         embeddings_layer_names=embeddings_layer_names,
    170                                         embeddings_data=[np.array(list(range(dim))) for dim in cat_dims] * 2 + [
--> 171                                             np.array(list(range(dim))) for dim in attr_dims])])
    172     model.save("model.h5")
    173     return model

/usr/local/lib/python3.6/dist-packages/keras/legacy/interfaces.py in wrapper(*args, **kwargs)
     89                 warnings.warn('Update your `' + object_name + '` call to the ' +
     90                               'Keras 2 API: ' + signature, stacklevel=2)
---> 91             return func(*args, **kwargs)
     92         wrapper._original_function = func
     93         return wrapper

/usr/local/lib/python3.6/dist-packages/keras/engine/training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   1416             use_multiprocessing=use_multiprocessing,
   1417             shuffle=shuffle,
-> 1418             initial_epoch=initial_epoch)
   1419 
   1420     @interfaces.legacy_generator_methods_support

/usr/local/lib/python3.6/dist-packages/keras/engine/training_generator.py in fit_generator(model, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
     92     else:
     93         callback_model = model
---> 94     callbacks.set_model(callback_model)
     95     callbacks.set_params({
     96         'epochs': epochs,

/usr/local/lib/python3.6/dist-packages/keras/callbacks.py in set_model(self, model)
     52     def set_model(self, model):
     53         for callback in self.callbacks:
---> 54             callback.set_model(model)
     55 
     56     def on_epoch_begin(self, epoch, logs=None):

/usr/local/lib/python3.6/dist-packages/keras/callbacks.py in set_model(self, model)
    873             for layer in self.model.layers:
    874                 if layer.name in embeddings_layer_names:
--> 875                     embedding_input = self.model.get_layer(layer.name).output
    876                     embedding_size = np.prod(embedding_input.shape[1:])
    877                     embedding_input = tf.reshape(embedding_input,

/usr/local/lib/python3.6/dist-packages/keras/engine/base_layer.py in output(self)
    811         if len(self._inbound_nodes) > 1:
    812             raise AttributeError('Layer ' + self.name +
--> 813                                  ' has multiple inbound nodes, '
    814                                  'hence the notion of "layer output" '
    815                                  'is ill-defined. '

AttributeError: Layer cat_embedding_0 has multiple inbound nodes, hence the notion of "layer output" is ill-defined. Use `get_output_at(node_index)` instead.

**Comment by gabrieldemarmiesse** [comment]
Could you simplify the code in notebook? Usually, small networks and code samples are enough to trigger bugs and it would help with the debugging.

**Comment by leemengtaiwan** [comment]
Any updates on this issue? Just encountered the exact issue when trying to visualize embedding for my Siamese LSTM with two inputs:

```
AttributeError: Layer embedding has multiple inbound nodes, hence the notion of "layer output" is ill-defined. Use `get_output_at(node_index)` instead.
```

**Comment by WangHexie** [comment]
@leemengtaiwan 
No. Maybe you have to rewrite some code in this callback function to avoid this problem.

**Comment by leemengtaiwan** [comment]
@WangHexie 
Thanks for your update. 

I did rewrite the callback and it worked well now. 

![image](https://user-images.githubusercontent.com/3454980/50424871-1835f880-08af-11e9-8702-5eab334d22b3.png)

For those who encounter the same issue and eager to find a solution, as suggested by the error message, I replaced this line:

```
embedding_input = self.model.get_layer(layer.name).output
```

with this line:

```
embedding_input = self.model.get_layer(layer.name).get_output_at(node_index) 
```

and it worked. (of course you should specify `node_index`, and if you have two inputs, you can choose `0` or `1`)

However, this approach is kinda hacky and I hope this issue can be solved in a more elegant way.

**Comment by simon19891101** [comment]
> get_output_at(node_index)

Awesome! Worked for me. Thanks.

**Comment by simon19891101** [comment]
> @WangHexie
> Thanks for your update.
> 
> I did rewrite the callback and it worked well now.
> 
> ![image](https://user-images.githubusercontent.com/3454980/50424871-1835f880-08af-11e9-8702-5eab334d22b3.png)
> 
> For those who encounter the same issue and eager to find a solution, as suggested by the error message, I replaced this line:
> 
> ```
> embedding_input = self.model.get_layer(layer.name).output
> ```
> with this line:
> 
> ```
> embedding_input = self.model.get_layer(layer.name).get_output_at(node_index) 
> ```
> and it worked. (of course you should specify `node_index`, and if you have two inputs, you can choose `0` or `1`)
> 
> However, this approach is kinda hacky and I hope this issue can be solved in a more elegant way.

Awesome! Worked for me. Thanks.
