### ISSUE TITLE
Add support for generator instances in `fit`/`predict`/`evaluate` 

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [keras-team/keras#11772]
Add support for generator instances in `fit`/`predict`/`evaluate` (instead of having to rely on the `fit_generator`/etc. The exact method signatures should follow those in [`tf.keras` `fit`/`predict`/`evaluate`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/engine/training.py).

Note created by @fchollet in the "Requests for contributions".

**Comment by aayushARM** [comment]
I think this issue should be closed now that #12568 is merged?
