### ISSUE TITLE
Improve performance (GPU utilization) of `multi_gpu_model` for small models.

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [keras-team/keras#11776]
Improve performance (GPU utilization) of `multi_gpu_model` for small models (see [this analysis](https://github.com/rossumai/keras-multi-gpu/blob/master/blog/docs/measurements.md)).

Note created by @fchollet in the "Requests for contributions".

**Comment by bzamecnik** [comment]
Based on the measurements it seems that  two thinks would help: avoiding copy from python to TF memory (using `tf.Dataset` and possibly with plain prefetch to RAM) and prefetching to GPU RAM asychronously. The first should be now supported fine, for the latter I'm not sure if it supports multi GPU so far.
