### ISSUE TITLE
Create tutorial on how to deploy Keras models to Android.

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [keras-team/keras#11778]
Everything is in the title.

Note created by @fchollet in the "Requests for contributions".

**Comment by saadmanrafat** [comment]
I would be happy to take this on. [TFLite Converter](https://www.tensorflow.org/lite/convert/) can be used to convert keras model to tensorflow lite models which can be deployed to mobile devices. Should I write up a tutorial on that or do you have anything else in mind?

**Comment by gabrieldemarmiesse** [comment]
I believe this is good! Good luck with this!

**Comment by gitman88** [comment]
Is it possible to use TFLite Converter and convert Keras-models with custom layers? I can't see that it is possible at the moment?

**Comment by margaretmz** [comment]
I wrote a blog post as well as the tf.Keras and Android code/tutorial on this: https://medium.com/@margaretmz/e2e-tfkeras-tflite-android-273acde6588
