### ISSUE TITLE
Sync the callback API

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [keras-team/keras#11771]
Sync the callback API. on the [new `tf.keras` API](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/callbacks.py#L175): `on_train_batch_begin` added, `on_batch_begin` and `on_batch_end` have new semantics.

Note created by @fchollet in the "Requests for contributions".

**Comment by mkaze** [comment]
I am interested to work on this if anyone else has not started yet?!

**Comment by gabrieldemarmiesse** [comment]
No one replied or made a pull request yet, so it seems you're the first.

**Comment by RaphaelMeudec** [comment]
I think this issue can be closed now

**Comment by gabrieldemarmiesse** [comment]
Yup, thanks for the ping!
