### ISSUE TITLE
Set up versioning of the docs.

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [keras-team/keras#11783]
Set up versioning of the docs. We should be able to autogenerate docs for various Keras version using MkDocs, then upload that to keras.io. Have a look at http://deeplearning.net/software/theano/ to see what we would like to see.

Note created by @fchollet in the "Requests for contributions".

**Comment by RaphaelMeudec** [comment]
@gabrieldemarmiesse What exactly is the docs deployment process? It seems that ReadTheDocs allows to publish multiple versions and is compatible with mkdocs.
