### ISSUE TITLE
Are you going to comment each line of code in Keras?

### ISSUE THREAD

**Issue by shyamalschandra** [keras-team/keras#11784]
Are you going to comment each line of code in Keras?  When is this going to happen along with detailed jupyter notebooks with tutorials?  The current stuff on the website is not linear and is missing tons of information.

**Comment by gabrieldemarmiesse** [comment]
We're always interested in improving the documentation. Notably, we'll likely add a lot of examples to it (see #11758). You'd be a great help if you could help us improving the docs!

**Comment by shyamalschandra** [comment]
If you are interested, do you have a budget?  Do you want more people forking the code and using it in their papers?  I have already attempted to comment parts of the keras code for myself but didn't check it in because I want to do the whole thing before pushing and hopefully, getting it committed.  Do you have technical documentation people?

**Comment by AAMetatron** [comment]
theres 2 90 degrees on a square its man and nature the earth is square with nature and the reflection is square too it makes the Cube held with four pillars Positivity Pray Hope and Strenght a circle is made by two square they said an inverted pyramid is imposible but whats above is so below one is full one is empty AAMetatron and V1

**Comment by shyamalschandra** [comment]
What is this response?  What is going on?
