### ISSUE TITLE
Write Keras style guide and developer guide

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [keras-team/keras#11782]
Note created by @fchollet in the "Requests for contributions".

**Comment by kartik4949** [comment]
Hi,
I can write Keras style & DEVELOPER guide.
Let me know a sample guide 
Thanks.

**Comment by gabrieldemarmiesse** [comment]
Hello @kartik4949 , thanks for the help, but we'll put that on hold until the tf.keras repo get split from tensorflow and replaces the current keras repo. I'll ping you when that's the case!
