### ISSUE TITLE
Implementation Error of los function in neural style transfer in keras

### ISSUE THREAD

**Issue by gourab4gd** [keras-team/keras#11788]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [ ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [ ] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by gourab4gd** [comment]
Sir,
I am trying to implement neural style transfer using keras and adm optimizer rather implementing it using fmin_l_bfgs_b function. Below is my code:
def preprocess(image_name):
    ima=Image.open(image_name)
    ima=ima.resize((224,224))
    im_ar=np.asarray(ima,dtype='float32')
    im_ar=np.expand_dims(im_ar,axis=0)
    return ima,im_ar
content,content_array=preprocess('hugo.jpg')
style,style_array=preprocess('starry_night.jpg')

content_array[:, :, :, 0] -= 103.939
content_array[:, :, :, 1] -= 116.779
content_array[:, :, :, 2] -= 123.68
content_array=content_array[:, :, :, ::-1]

style_array[:, :, :, 0] -= 103.939
style_array[:, :, :, 1] -= 116.779
style_array[:, :, :, 2] -= 123.68
style_array=style_array[:, :, :, ::-1]

height=224
width=224
generated_array=np.random.uniform(0,255,(1,height,width,3))-128.0

content_model = VGG16(input_tensor=K.variable(content_array), weights='imagenet', include_top=False)
style_model = VGG16(input_tensor=K.variable(style_array), weights='imagenet', include_top=False)
generated_model = VGG16(input_tensor=K.variable(generated_array), weights='imagenet', include_top=False)

for layer in content_model.layers:
    layer.name = layer.name + str("_content")

in_content=content_model.layers[-1].output
content_model.layers[-1].outbound_nodes = []

for layer in style_model.layers:
    layer.name = layer.name + str("_style")

in_style=style_model.layers[-1].output
style_model.layers[-1].outbound_nodes = []

for layer in generated_model.layers:
    layer.name = layer.name + str("_generated")

in_generated=generated_model.layers[-1].output
generated_model.layers[-1].outbound_nodes = []

in_img = Concatenate()([in_content,in_style,in_generated])
out_img=Dense(1)(in_img)

model=Model(inputs=[content_model.input,style_model.input,generated_model.input],outputs=[out_img])

content_outputs = dict([(layer.name, layer.output) for layer in content_model.layers])
style_outputs = dict([(layer.name, layer.output) for layer in style_model.layers])
generated_outputs = dict([(layer.name, layer.output) for layer in generated_model.layers])

def content_loss(content, generated):
     return K.sum(K.square(content - generated))

loss = K.variable(0)
content_features = content_outputs['block5_conv2_content']
generated_features = generated_outputs['block5_conv2_generated']
contentloss = content_loss(content_features, generated_features)
loss+=contentloss

def gram_matrix(x):
    #put number of filters to 1st dimension first
    features = K.batch_flatten(K.permute_dimensions(x, (2, 0, 1)))
    gram = K.dot(features, K.transpose(features))
    return gram

def style_loss(style, generated):
    style_gram = gram_matrix(style)
    content_gram = gram_matrix(generated)
    channels = 3
    size = height * width
    return K.sum(K.square(style_gram - content_gram)) / (4. * (pow(channels,2)) * (pow(size,2)))
 

#name of first 5 layers. you can check it by running content_model.summary()
feature_layers = ['block1_conv1', 'block2_conv1', 'block3_conv1', 'block4_conv1', 'block5_conv1']
 
styleloss = K.variable(0)
for layer_name in feature_layers:
    style_features = style_outputs[layer_name+'_style']
    generated_features = generated_outputs[layer_name+'_generated']
    styleloss = styleloss + style_loss(style_features[0], generated_features[0])

alpha = 0.025; beta = 0.2
total_loss = alpha * contentloss + beta * styleloss

model.compile(loss=total_loss, optimizer='adam', metrics=['mse'])

The error I am getting is following:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-113-4088e414f003> in <module>()
----> 1 model.compile(loss=total_loss, optimizer='adam', metrics=['mse'])

C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py in compile(self, optimizer, loss, metrics, loss_weights, sample_weight_mode, weighted_metrics, target_tensors, **kwargs)
     95         """
     96         self.optimizer = optimizers.get(optimizer)
---> 97         self.loss = loss or []
     98         self.metrics = metrics or []
     99         self.loss_weights = loss_weights

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py in __bool__(self)
    669       `TypeError`.
    670     """
--> 671     raise TypeError("Using a `tf.Tensor` as a Python `bool` is not allowed. "
    672                     "Use `if t is not None:` instead of `if t:` to test if a "
    673                     "tensor is defined, and use TensorFlow ops such as "

TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use TensorFlow ops such as tf.cond to execute subgraphs conditioned on the value of a tensor.

How to solve? Thanks in advance.

**Comment by harshini-gadige** [comment]
@gourab4gd  Changin the numpy operations to tensorflow ops may not lead to this error. Can you please try and see if it works fine.

**Comment by gourab4gd** [comment]
Thanks for the response. I would certainly like to try.
Please help me in one issue:
Is it possible to implement neural style transfer using fully in Keras. As whatever implementation I have seen, it has been implemented using tensorflow as in Prof. Andrew Ng courser course or using the scipy fmin_l_bfgs function.
I haven't found any implementation using fully in keras with keras model fit or model compile etc.
Thanks in advance.

**Comment by harshini-gadige** [comment]
@gourab4gd  Though you want to use only Keras, you need to have one of these backends Tensorflow/Theano/CNTK.

**Comment by harshini-gadige** [comment]
@fchollet  Any inputs please ?

**Comment by gourab4gd** [comment]
@fchollet Sir I am also eagerly looking for your response.
