### ISSUE TITLE
seq-seq lstm and dense layer

### ISSUE THREAD

**Issue by akramahmadi66** [keras-team/keras#11797]
Dear all
Is the dense layer necessary  for seq-seq LSTM model when data is not as one-hot vector(is as word2vec)?

![seq_seq_lstm](https://user-images.githubusercontent.com/32474515/49494580-56726600-f875-11e8-975d-f19f8752927b.PNG)

I comment dense layer, because I'm taking input data from the word2vec model.

**Comment by sakuranew** [comment]
if you mean that your decoder_traget_data is word2vec vectors[none,num_decoder_tokens,word_embedding_size],you also need to ensure decoder_outputs[none,num_decoder_tokens,decoder_unit_size] and decoder_traget_data have same shape to compute loss
so a dense layer(word_embedding_size)  is necessary to map decoder_unit_size to word_embedding_size
