### ISSUE TITLE
model = models.Sequential(); NameError: name 'models' is not defined

### ISSUE THREAD

**Issue by Sujatakataria** [keras-team/keras#11793]
base_model = InceptionResNetV2(
    include_top=False, 
    weights='imagenet', 
    input_shape=INPUT_SHAPE)    

# Freeze all the layers
for layer in base_model.layers[:]:
    layer.trainable = False

# Check the trainable status of the individual layers
#for layer in base_model.layers:
#    print(layer, layer.trainable)

# Create the model
**model = models.Sequential()**

# Add the InceptionResNetV2 convolutional base model
model.add(base_model)

**Comment by Sujatakataria** [comment]
It was working perfectly fine yesterday, after committing the code on Kaggle I tried running it, then it started giving me this error.

**Comment by farizrahman4u** [comment]
`from keras import models`

**Comment by Sujatakataria** [comment]
It was working perfectly fine yesterday, after committing the code on Kaggle I tried running it, then it started giving me this error.
Please let me know if you want me to submit the file

**Comment by farizrahman4u** [comment]
Post gist of your code.

**Comment by Sujatakataria** [comment]
It worked fine after import models and import layers
Thanks
