### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '_inbound_nodes'

### ISSUE THREAD

**Issue by marc88** [keras-team/keras#11811]
Hello,

Can anyone help me understand this error please? Am trying to run the code snippet below for a conv2d. The code snippets have been commented for better clarity.

```python
from keras.models import Model
sent_grams = Input(shape=(None,),dtype='int32')
sent_embed = Embedding(23625, 50, input_length=5, trainable=True)(sent_grams)
print(sent_embed.shape) #output: (?, ?, 50)
sent_input = expand_dims(sent_embed,axis=3) # for channels
print(sent_input.shape) # output: (?, ?, 50,1)

# 3 separate convolutions on the same input data 'sent_input'

conv2d_out7= MaxPooling2D(pool_size=(3,1))(Dropout(0.3)(Conv2D(filters=120,kernel_size=(3,50),activation='relu')(sent_input)))
conv2d_out6= MaxPooling2D(pool_size=(4,1))(Dropout(0.3)(Conv2D(filters=120,kernel_size=(2,50),activation='relu')(sent_input)))
conv2d_out5= MaxPooling2D(pool_size=(5,1))(Dropout(0.3)(Conv2D(filters=120,kernel_size=(1,50),activation='relu')(sent_input)))

print(conv2d_out7.shape,conv2d_out6.shape,conv2d_out5.shape)
# output: (?, ?, 1, 120) (?, ?, 1, 120) (?, ?, 1, 120)

# Concatenate the inputs from the above three convolutions

cat_conv = concatenate([conv2d_out7,conv2d_out6,conv2d_out5],axis=3)
print(cat_conv.shape)
#output: (?, ?, 1, 360)

squeezed_cat_conv = keras.backend.squeeze(cat_conv,axis=2)
squeezed_cat_conv2 = keras.backend.squeeze(squeezed_cat_conv,axis=1)
print(squeezed_cat_conv2.shape)
#output: (?, 360)

linear_input = Reshape((10,36))(squeezed_cat_conv2)
print(linear_input.shape)
#output: (?, 10, 36)

# model.add(Dense(5, input_shape=(36,)))
# now the model will take as input arrays of shape (*, 36)
# and output arrays of shape (*, 5)

linear_output = Dense(5,input_shape=(36,),activation='relu')(linear_input)
print(linear_output.shape)
#output: (?, 10, 5)


#Modeling
model = Model(inputs=[sent_grams],outputs=[linear_output])
```

The last line above gives an error that am unable to understand, as:

> AttributeError                            Traceback (most recent call last)
> <ipython-input-37-b951fc65f91d> in <module>()
>      66 print(linear_output.shape)
>      67 
> ---> 68 model = Model(inputs=[sent_grams],outputs=[linear_output])
>      69 
>      70 # output = concatenate([words, casing,char])
> 
> /opt/anaconda3/lib/python3.6/site-packages/keras/legacy/interfaces.py in wrapper(*args, **kwargs)
>      89                 warnings.warn('Update your `' + object_name + '` call to the ' +
>      90                               'Keras 2 API: ' + signature, stacklevel=2)
> ---> 91             return func(*args, **kwargs)
>      92         wrapper._original_function = func
>      93         return wrapper
> 
> /opt/anaconda3/lib/python3.6/site-packages/keras/engine/network.py in __init__(self, *args, **kwargs)
>      91                 'inputs' in kwargs and 'outputs' in kwargs):
>      92             # Graph network
> ---> 93             self._init_graph_network(*args, **kwargs)
>      94         else:
>      95             # Subclassed network
> 
> /opt/anaconda3/lib/python3.6/site-packages/keras/engine/network.py in _init_graph_network(self, inputs, outputs, name)
>     229         # Keep track of the network's nodes and layers.
>     230         nodes, nodes_by_depth, layers, layers_by_depth = _map_graph_network(
> --> 231             self.inputs, self.outputs)
>     232         self._network_nodes = nodes
>     233         self._nodes_by_depth = nodes_by_depth
> 
> /opt/anaconda3/lib/python3.6/site-packages/keras/engine/network.py in _map_graph_network(inputs, outputs)
>    1364                   layer=layer,
>    1365                   node_index=node_index,
> -> 1366                   tensor_index=tensor_index)
>    1367 
>    1368     for node in reversed(nodes_in_decreasing_depth):
> 
> /opt/anaconda3/lib/python3.6/site-packages/keras/engine/network.py in build_map(tensor, finished_nodes, nodes_in_progress, layer, node_index, tensor_index)
>    1351             tensor_index = node.tensor_indices[i]
>    1352             build_map(x, finished_nodes, nodes_in_progress, layer,
> -> 1353                       node_index, tensor_index)
>    1354 
>    1355         finished_nodes.add(node)
> 
> /opt/anaconda3/lib/python3.6/site-packages/keras/engine/network.py in build_map(tensor, finished_nodes, nodes_in_progress, layer, node_index, tensor_index)
>    1351             tensor_index = node.tensor_indices[i]
>    1352             build_map(x, finished_nodes, nodes_in_progress, layer,
> -> 1353                       node_index, tensor_index)
>    1354 
>    1355         finished_nodes.add(node)
> 
> /opt/anaconda3/lib/python3.6/site-packages/keras/engine/network.py in build_map(tensor, finished_nodes, nodes_in_progress, layer, node_index, tensor_index)
>    1323             ValueError: if a cycle is detected.
>    1324         """
> -> 1325         node = layer._inbound_nodes[node_index]
>    1326 
>    1327         # Prevent cycles.
> 
> **AttributeError: 'NoneType' object has no attribute '_inbound_nodes**'
> 

Please help.
Thanks

**Comment by gabrieldemarmiesse** [comment]
The problem is that squeezed_cat_conv2  is not the output of a keras layer. You should put `squeeze` in a lambda layer. You can use keras layers on normal tensors, but if you want to make a `Model` all operations should be in keras layers.

I believe that this type of error is frequent and is posing problems because the error message is not clear at all. PR welcome to improve the error message.

**Comment by ScaleRunner** [comment]
As stated before, all operations should be encapsulated in Keras layers. As a rule of thumb: all Keras layers start with a capital. If you would exchange 
``cat_conv = concatenate([conv2d_out7,conv2d_out6,conv2d_out5],axis=3)``
with
``cat_conv = Concatenate([conv2d_out7,conv2d_out6,conv2d_out5],axis=3)``
It should work.

**Comment by marc88** [comment]
@ScaleRunner  Thanks for the help but, it is complaining of a new error as shown below. Aren't 'concatenate' and 'Concatenate' both from keras.layers?

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-41-53dd214513d5> in <module>()
     26 
     27 
---> 28 cat_conv = Concatenate([conv2d_out7,conv2d_out6,conv2d_out5],axis=3)
     29 print(cat_conv.shape)
     30 squeezed_cat_conv = Lambda(lambda x: squeeze(x, axis=2))(cat_conv)

TypeError: __init__() got multiple values for argument 'axis'
```

Thanks

**Comment by ScaleRunner** [comment]
The `concatenate()` is an operation which can be performed on tensors. The `Concatenate()` is a layer. Which should be used as such. So I was wrong before, you should use:
``cat_conv = Concatenate(axis=3)([conv2d_out7,conv2d_out6,conv2d_out5])``
Where you first construct the layer with `Concatenate(axis=3)` and then call it with the inputs of the layer.

**Comment by mkaze** [comment]
@marc88 I think you have forgotten to wrap `expand_dims` inside a `Lambda` layer as well:

    sent_input = Lambda(lambda x: expand_dims(x, axis=3))(sent_embed) # for channels

**Comment by marc88** [comment]
wooho! It worked. Thanks so much everyone. This is a wonderful first lesson in Keras! :)

**Comment by monk1337** [comment]
I was also facing same error, Sharing my solution :

If you are using any `K.{operation} ` whose has no equivalent layer implementation, you can make that function as Lambda layer.  wrap that in Lambda layer and it should work fine.

Here I was trying to transpose the output of first model and then concatenate with second one 

First I was trying this : 

`cov = K.dot(model_a_output, K.transpose(model_b_output))
`
I was getting same error, then I changed that line into:

```
lambda_con      = Lambda(lambda x: K.transpose(x))
layer_output      = lambda_con(model_a_output)
lambda_dot        =  Lambda(lambda x: K.dot(x[0],x[1]))
layer_output_second = lambda_dot([model_a_output,layer_output] )
```
Now it's working fine.

**Comment by davebrijesh7** [comment]
Have you solved this problem?
I am having a similar issue: https://stackoverflow.com/questions/62138536/attributeerror-nonetype-object-has-no-attribute-inbound-nodes-keras

Can you help me identify the issue?

**Comment by srinathdwivedi** [comment]
i laso have save issue. if possible please help us.
