### ISSUE TITLE
plot_model's expand_nested looks wonky for model with multiple time-distributed layers

### ISSUE THREAD

**Issue by christian-lanius** [keras-team/keras#11810]
Hi everyone,
If a model has more than one time-distributed sub-model, all the layers from all the time-distributed sub-models are grouped together in a single dotted block. In the example image, observe how the predict_input layer and the dense layer are in the same block as the convolutional layer. 
Additionally (I am not sure if this is a plotting bug, but I assume so), the lstm_backward layer seems to not be connected with it's input.
![model](https://user-images.githubusercontent.com/1444164/49574693-51e8a300-f984-11e8-9394-3db4e6df07a7.png)

It was generated with the following code:
```python
from keras.models import Model
from keras.utils import plot_model
from keras.layers import Input, Dense, Flatten,Conv2D, Concatenate, LSTM, TimeDistributed

    
input_node = Input(shape=(16, 32, 32, 3), name='seq_input')
    
img_in = Input(shape=(32,32,3), name='img_input')
new_node = Conv2D(5, kernel_size=3, activation='relu')(img_in)
new_node = Flatten()(new_node)
new_node = Dense(5, activation='relu')(new_node)
time_dist_model = Model(inputs=img_in, outputs=new_node, name='Time_Dist_0')
time_dist_0 = TimeDistributed(time_dist_model)(input_node)


lstm_forward  = LSTM(5, return_sequences=True)(time_dist_0)
lstm_backward = LSTM(5, return_sequences=True, go_backwards=True)(time_dist_0)
lstm_out = Concatenate()([lstm_forward, lstm_backward])


tmp_input = Input((10,), name='predict_input')
new_node = Dense(2, activation='softmax')(tmp_input)
time_dist_1 = Model(inputs=tmp_input, outputs=new_node, name='Time_Dist_1')
output = TimeDistributed(time_dist_1, name='prediction')(lstm_out)

model = Model(inputs=input_node, outputs=output)
plot_model(model, to_file='../model.png', show_shapes=True, rankdir='TB', expand_nested=True)
 ```

**Comment by Jeff-Winchell** [comment]
what versions of plot_model allow a parameter called expand_nested? Clearly not what I have, nor what I get when I type conda update keras

**Comment by triforcely** [comment]
@Jeff-Winchell I solved this problem by installing Keras from git repository instead of from pip, looks like the package is outdated there?
