### ISSUE TITLE
broken github links on keras.io documentation

### ISSUE THREAD

**Issue by maderafunk** [keras-team/keras#11816]
The link "Edit on Github" in the upper right corner of the keras.io documentation is broken and leads to a 404 error page. 

This is an example of the current link:
https://github.com/keras-team/keras/edit/master/docs/index.md

I guess it should be:
https://github.com/keras-team/keras/tree/master/docs 

This is the same for all links on keras.io.

**Comment by SriRangaTarun** [comment]
Dear @maderafunk ,
I have started a [PR](https://github.com/keras-team/keras/pull/11825) for this issue.
Needs to be approved by @fchollet .
