### ISSUE TITLE
layer name issue

### ISSUE THREAD

**Issue by TrybeCoder** [keras-team/keras#11827]
CODE:
def get_model(num_users, num_items, userlayers = [512,64], itemlayers = [1024,64], reg_layers=[0,0]):
    assert len(userlayers) == len(reg_layers)
    num_user_layer = len(userlayers)
    num_item_layer = len(itemlayers)

    # Input variables
    user_input = Input(shape=(1,), dtype='int32', name = 'user_input')
    item_input = Input(shape=(1,), dtype='int32', name = 'item_input')

    MLP_Embedding_User = Embedding(input_dim = int(num_users), output_dim = int(userlayers[0]), name = 'user_embedding',
                                  init = initializers.TruncatedNormal(mean=0.0, stddev=0.01, seed=None), W_regularizer = l2(reg_layers[0]), input_length=1)
    MLP_Embedding_Item = Embedding(input_dim = int(num_items), output_dim = int(itemlayers[0]), name = 'item_embedding',
                                  init = initializers.TruncatedNormal(mean=0.0, stddev=0.01, seed=None), W_regularizer = l2(reg_layers[0]), input_length=1)

    # Crucial to flatten an embedding vector!
    user_latent = Flatten()(MLP_Embedding_User(user_input))
    # MLP layers
    for idx in range(1, num_user_layer):
        layer = Dense(userlayers[idx], W_regularizer= l2(reg_layers[idx]), activation='relu', name = 'layer%d' %idx)
        user_latent = layer(user_latent)

    item_latent = Flatten()(MLP_Embedding_Item(item_input))
    for idx in range(1, num_item_layer):
        layer = Dense(itemlayers[idx], W_regularizer= l2(reg_layers[idx]), activation='relu', name = 'layer%d' %idx)
        item_latent = layer(item_latent)

    vector = keras.layers.Multiply()([user_latent, item_latent])
    # Final prediction layer
    prediction = Dense(1, activation='sigmoid', init=initializers.TruncatedNormal(mean=0.0, stddev=0.01, seed=None), name = 'prediction')(vector)

    model = Model(input=[user_input, item_input],
                  output=prediction)
    return model
ERROR:
  File "D:/Log/byevents/workDMF.py", line 84, in get_model
    output=prediction)
  File "C:\Users\junbo\Anaconda3\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\junbo\Anaconda3\lib\site-packages\keras\engine\network.py", line 93, in __init__
    self._init_graph_network(*args, **kwargs)
  File "C:\Users\junbo\Anaconda3\lib\site-packages\keras\engine\network.py", line 231, in _init_graph_network
    self.inputs, self.outputs)
  File "C:\Users\junbo\Anaconda3\lib\site-packages\keras\engine\network.py", line 1455, in _map_graph_network
    ' times in the model. '
ValueError: The name "layer1" is used 2 times in the model. All layer names should be unique.

**Comment by sh7dm** [comment]
@TrybeCoder try using other name in the second `for` loop
