### ISSUE TITLE
LSTM output is close to zero (such as 0.00000001)

### ISSUE THREAD

**Issue by h-karami** [keras-team/keras#11828]
Dear all
We have a seq2seq autoencoder LSTM model wich the model input comes from a word2vec model. The model output is close to zero (such as 0.00000001) instead of being the same as the input!!!
can anyone help?

**Comment by sh7dm** [comment]
can you provide a code sample of your network?

**Comment by h-karami** [comment]
@sh7dm Thank you for your answer

![image](https://user-images.githubusercontent.com/44494193/49697403-44bdf500-fbcc-11e8-9141-6239d9d1ed2c.png)

**Comment by sh7dm** [comment]
@h-karami try to create `Model`s like this:
`encode_decode_model = Model(inputs=[encoder_inputs, decoder_inputs], outputs=decoder_outputs)`
and
`encoder_model = Model(inputs=encoder_inputs, outputs=encoder_outputs)`
