### ISSUE TITLE
ValueError: setting an array element with a sequence.

### ISSUE THREAD

**Issue by adouwitti** [keras-team/keras#11833]
hello , 
i am using keras and tensorflow to implement CNN nets for edge detection , when i tried to run the code ,  this error have occurred . so I would like that you help me to solve it. thanks in advance.
here is the code : 

[from keras.models import Sequential
from keras.layers import (Activation, Dropout, Flatten, Dense, Conv2D, MaxPooling2D)
from keras.utils import np_utils
from keras import backend as K
K.set_image_dim_ordering('th')
import json, pylab
import cv2
import numpy as np

np.set_printoptions(threshold=np.nan)

# some model and data processing constants
batch_size = 128
nb_classes = 2
nb_epoch = 7

# input image dimensions
img_rows, img_cols = 48, 72

# number of convolutional filters to use
nb_filters = 32
# size of pooling area for max pooling
nb_pool = 5
# convolution kernel size
nb_conv = 3

# architecture
model = Sequential()
model.add(Conv2D(nb_filters, (nb_conv, nb_conv),
                        padding='valid',
                        input_shape=(1, img_rows, img_cols)))
model.add(Activation('relu'))
model.add(Conv2D(nb_filters, (nb_conv, nb_conv)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(nb_pool, nb_pool)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(128))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(nb_classes))
model.add(Activation('softmax'))
model.compile(loss='sparse_categorical_crossentropy',
              optimizer='adadelta',
              metrics=['accuracy'])

train_imgs=(cv2.imread('1.jpg',0))
ground_truth_train=(cv2.imread('1edges.jpg',0))

test_imgs=(cv2.imread('2.jpg'),0)
ground_truth_test=(cv2.imread('2edges.jpg',0))

print('Preparing images...')

X_train = np.array(train_imgs)
X_test = np.array(ground_truth_train)
y_train = np.array(test_imgs)
y_test = np.array(ground_truth_test)
# prepare the data

X_train = X_train.reshape(X_train.shape[0], 1, img_rows, img_cols)
X_test = X_test.reshape(X_test.shape[0], 1, img_rows, img_cols)

X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255
print('X_train shape:', X_train.shape)
print(X_train.shape, 'train samples')
print(X_test.shape, 'test samples')

# convert class vectors to binary class matrices
# convert class vectors to binary class matrices

from keras.utils import to_categorical 
y_train = np.divide(y_train,255)
y_test = np.divide(y_test,255)
Y_train = to_categorical(y_train,nb_classes)
y_test = to_categorical(y_test,nb_classes)

# train it plz
print('Training model...')

model.fit(X_train, Y_train ,
          batch_size=batch_size,
          nb_epoch=nb_epoch, verbose=1,
          validation_data=(X_test,y_test) )

# let's dump the model
print('Saving model...')
saved_model = model.to_json()
with open('CNN_architecture.json', 'w') as outfile:
    json.dump(saved_model, outfile)
model.save_weights('CNN_weights.h5')
](url)

**Comment by gabrieldemarmiesse** [comment]
Can you provide the stacktrace and format your code snippet? Thanks!

**Comment by adouwitti** [comment]
![image](https://user-images.githubusercontent.com/44825125/49735542-6c8f8480-fcc2-11e8-8466-d14cf2d3e632.png)
i think , the error occurs in these steps,  also it was showing me this  Y_train = to_categorical(y_train,nb_classes) ,  y = np.array(y, dtype ='int')
