### ISSUE TITLE
TypeError: The added layer must be an instance of class Layer

### ISSUE THREAD

**Issue by CrookedNoob** [keras-team/keras#11848]
```[python]
from keras.applications import VGG16

conv_base = VGG16(weights='imagenet',
                  include_top=False,
                  input_shape=(150, 150, 3))

from keras import models
from keras import layers

model = models.Sequential()
model.add(conv_base)
model.add(layers.Flatten())
model.add(layers.Dense(256, activation='relu'))
model.add(layers.Dense(1, activation='sigmoid'))
```
Adding VGG16 from ```keras.applications``` with ```Sequential``` gives the below error:
```TypeError: The added layer must be an instance of class Layer. Found: <tensorflow.python.keras.engine.training.Model object at 0x000002C7010E3C88> ```

Attached image for reference:

![capture](https://user-images.githubusercontent.com/13174586/49801385-0a8d5880-fd70-11e8-8d6b-354d63a07992.JPG)

Currently I am using the below versions of TensorFlow and Keras-
TensorFlow: 1.11.0
Keras: 2.2.2

**Comment by CrookedNoob** [comment]
TensorFlow: 1.11.0
Keras: 2.2.2

**Comment by arquolo** [comment]
Update to keras>=2.2.3, it has been fixed already.

**Comment by CrookedNoob** [comment]
> Update keras to latest version (at least 2.2.3), this issue has been fixed already.
> Also, see [Issue template](https://github.com/keras-team/keras/blob/master/ISSUE_TEMPLATE.md)

Updated to 2.2.4 and it worked. Thanks for the quick help!!

**Comment by AliRashidnejad** [comment]
I have 2.2.4 but I'm getting the error too: 


import tensorflow as tf
# Importing the Keras libraries and packages
from tensorflow import keras
from tensorflow.keras.models import Sequential
from keras.layers import LSTM, Dropout, Lambda, BatchNormalization



`def createModel1(input_shape=(10,4),output_shape=(5,4)):
    
    '''
    more info: https://keras.io/getting-started/sequential-model-guide/
    '''
    #Initialising the RNN
    regressor=Sequential()

    #Adding the first LSTM layer and Dropout regularisation
    regressor.add(LSTM(units= 50, return_sequences= True, input_shape=input_shape))
    regressor.add(Dropout(rate=0.2))`

**Comment by yoch** [comment]
Same issue for me, using keras==2.2.4 and tensorflow=1.13.1

```python
from keras.layers import *
from keras.models import Sequential
from keras.applications.resnet50 import ResNet50

base_model = ResNet50(
    weights='imagenet',
    include_top=False, 
    input_shape=(224, 224, 3), 
    pooling='avg'
)
base_model.trainable = False

pooling = GlobalAveragePooling2D()
predictions = Dense(NB_CLS, activation='softmax')

model = tf.keras.Sequential([
  base_model,
  pooling,
  predictions
])
```

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-21-ccdaf5a437aa> in <module>()
     15   base_model,
     16   pooling,
---> 17   predictions
     18 ])
     19 

3 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/checkpointable/base.py in _method_wrapper(self, *args, **kwargs)
    440     self._setattr_tracking = False  # pylint: disable=protected-access
    441     try:
--> 442       method(self, *args, **kwargs)
    443     finally:
    444       self._setattr_tracking = previous_value  # pylint: disable=protected-access

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py in __init__(self, layers, name)
    107     if layers:
    108       for layer in layers:
--> 109         self.add(layer)
    110 
    111   @property

/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/checkpointable/base.py in _method_wrapper(self, *args, **kwargs)
    440     self._setattr_tracking = False  # pylint: disable=protected-access
    441     try:
--> 442       method(self, *args, **kwargs)
    443     finally:
    444       self._setattr_tracking = previous_value  # pylint: disable=protected-access

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py in add(self, layer)
    143       raise TypeError('The added layer must be '
    144                       'an instance of class Layer. '
--> 145                       'Found: ' + str(layer))
    146     self.built = False
    147     set_inputs = False

TypeError: The added layer must be an instance of class Layer. Found: <keras.engine.training.Model object at 0x7f17dd956978>
```

**Comment by arquolo** [comment]
@yoch ,
1) please stop using both `tf.keras` and `keras`, they are not compatible. Choose only one.
2) `include_top=False`, means that model will be cut right after last Global Pool, so you do not need another one (`GlobalAveragePooling2D`)
Try this:
```python
from keras.layers import *
from keras.models import Sequential
from keras.applications.resnet50 import ResNet50

CLASS_COUNT = 10

base_model = ResNet50(
    weights='imagenet',
    include_top=False, 
    input_shape=(224, 224, 3), 
    pooling='avg',
)
base_model.trainable = False

model = Sequential([
  base_model,
  Dense(CLASS_COUNT, activation='softmax'),
])
```
In my environment (`keras=2.2.4`, `tensorflow-gpu=1.13.1`) that works.

**Comment by yoch** [comment]
OK, after removing `tf.keras` it's work. Thank you.

**Comment by dsbsoni** [comment]
Just import-

from keras.models import Sequential

& then use Sequential only.

I was doing the keras.Sequential before....   This was the reason for my error

**Comment by Aditya183** [comment]
yes,its working after removing tensorflow.keras

**Comment by prasanna-1** [comment]
K.clear_session()
gc.collect()

resnet = DenseNet201(
    weights='imagenet',
    include_top=False,
    input_shape=(224,224,3)
)

model = build_model(resnet ,lr = 1e-4)
model.summary()

i am getting the below error after running the above code..and my tensorflow version is also updated..let me know why i'm getting the error.

The added layer must be an instance of class Layer. Found: <keras.engine.training.Model object at 0x7fe0ebfbd780>

**Comment by ShubhamBirhade1** [comment]
Hello i am getting an error as follows

Traceback (most recent call last):
  File "model2.py", line 74, in <module>
    model.add(Conv2D(32, kernel_size = (3, 3), activation='relu', input_shape = (1,200 , 200 , 1)))
  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\training\tracking\base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "c:\users\admin\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\keras\engine\sequential.py", line 154, in add
    'Found: ' + str(layer))
TypeError: The added layer must be an instance of class Layer. Found: <keras.layers.convolutional.Conv2D object at 0x000002CAFB08F048>

**Comment by ShubhamBirhade1** [comment]
here i am sharing my code also

import tensorflow
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras.layers import Dense, Dropout, Flatten
import tensorflow as tf
tf.compat.v1.get_default_graph
import tensorflow
from tensorflow.keras.layers import *
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
from tensorflow import keras
from PIL import Image
import os
from random import shuffle
import matplotlib.pyplot as plt
import numpy as np

**Comment by aish-where-ya** [comment]
> K.clear_session()
> gc.collect()
> 
> resnet = DenseNet201(
> weights='imagenet',
> include_top=False,
> input_shape=(224,224,3)
> )
> 
> model = build_model(resnet ,lr = 1e-4)
> model.summary()
> 
> i am getting the below error after running the above code..and my tensorflow version is also updated..let me know why i'm getting the error.
> 
> The added layer must be an instance of class Layer. Found: <keras.engine.training.Model object at 0x7fe0ebfbd780>

I think both of us are referring to the same notebook. Firstly, change your `resnet` to `densenet`.
Secondly, you need to change your import statement.
Original import - 
```
from tensorflow.python.keras.layers import Dense
from tensorflow.python.keras import Sequential
```

Replace it with - 
```
from keras.layers import Dense
from keras import Sequential
```

**Comment by maitrisingh** [comment]
model = allcnn()
Traceback (most recent call last):

  File "<ipython-input-21-2a281ec22964>", line 1, in <module>
    model = allcnn()

  File "<ipython-input-19-30ded367a89c>", line 30, in allcnn
    model.add(GlobalAveragePooling2D)

  File "/home/code/.local/lib/python3.7/site-packages/keras/engine/sequential.py", line 133, in add
    'Found: ' + str(layer))

TypeError: The added layer must be an instance of class Layer. Found: <class 'keras.layers.pooling.GlobalAveragePooling2D'>

**Comment by Mark-Kitur** [comment]
am runing the same issue
