### ISSUE TITLE
GPU Error on running Basic 2D CNN

### ISSUE THREAD

**Issue by ShivamSharma1997** [keras-team/keras#11843]
I am getting the following error on running a basic 2D CNN on my system. MY system specs are GTX 1080 4GB ram.

2018󈚰󈚯 01:29:40.165789: I C:\tf_jenkins\home\workspace\rel‑win\M\windows‑gpu\PY\35\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2018󈚰󈚯 01:29:42.720179: I C:\tf_jenkins\home\workspace\rel‑win\M\windows‑gpu\PY\35\tensorflow\core\common_runtime\gpu\gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX 1050 major: 6 minor: 1 memoryClockRate(GHz): 1.493
pciBusID: 0000:01:00.0
totalMemory: 4.00GiB freeMemory: 3.30GiB
2018󈚰󈚯 01:29:42.745682: I C:\tf_jenkins\home\workspace\rel‑win\M\windows‑gpu\PY\35\tensorflow\core\common_runtime\gpu\gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) ‑> (device: 0, name: GeForce GTX 1050, pci bus id: 0000:01:00.0, compute capability: 6.1)

Please help!!!

**Comment by ymodak** [comment]
Closing this issue since Dref60's comment is correct. Feel free to reopen if have any follow up questions. Thanks!

**Comment by ShivamSharma1997** [comment]
Ok, but my Ipython window is crashing everytime I run the code, and the memory usage also bursts so that my system hangs for a while and then this comes up with the closed Ipython window. 
What am I doing wrong?
