### ISSUE TITLE
raise StopIteration when my Iterator data  Enough.

### ISSUE THREAD

**Issue by sfhmzpig** [keras-team/keras#11845]
train code:
        if not self.valid:
            for i in range(self.trainEpochNum):
                m.fit_gen(D,2,epochs=1)
                m.save_weights(self.saveWeight+'.'+str(i))
                m.save(self.saveWeight+'.model.'+str(i))
loadBatch code:
        zippedFilePaths = itertools.cycle(zip(imgFilePaths,segFilePaths))

        while True:
            X = []
            Y = []

            for _ in range(self.batchSize):
                imgFilePath,segFilePath = next(zippedFilePaths)
                X.append(self._loadImg(imgFilePath))
                Y.append(self._loadSeg(segFilePath))

            yield np.array(X),np.array(Y)

Finaly:raise error:

1/2 [==============>...............] - ETA: 22s - loss: 2.2296 - acc: 0.0408Traceback (most recent call last):
  File "/Users/mba/PycharmProjects/vggUnet/train.py", line 75, in <module>
    trainner.train()
  File "/Users/mba/PycharmProjects/vggUnet/train.py", line 69, in train
    m.fit_generator(D,2,validation_data=D1,validation_steps=200,epochs=1)
  File "/Users/mba/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1761, in fit_generator
    initial_epoch=initial_epoch)
  File "/Users/mba/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_generator.py", line 211, in fit_generator
    max_queue_size=max_queue_size)
  File "/Users/mba/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_generator.py", line 308, in evaluate_generator
    generator_output = next(output_generator)
  File "/Users/mba/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/utils/data_utils.py", line 816, in get
    raise StopIteration()
StopIteration

it is can not finish my train

**Comment by Dref360** [comment]
Try again using keras master. An exception is occurring inside your generator and Keras reraise the exception now.

**Comment by sfhmzpig** [comment]
> COuld you try again using keras master. An exception is occurring inside your generator and Keras reraise the exception now.

Thankyou your receive,I update keras using keras master when I read your message,and a new problem appear.

#####problem###################
Epoch 1/1

1/2 [==============>...............] - ETA: 39s - loss: 2.2310 - acc: 0.1150
#############################

spend two hours,the model can not train to 2/2 [=======>...]

and the I set evey epoch batch nums is 3,4,5,same problem appear.
i.e
2/3[======>...]
3/4[======>...]
4/5[======>...]

the model can not finish a complete epoch.

**Comment by sfhmzpig** [comment]
I slove this problem already,
First. update my keras to new.
Second. ensure valiStep <= every epoch's batchsizeNums

**Comment by bmiftah** [comment]
what do you mean by every epochs batch_size number ...  just batch_size for the training , right ? I have issue with my validation accuracy remaining same despite the fact that validation-loss keeps on changing .. 

Epoch 00001: LearningRateScheduler reducing learning rate to 0.0003333333333333333.
Epoch 1/1000
100/100 [==============================] - 52s 521ms/step - loss: 7.7960 - acc: 0.6640 - val_loss: 9.1278 - val_acc: 0.5000

Epoch 00002: LearningRateScheduler reducing learning rate to 0.0001111111111111111.
Epoch 2/1000
100/100 [==============================] - 46s 460ms/step - loss: 6.1036 - acc: 0.6680 - val_loss: 8.5393 - val_acc: 0.5000

Epoch 00003: LearningRateScheduler reducing learning rate to 3.7037037037037037e-05.
Epoch 3/1000
100/100 [==============================] - 46s 455ms/step - loss: 5.7830 - acc: 0.6670 - val_loss: 8.4141 - val_acc: 0.5000

Epoch 00004: LearningRateScheduler reducing learning rate to 1.2345679012345678e-05.
Epoch 4/1000
100/100 [==============================] - 46s 457ms/step - loss: 5.7198 - acc: 0.6660 - val_loss: 8.3766 - val_acc: 0.5000

Epoch 00005: LearningRateScheduler reducing learning rate to 4.115226337448559e-06.
Epoch 5/1000


... any clue why this may have happened ?
