### ISSUE TITLE
Incorrect warning message when saving RNN layers with initial states

### ISSUE THREAD

**Issue by caisq** [keras-team/keras#11855]
Consider the following code:

```py
import keras
import numpy as np

xs1 = np.array([[1, 2, 3, 4, 5]]) / 10
xs2 = np.array([[[1, 2, 3, 4], [-1, -2, -3, -4], [3, 4, 5, 6]]]) / 10

in1 = keras.Input(shape=[5])
out1 = keras.layers.Dense(2,
                          kernel_initializer='ones',
                          bias_initializer='ones')(in1)

in2 = keras.Input(shape=[3, 4])
out2 = keras.layers.GRU(2,
                        recurrent_initializer='ones',
                        kernel_initializer='ones')(in2, initial_state=out1)

model = keras.Model(inputs=[in1, in2], outputs=[out1, out2])
model.save('foo.h5')

print(model.predict([xs1, xs2]))
```

When model.save() is called, it prints a warning message:

UserWarning: Layer gru_1 was passed non-serializable keyword arguments: {'initial_state': [<tf.Tensor 'dense_1/BiasAdd:0' shape=(?, 2) dtype=float32>]}. They will not be included in the serialized model (and thus will be missing at deserialization time).
  '. They will not be included 

This is misleading as the initial_state tensor is indeed serialized with the model JSON (i.e., it's treated as  the second input to the RNN layer). So this warning should no longer be necessary.

- [X] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps`

- [X] Check that your version of TensorFlow is up-to-date. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [X] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by jvishnuvardhan** [comment]
I don't see that warning when I use "tf.keras" instead of "keras". Thanks!
