### ISSUE TITLE
Tensorboad histogram option doesn't work with dataset API

### ISSUE THREAD

**Issue by lminer** [keras-team/keras#11864]
It would be nice to add support for the tensorflow dataset API to the Tensorboard callback. Specifically, it appears that the `histogram_freq` option is not currently supported. Currently if I pass in a dataset for validation data, I get the following error:

```
TypeError: The value of a feed cannot be a tf.Tensor object. Acceptable feed values include Python scalars, strings, lists, numpy ndarrays, or TensorHandles.For reference, the tensor object was Tensor("strided_slice:0", shape=(32, 512, 128, 2), dtype=float32) which was passed to the feed with key Tensor("input_1:0", shape=(?, 512, 128, 2), dtype=float32).
```

Looking at the source code this seems to be because a feed dict is being used.

**Comment by ymodak** [comment]
This issue is more suitable for Tensorboard repo. Please can you post it on Tensorboard from [here](https://github.com/tensorflow/tensorboard/issues)

**Comment by lminer** [comment]
This is an issue with the TensorBoard callback within keras, not with TensorBoard itself. Aren't all keras callbacks maintained by the keras team?

**Comment by aneergaard** [comment]
I don't think the Keras team is going to add support for the dataset API, isn't Keras supposed to be more or less framework agnostic? But if you want dataset API support, you can use tf.keras, no?

**Comment by lminer** [comment]
@aneergaard support for tf.data was added in 2.0.7.

**Comment by omalleyt12** [comment]
@lminer can you provide a minimal code snippet that repros this? That being said, I would say that if you are using tf.data, I would suggest using tf.keras. It is built to integrate natively with the other TF APIs
