### ISSUE TITLE
How to guarantee that Keras model loading the pretrained weights correctly, by setting  skip_mismatch=True ?

### ISSUE THREAD

**Issue by kangskii** [keras-team/keras#11867]
Dear,
Scenario Description 

Step #1:
I replaced the backbone in yoloV3 from Darknet53 to MobileNet. The MobileNet weights is loaded from the Imagenet, by using
`mobilenet = MobileNet(input_tensor=inputs,weights='imagenet') `.

Step #2:
I also want to load pre-trained weights for detector yolov3, so I download the .cfg and .weights files from the https://pjreddie.com/darknet/yolo/ where we can find the file links as shown below in the original page.
----------------------------------------------------------------------------------
YOLOv3-416 | COCO trainval | test-dev | 55.3 | 65.86 Bn | 35 | cfg | weights
----------------------------------------------------------------------------------
Obviously, the .weights and .cfg files for YOLOv3-416 include the weights for both yoloV3 detector, and its backbone, Darknet53.

Step #3 :
when we develop the new yolo body (yolo body = backbone + yolo Detector), by using, for example, 
`model_body = yolo_body(image_input, num_anchors // 3, num_classes) `
`model_body.load_weights(weights_path, by_name=True, skip_mismatch=True) `
where  "weights_path" is the place where we save the  .weights file in Step #2(Of course, the .cfg and .weights have been converted to .h5 file).

Now comes the issue: the new yolo body is composed of mobilenet + yoloV3, while the loaded pre-trained .h5 weights  is for Darknet53+yoloV3. How can we guarantee that we load the correct weights to the correct model, in this scenario, obviously, I just want to load the yoloV3 detector part to the new yolo body, and the Darknet53 weights in the .h5 file will be automatically dropped. 

How to guarantee this, in a formal way? Just by simply setting "skip_mismatch=True" ?

**Comment by keineahnung2345** [comment]
Relevant question on stackoverflow: https://stackoverflow.com/questions/47214382/how-can-i-know-if-weights-were-loaded-in-keras-model/47214490#47214490.
