### ISSUE TITLE
about  inference time 

### ISSUE THREAD

**Issue by 1448643857** [keras-team/keras#11861]
hi,I am a keras Novice,and when I use keras model to predict,I want to know the inference time,I set the code like below:
"""
import time 
.............
start = time.time()
model.predict(text_x)
end = time.time()
print(end-start)
"""

It's right?

**Comment by Golbstein** [comment]
`model.predict(text_x, verbose=1)
`
will print the inference time per batch

**Comment by harshini-gadige** [comment]
Hi

This issue isn't related to a bug/enhancement/feature-request or other accepted types of issue.

To ask questions, please see the following resources :

https://keras.io/
https://keras.io/#support
https://gitter.im/Keras-io/Lobby

Thanks!
