### ISSUE TITLE
evaluate_generator ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by Ontheroad123** [keras-team/keras#11871]
unet.load_weights('unet_bestweight_liver.h5')
    parallel_model = multi_gpu_model(unet, gpus=2)
    parallel_model.compile(optimizer=sgd, loss="categorical_crossentropy", metrics=[mean_iou, 'acc'])
    #parallel_model.fit_generator(read_images('image', 'label'),  epochs=epoch, workers=5, callbacks=callback_list)

    print("start test!")
    loss, acc = parallel_model.evaluate_generator(read_images('image4', 'label4'), steps=8, workers=5)
    print('loss: ,mean_iou: ', loss, acc)
the error:
File "unet_liver.py", line 113, in train
    loss, acc = parallel_model.evaluate_generator(read_images('image4', 'label4'), steps=8, workers=5)
ValueError: too many values to unpack (expected 2)
I use the same generator for train and test, but there is a error when i test the model,i don't know how to solve it.

**Comment by harsh204016** [comment]
you check the number of  metrics parameters by `model.metrics_names`
then assign them to the `model.evaluate_generator`
