### ISSUE TITLE
No GPU use under TensorFlow and Keras

### ISSUE THREAD

**Issue by EdouardDKP** [keras-team/keras#11888]
Hello,
I am coming back to you for help. I am installing a DevBox under Ubuntu 18.04.1 LTS with 4 RTX 2080Ti Nvidia cards.
I have performed multiple Linux/Drivers installation without success. There is no GPU use by Keras and fore sure no multi_GPU_model calculation.
At this time, the Nvidia drivers are 410.78 with CUDA 10.0.
The Nvidia-smi function shows me the good data : all the 4 GPUs, Drivers version, Cuda Revision
I am using Anaconda Python 3.6.5.
TensorFlow : 1.12.0 with GPU version
Keras : TensorFlow Backend 2.2.4

Additionally, is there anybody who has experienced starting issue with Ubuntu 18.04.1 LTS and Nvidia driver such as no starting ?
Thank you for your help
Best Regards
Edouard

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps`

- [x] Check that your version of TensorFlow is up-to-date. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by harshini-gadige** [comment]
Can you uninstall the cpu version of Tensorflow in your system and upgrade the gpu version of tensorflow.
Please check if it works.

**Comment by harshini-gadige** [comment]
> I installed TensorFlow with the following command line
> pip3 install --upgrade TensorFlow-gpu
> 
> Do you think the CPU version could have been installed ?

Please check by pip uninstall tensorflow or pip3 uninstall tensorflow

**Comment by EdouardDKP** [comment]
I removed TensorFlow but now, I am not able to reinstall it at this time.

**Comment by EdouardDKP** [comment]
Hello, 
Unfortunately, even after conda install TensorFlow-gpu, it does not work. Indeed, I have calculation issue (I think due to the fact that Vonda installation added other Cuda version and so one).
So, my issue remains. Even if I use pip install TensorFlow-gpu, it seems that the non gpu version is installed. Do you have any advise ?
Thanks in advance

**Comment by harshini-gadige** [comment]
@EdouardDKP  Can you please create a request in tensorflow repo ?

**Comment by EdouardDKP** [comment]
Hello,
As advised previously, I send my issue to the Tensorflow team.
They told me that the pip install tensorflow-gpu is not compatible with Cuda 10.0 (only cuda 9.2).
To use Cuda 10.0, we have to build tensorflow on our own machine.
I did it and at this time I have an error whl not supported. But I have the last revisionof pip.
Consequently, I am still working to install Tensorflow.
Best Regards

**Comment by jyning12** [comment]
> Can you uninstall the cpu version of Tensorflow in your system and upgrade the gpu version of tensorflow.
> Please check if it works.

@EdouardDKP   soon after I reply in your issuse, I fixed my problem by this way, hope you fixed your problem as soon as possible.

**Comment by EdouardDKP** [comment]
Hello,
I had booting issues with the Nvidia drivers 410.78.
I solved this with the drivers 410.93 and succeed to compile Tensorflow on my computer.
So everything works fine :-)
Thanks a lot for your support
