### ISSUE TITLE
How to implemente multi-output using sequence+fit_generator?

### ISSUE THREAD

**Issue by Shell777** [keras-team/keras#11883]
what shoule the _getitem_ return when there is a multi-output problem?
My output are:
`I model = Model(inputs=input_img, outputs=[mask,net2_opt, net3_opt])`

**Comment by Golbstein** [comment]
x - input_image
m - mask_image
o2 - net2_opt output
o3 - net3_opt output

```
def __getitem__(self, ...):
    ...
    return x, [m, o2, o3]
```

**Comment by Shell777** [comment]
> x - input_image
> m - mask_image
> o2 - net2_opt output
> o3 - net3_opt output
> 
> ```
> def __getitem__(self, ...):
>     ...
>     return x, [m, o2, o3]
> ```
my code is as follow:
`model = Model(inputs=input_img, outputs=[mask,
                                         net2_opt[0],
                                         net2_opt[1],
                                         net2_opt[2],
                                         net2_opt[3],
                                         net2_opt[4],
                                         net2_opt[5],
                                         net2_opt[6],
                                         net2_opt[7],
                                         net3_opt])`

`    def __getitem__(self, index):
        batch_indexs = self.indexes[index*self.batch_size:(index+1)*self.batch_size]
        batch_datas = [self.datas[k] for k in batch_indexs]
        images, masks,heatmaps1,heatmaps2,heatmaps3,heatmaps4,heatmaps5,heatmaps6,heatmaps7,heatmaps8,xyzs = self.data_generation(batch_datas)

        return images, [masks,
                        heatmaps1,
                        heatmaps2,
                        heatmaps3,
                        heatmaps4,
                        heatmaps5,
                        heatmaps6,
                        heatmaps7,
                        heatmaps8,
                        xyzs]`
but there is an error :ValueError: Error when checking target: expected conv_1x1_x14 to have 4 dimensions, but got array with shape (10, 1)
the output of conv_1x1_x14 is mask.

**Comment by Shell777** [comment]
> x - input_image
> m - mask_image
> o2 - net2_opt output
> o3 - net3_opt output
> 
> ```
> def __getitem__(self, ...):
>     ...
>     return x, [m, o2, o3]
> ```

my code is as follow:
```
model = Model(inputs=input_img, outputs=[mask, net2_opt[0], net2_opt[1], net2_opt[2], net2_opt[3], net2_opt[4], net2_opt[5], net2_opt[6], net2_opt[7], net3_opt])
```
```
def getitem(self, index):
batch_indexs = self.indexes[index*self.batch_size:(index+1)*self.batch_size]
batch_datas = [self.datas[k] for k in batch_indexs]
images, masks,heatmaps1,heatmaps2,heatmaps3,heatmaps4,heatmaps5,heatmaps6,heatmaps7,heatmaps8,xyzs = self.data_generation(batch_datas)

    return images, [masks,
                    heatmaps1,
                    heatmaps2,
                    heatmaps3,
                    heatmaps4,
                    heatmaps5,
                    heatmaps6,
                    heatmaps7,
                    heatmaps8,
                    xyzs]
```
but there is an error :ValueError: Error when checking target: expected conv_1x1_x14 to have 4 dimensions, but got array with shape (10, 1)
the output of conv_1x1_x14 is mask.

**Comment by Shell777** [comment]
oh,sorry,I solve the problem.the mask I generated has some problem.
