### ISSUE TITLE
Keras backend pow works with non-integers

### ISSUE THREAD

**Issue by tylergiallanza** [keras-team/keras#11886]
Please make sure that the boxes below are checked before you submit your issue.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps`

- [x] Check that your version of TensorFlow is up-to-date. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by tylergiallanza** [comment]
The documentation for the `pow` function in Keras backend indicates the following:

`keras.backend.pow(x, a)`

Element-wise exponentiation.

Arguments

x: Tensor or variable.
a: Python integer.

With the tensorflow backend, I don't think it is correct that `a` needs to be a Python integer. Consider the following code snippet:


```
import tensorflow as tf
import keras.backend as K

sess = tf.InteractiveSession()
sess.run(K.pow(2.0,0.5))
sess.run(K.pow(2,0.5))
```

The first call to the pow function, `K.pow(2.0,0.5)` runs correctly, but the second call `K.pow(2,0.5)` returns the following error:

`TypeError: Expected int32 passed to parameter 'y' of op 'Pow', got 0.5 of type 'float' instead.`

It looks like [this issue](https://github.com/tensorflow/tensorflow/issues/7170) logged on the tensorflow github repository addresses the same concern.

Am I understanding this correctly? If so, should the documentation for the `pow` function be changed?

**Comment by Dref360** [comment]
Theano does require an int.

**Comment by jvishnuvardhan** [comment]
@tylergiallanza As you mentioned, it is a duplicate ticket. If you are willing to contribute to update that pow op, let us know. Thanks!

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will open a new issue. Thanks!

**Comment by JafarMansouri** [comment]
in sess.run(K.pow(2.0,0.5)) , dtype of 2.0 is float but in sess.run(K.pow(2,0.5)), dtype of 2 is integer. Since the power(0.5) is float, you should first convert integer to float.
