### ISSUE TITLE
Feature request: K.einsum()

### ISSUE THREAD

**Issue by danielegrattarola** [keras-team/keras#11900]
Hi, 

I realize that this was asked already in #6754, and that it didn't get a follow-up because of compatibility issues with Theano, but I was wondering if maybe things changed and we can get an implementation of einsum in the backend. 

I would do it myself, but I lack the sufficient knowledge in Theano and CNTK. Still, I would be glad to collaborate on this and help out, e.g. with testing. 

Thanks, 
Daniele

**Comment by Dref360** [comment]
Theano is now in maintenance mode and I don't think CNTK supports einsum.
