### ISSUE TITLE
merge two networks with fixed weights

### ISSUE THREAD

**Issue by guofuzheng** [keras-team/keras#11906]
Hi, i want to merge two networks with two fixed weights (for example 0.8 and 0.2). My code may be wrong. I didn't get the result i wanted.
```
gru1 = ...
gru2 = ...
net1_w1 = Lambda(lambda x:x*0.8)(gru1)
net2_w2 = Lambda(lambda x:x*0.2)(gru2)
last = add([net1_w1,net2_w2])
last = Dropout(0.5)(last)
last = Dense(256)(last)
dense = Dense(15, activation='softmax')(last)
```
I want to know if there is problem. And please show me the right code. Thank you for your help.

**Comment by lvapeab** [comment]
Hi,
you are passing the inputs to the `add` function as arguments. It should be:

```last = add()([net1_w1,net2_w2])```

Cheers

**Comment by guofuzheng** [comment]
@lvapeab hello, thank you for your help. 
The code  about add in keras document is like this.
```
import keras

input1 = keras.layers.Input(shape=(16,))
x1 = keras.layers.Dense(8, activation='relu')(input1)
input2 = keras.layers.Input(shape=(32,))
x2 = keras.layers.Dense(8, activation='relu')(input2)
added = keras.layers.add([x1, x2])

out = keras.layers.Dense(4)(added)
model = keras.models.Model(inputs=[input1, input2], outputs=out)
``` 
I want to know if i am right about
```
net1_w1 = Lambda(lambda x:x*0.8)(gru1)
net2_w2 = Lambda(lambda x:x*0.2)(gru2)
```    
Thank you for your help.
