### ISSUE TITLE
Weight sharing

### ISSUE THREAD

**Issue by sanjanasri** [keras-team/keras#11903]
Please make sure that the boxes below are checked before you submit your issue.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.

Thank you!

- [ x] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps`

- [ x] Check that your version of TensorFlow is up-to-date. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

Hi all,

      I have some few question regarding weights tying

  1) how do we use transpose of weights of one layer to another layer

   2)  how do we split weight of one layer and give the partial weights to other layers. suppose I have layer of weight dimension is 100*600. i need to split as 100*300 and pass to one layer and rest 100*300 to another layer. 

It would be great if I could get an earnest reply.

**Comment by lvapeab** [comment]
Hi,

regarding your first question, here is a discussion about it: https://github.com/keras-team/keras/issues/10485

**Comment by shouldsee** [comment]
As of 
```
Name: Keras
Version: 2.1.2
```

I have adapted a previous solution to make it work

```python
Dense = keras.layers.Dense
K = keras.backend
class DependentDense(Dense):
    '''Adapted from https://github.com/nanopony/keras-convautoencoder/blob/master/autoencoder_layers.py
    '''
    def __init__(self, output_dim, master_layer, init='glorot_uniform', activation='linear', weights=None,
                 W_regularizer=None, b_regularizer=None, activity_regularizer=None,
                 W_constraint=None, b_constraint=None, input_dim=None, **kwargs):
        self.master_layer = master_layer
        super(DependentDense,self).__init__(output_dim, **kwargs)
        self.output_dim = output_dim

    def build(self,input_shapes):
#         self.kernel = self.master_layer.kernel.T
        self.kernel = keras.backend.transpose(self.master_layer.kernel)
#         self.kernel = K.variable(K.transpose(l.kernel))
#         self.W = self.master_layer.W.T
        self.bias = K.zeros((self.output_dim,))
        self.params = [self.bias,self.kernel]
        self.regularizers = []
        self.trainable_weights = [self.master_layer.kernel]
        self.built = True
#         if self.W_regularizer:
#             self.W_regularizer.set_param(self.W)
#             self.regularizers.append(self.W_regularizer)

#         if self.b_regularizer:
#             self.b_regularizer.set_param(self.b)
#             self.regularizers.append(self.b_regularizer)

#         if self.activity_regularizer:
#             self.activity_regularizer.set_layer(self)
#             self.regularizers.append(self.activity_regularizer)

#         if self.initial_weights is not None:
#             self.set_weights(self.initial_weights)
#             del self.initial_weights
```
