### ISSUE TITLE
weight extraction

### ISSUE THREAD

**Issue by sanjanasri** [keras-team/keras#11919]
Please make sure that the boxes below are checked before you submit your issue.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.

Thank you!

- [ 1] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps`

- [ 1] Check that your version of TensorFlow is up-to-date. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

Hi,

    I need to get weights from concatenate layer, when I did the following 

joint = concatenate([src2, tgt2],name='joint')
w_sj,w_jt=np.hsplit(joint.get_weights()[0], 2)

I get the following error , 'Tensor' object has no attribute 'get_weights'

**Comment by ymodak** [comment]
Duplicate #11903
