### ISSUE TITLE
MemoryError on linux 

### ISSUE THREAD

**Issue by fingerecho** [keras-team/keras#11938]
I try to build a network model using cnn. The code works well in my local area.
`
def generate_model_then_predict_model(model_name:str,epochs=2):

	train_size = len(os.listdir(DOG_SUMU_DIR)) + len(os.listdir(DOG_JINMAO_DIR))
	train_fi = len(os.listdir(DOG_JINMAO_DIR))
	trains = np.empty((train_size,DOG_PIC_WIDTH,DOG_PIC_HEIGHT,3),dtype="float32")
	labels = np.empty((train_size),dtype="int32")

	for ind in range(len(os.listdir(DOG_JINMAO_DIR))):
		img = Image.open(os.path.join(DOG_JINMAO_DIR, os.listdir(DOG_JINMAO_DIR)[ind]))
		arr = np.asarray(img,dtype="float32")
		trains[ind,:,:,:] = arr.reshape(DOG_PIC_WIDTH,DOG_PIC_HEIGHT,3) # (460,585,3)
		labels[ind] = 0

	for ind in range(len(os.listdir(DOG_SUMU_DIR))):
		img = Image.open(os.path.join(DOG_SUMU_DIR, os.listdir(DOG_SUMU_DIR)[ind]))#tf.image.decode_jpeg(img,channels=3)
		arr = np.asarray(img,dtype="float32")
		trains[ind+train_fi,:,:,:] = arr.reshape(DOG_PIC_WIDTH,DOG_PIC_HEIGHT,3)
		labels[ind+train_fi] = 1

	write_log(str(labels),file=log_file)

	model = keras.Sequential([
		keras.layers.Flatten(input_shape=(DOG_PIC_WIDTH,DOG_PIC_HEIGHT,3)),
		keras.layers.Dense(2,activation=tf.nn.relu,input_shape=(DOG_PIC_WIDTH,DOG_PIC_HEIGHT,3)),
		keras.layers.Dense(2,activation=tf.nn.relu),
		keras.layers.Dense(2,activation=tf.nn.softmax)
	])

	model.compile(
		optimizer =tf.train.AdamOptimizer(),
		loss = 'sparse_categorical_crossentropy',
		metrics = ['accuracy']
	)

	model.fit(trains,labels,epochs=epochs,steps_per_epoch=20)
	model.save(test_6_MODEL+"/"+model_name)
	predict_dog(model,test_jinmao)

`
But when I use a CentOS 7.3 Ali Cloud server, hint the following error
`
-> if __name__ == '__main__':
(Pdb) n
> /srv/dog-face-identify/dog-face-check/cnn/_test_cnn_6.py(132)<module>()
-> generate_model_then_predict_model("1915_01.h5",10)
(Pdb) n
MemoryError
> /srv/dog-face-identify/dog-face-check/cnn/_test_cnn_6.py(132)<module>()
-> generate_model_then_predict_model("1915_01.h5",10)
(Pdb) n
--Return--
> /srv/dog-face-identify/dog-face-check/cnn/_test_cnn_6.py(132)<module>()->None
-> generate_model_then_predict_model("1915_01.h5",10)
(Pdb) n
MemoryError
> <string>(1)<module>()->None
(Pdb) n
--Return--
> <string>(1)<module>()->None
(Pdb) n
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/pdb.py", line 1667, in main
    pdb._runscript(mainpyfile)
  File "/usr/local/python3/lib/python3.6/pdb.py", line 1548, in _runscript
    self.run(statement)
  File "/usr/local/python3/lib/python3.6/bdb.py", line 434, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/srv/dog-face-identify/dog-face-check/cnn/_test_cnn_6.py", line 132, in<module>
    generate_model_then_predict_model("1915_01.h5",10)
  File "/srv/dog-face-identify/dog-face-check/cnn/_test_cnn_6.py", line 97, in generate_model_then_predict_model
    trains = np.empty((train_size,DOG_PIC_WIDTH,DOG_PIC_HEIGHT,3),dtype="float32")
MemoryError
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /srv/dog-face-identify/dog-face-check/cnn/_test_cnn_6.py(97)generate_model_then_predict_model()
-> trains = np.empty((train_size,DOG_PIC_WIDTH,DOG_PIC_HEIGHT,3),dtype="float32")

`

**Comment by fingerecho** [comment]
[cnn.tar.zip](https://github.com/keras-team/keras/files/2711260/cnn.tar.zip)

**Comment by gabrieldemarmiesse** [comment]
It is unrelated to keras. You are trying to create a numpy array and your OS is telling you that it doesn't have enough free memory for this numpy array. There is nothing keras can do about it.

**Comment by fingerecho** [comment]
thank you , I solved this problem by modifying the limit value
