### ISSUE TITLE
Save model FailedPreconditionError

### ISSUE THREAD

**Issue by Tolkoton** [keras-team/keras#11946]
Please make sure that the boxes below are checked before you submit your issue.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps`

- [x] Check that your version of TensorFlow is up-to-date. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by Tolkoton** [comment]
Model works just fine, but just after I add: `model.save('model.h5')` I get :

> tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value dense_11/bias
	 [[Node: _retval_dense_11/bias_0_0 = _Retval[T=DT_FLOAT, index=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](dense_11/bias)]]

**Comment by gabrieldemarmiesse** [comment]
Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by Tolkoton** [comment]
Found error, sorry

**Comment by gabrieldemarmiesse** [comment]
No worries. Can this issue be closed?

**Comment by Tolkoton** [comment]
Yes, thank you!
