### ISSUE TITLE
Input_shape bug

### ISSUE THREAD

**Issue by Mcilie** [keras-team/keras#11950]
So my issue is when Im trying to make the first Conv2D layer of my CNN
I have scoured the docs, and the web for hours finding different answers and I've bruteforced every possible combination of input_shape. Basically, the parameter input_shape (for the Conv2D layer) is behaving weird. I set input_shape to (28, 28, 3) which is the rows, columns, and channels of my images. 
I have also tried adding channels first. I have also tried setting data_format to "channels_last" etc.
I keep getting an error no matter what. Here is my most recent error 
`ValueError: Error when checking input: expected conv2d_1_input to have 4 dimensions, but got array with shape (60000, 28, 28)`

Here is the code:
`model.add(Conv2D(32, kernel_size=(3,3), activation='relu', input_shape = (28,28,1)))`
Please help thank you

**Comment by RaphaelMeudec** [comment]
Keras is expecting a 4D tensor, which should be in your case : (60000,28, 28, 1)
You might want to use something like [np.expand_dims](https://docs.scipy.org/doc/numpy/reference/generated/numpy.expand_dims.html) to extend your dimension from (60000, 28, 28) to (60000, 28, 28, 1)

**Comment by Mcilie** [comment]
then i get this:
`ValueError: Input 0 is incompatible with layer conv2d_1: expected ndim=4, found ndim=5`

**Comment by Mcilie** [comment]
I have 3, it says i have too little, i have 4 it says i have too many.....

**Comment by RaphaelMeudec** [comment]
Can you provide a sample code?

**Comment by Jonas1312** [comment]
`Conv2D(..., input_shape = (60000,28,28,3))`
should be `Conv2D(..., input_shape = (28,28,3))`

For inference of a single image, you must process a tensor of rank (1, H, W, 1), the first number is the number of images in your batch and the last number is for grayscale.
If you have a grayscale image as a numpy array of shape (H, W) please try this:
`img = img[np.newaxis, :, :, np.newaxis]`

**Comment by RaphaelMeudec** [comment]
Mnist is in grayscale, you just have to expand last axis and give the `(28, 28, 1)` as input_shape. Also, `y_train` and `y_test` should be switched to categorical values. Below the working sample : 

```
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train = np.expand_dims(x_train, axis=-1)
x_test = np.expand_dims(x_test, axis=-1)
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)
model = Sequential()

model.add(Conv2D(32, kernel_size=(3,3), activation='relu', data_format = "channels_last", input_shape = (28, 28, 1)))
```

**Comment by Mcilie** [comment]
Nvm, fixed it.
I had to use numpy to modify some dimensions
heres an updated gist 
https://gist.github.com/Mcilie/d0535b972aacbe909ac07b7ca31d98f6
thanks for the help tho
