### ISSUE TITLE
order of arguments in in_top_k and top_k_categorical_accuracy not consistent

### ISSUE THREAD

**Issue by alexhernandezgarcia** [keras-team/keras#11970]
The order of the arguments in the function `keras.backend.in_top_k(y_pred, y_true, k)` is the opposite as in the function `keras.metrics.top_k_categorical_accuracy(y_true, y_pred, k)`. I believe it would be good to have the same order for API consistency. Is there a good reason why this is not the case?

**Comment by gabrieldemarmiesse** [comment]
I see your point and it's valid, but I'm not sure we can change the backend function signature (it would break a lot of existing code.

**Comment by gabrieldemarmiesse** [comment]
Tagging as feature as this is a request to change the API.
