### ISSUE TITLE
TimeDistribution wrapper fails the model compilation

### ISSUE THREAD

**Issue by kdx2** [keras-team/keras#11979]
Hello community,
I have an extremely simple cnn which i will be trying to bind to an rnn (but that in the future). For now, all I have is conv2D->maxpool>conv2d->maxpool->dense->dense. The CNN works well, no problems, compiles, runs.

`classifier.add(TimeDistributed(Convolution2D(32, (3, 3), input_shape=(32, 32, 3), activation='relu')))`

When I introduced the TimeDistributed layer though keras fails to compile.

**RuntimeError: You must compile your model before using it.**

And of course, model.compile() is immediately after the model definition and .fit following the compile...
Hence, is it me not getting something right or it is really an issue with the current Keras build?

**Comment by piyush-kgp** [comment]
If this `TimeDistributed` is your first layer, you will have to specify the input shape for this layer. You should add the `input_shape` to `TimeDistributed`; not to `Convolution2D ` like this:

`classifier.add(TimeDistributed(Convolution2D(32, (3, 3), activation='relu'), input_shape=(32, 32, 3)))`
