### ISSUE TITLE
Can't retrain loaded model

### ISSUE THREAD

**Issue by theabc123** [keras-team/keras#11983]
Hi, I create a autoencoder model with Keras, everything goes fine for training and prediction, but when I save the model then load it I can't retrain it, I get the following error : 

> tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'input1' with dtype float and shape [?,3506,132]
	 [[Node: input1 = Placeholder[dtype=DT_FLOAT, shape=[?,3506,132], _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
	 [[Node: loss_2/mul/_583 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_6463_loss_2/mul", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

The model.fit(..) method throws the previous error.  
Any suggestion ? Thanks ! 

Edit : FIXED !
If you're using a loss function that depends on internal layers, you should feed them to that loss function.

**Comment by Tiaspetto** [comment]
seems like you have fed wrong shape data, try print data shape you will find problem.
