### ISSUE TITLE
name 'shape' is not defined (Input layer)

### ISSUE THREAD

**Issue by onurbarut** [keras-team/keras#11999]
Hi all,

I've used Sequential models before, this is first time I'm using Functional  API. However I got the 

NameError: name 'shape' is not defined

error on line: inputs = Input(shape(200, 9, ))

It might be very trivial but I couldn't get out of it. Can anyone help?

**Comment by jacquerie** [comment]
You have a simple typo in your code: in Python keyword arguments requires an equal sign. So it should be:
```python
inputs = Input(shape=(200, 9))
```

**Comment by onurbarut** [comment]
> You have a simple typo in your code: in Python keyword arguments requires an equal sign. So it should be:
> 
> ```python
> inputs = Input(shape=(200, 9))
> ```

Yes yes absolutely. Thank you! I told you it was very trivial but I think I was quite exhausted to miss that :))
