### ISSUE TITLE
Use pyux to check API integrity in Keras

### ISSUE THREAD

**Issue by farizrahman4u** [keras-team/keras#11992]
[Pyux](https://www.github.com/farizrahman4u/pyux) is a tiny util that I wrote to check api integrity in python projects.
Is this something we could use for Keras? 

Right now the api stability is based on trust; moderators tag @fchollet on PRs that introduce API changes. With pyux, api changes will have to be "registered" explicitly and all api changes will be logged in a single place. Any unintentional API changes will break the build.

PRs that introduce API changes can be easily detected (just check if they modify the api hash) and we can probably automate tagging @fchollet in such PRs (or disable merging for mods).

**Comment by gabrieldemarmiesse** [comment]
I think it's a good idea. How will that work for module which have private classes or function not present in the docs? Especially the ones not marked by an underscore? I'm thinking about the backend module where all the imports are leaked in the module (the famous `K.tf`).

I also like the idea of a bot, bots are good :)

**Comment by farizrahman4u** [comment]
You can make exceptions for methods/classes/modules that happen to be public (no underscore) but shouldnt be.

**Comment by gabrieldemarmiesse** [comment]
I get your point. Let's not use the documentation as base, it's preferable to externalize code if possible, it reduces the maintenance burden. Which would be the case if we use pyux. 

So I believe that we can say that @farizrahman4u  and I agree about:

* Cleaning namespaces
* Use pyux to check that those namespaces do not change, or that each change was not a mistake.

I suppose that if we could have a bot to tag automatically @fchollet if `api.json` changes, reporting the api change automatically, it would be nice. But that will be for another time.

Any other input from @fchollet @taehoonlee @Dref360 ?

**Comment by Dref360** [comment]
Looks great!

Using the Checks API (https://developer.github.com/v3/checks/runs/), we could show a warning when the API does change.

**Comment by gabrieldemarmiesse** [comment]
@Dref360 very cool! :)

**Comment by gabrieldemarmiesse** [comment]
Linking the issue #11781 since this is related.

**Comment by farizrahman4u** [comment]
@fchollet Waiting for your response.

**Comment by fchollet** [comment]
This looks great! I think we could use it in a workflow like this:
- Keep a "master" version of the API files generated, alongside the codebase (or we could just regenerate it from the master branch every time we need it?)
- For each new PR, compare the current API to the master API
- In case of diff, add a label to the PR, and require owner approval before merging (via a custom branch rule, probably implemented via a custom CI check).

**Comment by gabrieldemarmiesse** [comment]
I can take care of cleaning the namespaces. I wanted to do it at some point anyway.

**Comment by farizrahman4u** [comment]
> Keep a "master" version of the API files generated, alongside the codebase (or we could just regenerate it from the master branch every time we need it?)

Its better to do it once and keep it alongside the codebase. Otherwise you will have to do a `git checkout master`, generate API file, and then git checkout the PR branch.. which is kinda sloppy.

**Comment by Dref360** [comment]
Could we just host the file in S3 and pull it on Travis/ a Github bot?

**Comment by farizrahman4u** [comment]
@Dref360 the file is small enough to be placed in the repo. In fact, pyux uses pyux to check API stability so you can see the api.json there: https://github.com/farizrahman4u/pyux/blob/master/api.json

The problem with storing it externally is that, if a user wants to actually change the API (adding a new backend method for e.g) they would have to update the file first (and they need access to that) for the build to pass; but it will break the build for master and other PRs! Now  imagine multiple PRs with API changes.
