### ISSUE TITLE
flow_from_dataframe directory parameter cannot be empty

### ISSUE THREAD

**Issue by karimamd** [keras-team/keras#11990]
Hello so I am using keras on colaboratory
and using flow_from_dataframe() on a dataframe having full paths to images and second column is labels
the dataframe has 36k rows
the problem is the directory parameter cannot be set to None , only accepts string
doesn't accept an empty string and I do not need to specify the directory if I have full paths in the first column as written in you recommended article in documentation

If I put an empty string it outputs that it found 0 images although paths are correct
and if I put None is an error
and If I did set the directory to the one that has all images, after calling the flow_from_directory it runs for more than an hour without actual output it just hangs running with no feed or progress bar or any sign of finishing 

to regenerate the error just "run all" this colab notebook:
https://colab.research.google.com/drive/151Ne6EX-AqleOKXBTeIE0LL7n1PT1Cwj

**Comment by Dref360** [comment]
Fix on master

**Comment by karimamd** [comment]
hello, it seems not to work yet
"TypeError: expected str, bytes or os.PathLike object, not NoneType"

I used the github version using the following commands:
!pip3 install git+https://github.com/keras-team/keras
!pip3 install git+https://github.com/keras-team/keras-preprocessing

can you help please ?

**Comment by karimamd** [comment]
> Fix on master

hello, it seems not to work yet
"TypeError: expected str, bytes or os.PathLike object, not NoneType"

I used the github version using the following commands:
!pip3 install git+https://github.com/keras-team/keras
!pip3 install git+https://github.com/keras-team/keras-preprocessing

can you help please ?
