### ISSUE TITLE
"DRAW: A Recurrent Neural Network For Image Generation" implementation?

### ISSUE THREAD

**Issue by mongoose54** [keras-team/keras#12010]
Is there an implementation of [DRAW: A Recurrent Neural Network For Image Generation](https://arxiv.org/pdf/1502.04623.pdf) in Keras? 

Found implementations in TF and PyTorch but nothing in Keras

**Comment by msymp** [comment]
Hi @omalleyt12 , the user is interested in a Keras implementation of the DRAW paper above. Thanks.

**Comment by omalleyt12** [comment]
I'm not aware of any implementation. If you would like to contribute an implementation, I would suggest https://github.com/keras-team/keras-contrib/tree/master/keras_contrib/applications

**Comment by msymp** [comment]
@mongoose54 , Please submit a PR for contribution as suggested by @omalley12 . This issue is closed. Thanks.
