### ISSUE TITLE
how to detect custom objects using model?

### ISSUE THREAD

**Issue by Poonamjo** [keras-team/keras#12015]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [ ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [ ] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by Poonamjo** [comment]
I have trained a model for images of Radiator. I have used keras model resnet50_coco_best_v2.0.1.h5 as base model to train it with csv dataset for radiator images.
Output model : resnet50_new_csv_01.h5
I want it to detect images like tv cell_phone and radiator. 
I have used the notebook example ResNet50RetinaNet.ipynb for detection purpose
modified line 
model_path = os.path.join('.\Downloads\keras-retinanet-master\keras-retinanet-master\snapshots', 'resnet50_coco_best_v2.1.0.h5')
Getting all outputs
But i want to detect custom objects tv and cell_phone how to do that? 
One more issue, I am getting no objects detected in output after changing the model to Output model : resnet50_new_csv_01.h5


Please please help

**Comment by msymp** [comment]
Hello @Poonamjo , Please make sure that the correct boxes in your template are checked. Thanks.

**Comment by Tiaspetto** [comment]
I don't think it is an issue,  my advice is going to coursera and Andrew Ng will told u how to do so nicely.

**Comment by jvishnuvardhan** [comment]
This issue isn't related to a bug/enhancement/feature request or other accepted types of issue.
To ask questions, please see the following resources :
[StackOverflow](http://stackoverflow.com/questions/tagged/keras)
[Keras Slack channel](https://keras-slack-autojoin.herokuapp.com)
[Keras.io support](https://keras.io/#support)
[Gitter](https://gitter.im/Keras-io/Lobby)
Thanks!
If you think we made a mistake, please open another issue and fill all the information asked by the template. Thanks!
