### ISSUE TITLE
CapsNet Model Evaluation with K-Fold validation - Best model and Evaluate!

### ISSUE THREAD

**Issue by iphton** [keras-team/keras#12018]
I was trying to implement `CapsuleNet` for classifying some of the Native digits.

Here, I've used RGB images and converted to grayscale and resize to **`32 X 32`** and dataset has **10** classification output.

> **X_train_all.shape**: `(1045, 32, 32, 1)`<br>
> **y_train_all.shape**: `(1045, 10)`

Here what I implemented so far and ended up with some annoying error. But first, Following is the vanilla structure of CapsNet.

## CapsNet Model

First, define the `CapsNet` model. Following is the main architecture of Capsule Network including **PrimaryCaps** and **DigitCaps** and so on.

```python
    def CapsNet(input_shape, n_class, routings):
        """
        A Capsule Network on MNIST.
        :param input_shape: data shape, 3d, [width, height, channels]
        :param n_class: number of classes
        :param routings: number of routing iterations
        :return: Two Keras Models, the first one used for training, and the second one for evaluation.
                `eval_model` can also be used for training.
        """
        x = layers.Input(shape=input_shape)
                                                                                                                                       
        # Layer 1: Just a conventional Conv2D layer
        conv1 = layers.Conv2D(filters=128, kernel_size=9, strides=1, padding='valid', activation='relu', name='conv1')(x)
    
        # Layer 2: Conv2D layer with `squash` activation, then reshape to [None, num_capsule, dim_capsule]
        primarycaps = PrimaryCap(conv1, dim_capsule=8, n_channels=32, kernel_size=9, strides=2, padding='valid')
    
        # Layer 3: Capsule layer. Routing algorithm works here.
        digitcaps = CapsuleLayer(num_capsule=n_class, dim_capsule=16, routings=routings,
                                 name='digitcaps')(primarycaps)
    
        # Layer 4: This is an auxiliary layer to replace each capsule with its length. Just to match the true label's shape.
        # If using tensorflow, this will not be necessary. :)
        out_caps = Length(name='capsnet')(digitcaps)
    
        # Decoder network.
        y = layers.Input(shape=(n_class,))
        masked_by_y = Mask()([digitcaps, y])  # The true label is used to mask the output of capsule layer. For training
        masked = Mask()(digitcaps)  # Mask using the capsule with maximal length. For prediction
    
        # Shared Decoder model in training and prediction
        decoder = models.Sequential(name='decoder')
        decoder.add(layers.Dense(512, activation='relu', input_dim=16*n_class))
        decoder.add(layers.Dense(1024, activation='relu'))
        decoder.add(layers.Dense(np.prod(input_shape), activation='sigmoid'))
        decoder.add(layers.Reshape(target_shape=input_shape, name='out_recon'))
    
        # Models for training and evaluation (prediction)
        train_model = models.Model([x, y], [out_caps, decoder(masked_by_y)])
        eval_model = models.Model(x, [out_caps, decoder(masked)])
        
        return train_model, eval_model
````
## Actual Training 

This simply returns `train_model` and `eval_model`. Now following is the actual training process I've implemented.

```python
    def train_caps(model, data, epoch_size_frac=1.0):
        """
        Training a CapsuleNet
        :param model: the CapsuleNet model
        :param data: a tuple containing training and testing data, like `((x_train, y_train), (x_test, y_test))`
        :param args: arguments
        :return: The trained model
        """
        # unpacking the data
        (x_train, y_train), (x_val, y_val) = data
    
        # compile the model
        model.compile(optimizer=Adam(lr=0.1),
                      loss=[margin_loss, 'mse'],
                      loss_weights=[1., 0.512],
                      metrics={'capsnet': 'accuracy'})
        
        tbCallBack = keras.callbacks.TensorBoard(log_dir='CapsuleNet/CapGraph', histogram_freq=0, 
                                              write_graph=True, write_images=True)
    
    
        # --------------Begin: Training with data augmentation --------------
        def train_generator(x, y, batch_size, shift_fraction=0.):
            train_datagen = ImageDataGenerator(width_shift_range = shift_fraction,
                                               height_shift_range = shift_fraction,
                                              rotation_range=20,
                                              rescale=1.0/255,
                                              shear_range=0.1,
                                              zoom_range=0.1,
                                              horizontal_flip=False,
                                              vertical_flip=False,
                                              fill_mode='nearest')  # shift up to 2 pixel
            
            generator = train_datagen.flow(x, y, batch_size=batch_size)
            
            while 1:
                x_batch, y_batch = generator.next()
                yield ([x_batch, y_batch], [y_batch, x_batch])
                 
    
        # Training with data augmentation. 
        history = model.fit_generator(generator = train_generator(x_train, y_train, 64, 0.1),
                            steps_per_epoch = int(y_train.shape[0] / 64),
                            epochs = 15,
                            validation_data = [[x_val, y_val], [y_val, x_val]],
                            callbacks = [tbCallBack])
        # -----End: Training with data augmentation ----------------#
        
    
        return model
```

## K-Fold Cross Validation

Now to train the model and fit data on it, I used **K-Fold** cross-validation approach. Let's say it's K-Fold = 5. Like the following code, we save 5 fold model and save the weight.

```python
    cvscores = []
    
    for train, val in kfold.split(X_train_all, y_train_all):
        gc.collect()
        K.clear_session()
        print ('Fold: ', Fold)
        
        # define model
        model, eval_model = CapsNet(input_shape=[32, 32, 1],
                        n_class=10,
                        routings=3)
        model.summary()
        
        X_train = X_train_all[train]
        X_val = X_train_all[val]
        
        X_train = X_train.astype('float32')
        X_val = X_val.astype('float32')
        print(X_train.shape)
        
        y_train = y_train_all[train]
        y_val = y_train_all[val]
        
    
    #   train -
        train_caps(model = model, data = ((X_train, y_train), (X_val, y_val)),
                   epoch_size_frac = 0.5)
    
        
    #     # Save each fold model
        model_name = 'cap_keras_aug_Fold_'+ str(Fold) + '.h5'
        model.save(model_name)
    
        # evaluate the model
        scores = model.evaluate(X_val, y_val, verbose = 0)
        print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))
        cvscores.append(scores[1] * 100) 
         
        Fold = Fold + 1

````
## Problem Faced 1

The problem occurred in the evaluation section. `scores = model.evaluate(X_val, y_val, verbose = 0)` and it showed:

    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    <ipython-input-36-12f206477b39> in <module>()
    ----> 1 scores = model.evaluate(X_val, Y_val, verbose = 0)
          2 print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))
    
    ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 2 array(s), but instead got the following list of 1 arrays: [array([[[[218.],
             [1.],
             [0.],
             ...,
             [1.],
             [1.],

Is there any other way I can evaluate the model performance and measure the scores?

## Problem Faced 2

In this approach, how to find the best model? I am thinking, we can load top (suppose) **3 weighted fold** model and get the average score value or something like ensemble method over them. Below is something I've tried so far.

```python
    def ensemble(models, model_input):
        
        Models_output = [model(model_input) for model in models]
        Avg = keras.layers.average(Models_output)
        
        modelEnsemble = Model(inputs = model_input, outputs = Avg, name = 'ensemble')
        modelEnsemble.summary()
        modelEnsemble.compile(Adam(lr = .0001), 
                              loss = 'categorical_crossentropy', 
                              metrics = ['accuracy'])
        
        return modelEnsemble
````

And load the save weighted that we get **K-Fold** cross-validation method.

```python
    import keras
    
    model_1, eval_model_1 = CapsNet(input_shape=[32, 32, 1],
                    n_class=10,
                    routings=3)
    
    model_2, eval_model_2 = CapsNet(input_shape=[32, 32, 1],
                    n_class=10,
                    routings=3)
    
    models = []
    
    # Load weights 
    model_1.load_weights('Fold_1.h5')
    model_1.name = 'model_1'
    models.append(model_1)
    
    model_2.load_weights('Fold_2.h5')
    model_2.name = 'model_2'
    models.append(model_2)
    
    model_input = Input(shape=models[0].input_shape[1:])
    ensemble_model = ensemble(models, model_input)
```

This throws an error following. I know, I'm missing something here but can't figure out how to manage this.

    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    <ipython-input-37-8cec3f452a69> in <module>()
          4 model_1, eval_model_1 = CapsNet(input_shape=[32, 32, 1],
          5                 n_class=10,
    ----> 6                 routings=3)
          7 
          8 model_2, eval_model_2 = CapsNet(input_shape=[32, 32, 1],
    
    <ipython-input-31-d96b4a5e15ad> in CapsNet(input_shape, n_class, routings)
         44 
         45     # Shared Decoder model in training and prediction
    ---> 46     decoder = models.Sequential(name='decoder')
         47     decoder.add(layers.Dense(512, activation='relu', input_dim=16*n_class))
         48     decoder.add(layers.Dense(1024, activation='relu'))
    
    AttributeError: 'list' object has no attribute 'Sequential'

If I make a short summary of my question or the problem I've faced is that - I can't evaluate model performance using `model.evaluate(...,...)` method. And further getting this **Attribution** error. 

Get no effective response in [Stack ](https://stackoverflow.com/questions/54130103/capsnet-model-evaluation-with-k-fold-validation-how-to-get-the-best-model-and)still now. Any help or suggestion is highly appreciated. Thanks.

**Comment by msymp** [comment]
Hi @pavithrasv , this user has implemented the CapsNet model and doing model evaluation. The first error relates to shape of the input arrays. In the second case, user is building ensemble of models, and gets an Attribute error during the evaluations. Can you advise who can assist? Thanks.

**Comment by Tiaspetto** [comment]
First problem, if you have a aux head in your networks, you actually have multi-outputs, therefore you need organize your ground truth, for example, if you have 3 output, ground truth label should like [label, label, label].

Second problem, I think your parameter 'models' is a list of model, and it's type of "list"  in python. A list object definitely don't have function in 'Model' object, that is error.

**Comment by Tiaspetto** [comment]
> @Tiaspetto I think the ground truth is organized well with 10 different classification output. I thought maybe `eval_model` can be used to evaluate the model performance but no. It asked for compilation before evaluate and if I do so it throws the same error. I'm not sure what I should do here to evaluate.
> 
> ```
>     train_model = models.Model([x, y], [out_caps, decoder(masked_by_y)])
>     eval_model = models.Model(x, [out_caps, decoder(masked)])
> ```
> Here, if I pass something like `train_model .evaluate(x, y )` - an error is obvious because `model.Model([x,y] ....` but what if I pass something like `eval_model.evaluate(x, y)` - got the same problem?
> 
> On the other hand, by using a cross-validation approach in the way how to find the best model or how to ensemble the model more effectively here. Below is the `model.summary()` of this CapsNet model.
> 
> ```
> __________________________________________________________________________________________________
> Layer (type)                    Output Shape         Param #     Connected to                     
> ==================================================================================================
> input_3 (InputLayer)            (None, 32, 32, 1)    0                                            
> __________________________________________________________________________________________________
> conv1 (Conv2D)                  (None, 24, 24, 128)  10496       input_3[0][0]                                       
> __________________________________________________________________________________________________
> conv2 (Conv2D)                  (None, 16, 16, 256)  2654464     conv1 [0][0]                                   
> __________________________________________________________________________________________________
> primarycap_conv2d (Conv2D)      (None, 4, 4, 256)    5308672     conv2 [0][0]      
> __________________________________________________________________________________________________
> primarycap_reshape (Reshape)    (None, 512, 8)       0           primarycap_conv2d[0][0]          
> __________________________________________________________________________________________________
> primarycap_squash (Lambda)      (None, 512, 8)       0           primarycap_reshape[0][0]         
> __________________________________________________________________________________________________
> digitcaps (CapsuleLayer)        (None, 10, 16)       655360      primarycap_squash[0][0]          
> __________________________________________________________________________________________________
> input_4 (InputLayer)            (None, 10)           0                                            
> __________________________________________________________________________________________________
> mask_3 (Mask)                   (None, 160)          0           digitcaps[0][0]                  
>                                                                  input_4[0][0]                    
> __________________________________________________________________________________________________
> capsnet (Length)                (None, 10)           0           digitcaps[0][0]                  
> __________________________________________________________________________________________________
> decoder (Sequential)            (None, 32, 32, 1)    1657344     mask_3[0][0]                     
> ==================================================================================================
> Total params: 10,287,360
> Trainable params: 10,286,848
> Non-trainable params: 512
> ```
> What I think I'm missing is, an ensemble method I'm approaching here with the last layer of the model is maybe wrong and whereas I should use only
> 
> `capsnet (Length) (None, 10) 0 digitcaps[0][0] `
> 
> to get the model classification output and average the score of each Fold model. But not sure how to do this during the ensembling process. I also think is the there more effective way to ensemble deep learning model!

Here is your problem:
     "Expected to see 2 array(s)"
As you say, you organize it as 10 labels, while you actually have 2 output of labels, therefore your output should be [10_labels, 10_labels]

**Comment by iphton** [comment]
@Tiaspetto I'm sorry, just to make it clear. Do you say I should use `model.evaluate(X_val, [y_val, y_val], verbose = 0)` ... ? Actually, training is really time-consuming, so I just want to make sure to do this.

**Comment by Tiaspetto** [comment]
> @Tiaspetto I'm sorry, just to make it clear. Do you say I should use `model.evaluate(X_val, [y_val, y_val], verbose = 0)` ... ? Actually, training is really time-consuming, so I just want to make sure to do this.

Well, here is your model
# Models for training and evaluation (prediction)
        train_model = models.Model([x, y], [out_caps, decoder(masked_by_y)])
        eval_model = models.Model(x, [out_caps, decoder(masked)])

Your train model has 2 inputs, and 2 outputs
eval model has 1 input, 2 outputs. 
From your code, you only fed 1 list
scores = model.evaluate(X_val, y_val, verbose = 0)
That's problem, your model output 2 list and you want evaluate with 1 list, shape do not match.

**Comment by iphton** [comment]
@Tiaspetto Hey, thanks for your hint. It works actually. I think the first problem is solved. ✌

Can you give some idea about second one. I mean about ensemble method? Much appreciated, Thanks.

**Comment by Tiaspetto** [comment]
> @Tiaspetto Hey, thanks for your hint. It works actually. I think the first problem is solved. ✌
> 
> Can you give some idea about second one. I mean about ensemble method? Much appreciated, Thanks.

As I have post in first comment, you face a type error.  You try to call a 'Sequential' on list type. A list of model is not model.

**Comment by msymp** [comment]
Thank you @Tiaspetto for your help in resolving both parts of this issue. @iphton we shall close this. Thanks.

**Comment by iphton** [comment]
@msymp Ensembling problem remains still. Can you please suggest some way to handle this issue? Using cross-validation approach we get `n_split` times models. How can we find the best model among them? Should we average them or there's something more effective we can do? Thanks.
