### ISSUE TITLE
Which model could be appropriate for multi variate time series with images in train and test, but only continuous features are to be predicted.

### ISSUE THREAD

**Issue by prgrmmraben** [keras-team/keras#12024]
Hi,
The input is a time sequence images, plus other variables. For prediction, the model should be able to predict these variables, when fed with future time sequence of images.

I think of CNN with RNN, still can't make my mind around different train/test nature. (train := images and features, test:= images alone to predict features).

I would like to stick with Tensorflow, Keras, or scikit learn.

My experience was with image classification, which is more common I think, to illustrate Tensorflow, and Keras capabilities.

I couldn't grasp this duality in timeseries prediction, from materials online, I can find that train can be used to predict new future values through autocorrelation, still this prediction could be assisted not only with future time indexes, but also images in this case.

Any help, or hint would be much appreciated.

Thank you.

**Comment by msymp** [comment]
Hello @prgrmmraben , you are asking a theoretical modeling question of sequences of images over time. Unfortunately this is a Keras issue repository. Once you have written Keras/TensorFlow/Python code and followed the steps advised by the Keras wiki site and TensorFlow.org, if you have questions on the build/run issues, please come back. Thanks.
