### ISSUE TITLE
Lambda layer doesn't pass mask properly

### ISSUE THREAD

**Issue by weiguanwang** [keras-team/keras#12027]
Hi everyone, I encountered an issue with the Lambda layer. The inner function of the Lambda layer is supposed to take  the mask tensor passed from the previous layer. I made a simple case where this does not work properly.
```
import numpy as np
import keras

def inner_fn(var, mask=None):
    print('print mask in inner_fn', mask)    
    return mask

arr_in = np.ones((2,3, 3))
arr_in[:, 0, :] = 0.
arr_out = np.ones((2,3,3))

x = keras.Input((None, 3))
mask_layer_out = keras.layers.Masking(mask_value = 0.)(x)
y = keras.layers.Lambda(inner_fn)(mask_layer_out)
model = keras.Model(inputs=x, outputs=y)
model.compile('sgd', 'mse')
model.fit(arr_in, arr_out, epochs=1)
```
With this code, the print in the `inner_fn` is called twice, as follows:
```
print mask in inner_fn Tensor("masking_1/Any_1:0", shape=(?, ?), dtype=bool)
print mask in inner_fn None
```
The first is what I believe is right. But I don't know why there is a second print, and for the second time, the mask is `None`.  Moreover, due to `mask` being `None`, the model can not be compiled, raising 
`AttributeError: 'NoneType' object has no attribute 'get_shape'`

Is this an issue of Lambda layer?
My keras version is  2.2.4, tensorflow 1.12.0, and windows 10.

**Comment by msymp** [comment]
Hello @omalleyt12 , In this code fragment, this user is calling the Keras Masking layer and then printing the result within a Lambda layer that also returns the _y_ value given to create the model with mask being _None_ cannot compile. Can you please advise. Thanks.

**Comment by Strateus** [comment]
Bumping this up, having same issue in tensorflow 2.1:

```
inputs_shape = (2, 1)
inputs = keras.layers.Input(shape=inputs_shape)
masked = keras.layers.Masking(mask_value=-10., input_shape=inputs_shape)(inputs)
output = keras.layers.Lambda(lambda x: x - 0.5)(masked)
model = keras.Model(inputs=inputs, outputs=output)
data = np.array([[1, -10]], dtype=np.float32).reshape(-1, 2, 1)
model(data)
```

expectations is to have 
```
<tf.Tensor: shape=(1, 2, 1), dtype=float32, numpy=
array([[[ 0.5],
        [ 0. ]]], dtype=float32)
```

but i get
```
<tf.Tensor: shape=(1, 2, 1), dtype=float32, numpy=
array([[[ 0.5],
        [-0.5]]], dtype=float32)
```
