### ISSUE TITLE
Different performances speed on Keras and Tensorflow 

### ISSUE THREAD

**Issue by MerceaOtniel** [keras-team/keras#12039]
Hello!

I am currently train a network in Keras, but when i look in nvidia-smi the Volatile Gpu Utils is around 50%. No matter how hard i try, i cannot pass that limit. On the other hand, using Tensorflow on the same model, with the same parameters and everything, i reach 100%. The problem is that in Tensorflow the training is faster with around 50%, so i don't think that those numbers are "errors" provided by nvidia-smi. What could be the problem?

**Comment by Dref360** [comment]
Are you using the same feeding mechanism?

Keras uses a for loop that call `sess.run` for each batch.

**Comment by MerceaOtniel** [comment]
Hello,

Yes, i can confirm that i use TensorFlow backend for Keras. The model is a resnet, the same as in the deep mind paper alphazerogo(so nothing special). I run it on 2080ti using cuda 10. I also run it on 1080ti using cuda 9 and it seems that while tensorflow has 100% usage, on 1080ti keras has somewhere around 90%.

**Comment by MerceaOtniel** [comment]
The main problem is not that it takes longer...it is why it only uses 80-90% of the gpu? What limitation does it has?

**Comment by Dref360** [comment]
The usage is affected by multiple things : 
1- The training loop (ability to create batches efficiently)
2- Some ops are "slower" to execute and you will decrease the usage.
3- IO bound
4- Keras does use allow_soft_placement by default which may cause some surprise memory allocation.

**Comment by jvishnuvardhan** [comment]
@MerceaOtniel Is this still an issue? Could you check with recent version of TF and Keras, and let us know if the issue still persists. thanks!

**Comment by MerceaOtniel** [comment]
I don't know if this is still an issue. I managed to run the code and work on the project using Tensorflow. It was not necessarily a problem, but it seemed odd because TF could use all my GPU and Keras was limited to 90% no matter what. It was more of a curiosity than an actual issue. I don't have the last version of TF, but i had Keras 2.2.4 when i obtained these results. The problem was not performance, but performance was poor due to the fact that Keras was unable to make use of the whole GPU. Right now i cannot install last version of TF to check. I will try in a week, if you have it already installed, then you can test it.

**Comment by jvishnuvardhan** [comment]
For now I will close the issue. If anyone face the same issue, please fill the [template](https://github.com/keras-team/keras/issues/new/choose) and provide a reproducible code. Thanks!
