### ISSUE TITLE
Bug when loading a KerasClassifier from a h5py file

### ISSUE THREAD

**Issue by PhilipMay** [keras-team/keras#12032]
I have saved my keras model as a h5py file: `model.save('my_model.h5')`

Now I want to load it to a KerasClassifier because I need that model as a sklearn estimator. I do this:

```
def load_keras_model():
    return load_model('my_model.h5')

keras_classifier = KerasClassifier(load_keras_model)
```

Now when I call `result = keras_classifier.predict(x_test)`
I am getting this:

```
AttributeError                            Traceback (most recent call last)
<ipython-input-17-fe55954e1a2b> in <module>
----> 1 result = keras_classifier.predict(x_train_resampled)
      2 
      3 result

~/miniconda3/envs/py36/lib/python3.6/site-packages/keras/wrappers/scikit_learn.py in predict(self, x, **kwargs)
    227         kwargs = self.filter_sk_params(Sequential.predict_classes, kwargs)
    228 
--> 229         proba = self.model.predict(x, **kwargs)
    230         if proba.shape[-1] > 1:
    231             classes = proba.argmax(axis=-1)

AttributeError: 'KerasClassifier' object has no attribute 'model'
```

So whats up here?
Is this a keras bug? How do I create a KerasClassifier from a saved file?

- [ok ] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps`

- [ ok] Check that your version of TensorFlow is up-to-date. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ok] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by PhilipMay** [comment]
Someone here https://github.com/keras-team/keras/issues/4274#issuecomment-293932098

Sais:
> Unfortunately, the KerasClassifier code does not call the build_fn until the 'fit' method of the KerasClassifier is called. This would defeat the purpose of persisting the model.

**Comment by sixilli** [comment]
To me it looked like the error might be correct.  Maybe it should reference sequential.py directly? Looking at the predict_class in sequential.py it wants a numpy array as an input.

**Comment by msymp** [comment]
Keras-level issue.
