### ISSUE TITLE
Keras-yolo3 gives AttributeError: 'InputLayer' object has no attribute 'outbound_nodes' with the docker

### ISSUE THREAD

**Issue by postuur** [keras-team/keras#12036]
I'm trying to run keras-yolo3's train.py (https://github.com/qqwweee/keras-yolo3) on the keras docker (https://github.com/keras-team/keras/tree/master/docker), but it yields the following error: 
AttributeError: 'InputLayer' object has no attribute 'outbound_nodes' 
Full error: https://pastebin.com/34tJ8q4A

Everything is up to date (docker and keras-yolo3) as of today.

Any leads on this? To me it seems a problem with the docker, but somehow I still doubt that it might be with keras-yolo3 instead, as it is so old (6 months).

**Comment by gabrieldemarmiesse** [comment]
Please open this issue in https://github.com/qqwweee/keras-yolo3/issues . If you later on have solid evidence that the error comes from the keras codebase, feel free to open a new issue with more details.
