### ISSUE TITLE
cannot limit cpu usage when training or predicting

### ISSUE THREAD

**Issue by deFang** [keras-team/keras#12033]
I have a server with 120 CPU cores, everytime I try to train a neural network, keras just use up all cores. 
```
import tensorflow as tf
from keras import backend as K
config = tf.ConfigProto(intra_op_parallelism_threads=15, inter_op_parallelism_threads=15, \
                        allow_soft_placement=False, device_count = {'CPU': 1}, log_device_placement=True)
session = tf.Session(config=config)
K.set_session(session)
```
the setting goes above, doesn't work at all. Any suggestions?

**Comment by colt18** [comment]
A workaround could be setting processor affinities for python tasks. But still a workaround.
