### ISSUE TITLE
Is it possible to reshape a tensor with shape=(128, 128) to 1D list of tensor value

### ISSUE THREAD

**Issue by dante2608** [keras-team/keras#12048]
Hi all,

I would like to convert the tensor with shape=(128, 128) to 1D list of tensor value to use it later for tf.spare.SpareTensor.

I was trying to run the following code: 

x = tf.zeros([128,128])
y = tf.reshape(x,-1)

But I got error: Shape must be rank 1 but is rank 0 for 'Reshape' (op: 'Reshape') with input shapes: [128,128], [].

Thanks in advance.

**Comment by tRosenflanz** [comment]
y = tf.reshape(x,[-1])

**Comment by msymp** [comment]
@dante2608 , hope @tRosenflanz  response got you going. Should be posted on TensorFlow repo.
[-1] is right syntax, for flattening to scalar.
https://www.quora.com/What-does-the-1-in-the-following-line-of-TensorFlow-code-do-x_image-tf-reshape-x-1-28-28-1
This issue is closed.
