### ISSUE TITLE
VGG16 Tuning 

### ISSUE THREAD

**Issue by sekti92** [keras-team/keras#12043]
I have an error. Please help 

> File "C:/Users/w024029h/PycharmProjects/keras_pretrained/vgg16_tuning.py", line 70, in <module>
>     top_model.add(Conv2D(2622, (1, 1), padding='same'))
> ValueError: Input 0 is incompatible with layer conv2d_16: expected ndim=4, found ndim=2

```
top_model = Sequential()
top_model.add(model)

top_model.add(ZeroPadding2D((1, 1), input_shape=(224,224,3)))
top_model.add(Conv2D(32, (3, 3), padding='same'))
top_model.add(ZeroPadding2D((1, 1)))
top_model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))
top_model.add(MaxPooling2D((2, 2), strides=(2, 2)))

top_model.add(ZeroPadding2D((1, 1)))
top_model.add(Conv2D(128, (3, 3), activation='relu', padding='same'))
top_model.add(ZeroPadding2D((1, 1)))
top_model.add(Conv2D(128, (3, 3), activation='relu', padding='same'))
top_model.add(MaxPooling2D((2, 2), strides=(2, 2)))

top_model.add(ZeroPadding2D((1, 1)))
top_model.add(Conv2D(256, (3, 3), activation='relu', padding='same'))
top_model.add(ZeroPadding2D((1, 1)))
top_model.add(Conv2D(256, (3, 3), activation='relu', padding='same'))
top_model.add(ZeroPadding2D((1, 1)))
top_model.add(Conv2D(256, (3, 3), activation='relu', padding='same'))
top_model.add(MaxPooling2D((2, 2), strides=(2, 2)))

top_model.add(ZeroPadding2D((1, 1)))
top_model.add(Conv2D(512, (3, 3), activation='relu', padding='same'))
top_model.add(ZeroPadding2D((1, 1)))
top_model.add(Conv2D(512, (3, 3), activation='relu', padding='same'))
top_model.add(ZeroPadding2D((1, 1)))
top_model.add(Conv2D(512, (3, 3), activation='relu', padding='same'))
top_model.add(MaxPooling2D((2, 2), strides=(2, 2)))

top_model.add(ZeroPadding2D((1, 1)))
top_model.add(Conv2D(512, (3, 3), activation='relu', padding='same'))
top_model.add(ZeroPadding2D((1, 1)))
top_model.add(Conv2D(512, (3, 3), activation='relu', padding='same'))
top_model.add(ZeroPadding2D((1, 1)))
top_model.add(Conv2D(512, (3, 3), activation='relu', padding='same'))
top_model.add(MaxPooling2D((2, 2), strides=(2, 2)))

top_model.add(Conv2D(4096, (7, 7), activation='relu', padding='same'))
top_model.add(Dropout(0.5))
top_model.add(Conv2D(4096, (1, 1), activation='relu', padding='same'))
top_model.add(Dropout(0.5))
top_model.add(Flatten())
top_model.add(Conv2D(2622, (1, 1), padding='same'))
top_model.add(Activation('softmax'))
```

**Comment by abtExp** [comment]
You're using Conv2D with a flattened input, Conv2D doesn't work with 1D, Flatten converts N-D to 1D, Use the Flatten layer after the Conv2D,

**Comment by sekti92** [comment]
@abtExp I already put Flatten layer after Conv2D. But i had error to load face weight into that model by keeps telling me this error

> ValueError: You are trying to load a weight file containing 16 layers into a model with 17 layers

I am using face weight from this [tutorial](https://sefiks.com/2018/08/06/deep-face-recognition-with-keras/) and the weight file from [here](https://drive.google.com/file/d/1CPSeum3HpopfomUEK1gybeuIVoeJT_Eo/view)

The current code is like this now:
```
from keras import applications
from keras.preprocessing.image import ImageDataGenerator
from keras import optimizers
from keras.models import Sequential
from keras.layers import Dropout, Flatten, Dense, Conv2D, MaxPooling2D, ZeroPadding2D, Activation

# path to the model weights files.
weights_path = './vgg16_face_weights.h5'

# dimensions of our images.
img_width, img_height = 224, 224

train_data_dir = 'database/train'
validation_data_dir = 'database/validation'
nb_train_samples = 46
nb_validation_samples = 26
epochs = 50
batch_size = 3

# build the VGG16 network
model = applications.VGG16(weights='imagenet', include_top=False, input_shape=(224,224,3))
print('Model loaded.')

# build a classifier model to put on top of the convolutional model
top_model = Sequential()
top_model.add(model)

top_model.add(ZeroPadding2D((1, 1), input_shape=(224,224,3)))
top_model.add(Conv2D(32, (3, 3), padding='same'))
top_model.add(ZeroPadding2D((1, 1)))
top_model.add(Conv2D(64, (3, 3), activation='relu', padding='same'))
top_model.add(MaxPooling2D((2, 2), strides=(2, 2)))

top_model.add(ZeroPadding2D((1, 1)))
top_model.add(Conv2D(128, (3, 3), activation='relu', padding='same'))
top_model.add(ZeroPadding2D((1, 1)))
top_model.add(Conv2D(128, (3, 3), activation='relu', padding='same'))
top_model.add(MaxPooling2D((2, 2), strides=(2, 2)))

top_model.add(ZeroPadding2D((1, 1)))
top_model.add(Conv2D(256, (3, 3), activation='relu', padding='same'))
top_model.add(ZeroPadding2D((1, 1)))
top_model.add(Conv2D(256, (3, 3), activation='relu', padding='same'))
top_model.add(ZeroPadding2D((1, 1)))
top_model.add(Conv2D(256, (3, 3), activation='relu', padding='same'))
top_model.add(MaxPooling2D((2, 2), strides=(2, 2)))

top_model.add(ZeroPadding2D((1, 1)))
top_model.add(Conv2D(512, (3, 3), activation='relu', padding='same'))
top_model.add(ZeroPadding2D((1, 1)))
top_model.add(Conv2D(512, (3, 3), activation='relu', padding='same'))
top_model.add(ZeroPadding2D((1, 1)))
top_model.add(Conv2D(512, (3, 3), activation='relu', padding='same'))
top_model.add(MaxPooling2D((2, 2), strides=(2, 2)))

top_model.add(ZeroPadding2D((1, 1)))
top_model.add(Conv2D(512, (3, 3), activation='relu', padding='same'))
top_model.add(ZeroPadding2D((1, 1)))
top_model.add(Conv2D(512, (3, 3), activation='relu', padding='same'))
top_model.add(ZeroPadding2D((1, 1)))
top_model.add(Conv2D(512, (3, 3), activation='relu', padding='same'))
top_model.add(MaxPooling2D((2, 2), strides=(2, 2)))

top_model.add(Conv2D(4096, (7, 7), activation='relu', padding='same'))
top_model.add(Dropout(0.5))
top_model.add(Conv2D(4096, (1, 1), activation='relu', padding='same'))
top_model.add(Dropout(0.5))
top_model.add(Conv2D(2622, (1, 1), padding='same'))
top_model.add(Flatten())
top_model.add(Activation('softmax'))

# note that it is necessary to start with a fully-trained
# classifier, including the top classifier,
# in order to successfully do fine-tuning
# top_model = Model(inputs=model.input, outputs=model.layers[-2].output)
top_model.load_weights(weights_path)

top_model.summary()

# add the model on top of the convolutional base

# set the first 25 layers (up to the last conv block)
# to non-trainable (weights will not be updated)
for layer in model.layers[:25]:
    layer.trainable = False

# compile the model with a SGD/momentum optimizer
# and a very slow learning rate.
top_model.compile(loss='categorical_crossentropy',
              optimizer=optimizers.SGD(lr=1e-4, momentum=0.9),
              metrics=['accuracy'])

# prepare data augmentation configuration
train_datagen = ImageDataGenerator(
    rescale=1. / 255,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True)

test_datagen = ImageDataGenerator(rescale=1. / 255)

train_generator = train_datagen.flow_from_directory(
    train_data_dir,
    target_size=(img_height, img_width),
    batch_size=batch_size,
    class_mode='categorical')

validation_generator = test_datagen.flow_from_directory(
    validation_data_dir,
    target_size=(img_height, img_width),
    batch_size=batch_size,
    class_mode='categorical')

# fine-tune the model
history = top_model.fit_generator(
    train_generator,
    steps_per_epoch=nb_train_samples,
    epochs=epochs,
    validation_data=validation_generator,
    validation_steps=nb_validation_samples)

```

**Comment by serengil** [comment]
The last 3 layers of VGG-Face is convolution (Conv2D) layers whereas regular VGG for imagenet is fully connected layers (Dense). In other words, they are different models. 

You put regular VGG into model variable and put VGG-Face into top_model variable. 

1- You confuse the model with the following command. You must remove this first.

`top_model.add(model)`

2- Then, you can load weights of VGG-Face model.

`top_model.load_weights(weights_path)`

3- After then, you can add remove and add layers to VGG-Face. For example, I made a similar implementation in this [repository](https://github.com/serengil/tensorflow-101/blob/master/python/apparent_age_prediction.ipynb). Please look at the code block 26, 27, 28.

**Comment by AnkitRusia** [comment]
### Load a fine tune model in keras ### 
**Error when load a fine Tuned model of Dog Vs Cat**


I am using keras version : 2.1.6

`import matplotlib.pyplot as plt
import keras
import numpy as np
from keras.models import Sequential
from keras.models import load_model
from keras.layers import Activation
from keras.layers.core import Dense, Flatten
from keras.optimizers import Adam
from keras.metrics import categorical_crossentropy
from keras.preprocessing.image import ImageDataGenerator
from keras.layers.normalization import BatchNormalization
from keras.layers.convolutional import *
from sklearn.metrics import confusion_matrix
import itertools


idg = ImageDataGenerator()
train_batch = idg.flow_from_directory('train', classes = ['cat', 'dog'], target_size = (224, 224), batch_size=10)
test_batch = idg.flow_from_directory('test', classes = ['cat', 'dog'], target_size = (224, 224), batch_size=2)
valid_batch = idg.flow_from_directory('valid', classes = ['cat', 'dog'], target_size = (224, 224), batch_size=2)


#Plot Images with labels
def plot(img, figsize = (12, 6), rows = 1, interp = False, titles = None):
    if type(img) is np.ndarray :
        img = np.array(img).astype(np.uint8)
        if img.shape[-1] != 3 :
            img = img.transpose((0, 2, 3, 1))
            
    f = plt.figure(figsize = figsize)
    cols = len(img)//rows if len(img)%2 == 0 else len(img)//rows + 1

    for i in range(len(img)) :
        sp = f.add_subplot(rows, cols, i+1)
        sp.axis('off')
        if titles is not None :
            sp.set_title(titles[i], fontsize = 16)
        plt.imshow(img[i], interpolation = None if interp else 'none')

    plt.show()



img, labels = next(train_batch)
plot(img, titles = labels)



# Use of pretrained model i.e VGG16
vgg16_model = keras.applications.vgg16.VGG16()
vgg16_model.summary()


model_fineTune = Sequential()
for layer in vgg16_model.layers :
    model_fineTune.add(layer)


model_fineTune.layers.pop()

for layer in model_fineTune.layers :
    layer.trainable = False

model_fineTune.add(Dense(2, activation='softmax'))
model_fineTune.summary()
model_fineTune.compile('adam', 'categorical_crossentropy', metrics=['accuracy'])
model_fineTune.fit_generator(train_batch, steps_per_epoch=6, epochs=2,
                    verbose=2, validation_data = valid_batch, validation_steps=1)

predictions = model_fineTune.predict_generator(test_batch, steps=1)
test_imgs, test_labels = next(test_batch)
plot(test_imgs, titles=test_labels)

print(predictions)


model_fineTune.save("DogVsCat.h5")
trained_model = load_model("DogVsCat.h5")  # Here it shows error
`
**Error **
ValueError: Dimension 0 in both shapes must be equal, but are 4096 and 1000. Shapes are [4096,2] and [1000,2]. for 'Assign_62' (op: 'Assign') with input shapes: [4096,2], [1000,2].

I might think that I drop Dense output layer which has 1000 neurons in before and add Dense layer of 2 neurons. 
I don't know how to solve this but I reallt want to save my trained model.

**Comment by SaketChaturvedi** [comment]
Hello @KafeelBasha,

As you tried "To tune the parameters like type of pooling in pre trained Inception model and optimizer in compile() method, with the help of KerasClassifier() and GridSearchCV()."

Same thing I am performing for pre trained Xception model. But, I am also having trouble getting the results. Will you found any solution to use GridSearchCV for pre trained models?

**Comment by SaketChaturvedi** [comment]
> I was trying to tune the parameters like type of pooling in pre trained models and optimizer in compile() method, with the help of KerasClassifier() and GridSearchCV().
> Since as per the documentation 'GridSearchCV' object has no attribute 'fit_generator'. Is there any way I can tune the parameters. Any reference will be helpful.
> 
> #InceptionV3 as base model
> ##Grid search
> def keras_incep(pool='avg',opt='sgd'):
> base_model=InceptionV3(include_top=False,pooling=pool,input_shape=(75,75,3))
> #Stacking layers
> x=base_model.output
> #Fully connected layer
> x=Dense(1024,activation="relu")(x)
> #We have two classes
> predictions=Dense(2,activation="sigmoid")(x)
> #Training Model
> model_class=Model(inputs=base_model.input,outputs=predictions)
> #Freeze base layer
> for layer in base_model.layers:
> layer.trainable=False
> 
> ```
> from keras.metrics import binary_accuracy
> model_class.compile(loss="binary_crossentropy",optimizer=opt,metrics=["binary_accuracy"])
> ```
> 
> ##create model
> from keras.wrappers.scikit_learn import KerasClassifier
> model=KerasClassifier(build_fn=keras_incep,verbose=0,epochs=10,batch_size=500)
> ##Grid parameters definition
> pool=['avg','max']
> opt=['sgd','adam','adagrad']
> param_grid={'pooling':pool,'optimizer':opt}
> 
> from sklearn.model_selection import GridSearchCV
> grid=GridSearchCV(estimator=model,param_grid=param_grid)
> grid_result=grid.fit_generator(gen_train,epochs=10,verbose=1,validation_data=gen_test,shuffle=False)




Hello @KafeelBasha,

As you tried "To tune the parameters like type of pooling in pre trained Inception model and optimizer in compile() method, with the help of KerasClassifier() and GridSearchCV()."

Same thing I am performing for pre trained Xception model. But, I am also having trouble getting the results. Will you found any solution to use GridSearchCV for pre trained models?

Please help me i am stuck.

**Comment by KafeelBasha** [comment]
@SaketChaturvedi 

GridSearchCV() method doesn't seem to implement fit_generator() method, it only implements fit() and score(), this could be the reason for the error.

**Comment by SaketChaturvedi** [comment]
@KafeelBasha 
I am getting an usual error:
"ValueError: Found input variables with inconsistent numbers of samples: [3206, 546]"

I am stuck here. Please help me to solve the problem. Thank you in advance!

Here is my code:

`def createmodel(): x = model.output x = Dropout(0.25)(x) x = Dense(1024, activation='relu')(x) predictions = Dense(7, activation='softmax')(x) model = Model(inputs=model.input, outputs=predictions) model.compile(optimizer='adam', loss='categoricalcrossentropy', metrics=['accuracy'])
return model

from keras.wrappers.scikitlearn import KerasClassifier from sklearn.modelselection import GridSearchCV
from time import time
start = time()
model = KerasClassifier(buildfn = Xception, verbose =1, epochs=40,batchsize=10)
optimizers = ['RMSprop','Adam','SGD','Adagrad','Adadelta']
epochs = [10,20,30,40,50]
batches = [5,10,20,30]
init = ['uniform','normal','zero','glorotuniform'] learnrate = [0.001,0.001,0.1,0.2,0.3]
momentum = [0.0,0.2,0.4,0.6,0.8,0.9]
dropoutrate = [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9] paramgrid = dict(epochs=epochs,optimizers=optimizers,batchsize=batches,learnrate=learnrate,momentum=momentum,initmode=init,dropoutrate=dropoutrate)
grid = GridSearchCV(estimator=model,paramgrid=paramgrid)
gridresult = grid.fit(trainbatches,valid_batches)
`

**Comment by KafeelBasha** [comment]
As per the documentation, Keras wrapper doesn't support multi input network. Refer below thread
[https://github.com/keras-team/keras/issues/2748](url)
[https://github.com/keras-team/keras/issues/6451](url)

**Comment by wangyexiang** [comment]
Dear, sir, will you found any solution to use GridSearchCV to implement fit_generator() method? @KafeelBasha

**Comment by KafeelBasha** [comment]
No, as GridSearchCV() only supports fit() and score().
