### ISSUE TITLE
could not broadcast input array from shape (1600,860,3) into shape (1)

### ISSUE THREAD

**Issue by sekti92** [keras-team/keras#12045]
I am trying to extract image feature but i keep gives me this error:

> Traceback (most recent call last):
>  File "C:/Users/w024029h/PycharmProjects/keras_pretrained/pretrained_vgg16.py", line 41, in <module>
>     x_train = np.array(images)
> ValueError: could not broadcast input array from shape (1600,860,3) into shape (1)

This is my actual code:

```
from pathlib import Path
import numpy as np
import joblib
from keras.preprocessing import image
from keras.applications import vgg16
import os.path

# Path to folders with training data
img_db = Path("database") / "train"

images = []
labels = []

# Load all the not-dog images
for file in img_db.glob("*/*.jpg"):

    file = str(file)

    # split path with filename
    pathname, filename = os.path.split(file)
    person = pathname.split("\\")[-1]

    print("Processing file: {}".format(file))

    # Load the image from disk
    img = image.load_img(file)

    # Convert the image to a numpy array
    image_array = image.img_to_array(img)

    # Add a fourth dimension (since Keras expects a list of images)
    image_array = np.expand_dims(image_array, axis=0)

    # Add the image to the list of images
    images.append(image_array)

    # For each 'not dog' image, the expected value should be 0
    labels.append(person)

# Create a single numpy array with all the images we loaded
x_train = np.array(images)

# Also convert the labels to a numpy array
y_train = np.array(labels)

# Normalize image data to 0-to-1 range
x_train = vgg16.preprocess_input(x_train)

input_shape = (224, 224, 3)
# Load a pre-trained neural network to use as a feature extractor
pretrained_nn = vgg16.VGG16(weights='imagenet', include_top=False, input_shape=input_shape)

# Extract features for each image (all in one pass)
features_x = pretrained_nn.predict(x_train)

# Save the array of extracted features to a file
joblib.dump(features_x, "x_train.dat")

# Save the matching array of expected values to a file
joblib.dump(y_train, "y_train.dat")

```

**Comment by ParikhKadam** [comment]
`images = []`  --- Images is a list... Ok!

```
# Add a fourth dimension (since Keras expects a list of images)
image_array = np.expand_dims(image_array, axis=0)
```
Keras expects a ~list~ batch (type=tensor) of images. But the code is correct!

```
# Create a single numpy array with all the images we loaded
x_train = np.array(images)
```
This code has the problem. You are asking numpy to create a new array from a list of arrays. How?

You have a list of images where each image is a numpy array of shape `(1, height, width, number_of_channels)`. Now, you need to create a batch of images from the given list. How do you do that?

The shape of input to the model should be `(batch_size, height, width, number_of_channels)`. How do you change **1** to **batch_size** (i.e. number of images in the list)? A simple way to **_concatenate the tensors at axis 0_**.

Hence, replace the code
`x_train = np.array(images)`
with
`x_train = np.concatenate(images, axis=0)`

I should solve the problem.

**Comment by sekti92** [comment]
@ParikhKadam Thanks its solved

**Comment by ParikhKadam** [comment]
@sekti92 Welcome.. Can you please close this issue now?
