### ISSUE TITLE
What happen to the images smaller than 197 x 197 px for transfer learning with resnet50 using new version of Keras (2.2.4)

### ISSUE THREAD

**Issue by masih4** [keras-team/keras#12059]
Hello,
In the Keras older versions, you could not pass images smaller than 197x197 px when using the resnet50 network. However, in the new version (i.e. 2.2.4) it is possible to do that. I am wondering what is happening? Maybe Keras performs some sort of resizing or zero padding internally?

Cheers,

**Comment by msymp** [comment]
@masih4 , Currently at 2.2.4 the lower limit for width and height should be no smaller than 32. We shall close this issue. Thanks.
