### ISSUE TITLE
Calculating mean for flow_from_directory

### ISSUE THREAD

**Issue by colt18** [keras-team/keras#12055]
Just as explained here
https://github.com/keras-team/keras/issues/5532
We need some standardization for flow_from_directory. Currently we could use datagen.fit() to calculate std, mean, and principal components if ZCA whitening is applied. What we need is some directory iterator that can calculate these parameters along whole train set.

**Comment by JoshuaRM** [comment]
I am interested in working on this feature/issue

**Comment by gabrieldemarmiesse** [comment]
Could you open this issue in https://github.com/keras-team/keras-preprocessing/issues ? Thanks!

**Comment by austinmw** [comment]
@JoshuaRM please see https://github.com/keras-team/keras-preprocessing/issues/142
