### ISSUE TITLE
this is my error message "input that isn't a symbolic tensor"

### ISSUE THREAD

**Issue by aminemosbah** [keras-team/keras#12078]
Please make sure that the boxes below are checked before you submit your issue.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps`

- [ ] Check that your version of TensorFlow is up-to-date. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by gabrieldemarmiesse** [comment]
> Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

We cannot help you with just an error message. Please open a new issue with more details.

**Comment by aminemosbah** [comment]
hi, 
just verified the requirements, and still, the same error is popping up over and over again;
here is the code for Mask_RCNN implemenation
# create model in inference model
with tf.device(DEVICE):
    model=modellib.MaskRCNN(mode="inference",model_dir=MODEL_DIR,
                           config=config)
#########################################"
and here is the error

ValueError                                Traceback (most recent call last)
c:\users\acer\anaconda3\envs\aminemask\lib\site-packages\keras\engine\base_layer.py in assert_input_compatibility(self, inputs)
    278             try:
--> 279                 K.is_keras_tensor(x)
    280             except ValueError:

All inputs to the layer should be tensors.
###################################
seems there is incompatibility of the inpute in the based_layer.py
 any suggesion 
Thanks
