### ISSUE TITLE
Wrong input variable used( it seems) 

### ISSUE THREAD

**Issue by rohitc01** [keras-team/keras#12079]
In line number 125 of the code encoder_inputs variable takes value of num_encoder_tokens as one of the inputs in place of encoder_input_data
`encoder_inputs = Input(shape=(None, num_encoder_tokens))`
Similarly following code for decoder inputs should take encoder_states
`decoder_inputs = Input(shape=(None, num_decoder_tokens))`

Please correct if I am wrong

**Comment by abhaikollara** [comment]
You're referring to "line number 125 of the code", I am unable to find any code in the issue

**Comment by msymp** [comment]
@rohitc01 , can you please provide the entire code for your example, and illustrate your query clearly? Thanks.

**Comment by jvishnuvardhan** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
