### ISSUE TITLE
datagen.flow_from_dataframe erro after last update

### ISSUE THREAD

**Issue by khaledbnmohamed** [keras-team/keras#12089]
An Error just popped-up tonight after the last update today 

for a line ```

```
 train_generator=datagen.flow_from_dataframe(dataframe=df_train, directory=None,x_col="Img_Path",
                                              y_col="Label", class_mode="binary", target_size=(224,224), batch_size=batch)
```

Error :
TypeError: If class_mode="binary", y_col="Label" column values must be strings.

the code was working fine just before the last Keras commit as I'm using the latest version

**Comment by gabrieldemarmiesse** [comment]
Thanks for the report, can you please open this issue in https://github.com/keras-team/keras-preprocessing/issues Thanks!

**Comment by alkra1** [comment]
i also had this issue - cant find a resolution anywhere?

**Comment by hakeemta** [comment]
https://github.com/keras-team/keras-preprocessing/issues/152

**Comment by alkra1** [comment]
thanks. but this never used to be a problem? ive been running it for weeks. and why does binary require string? assistance appreciated

**Comment by alkra1** [comment]
and then i changed to string:
df['R_eye'] = df['R_eye'].apply(str)
is_string_dtype(df['R_eye'])
True

and got same error
