### ISSUE TITLE
Unable to find my files

### ISSUE THREAD

**Issue by marrman** [keras-team/keras#12088]
When I run the code I get the error:
`FileNotFoundError: [Errno 2] No such file or directory: ' /home/ryan/Desktop/Art.jpg'`
However I know this picture exists at this location because when I execute `Locate Art.jpg` I get `/home/ryan/Desktop/Art.jpg`

**Comment by abhaikollara** [comment]
Please provide code that can reproduce this error

**Comment by Dref360** [comment]
There is a space in your path.
