### ISSUE TITLE
Multiprocessing with model.fit_generator and data augmentation

### ISSUE THREAD

**Issue by wittmarf** [keras-team/keras#12083]
I need to use the model.fit_generator method with use_multiprocessin=True and workers>1 because I want to parallelize augmentation.

The Keras ImageDataGenerator would be a perfect match for the model.fit_generator. But several people found out, that this causes problems because of lacking thread safety. 

Is there a simple way to make those two work together? Not everyone working with Keras wants (or is able) to write a data generator from scratch.

It would be greatly appreciated if you would give an example in the documentation.
In my case, the images that need to be augmented are in directories. One for each class,

Thanks!

**Comment by gabrieldemarmiesse** [comment]
Please submit your issue in keras-team/keras_preprocessing. Thanks!
