### ISSUE TITLE
Feature Request : Add Capsule Layer to convolutional.py

### ISSUE THREAD

**Issue by SriRangaTarun** [keras-team/keras#12097]
I request that the Capsule Layer be added to convolutional.py. It has achieved excellent results when used in many Computer Vision and NLP problems. I already have an implementation ready. I can go ahead with a PR if the people involved approve of this idea.

**Comment by gabrieldemarmiesse** [comment]
This is a good idea, I suggest you make a PR for keras_contrib and if we see that it gets traction in the keras community, we'll integrate it in core keras :)
