### ISSUE TITLE
Incompatibility of the inpute in the based_layer.py Keras 

### ISSUE THREAD

**Issue by aminemosbah** [keras-team/keras#12099]
Please make sure that the boxes below are checked before you submit your issue.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.

Thank you!

- [ ] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps`

- [ ] Check that your version of TensorFlow is up-to-date. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by aminemosbah** [comment]
hi,
just verified the requirements, and still, the same error is popping up over and over again;
here is the code for Mask_RCNN implemenation

create model in inference model

with tf.device(DEVICE):
model=modellib.MaskRCNN(mode="inference",model_dir=MODEL_DIR,
config=config)
#########################################"
and here is the error

ValueError Traceback (most recent call last)
c:\users\acer\anaconda3\envs\aminemask\lib\site-packages\keras\engine\base_layer.py in assert_input_compatibility(self, inputs)
278 try:
--> 279 K.is_keras_tensor(x)
280 except ValueError:

All inputs to the layer should be tensors.
###################################
seems there is incompatibility of the inpute in the based_layer.py
any suggesion
Thanks

**Comment by gabrieldemarmiesse** [comment]
We cannot help you until you provide a *minimal* standalone example to reproduce the error as well as the full error message.

**Comment by aminemosbah** [comment]
hi I m trying to run the balloon MaskRCNN example on my PC (Intel core I3, windows10,  2GHz, Intel HD Graphics 520, 4GB DDR4 Memory, no  GPU) cloned from https://github.com/matterport/Mask_RCNN/tree/master/samples/balloon
#######################################
here is the code 
#############
import os
import sys
import random
import math
import numpy as np
import skimage.io
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import tensorflow as tf
from tensorflow.keras import layers
print(tf.VERSION)
print(tf.keras.__version__)
out:: 
1.12.0
2.1.6-tf
# Root directory of the project
ROOT_DIR = os.path.abspath("../../")

# Import Mask RCNN
sys.path.append(ROOT_DIR)  # To find local version of the library
from mrcnn import utils
import mrcnn.model as modellib
from mrcnn import visualize
from mrcnn.visualize import display_images
#import mrcnn.model import log

from samples.balloon import balloon

%matplotlib inline

#directory to save logs and trained model
MODEL_DIR=os.path.join(ROOT_DIR,"logs")

BALLON_WRIGHTS_PATH="C:/Users/ACER/Anaconda3/envs/aminemask/Mask_RCNN/mask_rcnn_balloon.h5"
BALLOON_DIR= 'C:/Users/ACER/Anaconda3/envs/aminemask/Mask_RCNN/data_sets/balloon'
#####################################################
config=balloon.BalloonConfig()
print(config)
class InferenceConfig(config.__class__):
    # Set batch size to 1 since we'll be running inference on
    # one image at a time. Batch size = GPU_COUNT * IMAGES_PER_GPU
    CPU_COUNT = 3
    IMAGES_PER_CPU = 1
    GPU_COUNT = 0
    IMAGES_PER_GPU = 0

config = InferenceConfig()
config.display()

out::Configurations:
BACKBONE                       resnet101
BACKBONE_STRIDES               [4, 8, 16, 32, 64]
BATCH_SIZE                     3
BBOX_STD_DEV                   [0.1 0.1 0.2 0.2]
COMPUTE_BACKBONE_SHAPE         None
CPU_COUNT                      3
DETECTION_MAX_INSTANCES        100
DETECTION_MIN_CONFIDENCE       0.9
DETECTION_NMS_THRESHOLD        0.7
FPN_CLASSIF_FC_LAYERS_SIZE     1024
GPU_COUNT                      0
GRADIENT_CLIP_NORM             5.0
IMAGES_PER_CPU                 1
IMAGES_PER_GPU                 0
IMAGE_CHANNEL_COUNT            3
IMAGE_MAX_DIM                  1024
IMAGE_META_SIZE                14
IMAGE_MIN_DIM                  800
IMAGE_MIN_SCALE                0
IMAGE_RESIZE_MODE              square
IMAGE_SHAPE                    [1024 1024    3]
LEARNING_MOMENTUM              0.9
LEARNING_RATE                  0.001
LOSS_WEIGHTS                   {'rpn_class_loss': 1.0, 'rpn_bbox_loss': 1.0, 'mrcnn_class_loss': 1.0, 'mrcnn_bbox_loss': 1.0, 'mrcnn_mask_loss': 1.0}
MASK_POOL_SIZE                 14
MASK_SHAPE                     [28, 28]
MAX_GT_INSTANCES               100
MEAN_PIXEL                     [123.7 116.8 103.9]
MINI_MASK_SHAPE                (56, 56)
NAME                           balloon
NUM_CLASSES                    2
POOL_SIZE                      7
POST_NMS_ROIS_INFERENCE        100
POST_NMS_ROIS_TRAINING         200
PRE_NMS_LIMIT                  600
ROI_POSITIVE_RATIO             0.33
RPN_ANCHOR_RATIOS              [0.5, 1, 2]
RPN_ANCHOR_SCALES              (32, 64, 128, 256, 512)
RPN_ANCHOR_STRIDE              1
RPN_BBOX_STD_DEV               [0.1 0.1 0.2 0.2]
RPN_NMS_THRESHOLD              0.7
RPN_TRAIN_ANCHORS_PER_IMAGE    25
STEPS_PER_EPOCH                100
TOP_DOWN_PYRAMID_SIZE          256
TRAIN_BN                       False
TRAIN_ROIS_PER_IMAGE           200
USE_MINI_MASK                  True
USE_RPN_ROIS                   True
VALIDATION_STEPS               5
WEIGHT_DECAY                   0.0001

####################
#Preferences 

DEVICE="/cpu:0"
TEST_MODE="inference"
def get_ax(rows=1, cols=1,size=16):
    _, ax=plt.subplots(rows,cols,figsize=(size*cols, size*rows))
    return ax
#load validation dataset
dataset=balloon.BalloonDataset()
dataset.load_balloon(BALLOON_DIR,"val")

dataset.prepare()

print("images:{}\nClasses: {}".format(len(dataset.image_ids), dataset.class_names))

out: images:13
Classes: ['BG', 'balloon']
##########################
import tensorflow as tf
from tensorflow.keras import layers
################
# create model in inference model
with tf.device(DEVICE):
    model=modellib.MaskRCNN(mode="inference",model_dir=MODEL_DIR,
                           config=config)
 ###################and here is where i get stuked 

ValueError                                Traceback (most recent call last)
c:\users\acer\anaconda3\envs\aminemask\lib\site-packages\keras\engine\base_layer.py in assert_input_compatibility(self, inputs)
    278             try:
--> 279                 K.is_keras_tensor(x)
    280             except ValueError:

c:\users\acer\anaconda3\envs\aminemask\lib\site-packages\keras\backend\tensorflow_backend.py in is_keras_tensor(x)
    480         raise ValueError('Unexpectedly found an instance of type `' +
--> 481                          str(type(x)) + '`. '
    482                          'Expected a symbolic tensor instance.')

ValueError: Unexpectedly found an instance of type `<class 'list'>`. Expected a symbolic tensor instance.

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-17-32c41f47f0c0> in <module>
      2 with tf.device(DEVICE):
      3     model=modellib.MaskRCNN(mode="inference",model_dir=MODEL_DIR,
----> 4                            config=config)

~\Anaconda3\envs\aminemask\Mask_RCNN\mrcnn\model.py in __init__(self, mode, config, model_dir)
   1836         self.model_dir = model_dir
   1837         self.set_log_dir()
-> 1838         self.keras_model = self.build(mode=mode, config=config)
   1839 
   1840     def build(self, mode, config):

~\Anaconda3\envs\aminemask\Mask_RCNN\mrcnn\model.py in build(self, mode, config)
   2037                                      config.POOL_SIZE, config.NUM_CLASSES,
   2038                                      train_bn=config.TRAIN_BN,
-> 2039                                      fc_layers_size=config.FPN_CLASSIF_FC_LAYERS_SIZE)
   2040 
   2041             # Detections

~\Anaconda3\envs\aminemask\Mask_RCNN\mrcnn\model.py in fpn_classifier_graph(rois, feature_maps, image_meta, pool_size, num_classes, train_bn, fc_layers_size)
    924     # Shape: [batch, num_rois, POOL_SIZE, POOL_SIZE, channels]
    925     x = PyramidROIAlign([pool_size, pool_size],
--> 926                         name="roi_align_classifier")([rois, image_meta] + feature_maps)
    927     # Two 1024 FC layers (implemented with Conv2D for consistency)
    928     x = KL.TimeDistributed(KL.Conv2D(fc_layers_size, (pool_size, pool_size), padding="valid"),

c:\users\acer\anaconda3\envs\aminemask\lib\site-packages\keras\engine\base_layer.py in __call__(self, inputs, **kwargs)
    412                 # Raise exceptions in case the input is not compatible
    413                 # with the input_spec specified in the layer constructor.
--> 414                 self.assert_input_compatibility(inputs)
    415 
    416                 # Collect input shapes to build layer.

c:\users\acer\anaconda3\envs\aminemask\lib\site-packages\keras\engine\base_layer.py in assert_input_compatibility(self, inputs)
    283                                  'Received type: ' +
    284                                  str(type(x)) + '. Full input: ' +
--> 285                                  str(inputs) + '. All inputs to the layer '
    286                                  'should be tensors.')
    287 

ValueError: Layer roi_align_classifier was called with an input that isn't a symbolic tensor. Received type: <class 'list'>. Full input: [[], <tf.Tensor 'input_image_meta:0' shape=(?, 14) dtype=float32>, <tf.Tensor 'fpn_p2/BiasAdd:0' shape=(?, ?, ?, 256) dtype=float32>, <tf.Tensor 'fpn_p3/BiasAdd:0' shape=(?, ?, ?, 256) dtype=float32>, <tf.Tensor 'fpn_p4/BiasAdd:0' shape=(?, ?, ?, 256) dtype=float32>, <tf.Tensor 'fpn_p5/BiasAdd:0' shape=(?, ?, ?, 256) dtype=float32>]. All inputs to the layer should be tensors.


thanks for your help

**Comment by gabrieldemarmiesse** [comment]
I see that you opened an issue in the maskrcnn repo. This was the right thing to do. Let's wait for their answer. If you get confirmation that the bug comes from the keras codebase feel free to reopen this issue.

**Comment by aminemosbah** [comment]
yes, but the same issue is pending there for months without any ansewer, 
i m pretty sure that the trouble comes from the  keras\engine\base_layer.py file 
regards

**Comment by aminemosbah** [comment]
hi, any suggestions ?
