### ISSUE TITLE
Multi GPU for data evaluation

### ISSUE THREAD

**Issue by EdouardDKP** [keras-team/keras#12101]
Dear all,
I would like to use multi gpu for the data evaluation. During my web searches, I always see training with multi gpu but not for the evaluation.
Is it possible to do that with Keras ?
Thanks in advance
Best regards

**Comment by gabrieldemarmiesse** [comment]
Yes it is. The setup is exactly the same than for training. Just use `multi_gpu_model` and use it for whatever you wish.
