### ISSUE TITLE
keras API for model computation cost

### ISSUE THREAD

**Issue by Ezereal** [keras-team/keras#12102]
Hi,
Recently, i want to get my different models' computation cost. Have anyone known some related API in keras? Thank you!

**Comment by msymp** [comment]
@Ezereal , Assuming you are utilizing a TensorFlow backend, you can utilize the official benchmarks:
https://www.tensorflow.org/guide/performance/benchmarks

Something that is not supported and deprecated, but you could try:
https://github.com/tensorflow/benchmarks/tree/master/scripts/keras_benchmarks

**Comment by jvishnuvardhan** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
