### ISSUE TITLE
UserWarning: The output shape of `ResNet50(include_top=False)` has been changed since Keras 2.2.0.   warnings.warn('The output shape of `ResNet50(include_top=False)` '

### ISSUE THREAD

**Issue by yasaswinir** [keras-team/keras#12108]
I have been trying to train a Resnet50 model , though the training begins , i get the warning above. The keras 2.2.0 documentation indicates an argument like this. Am i doing something wrong??
I have initialised my model like this

base_model = resnet50.ResNet50(include_top=False,
					  		   weights='imagenet',
					  		   input_shape=(img_width,img_height,3),
					  		   classes=2,
					  		   pooling=None)

**Comment by gabrieldemarmiesse** [comment]
Please use the most recent version of keras from github when reporting bugs. Thank you.
