### ISSUE TITLE
How can I test a model with only partial layer of the trained model?

### ISSUE THREAD

**Issue by HyunkyuPark-biorobotics** [keras-team/keras#12117]
Hello everyone.

I am trying to test with a partial layer of trained model, but there is some problem I cannot overcome it.

When the layer was extracted in this way, 

%       x_test=np.transpose(np.loadtxt("dv_temp.csv", delimiter=","));
%       x = model.get_layer("reshape_24")(x_test)
%       x = model.get_layer("conv2d_46")(x)

%      np.savetxt("temp_result.csv", x, delimiter=",")

" Layer reshape_24 was called with an input that isn't a symbolic tensor. Received type: <class 'numpy.ndarray'>"

occured.

To change an input into tensor format I used this function

%       x_test=tf.convert_to_tensor(x_test);

But, the error like below was shown.

"Expected 1D or 2D array, got 0D array instead"

Can anyone help me to solve this problem?

Thank you so much.

**Comment by Tiaspetto** [comment]
You actually need build a new model with only this layer,  and load weights by name to initial this layer. Then using predict to produce output.
