### ISSUE TITLE
Custom Keras Layer and KerasClassifier

### ISSUE THREAD

**Issue by RomainCendre** [keras-team/keras#12128]
Hi everyone,
I'm trying to use KerasClassifier from keras wrapper, but I'm getting stuck on small part.
I have a custom layer made for Keras, but seems incompatible with KerasClassifier.
When sklearn is doing GridSearch, it copies model using deepcopy method, that call unpickle_model. But here is the problem: unpickle_model call _deserialize_model without custom objects... So my layer is not recognize.
Does exist a way to register custom classes to be natively recognize by keras?
Best regards,

**Comment by RomainCendre** [comment]
Ok find a solution, instead of using custom_object argument, just inject your layer in keras module like : 
        keras.layers.RandomLayer = RandomLayer

Thanks to @bstriner from #4990

**Comment by gabrieldemarmiesse** [comment]
There should be an easier way than monkeypatching the module.
