### ISSUE TITLE
Pretrained embedding example should use UNK token for unknown tokens

### ISSUE THREAD

**Issue by bjherger** [keras-team/keras#12124]
The [pretrained embeddings example](https://github.com/keras-team/keras/blob/master/examples/pretrained_word_embeddings.py) replaces any unknown tokens with the zero vector. This can actually cause poorer results, as the `UNK` token is designed to replace unkonwn / low frequency words for the [glove](https://groups.google.com/forum/#!searchin/globalvectors/unk|sort:date/globalvectors/9w8ZADXJclA/hRdn4prm-XUJ) and other embeddings. 

The example should replace words not in the embedding w/ UNK instead of zeros. 

BH

Please make sure that the boxes below are checked before you submit your issue.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.

Thank you!

- [X] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps`

- [X] Check that your version of TensorFlow is up-to-date. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [X] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by abhaikollara** [comment]
There is no `UNK` token in GloVe vectors according to this [stackoverflow answer](https://stackoverflow.com/a/53717345/6873695). But it does suggest that it is better to use an average of all vectors in such case.
