### ISSUE TITLE
Unexpected keyword argument 'expand_nested'

### ISSUE THREAD

**Issue by jordanott** [keras-team/keras#12145]
I have a model composed of nested models. I'm trying to use expand_nested to visualize the sub-models but get this error. I'm using keras 2.2.4. 

`TypeError: plot_model() got an unexpected keyword argument 'expand_nested'`

I've seen this work for other users, do I have the wrong version of keras or is this a bug with the current release?

`from keras.utils import plot_model`
`plot_model(model, to_file='file_name.png', expand_nested=True)`

**Comment by dinoking1975** [comment]
Try to download keras from https://github.com/keras-team/keras and then using [keras] folder from GIT tree to replace what in Pyhton installation folder, such as Python36\Lib\site-packages\keras.

**Comment by ckyleda** [comment]
I also have this issue.

We shouldn't need to mess around with the Python packages to solve this - what's the root cause? 

Has the pip package not been updated correctly?

**Comment by ckyleda** [comment]
This remains an issue.

**Comment by samvaran** [comment]
I have Keras 2.2.4 and have this issue as well

**Comment by csvance** [comment]
Looking in the 2.2.4 source code this argument is not present at all. Would be a nice option certainly.
