### ISSUE TITLE
How Keras use Glorot Uniform and Relu?

### ISSUE THREAD

**Issue by sekti92** [keras-team/keras#12140]
i want to ask how Keras process an input using **Glorot uniform initializer** and **relu activation**? 
I am confused how Keras process the input

For example i have a code like this
```
model = Sequential()
model.add(ZeroPadding2D((1, 1), input_shape=(224, 224, 3)))
model.add(Convolution2D(64, (3, 3), activation='relu'))
model.add(ZeroPadding2D((1, 1)))
model.add(Convolution2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2), strides=(2, 2)))

model.add(ZeroPadding2D((1, 1)))
model.add(Convolution2D(128, (3, 3), activation='relu'))
model.add(ZeroPadding2D((1, 1)))
model.add(Convolution2D(128, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2), strides=(2, 2)))

model.add(ZeroPadding2D((1, 1)))
model.add(Convolution2D(256, (3, 3), activation='relu'))
model.add(ZeroPadding2D((1, 1)))
model.add(Convolution2D(256, (3, 3), activation='relu'))
model.add(ZeroPadding2D((1, 1)))
model.add(Convolution2D(256, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2), strides=(2, 2)))

model.add(ZeroPadding2D((1, 1)))
model.add(Convolution2D(512, (3, 3), activation='relu'))
model.add(ZeroPadding2D((1, 1)))
model.add(Convolution2D(512, (3, 3), activation='relu'))
model.add(ZeroPadding2D((1, 1)))
model.add(Convolution2D(512, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2), strides=(2, 2)))

model.add(ZeroPadding2D((1, 1)))
model.add(Convolution2D(512, (3, 3), activation='relu'))
model.add(ZeroPadding2D((1, 1)))
model.add(Convolution2D(512, (3, 3), activation='relu'))
model.add(ZeroPadding2D((1, 1)))
model.add(Convolution2D(512, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2), strides=(2, 2)))

model.add(Convolution2D(4096, (7, 7), activation='relu'))
model.add(Dropout(0.5))
model.add(Convolution2D(4096, (1, 1), activation='relu'))
model.add(Dropout(0.5))
model.add(Convolution2D(2622, (1, 1)))
model.add(Flatten())
model.add(Activation('softmax'))
```
I know the RELU activation function used in ConvNet as the computational step. RELU will set value of any negative elements to 0 otherwise set to 1 if positive. But how they process an input like above.

`Input -> Glorot -> RELU` or `Input -> RELU -> Glorot`? 
Anybody can explain to me?

**Comment by kgrm** [comment]
>RELU will set value of any negative elements to 0 otherwise set to 1 if positive.

That's not the case. Negative elements are zeroed out, whereas the value of non-negative ones is preserved. To put it in python, `relu = lambda x: 0 if x < 0 else x`.

> Anybody can explain to me?

The Glorot initialization applies to the parameters of the convolutional kernel (ie, the filters), not the input. So the inference step is `relu(convolve(input, W))`, where the initial elements of W are drawn from the Glorot uniform distribution (unless the kernel_initializer parameter specifies otherwise).

**Comment by emc5ud** [comment]
A discussion on weight initialization:
https://www.coursera.org/lecture/deep-neural-network/weight-initialization-for-deep-networks-RwqYe
A discussion on activation functions:
https://www.coursera.org/lecture/neural-networks-deep-learning/activation-functions-4dDC1
