### ISSUE TITLE
Store layer for simply storing a value in Keras

### ISSUE THREAD

**Issue by madrugado** [keras-team/keras#12152]
Hello all,

I have found useful sometimes to have a layer which just stores some value and does nothing more. It could be useful when you need to output multiple values from one layer or for debug purposes. I haven't found this in Keras documentation and/or source code, so I've written on myself:

```
class Store(Layer):
    def __init__(self, **kwargs):
        super(Store, self).__init__(**kwargs)

    def call(self, x, mask=None):
        return x

    def compute_mask(self, input_tensor, mask=None):
        return None

    def get_output_shape_for(self, input_shape):
        return input_shape

    def compute_output_shape(self, input_shape):
        return input_shape

```

Hope it will be useful for someone else.

**Comment by gabrieldemarmiesse** [comment]
I don't think this is the right place to post this. GitHub issue are to report bugs in the keras codebase. I recommand you use the keras google groups or the keras slack channel for this.
