### ISSUE TITLE
How can I convert K.map_fn into a Keras Layer ?

### ISSUE THREAD

**Issue by poppintiger** [keras-team/keras#12150]
How should I convert K.map_fn into a Keras Layer by using Lambda layer?
```
def f(element):

    print('run')
    return element+1

inputs2=Input((10,20))
context= tf.map_fn(fn=f,elems=inputs2) 

```

If I want wrap above process in a keras layer:

```
context= Lambda(lambda x: K.map_fn(fn=f,elems=x))(inputs2)
```
There is some thing wrong that the function f will run twice(print‘run’  twice）. How I supposed to do?

**Comment by HuTobias** [comment]
Any updates on this issue? 
I have the same problem.
