### ISSUE TITLE
Implement K.reset_uids() for the cntk backend.

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [keras-team/keras#12161]
This should be fairly easy to do by looking at other backends implementation of the function.

**Comment by todiketan** [comment]
Hi, I would like to implement this as my first issue.

**Comment by khayamgondal** [comment]
@Ryan-Qiyu-Jiang This one should be closed.

**Comment by Ryan-Qiyu-Jiang** [comment]
yep

**Comment by DivyanshuSoni001** [comment]
Hi,
is  this issue already addressed?

**Comment by gabrieldemarmiesse** [comment]
Yes :)
