### ISSUE TITLE
implement K.cumsum and K.cumprod for the cntk backend.

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [keras-team/keras#12163]

**Comment by samJ27** [comment]
Hi, I'd be happy to have a implement some of these if they're good first issues!
Sam

**Comment by swainsubrat** [comment]
Hi, Can I work on this?
Swain

**Comment by abhishek-jana** [comment]
@gabrieldemarmiesse I'd like to work on this issue, please.

**Comment by gabrieldemarmiesse** [comment]
You can, sure. As long as someone didn't do it already.

**Comment by Myeongjoon** [comment]
hello. @gabrieldemarmiesse. I think this issue fixed at https://github.com/keras-team/keras/pull/12306 , https://github.com/keras-team/keras/pull/12536.
