### ISSUE TITLE
Implement K.arange for the cntk backend.

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [keras-team/keras#12164]

**Comment by Surya-06** [comment]
@gabrieldemarmiesse Hey there, I am new here and would like to help with this issue if it isn't already solved. Could you guide me ?

**Comment by jesus255221** [comment]
@gabrieldemarmiesse I am new to the open source community. I wonder if this issue has been solved. If not, can you provide any guidance so that I can work on this issue?

**Comment by KunLee-design** [comment]
Hi, I am also new here. It looks like this issue has been open for while. If it's still up, can I get some guidance also? I want to work on it.

**Comment by purnimapatel** [comment]
hello,how to make changes in its code

**Comment by souradeepmajumdar05** [comment]
would like to work on this issue if it is still open

**Comment by Armaxxx** [comment]
Working on this issue if no PR has been accepted

**Comment by embattle12** [comment]
hey i am new here, and i want to work on this project. can anyone please guide me through this??
