### ISSUE TITLE
Writing my own layer

### ISSUE THREAD

**Issue by marmus12** [keras-team/keras#12179]
Hello I am trying to write my own Keras layer as described in the following page:

[writing own layer](https://github.com/keras-team/keras/blob/c54f0a3611328622f0523188887dc484586f6bf6/docs/templates/layers/writing-your-own-keras-layers.md)

When I run the code below, it yields the following error: 

> TypeError: The added layer must be an instance of class Layer. Found: <class '__main__.MyLayer'>

`
class MyLayer(Layer):
    def __init__(self, output_dim, **kwargs):
        self.output_dim = output_dim
        super(MyLayer, self).__init__(**kwargs)

    def build(self, input_shape):
        assert isinstance(input_shape, list)
        # Create a trainable weight variable for this layer.
        self.kernel = self.add_weight(name='kernel',
                                      shape=(input_shape[0][1], self.output_dim),
                                      initializer='uniform',
                                      trainable=True)
        super(MyLayer, self).build(input_shape)  # Be sure to call this at the end

    def call(self, x):
        assert isinstance(x, list)
        a, b = x
        return [K.dot(a, self.kernel) + b, K.mean(b, axis=-1)]

    def compute_output_shape(self, input_shape):
        assert isinstance(input_shape, list)
        shape_a, shape_b = input_shape
        return [(shape_a[0], self.output_dim), shape_b[:-1]]
    
MyLayer(output_dim = 5)
seq = Sequential()
input_4d = Input(shape=(1,5,5,3), name='input_4d')

seq.add(MyLayer)
seq(input_4d)
`

**Comment by gabrieldemarmiesse** [comment]
try seq.add(MyLayer(output_dim))

**Comment by marmus12** [comment]
> 
> 
> try seq.add(MyLayer(output_dim))

ok I did this, this time it passes the seq.add(MyLayer(output_dim)) 
but it gives the following error in line seq(input_4d):

assert isinstance(input_shape, list)
AssertionError

And it doesnt work with seq.add(MyLayer([output_dim,])) either.
