### ISSUE TITLE
[Dev] Deprecation procedure

### ISSUE THREAD

**Issue by Dref360** [keras-team/keras#12174]
I would like to have a procedure to deprecate something or fix bugs that cannot be fixed because it would cause a major breaking change (like the infamous off by one error in keras.preprocessing.text). 

Right now, we have no resource to achieve this and once we agree to a procedure, it should be added to the wiki and to the CONTRIBUTING.md.

We have several different cases (with my proposition) :
1. Deprecate an argument
	* DeprecateWarning till the next minor.
	* Passed this date, remove
2. Deprecate a function
	* DeprecateWarning for 2 minors.
3. A bug that is fixable, but we did not fix it (off by one)
	* Make a V2 of the function with the bug
	* Add a warning in the faulty function that the user needs to switch to the new version.

If I forgot a case, please add a comment and I'll add it.
I don't think there are many resources to do this *the right way*. I'm open to suggestions.

**Comment by gabrieldemarmiesse** [comment]
I'm not too much in favor of having V2 in the name of a function.

What about this:

```python
def bad_function(...)

# becomes:
def bad_function(..., implementation=None):
    if implementation is None:
         # deprecation warning
         print('Please specify the type of implementation you want in the future, the default will change.')
         implementation = 0

# then after a few releases
def bad_function(...., implementation=None):
      if implementation is None:
            implementation = 1
      elif implementation == 0:
            raise NotImplementedAnymoreError

# then we can remove the implementation keyword from the docs 
# but keep it in the source code for compatibility.
....

This is to change progressively without affecting the API in the long term.

**Comment by fchollet** [comment]
> I'm not too much in favor of having V2 in the name of a function.

I tend to agree with this, in particular because we rely significantly on function / class names during serialization.

What @gabrieldemarmiesse describes is roughly what we have been doing so far. I would prefer doing this.

**Comment by Dref360** [comment]
Alright! I'll make the Wiki page and add the link to the contributing.md.

Thank you!
