### ISSUE TITLE
ValueError: Error when checking target: expected dense_4 to have shape (2,) but got array with shape (4,)

### ISSUE THREAD

**Issue by Dynamic2019** [keras-team/keras#12185]
Hi 
 I use keras for deep learning for big data with 4 class, but when it is two class it run properly but for 4 class it does not work. It shows the above error then please if someone suggest me to improve my code then it will a great pleasure for me 

 my code is 

def read_csv(file_path):
	lines=[]
	pgb=ProgressBar()
	with open(file_path) as file:
		for row in file:
			lines.append(row.strip())
	ll=lines[1].split(",")
	lines.pop(0)
	rows=len(lines)
	mat=np.zeros((rows, len(ll) - 2), np.float)
	instances=[None] * rows
	classes=[None] * rows
	for i in pgb(range(mat.shape[0])):
		s=lines[i].split(",")
		instances[i] = s.pop(0)
		classes[i] = s.pop(-1)
		for j in range(mat.shape[1]):
			mat[i,j]=s[j]
	return mat, classes

def matthews_correlation(y_true, y_pred):
    y_pred_pos = K.round(K.clip(y_pred, 0, 1))
    y_pred_neg = 1 - y_pred_pos
    y_pos = K.round(K.clip(y_true, 0, 1))
    y_neg = 1 - y_pos
    tp = K.sum(y_pos * y_pred_pos)
    tn = K.sum(y_neg * y_pred_neg)
    fp = K.sum(y_neg * y_pred_pos)
    fn = K.sum(y_pos * y_pred_neg)
    numerator = (tp * tn - fp * fn)
    denominator = K.sqrt((tp + fp) * (tp + fn) * (tn + fp) * (tn + fn))
    return numerator / (denominator + K.epsilon())

class roc_callback(Callback):
    def __init__(self,training_data,validation_data):
        self.x = training_data[0]
        self.y = training_data[1]
        self.x_val = validation_data[0]
        self.y_val = validation_data[1]
    def on_train_begin(self, logs={}):
        return
    def on_train_end(self, logs={}):
        return
    def on_epoch_begin(self, epoch, logs={}):
        return
    def on_epoch_end(self, epoch, logs={}):
        y_pred = self.model.predict(self.x)
        roc = roc_auc_score(self.y, y_pred)
        y_pred_val = self.model.predict(self.x_val)
        roc_val = roc_auc_score(self.y_val, y_pred_val)
        print('\rroc-auc: %s - roc-auc_val: %s' % (str(round(roc,4)),str(round(roc_val,4))),end=100*' '+'\n')
        return
    def on_batch_begin(self, batch, logs={}):
        return
    def on_batch_end(self, batch, logs={}):
        return

mat,classes=read_csv(file_path=file_path)

le=LabelEncoder()
le.fit(classes)
labels=le.transform(classes)
nClasses=len(np.unique(labels))
labels=to_categorical(labels)
nClasses=len(np.unique(labels))

model = Sequential()
model.add(Dense(512, activation='sigmoid', input_shape=(mat.shape[1],)))
model.add(Dense(512, activation='sigmoid'))
model.add(Dense(128, activation='sigmoid'))
model.add(Dense(nClasses, activation='softmax'))

model.compile(optimizer='rmsprop', 
              loss='categorical_crossentropy',
              metrics=['accuracy',matthews_correlation,])

X_train, X_test, y_train, y_test = train_test_split(mat, labels, test_size=0.2, random_state=42)

history=model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=5, shuffle = True, callbacks = [roc_callback(training_data=(X_train, y_train),validation_data=(X_test, y_test))])

  Please help me for improving the scripts as soon as possible.

**Comment by emc5ud** [comment]
Could you provide the error message?

**Comment by Dynamic2019** [comment]
Traceback (most recent call last):
  File "lgg.py", line 97, in <module>
    history=model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=5, shuffle = True, callbacks = [roc_callback(training_data=(X_train, y_train),validation_data=(X_test, y_test))])
  File "/home/anil/.pyenv/versions/3.6.1/lib/python3.6/site-packages/keras/engine/training.py", line 950, in fit
    batch_size=batch_size)
  File "/home/anil/.pyenv/versions/3.6.1/lib/python3.6/site-packages/keras/engine/training.py", line 787, in _standardize_user_data
    exception_prefix='target')
  File "/home/anil/.pyenv/versions/3.6.1/lib/python3.6/site-packages/keras/engine/training_utils.py", line 137, in standardize_input_data
    str(data_shape))
ValueError: Error when checking target: expected dense_4 to have shape (2,) but got array with shape (4,)

**Comment by emc5ud** [comment]
What is the shape of y_train and y_test? If I'm reading this right then I think your network expects the Y to be one hot encoded with 4 classes, but your y variables aren't in the right form.

**Comment by Dynamic2019** [comment]
(4,)

**Comment by slideWXY** [comment]
I had a similar problem and I solve it when I just change the optimizer.
In my configuration I start with :
`sgd = SGD(lr=0.001, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(optimizer=sgd, loss='binary_crossentropy', metrics = ['accuracy'])
`

and I changed that to :

`model.compile(optimizer='adam',
          loss='sparse_categorical_crossentropy',
          metrics=['accuracy'])

`

Just tell me if that solve your problem
