### ISSUE TITLE
Issue with Conv1D implementation 

### ISSUE THREAD

**Issue by tobiaspiechowiak** [keras-team/keras#12180]
I simply don't have an idea why the following code does not work on my win 10 machine...

`In [20]:
#load packages
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, GRU, TimeDistributed
from keras.layers import Conv1D, MaxPooling1D, Flatten
from keras.utils import np_utils
In [21]:
nfeat, kernel, timeStep, length, fs = 36, 8, 20, 100, 100
In [34]:
#data (dummy)
data = np.random.rand(length*fs,nfeat)
classes = 0*data[:,0]
classes[:int(length/2*fs)] = 1
In [66]:
#splitting matrix 
#data
X = np.asarray([data[i*timeStep:(i + 1)*timeStep,:] for i in range(0,length * fs // timeStep)])
#classes
Y = np.asarray([classes[i*timeStep:(i + 1)*timeStep] for i in range(0,length * fs // timeStep)])
In [67]:
#split into training and test set
from sklearn.model_selection import train_test_split
trainX, testX, trainY, testY = train_test_split(X,Y,test_size=0.2,random_state=0)
In [68]:
#one-hot-encoding
trainY_OHC = np_utils.to_categorical(trainY)
train_classes_OHC.shape, trainX.shape
Out[68]:
((400, 20, 2), (400, 20, 36))
In [69]:
#set up model with simple 1D convnet
model = Sequential()
model.add(Conv1D(8,kernel,activation='relu',input_shape=(timeStep,nfeat)))
model.add(MaxPooling1D(4))
model.add(Flatten())
model.add(Dense(10,activation='tanh'))
model.add(Dense(2,activation='softmax'))

model.summary()
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
conv1d_8 (Conv1D)            (None, 13, 8)             2312      
_________________________________________________________________
max_pooling1d_8 (MaxPooling1 (None, 3, 8)              0         
_________________________________________________________________
flatten_8 (Flatten)          (None, 24)                0         
_________________________________________________________________
dense_19 (Dense)             (None, 10)                250       
_________________________________________________________________
dense_20 (Dense)             (None, 2)                 22        
=================================================================
Total params: 2,584
Trainable params: 2,584
Non-trainable params: 0
_________________________________________________________________
In [70]:
#compile model
model.compile(loss='mse',optimizer='Adam' ,metrics=['accuracy'])
In [71]:
#train model
model.fit(trainX,trainY_OHC,epochs=5,batch_size=8)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-71-1aa2664ed604> in <module>()
      1 #train model
----> 2 model.fit(trainX,trainY_OHC,epochs=5,batch_size=8)

c:\users\tobias\appdata\local\programs\python\python36\lib\site-packages\keras\engine\training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, **kwargs)
    950             sample_weight=sample_weight,
    951             class_weight=class_weight,
--> 952             batch_size=batch_size)
    953         # Prepare validation data.
    954         do_validation = False

c:\users\tobias\appdata\local\programs\python\python36\lib\site-packages\keras\engine\training.py in _standardize_user_data(self, x, y, sample_weight, class_weight, check_array_lengths, batch_size)
    787                 feed_output_shapes,
    788                 check_batch_axis=False,  # Don't enforce the batch size.
--> 789                 exception_prefix='target')
    790 
    791             # Generate sample-wise weight values given the `sample_weight` and

c:\users\tobias\appdata\local\programs\python\python36\lib\site-packages\keras\engine\training_utils.py in standardize_input_data(data, names, shapes, check_batch_axis, exception_prefix)
    126                         ': expected ' + names[i] + ' to have ' +
    127                         str(len(shape)) + ' dimensions, but got array '
--> 128                         'with shape ' + str(data_shape))
    129                 if not check_batch_axis:
    130                     data_shape = data_shape[1:]

ValueError: Error when checking target: expected dense_20 to have 2 dimensions, but got array with shape (400, 20, 2)
In [72]:
#set up GRU model 
#design the net
m2 = Sequential()
m2.add(GRU(18,input_shape = (timeStep, nfeat),activation='tanh',return_sequences=True,dropout = 0.2))
m2.add(TimeDistributed(Dense(5,activation='softmax')))
In [73]:
#compiling
model.compile(loss='mean_squared_error',optimizer='Adam' ,metrics=['accuracy'])
In [74]:
#fit model
history = model.fit(trainX,trainY_OHC, epochs = 5, batch_size=32)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-74-09fddc70fbc3> in <module>()
      1 #fit model
----> 2 history = model.fit(trainX,trainY_OHC, epochs = 5, batch_size=32)

c:\users\tobias\appdata\local\programs\python\python36\lib\site-packages\keras\engine\training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, **kwargs)
    950             sample_weight=sample_weight,
    951             class_weight=class_weight,
--> 952             batch_size=batch_size)
    953         # Prepare validation data.
    954         do_validation = False

c:\users\tobias\appdata\local\programs\python\python36\lib\site-packages\keras\engine\training.py in _standardize_user_data(self, x, y, sample_weight, class_weight, check_array_lengths, batch_size)
    787                 feed_output_shapes,
    788                 check_batch_axis=False,  # Don't enforce the batch size.
--> 789                 exception_prefix='target')
    790 
    791             # Generate sample-wise weight values given the `sample_weight` and

c:\users\tobias\appdata\local\programs\python\python36\lib\site-packages\keras\engine\training_utils.py in standardize_input_data(data, names, shapes, check_batch_axis, exception_prefix)
    126                         ': expected ' + names[i] + ' to have ' +
    127                         str(len(shape)) + ' dimensions, but got array '
--> 128                         'with shape ' + str(data_shape))
    129                 if not check_batch_axis:
    130                     data_shape = data_shape[1:]

ValueError: Error when checking target: expected dense_20 to have 2 dimensions, but got array with shape (400, 20, 2)
In [ ]:
`
Are there any known issues with keras on win 10?

**Comment by emc5ud** [comment]
I don't think this is a keras or windows error. 
Your model takes in an input tensor shaped [400, 20, 36] and outputs a vector [400, 2]. You can see this in the output of `model.summary()` where the last layer has an Output shape of `(None, 2)`. The `None` simply represents the arbitrary number of examples you can feed in. 

Your Y however has a dimensions [400, 20, 36]. This does not match with the dimension of the model output, so keras throws an error. You either need to change your model architecture, or change your output shape. So that the prediction matches with the Y.

Hope this helps.
