### ISSUE TITLE
Issue of accessing variable value after multiple backend.set_session() calls

### ISSUE THREAD

**Issue by RLstat** [keras-team/keras#12198]
Please make sure that the boxes below are checked before you submit your issue.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps`

- [x] Check that your version of TensorFlow is up-to-date. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

Hi, Keras developers, contributors and experts, 

If I create a variable (in this case an optimizer object `adam`), then I create a tensorflow session and use backend.set_session() to set the session, I can still access the variable after that, (for example, using `adam.get_config()`). However, if I create the session again and set it again, then if I run `adam.get_config()` again, I will get `FailedPreconditionError: Attempting to use uninitialized value Adam_1/lr`. A bit more detail below:
```python
import tensorflow as tf
from keras import optimizers
from keras import backend

adam = optimizers.Adam(lr=0.01)
gpu_count = 1
config = tf.ConfigProto(device_count ={'GPU' : gpu_count})
session = tf.Session(config=config)
backend.set_session(session) 

opt_config = adam.get_config() # this time it runs OK

# let's run one more time
gpu_count = 1
config = tf.ConfigProto(device_count ={'GPU' : gpu_count})
session = tf.Session(config=config)
backend.set_session(session) 

opt_config = adam.get_config() # this time it gives the error.
```

The reason I need to do this is that I have a function that the user can pass a keras optimizer object into. The function also has an argument which allows user to specify how many GPU will be used. However, currently, the function can only run fine for the first time after the keras optimizer object is created, but not again. The simplified function is something like:

```python
import tensorflow as tf
from keras import optimizers
from keras import backend

adam = optimizers.Adam(lr=0.01)

def run_model(optimizer, gpu_count):
    config = tf.ConfigProto(device_count ={'GPU' : gpu_count})
    session = tf.Session(config=config)
    backend.set_session(session)     
    # create model, compile model based on the given optimizer
    # run model, etc. 

run_model(adam, gpu_count=1) # this time runs ok
run_model(adam, gpu_count=1) # this time gives an error
```

Is this behavior expected or an issue? Why it is designed this way if not an issue? Are there ways to get around it to achieve what I want to achieve?

Thanks a lot.

**Comment by PacGiu** [comment]
@RLstat Did you find a work around this? I am facing the same issue. Thanks!

**Comment by RLstat** [comment]
@PacGiu , unfortunately I have not found a way to resolve it yet.
