### ISSUE TITLE
'Could not compute output Tensor' error when I‘m using clone_model()

### ISSUE THREAD

**Issue by Mistariano** [keras-team/keras#12202]
Hi guys, I think I just met a bug. 
There was something wrong when I was using `multi_gpu_model` with `cpu_relocation=True`. After analyzing the traceback I think it is a bug inside `keras.models.clone_model`
The script below can reproduce it

```python
from keras.models import Model, clone_model
from keras.layers import Input, Add, Lambda
from keras.utils import multi_gpu_model


def build_model():
    input_layer = Input(shape=(1,))
    test1, test2 = Lambda(lambda x: [x, x])(input_layer)
    add = Add()([test1, test2])
    model = Model(inputs=[input_layer], outputs=[add])
    return model


if __name__ == '__main__':
    model = build_model()
    model = clone_model(model)
    # model = multi_gpu_model(model, cpu_relocation=True)  # it uses clone_model when set cpu_relocation=True
```
If I didn't make any mistake, the script will raise `AssertionError: Could not compute output Tensor("add_1/add:0", shape=(?, 1), dtype=float32)`

My environment:

- Keras 2.2.4
- tensorflow 1.12.0

I met the error on both 4 GTX1080tis and my own laptop with a GTX1060MQ

------

I noticed that `output_masks` here will always be `[None]`(but `[None, None]` is expected)
https://github.com/keras-team/keras/blob/a1397169ddf8595736c01fcea084c8e34e1a3884/keras/models.py#L157

and that's because `layer.compute_mask(...)` will always return `None` since `Lambda` doesn't support using masks
https://github.com/keras-team/keras/blob/a1397169ddf8595736c01fcea084c8e34e1a3884/keras/models.py#L153

So if I'm using a functional model with a layer which has more outputs without a mask support, I think the error can appear.

------

P.S. thanks a lot for your brilliant works :)  
From my perspective, Keras is an amazing gift to everyone. Thank you all!

**Comment by gabrieldemarmiesse** [comment]
> P.S. thanks a lot for your brilliant works :)
From my perspective, Keras is an amazing gift to everyone. Thank you all!

From the Keras team and all the contributors, you're welcome!

Thanks for the very nice report. I'll flag this as a bug. I'm not very familiar with `multi_gpu_model` so I hope someone else will have the time to look into it.

If you have an idea on how to fix the issue, feel free to do a pull request, pull requests usually get much more attention than issues.

**Comment by ymodak** [comment]
Closing this issue, since the PR has been merged. Thanks!
