### ISSUE TITLE
Add layer to multiply by constant and/or add constant bias

### ISSUE THREAD

**Issue by fredvannijnatten** [keras-team/keras#12215]
I would like to request a very simple layer: multiply inputs by a constant and / or add a constant bias. This can be used to include input normalization into the network. In this way the network can be made more self-contained and distributed with less instructions on how to prepare the inputs.

Furthermore if the network is converted to TensorRT for inference, the multiplication and bias most likely get merged into other convolutional layers making it most efficient.

**Comment by gabrieldemarmiesse** [comment]
This is easily possible in one line with a lambda layer. I believe that putting the preprocessing in the network is a really good idea.

**Comment by fredvannijnatten** [comment]
Yes, but lambda layers cannot be converted automatically to other
formats/frameworks such as onnx or tensorrt.

Op wo 6 feb. 2019 20:42 schreef Gabriel de Marmiesse <
notifications@github.com:

**Comment by gabrieldemarmiesse** [comment]
Why is that?
