### ISSUE TITLE
Convert the docstrings of examples in `examples/*` to use Markdown formatting

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [keras-team/keras#12219]
(e.g. for links and images), because some of these examples are now being rendered in the docs.

Added by @fchollet in requests for contributions.

**Comment by gabrieldemarmiesse** [comment]
See #11758

**Comment by gabrieldemarmiesse** [comment]
Tu add an example to the docs, just modify the file `keras/docs/mkdocs.yml`.

**Comment by joosephook** [comment]
Hi! I'd like to start working on this if possible. Are there any specific guidelines on how visibility should be improved? Or should it be figured out from the two existing examples in mkdocs.yml?

**Comment by gabrieldemarmiesse** [comment]
It's just making sure that the page is rendered correctly in the docs. No need to be fancy.

Also, it is advised to do one pull request per example file. This is faster to review.

**Comment by gabrieldemarmiesse** [comment]
Pull requests should include a screenshot to facilitate the review process.

**Comment by siddsuresh97** [comment]
Can i start working on this issue?

**Comment by hnumair** [comment]
Why this issue is still open? I guess every file is converted for Markdown.

**Comment by gabrieldemarmiesse** [comment]
Some PRs are note merged yet. So we can't really close this issue.

**Comment by marcemq** [comment]
Hi @gabrieldemarmiesse, 

building the documentation using `master` branch, it states that the following pages exist in the docs directory, but are not included in the "nav" configuration:
```
  - examples/class_activation_maps.md
  - examples/mnist_cnn.md
  - examples/mnist_dataset_api.md
  - examples/mnist_denoising_autoencoder.md
  - examples/mnist_hierarchical_rnn.md
  - examples/mnist_irnn.md
  - examples/mnist_mlp.md
  - examples/mnist_net2net.md
  - examples/mnist_siamese.md
  - examples/mnist_sklearn_wrapper.md
  - examples/mnist_swwae.md
  - examples/mnist_tfrecord.md
  - examples/mnist_transfer_cnn.md
  - examples/neural_doodle.md
  - examples/neural_style_transfer.md
  - examples/pretrained_word_embeddings.md
  - examples/reuters_mlp.md
  - examples/reuters_mlp_relu_vs_selu.md
  - examples/tensorboard_embeddings_mnist.md
  - examples/variational_autoencoder.md
  - examples/variational_autoencoder_deconv.md
```

I've worked on those and sent its PR(#12717 - #12763), one per example as you advised.
I hope my PRs get accepted so we can finally close this issue :)

**Comment by qwertpi** [comment]
Is any more help needed on this or not?

**Comment by marcemq** [comment]
Hi @qwertpi, I've covered all examples in `examples/*` directory, once the PRs get merge we can close this issue.

**Comment by PyExtreme** [comment]
Hi @marcemq , @qwertpi , @gabrieldemarmiesse , Is this still an open issue?

I am new to open source and looking to contribute to keras

**Comment by abhinav-mangal** [comment]
I am new to open source and would like to contribute to this code

**Comment by amansaini01** [comment]
hello, I am new to open source and wants to learn and contribute, is this open?
