### ISSUE TITLE
Compliance with the XDG Base Directory Specification

### ISSUE THREAD

**Issue by mjanonis** [keras-team/keras#12210]
Currently, Keras puts all of its configuration files and models into ~/.keras directory on Linux. This clutters up the user's home directory.

Keras could instead put its configuration files to XDG_CONFIG_HOME/keras/ and models to XDG_DATA_HOME/keras/models/.

It would be great if Keras used the standard directories, at least on Linux.

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by yochem** [comment]
Any updates on this?

**Comment by Jappie3** [comment]
It seems like keras is still using ~/.keras for e.g. keras.json. Are you sure this issue was correctly closed as completed? There are no PRs or commits linked...

**Comment by alichtman** [comment]
I can also still reproduce this issue:

```
~/.keras via 💎 v2.5.1 took 32ms
04:26:21 AM ➜ cat keras.json
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: keras.json
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ {
   2   │     "floatx": "float32",
   3   │     "epsilon": 1e-07,
   4   │     "backend": "tensorflow",
   5   │     "image_data_format": "channels_last"
   6   │ }
───────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

~/.keras via 💎 v2.5.1 took 68ms
04:26:24 AM ➜ ll
.rw-r--r-- alichtman staff 120 B Sun May 10 18:30:29 2020  keras.json
```

**Comment by Jappie3** [comment]
@fchollet may I ask why this was closed as 'completed'?

**Comment by yochem** [comment]
Looking at the code @alichtman linked, you can do:

export KERAS_HOME="$XDG_CONFIG_HOME/keras"

**Comment by Jappie3** [comment]
I should not have to manually set env vars so that programs respect the XDG base directory specification... it's there for a reason, can you imagine your home directory if all developers just put their files wherever they wanted?
