### ISSUE TITLE
decoder summary has a output shape as multiple. What does it mean

### ISSUE THREAD

**Issue by pachpandepriti** [keras-team/keras#12213]
![image](https://user-images.githubusercontent.com/29904255/52306796-e791b600-2966-11e9-82eb-84c1df397683.png)
Please make sure that the boxes below are checked before you submit your issue.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.

Thank you!

- [ ] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps`

- [ ] Check that your version of TensorFlow is up-to-date. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by gabrieldemarmiesse** [comment]
It's when layers have multiple outputs, it can't be displayed because of the size. The documentation should mention it. Pull request wecome to modify the documentation and add this.

**Comment by malharjajoo** [comment]
What does it mean for a layer to have multiple outputs ? 

Like in a vanilla CNN, each layer would output 3D volumes right ?
Is that considered as multiple output ( why/why not ?)
