### ISSUE TITLE
Plotted model doesn't render text

### ISSUE THREAD

**Issue by mirgee** [keras-team/keras#12222]
Plotting any model (Sequantial or Functional API) using `plot_model()` shows boxes instead of text:
```
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import plot_model

model = Sequential()
model.add(Dense(units=64, activation='relu', input_dim=100, name='Dense_1'))
model.add(Dense(units=32, activation='relu', input_dim=100, name='Dense_2'))
model.add(Dense(units=10, activation='softmax', name='Softmax'))
model.compile(loss='categorical_crossentropy',
              optimizer='sgd',
              metrics=['accuracy'])
plot_model(model, to_file='./some_model.png', show_layer_names=True)
```

Result:
![some_model](https://user-images.githubusercontent.com/11699479/52416650-5cd9c400-2aea-11e9-9574-d228212cf1e0.png)

Keras: 2.2.4
TF: 1.12.0
pydot: 1.3.0
graphviz: 2.40.1
OS: Arch Linux 4.20.5

**Comment by KappaDistributive** [comment]
I was not able to reproduce this bug under:

Keras: 2.2.5
tensorflow: 1.13.1
pydot: 1.4.1
graphviz: 2.40.1
OS: Fedora 29 with Kernel 5.0.5-200.fc29.x86_64

Could you please update your packages (or set up a new virtual environment with updated packages) and report whether this issue persists?
