### ISSUE TITLE
tf.reshape function using lambda layer in tensorflow backend keras showing error

### ISSUE THREAD

**Issue by pachpandepriti** [keras-team/keras#12236]
Example - size of spectrum is of size (2240,1)
def rehape(spectrum):
    N_Sub=32
   spectrum=tf.manip.reshape(encode_complex,[(tf.size(encode_complex)/N_Sub),N_Sub])
   return spectrum
The resulting size is (2240,1) instead of (70,32)
Can anyone help me where I am going wrong?
Please make sure that the boxes below are checked before you submit your issue.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.

Thank you!

- [ ] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps`

- [ ] Check that your version of TensorFlow is up-to-date. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by ymodak** [comment]
Closing this issue since it was [answered](https://github.com/tensorflow/tensorflow/issues/25629) in TensorFlow repo. Thanks!
