### ISSUE TITLE
Support for mixed precision training

### ISSUE THREAD

**Issue by lminer** [keras-team/keras#12249]
It's great to see half-precision is now supported. Are there any plans to support mixed precision as detailed, for example, [here](https://forums.fast.ai/t/mixed-precision-training/20720)?

**Comment by gabrieldemarmiesse** [comment]
I'm pretty sure it's already supported. Documented, well, that's another issue. PR to update the docs with an example welcome.

**Comment by lminer** [comment]
Does that mean that if we set

```
K.set_floatx('float16')
K.set_epsilon(1e-4)
```

we're actually doing mixed precision training then?

**Comment by gabrieldemarmiesse** [comment]
There are a few gotchas to mixed precision training, so you would have to be aware of them if you don't want any NaNs but that's the idea, yes.

**Comment by lminer** [comment]
Ah. I'm getting NaN's right now. Would love to hear the gotchas!

**Comment by yourtheron** [comment]
May I have a link to the mixed precision training in Keras or something alike, if there is a one, please? I urgently need it! Many many thanks!!!
