### ISSUE TITLE
When early stop the training process, consider calling validation first。

### ISSUE THREAD

**Issue by tanglemontree** [keras-team/keras#12268]
### When early stop the training process, consider calling validation first。
The code in **training_generator.fit_generator** achieves earlystop by setting stop_training variable. But when callbacks set stop_training to true, they jump out of the loop directly without validation. When **callbacks.epoch_end (epoch, epoch_logs)** are called later, epoch_logs is empty, so that other callbacks cannot obtain validation result in on_epoch_end function, resulting in on_epoch_end function cannot be handled correctly, which is typical in ModelCheckpoint. This problem also exists in **training_arrays.fit_loop**.

**Comment by andrei-papou** [comment]
@tanglemontree would adding the line
```py
callbacks.on_epoch_end(epoch, epoch_logs)
```
[here](https://github.com/keras-team/keras/blob/a6c8042121371b5873773ca767f28cdf5689d5e4/keras/engine/training_generator.py#L253) before `break` statement fix the issue?
