### ISSUE TITLE
Cell equivalent of CuDNNGRU/CuDNNLSTM

### ISSUE THREAD

**Issue by MrinalJain17** [keras-team/keras#12264]
Hi.

I am using seq2seq models for time series forecasting. In my setup, the encoder and decoder can have multiple layers (GRU/LSTM), that is possible due to the respective cell class - `GRUCell` and `LSTMCell`. Internally, a list of such cells is created, which is passed to the `RNN` class.

Now, while running my model on GPU, there was no *significant* speed-up, and each epoch was taking ~80s (with 2-3 layers in both encoder and decoder).

So, I want to use the optimised CuDNNGRU (or LSTM), but I could not find a way to stack multiple such units. I have gone through a lot of tutorials/examples, but none could effectively explain the "correct" way to do this.

I believe that if there was a "cell-like" class for the CuDNN backed GRU and LSTM, it would be extremely convenient for stacking them.

Also, if this is something that is not possible, any help for achieving this efficiently and correctly (in accordance with the Keras conventions) would be much appreciated.

**Comment by MrinalJain17** [comment]
It's probably not that simple, but does making `num_layers` a parameter would help in achieving this?

https://github.com/keras-team/keras/blob/05d713504852b490afcf2607aea1ce923e93ecfe/keras/layers/cudnn_recurrent.py#L227-L231

**Comment by UdiBhaskar** [comment]
@MrinalJain17 any update on this? I am also trying to do the same.

**Comment by qinhuangdaoStation** [comment]
I have the same trouble
