### ISSUE TITLE
Gradient errors when training multi-branched models

### ISSUE THREAD

**Issue by m-dawoud** [keras-team/keras#12271]
I'm working on a model that handles different driving scenarios, which needs a common CNN at first then branches to different networks that shouldn't interfere, which means that I need to train the common part along with a branch simultaneously without affecting the weights of the other branches, I implemented it and I made sure that it worked well in a single branch architecture, but when adding the rest and defining a loss function for only one of them (mean absolute error); I get this error

ValueError: An operation has `None` for gradient. Please make sure that all of your ops have a gradient defined (i.e. are differentiable). Common ops without gradient: K.argmax, K.round, K.eval.

So what's the solution of such error or what could have caused it or how to avoid it?

**Comment by ziyigogogo** [comment]
One requirement for gradient compute is that your function should be continuous.
When you employ K.round. Your function is not continuous so that gradient cannot be computed.

**Comment by MTarekShaaban** [comment]
> The Error raised by keras is pretty straightforward.
> One requirement for gradient compute is that your function should be continuous.
> When you employ K.round. Your function is not continuous so that gradient cannot be computed.
> [a quick img for explain, sorry for my poor painting](https://github.com/ziyigogogo/ref_imgs/blob/master/round.png)
> The main idea is that you cannot compute the gradient when using K.round at point 0.5

The thing is I don't want to optimize these branches, I'm not using K.round, all three branches I want to optimize end with a one unit dense layer, but I want to optimze only one at a time without affecting the weights of the others, any idea how could it be implemented?

**Comment by pedro-r-marques** [comment]
Perhaps the following may help:
https://keras.io/getting-started/faq/#how-can-i-freeze-keras-layers
