### ISSUE TITLE
keras.application installed by pip binary file has no resnext?

### ISSUE THREAD

**Issue by MSC19950601** [keras-team/keras#12289]
The [keras.applications](https://github.com/keras-team/keras-applications) module has been splitted from the main Keras repository.

Please submit your issue using this [link](https://github.com/keras-team/keras-applications/issues/new).

Thank you!

**Comment by brandonschabell** [comment]
I believe that ResNeXt will be released with the next version of Keras. It's in master, but was not present when 2.2.4 was released.

**Comment by gabrieldemarmiesse** [comment]
@brandonschabell is right. Closing this issue as this will be solved in the next release.

**Comment by ggthecoder** [comment]
>>> print(keras.__version__)
2.2.4
>>> keras.applications.resnext.ResNeXt101()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'keras.applications' has no attribute 'resnext'
>>> 

When is the next release happening? Anyways to get to that earlier?

**Comment by dmvictor** [comment]
Hi @gabrieldemarmiesse. Will ResNet50V2 be released with the next version of Keras? Thank you!
