### ISSUE TITLE
ValueError: Cannot create group in read only mode

### ISSUE THREAD

**Issue by tonmoyborah** [keras-team/keras#12298]
Hi,
I could not find this issue already listed, but then I am not sure as there are so many of them. 
First I tried to add a few layers (Dense, conv, batchNorm, etc.) to a pretrained MobileNetV2, did `model.save` and then loaded it using `load_model`(with no custom_objects), it worked fine on test data. Say this is Model1
Then I loaded my Model1 using `load_model`(no custom objects again), added a few more layers as below. Note that I did create Model1 in a very similar fashion, only `base_model` was the MobileNetV2

    def post_tune_model(input_shape, n_out):
	    input_tensor = Input(shape=input_shape)
	    base_model = load_model('/path/to/model1')

	    for i in range(4):
		    base_model.layers.pop()

	    for layer in base_model.layers:
		    layer.trainable = True

	    x = base_model(input_tensor)  # bn
	    # print(base_model.summary())
	    x = Dense(2048, activation='relu')(x)  
	    x = BatchNormalization()(x)
	    x = Dropout(0.4)(x)
	    x = Dense(1024, activation='relu')(x)
	    x = BatchNormalization()(x) 
	    x = Dropout(0.4)(x)
	    output = Dense(n_out, activation='sigmoid')(x)
	    model = Model(input_tensor, output)

	    return model

Then I did `model.compile()`, `model.fit_generator()` and `model.save()` to train this model and save it. Now when I try to test it on test data using `load_model()` it returns this error
`ValueError: Cannot create group in read only mode.`

Traceback (most recent call last):
  File "path/to/Detection.py", line 154, in <module>
    classifier = load_model('/path/to/saved/model.h5')
  File "/home/X/.local/lib/python3.5/site-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/home/X/.local/lib/python3.5/site-packages/keras/engine/saving.py", line 221, in _deserialize_model
    model_config = f['model_config']
  File "/home/X/.local/lib/python3.5/site-packages/keras/utils/io_utils.py", line 302, in __getitem__
    raise ValueError('Cannot create group in read only mode.')
ValueError: Cannot create group in read only mode.

I found some old answer in SO saying to manually define the architecture, but I am not sure where and why if I used `model.save`. I am unable to understand why it was not an issue in Model1 but in the second model. Is there anything I am doing wrong or any workaround?
Any help is appreciated.

Please make sure that the boxes below are checked before you submit your issue.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps`

- [ ] Check that your version of TensorFlow is up-to-date. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by farizrahman4u** [comment]
Can you post on end to end script that reproduces the bug ?

**Comment by tonmoyborah** [comment]
I am not sure if this is a bug, maybe I am doing something very stupid.

My main function looks like below.  The create model is like I said earlier, a function exactly similar to `post_tune_model`. First I run main with `create_model`, then I load this saved model in `post_tune_model` and run `main` function with the `model=post_tune_model()` part. And now when try to call a `load_model` on this new model created, the error is shown. 

    def main():
	model_name = '14'  # TODO:change
	opt = Adam(lr=config.INIT_LR, decay=config.INIT_LR / config.EPOCHS)
	labels = []
	model = create_model(
		input_shape=(config.IMG_SIZE[0], config.IMG_SIZE[1], 3),
		n_out=1)
	# model = post_tune_model(
	# 	input_shape=(config.IMG_SIZE[0], config.IMG_SIZE[1], 3),
	# 	n_out=1)
	model.compile(optimizer=opt, loss='binary_crossentropy', metrics=['accuracy'])
	train_datagenerator = ImageDataGenerator(rescale=1./255, shear_range=0.2, zoom_range=0.4, horizontal_flip=True, brightness_range=[-0.5, 1.5], rotation_range=30)
	test_datagenerator = ImageDataGenerator(rescale=1./255)
	val_datagenerator = ImageDataGenerator(rescale=1./255)
	training_set = train_datagenerator.flow_from_directory(config.PERSON_FRAMES_DIRECTORY + '/train_combined', target_size=config.IMG_SIZE, batch_size=config.INIT_BS,
														   class_mode='binary')
	test_set = test_datagenerator.flow_from_directory(config.PERSON_FRAMES_DIRECTORY + '/test', target_size=config.IMG_SIZE, batch_size=config.INIT_BS,
													  class_mode='binary')
	val_set = val_datagenerator.flow_from_directory(config.PERSON_FRAMES_DIRECTORY + '/val', target_size=config.IMG_SIZE, batch_size=config.INIT_BS,
													class_mode='binary')
	checkpoint_path = config.CHECKPOINT_SAVE_PATH.format(name=model_name)
	if not os.path.exists('/'.join(checkpoint_path.split('/')[0:-1])):
		os.mkdir('/'.join(checkpoint_path.split('/')[0:-1]))
	callbacks = [TensorBoard(log_dir=config.LOG_DIR.format(model_name), batch_size=config.INIT_BS, write_grads=True, write_images=True,
							 update_freq='epoch')]   # ModelCheckpoint(checkpoint_path, monitor='val_loss', verbose=1, period=10),
	model.fit_generator(training_set, epochs=config.EPOCHS, validation_data=val_set, callbacks=callbacks)
	
	print("CNN Network Trained")
	model.save(config.CLASSIFY_MODEL_PATH.format(model_name))
	print("CNN Network Saved")

**Comment by bruce25796** [comment]
I got a similiar Error:
``
Traceback (most recent call last):
  File "c.py", line 186, in <module>
    model= load_model( MODEL_FILENAME )
  File "C:\Users\bruce\AppData\Local\conda\conda\envs\py35\lib\site-packages\keras\engine\saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "C:\Users\bruce\AppData\Local\conda\conda\envs\py35\lib\site-packages\keras\engine\saving.py", line 221, in _deserialize_model
    model_config = f['model_config']
  File "C:\Users\bruce\AppData\Local\conda\conda\envs\py35\lib\site-packages\keras\utils\io_utils.py", line 302, in __getitem__
    raise ValueError('Cannot create group in read only mode.')
ValueError: Cannot create group in read only mode.
``

**Comment by tonmoyborah** [comment]
Yea, I couldn't solve this, so what I did was write everything in one script and never used the `load_model`. This works but is very inconvenient.

**Comment by angyee** [comment]
> Yea, I couldn't solve this, so what I did was write everything in one script and never used the `load_model`. This works but is very inconvenient.

i am running

sudo python3 keras_to_tensorflow.py --input_model=/home/deepedge/mask_rcnn-master/mask_rcnn_damage_0010.h5 --output_model=/home/deepedge/mask_rcnn-master/dent.pb

and getting error

Using TensorFlow backend.
E0619 15:22:44.379571 140399717234496 keras_to_tensorflow.py:95] Input file specified only holds the weights, and not the model definition. Save the model using model.save(filename.h5) which will contain the network architecture as well as its weights. If the model is saved using the model.save_weights(filename) function, either input_model_json or input_model_yaml flags should be set to to import the network architecture prior to loading the weights.
Check the keras documentation for more details (https://keras.io/getting-started/faq/)
Traceback (most recent call last):
File "keras_to_tensorflow.py", line 182, in
app.run(main)
File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
_run_main(main, args)
File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
sys.exit(main(argv))
File "keras_to_tensorflow.py", line 128, in main
model = load_model(FLAGS.input_model, FLAGS.input_model_json, FLAGS.input_model_yaml)
File "keras_to_tensorflow.py", line 106, in load_model
raise wrong_file_err
File "keras_to_tensorflow.py", line 63, in load_model
model = keras.models.load_model(input_model_path)
File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 419, in load_model
model = _deserialize_model(f, custom_objects, compile)
File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 221, in _deserialize_model
model_config = f['model_config']
File "/usr/local/lib/python3.6/dist-packages/keras/utils/io_utils.py", line 302, in getitem
raise ValueError('Cannot create group in read only mode.')
ValueError: Cannot create group in read only mode.

**Comment by cpoptic** [comment]
The cause of this error is that, due to the way this was saved, the keras `.h5` file only contains the model weights but no model architecture. 

Theoretically, to save the ENTIRE model (not just the weights), you have to explicitly set `save_weights_only=False`

I say "theoretically" because evidently there's a bug where the model contains only the model weights (thus producing the aforementioned `ValueError: Cannot create group in read only mode` error.

I discovered this when trying to load a previously saved model in which I had explicitly set `save_weights_only=False` and it would not load due to there being no saved architecture included in the .h5 file:   https://github.com/matterport/Mask_RCNN/issues/1604

**Comment by hanieshojaee** [comment]
> The cause of this error is that, due to the way this was saved, the keras `.h5` file only contains the model weights but no model architecture.
> 
> Theoretically, to save the ENTIRE model (not just the weights), you have to explicitly set `save_weights_only=False`
> 
> I say "theoretically" because evidently there's a bug where the model contains only the model weights (thus producing the aforementioned `ValueError: Cannot create group in read only mode` error.
> 
> I discovered this when trying to load a previously saved model in which I had explicitly set `save_weights_only=False` and it would not load due to there being no saved architecture included in the .h5 file: [matterport/Mask_RCNN#1604](https://github.com/matterport/Mask_RCNN/issues/1604)

I have  explicitly set `save_weights_only=False` but again getting the same error: "ValueError: Cannot create group in read-only mode."

**Comment by 1337-Pete** [comment]
@hanieshojaee / anyone else who comes across this issue....

I too had set `save_weights_only = False` for my ModelCheckpoint callback and couldn't load in my model with `load_model(path)`. However, I defined the architecture of my model  and then loaded in my weights. Works like a charm.


```
optimizer = tf.keras.optimizers.Adam(learning_rate=1e-4, beta_1 = 0.9, beta_2 = 0.999, epsilon=1e-09, clipnorm=1.0) 
optimizer = tf.keras.optimizers.Adam(epsilon=1e-08, clipnorm=1.0) 
loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
metric = tf.keras.metrics.SparseCategoricalAccuracy('accuracy')
model = TFGPT2LMHeadModel.from_pretrained('distilgpt2')
model.compile(optimizer=optimizer, loss=[loss, None, None, None, None, None, None], metrics=[metric])
model.load_weights('C:/.../model-100.hdf5')
```

**Comment by hanieshojaee** [comment]
> @hanieshojaee / anyone else who comes across this issue....
> 
> I too had set `save_weights_only = False` for my ModelCheckpoint callback and couldn't load in my model with `load_model(path)`. However, I defined the architecture of my model and then loaded in my weights. Works like a charm.
> 
> ```
> optimizer = tf.keras.optimizers.Adam(learning_rate=1e-4, beta_1 = 0.9, beta_2 = 0.999, epsilon=1e-09, clipnorm=1.0) 
> loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
> metric = tf.keras.metrics.SparseCategoricalAccuracy('accuracy')
> model = TFGPT2LMHeadModel.from_pretrained('distilgpt2')
> model.compile(optimizer=optimizer, loss=[loss, None, None, None, None, None, None], metrics=[metric])
> model.load_weights('C:/.../model-100.hdf5')
> ```

Did you close "model_100.h5" after writing it?(When training finished and model saved)
I mean :
```
model_hf = h5py.File(r'C:\...\model__100.h5', 'w')
model_hf.close()
```
