### ISSUE TITLE
keras custom layer variable doesnt have ndim attribute

### ISSUE THREAD

**Issue by sandeeppandey456** [keras-team/keras#12310]
Please make sure that the boxes below are checked before you submit your issue.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps`

- [x] Check that your version of TensorFlow is up-to-date. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by sandeeppandey456** [comment]
I am trying to create a custom layer in keras which has two trainable variables. I am passing this two variables to another function inside which they need to get the ndims and shape of the variables. But it is showing error.  My custom layer code is-

`class MyLayer(Layer):

    def __init__(self, output_dim, **kwargs):
        self.output_dim = output_dim
        super(MyLayer, self).__init__(**kwargs)

    def build(self, input_shape):
        # Create a trainable weight variable for this layer.
        assert len(input_shape) >= 3
        input_dim = input_shape[1:]
        print(input_shape)


        self.kernel1 = self.add_weight(shape=(self.output_dim[0],input_dim[0]),
                                       name = 'kernel1',
                                      initializer='uniform',
                                      trainable=True)
        print(self.kernel1)
                                      
        self.kernel2 = self.add_weight(shape=(self.output_dim[1],input_dim[1]),
                                       name = 'kernel2',
                                      initializer='uniform',
                                      trainable=True)
        print(self.kernel2)
  
    
        super(MyLayer, self).build(input_shape)  # Be sure to call this at the end

    def call(self, x):
         print(x.shape)
         
         mat1 =np.array(self.kernel1)
#         mat1 =sess.run(mat1)
         print(K.shape(mat1))
         #print(mat1.ndim)
       
         mat2 =np.array(self.kernel2)
#         mat2 = sess.run(mat2)
         print(K.shape(mat2))
         #print(mat2.ndim)
      
         
        
         output1 = Myoperation(x,mat1,1)
         output = Myoperation(output1,mat2,2)

         return output
    

    def compute_output_shape(self, input_shape):
        return (input_shape[0], self.output_dim)`


inside the function Myoperation, it needs to calculate 
`m2=list(np.shape(M))[1]`
The error is -

> IndexError: list index out of range
if we use mat1.shape to check the shape, we get
> TypeError: Expected binary or unicode string, got <tf.Variable 'my_layer_6/kernel1:0' shape=(40, 61) dtype=float32_ref>

please help

**Comment by pedro-r-marques** [comment]
From the documentation:

---
```
keras.backend.shape(x)
```
Returns

A symbolic shape (which is itself a tensor).

---

```
keras.backend.int_shape(x)
```

Returns

A tuple of integers (or None entries).

---

I suspect that you are calling K.shape() when you want K.int_shape() which returns a tuple like np.shape().
