### ISSUE TITLE
ValueError: `sequences` must be a list of iterables. Found non-iterable:

### ISSUE THREAD

**Issue by ankur220693** [keras-team/keras#12315]
from keras.preprocessing.sequence import pad_sequences
 
train_sentences_X = pad_sequences(train_sentences_X, maxlen=MAX_LENGTH, padding='post')
test_sentences_X = pad_sequences(test_sentences_X, maxlen=MAX_LENGTH, padding='post')
train_tags_y = pad_sequences(train_tags_y, maxlen=MAX_LENGTH, padding='post')
test_tags_y = pad_sequences(test_tags_y, maxlen=MAX_LENGTH, padding='post')
 

**ERROR**

python3.6 nlp_lstm.py
18
Using TensorFlow backend.
Traceback (most recent call last):
  File "nlp_lstm.py", line 87, in <module>
    train_tags_y = pad_sequences(train_tags_y, maxlen=MAX_LENGTH, padding='post')
  File "/root/opt/lib/python3.6/site-packages/keras_preprocessing/sequence.py", line 60, in pad_sequences
    'Found non-iterable: ' + str(x))
ValueError: `sequences` must be a list of iterables. Found non-iterable: <generator object <genexpr> at 0x7f146f4ba780>

Thank you!

**Comment by pedro-r-marques** [comment]
It seems that train_tags_y is a generator object. Perhaps you meant to apply pad_sequences inside the generator.

**Comment by ankur220693** [comment]
Thanks,

**Comment by ankur220693** [comment]
Traceback (most recent call last):
  File "Train_POS.py", line 70, in <module>
    model.fit(epochs=25)
  File "/home/Ankur_JRF/Backup_Ubuntu/LSTM/bilstm_mai/neuralnets/BiLSTM.py", line 381, in fit
    self.buildModel()
  File "/home/Ankur_JRF/Backup_Ubuntu/LSTM/bilstm_mai/neuralnets/BiLSTM.py", line 105, in buildModel
    tokens = Embedding(input_dim=self.embeddings.shape[0], output_dim=self.embeddings.shape[1], weights=[self.embeddings], trainable=False, name='word_embeddings')(tokens_input)
IndexError: tuple index out of range

I am getting an issue.

**Comment by Gavin4th** [comment]
i got the same mistake, please help me solve it.
