### ISSUE TITLE
Keras transfer learning for image classification with pre-trained model failed

### ISSUE THREAD

**Issue by momo1986** [keras-team/keras#12311]
Please make sure that the boxes below are checked before you submit your issue.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.

Thank you!

- [ ] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps`

- [ ] Check that your version of TensorFlow is up-to-date. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).
I try to build a Keras-pre-traind MobileNet model, following the guide on the Keras blog at https://blog.keras.io/building-powerful-image-classification-models-using-very-little-data.html
It is the idea of transfer-learning:
Here is my code:

> preTrainedModel = MobileNetV2(weights = 'imagenet', include_top = False)
> preFeatures = preTrainedModel.output
> preFeatures = GlobalAveragePooling2D()(preFeatures)
> preFeatures = Dense(1024, activation = 'relu')(preFeatures)
> predictions = Dense(10, activation = 'softmax')(preFeatures)
> 
> #Extract features
> model = Model(input = preTrainedModel.input, output = predictions)
> #Layer freezing
> for layer in preTrainedModel.layers:
>     layer.trainable = False
> 
> if os.path.exists(top_layers_checkpoint_path):
>     model.load_weights(top_layers_checkpoint_path)
>     print ("Checkpoint '" + top_layers_checkpoint_path + "' loaded.")
> 
> #Rmsprop optimizer
> model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'], )
> 
> #Save the model after every epoch
> mc_top = ModelCheckpoint(top_layers_checkpoint_path, monitor='val_acc', verbose=0, save_best_only=True, save_weights_only=False, mode='auto', period=1)
> 
> #Save the TensorBoard logs.
> tb = TensorBoard(log_dir='./logs', histogram_freq=1, write_graph=True, write_images=True)
> 
> model.fit_generator(datGen, samples_per_epoch = batchPerEpoch, nb_epoch = epochPerPass, validation_data = validateDataFlow, nb_val_samples = batchPerEpoch, callbacks = [mc_top, tb], use_multiprocessing=False)
> 
> for i, layer in enumerate(preTrainedModel.layers):
>    print(i, layer.name)
> #Save the model after every epoch.
> mc_fit = ModelCheckpoint(fine_tuned_checkpoint_path, monitor='val_acc', verbose=0, save_best_only=True, save_weights_only=False, mode='auto', period=1)
> 
> 
> if os.path.exists(fine_tuned_checkpoint_path):
>         model.load_weights(fine_tuned_checkpoint_path)
>         print ("Checkpoint '" + fine_tuned_checkpoint_path + "' loaded.")
> 
> # we chose to train the top 2 inception blocks, i.e. we will freeze
> # the first 172 layers and unfreeze the rest:
> for layer in model.layers[:50]:
>    layer.trainable = False
> for layer in model.layers[50:]:
>    layer.trainable = True
> 
> model.fit_generator(datGen, samples_per_epoch = batchPerEpoch, nb_epoch = epochPerPass, validation_data = validateDataFlow, nb_val_samples = batchPerEpoch, callbacks = [mc_top, tb], use_multiprocessing=False)
> 

It reports the error:
**tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[1373,32,112,112] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [[{{node Conv1/convolution}} = Conv2D[T=DT_FLOAT, _class=["loc:@bn_Conv1/cond/FusedBatchNorm/Switch"], data_format="NCHW", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 2, 2], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Conv1/convolution-0-TransposeNHWCToNCHW-LayoutOptimizer, Conv1/kernel/read)]]**

Does this mean the GPU resources are exhausted? How can I resolve the issue?

**Comment by ale152** [comment]
Yes, it's usually because your GPU memory is not large enough. You can try with a smaller batch size
