### ISSUE TITLE
fit_generator with multiple inputs crashes when batch > 1

### ISSUE THREAD

**Issue by Soulthym** [keras-team/keras#12326]
I am experimenting with a very simple word2vec-like model, with data that doesn't in RAM, so I am using fit_generator. I haven't had any problem with it while using a single input, however while using multiple inputs (namely 2), and a batch_size > 1, I get the following Traceback: 
```
Traceback (most recent call last):
  File "tf-clustering.py", line 74, in <module>
    steps_per_epoch=nb_steps)
  File "/usr/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 2177, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_generator.py", line 176, in fit_generator
    x, y, sample_weight=sample_weight, class_weight=class_weight)
  File "/usr/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1940, in train_on_batch
    outputs = self.train_function(ins)
  File "/usr/lib/python3.7/site-packages/tensorflow/python/keras/backend.py", line 2986, in __call__
    run_metadata=self.run_metadata)
  File "/usr/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/usr/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [10,3] vs. [5,3]
         [[{{node loss/concatenate_loss/sub}} = Sub[T=DT_FLOAT, _class=["loc:@training/RMSprop/gradients/loss/concatenate_loss/sub_grad/Reshape"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](concatenate/concat, _arg_concatenate_target_0_2)]]
```
The code is pretty simple and I don't think I've used the keras API wrongly, here is my code:
```
import json
import tensorflow as tf
import numpy as np
from pprint import pprint
from tensorflow.keras.layers import Input, Dense, Concatenate
from tensorflow.keras.models import Model
import tensorflow.keras.backend as K
BATCH_SIZE = 5
OUTPUT_SIZE = 3

def euclidean_distance_loss(y_true, y_pred):
    return K.sqrt(K.sum(K.square(y_pred[0] - y_pred[1]), axis=-1))
    
print(">>> Loading Data")
with open('data/dataset.json', 'r') as jf:
     dataset = json.load(jf)
     
vocab=dataset["vocab"]
inv_vocab = {v: k for k, v in vocab.items()}
vocab_size=len(vocab) 
data=dataset["dataset"]
print(">>> Estimating the amount of steps in Training")
nb_steps=0
for d in data:
    for s in d["d_data"]:
        nb_steps+= len(s)
print("nb_steps: ",nb_steps)
def iterdata():
    while True:
        for d in data:
            for s in d["d_data"]:
                for w in s:
                    val1=tf.keras.utils.to_categorical(d["d_id"], num_classes=vocab_size)
                    val2=tf.keras.utils.to_categorical(w, num_classes=vocab_size)
                    yield [val1, val2], np.zeros(OUTPUT_SIZE)
    
def generate_batch():
    batch_val1 = np.zeros((BATCH_SIZE, vocab_size))
    batch_val2 = np.zeros((BATCH_SIZE, vocab_size))
    batch_out = np.zeros((BATCH_SIZE, OUTPUT_SIZE))
    while True: 
        for ([v1, v2], o), batch in [(val, batch) for batch, val in zip(range(BATCH_SIZE),iterdata())]:
            batch_val1[batch]=v1 
            batch_val2[batch]=v2 
            batch_out[batch]=o
        print(batch_val1.shape)
        yield [batch_val1, batch_val2], batch_out
    
word_a = Input(shape=(vocab_size,))
word_b = Input(shape=(vocab_size,))

shared_encode = Dense(OUTPUT_SIZE, activation=None)

encoded_a = shared_encode(word_a)
encoded_b = shared_encode(word_b)

merged = Concatenate(axis=0)([encoded_a,encoded_b])

model = Model(inputs=[word_a,word_b], outputs=merged)
model.compile(
        loss=euclidean_distance_loss,
        optimizer='rmsprop',
        metrics=['accuracy'])
model.fit_generator(generate_batch(),
        epochs=10,
        steps_per_epoch=nb_steps)
```

**Comment by pedro-r-marques** [comment]
The operation Concatenate(axis=0) will concatenate the tensors along the X-axis. i.e. given 2 inputs with shape (5, 3) it will result in a shape of (10, 3).

It seems to me that there are several issues with your model:
1 - I would expect the loss function to compare y_true and y_pred; if y_true is not used by the loss function then batch_out in generate_batch is unused;
2 - y_pred in the loss function will have a shape of (2xBATCH_SIZE, OUTPUT). y_true has a shape of (BATCH_SIZE, OUTPUT). The error that you show would be compatible with a subtraction operation on y_true and y_pred;
3 - y_pred[0] and y_pred[1] would be vectors of shape (OUTPUT,); but then this would ignore the rest of the batch elements.

It seems to me that when you have multiple inputs you want to apply an operations to them that is not to concatenate and create a larger batch. e.g. it is likely that you want to concatenate on axis=1 and then apply another Dense() operation that takes (batch_size, 2 x OUTPUT) shape as input and generates a (batch_size, OUTPUT).

When debugging I would strongly suggest using model.summary() after compile.

**Comment by Soulthym** [comment]
Thanks for the reply,
1) it might seem weird but I'm experimenting with custom metrics that optimize the model without labels, namely optimizing the underlying structure itself.
2) I didn't know that not think about it, thanks for pointing it out.
3) I see where the mistake can be, I'll try to figure it out.

I didn't know about model.summary, I will use that from now on.

In a way, I am making a model that would use shared weights between 2 inputs and train by reducing the distance between the 2 evaluated vectors.

How should I define a loss function that uses 2 infered vectors, ignores the label (not needed for that specific case) and generalises well on batches?

**Comment by pedro-r-marques** [comment]
Apologies in advance if the discussion is inappropriate for the project GitHub issues (I believe this issue can be closed) vs other support fora.

The simplest way to define an unsupervised model between a pair of entities is to use a co-occurrence matrix. This is the approach used by word2vec.

For instance, you can express a matrix of co-occurences between words (the original word2vec idea) by considering a square matrix where the row and column indexes are token ids; and the matrix value is the number of times the word co-occurs in context.

You can model this in Keras as:
```
row = Input(shape=(1,))
col = Input(shape=(1,))
row_embedding = Embedding(n_rows, embedding_size, name='row_embedding', input_length=1)(row)
col_embedding = Embedding(n_cols, embedding_size, name='col_embedding', input_length=1)(col)
row_embedding = Flatten()(row_embedding)
col_embedding = Flatten()(col_embedding)
y = Dot(1)([row_embedding, col_embedding])
model = Model(inputs=[row, col], outputs=y)
```
Given a matrix row and column coordinates as input and the values as output you can fit a model.
The matrix can be dense or sparse.
```
matrix = scipy.sparse.coo_matrix(...)
model.fit([matrix.row, matrix.col], matrix.data)
```
This same concept can be expanded to predict a tensor rather than a single float value; in case the association between the row and col entities is expressible by a multi-dimensional value rather than just a measure such as number of words in context.

Given a dataset with a consistent signal and enough training iterations this creates a set of embeddings such that cosine similarity (and/or Euclidean distance) capture concepts that are latent in the data (example: word2vec analogies).

**Comment by Soulthym** [comment]
I wish I could do that, it was the original plan, but the matrix would never fit into memory because the vocabulary is so wide (it can go up to 2 million tokens), I'll try to find another solution than merging the outputs to have split inputs.
Thanks for your help! I'll close the issue

**Comment by Soulthym** [comment]
Just one last question before I close it, is there a way to split an array in 2 such  that it would work in the loss function? 
Say I have a vector [0,1,2,3], splitting it would result in [0,1] and [2,3]

**Comment by pedro-r-marques** [comment]
The example model above can be used with a sparse matrix that doesn't fit in memory. In fact that is the main use case. You can use the fit_generator method that reads the data as long as you can return a pair of token indices and a 'value' that describes the association between then.

Answering your question: Keras.backend defines a 'slice' operation that can be used to obtain a slice over a tensor.

If you do go down the path of defining your own cost function, I would encourage you to consider whether the optimizer can minimize the cost of the loss function just by predicting the same value for all the inputs. i.e. if your cost function is going to be the euclidian distance between input1 and input2 then the cost can be optimized to 0 if all weights of 'shared_encode' are the same.

**Comment by Soulthym** [comment]
Didn't think about that one, thank you very much for your help! 
The issue can be closed now :)
