### ISSUE TITLE
[Docs] depth_multiplier listed as argument to keras.applications.MobileNetV2

### ISSUE THREAD

**Issue by JTunis** [keras-team/keras#12327]
In the docs (https://keras.io/applications/#mobilenetv2), `depth_multiplier` is listed and used as an argument to `keras.applications.MobileNetV2`, even though it is not implemented in https://github.com/keras-team/keras-applications/blob/master/keras_applications/mobilenet_v2.py:
```python
def MobileNetV2(input_shape=None,
                alpha=1.0,
                include_top=True,
                weights='imagenet',
                input_tensor=None,
                pooling=None,
                classes=1000,
                **kwargs):

**Comment by gabrieldemarmiesse** [comment]
Closing as the PR was merged.
