### ISSUE TITLE
NameError in 'Guide to the Functional API' docs

### ISSUE THREAD

**Issue by pynchmeister** [keras-team/keras#12331]
Going through the documentation on keras.io, I have encountered a bug under the Guide to the Functional API/First example: a densely-connected network section.

Here is the error output: 

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-8-a814b5a756e2> in <module>()
     16               loss='categorical_crossentropy',
     17               metrics=['accuracy'])
---> 18 model.fit(data, labels)  # starts training

NameError: name 'data' is not defined
```

And a link to a Gist: https://gist.github.com/pynchmeister/0ca43aa9df871e8068170e14c53bb90b

**Comment by abhaikollara** [comment]
I'm not sure, but I think the example assumes that `data` and `labels` are prepared elsewhere to concentrate on the functional API.

A copy-pasteable example would look like this

```python
from keras.layers import Input, Dense
from keras.models import Model
from keras.datasets import mnist
from keras.utils import to_categorical

# The missing data loading part
(train_data, train_labels), (test_data, test_labels) = mnist.load_data()
train_data = train_data.reshape(-1, 784) # Reshape (60000, 28, 28) -> (60000, 784)
train_labels = to_categorical(train_labels)


# This returns a tensor
inputs = Input(shape=(784,))

# a layer instance is callable on a tensor, and returns a tensor
x = Dense(64, activation='relu')(inputs)
x = Dense(64, activation='relu')(x)
predictions = Dense(10, activation='softmax')(x)

# This creates a model that includes
# the Input layer and three Dense layers
model = Model(inputs=inputs, outputs=predictions)
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
```

**Comment by pynchmeister** [comment]
Thanks for the reply, your copypasta elucidated the issue. 

Despite this, I think the documentation should be switched to the code snippet you provided, so it is operational when readers try and experiment with the code in the documentation.

https://keras.io/getting-started/functional-api-guide/ 

Right under First example: a densely-connected network, like I said.
