### ISSUE TITLE
Save MaskRCNN full keras model

### ISSUE THREAD

**Issue by oriolorra** [keras-team/keras#12330]
Hi everyone!

I am trying to save the full model (not only the weight). 
I use the command:
     >> _model.keras_model.save(path_file)_
And it does not give any error.

But, when I try to load the full model shows an error, i am using these comands:
    >> _from keras.models import load_model_
    >> _model_test = load_model(path_file)_

And it shows this error:

_~\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\models.py in load_model(filepath, custom_objects, compile)
    268             raise ValueError('No model found in config file.')
    269         model_config = json.loads(model_config.decode('utf-8'))
--> 270         model = model_from_config(model_config, custom_objects=custom_objects)
    271 
    272         # set weights

~\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\models.py in model_from_config(config, custom_objects)
    345                         'Maybe you meant to use '
    346                         '`Sequential.from_config(config)`?')
--> 347     return layer_module.deserialize(config, custom_objects=custom_objects)
    348 
    349 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\layers\__init__.py in deserialize(config, custom_objects)
     53                                     module_objects=globs,
     54                                     custom_objects=custom_objects,
---> 55                                     printable_module_name='layer')

~\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\utils\generic_utils.py in deserialize_keras_object(identifier, module_objects, custom_objects, printable_module_name)
    142                 return cls.from_config(config['config'],
    143                                        custom_objects=dict(list(_GLOBAL_CUSTOM_OBJECTS.items()) +
--> 144                                                            list(custom_objects.items())))
    145             with CustomObjectScope(custom_objects):
    146                 return cls.from_config(config['config'])

~\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\engine\topology.py in from_config(cls, config, custom_objects)
   2523         # First, we create all layers and enqueue nodes to be processed
   2524         for layer_data in config['layers']:
-> 2525             process_layer(layer_data)
   2526         # Then we process nodes in order of layer depth.
   2527         # Nodes that cannot yet be processed (if the inbound node

~\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\engine\topology.py in process_layer(layer_data)
   2509 
   2510             layer = deserialize_layer(layer_data,
-> 2511                                       custom_objects=custom_objects)
   2512             created_layers[layer_name] = layer
   2513 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\layers\__init__.py in deserialize(config, custom_objects)
     53                                     module_objects=globs,
     54                                     custom_objects=custom_objects,
---> 55                                     printable_module_name='layer')

~\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\utils\generic_utils.py in deserialize_keras_object(identifier, module_objects, custom_objects, printable_module_name)
    136             if cls is None:
    137                 raise ValueError('Unknown ' + printable_module_name +
--> 138                                  ': ' + class_name)
    139         if hasattr(cls, 'from_config'):
    140             custom_objects = custom_objects or {}

ValueError: Unknown layer: BatchNorm_

Has anyone tried to save a full model? Is it possible? has anyone a solution?
url: [https://github.com/matterport/Mask_RCNN](url)

Thanks,

**Comment by hgaiser** [comment]
Their Mask_RCNN uses a custom `BatchNorm_` layer, which Keras won't know how to find by default. Look into the `custom_objects` argument for `load_model`, that should fix the issue you're having.

**Comment by oriolorra** [comment]
Okay, thanks. 

I will try to investigate more about it.
