### ISSUE TITLE
Batch_size issue when using model.fit on keras custom layers

### ISSUE THREAD

**Issue by sandeeppandey456** [keras-team/keras#12338]
I have a custom layer which reshapes the input tensor(batch+2D), perform some dot products with kernels and returns back a tensor with the same number of dimensions(batch+2D) . The input to my network is images, say of size 61x80. When the number of train images is a multiple of batch_size , model.fit works fine. eg total train images= 2700, batch_size=10. But when the total train images =2701, batch_size() it doesnt work, throwing an error something like this-

> Epoch 1/5 2520/2701 [==========================>...] - ETA: 0s - loss: 2.7465 - acc: 0.2516Traceback (most recent call last):
> 
> File "", line 5, in history = model.fit(x_train, y_train,batch_size=10, epochs=5)
> 
> File "/home/eee/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1039, in fit validation_steps=validation_steps)
> 
> File "/home/eee/anaconda3/lib/python3.6/site-packages/keras/engine/training_arrays.py", line 199, in fit_loop outs = f(ins_batch)
> 
> File "/home/eee/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2715, in call return self._call(inputs)
> 
> File "/home/eee/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call fetched = self._callable_fn(*array_vals)
> 
> File "/home/eee/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1439, in call run_metadata_ptr)
> 
> File "/home/eee/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in exit c_api.TF_GetCode(self.status.status))
> 
> InvalidArgumentError: Input to reshape is a tensor with 4880 values, but the requested shape has 48800 [[{{node my_layer_3/Reshape}} = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_input_2_0_0, my_layer_3/stack)]]

please help

**Comment by JARIS101** [comment]
Can You please share your code?
