### ISSUE TITLE
UpSampling2D throwing error with keyword 'interpolation'

### ISSUE THREAD

**Issue by FCOS** [keras-team/keras#12354]
I'm getting a weird error when I try to create a network using an upsampling layer, when I manually set the interpolate keyword to bilinear. If I leave it out, and go with the default of 'nearest neighbour; it works fine. Does anyone know what's up?

TF = 1.12.0
Keras = 2.2.2
OS = Ubuntu 18.04

Code for model. Error is thrown at layer 'up1'

    chnl4_input = Input(shape=(368, 256, 4))
    chnl3_input = Input(shape=(736, 512, 3))

    conv1 = Conv2D(26, self.kernel_size, activation='relu', padding='same')(chnl4_input)
    conv2 = Conv2D(26, self.kernel_size, strides=(2, 2), activation='relu', padding='same')(conv1)

    conv5 = Conv2D(64, self.kernel_size, activation='relu', padding='same')(conv2)
    conv6 = Conv2D(64, self.kernel_size, activation='relu', padding='same')(conv5)

    up1 = concatenate([UpSampling2D(size=(2, 2), interpolation='bilinear')(conv6), conv1], axis=-1)
    conv7 = Conv2D(64, self.kernel_size, activation='relu', padding='same')(up1)

    conv8 = Conv2D(64, self.kernel_size, activation='relu', padding='same')(conv7)
    conv9 = Conv2D(64, self.kernel_size, activation='relu', padding='same')(conv8)

    conv11 = Conv2D(64, self.kernel_size, activation='relu', padding='same')(conv9)
    conv12 = Conv2D(64, self.kernel_size, activation='relu', padding='same')(conv11)

    up3 = concatenate([UpSampling2D(size=(2, 2), interpolation='bilinear')(conv12), chnl3_input], axis=-1)
    conv13 = Conv2D(67, self.kernel_size, activation='relu', padding='same')(up3)

    conv14 = Conv2D(67, self.kernel_size, activation='relu', padding='same')(conv13)
    conv15 = Conv2D(32, self.kernel_size, activation='relu', padding='same')(conv14)
    conv16 = Conv2D(3, self.kernel_size, activation='relu', padding='same')(conv15)

    out = conv16

    self.model = Model(inputs=[chnl4_input, chnl3_input], outputs=[out])

    self.model.compile(optimizer=self.optimizer_func, loss=self.loss_func)
    self.model.name = 'UNET'

    return self.modele here`

Errror = TypeError: ('Keyword argument not understood:', 'interpolation')

**Comment by gabrieldemarmiesse** [comment]
I think this is because you don't have the latest version of keras. Can you check it?

**Comment by miasanisie** [comment]
Are there any news on this? I am facing the same issue as @FCOS  in my virtual environment with (currently) newest versions of Tensorflow and Keras installed:

TF = 1.13.1
Keras = 2.2.4
Python = 3.6.7
OS = Ubuntu 18.04


Great thanks for any kind of update with this respect in advance, guys!

**Comment by FCOS** [comment]
I had a root around the keras code, and it seems to be that 'interpolation' is simply left out of the valid arguments list for the upSampling2D function. You can modify it yourself if you're bothered, but you can bypass the problem altogether by just leaving out the interpolation argument. That way it will default to nearest neighbour interpolation. The performance difference is negligible between the two.

**Comment by miasanisie** [comment]
Alright, I see.. too bad. The bilinear case works better for my purposes, so I will try to figure an alternative out - thanks a lot, @FCOS ! (:

**Comment by he44** [comment]
I had the same issue with Keras 2.2.2 but it seemed to be working in 2.2.4
![image](https://user-images.githubusercontent.com/15525366/61409355-af908680-a8a7-11e9-9734-fecc1de227a5.png)

**Comment by gabrieldemarmiesse** [comment]
Closing this issue since it works on the master branch.

**Comment by Wanli-Jiang** [comment]
It works well with "cuda=9.0, tensorflow=1.11.0, keras=2.2.5"
