### ISSUE TITLE
multi_gpu_model fails at error l.173

### ISSUE THREAD

**Issue by ad12** [keras-team/keras#12360]
Please make sure that the boxes below are checked before you submit your issue.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps`

- [x] Check that your version of TensorFlow is up-to-date. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).
`new_model = multi_gpu_model(model, gpus)`

#### Error
```
  File "/home/anaconda3/envs/tf_36/lib/python3.6/site-packages/keras/utils/multi_gpu_utils.py", line 179, in multi_gpu_model
    available_devices))
TypeError: %d format: a number is required, not list
```

#### Error Source
At *keras/utils/multi_gpu_utils.py*:l173

```
raise ValueError(
                'To call `multi_gpu_model` with `gpus=%d`, '
                'we expect the following devices to be available: %s. '
                'However this machine only has: %s. '
                'Try reducing `gpus`.' % (gpus,
                                          target_devices,
                                          available_devices))
```

Variable `gpus` is not necessarily an integer, so `%d` formatting shouldn't be used

#### Suspected solution
```
raise ValueError(
                'To call `multi_gpu_model` with `gpus=%s`, '
                'we expect the following devices to be available: %s. '
                'However this machine only has: %s. '
                'Try reducing `gpus`.' % (gpus,
                                          target_devices,
                                          available_devices))
```

**Comment by ymodak** [comment]
I think ```%d``` formatting is correct and works well in cases for multi gpu placement. What gpu device assignment you observe where this can fail?
