### ISSUE TITLE
How to convert this code to new version of Keras code?

### ISSUE THREAD

**Issue by bestazad** [keras-team/keras#12375]
I saw this code in a question, but seems `input_dim` and `output_dim` arguments are no longer used with new version of Keras and they are replaced with `input_shape()` function. So may someone edits this part of previous version to compatible with new Keras version?
```

model = Sequential()  
model.add(LSTM(input_dim=1, output_dim=hidden_neurons, return_sequences=False))  
model.add(RepeatVector(10))
model.add(LSTM(output_dim=hidden_neurons, return_sequences=True))  
model.add(TimeDistributed(Dense(1)))
model.add(Activation('linear'))   
model.compile(loss='mean_squared_error', optimizer='rmsprop', metrics=['accuracy'])
```

I also like to know what is the meaning of adding this line `model.add(Activation('linear'))   ` ? Is it necessary for all many-to-many LSTMs or not?

**Comment by ferrjef** [comment]
Try use `units` instead of `output_dim` on the LSTM parameters

See also: [https://keras.io/getting-started/sequential-model-guide/#sequence-classification-with-lstm](https://keras.io/getting-started/sequential-model-guide/#sequence-classification-with-lstm)

**Comment by bestazad** [comment]
> Hi, @bestazad
> 
> Try to use `units` instead of `output_dim` in the LSTM parameters. For your last question, basically an activation is a hyper-parameter that you define that uses an output layer and applies some function to it. In this case it's a `'linear'` (i.e. identity) activation function.
> 
> See also:
> [Usage of Activations](https://keras.io/activations/)
> https://keras.io/getting-started/sequential-model-guide/#sequence-classification-with-lstm

Is this edition true:

model = Sequential()  
model.add(LSTM(units , input_shape(time_steps, 1) , return_sequences=False))  
model.add(RepeatVector(10))
model.add(LSTM(units , return_sequences=True))  
model.add(TimeDistributed(Dense(1)))
model.add(Activation('linear'))   
model.compile(loss='mean_squared_error', optimizer='rmsprop', metrics=['accuracy'])

I also like to know if I remove this line `model.add(Activation('linear'))   ` model won't use any activations or there is a default activation that will be used for all layers?

**Comment by ferrjef** [comment]
Hey, @bestazad 

I suppose you want this:

```
model = Sequential()  
model.add(LSTM(units = hidden_neurons, input_dim = time_steps))  
model.add(RepeatVector(10))
model.add(LSTM(units = hidden_neurons, return_sequences = True))  
model.add(TimeDistributed(Dense(units = 1)))
model.add(Activation('linear'))   
model.compile(loss = 'mean_squared_error', optimizer = 'rmsprop', metrics = ['accuracy'])
```
In Keras 2.x all default activations are linear, so if your version of Keras is earlier, the default activation may be different.

**Comment by bestazad** [comment]
> Hey, @bestazad
> 
> I suppose you want this:
> 
> ```
> model = Sequential()  
> model.add(LSTM(units = hidden_neurons, input_dim = time_steps))  
> model.add(RepeatVector(10))
> model.add(LSTM(units = hidden_neurons, return_sequences = True))  
> model.add(TimeDistributed(Dense(units = 1)))
> model.add(Activation('linear'))   
> model.compile(loss = 'mean_squared_error', optimizer = 'rmsprop', metrics = ['accuracy'])
> ```
> In Keras 2.x all default activations are linear, so if your version of Keras is earlier, the default activation may be different.

Thank you very much @ferrjef 
But seems using `input_dim` doesn't work if we have more than 1 dimensional vectors for inputs. For example my inputs look like: `training_set = (1800,75,2)`  and get this error with your suggested code:

`ValueError: Error when checking input: expected lstm_123_input to have shape (None, 75) but got array with shape (75, 2)`

**Comment by aezco** [comment]
> > Hey, @bestazad
> > I suppose you want this:
> > ```
> > model = Sequential()  
> > model.add(LSTM(units = hidden_neurons, input_dim = time_steps))  
> > model.add(RepeatVector(10))
> > model.add(LSTM(units = hidden_neurons, return_sequences = True))  
> > model.add(TimeDistributed(Dense(units = 1)))
> > model.add(Activation('linear'))   
> > model.compile(loss = 'mean_squared_error', optimizer = 'rmsprop', metrics = ['accuracy'])
> > ```
> > 
> > 
> > In Keras 2.x all default activations are linear, so if your version of Keras is earlier, the default activation may be different.
> 
> Thank you very much @ferrjef
> But seems using `input_dim` doesn't work if we have more than 1 dimensional vectors for inputs. For example my inputs look like: `training_set = (1800,75,2)` and get this error with your suggested code:
> 
> `ValueError: Error when checking input: expected lstm_123_input to have shape (None, 75) but got array with shape (75, 2)`

I am getting a similar error with the shape. Did You solve it?

`Error when checking input: expected input_10 to have 5 dimensions, but got array with shape (64, 224, 224, 3)`
