### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'get_default_graph

### ISSUE THREAD

**Issue by Sawatdatta** [keras-team/keras#12379]
I am using TensorFlow 2.0 preview, also keras is using  newly installed preview version as a backend

TensorFlow-gpu-2.0-preview
Keras :2.2.4
OS:Windows 10
python:3.6
CUDA:10

currently it is throwing following error:

File "C:\Users\SUS\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\backend\tensorflow_backend.py", line 74, in get_uid
    graph = tf.get_default_graph()
AttributeError: module 'tensorflow' has no attribute 'get_default_graph'

Is there any way to force Keras to use tf.compat.V1 as a backend?

**Comment by MrZhengXin** [comment]
I can't agree more.
Have to add it manually...

**Comment by Sawatdatta** [comment]
@MrZhengXin How?

**Comment by MrZhengXin** [comment]
> @MrZhengXin How?

Oh, sorry. I mean change the code manually like tf.compat.v1.get_default_graph

**Comment by Sawatdatta** [comment]
Even sub modules/packages need to update the calls, Manually changing the code in sub modules/packages will break the system. I am thinking to rewrite entire project code as per tf 2.0 's documentation.

**Comment by Sagarsharma4244** [comment]
I'm having the same issue.

**Comment by aakashganga** [comment]
Same issue here with Tensorflow 2.0

**Comment by russellfei** [comment]
For me, I just use `from tensorflow.python.keras.xx` to make it work after diving into `site-packages/tensorflow` src folder, hope keras team catching up with tensorflow.
Mark here, thx @aakashganga for your hints. 
Further reading [this guide](https://www.tensorflow.org/guide/keras)

**Comment by emikulic** [comment]
In my case, replacing
`from keras import backend`
with:
`from tensorflow.keras import backend`
in my script, fixed this problem.

**Comment by Sawatdatta** [comment]
Than you friends @aakashganga @russellfei @emikulic  for your information.

**Comment by Ademord** [comment]
@emikulic  that only escalates and gives me error "tensorflow has no attribute 'log'", when doing tf.log.
How does one fix this versioning problem??

**Comment by emikulic** [comment]
I think my problem was I had both tf2.0.0 and keras installed. Maybe you're less likely to run into versioning problems if you don't install keras, that way you'll only use the one that ships with tf.

**Comment by Ademord** [comment]
Another option: I ended up downgrading to not run into these silly alpha problems.

**Comment by navyup** [comment]
just re-install to deal with it

**Comment by ccgccc** [comment]
@navyup, Is your tensorflow version still 2.0.0 after re-install?

**Comment by navyup** [comment]
after re-install，it‘s OK

发自我的 iPhone

**Comment by wangyexiang** [comment]
@Sawatdatta，how to solve your problem？thx.

**Comment by wangyexiang** [comment]
@Sawatdatta，how did you solve your problem? thx.

**Comment by Sawatdatta** [comment]
Use keras bundled within Tensorflow as suggested by @emikulic  solves the problem 
 Replace
`from keras import backend`
with:
`from tensorflow.keras import backend`

**Comment by EthanJYK** [comment]
@Sawatdatta Thank you. I solved my problems with 'from tensorflow.python.keras import backend'

**Comment by zyjcs** [comment]
![image](https://user-images.githubusercontent.com/18757695/57181276-37c7d800-6ec4-11e9-8b8d-c7fd365664c8.png)
![image](https://user-images.githubusercontent.com/18757695/57181293-575f0080-6ec4-11e9-92eb-63a688a9ecb7.png)

**Comment by emikulic** [comment]
@zyjcs I'm worried about the `from keras` lines. Basically my problem is I was mixing Tensorflow 2.0 with keras. IMO you don't want both installed in the same virtualenv.

**Comment by Sawatdatta** [comment]
@zyjcs  you need to use 

`from tensorflow.python.keras import backend`

**Comment by SumanthMeenan** [comment]
@zyjcs Use the below line, it might solve your issue
from tensorflow.keras import backend as K

**Comment by SumanthMeenan** [comment]
@Sawatdatta I think you need to call 
'from tensorflow.keras' instead of 'from keras'
To avoid this 'AttributeError: module 'tensorflow' has no attribute 'get_default_graph' error

**Comment by chaslie** [comment]
tried all the above, an I still get the error:
AttributeError: module 'tensorflow' has no attribute 'get_default_graph'

any ideas what is causing this?

**Comment by zrajabi** [comment]
@chaslie I had the same issue for Tensorflow 2 beta from Embedding module and tried following which finally worked: 
tensorflow import keras
from tensorflow.keras import layers 
--> then call layers.Embedding()

**Comment by 0x01h** [comment]
Downloading binary version of TensorFlow solved my problem.

```sh
$ pip install --ignore-installed --upgrade "<URL>"
```

**Select right binary URL according to your system from below.**
https://github.com/lakshayg/tensorflow-build

**Comment by nilaykd** [comment]
> Another option: I ended up downgrading my tensorflow to 1.13.1 to not run into these silly alpha problems.

Honestly, the latest version is tensorflow-2.0.0b1 which is in Beta, it is much easier to create a separate environment for your specific project and downgrade it.

**Comment by bjm88620** [comment]
> For me, I just use `from tensorflow.python.keras.xx` to make it work after diving into `site-packages/tensorflow` src folder, hope keras team catching up with tensorflow.
> Mark here, thx @aakashganga for your hints.
> Further reading [this guide](https://www.tensorflow.org/guide/keras)

This actually works fine. Thanks for sharing.

**Comment by ishwor2048** [comment]
> @Sawatdatta I think you need to call
> 'from tensorflow.keras' instead of 'from keras'
> To avoid this 'AttributeError: module 'tensorflow' has no attribute 'get_default_graph' error

This is really helpful, Thanks Sawatdatta

**Comment by gleissonbispo** [comment]
> @Sawatdatta I think you need to call
> 'from tensorflow.keras' instead of 'from keras'
> To avoid this 'AttributeError: module 'tensorflow' has no attribute 'get_default_graph' error

Thank you very much!! It worked to me!

**Comment by ulfasihman** [comment]
> In my case, replacing
> `from keras import backend`
> with:
> `from tensorflow.keras import backend`
> in my script, fixed this problem.

thank you so muchh ive been looking for this problem for a day , and you solved em

**Comment by mohamedfaizancassim** [comment]
> In my case, replacing
> `from keras import backend`
> with:
> `from tensorflow.keras import backend`
> in my script, fixed this problem.

This worked for me too. I went from 'from keras import layers' to 'from tensorflow.keras import layers'. Python seems to confuse Keras namespace with the Tensorflow namespace. So try to state Tensorflow.xx (like Tensorflow.Keras) where possible.

**Comment by ShakirRasheedKhanKhattak** [comment]
useless discussions, at least one should have to answer generally not like, this piece of code works for me, not all peoples are doing the same type of project or solving a similar issue

**Comment by Sawatdatta** [comment]
> useless discussions, at least one should have to answer generally not like, this piece of code works for me, not all peoples are doing the same type of project or solving a similar issue

I hope the following solution will solve your problem:

Replace
`from keras import backend as k`
with:
`from tensorflow.keras import backend as k`

If this doesn't solve your problem, you might have to use
`from tensorflow.python.keras import backend as k`

**Comment by gaurav-vision** [comment]
For downgrading the tensorflow from 2.0 to 1.4
$ pip3 install tensorflow==1.4

**Comment by OyaKesgin** [comment]
None of the above worked for me:)

**Comment by OyaKesgin** [comment]
No module named 'tensorflow_graph_in_jupyter --- do you know why it doesnt work?
When i use this code: from tensorflow_graph_in_jupyter import show_graph ,i got above message.

**Comment by nonoabc** [comment]
update keras to 2.3.1
it fixs my problem

**Comment by DanielLin94144** [comment]
thank u @nonoabc  , updata keras to 2.3.1 works for me!

**Comment by linjiahuang521** [comment]
For downgrading the keras :
                         pip uninstall keras
                         pip install keras==2.1.3
And it work.

**Comment by jhughs** [comment]
Keras integrated into TensorFlow 2.0
The article below cleared this up for me.  Key points are:
1.	Keras is included in the TensorFlow 2.0 package
2.	So no need to install the stand-alone Keras package in your environment
3.	And now the fore-mentioned solutions of using "from tensorflow.keras…" make sense.
After recognizing that and making the change, my code samples work with some minor changes here and there.
https://www.pyimagesearch.com/2019/10/21/keras-vs-tf-keras-whats-the-difference-in-tensorflow-2-0/

**Comment by Sawatdatta** [comment]
Yes, Tensorflow 2.0 is neat and clean.

**Comment by peacelovingng** [comment]
import tensorflow.python.keras.backend as K or import tensorflow.keras.backend as K
K.get_graph() works for me.

**Comment by wangyexiang** [comment]
If I use `import tensorflow.keras.backend as K` and `K.get_graph()`, I got  `AttributeError: module 'tensorflow_core.keras.backend' has no attribute 'get_graph'`. 

However, If I use `import tensorflow.python.keras.backend as K ` and `K.get_graph()`, It works. 

My question is what‘s the difference between `import tensorflow.python.keras.backend as K` and `import tensorflow.keras.backend as K`? @peacelovingng

**Comment by peacelovingng** [comment]
> **tensorflow version:2.0-cpu**
> 
> If I use `import tensorflow.keras.backend as K` and `K.get_graph()`, I got `AttributeError: module 'tensorflow_core.keras.backend' has no attribute 'get_graph'`.
> 
> However, If I use `import tensorflow.python.keras.backend as K ` and `K.get_graph()`, It works.
> 
> My question is what‘s the difference between `import tensorflow.python.keras.backend as K` and `import tensorflow.keras.backend as K`? @peacelovingng

@wangyexiang the difference is if you are using conda python directly or you are using the python interpreter installed on your system.

**Comment by wangyexiang** [comment]
Dear sir, thank you for your quickly reply. Could you make some more details about this? I use Windows7 and Anaconda(py3.7). Does it mean I should use `import tensorflow.python.keras.backend as K`?
If I use conda to build a virtual environment, then, I should use` import tensorflow.keras.backend as K`. Is it right? @peacelovingng

**Comment by ShanuDey** [comment]
keras is included in TensorFlow 2.0 afterwords. So replace `keras` to `tensorflow.keras ` in the import section of your script. 

For Example:

- Old Code
`from keras.preprocessing.image import ImageDataGenerator`
`from keras.models import Sequential`
`from keras.layers import Dense, Dropout, Activation, Flatten`
`from keras.layers import Conv2D, MaxPooling2D`

- New/Modified Code:
`from tensorflow.keras.preprocessing.image import ImageDataGenerator`
`from tensorflow.keras.models import Sequential`
`from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten`
`from tensorflow.keras.layers import Conv2D, MaxPooling2D`

**Comment by champ2313** [comment]
conda install -c anaconda keras==2.2.0   works for me

**Comment by DreamOfCiCi** [comment]
> update keras to 2.3.1
> it fixs my problem

Thank you

**Comment by jackzhou99** [comment]
iam sorry,wrong to click



---Original---

**Comment by jackzhou99** [comment]
hi,I am a junior student, I have joined a study group to learn video processing, I really want to use deep learning to rebuild the video, do you know any good methods, or do you have any code about this



---Original---

**Comment by HanHao0420** [comment]
> Has same issue with Tensorflow 2.0. I changed the imports from keras.something.something to tensorflow.keras.something and the issue seemed to have gone away. Putting it here for others to benefit.

Thanks, it works

**Comment by hamzahkhan** [comment]
@peacelovingng @wangyexiang  I tried "tensorflow.python.keras" instead of "tensorflow.keras".
Getting below error now at ` model = Model(inputs = inputs, output = conv10)`

`TypeError: ('Keyword argument not understood:', 'inputs')`

**Comment by Nagakiran1** [comment]
Start the tensorflow session in running keras lines, it creates deffault graph for the specific session

with tf.compat.v1.Session() as sess:
    " attribute Error line"

**Comment by palandlom** [comment]
For tf 2.1.0 I change to `tf.compat.v1.get_default_graph()`

```
import tensorflow as tf
# sess = tf.compat.v1.Session(graph=tf.import_graph_def(), config=session_conf)
sess = tf.compat.v1.Session(graph=tf.compat.v1.get_default_graph(), config=session_conf)
tf.compat.v1.keras.backend.cset_session(sess)

```

**Comment by ConstantSun** [comment]
> Has same issue with Tensorflow 2.0. I changed the imports from keras.something.something to tensorflow.keras.something and the issue seemed to have gone away. Putting it here for others to benefit.
Thank Godddd You're here!!!!!!!

**Comment by SourabhMagadum** [comment]
https://stackoverflow.com/a/59090507/11548826
This solved my problem

**Comment by matteocollina** [comment]
`pip install tensorflow==1.13.1`

**Comment by fj0n** [comment]
> @emikulic that only escalates and gives me error "tensorflow has no attribute 'log'", when doing tf.log.
> How does one fix this versioning problem??

This is the easiest solution. Worked for me.

**Comment by DoeJoeDE** [comment]
For me reverting to a 1.x.x (1.15.0 to be precise) version of Tensorflow did the trick

**Comment by Sarojini96** [comment]
> In my case, replacing
> `from keras import backend`
> with:
> `from tensorflow.keras import backend`
> in my script, fixed this problem.

ModuleNotFoundError: No module named 'tensorflow.keras'

**Comment by Sarojini96** [comment]
# Create model in inference mode
with tf.device(DEVICE):
    model = modellib.MaskRCNN(mode="inference", model_dir=MODEL_DIR,
                              config=config)

# Set weights file path
if config.NAME == "shapes":
    weights_path = SHAPES_MODEL_PATH
elif config.NAME == "coco":
    weights_path = COCO_MODEL_PATH
elif config.NAME == "gdxray":
    weights_path = GDXRAY_MODEL_PATH
    
# Or, uncomment to load the last model you trained
weights_path = model.find_last()[1]

# Load weights
print("Loading weights ", weights_path)
model.load_weights(weights_path, by_name=True)

**GETTING ERRORS**
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-19-d79fdfc3700c> in <module>
      2 with tf.device(DEVICE):
      3     model = modellib.MaskRCNN(mode="inference", model_dir=MODEL_DIR,
----> 4                               config=config)
      5 
      6 # Set weights file path

~/ML projects/metal-defect-detection-master/model.py in __init__(self, mode, config, model_dir)
   1761         self.model_dir = model_dir
   1762         self.set_log_dir()
-> 1763         self.keras_model = self.build(mode=mode, config=config)
   1764 
   1765     def build(self, mode, config):

~/ML projects/metal-defect-detection-master/model.py in build(self, mode, config)
   1944             mrcnn_class_logits, mrcnn_class, mrcnn_bbox =\
   1945                 fpn_classifier_graph(rpn_rois, mrcnn_feature_maps, config.IMAGE_SHAPE,
-> 1946                                      config.POOL_SIZE, config.NUM_CLASSES)
   1947 
   1948             # Detections

~/ML projects/metal-defect-detection-master/model.py in fpn_classifier_graph(rois, feature_maps, image_shape, pool_size, num_classes)
    902     # Shape: [batch, num_boxes, pool_height, pool_width, channels]
    903     x = PyramidROIAlign([pool_size, pool_size], image_shape,
--> 904                         name="roi_align_classifier")([rois] + feature_maps)
    905     # Two 1024 FC layers (implemented with Conv2D for consistency)
    906     x = KL.TimeDistributed(KL.Conv2D(1024, (pool_size, pool_size), padding="valid"),

~/anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py in symbolic_fn_wrapper(*args, **kwargs)
     73         if _SYMBOLIC_SCOPE.value:
     74             with get_graph().as_default():
---> 75                 return func(*args, **kwargs)
     76         else:
     77             return func(*args, **kwargs)

~/anaconda3/lib/python3.7/site-packages/keras/engine/base_layer.py in __call__(self, inputs, **kwargs)
    487             # Actually call the layer,
    488             # collecting output(s), mask(s), and shape(s).
--> 489             output = self.call(inputs, **kwargs)
    490             output_mask = self.compute_mask(inputs, previous_mask)
    491 

~/ML projects/metal-defect-detection-master/model.py in call(self, inputs)
    363         image_area = tf.cast(
    364             self.image_shape[0] * self.image_shape[1], tf.float32)
--> 365         roi_level = log2_graph(tf.sqrt(h * w) / (224.0 / tf.sqrt(image_area)))
    366         roi_level = tf.minimum(5, tf.maximum(
    367             2, 4 + tf.cast(tf.round(roi_level), tf.int32)))

~/ML projects/metal-defect-detection-master/model.py in log2_graph(x)
    318 def log2_graph(x):
    319     """Implementatin of Log2. TF doesn't have a native implemenation."""
--> 320     return tf.math.log(x) / tf.log(2.0)
    321 
    322 

AttributeError: module 'tensorflow' has no attribute 'log'

**Comment by guoxiaojun1999** [comment]
If you are using bert-as-service, setting num_workers to 1 will cause this problem. Try setting it to 2 or bigger. But I got a memory problem when changing it. :(

**Comment by triumph9989** [comment]
> Has same issue with Tensorflow 2.0. I changed the imports from keras.something.something to tensorflow.keras.something and the issue seemed to have gone away. Putting it here for others to benefit.
thanks for the method.that is works for my code.

**Comment by triumph9989** [comment]
@amitdingareNovelis Thank you for your method. That is works on my code.

**Comment by btphan95** [comment]
@Ademord This solved everything! After failing to follow this [tutorial](https://medium.com/analytics-vidhya/deploy-your-first-deep-learning-model-on-kubernetes-with-python-keras-flask-and-docker-575dc07d9e76), I set my Keras version to 2.2.4 and TF to 1.13.1, and it solved all of my errors. Thanks :)

**Comment by RahulKamma0369** [comment]
i too  have same issue in previous .. but i resolved it by using

from tensorflow.python.framework import ops
ops.get_default_graph()

and the error got vanished 

thanks for the guy who helped me i gorgot his name

**Comment by tianzhipengfei** [comment]
> `pip install tensorflow==1.13.1`

This solved my problem

**Comment by kpkpal** [comment]
> > @MrZhengXin How?
> 
> Oh, sorry. I mean change the code manually like tf.compat.v1.get_default_graph

It works. Thank you

**Comment by sarithdivakarm** [comment]
> @Ademord This solved everything! After failing to follow this [tutorial](https://medium.com/analytics-vidhya/deploy-your-first-deep-learning-model-on-kubernetes-with-python-keras-flask-and-docker-575dc07d9e76), I set my Keras version to 2.2.4 and TF to 1.13.1, and it solved all of my errors. Thanks :)

Thanks. It worked :)

**Comment by carrell-ncl** [comment]
Tried everything and it didn't work. Simply upgrading Keras worked for me - 'pip install -U keras'
Need version 2.3 or above

**Comment by marsalan06** [comment]
i had this error in importing embedded layer,
i had written 
from keras.layers import Embedding
i changed it to 
from tensorflow.keras.layer import Embedding

**Comment by cod3licious** [comment]
I ran some code on my macbook where I had installed the regular tensorflow package (for cpu; version 2.3.0) together with keras (version 2.4.3) and everything worked fine. Then I wanted to run the same code on my linux machine with a GPU, where I had installed tensorflow-gpu and keras (same versions as above) and suddenly I got this AttributeError and had to change all my `keras` imports to `tensorflow.keras`. If it works with the regular tensorflow package, why not with the gpu version?

**Comment by Sawatdatta** [comment]
It seems that you have installed stand alone keras package on your macbook, that's why it was working without using tensorflow.keras . On your Linux machine you have installed TensorFlow with keras bundled inside. You need not to install standalone keras if you are installing recent versions of TensorFlow.

**Comment by mohammed-safwan** [comment]
In my case, I had both `tensorflow` and `keras` installed. Uninstalling `keras` fixed the issue for me.

**Comment by corn23** [comment]
had the same issue. using tensor flow 2.3.0. have the error module 'tensorflow' has no attribute 'get_default_graph'

**Comment by vpobleteacustica** [comment]
Ademord... Thank you very much... The perfect solution... After a lot of time looking for the solution

**Comment by AtaullahMasum** [comment]
Please tell me anyone how solve this problem 

AttributeError                            Traceback (most recent call last)
<ipython-input-16-879dc9c91e30> in <module>
      1 for modifier in ['guided', 'relu']:
      2     grads = visualize_saliency(model, layer_idx, filter_indices=class_idx,
----> 3                                seed_input=x_test[idx], backprop_modifier=modifier)
      4     plt.figure()
      5     plt.title(modifier)

~\Anaconda3\envs\tensorflow\lib\site-packages\vis\visualization\saliency.py in visualize_saliency(model, layer_idx, filter_indices, seed_input, wrt_tensor, backprop_modifier, grad_modifier, keepdims)
    125     if backprop_modifier is not None:
    126         modifier_fn = get(backprop_modifier)
--> 127         model = modifier_fn(model)
    128 
    129     # `ActivationMaximization` loss reduces as outputs get large, hence negative gradients indicate the direction

~\Anaconda3\envs\tensorflow\lib\site-packages\vis\backprop_modifiers.py in guided(model)
     15         (https://arxiv.org/pdf/1412.6806.pdf)
     16     """
---> 17     return backend.modify_model_backprop(model, 'guided')
     18 
     19 

~\Anaconda3\envs\tensorflow\lib\site-packages\vis\backend\tensorflow_backend.py in modify_model_backprop(model, backprop_modifier)
     93 
     94         # 3. Create graph under custom context manager.
---> 95         with tf.get_default_graph().gradient_override_map({'Relu': backprop_modifier}):
     96             #  This should rebuild graph with modifications.
     97             modified_model = load_model(model_path)

AttributeError: module 'tensorflow' has no attribute 'get_default_graph'

**Comment by Preetesh21** [comment]
I also had a similar problem
![tf_issue](https://user-images.githubusercontent.com/50336851/93571453-1a5cb680-f9b2-11ea-8d5d-9418fc050b8b.PNG)
I solved it using the advice given here  [Link](https://github.com/keras-team/keras/issues/12783) by @psschand
i.e. to add these lines instead 
from tensorflow.python.framework import ops
ops.reset_default_graph()

**Comment by Z-Shakeri** [comment]
I had the same problem using python 3.8. uninstalling Keras using `sudo pip uninstall keras` and re-installing it did the trick form me.

**Comment by paolosecci** [comment]
after running "pip install tensorflow==1.13.1"

ERROR: Could not find a version that satisfies the requirement tensorflow==1.13.1

**Comment by emikulic** [comment]
It looks like 1.13.1 goes up to Python 3.7, not 3.8: https://pypi.org/project/tensorflow/1.13.1/#files

**Comment by M7un** [comment]
solution:
https://github.com/M7un/Error/issues/1

**Comment by kirtijaiz** [comment]
I uninstalled keras then installed it back :) solved my problm!

**Comment by kthossen** [comment]
For my case, I also just reinstall Keras and TensorFlow to run it.

**Comment by Hassan-Shoayb** [comment]
Using tf.get_default_graph() is deprecated, Instead used tf.compat.v1.get_default_graph()
it works for me really fine.
