### ISSUE TITLE
Making a bot which posts the documentation page in htlm if a pull request changed it

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [keras-team/keras#12382]
If someone makes a PR which changes the documentation, a bot should build the documentation and comment on the pull request with the html page rendered as pdf. This should allow PR reviewers to see very quickly if there is a problem of formatting, and it would be easy to fix it early. That would make huge time savings in the long run.

Nearly all CI projects authorize using docker and https://github.com/arachnys/athenapdf seems good enough to convert html to PDF. Furthermore pygithub is a very cool package allowing to interact with github super easily with python (ideal to make bots).

Those tools should make the task not easy, but at least feasable given enough time.

This issue is also valid for keras-contrib, see https://github.com/keras-team/keras-contrib/issues/472

**Comment by JoshuaRM** [comment]
Is this still available? I think this would be similar to the bot you have created, please let me know if I can work on this.
