### ISSUE TITLE
Can Keras utilize two optimizers parallel for two branches and merge them together in the end layer for same label?

### ISSUE THREAD

**Issue by mangohero1985** [keras-team/keras#12386]
Hi all, I am trying to implement the google wide&deep model in Keras.

From the original paper and the official TF implementation, the optimization was done by two optimizers parallel.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py#L328

Can the model be compiled by optimizer dictionary like {branch1: “optimizer1”, branch2:“optimizer2"}? and the loss can be computed separately.
Thanks in advance.

**Comment by yoonkt200** [comment]
Hi, I am solving the same problem. 
We need concatenate wide component + deep component.
So, optimizer must be attached before the two are combined and compile.
Who knows the answer?

**Comment by mangohero1985** [comment]
Hi，Yoon
I am rewrite a complie method which can recieve optimizer list. But still not finish it. After that, i would submit a pull request. But now, you can try to feed several fix optimizers manully. The trainable weights can be splitted here:
https://github.com/keras-team/keras/blob/master/keras/engine/training.py#L507
Then the optimizers can be denoted to your own defination. hope this can help you.

**Comment by tychen5** [comment]
Hi all, I am facing the same issue.
If I pass the optimizer list to compile, it will pass. However, it will throw out errors when I use "fit" function: AttributeError: 'list' object has no attribute 'apply_gradients'.
If there's any solution or workaround method, I am very grateful.
