### ISSUE TITLE
Training output_shape differs from inference

### ISSUE THREAD

**Issue by CasperDern** [keras-team/keras#12402]
- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps`

- [x] Check that your version of TensorFlow is up-to-date. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

Hi, all

I have an issue where the output_shape differs depending on if you are training or not.
I get a situation where this happens
```python3
# train_gen yields [(16,1024), (16,1024,9611)]
# predict_gen yields (16,1024)
assert training_batch.shape == (16,1024)
x = _model.predict(training_batch)
assert x.shape == (16, 1024, 9611) # OK
_model.predict_generator(generator=predict_gen, steps=100) # Runs without errors
_model.fit_generator(generator=train_gen, verbose=2, steps_per_epoch=100, epochs=20)
# ValueError: Error when checking target: expected Output to have shape (1024, 1) but got array with shape (1024, 9611)
# note: evaluate_generator and train_on_batch give the same error
```
Full stacktrace: https://gist.github.com/CasperDern/3d7e20663f1b6034c7753ba52a1878de
Model graph: https://imgur.com/b0ZyvkK
Test scenario: https://gist.github.com/CasperDern/8d1f0fd3c4ab3f6805d5bbf38f561a29

Using layer.output_shape and plot_model I've checked that the output shape is indeed (None,1024,9611)

I have looked around for similar issues and actually came across one which denied the possibility of the output_shapes differing between inference and training, so I wanted to know if that changed at some point or if this might be a bug.

**Comment by RaphaelMeudec** [comment]
@CasperDern Why using the same generator when predicting and when fitting ? During training, the generator should provide both inputs and outputs (hence a tuple), whereas in prediction, it should only provide the inputs (first element of each tuple).

**Comment by CasperDern** [comment]
@RaphaelMeudec That's my bad, I'll correct the code above, the example above is mostly meant as psuedo code. For a reproducable example (using minimal np.zeros input, and no generator) check the [Test scenario gist](https://gist.github.com/CasperDern/8d1f0fd3c4ab3f6805d5bbf38f561a29)
