### ISSUE TITLE
[CI] The Travis build is pending for 3 days to check PR #12357.

### ISSUE THREAD

**Issue by leemgs** [keras-team/keras#12417]
I have one question on a CI operation that investigates the PR #12357. It seems that the Travis CI build is broken in case of PR #12357.  As we can see, The status of a build CI tasks is still a "**Pending**" step despite a last comment  by @ConcurrentPract passed 3 days. The PR could not be merged by a reviewer by getting the "Merging is blocked" step because the Travis CI facility is still running. 

Why does not the CI facility report a test result between a 'failure' and 'success' status? What is a possible reason? Who is in charge of the CI facilities of this github repository?

### The output of CI facility: 

* Error message:
```bash
Some checks haven’t completed yet
1 pending check

continuous-integration/travis-ci/pr Pending — The Travis CI build is in progress
Required

```
* Screenshot:
![image](https://user-images.githubusercontent.com/82404/54007436-0fae4800-41a5-11e9-99f7-ec718bd2519e.png)

**Comment by leemgs** [comment]
In case of PR #12336, the PR is approved by a reviewer although The Travis CI build failed.
It's weird. Is the Travis CI facility is normal? 

* Screenshot:

![image](https://user-images.githubusercontent.com/82404/54007970-e0e5a100-41a7-11e9-89ab-bd3cfc19f8bf.png)

**Comment by abhaikollara** [comment]
#12336 was approved because it was a fix in the tests. The fix reveals a bug that was undiscovered until then (see related issue #12335). I don't know why it hasn't been merged though.

**Comment by leemgs** [comment]
> continuous-integration/travis-ci/pr — The Travis CI build failed

@abhaikollara  As we can see, PR #12336 has been tackled by the abnormal CI bot for a long days.  :)
