### ISSUE TITLE
How to get user input for translation in seq2seq model?

### ISSUE THREAD

**Issue by sandeepdahake** [keras-team/keras#12411]
Hello,

I am working on to build a translation model for English to Spanish sentences.  I am using [this](https://github.com/keras-team/keras/blob/master/examples/lstm_seq2seq.py)  code to train and decode a sentences. I also use [this](https://github.com/keras-team/keras/blob/master/examples/lstm_seq2seq_restore.py) code to restore a model. Here is the final code that we are using for the translation:

for seq_index in range(100):
    # Take one sequence (part of the training set)
    # for trying out decoding.
    input_seq = encoder_input_data[seq_index: seq_index + 1]
    decoded_sentence = decode_sequence(input_seq)
    print('-')
    print('Input sentence:', input_texts[seq_index])
    print('Decoded sentence:', decoded_sentence)

In this code it is taking sentences for specific range from the existing dataset and decode those sentences. Instead of this I want to put user input sentence and decode a sentence for that particular user input sentence?

How can I do that?

Thanks

**Comment by satyam-bits** [comment]
Were you able to give new user input and decode it?

**Comment by stbtsaa** [comment]
Were you able to give user input and decode?
