### ISSUE TITLE
Keras Summary letter in params count

### ISSUE THREAD

**Issue by adrian-spataru** [keras-team/keras#12427]
I've built this particular model and it runs fine. What I have never seen and couldn't find in the documentation is the explanation of letters in the model summary. If you look at `lstm_2` the param count has the letter N in it. What does this mean?

![image](https://i.ibb.co/W6N5Nm0/Bildschirmfoto-vom-2019-03-09-01-09-26.png "Image")

I'm running  Keras ` 2.2.4` with Tensorflow backend

**Comment by basuam** [comment]
Hi, I also met with the same problem. I'm building a Sequence to Sequence Autoencoder. Did you understand why the Letter 'N'?

**Comment by adrian-spataru** [comment]
The output Shape was  [(None, 21, 512), (None, something, seomthing)]. But the output on the terminal was cut off. So "N" stands for None

**Comment by adrian-spataru** [comment]
> Hi, I also met with the same problem. I'm building a Sequence to Sequence Autoencoder. Did you understand why the Letter 'N'?
The output Shape was [(None, 21, 512), (None, something, seomthing)]. But the output on the terminal was cut off. So "N" stands for None

**Comment by basuam** [comment]
Thank you!!! This makes sense. Being honest, I'm attempting to share the weights in the Encoder-Decoder and I thought the 'N' may meant that I achieved that goal. Anyways, I'll keep trying to share the same weights between them.
