### ISSUE TITLE
Unable to import Keras (cannot import name 'issparse' from 'scipy.sparse' )

### ISSUE THREAD

**Issue by talhaanwarch** [keras-team/keras#12429]
Greetings. I have installed tensor flow (version '1.13.1'), and keras also. But when i try to import keras, i get the following error.

ImportError: cannot import name 'issparse' from 'scipy.sparse' (unknown location)

I face following issue while installing keras
_scikit-bio 0.5.5 requires matplotlib>=1.4.3, which is not installed.
scikit-bio 0.5.5 requires pandas>=0.23, which is not installed.
scikit-bio 0.5.5 requires scikit-learn>=0.19.1, which is not installed._

i have treid to upgrade scipy, but it say its already updated
_Requirement already up-to-date: scipy in c:\anaconda3\lib\site-packages (1.2.1)
Requirement already satisfied, skipping upgrade: numpy>=1.8.2 in c:\anaconda3\lib\site-packages (from scipy) (1.16.2)_

**complete log is as follow while installing keras**

Requirement already satisfied: keras in c:\anaconda3\lib\site-packages (2.2.4)
Collecting scipy>=0.14 (from keras)
  Downloading https://files.pythonhosted.org/packages/58/f0/d00c0e01e077da883f030af3ff5ce653a0e9e4786f83faa89a6e18c98612/scipy-1.2.1-cp37-cp37m-win_amd64.whl (30.0MB)
    100% |████████████████████████████████| 30.0MB 242kB/s
Collecting h5py (from keras)
  Downloading https://files.pythonhosted.org/packages/4f/1e/89aa610afce8df6fd1f12647600a05e902238587ae6375442a3164b59d51/h5py-2.9.0-cp37-cp37m-win_amd64.whl (2.4MB)
    100% |████████████████████████████████| 2.4MB 718kB/s
Requirement already satisfied: pyyaml in c:\anaconda3\lib\site-packages (from keras) (3.13)
Requirement already satisfied: keras-preprocessing>=1.0.5 in c:\anaconda3\lib\site-packages (from keras) (1.0.9)
Requirement already satisfied: keras-applications>=1.0.6 in c:\anaconda3\lib\site-packages (from keras) (1.0.7)
Requirement already satisfied: numpy>=1.9.1 in c:\anaconda3\lib\site-packages (from keras) (1.16.2)
Requirement already satisfied: six>=1.9.0 in c:\anaconda3\lib\site-packages (from keras) (1.12.0)
scikit-bio 0.5.5 requires matplotlib>=1.4.3, which is not installed.
scikit-bio 0.5.5 requires pandas>=0.23, which is not installed.
scikit-bio 0.5.5 requires scikit-learn>=0.19.1, which is not installed.
Installing collected packages: scipy, h5py
Successfully installed h5py-2.9.0 scipy-1.2.1

**complete log while importing keras**
import keras
Traceback (most recent call last):

  File "<ipython-input-29-88d96843a926>", line 1, in <module>
    import keras

  File "C:\Anaconda3\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils

  File "C:\Anaconda3\lib\site-packages\keras\utils\__init__.py", line 27, in <module>
    from .multi_gpu_utils import multi_gpu_model

  File "C:\Anaconda3\lib\site-packages\keras\utils\multi_gpu_utils.py", line 7, in <module>
    from ..layers.merge import concatenate

  File "C:\Anaconda3\lib\site-packages\keras\layers\__init__.py", line 5, in <module>
    from ..engine import Input

  File "C:\Anaconda3\lib\site-packages\keras\engine\__init__.py", line 8, in <module>
    from .training import Model

  File "C:\Anaconda3\lib\site-packages\keras\engine\training.py", line 21, in <module>
    from . import training_arrays

  File "C:\Anaconda3\lib\site-packages\keras\engine\training_arrays.py", line 8, in <module>
    from scipy.sparse import issparse

**Comment by jvishnuvardhan** [comment]
@talhaanwarch Were you able to install TF and Keras successfully? If you have Windows10, you could follow this [procedure](https://github.com/jvishnuvardhan/Installing-TensorFlow-GPU-on-Windows-10-TF1.12) to install TF and keras. Thanks!

**Comment by jvishnuvardhan** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
