### ISSUE TITLE
fit_generator complains validation_freq is unexpected keyword 

### ISSUE THREAD

**Issue by haydenth** [keras-team/keras#12442]
Hello. Love Keras! I have a relatively straight-forward call in my code to `fit_generator` but it is returning that one of the parameters (validation_freq) is unexpected. However, all the documentation and even the code to `fit_generator` shows it is an acceptable parameter.

The call, where parallel_model is an object of type `Sequential`
```
  parallel_model.compile(loss='categorical_crossentropy',
    optimizer=rms,
    metrics=['accuracy'])
  train_generator = parallel_model.fit_generator(
    generator=complex_data_generator(x_data, y_data, config),
    epochs=400,
    steps_per_epoch=(len(y_data)/DEFAULT_BATCH_SIZE),
    callbacks=callbacks,
    validation_data=(vx_data, vy_data),
    validation_freq=10)
```

The error response:
```
Traceback (most recent call last):
  File "train.py", line 102, in <module>
    validation_freq=10)
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
TypeError: fit_generator() got an unexpected keyword argument 'validation_freq'

```

Keras & Tensorflow Versions
```
>>> import keras
Using TensorFlow backend.
>>> keras.__version__
'2.2.4'
>>> import tensorflow
>>> tensorflow.__version__
'1.13.1'
```
Perhaps this is user error on my behalf but I do not think this is expected behavior given the docs. Thanks!

**Comment by haydenth** [comment]
This appears to work properly when I install Keras from current source versus pypi, so please disregard.

**Comment by MythreyaK** [comment]
Any fix for the PyPi package version? I have the same issue

**Comment by NoNamesLeft4Me** [comment]
@haydenth This is chaos. I use pip to install the lastest version 2.2.4 and had the same issue, which I found out fit_generator has different API than the official doc. So you mean I have to install from git source to use this parameter?

**Comment by MythreyaK** [comment]
> @haydenth  

Well perhaps for now; I had to do install from git to fix the issue

**Comment by haydenth** [comment]
I'm not the package maintainer - don't yell at me :) I just had more luck installing this from source.

**Comment by NoNamesLeft4Me** [comment]
@haydenth not yelling at you, just trying to figure out what's happening.:) If it is a version control problem, I will raise a request.

**Comment by NicolasWinckler** [comment]
I got the same issue on keras 2.2.4 (installed via pip)

**Comment by duygusar** [comment]
I get the same issue with keras 2.1.2 (pip installation)

**Comment by shahryarbaki** [comment]
I get the same issue with Keras 2.2.4 (pip installation)

**Comment by patrickvonplaten** [comment]
Same issue with Keras 2.2.4-tf (using tensorflow.python.keras)

**Comment by dabasajay** [comment]
You can either wait for next version of Keras or if you need a quick fix, just update Keras with master branch using:
`pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps`

**Comment by akshaykvnit** [comment]
I don't see why this issue was closed. Since this issue is prevalent since March 2019 and has not yet been fixed for the pip installation.

**Comment by sarahboufelja** [comment]
Got the same issue on keras 2.1.3, please reopen the issue.

**Comment by jgcaffari1** [comment]
I also have the same issue. Please reopen.
