### ISSUE TITLE
Keras Error: Variable does not exist, or was not created with tf.get_variable()

### ISSUE THREAD

**Issue by Gouiaa** [keras-team/keras#12457]
```
import tensorflow.keras as ks
def scope_error_test():
    input_holder = tf.placeholder(dtype=tf.float32,
                                  shape=(None, 368, 368, 3),
                                  name='input')
    with tf.variable_scope("scope_1"):
        with tf.variable_scope("scope_2"):
            conv1 = ks.layers.Conv2D(kernel_size=7,
                                     filters=64,
                                     strides=2,
                                     padding='same',
                                     activation=tf.nn.relu,
                                     name='conv1')(input_holder)
            pool1 = ks.layers.MaxPool2D(pool_size=3, padding='same',
                                        strides=2,
                                        name='pool1')(inputs=conv1)
    print(pool1.get_shape().as_list())
with tf.Session() as sess:
        scope_error_test()
        sess.run(tf.global_variables_initializer())
        print(tf.global_variables())
        with tf.variable_scope('', reuse=True):
            for variable in tf.global_variables():
                var_name = variable.name.split(':')[0]
                var_tf = tf.get_variable(var_name)
```
In this example code, I want to understand why I get this error: ValueError: Variable scope_1/scope_2/conv1/kernel does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=tf.AUTO_REUSE in VarScope?

Note: I used `tensorflow.contrib.layers` instead of `tensorflow.keras.layers` and It was working correctly! Could be a bug !?

I have tried `tensorflow 1.9.0` and `tensorflow 1.12.0`

**Comment by jvishnuvardhan** [comment]
@Gouiaa Cross-posted to TFlow repo [here](https://github.com/tensorflow/tensorflow/issues/26629). Thanks!

**Comment by Gouiaa** [comment]
@jvishnuvardhan is it a bug, right?

**Comment by umbrellalalalala** [comment]
You could try:
```
print tf.get_variable_scope().reuse
```
Add this before `scope_error_test()`, and if you get "True", you could add:
```
with tf.variable_scope(tf.get_variable_scope(), reuse=tf.AUTO_REUSE):
```
before `scope_error_test()`.

Some details I answered [here](https://github.com/tensorflow/tensorflow/issues/26629) just now.

**Comment by jvishnuvardhan** [comment]
I am closing this issue as it was cross-posted to TF repo [here](https://github.com/tensorflow/tensorflow/issues/26629). Thanks!
