### ISSUE TITLE
kernel initializers are called incorrectly when using load_model

### ISSUE THREAD

**Issue by bram98** [keras-team/keras#12452]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by bram98** [comment]
Keras version 2.2.4
tensorflow version 1.13.1
I'm using colab notebooks

I'm trying to make a custom initializer and save the model using model.save(). I have the following code:
```
import numpy as np

import tensorflow as tf
import keras

from google.colab import drive

from keras.models import Sequential, load_model
from keras.layers import Dense, Dropout, Flatten, Lambda, Reshape, Activation
from keras.layers.convolutional import Conv2D, MaxPooling2D
from keras import backend as K
K.set_image_data_format('channels_first')
K.backend()
# the output should be 'tensorflow'
```
>'tensorflow'

```
def myInit( input_shape, dtype=None):
  weights = np.full( input_shape, 2019 )
  return K.variable( weights, dtype=dtype )
```
This initializer is given an input_shape and returns a keras tensor like in the docs: [https://keras.io/initializers/](https://keras.io/initializers/)
```
model = Sequential()
model.add( 
  Dense( 40, input_shape=(784,) )
)
model.add(
  Dense( 30, kernel_initializer=myInit )
)
model.add(
  Dense( 5 )
)
model.build()
```
The weights are initialized correctly because when I call `model.layers[1].get_weights()` I get an array full of 2019.
I save the model using model.save:
```
model.save(somepath)
```
In a different notebook I then call 
```
model = load_model(somepath, 
           custom_objects={
               'tf' : tf,
               'myInit' : myInit
           }
          )
```
In this notebook `myInit` and all the imports are defined as well.
When I call `load_model` I get the following error:
`
TypeError: myInit() missing 1 required positional argument: 'input_shape'`

So it seems when the model is loaded, the input_shape is not passed to myInit. Does anyone have any idea?

**Comment by zrx1046** [comment]
Hello, how do you solve this problem, I am also a custom layer, the following problems arise:
TypeError: init() missing 2 required positional arguments: 'pool_size' and 'num_rois'
my keras=2.2.0,,tensorflow=1.8.0

**Comment by zrx1046** [comment]
@bram98 Hello, how do you solve this problem, I am also a custom layer, the following problems arise:
TypeError: init() missing 2 required positional arguments: 'pool_size' and 'num_rois'
my keras=2.2.0,,tensorflow=1.8.0
