### ISSUE TITLE
Unable to predict multiple outputs using Keras functional API with multiple inputs,outputs

### ISSUE THREAD

**Issue by Shaier** [keras-team/keras#12467]
Running a model with 9 inputs and 9 outputs on Keras Functional API.
The model fits just fine, but I'm getting this error when I'm running
`model.predict
`
This is my fit function:

```
history = model.fit(x=[train1,train2,train3,train4,train5,train6,train7,train8,train9], 
          y=[y1,y2,y3,y4,y5,y6,y7,y8,y9], callbacks=callbacks,
          batch_size=40, epochs=50, verbose=1, validation_split=0.1, shuffle=False)
```    

It runs perfectly, and I can even plot the history.

Then I'm running:

`model.predict(train1[1],train1[2],train1[3],train1[4],train1[5],train1[6],train1[7],train1[8],train1[9]) 
` 
And getting the error:

`TypeError: predict() takes from 2 to 5 positional arguments but 10 were given
`

I checked that the shape of each input is similar to what the model can accept (each train1[x] has the same shape)

I tried running

`model.predict([train1[1],train1[2],train1[3],train1[4],train1[5],train1[6],train1[7],train1[8],train1[9]])   
`
And got the following error:

 `ValueError: Error when checking input: expected input_1 to have shape (9216,) but got array with shape (1,)`  

I also tried running:

`model.predict(train1[1:9])  
`
And got

`ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 9 array(s), but instead got the following list of 8 arrays: [array([[255.]... –`

I also tried running

`model.predict(train1[1:10])
`
And got

`ValueError: Error when checking input: expected input_1 to have shape (9216,) but got array with shape (1,)`

**Comment by nicoapg** [comment]
did you ever figure this out?
