### ISSUE TITLE
model.save(filename) hits JSON errors with bytes in config dictionary

### ISSUE THREAD

**Issue by cottrell** [keras-team/keras#12473]
I am running the keras that ships with tensorflow.

```
In [7]: tf.keras.__version__
Out[7]: '2.2.4-tf'

In [8]: tf.__version__
Out[8]: '1.14.1-dev20190313'
```

Something is yielding some bytes in the config dictionary used by save function. For example: 

```
In [9]: n.model.get_config()['layers'][-1]
Out[9]:
{'name': 'Squeeze_1',
 'class_name': 'TensorFlowOpLayer',
 'config': {'name': 'Squeeze_1',
  'trainable': True,
  'dtype': None,
  'node_def': b'\n\tSqueeze_1\x12\x07Squeeze\x1a\x12q_output_1/BiasAdd*\x07\n\x01T\x12\x020\x01*\x1e\n\x0csqueeze_dims\x12\x0e\n\x0c\x1a\n\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01',
  'constants': DictWrapper({})},
 'inbound_nodes': [[['q_output', 0, 0, {}]]]}
```

When I try to run keras from github (latest, not the one in tensorflow) my code doesn't even run so I am not bothering figuring out the API change the blocks the test yet.

**Comment by jvishnuvardhan** [comment]
@cottrell Could you create a GitHub gist and provide a link to the code so that we can try to reproduce the bug? Also, provide trace of bug. Thanks

**Comment by cottrell** [comment]
Will try to fork out a minimal example without IP shortly, was hoping someone might have a guess as to what is causing this and I could just roll a patch if it was simple (am guessing it is). Sometimes that is easier that a minimal example :)

**Comment by cottrell** [comment]
Made a gist here:

https://gist.github.com/cottrell/580c3c49e13c3317038d6351f82f5156
