### ISSUE TITLE
Expected to see 2 array(s), but instead got the following list of 1 arrays

### ISSUE THREAD

**Issue by StephenLouis** [keras-team/keras#12476]
I want to create a model that receive one image and compute the image by two Softmax(two output). The code is:

-------------------------------------------------
```
base_model = InceptionV3(include_top=False)
x = base_model.output
x = GlobalAveragePooling2D()(x)

# first Softmax
x_1 = Dense(1024, activation='relu')(x)
predictions_1 = Dense(4, activation='softmax')(x_1)

# second Softmax
x_2 = Dense(1024, activation='relu')(x)
predictions_2 = Dense(4, activation='softmax')(x_2)

my_model = Model(inputs=base_model.input, outputs=[predictions_1,predictions_2])

# train
my_model.compile(...)
my_model.fit_generator(...)
```
-------------------------------------------------

When training, I got error:

ValueError: 
Expected to see 2 array(s), but instead got the following list of 1 arrays: [array([[0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],...

**Comment by Fanshia** [comment]
Same problem. Do you find the answer?

**Comment by aminhotob** [comment]
The problem is that your data generator yields `input_array, output_array` the shape for output_array is `[batch_size,2]`. **Instead** you should return a list of two numpy arrays each with one dimension e.g. `input_array,[predictions_1, predictions_2]`where size of predictions_1 and predictions_2 is `[batch_size,]`

**Comment by abhishekpundir22** [comment]
which line showing the error? please attach full error report
