### ISSUE TITLE
Any way for Keras officially supporting Colab TPUs?

### ISSUE THREAD

**Issue by ParikhKadam** [keras-team/keras#12504]
Various blog posts, stackoverflow answers and tweets say like it's very easy to convert a Keras model to Tensorflow Keras model which can be used in Tensorflow TPU wrapper to get the model support TPU. But that's not very easy..

What about custom layers? How can I convert custom layers to get trained on TPUs? Or what about when I used Keras backend functions? Surely things are messing up and I am getting nothing but errors.

Do you have any plans on releasing Keras with TPU support? If yes, then can you give an estimated date till which users should wait?

**Comment by FarhanSajid1** [comment]
yeah is there any way to use a keras model and tpu opposed to using tensorflow?

**Comment by kiruthihan10** [comment]
when i try to do transfer learning it is saying it has an assertion error in the base model.
Can any one explain me the reason for this error

`# -*- coding: utf-8 -*-
"""Kvasir-TPU.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18Zdd97H_fytOkQeidttQKfcrVmnRMOCz
"""

class file_write:
    import os

    def __init__(self,file_name,Address=os.getcwd()):
        self.Address=Address+file_name
        print(self.Address)
        #Address = "C:/Users/kirut/Documents/Project Prime/"
        self.file = open(self.Address,'w')

    def write(self,n,new_line=True):
        if new_line == True:
            write_string = str(n)+'\n'
        else:
            write_string = str(n)
        self.file.write(write_string)

    def close(self):
        self.file.close()


class file_read:
    import os

    def __init__(self,file_name,Address=os.getcwd()):
        self.Address=Address+file_name
        print(self.Address)
        self.file = open(self.Address,'r')

    def read(self,new_line=True,dtype=int):
        self.lines = []
        for line in self.file:
            if new_line == True:
                line = line.strip()
            self.lines.append(dtype(line))
        return self.lines

    def close(self):
        self.file.close()

class divider:
    def __init__(self,data,test_percentage=10):
        self.data = data
        self.test_percentage=test_percentage

    def test(self):
        return(self.data[:int(len(self.data)*self.test_percentage/100)])

    def train(self):
        return(self.data[int(len(self.data)*self.test_percentage/100):])

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/gdrive')
# %cd /gdrive

import glob
import os

class content_reader:
    def __init__(self,address):
        self.address = address+'/'

    def read_file_names(self):
        if True:
            out = []
            for r, d, f in os.walk(self.address):
                for folder in f:
                    out.append(os.path.join(r, folder))
            #for filename in glob.glob(self.address):
            #    print(filename)
            #    out.append(filename)
            return out
        else:
            print("Address has got no files or it is not a folder")
            return out

    def read_folder_names(self):
        if True:
            out = []
            for r, d, f in os.walk(self.address):
                for folder in d:
                    out.append(os.path.join(r, folder))
            #for filename in glob.glob(self.address):
            #    print(filename)
            #    out.append(filename)
            return out
        else:
            print("Address has got no files or it is not a folder")
            return out

    def read_text(self,output_type="LIST",strip=True):

        try:
            file = open(self.address,'r')
            if output_type.upper() == "LIST":
                out = []
                for line in file:
                    if strip == True:
                        out.append(line.strip)
                    else:
                        out.append(line)
            elif output_type.upper() == "TEXT":
                out = file.read()
            return out
        except:
            print("NOT A TEXT FILE")

    def read_image(self,output_type="NP_ARRAY",size="Default"):
        self.address = self.address[:-1]
        import PIL
        image = PIL.Image.open(self.address)
        if size != "Default":
            self.size = size
            image = image.resize(size,PIL.Image.ANTIALIAS)
        else:
            self.size=image.size
        if output_type=="NP_ARRAY":
            import numpy as np
            array = np.asarray(image)
            return array
        else:
            return image

import numpy as np
import random
class organize:
    def __init__(self,location):
        self.input_location = location

    def read_files(self):
        input_location = self.input_location
        input_files = content_reader(input_location)
        input_files_names = input_files.read_folder_names()
        X_datas = []
        Y_datas = []
        ref = {}
        i=0
        n = 0
        print(len(input_files_names))
        for file in input_files_names:
            ref[file]=i
            i+=1
        for file in input_files_names:
            file_location = file
            file_obj = content_reader(file_location)
            print(file_location)
            images = file_obj.read_file_names()
            for image_name in images:
                n+=1
                image_location = image_name
                image = content_reader(image_location)
                image_data = image.read_image(size=(331,331))
                X_datas.append(image_data)
                Y_datas.append(ref[file])
                print(float(n)/4000*100)
        total_number_of_data = len(Y_datas)
        zero = list(range(0,total_number_of_data-1))
        random.shuffle(zero)
        shuffled = zero
        #print(shuffled)
        X=[]
        Y=[]
        for i in shuffled:
            X.append(X_datas[i])
            Y.append(Y_datas[i])
        return([X,Y])

base_dir = os.path.join('','/gdrive/My Drive/Kvasir/kvasir-dataset')
train_dir = os.path.join(base_dir,'Train')
validation_dir = os.path.join(base_dir,'Validation')

train_dyed_lifted_polyps = os.path.join(train_dir,'dyed-lifted-polyps')
train_dyed_resection_margins = os.path.join(train_dir,'dyed_resection_margins')
train_esophagitis = os.path.join(train_dir,'esophagitis')
train_normal_cecum = os.path.join(train_dir,'normal-cecum')
train_normal_pylorus = os.path.join(train_dir,'normal-pylorus')
train_normal_z_line = os.path.join(train_dir,'normal-z-line')
train_polyps = os.path.join(train_dir,'polyps')
train_ulcerative_colitis = os.path.join(train_dir,'ulcerative-colitis')

validation_dyed_lifted_polyps = os.path.join(validation_dir,'dyed-lifted-polyps')
validation_dyed_resection_margins = os.path.join(validation_dir,'dyed_resection_margins')
validation_esophagitis = os.path.join(validation_dir,'esophagitis')
validation_normal_cecum = os.path.join(validation_dir,'normal-cecum')
validation_normal_pylorus = os.path.join(validation_dir,'normal-pylorus')
validation_normal_z_line = os.path.join(validation_dir,'normal-z-line')
validation_polyps = os.path.join(validation_dir,'polyps')
validation_ulcerative_colitis = os.path.join(validation_dir,'ulcerative-colitis')

print('total training polyps images:', len(os.listdir(train_polyps)))

from tensorflow import keras
import tensorflow as tf

image_size = 299 # All images will be resized to 160x160
batch_size = int(len(os.listdir(train_polyps))*8*10/100)

# Rescale all images by 1./255 and apply image augmentation
train_datagen = keras.preprocessing.image.ImageDataGenerator(
                rescale=1./255)

validation_datagen = keras.preprocessing.image.ImageDataGenerator(rescale=1./255)

# Flow training images in batches of 20 using train_datagen generator
train_generator = train_datagen.flow_from_directory(
                train_dir,  # Source directory for the training images
                target_size=(image_size, image_size),
                batch_size=batch_size,
                # Since we use binary_crossentropy loss, we need binary labels
                class_mode='categorical')

# Flow validation images in batches of 20 using test_datagen generator
validation_generator = validation_datagen.flow_from_directory(
                validation_dir, # Source directory for the validation images
                target_size=(image_size, image_size),
                batch_size=batch_size,
                class_mode='categorical')

try:
  device_name = os.environ['COLAB_TPU_ADDR']
  TPU_ADDRESS = 'grpc://'+device_name
  print('Found TPU at : {}'.format(TPU_ADDRESS))
except:
  print('TPU not found')

IMG_SHAPE = (image_size, image_size,3)

base_model = tf.keras.applications.InceptionV3(input_shape=IMG_SHAPE,
                                               include_top=False,
                                               weights='imagenet')

base_model.trainable = False

base_model.summary()

def create_model():
  model = tf.keras.Sequential([
      base_model,
      keras.layers.GlobalAveragePooling2D(),
      keras.layers.Dense(8),
      keras.layers.Activation('softmax')
  ])
  return model

def create_model():
  model = tf.keras.Sequential()
  model.add(base_model)
  model.add(tf.keras.layers.GlobalAveragePooling2D)
  model.add(tf.keras.layers.Dense(8))
  model.add(tf.keras.layers.Activation('softmax'))
  return model

print(tf.__version__)

resolver = tf.contrib.cluster_resolver.TPUClusterResolver('grpc://' + os.environ['COLAB_TPU_ADDR'])
tf.contrib.distribute.initialize_tpu_system(resolver)
strategy = tf.contrib.distribute.TPUStrategy(resolver)

with strategy.scope():
  model = create_model()
  model.compile(
      optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3, ),
      loss='sparse_categorical_crossentropy',
      metrics=['sparse_categorical_accuracy'])

#tpu_model = tf.contrib.tpu.keras_to_tpu_model(model,strategy=tf.contrib.tpu.TPUDistributionStrategy(tf.contrib.cluster_resolver.TPUClusterResolver(TPU_ADDRESS)))

model.summary()

len(tpu_model.trainable_variables)

epochs = 10
steps_per_epoch = train_generator.n
validation_steps = validation_generator.n

history = tpu_model.fit_generator(train_generator,
                             steps_per_epoch = steps_per_epoch,
                             epochs = epochs,
                             workers = 4,
                             validation_data = validation_generator,
                             validation_steps = validation_steps)

import matplotlib.pyplot as plt
import matpllotlb.image as mpimg

acc = history.history['acc']
val_acc = history.history['val_acc']

loss = history.history['loss']
val_loss = history.history['val_loss']

plt.figure(figsize=(8, 8))
plt.subplot(2, 1, 1)
plt.plot(acc, label='Training Accuracy')
plt.plot(val_acc, label='Validation Accuracy')
plt.legend(loc='lower right')
plt.ylabel('Accuracy')
plt.ylim([min(plt.ylim()),1])
plt.title('Training and Validation Accuracy')

plt.subplot(2, 1, 2)
plt.plot(loss, label='Training Loss')
plt.plot(val_loss, label='Validation Loss')
plt.legend(loc='upper right')
plt.ylabel('Cross Entropy')
plt.ylim([0,max(plt.ylim())])
plt.title('Training and Validation Loss')
plt.show()

base_model.trainable = True

print(len(base_model.layers))
fine_tune_at = int(len(base_model.layers)*90/100)
for layer in base_model.layers[:fine_tune_at]:
  layer.trainable = False

tpu_model.compile(optimizer=tf.keras.optimizers.RMSprop(lr=0.0001),
             loss='mean_squared_error',
             metrics=['accuracy'])

tpu_model.summary()

len(tpu_model.trainable_variable)

history_fine = tpu_model.fit_generator(train_generator,
                             steps_per_epoch = steps_per_epoch,
                             epochs = epochs,
                             workers = 4,
                             validation_data = validation_generator,
                             validation_steps = validation_steps)

acc += history_fine.history['acc']
val_acc += history_fine.history['val_acc']

loss += history_fine.history['loss']
val_loss += history_fine.history['val_loss']

plt.figure(figsize=(8, 8))
plt.subplot(2, 1, 1)
plt.plot(acc, label='Training Accuracy')
plt.plot(val_acc, label='Validation Accuracy')
plt.ylim([0.9, 1])
plt.plot([epochs-1,epochs-1], plt.ylim(), label='Start Fine Tuning')
plt.legend(loc='lower right')
plt.title('Training and Validation Accuracy')

plt.subplot(2, 1, 2)
plt.plot(loss, label='Training Loss')
plt.plot(val_loss, label='Validation Loss')
plt.ylim([0, 0.2])
plt.plot([epochs-1,epochs-1], plt.ylim(), label='Start Fine Tuning')
plt.legend(loc='upper right')
plt.title('Training and Validation Loss')
plt.show()

`

> W0915 05:54:59.943130 140003169343360 lazy_loader.py:50] 
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.


AssertionErrorTraceback (most recent call last)
<ipython-input-14-6528c01a76a4> in <module>()
      4 
      5 with strategy.scope():
----> 6   model = create_model()
      7   model.compile(
      8       optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3, ),

14 frames
<ipython-input-12-42aec310836f> in create_model()
      1 def create_model():
      2   model = tf.keras.Sequential()
----> 3   model.add(base_model)
      4   model.add(tf.keras.layers.GlobalAveragePooling2D)
      5   model.add(tf.keras.layers.Dense(8))

/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/tracking/base.pyc in _method_wrapper(self, *args, **kwargs)
    455     self._self_setattr_tracking = False  # pylint: disable=protected-access
    456     try:
--> 457       result = method(self, *args, **kwargs)
    458     finally:
    459       self._self_setattr_tracking = previous_value  # pylint: disable=protected-access

/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/sequential.pyc in add(self, layer)
    172           # and create the node connecting the current layer
    173           # to the input layer we just created.
--> 174           layer(x)
    175           set_inputs = True
    176 

/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/base_layer.pyc in __call__(self, inputs, *args, **kwargs)
    632                     outputs = base_layer_utils.mark_as_return(outputs, acd)
    633                 else:
--> 634                   outputs = call_fn(inputs, *args, **kwargs)
    635 
    636             except TypeError as e:

/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/network.pyc in call(self, inputs, training, mask)
    749                                 ' implement a `call` method.')
    750 
--> 751     return self._run_internal_graph(inputs, training=training, mask=mask)
    752 
    753   def compute_output_shape(self, input_shape):

/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/network.pyc in _run_internal_graph(self, inputs, training, mask)
    891 
    892           # Compute outputs.
--> 893           output_tensors = layer(computed_tensors, **kwargs)
    894 
    895           # Update tensor_dict.

/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/base_layer.pyc in __call__(self, inputs, *args, **kwargs)
    632                     outputs = base_layer_utils.mark_as_return(outputs, acd)
    633                 else:
--> 634                   outputs = call_fn(inputs, *args, **kwargs)
    635 
    636             except TypeError as e:

/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/layers/normalization.pyc in call(self, inputs, training)
    649 
    650     if self.fused:
--> 651       outputs = self._fused_batch_norm(inputs, training=training)
    652       if self.virtual_batch_size is not None:
    653         # Currently never reaches here since fused_batch_norm does not support

/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/layers/normalization.pyc in _fused_batch_norm(self, inputs, training)
    531                                              momentum, inputs_size)
    532 
--> 533       self.add_update(mean_update, inputs=True)
    534       self.add_update(variance_update, inputs=True)
    535 

/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/base_layer.pyc in add_update(self, updates, inputs)
   1080       return update
   1081 
-> 1082     updates = [process_update(x) for x in updates]
   1083     # Non-callable Updates are run automatically inside `call` in V2, so
   1084     # they do not need to be tracked later.

/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/base_layer.pyc in process_update(x)
   1068           # In V1 mode, call the callable right away and process. This is needed
   1069           # for TPU strategy.
-> 1070           return update()
   1071       elif isinstance(x, ops.Operation):
   1072         update = x

/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/base_layer.pyc in <lambda>()
   1064       """
   1065       if callable(x):
-> 1066         update = lambda: process_update(x())
   1067         if not ops.executing_eagerly_outside_functions():
   1068           # In V1 mode, call the callable right away and process. This is needed

/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/layers/normalization.pyc in mean_update()
    515           return strategy.extended.update(self.moving_mean,
    516                                           self._assign_moving_average,
--> 517                                           (mean, self.momentum, inputs_size))
    518 
    519         def variance_update():

/usr/local/lib/python2.7/dist-packages/tensorflow/python/distribute/distribute_lib.pyc in update(self, var, fn, args, kwargs, group)
   1301       kwargs = {}
   1302     with self._container_strategy().scope():
-> 1303       return self._update(var, fn, args, kwargs, group)
   1304 
   1305   def _update(self, var, fn, args, kwargs, group):

/usr/local/lib/python2.7/dist-packages/tensorflow/python/distribute/tpu_strategy.pyc in _update(self, var, fn, args, kwargs, group)
    543 
    544   def _update(self, var, fn, args, kwargs, group):
--> 545     assert isinstance(var, values.TPUMirroredVariable)
    546     if values._enclosing_tpu_context() is not None:  # pylint: disable=protected-access
    547       if group:

AssertionError:

**Comment by ParikhKadam** [comment]
Shift to tf.keras as Keras will no longer be maintained after the next release.
