### ISSUE TITLE
Documentation Required on loading pretrained models

### ISSUE THREAD

**Issue by harsh2ai** [keras-team/keras#12505]
Please make sure that the boxes below are checked before you submit your issue.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.

Thank you!

- [. ] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps`

- [ .] Check that your version of TensorFlow is up-to-date. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

I believe there should be a documentation on
https://keras.io
for letting beginners understand Transfer learning, I spent an entire day figuring out how to do this and i guess many people may have spend months doing this. This stuff reduces time to train and make predictions 

The documentation at 
https://keras.io/applications/
is not much clear and needs to be improved for instance there should be and indication upon what needs to be feeded in certain parts of the program and how can one use it using his or her own datasets

**Comment by mathemage** [comment]
Hi!

@hr21  @jvishnuvardhan Is this PR still open? I'd love to join the Keras and contribute but I have hard times to orient myself in [Good first issues page](https://github.com/keras-team/keras/contribute).

I can start with this PR on docs/ if it's still relevant. Please let me know in both cases so that I can start working on it. Thanks!
