### ISSUE TITLE
How to handle grayscale images when using transfer learning with VGG16?

### ISSUE THREAD

**Issue by Mahi-Mai** [keras-team/keras#12520]
Hello, Keras team!

I've been using VGG16 for transfer learning, but I'm using grayscale images.  

```model = VGG16(weights = "imagenet", include_top=False, input_shape = (img_width, img_height, 3))```

As far as I know, VGG16 only accepts 3 channels for input shape.  If I define my base model as accepting 3 channel images like above and don't define the colormode in ImageDataGenerater.flow_from_directory()- which defaults to RGB- the code runs and I appear to get good results.

But my input images are grayscale.  Could someone explain what Keras is doing in the background in this situation?

**Comment by harshitAgr** [comment]
Keras converts grayscale images to 3 channel (RGB images) using PIL. If you specify color_mode ='grayscale', then it will load grayscale image without conversion.

**Comment by Mahi-Mai** [comment]
Okay, thanks!

**Comment by SasikiranJ** [comment]
How it will convert one channel grayscale image to 3 channel . will it duplicate values to extra two channels?

**Comment by omerferhatt** [comment]
When you use 3 channel for grayscale, it will create dummy variable for cnn

**Comment by SasikiranJ** [comment]
I have given grayscale image to imageDataGenerator function with color_mode
RGB..... Is this sufficient?
