### ISSUE TITLE
Add dilation_rate parameter to DepthwiseConv2D

### ISSUE THREAD

**Issue by bonlime** [keras-team/keras#12525]
This issue is identical to the https://github.com/keras-team/keras/issues/9642. 

The documentation doesn't include dilation_rate for depthwise convolutions because it was not included as one of the keyword arguments. Instead dilation_rate is passed to _Conv() through **kwargs. Need to add dilation_rate explicitly to the keyword arguments. 
The fix should be pretty straightforward, like https://github.com/keras-team/keras/pull/9844. 

- [+ ] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps`

- [+ ] Check that your version of TensorFlow is up-to-date. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [SKIP ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by ymodak** [comment]
Closing this issue since the PR has been merged. Thanks!
