### ISSUE TITLE
ValueError: Graph disconnected: cannot obtain value for tensor Tensor("input_2:0", shape=(?, 224, 224, 3), dtype=float32) at layer "input_2". The following previous layers were accessed without issue: ['input_1']

### ISSUE THREAD

**Issue by csitaula** [keras-team/keras#12532]
# -*- coding: utf-8 -*-
'''VGG16-places365 model for Keras

# Reference:
- [Places: A 10 million Image Database for Scene Recognition](http://places2.csail.mit.edu/PAMI_places.pdf)
'''

from __future__ import division, print_function
import os

import warnings
import numpy as np
import tensorflow
import keras
from keras import backend as K
from keras.layers import Input
from keras.layers.core import Activation, Dense, Flatten
from keras.layers.pooling import MaxPooling2D
from keras.models import Model
from keras.layers import Conv2D
from keras.regularizers import l2
from keras.layers.core import Dropout
from keras.layers import GlobalAveragePooling2D
from keras.layers import GlobalMaxPooling2D
from Custom_preprocessing import *
# import keras.applications.imagenet_utils
# from preprocess.py import _obtain_input_shape
from keras.engine.topology import get_source_inputs
from keras.utils.data_utils import get_file
from keras.utils import layer_utils
from keras.preprocessing import image
from keras.applications.imagenet_utils import preprocess_input

WEIGHTS_PATH = 'https://github.com/GKalliatakis/Keras-VGG16-places365/releases/download/v1.0/vgg16-places365_weights_tf_dim_ordering_tf_kernels.h5'
WEIGHTS_PATH_NO_TOP = 'https://github.com/GKalliatakis/Keras-VGG16-places365/releases/download/v1.0/vgg16-places365_weights_tf_dim_ordering_tf_kernels_notop.h5'

def VGG16_Places365(include_top=True, weights='places',
                    input_tensor=None, input_shape=None,
                    pooling=None,
                    classes=365):
    """Instantiates the VGG16-places365 architecture.

    Optionally loads weights pre-trained
    on Places. Note that when using TensorFlow,
    for best performance you should set
    `image_data_format="channels_last"` in your Keras config
    at ~/.keras/keras.json.

    The model and the weights are compatible with both
    TensorFlow and Theano. The data format
    convention used by the model is the one
    specified in your Keras config file.

    # Arguments
        include_top: whether to include the 3 fully-connected
            layers at the top of the network.
        weights: one of `None` (random initialization),
                 'places' (pre-training on Places),
                 or the path to the weights file to be loaded.
        input_tensor: optional Keras tensor (i.e. output of `layers.Input()`)
            to use as image input for the model.
        input_shape: optional shape tuple, only to be specified
            if `include_top` is False (otherwise the input shape
            has to be `(224, 224, 3)` (with `channels_last` data format)
            or `(3, 224, 244)` (with `channels_first` data format).
            It should have exactly 3 inputs channels,
            and width and height should be no smaller than 48.
            E.g. `(200, 200, 3)` would be one valid value.
        pooling: Optional pooling mode for feature extraction
            when `include_top` is `False`.
            - `None` means that the output of the model will be
                the 4D tensor output of the
                last convolutional layer.
            - `avg` means that global average pooling
                will be applied to the output of the
                last convolutional layer, and thus
                the output of the model will be a 2D tensor.
            - `max` means that global max pooling will
                be applied.
        classes: optional number of classes to classify images
            into, only to be specified if `include_top` is True, and
            if no `weights` argument is specified.
    # Returns
        A Keras model instance.
    # Raises
        ValueError: in case of invalid argument for `weights`, or invalid input shape
        """
    if not (weights in {'places', None} or os.path.exists(weights)):
        raise ValueError('The `weights` argument should be either '
                         '`None` (random initialization), `places` '
                         '(pre-training on Places), '
                         'or the path to the weights file to be loaded.')

    if weights == 'places' and include_top and classes != 365:
        raise ValueError('If using `weights` as places with `include_top`'
                         ' as true, `classes` should be 365')

    # Determine proper input shape
    p = Custom_preprocessing
    # inpt_shape=p.
    input_shape = p._obtain_input_shape(input_shape,
                                        default_size=224,
                                        min_size=48,
                                        data_format=K.image_data_format(),
                                        require_flatten=include_top)

    if input_tensor is None:
        img_input = Input(shape=input_shape)
    else:
        if not K.is_keras_tensor(input_tensor):
            img_input = Input(tensor=input_tensor, shape=input_shape)
        else:
            img_input = input_tensor

    # Block 1
    x = Conv2D(filters=64, kernel_size=3, strides=(1, 1), padding='same',
               kernel_regularizer=l2(0.0002),
               activation='relu', name='block1_conv1')(img_input)

    x = Conv2D(filters=64, kernel_size=3, strides=(1, 1), padding='same',
               kernel_regularizer=l2(0.0002),
               activation='relu', name='block1_conv2')(x)

    x = MaxPooling2D(pool_size=(2, 2), strides=(2, 2), name="block1_pool", padding='valid')(x)

    # Block 2
    x = Conv2D(filters=128, kernel_size=3, strides=(1, 1), padding='same',
               kernel_regularizer=l2(0.0002),
               activation='relu', name='block2_conv1')(x)

    x = Conv2D(filters=128, kernel_size=3, strides=(1, 1), padding='same',
               kernel_regularizer=l2(0.0002),
               activation='relu', name='block2_conv2')(x)

    x = MaxPooling2D(pool_size=(2, 2), strides=(2, 2), name="block2_pool", padding='valid')(x)

    # Block 3
    x = Conv2D(filters=256, kernel_size=3, strides=(1, 1), padding='same',
               kernel_regularizer=l2(0.0002),
               activation='relu', name='block3_conv1')(x)

    x = Conv2D(filters=256, kernel_size=3, strides=(1, 1), padding='same',
               kernel_regularizer=l2(0.0002),
               activation='relu', name='block3_conv2')(x)

    x = Conv2D(filters=256, kernel_size=3, strides=(1, 1), padding='same',
               kernel_regularizer=l2(0.0002),
               activation='relu', name='block3_conv3')(x)

    x = MaxPooling2D(pool_size=(2, 2), strides=(2, 2), name="block3_pool", padding='valid')(x)

    # Block 4
    x = Conv2D(filters=512, kernel_size=3, strides=(1, 1), padding='same',
               kernel_regularizer=l2(0.0002),
               activation='relu', name='block4_conv1')(x)

    x = Conv2D(filters=512, kernel_size=3, strides=(1, 1), padding='same',
               kernel_regularizer=l2(0.0002),
               activation='relu', name='block4_conv2')(x)

    x = Conv2D(filters=512, kernel_size=3, strides=(1, 1), padding='same',
               kernel_regularizer=l2(0.0002),
               activation='relu', name='block4_conv3')(x)

    x = MaxPooling2D(pool_size=(2, 2), strides=(2, 2), name="block4_pool", padding='valid')(x)

    # Block 5
    x = Conv2D(filters=512, kernel_size=3, strides=(1, 1), padding='same',
               kernel_regularizer=l2(0.0002),
               activation='relu', name='block5_conv1')(x)

    x = Conv2D(filters=512, kernel_size=3, strides=(1, 1), padding='same',
               kernel_regularizer=l2(0.0002),
               activation='relu', name='block5_conv2')(x)

    x = Conv2D(filters=512, kernel_size=3, strides=(1, 1), padding='same',
               kernel_regularizer=l2(0.0002),
               activation='relu', name='block5_conv3')(x)

    x = MaxPooling2D(pool_size=(2, 2), strides=(2, 2), name="block5_pool", padding='valid')(x)

    if include_top:
        # Classification block
        x = Flatten(name='flatten')(x)
        x = Dense(4096, activation='relu', name='fc1')(x)
        x = Dropout(0.5, name='drop_fc1')(x)

        x = Dense(4096, activation='relu', name='fc2')(x)
        x = Dropout(0.5, name='drop_fc2')(x)

        x = Dense(365, activation='softmax', name="predictions")(x)

    else:
        if pooling == 'avg':
            x = GlobalAveragePooling2D()(x)
        elif pooling == 'max':
            x = GlobalMaxPooling2D()(x)

    # Ensure that the model takes into account
    # any potential predecessors of `input_tensor`.
    if input_tensor is not None:
        inputs = get_source_inputs(input_tensor)
    else:
        inputs = img_input

    # Create model.
    model = Model(inputs, x, name='vgg16-places365')

    # load weights
    if weights == 'places':
        if include_top:
            weights_path = get_file('vgg16-places365_weights_tf_dim_ordering_tf_kernels.h5',
                                    WEIGHTS_PATH,
                                    cache_subdir='models')
        else:
            weights_path = get_file('vgg16-places365_weights_tf_dim_ordering_tf_kernels_notop.h5',
                                    WEIGHTS_PATH_NO_TOP,
                                    cache_subdir='models')

        model.load_weights(weights_path)

        if K.backend() == 'theano':
            layer_utils.convert_all_kernels_in_model(model)

        if K.image_data_format() == 'channels_first':
            if include_top:
                maxpool = model.get_layer(name='block5_pool')
                shape = maxpool.output_shape[1:]
                dense = model.get_layer(name='fc1')
                layer_utils.convert_dense_weights_data_format(dense, shape, 'channels_first')

            if K.backend() == 'tensorflow':
                warnings.warn('You are using the TensorFlow backend, yet you '
                              'are using the Theano '
                              'image data format convention '
                              '(`image_data_format="channels_first"`). '
                              'For best performance, set '
                              '`image_data_format="channels_last"` in '
                              'your Keras config '
                              'at ~/.keras/keras.json.')

    elif weights is not None:
        model.load_weights(weights)

    return model

if __name__ == '__main__':
    # import urllib3
    import numpy as np
    # import gc
    # from bs4 import BeautifulSoup
    from PIL import Image
    # from petl import StringIO
    from cv2 import resize
    from keras import models
    from keras import layers
    from keras.layers import BatchNormalization, GlobalAvgPool2D
    from keras import optimizers
    from keras.preprocessing.image import ImageDataGenerator
    import matplotlib.pyplot as plt
    from keras.models import load_model

    # lr_decay = ReduceLROnPlateau(factor=0.9, patience=1, verbose=1)
    # checkpointer = ModelCheckpoint(filepath=WEIGHTS_CLASSIFIER, save_best_only=True, verbose=1)

    # TEST_IMAGE_URL = 'http://places2.csail.mit.edu/imgs/demo/6.jpg'
    # image = Image.open(urllib2.urlopen(TEST_IMAGE_URL))
    # http = urllib3.PoolManager()
    # response = http.request('GET', TEST_IMAGE_URL)
    # soup = BeautifulSoup(response.data,"lxml")
    # i=0
    vgg_conv = keras.applications.VGG16(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
    for layer in vgg_conv.layers[:]:
        layer.trainable = False

    # for layer in vgg_conv.layers[:-4]:
    # layer.trainable=False
    # check the trainable status of the individual layers
    for layer in vgg_conv.layers:
        print(layer, layer.trainable)
    # create the models
    # model=models.Sequential()
    # #add the vgg convolutional base model
    # model.add(vgg_conv)
    # Add new layers
    ##extract pooling layers with batch normalization
    # pool1 = vgg_conv.get_layer('block1_pool').output
    # pool1 = GlobalAveragePooling2D()(pool1)
    # pool1 = BatchNormalization()(pool1)
    # pool2 = vgg_conv.get_layer('block2_pool').output
    # pool2 = GlobalAveragePooling2D()(pool2)
    # pool2 = BatchNormalization()(pool2)
    # pool3 = vgg_conv.get_layer('block3_pool').output
    # pool3 = GlobalAveragePooling2D()(pool3)
    # pool3 = BatchNormalization()(pool3)
    # pool4 = vgg_conv.get_layer('block4_pool').output
    # pool4 = GlobalAveragePooling2D()(pool4)
    # pool4 = BatchNormalization()(pool4)
    pool5 = vgg_conv.get_layer('block5_pool').output
    pool5 = GlobalAveragePooling2D()(pool5)
    pool5 = BatchNormalization()(pool5)
    # layers=layers.concatenate(pool1,pool2,pool3,pool4,pool5)

    # x = merge([pool1, pool2, pool3, pool5],
    #           mode='concat', concat_axis=channel_axis,
    #           name='mixed' + str(9 + i))
    vgg_conv_places = VGG16_Places365(weights='places', include_top=False, input_shape=(224, 224, 3))

    for layer in vgg_conv_places.layers[:]:
        layer.trainable = False

    # for layer in vgg_conv_places.layers[:-4]:
    # layer.trainable=False
    # check the trainable status of the individual layers
    for layer in vgg_conv_places.layers:
        print(layer, layer.trainable)

    pool_5 = vgg_conv_places.get_layer('block5_pool').output
    pool_5 = GlobalAveragePooling2D()(pool_5)
    pool_5 = BatchNormalization()(pool_5)

    pool5 = vgg_conv.get_layer('block5_pool').output
    pool5 = GlobalAveragePooling2D()(pool5)
    pool5 = BatchNormalization()(pool5)
    x = keras.layers.concatenate([pool5,pool_5], axis=1)
    #x=BatchNormalization()(x)
    # print(x.shape)
    # Fully Connected Softmax Layer
    x_fc = Dropout(0.5)(x)
    x_fc = Dense(512, activation='relu')(x_fc)
    # x_fc = Flatten(name='flatten')(x_fc)
    x_fc = Dense(67, activation='softmax', name='predictions')(x_fc)

    # Show a summary of the model
    img_input = vgg_conv.input
    model = Model(img_input, x_fc)
    # model.load_weights('C:/Users/Chiru/.keras/models/vgg16-places365_weights_tf_dim_ordering_tf_kernels_notop.h5')

    model.summary()

    train_datagen = ImageDataGenerator(
        rescale=1. / 255,
        rotation_range=20,
        width_shift_range=0.2,
        height_shift_range=0.2,
        horizontal_flip=True,
        featurewise_center=True,
        featurewise_std_normalization=True,
        fill_mode='nearest')

    validation_datagen = ImageDataGenerator(rescale=1. / 255,featurewise_center=True,featurewise_std_normalization=True)

    # Change the batchsize according to your system RAM
    train_batchsize = 40
    val_batchsize = 10

    train_generator = train_datagen.flow_from_directory(
        'C:/Experiment/vggimagenet-finetune/data/indoor/train',
        target_size=(224, 224),
        batch_size=train_batchsize,
        class_mode='categorical')

    validation_generator = validation_datagen.flow_from_directory(
        'C:/Experiment/vggimagenet-finetune/data/indoor/val',
        target_size=(224, 224),
        batch_size=val_batchsize,
        class_mode='categorical',
        shuffle=False)

    # Compile the model
    model.compile(loss='categorical_crossentropy',
                  optimizer=optimizers.RMSprop(lr=1e-4),
                  metrics=['acc'])
    # Train the model
    history = model.fit_generator(
        train_generator,
        steps_per_epoch=100,
        epochs=50,
        validation_data=validation_generator,
        validation_steps=validation_generator.samples / validation_generator.batch_size,
        verbose=1)

    # Save the model
    model.save('small_last4.h5')
    # accuracy details
    acc = history.history['acc']
    val_acc = history.history['val_acc']
    loss = history.history['loss']
    val_loss = history.history['val_loss']

    epochs = range(len(acc))

    plt.plot(epochs, acc, 'b', label='Training acc')
    plt.plot(epochs, val_acc, 'r', label='Validation acc')
    plt.title('Training and validation accuracy')
    plt.legend()

    plt.figure()

    plt.plot(epochs, loss, 'b', label='Training loss')
    plt.plot(epochs, val_loss, 'r', label='Validation loss')
    plt.title('Training and validation loss')
    plt.legend()

    plt.show()

**Comment by RishikMani** [comment]
Looks like you have multiple inputs into your model, but in the final step when you render your model by joining all the blocks you are not providing all the required inputs. **E.g. my model has RNN block with input input_1 and a CNN block with input input_2.**

So the final model of mine would look like:
```python
model = Model(inputs=[rnn_model.input, cnn_model.input], outputs=z)
```

In  your code:
```python
if input_tensor is not None:
    inputs = get_source_inputs(input_tensor)
else:
    inputs = img_input

model = Model(inputs, x, name='vgg16-places365')
```
are you sure you have provided all the inputs here.

**Comment by martinpius** [comment]
f
