### ISSUE TITLE
Can't get PELU or SineReLu to work

### ISSUE THREAD

**Issue by GadL** [keras-team/keras#12565]
When I try to replace LeakyRELU or relu in a working coding with either SineRELU or PELU I. A variety of places, I keep getting this error:

ValueError: Unknown activation function:PELU

**Comment by RaphaelMeudec** [comment]
@GadL Hello, could you provide a minimal sample script to generate the error?

**Comment by GadL** [comment]
This code is very simplified from actual model, but has same error so hopefully solution here works elsewhere. (text file is python script)


[simpleError.txt](https://github.com/keras-team/keras/files/3023723/simpleError.txt)

data can be found: https://machinelearningmastery.com/tutorial-first-neural-network-python-keras/
