### ISSUE TITLE
"steps_per_epoch=NONE" is only valid for generator based on the "keras.utils.Sequence" class.

### ISSUE THREAD

**Issue by nauman9** [keras-team/keras#12577]
I am getting this error while using fit_generator. kindly help me to solve this.

**Here is my code screen shot.**

![2](https://user-images.githubusercontent.com/49028721/55231273-ee8cc480-5243-11e9-9c39-b3bb7634e1ab.PNG)

![1](https://user-images.githubusercontent.com/49028721/55231213-c309da00-5243-11e9-8b6d-51443431674d.PNG)

**Comment by Nisnab** [comment]
.
