### ISSUE TITLE
Downside allow_growth

### ISSUE THREAD

**Issue by ThomHordijk** [keras-team/keras#12595]
I don't have so much an issue as i have a question, so if this is not the proper place for it my apologies.
I am working with tensorflow 1.13.1 keras 2.1.2 ROS kinetic Ubuntu 16.04, using an RTX 2080 TI.
For a project i am working on i had to include the allow_growth statement for the model to accept its input data. I had to add the line in the tensorflow_backend.py script because I could not get it working with the statement anywhere else. The only references that i have been able to find al simply state that you should use it when to solve a memory problem. The question that i have is in regard to possible downsides to using this statement? Are there any?

**Comment by ymodak** [comment]
allow_growth is safest option to avoid resource exhaustion when not sure if input data.
However, This issue isn't related to a bug/enhancement/feature request or other accepted types of issue.
To ask questions, please see the following resources :
[StackOverflow](http://stackoverflow.com/questions/tagged/keras)
[Keras Slack channel](https://keras-slack-autojoin.herokuapp.com)
[Keras.io support](https://keras.io/#support)
[Gitter](https://gitter.im/Keras-io/Lobby)
Thanks!
