### ISSUE TITLE
ValueError: ('Error when checking model input: expected no data, but got:', 

### ISSUE THREAD

**Issue by kelly329** [keras-team/keras#12593]
The [keras.applications](https://github.com/keras-team/keras-applications) module has been splitted from the main Keras repository.

Please submit your issue using this [link](https://github.com/keras-team/keras-applications/issues/new).

Thank you!

**Comment by kelly329** [comment]
This my code:
width = 229
height = 229
input_tensor = Input((height, width, 3))
x = input_tensor
x = keras.applications.xception.preprocess_input(x)
base_model = keras.applications.xception.Xception(input_tensor=x, weights='imagenet', include_top=False)
        
model = Model(base_model.input, GlobalAveragePooling2D()(base_model.output))

gen = ImageDataGenerator()
train_generator = gen.flow_from_directory("train2", (229,229), shuffle=False, 
                                              batch_size=16)
test_generator = gen.flow_from_directory("test2", (229,229), shuffle=False, 
                                             batch_size=16, class_mode=None)
train = model.predict_generator(train_generator, train_generator.samples)
test = model.predict_generator(test_generator, test_generator.samples)
with h5py.File("data_%s.h5"%MODEL) as h:
    h.create_dataset("train", data=train)
    h.create_dataset("test", data=test)
    h.create_dataset("label", data=train_generator.classes)

the error:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-29-890b466ffcc0> in <module>()
     17                                              batch_size=16, class_mode=None)
     18 
---> 19 train = model.predict_generator(train_generator, train_generator.samples)
     20 test = model.predict_generator(test_generator, test_generator.samples)
     21 #     with h5py.File("gap_%s.h5"%MODEL.func_name) as h:

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/legacy/interfaces.py in wrapper(*args, **kwargs)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/training.py in predict_generator(self, generator, steps, max_queue_size, workers, use_multiprocessing, verbose)
   1520                     generator_output = None
   1521                     while enqueuer.is_running():
-> 1522                         if not enqueuer.queue.empty():
   1523                             generator_output = enqueuer.queue.get()
   1524                             break

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/training_generator.py in predict_generator(model, generator, steps, max_queue_size, workers, use_multiprocessing, verbose)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/training.py in predict_on_batch(self, x)
   1266             ins = x + [0.]
   1267         else:
-> 1268             ins = x
   1269         self._make_predict_function()
   1270         f = self.predict_function

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/training.py in _standardize_user_data(self, x, y, sample_weight, class_weight, check_array_lengths, batch_size)
    749     def _make_train_function(self):
    750         if not hasattr(self, 'train_function'):
--> 751             raise RuntimeError('You must compile your model before using it.')
    752         if self.train_function is None:
    753             if self.uses_learning_phase and not isinstance(K.learning_phase(), int):

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/training_utils.py in standardize_input_data(data, names, shapes, check_batch_axis, exception_prefix)

ValueError: ('Error when checking model input: expected no data, but got:', array([[[[255., 255., 255.],
         [255., 255., 255.],
         [255., 255., 255.],
         ...,
         [ 18.,  22.,  23.],
         [ 18.,  22.,  21.],
         [ 12.,  16.,  15.]],

Thanks!

**Comment by KarthikMgk** [comment]
Hi, I'm facing the same issue. While the input dimension work fine in custom built CNN, the problem arises when the inputs are convolved with resnets and inceptions. VGG didnt get initialised due to various known open issues

**Comment by EliasCai** [comment]
may be the weights was trained by the higher version, i have the same issue, but i figure it out by install the version from 2.1.6 to 2.2.4
