### ISSUE TITLE
AttributeError: module 'keras.backend' has no attribute 'slice'

### ISSUE THREAD

**Issue by jianwenl** [keras-team/keras#12599]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-31-a31d731b2b99> in <module>
----> 1 model= model_LSTM_CRF(max_len, n_words, n_tags)

<ipython-input-16-36f6017d456b> in model_LSTM_CRF(max_len, n_words, n_tags)
      7     model = TimeDistributed(Dense(50, activation="relu"))(model)  # a dense layer as suggested by neuralNer
      8     crf = CRF(n_tags)  # CRF layer
----> 9     out = crf(model)  # output
     10     model = Model(input, out)
     11     model.compile(optimizer="rmsprop", loss=crf.loss_function, metrics=[crf.accuracy])

~/anaconda3/envs/deepAI/lib/python3.6/site-packages/keras/engine/topology.py in __call__(self, inputs, **kwargs)
    594 
    595             # Actually call the layer, collecting output(s), mask(s), and shape(s).
--> 596             output = self.call(inputs, **kwargs)
    597             output_mask = self.compute_mask(inputs, previous_mask)
    598 

~/anaconda3/envs/deepAI/lib/python3.6/site-packages/keras_contrib/layers/crf.py in call(self, X, mask)
    290 
    291         if self.test_mode == 'viterbi':
--> 292             test_output = self.viterbi_decoding(X, mask)
    293         else:
    294             test_output = self.get_marginal_prob(X, mask)

~/anaconda3/envs/deepAI/lib/python3.6/site-packages/keras_contrib/layers/crf.py in viterbi_decoding(self, X, mask)
    562                 input_energy, mask, self.left_boundary, self.right_boundary)
    563 
--> 564         argmin_tables = self.recursion(input_energy, mask, return_logZ=False)
    565         argmin_tables = K.cast(argmin_tables, 'int32')
    566 

~/anaconda3/envs/deepAI/lib/python3.6/site-packages/keras_contrib/layers/crf.py in recursion(self, input_energy, mask, go_backwards, return_sequences, return_logZ, input_length)
    525                                                    constants=constants,
    526                                                    input_length=input_length,
--> 527                                                    unroll=self.unroll)
    528 
    529         if return_sequences:

~/anaconda3/envs/deepAI/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py in rnn(step_function, inputs, initial_states, go_backwards, mask, constants, unroll, input_length)
   2455 
   2456         time_steps = tf.shape(inputs)[0]
-> 2457         outputs, _ = step_function(inputs[0], initial_states + constants)
   2458         output_ta = tensor_array_ops.TensorArray(
   2459             dtype=outputs.dtype,

~/anaconda3/envs/deepAI/lib/python3.6/site-packages/keras_contrib/layers/crf.py in _step(input_energy_i, states)
    519 
    520         def _step(input_energy_i, states):
--> 521             return self.step(input_energy_i, states, return_logZ)
    522 
    523         target_val_last, target_val_seq, _ = K.rnn(_step, input_energy,

~/anaconda3/envs/deepAI/lib/python3.6/site-packages/keras_contrib/layers/crf.py in step(self, input_energy_t, states, return_logZ)
    461                 m = states[3][:, t:(t + 2)]
    462             else:
--> 463                 m = K.slice(states[3], [0, t], [-1, 2])
    464             input_energy_t = input_energy_t * K.expand_dims(m[:, 0])
    465             # (1, F, F)*(B, 1, 1) -> (B, F, F)

AttributeError: module 'keras.backend' has no attribute 'slice'

**Comment by TatianaShavrina** [comment]
@jianwenl how did you solve the issue? I have also faced it today

**Comment by jianwenl** [comment]
@TatianaShavrina Hi, it is about the version conflict of Keras and Keras_contrib. I suggest you update the Keras and Tensorflow.

**Comment by Walid-Ahmed** [comment]
@jianwenl Can you please tell me to which exact version I should update?
