### ISSUE TITLE
how to get a Cartesian product

### ISSUE THREAD

**Issue by saintthor** [keras-team/keras#12608]
Please make sure that the boxes below are checked before you submit your issue.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps`

- [x] Check that your version of TensorFlow is up-to-date. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by saintthor** [comment]
I need a keras layer to do such calculation:

def f( [a, b], [c, d] ):
     return [a*c, a*d, b*c, b*d]

what is the easiest way?

**Comment by paulbonnard** [comment]
use https://www.tensorflow.org/api_docs/python/tf/math/multiply

**Comment by kashyapraval** [comment]
> https://www.tensorflow.org/api_docs/python/tf/math/multiply

that would rather return [ac, bd].
matrix multiplication and extending rows there after should help.
 [a, b].T  X [c, d] that returns a matrix of shape(2,2)
X stands for matrix multiplication

**Comment by saintthor** [comment]
> > https://www.tensorflow.org/api_docs/python/tf/math/multiply
> 
> that would rather return [ac, bd].
> matrix multiplication and extending rows there after should help.
> [a, b].T X [c, d] that returns a matrix of shape(2,2)
> X stands for matrix multiplication

thanks. I use K.batch_dot( [[a], [b]], [c,d] ) to do this. is it the easiest way?
