### ISSUE TITLE
[API DESIGN REVIEW] Adding a hyperparameter input to the models

### ISSUE THREAD

**Issue by MikeShlis** [keras-team/keras#12657]
I propose creating a hyper-parameter input that allows users to control hyperparameters when running training or inference. Just adds a level of simplicity for people who do in-training augmentations and have other hps that they want the ability to change without either 
1) rebuilding the graph
2) creating a backend variable, and reassigning each time

an example snippet of how this would look (i implemented an outline of it already):
 
![image](https://user-images.githubusercontent.com/12632611/55992987-ec7f2880-5c7b-11e9-91ee-bbf1a366ac92.png)

**Comment by ziyigogogo** [comment]
Nope, data augmentations related more on data side, witch means that you should do augmentations in data generator/sequence or Tf.data. 
In other word, augmentation is not a good abstract for model object.

**Comment by MikeShlis** [comment]
@ziyigogogo data augmentation was only 1 example (which there exists multiple reasons to have in-loop DA vs doing it within a preprocessing step >> One of which is any implementation of EoT adversarial attacks https://arxiv.org/pdf/1707.07397.pdf). 
This could also extend past DA into other usages as well such as any model with hyper parameters that would be convenient to tune.

It wont be commonly used but it requires negligible overhead, does not mess with current functionality in any way, and provides certain users more control when they need it.
