### ISSUE TITLE
Fit_generator is NOT thread-safe

### ISSUE THREAD

**Issue by korosig** [keras-team/keras#12650]
Hi there!

I work with large datasets (user sequences in a MOOC course) and based on this I want to make a multiclass prediction (I want to predict users outcomes in MOOC course). I don't have enough memory, so I have to load every data user by user. Because of this, the batch size has to be 1, the steps_per_epoch same as the number of data (number of users), and I can't use multiprocessing.

During the testing I got the next error message: 
_RuntimeError: Your generator is NOT thread-safe.Keras requires a thread-safe generator when`use_multiprocessing=False, workers > 1`.For more information see issue #1638._

Here are some important parts from my code:
......
```
def _generator_(users,y):    
    while True:        
        for i in users: # go through every user
            df_o = np.array(pd.read_csv('data/user_Q21/_'+i+'.csv')) #load the user sequence from drive
            # create a  3D data for RNN(GRU) and add the label for training/prediction
            yield np.reshape(df_o, (1,df_o.shape[0], df_o.shape[1])),np.array(y.loc[y['user'] == i,['0','1','2','3','4','5','6']])     
    
## users - is the names of the users
## y - is the predicted value for multiclass classification
```

......
```
model = Sequential()
model.add(GRU(100, return_sequences=True,input_shape=(None,(features))))
model.add(Dropout(0.7))
model.add(GRU(100))
model.add(Dropout(0.7))     
model.add(Dense(100, activation='relu'))
model.add(Dense(n_outputs, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer=optim, metrics=['accuracy'])
......

training_generator = _generator_(tarin_user_names,train_labels)
validation_generator = _generator_(test_user_names,test_labels)  

model.fit_generator(training_generator,steps_per_epoch=1000, epochs=2,verbose = 1,
                        validation_data = validation_generator, validation_steps= 300,
                        max_queue_size=20,use_multiprocessing = False,workers=1)

model.evaluate_generator(validation_generator,steps=300, verbose=1)
```

Do you have any idea, how can be thread-safe my generator function?

Thanx

**Comment by Dref360** [comment]
Please use the keras.utils.Sequence API, it will be safe.

**Comment by jon-chuang** [comment]
@Dref360 This is false, I am encountering the error `"Your generator is NOT thread-safe."` even while utilising `Sequence`.

**Comment by sharkdeng** [comment]
I changed `from tensorflow.keras import *` to `from keras import *`. The problem solved. It seems tf 2.0 will throw this error if don't use keras Sequence.

**Comment by talhaanwarch** [comment]
> I changed `from tensorflow.keras import *` to `from keras import *`. The problem solved. It seems tf 2.0 will throw this error if don't use keras Sequence.

still facing

**Comment by talhaanwarch** [comment]
use_multiprocessing=True in fit_generator and model.predict_generator and false in model.evaluate_generator work for me

**Comment by Harsharma2308** [comment]
do u mean evaluate_generator , predict_generator and fit_generator functions in training_generator.py? I am confused by "model.predict_generator".

**Comment by don-tpanic** [comment]
> I changed `from tensorflow.keras import *` to `from keras import *`. The problem solved. It seems tf 2.0 will throw this error if don't use keras Sequence.

I can confirm tf<2.0 will also throw this error if don't use Sequence.
