### ISSUE TITLE
How to change final output shape of the model from NHWC to NCHW in keras

### ISSUE THREAD

**Issue by iamshri8** [keras-team/keras#12656]
Hello,

I am trying to implement YOLO in Windows ML. I have the following problems -
1. Windows ML format is NCHW whereas keras is NHWC for both output and input shape.

So , initially I took the yolo model from ONNX zoo and tried to generate bounding boxes values in Windows ML. 
I could successfully do it as yolo output shape from ONNX zoo is NCHW and could generate bounding box values in NCHW order.  ( as most of them have worked with NCHW order)

So, now I want to convert the Darknet YOLO models to ONNX , for which the intermediate framework is keras ( as searched every where on google) it is the yad2k script. So, in Keras as standard shape is NHWC. It is converted like this.
And I converted the keras model to ONNX using keras2onnx script.

Here, they have channels_first_input enabled as while converting to ONNX , the model converted to shape NCHW. But output shape is still the same NHWC. 

So, now it is difficult for me to handle this shape difference in Windows ML. So, could someone help me to change this output shape to NCHW in keras ?

**Comment by gentlezr** [comment]
For keras, the default backend is tensorflow and default data format is channels_last. If you want to change  data format you can modify the .keras/keras.json or use backend.set_image_data_format("channels_first") to change it's data format.
Is this helpful for you?

**Comment by iamshri8** [comment]
@gentlezr  Thanks for the reply.

It is just to load the model and and set the backend.set_image_data_format("channels_first") and again save the model is it? But I already have a model trained in Keras with tensorflow backend. Now I need to just change the output shape alone from NHWC to NCHW. Is that possible?

**Comment by gentlezr** [comment]
Oh sorry, I think I don't really understand you in the first comment. If your model can run correctly, you can get a NHWC array, maybe you can try np.swapaxes() or np.transpose() to change your model's results.

**Comment by iamshri8** [comment]
@gentlezr  Thanks for the reply. 

Here is my scenario. I have Yolo object detection pre trained model in Keras and Tensorflow. Now i need to convert it to onnx. After loading the model, i will pass it into the converter and then get my onnx model. **The converter will try to match the output shape of the keras model.** If i have it as NCHW in my pre trained model, then it will automatically be in NCHW format while conversion. But np.swapaxes() or np.transpose() could be used only if i want to do something with the loaded model in Keras and can't take that step attached along with the model while converting to ONNX model right?

**Comment by gentlezr** [comment]
> @gentlezr Thanks for the reply.
> Sorry I am a layman in onnx I hope you can solve your problem as sonn as possible.
