### ISSUE TITLE
Failed to import numpy_backend when building docs

### ISSUE THREAD

**Issue by KappaDistributive** [keras-team/keras#12677]
When attempting to build the docs with `KERAS_BACKEND=tensorflow python autogen.py`, I get the following error message:

> Using TensorFlow backend.
Traceback (most recent call last):
File "autogen.py", line 18, in <module> from keras.backend import numpy_backend
ImportError: cannot import name 'numpy_backend' from 'keras.backend' (/home/stefan/Documents/Programming/Python/keras/venv/lib/python3.7/site-packages/keras/backend/__init__.py)

Creating a new virtualenvironment and reinstalling the packages didn't solve the issue.

**System information** 
- TensorFlow backend: yes
- TensorFlow version: 1.13.1
- Keras version: 2.2.4
- Python version: 3.7.3

**Comment by spotiris** [comment]
The docs/README.md says to run `KERAS_BACKEND=tensorflow python autogen.py` from the `docs` dir, which produces this error.

If you instead run the script from the repo directory, the error mentioned does not appear, however another error appears: `Could not get the docstring from ~/src/keras/examples/class_activation_maps.py`.

I tried adding a module docstring for `class_activation_maps.py`, and viola it works!

Looking back at the version history for the README.md, it seems the directory to call the script from has not recently changed, and I am unsure how to fix it other than to change the calling directory.

Additionally... I can no longer recreate the original error after `git reset --hard` and `git clean -f`.
It could be one of the .gitignore files? Very confusing.

**Comment by BilalDendani** [comment]
Same problem for me when I tried to generate the offline documentation for my Keras. The following is the error 
(base) [bilal@bilal docs] $ KERAS_BACKEND=tensorflow python autogen.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "autogen.py", line 18, in <module>
    from keras.backend import numpy_backend
ImportError: cannot import name 'numpy_backend'

**Comment by Sumon-miazi** [comment]
first of all if you have multiple version of python then run the python that has keras installed.
for python2
`KERAS_BACKEND=tensorflow python autogen.py`

for python3
`KERAS_BACKEND=tensorflow python3 autogen.py`

`ImportError: cannot import name 'numpy_backend'`

this error happened cause there no file named **numpy_backend.py**.
 To solve this go to python **dist-packages** directory then **keras/backend** (in Linux  **cd /usr/local/lib/python3.5/dist-packages/keras/backend**) and make a file called numpy_backend.py

and copy the code in the numpy_backend.py from the link given below
[https://github.com/keras-team/keras/blob/master/keras/backend/numpy_backend.py]

run `mkdocs serve`

if you find any error like `No module named 'docs.structure'`.
then change import statement of the autogen.py from docs

from
```
from docs.structure import EXCLUDE
from docs.structure import PAGES
from docs.structure import template_np_implementation
from docs.structure import template_hidden_np_implementation
```

to 

```
from structure import EXCLUDE
from structure import PAGES
from structure import template_np_implementation
from structure import template_hidden_np_implementation
```

finaly build
`mkdocs build
`

**Comment by RonLek** [comment]
I'm still facing this issue while doing a fresh installation of keras and trying to build docs. Also the project structure @Sumon-miazi mentioned seems to have been changed and therefore the link taken off. 

Would be grateful for some help @KappaDistributive @fchollet
