### ISSUE TITLE
Feature Request: Accept None as target size for ImageDataGenerator

### ISSUE THREAD

**Issue by sun-yitao** [keras-team/keras#12679]
I came across this article: https://www.fast.ai/2018/04/30/dawnbench-fastai/#imagenet and I wanted to try implementing dynamic image sizes using ImageDataGenerator and keras applications models (those with global pooling layer). This is to allow the model to accept any input shape for progressively increasing input shape during training, as well as training a variety of image sizes without having to resize the input. However, there are a few problems I encountered.

First, keras.preprocessing.ImageDataGenerator does not accept None or (None, None) as target size. When target_size=(None, None):
```python
keras_preprocessing/image/iterator.py", line 218, in _get_batches_of_transformed_samples
    batch_x = np.zeros((len(index_array),) + self.image_shape, dtype=self.dtype)
TypeError: 'NoneType' object cannot be interpreted as an integer
```
When target_size=None:
```python
keras_preprocessing/image/iterator.py", line 169, in set_processing_attrs
    self.target_size = tuple(target_size)
TypeError: 'NoneType' object is not iterable
```

Also, while most keras applications models seem to accept (None, None, 3) as input shape, it doesn't seem to work with NASNet and ResNeXt. Here is the error when I get for ResNeXt for example:
```python
  File "keras/applications/__init__.py", line 28, in wrapper
    return base_fun(*args, **kwargs)
  File "keras/applications/resnext.py", line 19, in ResNeXt101
    return resnext.ResNeXt101(*args, **kwargs)
  File "keras_applications/resnet_common.py", line 575, in ResNeXt101
  File "keras_applications/resnet_common.py", line 373, in ResNet
  File "keras_applications/resnet_common.py", line 566, in stack_fn
  File "keras_applications/resnet_common.py", line 264, in stack3
  File "keras_applications/resnet_common.py", line 231, in block3
  File "kera/engine/base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "keras/layers/core.py", line 402, in call
    return K.reshape(inputs, (K.shape(inputs)[0],) + self.target_shape)
  File "keras/backend/tensorflow_backend.py", line 2167, in reshape
    return tf.reshape(x, shape)
  File "tensorflow/python/ops/gen_array_ops.py", line 7179, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "tensorflow/python/framework/op_def_library.py", line 529, in _apply_op_helper
    (input_name, err))
ValueError: Tried to convert 'shape' to a tensor and failed. Error: None values not supported.
```

Dynamic input shape may also break other models due to some implementation detail depending on input shape. For example, in a keras-contrib's implementation of ResNet, the stride value for Conv2D requires this calculation which will break if input shape is (None, None, 3)
```python
stride_width = int(round(input_shape[ROW_AXIS] / residual_shape[ROW_AXIS]))
 stride_height = int(round(input_shape[COL_AXIS] / residual_shape[COL_AXIS]))
```

It would really be great if ImageDataGenerator can support None type for target size for those fully convolutional networks and image models with global pooling which do not require a fixed input size.

Edit: I just realised that the problem is much more difficult than I initially thought since a numpy array representing a batch of images needs to have a fixed size

**Comment by Sole1Memory** [comment]
how to  get the number of epochs during training.

**Comment by sun-yitao** [comment]
@Sole1Memory ImageDataGenerator has a total_batches_seen attribute you could use by dividing that with the number of batches per epoch. You could also try using model.history.epoch. If you were using model.fit_generator you might have to use a callback:
```python
class EpochPrinter(keras.callbacks.Callback):
    def on_epoch_begin(self, epoch, logs=None):
        print(f'Epoch: {epoch}')

epoch_printer = EpochPrinter()
# fit_generator(callbacks=[epoch_printer...
```

I'm still trying to figure a way to make use of the epoch number to progressively increase image size during training. One possible way might be to loop the training manually:
```python
# train_gen = image_datagen.flow_from_directory...
for epoch in range(num_epochs):
    for batch in range(len(train_gen)):
        image_batch, y = train_gen.next()
        # do some manual image resizing
        # model.train_on_batch(resized_image_batch, y)
```

But it would be nice if it could be accomplished with a callback to model.fit_generator
