### ISSUE TITLE
ImportError: cannot import name 'get_backend' from 'matplotlib' 

### ISSUE THREAD

**Issue by dineshpalsingh** [keras-team/keras#12682]
ImportError                               Traceback (most recent call last)
<ipython-input-1-0484cd13f94d> in <module>()
----> 1 import matplotlib

/anaconda3/lib/python3.7/site-packages/matplotlib/__init__.py in <module>()
   1109 with warnings.catch_warnings():
   1110     warnings.simplefilter("ignore", MatplotlibDeprecationWarning)
-> 1111     rcParamsOrig = RcParams(rcParams.copy())
   1112     rcParamsDefault = RcParams([(key, default) for key, (default, converter) in
   1113                                 defaultParams.items()

/anaconda3/lib/python3.7/site-packages/matplotlib/__init__.py in __getitem__(self, key)
    889             val = dict.__getitem__(self, key)
    890             if val is rcsetup._auto_backend_sentinel:
--> 891                 from matplotlib import pyplot as plt
    892                 plt.switch_backend(rcsetup._auto_backend_sentinel)
    893 

/anaconda3/lib/python3.7/site-packages/matplotlib/pyplot.py in <module>()
     30 from cycler import cycler
     31 import matplotlib
---> 32 import matplotlib.colorbar
     33 import matplotlib.image
     34 from matplotlib import rcsetup, style

/anaconda3/lib/python3.7/site-packages/matplotlib/colorbar.py in <module>()
     38 import matplotlib.transforms as mtransforms
     39 import matplotlib._layoutbox as layoutbox
---> 40 import matplotlib._constrained_layout as constrained_layout
     41 from matplotlib import docstring
     42 

/anaconda3/lib/python3.7/site-packages/matplotlib/_constrained_layout.py in <module>()
     50 import warnings
     51 
---> 52 from matplotlib.legend import Legend
     53 import matplotlib.transforms as transforms
     54 import matplotlib._layoutbox as layoutbox

/anaconda3/lib/python3.7/site-packages/matplotlib/legend.py in <module>()
     41 from matplotlib.transforms import BboxTransformTo, BboxTransformFrom
     42 
---> 43 from matplotlib.offsetbox import HPacker, VPacker, TextArea, DrawingArea
     44 from matplotlib.offsetbox import DraggableOffsetBox
     45 

/anaconda3/lib/python3.7/site-packages/matplotlib/offsetbox.py in <module>()
     31 from matplotlib import docstring
     32 
---> 33 from matplotlib.image import BboxImage
     34 
     35 from matplotlib.patches import bbox_artist as mbbox_artist

/anaconda3/lib/python3.7/site-packages/matplotlib/image.py in <module>()
     17 import matplotlib.artist as martist
     18 from matplotlib.artist import allow_rasterization
---> 19 from matplotlib.backend_bases import FigureCanvasBase
     20 import matplotlib.colors as mcolors
     21 import matplotlib.cm as cm

/anaconda3/lib/python3.7/site-packages/matplotlib/backend_bases.py in <module>()
     44 import numpy as np
     45 
---> 46 from matplotlib import (
     47     backend_tools as tools, cbook, colors, textpath, tight_bbox, transforms,
     48     widgets, get_backend, is_interactive, rcParams)

ImportError: cannot import name 'get_backend' from 'matplotlib' (/anaconda3/lib/python3.7/site-packages/matplotlib/__init__.py)

**Comment by Dref360** [comment]
This is not a Keras issue.

**Comment by ymodak** [comment]
From the error stack, You have to install ```matplotlib``` module.
Closing this issue since it's not a Keras related bug or feature request. Thanks!
