### ISSUE TITLE
Allocator (GPU_0_bfc) ran out of memory

### ISSUE THREAD

**Issue by chengjianhong** [keras-team/keras#12693]
Hi,
I train my model use `multi_gpu_model(model,gpus=2)` with ParalleModelCheckpoint function. After a period of training, it happens some allocator  ran out of memory errors shown following details. I want to knows why it happens and how to avoid this.

```
class ParalleModelCheckpoint(ModelCheckpoint):
    def __init__(self,model,filepath, monitor='val_loss', verbose=0,
                 save_best_only=False, save_weights_only=False,
                 mode='auto', period=1):
        self.single_model = model
        super(ParalleModelCheckpoint,self).__init__(filepath, monitor,
verbose,save_best_only,save_weights_only,mode, period)
    def set_model(self, model):
        super(ParalleModelCheckpoint,self).set_model(self.single_model)
```

Errors：

> 45/114 [==========>...................] - ETA: 34:36 - loss: 0.2718 - acc: 0.0247 - dice_coefficient: 0.7282
>  46/114 [===========>..................] - ETA: 34:08 - loss: 0.2704 - acc: 0.0249 - dice_coefficient: 0.7296
>  47/114 [===========>..................] - ETA: 33:38 - loss: 0.2691 - acc: 0.0247 - dice_coefficient: 0.7309
>  48/114 [===========>..................] - ETA: 33:07 - loss: 0.2711 - acc: 0.0247 - dice_coefficient: 0.7289
>  49/114 [===========>..................] - ETA: 32:37 - loss: 0.2734 - acc: 0.0253 - dice_coefficient: 0.7266
>  50/114 [============>.................] - ETA: 32:07 - loss: 0.2735 - acc: 0.0250 - dice_coefficient: 0.7265
>  59/114 [==============>...............] - ETA: 27:38 - loss: 0.2790 - acc: 0.0251 - dice_coefficient: 0.7210
>  86/114 [=====================>........] - ETA: 14:04 - loss: 0.2747 - acc: 0.0252 - dice_coefficient: 0.7253
>  87/114 [=====================>........] - ETA: 13:34 - loss: 0.2747 - acc: 0.0252 - dice_coefficient: 0.7253
>  88/114 [======================>.......] - ETA: 13:04 - loss: 0.2754 - acc: 0.0250 - dice_coefficient: 0.7246
>  89/114 [======================>.......] - ETA: 12:34 - loss: 0.2754 - acc: 0.0255 - dice_coefficient: 0.7246
>  90/114 [======================>.......] - ETA: 12:04 - loss: 0.2744 - acc: 0.0253 - dice_coefficient: 0.7256
>  91/114 [======================>.......] - ETA: 11:34 - loss: 0.2734 - acc: 0.0257 - dice_coefficient: 0.72662019-04-17 23:05:41.799895: W tensorflow/core/common_runtime/bfc_allocator.cc:275] Allocator (GPU_0_bfc) ran out of memory trying to allocate 128.00MiB.  Current allocation summary follows.
> 2019-04-17 23:05:41.800808: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (256):   Total Chunks: 4704, Chunks in use: 4704. 1.15MiB allocated for chunks. 1.15MiB in use in bin. 309.7KiB client-requested in use in bin.
> 2019-04-17 23:05:41.800844: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (512):   Total Chunks: 300, Chunks in use: 300. 151.8KiB allocated for chunks. 151.8KiB in use in bin. 150.9KiB client-requested in use in bin.
> 2019-04-17 23:05:41.800867: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (1024):  Total Chunks: 387, Chunks in use: 387. 451.5KiB allocated for chunks. 451.5KiB in use in bin. 445.4KiB client-requested in use in bin.
> 2019-04-17 23:05:41.800888: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (2048):  Total Chunks: 4, Chunks in use: 4. 8.2KiB allocated for chunks. 8.2KiB in use in bin. 8.0KiB client-requested in use in bin.
> 2019-04-17 23:05:41.800907: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (4096):  Total Chunks: 261, Chunks in use: 261. 1.22MiB allocated for chunks. 1.22MiB in use in bin. 1.22MiB client-requested in use in bin.
> 2019-04-17 23:05:41.800930: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (8192):  Total Chunks: 23, Chunks in use: 23. 209.2KiB allocated for chunks. 209.2KiB in use in bin. 184.0KiB client-requested in use in bin.
> 2019-04-17 23:05:41.800949: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (16384):         Total Chunks: 241, Chunks in use: 241. 4.68MiB allocated for chunks. 4.68MiB in use in bin. 4.68MiB client-requested in use in bin.
> 2019-04-17 23:05:41.800969: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (32768):         Total Chunks: 54, Chunks in use: 54. 2.17MiB allocated for chunks. 2.17MiB in use in bin. 2.14MiB client-requested in use in bin.
> 2019-04-17 23:05:41.800990: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (65536):         Total Chunks: 175, Chunks in use: 175. 13.95MiB allocated for chunks. 13.95MiB in use in bin. 13.50MiB client-requested in use in bin.
> 2019-04-17 23:05:41.801012: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (131072):        Total Chunks: 76, Chunks in use: 76. 12.32MiB allocated for chunks. 12.32MiB in use in bin. 11.57MiB client-requested in use in bin.
> 2019-04-17 23:05:41.801033: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (262144):        Total Chunks: 87, Chunks in use: 87. 28.70MiB allocated for chunks. 28.70MiB in use in bin. 26.24MiB client-requested in use in bin.
> 2019-04-17 23:05:41.801054: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (524288):        Total Chunks: 116, Chunks in use: 116. 69.18MiB allocated for chunks. 69.18MiB in use in bin. 65.56MiB client-requested in use in bin.
> 2019-04-17 23:05:41.801076: I tensorflow/core/common_runtime/bfc_allocator.cc:630] Bin (1048576):       Total Chunks: 72, Chunks in use: 72. 93.28MiB allocated for chunks. 93.28MiB in use in bin. 87.71MiB client-requested in
> .......
> 2019-04-17 23:05:41.885127: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Sum Total of in-use chunks: 10.65GiB
> 2019-04-17 23:05:41.885143: I tensorflow/core/common_runtime/bfc_allocator.cc:680] Stats:
> Limit:                 11487382733
> InUse:                 11440863744
> MaxInUse:              11456095232
> NumAllocs:                69087351
> MaxAllocSize:           3595665408
> 
> 2019-04-17 23:05:41.885781: W tensorflow/core/common_runtime/bfc_allocator.cc:279] ***************************************************************************************************x
> 2019-04-17 23:05:41.885832: W tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at cwise_op_select.cc:116 : Resource exhausted: OOM when allocating tensor with shape[1,16,128,128,128] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
> Traceback (most recent call last):
>   File "train_isensee2017.py", line 134, in <module>
>     main(overwrite=config["overwrite"])
>   File "train_isensee2017.py", line 129, in main
>     n_epochs=config["n_epochs"])
>   File "../unet3d/training.py", line 118, in train_model
>     early_stopping_patience=early_stopping_patience))
>   File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
>     return func(*args, **kwargs)
>   File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/keras/engine/training.py", line 1418, in fit_generator
>     initial_epoch=initial_epoch)
>   File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/keras/engine/training_generator.py", line 217, in fit_generator
>     class_weight=class_weight)
>   File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/keras/engine/training.py", line 1217, in train_on_batch
>     outputs = self.train_function(ins)
>   File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
>     return self._call(inputs)
>   File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
>     fetched = self._callable_fn(*array_vals)
>   File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1382, in __call__
>     run_metadata_ptr)
>   File "/root/anaconda3/envs/py35/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
>     c_api.TF_GetCode(self.status.status))
> tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[1,16,128,128,128] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
>          [[Node: training/Adam/gradients/replica_0/model_1/leaky_re_lu_151/LeakyRelu_grad/Select_1 = Select[T=DT_FLOAT, _class=["loc:@training/Adam/gradients/AddN_259"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](training/Adam/gradients/replica_0/model_1/leaky_re_lu_151/LeakyRelu_grad/GreaterEqual, training/Adam/gradients/replica_0/model_1/leaky_re_lu_151/LeakyRelu_grad/zeros, training/Adam/gradients/replica_0/model_1/conv3d_200/convolution_grad/Conv3DBackpropInputV2)]]
> Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

**Comment by ziyigogogo** [comment]
OOM means that you should reduce your batch size for a more stable train scheme.

**Comment by Zyarra** [comment]
> OOM means that you should reduce your batch size for a more stable train scheme.

Yeah. However i have a lot of free VRAM(8gb+) and batch size 1 does the same
