### ISSUE TITLE
Keras Sequence Hangs with fit_generator when an Exception is Raised

### ISSUE THREAD

**Issue by briannemsick** [keras-team/keras#12704]
**System information**  
- Have I written custom code (as opposed to using example directory):  Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  OSX
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  1.13.1
- Keras version:  2.2.4
- Python version:  3.7
- CUDA/cuDNN version:  n/a
- GPU model and memory:  n/a

**Describe the current behavior**  
A Keras sequence raises an Exception, but the python process hangs.

**Describe the expected behavior**  
The python process is killed.

Note this issue is only present for sequences.

**Code to reproduce the issue**  
```python
import keras
import numpy as np
import pytest


class FaultSequence(keras.utils.Sequence):

    def __init__(self):
        self.batch_size = 5
        self.len = 20
        self.X = np.array(range(self.len))
        self.y = np.array(range(self.len)) 

    def __len__(self):
        return self.len

    def __getitem__(self, idx):
        bx = np.zeros((self.batch_size, 1))
        by = np.zeros((self.batch_size, 1))
        return (bx, by)

    def on_epoch_end(self):
        raise RuntimeError()


def simple_net(dense_dim=1):
    inputs = keras.layers.Input(shape=(1,))
    outputs = keras.layers.Dense(1, activation="linear")(inputs)
    net = keras.models.Model(inputs=inputs, outputs=outputs)
    return net


def test_fault_sequence():
    
    inputs = keras.layers.Input(shape=(1,))
    outputs = keras.layers.Dense(1, activation="linear")(inputs)
    net = keras.models.Model(inputs=inputs, outputs=outputs)
    net.compile(optimizer="Adam", loss="mse")

    with pytest.raises(RuntimeError):
        # A RuntimeError is raised as expected but the test never finishes executing.
        net.fit_generator(FaultSequence(), epochs=2)

**Comment by zhly0** [comment]
another question：
https://github.com/h5py/h5py/blob/master/examples/multiprocessing_example.py#L17-L21
the h5py seems to not support multiprocessing，and it did report error：
KeyError: 'Unable to open object (bad object header version number)，is there a way to avoid this？
