### ISSUE TITLE
No embedding in tensorboard for keras/examples/tensorboard_embeddings_mnist.py

### ISSUE THREAD

**Issue by jasonzhang2022** [keras-team/keras#12705]
**System information**  
- Have I written custom code (as opposed to using example directory):  
Copy the example code and run locally
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  
Linux Ubuntu 16.04
- TensorFlow backend (yes / no):  
yes
- TensorFlow version:  
2.0.0-alpha0 
- Keras version:  
tensorflow.keras

- Python version:  
3.6
- CUDA/cuDNN version:  
CPU
- GPU model and memory:  
CPU

**Describe the current behavior**  
python3 tensorboard_embeddings_mnist.py
then 
tensorboard --logdir=logs
I don't see any embeding tab

**Describe the expected behavior**  

I should see embedding tab

**Comment by ymodak** [comment]
Thanks for trying TF 2.0 alpha. You can visualize the embedding using the projector tab, there is no embedding tab.
