### ISSUE TITLE
Documentation Request for Sample Weights in Multi-Output Models

### ISSUE THREAD

**Issue by divyansha** [keras-team/keras#12708]
I have found the documentation for sample weights in multi-output models to be lacking. It does not tell you of the correct format to include sample weights in, for a multi-output model. 

While some trial-and-error helped me figure it out, it would've saved me and my collaborators some anguish if the documentation was clear beforehand.

Please add better documentation about this.

**Comment by ymodak** [comment]
Can you please point me to the link you are referring? Thanks!

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
