### ISSUE TITLE
Keras Document issue: sidebar dropdown shows nothing

### ISSUE THREAD

**Issue by I-Hong** [keras-team/keras#12739]
There is an issue as title. There supposed to show sub items on the pages. 
<img width="305" alt="Screen Shot 2019-04-25 at 3 52 46 PM" src="https://user-images.githubusercontent.com/41447049/56773256-3aaf2400-6772-11e9-8e24-dcac1ad80432.png">

**Comment by jvishnuvardhan** [comment]
@I-Hong There are no subitems. all the material was documented in the page. I know there is a `+` sign to expand, but as of now there is no more additional pages within `Convolutional Layers`. Please let us know what you think. Thanks!

**Comment by jvishnuvardhan** [comment]
I am closing the issue as there is no issue here. Thanks!
