### ISSUE TITLE
how do I expand the vocabulary size of a pre trained embedding

### ISSUE THREAD

**Issue by dwy904** [keras-team/keras#12734]
Hi, 

I have a pre-trained Keras model and there's a word embedding `[1000 vocabulary *  200 dimensions]` inside of the model.

Now I want to load it back to memory and continuous training it with new data. The vocabulary size increased because of the new data. 

I am wondering if it's possible to replace this embedding with a bigger vocabulary size `[2000 vocabulary * 200 dimensions]` but keeping other parameter weights unchanged for the entire model.

Thank you

**Comment by psschand** [comment]
I believe the question is not specific to keras. You will definitely need to retrain your model(refer arxiv) but if word embedding for your new vocabulary are covered in some other model, you may borrow them and use them for supervised learning.

**Comment by divyashreepathihalli** [comment]
you can now do this. Keras nightly version has added a new util `keras.utils.warmstart_embedding_matrix`. Using this you can continuously train your model with changing vocabulary. https://www.tensorflow.org/api_docs/python/tf/keras/utils/warmstart_embedding_matrix
