### ISSUE TITLE
Keras 2.2.4 doens't accept pathlib.Path when saving models, but older versions did.

### ISSUE THREAD

**Issue by odinsbane** [keras-team/keras#12754]
I recently updated keras to 2.2.4 and now when I create a model and use `model.save` with a pathlib object, I get the following error.

>TypeError: Required Group, str or dict. Received: <class 'pathlib.PosixPath'>.

Is this new behavior the expected behavior, or should a pathlib.Path be acceptable? I reinstalled keras version using `pip install keras==2.2.x`, and both 2.2.3 and 2.2.4 are broken but 2.2.2 worked as expected.

**System information**  
- OS Platform and Distribution : Centos 7  
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  1.13.1
- Keras version:  2.2.4
- Python version:  3.4.9
- CUDA/cuDNN version: 9.1  
- GPU model and memory: nvidia cards 2080 or 1080ti 

**Code to reproduce the issue**  
```python
from keras.layers import Input, Dense
from keras.models import Model
import pathlib

inputs = Input(shape=(784,))
x = Dense(64, activation='relu')(inputs)
x = Dense(64, activation='relu')(x)
predictions = Dense(10, activation='softmax')(x)
model = Model(inputs=inputs, outputs=predictions)
model.save(pathlib.Path("junk.h5"))
#model.save(str(pathlib.Path("junk.h5"))) works though.
```

**Comment by jvishnuvardhan** [comment]
@odinsbane i think model.save requires filepath as a string in 2.2.2, 2.2.3 and 2.2.4. There could be some changes in dtype of output of pathlib.Path.  you can use ` model.save(str(pathlib.Path("junk.h5"))) ` for all the three keras versions without any issue. thanks!

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will open a new issue. Thanks!

**Comment by odinsbane** [comment]
I am travelling, but you misread what I wrote. It used to work, says it
should work in the API, and now it doesn't work. Possibly update the api.

thank you
mbs

**Comment by jvishnuvardhan** [comment]
@odinsbane I can understand your question. My answer is this is not related to keras. It is related to Pathlib library.

In Keras 2.2.2, 2.2.3 and 2.2.4, [model.save](https://keras.io/getting-started/faq/#how-can-i-save-a-keras-model) expects a string input as follows
` model.save('my_model.h5') `

When we use Pathlib library with Keras 2.2.3 and 2.2.4 as 
`model.save(pathlib.Path("my_model.h5"))` 
it throws an error as `TypeError: Required Group, str or dict. Received: <class 'pathlib.PosixPath'>` which means that when we use Pathlib with Keras 2.2.3 and 2.2.4, the output of pathlib.path is not a string. Please let me know if I miss anything. thanks!

**Comment by odinsbane** [comment]
Thank you for your response. I think I misread the documentation and
actually I should just stick to using strings instead of Paths.

>which means that when we use Pathlib with Keras 2.2.3 and 2.2.4, the
output of pathlib.path is not a string.

Of course pathlib.Path is not a string it is a Path. That was supported up
until 2.2.2, and broken as of 2.2.3. After re-reading the documentation, I
think I missunderstodd.

`filepath: String, path to a ...`

I thought that meant String, or a path object but it makes more sense that
it means the path is a string. I was further confused by the fact the code
includes a condition for checking if the object is a pathlib.Path.

https://github.com/keras-team/keras/blob/master/keras/utils/io_utils.py#L206

So it is a bit ambiguous as to whether a pathlib.Path will be supported or
not. As you say though, I will just stick to using a string.

Cheers
Matt

**Comment by dizcza** [comment]
@jvishnuvardhan why wouldn't you wrap `filepath` in `self.filepath = str(filepath)` in the package implementation but rather insist on passing a string as input? With py3, pathlib becomes the recommended way of path handling and so it is a plus for packages that support this simple functional flawlessly.
Now image a user who made a script to train 100500 epochs and then keras failed to save the model just because it does not support `Path` objects.
-_-

**Comment by parthvshah** [comment]
Moreover, ```model.load_weights()``` is also not wrapped in ```str()```. Same issues as mentioned on this thread while loading the weights into a model. 

Can the API be changed to include support for Pathlib objects? @jvishnuvardhan
