### ISSUE TITLE
How to use fit_generator with generator that yields dictionary

### ISSUE THREAD

**Issue by Mem3rr0R** [keras-team/keras#12767]
https://github.com/keras-team/keras/issues/2568#issuecomment-215996122
This comment says that it's possible to yield a dictionary for fit_generator. But how is it done? I passed the name of the input like this
    inp_token = Input(shape=(MAX_LEN,),name='token_input')

Then in the generator I yield this
          yield {'token_input' : sequence.pad_sequences(tokens,maxlen=MAX_LEN), 'preds' : labels}

When I called fit_generator, it says this

/opt/conda/lib/python3.6/site-packages/keras/engine/training_generator.py in fit_generator(model, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
    208                     batch_size = list(x.values())[0].shape[0]
    209                 else:
--> 210                     batch_size = x.shape[0]
    211                 batch_logs['batch'] = batch_index
    212                 batch_logs['size'] = batch_size
AttributeError: 'str' object has no attribute 'shape'

If I can use a dictionary to specify input why is it indexing x.shape[0]? I don't see the traceback indexing any of the keys in the dictionary? I must have done it wrong. Anyone knows how to do that exactly? The original model has multiple inputs this is just partial output of it. Anyway it should be the same.

**Comment by edoardogiacomello** [comment]
I would need the same thing but I didn't tried to write any code yet. By the way, could you manage to inspect what is the if condition for the row 210?
The right branch would be row 208, so maybe the batch isn't detected as a dict.

**Comment by kukuruza** [comment]
The official docs (https://keras.io/models/model) give an example of what's needed in very end of section `fit_generator` -- your generator needs to yield two dicts, one for X, and one for Y.
```
yield {'input_1': x1, 'input_2': x2}, {'output': y}
```
