### ISSUE TITLE
Subclass of keras.utils.Sequence does not get the value I want when I use predict_generator

### ISSUE THREAD

**Issue by jeongHwarr** [keras-team/keras#12768]
My model expects to receive two input arrays when making a predict. (value, label)

So I made the following class using Sequence.

```
class No_decoder_sequence(keras.utils.Sequence):
 def __init__(self, x_set, y_set, batch_size):
    self.x, self.y = x_set, y_set
    self.batch_size = batch_size

 def __len__(self):
    return int(np.ceil(len(self.x) / float(self.batch_size)))

 def __getitem__(self, idx):
    batch_x = self.x[idx * self.batch_size:(idx + 1) * self.batch_size]
    batch_x = np.expand_dims(batch_x ,-1)
    batch_y = self.y[idx * self.batch_size:(idx + 1) * self.batch_size]

    return np.array(batch_x), np.array(batch_y)
```

However, an error occurs when I attempt to use the class to predict as follows:

```
 no_decoder_generator_1 = No_decoder_sequence(X_val_1, y_val_1, batch_size=1)
 y_predict_1, x_predict_1 = model.predict_generator(generator=no_decoder_generator_1, steps=len(X_val_1))
 y_predict_1 = np.asarray(y_predict_1)
 x_predict_1 = np.asarray(x_predict_1)  
```

> ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 2 array(s), but instead got the following list of 1 arrays: [array([[[[ 0.9287956 ],..

Why is my `No_decoder_sequence` returning only one array value?

![2019-04-30 02;15;31](https://user-images.githubusercontent.com/16534413/56914272-a4bb2680-6aee-11e9-9c0e-4dd5c1ce11da.PNG)

And how do I check the values sequence class returns?

**Comment by dulaku** [comment]
It's a bit hard to say without seeing your model code, but I believe what's going on here is that your generator is returning a tuple of your inputs and targets. The `fit_generator()` code expects the first element of that tuple to be all of the inputs and the second element to be all the targets. 

For a model with multiple inputs, you'd probably want a return line like:

`return [np.array(batch_x1), np.array(batch_x2)], np.array(batch_y)`

This way the generator's first return value will be a list of the 2 inputs the model expects. They should be in the same order that they're supplied when creating the Model object.

**Comment by jeonghwaYoo** [comment]
@dulaku Thank you for your comment! but, I think my model expects 2 inputs including target array. 
Why is not the target array returned? There was no problem with fit_generator. 

```
        train_model = models.Model(inputs=[x, y], outputs=[out_seg, shared_decoder(masked_by_y, conv_cap_2_1, x )]) # [x:image,y: mask] // [out_seg:length, reconstruction output]
        eval_model = models.Model(inputs=x, outputs=[out_seg, shared_decoder(masked, conv_cap_2_1, x)])
```

**Comment by dulaku** [comment]
Ah, my mistake! I did not read carefully enough. I believe that your generator's return line is correct in the code block you've just posted, though I'm not sure about the root cause of the error. I suspect, though, that there's a concatenation layer in your network that concatenates the inputs and targets, which won't work in this case because you've expanded a dimension on `batch_x` but not `batch_y`. Though that would only apply in the case of `train_model()` - `eval_model()` expects only one input.

I'm curious what the goal is here, however. Ordinarily, "target"s or "y"s are what the is trying to predict, and you wouldn't pass those as input; the model would very likely learn to rely on them, but they wouldn't be available at test time. Also, your model architecture would have to be somewhat different between the two models, I think; you wouldn't want the concatenation layer in `eval_model()` because there's nothing to concatenate, and since that means the input to the first layer after the concatenation would have a different size, you'd need to account for that as well.

Depending on your goal, it may be easier to revise the network architecture and training process to avoid encountering this error in the first place.

**Comment by jeonghwaYoo** [comment]
@dulaku 

![2019-04-30 23;11;41](https://user-images.githubusercontent.com/16534413/56968087-7ba59f00-6b9d-11e9-9e8a-de6d81a95d4d.PNG)

My model is basically similar to a convolution network.

I want my model to work regardless of the width of the input. So the width size appears as `None`.

My model requires a label in the decoder part.

This part is my decoder part (below)

```
if args.decoder==True:

    decoder = ConvCapsuleLayer(kernel_size=args.kernel_size, num_capsule=4, num_atoms=1, strides=1, padding='same',
                                  routings=1)(conv_cap)

    _, H, W, C, A = decoder.get_shape()

    y = layers.Input(shape=(n_class,))
    masked_by_y = Mask()([decoder, y])
    masked = Mask()(decoder)

    def shared_decoder(mask_layer):

        recon_1 = layers.Conv2DTranspose(4, (5,5), strides=(2, 2), padding='same',  kernel_initializer='he_normal', name='decoder_1', activation='relu')(mask_layer)
        recon_2 = layers.Conv2DTranspose(8, (5,5), strides=(2, 2), padding='same',  kernel_initializer='he_normal', name='decoder_2', activation='relu')(recon_1)
        recon_3 = layers.Conv2DTranspose(1, (1,1), strides=(1, 1), padding='same',  kernel_initializer='he_normal', name='decoder_3', activation='linear')(recon_2) 
        return recon_3

    if args.decoder==True:
        
        decoder = ConvCapsuleLayer(kernel_size=args.kernel_size, num_capsule=4, num_atoms=1, strides=1, padding='same', name='hello',
                                      routings=1)(conv_cap)
        
        _, H, W, C, A = decoder.get_shape()
        
        y = layers.Input(shape=(n_class,))
        masked_by_y = Mask()([decoder, y])
        masked = Mask()(decoder)
        
        def shared_decoder(mask_layer, ref_layer_1, ref_layer_2):
            
             recon_1 = Conv2DTranspose(1, (args.kernel_size, args.kernel_size), strides=(2, 2), padding='same', kernel_initializer='he_normal', name='decoder_1', activation='relu')([mask_layer, ref_layer_1])
             recon_2 = Conv2DTranspose(1, (args.kernel_size, args.kernel_size), strides=(2, 2), padding='same', kernel_initializer='he_normal', name='decoder_2', activation='relu')([recon_1, ref_layer_2])
             recon_3 = Conv2DTranspose(1, (1,1), strides=(1, 1), padding='same', kernel_initializer='he_normal', name='decoder', activation='linear')([recon_2, ref_layer_2])  
             return recon_3
    

    if args.decoder==True:
        train_model = models.Model(inputs=[x, y], outputs=[out_seg, shared_decoder(masked_by_y, conv_cap_2_1, x )]) # [x:image,y: mask] // [out_seg:length, reconstruction output]
        eval_model = models.Model(inputs=x, outputs=[out_seg, shared_decoder(masked, conv_cap_2_1, x)])
    else:
        train_model = models.Model(inputs=x, outputs=out_seg)
        eval_model = models.Model(inputs=x, outputs=out_seg)
    
    return train_model, eval_model
```


I created custom `Conv2DTranspose` to restore the size of the layer I wanted.

In `Mask` layer, 

If a label is given, only the channel of the label is returned. (masked_by_y)

If a label is not given, this layer only returns channel with the largest sum of the element values ​​in conv_capsule_layer_1. (masked)

I think that the shape that the input layer (`input_4`) requires and the shape `Sequence` creates are equal, but I do not know why there is a problem.

I really appreciate your reply. Please let me know if you know anything.

**Comment by dulaku** [comment]
Right, that is a curious problem then. I can't see the issue, but you can get sample outputs from a `Sequence` by creating a generator from it and using `next()`, which is what happens in the background when using them. The following snippet is taken from the `fit_generator()` code and should work:

```enqueuer = OrderedEnqueuer(generator, use_multiprocessing=use_multiprocessing, shuffle=shuffle)
enqueuer.start(workers=workers, max_queue_size=max_queue_size)
output_generator = enqueuer.get()
generator_output = next(output_generator)

**Comment by jeonghwaYoo** [comment]
@dulaku okay, so thank you!! However, how can I use it? 

I tried the following, but I get an error.
I refer to the following site.
https://www.tensorflow.org/api_docs/python/tf/keras/utils/SequenceEnqueuer
https://github.com/keras-team/keras/blob/master/keras/utils/data_utils.py

```
no_decoder_generator = No_decoder_sequence(x_train, y_train, batch_size=1)
enqueuer = keras.utils.data_utils.SequenceEnqueuer(no_decoder_generator)
enqueuer.start()
output_generator = enqueuer.get()
for output in output_generator:
          test = output
```

> NotImplementedError


Could you tell me more about how I can do it? So thank you :)

**Comment by jeonghwaYoo** [comment]
I found some strange things in `predict_generator`.

[https://github.com/keras-team/keras/blob/a6c8042121371b5873773ca767f28cdf5689d5e4/keras/engine/training_generator.py#L479-L516](url) 

why they only use `x` when the model predicts?

**Comment by dulaku** [comment]
In a typical model, there are two pieces of data for training: the inputs and targets. The inputs are the only data fed through the model to produce an output, and the only thing the targets are used for is computing the loss by comparison to the outputs. When predicting (rather than training), there is no loss to compute, so there's no need for the targets (indeed, you often won't have the targets at all because they're the information you wanted a model in order to compute in the first place). A `Sequence` should return a tuple whose first element is everything that's fed through the model, and the second element should be the targets that the model's output should be trained to match.

Unfortunately, that's all I know - I don't think I can resolve this problem, sorry!

**Comment by jeonghwaYoo** [comment]
@dulaku Okay, I understand! I really appreciate your kind answers. Thank you so much

**Comment by nicaogr** [comment]
What do you use finally to only load the inputs data with a generator ?
