### ISSUE TITLE
Error while try to execute 'make notebook' in Docker

### ISSUE THREAD

**Issue by zappee** [keras-team/keras#12789]
It seems I have a problem with nvidia-docker. I am trying to execute `make notebook` on my HP notebook but I get the following error:

```
Successfully tagged keras:latest
GPU=0 nvidia-docker run -it -v /home/user/keras:/src/workspace -v "/home/user/Data":/data --net=host --env KERAS_BACKEND=tensorflow keras
/bin/sh: 1: nvidia-docker: not found
Makefile:25: recipe for target 'notebook' failed
make: *** [notebook] Error 127
```

What I did:

- checked out the project from git: git clone https://github.com/keras-team/keras.git
- cd docker
- make notebook

Any idea what is wrong here?

**Comment by Castdeath97** [comment]
Can replicate the same issue, the scripts are still using a deprecated commands: https://github.com/NVIDIA/nvidia-docker#usage
