### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'image_data_format'

### ISSUE THREAD

**Issue by EdouardDKP** [keras-team/keras#12787]
Hello,
I am trying to train AI on different ResNet models. But, at each time, I have the following issue : 
AttributeError: 'NoneType' object has no attribute 'image_data_format'.
I am loading the ResNet models with the following code : 
from keras_applications.resnet import ResNet50
from keras_applications.resnet import ResNet101
from keras_applications.resnet import ResNet152

For example, the code line I am using to build the model is : 
model = ResNet50(input_shape= (IMG_SIZE_H, IMG_SIZE_W, NB_CHANNEL), include_top=True, weights=None, input_tensor=None, pooling=None, classes= NB_CLASSES)

My input shape is X_train shape: (415480, 50, 50, 1) with the parameter 'channels_last' applied by K.set_image_data_format('channels_last').
I am using the last version of Keras.

Could you help me please.
Thank you in advance

**Comment by ymodak** [comment]
Hi!
This issue isn't related to a bug/enhancement/feature request or other accepted types of issue.
To ask questions, please see the following resources :
[StackOverflow](http://stackoverflow.com/questions/tagged/keras)
[Keras Slack channel](https://keras-slack-autojoin.herokuapp.com)
[Keras.io support](https://keras.io/#support)
[Gitter](https://gitter.im/Keras-io/Lobby)
Thanks!
If you think we made a mistake, please open another issue explaining your request in detail.
