### ISSUE TITLE
 module 'tensorflow' has no attribute 'get_default_graph'

### ISSUE THREAD

**Issue by ahmedbenidir** [keras-team/keras#12783]
I'am using TensorFlow 2.0.0-alpha0 , also keras is using newly installed  version as a backend

TensorFlow 2.0.0-alpha0
Keras :2.2.4
OS:Kali Linux
python:3.7.3
CUDA: I'm not using CUDA

I had this error when trying to create a model:
_AttributeError: module 'tensorflow' has no attribute 'get_default_graph'_
Exactely i got this error on this instruction: `model = cnn_model()`
I followed  a lot of instructions on other Forums but nothings works.
Please does somebody could help me,
thank you !!

**Comment by psschand** [comment]
You normally import tensorflow by writing,

import tensorflow as tf
It's possible that you have named a file in your project tensorflow.py and the import statement is importing from this file.

Alternatively, you can try this,

from tensorflow.python.framework import ops
ops.reset_default_graph()

**Comment by ymodak** [comment]
In addition to psschand's suggestion, Please post this issue on [tensorflow repo](https://github.com/tensorflow/tensorflow/issues/new/choose) since its a not a bug/feature  request on keras end. Thanks!

**Comment by alanpurple** [comment]
same error, only when using  subclassing, and reset_default_graph doesn't work


/anaconda3/lib/python3.7/site-packages/keras/engine/network.py in __init__(self, *args, **kwargs)
     94         else:
     95             # Subclassed network
---> 96             self._init_subclassed_network(**kwargs)
     97 
     98     def _base_init(self, name=None):

/anaconda3/lib/python3.7/site-packages/keras/engine/network.py in _init_subclassed_network(self, name)
    292 
    293     def _init_subclassed_network(self, name=None):
--> 294         self._base_init(name=name)
    295         self._is_graph_network = False
    296         self._expects_training_arg = has_arg(self.call, 'training')

/anaconda3/lib/python3.7/site-packages/keras/engine/network.py in _base_init(self, name)
    107         if not name:
    108             prefix = self.__class__.__name__.lower()
--> 109             name = prefix + '_' + str(K.get_uid(prefix))
    110         self.name = name
    111 

/anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py in get_uid(prefix)
     72     """
     73     global _GRAPH_UID_DICTS
---> 74     graph = tf.get_default_graph()
     75     if graph not in _GRAPH_UID_DICTS:
     76         _GRAPH_UID_DICTS[graph] = defaultdict(int)

AttributeError: module 'tensorflow' has no attribute 'get_default_graph'

**Comment by dashanan** [comment]
i had got the same issue and used from  tensorflow.keras.models import load_model
this has fixed my issue with some warning , so try it if it works

**Comment by SumanthMeenan** [comment]
@ahmedbenidir Instead of using 1 use 2 
1. from keras
2. from tensorflow.keras

**Comment by 0x01h** [comment]
Downloading binary version of TensorFlow solved my problem.

```sh
$ pip install --ignore-installed --upgrade "<URL>"
```

**Select right binary URL according to your system from below.**
https://github.com/lakshayg/tensorflow-build

**Comment by duhita123** [comment]
> @ahmedbenidir Instead of using 1 use 2
> 
> 1. from keras
> 2. from tensorflow.keras

This worked

**Comment by Saajj** [comment]
> @ahmedbenidir Instead of using 1 use 2
> 
> 1. from keras
> 2. from tensorflow.keras

Worked For me

**Comment by ahmedbenidir** [comment]
Thank you for your help, I just tried with tensorflow 1.13 and it's good !

**Comment by gaurav-vision** [comment]
In my case I was using Tensorflow version 2.0 and got this error so I degraded my tensorflow version from 2.0 to tensorflow 1.4 and problem solved.

For downgrading the tensorflow from 2.0 to 1.4
$  pip3 install tensorflow==1.4

you can change it to other version as you wish by replacing last 1.4 to 1.1 or other.

**Comment by GarryGelade** [comment]
AFter updataing from tf 1.14 to tf 2.0, this worked for me as well.
Replace
```
from keras import backend as K
from keras.models import Sequential, load_model
from keras.layers import LSTM, Dense, RepeatVector, Masking, TimeDistributed
from keras.utils import plot_model
```
with
```
from tensorflow.keras import backend as K
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import LSTM, Dense, RepeatVector, Masking, TimeDistributed
from tensorflow. keras.utils import plot_model
```
Thank you @SumanthMeenan !

**Comment by tmukayev** [comment]
Guys, please, I have tried all of the above mentioned still no success

**Comment by ahmedbenidir** [comment]
Try the 1.13 or 1.14 version you'll not get errors

**Comment by tmukayev** [comment]
i actually thought I was working in 1.13 but I wasn't. So it really helped. Tnx peeps

**Comment by RSwarnkar** [comment]
> @ahmedbenidir Instead of using 1 use 2
> 
> 1. from keras
> 2. from tensorflow.keras

Can you please explain the reason for this, would be helpful for beginners as well.

**Comment by RSwarnkar** [comment]
> AFter updataing from tf 1.14 to tf 2.0, this worked for me as well.
> Replace
> 
> ```
> from keras import backend as K
> from keras.models import Sequential, load_model
> from keras.layers import LSTM, Dense, RepeatVector, Masking, TimeDistributed
> from keras.utils import plot_model
> ```
> 
> with
> 
> ```
> from tensorflow.keras import backend as K
> from tensorflow.keras.models import Sequential, load_model
> from tensorflow.keras.layers import LSTM, Dense, RepeatVector, Masking, TimeDistributed
> from tensorflow. keras.utils import plot_model
> ```
> 
> Thank you @SumanthMeenan !

Thank you for elaborating. Many beginners struggle due to bumpy version difference between TF1 and TF2.

**Comment by shivamshukla-hanaml** [comment]
> @ahmedbenidir Instead of using 1 use 2
> 
> 1. from keras
> 2. from tensorflow.keras

2
import keras 
import tensorflow as tf
from tensorflow.keras import backend
# from tensorflow.keras.models import load_model
model = tf.keras.models.Sequential()

**Comment by dilshadbanu** [comment]
> AFter updataing from tf 1.14 to tf 2.0, this worked for me as well.
> Replace
> 
> ```
> from keras import backend as K
> from keras.models import Sequential, load_model
> from keras.layers import LSTM, Dense, RepeatVector, Masking, TimeDistributed
> from keras.utils import plot_model
> ```
> 
> with
> 
> ```
> from tensorflow.keras import backend as K
> from tensorflow.keras.models import Sequential, load_model
> from tensorflow.keras.layers import LSTM, Dense, RepeatVector, Masking, TimeDistributed
> from tensorflow. keras.utils import plot_model
> ```
> 
> Thank you @SumanthMeenan !

It worked

**Comment by Satyadip-Biswas** [comment]
Use this: 
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
Insted of:
import tensorflow as tf

The issue is because of the version. Tensorflow 2.0 does not support that function.

Go to the link for more details:
https://www.tensorflow.org/api_docs/python/tf/compat/v1/get_default_graph

**Comment by Vimos** [comment]
@Satyadip-Biswas 

After replacing, it works for many interfaces! However, for some interfaces, it's not working.

```
    W_plus_b = lambda x: tf.contrib.layers.fully_connected(x,
                                           output_size, activation_fn=None)
AttributeError: module 'tensorflow_core.compat.v1' has no attribute 'contrib'
```

**Comment by zeysert** [comment]
> Use this:
> import tensorflow.compat.v1 as tf
> tf.disable_v2_behavior()
> Insted of:
> import tensorflow as tf
> 
> The issue is because of the version. Tensorflow 2.0 does not support that function.
> 
> Go to the link for more details:
> https://www.tensorflow.org/api_docs/python/tf/compat/v1/get_default_graph

Thank you,it works!

**Comment by WelcomeTshuma** [comment]
If you are using Tensorflow V2, use tf.compat.v1.get_default_graph() instead of tf.get_default_graph()
