### ISSUE TITLE
RepeatVector is not accepting 3D objects

### ISSUE THREAD

**Issue by SubrahmanyaG** [keras-team/keras#12796]
<em>i m trying to build last layer which has RepeatVector</em>  

**Problem Statement** : At RepeatVector layer I m getting the following error.
`ValueError: Input 0 is incompatible with layer repeat_vector_19: expected ndim=2, found ndim=3`

**Describe the current behavior**  
The shape of Input to the model is (30, 203) 
In the layer-2, I have given return_sequence=True so that I get all the features for all day (?, 30, 203). I pass this extracted data to the next layer a repeat vector.
In layer-3 I m repeating values 3 times so that at the end I can predict 3 different values.

But repeat vector is not accepting data in the 3 dimensional. 

```
from keras.models import Sequential
from keras.layers import Dense, LSTM, Masking, Input
from keras.layers import TimeDistributed, RepeatVector

timesteps=30
n_features = 203
model = Sequential()
model.add(Masking(mask_value=0, input_shape=(timesteps, n_features)))
model.add(LSTM(203, return_sequences=True)) ## return_sequences=False works as it return 2D
model.add(RepeatVector(3))
model.add(LSTM(100, activation='relu', return_sequences=True))
model.add(TimeDistributed(Dense(1)))
```
Please let me know how to solve this
@fchollet 

**System information**  
- OS Platform and Distribution (Linux Ubuntu 16.04):  
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  1.11.0
- Keras version:  2.2.4
- Python version:  3.5

**Comment by KoertS** [comment]
Hey,

I do not know if you already solved this issue but if you or somebody else runs into the same issue, try the code below.
I ran into the same problem when trying to use the repeatvector layer on  output with more than 2 dimensions
I adapted the RepeatVector code so it should work with 3D data.  Note that you can also change this to more than 3 dimension by changing the ndim=3 to different number. 

````python
from tensorflow.python.keras.engine.base_layer import Layer
from tensorflow.python.keras.engine.input_spec import InputSpec
from tensorflow.python.ops import array_ops
from tensorflow.keras.backend import repeat_elements

class RepeatVector3D(Layer):
  """Repeats the input n times.
  Example:
  ```python
  inp = tf.keras.Input(shape=(4,4))
  # now: model.output_shape == (None, 4,4)
  # note: `None` is the batch dimension
  output = RepeatVector3D(3)(inp)
  # now: model.output_shape == (None, 3, 4, 4)
  model = tf.keras.Model(inputs=inp, outputs=output)
  ```
  Args:
    n: Integer, repetition factor.
  Input shape:
    3D tensor of shape `(None, x, y)`.
  Output shape:
    4D tensor of shape `(None, n, x, y)`.
  """

  def __init__(self, n, **kwargs):
    super(RepeatVector3D, self).__init__(**kwargs)
    self.n = n
    self.input_spec = InputSpec(ndim=3)
  
  def compute_output_shape(self, input_shape):
    input_shape = tensor_shape.TensorShape(input_shape).as_list()
    return tensor_shape.TensorShape([input_shape[0], self.n, input_shape[1]])

  def call(self, inputs):
    inputs = array_ops.expand_dims(inputs, 1)
    repeat = repeat_elements(inputs, self.n, axis=1)
    return repeat

  def get_config(self):
    config = {'n': self.n}
    base_config = super(RepeatVector3D, self).get_config()
    return dict(list(base_config.items()) + list(config.items()))
```

**Comment by ogreyesp** [comment]
Hi @KoertS 

Thank you for your solution, I was facing the same problem.

Your solution worked well until TensorFlow tried to save the model (on_epoch_end) where it launched the following message:

raise NotImplementedError('Layer %s has arguments in `__init__` and '
NotImplementedError: Layer ModuleWrapper has arguments in `__init__` and therefore must override `get_config`.

How could I solve this error?

**Comment by KoertS** [comment]
Hey @ogreyesp,

I'm glad my code was useful for you. I just checked and when I save my model I do not get the error. Could you provide the code that you use to reproduce this behavior?

**Comment by ogreyesp** [comment]
Hi @KoertS 

I fixed the problem by commenting some lines as follows:

`class RepeatVector3D(layers.Layer):
    """Repeats the input n times.
    Example:
    ```python
    inp = tf.keras.Input(shape=(4,4))
    # now: model.output_shape == (None, 4,4)
    # note: `None` is the batch dimension
    output = RepeatVector3D(3)(inp)
    # now: model.output_shape == (None, 3, 4, 4)
    model = tf.keras.Model(inputs=inp, outputs=output)
    ```
    Args:
      n: Integer, repetition factor.
    Input shape:
      3D tensor of shape `(None, x, y)`.
    Output shape:
      4D tensor of shape `(None, n, x, y)`.
    """

    def __init__(self, n):

        super(RepeatVector3D, self).__init__()
        self.n = n

    def call(self, inputs):

        inputs = array_ops.expand_dims(inputs, 1)
        repeat = repeat_elements(inputs, self.n, axis=1)

        return repeat

    def get_config(self):

        # base_config = super(RepeatVector3D, self).get_config().copy()

        return {"n": self.n}`
