### ISSUE TITLE
flow_from_directory gets very slow for large datasets

### ISSUE THREAD

**Issue by JayCarraway** [keras-team/keras#12807]
Hey everybody,

I am working on a image classification task where I try to distinguish images of 51 categories. As inference-speed is crucial, I am using a mobilenetv2 with added layers on top. To speed up my training, I am building bottlenecks before the actual training. 
For the creation of the bottlenecks I am using the keras ImageDataGenerator and flow_from_directory to pipe my images into model.predict().

```
    params = {'model':{'name':'','input_shape':(224, 224,3),'alpha':1.0,'include_top':False,'weights':'imagenet','input_tensor':None,'pooling':None},
             'lr': 0.01648,
             'epsilon':0.086,
             'decay':1e-5,
             'first_neuron':256,
             'batch_size': 40,
             'epochs': 100,
             'dropout': 0.293,
             'loss': logcosh,
             'last_activation': sigmoid}
    model = applications.mobilenet_v2.MobileNetV2(input_shape=params['model']['input_shape'],
                                                  alpha=params['model']['alpha'],
                                                  include_top=params['model']['include_top'],
                                                  weights=params['model']['weights'],
                                                  input_tensor=params['model']['input_tensor'],
                                                  pooling=params['model']['pooling'])


    datagen = ImageDataGenerator(rescale=1. / 255)
    generator = datagen.flow_from_directory(
        FLAGS.train_data_dir,
        target_size=(img_width, img_height),
        batch_size=1,
        class_mode=None,
        shuffle=False)
```
I am running the prediction on a GPU and with small datasets (around a few thousand images, let's say 4000) I am able to create around 50 bottlenecks/s. If I increase my dataset to my actual size of about 150.000 images, I only yield around 3-5 bottlenecks/s. 
Is the size of my dataset slowing down the flow_from_directory? I cannot think of another reason.
Best regards,
J

**Comment by kechan** [comment]
Have you resolved your problem yet?

Do you think you can share the timing numbers? I am doing a image classification prototype and also starting off with .flow_from_directory(...). I have only 6k images for 6 classes but was extremely slow when I did this on google colab across gdrive. I was informed the network i/o could be significant cost. I then copied all the files locally onto localhost (whatever colab ran on at that moment) and saw signficant improvement. I think it is still slower than I expect, so next is disk I/O that could be causing it.

Overall, I have impression .flow_from_directory(...) is not doing any particular optimization such as caching, and it may well be doing too many disk I/O reading images over and over from disk. This will be a big drag for training. In your case, you are using it for inference, but it is still worth looking into disk I/O as a potential issue.
