### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'ResNet101'

### ISSUE THREAD

**Issue by alyato** [keras-team/keras#12804]
when i load pretrained model ,such as ResNet101, it show me `AttributeError: 'NoneType' object has no attribute 'ResNet101'`.
then i try the model,such as ResNet50V2, it also show me `AttributeError: 'NoneType' object has no attribute 'ResNet50V2`
how to fix it? thanks.
 keras: 2.2.4

**Comment by jvishnuvardhan** [comment]
@alyato Can you try
```
import keras
import keras_applications
keras_applications.set_keras_submodules(
    backend=keras.backend,
    layers=keras.layers,
    models=keras.models,
    utils=keras.utils
)

model= keras_applications.resnet.ResNet101(include_top=False,weights='imagenet')

```
Thanks!

**Comment by alyato** [comment]
Hi,@jvishnuvardhan I have done it but it doesn't work.
it show me `AttributeError: 'module' object has no attribute 'resnet'`
I can't check the `keras_applications` module.
When i change the `keras_applications.resnet.ResNet101` to `keras.applications.resnet.ResNet101` ,
it also show `AttributeError: 'NoneType' object has no attribute 'ResNet101'`
Thanks again.

**Comment by jvishnuvardhan** [comment]
@alyato I understand that there is no module under `keras.applications.resnet.ResNet101` and hence it is showing attribute error. But, it is strange to see attribute error" when you used `keras_applications.resnet.ResNet101` . 

I created a GitHub [gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/4e9aae6ff35167fd0c789b2b918adffc/untitled156.ipynb). Can you open and run it. I am not sure whether there is any issue in the installation of keras and related modules. Thanks!

**Comment by jvishnuvardhan** [comment]
@alyato Can you mentioned what backend you are using. Could you fill the issue template mentioned below.

Please fill the issue template [here](https://github.com/keras-team/keras/issues/new/choose). Could you update them if they are relevant in your case, or leave them as N/A? Thanks!

**Comment by alyato** [comment]
@jvishnuvardhan thanks.
the tensorflow is `1.4.0`
the keras is `2.2.4`
but i don't install the keras by `pip`,and i use `python setup.py install`
i check the gist you gived,and did it again.
![res50](https://user-images.githubusercontent.com/6815071/57741023-51032c80-76ed-11e9-8ca6-60eef6e7b7a3.png)

**Comment by alyato** [comment]
@jvishnuvardhan 
I install keras by`pip install keras==2.2.4`,and do it again. It show the same error.
`AttributeError: 'module' object has no attribute 'resnet'`
Is there some wrong about tensorflow? lower version?
thanks.

**Comment by icdee** [comment]
@alyato 
I solved this problem by updating keras-application package to latest version 1.0.7

`pip install keras-applications==1.0.7`

**Comment by jvishnuvardhan** [comment]
@alyato Please let me know whether @icdee suggestion worked for you. I think it should work with that version of keras-applications. Thanks!

**Comment by alyato** [comment]
@icdee @jvishnuvardhan 
i can't upgrade the latest version of the keras-applications when i do `pip install keras-applications==1.0.7`
It also the `1.0.6`
![pip_1 0 7](https://user-images.githubusercontent.com/6815071/58365948-f85a3d80-7efd-11e9-85ef-00d4a334930b.png)
![python2 7](https://user-images.githubusercontent.com/6815071/58365950-00b27880-7efe-11e9-9d24-ba8a8107b1aa.png)
So what can i do next? thanks.

**Comment by jvishnuvardhan** [comment]
@alyato Run your code and check whether the issue persists. Thanks!

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will open a new issue. Thanks!
