### ISSUE TITLE
define median-based error metric for keras in R

### ISSUE THREAD

**Issue by msloryg** [keras-team/keras#12815]
I would like to use the custom metric MdAPE (median absolute percentage error), but since I could neither find a median backend function nor something like oder or sort (so I could calculate the median myself) I do not really know how to do it..
I think median-based error metrics are not uncommon so I am quite surprised I couldn't find anything.
I use keras for R

**Comment by jvishnuvardhan** [comment]
@msloryg For median, you could use different libraries (numpy, pandas, tensorflow etc). Check a [resource](https://stackoverflow.com/questions/43824665/tensorflow-median-value) for median, and for custom metric, you can find them on [Keras website](https://keras.io/metrics/#custom-metrics). Thanks!

**Comment by msloryg** [comment]
@jvishnuvardhan 
I tried it this way (I use keras for R btw)

```
mdape <- custom_metric("mdape", function(y_true, y_pred) {
  
  # convert tensors to R objects
  K <- backend()
  y_true <- K$eval(y_true)
  y_pred <- K$eval(y_pred)
  
  # calculate the metric
  for(i in 1:length(y_true)){
    x[i] <- abs(y_true[i] - y_pred[i])/y_true[i]
  } 
  mdape = median(x)
  
  # convert to tensor
  K$constant(mdape)
})
```
but this is not correct since I get this error when trying to compile the model with the mdape metric:

```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  RuntimeError: Evaluation error: InvalidArgumentError: You must feed a value for placeholder tensor 'dense_1_target_7' with dtype float and shape [?,?]
	 [[node dense_1_target_7 (defined at C:\Users\Laura\ANACON~1\envs\TENSOR~1\lib\site-packages\tensorflow\python\training\checkpointable\base.py:474)  = Placeholder[dtype=DT_FLOAT, shape=[?,?], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'dense_1_target_7', defined at:
  File "C:\Users\Laura\ANACON~1\envs\TENSOR~1\lib\site-packages\tensorflow\python\training\checkpointable\base.py", line 474, in _method_wrapper
    method(self, *args, **kwargs)
  File "C:\Users\Laura\ANACON~1\envs\TENSOR~1\lib\site-packages\tensorflow\python\keras\engine\training.py", line 588, in compile
    dtype=K.dtype(self.outputs[i]))
  File "C:\Users\Laura\ANACON~1\envs\TENSOR~1\lib\site-packages\tensorflow\python\keras\backend.py", line 844, in placeholder
    x = array_ops.placeholder(dtype, shape=shape, name=name)
  File " 
```
I am not really familiar with Python, so I don't know what the problem is.. I tried using tensorflow functions as 
`tf$$contrib.distributions.percentile(x, 50.0)` but then I had to do something like `import tensorflow as tf` and I am not sure how to do this in R

**Comment by jvishnuvardhan** [comment]
@msloryg Please post it in another group that discusses issues of tensorflow related to R. The source code in this repo is python. Thanks!

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
