### ISSUE TITLE
Plans for new release?

### ISSUE THREAD

**Issue by dd1923** [keras-team/keras#12826]
The last release was in October of last year (2018) ! That is already 289 (!) commits behind. When is the next release planned? There are a lot of bug fixes and new features between now and last release.

**Comment by Jonas1312** [comment]
https://github.com/keras-team/keras/issues/12611 https://github.com/keras-team/keras/issues/12461 https://github.com/keras-team/keras/issues/12421 ... I'm starting to think that Keras has been definitely absorbed by `tf.keras`

**Comment by dd1923** [comment]
Definitely looks like so.
