### ISSUE TITLE
How can I add beam search in image_ocr.py 

### ISSUE THREAD

**Issue by menon92** [keras-team/keras#12823]
In example `image_ocr.py` there is use `best path search` algorithm for decoding as follows, 

```python
def decode_batch(test_func, word_batch):
    out = test_func([word_batch])[0]
    ret = []
    for j in range(out.shape[0]):
        out_best = list(np.argmax(out[j, 2:], 1))
        out_best = [k for k, g in itertools.groupby(out_best)]
        outstr = labels_to_text(out_best)
        ret.append(outstr)
    return ret
```
 How can I use `beam search` instead of  this `best path search` 

**System information**    
- OS : Ubuntu 16.04  
- TensorFlow backend : yes   
- TensorFlow version:  '1.13.1'
- Keras version:  '2.2.4'
- Python version:  3.7.1

Thanks in advance.

**Comment by ymodak** [comment]
Hi!
This issue isn't related to a bug/enhancement/feature request or other accepted types of issue.
To ask questions, please see the following resources :
[StackOverflow](http://stackoverflow.com/questions/tagged/keras)
[Keras Slack channel](https://keras-slack-autojoin.herokuapp.com)
[Keras.io support](https://keras.io/#support)
[Gitter](https://gitter.im/Keras-io/Lobby)
Thanks!
If you think we made a mistake, please open another issue explaining your request in detail and why this is a bug/feature request.
