### ISSUE TITLE
Documentation Required GAN

### ISSUE THREAD

**Issue by harsh2ai** [keras-team/keras#12838]
<em>Please make sure that this is a Bug or a Feature Request and provide all applicable information asked by the template.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.</em>  

**System information**  
- Have I written custom code (as opposed to using example directory):  
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  latest update
- Keras version:  up to date
- Python version:  up to date
- CUDA/cuDNN version:  -
- GPU model and memory: - 

The keras.io has no documentation on the Generative Adversial Network and No examples too, I guess there should be an section for this too

**Comment by abhinavsagar** [comment]
Agreed. Feel free to make a PR.

**Comment by siddheshsathe** [comment]
Thanks @hr21 for raising this issue.
Can we expect another example for GAN along with common MNIST, Fashion MNIST datasets?
I feel that would be a benefit for all.
