### ISSUE TITLE
sudo python setup.py install | RuntimeError: Python version >= 3.5 required

### ISSUE THREAD

**Issue by justinvzyl** [keras-team/keras#12837]
**System information**  
- Have I written custom code (as opposed to using example directory): 

[+] No 

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  

[+] Ubuntu 18.04

- TensorFlow backend (yes / no):  

[+] Yes

- TensorFlow version: 
 
[+] Tensorflow v1.13.1-0-g6612da8951

- Keras version: 
 
[+] Keras 2.2.4

- Python version:  

[+] Python 3.5.0

- CUDA/cuDNN version:  

[+] None

- GPU model and memory:  

[+] GTX 1050 4Gb

**Describe the current behavior**  

Running the commands as per the instructions in a virtual environment.

sudo python setup.py install
...
  File "/tmp/easy_install-vOk903/scipy-1.3.0/setup.py", line 31, in <module>
    author_email='francois.chollet@gmail.com',
RuntimeError: Python version >= 3.5 required.
...

**Describe the expected behavior** 

Successful installation.

**Code to reproduce the issue**  

[+] conda create -n kerasenv python=3.5.0 
[+] conda activate kerasenv
[+] git clone https://github.com/keras-team/keras.git
[+] cd keras
[+] pip install tensorflow
[+] sudo python setup.py install 
...
Installation Fail
... 

**Other info / logs**  

[errorlog2.txt](https://github.com/keras-team/keras/files/3196276/errorlog2.txt)

**Comment by justinvzyl** [comment]
Looks to be a problem with Scipy from the logs

**Comment by ymodak** [comment]
I understand that this is issue regarding unsuccessful TF installation and not bugs/ feature request on keras side. If that is the case can you please post this issue on [tensorflow repo](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!

**Comment by justinvzyl** [comment]
As per the TF testing instructions, I tested TF installation as follows:

[+] conda activate kerasenv
[+] python
[+] import tensorflow as tf
[+] hello = tf.constant('Hello TensorFlow!')
[+] sess = tf.Session()
[+] print(sess.run(hello))
--> b'Hello TensorFlow'

The TF installation seems fine. Should I still post this to the TF repo?

**Comment by ymodak** [comment]
Thanks for the clarification. You need post this TF repo.
@gabrieldemarmiesse  Can you please take a look? Thanks!

**Comment by justinvzyl** [comment]
Issue logged on TF repo:
https://github.com/tensorflow/tensorflow/issues/29100

**Comment by justinvzyl** [comment]
Full stack trace: [trace.txt](https://github.com/keras-team/keras/files/3230221/trace.txt)

**Comment by justinvzyl** [comment]
Issue resolved.
Solution:
`which python` -> `dir/to/python`
`sudo dir/to/python setup.py install`

Uses the correct version of python and not the system default which gets invoked by sudo
