### ISSUE TITLE
[ERROR]Input0 != Input1

### ISSUE THREAD

**Issue by chjq201410695** [keras-team/keras#12835]
**System information**  
- Have I written custom code (as opposed to using example directory):  Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Linux Ubuntu 16.04
- TensorFlow backend (yes / no):  Yes
- TensorFlow version:  1.12.0
- Keras version:  2.2.4
- Python version:  3.6.7
- CUDA/cuDNN version:  9.0.176
- GPU model and memory:  

**Describe the current behavior**  
I built a seq2seq model to deal with a regression problem.

model.fit() with 1 GPU can work.

however, parallel_model.fit() with 3 GPUs will raise a error of Input0 != Input1, as details in below.

**Other info / logs**  
here is my code:
```python
encoder_inputs = Input(shape=(25,157), name='encode_input')
masked_encoder_inputs = Masking(mask_value=-1)(encoder_inputs)

encoder_fst = GRU(config['fst_RNN'],return_sequences=True,kernel_initializer='orthogonal',activation='elu')
encoder_fst_out = fst_lstm(masked_encoder_inputs)

encoder_scd = GRU(config['thd_RNN'],return_sequences=False,return_state=True, kernel_initializer='orthogonal',activation='elu')
_ , state_h = encoder_scd(encoder_fst_out)

decoder_inputs = Input(shape=(25,1),name='decoder_input')
masked_decoder_inputs = Masking(mask_value=-1)(decoder_inputs)

decoder_fst = GRU(config['thd_RNN'], return_sequences=True,kernel_initializer='orthogonal',activation='elu')
decoder_fst_outputs = decoder_fst(masked_decoder_inputs, initial_state = state_h) 

decoder_outputs =Dense(1,activation='linear')(decoder_fst_outputs) 

with tf.device('/cpu:0'):
    model = Model([encoder_inputs,decoder_inputs], decoder_outputs)

parallel_model = multi_gpu_model(model,3)
parallel_model.compile(loss='mape',
            optimizer=Nadam(lr=config["lr"]),
            metrics=['mse'])   

 hist = parallel_model.fit([X_train,mulin_train.reshape(-1,25,1)], mulout_train.reshape(-1,25,1)，
                       epochs=500,
                       batch_size=config['batch_size'],
                       verbose=2,
                       callbacks=[earlyStopping,reduceLROnPlateau],
                       validation_data=([X_test,mulin_test.reshape(-1,25,1)],mulout_test.reshape(-1,25,1))
                          )


here is error information：
------------------------------------
Train on 642861 samples, validate on 33835 samples
Epoch 1/500

---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-533-4e3e2286e2c3> in <module>
     29                           verbose=2,
     30                           callbacks=[earlyStopping,reduceLROnPlateau],
---> 31                           validation_data=([X_test,mulin_test.reshape(-1,25,1)],mulout_test.reshape(-1,25,1))
     32                           )
     33 # X_train, X_test, y_train, y_test, mulin_train, mulin_test, mulout_train, mulout_test

~/.local/lib/python3.6/site-packages/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, **kwargs)
   1037                                         initial_epoch=initial_epoch,
   1038                                         steps_per_epoch=steps_per_epoch,
-> 1039                                         validation_steps=validation_steps)
   1040 
   1041     def evaluate(self, x=None, y=None,

~/.local/lib/python3.6/site-packages/keras/engine/training_arrays.py in fit_loop(model, f, ins, out_labels, batch_size, epochs, verbose, callbacks, val_f, val_ins, shuffle, callback_metrics, initial_epoch, steps_per_epoch, validation_steps)
    210                         val_outs = test_loop(model, val_f, val_ins,
    211                                              batch_size=batch_size,
--> 212                                              verbose=0)
    213                         val_outs = to_list(val_outs)
    214                         # Same labels assumed.

~/.local/lib/python3.6/site-packages/keras/engine/training_arrays.py in test_loop(model, f, ins, batch_size, verbose, steps)
    390                 ins_batch[i] = ins_batch[i].toarray()
    391 
--> 392             batch_outs = f(ins_batch)
    393             if isinstance(batch_outs, list):
    394                 if batch_index == 0:

~/.local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py in __call__(self, inputs)
   2713                 return self._legacy_call(inputs)
   2714 
-> 2715             return self._call(inputs)
   2716         else:
   2717             if py_any(is_tensor(x) for x in inputs):

~/.local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py in _call(self, inputs)
   2673             fetched = self._callable_fn(*array_vals, run_metadata=self.run_metadata)
   2674         else:
-> 2675             fetched = self._callable_fn(*array_vals)
   2676         return fetched[:len(self.outputs)]
   2677 

~/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py in __call__(self, *args, **kwargs)
   1437           ret = tf_session.TF_SessionRunCallable(
   1438               self._session._session, self._handle, args, status,
-> 1439               run_metadata_ptr)
   1440         if run_metadata:
   1441           proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

~/.local/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py in __exit__(self, type_arg, value_arg, traceback_arg)
    526             None, None,
    527             compat.as_text(c_api.TF_Message(self.status.status)),
--> 528             c_api.TF_GetCode(self.status.status))
    529     # Delete the underlying status object from memory otherwise it stays alive
    530     # as there is a reference to status from this from the traceback due to

InvalidArgumentError: Inputs to operation replica_2_37/model_85/gru_145/while/Select_1 of type Select must have the same size and shape.  Input 0: [14,64] != input 1: [15,64]
	 [[{{node replica_2_37/model_85/gru_145/while/Select_1}} = Select[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:2"](replica_2_37/model_85/gru_145/while/Tile, replica_2_37/model_85/gru_145/while/add_6, replica_2_37/model_85/gru_145/while/Switch_3:1)]]
	 [[{{node replica_0_38/model_85/gru_144/while/Switch_1/_21489}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1367_replica_0_38/model_85/gru_144/while/Switch_1", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopreplica_0_38/model_85/gru_144/while/TensorArrayReadV3_1/_21162)]]
```

**Comment by ymodak** [comment]
Hi!
This issue isn't related to a bug/enhancement/feature request or other accepted types of issue.
To ask questions, please see the following resources :
[StackOverflow](http://stackoverflow.com/questions/tagged/keras)
[Keras Slack channel](https://keras-slack-autojoin.herokuapp.com)
[Keras.io support](https://keras.io/#support)
[Gitter](https://gitter.im/Keras-io/Lobby)
Thanks!
If you think we made a mistake, please open another issue explaining your request in detail.

**Comment by visionscaper** [comment]
@ymodak I'm having the same issue, also with a sequence-to-seqeunce model structure.

I really think this issue should be reopened.

There is an issue when having a Masking layers in the seq-to-seq model combined with using the `multi_gpu_model` utility. Although I'm not 100% sure, the problem relates to having a masking layer for the **decoder** input; input masking for the **encoder** works fine.

This is the error that I receive:
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: Inputs to operation replica_0/model_1/decoder-model-with-agent-names/decoder-layer-0/while/Select_1 of type Select must have the same size and shape.  Input 0: [180,256] != input 1: [60,256]
	 [[{{node replica_0/model_1/decoder-model-with-agent-names/decoder-layer-0/while/Select_1}}]]
	 [[{{node replica_2/model_1/chat-encoder-model_4/chat-encoder-layer-1/while/LogicalAnd}}]]
```

Note:
```
Input 0: [180,256] != input 1: [60,256]
```

For some reason, in the multi GPU version, distributing the batch over three GPUs, the shape of `Input 0` remains the full batch size (`180/3=60`). If I remove the Masking layers, the multi GPU version trains just fine. If I train only on one GPU with masking, it also works, just like @chjq201410695 reported.

I have been digging through the Keras and Tensorflow code to understand what's going on, but until now I haven't been able to pinpoint the cause.

**Comment by visionscaper** [comment]
Update: 

 * I have also tried to add a masking layer to the state input for the decoder, but that didn't help either.
 * I have verified that removing the masking layer for the decoder input, but leaving in the masking layer for the encoder input, indeed resolves the problem; training works for the multi GPU version.

Some more info about my system:

 * Keras 2.2.4
 * Tensorflow 1.13.1

**Comment by karmel** [comment]
Can you try this with [tf.distribute.Strategy](https://www.tensorflow.org/guide/distribute_strategy#mirroredstrategy)? This is the new API for multi-GPU training.

**Comment by visionscaper** [comment]
Hi @karmel, you mean for the tf.keras fork it is the new API for multi-GPU training, right?
Or can users also use this with the original Keras library?

In any case, I'm using sample weighting which is not yet supported by the tf.distribute.Strategy.
But I could setup a test where I leave that out.

**Comment by visionscaper** [comment]
@ymodak Thanks you for reopening this issue. I was wondering if this issue also should also have a bug label? Or are you still investigating it?

**Comment by karmel** [comment]
tf.distribute.Strategy is only for tf.keras, but we would highly recommend you use tf.keras if you are working with the TensorFlow backend.

**Comment by visionscaper** [comment]
@karmel Yeah I'm trying to migrate, [see these tweets, including response from @fchollet](https://twitter.com/Visionscaper/status/1137102529194536963). If I manage to get any further I will experiment with the combination of Masking and MirroredStrategy.

**Comment by visionscaper** [comment]
@karmel, I did another attempt to migrate my code to tf.keras so I could test with tf.distribute.Strategy but I'm encountering so many issues, e.g., sample-weighting not supported, mixed precision/loss-scaling not working, difficulties to use my batch generators with tf.data.Dataset (resolved), DistributionStrategy can't use tf.keras optimizer instances; there seems to be a bug in tf.keras when trying to train a model composed of other models (You must feed a value for placeholder tensor 'X'), while there has not been an issue before training this composed model. 

Every time I fix one issue, or disable some functionality to simplify the migration, multiple other issues pop-up. It is highly frustrating. In any case this is beyond the scope of this issue, just needed to vent my frustration over this. I will communicate more details to @fchollet.

My time is unfortunately very limited so I'm not sure if I will create test code in order to try to reproduce this issue with tf.distribute.Strategy.

**Comment by karmel** [comment]
@visionscaper -- I'm really sorry to hear that it's been such a hassle. We are trying to improve the experience, and would welcome your feedback/can help you with specific issues. Is the code sample above what you are migrating? Or is there a representative ipynb?

CC @dynamicwebpaige @tomerk .

**Comment by visionscaper** [comment]
Hi @karmel, thanks for your response. I sent an extensive email to @fchollet and @dynamicwebpaige yesterday with a list of issues I encountered during my migration attempts.

I did not start this particular issue here, so the given code sample in the beginning is not mine. I commented on this issue because I was trying to add Masking layers in my model (based on the original Keras, not `tf.Keras`) and experienced the same errors as were reported by the OP.

The code base (particularly the model) I'm trying to migrate is more complex, but indeed, it is a  sequence to sequence type of model. What might be best is to create a simpler model (but keeping some key structural aspects) and test training script, that would reproduce this particular issue, and the issues I had while migrating my code. I will need some time to create that. To be continued.

**Comment by visionscaper** [comment]
@karmel @fchollet This has been resolved for tf.keras with Tensorflow 2.0 in the latest nightly.

Please see my [Tensorflow Keras issues tests repo](https://github.com/visionscaper/tf-issues) that I use to investigate what features from the original Keras work in `tf.keras` and which don't.

You can run this test and see it in action yourself:

```
python3 tests/tf20_keras/tests.py TestIssuesTFKeras.test_multi_gpu_float32_masking_use_partially_known_dropout_noise_shape_sample_weight_mode
```

To run the test above you need to have the dependencies in [`requirements_tensorflow20_keras_env.txt`](https://github.com/visionscaper/tf-issues/blob/master/requirements_tensorflow20_keras_env.txt) installed, also see the [`README.md`](https://github.com/visionscaper/tf-issues/blob/master/README.md).

This is the `tf-nightly` version I used:

```
$ pip list | grep tf-nightly
tf-nightly-gpu-2.0-preview       2.0.0.dev20190824
```
