### ISSUE TITLE
ImageDataGenerator has no keyword argument 'validation_split'

### ISSUE THREAD

**Issue by li-zheng-hao** [keras-team/keras#12857]
when I use ImageDataGenerator like this:

`gen = ImageDataGenerator(rescale=1. / 255,validation_split=0.1) `

there is an error:

![image](https://user-images.githubusercontent.com/22129824/58221966-17629f00-7d47-11e9-968e-10d2d31fcd77.png)

my keras version: 2.1.4
my tensorflow-gpu version:1.5.0
my python version:3.5

**Comment by Zhujia1995** [comment]
i have meet this problem also

**Comment by li-zheng-hao** [comment]
> i have meet this problem also

it makes me very confusing now,because I saw this parameter in official document

**Comment by ymodak** [comment]
@li-zheng-hao  Can you please update your keras version to 2.2.4 and try again?

**Comment by li-zheng-hao** [comment]
> @li-zheng-hao Can you please update your keras version to 2.2.4 and try again?

thank you very much! I update my keras version  and it solved my problem.
