### ISSUE TITLE
Failed to load a keras model to my raspberry pi3 b+

### ISSUE THREAD

**Issue by Emirismail** [keras-team/keras#12855]
**System information**  
- OS Platform and Distribution : Rasbian (RaspberryPi3 B+)  
- TensorFlow backend : Yes 
- TensorFlow version:  
- Keras version:  2.2.4
- Python version:  3.5.3
- CUDA/cuDNN version:  
- GPU model and memory: Ram 1Go  

**Describe the current behavior**  
I am trying to load a keras model to do classification task using my raspberry. But after running this code:
```
import keras
from keras.models import load_model

model = load_model("mobilenet_v2_3(trained).h5")
```

but i get this error:
```
Using TensorFlow backend.
Instructions for updating:
Colocations handled automatically by placer.
Backend terminated(returncode: -11)
Fatal python error: Segmentation fault 
```

**Comment by jvishnuvardhan** [comment]
I think your model needs more memory than what you have. Can you try with smaller model and see whether this bug persists. Thanks!

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
