### ISSUE TITLE
Verbose = 1 new line at each update

### ISSUE THREAD

**Issue by laurentopia** [keras-team/keras#12860]
**System information**  
- Have I written custom code (as opposed to using example directory): see attached 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10 
- TensorFlow backend (yes / no): yes  
- TensorFlow version:  1.13.1
- Keras version:  2.2.4
- Python version:  3.7.3
- CUDA/cuDNN version:  via anaconda 10.0/7.3.1
- GPU model and memory: 1060 6gb  

in visual code fit(...verbose=1) displays one line per epoch instead of keeping the progress bar at the same place

**Describe the current behavior**  
![image](https://user-images.githubusercontent.com/26075468/58236322-83b5b200-7cf7-11e9-96a8-ce6f38e88cd7.png)

**Describe the expected behavior**  
progress bar remains at the same spot

**Code to reproduce the issue**  
https://pastebin.com/gA7a9tKs

**Comment by mani2106** [comment]
This is confusing 
From Documentation:
> verbose: Integer. 0, 1, or 2. Verbosity mode. 0 = silent, 1 = progress bar, 2 = one line per epoch

Default is **1**.

Does the Progress bar represent the progress of whole training or the progress **for each epoch** in a training?.

What I get during training is A progress bar for each epoch.

The Documentation should be something like
- 0: No Logging.
- 1: Displaying a progress-bar for each epoch.
- 2: Displaying one line per epoch.

Outputs in Jupyter notebook:
**Verbosity 1**:
![progbar](https://user-images.githubusercontent.com/20659733/58314664-9e8a4280-7e2d-11e9-87ad-788768a61ba9.png)

**Verbosity 2**:
![progbar2](https://user-images.githubusercontent.com/20659733/58314846-f7f27180-7e2d-11e9-9c9b-2c844a6f848a.png)

This may be a Documentation issue.

**Comment by laurentopia** [comment]
Oh I get it, my expectations != the programmer's intention.
Verbose = 3 : displays en Epoch counter and a progress-bar for the entire training is what I am looking for.

The progress bar doesn't update in VS Code.

**Comment by ymodak** [comment]
Thanks for sharing your findings. Closing this issue since its resolved. Thanks!

**Comment by JEM-Mosig** [comment]
In TF 2.9.1 this is still an issue. E.g. for `verbose=3` I don't get any progress bar, just one print per epoch:
![image](https://user-images.githubusercontent.com/31377126/187019641-98efbe1a-86d1-4b69-9907-d40f78cc5b6e.png)

At the very least, the documentation should be fixed. Ideally, one verbosity level would print a progress bar for the entire training, so I have an indication of how far in it is without printing one line for each of 10k epochs.

**Comment by adamvvu** [comment]
@JEM-Mosig This is late but it can be done easily with callbacks. I was looking for a way too and decided to just code up a quick library [here](https://github.com/adamvvu/tf_compactprogbar)
