### ISSUE TITLE
Issue: Python int too large to convert to C long

### ISSUE THREAD

**Issue by AbbasiAYE** [keras-team/keras#12867]
Hello

I'm having this issue when fitting the system, any help is appreciated.
In the below code, I use both federated model and normal keras model to fit and evaluate the sequential NN. The error occurs when fitting or evaluating the keras single model (not federated) at:
1. trained_local_Model = Local_model.fit(XTrain,YTrain) #tbuc
2. Local_model_Fed_evaluated = Local_model_Fed.evaluate(XTrain, YTrain)

=====================================================
Code:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
import collections
import pandas as pd
from six.moves import range
import tensorflow as tf
import tensorflow_federated as tff
import numpy as np
import os
import Import_Pickle
from tensorflow.python.keras.optimizer_v2 import gradient_descent

tf.compat.v1.enable_v2_behavior()

TobeRemoved_Array = ['TX/CSI_RX/Channel Quality Indicator', 'core', 'epoch', 'TX/CSI_RX/Efficiency', 'TX/CSI_RX/Estimated Freq Error', 'TX/CSI_RX/Estimated Time Error', 'TX/CSI_RX/Precoding Matrix Indicator', 'TX/CSI_RX/Rank Indicator', 'log', 'BeamRSRP_max', 'CQI_max', 'gpsTime_float', 'BeamRSRP_max_Normazlied', 'is_training']

train_perc = 0.8
Norm_Input  = True
Norm_Output = False
Input_str  = ['latitude', 'longitude']
if Norm_Output:
    Output_str = ['BeamRSRP_max_Normazlied']
else: 
    Output_str = ['BeamRSRP_max']

##############################################
dir_name = 'pickle-data/'
file_name = 'all_logs_april_2019.pickle'
files = os.listdir('pickle-data/')
dataframe = Import_Pickle.Import_v1(dir_name,file_name,False) # choose False to use 2019 data
ave = dataframe.core.min() + 100000
df2 = dataframe[dataframe.core < ave]
df = Import_Pickle.PreProcessing_v2019(df2,Norm_Input)
train_df,test_df,X_traindf,X_testdf,Y_traindf,Y_testdf,XY_traindf,XY_testdf = Import_Pickle.Splitting_Train_Test(df,train_perc,Norm_Output,TobeRemoved_Array)
########## splitting for clients ############  
def Tag_per_day(train_df_loc,TagNum):
    train_df_loc['log2'] =  train_df_loc['log'].apply(lambda x: x.replace("_",""))
    tag_Index = train_df_loc.log2.apply(lambda x: x.index("201"))
    tag_Index2 = tag_Index.values[1]
    tag_date =train_df_loc.log2.apply(lambda x: x[tag_Index2:tag_Index2+8])
    train_df_loc.loc[:,'Tag'+str(TagNum)] = pd.Series(tag_date.to_list(),index=train_df.index)  # to be fixed
    return train_df_loc

# Introduce time as input
X_traindf['gpsTime_float'] = train_df['gpsTime_float']
# introduce first tag per day
TagNum=1
train_df = Tag_per_day(train_df,TagNum)
#examples on groupby
Unq_tag1_grps = list(train_df.groupby(train_df.Tag1).groups.keys())
train_df.groupby(train_df.Tag1).first()
train_df.groupby(train_df.Tag1)['gpsTime_float'].count()
X_traindf['Tag'+str(TagNum)] =  train_df['Tag'+str(TagNum)]
#############################
# introduce epoch as tag
#############################
TagNum=2
train_df['Tag'+str(TagNum)] = train_df.epoch
X_traindf['Tag'+str(TagNum)] =  train_df['Tag'+str(TagNum)]
#############################
# introduce core as tag
#############################
TagNum=3
train_df['Tag'+str(TagNum)] = train_df.core
X_traindf['Tag'+str(TagNum)] =  train_df['Tag'+str(TagNum)]
#############################
# introduce day as tag per client
#############################
TagNum = 4
Num_Clients = 10 # cannot be less than one
Num_Cons_Sample_Client = 5 # cannot be less than one
RepNum = np.ceil(train_df.shape[0]/(Num_Cons_Sample_Client*Num_Clients))
Part_Tag_Array=[]
for i in np.arange(Num_Clients):
    Part_Tag_Tmp = list(map(lambda _: i+1,range(Num_Cons_Sample_Client)))
    Part_Tag_Array.extend(Part_Tag_Tmp)

Full_Tag_Array2 = Part_Tag_Array * int(RepNum)
extra_tags = np.abs(len(Full_Tag_Array2) - train_df.shape[0])
Full_Tag_Array = Full_Tag_Array2[:-extra_tags]
train_df.loc[:,'Tag'+str(TagNum)] = pd.Series(Full_Tag_Array,index=train_df.index)
X_traindf.loc[:,'Tag'+str(TagNum)] = train_df['Tag'+str(TagNum)]
#############################
# END day as tag per client
#############################
Input_str.extend(['gpsTime_float','Tag4'])
################################################################
Act_Inputs  = tf.cast(tf.convert_to_tensor(X_traindf[Input_str].values),tf.float32)
Act_Outputs = tf.cast(tf.convert_to_tensor(Y_traindf[Output_str].values),tf.float32)

new_batch = collections.OrderedDict([('In', Act_Inputs),('Out', Act_Outputs)])
dataset_input = tf.data.Dataset.from_tensor_slices(new_batch)#,,maxval=100, dtype=tf.float32)
dataset2 = dataset_input
# Select among the datasets
Used_dataset= dataset2

#with eager_mode():

def client_data(new_dataset):
    #return Used_dataset.repeat(2).batch(2)
    def map_fn(elem):
        return collections.OrderedDict([('x', tf.reshape(elem['In'], [-1])),('y', tf.reshape(elem['Out'],[1]))])
    
    DS2= new_dataset.map(map_fn,num_parallel_calls=None)
    
    return DS2.repeat(20).batch(10)

train_data = [client_data(Used_dataset)]

sample_batch = tf.contrib.framework.nest.map_structure(lambda x: x.numpy(), next(iter(train_data[0])))
    
########## END Changes ############            
learning_rate = 1

def create_SK_model():
    modelF = tf.keras.Sequential([tf.keras.layers.Flatten(input_shape=(Act_Inputs.shape[1],)),
                                 tf.keras.layers.Dense(10, activation=tf.nn.relu, kernel_initializer='zeros'),
                                 tf.keras.layers.Dense(1, activation=tf.nn.relu, kernel_initializer='zeros'),
                                 ])
    return modelF

def loss_fn(y_true, y_pred):
    return tf.reduce_mean(tf.keras.losses.MSE(y_true, y_pred))

def model_fn():
    return tff.learning.from_keras_model(create_SK_model(), 
                                         sample_batch, loss=loss_fn, 
                                         optimizer=gradient_descent.SGD(0.1))

YTrain = Act_Outputs #np.random.rand(50,1)
XTrain = Act_Inputs  #np.random.rand(50,100)
# locally compile the model
Local_model = create_SK_model()
Local_model.compile(loss=loss_fn,optimizer=gradient_descent.SGD(learning_rate))
# fitting without federated learning
trained_local_Model = Local_model.fit(XTrain,YTrain) #tbuc
# training/fitting with TF federated learning
trainer_Itr_Process = tff.learning.build_federated_averaging_process(model_fn,server_optimizer_fn=(lambda : gradient_descent.SGD(learning_rate=1.0)),client_weight_fn=None)
FLstate = trainer_Itr_Process.initialize()
FLlosses  = []
# Track loss of different ...... of federated iteration
for round_num in range(1, 3):
    FLstate, FLoutputs = trainer_Itr_Process.next(FLstate, train_data)
    print('round {:2d}, metrics={}'.format(round_num, FLoutputs))
    # Track the loss.
    FLlosses.append(FLoutputs.loss)

# Loss of local model
local_Loss = trained_local_Model.history['loss'] # tbuc
print(local_Loss)
# Copy local model for comparison purposes
Local_model_Fed = Local_model
# Setting federated weights on copied Object of local model
Local_model_Fed.set_weights(tff.learning.keras_weights_from_tff_weights(FLstate.model))
# Evaluate loss of the copied federated weights on local model
Local_model_Fed_evaluated = Local_model_Fed.evaluate(XTrain, YTrain)
print(Local_model_Fed_evaluated )
print('End')

**Error Trace:**
WARNING:tensorflow:From C:\Program Files\Python36\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
2019-05-24 10:43:31.419098: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at strided_slice_op.cc:106 : Invalid argument: Expected begin, end, and strides to be 1D equal size tensors, but got shapes [32], [32], and [32] instead.
Traceback (most recent call last):
  File "C:\Users\ezalaab\.p2\pool\plugins\org.python.pydev.core_7.1.0.201902031515\pysrc\pydevd.py", line 2225, in <module>
    main()
  File "C:\Users\ezalaab\.p2\pool\plugins\org.python.pydev.core_7.1.0.201902031515\pysrc\pydevd.py", line 2218, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Users\ezalaab\.p2\pool\plugins\org.python.pydev.core_7.1.0.201902031515\pysrc\pydevd.py", line 1560, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "C:\Users\ezalaab\.p2\pool\plugins\org.python.pydev.core_7.1.0.201902031515\pysrc\pydevd.py", line 1567, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Users\ezalaab\.p2\pool\plugins\org.python.pydev.core_7.1.0.201902031515\pysrc\_pydev_imps\_pydev_execfile.py", line 25, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\ezalaab\Documents\eclipse-workspace\MANA-FederatedLearning\location-based-federated-learning\Test\FederatedLearningTFv2.py", line 204, in <module>
    trained_local_Model = Local_model.fit(XTrain,YTrain) #tbuc
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\engine\training.py", line 880, in fit
    validation_steps=validation_steps)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\engine\training_arrays.py", line 310, in model_iteration
    ins_batch = slice_arrays(ins[:-1], batch_ids) + [ins[-1]]
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 526, in slice_arrays
    return [None if x is None else x[start] for x in arrays]
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 526, in <listcomp>
    return [None if x is None else x[start] for x in arrays]
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\ops\array_ops.py", line 654, in _slice_helper
    name=name)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\ops\array_ops.py", line 820, in strided_slice
    shrink_axis_mask=shrink_axis_mask)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 11328, in strided_slice
    shrink_axis_mask)
OverflowError: Python int too large to convert to C long

**Comment by dorian821** [comment]
I'm experiencing this issue as well when I don't provide an argument for 'validation_split' in the model.fit method. fit works fine as long as I provide a value for validation_split. 

using:

Tensorflow  2.0.0beta1
Windows 7
Cuda 10.0
Cudnn 7.5
