### ISSUE TITLE
Is there an implementation of Memory-Efficient Implementation of DenseNets on Keras ?

### ISSUE THREAD

**Issue by adelabdelli** [keras-team/keras#12873]
I am looking for an implementation for  Memory-Efficient Implementation of DenseNets on Keras, i found the DenseNet implementation, but the  Memory-Efficient Implementation of DenseNets on Keras i didn't, for details about  Memory-Efficient Implementation of DenseNets on Keras, you will find them in the original paper here: https://arxiv.org/abs/1707.06990

**Comment by Ordgod** [comment]
I also looking for an implementation on keras. The original paper provided its implementations on PyTorch, MXNet, Torch, Caffe. I hope anyone who are interested in this technique can help to implement this technique on keras. Thanks.

**Comment by Ordgod** [comment]
https://github.com/joeyearsley/efficient_densenet_tensorflow

@adelabdelli This repo is a implementation on tensorflow. Hope it can help.
