### ISSUE TITLE
Run Default code for imdb_cnn.py it gives pickle-errors

### ISSUE THREAD

**Issue by EngrStudent** [keras-team/keras#12897]
<em>Please make sure that this is a Bug or a Feature Request and provide all applicable information asked by the template.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.</em>  

**System information**  
- Have I written custom code (as opposed to using example directory):  
>> I used the default code exactly as written.

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  
Microsoft Windows 10 Enterprise

- TensorFlow backend (yes / no): 
yes
 
- TensorFlow version:  
1.13.1

- Keras version:  
2.2.4

- Python version:  
Python 3.7.3

- CUDA/cuDNN version:  
None.  I'm using cpu-only vanilla keras installed by Anaconda. 

- GPU model and memory:  
NVidia Quadra P1000

**Describe the current behavior**  
It crashes when I hit F5 in Spyder.  It talks about pickle error.

```
using TensorFlow backend.
Loading data...
Traceback (most recent call last):

  File "<ipython-input-1-4a5d5f4a1034>", line 1, in <module>
    runfile('C:/work/imdb_cnn.py', wdir='c:/work')

  File "C:\ProgramData\Anaconda3\envs\Step2\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData\Anaconda3\envs\Step2\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/work/imdb_cnn.py", line 28, in <module>
    (x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=max_features)

  File "C:\ProgramData\Anaconda3\envs\Step2\lib\site-packages\keras\datasets\imdb.py", line 59, in load_data
    x_train, labels_train = f['x_train'], f['y_train']

  File "C:\ProgramData\Anaconda3\envs\Step2\lib\site-packages\numpy\lib\npyio.py", line 262, in __getitem__
    pickle_kwargs=self.pickle_kwargs)

  File "C:\ProgramData\Anaconda3\envs\Step2\lib\site-packages\numpy\lib\format.py", line 692, in read_array
    raise ValueError("Object arrays cannot be loaded when "

ValueError: Object arrays cannot be loaded when allow_pickle=False
```

**Describe the expected behavior**  

I would expect it to get to line 29 and print something about the training sequence count.

Line 28, where it is choking, is 
`(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=max_features)`

It doesn't get to print "train sequences" after attempting to load data, so it isn't getting past line 29.  

When I re-select line 28, and hit F9 (run highlighted) it gives the same error again.

**Code to reproduce the issue**  
You already have it.  It was literally copy-paste-run-crash

**Other info / logs**  
Traceback is included in what it did.

**Comment by ymodak** [comment]
This is [bug](https://github.com/numpy/numpy/pull/13359) with numpy 1.16.3 where allow_pickle=False. For the time being can you please downgrade your numpy version to 1.16.2 . This should execute the script successfully.
``` pip install numpy==1.16.2```
