### ISSUE TITLE
Mistake in convLSTM2D default activation documentation

### ISSUE THREAD

**Issue by asherRSIP** [keras-team/keras#12890]
In the Keras documentation, it says about the convLSTM2D activation parameter:

activation: Activation function to use (see activations). If you don't specify anything, no activation is applied (ie. "linear" activation: a(x) = x).

but in the code I see that the default activation is NOT linear:
activation='tanh'

**Comment by abhinavsagar** [comment]
I think tanh is the default. @fchollet Should we change the docs informing the same ?

**Comment by Kumar-Tarun** [comment]
@asherRSIP @abhinavsagar There are two places with the documentation saying a linear activation function, but code having default activation as 'tanh' :

- [In ConvLSTM2DCell class](https://github.com/keras-team/keras/blob/eab1b5bcdf105746ede02d2eb8a5cb3ca359b1b5/keras/layers/convolutional_recurrent.py#L494)

- [In ConvLSTM2D class](https://github.com/keras-team/keras/blob/eab1b5bcdf105746ede02d2eb8a5cb3ca359b1b5/keras/layers/convolutional_recurrent.py#L820) as pointed by @asherRSIP .

**Comment by mani2106** [comment]
Can I work on this by adding
` By default "tanh" activation is  applied, `
`which is:  tanh(x) = (exp(x) - exp(-x)) / (exp(x) + exp(-x))`
