### ISSUE TITLE
Embedding layer input should be floats

### ISSUE THREAD

**Issue by tiferet** [keras-team/keras#12914]
The [documentation for the embedding layer](https://keras.io/layers/embeddings/) specifies that the input should be an integer matrix. While the inputs should in fact be indices into the vocabulary (non-negative integers), they need to be cast as floats. If an integer-type matrix is input, the training does not work right, without ever giving an error, which is very hard to debug.

Suggestions:
- At minimum, update the documentation to specify that the input should be round numbers cast as floats.
- Maybe also check the input for this and all other layers and raise an error if the type is wrong.
- Maybe cast the inputs to floats within the `fit`, `predict`, and other relevant functions.

I may be able to try taking a stab at this, if you tell me which option you prefer. Thanks!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by abhinavsagar** [comment]
I think we should go for a documentation update. Feel free to open a PR regarding this.

**Comment by shegokarm** [comment]
Hi there, I am beginner here and would like to work on this issue. Just to clarify I'd need to update the doc, right?

**Comment by vineetred** [comment]
Hey! I've added the necessary information in the docs. Do let me know if the PR can be merged. #13011

**Comment by ashnakapoor07** [comment]
Can I take this as my first issue?
