### ISSUE TITLE
How to run keras model in java

### ISSUE THREAD

**Issue by Arpit-Mittal** [keras-team/keras#12921]
This is python model which is working good in python:
 
https://github.com/keras-team/keras/tree/master/examples
 
lstm_seq2seq.py Trains a basic character-level sequence-to-sequence model.
lstm_seq2seq_restore.py Restores a character-level sequence to sequence model from disk (saved by lstm_seq2seq.py) and uses it to generate predictions.

Do you know if there is way to convert to java?

**Comment by ymodak** [comment]
Hi!
This issue isn't related to a bug/enhancement/feature request or other accepted types of issue.
To ask questions, please see the following resources :
[StackOverflow](http://stackoverflow.com/questions/tagged/keras)
[Keras Slack channel](https://keras-slack-autojoin.herokuapp.com)
[Keras.io support](https://keras.io/#support)
[Gitter](https://gitter.im/Keras-io/Lobby)
Thanks!
If you think we made a mistake, please open another issue explaining your request in detail.
