### ISSUE TITLE
Can flow method in ImageDataGenerator also support autoencoder?

### ISSUE THREAD

**Issue by yourtheron** [keras-team/keras#12938]
@rodgzilla 
Relating to #6510 
While there is a class_model=input for autoencoder in flow_from_directory method, I am using
flow method, because in my case the training data are only part of a directory. My code snippet is

DataGen = ImageDataGenerator(featurewise_center=True, 
                             featurewise_std_normalization=True,
                             samplewise_center = False,
                             samplewise_std_normalizatio = False)
DataGen.fit(CurData)
self.autoencoder.fit_generator(DataGen.flow(CurData, CurData, batch_size=CurBatchSize), 
                               steps_per_epoch=len(CurData)/CurBatchSize, 
                               epochs=CurEpoch,
                               callbacks=CurCallbacks)

Could model=input option be also added to flow method? Or has flow method been suitable for autoencoder already without need to specify anything extra?

Thanks!

**Comment by stephenbaek** [comment]
I agree. I was wondering the same thing. `class_mode=input` option would be very helpful. Anyone working on this issue?

**Comment by leleogere** [comment]
Has this been implemented? The issue was closed as completed but I can't find the implementation

**Comment by Victorivus** [comment]
Up @leleogere

**Comment by leleogere** [comment]
I can't remember why I needed that, but I guess I did not have the last version of keras installed so I could not find it.
