### ISSUE TITLE
Kears use float16 failed to train Keras Model

### ISSUE THREAD

**Issue by yourtheron** [keras-team/keras#12947]
<em>Please make sure that this is a Bug or a Feature Request and provide all applicable information asked by the template.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.</em>  

**System information**  
- Have I written custom code (as opposed to using example directory):  no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Windows 7
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  1.13.1
- Keras version:  2.2.4
- Python version:  3.7
- CUDA/cuDNN version:  10.1
- GPU model and memory:  Quadro K620M 2048MB

You can obtain the TensorFlow version with:  
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"  
You can obtain the Keras version with:  
python -c 'import keras as k; print(k.__version__)'  

**Describe the current behavior**  
When I try to fit the model, which is an autoencoder. The following error occurs:
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor of shape [] and type int64
         [[{{node training_1/Adadelta/AssignAdd/value}}]]
I restarted python (I use conda) to run it again. This time, the following error occurs:
 File "D:\TProgramFiles\Anaconda3\envs\keras-gpu\lib\site-packages\keras\engine\training.py", line 1010, in fit
    self._make_train_function()

  File "D:\TProgramFiles\Anaconda3\envs\keras-gpu\lib\site-packages\keras\engine\training.py", line 509, in _make_train_function
    loss=self.total_loss)

  File "D:\TProgramFiles\Anaconda3\envs\keras-gpu\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)

  File "D:\TProgramFiles\Anaconda3\envs\keras-gpu\lib\site-packages\keras\optimizers.py", line 414, in get_updates
    new_p = p - lr * update

  File "D:\TProgramFiles\Anaconda3\envs\keras-gpu\lib\site-packages\tensorflow\python\ops\variables.py", line 935, in _run_op
    return tensor_oper(a.value(), *args, **kwargs)

  File "D:\TProgramFiles\Anaconda3\envs\keras-gpu\lib\site-packages\tensorflow\python\ops\math_ops.py", line 812, in binary_op_wrapper
    return func(x, y, name=name)

  File "D:\TProgramFiles\Anaconda3\envs\keras-gpu\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1078, in _mul_dispatch
    return gen_math_ops.mul(x, y, name=name)

  File "D:\TProgramFiles\Anaconda3\envs\keras-gpu\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 5860, in mul
    "Mul", x=x, y=y, name=name)

  File "D:\TProgramFiles\Anaconda3\envs\keras-gpu\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 547, in _apply_op_helper
    inferred_from[input_arg.type_attr]))

TypeError: Input 'y' of 'Mul' Op has type float16 that does not match type float32 of argument 'x'.

**Describe the expected behavior**  
When I used float32 data to run the same code, there was no such issue
**Code to reproduce the issue**  
        K.set_floatx('float16')
        K.set_epsilon(1e-4)
        self.autoencoder.compile(loss=CurLoss, optimizer= CurOptimizer, metrics=CurMetrics)
		# CurData is a [1, 128, 128, 1] float16 numpy nd array
        self.autoencoder.fit(CurData, CurData, 
                             epochs=CurEpoch, 
                             batch_size=CurBatchSize, 
                             callbacks=CurCallbacks) 

**Other info / logs**  
See above, please.

**Comment by jvishnuvardhan** [comment]
@yourtheron Can you provide a standalone code to reproduce the issue? Thanks!

**Comment by yourtheron** [comment]
@jvishnuvardhan Sure. Could you please offer me a mailbox? I do not intend to publish the code here. I am certain you understand the reason.

**Comment by jvishnuvardhan** [comment]
@yourtheron can you use any public data like `mnist` or other to make a toy example so that it will be helpful to others as well. Another reason is that if I am unable to resolve, then I need to share things with other team members which is not what you want with your private data. Thanks!

**Comment by yourtheron** [comment]
@jvishnuvardhan OK, let me try to provide a simplified version of code here. A new phenomenon is that sometimes it can be run, sometimes it cannot. The issue cannot be reproduced every time. Thank you for your help in advance.
I am highly suspicious that it might be caused by insufficient memory, but I do not understand why it can be run sometimes if memory is not enough.

Here is the code, just a simple stack autoencoder

`'''
ArraySize = [128, 128], 
ConvFilters = [16, 32, 48]
KernelSize = [3, 3, 3]
stride = [1, 1, 1]
DenseLayerDims = [ 2048, 16], 
activation = 'relu'
optimizer = optimizers.Adadelta(lr=1.0, rho=0.95, epsilon=None, decay=0.0)
regulariser = None
Input to autoencoder is sized [n, ArraySize[0], ArraySize[1], 1]

Those dictroies in the code are but places storing data, results, and coder's configurations, if any.

'''
from keras.layers import Activation, Dense, Input
from keras.layers import Conv2D, Flatten
from keras.layers import Reshape, Conv2DTranspose
from keras.initializers import glorot_normal, RandomNormal
from keras.models import Model
from keras import backend as K
from keras import optimizers
from keras import regularizers
from keras.callbacks import EarlyStopping
from keras.callbacks import ModelCheckpoint

    def BuildCoder(self, AvailableCoder = None, CurRegulariser = None):
        
        K.set_floatx('float16')
        K.set_epsilon(1e-4)
        
        if AvailableCoder == None:
            # Encoder
            InShape = (self.ArraySize[0], self.ArraySize[1], 1)
            EncoderInput = Input(shape=InShape, name='Encoder_Input')
            x = EncoderInput
            i = 0
            for CurFilter, CurKernelSize, CurStride, in zip(self.ConvFilters, self.KernelSize, self.stride):
                CurLayerName = 'Conv2D_' + str(i)
                x = Conv2D(filters=CurFilter,
                           kernel_size=CurKernelSize,
                           strides=CurStride,
                           kernel_regularizer= CurRegulariser,
                           activation=self.activation,
                           padding='same',
                           name = CurLayerName)(x)
                i += 1
                
            self.shape = K.int_shape(x)
            x = Flatten(name='Flatten_Tensor')(x)
            
            i = 0
            for DenseLayerDim in self.DenseLayerDims:
                CurLayerName = 'Dense_Encoder_' + str(i)
                x = Dense(DenseLayerDim,
                          activation='relu',
                          kernel_initializer = 'glorot_normal',
                          bias_initializer = RandomNormal(mean=0.0, stddev=1.0),
                          kernel_regularizer= CurRegulariser,
                          name = CurLayerName)(x)
                i += 1
            
            latent = x  
            self.encoder = Model(EncoderInput, latent, name='Encoder')
            self.encoder.summary()
            
            # Decoder
            LatentInput = Input(shape=(self.DenseLayerDims[-1],), name='Decoder_Input')
            # The middle hidden layer needs not to be involved
            i = 0
            ListDenseDim = self.DenseLayerDims[0:-1]
            ListDenseDim = ListDenseDim[::-1]
            ListDenseDim.append(self.shape[1] * self.shape[2] * self.shape[3])
            x = LatentInput
            for DenseLayerDim in ListDenseDim:
                CurLayerName = 'Dense_Decoder_' + str(i)
                x = Dense(DenseLayerDim,
                          activation='relu',
                          kernel_initializer = 'glorot_normal',
                          bias_initializer = RandomNormal(mean=0.0, stddev=1.0),
                          kernel_regularizer= CurRegulariser,
                          name = CurLayerName)(x)
                i += 1            

            x = Reshape((self.shape[1], self.shape[2], self.shape[3]), name='Construct_Tensor')(x)
            i = 0
            for CurFilter, CurKernelSize, CurStride, in zip(self.ConvFilters[::-1], self.KernelSize[::-1], self.stride[::-1]):
                CurLayerName = 'Conv2DTranspose_' + str(i)
                x = Conv2DTranspose(filters=CurFilter,
                                    kernel_size=CurKernelSize,
                                    strides=CurStride,
                                    kernel_regularizer= CurRegulariser,
                                    activation=self.activation,
                                    padding='same',
                                    name = CurLayerName)(x)
                i += 1
            x = Conv2DTranspose(filters=1,
                    kernel_size=self.KernelSize[0],
                    kernel_regularizer= CurRegulariser,
                    padding='same',
                    name = 'Conv2DTranspsze_Last')(x)    
            DecoderOutput = Activation('sigmoid', name='Decoder_output')(x)
            self.decoder = Model(LatentInput, DecoderOutput, name='Decoder')
            self.decoder.summary()
            # Autoencoder
            self.autoencoder = Model(EncoderInput, self.decoder(self.encoder(EncoderInput)), name='autoencoder')
            self.autoencoder.summary()
            print('Coders have been established. Please wait for training to commence...\n')
        else:
            # Perform transfer learning
            self.autoencoder = Model.from_config(AvailableCoder[0][0])
            self.encoder = Model.from_config(AvailableCoder[0][1])
            self.decoder = Model.from_config(AvailableCoder[0][2])
            self.autoencoder.set_weights(AvailableCoder[1][0])
            self.encoder.set_weights(AvailableCoder[1][1])
            self.decoder.set_weights(AvailableCoder[1][2])
            print('Configurations and weights have been transferred. Please wait for training to commence...\n')
            
        # Compute number of params in a model (the actual number of float16) and return them
        return np.asarray([sum([np.prod(K.get_value(w).shape) for w in self.autoencoder.trainable_weights]), 
                           sum([np.prod(K.get_value(w).shape) for w in self.encoder.trainable_weights]), 
                           sum([np.prod(K.get_value(w).shape) for w in self.decoder.trainable_weights])])
    
    
    def TrainCoder(self, ReadFileRange = [0, 1], CurEpoch = 30, CurBatchSize = 100,
                   CurLoss = 'mse', CurOptimizer = 'adam', CurMetrics=['accuracy'], CurCallbacks = None):
        CurData = self.FeedEncoderSeq(ReadFileRange)
        K.set_floatx('float16')
        K.set_epsilon(1e-4)
        self.autoencoder.compile(loss=CurLoss, optimizer= CurOptimizer, metrics=CurMetrics)
        self.autoencoder.fit(CurData, CurData, 
                             #validation_data=(CurData, CurData), 
                             epochs=CurEpoch, 
                             batch_size=CurBatchSize, 
                             callbacks=CurCallbacks)
           
        self.autoencoder.save(self.FilePath + '\\Coder\\'+ '\\Autoencoder\\AutoEncoder_' + str(ReadFileRange[0]) + '.h5')
        self.encoder.set_weights(self.autoencoder.layers[1].get_weights())
        self.encoder.save(self.FilePath + '\\Coder\\'+ '\\Encoder\\Encoder_'+ str(ReadFileRange[0]) + '.h5')
        self.decoder.set_weights(self.autoencoder.layers[2].get_weights())
        self.decoder.save(self.FilePath + '\\Coder\\'+ '\\Decoder\\Decoder_'+ str(ReadFileRange[0]) + '.h5')
        print('Coders have been trained\n')

        config0 = self.autoencoder.get_config()
        weight0 = self.autoencoder.get_weights()
        config1 = self.encoder.get_config()
        weight1 = self.encoder.get_weights()
        config2 = self.decoder.get_config()
        weight2 = self.decoder.get_weights()
        
        return [[config0, config1, config2], [weight0, weight1, weight2]]
    
    def InferEncoder(self, ReadFileRange = [0, 1]):
        K.set_floatx('float16')
        K.set_epsilon(1e-4)
        CurData = self.FeedEncoderSeq(ReadFileRange)
        self.StoreEncoderSeq(self.encoder.predict(CurData), ReadFileRange[0])
    
    def InferDecoder(self, ReadFileRange = [0, 1]):
        K.set_floatx('float16')
        K.set_epsilon(1e-4)
        CurData = self.FeedDecoderSeq(ReadFileRange)
        return self.StoreDecoderSeq(self.decoder.predict(CurData), ReadFileRange[0])

            
            `

**Comment by yourtheron** [comment]
@jvishnuvardhan Additional information: even I discard Conv2D-related layers, and use Dense layers with [2048 128] architecture, the same problem happens. Yet if I reduced number of neurons to, say, [200 128], it can be run. So probably it might really be caused by incapacity of my GPU, I surmise.

**Comment by yourtheron** [comment]
@jvishnuvardhan Updated debug info. Even if I use float32 now, the following errors occurs sometimes: 
` File "D:\TProgramFiles\Anaconda3\envs\keras-gpu\lib\site-packages\keras\engine\training.py", line 1039, in fit
    validation_steps=validation_steps)

  File "D:\TProgramFiles\Anaconda3\envs\keras-gpu\lib\site-packages\keras\engine\training_arrays.py", line 199, in fit_loop
    outs = f(ins_batch)

  File "D:\TProgramFiles\Anaconda3\envs\keras-gpu\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)

  File "D:\TProgramFiles\Anaconda3\envs\keras-gpu\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)

  File "D:\TProgramFiles\Anaconda3\envs\keras-gpu\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
    run_metadata_ptr)
ResourceExhaustedError: OOM when allocating tensor with shape[] and type int32 on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node Encoder_2/Flatten_Tensor/Prod}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[{{node loss_2/mul}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.`
