### ISSUE TITLE
Bug: ValueError: An operation has `None` for gradient.

### ISSUE THREAD

**Issue by Andrea-V** [keras-team/keras#12955]
<em>Please make sure that this is a Bug or a Feature Request and provide all applicable information asked by the template.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.</em>  

**System information**   
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04  
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  1.12.0
- Keras version:  2.2.4
- Python version: 3.6
- CUDA/cuDNN version:  9.2
- GPU model and memory:  nVidia GTX360

**Describe the current behavior**  
When I call train_on_batch on my model, i receive the error: 

```
sup_loss = self.supervised_phase.train_on_batch(X, label)
  File "/home/xxx/anaconda3/envs/mygan/lib/python3.6/site-packages/keras/engine/training.py", line 1216, in train_on_batch
    self._make_train_function()
  File "/home/xxx/anaconda3/envs/mygan/lib/python3.6/site-packages/keras/engine/training.py", line 509, in _make_train_function
    loss=self.total_loss)
  File "/home/xxx/anaconda3/envs/mygan/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/xxx/anaconda3/envs/mygan/lib/python3.6/site-packages/keras/optimizers.py", line 475, in get_updates
    grads = self.get_gradients(loss, params)
  File "/home/xxx/anaconda3/envs/mygan/lib/python3.6/site-packages/keras/optimizers.py", line 91, in get_gradients
    raise ValueError('An operation has `None` for gradient. '
ValueError: An operation has `None` for gradient. Please make sure that all of your ops have a gradient defined (i.e. are differentiable). Common ops without gradient: K.argmax, K.round, K.eval.

```

**Describe the expected behavior**  
I expect the training to proceed with no errors.

**Code to reproduce the issue**  

```
X = Input(shape=(self.phrase_size, self.n_cropped_notes, self.n_tracks), name="X")

s_pred, _  = self.encoder(X)

self.supervised_phase = Model(
			inputs=X,
			outputs=s_pred,
			name="supervised_phase"
		)
		self.supervised_phase.compile(
			loss="binary_crossentropy",
			loss_weights=[self.supervised_weight],
			optimizer=self.aae_optim,
			metrics=["binary_accuracy"]
		)

sup_loss = self.supervised_phase.train_on_batch(X, label)
```

**Other info**  
I'm sure that self.encoder only contains differentiable operations, because I use it as part of other subgraphs that I can train without problems, I only get the error while trying to train self.supervised_phase.

**Comment by tux-o-matic** [comment]
See same thing on Keras 2.2.4 with TF 1.13.1. Downgrading to Keras 2.2.0 and TF 1.8.0 my code works.

**Comment by S-Saran** [comment]
@wilderrodrigues Hi there, did you manage to find a solution in the end?
I'm having the same issue when trying to get gradient values for interpretablity of the model.
my environment: 

- CentOS Linux 7 (Core) 
- Nvidia Driver Version: 418.87.00    CUDA Version: 10.1 
- Python 3.7.4
- Tensorflow 2.0.0 
- Keras 2.3.1 

Any ideas?

**Comment by alokssingh** [comment]
@wilderrodrigues Hi there, did you find any solution.
For some architecture my code is working but when I am using Dense layer I have encountered same problem.

**Comment by jaswanthbjk** [comment]
@wilderrodrigues  @sepidehsaran  @alokssingh @Andrea-V  
Did any of you find the reason for this issue ?

[https://github.com/keras-team/keras/issues/12521](here) the suggestion is to look for unused weights. My model has 1.8 million parameters. 

Do you know of any method to check for unused weights ?

**Comment by wilderrodrigues** [comment]
Hey folks,

Wow, sorry for being away that long. I completely forgot to track this one. :( 

I will try to reproduce it this week and come back to you. I have been using TF 2 for a year already. But I can try going back to Keras + TF 1.13 to see how it behaves.
