### ISSUE TITLE
Memory leak in Keras: Functions Clone_model() and Set_Weights() become slower and slower when used in loop

### ISSUE THREAD

**Issue by Dandy-John** [keras-team/keras#12956]
### Configuration

| Library                        | Version  |
| ------------------------------ | -------- |
| pyhton                         | 3.6.8    |
| GCC                            | 7.3.0    |
| tensorflow-base/tensorflow-gpu | 1.13.1   |
| keras-gpu/keras-base           | 2.2.4    |
| theano                         | 1.0.4    |
| cudnn                          | 7.6.0    |
| cudatoolkit                    | 10.0.130 |

Machine Configuration：

Ubuntu 18.04.2 LTS

Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz 128GB RAM

CUDA Version: 10.2 

Double GeForce GTX 1080ti 

---

### Description

I use `keras.models.clone_model()` to clone the resnet50 model and use `set_weights()`  to set the weights for each layer. But I find that the time consumption for each iteration becomes much larger as time goes by. At the first iteration, the clone stage takes about 4 seconds and the setting-weights stage takes about 3 seconds but those turn to be 34 seconds and 4 minutes at the 50th iteration. 

Is there a problem with my usage? Or would there be a memory leak in keras?

I hope to hear from you soon. Thanks in advance.

The code is shown as bellow:

```python
import keras
import sys
import datetime

def get_HH_mm_ss(td):
    days,seconds = td.days,td.seconds
    hours = days * 24 + seconds // 3600
    minutes = (seconds % 3600)//60
    secs = seconds % 60
    return hours,minutes,secs


loop_iter = int(sys.argv[1])
origin_resnet = keras.applications.resnet50.ResNet50(include_top=True, weights='imagenet', input_tensor=None, input_shape=None, pooling=None, classes=1000)

for i in range(loop_iter):
    print("Iteration {}".format(i))
    s = datetime.datetime.now()
    copy_model = keras.models.clone_model(origin_resnet)
    e1 = datetime.datetime.now()
    copy_model.set_weights(origin_resnet.get_weights())
    e2 = datetime.datetime.now()
    td_copy = e1 - s
    td_set_weights = e2 - e1
    h1, m1, s1 = get_HH_mm_ss(td_copy)
    print("Copy model: Time used: {} hour,{} min,{} sec".format(h1, m1, s1))
    h2, m2, s2 = get_HH_mm_ss(td_set_weights)
    print("Set weights: Time used: {} hour,{} min,{} sec".format(h2, m2, s2))

```

Here is partial result:

![image](https://user-images.githubusercontent.com/17698785/59478187-019a5280-8e8b-11e9-8901-3e01a0b9daa4.png)

![image](https://user-images.githubusercontent.com/17698785/59478193-08c16080-8e8b-11e9-9e83-a595c0fe2e35.png)

**Comment by changchend** [comment]
Keras may leak memory。 load_model,memory continues to grow
