### ISSUE TITLE
Error using class weight on contrastive loss

### ISSUE THREAD

**Issue by LucasToriello** [keras-team/keras#12973]
**System information**  
- Have I written custom code (as opposed to using example directory):  No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Windows/Linux/MacOS
- TensorFlow backend (yes / no):  Yes
- TensorFlow version:  1.13.1
- Keras version:  2.2.4
- Python version:  3.6

**Describe the current behavior**  
Using example ‘siamese_mnist.py’.

When adding class_weight to fit method, the option work only when the batch size is equal to 1.
The following error is being returned: 
« InvalidArgumentError: Can not squeeze dim[0], expected a dimension of 1, got 128. [[{{node loss/lambda_loss/Squeeze}}]] » 

**Describe the expected behavior**  
Weighted custom loss function is applying different weights on each classes. 

**Code to reproduce the issue**  
Code at ‘siamese_mnist’. 
Apply this modification : 

class_weight = dict(zip(range(10), [1]* 10)) 
model.fit(..., class_weight=class_weight,...)

**Comment by jvishnuvardhan** [comment]
@LucasToriello Please provide a standalone code to reproduce the issue. You could create a google colab gist and share or by other means. thanks!

**Comment by LucasToriello** [comment]
Thanks for your response! Please find the code with the resulting error at this Colab link : https://colab.research.google.com/drive/1aaDD1dXAld-Q_494lqcQFL89-xaeOYtj#scrollTo=NOm1adao3EDl

I also created a Gist : https://gist.github.com/LucasToriello/2cbd77410f66c974042ba4158e189cd2
