### ISSUE TITLE
Flops count?

### ISSUE THREAD

**Issue by world4jason** [keras-team/keras#12970]
is it any method to count floating-point operation with keras?

**Comment by happyprotean** [comment]
For keras pretrained model:
![image](https://user-images.githubusercontent.com/31753214/72030083-eed1ea00-32c2-11ea-91df-d229df3abd3e.png)

For self-defined model:
![image](https://user-images.githubusercontent.com/31753214/72030096-fdb89c80-32c2-11ea-9a3c-d2eb0e9b6eb2.png)
