### ISSUE TITLE
keras docs missing methods for Tokenizer class

### ISSUE THREAD

**Issue by hemantranvir** [keras-team/keras#12980]
After visiting https://keras.io/preprocessing/text/ , I cannot find explaination for fit_on_texts (and other methods) under Tokenizer class.
On the other hand if I visit Japanese docs https://keras.io/ja/preprocessing/text/ , I can find the class and the methods listed as expected.
Is it a bug or an expected behavior?

**Comment by pavithrasv** [comment]
@hemantranvir do you want to contribute to the docs? Please feel free to send a PR.

**Comment by hemantranvir** [comment]
@pavithrasv I just submitted a PR #13089 covering the issue above.

**Comment by pavithrasv** [comment]
Thank you for the PR!

**Comment by pavithrasv** [comment]
Thank you for the PR!
