### ISSUE TITLE
Embedding Layer Persistence

### ISSUE THREAD

**Issue by karthim** [keras-team/keras#12982]
I have a rookie question with respect to persisting model with embedding layers. When we persist the model using save or to_json method, does it save the vectors used in the embedding layer?. 

If it is not saving the vectors used for the embedding layer, can someone point to a resource that will help me to add embedding layer to a model that is loaded from a file?

Thanks

**Comment by ymodak** [comment]
Hi!
This issue isn't related to a bug/enhancement/feature request or other accepted types of issue.
To ask questions, please see the following resources :
[StackOverflow](http://stackoverflow.com/questions/tagged/keras)
[Keras Slack channel](https://keras-slack-autojoin.herokuapp.com)
[Keras.io support](https://keras.io/#support)
[Gitter](https://gitter.im/Keras-io/Lobby)
Thanks!
If you think we made a mistake, please open another issue explaining your request in detail
