### ISSUE TITLE
How to Obtain Layer Output of Nested Model in Keras

### ISSUE THREAD

**Issue by kaushik88** [keras-team/keras#12986]
Does Keras provide a way to get the output of a nested model? Or is there a way to flatten the nested model? 
```
x2 = layer1(x1, name='layer1')
x3 = layer2(x2, name='layer2')
m1 = Model(x1, x3)
x5 = layer3(x4, name='layer3')
x6 = TimeDistributed(m1)(x5)
m2 = Model(x5, x4)
```

For the model architecture below, how can I 'get layer1' or 'layer2'? When I compile m2, I only see 'layer3' and the TimeDistributed layer.

**System information**  
- Have I written custom code (as opposed to using example directory):  No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Mac OS
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  b'v1.13.0-rc2-5-g6612da8951' 1.13.1
- Keras version:  2.2.4
- Python version:  3.6.5
- CUDA/cuDNN version: no  
- GPU model and memory: no

**Comment by jvishnuvardhan** [comment]
@kaushik88 Please check a [resource](https://datascience.stackexchange.com/questions/19362/how-to-obtain-output-of-intermediate-model-in-keras) that provide info of output layer. Thanks!

**Comment by jvishnuvardhan** [comment]
Hi!
This issue isn't related to a bug/enhancement/feature request or other accepted types of issue.
To ask questions, please see the following resources :
[StackOverflow](http://stackoverflow.com/questions/tagged/keras)
[Keras Slack channel](https://keras-slack-autojoin.herokuapp.com)
[Keras.io support](https://keras.io/#support)
[Gitter](https://gitter.im/Keras-io/Lobby)
Thanks!
If you think we made a mistake, please open another issue and fill all the information asked by the template. Thanks!

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by itsaugat** [comment]
I am facing a similar problem. Please share the working solution snippet.
