### ISSUE TITLE
Conv3D dilation increases batch size?

### ISSUE THREAD

**Issue by HansLeonardVanBrueggemann** [keras-team/keras#12981]
**System information**  
- Have I written custom code (as opposed to using example directory):  No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Linux Ubuntu 16.04
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  1.9.0
- Keras version:  2.2.4
- Python version:  3.5.2
- CUDA/cuDNN version: 9.0  
- GPU model and memory:  NVIDIA P6000

**Describe the current behavior**  

I'm trying to use dilated 3D convolutions. However, when I declare one, like
`x = keras.layers.Conv3D(32, 3, dilation_rate=2, padding='valid', name='conv0')(x)`
I run out of memory. It says it cannot allocate a tensor of `[512, 32, 22, 22, 22]`.

**Describe the expected behavior**  

Given that the batch size is set to 64, where does that 512 come from?

**Comment by jvishnuvardhan** [comment]
@HansLeonardVanBrueggemann Can you provide a standalone code to reproduce the issue?  Can you check by lowering the number of filters. Thanks!

**Comment by HansLeonardVanBrueggemann** [comment]
I can't provide the data, but the network looks like this

```
    inflow = keras.layers.Input(shape=input_shape, name='input')
    x = keras.layers.GaussianNoise(stddev=noise, name='input_noise')(inflow)

    x = keras.layers.Conv3D(32, 3, dilation_rate=3, padding='same')(x)
    x = keras.layers.LeakyReLU()(x)
    x = keras.layers.Dropout(rate=dropout)(x)
    x= keras.layers.AveragePooling3D(pool_size=2, strides=2)(x) 

    x = keras.layers.Conv3D(64, 3, dilation_rate=3, padding='same')(x)
    x = keras.layers.LeakyReLU()(x)
    x = keras.layers.Dropout(rate=dropout)(x)
    x= keras.layers.AveragePooling3D(pool_size=2, strides=2)(x) 

    x = keras.layers.Conv3D(128, 3, dilation_rate=3, padding='same')(x)
    x = keras.layers.LeakyReLU()(x)
    x = keras.layers.Dropout(rate=dropout)(x)
    x= keras.layers.GlobalAveragePooling3D()(x) 

    x = keras.layers.Dense(1, activation='sigmoid')(x)

    x = keras.models.Model(inflow, x)
```
