### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while saving a very small model

### ISSUE THREAD

**Issue by NaSed** [keras-team/keras#12992]
I have created a very small wide and deep neural network by using the below code:

    def get_wide_deep(layer_num, num_nodes):
        input = Input(shape=(feat_num,))
    
        if isinstance(num_nodes, list):
            n = num_nodes[0]
        else:
            n = num_nodes
    
        x = Dense(n, activation='relu', kernel_regularizer=regularizers.l2(params['l2_regulizer']), name = 'deep0')(input)
        x = BatchNormalization()(x)
        x = Dropout(params['dropout'])(x)
    
        for i in range(1,layer_num):
            if isinstance(num_nodes, list):
                n = num_nodes[i]
            else:
                n = num_nodes
    
            x = Dense(n, activation='relu', kernel_regularizer=regularizers.l2(params['l2_regulizer']), name = 'deep'+str(i))(x)
            x = BatchNormalization()(x)
            x = Dropout(params['dropout'])(x)
    
    
        wide_deep = concatenate([input, x])
        preds = Dense(len(drugLst), activation='sigmoid', kernel_regularizer=regularizers.l2(params['l2_regulizer']))(wide_deep)
        model = Model(input=input, output=preds)
        opt = Adam(lr=params['learningRate'])
        model.compile(optimizer=opt,loss=binary_crossentropy_nan, metrics=None)
        return(model)

I call it as get_wide_deep(3, 30) and after training the network I would like to save the trained model. However, I get the error of maximum recursion depth exceeded. What is the problem?

FYI, my tensorflow version is 1.13.1, my keras version is 2.2.4, and  my python is 3.6.3.

**Comment by jvishnuvardhan** [comment]
@NaSed Can you provide a reproducible code? Thanks!
