### ISSUE TITLE
Help! All layer operations, still get 'NoneType' object has no attribute '_inbound_nodes' error

### ISSUE THREAD

**Issue by DeligientSloth** [keras-team/keras#13002]
**My code as follow:**
`
def model_DynamicAttention_ContextWeighted(p, embedding_matrix, max_sent_len, n_out):
    print("Parameters:", p)

    # Take sentence encoded as indices and convert it to embeddings
    sentence_input = layers.Input(shape=(max_sent_len,), dtype='int32', name='sentence_input')
    # Repeat the input N times for each edge
    x = layers.RepeatVector(MAX_EDGES_PER_GRAPH)(sentence_input)  # N, maxlen
    word_embeddings = layers.wrappers.TimeDistributed(layers.Embedding(output_dim=embedding_matrix.shape[1], input_dim=embedding_matrix.shape[0],
                                                                       input_length=max_sent_len, weights=[embedding_matrix],
                                                                       trainable=False))(x)
    #  N, maxlen, out_dim  (None, 7, 36, 50)
    word_embeddings = layers.Dropout(p['dropout1'])(word_embeddings)

    # Take token markers that identify entity positions, convert to position embeddings
    # (None, 7, 36)
    entity_markers = layers.Input(shape=(MAX_EDGES_PER_GRAPH, max_sent_len,), dtype='int8', name='entity_markers')
    # (None, 7, 2)
    entity_indexes = layers.Input(shape=(MAX_EDGES_PER_GRAPH, 4,), dtype='int32', name='entity_indexes')

    # N, maxlen
    pos_embeddings = layers.wrappers.TimeDistributed(layers.Embedding(output_dim=p['position_emb'],
                                                                      input_dim=POSITION_VOCAB_SIZE, input_length=max_sent_len,
                                                                      embeddings_regularizer=regularizers.l2(),
                                                                      trainable=True))(entity_markers)
    # N, maxlen, out_dim_pos
    # Merge word and position embeddings and apply the specified amount of RNN layers
    x = layers.concatenate([word_embeddings, pos_embeddings])  # N, maxlen, out_dim (None, 7, 36, 3)
    for i in range(p["rnn1_layers"]):
        lstm_layer = layers.LSTM(p['units1'], return_sequences=True)
        if p['bidirectional']:
            lstm_layer = layers.Bidirectional(lstm_layer)
        x = layers.wrappers.TimeDistributed(lstm_layer)(x)

    sentence_matrix = layers.wrappers.TimeDistributed(Attention(step_dim=max_sent_len))(x)  # N, out_dim

    num_units = p['units1'] * (2 if p['bidirectional'] else 1)
    #  (None, 9218)
    # entity_pool_layer = layers.Lambda(
    #     lambda l: tf.reduce_mean(
    #         layers.Reshape(l[:, 0:max_sent_len*num_units], (-1, max_sent_len, num_units))
    #         [tf.cast(layers.Reshape(l[:, max_sent_len*num_units:max_sent_len*num_units+1], (1, ))[0], tf.int32):
    #          tf.cast(layers.Reshape(l[:, max_sent_len*num_units+1:max_sent_len*num_units+2], (1, ))[0], tf.int32)], axis=1)
    # )
    entity_pool_layer = layers.Lambda(
        lambda l: tf.map_fn(
            lambda t:
            tf.reduce_mean(
                K.reshape(t[0: max_sent_len*num_units],
                          [max_sent_len, num_units])
                [tf.cast(t[max_sent_len*num_units: max_sent_len*num_units+1], tf.int32)[0]:
                 tf.cast(t[max_sent_len*num_units+1: max_sent_len*num_units+2], tf.int32)[0]],
                axis=0
            ), l
        )
    )
    left_entity_indexes = layers.Lambda(lambda l: l[:, :, 0:2])(entity_indexes)   # (None, 7, 2)
    right_entity_indexes = layers.Lambda(lambda l: l[:, :, 2:])(entity_indexes)   # (None, 7, 2)
    # x: N, sent, dim  entity_indexes: N, 2
    x_flatten = layers.Reshape((MAX_EDGES_PER_GRAPH, max_sent_len*num_units))(x)
    # (None, 7, 256)
    left_entity_vector = layers.wrappers.TimeDistributed(entity_pool_layer)(
        layers.concatenate([x_flatten, tf.cast(left_entity_indexes, tf.float32)]))
    right_entity_vector = layers.wrappers.TimeDistributed(entity_pool_layer)(
        layers.concatenate([x_flatten, tf.cast(right_entity_indexes, tf.float32)]))
    # none, num, dim
    # print(K.int_shape(left_entity_vector))
    entity_relation_vector = layers.Lambda(
        lambda l: tf.subtract(l[0], l[1])
    )([left_entity_vector, right_entity_vector])

    ### Attention over ghosts ###
    sentence_matrix = layers.concatenate([sentence_matrix, entity_relation_vector])
    num_units = num_units * 2
    layers_to_concat = []

    for i in range(MAX_EDGES_PER_GRAPH):
        # Compute a memory vector for the target entity pair
        sentence_vector = layers.Lambda(lambda l: l[:, i], output_shape=(num_units,))(sentence_matrix)
        target_sentence_memory = layers.Dense(num_units,
                                              activation="linear", use_bias=False)(sentence_vector)

        if i == 0:
            context_vectors = layers.Lambda(lambda l: l[:, i+1:],
                                            output_shape=(MAX_EDGES_PER_GRAPH-1, num_units))(sentence_matrix)
        elif i == MAX_EDGES_PER_GRAPH - 1:
            context_vectors = layers.Lambda(lambda l: l[:, :i],
                                            output_shape=(MAX_EDGES_PER_GRAPH-1, num_units))(sentence_matrix)
        else:
            context_vectors = layers.Lambda(lambda l: K.concatenate([l[:, :i], l[:, i+1:]], axis=1),
                                            output_shape=(MAX_EDGES_PER_GRAPH-1, num_units))(sentence_matrix)

        sentence_scores = layers.Lambda(lambda inputs: K.batch_dot(inputs[0],
                                                                       inputs[1], axes=(1, 2)),
                                       output_shape=(MAX_EDGES_PER_GRAPH,))([target_sentence_memory, context_vectors])
        sentence_scores = layers.Activation('softmax')(sentence_scores)  # 每种关系的重要性

        # Compute the final vector by taking the weighted sum of context vectors and the target entity vector
        context_vector = layers.Lambda(lambda inputs: K.batch_dot(inputs[0], inputs[1], axes=(1, 1)),
                                      output_shape=(num_units,))([context_vectors, sentence_scores])

        edge_vector = layers.concatenate([sentence_vector, context_vector])
        edge_vector = layers.Reshape((1, num_units * 2))(edge_vector)
        layers_to_concat.append(edge_vector)

    edge_vectors = layers.concatenate(layers_to_concat, axis=1)  # N, num_units * 2
    # Apply softmax
    edge_vectors = layers.Dropout(p['dropout1'])(edge_vectors)
    main_output = layers.wrappers.TimeDistributed(layers.Dense(n_out, activation="softmax", name='main_output'))(edge_vectors)

    # N, out_dim
    model = models.Model(inputs=[sentence_input, entity_markers, entity_indexes], outputs=[main_output])
    optimizer = optimizers.Adam(lr=0.001)
    model.compile(optimizer=optimizer, loss=masked_categorical_crossentropy, metrics=['accuracy'])

    return model
`
**They all layer operation, but still get error, please help**
Traceback (most recent call last):
  File "/relation_extraction/model_train.py", line 163, in <module>
    model = getattr(keras_models, model_name)(keras_models.model_params, embedding_matrix, max_sent_len, n_out)
  File "relation_extraction\core\keras_models.py", line 782, in model_DynamicAttention_ContextWeighted
    model = models.Model(inputs=[sentence_input, entity_markers, entity_indexes], outputs=[main_output])
  File "C:\Program\anaconda3\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Program\anaconda3\lib\site-packages\keras\engine\network.py", line 93, in __init__
    self._init_graph_network(*args, **kwargs)
  File "C:\Program\anaconda3\lib\site-packages\keras\engine\network.py", line 231, in _init_graph_network
    self.inputs, self.outputs)
  File "C:\Program\anaconda3\lib\site-packages\keras\engine\network.py", line 1366, in _map_graph_network
    tensor_index=tensor_index)
  File "C:\Program\anaconda3\lib\site-packages\keras\engine\network.py", line 1353, in build_map
    node_index, tensor_index)
  File "C:\Program\anaconda3\lib\site-packages\keras\engine\network.py", line 1353, in build_map
    node_index, tensor_index)
  File "C:\Program\anaconda3\lib\site-packages\keras\engine\network.py", line 1353, in build_map
    node_index, tensor_index)
  [Previous line repeated 7 more times]
  File "C:\Program\anaconda3\lib\site-packages\keras\engine\network.py", line 1325, in build_map
    node = layer._inbound_nodes[node_index]
AttributeError: 'NoneType' object has no attribute '_inbound_nodes'

Process finished with exit code 1

**Comment by ucalyptus** [comment]
check if changinge concatenate to Concatenate works
