### ISSUE TITLE
Difference between DepthwiseConv2D and SeparableConv2D

### ISSUE THREAD

**Issue by michaelowenliu** [keras-team/keras#13008]
From the document, I know SeparableConv2D is a combination of depthwise and pointwise operation. However, when I call

`SeparableConv2D(100, 5, input_shape=(416,416,10) `
total parameters is 1350

`model.add(DepthwiseConv2D(5, input_shape=(416,416,10)))`
`model.add(Conv2D(100, 1))`
total parameters is 1360

Does it mean SeparableConv2D does not use bias in depthwise phase by default?

Thanks.

**Comment by chinmayshah99** [comment]
@michaelowenliu , you might wanna check out the implementation of `SeparableConv2D`, which suggests use_bias as True, - https://github.com/keras-team/keras/blob/c658993cf596fbd39cf800873bc457e69cfb0cdb/keras/layers/convolutional.py#L1643-L1661

**Comment by michaelowenliu** [comment]
> @michaelowenliu , you might wanna check out the implementation of `SeparableConv2D`, which suggests use_bias as True, -
> 
> https://github.com/keras-team/keras/blob/c658993cf596fbd39cf800873bc457e69cfb0cdb/keras/layers/convolutional.py#L1643-L1661

@chinmayshah99 the param is True by default.
