### ISSUE TITLE
Tensor-list conversion

### ISSUE THREAD

**Issue by dervishson** [keras-team/keras#13014]
In the model below, i try to apply attention mechanism. It is many to one architecture, however, i try to convert it to many to one architecture for my problem. 
In the output line, all outputs appended in a list, then this output list must be connected to Dense layer which produces many-to-one's one output, however, i get the raise ValueError which I shared after the model?What can i do to solve this problem? 
My model:
def model(Tx,Ty,n_a,n_s,in_size,out_size):
    X=Input(shape=(Tx,in_size))
    s0=Input(shape=(n_s,),name="s0")
    c0=Input(shape=(n_s,),name="c0")
    s=s0
    c=c0
    output=[]
    a=Bidirectional(CuDNNLSTM(n_a,return_sequences=True))(X)
    for t in range(Ty):
        context=one_step_attention(a,s)
        s,_,c=post_activation_LSTM_cell(context,initial_state=[s,c])
        out=output_layer(s)
        output.append(out)

    y_pred=np.asarray(output)
    y_pred=np.expand_dims(y_pred,axis=1)
    y_pred=Dense(1,activation="linear")(y_pred)
    output=Dense(1,activation="linear")(y_pred)
    model=Model(inputs=[X,s0,c0],outputs=output)
    return model

--------------------------------------------
ValueError: Layer dense_4 was called with an input that isn't a symbolic tensor. Received type: <class 'numpy.ndarray'>. Full input: [array([[<tf.Tensor 'dense_3/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_1/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_2/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_3/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_4/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_5/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_6/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_7/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_8/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_9/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_10/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_11/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_12/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_13/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_14/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_15/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_16/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_17/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_18/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_19/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_20/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_21/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_22/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_23/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_24/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_25/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_26/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_27/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_28/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_29/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_30/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_31/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_32/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_33/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_34/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_35/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_36/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_37/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_38/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_39/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_40/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_41/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_42/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_43/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_44/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_45/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_46/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_47/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_48/Softmax:0' shape=(?, 20) dtype=float32>],
       [<tf.Tensor 'dense_3_49/Softmax:0' shape=(?, 20) dtype=float32>]],
      dtype=object)]. All inputs to the layer should be tensors.

**Comment by gowtham-kp** [comment]
@dervishson Can you please take a look at the [issue](https://discourse.edwardlib.org/t/neural-networks-example-doesnt-work/587) and let me know if that helps. Thanks!

**Comment by dervishson** [comment]
I have found out the solution.At the end of this link's page,you can concatenate lists as tensors.This is very usual encoder-decoder stuff.
https://blog.keras.io/a-ten-minute-introduction-to-sequence-to-sequence-learning-in-keras.html
