### ISSUE TITLE
evaluate_generator() got an unexpected keyword argument 'callbacks'

### ISSUE THREAD

**Issue by architlfc** [keras-team/keras#13017]
The keras Documntation shows evaluate_generator having argument callbacks ,But while im using it it isnt accepting the callbcaks argument.

I'm using keras version: '2.2.4'

evaluate_generator(generator, steps=None, callbacks=None, max_queue_size=10, workers=1, use_multiprocessing=False, verbose=0)
https://keras.io/models/model/

**Comment by dabasajay** [comment]
`callbacks` argument in `evaluate_generator()` is removed in `2.2.4` version.
New definition of `evaluate_generator()` is:
`evaluate_generator(model, generator, steps=None, max_queue_size=10, workers=1, use_multiprocessing=False, verbose=0):`
