### ISSUE TITLE
Keras issue for loading uint16 (16 bits) images by ImageDataGenerator

### ISSUE THREAD

**Issue by omaghsoudi** [keras-team/keras#13023]
<em>Please make sure that this is a Bug or a Feature Request and provide all applicable information asked by the template.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.</em>  

**System information**  
- Have I written custom code (as opposed to using example directory):  no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Linux18.04 and Centos7
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  1.12.0
- Keras version:  2.2.4
- Python version:  3.7
- CUDA/cuDNN version:  7.5
- GPU model and memory:  V100, 16GB

You can obtain the TensorFlow version with:  
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"  
You can obtain the Keras version with:  
python -c 'import keras as k; print(k.__version__)'  

**Describe the current behavior**  
The 16 bits images are getting saturated as Keras reads them as 8bits! Anything above 255 will be 255!

**Describe the expected behavior**  
16 bits images should be read properly but it does not!

**Code to reproduce the issue**  
Provide a reproducible test case that is the bare minimum necessary to generate the problem.  
Save a 16 bits image and load it by ImageDataGenerator; the results will be between 0 to 255.

**Other info / logs**  
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.  
The issue is straight forward and can be easily resolved. Please let me know if you need more info. Also, thank you for the great API. I hope you resolve the issue soon as I do not want to write the whole ImageDataGenerator just because of this issue!

Thank you!

**Comment by kiblee** [comment]
This seems like an issue for Pillow and not Keras. Keras uses Pillow to load images and Pillow currently does not support multi-channel images with more than 8 bits. However, it does support higher bit-depth  single-channel images. 

Please see https://github.com/python-pillow/Pillow/issues/1888

**Comment by omaghsoudi** [comment]
You are correct about the Pillow issue with multi-channel images in 16 bits. However, this is an issue with Keras too as Keras fails loading images! Keras can provide the ability to load images using OpenCV or Scipy which can resolve this issue. Hopefully either 
Keras considers adding the possibility to load images using other packages or Pillow resolve the issue.

**Comment by CA4GitHub** [comment]
I'm experiencing this issue too.  Keras (& Pillow) should at least provide a warning.

**Comment by bersbersbers** [comment]
I agree with @CA4GitHub: this is not only a Pillow issue, as it happens also for single-channel 16-bit TIFF images; python-pillow/Pillow#1888 explicitly states that Pillow "is able to open higher bit depth images (e.g. I16, I32, or Float32 images) if they are single channel". In fact, as @CA4GitHub rightly states, PIL loads a 16-bit single-channel TIFF file into an `I;16` image successfully, that is then force-converted into either `L`, `rgba` or `rgb` by Keras code.

**Comment by JoeHRIsaac** [comment]
Bumping this since I'm also having the same problem. The 16-bit images are getting truncated at 255

**Comment by bersbersbers** [comment]
I think this is fixed as of `pip install "keras-preprocessing>=1.1.1"` and can be closed.

**Comment by mmkhan78** [comment]
keras-preprocessing version 1.1.2  provides support for 16 bit grayscale images however, there is still no support for 16 bit r,g,b images ? The update [https://github.com/keras-team/keras-preprocessing/commit/4e412de9f6dda66309f0e0f0a6ab5acd3691967f](url)  also seems to suggest this, right?

**Comment by TStein81** [comment]
Hello.  I have been using keras-preprocessing  1.1.2, so in theory this shoudl be fixed, but  the problem continues.

With this code :
train_datagen = ImageDataGenerator(horizontal_flip=True,
                                  vertical_flip=True,
                                  featurewise_center=False,
                                  samplewise_center=False,                                  
                                  brightness_range=[0.8, 1.2])

it = train_datagen.flow_from_directory("/home/tiago/workspace/aquila/test_16_bit/16bit/",
                                                  target_size=(256,256),
                                                  color_mode='grayscale',
                                                  interpolation='bicubic',                                                
                                                  #class_mode='binary',
                                                  save_to_dir="/tmp/augumented",                                  
                                                  batch_size=2)
X = next(it)
for i in range(2):
    im = X[0][0][..., 0]
    print(np.max(im))
    print(np.min(im))
    plt.imshow(X[0][0][..., 0])
    plt.show()

I get  min and max values on the generated image in between 0 and 255, no matter if my original images  are 8 bit or 16 bit PNG (both cases grayscale) (the second ones with values up to 4096.  If it were working correctly the value range should not have been compressed down to max 255.

Can anyone confirm that has been solved, and if yes if there is something else I should be looking about to fix it?
