### ISSUE TITLE
Feature Request: Better support to implement custom metrics like F1

### ISSUE THREAD

**Issue by PhilipMay** [keras-team/keras#13034]
You have removed F1 score from metrics in the past. I understand the reason but want to implement my own F1 score (and other metrics) as a callback to do early stopping.

There are many different implementations in the net. All of them do their own prediction run. This is unnecessary and a waste of time because if you have provided `validation_data` to the fit function keras already did it's own predictions. The problem is that you can not access the prediction results in the callback (with the `on_epoch_end` function for example).

My request is: Can you somehow implement a way to get prediction results from the callbacks if the user provided  `validation_data` to the fit function?

Thanks
Philip

**Comment by dynamicwebpaige** [comment]
Thanks for the suggestion, @PhilipMay! Are you using TensorFlow as your backend, by any chance? We have implemented something similar in a package called [TensorFlow Addons](https://www.github.com/tensorflow/addons). You would be able to create and open-source custom losses, layers, etc.

[It looks like F1 has been added.](https://github.com/tensorflow/addons/issues/265)

**Comment by briannemsick** [comment]
Use ``StatefulMetrics``, you can compute it exactly (not a batchwise average) and without having a custom callback hack:

See: https://github.com/keras-team/keras/blob/master/tests/keras/metrics_test.py

**Comment by PhilipMay** [comment]
> Thanks for the suggestion, @PhilipMay! Are you using TensorFlow as your backend, by any chance? We have implemented something similar in a package called [TensorFlow Addons](https://www.github.com/tensorflow/addons). You would be able to create and open-source custom losses, layers, etc.
> 
> [It looks like F1 has been added.](https://github.com/tensorflow/addons/issues/265)

@dynamicwebpaige For me this seem to be tensorflow metrics. Is it possible to use them with keras?

This does not work:
```
from tensorflow_addons.metrics import F1Score

f1 = F1Score(10, 'macro')

model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=[f1])
model.fit(train_images, train_labels, 
          validation_data=(test_images, test_labels), 
          epochs=2, 
          batch_size=64)
```

It gives me:

```
TypeError: in converted code:
TypeError: tf__update_state() got an unexpected keyword argument 'sample_weight'
```
