### ISSUE TITLE
ImportError: cannot import name 'issparse' keras version 2.2.4 

### ISSUE THREAD

**Issue by ayushiee** [keras-team/keras#13035]
from keras.models import Model
from keras.layers import Embedding, Dense, LSTM, Dropout, Input

This is the error occuring for executing the above statements:

ImportError                               Traceback (most recent call last)
<ipython-input-9-257c268d2e40> in <module>
      4 from nltk.tokenize import word_tokenize
      5 from nltk.corpus import stopwords
----> 6 from keras.models import Model
      7 from keras.layers import Embedding, Dense, LSTM, Dropout, Input
      8 #from sklearn.model_selection import train_test_split

~\Anaconda3\lib\site-packages\keras\__init__.py in <module>
      1 from __future__ import absolute_import
      2 
----> 3 from . import utils
      4 from . import activations
      5 from . import applications

~\Anaconda3\lib\site-packages\keras\utils\__init__.py in <module>
     25 from .np_utils import to_categorical
     26 from .np_utils import normalize
---> 27 from .multi_gpu_utils import multi_gpu_model

~\Anaconda3\lib\site-packages\keras\utils\multi_gpu_utils.py in <module>
      5 from __future__ import print_function
      6 
----> 7 from ..layers.merge import concatenate
      8 from .. import backend as K
      9 from ..layers.core import Lambda

~\Anaconda3\lib\site-packages\keras\layers\__init__.py in <module>
      3 from ..utils.generic_utils import deserialize_keras_object
      4 from ..engine.base_layer import Layer
----> 5 from ..engine import Input
      6 from ..engine import InputLayer
      7 from ..engine.base_layer import InputSpec

~\Anaconda3\lib\site-packages\keras\engine\__init__.py in <module>
      6 from .base_layer import Layer
      7 from .network import get_source_inputs
----> 8 from .training import Model

~\Anaconda3\lib\site-packages\keras\engine\training.py in <module>
     19 from .training_utils import standardize_weights
     20 from .training_utils import weighted_masked_objective
---> 21 from . import training_arrays
     22 from . import training_generator
     23 from .. import backend as K

~\Anaconda3\lib\site-packages\keras\engine\training_arrays.py in <module>
      6 
      7 import numpy as np
----> 8 from scipy.sparse import issparse
      9 
     10 from .training_utils import batch_shuffle

ImportError: cannot import name 'issparse'

**Comment by siddheshsathe** [comment]
Hi @ayushiee , can you please confirm the installation of scipy is correct?
Instead of importing these from keras' background, please try
```python
import scipy
```
if this works, try for 
```python
from scipy.sparse import issparse
```

Try re-installing scipy if the issue persists.

**Comment by ayushiee** [comment]
The packages were correct and up to date.
I re-installed anaconda, that seems to have solved the isuue for now. 
Thanks.
