### ISSUE TITLE
self-defined Attention layer failed for keras

### ISSUE THREAD

**Issue by nickhuangxinyu** [keras-team/keras#13045]
my layer code:

from keras.layers.core import Layer
from keras.engine import InputSpec
from keras import backend as K
try:
    from keras import initializations
except ImportError:
    from keras import initializers as initializations

import numpy as np
class HardAttention(Layer):
    def __init__(self, **kwargs):
        super(HardAttention, self).__init__(**kwargs)
        self.input_spec = InputSpec(min_ndim=2)

    def build(self, input_shape):
        input_dim = input_shape[-1]
        self.attention = self.add_weight(shape=input_shape,
                                         initializer='uniform',
                                         name='attention',
                                         dtype=np.float32,
                                         trainable=True)
                                         #dtype=bool)
        self.input_spec = InputSpec(min_ndim=2, axes={-1: input_dim})
        self.built = True
        super(HardAttention, self).build(input_shape)

    def call(self, inputs):
        return K.multiply(inputs, self.attention)

    def compute_output_shape(self, input_shape):
        return input_shape

model code:

(time_step, n_stock) = np.shape(x_train)

model = Sequential()
model.add(InputLayer(input_shape=(3,)))
model.add(HardAttention())
model.add(Dense(5))

model.compile(optimizer='adam', loss='mse')
model.summary()

error message:
TypeError: Failed to convert object of type <class 'tuple'> to Tensor. Contents: (None, 3). Consider casting elements to a supported type.

can anyone help me about this error, i think i define this layer quite similar with dense layer, why it doesnt work?

**Comment by dabasajay** [comment]
Fix:
```python
class HardAttention(Layer):
    def __init__(self, **kwargs):
        super(HardAttention, self).__init__(**kwargs)
        self.input_spec = InputSpec(min_ndim=2)
    def build(self, input_shape):
        input_dim = input_shape[-1]
        self.attention = self.add_weight(shape=(input_dim,1),
                                         initializer='uniform',
                                         name='attention',
                                         dtype=np.float32,
                                         trainable=True)
        self.input_spec = InputSpec(min_ndim=2, axes={-1: input_dim})
        self.built = True
        super(HardAttention, self).build(input_shape)
    def call(self, inputs):
        return K.dot(inputs, self.attention)
    def compute_output_shape(self, input_shape):
        output_shape = list(input_shape)
        output_shape[-1] = 1
        return tuple(output_shape)
```

**Comment by nickhuangxinyu** [comment]
> Fix:
> 
> ```python
> class HardAttention(Layer):
>     def __init__(self, **kwargs):
>         super(HardAttention, self).__init__(**kwargs)
>         self.input_spec = InputSpec(min_ndim=2)
>     def build(self, input_shape):
>         input_dim = input_shape[-1]
>         self.attention = self.add_weight(shape=(input_dim,input_dim),
>                                          initializer='uniform',
>                                          name='attention',
>                                          dtype=np.float32,
>                                          trainable=True)
>         self.input_spec = InputSpec(min_ndim=2, axes={-1: input_dim})
>         self.built = True
>         super(HardAttention, self).build(input_shape)
>     def call(self, inputs):
>         return K.dot(inputs, self.attention)
>     def compute_output_shape(self, input_shape):
>         return input_shape
> ```

Thanks dabasajay a looooooooooooooot

**Comment by dabasajay** [comment]
Happy to help! If your issue is resolved, please consider closing the issue.

**Comment by aezco** [comment]
Would you like explain this code, what are you doing? I would like to apply soft attention for a pretrained resnet.  Although, I struggle with implementation, dont know where to start. I would like to do soft attention after the FC layer for each feature map of single image.
