### ISSUE TITLE
How to combine two trained models in keras?

### ISSUE THREAD

**Issue by amitgupta911** [keras-team/keras#13049]
I have two models , trained using CNN on an image data set, both models are trained to identify different-different objects.Is it possible so that i combine these two trained models in keras, to detect two different objects in the given image,using a single merged model.

**Comment by dabasajay** [comment]
Why do you want to merge the models? I mean you can just run the first model to get predictions for objects of the 1st kind and then run the second model separately to get predictions for objects of the 2nd kind. This is like a pipeline setup.
If you merge them, say by concatenating penultimate layer, then you'll have to retrain the last layer to output predictions for 1st + 2nd kind of objects and this *may* or *may not* work as good as it was before.

**Comment by gowtham-kp** [comment]
Closing this issue due to the lack of recent activity. Please add additional comments and we can open the issue again. Thanks!

**Comment by sathyamoorthyrr** [comment]
> Why do you want to merge the models? I mean you can just run the first model to get predictions for objects of the 1st kind and then run the second model separately to get predictions for objects of the 2nd kind. This is like a pipeline setup.
> If you merge them, say by concatenating penultimate layer, then you'll have to retrain the last layer to output predictions for 1st + 2nd kind of objects and this _may_ or _may not_ work as good as it was before.

@dabasajay 
While running like a pipeline setup (the first model and then second model),
What if an object is predicted by both the model?

How can we assign a priority to either of the model, where the predictions of either model is not always true?
