### ISSUE TITLE
 NO such file or directory

### ISSUE THREAD

**Issue by luckmank** [keras-team/keras#13055]
I'm getting this error while opening a file in mac using spyder.

OSError: Unable to open file (unable to open file: name = '/Users/mayank/Dekstop/DeepLearningCV/Trained Models/mnist_simple_cnn.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
![Screenshot 2019-07-03 at 12 44 18 AM](https://user-images.githubusercontent.com/43822374/60540018-c1ace980-9d2b-11e9-97fc-817ed88464fd.png)
![Screenshot 2019-07-03 at 12 44 18 AM](https://user-images.githubusercontent.com/43822374/60540038-ce314200-9d2b-11e9-96bf-e3d9db7b5755.png)

**Comment by dabasajay** [comment]
How is this issue related to Keras? I guess if you're trying to load a model `.h5` file, then the file is not present at the provided path. Please make sure the path you entered is correct and the file is indeed present there.
