### ISSUE TITLE
Siamese

### ISSUE THREAD

**Issue by query90** [keras-team/keras#13054]
I am trying to run the Siamese code on MNIST data.
The link of the code is : https://github.com/keras-team/keras/blob/master/examples/mnist_siamese.py
In the code, I used my own training file and splitting the data into train and test as follows:
x_train, x_test, y_train, y_test = train_test_split(desc1, label1, test_size=0.5, random_state=1)
i.e. 50% into training and testing. When I am increasing the test_size from 0.5 to 1, the code is working. But if I reduced this value below 0.5, I am getting this error:
    validation_data=([te_pairs[:, 0], te_pairs[:, 1]], te_y))
IndexError: too many indices for array
Please help.

**Comment by dabasajay** [comment]
Can you please provide the whole stack traceback along with source code, if possible? It'll be easier to debug.

**Comment by query90** [comment]
'''Trains a Siamese MLP on pairs of digits from the MNIST dataset.
It follows Hadsell-et-al.'06 [1] by computing the Euclidean distance on the
output of the shared network and by optimizing the contrastive loss (see paper
for more details).
# References
- Dimensionality Reduction by Learning an Invariant Mapping
    http://yann.lecun.com/exdb/publis/pdf/hadsell-chopra-lecun-06.pdf
Gets to 97.2% test accuracy after 20 epochs.
2 seconds per epoch on a Titan X Maxwell GPU
'''
from __future__ import absolute_import
from __future__ import print_function
import numpy as np

import random
import sys
from keras.datasets import mnist
from keras.models import Model
from keras.layers import Input, Flatten, Dense, Dropout, Lambda
from keras.optimizers import RMSprop
from keras import backend as K
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import pandas as pd
np.set_printoptions(threshold=sys.maxsize)

num_classes = 2
epochs = 1


def euclidean_distance(vects):
    x, y = vects
    sum_square = K.sum(K.square(x - y), axis=1, keepdims=True)
    return K.sqrt(K.maximum(sum_square, K.epsilon()))


def eucl_dist_output_shape(shapes):
    shape1, shape2 = shapes
    return (shape1[0], 1)


def contrastive_loss(y_true, y_pred):
    '''Contrastive loss from Hadsell-et-al.'06
    http://yann.lecun.com/exdb/publis/pdf/hadsell-chopra-lecun-06.pdf
    '''
    margin = 1
    square_pred = K.square(y_pred)
    margin_square = K.square(K.maximum(margin - y_pred, 0))
    return K.mean(y_true * square_pred + (1 - y_true) * margin_square)


def create_pairs(x, digit_indices):
    '''Positive and negative pair creation.
    Alternates between positive and negative pairs.
    '''
    pairs = []
    labels = []
    n = min([len(digit_indices[d]) for d in range(num_classes)]) - 1
    print("*****n:",n)
    for d in range(num_classes):
        for i in range(n):
            z1, z2 = digit_indices[d][i], digit_indices[d][i + 1]
            pairs += [[x[z1], x[z2]]]
            inc = random.randrange(1, num_classes)
            dn = (d + inc) % num_classes
            z1, z2 = digit_indices[d][i], digit_indices[dn][i]
            pairs += [[x[z1], x[z2]]]
            labels += [1, 0]
    return np.array(pairs), np.array(labels)


def create_base_network(input_shape):
    '''Base network to be shared (eq. to feature extraction).
    '''
    input = Input(shape=input_shape)
    x = Flatten()(input)
    x = Dense(128, activation='relu')(x)
    x = Dropout(0.1)(x)
    x = Dense(128, activation='relu')(x)
    x = Dropout(0.1)(x)
    x = Dense(128, activation='relu')(x)
    return Model(input, x)


def compute_accuracy(y_true, y_pred):
    '''Compute classification accuracy with a fixed threshold on distances.
    '''
    pred = y_pred.ravel() < 0.5
    return np.mean(pred == y_true)


def accuracy(y_true, y_pred):
    '''Compute classification accuracy with a fixed threshold on distances.
    '''
    return K.mean(K.equal(y_true, K.cast(y_pred < 0.5, y_true.dtype)))


# the data, split between train and test sets
#***********************************************************
#data loading
df1=pd.read_csv("class7h.csv") #loads input file from classcsvfiles_headers folder
df1_desc = df1.loc[:, df1.columns != 'label']  # load descriptor as column 1 of input file contains label and rest 2025 columns contain feature vector
df1_label = df1["label"]  # load label
desc1=np.array(df1_desc)  # create descriptor array
label1=np.array(df1_label)  # create label array

#train test split making
x_train, x_test, y_train, y_test = train_test_split(desc1, label1, test_size=0.5, random_state=1) # split into training and test data, 80% training and 20% test
print("******************x_train_shape:", x_train.shape)
x_train = x_train.reshape(x_train.shape[0], 45, 45).astype('float32') # reshape to 45x45 array to form an image for training
x_test = x_test.reshape(x_test.shape[0], 45, 45).astype('float32')   # reshape to 45x45 array to form an image for tesing

x_train = x_train / 255
x_test = x_test / 255


input_shape = x_train.shape[1:]
print("******************x_train_shape:", x_train.shape)
#print("******************x_train:", x_train[0])
print("**************y_train_shape:", y_train.shape)
print("****************y_train:",y_train)
print("******************x_test_shape:", x_test.shape)
#print("******************x_train:", x_train[0])
print("**************y_test_shape:", y_test.shape)
print("****************y_test",y_test)
c=[]
for i in range(num_classes):
	c=np.where(y_train == i)[0]
	print(c)

# create training+test positive and negative pairs
digit_indices = [np.where(y_train == i)[0] for i in range(num_classes)]
tr_pairs, tr_y = create_pairs(x_train, digit_indices)
#print("************tr_pairs", tr_pairs)
print("************tr_pairs shape", tr_pairs.shape)
print("*****************tr_y shape", tr_y.shape)

c=[]
for i in range(num_classes):
	c=np.where(y_test== i)[0]
	print(c)

digit_indices = [np.where(y_test == i)[0] for i in range(num_classes)]
te_pairs, te_y = create_pairs(x_test, digit_indices)
print("************te_pairs shape", te_pairs.shape)
print("*****************te_y shape", te_y.shape)
# network definition
base_network = create_base_network(input_shape)

input_a = Input(shape=input_shape)
input_b = Input(shape=input_shape)

# because we re-use the same instance `base_network`,
# the weights of the network
# will be shared across the two branches
processed_a = base_network(input_a)
processed_b = base_network(input_b)

distance = Lambda(euclidean_distance,
                  output_shape=eucl_dist_output_shape)([processed_a, processed_b])

model = Model([input_a, input_b], distance)

# train
rms = RMSprop()
model.compile(loss=contrastive_loss, optimizer=rms, metrics=[accuracy])
model.fit([tr_pairs[:, 0], tr_pairs[:, 1]], tr_y,
          batch_size=128,
          epochs=epochs,
          validation_data=([te_pairs[:, 0], te_pairs[:, 1]], te_y))

# compute final accuracy on training and test sets
y_pred = model.predict([tr_pairs[:, 0], tr_pairs[:, 1]])
tr_acc = compute_accuracy(tr_y, y_pred)
y_pred = model.predict([te_pairs[:, 0], te_pairs[:, 1]])
te_acc = compute_accuracy(te_y, y_pred)

print('* Accuracy on training set: %0.2f%%' % (100 * tr_acc))
print('* Accuracy on test set: %0.2f%%' % (100 * te_acc))

**Comment by dabasajay** [comment]
I meant to ask you to provide the whole stack traceback i.e. the **whole** error message so that I can look into Keras code and find which line is throwing the error. Also, I read your code and if it is working for `test_size>=0.5` and not working for `test_size<0.5` then there's a possibility that during random splitting, only 1 type of class is present in train or test set instead of two. I suggest after you get data from `create_pairs` function, check shapes of data and also check that both `classes - 0 & 1` are present in `y_train` and `y_test` before proceeding to train.

**Comment by query90** [comment]
Thanks Ajay. The error is resolved. I have increased the data so that it may contain both the sets of classes. By doing this, the problem is solved.

**Comment by dabasajay** [comment]
Happy to help!
