### ISSUE TITLE
Focal loss in keras

### ISSUE THREAD

**Issue by adrianboguszewski** [keras-team/keras#13052]
@fchollet Do you think a [focal loss](https://arxiv.org/pdf/1708.02002.pdf) is useful in keras? I've done implementation for my purpose (binary and categorical classification) and I can commit it to keras also.

If yes, I'll provide tests, documentation and so on.

**Comment by littlemountainman** [comment]
Imo, might be useful. A lot of people use keras for object detection so it might be useful in the future.
