### ISSUE TITLE
 Keras model.fit InvalidArgumentError 

### ISSUE THREAD

**Issue by ayushiee** [keras-team/keras#13062]
x.shape() #(189912, 100)
y.shape() # (189912, 99, 1)
model.fit(x, y, batch_size = 128, epochs = 1, shuffle=True)

It is giving the InvalidArgumentError. Please help.
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-61-684c0d35ce76> in <module>
----> 1 print(model.fit(x, y, batch_size = 128, epochs = 1, shuffle=True))
      2 model.save('model.model')

~\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, max_queue_size, workers, use_multiprocessing, **kwargs)
    878           initial_epoch=initial_epoch,
    879           steps_per_epoch=steps_per_epoch,
--> 880           validation_steps=validation_steps)
    881 
    882   def evaluate(self,

~\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\training_arrays.py in model_iteration(model, inputs, targets, sample_weights, batch_size, epochs, verbose, callbacks, val_inputs, val_targets, val_sample_weights, shuffle, initial_epoch, steps_per_epoch, validation_steps, mode, validation_in_fit, **kwargs)
    327 
    328         # Get outputs.
--> 329         batch_outs = f(ins_batch)
    330         if not isinstance(batch_outs, list):
    331           batch_outs = [batch_outs]

~\Anaconda3\lib\site-packages\tensorflow\python\keras\backend.py in __call__(self, inputs)
   3074 
   3075     fetched = self._callable_fn(*array_vals,
-> 3076                                 run_metadata=self.run_metadata)
   3077     self._call_fetch_callbacks(fetched[-len(self._fetches):])
   3078     return nest.pack_sequence_as(self._outputs_structure,

~\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in __call__(self, *args, **kwargs)
   1437           ret = tf_session.TF_SessionRunCallable(
   1438               self._session._session, self._handle, args, status,
-> 1439               run_metadata_ptr)
   1440         if run_metadata:
   1441           proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

~\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py in __exit__(self, type_arg, value_arg, traceback_arg)
    526             None, None,
    527             compat.as_text(c_api.TF_Message(self.status.status)),
--> 528             c_api.TF_GetCode(self.status.status))
    529     # Delete the underlying status object from memory otherwise it stays alive
    530     # as there is a reference to status from this from the traceback due to

InvalidArgumentError: Incompatible shapes: [128,99] vs. [128,100]
	 [[{{node metrics_5/acc/Equal}}]]

**Comment by dabasajay** [comment]
Can you elaborate a little bit on your labels(y) shape? Why is it (189912, 99, 1)? Also, provide the source code of your model definition.

**Comment by ayushiee** [comment]
y shape, originally
(189812, 199)
[[   1    2    3 ...    4   83   79]
 [   2    3    4 ...   83   79    5]
 [   3    4    4 ...   79    5   84]
 ...
 [   5  264  841 ... 1101    5 1101]
 [ 264  841  245 ...    5 1101    5]
 [ 841  245   40 ... 1101    5 2790]]

x shape
(189812, 200)
[[   0    1    2 ...    4   83   79]
 [   1    2    3 ...   83   79    5]
 [   2    3    4 ...   79    5   84]
 ...
 [ 791    5  264 ... 1101    5 1101]
 [   5  264  841 ...    5 1101    5]
 [ 264  841  245 ... 1101    5 2790]]

Thus, to make the y model of a similar dimension of x, I've reshaped it using 
y.reshape(y.shape[0], y.shape[1],1) 
to get
y shape
(189812, 199, 1)
[[[   1]
  [   2]
  [   3]
  ...
  [   4]
  [  83]
  [  79]]

 [[   2]
  [   3]
  [   4]
  ...
  [  83]
  [  79]
  [   5]]

 [[   3]
  [   4]
  [   4]
  ...
  [  79]
  [   5]
  [  84]]

 ...

 [[   5]
  [ 264]
  [ 841]
  ...
  [1101]
  [   5]
  [1101]]

 [[ 264]
  [ 841]
  [ 245]
  ...
  [   5]
  [1101]
  [   5]]

 [[ 841]
  [ 245]
  [  40]
  ...
  [1101]
  [   5]
  [2790]]]

Model source:-
inp = Input((None, ))

embed = Embedding(vocab_size, embedding)
lstm1 = LSTM(lstm_size, return_sequences = True, return_state = True)
lstm2 = LSTM(lstm_size, return_sequences = True, return_state = True)
lstm3 = LSTM(lstm_size, return_sequences = True, return_state = True)
flat = Flatten()
dense = Dense(vocab_size)

net = embed(inp)
net, h1, c1 = lstm1(net)
net, h2, c2 = lstm2(net)
net, h3, c3 = lstm3(net)
#net.Flatten()
out = dense(net)

model = Model(inp, out)
init_states = [Input((lstm_size,)) for i in range(6)]

inference = embed(inp)
inference, h1, c1 = lstm1(inference, initial_state = init_states[:2])
inference, h2, c2 = lstm2(inference, initial_state = init_states[2:4])
inference, h3, c3 = lstm3(inference, initial_state = init_states[4:6])
inf_out = dense(inference)

states = [h1, c1, h2, c2, h3, c3]

inf_model = Model([inp]+init_states, [inf_out]+states)
model.compile(optimizer = 'rmsprop', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])

model.optimizer.lr = 0.01
model.compile(optimizer = 'rmsprop', loss = 'sparse_categorical_crossentropy', metrics=['accuracy'])

print(model.fit(x, y, batch_size = 128, epochs = 4, shuffle=True))

**Comment by dabasajay** [comment]
Hello @ayushiee 
As you said 
> to make the y model of a similar dimension of x, I've reshaped it using y.reshape(y.shape[0], y.shape[1],1) to get y shape (189812, 199, 1)
(189812, 200) is *not* similar to (189812, 199, 1)
To run the model training, you need to have y of shape: (189812, 200, 1)

**Comment by ayushiee** [comment]
Okay, thanks.

**Comment by hendryPrabha** [comment]
ValueError                                Traceback (most recent call last)
<ipython-input-80-69d2b3e5c756> in <module>
     28              metrics=['accuracy'])
     29 
---> 30 model.fit(x, y, batch_size=2, epochs=3, validation_split=0.33)

~\.conda\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    817         max_queue_size=max_queue_size,
    818         workers=workers,
--> 819         use_multiprocessing=use_multiprocessing)
    820 
    821   def evaluate(self,

~\.conda\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py in fit(self, model, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    233           max_queue_size=max_queue_size,
    234           workers=workers,
--> 235           use_multiprocessing=use_multiprocessing)
    236 
    237       total_samples = _get_total_number_of_samples(training_data_adapter)

~\.conda\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py in _process_training_inputs(model, x, y, batch_size, epochs, sample_weights, class_weights, steps_per_epoch, validation_split, validation_data, validation_steps, shuffle, distribution_strategy, max_queue_size, workers, use_multiprocessing)
    531                      'at same time.')
    532 
--> 533   adapter_cls = data_adapter.select_data_adapter(x, y)
    534 
    535   # Handle validation_split, we want to split the data and get the training

~\.conda\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\data_adapter.py in select_data_adapter(x, y)
    996         "Failed to find data adapter that can handle "
    997         "input: {}, {}".format(
--> 998             _type_name(x), _type_name(y)))
    999   elif len(adapter_cls) > 1:
   1000     raise RuntimeError(

ValueError: Failed to find data adapter that can handle input: <class 'numpy.ndarray'>, (<class 'list'> containing values of types {"<class 'int'>"})

**Comment by 123vim** [comment]
ValueError                                Traceback (most recent call last)
<ipython-input-80-69d2b3e5c756> in <module>
     28              metrics=['accuracy'])
     29 
---> 30 model.fit(x, y, batch_size=2, epochs=3, validation_split=0.33)

~\.conda\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    817         max_queue_size=max_queue_size,
    818         workers=workers,
--> 819         use_multiprocessing=use_multiprocessing)
    820 
    821   def evaluate(self,

~\.conda\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py in fit(self, model, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    233           max_queue_size=max_queue_size,
    234           workers=workers,
--> 235           use_multiprocessing=use_multiprocessing)
    236 
    237       total_samples = _get_total_number_of_samples(training_data_adapter)

~\.conda\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py in _process_training_inputs(model, x, y, batch_size, epochs, sample_weights, class_weights, steps_per_epoch, validation_split, validation_data, validation_steps, shuffle, distribution_strategy, max_queue_size, workers, use_multiprocessing)
    531                      'at same time.')
    532 
--> 533   adapter_cls = data_adapter.select_data_adapter(x, y)
    534 
    535   # Handle validation_split, we want to split the data and get the training

~\.conda\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\data_adapter.py in select_data_adapter(x, y)
    996         "Failed to find data adapter that can handle "
    997         "input: {}, {}".format(
--> 998             _type_name(x), _type_name(y)))
    999   elif len(adapter_cls) > 1:
   1000     raise RuntimeError(

ValueError: Failed to find data adapter that can handle input: <class 'numpy.ndarray'>, (<class 'list'> containing values of types {"<class 'int'>"})
