### ISSUE TITLE
on_epoch_end won't be called on validation_data as Sequence instance

### ISSUE THREAD

**Issue by Genarito** [keras-team/keras#13074]
**System information**  
- Have I written custom code: **yes**  
- OS Platform and Distribution: **Linux Kubuntu 19.04**
- TensorFlow backend (yes / no): **yes**
- TensorFlow version: **1.13.1**
- Keras version: **2.2.4-tf**
- Python version: **3.7.3**
- CUDA/cuDNN version: **-**
- GPU model and memory:  **-**

**Describe the current behavior**  
I've wrote a custom data generator for training and validation, as the data is generated on the fly I realised that **validation** during training throw error because the `on_epoch_end` (which I needed to get it work) method was being called **only the first epoch**. The **training data generator is working as expected**, executing that method every time an epoch finishes. Here is my code:

```
# Instances training and validation generator
training_generator = DataGenerator(**params)
validation_generator = DataGenerator(**other_params)

# Creates and trains the model
model.fit_generator(
    generator=training_generator,
    validation_data=validation_generator,
    epochs=50
)
```

**NOTE:** I realised too that training generator doesn't call the `on_epoch_end` method when `workers` parameter is setted to `0` on `fit_generator`.

**Describe the expected behavior**
Both training and validation instances should call `on_epoch_end` method every time a training/validation epoch respectively finishes.

**Code to reproduce the issue**  
Make a toy class example with a print() on the `on_epoch_end` method and see It's called only once for validation and always for training.

**Comment by rvallari1** [comment]
What error the code throws? Can you share.

**Comment by Genarito** [comment]
The error is not because of Keras, but my custom code. It happens beause I guess the method was executed. My code doesn't contribute to the clarification of this problem, sorry. [Here It is](https://colab.research.google.com/drive/144XX22706oKYvfO5FZBij5GBux4eNwBy) a little example in Colab showing the problem, observe that the printing neve ocurred on validation.

Hope It's clear now :)

**Comment by zhanjiezhu** [comment]
> The error is not because of Keras, but my custom code. It happens beause I guess the method was executed. My code doesn't contribute to the clarification of this problem, sorry. [Here It is](https://colab.research.google.com/drive/144XX22706oKYvfO5FZBij5GBux4eNwBy) a little example in Colab showing the problem, observe that the printing never happen on validation.
> 
> Hope It's clear now :)

Hi @Genarito, I'm facing exactly the same issue (validation generator's on_epoch_end is not called), did you find a workaround?

**Comment by Genarito** [comment]
Hi @zhanjiezhu ! I had to call It explicitly: i check if the `index` parameter is the last index in this way:

```
def __data_generation(self, index):
    [...]
    if index == self.len - 1:
        self.on_epoch_end()
```

It's not the best solution, but It worked for me. I hope It helps :D

**Comment by zhanjiezhu** [comment]
> Hi @zhanjiezhu ! I had to call It explicitly: i check if the `index` parameter is the last index in this way:
> 
> ```
> def __data_generation(self, index):
>     [...]
>     if index == self.len - 1:
>         self.on_epoch_end()
> ```
> 
> It's not the best solution, but It worked for me. I hope It helps :D

Thanks! Then in this way I guess on_epoch_end will be called twice for training (one triggered automatically and one manually). I tried to just make normal python generators (not based on Sequence), again having problems when both training and validation are used when workers = 1, then I have to change to workers = 0 to make it work. Another thing I tried is to use the Dataset (I'm using tf2) and it also works.
