### ISSUE TITLE
Initialize LSTM initial state manually

### ISSUE THREAD

**Issue by kushalj001** [keras-team/keras#13088]
I want to initialize the initial state of an LSTM layer with the final hidden state of another LSTM layer. Basically, I want to implement the _conditional encoding_ as explained in this paper https://www.aclweb.org/anthology/D16-1084 

![image](https://user-images.githubusercontent.com/32245327/60956724-fec33e00-a320-11e9-8ccd-6c8564c626ac.png)

How do I access the final hidden state of one LSTM layer and use it as the initial state of another LSTM layer?
Thanks

**Comment by Cstyler** [comment]
Try to look at source code of LSTMCell, LSTM, RNN classes

**Comment by kushalj001** [comment]
```
headline_output,state_h,state_c = headline_lstm(headline_input)
final_headline_states = [state_h,state_c]
#print(state_h,state_c)
article_input = Input(shape=(350,768,),name='article_input')
article_lstm = LSTM(64,name='article_lstm',return_state=True)
article_outputs,_,_ = article_lstm(article_input,initial_state=final_headline_states)
```

Does this work?
I am getting a warning here which says:
```
 UserWarning: Layer article_lstm was passed non-serializable keyword arguments: {'initial_state': [<tf.Tensor 'headline_lstm_1/while/Exit_3:0' shape=(?, 64) dtype=float32>, <tf.Tensor 'headline_lstm_1/while/Exit_4:0' shape=(?, 64) dtype=float32>]}. They will not be included in the serialized model (and thus will be missing at deserialization time).
  '. They will not be included '
```

**Comment by Mahhos** [comment]
Hi. Could you be able to implement LSTM with conditional encoding? I have the same question on how to initialize the second LSTM using the last hidden state of the first LSTM.

**Comment by kushalj001** [comment]
I'll share a snippet of my code. The `article_lstm` is initialized with the final states of `headline_lstm`.  

```
headline_input = Input(shape=(25,1024,),name='headline_input')
headline_lstm = LSTM(64,name='headline_lstm',return_state=True)
headline_output,state_h,state_c = headline_lstm(headline_input)
final_headline_states = [state_h,state_c]

article_input = Input(shape=(350,1024,),name='article_input')
article_lstm = LSTM(64,name='article_lstm',return_state=True)
article_outputs,_,_ = article_lstm(article_input,initial_state=final_headline_states)
dense = Dense(100,activation='relu',name='dense')(article_outputs)
output = Dense(4,activation='softmax',name='output')(dense)

model_cond = Model(inputs=[headline_input,article_input],outputs=output)
model_cond.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
model_cond.fit([y,body_text],Y,epochs=1)
```
Hope this helps.

**Comment by Mahhos** [comment]
May I ask how did you feed the sentences to the first layer (headline_input = Input(shape=(25,1024,),name='headline_input'))? Did you have an embedding layer before this line?

**Comment by kushalj001** [comment]
Yes. I actually calculated contextual embedding for my text and saved it to disk and then directly fed them to the LSTM. The` (25,1024 )` shape corresponds to sequence-length and the embedding/feature vector respectively. If I remember correctly, these are either extracted from ELMo or BERT.

**Comment by Mahhos** [comment]
Thank you. Did you possibly release the code? I am working on this for a while and it would be really helpful to look at your code.

**Comment by kushalj001** [comment]
The code has not been published yet. You can mail me at kushalj001@gmail.com. I'll share some files with you.

**Comment by Mahhos** [comment]
Thanks. I just emailed you.
