### ISSUE TITLE
ImageDataGenerator class

### ISSUE THREAD

**Issue by ericjiang18** [keras-team/keras#13082]
Referring to the ImageDataGenerator class:
[https://blog.keras.io/building-powerful-image-classification-models-using-very-little-data.html](url)
```
datagen = ImageDataGenerator(
        rotation_range=40,
        width_shift_range=0.2,
        height_shift_range=0.2,
        rescale=1./255,
        shear_range=0.2,
        zoom_range=0.2,
        horizontal_flip=True,
        fill_mode='nearest')

```
Is it possible to get the internal data such as the exact rotation value, the exact width shift, the exact height shift, and the exact rescale, and etc? and how using python?

Thank you for your time!

**Comment by Cstyler** [comment]
```python
def random_transform(self, x, seed=None):
    """Applies a random transformation to an image.

    # Arguments
        x: 3D tensor, single image.
        seed: Random seed.

    # Returns
        A randomly transformed version of the input (same shape).
    """
    params = self.get_random_transform(x.shape, seed)
    return self.apply_transform(x, params)
```
You can override this method of ImageDataGenerator and write these params somewhere

**Comment by gowtham-kp** [comment]
@ericjiang18 As @Cstyler mentioned, It is only possible by writing your own custom code by customizing the random_transfrom function [here](https://github.com/keras-team/keras-preprocessing/blob/ecb76f45887cc37a29f78fd5ded9c517aed9fd2d/keras_preprocessing/image/image_data_generator.py#L888). Hope this answers your question!

**Comment by ericjiang18** [comment]
@Cstyler @gowtham-kp thank you so much for helping me out! I figure it out!
