### ISSUE TITLE
Subsampling: Keras 1: What is the subsampling in the Convolution2D doing? Is it a "Stride" so the kernel is filtering only every 2nd pixel or so? Or is it a form of pooling? If so: What kind of pooling is it? MaxPooling? AveragePooling? Or does this subsampling, downsample the feature map created by the convolution?

### ISSUE THREAD

**Issue by WinterErnesto** [keras-team/keras#13083]
Subsampling: Keras 1: What is the subsampling in the Convolution2D doing?
One of the Arguments of Convolution2D-layer:
"subsample: tuple of length 2. Factor by which to subsample output. Also called strides elsewhere."

Is it a "Stride" so the convolutional-kernel is filters only every 2nd pixel or so? 

Or is it a form of pooling? If so: What kind of pooling is it exactly? 
MaxPooling?
AveragePooling? 

Or does this subsampling, downsample the feature map created by the convolution? So not exactly a pooling, but using only every 2nd pixel of the feature map?

It is a very specific question and I could not get a clear answer online. Most people seem not to know the exact difference.

**Comment by gowtham-kp** [comment]
Please refer to the following [stackoverflow](https://stackoverflow.com/questions/38681407/how-can-implement-subsample-like-keras-in-tensorflow) question where subsampling has been clearly defined. 

@WinterErnesto Also please post support questions is [Stackoverflow](https://stackoverflow.com/questions/tagged/keras) or Keras slack channel as there is a big community to help. This platform is only meant for bug/performance, feature request, build/install or related issues. Thanks!
