### ISSUE TITLE
None gradient when using tensorboard callback on keras 2.2.4 and tf 1.14. Bug??

### ISSUE THREAD

**Issue by btekgit** [keras-team/keras#13091]
I believe this may be a bug in the code. 
When I add tensorboard callback to a simple sequential model (with Batch Normalization layer) with write_grad=True

it gives this error:
`ValueError: An operation has `None` for gradient. Please make sure that all of your ops have a gradient defined (i.e. are differentiable). Common ops without gradient: K.argmax, K.round, K.eval.
`
Error traces back to Optimizer:

```
    def get_gradients(self, loss, params):
        grads = K.gradients(loss, params)
        if None in grads:
            #print(params,grads) I added this line to debug
            raise ValueError('An operation has `None` for gradient. '
                             'Please make sure that all of your ops have a '
                             'gradient defined (i.e. are differentiable). '
                             'Common ops without gradient: '
                             'K.argmax, K.round, K.eval.')
```
and this is called from 
```
Class Tensorboard line:
    def set_model(self, model):
        self.model = model
        if K.backend() == 'tensorflow':
            self.sess = K.get_session()
        if self.histogram_freq and self.merged is None:
            for layer in self.model.layers:
                
                #below line causes problem
                **for weight in layer.weights:** 
                    #print("SetModel. tb:", weight) I added this to debug
                    mapped_weight_name = weight.name.replace(':', '_')
```
The weight in my network that gives the error:
`SetModel. tb: <tf.Variable 'batch_normalization_1/moving_mean:0' shape=(32,) dtype=float32_ref>`

But moving_mean is not trainable!!! So it does not have any grad. 
The code is calling for all weights Optimizer.get_gradient. 
And get_gradient does not like None gradients. 

I change the code to the set_model of Tensorboad callback class. 

```
  def set_model(self, model):
        self.model = model
        if K.backend() == 'tensorflow':
            self.sess = K.get_session()
        if self.histogram_freq and self.merged is None:
            for layer in self.model.layers:
                
                #changing below line 
                for weight in layer.trainable_weights:
                      mapped_weight_name = weight.name.replace(':', '_')
...
```

**And it works!**
          

Below is my configuration however I have seen the same error in Google Collab too!

- Have I written custom code (as opposed to using example directory):  
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Ubuntu 16.04
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  1.14 but (1.13 had also error)
- Keras version:  2.2.4
- Python version:  3.7.3
- CUDA/cuDNN version:  10.0/7.6
- GPU model and memory:  gtx1070

**Comment by fotocoyotl** [comment]
Also experiencing this. I'm using Keras with the Tensorflow backend. I've installed the environment using anaconda, specifically the `keras-gpu` package.

OS: Ubuntu 19.04, Linux 5.0.0-21
Keras: 2.2.4
Tensorflow: 1.12.0
Python: 3.6.8
