### ISSUE TITLE
keras.backend.function with cntk backend returns different value from tensorflow backend.

### ISSUE THREAD

**Issue by goodjian7** [keras-team/keras#13094]
Please make sure that the boxes below are checked before you submit your issue.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps`

- [x] Check that your version of CNTK is up-to-date.

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

==============================================================
test code 
==============================================================
import keras
import numpy as np
from keras import backend as K

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

placeholderA = K.placeholder(shape = (2,2), ndim = 2, dtype = np.float32)
placeholderB = K.placeholder(shape = (2,2), ndim = 2, dtype = np.float32)
AdotB = K.dot(placeholderA, placeholderB)

func = K.function(inputs = [placeholderA, placeholderB], outputs = [AdotB])
returnValue = func([A,B])
print(returnValue)

=============================================================
tensorflow-gpu       1.14.0 backend : Keras                2.2.4
=============================================================
[array([[19., 22.],
            [43., 50.]], dtype=float32)]
=============================================================
cntk-gpu             2.7 backend : Keras                2.2.4
=============================================================
[array([[[ 5.,  6.],
             [10., 12.]],
            [[21., 24.],
             [28., 32.]]], dtype=float32)]
==============================================================

**Comment by jvishnuvardhan** [comment]
@goodjian7 result from Tensorflow backend is correct. Thanks!

**Comment by dynamicwebpaige** [comment]
Thank you for filing this issue! The problem you described looks like a bug in CNTK. If you would like for it to be addressed, please file an issue against [that project](https://github.com/microsoft/cntk).
