### ISSUE TITLE
How to add Constraints to the layer after the model is initialized?

### ISSUE THREAD

**Issue by prakharg24** [keras-team/keras#13100]
<em>Please make sure that this is a Bug or a Feature Request and provide all applicable information asked by the template.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.</em>  

**System information**  
- Have I written custom code (as opposed to using example directory): Yes 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Linux Ubuntu 18
- TensorFlow backend (yes / no):  Yes
- TensorFlow version:  1.13.1
- Keras version:  2.2.4
- Python version:  3.6.8
- CUDA/cuDNN version:  
- GPU model and memory:  

You can obtain the TensorFlow version with:  
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"  
You can obtain the Keras version with:  
python -c 'import keras as k; print(k.__version__)'  

**Describe the current behavior**  
I want to test a custom Constraint function that I have written on various models. However, the only way I know of adding a constraint to a layer is while declaring the model. If I want to use models from other people and simple apply my custom constraint and retrain it, I am not able to do so.

**Describe the expected behavior**  

I tried doing layer.kernel_constraint = CustomConstraint() and then all possible combinations of recompiling and initialising variables etc. afterwards, but none of that seems to work.

```
for ele in model.layers:
    print(ele.kernel_constraint) # Gives output None
for ele in model.layers:
    ele.kernel_constraint = CustomConstraint()

model.compile(loss=someloss, optimizer=somethingelse)

for ele in model.layers:
    print(ele.kernel_constraint) # Prints some object

model.fit() # Doesn't work the way I want it to
```
By doing the above, the layer.kernel_constraint is changed to the object at which I want it to be pointing. But since the CustomConstraint in itself contains tensor graphs which should be initialised for it to work, I think they are not getting initialsed.

Instead if I add it as 
```
x = Layer1(kernel_constriant = CustomConstraint())(x)

.......
model.compile(loss=someloss, optimizer=somethingelse)

for ele in model.layers:
    print(ele.kernel_constraint) # Prints some object

model.fit() # Works exactly as I want it to
```
everything works fine and the Constraint works as desired

**Code to reproduce the issue**  
Provide a reproducible test case that is the bare minimum necessary to generate the problem.  

**Other info / logs**  
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.  

Clearly I cannot do the second one if I want to take the model as an unknown input to my program. So I need a way to add constraint to the layers of a model that has already been declared

**Comment by gowtham-kp** [comment]
Hi @prakharg24, 2nd way that you implemented custom constraint is the right way:

Look at how in-built constraints are implemented:
https://github.com/keras-team/keras/blob/master/keras/constraints.py

And then use CustomConstraint in the same way as in-built:

model.add(Dense(64, kernel_constraint= CustomConstraint(your', parameters', go', here')))

Hope this helps :)

**Comment by prakharg24** [comment]
I know the 2nd way works perfectly, but I want to make some way of making it work in the 1st case too.

Let me add more details to my problem,

Lets say you have a model object 'm' and you want to add custom constraints to it. How will you design a function to do that? You know nothing about the model architecture beforehand because someone else designed it, not you. So you need to work with this object 'm' and try to add custom constraint to every layer (or some layers) present in it.

My current workaround is,

```
all_params = []
for layer in model.layers:
    param_dict = {}
    if('conv' in model.name):
        param_dict['type'] = 'conv'
        param_dict['name'] = ele.name
        param_dict['filters'] = ele.filters
        ..... # other parameters that I think are important with respect to this layer
    elif('flatten' in model.name):
        .... # Do the same for other layers too
    
    all_params.append(param_dict)

model = Sequential()
for ele in params_dict:
    if(ele['type']=='conv'):
        model.add(Conv2d(name=ele['name'], filters= ele['filter'] .... , kernel_constraint=CustomConstraint())
    elif(ele['type']=='dense'):
    ..... # and so on for all the layers


```

The above code can do what I want but assumes that I know what all type of possible layers can be and also what all parameters in them might ever have any input other than the default values. It also assumes a certain relation between the layer name and its type, but we can skip that for now (I know how to solve that, I just haven't gotten to it yet).

Is there a better way of doing this? 
I hope this clears up what I want.

Thanks :)

**Comment by prakharg24** [comment]
Any updates? @gowtham-kp

**Comment by sarathsp1729** [comment]
Any updates on this? Is there any way to get the first code mentioned by @prakharg24 working (adding constraint to layers in existing models)?
