### ISSUE TITLE
Keras incompatible shapes issue when the shape of target data and model output layers are different

### ISSUE THREAD

**Issue by shasut** [keras-team/keras#13102]
Hello, 

I posted this problem in [Stackoverflow](https://stackoverflow.com/questions/56994930/keras-incompatible-shapes-issue-when-the-shape-of-target-data-and-model-output-l) but no response, so, I post it here too. 
Sorry for the long description. 

I have a main_model defined as follows:

```
input_layer=Input(shape=(896,896,3))
new_layer = Conv2D(filters=32, kernel_size=(3,3), padding="same")(input_layer)
new_layer = MaxPooling2D(pool_size=(2, 2), strides=(2,2), padding='same')(new_layer)
new_layer = Conv2D(filters=100, kernel_size=(k,k), dilation_rate=4, padding="same", name="dilation_1")(new_layer)
main_model = Model(input_layer, new_layer)
```
The output layer shape is (448,448,100) and I don't have any target vector (Y_train) of that shape. I produce the target data in a tensor form from the input tensor and use it to calculate the loss using a custom loss function. The loss function uses another Keras model which has all constant kernels and applied to the same input tensor of the main_model to generate the target tensor.

```
y=input_layer #same input tensor from the main_model
y = Conv2D(filters=100, kernel_size=(3,3), padding="same", trainable=False, kernel_initializer='some_custom_method', name="non_trainable_layer")(y)
y=MaxPooling2D(pool_size=(2, 2), strides=(2,2), padding='same')(y)
constant_model=Model(input_layer, y)

constant_model.trainable=False
for l in constant_model.layers:
    l.trainable=False
```

And for the custom loss function, since I do not have the y_true data in the shape of (448,448,100), I generate y_true from the input_layer using the constant_model showed as follows:

```
def custom_loss_wrapper(constant_model):
    def custom_loss(y_true, y_pred):
        eval_true=constant_model(y_true)
        l= keras.losses.mean_absolute_error(eval_true, y_pred)
        return d
    return custom_loss

```
Then I compile and fit the main_model:

```
main_model.compile(optimizer='adam',
          loss=custom_loss_wrapper(constant_model),
          metrics=['accuracy'])

history = model.fit(x=X_train, y=X_train, batch_size=2, ...)

```

It is important that I need to provide y=X_train (which is actually the y_true in the loss function) since this X_train is actually being used to generate the main_model's labels of size (448,448,100)

But, while training, I get the following error:

```
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [2,896,896] vs. [2,448,448]
     [[Node: metrics_1/acc/Equal = Equal[T=DT_INT64, _device="/job:localhost/replica:0/task:0/device:GPU:0"](metrics_1/acc/ArgMax, metrics_1/acc/ArgMax_1)]]
     [[Node: loss_1/mul/_99 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_440_loss_1/mul", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

```

I suppose there is a problem with the size mismatch in the y_true and y_pred.

However, when I do not use any MaxPooling layers in the main_model and constant_model, i.e., the output layer shape is 896,896,100, then there is no error.

Anyone could help me to find out where is the problem?

**Comment by jvishnuvardhan** [comment]
@shasut Can you try using strides=(1,1)? 
It would be better If you can share a standalone code to reproduce the issue. Thanks!

**Comment by shasut** [comment]
> @shasut Can you try using strides=(1,1)?
> It would be better If you can share a standalone code to reproduce the issue. Thanks!

```
import keras
from keras.models import Model
from keras.layers import Conv2D, MaxPooling2D, Input



input_layer=Input(shape=(896,896,3))
new_layer = Conv2D(filters=32, kernel_size=(3,3), padding="same")(input_layer)
new_layer = MaxPooling2D(pool_size=(2, 2), strides=(2,2), padding='same')(new_layer)
new_layer = Conv2D(filters=100, kernel_size=(k,k), dilation_rate=4, padding="same", name="dilation_1")(new_layer)
main_model = Model(input_layer, new_layer)

y=input_layer #same input tensor from the main_model
y = Conv2D(filters=100, kernel_size=(3,3), padding="same", trainable=False, kernel_initializer='some_custom_method', name="non_trainable_layer")(y)
y=MaxPooling2D(pool_size=(2, 2), strides=(2,2), padding='same')(y)
constant_model=Model(input_layer, y)

constant_model.trainable=False
for l in constant_model.layers:
    l.trainable=False

def custom_loss_wrapper(constant_model):
    def custom_loss(y_true, y_pred):
        eval_true=constant_model(y_true)
        l= keras.losses.mean_absolute_error(eval_true, y_pred)
        return d
    return custom_loss

main_model.compile(optimizer='adam',
          loss=custom_loss_wrapper(constant_model),
          metrics=['accuracy'])

X_train = np.random.random(size=(10, 896, 896, 3))

history = model.fit(x=X_train, y=X_train, batch_size=2, epoch=10, verbose=True)

```

**Comment by jvishnuvardhan** [comment]
@shasut Still it is not a standalone code as there are some undefined variables and methods. Can you create a [gist like this](https://colab.sandbox.google.com/gist/jvishnuvardhan/0487c1d018f881ea052629ac66ad6e05/keras_13102.ipynb).  Please also fill template [here](https://github.com/keras-team/keras/issues/new/choose). Thanks!

**Comment by shasut** [comment]
> @shasut Still it is not a standalone code as there are some undefined variables and methods. Can you create a [gist like this](https://colab.sandbox.google.com/gist/jvishnuvardhan/0487c1d018f881ea052629ac66ad6e05/keras_13102.ipynb). Please also fill template [here](https://github.com/keras-team/keras/issues/new/choose). Thanks!



@jvishnuvardhan 
I edited the code in the link. Also provided the code below. 

```
import keras
from keras.models import Model
from keras.layers import Conv2D, MaxPooling2D, Input
import numpy as np


k=3
input_layer=Input(shape=(896,896,3))
new_layer = Conv2D(filters=32, kernel_size=(3,3), padding="same")(input_layer)
new_layer = MaxPooling2D(pool_size=(2, 2), strides=(2,2), padding='same')(new_layer)
new_layer = Conv2D(filters=100, kernel_size=(k,k), dilation_rate=4, padding="same", name="dilation_1")(new_layer)
main_model = Model(input_layer, new_layer)

y=input_layer #same input tensor from the main_model
y = Conv2D(filters=100, kernel_size=(3,3), padding="same", trainable=False, kernel_initializer='he_normal', name="non_trainable_layer")(y)
y=MaxPooling2D(pool_size=(2, 2), strides=(2,2), padding='same')(y)
constant_model=Model(input_layer, y)

constant_model.trainable=False
for l in constant_model.layers:
    l.trainable=False

def custom_loss_wrapper(constant_model):
    def custom_loss(y_true, y_pred):
        eval_true=constant_model(y_true)
        loss= keras.losses.mean_absolute_error(eval_true, y_pred)
        return loss
    return custom_loss

main_model.compile(optimizer='adam',
          loss=custom_loss_wrapper(constant_model),
          metrics=['accuracy'])

X_train = np.random.random(size=(10, 896, 896, 3))

history = main_model.fit(x=X_train, y=X_train, batch_size=2, epochs=10, verbose=True)
```
which generates the following error.

```
Epoch 1/10
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-6-c1167a7996fe> in <module>()
     34 X_train = np.random.random(size=(10, 896, 896, 3))
     35 
---> 36 history = main_model.fit(x=X_train, y=X_train, batch_size=2, epochs=10, verbose=True)

4 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in __call__(self, *args, **kwargs)
   1456         ret = tf_session.TF_SessionRunCallable(self._session._session,
   1457                                                self._handle, args,
-> 1458                                                run_metadata_ptr)
   1459         if run_metadata:
   1460           proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

InvalidArgumentError: Incompatible shapes: [2,896,896] vs. [2,448,448]
	 [[{{node metrics_3/acc/Equal}}]]
```

**Comment by jvishnuvardhan** [comment]
@shasut Please check the [gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/337c3be3d26df05a5d9d7a53758c9e8b/keras_13102_shape.ipynb) that runs without any shape error. Thanks!

**Comment by shasut** [comment]
> @shasut Please check the [gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/337c3be3d26df05a5d9d7a53758c9e8b/keras_13102_shape.ipynb) that runs without any shape error. Thanks!

@jvishnuvardhan Thanks for the code. 

`MaxPool stride = (1,1)` to the `constant_model` and `main_model` will work since for both cases the `X_train` shape, model `output layer` shape and `input layer` shape are the same, i.e. the shape of `x` and `y` data in the `.fit()` function and the model input and output shape for `main_model` and `constant_model` are the same. My question is, why is it not working when I reduce the output size by applying `(2,2)` stride in `MaxPool`. With my model, I have to use the `(2,2)` stride `MaxPool`, since, I need to reduce the size of the features of the output layer. 


The loss function is comparing `eval_true` and `y_pred`.  The `eval_true` comes from `const_model(y_true)`. Therefore the output layer of the `constant_model` has to have the same shape
as the `main_model`. With `stride=(1,1)` the output shape for both models is `(None, 896, 896, 100)`, and the model trains without error. With `stride=(2,2)` also the output shape is the same for both models i.e.  `(None, 448, 448, 100)`, however, raises an error. Why?

**Comment by jvishnuvardhan** [comment]
@shasut There is a shape mismatch in the inputs to the metric (loss) function. One is 448,448 and the other is 896,896. 

Initially, `y_true` and `y_pred` are of 896x896 shape. then, you pass `y_true` to constant_model to get `eval_true` which is when the shape becomes 448x448. Now comparing two different shapes will result in error. Thanks!

**Comment by shasut** [comment]
> @shasut There is a shape mismatch in the inputs to the metric (loss) function. One is 448,448 and the other is 896,896.
> 
> Initially, `y_true` and `y_pred` are of 896x896 shape. then, you pass `y_true` to constant_model to get `eval_true` which is when the shape becomes 448x448. Now comparing two different shapes will result in error. Thanks!

@jvishnuvardhan How is that initially, `y_true` and `y_pred` are of 896x896 shape? `y_pred` has shape of 448x448, since it is the output of the main_model. Would you please explain a bit?

**Comment by jvishnuvardhan** [comment]
@shasut You are training a model with the shape for `input` and `output` which is  896x896`. When you train a model with `output` size as 896x896, then your predicted size is also 896x896. `model.fit(x=X_train, y=X_train, batch_size=2, epoch=10, verbose=True)`

Please check the gist I sent you, and check main_model.summary(), then you can see that output of main_model is `(None, 896, 896, 100)`. Thanks!

I am closing the issue as it was resolved. Thanks again.
