### ISSUE TITLE
Feature Request: built-in ResizeBilinear Layer

### ISSUE THREAD

**Issue by chipfranzen** [keras-team/keras#13115]
I'm requesting a built-in Keras layer for resizing tensors.

Today:
I have to implement this layer either as a Lambda or a custom layer, both of which simply wrap `tensorflow.compat.v1.image.resize_bilinear`. This causes huge headaches for exporting to CoreML and TF-Lite. Existing layers like `Upsampling2d` and `Reshape` do not meet my needs, since I am downsampling to a fixed output size, so scaling by some factor does not work.

CoreML has a built-in `resizeBilinear` layer, but it is difficult to connect my custom Keras layer with that CoreML built-in.

Ideal solution:
There is a built-in Keras layer, I ask the CoreML team to use it, they implement a new layer conversion mapping, and I convert my model without digging into the guts of both Keras and CoreML.

**Comment by jameshfisher** [comment]
[`tf.keras.layers.experimental.preprocessing.Resizing`](https://www.tensorflow.org/api_docs/python/tf/keras/layers/experimental/preprocessing/Resizing) sounds like what you need. Looks like it was added in late 2019.
