### ISSUE TITLE
Sharing the weights for the corresponding layers of two models

### ISSUE THREAD

**Issue by AmirHussein96** [keras-team/keras#13119]
Hello everyone,

I am trying to implement an architecture with two similar models for feature extraction. I need to extract parameters of the corresponding layers of the two models and minimize their norm difference between. Any Ideas how this could be done in Keras?

**Comment by jvishnuvardhan** [comment]
@AmirHussein96 You could use keras functional API. There are lot of resources on Stackoverflow and other places addressing similar architecture. Check Examples on Keras website.

Hi!
This issue isn't related to a bug/enhancement/feature request or other accepted types of issue.
To ask questions, please see the following resources :
[StackOverflow](http://stackoverflow.com/questions/tagged/keras)
[Keras Slack channel](https://keras-slack-autojoin.herokuapp.com)
[Keras.io support](https://keras.io/#support)
[Gitter](https://gitter.im/Keras-io/Lobby)
Thanks!
If you think we made a mistake, please open another issue and fill all the information asked by the template. Thanks!

**Comment by jvishnuvardhan** [comment]
Closing this as it is better asked in other resources. Thanks!
