### ISSUE TITLE
AttributeError: 'zip' object has no attribute 'shape'

### ISSUE THREAD

**Issue by shivg7706** [keras-team/keras#13123]
<em>Please make sure that this is a Bug or a Feature Request and provide all applicable information asked by the template.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.</em>  

**System information**  
- Have I written custom code (as opposed to using example directory):  
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab  
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  1.14.0
- Keras version:  
- Python version: 3.6  
- CUDA/cuDNN version: 10.0  
- GPU model and memory:  15GB

You can obtain the TensorFlow version with:  
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"  
You can obtain the Keras version with:  
python -c 'import keras as k; print(k.__version__)'  

**Describe the current behavior**  
I was writing an image generator for segmentation. As mentioned in docs how to use `zip`, I used in the same way but it through me error as mentioned above

**Comment by gowtham-kp** [comment]
@shivg7706 In order to expedite the issue resolution process can you please provide us a small code snippet so that we will be able to reproduce it on our side and find the cause. Thanks!

**Comment by shivg7706** [comment]
```python
seed = 1
from tensorflow.python.keras.preprocessing.image import ImageDataGenerator

data_gen = ImageDataGenerator(rescale=1./255, validation_split=0.1)


img_gen = data_gen.flow_from_directory('segmentation_dataset/tumorImage/', target_size=(512, 512), batch_size=4,
                                       class_mode=None, seed=seed, color_mode='grayscale')
mask_gen = data_gen.flow_from_directory('segmentation_dataset/maskImage/', target_size=(512, 512), batch_size=4,
                                       class_mode=None, seed=seed, color_mode='grayscale')

train_gen = zip(img_gen, mask_gen)
```

**Comment by shivg7706** [comment]
I found my error.

**Comment by gowtham-kp** [comment]
I have ran this code:
we create two instances with the same arguments
data_gen_args = dict(featurewise_center=True,
                     featurewise_std_normalization=True,
                     rotation_range=90,
                     width_shift_range=0.1,
                     height_shift_range=0.1,
                     zoom_range=0.2)
image_datagen = ImageDataGenerator(**data_gen_args)
mask_datagen = ImageDataGenerator(**data_gen_args)

# Provide the same seed and keyword arguments to the fit and flow methods
seed = 1
image_datagen.fit(images, augment=True, seed=seed)
mask_datagen.fit(masks, augment=True, seed=seed)

image_generator = image_datagen.flow_from_directory(
    'data/images',
    class_mode=None,
    seed=seed)

mask_generator = mask_datagen.flow_from_directory(
    'data/masks',
    class_mode=None,
    seed=seed)

# combine generators into one which yields image and masks
train_generator = zip(image_generator, mask_generator)

model.fit_generator(
    train_generator,
    steps_per_epoch=2000,
    epochs=50)


and I don't get any errors. 

Can you please let me know if you made any changes to the code?

**Comment by shivg7706** [comment]
Didn't you copy-paste the code from Keras/Tensorflow docs.

**Comment by gowtham-kp** [comment]
Yes @shivg7706 I am not running into any error. Can you please provide the exact code you used so that I can work on providing a solution. Thanks!

**Comment by SumanthMeenan** [comment]
@shivg7706  
Bcz u can't zip two infinite generators.
So, we need to return a tuple of img and mask at once using new generator.
def new_generator(a,b): #a,b are image and mask generators
    while 'shiv'=='shiv':
        a1 = a.next()
        b1 = b.next()
        yield(a1[0], b1[0])

**Comment by SumanthMeenan** [comment]
``def new_generator(a,b): #a,b are image and mask generators
      while 'shiv'=='shiv':
           a1 = a.next()
           b1 = b.next()
           yield(a1[0], b1[0])

**Comment by SumanthMeenan** [comment]
In your case, you will get error saying zip object has no attribute shape
Bcz this zip object is passed into training_generator.convert_to_generator_like(data)
And U r passing a generator for data

In this line, you will get error
num_samples = int(nest.flatten(data)[0].shape[0]) 
data is generator
nest.flatten(data)[0] is a zip object and it has no shape

**Comment by shivg7706** [comment]
@SumanthMeenan yes, you are right, I end up writing my own generator.
This should definitely be mentioned in Keras/Tensorflow Docs.

**Comment by graffam** [comment]
so what is the actual solution here? The docs are clearly incorrect. I just tried with Tensorflow 2.0 as well as Tensorflow 1.14 I get the same error as @shivg7706. The same code works with 1.11 and 1.12. Brand new instance, copy and paste the reference code and ran it...zip error.

**Comment by shivg7706** [comment]
@graffam simple write your own generator.

**Comment by kevinkepp** [comment]
The keras implementation in TF 1.14 and TF 2.0-RC seems to not recognize zip objects as generators or sequences. I created a [bug](https://github.com/tensorflow/tensorflow/issues/32357) for the TensorFlow project.

Workaround for now: Create an inline generator
`train_gen = (pair for pair in zip(img_gen, mask_gen))`
