### ISSUE TITLE
Multi_gpu_model fails with improved wasserstein GAN.

### ISSUE THREAD

**Issue by ckyleda** [keras-team/keras#13122]
**System information**  
- Have I written custom code (as opposed to using example directory):  
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Ubuntu 18.04
- TensorFlow backend (yes / no):  Yes
- TensorFlow version:  1.12.0
- Keras version:  2.2.4
- Python version:  3.6
- CUDA/cuDNN version:  -
- GPU model and memory:  K80 12GB x2

**Describe the current behavior**  

The improved wasserstein GAN requires the gradients of a model to be extracted with regard to some averaged training samples. These gradients are then used to train the discriminator.
However, when trying to use multi_gpu_model on this model, despite the model **working on a single GPU** the model fails to compile with the following error:

```
Traceback (most recent call last):
  File "progan.py", line 402, in <module>
    G, D, GAN, Discriminator = construct_models(lod, a)
  File "progan.py", line 360, in construct_models
    Discriminator.compile(optimizer=adam, loss=[wasserstein_loss_reals, wasserstein_loss, partial_gp_loss])
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 342, in compile
    sample_weight, mask)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/keras/engine/training_utils.py", line 404, in weighted
    score_array = fn(y_true, y_pred)
  File "progan.py", line 76, in gradient_penalty_loss
    gradients_sqr = K.square(gradients)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 1470, in square
    return tf.square(x)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 342, in square
    return gen_math_ops.square(x, name=name)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 8197, in square
    "Square", x=x, name=name)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 528, in _apply_op_helper
    (input_name, err))
ValueError: Tried to convert 'x' to a tensor and failed. Error: None values not supported.
```

It looks like for whatever reason trying to call K.gradients on the model that multi_gpu_model creates returns a tensor with None values. Why is this happening?

The loss function in use is the common WGAN-GP keras loss and looks like this:
```
def gradient_penalty_loss(y_true, y_pred, averaged_samples,
                          gradient_penalty_weight):
    gradients = K.gradients(y_pred, averaged_samples)[0]
    gradients_sqr = K.square(gradients)
    gradients_sqr_sum = K.sum(gradients_sqr,
                              axis=np.arange(1, len(gradients_sqr.shape)))
    gradient_l2_norm = K.sqrt(gradients_sqr_sum)
    gradient_penalty = gradient_penalty_weight * K.square(1 - gradient_l2_norm)
    return K.mean(gradient_penalty)`
```
I printed out the values at compile time of the averaged_samples, y_pred, and  K.gradients and get:

Tensor("random_weighted_average_1/add:0", shape=(12, 4, 4, 3), dtype=float32)
Tensor("model_2_3_1/concat:0", shape=(24, 1), dtype=float32, device=/device:CPU:0)
[None]

My batch size at input is 12. I expected this to be split into two models each processing 6 samples, but it looks like instead the multi_gpu_model is being given 12 samples each and concatenating them into 24 total?

Any ideas on how to fix this? It seems multi_gpu_model doesn't handle models with multiple inputs/multiple outputs and custom loss functions very well. 

Perhaps somebody has managed to get this sort of model working across multiple GPUs?

**Comment by ckyleda** [comment]
If anyone would like to reproduce this easily, simply take the keras-contrib improved Wasserstein GAN available here:

https://github.com/keras-team/keras-contrib/blob/master/examples/improved_wgan.py

And make the discriminator a multi_gpu_model.

**Comment by lilili0402** [comment]
I have the same problem as you.
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [8,1,1,1] vs. [4,512,512,3]  
[[{{node replica_0/model_3/random_weighted_average_1/mul}}]]                                                    
[[{{node replica_1/model_3/model_2_2/activation_26/Sigmoid}}]]

**Comment by lilili0402** [comment]
As for the first problem, I run my code on CPU normally, runon gpu will report this error, the solution is:
[
![image](https://user-images.githubusercontent.com/32262125/61770969-1cb09880-ae21-11e9-9cae-de2f20b48ad2.png)
](url)

**Comment by lilili0402** [comment]
As for the first problem, I run my code on CPU normally, runon gpu will report this error, the solution is:
[https://github.com/tensorflow/tensorflow/issues/783](url)

**Comment by lilili0402** [comment]
https://github.com/tensorflow/tensorflow/issues/783#issuecomment-238734067
[https://github.com/tensorflow/tensorflow/issues/783#issuecomment-238734067](url)

**Comment by lilili0402** [comment]
As for the first problem, I run my code on CPU normally, run on gpu will report this error, the solution'link
[https://github.com/tensorflow/tensorflow/issues/783#issuecomment-238734067](url)

**Comment by lilili0402** [comment]
As for the first problem, I run my code on CPU normally, run on gpu will report this error.
`def replace_none_with_zero(l):
return [0 if i==None else i for i in l]

grads = replace_none_with_zero(tf.gradients([grads[0]], [x, y]))`

**Comment by lilili0402** [comment]
Gradient problem, you can try:
`def repalce_none_with_zero(l):
       return [K.zeros((1)) if i==None else i for i in l]
gradients=replace_none_with_zero(K.gradients(y_pred,averaged_samples))`

**Comment by lilili0402** [comment]
have successfully run through my code, In clalss:RancomWeightedAverage(_Merge).
we should modify the code `alpha=K.random_uniform((batchsize,1,1,1))` to
`alpha=K.random_uniform((int(batchsize/gpus_num),1,1,1))`

**Comment by ckyleda** [comment]
> Gradient problem, you can try:
> `def repalce_none_with_zero(l): return [K.zeros((1)) if i==None else i for i in l] gradients=replace_none_with_zero(K.gradients(y_pred,averaged_samples))`

Hi there, testing your other solution now. But be aware that with the above tensorflow doesn't allow you to just iterate through tensors like that.

**Comment by ckyleda** [comment]
@lilili0402 

Changing the implementation to ```alpha=K.random_uniform((int(batchsize/gpus_num),1,1,1))``` causes the error below:

```tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [32,1,1,1] vs. [64,28,28,1]```

How did you resolve that?

**Comment by ckyleda** [comment]
Okay, I have the code executing, but unfortunately this does NOT resolve the problem as the gradients are always None, and hence always zero, which renders that section of the loss function useless.

So while the model is running, it isn't actually working. Back to square one!

**Comment by Mofafa** [comment]
I solved this problem by replacing 'y_pred' in your gradient_penalty_loss function

``
self.discriminator_model = multi_gpu_model(self.discriminator_model, gpus=gpu_num)
self.discriminator_model.compile(optimizer=Adam(0.0001, beta_1=0.5, beta_2=0.9),
                                loss=[wasserstein_loss,
                                    wasserstein_loss,
                                    partial_gp_loss],
                                name='discriminator')

#replacing 'y_pred' in your gradient_penalty_loss function
gradients = K.gradients(self.discriminator_model.get_layer('discriminator').outputs[-1], averaged_samples)[0]
``

**Comment by ckyleda** [comment]
> I solved this problem by replacing 'y_pred' in your gradient_penalty_loss function
> 
> ```
> self.discriminator_model = multi_gpu_model(self.discriminator_model, gpus=gpu_num)
> self.discriminator_model.compile(optimizer=Adam(0.0001, beta_1=0.5, beta_2=0.9),
>                                 loss=[wasserstein_loss,
>                                     wasserstein_loss,
>                                     partial_gp_loss],
>                                 name='discriminator')
> 
> #replacing 'y_pred' in your gradient_penalty_loss function
> gradients = K.gradients(self.discriminator_model.get_layer('discriminator').outputs[-1], averaged_samples)[0]
> ```

I'll give this a try. 
Would you provide a full code listing? For example, which layer has the name "discriminator" ? (I assume it's the output but would be good to be sure.)

**Comment by Mofafa** [comment]
> > I solved this problem by replacing 'y_pred' in your gradient_penalty_loss function
> > ```
> > self.discriminator_model = multi_gpu_model(self.discriminator_model, gpus=gpu_num)
> > self.discriminator_model.compile(optimizer=Adam(0.0001, beta_1=0.5, beta_2=0.9),
> >                                 loss=[wasserstein_loss,
> >                                     wasserstein_loss,
> >                                     partial_gp_loss],
> >                                 name='discriminator')
> > 
> > #replacing 'y_pred' in your gradient_penalty_loss function
> > gradients = K.gradients(self.discriminator_model.get_layer('discriminator').outputs[-1], averaged_samples)[0]
> > ```
> 
> @Mofafa I'll give this a try.
> Would you provide a full code listing? For example, which layer has the name "discriminator" ? (I assume it's the output but would be good to be sure.)
> 
> How does this work considering multi_gpu_model renames layers to ensure there's no clash between them? (I simply get "No such layer: discriminator")

Sorry for my mistake. I didn't use the original code in your link and made a mistake. Now I've changed it. You need to name your discriminator_model when you use 'Model' to build it.  'multi_gpu_model' will  take your discriminator_model as a layer.

**Comment by ckyleda** [comment]
@Mofafa 

Great, I can confirm that appears to work! The gradients exist and the GPUs are being utilised. Haven't checked the outputs yet.

I believe the issue should remain open though as this is still an issue for standard multi_gpu_model use.
