### ISSUE TITLE
Memory Error--Input Data Are Huge

### ISSUE THREAD

**Issue by yourtheron** [keras-team/keras#13139]
<em>Please make sure that this is a Bug or a Feature Request and provide all applicable information asked by the template.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.</em>  

**System information**  
- Have I written custom code (as opposed to using example directory):  
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):   Windows7
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  1.13.1
- Keras version:  2.2.4
- Python version:  3.7
- CUDA/cuDNN version:  NVIDIA Quadro K620M
- GPU model and memory:  2048MB

You can obtain the TensorFlow version with:  
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"  
You can obtain the Keras version with:  
python -c 'import keras as k; print(k.__version__)'  

**Describe the current behavior**  
Each of my input vector is [1 256], and I have to load around 10^7 such vectors to train them as a whole by an autoencoder in order to extract features. When I try to load them, Keras gives a MemoryError. Yes when I use a smaller training set, it works.

**Describe the expected behavior**  
I want to know the limit/maximum size of arrays allowed in Kears. Or is that because my GPU memory is too small?

**Code to reproduce the issue**  
Provide a reproducible test case that is the bare minimum necessary to generate the problem.  
The following is the configuration of the autoencoder
`
ConvFilters = [128, 128, 128]
KernelSize = [[5, 1], [5, 1], [5, 1]]
stride = [1, 1, 1]
ArraySize = [1, 256]
DenseLayerDims = [256, 196, 128, 64, 32, 16, 4]
        # Encoder
        InShape = (self.ArraySize[0], self.ArraySize[1], 1)
        EncoderInput = Input(shape=InShape, name='Encoder_Input')
        x = EncoderInput
        i = 0
        for CurFilter, CurKernelSize, CurStride, in zip(self.ConvFilters, self.KernelSize, self.stride):
            x = Conv2D(filters=CurFilter,
                       kernel_size=CurKernelSize,
                       strides=CurStride,
                       kernel_regularizer= CurRegulariser,
                       activation=self.activation[0],
                       padding='same',
                       name = 'Conv2D_' + str(i))(x)
            i += 1
            
        self.shape = K.int_shape(x)
        x = Flatten(name='Flatten_Tensor')(x)
        
        i = 0
        for DenseLayerDim in self.DenseLayerDims:
            x = Dense(DenseLayerDim,
                      activation=self.activation[1],
                      kernel_initializer = 'glorot_normal',
                      bias_initializer = RandomNormal(mean=0.0, stddev=1.0),
                      kernel_regularizer= CurRegulariser,
                      name = 'Dense_Encoder_' + str(i))(x)
            i += 1
        
        latent = x  
        self.encoder = Model(EncoderInput, latent, name='Encoder')
        
        # Decoder
        # The middle hidden layer needs not to be involved
        LatentInput = Input(shape=(self.DenseLayerDims[-1],), name='Decoder_Input')
        
        i = 0
        ListDenseDim = self.DenseLayerDims[0:-1]
        ListDenseDim = ListDenseDim[::-1]
        ListDenseDim.append(self.shape[1] * self.shape[2] * self.shape[3])
        x = LatentInput
        for DenseLayerDim in ListDenseDim:
            x = Dense(DenseLayerDim,
                      activation=self.activation[1],
                      kernel_initializer = 'glorot_normal',
                      bias_initializer = RandomNormal(mean=0.0, stddev=1.0),
                      kernel_regularizer= CurRegulariser,
                      name = 'Dense_Decoder_' + str(i))(x)
            i += 1            

        x = Reshape((self.shape[1], self.shape[2], self.shape[3]), name='Construct_Tensor')(x)
        i = 0
        for CurFilter, CurKernelSize, CurStride, in zip(self.ConvFilters[::-1], self.KernelSize[::-1], self.stride[::-1]):
            x = Conv2DTranspose(filters=CurFilter,
                                kernel_size=CurKernelSize,
                                strides=CurStride,
                                kernel_regularizer= CurRegulariser,
                                activation=self.activation[0],
                                padding='same',
                                name = 'Conv2DTranspose_' + str(i))(x)
            i += 1
        x = Conv2DTranspose(filters=1,
                kernel_size=self.KernelSize[0],
                kernel_regularizer= CurRegulariser,
                padding='same',
                name = 'Conv2DTranspsze_Last')(x)    
        x = Activation(self.activation[2], name='Decoder_output')(x)
        if self.CustomActivation[0] == 1:
            DecoderOutput = QPWC(self.CustomActivation[1], DataType = self.precision, name='QPWC')(x)
        else:
            DecoderOutput = x
        self.decoder = Model(LatentInput, DecoderOutput, name='Decoder')
        
        # Autoencoder
        self.autoencoder = Model(EncoderInput, self.decoder(self.encoder(EncoderInput)), name='autoencoder')
  `
**Other info / logs**  
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by yourtheron** [comment]
I have 15.7GB RAM, andI try to establish a 10**7*1*256 float32 array (9.5367GB)

**Comment by gowtham-kp** [comment]
@yourtheron This is related to the similar issue [#5199](https://github.com/keras-team/keras/issues/5199). Your GPU is running out of memory as the number of parameters that are stored to calculate gradients are huge. 

My suggestion would be to use tf.data.Dataset which will iterate over data from disk.
(https://www.tensorflow.org/beta/tutorials/load_data/text#split_the_dataset_into_text_and_train_batches, https://www.tensorflow.org/beta/guide/keras/training_and_evaluation#training_evaluation_from_tfdata_datasets)
