### ISSUE TITLE
permission denied for keras docker jupyter  notebook 

### ISSUE THREAD

**Issue by naveen584** [keras-team/keras#13132]
i want to run keras with nvidia-docker, docker image pull successfully but when i try to  open python from jupyter notebook,it giving a issue of  permission denied.

**Comment by gowtham-kp** [comment]
@naveen584 Can you please post the snippet of error message so that we can take a look at it. Thanks!

**Comment by fvictorio** [comment]
This is happening to me too:

![image](https://user-images.githubusercontent.com/417134/74888339-71d36f00-535c-11ea-8df4-31178898986c.png)

There's a POST request to `/api/contents` that is returning a 403 status code.
