### ISSUE TITLE
load_model requires h5py

### ISSUE THREAD

**Issue by python1995** [keras-team/keras#13148]
I used the code and everything from the here.
https://github.com/autorope/donkey2
I was at the point were I went to run the code and see if the machine learning has worked and mz car can  go through a path detecting the lines

However I'm getting this

(env) pi@raspberrypi:~/donkey2 $ python drive.py --model model_2019-07-24__18-43
using donkey version: 2.5.8 ...
/home/pi/.local/lib/python3.5/site-packages/env/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.4 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.5
  return f(*args, **kwds)
/home/pi/.local/lib/python3.5/site-packages/env/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: builtins.type size changed, may indicate binary incompatibility. Expected 432, got 412
  return f(*args, **kwds)
loading config file: /home/pi/donkey2/config.py
config loaded
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Webcam loaded.. .warming camera
Starting Donkey Server...
Traceback (most recent call last):
  File "drive.py", line 142, in <module>
    drive(cfg, model_path=args['--model'])
  File "drive.py", line 52, in drive
    kl.load(model_path)
  File "/home/pi/.local/lib/python3.5/site-packages/env/lib/python3.5/site-packages/donkeypart_keras_behavior_cloning/part.py", line 17, in load
    self.model = load_model(model_path)
  File "/home/pi/.local/lib/python3.5/site-packages/env/lib/python3.5/site-packages/tensorflow/python/keras/engine/saving.py", line 187, in load_model
    raise ImportError('`load_model` requires h5py.')
ImportError: `load_model` requires h5py.

**Comment by gowtham-kp** [comment]
@python1995 
Just install necessary packages
```
sudo apt-get install libhdf5-dev
pip install h5py
```
This should work.
I am closing the issue. But if you are still facing the issue, you can reopen it again. Thanks!

**Comment by python1995** [comment]
@gowtham-kp 
One quick question. As u saw I was working in an environment.
Do I still use  sudo when installing  the packages _

**Comment by gowtham-kp** [comment]
@python1995 Please refer to this [link](https://stackoverflow.com/questions/15028648/is-it-acceptable-and-safe-to-run-pip-install-under-sudo) which has been beautifully answered.
