### ISSUE TITLE
cloning layers in keras

### ISSUE THREAD

**Issue by sabyUWO** [keras-team/keras#13140]
Is cloning layers possible in Keras? , it's done in torch7 in the following way : 

    lin_net1c = lin_net1:clone('weight','bias','gradWeight','gradBias')
    lin_net2c = lin_net2:clone('weight','bias','gradWeight','gradBias')

**Comment by jvishnuvardhan** [comment]
@sabyUWO Are you looking to clone a model or just clone layers? 
You could clone a model as follows.

```
model_cloned = keras.models.clone_model(model)
# As Keras only copy architecture of the model, not the weights. Need to set_weights as follows.
model_cloned.set_weights(model.get_weights())
```

If you are looking to clone layers, please give more details about the use-case and what do you mean by cloning? Thanks!

**Comment by jvishnuvardhan** [comment]
Automatically closing this out since I understand it to be resolved, but please let me know if I'm mistaken.Thanks!

**Comment by Santosh-Gupta** [comment]
I am interested in cloning a layer. My use case is to make a new model , using pretrained layers of other models. 

Here's my attempt, which doesn't seem to work 

```def get_mini_models():
    tempModel = TFRobertaModel.from_pretrained('bert-base-uncased', from_pt=True)

    layer9 = tempModel.layers[0].encoder.layer[8]
    layer10 = tempModel.layers[0].encoder.layer[9]

    inputHiddenVals = tf.keras.Input(shape=[None, 768], dtype=tf.float32, name='input_Q',
                                    batch_size=None) 

    hidden1 = layer9((inputHiddenVals, None, None), training=True)
    hidden2 = layer10((hidden1[0], None, None), training=True)
    modelNew = tf.keras.Model(inputs=inputHiddenVals, outputs=hidden2)

    del tempModel

    return modelNew```

**Comment by sabyUWO** [comment]
Can you copy the weights only and use it instead of the structure?

**Comment by Santosh-Gupta** [comment]
What do you mean?

**Comment by AlexKubiesa** [comment]
Would this work?

```
config = layer.get_config()
weights = layer.get_weights()
cloned_layer = type(layer).from_config(config)
cloned_layer.build(layer.input)
cloned_layer.set_weight(weights)
```

**Comment by phobrain** [comment]
How would you add cloned_layer to a model? E.g. something like,

    image_model = vars()[IMAGENET_MODEL](include_top=False, weights='imagenet')
    top = image_model.output
    top = top + cloned_layer?
    real_model = Model(image_model.input, [top])

**Comment by AmeerArsala** [comment]
> How would you add cloned_layer to a model? E.g. something like,
> 
> ```
> image_model = VGG16(include_top=False, weights='imagenet')
> top = image_model.output
> top = top + cloned_layer?
> real_model = Model(image_model.input, [top])?
> ```

```
class CustomModel(tf.keras.Model):
  def __init__(self, top_layer, **kwargs):
    super().__init__(**kwargs)
    vgg_model = VGG(include_top=False, weights='imagenet')
    
    self.vgg_layers = vgg_model.layers
    self.top_layer = top_layer

  def call(self, inputs, **kwargs):
    x = inputs
    for vgg_layer in self.vgg_layers:
      x = vgg_layer(x)
    
    x = self.top_layer(x)

    return x
```
