### ISSUE TITLE
reshaping input layer before passing to model

### ISSUE THREAD

**Issue by spartian** [keras-team/keras#13158]
I am trying to combine CNN with attention networks. I have a rather unusual requirement or it might be because I have not understood keras functionality properly. I have a source code from GitHub which I am trying to modify. A section of code is below:-

```
        texts_in = Input(shape=(MAX_SEQ_LEN,config.doc_size), dtype='int32')
            
        attention_weighted_sentences = TimeDistributed(attention_weighted_sentence)(texts_in)
            
            
        if rnn_type is 'GRU':
                #sentence_encoder = Bidirectional(GRU(50, return_sequences=True, dropout=0.1, recurrent_dropout=0.2))(attention_weighted_sentences)
                dropout = Dropout(0.1)(attention_weighted_sentences)
                sentence_encoder = Bidirectional(GRU(50, return_sequences=True))(dropout)
        else:
                sentence_encoder = Bidirectional(LSTM(50, return_sequences=True, dropout=0.1, recurrent_dropout=0.2))(attention_weighted_sentences)
            
            
        dense_transform_sentence = Dense(
                100, 
                activation='relu', 
                name='dense_transform_sentence',
                kernel_regularizer=l2_reg)(sentence_encoder)
            
            # sentence attention
        attention_weighted_text = Attention(name="sentence_attention")(dense_transform_sentence)
            
        out = Dense(
            data.documents.target_dim, init=my_init,
            W_regularizer=W_regularizer(config),
            activation='sigmoid'
            )(attention_weighted_text)
        
        # prediction = Dense(19, activation='sigmoid')(attention_weighted_text)       
        # texts_in = Reshape((500,))(texts_in) 
        model = Model(input = texts_in, output= out)
        model.summary()
```

The value of MAX_SEQ_LEN is 1 and config.doc_size is 500 in input layer i.e. texts_in. The reason I have kept the former value as 1 is because I want to reshape the input to (None,500) and don't want input as (None,1,500). 

However, since Timedistributed Layer does not take only 2 dims as input so I have to initialize it with (1,500). Is there anyway to reshape the input before passing to the model. Right now, if I reshape the input before passing to model, I get graph disconnected error which is fairly understandable. 

However, as I stated I want only 2 dimension for input layer which is None and 500. Can it be done and passed to TimeDistributed Layer or reshaped later?

**Comment by kiblee** [comment]
`MAX_SEQ_LEN=1` indicates that your input is not a sequence. Why not just use `Dense` instead of `TimeDistributed`?

**Comment by spartian** [comment]
Thanks for the suggestion kiblee...Will try it

**Comment by spartian** [comment]
Thank you ...kiblee....works out fine now...

**Comment by spartian** [comment]
I have combined cnn and attention network but it's hardly been accurate....When I run CNN differently and attention network differently I get F1-score of 0.82 and 0.83 respectively. However when I combine them my F1-score is just 0.45. I think the way I combined them has been wrong. Could you suggest something regarding it?
