### ISSUE TITLE
TypeError: flow_from_directory() got multiple values for argument 'target_size'

### ISSUE THREAD

**Issue by Javilonte** [keras-team/keras#13153]
Hello, i've been trying to do some basic stuff with keras by using easy examples of pre procesing with images, but at the time that im trying to set the values for the data gen it tells me that i got multiple values for the target size argument but as it says in the example you need two arguments, i also tried by setting those two values into a new variable called "tarjeto" but it doesnt work neither, this is what i got:
---------------------------------------------------------------------------
imagen_entrenamiento = entrenamiento_datagen.flow_from_directory(
    data_entrenamiento,
    '.data/entrenamiento/d1',
    target_size=tarjeto,
    batch_size=32,
    class_mode='categorical'
    )
TypeError                                 Traceback (most recent call last)
<ipython-input-8-3b753da4768e> in <module>
      4     target_size=tarjeto,
      5     batch_size=32,
----> 6     class_mode='categorical'
      7     )

TypeError: flow_from_directory() got multiple values for argument 'target_size'

**Comment by gowtham-kp** [comment]
@Javilonte Target size is a Tuple of integers (height, width), default: (256, 256). Can you please print and share out shape and the values of Tarjeto. Thanks!

**Comment by Javilonte** [comment]
Thanks for commenting, yes actually i know that i needs to take 2 integers but because of the error i tried to put those two values (150,150) into Tarjeto, so basically tarjeto values are (150,150).
Btw i also tried by just setting the value to (150,150)

**Comment by Sidharth99** [comment]
Any Updates on this issue? I am facing same error. Please help.
Thanks.

**Comment by Murtaza-Kazmi** [comment]
Stuck on the same error x2

**Comment by aish-where-ya** [comment]
If you look at the function signature given [here](https://keras.io/api/preprocessing/image/#flowfromdirectory-method), you'll notice the problem.
You need to pass the directory name and target_size is the next parameter. But you have passed 2 positional parameters when only 1 is required -  the path to the directory.
Instead of 
`data_entrenamiento,
'.data/entrenamiento/d1',`

pass only 
`'.data/entrenamiento/d1',` to the function. 
The error gets resolved.

**Comment by Murtaza-Kazmi** [comment]
Yeah^ this is right. 
I forgot to comment this sadly, so thanks

Another thing maybe that you want to use  entrenamiento_datagen.flow instead of  entrenamiento_datagen.flow_from_directory
