### ISSUE TITLE
Output of generator should be a tuple. Found: None

### ISSUE THREAD

**Issue by LiframCastle** [keras-team/keras#13167]
I'm guessing the error is on my generator but I can't find where exactly

```
def batch_generator(X1_gen,X2_gen,Y_gen):
        while true: 
            yield ([X1_gen.next(),X2_gen.next()],Y_gen.next())

image_datagen_1.fit(X, augment=True, seed=seed)
image_datagen_2.fit(X1, augment=True, seed=seed)
mask_datagen.fit(Y, augment=True, seed=seed)

image_generator_1 = image_datagen_1.flow_from_directory(
    os.path.join(train_dir, 'colored_0'),
    class_mode=None,
    batch_size=batch_size,
    target_size=(376,1241))

image_generator_2 = image_datagen_2.flow_from_directory(
    os.path.join(train_dir, 'colored_1'),
    class_mode=None,
    batch_size=batch_size,
    target_size=(376,1241))

mask_generator = mask_datagen.flow_from_directory(
    os.path.join(train_dir, 'disp_noc'),
    class_mode=None,
    batch_size=batch_size,
    target_size=(376,1241))

train_generator = batch_generator(image_generator_1,image_generator_2, mask_generator)
```

I have been using Keras documentation to guide myself. This is the error I get:

output of generator should be a tuple `(x, y, sample_weight)` or `(x, y)`. Found: None

**Comment by bozcani** [comment]
I think "class_mode" shouldn't be 'None' for training and validation generators. You can change it to "binary", "categorical" or "input" according to your label format. (If you have 2 classes -> "binary",  more than 2 classes -> "categorical", autoencoder output ->"input" ).

**Comment by LiframCastle** [comment]
> I think "class_mode" shouldn't be 'None' for training and validation generators. You can change it to "binary", "categorical" or "input" according to your label format. (If you have 2 classes -> "binary", more than 2 classes -> "categorical", autoencoder output ->"input" ).

Now the error is gone, thanks

**Comment by gowtham-kp** [comment]
Closing the issue as it has been resolved. Thank you @bozcani.
