### ISSUE TITLE
SK-Learn Pipeline containing KerasClassifier cannot be pickled/persisted 

### ISSUE THREAD

**Issue by Permafacture** [keras-team/keras#13168]
KerasClassifier gives an object that cannot be fully used with Sk-Learn's Pipeline.

The following code works:

```
model = Pipeline(steps=[
    ('min_max_scale', MinMaxScaler()),
    ('estimator', SVC(probability=True))
])

model.set_params(**params)
model.fit(X, y > TRUTH_THRESH)

with open(model_file, 'wb') as fh:
    dill.dump(nn_model, fh)
```
If I use a KerasClassifier, fails on dill.dump with a maximum recursion error. I an post the exact traceback if needed but I'd need to obfuscated the paths.

```
nn_model = Pipeline(steps=[
     ('min_max_scale', MinMaxScaler()),
     ('estimator', model.KerasClassifier(build_fn=model.create_keras_model, epochs=40, batch_size=10, verbose=2))
 ])

nn_model.set_params(**nn_params)
nn_model.fit(X, y > TRUTH_THRESH)

with open(model_file, 'wb') as fh:
    dill.dump(nn_model, fh). # FAILS
```

**System information**  
- Mac OSX
- using tensoflow backend  
- TensorFlow version:  1.5
- Keras version:  2.2.0
- Python version:  2.7

This is similar to  #4274  however they were not using a Pipeline.  One user said dill worked for them with a Pipeline but it did not for me.

**Comment by Permafacture** [comment]
I think this is a feature request, not support.  #4274 didn't get a fix, just a few workarounds. Those workarounds don't work here if the intention is for KerasClassifier to be a mostly drop in replacement for another SK-Learn classifier then this is a troublesome difference

**Comment by Permafacture** [comment]
I was able to solve this for myself with a subclass of the sklearn Pipeline.  I think the general fix would be in the keras classifier, not the sklearn pipeline.

Note: quick solution assumes last step is the the classifier (decent assumption) and the unpickled pipeline has just a keras model and not a KerasClassifier because the KerasClassifier is really for exploration, not deployment.
 
```
import io
from sklearn.pipeline import Pipeline
from keras.models import load_model
import h5py

class PickleablePipeline(Pipeline):

    def _pickle_steps(self):
        steps = self.steps[:]
        classifier = steps[-1][1]
        bio = io.BytesIO()
        with h5py.File(bio) as f:
            classifier.model.save(f)
        steps[-1] = (steps[-1][0], bio)
        return steps

    def _unpickle_steps(self, steps):
        with h5py.File(steps[-1][1]) as f:
            steps[-1] = (steps[-1][0], load_model(f))
        return steps

    def __getstate__(self):
        state = super(PickleablePipeline, self).__getstate__()
        state['steps'] = self._pickle_steps()
        return state

    def __setstate__(self, state):
        state['steps'] = self._unpickle_steps(state['steps'])
        return super(PickleablePipeline, self).__setstate__(state)
```

**Comment by gowtham-kp** [comment]
@Permafacture Than you for sharing the solution. Closing this issue as it has been resolved!

**Comment by lpereira95** [comment]
Following @Permafacture solution, I ended up with a fix that acts directly on ```KerasRegressor``` (I'm interested in dump the ```KerasRegressor``` itself, not necessarily a keras model). This solution is slightly more robust, e.g. sometimes I use a ```TransformedTargetRegressor``` in combination with the ```KerasRegressor```.

```python
import h5py
import io
from tensorflow.keras.wrappers.scikit_learn import KerasRegressor
from tensorflow.keras.models import load_model
from sklearn.base import BaseEstimator

class PickleableKerasRegressor(KerasRegressor, BaseEstimator):

    def _pickle_model(self):
        bio = io.BytesIO()
        with h5py.File(bio, 'w') as f:
            self.model.save(f)
        return bio

    def _unpickle_model(self, model):
        with h5py.File(model, 'r') as f:
            model = load_model(f)
        return model 

    def __getstate__(self):
        state = BaseEstimator.__getstate__(self)
        if hasattr(self, 'model'):
            state['model'] = self._pickle_model()
        return state

    def __setstate__(self, state):
        if state.get('model', None):
            state['model'] = self._unpickle_model(state['model'])
        return BaseEstimator.__setstate__(self, state)
```

I know this issue was already closed, but I thought it would be nice to share my solution.

**Comment by marcadella** [comment]
@luisfpereira Your solution is nice, but not working in case one passes a callback. For instance,
`PickleableKerasRegressor(..., callbacks=[keras.callbacks.EarlyStopping()])`
will make the pickling fail with the following error:
`Can't pickle local object 'Layer.add_loss.<locals>._tag_callable'`
