### ISSUE TITLE
How to predict after random crop(training image shape is different with predict image shape)

### ISSUE THREAD

**Issue by EricSheng0402** [keras-team/keras#13184]
I want to use random crop to train my network, as the original shape is (256,1024,3),
I use the input shape (256,512,3) for training, but when I try to predict original image which shape is (256,1024,3), I got this error:
Error when checking input: expected input_1 to have shape (256, 512, 3) but got array with shape (256, 1024, 3)
seems like in keras the input shape should be fixed, right now I just divide input data into 2 image and combine them after prediction.
Is there a better solution for that?
THX a lot!
i just switch caffe to keras, in caffe this shouldn't be a problem.

**Comment by PhilipMay** [comment]
You say "I use the input shape (256,512,3) for training".
And you say: "I try to predict original image which shape is (256,1024,3)".

This shape simply does not fit... That's the error.

**Comment by EricSheng0402** [comment]
@PhilipMay  
thanks for your replay, I know this error is very obvious...
Maybe I didn't describe it clearly, I'm training segmentation network which the input and output of the network will be the same.
Because I use random crop for training, so the training image will be smaller than original image, like training (256,512,3) and predict (256,1024,3).
So there will be a problem that the shape of image to be predicted is different with training image, which is not a problem in caffe. I can use  (256,512,3) for training and  (256,1024,3) for prediction.
So I'm asking, is it possible in keras.

**Comment by maderafunk** [comment]
@EricSheng0402 

Yes, that's possible in Keras.
When you create your model, you should give each layer an individual name. After training, you can save that model. Then you create a new model, which is exactly build the same, has the same names, but the input layer has a different shape. You can then create that model, and load the weights of the trained model into that model with the option by_name=True:
`model.load_weights('my_model_weights.h5', by_name=True)` 

See the FAQ for details:

https://keras.io/getting-started/faq/#how-can-i-save-a-keras-model
