### ISSUE TITLE
Subclassing API model doesn't work when calling first then fitting

### ISSUE THREAD

**Issue by zaccharieramzi** [keras-team/keras#13187]
**System information**  
- Have I written custom code (as opposed to using example directory):  yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Ubuntu 16.04
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  1.14.0 (gpu)
- Keras version:  2.2.4
- Python version:  3.6.8
- CUDA/cuDNN version:  V10.0.130
- GPU model and memory:  Quadro P5000 (16GB)

**Describe the current behavior** 
So the problem when calling the model first, is that it [builds it](https://github.com/keras-team/keras/blob/master/keras/engine/base_layer.py#L426) (using `Layer`'s `build`), but doesn't set the outputs. Therefore, when assigning the loss function, the model thinks it's already built, but [doesn't have outputs](https://github.com/keras-team/keras/blob/master/keras/engine/training.py#L143).
In most cases it works, because when the model is not built during a call to `fit`, which in turns call `_standardize_user_data`, `_set_inputs` is called which [assigns the outputs.](https://github.com/keras-team/keras/blob/master/keras/engine/training.py#L644).

**Describe the expected behavior**  
I think the inputs should be set regardless of whether the model was built before. But I am not familiar at all with the overall complex behaviours of models, so I don't know if it makes sense or not, and why `_set_inputs` is only called if the model is not built.

**Code to reproduce the issue**  
Using the vanilla subclassing example [from the docs](https://keras.io/models/about-keras-models/#model-subclassing):
```python
import keras

class SimpleMLP(keras.Model):

    def __init__(self, use_bn=False, use_dp=False, num_classes=10):
        super(SimpleMLP, self).__init__(name='mlp')
        self.use_bn = use_bn
        self.use_dp = use_dp
        self.num_classes = num_classes

        self.dense1 = keras.layers.Dense(32, activation='relu')
        self.dense2 = keras.layers.Dense(num_classes, activation='softmax')
        if self.use_dp:
            self.dp = keras.layers.Dropout(0.5)
        if self.use_bn:
            self.bn = keras.layers.BatchNormalization(axis=-1)
            
    def compute_output_shape(self, input_shape):
        return [input_shape[0], self.num_classes]

    def call(self, inputs):
        x = self.dense1(inputs)
        if self.use_dp:
            x = self.dp(x)
        if self.use_bn:
            x = self.bn(x)
        return self.dense2(x)

model = SimpleMLP()
model.compile(optimizer='adam', loss='mean_absolute_error',)
model(tf.convert_to_tensor(np.random.rand(36, 512).astype('float32')))
model.fit(x=np.random.rand(36, 512), y=np.random.rand(36, 10))
```

**Other info / logs**  
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-7886f253e840> in <module>
     30 model.compile(optimizer='adam', loss='mean_absolute_error',)
     31 model(tf.convert_to_tensor(np.random.rand(36, 512).astype('float32')))
---> 32 model.fit(x=np.random.rand(36, 512), y=np.random.rand(36, 10))

~/workspace/keras/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
   1090             sample_weight=sample_weight,
   1091             class_weight=class_weight,
-> 1092             batch_size=batch_size)
   1093 
   1094         # Prepare validation data.

~/workspace/keras/keras/engine/training.py in _standardize_user_data(self, x, y, sample_weight, class_weight, check_array_lengths, batch_size)
    728                              metrics=self.metrics,
    729                              loss_weights=self.loss_weights,
--> 730                              target_tensors=target_tensors)
    731 
    732         # If `x` and `y` were all symbolic,

~/workspace/keras/keras/engine/training.py in compile(self, optimizer, loss, metrics, loss_weights, sample_weight_mode, weighted_metrics, target_tensors, **kwargs)
    141         else:
    142             import pdb; pdb.set_trace()
--> 143             loss_function = losses.get(loss)
    144             loss_functions = [loss_function for _ in range(len(self.outputs))]
    145         self.loss_functions = loss_functions

TypeError: object of type 'NoneType' has no len()
```

**Comment by PhilipMay** [comment]
I suggest to rebuild the model with
[Keras Sequential model](https://keras.io/getting-started/sequential-model-guide/)
or
[Keras functional API](https://keras.io/getting-started/functional-api-guide/).
