### ISSUE TITLE
Where can I see the implementation of LSTM?

### ISSUE THREAD

**Issue by rezaee** [keras-team/keras#13192]
I am looking for file(s) that consist of implementation of LSTM.

**Comment by PhilipMay** [comment]
- LSTM: https://github.com/keras-team/keras/blob/master/keras/layers/recurrent.py#L2077
- LSTM implementation with CuDNN: https://github.com/keras-team/keras/blob/master/keras/layers/cudnn_recurrent.py#L328

**Comment by rezaee** [comment]
@PhilipMay , Thanks!
But I mean deeper than this. I like to see implementation codes.

**Comment by PhilipMay** [comment]
Well, just follow the code...
