### ISSUE TITLE
keras.engine.topology _to_list

### ISSUE THREAD

**Issue by oscar195** [keras-team/keras#13213]
Hi, I'm a beginner in the deep learning field. I'm using python3.7 and I've already installed the new version of keras and tensorflow but I obtain the following error if I try to import the module _to_list from keras.engine.topology
ImportError: cannot import name '_to_list' from 'keras.engine.topology'

**Comment by maxwell-aladago** [comment]
@oscar195, I believe there isn't a function `_to_list` in the module `Keras.engine.topology`. In fact, that module is deprecated as stated [here](https://github.com/keras-team/keras/blob/c10d24959b0ad615a21e671b180a1b2466d77a2b/keras/engine/topology.py#L1). 

 Is it possible for you to give more information/context about what you want to do?
