### ISSUE TITLE
Hi i have created a Keras model using the Tensroflow as it's background and using elmo embeddings.The model weights are getting saved but entire model is not getting saved.

### ISSUE THREAD

**Issue by chowdary-git** [keras-team/keras#13229]
<em>Please make sure that this is a Bug or a Feature Request and provide all applicable information asked by the template.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.</em>  

**System information**  
- Have I written custom code (as opposed to using example directory):  
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  
- TensorFlow backend (yes / no):  
- TensorFlow version:  
- Keras version:  
- Python version:  
- CUDA/cuDNN version:  
- GPU model and memory:  

You can obtain the TensorFlow version with:  
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"  
You can obtain the Keras version with:  
python -c 'import keras as k; print(k.__version__)'  

**Describe the current behavior**  

**Describe the expected behavior**  

**Code to reproduce the issue**  
Provide a reproducible test case that is the bare minimum necessary to generate the problem.  

**Other info / logs**  
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by chowdary-git** [comment]
The model is as follows 

from keras.models import Model, Input
from keras.layers.merge import add
from keras.layers import LSTM, Embedding, Dense, TimeDistributed, Dropout, Bidirectional, Lambda
input_text = Input(shape=(max_len,), dtype=tf.string)
embedding = Lambda(ElmoEmbedding, output_shape=(max_len, 512))(input_text)
x = Bidirectional(LSTM(units=50, return_sequences=True,
                       recurrent_dropout=0.2, dropout=0.2))(embedding)
x_rnn = Bidirectional(LSTM(units=50, return_sequences=True,
                           recurrent_dropout=0.2, dropout=0.2))(x)
x = add([x, x_rnn])  # residual connection to the first biLSTM
out = TimeDistributed(Dense(n_tags, activation="softmax"))(x)
model_elmo = Model(input_text, out)

Error i'm getting is :
TypeErrorTraceback (most recent call last)
<ipython-input-53-191b7ff17a6b> in <module>()
----> 1 model_elmo.save('/content/drive/My Drive/Roudsqr/Custom_Model_August/custom_13Aug/Custom_NER_weights_model_19th_August_2019_Elmo_new.h5')
      2 #model_elmo.save_weights('./model_elmo_weights.h5')

6 frames
/usr/local/lib/python2.7/dist-packages/keras/engine/saving.pyc in get_json_type(obj)
     72             return obj.__name__
     73 
---> 74         raise TypeError('Not JSON Serializable: %s' % (obj,))
     75 
     76     from .. import __version__ as keras_version

TypeError: Not JSON Serializable: <dtype: 'string'>

**Comment by spencerhan** [comment]
I'm facing the same issue here.

**Comment by FLamefiREz** [comment]
I have the same problem. Has anyone solved it？

**Comment by spencerhan** [comment]
U can same the weights from your 1st run, then next time, create a new elmo
embedding, load the saved weights from your 1st run.

Cheers
