### ISSUE TITLE
babi_rnn and babi_memnn example failed in python3.7

### ISSUE THREAD

**Issue by NaNAGISaSA** [keras-team/keras#13248]
I have Python version 3.7.0. When I run babi_rnn and babi_memnn examples, this function is failed: 
```python
def tokenize(sent):
    '''Return the tokens of a sentence including punctuation.
    >>> tokenize('Bob dropped the apple. Where is the apple?')
    ['Bob', 'dropped', 'the', 'apple', '.', 'Where', 'is', 'the', 'apple', '?']
    '''
    return [x.strip() for x in re.split(r'(\W+)?', sent) if x.strip()]
```
In Python 3.7, 
```python
re.split(r'(\W+)?', 'Bob dropped the apple. Where is the apple?')
```
returns 
```python
['', None, 'B', None, 'o', None, 'b', ' ', '', None, 'd', None, 'r', None, 'o', None, 'p', None, 'p', None, 'e', None, 'd', ' ', '', None, 't', None, 'h', None, 'e', ' ', '', None, 'a', None, 'p', None, 'p', None, 'l', None, 'e', '. ', '', None, 'W', None, 'h', None, 'e', None, 'r', None, 'e', ' ', '', None, 'i', None, 's', ' ', '', None, 't', None, 'h', None, 'e', ' ', '', None, 'a', None, 'p', None, 'p', None, 'l', None, 'e', '?', '', None, '']
```
and will raise an AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by anthonyhsyu** [comment]
I ran into the same issue and just changed the return statement to the following:

`return [x.strip() for x in re.split(r'(\W+)?', sent) if x and x.strip()]`

**Comment by fbdo** [comment]
Hi @NaNAGISaSA and @anthonyhsyu, if you check keras website and documentation, it's written: "Keras is compatible with: Python 2.7-3.6.".

I guess that's the reason why you are facing those issues, the frameworks was not test, neither supports Python 3.7. Could you check if this is the reason? If yes, should we close this issue as it works as expected?

**Comment by NaNAGISaSA** [comment]
@fbdo Thank you, I will close the issue.
