### ISSUE TITLE
predictions different with same weight

### ISSUE THREAD

**Issue by yasohasakii** [keras-team/keras#13268]
<em>Please make sure that this is a Bug or a Feature Request and provide all applicable information asked by the template.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.</em>  

**System information**  
- Have I written custom code (as opposed to using example directory):  
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Linux CentOS 7.0
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  1.14
- Keras version:  2.2.0
- Python version:  2.7
- CUDA/cuDNN version:  8.0
- GPU model and memory:  single GPU with 16GB memory

You can obtain the TensorFlow version with:  
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"  
You can obtain the Keras version with:  
python -c 'import keras as k; print(k.__version__)'  

**Describe the current behavior**  

**Describe the expected behavior**  

**Code to reproduce the issue**  
Provide a reproducible test case that is the bare minimum necessary to generate the problem.  

**Other info / logs**  
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.  

Hi ,I found I run the same code and same weight with same images but got different predictions each time ,my code and images are on github [binary_categorical](https://github.com/yasohasakii/binary_categorical) and you can run the `ipynb` script on colab, and weight `.h5` file has been upload to [google dirver](https://drive.google.com/open?id=1sCIAgoQ7Og18iBmhwaOUmVSbRziAX5fo). Below codes are my result for twice times.  
`./PetImages/test/Cat/10000.jpg 0.070283316  
./PetImages/test/Cat/10001.jpg 0.04877737  `  
`./PetImages/test/Cat/10000.jpg 0.39205018  
./PetImages/test/Cat/10001.jpg 0.06655105  `

**Comment by gowthamkpr** [comment]
Can you please take a look at this [issue](https://github.com/keras-team/keras/issues/2743) and let me know if it helps. Thanks!
