### ISSUE TITLE
ATTRIBUTE ERROR WHILE  CALLING PREDICT FUNCTIO OF A LOADED MODEL

### ISSUE THREAD

**Issue by bhaveshgoyal27** [keras-team/keras#13264]
TENSORFLOW ==1.6.0
KERAS ==2.2.4
PYTHON ==3.6
**THIS IS MY CODE:**
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
from keras.models import load_model
import numpy as np
import keras
from keras import backend
from keras.models import Sequential
from keras.layers import Activation
from keras.layers.core import Dense, Flatten
from keras.optimizers import Adam
from keras.metrics import categorical_crossentropy
from keras.preprocessing.image import ImageDataGenerator
from keras.preprocessing.image import *
from keras.layers.normalization import BatchNormalization
from keras.layers.convolutional import *
from matplotlib import pyplot as plt
from sklearn.metrics import confusion_matrix
import itertools
import matplotlib.pyplot as plt
#%matplotlib inline
CNN=keras.applications.vgg16.VGG16()
model=Sequential()
for capa in CNN.layers:
    model.add(capa)
for layer in model.layers:
    layer.trainable=False
model.add(Dense(2,activation='softmax'))
model.load_weights("C:\\Users\\bhavs\\Desktop\\final_model_22_july_for_sure.h5")
test='C:\\Users\\bhavs\\Desktop\\qa.jpg'
model.predict(test)

**The error  I'm getting is this:**
File "C:\Users\bhavs\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training_utils.py", line 27, in standardize_single_array
    elif x.ndim == 1:
AttributeError: 'str' object has no attribute 'ndim'

**Comment by gowthamkpr** [comment]
@bhaveshgoyal27  As this issue is not related to bug/performance or feature request, Can you please post this issue in [stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow) as there is a bigger community to help and we can pitch in too. Thanks!
