### ISSUE TITLE
display error in all function in jupyter lab

### ISSUE THREAD

**Issue by nchos88** [keras-team/keras#13274]
![image](https://user-images.githubusercontent.com/36718545/64084731-20610480-cd69-11e9-95b1-b0280a89ce80.png)

windows10
python 3.7

Package               Version
--------------------- -----------
absl-py               0.7.1
appdirs               1.4.3
asciitable            0.8.0
astor                 0.7.1
attrs                 19.1.0
backcall              0.1.0
bayesian-optimization 1.0.1
black                 19.3b0
bleach                3.1.0
catboost              0.13.1
certifi               2019.6.16
chardet               3.0.4
Click                 7.0
cloudpickle           1.2.1
colorama              0.4.1
cycler                0.10.0
Cython                0.29.10
cytoolz               0.10.0
dask                  2.2.0
decorator             4.4.0
defusedxml            0.5.0
elm                   0.4.1
entrypoints           0.3
feather-format        0.4.0
future                0.17.1
gast                  0.2.2
gplearn               0.4.1
graphviz              0.11
grpcio                1.12.1
h5py                  2.9.0
hdbscan               0.8.22
idna                  2.8
imageio               2.5.0
imgaug                0.2.9
ipykernel             5.1.0
ipython               7.8.0
ipython-genutils      0.2.0
ipywidgets            7.4.2
jedi                  0.13.3
Jinja2                2.10
joblib                0.13.2
jsonschema            3.0.1
jupyter-client        5.2.4
jupyter-core          4.4.0
Keras                 2.1.6
Keras-Applications    1.0.7
Keras-Preprocessing   1.0.9
kiwisolver            1.0.1
lightgbm              2.2.3
llvmlite              0.24.0
Mako                  1.0.7
Markdown              2.6.11
MarkupSafe            1.1.1
matplotlib            3.0.3
missingno             0.4.1
mistune               0.8.4
mock                  2.0.0
msgpack               0.6.1
msgpack-numpy         0.4.4.2
nb-conda              2.2.1
nb-conda-kernels      2.2.1
nbconvert             5.4.1
nbformat              4.4.0
networkx              2.3
notebook              5.7.8
numba                 0.39.0
numexpr               2.6.9
numpy                 1.16.2
olefile               0.46
opencv-python         4.1.0.25
pandas                0.24.2
pandocfilters         1.4.2
parso                 0.3.4
patsy                 0.5.1
pbr                   5.1.3
pickleshare           0.7.5
Pillow                6.1.0
pip                   19.0.3
plotly                3.9.0
progressbar           2.5
prometheus-client     0.6.0
prompt-toolkit        2.0.9
protobuf              3.7.0
pyarrow               0.13.0
pydicom               1.2.2
pydot                 1.4.1
Pygments              2.3.1
pygpu                 0.7.6
PyOpenGL              3.1.0
pyparsing             2.3.1
PyPDF2                1.26.0
pyreadline            2.1
pyrsistent            0.14.11
python-dateutil       2.8.0
pytz                  2018.9
PyWavelets            1.0.3
pywinpty              0.5.5
PyYAML                5.1
pyzmq                 18.0.1
requests              2.21.0
retrying              1.3.3
scikit-image          0.15.0
scikit-learn          0.21.1
scipy                 1.2.1
seaborn               0.9.0
Send2Trash            1.5.0
setuptools            40.8.0
shap                  0.29.3
Shapely               1.6.4.post2
six                   1.12.0
statsmodels           0.9.0
tables                3.5.1
tabulate              0.8.3
tensorboard           1.13.1
tensorflow            1.13.1
tensorflow-estimator  1.13.0
termcolor             1.1.0
terminado             0.8.2
terminaltables        3.1.0
testpath              0.4.2
Theano                1.0.4
toml                  0.10.0
toolz                 0.10.0
tornado               6.0.2
tqdm                  4.31.1
traitlets             4.3.2
umap-learn            0.3.8
urllib3               1.24.1
wcwidth               0.1.7
webencodings          0.5.1
Werkzeug              0.15.2
wheel                 0.33.1
widgetsnbextension    3.4.2
wincertstore          0.2
xgboost               0.83.dev0
xlrd                  1.2.0

---

**Comment by gowthamkpr** [comment]
What backend are you using. Theano or tensorflow?

**Comment by nchos88** [comment]
> What backend are you using. Theano or tensorflow?

tensorflow 1.14
