### ISSUE TITLE
Multi-label picture

### ISSUE THREAD

**Issue by kingdsz** [keras-team/keras#13277]
‘’ImageDataGenerator.flow_from_dataframe‘’  Why doesn't it support multiple tags?

**Comment by Den4ikNestor** [comment]
@kingdsz, the main idea behind ​​this method **flow_from_dataframe** - the directory name is the image label.

Set the argument **directory** in this method, which contains subdirectories, and the names of all these subdirectories are labels for images (e.g., the subdirectories ['cats', 'dogs', 'rabbits', ...] containing specific images with these kinds of animals). In particular, you can set the **classes** argument with a list of subdirectory names.

If the images have multiple labels, try using the **flow_from_dataframe()** method.

**Comment by kingdsz** [comment]
I looked at the label of flow_from_dataframe() and found that the y tag is multi-column which does not support multiple tags, but multiple categories of one tag.

> @kingdsz, the main idea behind ​​this method **flow_from_dataframe** - the directory name is the image label.
> 
> Set the argument **directory** in this method, which contains subdirectories, and the names of all these subdirectories are labels for images (e.g., the subdirectories ['cats', 'dogs', 'rabbits', ...] containing specific images with these kinds of animals). In particular, you can set the **classes** argument with a list of subdirectory names.
> 
> If the images have multiple labels, try using the **flow_from_dataframe()** method.
