### ISSUE TITLE
[Feature Request] PyTorch Backend

### ISSUE THREAD

**Issue by amit2555** [keras-team/keras#13298]
**THIS IS A FEATURE REQUEST**

I just want to ensure no one else is working on adding PyTorch as backend for Keras. If they are, I would like to contribute. If not, I am happy to start working on it.

**Comment by SCP-173-cool** [comment]
What are the advantages ?

**Comment by amit2555** [comment]
I guess same reason Keras currently supports Tensorflow, Theano and CNTK. I have also seen Keras support for MxNet in the wild.

**Comment by gabrieldemarmiesse** [comment]
The development of multi-backend keras is currently stopped. We only fix bugs. There will be no new features, so also no new backend. See the keras meeting notes for more information: http://bit.ly/keras-meeting-notes
