### ISSUE TITLE
Data augmentation for 3D numpy images ?

### ISSUE THREAD

**Issue by maddy023** [keras-team/keras#13312]
I have my dataset in npz format,when i load using numpy.load every image is loaded as 3d numpy array.
i can feed into CNN for classification.

But any way to view the image,i tried to convert 2d array and view the image .But image displayed in small bar size plot.
and is is possible to data augmentation using keras ?

**Comment by jokandre** [comment]
What is the shape of your image? And how are you trying to display your image?
ImageDataGenerator could be used for augmentation or you can write your own data generator to do augmentation during runtime.

**Comment by maddy023** [comment]
shape: 3d 
(10, 30, 30, 1)
how to use ImageDataGenerator to load from 3d array variable?
