### ISSUE TITLE
is there any sample about how to use multi-gpu with multi-model with runing multiprocessing of one main process

### ISSUE THREAD

**Issue by Ai-is-light** [keras-team/keras#13310]
is there any sample about how to use multi-gpu with multi-mode with runing multiprocessing of one main process?
I would like to try using 3 models to do detection, classification and other classification, and I met some trouble with using them into multiprocessing. The code can work with one pool.

**Comment by 050214221** [comment]
Hello! I have the same problem with you and I don't know how to deal with. Have you solved it?
