### ISSUE TITLE
unable to load saved model when convolution is shared

### ISSUE THREAD

**Issue by ssge** [keras-team/keras#13324]
**System information**  
- Have I written custom code (as opposed to using example directory):  Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Windows 10
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  v1.12.0-rc2-3-ga6d8ffae09
- Keras version:  2.2.4
- Python version: 3.6 
- CUDA/cuDNN version: 9.0.176 and 7.4.2 
- GPU model and memory: 1080Ti  

**Describe the current behavior**  

A model that uses the same convolution in two places in a model throws the below exeption when load_model is attempted. Please note the model is created and trained properly before it is saved

`ValueError: Input 0 is incompatible with layer conv9x9: expected axis -1 of input shape to have value 16 but got shape (None, 62, 62, 4)`

**Describe the expected behavior**  

model loaded

**Code to reproduce the issue**  

this is how the model is created. take note that inp_1 and inp_2 are reusing the convolutions which is causing the problem. if the convolutions are not reused the issue does not happen.

<pre>
from keras.models import Model, load_model
from keras.layers import Dense, Softmax, Input, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D, BatchNormalization
from keras.layers import Concatenate

image_dims = (256, 256, 3)

def CreateConvModel():
    inp1 = Input(shape=image_dims, name="image1")
    inp2 = Input(shape=image_dims, name="image2")
    
    pooler2x2 = MaxPooling2D(pool_size=(2, 2), name='pooler2x2')
    
    color_conv = Conv2D(4, (1, 1), name='color_conv', activation='relu', kernel_initializer="glorot_normal")
    conv3x3 =    Conv2D(16, (3, 3), name='conv3x3', activation='relu', kernel_initializer="glorot_normal")
    conv9x9 =    Conv2D(8, (3, 3), name='conv9x9', activation='relu', kernel_initializer="glorot_normal")
    conv27x27 =  Conv2D(4, (3, 3), name='conv27x27', activation='relu', kernel_initializer="glorot_normal")
    
    def one_conv(inp):
        layer = color_conv(inp)
        
        layer = conv3x3(layer)
        layer = pooler2x2(layer)
        conv3x3_out = layer
        
        layer = conv9x9(layer)
        layer = pooler2x2(layer)
        conv9x9_out = layer
        
        layer = conv27x27(layer)
        layer = pooler2x2(layer)
        conv27x27_out = layer
        
        conv = Concatenate()([Flatten()(conv3x3_out), Flatten()(conv9x9_out), Flatten()(conv27x27_out)])
        
        return conv
    
    x = Concatenate()([one_conv(inp1), one_conv(inp2)])
    
    for i in range(6):
        x = Dense(64, activation='relu')(x)
    
    output = Dense(2, activation='softmax')(x)
    
    model = Model(inputs=[inp1, inp2], outputs=[output])
    
    return model

if __name__== "__main__":
    model = CreateConvModel()
    model_file = "model.h5"
    
    model.save(model_file)
    
    m2 = load_model(model_file)
</pre>

**Other info / logs**  

The above seems to be working with only two convolutions are stacked. Also if additional layers are added (say BatchNormalization) after the first 1x1 convolution then the exception changes (as if the index is off by one more/less 

<pre>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python36\lib\site-packages\keras\engine\saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "C:\Program Files\Python36\lib\site-packages\keras\engine\saving.py", line 225, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "C:\Program Files\Python36\lib\site-packages\keras\engine\saving.py", line 458, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "C:\Program Files\Python36\lib\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "C:\Program Files\Python36\lib\site-packages\keras\utils\generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "C:\Program Files\Python36\lib\site-packages\keras\engine\network.py", line 1032, in from_config
    process_node(layer, node_data)
  File "C:\Program Files\Python36\lib\site-packages\keras\engine\network.py", line 991, in process_node
    layer(unpack_singleton(input_tensors), **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\keras\engine\base_layer.py", line 440, in __call__
    self.assert_input_compatibility(inputs)
  File "C:\Program Files\Python36\lib\site-packages\keras\engine\base_layer.py", line 352, in assert_input_compatibility
    ' but got shape ' + str(x_shape))
ValueError: Input 0 is incompatible with layer conv9x9: expected axis -1 of input shape to have value 16 but got shape (None, 62, 62, 4)
</pre>

**Comment by hensleyl4** [comment]
Can you share a short code snippet reproducing the error, that can be immediately executed? The code you provided has several undefined variables, such as the number of filters (model_color_convs, etc.) and color_norm function. Also, you are not loading the model in the example.

After writing code based on your description, loading a model that reuses a convolution, I was not able to reproduce that error.

**Comment by ssge** [comment]
thanks for looking at this. code is updated in the original description

**Comment by ssge** [comment]
Why type:support? This is clearly a bug. Works with 2 conv layers, does not work with 3 layers.

**Comment by ssge** [comment]
After a bit further investigation it appears that the shared pooling layer is to blame. When the pooling layer is not shared the model is loaded properly. Still though if there is an issue with sharing pooling layers the original model should not be able to be compiled and saved.
