### ISSUE TITLE
Keras: initiliaze bidirectional LSTM layer from config

### ISSUE THREAD

**Issue by enthu-sh** [keras-team/keras#13331]
I have a pretrained model with bidirectional LSTM layer for which I want to set return_sequences=True. I am trying as:

config=model.layers[-1].get_config()
config['layers']['config']['return_sequences']=True

This changes the value of return_sequences in dictionary config. But I do not know how to set this configuration in layer. Something like, is not working.

model.layers[-1]=LSTM.from_config(config)

It gives init takes at least two arguments.

Layer[-1] of model is actually a bidirectional wrapped LSTM.

**Comment by fchollet** [comment]
You should instantiate a new LSTM layer with your new options, and then load your old weights into it with `new_layer.set_weights(old_layer.get_weights())`. Note that all layer arguments should stay the same except `return_sequences`.
