### ISSUE TITLE
Unable to extract layer output after pushing layers back to model

### ISSUE THREAD

**Issue by enthu-sh** [keras-team/keras#13343]
I have a classification network with last two layers as Dense and activation respectively. I popped the layers from the model as :

    activationlayer=classifier.layers.pop()
    denselayer=classifier.layers.pop()

Then I pushed the layers back into the model:

    outt1=denselayer(classifier.layers[-1].output)
    outt=activationlayer(outt1)
    classifier=Model(classifier.input,outt)

Now while indexing the output of dense layer I get error:

    classifier.layers[-2].output

    Error: Layer out2 has multiple inbound nodes, hence the notion of "layer output" is ill-defined.

**Comment by anerirana** [comment]
If you are using keras v2.x then `classifier.layers.pop()` is not actually removing any layer from your model. It will just return you the element popped from the end of layers array. When you added 2 more layers, you just added more node paths to existing ones. Therefore the error.

Use `classifier.pop()` to remove last layer instead.
