### ISSUE TITLE
How can I get the number of intermediate layer before training? 

### ISSUE THREAD

**Issue by Bin-913** [keras-team/keras#13358]
For example: 
It's easy to get the number of  a certain layer by applying K.function when we have obtained the trained model:
"layer_1 = K.function([base_model.layers[0].input], [base_model.layers[243].output])"
what if I only have the model.py file, and can't train the network, how can I get the number of a certain layer?

**Comment by xiankgx** [comment]
Load your model, then

```
for i, layer in enumerate(model.layers):
    print i, layer
```

i is what you want.
