### ISSUE TITLE
Commercial usage of keras pretrained models

### ISSUE THREAD

**Issue by aseembits93** [keras-team/keras#13362]
Hi Keras Team,
At https://keras.io/applications/ , there are some model weights (Xception, ResNet) released under the MIT License. Although these models were trained on Imagenet, which can only be used for research and non-commercial usage. Does it mean we can use these model weights in commercial applications? does it conflict with Imagenet data's non-commercial license? since the model weight is a derivative of the imagenet data. Hope this is the right place to ask.
Best Regards,

**Comment by fchollet** [comment]
In the general case, pre-trained weight checkpoints have their own license which isn't inherited from the license of the dataset they were trained on. This is not legal advice, and you should consult with a lawyer.

**Comment by aseembits93** [comment]
@fchollet I'm highly grateful to you for your swift reply on this issue!
