### ISSUE TITLE
Error incompatible shapes when using batch size >1

### ISSUE THREAD

**Issue by NBasty** [keras-team/keras#13369]
- Have I written custom code:  yes and it works fine for batch size 1
- OS Platform and Distribution:  Ubuntu 18.04
- TensorFlow backend:  yes
- TensorFlow version:  1.13.1 (also tried on others 1.14.0)
- Keras version:  tried all versions from 2.2.1 to 2.3, 
- Python version:  3.6.8
- CUDA/cuDNN version: 10.0
- GPU model and memory:  (tried on) titan V and GeForce 12GB

When I try to train my model with batch size greater than 1 it always gives me an error such as this one below, where he incompatible shape on the left is the product of the batch size and the shape on the right. There is a similar question https://github.com/keras-team/keras/issues/11749 but the proposed fix of using another version does not work for me. I have tried increasing the batch size to 2 with all keras versions from 2.2.1 to 2.3 and that does not solve the problem for me. Is anybody else still experiencing this issue? Could anybody help?

> 
> InvalidArgumentError                      Traceback (most recent call last)
> <ipython-input-10-a8f8d9519e94> in <module>
>      12 
>      13 history = model.fit(x_train, y_train, batch_size = 2, epochs = 200,
> ---> 14         validation_data = (x_val, y_val), callbacks = callbacks_list)
> 
> ...
> 
> InvalidArgumentError: Incompatible shapes: [7077888] vs. [3538944]
> 	 [[{{node training/Adam/gradients/loss_1/conv3d_54_loss/mul_grad/BroadcastGradientArgs}}]]
> 	 [[{{node loss_1/mul}}]]

It works quite well as it is right now with batch size 1 but I want to increase the batch size for more stability in my training. 

Thanks.

**Comment by naiveHobo** [comment]
Could you post the output shapes of your model and the shape of the tensor containing the labels? I faced a similar issue recently.

The output shape for my model is **[batch_size, seq_len, num_classes]** where each row in each batch is a probability distribution over **num_classes**.

The shape for the labels in my dataset object was **[batch_size, seq_len]**. This threw an incompatible shape error. After searching for a bit, I found out that my metric fucntion (sparse_categorical_accuracy), tries to squeeze the last dimension of the labels tensor and throws an error is the last dimension is not 1.

Changing my labels tensor to the shape **[batch_size, seq_len, 1]** fixed the problem.

**Comment by NBasty** [comment]
Thank you for your reply. Yes, actually I think my error may also be in the loss function definition thank you for pointing that out. 

def dice_coef(y_true, y_pred):
    y_true_f = K.flatten(y_true)
    y_pred_f = K.flatten(y_pred)
    intersection = K.sum(y_true_f * y_pred_f)
    return (2.0 * intersection + smooth) / (K.sum(y_true_f) + K.sum(y_pred_f) + smooth)

def dice_loss(y_true,y_pred)
    return 1-dice_coef(y_true,y_pred)

I'm working with grayscale (one colour channel) 3D images, so the shapes are = [NUM_SAMP, im_dim1, im_dim2, im_dim3, 1]. Both the input data and the labels have the same shape. How can I see the shape of the tensor containing the labels? I wasn't aware it would be different, or I am not familiar with your terminology. Here's the output of the first and last layers shown in the model summary.

Layer (type)                               Output Shape                  Param #         Connected to                                
=====================================================================================================================================
input_2 (InputLayer)                       (None, 288, 256, 48, 1)       0                                   
...
_____________________
conv3d_54 (Conv3D)                         (None, 288, 256, 48, 1)       2               p_re_lu_60[0][0]                            
=====================================================================================================================================
