### ISSUE TITLE
Unable to change Nesterov value using backend

### ISSUE THREAD

**Issue by NMVRodrigues** [keras-team/keras#13363]
**System information**  
- Have I written custom code (as opposed to using example directory):  
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Ubunto
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  2.0.0-rc0
- Keras version:  2.2.4
- Python version:  3.6.8
- CUDA/cuDNN version:  None
- GPU model and memory:  None

When trying to change the model optimizer parameters, nesterov in particular, using backend, it throws an error regarding the bool assignment:

```python
tf.keras.backend.set_value(model.optimizer.nesterov, bool(getrandbits(1)))

File "/home/nuno/miniconda3/envs/venv/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 3199, in set_value
    value = np.asarray(value, dtype=dtype(x))
  File "/home/nuno/miniconda3/envs/venv/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 1243, in dtype
    return x.dtype.base_dtype.name
AttributeError: 'bool' object has no attribute 'dtype'
```

In this example I'm using a random bool value, but it is also possible to reproduce this error replacing the `bool(getrandbits(1))` by a `True` or a `False`.

**Comment by HuzuniV2** [comment]
EDIT:

I am aware that in the documentation for `set_value` it says the following:
```python
Arguments:

x: Tensor to set to a new value.

value: Value to set the tensor to, as a Numpy array (of the same shape).
```

But it is possible to use `set_value` to assing numerical values to other optimizer parameters, like it is described in[ this post](https://stackoverflow.com/questions/47523841/using-keras-to-load-model-and-assign-new-values-to-its-parameters), thus it should also be possible to use it to change the boolean value of the nesterov parameter.
