### ISSUE TITLE
How to load images and mask for unet ,with keras imagedatagenerator

### ISSUE THREAD

**Issue by maddy023** [keras-team/keras#13365]
I need to load images and mask for unet model,i dont wanna use cv2 or any libaraires to load images.I wanna use easy way to load up these images. My dataset strucuture

data/train
    1.png
    2.png

data/mask
    1_mask.png
NOT TO LOAD FROM VARIABLE,TO LOAD FROM DIR.
while googling i found keras docs for images and mask code.but it need images and mask stored in array.Or any other method to load up images and mask.

**Comment by WuChengziOrange** [comment]
Have you solved this problem? I have the same problem as you.
