### ISSUE TITLE
 'Adam' object has no attribute 'learning_rate'

### ISSUE THREAD

**Issue by fayeshine** [keras-team/keras#13423]
keras 2.3.1

```
Traceback (most recent call last):
 File "<ipython-input-10-d6b59bd49623>", line 174, in objective
 File "/home/wenjian/anaconda3/lib/python3.7/site-packages/keras/engine/training.py", line 1213, in fit
   self._make_train_function()
 File "/home/wenjian/anaconda3/lib/python3.7/site-packages/keras/engine/training.py", line 316, in _make_train_function
   loss=self.total_loss)
 File "/home/wenjian/anaconda3/lib/python3.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
   return func(*args, **kwargs)
 File "/home/wenjian/anaconda3/lib/python3.7/site-packages/keras/optimizers.py", line 507, in get_updates
   lr = self.learning_rate
AttributeError: 'Adam' object has no attribute 'learning_rate'
```

**Comment by Arktius** [comment]
I think the parameter is just 'lr'.

**Comment by fayeshine** [comment]
> I think the parameter is just 'lr'.

the 'learning_rate' bug is an internal problem. I didn't set 'learning_rate' at all.

**Comment by Arktius** [comment]
Could you please provide your code? The import and the code line where you'd like to use Adam.

I use it that way:

from keras.optimizers import Adam

Adam?

Init signature:
Adam(
    **lr=0.001,**
    beta_1=0.9,
    beta_2=0.999,
    epsilon=None,
    decay=0.0,
    amsgrad=False,
    **kwargs,
)
Docstring:     
Adam optimizer.

Default parameters follow those provided in the original paper.

# Arguments
    **lr: float >= 0. Learning rate.**
    beta_1: float, 0 < beta < 1. Generally close to 1.
    beta_2: float, 0 < beta < 1. Generally close to 1.
    epsilon: float >= 0. Fuzz factor. If `None`, defaults to `K.epsilon()`.
    decay: float >= 0. Learning rate decay over each update.
    amsgrad: boolean. Whether to apply the AMSGrad variant of this
        algorithm from the paper "On the Convergence of Adam and
        Beyond".

# References
    - [Adam - A Method for Stochastic Optimization]
      (https://arxiv.org/abs/1412.6980v8)
    - [On the Convergence of Adam and Beyond]
      (https://openreview.net/forum?id=ryQu7f-RZ)
File:           c:\users\admin\anaconda3\envs\ma\lib\site-packages\keras\optimizers.py
Type:           type
Subclasses:

**Comment by fayeshine** [comment]
from keras.optimizers import Adam
opt = Adam(epsilon=1e-8)
do i need to set lr during initialization?

**Comment by Arktius** [comment]
> from keras.optimizers import Adam
> opt = Adam(epsilon=1e-8)
> do i need to set lr during initialization?

No, It'll then be set to 0.001 as printed above. If you don't specify a parameter, it takes the default value.

**Comment by Walter-Romaric** [comment]
I had the same error message when importing Adam with: **from tensorflow.keras.optimizers import Adam** simply. This is more likely kind of a version issue. I corrected it by importing Adam as following: 
----> from tensorflow.keras.optimizers.**legacy** import Adam.
Specifying that I wanted the legacy Adam solved my problem.
