### ISSUE TITLE
InvalidArgumentError:  Incompatible shapes: [32] vs. [24]

### ISSUE THREAD

**Issue by shilpasonawani** [keras-team/keras#13425]
Pls help me for the following problem I hav created model

# reshape input to be 4D [samples, timesteps, features]
train_X = train_X.reshape((train_X.shape[0], 1,n_features, n_hours))
test_X = test_X.reshape((test_X.shape[0], 1,  n_features, n_hours))
print(train_X.shape, train_y.shape, test_X.shape, test_y.shape)
(17520, 1, 18, 1) (17520,) (8784, 1, 18, 1) (8784,)
# define model
from keras.layers import Dense,LSTM,TimeDistributed,Dropout,Conv1D,Flatten,concatenate,MaxPooling1D,GRU
keras.layers
model = Sequential()
model.add(TimeDistributed(Conv1D(filters=64, kernel_size=2, activation='relu'), batch_input_shape=(24,1, 18, 1)))
model.add(TimeDistributed(MaxPooling1D(pool_size=2)))
model.add(TimeDistributed(Flatten()))
model.add(GRU(50, return_sequences=True))
model.add(GRU(50))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
model.summary()

# fit network
gru_history = model.fit(train_X, train_y, epochs=50, validation_data=(test_X, test_y), shuffle=False)

when I fit the model I get following error
InvalidArgumentError:  Incompatible shapes: [32] vs. [24]
	 [[node gradients_1/loss_1/dense_2_loss/mean_squared_error/weighted_loss/mul_grad/Mul_1 (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1751) ]] [Op:__inference_keras_scratch_graph_9349]

Function call stack:
keras_scratch_graph

**Comment by xiankgx** [comment]
`model.add(TimeDistributed(Conv1D(filters=64, kernel_size=2, activation='relu'), batch_input_shape=(24,1, 18, 1)))`

Change the input shape.
