### ISSUE TITLE
Unable to load .h5 file using tf.model_load

### ISSUE THREAD

**Issue by acd556** [keras-team/keras#13449]
This is my first time asking question in GitHub, if there is anything wrong, please tell me, thank you.

-------------------------------------------------------------------------------------------------------------
Following is my question:

I've already trained a model on windows 10, and I want to use it to predict some data on linux.

versions on windows:
python 3.7.3
tensorflow 1.13.1
keras  2.2.4

versions on linux:
python 2.7.13
tensorflow 1.1.0

python version of IDE on linux: 3.5.3

I use keras to train my model and use `model.save()` to save my model as `model.h5`. I can't install keras on my linux, so I decide to use `tensorflow.contrib.keras.models.load_model()` to load it. 

The result of `tensorflow.contrib.keras.models.load_model()`  to load `model.h5` is :
 
    IOError: Unable to open file

What can I do to resolve this problem? Should I use other functions or change some version of them or anything can deal with it?

**Comment by xiankgx** [comment]
Try reloading the model using tf.keras then do a save weights. Then instantiate the new model in keras and then load weights. Should work.
