### ISSUE TITLE
Time Series Forecasting with LSTM and different/mixed frequencies

### ISSUE THREAD

**Issue by janwendt** [keras-team/keras#13444]
I could not find anything in the docs about how to handle different frequencies of time series. I have a Dataset A with monthly data that i want to use to predict the values from Dataset B that contains quarterly based data. So the target value e.g. quarter 1 is based on the values from month 1-3.

Dataset A (Features):

| Month  | Value1 | Value2 | Value3 |
| ------------- | ------------- | ------------- | ------------- |
| 1  | 91  | 72 | 23 |
| 2  | 93  | 68 | 33 |
| 3  | 92  | 57 | 27 |
| 4  | 91  | 72 | 23 |
| 5  | 93  | 68 | 33 |
| 6  | 92  | 57 | 27 |

Dataset B (Target):

| Quarter   | Target_Value |
| ------------- | ------------- |
| 1  | 51  |
| 2  | 57  |

**Comment by maxhardt** [comment]
Could you elaborate how you would not be able to use a sliding window approach here? ([Formal introduction here](http://web.engr.oregonstate.edu/~tgd/publications/mlsd-ssspr.pdf)). 

As from my understanding of your problem the only precaution needed here is in the exact way you sample from your time series data and how you frame the supervised learning problem, which is not a Keras issue.

**Comment by AZFARHAD24511** [comment]
my same question. did you find the solution? please let me know if you get the solution.
