### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'get_default_session'

### ISSUE THREAD

**Issue by nbro** [keras-team/keras#13442]
**System information**  
- Have I written custom code (as opposed to using example directory):  no
- OS Platform and Distribution:  8.04.3 LTS (Bionic Beaver)
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  2.0.0 (gpu)
- Keras version:  2.2.5
- Python version:  3.6.8
- CUDA/cuDNN version:  10.1
- GPU model and memory:  Tesla K80 (memory limit 11330115994).

**Describe the current behavior**  

I get the following error

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-17-3d00d838479b> in <module>()
      1 from keras import backend as K
----> 2 K.tensorflow_backend._get_available_gpus()

1 frames
/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py in get_session()
    188     global _SESSION
    189 
--> 190     default_session = tf.get_default_session()
    191 
    192     if default_session is not None:

AttributeError: module 'tensorflow' has no attribute 'get_default_session'
```
when executing the following code

```
from keras import backend as K
K.tensorflow_backend._get_available_gpus()
```

or 

```
from tensorflow.keras import backend
backend._get_available_gpus()
```

AFAIK, sessions should still be supported in TF 2.0. Even though `_get_available_gpus()` is considered a private method, given the initial `_`, it does fail with TF 2.0, so I think this is a bug.

**Describe the expected behavior**  

No error and I get the available GPUs. In general, I would like to make sure Keras uses GPU (with TF 2.0). Any reliable method to achieve this?

**Code to reproduce the issue**  

See above.

**Other info / logs**  

See above.

**Comment by tensorflowbutler** [comment]
t

**Comment by burakyldrm** [comment]
I think the following code will solve the problem
`pip install --force-reinstall tensorflow==1.15`

**Comment by nbro** [comment]
@burakyldrm Of course, I don't want to use any other TensorFlow version other than 2.0.0, as I said above.

**Comment by Rogan-Clark** [comment]
I was having the same problem, but if you modify "tf.get_default_session" to "tf.compat.v1.get_default_session", it should work, at least until the next TensorFlow update.

**Comment by nbro** [comment]
@Rogan-Clark Have you read my post above? The only lines of code I had were

```
from keras import backend as K
K.tensorflow_backend._get_available_gpus()
```

**Comment by Rogan-Clark** [comment]
You have to go into the /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py file and edit it in that, I think.

**Comment by nbro** [comment]
@Rogan-Clark Well, I would like to use TensorFlow and Keras out of the box. I don't want to mess with their implementation.

**Comment by pargass31** [comment]
Hi nbro, did you solve your issue? (I have exactly the same one)
thanks

**Comment by zbli** [comment]
I also run into the same problem. It would be appreciated if the solving method could be informed.
Thanks

**Comment by schustan235** [comment]
Same issue here, have also tried to go into the source files with no luck. But I can't find "tf_keras_backend" defined anywhere.

`"""Get a list of available gpu devices (formatted as strings).

    # Returns
        A list of available GPU devices.
    """
    global _LOCAL_DEVICES
    if _LOCAL_DEVICES is None:
        if _is_tf_1():
            **devices = get_session().list_devices()**
            #Source of error^^^
            _LOCAL_DEVICES = [x.name for x in devices]
        else:
            _LOCAL_DEVICES = tf.config.experimental_list_devices()
    return [x for x in _LOCAL_DEVICES if 'device:gpu' in x.lower()]
`
> You have to go into the /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py file and edit it in that, I think.
^^See above @Rogan-Clark

**Comment by advset** [comment]
I have the same issue while running

`# freeze graph
frozen_graph = freeze_session(K.get_session(),
                              output_names=[out.op.name for out in model.outputs])`

I imported the correct library I guess and load an h5 model I previously made using Keras and TF2

`from keras import backend as K

from tensorflow.keras.models import load_model
 
# load model
model = load_model('C:/Python36/face-mask-detector/mask_detector.model')`

haha T_T

**Comment by rizqira11** [comment]
path_model='/content/drive/MyDrive/Colab Notebooks/model_filter (1).h5' # save model at this location after each epoch
K.tensorflow_backend.clear_session() # destroys the current graph and builds a new one
model=my_model() # create the model
K.set_value(model.optimizer.lr,0.5) # set the learning rate
# fit the model
h=model.fit(x=X_train,     
            y=y_train, 
            batch_size=64, 
            epochs=20, 
            verbose=1, 
            validation_data=(X_test,y_test),
            shuffle=True,
            callbacks=[
                ModelCheckpoint(filepath=path_model),
            ]
            )


module 'tensorflow' has no attribute 'tensorflow_backend'

**Comment by AnjalyL** [comment]
AttributeError: module 'tensorflow' has no attribute 'get_default_session'
I am getting this error.
Can anyone help?
