### ISSUE TITLE
model.test_on_batch returns total loss instead of average - Keras 2.2.4

### ISSUE THREAD

**Issue by omrygin** [keras-team/keras#13458]
Is it a known issue (is it even an issue?) that model.test_on_batch returns the sum of losses of each entry in the batch instead of the average? I looked over the changelog and saw no reference to that.
model.train_on_batch does in fact returns the average, but in the docs their return value is documented the same.

**Comment by kartik4949** [comment]
Returns

Scalar test loss (if the model has a single output and no metrics) or list of scalars (if the model has multiple outputs and/or metrics). The attribute model.metrics_names will give you the display labels for the scalar outputs.


This is official Return for test_on_batch so, as you can see Scalar test loss will be returned for one single output.

and im pretty sure keras returns average for batch.
