### ISSUE TITLE
there is something wrong with the custom layer

### ISSUE THREAD

**Issue by JarmoHu** [keras-team/keras#13454]
<em>Please make sure that this is a Bug or a Feature Request and provide all applicable information asked by the template.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.</em>  

**System information**  
- Have I written custom code (as opposed to using example directory):  
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  win10 x64 1903
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  <module 'tensorflow_core._api.v2.version' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\tensorflow_core\\_api\\v2\\version\\__init__.py'>
- Keras version:  2.2.4-tf
- Python version:  Python 3.7.4
- CUDA/cuDNN version:  latest(2019/10/11)
- GPU model and memory:  GeForce GTX 1050 Ti 4G

**Describe the current behavior**  
When I changed parameter 'multiple' of the custom layer in a model, nothing  changed

**Describe the expected behavior**  
if multiple = 2**50, they should print [0,0,1,1]
if multiple = 2, they should print [0.xx , 0.xx, 0.xx , 0.xx]

**Code to reproduce the issue**  
'''python

    import scipy.io as sio
    import numpy as np
    from sklearn.model_selection import train_test_split
    import math
    import tensorflow as tf

    class Gradient_sigmoid(tf.keras.layers.Layer):
        def __init__(self, output_dim, multiple=2, **kwargs):
            self.output_dim = output_dim
            self.multiple = multiple
            super(Gradient_sigmoid, self).__init__(**kwargs)

        def build(self, input_shape):
            # Create a trainable weight variable for this layer.
            super(Gradient_sigmoid,
                self).build(input_shape)  # Be sure to call this at the end

        def call(self, x):
            return 1.0 / (1.0 + math.e**(-1 * self.multiple * x))

        def compute_output_shape(self, input_shape):
            return (input_shape[0], self.output_dim)

        def set_multiple(self, multiple):
            self.multiple = multiple
            return

        def get_multiple(self):
            return self.multiple

    if __name__ == "__main__":
        model = tf.keras.models.Sequential()
        layer_1 = Gradient_sigmoid(output_dim=4, input_shape=(4, ), multiple=2**50)
        model.add(layer_1)

        x_test = np.array([[-2, -1, 1, 2]])
        print(model.predict(x_test))
        print(model.layers[0].get_multiple())

        model.layers[0].multiple = 2
        print(model.predict(x_test))
        print(model.layers[0].get_multiple())

        model.layers[0].set_multiple(2)
        print(model.predict(x_test))
        print(model.layers[0].get_multiple())

'''

**Other info / logs**  
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by sixChar** [comment]
The problem (based on my loose understanding) is that the call function is not used when model.predict() is called, instead call just defines a set of tensorflow operations to apply to the input tensor. The call function as you have it uses the value of self.multiple to define a tensorflow op, not the variable itself. 

To use self.multiple this way you need to define it as a tensorflow variable by replacing:
`self.multiple = multiple`
with
`self.multiple = tf.keras.backend.variable(multiple)`
in the constructor, and defining the set_multiple function as:
```
def set_multiple(self, multiple):
    tf.keras.backend.set_value(self.multiple,multiple)
```
