### ISSUE TITLE
Training on multiple GPU inference on single GPU/CPU

### ISSUE THREAD

**Issue by flydsc** [keras-team/keras#13474]
Hi,

I was training my model by using  multi_gpu_model to wrap my model like this:

```python
combine_model = multi_gpu_model(combine_model, gpus=Config.gpu_num)
```
Then is that possible to train with multiple gpu, and inference with single GPU or CPU?

For now, the model would raise error if the devices were not the same. 

Anything we can do about this?

Any help thoughts or comments would be appreaciated. 

Best,

**Comment by PDXKor** [comment]
Any word on this? Having the same issue.
