### ISSUE TITLE
[Bug Request] InvalidArgumentError:  Incompatible shapes When I try to use accuracy as metric.

### ISSUE THREAD

**Issue by jmpr0** [keras-team/keras#13484]
This code: https://github.com/keras-team/keras-contrib/blob/master/examples/improved_wgan.py

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Colab Jupyter Notebook
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  2.0.0
- Keras version:  2.3.1
- Python version:  3

Hi guys.
When I try to train_on_batch my model, keras raise subsequent exception:

```
InvalidArgumentError:  Incompatible shapes: [2500,1] vs. [50,1]
	 [[node metrics_7/model_16_accuracy_2/Equal (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1751) ]] [Op:__inference_keras_scratch_graph_6318]

Function call stack:
keras_scratch_graph
```

The error derive from the use of 'accuracy' metric, and goes away when I remove it.
But, how I can solve it?

Thanks.

**Comment by Terkea** [comment]
I got just the same issue,
Windows 10, Tf 2, Python 3
```error
InvalidArgumentError:  Incompatible shapes: [32] vs. [32,111,111]
	 [[node metrics/accuracy/Equal (defined at <ipython-input-40-01a7b3e6c0fd>:12) ]] [Op:__inference_distributed_function_3107]

Function call stack:
distributed_function```

**Comment by Manish-git-135** [comment]
I got same error when i am using CNN. (Windows 10 Tf 2.1, python 3) because i didn't use Flatten() layer after CNN layers()
