### ISSUE TITLE
ValueError: x (images tensor) and y (labels) should have the same length.

### ISSUE THREAD

**Issue by Sejudyblues** [keras-team/keras#13483]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [ ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [ ] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by Sejudyblues** [comment]
hey,guys i have the same trouble. i don't know how to deal with it. my code is from https://github.com/keras-team/keras/blob/master/examples/cifar10_cnn.py  ValueError: x (images tensor) and y (labels) should have the same length. Found: x.shape = (10000, 32, 32, 3), y.shape = (50000, 10)

**Comment by William9Baker** [comment]
I also meet this error.

**Comment by yeasin50** [comment]
In my case I passed wrong parameters, I passed textX instead of trainX
make sure 
`# train the network
H = model.fit(x=aug.flow(trainX, trainY, batch_size=BS),
	validation_data=(testX, testY), steps_per_epoch=len(trainX) // BS,
	epochs=EPOCHS)`

**Comment by yeasin50** [comment]
In my case I passed wrong parameters, I passed textX instead of trainX
make sure

# train the network 
`
H = model.fit(x=aug.flow(trainX, trainY, batch_size=BS), validation_data=(testX, testY), steps_per_epoch=len(trainX) // BS, epochs=EPOCHS)`
