### ISSUE TITLE
tf.keras.layers.Concatenate(axis=axis)(conc_layer) not working

### ISSUE THREAD

**Issue by TheKeyOfficial** [keras-team/keras#13492]
**System information**  
- Have I written custom code (as opposed to using example directory):  no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Windows 10
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  2.0.0
- Keras version:  2.2.4-tf
- Python version: 3.6
- CUDA/cuDNN version:  10.1
- GPU model and memory:  Titan GTX 12Gb

**Describe the current behavior** 
//layer_type is in this case BatchNorm+ELU+Conv2D
 def dens_block(layer_num, layer_type,**kwargs):
	conc_layer = []
	def block(x):
		conc_layer.append(x)
		for i in range(layer_num):
		     x = layer_type(32, 2, strides=(1, 1), padding='same', **kwargs)(x)
		     conc_layer.append(x)
                     x = tf.keras.layers.Concatenate(axis=axis)(**list**(conc_layer))
		return x
	return block

**Describe the expected behavior**  
without the **list** in  tf.keras.layers.Concatenate the code not work

**Code to reproduce the issue**  
import tensorflow as tf
import netron

def bn_elu_conv(filters, kernel_size, strides=(1, 1), padding='valid', **kwargs):
	def layer(input_tensor):
		with tf.keras.backend.name_scope('bn_elu_conv'):
			x = tf.keras.layers.BatchNormalization()(input_tensor)
			x = tf.keras.layers.ELU()(x)
			x = tf.keras.layers.Conv2D(filters, kernel_size, strides=strides, padding=padding, **kwargs)(x)
		return x

	return layer

def conv_bn_elu(filters, kernel_size, strides=(1, 1), padding='valid', **kwargs):
	def layer(input_tensor):
		with tf.keras.backend.name_scope('conv_bn_elu'):
			x = tf.keras.layers.Conv2D(filters, kernel_size, strides=strides, padding=padding, **kwargs)(input_tensor)
			x = tf.keras.layers.BatchNormalization()(x)
			x = tf.keras.layers.ELU()(x)
		return x

	return layer

def dens_block(layer_num, filters, kernels_sizes, strides=(1, 1), padding='same', layer_type='bn_elu_conv', axis=-1, **kwargs):
	layer_type = _get_layerTyp(layer_type)
	filters = _check_list(filters, layer_num)
	kernels_sizes = _check_list(kernels_sizes, layer_num)
	conc_layer = []

	def block(x):
		conc_layer.append(x)
		for i in range(layer_num):
			x = layer_type(filters[i], kernels_sizes[i], strides=strides, padding=padding, **kwargs)(x)
			conc_layer.append(x)
			x = tf.keras.layers.Concatenate(axis=axis)(conc_layer)
			# x = tf.keras.layers.Concatenate(axis=axis)(list(conc_layer) # is working

		return x

	return block

def res_block(layer_num, filters, kernels_sizes, strides=(1, 1), padding='same', layer_type='bn_elu_conv', conv_block=False, **kwargs):
	layer_type = _get_layerTyp(layer_type)
	filters = _check_list(filters, layer_num)
	kernels_sizes = _check_list(kernels_sizes, layer_num)

	def block(x):
		input_tensor = x
		for i in range(layer_num):
			x = layer_type(filters[i], kernels_sizes[i], strides=strides, padding=padding, **kwargs)(x)
		if conv_block:
			input_tensor = layer_type(filters[-1], kernels_sizes[-1], strides=strides, padding=padding, )(input_tensor)
		x = tf.keras.layers.Add()([x, input_tensor])
		return x

	return block

def _get_layerTyp(layer_typ):
	if layer_typ is 'bn_elu_conv':
		return bn_elu_conv
	if layer_typ is 'conv_bn_elu':
		return conv_bn_elu
	else:
		raise ValueError('layer_typ have to be \'bn_elu_conv\' or \'conv_bn_elu\'')

def _check_list(x, list_len):
	if isinstance(x, list):
		if len(x) is list_len:
			return x
		else:
			raise TypeError('x have to be the same length as list_len')
	else:
		return _to_list(x, list_len)

def _to_list(x, list_len):
	new_x = []
	for _ in range(list_len):
		new_x.append(x)
	return new_x

if __name__ == '__main__':
	input_tensor = tf.keras.layers.Input(shape=(256, 256, 3))
	x = bn_elu_conv(filters=3, kernel_size=2)(input_tensor)
	for _ in range(4):
		x = dens_block(layer_num=4, filters=32, kernels_sizes=2)(x)
	model = tf.keras.models.Model(input_tensor, x)
	# model.compile(loss='binary_crossentropy', metrics=['accuracy'])
	model.summary()
	model.save('test.h5')
	netron.start('test.h5')

**Other info / logs**  
ValueError: Graph disconnected: cannot obtain value for tensor Tensor("conv2d_2/Identity:0", shape=(None, 255, 255, 32), dtype=float32) at layer "concatenate". The following previous layers were accessed without issue: ['input_1', 'batch_normalization', 'elu', 'conv2d', 'batch_normalization_1', 'elu_1', 'conv2d_1']

**Comment by Lasers67** [comment]
Tensorflow evalutates tensors lazily, so when you pass concat in tf.keras.layers.Concatenate(), it is still not evaluated until the model is defined in tf.keras.models.Model, when you define the model in the end, it passes the whole concat array(the final one with all the layers) to each and every Concatenate object due to lazy evaluation and gives the error as not all layers are connected to every concatenate layer, on the other hand when you use list(concat) or concat[:] it copies the array into the function hence all Concatenate functions dont get the same array.
