### ISSUE TITLE
load_model() does not load a trained model.

### ISSUE THREAD

**Issue by paganelle** [keras-team/keras#13505]
I'm trying to save a previously trained model using
modelZ.model.save("modelZ.h5")

this model is somehow trained and gives an accuracy of

_, accuracy = modelZ.evaluate(I, Z)
print('Accuracy: %.2f' % (accuracy*100))

_2852/2852 [==============================] - 2s 664us/step
Accuracy: 66.34_
 
but if I try to load this model in the different script 

modelX = load_model("modelZ.h5")
_, accuracy = modelX.evaluate(I, Z)
print('Accuracy of loaded model: %.2f' % (accuracy*100))

it gives me: 
_2852/2852 [==============================] - 2s 691us/step
Accuracy of loaded model: 18.48_

Which sounds like the model has not been trained at all. I use the same I and Z vectors to calculate accuracy.

**Comment by war21x3b** [comment]
It seems like https://github.com/keras-team/keras/issues/4875 problem
