### ISSUE TITLE
module 'tensorflow' has no attribute 'placeholder'

### ISSUE THREAD

**Issue by aysayparcasi** [keras-team/keras#13512]
File "C:\Users\User\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 517, in placeholder
    x = tf.placeholder(dtype, shape=shape, name=none)

AttributeError: module 'tensorflow' has no attribute 'placeholder'

How can I get rid of this kind of error?

**Comment by silkspace** [comment]
I am seeing the same error on OSX in virtenv using tensorflow==2.0.0, (virtualenv==16.7.7, Keras==2.2.4)

**Comment by vwurstep** [comment]
I am having the same problem. Did you solve your issue?

**Comment by selrahc** [comment]
I had the same problem. I solved it by re-installing Keras.
pip uninstall keras
conda install keras

**Comment by vwurstep** [comment]
The issue for me was that Tensorflow 2.x does not use tf.placeholders (and tf.session()) anymore. 

This guide from Tensorflow explains the changes from Tensorflow 1.x to Tensorflow 2.x and how to convert old code: https://www.tensorflow.org/guide/migrate

**Comment by whoisalbertmatt** [comment]
You may also try rewriting the code.
tf.compat.v1.placeholder(dtype, shape=shape, name=none). 
Also, you may need to migrate to TF2 (the new version of tensorflow) to avoid any possible errors in the future.
