### ISSUE TITLE
How to use KerasClassifier with fit_generator method?

### ISSUE THREAD

**Issue by wangyexiang** [keras-team/keras#13522]
I want to perform Hyperparameter Optimization on my Keras Model. The problem is the dataset is quite big, normally in training I use fit_generator to load the data in batch from disk, but the common package like SKlearn Gridsearch, etc. only support fit method. How to use GridSearchCV to implement fit_generator() method? Is it possible to use Keras's scikit-learn API together with fit_generator() method? Thank you.

**Comment by kmader** [comment]
@wangyexiang at the moment these wrappers don't support using the `.fit_generator` with the principal reason being the standard usage of sklearn estimators is to give them a `X, y` pair to fit and a single `X` to predict on. I am looking into making a general version which would allow for augmentation and the usage of a generator, what use case are you looking at?

**Comment by wangyexiang** [comment]
@kmader Dear sir, thank you for your reply. I have given up using this wrapper, and finally I choose kerastuner instead. If you could make a general wrapper, that will be pretty useful for performing hyperparameter optimization with a big dataset. GridSearchCV can allow you to set `n_job=-1`, this can accelerate the optimization process with parallel searching.

**Comment by Jakylsus** [comment]
[keras_batch_classifier.zip](https://github.com/keras-team/keras/files/4453445/keras_batch_classifier.zip)

**Comment by Jakylsus** [comment]
[keras_batch_classifier.zip](https://github.com/keras-team/keras/files/4453458/keras_batch_classifier.zip)
