### ISSUE TITLE
Could not pack sequence. Structure had 2 elements, but flat_sequence had 1 elements. 

### ISSUE THREAD

**Issue by qihuanwuqi** [keras-team/keras#13534]
Could not pack sequence. Structure had 2 elements, but flat_sequence had 1 elements. 
 Structure: [<tf.Tensor 'conv_gr_u2d_1/convolution:0' shape=(None, 64, 64, 40) dtype=float32>, <tf.Tensor 'conv_gr_u2d_1/convolution:0' shape=(None, 64, 64, 40) dtype=float32>],
 flat_sequence: [<tf.Tensor 'add_5:0' shape=(None, 64, 64, 40) dtype=float32>].

**Comment by kaiyu-tang** [comment]
how you solved this problem?

**Comment by 5tomato** [comment]
If this is still an issue, would you be able to provide more information so I can try to reproduce it?
