### ISSUE TITLE
Slow import of Keras array_to_img

### ISSUE THREAD

**Issue by sivi29y** [keras-team/keras#13538]
trying upload just one function from eras take me considerable time 
this is on ubuntu 18.04 under aws 
other functions such as bumpy are ok 
this is the only line of code I expect it to be much faster maybe 0.2 sec not 1+ why is it like so and is it solvable? how ? 
I hope this is a legit question I looked on the internet and did not find any hint of what to do.

<from keras.preprocessing.image import array_to_img > 

2019-11-10 10:09:51,380 - root - DEBUG - np 1 1573380591.3805187
2019-11-10 10:09:52,989 - root - DEBUG - tf 1 1573380592.9898841

**Comment by sivi29y** [comment]
tf 1.14 cpu 
Keras 2.3.1
I had this issue on GPU setup also

**Comment by kartik4949** [comment]
what do you mean by upload?
you mean import?

**Comment by sivi29y** [comment]
Improved on faster clock
