### ISSUE TITLE
ValueError: Error when checking input: expected input_14 to have 2 dimensions, but got array with shape (3, 1, 3)

### ISSUE THREAD

**Issue by im1111** [keras-team/keras#13546]
help me please i'm trying to write a simple model with tensor as input but i keep getting same error when it comes to the shape of tensor
ValueError: Error when checking input: expected input_14 to have 2 dimensions, but got array with shape (3, 1, 3)
inputs = Input(shape=(9,))
output_1 = Dense(3, activation='relu')(inputs)
output_2 = Dense(2, activation='relu')(output_1)
predictions = Dense(1, activation='softmax')(output_2)

model = Model(inputs=inputs, outputs=predictions)
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
model.fit(X_train)

**Comment by 22preich** [comment]
Please provide some information about the data you are trying to pass in. Also, use some 
`code blocks`
for readability.
