### ISSUE TITLE
After multi GPU train，use load_model(), got RuntimeError: You must compile your model before using it.

### ISSUE THREAD

**Issue by tiancailin** [keras-team/keras#13548]
**System information**  
- OS :  Ubuntu 18.04
- TensorFlow backend (yes / no):  yes
- TensorFlow version: 1.14  
- Keras version:  2.3.1
- Python version:  3.6.x
- CUDA/cuDNN version:  CUDA is 10.0 
- GPU model and memory:  RTX 2080ti * 2

In train, I use this code, like keras offical Document
```
with tf.device('/cpu:0'):
	model = Model(..)
parallel_model = multi_gpu_model(model, gpus=2)
parallel_model.compile(...)
parallel_model.fit_generator(...)
model.save(...)
```

This phase is ok，it works,train a network and save a .h5 model file,just like I use single GPU

But when I try to use the model file to evaluate_generator() or predict() some picture
I use the same code,just like I load single GPU trained .h5 model file

```
model = load_model("my model file")
test_loss, test_acc = model.evaluate_generator("my test file's directory", .....)
```
I got a error:

/python3.6/site-packages/keras/engine/saving.py:341: UserWarning: **No** training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('**No training configuration found** in save file: '

Traceback (most recent call last):
File "my_eval.py", line 115, in <module>
    data_eval()
    in data_eval
    test_loss, test_acc = model.evaluate_generator(test_generator, steps=test_generator.samples / batch_size,verbose=1)
........some python file information..........
File "/home/xxxxx/.local/lib/python3.6/site-packages/keras/engine/training.py", line 337, in _make_test_function
    raise RuntimeError('You must compile your model before using it.')
RuntimeError: You must compile your model before using it.

I can't understand，why I can load a .h5 model file(by SINGLE GPU trained ) and get what I expected result.
But when I load a .h5 model file(by MULTIPLE GUPs trained) with the same code, I got an error？

And in my mind,only model.fit() or model.fit_generator() need compile the model, evaluate() or predict() is need not compile model.

Is in mulitple GPU mode, save and load model file is difference whit single GPU mode?

Did I make some mistake？

Please help me,thank you...

**Comment by xv1nx** [comment]
I always get some errors if I try to load the weights of a multi-gpus model for fine-tuning.
My workaround looks like this:
- if you print your summary, normally you should get something like this:
![grafik](https://user-images.githubusercontent.com/1759396/70125835-f117a780-1677-11ea-878f-8c4b5c54aaf8.png)
- You notice, there is a layer named "model_1" of Type Model.
- Now, just get this layer and save it, you will get a single-gpu lightweight model:
`mod = keras.models.load_model(MODEL_CHECKPOINT)`
`model1 = mod.get_layer("model_1") `
`filename = get_single_model_filename(MODEL_CHECKPOINT)`
