### ISSUE TITLE
ValueError: Tensor("training/Adam/Const:0", shape=(), dtype=float32) must be from the same graph as Tensor("sub:0", shape=(), dtype=float32)

### ISSUE THREAD

**Issue by pascaltx** [keras-team/keras#13554]
Hello,
I implemented ssd7 (https://github.com/pierluigiferrari/ssd_keras/blob/master/ssd7_training.ipynb) and got error(ValueError:Tensor(training/Adam..).And I tried tensorflow 1.13-2.0 and with keras 2.0-2.3 and no luck. Also tried to changed K. Clear_session() to keras.backend.clear_session() and still have same error. Also tried on conda and pip.
Can anyone help ?

- OS Platform and Distribution (e.g., Linux Ubuntu 18.04):  same issue on windows
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  1.13, 1.14, 2.0
- Keras version:  2.0, 2.1, 2.2, 2.3
- Python version:  3.6, 3.7.4
- CUDA/cuDNN version:  7.6.2
- GPU model : rtx2080ti and 840m ( same issue on different Pc and laptob)

**Comment by kartik4949** [comment]
Mine is Working fine.
Have you modified anything?

**Comment by pascaltx** [comment]
Hi, I did not change anything. Just use orginal one and got this issue. Thanks for replying.

**Comment by kartik4949** [comment]
and can you reproduce the error and send me the snippet too?

**Comment by pascaltx** [comment]
Until there is no error. But when this code cell is running then I get error. 
# TODO: Set the epochs to train for.
# If you're resuming a previous training, set `initial_epoch` and `final_epoch` accordingly.
initial_epoch   = 0
final_epoch     = 20
steps_per_epoch = 100

history = model.fit_generator(generator=train_generator,
                              steps_per_epoch=steps_per_epoch,
                              epochs=final_epoch,
                              callbacks=callbacks,
                              validation_data=val_generator,
                              validation_steps=ceil(val_dataset_size/batch_size),
                              initial_epoch=initial_epoch)


**errors are:**


ValueError                                Traceback (most recent call last)
<ipython-input-8-0679422235f3> in <module>
     11                               validation_data=val_generator,
     12                               validation_steps=ceil(val_dataset_size/batch_size),
---> 13                               initial_epoch=initial_epoch)

~/anaconda3/envs/ssd/lib/python3.6/site-packages/keras/legacy/interfaces.py in wrapper(*args, **kwargs)
     89                 warnings.warn('Update your `' + object_name + '` call to the ' +
     90                               'Keras 2 API: ' + signature, stacklevel=2)
---> 91             return func(*args, **kwargs)
     92         wrapper._original_function = func
     93         return wrapper

~/anaconda3/envs/ssd/lib/python3.6/site-packages/keras/engine/training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   1416             use_multiprocessing=use_multiprocessing,
   1417             shuffle=shuffle,
-> 1418             initial_epoch=initial_epoch)
   1419 
   1420     @interfaces.legacy_generator_methods_support

~/anaconda3/envs/ssd/lib/python3.6/site-packages/keras/engine/training_generator.py in fit_generator(model, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
     38 
     39     do_validation = bool(validation_data)
---> 40     model._make_train_function()
     41     if do_validation:
     42         model._make_test_function()

~/anaconda3/envs/ssd/lib/python3.6/site-packages/keras/engine/training.py in _make_train_function(self)
    507                     training_updates = self.optimizer.get_updates(
    508                         params=self._collected_trainable_weights,
--> 509                         loss=self.total_loss)
    510                 updates = (self.updates +
    511                            training_updates +

~/anaconda3/envs/ssd/lib/python3.6/site-packages/keras/legacy/interfaces.py in wrapper(*args, **kwargs)
     89                 warnings.warn('Update your `' + object_name + '` call to the ' +
     90                               'Keras 2 API: ' + signature, stacklevel=2)
---> 91             return func(*args, **kwargs)
     92         wrapper._original_function = func
     93         return wrapper

~/anaconda3/envs/ssd/lib/python3.6/site-packages/keras/optimizers.py in get_updates(self, loss, params)
    482 
    483         t = K.cast(self.iterations, K.floatx()) + 1
--> 484         lr_t = lr * (K.sqrt(1. - K.pow(self.beta_2, t)) /
    485                      (1. - K.pow(self.beta_1, t)))
    486 

~/anaconda3/envs/ssd/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py in sqrt(x)
   1494     zero = _to_tensor(0., x.dtype.base_dtype)
   1495     inf = _to_tensor(np.inf, x.dtype.base_dtype)
-> 1496     x = tf.clip_by_value(x, zero, inf)
   1497     return tf.sqrt(x)
   1498 

~/anaconda3/envs/ssd/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py in wrapper(*args, **kwargs)
    178     """Call target, and fall back on dispatchers if there is a TypeError."""
    179     try:
--> 180       return target(*args, **kwargs)
    181     except (TypeError, ValueError):
    182       # Note: convert_to_eager_tensor currently raises a ValueError, not a

~/anaconda3/envs/ssd/lib/python3.6/site-packages/tensorflow/python/ops/clip_ops.py in clip_by_value(t, clip_value_min, clip_value_max, name)
     65   """
     66   with ops.name_scope(name, "clip_by_value",
---> 67                       [t, clip_value_min, clip_value_max]) as name:
     68     values = ops.convert_to_tensor(
     69         t.values if isinstance(t, ops.IndexedSlices) else t, name="t")

~/anaconda3/envs/ssd/lib/python3.6/site-packages/tensorflow/python/framework/ops.py in __enter__(self)
   6506       if self._values is None:
   6507         self._values = []
-> 6508       g = _get_graph_from_inputs(self._values)
   6509       self._g_manager = g.as_default()
   6510       self._g_manager.__enter__()

~/anaconda3/envs/ssd/lib/python3.6/site-packages/tensorflow/python/framework/ops.py in _get_graph_from_inputs(op_input_list, graph)
   6133         graph = graph_element.graph
   6134       elif original_graph_element is not None:
-> 6135         _assert_same_graph(original_graph_element, graph_element)
   6136       elif graph_element.graph is not graph:
   6137         raise ValueError("%s is not from the passed-in graph." % graph_element)

~/anaconda3/envs/ssd/lib/python3.6/site-packages/tensorflow/python/framework/ops.py in _assert_same_graph(original_item, item)
   6069   if original_item.graph is not item.graph:
   6070     raise ValueError("%s must be from the same graph as %s." %
-> 6071                      (item, original_item))
   6072 
   6073 

ValueError: Tensor("training/Adam/Const:0", shape=(), dtype=float32) must be from the same graph as Tensor("sub:0", shape=(), dtype=float32).

**Comment by kartik4949** [comment]
my tensorflow version = 1.14.0
keras = 2.2.4
cudnn = 10.0

so update ur cudnn/cuda accordingly
it will work
Thanks.

**Comment by pascaltx** [comment]
Actuallay I tried all versions, but i will check this specific versions again.
Many thanks
