### ISSUE TITLE
NaN output on Tensorflow and Theano backend while CNTK output normally

### ISSUE THREAD

**Issue by Dandy-John** [keras-team/keras#13571]
## Environment settings

Nvidia Driver Version: 430.50

CUDA Version: 10.1

GeForce RTX 2080 Ti

Ubuntu 16.04.6 LTS

| Library                        | Version  |       |
| ------------------------------ | -------- | ----- |
|libgpuarray               |0.7.6                |h14c3975_0|
|pygpu                     |0.7.6            |py36h035aef0_0|
|tensorflow-gpu            |1.14.0                    |\<pip>|
|tensorflow-estimator      |1.14.0                    |\<pip>|
|Theano                    |1.0.4                     |\<pip>|
|cntk-gpu                  |2.7                       |\<pip>|
|numpy                     |1.14.6           |py36h3b04361_4|
|numpy-base                |1.14.6           |py36h81de0dd_4|
|keras-applications        |1.0.8                      |py_0|
|keras-preprocessing       |1.1.0                      |py_1|

---

## Description

mobilenet.1.00.224-imagenet_origin0-NAI1-LS1-GF1-GF2.h5 is a model for image classification. We find something strange when we run this model for some inputs. When we load this model in Keras, this model works well on the backend of CNTK, but when we configure Tensorflow or Theano as the backend of Keras, the output of this model is NaN, which seems quite strange.

We attach the .h5 file, input image and the code below. The phenomenon I described above can be reproduced using this command:

```
python get_prediction.py [backend name]
```

[20191114-nan.zip](https://github.com/keras-team/keras/files/3877869/20191114-nan.zip)

**Comment by Justobe** [comment]
In addition, I found that the model also got NAN results with backend MXNET. It appears that all three backends treat the model as the same way.
