### ISSUE TITLE
RuntimeError: "Cannot clone object ..." when using sklearn.base.clone with BaseEstimator

### ISSUE THREAD

**Issue by mcarbajo** [keras-team/keras#13586]
#### Description

RuntimeError thrown when using `sklearn.base.clone` due to the fact that `get_params` of `KerasClassifier` returns copies instead of references.

Sanity check at the end of the `clone` function fails when the implementation of the estimator used, copies parameters in the `get_params` method.

The `scikit-learn` issue [15722](https://github.com/scikit-learn/scikit-learn/issues/15722) opens the discussion whether the behaviour of their estimator cloning functionality is incorrect or just poorly documented. 

This bug may also affect 'KerasRegressor`.

#### Steps/Code to Reproduce

```python
from keras.wrappers.scikit_learn import KerasClassifier
from keras.models import Sequential
from keras.layers import Dense
 
from sklearn.base import clone
 
def create_keras_classifier_model(n_classes):
    """Keras multinomial logistic regression creation model
 
    Args:
        n_classes(int): Number of classes to be classified
 
    Returns:
        Compiled keras model
 
    """
    # create model
    model = Sequential()
    model.add(Dense(n_classes, activation="softmax"))
    # Compile model
    model.compile(
        loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"]
    )
    return model
 
estimator = KerasClassifier(build_fn=create_keras_classifier_model, n_classes=2, class_weight={0: 1, 1:3})
 
clone(estimator)
```

#### Expected Results

No error is thrown.

#### Actual Results

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-520f4ee6e745> in <module>
     26 estimator = KerasClassifier(build_fn=create_keras_classifier_model, n_classes=2, class_weight={0: 1, 1:3})
    27
---> 28 clone(estimator)
 
/usr/local/anaconda/envs/ivan/lib/python3.6/site-packages/sklearn/base.py in clone(estimator, safe)
     73             raise RuntimeError('Cannot clone object %s, as the constructor '
     74                                'either does not set or modifies parameter %s' %
---> 75                                (estimator, name))
     76     return new_object
     77
 
RuntimeError: Cannot clone object <keras.wrappers.scikit_learn.KerasClassifier object at 0x7f7504148f28>, as the constructor either does not set or modifies parameter class_weight
```

**Comment by sal7g86** [comment]
there is a problem, if param is an array... 

param1
 [150, 50]

param2
 [150, 50]

param1 is not param2
True

# quick sanity check of the parameters of the clone
    for name in new_object_params:
        param1 = new_object_params[name]
        param2 = params_set[name]
        if param1 is not param2:
            raise RuntimeError('Cannot clone object %s, as the constructor '
                               'either does not set or modifies parameter %s' %
                               (estimator, name))

**Comment by oxqfsyef** [comment]
Shallow copying instead of deep in get_params appears to fix this (tested only with callbacks):
`
    def get_params(self, **_params):
        return dict(self.sk_params, build_fn=self.build_fn)
`

**Comment by mcarbajo** [comment]
Pull request #13598 does that.

**Comment by redoine-zitouni** [comment]
> #### Description
> 
> RuntimeError thrown when using `sklearn.base.clone` due to the fact that `get_params` of `KerasClassifier` returns copies instead of references.
> 
> Sanity check at the end of the `clone` function fails when the implementation of the estimator used, copies parameters in the `get_params` method.
> 
> The `scikit-learn` issue [15722](https://github.com/scikit-learn/scikit-learn/issues/15722) opens the discussion whether the behaviour of their estimator cloning functionality is incorrect or just poorly documented.
> 
> This bug may also affect 'KerasRegressor`.
> ```
This bug affects KerasRegressor. I am currently facing the same issue.

**Comment by sebastian-steindl** [comment]
I hat the same error when trying to pass an nested 2d array as parameters. I changed to to a tuple and it works.
E.g.:
Change
`param = [[1,2], [3,4]] 
`
to
`param = [(1,2), (3,4)]`

**Comment by furian-rising** [comment]
Under sklearn.model_selection._search.py (sklearn version 0.22.1) line 735, nested clone call seems to be responsible: 

self.best_estimator_ = clone(clone(base_estimator).set_params(
            **self.best_params_))

seems to be the culprit.  It changed from the following in a previous version:

self.best_estimator_ = clone(base_estimator).set_params(
                **self.best_params_)

Changing this back to the previous version seems to fix the error (Cannot clone object...), though not sure that is the correct solution... based upon the discussion in this thread.

Thoughts??

**Comment by Cynwell** [comment]
> I had the same error when trying to pass an nested 2d array as parameters. I changed to to a tuple and it works.
> E.g.:
> Change
> `param = [[1,2], [3,4]] `
> to
> `param = [(1,2), (3,4)]`

Yes I could confirm that this dirty fix could temporarily solve the problem. The problem seems to occur when the param is of higher dimensions (>1 dimension).

**Comment by ashishsangwan18** [comment]
This is sklearn bug. You should reduce the version of sklearn:

conda install scikit-learn==0.21.2

**Comment by mcemilg** [comment]
I was having the same issue. None of them solved my problem. Actually it seems my problem was a little bit different, maybe it will helps to somebody with same error. The problem is actually about the model I pass. I was passing a `pipeline` model includes a `keras`  model. 
```python
model = KerasClassifier(build_fn = create_model, verbose=0, nodes=nodes, lr=lr, input_shape=(n,))
kpca_mlp = Pipeline([('kpca', kpca), ('mlp', model)])
param_grid = {
    'kpca__gamma': [0.1, 0.01, 0.001, 0.0001]
}
clf = GridSearchCV(estimator=kpca_mlp, param_grid=param_grid)
```
I was trying to pass keras model fit parameters to the  grid search fit function. And I got the same error you have.
```python
    fit_params = {
        "batch_size":batch_size,
        "epochs":epochs,
        "verbose":0,
        "callbacks" : [
            keras.callbacks.EarlyStopping(patience=2)
        ],
        "mlp__validation_data":(X_dev, y_dev)
    }
    clf.fit(X_train, y_train, **fit_params)
``` 
The problem is I am passing the keras parameters to the `Pipeline` object. Changing paramater names to pass to keras model fit function fixed my problem.
```python
    fit_params = {
        "mlp__batch_size":batch_size,
        "mlp__epochs":epochs,
        "mlp__verbose":0,
        "mlp__callbacks" : [
            keras.callbacks.EarlyStopping(patience=2)
        ],
        "mlp__validation_data":(X_dev, y_dev)
    }
    clf.fit(X_train, y_train, **fit_params)
```
No need to change version for me.

**Comment by sam1902** [comment]
Hi, I have the same issue, it seems to come from initialising parameter ranges using numpy arrays. 
Versions:
```
Python 3.8.1
numpy==1.18.5
scikit-learn==0.23.1
tensorflow==2.2.0
```
Full code for reproducibility:
```python
#!/usr/bin/env python3
import numpy as np

from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV

def load_dataset():
    """ Load all the data """
    # Load pima indians dataset
    # https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv
    dataset = np.loadtxt("pima-indians-diabetes.csv", delimiter=",")
    # Split into input (X) and output (Y) variables
    X = dataset[:,:8]
    Y = dataset[:,8]
    return X, Y

def create_model():
    """ Creates a Keras model """
    model = Sequential()
    model.add(Dense(12, input_dim=8, activation="relu"))
    model.add(Dense(8, activation="relu"))
    model.add(Dense(1, activation="sigmoid"))

    model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])
    return model

def main():
    """Main function"""
    # Load dataset
    X, Y = load_dataset()
    # Create model
    model = KerasClassifier(build_fn=create_model, epochs=150, batch_size=10, verbose=0)
    pipeline = Pipeline([
        ('scale', StandardScaler()),
        ('mlp', model)])
    param_grid_working = dict(
            mlp__epochs=[150,200,250,300],
            mlp__batch_size=[16,32,64,128]
        )
    param_grid_breaking = dict(
            mlp__epochs=list(np.arange(150,301,50)),
            mlp__batch_size=list(2**np.arange(4,8))
        )
    print("Works ", param_grid_working)
    print("Breaks", param_grid_breaking)
    param_grid = param_grid_breaking
    grid = GridSearchCV(pipeline, param_grid=param_grid, cv=2, n_jobs=8, verbose=2, scoring='accuracy')
    results = grid.fit(X, Y)
if __name__ == "__main__":
    main()
```
In this simple example, switching between `param_grid = param_grid_breaking` and `param_grid = param_grid_working` respectively breaks or not the cloning process. 
I believe the issue stems from the list members' types in each cases being different (Python's `int` vs Numpy's `np.int64`). 

**You can work around this issue by casting numpy arrays to list using the `.tolist()` method.**

This would probably work for the multidimensional parameters as it conserves the nested list structure, but it discards numpy's dtype for Python's builtin types and uses probably way more memory.

**Comment by libinruan** [comment]
Downgrading the version of Scikit-learn from `0.22.2` to `0.21.2` works for me.

```
sudo python3 -m pip install scikit-learn==0.21.2 --upgrade
```

**Comment by analpaul** [comment]
TypeError: Cannot clone object '<tensorflow.python.keras.engine.sequential.Sequential object at 0x000002B3A00D8AC8>' (type <class 'tensorflow.python.keras.engine.sequential.Sequential'>): it does not seem to be a scikit-learn estimator as it does not implement a 'get_params' method.

**Comment by analpaul** [comment]
TypeError: Cannot clone object '<tensorflow.python.keras.engine.sequential.Sequential object at 0x000002B3A00D8AC8>' (type <class 'tensorflow.python.keras.engine.sequential.Sequential'>): it does not seem to be a scikit-learn estimator as it does not implement a 'get_params' method.

**Comment by omkarsutar1255** [comment]
> I had the same error when trying to pass an nested 2d array as parameters. I changed to to a tuple and it works.
> E.g.:
> Change
> `param = [[1,2], [3,4]] `
> to
> `param = [(1,2), (3,4)]`

But if you have single number in array then use following
Param = [(1,), (3,4)]

**Comment by Ashishsingh25** [comment]
Casting numpy arrays to list using the .tolist() method worked for me. 
Great help @sam1902

**Comment by gioxc88** [comment]
this quick sanity check does more harm than good and it should be removed

**Comment by mrallam** [comment]
I had to create an instance of OneHotEncoder to fixe my code and it worked :)

from sklearn.compose import ColumnTransformer

num_attribs = list(housing_num)
cat_attribs = ["ocean_proximity"]
oneHot = OneHotEncoder()
full_pipeline = ColumnTransformer([
    ("num",num_pipline,num_attribs),
    ("cat",oneHot,cat_attribs),
])

housing_prepared = full_pipeline.fit_transform(housing)
