### ISSUE TITLE
load_model fails when the model use keras.metrics.Precision

### ISSUE THREAD

**Issue by ybzz** [keras-team/keras#13590]
**System information**  
- Have I written custom code (as opposed to using example directory):  yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Linux Debian 3.16.43
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  v1.14.0
- Keras version:  2.3.0
- Python version:  3.6.8

**Describe the current behavior**  
train model with keras.metrics.Precision and save as a hdf5 file
load model from the hdf5 file, got the ValueError

ValueError: Unknown metric function: {'class_name': 'Precision', 'config': {'name': 'precision_1', 'dtype': 'float32', 'thresholds': None, 'top_k': None, 'class_id': None}}

**Describe the expected behavior**  
load model successfully

**Other info / logs**  
the training_config in hdf5 is correct, as shown below

> "metrics": ["accuracy", {"class_name": "Precision", "config": {"name": "precision_1", "dtype": "float32", "thresholds": null, "top_k": null, "class_id": null}}, {"class_name": "Recall", "c    onfig": {"name": "recall_1", "dtype": "float32", "thresholds": null, "top_k": null, "class_id": null}}]
> 

But the way of deserializing metrics is wrong in function keras.metrics.get
```
def get(identifier):
    if isinstance(identifier, dict):
        config = {'class_name': str(identifier), 'config': {}}
        return deserialize(config)
    elif isinstance(identifier, six.string_types):
        return deserialize(str(identifier))
    elif callable(identifier):
        return identifier
    else:
        raise ValueError('Could not interpret '
                         'metric function identifier:', identifier)
```
the identifier of metric "Precision"
> {"class_name": "Precision", "config": {"name": "precision_1", "dtype": "float32", "thresholds": null, "top_k": null, "class_id": null}}
>
become
>  {'class_name': "{'class_name': 'Precision', 'config': {'name': 'precision_1', 'dtype': 'float32', 'thresholds': None, 'top_k': None, 'class_id': None}}", 'config': {}}
>

**Comment by Z-Donald** [comment]
I have try:
load_model('model.h5', custom_objects={'Precision': keras.metrics.Precision(), 'Recall': keras.metrics.Recall()}),
but it fails too.

**Comment by dcshapiro** [comment]
same here

**Comment by Z-Donald** [comment]
But when I use keras_metrics.precision() and keras_metrics.recall()
and use
with CustomObjectScope({'binary_precision': keras_metrics.precision(), 'binary_recall':keras_metrics.recall()}):
        model = load_model('model')

to load the model, it succeeds.

**Comment by Z-Donald** [comment]
But when I use keras_metrics.precision() and keras_metrics.recall()
and use
with CustomObjectScope({'binary_precision': keras_metrics.precision(), 'binary_recall':keras_metrics.recall()}):
    model = load_model('model')

to load the model, it succeeds.

**Comment by vincentmichael089** [comment]
I have the same problem in Keras version: 2.3.0 and in my case, this behaviour can be fixed by using tf.keras.models.load_model instead of direct load_model.  hope it helps, cheers.

**Comment by jntorres** [comment]
thanks @vincentmichael089 this suggestion worked for me

**Comment by jimmykimmy68** [comment]
> I have the same problem in Keras version: 2.3.0 and in my case, this behaviour can be fixed by using tf.keras.models.load_model instead of direct load_model. I also change every import statement from 'keras' to 'tensorflow.keras' to avoid crash between old keras and new tensorflow.keras. hope it helps, cheers.

This worked for me too!
