### ISSUE TITLE
cifar 10 capsule example problem

### ISSUE THREAD

**Issue by alitk** [keras-team/keras#13599]
<em>Please make sure that this is a Bug or a Feature Request and provide all applicable information asked by the template.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.</em>  

**System information**  
- Have I written custom code (as opposed to using example directory):   No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Google Colab
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  1.15.0
- Keras version:  2.2.5
- Python version:  3.6.8
- CUDA/cuDNN version: CUDA Version 10.0.130 
- GPU model and memory:  Tesla K80

You can obtain the TensorFlow version with:  
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"  
You can obtain the Keras version with:  
python -c 'import keras as k; print(k.__version__)'  

**Describe the current behavior**  
Using TensorFlow backend.
Downloading data from https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz
170500096/170498071 [==============================] - 7s 0us/step
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:66: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:541: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4432: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4271: The name tf.nn.avg_pool is deprecated. Please use tf.nn.avg_pool2d instead.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-53cd1c390bd2> in <module>()
    161 
    162 x = Reshape((-1, 128))(x)
--> 163 capsule = Capsule(10, 16, 3, True)(x)
    164 output = Lambda(lambda z: K.sqrt(K.sum(K.square(z), 2)))(capsule)
    165 model = Model(inputs=input_image, outputs=output)

2 frames
/usr/local/lib/python3.6/dist-packages/keras/engine/base_layer.py in __call__(self, inputs, **kwargs)
    449             # Actually call the layer,
    450             # collecting output(s), mask(s), and shape(s).
--> 451             output = self.call(inputs, **kwargs)
    452             output_mask = self.compute_mask(inputs, previous_mask)
    453 

<ipython-input-2-53cd1c390bd2> in call(self, inputs)
    120             o = self.activation(K.batch_dot(c, hat_inputs, [2, 2]))
    121             if i < self.routings - 1:
--> 122                 b = K.batch_dot(o, hat_inputs, [2, 3])
    123                 if K.backend() == 'theano':
    124                     o = K.sum(o, axis=1)

/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py in batch_dot(x, y, axes)
   1259                          str(x_shape) + ' and ' + str(y_shape) +
   1260                          ' with axes=' + str(axes) + '. x.shape[%d] != '
-> 1261                          'y.shape[%d] (%d != %d).' % (axes[0], axes[1], d1, d2))
   1262 
   1263     # backup ndims. Need them later.

ValueError: Can not do batch_dot on inputs with shapes (None, 10, 10, 16) and (None, 10, None, 16) with axes=[2, 3]. x.shape[2] != y.shape[3] (10 != 16).

**Describe the expected behavior**  
running the example

**Code to reproduce the issue**  
Provide a reproducible test case that is the bare minimum necessary to generate the problem.  
https://keras.io/examples/cifar10_cnn_capsule/

**Other info / logs**  
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ns3284** [comment]
This is due to the change in batch_dot (TF and Keras). Just submitted a pull request for an updated/working version of that example.

https://github.com/keras-team/keras/pull/13620
