### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.contrib' (TF2 + Keras 2.3.1)

### ISSUE THREAD

**Issue by OverLordGoldDragon** [keras-team/keras#13613]
Minimal reproducible example, full error trace, & env info below - don't know what the problem is. Same error in Eager & Graph execution.

<hr>

**Minimal example**:

```python
from keras.layers import Input, CuDNNGRU
from keras.models import Model

ipt = Input((16,100))
out = CuDNNGRU(16)(ipt)
```

<hr>

**Environment**:

- CUDA 10.0.130, cuDNN 7.6.0, TF 2.0.0 + Keras 2.3.1
-  Python 3.7.4, Spyder 3.3.6 IDE, Anaconda virtual environment
- Windows 10 OS, GTX 1070, i7-7700HQ 2.8-GHz CPU

<hr>

**Full error trace**:

```python
File "<ipython-input-1-df21cce0c496>", line 5, in <module>
  out = CuDNNGRU(16)(ipt)
File "D:\Anaconda\envs\tf2_env\lib\site-packages\keras\layers\recurrent.py", line 541, in __call__
  return super(RNN, self).__call__(inputs, **kwargs)
File "D:\Anaconda\envs\tf2_env\lib\site-packages\keras\backend\tensorflow_backend.py", line 75, in symbolic_fn_wrapper
  return func(*args, **kwargs)
File "D:\Anaconda\envs\tf2_env\lib\site-packages\keras\engine\base_layer.py", line 463, in __call__
  self.build(unpack_singleton(input_shapes))
File "D:\Anaconda\envs\tf2_env\lib\site-packages\keras\layers\cudnn_recurrent.py", line 226, in build
  from tensorflow.contrib.cudnn_rnn.python.ops import cudnn_rnn_ops

ModuleNotFoundError: No module named 'tensorflow.contrib'
```

**Comment by talhaanwarch** [comment]
when i use CuDNNLSTM instead of LSTM i got this error

**Comment by tarjintor** [comment]
I got the same problem when I try to use to replace the layer in keras example of baby rnn in [babi_rnn](https://keras.io/examples/babi_rnn/)

**Comment by mike-code** [comment]
I have the same problem as OP

**Comment by FMena14** [comment]
Hi!
I have the same problem using CuDNNGRU, any updates?

**Comment by bill-bateman** [comment]
I had a similar problem but for CuDNNLSTM.
How I fixed it is to use tensorflow.keras, which is recommended by keras.

> At this time, we recommend that Keras users who use multi-backend Keras with the TensorFlow backend switch to tf.keras in TensorFlow 2.0.

See: https://keras.io/

The normal tf.keras.layers.LSTM and tf.keras.layers.GRU will automatically use CuDNN versions if a GPU is there (along with a list of requirements).

Have a look at: https://www.tensorflow.org/api_docs/python/tf/keras/layers/GRU

> If a GPU is available and all the arguments to the layer meet the requirement of the CuDNN kernel (see below for details), the layer will use a fast cuDNN implementation.
> 
> The requirements to use the cuDNN implementation are:
> 
>    1. activation == tanh
>    2. recurrent_activation == sigmoid
>    3. recurrent_dropout == 0
>    4. unroll is False
>    5. use_bias is True
>    6. reset_after is True
>    7. Inputs are not masked or strictly right padded.
