### ISSUE TITLE
connecting 2 pre-trained network in Keras

### ISSUE THREAD

**Issue by rezasabzi** [keras-team/keras#13626]
Hi, 
I have two separate pre-trained network.
Net1: input=x, output=y
Net2: input=y, output=z
is there any way to connect this two network together and make Net3: input=x, out=z and fine-tune the whole joint module?
Thanks in advance!

**Comment by mash2612** [comment]
Hi,
you could try something like this:
model1 = Model(input=x, output=y)
model2 = Model(input=y, output = z)
model3 = Model(input=model1.input, output=model2.output)
and then don't forget to compile the model with the relevant parameters.

Hope this works out!
