### ISSUE TITLE
"ValueError: Graph disconnected" when trying to create a trainable RNN initial hidden state

### ISSUE THREAD

**Issue by fmellomascarenhas** [keras-team/keras#13643]
Hi guys, I have a set of time-series experiments, and each experiment depends on its initial conditions. I am trying to train the initial hidden state of my RNN using these initial conditions.

![image](https://user-images.githubusercontent.com/23004953/71198653-fd545500-2272-11ea-8205-886443dabb4c.png)

**Here is the code:**

    from tensorflow.keras.layers import Input, Dense, LSTM
    from tensorflow.keras.models import Model
    
    input_layer = Input(shape=(16,3))
    hidden_state_dim = 7
    
    mlp_inp = Input(batch_shape=(hidden_state_dim,1))
    mlp_dense_h = Dense(hidden_state_dim, activation='relu')(mlp_inp)
    mlp_dense_c = Dense(hidden_state_dim, activation='relu')(mlp_inp)
    
    x = LSTM(7, return_sequences = True, input_shape = (16, 3))(input_layer, initial_state=[mlp_dense_h, mlp_dense_c])
    
    model = Model(input_layer, x)
**I receive the error:** "ValueError: Graph disconnected: cannot obtain value for tensor Tensor("input_2:0", shape=(7, 1), dtype=float32) at layer "input_2". The following previous layers were accessed without issue: []"

I imagine that the graph is disconnected because there is no back propagation to the mlp_dense_h/c? Any ideas on how to solve this?

Thanks!

I made a post on tensorflow describing it a little bit better: https://stackoverflow.com/questions/59402595/can-i-train-the-initial-hidden-state-of-a-rnn-to-represent-the-initial-condition

**Comment by ns3284** [comment]
What is passed to mlp_inp? You have two inputs, input_layer and mlp_inp. Nothing is given to mlp_inp, and thus cannot be forwarded to your other two dense layers.

That is what the error is saying.
 > cannot obtain value for tensor Tensor("input_2:0", shape=(7, 1), dtype=float32) at layer "input_2".
