### ISSUE TITLE
Unable to use `sparse_categorical_accuracy` with softmax output ndims=3

### ISSUE THREAD

**Issue by qtdaniel** [keras-team/keras#13642]
**System information**  
- Have I written custom code (as opposed to using example directory):  yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Ubuntu 16.04
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  1.14 (built from source)
- Keras version:  (built-in TF version)
- Python version:  3.7.4
- CUDA/cuDNN version:  10.0
- GPU model and memory:  GeForce RTX 2070 8G

**Describe the current behavior**  
Running the following minimal example

```
import numpy
from tensorflow import keras

x = keras.layers.Input(shape=(8,), dtype="int32")
y = keras.layers.Embedding(4, 2)(x)
y = keras.layers.Dense(4, activation="softmax")(y)

training_model = keras.Model(x, y)

training_model.compile(
    keras.optimizers.SGD(),
    loss=keras.losses.sparse_categorical_crossentropy,
    metrics=[keras.metrics.sparse_categorical_accuracy]
)

data = numpy.random.randint(4, size=(16, 8))
training_model.fit(x=data, y=data)
```

results in

```
Traceback (most recent call last):
  File "issue.py", line 18, in <module>
    training_model.fit(x=data, y=data)
  File "/python_env/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 780, in fit
    steps_name='steps_per_epoch')
  File "/python_env/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 363, in model_iteration
    batch_outs = f(ins_batch)
  File "/python_env/lib/python3.7/site-packages/tensorflow/python/keras/backend.py", line 3292, in __call__
    run_metadata=self.run_metadata)
  File "/python_env/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1458, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Can not squeeze dim[1], expected a dimension of 1, got 8
	 [[{{node metrics/sparse_categorical_accuracy/Squeeze}}]]
	 [[metrics/sparse_categorical_accuracy/Identity/_65]]
  (1) Invalid argument: Can not squeeze dim[1], expected a dimension of 1, got 8
	 [[{{node metrics/sparse_categorical_accuracy/Squeeze}}]]
0 successful operations.
0 derived errors ignored.
```

but commenting out the `metrics=[keras.metrics.sparse_categorical_accuracy]` line results in success.

**Describe the expected behavior**  

When using categorical targets it should be possible to use `keras.metrics.sparse_categorical_accuracy`

**Code to reproduce the issue**  
See above.

**Other info / logs**  
N/A

**Comment by qtdaniel** [comment]
Attempting to debug this by copy-pasting the code for `sparse_categorical_accuracy` and adding some `keras.backend.print_tensor` operations suggests something very strange: the symbolic shape of `y_true` is `(?, ?, ?)` (note: 3 dimensions) but the concrete value at runtime has only 2 dimensions. The 2 dimensions are correct because it's an integer array but because the symbolic shape is incorrect, the set of operations being applied causes the "squeeze" error. How can Keras be getting the symbolic shape of the targets so wrong?

**Comment by qtdaniel** [comment]
I've found a work-around: `training_model.fit(x=data, y=numpy.expand_dims(data, -1))`

**Comment by sushreebarsa** [comment]
@qtdaniel We see that you are using old version of tensorflow which is not actively supported now, please verify on 2.x and open a new issue in case you face any errors, hence moving this to closed status.Thanks!
