### ISSUE TITLE
customize loss function for Model.compile() loss argument

### ISSUE THREAD

**Issue by XzwHan** [keras-team/keras#13654]
I plan to use the sum of the negative log-likelihood from two distinct networks with two distinct dataset as my loss function, i.e. it would look something like
```
custom_loss = - (network1_output.log_prob(Y_1)+network2_output.log_prob(Y_2))
```
but as I ran 
```
model.compile(loss=custom_loss...)
```
I came across the following error:
```
OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.
```
I'm able to see that the output of custom_loss is a tf.Tensor object with shape=(None,), however the loss argument in Model.compile() function expects a function; but how do I customize a loss function that computes the log_prob from a distribution? The posts I found online pointed me to use Keras.backend.function() to construct custom loss function, and I tried something like
```
custom_loss_func = tfk.backend.function((network1_output, Y_1, network2_output, Y_2), custom_loss)
model.compile(loss=custom_loss_func...)
```
but received 
```
AttributeError: 'Independent' object has no attribute 'op'
```
from the first line of code above.

So this is what I've tried so far; any suggestions on how to make custom loss function with above mentioned pattern?

**Comment by sol0invictus** [comment]
If I understand you correctly you want a loss function that can deal with multiple (y_pred) and multiple (y_actual) ?

Let me give you an example of such a thing I implemented.

```
def me_loss(self,y_actual,y_pred):
 a,b=tf.split(y_actual, [1, 1], 1)
 a=tf.dtypes.cast(a, tf.int32)
 b=tf.dtypes.cast(b, tf.float32)
 selected_action_values = tf.math.reduce_sum(y_pred * tf.one_hot(a, self.K)) 
 cost = tf.math.reduce_mean(tf.math.squared_difference(b, selected_action_values)) 
 return cost
```


Lets walk through the code (the actual loss is irrelevant but I will walk you on how to deal with multiple values of arguments).
The loss function ALWAYS needs to have only 2 arguments (no matter how many y-actual or how many y_pred. So in this case I have only one y_pred but I have y_actual1 and y_actual2. To pass them both to the loss function I put both of them in a tensor of form y_actual = [y_actual1,y_actual2] in the model train function. When the loss is called I manually split y_actual to obtain both the two different y_actuals. Similar thing can be done with y_pred.
Hope this helps

**Comment by XzwHan** [comment]
I've found a solution that can be directly applied for .compile() function, instead of using tfk.backend.function:

We could implement multiple loss functions, say loss_fn_1 and loss_fn_2 (each has to have only two arguments in the form of y_true, y_pred); then during model building and compiling, we could write something like:
```
model = tf.Keras.Model(inputs=Keras_Input_objects, outputs=[output_1, output_2])
```
and
```
model.compile(loss=[loss_fn_1, loss_fn_2], loss_weights = weight_list, optimizer=tfk.optimizers.Adam(learning_rate))
```
in which weight_list is a list of coefficients for loss functions to form the final loss function. When we train the model, we call
```
model.fit(x=X_inputs, y=[Y_1, Y_2], …)
```
such that (Y_1, output_1) and (Y_2, output_2) each forms the argument of the corresponding loss function loss_fn_1 and loss_fn_2.
