### ISSUE TITLE
Code execution does not end

### ISSUE THREAD

**Issue by AvisP** [keras-team/keras#13666]
Hi,

When I ran the following line of code 

`x = Dense(intermediate_dim, activation='relu')(latent_inputs)`

its execution takes forever and does not end. No error messages also. Not sure what the issue is. Any help will be appreciated. 

Keras version 2.3.1
Tensorflow version 2.1.0-dev20191204
Python 3.7.5

**Comment by ns3284** [comment]
So much detail is missing from this. Nothing about that line of code raises any flags.

**Comment by AvisP** [comment]
I apologize for incomplete post. I was trying to run the variational autoencoder [example](https://github.com/keras-team/keras/blob/master/examples/variational_autoencoder.py) and had issue in the mentioned line. 

The issue seems to happen when I am running on the GPU version of tensforflow and does not happen on the CPU one.

**Comment by sushreebarsa** [comment]
@AvisP It looks like you are using an older Version of Tensorflow 2.1. Many bugs have been fixed in the latest version. Can you please execute your code using Latest Version 2.4.1 or 2.5 and let us know if the issue still persists? Thanks!

**Comment by sushreebarsa** [comment]
Closing this issue due to lack of recent activity & assuming this issue as resolved .Please feel free to reopen if you still have concern.Thanks!
