### ISSUE TITLE
ValueError: Error when checking target: expected activation_92 to have shape (2,) but got array with shape (1,

### ISSUE THREAD

**Issue by Kashyab19** [keras-team/keras#13686]
model = Sequential()
# 3 convolutional layers
model.add(Conv2D(32, (3, 3), input_shape = X.shape[1:]))
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Conv2D(64, (3, 3)))
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Conv2D(64, (3, 3)))
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.25))

# 4hidden layers
model.add(Flatten())
model.add(Dense(64))
model.add(Activation("relu"))

model.add(Dense(64))
model.add(Activation("relu"))

model.add(Dense(64))
model.add(Activation("relu"))

model.add(Dense(64))
model.add(Activation("relu"))

# The output layer with 2 neurons, for 2 classes
model.add(Dense(2))
model.add(Activation("sigmoid"))

model.compile(loss="mean_squared_error",
             optimizer="sgd",
             metrics=['accuracy'])

model.fit(X,Y,batch_size=32,epochs=20,verbose=2,validation_split=0.2,shuffle=True) #Accuracy is 94:

I have only 2 categories

**Comment by Vincent9797** [comment]
Assuming you have binary categories (class 0 and 1), you can do 2 things:

Firstly, have your model output a single value (which is the probability of belonging to class 1) by using a sigmoid activation function. Set your loss function to binary_crossentropy as well.

```
model.add(Dense(1))
model.add(Activation("sigmoid"))

model.compile(loss="binary_crossentropy",
optimizer="sgd",
metrics=['accuracy'])
```

Secondly, you can also choose 2 output 2 values, both adding to 1 by using a softmax layer. One represents the probability of belonging to class 0 and the other representing the probability of belonging to class 1. If your labels are being generated as 0/1, use `sparse_categorical_crossentropy` as the loss function. If your labels are one-hot encoded, use `categorical_crossentropy `as the loss function

```
model.add(Dense(2))
model.add(Activation("softmax"))

model.compile(loss="categorical_crossentropy",
optimizer="sgd",
metrics=['accuracy'])
```
