### ISSUE TITLE
experimental_list_devices in tensorflow_backend.py (line 506)

### ISSUE THREAD

**Issue by vgrankin1** [keras-team/keras#13684]
As we know  experimental_list_devices is removed from tensorflow, so i got an error:
AttributeError: module 'tensorflow_core._api.v2.config' has no attribute 'experimental_list_devices'

when creating 'Sequential' model.
It is happened as i understood beacause tf.config.experimental_list_devices()

tf.__version__ is: 2.1.0
tf.keras.__version__ is: 2.2.4-tf

[Kaggle notebook with error ](https://www.kaggle.com/vitost/kernel-keras-2)

**Comment by AlphaWu** [comment]
experimental_list_devices is deprecated in tf 2.1,use tf.config.list_logical_devices replaced.

`
def _get_available_gpus():
    """Get a list of available gpu devices (formatted as strings).

    # Returns
        A list of available GPU devices.
    """
    global _LOCAL_DEVICES
    if _LOCAL_DEVICES is None:
        if _is_tf_1():
            devices = get_session().list_devices()
            _LOCAL_DEVICES = [x.name for x in devices]
        else:
            devices = tf.config.list_logical_devices()
            _LOCAL_DEVICES = [x.name for x in devices]
    return [x for x in _LOCAL_DEVICES if 'device:gpu' in x.lower()]

`

**Comment by gagolucasm** [comment]
Same problem here, AlphaWu solution works. I have created a pull request

**Comment by DavidGervasio** [comment]
I solve this by installing an older version

**Comment by amirsayonara** [comment]
> I solve this by installing an older version

which version of Keras is downgraded? and which version of Tensorflow?

**Comment by vgrankin1** [comment]
> > I solve this by installing an older version
> 
> which version of Keras is downgraded? and which version of Tensorflow?

Hello, I think better solution is an injection.
```

import tensorflow as tf
import keras.backend.tensorflow_backend as tfback
...ba bla
print("tf.__version__ is", tf.__version__)
print("tf.keras.__version__ is:", tf.keras.__version__)

def _get_available_gpus():
    """Get a list of available gpu devices (formatted as strings).

    # Returns
        A list of available GPU devices.
    """
    #global _LOCAL_DEVICES
    if tfback._LOCAL_DEVICES is None:
        devices = tf.config.list_logical_devices()
        tfback._LOCAL_DEVICES = [x.name for x in devices]
    return [x for x in tfback._LOCAL_DEVICES if 'device:gpu' in x.lower()]

tfback._get_available_gpus = _get_available_gpus
```
it is working fine for me, even in jupyter notebooks

**Comment by S4lm4no** [comment]
Had the same problem, fixed it with a simple argument
**
model.add(MaxPooling2D(2,2, dim_ordering='tf'))
**
dim_ordering ='th'
gave me the previous error, replacing it with 'tf' fixed it.

**Comment by hasniansaleem** [comment]
This code is working on my colab notebook

import tensorflow as tf
import keras.backend.tensorflow_backend as tfback
print("tf.__version__ is", tf.__version__)
print("tf.keras.__version__ is:", tf.keras.__version__)

def _get_available_gpus():
    """Get a list of available gpu devices (formatted as strings).

    # Returns
        A list of available GPU devices.
    """
    #global _LOCAL_DEVICES
    if tfback._LOCAL_DEVICES is None:
        devices = tf.config.list_logical_devices()
        tfback._LOCAL_DEVICES = [x.name for x in devices]
    return [x for x in tfback._LOCAL_DEVICES if 'device:gpu' in x.lower()]

tfback._get_available_gpus = _get_available_gpus

**Comment by JingCi-ZHu** [comment]
the problem has not solved when i train my net  in the colab
    504     if tfback._LOCAL_DEVICES is None:
    505         devices = tf.config.list_logical_devices()
--> 506         tfback._LOCAL_DEVICES = [x.name for x in devices]
    507     return [x for x in tfback._LOCAL_DEVICES if 'device:gpu' in x.lower()]
    508 

AttributeError: module 'tensorflow._api.v2.config' has no attribute 'experimental_list_devices'

**Comment by wissam-bouattou** [comment]
@JingCi-ZHu same for me , plz if you've found a solution can you share it with me ?

**Comment by nmodem2k** [comment]
what's the error in these?

fork11 = Convolution2D(nb_filters_1, nb_conv_init, nb_conv_init,  activation="relu")(init)
fork12 = Convolution2D(nb_filters_1, nb_conv_init, nb_conv_init, activation="relu")(init)

showing error::AttributeError: module 'tensorflow_core._api.v2.config' has no attribute 'experimental_list_device

**Comment by wissam-bouattou** [comment]
@nmodem2k i tried the solution which is in this link https://www.kaggle.com/vitost/kernel-keras-injection-sol might it helps u

**Comment by nmodem2k** [comment]
![0001](https://user-images.githubusercontent.com/51241731/81822435-b849fb80-9550-11ea-8597-86bd4c291f79.PNG)
I am getting this error.plz help

**Comment by wissam-bouattou** [comment]
@nmodem2k add those 2 lignes before the function
```
 import tensorflow as tf
import keras.backend.tensorflow_backend as tfback
```

**Comment by JingCi-ZHu** [comment]
do u solve it now ?

**Comment by JingCi-ZHu** [comment]
use tensorflow 2.1.0, it works for me

**Comment by JingCi-ZHu** [comment]
do you solve it now?

**Comment by wissam-bouattou** [comment]
@JingCi-ZHu for me it works  , i followed the instructions given in this website https://www.kaggle.com/vitost/kernel-keras-injection-sol

**Comment by nmodem2k** [comment]
@JingCi-ZHu  @wissam-bouattou  yeah it worked for me too

**Comment by dagger112** [comment]
> I solve this by installing an older version

i am having build problem with older version any suggestions?

**Comment by lwoog** [comment]
Use tf.keras instead of keras with tf 2.1.0

**Comment by qzylalala** [comment]
> list_logical_devices()

It occurs another ERROR：'LogicalDevice' object has no attribute 'lower'

**Comment by biswajit310** [comment]
> experimental_list_devices is deprecated in tf 2.1,use tf.config.list_logical_devices replaced.
> 
> `
> def _get_available_gpus():
> """Get a list of available gpu devices (formatted as strings).
> 
> ```
> # Returns
>     A list of available GPU devices.
> """
> global _LOCAL_DEVICES
> if _LOCAL_DEVICES is None:
>     if _is_tf_1():
>         devices = get_session().list_devices()
>         _LOCAL_DEVICES = [x.name for x in devices]
>     else:
>         devices = tf.config.list_logical_devices()
>         _LOCAL_DEVICES = [x.name for x in devices]
> return [x for x in _LOCAL_DEVICES if 'device:gpu' in x.lower()]
> ```
> 
> `

I am still getting the same error after using "tf.config.list_logical_device". I am running it on google colab. Plz help me.

**Comment by KYHyeon** [comment]
I solved this problem using `pip install -U sensorflow-gpu`.

**Comment by vidhigandhi94** [comment]
> > list_logical_devices()
> 
> It occurs another ERROR：'LogicalDevice' object has no attribute 'lower'

I am also facing the same issue!! Did anyone else find a solution for this?
