### ISSUE TITLE
Keras Error : Unknown entries in loss dictionary: ['ctc']. Only expected following keys: ['dense_1']

### ISSUE THREAD

**Issue by BITCS0479** [keras-team/keras#13685]
<em>I am new on Keras and I want to use CTC loss to compile my model. But it raised the error just
like what title says. Can anyone help me? The following is my code.
</em>  
This is my ctc loss:
`def ctc_lambda_func(args):
    y_pred, labels, input_length, label_length = args
    return K.ctc_batch_cost(labels, y_pred, input_length, label_length)`
This is my compiling code:
`model.compile(loss={'ctc': lambda y_true, y_pred: y_pred}, optimizer='Adam')`

**Comment by mrgloom** [comment]
You should create model before compile: 

```
    def ctc_lambda_func(args):
        y_pred, labels, input_length, label_length = args
        return K.ctc_batch_cost(labels, y_pred, input_length, label_length)

    loss_out = Lambda(
        ctc_lambda_func, output_shape=(1,),
        name='ctc')([out, labels, input_length, label_length])

    model = Model(inputs=[image, labels, input_length, label_length], outputs=loss_out)

    sgd = SGD(lr=0.02,
              decay=1e-6,
              momentum=0.9,
              nesterov=True)

    model.compile(loss={'ctc': lambda y_true, y_pred: y_pred}, optimizer=sgd)
```

**Comment by andrenatal** [comment]
I'm having the same error, but when trying to execute `multi_gpu_model` before `model.compile` in order to make the model be trained on multiple gpus. If I run this:

```
    def ctc_lambda_func(args):
        y_pred, labels, input_length, label_length = args
        return K.ctc_batch_cost(labels, y_pred, input_length, label_length)

    loss_out = Lambda(
        ctc_lambda_func, output_shape=(1,),
        name='ctc')([out, labels, input_length, label_length])

    model = Model(inputs=[image, labels, input_length, label_length], outputs=loss_out)

    sgd = SGD(lr=0.02,
              decay=1e-6,
              momentum=0.9,
              nesterov=True)
    model = multi_gpu_model(model, gpus=2)
    model.compile(loss={'ctc': lambda y_true, y_pred: y_pred}, optimizer=sgd)

```

I then get this error:
`ValueError: Unknown entry in loss dictionary: "ctc". Only expected the following keys: ['concatenate_1']`
