### ISSUE TITLE
What does keras mean?

### ISSUE THREAD

**Issue by zzj0402** [keras-team/keras#13707]
Why calls this library keras? 

> Keras (κέρας) means horn in Greek. Kẽras means sorcery in Lithuanian

**Comment by nbro** [comment]
@zzj0402 So you opened this issue to answer your own question? This is actually answered in the [README file of the Keras' repo](https://github.com/keras-team/keras).

**Comment by zzj0402** [comment]
> @zzj0402 So you opened this issue to answer your own question? This is actually answered in the [README file of the Keras' repo](https://github.com/keras-team/keras).

If you don't know enough, then better leave it to the professional

**Comment by nbro** [comment]
> > @zzj0402 So you opened this issue to answer your own question? This is actually answered in the [README file of the Keras' repo](https://github.com/keras-team/keras).
> 
> If you don't know enough, then better leave it to the professional

What are you talking about?

**Comment by zzj0402** [comment]
> > > @zzj0402 So you opened this issue to answer your own question? This is actually answered in the [README file of the Keras' repo](https://github.com/keras-team/keras).
> > 
> > 
> > If you don't know enough, then better leave it to the professional
> 
> What are you talking about?

I am talking about you are being ignorant.

**Comment by nbro** [comment]
> > > > @zzj0402 So you opened this issue to answer your own question? This is actually answered in the [README file of the Keras' repo](https://github.com/keras-team/keras).
> > > 
> > > 
> > > If you don't know enough, then better leave it to the professional
> > 
> > 
> > What are you talking about?
> 
> I am talking about you are being ignorant.

@zzj0402 This is not the place to unburden yourself. Literally, this information can easily be found on the web with a simple search. I will not continue this useless discussion. I recommend you delete your comments.

**Comment by zzj0402** [comment]
> > > > > @zzj0402 So you opened this issue to answer your own question? This is actually answered in the [README file of the Keras' repo](https://github.com/keras-team/keras).
> > > > 
> > > > 
> > > > If you don't know enough, then better leave it to the professional
> > > 
> > > 
> > > What are you talking about?
> > 
> > 
> > I am talking about you are being ignorant.
> 
> @zzj0402 This is not the place to unburden yourself. Literally, this information can easily be found on the web with a simple search. I will not continue this useless discussion. I recommend you delete your comments.

I recommend you just leave me alone.

**Comment by karanjakhar** [comment]
keras is the best. :)

**Comment by PARKJUHONG123** [comment]
Hi, this link may helps you
https://github.com/keras-team/keras#why-this-name-keras
