### ISSUE TITLE
Reshaping the output from one model to pass to the input of another

### ISSUE THREAD

**Issue by grand3110** [keras-team/keras#13700]
I'm trying to pass the output of a CNN model as an input to LSTM. 
I'm currently working with videos. The array of each frame of the video is passed to a CNN model and the output is a vector array.  
I want to divide the output of CNN into a sequence of size 9 and pass it as an input to LSTM. I can't seem to figure it out how to divide the output of CNN into a sequence of size 9. I tried to use reshape but it didn't work.

Here's my current cnn model:

```
inp = Input(shape=(360,640,1))
norm_inp = BatchNormalization()(inp)
img_1 = Convolution2D(4, kernel_size=2, activation=activations.relu)(norm_inp)
img_1 = MaxPooling2D(pool_size=(3, 3))(img_1)
img_1 = Dropout(rate=0.2)(img_1)
img_1 = Convolution2D(16, kernel_size=3, activation=activations.relu)(img_1)
img_1 = MaxPooling2D(pool_size=(4, 4))(img_1)
img_1 = Dropout(rate=0.2)(img_1)
img_1 = Convolution2D(4, kernel_size=4, activation=activations.relu)(img_1)
img_1 = MaxPooling2D(pool_size=(4, 4))(img_1)
img_1 = Dropout(rate=0.2)(img_1)
img_1 = Flatten()(img_1)
dense_1 = BatchNormalization()(Dense(16, activation=activations.relu)(img_1))
# dense_1 = Dense(2, activation='softmax')(dense_1)
cnn2 = models.Model(inputs=inp, outputs=dense_1)
cnn2.summary()
```

I want the input to input to LSTM to be of shape (9,16)

Can someone help me with this please?

**Comment by karanjakhar** [comment]
Yes, you can do that easily. If you want to get this in detail then please check the implementation of the encoder-decoder architecture. You will understand everything clearly.
