### ISSUE TITLE
ValueError: Error when checking input: expected input_1 to have 5 dimensions, but got array with shape (1221, 50, 50, 1)

### ISSUE THREAD

**Issue by rustombhesania** [keras-team/keras#13709]
<em>Please make sure that this is a Bug or a Feature Request and provide all applicable information asked by the template.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.</em>  

**System information**  
- Have I written custom code (as opposed to using example directory):  
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  
- TensorFlow backend (yes / no):  
- TensorFlow version:  
- Keras version:  
- Python version:  
- CUDA/cuDNN version:  
- GPU model and memory:  

You can obtain the TensorFlow version with:  
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"  
You can obtain the Keras version with:  
python -c 'import keras as k; print(k.__version__)'  

**Describe the current behavior**  

**Describe the expected behavior**  

**Code to reproduce the issue**  
Provide a reproducible test case that is the bare minimum necessary to generate the problem.  

**Other info / logs**  
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by rustombhesania** [comment]
im trying to run a model with xtrain=(1221,50,50,1)
at the time of model.fit its showing this error

ValueError: Error when checking input: expected input_1 to have 5 dimensions, but got array with shape (1221, 50, 50, 1)


im using these functions:

model.compile(loss=categorical_crossentropy, optimizer=Adadelta(lr=0.8), metrics=['acc'])
model.fit(x=ZZ, y=yyy, batch_size=128, epochs=1, validation_split=0.2)



where im getting wrong idk

**Comment by abhipn** [comment]
The input layer of your network is expecting a 5 dimensional data but as you have mentioned your x_train has 4 dims. Check the input layer.

I think this is better suited to be asked at stackoverflow.

**Comment by rustombhesania** [comment]
@abhipn thnx i will post this in stack 

thank you for your time

**Comment by karanjakhar** [comment]
Your input layer shape should = (51,51,1).

**Comment by rustombhesania** [comment]
@karanjakhar 
Yes there was a error while taking input (it was not scanning the number of frames) 
It's working now

> Your input layer shape should = (51,51,1).
