### ISSUE TITLE
keras freezes during training a model with multiple output layers.

### ISSUE THREAD

**Issue by ZeRoss0000** [keras-team/keras#13703]
<em>Training a model that have a lot of outputs causes my keras to freeze, using 'use_multiprocessing=True' in fit it become freezes less(probably), but still freezes, i believe there is a problem in keras, i train it on data of size 2048 for 1 epoch for multiple times (reinforcement learning), it freezes randomly it freezes after few times of training but sometimes it takes thousands </em>  

**System information**  
- Have I written custom code (as opposed to using example directory):  yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Windows 10
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  2.0/2.1
- Keras version:  2.3.0
- Python version:  3.7.2
- CUDA/cuDNN version:  CUDA 10.1/cuDNN 7.6.4 (tested also with CUDA 10)
- GPU model and memory:  GTX 1070 8 gb memory

**Describe the current behavior**  
My model freeze randomly during training. when i use a model with alot of multiple layers (9 in my case)

**Describe the expected behavior**  
it don't freeze ?

**Code to reproduce the issue**  
```
	dims = [8,64,150,80,30,9]
	input_layer = Input(shape=(dims[0],))

	hidden = Dense(dims[1],activation='relu')(input_layer)
	hidden = Dense(dims[2],activation='relu')(hidden)
	hidden = Dense(dims[3],activation='relu')(hidden)

	policy = []
	for i in range(dims[-1]):
		hiddenl = Dense(dims[-2],activation='relu')(hidden)
		policy.append( Dense(n_atoms,activation='softmax')(hiddenl) )

	rmodel = Model(inputs=input_layer, outputs=policy)
	rmodel.compile(loss=['categorical_crossentropy']*9, optimizer=Adam(lr=lr,decay=decay))
	return rmodel
```

**Other info / logs**  
`can't provide any other infos python don't display any errors`

**Comment by sushreebarsa** [comment]
@ZeRoss0000 It looks like you are using an older Version of Tensorflow. Many bugs have been fixed in the latest version. Can you please execute your code using Latest Version 2.4.1 or 2.5 and let us know if the issue still persists? Thanks!

**Comment by sushreebarsa** [comment]
Closing this issue due to lack of recent activity & assuming this issue as resolved .Please feel free to reopen if you still have concern.Thanks!
