### ISSUE TITLE
Keras model with relative path not loading with Flask.

### ISSUE THREAD

**Issue by Tjieco** [keras-team/keras#13718]
Hi, I have an issue that's closely linked to #7825 
I am trying to load a model by using relative path runtime during a Flask request.
I can load the file without a relative path, and the relative path works when loading it by running the script directly, but it won't be able to find the location of the file when loading it in Flask using the relative path.

The following works:
` load_model(r'C:\Users\<<more path>>\models\Model.h5')`

The following only works outside of a Flask request:
` load_model('./models/Model.h5')`

Does anyone know how to solve this issue, or if Keras/Flask is working on a solution?

**System information**  
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Windows 10 v1809
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  2.2.4
- Keras version:  2.3.1
- Python version:  3.7.5

**Comment by karanjakhar** [comment]
Both works for me. I don't think there is any problem related to keras model. Please check other things.

**Comment by kumariko** [comment]
@Tjieco We are checking to see if you still need help on this issue. We recommend that you upgrade to 2.6 which is latest stable version of TF and let us know if the issue still persists in newer versions. If it is resolved then please feel free to move this issue to close status.Thanks!
