### ISSUE TITLE
Getting GRU gate activations values

### ISSUE THREAD

**Issue by MickHardins** [keras-team/keras#13715]
Hello, I was wondering if there's a way to get GRU's gate values at each timestep.
Namely z, and r as defined in recurrent.py (lines 1434-1435)

I already tried the silly approach: modify recurrent.py and printing the tensors, but it doesn't work. 
Even if I'm using TF 2.0 and eager execution is enabled, can't access the tensor's value.

Do you have some suggestions to help me accomplish this?
Is implementing a custom GRUCell the only way to do this?

Thanks!

**Comment by kumariko** [comment]
@MickHardins It looks like you are using an older Version of Tensorflow. Many bugs have been fixed in the latest version. Could you please execute your code using Latest Version 2.6 and let us know if the issue still persists? Thanks!
