### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/.keras/datasets/cifar-100-python/train'

### ISSUE THREAD

**Issue by thebeancounter** [keras-team/keras#13724]
When I import and load cifar 100 dataset, 
every few thousands of times I do that, 
that everything is OK 
I get a few error like this one 

> FileNotFoundError: [Errno 2] No such file or directory: '/tmp/.keras/datasets/cifar-100-python/train'

My script works about 99% of the time until it does not. 
Does it make any sense?

**Comment by kumariko** [comment]
@thebeancounter Could you please let us know if you still need help on this ? if it is resolved then please feel free to move this issue to close status ? Thanks!
