### ISSUE TITLE
Unexpected behaviour when evaluating book example 6.3 (very different results)

### ISSUE THREAD

**Issue by the-drunk-coder** [keras-team/keras#13733]
**System information**  
- Have I written custom code (as opposed to using example directory):  used example, only changed data retrieval
- OS Platform and Distribution: 'Linux-4.14.137+-x86_64-with-Ubuntu-18.04-bionic'  
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  '1.15.0'
- Keras version:  '2.2.5'
- Python version:  3.6
- CUDA/cuDNN version:  ?
- GPU model and memory:  ?

I've been running the notebooks in the Google Colab environment.

**Describe the current behavior** 
1.) The plots and results differ vastly from the expectation (that is, the results in the original example)
2.) The results differ vastly whether you use a GPU or CPU runtime (on Colab)

**Describe the expected behavior**  
1.) Results should match the original example/book.
2.) Results shouldn't differ in different environments (at least not to that degree)

**Code to reproduce the issue**  
Open the book example (https://github.com/fchollet/deep-learning-with-python-notebooks/blob/master/6.3-advanced-usage-of-recurrent-neural-networks.ipynb) on Google Colab
and evaluate. 

**Other info / logs**  
A similar issue exists in the examples repo: https://github.com/fchollet/deep-learning-with-python-notebooks/issues/127

**Comment by Saduf2019** [comment]
@the-drunk-coder 
We see that you are using old version of tensorflow which is not actively supported now, please verify on 2.x and open a new issue in case you face any errors, hence moving this to closed status.

**Comment by fangxuehouwuming** [comment]
> @the-drunk-coder We see that you are using old version of tensorflow which is not actively supported now, please verify on 2.x and open a new issue in case you face any errors, hence moving this to closed status.

Hi, I met this problem too, even though my version is:
tensorflow                    2.9.1
keras                            2.9.0
