### ISSUE TITLE
KerasClassifier does not accept epochs parameter

### ISSUE THREAD

**Issue by mrtj** [keras-team/keras#13749]
**System information**  
- Have I written custom code (as opposed to using example directory):  yes
- OS Platform and Distribution:  Linux Ubuntu 18.04
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  2.0.0
- Keras version:  2.2.4-tf
- Python version:  3.7.6
- CUDA/cuDNN version:  
- GPU model and memory:  

**Describe the current behavior**  
When I create a `KerasClassifier` object from the scikit_learn wrappers module, passing the `epochs` parameter throws the following exception:

    ValueError: epochs is not a legal parameter

**Describe the expected behavior**  

No exception is thrown and I can specify the number of epochs for the training.

**Code to reproduce the issue**  
Provide a reproducible test case that is the bare minimum necessary to generate the problem.  
```python
from keras.wrappers.scikit_learn import KerasClassifier
from keras.models import Sequential
estimator = KerasClassifier(build_fn=lambda:Sequential(), epochs=100)
```
**Other info / logs**  
Traceback:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-22-3a06930afa18> in <module>
      7 folds = 4
      8 
----> 9 estimator = KerasClassifier(build_fn=create_baseline, epochs=100)
     10 # kfold = StratifiedKFold(n_splits=10, shuffle=True)
     11 # results = cross_val_score(estimator, X, encoded_Y, cv=kfold)

~/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/wrappers/scikit_learn.py in __init__(self, build_fn, **sk_params)
     75     self.build_fn = build_fn
     76     self.sk_params = sk_params
---> 77     self.check_params(sk_params)
     78 
     79   def check_params(self, params):

~/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/wrappers/scikit_learn.py in check_params(self, params)
    104       else:
    105         if params_name != 'nb_epoch':
--> 106           raise ValueError('{} is not a legal parameter'.format(params_name))
    107 
    108   def get_params(self, **params):  # pylint: disable=unused-argument

ValueError: epochs is not a legal parameter
```

**Comment by smehdia** [comment]
I tried your code (keras==2.2.4, tensorflow-gpu==1.12.0, sklearn==0.20.3) , it works fine for me. Please make sure that you have the updated version of sklearn.

**Comment by mrtj** [comment]
Hello, I use keras==2.2.4, tensorflow=2.0.0 (**!!!**) and sklearn=0.22.1.

**Comment by Jefffish09** [comment]
I met same problem! How to solve?

**Comment by DavidKatz-il** [comment]
It looks like you are passing a function that doesn't have `epochs` as an argument.
The [check_params](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/wrappers/scikit_learn.py#L79-L106) function checks that the function you want to call has a given argument (`epochs` in your case).
Take a look at [this issue on mlflow](https://github.com/mlflow/mlflow/issues/3402).

**Comment by DavidKatz-il** [comment]
When running your code with:
```
tensorflow                2.2.0 
keras                     2.4.3 
scikit-learn              0.23.2 
```
I didn't get the error.

**Comment by AmanieOxana** [comment]
scikit-learn              0.24.1
and still same issue

**Comment by sushreebarsa** [comment]
I tried to run the code on colab with TF v2.5 and didn't see the error reported,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/82add070a3fb3d578e71b2b8bc9406f8/untitled329.ipynb#scrollTo=4wVKtjYhKX5E) .Let us know if this issue is resolved for you .Thanks!

**Comment by sushreebarsa** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
