### ISSUE TITLE
Cannot import keras even after installation

### ISSUE THREAD

**Issue by shivam-soniii** [keras-team/keras#13748]
Hi All, 
I'm new in ML field and I just came across Tensorflow and Keras. I successfully installed both but still facing an error while importing Keras. Please find related info below:

System information:
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Windows 10 64-bit
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  2.1.0
- Keras version:  2.3.1
- Python version:  3.7.2, 64-bit distribution

I've installed TensorFlow and Keras but still, when I'm trying to import Keras in jupyter notebook it is showing error as ModuleNotFoundError: No module named 'keras'.

I run the below command in cmd to verify the installation;
python -c "import keras as k; print(k.___ version ___)"
and got this:
Using TensorFlow backend.
2020-02-05 15:26:31.415156: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-02-05 15:26:31.423977: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2.3.1

Code to reproduce the issue:
from keras.models import Sequential

Output:
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-9-1543d14058f5> in <module>
      1 # Importing the Keras libraries and packages
----> 2 from keras.models import Sequential

ModuleNotFoundError: No module named 'keras'

Please help me with this.

**Comment by rajat-1994** [comment]
Are you using Anaconda? if yes, how did you install Keras using pip or conda?

**Comment by samsony12** [comment]
> Are you using Anaconda? if yes, how did you install Keras using pip or conda?

I've anaconda installed in my system but I installed Keras using pip.

**Comment by rajat-1994** [comment]
Install using conda

**Comment by mzaveri13** [comment]
I used conda to install. It still gives modulenotfound error

**Comment by cuspime** [comment]
How did you solve this issue??

**Comment by sushreebarsa** [comment]
@shivam-soniii Could you please try on latest stable version of tf 2.5 or 2.4.1 and let us know if this is still an issue.I tried the same and didn't face the error reported .Thanks!

**Comment by sushreebarsa** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by Shariq627** [comment]
@sushreebarsa , need more information on this since I am facing this issue recently. It would be of immense help, since i have tried multiple things left n right.

**Comment by jwohlfert** [comment]
Same here. I'm on Windows 10, and I installed tensorflow with conda.
