### ISSUE TITLE
Error in importing kulc.attention import ExternalAttentionRNNWrapper

### ISSUE THREAD

**Issue by alokssingh** [keras-team/keras#13756]
**System information**  
- Have I written custom code (as opposed to using example directory):   Yes 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04) : Ubuntu 16.04   
- TensorFlow backend (yes / no):   yes
- TensorFlow version:  tensorflow-gpu   1.14.0
- Keras version:  2.3.1 
- Python version:  3
- CUDA/cuDNN version: 10.1  
- GPU model and memory:   Quadro P2000 5GB

**Describe the current behavior**  
File "train.py", line 155, in <module>
    training_model, inference_model, initial_state_inference_model = create_model(le._vocabulary_size, EMBEDDING_SIZE, None, 14*14, 512)
  File "/home/alok/new-way-video/model.py", line 36, in create_model
    attented_encoder = ExternalAttentionRNNWrapper(encoder, return_attention=True)
  File "/home/alok/myenv/lib/python3.6/site-packages/kulc/attention.py", line 516, in __init__
    super(ExternalAttentionRNNWrapper, self).__init__(layer, **kwargs)
  File "/home/alok/myenv/lib/python3.6/site-packages/tensorflow/python/keras/layers/wrappers.py", line 51, in __init__
    assert isinstance(layer, Layer)
AssertionError

My code is 
 encoder = LSTM(embedding_size, return_sequences=True, return_state=False, recurrent_dropout=0.1)
    attented_encoder = ExternalAttentionRNNWrapper(encoder, return_attention=True)
Please help me out I have searched everywhere and didn't got any help 
Thank you

**Comment by Saduf2019** [comment]
@alokssingh 
We see that you are using old version of tensorflow which is not actively supported now, please verify on 2.x and open a new issue in case you face any errors, hence moving this to closed status.
