### ISSUE TITLE
K.eval() get High-dimensional matrix ouput spend too much CPU resource when using tensorflow as backend

### ISSUE THREAD

**Issue by shiningrain** [keras-team/keras#13758]
**System information**  
- Have I written custom code (as opposed to using example directory):  Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Linux Ubuntu 18.04
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  1.14.0-cpu
- Keras version:  2.3.1
- Python version:  3.6.9
- CUDA/cuDNN version:  no
- GPU model and memory:  TITAN V  

**Describe the current behavior**  
Whe I need to use _keras.backend.eval()_ to get the 6-dimensional matrix initialized by _keras.initializers.TruncatedNormal()_. Cntk only takes about 11 seconds in the eval part, and the CPU will use 100% in the entire process. However Tensoflow takes about 120 seconds in the eval part, and the CPU uses about 3100%,. Even if the data matrix is reduced to 5 dimensions (you can use the annotated 'list' in 'initial_single'), tensorflow also needs to use about 2000% CPU. I think this should be regarded as a efficiency problem of tensorflow backend.
In some calculations, CPU under tensorflow backend will be spent **30 times** than the cntk backend.

**Code to reproduce the issue**  
The code is shown below:
```
import numpy as np
import copy
import random
import datetime
import os
import importlib
from keras import initializers
from keras import backend as K
import tensorflow as tf
import cntk
import time


pop_list=[]
loss_list=[]
maxloss=10000
pop_amount=20
epoch=5
np.random.seed()


def set_keras_backend(backend='tensorflow'):
    if K.backend() != backend:
        os.environ['KERAS_BACKEND'] = backend
        importlib.reload(K.load_backend)
        importlib.reload(K)
        assert K.backend() == backend


def check_parameter_list(parameter_list):
    parameter_list1=np.array(parameter_list[:3])
    x = np.argwhere(np.isinf(parameter_list1))
    y = np.argwhere(np.isnan(parameter_list1))
    if x.shape[0] >0 or y.shape[0] >0:
        return 'Wrong'
    else: return 'OK'

def initial_single():
    mean = np.random.rand()
    std = np.random.rand()
    seed = np.random.rand()
    list=[83,62,31,14,53,38]
    #list=[83,62,31,14,53]
    shape=tuple(list)
    parameter = [mean, std, seed, shape]
    for each in range(3):
        parameter[each] *= np.random.randint(low=0, high=1000)
    parameter[2] = int(parameter[2])
    return parameter


def initialzero(pop_amount):
    global pop_list
    for pops in range(pop_amount):
        pop_list.append(initial_single())
    print('initialzero succeed')

#paprameters=[mean,std,seed,shape,dtype]
def runner(parameters):
    global loss_list,maxloss
    if (check_parameter_list(parameters)=='OK'):
        init=initializers.TruncatedNormal(mean=parameters[0], stddev=parameters[1],seed=parameters[2])
        K.clear_session()
        variable = K.variable(init(parameters[3]))#,dtype=parameters[4])
        time_start=time.time()
        output = K.eval(variable)
        time_end=time.time()
        print("used:",str(time_end-time_start))


for echo in range(epoch):
    print(echo,'--start')
    initialzero(pop_amount)
    loss_list=[]
    set_keras_backend()
    #set_keras_backend('cntk')
    for pa in range(len(pop_list)):
        tmp=runner(pop_list[pa])
```

**Other info / logs**  
Running this code with default backend(tensorflow), you may get something like this:

_2020-02-09 17:24:10.644635: W tensorflow/core/framework/allocator.cc:107] Allocation of 17991980384 exceeds 10% of system memory.
used: 122.11114597320557_ 
![image](https://user-images.githubusercontent.com/46860123/74100248-afb7e280-4b67-11ea-97db-cd208da9cc09.png)

CPU is used a lot, and eval() spends about 2 min to get result.

And Runing with cntk backend, you may get this:

_UserWarning: CNTK backend warning: GPU is not detected. CNTK's CPU version is not fully optimized,please run with GPU to get better performance.
  'CNTK backend warning: GPU is not detected. ' used: 11.376193046569824_ 
![image](https://user-images.githubusercontent.com/46860123/74100251-bc3c3b00-4b67-11ea-9a68-197dc0f6aa4e.png)
'zxy' is the running code. These can show the cpu efficiency differences on different backends

**Comment by Saduf2019** [comment]
@shiningrain 
We see that you are using old version of tensorflow which is not actively supported now, please verify on 2.x and open a new issue in case you face any errors, hence moving this to closed status.
