### ISSUE TITLE
InvalidArgumentError: You must feed a value for placeholder tensor 'input_rgb' with dtype float and shape [?,16,224,224,3]

### ISSUE THREAD

**Issue by sudonto** [keras-team/keras#13761]
<em>Please make sure that this is a Bug or a Feature Request and provide all applicable information asked by the template.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.</em>  

**System information**  
- Have I written custom code (as opposed to using example directory):  No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Windows 10 and Ubuntu 16.04.5 LTS
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  tensorflow-gpu version 1.12.0
- Keras version:  2.2.4
- Python version:  3.5.2
- CUDA/cuDNN version:  9.0.176/64.7
- GPU model and memory:  GTX 1080Ti 8GB (Win);  Quadro P6000 24GB (Ubuntu)

You can obtain the TensorFlow version with:  
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"  
You can obtain the Keras version with:  
python -c 'import keras as k; print(k.__version__)'  

**Describe the current behavior**
I run code below and  an error occured:  `InvalidArgumentError: You must feed a value for placeholder tensor 'input_rgb' with dtype float and shape [?,16,224,224,3]`.
But, if I rename all `BatchNormalization `layer, no error happen.

**Describe the expected behavior**  
I want to successfully build the network made using model subclassing. If I use FunctionalAPI, no error occured.

**Code to reproduce the issue**  
`
from keras.optimizers import Adam
from keras.models import Model
from keras.layers import Activation
from keras.layers import Conv3D
from keras.layers import Dropout
from keras.layers import Reshape

from keras.layers import Lambda
from keras import backend as K

import numpy as np

from i3d_inception import Inception_Inflated3d        #@UnresolvedImport

class I3D_Model(Model):
    
    def __init__(self, n_classes):
        super(I3D_Model, self).__init__()
        
        self.i3d = Inception_Inflated3d(include_top=False,
                                        weights=None,
                                        input_tensor=K.placeholder(shape=(None, 16, 224, 224, 3), ndim=5, name='input_rgb'),
                                        input_shape=(16, 224, 224, 3),
                                        classes=n_classes)
        
        #for layer in self.i3d.layers:
        #    if 'normalization.BatchNormalization' in str(layer):
        #        layer.name = layer.name + '_rgb'
        
        self.n_classes = n_classes
        
        self.define_layers()
        
    def compute_output_shape(self, input_shape):

        output_shape_pred = (input_shape[0], self.n_classes)
        
        return output_shape_pred
        
    def call(self, x):
        x = self.i3d(x)
        x = self.do(x)
        x = self.conv(x)
        x = self.reshape(x)
        x = self.mean(x)
        pred = self.smax(x)
        
        return pred
    
    def define_layers(self):
        
        " Dropout "
        layer_name = 'dropout_top'
        layer = Dropout(rate=0.5, name=layer_name)
        setattr(self, 'do', layer)
        
        " Conv3D "
        layer_name = 'Conv3d_6a_1x1_top'
        layer = Conv3D(self.n_classes, (1, 1, 1),
                       strides=(1, 1, 1),
                       padding='same',
                       use_bias=True,
                       name=layer_name)
        setattr(self, 'conv', layer)
        
        " Reshape "
        layer_name = 'reshape_top'
        layer = Reshape((1, self.n_classes), name=layer_name)
        setattr(self, 'reshape', layer)
        
        " Lambda "
        layer_name = 'lambda_top'
        layer = Lambda(function=lambda x: K.mean(x, axis=1, keepdims=False),
                       output_shape=lambda s: (s[0], s[2]), name=layer_name)
        setattr(self, 'mean', layer)
        
        " Softmax "
        layer_name = 'softmax_top'
        layer = Activation(activation='softmax', name=layer_name)
        setattr(self, 'smax', layer)
        
    def compile_model(self):
        
        optimizer = Adam(lr=1e-4, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=0.0)
        metrics=['accuracy','top_k_categorical_accuracy']
        losses='categorical_crossentropy'       
        
        self.compile(optimizer=optimizer, metrics=metrics, loss=losses)
    
    def build_attention_network(self, seq, dim, ch):
        
        sample_sequence = np.random.rand(1, seq, dim, dim, ch).astype(np.float32)
        y = np.random.rand(1, self.n_classes).astype(np.int)           
        
        self.fit(x=sample_sequence, y=y, epochs=1, verbose=0)
        

def train():
    print('Create network...')
    model = I3D_Model(n_classes = 200)
    model.compile_model()
    print('Build network...')
    model.build_attention_network(16, 224, 3)
    
    print('Done!\n')
    
    model.summary()

if __name__ == '__main__':
    train()
`  

- You can get file `i3d_inception.py` from [here](https://github.com/dlpbc/keras-kinetics-i3d/blob/master/i3d_inception.py)
- This error happen on both Windows 10 and Ubuntu 16.04

**Other info / logs**  
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.  
`
Traceback (most recent call last):
  File "C:\eclipse\eclipse_48\plugins\org.python.pydev.core_7.1.0.201902031515\pysrc\pydevd.py", line 2225, in <module>
    main()
  File "C:\eclipse\eclipse_48\plugins\org.python.pydev.core_7.1.0.201902031515\pysrc\pydevd.py", line 2218, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\eclipse\eclipse_48\plugins\org.python.pydev.core_7.1.0.201902031515\pysrc\pydevd.py", line 1560, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "C:\eclipse\eclipse_48\plugins\org.python.pydev.core_7.1.0.201902031515\pysrc\pydevd.py", line 1567, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\eclipse\eclipse_48\plugins\org.python.pydev.core_7.1.0.201902031515\pysrc\_pydev_imps\_pydev_execfile.py", line 25, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:\workspace\ActivityClassification\temporer\tes.py", line 110, in <module>
    train()
  File "D:\workspace\ActivityClassification\temporer\tes.py", line 103, in train
    model.build_attention_network(16, 224, 3)
  File "D:\workspace\ActivityClassification\temporer\tes.py", line 95, in build_attention_network
    self.fit(x=sample_sequence, y=y, epochs=1, verbose=0)
  File "C:\Users\stud\Envs\krtf\lib\site-packages\keras\engine\training.py", line 1039, in fit
    validation_steps=validation_steps)
  File "C:\Users\stud\Envs\krtf\lib\site-packages\keras\engine\training_arrays.py", line 199, in fit_loop
    outs = f(ins_batch)
  File "C:\Users\stud\Envs\krtf\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "C:\Users\stud\Envs\krtf\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "C:\Users\stud\Envs\krtf\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
    run_metadata_ptr)
  File "C:\Users\stud\Envs\krtf\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'input_rgb' with dtype float and shape [?,16,224,224,3]
	 [[{{node input_rgb}} = Placeholder[dtype=DT_FLOAT, shape=[?,16,224,224,3], _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
	 [[{{node metrics/acc/ArgMax/_2899}} = _HostRecv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_13438_metrics/acc/ArgMax", tensor_type=DT_INT64, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

`

**Comment by Saduf2019** [comment]
@sudonto 

We see that you are using old version of tensorflow which is not actively supported now, please verify on 2.x and open a new issue in case you face any errors, hence moving this to closed status.
