### ISSUE TITLE
MaxPooling2D input format and shape

### ISSUE THREAD

**Issue by katoabc123** [keras-team/keras#13768]
I would like to test the MaxPooling2D layer for understanding how it work.
Here is the problem:
I test the input np.array and get the unexpected result:

Here is my testing code:
Input=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
Input=Input.reshape(1,4,4,2)
model = Sequential([
    MaxPooling2D(pool_size=(2, 2),padding="same"),
    ])
print(model.predict(Input)[0])

The output is:
[[[11. 12.]
  [15. 16.]]

 [[11. 12.]
  [15. 16.]]]

I expect the result should be :

 [[[6. 8.]
  [14. 16.]]

 [[6. 8.]
  [14. 16.]]]

What should I change the code If I want my expected result?

**Comment by thomas-schillaci** [comment]
Hello @katoabc123 ,

So, what happens you you reshape your input tensor?
You get the following:

[[[[ 1,  2],
  [ 3,  4],
  [ 5,  6],
  [ 7,  8]],
 [[ 9, 10],
  [11, 12],
  [13, 14],
  [15, 16]],
 [[ 1,  2],
  [ 3,  4],
  [ 5,  6],
  [ 7,  8]],
 [[ 9, 10],
  [11, 12],
  [13, 14],
  [15, 16]]]]


As Keras considers by default that the shape's structure is (width, height, channels), we want to extract the columns to get two matrices of shape (4, 4):

`Input[:,:,:,0]`

[[[ 1,  3,  5,  7],
 [ 9, 11, 13, 15],
 [ 1,  3,  5,  7],
 [ 9, 11, 13, 15]]]

`Input[:,:,:,1]`

[[[ 2,  4,  6,  8],
 [10, 12, 14, 16],
 [ 2,  4,  6,  8],
 [10, 12, 14, 16]]]

That's better, now, why do we get this output?
The MaxPooling2D layer starts by finding the max of the following upper left corner:

[[1, 9],
 [3, 11]]

Which is 11. Then it does the same for the second channel, which gives 12.
This explains the first line of your output.

Then, the kernel is moved from two columns, which gives you the following matrix:

[[5, 7],
 [3, 15]]

The max is 15, for the second channel, you get 16.

Then your kernel goes to the lower left corner etc.

**Comment by katoabc123** [comment]
Thank you @thomas-schillaci ,
I finally understand what is happening in the max2d.
