### ISSUE TITLE
Batch Normalization Doesn't work after adding a new axis to tensor using Reshape layer

### ISSUE THREAD

**Issue by istiaq28** [keras-team/keras#13760]
**System information**  
- Have I written custom code (as opposed to using example directory):  No
- OS Platform and Distribution : Linux Ubuntu 18.04 
- TensorFlow backend (yes / no): YES 
- TensorFlow version:  1.13.1
- Keras version:  2.2.4
- Python version:  3.7.4
- CUDA/cuDNN version:  10.0.130 / 7.4
- GPU model and memory:  TITAN Xp, 12GB

**The situation**  
Here is what my goal is. I want to generate  a signal with 26 channels of length 250 (say) from a 1D signal using Conv1D and then add an axis (i.e expand_dims ). So, after Conv1D layer the output will be of shape (Batch_size, 250, 26) and after a Reshape layer from keras i will make it (Batch_size, 250, 26, 1), which can be treated like a gray image of size (26) with 1 channel. 
But after passing it through the Reshape layer the Batch_normalization layer gives me and error.
Here is the error it shows **ValueError: An operation has `None` for gradient. Please make sure that all of your ops have a gradient defined (i.e. are differentiable). Common ops without gradient: K.argmax, K.round, K.eval.**
If I don't use batch_normalization layer the model works fine. But as we know it's hard to train a deep network without batch norm. 
But if I don't use the Reshape layer and use the (Batch_size,250,26) output and use Conv1D layers later with Batch_normalization layer , it works fine. Also if I use the Reshape layer without adding new axis it works fine. It only gives the error when I add new axis to the tensor. 

**Code to reproduce the issue**  
def Network(eps = 0.000001, bn_momentum = 0.99,l2_reg=0.001):    
    input = Input(shape=(2500, 1))
    t = Conv1D(26, kernel_size = 5,padding='same',kernel_regularizer=l2(l2_reg))
    t = BatchNormalization(epsilon=eps, momentum=bn_momentum, axis=-1)(t)
    t = Reshape(target_shape=(-1,26,1))(t)
    t = Conv2D(26, kernel_size=5,
                kernel_initializer=initializers.he_normal(seed=1),
                padding='valid',
                use_bias=True,
                kernel_constraint=max_norm(10000),
                trainable=trainable,
                kernel_regularizer=l2(l2_reg))(t)
    t = BatchNormalization(epsilon=eps, axis=-1)(t)
    t = Activation(activation_function)(t)
    t = Dropout(rate=dropout_rate, seed=random_seed)(t) 
    t = Flatten()(t)
    t = Dense(20)
    t = Dense(2)
    opt = Adam(lr=.001,decay=.001,epsilon=eps)
    model = Model(inputs=input, outputs=t)
    model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['accuracy'])
   return model

Traceback (most recent call last):
  File "train_layer_mfcc.py", line 674, in <module>
    initial_epoch=initial_epoch,
  File "/home/mhealthra2/anaconda3/envs/tensor/lib/python3.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/mhealthra2/anaconda3/envs/tensor/lib/python3.7/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/mhealthra2/anaconda3/envs/tensor/lib/python3.7/site-packages/keras/engine/training_generator.py", line 94, in fit_generator
    callbacks.set_model(callback_model)
  File "/home/mhealthra2/anaconda3/envs/tensor/lib/python3.7/site-packages/keras/callbacks.py", line 54, in set_model
    callback.set_model(model)
  File "/media/mhealthra2/Data/heart_sound/Adversarial-Heart-Sound-Classification/codes/CustomTensorBoard.py", line 159, in set_model
    weight)
  File "/home/mhealthra2/anaconda3/envs/tensor/lib/python3.7/site-packages/keras/optimizers.py", line 91, in get_gradients
    raise ValueError('An operation has `None` for gradient. '
ValueError: An operation has `None` for gradient. Please make sure that all of your ops have a gradient defined (i.e. are differentiable). Common ops without gradient: K.argmax, K.round, K.eval.

**Comment by Saduf2019** [comment]
@istiaq28 
We see that you are using old version of tensorflow which is not actively supported now, please verify on 2.x and open a new issue in case you face any errors, hence moving this to closed status.
