### ISSUE TITLE
Bug - Conv2DTranspose, wrong shape inferring due to bug in call()

### ISSUE THREAD

**Issue by davideboschetto** [keras-team/keras#13776]
BUG
**System information**  
- Have I written custom code (as opposed to using example directory):  
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Windows 10 17134
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  1.14.0
- Keras version:  2.3.1
- Python version:  3.6
- CUDA/cuDNN version: 10.0- 7.6.5  
- GPU model and memory:  1x RTX 2080 Ti, 2x GTX 1080 Ti, 320GB RAM

Current behavior:
Shape inferring (whichever value you assign to output_padding) is not working with Conv2DTranspose. 

I expect this to return the right inferred output shape:
```
the_output = Conv2DTranspose(filters=64,
             kernel_size = (2,2),
             strides = (2,2),
             padding = 'valid',
             output_padding = 0,
             data_format = K.image_data_format(), #channels_first
             dilation_rate = (1, 1),
             use_bias = False)(the_input)
```
The shape of the input is (?, 64, 128, 32). The shape of the output should be, according to the documentations (and to what I expect it to be) (?, 64, 256, 64) but instead is returned as (?, 64, ?, ?). 

This happens because in the call function of Conv2DTranspose you pass as arguments to deconv_length the parameters height and width that are computed like this:
``` input_shape = K.shape(inputs)```

```  height, width = input_shape[h_axis], input_shape[w_axis]```

Height and width have no meaning in this situation. 
If you change it to:
`height, width = inputs.shape[h_axis], inputs.shape[w_axis]`

the call to deconv_length work as expected, returning the correct output shape.

With this modification, the shape inferring works even without passing the output_padding parameter (which make keras compute explicitly the output shape instead of inferring it).

**Comment by davideboschetto** [comment]
#13778 fixes this bug.

**Comment by sushreebarsa** [comment]
@davideboschetto  We see that you are using old version of tensorflow which is not actively supported now, please verify on 2.x and open a new issue in case you face any errors, hence moving this to closed status.Thanks!
