### ISSUE TITLE
When 'alpha = None', LeakyReLU with Tensorflow backend have unexpected behavior

### ISSUE THREAD

**Issue by shiningrain** [keras-team/keras#13787]
**System information**  
- Have I written custom code (as opposed to using example directory):  
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Windows 10 & Linux Ubuntu 18.04
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  1.15.0 
- Keras version:  2.3.1
- Python version:  3.6.9
- CUDA/cuDNN version:  -
- GPU model and memory:  -

**Describe the current behavior**  
When I use `alpha=None` in `LeakyReLU,` the output with TensorFlow backend will perform like following this rule :
_f(x) = nan for x < 0, f(x) = x for x >= 0_
However, I can find the implementation of leakyrelu in TensorFlow lib: `tensorflow_core\python\ops\gen_nn_ops.py, near line 5396`
In tensorflow codes we can find this:
```
  if alpha is None:#near line 5428
    alpha = 0.2
```
This means that **if we set alpha to 'None', TensorFlow backend will set it to 0.2 to calculate, but not the 'nan' which we got from Keras using TensorFlow backend**.
Maybe something is wrong in the code or my thought.
I have debugged and found that Keras have used K.cast_to_floatx() to convert the alpha. And it converted alpha from the 'None' to 'nan' (site-packages\keras\layers\advanced_activations.py, near line 45). Maybe this is the reason? Should we set a check function before K.cast_to_floatx() to make sure if we will convert the "None" toavoid this situation?

**Code to reproduce the issue**  
My code is only for reference, In fact, we can just set alpha to None in the Keras layer test file.

```
import os
import sys
import numpy as np
import argparse
import pickle
import keras.layers as L
import keras.backend as K
backends = ['tensorflow','cntk','theano']

def set_keras_backend(backend='tensorflow'):
    if K.backend() != backend:
        os.environ['KERAS_BACKEND'] = backend
        importlib.reload(K.load_backend)
        importlib.reload(K)
        assert K.backend() == backend

def inference(bk='tensorflow', model_path=None, input=None):
    set_keras_backend(backend=bk)
    from keras.models import load_model
    model = load_model(model_path)
    output = model.predict(input)
    return output

def reproduce(layer_name=None, kwargs={}, input=None):
    for bk in backends:
        set_keras_backend(backend=bk)
        from keras.engine import Model, Input
        K.set_floatx(str(input.dtype))
        try:
            layer_cls = getattr(L, layer_name)
            layer = layer_cls(**kwargs)
            x = Input(batch_shape=input.shape)
            y = layer(x)
            Model(x, y)
        except Exception:
            print('error')

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Analysis')
    parser.add_argument('-path', '-p', type=str,help='Bug Path')
    args = parser.parse_args(r'-p \DL-Bug-Testing\result\LeakyReLU\nan-00f3c085-725a-3991-840a-0a8b676af6ea'.split( ))

    root_path = os.path.abspath(args.path)
    with open(os.path.join(root_path, 'meta.pkl'), 'rb') as f:#input,bug type,params
        meta = pickle.load(f)
    K.set_floatx('float32')
    layer = meta['layer']
    err_type = meta['err_type'].upper()
    kwargs = meta['kwargs']
    input1 = meta['input']
    input=input1.astype(np.float32)
    logger.info('{}--->{}'.format(layer, err_type.upper()))
    logger.info('Kwargs: \n{}'.format(kwargs))

    reproduce(layer_name=layer, kwargs=kwargs, input=input)
    output = {}
    model_path = os.path.join(root_path, 'model.h5')
    for bk in backends:
        output[bk] = inference(bk=bk, model_path=model_path, input=input)
        print(output[bk])
```
**Other info / logs**  
[nan-00f3c085-725a-3991-840a-0a8b676af6ea.zip](https://github.com/keras-team/keras/files/4209886/nan-00f3c085-725a-3991-840a-0a8b676af6ea.zip)

 Files which is used in the code is uploaded here.

**Comment by Saduf2019** [comment]
@shiningrain 


We see that you are using old version of tensorflow which is not actively supported now, please verify on 2.x and open a new issue in case you face any errors, hence moving this to close
