### ISSUE TITLE
Fit give OOM, but fit_generator work perfect

### ISSUE THREAD

**Issue by pykeras** [keras-team/keras#13781]
Hi 
I just write a code for OctConv2DTranspose, and build a network using that the problem is that when I try run network with `model.fit()` it will give me `OOM Error` even with `batch_size=1` 
but when using `model.fit_genrator()` it work perfectly fine `batch_size=32`
 
I'm wondering if there is a problem with tensorflow/keras or a problem in my code.

**System information**  
- Have I written custom code (as opposed to using example directory):  
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  '1.13.1'
- Keras version:  -
- Python version:  3.7.5rc1
- CUDA/cuDNN version:  10.0
- GPU model and memory:  1080Ti

[Code to reproduce the issue](https://github.com/pykeras/OctConv-Keras/blob/master/UNet_OctConv_keras.ipynb)

Thanks alot

**Comment by sushreebarsa** [comment]
@pykeras  We see that you are using old version of tensorflow which is not actively supported now, please verify on 2.x and open a new issue in case you face any errors, hence moving this to closed status.Thanks!
