### ISSUE TITLE
Conv2dTranspose(dilation=(1,2)) can't build model on Tensorflow backends but no warning or description in the documents

### ISSUE THREAD

**Issue by shiningrain** [keras-team/keras#13818]
**System information**  
- Have I written custom code (as opposed to using example directory):  
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):   Windows 10
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  1.15.0-cpu
- Keras version:  2.3.1
- Python version:  3.6.9
- CUDA/cuDNN version:  -
- GPU model and memory:  -

**Describe the current behavior**  
When we set `dilation_rate `= (x, y)(x!=y), **both CNTK and Theano backends can run normally and even save the model, but TensorFlow will report an error** 
`'<class 'AssertionError'>, AssertionError()'`
It seems that it does not support such a setting. However, I don't see the corresponding description in Keras' documents. This may bring hidden dangers: if a user trains a model using the cntk or theano backend, he may run this model on a different backend without being alerted, and get unexpected errors.

**Code to reproduce the issue**  
```
import os
import numpy as np
import keras.layers as L
import keras.backend as K
import importlib

def set_keras_backend(backend='tensorflow'):
    if K.backend() != backend:
        os.environ['KERAS_BACKEND'] = backend
        importlib.reload(K.load_backend)
        importlib.reload(K)
        assert K.backend() == backend



layer_name = 'Conv2DTranspose'
kwargs={'filters': 19, 'kernel_size': (3, 3), 'padding': 'same', 'output_padding': (0, 0), 'strides': 2, 'dilation_rate': (1, 2), 'data_format': 'channels_last'}
input_data = (10 * np.random.random((1,32,32,16)))
input = input_data.astype('float32')
set_keras_backend('tensorflow')
from keras.engine import Model, Input
K.set_floatx(str(input.dtype))
layer_cls = getattr(L, layer_name)
layer = layer_cls(**kwargs)
x = Input(batch_shape=input.shape)
y = layer(x)
bk_model = Model(x, y)#you can save a h5 model here

```

**Comment by shiningrain** [comment]
DepthwiseConv2D(dilation=(x,y)), when x!=y, cntk will return error: <class 'ValueError'>, ValueError('CNTK Backend: non-square dilation_rate is not supported.',)
But tensorflow and theano backend can run it well. The document seems not to warn this too.
You can change the layer_name and kwargs in the above code to reproduce this issue.

**Comment by Saduf2019** [comment]
@shiningrain 
We see that you are using old version of tensorflow which is not actively supported now, please verify on 2.x and open a new issue in case you face any errors, hence moving this to closed status.
