### ISSUE TITLE
Dense(unit=0) can trigger errors on cntk and theano backend, but tensorflow runs well

### ISSUE THREAD

**Issue by shiningrain** [keras-team/keras#13819]
**System information**  
- Have I written custom code (as opposed to using example directory):  
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Windows 10
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  1.15.0
- Keras version:  2.3.1
- Python version:  3.6.9
- CUDA/cuDNN version:  -
- GPU model and memory:  -

**Describe the current behavior**  
When we set Dense (units = 0), **both CNTK and Theano can report an error because the shape will contain 0 in the operations, but TensorFlow can run smoothl**y. Does unit = 0 have any special effect on TensorFlow? I don't see the corresponding instructions in the documentation.

**Code to reproduce the issue**  
```
import os
import numpy as np
import keras.layers as L
import keras.backend as K
import importlib


def set_keras_backend(backend='tensorflow'):
    if K.backend() != backend:
        os.environ['KERAS_BACKEND'] = backend
        importlib.reload(K.load_backend)
        importlib.reload(K)
        assert K.backend() == backend


kwargs={'units': 0}
input_data = (10 * np.random.random((1,32,32,16)))
input = input_data.astype('float32')
set_keras_backend('tensorflow')
from keras.engine import Model, Input
K.set_floatx(str(input.dtype))
layer = L.core.Dense(**kwargs)
x = Input(batch_shape=input.shape)
y = layer(x)
bk_model = Model(x, y)
print('finish')
```

**Comment by sushreebarsa** [comment]
@shiningrain  We see that you are using old version of tensorflow which is not actively supported now, please verify on 2.x and open a new issue in case you face any errors, hence moving this to closed status.Thanks!
