### ISSUE TITLE
Model.save() very, very, very slow

### ISSUE THREAD

**Issue by JivanRoquet** [keras-team/keras#13835]
**System information**  
- Have I written custom code (as opposed to using example directory):  yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Ubuntu 16.04
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  1.13.2
- Keras version:  2.2.4
- Python version:  3.6
- CUDA/cuDNN version:  10.1
- GPU model and memory:  Tesla K80 (multiple GPUs)
- Using Jupyter Notebook environment

**Describe the current behavior**  

1. import InceptionV3 model with pre-trained weights from keras.applications (include_top=False)
2. add a few layers on top and call it "model"
3. make a parallel_model with multi_gpu_model
4. fit the parallel model with data
5. save "model" into "file.h5" by using `model.save('file.h5')`

Monitoring from the terminal, "file.h5" seems to be growing at around 1Mb per minute instead of usually several 10's Mb per second.

**Describe the expected behavior** 

Model should be saved in a few seconds or maybe a few minutes (not 8 to 10 hours)

**Code to reproduce the issue**  

```python
with tf.device('/cpu:0'):
    pretrained_model = InceptionV3(weights='imagenet', include_top=False)

    x = pretrained_model.output
    x = GlobalAveragePooling2D(name='gap_final')(x)
    x = Dense(1024, activation='relu', kernel_regularizer=regularizers.l2(0.005))(x)
    x = Dropout(0.2)(x)

    preds = Dense(len(config.classes),activation='softmax')(x)
    model = Model(inputs=pretrained_model.input, outputs=preds)

parallel_model = multi_gpu_model(model, gpus=16)
parallel_model.compile(optimizer=Adam(lr=0.0005), loss='categorical_crossentropy', metrics=['accuracy'])

parallel_model.fit_generator(
    batch_train, epochs=20,
    steps_per_epoch=train_k // config.batch_size,
    validation_data=batch_valid, validation_steps=valid_k // config.batch_size
)

model.save('file.h5')
```

**Other info / logs**  

Stopping the execution of model.save() from the Jupyter notebook, deleting the h5 file and then starting model.save() again re-creates the file with exactly the same size as it was before being deleted.

Example:
- run model.save() and wait until the file.h5 file is 50Mb
- stop model.save()
- `rm file.h5` from the terminal and check that it's effectively gone
- start model.save() again
- the re-created file.h5 immediately hits 50Mb just as it was before being deleted

This makes me think that there is no data transfer issue.

I have not experienced this slowness before with other models, it's the first time I see it happening.

**Comment by JaggerYoung** [comment]
+1，very very slow

**Comment by sushreebarsa** [comment]
@JivanRoquet  We see that you are using old version of tensorflow which is not actively supported now, please verify on 2.x and open a new issue in case you face any errors, hence moving this to closed status.Thanks!
