### ISSUE TITLE
Tensorflow-Keras: Loading weights from checkpoint increases graph size significantly

### ISSUE THREAD

**Issue by jptrxff** [keras-team/keras#13837]
I am working with a rather large network (98 million parameters), I am using the Keras ModelCheckPoint callback to save my weights as follows, when I reload my saved weights using keras, I can see that the loading operation adds approximately 10 operations per layer in my graph. This results in a huge memory increase of my total network. Is this expected behavior? And if so, are there any known work arounds?

Details: I am using: tf.keras.callbacks.ModelCheckpoint with "save_weights_only=True" as argument to save the weights

The code for loading it is: model.load_weights(path_to_existing_weights)

where model is a custom keras model.

I am using Tensorflow 1.14 and Keras 2.3.0

Can you guys point me in the right direction? or confirm that what I am experiencing is expected behavior?

**Comment by sushreebarsa** [comment]
@jptrxff  We see that you are using old version of tensorflow which is not actively supported now, please verify on 2.x and open a new issue in case you face any errors, hence moving this to closed status.Thanks!
