### ISSUE TITLE
ImageDataGenerator class_mode='raw' functionality

### ISSUE THREAD

**Issue by tinder-arozinov** [keras-team/keras#13839]
**System information**  
- OS Platform and Distribution ( Linux Ubuntu 16.04):  
- TensorFlow backend (yes):  
- TensorFlow version (1.14):  
- Keras version (2.2.4-tf):  
- Python version (3.6):  

**Describe the current behavior**  
I'm trying to generate raw, one-hot class vectors for a set of images. 

```
import os
from PIL import Image
from tensorflow.keras.preprocessing.image import ImageDataGenerator
os.mkdir('images')

N=10
for i in range(N):
    image = Image.new('RGB', (10, 10))
    image.save(f"images/{i}.jpg")
    
df = pd.DataFrame.from_dict([{'filePath': f'images/{i}.jpg'.format(i),'y':[1.,0.,0.]} for i in range(N)])
```
Giving:

![image](https://user-images.githubusercontent.com/24922223/75580396-87136200-5a1c-11ea-8fd6-1098804fc2f7.png)

Next I make a data generator:

```
datagen = ImageDataGenerator()

train_generator = datagen.flow_from_dataframe(
        dataframe=df,
        directory=None,
        x_col="filePath",
        y_col="y",
        target_size=(10,10),
        batch_size=3,
        class_mode='raw',
        shuffle=False)

out = next(train_generator)
```
This is where the issue arises. Notice that the target part of `out` is not a 2-D array, but a 1-D array of list objects. Running a direct `np.array` function on the list gives the desired result.

![image](https://user-images.githubusercontent.com/24922223/75580486-b629d380-5a1c-11ea-93ed-ba185b596ab4.png)

Is there any fix for this, aside from making a custom generator?

**Comment by bomila** [comment]
can i work on this issue

**Comment by chalar** [comment]
Hi!! Any update about this issue?

**Comment by sushreebarsa** [comment]
@tinder-arozinov We see that you are using old version of tensorflow which is officially considered as end of life, We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions .Please open a new issue in case you face any errors, we will get you the right help .Hence moving this to closed status.Thanks!

**Comment by ltkhang** [comment]
> @tinder-arozinov We see that you are using old version of tensorflow which is officially considered as end of life, We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions .Please open a new issue in case you face any errors, we will get you the right help .Hence moving this to closed status.Thanks!

No, this issue still exists in the new version 2.5.0.

I tried to convert each row in "y" column as "numpy array" but still got the error "Failed to convert a NumPy array to a Tensor (Unsupported object type numpy.ndarray)."

**Comment by ltkhang** [comment]
I found the solution, instead of usinf a list of arrays, you can break it into multiple cols.
My solution:
![tmp](https://user-images.githubusercontent.com/4698213/126897833-d45d6a1f-32d6-47a3-962b-7154d0566e96.PNG)
![tmp2](https://user-images.githubusercontent.com/4698213/126897839-c2618793-b521-4c19-b8aa-8f1b4271cb39.PNG)

**Comment by ysl125963** [comment]
I have the same problem !!
