### ISSUE TITLE
 Tensorflow fails to build `GRU` models in some cases.  But we can successfully build and save the models if we switch the backend to Theano or CNTK. More surprisingly,  the models built by Theano can be successfully loaded and predicted on Tensorflow then. But when it comes to the models built by CNTK, Tensorflow fails in loading.

### ISSUE THREAD

**Issue by Jup11ter** [keras-team/keras#13851]
## System information

- Have I written custom code (as opposed to using example directory):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 & Linux Ubuntu 18.04
- Tensorflow backend (yes / no): yes
- Tensorflow version：1.14.0-gpu
- Cntk version: 2.7-gpu
- Theano version:1.04-gpu
- Keras version: 2.3.1
- Python version: 3.6.8
- CUDA/cuDNN version: -
- GPU model and memory: -

## Describe the current behavior
**Using Tensorflow as backend, when I directly build a model with layer `GRU`,  or load the `GRU` model built by CNTK, I get some variable multiplication errors, which reveals unsatisfacory implementation on Tensorflow in supporting variable multiplication.** The behaviors of different backends in building and loading models are shown in the following table.

|                | Build model       | Load Theano-built model |Load CNTK-built mode|
| -------------- | :---------------- | :---------------------- |---|
| **Tensorflow** | &times; (Error 1) | &radic;                 |&times; (Error 2) |
| **CNTK**       | &radic;     | &radic;       |&radic;   |
| **Theano**     | &radic;           | &radic;                 |&radic;   |

* Error 1

  When I build a model with the layer `GRU` on Tensorflow backend, I get the following error, raised in `tensorflow_core\python\ops\resource_variable_ops.py line 1229`. However, we can successfully build and save the model using Theano or CNTK as backend. **Similar issues on Tensorflow backend also happen in `LSTM` and `SimpleRNN`**.  **For detailed parameters of `GRU`, you can refer to the following code snippet.**

  ```
  <class 'RuntimeError'>, RuntimeError('Variable *= value not supported. Use var.assign(var * value) to modify the variable or var = var * value to get a new Tensor object.',), <traceback object at 0x00000240961ED908>),
  ```

  Worse still, the table shows that **although Tensorflow reports an error when building the `GRU` model, it can successfully load and run the model built by Theano, and even get almost the same results as Theano** (the sum of absolute differences is less than 1e-10). 

* Error 2

  There is another interesting phenomenon in the above table: without any parameter changes, **when I use CNTK to save a same `GRU` model, Tensorflow also fails in loading it, reporting the similar variable multiplication error as Error 1.**

  ```
  ERROR (<class 'RuntimeError'>, RuntimeError('Variable *= value not supported. Use `var.assign(var * value)` to modify the variable or `var = var * value` to get a new Tensor object.',), <traceback object at 0x000001AA04BA6FC8>)
  ERROR:tensorflow:==================================
  Object was never used (type <class 'tensorflow.python.ops.tensor_array_ops.TensorArray'>):
  <tensorflow.python.ops.tensor_array_ops.TensorArray object at 0x000001AA04A7BA58>
  If you want to mark it as used call its "mark_used()" method.
  It was originally created here:
    File "G:\conda\envs\py36\lib\site-packages\tensorflow_core\python\keras\backend.py", line 3921, in <genexpr>
      for ta, input_ in zip(input_ta, flatted_inputs))  File "G:\conda\envs\py36\lib\site-packages\tensorflow_core\python\util\tf_should_use.py", line 198, in wrapped
      return _add_should_use_warning(fn(*args, **kwargs))
  
  ```

## Key insights

Both Error1 and Error2 indicate that **the variable multiplication with format `Variable *= value` is not well supported on TensorFlow. It should be extended to full mode to conduct multiplication.  This caused Tensorflow to be unable to build the model itself or load the CNTK model.** 

## Code to reproduce the issue

``` python
import os
import numpy as np
import keras.layers as L
import keras.backend as K
import importlib
from keras.models import load_model
from keras.engine import Model, Input

backends = ['cntk','tensorflow','theano']

def acc_abs_diff(output1, output2):
    assert output1.shape == output2.shape
    abs_diff = np.abs(output1-output2)
    return  np.sum(abs_diff)

def set_keras_backend(backend='tensorflow'):
    if K.backend() != backend:
        os.environ['KERAS_BACKEND'] = backend
        importlib.reload(K.load_backend)
        importlib.reload(K)
        assert K.backend() == backend

# GRU kwargs
kwargs = {
		'units': 2, 
  	'dropout': 0.20430343923336958, 
  	'recurrent_dropout': 0.7597739154146002, 
  	'implementation': 2,
    'reset_after': True, 
    'use_bias': True, 
    'return_sequences': False, 
    'return_state': False,
    'go_backwards': False, 
    'stateful': True, 
    'unroll': False
} 

# SimpleRNN kwargs
# kwargs = {
#		'units': 2, 
#  	'dropout': 0.9030407578803185, 
#  	'use_bias': True, 
#  	'recurrent_dropout': 0.8988069898639027, 
#  	'return_sequences': False, 
#  	'return_state': False, 
#  	'go_backwards': True, 
#  	'stateful': True, 
#  	'unroll': True
#}  


input_data = (10 * np.random.random((2,10,8)))
input = input_data.astype('float32')
set_keras_backend('tensorflow')  #you can change the backend to reproduce the issue
layer = L.recurrent.GRU(**kwargs)
#layer = L.recurrent.SimpleRNN(**kwargs)
x = Input(batch_shape=input.shape)
y = layer(x)
bk_model = Model(x, y)
model_path = os.path.join('./', 'model.h5')
bk_model.save(model_path, bk_model)
output = {}
for bk in backends:
    try:
        set_keras_backend(backend=bk)
        model = load_model(model_path)
        output[bk] = model.predict(input)
    except:
        print('error result')
print('finish')
```

**Comment by Saduf2019** [comment]
@Jup11ter 
We see that you are using old version of tensorflow which is not actively supported now, please verify on 2.x and open a new issue in case you face any errors, hence moving this to closed status.
