### ISSUE TITLE
CNTK backend has supporting issues with `GRU (unroll=true)` , and Keras lacks necessary warnings or descriptions in corresponding documentation.

### ISSUE THREAD

**Issue by Jup11ter** [keras-team/keras#13852]
## System information

- Have I written custom code (as opposed to using example directory):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 & Linux Ubuntu 18.04
- Tensorflow backend (yes / no): yes
- Tensorflow version：1.15.0
- Cntk version: 2.7
- Theano version:1.04
- Keras version: 2.3.1
- Python version: 3.6.9
- CUDA/cuDNN version: -
- GPU model and memory: -

## Describe the current behavior
When I build a model with layer `GRU`(parameter `unroll=True`), the three backends display different behaviours, as shown below.   **For detailed parameters of `GRU`, you can refer to the following code snippet.**

|                | Build model       | Load Theano-built model |
| -------------- | :---------------- | :---------------------- |
| **Tensorflow** | &times; (Error 1) | &radic;                 |
| **CNTK**       | &times; (Error 2) | &times; (Error 3)       |
| **Theano**     | &radic;           | &radic;                 |

### Build model

Only Theano can build such a model.  

* Error 1: Tensorflow. 
  ``` ocaml
  <class 'RuntimeError'>, RuntimeError('Variable *= value not supported. Use var.assign(var * value) to modify the variable or var = var * value to get a new Tensor object.',), <traceback object at 0x00000240961ED908>),
  ```

  This variable multiplication error is similar to  [keras issue13851](https://github.com/keras-team/keras/issues/13851)

* Error 2: CNTK 

  See `cntk\ops\__init__.py line 2743`

``` vim
`RuntimeError: Function 'Slice: Output('Plus237_Output_0', [#], [2 x 6]) -> Unknown': Slice operation index range [2,4), interpreted as [2,4), is invalid for input 'Output('Plus237_Output_0', [#], [2 x 6])' shape '[2 x 6]'.`
```

### Load model built by Theano

Tensorflow can load the model built by Theano and get almost the same output. (see the following picture).  

![pic10](https://user-images.githubusercontent.com/61384431/75657769-e59d4200-5ca1-11ea-8c16-e4539667b57c.png)

* Error 3: CNTK

  CNTK can't load Theano-built model, and return error in predict process.

``` prolog
'Function 'Slice: Output('Plus171_Output_0', [#], [2 x 6]) -> Unknown': Slice operation index range [2,4), interpreted as [2,4), is invalid for input 'Output('Plus171_Output_0', [#], [2 x 6])' shape '[2 x 6]'.'
```

## Key insights

It seems that CNTK cannot support `GRU` well, when `unroll=True`.  **There are some implementation gaps across backends herein, but Keras document does not mention this potential risk.**  This may cause confusion for CNTK users.

##  Code to reproduce the issue

``` python
import os
import numpy as np
import keras.layers as L
import keras.backend as K
import importlib
from keras.models import load_model
from keras.engine import Model, Input

backends = ['cntk','tensorflow','theano']

def acc_abs_diff(output1, output2):
    assert output1.shape == output2.shape
    abs_diff = np.abs(output1-output2)
    return  np.sum(abs_diff)

def set_keras_backend(backend='tensorflow'):
    if K.backend() != backend:
        os.environ['KERAS_BACKEND'] = backend
        importlib.reload(K.load_backend)
        importlib.reload(K)
        assert K.backend() == backend


kwargs = {
  	'units': 2, 
  	'dropout': 0.20430343923336958, 
  	'recurrent_dropout': 0.7597739154146002, 
  	'implementation': 2, 
  	'reset_after': True, 
  	'use_bias': True, 
  	'return_sequences': False, 
  	'return_state': False, 
  	'go_backwards': False, 
  	'stateful': True, 
  	'unroll': True
}

input_data = (10 * np.random.random((2,10,8)))
input = input_data.astype('float32')
set_keras_backend('theano')  #you can change the backend 'theano' to reproduce the issue
layer = L.recurrent.GRU(**kwargs)
x = Input(batch_shape=input.shape)
y = layer(x)
bk_model = Model(x, y)
model_path = os.path.join('./', 'model.h5')
bk_model.save(model_path, bk_model)
output = {}
for bk in backends:
    try:
        set_keras_backend(backend=bk)
        model = load_model(model_path)
        output[bk] = model.predict(input)
    except:
        print('error result')
print('finish')
```

**Comment by Saduf2019** [comment]
@Jup11ter 
We see that you are using old version of tensorflow which is not actively supported now, please verify on 2.x and open a new issue in case you face any errors, hence moving this to closed status.
