### ISSUE TITLE
Stopping before baseline reached

### ISSUE THREAD

**Issue by tennoshi** [keras-team/keras#13860]
<em>Please make sure that this is a Bug or a Feature Request and provide all applicable information asked by the template.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.</em>  

**System information**  
- Have I written custom code (as opposed to using example directory):  yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Linux
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  1.14.0
- Keras version:  2.3.1
- Python version:  3.7.6
- CUDA/cuDNN version: 7.6.5/cuda9.2.0 
- GPU model and memory:  

**Describe the current behavior**  

The way keras.callbacks.EarlyStopping is coded, training will stop after patience epochs if the training metric (eg, val_loss) remains above/below the input baseline.

**Describe the expected behavior**  

Training should continue until baseline has been reached, THEN stop after patience epochs have passed if training does not improve.

**Code to reproduce the issue**  
Provide a reproducible test case that is the bare minimum necessary to generate the problem.  

```
from keras.models import Model
from keras.layers import Input
from keras.layers.convolutional import Conv3D, Conv2D
from keras.layers.convolutional_recurrent import ConvLSTM2D
from keras.layers.normalization import BatchNormalization
from keras.callbacks import EarlyStopping
import numpy as np
from custom_layers import ReflectionPadding2D as PadLayer2D
from custom_layers import ReflectionPadding3D as PadLayer3D

dims = (40,40)
opt = 'adam'

# Initializing the model
inputs = Input(shape=(5,*dims,1))
padding = PadLayer2D(padding=(1,1))(inputs)
conv = ConvLSTM2D(filters=40, kernel_size=(3,3), padding='valid',
				  return_sequences=True)(padding)
batch = BatchNormalization()(conv)
padding = PadLayer3D(padding=(1,1,1))(batch)
conv3d = Conv3D(filters=1, kernel_size=(3,3,3), activation='sigmoid',
				padding='valid', data_format='channels_last')(padding)
model = Model(inputs=inputs, outputs=conv3d)
model.compile(optimizer=opt, loss='binary_crossentropy')

stopper = EarlyStopping(monitor="val_loss", mode="min", patience=5, baseline=0.1,
						verbose=True, restore_best_weights=True)
callbacks_list = [stopper]

# Train the network
model.fit(xtrain, ytrain, batch_size=10, epochs=10, validation_split = 0.05, callbacks=callbacks_list)

```

**Other info / logs**  
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.  

Because training stops after patience epochs (in above example, 5) there are no "best" weights to restore, giving the following error:

```
Traceback (most recent call last):
  File "/home/ket/Projects/cloudprediction/cloudprediction_callbacks.py", line 91, in <module>
    epochs=100, callbacks=callbacks_list)
  File "/home/ket/anaconda3/envs/gpuenv/lib/python3.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/ket/anaconda3/envs/gpuenv/lib/python3.7/site-packages/keras/engine/training.py", line 1732, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/ket/anaconda3/envs/gpuenv/lib/python3.7/site-packages/keras/engine/training_generator.py", line 260, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/ket/anaconda3/envs/gpuenv/lib/python3.7/site-packages/keras/callbacks/callbacks.py", line 152, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/ket/anaconda3/envs/gpuenv/lib/python3.7/site-packages/keras/callbacks/callbacks.py", line 834, in on_epoch_end
    self.model.set_weights(self.best_weights)
  File "/home/ket/anaconda3/envs/gpuenv/lib/python3.7/site-packages/keras/engine/network.py", line 516, in set_weights
    own_weights = weights[:num_param]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by tennoshi** [comment]
For anyone else looking for a work-around, changing the EarlyStopping.on_epoch_end() function as below (one line added) works. Note a work-around should not be necessary based on how the baseline is defined in the EarlyStopping reference documents.

```
    def on_epoch_end(self, epoch, logs=None):
        current = self.get_monitor_value(logs)
        if current is None:
            return

        if self.monitor_op(current - self.min_delta, self.best):
            self.best = current
            self.wait = 0
            if self.restore_best_weights:
                self.best_weights = self.model.get_weights()
        else:
            self.wait += 1
            if self.monitor_op(self.best, self.baseline):
                if self.wait >= self.patience:
                    self.stopped_epoch = epoch
                    self.model.stop_training = True
                    if self.restore_best_weights:
                        if self.verbose > 0:
                            print('Restoring model weights from the end of '
                                  'the best epoch')
                        self.model.set_weights(self.best_weights)
```

**Comment by Saduf2019** [comment]
@tennoshi 
We see that you are using old version of tensorflow which is not actively supported now, please verify on 2.x and open a new issue in case you face any errors, hence moving this to closed status.
