### ISSUE TITLE
Saving a keras.applications-based model takes forever

### ISSUE THREAD

**Issue by JivanRoquet** [keras-team/keras#13868]
**System information**  
- Have I written custom code (as opposed to using example directory):  yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  U16.04
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  1.13
- Keras version:  2.2
- Python version:  3.6
- CUDA/cuDNN version:  10.1
- GPU model and memory:  Tesla K80

**Describe the current behavior**  

After loading a VGG16 with ImageNet weights, adding some layers and then training the model a bit, using
```python
model.save('file.h5')
```
takes approx. 2.5 seconds, no issues, totally works

Now, when loading an InceptionV3 or a NasNet or a ResNet50 or ANYTHING ELSE apart from a VGGxx, with ImageNet weights, then adding some layers and training the model a bit, using
```python
model.save('file.h5')
```
literally takes hours (if not days).

The file is slowly building, by checking with the linux command line, at around 100kb/minute. It's been 30 minutes now and the files is barely bigger than 2Mb.

**Code to reproduce the issue**

```python
# VGG16
model_ = keras.applications.vgg16.VGG16(weights='imagenet', include_top=False)
x = GlobalAveragePooling()(model_.output)
x = Dense(16, activation='softmax')(x)
my_model = Model(inputs=my_model_.input, outputs=x)
my_model.fit(some_data)
my_model.save('file.h5') # takes 2.5 seconds on average

# NASNetMobile
model_ = keras.applications.nasnet.NASNetMobile(weights='imagenet', include_top=False)
x = GlobalAveragePooling()(model_.output)
x = Dense(16, activation='softmax')(x)
my_model = Model(inputs=my_model_.input, outputs=x)
my_model.fit(some_data)
my_model.save('file.h5') # takes YEARS

# InceptionV3
model_ = keras.applications.inception_v3.InceptionV3(weights='imagenet', include_top=False)
x = GlobalAveragePooling()(model_.output)
x = Dense(16, activation='softmax')(x)
my_model = Model(inputs=my_model_.input, outputs=x)
my_model.fit(some_data)
my_model.save('file.h5') # takes YEARS
```

**Describe the expected behavior**  

Using `model.save()` should not take that long. I don't understand why it works fine with VGG16/VGG19-based models and it takes ages for any other pre-trained model from keras.applications.

**Comment by JivanRoquet** [comment]
Update: when a model is finally saved, from one of the longer options above, then re-loading the model from the hdf5 file also takes ages.

```python
my_model = load_model('file.h5') # takes ages as well
```

Doing the same for a VGG-xx takes a few seconds at most.

**Comment by JivanRoquet** [comment]
If anyone is interested, I asked a question on StackOverflow about this issue.

https://stackoverflow.com/questions/60581664/saving-and-loading-some-models-takes-a-very-long-time-in-keras

**Comment by sushreebarsa** [comment]
@JivanRoquet We see that you are using old version of tensorflow which is not actively supported now, please verify on 2.x and open a new issue in case you face any errors, hence moving this to closed status.Thanks!
