### ISSUE TITLE
Make fit_generator get timeout configurable

### ISSUE THREAD

**Issue by UeliDeSchwert** [keras-team/keras#13878]
**System information**  
- Have I written custom code (as opposed to using example directory): Yes  
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Ubuntu 18.04.2 LTS
- TensorFlow backend (yes / no):   yes
- TensorFlow version:  1.14.0
- Keras version:  2.3.0
- Python version:  3.6
- CUDA/cuDNN version:  V9.1.85
- GPU model and memory:  No GPU used

I'm using Keras with TF backend to write a model using ConvLSTM2D.
Because the amount of the data is just too big to be able to be loaded into the memory, I use `fit_generator` to accomplish this.
Usually, everything works fine. All different datasets are loaded one after the other into `fit_generator`. Unless the system has heavy memory load. In these cases it is possible that I get the warning `/usr/local/lib/python3.6/dist-packages/keras/utils/data_utils.py:718: UserWarning: An input could not be retrieved. It could be because a worker has died.We do not have any information on the lost sample.`

I traced the error back to [keras/utils/data_utils.py#L713](https://github.com/keras-team/keras/blob/master/keras/utils/data_utils.py#L713) where it looks like Keras tries to load the next sample with a fixed timeout of 30 seconds. Actually, each dataset is not that huge (~500mb, scaling is applied in the generator as well). Usually a loading and processing takes around 2 seconds. If the memory is under huge load this skyrockets to over 30 seconds and then discards some samples.

It would be nice to have a setting to configure this timeout. In my case, I don't care if the training takes a few days longer if the generator needs to wait for I/O. But it is necessary that all samples are used. Therefore a setting to define the timeout used in [data_utils.py#L711](https://github.com/keras-team/keras/blob/7a39b6c62d43c25472b2c2476bd2a8983ae4f682/keras/utils/data_utils.py#L711) would be really nice.

At the moment all I can do is wait until other users don't use the memory as much until I start the training, and if during the training the memory is used too much by somebody else, my training gets filled with the warnings mentioned above.

Maybe there is any known other method? If yes, unfortunately no search could point me into the right direction.

Thanks in advance.

**Comment by PowerToThePeople111** [comment]
I am currently running into a similar problem: My data generator downloads huge files from s3, read them in and converts them to the appropriate format and then deletes the huge file. I have to do it that way, cause the whole dataset does not fit on the disk. 

Since the files are big, I get the timeout with this error. Imho it would make sense to make this timeout configurable.

**Comment by sushreebarsa** [comment]
@UeliDeSchwert We see that you are using old version of tensorflow which is officially considered as end of life, We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions .Please open a new issue in case you face any errors, we will get you the right help .Hence moving this to closed status.Thanks!
