### ISSUE TITLE
if 'class name' not in config 0 or config 0 'class name' == 'merge' KeyError: 0

### ISSUE THREAD

**Issue by RaspberryBoy** [keras-team/keras#13885]
**I am struggling to find a solution to this error.** 

Context: I am creating a deep-learning program. 
My imported model is a Keras.h5 model from a Google Teachable Machine.

The error might have something to do with sequential or functional models? or potentially layers? However I am still unsure on the purpose of these. 

Using TensorFlow backend. 2.1.5

Apologies if my code is incorrect, I am new to Python coding. 

**Imports:** 
from keras.preprocessing.image import img_to_array
from keras.models import load_model
from keras.preprocessing import image
from gpiozero import LEDBoard
from gpiozero.tools  import random_values
from imutils.video import VideoStream
from threading import Thread
import tensorflow as tf
import numpy as np
import imutils
import time
import cv2
import os

**Error:** 
File "/home/pi/.local/lib/python3.7/site-packages/keras/models.py", line 1367, in from_config
if 'class name' not in config 0 or config 0 'class name' == 'merge' KeyError: 0

**Comment by RaspberryBoy** [comment]
OpenCV Version 4.2.0

**Comment by aydenabad** [comment]
Did you ever figure it out? I have this issue too

**Comment by kumariko** [comment]
@RaspberryBoy We are checking to see if you still need help on this issue. We recommend that you upgrade to 2.6 which is latest stable version of TF and let us know if the issue still persists in newer versions. please check [**`link`**](https://stackoverflow.com/questions/52908944/keyerror-0-when-trying-to-load-a-sequential-model-in-keras). If it is resolved then please feel free to move this issue to close status. Thanks!
