### ISSUE TITLE
Dimension error in UNet using Keras. Cropping not happening

### ISSUE THREAD

**Issue by Flock1** [keras-team/keras#13884]
I know I am not supposed to post this error here but I have posted this on StackOverflow as well as the Slack channel but I haven't got any response. That's why I am posting here. 

<em>Please make sure that this is a Bug or a Feature Request and provide all applicable information asked by the template.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.</em>  

**System information**  
- Have I written custom code (as opposed to using example directory):  No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Ubuntu 18.04
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  1.14
- Keras version:  2.2.4
- Python version:  3.6
- CUDA/cuDNN version: 10.1 
- GPU model and memory:  GTX 1080

You can obtain the TensorFlow version with:  
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"  
You can obtain the Keras version with:  
python -c 'import keras as k; print(k.__version__)'  

**Describe the current behavior**  

I have posted this issue on Keras slack as well as StackOverflow but no one has replied. Here's the [StackOverflow](https://stackoverflow.com/questions/60523570/dimension-error-in-unet-using-keras-cropping-not-happening) link.

I am trying to use UNet but I don't know why cropping isn't happening. Can someone help me?

**Describe the expected behavior**  

It should work on varying image sizes

**Comment by Saduf2019** [comment]
@Flock1 
We see that you are using old version of tensorflow which is not actively supported now, please verify on 2.x and open a new issue in case you face any errors, hence moving this to closed status.
