### ISSUE TITLE
Switch Keras backend to Numpy

### ISSUE THREAD

**Issue by raselldev** [keras-team/keras#13909]
Hello!

Can i switch Numpy for Keras backend?
because i need learn numpy backend without tf, theano, or cntk.

**Comment by nadavkluger** [comment]
From keras docs:


>  At this time, Keras has three backend implementations available: the TensorFlow backend, the Theano backend, and the CNTK backend.
> 
> TensorFlow is an open-source symbolic tensor manipulation framework developed by Google.
> Theano is an open-source symbolic tensor manipulation framework developed by LISA Lab at Université de Montréal.
> CNTK is an open-source toolkit for deep learning developed by Microsoft.
> In the future, we are likely to add more backend options.

**Comment by raselldev** [comment]
Oke thank's
