### ISSUE TITLE
Issue in saving a keras model after creating the main resnet50 model into submodels

### ISSUE THREAD

**Issue by ashMajeed** [keras-team/keras#13924]
I am dividing a pretrained RESNET50 model into blocks, I redefined the whole model and created blocks. 

However, when I load the model, graph disconnected error is raised. I am new and experimenting with Keras models. I tried my best to fix it but I could not. Help is highly appreciated. Thanks in advance.

Please note I am splitting the model into blocks based on the code provided in this link  https://stackoverflow.com/questions/56147685/how-to-split-a-keras-model-with-a-non-sequential-architecture-like-resnet-into

        x = layers.Input(batch_shape=resnet_model.get_layer('input_1').get_input_shape_at(0))'
        def give_model1():
          def f(x):
            return block_1(x)
          return f

       def give_model2():
         def g(x):
          return block_2(x)
       return g

      inputs = x
      x = block_1(inputs)
      final=block_2(x)

     model = Model(inputs=inputs, outputs=final)
     model.save("resnet_model.h5")
     new_model= keras.models.load_model('resnet_model.h5')

      "ValueError: Graph disconnected: cannot obtain value for tensor Tensor("input_1_2:0", shape=(?, 
       224, 224, 3), dtype=float32) at layer "input_1". The following previous layers were accessed 
      without issue: []"
      python tensorflow

**Comment by jvishnuvardhan** [comment]
@ashMajeed Looks like this was already answered in Stackoverflow with great details. 

I am closing this issue as this was resolved. Please feel free to reopen if I am mistaken. thanks!
