### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'placeholder' 

### ISSUE THREAD

**Issue by tomklaver1995** [keras-team/keras#13923]
/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py in placeholder(shape, ndim, dtype, sparse, name)
    539         x = tf.sparse_placeholder(dtype, shape=shape, name=name)
    540     else:
--> 541         x = tf.compat.v1.placeholder(dtype, shape=shape, name=name)
    542     x._keras_shape = shape
    543     x._uses_learning_phase = False

AttributeError: module 'tensorflow' has no attribute 'placeholder'

**Comment by tilakrayal** [comment]
@tomklaver1995 ,

Can you please try upgrade to TensorFlow 2.0, you can still use 1.X API by replacing:

**import tensorflow as tf**
by

**import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()**

Also please take a look at this [issue](https://stackoverflow.com/questions/56226284/why-do-i-get-attributeerror-module-tensorflow-has-no-attribute-placeholder/56230839) with similar error.It helps.Thanks!
