### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError

### ISSUE THREAD

**Issue by Pluto1314** [keras-team/keras#13922]
I meet some trouble like this：
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[6,11] = -1 is not in [0, 2000)
	 [[{{node embedding_1/embedding_lookup}}]]

I've analyzed it for a long time and I don't know why. Is there any way to solve it？
code：
from __future__ import print_function
from keras.preprocessing import sequence
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.layers import Embedding
from keras.layers import LSTM
from keras.layers import Conv1D, MaxPooling1D
from keras.datasets import imdb
from Load_lstmdata import LstmData
import random
from itertools import chain
import numpy as np
# from sklearn.preprocessing import LabelBinarizer
from keras.utils import np_utils
# Embedding
# （词）嵌入
max_features = 2000
maxlen = 18
embedding_size = 64

# Convolution
# 卷积
kernel_size = 5
filters = 64
pool_size = 4

# LSTM
# 长短期记忆网络
lstm_output_size = 70

# Training
# 训练
batch_size = 18
epochs = 2

'''
Note:
batch_size is highly sensitive.
Only 2 epochs are needed as the dataset is very small.
'''
print('Loading data...')
LstmData, LstmLabel, Data_Y = LstmData()

index = [i for i in range(len(LstmData))]
random.shuffle(index)
LstmData = LstmData[index]
LstmLabel = LstmLabel[index]
# y = np_utils.to_categorical(Data_Y, num_classes=21)

trainNum = 2100
x_train = LstmData[:trainNum]         # 2100*18
y_train = LstmLabel[:trainNum]
x_test = LstmData[trainNum:]     
y_test = LstmLabel[trainNum:]

print(len(x_train), 'train sequences')
print(len(x_test), 'test sequences')
print('Pad sequences (samples x time)')
x_train = sequence.pad_sequences(x_train, maxlen=maxlen)
x_test = sequence.pad_sequences(x_test, maxlen=maxlen)
print('x_train shape:', x_train.shape)
print('x_test shape:', x_test.shape)

model = Sequential()
model.add(Embedding(max_features, embedding_size, input_length=maxlen))
model.add(Dropout(0.25))
model.add(Conv1D(filters,
                 kernel_size,
                 padding='valid',
                 activation='relu',
                 strides=1))
model.add(MaxPooling1D(pool_size=pool_size))
model.add(LSTM(lstm_output_size))
model.add(Dense(21))
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy',      # sparse_categorical_crossentropy
              optimizer='adam',
              metrics=['accuracy'])

print('Train...')
model.summary()
model.fit(x_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          validation_data=(x_test, y_test))
score, acc = model.evaluate(x_test, y_test, batch_size=batch_size)
print('Test score:', score)
print('Test accuracy:', acc)

**Comment by tilakrayal** [comment]
@Pluto1314 ,
Please refer this SO [link](https://stackoverflow.com/questions/62075321/tensorflow-python-framework-errors-impl-invalidargumenterror-invalid-argument) for similar error.It helps.Thanks!
