### ISSUE TITLE
Unexpected print in engine/base_layer.py

### ISSUE THREAD

**Issue by Svan70** [keras-team/keras#13935]
Keras version : 2.3.1

I have some unexpected prints in my keras code : 

```
tracking <tf.Variable 'Variable:0' shape=(9, 4) dtype=float32, numpy=

array([[-362.03867, -181.01933,  362.03867,  181.01933],
       [-456.14017, -228.07008,  456.14017,  228.07008],
       [-574.70056, -287.35028,  574.70056,  287.35028],
       [-256.     , -256.     ,  256.     ,  256.     ],
       [-322.5398 , -322.5398 ,  322.5398 ,  322.5398 ],
       [-406.37466, -406.37466,  406.37466,  406.37466],
       [-181.01933, -362.03867,  181.01933,  362.03867],
       [-228.07008, -456.14017,  228.07008,  456.14017],
       [-287.35028, -574.70056,  287.35028,  574.70056]], dtype=float32)> anchors
```

These prints come from this line in engine/base_layer.py :

https://github.com/keras-team/keras/blob/master/keras/engine/base_layer.py#L1237

I guess this is a forgotten print instruction... I can open a PR if needed. 
Print line was introduced in this commit : 479fc3a978221bb835f7e2781dcef0db66c96e1c

Thx

**Comment by jvishnuvardhan** [comment]
@Svan70 I think this was resolved in recently. I couldn't find the print command (`print('tracking', value, name)`)  in `master`.

Please check once and close the issue if this was already resolved. Thanks!

**Comment by Svan70** [comment]
@jvishnuvardhan I can't test right now, but I do not see the print in the code either. So yes, consider it as fixed. Thanks !
