### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'image_data_format'

### ISSUE THREAD

**Issue by PaddyUrs** [keras-team/keras#13958]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-11-2cf002a1bdd7> in <module>
----> 1 model = create_model('L')

<ipython-input-3-410e071e5e76> in create_model(model_size)
      3     if  model_size == 'L':
      4         resnet_weights_path = 'C:/Users/Parikshit/Desktop/Miniproject/resnet50/resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5'
----> 5         resnet = ResNet50(include_top=False, pooling='avg', weights=resnet_weights_path)
      6 
      7         #resnet.summary()

~\anaconda3\envs\tf-gpu\lib\site-packages\keras_applications\resnet50.py in ResNet50(include_top, weights, input_tensor, input_shape, pooling, classes, **kwargs)
    207                                       default_size=224,
    208                                       min_size=32,
--> 209                                       data_format=backend.image_data_format(),
    210                                       require_flatten=include_top,
    211                                       weights=weights)

AttributeError: 'NoneType' object has no attribute 'image_data_format'

**Comment by PaddyUrs** [comment]
If you want to see the code let me know

**Comment by work-mohit** [comment]
the same issue I m getting here , have you solved this issue ..?

**Comment by jvishnuvardhan** [comment]
@PaddyUrs If this is still an issue for you, can you share a simple standalone code to reproduce the issue? Thanks!

**Comment by PaddyUrs** [comment]
Thanks for your reply, but yeahh I figured it out no worries man.
