### ISSUE TITLE
Outdated Tutorial Page

### ISSUE THREAD

**Issue by Banyc** [keras-team/keras#13953]
<em>Please make sure that this is a Bug or a Feature Request and provide all applicable information asked by the template.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.</em>  

**System information**  
- Have I written custom code (as opposed to using example directory):  unrelated
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  unrelated
- TensorFlow backend (yes / no):  
- TensorFlow version:  unrelated
- Keras version:  unrelated
- Python version:  unrelated
- CUDA/cuDNN version:  unrelated
- GPU model and memory:  unrelated

**Describe the current behavior**  

Started from the "Convolutional autoencoder" section, tutorial on the page <https://blog.keras.io/building-autoencoders-in-keras.html> has some mistake about `plt` usage. The code is shown below.

**Describe the expected behavior**  

The usage of `plt` should be correct considering many learners might get frustrated when they imitated the code and got some unexpected errors.

**Code to reproduce the issue**  
Provide a reproducible test case that is the bare minimum necessary to generate the problem.  

```python
decoded_imgs = autoencoder.predict(x_test)

n = 10
plt.figure(figsize=(20, 4))
for i in range(n):
    # display original
    ax = plt.subplot(2, n, i)
    plt.imshow(x_test[i].reshape(28, 28))
    plt.gray()
    ax.get_xaxis().set_visible(False)
    ax.get_yaxis().set_visible(False)

    # display reconstruction
    ax = plt.subplot(2, n, i + n)
    plt.imshow(decoded_imgs[i].reshape(28, 28))
    plt.gray()
    ax.get_xaxis().set_visible(False)
    ax.get_yaxis().set_visible(False)
plt.show()
```

Focus on this code

```python
plt.subplot(2, n, i)
```

Unless `i` is started from `1`, this expression is not correct.

**Other info / logs**  
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.  

unrelated

**Comment by rmothukuru** [comment]
@Banyc,
The code of the [Keras Tutorial](https://blog.keras.io/building-autoencoders-in-keras.html) has been modified from 

`plt.subplot(2, n, i)` to **`plt.subplot(2, n, i + 1)`**

and the code now could be executed without any error. Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/20dac7c1ff25933a22812911926172ac/gh_keras_13953.ipynb) of the working code. Thanks!
