### ISSUE TITLE
Can not do batch_dot on inputs

### ISSUE THREAD

**Issue by ironWolf1990** [keras-team/keras#13961]
**System information**  
- OS Platform and Distribution : Ubuntu 18.04 
- TensorFlow backend :  yes
- TensorFlow version:  2.1
- Keras version:  2.3.1
- Python version:  3.7.7
- cudatoolkit - cuDNN version:  10.1.243 - 7.6.5
- GPU model and memory:  RTX 2070 

**Code** 
 Using example on keras site [Train a simple CNN-Capsule Network on the CIFAR10](https://keras.io/examples/cifar10_cnn_capsule/)

**Traceback**  

    Traceback (most recent call last):
    File "keras-example.py", line 164, in <module>
      capsule = Capsule(10, 16, 3, True)(x)

    File "/home/ironwolf1990/software/anaconda3/lib/python3.7/site-packages/keras/backend/
    tensorflow_backend.py", line 75, in symbolic_fn_wrapper
      return func(*args, **kwargs)

    File "/home/ironwolf1990/software/anaconda3/lib/python3.7/site-packages/keras/engine/
    base_layer.py", line 489, in __call__
      output = self.call(inputs, **kwargs)

    File "keras-example.py", line 123, in call
      b = K.batch_dot(o, hat_inputs, [2, 3])

    File "/home/ironwolf1990/software/anaconda3/lib/python3.7/site-packages/keras/backend/
    tensorflow_backend.py", line 1499, in batch_dot
      'y.shape[%d] (%d != %d).' % (axes[0], axes[1], d1, d2))

    ValueError: Can not do batch_dot on inputs with shapes (None, 10, 10, 16) and 
    (None, 10, None, 16) with axes=[2, 3]. x.shape[2] != y.shape[3] (10 != 16).

**Comment by tilakrayal** [comment]
@ironWolf1990 ,
Can you please take a look at this [comment](https://github.com/XifengGuo/CapsNet-Keras/issues/94) from the issue with similar error.It helps.Thanks
