### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'log'

### ISSUE THREAD

**Issue by Selolo28** [keras-team/keras#13960]
I get  "AttributeError: module 'tensorflow' has no attribute 'log'" error when I run my program.

I tried:

>>from tensorflow.python keras import backend as k

run the code again but didn't see any difference. Then,

>>from tensorflow import keras
>>from keras.backend.tensorflow_backend import set_session
>>from keras import applications
>>import tensorflow as tf

Still, nothing changed then I uninstalled keras 2.3.1 and installed the old version 2.1.3 and now I get 
AttributeError: module 'tensorflow' has no attribute 'placeholder'

I would really appriciate your help. Thank you
- Win10 
- TensorFlow backend
- TensorFlow version:  2.1.0
- Keras version:  2.3.1
- Python version: 3.7.6
- CUDA/cuDNN version:  Cuda 10.1
- GPU model and memory:  Nvidia 840M

**Comment by hamdanihamza** [comment]
try replacing `tf.log` by `tf.math.log`

**Comment by morganOliveira2018** [comment]
Can you solve the problem @Selolo28 ? I'm going through the same.
````
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-94ab32c3e66f> in <module>()
     89 
     90 config = InferenceConfig()
---> 91 model = modellib.MaskRCNN(mode="inference", model_dir=MODEL_DIR, config=config)
     92 
     93 # Create model object in inference mode.

5 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py in wrapper(*args, **kwargs)
    256       except Exception as e:  # pylint:disable=broad-except
    257         if hasattr(e, 'ag_error_metadata'):
--> 258           raise e.ag_error_metadata.to_exception(e)
    259         else:
    260           raise

AttributeError: in user code:

    /content/gdrive/My Drive/Fish-characteristic-measurement/Complete_code/mrcnn/model.py:390 call  *
        roi_level = log2_graph(tf.sqrt(h * w) / (224.0 / tf.sqrt(image_area)))
    /content/gdrive/My Drive/Fish-characteristic-measurement/Complete_code/mrcnn/model.py:341 log2_graph  *
        return tf.log(x) / tf.log(2.0)

    AttributeError: module 'tensorflow' has no attribute 'log'
````

**Comment by sahaj432** [comment]
> try replacing `tf.log` by `tf.math.log`

I tried to search in model.py file but I didn't find tf.log on it? would you please show me in which line it is?

**Comment by RickFSA** [comment]
@sahaj432 line 341 in model.py. Goodluck

**Comment by deadsupra** [comment]
Worked for me. Had to replace both calls.

From:
`return tf.log(x) / tf.log(2.0)`

To:
`return tf.math.log(x) / tf.math.log(2.0)`

Be warned though, Mask RCNN seems to still only support TF 1+ (<2.x). You will run into another issue.

**Comment by Al-Badri179** [comment]
I 

> Worked for me. Had to replace both calls.
> 
> From:
> `return tf.log(x) / tf.log(2.0)`
> 
> To:
> `return tf.math.log(x) / tf.math.log(2.0)`
> 
> Be warned though, Mask RCNN seems to still only support TF 1+ (<2.x). You will run into another issue.

I did the replacement step from [ return tf.log(x) / tf.log(2.0) ] to [return tf.math.log(x) / tf.math.log(2.0)] but it didn't work with me. I would appreciate any assistance

**Comment by vidya-research-2021** [comment]
> I
> 
> > Worked for me. Had to replace both calls.
> > From:
> > `return tf.log(x) / tf.log(2.0)`
> > To:
> > `return tf.math.log(x) / tf.math.log(2.0)`
> > Be warned though, Mask RCNN seems to still only support TF 1+ (<2.x). You will run into another issue.
> 
> I did the replacement step from [ return tf.log(x) / tf.log(2.0) ] to [return tf.math.log(x) / tf.math.log(2.0)] but it didn't work with me. I would appreciate any assistance

Solution 1: The folliwing code if from the official website (https://www.tensorflow.org/guide/upgrade)
$ tf_upgrade_v2 \
  --intree my_project/ \
  --outtree my_project_v2/ \
  --reportfile report.txt

So in this case, if you don't need a backup:

$ tf_upgrade_v2 --intree Mask_RCNN --inplace --reportfile report.txt

 Solution 2: If you are working on jupyter notebook, in the terminal from the project folder,
$ pip install -r requirements.txt --user

I tried both but Solution 2 worked for me.

**Comment by shubhambuccha** [comment]
> You will run into another iss

Can you tell me the versions you used that worked for you?

**Comment by tilakrayal** [comment]
@Selolo28 ,
Can you please take a look at this [comment](https://github.com/matterport/Mask_RCNN/issues/1797#issuecomment-560553450) from the issue with similar error.It helps.Thanks!
