### ISSUE TITLE
Custom keras/tensorflow layer, output-shape error

### ISSUE THREAD

**Issue by paulhigazi** [keras-team/keras#13970]
<em>Please make sure that this is a Bug or a Feature Request and provide all applicable information asked by the template.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.</em>  

**System information**  
- Have I written custom code (as opposed to using example directory):  
- Windows 10, Google Colab 
- TensorFlow backend (yes)
- TensorFlow version:  1.15
- Keras version:  2.3.1
- Python version:  3.6.9
- CUDA/cuDNN version:  Cuda compilation tools, release 10.1, V10.1.243
- GPU model and memory:  P100, 16gb

I wrote my own keras/tensorflow layer. Passing images into it works fine, but using it in combination with other layers, gives an error. Somehow the output shape of my custom layer should be wrong, or some kind of "Nonetype".

I posted my question on Stackoverflow, to reduce redundance, this link leads to the Stack-Question:

https://stackoverflow.com/questions/61231081/custom-keras-tensorflow-layer-output-shape-error

**Comment by kumariko** [comment]
@paulhigazi We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.6 which is latest stable version of TF and let us know if the issue still persists in newer versions. we will get you the right help.If it is resolved then please feel free to move this issue to close status.Thanks!
