### ISSUE TITLE
Keras AttributeError: 'NoneType' object has no attribute '_inbound_nodes'

### ISSUE THREAD

**Issue by TakeByEarn** [keras-team/keras#13978]
Here is python code with Keras 2.3.1 with tensorflow 1.14.0, python 3.6. 

 input_s = Input(shape=(self.ds,), dtype="float32", name="input_s")  
        input_a = Input(shape=(self.da,), dtype="float32", name="input_a")
        h_sa    = Concatenate(axis=1)( [input_s, input_a] )  # Concatenation of s,a 

        # 1:  2 layers fully connected 
        for i in range(0, 2): 
            h_sa = Dense(500, kernel_regularizer=self.reg_q, kernel_initializer=initializer)(h_sa)
            h_sa = LeakyReLU(alpha=0.01)(h_sa)
        
        # 2:  fc3
        h_sa = Dense(500+self._look_ahead, kernel_regularizer=self.reg_q, kernel_initializer=initializer)(h_sa)
        x1 =  h_sa[:, -self._look_ahead:]
        # 3: fc4
        h_sa = Dense(500+self._look_ahead, kernel_regularizer=self.reg_q, kernel_initializer=initializer)(h_sa[:, :-self._look_ahead])
        h_sa = LeakyReLU(alpha=0.01)(h_sa)
        x2 = h_sa[:, -self._look_ahead:]
        # 4: fc5
        x3 = Dense(1, kernel_regularizer=self.reg_q, kernel_initializer=initializer)(h_sa[:, :-self._look_ahead])
        x3 = LeakyReLU(alpha=0.01)(x3)

        x = Concatenate(axis=1)([x3, x2, x1])  # [bacth_size, 101]
        x = Lambda(lambda x: K.transpose(x))( x )
        output = Lambda(lambda tensor: K.expand_dims(tensor, axis=2))( x ) # tensor [101, batch_size, 1]

        # constrain regularization loss
        reg_loss = K.mean(K.square(output[0] - (output[1:self._look_ahead+1] + output[self._look_ahead+1:])))

        deep_q_model = Model(inputs=[input_s, input_a], outputs=[output])

-------------------------------------------------------------------------------------------------------------

Error info in the console:

  deep_q_model = Model(inputs=[input_s, input_a], outputs=[output])
  File "D:\Python\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "D:\Python\lib\site-packages\keras\engine\network.py", line 94, in __init__
    self._init_graph_network(*args, **kwargs)
  File "D:\Python\lib\site-packages\keras\engine\network.py", line 241, in _init_graph_network
    self.inputs, self.outputs)
  File "D:\Python\lib\site-packages\keras\engine\network.py", line 1436, in _map_graph_network
    tensor_index=tensor_index)
  File "D:\Python\lib\site-packages\keras\engine\network.py", line 1423, in build_map
    node_index, tensor_index)
  File "D:\Python\lib\site-packages\keras\engine\network.py", line 1423, in build_map
    node_index, tensor_index)
  File "D:\Python\lib\site-packages\keras\engine\network.py", line 1423, in build_map
    node_index, tensor_index)
  File "D:\Python\lib\site-packages\keras\engine\network.py", line 1423, in build_map
    node_index, tensor_index)
  File "D:\Python\lib\site-packages\keras\engine\network.py", line 1423, in build_map
    node_index, tensor_index)
  File "D:\Python\lib\site-packages\keras\engine\network.py", line 1395, in build_map
    node = layer._inbound_nodes[node_index]
AttributeError: 'NoneType' object has no attribute '_inbound_nodes'
-----------------------------------------------------------------------------------------------------------
I try to locate the point where error occur, so print the layers' info, but only got this:

layer name= <keras.layers.core.Lambda object at 0x000000B068379D68>   node_index 0
layer name= <keras.layers.core.Dense object at 0x000000B06836AE48>   node_index 0
layer name= <keras.layers.core.Dense object at 0x000000B0683134E0>   node_index 0
layer name= <keras.layers.core.Dense object at 0x000000B0683130F0>   node_index 0
layer name= <keras.engine.input_layer.InputLayer object at 0x000000B068304EF0>   node_index 0
layer name= <keras.layers.core.Lambda object at 0x000000B06A467C88>   node_index 0
layer name= <keras.layers.core.Lambda object at 0x000000B06A467F60>   node_index 0
layer name= <keras.layers.merge.Concatenate object at 0x000000B06A467CC0>   node_index 0
layer name= <keras.layers.advanced_activations.LeakyReLU object at 0x000000B06A467978>   node_index 0
layer name= <keras.layers.core.Dense object at 0x000000B06A445DD8>   node_index 0
layer name= None   node_index None

which seems one of layer is None, then i can'd do anything. Does anyone can solve this problem ?

**Comment by TakeByEarn** [comment]
I finally got the reason: during the process of construction model, each step must by Kears-tensor, not be tensorflow-tensor or Theano-tensor or numpy-array. So we have to using  keras.layers.Lambda to build a layers to slice the array. 


 def slice1(x, h1, h2):   # slice from h1 - h2
            """ Define a tensor slice function for kears"""
            return x[:, h1:h2]
 def slice2(x, h1):   # slice to end
            """ Define a tensor slice function for kears"""
            return x[:, h1:]    

  x1   = Lambda(slice2, arguments={ 'h1':-self._look_ahead} )(h_sa)
  h_sa = Lambda(slice1, arguments={ 'h1': 0, 'h2':-self._look_ahead} )(h_sa)

Every step must keras.layers type, that's a huge difference compare tensorflow(static graph mode)

**Comment by tilakrayal** [comment]
@TakeByEarn ,
Can you please take a look at this SO [link](https://stackoverflow.com/questions/44627977/keras-multi-inputs-attributeerror-nonetype-object-has-no-attribute-inbound-n) with similar error.It helps.Thanks!
