### ISSUE TITLE
Using sample_weight only works after disabling ValueErrors in training_utils.py

### ISSUE THREAD

**Issue by Juliusppz** [keras-team/keras#13994]
Hello,

I am using Keras that comes with Tensorflow CPU version 2.1.0 on Windows 10 with Python 3.7.2 

I built a convolutional model that uses individual weights for the different input samples. However, the broadcasting checks in Keras seem to incorrectly stop my usage of sample_weight. When I remove the ValueErrors raising in Keras, my model works as intended and I failed to get it to work using besides this hack. I used a lot of different shapes for the weights, I think all that make sense with numpy.

Here is part of my code to trigger this behavior:
```

pic_inds = np.random.randint(1, n_pics + 1, size=batch_size)
i = 0
for pic_ind in pic_inds:
     data[i, :, :, 0] = image.imread('images/train/' + str(pic_ind) + '.bmp')
     weights[i,0,0,0] = all_weights.loc[pic_ind, 'weights']
     i += 1
data = data / 255.0
ae_loss = ae.train_on_batch(data, data, sample_weight=weights)
```

And here are the changes I had to make to training_utils.py to make this work:

```
    if sample_weight is not None and len(sample_weight.shape) != 1:
      # raise ValueError('Found a sample_weight array with shape {}. In order to '
      #                  'use timestep-wise sample weights, you should specify '
      #                  'sample_weight_mode="temporal" in compile(); found "{}" '
      #                  'instead. If you just mean to use sample-wise weights, '
      #                  'make sure your sample_weight array is 1D.'
      #                  .format(sample_weight.shape, sample_weight_mode))
      pass

  if sample_weight is not None:
    if len(sample_weight.shape) > len(y.shape):
      raise ValueError('Found a sample_weight with shape' +
                       str(sample_weight.shape) + '.'
                       'Expected sample_weight with rank '
                       'less than or equal to ' + str(len(y.shape)))

    # if (not tensor_util.is_tensor(sample_weight) and
    #     y.shape[:sample_weight.ndim] != sample_weight.shape):
    #   raise ValueError('Found a sample_weight array with shape ' +
    #                    str(sample_weight.shape) + ' for an input with shape ' +
    #                    str(y.shape) + '. '
    #                    'sample_weight cannot be broadcast.')
```
Those two error messages are not surprisingly the ones that I get, if I run my code without both changes to training_utils.py.

**Comment by jvishnuvardhan** [comment]
@Juliusppz This is a stale issue. Sorry for late response. 

Is this still an issue for you? Can you please share a simple standalone code to reproduce the issue? Also, check your code with the recent TF versions (`2.6` and `tf-nightly`) and let us know whether the issue persists with recent TF versions. Thanks!

**Comment by Juliusppz** [comment]
@jvishnuvardhan Thank you for the response. This will most likely not be an issue for me anymore and right now I cannot provide the code you asked for. I might be able to try out the things you suggested in a month or so, but only if this is an important issue for you as well. If it is not, I suggest closing this thread.

**Comment by jvishnuvardhan** [comment]
@Juliusppz Thanks. I think I will close the issue for now. We can reopen the issue when you face any issues with your code. Thanks!
