### ISSUE TITLE
The clear_session() method of keras.backend does not clean up the previously execution 

### ISSUE THREAD

**Issue by RamziFsm** [keras-team/keras#14004]
When I run the model, I find that it was conflicting with the previously executed model. In addition to that, the global variables in my program contains values from the previous run. I used keras.backend.clear_session() and del model but the problem persists. How can I return to the initial state at each execution? 
I used google colab notebook as an execution environment with keras version 2.3.1 and Tensorflow backend 2.2.0

**Comment by tilakrayal** [comment]
@RamziFsm ,
Can you please provide the code to reproduce the issue also with latest tf and keras version and let us know if the issue still persists?Thanks!
