### ISSUE TITLE
Confusing documentation for on_epoch_end?

### ISSUE THREAD

**Issue by nicolas-gervais** [keras-team/keras#14023]
**System information**  
- Have I written custom code (as opposed to using example directory):  No (subclassing callbacks)
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Linux Ubuntu 18.04
- TensorFlow backend (yes / no):  YES
- TensorFlow version:  2.1.0
- Keras version:  2.2.4-tf
- Python version:  3.6.10
- CUDA/cuDNN version:  
- GPU model and memory:  

**Describe the current behavior**  
The documentation at [Keras Callbacks](https://keras.io/callbacks/) says 
> on_epoch_end: logs include acc and loss, and optionally include val_loss

However, '_acc_' throws an error, it seems to be only '_accuracy_'. If you
```
print(list(logs))
```
It gives:
```
['loss', 'accuracy']
```
**Describe the expected behavior**  

Documentation should say _accuracy_, not _acc_

**Code to reproduce the issue**  
```
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
import tensorflow as tf
from sklearn.datasets import make_blobs
from tensorflow.keras.layers import Dense
from tensorflow.keras import Model, Input
from tensorflow.keras.callbacks import Callback

X, y = make_blobs(n_features=10,
                  n_samples=5000,
                  cluster_std=1.5,
                  centers=5)


inputs = Input(shape=(10,))

x = Dense(8, activation='selu', kernel_initializer='lecun_normal')(inputs)
x = Dense(16, activation='elu', kernel_initializer='he_normal')(x)
outputs = Dense(5, activation='softmax')(x)

MyModel = Model(inputs=[inputs], outputs=[outputs])


class CustomCallback(Callback):
    def on_epoch_end(self, epoch, logs=None):
        print(list(logs))
        if logs.get('acc') > 9e-1:
            print('\nAccuracy above 80%, interrupting training.')
            self.model.stop_training = True


MyModel.compile(loss='sparse_categorical_crossentropy', 
    optimizer='sgd', metrics=['accuracy'])

history = MyModel.fit(X, y, callbacks=[CustomCallback()], epochs=20)
```
>TypeError: '>' not supported between instances of 'NoneType' and 'float'

When getting the documentation in `ipython` for `tensorflow.keras.callbacks.Callback`:
```
    on_epoch_end: logs include `acc` and `loss`, and
        optionally include `val_loss`
        (if validation is enabled in `fit`), and `val_acc`
        (if validation and accuracy monitoring are enabled).
```

**Comment by jvishnuvardhan** [comment]
@nicolas-gervais Sorry for the delayed response. This was an issue. But, it was resolved in the recent version. The current version clearly states what `logs` consists of

```
    Args:
        epoch: Integer, index of epoch.
        logs: Dict, metric results for this training epoch, and for the
          validation epoch if validation is performed. Validation result keys
          are prefixed with `val_`. For training epoch, the values of the
         `Model`'s metrics are returned. Example : `{'loss': 0.2, 'accuracy':
           0.7}`.
```

Also, you can define metric as `acc` or `accuracy` in `model.compile`. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/a3a0ce6afc78b7d211c06464203ec501/untitled.ipynb) that works as expected. Thanks!

**Comment by jvishnuvardhan** [comment]
Closing this as this was resolved in the recent docs. Thanks!
