### ISSUE TITLE
KeyError: 'sample_weight_mode'

### ISSUE THREAD

**Issue by benedives47** [keras-team/keras#14040]
I have done training and when loading load_model there is an error like that. please give enlightenment.
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  2.2
- Keras version: 2.3.1 
- Python version:  3.7

problem :
![Capture](https://user-images.githubusercontent.com/58981061/81471343-9f70db80-921a-11ea-95d7-62b2e6d89411.PNG)
![Capture2](https://user-images.githubusercontent.com/58981061/81471374-aef02480-921a-11ea-9de8-50f8901c512a.PNG)

**Comment by VismayTandel** [comment]
I don't know a solution but you can try it once that you had import load_model so can use directly in code like: model = load_model('/....')

**Comment by Raevel** [comment]
Resolved on my CNN.

Are you trying to load a model from a checkpoint? Because that's exactly how it went with me. 

When you use model_checkpoint it saves the model in a .h5 file. So, you have to load it using model.load_weights('NAMEOFFILE.h5').

But, if you use model.save function, you will have to use model.load. 

Hope this works for you also. Good luck!

**Comment by redsigma** [comment]
This error happens on keras 2.3.4 (last of this time) with tensorflow 2.2.0 built for python 3.7 on Raspberry pi 4 b
I tested on python 3.6.10 and it worked fine there.

**Comment by arbiter1elegantiae** [comment]
Had the same error, try to use the nightly TensorFlow version instead.

**Comment by NinaStr** [comment]
A version change has done the trick for me. 
tensorflow==2.3.0
numpy==1.18.0 (tensorflow 2.3.0 requires numpy<1.19.0,>=1.16.0)
Python 3.8

**Comment by libinruan** [comment]
I faced the same issue when I tried to load a trained model generated on Google Colab (TensorFlow 2.3.0) to my local machine (TensorFlow 2.0.0)

**Comment by AhmedMagdyHendawy** [comment]
@libinruan Did you manage to solve it?

**Comment by libinruan** [comment]
No, I didn't. I just downgraded Tensorflow to version 2.0 in one machine so
that trained models can be reloaded by the other machine.

**Comment by libinruan** [comment]
@AhmedMagdyHendawy
If you train the model with custom metric, loss, etc, then when you load the trained model, you need to pass into `load_model("some_model.h")` an additional argument `compile=False`. This specification resolves the issue for me when I trained a model on one machine and reloaded it on another one.

**Comment by DSPOWER93** [comment]
> @libinruan Did you manage to solve it?

I think it's a version issue when a model is saved in Tensorflow 2.3 and when trying to load the model in previous versions of TensorFlow. just maintaining the same version for saving and loading would probably solve the issue.

**Comment by MPS-MASTER** [comment]
- just change 
- from keras.models import load_model
- to
- from tensorflow.keras.models import load_model

- then 
- model = load_model('model.h5', compile = False)

**Comment by katejarne** [comment]
Thank you, the last thing works fine!

**Comment by MuhammedBuyukkinaci** [comment]
@MPS-MASTER your solution worked like a charm. Thanks.

**Comment by aarcascuerda** [comment]
> * just change
> * from keras.models import load_model
> * to
> * from tensorflow.keras.models import load_model
> * then
> * model = load_model('model.h5', compile = False)

Thanks!

**Comment by MPS-MASTER** [comment]
> > * just change
> > * from keras.models import load_model
> > * to
> > * from tensorflow.keras.models import load_model
> > * then
> > * model = load_model('model.h5', compile = False)
> 
> Thanks! Anybody could explain why this is working though?

>
1.  Fundamentally this is the problem of environment. So you save a model in an environment and you load it to different environment (Ubantu to windows something like that).
2.other thing is Keras is an interface over Tensorflow so better to use Tensorflow instead of Keras(because dependencies are different in different environment related to keras).
3. Every time we load a model by default it compiles(That's a problem because of different environment). If we do compile == False then we are forcing it not to compile.

**Comment by aarcascuerda** [comment]
> > > * just change
> > > * from keras.models import load_model
> > > * to
> > > * from tensorflow.keras.models import load_model
> > > * then
> > > * model = load_model('model.h5', compile = False)
> > 
> > 
> > Thanks! Anybody could explain why this is working though?
> 
> > 
> 
> 1. Fundamentally this is the problem of environment. So you save a model in an environment and you load it to different environment (Ubantu to windows something like that).
>    2.other thing is Keras is an interface over Tensorflow so better to use Tensorflow instead of Keras(because dependencies are different in different environment related to keras).
> 2. Every time we load a model by default it compiles(That's a problem because of different environment). If we do compile == False then we are forcing it not to compile.

Then, would I have problems when using the model?
For me is exactly as u said it. Im training and saving my model locally then uploading to stagging server. Would I better do any tests if I set compile to False?

**Comment by MPS-MASTER** [comment]
No it should works fine. I have used it. Did not get any problem.

**Comment by aarcascuerda** [comment]
> No it should works fine. I have used it. Did not get any problem.

Okay thank you! :+1:

**Comment by enrique-ismael** [comment]
> * solo cambia
> * desde keras.models import load_model
> * a
> * desde tensorflow.keras.models import load_model
> * luego
> * model = load_model ('model.h5', compile = False)

ME SIRVIO PERFECTAMENTE, tenia el problema de cargar el modelo creado en gogle colab en formato h5, 

Quisiera consultarte cuando guardo el mismo modelo pero con extensión "tf", utilizando la forma que recomienda keras: model.save("model") o model.save("model", save_format='tf') ambas sin extensiones ".h5" EN GOOGLE COLAB en ves de guardar el archivo como se hace con la extensión ".h5" SE CREA UNA CARPETA y no tengo idea porque sucede esto (UTILIZARIA LA FORMA ".h5" pero creo mis modelos con la función while y el archivo guardado con la extensión ".h5" pesa demasiado (en algunos casos ya que el while demora mucho en encontrar mi modelo deseado) pesa mas de 1gb).

Quisiera su apoyo, muchas gracias!!!

![archivoooooo](https://user-images.githubusercontent.com/73522640/97277069-048aae80-1806-11eb-8a2f-9072a306f505.png)

**Comment by adityagupta-9900** [comment]
>     * just change
> 
>     * from keras.models import load_model
> 
>     * to
> 
>     * from tensorflow.keras.models import load_model
> 
>     * then
> 
>     * model = load_model('model.h5', compile = False)

This definitely works. Thanks a lot

**Comment by ravindu20191193** [comment]
@MPS-MASTER I love you !

**Comment by kumariko** [comment]
@benedives47 We are checking to see if you still need help on this issue. We recommend that you upgrade to 2.6 which is latest stable version of TF and let us know if the issue still persists in newer versions. Thanks!
