### ISSUE TITLE
Error using cifar10

### ISSUE THREAD

**Issue by irlydontknowastaken** [keras-team/keras#14043]
**System information**  
- Have I written custom code (as opposed to using example directory):  
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Windows 10
- TensorFlow backend (yes / no):  Yes
- TensorFlow version:  2.2.0
- Keras version:  2.3.1
- Python version:  Python 3.6.5
- CUDA/cuDNN version:  IDK what this is and I have intel gpu so 
- GPU model and memory:  intel uhd 630 mobile, 8gb

**Describe the current behavior**  
Its just spitting out errors
**Describe the expected behavior**  
printing root arrays
**Code to reproduce the issue**  
```
from keras.datasets import cifar10
(train_images, train_labels), (test_images, test_labels) = cifar10.load_data()
print(train_images[0])
``
`**Other info / logs**  
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.  
Traceback (most recent call last):
  File "C:/Users/Jonathan/Desktop/ik right/Python/Demo/main.py", line 3, in <module>
    (train_images, train_labels), (test_images, test_labels) = cifar10.load_data()
  File "C:\Users\Jonathan\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\datasets\cifar10.py", line 32, in load_data
    y_train[(i - 1) * 10000: i * 10000]) = load_batch(fpath)
  File "C:\Users\Jonathan\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\datasets\cifar.py", line 23, in load_batch
    with open(fpath, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Jonathan\\.keras\\datasets\\cifar-10-batches-py\\data_batch_1'

**Comment by irlydontknowastaken** [comment]
well i messed up with the error bit but you know what I mean

**Comment by Ankuraxz** [comment]
I think I can help, let me look into it. Please Ensure Keras is installed Correctly

**Comment by Ankuraxz** [comment]
screenshot for reference:-- https://drive.google.com/file/d/1OPT-S84oSOCdRSAwlWgQjGB-KiU7jDo1/view?usp=sharing

Also Since you use tf 2, I would recommend that you use tenserflow.keras.datasets instead
Hope I could help.
Comment back if the error persisits/ or issue is resolved
