### ISSUE TITLE
Custom Attention Layer using in Keras

### ISSUE THREAD

**Issue by hassancpu** [keras-team/keras#14058]
I want to create a custom attention layer that for input at any time this layer returns the weighted sum of inputs at all times.

For Example, I want that input tensor with shape [32,100,2048] goes to layer and I get the tensor with the shape [32,100,2048]. I wrote the Layer as follow:

import tensorflow as tf

from keras.layers import Layer, Dense, Lambda

#or

from tensorflow.keras.layers import Layer, Dense, Lambda

class Attention(Layer):
    
  def __init__(self, units_att):
      
     self.units_att = units_att
     self.W = Dense(units_att)
     self.V = Dense(1)
     super().__init__()

  def __call__(self, values):
    
      t = tf.constant(0, dtype= tf.int32)    
      time_steps = tf.shape(values)[1]
      initial_outputs = tf.TensorArray(dtype=tf.float32, size=time_steps, element_shape= (None, 2048))
      initial_att =  tf.TensorArray(dtype=tf.float32, size=time_steps)
      
      def should_continue(t, *args):
          return t < time_steps

      def iteration(t, x, outputs, atts):
          
        score = self.V(tf.nn.tanh(self.W(x)))

        # attention_weights shape == (batch_size, time_step, 1)
        attention_weights = tf.nn.softmax(score, axis=1)
    
        # context_vector shape after sum == (batch_size, hidden_size)
        context_vector = attention_weights * x
        context_vector = tf.reduce_sum(context_vector, axis=1)
        
        outputs = outputs.write(t, context_vector)
        atts = atts.write(t, attention_weights)
        
        return t + 1, x, outputs, atts
    
      t, values, outputs, atts = Lambda( lambda x: tf.while_loop(should_continue, iteration,
                                  [t, x, initial_outputs, initial_att]))(values)
      
      outputs = outputs.stack()
      outputs = tf.transpose(outputs, [1,0,2])
      outputs.set_shape(values.shape)
      
      atts = atts.stack()
      atts = tf.squeeze(atts, -1)
      atts = tf.transpose(atts, [1,0,2])
      atts.set_shape([values.shape[0], values.shape[1],
                      values.shape[1]])
      return t, values, outputs, atts

values = tf.constant(2, shape= [32, 100, 2048], dtype= tf.float32)

attention_layer = Attention(50)
t, values, outputs, atts = attention_layer(values) #AttributeError: 'tuple' object has no attribute 'shape'.
I use tf 1.14 and keras 2.3.1

Thanks for any help...

**Comment by tilakrayal** [comment]
@hassancpu ,
Can you please try the latest versions of tf and keras and let us know if the issue still persists.Thanks!
