### ISSUE TITLE
numpy error

### ISSUE THREAD

**Issue by kk0186** [keras-team/keras#14052]
I wrote a code like this:

> for i in range(60, len(train_data)):
>   x_train.append(train_data[i-60:i, 0])

but then it keep return an error message of " x_train.append(train_data[i-60:i, 0])
AttributeError: 'numpy.ndarray' object has no attribute 'append'"

anyone can help to see any problem in there? thank you

**Comment by theo258** [comment]
Please show how you initialize `x_train` before.

**Comment by Hemanthkumar2112** [comment]
try to initialize x_train variable as a **list** 
like this  
```
x_train =[] 
for i in range(60, len(train_data)):
    x_train.append(train_data[i-60:i, 0])
x_train = np.asarray(x_train)
```

**Comment by kk0186** [comment]
my coding is like this

x_train = []
y_train = []

for i in range(60, len(train_data)):
 
  x_train.append(train_data[i-60:i, 0])
  y_train.append(train_data[i, 0])
  if i <= 60:
    print(x_train)
    print(y_train)
  
    x_train, y_train = np.array(x_train), np.array(y_train)

and it give me this error:

  File "C:\Users\user\.spyder-py3\stock prediction.py", line 46, in <module>
    x_train.append(train_data[i-60:i, 0])

AttributeError: 'numpy.ndarray' object has no attribute 'append'

**Comment by Palashio** [comment]
use `np.append` or `np.concatenate` instead.

**Comment by sushreebarsa** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
