### ISSUE TITLE
"Using X backend." printed many many times to stdout

### ISSUE THREAD

**Issue by antoinecarme** [keras-team/keras#14053]
Hi,

This is a request to remove an initial message that is printed to stdout that says "the current backend is ...".

https://github.com/keras-team/keras/blob/7a39b6c62d43c25472b2c2476bd2a8983ae4f682/keras/backend/load_backend.py#L89

The following code prints the same message "Using TensorFlow backend" **48 times** on my terminal:

```Python
def do_something_with_keras(arg):
    import keras
    print(keras.__version__)

import multiprocessing as mp
lPool = mp.Pool(processes = 48)
lPool.map(do_something_with_keras, list(range(48)))
```

I am using Keras version 2.3.1 (and on master branch from github cloned a few hours ago), Tensorflow 1.15.0 and Python 3.8.3 on Debian GNU Linux.

This message is annoying for some of tensorflow users as mentioned in the following issues :

1. "Using X backend." always printed to stdout #1406
   In 2016. @raindeer filed this issue and mentioned that this a bad practice to have a terminal side effect in a library
   
	https://github.com/keras-team/keras/issues/1406#issuecomment-169103948_

2. Keras backend package uses a print call at initialisation time. #11332
   In 2018,  @sarusso filed this and mentioned it a real nbad design to print stuff in libraries ( amen ) and consider it as a serious issue ( amen ).

       https://github.com/keras-team/keras/issues/11332

3. Some people tried to fix this , made some effort to write the necessary code. add clean logging, and the fix was rejected. Pull request by @sarusso

     https://github.com/keras-team/keras/pull/11336

4. Keras author is aware of this issue. Citation : 

Using TensorFlow backend" is more of a reminder than a debug message. You're using Keras, and that means you're using TensorFlow (resp. another backend). **It's branding, in a way**.

        https://github.com/keras-team/keras/pull/11336#issuecomment-429113707

Keras is a Google product after all.

5. Using ... eeuh ... what ? ... Google, it is easy to see some discussions about this same issue and Keras users are sharing workarounds. This one is from 2018

      https://stackoverflow.com/questions/51456842/how-do-i-stop-keras-showing-using-xxx-backend

I come from a country ( France ) where democracy is still a good practice, what about a vote / referendum among Keras users to keep or remove this message ? May be a political solution works after all.

One can see this a troll or better as a reminder for a long-awaited fix from a very happy Keras user. I prefer the last one, and will be glad to see someone else file a similar issue in 2021 or 2022 !!!

**Comment by jvishnuvardhan** [comment]
@antoinecarme This is a stale issue.

Starting `TF2.6`, keras only supports single backend (Tensorflow). Please update your version to recent keras so that you can use improved functionality.

If you notice any of the above mentioned `stdout`, please share a standalone code to reproduce the issue. Thanks!
