### ISSUE TITLE
Update custom layer arguments during training and testing with callbacks in Keras 

### ISSUE THREAD

**Issue by KTTrev** [keras-team/keras#14068]
I've implemented a CNN in which I've added a customized layer. However, this layer contains other data that need to be changed as the images fed in the network change. That's why I need to update these data during training and testing. I've tried to use Callbacks, but I don't know how to update a layer with it. Please, do you have any solution for that? Thanks in advance for your help.

**Comment by AniketSawale** [comment]
Can you post the screenshot of your code? Seem I got confused.

**Comment by KTTrev** [comment]
> 
> 
> Can you post the screenshot of your code? Seem I got confused.
Here is screenshot of the customized layer:
![image](https://user-images.githubusercontent.com/47731576/83454221-2c930300-a45c-11ea-864c-045ab02df990.png)

Now I want to use the following CNN model, such that one image going through the network should use the corresponding values of a and b (since they are given as a list). Basically, if I have a dataset of 50 images, I will also have a list of **a** with length 50, the same with **b**. 
![image](https://user-images.githubusercontent.com/47731576/83455132-a8417f80-a45d-11ea-8bcd-cfe0e44b193a.png)
 My idea is to use the following customized Callback during training, and testing, but it seems not to work.
![image](https://user-images.githubusercontent.com/47731576/83455312-fd7d9100-a45d-11ea-9b24-c24f9235abae.png)
