### ISSUE TITLE
Error While Implementing UNet in Sequential Mode

### ISSUE THREAD

**Issue by bhomaidan1990** [keras-team/keras#14088]
I do like to build the basic **UNet** Model in Keras with Sequential model, using simple modular functions for DownSampling path, and UpSampling path.

I tried to code it as you can see, but I'm getting the **Error**:
```
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Seq_UNet.py", line 56, in <module>
    model = UNet(128,128,1)
  File "C:\Users\User\Desktop\Seq_UNet.py", line 42, in UNet
    x6 = ConvTransposeBlock(128,x4.layer[3])(x5)
AttributeError: 'Tensor' object has no attribute 'layer'
```
How Can I get the output of the Sequential model at specific layer?
```
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2' 
import keras

def ConvBlock(num_features):
    model = keras.Sequential([
        keras.layers.Conv2D(num_features,(3,3),activation='relu',kernel_initializer='he_normal', padding='same'),
        keras.layers.BatchNormalization(epsilon=1e-06,  momentum=0.9, weights=None),
        keras.layers.Dropout(0.1),
        keras.layers.Conv2D(num_features,(3,3),activation='relu',kernel_initializer='he_normal', padding='same'),
        keras.layers.MaxPooling2D((2,2)) ])
    return model

def ConvTransposeBlock(num_features, layer):
    model = keras.Sequential([
        keras.layers.Conv2DTranspose(num_features,(2,2),strides=(2,2),padding='same'),
        keras.layers.concatenate([model.layer[0],layer]), # The past layer (model.layer[0])
        keras.layers.Conv2D(num_features,(3,3),activation='relu',kernel_initializer='he_normal', padding='same'),
        keras.layers.BatchNormalization(epsilon=1e-06,  momentum=0.9, weights=None),
        keras.layers.Dropout(0.2),
        keras.layers.Conv2D(num_features,(3,3),activation='relu',kernel_initializer='he_normal', padding='same') ])
    return model 

# Initialization
IMG_Width  = 128
IMG_Height = 128
IMG_Channels = 1

# Model
def UNet(IMG_Width=IMG_Width, IMG_Height=IMG_Height,IMG_Channels=IMG_Channels):
    # Input Layer
    inputs = keras.layers.Input((IMG_Width,IMG_Height,IMG_Channels))
    # Convert integer inputs to floating point
    s = keras.layers.Lambda(lambda x: x / 255)(inputs) 
    # Contraction path:
    x1 = ConvBlock(16)(s)
    x2 = ConvBlock(32)(x1)
    x3 = ConvBlock(64)(x2)
    x4 = ConvBlock(128)(x3)
    x5 = ConvBlock(256)(x4)
    # Expansion path:
    x6 = ConvTransposeBlock(128,x4.layer[3])(x5)
    x7 = ConvTransposeBlock( 64,x3.layer[3])(x6)
    x8 = ConvTransposeBlock( 32,x2.layer[3])(x7)
    x9 = ConvTransposeBlock( 16,x1.layer[3])(x8)

    outputs = keras.layers.Conv2D(1,(1,1), activation='sigmoid')(x9)

    model = keras.Model(inputs=[inputs],outputs=[outputs])

    optimizer = keras.optimizers.Adam(lr=1e-4)
    model.compile(optimizer=optimizer,loss=bce_dice_loss,metrics=['accuracy'])

    return model

model = UNet(128,128,1)
```

**Comment by ZohebAbai** [comment]
Hi,

As the models, ConvBlock and ConvTransposeBlock have not been build yet (not yet defined input and outputs), I don't think they can be called by their layers or even layer names (At least I think so).

If you are using sequential layers, just use them as it is within 'def', using variable names. Don't use 'model = keras.Sequential([...]) return model'. And Concatenate them by their variables.

Instead of sequential building, I would suggest you to use a functional build mode, if you want to use them as functions. Ex:
def ConcatBlock(x, growth_rate, name):
    x1 = keras.layers.Conv2D(16 * growth_rate,(3,3),activation='relu',kernel_initializer='he_normal', padding='same', name=name + '_1_conv')(x)
    x1 = keras.layers.BatchNormalization(epsilon=1e-06,  momentum=0.9, weights=None, , name=name + '_bn')(x1)
    x1 = keras.layers.Conv2D(16 * growth_rate,(3,3),activation='relu',kernel_initializer='he_normal', padding='same', name=name + '_2_conv')(x1)
    x = keras.layers.Concatenate(name=name + '_concat')([x, x1])
  return x

**Comment by bhomaidan1990** [comment]
@ZohebAbai 
> 
> 
> Hi,
> 
> As the models, ConvBlock and ConvTransposeBlock have not been build yet (not yet defined input and outputs), I don't think they can be called by their layers or even layer names (At least I think so).
> 
> If you are using sequential layers, just use them as it is within 'def', using variable names. No need for using 'model = keras.Sequential([...]) return model' inside a separate function. And Concatenate them by their variables.
> 
> Instead of sequential building, I would suggest you to use a functional build mode, if you want to use them as functions. Ex:
> def ConcatBlock(x, growth_rate, name):
> x1 = keras.layers.Conv2D(16 * growth_rate,(3,3),activation='relu',kernel_initializer='he_normal', padding='same', name=name + '_1_conv')(x)
> x1 = keras.layers.BatchNormalization(epsilon=1e-06, momentum=0.9, weights=None, , name=name + '_bn')(x1)
> x1 = keras.layers.Conv2D(16 * growth_rate,(3,3),activation='relu',kernel_initializer='he_normal', padding='same', name=name + '_2_conv')(x1)
> x = keras.layers.Concatenate(name=name + '_concat')([x, x1])
> return x

My purpose is to use Sequential and to build modular code, and layers can be called from the Sequential, I have checked that.

**Comment by Shubhranshu-Malhotra** [comment]
Hey did you get how to build it using Sequential? Actually, I am trying to do the same thing and am stuck. Making it using Functional is simple but I just wanna see if it is possible building it using Sequential or not.

**Comment by jvishnuvardhan** [comment]
@bhomaidan1990 Sorry for the late response. Is this still an issue for you?

As mentioned by @ZohebAbai , before building layer or model, you cannot use them or call a layer.

```
    # The following line breaks with the same error
    print(x4.layer[3])
```

Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/d43a64a5bbdae9fffdd0b2a9baf65055/untitled1102.ipynb). Thanks!

**Comment by bhomaidan1990** [comment]
@jvishnuvardhan I hope that there is a way around to solve it with sequential so the code becomes more modular and explicit, otherwise it looks like a shortage in the sequential!
