### ISSUE TITLE
R Terminal Killed 9

### ISSUE THREAD

**Issue by davezes** [keras-team/keras#14080]
Please consider this a very low priority -- at least for my sake.
Unlikely an actual keras or tf issue.  Perhaps more likely R 4.0 or Catalina issue ??

In RStudio:
> keras:::keras_version()
[1] ‘2.3.0’

In Terminal
> keras:::keras_version()
Killed 9

[See here](http://davezes.com/keras_002.png)
or attached PNG

MacOSX 10.15.5

- R version:  4.0.0
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  1.13.1
- Keras version:  2.3.0
- Python version:  3.7.7
- CUDA/cuDNN version:  none
- GPU model and memory:  none

Thank you.

![keras_002](https://user-images.githubusercontent.com/7951638/83341693-24d83080-a29b-11ea-91f9-cd4c5c87325e.png)

**Comment by davezes** [comment]
Fixed.

First, note that issuing

$ codesign --verify --verbose   /Users/davezes/Library/r-miniconda/envs/r-reticulate/lib/libmkl_intel_thread.dylib

in bash returns

/Users/davezes/Library/r-miniconda/envs/r-reticulate/lib/libmkl_intel_thread.dylib: invalid signature (code or signature have been modified)



Step 1:
Move 
r-miniconda
out of ~/Library

Step 2:
Start R session in Terminal:
> library(reticulate)
> install_miniconda(path = miniconda_path(), update = TRUE, force = FALSE)
> install_keras()


Restart R

Interestingly, even still issuing

> keras:::keras_version()

Returns
"Error:"

(nothing after the colon)

But re-issuing

> keras:::keras_version()

a second time yields the sought

2.3.0


Lastly, note that now issuing

$ codesign --verify --verbose   /Users/davezes/Library/r-miniconda/envs/r-reticulate/lib/libmkl_intel_thread.dylib

in bash returns

/Users/davezes/Library/r-miniconda/envs/r-reticulate/lib/libmkl_intel_thread.dylib: No such file or directory


Thank you!

~DZ

**Comment by leedrake5** [comment]
Mine is a bit more apocalyptic:

```
> keras:::keras_version()
Killed: 9
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

**Comment by davezes** [comment]
Oh man,
Something forked before Killed 9.
You running Catalina?

**Comment by kumariko** [comment]
@davezes We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.6 which is latest stable version of TF and let us know if the issue still persists in newer versions. Thanks!

**Comment by jvishnuvardhan** [comment]
@davezes Sorry for late response. This is a stale issue.

I am not sure about `R` based keras package. This repo is based on `python`.

Can you please try to post this question in [TF Forum](https://discuss.tensorflow.org/tags) where there are several user supporting each other. You might get faster answer there. Thanks!
