### ISSUE TITLE
Error tensorflow:Model inputs must come from `tf.keras.Input`

### ISSUE THREAD

**Issue by kouroshD** [keras-team/keras#14082]
Hi,
I have written a custom code for training Deep RNN network, but there was an error in it. I managed to fix the problem, but still I do not understand why there was that error. In the following I provide the description of the problem, and the error log.

**Describe the current behavior**  
if I have following line of code:

```
X = Input(shape=(self.Tx, self.n_x))
a0 = Input(shape=(self.n_a,), name='a0')
c0 = Input(shape=(self.n_a,), name='c0')

x = reshapor(x)
a0, _, c0 = LSTM_cell(inputs=x, initial_state=[a0, c0])
out = densor(a0)
outputs = outputs + [out]
x = Lambda(lambda z: z)(out)

model = Model(inputs=[X, a0, c0], outputs=outputs)
```

I will through the following error:

```
WARNING:tensorflow:Model inputs must come from `tf.keras.Input` (thus holding past layer metadata), they cannot be the output of a previous non-Input layer. Here, a tensor specified as input to "model" was not an Input tensor, it was generated by layer lstm_1_.
Note that input tensors are instantiated via `tensor = tf.keras.Input(shape)`.
The tensor that caused the issue was: lstm_/Identity:0
WARNING:tensorflow:Model inputs must come from `tf.keras.Input` (thus holding past layer metadata), they cannot be the output of a previous non-Input layer. Here, a tensor specified as input to "model" was not an Input tensor, it was generated by layer lstm_1_.
Note that input tensors are instantiated via `tensor = tf.keras.Input(shape)`.
The tensor that caused the issue was: lstm_/Identity_2:0
Traceback (most recent call last):
```

Basically, it is complaining that the $a0$ and $c0$ in the last line when passed to $inputs$ is not of type `tf.keras.Input` and it is the output of `LSTM_cell` which is a LSTM layer! 

**Describe the expected behavior**  
I expect that even if $a0 , c0$  are passed to `LSTM_cell`, it should keep its type as `tf.keras.Input`, and there should not exist this error.

**Describe the fix**  
I have copied the $a0 , c0$ into $a , c$, and the problem is fixed as follows:
However, we should take into account that the copy in python is by reference, so, the error should exist still, but instead it has been fixed!

```
X = Input(shape=(self.Tx, self.n_x))
a0 = Input(shape=(self.n_a,), name='a0')
c0 = Input(shape=(self.n_a,), name='c0')
a = a0
c = c0

x = self.reshapor(x)
a, _, c = self.LSTM_cell(inputs=x, initial_state=[a, c])
out = self.densor(a)
outputs = outputs + [out]
x = Lambda(lambda z: z)(out)

model = Model(inputs=[X, a0, c0], outputs=outputs)
```

**System information**  
- Have I written custom code (as opposed to using example directory): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Mojave 10.14.6
- TensorFlow backend (yes / no): yes
- TensorFlow version: 2.1.0
- Keras version: 2.3.1
- Python version: 3.7
- CUDA/cuDNN version: -
- GPU model and memory: -, 16GB

**Comment by AlieinApril** [comment]
thx a lot, i met same problem. is that a bug?

**Comment by kouroshD** [comment]
> thx a lot, i met same problem. is that a bug?

I am not sure if it is a bug or how it is implemented in the backend, but similar to your observation, this is the behavior which is not expected.

**Comment by sushreebarsa** [comment]
@kouroshD 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by kouroshD** [comment]
> @kouroshD
> In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

thank you @sushreebarsa  for your response. I have updated my implementations, and I do not face such problem. Please, feel free to close this issue.
