### ISSUE TITLE
expected PREDICTIONS to have 4 dimensions, but got array with shape (20, 131)

### ISSUE THREAD

**Issue by somdipdey** [keras-team/keras#14098]
I am trying to train pre-trained MobileNet version 2 model on Fruits-360 dataset ([https://github.com/Horea94/Fruit-Images-Dataset](https://github.com/Horea94/Fruit-Images-Dataset)) by fine-tuning the model with the classes provided in the dataset. While training my custom model it is throwing the following error for **model.fit_generator()**:

> ValueError: Error when checking target: expected PREDICTIONS to have 4 dimensions, but got array with shape (20, 131)

Any idea where I might be going wrong and how I can fix it?

My python code containing the fine-tuned model as follows:

```
import os
import glob
import sys

import tensorflow as tf
from tensorflow import keras

from keras.preprocessing import image
from keras.applications.mobilenet_v2 import MobileNetV2
from keras.models import Model
from keras.optimizers import SGD
from keras.applications.mobilenet_v2 import preprocess_input, decode_predictions
import numpy as np
from keras.preprocessing.image import ImageDataGenerator
from keras.callbacks import ModelCheckpoint, EarlyStopping, CSVLogger

import PIL
from PIL import Image
import requests
from io import BytesIO
from keras.layers import Dense, GlobalAveragePooling2D, GlobalMaxPooling2D, Flatten, Dropout

def list_dirs(path):
    return [os.path.basename(x) for x in filter(
        os.path.isdir, glob.glob(os.path.join(path, '*')))]

labels = list_dirs("Path_to_dataset/fruits-360/Training")
labels.sort()

epochs = 100

# Base directory of raw jpg/png images
base_dir = 'Path_to_dataset/fruits-360'

train_path = os.path.join(base_dir, 'Training')
nb_train_samples = 67692
valid_path = os.path.join(base_dir, 'Test')
nb_val_samples = 22688
test_path = os.path.join(base_dir, 'test-multiple_fruits')

batch_size = 20

train_steps = nb_train_samples // batch_size
valid_steps = nb_val_samples // batch_size

classes = labels

img_width, img_height = 224, 224

train_datagen = ImageDataGenerator(rescale=1. / 255)
val_datagen = ImageDataGenerator(rescale=1. / 255)

train_generator = train_datagen.flow_from_directory(train_path, target_size=(img_width, img_height),
                                                    classes=classes, class_mode='categorical',
                                                    batch_size=batch_size)
val_generator = val_datagen.flow_from_directory(valid_path, target_size=(img_width, img_height),
                                                    classes=classes, class_mode='categorical',
                                                    batch_size=batch_size)

base_model = MobileNetV2(weights='imagenet', include_top=True)

x = base_model.layers[-6].output
predictions = Dense(len(classes), activation='softmax', name='PREDICTIONS')(x)
model = Model(input=base_model.input, outputs=predictions)

for layer in model.layers[:-5]:
    layer.trainable = False

model.compile(optimizer=SGD(lr=0.0001, momentum=0.9),
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])
model.summary()

model.fit_generator(train_generator, epochs= epochs,
                                      steps_per_epoch=train_steps,
                                      validation_data = val_generator,
                                      validation_steps= valid_steps)
```

**Comment by ZohebAbai** [comment]
Hi,

Can you try the following:

1. **base_model = MobileNetV2(weights='imagenet', include_top=False)**
instead of 
base_model = MobileNetV2(weights='imagenet', include_top=True)

2. **for layer in base_model.layers:**
            **layer.trainable = False**
instead of 
for layer in model.layers[:-5]:
    layer.trainable = False

3. After the above write, 
**last_layer = base_model.get_layer('out_relu')**
**x = layers.GlobalAveragePooling2D()(last_layer)**
instead of 
x = base_model.layers[-6].output

and the rest follows as written
predictions = Dense(len(classes), activation='softmax', name='PREDICTIONS')(x)
model = Model(input=base_model.input, outputs=predictions)

model.compile(optimizer=SGD(lr=0.0001, momentum=0.9),
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])
model.summary()

model.fit_generator(train_generator, epochs= epochs,
                                      steps_per_epoch=train_steps,
                                      validation_data = val_generator,
                                      validation_steps= valid_steps)

Let us know if this doesn't work.

**Comment by somdipdey** [comment]
Thank you for your reply. The suggestion didn't work. The updated code is as follows:

base_model = MobileNetV2(weights='imagenet', include_top=False)

last_layer = base_model.get_layer('out_relu')
x = GlobalAveragePooling2D()(last_layer)

predictions = Dense(len(classes), activation='softmax', name='PREDICTIONS')(x)
model = Model(input=base_model.input, outputs=predictions)

for layer in base_model.layers:
    layer.trainable = False

model.compile(optimizer=SGD(lr=0.0001, momentum=0.9),
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])
model.summary()

model.fit_generator(train_generator, epochs= epochs,
                                      steps_per_epoch=train_steps,
                                      validation_data = val_generator,
                                      validation_steps= valid_steps,
                                      callbacks=callbacks_list)

----------------------------------------

However, when I execute the above code it throws the following error:

ValueError: Layer global_average_pooling2d_1 was called with an input that isn't a symbolic tensor. Rec
eived type: <class 'keras.layers.advanced_activations.ReLU'>. Full input: [<keras.layers.advanced_activ
ations.ReLU object at 0x13661fcd0>]. All inputs to the layer should be tensors.

**Comment by ZohebAbai** [comment]
Hi,

Did you put these lines of code
for layer in base_model.layers:
layer.trainable = False
before
last_layer = base_model.get_layer('out_relu')
x = GlobalAveragePooling2D()(last_layer)
?
If not, please put that there (as I mentioned) and let us know the results. 
If already, let us know.

**Comment by gadagashwini** [comment]
@somdipdey,

```
base_model = keras.applications.MobileNetV2(include_top=True,weights='imagenet')
x = base_model.layers[-6].output
x.shape
>>TensorShape([None, 7, 7, 320])
```

Output of the base_model is not compatible with expected shape of `keras.layers.Dense(len(classes), activation='softmax', name='PREDICTIONS')`.

```
flatten = keras.layers.Flatten(name='FLATTEN')(x)
flatten.shape
>>TensorShape([None, 15680])
predictions = keras.layers.Dense(len(classes), activation='softmax', name='PREDICTIONS')(flatten)

```
