### ISSUE TITLE
Model parallelism OOM error on unused GPU

### ISSUE THREAD

**Issue by ririya** [keras-team/keras#14093]
I'm trying to train a large model on 4 GPU's. The model is so big that it doesn't fit in a single gpu. So what I did was to place different layers into different GPU's. It works for small batch sizes, however for large batch sizes GPU 0 always cracks first with an OOM error. I did a test and removed GPU 0 from the model and before calling the fit function, it shows no usage (see image). However when the model starts loading the batches, GPU0 is fully used with 15488 MiB and still results in the OOM error. Can anyone tell me why this happens and if there's a way to overcome this issue?

keras 2.2.5 tensorflow 1.15

<img width="591" alt="Screen Shot 2020-06-04 at 2 22 27 PM" src="https://user-images.githubusercontent.com/23408930/83811527-d4801a80-a66e-11ea-94d2-1e98725fe591.png">

<img width="1652" alt="Screen Shot 2020-06-04 at 2 30 43 PM" src="https://user-images.githubusercontent.com/23408930/83812280-1b224480-a670-11ea-8673-9cf9d49a9487.png">

**Comment by sushreebarsa** [comment]
@ririya 
We see that you are using old version of tensorflow 1.x  which is not actively supported, we recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions .Batch size is often specified per GPU ,please refer [this](https://www.tensorflow.org/guide/distributed_training) link.
Please open a new issue in case you face any errors with detail information, we will get you the right help .Hence moving this to closed status.Thanks!
