### ISSUE TITLE
Are there any source than I can use to detect handwritten digit on webcam?

### ISSUE THREAD

**Issue by MuongKimhong** [keras-team/keras#14092]
Hello everyone! I have a question. Are there any source that I can use for handwritten digit detection on webcam? I already trained the model with mnist dataset but now I want to apply that model into real time detection example like it will draw the bounding box around the digit that will be written by my hand on paper.

**Comment by goelharshit562** [comment]
you must watch the given link for applying model :
**https://www.youtube.com/watch?v=6yqMovGDSsE&list=LL&index=5&t=0s**
channel name (Tech Wizard)
