### ISSUE TITLE
model.predict returns 'TypeError: data type not understood'

### ISSUE THREAD

**Issue by DemiTownson** [keras-team/keras#14112]
Hello.
I'm trying to implement a simple LSTM model:

model = Sequential()
model.add(LSTM(100, activation='relu', input_shape=(x_train.shape[1], x_train.shape[2])))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
history = model.fit(x_train, y_train, epochs=500, verbose=0, validation_data=(x_test, y_test))

Everything works fine until I come to use model.predict, with which I get the error in the title.  Apparently I am not the only one to have this problem, but the solution on stackoverflow is to uninstall and reinstall Anaconda, which I'd rather avoid. 

https://stackoverflow.com/questions/54903852/predict-with-keras-fails-due-to-faulty-environment-setup

Is there any other solution to this bug?
Thanks

**Comment by IgBell** [comment]
Use Google Colab

**Comment by sushreebarsa** [comment]
@DemiTownson In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by sushreebarsa** [comment]
Closing this issue due to lack of recent activity .Please feel free to reopen if you still have concern.Thanks!
