### ISSUE TITLE
Latest Keras version is not compatible with Python 2.7 anymore

### ISSUE THREAD

**Issue by Lothiraldan** [keras-team/keras#14128]
Latest Keras version requires tensorflow >= 2.2.0 but tensorflow 2.2.0 only has wheels for Python 3.5+. This means that trying to install keras in Python 2.7 or Python 3.4 leads to the following traceback:

```
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting keras
  Using cached Keras-2.4.0-py2.py3-none-any.whl (170 kB)
Collecting scipy>=0.14
  Using cached scipy-1.2.3-cp27-cp27mu-manylinux1_x86_64.whl (24.8 MB)
Processing /home/lothiraldan/.cache/pip/wheels/d1/d5/a0/3c27cdc8b0209c5fc1385afeee936cf8a71e13d885388b4be2/PyYAML-5.3.1-cp27-cp27mu-linux_x86_64.whl
Collecting numpy>=1.9.1
  Using cached numpy-1.16.6-cp27-cp27mu-manylinux1_x86_64.whl (17.0 MB)
ERROR: Could not find a version that satisfies the requirement tensorflow>=2.2.0 (from keras) (from versions: 0.12.0rc0, 0.12.0rc1, 0.12.0, 0.12.1, 1.0.0, 1.0.1, 1.1.0rc0, 1.1.0rc1, 1.1.0rc2, 1.1.0, 1.2.0rc0, 1.2.0rc1, 1.2.0rc2, 1.2.0, 1.2.1, 1.3.0rc0, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.4.0rc0, 1.4.0rc1, 1.4.0, 1.4.1, 1.5.0rc0, 1.5.0rc1, 1.5.0, 1.5.1, 1.6.0rc0, 1.6.0rc1, 1.6.0, 1.7.0rc0, 1.7.0rc1, 1.7.0, 1.7.1, 1.8.0rc0, 1.8.0rc1, 1.8.0, 1.9.0rc0, 1.9.0rc1, 1.9.0rc2, 1.9.0, 1.10.0rc0, 1.10.0rc1, 1.10.0, 1.10.1, 1.11.0rc0, 1.11.0rc1, 1.11.0rc2, 1.11.0, 1.12.0rc0, 1.12.0rc1, 1.12.0rc2, 1.12.0, 1.12.2, 1.12.3, 1.13.0rc0, 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 1.15.0rc0, 1.15.0rc1, 1.15.0rc2, 1.15.0rc3, 1.15.0, 2.0.0a0, 2.0.0b0, 2.0.0b1, 2.0.0rc0, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.1.0rc0, 2.1.0rc1, 2.1.0rc2, 2.1.0)
ERROR: No matching distribution found for tensorflow>=2.2.0 (from keras)
```

If that was planned, I would suggest to update the setup.py file with the correct https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires so pip can takes Keras 2.3.1 on incompatible Python versions.

I would also recommend yanking the release 2.4.0 as pip will try to get the 2.4.0 release if a 2.4.1 is released with the correct metadata.

**Comment by fchollet** [comment]
Python 2.7 has reached end of life over 6 months ago. If you are using it, it means you have a legacy codebase. For any legacy codebase, you should pin all dependencies to a specific version that is known to work. In this case, pin your Keras dependency to 2.3.1.

**Comment by Lothiraldan** [comment]
Latest keras version removed the Python 2.7 compatibility from Readme so I'm good. I would still recommend adding the `python_requires` field to setup.py and mark the wheel as compatible only with Python 3.

**Comment by yoddaa** [comment]
i used python 3.6.6 with keras worked well for facial recognition then upgraded to 3.7 got compatibility issues
