### ISSUE TITLE
Make keras.callbacks.Callback and tensorflow.keras.callbacks.Callback mutually compatible

### ISSUE THREAD

**Issue by PiotrJander** [keras-team/keras#14125]
`tensorflow.keras.callbacks.Callback` has private methods [`_implements_train_batch_hooks`](https://github.com/tensorflow/tensorflow/blob/2b96f3662bd776e277f86997659e61046b56c315/tensorflow/python/keras/callbacks.py#L739) etc which are [called](https://github.com/tensorflow/tensorflow/blob/2b96f3662bd776e277f86997659e61046b56c315/tensorflow/python/keras/callbacks.py#L328) e.g. when the callback is used with `tensorflow.keras.models.Model.fit`.

`keras.callbacks.Callback` provides no such methods and so using it with e.g. `tensorflow.keras.models.Model.fit` results in `AttributeError: 'SomeClassExtendingCallback' object has no attribute '_implements_train_batch_hooks'`.

If those two versions of Keras aim to be compatible, then this should be fixed.

**Comment by jvishnuvardhan** [comment]
@PiotrJander This is a stale issue. 

Recently `TF2.6` stable version released. Starting `TF2.6`, everything should match. Can you please check and let us know whether there is any discrepancy. If you see any discrepancy, can you please share a simple standalone code to reproduce the issue? Thanks!

If this was resolved with recent TF version, then feel free to close the issue. thanks!

**Comment by jvishnuvardhan** [comment]
I think this was resolved with recent TF versions. I am closing this issue. Feel free to reopen if I am mistaken. Thanks!
