### ISSUE TITLE
what is causing error in Callback?? 

### ISSUE THREAD

**Issue by aquib1011** [keras-team/keras#14137]
Code:

```
model.compile(optimizer = optimizer , loss = 'mean squared error', metrics = ['acc'])
model.summary()
checkpoint = ModelCheckpoint('model_weight.h5' , monitor = 'val_loss' , 
                            save_weight_only = True , mode = 'auto' , verbose= 1)
callbacks = [PlotLossesCallback() , checkpoint]
batch_size  = 32
history = model.fit( 
        datagen_train.flow(x_train , y_train , batch_size = batch_size , shuffle = True),
        steps_per_epoch = len (x_train)//batch_size,
        validation_data = datagen_val.flow(x_val,y_val, batch_size = batch_size , shuffle = True),
        validation_steps =len (x_val) // batch_size,
        epochs = 12 ,
        callbacks = callbacks)
```

Error Output :

KeyError                                  Traceback (most recent call last)
<ipython-input-21-3c391780894b> in <module>
      9         validation_steps =len (x_val) // batch_size,
     10         epochs = 12 ,
---> 11         callbacks = callbacks)

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in _method_wrapper(self, *args, **kwargs)
     64   def _method_wrapper(self, *args, **kwargs):
     65     if not self._in_multi_worker_mode():  # pylint: disable=protected-access
---> 66       return method(self, *args, **kwargs)
     67 
     68     # Running inside `run_distribute_coordinator` already.

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
    828       self.stop_training = False
    829       train_function = self.make_train_function()
--> 830       callbacks.on_train_begin()
    831       # Handle fault-tolerance for multi-worker.
    832       # TODO(omalleyt): Fix the ordering issues that mean this has to

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py in on_train_begin(self, logs)
    445     logs = self._process_logs(logs)
    446     for callback in self.callbacks:
--> 447       callback.on_train_begin(logs)
    448 
    449   def on_train_end(self, logs=None):

/opt/conda/lib/python3.7/site-packages/livelossplot/generic_keras.py in on_train_begin(self, logs)
     29 
     30     def on_train_begin(self, logs={}):
---> 31         self.liveplot.set_metrics([metric for metric in self.params['metrics'] if not metric.startswith('val_')])
     32 
     33         # slightly convolved due to model.complie(loss=...) stuff

KeyError: 'metrics'

**Comment by Vincent9797** [comment]
It looks like the issue is in the `on_train_begin()` method in `PlotLossesCallback()`. Could you share the code for the callback and how you instantiated it?
