### ISSUE TITLE
why my prediction model keep giving a different prediction result everytime when I run it?

### ISSUE THREAD

**Issue by kk0186** [keras-team/keras#14130]
I have built a stock prediction model using LSTM.  however, everytime when I run the program, the value of RMSE and the prediction result keep changing ( I did not change any data in the program. It giving out different result everytime when I clicking the run buttom everytime, ) Can anyone let me know what is the reason of it. Thank you very much

**Comment by maaz-bin-asad** [comment]
One of the possible reason being your validation data is changing at every try. Possibly if you are using K Fold cross validations.

**Comment by seriousran** [comment]
isn't it because of random seed?

https://github.com/keras-team/keras/issues/439
