### ISSUE TITLE
 ValueError: could not broadcast input array from shape (256,256,3) into shape (256,256)

### ISSUE THREAD

**Issue by JirasakRomsai** [keras-team/keras#14144]
import matplotlib.pyplot as plt
import matplotlib.image as im
import os, os.path
from os import walk
from matplotlib import image
import numpy as np

def read_nameDir(mypath,nameList):
     for (dirpath, dirnames, filenames) in walk(mypath):
         nameList.extend(dirnames)
         #nameList.extend(filenames)

def count_File(path,NameDir):
    path, dirs, files = next(os.walk(path+NameDir))
    file_count = len(files) 
    return(file_count)

def read_img(path, ListNameImg, Listdata,target):
    for i in range(len(ListNameImg)) :
        num_target=str(i)
        len_file=count_File(path,ListNameImg[i])
        for j in range(len_file):
             num_pic=str(j+1)
             image_train = image.imread(str(path)+ListNameImg[i]+"/"+num_target+" ("+num_pic+").jpg")
             Listdata.append(image_train)
             target.extend([list([eval(num_target)])])

pathDir_train = 'Bra/Bra/Bra'
nameDir_train = []
x_train = []    
read_nameDir(pathDir_train, nameDir_train)
y_train=[]
read_img(pathDir_train,nameDir_train,x_train ,y_train)

x_train=np.asarray(x_train)
y_train=np.asarray(y_train)

**Comment by JirasakRomsai** [comment]
line48  : x_train=np.asarray(x_train)

**Comment by ShamilaNasreen** [comment]
I had a similar problem and solved it . reference:  
[(https://stackoverflow.com/questions/62418108/could-not-broadcast-input-array-from-shape-27839-1-into-shape-27839/62584604#62584604)]

**Comment by sushreebarsa** [comment]
@JirasakRomsai Please check with the above comment and let us know if this is still an issue .Thanks!

**Comment by sushreebarsa** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
