### ISSUE TITLE
5-95% balance in classes trouble with predicting unseen data

### ISSUE THREAD

**Issue by haker88** [keras-team/keras#14141]
Question: how do you train for classifying dataset which has got hugely misbalanced classes ?

I have 230000 rows of data in which about 4% is class=1, for the rest class=0. When I train with whole dataset I get poor prediction accuracy about 10%. I tried taking all samples of class 1(8000 rows) and then 8000 random of class 0. With that dataset of 16000 I get awesome accuracy of 90% which is more than enough for me. BUT when I use that model to predict based on all the other left samples from big set which all of them are 0 I get very bad accuracy. What do I do wrong? I tried weights ( auto and manual) with no luck.

When I try to predict that other set of zeros I use polynomials, scaler, PCA and one hot encoders which are all fitted during training cycle.

**Comment by ShamilaNasreen** [comment]
for imbalance classes try to use other metric like weighted avg macro precision and recall etc.

**Comment by sushreebarsa** [comment]
@haker88 Please try with the above comment and let us know if this is still an issue.Thanks!

**Comment by sushreebarsa** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
