### ISSUE TITLE
Keras Conv2D with extended Batch Shape Incompatible Shapes

### ISSUE THREAD

**Issue by b15h0y** [keras-team/keras#14146]
using the example of keras Conv2D Layer from [here](https://keras.io/api/layers/convolution_layers/convolution2d/)

```
>>> # With extended batch shape [4, 7]:  
>>> input_shape = (4, 7, 28, 28, 3)
>>> x = tf.random.normal(input_shape)
>>> y = tf.keras.layers.Conv2D(
... 2, 3, activation='relu', input_shape=input_shape[2:])(x)
>>> print(y.shape)
(4, 7, 26, 26, 2)
```
yields 
```
ValueError: Input 0 of layer conv2d_11 is incompatible with the layer: expected ndim=4, found ndim=5. Full shape received: [4, 7, 127, 127, 3]
```
My batches are sequences of images captured from different views. you can consider them as videos. my intended shape in the model summary would be `(BS, SEQ, IMG_W ,IMG_H, CH)`

tf version: `2.1.0`

any idea what is the issue?

**Comment by b15h0y** [comment]
It's a documentation issue. the  tf documentation removed this example [tf.keras Conv2D](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Conv2D?fbclid=IwAR3L85fwvYlzHbQDvoBDmqQruOBUWDLidwGlEY3BZUZ-iCXymwkGIGykcPY)

**Comment by Vincent9797** [comment]
`Conv2D` layer expects input in the following shape: **(BS, IMG_W ,IMG_H, CH)**. You have 2 options to make the code work:

1. Capture the same spatial patterns in each frame and then combine the information in the temporal axis in a downstream layer

- Wrap the `Conv2D` layer in a `TimeDistributed` layer
- `y = TimeDistributed(Conv2D(2, 3, activation='relu', input_shape=input_shape[2:]))(x)`

2. Capture the spatial the temporal patterns together

- Replace the `Conv2D` with a `Conv3D` layer
- `y = Conv3D(2, 3, activation='relu', input_shape=input_shape[2:])(x)`

**Comment by jvishnuvardhan** [comment]
@b15h0y Is this still an issue for you? 
I ran the code snippet you shared (which is also present in TF and keras webpages), and i get the same output that is listed on those webpages. [Here](https://colab.research.google.com/gist/jvishnuvardhan/c9076e3ddf827e787d1ff50a62173f6a/untitled1063.ipynb) is a gist for reference. Please note that I ran your code with recent stable `TF2.6` version. Thanks!
