### ISSUE TITLE
WARNING:tensorflow:11 out of the last 11 via using Keras library

### ISSUE THREAD

**Issue by BestSithInEU** [keras-team/keras#14157]
Hello all, I'm getting this warning, I wonder why?

>WARNING:tensorflow:11 out of the last 11 calls to <function Model.make_train_function.<locals>.train_function at 0x0000023D1D542C80> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings is likely due to passing python objects instead of tensors. Also, tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. Please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for more details.

My whole code is [here.](https://github.com/BestSithInEU/Warning)

**Comment by LzyRapx** [comment]
@BestSithInEU Hi, BestSithInEU, did you solved this problem? if solved, would you tell me how you solved it ? Thanks in advance.

**Comment by tilakrayal** [comment]
@BestSithInEU ,
Can you please take a look at this SO [link](https://stackoverflow.com/questions/66271988/warningtensorflow11-out-of-the-last-11-calls-to-triggered-tf-function-retracin) and [issue](https://github.com/tensorflow/tensorflow/issues/38561#issuecomment-629937796) with similar error.It helps.
