### ISSUE TITLE
Save Model not saving the optimizer weights

### ISSUE THREAD

**Issue by Preetesh21** [keras-team/keras#14150]
**Important note:** the development of Keras is currently taking place at [`github.com/TensorFlow/TensorFlow`](https://github.com/tensorflow/tensorflow). Please file your bug report by creating a new issue in the TensorFlow repository.

Please note that multi-backend Keras development has been discontinued. Do not report issues about multi-backend Keras (Keras 2.3.1 and lower), only report issues about the TensorFlow implementation of Keras (tf.keras).
I had tried to save my model using the model.save() function provided by Keras which it did successfully but on loading the model again it failed to load the optimizer which was Adam. I had used trained layers in my model. Any help would be appreciated.
![error](https://user-images.githubusercontent.com/50336851/86742004-6d7ec880-c055-11ea-97de-1f0383e47763.PNG)

**Comment by jvishnuvardhan** [comment]
@Preetesh21 Sorry for the late response. Is this still an issue.

I was able to successfully save and load a simple model that had `adam` optimizer. Please find the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/902b20da18632211ff67489de48d7f43/untitled1048.ipynb).

If you still have a problem saving and loading, then please share a simple standalone code to reproduce the issue. Thanks!
