### ISSUE TITLE
Difference in output when trained using CPU and GPU

### ISSUE THREAD

**Issue by venom551998** [keras-team/keras#14156]
I was training an image segmentation model with TensorFlow and Keras as backend. Firstly I trained the model using GPU(google colab) and the results were good. Later on, I trained the same script/model using CPU the results were awful. I haven't change anything in the script except changing the runtime from CPU to GPU.

**Comment by jvishnuvardhan** [comment]
@venom551998 Sorry for the late response. Is this still an issue.

If it is still an issue, please share a simple standalone code to reproduce the issue. I haven't faced too much discrepancy when trained a identical model on cpu and gpu. Thanks!
