### ISSUE TITLE
Model.fit does not display train progress bar in tensorflow

### ISSUE THREAD

**Issue by HokyungLee** [keras-team/keras#14152]
tensorflow version : 2.2.0
using only cpu
the size of train data : 23928
batch size : 32

`checkpoint = ModelCheckpoint(filename, monitor='val_loss', verbose=1, save_best_only=True, mode='min')
hist = model.fit(train_X, train_Y, epochs = 10, batch_size = 32, validation_data = (val_X, val_Y), callbacks = [checkpoint])`

![image](https://user-images.githubusercontent.com/18568487/86888421-16502500-c135-11ea-9aef-938e688d4c04.png)

in above figure
working just one batch size per one epoch and display not "train on x samples"
additional, not display validation result in train progress bar

**Comment by HokyungLee** [comment]
I missed this issue

**Comment by royarafati** [comment]
hello Sir
I have the same problem. Did you find any explanation for this issue?

**Comment by RubenB747** [comment]
No one with a solution for that?
