### ISSUE TITLE
Travis CI: "No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself."

### ISSUE THREAD

**Issue by yousss** [keras-team/keras#14169]
**Important note:** the development of Keras is currently taking place at [`github.com/tensorflow/tensorflow`](https://github.com/tensorflow/tensorflow). Please file your bug report by creating a new issue in the TensorFlow repository.

Please note that multi-backend Keras development has been discontinued. Do not report issues about multi-backend Keras (Keras 2.3.1 and lower), only report issues about the TensorFlow implementation of Keras (tf.keras).

**Comment by jvishnuvardhan** [comment]
@yousss Looks like you forgot to add a description about your issue. Can you please share more details about the issue or close the issue if this was already resolved for you. Thanks!
