### ISSUE TITLE
Seq2Seq Modeling Error for English to Tamil language Translator

### ISSUE THREAD

**Issue by chellatamilan** [keras-team/keras#14161]
**Important note:** the development of Keras is currently taking place at [`github.com/tensorflow/tensorflow`](https://github.com/tensorflow/tensorflow). Please file your bug report by creating a new issue in the TensorFlow repository.

Please note that multi-backend Keras development has been discontinued. Do not report issues about multi-backend Keras (Keras 2.3.1 and lower), only report issues about the TensorFlow implementation of Keras (tf.keras).
For all the sentence of tam.txt
i get same output
Input sentence: I slept.
Decoded sentence: அவள் அவன் வருக்கிறான்

-
Input sentence: Calm down.
Decoded sentence: அவள் அவன் வருக்கிறான்

-
Input sentence: I'll walk.
Decoded sentence: அவள் அவன் வருக்கிறான்

-
Input sentence: Who is he?
Decoded sentence: அவள் அவன் வருக்கிறான்

-
Input sentence: Who knows?
Decoded sentence: அவள் அவன் வருக்கிறான்

-
Input sentence: She smiled.
Decoded sentence: அவள் அவன் வருக்கிறான்

-
Input sentence: Talk to me!
Decoded sentence: அவள் அவன் வருக்கிறான்

-
Input sentence: Who is she?
Decoded sentence: அவள் அவன் வருக்கிறான்

-
Input sentence: Go to sleep.
Decoded sentence: அவள் அவன் வருக்கிறான்

**Comment by chunduriv** [comment]
@chellatamilan, Sorry for the late response. Is this still an issue for you?

Can you please try recent TF2.7 or tf-nightly and let us know whether it is persisting? Also, share a simple standalone code to reproduce the issue.
