### ISSUE TITLE
ValueError: An operation has `None` for gradient. Please make sure that all of your ops have a gradient defined (i.e. are differentiable)

### ISSUE THREAD

**Issue by csitaula** [keras-team/keras#14171]

**Comment by vpuru98** [comment]
@csitaula I faced a similar issue. Ensure that all the ops on your tensors defined within your model are differentiable. Have a look at which ops are differentiable [here](https://github.com/Mainak431/List-of-Differentiable--OPs-and-Non-differentiable-OPs--in-Tensorflow).

**Comment by jvishnuvardhan** [comment]
@vpuru98 Thanks for the list. 

@csitaula Sorry for late response. Is this still an issue for you?

Can you please share a simple standalone code to reproduce the issue? Also, try with recent `TF/keras` and make sure you don't have any nondifferentiable ops. Thanks!
