### ISSUE TITLE
An unknown error while 'model.fit' execution

### ISSUE THREAD

**Issue by ujwalakoriraj** [keras-team/keras#14188]
This is my input:

`history = model.fit(train_images,
                    train_masks/255,
                    validation_split = 0.1,
                    epochs=EPOCHS)`

The error is:

`Train on 6274 samples, validate on 698 samples
Epoch 1/100
  32/6274 [..............................] - ETA: 37s
---------------------------------------------------------------------------
UnknownError                              Traceback (most recent call last)
<ipython-input-21-107e0c8149d7> in <module>
      2                     train_masks/255,
      3                     validation_split = 0.1,
----> 4                     epochs=EPOCHS)
      5 model.save("D:/python/building_detection/8_building/building_final.h5")

~\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    817         max_queue_size=max_queue_size,
    818         workers=workers,
--> 819         use_multiprocessing=use_multiprocessing)
    820 
    821   def evaluate(self,

~\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py in fit(self, model, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    340                 mode=ModeKeys.TRAIN,
    341                 training_context=training_context,
--> 342                 total_epochs=epochs)
    343             cbks.make_logs(model, epoch_logs, training_result, ModeKeys.TRAIN)
    344 

~\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py in run_one_epoch(model, iterator, execution_function, dataset_size, batch_size, strategy, steps_per_epoch, num_samples, mode, training_context, total_epochs)
    126         step=step, mode=mode, size=current_batch_size) as batch_logs:
    127       try:
--> 128         batch_outs = execution_function(iterator)
    129       except (StopIteration, errors.OutOfRangeError):
    130         # TODO(kaftan): File bug about tf function and errors.OutOfRangeError?

~\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\training_v2_utils.py in execution_function(input_fn)
     96     # `numpy` translates Tensors to values in Eager mode.
     97     return nest.map_structure(_non_none_constant_value,
---> 98                               distributed_function(input_fn))
     99 
    100   return execution_function

~\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\eager\def_function.py in __call__(self, *args, **kwds)
    566         xla_context.Exit()
    567     else:
--> 568       result = self._call(*args, **kwds)
    569 
    570     if tracing_count == self._get_tracing_count():

~\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\eager\def_function.py in _call(self, *args, **kwds)
    597       # In this case we have created variables on the first call, so we run the
    598       # defunned version which is guaranteed to never create variables.
--> 599       return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
    600     elif self._stateful_fn is not None:
    601       # Release the lock early so that multiple threads can perform the call

~\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\eager\function.py in __call__(self, *args, **kwargs)
   2361     with self._lock:
   2362       graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
-> 2363     return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
   2364 
   2365   @property

~\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\eager\function.py in _filtered_call(self, args, kwargs)
   1609          if isinstance(t, (ops.Tensor,
   1610                            resource_variable_ops.BaseResourceVariable))),
-> 1611         self.captured_inputs)
   1612 
   1613   def _call_flat(self, args, captured_inputs, cancellation_manager=None):

~\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\eager\function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1690       # No tape is watching; skip to running the function.
   1691       return self._build_call_outputs(self._inference_function.call(
-> 1692           ctx, args, cancellation_manager=cancellation_manager))
   1693     forward_backward = self._select_forward_and_backward_functions(
   1694         args,

~\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\eager\function.py in call(self, ctx, args, cancellation_manager)
    543               inputs=args,
    544               attrs=("executor_type", executor_type, "config_proto", config),
--> 545               ctx=ctx)
    546         else:
    547           outputs = execute.execute_with_cancellation(

~\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\eager\execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     65     else:
     66       message = e.message
---> 67     six.raise_from(core._status_to_exception(e.code, message), None)
     68   except TypeError as e:
     69     keras_symbolic_tensors = [

~\anaconda3\envs\tensorflow\lib\site-packages\six.py in raise_from(value, from_value)

UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node model/conv2d/Conv2D (defined at <ipython-input-17-45130942bb4a>:6) ]] [Op:__inference_distributed_function_7653]

Function call stack:
distributed_function`

**Comment by Ayush-Parhi** [comment]
> This is my input:
> 
> `history = model.fit(train_images, train_masks/255, validation_split = 0.1, epochs=EPOCHS)`
> 
> The error is:
> ## `Train on 6274 samples, validate on 698 samples
> Epoch 1/100
> 32/6274 [..............................] - ETA: 37s
> 
> UnknownError Traceback (most recent call last)
> in
> 2 train_masks/255,
> 3 validation_split = 0.1,
> ----> 4 epochs=EPOCHS)
> 5 model.save("D:/python/building_detection/8_building/building_final.h5")
> 
> ~\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
> 817 max_queue_size=max_queue_size,
> 818 workers=workers,
> --> 819 use_multiprocessing=use_multiprocessing)
> 820
> 821 def evaluate(self,
> 
> ~\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py in fit(self, model, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
> 340 mode=ModeKeys.TRAIN,
> 341 training_context=training_context,
> --> 342 total_epochs=epochs)
> 343 cbks.make_logs(model, epoch_logs, training_result, ModeKeys.TRAIN)
> 344
> 
> ~\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py in run_one_epoch(model, iterator, execution_function, dataset_size, batch_size, strategy, steps_per_epoch, num_samples, mode, training_context, total_epochs)
> 126 step=step, mode=mode, size=current_batch_size) as batch_logs:
> 127 try:
> --> 128 batch_outs = execution_function(iterator)
> 129 except (StopIteration, errors.OutOfRangeError):
> 130 # TODO(kaftan): File bug about tf function and errors.OutOfRangeError?
> 
> ~\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\training_v2_utils.py in execution_function(input_fn)
> 96 # `numpy` translates Tensors to values in Eager mode.
> 97 return nest.map_structure(_non_none_constant_value,
> ---> 98 distributed_function(input_fn))
> 99
> 100 return execution_function
> 
> ~\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\eager\def_function.py in **call**(self, *args, **kwds)
> 566 xla_context.Exit()
> 567 else:
> --> 568 result = self._call(*args, **kwds)
> 569
> 570 if tracing_count == self._get_tracing_count():
> 
> ~\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\eager\def_function.py in _call(self, *args, **kwds)
> 597 # In this case we have created variables on the first call, so we run the
> 598 # defunned version which is guaranteed to never create variables.
> --> 599 return self._stateless_fn(*args, **kwds) # pylint: disable=not-callable
> 600 elif self._stateful_fn is not None:
> 601 # Release the lock early so that multiple threads can perform the call
> 
> ~\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\eager\function.py in **call**(self, *args, **kwargs)
> 2361 with self._lock:
> 2362 graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
> -> 2363 return graph_function._filtered_call(args, kwargs) # pylint: disable=protected-access
> 2364
> 2365 @Property
> 
> ~\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\eager\function.py in _filtered_call(self, args, kwargs)
> 1609 if isinstance(t, (ops.Tensor,
> 1610 resource_variable_ops.BaseResourceVariable))),
> -> 1611 self.captured_inputs)
> 1612
> 1613 def _call_flat(self, args, captured_inputs, cancellation_manager=None):
> 
> ~\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\eager\function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
> 1690 # No tape is watching; skip to running the function.
> 1691 return self._build_call_outputs(self._inference_function.call(
> -> 1692 ctx, args, cancellation_manager=cancellation_manager))
> 1693 forward_backward = self._select_forward_and_backward_functions(
> 1694 args,
> 
> ~\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\eager\function.py in call(self, ctx, args, cancellation_manager)
> 543 inputs=args,
> 544 attrs=("executor_type", executor_type, "config_proto", config),
> --> 545 ctx=ctx)
> 546 else:
> 547 outputs = execute.execute_with_cancellation(
> 
> ~\anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\eager\execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
> 65 else:
> 66 message = e.message
> ---> 67 six.raise_from(core._status_to_exception(e.code, message), None)
> 68 except TypeError as e:
> 69 keras_symbolic_tensors = [
> 
> ~\anaconda3\envs\tensorflow\lib\site-packages\six.py in raise_from(value, from_value)
> 
> UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
> [[node model/conv2d/Conv2D (defined at :6) ]] [Op:__inference_distributed_function_7653]
> 
> Function call stack:
> distributed_function`

This error generally arises when you have mismatched versions of CUDA and cuDNN with Tensorflow. Please check your CUDA and cuDNN versions and check if they are compatible with your current tensorflow version.

Another reason for this, can the running out of memory, in that case, reduce your batch size, or use fewer data.

Hope this might help!

**Comment by ujwalakoriraj** [comment]
Yeah, thanks for the response. I did try most of the common fixes, but none worked. Later I happened to watch this video which literally worked like a magic to me!! The video is this: https://www.youtube.com/watch?v=h-LnF1d6uJI

Here's what one has to do as per the video (provided all the Tensorflow, CUDA, CuDNN are of the right versions): add the following piece of command before, I repeat, BEFORE importing Tensorflow in your code: (this is as of 13 August 2020)

```
import tensorflow as tf
config = tf.compat.v1.ConfigProto()
config.gpu_options.allow_growth = True
sess = tf.compat.v1.Session(config=config)
```

Remember: Restart your Spyder or Jupyter Notebook, or whichever environment you're working on, after adding the above lines.

Thank you!

**Comment by WittmannF** [comment]
The above worked for me, but why this error is even happening? And why do I have to import something from TensorFlow V1 to solve an issue in TF V2? Also, the traceback is misleading

**Comment by jasonheidermeiers** [comment]
TensorFlow is a pathetic mess written and maintained by 17 y/o kids whose mouth is still stained with milk and whose graduation license still feats fresh ink

This is why

**Comment by MATTYGILO** [comment]
I had to close my Jupyter notebook and start again fresh
