### ISSUE TITLE
NameError: name 'generator' is not defined

### ISSUE THREAD

**Issue by Nusrat1011** [keras-team/keras#14184]
Please need your kind suggestions to address the error given below:

import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd
import os
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from keras.layers import Input, Dense, Reshape, Flatten, Dropout 
from keras.layers import BatchNormalization, Activation
from keras.layers.advanced_activations import LeakyReLU 
from keras.layers.convolutional import Conv2D 
from keras.models import Sequential, Model 
from keras.optimizers import SGD 

def makediag3d(a):
    a = np.asarray(a)
    depth, size = a.shape
    x = np.zeros((depth,size,size))
    for i in range(depth):
        x[i].flat[slice(0,None,1+size)] = a[i]
    return x

input = pd.read_excel( '3_height.xls')
new_input = (makediag3d(input))
output = pd.read_excel( '3_absor.xls')
new_output= np.array(output)

BUFFER_SIZE = 50000
BATCH_SIZE = 128
train_dataset = tf.data.Dataset.from_tensor_slices(new_input).shuffle(BUFFER_SIZE).batch(BATCH_SIZE)

def make_generator_model():
    model = tf.keras.Sequential()
    model.add(layers.Dense(3*3*256, use_bias=False, input_shape=(50,)))
    model.add(layers.BatchNormalization())
    model.add(layers.LeakyReLU())

    model.add(layers.Reshape((3, 3, 256)))
    assert model.output_shape == (None, 7, 7, 256) # Note: None is the batch size

    model.add(layers.Conv2DTranspose(128, (5, 5), strides=(1, 1), padding='same', use_bias=False))
    assert model.output_shape == (None, 3, 3, 128)
    model.add(layers.BatchNormalization())
    model.add(layers.LeakyReLU())

    model.add(layers.Conv2DTranspose(64, (5, 5), strides=(2, 2), padding='same', use_bias=False))
    assert model.output_shape == (None, 3, 3, 64)
    model.add(layers.BatchNormalization())
    model.add(layers.LeakyReLU())

    model.add(layers.Conv2DTranspose(1, (5, 5), strides=(2, 2), padding='same', use_bias=False, activation='tanh'))
    assert model.output_shape == (None, 3, 3, 1)

    return model
    generator = make_generator_model()

 def make_discriminator_model():
    model = tf.keras.Sequential()
    model.add(layers.Conv2D(64, (5, 5), strides=(2, 2), padding='same',
                                     input_shape=[3, 3, 1]))
    model.add(layers.LeakyReLU())
    model.add(layers.Dropout(0.2))

    model.add(layers.Conv2D(128, (5, 5), strides=(2, 2), padding='same'))
    model.add(layers.LeakyReLU())
    model.add(layers.Dropout(0.2))

    model.add(layers.Flatten())
    model.add(layers.Dense(1))

    return model
    discriminator = make_discriminator_model()
    
    cross_entropy = tf.keras.losses.BinaryCrossentropy(from_logits=True)
    
def discriminator_loss(real_output, fake_output):
    real_loss = cross_entropy(tf.ones_like(real_output), real_output)
    fake_loss = cross_entropy(tf.zeros_like(fake_output), fake_output)
    total_loss = real_loss + fake_loss
    return total_loss

sgd = optimizers.SGD(lr=0.001, decay=1e-6, momentum=0.9, nesterov=True)
generator_optimizer = tf.keras.optimizers.SGD
discriminator_optimizer = tf.keras.optimizers.SGD

checkpoint_dir = './training_checkpoints'
checkpoint_prefix = os.path.join(checkpoint_dir, "ckpt")
checkpoint = tf.train.Checkpoint(generator_optimizer=generator_optimizer,
                                 discriminator_optimizer=discriminator_optimizer,
                                 generator=generator,
                                 discriminator=discriminator)
![image](https://user-images.githubusercontent.com/69383239/89706386-74785e00-d9a8-11ea-8632-b8e2d329b868.png)

**Comment by adeepH** [comment]
#14184 Please check if you have called generator = make_generator_model() inside   make_generator_model()

**Comment by Nusrat1011** [comment]
I have called it inside make_generator_model() even then it is not showing the same error. Please let me know how to modify the following portion of the code so that the error can be solved.

def make_generator_model():
    model = tf.keras.Sequential()
    model.add(layers.Dense(3*3*256, use_bias=False, input_shape=(50,)))
    model.add(layers.BatchNormalization())
    model.add(layers.LeakyReLU())

    model.add(layers.Reshape((3, 3, 256)))
    assert model.output_shape == (None, 7, 7, 256) # Note: None is the batch size

    model.add(layers.Conv2DTranspose(128, (5, 5), strides=(1, 1), padding='same', use_bias=False))
    assert model.output_shape == (None, 3, 3, 128)
    model.add(layers.BatchNormalization())
    model.add(layers.LeakyReLU())

    model.add(layers.Conv2DTranspose(64, (5, 5), strides=(2, 2), padding='same', use_bias=False))
    assert model.output_shape == (None, 3, 3, 64)
    model.add(layers.BatchNormalization())
    model.add(layers.LeakyReLU())

    model.add(layers.Conv2DTranspose(1, (5, 5), strides=(2, 2), padding='same', use_bias=False, activation='tanh'))
    assert model.output_shape == (None, 3, 3, 1)
    g = make_generator_model()
    return model

**Comment by adeepH** [comment]
@Nusrat1011  Could you share the files because I could try running that on my machine and tell  you what's wrong. Thanks in advance

**Comment by Nusrat1011** [comment]
Ofcourse @adeepH 
Here is the link of the file
https://drive.google.com/drive/folders/1CBc02XXq8rpBv5noXa9hVf6QWtik1Tiu?usp=sharing

**Comment by adeepH** [comment]
@Nusrat1011  I think you had missed an indentation , that's why It did not work the first time. It should work this time.
https://colab.research.google.com/drive/1vv-8eOjJqmfH8t5j_bxhZPQQay6YmoX3?usp=sharing

**Comment by Nusrat1011** [comment]
@adeepH Thank you very much. I have just sent a request to get access to the link shared by you.

**Comment by Nusrat1011** [comment]
Thank You @adeepH that problem has resolved but I am getting a new error i.e. given below. Therefore, I am again sharing the updated google drive link that contains all the necessary files to run the code.
https://drive.google.com/drive/folders/1CBc02XXq8rpBv5noXa9hVf6QWtik1Tiu?usp=sharing
![image](https://user-images.githubusercontent.com/69383239/89923495-0b147b80-dc44-11ea-8dc2-e9e2e7a97130.png)

**Comment by tilakrayal** [comment]
@Nusrat1011 ,
Can you please refer this SO [link](https://stackoverflow.com/questions/64224052/valueerror-checkpoint-was-expecting-a-trackable-object-an-object-derived-fro) with the similar error.It helps.Thanks!

**Comment by Amirzeb555** [comment]
i have same error 
NameError: name 'val_datagen' is not defined 
anyone help

**Comment by salah-ai** [comment]
I have the same error here can someone help me please



NameError                                 Traceback (most recent call last)
Cell In[29], line 10
      8 for i, sample in enumerate(test_loader):
      9     print(sample["img_path"][0])
---> 10     _, _, _, input, gt, pred, attention_map, back_ground, psnr, ssim = do_one_iteration(sample,generator, discriminator, benet, criterion, device, "evaluate", lambda_dict)
     12     gts += list(gt)
     13     preds += list(pred)

NameError: name 'generator' is not defined
