### ISSUE TITLE
ValueError: Negative dimension size caused by subtracting 60 from 1 for 'depthwise_conv2d_1/depthwise' (op: 'DepthwiseConv2dNative') with input shapes: [?,1,60,8], [60,1,8,2].

### ISSUE THREAD

**Issue by parasmemon** [keras-team/keras#14192]
**Important note:** the development of Keras is currently taking place at [`github.com/tensorflow/tensorflow`](https://github.com/tensorflow/tensorflow). Please file your bug report by creating a new issue in the TensorFlow repository.
 
I am running this code: https://github.com/vlawhern/arl-eegmodels/blob/master/examples/ERP.py

Please help me. None of the solution available on internet work for me.

**Comment by jvishnuvardhan** [comment]
@parasmemon Sorry for the late response. Is this still an issue for you?

This repo is mainly focussed on bugs/performance related issues. If you think this is more like a support question, then please post it in [TF Forum](https://discuss.tensorflow.org/) where there is a large community supporting each other and learning from each other.

If you think this is a bug, then please provide a simple standalone code to reproduce the issue. Thanks!
