### ISSUE TITLE
Multiple ground truths (incorporate in image generator mask folder and loss) or slice ground truth in custom loss

### ISSUE THREAD

**Issue by zetaSaahil** [keras-team/keras#14193]
I am working on segmentation, and I have 2 ground truth images for each image, that I need to incorporate into my custom loss function.

1. Is there a way for my mask folder to input 2 mask folders, and also call them in loss function? 

def trainGenerator(batch_size,train_path,image_folder,mask_folder,aug_dict,image_color_mode = "grayscale",
                    mask_color_mode = "grayscale",image_save_prefix  = "image",mask_save_prefix  = "mask",
                    flag_multi_class = False,num_class = 2,save_to_dir = None,target_size = (256,256),seed = 1):
    '''
    can generate image and mask at the same time
    use the same seed for image_datagen and mask_datagen to ensure the transformation for image and mask is the same
    if you want to visualize the results of generator, set save_to_dir = "your path"
    '''
    if aug_dict == None:
        image_datagen = ImageDataGenerator()
        mask_datagen = ImageDataGenerator()
    else:
        image_datagen = ImageDataGenerator(**aug_dict)
        mask_datagen = ImageDataGenerator(**aug_dict)
        
    image_generator = image_datagen.flow_from_directory(
        train_path,
        classes = [image_folder],
        class_mode = None,
        color_mode = image_color_mode,
        target_size = target_size,
        batch_size = batch_size,
        save_to_dir = save_to_dir,
        save_prefix  = image_save_prefix,
        seed = seed)
    mask_generator = mask_datagen.flow_from_directory(
        train_path,
        classes = [mask_folder],
        class_mode = None,
        color_mode = mask_color_mode,
        target_size = target_size,
        batch_size = batch_size,
        save_to_dir = save_to_dir,
        save_prefix  = mask_save_prefix,
        seed = seed)
    train_generator = zip(image_generator, mask_generator)
    for (img,mask) in train_generator:
        img,mask = adjustData(img,mask,flag_multi_class,num_class)
        yield (img,mask)

train_Generator = trainGenerator(batch_size=batch_size,
                                 train_path=str(Path('data_' + str(PATCH_SIZE) + pre_name + '_' + path_arg + '/train')),
                                 image_folder='images',
                                 mask_folder=**mask_folder**,
                                 aug_dict=None,
                                 save_to_dir=None)

2. Another way I could think of doing this was to concatenate the ground truths together, and call it at once in the loss function. However, I cant find a way to slice the y_true. It throws error everytime I try to do so. The shape of y_true is (None, None, None, None), and apparently in many discussions, this is how it is supposed to be. While slicing y_pred works just fine, but slicing y_true seems like a challenge.

def custom_loss(y_true, y_pred):
        y_true1 = y_true[:,:,256:,:]
        y_true2 = y_true[:,:,0:256,:]
        y_pred = y_pred*y_true2
        #calculate loss with y_pred
        return loss

tensorflow.python.framework.errors_impl.InvalidArgumentError:  Incompatible shapes: [15,256,256,1] vs. [15,256,0,1]

**Comment by tilakrayal** [comment]
@zetaSaahil ,
Can you please take a look at this [link](https://www.tensorflow.org/guide/keras/masking_and_padding) and [link2](https://towardsdatascience.com/generating-image-segmentation-masks-the-easy-way-dd4d3656dbd1).Thanks!
