### ISSUE TITLE
AttributeError: 'ModelCheckpoint' object has no attribute '_implements_train_batch_hooks'

### ISSUE THREAD

**Issue by 23subbhashit** [keras-team/keras#14196]
I was using ModelCheckpoint  from keras for model traing.Here is the code:
````
model1.compile(loss={'ctc': lambda y_true, y_pred: y_pred}, optimizer = 'adam')
 
filepath="model.hdf5"
checkpoint = ModelCheckpoint(filepath=filepath, monitor='val_loss', verbose=1, save_best_only=True, mode='auto')
````
````
# fitting model

model1.fit(x = [ IMAGES , LABELS_PADDED , IMAGES_LENGTH , LABELS_LENGTH ], y=np.zeros(len(IMAGES)) , batch_size = 256 , epochs = 1000 , validation_split = 0.33 , verbose = 1, callbacks = [ checkpoint ] )
````
And I encountered this error:

````
AttributeError                            Traceback (most recent call last)
<ipython-input-84-de48273d352a> in <module>
      1 # fitting model
      2 
----> 3 model1.fit(x = [ IMAGES , LABELS_PADDED , IMAGES_LENGTH , LABELS_LENGTH ], y=np.zeros(len(IMAGES)) , batch_size = 256 , epochs = 1000 , validation_split = 0.33 , verbose = 1, callbacks = [ checkpoint ] )

~\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py in _method_wrapper(self, *args, **kwargs)
     64   def _method_wrapper(self, *args, **kwargs):
     65     if not self._in_multi_worker_mode():  # pylint: disable=protected-access
---> 66       return method(self, *args, **kwargs)
     67 
     68     # Running inside `run_distribute_coordinator` already.

~\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
    824             verbose=verbose,
    825             epochs=epochs,
--> 826             steps=data_handler.inferred_steps)
    827 
    828       self.stop_training = False

~\anaconda3\lib\site-packages\tensorflow\python\keras\callbacks.py in __init__(self, callbacks, add_history, add_progbar, model, **params)
    229     # pylint: disable=protected-access
    230     self._should_call_train_batch_hooks = any(
--> 231         cb._implements_train_batch_hooks() for cb in self.callbacks)
    232     self._should_call_test_batch_hooks = any(
    233         cb._implements_test_batch_hooks() for cb in self.callbacks)

~\anaconda3\lib\site-packages\tensorflow\python\keras\callbacks.py in <genexpr>(.0)
    229     # pylint: disable=protected-access
    230     self._should_call_train_batch_hooks = any(
--> 231         cb._implements_train_batch_hooks() for cb in self.callbacks)
    232     self._should_call_test_batch_hooks = any(
    233         cb._implements_test_batch_hooks() for cb in self.callbacks)

AttributeError: 'ModelCheckpoint' object has no attribute '_implements_train_batch_hooks'
````

How to resolve this?

**Comment by WolframAlph** [comment]
Hi @23subbhashit have you tried this solution https://stackoverflow.com/questions/62454151/keras-callback-attributeerror-modelcheckpoint-object-has-no-attribute-imple ?

**Comment by 23subbhashit** [comment]
Yaa I tried it , didn't work for me.

**Comment by YokkaBear** [comment]
Hi @WolframAlph , I tried that solution but it didn't work for me, too.

**Comment by Y-Shy** [comment]
> 
> 
> Hi @23subbhashit have you tried this solution https://stackoverflow.com/questions/62454151/keras-callback-attributeerror-modelcheckpoint-object-has-no-attribute-imple ?

Yes, works for me. Thanks. What I do:
replace:
`from keras.callbacks import ModelCheckpoint`
by:
`from tensorflow.keras.callbacks import ModelCheckpoint`

**Comment by 23subbhashit** [comment]
> > Hi @23subbhashit have you tried this solution https://stackoverflow.com/questions/62454151/keras-callback-attributeerror-modelcheckpoint-object-has-no-attribute-imple ?
> 
> Yes, works for me. Thanks. What I do:
> replace:
> `from keras.callbacks import ModelCheckpoint`
> by:
> `from tensorflow.keras.callbacks import ModelCheckpoint`

Worked for me as well.
I reinstalled tensorflow and keras of lower versions. Then I used this method and it worked for me.

**Comment by munakadir22** [comment]
Thanks a lot. It worked

**Comment by munakadir22** [comment]
> > Hi @23subbhashit have you tried this solution https://stackoverflow.com/questions/62454151/keras-callback-attributeerror-modelcheckpoint-object-has-no-attribute-imple ?
> 
> Yes, works for me. Thanks. What I do: replace: `from keras.callbacks import ModelCheckpoint` by: `from tensorflow.keras.callbacks import ModelCheckpoint`

Thanks a lot. It worked

**Comment by MustafaLotfi** [comment]
I tried all of the methods above and none of them worked for me.
The point is, I was using Google Colab with a CPU runtime and everything was ok. But when I changed the runtime to GPU, this error occurred.
