### ISSUE TITLE
cannot import name 'detect_lp'

### ISSUE THREAD

**Issue by mgeraldhia** [keras-team/keras#14208]
I'm simply trying to import different things from Keras so I can run the tutorial. Specifically, I do this:

```
import cv2
import numpy as np
import glob
import keras
import matplotlib.pyplot as plt
from keras_utils import detect_lp
from os.path import splitext,basename
from keras.models import model_from_json
```

and it gets stuck at the first import, giving me a traceback of this:

```
Using TensorFlow backend.
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-7cdf08ce2bd4> in <module>()
      4 import keras
      5 import matplotlib.pyplot as plt
----> 6 from keras_utils import detect_lp
      7 from os.path import splitext,basename
      8 from keras.models import model_from_json

ImportError: cannot import name 'detect_lp'
```

I've Googled around but can't seem to find out why I'm running into this problem / how to fix. Any ideas?

Thanks!

**Comment by nishchalnishant** [comment]
i think it should be 
from keras.utils import detect_lp

but i  don't think that there is any detect_lp class or function ,

![image](https://user-images.githubusercontent.com/40529054/94168206-041b9280-feab-11ea-89ae-99c533b22cea.png)
