### ISSUE TITLE
 ValueError: You are trying to load a weight file containing 13 layers into a model with 19 layers.

### ISSUE THREAD

**Issue by yashkarbhari** [keras-team/keras#14206]
I'm getting this error while doing FCN segmentation.
`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-21-9eee427c0d03> in <module>
----> 1 fcn16_model.load_weights('vgg16_weights_tf_dim_ordering_tf_kernels_notop.h5')
      2 

~\anaconda3\lib\site-packages\keras\engine\topology.py in load_weights(self, filepath, by_name, skip_mismatch, reshape)
   2665             else:
   2666                 load_weights_from_hdf5_group(
-> 2667                     f, self.layers, reshape=reshape)
   2668 
   2669     def _updated_config(self):

~\anaconda3\lib\site-packages\keras\engine\topology.py in load_weights_from_hdf5_group(f, layers, reshape)
   3363                          'containing ' + str(len(layer_names)) +
   3364                          ' layers into a model with ' +
-> 3365                          str(len(filtered_layers)) + ' layers.')
   3366 
   3367     # We batch weight value assignments in a single backend call

ValueError: You are trying to load a weight file containing 13 layers into a model with 19 layers.`

**Comment by jvishnuvardhan** [comment]
@yashkarbhari Similar error was noticed when the model was saved in `h5` format. Saving in `tf` saved model format worked as expected. Please check [this issue](https://github.com/tensorflow/tensorflow/issues/34016#issuecomment-551207888) that was resolved earlier. Thanks!

If you notice any error when you save in `tf` format, then share a simple standalone code to reproduce the issue. Thanks!
