### ISSUE TITLE
Releasing keras session resources in Tensorflow 2

### ISSUE THREAD

**Issue by shahriar49** [keras-team/keras#14205]
I have a keras model running on Tensorflow 1.x, in which I have some datasets defined and then applied to a keras model. The code structure is as follows:

```
import tensorflow as tf
from tensorflow.keras import backend as K
config = tf.ConfigProto()
config.gpu_options.allow_growth = True

def doWork(args):

    sess = tf.Session(config=config)
    K.set_session(sess)

    ... generate datasets, create keras model, run training loop, etc.

    K.clear_session()
    sess.close()

if __name__ == '__main__':
    
    ... set some global variables
    doWork(first set of arguments)
    doWork(second set of arguments)
    ...

```
I wanted to limit gpu memory usage at the start (configProto line) so I needed to define a session with my desired gpu config. I have also cached my datasets in computer main memory to speed the training process, and wanted it to be released after finishing training. Therefore I put the training loop in the doWork() function to be able to assign and release resources each time I run it. I found unless I close the session, memory will not be freed. I also found a clear_session with keras and added it (but I am not sure if it helps for my purpose or not).

The above code works fine with TF 1.x, but I don't know how to port it to TF 2, as the sessions are removed from ordinary use there. How can I do that and have both configProto and main memory release done in TF 2? Should I define sessions again? I think there should be more straightforward method.

**Comment by jvishnuvardhan** [comment]
@shahriar49 Sorry for late response. Is this still an issue for you?

For limiting `GPU` usage with `TF2.x`, please check this guide https://www.tensorflow.org/guide/gpu

TF2.x is more pythonic. so, you don't need any `tf.Session` to define and run specific evaluation.  Please check tutorials in [TF webpage](https://www.tensorflow.org/tutorials) and [keras webpage](https://keras.io/guides/). Thanks!
