### ISSUE TITLE
Tensorflow-gpu error: Internal: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by Abheast12** [keras-team/keras#14202]
Currently I'm trying to use my GPU (an NVIDIA GeForce GTX 950M) to run a program in Jupyter Notebook, however, it came up with this error:

F .\tensorflow/core/kernels/random_op_gpu.h:232] Non-OK-status: GpuLaunchKernel(FillPhiloxRandomKernelLaunch<Distribution>, num_blocks, block_size, 0, d.stream(), gen, data, size, dist) status: Internal: no kernel image is available for execution on the device

The code I'm trying to run is pasted below:

import sys
import numpy as np
import tensorflow as tf
from datetime import datetime

device_name="/device:GPU:0"

shape=(int(100),int(100))

with tf.device(device_name):
    random_matrix = tf.compat.v1.random_uniform(shape=shape, minval=0, maxval=1)
    dot_operation = tf.matmul(random_matrix, tf.transpose(random_matrix))
    sum_operation = tf.reduce_sum(dot_operation)

    startTime = datetime.now()
    tf.compat.v1.disable_eager_execution()

    with tf.compat.v1.Session(config=tf.compat.v1.ConfigProto(log_device_placement=True)) as session:
            result = session.run(sum_operation)
            print(result)

    print("\n" * 2)
    print("Shape:", shape, "Device:", device_name)
    print("Time taken:", datetime.now() - startTime)

    print("\n" * 2)

I'm using Windows 10, Python 3.7, Tensorflow 2.2, Tensorflow-gpu 2.3, Keras 2.3.1, CUDA 11.0, cuDNN 8, and Jupyter Notebook does recognize my NVIDIA GeForce GTX 950M GPU.

I would really appreciate any assistance, I'm new to machine learning, and its been a hassle trying to get Jupyter Notebook to run on Tensorflow-gpu

**Comment by bhack** [comment]
@Abheast12 CUDA 11 requires `tf-nightly`. Can you try again with nightly?

**Comment by tilakrayal** [comment]
@Abheast12 ,
Could you please update tf v2.6 and keras to the latest stable version  and let us know if you are facing the same error. Thanks!
