### ISSUE TITLE
AttributeError: 'Sequential' object has no attribute '_make_predict_function'

### ISSUE THREAD

**Issue by zahrael97** [keras-team/keras#14214]
**Important note:** the development of Keras is currently taking place at [`github.com/tensorflow/tensorflow`](https://github.com/tensorflow/tensorflow). Please file your bug report by creating a new issue in the TensorFlow repository.

Please note that multi-backend Keras development has been discontinued. Do not report issues about multi-backend Keras (Keras 2.3.1 and lower), only report issues about the TensorFlow implementation of Keras (tf.keras).

**Comment by chunduriv** [comment]
@zahrael97, Sorry for the late response. Is this still an issue for you?

Does [this reference](https://stackoverflow.com/questions/64058523/attributeerror-sequential-object-has-no-attribute-make-predict-function) helps you? Else, can you please share standalone code to replicate your issue? Thanks!
