### ISSUE TITLE
Multiple tensorboard callbacks fails

### ISSUE THREAD

**Issue by SinaChavoshi** [keras-team/keras#14223]
Using multiple tensorboard callbacks fails for example given, 

``` python 
model.fit(x=x, y=y, callbacks=[
    tf.keras.callbacks.TensorBoard(log_dir='logs_1'),
    tf.keras.callbacks.TensorBoard(log_dir='logs_2')
])
```

results in 

```
...
/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/ops/summary_ops_v2.py in trace_export(name, step, profiler_outdir)
   1225   with _current_trace_context_lock:
   1226     if _current_trace_context is None:
-> 1227       raise ValueError("Must enable trace before export.")
   1228     graph, profiler = _current_trace_context  # pylint: disable=redefined-outer-name
   1229     if profiler and profiler_outdir is None:

ValueError: Must enable trace before export.
```

**Comment by jvishnuvardhan** [comment]
@SinaChavoshi Interesting. Can you please explain what is your use case and why do you need two `TensorBoard` callbacks? 

In the mean time, you might be able to workaround with a custom callback but always running two same callbacks doesn't guarantee results. Thanks!

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
