### ISSUE TITLE
batch dot product 

### ISSUE THREAD

**Issue by marziehoghbaie** [keras-team/keras#14233]
I am developing a Keras model for video, and I have to use Dot product for two matrixes with this dimension A = (?, a, b, c), B =(?, a, c, b), which there Dot product will be D(axes=(3, 2)). the problem is when I print the output.shape its all right and it is (?, a, b, b), but in model summary, it is (? a, b, a, b). Any suggestions about what's going on?

**Comment by lpossible** [comment]
i meet the same question,but i find in keras2.2.4+tf1.14.0,it work well,higher keras have the same problem,i don't know which runs wrong,keras or tf?

**Comment by Saduf2019** [comment]
@marziehoghbaie 
https://github.com/keras-team/keras/issues/14031
