### ISSUE TITLE
run K.ctc_decode() decode on GPU

### ISSUE THREAD

**Issue by abhishek-110** [keras-team/keras#14243]
**Important note:** the development of Keras is currently taking place at [`github.com/tensorflow/tensorflow`](https://github.com/tensorflow/tensorflow). Please file your bug report by creating a new issue in the TensorFlow repository.

Please note that multi-backend Keras development has been discontinued. Do not report issues about multi-backend Keras (Keras 2.3.1 and lower), only report issues about the TensorFlow implementation of Keras (tf.keras).

I am unable to run K.ctc_decode() on GPU. How can I do it

**Comment by tilakrayal** [comment]
@abhishek-110 ,
Can you please take a look at this comment from the [issue](https://github.com/tensorflow/tensorflow/issues/42151#issuecomment-1058640334) which delivers the information.Thanks!
