### ISSUE TITLE
Error in Loading BertForTokenClassification Model from Local directory in jupyter notebook

### ISSUE THREAD

**Issue by 55Ankur55** [keras-team/keras#14257]
I am Trying to load a model from local directory but it it showing an error 

.yml file looks like
name: env
channels:
  - defaults
  - pytorch
dependencies:
  - numpy=1.16.2
  - pandas=0.24.2
  - matplotlib=3.0.3
  - pillow=5.4.1
  - pip=19.0
  - plotly=3.7.0
  - scikit-learn=0.23.1
  - seaborn=0.9.0
  - python=3.7.3
  - jupyter=1.0.0
  - pytorch=1.6.0
  - torchvision=0.7.0
  
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-11-d77bd0c28872> in <module>
      1 path = './content/model_save/'
----> 2 model = BertForTokenClassification.from_pretrained(path,from_tf=True)
      3 tokenizer = BertTokenizer.from_pretrained(path,from_tf=True)
      4 model.cuda()

~\anaconda3\envs\env\lib\site-packages\transformers\modeling_utils.py in from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs)
    530                     from transformers import load_tf2_checkpoint_in_pytorch_model
    531 
--> 532                     model = load_tf2_checkpoint_in_pytorch_model(model, resolved_archive_file, allow_missing_keys=True)
    533                 except ImportError:
    534                     logger.error(

~\anaconda3\envs\env\lib\site-packages\transformers\modeling_tf_pytorch_utils.py in load_tf2_checkpoint_in_pytorch_model(pt_model, tf_checkpoint_path, tf_inputs, allow_missing_keys)
    233         tf_model(tf_inputs, training=False)  # Make sure model is built
    234 
--> 235     tf_model.load_weights(tf_checkpoint_path, by_name=True)
    236 
    237     return load_tf2_model_in_pytorch_model(pt_model, tf_model, allow_missing_keys=allow_missing_keys)

~\anaconda3\envs\env\lib\site-packages\tensorflow\python\keras\engine\training.py in load_weights(self, filepath, by_name, skip_mismatch, options)
   2202           'first, then load the weights.')
   2203     self._assert_weights_created()
-> 2204     with h5py.File(filepath, 'r') as f:
   2205       if 'layer_names' not in f.attrs and 'model_weights' in f:
   2206         f = f['model_weights']

~\anaconda3\envs\env\lib\site-packages\h5py\_hl\files.py in __init__(self, name, mode, driver, libver, userblock_size, swmr, rdcc_nslots, rdcc_nbytes, rdcc_w0, track_order, **kwds)
    406                 fid = make_fid(name, mode, userblock_size,
    407                                fapl, fcpl=make_fcpl(track_order=track_order),
--> 408                                swmr=swmr)
    409 
    410             if isinstance(libver, tuple):

~\anaconda3\envs\env\lib\site-packages\h5py\_hl\files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
    171         if swmr and swmr_support:
    172             flags |= h5f.ACC_SWMR_READ
--> 173         fid = h5f.open(name, flags, fapl=fapl)
    174     elif mode == 'r+':
    175         fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)

h5py\_objects.pyx in h5py._objects.with_phil.wrapper()

h5py\_objects.pyx in h5py._objects.with_phil.wrapper()

h5py\h5f.pyx in h5py.h5f.open()

OSError: Unable to open file (file signature not found)

**Comment by jvishnuvardhan** [comment]
@55Ankur55 Sorry for the late response. Is this still an issue for you?

Can you please share a simple standalone code to reproduce the issue? Also, try running the code with recent TF/keras versions to check whether the issue persists with recent versions. Thanks!

**Comment by 55Ankur55** [comment]
> @55Ankur55 Sorry for the late response. Is this still an issue for you?
> 
> Can you please share a simple standalone code to reproduce the issue? Also, try running the code with recent TF/keras versions to check whet

**Comment by 55Ankur55** [comment]
@jvishnuvardhan the issue was training the model with different version of Pytorch and loading with different version as I trained on google colab and was trying to load on local machine. 
The issue has been solved now. It was due to different version. 
Thanks for the reply
