### ISSUE TITLE
I am having this issue while building a keras model.

### ISSUE THREAD

**Issue by rahulv1999** [keras-team/keras#14262]
![Screenshot (53)](https://user-images.githubusercontent.com/48206612/97773413-8d427b00-1b75-11eb-8b73-9b4d4af8c354.png)
![Screenshot (54)](https://user-images.githubusercontent.com/48206612/97773416-8e73a800-1b75-11eb-95ab-f131968a35fb.png)
![Screenshot (55)](https://user-images.githubusercontent.com/48206612/97773417-8f0c3e80-1b75-11eb-8779-013539c1c278.png)

Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by Saduf2019** [comment]
@rahulv1999 
https://github.com/keras-team/keras/issues/14233
