### ISSUE TITLE
ValueError: Error when checking input: expected lstm_47_input to have shape (128, 1) but got array with shape (1, 11)

### ISSUE THREAD

**Issue by Artus86** [keras-team/keras#14273]
Hi All, 

I'm very beginner with Tensorflow and Keras. I'm struggling with issue with fitting LSTM network. My X_train_new shape is (128, 1, 11) I have 128 rows of data and 11 colums of fetures my y_train_new shape is  (128, 1) 128 raws and 1 column of target

```
LSTM_model = Sequential()
LSTM_model.add(LSTM(128, activation='relu', input_shape=(X_train_new.shape[0],X_train_new.shape[2]), return_sequences=True ))
LSTM_model.add(Dense(1))
LSTM_model.compile(loss='mean_squared_error', optimizer='adam')
LSTM_model.fit(X_train_new, y_train_new, nb_epoch=100,batch_size=1, verbose=1, shuffle=False)
```

and I got following error
`ValueError: Error when checking input: expected lstm_47_input to have shape (128, 11) but got array with shape (1, 11)`

Can You tell me what I'm doing wrong.
Thank's a lot

**Comment by abdulbasitds** [comment]
Hello Aurtus, 

By features, do you intent to say timesteps? Otherwise, I am not sure why are you using LSTM for just one time step. (I may be completely wrong in understanding your problem)

**Comment by Artus86** [comment]
Hello Thank You for Your reply. 
Each row is daily reading from 11 sensor. based on historical data I want forecast readings from next couple measurements.

**Comment by gadagashwini** [comment]
@Artus86,

I tried with random input of same input shape as you mention.
Working sample code
```
import tensorflow as tf
import numpy as np

#input and output
X_train_new = np.random.normal(size=(128,1,11)) #  input 
Y_train_new = np.random.normal(size=(128,1)) 

LSTM_model = tf.keras.Sequential()
LSTM_model.add(tf.keras.Input(shape=(X_train_new.shape[1],X_train_new.shape[2])))
LSTM_model.add(keras.layers.LSTM(128, activation='relu' ))
LSTM_model.add(keras.layers.Dense(11,activation = "linear"))
LSTM_model.compile(loss='mean_squared_error', optimizer='adam')
LSTM_model.fit(X_train_new, Y_train_new, epochs=1, verbose=1)

```

**Output**
`4/4 [==============================] - 1s 8ms/step - loss: 1.1150`
