### ISSUE TITLE
Need to save and reuse a data generator

### ISSUE THREAD

**Issue by JoeHRIsaac** [keras-team/keras#14276]
Windows PC with Anaconda and Python 3.7.9
Using Keras with Tensorflow backend:  Keras 2.3.1 with TF 2.1.0
GPU is GTX 1070

I am using the ImageDataGenerator to generate the data for my CNN model since I'm using a lot of images (HANDS2017 dataset with 980k training images)
When I'm running the program, it takes a solid 1 hour to create the generator, and any error I get in the code during training only shows after the long wait.
When I rerun the code after minor tweaks the entire generator is getting created again and another 1 hour.
I would like to know if there is a way to save the generator since I'm making no changes to it and load the generator during program runtime. Otherwise is there a way to create the generator faster?

**Comment by sushreebarsa** [comment]
@JoeHRIsaac 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!
