### ISSUE TITLE
tensorflow keras is killed by system (memory leak, distribution)

### ISSUE THREAD

**Issue by zhenql** [keras-team/keras#14270]
Hello, 

I'm using tensorflow keras to distribute training my model and having a memory leak
the loops of training are wrote like [https://tensorflow.google.cn/tutorials/distribute/custom_training](url)
the version of tensorflow is 2.2.0 

I print the memory for each train step (batch_size=256, wokers=10, MultiWorkerMirroredStrategy)
`psutil.Process(os.getpid()).memory_info().rss`
I have try to use `tf.keras.bakend.clear_session()` for each step, and there is no cross-validation.

when step goes from 1 to 1500 (epoch:1~15) , the memory goes from 6G to 9G, seems no problem.
when step goes form 1500 to 1588 (epoch:16), the memory increases quickly from 9G to 33G, thus the system kill the process.

how can I solve the problem?

**Comment by suprateem48** [comment]
You might want to consider batching, or using a generator to feed the data into the model. The behavior does seem unnatural and unexpected.

**Comment by zhenql** [comment]
> You might want to consider batching, or using a generator to feed the data into the model. The behavior does seem unnatural and unexpected.

Thanks. I used `tf.data.TFRecordDataset(...).map(...).repeat(epochs).prefetch(...)` to generate my dataset. Through many attempts, the reason may be `tf.Dataset.repeat(epochs)` which will increase the memory until it grows to the peak of memory (which base on the epochs). I will submit the issue to tf project.

**Comment by ktiwary2** [comment]
Were you able to figure out what the issue is? This is really strange `.repeat(epochs)` causes the memory to increase. Can you provide a link to where you have the new issue? Thanks.

**Comment by jvishnuvardhan** [comment]
@zhenql Sorry for the late response. Is this still an issue for you?

Can you please share simple standalone code to reproduce the issue? Cab you also check with recent TF/keras versions. Thanks!
