### ISSUE TITLE
export a single pb file from keras model to use in c++ api (cppflow in my case) is that possible without tensorflow 1?

### ISSUE THREAD

**Issue by OfekShochat** [keras-team/keras#14284]
can I export a pb file and use it in c++ API with tensorflow 2?
I already searched a lot. but everything is for tensorflow 1 and the folder one doesn't work

**Comment by jvishnuvardhan** [comment]
@OfekShochat Sorry for the late response. Is this still an issue for you?

If this is still an issue, can you please add more details the issue? Thanks!

**Comment by OfekShochat** [comment]
nope, very late reply 😛

**Comment by OfekShochat** [comment]
well this is not solved yet tho
