### ISSUE TITLE
AttributeError: 'Sequential' object has no attribute '_id'

### ISSUE THREAD

**Issue by deepBrainWH** [keras-team/keras#14287]
def learn_mu(self, state, state_, action_index):
        w = self.branch_1_model.get_layer('R').get_weights()[0]
        mus_ = []
        for i in range(self.n_actions):
            mus_.append(self.branch_2_model[i](state_))
        mus_ = np.squeeze(mus_)
        max_index = np.argmax(np.squeeze(np.matmul(mus_, w)), axis=0)
        training_model = self.branch_2_model[action_index]
        with tf.GradientTape() as tape:
            pred = training_model(state)
            label = state + self.gamma * mus_[max_index]
            loss = mean_squared_error(label, pred)
        >grads = tape.gradient(loss, training_model)     # error position
        RMSprop().apply_gradients(zip(grads, training_model.trainable_variables))
        self.branch_2_model[action_index] = training_model

**Comment by deepBrainWH** [comment]
I know the reason for this error. I need to write:
    grads = tape.gradient(loss, training_model.trainable_variables)

**Comment by ymodak** [comment]
Closing this issue since its resolved. Thanks!
