### ISSUE TITLE
AttributeError: 'Model' object has no attribute '_in_multi_worker_mode'

### ISSUE THREAD

**Issue by gharshini** [keras-team/keras#14295]
I am using Tensorflow on GPU: NVIDIA GEFORCE RTX 2070
I have installed CUDA and CuDNN

I get this error when I use the following code:

batch_size = 1024
epochs = 400
checkpoint_filepath = './Resnet50Conv1d_sin'
checkpointer = tf.keras.callbacks.ModelCheckpoint(
    checkpoint_filepath,
    verbose=2,
    save_best_only=True)

history = model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, verbose=1, 
                    callbacks=[checkpointer], validation_data=(x_val, y_val))

I need to use ModelCheckpoint. It works fine for google colabs but not in my machine. I have only one GPU in my laptop. I even tried to run two programs simultaneously and they don't run. Is it the similar issue?

**Comment by jvishnuvardhan** [comment]
@gharshini Sorry for the late response. Is this still an issue for you?

What was the version of keras you had tried? Can you please try recent `TF2.6` or `tf-nightly` and let us know whether it is persisting. Also, share a simple standalone code to reproduce the issue. May be I can try checking it on GCP with GPUs. Thanks!
