### ISSUE TITLE
ValueError: generator yielded an element of shape () where an element of shape (None, None) was expected.

### ISSUE THREAD

**Issue by lizhaozhi** [keras-team/keras#14308]
Hi,

Appreciate your ideas.

I got the following error when running my code:

ost/replica:0/task:0/device:GPU:0
sequential/Dense2/MatMul: (MatMul): /job:localhost/replica:0/task:0/device:GPU:0
sequential/Dense2/BiasAdd/ReadVariableOp: (ReadVariableOp): /job:localhost/replica:0/task:0/device:GPU:0
sequential/Dense2/BiasAdd: (BiasAdd): /job:localhost/replica:0/task:0/device:GPU:0
sequential/batch_normalization_1/batchnorm/ReadVariableOp: (ReadVariableOp): /job:localhost/replica:0/task:0/device:GPU:0
sequential/batch_normalization_1/batchnorm/add: (AddV2): /job:localhost/replica:0/task:0/device:GPU:0
sequential/batch_normalization_1/batchnorm/Rsqrt: (Rsqrt): /job:localhost/replica:0/task:0/device:GPU:0
sequential/batch_normalization_1/batchnorm/mul/ReadVariableOp: (ReadVariableOp): /job:localhost/replica:0/task:0/device:GPU:0
sequential/batch_normalization_1/batchnorm/mul: (Mul): /job:localhost/replica:0/task:0/device:GPU:0
sequential/batch_normalization_1/batchnorm/mul_1: (Mul): /job:localhost/replica:0/task:0/device:GPU:0
sequential/batch_normalization_1/batchnorm/ReadVariableOp_1: (ReadVariableOp): /job:localhost/replica:0/task:0/device:GPU:0
sequential/batch_normalization_1/batchnorm/mul_2: (Mul): /job:localhost/replica:0/task:0/device:GPU:0
sequential/batch_normalization_1/batchnorm/ReadVariableOp_2: (ReadVariableOp): /job:localhost/replica:0/task:0/device:GPU:0
sequential/batch_normalization_1/batchnorm/sub: (Sub): /job:localhost/replica:0/task:0/device:GPU:0
sequential/batch_normalization_1/batchnorm/add_1: (AddV2): /job:localhost/replica:0/task:0/device:GPU:0
sequential/activation_1/Relu: (Relu): /job:localhost/replica:0/task:0/device:GPU:0
sequential/dropout_1/Identity: (Identity): /job:localhost/replica:0/task:0/device:GPU:0
sequential/Dense3/MatMul/ReadVariableOp: (ReadVariableOp): /job:localhost/replica:0/task:0/device:GPU:0
sequential/Dense3/MatMul: (MatMul): /job:localhost/replica:0/task:0/device:GPU:0
sequential/Dense3/BiasAdd/ReadVariableOp: (ReadVariableOp): /job:localhost/replica:0/task:0/device:GPU:0
sequential/Dense3/BiasAdd: (BiasAdd): /job:localhost/replica:0/task:0/device:GPU:0
sequential/batch_normalization_2/batchnorm/ReadVariableOp: (ReadVariableOp): /job:localhost/replica:0/task:0/device:GPU:0
sequential/batch_normalization_2/batchnorm/add: (AddV2): /job:localhost/replica:0/task:0/device:GPU:0
sequential/batch_normalization_2/batchnorm/Rsqrt: (Rsqrt): /job:localhost/replica:0/task:0/device:GPU:0
sequential/batch_normalization_2/batchnorm/mul/ReadVariableOp: (ReadVariableOp): /job:localhost/replica:0/task:0/device:GPU:0
sequential/batch_normalization_2/batchnorm/mul: (Mul): /job:localhost/replica:0/task:0/device:GPU:0
sequential/batch_normalization_2/batchnorm/mul_1: (Mul): /job:localhost/replica:0/task:0/device:GPU:0
sequential/batch_normalization_2/batchnorm/ReadVariableOp_1: (ReadVariableOp): /job:localhost/replica:0/task:0/device:GPU:0
sequential/batch_normalization_2/batchnorm/mul_2: (Mul): /job:localhost/replica:0/task:0/device:GPU:0
sequential/batch_normalization_2/batchnorm/ReadVariableOp_2: (ReadVariableOp): /job:localhost/replica:0/task:0/device:GPU:0
sequential/batch_normalization_2/batchnorm/sub: (Sub): /job:localhost/replica:0/task:0/device:GPU:0
sequential/batch_normalization_2/batchnorm/add_1: (AddV2): /job:localhost/replica:0/task:0/device:GPU:0
sequential/activation_2/Softmax: (Softmax): /job:localhost/replica:0/task:0/device:GPU:0
Identity: (Identity): /job:localhost/replica:0/task:0/device:GPU:0
identity_RetVal: (_Retval): /job:localhost/replica:0/task:0/device:GPU:0
Const: (Const): /job:localhost/replica:0/task:0/device:GPU:0
sequential/batch_normalization/batchnorm/add/y: (Const): /job:localhost/replica:0/task:0/device:GPU:0
sequential/batch_normalization_1/batchnorm/add/y: (Const): /job:localhost/replica:0/task:0/device:GPU:0
sequential/batch_normalization_2/batchnorm/add/y: (Const): /job:localhost/replica:0/task:0/device:GPU:0
Traceback (most recent call last):
File "debug.py", line 198, in 
testPredictions = model.predict(test,
File "/users/zl/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 88, in _method_wrapper
return method(self, *args, **kwargs)
File "/users/zl/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1268, in predict
tmp_batch_outputs = predict_function(iterator)
File "/users/zl132/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 580, in call
result = self._call(*args, **kwds)
File "/users/zl/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 618, in _call
results = self._stateful_fn(*args, **kwds)
File "/users/zl/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2420, in call
return graph_function._filtered_call(args, kwargs) # pylint: disable=protected-access
File "/users/zl/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1661, in _filtered_call
return self._call_flat(
File "/users/zl/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1745, in _call_flat
return self._build_call_outputs(self._inference_function.call(
File "/users/zl/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 593, in call
outputs = execute.execute(
File "/users/zl/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
(0) Invalid argument: ValueError: generator yielded an element of shape () where an element of shape (None, None) was expected.
Traceback (most recent call last):

File "/users/zl/anaconda3/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 243, in call
ret = func(*args)

File "/users/zl/anaconda3/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 309, in wrapper
return func(*args, **kwargs)

File "/users/zl/anaconda3/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 819, in generator_py_func
raise ValueError(

ValueError: generator yielded an element of shape () where an element of shape (None, None) was expected.

 [[{{node PyFunc}}]]
 [[IteratorGetNext]]
(1) Invalid argument: ValueError: generator yielded an element of shape () where an element of shape (None, None) was expected.
Traceback (most recent call last):

File "/users/zl/anaconda3/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 243, in call
ret = func(*args)

File "/users/zl/anaconda3/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 309, in wrapper
return func(*args, **kwargs)

File "/users/zl/anaconda3/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 819, in generator_py_func
raise ValueError(

ValueError: generator yielded an element of shape () where an element of shape (None, None) was expected.

 [[{{node PyFunc}}]]
 [[IteratorGetNext]]
 [[IteratorGetNext/_2]]
0 successful operations.
0 derived errors ignored. [Op:__inference_predict_function_500]

Function call stack:
predict_function -> predict_function

++++++++++++++++++++++++++

functions:

class predictGenerator(keras.utils.Sequence):
def init(self, data_file, num_samples, batch_size):
sys.stderr.write('generator initiated\n')
self.batch_size = batch_size
self.data_file = data_file
self.num_samples = num_samples
self.data = pd.read_csv(data_file,
compression='gzip',
sep='\t',
chunksize=batch_size)
self.nb = 0
self.sample_names = []

def __len__(self):
    return int(np.ceil(float(self.num_samples) / float(self.batch_size)))

def __getitem__(self, index):
    for X in self.data:
        self.nb += 1
        self.sample_names.append(X.index)
        sys.stderr.write('\ngenerator yielded a batch %d \n' % self.nb)
        sys.stderr.write('size: %d \n' % X.shape[0])
        return np.array(X)

def get_sample_names(self):
    return list(itertools.chain.from_iterable(self.sample_names))
test = predictGenerator(testCountsFile, num_test_samples, batch_size)
testPredictions = model.predict(test,
steps=np.ceil(num_test_samples / batch_size),
verbose=1)

++++++++++++++++++++++++
keras 2.4.3
tensorflow 2.2.0

Thank you!!

**Comment by ravikiranrao** [comment]
@lizhaozhi I am encountering the sam error. Did you find any solution. Would be much appreciated :-)
