### ISSUE TITLE
can't perform image preprocessing in 3d convolutional neural network

### ISSUE THREAD

**Issue by Gaurav7888** [keras-team/keras#14318]
Input to `.fit()` should have rank 4

**Comment by yash-clear** [comment]
I can't understand your question.

**Comment by sushreebarsa** [comment]
@Gaurav7888 In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by sushreebarsa** [comment]
Closing this issue due to lack of recent activity & assuming this issue as resolved .Please feel free to reopen if you still have concern.Thanks!
