### ISSUE TITLE
How to slice a tensor in keras with variable indices?

### ISSUE THREAD

**Issue by ShivamP1993** [keras-team/keras#14315]
I have an image of size 100x120x3. After applying convolutions on original image, I want to get a subset/patch from the image, of size 11x11, during training. The patch would be centered around indices "index1" and "index2". The code I am trying is written below. The dimensions of `feats_new` is same as that of the image. Google colaboratory is being use for implementation.

`x = Input(shape=(100,120,3), name='inputA')`
`index1 = Input(shape=(1,), name='ind1', dtype = 'int32')`
`index2 = Input(shape=(1,), name='ind2', dtype = 'int32')`

`feats_new = encoder(x)`
`patch = feats_new[:,index1-5:index1+6, index2-5:index2+6,:]`

I get the following errors on execution:

`TypeError: Cannot convert a symbolic Keras input/output to a numpy`
`array. This error may indicate that you are trying to pass a`
`symbolic value to a NumPy call, which is not supported. Or, you may`
`be trying to pass Keras symbolic inputs/outputs to a TF API that`
`does not register dispatching, preventing Keras from automatically`
`converting the API call to a lambda layer in the Functional Model.`

and

`ValueError: Shapes must be equal rank, but are 2 and 0`
`From merging shape 2 with other shapes. `
`For '{{nodetf.__operators__.getitem_11/strided_slice/stack_2}} =`
`Pack[N=4,   T=DT_INT32, axis=0 `
`(tf.__operators__.getitem_11/strided_slice/stack_2/values_0,`
 `Placeholder_1, Placeholder_3,`
 `tf.__operators__.getitem_11/strided_slice/stack_2/values_3)' with`
 `input shapes: [], [?,1], [?,1], []`

How can I get the patch?

**Comment by adhilcodes** [comment]
Is it a problem related to broadcasting during matrix multiplication

**Comment by ShivamP1993** [comment]
No. I think the problem is that the input defined in keras in this form `index1 = Input(shape=(1,), name='ind1', dtype = 'int32')` cannot be used as index because its shape is (None,1). But I need it in this format because the index will change for every sample in the batch. Hence I want to give the index as numpy array during training and testing.

**Comment by sushreebarsa** [comment]
@ShivamP1993 Sorry for the late response! 
The normal way to go is to pad your inputs to the same maximum length before batching.Please refer to this [tensor slicing  ](https://www.tensorflow.org/guide/tensor_slicing) and  try with latest TF v2.7.0 .Please let us know if it helps?Thanks!

**Comment by ShivamP1993** [comment]
> @ShivamP1993 Sorry for the late response! The normal way to go is to pad your inputs to the same maximum length before batching.Please refer to this [tensor slicing ](https://www.tensorflow.org/guide/tensor_slicing) and try with latest TF v2.7.0 .Please let us know if it helps?Thanks!

This method is about general slicing of tensors. The problem comes when I want to use the indices for slicing as input in a Keras based model (using "Input" layer) and use that "Input" for slicing.

**Comment by gadagashwini** [comment]
@ShivamP1993,
Use Lambda layer to slice the Keras input

```
import tensorflow as tf
x = tf.keras.Input(shape=(100,120,3), name='inputA')
sliced_input = tf.keras.layers.Lambda(lambda x: x[:,:,0])
```
