### ISSUE TITLE
Issue with predicting classes for an uploaded input image using Flask Web app

### ISSUE THREAD

**Issue by Anishauday** [keras-team/keras#14323]
I tried developing a very simple flask app to see my DL Model class prediction output. When I deployed a web app for a CNN model I built from scratch. It worked fine. But when I tried deploying something similar for a Mobilenet pretrained model with my custome dataset of 4 classes. I'm facing issue while preprocessing the input image. Please find below find below my app.py code for reference.

```
@app.route("/upload", methods=["POST"])  
to/upload
def upload():
    target=os.path.join(APP_ROOT, 'images/')
    print(target)
    if not os.path.isdir(target):
           os.mkdir(target)
    else:
         print("Couldn't create upload directory: {}".format(target))
    print(request.files.getlist("file"))  #upload multiple files
    for upload in request.files.getlist("file"):
        print(upload)
        print("{} is the file name".format(upload.filename))
        filename = upload.filename
        destination = "/".join([target, filename])
        print("Accepting incoming file", filename)
        print("Save it to:", destination)
        upload.save(destination)
                
        import numpy as np
        import tensorflow as tf
        from tensorflow.keras.preprocessing import image
        from tensorflow.keras.models import load_model
        from keras.applications.mobilenet import MobileNet, preprocess_input
                
        new_model = load_model('model.h5')    #create var new_model for the file model.h5
        new_model.summary()
        def prepare_image(files):
            test_image = image.load_img('images\\'+files,target_size=(224,224))
            test_image = image.img_to_array(test_image)          
            test_image = np.expand_dims(test_image, axis=0)
        return tf.keras.applications.mobilenet.preprocess_input
        image = prepare_image('filename')             
        result = new_model.predict(image)              
        result1 = result[0]                                 
        for i in range (4):                                # class count is 4
            if result1[i] == 1.:                          #
                break;
        prediction = classes[i]
    return render_template("template.html",image_name=filename, text=prediction)

```
I assume I'm doing smething wrong while preprocessing the image. the error I'm getting is 

> File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\applications\mobilenet.py", line 445, in preprocess_input
>     return imagenet_utils.preprocess_input(x, data_format=data_format, mode='tf')
>   File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\applications\imagenet_utils.py", line 112, in preprocess_input
>     raise ValueError('Unknown data_format ' + str(data_format))
> ValueError: Unknown data_format <function run_wsgi_app.<locals>.start_response at 0x000002CE8795E5E0>
> 127.0.0.1 - - [22/Dec/2020 11:25:55] "[35m[1mPOST /upload HTTP/1.1[0m" 500 -

Please help!

**Comment by jvishnuvardhan** [comment]
@Anishauday Can you please share a simple standalone code to reproduce the issue? Did you face any error while training? Thanks!
