### ISSUE TITLE
ValueError: A target array with shape (180568, 80) was passed for an output of shape (None, 180568) while using as loss `categorical_crossentropy`. This loss expects targets to have the same shape as the output.

### ISSUE THREAD

**Issue by jpandeinge** [keras-team/keras#14343]
I am trying to implement a 1D  CNN from a network encrypted traffic classification and Intrusion detection dataset. Here is the snippet of my codes 

```
# The next step is to split training and testing data. For this we will use sklearn function train_test_split().
features_train, features_test, labels_train, labels_test = train_test_split(features, labels, test_size=.2)

features_train.shape, features_test.shape, labels_train.shape, labels_test.shape

((180568, 80), (45143, 80), (180568,), (45143,))

```

```
# Here I'm assuming some dummy data
# Xtrain => [180568, 80, 1] (Note that you need Xtrain to be 3D not 2D - So we're adding a channel dimension of 1)
Xtrain = np.expand_dims(np.random.normal(size=(180568, 80)), axis=-1)
# Ytrain => [180568, 10]
Ytrain = np.random.choice([0,1], size=(180568, 80))

# check shape
Xtrain.shape, Ytrain.shape

((180568, 80, 1), (180568, 80))
```
```
n_timesteps, n_features, n_outputs = features_train.shape[0], features_train.shape[1], labels_train.shape[0]

model = Sequential()
model.add(Conv1D(filters=64, kernel_size=1, activation='relu',input_shape=(n_features, 1)))
model.add(Conv1D(filters=64, kernel_size=1, activation='relu'))
model.add(Dropout(0.5))
model.add(MaxPooling1D(pool_size=3))
model.add(Flatten())
model.add(Dense(80, activation='relu'))
model.add(Dense(n_outputs, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

```
```
# fit network
model.fit(Xtrain, Ytrain, epochs=10, batch_size=10, verbose=0)
```

After I try to fit the model, i however get the following error.

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-101-da6e32acea16> in <module>
      1 # fit network
----> 2 model.fit(Xtrain, Ytrain, epochs=10, batch_size=10, verbose=0)

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_v1.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    783         max_queue_size=max_queue_size,
    784         workers=workers,
--> 785         use_multiprocessing=use_multiprocessing)
    786 
    787   def evaluate(self,

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_arrays.py in fit(self, model, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, **kwargs)
    632         steps=steps_per_epoch,
    633         validation_split=validation_split,
--> 634         shuffle=shuffle)
    635 
    636     if validation_data:

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_v1.py in _standardize_user_data(self, x, y, sample_weight, class_weight, batch_size, check_steps, steps_name, steps, validation_split, shuffle, extract_tensors_from_dataset)
   2306         is_dataset=is_dataset,
   2307         class_weight=class_weight,
-> 2308         batch_size=batch_size)
   2309 
   2310   def _standardize_tensors(self, x, y, sample_weight, run_eagerly, dict_inputs,

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_v1.py in _standardize_tensors(self, x, y, sample_weight, run_eagerly, dict_inputs, is_dataset, class_weight, batch_size)
   2412           # Additional checks to avoid users mistakenly using improper loss fns.
   2413           training_utils.check_loss_and_target_compatibility(
-> 2414               y, self._feed_loss_fns, feed_output_shapes)
   2415 
   2416       sample_weights, _, _ = training_utils.handle_partial_sample_weights(

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_utils.py in check_loss_and_target_compatibility(targets, loss_fns, output_shapes)
    808           raise ValueError('A target array with shape ' + str(y.shape) +
    809                            ' was passed for an output of shape ' + str(shape) +
--> 810                            ' while using as loss `' + loss_name + '`. '
    811                            'This loss expects targets to have the same shape '
    812                            'as the output.')

ValueError: A target array with shape (180568, 80) was passed for an output of shape (None, 180568) while using as loss `categorical_crossentropy`. This loss expects targets to have the same shape as the output.

```

**Comment by yash-clear** [comment]
@jpandeinge 
dimensions of Ytrain is not correct, try using Ytrain.shape=(180568,)

**Comment by jpandeinge** [comment]
@yash-clear tried to change it as you suggested and it has been running for an hour now without any output

**Comment by yash-clear** [comment]
@jpandeinge 
try this,
`import numpy as np
import tensorflow as tf
import pandas as pd
from tensorflow.keras import optimizers
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Conv1D, MaxPooling1D, Embedding,Flatten

from sklearn.model_selection import train_test_split

X_train = np.zeros((180568, 80, 1))
y_train = np.zeros((180568, 80))
n_timesteps, n_features, n_outputs =  X_train.shape[1], X_train.shape[2], y_train.shape[1]
n_samples = 1000

X = np.random.uniform(0,1, (n_samples, n_timesteps, n_features))
y = pd.get_dummies(np.random.randint(0,n_outputs, n_samples)).values

    
model = tf.keras.models.Sequential([
tf.keras.layers.Conv1D(input_shape=(n_timesteps, n_features), kernel_size=3, filters=16),
tf.keras.layers.GlobalAveragePooling1D(), # also GlobalMaxPooling1D() is ok
tf.keras.layers.Dense(256, activation='relu'),
tf.keras.layers.Dropout(0.2),
tf.keras.layers.Dense(n_outputs, activation='softmax')
])

model.compile('adam', 'categorical_crossentropy')
model.fit(X,y, epochs=2,verbose=1)
model.summary()`

## output
![output](https://user-images.githubusercontent.com/68466214/103633396-ac8dc800-4f6b-11eb-82a2-a9aed0f68f1e.png)

**Comment by yash-clear** [comment]
well I used GlobalAveragePooling1D() instead of MaxPooling1D which in turn  compresses the temporal dimension.

**Comment by yash-clear** [comment]
I want to make my first contribution ,tell me if it is ok then I will send pull request.

**Comment by jpandeinge** [comment]
> @jpandeinge
> try this,
> `import numpy as np
> import tensorflow as tf
> import pandas as pd
> from tensorflow.keras import optimizers
> from tensorflow.keras.preprocessing import sequence
> from tensorflow.keras.models import Sequential
> from tensorflow.keras.layers import Dense, Dropout, Activation, Conv1D, MaxPooling1D, Embedding,Flatten
> 
> from sklearn.model_selection import train_test_split
> 
> X_train = np.zeros((180568, 80, 1))
> y_train = np.zeros((180568, 80))
> n_timesteps, n_features, n_outputs = X_train.shape[1], X_train.shape[2], y_train.shape[1]
> n_samples = 1000
> 
> X = np.random.uniform(0,1, (n_samples, n_timesteps, n_features))
> y = pd.get_dummies(np.random.randint(0,n_outputs, n_samples)).values
> 
> model = tf.keras.models.Sequential([
> tf.keras.layers.Conv1D(input_shape=(n_timesteps, n_features), kernel_size=3, filters=16),
> tf.keras.layers.GlobalAveragePooling1D(), # also GlobalMaxPooling1D() is ok
> tf.keras.layers.Dense(256, activation='relu'),
> tf.keras.layers.Dropout(0.2),
> tf.keras.layers.Dense(n_outputs, activation='softmax')
> ])
> 
> model.compile('adam', 'categorical_crossentropy')
> model.fit(X,y, epochs=2,verbose=1)
> model.summary()`
> ## output
> 
> ![output](https://user-images.githubusercontent.com/68466214/103633396-ac8dc800-4f6b-11eb-82a2-a9aed0f68f1e.png)

This is working and I really appreciate, just a few tweaks I need to do and shall be fine
