### ISSUE TITLE
No module named 'keras' Jupyter Notebook

### ISSUE THREAD

**Issue by RecepBlby** [keras-team/keras#14344]
Hello.
I am using windows 10. I tried to install keras in windows prompt and anaconda prompt:
pip install keras
conda install keras 
they do not work. 
![image](https://user-images.githubusercontent.com/47719328/103559496-e5239800-4ebe-11eb-858d-895ea056e860.png)
 AttributeError: type object 'Callable' has no attribute '_abc_registry'
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\python\python.exe' 'c:\python\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\Recep\AppData\Local\Temp\pip-build-env-u1bm0m16\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel Check the logs for full command output.

I have got this error in windows prompt. 
Conda : Collecting package metadata (current_repodata.json): done
Solving environment: \
and nothing more.

Can you please help me?

**Comment by sulaiman12-34-ai** [comment]
ModuleNotFoundError: No module named 'keras.legacy'

**Comment by sulaiman12-34-ai** [comment]
please solve this problem

**Comment by sebaspv** [comment]
Did you re-run the jupyter environment? That happens sometimes when you install keras while being in a jupyter notebook and then trying to import it

**Comment by sushreebarsa** [comment]
@RecepBlby Could you please refer to this [link](https://github.com/antoniosehk/keras-tensorflow-windows-installation)  , [link1 ](https://www.educative.io/edpresso/how-to-install-keras-in-anaconda)  and let us know if it helps ? Thanks!

**Comment by sushreebarsa** [comment]
Closing this issue due to lack of recent activity & assuming this issue as resolved .Please feel free to reopen if you still have concern.Thanks!
