### ISSUE TITLE
 ValueError: Shapes (None, None) and (None, 7, 7, 67) are incompatible .. What's wrong with my code? 

### ISSUE THREAD

**Issue by shuaibaslam2019** [keras-team/keras#14341]
` 
```
inputs_1 = keras.Input(shape=(224, 224, 3), name="input_01")

inputs_2 = keras.Input(shape=(224, 224, 3), name="input_02")

vgg = VGG16(input_tensor=inputs_1, weights='imagenet', include_top=False)
    layer.trainable = False 

resnet = ResNet50(input_tensor=inputs_2, weights='imagenet', include_top=False) 
for layer in resnet.layers:
    layer.trainable = False

mergedOutput = keras.layers.concatenate([vgg.output, resnet.output])
print("merged output", mergedOutput)
x = layers.Dense(4096, activation="relu")(mergedOutput)
prediction = layers.Dense(67, activation='softmax')(x)
model = Model(inputs=[inputs_1, inputs_2], outputs=prediction)

model.compile(loss="categorical_crossentropy",optimizer='adam',metrics=['accuracy'])


train_datagen = ImageDataGenerator(
    rescale = 1./255,
    shear_range = 0.2,
    zoom_range = 0.2,
    horizontal_flip = True,
)

test_dataset = ImageDataGenerator(rescale=1./255)

dir_1 = '/scenes_classifiers/RESNET/indoor/train'
dir_2 = '/scenes_classifiers/RESNET/indoor/val'


def generate_generator_multiple(generator,dir1, dir2, batch_size, img_height,img_width):
    
    genX1 = generator.flow_from_directory(dir1,
                                          target_size = (img_height,img_width),
                                          class_mode = 'categorical',
                                          batch_size = batch_size,
                                          shuffle=False, 
                                          seed=7)
    
    genX2 = generator.flow_from_directory(dir2,
                                          target_size = (img_height,img_width),
                                          class_mode = 'categorical',
                                          batch_size = batch_size,
                                          shuffle=False, 
                                          seed=7)
    while True:
            X1i = genX1.next()
            X2i = genX2.next()
            yield [X1i[0], X2i[0]], X2i[1]  #Yield both images and their mutual label
            
            
inputgenerator=generate_generator_multiple(generator=train_datagen,
                                           dir1=dir_1,
                                           dir2=dir_1,
                                           batch_size=32,
                                           img_height=224,
                                           img_width=224)       
     
testgenerator=generate_generator_multiple(generator=test_datagen,
                                           dir1=dir_2,
                                           dir2=dir_2,
                                           batch_size=32,
                                           img_height=224,
                                           img_width=224)              
 history = model.fit(
    inputgenerator,
    steps_per_epoch=8,
    epochs = 200,
    validation_data = testgenerator,
    validation_steps=2
)
```
`

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-85-bb93111aeddb> in <module>
     81 
     82 
---> 83 history = model.fit(
     84     inputgenerator,
     85     steps_per_epoch=8,

~/.conda/envs/aslam_env/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py in _method_wrapper(self, *args, **kwargs)
     64   def _method_wrapper(self, *args, **kwargs):
     65     if not self._in_multi_worker_mode():  # pylint: disable=protected-access
---> 66       return method(self, *args, **kwargs)
     67 
     68     # Running inside `run_distribute_coordinator` already.

~/.conda/envs/aslam_env/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
    846                 batch_size=batch_size):
    847               callbacks.on_train_batch_begin(step)
--> 848               tmp_logs = train_function(iterator)
    849               # Catch OutOfRangeError for Datasets of unknown size.
    850               # This blocks until the batch has finished executing.

~/.conda/envs/aslam_env/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
    578         xla_context.Exit()
    579     else:
--> 580       result = self._call(*args, **kwds)
    581 
    582     if tracing_count == self._get_tracing_count():

~/.conda/envs/aslam_env/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
    625       # This is the first call of __call__, so we have to initialize.
    626       initializers = []
--> 627       self._initialize(args, kwds, add_initializers_to=initializers)
    628     finally:
    629       # At this point we know that the initialization is complete (or less

~/.conda/envs/aslam_env/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in _initialize(self, args, kwds, add_initializers_to)
    503     self._graph_deleter = FunctionDeleter(self._lifted_initializer_graph)
    504     self._concrete_stateful_fn = (
--> 505         self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
    506             *args, **kwds))
    507 

~/.conda/envs/aslam_env/lib/python3.8/site-packages/tensorflow/python/eager/function.py in _get_concrete_function_internal_garbage_collected(self, *args, **kwargs)
   2444       args, kwargs = None, None
   2445     with self._lock:
-> 2446       graph_function, _, _ = self._maybe_define_function(args, kwargs)
   2447     return graph_function
   2448 

~/.conda/envs/aslam_env/lib/python3.8/site-packages/tensorflow/python/eager/function.py in _maybe_define_function(self, args, kwargs)
   2775 
   2776       self._function_cache.missed.add(call_context_key)
-> 2777       graph_function = self._create_graph_function(args, kwargs)
   2778       self._function_cache.primary[cache_key] = graph_function
   2779       return graph_function, args, kwargs

~/.conda/envs/aslam_env/lib/python3.8/site-packages/tensorflow/python/eager/function.py in _create_graph_function(self, args, kwargs, override_flat_arg_shapes)
   2655     arg_names = base_arg_names + missing_arg_names
   2656     graph_function = ConcreteFunction(
-> 2657         func_graph_module.func_graph_from_py_func(
   2658             self._name,
   2659             self._python_function,

~/.conda/envs/aslam_env/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes)
    979         _, original_func = tf_decorator.unwrap(python_func)
    980 
--> 981       func_outputs = python_func(*func_args, **func_kwargs)
    982 
    983       # invariant: `func_outputs` contains only Tensors, CompositeTensors,

~/.conda/envs/aslam_env/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in wrapped_fn(*args, **kwds)
    439         # __wrapped__ allows AutoGraph to swap in a converted function. We give
    440         # the function a weak reference to itself to avoid a reference cycle.
--> 441         return weak_wrapped_fn().__wrapped__(*args, **kwds)
    442     weak_wrapped_fn = weakref.ref(wrapped_fn)
    443 

~/.conda/envs/aslam_env/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py in wrapper(*args, **kwargs)
    966           except Exception as e:  # pylint:disable=broad-except
    967             if hasattr(e, "ag_error_metadata"):
--> 968               raise e.ag_error_metadata.to_exception(e)
    969             else:
    970               raise

ValueError: in user code:

    /home/aslam/.conda/envs/aslam_env/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:571 train_function  *
        outputs = self.distribute_strategy.run(
    /home/aslam/.conda/envs/aslam_env/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:951 run  **
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /home/aslam/.conda/envs/aslam_env/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:2290 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /home/aslam/.conda/envs/aslam_env/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:2649 _call_for_each_replica
        return fn(*args, **kwargs)
    /home/aslam/.conda/envs/aslam_env/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:532 train_step  **
        loss = self.compiled_loss(
    /home/aslam/.conda/envs/aslam_env/lib/python3.8/site-packages/tensorflow/python/keras/engine/compile_utils.py:205 __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    /home/aslam/.conda/envs/aslam_env/lib/python3.8/site-packages/tensorflow/python/keras/losses.py:143 __call__
        losses = self.call(y_true, y_pred)
    /home/aslam/.conda/envs/aslam_env/lib/python3.8/site-packages/tensorflow/python/keras/losses.py:246 call
        return self.fn(y_true, y_pred, **self._fn_kwargs)
    /home/aslam/.conda/envs/aslam_env/lib/python3.8/site-packages/tensorflow/python/keras/losses.py:1527 categorical_crossentropy
        return K.categorical_crossentropy(y_true, y_pred, from_logits=from_logits)
    /home/aslam/.conda/envs/aslam_env/lib/python3.8/site-packages/tensorflow/python/keras/backend.py:4561 categorical_crossentropy
        target.shape.assert_is_compatible_with(output.shape)
    /home/aslam/.conda/envs/aslam_env/lib/python3.8/site-packages/tensorflow/python/framework/tensor_shape.py:1117 assert_is_compatible_with
        raise ValueError("Shapes %s and %s are incompatible" % (self, other))

    ValueError: Shapes (None, None) and (None, 7, 7, 67) are incompatible
​

**Comment by kbfreder** [comment]
I think this is a bug. I encountered a similar error when trying to use `ImageDataGenerator.flow_from_directory` with `class_mode` = "category" and my model loss and metric set to CategoricalCrossentropy and CategoricalAccuracy. Setting everything to "sparse" did the trick. I am dealing with a multi-class classification

tensorflow 2.4.1
keras 2.4.3
python 3.7.10

This does not work:
```python
data_augmentation = ImageDataGenerator(
    rotation_range=2,
    shear_range=2,
    vertical_flip=True,
    fill_mode='nearest',
    width_shift_range=0.05,
    height_shift_range=0.05,
    validation_split=0.25
)

train_gen = data_augmentation.flow_from_directory(
    data_dir,
    subset="training",
    class_mode="categorical" # this should yield one-hot-encoded classes
)

val_gen = data_augmentation.flow_from_directory(
   data_dir,
    subset="validation",
    class_mode="categorical"
)

# define our base model 
base_model = VGG19(
    weights="imagenet",
    input_shape=img_size,
    include_top=False
)

# Freeze it
base_model.trainable = False

# create new model on top
inputs = keras.Input(shape=img_size)
x = base_model(inputs, training=False)
x = keras.layers.GlobalAveragePooling2D()(x)
outputs = keras.layers.Dense(4)(x)

model = keras.Model(inputs, outputs)

model.compile(
    optimizer="adam",
    loss=keras.losses.CategoricalCrossentropy(),
    metrics=[keras.metrics.CategoricalAccuracy()]
)

model.fit(
    train_gen,
    epochs=20,
    validation_data=val_gen
)
```

The stack trace:
```
Epoch 1/20
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-40-e91a23893c9e> in <module>
      2     train_gen,
      3     epochs=20,
----> 4     validation_data=val_gen
      5 )

~/anaconda3/envs/cv/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
   1098                 _r=1):
   1099               callbacks.on_train_batch_begin(step)
-> 1100               tmp_logs = self.train_function(iterator)
   1101               if data_handler.should_sync:
   1102                 context.async_wait()

~/anaconda3/envs/cv/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
    826     tracing_count = self.experimental_get_tracing_count()
    827     with trace.Trace(self._name) as tm:
--> 828       result = self._call(*args, **kwds)
    829       compiler = "xla" if self._experimental_compile else "nonXla"
    830       new_tracing_count = self.experimental_get_tracing_count()

~/anaconda3/envs/cv/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
    886         # Lifting succeeded, so variables are initialized and we can run the
    887         # stateless function.
--> 888         return self._stateless_fn(*args, **kwds)
    889     else:
    890       _, _, _, filtered_flat_args = \

~/anaconda3/envs/cv/lib/python3.7/site-packages/tensorflow/python/eager/function.py in __call__(self, *args, **kwargs)
   2941        filtered_flat_args) = self._maybe_define_function(args, kwargs)
   2942     return graph_function._call_flat(
-> 2943         filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
   2944 
   2945   @property

~/anaconda3/envs/cv/lib/python3.7/site-packages/tensorflow/python/eager/function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1917       # No tape is watching; skip to running the function.
   1918       return self._build_call_outputs(self._inference_function.call(
-> 1919           ctx, args, cancellation_manager=cancellation_manager))
   1920     forward_backward = self._select_forward_and_backward_functions(
   1921         args,

~/anaconda3/envs/cv/lib/python3.7/site-packages/tensorflow/python/eager/function.py in call(self, ctx, args, cancellation_manager)
    558               inputs=args,
    559               attrs=attrs,
--> 560               ctx=ctx)
    561         else:
    562           outputs = execute.execute_with_cancellation(

~/anaconda3/envs/cv/lib/python3.7/site-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     58     ctx.ensure_initialized()
     59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:
     62     if name is not None:

InvalidArgumentError:  Incompatible shapes: [32,4] vs. [32,5]
	 [[node gradient_tape/categorical_crossentropy/mul/BroadcastGradientArgs (defined at <ipython-input-40-e91a23893c9e>:4) ]] [Op:__inference_train_function_3277]

Function call stack:
train_function
```

If I make these changes, I am able to fit the model:
```
train_gen = data_augmentation.flow_from_directory(
    cfg.PNG_DIR,
    subset="training",
    class_mode="sparse" # this should yield an integer
)

val_gen = data_augmentation.flow_from_directory(
    cfg.PNG_DIR,
    subset="validation",
    class_mode="sparse"
)

model = keras.Model(inputs, outputs)

model.compile(
    optimizer="adam", 
    loss=keras.losses.SparseCategoricalCrossentropy(),
    metrics=[keras.metrics.SparseCategoricalAccuracy()]
)

history = model.fit(
    train_gen,
    epochs=20,
    validation_data=val_gen
)
```

**Comment by sushreebarsa** [comment]
@shuaibaslam2019 Sorry for the late response! Is this still an issue?
 Could you please refer to the Image data [link](https://keras.io/api/preprocessing/image/) ,[ImageDataGenerator](https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/image/ImageDataGenerator) and let us know if it helps? To fix this issue, you need to reshape the input tensor  before training your model.Thanks!

**Comment by SamMohel** [comment]
how can i solve this issue please ?

**Comment by shuaibaslam2019** [comment]
@SamMohel what exactly issue you're facing could you give us enough code to reproduce that? If so, it would be nice to share in on Kaggle.

**Comment by berihunmolla** [comment]
Who are you and what are you saying for?
______________________________________
It is enough to be human to help someone
 Peace for all mankind
        link:     https://www.youtube.com/c/SamiTechnology/playlists
*Berihun Molla (** MSc (IT)  @ JU-JiT**, ** BSc (CS)  @ BDU-BiT )*
*                                                           ORCID** :
** https://orcid.org/0000-0002-8602-87
<https://orcid.org/0000-0002-8602-8770>*
     *Google scholar ID* :  h <https://scholar.google.com/citations>
ttps://scholar.google.com/citations <https://scholar.google.com/citations>
?hl=en&user=4T5qWl8AAAAJ
*Lecturer @ Arbaminch university *
*mobile:+2519 22 0176 33*
*emai: ***@***.*** ***@***.***>*
***@***.*** ***@***.***>*
