### ISSUE TITLE
min pooling layer

### ISSUE THREAD

**Issue by yash-clear** [keras-team/keras#14355]
should we add minimum pooling layer??
Min pooling gives better result for images with white background and black object

**Comment by leo-smi** [comment]
Yes, I was shocked to know keras doesn't have min pooling yet. I was looking for some papers I found this https://medium.com/@bdhuma/which-pooling-method-is-better-maxpooling-vs-minpooling-vs-average-pooling-95fb03f45a9

**Comment by sushreebarsa** [comment]
@yash-clear Could you please refer to [link](https://keras.io/api/layers/pooling_layers/), [link1](https://keras.io/api/layers/) and let us know if it helps? Thanks!

**Comment by AndhikaWB** [comment]
In case some of you need it, I figured that it can be easily implemented like this:

``` python
class MinPooling2D(keras.layers.MaxPooling2D):
    def call(self, inputs):
        return -super().call(-inputs)
```

**Comment by leo-smi** [comment]
> In case some of you need it, I figured that it can be easily implemented like this:
> 
> ```python
> class MinPooling2D(keras.layers.MaxPooling2D):
>     def call(self, inputs):
>         return -super().call(-inputs)
> ```

thank you
