### ISSUE TITLE
Deprecated operations in datasets

### ISSUE THREAD

**Issue by luisleee** [keras-team/keras#14358]
Creating an ndarray from ragged nested sequences is deprecated by numpy. You should specify "dtype=object" to do that. Some of the files in keras/datasets has this problem, which makes annoying warnings.

**Comment by embattle16** [comment]
hey i would love to work on this code. i am fairly new to GIT so a little help would be great!!

**Comment by rmothukuru** [comment]
@luisleee,
Can you please provide the reference link of the documentation so that we can understand where the problem is? Also, can you please let us know why you have **`closed`** [your PR](https://github.com/keras-team/keras/pull/14359)? Thanks!

**Comment by luisleee** [comment]
@rmothukuru reference here: https://numpy.org/doc/stable/release/1.19.0-notes.html#deprecate-automatic-dtype-object-for-ragged-input. I'm sorry that I closed it totally accidental cause I'm not very familiar with that. I'm gonna reopen it now.

**Comment by luisleee** [comment]
I'm so sorry that I've already deleted the repository, but I'm sure that I can make it as soon as possible.🙏

**Comment by luisleee** [comment]
@rmothukuru As I checked the code, I found that the problem has already been fixed. Thanks!
