### ISSUE TITLE
Make sure all arrays contain the same number of samples.

### ISSUE THREAD

**Issue by ajay-kanna** [keras-team/keras#14368]
https://colab.research.google.com/drive/1sy8tBzRY8tHIZVN1NjhtEljJljGaSli8?usp=sharing
please check
code:
X = X/255.0

model = Sequential()

model.add(Conv2D(256, (3, 3), input_shape=X.shape[1:]))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(256, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Flatten())  # this converts our 3D feature maps to 1D feature vectors
model.add(Dense(64))

model.add(Dense(1))
model.add(Activation('sigmoid'))
NAME = "Plastic"

tensorboard = TensorBoard(log_dir="logs/{}".format(NAME))

model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'],
              )

model.fit(X, y,
          batch_size=32,
          epochs=3,
          validation_split=0.3,
          callbacks=[tensorboard])

error:
ValueError                                Traceback (most recent call last)
<ipython-input-28-e34b707af383> in <module>()
     30           epochs=3,
     31           validation_split=0.3,
---> 32           callbacks=[tensorboard])

3 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
   1062           use_multiprocessing=use_multiprocessing,
   1063           model=self,
-> 1064           steps_per_execution=self._steps_per_execution)
   1065 
   1066       # Container that configures and calls `tf.keras.Callback`s.

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/data_adapter.py in __init__(self, x, y, sample_weight, batch_size, steps_per_epoch, initial_epoch, epochs, shuffle, class_weight, max_queue_size, workers, use_multiprocessing, model, steps_per_execution)
   1110         use_multiprocessing=use_multiprocessing,
   1111         distribution_strategy=ds_context.get_strategy(),
-> 1112         model=model)
   1113 
   1114     strategy = ds_context.get_strategy()

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/data_adapter.py in __init__(self, x, y, sample_weights, sample_weight_modes, batch_size, epochs, steps, shuffle, **kwargs)
    272 
    273     num_samples = set(int(i.shape[0]) for i in nest.flatten(inputs)).pop()
--> 274     _check_data_cardinality(inputs)
    275 
    276     # If batch_size is not passed but steps is, calculate from the input data.

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/data_adapter.py in _check_data_cardinality(data)
   1527           label, ", ".join(str(i.shape[0]) for i in nest.flatten(single_data)))
   1528     msg += "Make sure all arrays contain the same number of samples."
-> 1529     raise ValueError(msg)
   1530 
   1531 

ValueError: Data cardinality is ambiguous:
  x sizes: 753
  y sizes: 0
Make sure all arrays contain the same number of samples.

**Comment by ajay-kanna** [comment]
plsssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss plsssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss plsssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss plsssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss plsssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss plsssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss plsssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss plsssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss plsssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss 
same issue

**Comment by TerMinator-spec** [comment]
Seems like length of your `y` array is zero.
I saw your code, looks like you are not appending anything to `y` that's why length of `y` array is zero. The length of both `X` and `y` should be same.
This is your code:
```X = []
y = []
y=nd.array(y)
for features,label in training_data:
    X.append(features)
    #y.append(label)
    nd.array((y,label))```

**Comment by zem-alt** [comment]
ValueError: Data cardinality is ambiguous:
  x sizes: 144
  y sizes: 118
Make sure all arrays contain the same number of samples.
please guide me how to resolve this issue

**Comment by blcklptn** [comment]
## It works fine to me.

```python3
train_data = np.stack(train_data, axis=0)  # <--- np.stack()
train_labels = np.stack(train_labels, axis=0) <--- np.stack()

fc_model.fit(train_data, train_labels, epochs=500, batch_size=32, validation_data=(validation_data, validation_labels))
fc_model.save_weights("./bottleneck_features/violence.hdf5")  # Save weights
```


![image](https://user-images.githubusercontent.com/73552143/169650623-e7b32f2f-8794-4ede-b600-ae0550f060fb.png)

**Comment by niloysarker7** [comment]
hist = model.fit(train_data_features, y_train, epochs=10, batch_size=64)
ValueError: Data cardinality is ambiguous:
  x sizes: 2
  y sizes: 107090
Make sure all arrays contain the same number of samples
need a solution

**Comment by radhikatop** [comment]
I have 30,8900 files to train and 40000 files to validate and my model is giving me valueError
