### ISSUE TITLE
InvalidArgumentError:  indices[120,2] = -1 is not in [0, 10) 	 [[node sequential_3/embedding_3/embedding_lookup (defined at <ipython-input-65-50ea16cb11fb>:5) ]] [Op:__inference_train_function_13886]  Errors may have originated from an input operation. Input Source operations connected to node sequential_3/embedding_3/embedding_lookup:  sequential_3/embedding_3/embedding_lookup/12643 (defined at /home/jpandeinge/anaconda3/lib/python3.7/contextlib.py:112)  Function call stack: train_function

### ISSUE THREAD

**Issue by jpandeinge** [keras-team/keras#14367]
I am trying to train an LSTM network with the following parameters, however, I get the following error 

```
InvalidArgumentError:  indices[120,2] = -1 is not in [0, 10)
	 [[node sequential_3/embedding_3/embedding_lookup (defined at <ipython-input-65-50ea16cb11fb>:5) ]] [Op:__inference_train_function_13886]

Errors may have originated from an input operation.
Input Source operations connected to node sequential_3/embedding_3/embedding_lookup:
 sequential_3/embedding_3/embedding_lookup/12643 (defined at /home/jpandeinge/anaconda3/lib/python3.7/contextlib.py:112)

Function call stack:
train_function
```

Here is a snippet of my code;

```
# The next step is to split training and testing data. For this we will use sklearn function train_test_split().
features_train, features_test, labels_train, labels_test = train_test_split(features, labels, test_size=0.2)

# features and labels shape
features_train.shape, features_test.shape, labels_train.shape, labels_test.shape
```
((180568, 82), (45143, 82), (180568,), (45143,))
```
model = Sequential()
model.add(Embedding(10, 82, input_length=180568))
model.add(LSTM(10, return_sequences=True, input_shape=features_train))
model.add(Activation('sigmoid'))
model.add(Dropout(0.2))
model.build()

model.compile(loss = 'binary_crossentropy',  optimizer='adam', metrics = ['accuracy'])
model.summary()
```

```
Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
embedding_3 (Embedding)      (None, 180568, 82)        820       
_________________________________________________________________
lstm_3 (LSTM)                (None, 180568, 10)        3720      
_________________________________________________________________
activation_3 (Activation)    (None, 180568, 10)        0         
_________________________________________________________________
dropout_3 (Dropout)          (None, 180568, 10)        0         
=================================================================
Total params: 4,540
Trainable params: 4,540
Non-trainable params: 0
________________________
```
```
history = model.fit(features_train,
          labels_train,
          epochs=10,
          batch_size=128)
```

**Comment by gaigai1996** [comment]
i want to know if you have solved this problem, and i need your help, thanks very much

**Comment by sfines-clgx** [comment]
I am also running into the same problem:

The embedding portion of my model is defined as:
`
        absl.logging.warn("Making input for: "+_transformed_name(col))
        ip = keras.layers.Input(shape=(1,), name=_transformed_name(col), dtype='int64')
        vocab = transform_output.vocabulary_by_name(_transformed_name(col))
        vocab_size = len(vocab)+2
        absl.logging.warn(f"Vocab size is: {vocab_size}")
        l = keras.layers.Embedding(input_dim=vocab_size, output_dim=10, name=f"{col}_embed_layer", input_length=1)(ip)
        l = keras.layers.Dense(10, activation=tf.nn.leaky_relu, name=f"{col}_embedding_model")(l)
        embeddings.append(keras.Model(inputs=ip, outputs=l))
`
where col is just a feature name. 

The result is: 
`
  (0) Invalid argument:  indices[19,0] = -1 is not in [0, 9)
	 [[node model_y_dnn/quality_embed_layer/embedding_lookup (defined at /tmp/tmpyunrqqs0/dnn_model.py:164) ]]
  (1) Invalid argument:  indices[19,0] = -1 is not in [0, 9)
	 [[node model_y_dnn/quality_embed_layer/embedding_lookup (defined at /tmp/tmpyunrqqs0/dnn_model.py:164) ]]
	 [[Adadelta/Adadelta/group_deps/NoOp/_185]]
`
I've tried the solutions provided in [this link](https://stackoverflow.com/questions/54176051/invalidargumenterror-indicesi-0-x-is-not-in-0-x-in-keras)

**Comment by sushreebarsa** [comment]
@jpandeinge 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by sfines-clgx** [comment]
I'm not the tagged individual, but the first code block in my comment has code which definitely causes the issue....

**Comment by ohouohouohou** [comment]
> i want to know if you have solved this problem, and i need your help, thanks very much
You can add the follow codes after the 'import' session
config = tf.compat.v1.ConfigProto()
config.gpu_options.allow_growth = True
sess = tf.compat.v1.Session(config=config)

**Comment by Warmer123** [comment]
I have solved the question. Because of the activation function, we should normalize the data so that they range from 0 to 1. The code which I used is followed.
```
from sklearn.preprocessing import MinMaxScaler
min_max_normalizer=MinMaxScaler(feature_range=(0,1))
XSTD=min_max_normalizer.fit_transform(X_train)
XTST = min_max_normalizer.transform(X_test)
```
