### ISSUE TITLE
模式保存问题

### ISSUE THREAD

**Issue by fishermanxzx** [keras-team/keras#14363]
我也是这个问题，然后我让原来的模型和重新加载的模式的权重对比，完全一样的权重，就是预测结果不一样

**Comment by luisleee** [comment]
Translation: I have this problem too, and I ran my original model and the model which was reloaded. Their weight were the same but the result were different.

**Comment by sushreebarsa** [comment]
@fishermanxzx In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by sushreebarsa** [comment]
Closing this issue due to lack of recent activity.Please feel free to reopen if you still have concern.Thanks!
