### ISSUE TITLE
EfficientNet transfer learning and greyscale images

### ISSUE THREAD

**Issue by erotavlas** [keras-team/keras#14373]
Referring to this post on the Keras website [Image classification via fine-tuning with EfficientNet](https://keras.io/examples/vision/image_classification_efficientnet_fine_tuning/)

I don't have color images (they are greyscale) so I only have 1 channel not 3.  So I get this warning when starting the training.

Epoch 1/25
WARNING:tensorflow:Model was constructed with shape (None, None, None, 3) for input KerasTensor(type_spec=TensorSpec(shape=(None, None, None, 3), dtype=tf.float32, name='input_2'), name='input_2', description="created by layer 'input_2'"), but it was called on an input with incompatible shape (None, 240, 240, 1).

However it still continues to train the model.

I was wondering what is the recommended approach for using EfficientNet with greyscale images.  And if the warning is something we can ignore or any action needs to be taken (like convert the training data to color images)

**Comment by sushreebarsa** [comment]
@erotavlas While providing input shape please provide as (IMG_SIZE, IMG_SIZE, 1) while using greyscale image for training, and try with latest TF version .Please let us know if it helps?
Thanks!
