### ISSUE TITLE
Exception has occurred: KeyError 'inputs' when saving model

### ISSUE THREAD

**Issue by aginpatrick** [keras-team/keras#14374]
In TF  2.3.0, I'm training a keras Retinanet model (code from https://github.com/fizyr/keras-retinanet). In the code used for training, I've simply added the line `model.save('my_model')` and I get the error `Exception has occurred: KeyError 'inputs'`. It's working if I use instead `model.save('my_model.h5')`.  

Overview of code:

```
model, training_model, prediction_model = create_models(
            backbone_retinanet=backbone.retinanet,
            num_classes=train_generator.num_classes(),
            weights=weights, ...)

callbacks = create_callbacks(
        model,
        training_model,
        prediction_model,
        validation_generator,
        args,
    )

training_model.fit(
        train_generator,
        steps_per_epoch=args.steps,
        epochs=args.epochs,
        verbose=1,
        callbacks=callbacks,
        workers=args.workers,
        use_multiprocessing=args.multiprocessing,
        max_queue_size=args.max_queue_size,
        validation_data=validation_generator,
        initial_epoch=args.initial_epoch
    )

training_model.save('my_model')

```

Same error occurs if I define my ModelCheckpoint callback with `.ckpt` file instead of `.h5` file.

**Comment by satya12314** [comment]
Can you suggest me some ideas ,so that i try to solve this issue

**Comment by aginpatrick** [comment]
Hi and thank you for help,
Actually I'm not sure if the error is caused by a particular implementation
of a model or not (in other words, is it a *keras* issue or a *keras-retinanet
<https://github.com/fizyr/keras-retinanet/issues/1506>* issue). It's
difficult for me to know.  What I can say is that I simply loaded a retina
net model as shown here <https://github.com/fizyr/keras-retinanet#testing>
and tried to save it afterwards. Code to reproduce the error:

from keras_retinanet.models import load_model
# resnet50_coco_best_v2.1.0.h5 can be downloaded here
<https://github.com/fizyr/keras-retinanet/releases/download/0.5.1/resnet50_coco_best_v2.1.0.h5>
:
model = load_model('/path/to/resnet50_coco_best_v2.1.0.h5',
backbone_name='resnet50')
model.save('my-model')

Thank you again
Patrick

**Comment by aginpatrick** [comment]
It seems like a keras bug because I reproduced my error for a minimal model this time:

from tensorflow import keras
import keras_resnet
import keras_resnet.models

inputs = keras.layers.Input(shape=(None, None, 3))
resnet = keras_resnet.models.ResNet50(inputs, include_top=False, freeze_bn=True)

resnet.save("my-model")

and I get the same error: "KeyError: 'inputs'"

Is there something I'm missing with the save command?
Regards,
Patrick

**Comment by aginpatrick** [comment]
I've realized that it's related to the resnet50 specific implementation. I thought at the beginning that it was the official keras implementation. I have tested the official implementation from keras.applications.resnet and it's working. Thanks again.

**Comment by phil-holland** [comment]
For anyone running into the same problem, the was resolved for me by implementing the fix given in this pull request: https://github.com/broadinstitute/keras-resnet/pull/65/commits/73c50f77920aead4e8c71dba387822cdbeb16fd7

It's definitely an issue specifically with the `keras_resnet` package's implementation of Resnet.

**Comment by Egorundel** [comment]
What I need to do if I want convert model.h5 (after training by https://github.com/fizyr/keras-retinanet) to TensorFlow SavedModel format? I have an error `KeyError: 'inputs'`.

Code for convert:
![Screenshot from 2023-10-05 10-52-53](https://github.com/keras-team/keras/assets/65890558/3ee9ffc6-8e05-4244-8ac8-c6c1e0ba51c0)

Error `KeyError: 'inputs'`:
![Screenshot from 2023-10-05 10-53-25](https://github.com/keras-team/keras/assets/65890558/a4708560-4a6f-4905-9eab-36775f01e3a6)
