### ISSUE TITLE
How to use class_weights in keras for multioutput network?

### ISSUE THREAD

**Issue by buenohernandez** [keras-team/keras#14377]
I'm creating a mulit-output network using generators with class_mode = "multi_output"

I tried passing a list and it didn't work, I tried as well:

`class_weights = {col : {0:1, 1:df[col].count() / df[col].sum()} for col in columns}`

```
ValueError: Expected `class_weight` to be a dict with keys from 0 to one less than the number of classes, found 
{'col0': {0: 1, 1: 15.43398392652124}, 
'col1': {0: 1, 1: 2.399336046262583}, 
'col2': {0: 1, 1: 24.045432864297638}, 
'col3': {0: 1, 1: 1.1975946547884186}, 
'col4': {0: 1, 1: 2.0682811249923074}, 
'col5': {0: 1, 1: 20.7774343122102}, 
'col6': {0: 1, 1: 1.2918508552758023}, 
'col7': {0: 1, 1: 44.39564068692206}, 
'col8': {0: 1, 1: 4.168716793119844}, 
'col9': {0: 1, 1: 6.775933331093115}, 
'col10': {0: 1, 1: 4.859735377051551}, 
'col11': {0: 1, 1: 23.790113260972156}}
```

How can I do it?

**Comment by sushreebarsa** [comment]
@buenohernandez Could you please refer to this [link](https://keras.io/guides/training_with_built_in_methods/) and let us know  if it helps ? Thanks!

**Comment by hernandezfelipe** [comment]
Thank you for your reply @sushreebarsa. It's been so long I don't even have the code anymore.
You can close the issue.

Regards.

**Comment by sushreebarsa** [comment]
@hernandezfelipe Thank you for your update . Closing this issue .
