### ISSUE TITLE
Input an array of (50385, ) where each is an array of (x, 127) into MLP)

### ISSUE THREAD

**Issue by fokoa** [keras-team/keras#14398]
I want to input a numpy 2d array into MLP but I have an array of 50395 rows that contains many 2d array of shape `(x, 129)`. ``x`` because some matrices have different row numbers. Here is an example :

    train['spec'].shape
    >>(50395,)
    train['spec'][0].shape
    >>(41, 129)
    train['spec'][5].shape
    >>(71, 129)

Here an snippet of my code :

    X_train = train['spec'].values;     X_valid = valid['spec'].values
    y_train = train['label'].values;    y_valid = valid['label'].values
    model.add(Dense(12, input_shape=(50395, ), activation='relu'));
    model.fit(X_train, y_train, validation_data=(X_valid, y_valid), epochs=500, batch_size=1);

I get this error on last line (`model.fit`) : 
``ValueError: Error when checking input: expected dense_54_input to have shape (50395,) but got array with shape (1,)``

How to fix this problem so that the network can take as input all `50395` matrices of shape ``(x, 129)``?

**Comment by Rahul-132** [comment]
try to reshape the array and also try to change number 12 of dense layer and modify them try if that work. Another thing I guess you should enter flatten there and it may work

**Comment by fokoa** [comment]
> try to reshape the array and also try to change number 12 of dense layer and modify them try if that work. Another thing I guess you should enter flatten there and it may work

Yes @Rahul-132. I reshape the array but I do face at new  error. Where is my code now : 

`` 
# labels = [‘yes’, ‘no’, ‘up’, ‘down’, ‘left’,’right’, ‘on’, ‘off’, ‘stop’, ‘go’, unknow]
X_train = list(train['spec']);  
y_train = train['label'].values;

encoder = LabelEncoder();
encoder.fit(y_train);
encoded_y_train = encoder.transform(y_train);
dummy_y_train = to_categorical(encoded_y_train);

model = Sequential()
model.add(Dense(8, input_shape=(50395, 71, 129), activation='relu'));
model.add(Dense(8, activation='relu'));
model.add(Dense(11, activation='sigmoid'));

model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy']);

# Fit model 
model.fit(np.array(X_train), dummy_y_train, epochs=50, batch_size=1);
``
And now, I get this error : 
`ValueError: A target array with shape (50395, 11) was passed for an output of shape (None, 71, 11) while using as loss categorical_crossentropy. This loss expects targets to have the same shape as the output.`

Please, how I can fixe them ?

**Comment by Rahul-132** [comment]
model.add(Flatten())
model.output_shape

do this in the last layer this might help to fit

**Comment by Rahul-132** [comment]
if not can you provide the data set or array

**Comment by fokoa** [comment]
> if not can you provide the data set or array

I use this dataset: [Speech Command Dataset](https://ai.googleblog.com/2017/08/launching-speech-commands-dataset.html)

I removed the silence in all my audio then I transformed the result into array using the function ``scipy.signal.spectrogram (...)``.

After transformation, I ended up with a two-dimensional array for each audio where, all the array had the same number of columns (129) but different rows (some matrices had 20 rows, others 50, others 28 , etc).

So that all the array have the same number of rows, I first got the matrix that had the highest number of rows (71 rows) and then I completed the other array with rows filled with 0's. end of the process, all array have shape (71, 129).

`train_df.sample(5)
 >> 	                label	   spec
        4848	unknown	   [[0.15134239, -0.2616245, -0.7671668, -0.46412...
        58112	up	           [[-1.2584903, -2.3514917, -2.077282, -1.820599...
        62298	yes	           [[-0.7747345, 0.49947095, -0.3060484, -2.01911...
        61883	yes	           [[0.3465101, -0.008627839, -0.14907381, 0.0984...
        39726	right	           [[-0.10674563, 0.9989633, 0.5195742, -0.032281...`

`train_df.iloc[25000]
label                                                  off
spec     [[-0.7718518, -0.05070683, -0.63815033, -0.513...
Name: 31984, dtype: object`

`train_df['spec'][2500]
array([[ 0.6734798 ,  0.3073784 ,  0.61223936, ...,  1.0119904 ,
         0.8119934 ,  0.43300468],
       [ 0.2315741 ,  0.35808802,  1.2006477 , ...,  1.0028452 ,
         0.75628084,  0.8467174 ],
       [-2.3041399 ,  1.3576472 ,  1.2938004 , ...,  0.66340053,
        -0.7343602 ,  0.57536685],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]], dtype=float32)`
    
Here is where I am!

**Comment by fokoa** [comment]
> model.add(Flatten())
> model.output_shape
> 
> do this in the last layer this might help to fit

Thank you @Rahul-132! It's work!
