### ISSUE TITLE
Did 2.4 version tf.keras remove the multi_gpu_model method?

### ISSUE THREAD

**Issue by Erik-Ni** [keras-team/keras#14397]
How could we compile a multiple gpu model with Keras 2.4 then?

**Comment by ymodak** [comment]
`tf.keras.utils.multi_gpu_model` is deprecated. Please use [`tf.distribute.MirroredStrategy`](https://www.tensorflow.org/tutorials/distribute/keras) instead.' 
See https://github.com/tensorflow/tensorflow/commit/29372ca5093432c1591122cffd861b53d87b0af4#diff-1007fe830d10a5fbc62399251f37d1081bfda616cbe4f9077905bcaf64273db8
