### ISSUE TITLE
Closing brace is missing while printing model summary, when the filter size of three digits Eg. 128, 256, etc. (keras version 2.4.3 )

### ISSUE THREAD

**Issue by rebelgiri** [keras-team/keras#14396]
While painting the model summary, when the filter size is of three digits, printed model summary is not having closing brace (keras version 2.4.3 ).
```
conv = Conv2D( 128, (5, 5), padding='same', activation='relu')(layer_in)
model.summary()
```

![image](https://user-images.githubusercontent.com/18268525/105609086-21079a00-5da7-11eb-89e1-353857953d0d.png)

**Comment by sushreebarsa** [comment]
@rebelgiri In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by rebelgiri** [comment]
https://github.com/keras-team/keras/issues/14396#issue-792609162

**Comment by sushreebarsa** [comment]
@rebelgiri In order to reproduce the issue reported here, could you please provide the complete code and the dataset , you are using. Thanks!
