### ISSUE TITLE
Multiheadattention  layer dimensions

### ISSUE THREAD

**Issue by je-santos** [keras-team/keras#14405]
Hi, it looks like if I add a channel dimension, the number of parameters in the Dense layer is no longer correct:

# This is ok
inputs = Input(shape=[1800])
y = MultiHeadAttention(num_heads=10, 
                       key_dim=10,
                       use_bias=False,
                       attention_axes = 0,
                       )(inputs,inputs)
model = Model(inputs=inputs, outputs=y)
print(model.summary())

#### This is not:

inputs = Input(shape=[1800,1]).    # added channel dim here
y = MultiHeadAttention(num_heads=10, 
                       key_dim=10,
                       use_bias=False,
                       attention_axes = 0,
                       )(inputs,inputs)
model = Model(inputs=inputs, outputs=y)
print(model.summary())

**Comment by saberkun** [comment]
the valid inputs are [batch, sequence, channel] (and beyond). I don't think there are strict input validations
