### ISSUE TITLE
A keras model works bad with fp16 weights, but right when a lambda layer added.

### ISSUE THREAD

**Issue by venuswu** [keras-team/keras#14404]
I predicted a bert model with fp16 weights, part of the code as follows,  but there is a puzzled phenomenon, if the Lambda is deleted, the final results goes bad.

'''
        x = self.apply(
            inputs=xi,
            layer=Embedding,
            input_dim=self.vocab_size,
            output_dim=self.embedding_size,
            embeddings_initializer=self.initializer,
            mask_zero=True,
            name='Embedding-Token',
            dtype='float16'
        )
     x = Lambda( lambda x: x, name='Embedding-apply')(x)
'''

**Comment by sushreebarsa** [comment]
@venuswu In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by sushreebarsa** [comment]
Closing this issue due to lack of recent activity .Please feel free to reopen if you still have concern.Thanks!
