### ISSUE TITLE
How to handle  "steps_per_epoch" during training large image dataset

### ISSUE THREAD

**Issue by aratimcs** [keras-team/keras#14437]
Hello sir, I'm working on deep learning based classification problem. i'm not need learning expert. i have a little doubt on  selecting number of samples to train model at a time. what will happen when we take when we take step_per_epochs less than total NUM_OF_SAMPLES is it degrades the performance.  when i select  step_per_epochs = total NUM_OF_SAMPLES / batch_size then it takes more iterations per epochs on training and also it increases computation time.  Could you please clear my doubt. Please reply

Thanks and regards

**Comment by sushreebarsa** [comment]
@aratimcs Could you please refer to the[ link ](https://keras.io/guides/training_with_built_in_methods/)and let us know if it helps? Thanks!
