### ISSUE TITLE
how to implement Kullback–Leibler divergence in simple keras autoencoder

### ISSUE THREAD

**Issue by seis330** [keras-team/keras#14460]
Hii, i want to implement activity_regularizer as  Kullback–Leibler divergence,however, i donot get any implementation in keras.if anybody can provide the example code for the same i will be grateful you.

i try to use code as below

class SparseRegularizer(keras.regularizers.Regularizer):
    
    def __init__(self, rho = 0.01,beta = 1):
        """
        rho  : Desired average activation of the hidden units
        beta : Weight of sparsity penalty term
        """
        self.rho = rho
        self.beta = beta
        

    def __call__(self, activation):
        rho = self.rho
        beta = self.beta

implementation is 

encoded = Dense(512,  activation='softplus',activity_regularizer=regularizers.SparseRegularizer(rho = 0.01,beta = 1))(input_img)

error is  AttributeError: module 'keras.regularizers' has no attribute 'SparseRegularizer'

**Comment by sushreebarsa** [comment]
@seis330 In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!
