### ISSUE TITLE
Segmentation fault: 11 - when running a deep learning model with Keras and Tensorflow on Macbook M1 

### ISSUE THREAD

**Issue by yasith93** [keras-team/keras#14473]
I'm using an Apple Macbook Pro M1 8GB. I'm running a deep learning model with the following imports (Keras version 2.4.3 and tensorflow_macos version 2.4.0-rc0)

```
import numpy as np;
import keras;
from keras. layers.core import Dense, Flatten, Activation;
from keras.optimizers import Adam;
from keras.metrics import binary_crossentropy;
from keras.preprocessing.image import ImageDataGenerator;
from keras.preprocessing import image;
from keras.models import Model;
from keras.applications import imagenet_utils;
from keras.callbacks import ModelCheckpoint;
import tensorflow as tf;
```
When I'm training the model, at the end of the first epoch, I get the following error.
```
Epoch 1/50
60/60 [==============================] - ETA: 0s - loss: 0.6377 - accuracy: 0.6485
Segmentation fault: 11
```
Does anyone have any idea about how to solve this issue?

**Comment by ariG23498** [comment]
Hey @yasith93 
I have been using a MacBook M1 air for some time now. I have made it a point to use `tensorflow_macos keras` everytime I train a model. One workaround to your imports would be to 
```python
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Dense, Flatten, Activation
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import binary_crossentropy
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import Model
from tensorflow.keras.applications import imagenet_utils
from tensorflow.keras.callbacks import ModelCheckpoint
```
Hope this helps with! 😄

**Comment by yasith93** [comment]
Hi @ariG23498,

Thanks! That actually worked. Could you explain the reason for that?

**Comment by ariG23498** [comment]
My guesses are, `tensorflow_macos` has an indepth compatibility with the M1 chip while `keras` does not. Hence the `tf.keras` works while `keras` does not.

**Comment by yasith93** [comment]
Thanks!
