### ISSUE TITLE
AttributeError: 'ProgbarLogger' object has no attribute 'log_values'

### ISSUE THREAD

**Issue by billchen559** [keras-team/keras#14481]
AttributeError                            Traceback (most recent call last)
<ipython-input-19-73d2d1897696> in <module>
      9                                 validation_data = validation_generator,
     10                                 validation_steps = validation_generator.n//validation_generator.batch_size,
---> 11                                 callbacks=callbacks_list
     12                                 )

~\Anaconda3\lib\site-packages\keras\legacy\interfaces.py in wrapper(*args, **kwargs)
     89                 warnings.warn('Update your `' + object_name + '` call to the ' +
     90                               'Keras 2 API: ' + signature, stacklevel=2)
---> 91             return func(*args, **kwargs)
     92         wrapper._original_function = func
     93         return wrapper

~\Anaconda3\lib\site-packages\keras\engine\training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, validation_freq, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   1730             use_multiprocessing=use_multiprocessing,
   1731             shuffle=shuffle,
-> 1732             initial_epoch=initial_epoch)
   1733 
   1734     @interfaces.legacy_generator_methods_support

~\Anaconda3\lib\site-packages\keras\engine\training_generator.py in fit_generator(model, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, validation_freq, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
    258                     break
    259 
--> 260             callbacks.on_epoch_end(epoch, epoch_logs)
    261             epoch += 1
    262             if callbacks.model.stop_training:

~\Anaconda3\lib\site-packages\keras\callbacks\callbacks.py in on_epoch_end(self, epoch, logs)
    150         logs = logs or {}
    151         for callback in self.callbacks:
--> 152             callback.on_epoch_end(epoch, logs)
    153 
    154     def on_train_batch_begin(self, batch, logs=None):

~\Anaconda3\lib\site-packages\keras\callbacks\callbacks.py in on_epoch_end(self, epoch, logs)
    609                 self.log_values.append((k, logs[k]))
    610         if self.verbose:
--> 611             self.progbar.update(self.seen, self.log_values)
    612 
    613 

AttributeError: 'ProgbarLogger' object has no attribute 'log_values'

**Comment by ariG23498** [comment]
Could you share the code snippet somehow with us? A `colab` link would be just fine.
It would be great if I could reproduce the issue and get back to you.

**Comment by billchen559** [comment]
Thank you for your help, ariG23498 !  
I fixed it on checking it again!  
:)

**Comment by ymodak** [comment]
https://stackoverflow.com/questions/57857683/attributeerror-progbarlogger-object-has-no-attribute-log-values/59337511
