### ISSUE TITLE
wrong output shape for the layer LocallyConnected1D

### ISSUE THREAD

**Issue by happyalfred2016** [keras-team/keras#14485]
python=3.6.3
keras=2.3.1
tensorflow=1.14.0

```python
import keras
from keras.layers.local import LocallyConnected1D
from keras import Input

out = LocallyConnected1D(filters=1, kernel_size=1, data_format='channels_first')(Input((64, 32)))
print(out.shape)
```

the output shape of the above var "out" should be "(?, 1, 32)", however it prints as "(?, 64, 64)"

**Comment by ariG23498** [comment]
Hey @happyalfred2016 
I tried reproducing this ticket 👇 
```python
import tensorflow as tf
from tensorflow.keras.layers import LocallyConnected1D
# With channel_first, the data needs to be in (batch, channels, length)
# 4 batch
# 64 channels
# 32 length
inp = tf.ones(shape=(4,64,32))
out = LocallyConnected1D(filters=1, kernel_size=1, data_format='channels_first')(inp)
print(out.shape)
```
This infact give the output shape as `(4, 1, 32)`

On the other hand doing this
```python
out = LocallyConnected1D(filters=1, kernel_size=1, data_format='channels_first')(Input((64,32)))
print(out.shape)
```
I got the output as `(None, 1, 32)`

I don't seem to have an error here!

**Comment by jvishnuvardhan** [comment]
@happyalfred2016 I tried reproducing your issue with TF2.5. when using `tensorflow.keras` from recent `TF2.5` everything works as you expected. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/95fd4e3b450485acda9163bdac206e38/untitled1006.ipynb). Thanks!

Please verify once and close the issue if this was resolved for you. Thanks!

**Comment by happyalfred2016** [comment]
> Hey @happyalfred2016
> I tried reproducing this ticket 👇
> 
> ```python
> import tensorflow as tf
> from tensorflow.keras.layers import LocallyConnected1D
> # With channel_first, the data needs to be in (batch, channels, length)
> # 4 batch
> # 64 channels
> # 32 length
> inp = tf.ones(shape=(4,64,32))
> out = LocallyConnected1D(filters=1, kernel_size=1, data_format='channels_first')(inp)
> print(out.shape)
> ```
> 
> This infact give the output shape as `(4, 1, 32)`
> 
> On the other hand doing this
> 
> ```python
> out = LocallyConnected1D(filters=1, kernel_size=1, data_format='channels_first')(Input((64,32)))
> print(out.shape)
> ```
> 
> I got the output as `(None, 1, 32)`
> 
> I don't seem to have an error here!

Thanks for your reply. 

I finally figure out it's because I use "from keras.layers.local import LocallyConnected1D" while you are using "from tensorflow.keras.layers import LocallyConnected1D". 

And if you use "from keras.layers.local import LocallyConnected1D" the output shape would be (4, 64, 1)!

Really weird...

**Comment by happyalfred2016** [comment]
> @happyalfred2016 I tried reproducing your issue with TF2.5. when using `tensorflow.keras` from recent `TF2.5` everything works as you expected. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/95fd4e3b450485acda9163bdac206e38/untitled1006.ipynb). Thanks!
> 
> Please verify once and close the issue if this was resolved for you. Thanks!

I have figured out that it's because I use "keras.layers.local.LocallyConnected1D" instead of "tensorflow.keras.layers.LocallyConnected1D", where the latter one works exactly as expected.

But in tensorflow 2.5, the module "local" is no longer existed, so I am not sure if this issue is till needed to be being open.

Anyway, thank you for your reply.

**Comment by jvishnuvardhan** [comment]
@happyalfred2016 Agree. This was an issue with older version. It was resolved in recent `TF2.5`. So, I am closing this issue. Feel free to reopen if I am mistaken. Thanks!
