### ISSUE TITLE
ValueError: Error when checking input: expected input_1 to have 4 dimensions, but got array with shape (4, 1)

### ISSUE THREAD

**Issue by moonchildz** [keras-team/keras#14486]
I have a problem making a keras network. my code is : 

import cv2
import numpy as np
import math
import sys
import os
import re
import random as rnd
import keras
import keras.layers as L
import keras.models as M
import keras.optimizers as O
import keras.backend as B
import keras.backend.tensorflow_backend as B_
from keras.utils import Sequence as Seq

def unet_gen(input):
    x1 = L.Conv2D(filters=64, kernel_size=(3, 3), strides=1, padding='same')(input)
    x1 = L.ReLU()(x1)
    x1 = L.BatchNormalization()(x1)
    x1 = L.Conv2D(filters=64, kernel_size=(3, 3), strides=1, padding='same')(x1)
    x1 = L.ReLU()(x1)
    x1 = L.BatchNormalization()(x1)
    x1 = L.Conv2D(filters=64, kernel_size=(3, 3), strides=1, padding='same')(x1)
    x1 = L.ReLU()(x1)
    x1 = L.BatchNormalization()(x1)

    x2 = L.Conv2D(filters=128, kernel_size=(3, 3), strides=2, padding='same')(x1)
    x2 = L.ReLU()(x2)
    x2 = L.BatchNormalization()(x2)
    x2 = L.Conv2D(filters=128, kernel_size=(3, 3), strides=1, padding='same')(x2)
    x2 = L.ReLU()(x2)
    x2 = L.BatchNormalization()(x2)
    x2 = L.Conv2D(filters=128, kernel_size=(3, 3), strides=1, padding='same')(x2)
    x2 = L.ReLU()(x2)
    x2 = L.BatchNormalization()(x2)

    x3 = L.Conv2D(filters=256, kernel_size=(3, 3), strides=2, padding='same')(x2)
    x3 = L.ReLU()(x3)
    x3 = L.BatchNormalization()(x3)
    x3 = L.Conv2D(filters=256, kernel_size=(3, 3), strides=1, padding='same')(x3)
    x3 = L.ReLU()(x3)
    x3 = L.BatchNormalization()(x3)
    x3 = L.Conv2D(filters=256, kernel_size=(3, 3), strides=1, padding='same')(x3)
    x3 = L.ReLU()(x3)
    x3 = L.BatchNormalization()(x3)

    x4 = L.Conv2D(filters=512, kernel_size=(3, 3), strides=2, padding='same')(x3)
    x4 = L.ReLU()(x4)
    x4 = L.BatchNormalization()(x4)
    x4 = L.Conv2D(filters=512, kernel_size=(3, 3), strides=1, padding='same')(x4)
    x4 = L.ReLU()(x4)
    x4 = L.BatchNormalization()(x4)
    x4 = L.Conv2D(filters=512, kernel_size=(3, 3), strides=1, padding='same')(x4)
    x4 = L.ReLU()(x4)
    x4 = L.BatchNormalization()(x4)

    x3_ = L.UpSampling2D(size=(2,2))(x4)
    x3_ = L.Concatenate(axis=-1)([x3,x3_])
    x3_ = L.Conv2D(filters=256, kernel_size=(3, 3), strides=1, padding='same')(x3_)
    x3_ = L.ReLU()(x3_)
    x3_ = L.BatchNormalization()(x3_)
    x3_ = L.Conv2D(filters=256, kernel_size=(3, 3), strides=1, padding='same')(x3_)
    x3_ = L.ReLU()(x3_)
    x3_ = L.BatchNormalization()(x3_)
    x3_o = L.Conv2D(filters=1, kernel_size=(3, 3), strides=1, padding='same')(x3_)# Output compare 1

    x2_ = L.UpSampling2D(size=(2,2))(x3_)
    x2_ = L.Concatenate(axis=-1)([x2,x2_])
    x2_ = L.Conv2D(filters=128, kernel_size=(3, 3), strides=1, padding='same')(x2_)
    x2_ = L.ReLU()(x2_)
    x2_ = L.BatchNormalization()(x2_)
    x2_ = L.Conv2D(filters=128, kernel_size=(3, 3), strides=1, padding='same')(x2_)
    x2_ = L.ReLU()(x2_)
    x2_ = L.BatchNormalization()(x2_)
    x2_o = L.Conv2D(filters=1, kernel_size=(3, 3), strides=1, padding='same')(x2)  # Output compare 1

    x1_ = L.UpSampling2D(size=(2,2))(x2_)
    x1_ = L.Concatenate(axis=-1)([x1,x1_])
    x1_ = L.Conv2D(filters=64, kernel_size=(3, 3), strides=1, padding='same')(x1_)
    x1_ = L.ReLU()(x1_)
    x1_ = L.BatchNormalization()(x1_)
    x1_ = L.Conv2D(filters=64, kernel_size=(3, 3), strides=1, padding='same')(x1_)
    x1_ = L.ReLU()(x1_)
    x1_ = L.BatchNormalization()(x1_)
    x1_ = L.Conv2D(filters=1, kernel_size=(3, 3), strides=1, padding='same')(x1_)
    model = M.Model(input = input, output = [x1_,x2_o,x3_o])

    model.compile(optimizer = O.Adam(lr = 1e-4), loss = 'mean_absolute_error', metrics = ['accuracy'])
    return model

class load_dataset(Seq):
    def __init__(self,route,batch_size = 8,split ='train', shuffle=False):
        self.dir = route
        self.route = route
        self.batch_size = batch_size
        self.shuffle = shuffle
        self.in_list=[]
        self.gt_list=[]

        dir_l_in = self.dir+'imgs/'
        filelist = os.listdir(dir_l_in)
        print('::::::::',len(filelist))
        dir_l_gt = self.dir+'GT/'
        for ii in os.listdir(dir_l_in):
            self.in_list.append(dir_l_in+'/'+ii)
            self.gt_list.append(dir_l_gt+'/'+ii[:-3]+'png')
        self.on_epoch_end()
    def __len__(self):
        return int(np.floor(len(self.in_list) / self.batch_size))

    def __getitem__(self, index):
        indexes = self.indexes[index * self.batch_size:(index + 1) * self.batch_size]
        # Find list of IDs
        in_list_temp = [self.in_list[k] for k in indexes]
        gt_list_temp = [self.gt_list[k] for k in indexes]

        I,G = self.__data_generation(in_list_temp,gt_list_temp)
        return I,G

    def on_epoch_end(self):
        self.indexes = np.arange(len(self.in_list))
        if self.shuffle == True:
            np.random.shuffle(self.indexes)

    def __data_generation(self,in_list_temp,gt_list_temp):
        ib = []
        gb = []
        gb_05 = []
        gb_025 = []
        for ii,gg in zip(in_list_temp,gt_list_temp):
            img_i = (cv2.imread(ii,-1)/255.0).astype(np.float32)
#            print('shape_raw:',img_i.shape)
            w = img_i.shape[1]//16 *12
            h = img_i.shape[0]//16 *12
            img_i = img_i[48:h, 48:w, :]
            img_g = (cv2.imread(gg,-1)/255.0).astype(np.float32)
            img_g = img_g[48:h,48:w]
#            print('shape:',img_i.shape,img_g.shape)
            img_g_05 = cv2.resize(img_g,None,fx=0.5,fy=0.5)
            img_g_025 = cv2.resize(img_g,None,fx=0.25,fy=0.25)
            ib.append(img_i)
            gb.append(np.expand_dims(img_g,-1))
            gb_05.append(np.expand_dims(img_g_05,-1))
            gb_025.append(np.expand_dims(img_g_025,-1))
        print('S:',np.array(ib).shape,np.array(gb).shape)
        return np.array(ib),[np.array(gb),np.array(gb_05),np.array(gb_025)]

img_in = M.Input((None, None, 3))
unet_deblur = unet_gen(img_in)
unet_deblur.summary()
data_train = load_dataset(route = 'D:\Synthetic_hybrid_train_PG2018/',split='train',batch_size=4)
data_val = load_dataset(route = 'D:\Synthetic_hybrid_test_PG2018/',split='test',batch_size=4)
with B_.tf.device('/gpu:0'):
    unet_deblur.fit_generator(generator=data_train,validation_data=data_val,epochs=30,shuffle=True)
    unet_deblur.save('D:/blurdetect.hdf5')

And the Error appears like : 

Epoch 1/30
2021-02-25 23:37:07.514285: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2021-02-25 23:37:09.818975: W tensorflow/stream_executor/cuda/redzone_allocator.cc:312] Internal: Invoking ptxas not supported on Windows
Relying on driver to perform ptx compilation. This message will be only logged once.

   1/2115 [..............................] - ETA: 6:28:54 - loss: 3.5437 - conv2d_21_loss: 1.4239 - conv2d_18_loss: 0.9839 - conv2d_15_loss: 1.1358 - conv2d_21_accuracy: 0.0981 - conv2d_18_accuracy: 0.0955 - conv2d_15_accuracy: 0.1081Traceback (most recent call last):
  File "C:/Users/Administrator/PycharmProjects/eps/venv/deblur_net.py", line 155, in <module>
    unet_deblur.fit_generator(generator=data_train,validation_data=data_val,epochs=30,shuffle=True)
  File "C:\Users\Administrator\PycharmProjects\eps\venv\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Administrator\PycharmProjects\eps\venv\lib\site-packages\keras\engine\training.py", line 1732, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Users\Administrator\PycharmProjects\eps\venv\lib\site-packages\keras\engine\training_generator.py", line 220, in fit_generator
    reset_metrics=False)
  File "C:\Users\Administrator\PycharmProjects\eps\venv\lib\site-packages\keras\engine\training.py", line 1508, in train_on_batch
    class_weight=class_weight)
  File "C:\Users\Administrator\PycharmProjects\eps\venv\lib\site-packages\keras\engine\training.py", line 579, in _standardize_user_data
    exception_prefix='input')
  File "C:\Users\Administrator\PycharmProjects\eps\venv\lib\site-packages\keras\engine\training_utils.py", line 135, in standardize_input_data
    'with shape ' + str(data_shape))
**ValueError: Error when checking input: expected input_1 to have 4 dimensions, but got array with shape (4, 1)**

When checking the processes, the shape of the list ib sometimes become (4, ), while expecting (4, w ,h ,3 ) .
and I cannot completely understand why this happens, since  I checked every input image and confirmed that there is no damaged image. Can somebody please help me ?

**Comment by ariG23498** [comment]
Hey @moonchildz 
The code attached is very problematic to decipher. Could you instead share a `colab` link to the code?
I could try my hand on the code and maybe help you with it 😄

**Comment by sushreebarsa** [comment]
@moonchildz 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!
