### ISSUE TITLE
How to integrate CRF-as-RNN and CNN

### ISSUE THREAD

**Issue by ghost** [keras-team/keras#1449]
I'm looking to implement the architecture described in this paper: http://www.robots.ox.ac.uk/~szheng/papers/CRFasRNN.pdf

They first represent a CRF as an RNN. They then integrate that RNN with a CNN and train the model end-to-end. I understand that I can implement CNN and RNN separately with Keras, but can I also integrate them and train them end-to-end?

**Comment by svkerr** [comment]
@artitw  -- Have you received any information regarding your question? I'm interested in this as well (using Torch)...

**Comment by MehulAjax21** [comment]
I am also interested in this work. Please provide me any information you have

**Comment by pribadihcr** [comment]
+1

**Comment by wentaozhu** [comment]
I wrote a very simple version https://github.com/wentaozhu/adversarial-deep-structural-networks.git. Hope to see a nicer CRFasRNN.

**Comment by ahukui** [comment]
+1

**Comment by sadeepj** [comment]
A Keras/Tensorflow implementation of CRF-RNN is now available here: https://github.com/sadeepj/crfasrnn_keras
It produces almost identical results to our original Caffe-based version, which is available here: https://github.com/torrvision/crfasrnn

**Comment by dimahdera** [comment]
In the  Keras/Tensorflow implementation of CRF-RNN we have to run the compile.sh script in the cpp directory and this script is not working on Windows OS  The official Tensorflow guide for building a custom op does not yet include build instructions for Windows.
Could you please help. This stop the entire implementation of CRF-RNN using keras

**Comment by dimahdera** [comment]
Could anyone help with this issue
In the Keras/Tensorflow implementation of CRF-RNN we have to run the compile.sh script in the cpp directory and this script is not working on Windows OS The official Tensorflow guide for building a custom op does not yet include build instructions for Windows.
Could you please help. This stop the entire implementation of CRF-RNN using keras

**Comment by sadeepj** [comment]
@dimahdera Unfortunately, I'm unable to be of help directly as I've never tried it on Windows. But you might find some of the links in this comment useful: https://github.com/sadeepj/crfasrnn_keras/issues/2#issuecomment-321933952

**Comment by dimahdera** [comment]
Is there away to define the permutohedral lattice filters in python directly without c files. Did anyone do that before?
Thank you
