### ISSUE TITLE
Keras model.fit is displaying a big error, Unsolvable

### ISSUE THREAD

**Issue by Burnfireblaze** [keras-team/keras#14502]
A big error is popping up when model.fit is run
[Project for paper.pdf](https://github.com/keras-team/keras/files/6101734/Project.for.paper.pdf)
. I tried fit_generator, giving steps per epoch, and updating tensorflow also, nothing seems to work. I used vgg16 for preprocessing. The last error also doesn't seem to make sense because the dimensions of the expected input are 224,224,3 and the actual input's dimensions are the same. I have also attached the actual code file pdf below for reference. Can someone help me with this error?

`model.fit(x=train_batches,validation_data=valid_batches,epochs =10, verbose=2)
[Project for paper.pdf](https://github.com/keras-team/keras/files/6101744/Project.for.paper.pdf)

The following is the below error:
Epoch 1/10

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-12-651362454b83> in <module>
----> 1 model.fit(x=train_batches,validation_data=valid_batches,epochs =10, verbose=2)

~\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    671           use_multiprocessing=use_multiprocessing,
    672           shuffle=shuffle,
--> 673           initial_epoch=initial_epoch)
    674     if training_utils.is_eager_dataset_or_iterator(x):
    675       # Make sure that y, sample_weights, validation_split are not passed.

~\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, validation_freq, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   1431         shuffle=shuffle,
   1432         initial_epoch=initial_epoch,
-> 1433         steps_name='steps_per_epoch')
   1434 
   1435   def evaluate_generator(self,

~\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training_generator.py in model_iteration(model, data, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, validation_freq, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch, mode, batch_size, steps_name, **kwargs)
    262 
    263       is_deferred = not model._is_compiled
--> 264       batch_outs = batch_function(*batch_data)
    265       if not isinstance(batch_outs, list):
    266         batch_outs = [batch_outs]

~\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py in train_on_batch(self, x, y, sample_weight, class_weight, reset_metrics)
   1151     x, y, sample_weights = self._standardize_user_data(
   1152         x, y, sample_weight=sample_weight, class_weight=class_weight,
-> 1153         extract_tensors_from_dataset=True)
   1154 
   1155     # If `self._distribution_strategy` is True, then we are in a replica context

~\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py in _standardize_user_data(self, x, y, sample_weight, class_weight, batch_size, check_steps, steps_name, steps, validation_split, shuffle, extract_tensors_from_dataset)
   2649           feed_input_shapes,
   2650           check_batch_axis=False,  # Don't enforce the batch size.
-> 2651           exception_prefix='input')
   2652 
   2653     if y is not None:

~\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training_utils.py in standardize_input_data(data, names, shapes, check_batch_axis, exception_prefix)
    383                              ': expected ' + names[i] + ' to have shape ' +
    384                              str(shape) + ' but got array with shape ' +
--> 385                              str(data_shape))
    386   return data
    387 

ValueError: Error when checking input: expected conv2d_input to have shape (224, 224, 3) but got array with shape (244, 244, 3)

`

**Comment by ariG23498** [comment]
Hey @Burnfireblaze 
Could you link us to the colab that you are working on?
That would be really easy for us to repro and share insights on! 😄

**Comment by superp0tat0** [comment]
You may want to check your input shape. The error message is confusing but usually the input need to have 4 dimensions. 
(Height, Width, Batch_Size, Channel)
What you have here only have considering you used RGB images.
(Height, Width, Channel)

**Comment by jvishnuvardhan** [comment]
@Burnfireblaze Interesting. Can you please share a standalone code to reproduce the issue? Just format the code in pdf format, and make it as a standalone code so that we can reproduce and find root-cause of the issue. Thanks!

**Comment by Burnfireblaze** [comment]
@jvishnuvardhan @ariG23498 Yeah I will be sending that in just a while

**Comment by Burnfireblaze** [comment]
@ariG23498 Here's the link for the ipynb notebook 
https://colab.research.google.com/drive/1T-td48ZHlTQ6z8wbERF3MOWbHBJvEQGY?usp=sharing

**Comment by Burnfireblaze** [comment]
[Project.ipynb - Colaboratory.pdf](https://github.com/keras-team/keras/files/7070568/Project.ipynb.-.Colaboratory.pdf)

@jvishnuvardhan I have included the pdf file like you asked for. Any help would be much appreciated guys. If you guys want the dataset its available in Kaggle:
https://www.kaggle.com/paultimothymooney/chest-xray-pneumonia

Please let me know if you guys need anything.

Regards,
@Burnfireblaze

**Comment by ariG23498** [comment]
Hey @Burnfireblaze 
The problem is with the input shape of the conv layer and the shape of the images.
In the data loader the images are shaped `244, 244, 3` while the input conv layer expects the images to be of shape `224, 224, 3`.

This is the [Kaggle kernel](https://www.kaggle.com/aritrag/keras-issue) that I have built which works fine with aligned shapes.
Hope I could solve your issue 😄

**Comment by innat** [comment]
@ariG23498 
If you encode your label to one-hot encoded and thus use 2 activation layers in your model's last layer then you should use `softmax` and the corresponding loss function. For example: in your kernel, your true labels are one-hot encoded that's why you need to change as follows 

```python
Dense(units=2, activation='softmax'),
...
model.compile(optimizer=Adam(loss='categorical_crossentropy', ...)
```

Otherwise, if your labels are 1D binary array, then you would do 

```python
Dense(units=1, activation='sigmoid'),
...
model.compile(optimizer=Adam(loss='binary_crossentropy', ...)
```
