### ISSUE TITLE
save_model and load_model does not support streams

### ISSUE THREAD

**Issue by pokecheater** [keras-team/keras#14510]
Hello Keras-Team :-),

I noticed that the methods load_model and save_model only work with paths. But in a server client context this led to some detour. For example an uploaded file stream needs than to be saved first as file on the server to be read by the load_model method afterwards. Common handling in this context would be to use the bytes of the file that are already inside the memory directly.

For example:
```
        if model is None:
            _hdf5_file_bytes = BytesIO()
            hdf5_file.save(_hdf5_file_bytes)
            model = load_model(_hdf5_file_bytes)
```

results in the error:
`   TypeError: expected str, bytes or os.PathLike object, not _io.BytesIO`

(Note that hdf5_file is a FileStorage object from werkzeug library).

I noted that the error occurs from the usage of is_hdf5 method inside the line:
```
if (h5py is not None and
            (isinstance(filepath, h5py.File) or h5py.is_hdf5(filepath))):
          return hdf5_format.load_model_from_hdf5(filepath, custom_objects,
                                                  compile)

```
of your keras/saving/save.py.

Is there a reason why streams are not supported? Will it be supported in near future? At the moment I have to copycat the keras code and adapt it in order to make this work, or save the file on the SSD of the server which is also not a good option.

Greetz and thx in advance for your support :)

**Comment by pokecheater** [comment]
Sorry, my fault. :-D

I found out, that I have to pass the BytesIO object to an hdf_5 file object first and then it works like a charm
```
file_bytes = io.BytesIO()
hdf5_file.save(file_bytes)
mem_hdf5_file = h5py.File(file_bytes)
model = load_model(mem_hdf5_file)
```
Sorry for opening an issue on that. But I will leave it in case somebody else is facing the same issue :).

**Comment by apatange-source** [comment]
@pokecheater give me a sample code to save tf models as streams?
