### ISSUE TITLE
Specifying subset of validation data while using validation_split in ImageDataGenerator

### ISSUE THREAD

**Issue by ammarchalifah** [keras-team/keras#14525]
I'm trying to train an image classification model and wanted to use ImageDataGenerator and flow_from_directory method. However, there is a need to split the data into training and validation data and need the data to be split reproducibly. In addition, validation subset selection is also needed.

For example, 
```
datagen = ImageDataGenerator(
        zoom_range=0.1,  # set range for random zoom
        rotation_range = 360,
        fill_mode='constant',
        cval=0.,
        horizontal_flip=True,  # randomly flip images
        vertical_flip=True,  # randomly flip images
        validation_split = 0.1
    )

# Using generator
data_generator = datagen.flow_from_directory(..., subset = 'training', split_number = 1)
val_generator = datagen.flow_from_directory(..., subset = 'validation', split_number = 1)
```

In the example above, I add a non-existent parameter, which is `split_number`. According to the above code, my intention is to make the first 10% data as the validation data and the rest 90% as the training. If I pass 2 to `split_number`, I can get choose the second 10% as the validation data and the rest as the training data. Is there any workaround I can use to do this? Thanks a lot!

**Comment by sushreebarsa** [comment]
@ammarchalifah Could you please refer to the  similar issues [link](https://github.com/keras-team/keras/issues/5862),[ link1](https://stackoverflow.com/questions/42443936/keras-split-train-test-set-when-using-imagedatagenerator) and documentation [link](https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/image/ImageDataGenerator).Let us know if it helps ? Thanks!
