### ISSUE TITLE
FIT function works only with weird input order. Multiple inputs using tf.Dataset with Dictionary.

### ISSUE THREAD

**Issue by JosuaJoker** [keras-team/keras#14522]
### Describtion:
The code below throws a Value Error Exception. But when I switch the order in the inputs of the regrssion_model definition to 
`regression_model = Model(inputs=[meta_model.inputs, mvcnn_model.inputs], outputs = reg_out)`.
The fit function trains. This is wiered, because inputs=**[meta_model.inputs, mvcnn_model.inputs]** and read_tfrecord returns **{"mvcnn_data": images,"meta_data": meta_data}** have different orders. 

I would expect that the order should be the same or better it doesn't matter, because the keys definig the correct mapping. 

### Code block:
```
def read_tfrecord(self, bin_data):
        return {"mvcnn_data": images,"meta_data": meta_data}, label

def get_dataset(self, tfrecord_path):
        dataset = tf.data.TFRecordDataset(filenames=tfrecord_path)
        dataset = dataset.map(self.read_tfrecord)
        return dataset

#Model1
mvcnn_inputs = Input(shape=(views, image_size, image_size, channels),name='mvcnn_data')
mvcnn_model = Model(inputs = mvcnn_inputs, outputs=out)

#Model2
meta_inputs = Input(shape=(3,), name='meta_data')
meta_model  = Model(inputs=meta_inputs, outputs=meta_out)

#Model3
regression_model = Model(inputs=[mvcnn_model.inputs, meta_model.inputs], outputs = reg_out)

train_dataset = self.get_dataset(self.train_tfrecord_path)
valid_dataset = self.get_dataset(self.valid_tfrecord_path)
regression_model.fit(train_dataset, validation_data=valid_dataset, epochs=epochs)
```

### Issue Report:
Exception has occurred: ValueError
in user code:

    \site-packages\tensorflow\python\keras\engine\training.py:805 train_function  *
        return step_function(self, iterator)
    \site-packages\tensorflow\python\keras\engine\training.py:795 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    \site-packages\tensorflow\python\distribute\distribute_lib.py:1259 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
   \site-packages\tensorflow\python\distribute\distribute_lib.py:2730 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    \site-packages\tensorflow\python\distribute\distribute_lib.py:3417 _call_for_each_replica
        return fn(*args, **kwargs)
    \site-packages\tensorflow\python\keras\engine\training.py:788 run_step  **
        outputs = model.train_step(data)
  \site-packages\tensorflow\python\keras\engine\training.py:754 train_step
        y_pred = self(x, training=True)
    \site-packages\tensorflow\python\keras\engine\base_layer.py:1012 __call__
        outputs = call_fn(inputs, *args, **kwargs)
    \site-packages\tensorflow\python\keras\engine\functional.py:424 call
        return self._run_internal_graph(
    \site-packages\tensorflow\python\keras\engine\functional.py:560 _run_internal_graph
        outputs = node.layer(*args, **kwargs)
    \site-packages\tensorflow\python\keras\engine\base_layer.py:1012 __call__
        outputs = call_fn(inputs, *args, **kwargs)
    \site-packages\tensorflow\python\keras\layers\core.py:1327 _call_wrapper
        return self._call_wrapper(*args, **kwargs)
    \site-packages\tensorflow\python\keras\layers\core.py:1359 _call_wrapper
        result = self.function(*args, **kwargs)
   \site-packages\tensorflow\python\util\dispatch.py:201 wrapper
        return target(*args, **kwargs)
    \site-packages\tensorflow\python\ops\array_ops.py:2038 split
        return gen_array_ops.split(
    \site-packages\tensorflow\python\ops\gen_array_ops.py:10019 split
        _, _, _op, _outputs = _op_def_library._apply_op_helper(
   \site-packages\tensorflow\python\framework\op_def_library.py:748 _apply_op_helper
        op = g._create_op_internal(op_type_name, inputs, dtypes=None,
   \site-packages\tensorflow\python\framework\func_graph.py:590 _create_op_internal
        return super(FuncGraph, self)._create_op_internal(  # pylint: disable=protected-access
    \site-packages\tensorflow\python\framework\ops.py:3528 _create_op_internal
        ret = Operation(
  \site-packages\tensorflow\python\framework\ops.py:2015 __init__
        self._c_op = _create_c_op(self._graph, node_def, inputs,
    \site-packages\tensorflow\python\framework\ops.py:1856 _create_c_op
        raise ValueError(str(e))

    ValueError: Dimension size must be evenly divisible by 8 but is 3
    	Number of ways to split should evenly divide the split dimension for '{{node model_2/tf.split/split}} = Split[T=DT_FLOAT, num_split=8](model_2/tf.split/split/split_dim, model_2/tf.nn.bias_add/BiasAdd)' with input shapes: [], [?,3] and with computed input tensors: input[0] = <1>.
  File "mvcnn_regression_model.py", line 453, in train_model
    model.fit(train_dataset, validation_data=valid_dataset, epochs=epochs)#, callbacks=[model_checkpoint])

**Comment by jvishnuvardhan** [comment]
@JosuaJoker Can you share a standalone code to reproduce the issue?

Whenever you have multiple inputs/outputs, it is always better to pass them as a dictionary ( during training data as well as during compiling the model. ) Please check a code example here https://github.com/tensorflow/tensorflow/issues/48511#issuecomment-819828310
