### ISSUE TITLE
tf.data gives Cannot batch tensors with different shapes in component 0

### ISSUE THREAD

**Issue by soroushhashemifar** [keras-team/keras#14532]
I have created a data pipeline as follows:

```
def get_waveform_and_label(file_path):
    label = tf.strings.split(file_path, os.path.sep)[-2]

    audio_binary = tf.io.read_file(file_path)
    audio, _ = tf.audio.decode_wav(audio_binary)
    waveform = tf.squeeze(audio, axis=-1)
    
    return waveform, label

def get_spectrogram(waveform):
    waveform = tf.squeeze(tf.signal.frame(waveform, 16000, 16000, pad_end=True))
    spectrogram = tf.signal.stft(waveform, frame_length=255, frame_step=128)
    spectrogram = tf.abs(spectrogram)

    return spectrogram

def get_spectrogram_and_label_id(audio, label):
    spectrogram = get_spectrogram(audio)
    spectrogram = tf.expand_dims(spectrogram, -1)
    
    label_id = tf.argmax(label == np.array(labels))
    label_onehot = tf.one_hot(label_id, len(labels))
    
    return spectrogram, label_onehot

files_ds = tf.data.Dataset.from_tensor_slices(files)
waveform_ds = files_ds.map(get_waveform_and_label, num_parallel_calls=tf.data.AUTOTUNE)
spectrogram_ds = waveform_ds.map(get_spectrogram_and_label_id, num_parallel_calls=tf.data.AUTOTUNE)
```

and I fit the model as below:

```
early_stop = tf.keras.callbacks.EarlyStopping(monitor='val_loss', mode='min', verbose=1, patience=5, min_delta=0.0001) 
checkpoint = tf.keras.callbacks.ModelCheckpoint('/kaggle/working/speech2text_model.hdf5', monitor='val_acc', verbose=1, save_best_only=True, mode='max')

model.fit(
    spectrogram_ds.shuffle(buffer_size=1024).batch(64), 
    steps_per_epoch=512, 
    epochs=100, 
    callbacks=[early_stop, checkpoint], 
    validation_data=val_spectrogram_ds.shuffle(buffer_size=1024).batch(64), 
    validation_steps=512
)
```

but it gives an error after a few iterations (not epochs) which is as follows:

> ---------------------------------------------------------------------------
> InvalidArgumentError                      Traceback (most recent call last)
> <ipython-input-54-c35e32140e52> in <module>
>      10     callbacks=[early_stop, checkpoint],
>      11     validation_data=val_spectrogram_ds.shuffle(buffer_size=1024).batch(64),
> ---> 12     validation_steps=512
>      13 )
> 
> /opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
>    1098                 _r=1):
>    1099               callbacks.on_train_batch_begin(step)
> -> 1100               tmp_logs = self.train_function(iterator)
>    1101               if data_handler.should_sync:
>    1102                 context.async_wait()
> 
> /opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
>     826     tracing_count = self.experimental_get_tracing_count()
>     827     with trace.Trace(self._name) as tm:
> --> 828       result = self._call(*args, **kwds)
>     829       compiler = "xla" if self._experimental_compile else "nonXla"
>     830       new_tracing_count = self.experimental_get_tracing_count()
> 
> /opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
>     853       # In this case we have created variables on the first call, so we run the
>     854       # defunned version which is guaranteed to never create variables.
> --> 855       return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
>     856     elif self._stateful_fn is not None:
>     857       # Release the lock early so that multiple threads can perform the call
> 
> /opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/function.py in __call__(self, *args, **kwargs)
>    2941        filtered_flat_args) = self._maybe_define_function(args, kwargs)
>    2942     return graph_function._call_flat(
> -> 2943         filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
>    2944 
>    2945   @property
> 
> /opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
>    1917       # No tape is watching; skip to running the function.
>    1918       return self._build_call_outputs(self._inference_function.call(
> -> 1919           ctx, args, cancellation_manager=cancellation_manager))
>    1920     forward_backward = self._select_forward_and_backward_functions(
>    1921         args,
> 
> /opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/function.py in call(self, ctx, args, cancellation_manager)
>     558               inputs=args,
>     559               attrs=attrs,
> --> 560               ctx=ctx)
>     561         else:
>     562           outputs = execute.execute_with_cancellation(
> 
> /opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
>      58     ctx.ensure_initialized()
>      59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
> ---> 60                                         inputs, attrs, num_outputs)
>      61   except core._NotOkStatusException as e:
>      62     if name is not None:
> 
> InvalidArgumentError:  Cannot batch tensors with different shapes in component 0. First element had shape [249,65,1] and element 63 had shape [62,249,65,1].
> 	 [[node IteratorGetNext (defined at <ipython-input-48-e9e559e7939c>:19) ]] [Op:__inference_train_function_38967]
> 
> Function call stack:
> train_function

Anyone has any idea to resolve this issue?

**Comment by bguetarni** [comment]
Can you re-run the code with

```
model.fit(
    spectrogram_ds.shuffle(buffer_size=1024).batch(64, drop_remainder=True), 
    steps_per_epoch=512, 
    epochs=100, 
    callbacks=[early_stop, checkpoint], 
    validation_data=val_spectrogram_ds.shuffle(buffer_size=1024).batch(64, drop_remainder=True), 
    validation_steps=512
)
```

please. Thanks.
