### ISSUE TITLE
tensorboard is not updating images

### ISSUE THREAD

**Issue by nisarkhanatwork** [keras-team/keras#14533]
I have the following code for my reinforcement learning program:
```
tbCallBack = callbacks.TensorBoard(log_dir = log_dir,
        histogram_freq = 1, update_freq = 'epoch', write_graph = True, write_images = True)
```

The model fits data soon after getting data for training:
```
        model.fit(x = np.vstack(x_train),
                y = np.vstack(y_train),
                callbacks = [tbCallBack],
                verbose = 1, sample_weight = s_t)
```
I see my SCALARS, DISTRIBUTIONS, and HISTOGRAMS all getting updated but not the IMAGES in the tensorboard...
I see only one image, but no updates....Can you please let me know where the problem is ?
Here is the version information:
```
tensorboard               2.3.0              pyh4dce500_0  
tensorboard-plugin-wit    1.6.0                      py_0  
keras                     2.4.3                         0  
keras-base                2.4.3                      py_0  
```

_Originally posted by @nisarkhanatwork in https://github.com/keras-team/keras/issues/6096#issuecomment-800454482_

**Comment by jvishnuvardhan** [comment]
@nisarkhanatwork Can you please share a standalone code to reproduce the issue? Also, try with recent `TF2.6` and `tf-nightly` and let us know whether issue is persisting with the new versions also. Thanks!
