### ISSUE TITLE
multi_gpu_model.save() .hdf5 file crashes when loaded on tensorflow.keras.models.model.load_model()

### ISSUE THREAD

**Issue by eladmeir** [keras-team/keras#14547]
I am currently in the middle of migrating my TF 1.13.1 + Keras 2.2.4 code into TF 2.4.1 (with Keras integrated), on ubuntu machines.

I have some "old" models, trained using Keras' ```multi_gpu_model```, and wish to use them only for prediction on my "new" migrated code that is running TF 2.4.1 (with Keras integrated).

The problem is that I cannot ```load_model``` due to the following error message:
```AttributeError: module 'tensorflow.python.keras.backend' has no attribute 'slice'``` 

A weird thing is, that it as ```multi_gpu_model.py``` file's path written as it was on the **training** machine, which is not the same as the one I am running my ```load_model``` one. 

P.S. I am willing to compromise on some conversion of models, but cannot retrain those models from scratch. I do not have any problems training ```distributed.strategy``` models on TF 2.4.1 code, and then ```load_model```. The problem only occurs when trying to use a 1.13.1 + Keras 2.2.4 trained model in my TF 2.4.1 (with Keras integrated) code.

I have already tried many combinations of Keras 2.2+ and TF 2.2+ and only got to "new" errors.

**Comment by sushreebarsa** [comment]
@eladmeir 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!
