### ISSUE TITLE
Model saved in Linux cannot be opened in Windows 10

### ISSUE THREAD

**Issue by jhuus** [keras-team/keras#14540]
Using tf 2.4.1 with keras 2.4.3, I can do model.save() and model.load_model() as long as both are on same platform. But if I save the model in Linux and then load it in Windows 10 I get "AttributeError: 'Tensor' object has no attribute '_keras_history'". I also tried the h5 save format and got the same result. I can of course provide the model etc. if that would help.

**Comment by jvishnuvardhan** [comment]
@jhuus I was able to use save a model in Linux and load it in Windows10 successfully using `TF2.6`. 

I used a simple model from tutorials page on TF webpage.

```
import tensorflow as tf
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)
model.save('MyModel_h5', save_format='h5')
```

 Then I downloaded the saved model, and loaded on Windows10 with the following code

```
import tensorflow as tf
print(tf.__version__)

loaded_model = tf.keras.models.load_model(r'C:\Users\aaaaaa\Desktop\MyModel_h5')
loaded_model.summary()
```

Can you please try and let us know whether the issue is persisting with latest TF/keras. Thanks!

**Comment by jhuus** [comment]
I have tried with the latest version, and it works fine now. Thanks!

Jan Huus
