### ISSUE TITLE
ValueError: Layer model expects 1 input(s), but it received 2 input tensors. Inputs received:

### ISSUE THREAD

**Issue by siva-wellnesys** [keras-team/keras#14571]
ValueError: Layer model expects 1 input(s), but it received 2 input tensors. Inputs received: [<tf.Tensor 'IteratorGetNext:0' shape=(None, None, None, None) dtype=uint8>, <tf.Tensor 'IteratorGetNext:1' shape=(None, None, None) dtype=float32>]

hi i am getting this error continuously while training the SSD object detection model..

my library versions are 

tensorflow=2.4.1
keras== 2.4.3

can you help me how to solve this?

**Comment by bguetarni** [comment]
Can you share your code and data if possible please. It's hard to get an idea of what is going on without them. Thanks.
