### ISSUE TITLE
model.fit ran out of data when tf.data.experimental.ignore_errors is used

### ISSUE THREAD

**Issue by scharron** [keras-team/keras#14590]
When using `model.fit` with a tensorflow Dataset that contains errors hidden by `tf.data.experimental.ignore_errors`, the training stops with

>  Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches (in this case, 2 batches). You may need to use the repeat() function when building your dataset.

I suspect that model.fit is using `Dataset.cardinality` to get an estimate of the number of batches to process, but whenever there are errors in the Dataset, the actual cardinality is less.

```
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.data import Dataset

inputs = keras.Input(shape=(1))
model = keras.models.Model(inputs, keras.layers.Dense(1)(inputs))
model.compile(loss="binary_crossentropy")

dataset = (
    tf.data.Dataset.from_tensor_slices([0., 1.])
    .map(lambda x: tf.debugging.check_numerics(1. / x, "error"))
    .batch(1)
    .apply(tf.data.experimental.ignore_errors())
)
dataset = dataset.zip((dataset, dataset))

model.fit(dataset)
```

**Comment by jvishnuvardhan** [comment]
@scharron Is this still an issue for you? I ran your code without any issue. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/7e8acf7314770e93a9163cb4d3b5819c/untitled1024.ipynb).

Can you please try once and let me know if you notice any error. Also, mention what TF version you are using. Thanks!

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Hope this was resolved for you. Thanks!
