### ISSUE TITLE
Unable load trained model

### ISSUE THREAD

**Issue by dgvsnl** [keras-team/keras#14609]
Unable to load .h5 file using **keras.load_model("...h5")** on my local machine
But I was able to load it on online platforms such as colab and kaggle.
I even tried to degrade my h5py library version but didn't work

**Comment by saichatla** [comment]
Could you give the error output?

**Comment by dgvsnl** [comment]
It keeps on showing bad marshal error

**Comment by saichatla** [comment]
Try running `pip3 install -U setuptools`

**Comment by dgvsnl** [comment]
@saichatla Thanks for the help, but I've already tried that.
After downgrading tensorflow version 2.4.0 to 2.3.0 everything works completely fine

**Comment by jvishnuvardhan** [comment]
@dgvsnl Can you please try `TF2.5` or `tf-nightly` and let us know whether it was resolved in recent versions. Alternatively, you could share a simple standalone that I can run on windows local to check whether the problem still exists in the recent versions. Thanks!

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please feel free to reopen when you have more information. Thanks!
