### ISSUE TITLE
pretrained Tensorflow Hub .pb file loading triggers the following error

### ISSUE THREAD

**Issue by AlejandroBaron** [keras-team/keras#14604]
Hello!

I'm trying to load a pretrained model, yamnet (source: https://tfhub.dev/google/yamnet/1)

As a .pb file downloads, with the assets/ and variables/ folders, i proceeded to follow
https://www.tensorflow.org/tutorials/keras/save_and_load

If i'm not mistaken, it should be as simple as
```
from tensorflow.keras.models import load_model

model = load_model('pretrained_models/yamnet')
```

However, the following exception is thrown

```
ValueError: Inconsistent values for attr 'Tshape' DT_FLOAT vs. DT_INT32 
while building NodeDef 'tf_op_layer_Reshape/Reshape' using 
Op<name=Reshape; signature=tensor:T, shape:Tshape -> output:T; attr=T:type; attr=Tshape:type,default=DT_INT32
,allowed=[DT_INT32, DT_INT64]>
```

Any clues?

**Comment by ymodak** [comment]
You may use `hub.load` to load hub models.
See https://www.tensorflow.org/hub/api_docs/python/hub/load
