### ISSUE TITLE
why showing ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected.Expected to see 4 array(s), but instead got the following list of 1 arrays

### ISSUE THREAD

**Issue by Qyum** [keras-team/keras#14601]
How to fix this issue:

Here is my code snippet:

          outputs = {'ctc': np.zeros([final_df.shape[0]])}
 
    
            inputs = {'input': np.asarray(X_data),   
                   'labels': np.asarray(labels),
                  'input_length':np.asarray(input_length) ,
              '   label_length':np.asarray(label_length)
                 }
At model,I fit the inputs,outputs....whenever I'm trying to predict model then return a same error:

             model.fit(inputs,outputs,batch_size=10,epochs=epochs,validation_split=0.25)

            def get_predictions(model, data_point): 
             print(data_point.shape[0])    
  
            model.load_weights("E:/Deep_speech_recognition/model.h5")
            prediction = model.predict(np.array(np.expand_dims(data_point, axis=0)))
            output_length = [model.output_length(data_point.shape[0])] 
            pred_ints = (K.eval(K.ctc_decode(
            prediction, output_length)[0][0])+1).flatten().tolist()
            print('-'*80)
            print('Predicted transcription:\n' + '\n' + ''.join(int_sequence_to_text(pred_ints)))
            print('-'*80)  
           get_predictions(model,mfcc_vec[0])
This shows,
ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 4 array(s), but instead got the following list of 1 arrays: [array([[[-717.90515, -717.90515, -717.90515, ..., 0. ,
0. , 0. ],
[ 0. , 0. , 0. , ..., 0. ,
0. , 0. ],
...

**Comment by sushreebarsa** [comment]
@Qyum In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!
