### ISSUE TITLE
Issue in MaxPool1D with functional API

### ISSUE THREAD

**Issue by DarioArena87** [keras-team/keras#14613]
Hi i'm learning keras and i was experimenting with modifying a model previously built using the sequential API using the functional API. The model is a "mix" of the three main common layer, a convolutional layer, an LSTM layer and a Dense layer. The convolutional layer is a Conv1D and i'm trying to do a regression on a multivariate time serie (4 features per timestep)
If i build the model using the sequential model everything is fine

```    
keras_model = keras.Sequential([
        layers.Conv1D(filters=35, kernel_size=6),
        layers.MaxPool1D(),
        layers.LSTM(32),
        layers.Dense(32, activation='relu'),
        layers.Dense(10, activation='relu'),
        layers.Dense(4),
    ])
```
but if i use the functional API to build the model such that the convolutional layer and the LSTM are "in parallel" i get an error when i try to link the MaxPool1D after the Conv1D:
``` 
    batch_lenght = 180

    inputs = layers.Input(shape=(batch_length, 4))
    conv1d = layers.Conv1D(filters=35, kernel_size=6)(inputs),
    maxpool = layers.MaxPool1D()(conv1d),
    lstm = layers.LSTM(32)(inputs),
    conc = layers.concatenate([maxpool, lstm])
    dense = layers.Dense(32, activation='relu')(conc)
    output = layers.Dense(4)(dense)

    keras_model = keras.Model(inputs=inputs, outputs=output)
```
when keras tries to build the MaxPool1D layer it throws the following error:

> Traceback (most recent call last):
>   File "C:\tools\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1812, in _create_c_op
>     c_op = pywrap_tf_session.TF_FinishOperation(op_desc)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: Shape must be rank 4 but is rank 5 for '{{node max_pooling1d/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", ksize=[1, 2, 1, 1], padding="VALID", strides=[1, 2, 1, 1]](max_pooling1d/ExpandDims)' with input shapes: [1,?,1,175,35].
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "D:/Sviluppo/git/quantum/quantum-bootcamp-2/main.py", line 64, in <module>
>     model = build_keras_model(batch_length)
>   File "D:/Sviluppo/git/quantum/quantum-bootcamp-2/main.py", line 36, in build_keras_model
>     maxpool = layers.MaxPool1D()(conv1d),
>   File "C:\tools\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 925, in __call__
>     return self._functional_construction_call(inputs, args, kwargs,
>   File "C:\tools\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1117, in _functional_construction_call
>     outputs = call_fn(cast_inputs, *args, **kwargs)
>   File "C:\tools\Anaconda3\lib\site-packages\tensorflow\python\keras\layers\pooling.py", line 75, in call
>     outputs = self.pool_function(
>   File "C:\tools\Anaconda3\lib\site-packages\tensorflow\python\util\dispatch.py", line 201, in wrapper
>     return target(*args, **kwargs)
>   File "C:\tools\Anaconda3\lib\site-packages\tensorflow\python\keras\backend.py", line 5518, in pool2d
>     x = nn.max_pool(
>   File "C:\tools\Anaconda3\lib\site-packages\tensorflow\python\util\dispatch.py", line 201, in wrapper
>     return target(*args, **kwargs)
>   File "C:\tools\Anaconda3\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 4515, in max_pool
>     return gen_nn_ops.max_pool(
>   File "C:\tools\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 5266, in max_pool
>     _, _, _op, _outputs = _op_def_library._apply_op_helper(
>   File "C:\tools\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 742, in _apply_op_helper
>     op = g._create_op_internal(op_type_name, inputs, dtypes=None,
>   File "C:\tools\Anaconda3\lib\site-packages\tensorflow\python\framework\func_graph.py", line 591, in _create_op_internal
>     return super(FuncGraph, self)._create_op_internal(  # pylint: disable=protected-access
>   File "C:\tools\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3477, in _create_op_internal
>     ret = Operation(
>   File "C:\tools\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1974, in __init__
>     self._c_op = _create_c_op(self._graph, node_def, inputs,
>   File "C:\tools\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1815, in _create_c_op
>     raise ValueError(str(e))
> ValueError: Shape must be rank 4 but is rank 5 for '{{node max_pooling1d/MaxPool}} = MaxPool[T=DT_FLOAT, data_format="NHWC", ksize=[1, 2, 1, 1], padding="VALID", strides=[1, 2, 1, 1]](max_pooling1d/ExpandDims)' with input shapes: [1,?,1,175,35].

Maybe there's something i'm missing (i'm still a beginner) but shouldn't keras figure out the input shape of the MaxPooling1D himself based on the output shape of Conv1D layer?
I searched the internet to find some examples but i haven't found anything different from what i'm doing for Conv1D -> MaxPool1D

### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: yes
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 64bit
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**:
-   **TensorFlow installed from (source or binary)**: binary
-   **TensorFlow version (use command below)**: 2.3.0
-   **Python version**: 3.8.5
-   **Bazel version (if compiling from source)**:
-   **GCC/Compiler version (if compiling from source)**:
-   **CUDA/cuDNN version**: 11.2.2/11.2
-   **GPU model and memory**: NVIDIA GeForce RTX 2080 Super 8GB

**Comment by namaannn** [comment]
Use pool size in the MaxPool1D

**Comment by ymodak** [comment]
You can try reshape to 3d tensor before passing to pooling layer
See [example](https://www.tensorflow.org/api_docs/python/tf/keras/layers/MaxPool1D#args) for reference.
```python
conv1d = tf.keras.layers.Conv1D(filters=35, kernel_size=6)(inputs),
conv1d_reshape = tf.reshape(conv1d,[-1,35,1]) # Reshape to 3D tensor
print(tf.shape(conv1d1))
maxpool = tf.keras.layers.MaxPool1D()(conv1d_reshape)
```
