### ISSUE TITLE
Non-standard custom standardization function in TextVectorization

### ISSUE THREAD

**Issue by Keeyahto** [keras-team/keras#14618]
Hi! I'm going to use the TextVectorization layer in my project. My test sample is a numpy array:

```
array(['Boeing Quarterly Earnings Jump 78 Percent',
       'Western Afghan city quiet after bloody clashes',
       'Trash Your Xerox', 'Banks, insurers lead Nikkei higher',
       'Cisco unveils switches, software for SMBs',
       'A team with verve suddenly on the verge',
       'Dodgers sign Ledee to two-year deal', 'Apple high',
       'IMF Sees Robust U.S. Growth (Reuters)',
       'New Palm operating system targets smart phones'], dtype=object)
```

 In my standardization function, I reduce the entire string to lowercase, remove stop words, and remove punctuation using the tf.strings methods.

```
def custom_standardization(input_data):
    data = tf.strings.lower(input_data)
    data = tf.strings.regex_replace(
        data, "[%s]" % re.escape(string.punctuation), ""
    )
    for i in stopwords_eng:
        data = tf.strings.regex_replace(data, f' {i} ', " ")
    return data

```
I also wanted to implement the lemmatization of words in sentences using the WordNetLemmatizer from the nltk library, which accepts only elements of the str () type as input. How can I do this? 
TY

**Comment by sushreebarsa** [comment]
@Keeyahto Sorry for the late response! Could you please let us know if it is still an issue?
Could you please refer to the similar [issue](https://stackoverflow.com/questions/66878893/tensorflow-textvectorization-layer-how-to-define-a-custom-standardize-function) , [TextVectorization layer](https://keras.io/api/layers/preprocessing_layers/core_preprocessing_layers/text_vectorization/) and this [TF site](https://www.tensorflow.org/api_docs/python/tf/keras/layers/TextVectorization) and try with latest Tf v2.7.0 .Please let us know if it helps?Thank you!
