### ISSUE TITLE
How to load weights from .h5 file for WGAN-GP? I follow the official tutorial but don't know how to load weights for each epoch.

### ISSUE THREAD

**Issue by yifeipet** [keras-team/keras#14631]
Hi Keras Team,
I followed Keras's official tutorial for my project in WGAN-GP. The official tutorial is here: https://keras.io/examples/generative/wgan_gp/.

I add a checkpoint to save model weights of WGAN-GP only after each epoch during the training: 

mc = keras.callbacks.ModelCheckpoint('weight_save/weights{epoch:0.8d}.h5', save_weights_only=True, save_freq='epoch')

wgan.fit(train_ds, epochs = 100, callbacks = [mc])

After finishing training, I need to reload the model from one of the saved h5 files (total 100 files) using:

wgan.load_weights('weight_save/weights00000098.h5')

But it gives me an error that I need to call the model first. 

Then I try to call generator, discriminator, and WGAN models again. But it still gives me an error. 

Can anyone help me to solve this issue?

Thank you very much! 

Yifei

**Comment by mohamed-khoualed** [comment]
https://machinelearningmastery.com/save-load-keras-deep-learning-models/
