### ISSUE TITLE
input declaration issue with Embedding layer

### ISSUE THREAD

**Issue by ytiam** [keras-team/keras#14639]
![image](https://user-images.githubusercontent.com/13828878/117582101-e9d2b400-b11d-11eb-95fa-45939649161f.png)
In the Embedding function, should not the text_vocabulary_size be at the first position(input dim) and 64 at the second position (output dim)? 
Please help me to understand.

**Comment by mohamed-khoualed** [comment]
Did you try to execute it? 
  I think the best solution is to try an example with Keras doc  for embedding
Her is my code :
# -*- coding: utf-8 -*-
"""
Created on Mon May 10 02:45:13 2021

@author: Messaoud
"""
import numpy as np
from keras import layers
from keras.models import Model
from keras.layers import embeddings
from keras.models import Sequential
from keras.layers import embeddings
from keras.layers.embeddings import Embedding

model = Sequential()
model.add(Embedding(1000, 64, input_length=10))
input_array = np.random.randint(1000, size=(32, 10))
model.compile('rmsprop', 'mse')
output_array = model.predict(input_array)
assert output_array.shape == (32, 10, 64)

_running is ok_

-your paper : 
# -*- coding: utf-8 -*-
"""
Created on Mon May 10 02:45:13 2021

@author: Messaoud
"""
import numpy as np
from keras import layers
from keras.models import Model
from keras.layers import embeddings
from keras.models import Sequential
from keras.layers import embeddings
from keras.layers.embeddings import Embedding

model = Sequential()
model.add(Embedding(64, 1000, input_length=10))
input_array = np.random.randint(1000, size=(32, 10))
model.compile('rmsprop', 'mse')
output_array = model.predict(input_array)
assert output_array.shape == (32, 10, 64)

_Running return  InvalidArgumentError_


  File "C:\Users\Messaoud\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1458, in __call__
    run_metadata_ptr)

InvalidArgumentError: indices[30,1] = 789 is not in [0, 64)
	 [[{{node embedding_7/embedding_lookup}}]]

Please let me know if you find out somthing

**Comment by ytiam** [comment]
Yes, I executed the later one, as mentioned in the book, first. and got a similar kind of error you got. And then changed the function argument order as your first code block, and that is running fine. So I am a bit confused about why in the the textbook, it is written like that.

**Comment by ytiam** [comment]
Possibly that is what exactly happened, I also think so. 
The book is the one written by the Keras creator itself. Please check the below link:
[(https://www.manning.com/books/deep-learning-with-python)](url)
