### ISSUE TITLE
AttributeError: module 'keras.backend' has no attribute 'logsumexp'

### ISSUE THREAD

**Issue by gitfourteen** [keras-team/keras#14647]
Using Colab
keras.__version__ is 2.4.3 if `import keras` directly

when `help`([keras.backend.logsumexp](https://github.com/keras-team/keras/blob/master/keras/backend.py#L2574)), get error

AttributeError: module 'keras.backend' has no attribute 'logsumexp'

What's wrong?

**Comment by bizzmug** [comment]
same thing =(
have u find out where it is?

**Comment by gitfourteen** [comment]
> same thing =(
> have u find out where it is?

The best way is switch to `tf.math.reduce_logsumexp`. I don't want to change the default colab environment.

If checking `is 'logsumexp' in K` in colab default setting, you will get a `False`

No matter using `keras` script in old style
`import keras`
`from keras import backend as K`
or in [suggested way](https://keras.io)
`from tensorflow import keras`
`from tensorflow.keras import backend as K`


Don't know why this `keras.backend` keeps changing from version to version... I hope someone help elaborate more on this?

**Comment by jvishnuvardhan** [comment]
@gitfourteen Is this still an issue for you? 

I ran your code with recent `TF2.7` and I don't see any error. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/bdcaa66776ece061b958f23479ee9cef/untitled1107.ipynb). Thanks!

**Comment by gitfourteen** [comment]
Holy... run into this problem again when playing colab... and google popping out my own answer...

**Comment by gitfourteen** [comment]
> @gitfourteen Is this still an issue for you?
> 
> I ran your code with recent `TF2.7` and I don't see any error. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/bdcaa66776ece061b958f23479ee9cef/untitled1107.ipynb). Thanks!

Test with the way you import under tf 2.14, and utterly failed.
