### ISSUE TITLE
ValueError: Error when checking target: expected conv2d_transpose_6 to have shape (258, 258, 19) but got array with shape (258, 258, 3)

### ISSUE THREAD

**Issue by Sayandas** [keras-team/keras#14645]
ValueError                                Traceback (most recent call last)
<ipython-input-18-e88cba476bc9> in <module>
      2 model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
      3 print("sjj")
----> 4 model.fit(x_train,y_train,batch_size = 4, verbose=1, epochs=10, validation_data=(x_test, y_test), shuffle=False)

~/anaconda3/lib/python3.8/site-packages/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
   1148 
   1149         # Case 2: Symbolic tensors or Numpy array-like.
-> 1150         x, y, sample_weights = self._standardize_user_data(
   1151             x, y,
   1152             sample_weight=sample_weight,

~/anaconda3/lib/python3.8/site-packages/keras/engine/training.py in _standardize_user_data(self, x, y, sample_weight, class_weight, check_array_lengths, batch_size)
    614 
    615             # Standardize the outputs.
--> 616             y = training_utils.standardize_input_data(
    617                 y,
    618                 feed_output_names,

~/anaconda3/lib/python3.8/site-packages/keras/engine/training_utils.py in standardize_input_data(data, names, shapes, check_batch_axis, exception_prefix)
    139                 for dim, ref_dim in zip(data_shape, shape):
    140                     if ref_dim != dim and ref_dim:
--> 141                         raise ValueError(
    142                             'Error when checking ' + exception_prefix +
    143                             ': expected ' + names[i] + ' to have shape ' +

ValueError: Error when checking target: expected conv2d_transpose_6 to have shape (258, 258, 19) but got array with shape (258, 258, 3)

![Screenshot from 2021-05-15 18-35-55](https://user-images.githubusercontent.com/21043058/118362256-7234d700-b5ac-11eb-9c62-1154f62867ec.png)

![Screenshot from 2021-05-15 18-36-05](https://user-images.githubusercontent.com/21043058/118362268-7b25a880-b5ac-11eb-985a-94187d7e4eaf.png)

I see this error where i number of classes is 19.
How can fixed it

code - 

Data fetch

import cv2
import os
import imutils 
from imutils import paths
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
#path
train_xl='/media/sayan/UBUNTU 20_0/bdd100k_seg/bdd100k/seg/images/train'
train_yl='/media/sayan/UBUNTU 20_0/bdd100k_seg/bdd100k/seg/color_labels/train'

w_train_x=os.listdir(train_xl)[:1000]
w_train_y=os.listdir(train_yl)[:1000]
xr=258
yr=258
x_a=np.zeros((len(w_train_x),xr,yr,3),dtype=np.float32)
y_a=np.zeros((len(w_train_y),xr,yr,3),dtype=np.float32)
c=0
for i in w_train_x:
    n=w_train_x.index(i)
    path_x=os.path.join(train_xl,i)
    try:
        v=np.array(cv2.imread(path_x,1))
        v=cv2.resize(v,(xr,yr))
        x_a[n]=v
        path_y=os.path.join(train_yl,w_train_y[n])
        v1=np.array(cv2.imread(path_y,1))
        v1=cv2.resize(v1,(xr,yr))
        y_a[n]=v1
    except Exception as e:
        print(e)
        print(path_y)
    #c=c+1
    #if(c==100):
        #break
x_train,x_test,y_train,y_test=train_test_split(x_a,y_a,test_size=0.20,random_state=2019)
#model 

from keras.models import Model
from keras.layers import Input, Conv2D, MaxPooling2D, UpSampling2D, concatenate, Conv2DTranspose, BatchNormalization, Dropout, Lambda

#conv-mpool-conv-mpool-conv-conv-conv-mpool
def alexNet(noClass,img_height,img_width,img_channel):
    inputs = Input((img_height, img_width, img_channel))
    s=inputs
    c1 = Conv2D(96, (3, 3),strides=(1,1), activation='relu', kernel_initializer='he_normal')(s)
    c1=BatchNormalization()(c1)
    c1 = MaxPooling2D(pool_size=(2,2))(c1)
    
    c1 = Conv2D(96, (3,3),strides=(1,1), activation='relu', kernel_initializer='he_normal',padding='same')(c1)
    c1=BatchNormalization()(c1)
    c1=MaxPooling2D(pool_size=(2,2))(c1)
    
    c1=Conv2D(96, (3,3),strides=(1,1), activation='relu', kernel_initializer='he_normal',padding='same')(c1)
    c1=BatchNormalization()(c1)
    c1=Conv2D(96, (3,3),strides=(1,1), activation='relu', kernel_initializer='he_normal',padding='same')(c1)
    c1=BatchNormalization()(c1)
    c1=Conv2D(96, (3,3),strides=(1,1), activation='relu', kernel_initializer='he_normal',padding='same')(c1)
    c1=BatchNormalization()(c1)
    
    c1=MaxPooling2D(pool_size=(2,2))(c1)
    #decode
    
    c2=UpSampling2D(size=(2,2))(c1)
    
    #c2=Conv2DTranspose(256, (3,3),strides=(2,2), activation='relu', kernel_initializer='he_normal',padding='same')(c1)#--
    
    c2=Conv2DTranspose(96, (3,3),strides=(1,1), activation='relu', kernel_initializer='he_normal',padding='same')(c2)
    c2=BatchNormalization()(c2)
    c2=Conv2DTranspose(96, (3,3),strides=(1,1), activation='relu', kernel_initializer='he_normal',padding='same')(c2)
    c2=BatchNormalization()(c2)
    c2=Conv2DTranspose(96, (3,3),strides=(1,1), activation='relu', kernel_initializer='he_normal',padding='same')(c2)
    c2=BatchNormalization()(c2)
    
    
    c2=UpSampling2D(size=(2,2))(c2)
    
    #c2=Conv2DTranspose(256, (3,3),strides=(2,2), activation='relu', kernel_initializer='he_normal',padding='same')(c2)#--
    
    c2=Conv2DTranspose(96, (3,3),strides=(1,1), activation='relu', kernel_initializer='he_normal',padding='same')(c2)
    c2=BatchNormalization()(c2)
    
    c2=UpSampling2D(size=(2,2))(c2)
    c2=BatchNormalization()(c2)
    #c2=Conv2DTranspose(96, (3,3),strides=(2,2), activation='relu', kernel_initializer='he_normal',padding='same')(c2)#--
    
    c2=Conv2DTranspose(96, (3, 3),strides=(1,1), activation='relu', kernel_initializer='he_normal')(c2)
    c2=BatchNormalization()(c2)
    outputs=Conv2DTranspose(noClass, (1, 1), activation='softmax',kernel_initializer='he_normal')(c2)
    print(outputs.shape)
    
    print("ghhg")
    model = Model(inputs=[inputs], outputs=[outputs])
    model.summary()
    return model
    

model=alexNet(noClass=19, img_height=xr, img_width=yr, img_channel=3)
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
print("sjj")
model.fit(x_train,y_train,batch_size = 4, verbose=1, epochs=10, validation_data=(x_test, y_test), shuffle=False)

    Please help me ! Thank You

**Comment by jvishnuvardhan** [comment]
@Sayandas Can you please share a standalone code to reproduce the issue? Can you use a public dataset like `mnist` or something like that so that I can reproduce the issue. Thanks!
