### ISSUE TITLE
A suspected bug in the LSTM layer using cntk backend

### ISSUE THREAD

**Issue by River861** [keras-team/keras#14653]
Hi, I found inconsistency between the LSTM results calculated using the CNTK backend and the TensorFlow backend in keras2.3.1.
(I'm not sure if you're still maintaining multi-backend Keras, but I still want to raise this issue)

Detail information:
1. the arguments of LSTM layer
```
{
    "units": 2, 
    "activation": null, 
    "recurrent_activation": "tanh", 
    "use_bias": true, 
    "kernel_initializer": "random_uniform", 
    "recurrent_initializer": "random_uniform", 
    "bias_initializer": "random_uniform", 
    "unit_forget_bias": true, 
    "kernel_regularizer": null, 
    "recurrent_regularizer": null, 
    "bias_regularizer": null, 
    "activity_regularizer": null, 
    "kernel_constraint": null, 
    "recurrent_constraint": null, 
    "bias_constraint": null, 
    "dropout": 0, 
    "recurrent_dropout": 0, 
    "implementation": 2, 
    "return_sequences": false, 
    "return_state": false, 
    "go_backwards": false, 
    "stateful": false, 
    "unroll": false, 
    "name": "01_LSTM"
}
```

2. the weights of the LSTM layer
```
[array([[ 1.990736  ,  6.518715  ,  0.693779  ,  7.2438393 ,  1.420124  ,
         9.532984  , -0.6925678 ,  0.70940495],
       [ 3.6698008 , -1.0963745 ,  7.268093  , -1.8293142 , -6.9470477 ,
        -7.67282   , -1.8248796 ,  9.939407  ],
       [ 0.25988102,  5.5951138 , -1.0814047 ,  0.83802414,  1.3759708 ,
        -9.718197  ,  0.29959202, -2.7941465 ],
       [ 8.18062   ,  6.262762  , -6.7835093 ,  8.291611  ,  7.7360706 ,
        -3.4840512 , -8.364613  ,  7.246643  ]], dtype=float32), array([[ 9.568584 ,  1.7660522, -1.8287392, -8.905315 , -7.9364085,
        -3.597951 , -2.2792244, -8.496578 ],
       [-6.268451 ,  5.031085 , -4.384835 , -5.812278 ,  3.5230274,
        -3.836372 ,  9.967682 ,  5.0702953]], dtype=float32), array([ 2.1580791, -7.2620487,  1.       ,  1.       , -2.160828 ,
       -2.536323 ,  4.4840355, -5.096214 ], dtype=float32)]
```

3. the input tensor of the LSTM layer
```
[[46.57555061 51.0488424   9.02725368 23.49946975]
 [80.51310727 90.77741174 86.92215041 90.6576631 ]
 [63.35784393 82.52023272 80.99867875 15.82916619]]
```

4. the inconsistency of the output tensor
```
tensorflow:
[-3187.0117  7523.2666]
cntk:
[-3187.0117 -7523.2666]
```

I suspect that the code that caused the inconsistency might be here：
the LSTMCell return the states in the order of "h" first, "c" last,
https://github.com/keras-team/keras/blob/f295e8ee39d4ba841ac281a9337d69c7bc5e0eb6/keras/layers/recurrent.py#L2056
however the rnn function in cntk_backend.py regards the last state value(that is, the "c" value) as the output.
https://github.com/keras-team/keras/blob/f295e8ee39d4ba841ac281a9337d69c7bc5e0eb6/keras/backend/cntk_backend.py#L1627

**Comment by jpcf** [comment]
Check my bug report from 2 days ago

**Comment by rendaixu** [comment]
Please attach the code to reproduce this bug, thanks.

**Comment by jvishnuvardhan** [comment]
@River861 Sorry for the late response. We are currently supporting only TF backend.  Sorry for the inconvenience. 

Please post it in Stackoverflow where there is a large community to support and learn from each other's issues. If you face any Bugs and performance related issues with recent TF/Keras versions then please post them here. Thanks!
