### ISSUE TITLE
AttributeError: module 'keras.utils.generic_utils' has no attribute 'to_snake_case'

### ISSUE THREAD

**Issue by kiflowb777** [keras-team/keras#14657]
When I try to import keras:
```python
from keras import backend as K
```
I get:
```
AttributeError: module 'keras.utils.generic_utils' has no attribute 'to_snake_case'
```

I tried on versions 2.4.3, 2.3.1, 2.2.5

**Comment by ldasey** [comment]
same here

**Comment by mingwugmail** [comment]
I think the problem is caused some interaction between this two files (virtual `env`):

```
$ find env -name generic_utils.py
env/lib/python3.9/site-packages/tensorflow/python/keras/utils/generic_utils.py
env/lib/python3.9/site-packages/keras/utils/generic_utils.py
```

I added this import to `env/lib/python3.9/site-packages/keras/utils/generic_utils.py`:
```
from tensorflow.python.keras.utils.generic_utils import populate_dict_with_module_objects, to_snake_case
```

it seems worked.


(instead of copy code as said here:
https://stackoverflow.com/a/63956150                                                                                                                                              
)

**Comment by Kshitij-AI** [comment]
Can anyone help me with this?

model = sm.Unet(BACKBONE, encoder_weights='imagenet')

Error:

AttributeError                            Traceback (most recent call last)
<ipython-input-52-4d8687568079> in <module>()
----> 1 model = sm.Unet(BACKBONE, encoder_weights='imagenet')
      2 model.compile(optimizer='adam', loss=sm.losses.bce_jaccard_loss, metrics=['accuracy', sm.metrics.iou_score])

6 frames
/usr/local/lib/python3.7/dist-packages/classification_models/weights.py in load_model_weights(model, model_name, dataset, classes, include_top, **kwargs)
     23                              ' as true, `classes` should be {}'.format(weights['classes']))
     24 
---> 25         weights_path = keras_utils.get_file(
     26             weights['name'],
     27             weights['url'],

AttributeError: module 'keras.utils' has no attribute 'get_file'

**Comment by ldasey** [comment]
try:
`from tensorflow.keras.utils import get_file`

**Comment by Kshitij-AI** [comment]
@ldasey Thank you for your reply.
I have already tried doing that, still the same error.

**Comment by ldasey** [comment]
for a quick fix: try removing keras completely and only use keras within tensorflow

**Comment by jvishnuvardhan** [comment]
@kiflowb777 @Kshitij-AI Is this still an issue for you? Can you please share a simple standalone code to reproduce the issue?

Please check with `TF2.6` and let me know whether the issue persists. Thanks!
