### ISSUE TITLE
Can't save a model on M1 Mac due to h5py import error

### ISSUE THREAD

**Issue by nanhyang9** [keras-team/keras#14654]
Testing environment:
- Apple M1 MBA
- python 3.8.10
- tensorflow (for arm64) 2.4.0rc0
installed using `pip install --upgrade --force --no-dependencies https://github.com/apple/tensorflow_macos/releases/download/v0.1alpha3/tensorflow_macos-0.1a3-cp38-cp38-macosx_11_0_arm64.whl https://github.com/apple/tensorflow_macos/releases/download/v0.1alpha3/tensorflow_addons_macos-0.1a3-cp38-cp38-macosx_11_0_arm64.whl`
- keras 2.4.3 (tried 2.4.2 and 2.5.0rc0, as well)
- h5py 3.1.0 
- hdf5 1.10.6

Tensorflow for M1 Mac and Keras worked like a charm until `ModelCheckpoint` tries to save a model. When `ModelCheckpoint` tries to save a model, the following error is produced:

> ```ImportError                               Traceback (most recent call last)
> <ipython-input-20-dc3457728774> in <module>
> ----> 1 history = model.fit(X_train, y_train, callbacks = [es, mc], epochs = 15, batch_size = 256, validation_split = .2)
> 
> ~/miniforge3/envs/tf_m1/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
>    1143           epoch_logs.update(val_logs)
>    1144 
> -> 1145         callbacks.on_epoch_end(epoch, epoch_logs)
>    1146         training_logs = epoch_logs
>    1147         if self.stop_training:
> 
> ~/miniforge3/envs/tf_m1/lib/python3.8/site-packages/tensorflow/python/keras/callbacks.py in on_epoch_end(self, epoch, logs)
>     426     for callback in self.callbacks:
>     427       if getattr(callback, '_supports_tf_logs', False):
> --> 428         callback.on_epoch_end(epoch, logs)
>     429       else:
>     430         if numpy_logs is None:  # Only convert once.
> 
> ~/miniforge3/envs/tf_m1/lib/python3.8/site-packages/tensorflow/python/keras/callbacks.py in on_epoch_end(self, epoch, logs)
>    1342     # pylint: disable=protected-access
>    1343     if self.save_freq == 'epoch':
> -> 1344       self._save_model(epoch=epoch, logs=logs)
>    1345 
>    1346   def _should_save_on_batch(self, batch):
> 
> ~/miniforge3/envs/tf_m1/lib/python3.8/site-packages/tensorflow/python/keras/callbacks.py in _save_model(self, epoch, logs)
>    1394                     filepath, overwrite=True, options=self._options)
>    1395               else:
> -> 1396                 self.model.save(filepath, overwrite=True, options=self._options)
>    1397             else:
>    1398               if self.verbose > 0:
> 
> ~/miniforge3/envs/tf_m1/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py in save(self, filepath, overwrite, include_optimizer, save_format, signatures, options, save_traces)
>    1999     """
>    2000     # pylint: enable=line-too-long
> -> 2001     save.save_model(self, filepath, overwrite, include_optimizer, save_format,
>    2002                     signatures, options, save_traces)
>    2003 
> 
> ~/miniforge3/envs/tf_m1/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py in save_model(model, filepath, overwrite, include_optimizer, save_format, signatures, options, save_traces)
>     151           'to the Tensorflow SavedModel format (by setting save_format="tf") '
>     152           'or using `save_weights`.')
> --> 153     hdf5_format.save_model_to_hdf5(
>     154         model, filepath, overwrite, include_optimizer)
>     155   else:
> 
> ~/miniforge3/envs/tf_m1/lib/python3.8/site-packages/tensorflow/python/keras/saving/hdf5_format.py in save_model_to_hdf5(model, filepath, overwrite, include_optimizer)
>      82 
>      83   if h5py is None:
> ---> 84     raise ImportError('`save_model` requires h5py.')
>      85 
>      86   # TODO(psv) Add warning when we save models that contain non-serializable
> 
> ImportError: `save_model` requires h5py.

Here is the minimum code to reproduce the issue:

> ```import re
> from tensorflow.keras.preprocessing.sequence import pad_sequences
> from tensorflow.keras.models import Sequential
> from tensorflow.keras.layers import Embedding, GRU, Dense, LSTM
> from tensorflow.keras.utils import to_categorical
> from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
> from tensorflow.keras.datasets import imdb
> 
> vocab_size = 10000
> (X_train, y_train), (X_test, y_test) = imdb.load_data(num_words = 10000)
> maxlen = 500
> X_train = pad_sequences(X_train, maxlen = maxlen)
> X_test = pad_sequences(X_test, maxlen = maxlen)
> model = Sequential()
> model.add(Embedding(vocab_size, 100))
> model.add(LSTM(128))
> model.add(Dense(1, activation = 'sigmoid'))
> es = EarlyStopping(monitor = 'val_loss', mode = 'min', patience = 4, verbose = 1)
> mc = ModelCheckpoint('best_model_imdb.h5', monitor = 'val_acc', mode = 'max', save_best_only = True)
> model.compile(loss='binary_crossentropy', optimizer = 'adam', metrics = ['acc'])
> history = model.fit(X_train, y_train, callbacks = [es, mc], epochs = 15, batch_size = 256, validation_split = .2)```

Tried to install and test different versions of `h5py` and `hdf5` but neither `conda` nor `pip` worked due to package conflicts.

Any help would be appreciated.

**Comment by jvishnuvardhan** [comment]
@nanhyang9 I think, this is more related to M1 chip [tensorflow_macos](https://github.com/apple/tensorflow_macos). 

Please post them in their repo. We don't have any control on that TF build. Thanks!

Also, we don't have access to an M1 macbook to test this issue. Thanks!

We suggest asking on the apple developer forum:
https://developer.apple.com/forums/tags/tensorflow-metal
