### ISSUE TITLE
ValueError: `sequences` must be a list of iterables. Found non-iterable: 0.0382184

### ISSUE THREAD

**Issue by amine-boukriba** [keras-team/keras#14660]
I am extracting Mel spectrogram from the audio file then I want to apply padding

`y,sr = librosa.load(r"/content/test.WAV")
mel = librosa.feature.melspectrogram(y=y, sr=sr)
mel=np.mean(mel, axis=0)
mel=tf.keras.preprocessing.sequence.pad_sequences(mel,maxlen=1500)`
but I am receiving TypeError: object of type 'numpy.float32' has no len()During handling of the above exception, another exception occurred:
ValueError: sequences must be a list of iterables. Found non-iterable: 0.0382184 I tried changing`mel=tf.keras.preprocessing.sequence.pad_sequences(list(mel),maxlen=1500)`
and it didn't work .
 tried doing some reshaping by using `mel=mel.reshape(1,mel.shape[0])` it works without error but it gives an array full of zeros

**Comment by jvishnuvardhan** [comment]
@amine-boukriba Can you please share a simple standalone code to reproduce the issue? You could use public datasets. Thanks!
