### ISSUE TITLE
Not able to load keras

### ISSUE THREAD

**Issue by abhishek111222** [keras-team/keras#14662]
So I changed my keras to version 1.1.0; by the following command in google colab : 
!pip install q keras==1.1.0

But now I am not able to import keras. It is showing me this error.

AttributeError                            Traceback (most recent call last)
<ipython-input-4-88d96843a926> in <module>()
----> 1 import keras

2 frames
/usr/local/lib/python3.7/dist-packages/keras/backend/tensorflow_backend.py in <module>()
     15 
     16 _SESSION = None
---> 17 _LEARNING_PHASE = tf.placeholder(dtype='uint8', name='keras_learning_phase')  # 0 = test, 1 = train
     18 _MANUAL_VAR_INIT = False
     19 

AttributeError: module 'tensorflow' has no attribute 'placeholder'

![12](https://user-images.githubusercontent.com/49861521/119433273-d7f03400-bd0d-11eb-8841-d84d9600603a.PNG)

**Comment by rahulkapoor253** [comment]
There might be some issue with the TensorFlow version which comes by default in Google Colab. Try to import tensorflow.compat.v1

**Comment by jvishnuvardhan** [comment]
@abhishek111222 You need to add the following lines before importing keras

```
import os
os.environ['KERAS_BACKEND'] = 'theano'
```

WIth that modification, I was able to import keras1.1.0. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/f1113e9f020bb78d56bbbb4c2300cb89/untitled.ipynb). Thanks!

**Comment by jvishnuvardhan** [comment]
I am closing this issue as this was resolved. Feel free to reopen if I am mistaken. Thanks!
