### ISSUE TITLE
 No module named 'keras.legacy'

### ISSUE THREAD

**Issue by siwarbouziri** [keras-team/keras#14665]
hello,
when I try to use keras.legacy I get this error
 "No module named 'keras.legacy'"
my keras version is "2.4.3"
what is the possible solution to deal with this error and I can't downgrade my keras version 

thank you

**Comment by sagnik1511** [comment]
> hello,
> when I try to use keras.legacy I get this error
> "No module named 'keras.legacy'"
> my keras version is "2.4.3"
> what is the possible solution to deal with this error and I can't downgrade my keras version
> 
> thank you


Try this

        from keras import legacy_tf_layers

**Comment by jvishnuvardhan** [comment]
@siwarbouziri Looks like `legacy` module is not supported in current keras. May be you could create a conda environment and inside that you can install keras 2.3.1 and use it.

We are not supporting older keras versions anymore. Please post them in [TF Forum](https://discuss.tensorflow.org/tags) or Stackoverflow. Thanks!
