### ISSUE TITLE
Is Keras supported in python3.9?

### ISSUE THREAD

**Issue by Nizarazo** [keras-team/keras#14667]
Hi

Is Keras supported in python3.9? 
if yes which version support python3.9?
if no is it in work? and when is the expected release date? and which version it will be?

Thanks

**Comment by ymodak** [comment]
Keras is compatible with Python 3.6+ 
See https://pypi.org/project/keras/2.4.3/
You may also try the latest version https://pypi.org/project/keras/2.6.0rc1/

**Comment by Nizarazo** [comment]
Hi @ymodak 

Thanks for your reply.
Which version of Keras support Python3.9?

Thanks

**Comment by ymodak** [comment]
Python 3.9 support was added to TensorFlow with 2.5
Therefore you can try Keras 2.5 and above for python 3.9

**Comment by Nizarazo** [comment]
@ymodak , Thanks for your reply.
Ticket is closed.
