### ISSUE TITLE
ValueError: You are trying to load a weight file containing 1 layers into a model with 2 layers.

### ISSUE THREAD

**Issue by AhmedAlshoki** [keras-team/keras#14679]
I used keras to fine tuning VGG16 and I have coded this piece of code on Google Colab as following 
```
def Create_Model():
  #input_shape = (150,150,3)
  model_1 = VGG16(weights='imagenet',include_top=False)
  input = keras.layers.Input(shape=(150,150,3))
  Last_layer=model_1(input)

  Model_Vgg=keras.layers.Flatten()(Last_layer)   
  Model_Vgg = layers.Dropout(0.5)(Model_Vgg)
  Model_Vgg = layers.Dense(units=3, activation='softmax') (Model_Vgg)
  model = keras.Model(inputs =input,outputs = Model_Vgg )
  return model
model = Create_Model()  
model.compile(loss='categorical_crossentropy',optimizer=optimizers.SGD(lr=0.005708),metrics=['accuracy'])

monitor = EarlyStopping(monitor='accuracy',patience=50, mode='auto', restore_best_weights=True)
model.fit(X_Train,Y_Train,callbacks=[monitor],epochs=280,batch_size=50,verbose=1)
model.save_weights('/content/drive/MyDrive/Graduation Project/model_weights.h5')
```
and I loaded those weight on colab too and it worked perfectly 
but when I tried same code on local machine , it throws error as shown however I used same model on train those and the same architecture can not load those weights for mismatching 
Thanks for Advanced

**Comment by shubham0204** [comment]
Can you share the code you used to load the weights on your local machine?

**Comment by jvishnuvardhan** [comment]
@AhmedAlshoki Similar error was noticed when the model was saved in `h5` format. Saving in `tf` saved model format worked as expected. Please check [this issue](https://github.com/tensorflow/tensorflow/issues/34016#issuecomment-551207888) that was resolved earlier. Thanks!

If you notice any error when you save in `tf` format, then share a simple standalone code to reproduce the issue. Thanks!

**Comment by jvishnuvardhan** [comment]
I assume this was resolved in recent TF version. Please feel free to reopen if the issue persist with recent TF versions. Thanks!
