### ISSUE TITLE
ImportError: cannot import name 'convert_all_kernels_in_model' from 'keras.utils.layer_utils' 

### ISSUE THREAD

**Issue by gabirelasanchezzz** [keras-team/keras#14675]
My code worked perfectly on colab. I went to run it today and I cannot execute as this error keeps popping up. I went to layer_utils and there is no convert_all_kernels_in_model function. Anyone knows how to fix this or experienced this error?? Thanks

**Comment by Raghavendrapara** [comment]
Hi there,
try using tensorflow.keras.utils explicitly instead of keras.utils.

**Comment by 400lbhacker** [comment]
on colab... at the following magic line at the begining of your code cell
%tensorflow_version 1.x
