### ISSUE TITLE
AttributeError: module 'keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'

### ISSUE THREAD

**Issue by Maximevdm** [keras-team/keras#14677]
I'm having trouble with keras_self_attention import SeqSelfAttention.
It gives the error:
generic_utils.populate_dict_with_module_objects(
AttributeError: module 'keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'

Does someone know how to solve this problem?

**Comment by ymodak** [comment]
Would you please change your imports to `from tensorflow import keras` and try again?
Replace all `keras` imports to `tensorflow.keras`
