### ISSUE TITLE
NumPy 1.20 Compatibility Issue

### ISSUE THREAD

**Issue by jbroot** [keras-team/keras#14687]
Using the latest software: Keras 2.4.3; Tensorflow 2.5.0; and Python 3.9.5.
This code works with NumPy 1.19.5 but not >= 1.20:

```
import keras
from keras import layers

class m(keras.Model):
    def __init__(self):
        super(m, self).__init__()
        self.inputs = keras.Input(shape=(12, 1))
        self.allLayers = [self.inputs]
        self.allLayers.append(
            layers.Bidirectional(layers.LSTM(
                units=int(12 * 1.5), stateful=False, return_sequences=True
            ))(self.allLayers[-1])
        )

model = m()
```

Receives this error:

> NotImplementedError: Cannot convert a symbolic Tensor (lstm/strided_slice:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported

From this traceback:

> Traceback (most recent call last):
>   File "/home/j/.Pycharm/venv/phdCode/lib/python3.9/site-packages/tensorflow/python/training/tracking/base.py", line 522, in _method_wrapper
>     result = method(self, *args, **kwargs)
>   File "/home/j/.Pycharm/venv/phdCode/lib/python3.9/site-packages/keras/engine/sequential.py", line 208, in add
>     layer(x)
>   File "/home/j/.Pycharm/venv/phdCode/lib/python3.9/site-packages/keras/layers/recurrent.py", line 660, in __call__
>     return super(RNN, self).__call__(inputs, **kwargs)
>   File "/home/j/.Pycharm/venv/phdCode/lib/python3.9/site-packages/keras/engine/base_layer.py", line 945, in __call__
>     return self._functional_construction_call(inputs, args, kwargs,
>   File "/home/j/.Pycharm/venv/phdCode/lib/python3.9/site-packages/keras/engine/base_layer.py", line 1083, in _functional_construction_call
>     outputs = self._keras_tensor_symbolic_call(
>   File "/home/j/.Pycharm/venv/phdCode/lib/python3.9/site-packages/keras/engine/base_layer.py", line 816, in _keras_tensor_symbolic_call
>     return self._infer_output_signature(inputs, args, kwargs, input_masks)
>   File "/home/j/.Pycharm/venv/phdCode/lib/python3.9/site-packages/keras/engine/base_layer.py", line 856, in _infer_output_signature
>     outputs = call_fn(inputs, *args, **kwargs)
>   File "/home/j/.Pycharm/venv/phdCode/lib/python3.9/site-packages/keras/layers/recurrent_v2.py", line 1139, in call
>     inputs, initial_state, _ = self._process_inputs(inputs, initial_state, None)
>   File "/home/j/.Pycharm/venv/phdCode/lib/python3.9/site-packages/keras/layers/recurrent.py", line 860, in _process_inputs
>     initial_state = self.get_initial_state(inputs)
>   File "/home/j/.Pycharm/venv/phdCode/lib/python3.9/site-packages/keras/layers/recurrent.py", line 642, in get_initial_state
>     init_state = get_initial_state_fn(
>   File "/home/j/.Pycharm/venv/phdCode/lib/python3.9/site-packages/keras/layers/recurrent.py", line 2508, in get_initial_state
>     return list(_generate_zero_filled_state_for_cell(
>   File "/home/j/.Pycharm/venv/phdCode/lib/python3.9/site-packages/keras/layers/recurrent.py", line 2990, in _generate_zero_filled_state_for_cell
>     return _generate_zero_filled_state(batch_size, cell.state_size, dtype)
>   File "/home/j/.Pycharm/venv/phdCode/lib/python3.9/site-packages/keras/layers/recurrent.py", line 3006, in _generate_zero_filled_state
>     return tf.nest.map_structure(create_zeros, state_size)
>   File "/home/j/.Pycharm/venv/phdCode/lib/python3.9/site-packages/tensorflow/python/util/nest.py", line 867, in map_structure
>     structure[0], [func(*x) for x in entries],
>   File "/home/j/.Pycharm/venv/phdCode/lib/python3.9/site-packages/tensorflow/python/util/nest.py", line 867, in <listcomp>
>     structure[0], [func(*x) for x in entries],
>   File "/home/j/.Pycharm/venv/phdCode/lib/python3.9/site-packages/keras/layers/recurrent.py", line 3003, in create_zeros
>     return tf.zeros(init_state_size, dtype=dtype)
>   File "/home/j/.Pycharm/venv/phdCode/lib/python3.9/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
>     return target(*args, **kwargs)
>   File "/home/j/.Pycharm/venv/phdCode/lib/python3.9/site-packages/tensorflow/python/ops/array_ops.py", line 2911, in wrapped
>     tensor = fun(*args, **kwargs)
>   File "/home/j/.Pycharm/venv/phdCode/lib/python3.9/site-packages/tensorflow/python/ops/array_ops.py", line 2960, in zeros
>     output = _constant_if_small(zero, shape, dtype, name)
>   File "/home/j/.Pycharm/venv/phdCode/lib/python3.9/site-packages/tensorflow/python/ops/array_ops.py", line 2896, in _constant_if_small
>     if np.prod(shape) < 1000:
>   File "<__array_function__ internals>", line 5, in prod
>   File "/home/j/.Pycharm/venv/phdCode/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 3030, in prod
>     return _wrapreduction(a, np.multiply, 'prod', axis, dtype, out,
>   File "/home/j/.Pycharm/venv/phdCode/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
>     return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
>   File "/home/j/.Pycharm/venv/phdCode/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 867, in __array__
>     raise NotImplementedError(
> NotImplementedError: Cannot convert a symbolic Tensor (lstm/strided_slice:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported

Process finished with exit code 1

**Comment by jvishnuvardhan** [comment]
@jbroot  TF was built with 'numpy ~= 1.19.2' . Please check [here](https://github.com/tensorflow/tensorflow/blob/r2.5/tensorflow/tools/pip_package/setup.py#L84) to know all the packages and their versions that were used when building TF pip package2.5. 

As there are some in compatibility with `numpy1.20` version, currently `TF2.5` cannot support `numpy1.20`. There is a specific issue to track the progress on implementing `numpy1.20` for future versions of TF. You can check the progress [here](https://github.com/tensorflow/tensorflow/issues/47691)
Thanks!

**Comment by jbroot** [comment]
Thanks for the information.
