### ISSUE TITLE
can anyone help to combine two models

### ISSUE THREAD

**Issue by pavanpotteti** [keras-team/keras#14682]
```
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import MobileNetV2,Xception
from tensorflow.keras.layers import AveragePooling2D
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Input,Concatenate,concatenate
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
from tensorflow.keras.applications.xception import preprocess_input
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.preprocessing.image import load_img
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelBinarizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from imutils import paths
import matplotlib.pyplot as plt
import numpy as np
import argparse
import os

ap = argparse.ArgumentParser()
ap.add_argument("-d", "--dataset", default="dataset",
	help="path to input dataset")
ap.add_argument("-p", "--plot", type=str, default="plot.png",
	help="path to output loss/accuracy plot")
ap.add_argument("-m", "--model", type=str,
	default="mask_detector.model",
	help="path to output face mask detector model")
args = vars(ap.parse_args())

# initialize the initial learning rate, number of epochs to train for,
# and batch size
INIT_LR = 1e-4
EPOCHS = 2
BS = 32

# grab the list of images in our dataset directory, then initialize
# the list of data (i.e., images) and class images
print("[INFO] loading images...")
imagePaths = list(paths.list_images(args["dataset"]))
data = []
labels = []

# loop over the image paths
for imagePath in imagePaths:
	# extract the class label from the filename
	label = imagePath.split(os.path.sep)[-2]

	# load the input image (224x224) and preprocess it
	image = load_img(imagePath, target_size=(224, 224))
	image = img_to_array(image)
	image = preprocess_input(image)

	# update the data and labels lists, respectively
	data.append(image)
	labels.append(label)

# convert the data and labels to NumPy arrays
data = np.array(data, dtype="float32")
labels = np.array(labels)
# perform one-hot encoding on the labels
lb = LabelBinarizer()
labels = lb.fit_transform(labels)
labels = to_categorical(labels)

# partition the data into training and testing splits using 75% of
# the data for training and the remaining 25% for testing
(trainX, testX, trainY, testY) = train_test_split(data, labels,
                                                  test_size=0.20, stratify=labels, random_state=42)         

                      

# construct the training image generator for data augmentation
aug = ImageDataGenerator(
	rotation_range=20,
	zoom_range=0.15,
	width_shift_range=0.2,
	height_shift_range=0.2,
	shear_range=0.15,
	horizontal_flip=True,
	fill_mode="nearest")

# load the MobileNetV2 network, ensuring the head FC layer sets are
# left off
baseModel = MobileNetV2(weights="imagenet", include_top=False,
	input_tensor=Input(shape=(224, 224, 3)))
baseModel1=Xception(weights="imagenet",include_top=False,input_tensor=Input(shape=(224,224,3)))

# construct the head of the model that will be placed on top of the
# the base model
headModel = baseModel.output
headModel = AveragePooling2D(pool_size=(7, 7))(headModel)
headModel = Flatten(name="flatten")(headModel)
headModel = Dense(128, activation="relu")(headModel)
headModel = Dropout(0.5)(headModel)
headModel = Dense(2, activation="softmax")(headModel)
headModel1 = baseModel1.output
headModel1 = AveragePooling2D(pool_size=(7, 7))(headModel1)
headModel1 = Flatten(name="flatten")(headModel1)
headModel1 = Dense(128, activation="relu")(headModel1)
headModel1 = Dropout(0.5)(headModel)
headModel1 = Dense(2, activation="softmax")(headModel1)
merge_one=concatenate([headModel,headModel1])

# place the head FC model on top of the base model (this will become
# the actual model we will train)
model = Model(inputs=[baseModel.input,baseModel1.input], outputs=merge_one)

# loop over all layers in the base model and freeze them so they will
# *not* be updated during the first training process
for layer in baseModel.layers:
	layer.trainable = False
for layer in baseModel1.layers:
        layer.trainable=False

# compile our model
print("[INFO] compiling model...")
opt = Adam(learning_rate=INIT_LR, decay=INIT_LR / EPOCHS)
model.compile(loss="binary_crossentropy", optimizer=opt,
	metrics=["accuracy"])

# train the head of the network
print("[INFO] training head...")
H = model.fit(
	aug.flow(x=[trainX,trainX1],y=trainY, batch_size=BS),
	steps_per_epoch=len([trainX,trainX1]) // BS,
	validation_data=([testX,testX1],[testY,testY1]),
	validation_steps=len([testX,testX1]) // BS,
	epochs=EPOCHS)

# make predictions on the testing set
print("[INFO] evaluating network...")
predIdxs = model.predict([testX,testX1], batch_size=BS)

# for each image in the testing set we need to find the index of the
# label with corresponding largest predicted probability
predIdxs = np.argmax(predIdxs, axis=1)

# show a nicely formatted classification report
print(classification_report(testY.argmax(axis=1), predIdxs,
	target_names=lb.classes_))

# serialize the model to disk
print("[INFO] saving mask detector model...")
model.save(args["model"], save_format="h5")

# plot the training loss and accuracy
N = EPOCHS
plt.style.use("ggplot")
plt.figure()
plt.plot(np.arange(0, N), H.history["loss"], label="train_loss")
plt.plot(np.arange(0, N), H.history["val_loss"], label="val_loss")
plt.plot(np.arange(0, N), H.history["accuracy"], label="train_acc")
plt.plot(np.arange(0, N), H.history["val_accuracy"], label="val_acc")
plt.title("Training Loss and Accuracy")
plt.xlabel("Epoch #")
plt.ylabel("Loss/Accuracy")
plt.legend(loc="lower left")
plt.savefig(args["plot"])
```

**Comment by rmothukuru** [comment]
@pavanpotteti,
Can you please let us know what the problem, exactly, is? Also, if possible, either format the code properly or paste the code in Google Colab and Share the Colab Gist. Thanks!

**Comment by pavanpotteti** [comment]
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import MobileNetV2,Xception
from tensorflow.keras.layers import AveragePooling2D
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Input,Concatenate,concatenate
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
from tensorflow.keras.applications.xception import preprocess_input
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.preprocessing.image import load_img
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelBinarizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from imutils import paths
import matplotlib.pyplot as plt
import numpy as np
import argparse
import os

directory=r"C:/face-mask-detector/dataset"
cate=["with_mask","without_mask"]

INIT_LR = 1e-4
EPOCHS = 2
BS = 32

print("[INFO] loading images...")
data = []
labels = []

# loop over the image paths
for category in cate:
        path=os.path.join(directory,category)
        for img in os.listdir(path):
                img_path=os.path.join(path,img)
                image = load_img(img_path, target_size=(224, 224))
                image = img_to_array(image)
                image = preprocess_input(image)
                data.append(image)
                labels.append(category)

data = np.array(data, dtype="float32")
labels = np.array(labels)
# perform one-hot encoding on the labels
lb = LabelBinarizer()
labels = lb.fit_transform(labels)
labels = to_categorical(labels)


(trainX, testX, trainY, testY) = train_test_split(data, labels,
                                                  test_size=0.20, stratify=labels, random_state=42)

aug = ImageDataGenerator(rotation_range=20,zoom_range=0.15,width_shift_range=0.2,height_shift_range=0.2,shear_range=0.15,horizontal_flip=True,fill_mode="nearest")

baseModel = MobileNetV2(weights="imagenet", include_top=False,input_tensor=Input(shape=(224, 224, 3)))
baseModel1=Xception(weights="imagenet",include_top=False,input_tensor=Input(shape=(224,224,3)))

headModel = baseModel.output
headModel = AveragePooling2D(pool_size=(7, 7))(headModel)
headModel = Flatten(name="flatten")(headModel)
headModel = Dense(128, activation="relu")(headModel)
headModel = Dropout(0.5)(headModel)
headModel = Dense(2, activation="softmax")(headModel)
headModel1 = baseModel1.output
headModel1 = AveragePooling2D(pool_size=(7, 7))(headModel1)
headModel1 = Flatten(name="flatten")(headModel1)
headModel1 = Dense(128, activation="relu")(headModel1)
headModel1 = Dropout(0.5)(headModel)
headModel1 = Dense(2, activation="softmax")(headModel1)
merge_one=concatenate([headModel,headModel1])

model = Model(inputs=[baseModel.input,baseModel1.input], outputs=merge_one)

for layer in baseModel.layers:
    layer.trainable = False
for layer in baseModel1.layers:
    layer.trainable=False

print("[INFO] compiling model...")
opt = Adam(learning_rate=INIT_LR, decay=INIT_LR / EPOCHS)
model.compile(loss="binary_crossentropy", optimizer=opt,metrics=["accuracy"])

test_imagen=ImageDataGenerator(rescale=1./255)

def generate_generator_multiple(generator,dir1, dir2, batch_size, img_height,img_width):
    genX1 = generator.flow_from_directory(dir1,
                                          target_size = (224,224),
                                          class_mode = 'categorical',
                                          batch_size = batch_size,
                                          shuffle=False, 
                                          seed=7)
    genX2 = generator.flow_from_directory(dir2,
                                          target_size = (224,224),
                                          class_mode = 'categorical',
                                          batch_size = batch_size,
                                          shuffle=False, 
                                          seed=7)
    while True:
            X1i = genX1.next()
            X2i = genX2.next()
            yield [X1i[0], X2i[0]], X2i[1]  #Yield both images and their mutual label
            

inputgenerator=generate_generator_multiple(generator=input_imgen,
                                           dir1=directory,
                                           dir2=directory,
                                           batch_size=BS,
                                           img_height=224,
                                           img_width=224)    

testgenerator=generate_generator_multiple(test_imagen,
                                          dir1=directory,
                                          dir2=directory,
                                          batch_size=BS,
                                          img_height=224,
                                           img_width=224)
                                                

history=model.fit(inputgenerator,
                        steps_per_epoch=len(trainX)//BS,
                        epochs = EPOCHS,
                        validation_data = testgenerator,
                        validation_steps = len(testX)//BS,
                        use_multiprocessing=True,
                        shuffle=False)

**Comment by pavanpotteti** [comment]
this is the code i had tried ,but it is giving error like this

**Comment by pavanpotteti** [comment]
Exception in thread Thread-62:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Anaconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\keras\utils\data_utils.py", line 852, in _run
    with closing(self.executor_fn(_SHARED_SEQUENCES)) as executor:
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\keras\utils\data_utils.py", line 842, in pool_fn
    pool = get_pool_class(True)(
  File "C:\Anaconda3\lib\multiprocessing\context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "C:\Anaconda3\lib\multiprocessing\pool.py", line 212, in __init__
    self._repopulate_pool()
  File "C:\Anaconda3\lib\multiprocessing\pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "C:\Anaconda3\lib\multiprocessing\pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "C:\Anaconda3\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Anaconda3\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'generator' object

**Comment by jvishnuvardhan** [comment]
@pavanpotteti Too long code to support. Please note that this repository is mainly focussed on bug/performance related issues. [TF Forum](https://discuss.tensorflow.org/tag/help_request) is right place for support related questions as there are lot of users supporting each other. 

I think [this tutorial](https://www.tensorflow.org/tutorials/images/transfer_learning) from TF website could help you combiniing the two models you have. Thanks!

If you notice any bug/performance issue, then please post here. Please feel free to reopen if I am mistaken. Thanks!
