### ISSUE TITLE
ImageDataGenerator with mixed precision float16 - RuntimeError: data type not supported

### ISSUE THREAD

**Issue by klyack** [keras-team/keras#14699]
If **mixed precision** is activated on GPU (2080 RTX model compute 7.5)
Using **ImageDataGenerator** on CIFAR10 for transformations like **rotate** or **shift** are throwing an error - DataType not supported. Flips are working fine.

Steps to reproduce:
mixed_precision.set_global_policy(mixed_precision.Policy('mixed_float16'))
(X_train, y_train), (X_test, y_test) = cifar10.load_data()
X_train=X_train.astype('float16')
datagen = ImageDataGenerator(rescale=1.0/255.0, dtype='float16', height_shift_range=0.1)
datagen.fit(X_train)
model.fit(datagen.flow(X_train, y_train, batch_size=128), steps_per_epoch=int(X_train.shape[0] / 128), epochs=40)

....
c:\python38\lib\site-packages\keras_preprocessing\image\affine_transformations.py in <listcomp>(.0)
    325         final_offset = transform_matrix[:2, 2]
    326 
--> 327         channel_images = [ndimage.interpolation.affine_transform(
    328             x_channel,
    329             final_affine_matrix,

c:\python38\lib\site-packages\scipy\ndimage\interpolation.py in affine_transform(input, matrix, offset, output_shape, output, order, mode, cval, prefilter)
    606                              mode, cval, npad, False)
    607     else:
--> 608         _nd_image.geometric_transform(filtered, None, None, matrix, offset,
    609                                       output, order, mode, cval, npad, None,
    610                                       None)

RuntimeError: data type not supported

P.S. Changing to 'float32' doesn't eliminate the error
P.P.S. Without mixed precision same code works OK.

**Comment by klyack** [comment]
Hi.
I had to reinstall my system everything meanwhile and now I can't reproduce the problem.Please close the issue .
Sorry to waste your time.

    On Wednesday, August 4, 2021, 9:24:40 PM EDT, Vishnuvardhan Janapati ***@***.***> wrote:  
 
 


@klyack Can you please share a simple standalone code to reproduce the issue? I tried and created a gist.

Please update the gist with the model information and share it to reproduce the issue. thanks!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jvishnuvardhan** [comment]
@klyack Thanks! Closing this issue.
