### ISSUE TITLE
installing keras in macbook m1 

### ISSUE THREAD

**Issue by kanhaiyap** [keras-team/keras#14700]
I am not able to install Keras.
previously when I installed TensorFlow the ram used to crash but with python 3.4 the issue was resolved but now i am not able to install Keras. is there any fix for the issue!!
thank you!!

**Comment by irekzayniev** [comment]
possible to install following https://developer.apple.com/metal/tensorflow-plugin/
but crash in runtime

**Comment by ymodak** [comment]
You may also refer https://github.com/apple/tensorflow_macos/issues/101
