### ISSUE TITLE
 Wrapping Layers and Save

### ISSUE THREAD

**Issue by pierluigi-failla** [keras-team/keras#14769]
### System information

-   Custom code
-   Win 10
-   installed from binary
-   tensorflow-gpu==2.0.0
-   Python 3.7
-   GPU: 4095MB NVIDIA GeForce GTX 1050

### Describe the problem

I created a custom Keras `Layer` with the purpose of wrapping another `Layer` so that I can have some additional computation before and/or after it. Here is some pseudo code:

```
class Wrapper(Layer):

    def __init__(self, layer: Layer, **kwargs):
        super(Wrapper, self).__init__(**kwargs)
        self._layer = layer

    def build(self, input_shape):
        self._layer.build(input_shape)

        # i.e. following is just an example
        self._after_layer = Dense(10)

    def call(self, x, **kwargs):
        y = self._layer(x)
        y = self._after_layer(y)
        return y

    def compute_output_shape(self, input_shape):
        return self._after_layer.compute_output_shape(self._layer.compute_output_shape(input_shape))

    def get_config(self):
        config = super().get_config().copy()
        config.update({
            'layer': self._layer,
        })
        return config
```
now you can use the above wrapper the following way:
```
y = Wrapper(SomeOtherLayer(...))(x)
```
everything works like a charm, but having a `Layer` as input make impossible to save the model. Trying to save raise a "TypeError: Cannot convert ... to a TensorFlow DType" and it is triggered by the fact that I added `'layer': self._layer`, in the Layer config.

Is there any workaraound or best way to achieve the same as above and also save/load the model?

Same isssue has been submitted also [here](https://stackoverflow.com/questions/68030689/keras-wrapping-layers-and-save).

**Comment by pierluigi-failla** [comment]
My question has been answered on Stackoverflow.

**Comment by jvishnuvardhan** [comment]
@pierluigi-failla Since this is resolved with the answer in Stackoverflow, I am closing this issue. Please feel free to reopen if I am mistaken. Thanks!
