### ISSUE TITLE
CNN + LSTM ValueError: Input 0 of layer sequential_10 is incompatible with the layer: expected ndim=5, found ndim=4. Full shape received: (None, None, None, None)

### ISSUE THREAD

**Issue by ZulfikriMirza** [keras-team/keras#14836]
currently making  human action recognition to detect a cheating kind on exam from CCTV using AlexNet+LSTM

**My Data are raw image in a each class folder with like** [this][1] 

but i got error like this

ValueError: in user code:

    /usr/local/lib/python3.7/dist-packages/keras/engine/training.py:830 train_function  *
        return step_function(self, iterator)
    /usr/local/lib/python3.7/dist-packages/keras/engine/training.py:813 run_step  *
        outputs = model.train_step(data)
    /usr/local/lib/python3.7/dist-packages/keras/engine/training.py:770 train_step  *
        y_pred = self(x, training=True)
    /usr/local/lib/python3.7/dist-packages/keras/engine/base_layer.py:989 __call__  *
        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
    /usr/local/lib/python3.7/dist-packages/keras/engine/input_spec.py:212 assert_input_compatibility  *
        raise ValueError('Input ' + str(input_index) + ' of layer ' +

    ValueError: Input 0 of layer sequential_10 is incompatible with the layer: expected ndim=5, found ndim=4. Full shape received: (None, None, None, None)

The error come when i do the model.fit

from what i read it said that the problem at the input_shape but i am still doesnt found the solution of my problem
the link of **my code at colab can be found** [here][2], 

i still dont understand what is the problem, i check the documentation for input_shape in TimeDistributed and it's the same for (timeSteps, height, width, channels)

i did try to remaking the model but the problem are still the same

is it from my ImageDataGenerator?

i would appreciate if anybody have the experience in this matter and try to help my problem

Thank you so much !

  [1]: https://drive.google.com/drive/folders/1HpBLwcDe8Ifbfhe3yNGtPQkai-XsJ6xT?usp=sharing
  [2]: https://colab.research.google.com/drive/1D7grs6_WHxDYCo8UEwETKqp3V_10U51J?usp=sharing

**Comment by rmothukuru** [comment]
@ZulfikriMirza,
Can you try adding **`input_shape=(227, 227, 3)`** in the **`Conv2D Layer`** instead of **`TimeDistributed Layer`** and see if the issue persists? Thanks!

**Comment by rmothukuru** [comment]
Closing as stale. Please reopen if you'd like to work on this further.
