### ISSUE TITLE
 Failed to convert a NumPy array to a Tensor (Unsupported object type float).

### ISSUE THREAD

**Issue by sagniksanyal-99** [keras-team/keras#14851]
[Uploading station_day.xlsx…]()
[[x=df.iloc[:, 1:13] = df.groupby("Date").transform(lambda x: x.fillna(x.mean()))
x
y=df.iloc[:, 1:13]=df.fillna(df.mean())
y

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.1, random_state = 0)
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
x_train = np.asarray(x_train).astype(np.float32)

model=Sequential()
model.add(Dense(100,activation='relu'))
model.add(Dense(1,activation='softmax'))
loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False,name='sparse_categorical_crossentropy')
model.compile(optimizer='adam',metrics=['accuracy'],loss=loss)
model.fit(x_train, y_train, batch_size=32, epochs=10)
ValueError                                Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/constant_op.py in convert_to_eager_tensor(value, ctx, dtype)
     96       dtype = dtypes.as_dtype(dtype).as_datatype_enum
     97   ctx.ensure_initialized()
---> 98   return ops.EagerTensor(value, ctx.device_name, dtype)
     99 
    100 

ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float).]()

]([url](url))

**Comment by namaannn** [comment]
@sagniksanyal-99 I can solve this issue, kindly assign me this issue

**Comment by namaannn** [comment]
@sagniksanyal-99 can you provide the entire code with dataset so that i can make changes in the code

**Comment by meenaljain0303** [comment]
I would also like to work on this issue, pls assign me

**Comment by ymodak** [comment]
Closing this issue due lack of activity. Please update the thread when new information is available. Thanks!
