### ISSUE TITLE
[Contributions welcome] Implement a `DepthwiseConv1D` layer

### ISSUE THREAD

**Issue by fchollet** [keras-team/keras#14853]
Keras features a `DepthwiseConv2D` layer, but not yet `DepthwiseConv1D`. It is already implementable with existing TF ops. If you're interested in adding this feature, please open a PR.

**Comment by namaannn** [comment]
I can implement Depthwise Conv 1D using other libraries. Kindly assign me this issue @fchollet

**Comment by fsx950223** [comment]
I'm also interested in it.
