### ISSUE TITLE
Recover callback state when training is interrupted

### ISSUE THREAD

**Issue by dennymarcels** [keras-team/keras#14862]
**System information**.

TensorFlow version (you are using): 2
Are you willing to contribute it (Yes/No) : No (I wouldn't know how)

**Describe the feature and the current behavior/state**.
I was wondering if it would be possible to checkpoint and recover callback states, so that my callbacks can continue from their latest state after training is interrupted for some reason.

Example (presented as a tale): 

Suppose I am training a model for 100 epochs and checkpointing after each epoch. I am also using an EarlyStopping callback with patience = 10. Suppose also that my performance will peak at epoch 70, therefore my training is doomed to stop after epoch 80.

That if everything goes well. But the Gods are angry today and they decide my kernel will crash at epoch 79.

Well, after I sacrifice some rodents and burn their blood in the altar to calm the Universe, I restart my kernel and reload my weights from the latest finished epoch, aka 78. That part is a no brainer. But my (reinstantiated) EarlyStopping callback now lost track of its patience! It will restart from 0 and my training will have to go until epoch 88 now. Not nice.

Things will be even worse if I set some callback that changes training parameters, such as ReduceLROnPlateau. Now the scheduling is all messed up.

What else should I sacrifice to have my request considered?

**Will this change the current api? How?**
I guess it will, as the callback states should be saved/reloaded somehow.

**Who will benefit from this feature?**
Me :D and all those pundits out there who annoy the Gods.

**Comment by haifeng-jin** [comment]
@dennymarcels I think this is a good solution. https://github.com/tensorflow/tensorflow/issues/50516#issuecomment-873313024
You can subclass the `Callback` class in your code.

**Comment by haifeng-jin** [comment]
I believe the current best solution is to have a new callback function just to save the state of the rest of the callbacks by pickling them every epoch or every batch.

**Comment by dennymarcels** [comment]
@haifeng-jin that does not work, I get the error:
`TypeError: can't pickle tensorflow.python._pywrap_tf_session.TF_Operation objects`

This functionality would be very much appreciated as I am training models that extend beyond the Google Colab Pro time limit.

**Comment by dennymarcels** [comment]
> I believe the current best solution is to have a new callback function just to save the state of the rest of the callbacks by pickling them every epoch or every batch.
@haifeng-jin that does not work, I get the error:
TypeError: can't pickle tensorflow.python._pywrap_tf_session.TF_Operation objects

This functionality would be very much appreciated as I am training models that extend beyond the Google Colab Pro time limit.

**Comment by haifeng-jin** [comment]
What is the callback function you are trying to pickle?
There might be something special that cannot be pickled.
You may need to find a way to serialize it.

**Comment by dennymarcels** [comment]
EarlyStopping, ReduceLROnPlateau and ModelCheckpoint. Only I put all three instances inside a list then tried to pickle the list.

**Comment by dennymarcels** [comment]
I would insist that this issue is reopen and maybe changed into a feature request, I am really missing the possibility of saving callback states.

**Comment by haifeng-jin** [comment]
Hi @k-w-w 
What is a common practice for saving the state of the callbacks, please?
