### ISSUE TITLE
sample_weight taking long to initialize

### ISSUE THREAD

**Issue by Wenuka** [keras-team/keras#14877]
sample_weight in Keras model fit take a long time to initialize when compared to the same model trained on same data without the sample_weight.

It seems like I am not the only one having the issue
https://stackoverflow.com/questions/63158424/why-does-keras-model-fit-with-sample-weight-have-long-initialization-time

This is my first bug issue, so bear with me if the format is not correct.

**Comment by haifeng-jin** [comment]
```py
import tensorflow as tf
from tensorflow import keras
import numpy as np

x_train = np.random.rand(10000, 10)
y_train = np.random.rand(10000, 1)
w_train = np.random.rand(10000, 1)

def run(with_sample_weights=True):
  model = keras.Sequential()
  model.add(keras.layers.Dense(64, input_dim=x_train.shape[1], activation='relu')) 
  model.add(keras.layers.Dropout(0.1))
  model.add(keras.layers.Dense(64, activation='relu'))
  model.add(keras.layers.Dropout(0.1))
  model.add(keras.layers.Dense(64, activation='relu'))
  model.add(keras.layers.Dropout(0.1))
  model.add(keras.layers.Dense(64, activation='relu'))
  model.add(keras.layers.Dropout(0.1))
  model.add(keras.layers.Dense(1, activation='sigmoid'))
  model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

  if with_sample_weights:
    model.fit(x_train, y_train, sample_weight=w_train)
  else:
    model.fit(x_train, y_train)

import time

start = time.time()
for i in range(10):
  run(True)
end = time.time()
print(end - start)

start = time.time()
for i in range(10):
  run(False)
end = time.time()
print(end - start)
```
The time elapsed is 31s vs 14s.
It seems the cause is strided_slice() function.

**Comment by Wenuka** [comment]
Yes, exactly. The problem gets worse when the sample size is higher.

For example, using the above code (plus a batch size of 10,000), for a sample size of 1,000,000 the time taken was 1253.8s vs 17.1s 
i.e 73 times more time to train the model!
For comparison, for the 10,000 case as above, the time was 18.2s vs 5.1s

**Comment by sansarsecondary** [comment]
This bug is preventing usage of sample weights for high instance count data as initialization time explode. Can this please be looked at.

**Comment by Daddycool9999** [comment]
Facing same problem.

Training set size (sample size) : Around 150 million
Initialization time : Around 5-6 hrs
Training time (After initialization) : Around 2 hrs

**Comment by haifeng-jin** [comment]
Note: The first step is to inspect if the `sample_weight` is included in a `DataLoader`. If not, it means they are executed eagerly, which would be slow.

**Comment by timsharpzim** [comment]
If it helps anyone - I have found that in tensor flow 2.9.1 and the keras within, making sample_weight a pd.Series() no longer stops the slow initialisation. But making sample_weight a DataFrame does, and the model starts training almost instantly.
For avoidance of doubt, this is how I do it to avoid extremely slow initialisation:
model.fit(....., sample_weight=pd.Series(wts).to_frame('wt'))

**Comment by tilakrayal** [comment]
@Wenuka,
**Sample_weights** is used to provide a weight for each training sample. That means that you should pass a 1D array with the same number of elements as your training samples (indicating the weight for each of those samples). In case you are using temporal data you may instead pass a 2D array, enabling you to give weight to each timestep of each sample.

Also please try as mentioned below and also check whether sample_weights are eagerly executed which might be causing long to intialise. 

`model.fit( sample_weight=pd.Series(weights).to_frame('weight'))`  Thank you!

**Comment by jlpeper** [comment]
> 

This suggestion worked for me. For reference my training data sample size is 7.9 M. 
I am not sure if its necessary but I also passed the validation weights as a DataFrame....
`history = model.fit(
            df_to_series(x_train),
            y_train,
            sample_weight=sd_train.to_frame(),
            epochs=3,
            batch_size=512,
            validation_data = (df_to_series(x_val), np.array(y_val), sd_val.to_frame()),
            callbacks=[es_callback, mc_callback, lr_scheduler_rampdown],
            verbose=2,
        )`

> If it helps anyone - I have found that in tensor flow 2.9.1 and the keras within, making sample_weight a pd.Series() no longer stops the slow initialisation. But making sample_weight a DataFrame does, and the model starts training almost instantly. For avoidance of doubt, this is how I do it to avoid extremely slow initialisation: model.fit(....., sample_weight=pd.Series(wts).to_frame('wt'))
