### ISSUE TITLE
How to make low level tensor operations in custom layers?

### ISSUE THREAD

**Issue by Oezkan23** [keras-team/keras#14871]
System: Python 3.8.3 64-bit | Qt 5.12.9 | PyQt5 5.12.3 | Linux 5.8.0-55-generic
tensorflow version: 2021-07-05 20:04:06.422679
keras version: 2021-07-05 20:04:06.422679

I try to make a custom layer which has an input  tensor of a shape (None,2,2,3) and I wanted to have an output tensor with a shape (None,1,1,3) i.e output tensor and input tensor should have different shapes. Inside the custom layer the output tensor should also have one scalar element from an input tensor. I have not much knowledge about tensorflow and keras to do this, because I find in internet only custom layers with "dense"-operations, which are worthless for me. 

**Code Example which do not produce errors but does not work correctly as expected:**

```
from keras.layers import Layer
import numpy as np
import tensorflow as tf
from keras.layers import Input
from keras.models import Model 

InputTensor = np.array([[[[255,0,0],[255,0,0]],[[255,0,0],[0,144,0]]],
                        [[[100,100,0],[100,100,0]],[[100,100,0],[144,0,0]]]])

class MyLayer(Layer):
    def __init__(self, **kwargs):
        super(MyLayer, self).__init__(**kwargs)
    def build(self, input_shape):
        self.built = True
        super(MyLayer,self).build(input_shape)

    def call(self, X):
        Y = tf.zeros([1,1,1,3])
#       Y[None,0,0,0] = X[None,0,0,0].  # <--- Something like that is what I wanted to do.!!!
#                                              Just a simple assignment of tensor elements
        Y= tf.compat.v1.placeholder_with_default(Y,(None,1,1,3))
        return Y  
    
inputlayer = Input(shape = InputTensor[0].shape)
layer = MyLayer()(inputlayer)

model = Model(inputlayer, layer ) #Model wird erzeugt
model.summary()

Output = model.predict(InputTensor)
Output = np.array(Output)
print("Output = "+str(Output))
```
The output is:
```
odel: "model_22"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_43 (InputLayer)        [(None, 2, 2, 3)]         0         
_________________________________________________________________
my_layer_42 (MyLayer)        (None, 1, 1, 3)           0         
=================================================================
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
Output = [[[[0. 0. 0.]]]]
```
Output shoul'd be [[[[0.0.0.0]]][[[0.0.0.0]]]]
I whish an output where I have the first element of input tensor in the output tensor
like
```
Output = [[[[255. 0. 0]]][[[100. 0. 0.]]]]
```
if l know how to realisize low level assignments to type Tensor.

What shall I do that the output-tensor on Output has the dimension like the InputTensor  and how to assign tensor tensor elements in a custom layer?
There must be a way for low level tensor operations otherwise building custom layers make no sense if you use only backends and tensorflow tensor operations.

**Comment by haifeng-jin** [comment]
Hi @Oezkan23, thanks for the issue.
The tensorflow operations should be quite comprehensive.
Would tensorflow operations like `tf.slice` do it?

**Comment by Oezkan23** [comment]
Hello haifeng-jin, thanks for the hint of ```tf.slice``` . I got the result what I want, in defining the call-function in MyLayer as
```
def call(self,X):
Y = tf.slice(X, begin=[0,0,0,0],size=[2,1,1,3])
Y = tf.compat.v1.placeholder_with_default(Y,(None,1,1,3))
return Y
```
But it has a beauty mistake. For the expression ```size=[2,1,1,3]``` I need the first element which is the size of ```ImputTensor.shape[0]```. It is possible to put it as an argument or parameter to MyLayer() as ```layer =MyLayer(InputTensor.shape[0]) (inputlayer)``` which I don't want. The function ```Input``` expect a shape which has 3 dimensions and add a 4th dimension as None. In ```model.predict``` the argument has a Tensor of dimension = 4 with the shape = (2,2,2,3). 

It is not possible to define the call-function in the custom layer as
```
def call(self,X):
Y = tf.slice(X, begin=[0,0,0,0],size=[X.shape[0],1,1,3])
Y = tf.compat.v1.placeholder_with_default(Y,(None,1,1,3))
return Y
```

because ```X.shape[0]``` is None. Now I need only this information of that size.

Another problem is to produce output tensors, which have no elements of the input tensor but share some shapes.
