### ISSUE TITLE
How get the shape[0] of the input tensor of a custom layer?

### ISSUE THREAD

**Issue by Oezkan23** [keras-team/keras#14889]
In a custom layer we may have a call function with an input tensor X. The following example shows an unclean solution to get InputTensor.shape[0] and works very well as expected.
```
from keras.layers import Layer
import numpy as np
import tensorflow as tf
from keras.layers import Input
from keras.models import Model 

InputTensor = np.array([[[[255,0,0],[255,0,0]],[[255,0,0],[0,144,0]]],
                        [[[0,255,0],[0,255,0]],[[0,255,0],[144,0,0]]]])

class MyLayer(Layer):
    def __init__(self,indexmax, **kwargs):
        self.indexmax = indexmax
        super(MyLayer,self).__init__(**kwargs)
        
    def build(self, input_shape):
        self.built = True
        super(MyLayer,self).build(input_shape)

    def call(self, X):
        y= np.array([[[[0,0,0]]],[[[0,0,0]]]])
        w = self.indexmax
        if X[0,0,0,0] == 255:
            y[0,0,0,0] = 10
        if X[w-1,0,0,1] == 255:
            y[w-1,0,0,1] = 20
        Y =tf.constant(y)
        Y= tf.compat.v1.placeholder_with_default(Y,(None,1,1,3))
        return Y
    
indexmax = InputTensor.shape[0]
inputlayer = Input(shape = InputTensor[0].shape)
layer = MyLayer(indexmax)(inputlayer)

model = Model(inputlayer, layer ) 
model.summary()

Output = model.predict(InputTensor)
Output = np.array(Output)
print("Output = "+str(Output))
```

What I want is a custom Layer with one argument like
``` layer = MyLayer() (inputlayer)```
instead of
``` layer = MyLayer(indexmax)(inputlayer) ```
where 
```indexmax = InputTensor.shape[0]```

I wish a function to get X.shape[0] which is not None.

**Comment by haifeng-jin** [comment]
Thanks for the clarification. To my understanding this is the same as #14871 .

**Comment by haifeng-jin** [comment]
You can use `tf.shape(X)` to get the shape of X.

**Comment by Oezkan23** [comment]
Hello haifeng-jin,
tf.shape(Tensor) works outside custom layers very well, because  tensorflow tensor has a numpy-element. With tf.shape(Tensor)[0].numpy() you get the first entry of the shape. You can also use Tensor.shape[0] instead.  But inside of custom layers, tensorflow Tensors are different and don't know the method numpy() and Tensor.shape[0] delivers the value None!
