### ISSUE TITLE
ValueError: You are trying to load a weight file containing 233 layers into a model with 231 layers.

### ISSUE THREAD

**Issue by Nidhi397** [keras-team/keras#14895]
I am trying to train a custom dataset with Mask RCNN. 
Doing this on TF2 by using the mrcnn folder kindly open sourced by the owner of this repository: https://github.com/ahmedfgad/Mask-RCNN-TF2

But after the above change and also resolving a good number of bugs, I am getting this error:

```
Loading weights  /content/drive/My Drive/Mask_RCNN/mask_rcnn_coco.h5
Traceback (most recent call last):
  File "pothole.py", line 361, in <module>
    "mrcnn_bbox", "mrcnn_mask"])
  File "/content/drive/My Drive/Mask_RCNN/mrcnn/model.py", line 2132, in load_weights
    hdf5_format.load_weights_from_hdf5_group(f, layers)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/saving/hdf5_format.py", line 686, in load_weights_from_hdf5_group
    ' layers.')
ValueError: You are trying to load a weight file containing 233 layers into a model with 231 layers.

```

Has anyone faced this error? Can anyone please guide me as to how can I solve this issue?

**Comment by jvishnuvardhan** [comment]
@Nidhi397 Can you please share a standalone code to reproduce the error? Thanks!

**Comment by jvishnuvardhan** [comment]
The following could be similar to your problem. [1](https://github.com/tensorflow/tensorflow/issues/43498), [2](https://github.com/keras-team/keras/issues/10417), [3](https://github.com/tensorflow/tensorflow/issues/34016), [4](https://stackoverflow.com/questions/51544666/keras-try-save-and-load-model-error-you-are-trying-to-load-a-weight-file-contain), [5](https://github.com/tensorflow/tensorflow/issues/34016), [6](https://github.com/tensorflow/tensorflow/issues/30892). 

Hope those link will help resolving your issue. If you still have an issue, please share a standalone code. Thanks!

I am closing this issue. Please feel free to reopen when you have more information to share. Thanks!

**Comment by Rqcker** [comment]
I am also having this problem. I'm thinking if it's a tf version issue
