### ISSUE TITLE
For Keras training, can we relax the steps checking when distributed dataset is passed in

### ISSUE THREAD

**Issue by annyan09023** [keras-team/keras#14907]
Recently, when we tried to use MultiWorkerMirroredStrategy with Keras, we found:

1. When Keras wrap our passed in dataset with experimental distributed dataset, we found we cannot scale over x nodes because it needs us pass in a global batch size and global batch size needs to take number of workers into consideration (global batch size = batch size * num of workers * num of replica). Therefore, when we have a lot of workers, compared with Mirrored strategy, we start seeing job failure due to OOM
2. We try to get around this issue by passing in distribute_datasets_from_function that we can have full control over per replica batch and sharding logic (and get around OOM issue). Then our job failed at:
https://github.com/keras-team/keras/blob/f4254fb496508778edb7edb92342b6fe1babefc5/keras/engine/data_adapter.py#L748

When we passed in normal dataset, it has UNKNOWN cardinality and leverage
https://github.com/keras-team/keras/blob/f4254fb496508778edb7edb92342b6fe1babefc5/keras/engine/data_adapter.py#L725

to recreate iterator for every epoch. Our use case is to have validation step to exhaust our dataset instead of hard coding steps. I wonder if we can relax check in L733 altogether with change to L714. Then we can support no steps input from users? If you agree, I can submit the PR to make the change.

Please let me know if any downside of doing so.

Thanks

**Comment by rchao** [comment]
Hello @annyan09023, thanks for opening the issue. Can you give the [DatasetCreator](https://www.tensorflow.org/api_docs/python/tf/keras/utils/experimental/DatasetCreator) API a try and see if it mitigates the OOM issue?

**Comment by annyan09023** [comment]
Okay, looking

**Comment by gowthamkpr** [comment]
@annyan09023 Did `DatasetCreator` help you in solving the issue? Thanks!
