### ISSUE TITLE
How to get shape[0] of the input tensor of a custom layer and also the tensor values

### ISSUE THREAD

**Issue by Oezkan23** [keras-team/keras#14919]
Handling Tensors of tf.Tensor outside a custom layer is not a problem.
For example:
```
InputTensor = np.array([[[[255,0,0],[255,0,0]],[[255,0,0],[0,144,0]]],
                        [[[0,255,0],[0,255,0]],[[0,255,0],[144,0,0]]],
                        [[[0,245,0],[0,245,0]],[[0,245,0],[144,0,0]]]])

X = tf.constant(InputTensor)
print(X[0,0,0,0].numpy()) #--->255
print(tf.shape(X)[0].numpy() #--->3
print(X.shape[0]) #--->3
print(X) #---->
<tf.Tensor: shape=(3, 2, 2, 3), dtype=int64, numpy=
array([[[[255,   0,   0],
         [255,   0,   0]],

        [[255,   0,   0],
         [  0, 144,   0]]],


       [[[  0, 255,   0],
         [  0, 255,   0]],

        [[  0, 255,   0],
         [144,   0,   0]]],


       [[[  0, 245,   0],
         [  0, 245,   0]],

        [[  0, 245,   0],
         [144,   0,   0]]]])>
```
You get all the values you need for calculating. But inside custom layers the input tensor has another type:
Something like
```
Tensor("model_10/Cast:0", shape = (None,2,2,3), dtype = float32)
```
There is no numpy(). tf.shape(X)[0].numpy() does not work or X.shape[0] to get the batch. The numpy() function is helpful to get the values of a tensor. The following example is inside of a custom layer. If I make a tensor with tf.constant, then I receive a tensor without the numpy() function.

The next example is a dirty example which works fine but you must handle it with attention:
```
from keras.layers import Layer
import numpy as np
import tensorflow as tf
from keras.layers import Input
from keras.models import Model 

InputTensor = np.array([[[[255,0,0],[255,0,0]],[[255,0,0],[0,144,0]]],
                        [[[0,255,0],[0,255,0]],[[0,255,0],[144,0,0]]],
                        [[[0,245,0],[0,245,0]],[[0,245,0],[144,0,0]]]])

class MyLayer(Layer):
    def __init__(self,indexmax, **kwargs):
        self.indexmax = indexmax
        super(MyLayer,self).__init__(**kwargs)
        
    def build(self, input_shape):
        self.built = True
        super(MyLayer,self).build(input_shape)

    def call(self, X):
        print(X)
        y = np.array([[[[0,0,0]]],[[[0,0,0]]],[[[0,0,0]]]])
        if X[0,0,0,0] == 255:
            y[0,0,0,0] = 10
        if X[1,0,0,1] == 255:
	  y[1,0,0,1] = 20
        if X[2,0,0,1] == 245:
	  y[2,0,0,1] = 30   #y[2,0,0,1] = x[2,0,0,1]-30 # <--- Does not work!
	
        Y =tf.constant(y)
        Y= tf.compat.v1.placeholder_with_default(Y,(None,1,1,3))
        return Y
    
indexmax = InputTensor.shape[0]
inputlayer = Input(shape = InputTensor[0].shape)
layer = MyLayer(indexmax)(inputlayer)

model = Model(inputlayer, layer ) #Model wird erzeugt
model.summary()

Output = model.predict(InputTensor)
Output = np.array(Output)
print("Output = "+str(Output))
```
But if I try to assign the value of X[2,0,0,1] to a variable or to another tensor, it does not work. I need the value of the input tensor X for calculating to build output-tensors for example with index maps. To slice the input tensor make the access very complicated and also do not work either. What I wish to avoid the parameter indexmax in the custom layer to transport the batch size into the custom layer, which has first the value None. This is also a very important value to know! If there is no possibility to get these values custom layers make no sense!

**Comment by sushreebarsa** [comment]
@Oezkan23 Could you please let us know if you have checked this [thread](https://stackoverflow.com/questions/72256978/how-to-modify-tensor-inside-custom-layer-tensorflow) and let us know if it helped to modify the custom layer inside? I tried to replicate the provided [code](https://colab.research.google.com/gist/sushreebarsa/a54f4da5ed0d8d2a8c6711d0cba5a78e/14919.ipynb) and faced a different outcome.
Thank you!
