### ISSUE TITLE
in Model class, weights created by add_weigh can't be save [tf2.4, tf2.5]

### ISSUE THREAD

**Issue by WZMIAOMIAO** [keras-team/keras#14938]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu18.04
- TensorFlow installed from (source or binary): pip install 
- TensorFlow version (use command below): 2.4/2.5
- Python version: 3.7/3.8
- Bazel version (if compiling from source):
- GPU model and memory:
- Exact command to reproduce:

**Describe the problem**.

I create a weighs using add_weight in Model class, and save weights using model.save_weights. Next I load weight from h5 file using model.load_weights, but weights can't be load correctly.

**Describe the current behavior**.

**Describe the expected behavior**.
weights loaded by model.load_weights must equal weights saved by model.save_weights.

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no): no
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**.

```python
import tensorflow as tf


class MyModel(tf.keras.Model):
    def __init__(self):
        super(MyModel, self).__init__()
        self.class_token = self.add_weight(shape=[2, 3],
                                           initializer=tf.keras.initializers.RandomNormal())

    def call(self, inputs, training=None, mask=None):
        pass


m1 = MyModel()
m1.build([None])
print(m1.weights[0])
m1.save_weights("./m1.h5")

m2 = MyModel()
m2.build([None])
m2.load_weights("./m1.h5")
print(m2.weights[0])
```

**Source code / logs**.
weights ```class_token``` is not same.
```
<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 0.03856413, -0.02837599, -0.00168087],
       [-0.09213904,  0.03863193,  0.10821296]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 0.00409992, -0.00622567,  0.01508162],
       [-0.03862688, -0.04728783, -0.03659575]], dtype=float32)>
```

**Comment by vulkomilev** [comment]
I will take a look

**Comment by vulkomilev** [comment]
Try to build/train/evaluate your model. You  will discover that there is more that needs to be done in order for the weights to be saved

**Comment by WZMIAOMIAO** [comment]
thank you!
