### ISSUE TITLE
Identity Mappings in ResNet/ ResnetV2

### ISSUE THREAD

**Issue by ririya** [keras-team/keras#14953]
Hi everybody,

I’d like to discuss the correctness of the ResNet and ResNetV2 implementations, recently
I noticed a few flaws in the Keras applications implementation, starting with the weights initialization where all layers are initialized with Glorot instead of He. Now I want to discuss the identity mappings, it seems like they make a huge difference, according to the ResnetV2 paper.

The way ResNetV1 is implemented, the skip connections are not Identity at all, there are BN and activations in the way, which defeats the idea in which ResNets were designed.

ResNetV2 tries to correct those issues, but I still see some MaxPooling layers in the skip connections.

I have compared my results training a binary classifier with ResNetV1, ResNetV2 and a modified ResNetV1 with all identity mappings. The modified ResNetV1 is providing me the best results. My dataset contains images with a high number of channels, which impedes the usage of Imagenet weights.

See results [here ](https://github.com/ririya/ResNet_test/blob/main/networks_precision_recall.png)(scroll image to the right to see it all)

**Comment by seermer** [comment]
I think the original ResNetV2 paper did not discuss how they perform shortcut downsample in the paper, and they don't have an official implementation (I believe). 
All they said is it is best to have nothing on identity mapping when there is **no downsample**, which is correctly done in Keras. It is impossible to have nothing on identity mapping when the residual is downsampled, Keras chooses maxpool or conv1x1, which is not the best, but still correct considering the original paper did not say what they did.

**Comment by ririya** [comment]
I guess you are right, I'm wondering why ResNet V2 has some extra
dowsampling within the same stage (e.g. conv2_block2 -> conv2_block3,
conv3_block3 -> conv3_block4) compared to the original ResNet.

Em sex., 6 de ago. de 2021 às 10:45, Zhantao Yang ***@***.***>
escreveu:

**Comment by seermer** [comment]
@ririya this is again because there is no implementation detail on downsample/channel increment in the original paper,
Keras chooses to increase channel on the first block of each stage, and downsample on the last block of each stage (except stage conv2 has no downsample block, which is given in the original paper), if you look into the summary, you will notice that each stage has two non-identity shortcuts, one with conv on the way (for increase channel), another with maxpool (for downsample)

**Comment by qlzh727** [comment]
Thanks @seermer for replying this question. @ririya, if you still feel there is any actionable item for this bug, please either send a PR or a snippet of fix, and we can have a further discussion.

**Comment by ririya** [comment]
Fair enough. Let's not say Keras implementation is wrong, but couldn't it
be better? Seems to me that adding non identity blocks is not a good idea,
and if we have the choice not to do it, why would we do it? However
maxpooling is not as bad as a convolution layer, since it's closer to
identity.


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Em qui., 12 de ago. de 2021 às 09:49, Zhantao Yang ***@***.***>
escreveu:

**Comment by jvishnuvardhan** [comment]
@ririya As mentioned by @qlzh727 , Are you going to send any PR for a fix? Thanks!

**Comment by ririya** [comment]
> @ririya As mentioned by @qlzh727 , Are you going to send any PR for a fix? Thanks!

I will revisit this when I have some time. Just for the record, I ended up using this implementation https://github.com/raghakot/keras-resnet. This implementation is a mix of V1 and V2, but I believe the identity mappings work better.

I think adding some parts of it to the Keras implementation would create a better architecture.
