### ISSUE TITLE
cropping layer additional error message

### ISSUE THREAD

**Issue by arubiales** [keras-team/keras#14958]
This is the issue in Tensorflow https://github.com/tensorflow/tensorflow/issues/50612

And this is my PR https://github.com/tensorflow/tensorflow/pull/50844  

Now the issues of keras are done here. If it's necessary I can duplicate the issue here.

**Comment by rmothukuru** [comment]
@arubiales,
Thank you for raising a PR. Request you to replicate the PR in [Keras-Team/Keras Repo](https://github.com/keras-team/keras/pulls) (you can close the one in [TF Repo](https://github.com/tensorflow/tensorflow/pull/50844)) so that **Keras Engineers** can take a look. Thanks!

**Comment by ymodak** [comment]
Closing this issue since the associated PR has been merged. Thanks!
