### ISSUE TITLE
Allow keras constraints that affect both the kernel and the bias at the same time.

### ISSUE THREAD

**Issue by moralapablo** [keras-team/keras#14954]
**System information**.

TensorFlow version (you are using): R interface to Keras v2.4.0
Are you willing to contribute it (Yes/No) : No

**Describe the feature and the current behavior/state**.

With the current implementation of keras layers, weight constraints can be applied as kernel or bias constraints. This also means that when writing a custom constraint, it has an input parameter `w` that refers either to the kernel weights or the bias weights depeding on how it is used.

However, at least for research purposes, it would be useful to be able to include both the kernel and the bias together as input to a constraint. As an example, suppose that in a dense layer you want to constrain the L1 norm of the incident wegiths to a given neuron unit to be less than 1, but considering the bias at that unit as an extra element of the weight vector, ending up with a weight vector of length (input dimension + 1). Currently this simple constraint is not possible (as far as I know) because the input to a custom constraint is either bias or kernel weights, not both.

In this sense, even if the `kernel_constraint` and `bias_constraint` division is maintained, being able to use both kernel and bias weights as input to a custom constraint  would allow to use it with the two options `kernel_constraint` and `bias_constraint` and obtain the desired effect.

**Will this change the current api? How?**

Probably would be sufficient to add an extra option when creating custom constraints and how the constraints receive their inputs in the training process.

**Who will benefit from this feature?**

Anyone wanting to constraint the kernel and bias at the same time, for example computing the norm of the full weight vector incident to a neuron in a dense layer, including the bias.

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**

- Do you want to contribute a PR? (yes/no): no
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing):

**Comment by moralapablo** [comment]
Is there any idea on how this change in the constraints behaviour could be approached?

**Comment by sushreebarsa** [comment]
@moralapablo Did you try to combine the weight and bias into a single tensor with a constraint. After that you may split apart the tensor in the layers call method. Please refer to this [doc](https://www.tensorflow.org/api_docs/python/tf/keras/constraints/Constraint) and let us know if it helps?
Thank you!
