### ISSUE TITLE
Add "Copy Code Sample" Option in Keras Documentation, similar to that in TF.Org

### ISSUE THREAD

**Issue by worldpeaceaspirer** [keras-team/keras#14969]
**URL(s) with the issue:**.

Please provide a link to the documentation entry, for example: https://keras.io/guides/customizing_what_happens_in_fit/

**Description of issue (what needs to be changed):**.
We can add the symbol to "Copy Code Sample" (_2 Rectangles on the Top Right_) in Keras Documentation similar to that in [Tensorflow Site](https://www.tensorflow.org/tutorials/keras/classification), shown below:

![image](https://user-images.githubusercontent.com/77092296/126316901-17cf76ee-d3dc-4e12-aeba-52fcaa633153.png)

**Comment by sushreebarsa** [comment]
@worldpeaceaspirer  Sorry for the late response!
You may view the code using '`View in Colab`'  and copy the specific cell from there .Please let us know if it helps?
Thanks!
