### ISSUE TITLE
Adding "Run In Colab" Option for Keras Documentation similar to that in TF.Org

### ISSUE THREAD

**Issue by worldpeaceaspirer** [keras-team/keras#14966]
**URL(s) with the issue:**.

Please provide a link to the documentation entry, for example: https://keras.io/guides/customizing_what_happens_in_fit/

**Description of issue (what needs to be changed):**.
The Tutorials and Guide of Keras Documentation can have a button named "Run in Colab", like we have it in the [Tutorials in the Tensorflow Site](https://www.tensorflow.org/tutorials/keras/classification).

**Comment by yashk2810** [comment]
There is a button at the top of each notebook called `View in Colab`.
