### ISSUE TITLE
Model trains successfully but generating predictions gives ValueError: Graph disconnected: cannot obtain value for tensor KerasTensor

### ISSUE THREAD

**Issue by uttamdhakal** [keras-team/keras#14960]
I asked this question in [stackoverflow](https://stackoverflow.com/questions/68444781/keras-model-trains-successfully-but-generating-predictions-gives-valueerror-gr)  already. I am copying the same question here in the hope of finding an answer.

I created a Seq2Seq model for text summarization. I have two models, one with attention and one without. The one without attention was able to generate predictions but I can't do it for the one with attention even though it fits successfully.

This is my model:

    latent_dim = 300
    embedding_dim = 200
    
    clear_session()
    
    # Encoder
    encoder_inputs = Input(shape=(max_text_len, ))
    
    # Embedding layer
    enc_emb = Embedding(x_voc, embedding_dim,
                        trainable=True)(encoder_inputs)
    
    # Encoder LSTM 1
    encoder_lstm1 = Bidirectional(LSTM(latent_dim, return_sequences=True,
                         return_state=True, dropout=0.4,
                         recurrent_dropout=0.4))
    (encoder_output1, forward_h1, forward_c1, backward_h1, backward_c1) = encoder_lstm1(enc_emb)
    
    # Encoder LSTM 2
    encoder_lstm2 = Bidirectional(LSTM(latent_dim, return_sequences=True,
                         return_state=True, dropout=0.4,
                         recurrent_dropout=0.4))
    (encoder_output2, forward_h2, forward_c2, backward_h2, backward_c2) = encoder_lstm2(encoder_output1)
    
    # Encoder LSTM 3
    encoder_lstm3 = Bidirectional(LSTM(latent_dim, return_state=True,
                         return_sequences=True, dropout=0.4,
                         recurrent_dropout=0.4))
    (encoder_outputs, forward_h, forward_c, backward_h, backward_c) = encoder_lstm3(encoder_output2)
    
    state_h = Concatenate()([forward_h, backward_h])
    state_c = Concatenate()([forward_c, backward_c])
    
    # Set up the decoder, using encoder_states as the initial state
    decoder_inputs = Input(shape=(None, ))
    
    # Embedding layer
    dec_emb_layer = Embedding(y_voc, embedding_dim, trainable=True)
    dec_emb = dec_emb_layer(decoder_inputs)
    
    
    # Decoder LSTM
    decoder_lstm = LSTM(latent_dim*2, return_sequences=True,
                        return_state=True, dropout=0.4,
                        recurrent_dropout=0.2)
    (decoder_outputs, decoder_fwd_state, decoder_back_state) = \
        decoder_lstm(dec_emb, initial_state=[state_h, state_c])
    
    #start Attention part
    attention = dot([decoder_outputs, encoder_outputs], axes=[2, 2])
    attention = Activation('softmax')(attention)
    context = dot([attention, encoder_outputs], axes=[2,1])
    decoder_outputs = Concatenate()([context, decoder_outputs])
    #end Attention

    # Dense layer
    decoder_dense = TimeDistributed(Dense(y_voc, activation='softmax'))(decoder_outputs)
    
    # Define the model
    model = Model([encoder_inputs, decoder_inputs], decoder_dense)

This is how construct the encoder and decoder for generating predictions:
    
    model = load_model("model_intro.h5")

    encoder_inputs = model.input[0]  # input_1
    
    encoder_outputs, forward_h, forward_c, backward_h, backward_c = model.layers[5].output #Bi-lstm2
    
    state_h_enc = Concatenate()([forward_h, backward_h])
    state_c_enc = Concatenate()([forward_c, backward_c])
    
    encoder_states = [state_h_enc, state_c_enc]
    encoder_model = Model(encoder_inputs, encoder_states)
    
    decoder_inputs = model.input[1]  # input_2
    decoder_state_input_h = Input(shape=(latent_dim*2,), name="input_3")
    decoder_state_input_c = Input(shape=(latent_dim*2,), name="input_4")
    decoder_states_inputs = [decoder_state_input_h, decoder_state_input_c]
    decoder_emdedding = model.layers[6](decoder_inputs)
    decoder_lstm = model.layers[9]
    decoder_outputs, state_h_dec, state_c_dec = decoder_lstm(decoder_emdedding, initial_state=decoder_states_inputs)
    decoder_states = [state_h_dec, state_c_dec]
    
    #start Attention
    attention = dot([decoder_outputs, encoder_outputs], axes=[2, 2])
    attention2 = Activation('softmax')(attention)
    context = dot([attention2, encoder_outputs], axes=[2,1])
    decoder_outputs = Concatenate(axis=-1)([context, decoder_outputs])
    #end Attention

    decoder_dense = model.layers[-1]
    decoder_outputs = decoder_dense(decoder_outputs)
    decoder_model = Model(
        [decoder_inputs] + decoder_states_inputs, [decoder_outputs] + decoder_states
    )

In the code if I remove the attention part, it works fine. In the code I have added the comment for the start and the end of attention. The model with attention also fits successfully, however, while constructing the encoder and decoder for generating predictions, I get:

    ValueError: Graph disconnected: cannot obtain value for tensor KerasTensor(type_spec=TensorSpec(shape=(None, 300), dtype=tf.float32, name='input_1'), name='input_1', description="created by layer 'input_1'") at layer "embedding". The following previous layers were accessed without issue: []

This is how my model looks like:
[![model][1]][1]

  [1]: https://i.stack.imgur.com/0PB9P.png

**Comment by uttamdhakal** [comment]
I changed my attention layer to the one from Keras. But I still get the same error.

attention = Attention(causal = True)([decoder_outputs,encoder_outputs ])

```
# Dense layer
decoder_dense = TimeDistributed(Dense(y_voc, activation='softmax'))
decoder_outputs = decoder_dense(attention)

# Define the model
model = Model([encoder_inputs, decoder_inputs], decoder_outputs)
```

And this is now  in the inference model:

```
attention = model.layers[-2]([decoder_outputs,encoder_outputs ])

decoder_dense = model.layers[-1]
decoder_outputs = decoder_dense(attention)
decoder_model = Model(
    [decoder_inputs] + decoder_states_inputs, [decoder_outputs] + decoder_states
)
```

Please help. I have no idea what is going on. From what I see the graph is connected

**Comment by uttamdhakal** [comment]
I also created [a new question](https://stackoverflow.com/questions/68590104/graph-disconnected-cannot-obtain-value-for-tensor-kerastensor-in-inference-mode) in SO

**Comment by tilakrayal** [comment]
Can you please take a look at this link [1](https://github.com/keras-team/keras/issues/11151), [2](https://stackoverflow.com/questions/54151671/graph-disconnected-cannot-obtain-value-for-tensor-tensor), [3](https://stackoverflow.com/questions/65742643/keras-graph-disconnected-cannot-obtain-value-for-tensor-kerastensor) with the similar error.Thanks!
