### ISSUE TITLE
 Really Fix keras nightly PIP package build. 

### ISSUE THREAD

**Issue by eli-osherovich** [keras-team/keras#14973]
**Describe the problem**.
Recent [commit](https://github.com/keras-team/keras/commit/cffc048a59fb2619c13cb0f4d022f8aa23a89a7d) created broken code. 

**Describe the current behavior**.
Broken code 

**Describe the expected behavior**.
Keras needs some CI.

**Comment by ymodak** [comment]
This is fixed with https://github.com/keras-team/keras/commit/f6e8d5b910aa8afca0f9c4b5b9435cc356adb78c
Thanks!
