### ISSUE TITLE
TF 2.5 | Keras preprocessing.CategoryCrossing behavior different than feature_column.crossed_column

### ISSUE THREAD

**Issue by rafiqhasan** [keras-team/keras#14972]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- TensorFlow version (use command below): 2.5( All 2+ )
- Python version: 3.7

**Describe the current behavior**
When using the new `experimental.preprocessing.CategoryCrossing` layer, it returns values like `[[b'1_X_2_X_3'], [b'4_X_5_X_6']]` as stated in the documentation. Now when the dimension space becomes very large, it is impossible to convert these values to embeddings using the layer `tf.keras.layers.Embedding` as it expects values to be encoded between 0 to N and the layer doesn't return any integerlookup / vocabulary for new categories generated from `CategoryCrossing`. So it is not easily possible to use the output from `CategoryCrossing` to convert to Embeddings, this was directly possible in `tf.feature_column.embedding_column`

Bug has also been raised in TF Git: https://github.com/tensorflow/tensorflow/issues/50821 but it is explained by @saikumarchalla that the issue **is in Keras and not Tensorflow**

One of the alternates that I was trying was as below:
```
cross_day_hour = tf.keras.layers.experimental.preprocessing.CategoryCrossing()([cat_day, cat_hour])
hash_cross_day_hour = tf.keras.layers.experimental.preprocessing.Hashing(num_bins=24 * 8)(cross_day_hour)
embed_cross_day_hour = tf.keras.layers.Embedding(193, 4)(hash_cross_day_hour)
```

However it is not reliable to use the above method as the Hashing layer will have possible collisions( even when num_bins = max number of values ) in each training loop of minibatch. The hashing layer doesn't remember values from previous loops, leading to same hash for different values in each iteration. This will lead to same value passing in the `Embedding` layer for same hash generated for two different values being passed to `Hashing` layer in separate training batches( loops ).

It was *possible earlier* using the `tf.feature_column.crossed_column` to convert it to embeddings by passing the output directly to `tf.feature_column.embedding_column`. `crossed_column` automatically used to return hashes which were directly pluggable in `embedding_column` to generate embeddings but with the new layer this is no more possible. ***Please fix this.***

**Describe the expected behavior**:
Either of possible solutions:
1. The new layer `preprocessing.CategoryCrossing` should ideally be directly pluggable with the `layers.Embedding` layer to generate embeddings for very large categorical space. It should generate values = 0 to N
2. Or `preprocessing.CategoryCrossing` should return some other output as well which depicts what all possible unique values are there that can be passed to StringLookup layer to further generate Integer mapping per cross.
3. Or `preprocessing.Hashing` should be capable of remembering values from previous loops until re-instantiated in order to avoid generating same hashes for different values even though num_bins = total unique values

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
```
cross_day_hour = tf.keras.layers.experimental.preprocessing.CategoryCrossing()([cat_day, cat_hour])
hash_cross_day_hour = tf.keras.layers.experimental.preprocessing.Hashing(num_bins=24 * 8)(cross_day_hour)
embed_cross_day_hour = tf.keras.layers.Embedding(193, 4)(hash_cross_day_hour)
```

Also see how the ***Hashing*** layer generates same hash for different values even though num_bins is set to total number of unique values, which makes it impossible to use the above solution:

```
import tensorflow as tf
import tensorflow.keras as keras

layer = tf.keras.layers.experimental.preprocessing.Hashing(num_bins=10)
inp = [['A'], ['B'], ['C'], ['D'], ['E']]
print(layer(inp))

inp = [['F'], ['G'], ['H'], ['I'], ['J']]
print(layer(inp))
```

Output:
```
tf.Tensor(
[[4]
 [8]
 [7]
 [5]
 [2]], shape=(5, 1), dtype=int64)
tf.Tensor(
[[6]
 [1]
 [8]
 [0]
 [4]], shape=(5, 1), dtype=int64)

```

CC: @rsesha @AutoViML @rafiqhasan - This directly affects the libraries: https://github.com/AutoViML/deep_autoviml and https://github.com/rafiqhasan/auto-tensorflow/

**Comment by rafiqhasan** [comment]
Any updates ?

**Comment by mattdangerw** [comment]
We are actively looking at this! It actually seems like there's a couple different feature workflows being described above.

1) Convenient **hashed** crossing of categorical (int or string) input features. This is what `feature_column.crossed_column` provides, and we don't currently have a one-to-one replacement. We are looking at a design for one now. Worth noting that `crossed_column` has no mechanism for guaranteeing no collisions either! If you have a hashing+modding step in your crossing, you cannot guarantee no collisions (though in practice that's usually fine and bounding your crossing space can be important). The replacement would have integer output can be easily fed to an embedding.

2) Collision-less crossing of categorical inputs. This does not exist in `feature_columns` as far as I know. We are unsure whether we need a layer for this inside Keras. After converting all inputs to integers of a known range (e.g. with `StringLookup` and `IntegerLookup`), doing a crossing like this is quite trivial (its just `a * x1 + x2`). Some quick code for a layer to do this:

```
class IntCrossing(tf.keras.layers.Layer):
  """Multiply multiple categorical inputs, so each output index in unique."""
  def __init__(self, category_sizes, **kwargs):
    super().__init__(**kwargs)
    self.category_sizes = category_sizes

  def call(self, inputs):
    output = inputs[0]
    for i in range(1, len(inputs)):
      output = output * self.category_sizes[i] + inputs[i]
    return output

  def get_config(self):
    config = super().get_config()
    config.update({
        'category_sizes': self.category_sizes,
    })
    return config

IntCrossing([2, 5])((tf.constant([0, 1, 1, 0]), tf.constant([1, 2, 3, 4])))
>>> <tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 7, 8, 4], dtype=int32)>
```

For now, we have left `CategoryCrossing` in experimental as the layer is still subject to change. Any thoughts, please let us know!

Will update here as we make more progress on a better replacement layer for `crossed_column`.

**Comment by rafiqhasan** [comment]
Hi Matt,

Thank you so much for your response! I like the idea of both the approaches and seeing your response I am quite positive that we'll have a good solution for this.

Here are my thoughts and if needed I am happy to get on a call:

1. The explanation in point 1 seems correct but then it means that ```hashing``` layer probably needs to be fixed. Ideally the layer should be respecting the num_bins parameter, if we have already provided num_bins = 10 and the total set of unique values in space is also 10 then hash should not return collisions. Technically that means hashing is buggy. You can look at the example I gave in bug. If this problem is in ```feature_column.crossed_column``` as well then its a bigger problem to fix and strange that it was never caught. I think a robust hashing like ```Farm-Fingerprint``` should be implemented to fix this.

2. For collision less crossing i.e crossing on two lookup based categorical problems should be fairly easy.

Overall after reading your comments I believe the right thing to do is to fix the hashing layer. Once we fix ```hashing``` the point 1 will not exist and point 2 can be directly applied by combining ```category_crossing``` with ```hashing```

**Comment by mattdangerw** [comment]
I don't believe a hashing trick will ever be able to guarantee you a lack of collisions. You will see the exact same behavior in the underlying op, the feature column for hashing, and the feature column for crossed hashing.

 - https://www.tensorflow.org/api_docs/python/tf/strings/to_hash_bucket_fast
 - https://www.tensorflow.org/api_docs/python/tf/feature_column/categorical_column_with_hash_bucket
 - https://www.tensorflow.org/api_docs/python/tf/feature_column/crossed_column

All of these will do a hash *followed by a mod at the end*, and even with a good hash, that mod will involve some chance of collisions (basically think of a uniform distribution over your buckets). This is the entire point of the hashing trick, it allows you to have output indices of a bounded size without knowing anything about the input features. If this is unclear I think we should be updating the documentation for the hashing layer, but will not be changing how it works.

It sounds like what you are describing is a hash without a mod at the end, which would give you a lack of collisions, but would not be a good idea as the `Embedding` layer needs to know the input size, and without the mod we would have input size=the entire integer space. So if lack of collisions is essential, you need to do what I described in 2) above, no hash required. Keep in mind that if your hashing buckets are large enough, collisions will be rare, and in practice you may see no difference in model performance.

**Comment by rafiqhasan** [comment]
Wow ! That makes sense and I think its a really good idea to update the documentation as this is quite different than I have seen it in SkLearn etc. It should be good for other users to know as well.

Then it should be good

**Comment by mattdangerw** [comment]
We have now released a `tf.keras.layers.experimental.preprocessing.HashedCrossing` layer with equivalent functionality to crossed_column (crosses concatenations of features with a hashing trick).

https://www.tensorflow.org/api_docs/python/tf/keras/layers/experimental/preprocessing/HashedCrossing
