### ISSUE TITLE
ValueError: Error when checking target: expected aux1 to have shape (32, 32, 1) but got array with shape (256, 256, 1)

### ISSUE THREAD

**Issue by samuelireke** [keras-team/keras#14981]
### **My Problem**
I am currently working on a counting problem with the aim of examining the performance of attaching auxiliary outputs to UNETs . Unfortunately ran into a bug which I have been trying to resolve for over a week now. Have read several documentations and tried modifying my code in accordance but no success. 

I will be immensely grateful if anyone can help. 

### **Error obatined**.
File "<ipython-input-26-6a9e56aa1403>", line 1, in <module>
    runfile('C:/Users/samue/OneDrive/Documents/ODA Project/Napier University/Trimester 4 - Dissertation/UNet tutorial/tut2 - Xie et al/cell_counting_v2-master/train.py', wdir='C:/Users/samue/OneDrive/Documents/ODA Project/Napier University/Trimester 4 - Dissertation/UNet tutorial/tut2 - Xie et al/cell_counting_v2-master')

  File "C:\Users\samue\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\samue\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/samue/OneDrive/Documents/ODA Project/Napier University/Trimester 4 - Dissertation/UNet tutorial/tut2 - Xie et al/cell_counting_v2-master/train.py", line 293, in <module>
    train_(base_path)

  File "C:/Users/samue/OneDrive/Documents/ODA Project/Napier University/Trimester 4 - Dissertation/UNet tutorial/tut2 - Xie et al/cell_counting_v2-master/train.py", line 282, in train_
    train_model_multi_task(model, X_train,X_val,Y_train,Y_val)

  File "C:/Users/samue/OneDrive/Documents/ODA Project/Napier University/Trimester 4 - Dissertation/UNet tutorial/tut2 - Xie et al/cell_counting_v2-master/train.py", line 280, in train_model_multi_task
    validation_steps = X_val.shape[0] // batch_size

  File "C:\Users\samue\Anaconda3\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\samue\Anaconda3\lib\site-packages\keras\engine\training.py", line 1732, in fit_generator
    initial_epoch=initial_epoch)

  File "C:\Users\samue\Anaconda3\lib\site-packages\keras\engine\training_generator.py", line 220, in fit_generator
    reset_metrics=False)

  File "C:\Users\samue\Anaconda3\lib\site-packages\keras\engine\training.py", line 1508, in train_on_batch
    class_weight=class_weight)

  File "C:\Users\samue\Anaconda3\lib\site-packages\keras\engine\training.py", line 621, in _standardize_user_data
    exception_prefix='target')

  File "C:\Users\samue\Anaconda3\lib\site-packages\keras\engine\training_utils.py", line 145, in standardize_input_data
    str(data_shape))

ValueError: Error when checking target: expected aux1 to have shape (32, 32, 1) but got array with shape (256, 256, 1)

**Describe the expected behavior**.

![01](https://user-images.githubusercontent.com/48257726/126470351-a9d0a2d2-1146-4d23-9eff-b16dd5ea551c.JPG)

### **My code**.
import numpy as np
import pdb
import os
import tensorflow as tf
import matplotlib.pyplot as plt
from generator import ImageDataGenerator
from model import buildModel_U_net
from model import *
from keras import backend as K
import time
from keras.callbacks import ModelCheckpoint,Callback,LearningRateScheduler,EarlyStopping
from scipy import misc
import scipy.ndimage as ndimage

class LossHistory(Callback):
    def on_train_begin(self, logs={}):
        self.losses = []

    def on_batch_end(self, batch, logs={}):
        self.losses.append(logs.get('loss'))

def step_decay(epoch):
    step = 16
    num =  epoch // step 
    if num % 3 == 0:
        lrate = 1e-3
    elif num % 3 == 1:
        lrate = 1e-4
    else:
        lrate = 1e-5
        #lrate = initial_lrate * 1/(1 + decay * (epoch - num * step))
    print('Learning rate for epoch {} is {}.'.format(epoch+1, lrate))
    return np.float(lrate)

 
base_path = 'cells/'
data = []
anno = []

def read_data(base_path):
    imList = os.listdir(base_path)
    for i in range(len(imList)): 
        if 'cell' in imList[i]:
            img1 = plt.imread(os.path.join(base_path,imList[i]))
            data.append(img1)
            
            img2_ = plt.imread(os.path.join(base_path, imList[i][:3] + 'dots.png'))
            img2 = 100.0 * (img2_[:,:,0] > 0)
            img2 = ndimage.gaussian_filter(img2, sigma=(1, 1), order=0)
            anno.append(img2)
    return np.asarray(data, dtype = 'float32'), np.asarray(anno, dtype = 'float32')

def load_data():
    data, anno = read_data(base_path)
    anno = np.expand_dims(anno, axis = -1)
    
    mean = np.mean(data)
    std = np.std(data)
    print('Size of dataset = ', len(data[:]))
    data_ = (data - mean) / std
    
    train_data = data_[:150]
    train_anno = anno[:150]
    print('Size of training dataset = ', len(train_data[:]))

    val_data = data_[150:]
    val_anno = anno[150:]
    print('Size of validation dataset = ', len(val_data[:]))
    return train_data, train_anno , val_data , val_anno     

  
def train_(base_path):
    #device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    X_train,Y_train, X_val, Y_val = load_data()
    
    print('-'*30)
    print('Creating and compiling the fully convolutional regression networks.')
    print('-'*30)    
   
    model = buildMultiModel_U_net(input_dim = (256,256,3))
    model_checkpoint = ModelCheckpoint('cell_counting.hdf5', monitor='loss', save_best_only=True)
    early_stop = EarlyStopping(patience=2, monitor='val_loss')
    model.summary()
    #Plot model architecture
    #tf.keras.utils.plot_model(model,
    #                       to_file = 'model.pdf',
    #                         show_shapes = True,
    #                         show_layer_names = True,
    #                         rankdir = 'TB',
    #                         expand_nested = False,
    #                         dpi = 96)
    print('...Fitting model...')
    print('-'*30)
    change_lr = LearningRateScheduler(step_decay)
    time1 = time.time()
    

    def train_model_multi_task(model, X_train, X_val, Y_train, Y_val, nb_epochs=192, nb_epoch_per_record=1, input_shape=(256,256,3), batch_size =2, is_mae = False, lr_max = None):
    	import random
    	train_images=np.concatenate([X_train,Y_train],axis= -1)
    	val_images=np.concatenate([X_val,Y_val],axis= -1)
    	#print(len(train_images))
    	print(X_train.shape[0])        
    	
    	## train data generator
    	train_datagen = ImageDataGenerator(
        featurewise_center = False,  # set input mean to 0 over the dataset
        samplewise_center = False,  # set each sample mean to 0
        featurewise_std_normalization = False,  # divide inputs by std of the dataset
        samplewise_std_normalization = False,  # divide each input by its std
        zca_whitening = False,  # apply ZCA whitening
        rotation_range = 30,  # randomly rotate images in the range (degrees, 0 to 180)
        width_shift_range = 0.3,  # randomly shift images horizontally (fraction of total width)
        height_shift_range = 0.3,  # randomly shift images vertically (fraction of total height)
        zoom_range = 0.3,
        shear_range = 0.,
        horizontal_flip = True,  # randomly flip images
        vertical_flip = True, # randomly flip images
        fill_mode = 'constant',
        #validation_split=0.2,
        dim_ordering = 'tf')
    	train_datagen.fit(train_images)
    	#train_gen=train_datagen.flow(X_train, Y_train, batch_size = 2 )
    
    	## validation data generator
    	val_datagen = ImageDataGenerator(
        featurewise_center = False,  # set input mean to 0 over the dataset
        samplewise_center = False,  # set each sample mean to 0
        featurewise_std_normalization = False,  # divide inputs by std of the dataset
        samplewise_std_normalization = False,  # divide each input by its std
        zca_whitening = False,  # apply ZCA whitening
        rotation_range = 30,  # randomly rotate images in the range (degrees, 0 to 180)
        width_shift_range = 0.3,  # randomly shift images horizontally (fraction of total width)
        height_shift_range = 0.3,  # randomly shift images vertically (fraction of total height)
        zoom_range = 0.3,
        shear_range = 0.,
        horizontal_flip = True,  # randomly flip images
        vertical_flip = True, # randomly flip images
        fill_mode = 'constant',
        #validation_split=0.2,
        dim_ordering = 'tf')
    	val_datagen.fit(val_images)
    	#val_gen=val_datagen.flow(X_val, Y_val, batch_size = 2)
        
    	def multiple_outputs(generator, X, Y):    
            genX = generator.flow(X, Y, seed=7, batch_size = 150)

            while True:
                genXi = genX.next()

                yield genXi[0], [genXi[1],genXi[1], genXi[1], genXi[1]]
            
    	train_gen = multiple_outputs(train_datagen, X_train, Y_train, )
    	val_gen = multiple_outputs(val_datagen, X_val, Y_val)
    	print (train_gen)
    
    
    # Fit the model on the batches generated by datagen.flow().
    	model.fit_generator(train_gen,
                            steps_per_epoch = X_train.shape[0] // batch_size,
                            epochs = 192,
                            callbacks = [model_checkpoint, change_lr,early_stop],
                            validation_data= val_gen,
                            validation_steps = X_val.shape[0] // batch_size
                           )
    train_model_multi_task(model, X_train,X_val,Y_train,Y_val)
    model.load_weights('cell_counting.hdf5')
    A = model.predict(X_val)
    mean_diff = np.average(np.abs(np.sum(np.sum(A,1),1)-np.sum(np.sum(Y_val,1),1))) / (100.0)
    
    time2 = time.time()
    print('Training time:{}'.format(time2-time1 , str(' seconds')))
    print('After training, the difference is : {} cells per image.'.format(np.abs(mean_diff)))
 

if __name__ == '__main__':
    train_(base_path)

###############################
**Model defination**
###############################
weight_decay = 1e-5
#K.set_image_dim_ordering('tf')
K.set_image_data_format('channels_last')

def _conv_bn_relu(nb_filter, row, col, subsample = (1,1)):
    def f(input):
        conv_a = Conv2D(nb_filter, row, col, subsample = subsample,
                               init = 'orthogonal', 
                               border_mode='same', bias = False)(input)
        norm_a = BatchNormalization()(conv_a)
        act_a = Activation(activation = 'relu')(norm_a)
        return act_a
    return f

def U_net_Multi_base(input, dropout = None):
	nb_filter = 32
	kernel_size = (3,3)
	block1 = _conv_bn_relu(nb_filter, 3,3)(input)
	pool1 = MaxPooling2D(pool_size=(2,2))(block1)
	# =========================================================================
	block2 = _conv_bn_relu(nb_filter*2, 3,3)(pool1)
	pool2 = MaxPooling2D(pool_size=(2, 2))(block2)
	# =========================================================================
	block3 = _conv_bn_relu(nb_filter*4, 3,3)(pool2)
	pool3 = MaxPooling2D(pool_size=(2, 2))(block3)
	# =========================================================================
	block4 = _conv_bn_relu(nb_filter*16, 3,3)(pool3)
	if dropout:
		block4 = Dropout(dropout)(block4)
	# =========================================================================
	up5 = Concatenate(axis = -1)([UpSampling2D(size=(2, 2))(block4), block3])
	block5 = _conv_bn_relu(nb_filter*4, 3,3)(up5)
	# =========================================================================
	up6 =  Concatenate(axis = -1)([UpSampling2D(size=(2, 2))(block5), block2])
	block6 = _conv_bn_relu(nb_filter*2, 3,3)(up6)
	# =========================================================================
	up7 =  Concatenate(axis = -1)([UpSampling2D(size=(2, 2))(block6), block1])
	block7 = _conv_bn_relu(nb_filter, 3,3)(up7)
	# =========================================================================
	out_block1 = _conv_bn_relu_x2(nb_filter, 3,3)(block4)
	# =========================================================================
	out_block2 = _conv_bn_relu_x2(nb_filter, 3,3)(block5)
	# =========================================================================
	out_block3 = _conv_bn_relu_x2(nb_filter, 3,3)(block6)
	return out_block1, out_block2, out_block3, block7

def buildMultiModel_U_net(input_dim, lr = 1e-2, dropout = None, loss_fcn = 'mse', activation = 'linear', loss_weights=[1./64,1/16, 1./4, 1]):
	input_ = Input (shape = (input_dim))
	# =========================================================================
	out_block1, out_block2, out_block3, block7 = U_net_Multi_base(input_, dropout)
	# =========================================================================
	density_pred_1 =  Conv2D(1, (1,1), padding='same', kernel_initializer='orthogonal', activation = activation, name = 'aux1')(out_block1)	
	density_pred_2 =  Conv2D(1, (1,1), padding='same', kernel_initializer='orthogonal', activation = activation, name = 'aux2')(out_block2)
	density_pred_3 =  Conv2D(1, (1,1), padding='same', kernel_initializer='orthogonal', activation = activation, name = 'aux3')(out_block3)
	density_pred_4 =  Conv2D(1, (1,1), padding='same', kernel_initializer='orthogonal', activation = activation, name = 'original')(block7)
	# =========================================================================
	model = Model (inputs = input_, outputs = [density_pred_1, density_pred_2, density_pred_3, density_pred_4])
	#opt = SGD(lr = lr, momentum = 0.9, nesterov = True)
	model.compile(optimizer = 'adam', loss = 'mse')
	return model

**Comment by rmothukuru** [comment]
@samuelireke,
 From the First Layer of the Model Architecture, 

![image](https://user-images.githubusercontent.com/48206667/126498455-a2c4ef81-e79c-48e1-a89b-b5886f1ef966.png)

the **`shape`** of the **`Input`** Image should be **`(32,32)`** but the Shape of your Image is **`(256,256)`**, as seen from the below code:

**`def train_model_multi_task(model, X_train, X_val, Y_train, Y_val, nb_epochs=192, nb_epoch_per_record=1, input_shape=(256,256,3), batch_size =2, is_mae = False, lr_max = None):`**

Please try changing either the Input Shape of the Image or the Input Shape in the First Layer of the Model.

**Comment by samuelireke** [comment]
> @samuelireke,
> From the First Layer of the Model Architecture,
> 
> ![image](https://user-images.githubusercontent.com/48206667/126498455-a2c4ef81-e79c-48e1-a89b-b5886f1ef966.png)
> 
> the **`shape`** of the **`Input`** Image should be **`(32,32)`** but the Shape of your Image is **`(256,256)`**, as seen from the below code:
> 
> **`def train_model_multi_task(model, X_train, X_val, Y_train, Y_val, nb_epochs=192, nb_epoch_per_record=1, input_shape=(256,256,3), batch_size =2, is_mae = False, lr_max = None):`**
> 
> Please try changing either the Input Shape of the Image or the Input Shape in the First Layer of the Model.

Tried it but it returned an error for the other outputs since they have different shapes too. my dataset is (256,256) which should also be the shape of the main output, aux1 is expected to have (32,32), aux 2 (64,64), aux3 (128, 128).
My challenge is how can I define these to train my model. I would also appreciate relevant documentation on how to train models  with varying auxiliary output shapes.

**Comment by jvishnuvardhan** [comment]
@samuelireke Looks like data size mismatch is the problem. Can you add a reshape layer or use `ImageDataGenerator` as shown in this guide to set a `target_size`. So, if you set `target_size` as (256, 256,1), irrespective of your input data size, `ImageDataGenerator` reshapes data before passing it to the model. Thanks!

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please feel free to reopen if I am mistaken. Thanks!
