### ISSUE TITLE
Segmentation probability maps depend on CPU or GPU used for inference

### ISSUE THREAD

**Issue by pedrogalher** [keras-team/keras#14986]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): [colab](4/1AX4XfWiMccDeno1wNhW3ZhVTuhFA4Bb_CdiTMgXYk2HJ2tkEn5vu6UWqzWI) 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): TF2.5
- Python version: 3.8
- GPU model and memory: Nvidia 3080

**Describe the problem**.

I wrote a model for semantic segmentation in tensorflow. The model were trained in a CPU and the predictions were also done in a CPU. After some time I run the predictions again in a GPU machine and I noticed that there were some very small differences in the probability maps (from the 4th-5th decimal value). In addition, I wanted to check if the batch size affected the prediction distribution (I initially thought that there were no influence).

I ran a small experiment describing these four situations:

A1) Model Trained in CPU and Predictions run in CPU --> Batch Size = 1

A2) Model Trained in CPU and Prediction run in CPU --> Batch Size = 64

B1) Model Trained in CPU and Predictions run in GPU --> Batch Size = 1

B2) Model Trained in CPU and Prediction run in GPU --> Batch Size = 64

I observed that :

1. Training the model and running the predictions in a CPU provides the same results regardless the batch size.

2. Batch size has an effect (although small) when training the model in a CPU and running the predictions in a GPU

3. Predictions provided by a CPU and a GPU don't match (very small differences). This can be relevant if the cutoff threshold is placed at 0.55, the CPU will classify a given pixel as a background pixel (0.549857<0.55) , whereas the GPU will classify it as a foreground pixel (0.550076>0.55) if the image was part of a larger batch.
Running the GPU predictions again, provide different probabilities (very small differences again), whereas CPU provides always the same probabilities.

Here is the link to the [colab](https://drive.google.com/drive/folders/1YWXvM9h21DMu91trfyywoa--SGfqOneh?usp=sharing) to reproduce the feature. I inluded the model I used for that (the enitre model was saved) and some images that I have used.

So my main questions are:

- Is this behaviour something normal that is expected to happen?
- Why this behavior happens? Is this related to [this](https://keras.io/getting_started/faq/#how-can-i-obtain-reproducible-results-using-keras-during-development)?
- How can I avoid this to happen? So that the Predictions run in a GPU always provide the same probabilities as the CPU) and regardless of the batch size?

**Describe the current behavior**.
Differences in the probability maps based on when the inferences is done with a CPU or a GPU.

_Some Results:_ 

**Probability maps when running the inference in GPU** (there is a difference between using a batch size of 1 and using >1)

Batch Size=1

[[0.05668435 0.10867791 0.04235671 ... 0.22491932 0.12363011 0.17167044]
 [0.04555672 0.03822105 0.03054511 ... 0.42176178 0.11014031 0.0701196 ]
 [0.01282059 0.01109215 0.03718    ... 0.38060975 0.16944014 0.09439405]
 ...
 [0.0309867  0.01612546 0.03472591 ... 0.04758538 0.0287854  0.02922609]
 [0.09070282 0.01980974 0.04191865 ... 0.08519646 0.02937398 0.02979605]
 [0.08077859 0.02201488 0.04651429 ... 0.07312316 0.03979398 0.08936194]]

Batch Size>1
[[0.05668447 0.10867798 0.04235688 ... 0.22491935 0.12363014 0.17167065]
 [0.04555689 0.03822101 0.03054521 ... 0.42176208 0.11014052 0.07011983]
 [0.01282063 0.01109215 0.03718007 ... 0.3806101  0.1694407  0.09439442]
 ...
 [0.03098667 0.01612546 0.03472591 ... 0.04758547 0.02878542 0.02922612]
 [0.09070284 0.01980972 0.04191868 ... 0.08519673 0.02937401 0.02979604]
 [0.08077855 0.02201487 0.04651425 ... 0.07312333 0.03979404 0.08936189]]

**Probability maps when running the inference in CPU** (there is NO difference between using a batch size of 1 and using >1)

Batch Size=1

[[0.05668434 0.10867806 0.04235679 ... 0.22491916 0.12363013 0.1716703 ]
 [0.04555671 0.03822112 0.03054515 ... 0.42176208 0.11014024 0.07011949]
 [0.01282062 0.01109214 0.03717988 ... 0.3806093  0.1694399  0.09439388]
 ...
 [0.03098666 0.01612545 0.03472593 ... 0.04758537 0.02878539 0.02922607]
 [0.09070285 0.01980974 0.04191878 ... 0.08519644 0.02937397 0.02979606]
 [0.08077864 0.02201489 0.04651435 ... 0.07312308 0.039794   0.08936188]]

Batch Size>1
[[0.05668434 0.10867806 0.04235679 ... 0.22491916 0.12363013 0.1716703 ]
 [0.04555671 0.03822112 0.03054515 ... 0.42176208 0.11014024 0.07011949]
 [0.01282062 0.01109214 0.03717988 ... 0.3806093  0.1694399  0.09439388]
 ...
 [0.03098666 0.01612545 0.03472593 ... 0.04758537 0.02878539 0.02922607]
 [0.09070285 0.01980974 0.04191878 ... 0.08519644 0.02937397 0.02979606]
 [0.08077864 0.02201489 0.04651435 ... 0.07312308 0.039794   0.08936188]]

**Comment by tomerk** [comment]
Unfortunately GPU computations are often nondeterministic and susceptible to small numerical differences, e.g. https://github.com/tensorflow/tensorflow/issues/2732

I believe @reedwm is exploring fully-deterministic computation on GPUs for TensorFlow, though I'm not sure what the timeline for that looks like.

**Comment by reedwm** [comment]
The plan is that there will be a flag to make all GPU ops deterministic in TensorFlow 2.7. This means if you run the exact same op on the GPU multiple times, you will get the exact same results. However, even with the flag, running on the CPU will likely produce slightly different results than running on the GPU. Making CPU and GPU have identical numeric behavior is very difficult, so it is unlikely we would ever make running a model on the CPU give the exact same results as running on the GPU. 

Changing the training batch size may significantly affect training results, which would be true even with infinite precision, so it is expected changing it may affect the results.

In TensorFlow 2.5 and 2.6, setting the enviornmental variable `TF_DETERMINISTIC_OPS=1` will make many GPU ops deterministic, so you can try that, but some GPU ops will still be nondeterministic.

**Comment by pedrogalher** [comment]
Hi both,

Thank you very much for your explanations.
I'm actually relieved that this difference is something that is expected to happen when working with GPUs.

I will try to set the environmental variable to 1 in the future.

I think my question has been successfully answered. Therefore, I close the issue.

Pedro
