### ISSUE TITLE
No errors with incorrect input shape for LSTM

### ISSUE THREAD

**Issue by samshipengs** [keras-team/keras#15016]
I'm trying to build a LSTM with Keras,

    num_input = Input(shape=(30, 5), name='num_input')
    lstm = tf.keras.layers.LSTM(256, dropout=0.)
    x = lstm(num_input)

so my timesteps are 30 and for each timestep there is a feature with dimension 5, however, I noticed that I can change the feature dimension in Input to others and the networks still train fine, but I was expecting it would throw an error about shape mismatch, e.g. num_input = Input(shape=(30, 10), name='num_input') still works fine even when I was still supplying dataset with feature dim 5.

I did some check to other Keras tutorials, and looks like my understanding of Input is correct, i.e. (timesteps_dim, feature_dim), but why fit doesn't give an error when I initialized the model input to have the wrong feature_dim? I also looked at the model summary, it also shows it has more parameters now, this is really confusing me.

edit: I also tried changing the timesteps dimension to an incorrect value, the model.fit still runs fine as well.

tf version: '2.4.1'
keras version: '2.4.3'
OS: Ubuntu 20.04.2 LTS

**Comment by rmothukuru** [comment]
@samshipengs,
It is throwing the Error,

`ValueError: Dimensions must be equal, but are 10 and 5 for '{{node MatMul}} = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false](strided_slice_1, kernel)' with input shapes: [?,10], [5,1024].` 

as expected.

Please find the working code below:

```python
import tensorflow as tf
num_input = tf.keras.Input(shape=(30, 5), name='num_input')
lstm = tf.keras.layers.LSTM(256, dropout=0.)
x = lstm(num_input)
```

Above code doesn't give error.

```python
num_input1 = tf.keras.Input(shape=(30, 10), name='num_input1')
x = lstm(num_input1)
```

But the above code gives:
```python
ValueError: Dimensions must be equal, but are 10 and 5 for '{{node MatMul}} = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false](strided_slice_1, kernel)' with input shapes: [?,10], [5,1024].
```

**Comment by samshipengs** [comment]
@rmothukuru thanks for checking, unfortunately, it still doesn't throw me error (like what you had above) when I supplied incorrectly shaped input data, I wonder if this has something to do with my customized dataset...

**Comment by rmothukuru** [comment]
@samshipengs,
May be. Can you please let us know if we can Close this issue? Thanks!

**Comment by rmothukuru** [comment]
Closing the issue as it has been resolved. Thanks!
