### ISSUE TITLE
Add Metadata to Models

### ISSUE THREAD

**Issue by dgrahn** [keras-team/keras#15035]
**System information**.

TensorFlow version (you are using): v2.5.0
Are you willing to contribute it (Yes/No) : Yes

**Describe the feature and the current behavior/state**.
Models do not exist in isolation. Developers should be able to save their models with identifiers, tags, and other metadata.

**Will this change the current api? How?**
This could be implemented in one of two ways.

1. The `Model` class could be changed to include `add_metadata` and `get_metadata` methods.
2. The `models.save_model` function could be changed to accept metadata.

**Who will benefit from this feature?**
- Do you want to contribute a PR? (yes/no): I can
- Briefly describe your candidate solution(if contributing):

I prefer adding the methods directly to the model class. I could add these methods and ensure that the `save_model` and `load_model` functions respect them.

**Comment by rmothukuru** [comment]
@dgrahn,
Thank you for the issue. Feel free to submit a PR and we will be happy to review it.

**Comment by rchao** [comment]
Using config of the model or a variable as an attr of the model should allow them to be saved in the saved model. Can either of these work for you?

**Comment by dgrahn** [comment]
@rchao That should work. I'll get at it.
