### ISSUE TITLE
How to training new model begin from loading the old weight ?

### ISSUE THREAD

**Issue by HuangChiEn** [keras-team/keras#15045]
Most of the retrain issues have a suitable solution in keras, but the above request may be a new issue in some applications. 

I have no idea how to training a new model (add some new layers on the old model structure) base on the pre-trained old model (with pretrain weight).

For example. ( I did it, but it may not be a suitable way..
`
# at the first, train the old model
    def build_old_model( ):
          # omit...
     model = build_old_model( )
     model.compile( ...omit... )
     model.fit( ...omit... )
     model.save_weight("old_mod.h5")

# at the second phase, load old pretrain model and update the model structure!!
    def wrap_to_new_model( old_model ) :
          flatten_code = old_model.output                       # already have pretrain weights..
          pred_cls = Dense(units=42) (flatten_code)         # add new layer Dense..
          return Model( inputs=[old_model.input], outputs=[pred_cls] )
 
    old_model = build_old_model( )
    old_model.load_weight("old_mod.h5")
    new_model = wrap_to_new_model( old_model )
    new_model.compile( ...omit... )           # Since it's new model, it should compile...
    new_model.fit_generator( ...omit... )   # This line occur error
`
# Error message : 
FailedPreconditionError: Attempting to use uninitialized value Block8_2_Branch_1_Conv2d_0a_1x1_BatchNorm/moving_variance
	 [[{{node Block8_2_Branch_1_Conv2d_0a_1x1_BatchNorm/moving_variance/read}}]]
	 [[{{node metrics/acc/Mean}}]]

By the way, the pretrain model do not have the 'training=False' argument, and sess.run(initial) also cause some error. However, the mentioned error is not the point, I just have no idea that the example code is a right direction to train the new model? (or maybe I'm wrong )  

Any suggestion will be appreciated.... (plz emoji

**Comment by innat** [comment]
Here is some pointer. 

```python
import tensorflow as tf 
from tensorflow.keras.layers import * 
from tensorflow.keras import Input, Model 

(x_train, y_train), (_, _) = tf.keras.datasets.mnist.load_data()
x_train = x_train[..., tf.newaxis] / 255.0
x_train.shape, y_train.shape
((60000, 28, 28, 1), (60000,))
```

Build old model and train

```python
input = Input(shape=(28, 28, 1))
x = Flatten(name='flatten')(input)
x = Dense(512, name='dense1')(x)
x = Dense(256, name='dense2')(x)
y = Dense(units=10, activation='softmax')(x) 
old_model = Model(inputs=[input], outputs=[y])

old_model.compile(
          loss  = tf.keras.losses.SparseCategoricalCrossentropy(),
          metrics = tf.keras.metrics.SparseCategoricalAccuracy(),
          optimizer = tf.keras.optimizers.Adam())
old_model.fit(x_train, y_train)

4ms/step - loss: 0.4069 - sparse_categorical_accuracy: 0.8440
```

Next, save the weight 

```python
old_model.save_weights('old.h5')

# next
old_model = build_old_model...
old_model.load_weights('old.h5')
```

Next, we pick desired layer's output of the old model 

```python
new_dense1_code = old_model.get_layer('dense1').output                 
new_dense1_code
<KerasTensor: shape=(None, 512) dtype=float32 (created by layer 'dense1')>
```

Build a new model; for the difference in the new model from the old one, we now remove the `softmax` function in order to get logits.

```python
new_flat = Dense(units=100)(new_dense1_code)   
pred_cls = Dense(10)(new_flat) # remove softmax 

new_model = Model( inputs=[old_model.input],
                   outputs=[pred_cls] )


new_model.summary() # OK
new_model.get_weights() # Not Empty 
```

Train the new model 

```python
new_model.compile(
          loss  = ..SparseCategoricalCrossentropy(from_logits=True), # logit 
          metrics = ..SparseCategoricalAccuracy(),
          optimizer = tf.keras.optimizers.Adam())
new_model.fit(x_train, y_train)

3ms/step - loss: 0.3649 - sparse_categorical_accuracy: 0.8979
```

**Comment by jvishnuvardhan** [comment]
@innat thanks for the answer. 
@HuangChiEn Can you follow the process mentioned above. You could also check the [transfer learning tutorial](https://www.tensorflow.org/tutorials/images/transfer_learning) for more info . Thanks!

**Comment by patel-rupin2000** [comment]
You can take example of VGG16
model=Sequential()
from tensorflow.keras.applications.vgg16 import VGG16
base_model = VGG16(input_shape = (224, 224, 3), include_top = False, weights = 'imagenet')
for layer in base_model.layers:
    layer.trainable = False
x = Flatten()(base_model.output)
x = Dense(1024, activation='relu')(x)
x = Dropout(0.5)(x)
x = Dense(3, activation='softmax')(x)
model = Model(base_model.input, x)
model.compile(optimizer = "adam", loss = 'categorical_crossentropy',metrics = ["accuracy"])
model.summary()

Model: "model_1"

Layer (type) Output Shape Param #
input_2 (InputLayer) [(None, 224, 224, 3)] 0

block1_conv1 (Conv2D) (None, 224, 224, 64) 1792

block1_conv2 (Conv2D) (None, 224, 224, 64) 36928

block1_pool (MaxPooling2D) (None, 112, 112, 64) 0

block2_conv1 (Conv2D) (None, 112, 112, 128) 73856

block2_conv2 (Conv2D) (None, 112, 112, 128) 147584

block2_pool (MaxPooling2D) (None, 56, 56, 128) 0

block3_conv1 (Conv2D) (None, 56, 56, 256) 295168

block3_conv2 (Conv2D) (None, 56, 56, 256) 590080

block3_conv3 (Conv2D) (None, 56, 56, 256) 590080

block3_pool (MaxPooling2D) (None, 28, 28, 256) 0

Or take example of integrating YOLO waits here https://github.com/thtrieu/darkflow

**Comment by HuangChiEn** [comment]
Many thanks for your guys reply !!  The problem seems have a good solution presented in here~
