### ISSUE TITLE
Failure to load model files

### ISSUE THREAD

**Issue by Anuj040** [keras-team/keras#15048]
Copying the issue from [49162](https://github.com/tensorflow/tensorflow/issues/49162)
as advised by https://github.com/jvishnuvardhan @(https://github.com/tensorflow/tensorflow/issues/49162#issuecomment-880297471)

**Below I describe the issue**

I have a tensorflow model that I train using customizing the model.fit() as in following link
https://keras.io/guides/customizing_what_happens_in_fit/
Now when I save the model using ModelCheckpoint callback and then later try to reload the model (using tf.keras.models.Model.load_model) or weights (model.load_weights), I am unable to do that, with the following errors:

with _.load_model()_
> ValueError: No model found in config file. 

with _.load_weights()_
> ValueError: Unable to load weights saved in HDF5 format into a subclassed Model which has not created its variables yet. Call the Model first, then load the weights.

My models are defined using FunctionalAPI (https://keras.io/guides/functional_api/).

I am currently working with tensorflow==2.4.1 but I have faced a similar issue with 2.2.0 before.

Back then, to solve this issue, I wrote my own custom callback to save the model (using `.save()`) and then reload with `.load_model()`, as I discuss in this article [link](https://medium.com/dive-into-ml-ai/customization-of-model-fit-to-write-a-combined-discriminator-generator-gan-trainer-in-keras-524bce10cf66). But I was wondering if there is a default way to this.

Here is the [gist](https://gist.github.com/Anuj040/77a5ec315d8c5693f7e5e8dcb1072484).
I tried both the methods _load_model()_ method in the gist. 
so my question is what is the best way to save and load model if I am working with custom model.fit().
All help will be immensely appreciated.

**Comment by LanceNorskog** [comment]
Keras does not know about your subclasses, so it cannot load the model. This may not be the problem you are seeing, but you will need to use CustomObjects anyway.

This describes how to use the CustomObject registry:

https://keras.io/guides/serialization_and_saving/

**Comment by tanujdhiman** [comment]
Yes exactly.

**Comment by Anuj040** [comment]
> Keras does not know about your subclasses, so it cannot load the model. This may not be the problem you are seeing, but you will need to use CustomObjects anyway.
> 
> This describes how to use the CustomObject registry:
> 
> https://keras.io/guides/serialization_and_saving/

@LanceNorskog  Thanks a lot for your response. I followed your advice and made the following change to my load_model func().
```
def load_model(model):
    model = KM.load_model(
        "save_model/save_model.h5", custom_objects={"Trainer": Trainer}
    )
```

However, the problem persists..
>     raise ValueError('No model found in config file.')
> ValueError: No model found in config file.

**Comment by LanceNorskog** [comment]
There are two kinds of model files: .json and .h5. .h5 files are for storing lots of numbers. It may be that Keras will only load weights from a .h5 file. If you save the model as 'save_model.json' it should reload. It will also be in text form, so it will be a much larger file than a .h5 file. 

The manual page mentions .hdf5 files, which is the full name of this format.
https://keras.io/api/callbacks/model_checkpoint/

This blog has some good examples of saving&loading models:
https://machinelearningmastery.com/check-point-deep-learning-models-keras/

Machine Learning Master has a great collection of Keras recipes. I've fixed several problems by looking up what he did.

**Comment by tilakrayal** [comment]
@Anuj040 ,
Can you please take a look at this [comment](https://github.com/keras-team/keras/issues/15048#issuecomment-895446548) and try in latest version.Thanks!

**Comment by Anuj040** [comment]
@tilakrayal Sorry for not responding to this sooner. On trying the _*.json_ method as suggested [here](https://github.com/keras-team/keras/issues/15048#issuecomment-895446548), I received the following error in saving the model

> ValueError: Model <__main__.Trainer object at 0x140a80cd0> cannot be saved either because the input shape is not available or because the forward pass of the model is not defined.To define a forward pass, please override `Model.call()`. To specify an input shape, either call `build(input_shape)` directly, or call the model on actual data using `Model()`, `Model.fit()`, or `Model.predict()`. If you have a custom training step, please make sure to invoke the forward pass in train step through `Model.__call__`, i.e. `model(inputs)`, as opposed to `model.call()`.
>
The above issue I could solve in a hacky way as suggested [here](https://github.com/tensorflow/tensorflow/issues/39906#issue-625733265)
However this did not save a _*.json_ file instead it just created a folder named "save_model.json" as can be seen in the picture below
<img width="789" alt="image" src="https://user-images.githubusercontent.com/66895104/163674498-a5857261-74ad-4647-817d-5f982df1f530.png">
However, despite it not being a _json_ file, I am able to reload the model variables. So, basically it will work without _.json_ as well just not with _.h5_.
Thanks a lot for your assistance.

**Comment by tilakrayal** [comment]
@Anuj040 ,
Glad the issue is resolved for you and thank you for moving the issue to closed status.
