### ISSUE TITLE
Possibility to use 3D data in Image-Augmentation layer (Keras)

### ISSUE THREAD

**Issue by innat** [keras-team/keras#15046]
General. 

---

Keras provides the [image augmentation layers](https://keras.io/api/layers/preprocessing_layers/image_augmentation/) for 2D image and (even possible to use on intermediate feature maps) that takes input shape of `(samples, height, width, channels)` and returns `(samples, height, width, channels)`.

However, **is it possible to use these convenient functions on 3D data?** I've cases where data is in 3D shape, e.g. `(samples, 224, 224, 32, 3)` or `(samples, height, width, depth, channels)`. I'm wondering as we've some built-in 3D layers and 2D layers.

**Comment by LanceNorskog** [comment]
It should be possible to code a generic add-on to TF datasets: given a 2D image augmentation class, splits the 3D image into a stack of 2D layers, applies the augmentation to each flat layer, then repackages the stack into one new 3D image. This would then have the effect of, say, flipping a 3D medical image from left-right to right-left.

There are probably also 3D-only augmentations that could be useful.

**Comment by rchao** [comment]
Thanks. Making this as a contribution welcome issue.

**Comment by MaanasArora** [comment]
@rchao It seems that `TimeDistributed` performs the function we need, as @fchollet mentioned in the pull request I opened.

**Comment by innat** [comment]
It looks like it's possible to use in such cases as follows. However, I don't verify with reproducible results, when do, will update here. Also, for input shape `(None, h, w, depth, channel)`, we may need to transpose the input shape if we use the following `TimeDistributed` layers. You may also need to implement `compute_output_shape` for custom augmentation layers. 

```python 
keras_aug = tf.keras.layers.TimeDistributed(tf.keras.Sequential(
           [
              preprocessing.RandomFlip(),
              preprocessing.RandomRotation(),
              preprocessing.RandomTranslation(),
              preprocessing.RandomZoom(),
              custom_aug_layer_1(),
              custom_aug_layer_2()
           ],
          name='keras_augment_layers'
    )
)

keras_aug(tf.ones((2, 10, 224, 224, 3))).shape
TensorShape([2, 10, 224, 224, 3]
```
