### ISSUE TITLE
When using keras to train the model, how to use the output of the current round as the input of the next round.

### ISSUE THREAD

**Issue by SEEYOU20** [keras-team/keras#15043]
Hello. I want to use keras for time series forecasting. When forecasting, I hope that the forecast result at time t will be used as the input at time t+1. So when I want to train, I hope to use the output at time t as the input at time t+1. May I ask how it can be implemented in keras. Or how can it be achieved with tensorflow.

**Comment by HuangChiEn** [comment]
It may depend on which kind of forecasting model you want to use. For example, you attempt to use the LSTM to perform the series forecasting. The LSTM module has already taken the previous output (step t) as the next step (t+1) input automatically 'in the same layer'. So, you may not have to worried about how to implementation ~~ 

If you want to build the inner structure of RNN manually, then we can wait for other tensorflow experts to reply this question.

**Comment by SEEYOU20** [comment]
The effect I want to achieve is roughly as shown in the figure.
![image](https://user-images.githubusercontent.com/36726231/127761676-f7fc52b6-3183-425e-8407-3f68893d1b6a.png)

**Comment by rmothukuru** [comment]
@SEEYOU20,
Can you please let us know what is the Use Case for this functionality so that we will be able to help you? Thanks!

**Comment by SEEYOU20** [comment]
As shown in the figure, I will load the trained keras model into C++ for use. There are two values input to the model in each round, one of which is the predicted value of the model in the previous round (predict). So I hope that when the model is training, the output value of each round can also be used as the input value of the next round. I'm not sure if the model trained in this way is better because I don't know how to implement it yet.
The simple LSTM model I built before is not very good when used in this function of c++. Or just because the model I built is not good enough, the final prediction result is not good.
![image](https://user-images.githubusercontent.com/36726231/127893080-f072e545-0549-475c-ba96-471918cabacf.png)

**Comment by HuangChiEn** [comment]
Let's describe your problem more specifically. See below figure.1 is the framework of seq2seq.
![image](https://user-images.githubusercontent.com/52521165/127980274-91822176-e33a-4677-8af7-37657c5b78f4.png)

So, do you want to make your model pipeline as the follwoing figure.2 ?
![image](https://user-images.githubusercontent.com/52521165/127980768-1e6ae109-5761-46ca-8c43-50ccd103d8c8.png)

By the way, we may describe the whole picture in python, and then you may find the API to load the python model weight into C++ container or build & train in C++ directly by tensorflow released C++ API ~ ~

**Comment by SEEYOU20** [comment]
What I want is the one described in Figure 2.

**Comment by qlzh727** [comment]
Since this is more like a user support question rather than bug/issue, I would suggest you to post the question to the community to get more support and feedback.

**Comment by qlzh727** [comment]
Please forward this question to https://discuss.tensorflow.org/tag/help_request to get more support from community. You can also tag keras. Closing this issue since there isn't any action item here.
