### ISSUE TITLE
tf.saved_model.save fails when there is tf.reshape in tf.keras.Model call method

### ISSUE THREAD

**Issue by kacper-kleczewski** [keras-team/keras#15066]
**Current behavior**
tf.saved_model.save fails to save tf.keras.Model if there is tf.reshape operation in Model call method.

I have debugged it and I found that during saving the Model, SimpleModel.call is called twice. The first time everything is fine and **batch_size = 1,** but in the second call **batch_size = None** and this is why it fails.

**Expected behavior**
Model should be saved as Savedmodel

**Tested with**
TF 2.4.1 and TF 2.5 installed by PIP
Windows 10
Ubuntu 18.04
Nvidia GPU

**Example code for easy reproduction**
```
import tensorflow as tf

class SampleModel(tf.keras.Model):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.dense_1 = tf.keras.layers.Dense(
            units=10,
            activation=tf.nn.relu
        )

    def call(self, inputs, **kwargs):
        batch_size, height, width, filters = inputs.get_shape().as_list()
        x = tf.reshape(inputs, [batch_size, height * width * filters])
        x = self.dense_1(x)

        return x

def get_model():
    input_shape = (10, 10, 3)
    input = tf.keras.layers.Input(shape=input_shape, batch_size=1)

    x =  tf.keras.layers.Conv2D(
        filters=10,
        kernel_size=3
    )(input)

    sample_model = SampleModel()
    output = sample_model(x)
    model = tf.keras.Model(inputs=input, outputs=output)

    return model

if __name__ == "__main__":
    model = get_model()

    tf.saved_model.save(
        obj=model,
        export_dir="./savemodel_test"
    )


```

**Comment by rmothukuru** [comment]
@kacper-kleczewski,
Could reproduce the error with **`Tensorflow Version 2.5`**. Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/e9b75f4dfe8b144a44db41fbc04154b0/keras_15066.ipynb) of the working code.

**Comment by rchao** [comment]
Can you try with `tf.shape` instead of `get_shape`? Note that it doesn't unpack automatically as a tuple and it doesn't have `as_list` method.

**Comment by kacper-kleczewski** [comment]
`tf.shape` doesn't help because according to TF spec:
`Note: When using symbolic tensors, such as when using the Keras API, tf.shape() will return the shape of the symbolic tensor.`

So the results are:

- first call:

![image](https://user-images.githubusercontent.com/84719017/128513740-a1298b76-866c-45c6-a170-47583dc60858.png)

- second call:

![image](https://user-images.githubusercontent.com/84719017/128513809-6723cf15-f2ca-4b9e-be39-76db14bb4e08.png)

resulta from `tf.shape` doesn't contain shape information of `inputs` tensor shape.

**Comment by kacper-kleczewski** [comment]
> Can you try with `tf.shape` instead of `get_shape`? Note that it doesn't unpack automatically as a tuple and it doesn't have `as_list` method.

Proposed solution doesn't help. Do you have plans to fix issue with get_shape?

**Comment by gowthamkpr** [comment]
@kacper-kleczewski You cannot reshape inputs.get_shape() because you do not know the dimension statically. That is the cause of the error. You can go through similar explanation [here](https://github.com/tensorflow/models/issues/6245#issuecomment-623877638). Thanks!
