### ISSUE TITLE
How can I use multi_gpu in tf.keras?

### ISSUE THREAD

**Issue by llfzllfz** [keras-team/keras#15074]
How can I use multi_gpu in tf.keras?
WARNING:tensorflow:From train_conv.py:214: multi_gpu_model (from tensorflow.keras.utils.multi_gpu_utils) is deprecated and will be removed after 2020-04-01.
And in the documentation, the tf.keras.utils.multi_gpu_model has been removed.

**Comment by rmothukuru** [comment]
@llfzllfz,
You can use [Distribution Strategy](https://www.tensorflow.org/api_docs/python/tf/distribute) as a replacement for **`multi_gpu_model`**.  Please find [the Tutorial](https://www.tensorflow.org/guide/distributed_training) for more information. Thanks!
