### ISSUE TITLE
No information in official doc regarding implementation of class_weight in customized model.fit() method

### ISSUE THREAD

**Issue by n33lkanth** [keras-team/keras#15119]
Hi,
I have customized the standard model.fit() method based on the help/steps described in the official page. Now, I would like to use the class_weight in this customized function but I do not see any help regarding class_weight implementation in official page under the heading Supporting [sample_weight & class_weight](https://www.tensorflow.org/guide/keras/customizing_what_happens_in_fit#supporting_sample_weight_class_weight). Kindly help me to understand how to implement class_weight in this case?

**_Note:_** This issue is raised here after feedback from @saikumarchalla (earlier raised [here](https://github.com/tensorflow/tensorflow/issues/51127))

Best Regards

**Comment by sushreebarsa** [comment]
@n33lkanth Could you please refer to this [thread](https://stackoverflow.com/questions/57934638/how-does-tensorflow-kerass-class-weight-parameter-of-the-fit-function-work) and let us know if it helps?
Thanks!
