### ISSUE TITLE
ResNetV2 implementation problem

### ISSUE THREAD

**Issue by seermer** [keras-team/keras#15167]
**System information**
(not related to installation)
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Windows 10
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.5.0 GPU
- Python version: 3.8

**Describe the expected behavior**
As shown in the image below from **Identity Mappings in Deep Residual Networks** by He et al.\
ResNetV2 block has its preactivation **after** branching (bn-relu-conv-bn-relu-conv are all in contained in residual)
![image](https://user-images.githubusercontent.com/49250812/129236962-d30af2fc-8bac-4ddf-a951-6d986d25bef3.png)
the **only** exception on preactivation is the first block of the first stage\
quote from the original paper:
> For the first Residual Unit (that follows a stand-alone convolutional layer,
> conv1), we adopt the first activation right after conv1 and before splitting into
> two paths

**Describe the current behavior**
ResNetV2 Falsefully put preactivation before branching when channel increases for **all stages**
![image](https://user-images.githubusercontent.com/49250812/129238244-89917129-a60f-45a0-a29c-26cd3134a249.png)
As shown in above image, the output of `ResNet50V2(weights=None).summary()`\
the red arrow I added points to the shortcut path, it is connected to preact_relu, which means the preactivation is done **before** branching to residual and shortcut, which is not true according to the original paper\
a simple drawing representing the first block of each stage in current implementation, which is obviously not equivalent to the image from the original paper:
![image](https://user-images.githubusercontent.com/49250812/129239135-4cf8449e-87c8-439a-89c1-070ccd09411f.png)

**Comment by mattdangerw** [comment]
We are marking this as contributions welcome. It would also be very helpful if others from the community could also help us verify that this is a change we would want.

Thanks for filing!

**Comment by MaanasArora** [comment]
@seermer I checked the official implementation by the authors of the paper and it seems to match what Keras has (see linked pull request). Could you check if there's an error somewhere? Thanks!

**Comment by seermer** [comment]
> @seermer Just to let you know, I checked the official implementation by the authors of the paper and it seems to match what Keras has (see linked pull request).

I am not exactly sure which code/repo are you referring to, I read https://github.com/KaimingHe/resnet-1k-layers but the code README actually says it is "re-implemented by Xiang Ming", who is not the author of the paper, it is just referenced by the original author, so I would not call it an official code.
More importantly, this repo is a re-implementation based on facebook's Torch implementation, NOT based on the code used in the original paper. If you look at the repo by Facebook (where Xiang Ming reimplemented based on), they only used preact **before** split after conv1, all other stages, including when dimension change, they used preact **after** split, you can see the code for this described behavior [here](https://github.com/facebookarchive/fb.resnet.torch/blob/985e569d468d23baeef5b952954dcdf3c61c5e73/models/preresnet.lua#L147-L150) which is exactly what the original paper says. I remain skeptical on why Xiang Ming changed something during re-implementation.

Conclusion:
Although the resnet-1k-layers repo is released by author Kaiming He, it is a re-implementation based on Facebook's repo by non-author. And Facebook has its implementation exactly the same as described in the paper, whereas resnet-1k-layers differs from the paper. **I would say it is better to follow the description on the paper rather than following a repo written by a non-author that differs from the original paper.**

**Comment by MaanasArora** [comment]
@seermer That makes sense; I'll add corrections to my comments in the PR for further discussion. Thanks for the clarification!

**Comment by SuryanarayanaY** [comment]
Hello, Thank you for reporting an issue.

We're currently in the process of migrating the new Keras 3 code base from keras-team/keras-core to keras-team/keras.
Consequently, This issue may not be relevant to the Keras 3 code base . After the migration is successfully completed, feel free to reopen this Issue at keras-team/keras if you believe it remains relevant to the Keras 3 code base. If instead this Issue is a bug or security issue in legacy tf.keras, you can instead report a new issue at [keras-team/tf-keras](https://github.com/keras-team/tf-keras/issues), which hosts the TensorFlow-only, legacy version of Keras.

To know more about Keras 3, please read https://keras.io/keras_core/announcement/
