### ISSUE TITLE
ModuleNotFoundError: No module named 'keras.api'

### ISSUE THREAD

**Issue by YeonSeo-Kim** [keras-team/keras#15175]
Hi I tried to finetune my dataset but I couldn't solve this problem.

My env: 

**Ubuntu 18.04** 

My virtual conda list : 

**cudatoolkit  =  11.2.2 
cudnn  =  8.1.0.77**  
**tensorflow  =   2.6.0**   
**keras =   2.6.0**  

when I run the code, 

`Traceback (most recent call last):
  File "main.py", line 24, in <module>
    import dataloader
  File "/home/ais/Liberty/automl/efficientdet/dataloader.py", line 19, in <module>
    import utils
  File "/home/ais/Liberty/automl/efficientdet/utils.py", line 167, in <module>
    class TpuBatchNormalization(tf.keras.layers.BatchNormalization):
  File "/home/ais/anaconda3/envs/peace/lib/python3.7/site-packages/tensorflow/python/util/lazy_loader.py", line 62, in __getattr__
    module = self._load()
  File "/home/ais/anaconda3/envs/peace/lib/python3.7/site-packages/tensorflow/python/util/lazy_loader.py", line 45, in _load
    module = importlib.import_module(self.__name__)
  File "/home/ais/anaconda3/envs/peace/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)

`**ModuleNotFoundError: No module named 'keras.api'**

I've got those error message. 
I really have no idea about 'keras.api' module. 
Could anyone please tell me what is wrong here??

**Comment by ymodak** [comment]
Can you please provide a minima reproducible code to reproduce the error? Thanks!

**Comment by katoyu** [comment]
@YeonSeo-Kim 
Hi. I ran into the same error.
I consider that this error is specific to the version 2.6.0.
For the first aid, I downgraded the keras version from 2.6.0 to 2.4.0 and it worked fine. Please try it.

**Comment by thierrydecae** [comment]
Hi, i'm having the same error.. here is how to reproduce it:

!pip install --upgrade deepsegment
from deepsegment import DeepSegment

Thanks

**Comment by ymodak** [comment]
> !pip install --upgrade deepsegment
> from deepsegment import DeepSegment

Apparently the problem is not related to TF-Keras and more of external packages dependent on TF Keras.
You may want to post this issue on DeepSegment repo for support. Thanks!

**Comment by chang48** [comment]
I encountered the same issue. The error can be triggered by just executing:

`from deepsegment import DeepSegment`

Unfortunately DeepSegment's author has archived the project, not sure we are getting any help from the author. If the OP is still interested in sentence segmentation, DeepSegment's author recommended [**NNSplit**](https://github.com/bminixhofer/nnsplit).

**Comment by ymodak** [comment]
@chang48 have you tried installing keras 2.6.0 ?

**Comment by chang48** [comment]
@ymodak Indeed, the problem is resolved after installing keras 2.6.0. Thanks

**Comment by RamasubramanianL** [comment]
pip install "keras==2.6.0"

**Comment by space-N** [comment]
My solution is：
TensorFlow=1.14.0
Keras=2.3.0

The reason for the error is that the versions of TensorFlow and Keras do not correspond。

Hope it helps~

**Comment by abhirao317** [comment]
> @YeonSeo-Kim Hi. I ran into the same error. I consider that this error is specific to the version 2.6.0. For the first aid, I downgraded the keras version from 2.6.0 to 2.4.0 and it worked fine. Please try it.
