### ISSUE TITLE
Conv1d throws an error when using 'channels_first' data format

### ISSUE THREAD

**Issue by MoayedHajiAli** [keras-team/keras#15178]
**System information**.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Amazon EC2
- TensorFlow installed from (source or binary): source 
- TensorFlow version (use command below): 2.5.0
- Python version: 3.6.13
- tested on CPU

**Describe the problem**.
calling a Conv1D layer with the channels first data format throws an error of   <br> 
`The Conv2D op currently only supports the NHWC tensor format on the CPU. The op was given the format: NCHW [Op:Conv2D]`

This error is not present when using 'channels_last' data format and produce the expected behavior. The issue is also present in the Conv2d layers.

**Standalone code to reproduce the issue**.
`K.layers.Conv1D(10, 3, data_format='channels_first')(tf.random.normal((10, 3, 10), dtype=tf.float32))`

**Comment by collinzrj** [comment]
The convolution layer of keras use the tensorflow op `conv1d`. From [line 2002-2026](https://github.com/tensorflow/tensorflow/blob/919f693420e35d00c8d0a42100837ae3718f7927/tensorflow/python/ops/nn_ops.py#L2002-L2026) in tensorflow/python/ops/nn_ops
```
if value.shape.ndims in (4, 3, 2, 1, 0, None):
  result = gen_nn_ops.conv2d(
      value,
      filters,
      strides,
      padding,
      use_cudnn_on_gpu=use_cudnn_on_gpu,
      data_format=data_format,
      dilations=dilations,
      name=name)
else:
  result = squeeze_batch_dims(
      value,
      functools.partial(
          gen_nn_ops.conv2d,
          filter=filters,
          strides=strides,
          padding=padding,
          use_cudnn_on_gpu=use_cudnn_on_gpu,
          data_format=data_format,
          dilations=dilations,
      ),
      inner_rank=3,
      name=name)
return array_ops.squeeze(result, [spatial_start_dim])
```
It seems that the implementation of `conv1d` in tensorflow uses `conv2d`, so the error says "Conv2D". Changing to GPU solves this problem, or use 'channels_last' as you said.

**Comment by tilakrayal** [comment]
@MoayedHajiAli ,

Please check the above [comment](https://github.com/keras-team/keras/issues/15178#issuecomment-899087578) and also please take a look at this [issue](https://github.com/tensorflow/tensorflow/issues/32017) [link ](https://github.com/onnx/onnx-tensorflow/issues/535)which is similar.It helps.Thanks!

**Comment by MoayedHajiAli** [comment]
Thank you a lot for your help. I am closing the issue.
