### ISSUE TITLE
temporal 2D sample_weight in fit() causing dimension mismatch

### ISSUE THREAD

**Issue by chjanp** [keras-team/keras#15181]
- Have I written custom code: yes
- OS: Windows 10
- TensorFlow installed from binary (pip)
- TensorFlow version (use command below): 2.4.1 and 2.6.0
- Python version: 3.8
- Exact command to reproduce: See code snippet below

**current behavior**

Background: I am trying to train a temporal model where, for each training sample and each time, I know if
the information contained in the training data is sufficient to learn or not. I would like to encode this
information in a 2D sample_weight, essentially disabling the loss function where I have not (yet) sufficient
information.

Problem: Specifying a 2D sample_weight with temporal dimension for the fit() function causes a dimension mismatch.

The code below reproduces the issue for a simple toy problem.

**expected behavior**

This should work, according to [https://keras.io/api/models/model_training_apis/]:
>> sample_weight: [...] in the case of temporal data, you can pass a 2D array with shape 
>> (samples, sequence_length), to apply a different weight to every timestep of every sample. 

**[Contributing]**
- Do you want to contribute a PR? (yes/no): no

**Standalone code to reproduce the issue**.

import numpy as np
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
    
n = 100 #number of samples
nt = 64 #number of time steps
nx = 2  #number of channels

X = np.random.randn(n,nt,nx)      #generate a toy training data set including a time dimension
Y = np.sum(X,2)                   #generate toy labels which are very easy to learn
W = np.ones((n,nt))               #initialize weights for training
for i in range(n):                #now for each training sample
    t0 = np.random.randint(nt)    #take a random time 
    Y[i,:t0] = np.random.rand(t0) #modify the lables so that they are impossible to learn up to this time
    W[i,:t0] = 0                  #but also set the corresponding weights to 0

inp = Input(shape=X.shape[1:])    #create a simple neural network that consists of a single linear layer
m = Model(inp, Dense(1)(inp))
m.compile(Adam(0.1), loss="mse", sample_weight_mode="temporal")

m.fit(X,Y, batch_size=10, epochs=50, verbose=1, sample_weight=W) #this line causes the error:

"""
ValueError: Can not squeeze dim[1], expected a dimension of 1, got 64 for 
'{{node mean_squared_error/weighted_loss/Squeeze}} = Squeeze[T=DT_FLOAT, squeeze_dims=[-1]](IteratorGetNext:2)' 
with input shapes: [10,64].
"""

**Comment by tilakrayal** [comment]
@chjanp,
It was not the batch size that was causing it, but rather missing singleton dimension in the weights, so the weights tensor should have been [1, Height, Width, 1] and squeezing is applied on the channel dimension.
When using keras to load the model (load_model()) please replace that with tf.keras.models.load_model().

Also the provided labels are of the wrong shape. Please refer to this doc link for the reference and try to convert the labels to integers.

`train_labels = np.argmax(train_labels, axis=1)`

Thank you!
