### ISSUE TITLE
ValueError when accessing submodules of compiled subclassed tf.keras model

### ISSUE THREAD

**Issue by mmilosav** [keras-team/keras#15183]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): various including macOS 11.5.1 and Colab
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): various including 2.5.0 and 2.6.0
- Python version: various including 3.8.5
- Bazel version (if compiling from source): N/A
- GPU model and memory: N/A
- Exact command to reproduce: 

**Describe the problem**.

Attempting to access the submodules property of a _compiled_ subclassed tf.keras.Model raises a ValueError.

**Describe the current behavior**.

Attempting to access the submodules property of a _compiled_ subclassed tf.keras.Model raises a ValueError.

**Describe the expected behavior**.

Accessing the submodules property of an _uncompiled_ subclassed model, or a _compiled Sequential_ model, returns the submodules (layers).  The same should work for a _compiled_ subclassed model.

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no): no
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**.

```python
import tensorflow as tf


class Model(tf.keras.Model):
    def __init__(self):
        super().__init__()
        self.dense = tf.keras.layers.Dense(units=1)

    def call(self, inputs, training=None, mask=None):
        return self.dense(inputs)


model = Model()

print(model.submodules)  # prints out tensorflow.python.keras.layers.core.Dense 

model.compile(loss='mse', optimizer='sgd')

print(model.submodules)  # raises ValueError
```

**Source code / logs**.

```
(<tensorflow.python.keras.layers.core.Dense object at 0x7f3e0c2f55d0>,)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/tensorflow/python/module/module.py in _flatten_module(module, recursive, predicate, attribute_traversal_key, attributes_to_ignore, with_path, expand_composites, module_path, seen)
    369       leaves = nest.flatten_with_tuple_paths(
--> 370           prop, expand_composites=expand_composites)
    371     except Exception as cause:  # pylint: disable=broad-except

5 frames
TypeError: '<' not supported between instances of 'Dense' and 'Model'

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/six.py in raise_from(value, from_value)

ValueError: Error processing property '_compiled_trainable_state' of <WeakKeyDictionary at 0x7f3e0c2ea550>
```

**Comment by tilakrayal** [comment]
@jvishnuvardhan ,
I was able to reproduce the issue in tf v2.4,v2.6 and nightly.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/21e79f78bfed98c0cdf813590435cd19/untitled57.ipynb).

**Comment by jvishnuvardhan** [comment]
I think this may be intended behavior.

triage notes: 
Submodules of a subclassed model can be accessed before compilation but not after `model.compile`

**Comment by tilakrayal** [comment]
@mmilosav,
From Keras' perspective, calling **submodule** is expected to return the "Sequence of all sub-modules" as stated in the below document irrespective of the order. Also Submodules of a model cannot be accessed after the compilation.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/module/module.py#L191

Thank you!
