### ISSUE TITLE
Allow ```StringLookup``` and ```TextVectorization``` use multi output mode .

### ISSUE THREAD

**Issue by DachuanZhao** [keras-team/keras#15198]
**Describe the feature and the current behavior/state**.

```StringLookup``` and ```TextVectorization``` can only output result with one output mode . Considering that when I would to train a FM model or Wide&Deep model , I should use ```multi-hot``` output for LR and ```int``` output for embedding layer . I should init two ```StringLookup``` like this :
```Python
def get_string_lookup_layer(vocabulary_list,output_mode):
    vocabulary_list = list(set(vocabulary_list))
    max_tokens = len(vocabulary_list) + 1
    indexer = preprocessing.StringLookup(max_tokens=max_tokens,mask_token=None,output_mode=output_mode) 
    indexer.adapt(vocabulary_list)
    return indexer

vocabulary_list = ["title",...]
_input = tf.keras.Input(shape=(1,))
string_layer1 = get_string_lookup_layer(vocabulary_list,"int")
string_layer2 = get_string_lookup_layer(vocabulary_list,"multi_hot")
int_output =  string_layer1(_input )
multi_output =  string_layer2(_input )
...
```

**Will this change the current api? How?**
Change the string parameter ```output_mode``` to list parameter  ```output_modes``` .

**Who will benefit from this feature?**
Everyone who should use both ```multi-hot``` and ```int``` output .

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**

- Do you want to contribute a PR? (yes/no): no

**Comment by mattdangerw** [comment]
Closing this for now, as the solution above (using a StringLookup and CategoryEncoding) should be sufficient. Please reopen if there are issues.
