### ISSUE TITLE
Performance issues in the program

### ISSUE THREAD

**Issue by DLPerf** [keras-team/keras#15191]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras):no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):win10
- TensorFlow installed from (source or binary):source
- TensorFlow version (use command below):tf2.60
- Python version:python3.7
- Bazel version (if compiling from source):no
- GPU model and memory:no need
- Exact command to reproduce:no need

**Describe the problem**.
 in the definition of `run_dataset_implementation` ,
keras/layers/preprocessing/benchmarks/image_preproc_benchmark.py
[ds = ds.map(img_augmentation)](https://github.com/keras-team/keras/blob/05048b7c0d56c4c3c90460c31b5fa2406a0ea1e2/keras/layers/preprocessing/benchmarks/image_preproc_benchmark.py#L89) was called without **num_parallel_calls**

**Describe the current behavior**.
Missing parallelization operation,it will significant lower your programs.
Here is [the documemtation of tensorflow](https://tensorflow.google.cn/api_docs/python/tf/data/Dataset?hl=en#map) to support this thing.

**Describe the expected behavior**.
it will speed up the program

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no):yes
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing):Just have to add **num_parallel_calls** into map

Looking forward to your **reply**. Btw, I am very glad to create a PR to fix it if you are too busy.

**Comment by jvishnuvardhan** [comment]
@DLPerf  Please check the following paragraph that explains `num_parallel_calls` depend on few parameters and depending on your application and data, you can choose `num_parallel_calls`. You could also use `tf.data.AUTOTUNE` which automatically decide how many parallel threads can be run at a given time.

> Choosing the best value for the num_parallel_calls argument depends on your hardware, characteristics of your training data (such as its size and shape), the cost of your map function, and what other processing is happening on the CPU at the same time. A simple heuristic is to use the number of available CPU cores. However, as for the prefetch and interleave transformation, the map transformation supports `tf.data.AUTOTUNE` which will delegate the decision about what level of parallelism to use to the tf.data runtime.

Please let us know what you think. If you want to update some docs, please feel free to raise a PR. Thanks!

**Comment by DLPerf** [comment]
Thanks for your reply @jvishnuvardhan.
 According to the doc you cited,  we should call `map` with num_parallel_calls=tf.data.AUTOTUNE [here](https://github.com/keras-team/keras/blob/05048b7c0d56c4c3c90460c31b5fa2406a0ea1e2/keras/layers/preprocessing/benchmarks/image_preproc_benchmark.py#L89)?
Please correct me if I miss something.

**Comment by jvishnuvardhan** [comment]
@DLPerf Correct. If you want TF to control `num_parallel_calls `, then you need to call with `num_parallel_calls=tf.data.AUTOTUNE`. 

Please close the issue if this was resolved for you. Thanks!

**Comment by DLPerf** [comment]
@jvishnuvardhan Sorrry, maybe I explained not clearly. I mean that the code in keras/keras/layers/preprocessing/benchmarks/image_preproc_benchmark.py [line 89] (https://github.com/keras-team/keras/blob/05048b7c0d56c4c3c90460c31b5fa2406a0ea1e2/keras/layers/preprocessing/benchmarks/image_preproc_benchmark.py#L89) should be fixed with `num_parallel_calls=tf.data.AUTOTUNE` ? Otherwise it will run `map` sequentially even in multi-cores machine, which will take more time.
