### ISSUE TITLE
Namespace for custom objects not included in serialised config

### ISSUE THREAD

**Issue by peteboothroyd** [keras-team/keras#15192]
This is not a contribution.

**System information**.
- TensorFlow version: 2.6.0

**Describe the problem**.

Custom object serialisation is inconsistent when using `tf.keras.utils.custom_object_scope` as compared to `tf.keras.utils.register_keras_serializable`. `custom_object_scope` is not able to use namespaces for different custom objects, which risks name collisions.

**Describe the current behavior**.

```python
import tensorflow as tf

class Serialisable:
    def __init__(self, arg1, arg2):
        self.arg1 = arg1
        self.arg2 = arg2
    def get_config(self):
        return {'arg1': self.arg1, 'arg2': self.arg2}

custom_objects = {
    'custom_package>Serialisable': Serialisable,
}
serialisable = Serialisable('arg1', 2)

with tf.keras.utils.custom_object_scope(custom_objects):
  serialised = tf.keras.utils.serialize_keras_object(serialisable)

# note that the class_name field does not contain the namespace
serialised
>>> {'class_name': 'Serialisable', 'config': {'arg1': 'arg1', 'arg2': 2}}

with tf.keras.utils.custom_object_scope(custom_objects):
    deserialised = tf.keras.utils.deserialize_keras_object(serialised) # throws ValueError
```

**Describe the expected behavior**.

```python
# compare to what happens with tf.keras.utils.register_keras_serializable

tf.keras.utils.register_keras_serializable(package='custom_package')(Serialisable)

# class_name now contains the namespace information
serialised_after_registration = tf.keras.utils.serialize_keras_object(serialisable)
>>> {'class_name': 'custom_package>Serialisable', 'config': {'arg1': 'arg1', 'arg2': 2}}

# and deserialisation works as expected
with tf.keras.utils.custom_object_scope(custom_objects):
    deserialised_after_registration = tf.keras.utils.deserialize_keras_object(serialised)
```

So what I would like is that the names provided in the custom_object_scope keys be used when serialising, rather than just the object name.

**Source code / logs**.

I believe that this discrepancy happens because the custom object context has [two objects](https://github.com/keras-team/keras/blob/05048b7c0d56c4c3c90460c31b5fa2406a0ea1e2/keras/utils/generic_utils.py#L51-L52) tracking the registered objects and names. These map from name->object and from object->name, however they are not kept in sync. `register_keras_serializable` [updates both](https://github.com/keras-team/keras/blob/05048b7c0d56c4c3c90460c31b5fa2406a0ea1e2/keras/utils/generic_utils.py#L393-L394), however `custom_object_scope` [only updates one](https://github.com/keras-team/keras/blob/05048b7c0d56c4c3c90460c31b5fa2406a0ea1e2/keras/utils/generic_utils.py#L92) of the mappings. This means that there is a miss when looking up the name in the other mapping [during serialisation](https://github.com/keras-team/keras/blob/05048b7c0d56c4c3c90460c31b5fa2406a0ea1e2/keras/utils/generic_utils.py#L416). Either custom object scope should be changed to update both mappings, or I think it would likely be less error prone to only maintain one mapping, and derive both views from one source of truth to avoid any future divergences.

Aside: `get_registered_name` is [called](https://github.com/keras-team/keras/blob/05048b7c0d56c4c3c90460c31b5fa2406a0ea1e2/keras/utils/generic_utils.py#L509) twice during serialisation, and the [second](https://github.com/keras-team/keras/blob/05048b7c0d56c4c3c90460c31b5fa2406a0ea1e2/keras/utils/generic_utils.py#L533) looks redundant.

**Comment by sushreebarsa** [comment]
@peteboothroyd Sorry for the late response!
Could you please check this [link](https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object) to know more info to pass the custom objects and let us know if it helps ?
Thank you!

**Comment by peteboothroyd** [comment]
@sushreebarsa thanks, I don't think that addresses the issue I raised though. I've just checked and this still reproduces on 2.11

**Comment by tilakrayal** [comment]
Hello, Thank you for reporting an issue.

We're currently in the process of migrating the new `Keras 3` code base from **keras-team/keras-core** to **keras-team/keras.**
Consequently, This issue may not be relevant to the `Keras 3 `code base. After the migration is successfully completed, feel free to reopen this issue at **keras-team/keras** if you believe it remains relevant to the `Keras 3` code base. 
If instead this issue is a bug or security issue in legacy **tf.keras**, you can instead report a new issue at [keras-team/tf-keras](https://github.com/keras-team/tf-keras/issues), which hosts the TensorFlow-only, legacy version of Keras.

To know more about `Keras 3,` please take a look at https://keras.io/keras_core/announcement/. Thank you!
