### ISSUE TITLE
Add layer activations to keras.utils.plot_model and model_to_dot

### ISSUE THREAD

**Issue by ddrakard** [keras-team/keras#15211]
**System information**.

TensorFlow version (you are using): tf_nightly (keras_nightly-2.7.0.dev2021081907)
Are you willing to contribute it (Yes/No) : Yes

**Describe the feature and the current behaviour/state**.

`keras.utils.plot_model` generates a diagram of a model's architecture. This is very useful for debugging and publishing. If layer activations (as opposed to standalone activation layers) are used, for example `tf.keras.layers.Dense(10, activation='relu')`, it does not show the whole architecture because they are not shown. I propose to add an additional parameter: `layer_activations: bool = False` to `keras.utils.plot_model` and `keras.utils.model_to_dot` which when set to True will show the activation for each layer that has one set.

**Will this change the current api? How?**

Yes. It will add an extra parameter, `layer_activations: bool = False`, to both `keras.utils.plot_model` and `keras.utils.model_to_dot`. This is a backwards compatible api change.

It will also potentially formalise more concretely the `activation` attribute as an optional public API of `Layer`. I am not familiar enough with the design of Keras to know the current status of this attribute. There will be no problem for layers that have this attribute or do not have an activation. Layers which store an activation in a different way will be treated incorrectly.

**Who will benefit from this feature?**

Any users who want to generate a complete architecture diagram using `plot_model`, and who specify activation functions by argument, will benefit from this feature.

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**

- Do you want to contribute a PR? (yes/no): yes
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing):

I believe the solution is sufficiently specified by the requirements. In case the `layer_activations` argument is False the modified methods should have identical to current behaviour. This will ensure any problems displaying activation functions in unusual cases can be avoided by simply not using this feature.

**Comment by ddrakard** [comment]
Pull request #15233 implements this feature.

**Comment by tilakrayal** [comment]
@ddrakard ,
The issue will move to closed status once the PR is merged.

**Comment by ddrakard** [comment]
This feature is implemented in commit https://github.com/keras-team/keras/commit/6caa1073be16075dd41014cc7c7bc2a373dbba01
