### ISSUE TITLE
Error: "Failed to connect to all addresses", TPU on Colab

### ISSUE THREAD

**Issue by Tylersuard** [keras-team/keras#15214]
When I attempt to train on Colab using Keras and TPU, I get this error and training stops before the first epoch.

Link to code for reproduction: https://colab.research.google.com/drive/1ddTaQNmKbapwDPhrPlDKpnoCb8Exa_XI?usp=sharing

**Comment by tilakrayal** [comment]
@Tylersuard ,
Can you please take a look at this links for similar error.[Link1](https://stackoverflow.com/questions/59823424/grpc-14-unavailable-failed-to-connect-to-all-addresses),[Link2](https://stackoverflow.com/questions/42397370/distributed-tensorflow-save-fails-no-device).It helps.Thanks
