### ISSUE TITLE
Is there a way in Keras to apply class_weight functionality if I modify model.fit() method ?

### ISSUE THREAD

**Issue by n33lkanth** [keras-team/keras#15221]
Hi There,
I am working on a model which has 4 outputs. Each output gives prediction for (say) 6 sound events (each of the 4 output layer has 6 neurons ) for same input but different resolution. Now, the logic is I should give more preference to the branch which gives smallest loss by multiplying the loss with 1, for other three branch losses I need to multiply loss with 0.1. To achieve this I have modified the standard model.fit() method as explained [here](https://www.tensorflow.org/guide/keras/customizing_what_happens_in_fit#supporting_sample_weight_class_weight). I am pasting my custom method below. Now, my training is working properly but due to highly imbalance dataset, I am getting poor score. So, I wants to use the class_weight functionality. In the standard model.fit() methof it is easy as we need to just pass the dictionary of class weight but I am not sure how to pass class_weight in modified model.fit() method. I am using standard BCE loss function. Kindly help me to understtand how to achieve this and if possible, how to calculate class weight also.
Below is the custom method to overwrite the standard model.fit() method

`import tensorflow as tf
from tensorflow import keras

bce_loss = tf.keras.losses.BinaryCrossentropy(reduction=tf.keras.losses.Reduction.NONE)

epoch_loss_avg = tf.keras.metrics.BinaryCrossentropy(name='train_loss')
epoch_accuracy = tf.keras.metrics.BinaryAccuracy(name='train_accuracy')

val_loss_avg = tf.keras.metrics.BinaryCrossentropy(name='loss')
val_accuracy = tf.keras.metrics.BinaryAccuracy(name='accuracy')

val_acc = dict()`
`class CustomModel(keras.Model):
    def train_step(self, data):
        x, y = data
        # print('Inside custom train: ', np.shape(x), np.shape(y))

        alpha = 0.1
        loss_list = []
        loss = tf.Variable(0, dtype='float32')
        wt_loss = tf.Variable(0, dtype='float32')
        y_pred_all = []

        with tf.GradientTape() as tape:
            tape.watch(loss_list)
            for spl_idx in tf.range(1 if tf.shape(x)[0] == None else tf.shape(x)[0]):
                # sample_loss = tf.convert_to_tensor([])
                if variableInput:
                    x_spl = tf.reshape(x[spl_idx],
                                       (1, tf.shape(x[spl_idx])[0], tf.shape(x[spl_idx])[1], tf.shape(x[spl_idx])[2]))
                else:
                    x_spl = tf.reshape(x[spl_idx], (1, tf.shape(x)[1], tf.shape(x)[2], tf.shape(x)[3]))

                y_pred = self(x_spl, training=True)  # Forward pass
                y_pred_all.append(tf.reshape(tf.reduce_mean(tf.cast(y_pred, tf.float32), axis=0),
                                             (tf.shape(tf.reduce_mean(tf.cast(y_pred, tf.float32), axis=0))[0] *
                                              tf.shape(tf.reduce_mean(tf.cast(y_pred, tf.float32), axis=0))[1],
                                              tf.shape(tf.reduce_mean(tf.cast(y_pred, tf.float32), axis=0))[2])))

                # print(np.shape(y[spl_idx]),np.shape( y_pred))
                loss_element = bce_loss(y[spl_idx], tf.cast(y_pred, tf.float32))  # (4, 1, 512) == (scales, file, time_frames)

                # Sample level loss calculation for each scale (take mean of all time frame losses to get sample level scalar loss for each scale)
                sample_loss = [tf.reduce_mean(loss_element[0], axis=1),
                               tf.reduce_mean(loss_element[1], axis=1),
                               tf.reduce_mean(loss_element[2], axis=1),
                               tf.reduce_mean(loss_element[3], axis=1)]  # (1, 512) -----mean(axis=1)--> (1)

                id = tf.argmin(sample_loss)
                for i, ele in enumerate(sample_loss):
                    if i == id:
                        sample_loss[i] = tf.multiply(sample_loss[i], 1)
                    else:
                        sample_loss[i] = tf.multiply(sample_loss[i], alpha)

                # loss = tf.add(loss, tf.add(tf.add(tf.add(sample_loss[0], sample_loss[1]), sample_loss[2]), sample_loss[3]))
                loss = tf.add(tf.add(tf.add(sample_loss[0], sample_loss[1]), sample_loss[2]), sample_loss[3])
                # loss_list.append(tf.reduce_mean(sample_loss))
                loss_list.append(loss)

            wt_loss = tf.reduce_mean(loss_list)

        # Compute gradients
        trainable_vars = self.trainable_variables
        # loss = tf.reduce_mean(loss) # Calculating mean loss for current batch

        # gradients = tape.gradient(loss, trainable_vars)
        gradients = tape.gradient(wt_loss, trainable_vars)

        # Update weights
        self.optimizer.apply_gradients(zip(gradients, trainable_vars))

        epoch_loss_avg.update_state(tf.cast(y, tf.float32), y_pred_all)
        epoch_accuracy.update_state(tf.cast(y, tf.float32), y_pred_all)

        return {m.name: m.result() for m in [epoch_loss_avg, epoch_accuracy]}

    def test_step(self, data):
        x, y = data  # Unpack the data   x: (8, 512, 128, 1)    y: (8, 512, 6)
        y_pred = self(x, training=False)

        if len(tf.shape(y)) == 3 and tf.shape(y)[2] == 1 and tf.shape(y_pred)[3] == 1:
            y = tf.reshape(y, (tf.shape(y)[0], tf.shape(y)[1] * tf.shape(y)[2]))
            y_pred = tf.reshape(y_pred,(tf.shape(y_pred)[0], tf.shape(y_pred)[1],
                                        tf.shape(y_pred)[2] * tf.shape(y_pred)[3]))

        # bce_loss(y, y_pred) # Updates the metrics tracking the loss
        y_pred_all = tf.reduce_mean(y_pred, axis=0) # Taking mean of all 4 scales for each files
        val_loss_avg.update_state(tf.cast(y, tf.float32), tf.cast(y_pred_all, tf.float32))  # Update the metrics.
        val_accuracy.update_state(tf.cast(y, tf.float32), tf.cast(y_pred_all, tf.float32))  # Update the metrics.

        return {m.name: m.result() for m in [val_loss_avg, val_accuracy]}

    @property
    def metrics(self):
        # We list our `Metric` objects here so that `reset_states()` can be
        # called automatically at the start of each epoch
        # or at the start of `evaluate()`.
        # If you don't implement this property, you have to call
        # `reset_states()` yourself at the time of your choosing.
        return [epoch_loss_avg, epoch_accuracy, val_loss_avg, val_accuracy]`

**Comment by n33lkanth** [comment]
Hi,
Any thought about this problem?

**Comment by MrinalTyagi** [comment]
Hello @n33lkanth , as shown here every class that subclasses from keras.Model class will get the .fit() method in which you can pass the class_weight parameter like you do in the original .fit() method. The only difference will be I think that you have to utilize these class weights in the custom .fit() method regarding your requirements. Let me know if this helps.

**Comment by n33lkanth** [comment]
Hi @MrinalTyagi, Yes you are right that I can pass the class_weight in model.compile() method but when I am trying to pass class weights for all four outputs I am getting error that class_weight is not supported for the multi-output model.

**Comment by MrinalTyagi** [comment]
@n33lkanth Try having a look at the following. [Applying class weights to a multi-output model](https://datascience.stackexchange.com/questions/41698/how-to-apply-class-weight-to-a-multi-output-model). I think u are currently encountering the same issue described here. Let me know if this helps.

**Comment by n33lkanth** [comment]
Hi @MrinalTyagi,
Yes, you are right. However, I am getting the following error:

`ValueError: `class_weight` is only supported for Models with a single output`

**Comment by MrinalTyagi** [comment]
@n33lkanth could you please share a colab file of the code for me to have a look?

**Comment by sushreebarsa** [comment]
@n33lkanth 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!
