### ISSUE TITLE
InputSpec argument ignored

### ISSUE THREAD

**Issue by rschumi0** [keras-team/keras#15225]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras: no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.4.0-rc4-71-g582c8d236cb 2.4.0
- Python version: 3.8.5

**Describe the problem**.
The `ndim` argument of the [InputSpec](https://www.tensorflow.org/api_docs/python/tf/keras/layers/InputSpec?hl=ja) of a layer seems to be ignored when the `shape` argument is set. The issue is illustrated in the following example with a simple custom layer. 

**Standalone code to reproduce the issue**.
```
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np

class TempLayer(tf.keras.layers.Activation):
    def __init__(self):
        super(keras.layers.Activation, self).__init__()
        self.input_spec = keras.layers.InputSpec(ndim=5, shape=(1,2))
    def call(self, input_1, training=False):
        return input_1
        
model = keras.Sequential([TempLayer()])
x = tf.constant([[1.4392, 1.9206]])
print (np.array2string(model.predict(x,steps=1), separator=', '))
```

**Comment by tilakrayal** [comment]
@jvishnuvardhan ,
I was able to reproduce the issue in tf v2.5,v2.6 and nightly.Please find the gist [here](https://colab.research.google.com/gist/tilakrayal/2fed28117cf080e7e3ba4037c3cf7104/15225.ipynb).

**Comment by LukeWood** [comment]
Hey there - what is the expected behavior here?  Would we expect to error out?  is `ndim=5` compatible with a shape of `ndim=2`?

**Comment by LukeWood** [comment]
Would you be open to contributing a PR raising an error when `ndim` and `shape` mismatch?  Also, can you check whether or not the model fails when an incorrect shape is used per the input spec?  thanks @rschumi0

**Comment by tilakrayal** [comment]
@rschumi0,
I tried to execute the code with the ndim=5 and ndim=2 & the code was executed without any issues & output provided by the code was also similar. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/6eb5f6458b79a052e23e825b0bc955f4/untitled1115.ipynb). 

Also please confirm the expected behavior of the code  and raise the PR for the model fail and also when the shape was not right. Thank you!
