### ISSUE TITLE
ConvLSTM2D layer wrong computation

### ISSUE THREAD

**Issue by rschumi0** [keras-team/keras#15224]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras: no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.4.0-rc4-71-g582c8d236cb 2.4.0
- Python version: 3.8.5

**Describe the problem**.
There seems to be something wrong with the computation of the ConvLSTM2D layer. I tried to do the computation manually for a simplified example and I come to a different result. I think there might be a bug in the last round of the layer. The issue is illustrated in the example below.

**Describe the expected behavior**.
The output that I expected from the simple example model is `[[[[[   0.], [   8.]]], [[[ 0.],[1053.]]]]]`, but instead the actual output is `[[[[[   0.], [   8.]]], [[[ 512.],[1053.]]]]]`.

**Standalone code to reproduce the issue**.
```
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np
tf.keras.backend.set_floatx('float64')
model = keras.Sequential([
keras.layers.ConvLSTM2D(1, (1, 2), return_sequences=True, padding='valid', strides=(1,1),recurrent_activation='linear', activation='linear',  input_shape=(2, 1, 3, 1))])
w = model.get_weights()
w[0] = np.array([[[[1, 1, 1, 1]],[[1, 1, 1, 1]]]])
w[1] = np.array([[[[1, 1, 1, 1]],[[1, 1, 1, 1]]]])
w[2] = np.array([0, 0, 0, 0])
model.set_weights(w)
x = tf.constant([[[[[0], [0], [2]]], [[[0], [0], [1]]]]])
print (np.array2string(model.predict(x,steps=1), separator=', '))
```

**Comment by tilakrayal** [comment]
@jvishnuvardhan ,
I was able to reproduce the issue in tf v2.5.v2.6 and nightly.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/69627faf0e3237ceea5f2f406d7f21e3/untitled60.ipynb).

**Comment by jvishnuvardhan** [comment]
@rschumi0 Why do you think this is a wrong computation? Can you please check with couple of more computations. Thanks!

**Comment by rschumi0** [comment]
@jvishnuvardhan I investigated the intermediate steps of the layer and performed the calculations as described in the [reference paper](https://arxiv.org/abs/1506.04214v1) from the documentation. I tried many examples, and in many cases the implementation seems to be fine, but in a number of cases there were unexpected results. I suspect there might be an issue with the dataflow between the rounds of the algorithm, e.g., the inputs or weights might not be passed on as they should be.

**Comment by jvishnuvardhan** [comment]
@rschumi0 I quickly changed part of weights from 

`w[1] = np.array([[[[1, 1, 1, 1]],[[1, 1, 1, 1]]]])`

to 

`w[1] = np.array([[[[1, 1, 1, 1]],[[0, 0, 0, 0]]]])`

With that change, the output is what you are expecting 
```
[[[[[   0.],
    [   8.]]],


  [[[   0.],
    [1053.]]]]]
```

Can you please share other cases where you think you got unexpected results. Thanks!

**Comment by rschumi0** [comment]
@jvishnuvardhan Sorry, but adopting the weights doesn't help for this issue. There seems to be something wrong with the computation within the layer, so it doesn't make sense to change the weights to get an expected results. It would be important to have a closer look at the implementation of the layer and, e.g., check if the data flow of all variables and weights is correct and if the implementation really follows the algorithm as it was published in the original paper.

**Comment by qlzh727** [comment]
I think the result is working as intended.

Please note that the first element in the 2nd timestep result is not 0 since the state from the first step is used as the input state for the second step.

Please make sure to provide detailed justification/math formula about your expected result.
