### ISSUE TITLE
Stateful LSTM gives different predictions for different input shapes

### ISSUE THREAD

**Issue by eumel2** [keras-team/keras#15232]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in Keras)**: custom code
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04
-   **TensorFlow installed from (source or binary)**: binary
-   **TensorFlow version (use command below)**: 2.5.0
-   **Python version**: 3.8.10
-   **Bazel version (if compiling from source)**: -
-   **GPU model and memory**: RTX 3060 12GB

### Describe the problem
I made a stateful LSTM and trained it, so far so good. (The result of this training is bad but not in scope) Now im evaluating it in two different ways.
1. model.reset_state()
2. model.predict(*my_data of size (1,100,1)*)
OR
2. for x in *my_data of size (100,1,1,1)*: model.predict(x)

I would expect the result to be exactly the same since internally it passes through 100 timesteps of the same data. This is also confirmed by the states (model.layers[0].states[0]) of both approaches beeing exactly the same. Yet the actual predicted output is different by a small margin

### Source code / logs
```
# model-setup
model = tf.keras.Sequential()
model.add(LSTM(200, batch_input_shape = (1,1,1), return_sequences=True, stateful=True))
model.add(LSTM(100, return_sequences=True, stateful=True))
model.add(LSTM(50, return_sequences=True, stateful=True))
model.add(LSTM(1, stateful=True))
loss = 'mse'
opt = tf.keras.optimizers.Adam(learning_rate=0.001, clipnorm=1.)
model.compile(loss=loss, optimizer=opt)

# data i tested on basiccally 3 stack sin waves scaled to [0,1]
data_3 = np.sum(np.random.random((3,1))*5*np.sin((np.tile(np.linspace(0,500,3000),(3,1))+np.random.random((3,1))*5)*np.random.random((3,1))),axis=0).reshape(-1,1)
data_3 = ((data_3-np.min(data_3))/(np.max(data_3)-np.min(data_3))).reshape(3000,1,1,1)
xtrain = data_3[1:]
ytrain = data_3[:-1]

# training
for i in range(10):
      print("Epoch:", i+1)
      model.reset_states()
      loss = 0
      for x, y in zip(xtrain,ytrain):
           loss += model.train_on_batch(x,y)
      print(loss/len(xtrain))

# prediction, i do some splitting into sets for the real prediction but for a minimally working example the base set is reusable
model.reset_states()
my_data1 = data_3[:100]
for x in my_data1:
    print(model.predict(x))
a = model.layers[0].states[0].numpy()
model.reset_states()
my_data2 = data_3[:100].reshape(1,100,1)
print("in one: ", model.predict(my_data2))
b = model.layers[0].states[0].numpy()
print(a-b)
```

**Comment by eumel2** [comment]
Im not sure if im supposed to but ill bump this so it doesnt get closed automatically.

**Comment by tomerk** [comment]
~1e5 is definitely within numerical float differences that we expect. Running the code in colab appears to produce zero numerical difference.

I'm going to close this issue as it appears to be w/in expectations for numerical difference due to grouped computations w/ fewer operations vs. more operations in a python for loop.
