### ISSUE TITLE
Interested in adding RegNets to tf.keras.applications

### ISSUE THREAD

**Issue by AdityaKane2001** [keras-team/keras#15240]
**System information**.

TensorFlow version (you are using): 2.6.0
Are you willing to contribute it (Yes/No) : Yes

**Describe the feature and the current behavior/state**.

RegNets are used in self supervised vision works like SEER. They are also highly efficient and scalable architectures. I intend to train and incorporate RegNet-{X, Y, Z} in `tf.keras.applications`. I think having models that are fast, scalable and efficient be ready to use will greatly help the TF community.

**Will this change the current api? How?**
There will be new handles, namely `tf.keras.applications.RegNet{X, Y, Z}` in the API.

**Who will benefit from this feature?**
The entire TF Keras community.

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**

- Do you want to contribute a PR? (yes/no): yes

**Current Progress**

I have implemented the building blocks of RegNetY in [AdityaKane2001/regnety](https://github.com/AdityaKane2001/regnety). I have also trained 4 variants of RegNetY on ImageNet-1k and uploaded them to TFHub during Google Summer of Code 2021. 

[Published collection on TFHub](https://tfhub.dev/adityakane2001/collections/regnety/1)
[Repo link](https://github.com/AdityaKane2001/regnety)
[Project report link](https://adityakane2001.github.io/opensource/gsoc2021report)

/cc @sayakpaul

**Comment by AdityaKane2001** [comment]
@ymodak 

I'd really like if you (and the Keras team) could look into this as soon as possible, so that I can start relevant development and training. 
There are 36 models to train (12 each of X, Y and Z) and each one takes roughly >20 hours. So it'd be great if we could start soon.

**Comment by AdityaKane2001** [comment]
@fchollet 

Could you please take a look at this? Thanks.

**Comment by fchollet** [comment]
Hi there,

Yes, we'd welcome such a contribution. However, we have no availability to work on it, so you'd have to open a PR yourself (we will review the PR and guide you). Do you have an ImageNet checkpoint available for the model?

**Comment by sayakpaul** [comment]
@fchollet you probably missed out but @AdityaKane2001 has actually trained the models he's talking about as a part of his GSoC 2021 project (I was one of his mentors). 

The entire collection is available [here](https://tfhub.dev/adityakane2001/collections/regnety/1) on TensorFlow Hub. However, he wants to work on a more streamlined version of RegNets (model building wise) and train those variants once again. He has Cloud TPU access and a reproducible training pipeline already developed (refer [here](https://github.com/AdityaKane2001/regnety)) for that. 

So, if you provide the green signal he could start working on it ASAP. I'll also keen to take part in the reviews :)

**Comment by AdityaKane2001** [comment]
@fchollet 

Thanks for the reply.

To summarize, the objectives of my contribution are as follows:
- Add [RegNets](https://arxiv.org/pdf/2003.13678.pdf) to tf.keras.applications
- Train these models on ImageNet-1k or ImageNet-21k (please tell what would be preferable)

[Here](https://user-images.githubusercontent.com/64411306/132623704-1b18097f-c7fb-4c24-8f81-603462742c81.png) is the basic structure of RegNetX in case you want to take a look.

This would require writing a lot of code and substantial training (there are 36 variants of them). Thus, it would be really helpful if you could give a concrete good-to-go so I can start working on it. This is also the reason I didn't directly open a PR.

/cc @sayakpaul

**Comment by innat** [comment]
@AdityaKane2001 cc. @rchao @fchollet 
It's a promising model and would be good to have it. However, does `RegNet` have enough citations to be part of the `keras` application? If I'm not mistaken it currently has around 16 citations which is less than 50 citations threshold.

**Comment by sayakpaul** [comment]
I am not sure which citation stats you referred to @innat but it definitely seems wrong:

![Screenshot 2021-09-18 at 8 42 21 PM](https://user-images.githubusercontent.com/22957388/133893558-f3ba9ce2-7ee5-45b5-af01-03d0629b1a42.png)

![Screenshot 2021-09-18 at 8 41 47 PM](https://user-images.githubusercontent.com/22957388/133893561-302cb14d-bfcc-4b11-90af-34122fb61c06.png)

**Comment by AdityaKane2001** [comment]
@innat 

In my honest opinion, Regnets are celebrated for their efficiency and scalability. They beat ResNet and Efficientnet scores using lesser flops than them, especially at higher flop regimes. 

![IMG_20210918_205020.jpg](https://user-images.githubusercontent.com/64411306/133893773-cf96d9d8-5cf6-4e03-b4ba-67556022c3de.jpg)

@sayakpaul 

Thanks for the clarification!

**Comment by innat** [comment]
@AdityaKane2001 
Yes, my information source was wrong. Thanks to @sayakpaul.  

FYI, Please don't get too excited to see the claim to beat EfficientNet. In fact, they don't really respect the scaling and training process in the original EfficientNet paper during comparison. Facebook claimed beating EfficientNet with RegNet but people like Ross Wightman (timm) foumd the opposite during retraining especially for larger input resolution.

**Comment by sayakpaul** [comment]
@haifeng-jin could you provide an update on this? Should we start working on the PR?

**Comment by AdityaKane2001** [comment]
@haifeng-jin 

Yes, he has given the green light. We are now working on the PR : #15419

**Comment by AdityaKane2001** [comment]
Merged in #15702.
