### ISSUE TITLE
Loading weights from tf.compat.v1.keras.layers.CuDNNLSTM to tf2.keras.layers.LSTM

### ISSUE THREAD

**Issue by vikasrupadhyay** [keras-team/keras#15258]
Hi, 

I am new to Keras and have been using tf.compat.v1.keras.layers.CuDNNLSTM  in my network architecture.

It seems to be a faster implementation for training compared to the tf2 LSTM ( Cudnn ) version. 

Is there a way to load the weights from a model trained with tf.compat.v1.keras.layers.CuDNNLSTM  to tf2's LSTM. Loading the weights directly leads to errors. 

Is there a recommended approach to do this as direct loading doesnt work.

**Comment by vikasrupadhyay** [comment]
@yuyang-huang and @bzamecnik : Any Ideas ?

**Comment by bzamecnik** [comment]
It's working for me well without any problems. In TF 2 the default values are compatible with CuDNN. Make sure the parameters in the old and new model match. If your RNN is within a nested Functional model, make sure to upgrade to TF 2.6 or apply a small patch. See  https://github.com/tensorflow/tensorflow/issues/49214. Possibly post a sample code and the error message.

**Comment by kumariko** [comment]
@vikasrupadhyay Could you please check https://github.com/keras-team/keras/issues/15258#issuecomment-908160181 and let us know if your issue resolved ? Thanks!
