### ISSUE TITLE
ModuleNotFoundError: No module named 'keras.api'

### ISSUE THREAD

**Issue by angelorobo** [keras-team/keras#15262]
**Describe the problem**.

I'm using Macbook Pro to run a server which was used to deploy on AWS.

I have received an unknown error when running airflow. We do install Keras.

- `RUN pip install "Keras==2.3.1"`
- `RUN pip install "apache-airflow[celery,devel,postgres,redis,s3,ssh]==1.10.9"`
- `RUN pip install "keras-models==0.0.7"`
- `RUN pip install "tensorflow_cpu>=2.1.0"`

But we are getting the missing keras.api module. I can't find keras.api was used anywhere.

    ml.scheduler_1   |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    ml.scheduler_1   |   File "/robo/airflow/dags/general/video_migration.py", line 5, in <module>
    ml.scheduler_1   |     from flows.operators import video_process as videos
    ml.scheduler_1   |   File "/robo/flows/operators/video_process.py", line 11, in <module>
    ml.scheduler_1   |     from serving.models.ali_audit import AliVideoAbuseDetection
    ml.scheduler_1   |   File "/robo/serving/models/__init__.py", line 83, in <module>
    ml.scheduler_1   |     _module = loader.find_module(module_name).load_module(module_name)
    ml.scheduler_1   |   File "/robo/serving/models/places365.py", line 8, in <module>
    ml.scheduler_1   |     from keras_models.models.pretrained import vgg16_places365
    ml.scheduler_1   |   File "/usr/local/lib/python3.7/site-packages/keras_models/models/__init__.py", line 1, in <module>
    ml.scheduler_1   |     from .linear import build as LinearModel
    ml.scheduler_1   |   File "/usr/local/lib/python3.7/site-packages/keras_models/models/linear.py", line 2, in <module>
    ml.scheduler_1   |     from keras import Model
    ml.scheduler_1   |   File "/usr/local/lib/python3.7/site-packages/keras/__init__.py", line 3, in <module>
    ml.scheduler_1   |     from . import utils
    ml.scheduler_1   |   File "/usr/local/lib/python3.7/site-packages/keras/utils/__init__.py", line 26, in <module>
    ml.scheduler_1   |     from .vis_utils import model_to_dot
    ml.scheduler_1   |   File "/usr/local/lib/python3.7/site-packages/keras/utils/vis_utils.py", line 7, in <module>
    ml.scheduler_1   |     from ..models import Model
    ml.scheduler_1   |   File "/usr/local/lib/python3.7/site-packages/keras/models.py", line 12, in <module>
    ml.scheduler_1   |     from .engine.training import Model
    ml.scheduler_1   |   File "/usr/local/lib/python3.7/site-packages/keras/engine/__init__.py", line 8, in <module>
    ml.scheduler_1   |     from .training import Model
    ml.scheduler_1   |   File "/usr/local/lib/python3.7/site-packages/keras/engine/training.py", line 14, in <module>
    ml.scheduler_1   |     from . import training_utils
    ml.scheduler_1   |   File "/usr/local/lib/python3.7/site-packages/keras/engine/training_utils.py", line 17, in <module>
    ml.scheduler_1   |     from .. import metrics as metrics_module
    ml.scheduler_1   |   File "/usr/local/lib/python3.7/site-packages/keras/metrics.py", line 1850, in <module>
    ml.scheduler_1   |     BaseMeanIoU = tf.keras.metrics.MeanIoU
    ml.scheduler_1   |   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/util/lazy_loader.py", line 62, in __getattr__
    ml.scheduler_1   |     module = self._load()
    ml.scheduler_1   |   File "/usr/local/lib/python3.7/site-packages/tensorflow/python/util/lazy_loader.py", line 45, in _load
    ml.scheduler_1   |     module = importlib.import_module(self.__name__)
    ml.scheduler_1   |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    ml.scheduler_1   |     return _bootstrap._gcd_import(name[level:], package, level)
    ml.scheduler_1   | ModuleNotFoundError: No module named 'keras.api'

**Comment by kumariko** [comment]
@angelorobo Could you please refer to [**`link`**](https://github.com/keras-team/keras/issues/4889) and let us know if it helps. Thanks!

**Comment by angelorobo** [comment]
@kumariko We already install Keras at the local env through dockerfile.

RUN pip install "Keras==2.3.1"

Is it possible that the models were built on Linux and can not be re-used on Macbook?

**Comment by ymodak** [comment]
I suspect that you have incompatible TF and Keras versions installed in your system. What TF version are you using?

**Comment by angelorobo** [comment]
- `RUN pip install "Keras==2.3.1"`
- `RUN pip install "apache-airflow[celery,devel,postgres,redis,s3,ssh]==1.10.9"`
- `RUN pip install "keras-models==0.0.7"`
- `RUN pip install "tensorflow_cpu>=2.1.0"`

@ymodak These are the install statements in the dockerfile.

**Comment by ymodak** [comment]
> @ymodak Is it possible that the pre-built models were built on Linux and can not be re-used on Macbook?

You can use models built on Linux with MacOS or vice versa. 

Can you try changing your import from `keras` to `tensorflow.keras`?

**Comment by angelorobo** [comment]
@ymodak We don't directly import keras. This is an import statement related to keras in our code.

`from keras_models.models.pretrained import vgg16_places365`

In vgg16_places365, it imports these

```
from keras import backend as K
from keras.layers import Input
from keras.layers.core import Activation, Dense, Flatten
from keras.layers.pooling import MaxPooling2D
from keras.models import Model
from keras.layers import Conv2D
from keras.regularizers import l2
from keras.layers.core import Dropout
from keras.layers import GlobalAveragePooling2D
from keras.layers import GlobalMaxPooling2D
from keras_applications.imagenet_utils import _obtain_input_shape
from keras.engine.topology import get_source_inputs
from keras.utils.data_utils import get_file
from keras.utils import layer_utils
from keras.preprocessing import image
from keras.applications.imagenet_utils import preprocess_input
```
