### ISSUE TITLE
Add `ResNet [18, 34] ` to keras.applications

### ISSUE THREAD

**Issue by innat** [keras-team/keras#15269]
**System information**.

TensorFlow version (you are using): 2.5
Are you willing to contribute it (Yes/No): Yes. 

**Describe the feature and the current behavior/state**.

Currently, we have `ResNet 50/101/152`. However, sometimes it's needed to test the idea initially with some small models quickly and for that, if we want to choose a res-net-based model we can't just pick 50 because it's still too heavy to train. That's why we think it would be nice to have resnet18 and resnet34 as well with the keras packages. 

**Will this change the current api? How?**
Yes. It will include

```
from tensorflow.keras.applications.resnet18 import ResNet18
from tensorflow.keras.applications.resnet34 import ResNet34
```

**Who will benefit from this feature?**
ML engineers and researcher who uses `tf.keras`. 

**Others**
Others implementation: https://github.com/qubvel/classification_models

**Comment by quantumalaviya** [comment]
Can I work on this?

**Comment by innat** [comment]
@quantumalaviya of course. Just send a PR. It should be welcomed.

**Comment by quantumalaviya** [comment]
So, I just wrote the code but I notice some differences in the number of parameters when compared to https://github.com/qubvel/classification_models. Any suggestions on how to add weights?

**Comment by rchao** [comment]
Thanks for opening the issue. Can you provide a paragraph as a proposal for justifying adding this model? If you can provide some context of how widely this is used or some citation, that would be helpful.

**Comment by innat** [comment]
@rchao 
FYI, These have been asked before. [#151](https://github.com/keras-team/keras-applications/issues/151)

@quantumalaviya could you please check out [this implementation](https://github.com/keras-team/keras-contrib/tree/master/keras_contrib/applications), it already exists in `keras-contrib` but is not included in `keras`.

**Comment by breadbread1984** [comment]
https://github.com/breadbread1984/resnet18-34 . you may try this implement.

**Comment by KaleabTessera** [comment]
+1

**Comment by innat** [comment]
@breadbread1984 It would be nice to send PR. WDYT?

**Comment by innat** [comment]
@LukeWood Will the new model be added to `keras.application` or `keras_cv`?

**Comment by LukeWood** [comment]
for now keras.applications.

**Comment by zaccharieramzi** [comment]
In the end, we added the model in keras-cv, see [this PR](https://github.com/keras-team/keras-cv/pull/805#event-7441560537)
