### ISSUE TITLE
Add `SE-Net` and `SE-ResNeXt ` to keras.applications

### ISSUE THREAD

**Issue by innat** [keras-team/keras#15267]
**System information**.

TensorFlow version (you are using): 2.5
Are you willing to contribute it (Yes/No): Yes. As much as possible. 

**Describe the feature and the current behavior/state**.

Model like [`SEResNeXt`](https://arxiv.org/abs/1709.01507)( [50, 101] ) and **SE-Net[154]** are absent (for unknown reason to me) in `keras` application along with other models. So, I think, It would be a good addition to the `keras` core library. FYI, these models are widely used in Kaggle competition.

**Will this change the current api? How?**
Yes. It will change as follows 

```
tensorflow.keras.applications.SEResNeXt50
tensorflow.keras.applications.SEResNeXt101
tensorflow.keras.applications.SENet152`
```

**Who will benefit from this feature?** 
ML engineers and researcher who uses `tf.keras`. 

**Others**

Others implementation: https://github.com/qubvel/classification_models

**Comment by rchao** [comment]
Thanks for opening the issue. Can you provide a paragraph as a proposal for justifying adding this model? If you can provide some context of how widely this is used or some citation, that would be helpful.

**Comment by innat** [comment]
@rchao Thanks for asking. 
Replying to all your requests, [#15267](https://github.com/keras-team/keras/issues/15267), [#15268](https://github.com/keras-team/keras/issues/15268), [#15269](https://github.com/keras-team/keras/issues/15269), [#15270](https://github.com/keras-team/keras/issues/15270)

There is nothing new additional argument for justification I could use compared to the arguments that apply for available models like `inceptionv3`, `resent` `densenet` etc. I'm not fully sure why you're seeking a proposal as you mentioned, so please let me know why these models are not worthy to add and need proposals (I'm seriously don't know if there is any known issue. Is it for lack of man-power or something else! If `keras` follows some policy here to add new models). 

However, I can give some overview of how these models are widely used. For example, let's say in kaggle competition, these **SENet** models are used frequently used as part of the experiments, [link](https://www.kaggle.com/c/ranzcr-clip-catheter-line-classification/discussion/210016), amazing [notebooks](https://www.kaggle.com/debarshichanda/seresnext50-but-with-attention/notebook), [link](https://www.kaggle.com/ammarali32/seresnet152d-inference-single-model-lb-96-2), [link](https://www.kaggle.com/yasufuminakama/ranzcr-resnext50-32x4d-starter-training). I can provide more where these models are used actively. Along with these models, [RegNets](https://github.com/keras-team/keras/issues/15240), ResNeSt, [NFNet](https://github.com/keras-team/keras/issues/15229) is also worthy to add. All of these models are widely used in the Computer Vision competitions in Kaggle.

The point is, those models which are not available in `keras.applications`, a user needs to adopt other sources, and sometimes it's not always feasible to use those implementations and needs to support along with the new `tf. keras` version.

**Comment by innat** [comment]
@rchao 
Could you please give some feedback on this?

**Comment by rchao** [comment]
@innat thanks for the information, and sorry for the delayed response here. The general criteria for adding a new application is that the model has 50 or more citations on the paper, and the requester can provide a PR for us to review. In this case, the PR should include an ImageNet checkpoint. 

Can you show us the citation count or other reference demonstrating the popularity, and we'll assess to let you know whether we should proceed?

**Comment by innat** [comment]
@rchao Thanks for the response. 
For citation, I think it's not required to state the citation count for Issue [#15269](https://github.com/keras-team/keras/issues/15269) as we have already `ResNet 50/101`. However,

- For [`SENet`](https://github.com/hujie-frank/SENet?utm_source=catalyzex.com#trained-models) based models such as `SENet`, `SE-ResNet`, `SE-ResNeXt`, could you please check the citation count here, [source](https://ieeexplore.ieee.org/document/8578843/citations?tabFilter=papers), I think it's about ~1900 citation.

- For the `ResNeXt` model, could you please check here, [source](https://ieeexplore.ieee.org/document/8100117), I think it's about ~1000 citations?

Is this something you asked? Please let me know. ( And just to inform, I've created different issue regarding these models so that if PRs are welcomed, the contributor can work on specifically. )

**Comment by rchao** [comment]
Thanks @innat. Does this model have an imagenet checkpoint as well?

**Comment by innat** [comment]
@rchao yes, (afaik) they do. [Here](https://github.com/qubvel/classification_models) is the third-party implementation, and here is the list of [imagenet weights](https://github.com/qubvel/classification_models/releases/tag/0.0.1).

**Comment by gcunhase** [comment]
Any update on this?

**Comment by tanzhenyu** [comment]
I will transfer this issue to KerasCV, if there's no objection
