### ISSUE TITLE
Flatten layer should support sparse tensors

### ISSUE THREAD

**Issue by thomasbbrunner** [keras-team/keras#15276]
**System information**.

TensorFlow version (you are using): 2.6.0
Are you willing to contribute it (Yes/No) : depends

**Describe the feature and the current behavior/state**.

Currently, the keras.layers.Flatten layer cannot process sparse tensors. Yes, the documentation states that only some keras layers support sparse tensors, but Flatten is a common first layer in NNs and should be able to handle sparse tensors.

This code describes it:
```
import tensorflow as tf
import numpy as np

x = np.random.random_integers(0, 1, size=(64, 100, 100))

x_tensor = tf.convert_to_tensor(x)
x_sparse = tf.sparse.from_dense(x)

flatten = tf.keras.layers.Flatten()
dense = tf.keras.layers.Dense(100, activation='relu')

# works
dense(flatten(x_tensor))

# works
dense(tf.sparse.reshape(x_sparse, (64, 100*100)))

# does not work (should work!)
dense(flatten(x_sparse))

# Even with InputLayer and sparse=True
# works
input_layer = tf.keras.layers.InputLayer(input_shape=(100, 100))
dense(flatten(input_layer(x_tensor)))

# does not work (should work!)
input_layer = tf.keras.layers.InputLayer(input_shape=(100, 100), sparse=True)
dense(flatten(input_layer(x_sparse)))
```

**Will this change the current api? How?**

No, I'm guessing the layer can check it it is sparse and then apply the tf.sparse.reshape function. All this is done in the back without changes to the user.

**Who will benefit from this feature?**

Users who use sparse tensors, who won't have to spend time debugging code :)

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**

- Do you want to contribute a PR? (yes/no): maybe, would like to know first if the devs would be interested in this feature
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution (if contributing):

**Comment by rchao** [comment]
Triage note: can you describe more about what you think makes sense for the semantics? If you can create a short paragraph as a proposal we'll run through it with api owners to conclude whether we should have one. Thanks for opening the issue.
