### ISSUE TITLE
Incomplete Convolutional docs

### ISSUE THREAD

**Issue by pokecheater** [keras-team/keras#15289]
Hey Keras-Team,

As I noticed the convolutional layers documentation seems to be incomplete.

Concret I am missing the layer DepthwiseConv1D in your documentation. In code this layer is available but not mentioned in the layers overview:
![image](https://user-images.githubusercontent.com/20928617/131623414-67b8d7cb-d146-4762-9d8d-28c582261978.png)
(https://keras.io/api/layers/convolution_layers/)

![image](https://user-images.githubusercontent.com/20928617/131623040-db7f8b0f-a1a2-4257-b078-06dd461673b6.png)

The same is true for TransposeConvolution1D case:
![image](https://user-images.githubusercontent.com/20928617/131623568-27daa239-1195-4587-af7e-ddca153f5d5f.png)

Thx in advance for adding them <3

**Comment by ymodak** [comment]
DepthwiseConv1D is new API and only available via pip install tf-nightly.
See https://www.tensorflow.org/api_docs/python/tf/keras/layers/DepthwiseConv1D
