### ISSUE TITLE
load_model JSONDecodeError

### ISSUE THREAD

**Issue by DinhNguyen1996** [keras-team/keras#15281]
When I use 
import tensorflow as tf
from tensorflow import keras
from keras.models import load_model

model = load_model('D:/Dinh-NDecT/AI/Model/model_keras_fb_fn_120_2')
![image](https://user-images.githubusercontent.com/32614709/131430453-0906603b-151f-4af8-a9d9-6745908e38d9.png)

I don't know to fix. I load model in local but in colab that OK. Please help me.
My model : 
![image](https://user-images.githubusercontent.com/32614709/131430623-9d8ec8d0-cf46-4648-b00a-d16b892d76aa.png)

**Comment by kumariko** [comment]
@DinhNguyen1996 please do let us know which version of tf you are using. Thanks!

**Comment by DinhNguyen1996** [comment]
> @DinhNguyen1996 please do let us know which version of tf you are using. Thanks!

tf 2.6.0 and keras 2.6.0
I fixed the problem. I run and save model in local when I load model is OK,. But when l down load from coblab but it does't. I don't know why.

**Comment by ymodak** [comment]
You may try loading the model using https://www.tensorflow.org/api_docs/python/tf/keras/models/model_from_json
Also see similar [post](https://github.com/keras-team/keras/issues/6971#issuecomment-469671605). Thanks!
