### ISSUE TITLE
Bug with optimizer_v2.OptimizerV2.set_weights method 

### ISSUE THREAD

**Issue by ymodak** [keras-team/keras#15298]
Cross posted from https://github.com/tensorflow/tensorflow/issues/50859
Original Author : @suneeta-mall

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
 None
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux (Ubuntu/Debina)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- NA
- TensorFlow installed from (source or binary):
Binary
- TensorFlow version (use command below):
- Python version: 2.4.1 & 2.4.x
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
11.0
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`
2.4.1

**Describe the current behavior**
I am seeing an issue in setting Adam optimizer weights in Optimizer v2 implementation. Looking at the code here https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/optimizer_v2/adam.py#L154-L160, it seems to be able to set the weights the current optimizer must have been initialized and set the right size in terms of array length. If this assertion is correct setting weights `on_train_begin` or prior to the first gradient calculation is a bit too soon to set optimizers weights. 
In earlier versions, this was not a problem, and optimizer set_weights use to work at `on_train_begin`.  
I suspect this is a bug in how slots and weights are internally structured.

Code to reproduce the issue is here: 
https://gist.github.com/suneeta-mall/b6086a6b252075f48936a5f80f040b77
To run try:
```
python debug_optimizer_issue.py
```
& then try again:
```
python debug_optimizer_issue.py --start_epoch 2
```

The first run finishes and the second one, where its suppose to start from epoch 2,  fails with error as:
```
ValueError: You called `set_weights(weights)` on optimizer Adam with a  weight list of length 9, but the optimizer was expecting 0 weights. Provided weights: [120, array([[ 0.0000000e+00,  0.0000000e+00,  0.0...
```

I looked around in Adam V2 code to see if there are any other APIs that can help with creating slots etc but I didn't see any that does not require knowledge of internal implementation details (I think). 

As a crazy thought, I use array extension on actual weights to bypass the bug in set_weights like this:
```
model.optimizer.weights.extend(_ref_model.optimizer.get_weights())
```
This lets past the training regime, but the next model save errors into:
```
AttributeError: 'numpy.int64' object has no attribute 'name'
```

Worth noting, the same problem exists with SGD, which is met with the following related error:
```
ValueError: You called `set_weights(weights)` on optimizer SGD with a  weight list of length 1, but the optimizer was expecting 0 weights. Provided weights: [120]...
```

*Please note*: This code is written for TF2, and will not work as in TF1. Also, in earlier versions of TF 2.1 support for loading h5 weights in distributed scope was not there. In that case, a callback was necessary to set the weights, for more see here https://github.com/tensorflow/tensorflow/issues/30850. 

Also worth noting that, I appreciate that the instead of setting weights, I can just load the model like following:
```
        if args.start_epoch:
            model = load_model(f"model_{args.start_epoch}.h5")
            # deduced_epoch = int(_ref_model.optimizer.iterations.numpy() // (len(train_images) / args.batch_size))
            # if deduced_epoch != args.start_epoch:
            #     raise ValueError()
            # model.set_weights(_ref_model.get_weights())
            # model.optimizer.set_weights(_ref_model.optimizer.get_weights())
```
and that works fine. But for the use case I have I need to set the weights and optimizer weights explicitly. 

**Describe the expected behavior**
I expect the set_weights to work naturally. 
**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by irasit** [comment]
@chenmoneygithub Are we planing to fix this issue?
It is still needed for some cases we like to want to reuse original optimizer's weights in a new optimizer and continue training. 
For example: model with optimizer is loaded from a checkpoint, and we want to continue training with a different optimizer ( like horovod.DistributedOptimizer). 
```
        model = load_model(f"model.h5")
        new_opitmizer = get_new_opimtizer(config)
        new_opitmizer.set_weights(model.optimzier.get_weights())
        model.compile(optimizer=new_opitmizer)
```

**Comment by chenmoneygithub** [comment]
I may not understand your use case: could you explain why you want to use two types of optimizers before and after saving?

**Comment by suneeta-mall** [comment]
@chenmoneygithub Can I please ask why the original issue is closed?

**Comment by irasit** [comment]
@chenmoneygithub 
It is mainly for model fine tuning or incremental training use cases. We like to load a compiled and trained model from checkpoing.h5 file. Copy the optimizer weights to a new horovod distributed optimizer and continue the training job. 
```
        model = load_model(f"model.h5")
        old_weights = model.optimzier.get_weights()
        new_opitmizer = horovod.DistributedOptimizer(...)
        model.compile(optimizer=new_opitmizer)

       # this will fail because the new optimizer do not have weights initialized.
        model.set_weights(old_weights) 
```

We found a work around like below, but just like to know if it can be fixed officially. 
```
        model = load_model(f"model.h5")
        old_weights = model.optimzier.get_weights()
        new_opitmizer = horovod.DistributedOptimizer(...)
        model.compile(optimizer=new_opitmizer)

        # use fake gradient to let optimizer init the wieghts.
        grad_vars = model.trainable_weights
        zero_grads = [tf.zeros_like(w) for w in grad_vars]
        model.optimizer.apply_gradients(zip(zero_grads, grad_vars))

        # This will work because the new optimizer is initialized.
        model.set_weights(old_weights)
```
