### ISSUE TITLE
MAINT: Replace os.path.join with tf.io.join

### ISSUE THREAD

**Issue by adriangb** [keras-team/keras#15300]
Now that https://github.com/tensorflow/tensorflow/pull/48125 is merged, we should also replace `os.path.join` usage in this repo with the new `tf.io.join` method.

**Comment by jvishnuvardhan** [comment]
@adriangb I see that the PR got merged. Can we close this issue? Thanks!

**Comment by qlzh727** [comment]
This should be fixed now.

**Comment by adriangb** [comment]
Sorry for not tagging it, thanks folks!
