### ISSUE TITLE
Add the source code Link of the corresponding API!

### ISSUE THREAD

**Issue by innat** [keras-team/keras#15308]
**URL(s) with the issue:**.

Please provide a link to the documentation entry, for example, https://keras.io/guides/customizing_what_happens_in_fit/

**Description of the issue (what needs to be changed):**.
In the `tf` document, the GitHub source link is provided along with each API. But on the `keras` website, the link is absent. We're considering this is an issue because many times we need to go through the source code but because of not having them on the `keras` website, we need to do either a good search or visit the `tf` document. Here is one example: 

<img src="https://user-images.githubusercontent.com/17668390/132003253-4bd8b6ff-6de6-4b0d-bfbd-2a9f952de7ac.png" width="600" height="350" />

But in keras documents, it's absent. So, whenever we need to inspect the source code, we further need to leave the keras site. That's why I think, it's better to have this option there. 

<img src="https://user-images.githubusercontent.com/17668390/132003257-bea0d228-641a-437f-9133-0f4c4eda2b50.png" width="600" height="350" />

**Comment by AdityaKane2001** [comment]
@innat 

I think this is intentional. Keras doesn't want you to worry about the implementational details because it has such a nice abstraction of things. Thus, it makes sense to keep Keras docs for quick reference and TF docs to be more contributor oriented.

**Comment by innat** [comment]
@AdityaKane2001 

> Thus, it makes sense to keep Keras docs for quick reference and TF docs to be more contributor oriented.

Thanks for your comment. I understand your point. And it might be true for `tf < 2`, right before when `keras` didn't tightly integrate into `tf`. But now, `keras` has the nature of **progressively disclosure of complexity**, for example, now we can do the custom training loop in `keras` etc. Also, now `keras` moved back to its original repo (as said) to keep the `keras` development more concrete and focus; [keras.io](https://keras.io/) traffic is too high these days. So, just considering it for quick reference can be a wrong said. 

> Also, TF docs contain nightly APIs whereas Keras docs contain only stable release APIs. Thus, it is assumed that there will be no need to tweak the internal code.

If we assume that, `keras` gives stable release and for that, we don't need to tweak the internal code - **IMHO**, that's a bad argument. 

---


In end, I would say that having a source link would not break anything but surely add some value.

**Comment by innat** [comment]
Closing this, it's been addressed. Thanks.
