### ISSUE TITLE
Problem for passing integer seed value for tensorflow.keras.layers.experimental.preprocessing functions in .map function

### ISSUE THREAD

**Issue by Kaveh8** [keras-team/keras#15314]
I am trying to create a map function for my dataset, in order to augment images. For each sample, I want to generate a random seed and pass it to the `preprocessing` layers as `seed` argument. I get error when passing seed as a tensor, since the code in the preprocessing layers is like `if seed:` and it says tensors are not allowed for a bool operation. On the other hand, if I try to pass it like int, it gives me another error. 

My map function is like:
```
from tensorflow.keras.layers.experimental import preprocessing as pre
def augmentation(img, label):
    global_seed = int(tf.random.uniform([], dtype=tf.int32, minval=0, maxval=100)) # is it possible to pass it without error?
    random_flip = pre.RandomFlip("horizontal", seed=global_seed)
   ....
```
And I am trying to pass `global_seed` without error. I want a different seed for each call (each sample). 
I call this function like this:
```
train_set = tf.data.TFRecordDataset(str(tf_train_path + os.sep + "train.tfrec"), compression_type="GZIP", 
                                    num_parallel_reads=AUTO)
train_set = train_set.shuffle(512)\
                        .map(deserialize_example ,num_parallel_calls=AUTO)\
                        .map(augmentation, num_parallel_calls=AUTO)
```
The error is:
```
OperatorNotAllowedInGraphError: in user code:

    <ipython-input-34-6866cc669c6e>:6 augmentation  *
        random_flip = pre.RandomFlip("horizontal", seed=global_seed)
    /opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/layers/preprocessing/image_preprocessing.py:401 __init__  **
        self._rng = make_generator(self.seed)
    /opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/layers/preprocessing/image_preprocessing.py:1390 make_generator
        if seed:
    /opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:885 __bool__
        self._disallow_bool_casting()
    /opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:492 _disallow_bool_casting
        self._disallow_in_graph_mode("using a `tf.Tensor` as a Python `bool`")
    /opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:481 _disallow_in_graph_mode
        " this function with @tf.function.".format(task))

    OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.
```

**Comment by sushreebarsa** [comment]
@Kaveh8 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by Kaveh8** [comment]
@sushreebarsa  Thanks for your response. [Here](https://colab.research.google.com/drive/12h9BO2ymiF0OSTSR60eEzIHdewch3IgP?usp=sharing) I have provided a notebook in colab, to reproduce the issue. I get another error message in colab, anyway the error still exist.

**Comment by innat** [comment]
@Kaveh8 cc: @sushreebarsa 
These are the layers: RandomFlip, RandomRotation, etc. So, I think you need to call them in such ways. Something like 

```python
class auglayer(tf.keras.layers.Layer):
    def __init__(self):
        super().__init__()
        self.seed = int(tf.random.uniform([], dtype=tf.int32, minval=0, maxval=100))
        self.random_flip = pre.RandomFlip("horizontal", seed=self.seed)
        self.random_rotate = pre.RandomRotation(factor=0.01, seed=self.seed)

    def call(self, inputs):
        x = self.random_flip(inputs)
        x = self.random_rotate(x)
        return x 

augs = tf.keras.Sequential([auglayer()])
```
```python
train_ds_rand = (
    tf.data.Dataset.from_tensor_slices((x_train, y_train))
    .batch(100)
    .map(lambda x, y: (augs(x), y),num_parallel_calls=AUTO)
    .prefetch(AUTO)
    )
```

**Comment by Kaveh8** [comment]
@innat Thanks for your response. I finally did it like what you have done In Kaggle. But I think it should be fine to use them in a function (not a class), like other layers in Keras. I wonder why I get errors in a map function without subclassing (I know it will be run in a graph mode, and the error may be related for graph mode) but no error when implemented as layer subclass.

**Comment by innat** [comment]
@Kaveh8 
I think a functional approach can also be done. However, in your gist above, there is some issue, for example, initializing the layers and calling them stuff. Instead of what you've done on gist, you should call them as follows 

```python
def apply_augment(x):
    x = keras_aug.RandomFlip(..., seed=set_seed)(x)
    x = keras_aug.RandomRotation(..., seed=set_seed)(x)
    x = keras_aug.RandomTranslation(..., seed=set_seed)(x)
    x = keras_aug.RandomContrast(..., seed=set_seed)(x)
    x = keras_aug.RandomRotation(..., seed=set_seed)(x)
    return x 
```



I've posted a possible solution [here](https://www.kaggle.com/ipythonx/tf-3d-2d-model-for-brain-tumor-classification/comments#1503883), hope it helps.

**Comment by Kaveh8** [comment]
@innat Thanks for your solution. In this way, the key to resolve the error is wrapping function with `tf.numpy_function`. Then I can set seed like what you said. But using `tf.numpy_function` or `py_function` is not allowed with TPUs. As you may see, I have used TPUs in my code. I am still curious to know is it possible to run this function (preprocessing layers) on `.map` and with TPU? Are they compatible with TPUs?

**Comment by innat** [comment]
Not sure exactly, it's known [issue](https://github.com/tensorflow/tensorflow/issues/38762#issuecomment-688247286) currently.

**Comment by Kaveh8** [comment]
@innat Yes. I know it is an issue for `py_function` with TPU. So, I considered to not use them in my code. I haven't used any raw python or numpy functions in my code, so I don't need to wrap my function with `py_function` or `numpy_function`. Now, I think `preprocessing` layers are using this underneath, and so they are not available on TPUs. But, how is it possible when using subclassing approach? I'm really get confused.

**Comment by innat** [comment]
@Kaveh8 cc @sushreebarsa @k
It should be available on all devices either CPU/GPU/TPU. TPU has some issue with `numpy_function`. It also has some issues with the `keras` generator or `tf. data.from_generator`. If we try to use a custom layer, it should work on TPU. The problem is with `tf. Data` and its strict graph execution. Even with `.run_functions_eagerly(True)` doesn't work here. 

The following approach may work on all devices even with TPU and Not within the `tf. data` API. 

```python
class Keras3DAugmentation(tf.keras.layers.Layer):
    def __init__(self):
        super(KerasAug, self).__init__()
        self.rng = tf.random.Generator.from_seed(global_seed)
        print('init seed ', self.rng)

    def apply_augment(self, sample):
        set_seed = self.rng.make_seeds()[0]
        print('dynamic seed ', set_seed)
        x = keras_aug.RandomFlip(, seed=set_seed)(sample)
        x = keras_aug.RandomRotation(, seed=set_seed)(x)
        x = keras_aug.RandomTranslation(, seed=set_seed)(x)
        x = keras_aug.RandomContrast(, seed=set_seed)(x)
        return x 
        
    def call(self, inputs):
        splitted_modalities = tf.split(tf.cast(inputs, tf.float32), 
                  input_channel, axis=-1)
        splitted_modalities = [tf.squeeze(i, axis=-1) \
                  for i in splitted_modalities] 
   
        # Will contain the augmented outputs
        flair = []
        t1w = []
        t1wce = []
        t2w = []

        flair = tf.expand_dims(self.apply_augment(splitted_modalities[0]), axis=-1)
        t1w   = tf.expand_dims(self.apply_augment(splitted_modalities[1]), axis=-1)
        t1wce = tf.expand_dims(self.apply_augment(splitted_modalities[2]), axis=-1)
        t2w   = tf.expand_dims(self.apply_augment(splitted_modalities[3]), axis=-1)

        image = tf.stack([flair, t1w, t1wce, t2w], axis=-1)
        image = tf.reshape(image, [-1, input_height, input_width, 
                                   input_depth, input_channel])
        return image
```

```python
 keras_image_augmentation = tf.keras.Sequential(
        [
           Keras3DAugmentation()
        ],
        name='keras_augment_layers'
    )

samples = tf.ones((2, input_height, input_width,  input_depth, input_channel))
keras_image_augmentation(samples).shape

(2, 256, 256, 24)
dynamic seed  Tensor("keras_aug_4/strided_slice:0", shape=(1,), dtype=int64)
(2, 256, 256, 24)
dynamic seed  tf.Tensor([-5927004847686741621], shape=(1,), dtype=int64)
dynamic seed  tf.Tensor([4629789014631912635], shape=(1,), dtype=int64)
dynamic seed  tf.Tensor([-344729292210807444], shape=(1,), dtype=int64)
dynamic seed  tf.Tensor([-3758752224390587847], shape=(1,), dtype=int64)
TensorShape([2, 256, 256, 24, 4])
```

Though I didn't test end-to-end. But I think it's possible to use this layer inside the model definition class and not in the data pipeline and also may need to run the code eagerly.

```python

model = tf.keras.Sequential([
       Keras3DAugmentation(),
       OTHER_3D_LAYERS,
       Last_Layer
   ]
)
```

But it's not good or best practice.

**Comment by Kaveh8** [comment]
@innat  It is about `seed`. When implementing layer subclassing, setting `seed` is done outside of the `tf.data` API (`seed` is set within `__init__` when creating object from class), and in `tf.data` only the `call` function is executed, without any problem. But when we implement it as a function, passing `seed` also, will be executed within `tf.data`, and it leads to an error. I want to know, is it possible to pass `seed` argument within `tf.data` API or not? And is it a bug or a reasonable behavior? Thanks.

**Comment by innat** [comment]
@Kaveh8 not sure if it's a bug or else. I've raised a related [issue](https://github.com/keras-team/keras/issues/15358).

**Comment by qlzh727** [comment]
@Kaveh8, the seed value for preprocessing layer is expected to be a integer, and not a tensor. If you would like to have some deterministic behavior, you can refer to https://github.com/keras-team/keras/issues/15358 as well.

Assign to @mattdangerw who works on KPL.

**Comment by SuryanarayanaY** [comment]
Hello, Thank you for reporting an issue.

We're currently in the process of migrating the new Keras 3 code base from keras-team/keras-core to keras-team/keras.
Consequently, This issue may not be relevant to the Keras 3 code base . After the migration is successfully completed, feel free to reopen this Issue at keras-team/keras if you believe it remains relevant to the Keras 3 code base. If instead this Issue is a bug or security issue in legacy tf.keras, you can instead report a new issue at [keras-team/tf-keras](https://github.com/keras-team/tf-keras/issues), which hosts the TensorFlow-only, legacy version of Keras.

To know more about Keras 3, please read https://keras.io/keras_core/announcement/
