### ISSUE TITLE
Custom signatures not working with Subclasssed Keras Model

### ISSUE THREAD

**Issue by sumitbinnani** [keras-team/keras#15324]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3
- Python version: 3.7
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the current behavior**
When saving keras_models (checked for Subclassed Model) and providing custom signatures, `keras_model.save(export_dir, signatures)`  does not work and the saved model does not have the exported signature. The custom signature however works if we are using `tf.saved_model.save(keras_model, export_dir, signatures)`.

**Describe the expected behavior**
tf.saved_model.save(keras_model, export_dir, signatures) and `keras_model.save(export_dir, signatures)` should have similar signatures.

Linked to TF Issue: https://github.com/tensorflow/tensorflow/issues/51827

**Comment by ymodak** [comment]
Thanks for your issue. Can you provide a minimal repro example to illustrate the behavior?

**Comment by innat** [comment]
@sumitbinnani [Saving a TF2 keras model with custom signature](https://stackoverflow.com/questions/56659949/saving-a-tf2-keras-model-with-custom-signature-defs)
