### ISSUE TITLE
Execute single test

### ISSUE THREAD

**Issue by bhack** [keras-team/keras#15338]
Why we claim at  https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md#run-a-single-test-case :

> The best way to run a single test case is to comment out the rest of the test
cases in a file before runnig the test file.

We can run single test with `--test_arg` e.g.:

`bazel test keras:backend_test --test_arg=BackendCrossEntropyLossesTest.test_binary_crossentropy_from_logits_no_warnings_test_mode_eager --test_sharding_strategy=disabled`

We have a ticket instead for `--test_filter` https://github.com/bazelbuild/bazel/issues/13664 but it seems more related to `abseil` https://github.com/abseil/abseil-py/issues/128

So it seems for me that the claim is that we can run single test and we are investigating instead the pattern filter issue.

/cc @haifeng-jin

**Comment by haifeng-jin** [comment]
I didn't know this, let me try and get back to you later.
If it works, it does look like a better solution than the current one.

**Comment by haifeng-jin** [comment]
I just tried. It works. So we may add it to the contributing guide.

**Comment by haifeng-jin** [comment]
@bhack I guess our plan should be suggest using `--test_filter` in the contributing guide after the next `abseil-py` release (I guess it should be fixed).
As you said it is more convenient since we have a lot of parameterized tests.

**Comment by bhack** [comment]
> As you said it is more convenient since we have a lot of parameterized tests.

Do we have also glob in the next release?

**Comment by bhack** [comment]
Here the PR in TF:
https://github.com/tensorflow/tensorflow/pull/52173

But glob is still in their TODO list https://github.com/abseil/abseil-py/issues/128

So I don't know what you want to do with parameterized tests names.

**Comment by bhack** [comment]
Ok the PR is merged and available in tf-nightly.

As you have seen in the upstream ticket we can temp filter tests with (e.g):

`bazel test keras:backend_test --test_arg=-- --test_arg=-k=__main__.BackendCrossEntropyLossesTest.test_binary_crossentropy* --test_sharding_strategy=disable`

or 
`bazel test keras:backend_test --test_arg=-- --test_arg=-k=*BackendCrossEntropyLossesTest.test_binary_crossentropy* --test_sharding_strategy=disable`

**Comment by bhack** [comment]
@MarkDaoust As a side effect are you interested in this for https://github.com/tensorflow/tensorflow/blob/master/CONTRIBUTING.md#running-unit-tests ?

**Comment by haifeng-jin** [comment]
Thank you @bhack !
This is awesome work!
I will update the contributing guide for running single or parameterized tests and keep you posted.
