### ISSUE TITLE
Loading the versions of tfs and keras 

### ISSUE THREAD

**Issue by starboyvarun** [keras-team/keras#15334]
![6](https://user-images.githubusercontent.com/26819449/132688854-1c7c6bcd-681a-4e9c-9e78-aedb05e0b67e.JPG)

**Comment by sanatmpa1** [comment]
@starboyvarun,

Can you provide more details about what's the package that you want to use and what's the error that you are getting with TF and Keras. Thanks!

**Comment by starboyvarun** [comment]
@sanatmpa1  Actually this is the starting line of code . The Error is I wanted to use specific version for my bioinformatics library but it loads the wrong version.
As you can see in the screenshot.
Thanks!

**Comment by starboyvarun** [comment]
@sanatmpa1   Can you tell me when this bug will be fixed???

**Comment by sanatmpa1** [comment]
@starboyvarun,

Can you clarify the requirements you need, You need TF version as 2.2.0 and Keras version as 2.4.3 for your project?

**Comment by starboyvarun** [comment]
@sanatmpa1  yes

**Comment by starboyvarun** [comment]
@sanatmpa1 why you are not changing its type.?
