### ISSUE TITLE
pad_sequences bug in Batch

### ISSUE THREAD

**Issue by ucasiggcas** [keras-team/keras#15340]
hi,dear
want to use the **pad_sequences** in batch ,but got the bug down

```
>>> inputs=tf.keras.Input(shape=(None,),dtype=tf.int32)
>>> inputs
<tf.Tensor 'input_1:0' shape=(None, None) dtype=int32>
>>> tf.keras.preprocessing.sequence.pad_sequences(inputs)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/../python3.8/site-packages/tensorflow/python/keras/preprocessing/sequence.py", line 156, in pad_sequences
    return sequence.pad_sequences(
  File "/../python3.8/site-packages/keras_preprocessing/sequence.py", line 57, in pad_sequences
    num_samples = len(sequences)
  File "/../python3.8/site-packages/tensorflow/python/framework/ops.py", line 752, in __len__
    raise TypeError("len is not well defined for symbolic Tensors. ({}) "
TypeError: len is not well defined for symbolic Tensors. (input_1:0) Please call `x.shape` rather than `len(x)` for shape information.

```

could pls help me ?
thx

**Comment by sushreebarsa** [comment]
@ucasiggcas 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by ucasiggcas** [comment]
```
class Model(tf.keras.Model):
    def __init__(self, maxlen=10):
        super(Model,self).__init__()
        self.maxlen=maxlen
    def call(self,inputs):
        seqs_pad=tf.keras.preprocessing.sequence.pad_sequences(inputs)
        return seqs_pad

def gen():
    seqs=[np.random.randint(0,1000,size=10).tolist() for k in range(5,15)]
    yield seqs
#batch_size=10,dim=10,
dataset=tf.data.Dataset.from_generator(gen,output_types=(tf.int32),
                                             output_shapes=((10,10)))
model=Model()
@tf.function
def train_step(inputs):
    with tf.GradientTape() as tape:
        seqs_pad=model(inputs)
        print(seqs_pad)

for inputs in dataset:
    train_step(inputs)
```

bug
```
TypeError: in user code:

    pad_sequences_issue_.py:23 train_step  *
        seqs_pad=model(inputs)
    pad_sequences_issue_.py:10 call  *
        seqs_pad=tf.keras.preprocessing.sequence.pad_sequences(inputs)
    /../python3.8/site-packages/tensorflow/python/keras/preprocessing/sequence.py:156 pad_sequences  **
        return sequence.pad_sequences(
    /../python3.8/site-packages/keras_preprocessing/sequence.py:57 pad_sequences
        num_samples = len(sequences)
    /../python3.8/site-packages/tensorflow/python/framework/ops.py:851 __len__
        raise TypeError("len is not well defined for symbolic Tensors. ({}) "

    TypeError: len is not well defined for symbolic Tensors. (inputs:0) Please call `x.shape` rather than `len(x)` for shape information.

```

**Comment by sushreebarsa** [comment]
@ucasiggcas I tried to run your [code](https://github.com/keras-team/keras/issues/15340#issuecomment-917626071) and faced [this issue](https://colab.research.google.com/gist/sushreebarsa/fbb658c0b20d5b3c181edac35ac21943/untitled196.ipynb) while reproducing. In order to reproduce the issue reported here, could you please provide the complete code and the dataset , tensorflow version you are using. Please refer to the [link](https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/sequence/pad_sequences) and let us know if it helps? Thanks!

**Comment by ucasiggcas** [comment]
No, have tried
could not be useful to my code

**Comment by sushreebarsa** [comment]
@ucasiggcas Thanks for the update! Could you please have a look at the [gist](https://colab.research.google.com/gist/sushreebarsa/e972e392d7ba2fb6f91d2f24fd0fc365/untitled201.ipynb) and let us know if it is the way to reproduce the issue reported here ? Please let me know if I am missing something while reproducing. Thanks!

**Comment by ucasiggcas** [comment]
hi
you forget import np
should need the code
`import numpy as np`
then will reproduce the error

**Comment by sushreebarsa** [comment]
@jvishnuvardhan Was able to reproduce the issue on colab using TF `v2.6` and `tf-nightly` ,please find the gist [here ](https://colab.research.google.com/gist/sushreebarsa/e972e392d7ba2fb6f91d2f24fd0fc365/untitled201.ipynb#scrollTo=VUFIub7eycj9) for reference .Thank you!

**Comment by ucasiggcas** [comment]
yes
it's the problem 
thx

**Comment by fchollet** [comment]
Hi there, `pad_sequences` is only for NumPy data, not for TF tensors, hence the error. Prefer using `tf.pad` https://www.tensorflow.org/api_docs/python/tf/pad
