### ISSUE TITLE
Keras Doesn't Use `KERAS_HOME` for Downloading Data on Windows

### ISSUE THREAD

**Issue by RoyiAvital** [keras-team/keras#15351]
I am on Windows 10.
In my notebook script I define a system environment variable before loading `Keras` (Before loading any package at all beside `os`):

```python
# Setting Keras Path
import os
currFolder      = os.getcwd()
relPath         = "./../../DataSet/"
kerasHomePath   = os.path.normpath(os.path.join(currFolder, relPath))
os.environ['KERAS_HOME'] = kerasHomePath
```

Then, when loading Keras it seems to honor this by creating a file named `keras.json` in it.  
Yet, when I download a data set (Like `(imagesTrain, labelsTrain), (imagesTest, labelsTest) = fashion_mnist.load_data()`) it uses `D:\tmp\.keras` where `D:\` is the drive letter of `kerasHomePath`.

If I don't set `kerasHomePath` then Keras uses my home folder (`C:\Users\<MyUserName>\.keras`).
What can I do to enforce the path to be used by Keras?

**Comment by gowthamkpr** [comment]
@RoyiAvital Please take a look at the solution provided [here](https://stackoverflow.com/questions/49055214/how-do-i-change-the-default-download-directory-for-pre-trained-model-in-keras). Thanks!

**Comment by RoyiAvital** [comment]
@gowthamkpr , Wouldn't it be better if this issue is solved by a code which does as documented?
