### ISSUE TITLE
`keras` augmentation layers into `tf.data.API` with random seed. 

### ISSUE THREAD

**Issue by innat** [keras-team/keras#15358]
I want to use `keras` augmentation layers inside my data pipelines. And I also want to pass different `seeds` per batch. That's why I'm using `tf.random.Generator.from_seed` to get a new seed at each call. And use it to the `keras` augmentation layers. But I've faced the following error:

> ValueError: Tensor-typed variable initializers must either be wrapped in an init_scope or callable (e.g., `tf.Variable(lambda : tf.truncated_normal([10, 40]))`) when building functions. Please file a feature request if this restriction inconveniences you.

**Reproducible Code**

TF Version: 2.6
Environment: Colab.

```python
import tensorflow as tf; print(tf.__version__) # Version : 2.6 
from tensorflow.keras import layers 
AUTO = tf.data.AUTOTUNE
(x_train, y_train), (_, _) = tf.keras.datasets.cifar10.load_data()

def mnist_process(x, y):
    x, y = tf.cast(x, dtype=tf.float32) / 255., tf.cast(y[0], dtype=tf.float32)      
    return x, y

train_ds = tf.data.Dataset.from_tensor_slices((x_train, y_train)).map(mnist_process)
train_ds = train_ds.shuffle(buffer_size=1024).batch(64)
```

```python
# Create a generator
rng = tf.random.Generator.from_seed(123, alg='philox')
def rand_augmentation(x, y):
    # updating seeds
    set_seed = rng.make_seeds()[0]
    def apply_augment(x):
        x = layers.RandomFlip("horizontal", seed=set_seed)(x)
        x = layers.RandomRotation(factor=0.01, seed=set_seed)(x)
        x = layers.RandomTranslation(height_factor=0.0, width_factor=0.1, seed=set_seed)(x)
        x = layers.RandomContrast(factor=0.6, seed=set_seed)(x)
        x = layers.RandomRotation(factor=(-0.2, 0.2), fill_mode='reflect', seed=set_seed)(x)
        x = tf.clip_by_value(x, 0, 1)
        return x 
    return apply_augment(x), y

train_ds = train_ds.map(lambda x, y: (rand_augmentation(x, y)), 
                                      num_parallel_calls=AUTO)
# Doesn't work.
```

---

However, if I wrap the `rand_augmentation` function as follows, it works on **GPU** but not on **TPU** ([known issue](https://github.com/tensorflow/tensorflow/issues/38762#issuecomment-688247286), not fixed yet) 

```python
def wrap_augment(image,  label):
    aug_img, label = tf.numpy_function(func=rand_augmentation, 
                                inp=[image, label], 
                                Tout=[tf.float32, tf.float32])
    return aug_img, label

train_ds = train_ds.map(lambda x, y: (wrap_augment(x, y)), num_parallel_calls=AUTO)
# Works.
```

cc: @fchollet

**Comment by AdityaKane2001** [comment]
@innat 

I may be wrong, but please hear me out. TPUs are systolic devices, which means they do not support (almost) anything except MatMul. They are designed to be deterministic in nature. This is a well known fact, and thus augmentations and pyfuncs are executed on a powerful host CPU attached to the TPU. Note that GPUs have essentially same architecture as CPUs and thus they can perform random operations without any problem. ([source](https://cloud.google.com/tpu/docs/beginners-guide))

Hope this helps.

**Comment by innat** [comment]
@AdityaKane2001 thanks for the info, it's helpful. 
I am not a frequent TPU user but I came to know about such an [issue](https://github.com/tensorflow/tensorflow/issues/34346#issuecomment-569815051). However, I believe there should some efficient workaround for that. Do you have anything on mind to resolve this issue?

**Comment by AdityaKane2001** [comment]
@innat 

Unfortunately, no. I have not found  a clean workaround so far. All you can try is to make the input pipeline fast enough.

**Comment by qlzh727** [comment]
@wangpengmit for tf.random.Generator() and tf.function related question.

**Comment by wangpengmit** [comment]
`layers.RandomFlip` etc. layers create a `tf.random.Generator` internally, and generator creation (similar to variable creation) doesn't work very well with `Dataset.map`. You can move your layer creations out of `Dataset.map` (like how you created `tf.random.Generator` outside `Dataset.map`):
```python
layer1 = layers.RandomFlip("horizontal", seed=[1, 0])
layer2 = layers.RandomRotation(factor=0.01, seed=[2, 0])
layer3 = layers.RandomTranslation(height_factor=0.0, width_factor=0.1, seed=[3, 0])
layer4 = layers.RandomContrast(factor=0.6, seed=[4, 0])
layer5 = layers.RandomRotation(factor=(-0.2, 0.2), fill_mode='reflect', seed=[5, 0])
def rand_augmentation(x, y):
    # updating seeds
    set_seed = rng.make_seeds()[0]
    def apply_augment(x):
        x = layer1(x)
        x = layer2(x)
        x = layer3(x)
        x = layer4(x)
        x = layer5(x)
        x = tf.clip_by_value(x, 0, 1)
        return x 
    return apply_augment(x), y

train_ds = train_ds.map(lambda x, y: (rand_augmentation(x, y)), 
                                      num_parallel_calls=AUTO)
```
Since those layers have generators internally, you can just set their `seed` to fixed numbers. They'll still give you different results for each batch.

**Comment by innat** [comment]
@wangpengmit thanks for the detailed reply. I was already doing a similar approach. Something like as follows:

```python
class KerasAugmentation(tf.keras.layers.Layer):
   def __init__():
	  layer1 = layers.RandomFlip("horizontal", seed=[1, 0])
      layer2 = ... seed[1, 0]
      layer3 = ... seed[1, 0]
   
   def call(..):
      x = layer1(inputs)
      x = layer2(x)
      x = layer3(x)
```

And I know [internally](https://github.com/keras-team/keras/blob/3a33d53ea4aca312c5ad650b4883d9bac608a32e/keras/layers/preprocessing/image_preprocessing.py#L1362) it uses `tf.random.Generator()` for a given `seed` value. In this way, it works on both GPU and TPU. And no need to wrap anything in `py_function`. 

Now, in this way we're fixing the seed value specifically. Each time when `call` method runs, it will use the same `seed` value (defined in `init` or outside) for all samples throughout the data set, which means that batch 1, 2, 3 .. will go through the same type of augmentation. If that's the case, won't be more precise to able to pass different `seed` value for different batch (if not sample-wise)?

**Comment by qlzh727** [comment]
I think the given seed will only make the layer to produce same deterministic sequence of random number, but will still be different between each batches.

```
layer = layers.RandomFlip("horizontal", seed=[1, 0])
input = ...
output1 = layer(input)
output2 = layer(input)

output1 != output2

layer2 =  layers.RandomFlip("horizontal", seed=[1, 0])
output3 = layer2(input)
output4 = layer2(input)

output3 == output1
output4 == output2
output3 != output4
```

So far I don't think there is a way to provide same random number for the KPL across the batches.

**Comment by wangpengmit** [comment]
+1 to what @qlzh727 said.

**Comment by innat** [comment]
@wangpengmit Actually, using the same random seed is on purpose (will explain later). As @qlzh727 stated it's true that for such setup (same seed initialization), it causes `output3 == output1` which is not wanted. 

The issue is, I'm working on a multi-modal brain tumor [data set](https://www.kaggle.com/c/rsna-miccai-brain-tumor-radiogenomic-classification); where each sample has 4 different modalities. And that's why I need to ensure that samples for each modality should have a unique seed value for augmentation. Because the samples of a modality are basically voxel data (3D) and so that spatial transformation should be the same for each modality. So precisely I was looking for some solutions like stated below:

```bash
epoch 1, batch 1
1st modalities: (total 120 samples and seed value 1)
2nd modalities: (total 120 samples and seed value 2)
3rd modalities: (total 120 samples and seed value 3)
4th modalities: (total 120 samples and seed value 4)
epoch 1, batch 2
1st modalities: (total 120 samples and seed value 5)
2nd modalities: (total 120 samples and seed value 6)
3rd modalities: (total 120 samples and seed value 7)
4th modalities: (total 120 samples and seed value 8)
...
epoch 2, batch 1
1st modalities: (total 120 samples and seed value 100)
2nd modalities: (total 120 samples and seed value 101)
3rd modalities: (total 120 samples and seed value 102)
4th modalities: (total 120 samples and seed value 103)
...
```

The solution by far I could manage was mentioned, using [rng.make_seeds()[0]](https://github.com/keras-team/keras/issues/15358#issue-995140501), and it's generally similar to [this](https://github.com/keras-team/keras/issues/15358#issuecomment-926965908) one, I think. However, later the problem arises for TPU use cases.

```
TPU: 
UnavailableError: failed to connect to all addresses
Additional GRPC error information from remote target /job:localhost/replica:0/task:0/device:CPU:0:
```

**Comment by qlzh727** [comment]
I see. In that case, what you might want to do is:

1. Within each batch, concat the modalities 1 to 4 together, and feed them to the random layers, split the output into 4 afterward. This will ensure the same augmentation is applied to all the modalities.

2. You don't need to set seed for the random layer, the tf.random.Generator under the hood will make sure it create new augmentation every time it is invoked (across the batches).

3. If you want the epoch 2 to have different augmentation comparing to epoch 1, then you should just remove the seed. The seed will actually make epoch 1 to have same value as epoch 2 (see my previous comment).

**Comment by innat** [comment]
@qlzh727 
Awesome, It works as expected; Thanks. 

```python
def ABC: 
	inputs = - batach, h, w, depth, channel 
	images = tf.reshape(inputs, [-1, h, w, depth*channel])
	
	def augment (all_modalities) :
		x = keras_aug.random_flip(all_modalities)
       	x = next_layer(x)
		return x 

	augmented_modalities =  augment (images) 
	images = tf.reshape (augmented_modalities, [-1, h, w, depth, channel])
	return images
```

However, what if...we have a custom augmentation layer, build with `tf.image` or `tf.addons.image` modules. How to make sure the randomness **per batch** in such a case? Like in your point 2, with built-in `keras` augmentation, randomness is ensured by `tf.random.Generator` under the hood but how to ensure that for custom augmentation layers?

**Comment by qlzh727** [comment]
It depends on how the lib author implement their layer. User can still use tf.random.Generator which is a public API.


> @qlzh727 Awesome, It works as expected; Thanks.
> 
> ```python
> def ABC: 
> 	inputs = - batach, h, w, depth, channel 
> 	images = tf.reshape(inputs, [-1, h, w, depth*channel])
> 	
> 	def augment (all_modalities) :
> 		x = keras_aug.random_flip(all_modalities)
>        	x = next_layer(x)
> 		return x 
> 
> 	augmented_modalities =  augment (images) 
> 	images = tf.reshape (augmented_modalities, [-1, h, w, depth, channel])
> 	return images
> ```
> 
> However, what if...we have a custom augmentation layer, build with `tf.image` or `tf.addons.image` modules. How to make sure the randomness **per batch** in such a case? Like in your point 2, with built-in `keras` augmentation, randomness is ensured by `tf.random.Generator` under the hood but how to ensure that for custom augmentation layers?

**Comment by qlzh727** [comment]
Since tf.data API doesn't allow weight creation within it (tf.random.Generator creates weight as its own internal state), I don't think we can address anything here in this bug. Also with the walk around above, you probably can achieve what you want. Closing this bug now, and let me know if you need anything else. 

Thanks.
