### ISSUE TITLE
How can i solve problem of Matrix size-incompatible ?

### ISSUE THREAD

**Issue by mathshangw** [keras-team/keras#15353]
I'm facing this problem 

    (0) Invalid argument:  Matrix size-incompatible: In[0]: [53,1132], In[1]: [1240,512]
    	 [[node functional_1/dense/MatMul (defined at fit.py:324) ]]
      (1) Invalid argument:  Matrix size-incompatible: In[0]: [53,1132], In[1]: [1240,512]
    	 [[node functional_1/dense/MatMul (defined at fit.py:324) ]]
    	 [[gradient_tape/functional_1/embedding/embedding_lookup/Reshape_1/_30]]

**Comment by sushreebarsa** [comment]
@mathshangw In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by mathshangw** [comment]
```
def define_model(vocab_size, max_length,curr):

    inputs1 = Input(shape=curr)
    x= Dropout(0.2)(inputs1)
    x = Dense(256, activation='relu')(x) 
    inputs2 = Input(shape=(max_length,))
    y = Embedding(vocab_size, 128, mask_zero=True)(inputs2)
    y = LSTM(256)(y)
    z = Concatenate()([y, x])
    d = Dense(vocab_size, activation='softmax')(z)
    model = Model(inputs=[inputs1, inputs2], outputs=d)
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
   return model
```

**Comment by mathshangw** [comment]
```
def define_model(vocab_size, max_length):

    inputs1 = Input(shape=(1120, ))
    x= Dropout(0.2)(inputs1)
    x = Dense(256, activation='relu')(x) 
    inputs2 = Input(shape=(max_length,))
    y = Embedding(vocab_size, 128, mask_zero=True)(inputs2)
    y = LSTM(256)(y)
    z = Concatenate()([y, x])
    d = Dense(vocab_size, activation='softmax')(z)
    model = Model(inputs=[inputs1, inputs2], outputs=d)
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
   return model
```

**Comment by sushreebarsa** [comment]
@mathshangw I tried to run your[ code](https://github.com/keras-team/keras/issues/15353#issuecomment-917643111) on Colab using **`TF v2.6`** and didn't face the error reported here .Please find the [gist](https://colab.research.google.com/gist/sushreebarsa/673fa5a29ffaab854b991604f984d2be/untitled192.ipynb) for reference and let us know if it helps ?Thanks!

**Comment by mathshangw** [comment]
Thanks for your time . Excuse me can you answer me for those questions as I'm confused
 does this solution right for solving this type of error ? 
Will zeros that will be exists be a problem in training data ? Is there any solution for this error ?

**Comment by mathshangw** [comment]
Thanks for your time . the problem with me in the first post not the model itself so excuse me can you answer me for those questions as I'm confused
does this solution right for solving this type of error ?
Will zeros that will be exists be a problem in training data ? Is there any solution for this error

**Comment by mathshangw** [comment]
is there any help please ?
