### ISSUE TITLE
VAE example is no longer valid

### ISSUE THREAD

**Issue by ldmtwo** [keras-team/keras#15361]
I followed this example and it now requires a call() method in keras.Model.

Not working:
https://keras.io/examples/generative/vae/

Working:
https://www.tensorflow.org/guide/keras/custom_layers_and_models

After calling fit ...

NotImplementedError: in user code:

anaconda3/lib/python3.8/site-packages/keras/engine/training.py:1330 test_function  *
        return step_function(self, iterator)
anaconda3/lib/python3.8/site-packages/keras/engine/training.py:1320 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
anaconda3/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:1286 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
anaconda3/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:2849 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
   anaconda3/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:3632 _call_for_each_replica
        return fn(*args, **kwargs)
    anaconda3/lib/python3.8/site-packages/keras/engine/training.py:1313 run_step  **
        outputs = model.test_step(data)
anaconda3/lib/python3.8/site-packages/keras/engine/training.py:1267 test_step
        y_pred = self(x, training=False)
   lib/python3.8/site-packages/keras/engine/base_layer.py:1037 __call__
        outputs = call_fn(inputs, *args, **kwargs)
    anaconda3/lib/python3.8/site-packages/keras/engine/training.py:446 call  **
        raise NotImplementedError('When subclassing the `Model` class, you should '

    NotImplementedError: When subclassing the `Model` class, you should implement a `call` method.

**Comment by ymodak** [comment]
I was able to successfully execute the tutorial as is from the colab gist given on the top.
Also there is TF implementation for [convolutional variational  autoencoder](https://www.tensorflow.org/tutorials/generative/cvae) you may find useful.
