### ISSUE TITLE
Sequence labeling with 95% accuracy while learning but still predicting badly

### ISSUE THREAD

**Issue by Rachnog** [keras-team/keras#1539]
Ciao everyone,
I'm working on sentence labeling problem, I've done embedding and padding by myself and my inputs look like:

```
X_i = [[0,1,1,0,2,3...], [0,1,1,0,2,3...], ..., [0,0,0,0,0...],  [0,0,0,0,0...], ....]
```

For every word in sentence I want to predict one of four classes, so my desired output should look like:

```
Y_i = [[1,0,0,0], [0,0,1,0], [0,1,0,0], ...]
```

My network architecture is quite simple and looks like:

```
model = Sequential()

model.add(LSTM(input_shape = (emb,),input_dim=emb, output_dim=hidden, return_sequences=True))
model.add(TimeDistributedDense(output_dim=4))
model.add(Activation('softmax'))
model.compile(loss='binary_crossentropy', optimizer='adam')

model.fit(X_train, Y_train, batch_size=32, nb_epoch=3, validation_data=(X_test, Y_test), verbose=1, show_accuracy=True)
```

It shows approximately 95% while training, but when I'm trying to predict new sentences using trained model results are really bad, it looks like model just learnt some classes for first words and shows it every time. I want to know, how to solve this issue... I think that problem can be in:

1) Written by myself padding (zero vectors in the end of the sentence), can it make learning worse?
2) I should try to learn sentences of different length, without padding (if yes, can you help me how train such kind of a model in Keras?)
3) Wrong objective of learning, but I tried mean squared error, binary cross entropy and others, it doesn't change.
4) Something with TimeDistributedDense and softmax, I think, that I've got how it works, but still not 100% sure.

I'll be glad to see any hint or help regarding to this problem, thank you!

**Comment by magic282** [comment]
Why are you using `binary_crossentropy` loss?

**Comment by Rachnog** [comment]
@magic282 isn't it correct for four classes that look like [0, 0, 1, 0]?
As far as I understand, `categorical_crossentropy` is for multi-class classification?

**Comment by magic282** [comment]
@Rachnog [ref](http://deeplearning.net/software/theano/library/tensor/nnet/nnet.html#tensor.nnet.binary_crossentropy)

**Comment by Rachnog** [comment]
@magic282 thanks' I got it.
By the way, do you know how to pass into my network sequences of different length? I think, that my model is showing high accuracy, because it's predicting all padded zeros correctly and "doesn't care" about first 5-10 words in sentence.

**Comment by talentlei** [comment]
@Rachnog 
I'm also working on sentence labeling problem. But I failed running the lstm program that almost the same with yours.  

train.shape = (seq_len,200)   #200 dim
train_lab.shape=(seq_len,5)  #5 classes

       model = Sequential()
        
        model.add(LSTM(output_dim=16,input_shape=(self.embed_length,),input_dim=self.embed_length,return_sequences=True ))
        #model.add(Dropout(0.5))
        model.add(TimeDistributedDense(output_dim=self.labs_len))
        model.add(Activation('softmax'))
        model.compile(loss="categorical_crossentropy" , optimizer='rmsprop' , class_mode='categorical')
        model.fit(self.train,self.train_lab,batch_size=16,nb_epoch=1)

but I got error as follows:

File "ner_rnn.py.bak", line 100, in moduleRnn
    model.fit(self.train,self.train_lab,batch_size=16,nb_epoch=1)
  File "build/bdist.linux-x86_64/egg/keras/models.py", line 583, in fit
  File "build/bdist.linux-x86_64/egg/keras/models.py", line 241, in _fit
  File "build/bdist.linux-x86_64/egg/keras/backend/theano_backend.py", line 385, in __call__
  File "/home/cl/download/Theano/theano/compile/function_module.py", line 786, in __call__
    allow_downcast=s.allow_downcast)
  File "/home/cl/download/Theano/theano/tensor/type.py", line 177, in filter
    data.shape))
TypeError: ('Bad input argument to theano function with name "build/bdist.linux-x86_64/egg/keras/backend/theano_backend.py:382"  at index 0(0-based)', 'Wrong number of dimensions: expected 3, got 2 with shape (16, 200).')

Can you help me?
thx

**Comment by magic282** [comment]
@Rachnog Use `Masking` layer or `Embedding` layer to mask the padded timesteps. But it seems that there are some issues after v0.3.0. Check this issue [https://github.com/fchollet/keras/issues/1491] I proposed.

**Comment by talentlei** [comment]
Thanks for sharing!

**Comment by Rachnog** [comment]
@magic282 Do you know, is it possible to mask not only with `mask_value = 0.0`, but with something like `mask_value = [0,0,0,0,0,0,0,0]`?
Thank you for support, you help me very much!

**Comment by o0laika0o** [comment]
Hi Rachnog,
have you solved your problem yet? I have a similar case in which I would mask some sequences. Would you please share your ideas or code blocks?

**Comment by ersinyar** [comment]
@talentlei why did you use TimeDistributedDense in your case? I am dealing with sentence labelling also. After LSTM layer normally one obtains a representation for each word. But how to combine them? You did TimeDistributedDense and then activation. How do you combine the representations obtained from LSTM layer for each word to get a single representation for whole sentence?

**Comment by Reihan-amn** [comment]
Hi @Rachnog 

May I know what features are you using for feeding this LSTM model?
how do you vectorize the words or sentences?

**Comment by naisanza** [comment]
@Reihan-amn 

For vectorizing the sentences (in this case, a word-based classifier instead of a character-based classifier), you can either manually split the words in a sentence, or use a smarter library (like nltk) to do the tokenizing for you

```
from nltk.tokenize import word_tokenize
tokens = word_tokenize(SENTENCES)
```

After you have the sentences tokenized into individual words, you want to create two dictionary indexes of `word_to_index` and it's reverse (for translating a prediction) `index_to_word`

After that you can use an `Embedding` layer to prep it for the LSTM layer, or you can further create a one-hot encoded index of your inputs, which can be fed directly into a LSTM layer

That's what I think I know to the best of my knowledge

**Comment by ravaan** [comment]
I have manually padded the sentences to the 90th percentile length (16 in my case, max = 29). Now I am confused how to account this padding while calculating the accuracy of the model. 

So many sentences are ending with a few zeros and have 0 for them in the `y_train`. So the model must be predicting this with a pretty high accuracy thus effectively increasing the overall accuracy of my model. Which is misleading for me. How can I account for this in `Keras`. Right now I am calculating the accuracy using the default function in `Keras` (passing `metrics = ['accuracy']` while compiling the model).
