### ISSUE TITLE
Different output after Save/Load for Keras model with LSTM

### ISSUE THREAD

**Issue by yelandgit** [keras-team/keras#15398]
**Platform:** Ubuntu 18.04 (Amazon Cloud EC2 instance)
**TensorFlow:** 2.3.4/2.4.3 + Keras + Cuda
**Python:** 3.7.10

I try to train model with LSTM using CTC algorithm ( code from [OCR model for reading Captchas](https://keras.io/examples/vision/captcha_ocr/) )
If I do sequentially model creation, training, evaluation, saving, loading, and evaluation again, everything is correct.
The original trained model and the restored model give me same result.
At first look Save + Load functions working fine, but if I comment Model, Train sections (see code below), and leave just final Load, Evaluate steps for previous saved model (section Test), the restored model  produces wrong result.
I have tried to use other formats to save/load model, but nothing changed.
I don't understand is it bug in Keras, or maybe I do something incorrect? Could you help me?
My source code is below:

**ctc-test.py**

<pre><code>import os
import numpy as np

from pathlib import Path
#from collections import Counter

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
#import onnxruntime as ort
#import keras2onnx
#import onnx

#keras.backend.manual_variable_initialization(True)

# ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
#               data
# ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~

def SplitData(images, labels, train_size=0.9, shuffle=True):
    # 1. Get the total size of the dataset
    size = len(images)
    # 2. Make an indices array and shuffle it, if required
    indices = np.arange(size)
    if shuffle:
        np.random.shuffle(indices)
    # 3. Get the size of training samples
    train_samples = int(size * train_size)
    # 4. Split data into training and validation sets
    x_train, y_train = images[indices[:train_samples]], labels[indices[:train_samples]]
    x_valid, y_valid = images[indices[train_samples:]], labels[indices[train_samples:]]
    return x_train, x_valid, y_train, y_valid

def EncodeSingleSample(img_path, label):
    # 1. Read image
    img = tf.io.read_file(img_path)
    # 2. Decode and convert to grayscale
    img = tf.io.decode_png(img, channels=1)
    # 3. Convert to float32 in [0, 1] range
    img = tf.image.convert_image_dtype(img, tf.float32)
    # 4. Resize to the desired size
    img = tf.image.resize(img, [img_height, img_width])
    # 5. Transpose the image because we want the time
    # dimension to correspond to the width of the image.
    img = tf.transpose(img, perm=[1, 0, 2])
    # 6. Map the characters in label to numbers
    label = char_to_num(tf.strings.unicode_split(label, input_encoding="UTF-8"))
    # 7. Return a dict as our model is expecting two inputs
    return {"image": img, "label": label}

# ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
#               neural net
# ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~

class CTCLayer(layers.Layer):
    def __init__(self, name=None):
        super().__init__(name=name)
        self.loss_fn = keras.backend.ctc_batch_cost

    def call(self, y_true, y_pred):
        # Compute the training-time loss value and add it to the layer using `self.add_loss()`
        batch_len = tf.cast(tf.shape(y_true)[0], dtype="int64")
        input_length = tf.cast(tf.shape(y_pred)[1], dtype="int64")
        label_length = tf.cast(tf.shape(y_true)[1], dtype="int64")

        input_length = input_length * tf.ones(shape=(batch_len, 1), dtype="int64")
        label_length = label_length * tf.ones(shape=(batch_len, 1), dtype="int64")

        loss = self.loss_fn(y_true, y_pred, input_length, label_length)
        self.add_loss(loss)

        # At test time, just return the computed predictions
        return y_pred

def BuildModel():
    # Inputs to the model
    inp = layers.Input(shape=(img_width, img_height, 1), name="image", dtype="float32")
    labels = layers.Input(name="label", shape=(None,), dtype="float32")

    # First conv block
    x = layers.Conv2D(  32, (3, 3),
                        activation="relu",
                        kernel_initializer="he_normal",
                        padding="same",
                        name="Conv1",
                    )(inp)
    x = layers.MaxPooling2D((2, 2), name="pool1")(x)

    # Second conv block
    x = layers.Conv2D(  64, (3, 3),
                        activation="relu",
                        kernel_initializer="he_normal",
                        padding="same",
                        name="Conv2",
                    )(x)
    x = layers.MaxPooling2D((2, 2), name="pool2")(x)

    # We have used two max pool with pool size and strides 2.
    # Hence, downsampled feature maps are 4x smaller.
    # The number of filters in the last layer is 64. 
    # Reshape accordingly before passing the output to the RNN part of the model
    new_shape = ((img_width // 4), (img_height // 4) * 64)
    x = layers.Reshape(target_shape=new_shape, name="reshape")(x)
    x = layers.Dense(64, activation="relu", name="dense1")(x)
    x = layers.Dropout(0.2)(x)

    # RNNs
    x = layers.Bidirectional(layers.LSTM(128, return_sequences=True, dropout=0.25))(x)
    x = layers.Bidirectional(layers.LSTM(64, return_sequences=True, dropout=0.25))(x)

    # Output layer
    x = layers.Dense(len(char_to_num.get_vocabulary()) + 1, activation="softmax", name="dense2")(x)

    # Add CTC layer for calculating CTC loss at each step
    out = CTCLayer(name="ctc_loss")(labels, x)

    # Define the model
    model = keras.models.Model(inputs=[inp, labels], outputs=out, name="ocr_model_v1")
    model.compile(optimizer=keras.optimizers.Adam())
    return model

def TrainModel(model, train_set, epochs, early_stop):
    early_stopping = keras.callbacks.EarlyStopping( monitor="val_loss",
                                                    patience=early_stop,
                                                    restore_best_weights=True)
    history = model.fit(train_set,
                        validation_data=valid_set,
                        epochs=epochs,
                        callbacks=[early_stopping])

    xmodel = keras.models.Model(model.get_layer(name="image").input,
                                model.get_layer(name="dense2").output)
    return xmodel

def DecodeBatchPredictions(pred):
    input_len = np.ones(pred.shape[0]) * pred.shape[1]
    # Use greedy search. For complex tasks, you can use beam search
    results = keras.backend.ctc_decode(pred, input_length=input_len, greedy=True)[0][0][:, :max_length]
    # Iterate over the results and get back the text
    output_text = []
    for res in results:
        res = tf.strings.reduce_join(num_to_char(res)).numpy().decode("utf-8")
        output_text.append(res)
    return output_text

def EvaluateModel(model, data_set, name, header=False):
    total = 0
    correct = 0
    for batch in data_set:
        images = batch["image"]
        labels = batch["label"]

        pred = model.predict(images)
        text = DecodeBatchPredictions(pred)
        for i in range(len(labels)):
            ref = tf.strings.reduce_join(num_to_char(labels[i])).numpy().decode("utf-8")
            if (text[i] == ref):
                correct += 1

        total += images.shape[0]

    if (total == 0):
        total = 1
    acc = (100*correct)/total

    if (header):
        print("")
        print("            Corr    Err    Total     Acc     Err")
    print(name, "%8d%8d%8d  %8.2f%8.2f" % (correct,total-correct,total,acc,100-acc))

# ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
#               load / save
# ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~

def LoadModel(file):
    # JSON format
    xfile = os.path.splitext(file)
    if (xfile[1] == ".json"):
        with open(file, "r") as json:
            json_model = json.read()
        model = keras.models.model_from_json(json_model)
        model.load_weights(xfile[0] + ".wgt")

    # ONNX format
    elif (xfile[1] == ".onnx"):
        raise Exception("LoadModel; ONNX format not supported yet")
        model = None

    # TF/Keras format
    else:
        model = keras.models.load_model(file, custom_objects={'leaky_relu': tf.nn.leaky_relu})

    return model

def SaveModel(file, model):
    # JSON format
    xfile = os.path.splitext(file)
    if (xfile[1] == ".json"):
        print("save JSON:", file)
        json_model = model.to_json()
        with open(file, "w") as json:
            json.write(json_model)
        model.save_weights(xfile[0] + ".wgt")

    # ONNX format
    elif (xfile[1] == ".onnx"):
        print("save ONNX:", file)
        onnx_model = keras2onnx.convert_keras(model, model.name)
        onnx.save_model(onnx_model, file)

    # Keras format
    elif (xfile[1] == ".h5" or xfile[1] == ".dnn"):
        print("save HDF5:", file)
        model.save(file, save_format='h5')

    # TF format
    else:
        print("save TF:", file)
        model.save(file, save_format='tf')

# ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
#               main
# ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~

img_width = 200
img_height = 50

batch_size = 16

# Get list of all the images
data_dir = Path("./data/captcha_images_v2/")
images = sorted(list(map(str, list(data_dir.glob("*.png")))))
labels = [img.split(os.path.sep)[-1].split(".png")[0] for img in images]
charset = set(char for label in labels for char in label)
max_length = max([len(label) for label in labels])
    
print()
print("Number of images:  ", len(images))
print("Number of labels:  ", len(labels))
print("Unique characters: ", charset, len(charset))
print("Maximum length:    ", max_length)
print()
    
# Mapping characters to integers
char_to_num = layers.experimental.preprocessing.StringLookup(vocabulary=list(charset), mask_token=None)

# Mapping integers back to original characters
num_to_char = layers.experimental.preprocessing.StringLookup(vocabulary=char_to_num.get_vocabulary(), mask_token=None, invert=True)

# Splitting data into training and validation sets (file list)
x_train, x_valid, y_train, y_valid = SplitData(np.array(images), np.array(labels))
    
train_set = tf.data.Dataset.from_tensor_slices((x_train, y_train))
train_set = (
    train_set.map(EncodeSingleSample, num_parallel_calls=tf.data.experimental.AUTOTUNE)
    .batch(batch_size)
    .prefetch(buffer_size=tf.data.experimental.AUTOTUNE)
)
valid_set = tf.data.Dataset.from_tensor_slices((x_valid, y_valid))
valid_set = (
    valid_set.map(EncodeSingleSample, num_parallel_calls=tf.data.experimental.AUTOTUNE)
    .batch(batch_size)
    .prefetch(buffer_size=tf.data.experimental.AUTOTUNE)
)

file_tf = "model-tf"
file_json = "model.json"
file_wgt = "model.wgt"

file = file_tf

#-------- model

model = BuildModel()
model.summary()
print()

#-------- train

epochs = 50
early_stop = 10
viewf = False

model1 = TrainModel(model, train_set, epochs, early_stop)
EvaluateModel(model1, train_set, "train:", True)
EvaluateModel(model1, valid_set, "test: ")
print()
SaveModel(file, model1)

#-------- test

print("")
print("Test: model3 = LoadModel(", file, ")")
model3 = LoadModel(file)
EvaluateModel(model3, train_set, "train:", True)
EvaluateModel(model3, valid_set, "test: ")

print()</code></pre>

**Comment by kumariko** [comment]
@yelandgit I tried to run your code on colab using TF v2.6 . I faced value error while reproducing please find the gist [**`here`**](https://colab.research.google.com/gist/kumariko/a3309b687ad76f7cbed97c71e531f39a/51241.ipynb) for reference and  confirm the same .Could you please have a look at the [**`link1`**](https://www.tensorflow.org/guide/keras/save_and_serialize) ,  [**`link2`**](https://github.com/keras-team/keras/issues/4875) and let us know if it helps ? Thanks!

**Comment by yelandgit** [comment]
I got error "_max() arg is an empty sequence_", because program uses external data set (see [https://keras.io/examples/vision/captcha_ocr/)](url)
Before to run my code, you need to download and unpack data:
<pre><code>curl -LO https://github.com/AakashKumarNain/CaptchaCracker/raw/master/captcha_images_v2.zip
unzip -qq captcha_images_v2.zip</code></pre>
My program reads data from directory ./data./captcha_images_v2/

Yes, I have seen [link1](https://www.tensorflow.org/guide/keras/save_and_serialize) and [link2](https://github.com/keras-team/keras/issues/4875). I didn't find solution. Advice from **kswersky** doesn't work for me

**Comment by yelandgit** [comment]
I think Save/Load functions don't work correct. The next simple test shows it:
<pre><code>import os
import numpy as np
from pathlib import Path

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
#import keras2onnx
#import onnx

# ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
#               neural net
# ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~

class CTCLayer(layers.Layer):
    def __init__(self, name=None):
        super().__init__(name=name)
        self.loss_fn = keras.backend.ctc_batch_cost

    def call(self, y_true, y_pred):
        # Compute the training-time loss value and add it to the layer using `self.add_loss()`
        batch_len = tf.cast(tf.shape(y_true)[0], dtype="int64")
        input_length = tf.cast(tf.shape(y_pred)[1], dtype="int64")
        label_length = tf.cast(tf.shape(y_true)[1], dtype="int64")

        input_length = input_length * tf.ones(shape=(batch_len, 1), dtype="int64")
        label_length = label_length * tf.ones(shape=(batch_len, 1), dtype="int64")

        loss = self.loss_fn(y_true, y_pred, input_length, label_length)
        self.add_loss(loss)

        # At test time, just return the computed predictions
        return y_pred

def BuildModel():
    # Inputs to the model
    inp = layers.Input(shape=(img_width, img_height, 1), name="image", dtype="float32")
    labels = layers.Input(name="label", shape=(None,), dtype="float32")

    # First conv block
    x = layers.Conv2D(  32, (3, 3),
                        activation="relu",
                        kernel_initializer="he_normal",
                        padding="same",
                        name="Conv1",
                    )(inp)
    x = layers.MaxPooling2D((2, 2), name="pool1")(x)

    # Second conv block
    x = layers.Conv2D(  64, (3, 3),
                        activation="relu",
                        kernel_initializer="he_normal",
                        padding="same",
                        name="Conv2",
                    )(x)
    x = layers.MaxPooling2D((2, 2), name="pool2")(x)

    # We have used two max pool with pool size and strides 2.
    # Hence, downsampled feature maps are 4x smaller.
    # The number of filters in the last layer is 64. 
    # Reshape accordingly before passing the output to the RNN part of the model
    new_shape = ((img_width // 4), (img_height // 4) * 64)
    x = layers.Reshape(target_shape=new_shape, name="reshape")(x)
    x = layers.Dense(64, activation="relu", name="dense1")(x)
    x = layers.Dropout(0.2)(x)

    # RNNs
    x = layers.Bidirectional(layers.LSTM(128, return_sequences=True, dropout=0.25))(x)
    x = layers.Bidirectional(layers.LSTM(64, return_sequences=True, dropout=0.25))(x)

    # Output layer
    x = layers.Dense(len(char_to_num.get_vocabulary()) + 1, activation="softmax", name="dense2")(x)

    # Add CTC layer for calculating CTC loss at each step
    out = CTCLayer(name="ctc_loss")(labels, x)

    # Define the model
    model = keras.models.Model(inputs=[inp, labels], outputs=out, name="ocr_model_v1")
    model.compile(optimizer=keras.optimizers.Adam())
    return model

# ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
#               load / save
# ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~

def LoadModel(file):
    # JSON format
    xfile = os.path.splitext(file)
    if (xfile[1] == ".json"):
        with open(file, "r") as json:
            json_model = json.read()
        model = keras.models.model_from_json(json_model)
        model.load_weights(xfile[0] + ".wgt")

    # ONNX format
    elif (xfile[1] == ".onnx"):
        raise Exception("LoadModel; ONNX format not supported yet")
        model = None

    # TF/Keras format
    else:
        model = keras.models.load_model(file, custom_objects={'leaky_relu': tf.nn.leaky_relu})

    return model

def SaveModel(file, model):
    # JSON format
    xfile = os.path.splitext(file)
    if (xfile[1] == ".json"):
        print("save JSON:", file)
        json_model = model.to_json()
        with open(file, "w") as json:
            json.write(json_model)
        model.save_weights(xfile[0] + ".wgt")

    # ONNX format
    elif (xfile[1] == ".onnx"):
        print("save ONNX:", file)
        onnx_model = keras2onnx.convert_keras(model, model.name)
        onnx.save_model(onnx_model, file)

    # Keras format
    elif (xfile[1] == ".h5" or xfile[1] == ".dnn"):
        print("save HDF5:", file)
        model.save(file, save_format='h5', save_traces=False)

    # TF format
    else:
        print("save TF:", file)
        model.save(file, save_format='tf', save_traces=False)

# ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
#               main
# ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~

img_width = 200
img_height = 50

batch_size = 16

# Get list of all the images
data_dir = Path("./data/captcha_images_v2/")
images = sorted(list(map(str, list(data_dir.glob("*.png")))))
labels = [img.split(os.path.sep)[-1].split(".png")[0] for img in images]
charset = set(char for label in labels for char in label)
max_length = max([len(label) for label in labels])
    
print()
print("Number of images:  ", len(images))
print("Number of labels:  ", len(labels))
print("Unique characters: ", charset, "=", len(charset))
print("Maximum length:    ", max_length)
print()
    
# Mapping characters to integers
char_to_num = layers.experimental.preprocessing.StringLookup(vocabulary=list(charset), mask_token=None)

# Mapping integers back to original characters
num_to_char = layers.experimental.preprocessing.StringLookup(vocabulary=char_to_num.get_vocabulary(), mask_token=None, invert=True)

#-------- model

model = BuildModel()
model.summary()
print()

#--------save/load test

xmodel = keras.models.Model(model.get_layer(name="image").input,
                            model.get_layer(name="dense2").output)
SaveModel("m1.h5", xmodel)
m2 = LoadModel("m1.h5")
SaveModel("m2.h5", m2)
m3 = LoadModel("m2.h5")
SaveModel("m3.h5", m3)
m4 = LoadModel("m3.h5")
SaveModel("m4.h5", m4)

print()</code></pre>
All created files (m1.h5, m2.h5, m3.h5, m4.h5) are different, but must be same

**Comment by jvishnuvardhan** [comment]
@yelandgit Did you try evaluating all four models? How much difference you are noticing? Also, currently it throws a warning about compiling the model. Please find the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/776f4a41a79071166723189d9341d20f/untitled1061.ipynb) for our reference.

```
warnings
save HDF5: m1.h5
WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
WARNING:tensorflow:No training configuration found in the save file, so the model was *not* compiled. Compile it manually.
save HDF5: m2.h5
WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
WARNING:tensorflow:No training configuration found in the save file, so the model was *not* compiled. Compile it manually.
save HDF5: m3.h5
WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
WARNING:tensorflow:No training configuration found in the save file, so the model was *not* compiled. Compile it manually.
save HDF5: m4.h5
WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
```

**Comment by yelandgit** [comment]
It's just simple test without training to show different result after save/load. Nothing else

If we are talking about trained model, try 1st source code above this simple test.
Yes, I have tried to evaluate restored model from file after training. The recognition result was 0% vs 99% after training

**Comment by jvishnuvardhan** [comment]
@yelandgit I tried LSTM model from TF tutorials, trained the model, evaluated model performance, saved the model, loaded saved model, and evaluated performance. The results from original model and loaded_model are very similar. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/f44a17ea0a6a8fe1b083bfbbdc7dadda/time_series.ipynb). Thanks!

**Comment by yelandgit** [comment]
Ok, good for you, but I try to train model with LSTM layers using CTC for training, therefore I use example from Keras tutorial [OCR model for reading Captchas](https://keras.io/examples/vision/captcha_ocr/). Training process works fine, but I cannot restore saved trained model. See my 1st source code

**Comment by jvishnuvardhan** [comment]
@yelandgit I think this was fixed in recent `tf-nightly`. I ran your code (like your code, sorry for not using it earlier) and noticed the results are same before and after loading the model. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/8132c42e15026cbdd107f384342976b2/untitled1077.ipynb).

Please verify once and close the issue if this was resolved for you. thanks!
