### ISSUE TITLE
How to preprocess weights before loading them with model.load_weights ?

### ISSUE THREAD

**Issue by jrabary** [keras-team/keras#15405]
We need to fine-tune a Vision Transformer for task with different input resolution as the pre-training phase.
In this case we need to interpolate the positional embedding weights. 
Is there a way to do it easily with "model.load_weights" or we have to do the pre-processing manually ?

**Comment by jvishnuvardhan** [comment]
@jrabary This is not a bug/performance issue. Keras repo is mainly to discuss bugs/performance related issues. This is a good question for discussion in [TF Forum](https://discuss.tensorflow.org/tag/keras).

You can use model.get_weights() and model.set_weights() methods to get the weights, preprocess them and write them back to the model. 

May be [this](https://www.codespeedy.com/get_weights-and-set_weights-functions-in-keras-layers/) article will help you. Please post this kind of question in TF Forum for a discussion where there is a bug community to support this kind of questions. Thanks!
