### ISSUE TITLE
latest keras==2.6.0 is missing `install_requires`

### ISSUE THREAD

**Issue by asottile** [keras-team/keras#15406]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): **no**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **(any)**
- TensorFlow installed from (source or binary): **(n/a)**
- TensorFlow version (use command below): **(n/a)**
- Python version: **(n/a)**
- Bazel version (if compiling from source): **(n/a)**
- GPU model and memory: **(n/a)**
- Exact command to reproduce: **see below**

**Describe the problem**.

`pip install keras` no longer installs the dependencies of `keras` (the `install_requires` is no longer correct in terms of setuptools metadata).

This regressed somewhere between keras 2.4.3 and 2.6.0

**Describe the current behavior**.

```console
$ rm -rf *.whl && pip download -qq --no-deps 'keras==2.6.0' && unzip -p *.whl '*/METADATA' | grep -i require
```

(this produces no output because there are no dependencies in the distribution)

**Describe the expected behavior**.

this is the output of the previous version:

```console
$ rm -rf *.whl && pip download -qq --no-deps 'keras<2.6.0' && unzip -p *.whl '*/METADATA' | grep -i require
Requires-Dist: numpy (>=1.9.1)
Requires-Dist: scipy (>=0.14)
Requires-Dist: pyyaml
Requires-Dist: h5py
Requires-Dist: pytest ; extra == 'tests'
Requires-Dist: pytest-pep8 ; extra == 'tests'
Requires-Dist: pytest-xdist ; extra == 'tests'
Requires-Dist: flaky ; extra == 'tests'
Requires-Dist: pytest-cov ; extra == 'tests'
Requires-Dist: pandas ; extra == 'tests'
Requires-Dist: requests ; extra == 'tests'
Requires-Dist: markdown ; extra == 'tests'
Requires-Dist: pydot (>=1.2.4) ; extra == 'visualize'
```

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no): **no**
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**.

see commands above

**Source code / logs**.

see commands and output above

**Comment by LukeWood** [comment]
@jvishnuvardhan will create a PR

**Comment by bhack** [comment]
We already claim  that Tensorflow is required at:

https://github.com/keras-team/keras-io/blob/master/templates/getting_started/index.md#installing-keras

**Comment by jvishnuvardhan** [comment]
@bhack Some users are using just 

> The simplest way to install Keras is to via pip:
> 
> pip install keras

So, in the above attached PR, i updated the instructions as follows. With this modification, dependencies are also installed.

```
pip install tensorflow as tf
from tensorflow import keras
```

**Comment by bhack** [comment]
But we already claim in the next line:

> You will need to have the TensorFlow package installed. See detailed instructions.

**Comment by jvishnuvardhan** [comment]
@asottile I think this was resolved with the recently updated instructions on TF/Keras installation. Please check https://keras.io/getting_started/

I am closing this issue as this was resolved. Feel free to reopen if I am mistaken. Thanks!
