### ISSUE TITLE
Custom metrics as partial function not working as intended

### ISSUE THREAD

**Issue by MathisMohand** [keras-team/keras#15413]
Hello, when coding custom metrics (e.g; FBeta-score), defining it as a partial function : 
`def fbeta_score(beta=1, threshold=0.5):

    def fbeta(y_true, y_pred):

        # Clipping predictions just in case
        y_pred = K.clip(y_pred, 0, 1)
        y_pred = K.cast(y_pred + 1 - threshold, tf.int32)
        y_pred = K.cast(y_pred, tf.float32)

        true_positives = float(K.sum(y_true * y_pred))
        possible_positives = float(K.sum(y_true))
        predicted_positives = float(K.sum(y_pred))

        prec = true_positives / (predicted_positives + K.epsilon())
        rec = true_positives / (possible_positives + K.epsilon())

        beta_squared = beta ** 2
        num = (beta_squared + 1.0) * (prec * rec)
        den = (beta_squared * prec) + rec + K.epsilon()

        return num / den

    return fbeta`

This would have an unexpected behavior as every term in this metric were well computed, I even created two other metrics returning `num` and `den` respectively and the division between the two wouldn't match with this fbeta result. 
However, coding this function as only `fbeta(y_true, y_pred)` with hard-coded values for threshold and beta would result in right values for this metric.
Thus my issue wondering whether it is a wild behavior with this type of function as my metrics line in my model is like this : 
`metrics=[fbeta_score(beta=0.5)]` or that it might caused by something else that I would have overlooked.

**Comment by kumariko** [comment]
@MathisMohand In order to expedite the troubleshooting process, please provide a code snippet to reproduce the issue reported here.
