### ISSUE TITLE
Can i use object detection for captioning?

### ISSUE THREAD

**Issue by ersamo** [keras-team/keras#15410]
I trained the maskRCNN model for detection of the objects on my images and got the results in a file with a .pkl extension with a format x1, y1, x2, y2, class_id, bbox_score can I use the results for captioning as I need to use Keras model for this task

How can these features be different from what we can get with VGG as the format of the result is different?

**Comment by jvishnuvardhan** [comment]
@ersamo Object detection model is to detect objects (`class_id`) within a bounding box. For image captioning, you can follow this [this](https://keras.io/examples/vision/image_captioning/) tutorial.

This repository is mainly to discuss bugs/performance related issues. For a discussion, please raise a question in [`TF Forum`](https://discuss.tensorflow.org/) where there is a big community to support and learn from each other. Thanks!
