### ISSUE TITLE
[BUG] Omitting loss in model.compile will result in unhelpful error message

### ISSUE THREAD

**Issue by xhlulu** [keras-team/keras#15420]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Kaggle Notebook
- TensorFlow version (use command below): 2.4.1
- Python version: 3.7
- GPU model and memory: Intel CPU/Tesla P100

**Describe the problem**.

If you try to compile your model without specifying a loss, no error or warning will be given, but you will not be able to fit your model later on. Moreover, the error message encountered does not help us pinpoint the issue to be the omission of `loss` inside `model.compile()`.

**Describe the current behavior**.

```python
model.compile(optimizer="adam")

# ...

model.fit(x, y)
# => ValueError: No gradients provided for any variable: ['dense_3/kernel:0', 'dense_3/bias:0'].
```

**Describe the expected behavior**.

A more helpful error message or warning should be given when you try to compile without a loss:
```python
model.compile(optimizer="adam")
# => UserWarning: A loss was not detected when calling `compile`. Please specify a loss before fitting your model or you will get an error.
```

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no):
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**.

```python
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np

# Build a basic model:
model = keras.Sequential()
model.add(layers.Dense(64, kernel_initializer='uniform', input_shape=(10,)))
model.add(layers.Activation('sigmoid'))

# Let's use some random inputs/outputs for testing purposes:
x = np.random.randn(1000, 10)
y = np.random.randint(0, 2, (1000, 64))

# If you compile with a loss, it will work fine:
model.compile(loss='binary_crossentropy', optimizer='adam')
model.fit(x, y)

# If you omit the loss, no warning is given but obscure error messages will appear when you try to fit your model:
model.compile(optimizer='adam')
model.fit(x, y)
```

**Source code / logs**.

The following error trace (manually truncated due to length) does not tell us that the model failed to train due to the omission of `loss` in the `compile` method:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_42/181398162.py in <module>
      1 model.compile(optimizer='adam')
----> 2 model.fit(x, y)

[...]

ValueError: in user code:

    /opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:805 train_function  *
        return step_function(self, iterator)
    [...]
    /opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:598 apply_gradients
        grads_and_vars = optimizer_utils.filter_empty_gradients(grads_and_vars)
    /opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/optimizer_v2/utils.py:79 filter_empty_gradients
        ([v.name for _, v in grads_and_vars],))

    ValueError: No gradients provided for any variable: ['dense_3/kernel:0', 'dense_3/bias:0'].
```

**Comment by nilay121** [comment]
You are using one hot encoded vectors as the target variable, but in the loss function you are using "binary crossentropy", which is not correct rather you should use "categorical cross entropy", the loss obtained using "binary crossentropy" for this problem is wrong.
Kindly refer to this for more details :- https://stackoverflow.com/questions/42081257/why-binary-crossentropy-and-categorical-crossentropy-give-different-performances

**Comment by xhlulu** [comment]
@nilay121 The `loss` used here is tangential to the issue I reported, as I'm not reporting an issue with the convergence of some model. 

However, to answer your question, I am not using a one hot encoding, which you can verify with `y.sum(axis=1) == 1`. Thanks for bringing up as I noticed that I am using `softmax` instead of `sigmoid`, which I have corrected in the original post for correctness.

**Comment by innat** [comment]
@xhlulu [#15441](https://github.com/keras-team/keras/pull/15441)

**Comment by sushreebarsa** [comment]
@xhlulu I was able to replicate the issue on colab using TF [v2.4.1](https://colab.research.google.com/gist/sushreebarsa/425cd7b2ef769b4219a07dda1ff53c95/15420-2-4-1.ipynb) .The error message is improved in the latest TF version 2.8.0,could you please find the [gist](https://colab.research.google.com/gist/sushreebarsa/1f05dec9c9d499e7b38258c9b3b7ab6b/untitled122.ipynb) and let us know if it helps?Thanks!

**Comment by xhlulu** [comment]
@sushreebarsa that's perfect, thanks for the fix!

**Comment by xhlulu** [comment]
Closed in https://github.com/keras-team/keras/pull/15441

**Comment by sushreebarsa** [comment]
@xhlulu Thank you for the update!
Glad it is resolved.Thanks!
