### ISSUE TITLE
ValueError: The mask that was passed in was tf.RaggedTensor(values=Tensor("Placeholder_2:0", shape=(None,), dtype=bool),  row_splits=Tensor("Placeholder_3:0", shape=(None,), dtype=int64)) and cannot be applied to RaggedTensor inputs.  Please make sure that there is no mask passed in by upstream layers.

### ISSUE THREAD

**Issue by Electric-Dragon** [keras-team/keras#15427]
Tensorflow version: 2.6.0
Environment: Google Colab GPU Instance

---

Model Structure

```
model = tf.keras.Sequential([
    encoder,
    tf.keras.layers.Embedding(input_dim=len(encoder.get_vocabulary()),output_dim=64,mask_zero=True),
    tf.keras.layers.LSTM(64, return_sequences = True),
    tf.keras.layers.GlobalMaxPool1D(),
    tf.keras.layers.Dense(7)
])
```

Encoding Layer

```
encoder = tf.keras.layers.experimental.preprocessing.TextVectorization(
    max_tokens=VOCAB_SIZE)
```

---

The Problem

I am getting the following error when trying to load the model with `tf.keras.models.load_model()`:

```
ValueError: The mask that was passed in was tf.RaggedTensor(values=Tensor("Placeholder_2:0", shape=(None,), dtype=bool), row_splits=Tensor("Placeholder_3:0", shape=(None,), dtype=int64)) and cannot be applied to RaggedTensor inputs. Please make sure that there is no mask passed in by upstream layers.
```

---

The model was saved with the command `model.save(PATH)`
While saving, I get the following warning:

```
WARNING:absl:Found untraced functions such as lstm_cell_layer_call_and_return_conditional_losses, lstm_cell_layer_call_fn, lstm_cell_layer_call_fn, lstm_cell_layer_call_and_return_conditional_losses, lstm_cell_layer_call_and_return_conditional_losses while saving (showing 5 of 5). These functions will not be directly callable after loading.
```

---

Can I please get some help?

**Comment by Electric-Dragon** [comment]
Okay I solved this by removing the `mask_zero=True` attribute from the embedding layer, however, I'm not sure why this works and why it did not work with `mask_zero=True`. It would be helpful if someone can tell me the reason.

**Comment by sachinprasadhs** [comment]
When you use `mask_zero=True` in a layer, then all subsequent layers in the model need to support masking or an exception will be raised.
You can set mask_zero=False(which is default in Embedding layer) or in some cases for Ragged errors can be handled by setting ragged=False in the Input layer.
You can find more details on masking in the document [here](https://www.tensorflow.org/guide/keras/masking_and_padding).

**Comment by Electric-Dragon** [comment]
So I'll have to use `mask_zero=True` in all of the layers?

**Comment by sachinprasadhs** [comment]
> So I'll have to use `mask_zero=True` in all of the layers?

You don't have to, you can use it in the layer which is required and the subsequent layers should support, as of now you can proceed with mask=False, since it is throwing error.

**Comment by Electric-Dragon** [comment]
Okay thanks
