### ISSUE TITLE
save_model() still fails with custom layer and SavedModel format

### ISSUE THREAD

**Issue by jvcrnc** [keras-team/keras#15483]
Have I written custom code: Yes
OS Platform and Distribution: Windows 10
TensorFlow version (use command below): 2.6 and 2.8.0-dev20211003
Python version: 3.9.6
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Current behavior
I have defined a custom Keras layer which acts as a learnable lookup table. The layer is functional and learns throughout training. I am able to save the Keras model using both model.save('/path/to/dir') and model.save('/path/to/dir/model.h5').

However, tf.keras.models.load_model('/path/to/dir') fails whereas the H5 model seems to load properly with tf.keras.models.load_model('/path/to/dir/model.h5', custom_objects = {"Lookup": Lookup}). Passing custom_objects to the SavedModel call (without .h5) makes no difference.

For code example to reproduce, see related ticket:
https://github.com/tensorflow/tensorflow/issues/40912

**Comment by jvishnuvardhan** [comment]
@jvcrnc I can reproduce the issue with `tf-nightly`. [Here](https://colab.research.google.com/gist/jvishnuvardhan/dea8b2422ae9ac1c845b5d2ae6ec4b44/untitled249.ipynb) is a gist for our reference. Thanks!

**Comment by k-w-w** [comment]
This should now be fixed in the nightlies. https://github.com/tensorflow/tensorflow/commit/d3b6494e82085a397bad2260a43ea6769aa20f5d

**Comment by jvishnuvardhan** [comment]
I can confirm that this was resolved in recent `tf-nightly`. [Here](https://colab.research.google.com/gist/jvishnuvardhan/4eb55662fdf7254ce1e317034a4ebee3/untitled249.ipynb) is a gist for reference. Thanks @k-w-w
