### ISSUE TITLE
 AttributeError: module 'kerastools' has no attribute 'callback'

### ISSUE THREAD

**Issue by Gravityzd** [keras-team/keras#15481]
Hello!
I run a keras deep learning example on the IRIS data. However,I cant fit the model with the function of fit.
**The error message :**
"Error in py_get_attr_impl(x, name, silent): AttributeError: module 'kerastools' has no attribute 'callback'"
I check the version of R and packages:
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.3 LTS
**attached base packages:**
[1] stats     graphics  grDevices utils     datasets  methods   base     
other attached packages:
 [1] forcats_0.5.0   stringr_1.4.0   dplyr_1.0.3     purrr_0.3.4    
 [5] readr_1.4.0     tidyr_1.1.2     tibble_3.0.5    ggplot2_3.3.3  
 [9] tidyverse_1.3.0 keras_2.6.1  

**My code:**
library("keras")
library(tidyverse)
mnist <- dataset_mnist()
train_images <- mnist$train$x
train_labels <- mnist$train$y
test_images <- mnist$test$x
test_labels <- mnist$test$y

train_images <- array_reshape(train_images,c(60000,28*28))
train_images <- train_images/255
test_images <- array_reshape(test_images,c(10000,28*28))
test_images <- test_images/255

train_labels <- train_labels %>% to_categorical
test_labels <- test_labels %>% to_categorical

network <- 
keras_model_sequential() %>% 
layer_dense(units = 1000,activation = "relu",input_shape = c(28*28)) %>% 
layer_dense(units = 10,activation = "softmax")

network %>% 
compile(
    optimizer="rmsprop",
    loss="categorical_crossentropy",
    metrics=c("accuracy")
)

tmp.history <- network %>% 
fit(train_images,train_labels,epochs = 5,batch_size = 128)
 **The function of fit cant work .**
Error in py_get_attr_impl(x, name, silent): AttributeError: module 'kerastools' has no attribute 'callback'
Traceback:

1. model %>% fit(x_train, y_train, epochs = 200, batch_size = 5, 
 .     validation_split = 0.2)
2. fit(., x_train, y_train, epochs = 200, batch_size = 5, validation_split = 0.2)
3. fit.keras.engine.training.Model(., x_train, y_train, epochs = 200, 
 .     batch_size = 5, validation_split = 0.2)
4. normalize_callbacks_with_metrics(view_metrics, initial_epoch, 
 .     callbacks)
5. normalize_callbacks(callbacks)
6. lapply(callbacks, function(callback) {
 .     warn_callback(callback)
 .     if (inherits(callback, "keras.callbacks.TensorBoard")) 
 .         have_tensorboard_callback <<- TRUE
 .     if (inherits(callback, "KerasCallback")) {
 .         args <- list(r_set_context = callback$set_context, r_on_epoch_begin = callback$on_epoch_begin, 
 .             r_on_epoch_end = callback$on_epoch_end, r_on_train_begin = callback$on_train_begin, 
 .             r_on_train_end = callback$on_train_end, r_on_batch_begin = callback$on_batch_begin, 
 .             r_on_batch_end = callback$on_batch_end, r_on_predict_batch_begin = callback$on_predict_batch_begin, 
 .             r_on_predict_batch_end = callback$on_predict_batch_end, 
 .             r_on_predict_begin = callback$on_predict_begin, r_on_predict_end = callback$on_predict_end, 
 .             r_on_test_batch_begin = callback$on_test_batch_begin, 
 .             r_on_test_batch_end = callback$on_test_batch_end, 
 .             r_on_test_begin = callback$on_test_begin, r_on_test_end = callback$on_test_end, 
 .             r_on_train_batch_begin = callback$on_train_batch_begin, 
 .             r_on_train_batch_end = callback$on_train_batch_end)
 .         if (!isTRUE(all.equal(callback$on_batch_begin, empty_fun))) {
 .             args$r_on_train_batch_begin <- callback$on_batch_begin
 .         }
 .         if (!isTRUE(all.equal(callback$on_batch_end, empty_fun))) {
 .             args$r_on_train_batch_end <- callback$on_batch_end
 .         }
 .         do.call(tools$callback$RCallback, args)
 .     }
 .     else {
 .         callback
 .     }
 . })
7. FUN(X[[i]], ...)
8. do.call(tools$callback$RCallback, args)
9. tools$callback
10. `$.python.builtin.module`(tools, "callback")
11. `$.python.builtin.object`(x, name)
12. py_get_attr_or_item(x, name, TRUE)
13. py_get_attr(x, name)
14. py_get_attr_impl(x, name, silent)

Could you tell me how to fix this ?
Thanks a lot !

**Comment by jvishnuvardhan** [comment]
@Gravityzd Can you please share a simple standalone code in the correct format or share a .py file. You can also check [the tutorial](https://www.tensorflow.org/tutorials/customization/custom_training_walkthrough) on classification model with IRIS data. Thanks!

**Comment by Gravityzd** [comment]
Thank you for your reply. I use keras R package in R and I solved this problem by creat a new conda configured environment. The code can work correctly.

**Comment by qsh1neTHD** [comment]
> Thank you for your reply. I use keras R package in R and I solved this problem by creat a new conda configured environment. The code can work correctly.

Could you share the set up for a new conda env? 
I run into the same issue using the Keras3 lib in RStudio.
