### ISSUE TITLE
TypeError: Parameter to MergeFrom() must be instance of same class: expected tensorflow.TensorShapeProto got tensorflow.TensorShapeProto.

### ISSUE THREAD

**Issue by yosemite1998** [keras-team/keras#15484]
System information

Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 10.13.3
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
TensorFlow installed from (source or binary): binary
TensorFlow version (use command below): 2.6.0
Keras version (use command below): 2.6.0
Python version: 3.8.12
CUDA/cuDNN version: n/a
GPU model and memory: n/a
Describe the current behavior

When building simple Sequential model with Keras, strange errors occur. I'v tried to update Conda, re-create a new py38 virtualenv to establish another environment but still encountered the same issue. I'v searched similiar issues before, like re-install protobuf, add pywrap_tensorflow etc. but did not work for me. It should be compatible issue. The traceback is:
TypeError Traceback (most recent call last)
/var/folders/94/dvh9t1_x3w9bnp_ghskg3rzr0000gn/T/ipykernel_17083/2882519647.py in
1 # define the model
----> 2 model = Sequential([
3 Dense(units=16,input_shape=(1,),activation='relu'),
4 Dense(units=32,activation='relu'),
5 Dense(units=2,activation='softmax')

~/anaconda3/envs/py38/lib/python3.8/site-packages/tensorflow/python/training/tracking/base.py in _method_wrapper(self, *args, **kwargs)
528 self._self_setattr_tracking = False # pylint: disable=protected-access
529 try:
--> 530 result = method(self, *args, **kwargs)
531 finally:
532 self._self_setattr_tracking = previous_value # pylint: disable=protected-access

~/anaconda3/envs/py38/lib/python3.8/site-packages/tensorflow/python/keras/engine/sequential.py in init(self, layers, name)
112 """
113 # Skip the init in FunctionalModel since model doesn't have input/output yet
--> 114 super(functional.Functional, self).init( # pylint: disable=bad-super-call
115 name=name, autocast=False)
116 base_layer.keras_api_gauge.get_cell('Sequential').set(True)

~/anaconda3/envs/py38/lib/python3.8/site-packages/tensorflow/python/training/tracking/base.py in _method_wrapper(self, *args, **kwargs)
528 self._self_setattr_tracking = False # pylint: disable=protected-access
529 try:
--> 530 result = method(self, *args, **kwargs)
531 finally:
532 self._self_setattr_tracking = previous_value # pylint: disable=protected-access

~/anaconda3/envs/py38/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py in init(self, *args, **kwargs)
316 self._steps_per_execution = None
317
--> 318 self._init_batch_counters()
319 self._base_model_initialized = True
320

~/anaconda3/envs/py38/lib/python3.8/site-packages/tensorflow/python/training/tracking/base.py in _method_wrapper(self, *args, **kwargs)
528 self._self_setattr_tracking = False # pylint: disable=protected-access
529 try:
--> 530 result = method(self, *args, **kwargs)
531 finally:
532 self._self_setattr_tracking = previous_value # pylint: disable=protected-access

~/anaconda3/envs/py38/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py in _init_batch_counters(self)
324 # evaluate, and predict.
325 agg = variables.VariableAggregationV2.ONLY_FIRST_REPLICA
--> 326 self._train_counter = variables.Variable(0, dtype='int64', aggregation=agg)
327 self._test_counter = variables.Variable(0, dtype='int64', aggregation=agg)
328 self._predict_counter = variables.Variable(

~/anaconda3/envs/py38/lib/python3.8/site-packages/tensorflow/python/ops/variables.py in call(cls, *args, **kwargs)
266 return cls._variable_v1_call(*args, **kwargs)
267 elif cls is Variable:
--> 268 return cls._variable_v2_call(*args, **kwargs)
269 else:
270 return super(VariableMetaclass, cls).call(*args, **kwargs)

~/anaconda3/envs/py38/lib/python3.8/site-packages/tensorflow/python/ops/variables.py in _variable_v2_call(cls, initial_value, trainable, validate_shape, caching_device, name, variable_def, dtype, import_scope, constraint, synchronization, aggregation, shape)
248 if aggregation is None:
249 aggregation = VariableAggregation.NONE
--> 250 return previous_getter(
251 initial_value=initial_value,
252 trainable=trainable,

~/anaconda3/envs/py38/lib/python3.8/site-packages/tensorflow/python/ops/variables.py in (**kws)
241 shape=None):
242 """Call on Variable class. Useful to force the signature."""
--> 243 previous_getter = lambda **kws: default_variable_creator_v2(None, **kws)
244 for _, getter in ops.get_default_graph()._variable_creator_stack: # pylint: disable=protected-access
245 previous_getter = _make_getter(getter, previous_getter)

~/anaconda3/envs/py38/lib/python3.8/site-packages/tensorflow/python/ops/variable_scope.py in default_variable_creator_v2(next_creator, **kwargs)
2660 shape = kwargs.get("shape", None)
2661
-> 2662 return resource_variable_ops.ResourceVariable(
2663 initial_value=initial_value,
2664 trainable=trainable,

~/anaconda3/envs/py38/lib/python3.8/site-packages/tensorflow/python/ops/variables.py in call(cls, *args, **kwargs)
268 return cls._variable_v2_call(*args, **kwargs)
269 else:
--> 270 return super(VariableMetaclass, cls).call(*args, **kwargs)
271
272

~/anaconda3/envs/py38/lib/python3.8/site-packages/tensorflow/python/ops/resource_variable_ops.py in init(self, initial_value, trainable, collections, validate_shape, caching_device, name, dtype, variable_def, import_scope, constraint, distribute_strategy, synchronization, aggregation, shape)
1601 self._init_from_proto(variable_def, import_scope=import_scope)
1602 else:
-> 1603 self._init_from_args(
1604 initial_value=initial_value,
1605 trainable=trainable,

~/anaconda3/envs/py38/lib/python3.8/site-packages/tensorflow/python/ops/resource_variable_ops.py in _init_from_args(self, initial_value, trainable, collections, caching_device, name, dtype, constraint, synchronization, aggregation, distribute_strategy, shape)
1755 else:
1756 shape = initial_value.shape
-> 1757 handle = eager_safe_variable_handle(
1758 initial_value=initial_value,
1759 shape=shape,

~/anaconda3/envs/py38/lib/python3.8/site-packages/tensorflow/python/ops/resource_variable_ops.py in eager_safe_variable_handle(initial_value, shape, shared_name, name, graph_mode)
237 """
238 dtype = initial_value.dtype.base_dtype
--> 239 return _variable_handle_from_shape_and_dtype(shape, dtype, shared_name, name,
240 graph_mode, initial_value)
241

~/anaconda3/envs/py38/lib/python3.8/site-packages/tensorflow/python/ops/resource_variable_ops.py in _variable_handle_from_shape_and_dtype(shape, dtype, shared_name, name, graph_mode, initial_value)
177 handle_data.is_set = True
178 handle_data.shape_and_type.append(
--> 179 cpp_shape_inference_pb2.CppShapeInferenceResult.HandleShapeAndType(
180 shape=shape.as_proto(), dtype=dtype.as_datatype_enum))
181

TypeError: Parameter to MergeFrom() must be instance of same class: expected tensorflow.TensorShapeProto got tensorflow.TensorShapeProto.

**Comment by yosemite1998** [comment]
Yes,I also did not reproduce it on colab..It seems I have to do sth. big with my local env. thanks

**Comment by sushreebarsa** [comment]
@yosemite1998 Could you please confirm if we can close this ticket as it is resolved ? Thank you!
