### ISSUE TITLE
when i read images data set for validation with ImageDataGenerator it returns subclasses but doesn't read images from it.

### ISSUE THREAD

**Issue by mazharnoor13** [keras-team/keras#15495]
The first one read images and classes in it.  the second one read subfolders but not the images inside folders.

here is the code

from keras.preprocessing.image import ImageDataGenerator
datagen = ImageDataGenerator()

train_images = datagen.flow_from_directory('D:/Dataset mood/my dataset', class_mode='categorical', subset='training')
valit_images = datagen.flow_from_directory('D:/Dataset mood/valid', class_mode='categorical', subset='validation')

Here is the output///
Found 6999 images belonging to 7 classes.
Found 0 images belonging to 7 classes.

**Comment by chunduriv** [comment]
@mazharnoor13, You can remove `subset` argument from `flow_from_directory`. It can be used only if `validation_split` is set in `ImageDataGenerator`.

You can change the code as shown below will resolve your issue
```
train_images = datagen.flow_from_directory('D:/Dataset mood/my dataset', class_mode='categorical')
valit_images = datagen.flow_from_directory('D:/Dataset mood/valid', class_mode='categorical')
```
I tried it on `Dogs_Vs_Cats` data and it is working as expected. Please check the [gist here](https://colab.research.google.com/gist/chunduriv/12f2b22048fbc37b655f5f50206f33b3/15495.ipynb). Thanks!

**Comment by mazharnoor13** [comment]
Thanks @chunduriv
