### ISSUE TITLE
Setting None to fname parameter in Keras utils get_file() throws an error

### ISSUE THREAD

**Issue by yalegria** [keras-team/keras#15498]
Using Tensorflow 2.4.1.

The following call to get_file() method throws an error:

```
custom_img_url = 'https://xyz.com/images/abc/my_image.jpg'
custom_img_path = tf.keras.utils.get_file(fname=None,origin=custom_img_url)
```

Error:

`TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'`

I was hoping that by using **fname=None**, Keras will grab the filename from the origin URL value. Calling get_file() inside a loop will require to set the fname parameter beforehand, which would be extra unnecessary processing.

**Comment by sushreebarsa** [comment]
@yalegria Could you  please try with the latest **TF v2.6.0** and let us know if it helps ? Was able to run the code successfully using another image url on Colab,please find the [gist](https://colab.research.google.com/gist/sushreebarsa/da40e8070c620405cb41e7b017c9798f/untitled465.ipynb) for reference .Thank you!
