### ISSUE TITLE
tensoflow.keras.preprocessing.image_dataset_from_directory doesn't recognize there are files in a directory when labels are supplied as a list/tupple comp:keras stat:awaiting

### ISSUE THREAD

**Issue by AngCamp** [keras-team/keras#15501]
em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

https://keras.io/api/preprocessing/image/#imagedatasetfromdirectory-function

My code:
In order to reproduce my example please go to the following kaggle dataset: https://www.kaggle.com/c/recursion-cellular-image-classification/data

Open a notebook, download that data.  Kaggle will host the compiler and then you may chosoe either to run the environment with a CPU, GPU or TPU.  I've tried all three and the same issue comes up in all of them.

```
#import libraries
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation, Dropout, Flatten, Conv2D, MaxPooling2D
from tensorflow.keras.preprocessing.image import ImageDataGenerator #for image normalization
import numpy as np
import pandas as pd 
import os
import glob
import PIL
import PIL.Image

#setting parameters for the images and for the model for image_dataset_from_directory
image_count = len(glob.glob1("../input/recursion-cellular-image-classification-224-jpg/train/train","*.jpeg"))
image = PIL.Image.open("../input/recursion-cellular-image-classification-224-jpg/train/train/HEPG2-01_1_B03_s1.jpeg")
img_width, img_height = image.size
batch_size = 100 # number of samples taken in training round

#print some useful information about our image files
print("There are "+str(image_count)+" .jpeg images in the ../train folder.")
print("The images are "+str(img_width)+" pixels wide.")
print("The images are "+str(img_height)+" pixels high.")
print("We will train with a batch size of "+str(batch_size))

#run this to show that the directory has image files in it
image_count = len(glob.glob1("../input/recursion-cellular-image-classification-224-jpg/train/train","*.jpeg"))
print(image_count)

#get the labels (sirna) from the dataset
train_metadat_df = pd.read_csv("../input/recursion-cellular-image-classification-224-jpg/new_train.csv")
train_metadat_df.head()

#reorganize the order or labels to make them match alphanumeric order of the filenames (as required by image_dataset_from_directory)
train_metadat_df.sort_values(by='filename').head()

#this will be our list of image labels
train_labels = train_metadat_df.sort_values(by='filename')['sirna'].tolist()
print(train_labels[0:5])

#now run the function
train_ds = tf.keras.preprocessing.image_dataset_from_directory(
  "../input/recursion-cellular-image-classification-224-jpg/train/train",
  validation_split=0.2,
  subset="training",
  labels= train_labels,
  label_mode= "categorical",
  seed=123,
  image_size=(img_height, img_width),
  batch_size=batch_size)
```

Running the function will return:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_43/281099960.py in <module>
     11   seed=123,
     12   image_size=(img_height, img_width),
---> 13   batch_size=batch_size)

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/preprocessing/image_dataset.py in image_dataset_from_directory(directory, labels, label_mode, class_names, color_mode, batch_size, image_size, shuffle, seed, validation_split, subset, interpolation, follow_links)
    180       shuffle=shuffle,
    181       seed=seed,
--> 182       follow_links=follow_links)
    183 
    184   if label_mode == 'binary' and len(class_names) != 2:

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/preprocessing/dataset_utils.py in index_directory(directory, labels, formats, class_names, shuffle, seed, follow_links)
     96                        'of files in the target directory. len(labels) is %s '
     97                        'while we found %s files in %s.' % (
---> 98                            len(labels), len(filenames), directory))
     99   else:
    100     i = 0

ValueError: Expected the lengths of `labels` to match the number of files in the target directory. len(labels) is 73030 while we found 0 files in ../input/recursion-cellular-image-classification-224-jpg/train/train.
```

More proof there are images in the directory:
There are ~73000 .jpeg files in that directory and when I run it on ../input/recursion-cellular-image-classification-224-jpg/train it finds ~54000 of them and trains them all on one class (because they are all stored in one file).

```
#moved up one folder from ../train/train to ../train
train_ds = tf.keras.preprocessing.image_dataset_from_directory(
  "../input/recursion-cellular-image-classification-224-jpg/train",
  validation_split=0.2,
  subset="training",
  labels= train_labels,
  label_mode= "categorical",
  seed=123,
  image_size=(img_height, img_width),
  batch_size=batch_size)
```
this will return:
```
2021-10-12 22:25:56.268255: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-10-12 22:25:56.271461: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/conda/lib
2021-10-12 22:25:56.271523: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-10-12 22:25:56.271550: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (c05fd61b7193): /proc/driver/nvidia/version does not exist
2021-10-12 22:25:56.273711: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-10-12 22:25:56.275021: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
Using 58424 files for training.
```

**System information**
- using Tensorflow in a kaggle notebook
- currently no GPU is turned on
- tensorflow version 2.4.1

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

I have raised an issue with the documentation here: https://github.com/keras-team/keras/issues/15500
I do not think the description of how to use the function by supplying the labels with a list or tupple is detailed enough and there should be examples.

**Comment by jvishnuvardhan** [comment]
@AngCamp Can you please share a simple standalone code to reproduce the issue. Also, just to demonstrate the issue, please try to use smaller dataset. Current dataset in the above example is too big which takes too much time and space for downloading/uploading and reproducing the issue. Thanks!

**Comment by GeoffCan** [comment]
Hi everyone. First time poster....this has been a mystery for me for some time as well. Keras says it will take a list of labels and attribute them to your images so they can be trained on the labels. In my experimentations it appears to do just that, BUT... when generating the image/label dataset from the module dataset_utils.py/index_directory in lines 575-579 where it prints out how many files and classes were encountered (The if checking of 'labels' has fallen all the way through to the default else: used for "categorical" labels), class_names contains only 1 directory..so 1 is returned. What I think needs to happen is a Counter needs to be applied to the passed in labels (or label_list?) to determine how many categorical classes it contains. THEN this number is returned for class_names, not the number of directories.
