### ISSUE TITLE
Attention module not working with TimeDistributed layer

### ISSUE THREAD

**Issue by DriesSmit** [keras-team/keras#15515]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras):
   Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
   Linux Ubuntu 21.04
- TensorFlow installed from (source or binary):
  binary
- TensorFlow version (use command below):
TensorFlow 2.5.0
- Python version:
Python 3.6.9
- Bazel version (if compiling from source):
- GPU model and memory:
  GeForce GTX 1080 and 64 gb memory
**Describe the problem**.

I am trying to apply the keras `TimeDistributed` layer to the `Attention` layer in Keras but it gives and error.

**Describe the current behavior**.
When I try to run the code I just get an error as follows:
`NotImplementedError: Please run in eager mode or implement the compute_output_shape method on your layer (Attention).`

**Describe the expected behavior**.
I expect the code snippet example below to run without an error. The TimeDistributed layer should apply the attention layer to each timestep in the tensor provided.
**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no):
No. I am willing to try and fix this if someone has any guidance on how.

**Standalone code to reproduce the issue**.

```
import tensorflow as tf
from tensorflow.keras.layers import Input, Dense, LSTM, Conv1D, TimeDistributed, Flatten, Concatenate, Attention

# Variable-length int sequences.
query_input = tf.keras.Input(shape=(None, 1,100), dtype='float32')
value_input = tf.keras.Input(shape=(None, 4,100), dtype='float32')

print("query_seq_encoding: ", query_input)
print("value_seq_encoding: ", value_input)

# Query-value attention of shape [batch_size, Tq, filters].
query_value_attention_seq = TimeDistributed(tf.keras.layers.Attention())(
    [query_input, value_input])
```

**Comment by kumariko** [comment]
@DriesSmit Could you please check https://github.com/keras-team/keras/issues/15515#issuecomment-946129038 and let us know if this issue resolved or not?

**Comment by tomerk** [comment]
Triage notes:
unclear if this is meant to work because timedistributed layer expects only one input. Workaround may be to do it by hand if needed. Timedistributed layer should maybe raise a better error.

**Comment by DriesSmit** [comment]
The workaround did work yes :) I had to do it by hand. Thanks for the comments! You can close this issue if you wish.

**Comment by tempdeltavalue** [comment]
This problem still exists  (encoder from here https://www.tensorflow.org/text/tutorials/transformer )


inputs = tf.keras.Input(shape=(None,None,), name="inputs")
padding_mask = tf.keras.Input(shape=(1, 1, None), name="padding_mask")
enc_outputs = TimeDistributed(encoder) ([inputs, padding_mask])




 KerasTensor(type_spec=TensorSpec(shape=(None, 1, 1, None), dtype=tf.float32, name='padding_mask'), name='padding_mask', description="created by layer 'padding_mask'"), but it was called on an input with incompatible shape (None, 1, None).
WARNING:tensorflow:Model was constructed with shape (None, 1, 1, None) for input KerasTensor(type_spec=TensorSpec(shape=(None, 1, 1, None), dtype=tf.float32, name='padding_mask'), name='padding_mask', description="created by layer 'padding_mask'"), but it was called on an input with incompatible shape (None, 1, None).
WARNING:tensorflow:Model was constructed with shape (None, 1, 1, None) for input KerasTensor(type_spec=TensorSpec(shape=(None, 1, 1, None), dtype=tf.float32, name='padding_mask'), name='padding_mask', description="created by layer 'padding_mask'"), but it was called on an input with incompatible shape (None, 1, None).
WARNING:tensorflow:Model was constructed with shape (None, 1, 1, None) for input KerasTensor(type_spec=TensorSpec(shape=(None, 1, 1, None), dtype=tf.float32, name='padding_mask'), name='padding_mask', description="created by layer 'padding_mask'"), but it was called on an input with incompatible shape (None, 1, None).
WARNING:tensorflow:Model was constructed with shape (None, 1, 1, None) for input KerasTensor(type_spec=TensorSpec(shape=(None, 1, 1, None), dtype=tf.float32, name='padding_mask'), name='padding_mask', description="created by layer 'padding_mask'"), but it was called on an input with incompatible shape (None, 1, None).
WARNING:tensorflow:Model was constructed with shape (None, 1, 1, None) for input KerasTensor(type_spec=TensorSpec(shape=(None, 1, 1, None), dtype=tf.float32, name='padding_mask'), name='padding_mask', description="created by layer 'padding_mask'"), but it was called on an input with incompatible shape (None, 1, None).
Traceback (most recent call last):
  File "lstm_transformer.py", line 103, in <module>
    enc_outputs = TimeDistributed(encoder) ([inputs, padding_mask])
  File "/home/temp/.local/lib/python3.6/site-packages/keras/engine/base_layer.py", line 977, in __call__
    input_list)
  File "/home/temp/.local/lib/python3.6/site-packages/keras/engine/base_layer.py", line 1115, in _functional_construction_call
    inputs, input_masks, args, kwargs)
  File "/home/temp/.local/lib/python3.6/site-packages/keras/engine/base_layer.py", line 848, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "/home/temp/.local/lib/python3.6/site-packages/keras/engine/base_layer.py", line 888, in _infer_output_signature
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/temp/.local/lib/python3.6/site-packages/keras/layers/wrappers.py", line 271, in call
    output_shape = self.compute_output_shape(input_shape)
  File "/home/temp/.local/lib/python3.6/site-packages/keras/layers/wrappers.py", line 190, in compute_output_shape
    child_output_shape = self.layer.compute_output_shape(child_input_shape)
  File "/home/temp/.local/lib/python3.6/site-packages/keras/engine/functional.py", line 470, in compute_output_shape
    layer_output_shapes = layer.compute_output_shape(layer_input_shapes)
  File "/home/temp/.local/lib/python3.6/site-packages/keras/engine/base_layer.py", line 793, in compute_output_shape
    'method on your layer (%s).' % self.__class__.__name__)
NotImplementedError: Please run in eager mode or implement the `compute_output_shape` method on your layer (TFOpLambda).

**Comment by mishc9** [comment]
Which version of tensorflow are you using in this example?

**Comment by tempdeltavalue** [comment]
@mishc9 
tensorflow               2.6.2

(and I don't use Attention layer)

**Comment by tempdeltavalue** [comment]
@mishc9 

you can try this colab if you're interested in 

https://colab.research.google.com/drive/1X6zuidDqZqf4xM5YBEygPlyy6KVJwYC1?usp=sharing

**Comment by k00shan** [comment]
I made this layer from MultiHeadAttention layer and and used in in a model. When i try to make that model time distributed I get the same error of compute_output_shape is not implemented. Is there any solution?

```
class TransformerEncoder(layers.Layer):
    def __init__(self, embed_dim, dense_dim, num_heads, **kwargs):
        super().__init__(**kwargs)
        self.embed_dim = embed_dim
        self.dense_dim = dense_dim
        self.num_heads = num_heads
        self.attention = layers.MultiHeadAttention(
            num_heads=num_heads, key_dim=embed_dim, dropout=0.3
        )
        self.dense_proj = keras.Sequential(
            [layers.Dense(dense_dim, activation=tensorflow.nn.gelu), layers.Dense(embed_dim), ]
        )
        self.layernorm_1 = layers.LayerNormalization()
        self.layernorm_2 = layers.LayerNormalization()

    def call(self, inputsQ, inputsV, mask=None):
        if mask is not None:
            mask = mask[:, tensorflow.newaxis, :]

        attention_output = self.attention(inputsQ, inputsV, attention_mask=mask)
        proj_input = self.layernorm_1(inputsQ + attention_output)
        proj_output = self.dense_proj(proj_input)
        return self.layernorm_2(proj_input + proj_output)

    def compute_output_shape(self, input_shape):
        # Assuming the input shape is (batch_size, sequence_length, input_dim)
        return input_shape[0]

    def get_config(self):
        config = super().get_config()
        config.update({
            "embed_dim": self.embed_dim,
            "dense_dim": self.dense_dim,
            "num_heads": self.num_heads
        })
        return config
```
