### ISSUE TITLE
Input 0 of layer denseC1 is incompatible with the layer: : expected min_ndim=2, found ndim=1.

### ISSUE THREAD

**Issue by WiktorMP** [keras-team/keras#15521]
I have been writing a simple ML model with tf keras and found an issue. I read the documentation and i know that dense layer needs a 2 dimensional input and it corresponds with the output dimension of  input layer but for some reasons it returns output in shape (x,). Could someone please help me?

This is the model

class Player:

    def __init__(self, name, team, model):
        self.name = name
        self.hand = []
        self.team = team

        # model input is either the model or False
        if not model:
            self.inputs = tf.keras.Input(shape=(56,), name="input")
            self.model = self.build_model()

    def build_model(self):
        color_branch = self.build_color_branch()
        number_branch = self.build_number_branch()

        model = tf.keras.models.Model(inputs=self.inputs,
                                      outputs=[number_branch, color_branch],
                                      name="kerasv1")
        return model

    def build_color_branch(self):
        dense_1 = tf.keras.layers.Dense(100, activation='relu', name="denseC1")
        dense_2 = tf.keras.layers.Dense(50, name="denseC2")
        dense_3 = tf.keras.layers.Dense(30, name="denseC3")
        dense_4 = tf.keras.layers.Dense(4, name="denseC4")
        final = "softmax"

        x = dense_1(self.inputs)
        x = dense_2(x)
        x = dense_3(x)
        x = dense_4(x)
        x = Activation(final, name="color")(x)
        return x

    def build_number_branch(self):
        dense_1 = tf.keras.layers.Dense(100, name="denseN1")
        dense_2 = tf.keras.layers.Dense(50, name="denseN2")
        dense_3 = tf.keras.layers.Dense(30, name="denseN3")
        dense_4 = tf.keras.layers.Dense(13, name="denseN4")
        final = "softmax"

        x = dense_1(self.inputs)
        x = dense_2(x)
        x = dense_3(x)
        x = dense_4(x)
        x = Activation(final, name="number")(x)
        return x

and when i run

player.model(np.array([ 0 for _ in range(56)])

it gives the error
ValueError: Input 0 of layer denseC1 is incompatible with the layer: : expected min_ndim=2, found ndim=1. Full shape received: (56,)

**Comment by ToutaF** [comment]
@WilczekxxD , im facing the same issue, could you please provide the code which fixed yours.
Thank you in advance.
this is the model:
`       inputs = Input(shape=(col,)) # input tensor, col=126
        hidden1 = Dense(units=50)(inputs) # hidden layer 1
        hidden2 = Dense(units=50)(hidden1) # hidden layer 2
        outputs = Dense(self._action_size, activation='softmax')(hidden2)  
        model = Model(inputs, outputs)
        model.compile(loss='categorical_crossentropy', optimizer=self._optimizer,metrics=['accuracy'])
        return model`
the error occurs here:
`q_values = self.q_network.predict(state)`

**Comment by ToutaF** [comment]
@[AdityaKane2001](https://github.com/AdityaKane2001) how to batch the inputs please?

**Comment by cdahms123** [comment]
@fatenlouati Here is a simple example that gets past this error, I'm using TF 2.6.0 if that matters:

```
# model_inherit.py

import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '1'
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

BATCH_SIZE = 64

class MNIST(keras.Model):
    def __init__(self):
        super().__init__()
        self.dense1 = layers.Dense(64, input_shape=(BATCH_SIZE, 784), activation='relu')
        self.dense2 = layers.Dense(10, activation='softmax')
    # end function

    def call(self, inputs):
        x = self.dense1(inputs)
        x = self.dense2(x)
        return x
    # end function
# end class

def main():
    model = MNIST()
    model.build((BATCH_SIZE, 784))
    model.summary()

    (x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

    x_train = x_train.reshape(60000, 784).astype(np.float32) / 255.0
    x_test = x_test.reshape(10000, 784).astype(np.float32) / 255.0

    model.compile(
        loss=keras.losses.SparseCategoricalCrossentropy(),
        optimizer=keras.optimizers.Adam(),
        metrics=["accuracy"],
    )

    model.fit(x_train, y_train, batch_size=BATCH_SIZE, epochs=2, validation_split=0.2)

    test_scores = model.evaluate(x_test, y_test, verbose=2)

    print("Test loss:", test_scores[0])
    print("Test accuracy:", test_scores[1])
# end function

if __name__ == '__main__':
    main()
```

**Comment by Rehan-Afzaal** [comment]
For the initial Player class:
Before:
player.model(np.array([ 0 for _ in range(56)]))

After (using numpy to reshape the input):
input_data = np.array([0 for _ in range(56)])
batched_input = input_data.reshape(1, -1)
player.model(batched_input)

For fatenlouati's model:
Before:
q_values = self.q_network.predict(state)

Assuming state is a numpy array with shape (126,):
After:
batched_state = state.reshape(1, -1)
q_values = self.q_network.predict(batched_state)


cdahms123's Solution: cdahms123 provided a more detailed example using the MNIST dataset, showing how to batch the input data properly. Their model expects input data in the shape (BATCH_SIZE, 784), and they correctly reshape the dataset to fit this shape.
Always ensure that your input data shape matches what the model expects. In the case of models expecting batches, even if you're predicting for a single sample, reshape the data to have a batch dimension.
