### ISSUE TITLE
keras get_custom_objects()

### ISSUE THREAD

**Issue by SeanLee97** [keras-team/keras#15544]
**System information**.

Keras version (you are using): 2.6.0
TensorFlow version (you are using): 2.6.0
Are you willing to contribute it (Yes/No) : Yes

**Describe the feature and the current behavior/state**.

```bash
>>> import keras; keras.__version__
'2.6.0'
>>> import tensorflow; tensorflow.__version__
'2.6.0'
>>> from keras.utils.generic_utils import get_custom_objects
>>> from keras.utils import get_custom_objects
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'get_custom_objects' from 'keras.utils' (/usr/local/lib/python3.7/dist-packages/keras/utils/__init__.py)
>>> from tensorflow.keras.utils.generic_utils import get_custom_objects
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow.keras.utils.generic_utils'
>>> from tensorflow.keras.utils import get_custom_objects
```

It seems like that the `keras.utils.get_custom_objects` has been removed in the v2.6.0, and it is still preserved in the `keras.utils.generic_utils`. But in Tensorflow (v2.6.0),  `get_custom_objects` is implemented in `tensorflow.keras.utils`. It confuse me why removing `get_custom_objects` from `keras.utils` rather than `keras.utils.generic_utils`? I think it would be better to follow TF Keras to keep the `get_custom_objects` in `keras.utils` .

**Comment by nikhil1111111** [comment]
> @SeanLee97, To use `Keras`, will need to have the `TensorFlow package installed`. Once TensorFlow is installed, just import `Keras` via `from tensorflow import keras`. For more information you can refer [here](https://keras.io/getting_started/).
> 
> We have to import `get_custom_objects` as shown below
> 
> ` from tensorflow.keras.utils import get_custom_objects`

finally i got this error!!  thank you!!:
