### ISSUE TITLE
Support building without Bazel

### ISSUE THREAD

**Issue by KOLANICH** [keras-team/keras#15559]
**System information**.

TensorFlow version (you are using): doesn't matter
Are you willing to contribute it (Yes/No) : I probably can, but it is likely to be rejected. I remember that in the past Keras used to be built with setuptools.

**Describe the feature and the current behavior/state**.

I strongly dislike Bazel and don't want this be executed on my PC despite Google pushing hard it everywhere. It has numerous drawbacks, which Google is OK with (and won't fix them). I am not Google, I am not OK with Bazel drawbacks.

**Will this change the current api? How?**

No.

**Who will benefit from this feature?**

Users who build Keras wheel from source.

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**

- Do you want to contribute a PR? (yes/no): Likely no.
- Briefly describe your candidate solution(if contributing): Implement building with setuptools/flit_core/poetry_core at your choice. Setuptools is preferred.

**Comment by qlzh727** [comment]
Unfortunately we build keras both internally within Google and externally on Github. Removing the bazel as build dependency will cause big maintenance overhead for us which we can't accommodate at the moment.

Btw, if you would like to just build pip/wheel package, you still can do it via https://github.com/keras-team/keras/blob/master/keras/tools/pip_package/build_pip_package.sh
