### ISSUE TITLE
InvalidArgumentError: 9 root error(s) found.

### ISSUE THREAD

**Issue by innat** [keras-team/keras#15577]
https://discuss.tensorflow.org/tag/keras

**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- TensorFlow installed from (source or binary): Colab
- TensorFlow version (use command below): 2.6
- Python version: Colab
- Bazel version (if compiling from source):
- GPU model and memory: TPU
- Exact command to reproduce:

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

## Describe the problem

I was trying to run [`keras/vit`](https://keras.io/examples/vision/image_classification_with_vision_transformer/) code example on TPU but it causes the following error. 

> InvalidArgumentError: 9 root error(s) found.
  (0) Invalid argument: {{function_node __inference_train_function_49310}} Incompatible shapes: [256,25,64] vs. [144,64]

>	 [[{{node gradient_tape/model_1/patch_encoder_1/add/BroadcastGradientArgs}}]]
	 [[TPUReplicate/_compile/_12894506912996439067/_4]]
	 [[tpu_compile_succeeded_assert/_14236840403296971761/_5/_197]]
  (1) Invalid argument: {{function_node __inference_train_function_49310}} Incompatible shapes: [256,25,64] vs. [144,64]

>	 [[{{node gradient_tape/model_1/patch_encoder_1/add/BroadcastGradientArgs}}]]
	 [[TPUReplicate/_compile/_12894506912996439067/_4]]
	 [[tpu_compile_succeeded_assert/_14236840403296971761/_5/_245]]
  (2) Invalid argument: {{function_node __inference_train_function_49310}} Incompatible shapes: [256,25,64] vs. [144,64]

 I think it's due to the use of `tf.image.extract_patches` function on TPU. But not sure. 

## [Reproducible Coe. ](https://colab.research.google.com/drive/1DAQpG9YD-5vH-A-jfaISwFzMkE6oAlm9?usp=sharing)

**Describe the expected behavior**.

It should simply run. 

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no):
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**.

Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Source code / logs**.

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by innat** [comment]
cc @ksalama

**Comment by bhack** [comment]
Is this going to happen on training?  As I cannot reproduce your error on Colab/TPU with the vanilla notebook.
Can you share your Colab?

**Comment by innat** [comment]
@bhack hi, I've shared a reproducible colab link, mentioned above. If it's not working, please try [this](https://colab.research.google.com/drive/1DAQpG9YD-5vH-A-jfaISwFzMkE6oAlm9?usp=sharing).

**Comment by bhack** [comment]
Ok now I can reproduce it I don't think it is related `tf.image.extract_patches` as it is in the official list without special notes:
https://cloud.google.com/tpu/docs/tensorflow-ops

Have you tried to check the TPU compatiblity graph:
https://cloud.google.com/tpu/docs/cloud-tpu-tools#tpu_compatibility_graph

I don't if on colab it could be retrieved with:
https://colab.research.google.com/github/tensorflow/tpu/blob/master/tools/colab/profiling_tpus_in_colab.ipynb

**Comment by innat** [comment]
OK, I just replace class `Patches` and `PatchEncoder` layer with a single class `PatchEmbed` layer that does a similar thing but doesn't use `tf.image.extract_patches` and it runs successfully. 

```python
def create_vit_classifier():
    inputs = layers.Input(shape=input_shape)
    # # Create patches.
    # patches = Patches(patch_size)(inputs)
    # # Encode patches.
    # encoded_patches = PatchEncoder(num_patches, projection_dim)(patches)

    encoded_patches = PatchEmbed(img_size=(72, 72), 
                                 patch_size=(patch_size, patch_size), in_chans=3, 
                                 embed_dim=projection_dim)(inputs)
```

**Comment by bhack** [comment]
Are you sure that it was about `tf.image.extract_patches`? As I see that you have also removed the keras embedding layer. I don't know what is the behavior inside the TPU strategy_scope:

https://github.com/keras-team/keras/blob/42bf9972492f47c3d3c249de9c20942ba217937d/keras/layers/embeddings.py#L83-L99

**Comment by innat** [comment]
I'm not sure if it causes for `tf.image.extract_patches`. I guess came from seeing the error logs, i.e. `patch_encoder_3`; maybe from layer `PatchEncoder`. 

```
InvalidArgumentError: 9 root error(s) found.
  (0) Invalid argument: {{function_node __inference_train_function_43005}}
    Incompatible shapes: [100,25,64] vs. [144,64]

	# ---------------------------------------  HERE ------------------------
	 [[{{node gradient_tape/model_1/patch_encoder_3/add/BroadcastGradientArgs}}]]
	 [[TPUReplicate/_compile/_58268965962327260/_4]]
	 [[tpu_compile_succeeded_assert/_14858208428749173052/_5/_197]]
```

Also in the following docstring, it says if my embedding matrix is too large for the GPU, I may consider placing the operation on CPU.  

https://github.com/keras-team/keras/blob/42bf9972492f47c3d3c249de9c20942ba217937d/keras/layers/embeddings.py#L83-L99

But note that here I'm using TPU. Even if I set `tf.config.set_soft_device_placement(True)`, it doesn't work either.

**Comment by bhack** [comment]
What I see is:
`tf.keras.layers.Add`
> It takes as input a list of tensors, **all of the same shape**, and returns a single tensor (also of the same shape).

In your example if add a check in your PatchEncoder
```
    def call(self, patch):
        positions = tf.range(start=0, limit=self.num_patches, delta=1)
        pos_emb = self.position_embedding(positions)
        proj =  self.projection(patch)
        tf.test.TestCase().assertEqual(proj.shape,pos_emb.shape)
        encoded = pos_emb + proj
        return encoded
```


`AssertionError: TensorShape([None, None, 64]) != TensorShape([144, 64])`
