### ISSUE TITLE
RecursionError when creating large models using Functional API.

### ISSUE THREAD

**Issue by sebastian-sz** [keras-team/keras#15596]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.6.0-0-g919f693420e 2.6.0
- Python version: 3.7.12 - Google Colab
- Bazel version (if compiling from source): N/A
- GPU model and memory: N/A
- Exact command to reproduce:

```python
import tensorflow as tf

inputs = tf.keras.Input(1)

x = inputs
for _ in range(975):
  x = tf.keras.layers.Dense(1)(x)

model = tf.keras.Model(inputs=inputs, outputs=[x])
```

**Describe the problem**.
When creating a **large** model (like EfficientNetV2XL or Resnet-RS-420) using Keras functional API, the model creation will throw Python's `RecursionError`. 

**Describe the current behavior**.
For simplest comparison let's run a for loop 1000 times:

```python
for _ in range(1000):
    continue  
# OK
```

Let's create a Keras model with the same number of layers:

```python
inputs = tf.keras.Input(1)

x = inputs
for _ in range(1000):
  x = tf.keras.layers.Dense(1)(x)  # OK

# Creating the mode = RecursionError
model = tf.keras.Model(inputs=inputs, outputs=[x])
```

For a more real life example you can preview a part of [my repository](https://github.com/sebastian-sz/efficientnet-v2-keras/blob/3e6cf205e8eb3cf5fda0ef6c86119e4cdf39e30f/efficientnet_v2/efficientnet_v2.py#L759).

**Describe the expected behavior**.
Currently one needs to make workarounds and increase Python's default recursion limit using the `sys` module.

```python
import sys

current_limit = sys.getrecursionlimit()
target_limit = 2000
if current_limit < target_limit:
    sys.setrecursionlimit(target_limit)
```
Is there a way to create these models, using functional API without having to interfere with Python's default settings?

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no): I could, but I'm not sure where the problem is.
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing): If you point me where the problem might be I can submit a PR with fix.

**Standalone code to reproduce the issue**.
End to End [Colab Link](https://colab.research.google.com/drive/1_756odl-KXb3RZ0S_2an-ut0OzwfZpEn?usp=sharing)

**Source code / logs**.

```python
---------------------------------------------------------------------------
RecursionError                            Traceback (most recent call last)
<ipython-input-15-42c0bafd7673> in <module>()
      5   x = tf.keras.layers.Dense(1)(x)
      6 
----> 7 model = tf.keras.Model(inputs=inputs, outputs=[x])

7 frames
... last 1 frames repeated, from the frame below ...

/usr/local/lib/python3.7/dist-packages/keras/engine/functional.py in _build_map_helper(tensor, finished_nodes, nodes_in_progress, nodes_in_decreasing_depth, layer_indices)
   1053     for tensor in node.keras_inputs:
   1054       _build_map_helper(tensor, finished_nodes, nodes_in_progress,
-> 1055                         nodes_in_decreasing_depth, layer_indices)
   1056 
   1057   finished_nodes.add(node)

RecursionError: maximum recursion depth exceeded
```

### Related links
[Keras PR](https://github.com/keras-team/keras/pull/14935) where the discussion about it emerged.

**Comment by mattdangerw** [comment]
Triage notes from Keras team: this is expected behavior.

For the application in question (EfficientNetV2XL), could actually include the snippet above in the model building code.

```
current_limit = sys.getrecursionlimit()
target_limit = 2000
if current_limit < target_limit:
    sys.setrecursionlimit(target_limit)
```

**Comment by sebastian-sz** [comment]
@mattdangerw Thanks for the answer - that solves the issue.
