### ISSUE TITLE
Low Priority: Typo BugFix lost in 2.6.x Branch -- "optimizers"  has Typo in Function Name "tf.keras.optimizers.Adam"  --  See line  463 in file   keras/engine/training.py -- Original Fix in  #15227 

### ISSUE THREAD

**Issue by scottc21** [keras-team/keras#15590]
**System information**.
All Platforms.
This is a fix was accidentally lost from "2.6", but is present on both "master" and "2.7".   
See (  #15583 ) for information on the abandoned  origin/r2.6.1" branch, so see how this was accidentally lost.

_IMHO_: this is low-priority, since this Typo is in the comment section for the scripts "Example".  See script for exact context here.

**Describe the problem**.
There is an existing closed bugFix (#15227) for a typo in the word "**optimizers**" in the function call  below: 
--   tf.keras.**optimizers**.Adam()
--  The original bugFix is outlined in ( #15227)   ==>>  Fix small mistake `optimizer` to `optimizers` 

This bugFix appears to be present in the "master" and "2.7" branches, but was accidentally lost on the "2.6" branch.

**Describe the current behavior**.
In the current "2.6" branch see the file  "keras/engine/training.py" and goto line 463.  
You will see the following typo shown below:
-- tf.keras.optimizer.Adam

If you look at the Keras 2.6.1 docs, this will also show that this is a typo.  See the doc URL below:
-- https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam

**Describe the expected behavior**.
If a user   "cuts and pastes" this example section into a real script, they will get a run-time error due to the typo in the function name. 

**Standalone code to reproduce the issue**.
n/a

**Source code / logs**.
In the current "2.6" branch see the file  "keras/engine/training.py" and goto line 463. 
![Fix_2 6_branch___Typo_for__optimizers___Nov04_](https://user-images.githubusercontent.com/93684290/140432547-5be475bd-7607-46f0-a5ec-e59876604392.png)

**Comment by sachinprasadhs** [comment]
Thanks for reporting this bug, Have raised the PR for the same. #15595

**Comment by sachinprasadhs** [comment]
Closing this issue based on the comment mentioned for the PR https://github.com/keras-team/keras/pull/15595#issuecomment-962118385. Thank you.
