### ISSUE TITLE
resnet50 code has bug?，the first stack1' first block don't use 1*1 conv 

### ISSUE THREAD

**Issue by chenying99** [keras-team/keras#15635]
https://github.com/keras-team/keras/blob/2c48a3b38b6b6139be2da501982fd2f61d7d48fe/keras/applications/resnet.py#L453

https://github.com/keras-team/keras/blob/2c48a3b38b6b6139be2da501982fd2f61d7d48fe/keras/applications/resnet.py#L271

https://github.com/keras-team/keras/blob/2c48a3b38b6b6139be2da501982fd2f61d7d48fe/keras/applications/resnet.py#L213

the first stack1' first block should be conv_shortcut=False  (but the function block1' paramerer default value conv_shortcut=True)

Here are my previous discussions about restnet with other teams:

https://github.com/d2l-ai/d2l-en/pull/1839

**Comment by old-school-kid** [comment]
Hi @chenying99 
In the [ResNet Paper](https://arxiv.org/pdf/1512.03385.pdf) they said 

> (B) The projection shortcut in Eqn.(2) is used to
> match dimensions (done by 1×1 convolutions)

This doesnt mean 1x1 convolution is there only to solve the problem of dimensionality increase. As a matter of fact **Table 1** in the paper explicitly lays out the architecture and there is a 1x1 convolution in the first stack too.

**Comment by old-school-kid** [comment]
1x1 Conv is not present in ResNet18 and ResNet34 but is present in ResNet50, ResNet101 and ResNet152. The discussion you provided is maybe about ResNet18 and ResNet34. And to quote @goldmermaid from the said discussion

> I see what you were saying. The TF code is used for modelling Resnet50, Resnet101 and Resnet152, which may not be a good reference for Resnet18.

I think this helps you out.

**Comment by chenying99** [comment]
Thank you for your explanation. The reason is probably that the number of output channels of resnet50 in the last convolutional layer is 4 * filter


`x = layers.Conv2D(4 * filters, 1, name=name + '_3_conv')(x)`


https://github.com/keras-team/keras/blob/2c48a3b38b6b6139be2da501982fd2f61d7d48fe/keras/applications/resnet.py#L249
