### ISSUE TITLE
Interrupting training crashes Python kernel when training on GPU for the first time with MirroredStrategy

### ISSUE THREAD

**Issue by JivanRoquet** [keras-team/keras#15637]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): binary (`pip install tensorflow`)
- TensorFlow version (use command below): 2.4.3
- Python version: 3.7
- GPU model and memory: Nvidia Tesla V100

**Describe the problem**.

When using multi-GPU training in a Jupyter Notebook:

```python
strategy = tf.distribute.MirroredStrategy()
model_ = ...
with strategy.scope():
    model = model_.compile(loss='categorical_crossentropy', optimizer='adam', metrics=["accuracy"])
```

Then launching training:

```python
model.fit(...)
```

**Describe the current behavior**.

- when initial training runs to the end, subsequent trainings can be interrupted fine
- when initial training itself is interrupted, the Jupyter kernel dies

Detailed step-by-step procedure:

1. compile the model with mirrored strategy
2. launch training with `model.fit()`
3. let the training go to its own end -> otherwise kernel dies if interrupted here
4. after initial training completed, re-compile the model with mirrored strategy
5. launch another training
6. interrupt this training -> works fine, kernel doesn't die

If training was interrupted at step 3. then the kernel dies systematically.

<img width="1313" alt="Screenshot 2021-11-11 at 13 13 11" src="https://user-images.githubusercontent.com/6452675/141304515-f38c174f-74bd-4fe3-ad46-b732e267b388.png">

**Describe the expected behavior**.

- when initial training is interrupted, the Jupyter kernel should not die

**Source code / logs**.

No error message — the Jupyter iPython kernel simply dies with no message.

**Current workaround**.

The current workaround I found is to run the first training with just 1 epoch, let it complete, then I can recompile the model and re-train at will with no crashes. Less than ideal, but it works.

**Comment by sushreebarsa** [comment]
@JivanRoquet Could you please try with the latest stable `TF v2.7.0` and let us know if it helps ? Thank you!

**Comment by JivanRoquet** [comment]
@sushreebarsa I did the following:

```shell
pip install tensorflow --upgrade
pip install tensorflow-gpu --upgrade
```

Now I have TensorFlow v2.7.0 but when running `model.fit()` I have the following error repeatedly:

```
UnknownError: 5 root error(s) found.
  (0) UNKNOWN:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node model_transformer/conv_block_1/conv1d_3/Conv1D
 (defined at /home/ubuntu/anaconda3/envs/tensorflow2_latest_p37/lib/python3.7/site-packages/keras/layers/convolutional.py:238)
]]
```

I didn't change anything apart from upgrading TensorFlow. What do I need to do in this case?

**Comment by jvishnuvardhan** [comment]
@JivanRoquet Quick question to find whether the root-cause is keras or distribution strategy. I guess distribution strategy. 
Are you using Keras or TF model?
Did you try without Mirrored strategy? Do you notice this issues without distribution strategy.

If you think this is more related to distribution strategy, please open this issue in TF repository https://github.com/tensorflow/tensorflow/issues as this keras repo is mainly for keras related issues. Thanks!

**Comment by JivanRoquet** [comment]
I guess this would be the distribution strategy then because effectively, the problem doesn't appear when not using the mirrored strategy. I'm using a Keras model however (function API), so perhaps the problem might be the result of a combination of the two.

**Comment by jvishnuvardhan** [comment]
@JivanRoquet Thanks for the quick response. This is more related to `distribution strategy`. Can you please open the issue in TF repository.  Thanks!

**Comment by JivanRoquet** [comment]
Sure thing. Closing here for now.
