### ISSUE TITLE
New and modern model and weights for applications 

### ISSUE THREAD

**Issue by birolkuyumcu** [keras-team/keras#15648]
New and modern model and weights for applications 
i think these aded to repo 

https://github.com/leondgarse/keras_cv_attention_models

**Comment by sanatmpa1** [comment]
@birolkuyumcu,

Can you take a look at this [guideline](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md#contributing-to-keras-applications) for contributing to Keras applications and follow the same? Thanks!
