### ISSUE TITLE
`keras.backend.random_bernoulli()` raises exception if dtype is not a float

### ISSUE THREAD

**Issue by t-kalinowski** [keras-team/keras#15659]
Hello, passing a non-floating dtype to `keras.backend.random_bernoulli()` raises an exception.

```python
>>> import tensorflow.keras.backend as K
>>> K.random_bernoulli((), dtype = 'float32')
<tf.Tensor: shape=(), dtype=float32, numpy=0.0>
>>> K.random_bernoulli((), dtype = 'int32')
ValueError: Must specify maxval for integer dtype tf.int32
>>> K.random_bernoulli((), dtype = 'bool')
ValueError: Invalid dtype. Dtype should be one of float16, float32, float64, int32 and int64, but is <dtype: 'bool'>.
```
The issue is that the user supplied dtype is passed to `tf.random.uniform()`. 
https://github.com/keras-team/keras/blob/5171cc7925857e1f826c19ecf7f587184e1230d1/keras/backend.py#L6287

One way to resolve this is to fix the dtype passed to `tf.random.uniform(dtype = floatx())`, and then only pass the user supplied dtype through to the `tf.ones()` and `tf.zeros()` call on the subsequent line.

I'm happy to submit a PR if this sounds reasonable.

**Comment by sachinprasadhs** [comment]
You can keep dtype as None and it will consider dtype as `floatx()` and will not throw any error.
Please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/6ee87dffe7e4350e764b5c00014a5a2f/15659.ipynb), Thanks!

**Comment by t-kalinowski** [comment]
Would it be helpful if I submit a PR?

**Comment by t-kalinowski** [comment]
Bump, for the stale bot. 
To clarify, the linked gist is not helpful and seems to be intended for a different issue. Perhaps there has been some misunderstanding? 
(Also, I replied _after_ the label "stat:awaiting response" was added, the stale-issue bot seems to be malfunctioning.)

**Comment by sachinprasadhs** [comment]
Here is the link to the code https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/backend.py#L6145, if  you want to contribute, you can raise a PR with your suggested changes.
