### ISSUE TITLE
Wrong explanation in documentation (multi-head-attention)

### ISSUE THREAD

**Issue by utkutopcuoglu** [keras-team/keras#15654]
In the docs, the explanation for the call arguments for **multi-head-attention** is wrong. 
Currently it says:

`return_attention_scores: A boolean to indicate whether the output should be attention output if True, or (attention_output, attention_scores) if False. Defaults to False.`

It should be the reverse. Here is the link: [multi-head-attention](https://keras.io/api/layers/attention_layers/multi_head_attention/#:~:text=return_attention_scores%3A%20A%20boolean%20to%20indicate%20whether%20the%20output%20should%20be%20attention%20output%20if%20True%2C%20or%20(attention_output%2C%20attention_scores)%20if%20False.%20Defaults%20to%20False.).

It should be:
`return_attention_scores: A boolean to indicate whether the output should be attention output if False, or (attention_output, attention_scores) if True. Defaults to False.`

**Comment by qlzh727** [comment]
I think the current docstring is correct, which was updated in https://github.com/keras-team/keras/pull/14920.
