### ISSUE TITLE
Current implementation only supports equal length strides in the row and column dimensions.

### ISSUE THREAD

**Issue by Gandalf401** [keras-team/keras#15667]
When I use layers related to DepthwiseConv2d operation, such as tf.keras.layers.SeparableConv2d, exception occurs like that: 'Current implementation only supports equal length strides in the row and column dimensions. [Op: DepthwiseConv2dNative]'. It means that i cannot use parameter 'strides' like [1, 2], however, that conflicts with the documentation, which allows 'strides' with list format without mentioning that elements within the list should be the same.
I'm using TensorFlow 2.0.0, and I guess this bug exisits in 3D scenariothe and further edition.
### System information
Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-74-generic x86_64)
TensorFlow 2.0.0 installed by anaconda
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
NVIDIA-SMI 460.80 Driver Version: 460.80 CUDA Version: 11.2
### Describe the current behavior
tf.keras.layers.SeparableConv2d do not support different value for rows and columns, caused by depthwiseConv2dNative not supporting different stride value for rows and columns.
### Describe the expected behavior
tf.keras.layers.SeparableConv2d and depthwiseConv2dNative obviously should support different value for rows and columns.
###Standalone code to reproduce the issue
e.g.
separable_conv2d = tf.keras.layer.SeparableConv2D(32, 3, [1, 2], depth_multiplier=3)
print(separable_conv2d(np.ones((100, 28, 28, 1), dtype=np.float32))

### Other info / logs
![image](https://user-images.githubusercontent.com/94270103/142407336-e33dbd76-a87e-4c40-ab5d-b6a217bc7a45.png)

**Comment by beginner401** [comment]
It seems that when I upgrade my tensorflow version to the latest 2.7, similar exceptions still occurs, the error-info takes a bit changes, but the problem stay the same. Here is the erro info: 
![image](https://user-images.githubusercontent.com/94270103/142407564-5b7d1ebc-b29d-48fe-a4c4-4c9ca407ad04.png)
And the link to original issue post on [tensorflow/tensorflow](https://github.com/tensorflow/tensorflow/) is:
https://github.com/tensorflow/tensorflow/issues/53055.

**Comment by gowthamkpr** [comment]
@Gandalf401 In the [documentation](https://www.tensorflow.org/api_docs/python/tf/keras/layers/SeparableConv2D), it clearly states that 
_Current implementation only supports equal length strides in the row and column dimensions. Specifying any stride value != 1 is incompatible with specifying any dilation_rate value != 1._ describing the `strides` argument. This is expected behavior

**Comment by burnpanck** [comment]
Unforuntately, the documentation of [`tf.nn.depthwise_conv2d`](https://www.tensorflow.org/api_docs/python/tf/nn/depthwise_conv2d)
*does not mention* any such limitation, yet it behaves the same.

**Comment by inkzk** [comment]
> Unfortunately, the documentation of [`tf.nn.depthwise_conv2d`](https://www.tensorflow.org/api_docs/python/tf/nn/depthwise_conv2d) _does not mention_ any such limitation, yet it behaves the same.

@burnpanck hi, is inequal strides length supported now? And which versions of tensorflow or keras should I use?
THX!
