### ISSUE TITLE
Understanding hinge loss

### ISSUE THREAD

**Issue by jay-thakur** [keras-team/keras#15665]
I am learning `Tensorflow 2.X`. I am following [this page][1] to understand hinge loss.

I went through the [standalone usage][2] code.

Code is below - 

```
 y_true = [[0., 1.], [0., 0.]]
 y_pred = [[0.6, 0.4], [0.4, 0.6]]
 h = tf.keras.losses.Hinge()
 h(y_true, y_pred).numpy()
```

the output is `1.3`

I tried to manually calculate it by given formula 

`loss = maximum(1 - y_true * y_pred, 0)`

my code - 
```
def hinge_loss(y_true, y_pred):
  return tf.reduce_mean(tf.math.maximum(1. - y_true * y_pred, 0.))

print("Hinge Loss :: ", hinge_loss(y_true, y_pred).numpy())
```

But I am getting `0.9`.

**Where am i doing wrong ? Am i missing any concept here ?**

Kindly guide.

  [1]: https://www.tensorflow.org/api_docs/python/tf/keras/losses/Hinge
  [2]: https://www.tensorflow.org/api_docs/python/tf/keras/losses/Hinge#standalone_usage

**Comment by chunduriv** [comment]
@jay-thakur, I tried to run your code on Colab using TF v2.7 and faced `TypeError: can't multiply sequence by non-int of type 'list'` Please find the [gist here](https://colab.research.google.com/gist/chunduriv/d57bd96951850120e2a63f955944dbd4/untitled62.ipynb) for reference. Thanks!

**Comment by jay-thakur** [comment]
Hi @chunduriv ,

please try this code. - 

```
y_true = tf.Variable([[0., 1.], [0., 0.]])
y_pred = tf.Variable([[0.6, 0.4], [0.4, 0.6]])

def hinge_loss(y_true, y_pred):
  return tf.reduce_mean(tf.math.maximum(1. - y_true * y_pred, 0.))

print("Hinge Loss :: ", hinge_loss(y_true, y_pred).numpy())
```

Thanks!

**Comment by chunduriv** [comment]
Yes, now i am able to replicate reported issue on Colab using TF v2.7. Please find the [gist here](https://colab.research.google.com/gist/chunduriv/64765b329c9e31f2c1d83ad28b701c59/untitled63.ipynb) for reference. Thanks!

**Comment by old-school-kid** [comment]
Hi @jay-thakur 
Hinge loss is a binary function for binary labels consisting of -1s and 1s and not 0s and 1s. If you're labels consists of 0s and 1s then it is normalized to -1 and 1. And hence you are observing the error. 
Hope this helps!

**Comment by jay-thakur** [comment]
@old-school-kid Got it. Thank you so much.
