### ISSUE TITLE
TypeError: The added layer must be an instance of class Layer. Found: <keras.layers.convolutional.Conv1D object at ...

### ISSUE THREAD

**Issue by nihayahzahra** [keras-team/keras#15664]
I want building the CNN Model

`CNNmodel = keras.Sequential()  
CNNmodel.add(Conv1D(32, 2, activation='relu', input_shape=(20,28) )) # 32 convolution filters used each of size 2
CNNmodel.add(Conv1D(64, 3, activation='relu' ))       # 64 convolution filters used each of size 3
CNNmodel.add(MaxPooling1D(pool_size=(1,)))            # choose the best features via pooling
CNNmodel.add(Dropout(0.25))                           # randomly turn neurons on and off to improve convergence
CNNmodel.add(Flatten())                               # flatten we only want a classification output
CNNmodel.add(Dense(150, activation='relu'))           # fully connected to get all relevant data
CNNmodel.add(Dropout(0.1))                            # one more dropout
CNNmodel.add(Dense(1, activation='sigmoid'))          # output 

lr_schedule = keras.optimizers.schedules.ExponentialDecay(
    initial_learning_rate=1e-2,
    decay_steps=10000,
    decay_rate=0.9)
opt = keras.optimizers.Adagrad(learning_rate=lr_schedule)
CNNmodel.compile(loss='binary_crossentropy', optimizer=opt, metrics=['accuracy'])

CNNhistory = CNNmodel.fit(x_train, y_train, validation_data=(x_val, y_val),  epochs=20, batch_size=128) # Getting score metrics
scores = CNNmodel.evaluate(x_test, y_test) 
print("Accuracy: %.2f%%" % (scores[1]*100))`

but TypeError: The added layer must be an instance of class Layer. Found: <keras.layers.convolutional.Conv1D object at

**Comment by chunduriv** [comment]
@nihayahzahra, How did you import **Conv1D** layer? Can you try it as `from tensorflow.keras.layers import Conv1D, MaxPooling1D,Dropout, Flatten, Dense`.

This worked for me on Tensorflow 2.7.0

```
from tensorflow import keras
from tensorflow.keras.layers import Conv1D, MaxPooling1D,Dropout, Flatten, Dense
from tensorflow.keras import models

CNNmodel = keras.Sequential()
CNNmodel.add(Conv1D(32, 2, activation='relu', input_shape=(20,28) )) # 32 convolution filters used each of size 2
CNNmodel.add(Conv1D(64, 3, activation='relu' )) # 64 convolution filters used each of size 3
CNNmodel.add(MaxPooling1D(pool_size=(1,))) # choose the best features via pooling
CNNmodel.add(Dropout(0.25)) # randomly turn neurons on and off to improve convergence
CNNmodel.add(Flatten()) # flatten we only want a classification output
CNNmodel.add(Dense(150, activation='relu')) # fully connected to get all relevant data
CNNmodel.add(Dropout(0.1)) # one more dropout
CNNmodel.add(Dense(1, activation='sigmoid')) # output

CNNmodel.summary()

lr_schedule = keras.optimizers.schedules.ExponentialDecay(
initial_learning_rate=1e-2,
decay_steps=10000,

decay_rate=0.9)
opt = keras.optimizers.Adagrad(learning_rate=lr_schedule)

CNNmodel.compile(loss='binary_crossentropy', optimizer=opt, metrics=['accuracy'])
```

**Comment by nihayahzahra** [comment]
I use this 

`from tensorflow import keras
from keras.layers import Dense, Dropout, Flatten, GRU, SimpleRNN, LSTM, Bidirectional, Activation, TimeDistributed
from keras.layers.convolutional import Conv1D, MaxPooling1D
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers`

**Comment by nihayahzahra** [comment]
I use this 

from tensorflow import keras
from keras.layers import Dense, Dropout, Flatten, GRU, SimpleRNN, LSTM, Bidirectional, Activation, TimeDistributed
from keras.layers.convolutional import Conv1D, MaxPooling1D
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers

and when I used your code, still error AttributeError : module 'tensorflow._api.v1.keras.optimizers' has no attribute 'schedules'

**Comment by chunduriv** [comment]
@nihayahzahra, I am not able to replicate your issue. Can you let us know what is the version of `TF` and `Keras` are you using? You can try imports as shown below
```
from tensorflow import keras
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Dense, Dropout, Flatten, GRU, SimpleRNN, LSTM, Bidirectional, Activation, TimeDistributed
from sklearn.model_selection import train_test_split
```

**Comment by nihayahzahra** [comment]
I use tensorflow version 1.13.1 and keras version 2.2.4.. but it's been updated

**Comment by chunduriv** [comment]
According to [Installing Keras](https://keras.io/getting_started/#installing-keras): To use `Keras`, will need to have the `TensorFlow` package installed. Once TensorFlow is installed, just import Keras via:  `from tensorflow import keras`

I tried sample code using `Tensorflow 2.7.0` and it is working. Please check the [gist here](https://colab.research.google.com/gist/chunduriv/80e097d38548bcb94117c980d5e189ac/15664.ipynb). Thanks!

**Comment by nihayahzahra** [comment]
yes it's work when I used tensorflow 2.7.0

thank you

**Comment by chunduriv** [comment]
@nihayahzahra, Please feel free to close the issue as issue was resolved. Thanks!
