### ISSUE TITLE
tf.keras.layers.Conv2dTranspose doesn't support different dilation_rate

### ISSUE THREAD

**Issue by beginner401** [keras-team/keras#15677]
**System information**.
Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-74-generic x86_64)
TensorFlow 2.0.0 installed by anaconda
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
NVIDIA-SMI 460.80 Driver Version: 460.80 CUDA Version: 11.2

**Describe the problem**.
While using tf.keras.layers.Conv2dTranspose with dilation param setting different values for row and columns, it turns out to be a bug. Inferred from the error info, there exists an assert that dilation[0] has to be equal to dilation[1], however, that conflicts with the documentation and I suggest that there's no reason for not supporting various values for dilation. If I am wrong, please correct me and maybe the documentation should be revised, or maybe the function should be improved.

**Describe the current behavior**.
While using tf.keras.layers.Conv2dTranspose with dilation param setting different values for row and columns, it turns out to be a bug. Inferred from the error info, there exists an assert that dilation[0] has to be equal to dilation[1].

**Describe the expected behavior**.
Different values for dilation param accross different axes should be support, or, documentation should be revised.

**Standalone code to reproduce the issue**.
e.g.
conv2d_transpose = tf.keras.layers.Conv2DTranspose(32, (3, 2), (1, 1), 'valid', dilation_rate=(1, 2))
print(conv2d_tanspose(np.ones((100, 28, 28, 1), dtype=np.float32)))
**Source code / logs**.
![1637298055(1)](https://user-images.githubusercontent.com/94270103/142567674-1cb7ab06-05c3-42ca-86ed-bd1504a72ed8.png)

**Comment by sanatmpa1** [comment]
@beginner401,

Can you share the complete stand alone code or colab gist to reproduce the issue? Thanks!

**Comment by beginner401** [comment]
@beginner401 https://colab.research.google.com/gist/beginner401/b5ba37ece87af7a32d5b175be547e3fa/github15677.ipynb
Just code like above can trigger this bug. If the link is invalid, just try to run code below:
import tensorflow as tf
import numpy as np
conv2d_transpose = tf.keras.layers.Conv2DTranspose(32, (3, 2), (1, 1), 'valid', dilation_rate=(1, 2))
print(conv2d_transpose(np.ones((100, 28, 28, 1), dtype=np.float32)))

**Comment by sanatmpa1** [comment]
I am able to reproduce the reported issue with `Conv2dTranspose`. Please find the [gist here](https://colab.sandbox.google.com/gist/sanatmpa1/95b77f588da7ae68dfd2cfa95d68ad6e/15677.ipynb). Thanks!

**Comment by mattdangerw** [comment]
Triage notes: we should update the docs. It looks like currently variable rates not supported because the underlying tensorflow op does not support it.
