### ISSUE TITLE
layers.RandomCrop raises error

### ISSUE THREAD

**Issue by d-01** [keras-team/keras#15681]
#### System information

Environment: Google Colab

Python: 3.7.12 (default, Sep 10 2021, 00:21:48)  [GCC 7.5.0]

TensorFlow: 2.7.0

#### Describe the problem

`tf.keras.layers.RandomCrop()` doesn't work for some input types.

#### Describe the current behavior

`tf.keras.layers.RandomCrop()` depending on the input type:

1. ndarray of type uint8: works as expected.
1. ndarray of type float32: works as expected.
1. **tf.Tensor of type uint8: raises TypeError.**
1. tf.Tensor of type float32: works as expected.

#### Describe the expected behavior

Expected to work with tf.Tensor of type uint8.

#### Standalone code to reproduce the issue

Colab: https://colab.research.google.com/drive/1d4FF1nL9xAYs-lfg1ylsfaQ0UniyB0Wb?usp=sharing

```python
import numpy as np
import tensorflow as tf

# Works with ndarray
input_numpy = np.zeros((2, 128, 128, 3), dtype=np.uint8)
print('Input:', type(input_numpy).__name__, input_numpy.shape, input_numpy.dtype)
output_numpy = tf.keras.layers.RandomCrop(64, 64)(input_numpy)
print('Output:', type(output_numpy).__name__, output_numpy.shape, output_numpy.dtype)
print()

# Raises error with tf.Tensor
input_tensor = tf.keras.layers.Input((128, 128, 3), batch_size=2, dtype=tf.uint8)
print('Input:', type(input_tensor).__name__, input_tensor.shape, input_tensor.dtype)
output_tensor = tf.keras.layers.RandomCrop(64, 64)(input_tensor)
print('Output:', type(output_tensor).__name__, output_tensor.shape, output_tensor.dtype)
```

Output:

```
Input: ndarray (2, 128, 128, 3) uint8
Output: EagerTensor (2, 64, 64, 3) <dtype: 'uint8'>

Input: KerasTensor (2, 128, 128, 3) <dtype: 'uint8'>
Output:
	--------------------------------------------------------------------------------
    TypeError: Exception encountered when calling layer "random_crop_5" (type
    RandomCrop).

    true_fn and false_fn arguments to tf.cond must have the same number, type, and
    overall structure of return values.

    true_fn output: Tensor("random_crop_5/cond/crop_to_bounding_box/Slice:0",
    shape=(2, 64, 64, 3), dtype=uint8)
    false_fn output: Tensor("random_crop_5/cond/resize/ResizeBilinear:0",
    shape=(2, 64, 64, 3), dtype=float32)

    Error details:
    Tensor("random_crop_5/cond/crop_to_bounding_box/Slice:0", shape=(2, 64, 64, 3),
    dtype=uint8) and Tensor("random_crop_5/cond/resize/ResizeBilinear:0",
    shape=(2, 64, 64, 3), dtype=float32) have different types

    Call arguments received:
      • inputs=tf.Tensor(shape=(2, 128, 128, 3), dtype=uint8)
      • training=True
```

#### Comment

As far as I understand the problem is related to `tf.image.resize()` function which always convert `uint8` to `float32` (except for `method='nearest'`, by default `method='bilinear'`).

**Comment by sushreebarsa** [comment]
@sachinprasadhs Was able to replicate the issue on colab using TF v2.7.0 and tf-nightly.Please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/c67af173abeaa9f935c1062c4be62c70/15681.ipynb) for  reference.Thank you!

**Comment by sachinprasadhs** [comment]
If you provide a input value as tensor there is no issue reported for `tf.uint8`, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/fe047877931796352ca69baa5789a057/15681.ipynb). Thanks!

**Comment by d-01** [comment]
@sachinprasadhs sorry for misconception, but under *tf.Tensor* I actually mean [*KerasTensor*](https://www.tensorflow.org/api_docs/python/tf/keras/Input) which is a symbolic tensor (a placeholder for graph execution), not an *EagerTensor* (an actual value for eager execution). EagerTensor works fine, because it's much like numpy array.

See the difference:

```python
# EagerTensor
eager_input_tf = tf.zeros((2, 128, 128, 3), dtype=tf.uint8)
eager_output_tf = tf.keras.layers.RandomCrop(64, 64)(eager_input_tf)  # OK

# KerasTensor
sym_input_tf = tf.keras.Input((128, 128, 3), batch_size=2, dtype=tf.uint8)
sym_output_tf = tf.keras.layers.RandomCrop(64, 64)(sym_input_tf)  # error
```

Symbolic tensors are used in [Functional API](https://www.tensorflow.org/guide/keras/functional). Example:

```python
inputs = tf.keras.Input((128, 128, 3), batch_size=2, dtype=tf.uint8)
outputs = tf.keras.layers.RandomCrop(64, 64)(inputs)  # error

model = tf.keras.Model(inputs=inputs, outputs=outputs)
```

**Comment by sachinprasadhs** [comment]
As the error suggests `true_fn and false_fn arguments to tf.cond must have the same number, type, and overall structure of return values.`
You need to match the `true_fn` with the `false_fn` dtype which is `float32`.

**Comment by d-01** [comment]
If `float32` is required, then why it's working with `uint8` EagerTensor and numpy array?
If this function (`layers.RandomCrop`) meant to be consistent, then it should either reject or accept *any* `uint8` input tensor (either eager or symbolic).

**Comment by d-01** [comment]
An example of consistent behaviour – `tf.keras.layers.Resizing`:

```python
import tensorflow as tf

# Works with EagerTensor
input_eager = tf.zeros((2, 128, 128, 3), dtype=tf.uint8)
print('Input:', type(input_eager).__name__, input_eager.shape, input_eager.dtype)
output_eager = tf.keras.layers.Resizing(64, 64, 'nearest')(input_eager)
print('Output:', type(output_eager).__name__, output_eager.shape, output_eager.dtype)
print()

# Works with KerasTensor
input_symbolic = tf.keras.Input((128, 128, 3), batch_size=2, dtype=tf.uint8)
print('Input:', type(input_symbolic).__name__, input_symbolic.shape, input_symbolic.dtype)
output_symbolic = tf.keras.layers.Resizing(64, 64, 'nearest')(input_symbolic)
print('Output:', type(output_symbolic).__name__, output_symbolic.shape, output_symbolic.dtype)
```
Output:
```
Input: EagerTensor (2, 128, 128, 3) <dtype: 'uint8'>
Output: EagerTensor (2, 64, 64, 3) <dtype: 'uint8'>

Input: KerasTensor (2, 128, 128, 3) <dtype: 'uint8'>
Output: KerasTensor (2, 64, 64, 3) <dtype: 'uint8'>
```
I expected `tf.keras.layers.RandomCrop` should work just as fine.

**Comment by mattdangerw** [comment]
Thanks for filing. Just put a fix up for review, which should make it in to 2.8.

One thing to call out is that the output dtype of the image preprocessing layers will be changing with the 2.8 release. With the current 2.7 release, we are inconsistent on what dtypes we return. About half of our image layers will cast to floating point, and half would preserve the input dtype.

As of 2.8, all image preprocessing layers will return the float32 by default (or the compute dtype specified by a `tf.keras.mixed_percision.policy`). If you would like to keep the preprocessed images a different type you will need to manually specify it when constructing the layer (e.g. `tf.keras.layers.RandomCrop(64, 64, dtype='uint8')`). The inputs to the layer can continue to whatever type you would like.

**Comment by d-01** [comment]
Please note: `uint8` values can't fall out of the range `[0, 255]`, but `float32` can.

Be careful with `float32 -> uint8` conversion.

For example: `tf.image.adjust_contrast(imgs, contrast_factor=2.0)` can return value like `-101.9`, which normally (for `uint8` input) is clipped to `0` (black).

But when trying to convert `-101.9` directly to `uint8` you'd get `155` (`=int(-101.9) % 256`) -- wrong color (not black).

To prevent wrong results `tf.clip_by_value(x_float, 0, 255)` should be used before `uint8` casting.
