### ISSUE TITLE
Are there any codes for AlexNet, ZF Net, GoogLeNet, VGGNet in Keras

### ISSUE THREAD

**Issue by tingtinglu** [keras-team/keras#1568]
I want to test the performance of AlexNet, ZF Net, GoogLeNet, VGGNet on my own dataset. But I cannot find the code for these models in Keras, then are there any codes for AlexNet, ZF Net, GoogLeNet, VGGNet in Keras? How can I find them? Thank you so much!

**Comment by avisingh599** [comment]
VGG is available [here](https://gist.github.com/baraldilorenzo/07d7802847aaad0a35d3). Not sure about the others though.

**Comment by tingtinglu** [comment]
Thanks so much!

**Comment by parag2489** [comment]
AlexNet is [here](https://gist.github.com/JBed/c2fb3ce8ed299f197eff). Verify its correctness before using.

**Comment by YangZhang4065** [comment]
I do not think you can re-implement the exact Alexnet easily in Keras. Alexnet has sort of "two stream" feature which duplicates the convolution filters. And that feature is not supported in Keras convolution layer yet.

**Comment by saikiran6** [comment]
How abt GoogleNet..! Please help me guys..!

**Comment by tingtinglu** [comment]
Still no googleNet. sad...

**Comment by leonardblier** [comment]
Hi ! We have just released a pre-trained version of AlexNet in Keras, and compared it to the VGGs.
Moreover, we added a method to do object localisation with all these CNN if you want : 
https://github.com/heuritech/convnets-keras

**Comment by joelouismarino** [comment]
Here's [GoogLeNet](https://gist.github.com/joelouismarino/a2ede9ab3928f999575423b9887abd14)

**Comment by WenchenLi** [comment]
resnet avalilable?

**Comment by varoudis** [comment]
@WenchenLi 
https://github.com/fchollet/keras/blob/master/examples/resnet_50.py
???

**Comment by iamhankai** [comment]
vgg, googlenet, resnet is here: https://github.com/fchollet/deep-learning-models

**Comment by tangyibin** [comment]
so does anyone have ZF net? cause all the version i found is the version 'with Fast-RCNN' [..]

**Comment by webcsm** [comment]
You can find 2-stream AlexNet here: http://dandxy89.github.io/ImageModels/alexnet/

**Comment by dhruvramani** [comment]
Here's a simple to use one for Alexnet : https://github.com/dhruvramani/keras-alexnet
