### ISSUE TITLE
Adding RandomCutMix, RandomMixUp augmentation. 

### ISSUE THREAD

**Issue by innat** [keras-team/keras#15712]
TensorFlow version (you are using): 2.7
Are you willing to contribute it (Yes/No): Yes, or I can provide the starter code for an interested contributor. 

**Describe the feature and the current behavior/state**.

CutMix - [Paper](https://arxiv.org/abs/1905.04899) - Cited by ~ 865
MixUp - [Paper](https://arxiv.org/abs/1710.09412) - Cited by ~ 2675

These two well-known and very effective augmentation methods are widely used among ML practitioners. In `keras`, we can find some [general augmentation ](https://keras.io/api/layers/preprocessing_layers/image_augmentation/). And these two augmentation methods can be included as advanced augmentation layers. 

**Will this change the current api? How?**
Yes. 

```python
tf.keras.layers.RandomCutMix
tf.keras.layers.RandomMixUp
```

**Who will benefit from this feature?**
Keras users. 

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**

- Do you want to contribute a PR? (yes/no):
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing):

**Comment by MrinalTyagi** [comment]
@innat Would love to be a part if you insist or need help.

**Comment by LukeWood** [comment]
@fchollet what do you think about including this in Keras-CV (https://github.com/keras-team/keras-cv)?  I think it would be a good fit personally, but let's see if @fchollet has any thoughts.

**Comment by innat** [comment]
@LukeWood I think in that case, it may need to re-think this augmentation for all possible cv tasks, which means not only for classification but also for detection, etc.

**Comment by LukeWood** [comment]
https://github.com/keras-team/keras-cv/issues/19 @innat @MrinalTyagi let's move to this issue to discuss.
