### ISSUE TITLE
multi-GPUs are under-utilized when using prediction on tensorflow_io dataset

### ISSUE THREAD

**Issue by kretes** [keras-team/keras#15730]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): docker on ubuntu 20.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.7.0-rc1-69-gc256c071bb2 2.7.0 (same happens in tf:nightly)
- Python version: 3.8.10
- Bazel version (if compiling from source):
- GPU model and memory: 4xT4 16GB
- NVIDIA-SMI 460.91.03    Driver Version: 460.91.03    CUDA Version: 11.
- Exact command to reproduce:
0. On a multi-GPU machine
1. monitor GPU usage using nvidia-smi interactive or by 
`nvidia-smi --query-gpu=utilization.gpu,utilization.memory,memory.total,memory.free,memory.used --format=csv -lms 200 > stats.csv`
2. run the program: `docker run --gpus all -v test.py:/test.py --rm -it tensorflow/tensorflow:2.7.0-gpu python /test.py`

**Describe the problem**.
multi GPUs aren't utilized equally in tf 2.7.0 - effective poor performance.

**Describe the current behavior**.
Nvidia-smi will show that GPU utilization alternates from {GPU0-GPU1-GPU2-GPU3} (100%-0%-0%-0%) to (0%-100%-100%-100%) 

**Describe the expected behavior**.
all Gpus should be utilized, as it was in tf 2.6.X

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no): no
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**.
see links below
To reproduce in tf-nightly image I needed to first:
`pip install tensorflow-io --no-dependencies`
To reproduce in tf-2.6.1 (no tf 2.6.2 image?) image I needed to first:
`pip install tensorflow-io==0.21.0`

I know the issue is somewhere between keras and tensorflow-io. I am creating it here, since it affects the way keras behaves. If something is 'wrong' with the IODataset - keras should raise it and not under-utilize the resources.

**Source code / logs**.
test.py script: https://colab.research.google.com/drive/1jWi1RAjMhO8h8vmWnD5o6S-PiXOsVdIv?usp=sharing 
[stock_tf26_gpuutil_1.csv](https://github.com/keras-team/keras/files/7632234/stock_tf26_gpuutil_1.csv)
[stock_tf26_repro1.log](https://github.com/keras-team/keras/files/7632220/stock_tf26_repro1.log)
[stock_tf27_gpuutil_7.csv](https://github.com/keras-team/keras/files/7632221/stock_tf27_gpuutil_7.csv)
[stock_tf27_repro7.log](https://github.com/keras-team/keras/files/7632222/stock_tf27_repro7.log)
[stock_tfnightly_gpuutil_1.csv](https://github.com/keras-team/keras/files/7632223/stock_tfnightly_gpuutil_1.csv)
[stock_tfnightly_repro1.log](https://github.com/keras-team/keras/files/7632224/stock_tfnightly_repro1.log)

analysis & charts of gpu utilization: https://colab.research.google.com/drive/1mZKDKjQiQSPu51p01AVrdB-wm1lXDpFW?usp=sharing
(the prediction happens between time_step 100 and 140 - the difference between tf 2.6 and 2.7 is huge.

**Comment by mattdangerw** [comment]
@yuefengz could someone on the distribute team take a look at this?

**Comment by yuefengz** [comment]
Hi @kretes , could you try to grab a profile? https://www.tensorflow.org/guide/profiler

**Comment by kretes** [comment]
Hi @yuefengz , I did the profiling by running .start() and .stop() of the profiler around the .predict() method and I increased no of batches to 12 - [Colab](https://colab.research.google.com/drive/1uZucXZ_sQJjudYHLosWw6nHyguAP3KMJ?usp=sharing) for reference.

[Profiler output](https://drive.google.com/file/d/1ZOop9ITv3uB7IaXhWkXulV-lF69XMM2J/view?usp=sharing) 

Let me know if you need anything else

**Comment by kretes** [comment]
@yuefengz have you been able to look at the profiler output and this issue?

**Comment by kretes** [comment]
I can confirm it is still reproducible in tf 2.8.0

**Comment by tilakrayal** [comment]
Hello, Thank you for reporting an issue.

We're currently in the process of migrating the new `Keras 3` code base from **keras-team/keras-core** to **keras-team/keras.**
Consequently, This issue may not be relevant to the `Keras 3 `code base. After the migration is successfully completed, feel free to reopen this issue at **keras-team/keras** if you believe it remains relevant to the `Keras 3` code base. 
If instead this issue is a bug or security issue in legacy **tf.keras**, you can instead report a new issue at [keras-team/tf-keras](https://github.com/keras-team/tf-keras/issues), which hosts the TensorFlow-only, legacy version of Keras.

To know more about `Keras 3,` please take a look at https://keras.io/keras_core/announcement/. Thank you!
