### ISSUE TITLE
Video Classification with Transformers official notebook error: module 'tensorflow.keras.layers' has no attribute 'CenterCrop'

### ISSUE THREAD

**Issue by ImSo3K** [keras-team/keras#15742]
### **System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): Nope.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- TensorFlow installed from (source or binary):  binary (conda)
- TensorFlow version (use command below): 2.4.1 GPU
- Keras Version
- Python version: 3.9.7 conda env
- Bazel version (if compiling from source):
- GPU model and memory: NVIDIA Corporation GP108M, 8 GB RAM
- Exact command to reproduce:
`center_crop_layer = layers.CenterCrop(IMG_SIZE, IMG_SIZE)
`

### **The problem: **.

I used the notebook from the  [Video Classification with Transformers](https://keras.io/examples/vision/video_transformers/) guide, it runs perfectly on Google Colab but I wanted to work on it locally, when I ran it for the first time in VS Code this error was raised, I tried to run it with `tf.keras.layers.experimental.preprocessing.CenterCrop` which worked until it raised an error again at `StringLookup` so it is not really a fix, I don't know if it is version related but `conda list` returns the following related versions:

```
keras                     2.7.0                    pypi_0    pypi
keras-preprocessing       1.1.2              pyhd3eb1b0_0  
tensorboard               2.6.0                      py_1  
tensorboard-data-server   0.6.0            py39hca6d32c_0  
tensorboard-plugin-wit    1.6.0                      py_0  
tensorflow                2.4.1           gpu_py39h8236f22_0  
tensorflow-addons         0.15.0                   pypi_0    pypi
tensorflow-base           2.4.1           gpu_py39h29c2da4_0  
tensorflow-docs           0.0.0.dev0               pypi_0    pypi
tensorflow-estimator      2.7.0                    pypi_0    pypi
tensorflow-gpu            2.7.0                    pypi_0    pypi
tensorflow-hub            0.12.0                   pypi_0    pypi
tensorflow-io-gcs-filesystem 0.22.0                   pypi_0    pypi
tensorflow-model-optimization 0.7.0                    pypi_0    pypi
```

### **Describe the current behavior**.

This error is raised:
`AttributeError: module 'tensorflow.keras.layers' has no attribute 'CenterCrop'
`
### **Describe the expected behavior**.

The expected output is shown in the notebook.

### **Standalone code to reproduce the issue**.

[This cell](https://colab.research.google.com/github/keras-team/keras-io/blob/master/examples/vision/ipynb/video_transformers.ipynb#scrollTo=4qSl8Tn3CVDU) in the notebook

### **Source code / logs**.

```
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_144262/1363818029.py in <module>
      5 print(f"Total videos for testing: {len(test_df)}")
      6 
----> 7 center_crop_layer = layers.CenterCrop(IMG_SIZE, IMG_SIZE)
      8 
      9 

AttributeError: module 'tensorflow.keras.layers' has no attribute 'CenterCrop'
```

**Comment by old-school-kid** [comment]
Hi @ImSo3K 
Could you please update your tensorflow package and give it a try?
Thank you

**Comment by ImSo3K** [comment]
> Hi @ImSo3K Could you please update your tensorflow package and give it a try? Thank you

Yep, version `2.6.2` works perfectly with it, thank you.

**Comment by MaoMakara** [comment]
Hi @ImSo3K 

Try to use tensorflow version 2.8.0 and use 
center_crop_layer = keras.layers.experimental.preprocessing.CenterCrop(IMG_SIZE, IMG_SIZE)

It worked for me.!!
