### ISSUE TITLE
Allowing Input Tensors to be dynamic for Predictions when using the Subclass method for defining a model

### ISSUE THREAD

**Issue by AshwinJay101** [keras-team/keras#15752]
**Describe the feature and the current behavior/state**.

I am trying to write a Keras Model which implements some complex logic. That logic has been implemented in my call method

As my network layers are convolutional, my model can theoretically predict on input sizes which are different than the size I trained on. Is there any way to specify that for running Predictions on the data.

Here is the skeletal code

     class CustomModel(tf.keras.Model):
         def __init__(self):
              super().__init__()
              self.conv1 = tf.keras.layers.Conv2D(filters=4, kernel_size=4)
              self.conv2= tf.keras.layers.Conv2D(filters=4, kernel_size=4)
      
         def call(inputs):
             image = inputs[0]
             output = self.conv1(image)
             # There is more complex logic here for inputs[1]
             # For sake of simplicity, writing this as output
             another_output = self.conv2(inputs[1])
             combined_output = (output, another_output)
             return combined_output 

And this is the code I am using for running the model

    model = CustomModel()
    model.compile()
    model.fit(x=Train_TF_Dataset)
    
    model.save(filename)
    
    load_model = tf.keras.models.load_model(filename)
    
    model.predict(x=Predict_TF_Dataset)

The train TF Dataset and the predict TF Datasets consist of different sizes which is our usecase.

The training data consisted of a tuple of 256x256x2 images and a second image while the prediction data consists of 512x512x2 along with the corresponding second images. The size of the first input in the tuple can be anything.

Is there some way of specifying that the input shape is (None, None, None, 2) instead of (None, 256, 256, 2). The first value of None is variable by default for the batch size.

The solutions I have seen on stackoverflow just convert it to a functional model which is not possible because of how complex my call method is

Note: 256 and 512 are just numbers. The actual sizes are different. 

Right now when I predict, I will get the following error 

    ValueError: `generator` yielded an element of shape (512, 512, 2) where an element of shape (256, 256, 2) was expected.

As per requests when I raised it on the tensorflow github [Link](https://github.com/tensorflow/tensorflow/issues/53267), I have written a standalone script. You will notice in that script that the model type of functional will work while the model type of subclass will fail. The 2 models though are identical

I tested it on tensorflow2.7 as well and got a similar error. I hope that this code snippet works. I can attach the file as well if required
Code Snippet: [Link](https://gist.github.com/AshwinJay101/b7ded2a1e687dcd9dcb3792494a692d4)

**System information**
- TensorFlow version (you are using): 2.4.0
- Are you willing to contribute it (Yes/No): Yes

**Will this change the current api? How?** 
No the issue will be present in the current API as well 

**Who will benefit with this feature?**
This will allow people to develop subclass models with variable input sizes for Inference. This is huge use case in many industries. Training occurs on a sample of images with smaller size for reducing memory of the network. Inference on the other hand can run on any images as per requirements 

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**

- Do you want to contribute a PR? (yes/no): I can but am not that familiar with the codebase internally. I have used it extensively though

**Comment by chunduriv** [comment]
@AshwinJay101, I tried to run your code on colab using TF2.7 and faced error

   ```
ValueError: Exception encountered when calling layer "custom_model" (type CustomModel).
    Could not find matching concrete function to call loaded from the SavedModel.
```

Please find the [gist here](https://colab.research.google.com/gist/chunduriv/b48979958feb8fa4bcd2d71ff4fc3049/15752.ipynb) for reference. Thanks!

**Comment by AshwinJay101** [comment]
@chunduriv I mentioned that you get a similar error in TF2.7. If you notice, it mentions that it got inputs of shape (None, 512, 512, 6) while it expected inputs of the shape to be (None, 256, 256, 6)

This is the error message 

    Could not find matching concrete function to call loaded from the SavedModel. Got:
          Positional arguments (1 total):
            * (<tf.Tensor 'inputs:0' shape=(None, 512, 512, 6) dtype=float32>, <tf.Tensor 'inputs_1:0' shape=(None, 256, 256, 6) dtype=float32>)
          Keyword arguments: {}
    
     Expected these arguments to match one of the following 2 option(s):
    
    Option 1:
      Positional arguments (1 total):
        * (TensorSpec(shape=(None, 256, 256, 6), dtype=tf.float32, name='inputs/0'), TensorSpec(shape=(None, 256, 256, 6), dtype=tf.float32, name='inputs/1'))
      Keyword arguments: {}
    
    Option 2:
      Positional arguments (1 total):
        * (TensorSpec(shape=(None, 256, 256, 6), dtype=tf.float32, name='input_1'), TensorSpec(shape=(None, 256, 256, 6), dtype=tf.float32, name='input_2'))
      Keyword arguments: {}
    
    Call arguments received:
      • args=(('tf.Tensor(shape=(None, 512, 512, 6), dtype=float32)', 'tf.Tensor(shape=(None, 256, 256, 6), dtype=float32)'),)
      • kwargs=<class 'inspect._empty'>``

**Comment by qlzh727** [comment]
Adding Kathy for this question.

The walkaround I can think of are:

1. Use save_spec/signatures for model.save, so that you force the width/height dimension to be None for the train/eval/predict function. https://www.tensorflow.org/api_docs/python/tf/saved_model/save
2. Save the weights only by model.get_weights() and load the weights back to the model. This will make your loaded model to not have any input shape.
3. Down scale the image so that inputs between training/inference are having the same shape. Usually this is the best practice, otherwise you will often see the model perform badly with random input image size.
