### ISSUE TITLE
How should I made custom loss function which has weights

### ISSUE THREAD

**Issue by minsung-k** [keras-team/keras#15770]
Hi,
I'm trying to make a cost-sensitive learning model.

During that, I have an issue making my custom model which has weight.

My question is that

1. Why my custom_loss doesn't work.  
    I've seen this error code (ValueError: No gradients provided for any variable)

2. How to set the weight which works in custom_loss? Should I use lose_weights in .compile?
3. How to make my own metrics that show my custom_loss.

### Here is a code.

'''
    import tensorflow as tf
    def custom_loss(y_true, y_pred):

        y_true = tf.cast(y_test, tf.float32)
        y_pred = tf.cast(y_pred, tf.float32)

        cost = (1-y_test)  * (cost_1) + y_test * (cost_2)
        mean_cost = tf.reduce_mean(cost, axis=-1)

        return mean_cost

    #simple model
    model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation='relu')
    ])

    model.compile(optimizer = 'adam', loss = custom_loss, metrics = ['accuracy'])
'''

Thanks in advance

And please tell me why the first two code import ~~ and def ~~ do not in code block...

**Comment by AshwinJay101** [comment]
Your loss function must utilize _y_pred_. _y_pred_ is the output of the network and would provide us with the forward pass. That will be utilized during backpropagation where the gradients are updated

As your loss function is only using y_true and not y_pred, there are no gradients for backpropagation. That as a result will throw a error mentioning no gradients provided

**Comment by minsung-k** [comment]
@AshwinJay101 
Thank you for your comment.

@sanatmpa1 only Question 1 solved.

There are still questions left about weight.

How to put cost in loss function.
Should I use lose_weight in .compile method?

'''
cost = (1-y_test)  * y_pred * (cost_1) + y_test * y_pred * (cost_2)
'''

**Comment by old-school-kid** [comment]
Hi @minsung-k 
There ar actually various a lot of ways you can put weights in the loss function. 
1. [**Declare your own cost function**] : Basically create your own custom loss function as you have done above. (Reminder you have casted `y_test` to `y_true` but still using `y_test`)
2. [**Use `sample_weight` of in-built loss function**](https://www.tensorflow.org/api_docs/python/tf/keras/losses/Loss#__call__): All loss function in keras have a `sample_weight` parameter while calling them which can be used to put weights.
3. [**Use `class_weights` and/or `sample_weight` in model.fit**](https://www.tensorflow.org/api_docs/python/tf/keras/Model#fit): While training a model you can use these two parameters two for weighting the loss function. `class_weights` weights the according to the labels while `sample_weight` weights them individually. 
4. [**Use `loss_weights` in model.compile**](https://www.tensorflow.org/api_docs/python/tf/keras/Model#compile):  Weights to multiplied to the loss function for each of model's outputs.
Hope this helps.

**Comment by minsung-k** [comment]
@old-school-kid 

Thank you!
