### ISSUE TITLE
GPU and simpleRNN combination problem

### ISSUE THREAD

**Issue by DameNianch** [keras-team/keras#15784]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): I don't know. I use google colab.
- TensorFlow installed from (source or binary):I don't know. I use google colab.
- TensorFlow version (use command below): 2.7.0
- Python version: I don't know. I use google colab.
- Bazel version (if compiling from source):
- GPU model and memory: I use Tesla K80. I don't know details.
- Exact command to reproduce: Please refer to this https://colab.research.google.com/gist/DameNianch/a1cc7b076d93100c4fd628a14eab9952/simplernndebug.ipynb

When I trained simpleRNN on the sine function using GPU, the learning did not progress much. On the other hand, learning using the CPU gave better results than learning from the GPU. I felt this strange, so I did some experiments and drew the mean and variance for each epoch. As a result, the learning performance of the GPU is clearly inferior to that of the CPU.
Is there any useful information about this?

**Comment by sanatmpa1** [comment]
@DameNianch,

I tried running the reproducible code provided and I can see a good overlap between CPU and GPU, on both the graphs. You can find the [gist here](https://colab.sandbox.google.com/gist/sanatmpa1/91ca3912e0c401481cf30d984bfa3a05/simplernndebug.ipynb). Thanks!

**Comment by DameNianch** [comment]
@sanatmpa1 
Thanks!! Certainly your results do not seem to be as clear as my experiments. I re-experimented twice, thinking that I might just have been unlucky. As a result, the averages weren't too far apart, but the GPU training variance seemed to be too far away compared to that of the CPU. So I further increased the number of experiments (repeat_num) to 1000, reduced epochs to 20 to save time, and re-experimented. As a result, it turned out that they were almost the same.
https://colab.research.google.com/gist/DameNianch/275b1d0bd6753f2225b1e3b25db8f445/simplernn_1000.ipynb
Thank you!!

PS
I hope anyone who comes across a bar that was confused by simpleRNN will get to this issue.

![Screenshot from 2021-12-14 13-07-51](https://user-images.githubusercontent.com/40750603/145931550-91051917-522b-40d1-84f7-346b9caaf287.png)
![Screenshot from 2021-12-14 12-46-34](https://user-images.githubusercontent.com/40750603/145931554-5baa9f56-158a-4579-a530-e930f0e44aef.png)
