### ISSUE TITLE
Surface encoding to TextVectorization layer

### ISSUE THREAD

**Issue by seanmor5** [keras-team/keras#15800]
**System information**.

TensorFlow version (you are using): 2.7

Are you willing to contribute it (Yes/No) : Yes

**Describe the feature and the current behavior/state**.

Hey there, I'm working with a dataset that uses latin-1 encoding rather than UTF-8. After adapting a TextVectorization layer to the dataset and attempting to extract the vocabulary for use later on, I get a UnicodeDecodeError inside the internal string lookup layer. It's trying to decode one of the strings using the default encoding (which I'm assuming is UTF-8). This seems like a pretty easy fix since StringLookup already supports an encoding option. If this is something that's supported, I'd like to contribute it.

**Will this change the current api? How?**

Yes, it will add a new configuration option to TextVectorization.

**Who will benefit from this feature?**

Users who want to use with non UTF-8 codecs

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**

- Do you want to contribute a PR? (yes/no): yes
- Briefly describe your candidate solution(if contributing):

Surface an encoding option in TextVectorization and propagate down to internal String Lookup

**Comment by tilakrayal** [comment]
@seanmor5 ,
Can you please share a reproducible code that supports your statement so that the issue can be easily understood? Thanks!

**Comment by seanmor5** [comment]
Sure, this example raises an error:

```python
import tensorflow as tf

# Example of a character that differs between utf-8 and latin-1,
# If you try with something like basic ascii you wouldn't catch
# this because they're (I think) mostly encoded exactly the same
corpus = [chr(0xa9).encode('latin-1')]

vectorizer = tf.keras.layers.TextVectorization()
vectorizer.adapt(corpus)

vectorizer.get_vocabulary()
```

**Comment by hockeyjudson** [comment]
Regarding @seanmor5 stated issue,
The issue resides in the code: https://github.com/keras-team/keras/blob/f1e9c76675981ee6683f54a3ce569212d551d12d/keras/layers/preprocessing/text_vectorization.py#L448 
On this code we need to add extra argument to explicitly describe text encoding type. currently the code sets up only to utf-8 refer： refer https://github.com/keras-team/keras/blob/f1e9c76675981ee6683f54a3ce569212d551d12d/keras/layers/preprocessing/string_lookup.py#L321

If you are fine with adding extra encoding param i can go on modify the code and raise the PR for this issue.

**Comment by mattdangerw** [comment]
Thanks for filing! I believe the solution proposed by @hockeyjudson is correct. We should add an encoding parameter to the TextVecotorization layer, include it in the config, and mirror it down to the underlying StringLookup layer.

Marking this as open for contributions.

**Comment by Nareshmalviya212** [comment]
> Sure, this example raises an error:
> 
> ```python
> import tensorflow as tf
> 
> # Example of a character that differs between utf-8 and latin-1,
> # If you try with something like basic ascii you wouldn't catch
> # this because they're (I think) mostly encoded exactly the same
> corpus = [chr(0xa9).encode('latin-1')]
> 
> vectorizer = tf.keras.layers.TextVectorization()
> vectorizer.adapt(corpus)
> 
> vectorizer.get_vocabulary()
> ```
> 
> ```
> UnicodeDecodeError                        Traceback (most recent call last)
> <ipython-input-33-aac8958f9c88> in <module>()
>       9 vectorizer.adapt(corpus)
>      10 
> ---> 11 vectorizer.get_vocabulary()
> 
> 4 frames
> /usr/local/lib/python3.7/dist-packages/tensorflow/python/util/compat.py in as_text(bytes_or_text, encoding)
>     107     return bytes_or_text
>     108   elif isinstance(bytes_or_text, bytes):
> --> 109     return bytes_or_text.decode(encoding)
>     110   else:
>     111     raise TypeError('Expected binary or unicode string, got %r' % bytes_or_text)
> 
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 0: invalid start byte
> ```

hey hii @seanmor5 
can you give me solution of this problem.

**Comment by tilakrayal** [comment]
Hello, Thank you for reporting an issue.

We're currently in the process of migrating the new `Keras 3` code base from **keras-team/keras-core** to **keras-team/keras.**
Consequently, This issue may not be relevant to the `Keras 3 `code base. After the migration is successfully completed, feel free to reopen this issue at **keras-team/keras** if you believe it remains relevant to the `Keras 3` code base. 
If instead this issue is a bug or security issue in legacy **tf.keras**, you can instead report a new issue at [keras-team/tf-keras](https://github.com/keras-team/tf-keras/issues), which hosts the TensorFlow-only, legacy version of Keras.

To know more about `Keras 3,` please take a look at https://keras.io/keras_core/announcement/. Thank you!
