### ISSUE TITLE
Bug: Cannot save tf.function decorated custom model

### ISSUE THREAD

**Issue by EdwardCuiPeacock** [keras-team/keras#15820]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOSX 10.15.7
- TensorFlow installed from (source or binary): binary via pip
- TensorFlow version (use command below): 2.7.0 
- Python version: 3.7.10
- Bazel version (if compiling from source): N/A
- GPU model and memory: N/A
- Exact command to reproduce:

When saving a model decorated with `@tf.function` with an input signature, I got the following error:

```
Traceback (most recent call last):

  File "/var/folders/99/yfp904qj47z9_hn0td6z0dd40000gs/T/ipykernel_99573/2600402858.py", line 1, in <module>
    model.save("./tmp_bug_model")

  File "/Users/edwardcui/opt/anaconda3/envs/deepfm/lib/python3.7/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None

  File "/Users/edwardcui/opt/anaconda3/envs/deepfm/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 1129, in autograph_handler
    raise e.ag_error_metadata.to_exception(e)

TypeError: in user code:

    File "/Users/edwardcui/opt/anaconda3/envs/deepfm/lib/python3.7/site-packages/keras/saving/saving_utils.py", line 125, in _wrapped_model  *
        outputs = model(*args, **kwargs)
    File "/Users/edwardcui/opt/anaconda3/envs/deepfm/lib/python3.7/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler  **
        raise e.with_traceback(filtered_tb) from None

    TypeError: call(inputs, training) got two values for 'training'.
```

Here is an example model class subclassing `keras.Model`

```python

import tensorflow as tf
import keras

class ExampleBugClass(tf.keras.Model):
    def __init__(self):
        super(ExampleBugClass, self).__init__()
        
    @tf.function(input_signature=[
        {"x": tf.TensorSpec((None, None), dtype=tf.int32, name="x")},
         tf.TensorSpec(None, dtype=tf.bool, name="training")
         ])
    def call(self, inputs, training=False):
        return tf.reduce_sum(inputs["x"], axis=1, keepdims=True)
    


model = ExampleBugClass()

# Make example data
data = {"x": tf.constant([[1, 2, 5, 3], [2, 3, 6, 4], [3, 7, 2, 1], [9, 4, 2 ,0]])}

# Call the model, no error
output = model(data, training=False)


# Save the model, gives the error above
model.save("./tmp_bug_model")

```

**Comment by AshwinJay101** [comment]
According to the documentation, you can use a serving functions for our task. Custom code below 

    import tensorflow as tf
    import tensorflow.keras as keras
    
    class ExampleBugClass(tf.keras.Model):
        def __init__(self):
            super(ExampleBugClass, self).__init__()
    
        def call(self, inputs, training=False):
            return tf.reduce_sum(inputs["x"], axis=1, keepdims=True)
        
        @tf.function(input_signature=[
            {"x": tf.TensorSpec((None, None), dtype=tf.int32, name="x")}
             ])
        def serve(self, inputs):
            return self.call(inputs)
        
    
    
    model = ExampleBugClass()
    
    # Make example data
    data = {"x": tf.constant([[1, 2, 5, 3], [2, 3, 6, 4], [3, 7, 2, 1], [9, 4, 2 ,0]])}
    
    # Call the model, no error
    output = model(data, training=False)
    print(output)
    
    # Save the model, gives the error above
    model.save("./tmp_bug_model", signatures={"serving_default": model.serve})
    
    new_model = tf.keras.models.load_model("./tmp_bug_model")
    infer = new_model.signatures["serving_default"]
    
    
    print(infer(x=data["x"]))

**Comment by chunduriv** [comment]
@EdwardCuiPeacock, 

Can you please a take a look at this [comment](https://github.com/keras-team/keras/issues/15820#issuecomment-999017867) and let us know if it helps you? Thanks!

**Comment by EdwardCuiPeacock** [comment]
@chunduriv Thanks, this seems like a great workaround.
