### ISSUE TITLE
[TF] Loading a Keras model which contains __ne__ or __eq__ operators fails

### ISSUE THREAD

**Issue by OmriSteiner** [keras-team/keras#15832]
I'm not sure whether this is a Keras or TF bug. I can post this on TF instead.

**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.7.0-rc1-69-gc256c071bb2
- Python version: 3.8.10

**Describe the current behavior**
Keras fails to load a model which contains `__eq__` or `__ne__` operations on `KerasTensor`s. Replacing these operations with `tf.equal` or `tf.not_equal` respectively solves the issue (this is a great workaround, although confusing).

**Describe the expected behavior**
Operators `==` and `!=` should behave exactly like `tf.equal` and `tf.not_equal` on `KerasTensor`.

**Standalone code to reproduce the issue**.
[Have a look at this collab notebook](https://gist.github.com/OmriSteiner/8b73dc9ede551cd3758fe37ba1a98b11)

**Describe the problem**
The problem exists because of the way the `__eq__` and `__ne__` operators are implemented in TF. You can see the implementation of `__eq__` [here](https://github.com/tensorflow/tensorflow/blob/v2.7.0/tensorflow/python/ops/math_ops.py#L1945). These functions are free functions which are then bound to `tf.Tensor` and `KerasTensor`. These functions' first argument name is `self`, which gets lost somewhere. I was able to change the argument name for these functions, and make Keras load the model successfully.

I'm not sure whether this causes issues in saving or loading the model (it saves successfully, but I'm not sure the model is valid).

I tried investigating a bit further, but I'm not sure of the root cause yet.
When creating a Keras model using the Functional API, Keras translates operations on symbolic `KerasTensor`s (either Tensorflow operations or invocations of `KerasTensor` operators) to `TFOpLambda` layers. `TFOpLambda` receives a function to run as a parameter, and it does [this assignment](https://github.com/keras-team/keras/blob/v2.7.0/keras/layers/core/tf_op_layer.py#L228). Afterwards, in the base `Layer` constructor, the class [inspects the `call` method of the instance being initialized](https://github.com/keras-team/keras/blob/v2.7.0/keras/engine/base_layer.py#L3005). It expects the parameter `self` to be missing, and if it exists, it removes it from the argument list.
However, this doesn't seem to be the problem, because when changing `Layer._call_fn_args` to explicitly work for these functions, the problem persisted.

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.
- Do you want to contribute a PR? (yes/no): yes
- Briefly describe your candidate solution(if contributing): I'm not done examining the root cause of this, so I can't propose a solution.

**Comment by OmriSteiner** [comment]
Okay, I found the issue. It was `Layer._call_fn_args`, as suspected. For some reason the patch I applied for `Layer._call_fn_args` didn't work, but it does now.

As you can see [here](https://github.com/keras-team/keras/blob/v2.7.0/keras/engine/node.py#L178), when serializing a node (happens while saving a Keras model), the function explicitly calls `_call_fn_args`, which filters out the `self` argument.

**Comment by OmriSteiner** [comment]
Mentioning @omalleyt12, as you're the last one who've touched this function (at least it says so in the TF source control).
I'm curious about [this comment](https://github.com/keras-team/keras/blob/v2.7.0/keras/engine/base_layer.py#L3007). It implies that `self` appears in `self.call`'s argument list in case a decorator has been applied. However, in most cases `self.call` is a bound method, which means it should contain a `self` argument. So this is the "likely" code path.

This makes me thing the most plausible solution for this issue is just changing the function signatures in the TF repository.
Something like `def tensor_equals(self, other)` -> `def tensor_equals(lhs, rhs)`.

**Comment by sushreebarsa** [comment]
@sachinprasadhs Was able to reproduce the issue in TF v2.7.0 ,please find the gist [here](https://colab.sandbox.google.com/gist/sushreebarsa/60e61e020c086b758ca0a20b40fec90c/keras_load_model_bug.ipynb#scrollTo=oKMnt8y-fUbq).Thanks!

**Comment by OmriSteiner** [comment]
Yeah, I can open a PR to fix this.
I'm not sure about the correct solution though.
What do you think about changing the function signature in TF?
Is there any other way you think we can solve this in Keras?

**Comment by chenmoneygithub** [comment]
Thanks! You mentioned 

```These functions' first argument name is self, which gets lost somewhere. I was able to change the argument name for these functions, and make Keras load the model successfully.```

Could you paste the changed function signature here? If I understand correctly, your fix is to force keeping the `self` argument?

**Comment by OmriSteiner** [comment]
Hey, sorry for disappearing.
Unfortunately I don't have a local setup for TF any more, so I am not able to test anything.
I don't think this is the correct solution for this issue, but since you've asked I'll post it:

https://github.com/tensorflow/tensorflow/blob/v2.7.0/tensorflow/python/ops/math_ops.py#L1945
```diff
- def tensor_equals(self, other):
+ def tensor_equals(lhs, rhs):
```
But changing the `tensor_equals` signature affects the ragged tensor implementation, because it uses `dispatch_for_api` which (IIRC) makes sure the function signatures match. So we'll have to change this as well:
https://github.com/tensorflow/tensorflow/blob/v2.7.0/tensorflow/python/ops/ragged/ragged_math_ops.py#L1112
```diff
- def tensor_equals(self: ragged_tensor.RaggedOrDense,
-                   other: ragged_tensor.RaggedOrDense):
+ def tensor_equals(lhs: ragged_tensor.RaggedOrDense,
+                   rhs: ragged_tensor.RaggedOrDense):
```

Besides these, you'll also have to change the same thing for `tensor_not_equals` in the same files.
I'm sorry these diffs are for 2.7.0, but this was the version I worked on back then.

**Comment by OmriSteiner** [comment]
@chenmoneygithub This still seems to reproduce in the nightly build (`2.11.0-dev20220808`).
