### ISSUE TITLE
"ValueError: Layer "model_1" expects 1 input(s), but it received 2 input tensors" as more than one face appears in frame. Real Time Mask Detection System

### ISSUE THREAD

**Issue by Alex-Zab** [keras-team/keras#15837]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): custom, but not mine
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 20H2
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): v2.7.0-rc1-69-gc256c071bb2 2.7.0
- Python version: 3.8
- Bazel version (if compiling from source): -
- GPU model and memory: None
- Exact command to reproduce: ValueError: Layer "model_1" expects 1 input(s), but it received 2 input tensors

**Describe the problem**.

I am doing a real-time face mask recognition system and after two or more faces appear in the frame, this error stops the process.

**Describe the current behavior**.

Program crashes with error - 
```Traceback (most recent call last):
  File "C:\Users\___\Desktop\MD\test_mask_video.py", line 99, in <module>
    (locs, preds) = detect_and_predict_mask(frame, faceNet, maskNet)
  File "C:\Users\___\Desktop\MD\test_mask_video.py", line 68, in detect_and_predict_mask
    preds = maskNet.predict(faces)
  File "C:\Users\___\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\___\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\framework\func_graph.py", line 1129, in autograph_handler
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    File "C:\Users\___\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\engine\training.py", line 1621, in predict_function  *
        return step_function(self, iterator)
    File "C:\Users\___\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\engine\training.py", line 1611, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\___\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\engine\training.py", line 1604, in run_step  **
        outputs = model.predict_step(data)
    File "C:\Users\___\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\engine\training.py", line 1572, in predict_step
        return self(x, training=False)
    File "C:\Users\___\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\___\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\engine\input_spec.py", line 199, in assert_input_compatibility
        raise ValueError(f'Layer "{layer_name}" expects {len(input_spec)} input(s),'

    ValueError: Layer "model_1" expects 1 input(s), but it received 3 input tensors. Inputs received: [<tf.Tensor 'IteratorGetNext:0' shape=(None, 224, 224, 3) dtype=float32>, <tf.Tensor 'IteratorGetNext:1' shape=(None, 224, 224, 3) dtype=float32>, <tf.Tensor 'IteratorGetNext:2' shape=(None, 224, 224, 3) dtype=float32>]
```

**Describe the expected behavior**.

Determine several faces in the frame at a time.

- Do you want to contribute a PR? (yes/no): no
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**.

`preds = maskNet.predict(faces)`

**Source code / logs**.

```
confidence_arg = 0.5

def detect_and_predict_mask(frame, faceNet, maskNet):
    (h, w) = frame.shape[:2]
    blob = cv2.dnn.blobFromImage(frame, 1.0, (300, 300),
        (104.0, 177.0, 123.0))

    faceNet.setInput(blob)
    detections = faceNet.forward()

    faces = []
    locs = []
    preds = []

    for i in range(0, detections.shape[2]):
        confidence = detections[0, 0, i, 2]

        if confidence > confidence_arg:
            box = detections[0, 0, i, 3:7] * np.array([w, h, w, h])
            (startX, startY, endX, endY) = box.astype("int")

            (startX, startY) = (max(0, startX), max(0, startY))
            (endX, endY) = (min(w - 1, endX), min(h - 1, endY))

            face = frame[startY:endY, startX:endX]
            face = cv2.cvtColor(face, cv2.COLOR_BGR2RGB)
            face = cv2.resize(face, (224, 224))
            face = img_to_array(face)
            face = preprocess_input(face)
            face = np.expand_dims(face, axis=0)

            faces.append(face)
            locs.append((startX, startY, endX, endY))

    if len(faces) > 0:
        #for x in faces:
        preds = maskNet.predict(faces)

    return (locs, preds)

print("Loading face detector model...")
prototxtPath = 'face_detector/deploy.prototxt'
weightsPath = 'face_detector/res10_300x300_ssd_iter_140000.caffemodel'
faceNet = cv2.dnn.readNet(prototxtPath, weightsPath)

maskNet = load_model('model')


print("Starting video stream...")
vs = VideoStream(src=0).start()

while True:
    frame = vs.read()
    frame = imutils.resize(frame, width=800, height=320)

    (locs, preds) = detect_and_predict_mask(frame, faceNet, maskNet)
    print(locs, preds)

    for (box, pred) in zip(locs, preds):
        (startX, startY, endX, endY) = box

        (noproperMask, mask, withoutMask) = pred

        if (mask>withoutMask and mask>noproperMask):
            label = "Mask"
            color = (0, 255, 0)
        elif (withoutMask>mask and withoutMask>noproperMask):
            label = "No Mask"
            color = (0, 0, 255)

        cv2.putText(frame, label, (startX, startY - 10),
            cv2.FONT_HERSHEY_SIMPLEX, 0.45, color, 2)
        cv2.rectangle(frame, (startX, startY), (endX, endY), color, 2)

    cv2.imshow("Mask Detection System", frame)
    key = cv2.waitKey(1) & 0xFF

    if key == ord("q"):
        break

vs.stop()
cv2.destroyAllWindows()
```

**Comment by old-school-kid** [comment]
Hi @Alex-Zab 
I assume your keras model `maskNet` only takes 1 image as input. But it appears `frame` has two faces and thus `faces` becomes a list of two images. Instead of calling `preds = maskNet.predict(faces)` you can  call `preds.append(maskNet.predict(face))` inside the loop. So you pass one image and also the overhead of checking len(faces) is removed.
Hope this helps

**Comment by Alex-Zab** [comment]
@old-school-kid Thanks for your reply! But, if I put `preds.append(maskNet.predict(face))` instead of `preds = maskNet.predict(faces)`, my program crashes with another error - 
```
Traceback (most recent call last):
  File "C:\Users\MD\test_mask_video.py", line 106, in <module>
    (noproperMask, mask, withoutMask) = pred
ValueError: not enough values to unpack (expected 3, got 1)
```

**Comment by old-school-kid** [comment]
You have to first initialize the variable `face`. Like after `faces.append(face)` line you can call `preds.append(maskNet.predict(face))`. 
The first error rose because of the second error.

**Comment by Alex-Zab** [comment]
@old-school-kid Ok, so I put `preds.append(maskNet.predict(face))` after `faces.append(face)`, commented line `#if len(faces) > 0:` and still receiving error - 
```
Traceback (most recent call last):
  File "C:\Users\MD\test_mask_video.py", line 108, in <module>
    (noproperMask, mask, withoutMask) = pred
ValueError: not enough values to unpack (expected 3, got 1)
```

**Comment by old-school-kid** [comment]
@Alex-Zab 
Can you please provide the code for the model. It appears that the pred has got one value while you are trying to access three values.

**Comment by Alex-Zab** [comment]
@old-school-kid I have `model.h5` file which is 11Mb, I can't input that much text. Also, after searching `pred` in file nothing was found.

**Comment by old-school-kid** [comment]
@Alex-Zab 
`model.h5` contains the weight of the model. I just need a look of the model architecture. So can you provide the code for initializing the architecture? It appears that your model has 1 output only while you are trying to unpack 3.

**Comment by Alex-Zab** [comment]
@old-school-kid Can You, please, clarify, where should I find it?

**Comment by Alex-Zab** [comment]
@old-school-kid You can take a look at all of the files in here - https://github.com/Nitin1901/Face-mask-detection

**Comment by SuryanarayanaY** [comment]
Hello, Thank you for reporting an issue.

We're currently in the process of migrating the new Keras 3 code base from keras-team/keras-core to keras-team/keras.
Consequently, This issue may not be relevant to the Keras 3 code base . After the migration is successfully completed, feel free to reopen this Issue at keras-team/keras if you believe it remains relevant to the Keras 3 code base. If instead this Issue is a bug or security issue in legacy tf.keras, you can instead report a new issue at [keras-team/tf-keras](https://github.com/keras-team/tf-keras/issues), which hosts the TensorFlow-only, legacy version of Keras.

To know more about Keras 3, please read https://keras.io/keras_core/announcement/
