### ISSUE TITLE
model.fit excess memory usage with GPU

### ISSUE THREAD

**Issue by Chaudry24** [keras-team/keras#15843]
I am running 4 scripts which should be equivalent in theory. However, two of those [which use GPU to train the model] are using 10 times more memory than their CPU counterparts.

The scripts which are using acceptable levels of memory are scripts 1 and 3. The unacceptable levels are scripts 2 and 4.

Here is the code:
script1: https://pastebin.com/2gRbjKmx
script2: https://pastebin.com/GK9iE2DC
script3: https://pastebin.com/cUniWZxj
script4: https://pastebin.com/BwkWbHjg

My python version is 3.9.7 and tensorflow version is 2.4.1.

The OS is: Red Hat Enterprise Linux
The Kernel is: Linux 3.10.0-1160.2.1.el7.x86_64
The architecture is: x86-64

The GPU is Nvidia either P100 or Nvidia V100.

The colab [Gist](https://colab.research.google.com/gist/mohantym/e8a26e8b9928bd24c436c654ef8e8c4d/github_53577.ipynb#scrollTo=TLi1gNCx3H8v) -- thanks to [mohantym](https://github.com/mohantym)

**Comment by kumariko** [comment]
@sachinprasadhs Was able to reproduce the issue in TF v2.7.0 ,please find the gist [here](https://colab.research.google.com/gist/kumariko/52c1dc589e72116c5c6242591fbd7661/github_53577.ipynb#scrollTo=2GGz3DqX6ATy).Thanks!

**Comment by sachinprasadhs** [comment]
Which memory are you comparing, the RAM usage or the GPU memory usage between those tests?
Could you also provide what is the difference in memory you see for each tests in both CPU and GPU for 10 epochs. Thanks!

**Comment by Chaudry24** [comment]
I am comparing CPU memory. The difference is almost 10x

**Comment by sachinprasadhs** [comment]
I don't see the excess memory usage from GPU for the examples provided, instead the GPU is consuming the less RAM compared to it's CPU equivalent, which is expected. Please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/30e36ed1b6f8a217f38ba5cdcf29b72c/github_53577.ipynb#scrollTo=X08-wUOj2yAf) for detailed usage. I'm printing the total ram consumed after each example/cell, you can check the difference in mb with the previous example.
