### ISSUE TITLE
test_activity_regularizer_batch_independent_v2_eager  and test_activity_regularizer_batch_independent_v2_function fail on aarch64

### ISSUE THREAD

**Issue by ggardet** [keras-team/keras#15881]
**System information**.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): openSUSE Tumbleweed aarch64
- TensorFlow installed from (source or binary): from distro rpm
- TensorFlow version (use command below): 2.6.0
- Python version: 
- Bazel version (if compiling from source): 3.7
- GPU model and memory: N/A
- Exact command to reproduce: We run tests from `keras/tests/*_test.py`

**Describe the problem**.
`test_activity_regularizer_batch_independent_v2_eager` and `test_activity_regularizer_batch_independent_v2_function` fail on aarch64.

**Describe the current behavior**.
2 tests fail.

**Describe the expected behavior**.
All tests should succeed.

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no):
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**.
Run self test on aarch64.

**Source code / logs**.
See: https://build.opensuse.org/package/live_build_log/science:machinelearning/python-Keras:test/openSUSE_Tumbleweed/aarch64

**Comment by tilakrayal** [comment]
@ggardet ,
In order to expedite the trouble-shooting process, could you please provide the complete code and dataset to reproduce the issue reported here.

**Comment by ggardet** [comment]
> 

We just run:
```
for f in keras/tests/*_test.py; do
  # ValueError: Please provide a TPU Name to connect to.
  [ "$f" = "keras/tests/automatic_outside_compilation_test.py" ] && continue || :
  # import error: test file not installed into sitelib
  [ "$f" = "keras/tests/get_config_test.py" ] && continue || :
  # no tensorflow.compiler.tests
  [ "$f" = "keras/tests/tracking_util_xla_test.py" ] && continue || :
  # Note: These might be genuine errors, but in order to get it checked in, we rather ignore them now.
  #       It is still better than not running any tests at all.
  $python $f
done
```
With `$python` being the current python interpreter.

**Comment by LukeWood** [comment]
@ggardet could you help us by identifying which OP is returning NaN in these test cases then we will follow up with the TensorFlow repo?
