### ISSUE TITLE
Error in using compile inside Callback class

### ISSUE THREAD

**Issue by Dianagle2** [keras-team/keras#15893]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras):Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Windown 10
- TensorFlow installed from (source or binary):source
- TensorFlow version (use command below):2.4
- Python version:3.6

I'm trying to make a fine tuning callback.
So, I wish to unfreeze layers after few epochs but I get this error: "TypeError: 'NoneType' object is not callable".

My code:
        
            
     class UnFreezeCallback(tf.keras.callbacks.Callback): 
        def __init__(self, n_epochs):
              super().__init__()
              self.n_epochs = n_epochs    
        def on_epoch_end(self, epoch, logs=None):
            print("This is epoch number: {}".format(epoch))
            if epoch == self.n_epochs-1 and self.n_epochs != 0:            
                print("Open entire model for training")                
                for layer in self.model.layers[args.unfreeze_layer_idx:]:
                    if args.freeze_bn == False or layer.__class__.__name__ != 'BatchNormalization':
                        layer.trainable = True
                    else:
                        layer.trainable = False

                with strategy.scope():                    
                    #must re-compile after freeze redefinition:            
                    print("compiling model")                
                    self.model.compile(loss = "categorical_crossentropy", 
                                            optimizer="Adam",                                        
                                            metrics=["accuracy"],
                                            run_eagerly=args.run_eagerly) 

                    
                    
    unfreeze_callback = UnFreezeCallback(args.open_training_epoch)
        
    model_final.fit(          
          tf_dataset,                
          steps_per_epoch  = math.floor(len(y_train) / args.train_batch_size),
          epochs = args.epochs,
          batch_size = args.train_batch_size,
          verbose=1,
          initial_epoch=0, 
          callbacks = [unfreeze_callback, tensorboard_callback, lr_scheduler]) 

If I'm removing self.model.compile everything works fine.
With it I'm having this error:

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
   1098                 _r=1):
   1099               callbacks.on_train_batch_begin(step)
-> 1100               tmp_logs = self.train_function(iterator)
   1101               if data_handler.should_sync:
   1102                 context.async_wait()

TypeError: 'NoneType' object is not callable

This error shows up at the beginning of the next epoch.

**Comment by fchollet** [comment]
The `fit()` call requires attributes that are set in the first `compile()` call. You can't recompile then resume the *same* `fit()`, it needs to be a new `fit()` call. You can't saw the tree branch on which you're currently sitting then expect it to stay there.

You should do something like:

```python
for epoch in range(epochs):
  model.fit(..., epochs=1)
  change_weight_trainability(...)
  model.compile(...)
```
