### ISSUE TITLE
Loading saved model with TextVectorization layer throws exception

### ISSUE THREAD

**Issue by lrwagner** [keras-team/keras#15922]
**System information**.
Google Colab (also on own system, Linux Ubuntu 20.04, tf 2.7.0)

**Describe the problem**.
Loading a saved model which includes a TextVectorization layer throws an exception (tested with tf 2.7 and 2.6). The stacktrace points to another layer in the model, but only removing the TextVectorization layer solves the problem.

**Describe the current behavior**.
Throws an exception

```
TypeError: Exception encountered when calling layer "flatten" (type Flatten).

Failed to convert elements of tf.RaggedTensor(values=Tensor("Placeholder:0", shape=(None, 64), dtype=float32), row_splits=Tensor("Placeholder_1:0", shape=(None,), dtype=int64)) to Tensor. Consider casting elements to a supported type. See https://www.tensorflow.org/api_docs/python/tf/dtypes for supported TF dtypes.

Call arguments received:
  • inputs=tf.RaggedTensor(values=Tensor("Placeholder:0", shape=(None, 64), dtype=float32), row_splits=Tensor("Placeholder_1:0", shape=(None,), dtype=int64))
```

**Describe the expected behavior**.
Model should be loadable with TextVectorization Layer, as used in some of the tutorials on keras.io

**Standalone code to reproduce the issue**.
Notebook with example:
Model without TextVectorization Layer is loadable, model including TextVectorization throws exception
https://colab.research.google.com/drive/1gjW5f9oRbkFfirAftzmVqppS7nsC5Q-E?usp=sharing

**Comment by fchollet** [comment]
@mattdangerw can you take a look? Perhaps this can be covered as part of the effort to add RaggedSupport to layers (cc @haifeng-jin)

**Comment by jvishnuvardhan** [comment]
@lrwagner Looks like this was already resolved in recent `tf-nightly`. [Here](https://colab.research.google.com/gist/jvishnuvardhan/f1fded8f311cafbf036b95b74465cfa8/textvectorization.ipynb) is a gist for reference. 

May this code fix https://github.com/tensorflow/tensorflow/commit/d3b6494e82085a397bad2260a43ea6769aa20f5d might have fixed the bug in the code. Thanks

**Comment by lrwagner** [comment]
I can confirm it works when using `tf-nightly`!

**Comment by Amit-g12** [comment]
for epoch in range(EPOCHS):
    start = time.time()

    train_loss.reset_states()
  
    for (batch, (inp, tar)) in enumerate(dataset):
        train_step(inp, tar)
    
        # 55k samples
        # we display 3 batch results -- 0th, middle and last one (approx)
        # 55k / 64 ~ 858; 858 / 2 = 429
        if batch % 429 == 0:
            print ('Epoch {} Batch {} Loss {:.4f}'.format(epoch + 1, batch, train_loss.result()))
      
    if (epoch + 1) % 5 == 0:
        ckpt_save_path = ckpt_manager.save()
        print ('Saving checkpoint for epoch {} at {}'.format(epoch+1, ckpt_save_path))
    
    print ('Epoch {} Loss {:.4f}'.format(epoch + 1, train_loss.result()))

    print ('Time taken for 1 epoch: {} secs\n'.format(time.time() - start))


TypeError                                 Traceback (most recent call last)
[<ipython-input-112-cba6d4f116fb>](https://localhost:8080/#) in <module>()
      5 
      6     for (batch, (inp, tar)) in enumerate(dataset):
----> 7         train_step(inp, tar)
      8 
      9         # 55k samples

4 frames
[<ipython-input-83-38ad553704c3>](https://localhost:8080/#) in call(self, x, training, mask)
     13 
     14     def call(self, x, training, mask):
---> 15         attn_output, _ = self.mha(x, x, x, mask)
     16         attn_output = self.dropout1(attn_output, training=training)
     17         out1 = self.layernorm1(x + attn_output)

TypeError: Exception encountered when calling layer "encoder_layer_4" (type EncoderLayer).

cannot unpack non-iterable NoneType object

Call arguments received:
  • x=tf.Tensor(shape=(64, 400, 128), dtype=float32)
  • training=True
  • mask=tf.Tensor(shape=(64, 1, 1, 400), dtype=float32)

**Comment by lrwagner** [comment]
> for epoch in range(EPOCHS): start = time.time()
> 
> ```
> train_loss.reset_states()
> 
> for (batch, (inp, tar)) in enumerate(dataset):
>     train_step(inp, tar)
> 
>     # 55k samples
>     # we display 3 batch results -- 0th, middle and last one (approx)
>     # 55k / 64 ~ 858; 858 / 2 = 429
>     if batch % 429 == 0:
>         print ('Epoch {} Batch {} Loss {:.4f}'.format(epoch + 1, batch, train_loss.result()))
>   
> if (epoch + 1) % 5 == 0:
>     ckpt_save_path = ckpt_manager.save()
>     print ('Saving checkpoint for epoch {} at {}'.format(epoch+1, ckpt_save_path))
> 
> print ('Epoch {} Loss {:.4f}'.format(epoch + 1, train_loss.result()))
> 
> print ('Time taken for 1 epoch: {} secs\n'.format(time.time() - start))
> ```
> 
> TypeError Traceback (most recent call last) in () 5 6 for (batch, (inp, tar)) in enumerate(dataset): ----> 7 train_step(inp, tar) 8 9 # 55k samples
> 
> 4 frames in call(self, x, training, mask) 13 14 def call(self, x, training, mask): ---> 15 attn_output, _ = self.mha(x, x, x, mask) 16 attn_output = self.dropout1(attn_output, training=training) 17 out1 = self.layernorm1(x + attn_output)
> 
> TypeError: Exception encountered when calling layer "encoder_layer_4" (type EncoderLayer).
> 
> cannot unpack non-iterable NoneType object
> 
> Call arguments received: • x=tf.Tensor(shape=(64, 400, 128), dtype=float32) • training=True • mask=tf.Tensor(shape=(64, 1, 1, 400), dtype=float32)

I think this might not be related to my original issue
