### ISSUE TITLE
Using learning-rate decay schedule with Keras (transfer learning with RESNET) generates unsupported operand error 'ExponentialDecay'

### ISSUE THREAD

**Issue by castorgit** [keras-team/keras#15931]
** System information **

    custom code
    Ubuntu 20.4
    TF installed from binary
    TF / Keras 2.7.0
    Python 3.8.12
    no GPU

** Current Behavior **

Training a Network to classify images, Network is based on RESNET152V2 + some new layers. We train last 19 layers of RESNET + the new added layers
(data is XRAY dataset from Kaggle)
Using a learning-rate decay schedule, the training crashes with an error 'unsupported operand error'

TypeError: unsupported operand type(s) for *: 'ExponentialDecay' and 'int'

** Standalone code to reproduce the issue **
[link to notebook](https://github.com/castorgit/AI-course-2021/blob/main/Group_Project/ResNet152V%20error.ipynb)

**Comment by Cheril311** [comment]
@castorgit this problem appears to be fixed in the latest TF-nightly version. See here https://colab.research.google.com/gist/amahendrakar/697836288a6d02f048d11e08b7044079/41639-tf-nightly.ipynb

**Comment by jvishnuvardhan** [comment]
@castorgit Can you please verify with `tf-nightly` and close the issue if this was resolved for you? Thanks!

**Comment by nrcjea001** [comment]
Same issue here with tensorflow 2.8.0

Removing callback ReduceLROnPlateau seems to fix the issue

**Comment by arghanath007** [comment]
Why should we remove it? It is needed right? I am also getting the same error on tensorflow: 2.8.2 on google Colab.
