### ISSUE TITLE
[Metric] get shape of a tensor for custom metric

### ISSUE THREAD

**Issue by hoangtnm** [keras-team/keras#15932]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow installed from (source or binary): conda-forge
- TensorFlow version (use command below): 2.6.2
- Python version: 3.7
- CUDA/cuDNN version: 10.2 / 7.6.5.32
- GPU model and memory: GTX 1080Ti

**Describe the current behavior**

I am implementing a custom metric for `tf.keras` which need to extract the batch dimension of input tensor `x.shape[0]` during `model.fit(...)` but it raises:

```
(None, None)
Traceback (most recent call last):
  File "train.py", line 81, in <module>
    main()
  File "train.py", line 71, in main
    use_multiprocessing=True)
  File "/opt/conda/lib/python3.7/site-packages/keras/engine/training.py", line 1184, in fit
    tmp_logs = self.train_function(iterator)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 885, in __call__
    result = self._call(*args, **kwds)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 933, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 760, in _initialize
    *args, **kwds))
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3066, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3463, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3308, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 1007, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 668, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 994, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /opt/conda/lib/python3.7/site-packages/keras/engine/training.py:853 train_function  *
        return step_function(self, iterator)
    /AgeGenderMask/metrics/age_mae.py:36 update_state  *
        self.count.assign_add(y_true.shape[0])
    /opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:857 assign_add  **
        ops.convert_to_tensor(delta, dtype=self.dtype),
    /opt/conda/lib/python3.7/site-packages/tensorflow/python/profiler/trace.py:163 wrapped
        return func(*args, **kwargs)
    /opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:1566 convert_to_tensor
        ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
    /opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py:346 _constant_tensor_conversion_function
        return constant(v, dtype=dtype, name=name)
    /opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py:272 constant
        allow_broadcast=True)
    /opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py:290 _constant_impl
        allow_broadcast=allow_broadcast))
    /opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/tensor_util.py:445 make_tensor_proto
        raise ValueError("None values not supported.")
```

**Describe the expected behavior**

As mentioned above.

**Standalone code to reproduce the issue**

```python
class CustomMetric(keras.metrics.Metric):
    def __init__(self, name: Optional[str] = None) -> None:
        super().__init__(name=name)
        self.total = self.add_weight("total", initializer="zero")
        self.count = self.add_weight("count", initializer="zero")

    def update_state(self, y_true, y_pred, sample_weight=None) -> None:
        self.total.assign_add(tf.reduce_sum(y_pred))
        print(y_true.shape[0]) # Cannot extract tensor's shape
        self.count.assign_add(y_true.shape[0])

    def result(self) -> tf.Tensor:
        return tf.math.divide_no_nan(self.total, self.count)

    def reset_state(self) -> None:
        self.total.assign(0)
        self.count.assign(0)
```

**Comment by jvishnuvardhan** [comment]
@hoangtnm Can you please share a simple standalone code to reproduce the issue? The current code is only partial. Thanks!

**Comment by hoangtnm** [comment]
@jvishnuvardhan Hi, this is my [notebook](https://colab.research.google.com/drive/142x49hRMzy0KK85ggEIpAW7beJJJuLB4?usp=sharing) to reproduce this issue.

**Comment by jvishnuvardhan** [comment]
@hoangtnm I am not sure why it is throwing that error in graph mode but works in eager mode. You can run the model in eager mode (at the cost of some computational time) by adding `run_eagerly=True` in `model.compile` as shown below

```
model.compile(
    optimizer=keras.optimizers.RMSprop(),  # Optimizer
    # Loss function to minimize
    loss=keras.losses.SparseCategoricalCrossentropy(),
    # List of metrics to monitor
    metrics=[keras.metrics.SparseCategoricalAccuracy(), CustomMetric()], run_eagerly=True#
)
```

Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/56ad07307b611504f9ce97f5536a26a4/untitled0.ipynb). Thanks

**Comment by hoangtnm** [comment]
@jvishnuvardhan thank your for your response, I solved the problem with `run_eagerly=True`, but I think some custom losses or metrics might need to know the shape of inputs, because the last batch of each epoch is often smaller than normal `batch_size`. Therefore, it is really important to know the batch_size to implement some custom logic. Do you think its root cause is caused by `tf.keras` or whether there is any operation to know the batch_size or arbitrary size of arbitrary dimension of a tensor?

**Comment by jvishnuvardhan** [comment]
@hoangtnm I thought I added a response earlier but don't see here. 

Ultimately, I removed `run_eagerly=True` from compile (which makes it as your original code)

In your code you are trying to access static shape where it is `None`. It is recommended to use dynamic shape so that at the runtime, code understands the actual size of the variable. The following line is what I changed. 

`self.count.assign_add(float(tf.shape(y_true)[0])) `

[Here](https://colab.research.google.com/gist/jvishnuvardhan/b5498c456b186758dcb87e78533fe618/untitled0.ipynb) is a gist for reference. Thanks!

You can check [this response](https://github.com/tensorflow/tensorflow/issues/35798#issuecomment-574017006) to know more about why we use dynamic shape


> The root cause is not because of TensorArray, but the way it is used. The important part here is "x.shape[0]". Note that x.shape returns the static shape of x. In the case of model.predict, since the batch size is not configured on the model, we tend to build the graph with a dynamic batch size, so that the same tf.function can be used with different batch size inputs. The result of x.shape is [None, 1] and then cause the tensorarray to fail to init.
> 
> If you change it to "tf.shape(x)[0]", which is the dynamic shape, tensorarray will correctly init even the batch is not known at the time. Hope this can be a workaround for you.

Please close the issue if this was resolved for you. Thanks!

**Comment by hoangtnm** [comment]
@jvishnuvardhan thank you for your response. your solution works perfectly :))

**Comment by ymodak** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
