### ISSUE TITLE
The model saving is disturbed by the error raised intentionaly.

### ISSUE THREAD

**Issue by realmadridmarcelo** [keras-team/keras#15940]
### **Purpose**
I want to save the keras model which includes in TFbert layer.

### **Details**
I tried to excute below the code on ipython notebook.

`pretrain_model = TFBertModel.from_pretrained('cl-tohoku/bert-base-japanese-whole-word-masking')`

(This code block means the function definition. I want to make the indents but I couldn't owing to my knowledge about markdown notation.)
`def build_model(bert_model, max_length=max_length, bert_frozen=True, class_num=3):`
`    bert_model.layers[0].trainable = not bert_frozen`
`    input_ids = tf.keras.layers.Input(shape=(max_length, ), dtype=tf.int32, name='input_ids')`
`    attention_mask = tf.keras.layers.Input(shape=(max_length, ), dtype=tf.int32, name='attention_mask')`
`    token_type_ids = tf.keras.layers.Input(shape=(max_length, ), dtype=tf.int32, name='token_type_ids')`
`    inputs = [input_ids, attention_mask, token_type_ids]`
`    bert = bert_model(inputs)`
`    pooler_output = bert.pooler_output`
`    output = tf.keras.layers.Dense(class_num, activation="softmax", name='output')(pooler_output)`
`    model = tf.keras.Model(inputs=inputs, outputs=[output])`
`    optimizer = tf.keras.optimizers.Adam(learning_rate=3e-5, epsilon=1e-08, clipnorm=1.0)`
`    model.compile(optimizer=optimizer, loss="categorical_crossentropy", metrics=["acc"])`
`    return model`

`model = build_model(pretrain_model)`
Finaly, I excuted this.
`model.save('./model.h5)`

Then, this implementation raised an error with this error message.
`NotImplementedError                       Traceback (most recent call last)`
`/var/folders/vg/3gw4b6cx37l87mcy_hlpswy80000gn/T/ipykernel_1932/1770228413.py in <module>`
`----> 1 history.model.save('./model.h5')`
``
`/usr/local/Caskroom/miniforge/base/envs/<conda_env_name>/lib/python3.8/site-packages/keras/utils/traceback_utils.py in error_handler(*args, **kwargs)`
`     65     except Exception as e:  # pylint: disable=broad-except`
`     66       filtered_tb = _process_traceback_frames(e.__traceback__)`
`---> 67       raise e.with_traceback(filtered_tb) from None`
`     68     finally:`
`     69       del filtered_tb`
``
`/usr/local/Caskroom/miniforge/base/envs/<conda_env_name>/lib/python3.8/site-packages/keras/engine/training.py in get_config(self)`
`   2435 `
`   2436   def get_config(self):`
`-> 2437     raise NotImplementedError`
`   2438 `
`   2439   @classmethod`

`NotImplementedError: `

I can't find why get_config() is defined to raise this error.

I also tried
`model.get_config()`
and get the same error.
`raise NotImplementedError`

I expect to get hints to solve this.

### **Supplement**

I tried this.
`model.save('model)`
(I only removed the string '.h5')
and get the message.
`StagingError: in user code:`

`    File "/usr/local/Caskroom/miniforge/base/envs/<conda_env_name>/lib/python3.8/site-packages/keras/saving/saving_utils.py", line 125, in _wrapped_model  *`
`        outputs = model(*args, **kwargs)`
`    File "/usr/local/Caskroom/miniforge/base/envs/<conda_env_name>/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler  **`
`        raise e.with_traceback(filtered_tb) from None`
`    File "/usr/local/Caskroom/miniforge/base/envs/<conda_env_name>/lib/python3.8/site-packages/transformers/models/bert/modeling_tf_bert.py", line 872, in call`
`        inputs = input_processing(`
`    File "/usr/local/Caskroom/miniforge/base/envs/<conda_env_name>/lib/python3.8/site-packages/transformers/modeling_tf_utils.py", line 389, in input_processing`
`        output[parameter_names[i]] = input`

`    IndexError: Exception encountered when calling layer "tf_bert_model" (type TFBertModel).`
    
`    list index out of range`
    
`    Call arguments received:`
`      • args=(['tf.Tensor(shape=(None, 128), dtype=int32)', 'tf.Tensor(shape=(None, 128), dtype=int32)', 'tf.Tensor(shape=(None, 128), dtype=int32)'],)`
`      • kwargs={'training': 'False'}`

I couldn't find the relationship with NotImplementedError.

### **Environment**
- Machine: MacBookPro 14inch Apple M1 Max
- Package Management: conda mini-forge
- about tensorflow: 
tensorboard               2.6.0              pyhd8ed1ab_1    conda-forge
tensorboard-data-server   0.6.0            py38h10d4710_1    conda-forge
tensorboard-plugin-wit    1.8.1              pyhd8ed1ab_0    conda-forge
tensorflow-deps           2.7.0                         0    apple
tensorflow-estimator      2.7.0                    pypi_0    pypi
tensorflow-macos          2.7.0                    pypi_0    pypi
tensorflow-metal          0.3.0                    pypi_0    pypi
- about Keras
keras                     2.7.0              pyhd8ed1ab_0    conda-forge
keras-preprocessing       1.1.2              pyhd8ed1ab_0    conda-forge

**Comment by jvishnuvardhan** [comment]
@realmadridmarcelo I am not able to reproduce the issue. When I ran your code, I was able to save the model in `h5` format but couldn't load it. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/f53d38e7cc05c9fef9a505aa5aaecd7e/untitled1145.ipynb). Thanks!

Please check whether I made any mistake. Thanks!

**Comment by realmadridmarcelo** [comment]
Thank you for your examination!
Your code and mine are almost the same.
Only one difference is the python version. (My env: 3.8.12, Your env: 3.7)
But I think that it is not essential for this issue.

**Comment by QuentinMahieu** [comment]
I encounter the exact same problem.
I was able to build the model saving weights only. 
But when I want to save the entire model I get the same error as you @realmadridmarcelo 
Any solution yet?

**Comment by realmadridmarcelo** [comment]
@QuentinMahieu Thank you for asking..
I've never solved this.
I only know that this issue causes when Custom Layer is introduced into the model...

**Comment by jvishnuvardhan** [comment]
@QuentinMahieu Can you please share a standalone code that I can reproduce? I am not sure why but I couldn't reproduce the issue with @realmadridmarcelo code. Thanks

**Comment by QuentinMahieu** [comment]
@jvishnuvardhan I just created a notebook on Google Colab.
Here is the [https://colab.research.google.com/drive/1j84NqR3cD8aZkd2MhwEbUqled_cigAWy?usp=sharing](link)
it takes about 25 min to fit the model.

**Comment by jvishnuvardhan** [comment]
@QuentinMahieu I don't have access to the following file `SetenceSentiSample.csv` that you are loading 

`df = pd.read_csv('/content/sample_data/SetenceSentiSample.csv')`

**Comment by QuentinMahieu** [comment]
@jvishnuvardhan  Sorry, I didn't realise that the files were deleted once the session is closed. Just add this file to your drive, I have modified the code to get the file from dive and this should work (works for me)
[SentencesSentiment.csv](https://github.com/keras-team/keras/files/8221705/SentencesSentiment.csv)
