### ISSUE TITLE
tf.keras.layers.Conv2D seems to accept 0 as the value of filters by mistake.

### ISSUE THREAD

**Issue by linmajia** [keras-team/keras#15942]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): 2.7.0
- Python version: 3.8

Please refer to tensorflow/python/keras/layers/convolutional.py, lines 139-141:
```python
 if filters is not None and filters < 0:
      raise ValueError(f'Received a negative value for `filters`.'
                       f'Was expecting a positive value, got {filters}.')
```
The error message says that the filters expects a positive value. It seems that the validation code  should be "filters <= 0".

**Comment by AdityaKane2001** [comment]
@linmajia 

Please see #15943

**Comment by linmajia** [comment]
@AdityaKane2001 , thank you very much!

**Comment by jvishnuvardhan** [comment]
Thanks @AdityaKane2001 .

@linmajia Thanks for raising this issue. This issue will be closed once the above PR merges into `master`.
