### ISSUE TITLE
Silent swallowing of Exceptions thrown in `get_config` and potentially `from_config` / Documentation of SavedModel for custom Model

### ISSUE THREAD

**Issue by burnpanck** [keras-team/keras#15978]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): Yes (custom layers and models)
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 12.1 on M1 Max
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): unknown 2.7.0
- Python version: 3.9.8
- Bazel version (if compiling from source):
- GPU model and memory: M1 Max 64 GB shared
- Exact command to reproduce: N/A

**Describe the problem**.

I am trying to round-trip a trained model through a SavedModel on disk. The model is a custom subclass of `tf.keras.Model`, which combines building blocks that are themselves subclasses of `Model`, sometimes also `Sequential`. These models basically abstract lower-level primitive layers and add a few methods that help with data preparation that I still need after the round-trip. However, instead of my subclass, I would get a generic `keras.saving.saved_model.load.GeneratedReplacementOfMyCustomModel` instead, despite having implemented a `get_config` as instructed in the doc. The issue was that my `get_config` would call `super().get_config`, as illustrated in the [SavedModel guide](https://www.tensorflow.org/guide/keras/save_and_serialize#custom_objects). This seems to be valid for subclasses of `Layers` as well as `Sequential`, but not direct subclasses of `Model` - their `get_config` raises an exception, _which gets swallowed by the machinery_. This severely hinders the discoverability of the correct mechanism - and it is against the [Zen of Python: "Errors should never pass silently."](https://www.python.org/dev/peps/pep-0020/). Similarly, a missing `from_config` also causes the model not to be restored fully, without any indication why.

**Describe the current behavior**.
- The documentation of the required steps to fully round-trip a custom `tf.keras.Model` leaves out important information.
- The SavedModel machinery swallows important exceptions and does not notify the user about that, silently creating "wrong" (or at least unintended) output.

**Describe the expected behavior**.
- The documentation mentions:
 - Custom `Layer` should call `super` in `get_config` and `from_config`.
 - Custom `Model` should not call `super` in `get_config` and `from_config`, but instead,
    they need to include nested layers into the config through `tf.keras.layers.serialize` / `unserialize`.
    Alternatively, `Model.get_config` could try to inspect instance variables to see if there are any nested layers and models,
    and handle that for the custom model.
- The SavedModel machinery should not swallow exceptions (or at least cause a warning) whenever user code is present for either 
   `get_config` or `from_config` and not both of them pass as expected.

**Contributing**.

- Do you want to contribute a PR? (yes/no): no 

**Standalone code to reproduce the issue**.

```python
import tensorflow as tf
import numpy as np

class CustomModel(tf.keras.Model):
    def __init__(self, n_features, extra, **kw):
        super().__init__(**kw)
        self.n_features = n_features
        self.extra = extra
        self.layer = tf.keras.layers.Conv1D(n_features,2)
    
    def get_config(self):
        try:
            ret = super().get_config()
        except Exception as ex:
            print(f"Exception in CustomModel.get_config(): {ex!r}")
            raise    # !! 1
            # instead, we should do
            ret = dict(layers=[
                dict(name=k,config=tf.keras.layers.serialize(getattr(self,k)))
                for k in ["extra"]
            ])
        ret.update({
            k:getattr(self,k) for k in ["n_features"]
        })
        return ret
    
    @classmethod
    def from_config(cls, config):
        try:
            layers = {
                l["name"]: tf.keras.layers.deserialize(l["config"])
                for l in config.pop("layers")
            }
            raise RuntimeError("I did a coding error here") # !! 2
            return cls(**config,**layers)
        except Exception as ex:
            print(f"Exception in CustomModel.from_config(): {ex!r}")
            raise
    
    def call(self, input, training=False):
        intermediate = self.layer(input, training=training)
        output = self.extra(intermediate, training=training)
        return output
    
    
model = CustomModel(2, tf.keras.layers.Conv1D(2,2))
model.predict(np.zeros((1,10,2)))
model.save("test")

loaded_model = tf.keras.models.load_model(
    "test",
    custom_objects={
        k.__name__: k
        for k in [CustomModel]
    },
)
assert type(loaded_model) is type(model)
```

If the two lines marked with `!! 1` and `!! 2` are commented out, the final assert passes. Note that both indicate a form of coding error (the first potentially more subtle) but without the print statement, there would be no feedback at all to the user about the problem.

**Comment by kumariko** [comment]
@burnpanck I tried to reproduce the issue on colab using TF v2.7.0 and tf-nightly but facing different issue .Could you please have a look on the [gist](https://colab.research.google.com/gist/kumariko/a2f2a6f28ca551aaa429c798a4652e72/10474.ipynb#scrollTo=Eo7e6fuVwjOe) and let me know if i'm missing something ?

**Comment by burnpanck** [comment]
It looks like the silent swallowing is fixed in tf-nightly. In particular, neither the exceptions in `from_config` nor in `get_config` are swallowed, but propagated instead. The error you experienced was because `tf.keras.Model` now also seems to implement a bare `get_config`, so the `NotImplementedError` wasn't being raised in the first place. Then the returned config was not suitable for the subsequent `from_config`.

What is still open though is therefore a definite documentation what exactly `get_conig` and `from_config` should do on a `Model` (and also in comparison to a `Layer`). In particular, should they call their parent-class implementation? How should they handle nested `Layers` and `Models`? Are those handled by the parent class? By the machinery itself? Who is responsible for the name of itself and of nested objects? Should the name be part of the config or not? (grepping though the source code, I found mentions of some kind of "metadata" handling the name within the machinery). What else is the machinery taking care of?

The gist/MWE handles the nested layer that is provided as an argument completely, while relies on `__init__` to re-create the nested layer that it "owns". However, I'm absolutely not sure if that is the right way to do, or if that actually double-creates some layers somewhere in the machinery. Or if they end up having the right name/if they do get their weights assigned during load.

**Comment by burnpanck** [comment]
Re TF 2.7.0, I could reproduce the issue with your gist. Of course, the assert at the end will raise, as an indication of the issue.
