### ISSUE TITLE
Feature/documentation request: re-add activation histograms or remove from docs

### ISSUE THREAD

**Issue by bersbersbers** [keras-team/keras#15972]
**System information**.

TensorFlow version: 2.8.0-rc1

**Describe the feature and the current behavior/state**.

https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/TensorBoard says:

> `histogram_freq`: frequency (in epochs) at which to compute *activation* and weight *histograms* for the layers of the model. If set to 0, histograms won't be computed. Validation data (or split) must be specified for histogram visualizations.

But I am fairly certain activation histograms are not written, see also https://github.com/tensorflow/tensorflow/issues/39755 and https://github.com/tensorflow/tensorflow/issues/42027.

Solutions:
1. re-implement the documented feature (it existed before)
2. un-document the un-implemented feature

**Will this change the current api? How?**

1 will not change the API; 2 will change the docs.

**Who will benefit from this feature?**

Everyone

**Comment by Cheril311** [comment]
I can try to solve this

**Comment by Cheril311** [comment]
Hey @bersbersbers as far as I know you can visualize histograms in 
tensorboard by using tf.summary.histogram<br>Can you please attach your code so that I can see if we are on the same page?

**Comment by bersbersbers** [comment]
@Cheril311 please see https://github.com/tensorflow/tensorflow/issues/42027#issuecomment-670719469. Keras writes weight histograms, but no activation histograms.

**Comment by Cheril311** [comment]
@bersbersbers you seem to be right, however I am changing just the documentation for now and removing activation histograms from there rather than adding it as a feature as callbacks.py version 2 in the keras file seems to create histograms by calling tf.summary and in the documentation for tf.summary I see a feature for activation histograms as shown here https://www.tensorflow.org/api_docs/python/tf/summary/histogram so I believe this is some merge issue. Will wait for keras-team or a tensorflower to review the actual feature

**Comment by Cheril311** [comment]
You seem to be right @bersbersbers , for now I have changed the documentation as I do know how to compute activation histograms but I am unaware on how to write them as tensorboard images

**Comment by bersbersbers** [comment]
> I do know how to compute activation histograms but I am unaware on how to write them as tensorboard images

I would think activation histograms can be written the same way as the weight histograms, at least in a first iteration. After all, both should have the exact same dimensions.

**Comment by Cheril311** [comment]
> > I do know how to compute activation histograms but I am unaware on how to write them as tensorboard images
> 
> I would think activation histograms can be written the same way as the weight histograms, at least in a first iteration. After all, both should have the exact same dimensions.

Yup I agree with that but there is some other process done in the function  _log_weight_as_image in callbacks.py and I am not sure how to do the same for activations, if you can help me maybe we can submit a pr

**Comment by bersbersbers** [comment]
> > I would think activation histograms can be written the same way as the weight histograms, at least in a first iteration. After all, both should have the exact same dimensions.
> 
> Yup I agree with that but there is some other process done in the function _log_weight_as_image in callbacks.py and I am not sure how to do the same for activations, if you can help me maybe we can submit a pr

To my understanding, activations and weights have the same shape, so you can do exactly the same thing as here:

https://github.com/keras-team/keras/blob/8015f697d0109ccd6021fe1b8f2bf5b133b259b9/keras/callbacks.py#L2570-L2580

Since you mentioned in https://github.com/keras-team/keras/issues/15972#issuecomment-1024857466 that you know how to compute activation histograms (although I have yet to find a good solution myself, compare https://stackoverflow.com/q/60816678, https://gist.github.com/SiLiKhon/3965c967c3283feccc79822e6252b34c, https://stackoverflow.com/q/66779524), this should be straightforward then. Good luck!

**Comment by haifeng-jin** [comment]
Summary: The tensorboard callback doesn't print activation histograms. The solution is either change the docs or fix this bug.

**Comment by haifeng-jin** [comment]
This should have been fixed. Please reopen if it is not.

**Comment by bersbersbers** [comment]
@haifeng-jin may I ask where I can see the change? Did you update the docs or implement the functionality?

I don't see any commit on https://github.com/keras-team/keras/commits/master, and https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/TensorBoard (which has been updated for TB2.8.0) still mentions "Activation histograms".

**Comment by haifeng-jin** [comment]
@bersbersbers Do you reproduce it in TF-nightly? The commit should be sometime ago. This was from the team member who handled this.
If so, you can create a Colab notebook, which can show tensorboard in it.
Thanks

**Comment by bersbersbers** [comment]
@haifeng-jin I am getting errors with TensorBoard on `tf-nightly` (ValueError: Duplicate plugins for name projector), so I cannot test it there. The code that reproduces the issue on TF/TB2.8.0 with `keras-nightly` (I guess this is the important nightly part) is this:

```python
# pip install tensorflow
# pip uninstall keras
# pip install keras-nightly
import tensorflow as tf
dataset = tf.data.Dataset.from_tensor_slices([[1]])
data = tf.data.Dataset.zip((dataset, dataset))
layer = tf.keras.layers.Input(shape=())
model = tf.keras.models.Model(inputs=layer, outputs=layer)
model.compile(optimizer="adam", loss="mse", experimental_run_tf_function=False)
cb = tf.keras.callbacks.TensorBoard("logs", histogram_freq=1)
model.fit(x=data, validation_data=data, epochs=2, callbacks=[cb])
# tensorboard --logdir logs
```

And then there's weight histograms, but not activation histograms, just like 1.5 years ago.
![image](https://user-images.githubusercontent.com/12128514/152863309-a858612e-ef57-4899-86a6-3305ebbc9328.png)

**Comment by bersbersbers** [comment]
Thanks. For the record, I had previously missed the fix to the documentation in [2ba6dea](https://github.com/tensorflow/tensorflow/commit/2ba6dea0d91bce201a6a251b7dcdbb27e440c72a), hence my confusion.

**Comment by Shreyz-max** [comment]
@LukeWood anyone working on it?

**Comment by LukeWood** [comment]
> @LukeWood anyone working on it? I would like to if no one else is.

Dont think so!
