### ISSUE TITLE
Keras 2.8.0 -- Git: Please add "v2.8.0" LABEL ; that corresponds to PyPi release --- https://pypi.org/project/keras/2.8.0/ 

### ISSUE THREAD

**Issue by scottc21** [keras-team/keras#15988]
Minor GIT management issue.  
Please add a  "v2.8.0" label to the Git "2.8" branch  -- that corresponds with the 2.8.0 release that was just posted today to PyPi.

The 2.8.0 release was just posted to the PyPi website today ( Jan-31 ); however, the GIT repo at GitHub has no corresponding label.
The PyPi url to this release is:  https://pypi.org/project/keras/2.8.0/  

I will attach a screenShot that shows the current checkins and labels on the "2.8" branch.

**Comment by scottc21** [comment]
See attached screenshot of Git history & current labels

![Git_Missing_LABEL_for_2 8 0__to_correspond_to_PyPi_](https://user-images.githubusercontent.com/93684290/151866386-4086a3ac-9e0f-492e-a76f-a69f7d23f1d4.png)

**Comment by qlzh727** [comment]
Done. Create Keras 2.8 release with tag at https://github.com/keras-team/keras/releases/tag/v2.8.0
