### ISSUE TITLE
TimeDistributed(Flatten()) does not support masking

### ISSUE THREAD

**Issue by lauraht** [keras-team/keras#15980]
**System information**.

TensorFlow version: 2.7.0.

**Describe the feature and the current behavior/state**.

I hope the `TimeDistributed(Flatten())` can support masking.

My inputs are DNA sequences with variable lengths, where each base is a “timestep”. For each timestep (i.e. each base), I also use the 5-bases’ segment before the current base as a feature. So this is a hierarchical time series. Thus, I use the `TimeDistributed(LSTM())` to process the 5-bases’ segment for each timestep, and its output is concatenated with other features and then fed into a not-time-distributed higher-level LSTM. Since the DNA sequences' lengths vary, I pad and mask the sequences to a fixed length. I need to use the `TimeDistributed(Flatten())` to flatten the output from the `TimeDistributed(LSTM())` in order to feed it into a higher-level LSTM. So I have the following layers:
```
hier_lstm = TimeDistributed(LSTM(16, return_sequences=True))(masked_input)
flattened = TimeDistributed(Flatten())(hier_lstm)
```
For example, the `masked_input` has the shape `(10, 60, 5, 4)`, where the DNA sequence length is 60, and the 5-bases’ segment for each base in the sequence is one-hot encoded for 4 base-letters. Then, the `hier_lstm` has the shape `(10, 60, 5, 16)`. I need to flatten the last two dimensions of `hier_lstm` to turn it into 3D, such that it can be concatenated with other features (3D) and then fed into a higher-level LSTM.

However, `TimeDistributed(Flatten())(hier_lstm)` threw the following errors:
```
TypeError: Layer flatten does not support masking, but was passed an input_mask: tf.Tensor(
```

I think it would be very useful for the `TimeDistributed(Flatten())` to support masking, since the applications like what I described here need to use the `TimeDistributed(Flatten())` with masking when sequence lengths vary.

Since the current `TimeDistributed(Flatten())` does not support masking, I was wondering if there is any **alternative way** in Keras to solve my problem here--- to flatten the last two dimensions and turn it into 3D with masking support? I would greatly appreciate your advice.

Thank you very much!

**Comment by chenmoneygithub** [comment]
Hi, thanks for reporting the issue! Generally Flatten() will destroy the mask, because it no longer maintains the sequence dimension. Can I ask why you need to keep mask after calling Flatten()?

**Comment by lauraht** [comment]
Hello!
Thank you for your response!

Actually, I need to keep the mask after calling the `TimeDistributed(Flatten())` rather than the standalone `Flatten()`. 

My inputs are DNA sequences with variable lengths (each base is a “timestep”). For each timestep (i.e. base), I also use the 5-bases’ segment before the current base as a feature. So this is a hierarchical time series problem. This is kind of similar to the NLP problem that a sentence is a time series while each word in the sentence is a lower-level time series.

Thus, I use the `TimeDistributed(LSTM())` to process the 5-bases’ segment for each timestep, and its output is concatenated with other features and then fed into a not-time-distributed higher-level LSTM. Since the DNA sequences' lengths vary, I pad and mask the DNA sequences to a fixed length. I need to use the `TimeDistributed(Flatten())` to flatten the output from the `TimeDistributed(LSTM())` in order to feed it into a higher-level LSTM.

The reason I need to keep the mask after calling the `TimeDistributed(Flatten())` is that I need to concatenate its output with other features and then feed them into a not-time-distributed higher-level LSTM. The mask is important since the DNA sequences’ lengths are different, and the mask needs to be carried out to the final output.

Since the current `TimeDistributed(Flatten())` does not support masking, I was wondering if there is any alternative way in Keras to solve my problem here--- to flatten the last two dimensions in the output of the `TimeDistributed(LSTM())` to turn it into a 3D tensor with masking support? I would greatly appreciate your advice.

Thank you very much!

**Comment by chenmoneygithub** [comment]
I see, if I understand correctly, your input data's dimension is >3? 

It seens TimeDistributed() would not keep the mask, so there are two approaches you can try in this case:
1. Handle the masking by yourself, which means you always keep an variable, let's call it `mask`, and at each layer, you manually pass it into the layer call.
2. Repopulate the mask. Mask is stored as `inputs._keras_mask` if it is present, so after your TimeDistributed(Flatten()) call, you can reset `inputs._keras_mask` as your original mask.

**Comment by lauraht** [comment]
Thank you so much for your advice!

Yes, my input is 4D.

So you mean I can set the ` ._keras_mask` to `None` before going into the `TimeDistributed(Flatten())` layer and then restore the ` ._keras_mask` after calling `TimeDistributed(Flatten())`? Something like the following:
```
hier_lstm = TimeDistributed(LSTM(16, return_sequences=True))(masked_input)
kept_mask = hier_lstm._keras_mask
hier_lstm._keras_mask = None
flattened = TimeDistributed(Flatten())(hier_lstm)
flattened._keras_mask = kept_mask
```
However, the ` ._keras_mask` is 3D before calling `TimeDistributed(Flatten())`. After calling `TimeDistributed(Flatten())`, the ` ._keras_mask` is supposed to be 2D. So if we give the original 3D `._keras_mask` to the output of `TimeDistributed(Flatten())`, I was wondering if this dimensionality inconsistency could work out for the subsequent layers?

Another question is, since the ` ._keras_mask` is not passed into `TimeDistributed(Flatten())`, the `TimeDistributed(Flatten())` does not ignore those supposed-to-be-masked data--- would this have any effect on the subsequent layers in their masking data handling?

Thank you very much for your help!

**Comment by chenmoneygithub** [comment]
Mask should be applied on the sequence dimension, so for your 4D input, the mask should still be 2D? If your mask is actually 3D due to your use case, then you may need to design on how to collapse your 3D mask to 2D. 

Flatten() should not be affected by mask, so you can always populate back the mask after the layer. Hope it could help you, thanks!
