### ISSUE TITLE
Feature/documentation request: Point cloud transformer

### ISSUE THREAD

**Issue by yhpeng6** [keras-team/keras#16004]
TensorFlow version (you are using): TensorFlow version: 2.7.0

Describe the feature clearly here. Be sure to convey here why the requested feature is needed. Any brief description about the use-case would help.
The [point cloud transformer](https://github.com/MenghaoGuo/PCT) and [point transformer](https://github.com/qq456cvb/Point-Transformers) are effective method to get the global or local feature of point cloud recently based on attention mechanism. These features can be used for segmentation and classification tasks of point cloud, and have the better performance than PointNet (published in2018).

I think it is necessary to update the more advanced method for point cloud processing.

**Will this change the current api? How?** 
No, add the document examples.

**Who will benefit from this feature?** 
The researchers working on point cloud.

**Comment by niranjankrishna-acad** [comment]
@yhpeng6 I'm gonna start working on the Point Cloud transformer

**Comment by yhpeng6** [comment]
Very thanks for your consideration!

**Comment by haifeng-jin** [comment]
You are welcome to add this example to [keras.io](https://github.com/keras-team/keras-io) if you don't find anything similar in the existing examples.
That is where we keep the various code examples of Keras.
