### ISSUE TITLE
Option for using dropout in the predict phase when using Functional model

### ISSUE THREAD

**Issue by cevheck** [keras-team/keras#16000]
I have recently been working on something that resembles a PINN (cfr Maziar Raissi) and for this I have been combining physical equations with keras Sequential models in a combined Keras.Model(). I would now like to add dropout during inference for bayesian approximation, I am trying to add the training=True argument to the dropout layer. 

In another issue (https://github.com/keras-team/keras/issues/9412#issuecomment-510609226) someone suggest you could just add this to the model.add function, however this keeps on resulting in:
"TypeError: ('Keyword argument not understood:', 'training')".

However adding it during the call feels like it is not propagating from the call on the Keras.Model to the underlying Sequential model. I was hoping someone could help me tackle this issue.

Thanks in advance
Cedric

Python 3.9
TF 2.5.0

**Comment by Cheril311** [comment]
@cevheck can you please provide your code snippet ?

**Comment by cevheck** [comment]
@Cheril311 Unfortunately I cannot share my code. The following lines show a simplified version of what I mean.
NNmodel = tensorflow.keras.Sequential()
NNmodel.add(tensorflow.keras.layers.Dense(32, activation='relu'))
NNmodel.add(tensorflow.keras.layers.Dropout(rate=0.2, training=True))
NNmodel.add(tensorflow.keras.layers.Dense(1))
output = 1 + 2*(inputs) + NNmodel(inputs)

model = tf.keras.Model(inputs=inputs, outputs=output)

X_train = ...
X_output = model(X_train)

-------
When calling the model I would like the Dropout layer to be in training=True mode in order to obtain different results every time. The above code however returns TypeError: ('Keyword argument not understood:', 'training').

However, in the meantime I've succeeded in what I wanted to do, the problem actually came down to the following:
dropoutlayer = tensorflow.keras.layers.Dropout(rate=0.2, training=True)
does not work as mentioned in the comment I refered to. The training argument should be passed to the call function as mentioned in the official documentation. 
For my toy example this comes down to adding a normal dropout layer and changing 
output = 1 + 2*(inputs) + NNmodel(inputs)
to
output = 1 + 2*(inputs) + NNmodel(inputs, training=True)

However I hope you can imagine that, if desired to switch between training=True and training=False and in a more extensive code, this is not that straightforward.

The challenge thus lies in propagating the training=True argument from the Functional model to the Sequential. Although my issue is resolved in the meantime, it might be an interesting feature to be able to add a Dropout layer in the manner mentioned above. 

Greetings,
Cedric

**Comment by jvishnuvardhan** [comment]
@cevheck Are you trying to use a Sequential model or a Functional Model? As you cannot your code, can you use some public model and show us what is the problem you are facing? For example, take this tutorial https://www.tensorflow.org/guide/keras/functional and update according to your application.

In recent TF/Keras versions, model automatically infer `training=True` when you call `model.fit` or you can pass training argument as in `model(X, training=True)` . Hope it helps. Thanks!

**Comment by cevheck** [comment]
@jvishnuvardhan As you can see in the code I posted in my previous comment I am using both. I'm writing a Functional Model (I believe it's called that way anyways) the tf.keras.model(...), which is using an equation where a single term is predicted using a sequential neural network.

**Comment by jvishnuvardhan** [comment]
@cevheck Can you please use any public dataset and create a simple standalone code to reproduce the issue. Without code, it may take too much effort with/without any possible resolution.  

Dropout or any other layer in keras, automatically infer the training argument. Thanks
