### ISSUE TITLE
plot_model gives error when using the Functional API and adding custom loss

### ISSUE THREAD

**Issue by faikozcan** [keras-team/keras#16011]
I am trying to implement a variational autoencoder. I am using google colab as environment.
The code sample shown in this page: https://www.tensorflow.org/guide/keras/custom_layers_and_models#the_model_class
at part "Beyond object-oriented development: the Functional API" .

The loss function is added as following:
`        kl_loss = -0.5 * tf.reduce_mean(z_log_var - tf.square(z_mean) - tf.exp(z_log_var) + 1)
        vae.add_loss(kl_loss)`

I can build and train and test model, it works but when i try to plot the model by using  tensorflow.keras.utils.plot_model
i get the following error:

[/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py](https://localhost:8080/#) in __getattr__(self, name)
    440         from tensorflow.python.ops.numpy_ops import np_config
    441         np_config.enable_numpy_behavior()""".format(type(self).__name__, name))
--> 442     self.__getattribute__(name)
    443 
    444   @staticmethod

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute '_keras_history'

When i remove the  add kl_loss part, it does not give any error.

**Comment by gowthamkpr** [comment]
@faikozcan This is similar to this [issue](https://discuss.tensorflow.org/t/attributeerror-tensorflow-python-framework-ops-eagertensor-object-has-no-attribute-keras-history/3095). Can you please take a look at the issue. Thanks!
