### ISSUE TITLE
ImportError: cannot import name 'AtrousConvolution2D'

### ISSUE THREAD

**Issue by mazimiucc** [keras-team/keras#16035]
from keras.layers import AtrousConvolution2D
ImportError: cannot import name 'AtrousConvolution2D'

keras 2.6.0
tensorflow 2.6.2 
gpu

**Comment by old-school-kid** [comment]
Hi @mazimiucc 
There is no such layer as AtrousConvolution2D under Keras. Instead you can use the `dilation_rate` parameter under Conv2D layer.
Hope this helps!
