### ISSUE TITLE
Multi-input model cannot be saved using `.h5` format when using pretrained backbone

### ISSUE THREAD

**Issue by AdityaKane2001** [keras-team/keras#16037]
**Describe the problem**.
I am using a multi-input single output model with `ResNet50V2` as the backbone. However, when I try to save it using the h5 format, it errors out. The reason is both backbones have layers of the same name. However, `ResNet50V2` has no option of adding a name extension, which prevents the user from changing layer names.  

**Describe the current behavior**.
See [gist](https://colab.research.google.com/gist/AdityaKane2001/c6390152e56742cbaa1ad696edb910ed/saving_issue.ipynb) for minimal reproducible code.

**Describe the expected behavior**.
Model should be saved successfully. 

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no): No

/cc @qlzh727 @gbaned @bhack

**Comment by sushreebarsa** [comment]
@jvishnuvardhan Was able to reproduce the issue on colab using TF v2.8.0 and tf-nightly(2.9.0.dev20220209) ,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/5dd4d2ae55d0e8426293be9aa3f98136/saving_issue.ipynb#scrollTo=-Ru10Pqp3Ryr) for reference.Thanks!

**Comment by AdityaKane2001** [comment]
@sushreebarsa 

The notebook is not opening:
![image](https://user-images.githubusercontent.com/64411306/153246293-80660f2b-eac9-4a28-8107-6e1045dcc6e7.png)

**Comment by sushreebarsa** [comment]
@AdityaKane2001 Please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/5f74bb70ffeaeedfa68e76f57ab1d0af/saving_issue.ipynb),Thanks!
