### ISSUE TITLE
Models in `tf.keras.applications` should have provision for custom naming

### ISSUE THREAD

**Issue by AdityaKane2001** [keras-team/keras#16039]
See #16037. The error is caused because the user cannot assign custom name to the layers from models from `tf.keras.applications`. I am opening this issue to rectify that. 

If it is okay, I would like to open a few PRs adding a minor naming system to all the models, as in RegNets [(1)](https://github.com/keras-team/keras/blob/461199818c6777061411eb12ae33f1576dfcfb21/keras/applications/regnet.py#L354-L364) [(2)](https://github.com/keras-team/keras/blob/461199818c6777061411eb12ae33f1576dfcfb21/keras/applications/regnet.py#L854-L856).

/cc @qlzh727 @sushreebarsa @jvishnuvardhan @gbaned @parthsr5

**Comment by chenmoneygithub** [comment]
PRs are more than welcome! Thanks for contributing!
