### ISSUE TITLE
Customize what happens in Model.fit with multi-output model and metrics

### ISSUE THREAD

**Issue by hoangtnm** [keras-team/keras#16030]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow installed from (source or binary): conda-forge
- TensorFlow version (use command below): 2.7
- Python version: 3.7

**Describe the problem**.

I'm trying to write custom Model.fit according to [TF doccument](https://www.tensorflow.org/guide/keras/customizing_what_happens_in_fit), but it seems that the document is tailored for single-output model, so `self.compiled_loss` and `self.compiled_metrics` works as expected. But when I use a multi-output model which uses different losses and metrics for each output, so `self.compiled_metrics` only returns `<keras.engine.compile_utils.MetricsContainer at 0x7f6f2002e350>` rather than a dictionary as expected:

```python
model.compile(
    metrics={
        "score_output": [
            keras.metrics.MeanAbsolutePercentageError(),
            keras.metrics.MeanAbsoluteError(),
        ],
        "class_output": [keras.metrics.CategoricalAccuracy()],
    },
)
```

Is there anyway to use it in the right way? thank you

**Comment by ghylander** [comment]
metrics are not returned as a dict by default, you have to use the `return_dict=True` argument when doing model.evaluate()
[check the tf.keras.model docs](https://www.tensorflow.org/api_docs/python/tf/keras/Model#evaluate)

**Comment by hoangtnm** [comment]
@ghylander I mean I want to customize how `model.fit` by implementing `model.train_step` manually:

```python
class CustomModel(keras.Model):
    def train_step(self, data):
        # Unpack the data. Its structure depends on your model and
        # on what you pass to `fit()`.
        x, y = data

        with tf.GradientTape() as tape:
            y_pred = self(x, training=True)  # Forward pass
            # Compute the loss value
            # (the loss function is configured in `compile()`)
            loss = self.compiled_loss(y, y_pred, regularization_losses=self.losses)

        # Compute gradients
        trainable_vars = self.trainable_variables
        gradients = tape.gradient(loss, trainable_vars)
        # Update weights
        self.optimizer.apply_gradients(zip(gradients, trainable_vars))
        # Update metrics (includes the metric that tracks the loss)
        self.compiled_metrics.update_state(y, y_pred)
        # Return a dict mapping metric names to current value
        return {m.name: m.result() for m in self.metrics}
```
As you can see, `self.compiled_metrics.update_state` assumes multiple complied_metrics will use the same `y, y_pred` as input, which doesn't work for multi-output model using multiple losses and metrics for each output.

**Comment by ghylander** [comment]
I see, thanks for the clarification, I didn't understand your question

I don't have experience with multi-output models with each ouput having different metrics, but having a look at this [keras guide on how to build a training function from scratch](https://keras.io/guides/writing_a_training_loop_from_scratch/#lowlevel-handling-of-metrics), I would try to instantiate the metrics for each ourput, then try something like (pseudo-code: quickly patched from the guide I linked)
```
val_acc_metric1 = keras.metrics.SparseCategoricalAccuracy()
val_acc_metric2 = keras.metrics.SparseCategoricalAccuracy()

 for x_batch_val, y_batch_val1, y_batch_val2 in val_dataset:
        val_logits = model(x_batch_val, training=False)
        # Update val metrics
        val_acc_metric1.update_state(y_batch_val1, val_logits[0])
        val_acc_metric2.update_state(y_batch_val2, val_logits[0])
    val_acc1 = val_acc_metric1.result()
    val_acc2 = val_acc_metric2.result()
    val_acc_metric1.reset_states()
    val_acc_metric2.reset_states()
```

**Comment by hoangtnm** [comment]
@ghylander implementing custom training_loop scratch can solve the problem easily, but I aim to leverage `train_step` so that I can use `model.fit`, which is cleaner and easier to maintain.

**Comment by ghylander** [comment]
check [this](https://keras.io/guides/customizing_what_happens_in_fit/) out
seems to be more in line with what you want

**Comment by sushreebarsa** [comment]
@hoangtnm Could you please refer to the [comment](https://github.com/keras-team/keras/issues/16030#issuecomment-1033728000) above and let us know if it helps?Thanks!
