### ISSUE TITLE
ResourceExhaustedError:

### ISSUE THREAD

**Issue by NevilShingala** [keras-team/keras#16047]
ResourceExhaustedError: OOM when allocating tensor with shape[5,64,4890,4890] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
[[node sequential/conv2d/Relu
(defined at /usr/local/lib/python3.7/dist-packages/keras/backend.py:4867)
]]
Below is my code:
from google.colab import drive

drive.mount('/content/drive')

import tensorflow as tf
from keras.layers import Input, Lambda, Dense, Flatten, MaxPooling2D, Conv2D
from keras.models import Model
#from keras.applications.resnet50 import ResNet50
from PIL import Image, ImageChops
from keras.applications.vgg16 import VGG16
from keras.applications.vgg16 import preprocess_input
from keras.preprocessing import image
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from tensorflow.keras.callbacks import EarlyStopping,ReduceLROnPlateau
import numpy as np
from glob import glob
import matplotlib.pyplot as plt
IMAGE_SIZE =[4892, 4892]
train_path = '/content/drive/MyDrive/ColabNotebooks1/FinalDataLeft/Train'
valid_path = '/content/drive/MyDrive/ColabNotebooks1/FinalDataLeft/Test'

folders = glob('/content/drive/MyDrive/ColabNotebooks1/FinalDataLeft/Train/*')

from keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(rescale = 1./255,
shear_range = 0.2,
zoom_range = 0.2,
horizontal_flip = True)

test_datagen = ImageDataGenerator(rescale = 1./255)
test_set = test_datagen.flow_from_directory('/content/drive/MyDrive/ColabNotebooks1/FinalDataLeft/Test',
target_size = (4892, 4892),
batch_size = 5,
class_mode = 'categorical')

training_set = train_datagen.flow_from_directory('/content/drive/MyDrive/ColabNotebooks1/FinalDataLeft/Train',
target_size = (4892, 4892),
batch_size = 5,
class_mode = 'categorical')

#create model
model = Sequential()

#add model layers
model.add((Conv2D
(64,(3,3), activation='relu', input_shape=(4892,4892,3))
))
model.add(MaxPooling2D(pool_size = (2, 2)))

model.add((Conv2D
(64, (3,3), activation='relu', input_shape=(4892,4892,3))
))
model.add(MaxPooling2D(pool_size = (2, 2)))

model.add((Conv2D
(64, (3,3), activation='relu', input_shape=(4892,4892,3))
))
model.add(MaxPooling2D(pool_size = (2, 2)))

model.add((Conv2D
(64, (3,3), activation='relu', input_shape=(4892,4892,3))
))
model.add(MaxPooling2D(pool_size = (2, 2)))

model.add((Conv2D
(128, (3,3), activation='relu', input_shape=(4892,4892,3))
))
model.add(MaxPooling2D(pool_size = (2, 2)))

model.add((Conv2D
(128, (3,3), activation='relu', input_shape=(4892,4892,3))
))
model.add(MaxPooling2D(pool_size = (2, 2)))

model.add((Conv2D
(128, (3,3), activation='relu', input_shape=(4892,4892,3))
))
model.add(MaxPooling2D(pool_size = (2, 2)))

model.add(Flatten())
model.add(Dense(activation = 'relu', units = 128))
model.add(Dense(activation = 'relu', units = 64))
model.add(Dense(1, activation='softmax'))

compiling model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

train model
model.fit(training_set,
batch_size=32,
epochs= 25,
validation_data= test_set)

**Comment by NevilShingala** [comment]
https://drive.google.com/drive/folders/1mSf0DbYrA07oWdz2Fwreh4EbAaKIOl5Z?usp=sharing

**Comment by tilakrayal** [comment]
@NevilShingala ,
Can you please take a look at this [SO link](https://stackoverflow.com/questions/46066850/understanding-the-resourceexhaustederror-oom-when-allocating-tensor-with-shape) and [issue](https://github.com/tensorflow/tensorflow/issues/16768) with the similar error.It helps.Thanks
