### ISSUE TITLE
Keras. Error when checking input

### ISSUE THREAD

**Issue by Anna8920** [keras-team/keras#16075]
Всем привет. Подскажите решение проблемы. Есть нейронка, которая распознает алфавитные буквы. Но при model.fit выдает ошибку: ValueError: Error when checking input: expected dense_1_input to have shape (33,) but got array with shape (1,)
`import os
import pandas as pd
import numpy as np

from keras.models import Sequential
from keras.layers import Conv2D, Dense, Embedding, MaxPooling2D, Flatten, Dropout
from keras.callbacks import ModelCheckpoint, EarlyStopping
from keras.optimizers import RMSprop

from sklearn.model_selection import train_test_split

import h5py

dataset = pd.read_csv("/media/anna/2b9d8a29-1113-48a8-a163-7ae3020ce40a/anna/Документы/АлфавитБот/Dataset/cyrillic.csv", index_col=0)
#print(dataset)

let = np.array(dataset)
#print(let)

feat = len(let)
#print(feat)

#print(len(dataset.index))

training_points = np.array(dataset)
training_labels = np.array(dataset)
#print(training_points.shape)

X_train = training_points.shape[1]
Y_train = training_labels.shape[1]
#print(X_train)

X = pd.DataFrame(dataset, columns = ["letter"])
y = pd.DataFrame(dataset, columns = ["label"])

train_X, test_X, train_y, test_y = train_test_split(training_points, training_labels, test_size = 0.25, random_state=50)
#print(train_y)

early_stop = EarlyStopping(monitor='val_acc', min_delta=0.001,
                           patience=3, verbose=1, mode='auto')
chkpt = ModelCheckpoint('/media/anna/2b9d8a29-1113-48a8-a163-7ae3020ce40a/anna/Документы/АлфавитБот/lstm.hdf5', 
                        monitor='val_loss', 
                        verbose=1, 
                        save_best_only=True, 
                        mode='auto')
callbacks = [early_stop, chkpt]

model = Sequential()

model.add(Dense(1024, input_dim=33, activation='relu'))
model.add(Dense(512, activation='relu'))

model.add(Dense(len(dataset), activation='softmax'))

model.compile(loss='sparse_categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

print('Model summary')
print(model.summary())

model.fit(training_points, training_labels, batch_size=500, epochs=50, shuffle=True, verbose=1, callbacks=callbacks)

model.save("/media/anna/2b9d8a29-1113-48a8-a163-7ae3020ce40a/anna/Документы/АлфавитБот/save_model_LSTM.h5")

print("Сохранение сети завершено")`
Как мне прописать здесь: model.fit(training_points, training_labels,...)?

**Comment by Anna8920** [comment]
> @ Anna8920 Анна8920 Чтобы воспроизвести описанную здесь проблему, не могли бы вы предоставить полный код и набор данных, версию tensorflow, которую вы используете. Спасибо!

Добавляю набор данных и код. Надеюсь Вы мне поможете

[cyrillic.csv](https://github.com/keras-team/keras/files/8087495/cyrillic.csv)

1. Обрабтка
`import pandas as pd
df = pd.DataFrame(columns=['letter', 'label'])

for letra in range(1,2):
    df = df.append({'letter': "А","label":1}, ignore_index=True)

for letra in range(1,2):
    df = df.append({'letter': "Б","label":2}, ignore_index=True)

for letra in range(1,2):
    df = df.append({'letter': "В","label":3}, ignore_index=True)

for letra in range(1,2):
    df = df.append({'letter': "Г","label":4}, ignore_index=True)

for letra in range(1,2):
    df = df.append({'letter': "Д","label":5}, ignore_index=True)

for letra in range(1,2):
    df = df.append({'letter': "Е","label":6}, ignore_index=True)

for letra in range(1,2):
    df = df.append({'letter': "Ё","label":7}, ignore_index=True)

for letra in range(1,2):
    df = df.append({'letter': "Ж","label":8}, ignore_index=True)

for letra in range(1,2):
    df = df.append({'letter': "З","label":9}, ignore_index=True)

for letra in range(1,2):
    df = df.append({'letter': "И","label":10}, ignore_index=True)

for letra in range(1,2):
    df = df.append({'letter': "Й","label":11}, ignore_index=True)

for letra in range(1,2):
    df = df.append({'letter': "К","label":12}, ignore_index=True)

for letra in range(1,2):
    df = df.append({'letter': "Л","label":13}, ignore_index=True)

for letra in range(1,2):
    df = df.append({'letter': "М","label":14}, ignore_index=True)

for letra in range(1,2):
    df = df.append({'letter': "Н","label":15}, ignore_index=True)

for letra in range(1,2):
    df = df.append({'letter': "О","label":16}, ignore_index=True)

for letra in range(1,2):
    df = df.append({'letter': "П","label":17}, ignore_index=True)

for letra in range(1,2):
    df = df.append({'letter': "Р","label":18}, ignore_index=True)
    
for letra in range(1,2):
    df = df.append({'letter': "С","label":19}, ignore_index=True)
    
for letra in range(1,2):
    df = df.append({'letter': "Т","label":20}, ignore_index=True)

for letra in range(1,2):
    df = df.append({'letter': "У","label":21}, ignore_index=True)

for letra in range(1,2):
    df = df.append({'letter': "Ф","label":22}, ignore_index=True)

for letra in range(1,2):
    df = df.append({'letter': "Х","label":23}, ignore_index=True)

for letra in range(1,2):
    df = df.append({'letter': "Ц","label":24}, ignore_index=True)

for letra in range(1,2):
    df = df.append({'letter': "Ч","label":25}, ignore_index=True)

for letra in range(1,2):
    df = df.append({'letter': "Ш","label":26}, ignore_index=True)

for letra in range(1,2):
    df = df.append({'letter': "Щ","label":27}, ignore_index=True)

for letra in range(1,2):
    df = df.append({'letter': "Ъ","label":28}, ignore_index=True)

for letra in range(1,2):
    df = df.append({'letter': "Ы","label":29}, ignore_index=True)

for letra in range(1,2):
    df = df.append({'letter': "Ь","label":30}, ignore_index=True)

for letra in range(1,2):
    df = df.append({'letter': "Э","label":31}, ignore_index=True)

for letra in range(1,2):
    df = df.append({'letter': "Ю","label":32}, ignore_index=True)

for letra in range(1,2):
    df = df.append({'letter': "Я","label":33}, ignore_index=True)

#print(df)

indice=df.index[-1]

df.to_csv('/media/anna/2b9d8a29-1113-48a8-a163-7ae3020ce40a/anna/Документы/АлфавитБот/Dataset/cyrillic.csv', index = False, header=True)
dataset=pd.read_csv("/media/anna/2b9d8a29-1113-48a8-a163-7ae3020ce40a/anna/Документы/АлфавитБот/Dataset/cyrillic.csv")`

2. Код
`import os
import pandas as pd
import numpy as np

из keras.models import Sequential
из keras.layers import Conv2D, Dense, Embedding, MaxPooling2D, Flatten, Dropout
из keras.callbacks import ModelCheckpoint, EarlyStopping
из keras.optimizers import RMSprop

из sklearn.model_selection импорта train_test_split

импортировать h5py

dataset = pd.read_csv("/media/anna/2b9d8a29-1113-48a8-a163-7ae3020ce40a/anna/Документы/АлфавитБот/Dataset/cyrillic.csv", index_col=0)
#print(dataset)

пусть = np.array(набор данных)
#print(пусть)

feat = len(let)
#print(feat)

#print(len(набор данных.индекс))

training_points = np.array (набор данных)
training_labels = np.array (набор данных)
#print (training_points.shape)

X_train = training_points.shape[1]
Y_train = training_labels.shape[1]
#print(X_train)

X = pd.DataFrame (набор данных, столбцы = ["буква"])
y = pd.DataFrame (набор данных, столбцы = ["метка"])

train_X, test_X, train_y, test_y = train_test_split (training_points, training_labels, test_size = 0,25, random_state = 50)
#print (train_y)

Early_stop = Ранняя остановка (монитор = 'val_acc', min_delta = 0,001,
терпение = 3, подробный = 1, режим = 'авто')
chkpt = ModelCheckpoint ('/media/anna/2b9d8a29-1113-48a8-a163-7ae3020ce40a/anna/ Документы/АлфавитБот/lstm.hdf5',
monitor='val_loss',
verbose=1,
save_best_only=True,
mode='auto')
callbacks = [early_stop, chkpt]

модель = Последовательный()

model.add (Dense (1024, input_dim = 33, активация = 'relu'))
model.add (Dense (512, активация = 'relu'))

model.add (Dense (len (набор данных), активация = 'softmax'))

model.compile (потеря = 'sparse_categorical_crossentropy',
оптимизатор = 'адам',
метрики = ['точность'])

print('Сводка модели')
print(model.summary())

model.fit(training_points, training_labels, batch_size=500, epochs=50, shuffle=True, verbose=1, callbacks=callbacks)

model.save("/media/anna/2b9d8a29-1113-48a8-a163-7ae3020ce40a/anna/Документы/АлфавитБот/save_model_LSTM.h5")

print("Сохранение сети завершено")`

**Comment by gadagashwini** [comment]
Closing as stale. Please reopen if you'd like to work on this further.
