### ISSUE TITLE
Does the ordering of values at the level of timesteps matter, for a RNN input in Keras?

### ISSUE THREAD

**Issue by IavTavares** [keras-team/keras#16097]
An RNN, in keras, accepts an input with the following shape

```
array([[['Xa0', 'Ya0'],
           ['Xa1', 'Ya1'],
           ['Xa2', 'Ya2']],

         [['Xb0', 'Yb0'],
          ['Xb1', 'Yb1'],
          ['Xb2', 'Yb2']],

        [['Xc0', 'Yc0'],
         ['Xc1', 'Yc1'],
         ['Xc2', 'Yc2']]], dtype='<U3')

```
The numbers are associated with the time steps (3 in our case), and X,Y are features. We have 3 batches (a,b,c).

Which order should I use:

 1. 0 -> 2 as in from past to present ?
 2. or  2 -> 0 as in from present to past?

```
array([[['Xa2', 'Ya2'],
           ['Xa1', 'Ya1'],
           ['Xa0', 'Ya0']],

         [['Xb2', 'Yb2'],
          ['Xb1', 'Yb1'],
          ['Xb0', 'Yb0']],

        [['Xc2', 'Yc2'],
         ['Xc1', 'Yc1'],
         ['Xc0', 'Yc0']]], dtype='<U3')

```

Nothing in the documentation tells me which is the order I should use

**Comment by chunduriv** [comment]
@IavTavares, In a RNN the information cycles through a loop. When it makes a decision, it considers the current input and also what it has learned from the inputs it received previously. This is important because the sequence of data contains crucial information about what is coming next.

For better understanding, please can you refer this [RNN tutorial](https://www.simplilearn.com/tutorials/deep-learning-tutorial/rnn). Thanks!

**Comment by IavTavares** [comment]
Yes, I get that, but the documentation does not explicitly state which order one should use... That's the problem.

**Comment by chunduriv** [comment]
@IavTavares, Can you please share documentation link that you are referring here? Thanks!

**Comment by IavTavares** [comment]
If I say that the documentation on Keras has no information on which order one should use, it's hard to share a link of what does not exist. Em 22/02/2022 12:11, chunduriv ***@***.***> escreveu:
@IavTavares, Can you please share documentation link that you are referring here? Thanks!

**Comment by IavTavares** [comment]
For time series analysis, from the examples, we should just use the order from past to present...

**Comment by chunduriv** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
