### ISSUE TITLE
tensorflow.keras.utils.plot_model not working correctly with show_shapes=True

### ISSUE THREAD

**Issue by RicardFos** [keras-team/keras#16090]
Hi, I've just used the tf.keras.utils.plot_model with tensorflow 2.8.0 and the following diagram appeared:
![image](https://user-images.githubusercontent.com/11573780/154634034-8863e81e-be61-42fb-a6b5-d13f8255bf51.png)

As you can see, the right part of the diagram shows the input and output shapes with a vertical split, but it should be an horizontal split to fit with the "intput:" and  "output:" cells at its left.

**Comment by RicardFos** [comment]
Hi, I could work on it, no problem.

**Comment by mattdangerw** [comment]
Assigning this to you @RicardFos as it looks like you are actively working on this and the conversation has moved to the PR https://github.com/keras-team/keras/pull/16096. Thanks for contributing!

**Comment by jvishnuvardhan** [comment]
@RicardFos This was resolved in recent `tf-nightly` by your PR as it got merged. [Here](https://colab.research.google.com/gist/jvishnuvardhan/a00d1fea601fefae2835d87a8fb84ed2/untitled234.ipynb) is a gist for reference. 

Please verify once and close the issue if this was resolved for you. Thanks!

**Comment by RicardFos** [comment]
Thanks, I've checked the notebook and it works correctly, I'll mark this issue as resolved.
