### ISSUE TITLE
AttributeError: module 'tensorflow_core.keras' has no attribute 'Seqential'

### ISSUE THREAD

**Issue by wangshan1997** [keras-team/keras#16106]
D:\anaconda\python.exe E:/test/hand/have_train.py
(60000, 28, 28) (60000, 10)
Traceback (most recent call last):
  File "E:/test/hand/have_train.py", line 19, in <module>
    model=keras.Seqential([
  File "D:\anaconda\lib\site-packages\tensorflow\__init__.py", line 51, in __getattr__
    return getattr(module, item)
AttributeError: module 'tensorflow_core.keras' has no attribute 'Seqential'

**Comment by sushreebarsa** [comment]
@wangshan1997 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by AdityaKane2001** [comment]
@wangshan1997 

I believe it is `tf.keras.Sequential` and not the one you mentioned. Please check your spelling.

**Comment by sushreebarsa** [comment]
@wangshan1997 Could you please update as per the [comment](https://github.com/keras-team/keras/issues/16106#issuecomment-1051560823) above ?Thanks!
