### ISSUE TITLE
An op outside of the function building code is being passed a "Graph" tensor

### ISSUE THREAD

**Issue by pnuzyf** [keras-team/keras#16107]
I am using tf 2.3.0, and did not explicitly set the eager mode。

I defined a memory network layer, and call it from another layer。 It succeeded during the training step. However, I got the following error during the evaluation step。

Traceback (most recent call last):
File "/Users/fabriszhou/PycharmProjects/tf-model/test/msmt/test_memory.py", line 94, in
mymodel = model.get_train_model()
File "/Users/fabriszhou/PycharmProjects/tf-model/models/msmt.py", line 374, in get_train_model
long_cluster = self.memory.predict_process([query_emb, long_emb, isActive_vals]) # 拿到长期的兴趣表征
File "/Users/fabriszhou/PycharmProjects/tf-model/pkgs/tf/extend_layers.py", line 2499, in predict_process
read_attention = compute_cosine_similarity(read_query, self.key_memory, temperature=self.temperature)
File "/Users/fabriszhou/PycharmProjects/tf-model/pkgs/tf/extend_layers.py", line 2322, in compute_cosine_similarity
normed_memory = tf.nn.l2_normalize(memory, axis=1) # [n_memory, dim]
File "/opt/anaconda3/envs/tf23/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
return target(*args, **kwargs)
File "/opt/anaconda3/envs/tf23/lib/python3.7/site-packages/tensorflow/python/ops/nn_impl.py", line 666, in l2_normalize_v2
square_sum = math_ops.reduce_sum(math_ops.square(x), axis, keepdims=True)
File "/opt/anaconda3/envs/tf23/lib/python3.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 10309, in square
x, name=name, ctx=_ctx)
File "/opt/anaconda3/envs/tf23/lib/python3.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 10347, in square_eager_fallback
ctx=ctx, name=name)
File "/opt/anaconda3/envs/tf23/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 75, in quick_execute
raise e
File "/opt/anaconda3/envs/tf23/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
inputs, attrs, num_outputs)
TypeError: An op outside of the function building code is being passed
a "Graph" tensor. It is possible to have Graph tensors
leak out of the function building context by including a
tf.init_scope in your function building code.
For example, the following function will fail:
@tf.function
def has_init_scope():
my_constant = tf.constant(1.)
with tf.init_scope():
added = my_constant * 2
The graph tensor has name: add:0

you can clone the source code from https://github.com/pnuzyf/tf-model.git, the test code locates in test/msmt/test_memory.py. n test_memory.py, you should change the argument of custom_layer_file_path， and the correponding config_file, export_path, pack_path and data_path etc.

model = MsMtModel(input, num_scenarios, moe_num_experts, moe_expert_layers, ordered_task_names, layer_number, ple_dict, tower_dict, task_output_act,
tower_dependencies_dict={},
custom_layer_file_path="/Users/fabriszhou/PycharmProjects/tf-model/test/msmt/custom/custom_layers.py", is_parallel=False, short_cut=True,
cut_tower=cut_tower_dict, is_memory=True, controller_layers=controller_layers, controller_output_act=controller_output_act, key_dims=key_dims,
long_dims=long_dims,
name='msmt')

**Comment by pnuzyf** [comment]
When I add MemoryLayer to Msmt， I got the above error, without MemoryLayer, it's ok.

**Comment by pnuzyf** [comment]
model.compile(..., run_eagerly=True, ...) also can not work.

**Comment by sushreebarsa** [comment]
@pnuzyf We see that you are using older version of TF which is not actively supported.Please try to upgrade the version to latest  and let us know the outcome. Please refer the similar [issue1](https://stackoverflow.com/questions/58565913/typeerror-an-op-outside-of-the-function-building-code-is-being-passed-a-graph-t),[issue2](https://github.com/tensorflow/tensorflow/issues/32889) and let us know if it helps?Thanks!

**Comment by pnuzyf** [comment]
I can successfully train the model, but can not evaluate.

**Comment by pnuzyf** [comment]
class MemoryLayer(tf.keras.layers.Layer):
    def __init__(self, controller_layers, controller_hidden_act='relu', controller_output_act=None, n_clusters=100, key_dims=8, long_dims=8, short_dims=8, temperature=0.1, alpha=0.1, is_short=False, name="memory_layer", **kwargs):
        super(MemoryLayer, self).__init__(name=name, trainable=True, **kwargs)
        self.controller_layers = controller_layers
        self.controller_hidden_act = controller_hidden_act
        self.controller_output_act = controller_output_act
        self.n_clusters = n_clusters
        self.key_dims = key_dims
        self.long_dims = long_dims
        self.short_dims = short_dims
        self.temperature = temperature
        self.alpha = alpha
        self.is_short = is_short

        self.key_memory = self.add_weight(f"{self.name}_key_memory",
                              shape=(self.n_clusters, self.key_dims),
                              initializer=tf.keras.initializers.GlorotNormal(),
                              trainable=False)


        self.long_memory = self.add_weight(f"{self.name}_long_memory",
                              shape=(self.n_clusters, self.long_dims),
                              initializer=tf.keras.initializers.GlorotNormal(),
                              trainable=False)

        if is_short:
            self.short_memory =  self.add_weight(f"{self.name}_short_memory",
                              shape=(self.n_clusters, self.long_dims),
                              initializer=tf.keras.initializers.GlorotNormal(),
                              trainable=False)

            self.short_erase_layer = DNNLayer([self.short_dims], 'sigmoid',
                                             name=f"{self.name}_short_erase_layer")  # short的删除层
            self.short_add_layer = DNNLayer([self.short_dims], 'tanh', name=f"{self.name}_short_add_layer")  #short的更新层

        self.write_controller = DNNLayer(controller_layers, controller_hidden_act, controller_output_act) #write控制器

        self.read_controller = DNNLayer(controller_layers, controller_hidden_act, controller_output_act) #read控制器

        self.key_erase_layer = DNNLayer([self.key_dims], 'sigmoid', name=f"{self.name}_key_erase_layer") #key的删除层
        self.key_add_layer = DNNLayer([self.key_dims], 'tanh', name=f"{self.name}_key_add_layer") #key的更新层

        self.long_erase_layer = DNNLayer([self.long_dims], 'sigmoid', name=f"{self.name}_long_erase_layer")  #long的删除层
        self.long_add_layer = DNNLayer([self.long_dims], 'tanh', name=f"{self.name}_long_add_layer")  # long的更新层

    @tf.function
    def call(self, inputs, training=None, **kwargs):
        attr_emb = inputs[0]  # [batch_size, attr_emb]
        long_emb = inputs[1] #[batch, long_dims] 长期兴趣表征
        isActive = inputs[2]  # [batch_size, 1] 是否需要更新long、short memory

        active_status = tf.cast(tf.transpose(isActive, perm=[1,0]), dtype='float32')

        denominator = tf.math.count_nonzero(isActive) #统计非0的个数

        #＞0才更新
        if denominator > 0 and training:
            #write memory
            #[batch_size, key_dims]
            write_query = self.write_controller(tf.stop_gradient(attr_emb)) #获取写控制器的表征

            #[batch, n_clusters]
            write_attention = compute_cosine_similarity(write_query, self.key_memory, temperature=self.temperature)
            #
            # #[1, n_clusters]
            write_memory_attention = tf.matmul(active_status, write_attention) / tf.cast(denominator, dtype=tf.float32)

            #[n_clusters, 1]
            write_memory_attention = tf.transpose(write_memory_attention, perm=[1, 0])

            #write key memory
            key_erase_vector = self.key_erase_layer(write_query) #[batch, key_dims]
            key_erase_vector = tf.matmul(active_status, key_erase_vector) / tf.cast(denominator, dtype=tf.float32) #[1,key_dims]
            #
            key_add_vector = self.key_add_layer(write_query) #[batch, key_dims]
            key_add_vector = tf.matmul(active_status, key_add_vector) / tf.cast(denominator, dtype=tf.float32)  # [1,key_dims]

            self.key_memory = tf.stop_gradient(self.key_memory) \
                              * (1. - self.alpha * tf.matmul(write_memory_attention, key_erase_vector)) \
                              * + self.alpha * tf.matmul(write_memory_attention, key_add_vector)

            #write long_memory
            long_erase_vector = self.long_erase_layer(long_emb)  # [batch, long_dims]
            long_erase_vector = tf.matmul(active_status, long_erase_vector) / tf.cast(denominator, dtype=tf.float32)  # [1,long_dims]
            #
            long_add_vector = self.long_add_layer(long_emb)  # [batch, long_dims]
            long_add_vector = tf.matmul(active_status, long_add_vector) / tf.cast(denominator, dtype=tf.float32)  # [1,long_dims]

            self.long_memory = tf.stop_gradient(self.long_memory) \
                              * (1. - self.alpha * tf.matmul(write_memory_attention, long_erase_vector)) \
                              + self.alpha * tf.matmul(write_memory_attention, long_add_vector)

        #read memory
        #[batch, key_dims]
        read_query = self.read_controller(tf.stop_gradient(attr_emb))

         #[batch, n_clusters]
        read_attention = compute_cosine_similarity(read_query, self.key_memory, temperature=self.temperature)

        # read_attention = self.read_sim_layer([read_query, self.key_memory], temperature=self.temperature)

        long_cluster_emb = tf.matmul(read_attention, self.long_memory) #[batch, long_dims] 长期兴趣表征

        return long_cluster_emb

it seems that the error is due to the key_memory, since key_memory is updated through forward path, and the tensor name is changed.

**Comment by pnuzyf** [comment]
I found the problem due to the reassignment of self.key_memory and self.long_memory. If I change it to self.long_memory.assign, then it can work. but nor grandents for read_controller and write_controller

**Comment by sushreebarsa** [comment]
@pnuzyf I tried to replicate the issue on colab using TF v2.8.0 .  Could you please have a look at the [gist](https://colab.research.google.com/gist/sushreebarsa/8d66c74c9c8b12a2efef40fcf3c263a7/16057.ipynb) and confirm the same?
Thanks!

**Comment by sushreebarsa** [comment]
@pnuzyf 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by pnuzyf** [comment]
hello， I believe I have solved this problem. 

 long_val = self.long_memory \
                        * (1. - self.alpha * tf.matmul(write_memory_attention, long_erase_vector)) \
                        + self.alpha * tf.matmul(write_memory_attention, long_add_vector)


            long_update_op = self.long_memory.assign(long_val)

            tf.compat.v1.add_to_collections(tf.compat.v1.GraphKeys.UPDATE_OPS, long_update_op)

**Comment by sushreebarsa** [comment]
@pnuzyf Thank you for the quick update!
Could you please move this issue to closed status as if it is resolved for you ?Thanks!
