### ISSUE TITLE
EfficientNetV2 does not match google implementation

### ISSUE THREAD

**Issue by SergioG-M** [keras-team/keras#16144]
Hi,
I may be wrong, but checking the efficientnetv2 implementation I think there is a difference with the [google one](https://github.com/google/automl/blob/387d5ddb92bb8fbbec4b012e5636a81ea65fffda/efficientnetv2/effnetv2_model.py)
The  ["survival_probability"](https://github.com/keras-team/keras/blob/d8fcb9d4d4dad45080ecfdd575483653028f8eda/keras/applications/efficientnet_v2.py#L990) is defined as `survival_probability=drop_connect_rate * b / blocks` but b is set to zero, while according to the [google implementation](https://github.com/google/automl/blob/387d5ddb92bb8fbbec4b012e5636a81ea65fffda/efficientnetv2/effnetv2_model.py#L619) it should increase with the "number" of the block.

I think that line should be replaced with:
`survival_probability=drop_connect_rate * i / blocks` 
where i is the counter of the for loop

**Comment by innat** [comment]
cc. @sebastian-sz

**Comment by sebastian-sz** [comment]
thanks for cc @innat.

Yes, I think you are correct @SergioG-M. 
I mostly followed the Efficientnet V1 implementation, which indeed increases block size in the [end of the loop](https://github.com/keras-team/keras/blob/d8fcb9d4d4dad45080ecfdd575483653028f8eda/keras/applications/efficientnet.py#L360) and it looks like i missed this step.

Without it, the value of `drop_connect_rate * b / blocks` is always 0.0.
>I think that line should be replaced with:
survival_probability=drop_connect_rate * i / blocks
where i is the counter of the for loop

One can also, similar to Efficientnet V1 implementation, add `b+=1` in line 995 of `efficientnet_v2.py`.

I can submit the PR with the fix, unless you want to do it? Please, let me know.

**Comment by SergioG-M** [comment]
> I don't think this will work, as b is increased also in the second for loop, as opposed to i, which increases only when second for loop finishes.

You're right, I was following the google implementation, but their blocks already include the second for loop in the keras one, so it should be` b += 1`

Go ahead with the PR please.
