### ISSUE TITLE
Add a decorator for plotting a subclassed model (based on plot_model)

### ISSUE THREAD

**Issue by Meidozuki** [keras-team/keras#16142]
**System information**.

TensorFlow version (you are using): 2.6
Are you willing to contribute it (Yes/No) : Yes

**Describe the feature and the current behavior/state**.

I tested `tf.keras.utils.plot_model` in tf 2.6 and 2.8, to find `plot_model`  cannot directly plot a subclassed model. I've tried several ideas, and this one requires minimal code to change.

**Will this change the current api? How?**
It will add a decorator function to `keras/utils/vis_utils.py`, which is like a wrapper and will call `plot_model` to do the work.

**Who will benefit from this feature?**
`plot_model` support functional model so usually we can do below to plot a subclassed model.

Here is a method on StackOverflow, which I used to use:  
```
class Model(tf.keras.Model):
    def plot(self,input_shape):
        x=layers.Input(input_shape)
        y=self.call(x)
        model=tf.keras.Model(inputs=x,outputs=y)
        return tf.keras.utils.plot_model(model,show_shapes=True)
```
But everytime I want to plot a new model, I need to copy this `plot` function and manually change the input_shape. I considered to derive a plotable class who completes the `plot` function, but it still can't avoid manually changing the input_shape. (Oh yes, I am lazy.)
So I want to find a Don't-Repeat-Youtself way to do so.
My idea is to add a decorator on `build` function (I'll show my code below). It just catched the input_shape of `build`, and all the work is still done by `Model.build` and `plot_model`. 
```
@plotable()
    def build(self,input_shape):
        super().build(input_shape)
```

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**

- Do you want to contribute a PR? (yes/no): yes
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing):  

Here is my [sample](https://github.com/Meidozuki/light-keras-plot/blob/main/Usage.ipynb).
 
Below are the codes.  

```
def plot_subclass_model(silent=False,show_shapes=True,**kwargs):
    '''
    This is a supplementary decorator to plot a subclassed model.
    Decorate it on Model.build to call `tf.keras.utils.plot_model`.
    Example:
    
    ```python
    class MyModel(tf.keras.Model):
    
      def __init__(self):
        super().__init__()
        self.dense = tf.keras.layers.Dense(4, activation=tf.nn.relu)
    
      def call(self, inputs):
        return self.dense(inputs)
        
      @plot_subclass_model()
      def build(self,input_shape):
        super().build(input_shape)
        
    model=MyModel()
    model.build((None,32,32,3))
    ```
    
    Args:
      silent: Whether to plot the model. If set to True, it will do nothing other than the `build` function. Default is False.
      kwargs: Args passed to `plot_model`. Arg `show_shapes` will pass True by default. See more in `tf.keras.utils.plot_model`.
    '''
    from functools import wraps
    
    kwargs['show_shapes']='show_shapes'
    
    def decorate(func):
        @wraps(func)
        def wrapper(self,input_shape):
            result=func(self,input_shape)

            if not silent:
                from tensorflow.keras import layers
                if isinstance(input_shape,(tuple,tf.TensorShape)):
                    inputs=layers.Input(input_shape[1:])
                elif isinstance(input_shape,list):
                    inputs=[layers.Input(s[1:]) for s in input_shape]
                else:
                    raise ValueError(f'Expect input_shape to be a shape or a list of shape, but received {type(input_shape)}')

                outputs=self.call(inputs)
                model=tf.keras.Model(inputs=inputs,outputs=outputs)
                plot_result=tf.keras.utils.plot_model(model,**kwargs)
                try:
                    from IPython.display import display
                    display(plot_result)
                except ImportError:
                    pass
            return result
        return wrapper
    return decorate
```

**Comment by zrx563010758** [comment]
unsubscribe




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "keras-team/keras"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月1日(星期二) 下午3:31
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[keras-team/keras] A decorator for plotting a subclassed model (based on plot_model) (Issue #16142)





 
System information.
 
TensorFlow version (you are using): 2.6
 Are you willing to contribute it (Yes/No) : Yes
 
Describe the feature and the current behavior/state.
 
I tested tf.keras.utils.plot_model in tf 2.6 and 2.8, to find plot_model  cannot directly plot a subclassed model. I've tried several ideas, and this one requires minimal code to change.
 
Will this change the current api? How?
 It will add a decorator function to keras/utils/vis_utils.py, which is like a wrapper and will call plot_model to do the work.
 
Who will benefit from this feature?
 plot_model support functional model so usually we can do below to plot a subclassed model
 class Model(tf.keras.Model):     def plot(self,input_shape):         x=layers.Input(input_shape)         y=self.call(x)         model=tf.keras.Model(inputs=x,outputs=y)         return tf.keras.utils.plot_model(model,show_shapes=True)  
But everytime I want to plot a new model, I need to copy this plot function and mannually change the input_shape. I considered to derive a plotable class who completes the plot function, but it still can't avoid mannually changing the input_shape. (Oh yes, I am lazy.)
 So I want to find a Don't-Repeat-Youtself way to do so.
 My idea is to add a decorator on build function (I'll show my code below). It just catched the input_shape of build, and all the work is still done by Model.build and plot_model.
 @plotable()     def build(self,input_shape):         super().build(input_shape)  
Contributing
  
Do you want to contribute a PR? (yes/no): yes
 
If yes, please read this page for instructions
 
Briefly describe your candidate solution(if contributing):
  
Here is my sample.
 
Below are all the code, and I'll update it soon following the keras_api_design_guidelines .
 def plotable(silent=False):     '''     Used on model.build to call tf.keras.utils.plot_model     '''     from functools import wraps     def decorate(func):         @wraps(func)         def wrapper(self,input_shape):             result=func(self,input_shape)             if not silent:                 from tensorflow.keras import layers                 from IPython.display import display                 if isinstance(input_shape,(tuple,tf.TensorShape)):                     inputs=layers.Input(input_shape[1:])                 elif isinstance(input_shape,list):                     inputs=[layers.Input(s[1:]) for s in input_shape]                 else:                     raise AssertionError                 outputs=self.call(inputs)                 model=tf.keras.Model(inputs=inputs,outputs=outputs)                 display(tf.keras.utils.plot_model(model,show_shapes=True))             return result         return wrapper     return decorate  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chenmoneygithub** [comment]
Hi Meidozuki, thanks for reporting the issue and being willing to contribute! 

We do not have general approach for plotting the subclassed model by intention, because subclassed model might contain customized layer and special structure that is hard to plot. The approach you are proposing is aligned with Functional model, which is a chain of Keras layers.

**Comment by Meidozuki** [comment]
OK, I see. I did meet  a case that a subclass has its own variables and cannot be plotted. 
Thanks for reviewing.
