### ISSUE TITLE
Segmentation Fault (core dumped) Issue

### ISSUE THREAD

**Issue by peter-jp** [keras-team/keras#16150]
**System information**

I have written custom code
OS Platform and Distribution: CentOS Linux release 7.7.1908 (AltArch), Power9 PC with 4 GPU nodes, 1 login node and 1 compute node and it has little endian architecture
TensorFlow installed from (source or binary): https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/
TensorFlow version (use command below): 2.1.3 (tensorflow-gpu) - This is the latest available version from the above channel for ppcle64 architecture.
Python version:3.6.13
Bazel version (if compiling from source):
python compiler version: GCC 7.3.0
CUDA/cuDNN version:10.2
GPU model and memory: NVIDIA Tesla V100, Total memory: 379140608 kB =379.140608 GB (in one of the node)

Are you willing to contribute it (Yes/No) : Yes

I use Supercomputer at our organization for training. I am facing the Segmentation Fault (core dumped) Issue, when I attempt to train a CNN model. The model gets trained for a smaller number of Epochs. Eg if epochs=50 the model runs fine and outputs the trained model file (using callbacks in model.fit). But when epochs are increased, to 75 then segmentation fault occurs at 54th epoch for the same dataset. I ran .py file by submitting it as a job through slurm script. Dataset size is 80,000*5600, around 9GB.

**code**
```
import os
import os.path
import sys

import h5py
import numpy as np
import tensorflow as tf
from tensorflow import keras

def load_file(database_file, load_data=False):
    in_file  = h5py.File(database_file, "r")
    X_train = np.array(in_file['training/data'],dtype=np.int8)
    Y_train = np.array(in_file['training/label'])
    X_test = np.array(in_file['testing/data'], dtype=np.int8)
    Y_test = np.array(in_file['testing/label'])
    if load_data == False:
        return (X_train, Y_train), (X_test, Y_test)
    else:
        return (X_train, Y_train), (X_test, Y_test), (in_file['train/data'], in_file['test/data'])

database = "/home/..../dataset.h5"
trained_model = "/home..../trained_epoch_test.h5"
  
(X_train, Y_train), (X_test, Y_test) = load_file(database_file)

X_train_scaled = X_train.reshape((X_train.shape[0], X_train.shape[1], 1))
X_test_scaled = X_test.reshape((X_test.shape[0], X_test.shape[1], 1))

y_train_categorical = keras.utils.to_categorical(Y_train, num_classes=256)
y_test_categorical    = keras.utils.to_categorical(Y_test, num_classes=256)

batch_size = 300 
epochs = 100
   
classes=256
input_shape = (5600,1)     
img_input = keras.layers.Input(shape=input_shape)

x = keras.layers.Conv1D(64, 11, activation='relu', padding='same', name='block1_conv1')(img_input)
x = keras.layers.AveragePooling1D(2, strides=2, name='block1_pool')(x)

x = keras.layers.Conv1D(128, 11, activation='relu', padding='same', name='block2_conv1')(x)
x = keras.layers.AveragePooling1D(2, strides=2, name='block2_pool')(x)

x = keras.layers.Conv1D(256, 11, activation='relu', padding='same', name='block3_conv1')(x)
x = keras.layers.AveragePooling1D(2, strides=2, name='block3_pool')(x)

x = keras.layers.Conv1D(512, 11, activation='relu', padding='same', name='block4_conv1')(x)
x = keras.layers.AveragePooling1D(2, strides=2, name='block4_pool')(x)

x = keras.layers.Conv1D(512, 11, activation='relu', padding='same', name='block5_conv1')(x)
x = keras.layers.AveragePooling1D(2, strides=2, name='block5_pool')(x)

x = keras.layers.Flatten(name='flatten')(x)
x = keras.layers.Dense(4096, activation='relu', name='fc1')(x)
x = keras.layers.Dense(4096, activation='relu', name='fc2')(x)
x = keras.layers.Dense(classes, activation='softmax', name='predictions')(x)
  
model = keras.models.Model(img_input, x, name='cnn_best')
optimizer = keras.optimizers.RMSprop(lr=0.00001)
model.compile(loss='categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])
    
save_model = keras.callbacks.ModelCheckpoint(trained_model)
callbacks=[save_model]
    
model.fit(x=X_train_scaled, y=y_train_categorical, batch_size=batch_size, verbose = 1, epochs=epochs, callbacks=callbacks)
```

**Following is the logs generated after enabling fault handler() function:**
![fault handler](https://user-images.githubusercontent.com/70361953/156314035-be4fa6a6-fd73-4823-804c-f4400cac239f.png)

**Slurm Script used to submit the job**
#!/bin/bash
#SBATCH --partition=GPU_three
#SBATCH --nodelist=Node_03
#SBATCH --output=output
python3 train.py

(I followed https://github.com/keras-team/keras/issues/14473 for importing Keras from Tensorflow, though segmentation fault persists)

FYI: Meanwhile, I used Tensorflow Mirrored strategy within one GPU, but that also resulted in segmentation fault after some more epochs than normal implementation.

**Comment by tilakrayal** [comment]
@peter-jp ,
I am facing different error while executing the given code.Please find the gist [here](https://colab.research.google.com/gist/tilakrayal/a457e41c559c89809957d56c75ac6ddb/16150.ipynb).

**Comment by peter-jp** [comment]
Actually, It points to the dataset location.

**Comment by tilakrayal** [comment]
@peter-jp ,
In order to expedite the trouble-shooting process, could you please provide a complete code and the dataset you are using.

**Comment by peter-jp** [comment]
yes

**Comment by tilakrayal** [comment]
@peter-jp ,
In order to expedite the trouble-shooting process, could you please provide a complete code and the dataset you are using.Also please try to test the code in latest stable version2.8  and let us know if you are facing same issue.Thanks!
