### ISSUE TITLE
Installing specific Keras Version in Colab works strange

### ISSUE THREAD

**Issue by BanzerUniKL** [keras-team/keras#16167]
Hey,

for a project I need Keras Vers. 2.2.5. I'm running it on Google Colab. My Code is

```
%tensorflow_version 1.x
!pip install h5py==2.10.0
!pip install q keras==2.2.5
```

strangely it installs (according to the last line) Keras 2.8.0.

`
TensorFlow 1.x selected.
Collecting h5py==2.10.0
  Downloading h5py-2.10.0-cp37-cp37m-manylinux1_x86_64.whl (2.9 MB)
     |████████████████████████████████| 2.9 MB 5.0 MB/s 
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from h5py==2.10.0) (1.15.0)
Requirement already satisfied: numpy>=1.7 in /usr/local/lib/python3.7/dist-packages (from h5py==2.10.0) (1.21.5)
Installing collected packages: h5py
  Attempting uninstall: h5py
    Found existing installation: h5py 3.1.0
    Uninstalling h5py-3.1.0:
      Successfully uninstalled h5py-3.1.0
Successfully installed h5py-2.10.0
Collecting q
  Downloading q-2.6-py2.py3-none-any.whl (6.8 kB)
Collecting keras==2.2.5
  Downloading Keras-2.2.5-py2.py3-none-any.whl (336 kB)
     |████████████████████████████████| 336 kB 5.1 MB/s 
Requirement already satisfied: numpy>=1.9.1 in /usr/local/lib/python3.7/dist-packages (from keras==2.2.5) (1.21.5)
Requirement already satisfied: keras-applications>=1.0.8 in /tensorflow-1.15.2/python3.7 (from keras==2.2.5) (1.0.8)
Requirement already satisfied: keras-preprocessing>=1.1.0 in /usr/local/lib/python3.7/dist-packages (from keras==2.2.5) (1.1.2)
Requirement already satisfied: scipy>=0.14 in /usr/local/lib/python3.7/dist-packages (from keras==2.2.5) (1.4.1)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.7/dist-packages (from keras==2.2.5) (1.15.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.7/dist-packages (from keras==2.2.5) (3.13)
Requirement already satisfied: h5py in /usr/local/lib/python3.7/dist-packages (from keras==2.2.5) (2.10.0)
Installing collected packages: q, keras
  Attempting uninstall: keras
    Found existing installation: Keras 2.3.1
    Uninstalling Keras-2.3.1:
      Successfully uninstalled Keras-2.3.1
Successfully installed keras-2.8.0 q-2.6`

If I run the same cell again without changing anything it installs the right version
`Requirement already satisfied: h5py==2.10.0 in /usr/local/lib/python3.7/dist-packages (2.10.0)
Requirement already satisfied: numpy>=1.7 in /usr/local/lib/python3.7/dist-packages (from h5py==2.10.0) (1.21.5)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from h5py==2.10.0) (1.15.0)
Requirement already satisfied: q in /usr/local/lib/python3.7/dist-packages (2.6)
Collecting keras==2.2.5
  Using cached Keras-2.2.5-py2.py3-none-any.whl (336 kB)
Requirement already satisfied: scipy>=0.14 in /usr/local/lib/python3.7/dist-packages (from keras==2.2.5) (1.4.1)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.7/dist-packages (from keras==2.2.5) (1.15.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.7/dist-packages (from keras==2.2.5) (2.10.0)
Requirement already satisfied: keras-preprocessing>=1.1.0 in /usr/local/lib/python3.7/dist-packages (from keras==2.2.5) (1.1.2)
Requirement already satisfied: keras-applications>=1.0.8 in /tensorflow-1.15.2/python3.7 (from keras==2.2.5) (1.0.8)
Requirement already satisfied: numpy>=1.9.1 in /usr/local/lib/python3.7/dist-packages (from keras==2.2.5) (1.21.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.7/dist-packages (from keras==2.2.5) (3.13)
Installing collected packages: keras
  Attempting uninstall: keras
    Found existing installation: keras 2.8.0
    Uninstalling keras-2.8.0:
      Successfully uninstalled keras-2.8.0
Successfully installed keras-2.2.5`

How is that possible? How can I avoid having to click the cell twice?

Thanks in advance

**Comment by sushreebarsa** [comment]
@BanzerUniKL Could you please have a look on this [gist](https://colab.research.google.com/gist/sushreebarsa/462bc06c1707fc329118ebbe5d37a08e/16167.ipynb) and let us know if it helps?Thanks!

**Comment by BanzerUniKL** [comment]
hey, yeah, that helps. unfortunally i forgot to say that i need tensorflow ver. 1.x . So it is  a tensorflow-issue

**Comment by sushreebarsa** [comment]
@BanzerUniKL Thank you for the update!
`TF version 1.x` is not actively supported, for any further queries you may open this issue in tf discussion [forum](https://discuss.tensorflow.org/) as there is a larger community there. Thanks!
