### ISSUE TITLE
Why here use "caffe" but not "tf"?

### ISSUE THREAD

**Issue by Zhaopudark** [keras-team/keras#16179]
https://github.com/keras-team/keras/blob/d8fcb9d4d4dad45080ecfdd575483653028f8eda/keras/applications/vgg19.py#L237

I'm using `tf.keras.applications.vgg19.VGG19` for transfer leraning, following the guides in tf docs and using `tf.keras.applications.vgg19.preprocess_input` to deal with inputs. But I'm very confused with the above source code, i.e., why here set mode as "caffee" but not "tf"?

**Comment by chunduriv** [comment]
@Zhaopudark,

Here mode `caffe`: will convert the images from `RGB` to `BGR`, then will zero-center each color channel with respect to the ImageNet dataset, without scaling 

Where as  mode `tf` will scale pixels between `-1` and `1`, sample-wise.

**Comment by Zhaopudark** [comment]
@chunduriv Thank you! 
I think this answer eliminate my confusion very well in detail.
