### ISSUE TITLE
Bug in saving keras models when a customized decorated loss function is used

### ISSUE THREAD

**Issue by saddamhijazi** [keras-team/keras#16180]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): **Yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.6 **LTS**
- TensorFlow installed from (source or binary): **source**
- TensorFlow version (use command below): **2.7**
- Python version:  **Python 3.8.12**

**Describe the problem**.

The problem happens when I try to run a Keras model on TensorFlow 2.7 with a customized loss function which is decorated with @tf.function in order to keep the graph flow ( I use some other packages which requires that). When I try to save the model after running it using the 'tf' saving format I get the following error 

`
KeyError: "Failed to add concrete function 'b'__inference_custom_loss_202116'' to object-based SavedModel as it captures tensor <tf.Tensor: shape=(), dtype=resource, value=<Resource Tensor>> which is unsupported or not reachable from root. One reason could be that a stateful object or a variable that the function depends on is not assigned to an attribute of the serialized trackable object (see SaveTest.test_captures_unreachable_variable)."
`
This error does not happen when I don't decorate the customized loss function with @tf.function. I would like to understand how one could save the model in a tf format for later load and use.

I write here a minimal example for reproducing the issue 

```
import sys
import os.path
import tensorflow as tf
import numpy as np
import time
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Layer, Activation, Dense
from tensorflow.keras.optimizers import Adam

np.random.seed(1234)
tf.random.set_seed(1234)

      

x = tf.linspace([0.0], [10.0], 1001) 
y = x**3 - 5 * x**2


inputs = tf.keras.Input(shape=(1,),dtype='float32')
layer1 = Dense(units=32, activation='tanh',dtype='float32')(inputs)
layer2 = Dense(units=32, activation='tanh',dtype='float32')(layer1)
layer3 = Dense(units=32, activation='tanh',dtype='float32')(layer2)
predictions = Dense(units=1, activation='linear',dtype='float32')(layer3)
model = tf.keras.Model(inputs=inputs, outputs=predictions)
model.summary()

x0 = tf.Variable([[0.0]], shape=[1,1])




@tf.function 
# # Define custom loss
def custom_loss(y_true,y_pred):
    
    y0 = model(x0, training=True)
    pred = model(x, training=True)

   
    # compute the time derivative of a 
    aDot = tf.gradients(pred, x)[0]

    # compute the batch values of f
    f = aDot - 3 * x**2 + 10 * x

    
    tf.print("\n IC Loss is : ", tf.reduce_mean(tf.square(y0)), output_stream=sys.stdout)
    tf.print("\n F Loss is : ", tf.reduce_mean(tf.square(f)), output_stream=sys.stdout)

    loss = tf.reduce_mean(tf.square(y0)) + tf.reduce_mean(tf.square(f))

    # Return a function
    return loss


optimizerAdam = keras.optimizers.Adam(learning_rate=1e-3)

# Compile the model
model.compile(optimizer=optimizerAdam ,
              loss=custom_loss,
              # Call the loss function with the selected layer
              metrics=['accuracy'])


# train
sys.stdout.flush()
startTime = time.time()
history = model.fit(x.numpy(), y.numpy(),epochs=25000, batch_size = x.shape[0])
endTime = time.time()
elapsed = (endTime - startTime) / 60.0
print("The training took {:.4} minutes".format(elapsed))


s = 'MyModel_tf'
model.save(s,save_format='tf')
```

**Comment by chunduriv** [comment]
@saddamhijazi,
A workaround would be to simply save your model with the `H5` format, `model.save(s,save_format='h5')`.

**Comment by saddamhijazi** [comment]
Thank you for your answer @chunduriv, then I will change to the h5 format. Thanks again, I will close the issue.
