### ISSUE TITLE
Transformer toolkit 

### ISSUE THREAD

**Issue by vulkomilev** [keras-team/keras#16181]
I want to implement a transformer toolkit(a set of modules that will compose some kind of DL model with attention ).I have said a toolkit because the today's landscape of the transformer research is very diverse and I think that it will be better to have the separate modules ( attention layer , concat layer ,add& norm layer etc)  and mix and match them rather to have one or two ready layer that will be very general and not good for any specific task

**Comment by bhack** [comment]
> APIs for transformer encoder/decoder block? We have an ongoing project called Keras-nlp, which has implemented the encoder and decoder

Are these potential API really related to NLP only? Do we need to replicate/duplicate these in the CV vertical repo (keras-cv)?

Is it a quite general issue about where to handle cross domain API/components (see https://github.com/keras-team/keras-cv/issues/137#issuecomment-1043585248) other then the Keras main repo.

**Comment by chenmoneygithub** [comment]
Yes, I am aware that transformer is applied on CV as well. However, there is some subtle difference here - on NLP tasks, we can assume the input shape is 3D: [batch_size, sequence_length, feature_size], so we can use [tf.keras.layers.MultiHeadAttention](https://www.tensorflow.org/api_docs/python/tf/keras/layers/MultiHeadAttention) to simplify the implementation and make it very readable. But on CV, the input of transformer can be of variant shape, implementation needs a more general approach like Einsum, so at least for now, we are keeping transformer to KerasNLP only.

And you are totally correct, we need to agree on a repo for shared components. We think it makes sense to put things into Keras main repo if both KerasCV and KerasNLP would depend on them.
