### ISSUE TITLE
Better error message for Unexpected result of `train_function` (Empty logs). Please use `Model.compile(..., run_eagerly=True)`, or `tf.config.run_functions_eagerly(True)` for more information of where went wrong, or file a issue/bug to `tf.keras`

### ISSUE THREAD

**Issue by Vishu26** [keras-team/keras#16202]
Hi!

This error message pops up when empty arrays are passed to `Model.fit` or `Model.predict`. The solution suggested in the error message does not work and in some sense is not logical. Either the error message should be updated or the mentioned functions should have additional assertions to check for empty input arrays.

**Comment by sachinprasadhs** [comment]
Could you please provide some simple reproducible code and the error message which you are getting currently in order to expedite the troubleshooting process. Thanks!

**Comment by Vishu26** [comment]
To be precise, this issue popped up in `tensorflow==2.7.0` and `keras==2.7.0` and their recent versions.

Currently, I have `python==3.8.6`, `tensorflow==2.8.0` and `keras==2.8.0`.

The minimal code to reproduce the issue:

```
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
import numpy as np

X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
Y = np.array([0, 1, 1, 0])

model = Sequential()
model.add(Dense(16, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='Adam', loss='binary_crossentropy', metrics=['acc'])

idx = []

model.fit(X[idx], Y[idx])
```

**Comment by NAWRASALANI** [comment]
i have the same issue and i didnt know what is the solution

**Comment by urosjarc** [comment]
Fix this error message to something more logical. Asap

**Comment by bhack** [comment]
Can you check also this case:
https://discuss.tensorflow.org/t/text-based-tensorflow-unexpected-result-of-train-function-empty-logs/11075

**Comment by SJYinda** [comment]
Hi all,

Is there any solution to this issue?

Thank you in advance.

**Comment by mani2001** [comment]
> Hi all,
> 
> Is there any solution to this issue?
> 
> Thank you in advance.

Did you find a solution to this?

**Comment by pwernette** [comment]
Any update on a different (more informative) error message?

I've been working with TF for a while now and just have to say that this generic error message requires a lot more time to debug code than it seems like it should. Having a more informative message would really help code development.

**Comment by sachinprasadhs** [comment]
@pwernette , There is a PR created for this issue here https://github.com/keras-team/keras/pull/16216, but there is no update from the author.

**Comment by Gumo-A** [comment]
In the hope of helping someone in a similar situation, I had the same error message, but my problem was my .fit() call was using a backup I had created using keras' BackupAndRestore callback. After deleting the backup, training could be launched.
