### ISSUE TITLE
How to make notop weight？

### ISSUE THREAD

**Issue by atlastanka** [keras-team/keras#16214]
How to make weight without FC?

**Comment by sushreebarsa** [comment]
@atlastanka 
Can you please elaborate about the feature and please specify the use cases for this feature? Thanks!

**Comment by atlastanka** [comment]
I have a weight of the ResNet in the custom data set, I want to convert it into the weight that does not include the full connection layer. When I set include_top = false, the weight cannot be loaded.
how to transfer the weight from include_top = true to include_top = false?

**Comment by old-school-kid** [comment]
@atlastanka 
You can save/transfer weights either by layer name or their index. Since you are using a ResNet all you FCs will occur at the end so you can use negative indexing for transfering weights.

**Comment by atlastanka** [comment]
So can this weight use different size images as the inputs?
