### ISSUE TITLE
 AttributeError: 'LossScaleOptimizer' object has no attribute '_hypers_created'

### ISSUE THREAD

**Issue by anth2o** [keras-team/keras#16218]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOSX 12.2.1
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.8
- Python version: 3.8.12
- Bazel version (if compiling from source):
- GPU model and memory: None
- Exact command to reproduce:

**Describe the problem**.

I can't access the value of the learning of my optimizer if I'm using both:
- `LossScaleOptimizer`
- `LearningRateSchedule`

Because I'm using `LearningRateSchedule`, I try to access the learning rate's value with `optimizer._decayed_lr("float32")`

**Describe the current behavior**.

 I have an error `AttributeError: 'LossScaleOptimizer' object has no attribute '_hypers_created'` (full stack trace at the end)

**Describe the expected behavior**.

I would expect this code to work, as it did when I wasn't using a `LossScaleOptimizer`

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no): yes
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing):

Currently, I avoided this bug in my code by doing:
```python
if isinstance(optimizer, tf.keras.mixed_precision.LossScaleOptimizer):
    value = optimizer._optimizer._decayed_lr("float32")
else:
    value = optimizer._decayed_lr("float32")
```
we could perform a similar logic in the implementation of `LossScaleOptimizer`

**Standalone code to reproduce the issue**.

```python
import pytest
import tensorflow as tf
from contextlib import ExitStack


class Schedule(tf.keras.optimizers.schedules.LearningRateSchedule):

    def __call__(self, step):
        return step


@pytest.mark.parametrize("use_loss_scale", [False, True])
def test_get_lr(use_loss_scale):
    optimizer = tf.keras.optimizers.Adam(learning_rate=Schedule())
    if use_loss_scale:
        optimizer = tf.keras.mixed_precision.LossScaleOptimizer(optimizer)
    assert optimizer._decayed_lr("float32").numpy() == 0
```

Launch it with `pytest`

**Source code / logs**.

```bash
test_loss_scale.py:18:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../../venv/lib/python3.8/site-packages/keras/optimizer_v2/optimizer_v2.py:1005: in _decayed_lr
    lr_t = self._get_hyper("learning_rate", var_dtype)
../../../venv/lib/python3.8/site-packages/keras/optimizer_v2/optimizer_v2.py:795: in _get_hyper
    if not self._hypers_created:
../../../venv/lib/python3.8/site-packages/keras/mixed_precision/loss_scale_optimizer.py:796: in __getattribute__
    raise e
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <keras.mixed_precision.loss_scale_optimizer.LossScaleOptimizer object at 0x1249895e0>, name = '_hypers_created'

    def __getattribute__(self, name):
      try:
>       return object.__getattribute__(self, name)
E       AttributeError: 'LossScaleOptimizer' object has no attribute '_hypers_created'

../../../venv/lib/python3.8/site-packages/keras/mixed_precision/loss_scale_optimizer.py:785: AttributeError
```

**Comment by sushreebarsa** [comment]
@anth2o I tried to replicate the issue on colab using TF v2.8.0 and tf-nightly but didn't face the error reported. Could you please have a look at the gist [here](https://colab.research.google.com/gist/sushreebarsa/bf90612286b39325185b3896b1a8d722/16218.ipynb) and let me know if I have missed something to reproduce the issue?
Thanks!

**Comment by anth2o** [comment]
@sushreebarsa Actually I think you didn't execute the code. I wrote this piece of code as a unit test that has to be launched with pytest. If you want to reproduce the issue with your Colab, you should called the method:
```python
test_get_lr(True)
```

**Comment by sushreebarsa** [comment]
@anth2o Thank you for the response!
@sachinprasadhs I was able to replicate the issue on colab , please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/77eb39e11335cb4edbe8d3a7053dfc6f/16218-updated.ipynb).
Thanks!

**Comment by gowthamkpr** [comment]
The LossScaleOptimizer issues comes from the fact that we call a private _decayed_lr method on the optimizer, which is not supported on the LossScaleOptimizer:

Please take a look at this [comment](https://github.com/tensorflow/models/issues/9262#issuecomment-696420425) and follow the steps as provided in the comment.
