### ISSUE TITLE
keras.preprocessing.image_dataset_from_directory resizes image even if its source size is already the target size.

### ISSUE THREAD

**Issue by TrueWodzu** [keras-team/keras#16227]
**System information**.
- TensorFlow version (use command below): v2.3.0-rc2-23-gb36436b087 2.3.0
- Keras version: 2.4.3
- keras-preprocessing version: 1.1.2

**Describe the problem**.

This is a twofold problem:

Firstly, it is not optimal to perform a resize on the image that has already the target size.
Secondly, resize operation on such image, changes the binary representation of the image. This impacts the training of a model and inference.

**Describe the current behavior**.

There is no internal check in `keras.preprocessing.image_dataset_from_directory` whether a given image is already at the target size, and such image is interpolated regardless of the need of doing so.

**Describe the expected behavior**.

It should be checked whether an image needs an interpolation, before applying the interpolation (resizing).

`image_dataset_from_directory` is an entry point but the real operations happens in `paths_and_labels_to_dataset` which then calls `path_to_image` :

```
def path_to_image(path, image_size, num_channels, interpolation):
  img = io_ops.read_file(path)
  img = image_ops.decode_image(
      img, channels=num_channels, expand_animations=False)
  img = image_ops.resize_images_v2(img, image_size, method=interpolation)
  img.set_shape((image_size[0], image_size[1], num_channels))
  return imgn)
```

Proposed solution (just comment added, no actual code):

```
def path_to_image(path, image_size, num_channels, interpolation):
  img = io_ops.read_file(path)
  img = image_ops.decode_image(
      img, channels=num_channels, expand_animations=False)
  # Check height and width of img and if they are the same as image_size don't call resize_images_v2
  img = image_ops.resize_images_v2(img, image_size, method=interpolation)
  img.set_shape((image_size[0], image_size[1], num_channels))
  return img
```

**Contributing**.

- Do you want to contribute a PR? (yes/no): No, I have not enough experience.

**Comment by tilakrayal** [comment]
@TrueWodzu ,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also can you please test the code in latest stable v2.8 and let us know if you are facing same issue.Thanks!

**Comment by tilakrayal** [comment]
@gadagashwini ,
I was able to reproduce the issue in tf v2.8, v2.7 and nightly.Please find the gist [here](https://colab.research.google.com/gist/tilakrayal/f36559373eba6894886caa430c5284f2/untitled251.ipynb).

**Comment by gadagashwini** [comment]
@TrueWodzu,

Are there scenarios where img.shape[0] will be None because tf.image.decode_image() will return a dynamically sized image? I think this should happen any time the function is called inside a compiled tf.function?

**Comment by TrueWodzu** [comment]
> Are there scenarios where img.shape[0] will be None because tf.image.decode_image() will return a dynamically sized image? 

I am not sure I understand your question. Each Tensor returned from tf.image.decode_image() will have a 3 or 4 dimensional shape, so I don't think it will ever happen that img.shape[0] will be None. tf.image.decode_image() either returns a valid Tensor or it throws an exception.

However, your question forced me to delve deeper into tf.image.decode_image and it seems that img.shape[0] not necessarily will always contain image height:

>   Returns:
>     `Tensor` with type `dtype` and a 3- or 4-dimensional shape, depending on
>     the file type and the value of the `expand_animations` parameter.

>   Note: `decode_gif` returns a 4-D array `[num_frames, height, width, 3]`, as
>   opposed to `decode_bmp`, `decode_jpeg` and `decode_png`, which return 3-D
>   arrays `[height, width, num_channels]`.

In case of animated giff img.shape[0] will contain number of frames not the image height. So the check for dimensions must be modified to something like this:

```
  if tf.size(img.shape) == 3:
    idx = 0
  else:
    idx = 1 # 4-dimensional shape keeps number of frames at index 0
  if img.shape[idx] != image_size[0] or img.shape[idx + 1] != image_size[1]: # Possible fix
    if crop_to_aspect_ratio:
      img = keras_image_ops.smart_resize(img, image_size,
                                        interpolation=interpolation)
    else:
      img = tf.image.resize(img, image_size, method=interpolation)
```

A side note: the line right after my proposed changes, probably contains a bug too:
`img.set_shape((image_size[0], image_size[1], num_channels))`
 
As you can see it doesn't take into account a possibility of a 4-dimensional array .

**Comment by gadagashwini** [comment]
@TrueWodzu, Can you take a look at the [#16301](https://github.com/keras-team/keras/pull/16301#discussion_r841096001)
