### ISSUE TITLE
Attention layer fails when both queries and values are ragged tensors

### ISSUE THREAD

**Issue by ageron** [keras-team/keras#16226]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 12.2.1
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.8.0-rc1-32-g3f878cff5b6 2.8.0
- Python version: 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:28:27)
- Bazel version (if compiling from source): N/A
- GPU model and memory: N/A
- Exact command to reproduce:

```python
import tensorflow as tf

query_ids = tf.ragged.constant([[1, 2, 3], [1, 3, 5, 7, 9, 3, 1]])
value_ids = tf.ragged.constant([[0, 1, 2, 6, 8, 1, 3, 4], [1, 2, 9]])
embedding_layer = tf.keras.layers.Embedding(10, 5)
queries = embedding_layer(query_ids)
values = embedding_layer(value_ids)
attention_layer = tf.keras.layers.Attention()
outputs = attention_layer([queries, values])   # InvalidArgumentError!
```

See this [gist](https://colab.research.google.com/gist/ageron/eb830024b72ff3695403cf21e0ea7c8b/keras-issue.ipynb).

**Describe the problem**.

The `Attention` layer raises an `InvalidArgumentError` when both the queries and the values are ragged tensors.

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no): not right now, perhaps in a few weeks

**Source code / logs**.

Below is the full stacktrace:

<details>

```stacktrace
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-1-3f041ae3adb1> in <module>()
      7 values = embedding_layer(value_ids)
      8 attention_layer = tf.keras.layers.Attention()
----> 9 outputs = attention_layer([queries, values])   # InvalidArgumentError!

1 frames
/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py in error_handler(*args, **kwargs)
     65     except Exception as e:  # pylint: disable=broad-except
     66       filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67       raise e.with_traceback(filtered_tb) from None
     68     finally:
     69       del filtered_tb

/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py in raise_from_not_ok_status(e, name)
   7184 def raise_from_not_ok_status(e, name):
   7185   e.message += (" name: " + name if name is not None else "")
-> 7186   raise core._status_to_exception(e) from None  # pylint: disable=protected-access
   7187 
   7188 

InvalidArgumentError: Exception encountered when calling layer "attention" (type Attention).

All flat_values must have compatible shapes.  Shape at index 0: [8].  Shape at index 1: [3].  If you are using tf.map_fn, then you may need to specify an explicit fn_output_signature with appropriate ragged_rank, and/or convert output tensors to RaggedTensors. [Op:RaggedTensorFromVariant]

Call arguments received:
  • inputs=['<tf.RaggedTensor [[[-0.027546966, -0.046601307, 0.031270754, 0.002985619, 0.03187236],\n  [-0.043807685, -0.0034521446, -0.03243687, 0.0064857714, 0.0027313456],\n  [-0.021520246, -0.035491932, -0.04025687, -0.043561112, -0.040334523]] ,\n [[-0.027546966, -0.046601307, 0.031270754, 0.002985619, 0.03187236],\n  [-0.021520246, -0.035491932, -0.04025687, -0.043561112, -0.040334523],\n  [0.02757522, 0.04603419, -0.03672434, 0.017829526, -0.0049615987],\n  [-0.031660724, -0.011377871, 0.03767674, 0.016496744, -0.037768506],\n  [-0.009317435, 0.01874194, 0.04787064, 0.0045291185, -0.033237804],\n  [-0.021520246, -0.035491932, -0.04025687, -0.043561112, -0.040334523],\n  [-0.027546966, -0.046601307, 0.031270754, 0.002985619, 0.03187236]]   ]>', '<tf.RaggedTensor [[[-0.012168575, -0.04613155, -0.01253029, -0.011328984, -0.028791858],\n  [-0.027546966, -0.046601307, 0.031270754, 0.002985619, 0.03187236],\n  [-0.043807685, -0.0034521446, -0.03243687, 0.0064857714, 0.0027313456],\n  [0.04400405, 0.036700714, -0.013053097, -0.036535777, 0.0032472126],\n  [0.03461111, -0.04031247, 0.03413892, 0.0055856705, -0.032852937],\n  [-0.027546966, -0.046601307, 0.031270754, 0.002985619, 0.03187236],\n  [-0.021520246, -0.035491932, -0.04025687, -0.043561112, -0.040334523],\n  [-0.013353277, 0.033556495, 0.022906508, -0.005790353, -0.018588793]]  ,\n [[-0.027546966, -0.046601307, 0.031270754, 0.002985619, 0.03187236],\n  [-0.043807685, -0.0034521446, -0.03243687, 0.0064857714, 0.0027...
  • mask=None
  • training=None
  • return_attention_scores=False
```

</details>

**Comment by ageron** [comment]
Note that the layer works fine when the queries are ragged, but not the values. For example, this works fine:

```python
outputs = attention_layer([queries, values.to_tensor()])  # OK
```

**Comment by sushreebarsa** [comment]
@sachinprasadhs Was able to reproduce this issue on colab using TF v2.8.0 and tf-nightly(2.9.0.dev20220310),please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/9da271e44bf9534568e69791f1e40c5e/keras-issue.ipynb#scrollTo=mGyVQ7ZxYi4i).Thanks!

**Comment by ageron** [comment]
It looks like the exception is due to [this line](https://github.com/keras-team/keras/blob/980a6be629610ee58c1eae5a65a4724ce650597b/keras/layers/attention/attention.py#L174) in attention.py:

```python
scores = tf.matmul(query, key, transpose_b=True)
```

When I call this line directly, passing it `query=queries` and `key=values` using the `queries` and `values` defined in the above code example, I get the same exception.

But if I transpose the values first (swapping the last two dimensions), and I remove `transpose_b=True`, then it works fine:

```python
transposed_values = tf.transpose(values, perm=[0, 2, 1])
scores = tf.matmul(query, transposed_values)  # works fine!
```

However, the `tf.transpose()` line does not actually work, I had to build a ragged tensor manually. I can't find a way to do this transpose operation efficiently. Any ideas?

**Comment by ageron** [comment]
It's also worth noting that the code example also works fine if you set `score_mode="concat"` (in TF 2.9+).

**Comment by LukeWood** [comment]
> Do you want to contribute a PR? (yes/no): not right now, perhaps in a few weeks

If you would be able to contribute a fix, this would be great.
@ageron

**Comment by LukeWood** [comment]
Thanks - We will follow up with TensorFlow

**Comment by ageron** [comment]
The root TensorFlow issue #55209 was fixed in [this commit](https://github.com/tensorflow/tensorflow/commit/abc6f6ec7869d846b33b3d8e5e33284aac1600dc), so hopefully it will also fix this issue (unless it reveals another issue?).

**Comment by LukeWood** [comment]
Cool!  Yeah, should be fixed now so lets close unless another arises.  Thanks @ageron

**Comment by haifeng-jin** [comment]
@ageron I am working on supporting a ragged tensor Transformer. Will further verify the bug is fixed. Thanks
