### ISSUE TITLE
ValueError: Shapes (None, 7) and (None, 1, 7) are incompatible

### ISSUE THREAD

**Issue by Nafees-060** [keras-team/keras#16228]
I am implementing variable length time-series classification by using CNN and LSTM. Let me explain in detail:

I have **data** `train_x`, its list of **200 Elements** and each element index contained `ndarray` of different shapes for example `(1095, 6, 1), (332, 6, 1), (776, 6, 1), (22, 6, 1)` and so on. And the `train_y` is **label** which is `ndarray` (Note its not list) with (200,7) dimensions. 7 means labels are total 7 and its converted into one hot. 

From the data, it can be clearly observed that input to the model is variable-length. Sometime input is excessively large and sometime small. To handle memory for the large input, I am utilizing `generator`. In addition I am using `tf.data.Dataset` to prepare efficient input pipeline for the model

     train_var_len = tf.data.Dataset.from_generator(lambda: (train_x, train_y),
                                                       (tf.float64, tf.float64),
                                                       output_shapes=([None, 6, 1], [200, 7])
                                                       )

     un_data = tf.data.Dataset.unbatch(train_var_len)
     ds_series_batch = un_data.shuffle(batch_size).padded_batch(batch_size) # padded_batch means to make input length uniform in each batch. However I do not have intention that model consider these 0 padded value with the original input. So it should be masked, if my model architecture is not accordingly, please make me correct
     test_ds = tf.data.Dataset.from_tensor_slices((test_x, test_y)).batch(batch_size) # test_x: ndarray: (16079, 24, 6, 1) and test_y ndarray: (16079, 7)

    input_shape = (None, 6, 1)
    model = model_arch(input_shape, total_classes) # total_classes = 7

**Here is the code for model_arch(input_shape, total_classes) with LSTM_mod(cnn_featuremap) function**:
 
    def LSTM_mod(cnn_featureMap):
    rl = Reshape((-1, int(cnn_SE_featureMap.shape[2]) * int(cnn_SE_featureMap.shape[3])))(
        cnn_featureMap)

    lstm_l5 = tf.keras.layers.LSTM(128, activation='tanh',
                                   recurrent_initializer=tf.keras.initializers.Orthogonal(), dropout=0.0,
                                   recurrent_dropout=0.0, return_sequences=True)(
        rl) 
    lstm_l6 = tf.keras.layers.LSTM(128, activation='tanh',
                                   recurrent_initializer=tf.keras.initializers.Orthogonal(), dropout=0.9,
                                   recurrent_dropout=0.5, return_sequences=True)(lstm_l5)
    return lstm_l6

    def model_arch(input_shape, total_classes):
        input_layer = tf.keras.Input(shape=input_shape, name="time_series_activity")
        input_mask = tf.keras.layers.Masking(mask_value=0.)(input_layer)
        con_l1 = tf.keras.layers.Conv2D(64, (5, 1), activation="relu", padding="same")(
            input_mask)  # padding="same" ensure the dimensions will be same
    
        con_l2 = tf.keras.layers.Conv2D(64, (5, 1), activation="relu", padding="same")(con_l1)
    
        con_l3 = tf.keras.layers.Conv2D(64, (5, 1), activation="relu", padding="same")(con_l2)
    
        con_l4 = tf.keras.layers.Conv2D(64, (5, 1), activation="relu", padding="same")(con_l3)
        lstm_fm = LSTM_mod(con_l4)
        output_layer = tf.keras.layers.Dense(total_classes, activation="softmax")(lstm_fm)
        return tf.keras.models.Model(inputs=input_layer, outputs=output_layer)
       
     
   **Rest of the code:**

      model.compile(loss="categorical_crossentropy",
                  optimizer=opt,
                  metrics=[tfa.metrics.F1Score(num_classes=total_classes, average='macro')]
                  )

    path_checkpoint = os.path.join(filepath,
                                   dataset,
                                   "best_model_checkpoint"
                                   )
    callback_model_saving = tf.keras.callbacks.ModelCheckpoint(filepath=path_checkpoint,
                                                               monitor='val_f1_score',
                                                               mode='max',
                                                               verbose=1,
                                                               save_best_only=True)
    history = model.fit(ds_series_batch, epochs=total_epoch,
                        callbacks=[callbacks, callback_model_saving],
                        validation_data=test_ds)
    
**Error**

     target.shape.assert_is_compatible_with(output.shape)
    
        ValueError: Shapes (None, 7) and (None, 1, 7) are incompatible

It seems the prediction output and actual output dimensions are not matched. How I should fix this problem?

Particularly see, I am on the right path to handle variable length problem. If not, please guide me how should I implement this kind of problem?

**Comment by t3bol90** [comment]
Would I ask you, @Nafees-060 a question about how to overcome this issue when using Keras? I have the same problem of shape with additional ONE in the middle. 

![image](https://user-images.githubusercontent.com/43676770/158207838-05056a2f-d7e0-40eb-80d9-9c3eaddc0303.png)

**Comment by Nafees-060** [comment]
@t3bol90 It means your actual output shape is (5, 1, 5) and your prediction is (5, 5). So I believe you need to see your code where you reduced 1 dimension. In my case you can see that true value shape was (None, 7) and in prediction I was getting (None, 1, 7). So I just used flatten layer before output layer to make the dimension into (None, 7). However, in your case it seems you reduced 1 Dimension in the architecture or some thing that. You should see your code.

**Comment by t3bol90** [comment]
Thank you @Nafees-060, the problem is the output of tf.one_hot in my implementation return addition 1 in the middle, I need to reshape the output of one hot vector <3.

**Comment by zahraatalal** [comment]
i tried to write a vgg16 encoder-decoder  and use cat and dog to train model but the error occur and i can not fix it please help me 
def vgg16_encoder_decoder(input_size = (64,64,3)):
    #################################
    # Encoder
    #################################
    inputs = Input(input_size, name = 'input')

    conv1_be = Conv2D(64, (3, 3), activation = 'relu', padding = 'same', name ='conv1_1')(inputs)
    print ('out of conv1===========', conv1_be.shape)
    conv1 = Conv2D(64, (3, 3), activation = 'relu', padding = 'same', name ='conv1_2')(conv1_be)
    pool1 = MaxPooling2D(pool_size = (2,2), strides = (2,2), name = 'pool_1')(conv1)

    conv2 = Conv2D(128, (3, 3), activation = 'relu', padding = 'same', name ='conv2_1')(pool1)
    conv2 = Conv2D(128, (3, 3), activation = 'relu', padding = 'same', name ='conv2_2')(conv2)
    pool2 = MaxPooling2D(pool_size = (2,2), strides = (2,2), name = 'pool_2')(conv2)
    
    conv3 = Conv2D(256, (3, 3), activation = 'relu', padding = 'same', name ='conv3_1')(pool2)
    conv3 = Conv2D(256, (3, 3), activation = 'relu', padding = 'same', name ='conv3_2')(conv3)
    conv3 = Conv2D(256, (3, 3), activation = 'relu', padding = 'same', name ='conv3_3')(conv3)
    pool3 = MaxPooling2D(pool_size = (2,2), strides = (2,2), name = 'pool_3')(conv3)
    
    conv4 = Conv2D(512, (3, 3), activation = 'relu', padding = 'same', name ='conv4_1')(pool3)
    conv4 = Conv2D(512, (3, 3), activation = 'relu', padding = 'same', name ='conv4_2')(conv4)
    conv4 = Conv2D(512, (3, 3), activation = 'relu', padding = 'same', name ='conv4_3')(conv4)
    pool4 = MaxPooling2D(pool_size = (2,2), strides = (2,2), name = 'pool_4')(conv4)

    conv5 = Conv2D(512, (3, 3), activation = 'relu', padding = 'same', name ='conv5_1')(pool4)
    conv5 = Conv2D(512, (3, 3), activation = 'relu', padding = 'same', name ='conv5_2')(conv5)
    conv5 = Conv2D(512, (3, 3), activation = 'relu', padding = 'same', name ='conv5_3')(conv5)
    # pool5 = MaxPooling2D(pool_size = (2,2), strides = (2,2), name = 'pool_5')(conv5)

    #############################################
    # Decoder
    ############################################
    #conv1 = Conv2DTranspose(512, (2, 2), strides = 2, name = 'conv1')(pool5)

    # upsp1 = UpSampling2D(size = (2,2), name = 'upsp1')(pool5)
    conv6 = Conv2D(512, 3, activation = 'relu', padding = 'same', name = 'conv6_1')(conv5)
    conv6 = Conv2D(512, 3, activation = 'relu', padding = 'same', name = 'conv6_2')(conv6)
    conv6 = Conv2D(512, 3, activation = 'relu', padding = 'same', name = 'conv6_3')(conv6)

    upsp2 = UpSampling2D(size = (2,2), name = 'upsp2')(conv6)
    conv7 = Conv2D(512, 3, activation = 'relu', padding = 'same', name = 'conv7_1')(upsp2)
    conv7 = Conv2D(512, 3, activation = 'relu', padding = 'same', name = 'conv7_2')(conv7)
    conv7 = Conv2D(512, 3, activation = 'relu', padding = 'same', name = 'conv7_3')(conv7)
    # zero1 = ZeroPadding2D(padding =  ((1, 0), (1, 0)), data_format = 'channels_last', name='zero1')(conv7)

    upsp3 = UpSampling2D(size = (2,2), name = 'upsp3')(conv7)
    conv8 = Conv2D(256, 3, activation = 'relu', padding = 'same', name = 'conv8_1')(upsp3)
    conv8 = Conv2D(256, 3, activation = 'relu', padding = 'same', name = 'conv8_2')(conv8)
    conv8 = Conv2D(256, 3, activation = 'relu', padding = 'same', name = 'conv8_3')(conv8)

    upsp4 = UpSampling2D(size = (2,2), name = 'upsp4')(conv8)
    conv9 = Conv2D(128, 3, activation = 'relu', padding = 'same', name = 'conv9_1')(upsp4)
    conv9 = Conv2D(128, 3, activation = 'relu', padding = 'same', name = 'conv9_2')(conv9)

    upsp5 = UpSampling2D(size = (2,2), name = 'upsp5')(conv9)
    conv10 = Conv2D(64, 3, activation = 'relu', padding = 'same', name = 'conv10_1')(upsp5)
    conv10 = Conv2D(64, 3, activation = 'relu', padding = 'same', name = 'conv10_2')(conv10)
    print ('the len of conv10======',conv10.shape)
    # conv11 = Conv2D(1, 3, activation = 'relu', padding = 'same', name = 'conv11')(conv10)
    # print ('the len of conv11======',conv10.shape)
    model =keras.Model(inputs = inputs, outputs = conv10, name = 'vgg-16_encoder_decoder')
    # model.summary()
    return model






###########################################################

# k = vgg16_encoder_decoder()
# k.summary()
################ Read image from dataset and check the size 

import imageio as iio
 
# read an image
img1 = iio.imread('dataset/training_set/cats/cat.1.jpg')
img = np.resize(img1,(224,224))
###########################################################
k = vgg16_encoder_decoder()
k.summary()


from keras.optimizers import Adam
opt = Adam(learning_rate=0.001)
# model.compile(optimizer=opt, loss=keras.losses.categorical_crossentropy, metrics=['accuracy'])

k.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

from keras.preprocessing.image import ImageDataGenerator
train_datagen = ImageDataGenerator(rescale = 1./255, horizontal_flip = True)
test_datagen = ImageDataGenerator(rescale = 1./255)
training_set = train_datagen.flow_from_directory('dataset/training_set', target_size = (64, 64), batch_size = 32, class_mode = 'binary')
test_set = test_datagen.flow_from_directory('dataset/test_set', target_size = (64, 64), batch_size = 32, class_mode = 'binary')
k.fit(training_set, epochs =5, validation_data = test_set)


ValueError: in user code:

    File "C:\Users\6g\anaconda3\envs\RESNET_ENCODER\lib\site-packages\keras\engine\training.py", line 1051, in train_function  *
        return step_function(self, iterator)
    File "C:\Users\6g\anaconda3\envs\RESNET_ENCODER\lib\site-packages\keras\engine\training.py", line 1040, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\6g\anaconda3\envs\RESNET_ENCODER\lib\site-packages\keras\engine\training.py", line 1030, in run_step  **
        outputs = model.train_step(data)
    File "C:\Users\6g\anaconda3\envs\RESNET_ENCODER\lib\site-packages\keras\engine\training.py", line 890, in train_step
        loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "C:\Users\6g\anaconda3\envs\RESNET_ENCODER\lib\site-packages\keras\engine\training.py", line 948, in compute_loss
        return self.compiled_loss(
    File "C:\Users\6g\anaconda3\envs\RESNET_ENCODER\lib\site-packages\keras\engine\compile_utils.py", line 201, in __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "C:\Users\6g\anaconda3\envs\RESNET_ENCODER\lib\site-packages\keras\losses.py", line 139, in __call__
        losses = call_fn(y_true, y_pred)
    File "C:\Users\6g\anaconda3\envs\RESNET_ENCODER\lib\site-packages\keras\losses.py", line 243, in call  **
        return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "C:\Users\6g\anaconda3\envs\RESNET_ENCODER\lib\site-packages\keras\losses.py", line 1787, in categorical_crossentropy
        return backend.categorical_crossentropy(
    File "C:\Users\6g\anaconda3\envs\RESNET_ENCODER\lib\site-packages\keras\backend.py", line 5119, in categorical_crossentropy
        target.shape.assert_is_compatible_with(output.shape)

    ValueError: Shapes (None,) and (None, 64, 64, 64) are incompatible

**Comment by Afnan7120** [comment]
> @zahraatalal It was difficult to find any post with this error and I'm so lucky you've just posted it. Have you managed with this? For a few days, I'm fighting with my autoencoder and now I've got the one.
> 
> My code:
> 
> ```python
> # encoder
> model2 = models.Sequential()
> model2.add(layers.Conv2D(32, 5, padding='same', activation='relu', strides=(1, 1), input_shape=img_shape))
> model2.add(layers.MaxPooling2D(pool_size=(3, 3), strides=(1, 1)))
> model2.add(layers.Conv2D(64, 5, activation='relu', strides=(1, 1)))
> model2.add(layers.MaxPooling2D(pool_size=(3, 3), strides=(1, 1)))
> model2.add(layers.Conv2D(128, 5, activation='relu', strides=(1, 1)))
> model2.add(layers.MaxPooling2D(pool_size=(3, 3), strides=(1, 1)))
> 
> shape_before_flattening = (50, 50, 128)
> 
> model2.add(layers.Flatten())
> model2.add(layers.Dense(64, activation="relu"))
> model2.add(layers.Dense(64, activation="relu"))
> model2.add(layers.Dense(2, activation="softmax"))
>  
> # decoder
> decoder = models.Sequential()
> decoder.add(layers.InputLayer(2))
> decoder.add(layers.Dense(shape_before_flattening[0] * shape_before_flattening[1] * shape_before_flattening[2]))
> decoder.add(layers.Reshape((shape_before_flattening[0], shape_before_flattening[1], shape_before_flattening[2])))
> decoder.add(layers.Conv2D(128, 5, strides=(1, 1), activation='relu'))
> decoder.add(layers.Conv2D(64, 5, strides=(1, 1), activation='relu'))
> decoder.add(layers.Conv2D(32, 5, strides=(1, 1), activation='relu'))
> decoder.add(layers.Conv2D(32, 5, strides=(1, 1), activation='relu'))
> decoder.add(layers.UpSampling2D(2))
> decoder.add(layers.Conv2D(3, 5, strides=(1, 1), activation='softmax'))
> 
> # autoencoder
> autoencoder = Model(inputs=model2.input, outputs=decoder(model2.outputs))
> autoencoder.compile(optimizer='adam', loss="categorical_crossentropy", metrics= ["accuracy"])
> earlystopping = callbacks.EarlyStopping(monitor="val_loss", mode="min", patience=5, restore_best_weights=True)
> history_autoencoder = autoencoder.fit(trainset, epochs=25, verbose=1, validation_data=(testset), callbacks=[earlystopping])
> ```
> 
> Received error:
> 
> ```
> ValueError: in user code:
> 
>     File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1021, in train_function  *
>         return step_function(self, iterator)
>     File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1010, in step_function  **
>         outputs = model.distribute_strategy.run(run_step, args=(data,))
>     File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1000, in run_step  **
>         outputs = model.train_step(data)
>     File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 860, in train_step
>         loss = self.compute_loss(x, y, y_pred, sample_weight)
>     File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 919, in compute_loss
>         y, y_pred, sample_weight, regularization_losses=self.losses)
>     File "/usr/local/lib/python3.7/dist-packages/keras/engine/compile_utils.py", line 201, in __call__
>         loss_value = loss_obj(y_t, y_p, sample_weight=sw)
>     File "/usr/local/lib/python3.7/dist-packages/keras/losses.py", line 141, in __call__
>         losses = call_fn(y_true, y_pred)
>     File "/usr/local/lib/python3.7/dist-packages/keras/losses.py", line 245, in call  **
>         return ag_fn(y_true, y_pred, **self._fn_kwargs)
>     File "/usr/local/lib/python3.7/dist-packages/keras/losses.py", line 1790, in categorical_crossentropy
>         y_true, y_pred, from_logits=from_logits, axis=axis)
>     File "/usr/local/lib/python3.7/dist-packages/keras/backend.py", line 5083, in categorical_crossentropy
>         target.shape.assert_is_compatible_with(output.shape)
> 
>     ValueError: Shapes (None,) and (None, 64, 64, 3) are incompatible
> ```



> @zahraatalal It was difficult to find any post with this error and I'm so lucky you've just posted it. Have you managed with this? For a few days, I'm fighting with my autoencoder and now I've got the one.
> 
> My code:
> 
> ```python
> # encoder
> model2 = models.Sequential()
> model2.add(layers.Conv2D(32, 5, padding='same', activation='relu', strides=(1, 1), input_shape=img_shape))
> model2.add(layers.MaxPooling2D(pool_size=(3, 3), strides=(1, 1)))
> model2.add(layers.Conv2D(64, 5, activation='relu', strides=(1, 1)))
> model2.add(layers.MaxPooling2D(pool_size=(3, 3), strides=(1, 1)))
> model2.add(layers.Conv2D(128, 5, activation='relu', strides=(1, 1)))
> model2.add(layers.MaxPooling2D(pool_size=(3, 3), strides=(1, 1)))
> 
> shape_before_flattening = (50, 50, 128)
> 
> model2.add(layers.Flatten())
> model2.add(layers.Dense(64, activation="relu"))
> model2.add(layers.Dense(64, activation="relu"))
> model2.add(layers.Dense(2, activation="softmax"))
>  
> # decoder
> decoder = models.Sequential()
> decoder.add(layers.InputLayer(2))
> decoder.add(layers.Dense(shape_before_flattening[0] * shape_before_flattening[1] * shape_before_flattening[2]))
> decoder.add(layers.Reshape((shape_before_flattening[0], shape_before_flattening[1], shape_before_flattening[2])))
> decoder.add(layers.Conv2D(128, 5, strides=(1, 1), activation='relu'))
> decoder.add(layers.Conv2D(64, 5, strides=(1, 1), activation='relu'))
> decoder.add(layers.Conv2D(32, 5, strides=(1, 1), activation='relu'))
> decoder.add(layers.Conv2D(32, 5, strides=(1, 1), activation='relu'))
> decoder.add(layers.UpSampling2D(2))
> decoder.add(layers.Conv2D(3, 5, strides=(1, 1), activation='softmax'))
> 
> # autoencoder
> autoencoder = Model(inputs=model2.input, outputs=decoder(model2.outputs))
> autoencoder.compile(optimizer='adam', loss="categorical_crossentropy", metrics= ["accuracy"])
> earlystopping = callbacks.EarlyStopping(monitor="val_loss", mode="min", patience=5, restore_best_weights=True)
> history_autoencoder = autoencoder.fit(trainset, epochs=25, verbose=1, validation_data=(testset), callbacks=[earlystopping])
> ```
> 
> Received error:
> 
> ```
> ValueError: in user code:
> 
>     File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1021, in train_function  *
>         return step_function(self, iterator)
>     File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1010, in step_function  **
>         outputs = model.distribute_strategy.run(run_step, args=(data,))
>     File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1000, in run_step  **
>         outputs = model.train_step(data)
>     File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 860, in train_step
>         loss = self.compute_loss(x, y, y_pred, sample_weight)
>     File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 919, in compute_loss
>         y, y_pred, sample_weight, regularization_losses=self.losses)
>     File "/usr/local/lib/python3.7/dist-packages/keras/engine/compile_utils.py", line 201, in __call__
>         loss_value = loss_obj(y_t, y_p, sample_weight=sw)
>     File "/usr/local/lib/python3.7/dist-packages/keras/losses.py", line 141, in __call__
>         losses = call_fn(y_true, y_pred)
>     File "/usr/local/lib/python3.7/dist-packages/keras/losses.py", line 245, in call  **
>         return ag_fn(y_true, y_pred, **self._fn_kwargs)
>     File "/usr/local/lib/python3.7/dist-packages/keras/losses.py", line 1790, in categorical_crossentropy
>         y_true, y_pred, from_logits=from_logits, axis=axis)
>     File "/usr/local/lib/python3.7/dist-packages/keras/backend.py", line 5083, in categorical_crossentropy
>         target.shape.assert_is_compatible_with(output.shape)
> 
>     ValueError: Shapes (None,) and (None, 64, 64, 3) are incompatible
> ```

Did you solve it , because I have the same error ? :')

**Comment by MD-DILDAR-MANDAL** [comment]
can be solved by flattening  before calculating the loss to ensure same shape
