### ISSUE TITLE
Can't train when a column name is 'next'

### ISSUE THREAD

**Issue by tariqph** [keras-team/keras#16233]
So, I was training a tensorflow model using keras api and one of the column names that the dataframe had was 'next'. Running model.fit on the data threw the following error:

`RuntimeError: Data adapters should be mutually exclusive for handling inputs. Found multiple adapters [<class 'tensorflow.python.keras.engine.data_adapter.TensorLikeDataAdapter'>, <class 'tensorflow.python.keras.engine.data_adapter.GeneratorDataAdapter'>] to handle input: <class 'pandas.core.frame.DataFrame'>, <class 'pandas.core.series.Series'>`

The whole issue is recreated below:
```
import numpy as np
import pandas as pd 
from sklearn.model_selection import train_test_split
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
```
```
X = pd.read_csv('X_train_1.csv', index_col=0) # inputs of the training set
y = pd.read_csv('y_train.csv', index_col=0, squeeze = True) 
X.head()
```
Output:
![image](https://user-images.githubusercontent.com/14332590/158110934-cf8cf151-1c0c-429e-9b4e-84258a6a7edf.png)

```
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=13)
n_words = X_train.shape[1]

model = Sequential()
model.add(Dense(5, input_shape=(n_words,), activation='relu'))
model.add(Dense(1, activation='sigmoid'))
# compile network
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
# fit network
model.fit(X_train,y_train)
```
Error Traceback:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-13-73e838216e84> in <module>
      7 model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
      8 # fit network
----> 9 model.fit(X_train,y_train)

~\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\keras\engine\training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
   1048          training_utils.RespectCompiledTrainableState(self):
   1049       # Creates a `tf.data.Dataset` and handles batch and epoch iteration.
-> 1050       data_handler = data_adapter.DataHandler(
   1051           x=x,
   1052           y=y,

~\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\keras\engine\data_adapter.py in __init__(self, x, y, sample_weight, batch_size, steps_per_epoch, initial_epoch, epochs, shuffle, class_weight, max_queue_size, workers, use_multiprocessing, model, steps_per_execution)
   1097       self._steps_per_execution_value = steps_per_execution.numpy().item()
   1098 
-> 1099     adapter_cls = select_data_adapter(x, y)
   1100     self._adapter = adapter_cls(
   1101         x,

~\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\keras\engine\data_adapter.py in select_data_adapter(x, y)
    964             _type_name(x), _type_name(y)))
    965   elif len(adapter_cls) > 1:
--> 966     raise RuntimeError(
    967         "Data adapters should be mutually exclusive for "
    968         "handling inputs. Found multiple adapters {} to handle "

RuntimeError: Data adapters should be mutually exclusive for handling inputs. Found multiple adapters [<class 'tensorflow.python.keras.engine.data_adapter.TensorLikeDataAdapter'>, <class 'tensorflow.python.keras.engine.data_adapter.GeneratorDataAdapter'>] to handle input: <class 'pandas.core.frame.DataFrame'>, <class 'pandas.core.series.Series'>
```
Renaming column and training
```
X_train = X_train.rename(columns={'next': 'new_column'})
model.fit(X_train,y_train)
```
Output:
```
25/25 [==============================] - 0s 1ms/step - loss: 0.7535 - accuracy: 0.4763

<tensorflow.python.keras.callbacks.History at 0x275388cc520>
```

**Comment by tilakrayal** [comment]
@tariqph ,
Can you please take a look at this SO [link](https://stackoverflow.com/questions/60960820/data-adapters-should-be-mutually-exclusive-for-handling-inputs-tensorflow) with the similar error.Also please re-name the column and test your code.It helps.Thanks!

**Comment by tariqph** [comment]
> @tariqph , Can you please take a look at this SO [link](https://stackoverflow.com/questions/60960820/data-adapters-should-be-mutually-exclusive-for-handling-inputs-tensorflow) with the similar error.Also please re-name the column and test your code.It helps.Thanks!

Yes, renaming the column does work as I have shown in the post above. Just odd that I can't use this particular word as a column name.

**Comment by tilakrayal** [comment]
@tariqph ,
The next() function returns the next item in an iterator. You can add a default return value, to return if the iterable has reached to its end.
As suggested please try to re-name the column.It helps.Thanks!

**Comment by tariqph** [comment]
The column name change works as stated before. Does it mean that this is something to do with the implementation and column name 'next' can never be used in this context?

**Comment by tilakrayal** [comment]
@tariqph ,
As stated above next() is a function which returns the next item in an iterator.If we provide same name it will leads to ambiguity.So please provide different name which helps to resolve the issue.Thanks!
