### ISSUE TITLE
Compiling model in callback causes TypeError

### ISSUE THREAD

**Issue by dmirecki** [keras-team/keras#16234]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): yes
- TensorFlow version (use command below): 2.8.0 (2.4 too)
- Python version: 3.7

**Describe the problem**.

In a fine-tuning case I would like to do transfer-learning phase first (with fine-tuned layers frozen) and after that,  all layers should be unfrozen. I wrote a callback that unfreeze the layers after few epochs. Unfortunately, after changing the layers' `trainable` attribute, the model should be recompiled - and the recompilation causes the `TypeError` (see colab). 

I am aware that I can workaround this by compiling and fitting model twice - for both phases separately - but the usage of callback seems more elegant to me.

**Standalone code to reproduce the issue**.

https://colab.research.google.com/drive/1u6VlH6EIQGXSp7vEIngTasp3v2EE42Wi?usp=sharing

**Source code / logs**.

```
TypeError: 'NoneType' object is not callable
```

**Comment by sushreebarsa** [comment]
@jvishnuvardhan Was able to replicate the issue on colab using TF v2.8.0 and tf-nightly(2.9.0.dev20220314), please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/d1620a5f08fb4e4e8c390e6879f98ffa/untitled1.ipynb#scrollTo=eO74Q6derngV) .Thanks!

**Comment by old-school-kid** [comment]
@dmirecki 
I really like the idea of having a callback for fine-tuning rather than training again. 
But is the correct way to do is to recompile the model or to set the value of `layer.trainable` as False like [here](https://www.tensorflow.org/guide/keras/custom_callback#learning_rate_scheduling). Although this also raises an error `AttributeError: 'bool' object has no attribute 'dtype' `

**Comment by LukeWood** [comment]
interesting bug - thanks for the report.

**Comment by old-school-kid** [comment]
Is compiling the model the right way to do it or should we just use backend.set_value like we set [lr of optimizers in callbacks](https://github.com/keras-team/keras-io/blob/master/guides/writing_your_own_callbacks.py#L368).

**Comment by dmirecki** [comment]
It seems that adding `self.model.make_train_function()` indeed fixed the problem! Thanks a lot!

**Comment by GoodTekken** [comment]
您好，您的邮件已经收到 ！                   杨显洁
