### ISSUE TITLE
`batch_size` parameter for `model(x, training=True)`

### ISSUE THREAD

**Issue by Vishu26** [keras-team/keras#16241]
Hi!

When I use `model(x, training=True)` with very large sizes of x, it results in a `RESOURCE_EXHAUSTED` error.  There is no way to make the function run in a batch mode. Is it possible to implement `batch_size` parameter in this function similar as in `model.predict(x, ...)`.

**Comment by haifeng-jin** [comment]
For this case, you should batch by first wrapping it into `tf.data.Dataset` and call the `.batch()` method to batch it.
