### ISSUE TITLE
Implement all tf interpolation upscaling methods

### ISSUE THREAD

**Issue by Mahrkeenerh** [keras-team/keras#16243]
`keras.layers.UpSampling2D` right now only supports two interpolation methods.

Why not implement all possible ones found at `tf.image.ResizeMethod`?

I already have the changes ready, but the How-to-contribute suggested to create an Issue first, and only after that make the Pull request.

**Comment by tilakrayal** [comment]
@Mahrkeenerh ,
Can you please elaborate about your Feature. Also, please specify the Use Cases for this feature. Thanks!

**Comment by Mahrkeenerh** [comment]
Sure, here's the explanation:

`tf.image.resize` supports 8 different resize modes. These modes are however not available for the layer `UpSampling2D` (and maybe others, I'm not really sure about that, sorry), because they are also not available in `backend.resize_images`.

That's why I propose to implement all these other 6 modes, to make a wider choice option. Because these modes are already available in `tensorflow`, it's just a matter of altering the if-else condition.

I'll open the pull request, so it will be clear what I'm talking about.

**Comment by gadagashwini** [comment]
Fixes PR [#16249](https://github.com/keras-team/keras/pull/16249)
