### ISSUE TITLE
Silent reset_states() error in custom model 

### ISSUE THREAD

**Issue by mattiasu96** [keras-team/keras#16250]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Custom code
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Monterey 12.1
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.8
- Python version: 3.9

**Describe the current behavior**
I am developing a custom model by inheriting from the `tf.keras.Model` class, in particular I am developing a custom LSTM residual network. Following the documentation and code, if calling `model.reset_states()` on a stateless layer should trigger an exception present in the layer class (in my case LSTM). 

However, such call is obscured by a conditional statement that prevents the raising of such exception in any case (at least the one I was trying). So basically `model.reset_states()` runs silently without errors and without resetting the states. 

The following is the function present inside `tf.keras.Model` class. The conditional statement prevents the exception from `layer.reset_states()` to be raised. By manually forcing the evaluation  of `layer.reset_states()` inside a debugger, the exception is correctly raised.

```
  def reset_states(self):
    for layer in self.layers:
      if hasattr(layer, 'reset_states') and getattr(layer, 'stateful', False):
        layer.reset_states()

```

**Describe the expected behavior**
Raise the exception and make explicit whether reset_states() is called on layers that are not stateful

- Do you want to contribute a PR? (yes/no): no

**Standalone code to reproduce the issue**

```
class ResNetModel(Model):
    def __init__(self, num_inputs, **kwargs):
        """
        The class initialiser should call the base class initialiser, passing any keyword
        arguments along. It should also create the layers of the network according to the
        above specification.
        """
        super(ResNetModel, self).__init__(**kwargs)
        self.lstm_1 = tf.keras.layers.LSTM(units=32, input_shape=(None, num_inputs), return_sequences=True, stateful = False)
        self.dense = tf.keras.layers.Dense(units=1, activation=None)

    def call(self, inputs, training=False):
        """
        This method should contain the code for calling the layer according to the above
        specification, using the layer objects set up in the initialiser.
        """
        x = self.lstm_1(inputs)
        y = self.dense(x)
        return y + inputs

model = ResNetModel(1)
model.reset_states() # does not raise any errors
```

**Comment by tilakrayal** [comment]
@mattiasu96 ,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here

**Comment by mattiasurricchioprima** [comment]
I don't know if it is enough, but I have already inserted the code needed to reproduce the error

**Comment by mattiasu96** [comment]
@tilakrayal I provided the code, it is enough to reproduce the problem. Do you need something else?

**Comment by tilakrayal** [comment]
@mattiasu96 ,
I was facing different issue while executing the provided code.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/872e07677caa6070b9820f3dd5f4ead9/untitled252.ipynb).

**Comment by tilakrayal** [comment]
@gadagashwini ,
I was able to reproduce the issue in tf v2.8 and nightly.Please find the gist [here](https://colab.research.google.com/gist/tilakrayal/1f9776716737320b137331d19c50c6b6/untitled277.ipynb).

**Comment by gadagashwini** [comment]
@mattiasu96, 
`model.reset_states()`, Reset the recorded states for the stateful RNN layer.
Can only be used when RNN layer is constructed with `stateful = True`.

When i tried with LSTM
```
import tensorflow as tf
import numpy as np
paragraph1 = np.random.random((20, 10, 50)).astype(np.float32)
paragraph2 = np.random.random((20, 10, 50)).astype(np.float32)
paragraph3 = np.random.random((20, 10, 50)).astype(np.float32)

lstm_layer = tf.keras.layers.LSTM(64, stateful=False)
output = lstm_layer(paragraph1)
output = lstm_layer(paragraph2)

existing_state = lstm_layer.states

new_lstm_layer = tf.keras.layers.LSTM(64)
new_output = new_lstm_layer(paragraph3, initial_state=existing_state)
```

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-2-70371a2ff313>](https://localhost:8080/#) in <module>()
     12 
     13 new_lstm_layer = tf.keras.layers.LSTM(64)
---> 14 new_output = new_lstm_layer(paragraph3, initial_state=existing_state)

4 frames
[/usr/local/lib/python3.7/dist-packages/keras/backend.py](https://localhost:8080/#) in int_shape(x)
   1468   """
   1469   try:
-> 1470     shape = x.shape
   1471     if not isinstance(shape, tuple):
   1472       shape = tuple(shape.as_list())

AttributeError: 'NoneType' object has no attribute 'shape'
```

**Comment by mattiasu96** [comment]
> Can only be used when RNN layer is constructed with stateful = True.

Yes and I am aware of it. The problem is that in my code, I am able to call such method, without the method being actually called and without any error at all. So everything runs silently, even if it is not supposed to happen.

As mentioned in my original post this function:
```
  def reset_states(self):
    for layer in self.layers:
      if hasattr(layer, 'reset_states') and getattr(layer, 'stateful', False):
        layer.reset_states()
```
has a condition that skips completely the call of  `layer.reset_states()`. Inside `layer.reset_states()` there is a check that raises an exception if `reset_states()` is called on a stateless layer. However, such exepction is never raised because the previously showed if condition skips the execution of such function.

**Comment by qlzh727** [comment]
I think the existing API/function is working as intended. For a keras model, it shouldn't invoke a stateless layer with `reset_states()`. Note that majority of the layer in keras is not stateful (only RNN layer could be stateful), Changing this default behavior could cause errors for existing user, and force end user to write for loop to filter out the stateful layer to reset by themselves. This will pretty much make the `model.reset_states()` unusable at all.

**Comment by mattiasu96** [comment]
I agree with your idea but, calling reset_states() on a stateless RNN does not raise any warning or error/exception. Considering that inside the layer class, there is a check + exception if reset_states() is called on a layer with stateful = False, I think that such exception should be added also in the case i provided with my code

**Comment by qlzh727** [comment]
I am confused. All the rnn stateless layer dose raise exception when reset_state() is called.

https://github.com/keras-team/keras/blob/62aab556c6252e54b9f3ee3fa65243aecd6aea52/keras/layers/rnn/base_rnn.py#L767

**Comment by mattiasu96** [comment]
> I am confused. All the rnn stateless layer dose raise exception when reset_state() is called.
> 
> https://github.com/keras-team/keras/blob/62aab556c6252e54b9f3ee3fa65243aecd6aea52/keras/layers/rnn/base_rnn.py#L767

Exactly! That condition should be raised! 
However, as you might notice, no condition is raised if you run the snippet I provided. This happens because in the `Model` class inside Tensorflow there is the following wrapping function:

```
  def reset_states(self):
    for layer in self.layers:
      if hasattr(layer, 'reset_states') and getattr(layer, 'stateful', False):
        layer.reset_states()
```
That prevents the raising of the exception you mentioned; consenquently I can call `reset_states()` on a stateless layer without any warning/exception being raised.
