### ISSUE TITLE
How to save and load the constant tensor of custom layer 

### ISSUE THREAD

**Issue by ambarion** [keras-team/keras#16275]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GPU model and memory:
- Exact command to reproduce:

**Describe the problem**.

I want to save a model which contains some custom layers, especially there are some constant input tensors inside, like this

(where the GCNconv is something like https://github.com/danielegrattarola/spektral/blob/master/spektral/layers/convolutional/gcn_conv.py)

```
import GCNconv from spektral.layer
img_input = Input(shape=input_shape)
x = Conv2D(3, (3, 3), activation='relu', padding='same', name='conv1_1')(img_input)
x = Conv2D(3, (3, 3), activation='relu', padding='same', name='conv1_2')(x)
x = MaxPooling2D((2, 2), strides=(2, 2), name='pool1')(x)    # output x: (B*H*W*3)
x = Reshape(H*W, 3)     # output x: (B*(H*W)*3)

gcn = GCNConv(1024)      # The custom layer

A = tf.Variable(np.eye(3), trainable=True, shape=(3, 3), name='adj')      #The constant input tensor
y = gcn([x, A])      # Use the constant tensor
```

Then save the model use model.save() or the model.to_json(), the **serialize** method in https://github.com/tensorflow/tensorflow/blob/5dcfc51118817f27fad5246812d83e5dccdc5f72/tensorflow/python/keras/engine/node.py#L199 
will treat the input tensor **A** of the custom layer as a _CONSTANT_VALUE. This leads to the JSON saved in the format as:

```
{"class_name": "GCNConv", "config": {"name": "gcn_conv", "trainable": true, "dtype": "float32", "activation": "linear", "use_bias": false, "kernel_initializer": {"class_name": "LecunNormal", "config": {"seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": {"class_name": "L2", "config": {"l2": 0.0005000000237487257}}, "bias_regularizer": null, "kernel_constraint": null, "bias_constraint": null, "channels": 1024}, "name": "gcn_conv", "inbound_nodes": [[["reshape", 0, 0, {}], ["_CONSTANT_VALUE", -1, [[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]], {}]]]} 
```

When load the model  with model_from_json
```
model = tf.keras.models.model_from_json(loaded_model_json, custom_objects={'GCNConv': GCNConv})
```
 According to https://github.com/tensorflow/tensorflow/blob/5dcfc51118817f27fad5246812d83e5dccdc5f72/tensorflow/python/keras/engine/node.py#L181, **The _CONSTANT_VALUE  A cannot be converted back to a tf.tensor**, but will be a **List** of tensor :

```
[[<tf.Tensor: shape=(), dtype=float32, numpy=1.0>, <tf.Tensor: shape=(), dtype=float32, numpy=0.0>, <tf.Tensor: shape=(), dtype=float32, numpy=0.0>], [...], [<tf.Tensor: shape=(), dtype=float32, numpy=0.0>, <tf.Tensor: shape=(), dtype=float32, numpy=0.0>, <tf.Tensor: shape=(), dtype=float32, numpy=1.0>]]
```

Is there any way to solve the problem or bypass it?

**Describe the current behavior**.
_CONSTANT_VALUE in JSON will be deserialized into a List.

**Describe the expected behavior**.
The constant tensor can be loaded from JSON as a tf.tensor.

**Comment by ambarion** [comment]
Same problem happened when save the model into '.h5' and '.pb', maybe I need to carefully define the custom layer? Is there any guidance for that?

**Comment by tilakrayal** [comment]
@ambarion ,
Can you please take a look at this SO [link](https://stackoverflow.com/questions/62737825/how-can-i-save-a-keras-model-with-custom-layer-that-have-constant) which delivers the similar information.It helps.Thanks!
