### ISSUE TITLE
"TypeError: Reduce.update_state() got multiple values for argument 'sample_weight'" when using Mean() or Sum() metric

### ISSUE THREAD

**Issue by wellsonah2019** [keras-team/keras#16291]
System Information:

1. **Platform used:** Windows 10
2. **Tensorflow installed with** pip (pip install tensorflow), version: v2.8.0-rc1-32-g3f878cff5b6 2.8.0
3. **Python version:** 3.10.1
4. **GPU model:** RTX 3070 -- 16GB VRAM
5. **Code to reproduce:**

```
model = Sequential()

model.add(Dense(4, input_shape=(1,)))
model.add(Dense(1, ))

model.compile(optimizer='Adam', loss='binary_crossentropy', metrics=[tf.keras.metrics.Sum()]) or model.compile(optimizer='Adam', loss='binary_crossentropy', metrics=[tf.keras.metrics.Mean()])

model.fit([1], [0])
```

**Main Problem:**

This error happens whenever the Mean() or Sum() metrics are used. It does not appear when other metrics are used. I am not sure if this is not how those metrics are supposed to be used, but the fact that these 2 give errors while others do not made me believe that this is a possible issue.

**Traceback:**
```

Traceback (most recent call last):
  File "D:\OneDrive - Singapore Management University\SMU_Materials\Research Assistant - Software Testing\hdf5-grammar\grammar-error-inv.py", line 38, in <module>
    model.fit([1], [0])
  File "C:\Users\Wellson\AppData\Roaming\Python\Python310\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Wellson\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\framework\func_graph.py", line 1147, in autograph_handler
    raise e.ag_error_metadata.to_exception(e)
TypeError: in user code:

    File "C:\Users\Wellson\AppData\Roaming\Python\Python310\site-packages\keras\engine\training.py", line 1021, in train_function  *
        return step_function(self, iterator)
    File "C:\Users\Wellson\AppData\Roaming\Python\Python310\site-packages\keras\engine\training.py", line 1010, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\Wellson\AppData\Roaming\Python\Python310\site-packages\keras\engine\training.py", line 1000, in run_step  **
        outputs = model.train_step(data)
    File "C:\Users\Wellson\AppData\Roaming\Python\Python310\site-packages\keras\engine\training.py", line 864, in train_step
        return self.compute_metrics(x, y, y_pred, sample_weight)
    File "C:\Users\Wellson\AppData\Roaming\Python\Python310\site-packages\keras\engine\training.py", line 957, in compute_metrics
        self.compiled_metrics.update_state(y, y_pred, sample_weight)
    File "C:\Users\Wellson\AppData\Roaming\Python\Python310\site-packages\keras\engine\compile_utils.py", line 459, in update_state
        metric_obj.update_state(y_t, y_p, sample_weight=mask)
    File "C:\Users\Wellson\AppData\Roaming\Python\Python310\site-packages\keras\utils\metrics_utils.py", line 70, in decorated
        update_op = update_state_fn(*args, **kwargs)
    File "C:\Users\Wellson\AppData\Roaming\Python\Python310\site-packages\keras\metrics.py", line 178, in update_state_fn
        return ag_update_state(*args, **kwargs)

    TypeError: Reduce.update_state() got multiple values for argument 'sample_weight'

```
Please do let me know if the way I used the metrics are wrong, or if this is really an unintended bug.

Thanks!

**Comment by vulkomilev** [comment]
I think that maybe you are misusing the sum metric .It is summing some values .What exactly are you trying to do?

**Comment by tilakrayal** [comment]
@wellsonah2019 
In order to expedite the trouble-shooting process, could you please provide a complete code  you are using.

**Comment by wellsonah2019** [comment]
@tilakrayal

I have included the code in the main post, but for your convenience, here it is:

```
model = Sequential()

model.add(Dense(4, input_shape=(1,)))
model.add(Dense(1, ))

model.compile(optimizer='Adam', loss='binary_crossentropy', metrics=[tf.keras.metrics.Sum()]) or model.compile(optimizer='Adam', loss='binary_crossentropy', metrics=[tf.keras.metrics.Mean()])

model.fit([1], [0])
```

Hope this helps!

**Comment by tilakrayal** [comment]
@wellsonah2019 ,
I was facing different issue while executing the code.Please find the gist [here](https://colab.research.google.com/gist/tilakrayal/e8fcb3e5b4ad3cf46e03a26869f69a23/untitled272.ipynb).

**Comment by wellsonah2019** [comment]
@tilakrayal,

I saw the code that you made and I believe that you will need to import Sequential and Dense layers first before being able to run the code.


Please include this before you add the models.
```
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense
```

**Comment by tilakrayal** [comment]
@wellsonah2019 ,
Can you please take a look at this SO [link](https://stackoverflow.com/questions/68354367/getting-an-error-when-using-tf-keras-metrics-mean-in-functional-keras-api) with the similar error.It helps.Thanks!

**Comment by wellsonah2019** [comment]
@tilakrayal,

Sorry for the late reply.

I see that the fix seems plausible, I can't verify yet but it does seem like that will work. However, that essentially means that users will have to use this workaround fix to solve this issue. Is the Keras team planning to implement the fix instead so users will not encounter the issue when they first use these metrics?

Thanks

**Comment by tilakrayal** [comment]
@wellsonah2019 ,
`tf.keras.metrics.Sum()/Mean()` --> It computes the (weighted) sum/mean of the given **values**. I request to please check the workaround fix which helps to solve this issue.
Also can you please provide link of the above mentioned code which you are trying to execute.Thanks!

**Comment by wellsonah2019** [comment]
@tilakrayal 

Here is the google colab link: https://colab.research.google.com/gist/wellsonah2019/931048f5b4ada6db49b450fc227cf00f/untitled272.ipynb. I've added in the workaround and also tried running it and it works as I expected.

Please let me know if you are unable to access it.

**Comment by tilakrayal** [comment]
@wellsonah2019 ,
Glad the suggestion worked to resolve the issue.I request you to please feel free to submit a PR for the requested change or share the link where requested change is to be made.Thanks!

**Comment by wellsonah2019** [comment]
@tilakrayal,

Okay, I will try to do so. It might take a while though.

Thanks!
