### ISSUE TITLE
 Models starting from EfficientNetV2B0 and ending at EfficientNetV2L are duplicated in the table.

### ISSUE THREAD

**Issue by TrueWodzu** [keras-team/keras#16303]
**URL(s) with the issue:**.

https://keras.io/api/applications/

**Description of issue (what needs to be changed):**.

 Models starting from EfficientNetV2B0 and ending at EfficientNetV2L are duplicated in the table.

**Are you planning to also submit a pull request to fix the issue? See the [docs contributor guide](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md):**

I could but I don't know how to update docs.

**Comment by tilakrayal** [comment]
@TrueWodzu ,
The issue will move to closed status once the PR is merged.
