### ISSUE TITLE
The parameters of BERT constructed with Keras

### ISSUE THREAD

**Issue by tinyxuyan** [keras-team/keras#16302]
When I construct BERT with the [example codes](https://keras.io/examples/nlp/masked_language_modeling/ ), the parameter scale is significant larger than the values given in the BERT original paper.  Is there any difference between the tf.keras.layers.MultiHeadAttention and the original one in Transformer paper?

**Comment by gadagashwini** [comment]
@tinyxuyan, Parameter value is depends on BERT model size. 

bert-base-uncased, 110M parameters with Transformer * 12
bert-large-uncased, 340M parameters with Transformer * 24

`tf.keras.layers.MultiHeadAttention()` an implementation of multi-headed attention as described in the paper ["Attention is all you Need" (Vaswani et al., 2017)](https://arxiv.org/abs/1706.03762)

**Comment by tinyxuyan** [comment]
According to your advice, I have modified the configuration depending on the original paper. There are still some differences. The total parameters are slightly larger than the values provided by the paper.

As for the bert-base-uncased model with configuration as below: 
`class config:
    MAX_LEN = 256
    BATCH_SIZE = 32
    LR = 0.001
    VOCAB_SIZE = 30000
    EMBED_DIM = 768
    NUM_HEAD = 12  # used in bert model
    FF_DIM = 3072  # used in bert model
    NUM_LAYERS = 12`
I got total parameters 131,164,464.

As for the bert-large-uncased model with configuration as below: 
`class Config:
    MAX_LEN = 256
    BATCH_SIZE = 32
    LR = 0.001
    VOCAB_SIZE = 30000
    EMBED_DIM = 1024
    NUM_HEAD = 16  # used in bert model
    FF_DIM = 4096  # used in bert model
    NUM_LAYERS = 24`
I got total parameters 363,779,376.

**Comment by tinyxuyan** [comment]
I have found the issues by myself.
In the [BERT code](https://keras.io/examples/nlp/masked_language_modeling/), the transformer blocks are built with
layers.MultiHeadAttention(num_heads=num_heads, key_dim=embed_dim//num_heads).
In the [GPT code](https://keras.io/examples/generative/text_generation_with_miniature_gpt/), the transformer blocks are built with layers.MultiHeadAttention(num_heads=num_heads, key_dim=embed_dim).
The first method might be the accurate one to reproduce the results in the original paper, while the second method is a little misleading and will lead to a significantly larger network scale.

**Comment by gadagashwini** [comment]
@tinyxuyan,
Yes you are right.
Difference in the Parameters is due to the way MultiHeadAttention layer used

[BERT model ](https://github.com/keras-team/keras-io/blob/master/examples/nlp/masked_language_modeling.py#L261)
```
def bert_module(query, key, value, i):
    # Multi headed self-attention
    attention_output = layers.MultiHeadAttention(
        num_heads=config.NUM_HEAD,
        key_dim=config.EMBED_DIM // config.NUM_HEAD,
        name="encoder_{}/multiheadattention".format(i),
    )(query, key, value)
```

[GPT model ](https://github.com/keras-team/keras-io/blob/master/examples/generative/text_generation_with_miniature_gpt.py#L65)
```
class TransformerBlock(layers.Layer):
    def __init__(self, embed_dim, num_heads, ff_dim, rate=0.1):
        super(TransformerBlock, self).__init__()
        self.att = layers.MultiHeadAttention(num_heads, embed_dim)
```

**Comment by gadagashwini** [comment]
@tinyxuyan, Can we close this issue since its resolved. Thanks!
