### ISSUE TITLE
'Activation' object has no attribute 'kernel' applying regularization to MobileNetV3

### ISSUE THREAD

**Issue by mattpotma** [keras-team/keras#16316]
**System information**.

- Have I written custom code (as opposed to using a stock example script provided in Keras): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.7.0-rc1-69-gc256c071bb2, tf-nightly-2.9.0.dev20220325
- Python version: 3.9.70
- GPU model and memory: N/A
- Exact command to reproduce: N/A

**Describe the problem**.

Adding regularization to MobileNetV3 fails to train the model if regularization is added with `layer.add_loss(lambda: regularizer(layer.kernel))` or fails saving the model if regularization is added with `layer.add_loss(lambda l=layer: regularizer(l.kernel))`.

**Describe the current behavior**.

Attempting to add regularization to MobileNetV3. 

The regularization appears to be applied correctly (applied to 43 Conv2D and Dense layers), but calling `model.fit` fails with the error `AttributeError: 'Activation' object has no attribute 'kernel'`.

It appears that calling `model.fit` is reapplying the regularization, but on the last `layer`, which is the output Activation. Adding regularization this way works on MobileNetV2 and custom models I've built, but only fails on MobileNetV3 (small or large).

If a default argument is used in the lambda (`layer.add_loss(lambda l=layer: regularizer(l.kernel))`), I can build and train the model, but saving the model with the Saved Model API fails with `tensorflow.python.saved_model.nested_structure_coder.NotEncodableError: No encoder for object <keras.layers.convolutional.Conv2D object at 0x7f0c4083be80> of type <class 'keras.layers.convolutional.Conv2D'>.` This failure occurs with both MobileNetV2 and MobileNetV3.

**Describe the expected behavior**.

The sample script should run without fail, or at least fail similarly between MobieNetV2 and MobileNetV3.

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no):
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**.

Colab notebook (2.9.0 nightly) https://colab.research.google.com/drive/1JQxl6KyCf5vWUnFjo0qB7v_I5maMMspb#scrollTo=HAlKVbk08W3X

Standalone code:

```python
import numpy as np
import tensorflow as tf


model = tf.keras.applications.MobileNetV3Small(input_shape=(96, 96, 3))
# model = tf.keras.applications.MobileNetV2(input_shape=(96, 96, 3))
regularizer = tf.keras.regularizers.L1(1e-3)

for layer in model.layers:
    if hasattr(layer, "kernel"):
        layer.add_loss(lambda: regularizer(layer.kernel))  # Fails building V3
        # layer.add_loss(lambda l=layer: regularizer(l.kernel))  # Fails saving SavedModel all versions

# Ensure regularization only applied to Conv2D or Dense layers
regularization_count = 0
for layer in model.layers:
    if layer.losses:
        regularization_count += 1
        assert isinstance(layer, tf.keras.layers.Conv2D) or isinstance(layer, tf.keras.layers.Dense)
        assert not isinstance(layer, tf.keras.layers.Activation)

print(f"Regularization added to {regularization_count} layers")

model.compile(loss="mse")
model.fit(
    np.random.randn(10, 96, 96, 3),
    np.random.randn(10, 1000),
)
model.save("test")
```

**Source code / logs**.

Traceback from Colab notebook:

```
WARNING:tensorflow:`input_shape` is undefined or non-square, or `rows` is not 224. Weights for input shape (224, 224) will be loaded as the default.
Downloading data from https://storage.googleapis.com/tensorflow/keras-applications/mobilenet_v3/weights_mobilenet_v3_small_224_1.0_float.h5
10734624/10734624 [==============================] - 0s 0us/step
Regularization added to 43 layers

---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

[<ipython-input-3-0ea365886076>](https://localhost:8080/#) in <module>()
     23 model.fit(
     24     np.random.randn(10, 96, 96, 3),
---> 25     np.random.randn(10, 1000),
     26 )

2 frames

[<ipython-input-3-0ea365886076>](https://localhost:8080/#) in <lambda>()
      8 for layer in model.layers:
      9     if hasattr(layer, "kernel"):
---> 10         layer.add_loss(lambda: regularizer(layer.kernel))
     11 
     12 # Ensure regularization only applied to Conv2D or Dense layers

AttributeError: in user code:

    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1051, in train_function  *
        return step_function(self, iterator)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1040, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1030, in run_step  **
        outputs = model.train_step(data)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 890, in train_step
        loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 949, in compute_loss
        y, y_pred, sample_weight, regularization_losses=self.losses)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/base_layer.py", line 1268, in losses
        loss_tensor = regularizer()
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/base_layer.py", line 1342, in _tag_callable
        loss = loss()
    File "<ipython-input-3-0ea365886076>", line 10, in <lambda>
        layer.add_loss(lambda: regularizer(layer.kernel))

    AttributeError: 'Activation' object has no attribute 'kernel'
```

**Comment by mattpotma** [comment]
I've found two more caveats of this.

First, with MobileNetV2, if I add regularization to the DepthwiseConv2D layers using this,

```python
if hasattr(layer, "depthwise_kernel"):
    layer.add_loss(lambda: regularizer(layer.depthwise_kernel))
```

then training fails with the error `AttributeError: 'Dense' object has no attribute 'depthwise_kernel'`. So the regularization being applied to the wrong layer once training begins is not unique to MobileNetV3, but rather seems to only happen in select cases. This method of adding regularization is straight from your documentation here https://www.tensorflow.org/api_docs/python/tf/keras/layers/Layer#example_3


Second, if I add the regularization using the lambda default; e.g.

```python
if hasattr(layer, "kernel"):
    layer.add_loss(lambda l=layer: regularizer(l.depthwise_kernel))
```

and export the model to TFLite using `tf.lite.TFLiteConverter.from_keras_model`, calling `get_signature_details()` returns an empty dictionary and the output name is `Identity` rather than `StatefulPartitionedCall:0`. It seems like exporting is falling back to an older version of the TFLite exporter.

I can provide code examples of either of these if requested.

**Comment by sushreebarsa** [comment]
@gadagashwini I was able to reproduce the issue on colab using TF v2.8.0 and tf-nightly(2.9.0.dev20220329), please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/3d2008febc1334e90c26bdc4a94dea27/16316.ipynb#scrollTo=Jm34f515X791).Thanks!

**Comment by LukeWood** [comment]
Interesting bug - thanks for reporting this!

**Comment by qlzh727** [comment]
I think there is a bug in the client side code. Notably the lambda function. Note that lambda function created in the loop need to properly bind to the param it need, otherwise it will just bind to the first value it sees (eg in this case, the activation layer, which doesn't have a kernel).

If you need a lazy evaluate the function, you can do something like below, which probably define the variable within its scope.

```
def create_regularization_loss(weights, regularizer):
  return lambda: regularizer(weights)

for layer in model.layers:
    if hasattr(layer, "kernel"):
        layer.add_loss(create_regularization_loss(layer.kernel, regularizer)) 
```

**Comment by qlzh727** [comment]
Also see more details about lambda function in a loop. 

https://stackoverflow.com/questions/19837486/lambda-in-a-loop
