### ISSUE TITLE
Tokenizer fit from drive

### ISSUE THREAD

**Issue by chelove4draste** [keras-team/keras#16312]
Hello, I tried to make a model using keras tokenizer. I wanted to tokenize large text dataset and found this problem: using custom generator takes a lot of time (more than 10 hours) to tokenize (
```
def author_func():
    xf = ""
    for i in tqdm.tqdm(files, leave=False):
        textek = pd.read_json(i, encoding='ISO-8859-2')
        authorx = textek[['text']]
        xf = ""
        #yield np.ndarray.tolist(authorx.values)
        z = np.ndarray.tolist(authorx.values)
        print(type(z[0][0]))
        #for j in tqdm.tqdm(z, leave=False):
            #xf += str(j)
            
        yield xf
```
)
while just loading to memory and tokenizing takes around 5-7 minutes. 
```
author = []
for i in tqdm.tqdm(files[0:1]):
    textek = pd.read_json(i, encoding='ISO-8859-2') 
    authorx = textek[["text"]]
    author = author + np.ndarray.tolist(authorx.values)
```
Expected behaviour of new feature:
tokenizer.fit_from_file("filename.txt")
training for around 5-7 minutes and finished

**Comment by tilakrayal** [comment]
@chelove4draste ,
In order to expedite the trouble-shooting process, could you please provide a complete code and the TensorFlow version you are using.
