### ISSUE TITLE
Add ConvNeXt family of models to keras.applications

### ISSUE THREAD

**Issue by sayakpaul** [keras-team/keras#16321]
**Describe the feature and the current behavior/state**.

ConvNeXt [1] family of models doesn't use attention or any new components for that but still achieves really good performance on ImageNet-1k while being efficient. They also demonstrate good performance on a variety of downstream tasks. 

ConvNeXt family of models was trained using recipes used for training Vision Transformer-based models. Another point to note is that these models were evolved to simulate the design choices of Swin Transformers [2]. 

**Will this change the current api? How?**

Yes:

```
keras.applications.ConvNeXtBase, keras.applications.ConvNeXtTiny, ...
```

**Who will benefit from this feature?**

Keras users using `keras.applications` in their projects. 

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**

- Do you want to contribute a PR? (yes/no): Yes
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing): I have implemented the non-isotropic ConvNeXt variants [here](https://github.com/sayakpaul/ConvNeXt-TF) (with all the original pre-trained params ported). I also co-contributed the TF variant of this to Hugging Face `transformers` (https://github.com/huggingface/transformers/pull/15750).

## References

[1] https://arxiv.org/abs/2201.03545
[2] https://arxiv.org/abs/2103.14030

@fchollet @LukeWood

**Comment by hertschuh** [comment]
Hi Sayak, this looks like a great addition. Would you be willing to put up a PR for this?

**Comment by sayakpaul** [comment]
Thanks. I think the following answers your question :)

> Do you want to contribute a PR? (yes/no): Yes

**Comment by LukeWood** [comment]
Sweet - yes we are happy to take this, and we can take it in keras.applications.  Cheers @sayakpaul and thanks!

**Comment by sayakpaul** [comment]
Alright! I will get started as soon as I can then.

**Comment by sayakpaul** [comment]
Join the conversation here: https://github.com/keras-team/keras/pull/16421.
