### ISSUE TITLE
Module Not Found Error with ResNet50

### ISSUE THREAD

**Issue by Saxingh** [keras-team/keras#16345]
Hi! I am trying to use ResNet50 for damage classification of buildings from images however I cannot get the ResNet to load. I am using the code below to call for ResNet.

`import numpy as np
import tensorflow as tf
import keras
import ast
from keras import Sequential
from keras.layers import Conv2D, MaxPooling2D, Dense, Flatten, Add, Input, Concatenate
from keras.models import Model
from keras.applications.resnet50 import ResNet50
from keras import backend as K

from model import *`

I have also followed other suggestions and tried...

`from tensorflow.keras.applications.resnet50 import ResNet50`
as well as...

`import tensorflow.keras.applications'
'from tensorflow.keras.applications.resnet import ResNet50`

However I keep getting the following error...

`    from keras.applications.resnet50 import ResNet50
ModuleNotFoundError: No module named 'keras.applications.resnet50'` (note: this changes depending on if tensorflow. ... is used or not)

In addtion I have also checked CUDA and the %PATH% and Microsot visual studio 2015, '17 and '19 are installedand up to date.

Below is my system information and versions:
Windows 11 running miniconda3 ver., 4.12.0
Nvidia RTX3060 6GB

Python 3.9.11
PIP 21.2.4
Keras 2.8.0
Tensorflow 2.8.0

Any help or suggestions is welcomed!

**Comment by tilakrayal** [comment]
@Saxingh ,
I tried to execute the mentioned code and haven't faced any issue.Please find the gist [here](https://colab.research.google.com/gist/tilakrayal/8969d9819195fcd9d9ea7a4405c8a886/untitled286.ipynb).Also i request you please build tensorflow from [source](https://www.tensorflow.org/install) for respective dependencies and test your code.Thanks!

**Comment by Saxingh** [comment]
Thank you for your help but I think I'm going to close this.
I couldnt seem to install from source so I've switched to using google colab which seems to be working fine.
