### ISSUE TITLE
RegNets in next release?

### ISSUE THREAD

**Issue by AdityaKane2001** [keras-team/keras#16365]
**System information**.

TensorFlow version (you are using): 2.8
Are you willing to contribute it (Yes/No) : Yes

**Describe the feature and the current behavior/state**.

RegNets were incorporated in `keras.applications` in #15702. However, they are still in nightly and not in the release version of the Keras. It would be awesome to see them in the main module. 

**Will this change the current api? How?**

`tf.keras.applications.regnet.*` and `tf.keras.applications.RegNet*` will be in main release.

**Who will benefit from this feature?**

All Keras users.

**Comment by fchollet** [comment]
Can you check whether they're in the Keras 2.9 RC? I believe they should be.

**Comment by AdityaKane2001** [comment]
@fchollet 

Thanks for the response. No, they are not in the RC. That's the reason I raised the issue. 

Also I have not generated the metrics as in the other models. Please take a look at https://github.com/keras-team/keras/issues/15895 for the discussion.

**Comment by AdityaKane2001** [comment]
@fchollet 

Just want to point out that since [my PR](https://github.com/keras-team/keras/pull/15702) was technically never merged (if I'm not wrong Matt [merged it internally](https://github.com/keras-team/keras/commit/dd73626ab544768060ce38f4a2b35db468fcd2be) and the changes were pushed to public repo), it didn't make it to the [2.8.0 RC0 PR list](https://github.com/keras-team/keras/releases/tag/v2.9.0-rc0) either.

**Comment by fchollet** [comment]
@AdityaKane2001 I checked and I do see the new applications in the RC. They will be part of the 2.9.0 release.

> https://github.com/keras-team/keras/pull/15702 was technically never merged (if I'm not wrong Matt [merged it internally](https://github.com/keras-team/keras/commit/dd73626ab544768060ce38f4a2b35db468fcd2be) and the changes were pushed to public repo)

Right, any PR that adds new APIs requires additional work on our end and has to be merged internally first. Normally this works just the same as a regular PR merge, but this case it seems there was some kind of anomaly that caused the PR to be orphaned. I've seen it happen a couple times, not sure what causes it.

**Comment by fchollet** [comment]
PS: you can `pip install tensorflow==2.9.0rc0` to install the 2.9 version.

**Comment by AdityaKane2001** [comment]
@fchollet 

Thanks a lot for the response. Really appreciate you taking a look during the holiday weekend. 

> Normally this works just the same as a regular PR merge, but this case it seems there was some kind of anomaly that caused the PR to be orphaned. I've seen it happen a couple times, not sure what causes it.

I see.

Thanks for sorting this out. Please do let me know if there's anything to be done from my side (#15895).
