### ISSUE TITLE
Failure to define the specific shape of a Graph when using the Keras.layers.Input to define the input of a model

### ISSUE THREAD

**Issue by zzzy0828** [keras-team/keras#16381]
The exact shape a graph built by myself is:
Graph(n_nodes=6, n_node_features=7, n_edge_features=None, n_labels=None) (based on Spektral)
So how can I define the specific shape of it when using the Keras.layers.Input?
input1 = **Input(shape=(????))**
output1 = spektral.layers.GCNConv(channels=64, activation='relu')(input1)
output1 = spektral.layers.GCNConv(channels=32, activation='relu')(output1)
...
That's the core problem confusing me for few days.
Expecting for you future applies. Thank you!

**Comment by tilakrayal** [comment]
@zzzy0828 ,
Can you please elaborate about your Feature. Also, requesting you to please specify the Use Cases for this feature. Thanks!
