### ISSUE TITLE
[Contributors Wanted] A data loading utility for audio files

### ISSUE THREAD

**Issue by fchollet** [keras-team/keras#16383]
We would like to add an audio file loading utility to `keras.utils`, similar to the existing [`image_dataset_from_directory `](https://keras.io/api/data_loading/image/#imagedatasetfromdirectory-function) and [`text_dataset_from_directory `](https://keras.io/api/data_loading/text/#text_dataset_from_directory-function).

The signature would be identical as those of the two above utilities, with two audio-specific arguments:

```python
# Available at keras.utils.audio_dataset_from_directory
def audio_dataset_from_directory(
    directory,
    labels="inferred",
    label_mode="int",
    class_names=None,
    batch_size=32,
    sampling_rate=None,  # For audio subsampling
    output_sequence_length=None,  # If ragged=False, will truncate/pad to this length (defaults to the max sequence length in the current batch)
    ragged=False,  # Whether to return RaggedTensor sequences as output (so each sequence could have a different length)
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    follow_links=False,
)
```

The audio-specific arguments would be:

```
    sampling_rate=None,
    output_sequence_length=None,
```

The utility would load `wav` files specifically, via `tf.audio.decode_wav()`.

The code would live in `keras/utils/audio_dataset.py` and would leverage the functionality from `keras/utils/dataset_utils.py`. The code of `text_dataset_from_directory` can be used as a reference for code factoring.

If interested, please open a draft PR!

Also, if you're a potential user of this functionality and you have suggestions regarding the function signature, please post here.

**Comment by palash247** [comment]
I would like to work on this.

**Comment by fchollet** [comment]
@palash247 awesome, thanks! Please open a PR :)

**Comment by bhack** [comment]
This has not the behaviour complexity of `*_dataset_from_directory" APIs  but it could be inspiring and it already support many more audio formats (and pre-processing) then TF-Core "wav" ops:

https://www.tensorflow.org/io/api_docs/python/tfio/audio/AudioIODataset

**Comment by fchollet** [comment]
This has now been implemented! 👍

**Comment by bhack** [comment]
Only for WAV right?
