### ISSUE TITLE
Allow RandomCrop layer to crop at different locations

### ISSUE THREAD

**Issue by zaccharieramzi** [keras-team/keras#16399]
**System information**.

TensorFlow version (you are using): 2.8
Are you willing to contribute it (Yes/No) : Yes

**Describe the feature and the current behavior/state**.

It would be nice to have the possibility in [`keras.layers.RandomCrop`](https://www.tensorflow.org/api_docs/python/tf/keras/layers/RandomCrop) to crop in different locations for a given image batch.

**Will this change the current api? How?**

It should change the current api, adding an extra flag to the `RandomCrop` layer, like `different_locations`.

**Who will benefit from this feature?**

If you want `RandomCrop` as part of your data augmentation pipeline, for example to reproduce [this PyTorch script](https://github.com/kuangliu/pytorch-cifar/blob/master/main.py), you need to use it before batching.

I think this could be inefficient, as batched operations should be faster.

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**

- Do you want to contribute a PR? (yes/no): I might not have the time right now, but in the long run yes
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing): Right now, I can't think of anything better than looping...

**Comment by zaccharieramzi** [comment]
Sure thing!

So in the [`RandomCrop` doc](https://www.tensorflow.org/api_docs/python/tf/keras/layers/RandomCrop), it says:
> The layer will crop all the images in the same batch to the same cropping location.

Ideally, when using random crop for data augmentation you would like to have a different cropping location for each image in the batch to obtain diversity.
Therefore, it would be nice to have the possibility to specify that behavior.

In a data pipeline for example, it is always possible to do something like:
```python
augmented_batched_dataset = dataset.map(RandomCrop(...)).batch(batch_size)
```

But it would be more efficient to do:
```python
augmented_batched_dataset = dataset.batch(batch_size).map(RandomCrop(..., different_locations=True))
```

This is especially true since the augmentation bit will generally not consist only of the `RandomCrop` layer.

**Comment by LukeWood** [comment]
In the near future KerasCV will be offering a `RandomlyResizedCrop` layer that will operate on an image-wise basis.  To get this behavior, you may use that layer and set the resize factor to 0.  This will give the behavior you are looking for.

**Comment by LukeWood** [comment]
We have double checked this @zaccharieramzi and actually in the newest version of Keras this will be the default behavior for RandomCrop!  Thanks

**Comment by zaccharieramzi** [comment]
Cool this makes a lot more sense.

Thanks!
