### ISSUE TITLE
Strange behaviour of model.predict

### ISSUE THREAD

**Issue by itmo153277** [keras-team/keras#16397]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- TensorFlow installed from (source or binary): provided
- TensorFlow version (use command below): 2.8.0
- Python version: 3.7
- Bazel version (if compiling from source):
- GPU model and memory: no
- Exact command to reproduce:

**Describe the problem**.

Prediction for models with structured output sometimes fails on tf datasets with static shapes when `steps_per_execution` is greater than one. The error message is not descriptive.

After a successful prediction, the predictions that were failing don't fail anymore.

**Describe the current behavior**.

Prediction fails with  `'outputs' has shape <...> before the loop, but shape <...> after one iteration`

**Describe the expected behavior**.

Either a consistent successful execution or a meaningful error message.

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no): no
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**.

Example notebook: https://colab.research.google.com/gist/itmo153277/d921710f4876f3883da3b37dc7122599/testpredict.ipynb

**Source code / logs**.

See notebook above

**Comment by itmo153277** [comment]
After looking into the issue more deeply, I found out that the loop options are set incorrectly inside predict function

Currently, keras sets the option per tensor from flatten structure:
```py
          tf.autograph.experimental.set_loop_options(
              shape_invariants=[(
                  t, tf_utils.get_tensor_spec(t, dynamic_batch=True).shape)
                                for t in tf.nest.flatten(outputs)])
```

However, autograph seems to be expecting options for the structure as a whole, e.g.
```py
          tf.autograph.experimental.set_loop_options(
              shape_invariants=[(
                  outputs, tf.nest.map_structure(
                      lambda t: tf_utils.get_tensor_spec(t, dynamic_batch=True).shape,
                      outputs)
          )])
```

**Comment by sushreebarsa** [comment]
@itmo153277 This issue will be closed once the PR is merged.
Thank you!
