### ISSUE TITLE
Early stopping halts training after second epoch with default patience

### ISSUE THREAD

**Issue by mogeid** [keras-team/keras#16393]
The `EarlyStopping` callback monitors the number of epochs without improvement through the `wait` attribute.
Whenever there is improvement, this value is set to zero; when there is not, it is incremented by one.
However, the `patience` attribute of `EarlyStopping` objects is set to zero by default.
This means that the condition `self.wait >= self.patience` in [this line](https://github.com/keras-team/keras/blob/d8fcb9d4d4dad45080ecfdd575483653028f8eda/keras/callbacks.py#L1866) is always verified.
This triggers `EarlyStopping` after two epochs regardless of improvement when using the default patience.

**Comment by sushreebarsa** [comment]
@mogeid 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by mogeid** [comment]
@sushreebarsa  I suppose a minimal working example could look something like this:
```python
import numpy as np
from tensorflow.keras import Model, Input
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping

inp = Input(shape=(32,))
out = Dense(1)(inp)
model = Model(inp, out)
model.compile(loss='mse', optimizer='sgd')
x = np.random.rand(512, 32)
y = x.max(-1)**2 - x.min(-1)
early_stopping = EarlyStopping(monitor='loss', patience=0, verbose=1, mode='min')
model.fit(x, y, shuffle=True, epochs=10, callbacks=[early_stopping])

#Epoch 1/10
#16/16 [==============================] - 0s 611us/step - loss: 0.0926
#Epoch 2/10
#16/16 [==============================] - 0s 769us/step - loss: 0.0879
#Epoch 00002: early stopping

```
Note the stopping despite the improvement in the monitored quantity.

**Comment by sushreebarsa** [comment]
@gowthamkpr I was able to replicate the issue on colab using TF v2.8.0 ,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/7ccaaeaca9ebb2928fb10386540c885d/16393.ipynb) for reference.Thanks!

**Comment by gowthamkpr** [comment]
@mogeid Thank you for reporting the bug. I created a PR to fix it.

**Comment by hertschuh** [comment]
@mogeid Can you add a unit test exercising this new condition? Thanks!

**Comment by tilakrayal** [comment]
@mogeid,
I tried to execute the mentioned code on both tensorflow **v2.8** and also the latest stable **v2.12**. Please find the difference between the outputs. 

When I try to execute with v2.8, after epoch2 the execution was stopped, whereas with v2.12 the code was executed with the mentioned epochs. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/92fc05aa7789905eae19bff3283f4ac4/untitled1131.ipynb).  Thank you!
