### ISSUE TITLE
The vocabulary_size method of preprocessing layers does not work in graph mode

### ISSUE THREAD

**Issue by foxik** [keras-team/keras#16453]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): **yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Colab**
- TensorFlow installed from (source or binary): **binary**
- TensorFlow version (use command below): **TF 2.8, nightly 2.10.0-dev20220422**

**Describe the problem**.

Using the `vocabulary_size()` method of preprocessing layers (like `tf.keras.layers.StringLookup`) fails in graph mode, because the implementation looks like this: https://github.com/keras-team/keras/blob/aea9728313bcaa8262774699c21976288171b209/keras/layers/preprocessing/index_lookup.py#L346-L352

**Describe the current behavior**.

Calling `vocabulary_size()` in graph mode fails.

**Describe the expected behavior**.

Calling `vocabulary_size()` in graph mode succeeds and returns a `tf.Tensor` with the size.

**Standalone code to reproduce the issue**.

Colab notebook showing the issue is at https://colab.research.google.com/drive/1Mq9G8eUvNLw6ykk4ARKf6jurLREAvRhu?usp=sharing both for TF 2.8 and TF nightly.

**Source code / logs**.

An obvious fix is to avoid using the `numpy()` method when in graph mode, i.e., instead of
```python
return int(self.lookup_table.size().numpy()) + self._token_start_index()
```
use just
```python
return self.lookup_table.size() + self._token_start_index()
```
Note that the above notebook also shows that this implementation works in the graph mode.

**Comment by tilakrayal** [comment]
@foxik ,
The PR has been assigned for reviewing and once it is merged this issue will move to closed status.Thanks!
