### ISSUE TITLE
Cannot use Model.fit with loaded TF SavedModel

### ISSUE THREAD

**Issue by Ark-kun** [keras-team/keras#16451]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras):
- OS Platform and Distribution: Linux Ubuntu
- TensorFlow installed from: pip
- TensorFlow version: 2.7.0
- Python version: 3.7

**Describe the problem**.

I'm writing a training component function. The function receives SavedModel dir path and a training dataset CSV file path and should train the model on the training dataset.
However some of the TF SavedModels refuse to be loaded and trained by Keras.

**Describe the current behavior**.

>ValueError: Unable to create a Keras model from this SavedModel. This SavedModel was created with `tf.saved_model.save`, and lacks the Keras metadata.Please save your Keras model by calling `model.save`or `tf.keras.models.save_model`.

**Describe the expected behavior**.

I expect that there is a way to use `Model.fit` on any loaded `SavedModel`.

```python
def train_model_using_Keras_on_CSV(
    training_data_path: InputPath("CSV"),
    model_path: InputPath("TensorflowSavedModel"),
    trained_model_path: OutputPath("TensorflowSavedModel"),
    label_column_name: str,
    loss_function_name: str = "mean_squared_error",
    number_of_epochs: int = 1,
    learning_rate: float = 0.1,
    optimizer_name: str = "Adadelta",
    optimizer_parameters: dict = None,
    batch_size: int = 32,
    metric_names: list = None,
    random_seed: int = 0,
):
    import tensorflow as tf
    tf.random.set_seed(seed=random_seed)

    # Loading model using Keras. Model loaded using TensorFlow does not have .fit.
    #model = tf.saved_model.load(export_dir=model_path)
    keras_model = tf.keras.models.load_model(filepath=model_path)

    print("Model:")
    print(keras_model.to_yaml())
    #print(f"Model has {len(model.trainable_variables)} trainable variables: " + ", ".join([v.name for v in model.trainable_variables[:5]]) + ", ...")

    optimizer_parameters = optimizer_parameters or {}
    optimizer_parameters["learning_rate"] = learning_rate
    optimizer_config = {
        "class_name": optimizer_name,
        "config": optimizer_parameters,
    }
    optimizer = tf.keras.optimizers.get(optimizer_config)
    loss = tf.keras.losses.get(loss_function_name)

    training_dataset = tf.data.experimental.make_csv_dataset(
        file_pattern=training_data_path,
        batch_size=batch_size,
        label_name=label_column_name,
        header=True,
        # Need to specify num_epochs=1 otherwise the training becomes infinite
        num_epochs=1,
        shuffle=True,
        shuffle_seed=random_seed,
        ignore_errors=True,
    )
    def stack_feature_batches(features_batch, labels_batch):
        # Need to stask individual feature columns to create a single feature tensor
        # Need to cast all column tensor types to float to prevent error:
        # TypeError: Tensors in list passed to 'values' of 'Pack' Op have types [int32, float32, float32, int32, int32] that don't all match.
        list_of_feature_batches = list(tf.cast(x=feature_batch, dtype=tf.float32) for feature_batch in features_batch.values())
        return tf.stack(list_of_feature_batches, axis=-1), labels_batch

    training_dataset = training_dataset.map(stack_feature_batches)

    # Need to compile the modle to prevent error:
    # ValueError: No gradients provided for any variable: [..., ...].
    keras_model.compile(
        optimizer=optimizer,
        loss=loss,
        metrics=metric_names,
    )
    keras_model.fit(
        training_dataset,
        epochs=number_of_epochs,
    )
    # Saving the model in TensorFlow SavedModel format
    # Note: The tf.saved_model.save method creates the directory automatically
    tf.saved_model.save(keras_model, trained_model_path)
```

**Comment by vulkomilev** [comment]
Can you post the saved model ?

**Comment by tilakrayal** [comment]
Hello @Ark-kun ,
Looks like code is incomplete. Request you to please provide complete code to reproduce the issue in our environment. It helps us in localizing the issue faster.Thanks!

**Comment by Ark-kun** [comment]
> Can you post the saved model ?

I've attached the model (zipped).
[TFKerasSavedModel.zip](https://github.com/keras-team/keras/files/8606630/TFKerasSavedModel.zip)

Trying to load this model using `tf.keras.models.load_model` fails in tf v2.7.1

I'm not sure you really need this file. The error seems to be by design. But I'm questioning the design. The TF SavedModel should be a stable standard, but right now it seems to be fragmented with incompatible versions.

**Comment by gowthamkpr** [comment]
@Ark-kun Please go through this [document](https://keras.io/api/models/model_saving_apis/)  which explains the difference between `tf.saved_model.save()` and `model.save()`

Keras SavedModel (model.save()) uses [tf.saved_model.save](https://www.tensorflow.org/api_docs/python/tf/saved_model/save) to save the model and all trackable objects attached to the model (e.g. layers and variables). The model config, weights, and optimizer are saved in the SavedModel. Additionally, for every Keras layer attached to the model, the SavedModel stores:

* the config and metadata -- e.g. name, dtype, trainable status * traced call and loss functions, which are stored as TensorFlow subgraphs.

The traced functions allow the SavedModel format to save and load custom layers without the original class definition.
