### ISSUE TITLE
WARNING:absl:Found untraced functions such as [...]

### ISSUE THREAD

**Issue by mhorlacher** [keras-team/keras#16469]
I run into the above warning when saving sub-classed models with `model.save()`. 

After some investigation, the error seems to occur when using sub-classed layers in combination with sub-classed models. 

See the code below for a minimal example: 

```
import tensorflow as tf

class CustomLayer(tf.keras.layers.Layer):
    def __init__(self, units=2):
        super(CustomLayer, self).__init__()

        self.units = units

        self.layer = tf.keras.layers.Dense(units)

    def get_config(self):
        config = super(CustomLayer, self).get_config()
        config['units'] = self.units

        return config

    def call(self, x, **kwargs):
        x = self.layer(x)
        return x


class CustomModel(tf.keras.Model):
    def __init__(self, hidden_units):
        super(CustomModel, self).__init__()
        self.hidden_units = hidden_units
        self.dense_layers = [CustomLayer(u) for u in hidden_units]

    def call(self, inputs):
        x = inputs
        for layer in self.dense_layers:
            x = layer(x)
        return x

    def get_config(self):
        return {"hidden_units": self.hidden_units}

    @classmethod
    def from_config(cls, config):
        return cls(**config)


model = CustomModel([16, 16, 10])
print(model(tf.random.uniform((1, 5))).shape)
model.compile()
model.save("my_model", )
print('---')
loaded_model = tf.keras.models.load_model('my_model')
```

Or check out this [gist](https://colab.research.google.com/gist/mhorlacher/e172e2dc8ec10fc790cf1c3fa1931e8a/untitled8.ipynb).

My TF version is `2.8.0`.

**Comment by mhorlacher** [comment]
This issue as also been discussed here: https://github.com/tensorflow/models/issues/10562

**Comment by saberkun** [comment]
@qlzh727

**Comment by qlzh727** [comment]
@k-w-w for saving related qustion.

**Comment by qlzh727** [comment]
Also the warnings a bit weird that it contains layer name like dense_4_layer_call_fn, whereas there are only 3 layers in the model. It seems that there are duplicated tf.functions being created and somehow discarded.

**Comment by mhorlacher** [comment]
@qlzh727 Do you observe this after re-starting the runtime? The exact warning I get is: 

```
WARNING:absl:Found untraced functions such as dense_layer_call_fn, dense_layer_call_and_return_conditional_losses, dense_1_layer_call_fn, dense_1_layer_call_and_return_conditional_losses, dense_2_layer_call_fn while saving (showing 5 of 6). These functions will not be directly callable after loading.
```

Which makes sense IMO, as the model has 3 dense layers.

**Comment by gadagashwini** [comment]
I could able to reproduce the issue, please take a look at [gist](https://colab.research.google.com/drive/1LuNdGlQ2XdlCNyua_araGr6RYrwhiHPm?usp=sharing). 
Similar issue opened on Tensorflow repo [#47554](https://github.com/tensorflow/tensorflow/issues/47554). Thanks!

**Comment by mhorlacher** [comment]
Any updates on this?

**Comment by jenabesaman** [comment]
I have same issue and when I load the saved model then my predicts become randomly or uncorrected
I search for this issue hole the web but I didn't get any answer

**Comment by mhorlacher** [comment]
@jenabesaman This warning can probably be ignored, as it appears even in guides on the official Tensorflow website, e.g. https://www.tensorflow.org/text/tutorials/text_generation. Still, it would be great if someone could have a closer look at this.

**Comment by juemrami** [comment]
Anyway to suppress the warning then. I'm seeing it every time Keras saves a model at a checkpoint. rather annoying

**Comment by SuryanarayanaY** [comment]
Hi @mhorlacher ,
The warnings that you are getting can be safely ignored.AFAIK It should not be problem if the saved model reloads without error.Please find the attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/e046643fc7c78a7570ba0ed74fb3a4ee/16469-keras-bug_warning_absl_found_untraced_functions.ipynb) where reloading does not change Model architecture or Parameters.

You can also find such warning in Tensorflow text [Tutorial](https://www.tensorflow.org/text/tutorials/text_generation) which are safely ignored.You can refer [groups.google](https://groups.google.com/g/tensorflow-compression/c/ukHiz5ULRK8) and [SO](https://stackoverflow.com/questions/65697623/tensorflow-warning-found-untraced-functions-such-as-lstm-cell-6-layer-call-and) also which supports Ignoring this warning.You can also disable the warnings as mentioned in the above comment.

Thank you!

**Comment by BukenyaLukman** [comment]
I am getting the same issue here. Tensorflow 3+

**Comment by JuLieAlgebra** [comment]
Same, tensorflow 3.11
