### ISSUE TITLE
image_dataset_from_directory cannot load JPG images into shape (w, h, 4)

### ISSUE THREAD

**Issue by CaptainDario** [keras-team/keras#16473]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.8
- Python version: 3.8
- GPU model and memory: not relevant
- Exact command to reproduce:
``` python
dataset = tf.keras.preprocessing.image_dataset_from_directory(
    PATH,
    labels="inferred",
    label_mode="categorical",
    interpolation="bilinear",
    color_mode="rgba",
    batch_size=bs,
    image_size=img_size,
    shuffle=True,
    seed=123,
)
```

**Describe the problem**.

I have a dataset with PNG and JPG images. I want to load all of them with shape (256, 256, 4)
The documentation states:
> color_mode: One of "grayscale", "rgb", "rgba". Default: "rgb". Whether the images will be **converted** to have 1, 3, or 4 channels.

From which, one would assune that JPGs will be **converted** to have an alpha channel.

**Describe the current behavior**.
``` python
  (0) INVALID_ARGUMENT:  JPEG does not support 4 channels
	 [[{{node decode_image/DecodeImage}}]]
	 [[IteratorGetNext]]
	 [[IteratorGetNext/_4]]
```

**Describe the expected behavior**.
The images should be loaded with shape (width, height, 4) or the documentation should be more concise.

**Standalone code to reproduce the issue**.

``` python
import tensorflow as tf

dataset = tf.keras.preprocessing.image_dataset_from_directory(
    PATH,
    labels="inferred",
    label_mode="categorical",
    interpolation="bilinear",
    color_mode="rgba",
    batch_size=bs,
    image_size=img_size,
    shuffle=True,
    seed=123,
)

imgs, lbs = [], []
for images, labels in dataset.take(1):
    for img, label in zip(images, labels):
        imgs.append(img.numpy())
        lbs.append(label.numpy())
        
print(imgs[0].shape)
plt.imshow(imgs[0].astype(np.float64), cmap="gray")
```

**Comment by sushreebarsa** [comment]
@CaptainDario I tried to replicate the issue with the provided code on colab , could you please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/7087f395e8e13f9008c4de8755643a69/16473.ipynb),and confirm the same?
Thanks!

**Comment by CaptainDario** [comment]
@sushreebarsa I updated your gist to be executable and also raise the exception I mentioned.

**Comment by sushreebarsa** [comment]
@gowthamkpr I was able to replicate the issue , please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/34606b9632b715da6bab7996a1b1ff05/16473.ipynb#scrollTo=WyaGSToM0QPI) for reference.
Thank you!

**Comment by CaptainDario** [comment]
@gowthamkpr I know this and my current work around is to convert all images manually.
Howeber, as written in my issue the documnetation states

> color_mode: One of "grayscale", "rgb", "rgba". Default: "rgb". Whether the images will be **converted** to have 1, 3, or 4 channels.

Because it says **converted** I think one would assume that it converts a jpg image to have a 4 channel.

**Comment by gowthamkpr** [comment]
@CaptainDario The error message clearly states that JPEG does not support 4 channels. It is not documented because it is well known fact that JPEG doesn't support alpha channel. Will discuss with the team and get back if we need to update the documentation. Thanks!
