### ISSUE TITLE
Performance regression for FP16 Div kernel from Eigen to LLVM

### ISSUE THREAD

**Issue by kaixih** [keras-team/keras#16476]
Might be related to https://github.com/keras-team/keras/issues/15857

We've benchmarked a set of pointwise kernels to understand the LLVM codegen CUDA kernels on Ampere/Volta GPUs. We noticed that the division kernel is slower than the original eigen kernel. Here is the perf result of eigen kernels vs LLVM kernels:

https://docs.google.com/spreadsheets/d/13i0P_TaYEYz7cW20uU2YqoL_eE4uxiPzpaBhAPFUbdU/edit?usp=sharing

So, considering division is typically more expensive than other ops, we guess the code gen kernel might need higher loop unrolling factor.

cc. @wenscarl @nluehr

The repro script:
```python
import tensorflow as tf
import time

a = tf.ones((500000000, ), tf.dtypes.float16)
b = tf.ones((1, ), tf.dtypes.float16)
p = tf.constant(1.)
# warmup
tf.math.add(a, b)

steps = 1000
start = time.time()
for i in range(steps):
  c = tf.math.add(a, b)
(p + 1.).numpy()
end = time.time()

print("GPU: addition {} ms".format((end - start) / steps * 1000))

start = time.time()
for i in range(steps):
  c = tf.math.subtract(a, b)
(p + 1.).numpy()
end = time.time()

print("GPU: subtract {} ms".format((end - start) / steps * 1000))

start = time.time()
for i in range(steps):
  c = tf.math.divide(a, b)
c = tf.reduce_max(c)
(p + 1.).numpy()
end = time.time()

print("GPU: divide {} ms".format((end - start) / steps * 1000))

start = time.time()
for i in range(steps):
  c = tf.math.maximum(a, b)
(p + 1.).numpy()
end = time.time()

print("GPU: maximum {} ms".format((end - start) / steps * 1000))

start = time.time()
for i in range(steps):
  c = tf.math.minimum(a, b)
(p + 1.).numpy()
end = time.time()

print("GPU: minimum {} ms".format((end - start) / steps * 1000))

start = time.time()
for i in range(steps):
  c = tf.math.negative(a)
(p + 1.).numpy()
end = time.time()

print("GPU: negative {} ms".format((end - start) / steps * 1000))
start = time.time()
for i in range(steps):
  c = tf.nn.relu(a)
c = tf.reduce_max(c)
(p + 1.).numpy()
end = time.time()

print("GPU: relu {} ms".format((end - start) / steps * 1000))
```

**Comment by tilakrayal** [comment]
@gadagashwini ,
I was able to reproduce the issue in tf v2.7, v2.8 and nightly.Please find the gist [here](https://colab.research.google.com/gist/tilakrayal/43c398868415cd84605fa5db3018fa0e/16476.ipynb).

**Comment by reedwm** [comment]
@chsigg, can you take a look?

**Comment by qlzh727** [comment]
Assign to Reed for FP16 issue.

**Comment by chsigg** [comment]
The following changes should fix performance of fp16 division:

https://github.com/tensorflow/tensorflow/commit/b621d11a9c3bbfb3339b3792fb2263a3d28930b4
https://reviews.llvm.org/rG400fef081adbafc358858709861cdb14303de0e9
https://github.com/tensorflow/tensorflow/commit/a9e09537e7caf942d8cad6dff3ee9dca52c1d3fb

Kaixi, would you mind confirming? Thanks!

**Comment by kaixih** [comment]
Sorry for the late reply.

Thanks for the fix and the issue is no longer there. Closing.
