### ISSUE TITLE
How to pass model into TimeDistributed layer ? (or convert model to layer?)

### ISSUE THREAD

**Issue by tempdeltavalue** [keras-team/keras#16482]
Here's I tried to pass model into TD layer 

enc_outputs = TimeDistributed(sample_encoder(inputs=[inputs, enc_padding_mask]))  # sample_encoder - is model 

And I get this error: 
ValueError: Please initialize `TimeDistributed` layer with a `tf.keras.layers.Layer` instance. You passed: KerasTensor(type_spec=TensorSpec(shape=(None, None, 128), dtype=tf.float32, name=None), name='sample_encoder/encoder_layer_1/layer_normalization_3/batchnorm/add_1:0', description="created by layer 'sample_encoder'")

**Comment by tempdeltavalue** [comment]
related to this issue 

https://github.com/keras-team/keras/issues/15515

**Comment by sushreebarsa** [comment]
@tempdeltavalue 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by tempdeltavalue** [comment]
@sushreebarsa 
Hi.🍏 
Is colab convinent for you ?

https://colab.research.google.com/drive/1X6zuidDqZqf4xM5YBEygPlyy6KVJwYC1?usp=sharing

**Comment by sushreebarsa** [comment]
@tempdeltavalue Thank you for the update!
@gowthamkpr I was able to replicate the issue on colab , please find the [gist ](https://colab.research.google.com/gist/sushreebarsa/927e8499c2b651327b256006b81972d7/timedistwithlambda.ipynb#scrollTo=ACww9sE6h-8L) here.Thanks!

**Comment by tempdeltavalue** [comment]
@sushreebarsa @gowthamkpr 

Hi ✋
Any updates?

**Comment by divyashreepathihalli** [comment]
@tempdeltavalue, have you tried implementing a custom keras layer using this guide - https://keras.io/guides/making_new_layers_and_models_via_subclassing/ . you can call the model in call(). All the operations in call should be differentiable.

**Comment by divyashreepathihalli** [comment]
@tempdeltavalue I see that you are passing the outputs(kerasTensor) of a model to TimeDistributed layer. you can pass the model to the TimeDistributed layer directly and try it out.

**Comment by tempdeltavalue** [comment]
@divyashreepathihalli Hmmm.. not sure what I'm get you 

I'm passing to TD layer 
TimeDistributed(sample_encoder)

where is sample_encoder is 
tf.keras.Model(inputs=[inputs, padding_mask],
                        outputs=outputs,
                        name=name)

**Comment by tempdeltavalue** [comment]
@divyashreepathihalli soo, any suggestions how to do that ?

**Comment by divyashreepathihalli** [comment]
@tempdeltavalue, I dont see this error anymore in the colab script - 
`NotImplementedError: Exception encountered when calling layer "time_distributed" (type TimeDistributed).
Please run in eager mode or implement the `compute_output_shape` method on your layer (TFOpLambda).`

Regarding the "notImplementedError" that I now see on your colab, here is another thread - https://github.com/keras-team/keras/issues/16656

**Comment by tempdeltavalue** [comment]
@divyashreepathihalli 🤔

I'll check it in some "future"

Thank you )
