### ISSUE TITLE
Keras and Sklearn StackingRegressor : problem with one row input

### ISSUE THREAD

**Issue by phbillet** [keras-team/keras#16495]
Hello,

I am trying to build a regressor using sklearn Stacking regressor and Keras, everything works fine when the input contains more than one row.

But if I use one row, the program returns the message "ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 10 has 1 dimension(s)".

After some investigations, for one row input : the shape of the Keras NN output is (), and the shape of the other sklearn estimator output  is (1,).

If I use 2 rows input, the shape of the Keras NN is (2,), and the shape of the other sklearn estimator is (2,).

The keras NN is:

`model = Sequential()`

`model.add(Dense(11, activation='relu'))`

`model.add(BatchNormalization())`

`model.add(Dense(1))`

`model.compile(loss='mean_squared_error', optimizer='adam')`

How to solve it ?

Thanks for your help.

**Comment by tilakrayal** [comment]
@phbillet ,
In order to expedite the trouble-shooting process, could you please provide a complete code and the TensorFlow version you are using.Thanks!

**Comment by phbillet** [comment]
**System information**
I use wsl with Ubuntu 20.04 LTS and anaconda for Python
I use those package versions :
numpy: 1.21.5
pandas: 1.4.1
sklearn: 1.0.2
keras: 2.7.0
yellowbrick: 1.4

**Describe the problem**
In the notebook https://github.com/phbillet/EZStacking/blob/main/Stack_Keras_1.ipynb
the cell 24 (`array(22.85553, dtype=float32)`) shows that the output value is not complaint with the output value of the cell 25 (`array([22.855536, 41.029778], dtype=float32)`).
For me, the correct value for cell 24 is `array([22.85553], dtype=float32)`

I tried a similar test just with Keras, it works fine, so I think that the problem comes from  KerasRegressor (from keras.wrappers.scikit_learn).

**Comment by tilakrayal** [comment]
@gadagashwini ,
I was able to reproduce the issue in tf [v2.7](https://colab.research.google.com/gist/tilakrayal/0c3402cfd285543c209fb402623f23b7/16495_2_7.ipynb), [v2.8](https://colab.research.google.com/gist/tilakrayal/4211717502f4624179724580746717df/16495-2-8.ipynb) and [nightly](https://colab.research.google.com/gist/tilakrayal/86fb6cf06fbd31260285f723152518b3/16495_nightly.ipynb).Please find the gist of it here.

**Comment by qlzh727** [comment]
It seem that the KerasRegressor is deprecated and we are no longer maintaining/bug fixing it. Please forward this issue to https://github.com/adriangb/scikeras.
