### ISSUE TITLE
Add Levenberg-Marquardt algorithm as a optimizer for keras.

### ISSUE THREAD

**Issue by Fly-Playgroud** [keras-team/keras#16498]
Hi！please add` Levenberg-Marquardt` algorithm as a optimizer for keras. This algorithm is great useful for some problems.

**Comment by sushreebarsa** [comment]
@Fly-Playgroud 
Can you please elaborate about your feature and please specify the use cases for this feature. Thanks!

**Comment by JohnTaylor2000** [comment]
Here is an example of an implementation of levenberg-Marquardt algorithm in Keras. Lots of useful applications.

https://github.com/fabiodimarco/tf-levenberg-marquardt

See also results here. Very helpful for PINNs

https://arxiv.org/abs/2205.07430

**Comment by Fly-Playgroud** [comment]
@JohnTaylor2000 Thanks for your reply, I just skimmed the article and I think it's really well written and quite helpful.
Only I didn't find the code for this side of the article, it would have been nice to have it.I found this project(https://github.com/fabiodimarco/tf-levenberg-marquardt) a long time ago, I tried to use it and did not feel very comfortable.

**Comment by JohnTaylor2000** [comment]
Hi,

This was the code that I have been using. You can also find an implementation in scipy:-

https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.least_squares.html method=’lm’

Best wishes,

John





From: BUG|Fly ***@***.***>
Date: Monday, 23 May 2022 at 7:36 pm
To: keras-team/keras ***@***.***>
Cc: Taylor, John (Data61, Black Mountain) ***@***.***>, Mention ***@***.***>
Subject: Re: [keras-team/keras] Add Levenberg-Marquardt algorithm as a optimizer for keras. (Issue #16498)

@JohnTaylor2000<https://github.com/JohnTaylor2000> Thanks for your reply, I just skimmed the article and I think it's really well written and quite helpful.
Only I didn't find the code for this side of the article, it would have been nice to have it.I found this project(https://github.com/fabiodimarco/tf-levenberg-marquardt) a long time ago, I tried to use it and did not feel very comfortable.
