### ISSUE TITLE
RNN get_initial_state() does not expose state: training or evaluation.

### ISSUE THREAD

**Issue by mcourteaux** [keras-team/keras#16502]
**System information**.

TensorFlow version (you are using): v2.7.0
Are you willing to contribute it (Yes/No) : Potentially

**Describe the feature and the current behavior/state**.

RNN Cell's `get_initial_state()` does not take a `training` bool to allow you to change the initial state based on whether you are training or evaluating.

**Will this change the current API? How?**
Have a `training=True` or `training=False` passed into the RNN Cell `get_initial_state()` function. Not sure if this will break backwards compatibility... I'm not a Python wizard, however, maybe a `**kwargs` will allow us to add the field without breaking backwards compatibility. But this addition seems sensible to me. On the other hand, the by-now-deprecated `K.is_training_phase()` seemed like a good fit which wouldn't affect the API, but that function is gone it seems.

**Who will benefit from this feature?**
Anyone training RNN who wish to do more interesting things with the initial state. I'm trying to use randomized initial state during training, but of course want to not have a random initial state during evaluation. The initial state being random is a form of augmentation.

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**

- Do you want to contribute a PR? (yes/no): potentially yes
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing):
Maybe a `**kwargs` will allow us to add a parameter without breaking backwards compatibility?

**Comment by qlzh727** [comment]
Thanks for reporting the issue. Usually the init state is provided by user when calling the layer, which means you could provide a init state to the layer between train/eval. Note that this method is only called when user didn't specify the init state, if you already have the state available, then just call the layer/cell with it.

**Comment by mcourteaux** [comment]
Thanks for your answer, but essentially, this is my current workaround, which is unsatisfactory. I am passing in a training flag myself to the whole layer. Based on this flag, I choose random initial state, or de default zero state. As this flag is static for one given model instance, this doesn't solve the issue for the expected different behavior of `Model.fit()` and `Model.evaluate()` or `Model.predict()`. Augmentation and noise layers are usually disabled during evaluation, which now can't be done, as the solution you suggest is permanent for a given model instance.

The workaround is rather cumbersome: I have to train a model with random initial state. Save the weights to disk, instantiate a new identical model, but with zero initial state this time, and load the weights from disk again. Now I can use the new instance for evaluation purposes.

**Comment by mcourteaux** [comment]
> we have to detect any custom cell that doesn't have the optional kwarg `trainin`

I have no clue how you would go about that. Try-catch in Python? Kinda ugly to use exceptions for this, but I'm not sure if there is a nice way.

> Shouldn't be a complicated change.

I could try to find some time soonish. This should be a Python-only change that doesn't require any Bazel steps, right?

**Comment by qlzh727** [comment]
> > we have to detect any custom cell that doesn't have the optional kwarg `trainin`
> 
> I have no clue how you would go about that. Try-catch in Python? Kinda ugly to use exceptions for this, but I'm not sure if there is a nice way.

You need to inspect the args/kwargs for a method and see if there is a training arg in it. See https://docs.python.org/3/library/inspect.html#inspect.signature
> 
> > Shouldn't be a complicated change.
> 
> I could try to find some time soonish. This should be a Python-only change that doesn't require any Bazel steps, right?

To test the change, you will need bazel for running the test case.

**Comment by sachinprasadhs** [comment]
Hello, Thank you for reporting an issue.

We're currently in the process of migrating the new Keras 3 code base from keras-team/keras-core to keras-team/keras.
Consequently, This issue may not be relevant to the Keras 3 code base . After the migration is successfully completed, feel free to reopen this Issue at keras-team/keras if you believe it remains relevant to the Keras 3 code base. If instead this Issue is a bug or security issue in legacy tf.keras, you can instead report a new issue at [keras-team/tf-keras](https://github.com/keras-team/tf-keras/issues), which hosts the TensorFlow-only, legacy version of Keras.

To know more about Keras 3, please read https://keras.io/keras_core/announcement/
