### ISSUE TITLE
unable to pickle keras.layers.StringLookup

### ISSUE THREAD

**Issue by ophiry** [keras-team/keras#16503]
cross posting: https://github.com/tensorflow/tensorflow/issues/55825

 
 <details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.8

### Custom Code

No

### OS Platform and Distribution

colab

### Python version

3.7

### Current Behaviour?

```shell
trying to pickle a StringLookup layer causes an exception
tried in colab python 3.7 and local macos python 3.8
```

### Standalone code to reproduce the issue

```shell
import tensorflow
import pickle
print(tensorflow.__version__)
pickle.dumps(tensorflow.keras.layers.StringLookup())
```

### Relevant log output

```shell
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-2-caa8edb2bfc5> in <module>()
      2 import pickle
      3 print(tensorflow.__version__)
----> 4 pickle.dumps(tensorflow.keras.layers.StringLookup())

1 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py in _numpy(self)
   1189       return self._numpy_internal()
   1190     except core._NotOkStatusException as e:  # pylint: disable=protected-access
-> 1191       raise core._status_to_exception(e) from None  # pylint: disable=protected-access
   1192 
   1193   @property

InvalidArgumentError: Cannot convert a Tensor of dtype resource to a NumPy array.
```
</details></details>

**Comment by sushreebarsa** [comment]
@gowthamkpr I was able to replicate the issue on colab ,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/9192cb50196d321394ebe228609fa58f/16503.ipynb#scrollTo=CysKXd1YcqsN) for reference. Thank you!

**Comment by gowthamkpr** [comment]
@ophiry Please try using [tf.keras.layers.serialize](https://www.tensorflow.org/api_docs/python/tf/keras/layers/serialize) and it should work.

**Comment by ophiry** [comment]
Thanks.

the reason for using pickle is to allow seamless serialization of nested objects. using the [tf.keras.layers.serialize](https://www.tensorflow.org/api_docs/python/tf/keras/layers/serialize) is possible, but will require additional boilerplate of implementing get state and set state methods

**Comment by rchao** [comment]
Hello @ophiry , pickling afaik isn't natively supported in Keras as the pickle module is generally [not secure](https://docs.python.org/3/library/pickle.html). Therefore I don't think this is actionable on Keras side, and overriding methods for `tf.keras.layers.serialize` is necessary. Please reopen is `tf.keras.layers.serialize` is still not working after the methods are provided.

Thanks for the question!
