### ISSUE TITLE
Math error in OrthogonalRegularizer

### ISSUE THREAD

**Issue by Kiwiakos** [keras-team/keras#16518]
The code below adds up the non-diagonal elements of the product matrix, which is not correct. It should compute the norm of the matrix instead. As it stands the regularizer does not orthogonalise, but instead pushes vectors to be negatively correlated towards `-1/(N-1)` where `N` is the number of vectors.

https://github.com/keras-team/keras/blob/81c83b32e4b4d4a4107d4aa63a3970dadff3058a/keras/regularizers.py#L371

Therefore `tf.reduce_sum(product_no_diagonal)` should be replaced with either `tf.norm(product_no_diagonal, ord='fro')` to use the Froebenius norm (with the appropriate `import`), or with `tf.reduce_sum(tf.abs(product_no_diagonal))` to use the (1,1) matrix norm.

**Comment by tilakrayal** [comment]
@Kiwiakos ,
Can you please feel free to submit a PR for the requested change to be made.Thanks!

**Comment by Kiwiakos** [comment]
Fix implemented
