### ISSUE TITLE
TypeError found in keras-Mxnet 2.2.4.2

### ISSUE THREAD

**Issue by rubbberrabbit** [keras-team/keras#16515]
**Describe the problem**.
Analysis:
The error is found in keras-Mxnet 2.2.4.2. The location of the error is in Line 359 of file saving.py. After deserializing model, the program checks the weight parameters of each layer. If the length of weight values is not equal to the length of symbolic weights, a ValueError exception will be triggered. However, the program splices string type data with the name parameter (a bytes type parameter), which makes the program unable to handle exception correctly and then causes a vulnerability instead of returning an error message.

**Describe the current behavior**.
![图片1](https://user-images.githubusercontent.com/38725110/167263551-b0c6d2a5-bd46-4a31-9637-e1296f4fc7b2.png)

**Comment by rubbberrabbit** [comment]
The complete code and the .h5 model is provided here. The issue happens when the Keras load to model for Mxnet, and in other DL libraries likes the Tensorflow, the model works well, so I don't think the error stating is related with a wrong input type by user.
https://drive.google.com/drive/folders/1minNMHx9h7ptIJ9ra6HVDYgZvSifc0p1?usp=sharing

**Comment by gowthamkpr** [comment]
@rubbberrabbit Can you please use the latest version of keras and just provide a reproducible code with keras (not keras-Mxnet). Thanks!
