### ISSUE TITLE
RandomFlip layer doesn't work vertically

### ISSUE THREAD

**Issue by Wehzie** [keras-team/keras#16559]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Fedora 35, kernel 5.17.5-200.fc35.x86_64
- TensorFlow installed from (source or binary): binary via pip
- TensorFlow version (use command below): v2.9.0-rc2-42-g8a20d54a3c1 2.9.0
- Python version:  3.10.4
- Bazel version (if compiling from source):
- GPU model and memory: GP108M [GeForce MX250],  2,048 MB GDDR5 memory 
- Exact command to reproduce: execute code below

**Describe the problem**.

Describe the problem clearly here. Be sure to convey here why it's a bug in Keras or why the requested feature is needed.
When using the RandomFlip layer for data augmentation, vertical flipping doesn't occur.
This is the case when using "horizontal_and_vertical" and "vertical".
In the case of "horizontal_and_vertical", the horizontal flipping works.
In the case of "horizontal", all works as expected.

**Describe the current behavior**.
No vertical flipping occurs.

**Describe the expected behavior**.
Vertical flipping should occur.

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no): no

**Standalone code to reproduce the issue**.

```
import matplotlib.pyplot as plt
import tensorflow as tf
def keras_layers(img_path: Path, reps: int = 1):
        """Combine multiple keras augmentation layers."""

        augment_layers = tf.keras.Sequential([
            layers.RandomFlip("horizontal_and_vertical"), # see also "vertical"
        ])
        
        im = plt.imread(str(img_path))
        image = tf.cast(tf.expand_dims(im, 0), tf.float32)
        for _ in range(reps):
            augmented_image = augment_layers(image)
            print("")
            print("ORIGINAL IMAGE")
            print(im)
            print("AUGMENTED IMAGE")
            print(augmented_image)
            
            fig = plt.figure(frameon=False)
            ax = plt.Axes(fig, [0., 0., 1., 1.])
            ax.set_axis_off()
            fig.add_axes(ax)
            ax.imshow(augmented_image[

            plt.savefig("test.png")
            plt.show()
```

**Source code / logs**.

No error behavior.

**Comment by tilakrayal** [comment]
@Wehzie ,
I was facing different error while trying to execute the given code. Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/5bfc624fb0d15991f137dcccfef49b2a/untitled349.ipynb). Also, code shared is having indentation errors, could you share a colab gist with the issue reported or simple stand alone indented code to replicate the issue. Thank you!

**Comment by Wehzie** [comment]
Sorry for false alarm, it seems like there is no bug here; couldn't reproduce the issue on Colab. I think the issue arises from how images are read on my local machine, not a Keras problem.

Code is properly working, [here](https://gist.github.com/Wehzie/aa7015a074b9704842d5f02b9b9c6b80).
