### ISSUE TITLE
tf.keras.datasets.cifar10(path='cifar-10-python.tar.gz')

### ISSUE THREAD

**Issue by BA7LYA** [keras-team/keras#16561]
The `tf.keras.datasets.mnist.load_data(path='/user/.keras/datasets/mnist.npz')` works fine, but the `tf.keras.datasets.cifar10.load_data()` have no `path` param, which means everytime everyone runs his/her jupyter scripts that requires cifar10, he/she had to download the datasets from source again, it's really boring and time-consuming :)

**Comment by tilakrayal** [comment]
Hi @BA7LYA,
`tf.keras.datasets.cifar10.load_data()` doesn't require you to store data locally. It provides a convenient option where you can download as well load the data in your instance on the fly.
Perhaps could you use `tf.keras.utils.get`_file function to load data stored locally.

Also could you take a look at this [link](https://www.tensorflow.org/api_docs/python/tf/keras/utils/get_file) which delivers the information.It helps.Thanks!

**Comment by BA7LYA** [comment]
thx
