### ISSUE TITLE
New experimental optimizers can't be used with mixed precision

### ISSUE THREAD

**Issue by andrey-klochkov-liftoff** [keras-team/keras#16560]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.9.0
- Python version: 3.9.10
- Bazel version (if compiling from source): N/A
- GPU model and memory: NVIDIA A10G
- Exact command to reproduce: 

**Describe the problem**.

When an experimental optimizer is used and mixed precision is enabled by setting the global policy to `mixed_float16`, model compilation fails with the following error:

> TypeError: You passed an instance of the new experimental optimizer, `optimizer_experimental.Optimizer`, to LossScaleOptimizer, but only the classic optimizers subclassing from `tf.keras.optimizers.Optimizer` can be passed. Please use `loss_scale_optimizer.LossScaleOptimizerV3` instead of `tf.keras.mixed_precision.LossScaleOptimizer`, as the former supports wrapping instances of the new experimental optimizer. Got optimizer: <keras.mixed_precision.loss_scale_optimizer.LossScaleOptimizerV3 object at 0x7fbc4856fbd0>

**Source code / logs**.

A very simple script that reproduces this:
```Python
import tensorflow as tf

opt = tf.keras.optimizers.experimental.Adam()

tf.keras.mixed_precision.set_global_policy("mixed_float16")

# Create a very simple model. The code is taken from the docs of the Model class.
inputs = tf.keras.Input(shape=(3,))
x = tf.keras.layers.Dense(4, activation=tf.nn.relu)(inputs)
outputs = tf.keras.layers.Dense(5, activation=tf.nn.softmax)(x)
model = tf.keras.Model(inputs=inputs, outputs=outputs)

# This call fails with the error provided above.
model.compile(optimizer=opt)
```

I attempted to wrap the optimizer into a `LossScaleOptimizerV3` with `opt = LossScaleOptimizerV3(opt)` but it didn't fix the problem.

I debugged this and found that  in`Model._get_optimizer` the nested function `_get_single_optimizer` checks for the `opt` parameter to be an instance of `LossScaleOptimizer`, while it should be checking if it's an instance of `BaseLossScaleOptimizer`. Currently, the check fails if the passed object is a `LossScaleOptimizerV3`, and so the code attempts to wrap the `LossScaleOptimizerV3` object into `LossScaleOptimizerV2` which leads to the error. The fix is very simple and I can file a PR if necessary.

**Comment by andrey-klochkov-liftoff** [comment]
A workaround is to monkey-patch the bug like this:

```Python
def _get_optimizer(self, optimizer):
    """Wraps `optimizer` in `LossScaleOptimizer` if necessary."""

    def _get_single_optimizer(opt):
        opt = tf.keras.optimizers.get(opt)
        if self.dtype_policy.name == "mixed_float16" and not isinstance(
            opt, lso.BaseLossScaleOptimizer
        ):
            # Loss scaling is necessary with mixed_float16 for models to converge to
            # the same accuracy as with float32.
            opt = lso.BaseLossScaleOptimizer(opt)
        return opt

    return tf.nest.map_structure(_get_single_optimizer, optimizer)

tf.keras.Model._get_optimizer = _get_optimizer
```

**Comment by sushreebarsa** [comment]
Hi @andrey-klochkov-liftoff I tried to reproduce the provided code on colab using TF v2.9.0 and faced the following error
```
AttributeError: module 'keras.api._v2.keras.optimizers' has no attribute 'experimental'
```
Please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/fcc3b5ca6412349394dee10964048ae3/16560.ipynb) and confirm the same. Thank you!

**Comment by bhack** [comment]
@andrey-klochkov-liftoff Can you try with 2.9 and:

`opt = tf.keras.optimizers.Adam()`

**Comment by andrey-klochkov-liftoff** [comment]
@sushreebarsa ,
I executed the Colab notebook you referenced and it reproduced the problem I reported. Did you restart the notebook runtime after installing TF 2.9.0? If not, you were still running with TF 2.8 and you'd get the error like you pasted (`module 'keras.api._v2.keras.optimizers' has no attribute 'experimental'`).

**Comment by andrey-klochkov-liftoff** [comment]
@bhack ,
This bug report is specifically about the new experimental optimizers available in 2.9. Yes, the regular optimizers (like `tf.keras.optimizers.Adam`) work fine.

**Comment by sushreebarsa** [comment]
@andrey-klochkov-liftoff Thank you for the update!
@gowthamkpr I was able to replicate the issue on colab, please find the updated [gist](https://colab.research.google.com/gist/sushreebarsa/fcc3b5ca6412349394dee10964048ae3/16560.ipynb#scrollTo=H2Tx7-3HytnQ) here.
Thank you!

**Comment by chenmoneygithub** [comment]
@andrey-klochkov-liftoff  Thanks reporting the issue! 

Good catch! We will fix this error and keep you posted. Thanks again!

**Comment by chenmoneygithub** [comment]
This should have been fixed in tf-nightly
