### ISSUE TITLE
Dataset.repeat(0)

### ISSUE THREAD

**Issue by jamesbraza** [keras-team/keras#16578]
**URL(s) with the issue:**.

https://www.tensorflow.org/api_docs/python/tf/data/Dataset#repeat

**Description of issue (what needs to be changed):**.

I am coming from here: https://github.com/tensorflow/tensorflow/issues/56215.

Here's how to get a dataset (from [Image classification from scratch](https://keras.io/examples/vision/image_classification_from_scratch/)).

```shell
curl -O https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_5340.zip
unzip kagglecatsanddogs_5340.zip
```

Then run this:

```python
import tensorflow as tf

train_ds = tf.keras.preprocessing.image_dataset_from_directory("PetImages")

flag = False
for images, labels in train_ds.repeat(0):
    flag = True
assert flag  # Fails
```

We can see that `.repeat(0)` will not enter the `for` loop.

In my opinion, the expected behavior for `.repeat(0)` would be to move through the `Dataset` once and then `StopIteration`, because we are repeating the dataset zero times.  However, `.repeat(0)` results in a zero-length iterable.

I think this should be documented: that if you want to move through the dataset once, don't use `.repeat(0)` instead use `.repeat(1)`.

**Comment by sushreebarsa** [comment]
@jamesbraza Could you please have a look at this [gist](https://colab.research.google.com/gist/sushreebarsa/56cf1e103929b8b348447b3533b0208f/untitled54.ipynb#scrollTo=qywjU2IKazb2) and confirm the issue?
Thank you!

**Comment by jamesbraza** [comment]
Yeah that's correct, thank you for converting @sushreebarsa 👍 

The assertion's failure means we never entered the loop.  I think it'd be useful to document this

**Comment by jamesbraza** [comment]
I do see that.  In my opinion I think a slight clarification (e.g. an example) to the docs would be useful.

Current `count` arg description:

> (Optional.) A `tf.int64` scalar `tf.Tensor`, representing the number of times the dataset should be repeated. The default behavior (if `count` is `None` or `-1`) is for the dataset be repeated indefinitely.

Here is what I would like to see:

> (Optional.) A `tf.int64` scalar `tf.Tensor`, representing the number of times the dataset should be repeated. The default behavior (if `count` is `None` or `-1`) is for the dataset be repeated indefinitely.  If `count` is `0`, the output dataset will be empty.

What do you think?

**Comment by gowthamkpr** [comment]
@jamesbraza Thank you for the response. 

> Repeats this dataset so each original value is seen count times.

The above line describes the same in the document. If you really think this is necessary please create a PR. Thanks!
