### ISSUE TITLE
Mapping a Dataset squashes class_names from image_dataset_from_directory

### ISSUE THREAD

**Issue by jamesbraza** [keras-team/keras#16577]
**System information**.

- Have I written custom code (as opposed to using a stock example script provided in Keras): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Big Sur v11.5.1
- TensorFlow installed from (source or binary): binary (`pip`)
- TensorFlow version (use command below):2.4.4
- Python version: 3.8.13
- Bazel version (if compiling from source): n/a
- GPU model and memory: n/a
- Exact command to reproduce: see below

**Describe the current behavior**.

I am coming from https://github.com/tensorflow/tensorflow/issues/56233.

Using [image_dataset_from_directory](https://www.tensorflow.org/api_docs/python/tf/keras/utils/image_dataset_from_directory) will correctly create a `Dataset` that contains the labels as `class_names`.

However, when you transform that dataset (e.g. via .map) the `class_names` get clobbered.

**Describe the expected behavior**.

Ideally, `.map`'ing or `.batch`'ing a `Dataset` won't clobber `class_names`.

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no):

**Standalone code to reproduce the issue**.

From [Image classification from scratch](https://keras.io/examples/vision/image_classification_from_scratch/)

```shell
curl -O https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_5340.zip
unzip kagglecatsanddogs_5340.zip
```

Then running this:

```python
import tensorflow as tf

train_ds = tf.keras.preprocessing.image_dataset_from_directory(
    "PetImages",
    batch_size=32,
)
assert hasattr(train_ds, "class_names")  # Passes
mapped_train_ds = train_ds.map(lambda x, y: (x, y))
assert hasattr(mapped_train_ds, "class_names")  # Doesn't pass
```

**Source code / logs**.

n/a

**Comment by tilakrayal** [comment]
@jamesbraza ,
Could you provide the error log you are facing. It helps to debug the issue. Thank you!

**Comment by jamesbraza** [comment]
Yeah sure!  If you mean error logs, there's not one, but the assertion is failing because the `class_names` gets clobbered.

```
Found 25000 files belonging to 2 classes.
2022-05-25 21:15:43.343109: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-05-25 21:15:43.343489: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/path/to/file.py", line 9, in <module>
    assert hasattr(mapped_train_ds, "class_names")  # Doesn't pass
AssertionError

Process finished with exit code 1
```

Please let me know if you need more clarity anywhere 👍

**Comment by tilakrayal** [comment]
@gowthamkpr ,
I was able to reproduce the issue in tensorflow v2.8, v2.9 and nightly. Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/c237d81017bbf9243917e66e39bf8ad1/16577.ipynb).

**Comment by rchao** [comment]
Triage note: users are recommended to store the `class_name` from `tf.keras.preprocessing.image_dataset_from_directory()` instance in their own variable without relying on the attribute. There's little actionable items for Keras.

**Comment by rchao** [comment]
We should append this information to `image_dataset_from_directory()`, though.
