### ISSUE TITLE
TypeError: ('Keyword argument not understood:', 'inputs') (reopens #13743)

### ISSUE THREAD

**Issue by jim-smith** [keras-team/keras#16582]
**System information**.
I encountered this error trying to subclass keras model.
As per the code below have stripped out everything but the call to Model.__init()__ and still experience the error

I have tested this and experience the same error on 2 machines in three different environments:
1. A macbook pro running keras 2.8 installed via miniconda optimised for the AppleM1pro chipset. (tensor flow-macos)
    -   python 3.9.7
    - tensorflow version command reports "unknown 2.8.0"
3. a linux box running Ubuntu 20.04.3 LTS with  keras 2.3 / python 3.8. Tensorflow installed. from pip, 
4. the same  linux box running Ubuntu 20.04.3 LTS with   keras 2.9 / python 3.8 running  in a virtual environment created 25/5/2022,  
       -    Tensorflow installed. from pip , version v2.9.0-18-gd8ce9f9c301 2.9.1

- Exact command to reproduce:
 python keras_debug.py (where the code below has been saved as keras_debug.py)

**Describe the problem**.

I get the error TypeError: ('Keyword argument not understood:', 'inputs') 
when trying to create a second instance of a subclassed model.

I have reduced my sub-class to a bare bones as per the code below.
 
**Describe the current behavior**.
Creates first instance correctly, then throws the type error when using exactly the same call to create the second instance 

**Describe the expected behavior**.
Should create two instances of the subclass

**Standalone code to reproduce the issue**.
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification

n_classes = 2
X, y = make_classification(n_samples=1000,
                           n_classes=n_classes,
                           n_features=300,
                           n_informative=300,
                           n_redundant=0,
                           n_repeated=0,
                           random_state=15
                          )
y = np.eye(n_classes)[y]

from tensorflow.keras import Model as Keras_Model
class KModel_Subclass(Keras_Model ):
    """minimal subclass Wrapper around  tf.keras.Model class from tensorflow 2.8"""

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        """Creates model and applies constraints to params"""
        Keras_Model.__init__(self,*args,**kwargs)

#define simple model
from tensorflow.keras.layers import Input, Dense
the_input = Input(shape = X[0].shape)
x = Dense(128, activation='relu')(the_input)
x = Dense(128, activation='relu')(x)
x = Dense(64, activation='relu')(x)
the_output = Dense(2, activation='softmax')(x)

#create two instances
first_instance = KModel_Subclass(inputs=the_input, outputs= the_output)
print('Made first instance')
second_instance = KModel_Subclass(inputs=the_input, outputs= the_output)
print('Made second instance')

**Source code / logs**.
Made first instance
Traceback (most recent call last):
  File "keras_debug.py", line 45, in <module>
    second_instance = KModel_Subclass(inputs=the_input, outputs= the_output)
  File "keras_debug.py", line 31, in __init__
    Keras_Model.__init__(self,**kwargs)
  File "/home/j4-smith/aienv/lib/python3.8/site-packages/tensorflow/python/training/tracking/base.py", line 587, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/j4-smith/aienv/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/j4-smith/aienv/lib/python3.8/site-packages/keras/utils/generic_utils.py", line 1174, in validate_kwargs
    raise TypeError(error_message, kwarg)
TypeError: ('Keyword argument not understood:', 'inputs')

**Comment by sushreebarsa** [comment]
@jim-smith I tried to replicate the issue on colab and didn't face the error reported. Could you please have a look at the [gist ](https://colab.research.google.com/gist/sushreebarsa/80a5ee862edc129a19fc2c1259fa0177/untitled365.ipynb)here and confirm the same?  In case I have missed something to reproduce this issue, please provide the complete code snippet in order to expedite the trouble-shooting process. Thank you!

**Comment by jim-smith** [comment]
@sushreebarsa thanks for your help with this.
- Im not entirely sure about the reasons for the change to putting inputs and outputs as positional arguments and defining an empty call() function,   
-  but even with those changes the code supplied does not work if you then try to use those instances.

- When I copied you code I found that  although I can call compile on both objects, and fit() on the first,  when I try to call fit() on the second object it fails with an error that the second instance
>- AttributeError: 'KModel_Subclass' object has no attribute '_nested_inputs'

To confirm this I've added these lines to the end of your gist:
```
keys1 = list(first_instance.__dict__.keys())
keys2 = list(second_instance.__dict__.keys())
for key in keys1:
    if key not in keys2:
        print(f'key {key} present in first instance but not second')
for key2 in keys2:
    if key2 not in keys1:
        print(f'key {key2} present in second instance but not first'
```

and it illustrates  an issue because it gives this output 

Made first instance <__main__.KModel_Subclass object at 0x7f7613003590>
Made second instance <__main__.KModel_Subclass object at 0x7f7612f97550>
key _nested_inputs present in first instance but not second
key _nested_outputs present in first instance but not second
key _enable_dict_to_input_mapping present in first instance but not second
key _input_layers present in first instance but not second
key _output_layers present in first instance but not second
key _input_coordinates present in first instance but not second
key _output_coordinates present in first instance but not second
key _output_mask_cache present in first instance but not second
key _output_tensor_cache present in first instance but not second
key _output_shape_cache present in first instance but not second
key _network_nodes present in first instance but not second
key _nodes_by_depth present in first instance but not second
key _layer_call_argspecs present in first instance but not second
key _feed_input_names present in first instance but not second
key _feed_inputs present in first instance but not second
key _feed_input_shapes present in first instance but not second
key _tensor_usage_count present in first instance but not second



The other issue is that I can't use 'return' on the line where I call the keras model init() method,  because I want to do. multiple inheritance and call the init function from a second superclass

But I'm not sure that is related to this

**Comment by jim-smith** [comment]
@sushreebarsa 
code that uses yours then illustrates the issue in that gist and replicated below


import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification

n_classes = 2
X, y = make_classification(n_samples=1000,
n_classes=n_classes,
n_features=300,
n_informative=300,
n_redundant=0,
n_repeated=0,
random_state=15
)
y = np.eye(n_classes)[y]
import tensorflow as tf
from tensorflow.keras import Model as Keras_Model
class KModel_Subclass(Keras_Model ):
  def __init__(self,inputs,outputs) -> None:
    def call(self, inputs,outputs):
      pass
    """Creates model and applies constraints to params"""
    return Keras_Model.__init__(self,inputs,outputs)
  



#define simple model
from tensorflow.keras.layers import Input, Dense
the_input = Input(shape = X[0].shape)
x = Dense(128, activation='relu')(the_input)
x = Dense(128, activation='relu')(x)
x = Dense(64, activation='relu')(x)
the_output = Dense(2, activation='softmax')(x)

the_input2 = Input(shape = X[0].shape)
x2 = Dense(128, activation='relu')(the_input2)
x2 = Dense(128, activation='relu')(x2)
x2 = Dense(64, activation='relu')(x2)
the_output2 = Dense(2, activation='softmax')(x2)

#create two instances
first_instance = KModel_Subclass(inputs=the_input, outputs= the_output)
print('Made first instance',first_instance)
second_instance = KModel_Subclass(inputs=the_input2, outputs= the_output2)
print('Made second instance',second_instance)

keys1 = list(first_instance.__dict__.keys())
keys2 = list(second_instance.__dict__.keys())
for key in keys1:
    if key not in keys2:
        print(f'key {key} present in first instance but not second')
for key2 in keys2:
    if key2 not in keys1:
        print(f'key {key2} present in second instance but not first')

from tensorflow.keras.losses import CategoricalCrossentropy

first_instance.compile (loss='categorical_crossentropy')
first_instance.fit(X,y)

second_instance.compile (loss='categorical_crossentropy')
second_instance.fit(X,y)

**Comment by sushreebarsa** [comment]
@jim-smith I have faced the output as below:
```Made first instance <__main__.KModel_Subclass object at 0x7faf44c96250>
Made second instance <__main__.KModel_Subclass object at 0x7faf44ca6310>
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-e58938b94217> in <module>()
     18 print('Made second instance',second_instance)
     19 
---> 20 keys1 = list(first_instance.dict.keys())
     21 keys2 = list(second_instance.dict.keys())
     22 for key in keys1:

AttributeError: 'KModel_Subclass' object has no attribute 'dict'
```
Please find the [gist](https://colab.research.google.com/gist/sushreebarsa/a92401699867530c48d721ad7dcd1102/16582.ipynb#scrollTo=AKRtkprMEvlv) here and confirm the same.
Could you provide the colab gist or notebook link to reproduce the exact issue reported here. Thank you!

**Comment by sushreebarsa** [comment]
@jim-smith Thank you for the update!
Could you have a look at this updated [gist](https://colab.research.google.com/gist/sushreebarsa/80a5ee862edc129a19fc2c1259fa0177/untitled365.ipynb#scrollTo=hS25o5bzcY69) and confirm the reported issue?
Thank you!

**Comment by jim-smith** [comment]
@sushreebarsa 
Yes,
The last cell of that gist seems to illustrate the issue - the second object is not being properly created.

In case it is useful, I've checked:
-  defining the call() method inside the class rather than inside the``` __init__``` function :  
     if you do that neither instance will compile
- adding the line super.call() inside the call method I.e.
````
class KModel_Subclass(Keras_Model ):
    def __init__(self,inputs,outputs) -> None:
        print('in init function of class KModel_Subclass')
        def call(self, inputs,outputs):
            super().call()
            pass
        
        Keras_Model.__init__(self,inputs,outputs)
        
````
and that makes no difference - the error in the gist still manifests
