### ISSUE TITLE
change weights in model saved in format "saved_model"

### ISSUE THREAD

**Issue by Matteo-Castrignano** [keras-team/keras#16601]
Hi, i m trying to change the weights type in the yolov5 cnn. The model is in the formtat "saved_model" i load it 2 time, in the first "model" i load the model to retrive the weghts and change its type and these work! But when i pass the new weights to the "model_quant" in the new type also changing the layer type, it does not work

Code:

model = load_model(model_path)
model_quant = load_model(model_path)

for w, layer in zip(model.layers, model_quant.layers):
    y = w.get_weights()
    y = [e.astype(keras.backend.floatx()) for e in y]
    layer.trainable = True
    layer.dtype = 'float64'
    layer.set_weights(y)

Output:
WARNING:absl:Importing a function (__inference_tf_c3_7_layer_call_and_return_conditional_losses_8593) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_4_layer_call_and_return_conditional_losses_17886) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_bottleneck_layer_call_and_return_conditional_losses_19821) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_1_layer_call_and_return_conditional_losses_15076) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_bottleneck_5_layer_call_and_return_conditional_losses_20105) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_2_layer_call_and_return_conditional_losses_9475) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_51_layer_call_and_return_conditional_losses_8656) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_bottleneck_10_layer_call_and_return_conditional_losses_6574) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_14_layer_call_and_return_conditional_losses_19674) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_8_layer_call_and_return_conditional_losses_18792) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_14_layer_call_and_return_conditional_losses_19644) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_layer_call_and_return_conditional_losses_9864) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_bottleneck_8_layer_call_and_return_conditional_losses_5966) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_5_layer_call_and_return_conditional_losses_7609) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_5_layer_call_and_return_conditional_losses_16371) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_layer_call_and_return_conditional_losses_6830) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_layer_call_and_return_conditional_losses_14867) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_bottleneck_3_layer_call_and_return_conditional_losses_20017) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_layer_call_and_return_conditional_losses_9962) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_33_layer_call_and_return_conditional_losses_15954) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_2_layer_call_and_return_conditional_losses_7161) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_6_layer_call_and_return_conditional_losses_18375) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_45_layer_call_and_return_conditional_losses_16440) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_layer_call_and_return_conditional_losses_14622) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_7_layer_call_and_return_conditional_losses_7867) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_7_layer_call_and_return_conditional_losses_9755) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_bottleneck_6_layer_call_and_return_conditional_losses_20181) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_51_layer_call_and_return_conditional_losses_16705) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_15_layer_call_and_return_conditional_losses_15260) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_1_layer_call_and_return_conditional_losses_14701) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_1_layer_call_and_return_conditional_losses_6750) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_2_layer_call_and_return_conditional_losses_17506) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_3_layer_call_and_return_conditional_losses_15767) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_7_layer_call_and_return_conditional_losses_16830) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_6_layer_call_and_return_conditional_losses_16636) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_5_layer_call_and_return_conditional_losses_16300) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_1_layer_call_and_return_conditional_losses_9691) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_2_layer_call_and_return_conditional_losses_17475) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_layer_call_and_return_conditional_losses_14641) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_7_layer_call_and_return_conditional_losses_6871) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_14_layer_call_and_return_conditional_losses_19614) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_25_layer_call_and_return_conditional_losses_9296) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_2_layer_call_and_return_conditional_losses_17568) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_bottleneck_2_layer_call_and_return_conditional_losses_19941) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_4_layer_call_and_return_conditional_losses_17828) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference__wrapped_model_4006) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_bottleneck_layer_call_and_return_conditional_losses_4330) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_4_layer_call_and_return_conditional_losses_17770) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_12_layer_call_and_return_conditional_losses_19410) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_3_layer_call_and_return_conditional_losses_15839) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_model_layer_call_and_return_conditional_losses_14065) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_51_layer_call_and_return_conditional_losses_16724) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_12_layer_call_and_return_conditional_losses_19380) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_1_layer_call_and_return_conditional_losses_6978) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_33_layer_call_and_return_conditional_losses_7382) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_bottleneck_3_layer_call_and_return_conditional_losses_5065) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_3_layer_call_and_return_conditional_losses_7298) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_bottleneck_7_layer_call_and_return_conditional_losses_5804) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_9_layer_call_and_return_conditional_losses_18974) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_bottleneck_4_layer_call_and_return_conditional_losses_20061) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_10_layer_call_and_return_conditional_losses_19116) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_2_layer_call_and_return_conditional_losses_17537) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_8_layer_call_and_return_conditional_losses_18761) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_6_layer_call_and_return_conditional_losses_16565) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_9_layer_call_and_return_conditional_losses_18884) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_8_layer_call_and_return_conditional_losses_18730) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_bottleneck_4_layer_call_and_return_conditional_losses_5108) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_10_layer_call_and_return_conditional_losses_19056) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_25_layer_call_and_return_conditional_losses_15673) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_15_layer_call_and_return_conditional_losses_15279) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_bottleneck_9_layer_call_and_return_conditional_losses_20342) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_bottleneck_1_layer_call_and_return_conditional_losses_19897) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_15_layer_call_and_return_conditional_losses_7027) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_9_layer_call_and_return_conditional_losses_18914) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_45_layer_call_and_return_conditional_losses_16459) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_6_layer_call_and_return_conditional_losses_18460) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_7_layer_call_and_return_conditional_losses_16901) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_bottleneck_6_layer_call_and_return_conditional_losses_5620) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_39_layer_call_and_return_conditional_losses_7515) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_3_layer_call_and_return_conditional_losses_9240) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_bottleneck_2_layer_call_and_return_conditional_losses_4678) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_7_layer_call_and_return_conditional_losses_14936) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_bottleneck_10_layer_call_and_return_conditional_losses_20417) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_45_layer_call_and_return_conditional_losses_7650) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_5_layer_call_and_return_conditional_losses_8935) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tfsppf_layer_call_and_return_conditional_losses_7355) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_15_layer_call_and_return_conditional_losses_9547) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_layer_call_and_return_conditional_losses_6723) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_1_layer_call_and_return_conditional_losses_14682) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_39_layer_call_and_return_conditional_losses_16196) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_25_layer_call_and_return_conditional_losses_15654) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_bottleneck_1_layer_call_and_return_conditional_losses_4635) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_6_layer_call_and_return_conditional_losses_7738) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_1_layer_call_and_return_conditional_losses_15175) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_4_layer_call_and_return_conditional_losses_16058) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_2_layer_call_and_return_conditional_losses_15427) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_12_layer_call_and_return_conditional_losses_19320) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_4_layer_call_and_return_conditional_losses_9080) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_9_layer_call_and_return_conditional_losses_18944) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_6_layer_call_and_return_conditional_losses_18290) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_8_layer_call_and_return_conditional_losses_18699) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_bottleneck_7_layer_call_and_return_conditional_losses_20224) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_bottleneck_9_layer_call_and_return_conditional_losses_6270) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_51_layer_call_and_return_conditional_losses_7779) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_10_layer_call_and_return_conditional_losses_19086) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_14_layer_call_and_return_conditional_losses_19584) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_model_layer_call_and_return_conditional_losses_13001) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_4_layer_call_and_return_conditional_losses_16129) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_6_layer_call_and_return_conditional_losses_8764) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_2_layer_call_and_return_conditional_losses_15553) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_layer_call_and_return_conditional_losses_14795) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_7_layer_call_and_return_conditional_losses_14955) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_25_layer_call_and_return_conditional_losses_7218) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tfsppf_layer_call_and_return_conditional_losses_15924) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_6_layer_call_and_return_conditional_losses_18205) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_45_layer_call_and_return_conditional_losses_8827) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_4_layer_call_and_return_conditional_losses_17944) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_10_layer_call_and_return_conditional_losses_19146) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_c3_4_layer_call_and_return_conditional_losses_7476) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_conv_1_layer_call_and_return_conditional_losses_9920) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_bottleneck_8_layer_call_and_return_conditional_losses_20267) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_sequential_12_layer_call_and_return_conditional_losses_19350) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_tf_bottleneck_5_layer_call_and_return_conditional_losses_5151) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
WARNING:tensorflow:No training configuration found in save file, so the model was *not* compiled. Compile it manually.
WARNING:tensorflow:No training configuration found in save file, so the model was *not* compiled. Compile it manually.
Traceback (most recent call last):
  File "/home/matteo/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 2785, in __setattr__
    super(tracking.AutoTrackable, self).__setattr__(name, value)  # pylint: disable=bad-super-call
AttributeError: can't set attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "prova.py", line 30, in <module>
    layer.dtype = 'float64'
  File "/home/matteo/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 2790, in __setattr__
    'different name.').format(name))
AttributeError: Can't set the attribute "dtype", likely because it conflicts with an existing read-only @property of the object. Please choose a different name.

**Comment by tilakrayal** [comment]
Hi @Matteo-Castrignano,
In order to expedite the trouble-shooting process, could you provide the complete code to reproduce the issue reported here. Thank you!

**Comment by Matteo-Castrignano** [comment]
@tilakrayal 

import tensorflow as tf
import tensorflow_hub as hub
import numpy as np
from tensorflow.python import keras
from tensorflow.python.keras.models import save_model, load_model
from tensorflow.python.keras.preprocessing.image import img_to_array, load_img



#Define model
model_path = "yolov5s_saved_model"


model = load_model(model_path)
model_quant = load_model(model_path)

for w, layer in zip(model.layers, model_quant.layers):
    y = w.get_weights()
    y = [e.astype(keras.backend.floatx()) for e in y]
    layer.trainable = True
    layer.dtype = 'float64'
    layer.set_weights(y)
 
for i,layer in enumerate(model_quant.layers):
    print(layer.get_weights())
    if i==2:
        break

print(np.unique([w.dtype for w in model_quant.get_weights()]))



# #Load images
img_path = "Immagini/000000581781.jpg"
img = load_img(img_path, target_size=(640, 640))
img_tensor = img_to_array(img)
img_tensor = np.expand_dims(img_tensor, axis=0)
print("Tensor type: ", type(img_tensor[0][0][0][0]))
output=model.predict(img_tensor)
print(output)
print("Tensor type: ", type(output[0][0][0]))

**Comment by tilakrayal** [comment]
@Matteo-Castrignano,
The given code contains [indentation errors](https://colab.research.google.com/gist/tilakrayal/bafd8e545cd7c721da4385842a076d06/untitled358.ipynb), please share a colab gist with issue reported or simple stand alone indented code with all dependencies such that we can replicate the issue reported. Thank you!
