### ISSUE TITLE
Are masking layers in CNN supported?

### ISSUE THREAD

**Issue by nox4y** [keras-team/keras#16622]
Will this code work properly? And by "work," I don't mean if this code will throw an error, because it does not. I've looked everywhere, but I can't find an answer to whether Keras supports masking layers with CNN layers.

inputs2 = Input(shape=(12,17))
mask2 = Masking(mask_value=20.0, input_shape=(4, 21))(inputs2)
conv2 = Conv1D(filters=84, kernel_size=8, activation='gelu')(mask2)
drop2 = Dropout(0.3)(conv2) 
pool2 = MaxPooling1D(pool_size=4)(drop2)
flat2 = Flatten()(pool2)

**Comment by tilakrayal** [comment]
@nox4y,
Can you please elaborate about your Feature. Also, please specify the Use Cases for this feature. Thanks!

**Comment by gowthamkpr** [comment]
Linking this issue #411  here

**Comment by qlzh727** [comment]
In short, CNN layers doesn't support masking.

Masking usually expects the inputs to be time sequence, eg, the second dimension of the input is timestep. However, the input to CNN layers are usually [batch, height, width, channel], or [batch, length, channel]. The conv ops couldn't correctly ignore the values in channel/feature, nor could it generate a correct mask for the output (the shape of height/width/length usually changes between inputs/outputs).

For any keras layers that support masking, they usually have a good semantic meaning of time sequences (eg RNN/LSTM), or pass through the input mask to output mask (eg Dense).
