### ISSUE TITLE
model.fit(..., verbose=0) still prints stuff

### ISSUE THREAD

**Issue by m-ahmadi** [keras-team/keras#16637]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Build 17763
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.9.1
- Python version: 3.9
- Bazel version (if compiling from source):
- GPU model and memory:
- Exact command to reproduce:

**Describe the problem**.
The `model.fit(..., verbose=0)` still prints stuff.
This happens in `tensorflow==2.9.1` and `tensorflow==2.9.0`, but it does not happen in `tensorflow==2.8.0`
(first posted [here](https://github.com/tensorflow/tensorflow/issues/56326) then was told to come here)

**Describe the current behavior**.
When calling `model.fit(..., verbose=0)` there are still some stuff being printed

**Describe the expected behavior**.
I expected to see nothing printed when calling `model.fit(..., verbose=0)`

**Standalone code to reproduce the issue**.
```python
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
from tensorflow import keras
from keras.layers import InputLayer, Dense

data = [
	[ [0,0], [0] ],
	[ [0,1], [1] ],
	[ [1,0], [1] ],
	[ [1,1], [0] ],
]
x_train = [i[0] for i in data]
y_train = [i[1] for i in data]

model = keras.Sequential([
	InputLayer(2),
	Dense(units=8, activation='sigmoid'),
	Dense(units=1, activation='sigmoid'),
])
model.compile(optimizer=keras.optimizers.SGD(0.6), loss='mean_squared_error')

model.fit(x_train, y_train, batch_size=1, epochs=500, verbose=0)

print(
	model.predict(  [ [0,0], [0,1], [1,0], [1,1] ]  )
)
```

**Source code / logs**.
![Untitled](https://user-images.githubusercontent.com/16363767/171522020-7946b036-376b-4ca0-8a55-5150263b5a76.png)

**Comment by rajivhockey97** [comment]
Verbose=0 is not defined in the file training.py . PFA the screenshot of keras/engine/training.py . Verbosity= 0 has to be defined. 
![Keras_verbose](https://user-images.githubusercontent.com/25576606/171836841-5185290d-b9e9-4da9-b8dd-e56eaf626b1b.PNG)

**Comment by gadagashwini** [comment]
I could able to reproduce the issue with Tensorflow v 2.9.1 and with tf-nightly-2.10.0.dev20220606 find the gist [here](https://colab.research.google.com/drive/1waKAk39nA95B6x8mt8HDz4NTIq0z3H92?usp=sharing).  

```
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
from tensorflow import keras
from keras.layers import InputLayer, Dense
import tensorflow as tf
print(tf.__version__)

data = [
	[ [0,0], [0] ],
	[ [0,1], [1] ],
	[ [1,0], [1] ],
	[ [1,1], [0] ],
]
x_train = [i[0] for i in data]
y_train = [i[1] for i in data]

model = keras.Sequential([
	InputLayer(2),
	Dense(units=8, activation='sigmoid'),
	Dense(units=1, activation='sigmoid'),
])
model.compile(optimizer=keras.optimizers.SGD(0.6), loss='mean_squared_error')

model.fit(x_train, y_train, batch_size=1, epochs=500, verbose=0)

print(
	model.predict(  [ [0,0], [0,1], [1,0], [1,1] ]  )
)
```
**Output**
```
2.9.1
1/1 [==============================] - 0s 115ms/step
[[0.05208703]
 [0.9335924 ]
 [0.9331978 ]
 [0.08520259]]
```
Thank you!

**Comment by qlzh727** [comment]
Triage notes: from API doc, verbose=0 means silence.

https://www.tensorflow.org/api_docs/python/tf/keras/Model?version=nightly#fit

**Comment by rajivhockey97** [comment]
When using the functional API for model building verbose=0 in the fit method doesn't print any logs.

**Comment by haifeng-jin** [comment]
Thanks everyone for the issue.
This is an expected behavior.
The progressbar is printed by the `model.predict()`.
The verbosity of `model.fit()` and `model.predict()` are controlled separately by their own `verbose` argument.
You may need `model.predict(..., verbose=0)`.

To disable the progress bar, you can do the following.
```py
print("do not print progressbar")
model.predict(  [ [0,0], [0,1], [1,0], [1,1] ], verbose=0)
print("print progressbar")
model.predict(  [ [0,0], [0,1], [1,0], [1,1] ])
```

**Comment by voaneves** [comment]
@haifeng-jin If you're using the model.train_on_batch method, how can you adjust the verbosity level?
