### ISSUE TITLE
custom sparse categorical loss

### ISSUE THREAD

**Issue by Suzan009** [keras-team/keras#16644]
I want to write a custom sparse categorical loss function in numpy or pure tensorflow. It should handle integer target labels and logit or probabilities output. To this end, I have the following:

```python

def softmax(x, axis=-1):
    y = np.exp(x - np.max(x, axis, keepdims=True))
    return y / np.sum(y, axis, keepdims=True)

def categorical_crossentropy(target, output, from_logits=False):
    if from_logits:
        output = softmax(output)
    else:
        output /= output.sum(axis=-1, keepdims=True)
    output = np.clip(output, 1e-7, 1 - 1e-7)
    return np.sum(target * -np.log(output), axis=-1, keepdims=False)
```

 I can do (target is one hot)

```python

y_true = np.array([[0, 1, 0], [0, 0, 1]])
y_pred = np.array([[0.05, 0.95, 0], [0.1, 0.8, 0.1]])

categorical_crossentropy(y_true, y_pred)
array([0.05129329, 2.30258509])
```

But I can not do it (target is an integer, desired).

```python

y_true = np.array([1, 2])
y_pred = np.array([[0.05, 0.95, 0], [0.1, 0.8, 0.1]])

categorical_crossentropy(y_true, y_pred)
ValueError: operands could not be broadcast together with shapes (2,) (2,3) 
```

How to achieve this, where a loss function takes integer target and is able to compute with logits as well as probabilities output. I know there is a built-in function (`sparse_categorical_crossentropy`), but I like to write it in plain numpy or pure tensorflow as a custom loss function.

**Comment by rajivhockey97** [comment]
You have given the wrong shape for y_true in the second example. If the shape was (2,3) the loss works fine. Please find the snippet below which shows that the error calculation works for values other than one hot enconding (2) . 
![Keras_broadcasting_error](https://user-images.githubusercontent.com/25576606/171832543-a72da615-7643-480b-8c91-16ecba319643.PNG)

**Comment by Suzan009** [comment]
@rajivhockey97 no, I think you're missing the point. The `y_true` can't be that format. It should be integer encoding and the output is 3 logits with each integer label. Please see the sparse categorical loss in the official document.

**Comment by sushreebarsa** [comment]
@Suzan009 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thank you!

**Comment by rajivhockey97** [comment]
@Suzan009 You have to implement reduction over batch size in your custom loss. The shapes would match then and you can use integer encoding for y_true.

**Comment by Suzan009** [comment]
@sushreebarsa I already did. Please see the first post and please reopen the issue. Or I have to create a new one. 

@rajivhockey97 can you elaborate and show some code please?

**Comment by Suzan009** [comment]
> @sushreebarsa I already did. Please see the first post and please reopen the issue. Or I have to create a new one.

As now response from assignees, reposting https://github.com/keras-team/keras/issues/16738

**Comment by sushreebarsa** [comment]
@Suzan009 Sorry for the late response!
We will track the new issue.
Thank you!
