### ISSUE TITLE
Returning a Dictionary From a Metric Class

### ISSUE THREAD

**Issue by abheesht17** [keras-team/keras#16665]
In the KerasNLP repository, we are currently working on implementing the ROUGE metric. It inherits from `keras.metrics.Metric`. However, we came across this issue:

```
>>> rg(y_true, y_pred)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/abheesht/python_envs/keras_nlp/lib/python3.8/site-packages/keras/metrics/base_metric.py", line 200, in __call__
    return distributed_training_utils.call_replica_local_fn(
  File "/home/abheesht/python_envs/keras_nlp/lib/python3.8/site-packages/keras/distribute/distributed_training_utils.py", line 60, in call_replica_local_fn
    return fn(*args, **kwargs)
  File "/home/abheesht/python_envs/keras_nlp/lib/python3.8/site-packages/keras/metrics/base_metric.py", line 196, in replica_local_fn
    result_t._metric_obj = self  # pylint: disable=protected-access
AttributeError: 'dict' object has no attribute '_metric_obj'
```

Note that this issue shows up only when we call the object directly, and not when we run it like this:
```
>>> rg.update_state(y_true, y_pred)
>>> rg.result()
{'precision': <tf.Tensor: shape=(), dtype=float32, numpy=0.4>, 'recall': <tf.Tensor: shape=(), dtype=float32, numpy=0.2>, 'f1_score': <tf.Tensor: shape=(), dtype=float32, numpy=0.26666668>}
```

This gives rise to a couple of questions.

- Does Keras support dictionary return type for metrics? If not, we can close this issue immediately.
- If it does support dictionary return type, this is most probably a bug. In particular, this line is the cause of error: https://github.com/keras-team/keras/blob/master/keras/metrics/base_metric.py#L206.

I am of the opinion that there wasn't any intention to support dictionary return type for metrics because this comment mentions that `result_t` is of type tensor: https://github.com/keras-team/keras/blob/master/keras/metrics/base_metric.py#L198. However, it would be really helpful for us KerasNLP folks if we could have support for dictionary (we want to return precision, recall, F1-score for ROUGE metric). The other solution could be to return a tensor of shape (3,) containing the precision, recall, F1-score values (but this isn't very elegant).

CC: @mattdangerw, @chenmoneygithub, @fchollet 

EDIT: Looks like returning a dictionary of scalars is supported according to the doc-string: https://github.com/keras-team/keras/blob/master/keras/metrics/base_metric.py#L88-L89. So, this is most likely a bug.

This is the `result()` function I wrote:
```
def result(self):
        if self._number_of_samples == 0:
            return {"precision": 0.0, "recall": 0.0, "f1_score": 0.0}

        rouge_precision = self._rouge_precision / self._number_of_samples
        rouge_recall = self._rouge_recall / self._number_of_samples
        rouge_f1_score = self._rouge_f1_score / self._number_of_samples
        return {"precision": rouge_precision, "recall": rouge_recall, "f1_score": rouge_f1_score}
```

**Comment by tilakrayal** [comment]
@abheesht17,
To expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thank you!

**Comment by abheesht17** [comment]
@tilakrayal, here is the notebook where I've reproduced the error: https://colab.research.google.com/drive/1dDYLLgjiSZHEHEzC5t0zHIh0ljfYV9P7?usp=sharing. Thanks!

**Comment by tilakrayal** [comment]
@gadagashwini,
I was able to reproduce the issue in tensorflow [v2.8](https://colab.research.google.com/gist/tilakrayal/676b104a9f36b6f7bc261150cf0f1dc6/2-8-keras_metrics_dict_return_bug.ipynb), [v2.9](https://colab.research.google.com/gist/tilakrayal/ee7be053379c5f3267e90a38390480b8/2-9-keras_metrics_dict_return_bug.ipynb) and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/a4f926b98cb925f3afcbf7a270d26bce/2-10-keras_metrics_dict_return_bug.ipynb).

**Comment by tilakrayal** [comment]
@abheesht17,
I tried to execute the code on the latest tf-nightly(2.13.0-dev20230215)  and Keras(2.13.0)
 and it was executed without any issue/error. Could you please check the gist of it [here](https://colab.research.google.com/gist/tilakrayal/ce9181358a847686e6bfc1bd8b7114e6/keras_metrics_dict_return_bug.ipynb) and let us know if it serves the purpose. Also please take a look at the **base_metric.py** file where the **MetricDict** class was updated. Thank you!

https://github.com/keras-team/keras/blob/master/keras/metrics/base_metric.py#L206

```
class _MetricDict(dict):
    """Wrapper for returned dictionary of metrics."""

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self._metric_obj = None
```
