### ISSUE TITLE
Unable to use class_weights| Error: 'class_weight' not supported for 3+ dimensional targets

### ISSUE THREAD

**Issue by iamkashish** [keras-team/keras#16674]
TensorFlow version : 2.7.0
Are you willing to contribute it: Yes

**Describe the feature and the current behavior/state**.
When we want to work with imbalanced data for multi-class segmentation, we can use class_weight upto 3 classes. But for 3+ classes, currently people work with sample_weight. 

**Will this change the current api? How?**
Not at all.

**Who will benefit from this feature?**
The users will get benefit out of it. As they can directly use class_weight for 3+ dimensional targets. Easy to work with multi-class.

**Comment by mattdangerw** [comment]
Do you have a concrete example showing a workflow? That might help us assess this request better. Thank you!

**Comment by tilakrayal** [comment]
@iamkashish,
Could you please check the above @mattdangerw comments and respond to the issue accordingly? Thank you!
