### ISSUE TITLE
Model Documentation Inconsistency on Layer Information and Actual Architecture

### ISSUE THREAD

**Issue by wellsonah2019** [keras-team/keras#16676]
**Background**

Documentation entry: https://www.tensorflow.org/api_docs/python/tf/keras/Sequential

As part of my fuzz testing project, I decided to try and mutate existing models' layers to see if there are any unexpected behaviours. Upon doing so, I found that when we try to rewrite the models' layer information (through the Sequential()._self_tracked_trackables attribute), the actual model architecture remains unchanged even though the information displayed (through Sequential().layers attribute) shows that the new layer has been added.

**Code to reproduce**

```
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM


model = Sequential(layers=[Dense(3, input_shape=(1, ), activation='relu'), Dense(5, activation='relu'), Dense(1, activation='relu')])
model.compile(optimizer='Adam', loss='binary-crossentropy')
layers_before_mutate = (model.layers)
pred_result_before_mutate = model.predict([0.1231245])

model._self_tracked_trackables[1] = LSTM(50)

if layers_before_mutate == model.layers: # Check if the information has been changed
    print("Model information has NOT been changed")
else:
    print("Model information HAS been changed")

pred_result_after_mutate = model.predict([0.1231245])

if pred_result_after_mutate == pred_result_before_mutate: # Check if prediction result is still the same -- indicating unchanged architecture
    print("Model ARCHITECTURE most likely has NOT been changed.")
else:
    print("Model ARCHITECTURE HAS been changed.")
```

There is a possible workaround for this, which is by re-initializing the model again (e.g., using the model json functions).

`model = model_from_json(model.to_json())`

This re-initialization will recognize the mutation created and will construct the architectures as per the information shown in model.layers. However, I do believe that this might be something interesting to look into as inconsistency information may be costly to developers.

**Comment by tilakrayal** [comment]
@wellsonah2019,
Could you please feel free to submit a PR for the requested change to be made. Thank you!

**Comment by wellsonah2019** [comment]
@tilakrayal,
Actually, I am not too sure as to how this could be fixed. I was hoping that perhaps keras developers would look into this as this could introduce a security issue.

**Comment by mattdangerw** [comment]
Thanks for filing!

I don't think this would qualify as a security issue. Almost anything within a layer or model is modifiable, and we can't protect against users deliberately doing something destructive to the model internal state like this. There is a whole host of hidden state on the model that could be modified this way to produce unexpected behavior.
