### ISSUE TITLE
ValueError: No model config found in the file at <tensorflow.python.platform.gfile.GFile object at 0x0000027F490B2F10>. issue please help me

### ISSUE THREAD

**Issue by Henry-Kweon** [keras-team/keras#16679]
- Code
-from  simple_3d_unet import simple_unet_model

model = simple_unet_model(IMG_HEIGHT=128, 
                          IMG_WIDTH=128, 
                          IMG_DEPTH=128, 
                          IMG_CHANNELS=3, 
                          num_classes=4)

model.compile(optimizer = optim, loss=total_loss, metrics=metrics)
print(model.summary())

print(model.input_shape)
print(model.output_shape)

history = model.fit(train_img_datagen,
          steps_per_epoch=steps_per_epoch,
          epochs=1, #epoch 수 조절해보기
          verbose=1,
          validation_data=val_img_datagen,
          validation_steps=val_steps_per_epoch,
          )

model.save('brats_3d.hdf5')
##################################################################

#plot the training and validation IoU and loss at each epoch
loss = history.history['loss']
val_loss = history.history['val_loss']
epochs = range(1, len(loss) + 1)
plt.plot(epochs, loss, 'y', label='Training loss')
plt.plot(epochs, val_loss, 'r', label='Validation loss')
plt.title('Training and validation loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.show()

acc = history.history['accuracy']
val_acc = history.history['val_accuracy']

plt.plot(epochs, acc, 'y', label='Training accuracy')
plt.plot(epochs, val_acc, 'r', label='Validation accuracy')
plt.title('Training and validation accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.show()
#################################################
from keras.models import load_model

#Load model for prediction or continue training

#For continuing training....
#The following gives an error: Unknown loss function: dice_loss_plus_1focal_loss
#This is because the model does not save loss function and metrics. So to compile and 
#continue training we need to provide these as custom_objects.
my_model = load_model('C:/Users/cctv7/Desktop/BraTS2020_TrainingData/brats_3d.hdf5', compile = False)

#So let us add the loss as custom object... but the following throws another error...
#Unknown metric function: iou_score
my_model = load_model('C:/Users/cctv7/Desktop/BraTS2020_TrainingData/brats_3d.hdf5', 
                      custom_objects={'dice_loss_plus_1focal_loss': total_loss})

#Now, let us add the iou_score function we used during our initial training
my_model = load_model('C:/Users/cctv7/Desktop/BraTS2020_TrainingData/brats_3d.hdf5', 
                      custom_objects={'dice_loss_plus_1focal_loss': total_loss,
                                      'iou_score':sm.metrics.IOUScore(threshold=0.5)})

- Error
ValueError: No model config found in the file at <tensorflow.python.platform.gfile.GFile object at 0x0000027F490B2F10>.

  File "C:\Users\cctv7\.spyder-py3\234_train_brats2020_V5.0.py", line 214, in <module>
    my_model = load_model('C:/Users/cctv7/Desktop/BraTS2020_TrainingData/brats_3d.hdf5', compile = False)

  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None

  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\saving\hdf5_format.py", line 182, in load_model_from_hdf5
    raise ValueError(f'No model config found in the file at {filepath}.')

**Comment by tilakrayal** [comment]
@Henry-Kweon,
Code shared contains the indentation errors. Kindly share a colab gist with issue reported or simple stand alone indented code with all dependencies such that we can replicate the issue reported. Thank you!

**Comment by dgrnd4** [comment]
I'm facing the same problem
