### ISSUE TITLE
Add kernel_size output to plot_model

### ISSUE THREAD

**Issue by jerodway** [keras-team/keras#16715]
**System information**.

TensorFlow version 2.9.1:
Are you willing to contribute it (Yes/No) : Yes

**Describe the feature and the current behavior/state**.

Add an argument to plot_model that allows kernel_size to be displayed on the model plot.  Right now there doesn't seem to be a way to have this information displayed.

**Will this change the current api? How?**
I don't think so

**Who will benefit from this feature?**
Anybody that has a created a lot of different model architectures that they would like to visually compare kernel_sizes for.

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**

- Do you want to contribute a PR? (yes/no): yes
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing):

The proposed solution is basically just a copy of the 'show_layer_activations' code, but with the kernel_size property of a layer

PR is here [https://github.com/keras-team/keras/pull/16716](url)

**Comment by tilakrayal** [comment]
@jerodway,
The pr has been assigned for reviewing and once it is merged this issue will move to closed status. Thank you!

**Comment by jerodway** [comment]
> @jerodway, Respective PR #16716 has been closed. Could you please check and confirm the same. Thank you!

The PR has been close as a feature too specialized for inclusion. Closing this issue.
