### ISSUE TITLE
No validation exists for special characters in name in InputLayer

### ISSUE THREAD

**Issue by ronigober** [keras-team/keras#16717]
Hi, 
When I set a name with special characters for InputLayer as for example  - > Input(shape=self.input_shape, name="hey:)") - it works fine, but when I set it in other layers then input layer I get the validation error: 
ValueError: 'hey:)/' is not a valid root scope name. A root scope name has to match the following pattern: ^[A-Za-z0-9.][A-Za-z0-9_.\\/>-]*$

I think you need to add the validation for name also in InputLayer thanks!

**Comment by sushreebarsa** [comment]
@ronigober 
In order to expedite the trouble-shooting process, please provide mode details and  a code snippet to reproduce the issue reported here. Thanks!
