### ISSUE TITLE
Indexing a ragged tensor over a non-ragged index fails in tf.keras.Model

### ISSUE THREAD

**Issue by pstjohn** [keras-team/keras#16719]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google colab, mac 
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): tf 2.9.1, nightly
- Python version: 3.7
- Exact command to reproduce:

```python
rt = tf.ragged.constant([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                         [[2, 3, 4], [5, 6, 7]],
                         [[3, 4, 5]]], ragged_rank=1)

rt_input = tf.keras.Input(shape=(None, 3), dtype=tf.int32)
model = tf.keras.Model([rt_input], [rt_input[:, :, 0]])
model(rt)
```

**Describe the problem**.
Indexing a ragged tensor over a non-ragged dimension throws an error inside a tf.keras.Model. I'm trying to slice a ragged tensor containing a known amount of features, i.e., with shape (batch_size, ragged_dim, known_feature_dim) by the last axis inside a Keras model, hopefully returning a (batch_size, ragged_dim) tensor of features.
This works in eager mode with a tf.ragged.constant, but a model (that works with a tf.constant) fails when passed the same ragged constant.

**Describe the current behavior**.
Currently raises
```python
ValueError: Exception encountered when calling layer "tf.__operators__.getitem" "  f"(type SlicingOpLambda).

TypeError: object of type 'RaggedTensor' has no len()
```
**Describe the expected behavior**.
indexing the ragged tensor outside of keras works as expected:
```python
>>> rt[:, :, 0]
<tf.RaggedTensor [[1, 4, 7], [2, 5], [3]]>
```

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no): perhaps, but it's not a code base I'm very familiar with

**Standalone code to reproduce the issue**.

https://colab.research.google.com/drive/1eSEdKidC1A4kw5EYeYimKrSEHkV6EndS?usp=sharing

Moved from tensorflow/tensorflow#56565

**Comment by gowthamkpr** [comment]
@pstjohn Please set the argument `ragged=True` in `tf.keras.Input()` if you are using ragged tensors. Please find the gist [here](https://colab.sandbox.google.com/gist/gowthamkpr/410ca2e7f4e36e235c327b95d677e2cb/16719.ipynb). Thanks!
