### ISSUE TITLE
Is there something wrong in OrthogonalRegularizer?

### ISSUE THREAD

**Issue by JingangQu** [keras-team/keras#16718]
https://github.com/keras-team/keras/blob/07e13740fd181fc3ddec7d9a594d8a08666645f6/keras/regularizers.py#L371

Maybe the right way is to sum up the absolute value of `product_no_diagonal`, as follows:
         return self.factor * 0.5 * tf.reduce_sum(tf.abs(product_no_diagonal)) / num_pairs

**Comment by tilakrayal** [comment]
@JingangQu,
To expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thank you!

**Comment by tilakrayal** [comment]
@JingangQu,
This issue has been resolved in the tf-nightly version. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/efbd438cfeee49b28d4a7a7b3ffef242/16682.ipynb). Thank you!

**Comment by JingangQu** [comment]
Ok, thanks for your reply!
