### ISSUE TITLE
BatchNormalization with virtual_batch_size breaks load_model()

### ISSUE THREAD

**Issue by yellowdolphin** [keras-team/keras#16713]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux (colab)
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): tf 2.4.1, 2.8.2, nightly
- Python version: 
- Bazel version (if compiling from source):
- GPU model and memory:
- Exact command to reproduce: https://colab.research.google.com/drive/1QN7EPzr0MaYnHAdzVc2ucaMO544aQYvY?usp=sharing

**Describe the problem**.

Passing `virtual_batch_size=int` to BatchNormalization performs "Ghost Batch Normalization", which creates virtual sub-batches which are each normalized separately.

Loading a keras model with such a layer fails with a ValueError.

**Describe the current behavior**.

In BatchNormalizationBase, the `axis` attrib is incremented, e.g. from [3] to [4], I think this happens here: https://github.com/keras-team/keras/blob/07e13740fd181fc3ddec7d9a594d8a08666645f6/keras/layers/normalization/batch_normalization.py#L382

Then, when self.build() is called upon load_model(), `axis` is checked against input rank, which fails. This check has moved in the current version to `validate_axis()` in keras/utils/tf_utils.py:

https://github.com/keras-team/keras/blob/07e13740fd181fc3ddec7d9a594d8a08666645f6/keras/utils/tf_utils.py#L228

**Describe the expected behavior**.

It seems there is some confusion in the code, whether or not `axis` is allowed to be larger than rank - 1.

**Standalone code to reproduce the issue**.

https://colab.research.google.com/drive/1QN7EPzr0MaYnHAdzVc2ucaMO544aQYvY?usp=sharing

**Source code / logs**.
```
/usr/local/lib/python3.7/dist-packages/keras/layers/normalization/batch_normalization.py in build(self, input_shape)
    311       if x < 0 or x >= ndims:
    312         raise ValueError(
--> 313             f'Invalid axis. Expected 0 <= axis < inputs.rank (with '
    314             f'inputs.rank={ndims}). Received: layer.axis={self.axis}')
    315     if len(self.axis) != len(set(self.axis)):

ValueError: Invalid axis. Expected 0 <= axis < inputs.rank (with inputs.rank=4). Received: layer.axis=ListWrapper([4])
```

**Comment by sushreebarsa** [comment]
@gadagashwini I was able to replicate the issue on colab, please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/c62641d5dc98073ab58aeecaf15e0d75/virtual_batch_size_issue.ipynb#scrollTo=MVCA4r0tSOXB). Thank you!

**Comment by fchollet** [comment]
As you can see in the API docs, virtual batch normalization is not *intended* to be supported. The argument is not documented, and was remove about one year ago. https://keras.io/api/layers/normalization_layers/batch_normalization/

The argument is accepted only for backwards compatibility reasons. I recommend that you do not rely on it. Because it is no longer supported, we won't focus on fixing the issue (but if you have a fix we will review your PR).

**Comment by yellowdolphin** [comment]
I did some experiments with virtual_batch_size using the following workaround for saving/loading the model:

```
try:
    model.save('my_model.h5')
    model = tf.keras.models.load_model('my_model.h5')

except ValueError as e:
    if 'axis' in str(e):
        # Work around BatchNormalization/VBS bug, axis must be 3 during save, else 4
        for l in model.layers:
            if isinstance(l, tf.keras.layers.BatchNormalization) and l.virtual_batch_size is not None:
                #print("axis before save:", l.axis[0])  # 4
                if hasattr(l.axis, '__len__'):
                    l.axis[0] -= 1
                else:
                    l.axis -= 1

        model.save('my_model.h5')
        model = tf.keras.models.load_model('my_model.h5')

        for l in model.layers:
            if isinstance(l, tf.keras.layers.BatchNormalization) and l.virtual_batch_size is not None:
                #print("axis after load:", l.axis[0])  # 4 (!)
                if hasattr(l.axis, '__len__') and l.axis[0] == 3:
                    l.axis[0] += 1
                elif l.axis == 3:
                    l.axis += 1
                #print("restored axis:", l.axis[0])
    else:
        raise
```
However, I did not find any benefits in using `virtual_batch_size`, e.g. in combination with small batch_size and gradient accumulation. Hence, I will not attempt to find a fix/PR, nor advocate for officially supporting the feature. 

Feel free to close the issue.

**Comment by gadagashwini** [comment]
Closing as this issue is resolved by workaround mentioned in the above [comment](https://github.com/keras-team/keras/issues/16713#issuecomment-1180368482). Thank you!
