### ISSUE TITLE
Incorrectly rendered tables

### ISSUE THREAD

**Issue by Rishit-dagli** [keras-team/keras#16727]
**Describe the problem**.

The API docs for multiple pages in `keras.applications` are not rendered properly, see the tables on:

- https://www.tensorflow.org/api_docs/python/tf/keras/applications/nasnet
- https://www.tensorflow.org/api_docs/python/tf/keras/applications/mobilenet_v2
- https://www.tensorflow.org/api_docs/python/tf/keras/applications/mobilenet

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no): yes
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing):

**Comment by chunduriv** [comment]
@Rishit-dagli,

Thank you for reporting the issue. I have submitted [PR](https://github.com/keras-team/keras/pull/16839) to fix the issue.
