### ISSUE TITLE
custom sparse categorical loss 

### ISSUE THREAD

**Issue by Suzan009** [keras-team/keras#16738]
I want to write a custom sparse categorical loss function in numpy or pure tensorflow. It should handle integer target labels and logit or probabilities output. To this end, I have the following:

```python

def softmax(x, axis=-1):
    y = np.exp(x - np.max(x, axis, keepdims=True))
    return y / np.sum(y, axis, keepdims=True)

def categorical_crossentropy(target, output, from_logits=False):
    if from_logits:
        output = softmax(output)
    else:
        output /= output.sum(axis=-1, keepdims=True)
    output = np.clip(output, 1e-7, 1 - 1e-7)
    return np.sum(target * -np.log(output), axis=-1, keepdims=False)
```

 I can do (target is one hot)

```python

y_true = np.array([[0, 1, 0], [0, 0, 1]])
y_pred = np.array([[0.05, 0.95, 0], [0.1, 0.8, 0.1]])

categorical_crossentropy(y_true, y_pred)
array([0.05129329, 2.30258509])
```

But I can not do it (target is an integer, desired).

```python

y_true = np.array([1, 2])
y_pred = np.array([[0.05, 0.95, 0], [0.1, 0.8, 0.1]])

categorical_crossentropy(y_true, y_pred)
ValueError: operands could not be broadcast together with shapes (2,) (2,3) 
```

How to achieve this, where a loss function takes integer target and is able to compute with logits as well as probabilities output. I know there is a built-in function (`sparse_categorical_crossentropy`), but I like to write it in plain numpy or pure tensorflow as a custom loss function.

**Comment by Suzan009** [comment]
can you elaborate with full working code? what is p and y in your above code?

**Comment by gadagashwini** [comment]
Hi @Suzan009, 
You can add extra dimension to your y_true value.

```
y_true = np.array([1, 2])
y_true = np.expand_dims(y_true, axis=-1)
y_pred = np.array([[0.05, 0.95, 0], [0.1, 0.8, 0.1]])

categorical_crossentropy(y_true, y_pred)
```

**Output**
`array([19.16512122,  9.65662747])`

**Comment by Suzan009** [comment]
@gadagashwini but both output should be same, but it gives different output. 

```
y_true = np.array([[0, 1, 0], [0, 0, 1]])
y_pred = np.array([[0.05, 0.95, 0], [0.1, 0.8, 0.1]])
categorical_crossentropy(y_true, y_pred)

y_true = np.array([1, 2])
y_true = np.expand_dims(y_true, axis=-1)
y_pred = np.array([[0.05, 0.95, 0], [0.1, 0.8, 0.1]])
categorical_crossentropy(y_true, y_pred)
```

@lucasdavid workaround is working, but I'm trying to understand it a bit. Will close the issue afterwards.

**Comment by gadagashwini** [comment]
@Suzan009, Did you a get chance to look into the issue. Thank you!
