### ISSUE TITLE
[Bug Report] ResNetRS101.__doc__ is missing

### ISSUE THREAD

**Issue by asukakenji** [keras-team/keras#16749]
`ResNetRS101.__doc__` is missing, as seen from the code below:
https://github.com/keras-team/keras/blob/7dd01b12c275d8f5f9c1f82014deb302ed14560c/keras/applications/resnet_rs.py#L979-L984

When getting help on `ResNetRS50` in an interactive Python session using the following code:
```py
import tensorflow as tf
help(tf.keras.applications.ResNetRS50)
```

The result is:
```
Help on function ResNetRS50 in module keras.applications.resnet_rs:

ResNetRS50(include_top=True, weights='imagenet', classes=1000, input_shape=None, input_tensor=None, pooling=None, classifier_activation='softmax', include_preprocessing=True)
    Instantiates the ResNetRS50 architecture.
    
    Reference:
    [Revisiting ResNets: Improved Training and Scaling Strategies](
    https://arxiv.org/pdf/2103.07579.pdf)
    ...
(END)
```

However, when the same is applied to `ResNetRS101`, the result is:
```
Help on function ResNetRS101 in module keras.applications.resnet_rs:

ResNetRS101(include_top=True, weights='imagenet', classes=1000, input_shape=None, input_tensor=None, pooling=None, classifier_activation='softmax', include_preprocessing=True)
    Build ResNet-RS101 model.
(END)
```

**Comment by sushreebarsa** [comment]
@asukakenji Sorry for the late response!
I hope ResNetRS101.__doc__ is now reflecting 
https://github.com/keras-team/keras/blob/dc01c981d7f67ad195bfc3ca983b316f1719ccc1/keras/applications/resnet_rs.py#L979-L983
Could you please move this issue to closed status if it is resolved. Thank you!

**Comment by asukakenji** [comment]
Fixed by https://github.com/keras-team/keras/pull/16751
