### ISSUE TITLE
How to put my object detection dataset in this specific COCO annotation format?

### ISSUE THREAD

**Issue by allansdefreitas** [keras-team/keras#16748]
Hello,

I'm running this Keras implementation of [retinanet](https://github.com/keras-team/keras-io/blob/master/examples/vision/retinanet.py) and it works perfectly on COCO dataset obtained from tfds.load().

I noticed that the downloaded TFrecords (from tfds.load() ) contain COCO annotations in a different way from traditional COCO annotations and that is the cause of all problems. 

The COCO annotation format, creates **one annotation element for each element in image**, whereas Tensorflow COCO format (obtained from tfds), crates **one single annotation for each image and inside this annotation, there is a list of objects and their positions (bboxes)** That is the main difference.

![Comparing annotations format](https://user-images.githubusercontent.com/16272954/177061168-9869e899-f3b3-4b70-a081-73c5fb18a39b.jpeg)

**Is there a way to put my dataset in this Tensorflow COCO format?**

Thanks in advance,
Allan Freitas

System informations:
Ubuntu
Tensorflow: 2.9.1
Python: 3.7.13

**Comment by tilakrayal** [comment]
@allansdefreitas,
To expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here or the error log. It helps to debug the issue. Thank you!

**Comment by allansdefreitas** [comment]
Let me prepare and send to you...

**Comment by allansdefreitas** [comment]
> @allansdefreitas, To expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here or the error log. It helps to debug the issue. Thank you!

@tilakrayal here you can find the notebook: [https://github.com/allansdefreitas/Deep-Learning-Experiments/blob/master/retinanet_coco_error.ipynb](https://github.com/allansdefreitas/Deep-Learning-Experiments/blob/master/retinanet_coco_error.ipynb)

**Comment by tilakrayal** [comment]
@allansdefreitas,
I was facing different error while trying to execute the given code. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/7a9e37d3c2f7fe3be05ec6412d66e61a/retinanet_coco_error.ipynb). Thank you!

**Comment by allansdefreitas** [comment]
> @allansdefreitas, I was facing different error while trying to execute the given code. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/7a9e37d3c2f7fe3be05ec6412d66e61a/retinanet_coco_error.ipynb). Thank you!

It seems like if the content of TFRecords is encoded..

**Comment by tilakrayal** [comment]
@allansdefreitas,
Could you please provide the TFRecord to debug the issue. Thank you!

**Comment by allansdefreitas** [comment]
> @allansdefreitas, Could you please provide the TFRecord to debug the issue. Thank you!

Hi, @tilakrayal.

You can download the TFRecords, running via terminal: `curl -L "https://app.roboflow.com/ds/XqoiwGXC8L?key=NyDE34g8vI" > roboflow.zip; unzip roboflow.zip; rm roboflow.zip`

**Comment by tilakrayal** [comment]
@allansdefreitas,
After uploading the `tfrecord`, I tried to execute the code and faced the same issue. Kindly find the gist [here](https://colab.research.google.com/gist/tilakrayal/5f1fd957ec4b055bc6c666a0fb156121/retinanet_coco_error.ipynb) and please try to define the `test_dataset` . Thank you!
