### ISSUE TITLE
Model fails to save after build

### ISSUE THREAD

**Issue by enaskopelja** [keras-team/keras#16759]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): `Linux Arch 5.18.9`
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): `2.9`
- Python version: `3.9`
- Bazel version (if compiling from source): /
- GPU model and memory:  N/A
- Exact command to reproduce: see code below

**Describe the problem**.
Keras Model fails to save (with `tf.keras.models.save_model`) after being built with error:
```bash
Model cannot be saved either because the input shape is not available or because the forward pass of the model is not defined. *To define a forward pass, please override `Model.call()`. To specify an input shape, either call `build(input_shape)` directly, or call the model on actual data using `Model()`, `Model.fit()`, or `Model.predict()`*. If you have a custom training step, please make sure to invoke the forward pass in train step through `Model.__call__`, i.e. `model(inputs)`, as opposed to `model.call()`.
```

The model can be saved after calling the model directly but not after calling `build(input_shape)` as directed above.

**Standalone code to reproduce the issue**.
Colab: [here](https://colab.research.google.com/drive/1Fm1oOg6PQGQ29VDi_RUzxC7uLh6gD3di#scrollTo=VNTQ6aJWqPD2) 

**Source code / logs**.
```python
import tensorflow as tf

class Model(tf.keras.Model):
    def call(self, inputs):
        sum1 = tf.reduce_sum(inputs["input1"])
        sum2 = tf.reduce_sum(inputs["input2"])
        return {"sum1": sum1, "sum2": sum2}

if __name__ == "__main__":
    import numpy as np

    model = Model()
    model.build(
        {
            "input1": tf.TensorShape([None, 5, 5]),
            "input2": tf.TensorShape([None, 5, 5]),
        }
    )
    model.summary()

    tf.keras.models.save_model(model, "model")  # does not work here
    predictions = model.predict(
        {
            "input1": np.random.rand(1, 5, 5),
            "input2": np.random.rand(1, 5, 5),
        }
    )
    print(predictions)
    
    tf.keras.models.save_model(model, "model")  # works here
```
logs: 

```bash
Model cannot be saved either because the input shape is not available or because the forward pass of the model is not defined. *To define a forward pass, please override `Model.call()`. To specify an input shape, either call `build(input_shape)` directly, or call the model on actual data using `Model()`, `Model.fit()`, or `Model.predict()`*. If you have a custom training step, please make sure to invoke the forward pass in train step through `Model.__call__`, i.e. `model(inputs)`, as opposed to `model.call()`.

```

**Comment by tilakrayal** [comment]
Hi @enaskopelja,
As a workaround you may want to try to use` tf.saved_model.save(model, name)` and see if that works.

Please go through this [document](https://keras.io/api/models/model_saving_apis/) which explains the difference between tf.saved_model.save() and model.save()

Keras SavedModel (model.save()) uses [tf.saved_model.save](https://www.tensorflow.org/api_docs/python/tf/saved_model/save) to save the model and all trackable objects attached to the model (e.g. layers and variables). The model config, weights, and optimizer are saved in the SavedModel. Thank you!

**Comment by enaskopelja** [comment]
Hi @tilakrayal, 

unfortunately I get the same error with `tf.saved_model.save` (see updated colab notebook [here](https://colab.research.google.com/drive/1Fm1oOg6PQGQ29VDi_RUzxC7uLh6gD3di?usp=sharing)).

**Comment by tilakrayal** [comment]
@gowthamkpr,
I was able to reproduce the issue on tensorflow v2.8, v2.9 and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/809d2357c856e8a953f785c71a30fbcb/16759.ipynb).

**Comment by gowthamkpr** [comment]
@enaskopelja The issue here is that the forward pass has not been defined. Please go through a similar issue for which solution is discussed [here](https://stackoverflow.com/questions/71299786/model-cannot-be-saved-either-because-the-input-shape-is-not-available-or-because). Try adding `model.fit()` before saving the model.
