### ISSUE TITLE
Can't pickle optimizer

### ISSUE THREAD

**Issue by 7NoteDancing** [keras-team/keras#16752]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 11
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.9.1
- Python version: 3.7
- Bazel version (if compiling from source):
- GPU model and memory:
- Exact command to reproduce:

**Describe the problem**.

Can't pickle optimizer

**Describe the current behavior**.

AttributeError: Can't pickle local object 'make_gradient_clipnorm_fn.<locals>.<lambda>'

**Describe the expected behavior**.

**Standalone code to reproduce the issue**.

import tensorflow as tf
import pickle
output_file=open('save.dat','wb')
pickle.dump(tf.keras.optimizers.Adam(),output_file).

**Comment by tilakrayal** [comment]
@gadagashwini,
I was able to reproduce the issue on tensorflow v2.8, v2.9 and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/d3aa53a8eb0d27983f8767dad7052f52/16752.ipynb).

**Comment by rajivhockey97** [comment]
https://github.com/NREL/phygnn/issues/16
It is mentioned in the last comment that the optimizers can't be pickled and we have two other functions

**Comment by gadagashwini** [comment]
Hi @7NoteDancing, You can First, save the optimizer weights: `np.save(path, optimizer.get_weights())`.
Take a look at workaround mentioned on similar thread [here](https://stackoverflow.com/a/63089235/14290244). Thank you!

**Comment by 7NoteDancing** [comment]
> Hi @7NoteDancing, You can First, save the optimizer weights: `np.save(path, optimizer.get_weights())`. Take a look at workaround mentioned on similar thread [here](https://stackoverflow.com/a/63089235/14290244). Thank you!

I want to save optimizer function.

**Comment by 7NoteDancing** [comment]
> Hi @7NoteDancing, You can use `get_config()` method. For more details refer [link](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Optimizer?version=nightly#get_config). Thank you !

Why when I used tf.keras.optimizers.Optimizer.from_config() to recover optimizer,an error occurred?
TypeError: Unexpected keyword argument passed to optimizer: learning_rate. Allowed kwargs are {'clipnorm', 'clipvalue', 'decay', 'lr', 'global_clipnorm'}.

**Comment by gadagashwini** [comment]
Hi @7NoteDancing, You try like below sample code snippet
```
import tensorflow as tf
import numpy as np

inputs = tf.keras.Input((1,))
outputs = tf.keras.layers.Dense(10)(inputs)
model = tf.keras.Model(inputs=inputs, outputs=outputs)

model.compile(optimizer=tf.optimizers.SGD(0.1), loss=tf.losses.mse)
model.fit(np.zeros((4, 1)), np.zeros((4, 10)))
config = model.optimizer.get_config()
model.optimizer.from_config(config)
```
Thank you!

**Comment by gadagashwini** [comment]
Closing as stale. Please reopen if you'd like to work on this further.
