### ISSUE TITLE
How does Keras Train their Applications? No Code or Documentation

### ISSUE THREAD

**Issue by OUStudent** [keras-team/keras#16794]
**URL(s) with the issue:**.

https://keras.io/api/applications/

**Description of issue (what needs to be changed):**.

Keras applications are pre-trained CNN models on ImageNet that can be utilized for transfer learning or for utilizing a preconstructed CNN architecture. The documentation does not describe anywhere where the code is located on how the models were trained to obtain the final ImageNet weights.

**Benefit of including this code/documentation**.

1) Allows for open source code on how state of the art models are trained and constructed from scratch

2) Allows to see any preprocessing and image augmentation techniques, optimizers, regularizes, etc,  that were applied to the model, in order to apply the same methodology to a current transfer learning dataset

**Comment by tilakrayal** [comment]
@OUStudent,
Could you please check this doc [link](https://keras.io/api/applications/) and confirm which you are referring to. The provided doc link delivers the information on Keras application. Thank you!

**Comment by OUStudent** [comment]
@tilakrayal 
I am talking about the entire document. There is no comment or documentation in the official link you gave on how the image net weights are obtained or how the models were trained. My issue is notify Keras team to provide this information.

**Comment by OUStudent** [comment]
> @OUStudent, Could you please check this doc [link](https://keras.io/api/applications/) and confirm which you are looking for. The provided doc link delivers the information on Keras application. Thank you!

I am talking about the entire document. There is no comment or documentation in the official link you gave on how the image net weights are obtained or how the models were trained. My purpose is notify Keras team of this in order to provide this information as it allows users to know how the models were trained to obtain the imagenet weights

**Comment by tilakrayal** [comment]
@OUStudent,
Could you please try to open the link of the available models( `Xception`, `VGG16`, `VGG19`, `ResNet50`), It will provided the required details as mentioned [here](https://keras.io/api/applications/xception/). Thank you!

**Comment by OUStudent** [comment]
> @OUStudent, Could you please try to open the link of the available models( `Xception`, `VGG16`, `VGG19`, `ResNet50`), It provides the required details as mentioned [here](https://keras.io/api/applications/xception/). Thank you!

Thank you. It seems that the code for how the models are created are detailed but what about code for training? Other than the paper, I don't see those details when I open any specific model link.
