### ISSUE TITLE
[URGENT] There is less inputs received while giving the exact number of inputs required 2.0

### ISSUE THREAD

**Issue by 20Saboteur20** [keras-team/keras#16849]
This is a follow up to this issue #16825, which I just closed from my previous account , given that it has been just sanctioned by GitHub because I am living in a US sanctioned country , because of this I can't do anything with the previous account.
continuing with the issue , the assigned account @tilakrayal has already asked me to create a gist ; so here it is https://gist.github.com/20Saboteur20/209e8236e1655125e555d76749bc3d2b
the used files are here , https://drive.google.com/drive/folders/1728ZfGo6JUDhNODMDdC3pH6HOxqS7oiB?usp=sharing
and as a precaution here I included them as zip
[Project Files.zip](https://github.com/keras-team/keras/files/9222144/Project.Files.zip)
.

**Comment by tilakrayal** [comment]
@gadagashwini,
I was able to reproduce the issue on tensorflow [v2.8](https://colab.research.google.com/gist/tilakrayal/5df9137af0838c148edb46e720bb07ba/2-8university_project.ipynb), [v2.9](https://colab.research.google.com/gist/tilakrayal/15494785b3fa1709b7a323e88701b180/2_9university_project.ipynb) and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/2bbd9c2c7032c117f65f216bc4337840/nightlyuniversity_project.ipynb).

**Comment by gowthamkpr** [comment]
@20Saboteur20 This is similar to this [issue](https://github.com/tensorflow/tensorflow/issues/36508). Please take a look at the solution provided [here](https://stackoverflow.com/questions/72993170/unknownerror-graph-execution-error-fail-to-find-the-dnn-implementation-google). Thanks!
