### ISSUE TITLE
What is the difference between model.__call__ on TensorSpec and Tensor

### ISSUE THREAD

**Issue by gowthamkpr** [keras-team/keras#16862]
Attaching this issue 

https://github.com/tensorflow/tensorflow/issues/56677

**Comment by divyashreepathihalli** [comment]
this would be a better place to ask this question - https://discuss.tensorflow.org/.

**Comment by qlzh727** [comment]
See https://github.com/keras-team/keras/blob/30bf872258415cd4a83ac1a33b031cc804981a9c/keras/engine/base_layer.py#L1019. Keras layer/model only care about tensor or tensor like objects (np, list, etc). All the other types are filtered and not reach layer.call() method.

**Comment by KingsleyLiu-NV** [comment]
@qlzh727  I don't think feeding `tf.keras.Input(shape=(10,))` will not get the model executed: if  I replace `tf.print()` with `print()`, I can see the log like this:

```shell
**************Feed TensorSpec*************
=============Demo.call()============
=============TestLayer.call()============
**************Feed Tensor*************
=============Demo.call()============
=============TestLayer.call()============
```

Can you explain this? I think the model is executed when feeding `tf.keras.Input(shape=(10,))` but `tf.print()` does **NOT** print the log, while `print()` does. This is really confusing for users.

**Comment by qlzh727** [comment]
There are differences between tf.print and python print.

tf.print is adding an op to the graph, which will print out tensor values when the grpah is executed. If there isn't an graph/tf.function to be executed (eg in your tf.keras.Input() case, it is just a placeholder), the tf.print will not give u anything.

print is pure python funciton, which will be executed when trace a tf.function (doesn't execute the graph with input tensors), which will give you some output even you don't have any real inputs.

**Comment by KingsleyLiu-NV** [comment]
Understood, thanks.
