### ISSUE TITLE
ValueError: Unknown layer: PruneLowMagnitude. Please ensure this object is passed to the `custom_objects` argument. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.

### ISSUE THREAD

**Issue by MiraGaikwad** [keras-team/keras#16873]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): I have used pre-trained model for InceptionNetV3 and last layer was train and then doing pruning on it. 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google colab
- TensorFlow installed from (source or binary): on colab 
- TensorFlow version (use command below): 2.8
- Python version: Python 3.7.13
- Bazel version (if compiling from source):
- GPU model and memory: Colab Pro +
- Exact command to reproduce:

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with:
python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"

**Describe the problem**.

1. I have used pre-trained model for InceptionNetV3 and only trained last layer. I could save load that model.
2. I then pruned that model and saved. But when I tried loading thar model I got error as 

'ValueError: Unknown layer: PruneLowMagnitude. Please ensure this object is passed to the `custom_objects` argument. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.'

It worked well on MobileNetV2, InceptionResNet but not working on VGG19 and InceptionnetV3

I have used below code to prun the model 

import tensorflow_model_optimization as tfmot
prune_low_magnitude = tfmot.sparsity.keras.prune_low_magnitude
#Compute end step to finish pruning after 2 epochs.
batch_size = 10
epochs = 2

end_step = np.ceil(train_imgs.shape[0]//batch_size).astype(np.int32) * epochs

#Define model for pruning.
pruning_params = {
      'pruning_schedule': tfmot.sparsity.keras.PolynomialDecay(initial_sparsity=0.50,
                                                               final_sparsity=0.80,
                                                               begin_step=0,
                                                               end_step=end_step)
}

model_for_pruning = prune_low_magnitude(InceptionnetV3_model_base, **pruning_params)
#`prune_low_magnitude` requires a recompile.
model_for_pruning.compile(optimizer='adam',
              # loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              loss=['categorical_crossentropy'],
              metrics=['accuracy'])

model_for_pruning.summary()

Describe the problem clearly here. Be sure to convey here why it's a bug in Keras or why the requested feature is needed.

**Describe the current behavior**.

**Describe the expected behavior**.

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no):
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**.

Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Source code / logs**.

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by tilakrayal** [comment]
@MiraGaikwad,
I ran the code and faced a different error, please find the gist [here](https://colab.research.google.com/gist/tilakrayal/0fe248dd0adeb252792242f8e922ecd9/untitled476.ipynb) and share all dependencies to replicate the issue or share a colab gist with the reported error.

**Comment by MiraGaikwad** [comment]
@tilakrayal Could you please share your email id ? I can give access to google drive where I have dataset to replicate the process ?

Cheers
Mira

**Comment by tilakrayal** [comment]
@MiraGaikwad,
Could you please attach the code here or provide the colab gist to reproduce the issue. Thank you!

**Comment by MiraGaikwad** [comment]
@tilakrayal - Please find the attached code - 

after the pruned code while loading pruned model you can see the error in below fine - 
(
[Pruned_Formatted_InceptionnetV3_01.zip](https://github.com/keras-team/keras/files/9330501/Pruned_Formatted_InceptionnetV3_01.zip)
)

Dataset I used is from this link - https://www.kaggle.com/code/brsdincer/land-use-scene-classification-all-process/data

**Comment by tilakrayal** [comment]
@gadagashwini,
I was able to reproduce the issue on tensorflow v2.8, v2.9. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/2609ab440a1b578db25729db1e7f2613/16873.ipynb).

**Comment by MiraGaikwad** [comment]
@LukeWood , @rchao , @tilakrayal  Could you please let me know if there is any update on this issue ?

**Comment by rchao** [comment]
Thanks for checking in @MiraGaikwad - if you could re-build `tensorflow_model_optimization` library, can you follow what the error message suggests, "Please ensure this object is passed to the custom_objects argument" and see if it helps in any way?

**Comment by MiraGaikwad** [comment]
@rchao - Yeah, I already tried that but no luck..

**Comment by SuryanarayanaY** [comment]
Hello, Thank you for reporting an issue.

We're currently in the process of migrating the new Keras 3 code base from keras-team/keras-core to keras-team/keras.
Consequently, This issue may not be relevant to the Keras 3 code base . After the migration is successfully completed, feel free to reopen this Issue at keras-team/keras if you believe it remains relevant to the Keras 3 code base. If instead this Issue is a bug or security issue in legacy tf.keras, you can instead report a new issue at [keras-team/tf-keras](https://github.com/keras-team/tf-keras/issues), which hosts the TensorFlow-only, legacy version of Keras.

To know more about Keras 3, please read https://keras.io/keras_core/announcement/
