### ISSUE TITLE
Returning model with best weights when EarlyStopping is not triggered and restore_best_weights=True

### ISSUE THREAD

**Issue by cevheck** [keras-team/keras#16876]
TensorFlow version (you are using): 
TF 2.5.0

Are you willing to contribute it (Yes) :

**Describe the feature and the current behavior/state**.
At this moment, EarlyStopping will only return the best performing model when EarlyStopping occurs due to no increase in performance over "patience" amount of epochs. Looking at the case where the complete training process is completed without invoking early stopping (e.g. patience is set way to high), most people would like to get the best performing model as a returned model. As the EarlyStopping callback tracks this best weights, it would be almost trivial to integrate this functionality.

Describe the feature clearly here. Be sure to convey here why the requested feature is needed. Any brief description about the use-case would help.
Updating the returned model when complete training occurs in the EarlyStopping callback. In this instant this is possible afterwards by using following code:
        
        ES = EarlyStopping(patience=20, restore_best_weights=True)
        callbacks = [ES]
        model.fit(x=train_input, y=train_output, epochs=400, batch_size=64, callbacks=callbacks, validation_split=0.25)

       if ES.stopped_epoch == 0:   # ES did not halt training and thus not update model to best one seen
            model.set_weights(ES.best_weights)   # does however save the best weights under ES.best_weights
            print(f"Restoring model weights from the end of the best epoch: {ES.best_epoch + 1}.")

**Will this change the current api? How?**
No undesired behaviour should occur

**Who will benefit from this feature?**
Will return desired behaviour for most people using EarlyStopping

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**

- Do you want to contribute a PR? (No):
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing):
Update the on train end function as follows:

        def on_train_end(self, logs=None):
                  if self.stopped_epoch > 0 and self.verbose > 0:
                        io_utils.print_msg( f"Epoch {self.stopped_epoch + 1}: early stopping")
                   else:
                        self.model.set_weights(self.best_weights)
                        io_utils.print_msg(
                        "Restoring model weights from "
                        "the end of the best epoch: "
                        f"{self.best_epoch + 1}."
                    )

**Comment by jbischof** [comment]
This functionality is available in the `ModelCheckpoint` callback ([doc](https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/ModelCheckpoint)) if you change the default params to `save_best_only=True`.

**Comment by cevheck** [comment]
Agreed that the functionality is already provided in ModelCheckpoint, it just seemed a good addition to me to add it to the EarlyStopping as it would be the desired behaviour for most people and the best weights are already tracked so it's just a matter of returning them instead of having 2 callback functions tracking the same variables.
