### ISSUE TITLE
ValueError: Please initialize `Prune` with a supported layer. Layers should either be supported by the PruneRegistry (built-in keras layers) or should be a `PrunableLayer` instance, or should has a customer defined `get_prunable_weights` method. You passed: <class 'keras.layers.core.TFOpLambda'>

### ISSUE THREAD

**Issue by zhenhao-huang** [keras-team/keras#16889]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras):y
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu18
- TensorFlow installed from (source or binary):source 
- TensorFlow version (use command below):2.6.0
- Python version:3.6
- Bazel version (if compiling from source):
- GPU model and memory:
- Exact command to reproduce:

**Describe the problem**.

The whole model cannot be pruned directly

**Describe the expected behavior**.

Fine-tune pre-trained model with pruning

**Standalone code to reproduce the issue**.

    import tensorflow as tf
    from tensorflow.keras.models import Model
    
    
    class Mobilenet_v2():
        def __init__(self):
            self._base_model = tf.keras.applications.MobileNetV2(input_shape=(224, 224, 3), include_top=False, weights=None)
    
            _MOBILENET_V2_FPN_SKIP_LAYERS = ['block_2_add', 'block_5_add']
            self.skip_outputs = [
                self._base_model.get_layer(skip_layer_name).output
                for skip_layer_name in _MOBILENET_V2_FPN_SKIP_LAYERS
            ]
    
            self.conv_fpn_d = tf.keras.models.Sequential([
                tf.keras.layers.DepthwiseConv2D(
                    kernel_size=3, padding="same", activation=None),
                tf.keras.layers.Conv2D(
                    filters=24, kernel_size=1, activation=None),
                tf.keras.layers.BatchNormalization(),
                tf.keras.layers.ReLU(),
                tf.keras.layers.Conv2DTranspose(filters=24,
                                                kernel_size=3, padding="same", strides=(2, 2))
            ])
            self.conv_fpn_e = tf.keras.models.Sequential([
                tf.keras.layers.Conv2D(
                    filters=24, kernel_size=1, activation=None),
                tf.keras.layers.BatchNormalization(),
                tf.keras.layers.ReLU()
            ])
    
            self.conv_final = tf.keras.models.Sequential([
                tf.keras.layers.DepthwiseConv2D(
                    kernel_size=3, padding="same", activation=None),
                tf.keras.layers.Conv2D(
                    filters=24, kernel_size=1, activation=None),
                tf.keras.layers.BatchNormalization(),
                tf.keras.layers.ReLU(),
                tf.keras.layers.DepthwiseConv2D(
                    kernel_size=3, padding="same", activation=None)
            ])
    
        def build_model(self):
            fm64 = self.skip_outputs[0]
            fm32 = self.skip_outputs[1]
    
            decode_up = self.conv_fpn_d(fm32)
            encode = self.conv_fpn_e(fm64)
            fuse = encode + decode_up
    
            y = self.conv_final(fuse)
            sigmoid = tf.keras.layers.Activation("sigmoid")(y)
    
            return Model(inputs=self._base_model.input, outputs=sigmoid)
    
    
    if __name__ == '__main__':
        import tensorflow_model_optimization as tfmot
        model = Mobilenet_v2().build_model()
        print(model.summary())
        model = tfmot.sparsity.keras.prune_low_magnitude(model)
        print(model.summary())

**Source code / logs**.

    Traceback (most recent call last):
      File "C:/Users/laozhenyao/Desktop/code/src/models/test.py", line 61, in <module>
        model = tfmot.sparsity.keras.prune_low_magnitude(model)
      File "C:\Users\laozhenyao\anaconda3\envs\tf2x\lib\site-packages\tensorflow_model_optimization\python\core\keras\metrics.py", line 74, in inner
        raise error
      File "C:\Users\laozhenyao\anaconda3\envs\tf2x\lib\site-packages\tensorflow_model_optimization\python\core\keras\metrics.py", line 69, in inner
        results = func(*args, **kwargs)
      File "C:\Users\laozhenyao\anaconda3\envs\tf2x\lib\site-packages\tensorflow_model_optimization\python\core\sparsity\keras\prune.py", line 210, in prune_low_magnitude
        return _add_pruning_wrapper(to_prune)
      File "C:\Users\laozhenyao\anaconda3\envs\tf2x\lib\site-packages\tensorflow_model_optimization\python\core\sparsity\keras\prune.py", line 181, in _add_pruning_wrapper
        return keras.models.clone_model(
      File "C:\Users\laozhenyao\anaconda3\envs\tf2x\lib\site-packages\keras\models.py", line 451, in clone_model
        return _clone_functional_model(
      File "C:\Users\laozhenyao\anaconda3\envs\tf2x\lib\site-packages\keras\models.py", line 191, in _clone_functional_model
        model_configs, created_layers = _clone_layers_and_model_config(
      File "C:\Users\laozhenyao\anaconda3\envs\tf2x\lib\site-packages\keras\models.py", line 244, in _clone_layers_and_model_config
        config = functional.get_network_config(
      File "C:\Users\laozhenyao\anaconda3\envs\tf2x\lib\site-packages\keras\engine\functional.py", line 1349, in get_network_config
        layer_config = serialize_layer_fn(layer)
      File "C:\Users\laozhenyao\anaconda3\envs\tf2x\lib\site-packages\keras\models.py", line 241, in _copy_layer
        created_layers[layer.name] = layer_fn(layer)
      File "C:\Users\laozhenyao\anaconda3\envs\tf2x\lib\site-packages\tensorflow_model_optimization\python\core\sparsity\keras\prune.py", line 188, in _add_pruning_wrapper
        return pruning_wrapper.PruneLowMagnitude(layer, **params)
      File "C:\Users\laozhenyao\anaconda3\envs\tf2x\lib\site-packages\tensorflow_model_optimization\python\core\sparsity\keras\pruning_wrapper.py", line 167, in __init__
        raise ValueError(
    ValueError: Please initialize `Prune` with a supported layer. Layers should either be supported by the PruneRegistry (built-in keras layers) or should be a `PrunableLayer` instance, or should has a customer defined `get_prunable_weights` method. You passed: <class 'keras.layers.core.TFOpLambda'>

**Comment by sushreebarsa** [comment]
@zhenhao-huang I tried to replicate the issue on colab, could you please find the [gist](https://colab.research.google.com/gist/sushreebarsa/3a2d3a1969776fa796d3fa6d8a2d9afb/16889.ipynb#scrollTo=kVn5voBqLZs2) here and confirm the same?
Thank you!

**Comment by zhenhao-huang** [comment]
Yes, that's right.And I also want to ask other questions:`tfmot.sparsity.keras.strip_pruning()` should be better used before or after `model.fit`?

    model = tfmot.sparsity.keras.prune_low_magnitude(model)
    model.fit()
    prune_model = tfmot.sparsity.keras.strip_pruning(model)
    prune_model.save_model()

or

    model = tfmot.sparsity.keras.prune_low_magnitude(model)
    prune_model = tfmot.sparsity.keras.strip_pruning(model)
    prune_model.fit()
    prune_model.save_model()

**Comment by gowthamkpr** [comment]
@zhenhao-huang This is very similar to this issue [here](https://github.com/tensorflow/model-optimization/issues/374). Also this issue is a tensorflow model optimization issue and not a keras issue. Can you please post your issue [here](https://github.com/tensorflow/model-optimization/issues) and close it here. Thanks!!
