### ISSUE TITLE
ConvNeXt not compatible with mixed precision

### ISSUE THREAD

**Issue by andreped** [keras-team/keras#16907]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow installed from (source or binary): nightly
- TensorFlow version (use command below): 2.11.0a20220816
- Python version: 3.8.10
- GPU model and memory: NVIDIA Quadro RTX 6000 (24 GB VRAM)
- Do you want to contribute a PR? (yes/no): No

**Describe the problem**.
Starting from [this issue](https://github.com/keras-team/keras/issues/16656), I observed that ConvNeXt was not compatible with TimeDistributed, this was then fixed in the nightly release (see [here](https://github.com/keras-team/keras/issues/16656#issuecomment-1216889267)). As it was working I then tried to use mixed precision, where I got a new error. Note that MobileNetV3 works seemlessly with mixed precision. Hence, I think only ConvNeXt might be affected, but not sure.

I believe the model itself is working fine with mixed precision, but it contains the layer `LayerScale`, which may not be (see logs below for more details).

**Describe the expected behavior**.
Mixed precision should work seemlessly with ConvNeXt.

**Standalone code to reproduce the issue**.
It failed when initializing the ConvNeXt model, after mixed precision was enabled. Hence, I believe running this might reproduce the issue (note that source logs are not directly from this script, but I believe you will get the same error):
```
import tensorflow as tf
from tensorflow.keras.applications import ConvNeXtSmall

tf.keras.mixed_precision.set_global_policy('mixed_float16')
model = ConvNeXtSmall(include_top=False, weights="imagenet", pooling="none")
```

**Source code / logs**.
```
Traceback (most recent call last):
  File "source/main.py", line 454, in <module>
    main()
  File "source/main.py", line 216, in main
    model = get_classifier_architecture(MODEL_ARCH=ret.arch, ret=ret, instance_size=instance_size,
  File "/home/andrep/workspace/bcgrade/source/models/classifiers.py", line 371, in get_classifier_architecture
    shared_base_model = ConvNeXtSmall(include_top=False, weights="imagenet", pooling="none", input_shape=instance_size[1:])
  File "/home/andrep/workspace/bcgrade/venv/lib/python3.8/site-packages/keras/applications/convnext.py", line 610, in ConvNeXtSmall
    return ConvNeXt(
  File "/home/andrep/workspace/bcgrade/venv/lib/python3.8/site-packages/keras/applications/convnext.py", line 516, in ConvNeXt
    x = ConvNeXtBlock(
  File "/home/andrep/workspace/bcgrade/venv/lib/python3.8/site-packages/keras/applications/convnext.py", line 283, in apply
    x = LayerScale(
  File "/home/andrep/workspace/bcgrade/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/andrep/workspace/bcgrade/venv/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py", line 588, in _ExtractInputsAndAttrs
    raise TypeError(
TypeError: Exception encountered when calling layer "convnext_small_stage_0_block_0_layer_scale" (type LayerScale).

Input 'y' of 'Mul' Op has type float32 that does not match type float16 of argument 'x'.

Call arguments received by layer "convnext_small_stage_0_block_0_layer_scale" (type LayerScale):
  • x=tf.Tensor(shape=(None, None, None, 96), dtype=float16)
```

**Comment by tilakrayal** [comment]
@gowthamkpr,
I was able to reproduce the issue on tensorflow v2.8, [v2.9](https://colab.research.google.com/gist/tilakrayal/a5520f1ef47e04c7d052b1ff75cf7ad2/untitled504.ipynb) and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/30257452eebf9cc45e590f84ed8da4bd/untitled503.ipynb).

**Comment by zibbini** [comment]
I was able to fix this by adding in casts to the appropriate dtype for the the `build` and `__call__` functions (lines [219](https://github.com/keras-team/keras/blob/b80dd12da9c0bc3f569eca3455e77762cf2ee8ef/keras/applications/convnext.py#L219)-[225](https://github.com/keras-team/keras/blob/b80dd12da9c0bc3f569eca3455e77762cf2ee8ef/keras/applications/convnext.py#L225)) in the custom layer [LayerScale](https://github.com/keras-team/keras/blob/v2.10.0/keras/applications/convnext.py#L199) as follows:

``` python
class LayerScale(layers.Layer):
    """Layer scale module.

    References:
      - https://arxiv.org/abs/2103.17239

    Args:
      init_values (float): Initial value for layer scale. Should be within
        [0, 1].
      projection_dim (int): Projection dimensionality.

    Returns:
      Tensor multiplied to the scale.
    """

    def __init__(self, init_values, projection_dim, **kwargs):
        super().__init__(**kwargs)
        self.init_values = init_values
        self.projection_dim = projection_dim

    def build(self, input_shape):
        self.gamma = tf.Variable(
            self.init_values * tf.ones((self.projection_dim,))
        )
        if self.gamma.dtype.base_dtype != self._compute_dtype_object.base_dtype:
            self.gamma = tf.cast(self.gamma, dtype=self._compute_dtype_object)        

    def call(self, x):
        if x.dtype.base_dtype != self._compute_dtype_object.base_dtype:
            x = tf.cast(x, dtype=self._compute_dtype_object)
        return x * self.gamma

    def get_config(self):
        config = super().get_config()
        config.update(
            {
                "init_values": self.init_values,
                "projection_dim": self.projection_dim,
            }
        )
        return config
```

**Comment by andreped** [comment]
> I was able to fix this by adding in casts to the appropriate dtype for the the `build` and `__call__` functions

Interesting, @zibbini. LGTM. Can run some checks tomorrow.

**Comment by andreped** [comment]
@zibbini Just ran some experiments, but ran into more issues. See [gist](https://colab.research.google.com/gist/andreped/7e8bf14d7db851bdf4f43d35f6c9c787/untitled503.ipynb#scrollTo=izDg48QF1YDI).

After adding your modifications, it seems to work, but it fails to load the pretrained weights.

**Comment by zibbini** [comment]
@andreped I managed to fix those issues with pre-trained weights by initialising the gamma variable in `LayerScale` with the correct dtype rather than adding in the casts (see [gist](https://colab.research.google.com/gist/zibbini/4ae1396c10e48b0e69bb6394e259f08e/untitled1.ipynb)):

``` python 
class LayerScale(layers.Layer):
    """Layer scale module.

    References:
      - https://arxiv.org/abs/2103.17239

    Args:
      init_values (float): Initial value for layer scale. Should be within
        [0, 1].
      projection_dim (int): Projection dimensionality.

    Returns:
      Tensor multiplied to the scale.
    """

    def __init__(self, init_values, projection_dim, **kwargs):
        super().__init__(**kwargs)
        self.init_values = init_values
        self.projection_dim = projection_dim

    def build(self, input_shape):
        self.gamma = tf.Variable(
            self.init_values * tf.ones((self.projection_dim,)), dtype=self._compute_dtype_object
        )

    def call(self, x):
        return x * self.gamma

    def get_config(self):
        config = super().get_config()
        config.update(
            {
                "init_values": self.init_values,
                "projection_dim": self.projection_dim,
            }
        )
        return config
```

**Comment by andreped** [comment]
> I managed to fix those issues with pre-trained weights by initialising the gamma variable in `LayerScale` with the correct dtype rather than adding in the casts (see [gist](https://colab.research.google.com/gist/zibbini/4ae1396c10e48b0e69bb6394e259f08e/untitled1.ipynb)):

Sorry, I've been away and doing other stuff for a while. Just returned back to this issue.

Just tried the gist. Works well, at least it seems so. Shall we make a PR to see if gets added in the next release. @zibbini?

**Comment by andreped** [comment]
I made a PR: https://github.com/keras-team/keras/pull/17547

Hopefully this will be accepted and merged soon, such that we can use pretrained ConvNeXt models with mixed precision in the upcoming release :]

**Comment by andreped** [comment]
Fixed in 2b3344ac4e0ee141904e5e00b36c329dc7c2b0c0

**Comment by eduardinjo** [comment]
The PR: #17547   fixes gives problem but creates another error during save of custom model. With original definition there was no such problem in fp32.

```
child_proto.local_name = child.name 
TypeError: None has type NoneType, but expected one of: bytes, unicode
```

If I pass name to `add_weight` then it saves without error:

```python   
def build(self, input_shape):
    self.gamma = self.add_weight(
        name=self.name,
        shape=(self.projection_dim,),
        initializer=initializers.Constant(self.init_values),
        trainable=True,
    )
```

**Comment by andreped** [comment]
> The PR: #17547 fixes given problemm but creates another error during saving. With original definition there was no such problem in fp32.

@eduardinjo Could you make a separate issue, reference this PR, and make a minimalistic gist such that others can reproduce this issue? Should be made one or multiple unit tests to avoid this from happening in the future.
