### ISSUE TITLE
filters can be set to float value in tf.keras.layers.Conv1D

### ISSUE THREAD

**Issue by cheyennee** [keras-team/keras#16914]
Parameter 'filters' should be an integer, because it's relevant to the dimensionality of the output space. Also it must be an integer written on the document. However, I find that when the type of filters is float, code works.
Same problem is found in similar APIs:
_tf.keras.layers.Conv1DTranspose
tf.keras.layers.Conv2D
tf.keras.layers.Conv2DTranspose
tf.keras.layers.Conv3D
tf.keras.layers.Conv3DTranspose
tf.keras.layers.Convolution1D
tf.keras.layers.Convolution1DTranspose_
Similar problem is found in tf.keras.layers.UpSampling1D. Parameter 'size' can be set to float in tf.keras.layers.UpSampling1D. But size should be an integer written in documentation.

```
import tensorflow as tf
results={}
try:
  padding = "same"
  filters = 2.5
  kernel_size = 3
  arg_class = tf.keras.layers.Conv1D(padding=padding,filters=filters,kernel_size=kernel_size,)
  arg_input = tf.random.uniform([1, 2, 2], dtype=tf.float32)
  results["res"] = arg_class(arg_input)
except Exception as e:
  results["err"] = "Error:"+str(e)
print(results)
```
'''
results = {'res': <tf.Tensor: shape=(1, 2, 2), dtype=float32, numpy=
array([[[-0.49259394,  0.5246876 ],
        [-0.00979106,  0.42434496]]], dtype=float32)>}
'''

```
import tensorflow as tf
results={}
try:
  size = 2.5
  arg_class = tf.keras.layers.UpSampling1D(size=size,)
  arg_input = tf.saturate_cast(tf.random.uniform([2, 2, 3], minval=-256, maxval=257, dtype=tf.int64), dtype=tf.int64)
  results["res"] = arg_class(arg_input)
except Exception as e:
  results["err"] = "Error:"+str(e)
print(results)
```
Above code also works

tf version: 2.11
os: win11

**Comment by sushreebarsa** [comment]
@cheyennee I was able to replicate the issue on colab, please find the [gist](https://colab.research.google.com/gist/sushreebarsa/ea0d92d441898baa946b45aff508506f/57164.ipynb) here. 
Thank you!

**Comment by LukeWood** [comment]
We are casting the input to an integer.  The difficulty with validating this is that if the user passes `2.0` as `filters` that is a valid input.  We can't fix this without breaking backwards compatibility - so this is not a true "bug" in that sense.
