### ISSUE TITLE
Hyperlink for ResNetv2 not working due to line breaks

### ISSUE THREAD

**Issue by Anselmoo** [keras-team/keras#16936]
### Problem:

Due to linebreaks in the source code, the hyperlink for `ResNetv2` is not working

<img width="746" alt="image" src="https://user-images.githubusercontent.com/13209783/186423407-3e97a811-e98b-4a68-8c29-cbfff5aab28c.png">

https://github.com/keras-team/keras/blob/07e13740fd181fc3ddec7d9a594d8a08666645f6/keras/applications/resnet_v2.py#L18-L21

### Solution:

```python
- [Identity Mappings in Deep Residual Networks](
      https://arxiv.org/abs/1603.05027) (CVPR 2016)

```

**Comment by sushreebarsa** [comment]
@Anselmoo Thank you for raising the issue.
It will be closed once the PR is merged. Thank you!
