### ISSUE TITLE
tf.keras.utils.pack_x_y_sample_weight cannot compute gradient

### ISSUE THREAD

**Issue by VictoriaGriffith** [keras-team/keras#16944]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): TF2.9.1
- Python version: 3.9
- Bazel version (if compiling from source):
- GPU model and memory:

**Describe the problem**.
`tf.keras.utils.pack_x_y_sample_weight` cannot compute gradient

**Describe the current behavior**.
Raises error.

**Describe the expected behavior**.
The backward computation should succeed.

**Standalone code to reproduce the issue**.
```
import tensorflow as tf

x = tf.random.uniform([2, 2], dtype=tf.float32)
y = (1, 2,)
sample_weight = None
print(x)
result = tf.keras.utils.pack_x_y_sample_weight(x, y=y, sample_weight=sample_weight, )
print(result)

with tf.GradientTape(persistent=True,) as g:
  g.watch(x)
  res = tf.keras.utils.pack_x_y_sample_weight(x, y=y, sample_weight=sample_weight, ) 
grad = g.gradient(res, x) # AttributeError

```

**Output**.
```
tf.Tensor(
[[0.68789124 0.48447883]
 [0.9309944  0.252187  ]], shape=(2, 2), dtype=float32)
(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.68789124, 0.48447883],
       [0.9309944 , 0.252187  ]], dtype=float32)>, (1, 2))
AttributeError: 'int' object has no attribute '_id'
```

**Comment by sushreebarsa** [comment]
@gadagashwini I was able to replicate the issue on colab, please find the [gist](https://colab.research.google.com/gist/tiruk007/aae0db8491dee09a77ec12c056a428e9/untitled106.ipynb) here. Thank you!

**Comment by mattdangerw** [comment]
The pack/unpack utilities are very simple. They just move things in and out of tuples. It looks like the error you are hitting is just from trying to attach a gradient to a python integer (`y`) in your code example, which is not supported for gradient_tape.

The following works.

```
import tensorflow as tf

x = tf.random.uniform([2, 2], dtype=tf.float32)
y = tf.constant((1, 2,), dtype=tf.float32)

with tf.GradientTape(persistent=True,) as g:
  g.watch(x)
  res = tf.keras.utils.pack_x_y_sample_weight(x, y=y, sample_weight=sample_weight, ) 
grad = g.gradient(res, x)
```

**Comment by mattdangerw** [comment]
I don't believe that is the behavior of gradient tap. The `target` (first argument of `gradient()`), should be passed only tensor types, so it matters that `res` has non tensor types in it.

Here's the same code but without any `pack_x_y_sample_weight`...

```python
x = tf.random.uniform([2, 2], dtype=tf.float32)
y = (1, 2,)

with tf.GradientTape(persistent=True,) as g:
  g.watch(x)
  res = (x, y)

# Fails, y is not a tensor.
grad = g.gradient(res, x)
```

Here are two options...
```python
x = tf.random.uniform([2, 2], dtype=tf.float32)
y = (1, 2,)

with tf.GradientTape(persistent=True,) as g:
  g.watch(x)
  res = (x, y)

# OK, y is ignored.
grad = g.gradient(res[0], x)
```

```python
x = tf.random.uniform([2, 2], dtype=tf.float32)
y = tf.constant((1, 2,))

with tf.GradientTape(persistent=True,) as g:
  g.watch(x)
  res = (x, y)

# OK, y is a tensor.
grad = g.gradient(res[0], x)
```
