### ISSUE TITLE
[Contributors Wanted] Implement `compute_output_shape()` method for `MultiHeadAttention`

### ISSUE THREAD

**Issue by fchollet** [keras-team/keras#16951]
## Nature of the task

Implement the method `compute_output_shape()` on the layer [`MultiHeadAttention`](https://github.com/keras-team/keras/blob/master/keras/layers/attention/multi_head_attention.py#L131). It should have the following signature:

```python
def compute_output_shape(self, query_shape, value_shape, key_shape=None):
```

It should accept either `TensorShape` instances or tuples as shapes, and it should return a `TensorShape` instance.

## Why?

The method is not required in order to use the layer, but it can be very useful to be able to compute the output shape of a layer without having to actually call it.

**Comment by Pouyanpi** [comment]
I would like to take it if it is still available.

**Comment by fchollet** [comment]
@Pouyanpi thanks! Feel free to open a PR.

**Comment by hnhparitosh** [comment]
Hello! Is this closed as per #16989?

**Comment by Pouyanpi** [comment]
Hello, 
Yes it is closed.

**Comment by tilakrayal** [comment]
@fchollet,
The related PR #https://github.com/keras-team/keras/pull/16989 which was raised and merged. The requested implement ation of `compute_output_shape()` method for **MultiHeadAttention** was also completed with the mentioned PR.

```
def compute_output_shape(self, query_shape, value_shape, key_shape=None):

        if key_shape is None:
            key_shape = value_shape

        query_shape = tf.TensorShape(query_shape)
        value_shape = tf.TensorShape(value_shape)
        key_shape = tf.TensorShape(key_shape)

        if query_shape[-1] != value_shape[-1]:
            raise ValueError(
                "The last dimension of `query_shape` and `value_shape` "
                f"must be equal, but are {query_shape[-1]}, {value_shape[-1]}. "
                "Received: query_shape={query_shape}, value_shape={value_shape}"
            )
```


Could you please confirm and feel free to close the issue, if the issue was resolved. 
https://github.com/keras-team/keras/pull/16989/files
Thank you!
