### ISSUE TITLE
tf.keras.layers.Layer.weights has inconsistent order in 'saved_model' format

### ISSUE THREAD

**Issue by MathiasToftas** [keras-team/keras#16966]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): yes
- OS Platform and Distribution: Linux Ubuntu 20.04
- TensorFlow installed from: binary
- TensorFlow version: v2.9.0-18-gd8ce9f9c301 2.9.1
- Python version: 3.8
- Exact command to reproduce: see google colab page

**Describe the problem**.

I originaly posted this issue in the tensorflow github, but was asked to move it here (original issue: https://github.com/tensorflow/tensorflow/issues/57438)

I'm building tensorflow lite and tensorflow  'saved_model's with the purpose of training them on edge devices in a federated learning setting. To start off I've been following this guide [(On-Device Training with TensorFlow Lite)](https://www.tensorflow.org/lite/examples/on_device_training/overview). 

To perform the FL, the weights of each edge model must be transferred to the server. The way I've done this is by accessing the weights using the tf.keras.layers.Layer.weights member. The issue lies in how the weights of this list are not always ordered consistently. If these weights are not ordered, the server will need some kind of extra information to sort the weights, which needlessly complicates the weights transfer.

**Describe the current behavior**.

Currently, if you access tf.keras.layers.Layer.weights from a normal keras model or tf.Module that exists in memory (no saving, loading, compressing, etc) the weights are given as a list in an order that is consistent, i.e. we can reinitialize the model and still receive the weights in the same order. This is the expected behavior.

However, if you save the same model in a 'saved_model' format (which is the recommended way to construct a tensorflow lite model [Convert TensorFlow models](https://www.tensorflow.org/lite/models/convert/convert_models)), the order in which these weights are given is seemingly randomized each time the model is loaded.

Confusingly enough, if we convert the 'saved_model' into a tensorflow light model, the order is once again consistent as expected.

**Describe the expected behavior**.

The expected behavior is that accessing  tf.keras.layers.Layer.weights should always produce the exact same result, no matter how the model has been packaged. Especially given that for the above 3 cases, a single model source file is used.

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no): no
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**.

[colab](https://colab.research.google.com/drive/1AE0dS1vJXV3D_NL29NjkVwavcszximFY?usp=sharing#scrollTo=Jqv5f4kfu03a)

**Comment by sushreebarsa** [comment]
@gadagashwini I was able to replicate the issue on colab, please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/0e2c1a62e70c7f8dc721b3647230ca95/untitled112.ipynb). Thank you!

**Comment by gadagashwini** [comment]
HI @MathiasToftas, You need to use signatures under tf.function ( for graph mode). Please take a look at this reference [link ](https://www.tensorflow.org/lite/guide/signatures#:~:text=%40tf.function%28input_signature%3D%5Btf.TensorSpec%28shape%3D%5BNone%5D%2C%20dtype%3Dtf.float32%29%5D%29)for more information. Thank you!

**Comment by MathiasToftas** [comment]
I'm not sure I follow, from the link you've shared, and from my own experience, you only need to add the 'input' signature under @tf.function. The function show in the colab doc does not have any inputs (other than self), so I'm not sure what can be added. 

From what the link you shared seems to say, the outputs signature is gathered from the structure of the dict you return, and looking at the returned dict in the colab doc, there is nothing there that would create a random order, except for the Layer.weights attribute.

Further, if this was the issue, why would the conversion to a tf lite model even succeed, and why would the signature_runner return anything at all if the graph conversion was unsuccessful?

**Comment by SuryanarayanaY** [comment]
Hello, Thank you for reporting an issue.

We're currently in the process of migrating the new Keras 3 code base from keras-team/keras-core to keras-team/keras.
Consequently, This issue may not be relevant to the Keras 3 code base . After the migration is successfully completed, feel free to reopen this Issue at keras-team/keras if you believe it remains relevant to the Keras 3 code base. If instead this Issue is a bug or security issue in legacy tf.keras, you can instead report a new issue at [keras-team/tf-keras](https://github.com/keras-team/tf-keras/issues), which hosts the TensorFlow-only, legacy version of Keras.

To know more about Keras 3, please read https://keras.io/keras_core/announcement/
