### ISSUE TITLE
Clarify override of non-trainability of layers when model is created. 

### ISSUE THREAD

**Issue by microprediction** [keras-team/keras#16965]
**URL(s) with the issue:**.

https://keras.io/guides/transfer_learning/

**Description of issue (what needs to be changed):**.

Unless I am mistaken (and I may well be) there is no point in setting a layer to be non-trainable prior to construction of the model. This property will be ignored, as this [gist](https://gist.github.com/microprediction/7aa395cec8a0ea2586936084a635cfba) demonstrates. Instead one must access the layer after the model is created.

**Comment by tilakrayal** [comment]
@microprediction,
Could you please feel free to submit a PR for the requested change to be made. Thank you!

**Comment by microprediction** [comment]
Sure thanks

**Comment by tilakrayal** [comment]
@microprediction,
Could you please feel free to submit a PR for the requested change to be made and provide the PR number for the tracking. Thank you!

**Comment by aliakdeniz38** [comment]
unsubscribe
