### ISSUE TITLE
Build Keras and TensorFlow in Bazel

### ISSUE THREAD

**Issue by ShuaiShao93** [keras-team/keras#16972]
**System information**.

TensorFlow version (you are using): 2.9.1

**Describe the feature and the current behavior/state**.
Right now the Keras assumes TensorFlow is installed by pip, and it has no Bazel dependencies on TensorFlow. However, I'm interested in building Tensorflow and Keras in two Bazel repositories. It doesn't work today because adding mutual dependency on each other causes cyclic dependency. It would be good if we can build them in Bazel instead of using pip.

**Will this change the current api? How?**
No

**Who will benefit from this feature?**
Everyone who intends to use Bazel to build TF and Keras.

**Comment by tilakrayal** [comment]
@ShuaiShao93,
Could you please take a look at this installation doc [link](https://www.tensorflow.org/install/source#install_bazel) where the Bazel installation is required while building the tensorflow. Thank you!
