### ISSUE TITLE
ValueError: Cowardly refusing to save variable .. unexpected suffix which won't be restored.

### ISSUE THREAD

**Issue by innat** [keras-team/keras#16984]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): 2.4.1, 2.6.4
- Python version:
- Bazel version (if compiling from source):
- GPU model and memory:
- Exact command to reproduce:

**Describe the problem**.

I want to build sinmple model which consist of different version of same model, here which is `efficient-net`. The model build successfully. The training also works fine. But until now, I would get the following error if I use `ModelCheckpoint` to save model in the runtime. 

```yaml
RuntimeError: Unable to create link (name already exists)
```

To solve this, one of (dirty) workaround (suggestion get from web) is to rename weight variable. But that raise another issue at the time of model saving due to unexpected suffix with variable name. 

> /opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py in write_object_proto_for_resource_variable(resource_variable, proto, options)
   2319     raise ValueError("Cowardly refusing to save variable {} because of"
   2320                      " unexpected suffix which won't be restored.".format(
-> 2321                          resource_variable.name))
   2322   proto.variable.name = meta_graph._op_name(resource_variable.name)  # pylint: disable=protected-access
   2323   proto.variable.trainable = resource_variable.trainable

```yaml
ValueError: Cowardly refusing to save 
variable normalization/mean:00 because of unexpected suffix which won't be restored.
```

**Standalone code to reproduce the issue**.

Here is the code to reproduce.

```python
from tensorflow.keras.applications import (
    EfficientNetB0, EfficientNetB1, EfficientNetB2
)
image_sizes_maps = {
    'B0': [EfficientNetB0, 224],
    'B1': [EfficientNetB1, 240],
    'B2': [EfficientNetB2, 260],
}
```
```python
def get_model():
    base_embeds = []    
    model_input = tf.keras.Input(shape=(None, None, 3),name='effnets')
    
    for key,value in image_sizes_maps.items():
        base_model, image_size = value
        x = tf.image.resize(model_input, [image_size, image_size], name=f'resize_{key}')
        z = base_model(
            include_top=False, 
        )(x)
        base_embeds.append(z)
   
    model = tf.keras.Model(model_input, base_embeds)
    return model
```
```python
MODEL = get_model()
```
```python
# DIRTY SOLUTION
# IF WE DON'T DO IT, THEN IT WILL CAUSE 
# Unable to create link (name already exists)
for i in range(len(MODEL.weights)):
    MODEL.weights[i]._handle_name = MODEL.weights[i].name + str(i)
```
```python
MODEL.save("model")
```
```
2022-09-04 21:11:19.660403: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_17/3402985690.py in <module>
----> 1 MODEL.save("E0_E6")

ValueError: Cowardly refusing to save 
variable normalization/mean:00 because of unexpected suffix which won't be restored.
```

**Additional Content**

With this, you can check if there is duplicate variable name. 

```python
from collections import Counter

def non_unique(l):
    def low(x):
        return x.lower() if isinstance(x, str) else x
    c = Counter(map(low, l))
    return [x for x in l if c[low(x)] > 1]

hold_w = []
for i, w in enumerate(MODEL.weights): 
    hold_w.append(w.name)

# It will return empty if all variable names are unique.
non_unique(hold_w)
```

**Comment by sushreebarsa** [comment]
@gowthamkpr I was able to replicate the issue on colab, please find the [gist](https://colab.research.google.com/gist/sushreebarsa/0bf91d3f60e52bc0e9aaeb54f41d73c0/16984.ipynb#scrollTo=u2kkrVjOKGfl) here.
Thank you!

**Comment by fchollet** [comment]
Can you try a simpler reproduction that only involves `tf.Variable` instead of an entire Keras model? Thank you.

**Comment by innat** [comment]
@fchollet 
I like to summarize the exact issue. 


**Background**

Like, here I was using some `EfficientNet` models (same model but difrerent variants) to **train combinedly**. So, it's natual that, there would be some naming overlaps to the final model or ensemble model (layer's name, weight's name across the internal models).

```python

MODEL = [EfficientNetB0, EfficientNetB1, EfficientNetB2]
```

Now due to have the same variable name of these models, I can't use `ModelCheckpoint` callbacks out of the box. It will cause [this known error](https://stackoverflow.com/questions/62169315/runtimeerror-unable-to-create-link-name-already-exists-keras). So, it's [suggested](https://github.com/tensorflow/tensorflow/issues/46871) that, a renaming would be a simple hack to resolve this. So, I used the following snippet to rename the weight variable, shown below (also mentioned above):

```python
for i in range(len(MODEL.weights)):
    MODEL.weights[i]._handle_name = MODEL.weights[i].name + str(i)
```

And it did rename. But the problem occurred at the time of saving, like when I did as follows:

```python
MODEL.save('saved_model')
```
It caused the reported error. 

**Motivation**

Ensembling training was a fun experiment that I wanted to conduct on TPU. No other reason. 

**Reproducing**

At this point, I think it may not needed to have reproducible code. It's hardly a bug. However, here is a shortcut to reproduce the error. We can reproduce it even with a single model if we try to rename the variable names.

```python
from tensorflow.keras.applications import (
    EfficientNetB3
)
base = EfficientNetB0()

MODEL = tf.keras.Model(
    base.get_layer('stem_conv_pad').input,
    base.get_layer('block1a_se_squeeze').output
)
```
```python
for i, w in enumerate(MODEL.weights): 
    print(w.name)

stem_conv/kernel:0
stem_bn/gamma:0
stem_bn/beta:0
stem_bn/moving_mean:0
stem_bn/moving_variance:0
block1a_dwconv/depthwise_kernel:0
block1a_bn/gamma:0
block1a_bn/beta:0
block1a_bn/moving_mean:0
block1a_bn/moving_variance:0
```
```python
for i in range(len(MODEL.weights)):
    MODEL.weights[i]._handle_name = MODEL.weights[i].name + str(i)

for i, w in enumerate(MODEL.weights): 
    print(w.name)

stem_conv/kernel:00
stem_bn/gamma:01
stem_bn/beta:02
stem_bn/moving_mean:03
stem_bn/moving_variance:04
block1a_dwconv/depthwise_kernel:05
block1a_bn/gamma:06
block1a_bn/beta:07
block1a_bn/moving_mean:08
block1a_bn/moving_variance:09
```

```python
MODEL.save("model")
ValueError:
..............
```

**Comment by innat** [comment]
Okay, it looks like if I rename the variablen ame as follows, it doesn't throw error. 

```python
for i in range(len(MODEL.weights)):
    MODEL.weights[i]._handle_name = str(i) + '/' + MODEL.weights[i].name

0/stem_conv/kernel:0
1/stem_bn/gamma:0
2/stem_bn/beta:0
```

**previous** (gives error)

```python
for i in range(len(MODEL.weights)):
    MODEL.weights[i]._handle_name = MODEL.weights[i].name + str(i)

stem_conv/kernel:00
stem_bn/gamma:01
stem_bn/beta:02
```

Is it expected? However, I think it solves the issue. Feel free to close the issue if you don't want to add anything.
