### ISSUE TITLE
ValueError: Input 0 of layer lstm_112 is incompatible with the layer: expected ndim=3, found ndim=4. Full shape received: (1, 72, 110907, 200)

### ISSUE THREAD

**Issue by Egrikkkk** [keras-team/keras#16985]
I have the following model:
`def define_model(vocab_size, max_length):

    input_texts = Input(shape=(max_length, vocab_size), batch_size=1)

    embed = Embedding(vocab_size, 200, mask_zero=True, input_length=max_length)(input_texts) #input_length=max_length

    print(embed.shape)

    drop1 = Dropout(0.5)(embed)

    lstm1 = LSTM(256, return_sequences=True, input_shape= (72, 200),)(drop1) 

    flatten = Flatten()(lstm1)

    dense1 = Dense(10, activation='relu',)(flatten)

    print(dense1)

    #parties

    input_parties = Input(shape=(1,))

    concat = Concatenate()([dense1, input_parties])

    outputs = Dense(vocab_size, activation='softmax')(concat)

    model = Model(inputs=[input_texts, input_parties], outputs=outputs)

    print(model.summary())

    return model`

And I get the next error:

`ValueError                                Traceback (most recent call last)
/tmp/ipykernel_17/3704233147.py in <module>
     16     return model
     17 
---> 18 model = define_model(vocab_size,max_len)
     19 model.compile(loss='categorical_crossentropy', optimizer='adam')

/tmp/ipykernel_17/3704233147.py in define_model(vocab_size, max_length)
      4     print(embed.shape)
      5     drop1 = Dropout(0.5)(embed)
----> 6     lstm1 = LSTM(256, return_sequences=True, input_shape= (72, 200),)(drop1)
      7     flatten = Flatten()(lstm1)
      8     dense1 = Dense(10, activation='relu',)(flatten)

/opt/conda/lib/python3.7/site-packages/keras/layers/recurrent.py in __call__(self, inputs, initial_state, constants, **kwargs)
    657 
    658     if initial_state is None and constants is None:
--> 659       return super(RNN, self).__call__(inputs, **kwargs)
    660 
    661     # If any of `initial_state` or `constants` are specified and are Keras

/opt/conda/lib/python3.7/site-packages/keras/engine/base_layer.py in __call__(self, *args, **kwargs)
    975     if _in_functional_construction_mode(self, inputs, args, kwargs, input_list):
    976       return self._functional_construction_call(inputs, args, kwargs,
--> 977                                                 input_list)
    978 
    979     # Maintains info about the `Layer.call` stack.

/opt/conda/lib/python3.7/site-packages/keras/engine/base_layer.py in _functional_construction_call(self, inputs, args, kwargs, input_list)
   1113       # Check input assumptions set after layer building, e.g. input shape.
   1114       outputs = self._keras_tensor_symbolic_call(
-> 1115           inputs, input_masks, args, kwargs)
   1116 
   1117       if outputs is None:

/opt/conda/lib/python3.7/site-packages/keras/engine/base_layer.py in _keras_tensor_symbolic_call(self, inputs, input_masks, args, kwargs)
    846       return tf.nest.map_structure(keras_tensor.KerasTensor, output_signature)
    847     else:
--> 848       return self._infer_output_signature(inputs, args, kwargs, input_masks)
    849 
    850   def _infer_output_signature(self, inputs, args, kwargs, input_masks):

/opt/conda/lib/python3.7/site-packages/keras/engine/base_layer.py in _infer_output_signature(self, inputs, args, kwargs, input_masks)
    884           # overridden).
    885           # TODO(kaftan): do we maybe_build here, or have we already done it?
--> 886           self._maybe_build(inputs)
    887           inputs = self._maybe_cast_inputs(inputs)
    888           outputs = call_fn(inputs, *args, **kwargs)

/opt/conda/lib/python3.7/site-packages/keras/engine/base_layer.py in _maybe_build(self, inputs)
   2632     if not self.built:
   2633       input_spec.assert_input_compatibility(
-> 2634           self.input_spec, inputs, self.name)
   2635       input_list = tf.nest.flatten(inputs)
   2636       if input_list and self._dtype_policy.compute_dtype is None:

/opt/conda/lib/python3.7/site-packages/keras/engine/input_spec.py in assert_input_compatibility(input_spec, inputs, layer_name)
    216                          'expected ndim=' + str(spec.ndim) + ', found ndim=' +
    217                          str(ndim) + '. Full shape received: ' +
--> 218                          str(tuple(shape)))
    219     if spec.max_ndim is not None:
    220       ndim = x.shape.rank

ValueError: Input 0 of layer lstm_112 is incompatible with the layer: expected ndim=3, found ndim=4. Full shape received: (1, 72, 110907, 200)`

I get this error regardless of what I do.  It still occurs if I remove the batch size, change input shapes, etc. What can be done to fix it?

**Comment by tilakrayal** [comment]
@Egrikkkk,
To expedite the trouble-shooting process, could you please provide a complete code and the TensorFlow version you are using.

Keras' convention is that the batch dimension (number of examples (not the same as timesteps)) is typically omitted in the input_shape arguments. The batching (number of examples per batch) is handled in the fit call.

Also please take a look at this SO [link](https://stackoverflow.com/questions/44583254/valueerror-input-0-is-incompatible-with-layer-lstm-13-expected-ndim-3-found-n) and the [issue](https://github.com/keras-team/keras/issues/7403) with the similar error. Thank you!
