### ISSUE TITLE
Can't deserialize model using __add__ or Add()

### ISSUE THREAD

**Issue by froody** [keras-team/keras#16987]
Clone of https://github.com/tensorflow/tensorflow/issues/57574

**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): v2.9.1-0-gd8ce9f9c301 2.9.1
- Python version: 3.9.13
- Bazel version (if compiling from source): 5.0.0
- GPU model and memory: nvidia A100-SXM4-40GB
- Exact command to reproduce: `python repro.py`

**Describe the problem**.

When I declare a model as such:
```
import tensorflow as tf
from tensorflow.keras.layers import Dense, Layer

class MyLayer(Layer):
    def __init__(self):
        super().__init__()
        self.dense = Dense(512)
    def __call__(self, X):
        short = X
        X = self.dense(X)
        X = short + X
        return X


def main():
    model = tf.keras.Sequential([MyLayer()])
    model.build([None, 512])
    model.save("/tmp/my_model")

    tf.keras.models.load_model("/tmp/my_model")

if __name__ == "__main__":
    main()
```

**Describe the current behavior**.

I get an exception trying to load the model:
```
api_dispatcher.Dispatch=<bound method PyCapsule.Dispatch of <Dispatch(_add_dispatch): >, args=(<tf.Tensor 'Placeholder:0' shape=(None, 512) dtype=float32>,), kwargs={}
Traceback (most recent call last):
  File "/mnt/disks/data/src/repro.py", line 24, in <module>
    main()
  File "/mnt/disks/data/src/repro.py", line 21, in main
    tf.keras.models.load_model("/tmp/my_model")
  File "/mnt/disks/data/src/conda/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/mnt/disks/data/src/conda/lib/python3.9/site-packages/tensorflow/python/util/dispatch.py", line 1078, in op_dispatch_handler
    result = api_dispatcher.Dispatch(args, kwargs)
TypeError: Missing required positional argument
```

**Describe the expected behavior**.

The model loads fine.

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no): no
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**.

[notebook](https://colab.research.google.com/gist/sushreebarsa/8dc86c2d722124d3fc70fd9e439ddff6/untitled122.ipynb)

**Comment by tilakrayal** [comment]
@froody,
A functional model and subclassed model cannot be mixed. If you would like a subclassed model, you can follow the form in the guide below, and will not need the keras.Input functional style. You would chain to the parent class constructor at the start of init, without supplying inputs and outputs.
https://www.tensorflow.org/guide/keras/custom_layers_and_models

If you would like a functional model, you define keras.Input and eventual outputs before creating the model. Thank you!

**Comment by froody** [comment]
@tilakrayal looking at that doc it says

"Layers are recursively composable

If you assign a Layer instance as an attribute of another Layer, the outer layer will start tracking the weights created by the inner layer."

That's exactly what I'm doing. If I use the `Add` layer instead of the `+` operator I still get an exception when I load a saved model:

```class MyLayer(Layer):
    def __init__(self):
        super().__init__()
        self.dense = Dense(512)
        self.add = Add()
    def __call__(self, X):
        short = X
        X = self.dense(X)
        X = self.add([short , X])
        return X```

If it cannot be mixed, how does it train? IMHO an invalid layer configuration should fail at first instantiation, in my case I trained a model for a day and only discovered the problem when I tried to load it.

**Comment by tilakrayal** [comment]
@gadagashwini,
I was able to reproduce the issue on tensorflow v2.8, v2.9 and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/03efb82205db91ef37b428d8b8cff9f4/untitled583.ipynb).

**Comment by ianstenbit** [comment]
Hi Froody!

It looks like you are overriding `__call__` directly instead of the `call` method, which is what subclasses of `Layer` should override (see [Layer docs](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Layer))

I modified the gist from tlakrayal@ to rename your override from `__call__` to `call` and it now appears to be working as intended.

I hope this unblocks you for now, and I am going to look into options for how to better prevent this for future users.

Thanks!

**Comment by ianstenbit** [comment]
I don't think there is a clean way of preventing accidental override of `__call__` because there are valid use cases for overriding it.

I've looked through the [Layer docs](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Layer#call) again and between the docstrings about `call` and `__call__` and the examples, I think there is currently sufficient guidance toward overriding `call` for use cases like this one.
