### ISSUE TITLE
MeanIoU Metric not supporting sparse_y_true: bool or sparse_y_pred: bool in Tensorflow

### ISSUE THREAD

**Issue by Znerual** [keras-team/keras#16996]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.9.1
- Python version: 3.10.6
- Bazel version (if compiling from source): -
- GPU model and memory: Quadro M3000M, 4096MiB
- Exact command to reproduce: keras.metrics.MeanIoU(num_classes=3, sparse_y_pred=False)

**Describe the problem**.

The keras [documentation](https://keras.io/api/metrics/segmentation_metrics/#meaniou-class) states that options sparse_y_pred and sparse_y_true can be set to toggle between sparse and one-hot encoding for the MeanIoU metric, and also the [code](https://github.com/keras-team/keras/blob/v2.10.0/keras/metrics/metrics.py#L3018):
```
@dtensor_utils.inject_mesh
    def __init__(
        self,
        num_classes: int,
        name: Optional[str] = None,
        dtype: Optional[Union[str, tf.dtypes.DType]] = None,
        ignore_class: Optional[int] = None,
        sparse_y_true: bool = True,
        sparse_y_pred: bool = True,
        axis: int = -1,
    ):
```
seems to support it. But when wanting to initialize the metric (inside my model fit function), it states:
```
File ~/Code/Environments/Py310TF/lib/python3.10/site-packages/keras/dtensor/utils.py:141, in inject_mesh.<locals>._wrap_function(instance, *args, **kwargs)
    139 if mesh is not None:
    140   instance._mesh = mesh  # pylint: disable=protected-access
--> 141 init_method(instance, *args, **kwargs)

TypeError: MeanIoU.__init__() got an unexpected keyword argument 'sparse_y_pred'
```
which seems as if the argument is not supported. Also in the tf [documentation](https://www.tensorflow.org/api_docs/python/tf/keras/metrics/IoU), `sparse_y_pred` is not mentioned.  

**Describe the current behavior**.
Currently, I get the error written above.

**Describe the expected behavior**.
Support for `sparse_y_pred` and `sparse_y_true`, as stated in the documentation.

**Standalone code to reproduce the issue**.

```
import tensorflow as tf

tf.keras.metrics.MeanIoU(num_classes=3, sparse_y_pred=False)
```

**Source code / logs**.

```
File ~/Code/Environments/Py310TF/lib/python3.10/site-packages/keras/dtensor/utils.py:141, in inject_mesh.<locals>._wrap_function(instance, *args, **kwargs)
    139 if mesh is not None:
    140   instance._mesh = mesh  # pylint: disable=protected-access
--> 141 init_method(instance, *args, **kwargs)

TypeError: MeanIoU.__init__() got an unexpected keyword argument 'sparse_y_pred'
```

**Comment by tilakrayal** [comment]
@Znerual,
I was able to execute the code without any issue/error on tf-nightly.  Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/8388c5bb5cb34395f9c382c176a7fafd/untitled578.ipynb).

**Comment by Znerual** [comment]
Thank you for your answer @tilakrayal !
