### ISSUE TITLE
Automatic Speech Recognition with Transformer

### ISSUE THREAD

**Issue by EZMarouane** [keras-team/keras#17070]
hello keras Community i want no if some one can help me ith the keras implementation of Automatic Speech Recognition with Transformer i train the model but it doesn't give me a good transcription.
if some one can help me or advice me

**Comment by innat** [comment]
https://keras.io/examples/audio/transformer_asr/

**Comment by sushreebarsa** [comment]
@EZMarouane Could you please refer to this [link](https://keras.io/examples/audio/transformer_asr/) and let us know if it helps?
Thank you!
