### ISSUE TITLE
Multi-Kernel ELM 

### ISSUE THREAD

**Issue by sudheerpunuri** [keras-team/keras#17092]
Hiii All:
Can anyone suggest or give an idea on the implementation of Multi Kernel Extreme Learning Machine (MKELM) for Deep Neural Networks? Later I need to apply particle swarm optimization (PSO) for the optimization of the classifier.

**Comment by gadagashwini** [comment]
Hi @sudheerpunuri, Could you explain the feature in more detail with example or use cases. Thank you!
