### ISSUE TITLE
ValueError: Graph disconnected: cannot obtain value for tensor KerasTensor(type_spec=TensorSpec(shape=(None, 10), dtype=tf.float32, 

### ISSUE THREAD

**Issue by timothyslau** [keras-team/keras#17105]
**Problem Description:**
I am getting a graph disconnection error when I try to combine different input types.  I expect to get a functioning model fit. Keras is having an issue concatenating the different inputs.

**Error Output**
`ValueError: Graph disconnected: cannot obtain value for tensor KerasTensor(type_spec=TensorSpec(shape=(None, 10), dtype=tf.int64, name='numeric_input'), name='numeric_input', description="created by layer 'numeric_input'") at layer "numeric_dense_layer". The following previous layers were accessed without issue: ['embedding_stringlookup2', 'embedding_stringlookup1', 'embedding_layer2', 'embedding_layer1', 'embedding_lstm1', 'embedding_lstm2']`

**Reproducible Example Code:**
```
import pandas as pd
import keras

temp = pd.DataFrame(data={
    "x1":["a", "b", "c", "a", "b", "c", "a", "b", "c", "a"], 
    "x2":["d", "e", "f", "e", "f", "d", "e", "f", "d", "e"],
    "x3":[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "y":[0.2, 0.6, 0.9, 0.4, 1.0, 0.1, 0.3, 0.5, 0.8, 0.7]
    })

embedding_input1 = keras.Input(shape=(None,), dtype="string", name="embedding_input1")
embedding_stringlookup1 = layers.StringLookup(vocabulary=list(temp.x1.unique()), num_oov_indices=0, name="embedding_stringlookup1")(embedding_input1)
embedding_feat1 = layers.Embedding(input_dim=len(temp.x1.unique()), output_dim=2, name="embedding_layer1")(embedding_stringlookup1)
embedding_lstm1 = layers.LSTM(units=100, name="embedding_lstm1")(embedding_feat1)

embedding_input2 = keras.Input(shape=(None,), dtype="string", name="embedding_input2")
embedding_stringlookup2 = layers.StringLookup(vocabulary=list(temp.x2.unique()), num_oov_indices=0, name="embedding_stringlookup2")(embedding_input2)
embedding_feat2 = layers.Embedding(input_dim=len(temp.x2.unique()), output_dim=2, name="embedding_layer2")(embedding_stringlookup2)
embedding_lstm2 = layers.LSTM(units=100, name="embedding_lstm2")(embedding_feat2)

numeric_input = keras.Input(shape=(10), dtype="int64", name="numeric_input")
numeric_layer = layers.Dense(units=100, name="numeric_dense_layer")(numeric_input)

comb_inputs = layers.concatenate(inputs=[embedding_lstm1, embedding_lstm2, numeric_layer], axis=1)

output = layers.Dense(units=1, name="output")(comb_inputs)

model = keras.Model(inputs=[embedding_input1, embedding_input2], outputs=output, name="example_model")

model.compile(
    loss=keras.losses.mean_squared_error, 
    optimizer=keras.optimizers.RMSprop(),
    metrics=["mean_squared_error"]
)

keras.utils.plot_model(model, "embedding_from string_example.png", show_shapes=True)

history = model.fit(
    x={"embedding_input1":temp.x1, "embedding_input2":temp.x2, "numeric_input":temp.x3},
    y=temp.y, 
    batch_size=2, 
    epochs=5, 
    validation_split=0.2
    )
```

**Tensorflow version output:**
v2.9.0-18-gd8ce9f9c301 2.9.1

**Environment capture script output:**

== check python ===================================================
python version: 3.9.0
python branch: v3.9.0
python build version: ('v3.9.0:9cf6752276', 'Oct  5 2020 11:29:23')
python compiler version: Clang 6.0 (clang-600.0.57)
python implementation: CPython

== check os platform ===============================================

== are we in docker =============================================
No

== compiler =====================================================
Apple clang version 14.0.0 (clang-1400.0.29.102)
Target: x86_64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

== check pips ===================================================
numpy                        1.21.6
protobuf                     3.18.1
tensorflow                   2.9.1
tensorflow-datasets          4.6.0
tensorflow-estimator         2.9.0
tensorflow-io-gcs-filesystem 0.26.0
tensorflow-metadata          1.10.0

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.version.VERSION = 2.9.1
tf.version.GIT_VERSION = v2.9.0-18-gd8ce9f9c301
tf.version.COMPILER_VERSION = 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.16)

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
/Users/laut/Downloads/tf_env_collect.sh: line 147: nvidia-smi: command not found

== cuda libs  ===================================================

== tensorflow installed from info ==================
Name: tensorflow
Version: 2.9.1
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /Users/laut/pwd/lib/python3.9/site-packages
Required-by: 

== python version  ==============================================
(major, minor, micro, releaselevel, serial)
(3, 9, 0, 'final', 0)

== bazel version  ===============================================

**Comment by PierrickPochelu** [comment]
```
import pandas as pd
import keras
from keras import layers
import numpy as np
temp = pd.DataFrame(data={
    "x1":["a", "b", "c", "a", "b", "c", "a", "b", "c", "a"],
    "x2":["d", "e", "f", "e", "f", "d", "e", "f", "d", "e"],
    "x3":[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "y":[0.2, 0.6, 0.9, 0.4, 1.0, 0.1, 0.3, 0.5, 0.8, 0.7]
    })

embedding_input1 = keras.Input(shape=(None,), dtype="string", name="embedding_input1")
embedding_stringlookup1 = layers.StringLookup(vocabulary=list(temp.x1.unique()), num_oov_indices=0, name="embedding_stringlookup1")(embedding_input1)
embedding_feat1 = layers.Embedding(input_dim=len(temp.x1.unique()), output_dim=2, name="embedding_layer1")(embedding_stringlookup1)
embedding_lstm1 = layers.LSTM(units=100, name="embedding_lstm1")(embedding_feat1)

embedding_input2 = keras.Input(shape=(None,), dtype="string", name="embedding_input2")
embedding_stringlookup2 = layers.StringLookup(vocabulary=list(temp.x2.unique()), num_oov_indices=0, name="embedding_stringlookup2")(embedding_input2)
embedding_feat2 = layers.Embedding(input_dim=len(temp.x2.unique()), output_dim=2, name="embedding_layer2")(embedding_stringlookup2)
embedding_lstm2 = layers.LSTM(units=100, name="embedding_lstm2")(embedding_feat2)

numeric_input = keras.Input(shape=(1,), dtype="int64", name="numeric_input") #<================ UPDATE HERE
numeric_layer = layers.Dense(units=100, name="numeric_dense_layer")(numeric_input)

comb_inputs = layers.concatenate(inputs=[embedding_lstm1, embedding_lstm2, numeric_layer], axis=1)

output = layers.Dense(units=1, name="output")(comb_inputs)

model = keras.Model(inputs=[embedding_input1, embedding_input2, numeric_input], outputs=output, name="example_model")  #<================ UPDATE HERE

model.compile(
    loss=keras.losses.mean_squared_error,
    optimizer=keras.optimizers.RMSprop(),
    metrics=["mean_squared_error"]
)

#keras.utils.plot_model(model, "embedding_from string_example.png", show_shapes=True) # I commented it

history = model.fit(
    x={"embedding_input1":temp.x1, "embedding_input2":temp.x2, "numeric_input":temp.x3},
    y=temp.y,
    batch_size=2,
    epochs=5,
    validation_split=0.2
    )
```

returns

_Epoch 1/5
4/4 [==============================] - 3s 205ms/step - loss: 0.3886 - mean_squared_error: 0.3886 - val_loss: 0.0838 - val_mean_squared_error: 0.0838
Epoch 2/5
4/4 [==============================] - 0s 9ms/step - loss: 0.1614 - mean_squared_error: 0.1614 - val_loss: 0.0519 - val_mean_squared_error: 0.0519
Epoch 3/5
4/4 [==============================] - 0s 9ms/step - loss: 0.1535 - mean_squared_error: 0.1535 - val_loss: 0.0271 - val_mean_squared_error: 0.0271
[...]_
