### ISSUE TITLE
Function _create_seed() in keras.backend causes DeprecationWarning in Python 3.10

### ISSUE THREAD

**Issue by jedrek-VL** [keras-team/keras#17149]
In [line 2032 of keras.backend.py](https://github.com/keras-team/keras/blob/af1408d3255e3db9067522762e22a6c454c56654/keras/backend.py#L2032) we call random.randint(1, 1e9), which causes DeprecationWarning in Python 3.10 and will raise an error in some future version of Python. I suggest to replace it with `random.randint(1, int(1e9))` or `random.randint(1, 1000000000)`.

**Comment by sushreebarsa** [comment]
@jedrek-VL We have raised one PR to fix this issue. This ticket will be closed once the PR is merged.
Thank you!
