### ISSUE TITLE
Y_pred = model.predict_classes(X_test) Y_pred

### ISSUE THREAD

**Issue by Pratik-12a** [keras-team/keras#17156]
Can you please help me in solving this errror

Y_pred = model.predict_classes(X_test) Y_pred

AttributeError                            Traceback (most recent call last)
<ipython-input-29-abd0b9b99a1f> in <module>
----> 1 Y_pred = model.predict_classes(X_test)
      2 Y_pred

AttributeError: 'Sequential' object has no attribute 'predict_classes'

**Comment by Mohit-robo** [comment]
In the newest version of Tensorflow, the predict_classes function has been deprecated (there was a warning in previous versions about this). The new syntax is as follows:

    Y_pred = np.argmax(model.predict(X_test),axis=1)

**Comment by sushreebarsa** [comment]
@Pratik-12a Could you refer the comment above and let me know if t helps?
Thank you!
