### ISSUE TITLE
Library for feature extraction for Keras models

### ISSUE THREAD

**Issue by LukasMut** [keras-team/keras#17192]
I just wanted to let you know that we are working on a library that facilitates feature extraction (i.e., extraction of image representations) for Keras models. :) Here's the link to our library: https://github.com/ViCCo-Group/THINGSvision. Maybe, you'll find it useful. This is actually not a documentation issue, but I was not sure where else to mention it.

**Comment by tilakrayal** [comment]
@LukasMut,
Could you please elaborate about your Feature. Also, please specify the Use Cases for this feature. Thank you!
