### ISSUE TITLE
OSError: Unable to open file (truncated file: eof = 1180918, sblock->base_addr = 0, stored_eof = 61980832)

### ISSUE THREAD

**Issue by fatimaBM** [keras-team/keras#17200]
hello everyone
The data_set variable is an NwbDataSet instance, which has some methods we can use to access the injected current stimulus waveform and the voltage response waveform for all experimental sweeps. Let's pull one sweep out and plot it.
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

sweep_number = 30
sweep_data = data_set.get_sweep(sweep_number)

index_range = sweep_data["index_range"]
i = sweep_data["stimulus"][0:index_range[1]+1] # in A
v = sweep_data["response"][0:index_range[1]+1] # in V
i *= 1e12 # to pA
v *= 1e3 # to mV

sampling_rate = sweep_data["sampling_rate"] # in Hz
t = np.arange(0, len(v)) * (1.0 / sampling_rate)

plt.style.use('ggplot')
fig, axes = plt.subplots(2, 1, sharex=True)
axes[0].plot(t, v, color='black')
axes[1].plot(t, i, color='gray')
axes[0].set_ylabel("mV")
axes[1].set_ylabel("pA")
axes[1].set_xlabel("seconds")
plt.show()

But it doesn't show the image and gives this error

OSError: Unable to open file (truncated file: eof = 1180918, sblock->base_addr = 0, stored_eof = 61980832)

how to solve this problem?
thank you

**Comment by tilakrayal** [comment]
@fatimaBM,
I was facing a different error while executing the mentioned code. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/132963d13568e5d98ea1388388f9c6b3/untitled724.ipynb) and provide the required dependencies. Thank you!
