### ISSUE TITLE
The dimension of y_pred changes when using a custom loss function

### ISSUE THREAD

**Issue by AshwinJay101** [keras-team/keras#17201]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): 2.6
- Python version: 3.8
- Bazel version (if compiling from source): N/A
- GPU model and memory: V100
- Exact command to reproduce: See snippet 

**Describe the problem**.
The dimension of y_pred when passed to a custom loss function is different from what is passed to the model in the fit method.  If you notice, I pass ys to be without any dimension. When printing the value inside the loss_fn, I notice that a dimension has been added. This causes an issue when writing loss functions due to dimension mismatches, This is a simple code here but in general this is different 

**Describe the current behavior**.
The function appends a dimention to y_true, I expected y_true to be of the form `[[0 1]]` instead of `[[[0] [1]]]`. This causes dimention mismatch issues after onehot encoding and passing to the crossentropy function

**Describe the expected behavior**.
y_true does not add the extra dimension. This leads to confusion when writing custom loss functions 

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no): no
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**.

Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```
xs = np.array([-1.0, 0.0, 1.0, 2.0, 3.0, 4.0], dtype=float)
# labels
ys = np.array([1, 0, 1, 0, 0, 0], dtype=int)
def my_custom_loss(y_true, y_pred):
    tf.print(y_true)
    y_true = tf.cast(y_true, tf.uint8)
    y_true = tf.one_hot(y_true, depth=2)
    tf.print("one hot", y_true.numpy())
    loss_val = tf.keras.losses.CategoricalCrossentropy(from_logits=False,
                                                       label_smoothing=0.1)
    
    loss = loss_val(y_true, y_pred)
    return loss

model = tf.keras.Sequential([
    tf.keras.layers.Dense(units=2, input_shape=[1,], activation='softmax')
])

model.compile(optimizer='sgd', loss=my_custom_loss, run_eagerly=True)
model.fit(xs, ys, epochs=1, verbose=0, batch_size=2)
```

**Source code / logs**.

```
test.py:179 my_custom_loss  *
        loss = loss_val(y_true, y_pred)
    /usr/local/lib/python3.8/site-packages/keras/losses.py:141 __call__  **
        losses = call_fn(y_true, y_pred)
    /usr/local/lib/python3.8/site-packages/keras/losses.py:245 call
        return ag_fn(y_true, y_pred, **self._fn_kwargs)
    /usr/local/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py:206 wrapper
        return target(*args, **kwargs)
    /usr/local/lib/python3.8/site-packages/keras/losses.py:1665 categorical_crossentropy
        return backend.categorical_crossentropy(
    /usr/local/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py:206 wrapper
        return target(*args, **kwargs)
    /usr/local/lib/python3.8/site-packages/keras/backend.py:4839 categorical_crossentropy
        target.shape.assert_is_compatible_with(output.shape)
    /usr/local/lib/python3.8/site-packages/tensorflow/python/framework/tensor_shape.py:1161 assert_is_compatible_with
        raise ValueError("Shapes %s and %s are incompatible" % (self, other))

    ValueError: Shapes (2, 1, 2) and (2, 2) are incompatible
```

**Comment by sushreebarsa** [comment]
@AshwinJay101 Could you please have a look at this [gist](https://colab.research.google.com/gist/sushreebarsa/d96117d0577d8a3545040d83e2542d44/17201.ipynb) and confirm the issue?
Thank you!

**Comment by AshwinJay101** [comment]
@sushreebarsa Yes this is the issue

**Comment by sushreebarsa** [comment]
@AshwinJay101 One-hot encoding to be done before passing data to training otherwise shape compatibility issues may arise. Could you refer this modified gist [here](https://colab.research.google.com/gist/SuryanarayanaY/e30b600097ca9c583126ed16099fc98b/17201.ipynb) and let us know if it helps?
Thank you!

**Comment by AshwinJay101** [comment]
Thanks this is a good workaround. My only issue is that I wanted to do the one hot encoding on the GPU instead of the CPu since the former is faster.

**Comment by SuryanarayanaY** [comment]
Hi @AshwinJay101 ,
You can use `tf.device()` as mentioned below incase wanted to run one hot encoding also on GPU.
```
with tf.device('GPU'):
  ys = tf.one_hot(ys,depth=2)
```
For more information please refer to attached documentation link [GPU](https://www.tensorflow.org/guide/gpu).

Thankyou!

**Comment by AshwinJay101** [comment]
Thanks. If I use tf data to provide the inputs, would this still work

**Comment by SuryanarayanaY** [comment]
Sure @AshwinJay101 ,
You can still use it for Dataset generator also.Even we can put our complete model also inside tf.device('GPU') like the one in attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/25c90a386fda37e21ad8a1796ba1ebf8/copy-of-17201-r2.ipynb) here.

**Comment by AshwinJay101** [comment]
Thanks

**Comment by SuryanarayanaY** [comment]
@AshwinJay101 ,
Could you please close this issue if your issue resolved.
Thankyou!
