### ISSUE TITLE
Converting model to frozen pb causes original model to go into an "Invalid State"

### ISSUE THREAD

**Issue by matthewfernst** [keras-team/keras#17218]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

binary

### Tensorflow Version

2.4 / 2.9.2 (Occurs on both)

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 18.04

### Python version

3.8

### Current Behaviour?

I currently am trying to convert a Tensorflow 2 Keras model into a Tensorflow 1 frozen pb. My code is able to accomplish this and freezes the model correctly. I do this by creating my model, then saving it as an h5, then load that models h5 as a separate model and freeze it.

However, if I try to load and freeze the model and then continue on to use the original model (the untouched one), it's put into an "Invalid State". I've tried looking to see if there is an issue with the keras backend session being confused or if the two models have the same reference but they are all separate. 

It's as if the original model and the loaded model are the same one. I'm not sure if this is a bug or more likely user error.

### Standalone code to reproduce the issue

```python
# create, compile, train original model | or load original model 

original_model.save('original_model.h5', save_format='h5')
convert_to_pb('original_model.h5')

original_model.predict(inp) # Error occurs here

-----------------------------------------
# Convert Script

import tensorflow as tf

def convert_to_pb(h5_file):
    with tf.compat.v1.keras.backend.get_session() as sess:
        model = tf.keras.models.load_model(h5_file)

        graph = sess.graph
        output_names = [out.op.name for out in model.outputs]
        input_graph_def = graph.as_graph_def()

        for node in input_graph_def.node:
            node.device = ""
        
        frozen_graph = tf.compat.v1.graph_util.convert_variables_to_constants(sess, input_graph_def, output_names)
        frozen_graph = tf.compat.v1.graph_util.remove_training_nodes(frozen_graph)

        tf.io.write_graph(frozen_graph, '.', 'frozen_model.pb', as_text=False)
```

A gist can be found [here](https://colab.research.google.com/gist/matthewfernst/98743463177ee1d85bb4870bb454b79c/untitled727.ipynb) with the code.

### Relevant log output

```shell
ValueError: Your Layer or Model is in an invalid state. This can happen for the following cases:
1. You might be interleaving estimator/non-estimator models or interleaving models/layers made in tf.compat.v1.Graph.as_default() with model/layers created outside of it. Converting a model to an estimator (via model_to_estimator) invalidates all models/layers made before the conversion (even if they were not the model converted to an estimator). Similarly, making a layer or a model inside a a tf.compat.v1.Graph invalid$tes all layers/models you previously made outside of the graph. 
2. You might be using a custom keras layer implementation with  custom __init__ which didn't call super().__init__.  Please check the implementation of <class 'tensorflow.python.keras.layers.convolutional.Conv2D'> and its bases.
```
</details>

</details>

**Comment by matthewfernst** [comment]
@sushreebarsa I was curious if this had been looked into? Thank you!

**Comment by sushreebarsa** [comment]
@SuryanarayanaY I was able to replicate the issue on colab, please find the [gist](https://colab.research.google.com/gist/sushreebarsa/644f69677019706c0522aaa9b5af5c2d/untitled727.ipynb#scrollTo=s6s9TPsw_uNw) here. Thank you!

**Comment by SuryanarayanaY** [comment]
Hi @matthewfernst ,

As we can see in the error log s.no.1 `Similarly, making a layer or a model inside a a tf.compat.v1.Graph invalidates all layers/models you previously made outside of the graph.`This means whenever we call the tf.compat.v1.graph API internally Tensorflow is invalidating all the models/layers that are stored in the current thread.Hence we are losing the `original_model` data which is expected behaviour. To prove this i have created `another_model` and this model we are not going to use for graph generation.

`another_model = model()`

After generating the graph for `original_model` call `predict()` on both models and you observe same behaviour for both.This means that the statement mentioned above is validated right? If you again call the `predict()` on the `original_model` at the end of your gist it will give required predictions.
 
Please note that in the above code we are not instantiating data to `random_input_data` again.Since it is neither a model nor a layer it lived in the current thread and giving the predictions on model. Please refer the attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/481b2ae3d332b512646fe4617c82bc84/17218-r1.ipynb#scrollTo=QA0SHmnq9ONw) also for the proof.

I hope this clarifies your doubt.
Thankyou!

**Comment by matthewfernst** [comment]
@SuryanarayanaY thank you so much for the information! Yes this makes sense, I guess is there a workaround instead of reinitiating the model? 

Potentially saving the state of the graph before calling that function and then resetting the state? Thank you!

**Comment by SuryanarayanaY** [comment]
Hi @matthewfernst ,
I have explored and found the below two APIs will serve your purpose of saving the model graph without invalidating even after converting the model to frozen graph.

Solution:1
```
config = original_model.get_config() 
new_model = tf.keras.Model.from_config(config)
```
Solution:2
```
json_config = original_model.to_json()
new_json_model = tf.keras.models.model_from_json(json_config)
```

Please also refer the attached [gist1](https://colab.research.google.com/gist/SuryanarayanaY/93829ed0fe7ecd82250906410179bff4/17218-r2.ipynb) and [gist2](https://colab.research.google.com/gist/SuryanarayanaY/d9a989492d28953b7214558b6a59e036/17218-r2-2nd-way.ipynb#scrollTo=TKk8ghCqHKCo) here for the same example we are working previously.
Could you please go through and confirm whether it solves your purpose.

Thankyou!

**Comment by matthewfernst** [comment]
Hi @SuryanarayanaY,

Thanks for the solution! I am able to get this to work for normal Keras models. However, the model that I am working on, wraps the original layer into another layer. For instance, if I had a Conv2D layer, I would wrap it in another custom layer that has underlying C++ calls. Due to this, I get the error below for both solutions. 

```console
File "/usr/lib/python3.8/copy.py", line 161, in deepcopy 
    rv = reductor(4)
TypeError: cannot pickle 'backend.CustomLayer' object
```

Is there a way around this? Perhaps I need to implement something in my layer class? Thank you so much for your help! Really appreciate it!

**Comment by SuryanarayanaY** [comment]
Hi @matthewfernst ,

Glad that we are of little help for you. For custom layers please refer the attached documentation links [here](https://www.tensorflow.org/tutorials/customization/custom_layers) and [here](https://www.tensorflow.org/guide/keras/custom_layers_and_models#you_can_optionally_enable_serialization_on_your_layers) and see whether it helpful for you. The new error you are facing seems to be a different one. Could you please raise another issue with the corresponding context and error statement by providing minimal code snippet to dig into the problem.This will be helpful to us and larger community to track the issue more efficiently.We will definitely address your issue there.

Thankyou!

**Comment by matthewfernst** [comment]
@SuryanarayanaY, Sounds good! Thank you so much for help. I really appreciate it!

**Comment by matthewfernst** [comment]
@SuryanarayanaY Hi there. I finally got my config portion to work on my custom layers and this issue is still persisting. Do you have another solution? Thanks!
