### ISSUE TITLE
tf.keras.utils.get_file() produces duplicate file with dot underscore "._" 

### ISSUE THREAD

**Issue by pocathoughts** [keras-team/keras#17244]
How do I prevent the untar from the above get_file() call from creating duplicate "._*" files?

I get double the images in the dataset when I run the following, and the duplicated images have a prefix of ._

import pathlib
import matplotlib.pyplot as plt
import numpy as np
import PIL
import tensorflow as tf

from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential

# custom data attempt
weeds_dataset_url = "https://storage.googleapis.com/aquarium-public/datasets/deepweeds/full_image_set/weed_images.tar"
weeds_data_dir = tf.keras.utils.get_file('weed_images', origin=weeds_dataset_url, untar=True)
weeds_data_dir = pathlib.Path(weeds_data_dir)

snake_weeds = list(weeds_data_dir.glob('Snake weed/*'))
print(snake_weeds[0]) # gives me a file starting with ._

**Comment by pocathoughts** [comment]
Still an issue

**Comment by tilakrayal** [comment]
@pocathoughts,
I tried to execute the code and was able to save the images without any issues. And also those images are being saved in the expected format. Kindly find the below image for the reference. Please try to clear the cache and try to save the images. Thank you!

![image](https://user-images.githubusercontent.com/81610181/202133426-9092f396-679c-4747-a263-9080d0367654.png)
