### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by pure-rgb** [keras-team/keras#17255]
I want to recompile the model using callback but it does not work. See below. I'm using TF 2.9.

```python
import tensorflow as tf
from tensorflow import keras

# Define the Keras model to add callbacks to
def get_model():
    model = keras.Sequential()
    model.add(keras.layers.Dense(1, input_dim=784))
    model.compile(
        optimizer=keras.optimizers.RMSprop(learning_rate=0.1),
        loss="mean_squared_error",
        metrics=["mean_absolute_error"],
    )
    return model


# Load example MNIST data and pre-process it
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()
x_train = x_train.reshape(-1, 784).astype("float32") / 255.0
x_test = x_test.reshape(-1, 784).astype("float32") / 255.0

# Limit the data to 1000 samples
x_train = x_train[:1000]
y_train = y_train[:1000]
x_test = x_test[:1000]
y_test = y_test[:1000]
```

In below, see in `on_epoch_begin` method, where recompiling is tried. For this, training can not be done. How to enable recompiling the keras model?

```python
class CustomLearningRateScheduler(keras.callbacks.Callback):
    """Learning rate scheduler which sets the learning rate according to schedule.

  Arguments:
      schedule: a function that takes an epoch index
          (integer, indexed from 0) and current learning rate
          as inputs and returns a new learning rate as output (float).
  """

    def __init__(self, schedule):
        super(CustomLearningRateScheduler, self).__init__()
        self.schedule = schedule

    def on_epoch_begin(self, epoch, logs=None):
        if not hasattr(self.model.optimizer, "lr"):
            raise ValueError('Optimizer must have a "lr" attribute.')
        # Get the current learning rate from model's optimizer.
        lr = float(tf.keras.backend.get_value(self.model.optimizer.learning_rate))
        # Call schedule function to get the scheduled learning rate.
        scheduled_lr = self.schedule(epoch, lr)
        # Set the value back to the optimizer before this epoch starts
        tf.keras.backend.set_value(self.model.optimizer.lr, scheduled_lr)
        
        self.model.compile(
            optimizer=keras.optimizers.RMSprop(learning_rate=0.1),
            loss="mean_squared_error",
            metrics=["mean_absolute_error"],
        )
        print("\nEpoch %05d: Learning rate is %6.4f." % (epoch, scheduled_lr))


LR_SCHEDULE = [
    # (epoch to start, learning rate) tuples
    (3, 0.05),
    (6, 0.01),
    (9, 0.005),
    (12, 0.001),
]


def lr_schedule(epoch, lr):
    """Helper function to retrieve the scheduled learning rate based on epoch."""
    if epoch < LR_SCHEDULE[0][0] or epoch > LR_SCHEDULE[-1][0]:
        return lr
    for i in range(len(LR_SCHEDULE)):
        if epoch == LR_SCHEDULE[i][0]:
            return LR_SCHEDULE[i][1]
    return lr


model = get_model()
model.fit(
    x_train,
    y_train,
    batch_size=64,
    steps_per_epoch=5,
    epochs=15,
    verbose=0,
    callbacks=[
        CustomLearningRateScheduler(lr_schedule),
    ],
)
```

```

Epoch 00000: Learning rate is 0.1000.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_27/3511289952.py in <module>
     58     verbose=0,
     59     callbacks=[
---> 60         CustomLearningRateScheduler(lr_schedule),
     61     ],
     62 )

/opt/conda/lib/python3.7/site-packages/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
   1182                 _r=1):
   1183               callbacks.on_train_batch_begin(step)
-> 1184               tmp_logs = self.train_function(iterator)
   1185               if data_handler.should_sync:
   1186                 context.async_wait()

TypeError: 'NoneType' object is not callable
```

**Comment by Suzan009** [comment]
Is it valid? The error mainly occurs for this, where I try to recompile the model.

```python
class CustomLearningRateScheduler(keras.callbacks.Callback):
    def on_epoch_begin(self, epoch, logs=None):
        self.model.compile(
            optimizer=keras.optimizers.RMSprop(learning_rate=0.1),
            loss="mean_squared_error",
            metrics=["mean_absolute_error"],
        )
```

**Comment by sushreebarsa** [comment]
@SuryanarayanaY I was able to replicate the issue on colab, please find the [gist ](https://colab.research.google.com/gist/sushreebarsa/f38e2c1e1ef33a776f20cf4da8a5c8cb/17255.ipynb)here. Thank you!

**Comment by SuryanarayanaY** [comment]
Hi @Suzan009 ,

Thanks for writing us. Calling `model.compile()` in Custom Callbacks not valid.Whenever we call `model.fit()` internally TF calls `make_train_function()` which creates a function that executes one step of training. This function is cached the first time `Model.fit` or `Model.train_on_batch` is called. The cache is cleared whenever`Model.compile` is called.Hence the error `'NoneType' object is not callable` might be popping out.Please refer to source [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/engine/training.py#L813-825) for more details.

However we can define our own `compile()` method by Subclassing our model to `tf.keras.Model` API and then we can override the default `train_step()` method and configure it wrt loss functions and optimizers as per our requirement.Please find the attached [example](https://www.tensorflow.org/guide/keras/customizing_what_happens_in_fit#going_lower-level) for one such use case.

Thankyou!

**Comment by Suzan009** [comment]
@SuryanarayanaY 
I've found an issue that is somewhat similar to mine, https://github.com/keras-team/keras/issues/13368. It was closed as complete on Jun 25, 2021. What does it mean?

I've a case where I need to recompile with different parameter inside the `self.model.compile` method during the training time. As you said, calling `model.compile()` in custom callback is not valid. Well, I would argue a bit, see a ticket here https://github.com/keras-team/keras/issues/9477, It looks that it was cetainly possible to do that but this issue was also closed on Jun 25, 2021 by keras author. What a coincident!

**Comment by innat** [comment]
@gowthamkpr 
I think it's a valid request to able to recompile the model using callback. Here is the [gist](https://colab.research.google.com/drive/1EbGCWdLMIYm7lWCbaaIDL2Rih7NL8ma5?usp=sharing).

https://github.com/keras-team/keras/issues/9477
https://github.com/keras-team/keras/issues/13368
S0: https://stackoverflow.com/q/75361509/9215780 

cc. @ahundt
