### ISSUE TITLE
about lstm 

### ISSUE THREAD

**Issue by Turningl** [keras-team/keras#17268]
I would like to ask a very simple question. lstm module of keras is really good, one line of simple code can run lstm algorithm. My question is: In pytorch lstm needs to pass h0, c0, but it seems that in keras lstm only needs to pass x. Can you please tell me how h0, c0 are defined or pre-set in lstm in Keras?

**Comment by sushreebarsa** [comment]
@Turningl 
Could you please elaborate about your feature and  specify the use cases for this feature. Thank you!
