### ISSUE TITLE
自动驾驶更新笔记 Autopilot Updating Notes

### ISSUE THREAD

**Issue by nwaysir** [keras-team/keras#17277]
您好，仓库内容很全面，非常受益， 可否引荐下本人的笔记，把我对自动驾驶的理解分享给大家，希望大家和我一起不断完善相关内容，谢谢您！

Hello, the content of the repository is very comprehensive and very beneficial. Could you introduce my notes and share my understanding of autopilot with others? I hope you can continue to improve the relevant content with me, thank you!

[Autopilot-Updating-Notes](https://github.com/nwaysir/Autopilot-Updating-Notes)

**Comment by sushreebarsa** [comment]
@nwaysir Could you describe the issue reported here, please provide use cases for this feature?
Thank you!
