### ISSUE TITLE
ModelCheckpoint callback fails when mixed precision is enabled in TF 2.11.0

### ISSUE THREAD

**Issue by goncinious** [keras-team/keras#17275]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 22.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.1..0
- Python version: 3.7.15
- GPU model and memory: Tesla T4 (16GB)
- Exact command to reproduce: see [Colab](https://colab.research.google.com/drive/1XaZ0NlySrBkNJ9W6rc8eF_A4VKQY5yEk?usp=sharing)

**Describe the problem**.

After upgrading to TensorFlow 2.11.0, I haven't been able to use the `ModelCheckpoint` callback in `model.fit()` with mixed precision enabled. Works fine with full precision specified with `set_global_policy("float32")`. See failure example below:

```python
import tensorflow as tf

tf.keras.mixed_precision.set_global_policy("mixed_float16")

dataset = tf.data.Dataset.from_tensors(([1.0], [1.0])).repeat(100).batch(10)
model = tf.keras.Sequential([tf.keras.layers.Dense(1, input_shape=(1,))])
callbacks = [
    tf.keras.callbacks.ModelCheckpoint(
                filepath="model.h5",
                verbose=1,
            )
]
model.compile(loss="mse", optimizer=tf.keras.optimizers.Adam())
model.fit(dataset, validation_data=dataset,  epochs=5, callbacks=callbacks)
```

Output:

```python
---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

[<ipython-input-8-9ca68522b763>](https://localhost:8080/#) in <module>
     17 ]
     18 model.compile(loss="mse", optimizer=tf.keras.optimizers.Adam())
---> 19 model.fit(dataset, validation_data=dataset,  epochs=5, callbacks=callbacks)

1 frames

[/usr/local/lib/python3.7/dist-packages/keras/optimizers/optimizer_experimental/optimizer.py](https://localhost:8080/#) in variables(self)
    773     def variables(self):
    774         """Returns variables of this optimizer."""
--> 775         return self._variables
    776 
    777     def set_weights(self, weights):

AttributeError: 'LossScaleOptimizerV3' object has no attribute '_variables'
```

**Standalone code to reproduce the issue**.

See [Colab](https://colab.research.google.com/drive/1XaZ0NlySrBkNJ9W6rc8eF_A4VKQY5yEk?usp=sharing).

**Comment by tilakrayal** [comment]
@goncinious,
I tried to execute the code in the alternative approach  and was able to execute without any issues/error. And also the model will use bfloat16 as its compute data type.

```
from tensorflow.keras import mixed_precision
policy = mixed_precision.Policy('mixed_bfloat16')
mixed_precision.set_global_policy(policy)
```
Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/5292a13779231ac424b49fb6eb4b6366/17275.ipynb). Thank you!

**Comment by tilakrayal** [comment]
@goncinious,
Have you got the chance to take a look at this related PR where the PR delegates **finalize_variable_values()** in **LossScaleOptimizerV3** to the wrapped optimizer and also it fixes the exponential moving averages when used together with mixed precision. Thank you!

**Comment by goncinious** [comment]
@tilakrayal I had already seen https://github.com/keras-team/keras/pull/17225, but I noticed that the change is already part of TF 2.11, where this issue was observed.

I understand that this likely requires a similar fix. I'd be happy to contribute, but currently don't have the bandwidth to focus on it. Could you please assign someone that could help?

**Comment by reedwm** [comment]
> 1. `mixed_bfloat16` works for LossScaleOptimizer while `mixed_float16` does not , do they take different code paths?

LossScaleOptimizer is only used for `mixed_float16`. Looks like calling `Model.save` for the h5 format on a model with LossScaleOptimizer is broken. I will take a look.

> 2. Seems `MaxPool3D` does not support `mixed_bfloat16`, is there a quick fix for that?

Currently many ops are not supported with bfloat16 except through XLA, but @trevor-m is working on adding bfloat16 to all major ops. Note all major ops do support float16, just not yet bfloat16.
