### ISSUE TITLE
Validation_split changing the input dimensions

### ISSUE THREAD

**Issue by Mark531** [keras-team/keras#17319]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win 64
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.11.0
- Python version: 3.9.12
- Bazel version (if compiling from source):
- GPU model and memory:
- Exact command to reproduce:

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with:
python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"

**Describe the problem**.

I have an issue with training a multi-input model with validation_split flag. When I don't set the flag, the model trains well. When I set it, I get an error.

I tried to pass validation data instead to the fit method, but I get the very same error.

**Describe the current behavior**
If I train this model during one epoch:
```
product_id_input = Input(shape=(MAX_CART_SIZE,), name="product_id")
category_input = Input(shape=(MAX_CART_SIZE,), name="category")
account_input = Input(shape=(1,), name="account_id")
...
inputs = {"product_id": product_id_input, "category": category_input, "account": account_input}

model = Model(inputs, outputs)

model.compile(loss="sparse_categorical_crossentropy", optimizer="adam.", metrics=["accuracy"])

X_train = {"product_id": product_id_enc_train, "category": category_enc_train, "account": account_enc_train}
y_train = target_enc_train

history = model.fit(X_train,
                    y_train,
                    batch_size=512,
                    epochs=1,
                    shuffle=False)
```

It works fine. The input shapes are correct:

```
product_id_enc_train.shape
Out[74]: (143824, 69)

category_enc_train.shape
Out[75]: (143824, 69)

account_enc_train.shape
Out[77]: (143824,)

target_enc_train.shape
Out[78]: (143824,)
```
But if I add the option validation_split=0.2, then it raises an exception upon epoch completion:

>     ValueError: Input 1 of layer "model" is incompatible with the layer: expected shape=(None, 69), found shape=(None, 75)

**Describe the expected behavior**.

I expect validation_split to only split the dataset without changing the input tensors' shapes. Passing the data directly with the validation_data parameter triggers the same error.

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no): no
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**.

I tried to reproduce the problem on a minimal example but I failed. If you don't have a clue about where this problem comes from, I can try to share the complete code.

**Source code / logs**.

**Comment by SuryanarayanaY** [comment]
Hi @Mark531 ,

The option `validation_split` is not supported when `x` is a `dataset, generator `or `keras.utils.Sequence` instance.Please refer source below and for more info please refer attached API [link](https://www.tensorflow.org/api_docs/python/tf/keras/Model?version=nightly#fit).

https://github.com/keras-team/keras/blob/master/keras/engine/training.py#L1432-L1434

Could you please confirm whether the input you are feeding to model is in any of above categories ? If so then `validation_split` won't work and you can choose option `validation_data` though.

Also if the model has named inputs i.e. Inputs should be inform of Arrays or Tensors only

> A dict mapping input names to the corresponding array/tensors, if the model has named inputs.

Please cross check above conditions and confirm.

Thankyou!

**Comment by Mark531** [comment]
Hi @SuryanarayanaY,

Thanks for your feedback. In fact, my input is a dictionary of numpy arrays (see the input shapes I displayed). It made it possible to pass the right data to the right network inputs.

Regards,
Mark

**Comment by SuryanarayanaY** [comment]
Hi @Mark531 ,

Could you please provide some sample data so that i can try to replicate the issue and may possibly resolve it.
Can you please confirm what is the value of `MAX_CART_SIZE` you are passing to Input layer below
`product_id_input = Input(shape=(MAX_CART_SIZE,), name="product_id")`

As per the error you got it should not be train even without `validation_data` or `validation_split` since these only changes the No of data points(rows) but not features.

Please provide complete code along with some input data so that i can try to replicate the issue to better understand the problem.

Thankyou!

**Comment by old-school-kid** [comment]
Hi @SuryanarayanaY ,
I think I was able to reproduce the code. But unfortunately I did not find any error. 
Would you please let me know of this was the case or there was something else. 
Thanks
[Link to the coalb file](https://colab.research.google.com/drive/1irTZ8i00ULFX4VUSrPIWj1qoPBlVZYjc?usp=sharing)

**Comment by Mark531** [comment]
Guys, after several experiments, I think I understand the context when the problem occurs.

If you run a fit with incorrect validation_data, you get an error. Ok. But then if you run fit again when using validation_split instead, you get the same error. It's as if keras was keeping in memory the previous validation data, without taking into account the validation_split parameter which should erase it.

I guess a quick glance at the code should allow you to pinpoint the issue. Otherwise, tell me if you want me to provide a toy sample code that reproduces the problem.

**Comment by SuryanarayanaY** [comment]
@old-school-kid ,
Thanks for the code snippet for replication.I can see there is no error in Colab environment as per attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/7981960bae43172f18b6b61ba390a9f0/17319_keras.ipynb).

@Mark531 It would be better to submit toy code to understand the exact problem.But before that can you please confirm if you are using any GPU then you should have installed WSL2 in windows as TF 2.11V not supported on windows native.On windows native you can use tensorflow-cpu only. Please refer the documentation [reference](https://www.tensorflow.org/install/pip#windows-wsl2).

Other than validation_split whether there is any change in code ? It seems something like one hot encoding happening which is increasing the feature size.Please provide minimal code for both cases.
