### ISSUE TITLE
Add Vision Transformer to `keras.applications`

### ISSUE THREAD

**Issue by IMvision12** [keras-team/keras#17329]
If you open a GitHub issue, here is our policy:

Vision Transformer[1] is model which uses transformers-like architecture. A sequence of vectors is created by dividing a picture into fixed-size patches, linearly embedding each one, adding position embeddings, and then feeding the assembled vectors to a conventional Transformer encoder.

**Who will benefit from this feature?**

Keras users using `keras.applications` in their projects.

**Will this change the current api? How?**
``` keras.applications.ViTBase, keras.applications.ViTLarge, ... ```

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**

- Do you want to contribute a PR? (yes/no): Yes
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing): I have implemented base model of vision transformer from scratch [here](https://github.com/IMvision12/Vision-Transformer-Implementation)

### References
[1] https://arxiv.org/abs/2010.11929

@fchollet @LukeWood

**Comment by cybergeekgyan** [comment]
I would like to know more about the specific features needed to be added, Can you guide me along to make successful changes in the feature addition..

How to proceed further with this feature? Help Needed to make required changes @tilakrayal

**Comment by IMvision12** [comment]
Thanks, @cybergeekgyan. I've begun working on it and have finished some preliminary research; could you work on some other issues..

Thanks

**Comment by cybergeekgyan** [comment]
Yes sure @IMvision12 do let me know on what specific issues I can work and also let me know how to proceed further 
Thanks

**Comment by innat** [comment]
Check.
https://github.com/keras-team/keras-cv/issues/668

**Comment by IMvision12** [comment]
i guess i can close this issue..
