### ISSUE TITLE
How to add additional parameter to custom formatting in ModelCheckpoint's filepath?

### ISSUE THREAD

**Issue by Suzan009** [keras-team/keras#17331]
In https://keras.io/api/callbacks/model_checkpoint/, 

![image](https://user-images.githubusercontent.com/45315076/207058025-796cbad2-f7ac-4964-a50a-3c3b3c41c413.png)

```
weights.{epoch:02d}-{val_loss:.2f}.hdf5
```

Now, how can we add custom variable object that are not part of the `epoch` and `logs`? For example 

```python
lr = 0.01
model_name = 'gcnn'
version = 1
model_checkpoint_callback = tf.keras.callbacks.ModelCheckpoint(
    filepath=weights.{epoch:02d}.hdf5,
    filepath=f'{version}'_{model_name}_{lr}_weights.{epoch:02d}.hdf5,
)
```

**Comment by old-school-kid** [comment]
@Suzan009 
I havent given it a try but `learning_rate` is a parameter in the logs itself so can be used as is. And as far as version and model_name goes I guess you have to hard code them. 
Hope it helps.

**Comment by Suzan009** [comment]
@old-school-kid Thanks for the reply. 

> as far as version and model_name goes I guess you have to hard code them.

any sample code?

**Comment by sushreebarsa** [comment]
@Suzan009 Could you please refer to this [doc](https://keras.io/api/optimizers/) for using optimizers in custom training?
 Thank you!
