### ISSUE TITLE
autocast=False not respected when saving/loading Keras model

### ISSUE THREAD

**Issue by JustASquid** [keras-team/keras#17362]
Please go to TF Forum for help and support:

https://discuss.tensorflow.org/tag/keras

If you open a GitHub issue, here is our policy:

**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.9.3
- Python version: 3.9
- Bazel version (if compiling from source): -
- GPU model and memory: -
- Exact command to reproduce: -

**Describe the problem**.

See https://github.com/tensorflow/tensorflow/issues/58940

In the below code, the intention is to create a model that takes an input of type `float32` when saved, even if it is trained with `mixed_precision`. In this example, training code is omitted, and `call()` is just a placeholder for conciseness, but it still shows the issue.

The problem comes when loading the model. Because it has `autocast=False` I would expect that the model is saved with an input type of `tf.float32`. But it seems that the model is saved in an invalid state, because it loads with an error. If I use an input signature to force the input to be of type tf.float32, the error is the same.

The error is the same even if you call `tf.keras.mixed_precision.set_global_policy("float32")` before loading the model.

**Standalone code to reproduce the issue**.

```python
import keras
import tensorflow as tf

class MyModel(keras.Model):
    def __init__(self):
        super().__init__(autocast=False)

    def call(self, inputs):
        return 0

def main():
    tf.keras.mixed_precision.set_global_policy("mixed_float16")

    model = MyModel()

    inputs = tf.zeros(shape=(1, 1), dtype=tf.float32)

    prediction_0 = model(inputs)

    model_path = "test_model"

    model.save(model_path)

    loaded_model = keras.models.load_model(model_path)

    prediction_1 = loaded_model(inputs)

if __name__ == "__main__":
    main()
```

**Source code / logs**.

```
ValueError: Exception encountered when calling layer "my_model" (type MyModel).

Could not find matching concrete function to call loaded from the SavedModel. Got:
  Positional arguments (1 total):
    * <tf.Tensor 'inputs:0' shape=(1, 1) dtype=float16>
  Keyword arguments: {}

 Expected these arguments to match one of the following 2 option(s):

Option 1:
  Positional arguments (1 total):
    * TensorSpec(shape=(None, 1), dtype=tf.float32, name='inputs')
  Keyword arguments: {}

Option 2:
  Positional arguments (1 total):
    * TensorSpec(shape=(None, 1), dtype=tf.float32, name='input_1')
  Keyword arguments: {}

Call arguments received by layer "my_model" (type MyModel):
  • args=('tf.Tensor(shape=(1, 1), dtype=float16)',)
  • kwargs=<class 'inspect._empty'>

Process finished with exit code 1
```

**Comment by sushreebarsa** [comment]
@SuryanarayanaY I was able to replicate the issue, please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/fcb91c95c9d058e02c5c7809fffa4f00/17362-keras.ipynb). Thank you!

**Comment by SuryanarayanaY** [comment]
Similar to issue  #[58937](https://github.com/tensorflow/tensorflow/issues/58937) with minor difference that this issue is without `tf.function` wrapper.

**Comment by reedwm** [comment]
> In the below code, the intention is to create a model that takes an input of type float32 when saved, even if it is trained with mixed_precision.

If you want a model that takes in an input of type float32, you instead can pass `dtype="float32"` to the the super constructor:

```python
class MyModel(keras.Model):
  def __init__(self):
    super().__init__(dtype="float32")

  def call(self, inputs):
    return 0
```

This will cause the inputs in `call` to be float32 (even if float16 inputs are passed). Any layers you create in the model will still use the global policy dtype of `mixed_float16` and therefore cast their inputs to float16. This is useful if you want the inputs and the initial computations of the model to be float32 but keep the rest of the model in mixed precision.

Still, this is a bug and should be fixed. But I'm not familiar with SavedModel enough to address this issue. @hertschuh, can you reassign to someone who works on SavedModel?

**Comment by JustASquid** [comment]
@reedwm Thanks for the suggested workaround! However it doesn't seem to work in the case of nested models, where we want the outer model to accept float32 input and the inner models to use float16 computation, e.g.

```python
import keras
import tensorflow as tf
import numpy as np
from keras import Model, Input

class InnerModel(keras.Model):
    def call(self, inputs, training=None, mask=None):
        return inputs

class OuterModel(keras.Model):
    def __init__(self):
        super().__init__(autocast=False, dtype=tf.float32)
        self.inner_model = InnerModel()
        self.model = self.make_model()

    def call(self, inputs, training=None, mask=None):
        return self.model(inputs, training, mask)

    def make_model(self):
        im_input = Input(shape=())
        x = self.inner_model(im_input)
        return Model(inputs=[im_input], outputs=x)

def main():
    tf.keras.mixed_precision.set_global_policy("mixed_float16")

    model = OuterModel()

    inputs = [np.zeros(shape=(1,), dtype=np.float32)]

    prediction_0 = model(inputs)

    model_path = "test_model"

    model.save(model_path)

    loaded_model = keras.models.load_model(model_path)

    prediction_1 = loaded_model(inputs)

    print(prediction_1)

if __name__ == "__main__":
    main()
```

The above has the error `TypeError: No common supertype of TensorSpec(shape=(None,), dtype=tf.float32, name=None) and TensorSpec(shape=(None,), dtype=tf.float16, name='inputs').`

**Comment by reedwm** [comment]
Unfortunately I'm not sure of a workaround in this case. The example above fails even if you remove `autocast=False`, in which case it looks like a fairly typical example with nested models and mixed precision. @k-w-w, can you take a look?

**Comment by JustASquid** [comment]
@reedwm @k-w-w appreciate you all looking into this.

Since we would really love to implement fp16 training, I was wondering if you could suggest any other workarounds that would allow us to save our models in a valid state after training on fp16? I don't really mind (for the moment) if inference is done in fp32 / fp16, but the input to the model ideally needs to be fp32.

**Comment by reedwm** [comment]
This was fixed in https://github.com/keras-team/keras/commit/0b96ba57c7b3cd200ff571c56443230166f79708.

**Comment by JustASquid** [comment]
@reedwm This fix does work for the original case, but not for the nested model case (https://github.com/keras-team/keras/issues/17362#issuecomment-1378162050)

The error there is: ```TypeError: No common supertype of TensorSpec(shape=(None,), dtype=tf.float32, name=None) and TensorSpec(shape=(None,), dtype=tf.float16, name='inputs').```

Any ideas/workarounds?
