### ISSUE TITLE
Unable to load model from .h5 file

### ISSUE THREAD

**Issue by faisalhazry** [keras-team/keras#17372]
currently i am using anaconda and python 3.6

i have .h5 but cannot load plz help me solve this error 

i type this line to load the .hm 
`model = tf.keras.models.load_model('**rustnorust_b/rustnorust_model.h5**'))`

i get this error 
AttributeError                            Traceback (**most recent call last**)
<ipython-input-34-f883c84dfa5e> in <module>
----> 1 model = tf.keras.models.load_model('**rustnorust_b/rustnorust_model.h5**')

~\anaconda3\envs\Corrosion_Detection\lib\site-packages\tensorflow\python\keras\engine\saving.py in load_model(filepath, custom_objects, compile)
    227     if model_config is None:
    228       raise ValueError('**No model found in config file**.')
--> 229     model_config = json.loads(**model_config.decode('utf-8')**)
    230     model = model_from_config(**model_config, custom_objects=custom_objects**)
    231 

AttributeError: '**str**' object has no attribute '**decode**'

I have no idae help give any suggestion

**Comment by sushreebarsa** [comment]
@faisalhazry 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Could you let us know the TF version you are using ? Thank you!

**Comment by faisalhazry** [comment]
> @faisalhazry In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Could you let us know the TF version you are using ? Thank you!

is this code snippet (https://github.com/faisalhazry/Corrosion_Detection/blob/main/rust_det-using-a-pretrained-convnet-VGG16.ipynb) 

i upload the file in my github repository

If i am wrong plz tell me. I am new in this forum and machine learning 
Current the file is running in anaconda python environment python=3.6 tensorflow==1.12.2 and keras==2.2.4

**Comment by faisalhazry** [comment]
> @faisalhazry In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Could you let us know the TF version you are using ? Thank you!

![image](https://user-images.githubusercontent.com/121289405/209328756-1db63506-73de-4891-b0bb-04067e71405c.png)

**Comment by sunny7712** [comment]
@faisalhazry The error is not reproducing with the 2.x version of Tensorflow. I tried to install the 1.x version on Google Colab but it is not longer supported. @sushreebarsa if there's anything you want me to try, please let me know.

**Comment by sushreebarsa** [comment]
@sunny7712 Thank you for your response!
@faisalhazry TF v1.x is no longer actively supported so it is always recommended for upgrading to latest TF version. Please let us know if you still face the issue in TF v2.11.
Thank you!
