### ISSUE TITLE
Callback model attribute value

### ISSUE THREAD

**Issue by khamyl** [keras-team/keras#17376]
The model is None in the callback - throwing errors about None has no method "XXX" defined.

It is not clear whether we need to _set_model()_ when defining the callback, and if we set the model, the callback is working with the model with updated weights, or the original (random) weights set at the beginning.

https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/Callback#attributes
https://www.tensorflow.org/guide/keras/custom_callback#usage_of_selfmodel_attribute

**Comment by tilakrayal** [comment]
@khamyl,
I donot find any issue/error while executing the mentioned document code. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/dbe43fe25c345aa9c35a8a2c39d0b54d/custom_callback.ipynb).

**Comment by khamyl** [comment]
I found out, that you don't have access to the model only if you call the ancestor initialization.
```Python
class MyCallback(Callback):
    def __init__(self, arg_tensorboard_filewriter):
        super().__init__()
```
I spent a few time to found this out - therefore I think, some more information about `set_model()` would be helpful in documentation. Also when the `set_model()` is called, if we omit the ancestor initialization. Also if we override the `set_model()` will it be called - my observation is that it will not - you have to call it explicitly?

**Comment by tilakrayal** [comment]
@khamyl ,
We would prefer a PR for the validation, Could you please feel free to submit a PR for the requested change to be made. Thank you!
