### ISSUE TITLE
Training horizontally stacked layers does not happen in parallel 

### ISSUE THREAD

**Issue by carlosg-m** [keras-team/keras#17378]
When using Keras to build a multiple layer model, by stacking layers horizontally instead of vertically (deep network), training happens sequentially, and adding more layers increases each epoch duration linearly, while GPU utilization and memory usage remains the same as a single layer regardless of the number of total layers.

In the example below I would expect that each sub-network called though the `cnn_example()` function, would run in parallel before the GlobalAveragePooling1D operation is called. However this does not happen, regardless the number of times the layer is repeated. Is this expected behavior or am I missing something?

```
import tensorflow as tf
from tensorflow.keras import layers

input_img= layers.Input(shape=(112, 112, 3))

x = [cnn_example()(input_img) for _ in range(n_repeats)]
x = layers.Lambda(lambda x: tf.stack(x, axis=1))(x)
x = layers.GlobalAveragePooling1D()(x)
x = layers.Dense(1)(x)

model = tf.keras.Model(input_img, x)
```

**Comment by carlosg-m** [comment]
@sushreebarsa, I created a Colab notebook, with a complete reproducible example:
- https://colab.research.google.com/drive/11jtCBrwWqDYbdsuMu04ptRfFXi0sr1EV?usp=sharing

The notebook runs on a GPU with small batch sizes of 32 to keep resource usage low, so when the number of stacked layers increases, there are free resources available to allocate, assuming a quasi-parallel execution. However once again that was not the case:
- 1 model: ~5 seconds epoch
- 2 models: ~10 seconds epoch
- 3 models: ~15 seconds epoch

The same issue open on TensorFlow repository: https://github.com/tensorflow/tensorflow/issues/59049

**Comment by sushreebarsa** [comment]
@SuryanarayanaY I was able to replicate the issue, please find the [gist](https://colab.research.google.com/gist/sushreebarsa/6e97ceadeb6ccf738671d15aa62165dc/copy-of-untitled59.ipynb#scrollTo=CdvsUzEob4aM) here.  Thank you!

**Comment by SuryanarayanaY** [comment]
Hi @carlosg-m ,
We have data parallelism and model parallelism which can be used for parallel training across multiple devices.
AFAIK what you are asking for is model parallelism in which model operations can be divided across multiple devices for parallel training.At present Tensorflow won't have support for model parallelism yet as per source [here](https://www.tensorflow.org/api_docs/python/tf/distribute).

<img width="1215" alt="Screenshot 2023-01-17 at 4 36 05 PM" src="https://user-images.githubusercontent.com/116063290/212898393-12b52c55-ead0-4a17-9475-2bc0bd03ce58.png">

I hope this may clarify your doubt.If still have doubt Please let us know. Thanks!

**Comment by SuryanarayanaY** [comment]
To add more we can convert a GPU into multiple logical devices with using `tf.config.set_logical_device_configuration` API and then train different models on different logical devices.But for same model AFAIK your requirement can be achieved only by using model parallelism technique which not yet supported by Tensorflow.

**Comment by SuryanarayanaY** [comment]
@carlosg-m ,

Apologies for the long delay. As I mentioned earlier right now Tensorflow supports Data parallelism by splitting the data across batches.Layer parallelism comes under Model parallelism which is still under experimental stage and may be implemented soon. Right now Tensorflow supports Data Parallelism i.e Data will be splitted across the accelerators but the same model will be copied across all these devices(each device have same copy of model but different slices of data).

Please refer this official tensorflow video [tutorial](https://www.youtube.com/watch?v=cdNLtMszdLs) for more detail on this concept.
