### ISSUE TITLE
__init__() got an unexpected keyword argument 'reduction'

### ISSUE THREAD

**Issue by yunhao-tech** [keras-team/keras#17371]
**System information**.
- OS Platform and Distribution: Windows 10 
- TensorFlow version: tf 2.7.0 (tf 2.11. still has this issue)
- Python version: 3.8.3

**Describe the problem**.
If we use `metrics=[tf.keras.losses.XXX]` in model construction, there would be a problem when we save and reload the model.

**Current behavior**.
Compile a model with `metrics=[tf.keras.losses.XXX]` does not raise error. The training process seems also good. However, if we save the model and try to reload it, it does not work. Moreover, the error message `__init__() got an unexpected keyword argument 'reduction'` gives no information. 

**Expected behavior**.
Why not raise an error during the training or even during the compiling? That would be much more friendly for new comers.

**Standalone code to reproduce the issue**.

Please find a code gist [here](https://gist.github.com/yunhao-tech/639b8d5262bc164b37cc227240b04ce0) or a Colab [here](https://colab.research.google.com/gist/tiruk007/2dbe0afc37df36d78fd167261dd6c3f6/untitled48.ipynb)

**Relevant log output**.
Traceback (most recent call last):
  File "d:/VScode/M2-SMC/debug.py", line 26, in <module>
    pretrained = tf.keras.models.load_model('saved_model/my_model')
  File "C:\Users\yunhao\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\yunhao\anaconda3\lib\site-packages\keras\engine\base_layer.py", line 784, in from_config
    return cls(**config)
TypeError: __init__() got an unexpected keyword argument 'reduction'

**Comment by deepNeuralNick** [comment]
I can take this issue/feature if there are no available assignees.

**Comment by tilakrayal** [comment]
@yunhao-tech,
I tried to execute the code with an alternative approach and was able to execute without any issue. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/024be080f1d0e2787a03e224476d8ab9/untitled822.ipynb) and also please take a look at this SO [link](https://stackoverflow.com/questions/60530304/loading-custom-model-with-tensorflow-2-1) and the [issue](https://github.com/tensorflow/tensorflow/issues/31850#issuecomment-578566637) for the reference. Thank you!

**Comment by yunhao-tech** [comment]
@tilakrayal Thank you! 
Yes, just by saving the model in `.hdf5` format, it works. It seems that `compile=False` does not play an important role here. 
But I'm still confused why the default saving format is not supported.

**Comment by tilakrayal** [comment]
@yunhao-tech,
 Keras team is coming up with a new format that ends with the **.keras** extension. This works in both keras format `.keras` and saved model `.tf` format. I request you to take a look at this [issue](https://github.com/keras-team/keras/issues/17232) where a similar issue has been proposed and it is still open. Thank you!

**Comment by yunhao-tech** [comment]
Hi @tilakrayal Thanks for your response!
The issue you mentioned talks about the incompatibility of SavedModel across TF versions. 
I tried `model.save('saved_model/my_model', save_format="keras")`, but it has the same pbm when reload the model.
Here, what is strange is that in context of using `metrics=[tf.keras.losses.XXX]` during compile process, to save the model after training: `model.save('saved_model/my_model.hdf5')` works. But `model.save('saved_model/my_model')` fails when model is reloaded.

**Comment by tilakrayal** [comment]
@yunhao-tech,
Sorry for the delay. I tried to execute the given code with the alternative approach where passing a loss model into the metrics argument causes an error. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/26848306d3a970d68855cb79843e5a7e/untitled48.ipynb) and also PR [#2157](https://github.com/tensorflow/docs/pull/2157) was created and merged for a similar request. Thank you!

**Comment by yunhao-tech** [comment]
Thank you!

**Comment by tilakrayal** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
