### ISSUE TITLE
invalid syntax trainer.trainModel()

### ISSUE THREAD

**Issue by faisalhazry** [keras-team/keras#17387]
Help me currently i am doing at Jupyter notebook anaconda **i got invalid syntax when running this code trainer.trainModel()**
currently i am using Python 3.7.6 TenserflowVer: 2.4.0

`from imageai.Detection.Custom import DetectionModelTrainer`

`trainer = DetectionModelTrainer()`
`trainer.setModelTypeAsYOLOv3()`
`trainer.setDataDirectory(data_directory="hololens")`
`trainer.setTrainConfig(object_names_array=["hololens"], batch_size=4, num_experiments=100, train_from_pretrained_model=("pretrained-yolov3.h5")`
`trainer.trainModel()`

![image](https://user-images.githubusercontent.com/121289405/210163822-afa0e084-36a9-48c5-a9da-41856f1d3e6f.png)

**Comment by faisalhazry** [comment]
Currently i am trying to leaning doing this tutorial https://medium.com/deepquestai/train-object-detection-ai-with-6-lines-of-code-6d087063f6ff

**Comment by faisalhazry** [comment]
My bad i add bracket in the code that why syntax error here is the working code

'''
from imageai.Detection.Custom import DetectionModelTrainer

trainer = DetectionModelTrainer()
trainer.setModelTypeAsYOLOv3()
trainer.setDataDirectory(data_directory="hololens")
trainer.setTrainConfig(object_names_array=["hololens"], batch_size=4, 
num_experiments=100, train_from_pretrained_model="pretrained-yolov3.h5")
trainer.trainModel()

'''

**Comment by ShisuiUzumaki** [comment]
> My bad i add bracket in the code that why syntax error here is the working code
> 
> ''' from imageai.Detection.Custom import DetectionModelTrainer
> 
> trainer = DetectionModelTrainer() trainer.setModelTypeAsYOLOv3() trainer.setDataDirectory(data_directory="hololens") trainer.setTrainConfig(object_names_array=["hololens"], batch_size=4, num_experiments=100, train_from_pretrained_model="pretrained-yolov3.h5") trainer.trainModel()
> 
> '''

has the issue been resolved? if so, you can close this issue

**Comment by tilakrayal** [comment]
@faisalhazry,
I was not able to find any Syntax error while executing the mentioned code. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/6dffca6d491e0605398250cb972a29aa/untitled828.ipynb).
