### ISSUE TITLE
`timeseries_dataset_from_array` gives empty output on edge case

### ISSUE THREAD

**Issue by basjacobs93** [keras-team/keras#17392]
**Describe the problem**.

The `keras.utils.timeseries_dataset_from_array` function does not give the correct output when `sampling_rate > 1` and the size of `data`  is exactly big enough to extract 1 dataset.

**Describe the current behavior**.
The result is empty

**Describe the expected behavior**.
The result contains 1 element

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no): yes
- Briefly describe your candidate solution(if contributing): replace `+ 1` with `+ sampling_rate` in https://github.com/keras-team/keras/blob/16bc9f8b4b3cfc4d20f8ad683a8c400dcac5b35e/keras/utils/timeseries_dataset.py#L212.

**Standalone code to reproduce the issue**.
```
from keras.utils import timeseries_dataset_from_array
ds = timeseries_dataset_from_array(
    data=np.arange(99),
    targets=None,
    sequence_length=50,
    sampling_rate=2,
    batch_size=None
)

len([a for a in ds])
```
gives `0` but should give `1` (corresponding to the 50 indices `[0, 2, 4, ..., 96, 98]`)

**Comment by tilakrayal** [comment]
@basjacobs93,
We would prefer a PR for the validation, Could you please feel free to submit a PR for the requested change to be made. Thank you!

**Comment by tilakrayal** [comment]
The pr #17396 has been assigned for reviewing and once it is merged this issue will move to closed status.
