### ISSUE TITLE
Sequential models should let you add multiple layers at once

### ISSUE THREAD

**Issue by DCtheTall** [keras-team/keras#17408]
**Describe the feature and the current behavior/state**.

Right now, `Sequential` only allows you to add one layer at a time via `add`. If you want to add multiple layers, this leads to repetitive code:

```python
model = Sequential()
model.add(LayerFoo())
model.add(LayerBar())
model.add(LayerBaz())
```

It would be nice if `add` allowed you to pass a list or a variadic number of arguments, which would reduce the above code to

```python
...
model.add(LayerFoo(), LayerBar(), LayerBaz())
```

which is less repetitive. The proposed solution is to change `add` to something like

```python
def add(self, *layers):
  for layer in layers:
    # Rest of current implementation...
```

Alternatively something like

```python
def add(self, layer_or_layers):
  if is_sequential_container(layer_or_layers):
    for layer in layer_or_layers:
      self._add_layer(layer):
    return
  else:
    self._add_layer(layer_or_layers)

def _add_layer(self, layer):
  # Current implementation...
```

**Will this change the current api? How?**

Yes, but in a backward-compatible way.

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**

- Do you want to contribute a PR? (yes/no): **yes**
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution (if contributing): **See above**

**Comment by mihirparadkar** [comment]
Hi,

Keras already supports a similar feature where you can pass multiple layers to a `Sequential(...)` in a list. For example
```python
model = Sequential([LayerFoo(), LayerBar(), LayerBaz()])
```

**Comment by sachinprasadhs** [comment]
Here is the toy example to the above comment. 
```
initial_model = keras.Sequential(
    [
        keras.Input(shape=(250, 250, 3)),
        layers.Conv2D(32, 5, strides=2, activation="relu"),
        layers.Conv2D(32, 3, activation="relu"),
        layers.Conv2D(32, 3, activation="relu"),
    ]
)
```

For more details refer the document [here](https://www.tensorflow.org/guide/keras/sequential_model). Thanks!

**Comment by DCtheTall** [comment]
Thanks for the response and examples! However, I think my explanation issue wasn't clear.

I understand that there can be multiple layers added to a Sequential model at construction time, but, since some Sequential models have layers added after their initial construction, I was thinking of adding the capability to add multiple layers in one `add` call _after_ construction time.

**Comment by innat** [comment]
@DCtheTall To use one `add`, it can be done with as follows. Almost same thing you proposed above. 

```python
model = Sequential()
for layer in [LayerFoo(), LayerBar(), LayerBaz()]:
    model.add(layer)
```

**Comment by old-school-kid** [comment]
@DCtheTall 
Adding to what @innat suggested, which is a great pythonic way BTW, you can also create function which has layers staked in them like a resnet block or vgg block and call the function. 
Or a more intuitive way is to create a lambda layer.

**Comment by DCtheTall** [comment]
Thanks, this was more of a question about API shape than the capability to do this at all. But if it's not something the owners of this library are interested in that's ok with me.

**Comment by innat** [comment]
@DCtheTall 
Did you mean this?

**current**

```python
model = keras.Sequential()

for dim in [1, 2, 3, 4, 5, 6]:
    blocks = [
        keras.layers.Dense(dim),
        keras.layers.Dense(dim * 2)
    ]
    
    for block in blocks:
        model.add(block)

model.build((None, 16))
> OK
```

**should also**

```python

model = keras.Sequential()

for dim in [1, 2, 3, 4, 5, 6]:
    model.add(
        [
            keras.layers.Dense(dim),
            keras.layers.Dense(dim * 2)
        ]
    )
model.build((None, 16))

> TypeError: ...
```
