### ISSUE TITLE
`GroupNormalization` layer does not compute broadcast shape correctly for specified axis

### ISSUE THREAD

**Issue by MasterSkepticista** [keras-team/keras#17402]
On TensorFlow v2.11.0-rc2-17-gd5b57ca93e5 2.11.0
(This issue exists in `tf-nightly` as of writing)

**Describe the problem**.
`layers.GroupNormalization` raises an `Exception` on passing a valid non-negative `axis` argument.

**Describe the expected behavior**.
`layers.GroupNormalization(axis=3)` should be a valid argument, 3 being the channel axis for a 4D NHWC input.

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no): **Yes**
- Briefly describe your candidate solution(if contributing): 

The following line computes broadcast shape by inferring the `rank` of the `shape` of `input_shape`, which is already a shape, and will always return `1`. Solution would be to replace `input_shape.shape.rank` with `len(input_shape)` https://github.com/keras-team/keras/blob/50542a234850ebf6128f9c61673fc4cae596ff01/keras/layers/normalization/group_normalization.py#L215 

**Standalone code to reproduce the issue**.
```python
import tensorflow as tf
import tensorflow_addons as tfa

x = tf.random.uniform((4, 7, 7, 64))

# norm_axis=3 fails for keras implementation
# norm_axis=-1 works for both
norm_axis = 3
tfa_norm = tfa.layers.GroupNormalization(groups=32, axis=norm_axis)(x)
keras_norm = tf.keras.layers.GroupNormalization(groups=32, axis=norm_axis)(x)

tf.debugging.assert_near(keras_norm, tfa_norm)
```
**Source code / logs**.
```shell
Traceback (most recent call last):
  File "groupnorm.py", line 7, in <module>
    keras_norm = tf.keras.layers.GroupNormalization(groups=32, axis=norm_axis)(x)
  File "/home/karan/envs/tfgpu/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/karan/envs/tfgpu/lib/python3.8/site-packages/keras/layers/normalization/group_normalization.py", line 217, in _create_broadcast_shape
    broadcast_shape[self.axis] = input_shape[self.axis] // self.groups
IndexError: Exception encountered when calling layer 'group_normalization_1' (type GroupNormalization).

list assignment index out of range

Call arguments received by layer 'group_normalization_1' (type GroupNormalization):
  • inputs=tf.Tensor(shape=(4, 7, 7, 64), dtype=float32)
```

**Comment by sushreebarsa** [comment]
@SuryanarayanaY I was able to replicate the issue on colab, please find [this](https://colab.research.google.com/gist/sushreebarsa/b26f36bca3b24cf0fde57406b8461b27/untitled.ipynb#scrollTo=8OdRL0c0ULUo) gist.
Thank you!

**Comment by old-school-kid** [comment]
Line 216 is `broadcast_shape = [1] * input_shape.shape.rank` where `input_shape` is the shape of input only. @SuryanarayanaY  I think the bug lies there. Could you please look into it?
TUA

**Comment by SuryanarayanaY** [comment]
@MasterSkepticista, @old-school-kid ,
Apologies for delay.There is the bug at the line below.
https://github.com/keras-team/keras/blob/e52370bb58b7325ac90d4bd7e2a6a0d2a73404e8/keras/layers/normalization/group_normalization.py#L215
The solution `broadcast_shape = [1] * len(input_shape)` as proposed by MasterSkepticista works for this.I have tested this and seems working fine. 
@MasterSkepticista If you willing to raise PR for this please confirm and proceed.Otherwise let me know if I can proceed for PR. 
Thanks for contribution.

**Comment by MasterSkepticista** [comment]
I will link a PR to this issue soon.

**Comment by SuryanarayanaY** [comment]
@MasterSkepticista ,

The issue resolved in tf-nightly version and attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/3e4c0fca08bd44c221173f1898263bec/17402_r2.ipynb) for reference. Could we close this issue ?

Thanks!

**Comment by MasterSkepticista** [comment]
I've marked my PR as closed. Closing this issue.
https://github.com/keras-team/keras/pull/17512#issuecomment-1487219125
