### ISSUE TITLE
Updates to pydot dependency in `plot_model`

### ISSUE THREAD

**Issue by rossbar** [keras-team/keras#17416]
The `vis_utils` module includes a cascading set of import statements traversing various forks of `pydot`:

https://github.com/keras-team/keras/blob/db667716ac6be59a8495b58e0d2e246e9c031599/keras/utils/vis_utils.py#L30-L42

At the very least, the comments are misleading, as `pydot-ng` [has been public archive since 2018](https://github.com/pydot/pydot-ng) and [pydotplus hasn't had a release since 2014](https://pypi.org/project/pydotplus/#history). Unfortunately pydot itself also appears not to be very actively maintained, so there is no silver-bullet. Nevertheless it may be worthwhile to consider dropping the unsupported forks assuming there are no backcompat issues - I didn't see anything explicit in the test suite to suggest that was the case.

Longer term, it might be worth considering switching to a better-supported project for Python bindings to Graphviz, e.g. `pygraphviz`[^1], especially since `plot_model` already has the hard requirement that Graphviz itself be installed. That's a larger, separate discussion though!

[^1]: full disclosure: I am a contributor to pygraphviz

**Comment by tilakrayal** [comment]
@rossbar,
We would prefer a PR for the validation, Could you please feel free to submit a PR for the requested change to be made. Thank you!
