### ISSUE TITLE
keras.models.clone_model creates different weight names for RNN layers

### ISSUE THREAD

**Issue by mergian** [keras-team/keras#17433]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS
- TensorFlow installed from (source or binary): PYPI
- TensorFlow version (use command below): v2.11.0-rc2-17-gd5b57ca93e5 2.11.0
- Python version: 3.7.12

**Describe the problem**.

When cloning a Keras RNN model using `keras.models.clone_model(...)` the weight names of the inner RNN cells get incremented instead of being cloned. The problem does not occur when using `save_model(...)` and then `load_model(...)`.

**Describe the current behavior**.

Here an example:
```python
import tensorflow as tf

inputs = tf.keras.Input(batch_shape=[1, 2, 3])
layer = tf.keras.layers.SimpleRNN(units=5)(inputs)
model = tf.keras.Model(inputs, layer)

print("Original:")
for w in model.weights: print(w.name)
print()

cloned = tf.keras.models.clone_model(model)

print("Cloned:")
for w in cloned.weights: print(w.name)
print()

tf.keras.models.save_model(model, 'save')
saved = tf.keras.models.load_model('save')

print("Saved:")
for w in saved.weights: print(w.name)
```

This produces:
```
Original:
simple_rnn/simple_rnn_cell/kernel:0
simple_rnn/simple_rnn_cell/recurrent_kernel:0
simple_rnn/simple_rnn_cell/bias:0

Cloned:
simple_rnn/simple_rnn_cell_1/kernel:0
simple_rnn/simple_rnn_cell_1/recurrent_kernel:0
simple_rnn/simple_rnn_cell_1/bias:0

Saved:
simple_rnn/simple_rnn_cell/kernel:0
simple_rnn/simple_rnn_cell/recurrent_kernel:0
simple_rnn/simple_rnn_cell/bias:0
```

As you can see, the cloned model has `simple_rnn_cell_1` instead as `simple_rnn_cell` as name. When using other layers, i.e., Conv the weight names are correct. The problem occurs with all types of RNN layers (SimpleRNN, LSTM and GRU).

**Describe the expected behavior**.
The names are set correctly ;)

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no): no -> I don't think I know enough of Keras internal to contribute here.
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing): To me it seems the `rnn_cell.name` attribute needs to be put into the RNN's config, so when cloning the model it gets set properly, and not the automatic enumeration method is triggered.

**Comment by rajivhockey97** [comment]
In the model.summary() function's output the names of the layers are the same. The error shows up only when we print the name of the layers.

**Comment by mergian** [comment]
Yes. The reason is, that `model.summary()` shows the name of the `keras.layers.[LSTM,GRU,SimpleRNN]` class. But all of them have a member `cell` that is generating the weights see here: https://github.com/keras-team/keras/blob/master/keras/layers/rnn/lstm.py#L533

And `cell_kwargs` doesn't have a name field, so the names for the cell always get auto-generated.

**Comment by rajivhockey97** [comment]
@mergian  Could you point me to where the cell names get auto generated while using weights.name attribute?

**Comment by mergian** [comment]
Alternativly, the name could always be `name='cell'`, as the name of the parent LSTM/GRU/SimpleRNN is already unique within the model. So it would be `[model_name]/[rnn_name]/cell/[weight_name]`.

**Comment by tilakrayal** [comment]
@gowthamkpr,
I was able to reproduce the issue on tensorflow v2.9, v2.11 and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/f7d1e8848fbe92da7f42b669f54b09c1/untitled_gpu.ipynb).
