### ISSUE TITLE
cannot find reference 'keras in __init__ py __init__ py

### ISSUE THREAD

**Issue by raul-parada** [keras-team/keras#17442]
I have a code for LSTM including transformers.

The error is the following: 
```
Traceback (most recent call last):
  File "C:\UsersLSTM_TL.py", line 12, in <module>
    from tensorflow.keras.layers import Input, Transformer
ImportError: cannot import name 'Transformer' from 'tensorflow.keras.layers' (C:\Users\cttc\anaconda3\envs\testenv\lib\site-packages\keras\api\_v2\keras\layers\__init__.py)
```

The line is:
... 
`model.add(Transformer(num_layers=6, d_model=64, num_heads=8, dff=256, dropout=0.2)) 
`...

In the imports I do have:
```
from tensorflow.keras.layers import Input, Transformer
from tensorflow.keras.models import Model
from tensorflow.keras import optimizers
```

In which the keras part appears with a red underline with the following error: "`cannot find reference 'keras in __init__ py __init__ py`".

I'm running this on:
- Windows 10 64bits
- Anaconda3 2022.10 (Python 3.9.13 64-bit)
- PyCharm 2022.3.1
- Inside Conda Env setup as Python 3.10.4 (previously installed). 
I've installed tensorflow on Administrator Anaconda Prompt with conda install tensorflow (it was successful)

**Comment by rehsan-akturk** [comment]
> @raul-parada, Transformer is now available in **tensorflow.keras.layers**. To use the transformer, Please try to import it as `!pip install transformers`
> 
> ![image](https://user-images.githubusercontent.com/81610181/216325668-d25d4fa1-72bd-4f14-a154-d42f4c4d85f9.png)
> 
> Kindly find the [gist](https://colab.research.google.com/gist/tilakrayal/d751db1e7dd175ccee43fa3d8975d47e/untitled916.ipynb). Also please take a look at this official doc [link](https://keras.io/examples/nlp/text_classification_with_transformer/#text-classification-with-transformer) where we can implement a Transformer block as a Keras layer and use it for text classification. Thank you!
