### ISSUE TITLE
Dividing MNIST image into blocks (without overlapping) and run simple CNN through different blocks. Found 4 input samples and 60000 target samples.

### ISSUE THREAD

**Issue by deepquantum88** [keras-team/keras#17446]
I am trying to run simple CNN o a mnist dataset.  The objective is to divide the image into equal blocks and execute CNN separately on each block. first I resize mnist images into 4by4. Then, split it into 2by2 blocks i.e. equal to 4 equal parts of each image. In the end, run models through 4 parts and concatenate their output. The execution of four models on different blocks will produce a single output(label)of the image jointly. During the fit, it throws an error, ValueError: Input arrays should have the same number of samples as target arrays. Found 4 input samples and 60000 target samples. I checked to reshape. But did not work. During fit, if I remove * from data_train, then it will be a different error. The complete code is given.

import tensorflow as tf
import seaborn as sns
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()

x_train=x_train.reshape(x_train.shape[0], x_train.shape[1], x_train.shape[2], 1)
x_train=x_train / 255.0
x_test = x_test.reshape(x_test.shape[0], x_test.shape[1], x_test.shape[2], 1)
x_test=x_test/255.0

x_train=tf.image.resize(x_train, (4,4))
x_test=tf.image.resize(x_test, (4,4))

#creating blocks..
def blockshaped(arr, nrows, ncols):
    """
    Return an array of shape (n, nrows, ncols) where
    n * nrows * ncols = arr.size

    If arr is a 2D array, the returned array should look like n subblocks with
    each subblock preserving the "physical" layout of arr.
    """
    h, w = arr.shape
    assert h % nrows == 0, f"{h} rows is not evenly divisible by {nrows}"
    assert w % ncols == 0, f"{w} cols is not evenly divisible by {ncols}"
    return (arr.reshape(h//nrows, nrows, -1, ncols)
               .swapaxes(1,2)
               .reshape(-1, nrows, ncols))

x_train=x_train.numpy()
x_test=x_test.numpy()

x_train = [blockshaped(x_train[i,:,:,0],2,2) for i in range(len(x_train))]
x_test = [blockshaped(x_test[i,:,:,0],2,2) for i in range(len(x_test))]

y_train = tf.one_hot(y_train.astype(np.int32), depth=10)
y_test = tf.one_hot(y_test.astype(np.int32), depth=10)

#appending train images in four parts
Data_train=[]
for i in range(4):
    Data_train.append([])
    for j in range(len(x_train)):
        Data_train[i].append(np.ndarray.flatten(x_train[j][i]))
        

Data_test=[]
for i in range(4):
    Data_test.append([])
    for j in range(len(x_test)):
        Data_test[i].append(np.ndarray.flatten(x_test[j][i]))
        
Data_train=np.asarray(Data_train)

Data_train=Data_train.reshape(-1,4, 2,2)

model_input1 = tf.keras.layers.Input(shape=(2,2))
model1 = tf.keras.layers.Dense(64)(model_input1)
model1 = tf.keras.Model(inputs=model_input1, outputs=model1)

model_input2 = tf.keras.layers.Input(shape=(2,2))
model2 = tf.keras.layers.Dense(64)(model_input2)
model2 = tf.keras.Model(inputs=model_input2, outputs=model2)

model_input3 = tf.keras.layers.Input(shape=(2,2))
model3 = tf.keras.layers.Dense(64)(model_input3)
model3 = tf.keras.Model(inputs=model_input3, outputs=model3)

model_input4 = tf.keras.layers.Input(shape=(2,2))
model4 = tf.keras.layers.Dense(64)(model_input4)
model4 = tf.keras.Model(inputs=model_input4, outputs=model4)
 
#kernel_model_list.append(model)
#kernel_model_list_input.append(model.input)
#kernel_model_list_output.append(model.output)
    
#print(kernel_model_list_input[0], kernel_model_list_input[1])

z_input = tf.keras.layers.Concatenate()([model1.output, model2.output, model3.output, model4.output])
z = tf.keras.layers.Dense(32, activation="relu")(z_input)
z = tf.keras.layers.Dense(num_classes, activation='softmax')(z)
final_network_model = tf.keras.Model(inputs=[model1.input, model2.input, model3.input, model4.input], outputs=z)

final_network_model.compile(optimizer=tf.keras.optimizers.RMSprop(epsilon=1e-08), loss='categorical_crossentropy',
                            metrics=['acc'])

history = final_network_model.fit([*Data_train], np.array(y_train),
                    batch_size=batch_size,
                    epochs=epochs)

**Comment by sushreebarsa** [comment]
@deepquantum88 I tried to replicate the provided code and faced a different outcome, could you please check this [gist ](https://colab.research.google.com/gist/sushreebarsa/ecf904ad19051b92109bb66f072b929c/17446.ipynb)and let me know what I am missing here to replicate this issue?
If possible please provide a colab gist or notebook with the standalone code.
Thank you!

**Comment by akshaya-hub** [comment]
hello,i would like work on it can you assign me

**Comment by akshaya-hub** [comment]
@deepquantum88 The error is occurring because you have different number of samples in your input and target arrays. You have 4 input samples (2x2 blocks), but 60000 target samples (full images).

**Comment by deepquantum88** [comment]
@akshaya-hub @sushreebarsa 

I know the error is due to number of samples of x train and y train. But the main thins is that here each x_train or each image is divided as 2by2. So i resize image first into 4by4. Then created it 2by2 parts of each image. Therefore, there will be four parts of each image, which will be processed independently and then concatenated to create an output. the problem at my end still not worked.
