### ISSUE TITLE
keras.layers.Bidirectional is missing argument "states", which is defined for keras.layers.RNN

### ISSUE THREAD

**Issue by mergian** [keras-team/keras#17449]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS
- TensorFlow installed from (source or binary): PYPI
- TensorFlow version (use command below): 2.11.0
- Python version: 3.9

**Describe the problem**.

The `reset_states(self)` method of `keras.layers.Bidirectional` (https://github.com/keras-team/keras/blob/master/keras/layers/rnn/bidirectional.py#L448) is missing the `states` argument, which is defined for `keras.layers.RNN` (https://github.com/keras-team/keras/blob/master/keras/layers/rnn/base_rnn.py#L846).

**Describe the current behavior**.
User cannot pass the states to bidirectional layers using `reset_states()`

**Describe the expected behavior**.
Users should be able to pass states to bidirectional layers ;)

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no): yes
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing):

Something like this:
```python
def reset_states(self, states=None):
   forward_state, backward_state = None, None
   if states is not None:
       assert isinstance(states, (list, tuple))
       cnt = len(states)
       assert cnt % 2 == 0
       cnt = cnt // 2
       forward_state, backward_state = states[:cnt], states[cnt:]
   self.forward_layer.reset_states(forward_state)
   self.backward_layer.reset_states(backward_state)
```

**Comment by tilakrayal** [comment]
@mergian,
Is it possible to provide the reproducible way of code or any test-case which helps us to specify and debug the issue in an effective manner. Thank you!

**Comment by mergian** [comment]
```python
import tensorflow as tf
import numpy as np

inp = tf.keras.Input(batch_shape=[1, 2, 3])

def run(layer):
    model = tf.keras.Model(inp, layer(inp))
    model.summary()
    new_states = np.random.rand(1, 3).astype(np.float32)
    for l in model.layers:
        if hasattr(l, 'reset_states'):
            l.reset_states(new_states)

run(tf.keras.layers.SimpleRNN(units=3, stateful=True))
run(tf.keras.layers.Bidirectional(tf.keras.layers.SimpleRNN(units=3, stateful=True)))
```

It will fail with `TypeError: Bidirectional.reset_states() takes 1 positional argument but 2 were given` when using the Bidirectional.

**Comment by tilakrayal** [comment]
The related pr #17469 has been assigned for reviewing and once it is merged this issue will move to closed status. Thank you!

**Comment by mergian** [comment]
Not sure which comments I should respond to. There are no open requests and the PR is ready to be pulled. 🤔
