### ISSUE TITLE
`amsgrad=True` of Adam optimizer causes InvalidArgumentError on TPU

### ISSUE THREAD

**Issue by innat** [keras-team/keras#17456]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): 2.9
- Python version:
- Bazel version (if compiling from source):
- GPU model and memory:
- Exact command to reproduce:

**Describe the problem**.

LINK https://keras.io/api/optimizers/adam/

Adam optimizer has a parameter called `amsgrad` (False by default). To set it True on TPU causes error.

> InvalidArgumentError: 9 root error(s) found.
  (0) INVALID_ARGUMENT: {{function_node __inference_train_function_28127}} Detected unsupported operations when trying to compile graph while/cluster_while_body_26756_3584483334958204301[] on XLA_TPU_JIT: ResourceApplyAdamWithAmsgrad (No registered 'ResourceApplyAdamWithAmsgrad' OpKernel for XLA_TPU_JIT devices compatible with node {{function_node while_body_26756}}{{node while/Adam/Adam/update/ResourceApplyAdamWithAmsgrad}}){{function_node while_body_26756}}{{node while/Adam/Adam/update/ResourceApplyAdamWithAmsgrad}}
One approach is to outside compile the unsupported ops to run on CPUs by enabling soft placement `tf.config.set_soft_device_placement(True)`. This has a potential performance penalty.

>	 [[TPUReplicate/_compile/_8786033626483313669/_4]]
  (1) INVALID_ARGUMENT: {{function_node __inference_train_function_28127}} Detected unsupported operations when trying to compile graph while/cluster_while_body_26756_3584483334958204301[] on XLA_TPU_JIT: ResourceApplyAdamWithAmsgrad (No registered 'ResourceApplyAdamWithAmsgrad' OpKernel for XLA_TPU_JIT devices compatible with node {{function_node while_body_26756}}{{node while/Adam/Adam/update/ResourceApplyAdamWithAmsgrad}}){{function_node while_body_26756}}{{node while/Adam/Adam/update/ResourceApplyAdamWithAmsgrad}}
One approach is to outside compile the unsupported ops to run on CPUs by enabling soft placement `tf.config.set_soft_device_placement(True)`. This has a potential performance penalty.

>	 [[TPUReplicate/_compile/_8786033626483313669/_4]]
	 [[while/body/_1/while/strided_slice_8/_285]]
  (2) INVALID_ARGUMENT: {{function_node __inference_train_function_28127}} Detected unsupported operations when trying to compile graph while/cluster_while_body_26756_3584483334958204301[] on XLA_TPU_JIT: ResourceApplyAdamWithAmsgrad (No registered 'ResourceApplyAdamWithAmsgrad' OpKernel for XLA_TPU_JIT devices compatible with node {{function_node while_body_26756}}{{node while/Adam/Adam/update/ResourceApplyAdamWithAmsgrad}}){{function_node while_body_26756}}{{node while/Adam/Adam/update/ResourceApplyAdamWithAmsgrad}}
One approach is to outside compile the unsupported ops to run on CPUs by enabling soft placement `tf.config.set_soft_device_placement(True)`. This has a potential performance penalty.

> [[TPUReplicate/_compile/_8786033626483313669/_4]]
	 [[while/body/_1/while/strided_slice_3/_273]]
  (3) INVALID_ARGUMENT: {{function_node __inference_train_function_28127}} Detected unsupported operations when trying to compile graph while/cluster_while_body_26756_3584483334958204301[] on XLA_TPU_JIT: ResourceApplyAdamWithAmsgrad (No registered 'ResourceApplyAdamWithAmsgrad' OpKernel for XLA_TPU_JIT devices compatible with node {{function_node while_body_26756}}{{node while/Adam/Adam/update/ResourceApplyAdamWithAmsgrad}}){{function_node while_body_26756}}{{node while/Adam/Adam/update/ResourceApplyAdamWithAmsgrad}}
One approach is to outside compile the unsupported ops to run on CPUs by enabling soft placement `tf.config.set_soft_device_placement(True)`. This h ... [truncated]

- Do you want to contribute a PR? (yes/no):
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**.

[Gist.
](https://colab.research.google.com/drive/1oAQf9gXTsd9P0_j_zpraOeq-zkIpjTUq?usp=sharing)

**Comment by SuryanarayanaY** [comment]
Hi @innat ,
I replicated the reported behaviour with TF 2.9 version as per attached gist [here](https://colab.sandbox.google.com/gist/SuryanarayanaY/d608ebf7392fb759675021eee4a314a7/git_17456_2-9-2.ipynb). 
I have tried the same code in TF2.11V and tf-nightly versions and both executed without error and training also completed successfully.Please refer to attached gists [2.11v](https://colab.sandbox.google.com/gist/SuryanarayanaY/68cda89f6f4fc154a63ae426b07ebdf5/17456_2-11v.ipynb) and [tf-nightly](https://colab.sandbox.google.com/gist/SuryanarayanaY/ab659ea1f1de9e17fd6244a3986191a7/17456_nightly-2-12v.ipynb).Could you please check and confirm with TF2.11v and tf-nightly and if the code works fine then we can consider it as resolved.

Thanks!

**Comment by innat** [comment]
From your gist, it looks like it is fixed in TF 2.11. Could you please let me know the PR that solves this issue. I like to try to adopt it for < TF 2.11.

**Comment by SuryanarayanaY** [comment]
@innat ,
Unfortunately Iam not sure which commit fixed this or it internal fix.May update here if I get details.As the issue resolved with latest versions shall we consider it closed ? Thanks!
