### ISSUE TITLE
Found a possible security concern

### ISSUE THREAD

**Issue by benharvie** [keras-team/keras#17459]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@blueudp) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by sachinprasadhs** [comment]
Hi @benharvie, Thanks for reporting the issue. 
Since Tensorflow uses Keras as high level API, you can refer the security policies mentioned in the Tensorflow repo here https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md to report any  security vulnerabilities. Thanks!

**Comment by psmoros** [comment]
Hey @sachinprasadhs ! I work with ben, will do! Feel free to close this issue :)
