### ISSUE TITLE
keras.layers.Bidirectional constructor ignores trainable argument, causing models with trainable=False layers to incorrectly be cloned

### ISSUE THREAD

**Issue by mergian** [keras-team/keras#17466]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS
- TensorFlow installed from (source or binary): PYPI
- TensorFlow version (use command below): 2.11.0
- Python version: 3.7

**Describe the problem**.

`keras.layers.Bidirectional` ignore the `trainable` argument, therefore cloning a model with Bidirectional layers, where the layer has been set to `trainable=False` will be cloned with `trainable` set to `True`.

**Describe the current behavior**.
The `trainable` property is set always to `True`.

**Describe the expected behavior**.
The `trainable` property should be set correctly.

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no): yes
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing):

Change `trainable = True` to `trainable = kwargs.get('trainable', True)` in https://github.com/keras-team/keras/blob/master/keras/layers/rnn/bidirectional.py#L178

**Standalone code to reproduce the issue**.

```python
import tensorflow as tf

inp = tf.keras.Input([None, 3])
rnn = tf.keras.layers.SimpleRNN(units=3)
bid = tf.keras.layers.Bidirectional(rnn)
model = tf.keras.Model(inp, bid(inp))

model.summary()

clone_trainable = tf.keras.models.clone_model(model)
assert clone_trainable.get_config() == model.get_config()

bid.trainable = False
clone_untrainable = tf.keras.models.clone_model(model)
assert clone_untrainable.get_config() == model.get_config()
```

**Comment by tilakrayal** [comment]
@mergian,
The pr #17467  has been assigned for reviewing and once it is merged this issue will move to closed status. Thank you!
