### ISSUE TITLE
Keras generates non-unique names for stateful LSTM's states

### ISSUE THREAD

**Issue by mergian** [keras-team/keras#17477]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS
- TensorFlow installed from (source or binary): PYPI
- TensorFlow version (use command below): 2.11.0
- Python version: 3.7

**Describe the problem**.
A stateful LSTM has 2 state values, both with the identical name. As you can see in the reproducing example, we have two different variables, but both have the identical name.

**Describe the current behavior**.
LSTM states have the identical name.

**Describe the expected behavior**.
LSTM states should have unique names.

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no): yes
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing):

I think the problem comes from here:
https://github.com/keras-team/keras/blob/master/keras/layers/rnn/base_rnn.py#L909

1. I would do something like `lambda x: backend.variable(x, name='state')`. This will change the name to `lstm/state:0` which is already more readable.
2. To me it seems it's not possible to give `tf.Variable` a unique id, so I assume the naming would need to be done manually with something like `lambda x: backend.varaible(x, name=f'state_{unique_id}'`.

**Standalone code to reproduce the issue**.

```python
import tensorflow as tf
import tensorflow.keras as keras
import numpy as np

inp = keras.Input(batch_shape=[1, 2, 3])
rnn = keras.layers.LSTM(stateful=True, units=3)
model = keras.Model(inp, rnn(inp))

print('Before:')
print(*rnn.states, sep='\n')
print()

data = np.random.rand(1, 2, 3).astype(np.float32)
model(data)

print('After:')
print(*rnn.states, sep='\n')
```

Output:
```
Before:
<tf.Variable 'lstm/Variable:0' shape=(1, 3) dtype=float32, numpy=array([[0., 0., 0.]], dtype=float32)>
<tf.Variable 'lstm/Variable:0' shape=(1, 3) dtype=float32, numpy=array([[0., 0., 0.]], dtype=float32)>

After:
<tf.Variable 'lstm/Variable:0' shape=(1, 3) dtype=float32, numpy=array([[ 0.11526701, -0.02300704, -0.1668661 ]], dtype=float32)>
<tf.Variable 'lstm/Variable:0' shape=(1, 3) dtype=float32, numpy=array([[ 0.17723909, -0.06333476, -0.31777197]], dtype=float32)>
```

**Comment by sushreebarsa** [comment]
@mergian Sorry for the late response! I was able to replicate this issue on colab, please find the [gist](https://colab.research.google.com/gist/sushreebarsa/5cd4b87c5e7a757876e073aae30b7aae/17477.ipynb) here.
Thank you!

**Comment by SuryanarayanaY** [comment]
@mergian ,

I have checked the Source code of LSTM and observed that the all LSTM layer attributes except `states` not defined as @property. Not sure though the exact reason for this and how it may affect this case. If you have time please have a look and see whether it provides any insight. I just checked implementing this makes any difference and found no difference. Escalating the issue for further investigation. Thanks!

**Comment by sampathweb** [comment]
Thanks for the issue.  Would you be able to contribute with a PR?

**Comment by SuryanarayanaY** [comment]
@mergian , Thanks for the PR.

**Comment by SuryanarayanaY** [comment]
Hello, Thank you for reporting an issue.

We're currently in the process of migrating the new Keras 3 code base from keras-team/keras-core to keras-team/keras.
Consequently, This issue may not be relevant to the Keras 3 code base . After the migration is successfully completed, feel free to reopen this Issue at keras-team/keras if you believe it remains relevant to the Keras 3 code base. If instead this Issue is a bug or security issue in legacy tf.keras, you can instead report a new issue at [keras-team/tf-keras](https://github.com/keras-team/tf-keras/issues), which hosts the TensorFlow-only, legacy version of Keras.

To know more about Keras 3, please read https://keras.io/keras_core/announcement/
