### ISSUE TITLE
InvalidArgumentError: Value for attr 'dtype' of bfloat16 is not in the list of allowed values: uint8, int32, int64, half, float, double

### ISSUE THREAD

**Issue by innat** [keras-team/keras#17508]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): 2.4.1 
- Python version:
- Bazel version (if compiling from source):
- GPU model and memory:
- Exact command to reproduce:

**Describe the problem**.

With **mixed precisoin** technique in TPU, the following random agumentation layers from keras raised errorr. 

```
InvalidArgumentError: Value for attr 'dtype' of bfloat16 is not in the list of allowed values: uint8, int32, int64, half, float, double
```

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no):
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**.

```python
from tensorflow.keras.layers import RandomZoom
from tensorflow.keras.layers import RandomRotation
from tensorflow.keras.layers import RandomCrop

resolver = tf.distribute.cluster_resolver.TPUClusterResolver(tpu='')
tf.config.experimental_connect_to_cluster(resolver)
tf.tpu.experimental.initialize_tpu_system(resolver)
strategy = tf.distribute.TPUStrategy(resolver)
keras.mixed_precision.set_global_policy("mixed_bfloat16") 

# Some data in batch 
# Pass to Random*
```

**Source code / logs**.

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by johnsnow9964** [comment]
can we use `float32` instead of `bfloat16` in keras.mixed_precision.set_global_policy("mixed_bfloat16") ?

**Comment by innat** [comment]
Why I would do that if I want to enable mixed precision in TPU?

**Comment by johnsnow9964** [comment]
> Why I would do that if I want to enable mixed precision in TPU?

you're right. in that case can we try converting data before and after passing it to the data augmentation layers?

**Comment by innat** [comment]
> > Why I would do that if I want to enable mixed precision in TPU?
> 
> you're right. in that case can we try converting data before and after passing it to the data augmentation layers?

IMO, not a good design, this should be supported by the API.

**Comment by SuryanarayanaY** [comment]
Hi @innat ,

Since you mentioned TF version 2.4.1v, Can you confirm whether the error persists in latest versions ? I tried the code snippet with TF2.11v and there is no such error arises.Please refer to attached [gist-2.11v](https://colab.sandbox.google.com/gist/SuryanarayanaY/51af5336791cb9333f5f110efef77d54/17508_2-11-tpu.ipynb#scrollTo=j--iQAp3gcEE). I tried with TF2.4.1 but it seems the path is not correct as per[ gist-2.4.1 ](https://colab.sandbox.google.com/gist/SuryanarayanaY/a6f5d126df9318eb1b26aecfe38ffc89/17508_2-4-1v-tpu.ipynb)and hence not exactly replicated the reported behaviour.

However since 2.4.1 version is not actively supported and also there seems no problem with TF2.11v there is very little chance(almost nill) that this will be cherry picked for 2.4.1. So my request you to please confirm whether the reported issue persists in latest versions ?

**Comment by innat** [comment]
@SuryanarayanaY Thanks for the response. 
I tried to start TPU on colab but each time it shows me **No backend with TPU available.**. However, I could test the code on kaggle TPU but it still provides TF 2.4.1. Here is the [gist](https://colab.research.google.com/drive/12_tdXYlP_HJYdufevWizBK7ZpOCwaliZ?usp=sharing) that I ran on TPU (TF 2.4.1).

**Comment by SuryanarayanaY** [comment]
Hi @innat ,

Thanks for confirmation and the repro code.I tested the code with tf2.4.1 version I couldn't found any such error in my [gist](https://colab.research.google.com/gist/SuryanarayanaY/bec924ea95e5ee6bcc1ff0fac6679ad8/17508_tf2-4-1v-tpu-r1.ipynb).

I have also tested the code with TF2.11v and code executes fine without error.Please refer to attached [gist-tf2.11v](https://colab.research.google.com/gist/SuryanarayanaY/16e3a974fb230aaf352e1090e6dc73aa/17508_tf2-11v-tpu-r1.ipynb).

Whether this code snippet enough to replicate the error ? If so then it is probably resolved already as my colab gist is success in running the code without error.Not sure of Kaggle environment though.Could you please check and confirm ?

Thank you!

**Comment by innat** [comment]
@SuryanarayanaY Thanks for checking. In your gist, the code is incomplete, that's why you didn't face the reported error. I'm placing the full code here. 

```python
from packaging.version import parse
import tensorflow as tf
from tensorflow import keras

resolver = tf.distribute.cluster_resolver.TPUClusterResolver(tpu='')
tf.config.experimental_connect_to_cluster(resolver)
tf.tpu.experimental.initialize_tpu_system(resolver)
strategy = tf.distribute.TPUStrategy(resolver)
print("All devices: ", tf.config.list_logical_devices('TPU'))
tf.keras.mixed_precision.set_global_policy("mixed_bfloat16")
tf.__version__

if parse(tf.__version__) < parse('2.6.2'):
    from tensorflow.keras.layers.experimental.preprocessing import Resizing
    from tensorflow.keras.layers.experimental.preprocessing import RandomFlip
    from tensorflow.keras.layers.experimental.preprocessing import RandomZoom
    from tensorflow.keras.layers.experimental.preprocessing import RandomRotation
else:
    from tensorflow.keras.layers import Resizing
    from tensorflow.keras.layers import RandomFlip
    from tensorflow.keras.layers import RandomZoom
    from tensorflow.keras.layers import RandomRotation

INP_SIZE = 224

# Preprocessing
data_preprocessing = keras.Sequential(
    [
        Resizing(
            *[INP_SIZE] * 2, 
            interpolation="bilinear"
        ),
    ], 
    name='PreprocessingLayers'
)

# Augmentation
data_augmentations = keras.Sequential(
    [
        RandomFlip("horizontal"),
        # Doesn't work on TPU with mixed precision (TF 2.4.1)
        # ticket: https://github.com/keras-team/keras/issues/17508
        RandomZoom(0.2, fill_mode='reflect'),
        RandomRotation(0.1, fill_mode='reflect'),
    ],
    name='AugmentationLayers'
)
```
```python
# Define Sequential model with 3 layers
model = keras.Sequential(
    [
        keras.layers.InputLayer(input_shape=tuple([INP_SIZE] * 2) + (3,)),
        data_preprocessing,
        data_augmentations,
        keras.applications.EfficientNetB0(include_top=False, pooling='avg')
    ]
)
# Call model on a test input
x = tf.ones((1, INP_SIZE, INP_SIZE, 3))
y = model(x)
y.shape
```

**Comment by SuryanarayanaY** [comment]
Hi @innat ,
Iam getting different error as below and also refer attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/33af9a99b9009a8a51ee6e70393cd95e/17508_tf2-4-1v-tpu-r2.ipynb).Could you please provide exact code snippet to replicate the reported behaviour.
`NotImplementedError: Cannot convert a symbolic Tensor (AugmentationLayers/random_zoom/zoom_matrix/strided_slice:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported`

**Comment by innat** [comment]
@SuryanarayanaY 

Sorry for the inconvenience. The model build should be as follows. Please re-check.

```python
with strategy.scope():
    model = ...
```

**Comment by innat** [comment]
@SuryanarayanaY 
I've run the [gist](https://colab.research.google.com/drive/12_tdXYlP_HJYdufevWizBK7ZpOCwaliZ?usp=sharing) on colab (with tf 2.11 on TPU). The error is reported. Please check

**Comment by SuryanarayanaY** [comment]
Hi @innat ,

It seems `tf.random_zoom` is not supported on TPU which is the reason for the error.Please refer to [source](https://cloud.google.com/tpu/docs/tensorflow-ops) for list of Tensorflow Ops that supported on TPU. `tf.random_zoom` is not in the list.

**Comment by innat** [comment]
Thanks for the hint. I didn't check all [random_*](https://keras.io/api/layers/preprocessing_layers/image_augmentation/). 

(shallow cmt), I think there is not api like `tf.random_zoom`, but it's [contructed](https://github.com/keras-team/keras/blob/e6784e4302c7b8cd116b74a784f4b78d60e83c26/keras/layers/preprocessing/image_preprocessing.py#L1304). WDYT?

**Comment by innat** [comment]
.

**Comment by SuryanarayanaY** [comment]
Hi @innat ,

Sorry for being not specific.Most of the Image augmentation layers one way or other uses Ops from `tf.image` module or other TF ops internally. If these Ops were not supported on TPU then the layer also likely to fail on TPU. I haven't specified complete path earlier but nevertheless there is no Op `random_zoom` even in `tf.image` module but it is a Constructed Layer only that not supported on TPU.

As per the source attached above [comment-1446771123](https://github.com/keras-team/keras/issues/17508#issuecomment-1446771123) None of the layers of  tf.keras.layers.Random* included in the TPU supported layers.

**Comment by innat** [comment]
@SuryanarayanaY , Actually these augmentaiton layers works on TPU without any issue until the mixed precisoin (`bfloat16`) is enabled. So, these ops are supported on TPU but not with mixed precisoin. WDYT?

**Comment by rchao** [comment]
Cc'ing @reedwm - Reed do you have a suggestion how to move forward with this?
