### ISSUE TITLE
BackupAndRestore checkpoint fails to account for datasets that have undefined steps_per_epoch (from generator)

### ISSUE THREAD

**Issue by lschlieder** [keras-team/keras#17520]
The BackupAndRestore Callback fails to reinitialize training with : 

  File "/miniconda3/envs/tf/lib/python3.9/site-packages/keras/distribute/worker_training_state.py", line 189, in maybe_load_initial_counters_from_ckpt
    if batch == steps_per_epoch - 1:
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'

This is due to my dataset having no max number, since i create it with a tf.dataset.from_generator() call. 

If this is expected/wanted behaviour, the documentation needs to be updated, or the code in "maybe_load_initial_counters_from_ckpt" needs to handle "None" as a parameter for "steps_per_epoch"

**Comment by sushreebarsa** [comment]
@lschlieder Thanks for reporting an issue!
Could you please elaborate on the issue and provide standalone code to replicate this?

**Comment by sushreebarsa** [comment]
@lschlieder Thanks for reporting an issue!
Could you please elaborate on the issue and provide standalone code to replicate this?

**Comment by lschlieder** [comment]
Sure. Here is some standalone code to replicate this issue.


```
 import tensorflow as tf


def generator_fn():
    while True:
        yield [42], [42]

dataset = tf.data.Dataset.from_generator(generator_fn, output_signature=(
    tf.TensorSpec(shape = (1), dtype = tf.int32),
    tf.TensorSpec(shape = (1), dtype = tf.int32)
)).batch(10)

model = tf.keras.Sequential(
    [
        tf.keras.layers.Dense(1)
    ]
)

optimizer = tf.keras.optimizers.Adam(0.01)
loss = tf.keras.losses.mse
model.compile(optimizer, loss)


callback = tf.keras.callbacks.BackupAndRestore("./", save_freq = 5)
model.fit(dataset, callbacks= [callback])
```

When restarted this gives the error:

`  
File "/home/me/miniconda3/envs/tf/lib/python3.9/site-packages/keras/distribute/worker_training_state.py", line 189, in maybe_load_initial_counters_from_ckpt
    if batch == steps_per_epoch - 1:
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
`


This is solved by giving dataset length explicitly into the fit function with 
`model.fit(dataset, callbacks= [callback], steps_per_epoch= 100000)`
, but since it is possible to start without "steps_per_epoch" in the above example, i would suggest that the "maybe_load_initial_counters_from_ckpt" function handles none types for steps_per_epoch better, or gives a more insightfull exception.

**Comment by sushreebarsa** [comment]
@SuryanarayanaY I tried to replicate this issue on colab using TF v2.10 and 2.11, please find the attached gists. The cell is running for a longer time and showing the output as below;
![A5Nx5MLNGgGPbEu](https://user-images.githubusercontent.com/84765720/217297066-5bbf1248-b5c6-4e08-8c17-c157f2cc238a.png)


Thank you!

**Comment by SuryanarayanaY** [comment]
Hi @lschlieder ,Thanks for reporting this issue.

I have replicated the reported behaviour with TF 2.10v.Please refer to attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/ba8aa12ec921bc7fef4672f565eacdfe/17520.ipynb).

Please refer the snapshot below highlighting the  documentation of model.fit() args:  

<img width="1495" alt="Screenshot 2023-02-10 at 2 28 02 PM" src="https://user-images.githubusercontent.com/116063290/218053113-32d79908-871d-45d0-a64e-c9d5162724a4.png">

Since your generator function is Infinite the `steps_per_epoch` argument must be specified.Could you please confirm whether this documentation is adequate or not ? 

Thanks!

**Comment by lschlieder** [comment]
> Hi @lschlieder ,Thanks for reporting this issue.
> 
> I have replicated the reported behaviour with TF 2.10v.Please refer to attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/ba8aa12ec921bc7fef4672f565eacdfe/17520.ipynb).
> 
> Please refer the snapshot below highlighting the documentation of model.fit() args:
> 
> <img alt="Screenshot 2023-02-10 at 2 28 02 PM" width="1495" src="https://user-images.githubusercontent.com/116063290/218053113-32d79908-871d-45d0-a64e-c9d5162724a4.png">
> 
> Since your generator function is Infinite the `steps_per_epoch` argument must be specified.Could you please confirm whether this documentation is adequate or not ?
> 
> Thanks!

Yep, that works.
