### ISSUE TITLE
`tf.name_scope` is ignored when constructing a model using the functional API

### ISSUE THREAD

**Issue by slanzmich** [keras-team/keras#17538]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.11.

## Problem description

When constructing a Keras model using the functional API, the current `tf.name_scope` is ignored. The internal API [`tf.keras.__internal__.apply_name_scope_on_model_declaration`](https://github.com/keras-team/keras/blob/v2.11.0/keras/engine/base_layer.py#L3655-L3681) is supposed to change the behavior, but does not work as documented.

Consider the following example:
```python
import tensorflow as tf

inputs = tf.keras.Input(shape=[2])
with tf.name_scope('MyScope'):
    outputs = tf.keras.layers.Dense(10, name='MyDense')(inputs)
model = tf.keras.Model(inputs, outputs)

for layer in model.layers:
    print("layer:", layer.name)
for w in model.weights:
    print("weight:", w.name)
```
The output is
```
layer: input_1
layer: MyDense
weight: MyDense/kernel:0
weight: MyDense/bias:0
```
meaning that `tf.name_scope` is ignored, which may or may not be expected by the user. Adding
```python
tf.keras.__internal__.apply_name_scope_on_model_declaration(True)
```
to the snippet above does not change the output.

## Partial solution

For the naming of the weights variables, this can be addressed by replacing
```python
            with backend.name_scope(self._name_scope()):
                with autocast_variable.enable_auto_cast_variables(
                    self._compute_dtype_object
                ):
                    # Build layer if applicable (if the `build` method has been
                    # overridden).
```
with
```python
            with backend.name_scope(self._get_unnested_name_scope()):
                with autocast_variable.enable_auto_cast_variables(
                    self._compute_dtype_object
                ):
                    # Build layer if applicable (if the `build` method has been
                    # overridden).
```
in [`Layer._infer_output_signature`](https://github.com/keras-team/keras/blob/v2.11.0/keras/engine/base_layer.py#L2431). The output changes to
```
layer: input_1
layer: MyDense
weight: MyScope/MyDense/kernel:0
weight: MyScope/MyDense/bias:0
```
However, the docstring of `tf.keras.__internal__.apply_name_scope_on_model_declaration` suggests that the `tf.name_scope` should also affect layer names, which I think is not unreasonable to expect:
```python
    # with `tf.keras.__internal__.apply_name_scope_on_model_declaration(True)`,
    # The name of the dense layer is "model/MyScope/MyDense/*", and without,
    # "model/MyDense/*"
```

## Proposed change

In order to make use of the current `tf.name_scope` also for the layer names, one could bake the name scope into `self._name` in `Layer._init_set_name` and check the use of `self._name` in all the eager / non-eager code paths, and make this dependent on whether `tf.keras.__internal__.apply_name_scope_on_model_declaration` has been called.

If this has a chance to get accepted, I'd be happy to prepare a PR.

This has also been discussed in tensorflow/tensorflow#27298.

**Comment by tilakrayal** [comment]
@slanzmich,
Could you please feel free to submit a PR for the requested change to be made. Thank you!

**Comment by Harrypotterrrr** [comment]
Please refer to https://github.com/tensorflow/tensorflow/issues/27298#issuecomment-1535540544
