### ISSUE TITLE
AttributeError: module 'inspect' has no attribute 'ArgSpec'

### ISSUE THREAD

**Issue by igbw** [keras-team/keras#17541]
Linux Ubuntu 23.04
TensorFlow installed from binary
TensorFlow version 2.13.0
Python version 3.11
Bazel version 5.3.0
GPU model and memory:  GTX1070  8Gb
Exact command to reproduce:
 **import tensorflow as tf**

2023-02-08 17:07:56.487922: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-02-08 17:07:56.520483: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE3 SSE4.1 SSE4.2 AVX AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[1], line 1
----> 1 import tensorflow as tf
      2 #print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

File ~/.local/lib/python3.11/site-packages/tensorflow/__init__.py:476
    474 if hasattr(_current_module, "keras"):
    475   try:
--> 476     _keras._load()
    477   except ImportError:
    478     pass

File ~/.local/lib/python3.11/site-packages/tensorflow/python/util/lazy_loader.py:41, in LazyLoader._load(self)
     39 """Load the module and insert it into the parent's globals."""
     40 # Import the target module and insert it into the parent's namespace
---> 41 module = importlib.import_module(self.__name__)
     42 self._parent_module_globals[self._local_name] = module
     44 # Emit a warning if one was specified

File /usr/lib/python3.11/importlib/__init__.py:126, in import_module(name, package)
    124             break
    125         level += 1
--> 126 return _bootstrap._gcd_import(name[level:], package, level)

File ~/.local/lib/python3.11/site-packages/keras/__init__.py:21
     15 """Implementation of the Keras API, the high-level API of TensorFlow.
     16 
     17 Detailed documentation and user guides are available at
     18 [keras.io](https://keras.io/).
     19 """
     20 from keras import distribute
---> 21 from keras import models
     22 from keras.engine.input_layer import Input
     23 from keras.engine.sequential import Sequential

File ~/.local/lib/python3.11/site-packages/keras/models/__init__.py:18
      1 # Copyright 2022 The TensorFlow Authors. All Rights Reserved.
      2 #
      3 # Licensed under the Apache License, Version 2.0 (the "License");
   (...)
     13 # limitations under the License.
     14 # ==============================================================================
     15 """Keras models API."""
---> 18 from keras.engine.functional import Functional
     19 from keras.engine.sequential import Sequential
     20 from keras.engine.training import Model

File ~/.local/lib/python3.11/site-packages/keras/engine/functional.py:26
     22 import warnings
     24 import tensorflow.compat.v2 as tf
---> 26 from keras import backend
     27 from keras.dtensor import layout_map as layout_map_lib
     28 from keras.engine import base_layer

File ~/.local/lib/python3.11/site-packages/keras/backend.py:34
     32 from keras import backend_config
     33 from keras.distribute import distribute_coordinator_utils as dc
---> 34 from keras.engine import keras_tensor
     35 from keras.utils import control_flow_util
     36 from keras.utils import object_identity

File ~/.local/lib/python3.11/site-packages/keras/engine/keras_tensor.py:19
     15 """Keras Input Tensor used to track functional API Topology."""
     17 import tensorflow.compat.v2 as tf
---> 19 from keras.utils import object_identity
     21 # isort: off
     22 from tensorflow.python.data.util import structure

File ~/.local/lib/python3.11/site-packages/keras/utils/__init__.py:17
      1 # Copyright 2022 The TensorFlow Authors. All Rights Reserved.
      2 #
      3 # Licensed under the Apache License, Version 2.0 (the "License");
   (...)
     13 # limitations under the License.
     14 # ==============================================================================
     15 """Public Keras utilities."""
---> 17 from keras.saving.legacy.serialization import deserialize_keras_object
     18 from keras.saving.legacy.serialization import serialize_keras_object
     20 # Serialization related

File ~/.local/lib/python3.11/site-packages/keras/saving/legacy/serialization.py:24
     21 import tensorflow.compat.v2 as tf
     23 from keras.utils import tf_contextlib
---> 24 from keras.utils import tf_inspect
     26 # isort: off
     27 from tensorflow.python.util.tf_export import keras_export

File ~/.local/lib/python3.11/site-packages/keras/utils/tf_inspect.py:22
     18 import inspect as _inspect
     20 import tensorflow.compat.v2 as tf
---> 22 ArgSpec = _inspect.ArgSpec
     25 if hasattr(_inspect, "FullArgSpec"):
     26     FullArgSpec = _inspect.FullArgSpec

**AttributeError: module 'inspect' has no attribute 'ArgSpec'**

**Comment by tilakrayal** [comment]
@igbw,
Currently Python 3.11 isn't fully supported in TensorFlow yet, including testing in CI and publishing wheels to PyPI.

Python 3.11 is currently in Release Candidate state and will be released in about two weeks. Major packages like NumPy, Pandas, SciPy and Matplotlib have already uploaded their Python 3.11 wheels to PyPI.

#https://github.com/tensorflow/tensorflow/issues/58032 For similar feature there is an open issue where developers are working on the same. I request to follow the similar feature which has been proposed to have the updates on the similar issue. Thank you!
