### ISSUE TITLE
ModelCheckpoint cannot use save_weights_only on a GCS location

### ISSUE THREAD

**Issue by EdwardCuiPeacock** [keras-team/keras#17549]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Cloud Vertex AI Training (Linux)
- TensorFlow installed from (source or binary): binary through pip
- TensorFlow version (use command below): 2.9.1
- Python version: 3.9.13
- Bazel version (if compiling from source):
- GPU model and memory: CPU only
- Exact command to reproduce: See below

**Describe the problem**.

I am training a model on Google Vertex AI training using Keras. When saving model checkpoints using ModelCheckpoint and set the argument `save_weights_only=True`, I got the following error:

```
> model.fit(
> File "/usr/local/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
> raise e.with_traceback(filtered_tb) from None
> File "/usr/local/lib/python3.9/site-packages/h5py/_hl/files.py", line 533, in __init__
> fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
> File "/usr/local/lib/python3.9/site-packages/h5py/_hl/files.py", line 232, in make_fid
> fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
> File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
> File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
> File "h5py/h5f.pyx", line 126, in h5py.h5f.create
> FileNotFoundError: [Errno 2] Unable to create file (unable to open file: name = 'gs://nbcu-ds-sandbox-b-001-kubeflowpipelines-default/tfx_pipeline_output/833943664137/cached-trainer-20230209170252/Trainer_8673819632617914368/model/checkpoint/checkpoint-weights-01-572.01.hdf5', errno = 2, error message = 'No such file or directory', flags = 13, o_flags = 242)
```

Here is the associated code

```python
    checkpoint_dir = os.path.join(os.path.dirname(fn_args.serving_model_dir), "checkpoint")
    tf.io.gfile.makedirs(checkpoint_dir) # make the folder on GCS
    model_checkpoint_callback = tf.keras.callbacks.ModelCheckpoint(
        filepath=os.path.join(checkpoint_dir, "checkpoint-weights-{epoch:02d}-{val_loss:.2f}.hdf5"),
        save_weights_only=True,
        save_best_only=False,
        save_freq="epoch",
    )
    # train
    model.fit(
        train_dataset,
        epochs=fn_args.custom_config["num_of_epochs"],
        verbose=fn_args.custom_config.get("model_fit_verbose", 2),
        validation_data=eval_dataset,
        # steps_per_epoch=10,
        # validation_steps=10,
        callbacks=[ # tensorboard_callback,
             model_checkpoint_callback,
        ],
    )
```

However, if I set to `save_weights_only=False`, then the checkpoint can be saved without error.

I am more or less expecting that both `save_weights_only=True` and  `save_weights_only=False` are supported on GCS. Is there something wrong with code on specifying the file path of the checkpoints?

**Comment by tilakrayal** [comment]
@EdwardCuiPeacock,
Thank you for the issue. The provided code is incomplete. In order to expedite the trouble-shooting process, could you please provide a complete code snippet which helps us to debug the issue in an effective way. Thank you!
