### ISSUE TITLE
Empty page

### ISSUE THREAD

**Issue by Guitalex** [keras-team/keras#17584]
this page is empty.. is it possible to fix it?

https://keras.io/examples/structured_data/bayesian_neural_networks/

**Comment by tilakrayal** [comment]
@Guitalex,
Thank you for reporting the issue. We will keep a track on the issue. For the workaround, Could you please let us know if you are looking for a similar document, kindly have a look at this https://keras.io/examples/keras_recipes/bayesian_neural_networks/   and let us know if it serves the purpose. Thank you!

**Comment by SuryanarayanaY** [comment]
This file is missing at the master branch.Technically it should be here at this [path](https://github.com/keras-team/keras-io/tree/master/examples/structured_data) but no such notebook exists for this. I need to check whether this is under implementation stage or missing now.

Hi @Guitalex ,
Thanks for reporting this.Do you have any idea whether this file existed with older versions?

**Comment by SuryanarayanaY** [comment]
Hi @Guitalex ,
A commit has been raised from our Dev Team to remove this blank page as it was moved to other path mentioned above.
The documentation may reflect shortly or in next doc release. Thanks!
