### ISSUE TITLE
Add "tf.debugging.check_numerics" to each API's inputs and outputs.  Use a global flag to enable/disable this check.

### ISSUE THREAD

**Issue by edwardyehuang** [keras-team/keras#17604]
**System information**.

TensorFlow version (you are using):2.11
Are you willing to contribute it (Yes/No) :maybe

**Describe the feature and the current behavior/state**.

Add "tf.debugging.check_numerics" to each API's inputs and outputs.  Use a global flag to enable/disable this check.

**Will this change the current api? How?**
Add "tf.debugging.check_numerics" to each API's inputs and outputs. 

**Who will benefit from this feature?**
I found some code under mixed precision that can run on GPU or TPUv3 but get NaN on TPUv4. This feature will help me easier to debug numerics issues.

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**

- Do you want to contribute a PR? (yes/no):
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing):

**Comment by jbischof** [comment]
@edwardyehuang since this is a core TensorFlow feature request could you please file an issue in the [tensorflow](https://github.com/tensorflow/tensorflow/issues) repo?
