### ISSUE TITLE
KerasCV - Cannot save model from model.save(PATH)

### ISSUE THREAD

**Issue by slavazhulanov** [keras-team/keras#17610]
keras                         2.11.0
keras-cv                      0.4.2

I trained the model with [this ](https://keras.io/guides/keras_cv/retina_net_overview/)tutorial. At the end, the WEIGHTS are saved, but I need to save the MODEL. When I save the MODEL I get the error:

ValueError: Model <keras_cv.models.object_detection.retina_net.retina_net.RetinaNet object at 0x00000287F451B6D0> cannot be saved either because the input shape is not available or because the forward pass of the model is not defined.To define a forward pass, please override Model.call(). To specify an input shape, either call build(input_shape)directly, or call the model on actual data usingModel(), Model.fit(), or Model.predict(). If you have a custom training step, please make sure to invoke the forward pass in train step through Model.call, i.e. model(inputs), as opposed to model.call().

Next, I plan to convert the MODEL to ONNX format and use it in OpenCV.

![image](https://user-images.githubusercontent.com/50666828/221521333-8eea32ea-3f30-4a5c-b841-ac8a3e296ec1.png)
![image](https://user-images.githubusercontent.com/50666828/221521365-57bb647d-d773-41cb-bf91-7a42441c29e3.png)

**Comment by sushreebarsa** [comment]
@slavazhulanov I tried to replicate this issue and didn't face the error, could you please check this [gist](https://colab.research.google.com/gist/sushreebarsa/fdadfe6a5f81847ebf4be695e40fc07b/retina_net_overview.ipynb) and confirm the same. Please let me know if I am missing something to replicate the issue.
Thank you!

**Comment by slavazhulanov** [comment]
@sushreebarsa I have attached a [link ](https://colab.research.google.com/drive/1LC76i5Wbey7BM4KkciZnVuHth7BZhM-M?usp=sharing)here. The tutorial uses .save_weights() and my error is related to .save()

**Comment by SuryanarayanaY** [comment]
Hi @slavazhulanov ,

As the tutorial using are using `keras.callbacks.ModelCheckpoint(CHECKPOINT_PATH, save_weights_only=True)` in the callbacks, we can only save this model weights using `model.save_weights()` . 

To use model.save() with the same above call back you should use it like below.
`model.save(CHECKPOINT_PATH,include_optimizer=None,save_traces=None)`

Please refer to attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/3b61e523004dc633752daf7310e951ab/17610_r2.ipynb).

Thanks!

**Comment by slavazhulanov** [comment]
Hi @SuryanarayanaY,

Your reply solved my problem! 
Thank you very much)

**Comment by slavazhulanov** [comment]
@SuryanarayanaY 
But when I tried to make a prediction I got this error: 
    
    Cannot call custom layer RetinaNet of type <class 'keras.saving.legacy.saved_model.load.keras_cv>RetinaNet'>, because the call function was not serialized to the SavedModel.Please try one of the following methods to fix this issue:
    
    (1) Implement `get_config` and `from_config` in the layer/model class, and pass the object to the `custom_objects` argument when loading the model. For more details, see: https://www.tensorflow.org/guide/keras/save_and_serialize
    
    (2) Ensure that the subclassed model or layer overwrites `call` and not `__call__`. The input shape and dtype will be automatically recorded when the object is called, and used when saving. To manually specify the input shape/dtype, decorate the call function with `@tf.function(input_signature=...)`.
    
    Call arguments received by layer 'RetinaNet' (type keras_cv>RetinaNet):
      • unused_args=('tf.Tensor(shape=(None, 640, 640, 3), dtype=float32)',)
      • unused_kwargs={'training': 'False'}`
      
      
 
Check [this](https://colab.research.google.com/drive/1LC76i5Wbey7BM4KkciZnVuHth7BZhM-M?usp=share_link)

**Comment by SuryanarayanaY** [comment]
Hi @slavazhulanov ,

If your model has custom objects or custom layers then you need to define `get_config` and `from_config` methods in the Model.Then during model.save() you need to pass an argument custom_objects with dictionary of custom objects.

Please refer to attached [source](https://www.tensorflow.org/guide/keras/save_and_serialize#defining_the_config_methods) for a minimal example.

You may also refer to this keras [issue-17383](https://github.com/keras-team/keras/issues/17383) for an example.You need to recreate the model accordingly.

Thanks!
