### ISSUE TITLE
Convert the CuDNNLSTM weights into LSTM fails while the custom Model class is used

### ISSUE THREAD

**Issue by YadongChen-1016** [keras-team/keras#17623]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.10.0
- Python version: 3.10.8
- Bazel version (if compiling from source):
- GPU model and memory: Nvidia 3070 ti 

**Describe the problem**.

**Describe the current behavior**.
I tried to train the model weight using CuDNNLSTM and load the weight into LSTM. When I call CuDNNLSTM, if I do not use the custom Model class, everything is okay. However, when I use 'tf.keras.Model' to implement a custom model class, and then call it, the following error will appear:

ValueError: Cannot assign value to variable ' rnn_block_1/bidirectional_2/forward_lstm/lstm_cell_1/bias:0': Shape mismatch.The variable shape (64,), and the assigned value shape (128,) are incompatible.

**Describe the current behavior**.
**Describe the expected behavior**.
**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no):  no
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing):

**When the following code runs, the error described above will occur.**

`import python`
`import tensorflow as tf`
`from tensorflow.keras.models import Model`
`from keras import layers`

`class RNNBlock(tf.keras.Model):`

    def __init__(self, if_cudnn):
        super(RNNBlock, self).__init__()
        if if_cudnn:
            self.intra_rnn = tf.keras.layers.Bidirectional(
                    tf.compat.v1.keras.layers.CuDNNLSTM(units=16, return_sequences=True, implementation=2))
            self.inter_rnn = tf.keras.layers.Bidirectional(
                    tf.compat.v1.keras.layers.CuDNNLSTM(units=16, return_sequences=True, implementation=2))
        else:
            self.intra_rnn = tf.keras.layers.Bidirectional(
                tf.compat.v1.keras.layers.LSTM(units=16, return_sequences=True, implementation=2))
            self.inter_rnn = tf.keras.layers.Bidirectional(
                tf.compat.v1.keras.layers.LSTM(units=16, return_sequences=True, implementation=2))

    def call(self, x):
        out = self.inter_rnn(self.intra_rnn(x))
        return out

`class RNN_model():`

    def __init__(self, if_cudnn):
        self.model = None
        self.if_cudnn = if_cudnn

    def build_RNN_model(self):

        # input layer for time signal
        in_data = layers.Input(batch_shape=(2, 20, 32))
        out_data = RNNBlock(self.if_cudnn)(in_data)
        self.model = Model(in_data, out_data)
        return self.model

`if __name__ == "__main__":`

    dpcrn_1 = RNN_model(if_cudnn=1)
    model_1 = dpcrn_1.build_RNN_model()
    model_1.save_weights("GPU_keras.h5")

    dpcrn_0 = RNN_model(if_cudnn=0)
    model_0 = dpcrn_0.build_RNN_model()
    model_0.load_weights("GPU_keras.h5")

**By contrast, there are no errors when running the following code.**

`import tensorflow as tf`
`from tensorflow.keras.models import Model`
`from keras import layers`

`class RNN_model():`

    def __init__(self, if_cudnn):
        self.model = None
        self.if_cudnn = if_cudnn

    def RNNBlock(self, input):
        if self.if_cudnn:
            out = tf.keras.layers.Bidirectional(
                tf.compat.v1.keras.layers.CuDNNLSTM(units=16, return_sequences=True, implementation=2))(input)
            output = tf.keras.layers.Bidirectional(
                tf.compat.v1.keras.layers.CuDNNLSTM(units=16, return_sequences=True, implementation=2))(out)
        else:
            out = tf.keras.layers.Bidirectional(
                tf.compat.v1.keras.layers.LSTM(units=16, return_sequences=True, implementation=2))(input)
            output = tf.keras.layers.Bidirectional(
                tf.compat.v1.keras.layers.LSTM(units=16, return_sequences=True, implementation=2))(out)
        return output

    def build_RNN_model(self):

        # input layer for time signal
        in_data = layers.Input(batch_shape=(2, 20, 32))
        out_data = self.RNNBlock(in_data)
        self.model = Model(in_data, out_data)
        return self.model

`if __name__ == "__main__":`

    dpcrn_1 = RNN_model(if_cudnn=1)
    model_1 = dpcrn_1.build_RNN_model()
    model_1.save_weights("GPU_keras.h5")

    dpcrn_0 = RNN_model(if_cudnn=0)
    model_0 = dpcrn_0.build_RNN_model()
    model_0.load_weights("GPU_keras.h5")

**How should I solve it?**

**Comment by tilakrayal** [comment]
@YadongChen-1016,
I tried to execute the mentioned code and it was failing due to an indentation error. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/a9e52eb7537bd6ec86d4a1e6385af5f1/untitled1019.ipynb) and provide the code in the executable way or colab gist. Thank you!
