### ISSUE TITLE
Distributed training 

### ISSUE THREAD

**Issue by DNJ-JINI** [keras-team/keras#17683]
I am using the following code to use distributed training with azure [GPU - 2 x NVIDIA Tesla V100]. So during the training process both the available  GPU  is working and the training time is also less compared with single GPU. 
My question is whether the data is divided among each GPU ( 16 samples per GPU or 32 samples per GPU since I have given the batch_size as 32). Also when batch_size is 64 it results in resource exhausted error. The model input shape is 256x256

batch_size = 32
dist_data_train = tf.data.Dataset.from_tensor_slices((X_train, y_train)).batch(batch_size)
dist_data_val = tf.data.Dataset.from_tensor_slices((X_test, y_test)).batch(batch_size)

strategy = tf.distribute.MirroredStrategy()
print('Number of devices: {}'.format(strategy.num_replicas_in_sync))

# Create a distributed model
with strategy.scope():
    model = get_model(img_size, num_classes)
    distributed_model = model
    distributed_model.compile(optimizer = tf.keras.optimizers.Adam(lr = 0.001), loss = ['sparse_categorical_crossentropy'], metrics=['accuracy'])

checkpoint = ModelCheckpoint(model_name,
                             monitor="val_loss",
                             mode="min",
                             save_best_only = True,
                             verbose=1)
early = EarlyStopping(monitor="val_loss", mode="min", patience=15)
callbacks=[early, checkpoint]
num_epochs= 200
#modelunet=distributed_model.fit(train_gen, epochs=num_epochs, validation_data=val_gen, callbacks=callbacks)
model=distributed_model.fit(dist_data_train, epochs=num_epochs, validation_data=dist_data_val, callbacks=callbacks)

**Comment by sushreebarsa** [comment]
@DNJ-JINI Could you please share the complete standalone code to reproduce this issue?
Thank you!

**Comment by DNJ-JINI** [comment]
####MNist
import tensorflow as tf
from tensorflow import keras
import random
import matplotlib.pyplot as plt

def get_compiled_model():
    # Make a simple 2-layer densely-connected neural network.
    inputs = keras.Input(shape=(784,))
    x = keras.layers.Dense(256, activation="relu")(inputs)
    x = keras.layers.Dense(256, activation="relu")(x)
    outputs = keras.layers.Dense(10)(x)
    model = keras.Model(inputs, outputs)
    model.compile(
        optimizer=keras.optimizers.Adam(),
        loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
        metrics=[keras.metrics.SparseCategoricalAccuracy()],
    )
    return model


def get_dataset():
    batch_size = 32
    num_val_samples = 10000

    # Return the MNIST dataset in the form of a [`tf.data.Dataset`](https://www.tensorflow.org/api_docs/python/tf/data/Dataset).
    (x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

    # Preprocess the data (these are Numpy arrays)
    x_train = x_train.reshape(-1, 784).astype("float32") / 255
    x_test = x_test.reshape(-1, 784).astype("float32") / 255
    y_train = y_train.astype("float32")
    y_test = y_test.astype("float32")

    # Reserve num_val_samples samples for validation
    x_val = x_train[-num_val_samples:]
    y_val = y_train[-num_val_samples:]
    x_train = x_train[:-num_val_samples]
    y_train = y_train[:-num_val_samples]
    print("111111111111111111111",len(x_train))
    return (
        tf.data.Dataset.from_tensor_slices((x_train, y_train)).batch(batch_size),
        tf.data.Dataset.from_tensor_slices((x_val, y_val)).batch(batch_size),
        tf.data.Dataset.from_tensor_slices((x_test, y_test)).batch(batch_size),
    )


# Create a MirroredStrategy.
strategy = tf.distribute.MirroredStrategy()
print("Number of devices: {}".format(strategy.num_replicas_in_sync))

# Open a strategy scope.
with strategy.scope():
    # Everything that creates variables should be under the strategy scope.
    # In general this is only model construction & `compile()`.
    model = get_compiled_model()

# Train the model on all available devices.
train_dataset, val_dataset, test_dataset = get_dataset()

model.fit(train_dataset, epochs=20, validation_data=val_dataset)

# Test the model on all available devices.
model.evaluate(test_dataset)


Please clarify the following question
Here batch size is 32 so  each GPU will take 16 samples or 32 samples for batch training.
If 32 samples are taken by each GPU in total 64 samples of data can be processed at single epoch utilizing both GPU.

**Comment by SuryanarayanaY** [comment]
Hi @DNJ-JINI ,

This is the concept of Data Parallelism. That means given batch of data equally sliced into available GPUs. Suppose If you have batch_size=32 and 2 nos of GPUs then each GPU will get 16 data points and if having 4 GPUs then Each GPU will get 8 data points for btach_size=32.

You might have observed that with single GPU suppose `batch_size=32` in `model.fit(x,y,batch_size = 32)` .The batch_size can be increased if we have multiple GPUs using Distribution Training and you can pass model.fit(x,y,batch_size = 32*No of GPUs).

Please refer to the attached Official Video [Tutorial](https://www.youtube.com/watch?v=S1tN9a4Proc) for more details of this concept.

**Comment by DNJ-JINI** [comment]
Thanks for the detail.
I am trying to apply distributed training on my custom dataset but I am getting this error
    ValueError: Layer "model" expects 1 input(s), but it received 2 input tensors. Inputs received: [<tf.Tensor 'cond/Identity:0' shape=(None, 256, 256, 3) dtype=float32>, <tf.Tensor 'cond/Identity_1:0' shape=(None, 256, 256, 1) dtype=int32>]


###thirdtrial#####
from sklearn.model_selection import train_test_split
images = [load_img(path, target_size=img_size, color_mode="rgb") for path in input_img_paths[0:100]]
print("00000000")
masks = [load_img(path, target_size=img_size, color_mode="grayscale") for path in target_img_paths[0:100]]

image_dataset = np.stack(images, axis=0)
image_dataset = image_dataset.astype('float32') 
#image_dataset =image_dataset/255.0
#print(".....",np.unique(image_dataset))
print("1111")
mask_dataset = np.stack(masks, axis=0)
mask_dataset = np.expand_dims(mask_dataset, axis=-1)
mask_dataset = mask_dataset.astype('uint8')
mask_dataset = np.where(mask_dataset == 0, 0, np.where(mask_dataset == 128, 1, 2))
print(".....",np.unique(mask_dataset))
print("22222")
X_train, X_test, y_train, y_test = train_test_split(image_dataset, mask_dataset, test_size = 0.20, random_state = 42)
print("333333")

augmentation_train = ImageDataGenerator(
    rotation_range=10,
    width_shift_range=0.1,
    height_shift_range=0.1,
    shear_range=0.1,
    zoom_range=0.1,
    horizontal_flip=True,
    vertical_flip=False,
    fill_mode='nearest'
)
augmentation_test = ImageDataGenerator(
    fill_mode='nearest'
)
X_train_augmented = augmentation_train.flow(X_train, batch_size=32)
y_train_augmented = augmentation_train.flow(y_train, batch_size=32)
X_test_augmented = augmentation_test.flow(X_test, batch_size=32)
y_test_augmented = augmentation_test.flow(y_test, batch_size=32)
train_augmented = zip(X_train_augmented, y_train_augmented)
test_augmented = zip(X_test_augmented, y_test_augmented)

train_ds = tf.data.Dataset.from_generator(
    lambda: train_augmented,
    output_types=((tf.float32, tf.int32), tf.int32),
    output_shapes=(([None, *X_train.shape[1:]], [None, *y_train.shape[1:]]), [None, *y_train.shape[1:]])
)

test_ds = tf.data.Dataset.from_generator(
    lambda: test_augmented,
    output_types=((tf.float32, tf.int32), tf.int32),
    output_shapes=(([None, *X_test.shape[1:]], [None, *y_test.shape[1:]]), [None, *y_test.shape[1:]])
)

strategy = tf.distribute.MirroredStrategy()
train_ds_distributed = strategy.experimental_distribute_dataset(train_ds)
test_ds_distributed = strategy.experimental_distribute_dataset(test_ds)

print(train_ds_distributed,test_ds_distributed)
print(train_ds,test_ds)
num_replicas =2
# Calculate the number of batches
train_steps_per_epoch = len(X_train) // batch_size
train_steps_per_epoch = train_steps_per_epoch // num_replicas


with strategy.scope():

    #model = get_model(img_size, num_classes) #mobilenet,basicmodel

    img_size =256 #xception
    num_classes =3 #xception
    model = get_model(num_classes,input_shape=(img_size,img_size,3)) #xception
    distributed_model = model
    distributed_model.compile(optimizer = tf.keras.optimizers.Adam(lr = 0.001), loss = ['sparse_categorical_crossentropy'], metrics=['accuracy'])

checkpoint = ModelCheckpoint(model_name,
                             monitor="val_loss",
                             mode="min",
                             save_best_only = True,
                             verbose=1)
early = EarlyStopping(monitor="val_loss", mode="min", patience=15)


callbacks=[early, checkpoint]
num_epochs= 200
#modelunet = distributed_model.fit(train_ds_distributed, epochs=num_epochs, steps_per_epoch=train_steps_per_epoch,validation_data=test_ds_distributed, callbacks=callbacks)
modelunet=distributed_model.fit(train_ds, epochs=num_epochs, validation_data=test_ds, callbacks=callbacks)
steps_per_epoch=train_steps_per_epoch
# summarize history for accuracy
plt.plot(modelunet.history['accuracy'])
plt.plot(modelunet.history['val_accuracy'])
plt.title('Model accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train', 'val'], loc='upper left')
plt.grid(True)
plt.show()
# summarize history for loss
plt.plot(modelunet.history['loss'])
plt.plot(modelunet.history['val_loss'])
plt.title('Model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'val'], loc='upper left')
plt.grid(True)
plt.show()

**Comment by SuryanarayanaY** [comment]
Hi @DNJ-JINI ,

Could you please share the code snippet in the form of a gist which can contain the outputs and logs. That helps us debugging the issue. I am not sure at what point the error is getting raised. You can run the code in Google colab with minimal data that is required for replication of the error and share it as a gist.

From the error you mentioned it seems the input arguments not defined properly. It seems your model expecting 1 input but its getting 2 Tensors as input.Model seems not configured properly.Providing more details along with colab gist can help us to look into the issue.

Thank you!

**Comment by SuryanarayanaY** [comment]
Hi @DNJ-JINI ,

As I don't have access to the dataset I can't reproduce the issue. Its nice if you can provide a dummy data set and also only minimal code required to reproduce the issue.

The error is related to the line `distributed_model.fit(train_ds,...)`. As for my understanding the `train_ds ` generated was not matching to the input that actually model was expecting at this step `get_model(num_classes,input_shape=(img_size,img_size,3))`.But in contrast the train_ds is actually generating two separate input Tensors, one of shape=(None, 256, 256, 3) dtype=float32 and other of `shape=(None, 256, 256, 1) dtype=int32`.

It seems the error is at below code which seems wrongly configured.

```
train_ds = tf.data.Dataset.from_generator(
    lambda: train_augmented,
    output_types=((tf.float32, tf.int32), tf.int32),
    output_shapes=(([None, *X_train.shape[1:]], [None, *y_train.shape[1:]]), [None, *y_train.shape[1:]])
)
```

Can you go through this once again and explain this to me.

Also can you confirm whether this runs without any distribution strategy. I am eager to know how this is related to distribution strategy.Can you share the code that works without any distribution strategy.

Thanks!
