### ISSUE TITLE
tensorflow 2.4.1 keras 2.4.3 cannot import name 'tf_utils' from 'tensorflow.keras.utils 

### ISSUE THREAD

**Issue by By1997-24** [keras-team/keras#17728]
I installed tensorflow-gpu using **conda install -c Anaconda tensorflow-gpu** , i then imported keras "import keras" module not found so i installed keras through conda too: **conda install -c anaconda keras-gpu**,  when i try to import tf_utils through tensorflow.keras.utils or keras.utils i get the same error cannot import name 'tf_utils' from 'tensorflow.keras.utils . Can you help please?

**Comment by fchollet** [comment]
That module doesn't exist. Try `keras.utils` or otherwise search for the symbol you want to import and you'll find its location.
