### ISSUE TITLE
Be explicit about rank of "left" versus "right" with respect to their relative positions within the source dataset

### ISSUE THREAD

**Issue by hstclair** [keras-team/keras#17730]
https://github.com/keras-team/keras/blob/f9336cc5114b4a9429a242deb264b707379646b7/keras/utils/dataset_utils.py#L36

Given the frequency with data leakage is a problem in AI models, it is important that documentation for methods that split training and testing data be as clear as possible.  Given the documentation of this method, it would be easy for an untrained reader to come away with the impression that `training_dataset, testing_dataset = split_dataset(source_dataset, left_size=training_size, right_size=testing_size)` is essentially equivalent to `testing_dataset, training_dataset = split_dataset(source_dataset, left_size=testing_size, right_size=training_size)`.  Even knowing that this is an important issue when working with a time series, it is not altogether clear to me, without testing, that left would precede right (though it seems intuitive).

Please update the documentation to indicate that "left" precedes "right" and update the example to demonstrate this - e.g.:
```
>>> import tensorflow as tf
>>> source_dataset = tf.data.Dataset.from_tensor_slices([[n] for n in range(0, 2)])
>>> list(source_dataset)
[<tf.Tensor: shape=(1,), dtype=int32, numpy=array([0], dtype=int32)>, <tf.Tensor: shape=(1,), dtype=int32, numpy=array([1], dtype=int32)>]
>>> training, testing = tf.keras.utils.split_dataset(source_dataset, left_size=1, right_size=1)
>>> list(training)
[(<tf.Tensor: shape=(), dtype=int32, numpy=0>,)]
>>> list(testing)
[(<tf.Tensor: shape=(), dtype=int32, numpy=1>,)]
```

**Comment by SuryanarayanaY** [comment]
Hi @hstclair ,

The API tf.keras.utils.split_dataset returns a tuple containing two `tf.data.Dataset ` objects. The left value takes Index[0] and right value takes index[1]. This is python behaviour and I hope users are aware of that.

Do you mean to say for Time series data, if they use test_dataset at left then there might be problem ? 

Is that what you meant to say or is there anything else I am missing here ?

**Comment by hstclair** [comment]
For timeseries data, the left entry in the tuple (at index[0] in the tuple) contains earlier elements and the right entry in the tuple (at index[1] in the tuple) contains later elements.

Given a dataset of k elements and some selection n where n < k:

`left, right = split_dataset(dataset, left_size=n, right_size=k-n)`

left will contain elements `dataset[:n]` while right will contain elements `dataset[n:]`

This result is not specified anywhere in the documentation and, while this result makes sense, it is not strictly intuitive.  

A user who is concerned about defending against temporal dependency errors while processing time series history versus outcomes must manually test this method in order to determine how it actually behaves.

I'm simply asking that an explanation similar to what I have provided above be added to the documentation so that it is not necessary to test the method in order to discover how it behaves.

**Comment by SuryanarayanaY** [comment]
Hi @hstclair ,

I think the example provided in documentation also same what you are expecting.Please refer below.

<img width="957" alt="Screenshot 2023-04-11 at 3 57 05 PM" src="https://user-images.githubusercontent.com/116063290/231133661-2c2740d8-9732-4470-b1cf-bf3573fc2eeb.png">

The example seems enough to what you are expecting. For me this seems enough.

May be, you can propose adding some additional text under the **Returns** section like: `the first and second objects of the tuple represents left_size and right_size datasets respectively`. You may propose similar text by creating a PR and let's hear from the developer team. WDYT ?

Thanks!
