### ISSUE TITLE
Keras TimeDistributed().  Same input shape produces inconsistent output shape between TF1.15.5 and TF2.11.0

### ISSUE THREAD

**Issue by ctmckee** [keras-team/keras#17734]
I am updating a model from TF1.15.5 to TF2.11.0.
For TF 1.15.5, Keras == 2.2.4
for TF 2.11.0, Keras == 2.11.0
I am running Python 3.10.8 
I am running the model on an AWS p3.2xlarge SageMaker Notebook

In TF == 1.15.5
```python
import keras
### This code snippet prints the shape issue.  The inputs tensor is the output of the prior layer in a Keras function model ###
print("shape of input going into TimeDistributed=",inputs.shape)
conv_2d_layer = keras.layers.Conv2D(filters=1024, kernel_size=(7,7), data_format='channels_last')
outputs = keras.layers.TimeDistributed(conv_2d_layer)(inputs)
print("TimeDistributed output shape =",outputs.shape)
### end of code snippet ###
```
![tf1 15Print](https://user-images.githubusercontent.com/40606780/228021281-11f5d0d0-9424-4d40-b7b7-3b4f4d2e69dd.PNG)

In TF == 2.11.0
```python
import tensorflow as tf
### This code snippet prints the shape issue.  The inputs tensor is the output of the prior layer in a Keras function model ###
print("shape of input going into TimeDistributed =",inputs.shape)    
conv_2d_layer = tf.keras.layers.Conv2D(filters=1024, kernel_size=(7, 7), data_format='channels_last')
outputs = tf.keras.layers.TimeDistributed(conv_2d_layer)(inputs)
print('TimeDistributed output shape =',outputs.shape)
### end of code snippet ###
```
![TF2 11Print](https://user-images.githubusercontent.com/40606780/228021608-19a781dd-fe10-4e18-8418-0521c30852e3.PNG)

The model I am trying to convert (MaskRCNN), has been utilized extensively by others in TF1.15.  Is this a bug of TF2.11.0?  If not could you explain in the documentation why these are different and/or how to achieve the correct output shape.  The correct output shape should be that shown for TF1.15.5.

**Comment by ctmckee** [comment]
I think I have found the issue, but do not know how to resolve yet:

The Class TimeDistributed(Wrapper) in Keras 2.11.0 performs the the 'if input_shape[0]:' of the def call(), the Class TimeDistributed(Wrapper) in Keras 2.2.4 performs the 'else:' of the def call().

The reason for this, is that the backend function keras.backend.int_shape(input) has changed.  In Keras 2.2.4 it is looking for an attribute of the input called ._keras_shape.  This attribute exists in Keras 2.2.4 and the function returns input._keras_shape which = (None, 200, 7, 7, 256), triggering the "else" inside the call of TimeDistributed().  This attribute does not exist in Keras 2.11.0 and keras.backend.int_shape(input) returns input.shape which = (2, None, 7, 7, 256), triggering the 'if' of TimeDistributed().

**Comment by ctmckee** [comment]
Root Issue Identified:

The root issue is caused by a change in the keras backend function int_shape(input).  In Keras 2.2.4, if the input to int_shape(input) has an Attribute called "_keras_shape", the return is input._keras_shape, else the return is input.get_shape().as_list().   These two return shapes do not match in Keras 2.2.4 for this model.    In Keras 2.2.4, the call() of TimeDistributed(Wrapper) has two optional pathways to create the output shape and the selection of that pathway depends on the return of int_shape(input).  The "if" pathway uses an rnn-based implementation which produces (2, None, 1,1,1024), the "else" pathway uses a reshape implementation which produces (None, 200, 1, 1, 1024) for the MaskRCNN model.  

In Keras 2.11.0 the backend function int_shape(input), no longer looks for the attribute "_keras_shape", I also ran a check to see if the input to int_shape(input) even has the attribute "_keras_shape" -  It did not.  So I suspect the same rnn pathway is being run, instead of the the reshape implementation in Keras 2.11.0 TimeDistributed(Wrapper).

**Comment by sushreebarsa** [comment]
@ctmckee Thank you for the update!
Yes you were right. The back-end function int_shape(input), no longer looks for the attribute "_keras_shape". 
For an example please check the following code snippet and refer to [this](https://keras.io/api/layers/recurrent_layers/time_distributed/) guide as well. This is a [guide](https://www.tensorflow.org/guide/migrate) for migration from TF v1.x to 2.x . Please let us know if it helps?
```
inputs = tf.keras.Input(shape=(10, 128, 128, 3))
conv_2d_layer = tf.keras.layers.Conv2D(64, (3, 3))
outputs = tf.keras.layers.TimeDistributed(conv_2d_layer)(inputs)
outputs.shape
```
Thank you!
