### ISSUE TITLE
Import issue with Keras nightly after 3/25

### ISSUE THREAD

**Issue by gkroiz** [keras-team/keras#17986]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 22.04.2 LTS
- TensorFlow installed from (source or binary): pip3 tf-nightly
- TensorFlow version (use command below): v1.12.1-92665-g26da3100020 2.13.0-dev20230414
- Python version: Python 3.10.6
- Bazel version (if compiling from source): N/A
- GPU model and memory: N/A (using TPU but I don't think that is important here)
- Exact command to reproduce: `python3 -c 'from keras.utils import tf_utils;`

**Describe the problem**.
When using keras-nightly from 3/25 to present day results in an import issue with `from keras.utils import tf_utils`: `ImportError: cannot import name 'tf_utils' from 'keras.utils' (/usr/local/lib/python3.10/dist-packages/keras/utils/__init__.py)`. However, `from keras.src.utils import tf_utils` works. This is an issue for existing repos that rely on the old import structure. I realize the [readme](https://github.com/keras-team/keras/blob/master/README.md#release-and-compatibility) mentions there is no support for backward compatibility in nightly builds. Keeping this in mind, is this change intentional or a bug? If this is intentional, then perhaps the fix needs to be implemented in repos that rely on this import, not keras.

**Describe the current behavior**.
Import error

**Describe the expected behavior**.
No import error

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no): I would be happy to if this is indeed a keras bug.
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing): N/A

**Standalone code to reproduce the issue**.
```
pip3 install tf-nightly
python3 -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"
```

**Comment by sushreebarsa** [comment]
Hello @gkroiz! 
I tried to replicate the issue reported on colab and didn't face any import error for `from keras.utils import tf_utils ` in tf-nightly. Could you please  have a look at this [gist](https://colab.research.google.com/gist/sushreebarsa/2e26e148342bce1374790312c78bbd65/17986.ipynb#scrollTo=VeE-y50C8LcO) and let me know if I am missing something?
Thank you!

**Comment by gkroiz** [comment]
Thank you for the response. Please look at the following:
Example using keras-nightly-latest: [gist](https://colab.research.google.com/gist/gkroiz/e1eddd208f205855da204363418ced64/17986.ipynb)

**Comment by sushreebarsa** [comment]
@gkroiz Thank you for your response!
I have made a copy for your gist and executed it again. I didn't see the import error. Please find the [gist](https://colab.research.google.com/gist/sushreebarsa/c282534ffeb0a95d5948298d5b12aa0a/17986.ipynb). Thank you!
