### ISSUE TITLE
Conv1DTranspose "groups" argument

### ISSUE THREAD

**Issue by WaterBoiledPizza** [keras-team/keras#18051]
**System information**.

TensorFlow version (you are using): 2.10.0
Are you willing to contribute it (Yes/No) : No since I have yet to have enough knowledge about that, but would love to if I eventually know more about this topic.

**Describe the feature and the current behavior/state**.

In the Conv1D layer, there's a "groups" argument to separate channels. However, there is none for the Conv1DTranspose layer, which would greatly increase the parameter for the model.
The following image shows the problem of such an issue. 
![image](https://user-images.githubusercontent.com/31476555/233968453-aeb87176-fb69-4de9-8c55-8b37a9454c72.png)

**Will this change the current api? How?**
Not enough knowledge to answer.

**Who will benefit from this feature?**
Users who plans to implement autoencoders with 1D Convolutions, multiple channels, and 1 kernel

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**

- Do you want to contribute a PR? (yes/no): No since I have yet to have enough knowledge about that, but would love to if I eventually know more about this topic

**Comment by WaterBoiledPizza** [comment]
I am currently modifying a speech enhancement model based on [breizhn's DTLN](https://github.com/breizhn/DTLN)
The original model contains a 1D Convolution encoder and decoder that operates in a different dimension (block length x 1) instead of the usual dimension (1 x block length). Therefore I am experimenting with the latter method.

During the training, a whole 6 seconds of audio is used and separated into different blocks as channels (for the numbers, 96000 samples totally, a block length is 512. With overlap, the number of blocks/channels is ((96000 x 2) - 512) / 512 = 374 as shown in the image in the original comment)

With this approach, in the Conv1D operation, I can specify the convolution is split into 374 groups so only one kernel is used during the operation. However, this is not the case for Conv1DTranspose as there's no option to split the channel into groups.

**Comment by mihirparadkar** [comment]
Hi!

This would be a nice feature to have, but it's not supported in the tf.nn module as of yet. A possible workaround could be using separate Conv1DTranspose operations and concatenating the outputs. If you think of something better we would also welcome PRs.
