### ISSUE TITLE
Spurious results with `model.compile(jit_compile=True)` and explicit XLA compilation of the model 

### ISSUE THREAD

**Issue by sayakpaul** [keras-team/keras#18062]
I am trying to reap the benefit of XLA for speeding up the inference latency of a model. 

Here's what I have initially:

```python
import tensorflow as tf 
import timeit 

mobilenet = tf.keras.applications.MobileNetV3Large()
mobilenet.compile(jit_compile=True)
random_inputs = tf.random.normal((10, 224, 224, 3))

# Warm-up
_ = mobilenet.predict(random_inputs)
print("XLA:", timeit.timeit(
    lambda: mobilenet.predict(random_inputs, verbose=0),
    number=10)
)
```

This spits out: `0.740119798999956` (seconds) which is faster than the non-XLA compiled variant. 

But when I do:

```python
tf.keras.backend.clear_session()

mobilenet = tf.keras.applications.MobileNetV3Large()
model_call_fn = tf.function(mobilenet, jit_compile=True)
random_inputs = tf.random.normal((10, 224, 224, 3))

# Warm-up
_ = model_call_fn(random_inputs, training=False)
print(
    "XLA:",
    timeit.timeit(lambda: model_call_fn(random_inputs, training=False), number=10),
)
```

i.e., compile the model forward pass into XLA more explicitly, I get even more speed-up: `0.05020096599997714` (seconds). 

**Why is this the case?** I would expect these two to produce identical results in terms of speed (unless I am missing out on something). 

I have verified that both the above snippets produce the same results:

```
import numpy as np 

non_function_output = mobilenet.predict(random_inputs)
function_output = model_call_fn(random_inputs, training=False)

np.testing.assert_allclose(
    non_function_output,
    function_output.numpy(),
    atol=1e-5,
    rtol=1e-5
) 
```

Here's my test Colab Notebook: https://colab.research.google.com/gist/sayakpaul/81bb03bcca3324935928dd347cce3a5d/scratchpad.ipynb

Cc: @gante

**Comment by tilakrayal** [comment]
@sayakpaul,
When I tried to execute with the t tf-nightly [2.13.0-dev20230428](https://colab.research.google.com/gist/tilakrayal/ac2d158f9e57698d4c826ba26db6b9dd/2-13-scratchpad.ipynb), the results in terms of speed changes from `74 to 64`. Kindly find the gist and the screenshot for the reference. Thank you!

![Screenshot 2023-04-28 7 04 03 PM](https://user-images.githubusercontent.com/81610181/235161825-5c08543d-f57b-452d-adb1-4386201d0667.png)

**Comment by sayakpaul** [comment]
I think I made my question pretty clear here:

> Why is this the case? I would expect these two to produce identical results in terms of speed (unless I am missing out on something).

In your screenshot also, in the bottom cell, the inference speed doesn't match with the cell above.

**Comment by Frightera** [comment]
@sayakpaul 

AFAIK when you use `predict()` it triggers bunch of validations and data conversions, for example your `random_inputs` was converted to an iterable first, called data adapter object, see: https://github.com/keras-team/keras/blob/302b8da880d5589a4e206d61b97f1c6b848d751b/keras/engine/data_adapter.py#L220

I expect some speed-up if you use `tf.data` in predict like this:

```python
tf.keras.backend.clear_session()

mobilenet = tf.keras.applications.MobileNetV3Large()
mobilenet.compile(jit_compile=True)
random_inputs = tf.data.Dataset.from_tensor_slices(tf.random.normal((10, 224, 224, 3))).batch(10)

# Warm-up
_ = mobilenet.predict(random_inputs)
print("XLA:", timeit.timeit(
    lambda: mobilenet.predict(random_inputs, verbose=0),
    number=10)
)
```

If you directly invoke `call` method of the model, you just make the forward pass and get the outputs, that's why it is faster. I don't expect both of them to be identical (in terms of speed) as `predict()` has some kind of different checks and transformations.

Hope this clarifies your query.

**Comment by sayakpaul** [comment]
Fair enough. That is really helpful.
