### ISSUE TITLE
an incorrect comments in keras.layers.RandomWidth

### ISSUE THREAD

**Issue by qibolee** [keras-team/keras#18080]
https://github.com/keras-team/keras/blob/117a514bed5fd2f1124b7d78790cc72a63679ac7/keras/layers/preprocessing/image_preprocessing.py#L1654

it should be:
`for resizing horizontally`, not `for resizing vertically`

**Comment by qibolee** [comment]
@SuryanarayanaY 
thank you for your reply. I don't agree with your statement, from actual performance, `keras.layers.RandomWidth()` is to change the no. of columns based on `factor`. The result of running the code is as follows, we can see that the no. of rows is  not changed, but the columns has changed:
![image](https://user-images.githubusercontent.com/16131647/236135917-7343ac38-2e39-4955-84cb-ae49c2b683c1.png)

**Comment by ianstenbit** [comment]
@qibolee I agree that this docstring should state "for resizing horizontally"

Are you interested in opening a PR to fix this?
If not, I can send a fix. Thanks for pointing out this issue!

**Comment by qibolee** [comment]
@ianstenbit  yes, I'm interested to fix this, but I when I push request, I get a error: 
![image](https://github.com/keras-team/keras/assets/16131647/175af18c-20da-41db-8eb8-ab45f634a9c0)

I don't know how to solve this error

**Comment by ianstenbit** [comment]
@qibolee you don't have write access to the Keras repo, so you'll need to create your own fork, make the change on the fork, and open a pull request to this repo. Feel free to @ me on that pull request when you make it.

**Comment by SuryanarayanaY** [comment]
@qibolee ,

The proposed PR merged now and it reflecting in tf-nightly source code below.

https://github.com/keras-team/keras/blob/cf88adabeabcf468e3f5f3a3167fbcbe69a89b36/keras/layers/preprocessing/image_preprocessing.py#LL1654C1-L1655C1

Shall we close the PR now. Thanks!
