### ISSUE TITLE
Reopen Adding option for custom padding (Conv2D)

### ISSUE THREAD

**Issue by antonmilev** [keras-team/keras#18109]
Please reassess the following request for custom padding in Conv2D layers:

https://github.com/keras-team/keras/issues/15504

I am not sure why it is closed because it seems the feature is not implemented (or at least not in the documentation).

Thanks.

**Comment by tilakrayal** [comment]
@antonmilev,
Could you please elaborate about your Feature. Also, please specify the Use Cases for this feature. Thank you!
