### ISSUE TITLE
Issue with masking padding values on embedding layer

### ISSUE THREAD

**Issue by torivor** [keras-team/keras#18104]
I'd like to ask further details about Keras embedding layer masking functionalities. Reference to the layer code =
https://github.com/keras-team/keras/blob/f9336cc5114b4a9429a242deb264b707379646b7/keras/layers/core/embedding.py#L33-L306

Main issue =
The docs stated that the layer can mask out special padding values. However, based on the parameters available, it seemed that the only value that can be masked out is 0 (through `mask_zero = True`). I've also tried adding a masking layer before an embedding layer, but the embedding layer still ignores the mask created by the masking layer.

Question =
Is there a way to specify another value other than 0 to be masked out by the embedding layer? Or perhaps a way so that the embedding layer accepts the mask created by the masking layer??

**Comment by tilakrayal** [comment]
@torivor,
Thank you for the issue. Could you please provide the complete code which can be reproducible and help us to analyse the issue in an effective way. Thank you!
