### ISSUE TITLE
Export some commonly used functions to public API

### ISSUE THREAD

**Issue by shkarupa-alex** [keras-team/keras#18115]
**System information**.

TensorFlow version (you are using): 2.13.0.dev20230417
Are you willing to contribute it (Yes/No) : Maybe

**Describe the feature and the current behavior/state**.

Allow to import these functions and classes from public api, not from `src`:
```
from keras.src.backend import convert_inputs_if_ragged, maybe_convert_to_ragged  # was from keras import backend -> backend.convert_inputs_if_ragged
from keras.src.losses import LossFunctionWrapper # for custom losses
from keras.src.metrics import SumOverBatchSize # for custom metrics
from keras.src.utils.tf_utils import shape_type_conversion # as decorator for custom layers build/compute_output_shape  methods
from keras.src.utils.conv_utils import normalize_tuple # for custom layers constructors
from keras.src.utils.control_flow_util import smart_cond
from keras.src.utils.losses_utils import compute_weighted_loss # for custom losses inside layers
from keras.src.utils.losses_utils import ReductionV2 # for custom losses
from keras.src.utils.generic_utils import has_arg # for custom layer wrappers
```

**Will this change the current api? How?**

No, it will just enable more comfortable usage

**Who will benefit from this feature?**

People who write custom layers/losses/metrics

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**

- Do you want to contribute a PR? (yes/no): Maybe
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing): Mark these functions/classes with @keras_export

**Comment by tilakrayal** [comment]
@shkarupa-alex,
Could you please provide any specific usecase for this feature implementation which helps us to analyse the purpose more. Thank you!

**Comment by rchao** [comment]
For now Keras team does not have the plan to make those APIs public; you can continue using `src` namespace but they are without guarantees from the Keras team.

**Comment by shkarupa-alex** [comment]
@rchao it would be great if at least `shape_type_conversion` become public
