### ISSUE TITLE
Adding this topic to keras.io/keras_tuner

### ISSUE THREAD

**Issue by jntdst** [keras-team/keras#18119]
https://stackoverflow.com/questions/73180899/keras-tuner-what-exactly-does-max-trials-executions-per-trial-and-epochs-do

**Comment by tilakrayal** [comment]
@jntdst,
executions_per_trial and epoch are the arguments which are to be provided for the model/apis. That data was already available in the Keras.io official doc. Please take a look at the below links
https://keras.io/guides/keras_tuner/getting_started/
https://keras.io/api/models/model_training_apis/


**executions_per_trial.**:  The number of models that should be built and fit for each trial. Different trials have different hyperparameter values. The executions within the same trial have the same hyperparameter values. The purpose of having multiple executions per trial is to reduce results variance and therefore be able to more accurately assess the performance of a model. If you want to get results faster, you could set executions_per_trial=1 (single round of training for each model configuration)

**epochs:** Integer. Number of epochs to train the model. An epoch is an iteration over the entire x and y data provided (unless the steps_per_epoch flag is set to something other than None). Note that in conjunction with initial_epoch, epochs is to be understood as "final epoch". The model is not trained for a number of iterations given by epochs, but merely until the epoch of index epochs is reached.

If you feel something needs to be added more in those document, please feel free to contribute with the PR. Thank you!
