### ISSUE TITLE
Support for Keras in Java

### ISSUE THREAD

**Issue by lohitslohit** [keras-team/keras#18120]
## Description

I am exploring the usage of Keras for deep learning tasks, and I would like to know if Keras has support for Java programming language. I have been using Keras in Python, but now I need to integrate it into a Java project. I have searched for documentation and examples but couldn't find clear information on using Keras in Java.

## Question

1. Does Keras have official support for Java? If yes, where can I find the relevant documentation and resources?
2. If there is no official support, are there any community-supported libraries or frameworks that allow using Keras in Java?
3. What are the recommended approaches or best practices for integrating Keras models into a Java project?

Any insights, guidance, or references to relevant resources would be greatly appreciated. Thank you!

**Comment by innat** [comment]
> If there is no official support, are there any community-supported libraries or frameworks that allow using Keras in Java?

https://github.com/dhruvrajan/tensorflow-keras-java

**Comment by rchao** [comment]
No, there's not official support of Java-based Keras library from Keras team.

There's a Java project that enables you to load Keras model, that you're free to check out: https://github.com/deeplearning4j/deeplearning4j
