### ISSUE TITLE
RepeatVector for LSTM encoder decoder models

### ISSUE THREAD

**Issue by jaweriaamjad** [keras-team/keras#18130]
I am currently working on implementing a variational autoencoder for time series data. The dataset I'm using contains samples with varying timesteps, ranging from 100 to 6000 samples. Below is the definition of my model:

`def get_model():
    
    max_length = 6000
    # encoder 
    inp = Input(shape=(None, 1))
    print(tf.shape(inp))
    masked = Masking(mask_value=-999.0)(inp)
    enc = LSTM(64)(masked)
    z = Dense(32, activation="relu")(enc)
    z_mean = Dense(latent_dim)(z)
    z_log_sigma = Dense(latent_dim)(z)
    encoder = Model(inp, [z_mean, z_log_sigma])
    
    # decoder 
    inp_z = Input(shape=(latent_dim,))
    dec = RepeatVector(max_length)(inp_z)
    dec = LSTM(64, return_sequences=True)(dec)
    out = TimeDistributed(Dense(1))(dec)
    decoder = Model(inp_z, out)   
    
    z_mean, z_log_sigma = encoder(inp)
    z = Lambda(sampling)([z_mean, z_log_sigma])
    pred = decoder(z)
    
    vae = Model(inp, pred)
    vae.add_loss(vae_loss(inp, pred, z_log_sigma, z_mean))
    vae.compile(loss=None, optimizer=Adam(learning_rate=1e-3))
    print(vae.summary())
    return vae, encoder, decoder`

To handle the varying timesteps, I initially tried padding all the samples to a fixed length of 6000. However, this approach significantly increases the training load and affects performance. As an alternative solution, I am considering passing batches with different lengths, where padding is applied within each batch to ensure that the maximum length of each batch matches the length of the longest sample within that batch. I have attempted to use tf.RepeatVector to achieve this, but it seems that tf.RepeatVector does not accept varying length values. Despite exploring various solutions suggested in previous issues ([Variable length RepeatVector #7949](https://github.com/keras-team/keras/issues/7949)), I encountered compilation errors with TensorFlow.

> ValueError: Graph disconnected: cannot obtain value for tensor KerasTensor(type_spec=TensorSpec(shape=(None, None, 1), dtype=tf.float32, name='input_17'), name='input_17', description="created by layer 'input_17'") at layer "repeat_vector_dynamic". The following previous layers were accessed without issue: []

Is there any alternative approach that can be used instead of tf.RepeatVector to repeat the latent representation across timesteps with varying lengths?

**Comment by tilakrayal** [comment]
@jaweriaamjad,
In the given code snippet you have defined the class and its methods but are not calling them anywhere. Could you please provide the complete code to reproduce the issue and helps us to analyse the issue in an effective way. Thank you!
