### ISSUE TITLE
i am getting error like this (Sequential' object has no attribute '_nested_outputs)

### ISSUE THREAD

**Issue by manish123k** [keras-team/keras#18149]
### This is error
AttributeError                            Traceback (most recent call last)
[<ipython-input-26-38c2629cdfbf>](https://localhost:8080/#) in <cell line: 2>()
      1 # Merging the output of the two models,i.e, model_q1 and model_q2
----> 2 mergedOut = Multiply()([model_q1.output, model_q2.output])
      3 
      4 mergedOut = Flatten()(mergedOut)
      5 mergedOut = Dense(100, activation = 'relu')(mergedOut)

[/usr/local/lib/python3.10/dist-packages/keras/engine/functional.py](https://localhost:8080/#) in output(self)
    393           RuntimeError: if called in Eager mode.
    394         """
--> 395         return self._nested_outputs
    396 
    397     @property

AttributeError: 'Sequential' object has no attribute '_nested_outputs'

### Source code / logs
# Model for Q1
model_q1 = tf.keras.Sequential()
model_q1.add(Embedding(input_dim = len(word_index)+1,
                       output_dim = 100,
                      weights = [embedding_matrix],
                      input_length = 30))
model_q1.add(LSTM(128, activation = 'tanh', return_sequences = True))
model_q1.add(Dropout(0.2))
model_q1.add(LSTM(128, return_sequences = True))
model_q1.add(LSTM(128))
model_q1.add(Dense(60, activation = 'tanh'))
model_q1.add(Dense(2, activation = 'sigmoid'))

# Model for Q2
model_q2 = tf.keras.Sequential()
model_q2.add(Embedding(input_dim = len(word_index)+1,
                       output_dim = 100,
                      weights = [embedding_matrix],
                      input_length = 30))
model_q2.add(LSTM(128, activation = 'tanh', return_sequences = True))
model_q2.add(Dropout(0.2))
model_q2.add(LSTM(128, return_sequences = True))
model_q2.add(LSTM(128))
model_q2.add(Dense(60, activation = 'tanh'))
model_q2.add(Dense(2, activation = 'sigmoid'))

# Merging the output of the two models,i.e, model_q1 and model_q2
mergedOut = Multiply()([model_q1.output, model_q2.output])

mergedOut = Flatten()(mergedOut)
mergedOut = Dense(100, activation = 'relu')(mergedOut)
mergedOut = Dropout(0.2)(mergedOut)
mergedOut = Dense(50, activation = 'relu')(mergedOut)
mergedOut = Dropout(0.2)(mergedOut)
mergedOut = Dense(2, activation = 'sigmoid')(mergedOut)

##Please help me

**Comment by tilakrayal** [comment]
@manish123k,
Could you please try to add `input_shape=(height,width,channels)` to the first layer of the network and try to execute the code.

```
model = keras.models.Sequential()
model.add(firstLayer(....., input_shape=(height,width,channels))
```

Thank you!
