### ISSUE TITLE
Loading weights as a plain text results in an unexpected output when model.fit is not called

### ISSUE THREAD

**Issue by rs189** [keras-team/keras#18146]
**System information**.
- Windows 10 21H2
- TensorFlow version 2.10.0
- Python version 3.10.11
- GPU model and memory: RTX 2070 8GB

**Describe the problem**.

Loading plain text weights does not work correctly, as it requires me to re-train and re-save weights every time even though I am not directly passing over any model data but rather just saving it and loading it later. (See Google Colab URL comments and code)

**Describe the current behavior**.

Saving the model along with all its layers and JSON configuration to be loaded later, without calling `model.fit` first and then saving the re-trained weights again makes the loaded model unusable. (See Google Colab URL comments and code)

**Describe the expected behavior**.

I expect to be able to load the model along with all its layers and JSON configuration, without calling `model.fit` first and then saving the re-trained weights

**Standalone code to reproduce the issue**.

Google Colab URL with comments and explanations of parts of code -https://colab.research.google.com/drive/1mMGBtZxAc0p7wiD6pJ7F9I-r4yET_wgn?usp=sharing

As described on Google Colab in the last comment, if the model has been trained and `save_model(model)` has been called all as a part of a single runtime execution then are no issues, however, if after training and saving the model with `save_model(model)` we will restart the runtime (Runtime -> Restart runtime), then comment out the training and saving code (`save_model(model)`) before running the runtime again (Runtime -> Run all), the loaded model will become unusable and trying to predict the same outputs will not work (Except for a small random chance that is purely coincidental), even though the saved model configuration and weights are still present inside of the `content/` folder.

An example of expected output whenever training, saving, loading and predicting all as a part of a single runtime is:

Excepted output for "I am" is "trying to reproduce an issue"
Excepted output for "Issue is what" is "I am trying to reproduce"

Whereas an example of broken output whenever first training and saving, then restarting the runtime and just loading and predicting is:

An example of broken output for "I am" is " " (Infinite loop, Empty space, Or other nonsense)
An example of broken output for "Issue is what" is "what" (Infinite loop, Empty space, Or other nonsense)

I did not try but I assume that this would have not been an issue if the model was saved as an h5 or keras instead of plain text, however, for my use case, I really prefer having weights as plain text as I intend to use this model on its own later in C instead of Python without using Keras/TensorFlow.

**Comment by tilakrayal** [comment]
@rs189,
I tried to execute the mentioned code on tf-nightly, and I was able to print the output. Could you please confirm whether you are facing the same issue. Kindly find the [gist](https://colab.research.google.com/gist/tilakrayal/1b3ed3c5359e644e07d94d3f3ad77ed3/plaintextloadsaveexample.ipynb). Thank you!

![image](https://github.com/keras-team/keras/assets/81610181/8da5e34a-b9eb-4821-97db-4a5d702de5f0)

**Comment by tilakrayal** [comment]
@rs189,
Apologies for the delay.
I tried to execute the mentioned code on tf-nightly, in multiple iterations and found that the code was executed and provided the results as mentioned in the colab. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/d525a6a4b6807ab1f12999ef9e9de1bf/plaintextloadsaveexample.ipynb).


**Testing the model, try putting in "I am" or "Issue is what" into the input field.
Excepted output for "I am" is "trying to reproduce an issue" Excepted output for "Issue is what" is "I am trying to reproduce"**


![Screenshot 2023-07-20 12 55 52 PM](https://github.com/keras-team/keras/assets/81610181/a054ff4c-b38d-43a1-b521-aca22bb1c731)
