### ISSUE TITLE
getting Error after merging two Deep Learning models VGG16 and ResNet50

### ISSUE THREAD

**Issue by abani29** [keras-team/keras#18154]
ValueError: Exception encountered when calling layer "vgg16" (type Functional).

Input 0 of layer "block1_conv1" is incompatible with the layer: expected min_ndim=4, found ndim=3. Full shape received: (None, 224, 224)

Call arguments received by layer "vgg16" (type Functional):
  • inputs=tf.Tensor(shape=(None, 224, 224), dtype=float32)
  • training=False
  • mask=None

import imageio
import cv2

import keras
from tensorflow.keras.applications.vgg16 import VGG16, preprocess_input
from keras.applications.resnet_v2 import ResNet50V2
from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import Model
import numpy as np

import cv2
import os
import random
import shutil
import pandas as pd
import csv
#import pydicom as dicom
import zipfile
from keras import optimizers
from keras.models import Sequential,Model
from keras.layers import Dropout, Flatten, Dense,Input
#from keras.applications.resnet_v2 import ResNet50V2
#from keras.applications.exception import Xception
from keras.callbacks import ModelCheckpoint
from keras.applications.imagenet_utils import preprocess_input
from keras import backend as K
from keras.preprocessing.image import ImageDataGenerator
from keras.initializers import RandomNormal
#input_tensor=Input(shape=(224,224,3))
#input=Input(shape=(224,224,1))
#inputs = tf.keras.layers.Input(shape=input_shape)
inputs = tf.keras.layers.Input(shape=(224,224))
model1 = VGG16()
# restructure the model

base_model1 = Model(inputs=model1.inputs, outputs=model1.layers[-2].output)
# summary
features1 = base_model1.output
######################################################################################################
model2=ResNet50V2()
base_model2 = Model(inputs=model2.inputs, outputs=model2.layers[-2].output)
features2 = base_model2.output
 #Concatenate the extracted features
####################################################################################################
combined = tf.keras.layers.Concatenate()([model1(inputs), model2(inputs)])
outputs=keras.layers.concatenate([features1,features2])(combined)
#merge##
#model = tf.keras.models.Model(inputs=[(model1.inputs,model2.inputs)], outputs=concatenated)
#model = tf.keras.models.Model(inputs=input_tensor, outputs=concatenated)
#input=[model1.inputs,model2.inputs]
model = tf.keras.models.Model(inputs, outputs)

print(model.summary())
img_path = 'img-1.png'
img = image.load_img(img_path, target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

features  = model.predict(x)

**Comment by tilakrayal** [comment]
@abani29,
Here in the above mentioned code you are trying to concatenate both VGG16 and Resnet50, where both  are incompatible with the layer: **expected min_ndim=4**, **found ndim=3**. 

The input layers of the model you created needs a 4 dimension tensor to work with but the x_train tensor you are passing to it has only 3 dimensions. This means that you have to reshape your training set with .reshape accordingly. 

You have to use **input_shape = (img_width, img_height, 1)** to indicate that it is a grayscale image, meaning one channel.
https://stackoverflow.com/questions/43895750/keras-input-shape-for-conv2d-and-manually-loaded-images
https://stackoverflow.com/questions/63279168/valueerror-input-0-of-layer-sequential-is-incompatible-with-the-layer-expect

Thank you!
