### ISSUE TITLE
Contradictory behavior of sqrt() and pow() function in keras. 

### ISSUE THREAD

**Issue by bisnu16cse039** [keras-team/keras#18169]
In one place of my code, I have used sqrt function of Keras. sqrt(x) is similar to pow(x,0.5). But I get different behavior. Then I find when sqrt function getting negative values it returning 0 but pow is returning NAN at that case. So it seems contradictory behavior between sqrt() and pow() function in keras.

**Comment by tilakrayal** [comment]
@bisnu16cse039,
math.pow(math.max(epsilon, a) , b)
where epsilon is some small constant like 1e-3 to make sure you don't make something 0 either (because 0^negative is NaN as well).
https://stackoverflow.com/questions/68839035/activation-function-of-tf-math-powx-0-5-leading-to-nan-losses
Thank you!
