### ISSUE TITLE
Adding SophiaH and G optimizers

### ISSUE THREAD

**Issue by thegodone** [keras-team/keras#18174]
Can we add the following Sophia optimizer that looks so impressive for LLM ?

I found 2 pytorch versions. Based on the paper the two options H or G give similar results, H looks simpler to implement.

https://github.com/Liuhong99/Sophia & https://github.com/kyegomez/Sophia

BR

Guillaume

**Comment by tilakrayal** [comment]
@thegodone,
Could you please elaborate or more context about the feature. Also, please specify the Use Cases for this feature. Thank you!

**Comment by thegodone** [comment]
Basically the goal is to have a faster convergence (twice faster) for large models LLM using this method. there is already an issue in the source repo but the Devs is not a keras/tf expert so it will take long time without help him: https://github.com/kyegomez/Sophia/issues/4

**Comment by sachinprasadhs** [comment]
Hi, Thanks for creating the feature request, based on the number of citations(1 as of now), it is too early to implement it in Keras for now.
https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=https%3A%2F%2Farxiv.org%2Fabs%2F2305.14342&btnG=
