### ISSUE TITLE
 How to take some sub-directories from a main directory tf.keras.utils.image_dataset_from_directory

### ISSUE THREAD

**Issue by ARPIT2128** [keras-team/keras#18170]
### How to take some sub-directories from a main directory

- Hello I'm new to this issue stuff 😃 
- Basically I was unable to find a fix for the issue on Stackoverflow so I'm here to ask the experts. 💜 
- Hope I'm not creating a problem for you all will make it short and simple. 😥 

```
def image_dataset_from_directory(
    directory,
    labels="inferred",
    label_mode="int",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(256, 256),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    **kwargs,
):
```   
- HERE IF I ONLY WANT ```class_a``` THEN WHAT TO DO
```
    main_directory/
    ...class_a/
    ......a_image_1.jpg
    ......a_image_2.jpg
    ...class_b/
    ......b_image_1.jpg
    ......b_image_2.jpg
```

![image](https://github.com/keras-team/keras/assets/93235104/57da81b4-a110-45f8-80bd-da353fd4832a)

- As shown in above figure I'm trying to use the tf.keras.utils.image_dataset_from_directory
- But here I want to take some sub directories only and not all like .git files from the main directory
- Previously it was in ```from tensorflow.keras.preprocessing.image import image_dataset_from_directory```
- with parameter ```ignore```
- is there a easy fix for this using this directory or any relevant.
THANKS IN ADVANCE 😉

**Comment by sachinprasadhs** [comment]
Hi,

Thanks for reporting the issue.
I was able to verify the issue in colab.

![image](https://github.com/keras-team/keras/assets/73069040/3dfec35b-f841-42fd-b3c5-a5c8d09f1031)



I have created a PR to handle the hidden folders like `.git , .ipynb` etc.

Coming to your question about ignoring directory with directory name as input is not possible in the current implementation as per my understanding.
