### ISSUE TITLE
TypeError: Unable to serialize [2.0896919 2.1128857 2.1081853] to JSON.

### ISSUE THREAD

**Issue by ngbusca** [keras-team/keras#18218]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras):
No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian 11
- TensorFlow installed from (source or binary): from pip
- TensorFlow version (use command below): 2.12
- Python version: 3.9
- Bazel version (if compiling from source): N/A
- GPU model and memory: Tesla V100-PCIE-16GB
- Exact command to reproduce:
```
m = tf.keras.applications.efficientnet.EfficientNetB1()
m.save("test-save")
```

**Describe the problem**.

Starting with TF 2.10, None of the effientnet models loaded from keras applications can be serialized. The code above works for TF 2.9 but fails for 2.10, 2.11 and 2.12. The issue was reported [on the TF repo](https://github.com/tensorflow/tensorflow/issues/58088) but the response was "go complain to the the keras falks" :)

**Describe the current behavior**.

Trying to save models using efficientnet fails.

**Describe the expected behavior**.

Saving works

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no): no

**Standalone code to reproduce the issue**.

```
m = tf.keras.applications.efficientnet.EfficientNetB1()
m.save("test-save")
```

**Source code / logs**.

```
TypeError                                 Traceback (most recent call last)
Cell In[11], line 1
----> 1 m.save("test-save")

File ~/.local/lib/python3.9/site-packages/keras/utils/traceback_utils.py:70, in filter_traceback.<locals>.error_handler(*args, **kwargs)
     67     filtered_tb = _process_traceback_frames(e.__traceback__)
     68     # To get the full stack trace, call:
     69     # `tf.debugging.disable_traceback_filtering()`
---> 70     raise e.with_traceback(filtered_tb) from None
     71 finally:
     72     del filtered_tb

File /usr/lib/python3.9/json/encoder.py:199, in JSONEncoder.encode(self, o)
    195         return encode_basestring(o)
    196 # This doesn't pass the iterator directly to ''.join() because the
    197 # exceptions aren't as detailed.  The list call should be roughly
    198 # equivalent to the PySequence_Fast that ''.join() would do.
--> 199 chunks = self.iterencode(o, _one_shot=True)
    200 if not isinstance(chunks, (list, tuple)):
    201     chunks = list(chunks)

File /usr/lib/python3.9/json/encoder.py:257, in JSONEncoder.iterencode(self, o, _one_shot)
    252 else:
    253     _iterencode = _make_iterencode(
    254         markers, self.default, _encoder, self.indent, floatstr,
    255         self.key_separator, self.item_separator, self.sort_keys,
    256         self.skipkeys, _one_shot)
--> 257 return _iterencode(o, 0)

TypeError: Unable to serialize [2.0896919 2.1128857 2.1081853] to JSON. Unrecognized type <class 'tensorflow.python.framework.ops.EagerTensor'>.

1
```

**Comment by Frightera** [comment]
This one was fixed in #17498, probably will be included in 2.13 release. The nightly release should work fine.

**Comment by ngbusca** [comment]
Thanks for the reply, I confirm it works on tf-nightly (as of the day of this comment)

**Comment by tilakrayal** [comment]
@ngbusca,
Yeah, It was an issue on tensorflow v2.12. Whereas when I tried to execute the mentioned code on tf-nightly(2.14.0-dev20230611), it was executed without any issue/error. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/6beb13ab643c6004c2c208b8687850bc/untitled1196.ipynb).

As mentioned this change will be reflected in the upcoming tensorflow release.  Below are the changes done on the PR https://github.com/keras-team/keras/pull/17498 which was already merged.

```
       x = layers.Rescaling(
            [1.0 / math.sqrt(stddev) for stddev in IMAGENET_STDDEV_RGB]
        )(x)
```

Could you please feel free to move this issue to closed status, as the issue was resolved on tf-nightly. Thank you!

**Comment by huijunam** [comment]
@tilakrayal thank you for your help👍
