### ISSUE TITLE
Merge IntegerLookup and StringLookup

### ISSUE THREAD

**Issue by RobertKuebler** [keras-team/keras#18225]
Hi!

I'm building a lot of embeddings-based models, and the annoying thing is that I have to specify which of my many features uses which layer, although the logic is the same. Integer features use the integer lookup, string features use the StringLookup. Sure, you can write some boilerplate code to extract the type from the feature and choose the appropriate layer, but can't there just be a **Lookup** layer that takes integers and strings?

For the Hashing layer, it also works. You can give it integers or strings, and it just hashes it to integers between 0 and #buckets.

Thanks a lot!

PS: Tensorflow 2.12.0, not able to contribute.

Best
Robert

**Comment by tilakrayal** [comment]
@RobertKuebler,
Could you please elaborate about your Feature. Also, please specify the Use Cases for this feature. Thank you!

**Comment by RobertKuebler** [comment]
Heya!

Imagine that you have a dataset with two features
- N (some numbers, but categorical, int64 type) and 
- S (some strings, also categorical, string type).

I want to create embeddings for both features, and for this, I have to use the Lookup layers before. In order to get embeddings for N, I need to use the IntegerLookup before the EmbeddingLayer. For S, I need StringLookup instead of the IntegerLookup. So I have to write some boilerplate code before (if feature is numeric, use IntegerLookup, if feature is a string, use StringLookup).

I could use the Hashing layer for both N and S because this layer doesn't care. And I just wanted to ask if there could be a generic Lookup layer that can deal with integers and strings.

Thanks a lot!

**Comment by fchollet** [comment]
Thanks for the request.

> can't there just be a Lookup layer that takes integers and strings

Well, there is, but it is internal. The reason we prefer for the interface to lookup layers to be type-specific is that it is much easier to reason about the program's behavior, which minimizes errors. It's like static typing.

If you really want such a type-agnostic layer, it's easy to make one for your own codebase, leveraging the existing `IntegerLookup` and `StringLookup` layers.
