### ISSUE TITLE
Problem with shape comparison when using from_config

### ISSUE THREAD

**Issue by bluddy** [keras-team/keras#18227]
I'm translating from Onnx to Keras and trying to create an Add or Concat layer that combines a tensor and a layer output as input. Creating these layers works fine at first, but when trying to recreate the graph from a config file produced by Keras, shape checking fails. It appears that the shape of the constant tensor, which should be (1,63), is deduced to be something like (1, (), (), ()... 63 times). A simple example follows. It doesn't fail in the exact same way as my more complex example, but should indicate what goes wrong.

```
import tensorflow as tf
import numpy as np

input1 = tf.keras.layers.Input(shape=(63,))
x1 = tf.keras.layers.Dense(63, activation='relu')(input1)
x3 = tf.random.normal((1, 63))
x3 = tf.keras.backend.constant(x3)
added = tf.keras.layers.Add()([x1, x3])
model = tf.keras.models.Model(inputs=[input1], outputs=added)
config = model.get_config()
model2 = tf.keras.Model.from_config(config)

print(model2)
```

**Comment by tilakrayal** [comment]
@bluddy,
Could you please provide the error log for the mentioned above code which helps to debug the issue. Thank you!
