### ISSUE TITLE
Clipping `steps_per_epoch` to len(dataset) if user provided value is greater

### ISSUE THREAD

**Issue by mayureshagashe2105** [keras-team/keras#18232]
**System information**.

TensorFlow version (you are using):2.12.0
Are you willing to contribute it (Yes/No) :Yes

**Describe the feature and the current behavior/state**.

This issue is related to [TF#58966](https://github.com/tensorflow/tensorflow/issues/58966)

When `tf.data.Dataset` object is passed in `model.fit()` method, and if the value of `steps_per_epoch` or `validation_steps` exceeds `len(dataset)` current implementation logs a warning about the iterator running out of the data and training/validation of data is only performed only once and training/validation stops prematurely. In this case, I'd expect that validation/training is simply performed across the entire dataset every epoch. 

**Will this change the current api? How?**

`steps_per_epoch` is being inferred by [`DataHandler.infer_steps`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/engine/data_adapter.py#LL1311C5-L1311C5) method. If a user provides a value to the arg `steps_per_epoch`/`validation_steps` it is simply returned by the current method implementation.
If step_size > `len(dataset)` then this line [`next(iterator)`](https://github.com/tensorflow/tensorflow/blob/720f89ab4606b2be8bd3659a229c23cb2c0cb2ad/tensorflow/python/keras/engine/training.py#L1318) will throw `StopIteration` error which is causing `DataHandler._insufficient_data` to set to True and the training/validation stops. 

To solve this, while inferring the step value, via [`DataHandler.infer_steps`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/engine/data_adapter.py#LL1311C5-L1311C5) method, we can clip the args value to min(user-provided-value, len(dataset)) if the cardinality of the dataset in not INFINITY, and the API should log a warning about this clipping process.

**Who will benefit from this feature?**
Anyone using tf.data.Dataset with model.fit(). If the value of the arg is passed greater than the length of the dataset it will stop the training/validation process prematurely so this patch might help in avoiding this.

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**

- Do you want to contribute a PR? (yes/no):Yes
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing):

**Comment by sachinprasadhs** [comment]
Thanks for reporting an issue,

I was able to replicate the reported issue with toy example here https://gist.github.com/sachinprasadhs/2e1c5d98c894a5952fb1d3c0ff09c7d3.

Also, there is a similar issue reported here https://github.com/tensorflow/tensorflow/issues/36539

**Comment by haifeng-jin** [comment]
Hi @sachinprasadhs, thanks for the issue.
We would prefer users not relying on any behavior of the framework when they encounter this use case.
The best way is to reduce the `step_per_epoch` when they see the warning message.

So we prefer not change the behavior in this case. Thanks!
