### ISSUE TITLE
model fit method | validation_batch_size needs to be defined when validation data is in the form of generators and different from the training batch size

### ISSUE THREAD

**Issue by angelo-ml** [keras-team/keras#18252]
Hello,
I use Tensorflow 2.6.2

**Describe the problem**.

Let's say that I define two different generators for validation and training data like this:
`train_gen = batch_generator(train_data, train_labels, batch_size=train_batch, epochs=epochs)`
`val_gen = batch_generator(test_data, test_labels, batch_size=val_batch, epochs=epochs)`

and I use them on the model fit method like this
`model.fit(train_gen, steps_per_epoch=train_steps, epochs=train_epochs, validation_data=val_gen, validation_steps=val_steps)`

According to the documentation, in this case the parameter validation_batch_size it doesn't need to be specified:

> **validation_batch_size**: Integer or None. Number of samples per validation batch. If unspecified, will default to batch_size. Do not specify the validation_batch_size if your data is in the form of datasets, generators, or keras.utils.Sequence instances (since they generate batches).

However, if I don't specify it, the method assumes that the validation batch size is the same with the training batch size. As a result it produces the warning.

> WARNING:tensorflow:Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches (in this case, 25 batches). You may need to use the repeat() function when building your dataset.

By specifying the parameter _validation_batch_size_, the method has the expected behaviour.

**Comment by tilakrayal** [comment]
@angelo-ml,
Could you please provide the complete standalone code to reproduce the issue and helps us to analyse the issue in an effective way. Thank you!
