### ISSUE TITLE
Performance issue with Keras 2.13.1 / Tensorflow 2.13.0

### ISSUE THREAD

**Issue by nhuet** [keras-team/keras#18301]
I noticed performance degradation since last release (Keras 2.13.1 / Tensorflow 2.13.0).
I managed to find a very simple example involving only a sum of inputs. The computation time is much worse (4x slower) with last release.

Here is my minimal example:

```python
import time

from tensorflow.keras import Input


number_of_executions = 3000

x = Input((1,))
y = Input((1,))

start = time.time()
for i in range(number_of_executions):
    x + y
duration = time.time() - start
print(f"Duration: {duration:.1f}")
```

I am using the CPU version of tensorflow installed with pip, on a linux machine, python 3.9.
And the code run more than **4 times longer** with tensorflow==2.13.0/keras==2.13.1 compared to tensorflow==2.12.1/keras==2.12.0 !

- tensorflow==2.13.0/keras==2.13.1: around 24 s
- tensorflow==2.12.1/keras==2.12.0: around 6 s

Do you think this is related to Keras or to Tensorflow?

**Comment by nhuet** [comment]
As suggested by @grasskin on corersponding tensorflow [issue](https://github.com/tensorflow/tensorflow/issues/61363#issuecomment-1654059193), I testes with keras-core which will supersed keras in the near future. And the bug disappear. (Actually, the test is 20x faster even than with keras 2.12). So the "bug" seems really to be with keras 2.13 and not with tensorflow 2.13.

My timings:
- keras 2.12.0 + tensorflow 2.12.1: 7.8 s
- keras 2.13.1 + tensorflow 2.13.0: 24.1 s
- keras-core 0.1.3 + tensorflow 2.12.1: 0.4 s
- keras-core 0.1.3 + tensorflow 2.13.0: 0.3 s

(and even increasing the number of iteration, there is not noticeable differences between keras-core + tf2.12 or keras-cre + tf2.13)

**Comment by sachinprasadhs** [comment]
Hi, 

Thanks for confirming the improved performance behavior in `keras-core`. 

Since `keras-core` will be part of keras in the keras 3.0 release, which is planned for the fall of 2023.
 Feel free to close this issue since `keras-core` will become the source of truth.
