### ISSUE TITLE
Keras.callbacks.ModelCheckpoint doesn't work

### ISSUE THREAD

**Issue by maxkskhor** [keras-team/keras#18312]
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.13.0
- Python version: 3.10.9
- GPU model and memory: n/a
- Exact command to reproduce: n/a

**Describe the problem**.
ModelCheckpoint doesn't work.

**Describe the current behavior**.
Threw `ValueError: The following argument(s) are not supported with the native Keras format: ['options']`

**Describe the expected behavior**.
ModelCheckpoint should not throw this ValueError.

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no): No

**Standalone code to reproduce the issue**.
```
import tensorflow
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist

assert tensorflow.__version__ == '2.13.0'

inputs = keras.Input(shape=(28, 28, 1))
x = layers.Conv2D(filters=32, kernel_size=3, activation="relu")(inputs)
x = layers.MaxPooling2D(pool_size=2)(x)
x = layers.Conv2D(filters=64, kernel_size=3, activation="relu")(x)
x = layers.MaxPooling2D(pool_size=2)(x)
x = layers.Conv2D(filters=128, kernel_size=3, activation="relu")(x)
x = layers.Flatten()(x)
outputs = layers.Dense(10, activation="softmax")(x)
model = keras.Model(inputs=inputs, outputs=outputs)

(train_images, train_labels), (val_images, val_labels) = mnist.load_data()
train_images = train_images.reshape((60000, 28, 28, 1))
train_images = train_images.astype("float32") / 255
val_images = val_images.reshape((10000, 28, 28, 1))
val_images = val_images.astype("float32") / 255

callbacks = [
    keras.callbacks.ModelCheckpoint(
        filepath="convnet_mnist.keras",
        save_best_only=True,
        monitor="val_loss",
        )
]

model.compile(optimizer="rmsprop",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"])

model.fit(train_images, train_labels, 
          epochs=5, 
          batch_size=64, 
          callbacks=callbacks, 
          validation_data=(val_images, val_labels)
         )
```

**Source code / logs**.
```
Epoch 1/5
937/938 [============================>.] - ETA: 0s - loss: 0.1624 - accuracy: 0.9490
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[10], line 37
     24 callbacks = [
     25     keras.callbacks.ModelCheckpoint(
     26         filepath="convnet_mnist.keras",
   (...)
     29         )
     30 ]
     33 model.compile(optimizer="rmsprop",
     34     loss="sparse_categorical_crossentropy",
     35     metrics=["accuracy"])
---> 37 model.fit(train_images, train_labels, 
     38           epochs=5, 
     39           batch_size=64, 
     40           callbacks=callbacks, 
     41           validation_data=(val_images, val_labels)
     42          )

File ~\workarea\Program\anaconda3\lib\site-packages\keras\src\utils\traceback_utils.py:70, in filter_traceback.<locals>.error_handler(*args, **kwargs)
     67     filtered_tb = _process_traceback_frames(e.__traceback__)
     68     # To get the full stack trace, call:
     69     # `tf.debugging.disable_traceback_filtering()`
---> 70     raise e.with_traceback(filtered_tb) from None
     71 finally:
     72     del filtered_tb

File ~\workarea\Program\anaconda3\lib\site-packages\keras\src\saving\saving_api.py:142, in save_model(model, filepath, overwrite, save_format, **kwargs)
    140             return
    141     if kwargs:
--> 142         raise ValueError(
    143             "The following argument(s) are not supported "
    144             f"with the native Keras format: {list(kwargs.keys())}"
    145         )
    146     saving_lib.save_model(model, filepath)
    147 else:
    148     # Legacy case

ValueError: The following argument(s) are not supported with the native Keras format: ['options']
```

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by tilakrayal** [comment]
@maxkskhor,
**tf.keras.callbacks.ModelCheckpoint** currently does not support the native keras format and saved_model/hdf5 has been deprecated. I tried to execute the mentioned code in an alternative approach by providing the filepath as `convnet_mnist.h5 and convnet_mnist` and it is working without any issue/error. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/91112e4e49d2827194d5cddfb691767d/untitled1270.ipynb).

**filepath**: string or PathLike, path to save the model file. e.g. filepath = os.path.join(working_dir, 'ckpt', file_name). filepath can contain named formatting options, which will be filled the value of epoch and keys in logs (passed in on_epoch_end). For example: if filepath is weights.{epoch:02d}-{val_loss:.2f}.hdf5, then the model checkpoints will be saved with the epoch number and the validation loss in the filename. The directory of the filepath should not be reused by any other callbacks to avoid conflicts.

https://keras.io/api/callbacks/model_checkpoint/

Thank you!

**Comment by maxkskhor** [comment]
@tilakrayal Thank you for your time! It worked in both cases.

On a side note, I have got this warning, which can be misleading in this case:
```
UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.saving_api.save_model(
```

**Comment by jerrykuch** [comment]
So about the `UserWarning` that @maxkskhor described "misleading."  What's the understanding that one should take away from the current state of things?  Is HDF5 considered "legacy", deprecated and not recommended for further use?  If so, is it likely that saving in native Keras format by suffixing the file name in the `ModelCheckpoint` callback with ".keras" will be fixed to work again, since it used to do so?

**Comment by EdIzaguirre** [comment]
I am also confused, more or less same questions as @jerrykuch. Is this a temporary bug that will be fixed, or is keras moving away from the .keras format?
