### ISSUE TITLE
Addition of another model (alexnet) to the applications list

### ISSUE THREAD

**Issue by aarda55** [keras-team/keras#18321]
**System information**.

TensorFlow version (you are using): 2.12.0
Are you willing to contribute it (Yes/No) : Yes

**Describe the feature and the current behavior/state**.
Adding of the CNN-model alexnet would increase the diversity of models from which users can choose from. Currently there are already multiple CNN-models but this would simply increase diversity.

**Will this change the current api? How?**
It will only minimally change it thorugh the option of using another CNN-model whith pre-trained weight and/-or fine-tune it yourself.

**Who will benefit from this feature?**
Keras users that use the pre-trained models

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**

- Do you want to contribute a PR? (yes/no): yes
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing): addition of alexnet model with the needed integration

**Comment by tilakrayal** [comment]
@aarda55,
Could you please elaborate about your Feature. Also, please specify the Use Cases for this feature, it helps to analyse the issue/feature in an effective way. Thank you!

**Comment by aarda55** [comment]
@tilakrayal,
this contribution would go to the pre-trained application library of Keras and the model i want to add is called Alexnet (Reference: [Very Deep Convolutional Networks for Large-Scale Image Recognition] (https://papers.nips.cc/paper_files/paper/2012/file/c399862d3b9d6b76c8436e924a68c45b-Paper.pdf) (NIPS 2012)). This is another Convolutional Neural Network. It is not a new feature per se but rather an addition to the amount of pre-trained models keras has to offer. It would use Imagenet pre-trained weights or could be fine-tuned by the user himself. The use case would be image recognition. So this contribution won't change the way the api function and only increases the amount of models the user can choosee from because all model have their advantages and disadvantages. I thank you and for reference look at the implementation of VGG16 or VGG19 in the pre-trained library!

**Comment by nkovela1** [comment]
Hi @aarda55 , in general we are planning to keep only the latest models in Keras to guide users towards modern best practices as much as possible. As a result, we will not accept AlexNet to our repositories as it is a historic model.

In the future for e2e model implementations like these, please open issues/PRs in KerasCV and KerasNLP for CV and NLP models, respectively. Thanks!
