### ISSUE TITLE
cannot import name 'np_utils'

### ISSUE THREAD

**Issue by faithful-dragon** [keras-team/keras#18363]
import keras
from keras.utils import np_utils

can not import even after installing np_utils using pip command in Jupyter notebook

**Comment by tilakrayal** [comment]
@faithful-dragon,
In the public API, you cannot access np_util (it's internal). You are supposed to access utilities via the utils module, e.g.

```
from keras import utils

utils.to_categorical(...)
```

https://stackoverflow.com/questions/45149341/importerror-cannot-import-name-np-utils

Thank you!

**Comment by faithful-dragon** [comment]
Thank You
