### ISSUE TITLE
TF 2.x Feature: Flops calculation

### ISSUE THREAD

**Issue by innat** [keras-team/keras#18378]
Reopening from 

- https://github.com/keras-team/keras/issues/16699
- https://github.com/tensorflow/tensorflow/issues/32809
- https://github.com/keras-team/keras/issues/12970
- https://github.com/keras-team/keras/issues/5625
- https://github.com/tensorflow/tensorflow/issues/39834

Currently the adopted solutions (from community)

```python
import tensorflow as tf
from tensorflow.python.profiler import model_analyzer, option_builder

model = tf.keras.applications.Xception(
    weights='imagenet',
    input_shape=(150, 150, 3),
    include_top=False
) 

input_signature = [
    tf.TensorSpec(
        shape=(1, *params.shape[1:]), 
        dtype=params.dtype, 
        name=params.name
    ) for params in model.inputs
]
forward_graph = tf.function(model, input_signature).get_concrete_function().graph
options = option_builder.ProfileOptionBuilder.float_operation()
graph_info = model_analyzer.profile(forward_graph, options=options)
flops = graph_info.total_float_ops // 2
flops # 1925897756 
```

**Comment by divyashreepathihalli** [comment]
This issue  does not seem to be related to keras.
Please file TF related issues here - https://github.com/tensorflow/tensorflow/issues

**Comment by innat** [comment]
@divyashreepathihalli 
> This issue does not seem to be related to keras.

How come? How did you evaluate it is not fit here?

I updated the title, it is not about tf 2 only but for all backed, tf, torch, jax.
