### ISSUE TITLE
Add a dedicated file for Keras' security policy

### ISSUE THREAD

**Issue by pnacht** [keras-team/keras#18384]
**Describe the feature and the current behavior/state**.

Keras' security policy is currently at the very end of `CONTRIBUTING.md`. I suggest this information be moved to a dedicated `SECURITY.md` file.

GitHub treats `SECURITY.md` as a special file. If it exists in your repository, a new "issue type" is created that redirects users to the policy if they've discovered a vulnerability. The policy also appears in the project's [Security Panel](https://github.com/keras-team/keras/security).

Alternatively, the policy can also be added to the https://github.com/keras-team/.github repository. This will be treated as the default policy for all projects in the keras-team organization.

**Will this change the current api? How?**
No.

**Who will benefit from this feature?**
Security researchers will have an easier time safely reporting vulnerabilities, therefore increasing Keras' overall security.

- Do you want to contribute a PR? (yes/no): YES

- Briefly describe your candidate solution(if contributing):

I will simply move the security policy to a `SECURITY.md` file at the root of the repository.

I would have preferred to send this PR to the keras-team/.github repository (therefore applying the policy to all repos), but since the repository is empty, I cannot create a fork and send a PR there.

**Comment by divyashreepathihalli** [comment]
@pnacht thanks for filing the issue, this sounds reasonable. Just approved the PR.
