### ISSUE TITLE
List and dictionary dependencies not properly tracked on tensorflow backend

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras#18398]
On the tensorflow backend our `Layer` is a tf `AutoTrackable`, which allows `tf.save_model` and `tf.train.Checkpoint` to work by tracking all sublayers, variables, etc.

However keras-core `Tracker` and `AutoTrackable` conflict for dictionaries and lists. Our `Tracker` creates specialized `list` and `dict` subclasses, which tensorflow refuses to track with `AutoTrackable`. `AutoTrackable` will only track children if `type(child) == list` or `type(child) == dict`.

The net effect is `tf.save_model` and `tf.train.Checkpoint` will not work for layers with list/dictionary sublayers or weights. Here's a repro.

https://colab.research.google.com/gist/mattdangerw/be42f510562906925985e2954db9c8e8/tf-saving-bug.ipynb

**Comment by nkovela1** [comment]
FIxed in #18507
