### ISSUE TITLE
Tensorflow 2.14 breaks dictionary output from a functional model

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras#18399]
When tf 2.14 releases, we will face a bug with dictionary output from a functional model.

https://colab.research.google.com/gist/mattdangerw/019d1ebcec746d6f7424248911cf16ae/tf-2-14-bug.ipynb

I am not sure this will show up on a colab right away, as it actually depends on the specific version of `typing-extensions` (this is a pretty obtuse bug). But we will see this in a clean pip environment which picks up the latest `typing-extensions`.

After the 2.14 release:
- Clean install keras-core and tensorflow in a pip environment.
- Attempt to write a functional model with dictionary output.
- Any compiled functions (e.g. predict, fit), will fail.

**Comment by sachinprasadhs** [comment]
I think we can close this issue since it has no problem with the Keras 3 with the below code.

```python
import keras

batch = keras.ops.ones((2, 1))
inputs = keras.Input(shape=(1,))
outputs = {
    "sum": keras.layers.Add()((inputs, inputs)),
    "diff": keras.layers.Subtract()((inputs, inputs)),
}
model = keras.Model(inputs, outputs)
model.predict(batch)
```
