### ISSUE TITLE
Fine-tuned Torch model weights not updating when wrapped with Keras `TorchModuleWrapper`

### ISSUE THREAD

**Issue by ariG23498** [keras-team/keras#18395]
I am trying to fine tune a torch model using the `keras.Model` API. I am aware that if we pass a torch model inside the `__init__` of the `keras.Model` subclass, the torch model will be wrapped with the `TorchModuleWrapper`.

After I fine tune the `keras.Model` (using `model.fit`) I would like to extract the torch model and save the state of the trained torch model in a `pth` format.

I have a [colab notebook](https://colab.research.google.com/gist/ariG23498/e87635e09f57b31609cd7c5d8ca60028/scratchpad.ipynb) that demos the entire workflow. The problem that I am facing is with the `sate_dict()` of the wrapped torch model. It shows that the parameters are not trained at all (the initial state and the trained states are the same).

Any pointers on this would be great.

CC: @soumik12345

**Comment by kernel-loophole** [comment]
HI @ariG23498  after running your colab notebook .find that there is issue with optimizer .if you change the optimizer as below ,this will work.I change the optimizer to  RMSprop .After changing the optimizer weight are updated accordingly .Here is part of code which I update .
```
pytorch_model = resnet18(weights=None, num_classes=10)
model = KerasCoreModel(pytorch_model=pytorch_model)
model.compile(
    optimizer="RMSprop",
    loss="sparse_categorical_crossentropy",
)
```

**Comment by ariG23498** [comment]
> HI @ariG23498 after running your colab notebook .find that there is issue with optimizer .if you change the optimizer as below ,this will work.I change the optimizer to RMSprop .After changing the optimizer weight are updated accordingly .Here is part of code which I update .
> 
> ```
> pytorch_model = resnet18(weights=None, num_classes=10)
> model = KerasCoreModel(pytorch_model=pytorch_model)
> model.compile(
>     optimizer="RMSprop",
>     loss="sparse_categorical_crossentropy",
> )
> ```

Hi @kernel-loophole I still do not think the problem that I am having here is solved with the change in the optimizer. My main issue is to unwrap the `resnet18` model into the torchvision format and save it in `pth`. To do this, I would either need to know which parameters are trained (learned) after I fine tune the `keras.Model`.

**Comment by kernel-loophole** [comment]
I think you can identify which parameters are learned (trained)  Once you have identified the trained parameters, you can convert your Keras model to a PyTorch model and save it as a .pth file.

**Comment by ariG23498** [comment]
> I think you can identify which parameters are learned (trained) Once you have identified the trained parameters, you can convert your Keras model to a PyTorch model and save it as a .pth file.

You are absolutely right with the approach. I had a similar idea to being with. In the colab notebook I show that the initial states and trained states are all equal (that means they were not trained). I was unable to identify which varaibles are trained and how to load them to the same `state_dict` like structure to later save.

If you have any pointers on it, that would be of great help 😄

**Comment by ariG23498** [comment]
Interesting can you share your colab notebook -- I cannot reproduce what you claim here. It must be something that I am missing.

**Comment by kernel-loophole** [comment]
Yeah sure .here it is 
https://colab.research.google.com/gist/ariG23498/e87635e09f57b31609cd7c5d8ca60028/scratchpad.ipynb

**Comment by ariG23498** [comment]
Thanks for the colab! The problem now is that the name of the keys do not match. There is also a descripancy with the shape of the variables.

Did you find a way to mitigate that?

**Comment by kernel-loophole** [comment]
Hi there,you can map the keys.check both Before and after dict keys if key is missing append that key to dict.

**Comment by sampathweb** [comment]
@ariG23498 - Is this still an open issue?

**Comment by ariG23498** [comment]
Yep!

I do not have a fix to this yet.

**Comment by fchollet** [comment]
I think we'd need a PyTorch export to debug this. It seems the PyTorch parameter in the Module is not the same as the one used by Keras. The origin likely in the `TorchModuleWrapper._track_module_parameters` method. Can anyone look into it?

**Comment by fchollet** [comment]
I believe the issue should be fixed at this point. Looking at the code snippet, I'm seeing the following:

```
val = np.allclose(
    init_state_kv[1],
    raw_state_kv[1],
    rtol=1e-05,
    atol=1e-08,
)
print("init_state_kv == raw_state_kv", val)
val = np.allclose(
    raw_state_kv[1],
    module_state_kv[1],
    rtol=1e-05,
    atol=1e-08,
)
print("raw_state_kv == module_state_kv", val)
```
->
```
init_state_kv == raw_state_kv False
raw_state_kv == module_state_kv True
# (for all variables)
```

That implies that the state has been updated and that the Model's state reflects the wrapped Module's state.

For initial state I used `initial_state = copy.deepcopy(pytorch_model.state_dict())` taken after instantiation.

Please check that it works for you.
