### ISSUE TITLE
Add integration test that jax, torch and tensorflow are all optional

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras#18401]
As of https://github.com/keras-team/keras-core/pull/475, we should be able to run on any backend, without the other backend packages installed on the system (e.g. run with the jax backend without the torch and tf packages).

However this is super fragile as any unconditional import or `torch`, `jax` or `tensorflow` outside of the `backend` module itself will break the optionality.

We really need a integration test here, that builds our package, loads it up in each backend without the other backends available, and makes sure nothing blows up.

**Comment by nkovela1** [comment]
Added this integration test (#18491) and added it to CI (#18513).
