### ISSUE TITLE
ArrayDataAdapter will needlessly convert backend native tensors

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras#18408]
Given the following snippet on the tf backend....

```
x = tf.ones((1000, 2))
y = tf.ones((1000,))
model.fit(x, y, batch_size=8)
```

The [ArrayDataAdapter](https://github.com/keras-team/keras-core/blob/main/keras_core/trainers/data_adapters/array_data_adapter.py) will convert all `tf.Tensor` inputs to `np.array`, before converting them back to the `tf.Tensor` format. The same roundtrip through `np.array` is true for jax and torch tensors on the respective backends.

This seem inefficient. We should benchmark if this is causing a slowdown on any backend, and fix if necessary.

**Comment by haifeng-jin** [comment]
I will work on this as I resolve PyTorch backend memory issues.

**Comment by hertschuh** [comment]
Fixed with https://github.com/keras-team/keras/pull/19298
