### ISSUE TITLE
Add `EmbeddingBag` layer to keras-core

### ISSUE THREAD

**Issue by shivance** [keras-team/keras#18418]
(Do we have it already?)

It would be good to add a EmbeddingBag layer to keras like pytorch https://pytorch.org/docs/stable/generated/torch.nn.EmbeddingBag.html.

It used to be there in [tensorflow-addons](https://www.tensorflow.org/addons/api_docs/python/tfa/layers/EmbeddingBag), but the package is deprecated now. If this proposal is accepted, I'm up for contributing this.

**Comment by KossaiSbai** [comment]
Happy to look into this

**Comment by wangzhe258369** [comment]
In the recommendation system, the input layer of the model needs to convert multi-value features into a single embedding vector through EmbeddingBag.
