### ISSUE TITLE
Keras Core on H100

### ISSUE THREAD

**Issue by kapoorlab** [keras-team/keras#18429]
Hello to the developers of wonderful Keras-Core framework, I really want to deploy it for our users of the HPC, but we have not been able to find a tensorflow installation that can work with CUDA capability offered by Nvidia H100 GPUs. 

The latest pytorch version does support H100 GPUs but without a working tensorflow installation we are unable to repackage and deploy our tensorflow codes as keras-core packages. If we could get a working tensorflow for H100 then it would be great for us as we can then use our pytorch dataloaders and trainers in conjunction with other codes that are written using tensorflow and Jax.

Is the tensorflow going to come out with a new version that works on H100 soon? or is there a workaround offered by the keras-core team?

**Comment by sachinprasadhs** [comment]
@kapoorlab , Feel free to close the issue if you don't have any other concern.
`TensorFlow` also now supports H100 https://github.com/tensorflow/tensorflow/issues/60739
