### ISSUE TITLE
MultiHeadAttention is missing a position_bias call argument, making Alibi or T5-style position embedding impossible to implement

### ISSUE THREAD

**Issue by martin-gorner** [keras-team/keras#18423]
[Alibi](https://arxiv.org/abs/2108.12409) or T5 relative position embeddings modify the attention computation instead of being simply added to token embeddings.

The [T5 implementation of MultiHeadAttention](https://github.com/tensorflow/models/blob/98dab0626d2448baeb6ecbc88b6709b5da0f1cd5/official/nlp/modeling/models/t5.py#L655) has a position_bias argument that allows this.

The [Keras MultiHeadAttention](https://github.com/keras-team/keras-core/blob/32d1dbe6d8d287116240c76b109f2ab2aaf5e005/keras_core/layers/attention/multi_head_attention.py#L380) seems to be missing this argument.

Without this, I don't think that implementing T5-style or Alibi relative position embeddings is possible.

**Comment by sachinprasadhs** [comment]
With the addition of [GroupedQueryAttention](https://keras.io/api/layers/attention_layers/group_query_attention/) layer if the concern of this issue is addressed, feel free to close the issue. Thanks!
