### ISSUE TITLE
Verbose overloads terminal output

### ISSUE THREAD

**Issue by emi-dm** [keras-team/keras#18427]
I have been experiencing problems when running training scripts via terminal. The output provided by the fit method overloads the terminal.

![image](https://github.com/keras-team/keras-core/assets/140513018/80b3edb8-a129-4ada-b439-471dc8c4325b)

**Comment by sachinprasadhs** [comment]
Hi, 

Could you please provide more context on the issue you are facing, reproducible code would help us investigate more.

Also, try with the latest Keras version and confirm if the issue still exists.
