### ISSUE TITLE
Histograms in Tensorboard

### ISSUE THREAD

**Issue by AakashKumarNain** [keras-team/keras#18433]
I was training a few models, and for debugging something I wanted to use Tensorboard. For me, the use-case was to look for the histograms of the weights for each layer in the network. When I added the callback to the training loop, this is what I get:

<img width="1780" alt="Screenshot 2023-07-21 at 10 42 49 PM" src="https://github.com/keras-team/keras-core/assets/11736571/20cf9442-ebbc-4808-a63b-850b4b142ea8">

<br>

**Expected behavior**: The histogram plot should display the distribution of weights, and biases(if any) separately for each layer in the model.

cc: @sampathweb

**Comment by sachinprasadhs** [comment]
@AakashKumarNain , Feel free to close the issue if you do 't have any follow-up question.

**Comment by miticollo** [comment]
I would want to try to propose a solution.

IMO an easy and less error-prone solution could be the following:
1. Replace [this line](https://github.com/keras-team/keras/blob/cb6ece3e2ead7baec874cb71e579fbf310b1b05c/keras/src/callbacks/tensorboard.py#L550) with
    ```python
    weight_name = weight.path.replace(":", "_")
    ```
    Checking [this TensorBoard guide](https://github.com/tensorflow/tensorboard/blob/9646de3fb47d0a0198ac34d16739ba0a8d17bf31/docs/r1/histograms.md) this is possible.
 2. Replace [this line](https://github.com/keras-team/keras/blob/cb6ece3e2ead7baec874cb71e579fbf310b1b05c/keras/src/callbacks/tensorboard.py#L554) with
     ```python
     histogram_weight_name, weight, step=epoch, description=f"This KerasVariable belongs to **{layer.name}**"
     ```
     or another [`description`](https://github.com/tensorflow/tensorboard/blob/9646de3fb47d0a0198ac34d16739ba0a8d17bf31/tensorboard/plugins/histogram/summary_v2.py#L160-L161).
     
Anyway I don't know if this is a satisfying solution.
