### ISSUE TITLE
TODO: add docstrings on all `keras_core.operations` functions

### ISSUE THREAD

**Issue by fchollet** [keras-team/keras#18469]
All exported functions in the `keras_core.operations` namespace should have docstrings, with an `Args:` section and a `Returns:` section, and a code example.

**Comment by sachinprasadhs** [comment]
Can we close this issue, since the changes are made in Keras 3 code https://github.com/keras-team/keras/commit/a6ddf604714cd5a4ea6da9001ba2d996d2a3fd0b
