### ISSUE TITLE
Conversion script from tf.keras to Keras Core

### ISSUE THREAD

**Issue by fchollet** [keras-team/keras#18472]
We should release a conversion script that takes as input a Python file, and does the following:

- Replace all `tf.keras` imports with `keras_core` imports
- For every tentatively imported `keras_core` object, checks whether it is present in the API, and warn if not.
- Check for other features that were removed in Keras Core but that won't be obvious at the import level, like `add_metric` and `add_loss`.
- For some of the missing objects, provide helpful tips for what to do (e.g. instead of using a symbolic `add_loss`, call it in a layer subclass).

**Comment by sachinprasadhs** [comment]
Can we close this issue, since we have `Keras 3` with all the changes mentioned above.
