### ISSUE TITLE
Add `pad_to_bounding_box` & `crop_to_bounding_box` image ops

### ISSUE THREAD

**Issue by awsaf49** [keras-team/keras#18489]
Both of these layers are used in many `keras.io/examples`. I think it would be nice to have this features in Keras 3.0.

Reference:
1. `pad_to_bounding_box`: [link](https://github.com/tensorflow/tensorflow/blob/v2.13.0/tensorflow/python/ops/image_ops_impl.py#L1002-L1066)
2. `crop_to_bounding_box`: [link](https://github.com/tensorflow/tensorflow/blob/v2.13.0/tensorflow/python/ops/image_ops_impl.py#L1162-L1264)

**Comment by sachinprasadhs** [comment]
Hi, Since the linked PR is merged, is this issue good to close?

**Comment by awsaf49** [comment]
Hi, actually half part is done as `corp_to_bounding` box is yet to be added. I will start working on it soon.
