### ISSUE TITLE
`keras.config.disable_traceback_filtering()` does not work

### ISSUE THREAD

**Issue by suvadityamuk** [keras-team/keras#18506]
Calling the function `keras.config.disable_traceback_filtering()` returns the following traceback. This is in a Colaboratory environment.

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-34-95177c516946>](https://localhost:8080/#) in <cell line: 1>()
----> 1 keras.config.disable_traceback_filtering()

AttributeError: module 'keras' has no attribute 'config'
```

**Comment by fchollet** [comment]
`keras.config.disable_traceback_filtering()` is a Keras 3 API. In Keras 2 you can use `tf.debugging.disable_traceback_filtering()`.

**Comment by suvadityamuk** [comment]
Oh no, I was using Keras 3. Please find a more detailed screenshot below.
![image](https://github.com/keras-team/keras/assets/70141886/51cab8a6-9e26-4ea1-9020-5304c9e0ee6d)

My installation cell is below
```shell
!git clone https://github.com/keras-team/keras.git
%cd keras
!pip install -qq namex
!apt install python3.10-venv
!pip install -r requirements-cuda.txt
!python pip_build.py --install
```
