### ISSUE TITLE
Adding resnet34/resnet18 from the resnet paper to tensorflow keras

### ISSUE THREAD

**Issue by Algorithmist-Girl** [keras-team/keras#18508]
Thinking of adding resnet34/resnet18 from the resnet paper, https://arxiv.org/abs/1512.03385, to tensorflow keras. it would be great if a tensorflow team committee member could just confirm this change is good for me to work on

**Comment by grasskin** [comment]
Hi @Algorithmist-Girl, thank you for your interest in contributing! Unfortunately, Resnet34 and Resnet18 are not models we are currently looking to add. Additionally, they are already available with KerasCV: https://keras.io/api/keras_cv/models/backbones/resnet_v1/.
