### ISSUE TITLE
ValueError: The `pool_size` argument must be a tuple of 1 integers. Received: Tensor("custom_model_14/Ceil:0", shape=(), dtype=float64)

### ISSUE THREAD

**Issue by innat** [keras-team/keras#18512]
## Describe the issue

I tried to use `layers.AveragePooling` method and wanted to set `pool_size` that was computed from a dynamically computed tensor. But got the error (issue title). I understand the error message. But in case of dynamic input tensor, it seems problematic to compute such basic stuff.

## Reproducible code

```python

class CustomModel(keras.Model):
    
    def call(self, inputs):
        
        # in actual case, input is dynamic (b, none, none, none, chanenel)
        shape = tf.shape(inputs) 
        D, H, W = (
            shape[1],
            shape[2],
            shape[3],
        )

        reshaped_tensor = tf.reshape(
            inputs, 
            [
                -1, 
                D * H * W,
                3
            ]
        )

        avg_dim = tf.math.ceil( tf.shape(reshaped_tensor )[1] / 7)
        avg_pool = layers.AveragePooling1D(pool_size=avg_dim)
        avg_pool_output = avg_pool(reshaped_tensor)
        return avg_pool_output


inputs = layers.Input(shape=(10, 20, 30, 3))
outputs = CustomModel()(inputs)
model = keras.Model(inputs=inputs, outputs=outputs)
```
```
ValueError: Exception encountered when calling layer "custom_model_14" (type CustomModel).

in user code:

    File "/tmp/ipykernel_32/1206670261.py", line 27, in call  *
        avg_pool = layers.AveragePooling1D(pool_size=avg_dim)
    File "/opt/conda/lib/python3.10/site-packages/keras/layers/pooling/average_pooling1d.py", line 136, in __init__  **
        super().__init__(
    File "/opt/conda/lib/python3.10/site-packages/keras/layers/pooling/base_pooling1d.py", line 65, in __init__
        self.pool_size = conv_utils.normalize_tuple(pool_size, 1, "pool_size")
    File "/opt/conda/lib/python3.10/site-packages/keras/utils/conv_utils.py", line 88, in normalize_tuple
        raise ValueError(error_msg)

    ValueError: The `pool_size` argument must be a tuple of 1 integers. Received: Tensor("custom_model_14/Ceil:0", shape=(), dtype=float64)


Call arguments received by layer "custom_model_14" (type CustomModel):
  • inputs=tf.Tensor(shape=(None, 10, 20, 30, 3), dtype=float32)
```

## More info

In the actual case, the `inputs` is dynamic tensor value such as `bs, None, None, None, channel_dim`.  The axis 1, 2, 3 are `None` due to using `tf.pad` method in the preceding layer. Thus `tf.shape` method is used instead of `x.shape` and `math.ceil` module which might work.

**Comment by fchollet** [comment]
This is not feasible -- neither TF nor JAX support avp pooling window sizes that are tensors. They have to be static ints.

1. If you really need a layer that can handle different pooling sizes dynamically, you can implement one by combining a `cond` op and a series of `avg_pool` ops with hardcoded window sizes, routing to the right op based on the current size value. You can do this in a custom layer.
2. Most likely you don't actually need dynamic pool sizes because you only have a single image size. You just need to make sure that your inputs have a static shape. Then your logic will work.

**Comment by innat** [comment]
Thanks for the details response. I understood and agreed to those points. Ensuring static shape for all cases are a bit troublesome. For example, operations like `tf.cond` assumes that the returned factor (methods) should be same shape otherwise it would return unknown shape. And that may cause dynamic shape issue if `tf.cond` ops is used in call method to pad tensor based on some logic, which may not in the case with torch.nn.functional.pad. 

Now for similar casse (i.e. padding a tensor) on **input shape of a layer**, the `build` method can be used to compute necessary factor only. 

Further, in the above dummy example, even if we use static shape, due to `tf.math.ceil`, it returns `tf.tensor` which cause the same reported error and had to use `math.ceil` module .
