### ISSUE TITLE
importing `tf` is required for some text operations (eg, TextVectorization)

### ISSUE THREAD

**Issue by dkgaraujo** [keras-team/keras#18516]
Running some examples from keras.io in "pure" keras 3 (ie, removing tf imports and importing from `keras_core`), I found that `TextVectorization` requires importing `tensorflow` as "tf" specifically.

This is because some operations in the `keras_core` codebase are still using `tf.strings.lower()` and `tf.strings.regex_replace()` specifically.

I know there was a PR in the past that was not merged because porting over all these functions would require deeper reengineering (https://github.com/keras-team/keras-core/pull/672). I'm also aware of the message in the README of this repo. But a quick fix in user experience at this point could be to `import tensorflow as tf` inside `TextVectorization._preprocess`. https://github.com/keras-team/keras/blob/1ab9642de3a7961bd0173ba257b26c5a4dfce374/keras/layers/preprocessing/text_vectorization.py#L521 

This would ensure it works without requiring the user to import it before, keeping user code cleaner and in line with what I believe is the intention. And then behind the scenes this would allow for a smooth  transition to a backend-agnostic Rust library to address these things, as mentioned in https://github.com/keras-team/keras/issues/18421, when the time comes.

If this is an acceptable workaround please let me know and I would be happy to propose such a quick fix PR, or alternatively let the original contributor of the PR mentioned above do that if they prefer.

**Comment by dkgaraujo** [comment]
Further context: I know the following import line at the beginning of the code would import tf:

`from keras.utils.module_utils import tensorflow as tf`

An error message shows if tensorflow is not installed but weirdly enough in my case (tf installed) the error was:

```
Traceback (most recent call last):
  File "/Users/username/Coding/NLP experiments/BERT.ipynb Cell 16", line 0
    vec = get_vectorize_layer(
  File "/Users/username/Coding/NLP experiments/BERT.ipynb Cell 16", line 1
    texts=["Don't worry, be happy", "cause every little thing is gonna be alright"],
  File "/Users/username/Coding/NLP experiments/BERT.ipynb Cell 16", line 2
    vocab_size=30,
  File "/Users/username/Coding/NLP experiments/BERT.ipynb Cell 16", line 3
    max_seq=4
  File "/Users/username/Coding/NLP experiments/BERT.ipynb Cell 16", line 4
) 
in get_vectorize_layer(texts, vocab_size, max_seq, special_tokens)

File "/Users/username/Coding/NLP experiments/BERT.ipynb Cell 16", line 1
  """
  Build Text vectorization layer
  Args:
    ...
  Returns:
    layers.Layer: Return TextVectorization Keras Layer
  """
  vectorize_layer = TextVectorization(
    max_tokens=vocab_size,
    output_mode="int",
    standardize=custom_standardization,
    output_sequence_length=max_seq,
  )
  vectorize_layer.adapt(texts)
  # Insert mask token in vocabulary
  vocab = vectorize_layer.get_vocabulary()

File "/Users/username/Coding/.venv_keras/lib/python3.10/site-packages/keras_core/src/layers/preprocessing/text_vectorization.py", line 432
  self.update_state(data)

File "/Users/username/Coding/.venv_keras/lib/python3.10/site-packages/keras_core/src/layers/preprocessing/text_vectorization.py", line 436
  self._lookup_layer.update_state(self._preprocess(data))

File "/Users/username/Coding/NLP experiments/BERT.ipynb Cell 16", line 0
  def custom_standardization(input_data):
    lowercase = tf.strings.lower(input_data)
  File "/Users/username/Coding/NLP experiments/BERT.ipynb Cell 16", line 1
    stripped_html = tf.strings.regex_replace(lowercase, "<br />", " ")
  File "/Users/username/Coding/NLP experiments/BERT.ipynb Cell 16", line 2
    return tf.strings.regex_replace(
      stripped_html, "[!#\$%&'\(\)\*\+,\-./:;<=>\?@\[\\\]\^_`\{\|\}~\"]", ""
    )
NameError: name 'tf' is not defined
```

**Comment by fchollet** [comment]
The code that uses `tf` here is your code, your notebook (the function `custom_standardization` specifically) -- hence `tf` needs to be imported in your notebook.

`TextVectorization` does use TF internally (this is mentioned in the docstring) but that does not on its own require you to import tf.
