### ISSUE TITLE
[Distribution] Prototype Pytorch distribution with Pytorch XLA

### ISSUE THREAD

**Issue by qlzh727** [keras-team/keras#18510]
For the unified distribution API, we have JAX backend implemented with named sharding. For pytorch backend, we are planning for use pytorch XLA as underlying API. 

See https://github.com/pytorch/xla for more details.

**Comment by qlzh727** [comment]
@kiukchung and @yeounoh

**Comment by kiukchung** [comment]
I just created https://github.com/keras-team/keras/issues/18511 and referenced this issue. Let me know if you'd like me to close 18511 and move the contents of that here.

**Comment by qlzh727** [comment]
Let me dup this against #18511, which has way more details. Thanks.
