### ISSUE TITLE
.keras models saved in linux don't load in windows (inconsistent path separators in .h5 weights file!)

### ISSUE THREAD

**Issue by lbortolotti** [keras-team/keras#18528]
I've been having trouble with .keras models saved on a linux box, not loading on my windows machine.

If I run this "train+save" code on linux

```
import os

os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
os.environ["NVIDIA_VISIBLE_DEVICES"] = "-1"

os.environ['KERAS_BACKEND'] = 'jax'
import keras_core as keras
import numpy as np

window_size = 100

X = np.random.random((1024, window_size, 1))
Y = np.random.random((1024, window_size, 1))

model = keras.Sequential([keras.layers.Dense(128, activation='relu'),
                          keras.layers.Dense(64, activation='relu'),
                          keras.layers.Dense(1, activation='relu'),
                          ])

model.compile(optimizer=keras.optimizers.Adam(), loss=keras.losses.mean_squared_error)

model.fit(X, Y, batch_size=32)

model.save(f'repro_{os.name}.keras')

```

And this "load" on windows:

```
import os

os.environ['KERAS_BACKEND'] = 'jax'
import keras_core as keras

# The fact that this custom_object is needed might be a bug in itself
model2 = keras.models.load_model('repro_3.keras', custom_objects={'mean_squared_error': keras.losses.mean_squared_error})
```

I get the following error:

 ```
 File "C:\keras_core_experiments\repro_3_load.py", line 6, in <module>
    model2 = keras.models.load_model('repro_3.keras', custom_objects={'mean_squared_error': keras.losses.mean_squared_error})
  File "C:\keras_core_experiments\venv\lib\site-packages\keras_core\src\saving\saving_api.py", line 177, in load_model
    return saving_lib.load_model(
  File "C:\keras_core_experiments\venv\lib\site-packages\keras_core\src\saving\saving_lib.py", line 174, in load_model
    _load_state(
  File "C:\keras_core_experiments\venv\lib\site-packages\keras_core\src\saving\saving_lib.py", line 378, in _load_state
    _load_container_state(
  File "C:\keras_core_experiments\venv\lib\site-packages\keras_core\src\saving\saving_lib.py", line 435, in _load_container_state
    _load_state(
  File "C:\keras_core_experiments\venv\lib\site-packages\keras_core\src\saving\saving_lib.py", line 347, in _load_state
    trackable.load_own_variables(weights_store.get(inner_path))
  File "C:\keras_core_experiments\venv\lib\site-packages\keras_core\src\layers\layer.py", line 1111, in load_own_variables
    raise ValueError(
ValueError: Layer 'dense' expected 2 variables, but received 0 variables during loading. Expected: ['kernel', 'bias']
```

I've dug into it, and compared the .keras models that I get running the same "train+save" code above on windows and linux, and I suspect I may have found the culprit:

```
import h5py

win_file = r"C:\keras_core_experiments\New folder\repro_3_nt\model.weights.h5"
linux_file = r"C:\keras_core_experiments\New folder\repro_3_posix\model.weights.h5"

with h5py.File(linux_file, "r") as f:
    # Print all root level object names (aka keys)
    # these can be group or dataset names
    print("Linux-saved model.weights.h5 Keys: %s" % f.keys())

with h5py.File(win_file, "r") as f:
    # Print all root level object names (aka keys)
    # these can be group or dataset names
    print("Window-saved model.weights.h5 Keys: %s" % f.keys())

```

Prints:
```

Linux-saved model.weights.h5 Keys: <KeysViewHDF5 ['layers', 'optimizer', 'vars']>
Window-saved model.weights.h5 Keys: <KeysViewHDF5 ['layers\\dense', 'layers\\dense_1', 'layers\\dense_2', 'optimizer', 'vars']>
```

The two files are different!  And I suspect that we're picking up some os-specific path separators which are breaking things...

**Comment by fchollet** [comment]
@nkovela1 can you take a look? There may be a need for some cross-platform normalization when we write values to the HDF5 variable store. I assume the h5 library itself is intended to work fine on Windows.

**Comment by nkovela1** [comment]
Hi @lbortolotti, could you try switching your filenames to using '/ ' instead of '\' and see if the issue persists? I'm seeing that 
in Linux, the path separator is / while In Windows, it is either \ or / .
This may be the root of the problem, and I could write something simple to standardize filepaths if this is the case.

**Comment by lbortolotti** [comment]
Where would I be changing this exactly?  I think 100% of what's happening is within keras internals.  I'm just saving an h5 file with model.save(filename.keras).

To help you diagnose this, I've then manually extracted the .keras file (which I've learned is just a zip file), and found that the .h5 that gets saved on windows is different to the one that gets saved on linux.

Somewhere (again, internally to keras, nothing under my control), it seems that you're picking up the os path separator and using it to generate the keys for the .h5 file.  This is incorrect, as .h5 doesn't seem to correctly interpret backslashes.

**Comment by AxXxB** [comment]
Faced the same issue, and i agree with [lbortolotti](https://github.com/lbortolotti) that this is a bug inside keras.

**Comment by nkovela1** [comment]
Got it, I think a simple normalization replacing \\ with / should do the trick on the Keras side.

**Comment by nkovela1** [comment]
Please see if this fix works on your end, thanks! If not, please reopen the issue.

**Comment by nkovela1** [comment]
Wait until ##18588 is closed for full coverage, thanks.

**Comment by nkovela1** [comment]
#18588 closed, should be ready for testing.

**Comment by bizso09** [comment]
At the moment, I've tried to save and load models in two different ways accross platforms. Both of them fail. 

1) pickle 
FileNotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files 
2) model.save():
ValueError: Layer 'dense' expected 2 variables, but received 0 variables during loading.

Is there a working solution right now to save and load model accross platform with keras? I'm using tensorflow 2.14

**Comment by mshiffer** [comment]
@nkovela1 I have this issue with an AWS ARM ubuntu instance. The latest release available for that machine is tensorflow-cpu-aws 2.15.0  Can you tell me: How I can find out when the next release of tensorflow-cpu-aws will occur?  Is there a manual workaround for this problem that I can implement in the meantime?  Thanks!

**Comment by moreugene** [comment]
@nkovela1  Having issue similar to @mshiffer described. Stuck on 2.15.0 version. Is there some workaround to save model in linux, then load on windows?

**Comment by re-tundra** [comment]
same here. im stuck on 2.15.0

**Comment by stock-ds** [comment]
Seems to be an issue with keras 2.15.0

Upgraded to tensorflow 2.16.1 + keras 3.1.1 and now .keras model loads in both windows and linux
