### ISSUE TITLE
RandomZoom backwards compatibility 

### ISSUE THREAD

**Issue by SimonF24** [keras-team/keras#18533]
Working on converting the "Image classification with Vision Transformer" keras.io example to keras 3 and ran into a backwards compatibility issue with RandomZoom(). Logging here as per #18468. Changing the imports to keras_core results in an exception when calling RandomZoom.call() where image_width is a Tensor in line 230 of keras_core/src/layers/preprocessing/random_zoom.py.

<a href="https://colab.research.google.com/drive/1RaWBbiwexyXc0ztPJKg6ZkYB8tF_SGXi?usp=sharing">Colab</a>

**Comment by fchollet** [comment]
Thanks for the report! The issue is now fixed at HEAD.
