### ISSUE TITLE
Fix type in data_adapter.py (DistributedDatasetInterface)

### ISSUE THREAD

**Issue by franz101** [keras-team/keras#18541]
Currently the updated `tensorflow/python/keras/engine/data_adapter.py` helper_function:
```
def _is_distributed_dataset(ds):
   return isinstance(ds, input_lib.DistributedDatasetInterface)
```
is causing issues since `input_lib` was changed to `input_lib.distribute_types.DistributedDatasetInterface`

I was referred to open the issue here, though I don't find the data_adapter engine in the keras repo:
https://github.com/tensorflow/tensorflow/pull/62033

I know this is a tiny fix and probably the desk is full of open Issues/PRs.
@fchollet, @qlzh727

**Comment by nkovela1** [comment]
Hi @franz101, `tensorflow/python/keras` is legacy unsupported code. Please make sure you have the correct Keras install, as this is why `data_adapter.py` is different from that in the current repos.

**Comment by qlzh727** [comment]
Agree with Neel's comment. Please make sure to use tf.keras as public API, and the code under tensorflow/python/keras is suppose to be deleted.
