### ISSUE TITLE
Make Torch backend compatible with `2.0.1`

### ISSUE THREAD

**Issue by sampathweb** [keras-team/keras#18558]
Follow-up action item to PR: #18554(where PYTorch min version was updated to `2.1.0`) to make code compatible with PyTorch >= 2.0.1.   This  is a result of #18550.  @james77777778 has suggested a fix in #18554 .

**Comment by grasskin** [comment]
Internally we need 2.0.1 (2.0.0a0 but I think we're ok with 2.0.1) - Fix from @james77777778 looks good
