### ISSUE TITLE
Automated actions on PR approval

### ISSUE THREAD

**Issue by fchollet** [keras-team/keras#18568]
Right now approving a PR automatically triggers the following actions:

> [google-ml-butler](https://github.com/apps/google-ml-butler) bot added [kokoro:force-run](https://github.com/keras-team/keras/labels/kokoro%3Aforce-run) [ready to pull](https://github.com/keras-team/keras/labels/ready%20to%20pull) labels [11 minutes ago](https://github.com/keras-team/keras/pull/18562#event-10579911812)
> @[kokoro-team](https://github.com/kokoro-team) kokoro-team removed the [kokoro:force-run](https://github.com/keras-team/keras/labels/kokoro%3Aforce-run) label [9 minutes ago](https://github.com/keras-team/keras/pull/18562#event-10579920388)

Since GitHub is the source of truth for the codebase this is not necessary. The CI is already run anyway and doesn't need to be rerun after approval.

**Comment by sampathweb** [comment]
@fchollet - Currently the CI doesn't automatically run the "GPU" jobs.  Its only run after the PR is approved or when you manually add the "kokoro:force-run" label.  When user pushes multiple commits, it only runs the GitHub CI CPU jobs and not the GPU CI jobs until its reviewed.  Are you suggesting we change this behavior and have the GPU CI run on commit push from the user?

**Comment by fchollet** [comment]
Got it -- sure, that's fine. It wasn't clear to me.
