### ISSUE TITLE
Feature request: coexistence of `ragged` and `output_sequence_length` in `TextVectorization`

### ISSUE THREAD

**Issue by WenjieZ** [keras-team/keras#18576]
Sometimes, we may want a ragged tensor but still get to truncate a too long sentence. This configuration is currently forbidden for no reasons.

https://github.com/keras-team/keras/blob/b3ffea6602dbbb481e82312baa24fe657de83e11/keras/layers/preprocessing/text_vectorization.py#L353-L358

**Comment by qlzh727** [comment]
Assign to Matt for further triage.

**Comment by mattdangerw** [comment]
No strong feeling here. Seems slightly confusing that `output_sequence_length` would effectively work as `max_sequence_length` when `ragged=True`, but definitely something we could document and could be useful.

Seems our options:
1) Allow `ragged=True` and `output_sequence_length=xx`, document the `output_sequence_length` will truncate in the ragged case.
2) Continue to disallow. Users can simply do `text_vectorization(inputs)[:, :max_length]` to truncate.

I'm open to a PR if someone wanted to put one up. @fchollet any strong opinions?

**Comment by rajveer43** [comment]
would like to work on it

**Comment by fchollet** [comment]
Yes we can allow it. It's not a big problem. If someone wants to send out a PR we'll review it.

**Comment by rajveer43** [comment]
> Yes we can allow it. It's not a big problem. If someone wants to send out a PR we'll review it.

Thank you. Will work on it.

**Comment by SasankYadati** [comment]
@mattdangerw @fchollet please have a look at the PR https://github.com/keras-team/keras/pull/18980 and let me know your thoughts.

**Comment by sampathweb** [comment]
Addressed in #19028
