### ISSUE TITLE
Example using `vmap`/`pmap` from Jax?

### ISSUE THREAD

**Issue by asmith26** [keras-team/keras#18570]
I've written a [custom Jax training loop](https://keras.io/keras_core/guides/writing_a_custom_training_loop_in_jax/), but unfortunately my script doesn't seem to be using very much GPU-memory. I've tried increasing the `batch_size`, but unfortunately that doesn't seem to make much difference. Hence I thought I'd try to increase the throughput with something like [vmap](https://jax.readthedocs.io/en/latest/_autosummary/jax.vmap.html) or run some models in parallel (where applicable) with something like [pmap](https://jax.readthedocs.io/en/latest/_autosummary/jax.pmap.html) (or even like [`flax.linen.vmap()`](https://flax.readthedocs.io/en/latest/api_reference/flax.linen/_autosummary/flax.linen.vmap.html).

Are there any examples regarding how to do this? I've come across [this guide](https://keras.io/keras_core/guides/distributed_training_with_jax/), but this only appears to be for multiple devices.

I might be misunderstanding my problem, but many thanks for any help! :)

**Comment by AakashKumarNain** [comment]
Can you provide a minimal example?

**Comment by asmith26** [comment]
I'm trying to reproduce SAC with Keras Core Jax, and I'm following another example and am struggling to re-create the following `vmap`:  https://github.com/vwxyzjn/cleanrl/blob/bbec22d1b60f54903ffaf4993df443f9001d0951/cleanrl/sac_continuous_action_jax.py#L128-L139

**Comment by AakashKumarNain** [comment]
You should be able to use `vmap` and `pmap` flawlessly in Keras 3. If you can share the code you have written, I can provide some suggestions on how to do it

**Comment by asmith26** [comment]
Hi @AakashKumarNain, many thanks for your help, I really appreciate it.

Regarding a code example, to learn about Keras Core + Jax, I thought I'd have a go at recreating [this Flax SAC example](https://github.com/vwxyzjn/cleanrl/blob/bbec22d1b60f54903ffaf4993df443f9001d0951/cleanrl/sac_continuous_action_jax.py), here is [my attempt](https://github.com/asmith26/cleanrl/blob/keras_core_jax/cleanrl/keras_core_jax/sac_continuous_action.py).

The code is still a work in progress, but I've struggled to recreate [these lines](https://github.com/vwxyzjn/cleanrl/blob/bbec22d1b60f54903ffaf4993df443f9001d0951/cleanrl/sac_continuous_action_jax.py#L128-L139) (and instead just running the 2 Qnetworks sequentially), so if you are able to help with this this would be very helpful thanks.

**Comment by asmith26** [comment]
[I'm also struggling to recreate [this network](https://github.com/vwxyzjn/cleanrl/blob/bbec22d1b60f54903ffaf4993df443f9001d0951/cleanrl/sac_continuous_action_jax.py#L247-L253), my attempt is [here](https://github.com/asmith26/cleanrl/blob/4da0767adacb7e79b68de8e6d7b37a553980fb8e/cleanrl/keras_core_jax/sac_continuous_action.py#L324-L349).]

**Comment by asmith26** [comment]
I've tried to create a minimal example of the thing I'm trying achieve - essentially I'm not sure how to stack and map over Keras 3 variables/models:

```python
import os
from typing import Iterable

os.environ["KERAS_BACKEND"] = "jax"
import keras_core as keras
import jax
import jax.numpy as jnp

x = keras.ops.ones((2, 1))
inputs = keras.Input(shape=(1,))
outputs = keras.layers.Dense(1)(inputs)
model1 = keras.Model(inputs, outputs)
model2 = keras.Model(inputs, outputs)

# HOW STACK MODELS TO MAP OVER?
trainables = [model1.trainable_variables, model2.trainable_variables]
non_trainables = [model1.non_trainable_variables, model2.non_trainable_variables]

# THESE FAIL (arbitrarily use `model1.stateless_call`)
jax.vmap(model1.stateless_call, in_axes=(0, 0, None))(trainables, non_trainables, x)
jax.tree_util.tree_map(model1.stateless_call, trainables, non_trainables, jnp.stack([x, x]))
```

**Comment by AakashKumarNain** [comment]
Thanks for the code examples. I wasn't able to dig into the first code. For the last code, here is how I ran the stateless call via `vmap`.

```python
def build_model():
    inputs = layers.Input(shape=(1,), batch_size=2)
    x = layers.Dense(64, activation="relu")(inputs)
    x = layers.Dense(1)(x)
    model = Model(inputs, x, name="useless_model")
    return model

keras.backend.clear_session()
model = build_model()
model.summary()

trainable_vars = model.trainable_variables
non_trainable_vars = model.non_trainable_variables
inputs = jnp.array(np.random.rand(2, 1).astype(np.float32))

vmapped = jax.vmap(model.stateless_call, in_axes=(None, None, 0), out_axes=(0, None))
out = vmapped(trainable_vars, non_trainable_vars, inputs)

## output:
## (Array([[[-0.00094579]],
## 
##        [[-0.00088299]]], dtype=float32),
## [])
``` 

PS: IMO you are approaching the problem in a wrong fashion though. If I were in your place, I would rather `vmap` the function that is computationally expensive, and will keep everything else as it is.

**Comment by asmith26** [comment]
Thanks very much for the example and your help @AakashKumarNain. What I'm trying to achieve is running 2 different sets of model weights through the same model structure in parallel, e.g. something like (but this doesn't work):

```python
trainables = [model1.trainable_variables, model2.trainable_variables]
non_trainables = [model1.non_trainable_variables, model2.non_trainable_variables]
jax.vmap(model.stateless_call, in_axes=(0, 0, None))(trainables, non_trainables, x)

# this produced the error:
ValueError: Argument `non_trainable_variables` must be a list of tensors corresponding 1:1 to Functional().non_trainable_variables. Received list with length 2, but expected 0 variables.

```

I think I'm creating the Jax container/Pytree incorrectly, not sure if I need to stack them in some other way?
