### ISSUE TITLE
keras.layers.preprocessing exists in the code but not in the pip package

### ISSUE THREAD

**Issue by wangkuiyi** [keras-team/keras#18606]
I installed tensorflow==2.14.0 using pip, which depends on keras==2.14.0. Then my exisitng code that calls `kears.layers.preprocessing.image_preproessing.transform` stopped working.

It seems that this function exists in the code base: https://github.com/keras-team/keras/blob/v2.14.0/keras/layers/preprocessing/image_preprocessing.py#L720

However, the package `preprocessing` doesn't exist in the pip package.

```
20:14 $ python
Python 3.9.0 | packaged by conda-forge | (default, Nov 26 2020, 07:55:15)
[Clang 11.0.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from keras import layers
>>> from keras.layers import preprocessing
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'preprocessing' from 'keras.layers' (/Users/y/miniforge3/envs/play/lib/python3.9/site-packages/keras/layers/__init__.py)
>>> import keras
>>> keras.__version__
'2.14.0'
```

**Comment by SuryanarayanaY** [comment]
Hi @wangkuiyi ,

Please try `from keras.layers.experimental import preprocessing` as you can see in the API export decorator.

https://github.com/keras-team/keras/blob/68f9af408a1734704746f7e6fa9cfede0d6879d8/keras/layers/preprocessing/image_preprocessing.py#L501

**Comment by fchollet** [comment]
All symbols in that module are in `keras.layers`, so just use that. The pip package reflects the public API (unlike the codebase). `preprocessing` is not part of the public API.
