### ISSUE TITLE
How to output a dense layer with different dim length of output?

### ISSUE THREAD

**Issue by arditobryan** [keras-team/keras#18608]
In the following code I am training a small neural network on a set of features (X_train, length of 2) and labels (y_train, length of 7). 
Instead of just outputting the prediction, I am also trying to output the dense_representation_layer:

```
n_inputs, n_outputs = X_train.shape[1], y_train.shape[1]
    #2, 7

    input_layer = Input(shape=(n_inputs,))
    dense_layer = Dense(20, activation='relu')(input_layer)
    output_layer = Dense(n_outputs, activation='sigmoid')(dense_layer)
    dense_representation_layer = Dense(20, activation='sigmoid')(dense_layer) # ERROR HERE
    model = Model(inputs=input_layer, outputs=[output_layer, dense_representation_layer])

    model.compile(
        loss='binary_crossentropy', 
        optimizer='adam', 
        metrics=['mse', 'mae', 'mape','accuracy']
    )

    # fit model
    model.summary()
    history = model.fit(X_train, y_train, validation_split=0.25, verbose=2, epochs=epochs)

    return model, history
```

However, it tells me that the dimension of the dense_representation_layer must be the same of the output layer:

`ValueError: `logits` and `labels` must have the same shape, received ((None, 20) vs (None, 7)).`

Any help is appreciated, thank you

**Comment by sampathweb** [comment]
@arditobryan - Please create a reproducible colab with sample inputs you were trying to use.
