### ISSUE TITLE
Bug in batch_dot() [keras-core 0.1.7]

### ISSUE THREAD

**Issue by nhuet** [keras-team/keras#18622]
The `batch_dot()` from `keras_core.src.layers.merging.dot` does not work with tensors having more thatn 2 dimensions (x_squashed = True or y_squashed=True) due to a call to a non-existent ops.concat().

I am using keras-core 0.1.7.

Here is a minimal example reproducing the error:
```python
import numpy as np
from keras_core.src.layers.merging.dot import batch_dot
from keras_core.ops import convert_to_tensor

x=convert_to_tensor(np.reshape(list(range(6)),(1,3,2)))
y=convert_to_tensor(np.reshape(list(range(6)),(1,1,2,3)))

batch_dot(x, y)
```

> AttributeError: module 'keras_core.src.ops' has no attribute 'concat'

This works if we remove a dimension:
```python
import numpy as np
from keras_core.src.layers.merging.dot import batch_dot
from keras_core.ops import convert_to_tensor

x=convert_to_tensor(np.reshape(list(range(6)),(1,3,2)))
y=convert_to_tensor(np.reshape(list(range(6)),(1,2,3)))

batch_dot(x, y)
```

The bug seems fixed if we replace `ops.concat()` by `ops.concatenate()` in the code of batch_dot. However, I am not familiar enough with the library to be sure that this behaves exactly as intended.

**Comment by fchollet** [comment]
Thanks for the report. This is now fixed at HEAD.

Please note that `batch_dot` is a private API. You can use the `Dot` layer instead, which is public.
