### ISSUE TITLE
[tensorflow] MirroredStrategy Multi-GPU - AttributeError: KerasVariable has no attribute device

### ISSUE THREAD

**Issue by crohkohl** [keras-team/keras#18627]
I am using the `MirroredStrategy` in a multi-gpu setting. Using the optimizer `optimizers.sgd.SGD`.

The following call fails:

https://github.com/keras-team/keras/blob/66b1c0c01fc08d6b4832643ce18dbac8ea8bfb9b/keras/backend/tensorflow/optimizer.py#L107

Here is the exception:

<img width="892" alt="Screenshot 2023-10-16 at 20 54 24" src="https://github.com/keras-team/keras/assets/6941505/91ed3aa3-da07-4c3e-bd1a-eddc4388cccc">

And here details of the `KerasVariable` for that the call fails:

<img width="1006" alt="Screenshot 2023-10-16 at 20 52 57" src="https://github.com/keras-team/keras/assets/6941505/434d9a32-bdb9-45db-a6c5-0fb674407a10">

Any help or hint on the reason for this error would be appreciated, thank you!

**Comment by fchollet** [comment]
What's your Keras version? I suspect this is already fixed at HEAD.

**Comment by qlzh727** [comment]
Yea, this should be addressed by https://github.com/keras-team/keras/pull/18494/files. Can u rerun the test with latest version?

**Comment by crohkohl** [comment]
Yes, I tried and its fixed. 

The only remaining error is the `jit_compile=False` requirement in the `model.compile()` method. All other things seem to work as intended now.
