### ISSUE TITLE
[keras-core] keras.ops.min() bugged for symbolic tensors

### ISSUE THREAD

**Issue by nhuet** [keras-team/keras#18638]
`keras.ops.min() `is not working on a `KerasTensor`:

```python
from keras_core import Input
from keras_core import ops

x = Input((1,))
ops.min(x)
```

> AttributeError: 'Min' object has no attribute '_inbound_nodes'

This seems to be due to the fact that `Min.__init__()` does not call `super().__init__()` and thus does not instantiate `_inbound_nodes ` attribute.

**Comment by fchollet** [comment]
Thanks for the report. This is now fixed at HEAD.
