### ISSUE TITLE
[Feature request] Extract layer output from subclassed keras model

### ISSUE THREAD

**Issue by innat** [keras-team/keras#18634]
**Describe**

Unlike functional API, it is not convinient to get the tensor output of a certain layer from a subclass API model. Thus making it hard to explain subclass type model. In the [`keras.Model`](https://keras.io/api/models/model/), it is documented about [`get_layer`](https://keras.io/api/models/model/#:~:text=%5Bsource%5D-,get_layer,-method) method which generally being used to get the [`tensor output`](https://keras.io/examples/vision/grad_cam/#:~:text=grad_model%20%3D%20keras.models.Model(%0A%20%20%20%20%20%20%20%20model.inputs%2C%20%5Bmodel.get_layer(last_conv_layer_name).output%2C%20model.output%5D%0A%20%20%20%20)) of certain layer for functional API model.

Someone might suggest to modify the `call` method based on the desired tensor output but simply it is not desirable. Because, the subclass model arch may be complicated with many internal blocks/layers where the desired layer(s) is placed. Also, subclass API might be built with **pure or with mixed API**. Also, for a built-in subclass model and a given trained weight, it would require to rewrite the whole `call` function of the target layer/module in order to alter. Note, we don't have to go through any of like this with functional API model.

```python
class MyModel(tf.keras.Model):
    def __init__(self):
        super(MyModel, self).__init__()
        self.conv1 = Conv2D(32, (3, 3), name='beluga')
        self.conv2 = Conv2D(64, (3, 3), name='hecker')
        self.gap = GlobalAveragePooling2D()
        self.fc = Dense(10, activation='softmax')

    def call(self, inputs):
        x = self.conv1(inputs)
        x = self.conv2(x)
        x = self.gap(x)
        return self.fc(x)


....
def call(self, inputs, return_tensor='fo'):
    x1 = self.conv1(inputs)
    x2 = self.conv2(x)
    gapx = self.gap(x)

    if return_tensor == 'fo':
        return self.fc(x), x1

    return self.fc(x)
```

This issue was asked in [StackOverflow](https://stackoverflow.com/q/68259714/9215780), viewed over 1k+, stating its demand. I gave two [answers](https://stackoverflow.com/a/68267251/9215780) there but it was simply workaroud. It would a be great feature for subclass API model to have some methodology (that works with i.e `get_layer`, `model.inputs`), gives seamless access to internel layer for its output in order to build explainable model, i.e. grad-cam.

```python
model = MyModel()
grad_model = keras.Model(
    model.inputs, 
    [
        model.get_layer('beluga').output, 
        model.output
    ]
)
```

Or, in the `call` method adding a param that auto track the imported layer (from `__init__`) and while calling `y_pred, layer_outs = model(x, name=['hecker', 'begula']`.

In `torch`, we prefer subclass API, so setting is as backend it could be desirable feature for keras. Same goes to `jax`.

 <sup>(please avoid recommending functional API over subclass API to remedy this issue!)</sup>

**Comment by fchollet** [comment]
The correct approach here is to use a Functional model. A subclassed model is a blob of bytecode, there is no concept of "layer output". You can always implement hacks (e.g. cache the layer's latest eager or symbolic output) but they're not conceptually sound. If you are looking to reusing a layer's output, it means you are thinking of your model as a graph, and so you should use a graph datastructure to represent it, i.e. a Functional model.

**Comment by innat** [comment]
It doesn't solve the issue. If subclass API is available in keras, it should be support such basic feature. This doesn't have to be same as functional API but the way torch handles it can be a reference.

This encourage user to prefer functional api (but https://github.com/keras-team/keras/issues/16355) over subclass which may not be desired for all user who prefer subclass.

**Comment by fchollet** [comment]
Subclassing is perfectly fine, but the expectation of writing a model/layer subclass is that its forward pass is a blackbox. You can't externally inspect and reuse intermediate outputs from inside a Python function -- you must return from the function anything you want to reuse, or turn your monolithic function into a more modular chain or graph of functions. Same with Keras. Either use a chain / graph of layers (a Functional model), and reuse intermediate outputs, or use a single `def call()` and treat it like a blackbox.

**Comment by innat** [comment]
For future study: **Feature extraction in PyTorch**.

https://pytorch.org/vision/stable/feature_extraction.html

```python
import torch
from torchvision.models import resnet50
from torchvision.models.feature_extraction import create_feature_extractor

model = resnet50()
return_nodes = {
    "layer4.2.relu_2": "layer4"
}
model2 = create_feature_extractor(model, return_nodes=return_nodes)

x = torch.rand(1, 3, 224, 224)
intermediate_outputs = model2(x)

print(intermediate_outputs['layer4'].shape)
```
