### ISSUE TITLE
Unable to change validation dataset for "model.fit()" function after it raises an exception

### ISSUE THREAD

**Issue by SuryanarayanaY** [keras-team/keras#18653]
Cross reporting issue #[62014](https://github.com/tensorflow/tensorflow/issues/62104) from tensorflow repo.

When using model.fit() with validation_data, during first call to fit() it will create an `EpochIterator` object for evaluation and cache it. This cache will be deleted after completion of all epochs.

However if we try to change the `validation_data` shapes (Not sure of the exact use case of this) and called `model.fit() `again it will raise an exception like Graph execution error which is intended. After this if we call `model.fit()` with correct `validation_data` that of first training call it won't work. The reason being is after first call is success evaluation `EpochIterator` will be deleted at the end and during second training call a new `EpochIterator` will be generated again with changed shape.But during `evaluate()` call it will raise an exception terminating the process without deleting evaluation `EpochIterator` object and it remains in cache. During third call though with correct `validation_data` it will not create new `EpochIterator` object as one already exists in cache which makes it fail again.

It don't strike me any use case of this situation. Reporting here whether it needs attention.

Attaching [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/767f89dd0b195367be917add09afc8d4/62104_with_keras-core_r2.ipynb) replicating the issue with `keras_core`.

**Comment by SuryanarayanaY** [comment]
If worth to consider this as bug, a simple fix may be initializing `EpochIterator` to `None` in `model.fit` at beginning itself.

In the source code self._eval_epoch_iterator is the validation_data EpochIterator object. Setting 
`self._eval_epoch_iterator = None` at the beginning of model.fit() ensures creation of new EpochIterator object for each training call. 

It indeeds fix this issue but not sure it has any toll on other things.

**Comment by sampathweb** [comment]
Thanks for this report. Can you create a PR for this issue?
