### ISSUE TITLE
[ops] add `tf.math.floordiv` , `tf.math.floormod`

### ISSUE THREAD

**Issue by innat** [keras-team/keras#18679]

**Comment by haifeng-jin** [comment]
Hi @innat ,
Thanks for the issue.

Do you mean add it for all backends? or just the TF backend?
It can be done with existing numpy ops.
For TF backend, you can directly use these functions with your code.

**Comment by innat** [comment]
For all backend. I was porting a tf.keras model to keras 3 and noticed there is no `ops.floordiv` yet. I was trying to make mmthis model backed agnostic. 

(Apart from this, I've just noticed split approach of keras.ops.split and tf.split are different. And assumed that there may be more. So, for keras.ops, is there any reference backend (tf/jax/torch/np)?)

**Comment by james77777778** [comment]
I believe these two ops have been included in Keras:
- `tf.math.floordiv` <---> `ops.floor_divide`
- `tf.math.floormod` <---> `ops.mod`

```python
import numpy as np
import tensorflow as tf

from keras import ops

x = np.random.uniform(high=10, size=(2, 4, 6)).astype("float32")
print(x)

tf_res = tf.math.floordiv(x, 3).numpy()
ops_res = ops.floor_divide(x, 3)
np.testing.assert_allclose(tf_res, ops_res)
print(ops_res)

tf_res = tf.math.floormod(x, 3).numpy()
ops_res = ops.mod(x, 3)
np.testing.assert_allclose(tf_res, ops_res)
print(ops_res)

```
