### ISSUE TITLE
Only input tensors may be passed as positional arguments

### ISSUE THREAD

**Issue by innat** [keras-team/keras#18676]
@ianstenbit 
Thanks for raising this [issue](https://github.com/keras-team/keras-core/issues/737) and [hint](https://github.com/keras-team/keras-core/issues/737#issuecomment-1681343954). I've just faced similar issue while converting a tf.keras model to keras. In my case, it wasn't `None` but `int`, shown below.

```python
shape = ops.shape(tensor1)
H, W = shape[1], shape[2]
y = ALayer(tensor2, H, W)
```

> ValueError: Exception encountered when calling TFVideoFocalNet.call().
Only input tensors may be passed as positional arguments. The following argument value should be passed as a keyword argument: 56 (of type <class 'int'>)

Refactoring is not a problem if needed, but above way works in tf.keras and not keras-core. Is it expected?

**Comment by fchollet** [comment]
This is deliberate. The trade-off is that, now you have to specify keyword args for non-tensor arguments, but in return you get the ability to have layers with multiple tensor arguments where all arguments will support masking and mixed precision (which wasn't possible in tf.keras).
