### ISSUE TITLE
Torch Utils

### ISSUE THREAD

**Issue by emi-research-dl** [keras-team/keras#18685]
Hi @sampathweb, It was installed from PyPy. Issue #18680 

1. Clone Keras repo
2. pip install -r requirements-common.txt
3. pip install -r requirements-tensorflow-cuda.txt
4. pip install -U keras-nightly

![image](https://github.com/keras-team/keras/assets/140513018/c3275138-49a3-48c6-9448-60f168acac96)

**Comment by sachinprasadhs** [comment]
Hi, I was able to replicate the issue with only `pip install -U keras-nightly`.
Here is the Gist attached for reference https://gist.github.com/sachinprasadhs/00c0acff862a672e8c9042bc7683d627.

Interesting thing is that I was able to run `from keras.layers import TorchModuleWrapper` but I get error when I tried to run `keras.utils.torch_utils.`

**Comment by haifeng-jin** [comment]
@emi-research-dl Thanks for the issue!

Now, only public APIs are visible to the users. The private APIs, like the ones in `torch_utils.py`, are under `keras.src`, like `keras.src.utils.torch_utils` when it is on PyPI. We discourage people to use it since it is subject to changes.
