### ISSUE TITLE
Torch utils

### ISSUE THREAD

**Issue by emi-research-dl** [keras-team/keras#18680]
Why torch_utils is not available on Keras TF-Cuda backend version?

![image](https://github.com/keras-team/keras/assets/140513018/32f44f7d-140a-4fcd-9a78-251309c79f4a)

With torch-cuda installation it is:
![image](https://github.com/keras-team/keras/assets/140513018/2c4349b2-eae2-49de-8ff4-4f3ca7a7a312)

Thanks in advanced!

**Comment by sampathweb** [comment]
I am not sure how you install `keras`.  Did you use `pip install -U keras-nightly`?  

What you have looks like folder tree structure and not based on API exports which is not necessarily the same as API exports.  For example, `keras.layers.TorchModuleWrapper` is in `keras/utils/torch_utils`.  So if you installed from GitHub, and used the referene as `keras.utils.torch_utils`, that code will not work when you `pip install keras`, so please install from pypi `keras-nightly` until `keras3` is officially released.
