### ISSUE TITLE
Add `GCViT` Implementation as Multi-backend Example

### ISSUE THREAD

**Issue by awsaf49** [keras-team/keras#18696]
I wrote this [notebook](https://www.kaggle.com/code/awsaf49/gcvit-global-context-vision-transformer/notebook) which implements the [GCViT: Global Context Vision Transformer](https://arxiv.org/pdf/2206.09959.pdf) (ICML 2023) paper from scratch along with a port of the official ImageNet weights. I believe it would be beneficial to include this work as an example on `keas.io` with `multi-backend` feature.

Currently, this work supports `TensorFlow`, but I can adapt it for `multi-backend` support. The notebook might be somewhat lengthy, but I can condense it if required.

**References**
* Notebook: [Kaggle](https://www.kaggle.com/code/awsaf49/gcvit-global-context-vision-transformer/notebook)
* Code: [GitHub](https://github.com/awsaf49/gcvit-tf)
* Paper: [Arxiv](https://arxiv.org/pdf/2206.09959.pdf)
* Official Code: [GitHub](https://github.com/NVlabs/GCVit)

**Comment by awsaf49** [comment]
cc: @fchollet

**Comment by fchollet** [comment]
That sounds great! Let's definitely try to target the multi-backend setup if at all possible -- that will be much more valuable. Code examples are expected to be 300 lines of code max (not counting whitespace and comments), but if that's impossible we can make exceptions.

**Comment by awsaf49** [comment]
PR has been merged for this issue, https://github.com/keras-team/keras-io/pull/1673
