### ISSUE TITLE
 AttributeError: module 'keras.utils' has no attribute 'Sequence'

### ISSUE THREAD

**Issue by madhusshivakumar** [keras-team/keras#18698]
while migrating examples/vision/metric_learning.py to keras 3 I run into this issue:

```
AttributeError                            Traceback (most recent call last)
[<ipython-input-9-4af7ddf22abc>](https://localhost:8080/#) in <cell line: 125>()
    123 
    124 
--> 125 class AnchorPositivePairs(keras.utils.Sequence):
    126     def __init__(self, num_batches):
    127         super().__init__()

AttributeError: module 'keras.utils' has no attribute 'Sequence'
```

Here is the colab link to recreate the issue:

https://colab.research.google.com/drive/1iCM-yB_JpgRS0EdvD6CUjDrNhGN4Lwbs?usp=sharing

**Comment by sachinprasadhs** [comment]
Hi, You can use the Keras 3.0 using` !pip install keras-nightly`, I was able to run the code successfully, attaching the Gist here https://gist.github.com/sachinprasadhs/c32f8d61e5109c3ff75e842d6c1b365f for reference. Thanks!

**Comment by madhusshivakumar** [comment]
> !pip install keras-nightly

I see, this worked! thank you😅
