### ISSUE TITLE
yolov8 with yolo_v8_xl_backbone_coco not able to detect objects with pretrained weights

### ISSUE THREAD

**Issue by muhammetp** [keras-team/keras#18703]
``` python

HEADER_STARTING_LAYER_NAME = 'yolo_v8_head_1_class_1_pad'
BBOX_FORMAT = "xywh"
INFERENCE_RESIZING = keras_cv.layers.JitteredResize(
    target_size=(640, 640),
    scale_factor=(0.75, 1.3),
    bounding_box_format=BBOX_FORMAT,
)

def load_model():
    model =  keras_cv.models.YOLOV8Detector(
        num_classes=len(LABEL_MAP),
        bounding_box_format=BBOX_FORMAT,
        backbone=keras_cv.models.YOLOV8Backbone.from_preset(
            "yolo_v8_xl_backbone_coco", load_weights=True
        ),
        fpn_depth=3
    )
    prediction_decoder = keras_cv.layers.MultiClassNonMaxSuppression(
    bounding_box_format=BBOX_FORMAT,
    from_logits=True,
    iou_threshold=0.8,
    confidence_threshold=0.62,
    )
    model.prediction_decoder = prediction_decoder
    #model = freeze_weights_up_to_header(model)
    
    return model
model = load_model()
if len(images.shape):
    images = np.expand_dims(images, axis=0)
norm_img = INFERENCE_RESIZING(images)
y_pred = model.predict(norm_img)
```

i m getting so weird predictions out of this lines of code above even if i used  pretrained weights. the corresponding output is shown as follows:

![frame1](https://github.com/keras-team/keras/assets/145387899/85699f9d-0430-46c1-998c-66640d36814e)

As you can see the outputs all of their predictions confidence score 0.63 i also verified from debuggin which is 0.62... maybe that helps you to understand the root of the problem
 
![image](https://github.com/keras-team/keras/assets/145387899/8c567313-83fb-4f64-adcc-1fd94b183566)

please suggest me correct codebase which make predictions well and accurately.

**Comment by sachinprasadhs** [comment]
Hi, Could you please provide reproducible code in colab. Thanks!
