### ISSUE TITLE
Accessing TF backend session variables

### ISSUE THREAD

**Issue by azagajewski** [keras-team/keras#18707]
Hi,

I'm trying to diagnose and fix a RAM memory leak when training a subclassed keras model - to that end, I'm trying to access the backend session graph operations and variables as a function of epoch using a callback, to check if/where new variables are being created during the run. However, using:

`graph = tf.compat.v1.keras.backend.get_session().graph`

returns the graph, but it is empty. See reproducible example in colab below:

https://colab.research.google.com/drive/11HU5H_R3skwkx5sgRrRkpS4yrO7ad7yi?usp=sharing

Any suggestions on how to do this most effectively, or any other ways of tracking the global state of keras/tensorflow?

**Comment by fchollet** [comment]
There is no global graph (or session) in TF 2, that was a TF 1 concept.

Keras 3 runs via `tf.function` objects, which are stored at e.g. `model.train_function` for the training function (there's also `model.test_function` and `predict_function`). They are created on the fly when you run e.g. `fit()` or `evaluate()`. Each function has its own graph. See also https://www.tensorflow.org/guide/intro_to_graphs

You can try inspecting the graphs of these functions.
