### ISSUE TITLE
load saved model in keras with tensorflow backend!

### ISSUE THREAD

**Issue by pure-rgb** [keras-team/keras#18709]
```
keras.models.load_model('my_model')
keras.model.load_weights('my_model')
```
With tf.keras it works but in new keras, 

```
ValueError: File format not supported: filepath=my_model Keras Core only supports V3 `.keras` and `.weights.h5` files.
```

```
-> 192     raise ValueError(
    193         f"File format not supported: filepath={filepath}. "
    194         "Keras Core only supports V3 `.keras` files and "
    195         "legacy H5 format files (`.h5` extension). "
    196         "Note that the legacy SavedModel format is not "
    197         "supported in Keras Core."
    198     )
```

How keras intend to support thousands of models that are shared with saved model format? Why even with tf backend, it drops support saved model format? Bummer.

**Comment by emi-research-dl** [comment]
Can you share the piece of code where you store the model?

**Comment by fchollet** [comment]
Just use `.keras` as your file extension to save/load Keras models.

If you want to save a TF `SavedModel`, you can do so via `tf.saved_model.save(model)`.

If you want to reload a TF `SavedModel` as a Keras layer, you can do so via `keras.layers.TFSMLayer(path)`.

**Comment by pure-rgb** [comment]
@fchollet Are these documented yet? Didn't find anything here https://keras.io/keras_core/guides/

**Comment by sachinprasadhs** [comment]
@pure-rgb , You can refer to the Guide published here https://keras.io/guides/serialization_and_saving/

**Comment by JohnFarl** [comment]
@fchollet @sachinprasadhs I don't find anything about load checkpoint saved as ckpt 
I have a model and I have to load model weights from 
```
checkpoint
e_8_b_100000.ckpt.data-00000-of-00002
e_8_b_100000.ckpt.data-00001-of-00002
e_8_b_100000.ckpt.index
```
so that I can call model.load_weights(checkpoint). What previously worked, now returns me that error and the (poor) documentation doesn't cover my case. What a mess.

**Comment by MariaLuize** [comment]
@JohnFarl I am facing the same issue.

Now, it only returns: 
``File format not supported: filepath=~cp.ckpt. Keras 3 only supports V3 `.keras` and `.weights.h5` files, or legacy V1/V2 `.h5` files.``

**Comment by MariaLuize** [comment]
An update on how I solved this: I successfully worked around this restriction by building a dynamic bridge that handles weight translation depending on which Keras version is currently running.

The minimal logic works as follows:

-  When running Keras 2:
> 1. If a native Keras 2 `.keras` file exists, load its weights.
> 
> 2. If only the legacy `.ckpt` exists, instantiate the model, load the `.ckpt` weights, and explicitly export the model as a Keras 2 `.keras` file for future compatibility.


- When running Keras 3:

> 1. If a native Keras 3 `.keras` file exists, load it directly using `keras.models.load_model()`.
> 
> 2. If only a Keras 2 `.keras` file exists, instantiate the Keras 3 model architecture, load the Keras 2 weights into it (which Keras 3 natively supports), and then save it to disk as a true Keras 3 `.keras` file.
> 
> 3. If only a `.ckpt` exists, fail gracefully, as Keras 3 cannot interpret raw TensorFlow checkpoints directly without the Keras 2 extraction step.
