### ISSUE TITLE
Doc: Improve documentation and tutorials for distributed training 

### ISSUE THREAD

**Issue by kamlishgoswami** [keras-team/keras#18711]
**Description:**

The documentation and tutorials for distributed training are limited. This can make it difficult for users to get started with distributed training and to use it effectively.

**Improving the documentation and tutorials for distributed training would make it easier for users to:**

- Understand the different types of distributed training available 
- Set up and use distributed training for a model
- Use distributed training to improve the performance of their models

**Specifically, the documentation and tutorials could be improved by:**

- Providing a clear overview of the different types of distributed training available
- Expanding the existing documentation on how to set up and use distributed training
- Adding new tutorials that cover all of the different ways to use distributed training

**Comment by crohkohl** [comment]
I was researching the same topic, because I would like to use a uniform distribution strategy via keras.
The way to go would be most likely:

https://github.com/keras-team/keras/blob/ace2f43edc82f5a474301baff7ca2da3ee9d383c/keras/distribution/distribution_lib.py

Is there any work going on related to this functionality? I would like to use it and could test / contribute.

**Comment by AakashKumarNain** [comment]
If you are looking for a tutorial on Distributed training with JAX backend, you can take a look at [this](https://www.kaggle.com/code/aakashnain/parallelization-and-distributed-training-in-jax)

**Comment by sataliulan** [comment]
> We have the following guides now:
> 
> [Distributed training with JAX](https://keras.io/guides/distributed_training_with_jax/) [Distributed training with TensorFlow](https://keras.io/guides/distributed_training_with_tensorflow/) [Distributed training with PyTorch](https://keras.io/guides/distributed_training_with_torch/) [Distributed training with Keras 3](https://keras.io/guides/distribution/) -- this is the native Keras API (only working for JAX for now)

does keras3 support distribution now? I've upgraded keras to 3.0.1, got an error (by using pytorch2.1.1 as backend), as shown in the picture
 
![image](https://github.com/keras-team/keras/assets/6769310/46ecaf1e-b9d7-41a7-92ab-eb23fcb6bf3c)
