### ISSUE TITLE
model = tf.keras.models.load_model('lung_cancer_CNN.h5')

### ISSUE THREAD

**Issue by Enjoy97** [keras-team/keras#18728]
model = tf.keras.models.load_model('lung_cancer_CNN.h5')
model.summary()

site-packages\keras\saving\legacy\hdf5_format.py", line 186, in load_model_from_hdf5
    raise ValueError(
ValueError: No model config found in the file at <tensorflow.python.platform.gfile.GFile object at 0x00000290B2D65610>.

**Comment by SuryanarayanaY** [comment]
Hi @Enjoy97 ,

Could you please confirm how you have saved the model and which format it was saved ? Whether you have saved complete model or just weights ? Also confirm the kears version used?

Thanks!
