### ISSUE TITLE
Confusing `{"trainable" : True}` in `text_vectorizer.get_config()`

### ISSUE THREAD

**Issue by Ammar-Azman** [keras-team/keras#18741]
From `from tensorflow.keras.layers import TextVectorization`,

``` Python
text_vectorizer = TextVectorization()
text_vectorizer.get_config()

````
I will get the following output

```Python
{'name': 'text_vectorization',
 'trainable': True,
 'dtype': 'string',
 'batch_input_shape': (None,),
 'max_tokens': 68000,
 'standardize': 'lower',
 'split': 'whitespace',
 'ngrams': None,
 'output_mode': 'int',
 'output_sequence_length': 55,
 'pad_to_max_tokens': False,
 'sparse': False,
 'ragged': False,
 'vocabulary': None,
 'idf_weights': None,
 'encoding': 'utf-8',
 'vocabulary_size': 68000}
````

My question is what does the `'trainable': True` means? As far as I know, `TextVectorization` has no trainable weight. We can see it in `model.summary()` where the value of `Params` of this layer would be 0. Hence no trainable weight. But, why "trainable" value is True?

**Comment by fchollet** [comment]
It's just a default setting. All layers have the `trainable` attribute regardless of whether they have weights or not.
