### ISSUE TITLE
Question: If we contribute Keras 3, we don't need to submit the CLA, do we??

### ISSUE THREAD

**Issue by y-vectorfield** [keras-team/keras#18788]
I could not discover the contribution guide for Keras 3.
If we contribute this, we don't need to submit the CLA like tf.keras(Googel CLA).
Is my understaindig correct??

**Comment by SuryanarayanaY** [comment]
Hi @y-vectorfield ,

I think you still needs to submit CLA for contributing this repo as part of policy.You will be asked for it automatically when you submit a First PR here. You may refer this PR #18716 as an example.

**Comment by y-vectorfield** [comment]
Hello, @SuryanarayanaY ,
OK. I understand. Thank you!

**Comment by sachinprasadhs** [comment]
@y-vectorfield , Refer the Contributing guidelines which is newly added for Keras 3 here https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md

**Comment by y-vectorfield** [comment]
Hello, @sachinprasadhs. Thank you very much for your message.
Oh, I see. Thank you.
