### ISSUE TITLE
Bus error when importing keras_nlp before tensorflow

### ISSUE THREAD

**Issue by yaddayaddayaddayadda** [keras-team/keras#18801]
Importing keras_nlp (version 0.6.3) before importing Tensorflw in a python package results in bus error on mac M1. 
I.e, this gives an error:
import keras_nlp
import tensorflow
While this doesn't:
import tensorflow
import keras_nlp

Running on a M1 machine with tensorflow-macos 2.14 and keras_nlp 0.6.3

**Comment by sachinprasadhs** [comment]
I was able to import `keras_nlp` and `tensorflow` on my M1 Mac.

Can you try to install `TensorFlow` 2.15 using `pip install tensorflow==2.15` and install `keras_nlp(0.6.3)` using `pip install keras-nlp`.
Create a new environment to to fresh install to avoid other package conflicts if there is any.
<img width="1666" alt="Screenshot 2023-11-20 at 1 19 45 PM" src="https://github.com/keras-team/keras/assets/73069040/4cecd418-7966-4e1b-a45d-0cc8604f98ee">
