### ISSUE TITLE
Differences feature embeddings in keras and torch models

### ISSUE THREAD

**Issue by innat** [keras-team/keras#18810]
This is not a bug report but to find answer how pretrained weights for `resnet` models are produced and why it differs. This search inspired from [this](https://stackoverflow.com/q/77507225/9215780) post. I ran [torch's `ResNet152`](https://pytorch.org/vision/main/models/generated/torchvision.models.resnet152.html) and [keras's `ResNet152V2`](https://keras.io/api/applications/) **in order to compare their pooling embeddings** and expected to get nearly equal if not exactly.  Now, according to their respected docs, the reported scores are `78.312 acc@1` for torch model and `78.0% acc@1` for keras model. To begin the test, I've run same input (with exact preprocessing) on both models and outputs are quite different in large margin.  Here are the codes to reproduce it. Tested in `tf.keras 2.12.0`

**Input**

```python
import torch
import torchvision.models as models
from torchvision import transforms
from tensorflow import keras
from PIL import Image
import numpy as np

image_path = keras.utils.get_file(
    "african_elephant.jpg", "https://i.imgur.com/Bvro0YD.png"
)
image_array = Image.open(image_path).convert("RGB")
image_array = image_array.resize((224, 224))
```

**torch preprocess**

```python
preprocess = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])
pt_img_tensor = preprocess(image_array).unsqueeze(0)
pt_img_tensor.shape
torch.Size([1, 3, 224, 224])
```

**keras preprocess**

```python
preprocess = keras.Sequential([
    keras.layers.Rescaling(1/255.),
    keras.layers.Normalization(
        mean=[0.485, 0.456, 0.406], 
        variance=[np.square(0.229), np.square(0.224), np.square(0.225)]
    ),
])
keras_img_tensor = preprocess(np.array(image_array))[None, ...]
keras_img_tensor.shape
TensorShape([1, 224, 224, 3])
```

**exactness**

```python
np.testing.assert_allclose(
    pt_img_tensor,
    keras_img_tensor.numpy().transpose(0, 3, 1, 2),
    1e-5, 1e-5
)
# OK
```

**models**

```python
# torch
resnet152_torch = models.resnet152(weights='ResNet152_Weights.IMAGENET1K_V1')
resnet152_torch = torch.nn.Sequential(*(list(resnet152_torch.children())[:-1]))
resnet152_torch.eval();

# keras
resnet152_keras = keras.applications.ResNet152V2(
    include_top=False, 
    pooling='avg', 
    weights='imagenet',
)
resnet152_keras.trainable=False
```

**params**

```python
n_parameters = sum(
    p.numel() for p in resnet152_torch.parameters() if p.requires_grad
)
(n_parameters / 1.0e6)
params (M): 58.14

n_parameters = resnet152_keras.count_params()
(n_parameters / 1.0e6)
params (M): 58.37
```

**inference**

```python
# torch
with torch.no_grad():
    y_pred_pt = resnet152_torch(pt_img_tensor).squeeze()

y_pred_pt.shape
torch.Size([2048])

# keras
y_pred_keras = resnet152_keras(keras_img_tensor).numpy().squeeze()
y_pred_keras.shape
(2048,)
```

**results**

```python
y_pred_pt[:10]
tensor(
  [0.0167, 0.5035, 0.6792, 0.1662, 0.2626, 0.2229, 0.2680, 0.2620, 0.2825, 0.5295]
)

y_pred_keras[:10]
array([0.        , 0.3470126 , 0.10311372, 0.17380843, 0.5537252 ,
       0.        , 0.4661837 , 0.        , 0.0013476 , 0.        ],
      dtype=float32)
```

## Comments

1. The inference results are different despite passing same input to same model
2. Is this previous [issue](https://github.com/keras-team/keras/issues/15822) related regarding weight? cc. @qlzh727 
3. A possible implementation differences of [torch-resnet](https://pytorch.org/vision/main/_modules/torchvision/models/resnet.html#ResNet) and [keras-resnet](https://github.com/keras-team/keras/blob/aef288fa5e2730fffc9afdc02e88e0cbb244e204/keras/applications/resnet.py#L48)! 
4. Outcomes are same for `ResNet152V1`.  (didn't test other type of model, i.e. efficientnet, densenet, etc).

**Comment by fchollet** [comment]
The first thing to check is whether you have the right preprocessing. The best practice is to always use `keras.applications.xxxx.preprocess_input`, in this case `keras.applications.resnet.preprocess_input`.

I would not expect intermediate features or predictions to necessarily be close, because many of the models were retrained from scratch.
