### ISSUE TITLE
[keras3] TrackedList.remove() / Tracker.untrack() bugged 

### ISSUE THREAD

**Issue by nhuet** [keras-team/keras#18811]
When untracking variables an error is raised if it is not the first one registered (because it compares 2 tensors between them which raises a `ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`.

Here is a minimal (silly) example (using only the public API) showing the error:

```python
from keras.layers import Input, Layer


class MyLayer(Layer):

    def build(self, input_shape):
        self.wlist = [self.add_weight(name=f"w{i}", shape=(i, i)) for i in range(1, 4)]
        self.built = True

    def call(self, input):
        return input


layer = MyLayer()
input = Input((2, 3))
layer(input)
print(type(layer.wlist))  # this is a TrackedList

layer.wlist.remove(layer.wlist[1])  # works if we remove the first element instead: layer.wlist.remove(layer.wlist[0])
```

I am using keras-nightly.

**Comment by fchollet** [comment]
Thanks for the report. The untracking feature is WiP, I don't think it's used anywhere and likely not tested either. I'm curious how you ran into this bug?

**Comment by fchollet** [comment]
I think the fix would be to rely on `id()` to find the element's index in the list and then pop the element by index instead of by value.

**Comment by fchollet** [comment]
I pushed a fix, please check that it works for you.

**Comment by nhuet** [comment]
It works thx!

(about how i ran into the bug: I am afraid i did use layer._tracker which I am not supposed to. This is because a feature request I might have about sharing weights across layers. But it seems this is not possible with the current api by design as you said in this [issue](https://github.com/keras-team/keras/issues/18419#issuecomment-1731867106). I will still post my feature request to discuss it in a more appropriate place)

**Comment by nhuet** [comment]
I opened this issue: #18821 related to the feature request i talked about.
