### ISSUE TITLE
layer was never built but weights file lists have variables

### ISSUE THREAD

**Issue by innat** [keras-team/keras#18823]
I've simple model built in tf.keras 2.12. To move keras v3, I tried 

- save weight from tf.keras as `.save_weights("model.weights.h5")`
- translate tf.keras to keras v3
- tried to load weight `model.load_weights("model.weights.h5")`

But it gives error, saying some layers were not built but the weights have states. Following are the model (translated to keras v3) and attempt.

```python
import tensorflow as tf
import keras
from keras import layers
from keras import ops

class SubModel(keras.Model):
    def __init__(self, num_layer_norm):
        super().__init__()
        self.dense_layers = [
            layers.Dense(64, activation='relu') for _ in range(num_layer_norm)
        ]
        self.layer_norms = [
            layers.LayerNormalization() for _ in range(num_layer_norm)
        ]
        self.output_layer = layers.Dense(32, activation='relu')

    def call(self, inputs):
        x = inputs
        for i, (dense, layer_norm) in enumerate(zip(self.dense_layers, self.layer_norms)):
            
            if i < 2:
                continue
                
            x = dense(x)
            x = layer_norm(x)
        output = self.output_layer(x)
        return output

class CombinedModel(keras.Model):
    def __init__(self, num_submodels, num_layer_norm):
        super().__init__()
        self.submodels = [
            SubModel(num_layer_norm) for _ in range(num_submodels)
        ]
        self.combine_layer = layers.Dense(
            10, activation='softmax'
        )

    def call(self, inputs):
        submodel_outputs = [submodel(inputs) for submodel in self.submodels]
        combined_output = ops.concatenate(submodel_outputs, axis=-1)
        final_output = self.combine_layer(combined_output)
        return final_output
```
```python
num_submodels = 5
num_layer_norm = 10
model = CombinedModel(num_submodels, num_layer_norm)
model.build(input_shape=(None, 100))  
model.summary()
```
> /opt/conda/lib/python3.10/site-packages/keras/src/layers/layer.py:357: UserWarning: `build()` was called on layer 'combined_model_2', however the layer does not have a `build()` method implemented and it looks like it has unbuilt state. This will cause the layer to be marked as built, despite not being actually built, which may cause failures down the line. Make sure to implement a proper `build()` method.

```python
model.load_weights(
    'model.weights.h5', 
)
```

> ValueError: Layer 'dense_167' was never built and thus it doesn't have any variables. However the weights file lists 2 variables for this layer.
In most cases, this error indicates that either:

> 1. The layer is owned by a parent layer that implements a `build()` method, but calling the parent's `build()` method did NOT create the state of the child layer 'dense_167'. A `build()` method must create ALL state for the layer, including the state of any children layers.

> 2. You need to implement the `def build_from_config(self, config)` method on layer 'dense_167', to specify how to rebuild it during loading. In this case, you might also want to implement the method that generates the build config at saving time, `def get_build_config(self)`. The method `build_from_config()` is meant to create the state of the layer (i.e. its variables) upon deserialization.

**Comments**

- The same model works just fine in tf.keras 2.12, saving and reloading, no complain.
- Skipping some layer computation in `SubModel` might cause this issue. 
- If such approach is valid for tf.keras 2.12, this should also valid for keras v3. Was it bug or is it now?
- The above error log messages give some intuition ( override the `build` method, etc.), but this is expensive to comply on actual model.
- Translating is not going smooth!

**Comment by fchollet** [comment]
Keras 3 is more strict than Keras 2 about state creation. In all cases the solution is to implement a proper `build()` method on your layers/models.

If you can't be bothered writing a symbolic one, just use `build()` to create dummy data and then call the model eagerly.

**Comment by innat** [comment]
Thanks for the response.  Actually, writing a new model with new API is okay. But adding new components to old models can be expensive, especially if the amount is big. Keras 3 becomes more strict for state creating, I think that's because of supporting all backend. That's okay, I will revisit this issue soon, report you back. Thank you for all the support.

**Comment by fchollet** [comment]
> I think that's because of supporting all backend

It's for JAX mainly. TF can create new state during function tracing, but in JAX all state must be created in advance of any tracing. So Keras needs to be able to create all model state in advance.

**Comment by innat** [comment]
Thanks @fchollet 

I rewrite the above sample model to keep align with new API. The model build well and `weights.h5` saving and reloading also work. But `.keras` reloading gives above **no-yet-build** error.

```python
class SubModel(keras.Model):
    def __init__(self, num_layer_norm, **kwargs):
        super().__init__(**kwargs)
        self.num_layer_norm = num_layer_norm
    
    def build(self, input_shape):
        self.dense_layers = [
            layers.Dense(64, activation='relu') for i in range(self.num_layer_norm)
        ]
        self.layer_norms = [
            layers.LayerNormalization() for _ in range(self.num_layer_norm)
        ]
        self.output_layer = layers.Dense(32, activation='relu')

    def call(self, inputs):
        x = inputs
        for i, (dense, layer_norm) in enumerate(
            zip(self.dense_layers, self.layer_norms)
        ):
            x = dense(x)
            x = layer_norm(x)
        output = self.output_layer(x)
        return output
    
    def get_config(self):
        config = super().get_config()
        config.update(
            {
                "num_layer_norm": self.num_layer_norm,
            }
        )
        return config
```
```python
@keras.saving.register_keras_serializable('combined.model')
class CombinedModel(keras.Model):
    def __init__(self, num_submodels, num_layer_norm, **kwargs):
        super().__init__(**kwargs)
        self.num_submodels = num_submodels
        self.num_layer_norm = num_layer_norm
        
    def build(self, input_shape):
        self.submodels = [
            SubModel(self.num_layer_norm) for _ in range(self.num_submodels)
        ]
        self.combine_layer = layers.Dense(
            10, activation='softmax', name='combined_dense', dtype='float32'
        )

    def call(self, inputs):
        submodel_outputs = [submodel(inputs) for submodel in self.submodels]
        combined_output = ops.concatenate(submodel_outputs, axis=-1)
        final_output = self.combine_layer(combined_output)
        return final_output
    
    def get_config(self):
        config = super().get_config()
        config.update(
            {
                "num_submodels": self.num_submodels,
                "num_layer_norm": self.num_layer_norm
            }
        )
        return config
```

Test

```python
num_submodels = 5
num_layer_norm = 10
model = CombinedModel(num_submodels, num_layer_norm)
model(tf.ones(shape=(2, 100))) 
model.summary() # OK
```

State saving and reloading works.

```python
# OK
model.save_weights('custom.weights.h5')
new_model = CombinedModel(num_submodels, num_layer_norm)
new_model(tf.ones(shape=(2, 100))) 
new_model.load_weights("custom.weights.h5")
```
But, saving in `.keras` format, it breaks on `self.combine_layer` (built-in dense layer) of `CombinedModel` model above. 

```python
# NOT OK
model.save('custom.keras')
check = keras.models.load_model(
   'custom.keras'
)
```

> ValueError: Layer 'combined_dense' was never built and thus it doesn't have any variables. However the weights file lists 2 variables for this layer.
In most cases, this error indicates that either:
> 1. The layer is owned by a parent layer that implements a `build()` method, but calling the parent's `build()` method did NOT create the state of the child layer 'combined_dense'. A `build()` method must create ALL state for the layer, including the state of any children layers.
> 2. You need to implement the `def build_from_config(self, config)` method on layer 'combined_dense', to specify how to rebuild it during loading. In this case, you might also want to implement the method that generates the build config at saving time, `def get_build_config(self)`. The method `build_from_config()` is meant to create the state of the layer (i.e. its variables) upon deserialization.
