### ISSUE TITLE
Keep GitHub Actions and Python dependencies up-to-date with Dependabot

### ISSUE THREAD

**Issue by pnacht** [keras-team/keras#18833]
I've noticed Keras is using some older versions of GitHub Actions (i.e `actions/stale@v5`, when `@v8` is available). These can be kept up-to-date with dependabot, ensuring Keras runs the latest versions of Actions after a new major version. The status of the CI tests will ensure there are no breaking changes.

There are also a few Python dependencies with new versions (torch and torchvision, which are fully pinned in `requirements-torch-cuda.txt`). Dependabot can also keep an eye on these if you wish.

I'll send a PR setting up dependabot to update all these dependencies so you can take a look.

**Comment by sachinprasadhs** [comment]
Thanks for the issue report, on successful merging of the linked PR, the issue will be closed.
Going forward, you can create only PR with the details.
