### ISSUE TITLE
Link to release announcement broken

### ISSUE THREAD

**Issue by timoklein** [keras-team/keras#18841]
When trying to access the site https://keras.io/keras_3/ from https://github.com/keras-team/keras/releases/tag/v3.0.0, it doesn't exist.  
Should this instead link to https://keras.io/keras_core/announcement/?

**Comment by aliencaocao** [comment]
https://keras.io/guides/migrating_to_keras_3/
this one also broken

**Comment by aliencaocao** [comment]
Works for me, thanks

**Comment by timoklein** [comment]
Looks good to me

**Comment by sachinprasadhs** [comment]
Closing the issue since the issue is resolved. Thanks for confirming.
