### ISSUE TITLE
numpy backend requires jax?

### ISSUE THREAD

**Issue by hmaarrfk** [keras-team/keras#18840]
It seems that the numpy backend imports jax

https://github.com/keras-team/keras/blob/9c675a9a45e5e8244163fea82efc6066722608a1/keras/backend/numpy/image.py#L1

and seems to use it below:

```python
    return np.array(
        jax.image.resize(image, size, method=interpolation, antialias=antialias)
    )
```

is that intention?

**Comment by SuryanarayanaY** [comment]
It seems numpy backend has Jax dependency. I can find it in[ backend/numpy/nn.py](https://github.com/keras-team/keras/blob/9c675a9a45e5e8244163fea82efc6066722608a1/keras/backend/numpy/nn.py) also.

**Comment by fchollet** [comment]
Yes, that's intentional. We found that when implementing nn ops like conv or pooling, a low-level pure numpy implementatoin was vastly less performant than jax, so we just use jax for these ops.

**Comment by hmaarrfk** [comment]
I feel like this is seriously misleading. numpy and Jax offer drastically different compilation, testing, and integration challenges.

installing Jax and installing numpy can be quite different in resource limited environments.

I think that:

1. users of the pure numpy backend should expect slower, albeit numerically equivalent/similar to that of other more accelerated backends.
2. if you want, I think a hybrid approach if "trying to use Jax, but falling back to the much slower numpy operators" may be acceptable, but it may create surprising behavior.

for example, I would expect a backend of 
1. "numpy" not to depend on Jax at all.
3. "numpy+Jax" to use Jax in select locations
4. "jax" primarily use Jax 

as is, users cannot use the numpy backend at all without Jax. in my mind, it just shouldn't be called "numpy backend"

I am not saying this in any hostile way, just as a packager that tried to test things with numpy only and was quite surprised that I needed a heavy dependency like Jax to get any operators to work.

If my tone is negative, it is because in my mind, you hastily closed this issue without giving the chance to respond.
would it be acceptable to reopen this issue and at least acknowledge to others that this is a present limitation of the 3.0.0 version? Closing this issue just seems wrong.

**Comment by mthiboust** [comment]
I second the comment of @hmaarrfk. I think it would be useful to have the possibility of having a lightweight keras installation powered by the numpy backend in order to make small inference tasks in limited environments.

**Comment by fchollet** [comment]
That's a reasonable view. There's definitely a huge slowdown however.

If you'd like to open a PR to revert some ops to pure numpy implementation, we can consider it.

**Comment by mthiboust** [comment]
Thanks François for your answer. I see that the functions involved are `jax.image.resize`, `jax.numpy.fft.*` and `jax.lax.conv_*`.  Don't know yet if I'll work on this PR.

**Comment by fchollet** [comment]
The fft ops should be a trivial change since they're already available in numpy.

**Comment by jamesmyatt** [comment]
@fchollet Can you reopen this issue please? Especially if you're open to someone working on it. Otherwise people will keep opening new issues (e.g. #20966).

I agree 100% with @hmaarrfk  and everyone else. If you select the numpy backend, then you accept that some operations will be much slower than the jax one, otherwise what's the point. If you want the fastest operations, then you expect to select one of the other backends. I don't see the point of "numpy+jax": I would either want the minimal dependencies of the "numpy" backend or the blazing fast operations of the "jax" one. But I don't mind if the "numpy" backend depends on "scipy" or similar.
