### ISSUE TITLE
No GPU acceleration on Macos 14.1.1 using Keras 3.0.0

### ISSUE THREAD

**Issue by mocher72** [keras-team/keras#18844]
Testing some example code which is running on tensorflow 2.15 with tensorflow-metal installed.
When I run the same code but converted to Keras 3.0.0 with tf as the backend the model does not run on the GPU and the fit process is very slow.
Is there any way to probe the keras code to see if GPU is available similar to the tf command.
`tf.config.list_physical_devices()`

**Comment by SuryanarayanaY** [comment]
Hi @mocher72 ,

AFAIK, for utilising GPU you still need to have a backend like Tensorflow/Pytorch etc. You need to install for example say for TF backend, [requirements-tensorflow-cuda.txt](https://github.com/keras-team/keras/blob/5b9f1b70dca1ac3b7a307f0ddbbe5df816dfe5b7/requirements-tensorflow-cuda.txt).

Similarly we have other `requirements_xxx_cuda.txt` files for respective backends which we need to install for GPU utilization.

**Comment by mocher72** [comment]
Thanks @SuryanarayanaY I had installed via pip so for some reason it had not updated the tensorflow install to use the nightly build.
I have installed the tf-nightly using `pip install tf-nightly` and this has installed version 2.16.0.dev20231018 along with tf-nightly-macos.
I have rerun the benchmark and it is now running with GPU acceleration with epoch times similar to using tf.keras code.
