### ISSUE TITLE
Execution time in model.fit

### ISSUE THREAD

**Issue by ramakc153** [keras-team/keras#18854]
i got issue when i try to train my model using keras 3.0. the steps per epoch take really long time when i run it on keras 3.0 compared to when i'm using keras_core. Is there anyway to fix it ?
Here is the screenshot on keras 3.0 
![image](https://github.com/keras-team/keras/assets/72650027/4338f3f9-9a5c-4e57-a40d-7832a1b2c521)

and this one on keras-core
![image](https://github.com/keras-team/keras/assets/72650027/7e893ec5-4157-4114-9d83-01a90ef03e5e)

layers used in this model are : 
```py
def create_model():
    model = keras.Sequential([
        Input((778, 1)),
        Conv1D(96, 1, activation = 'relu'),
        Conv1D(352, 1,  activation = 'relu'),
        Conv1D(224, 1,  activation = 'relu'),
        Conv1D(160, 1,  activation = 'relu'),
        Conv1D(320, 1,  activation = 'relu'),
        Bidirectional(LSTM(192, return_sequences = True, activation = 'tanh')),
        Bidirectional(LSTM(384, return_sequences = True, activation = 'tanh')),
        Bidirectional(LSTM(160, return_sequences = True, activation = 'tanh')),
        Dropout(0.2),


        Dense(4, activation = 'softmax')
    ])
    model.compile(loss = 'sparse_categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])
    return model
```
i run the model on google collab. is there any way to fix it ? Thanks

**Comment by fchollet** [comment]
This sort of issue is usually because you're not using the GPU.

1. What backend is this?
2. Can you check if the backend can detect the GPU?

**Comment by fchollet** [comment]
I can reproduce the issue. The issue is specifically with the LSTM layers. Most likely the problem is that cuDNN is not being used/detected by Keras 3 in this case. Will look into it.

**Comment by ramakc153** [comment]
Thanks Keras team. everything is working well right now.
