### ISSUE TITLE
Feature duplication on model.save() and keras.saving.save_model()

### ISSUE THREAD

**Issue by VertexToEdge** [keras-team/keras#18864]
When I was reading the code of model saving, I got strange feeling.

https://github.com/keras-team/keras/blob/724321c7b39a90f6125b79931284aa9932c673a0/keras/models/model.py#L294-L297
It says `model.save()` is an alias for `keras.saving.save_model()`. But each of these method are implemented same feature.

https://github.com/keras-team/keras/blob/f0b7062e4c6a62c521af491b09d97f009b1add0b/keras/models/model.py#L268
https://github.com/keras-team/keras/blob/f0b7062e4c6a62c521af491b09d97f009b1add0b/keras/saving/saving_api.py#L19

these method's code are almost same. this duplicated feature will cause increase management point of code and It seems already started version fragmentation.

I think `model.save()` method can be removed and be modified to just calling `keras.saving.save_model()`.

Can I refactor this code?

**Comment by fchollet** [comment]
Yes, feel free to open a PR to reduce code redundancy. Thanks!
