### ISSUE TITLE
Bidirectional LSTM error

### ISSUE THREAD

**Issue by ASEM000** [keras-team/keras#18861]
The following throw ```ValueError: All input arrays must have the same shape.``` when `return_state=True` on `jax` backend, but works fine on `torch` backend.

```python
import os
os.environ["KERAS_BACKEND"] = "jax"
import keras
import jax
import jax.numpy as jnp 
input = jnp.ones([10, 2])
keras.layers.Bidirectional(keras.layers.LSTM(4, return_sequences=True, return_state=True))(input[None])
```

**Comment by fchollet** [comment]
Thanks for the report! There was in fact a bug in `Bidirectional` with `return_state=True`. I have fixed it at HEAD. Please check that it works for you.
