### ISSUE TITLE
model output inconsistent on tensorflow and theano backends

### ISSUE THREAD

**Issue by cheyennee** [keras-team/keras#18866]
[model.zip](https://github.com/keras-team/keras/files/13527190/model.zip)
**problem**
I trained a model on both TensorFlow and Theano backends, saving the outputs of all layers for comparison. The outputs of the second layer and beyond differ between the two implementations. Attached you will find the model file (tensorflow.h5), dataset directory (containing data and ground truth), weight directory (containing weights for all layers), and layer outputs directory.
**version**
keras: 2.3.1
tensorflow: 2.0.0
theano: 1.0.4
python: 3.6

**Comment by fchollet** [comment]
Thanks for the report. The Theano backend has been deprecated since 2019 and we do not process Theano related issues. I suggest you upgrade to Keras 3.
