### ISSUE TITLE
Why is Keras 3 slower than Keras 2 with the same code?

### ISSUE THREAD

**Issue by pass-lin** [keras-team/keras#18872]
I recently developed a pre-trained model library that is compatible with both Keras 2 and Keras 3. I manually aligned the APIs from Keras 2 and TensorFlow in Keras 3, and then rewrote a set of pre-trained models using the ops API in Keras 3. You can see my ongoing work at 'https://github.com/pass-lin/bert4keras3/tree/main'. However, I noticed that when running 'basic_extract_features.py', the CPU performance based on Keras 2 is significantly better than any backend in Keras 3. Can you help me understand the reason for this? My platform is 1660ti + i7-9750H.

**Comment by mthiboust** [comment]
Hello @pass-lin 

Have you found a solution to your issue? I may be running into a similar issue on my side when running my Keras 3 code on the same CPU i7-9750H. See https://github.com/keras-team/keras/issues/19601
