### ISSUE TITLE
Training as BackgroundJob in FastAPI

### ISSUE THREAD

**Issue by DavidAdamczyk** [keras-team/keras#18879]
I would like to use training in BackgroundJob in FastAPI because I need to initiate the training process with one HTTP request, and I would like to use a second HTTPS request to check the training status (I use a custom callback for this). Unfortunately, there is an issue with the training in BackgroundJob:

```bash
model.fit(
  File "/usr/local/lib/python3.11/dist-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.11/dist-packages/keras/src/engine/data_adapter.py", line 949, in _peek_and_restore
    peek = next(x)
           ^^^^^^^
ValueError: generator already executing
```

I use this in my code:
```python
async def run_training():
    app.model.fit(
        ....
        )
    await asyncio.sleep(3)
```

```python
@app.post("/train")
async def handle_train(train_req: TrainRequest, background_tasks: BackgroundTasks):
    background_tasks.add_task(
            run_training,
            train_generator, num_train, num_val, batch_size, epochs, callbacks
            )
```

What is the correct way to execute the training process in a BackgroundJob?

**Comment by sachinprasadhs** [comment]
Hi,

This issue does not seem to be related to `Keras`, it's specific to FastAPI.

You can close the issue here and open a new issue in FastAPI repo https://github.com/tiangolo/fastapi/issues
