### ISSUE TITLE
Is tensorflow necessary for keras

### ISSUE THREAD

**Issue by Noob225566** [keras-team/keras#18880]
I install keras,theano and pythorch in termux in android i didn't install tensorflow because keras said we can change its backend to pytorch or theano that's why i didn't install tensorflow but i try all the ways possible to change its backend but nothing works there is no keras.json file so i create it my own but didn't work i try all ways keras listed to change its backend but didn't work is tensorflow necessary for keras because everytime i run keras i got a error that no module found tensorflow.comapt.v2 as tf plz help me and respond me as soon as possible

**Comment by fchollet** [comment]
With Keras==3.0.0 you do not need to have TensorFlow installed (unless for specific features like tf.data support).

**Comment by Noob225566** [comment]
Yeah i installed keras 3.0.0 but i can't see any keras.json file even i try every way possible to change its backend to pytorch or theano but nothing worked whenever i try to run keras in termux i got no module named tensorflow.compat.v2 as tf even i installed keras-core in termux (but can't install h5py for keras-core so i install keras-core without h5py) but it also don't work plz respond me as soon as possible and help me

**Comment by SuryanarayanaY** [comment]
Hi @Noob225566 ,

Keras3 won't support Theano backend. But Pytorch is supported. Either you can export the environment variable KERAS_BACKEND using `export KERAS_BACKEND="torch"` or you can edit your local config file at` ~/.keras/keras.json` to configure your backend.

Please refer this [source](https://github.com/keras-team/keras#configuring-your-backend) for more details.

**Comment by Noob225566** [comment]
I know even i try every possible way but i can't got successfull in changing keras's backend to pytorch there is no .keras folder or keras.json file even i created it manually it doesn't work

**Comment by SuryanarayanaY** [comment]
Hi @Noob225566 ,

Could you please confirm which version of keras you have installed ? What is the installation instructions you have followed?

You may try with `pip install keras --upgrade ` to ensure kears3 being installed and print the` keras.__version__` also to double check.

**Comment by Noob225566** [comment]
Sorry bro i accidentally delete termux that's why keras and keras-core got deleted so now i need to restore them i will tell you when i install it because till i have issues installing keras latest version 3.0.0 so i will tell you later

**Comment by Noob225566** [comment]
Sorry bro i can't install keras in termux in android everytime i try to install it(even with all the methods)i got errors because of dm-tree and h5py and these are dependinces of keras and i am unable to install these dependinces  when i try to install dm-tree i got cmake error and i can't properly install cmake second when i try to install h5py i got cython compile error which i am unable to fix

**Comment by SuryanarayanaY** [comment]
Hi @Noob225566 ,

I hope you got clarity on tensorflow dependency on keras. Could you please feel free to close the issue? Thanks!
