### ISSUE TITLE
when loss function is poisson, the loss of model is NaN

### ISSUE THREAD

**Issue by cheyennee** [keras-team/keras#18886]
I have a keras [model](https://drive.google.com/file/d/1RQSPgSw3Rfr7n5fVH6sXrv1R_JtE5BD-/view?usp=drive_link) here. When I use `poisson` as the loss function of this model, the loss value will be NaN. However, when I use other loss function, such as `mean_absolute_error`, `mean_squared_error` and so on, the loss outputs normally. I'm not sure if there is a bug in `poisson` loss function.

Repo snippet code is in [colab](https://colab.research.google.com/drive/1hJWHEM9FK_QblGYy2A0gQkRiBalfil0z#scrollTo=4EBkQRpwfsRn). Need to download this keras model first.

**Comment by SuryanarayanaY** [comment]
Hi @cheyennee ,

I have replicated the reported behaviour and attaching [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/9348b9042fa4bf7c1864450aa5d8bbf5/18886.ipynb) here.

The poisson loss generating Nan as loss value though MAE is OK.

**Comment by hertschuh** [comment]
Hi @cheyennee ,

I wasn't able to test your example. When I load the model at https://drive.google.com/file/d/1RQSPgSw3Rfr7n5fVH6sXrv1R_JtE5BD-/view?usp=drive_link
I get the following error:
```
ValueError: The shape of the target variable and the shape of the target value in `variable.assign(value)` must match. variable.shape=(12,), Received: value.shape=(2,). Target variable: <KerasVariable shape=(12,), dtype=float32, path=27_batch_normalization/moving_mean>
```

Additionally, can you paste the content of your `~/.keras/keras.json` file here?

Thanks,
Fabien

**Comment by SuryanarayanaY** [comment]
Hi @cheyennee ,

The snippet not working with keras3. Getting the same error as stated in above [comment](https://github.com/keras-team/keras/issues/18886#issuecomment-1854831548). Please refer attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/eb654bd5af6ed08e7f1370f8fac5f5a7/18886_keras3.ipynb).

The reported issue can be replicable with Keras2  but with not with Keras3.

Can you please report the issue at [tf-keras](https://github.com/keras-team/tf-keras) repo as this is not reproducible with keras3.
