### ISSUE TITLE
Unknown decay: 'WarmUp' error  loading custom objects using tf.keras.models.load_model('saved_model/cnn_model.h5', custom_objects={'KerasLayer':hub.KerasLayer, 'AdamWeightDecay': optimizer}

### ISSUE THREAD

**Issue by sdanie53** [keras-team/keras#18887]
I am trying to load a custom model that has been trained using custom objects (custom layer and optimizer). When I load the saved model I get this error:
ValueError: Unknown decay: 'WarmUp'. Please ensure you are using a `keras.utils.custom_object_scope` and that this object is included in the scope. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.

My code for loading the saved model:
```
read_dictionary = np.load('saved_model/optimizer_config.npy',allow_pickle='TRUE').item()
optimizer = optimization.create_optimizer(init_lr=read_dictionary['learning_rate']['config']['initial_learning_rate'],
                                          num_train_steps=read_dictionary['learning_rate']['config']['decay_schedule_fn']['config']['decay_steps'],
                                          num_warmup_steps=read_dictionary['learning_rate']['config']['warmup_steps'],
                                          optimizer_type='adamw')
my_loaded_model = tf.keras.models.load_model('saved_model/cnn_model.h5', custom_objects={'KerasLayer':hub.KerasLayer, 'AdamWeightDecay': optimizer}) 
```

nlp package being used: tf-models-official 2.15.0

**Comment by sachinprasadhs** [comment]
Hi,

Could you please install Keras 3 using` !pip install keras --upgrade` and let us know with the reproducible code, if you still face an error.

**Comment by sdanie53** [comment]
I tried updating to keras 3. Looks like there is a dependency issue with the latest tensorflow version 2.15 
I tried upgrading tensorflow as well and it just reverts keras back to 2.15

**Comment by sachinprasadhs** [comment]
First you need to install Tensorflow 2.15 first and then install `Keras 3`.
Tensorflow has internal Keras package dependency.

Follow the Migration guide to replace `tf.keras` instance to `keras` https://keras.io/guides/migrating_to_keras_3/

**Comment by sdanie53** [comment]
I installed tensorflow 2.15 first and then installed keras 3. Here are the versions installed:

>>> print(keras.__version__)
3.0.1.dev2023120703
>>> import tensorflow
>>> print(tensorflow.__version__)
2.15.0

I get this error when trying to import the official.nlp package:
from official.nlp import optimization
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[1], line 10
      8 import tensorflow_hub as hub
      9 from keras import layers, Model
---> 10 from official.nlp import optimization  
     11 from keras.callbacks import EarlyStopping
     12 import tensorflow_text as text

File ~/SageMaker/.persisted_conda/anxiety/lib/python3.10/site-packages/official/nlp/optimization.py:21
     18 import gin
     19 import tensorflow as tf
---> 21 from official.modeling.optimization import lamb
     22 from official.modeling.optimization import legacy_adamw
     24 AdamWeightDecay = legacy_adamw.AdamWeightDecay

File ~/SageMaker/.persisted_conda/anxiety/lib/python3.10/site-packages/official/modeling/optimization/__init__.py:22
     20 from official.modeling.optimization.configs.optimizer_config import *
     21 from official.modeling.optimization.ema_optimizer import ExponentialMovingAverage
---> 22 from official.modeling.optimization.lr_schedule import *
     23 from official.modeling.optimization.optimizer_factory import OptimizerFactory
     24 from official.modeling.optimization.optimizer_factory import register_optimizer_cls

File ~/SageMaker/.persisted_conda/anxiety/lib/python3.10/site-packages/official/modeling/optimization/lr_schedule.py:89
     83 PolynomialDecayWithOffset = _make_offset_wrapper(
     84     "PolynomialDecayWithOffset", tf.keras.optimizers.schedules.PolynomialDecay)
     85 ExponentialDecayWithOffset = _make_offset_wrapper(
     86     "ExponentialDecayWithOffset",
     87     tf.keras.optimizers.schedules.ExponentialDecay)
     88 CosineDecayWithOffset = _make_offset_wrapper("CosineDecayWithOffset",
---> 89                                              tf.keras.experimental.CosineDecay)
     92 class LinearWarmup(tf.keras.optimizers.schedules.LearningRateSchedule):
     93   """Linear warmup schedule."""

AttributeError: module 'keras._tf_keras.keras' has no attribute 'experimental'


I even tried upgrading the nlp package using:
pip install --upgrade keras-nlp-nightly

**Comment by sdanie53** [comment]
I was able to fix the issue by importing the WarmUp class and then passing it as a custom object while loading the model. 

from official.nlp.optimization import WarmUp
read_dictionary = np.load('saved_model/optimizer_config.npy',allow_pickle='TRUE').item()
optimizer = optimization.create_optimizer(init_lr=read_dictionary['learning_rate']['config']['initial_learning_rate'],
                                          num_train_steps=read_dictionary['learning_rate']['config']['decay_schedule_fn']['config']['decay_steps'],
                                          num_warmup_steps=read_dictionary['learning_rate']['config']['warmup_steps'],
                                          optimizer_type='adamw')
my_loaded_model = tf.keras.models.load_model('saved_model/cnn_model.h5', custom_objects={'KerasLayer':hub.KerasLayer, 'AdamWeightDecay': optimizer, 'WarmUp': WarmUp})

**Comment by sachinprasadhs** [comment]
If your issue is resolved, could you please close the issue. Thanks!
