### ISSUE TITLE
Constraints not applied

### ISSUE THREAD

**Issue by salemileandro** [keras-team/keras#18883]
Hi! First, I'd like to thank those who contributed to Keras 3.0! The revamp looks beyond amazing!!! 😍 

**I think there is a bug with the constraints: they are not applied**. I've tried both with pre-implemented constraints and custom implementation, and they both fail. Here, I'm sharing a gist with Dense layers (I've also tried custom layers and it failed too).
https://gist.github.com/salemileandro/1afecb8ec5ac7ca80f413ac287dccd03

For ``Clip``, the subclass of ``keras.constraints.Constraint``, the gist I'm sharing uses
```python
    def __call__(self, w):
        w = ops.convert_to_tensor(w)
        min_value = ops.ones_like(w, dtype="float32") * self.min_value
        max_value = ops.ones_like(w, dtype="float32") * self.max_value
        return ops.clip(w, min_value, max_value)
```
but I was first using (and it failed too)
```python
    def __call__(self, w):
        w = ops.convert_to_tensor(w)
        return ops.clip(w, self.min_value, self.max_value)
```

**Comment by fchollet** [comment]
Thanks for the report! As it turns out, constraints are applied by the optimizer, but in this case the constraints passed to the `Dense` layer were never set on the variables. It seems this was also the case for another layer in the codebase (`MultiHeadAttention`). We're fixing it.
