### ISSUE TITLE
keras outputs wrong pool_size in `keras.layers.AveragePooling1D`

### ISSUE THREAD

**Issue by cheyennee** [keras-team/keras#18899]
The pool_size of keras.layers.AveragePooling1D should be an integer. When I set an integer to keras.layers.AveragePooling1D, then outputs the pool_size of AveragePooling1D layer, I get a tuple. What a surprise😂

repo code:
```
import keras
layer = keras.layers.AveragePooling1D(pool_size=2)
print(layer.pool_size)
```
output:
```
(2,)
```

**Comment by cheyennee** [comment]
Hi, @sachinprasadhs . I think a distinction should be made between the two. I got this parameter to construct a new `AveragePooling1D` layer, but it doesn't support tuples as pool_size, which causes an error. IMO, If the output of pool_size is a tuple, I think a tuple value of pool_size should also work.

**Comment by sachinprasadhs** [comment]
For an int value, you can just use the below code.

```
import keras
layer = keras.layers.AveragePooling1D(pool_size=2)
print(layer.pool_size[0])
```
