### ISSUE TITLE
`add_variable` vs `add_weight`

### ISSUE THREAD

**Issue by ariG23498** [keras-team/keras#18891]
`add_variable` is termed as an alias to `add_weight`. Is there any particular reason behind this API?

https://github.com/keras-team/keras/blob/327360e617771d4f34e2b4bf4810ed8b413709bb/keras/layers/layer.py#L423

**Comment by mattdangerw** [comment]
It is a bit confusing, but essentially variables are a super set of weights, that contain other variables that will be compiled (at least on some backends) but are not trainable floats.

In particular, jax random seeds are state, that must be passed explicitly to any jax compiled function. These are not trainable floats, so you would not want them in `model.weights`, but we do need an way to gather all state to pass to a jax compiled function, and `model.variables` is that.

**Comment by ariG23498** [comment]
That is super helpful!

Do you think we should document this inside of the docstrings from the method?

**Comment by mattdangerw** [comment]
Improving docs sounds good. We don't want to get overwhelmingly detailed, but do want to give users the right mental model. Currently we have

https://github.com/keras-team/keras/blob/aa055387f27d974a9a7a3eed8fdd9a2f2e589b6b/keras/layers/layer.py#L538-L545

https://github.com/keras-team/keras/blob/aa055387f27d974a9a7a3eed8fdd9a2f2e589b6b/keras/layers/layer.py#L586-L589

Though it looks like this is not yet all on keras.io

**Comment by haifeng-jin** [comment]
I believe the issue has been concluded. Feel free to reopen if you have more questions.

Thanks!
