### ISSUE TITLE
keras.ops.tril doesn't support dynamic shape with tensorflow backend

### ISSUE THREAD

**Issue by breadbread1984** [keras-team/keras#18890]
keras.ops.tril doesn't support tensor with unknown dimension with tensorflow backend.
it is OK with torch backend.
could you update keras.ops.tril implement with tensorflow ops to support input with unknown dimension?

```python
#!/usr/bin/python3

from os import environ
environ['KERAS_BACKEND'] = 'tensorflow'  # FAIL
#environ['KERAS_BACKEND'] = 'torch' # OK
import keras as K

def Test():
  inputs = K.Input((None, 100)) # inputs.shape = (batch x seq_len x hidden)
  attn = K.layers.Lambda(lambda x: K.ops.tril(K.ops.ones((K.ops.shape(x)[1],K.ops.shape(x)[1]))))(inputs)
  return K.Model(inputs = inputs, outputs = attn)

test = Test()
import numpy as np
print(test(np.random.normal(size = (1,10,100))).shape)
```

I find the following tensorflow implement support dimension with unknown dimension

```python
#!/usr/bin/python3

import tensorflow as tf

def Test():
  inputs = tf.keras.Input((None, 100))
  outputs = tf.keras.layers.Lambda(lambda x: tf.linalg.band_part(tf.ones((tf.shape(x)[1], tf.shape(x)[1])), -1, 0))(inputs)
  return tf.keras.Model(inputs = inputs, outputs = outputs)

test = Test()
import numpy as np
print(test(np.random.normal(size = (1,10,100))))
```

**Comment by SuryanarayanaY** [comment]
Hi @breadbread1984 ,

I have replicated the issue with TF backend.Attached [gist-tf](https://colab.sandbox.google.com/gist/SuryanarayanaY/73047a12f402fb7b50a9e4335c99e65e/18890_tf-backend.ipynb) for reference.

It works with Torch as reported.[gist-torch](https://colab.sandbox.google.com/gist/SuryanarayanaY/26e1503ce61fba33edc1486e1bf502ae/18890_torch-backend.ipynb)
