### ISSUE TITLE
Saving custom model with keras.layers.flatten raised some issues

### ISSUE THREAD

**Issue by soup10** [keras-team/keras#18903]
When I made a custom model by adding Flatten layer onto ResNet and saved the model by

`keras.models.save_model(model, "path")`

, I got the following error

```
File ~/anaconda3/lib/python3.10/site-packages/keras/src/layers/reshaping/flatten.py:72, in Flatten.compute_output_spec(self, inputs)
     71 def compute_output_spec(self, inputs):
---> 72     output_shape = self.compute_output_shape(inputs.shape)
     73     return KerasTensor(
     74         shape=output_shape, dtype=inputs.dtype, sparse=inputs.sparse
     75     )

AttributeError: Exception encountered when calling Flatten.call().

'list' object has no attribute 'shape'

Arguments received by Flatten.call():
  • args=(['<KerasTensor shape=(10, 15, 20, 2048), dtype=float32, sparse=False, name=keras_tensor_1070>'],)
  • kwargs=<class 'inspect._empty'>
```

, where the type of parameter "inputs" is supposed to be <KerasTensor> but was [<KerasTensor>] actually.

I could solve this issue by changing "compute_output_spec" function in "File ~/anaconda3/lib/python3.10/site-packages/keras/src/layers/reshaping/flatten.py" into

```
def compute_output_spec(self, inputs):
        #print(type(inputs), type(inputs[0]))
        if type(inputs)==list:
            output_shape = self.compute_output_shape(inputs[0].shape)
            return KerasTensor(
                shape=output_shape, dtype=inputs[0].dtype, sparse=inputs[0].sparse
            )
            
        else:
            output_shape = self.compute_output_shape(inputs.shape)
            return KerasTensor(
                shape=output_shape, dtype=inputs.dtype, sparse=inputs.sparse
            )
```

However I got same sort of error at function "call" in the same file when loading the model. In this error, on the other hand, the type of parameter "inputs" was 

[Traced<ShapedArray(float32[1,15,20,2048])>with<DynamicJaxprTrace(level=1/0)>]

, which I found difficult to fix by myself since it uses new backend. 

I hope this error will be fixed.

**Comment by sampathweb** [comment]
Thanks for raising this issue.
The reason you are getting this error is, `functional` model gives a list of outputs.  And `flatten` layer doesn't take a list of tensors.  So if you modify your code to `keras.layers.Flatten()(model.outputs[0])`, it would work fine.  Please re-open if it doesn't resolve the issue.

**Comment by soup10** [comment]
Thank you for your kind reply.

Actually, I figured out the cause of the error and it was because I was using preprocess_input function not from keras.applications.resnet but from tensorflow.keras.applications.resnet50 although I made my model with keras(not tensorflow.keras). The error came not to come out after I fixed that point.

Thank you anyway.

**Comment by MaduraPrasad** [comment]
> Thanks for raising this issue. The reason you are getting this error is, `functional` model gives a list of outputs. And `flatten` layer doesn't take a list of tensors. So if you modify your code to `keras.layers.Flatten()(model.outputs[0])`, it would work fine. Please re-open if it doesn't resolve the issue.

I have similar issue , below is model build,

# Build the model on top of the base model
model = Sequential([
    base_model,
    Flatten(),
    Dense(256, activation='relu'),
    Dropout(0.5),
    Dense(num_classes, activation='softmax')
])
 Could plz help me to sort this out

**Comment by MaduraPrasad** [comment]
> Thanks for raising this issue. The reason you are getting this error is, `functional` model gives a list of outputs. And `flatten` layer doesn't take a list of tensors. So if you modify your code to `keras.layers.Flatten()(model.outputs[0])`, it would work fine. Please re-open if it doesn't resolve the issue.

**Comment by Stvchm9703** [comment]
same issue, with the Sequential modeling, the Flatten layer are casing by the loading model;
should it be the Sequential Model Design issue, or the SaveModel load_model issue ? 

```log
AttributeError: Exception encountered when calling Flatten.call().

'list' object has no attribute 'shape'

Arguments received by Flatten.call():
  • args=(['<KerasTensor shape=(None, 2048), dtype=float32, sparse=False, name=keras_tensor_9330>'],)
  • kwargs=<class 'inspect._empty'>

```

**Comment by ValentinMaftei** [comment]
Same issue for my code:

```
AttributeError: Exception encountered when calling Flatten.call().

'list' object has no attribute 'shape'

Arguments received by Flatten.call():
  • args=(['<KerasTensor shape=(None, 2048), dtype=float32, sparse=False, name=keras_tensor_367>'],)
  • kwargs=<class 'inspect._empty'>
```

**Comment by sachinprasadhs** [comment]
@ValentinMaftei , Could you please provide the code or open a new issue with the reproducible code to verify the bug from our side. Thank you.

**Comment by ValentinMaftei** [comment]
> @ValentinMaftei , Could you please provide the code or open a new issue with the reproducible code to verify the bug from our side. Thank you.

Here i create the model:
`model = createModel()

    hist = model.fit(trainData, epochs=10, validation_data=valData,
                     callbacks=[tensorboardCallback])

    model.save('resnet50Epoch10_v2.keras')`
    
For image preprocessing:
`    train_datagen = ImageDataGenerator(dtype = 'float32', preprocessing_function=keras.applications.resnet.preprocess_input)

    val_datagen = ImageDataGenerator(dtype = 'float32', preprocessing_function=keras.applications.resnet.preprocess_input)`

Here is the model:

```
def createModel():
    model = Sequential()

    pretrained_model = keras.applications.ResNet50(
        input_shape=(imgDataWidth, imgDataHeight, 3),
        include_top=False,
        weights='imagenet',
        pooling='avg',
        classes=4)

    for layer in pretrained_model.layers:
        layer.trainable = False

    model.add(pretrained_model)
    model.add(Flatten())
    model.add(Dense(1024, activation='relu'))
    model.add(Dropout(0.4))
    model.add(Dense(4, activation='softmax'))

    model.compile(optimizer=Adam(learning_rate=0.0001), loss='categorical_crossentropy', metrics=['accuracy'])

    return model
```

I get the error when i want to predict for only one image.

**Comment by sachinprasadhs** [comment]
@ValentinMaftei , Could you please provide sample toy example with sample input data and all the necessary details to run the code and debug. Preferably colab file.
