### ISSUE TITLE
Broken links to "Saving and serialization"

### ISSUE THREAD

**Issue by robertknight** [keras-team/keras#18905]
The "Saving and serialization" link on https://keras.io/api/ points to https://keras.io/api/saving/ which 404s.

Using an online link checker I found some other broken doc links too. Apologies this report isn't in a more convenient format. [Broken – Dr. Link Check.pdf](https://github.com/keras-team/keras/files/13604131/Broken.Dr.Link.Check.pdf)

**Comment by fchollet** [comment]
Thanks for the report. We're fixing it.
