### ISSUE TITLE
keras outputs differently in v2.14.0 and v2.3.1 on tensorflow backend

### ISSUE THREAD

**Issue by cheyennee** [keras-team/keras#18904]
I have a keras [model](https://drive.google.com/file/d/1RoNy5rs4vlOV37NmrTuRrf1GR_4FvY9V/view?usp=drive_link) and an [input](https://drive.google.com/file/d/126zU8p3Jm6HTqRoI4p1Lni1VMkM1QeGi/view?usp=drive_link). I use model to predict this input. I found that in keras v2.3.1, it predicts `nan`. However, in keras v2.14.0, it outputs normally.

repo code:
```
import keras
import numpy as np
print(keras.__version__)
from keras.datasets import mnist
(x_train,y_train),(x_test,y_test) = mnist.load_data()
model = keras.models.load_model('/content/322-tensorflow.h5')
input = np.load('/content/input.npy')
model.compile(loss='mean_squared_logarithmic_error', optimizer='adadelta')
history = model.fit(x_train, y_train)
model.predict(input)
```

outputs:
keras v2.14.0
```
WARNING:tensorflow:No training configuration found in the save file, so the model was *not* compiled. Compile it manually.
1875/1875 [==============================] - 27s 11ms/step - loss: 6202843795574403104768.0000
1/1 [==============================] - 0s 408ms/step
array([[-1902.7032 ,   141.09955,  -277.39343,  1343.9507 ,  1219.6061 ,
          893.0104 ,   997.8686 ,  2026.3091 ,  -905.83954,  -349.66815]],
      dtype=float32)
```
keras v2.3.1
```
Epoch 1/1

10/10 [==============================] - 1s 104ms/step - loss: 97095230641965394441535488.0000
[[nan nan nan nan nan nan nan nan nan nan]]
```

**Comment by sampathweb** [comment]
@cheyennee - Can you open this issue in `tf_keras` since we use this Repo to primarily keep track of `Keras 3` issues.  Also, can you create a minimum fully reproducible Colab.  Due to security reasons, we can't test with weights or numpy download files.  Hope that makes sense.

**Comment by cheyennee** [comment]
Sure, I will open this issue to `tf_keras` and close this issue.
