### ISSUE TITLE
dilation_rate lacks of checking in theano backend

### ISSUE THREAD

**Issue by cheyennee** [keras-team/keras#18916]
SeparableConv1D crashes in tensorflow backend when dilation_rate is 0, but works in theano backend.

repo code:
```
import keras
from keras.engine import Model, Input
x = Input(batch_shape=(28, 28, 1))
layer = keras.layers.SeparableConv1D(filters=5, kernel_size=[2], dilation_rate=[0])
y = layer(x)
model = Model(x, y)
```

**Comment by SuryanarayanaY** [comment]
Hi @cheyennee ,

The `dilation_rate` must be int or list/tuple of 1 integers as per documentation and value must be >0.

https://github.com/keras-team/keras/blob/3b6b929bda64cd48ddb4c96e2a9648d42bdc2acf/keras/layers/convolutional/separable_conv1d.py#L40-L42


The tested code seems not relevant to Keras3.0 version. I have changed the imports suitable to keras3 and it is raising intended exception in Keras3. Please refer attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/47420fe3476007d2fcb9ba17e7d7e2ee/18916.ipynb).
