### ISSUE TITLE
got ValueError when loading model that have LSTM Layer.

### ISSUE THREAD

**Issue by ramakc153** [keras-team/keras#18913]
i found an issue when i try to load my model that has LSTM Layers. Layers used in my model are

```py
def create_model():
    model = keras.Sequential([
        Input((X_train.shape[1], 1)),
        Conv1D(16, 1, activation = 'relu'),
        Conv1D(32, 1,  activation = 'relu'),
        Conv1D(64, 1,  activation = 'relu'),
        Conv1D(128, 1,  activation = 'relu'),
        Conv1D(256, 1,  activation = 'relu'),
        Conv1D(512, 1,  activation = 'relu'),
        Bidirectional(LSTM(64, return_sequences = True, activation = 'tanh')),
        Bidirectional(LSTM(128, return_sequences = True, activation = 'tanh')),
        Bidirectional(LSTM(256, return_sequences = True, activation = 'tanh')),
        # Dense(512, activation = 'relu'),
        # Dense(64, activation = 'relu'),
        # Dense(32, activation = 'relu'),
        Dropout(0.2),


        Dense(7, activation = 'softmax')
    ])
    model.compile(loss = 'sparse_categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy',])
    return model
```
and i save my model using ```model.save("model_name.keras")```
and when i try to load my model, i got this error
```ValueError: Layer 'lstm_cell' expected 3 variables, but received 0 variables during loading. Expected: ['kernel', 'recurrent_kernel', 'bias']```
I have try to do this on tensorflow and everything works fine
i'm using keras 3.0.1 using tensorflow backend and run it on google colab.

**Comment by sachinprasadhs** [comment]
Are you trying to save and load the model in same Version? 
Could you please let us know what TensorFlow version you are using?

If you could provide some sample reproducible code, it would help us to investigate on the issue further. Thanks!

**Comment by ramakc153** [comment]
update : i'm using keras 3.0.2 and it's still produce the same error. tensorflow version that i used is 2.15

sorry for the late reply. here is the code 
```py
def create_model():
    model = keras.Sequential([
        Input((X_train.shape[1], 1)),
        Conv1D(16, 1, activation = 'relu'),
        Conv1D(32, 1,  activation = 'relu'),
        Conv1D(64, 1,  activation = 'relu'),
        Conv1D(128, 1,  activation = 'relu'),
        Conv1D(256, 1,  activation = 'relu'),
        Conv1D(512, 1,  activation = 'relu'),
        Bidirectional(LSTM(64, return_sequences = True, activation = 'tanh')),
        Bidirectional(LSTM(128, return_sequences = True, activation = 'tanh')),
        Bidirectional(LSTM(256, return_sequences = True, activation = 'tanh')),
        Dropout(0.2),


        Dense(7, activation = 'softmax')
    ])
    model.compile(loss = 'sparse_categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy',])
    return model
    model = create_model()
    history = model.fit(X_train, y_train, epochs = 10)
    model.save("new_model.keras")
    # the first one, im using this way
    new_model = keras.models.load_model("new_model.keras")
    # and after that i'm using the way that documented on keras 3
    new_model = keras.saving.load_model("new_model.keras")

```
and both of them still producing the same error.

**Comment by Regenhardt** [comment]
I have the same problem using tensorflow 2.15.0 for a simple model. 
```
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
=================================================================
 lstm (LSTM)                 (None, 1)                 272       
                                                                 
 dense (Dense)               (None, 1)                 2         
                                                                 
=================================================================
Total params: 274 (1.07 KB)
Trainable params: 274 (1.07 KB)
Non-trainable params: 0 (0.00 Byte)
```

I train it on a linux server in a docker container running Python 3.11.0rc1 (`FROM  tensorflow/tensorflow:2.15.0-gpu`).  
Saved as `model.keras`, I get the same error when trying to load it on my windows machine running Python 3.11.7 (expected 3 variables received 0).

Saving/loading as .h5 works.

**Comment by ramakc153** [comment]
> I have the same problem using tensorflow/keras 2.15.0 for a simple model.
> 
> ```
> Model: "sequential"
> _________________________________________________________________
>  Layer (type)                Output Shape              Param #   
> =================================================================
>  lstm (LSTM)                 (None, 1)                 272       
>                                                                  
>  dense (Dense)               (None, 1)                 2         
>                                                                  
> =================================================================
> Total params: 274 (1.07 KB)
> Trainable params: 274 (1.07 KB)
> Non-trainable params: 0 (0.00 Byte)
> ```
> 
> I train it on a linux server in a docker container running Python 3.11.0rc1 (`FROM tensorflow/tensorflow:2.15.0-gpu`). Saved as `model.keras`, I get the same error when trying to load it on my windows machine running Python 3.11.7 (expected 3 variables received 0).
> 
> Saving/loading as .h5 works.

maybe you can try to use python 3.10 ?

**Comment by Regenhardt** [comment]
How do I put that into the container? The tensorflow image comes with 3.11.0rc. 

Secretly I hope there'll be a new container that lets me just port the whole thing to keras3, but this is my bachelor's so I can't really wait for that, it's why I'm working with h5 for now because I see no pressing reason to figure out .keras right now.

**Comment by adampirog** [comment]
I have the same issue and it's connected Bidirectional layers. Loading a model with a Bidirectional results in error like above

**Comment by akeeman** [comment]
Did some digging, and it turns out that the problems are introduced in 0454a403867cd4ba23bf2604f1feaa36c357db17.
Reverting the commit made my error vanish.

**Comment by akeeman** [comment]
Keras 2.15 fails to load a model exported in keras_v3 format using Keras 2.14 with the same error as the one Keras 2.14 produces when trying to load one exported using Keras 2.13. This time commit https://github.com/keras-team/keras/commit/bd465a78e6e14b129e14eafb27e7fb397cdfbb54 broke the bc.

**Comment by TristanPagden** [comment]
I had the same error and I fixed it by saving the model in the .h5 format instead of the .keras format

**Comment by rohanbobby01** [comment]
What is the fix

**Comment by niko247** [comment]
I have same issue with: tensorflow==2.16.1 keras==3.0.5
I noticed the issue is with Bidirectional layer, without it it works:

```
from keras.models import Sequential
from keras.layers import LSTM, Dense, Bidirectional, Input
from keras.models import load_model, save_model
import numpy as np

data = np.random.random((100, 10, 1))
target = np.random.random((100, 1))

model = Sequential()
model.add(Input(shape=(10, 1)))
model.add(Bidirectional(LSTM(20)))
model.add(Dense(1))

model.compile(loss='mae', optimizer='adam')
model.fit(data, target, epochs=10, batch_size=1, verbose=1)

save_model(model, 'model.keras')
loaded_model = load_model('model.keras')
```

```
ValueError: A total of 1 objects could not be loaded. Example error message for object <LSTMCell name=lstm_cell, built=True>:

Layer 'lstm_cell' expected 3 variables, but received 0 variables during loading. Expected: ['kernel', 'recurrent_kernel', 'bias']

List of objects that could not be loaded:
[<LSTMCell name=lstm_cell, built=True>]
```

**Comment by Pierrott64** [comment]
Same issue for me with tensorflow==2.16.1 keras==3.0.5

`ValueError: A total of 1 objects could not be loaded. Example error message for object <LSTMCell name=lstm_cell, built=True>:

Layer 'lstm_cell' expected 3 variables, but received 0 variables during loading. Expected: ['kernel', 'recurrent_kernel', 'bias']

List of objects that could not be loaded:
[<LSTMCell name=lstm_cell, built=True>]`

**Comment by Pierrott64** [comment]
Same issue for me with tensorflow==2.16.1 keras==3.0.5

`ValueError: A total of 1 objects could not be loaded. Example error message for object :

Layer 'lstm_cell' expected 3 variables, but received 0 variables during loading. Expected: ['kernel', 'recurrent_kernel', 'bias']

List of objects that could not be loaded:
[<LSTMCell name=lstm_cell, built=True>]`

**Comment by Pierrott64** [comment]
Same issue for me with tensorflow==2.16.1 keras==3.0.5 ValueError: A total of 1 objects could not be loaded. Example error message for object <LSTMCell name=lstm_cell, built=True>:

Layer 'lstm_cell' expected 3 variables, but received 0 variables during loading. Expected: ['kernel', 'recurrent_kernel', 'bias']

List of objects that could not be loaded:
[<LSTMCell name=lstm_cell, built=True>]

**Comment by justinejones** [comment]
Any movement on this item?  I just ran into the same issue trying to reload a saved .keras model.  I have trained the models a few times and am trying to save them to disc and reload.

**Comment by nilesh-sengupta** [comment]
Same issue with tensorflow==2.16.1 keras==3.0.5
ValueError: A total of 2 objects could not be loaded. Example error message for object <LSTMCell name=lstm_cell, built=True>:

Layer 'lstm_cell' expected 3 variables, but received 0 variables during loading. Expected: ['kernel', 'recurrent_kernel', 'bias']

List of objects that could not be loaded:
[<LSTMCell name=lstm_cell, built=True>, <LSTMCell name=lstm_cell, built=True>]

Is there some fix to save the .keras file as a .h5 with this loading error and not re-training the entire model again ?

**Comment by niko247** [comment]
@EngMohamedSaeed2001 no, there is no fix so far, but it works on version: 1.15.1

**Comment by EngMohamedSaeed2001** [comment]
> @EngMohamedSaeed2001 no, there is no fix so far, but it works on version: 1.15.1

I didn't find keras or tensorflow version 1.15.1

Can you specify the versions of them please?

**Comment by niko247** [comment]
@EngMohamedSaeed2001 sorry for typo tensorflow: 2.15.1

**Comment by EngMohamedSaeed2001** [comment]
> @EngMohamedSaeed2001 sorry for typo tensorflow: 2.15.1

What about keras version?

**Comment by niko247** [comment]
@EngMohamedSaeed2001 keras: 2.15.0 is compatible

**Comment by EngMohamedSaeed2001** [comment]
> @EngMohamedSaeed2001 keras: 2.15.0 is compatible

Thank you

**Comment by jdelpino-dev** [comment]
I have same issue with: tensorflow==2.16.1 keras==3.1.1

I also noticed that the issue is with Bidirectional layer, without it it works:

`python
class OneHotEncodingLayer(layers.Layer):
    def __init__(self, depth, **kwargs):
        super(OneHotEncodingLayer, self).__init__(**kwargs)
        self.depth = depth

    def call(self, inputs):
        return tf.one_hot(tf.cast(inputs, tf.int32), depth=self.depth)

inputs = keras.Input(shape=(None,), dtype="int64")
embedded = OneHotEncodingLayer(depth=max_tokens)(inputs)
x = layers.Bidirectional(layers.LSTM(32))(embedded)
x = layers.Dropout(0.5)(x)
outputs = layers.Dense(1, activation="sigmoid")(x)
model = keras.Model(inputs, outputs)
model.compile(optimizer="rmsprop",
              loss="binary_crossentropy",
              metrics=["accuracy"])

callbacks = [
    keras.callbacks.ModelCheckpoint("one_hot_bidir_lstm.keras",
                                    save_best_only=True)
]
model.fit(int_train_ds, validation_data=int_val_ds, epochs=1, callbacks=callbacks)
`

**Comment by nilesh-sengupta** [comment]
@nkovela1 @sachinprasadhs is there a way to manually change the config file after unzipping the .keras file to resolve this error ?

**Comment by estebangarcia21** [comment]
I have the same issue trying to load a model with a PyTorch backend and a Bidirectional LSTM layer using `keras.models.load_model`.

```
ValueError: A total of 1 objects could not be loaded. Example error message for object <LSTMCell name=lstm_cell, built=True>:

Layer 'lstm_cell' expected 3 variables, but received 0 variables during loading. Expected: ['kernel', 'recurrent_kernel', 'bias']

List of objects that could not be loaded:
[<LSTMCell name=lstm_cell, built=True>]
```

**Comment by andybrandt** [comment]
Also run into this problem, for now going back to 2.15.0 - thank you for pointing this out as a working version.

**Comment by Jnorm911** [comment]
Same issue with bidirectional on python 3.11.8, tensorflow 2.16.1 and keras 3.1.1

**Comment by JelleKuiper** [comment]
I've found a temporary fix. You can export the model via model.export(path) without an extention. Then you can load it back into a TSFMLayer object which you can get outputs from.

**Comment by niko247** [comment]
It's fixed already with:
keras==3.3.3
tensorflow[and-cuda]==2.16.1
python==3.12

**Comment by sachinprasadhs** [comment]
Here [![](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.sandbox.google.com/gist/sachinprasadhs/1304a11da87083b53fe51186470eaf45/18913.ipynb) is the sample example demonstrating the working Gist with the latest version.

**Comment by ramakc153** [comment]
test

**Comment by ramakc153** [comment]
So the solution is either using ```model.export()``` when exporting the model or use lower version on tensorflow

what is the difference between ```using model.export()``` and ```model.save()```?

since in keras docs is still suggest to use ```model.save()``` instead of ```model.export()```. since i'm only find it on keras migration guide

**Comment by ghsanti** [comment]
use `load` and `save` and keras **3.4** or **3.5**, but i'm unsure custom objects are supported. @ramakc153

**Comment by indrex** [comment]
Google for the issue, saw this thread, _downgraded_ to 2.15. I guess that's the only practical solution for now.
