### ISSUE TITLE
MIssing v2.15.0 release tag

### ISSUE THREAD

**Issue by klawik-j** [keras-team/keras#18931]
Apparently there is no tag for v2.15.0 release. It might be confusing.
https://github.com/keras-team/keras/tags 
![image](https://github.com/keras-team/keras/assets/52794536/7629578a-5b25-4c1e-944c-132235a68be3)

**Comment by sachinprasadhs** [comment]
Hi, 
2.15 is part of `tf-keras` and can be found here https://github.com/keras-team/tf-keras/tree/v2.15.0

This is due to the migration process of` Keras 3` from `Keras-Core` to `Keras`. 
For Keras 2.15, you can refer the published wheels here on PyPi https://pypi.org/project/keras/2.15.0/#history.

**Comment by qlzh727** [comment]
Thanks,  I have created keras 2.15.0 release in https://github.com/keras-team/keras/releases/tag/v2.15.0.
