### ISSUE TITLE
Is QAT supported in Keras 3.0 for TFLite Quantisation?

### ISSUE THREAD

**Issue by tarushbansal** [keras-team/keras#18930]
I couldn't find any mention of Quantisation Aware Training in the Keras 3 API documentation. Is it possible to convert the current Keras 3.0 models into quantisation-aware models with quantisation nodes added for TFLite conversion after training? If not, are there any plans to include this support in the future?

**Comment by SuryanarayanaY** [comment]
Hi @tarushbansal ,

Have you seen this `mobilevit` [tutorial](https://github.com/keras-team/keras/blob/master/examples/keras_io/tensorflow/vision/mobilevit.py) that converts keras3 model into TFlite ? Is it what you are looking for ?

**Comment by tarushbansal** [comment]
Hi @SuryanarayanaY,
The `mobilevit` tutorial focuses on post-training quantisation instead. I am looking for a way to train the model in a quantisation aware setting just like previously supported by the TF Optimisation toolkit in this example [here].(https://www.tensorflow.org/model_optimization/guide/quantization/training_example)

**Comment by SuryanarayanaY** [comment]
Hi @tarushbansal ,

> I am looking for a way to train the model in a quantisation aware setting just like previously supported by the TF Optimisation toolkit as in this example [here](https://www.tensorflow.org/model_optimization/guide/quantization/training_example).

The tutorial not working with Keras3. It seems Keras3 not yet supporting this feature. Escalating to Dev team for confirmation.

**Comment by matpalm** [comment]
is QAT still on the roadmap @fchollet ?

have been porting code to keras3 ( as a way to move more to Jax ) & have options for post training quantisation but expect a non trivial benefit from QAT in a number of projects.

can see a path forward by partially porting pieces of https://www.tensorflow.org/model_optimization/api_docs/python/tfmot and/or  https://github.com/google/aqt but will hold back if a QAT api is imminent ? ( additionally; might have some bandwidth to help if there are community contrib options? )
