### ISSUE TITLE
EMA doesn't function properly in jax and torch backend

### ISSUE THREAD

**Issue by james77777778** [keras-team/keras#18949]
Hi Keras team,

I have found that EMA in optimizers doesn't function properly in jax and torch backend.
You can see the result in this colab: https://colab.research.google.com/drive/1g-fB4ELT0lwSb6WL6chqRlIjSVsIhOzQ?usp=sharing

```python
from keras import ops
from keras import optimizers
from keras import Variable

variable = Variable([10.0], trainable=True)
optimizer = optimizers.SGD(use_ema=True)
optimizer.build([variable])

gradients = ops.convert_to_tensor([1.0])
for _ in range(10):
    optimizer.apply_gradients(zip([gradients], [variable]))

print(variable.value)  # all trainable backend got 9.899998
optimizer.finalize_variable_values([variable])
print(variable.value)  # 9.985618 in tensorflow but 0.0 in jax and torch
```

Despite the mentioned bug, the current implementation of EMA in optimizer is not user-friendly.
During fitting, it is often to evaluate the model using average weights. However, it is challenging to `finalize_variable_values` before evaluation and restore the weights afterward while fitting.

Here is my suggestion by moving the implementation of EMA from the optimizer to the trainer:
- store the average weights in `models.Model` if `use_ema=True`
- save the current weights before applying averaging (swapping can be utilized to save space)
- apply averaging before `evaluate`
- restore the previous weights after `evaluate`

Additionally, we can expose functions like `apply_ema_weights` and `restore_previous_weights` in `Trainer` for better UX when user want to implement a custom training loop.

I can try to open a PR if this sounds good.

**Comment by fchollet** [comment]
Thanks for the report. Coincidentally I became aware of this a few hours before you opened this issue, as I started working on gradient accumulation support...

This is all fixed as part of: https://github.com/keras-team/keras/pull/18951

> Despite the mentioned bug, the current implementation of EMA in optimizer is not user-friendly.
During fitting, it is often to evaluate the model using average weights. However, it is challenging to finalize_variable_values before evaluation and restore the weights afterward while fitting.

Two possible solutions are:

- Apply the averaging manually in a callback.
- Just use `ema_overwrite_frequency` to regularly overwrite weights (e.g. every 1000 steps). This guarantees that whenever you evaluate your model, its weights have been synced relatively recently.

**Comment by james77777778** [comment]
> Two possible solutions are:
> 
>     * Apply the averaging manually in a callback.
> 
>     * Just use `ema_overwrite_frequency` to regularly overwrite weights (e.g. every 1000 steps). This guarantees that whenever you evaluate your model, its weights have been synced relatively recently.

Actually, I have implemented a similar workaround to get averaged model before evaluation:

```python
# pseudocode below
class EMACallback(callbacks.Callback):
    def on_test_begin(self, logs=None):
        self.optimizer.finalize_variable_values(self.model.trainable_variables)
```

However, one issue remains:
How can we restore the original training weights after the evaluation to continue the training?

I believe the dynamics will change if we overwrite the model weights during the fitting.
For example, the official training script of EfficientNet only applies averaging weights during evaluation:
https://github.com/tensorflow/tpu/blob/master/models/official/efficientnet/main.py#L517-L518
https://github.com/tensorflow/tpu/blob/master/models/official/efficientnet/main.py#L557-L565

Moreover, it is impossible to apply EMA to `model.variables` including the statistics of BN, since we only apply `model.trainable_variables` in the optimizer.

We can implement all the above logic in a custom callback (which I have done before), but the training speed slows down significantly. (The reason should be the calculations are outside of the compiled function)

The minimal solution based on the current implementation might be:
- Replace `finalize_variable_values` with the apis like `apply_ema_weights` and `restore_model_weights` to provide more fine-grained control (or combine them as `swap_ema_weights`!?)
- Add `EMACallback` to invoke `apply_ema_weights` in `on_[test|predict]_begin` and `restore_model_weights` in `on_[test|predict]_end`

**Comment by fchollet** [comment]
> Replace finalize_variable_values with the apis like apply_ema_weights and restore_model_weights to provide more fine-grained control (or combine them as swap_ema_weights!?)

What would the APIs and the workflow look like?

> I believe the dynamics will change if we overwrite the weights during the fitting.

Yes, but the impact is not material, typically.

> Moreover, it is impossible to apply EMA to model.variables including the statistics of BN, since we only apply model.trainable_variables in the optimizer.

It should not matter because the way these weights are obtained in BN means that they wouldn't be improved by reassigning them to an EMA. They're already obtained via EMA of the per-batch statistics. No need to double the EMA. In fact it would make the model suck, most likely, because the BN stats would take took long to update, since they would update the rate of ema_momentum * bn_momentum = 1e-4. So it should be strictly better to exclude them from the EMA.

Please note that I've update the EMA variable initialization mechanism so that the EMA weights are initialized with the original variable value rather than the value after the first gradient update. This simplifies the code and it means we don't need to track an additional `Variable` in the base optimizer to monitor whether the weights have been initialized. https://github.com/keras-team/keras/commit/335989b42ed14150821861b2996afc66d2af583e

**Comment by james77777778** [comment]
> What would the APIs and the workflow look like?
> 

I have come up with the following callback implementation; no additional API is needed:

```python
from keras import callbacks
from keras import ops


class SwapEMAWeights(callbacks.Callback):
    def _swap_variables(self, variable, average_variable):
        temporary_variable = ops.convert_to_numpy(variable)
        variable.assign(average_variable)
        average_variable.assign(temporary_variable)

    def on_test_begin(self, logs=None):
        for var, average_var in zip(
            self.model.trainable_variables,
            self.model.optimizer._model_variables_moving_average,
        ):
            self._swap_variables(var, average_var)

    def on_test_end(self, logs=None):
        for var, average_var in zip(
            self.model.trainable_variables,
            self.model.optimizer._model_variables_moving_average,
        ):
            self._swap_variables(var, average_var)

    def on_predict_begin(self, logs=None):
        for var, average_var in zip(
            self.model.trainable_variables,
            self.model.optimizer._model_variables_moving_average,
        ):
            self._swap_variables(var, average_var)

    def on_predict_end(self, logs=None):
        for var, average_var in zip(
            self.model.trainable_variables,
            self.model.optimizer._model_variables_moving_average,
        ):
            self._swap_variables(var, average_var)

```

> Yes, but the impact is not material, typically.
> 
> It should not matter because the way these weights are obtained in BN means that they wouldn't be improved by reassigning them to an EMA. They're already obtained via EMA of the per-batch statistics. No need to double the EMA. In fact it would make the model suck, most likely, because the BN stats would take took long to update, since they would update the rate of ema_momentum * bn_momentum = 1e-4. So it should be strictly better to exclude them from the EMA.
> 
Thanks for the clarification. I agree that we shouldn't double the EMA in BN.
However, aligning the implementation of certain models can sometimes be challenging.
- timm (torch): https://github.com/huggingface/pytorch-image-models/blob/main/timm/utils/model_ema.py#L115-L120
- yolov8 (torch): https://github.com/ultralytics/ultralytics/blob/main/ultralytics/utils/torch_utils.py#L406-L417
- efficientnet (tensorflow): https://github.com/tensorflow/tpu/blob/master/models/official/efficientnet/utils.py#L339-L346

> Please note that I've update the EMA variable initialization mechanism so that the EMA weights are initialized with the original variable value rather than the value after the first gradient update. This simplifies the code and it means we don't need to track an additional `Variable` in the base optimizer to monitor whether the weights have been initialized. [335989b](https://github.com/keras-team/keras/commit/335989b42ed14150821861b2996afc66d2af583e)

Thanks for the update; it is cleaner than before. However, I ran into the following issue when `use_ema=True` and `compile(jit_compile=True)` with CUDA:
```bash
iterator = <tensorflow.python.data.ops.iterator_ops.OwnedIterator object at 0x7f8b680cb3d0>

    @tf.autograph.experimental.do_not_convert
    def one_step_on_iterator(iterator):
        """Runs a single training step given a Dataset iterator."""
        data = next(iterator)
>       outputs = self.distribute_strategy.run(
            one_step_on_data, args=(data,)
        )
E       tensorflow.python.framework.errors_impl.UnimplementedError: We failed to lift variable creations out of this tf.function, so this tf.function cannot be run on XLA. A possible workaround is to move variable creation outside of the XLA compiled function.
```

The commit I pushed earlier ran successfully instead: [095de43](https://github.com/keras-team/keras/commit/095de4388389b68a28a67e9b3cd68d1c1be2db81)

**Comment by fchollet** [comment]
> Thanks for the update; it is cleaner than before. However, I ran into the following issue when use_ema=True and compile(jit_compile=True) with CUDA:

Thanks, I looked into it. Seems to be a fairly complex TF issue. Rather than debugging it I opted for a different initialization strategy, setting the momentum to 0 when `iterations == 0`.

**Comment by james77777778** [comment]
> Thanks, I looked into it. Seems to be a fairly complex TF issue. Rather than debugging it I opted for a different initialization strategy, setting the momentum to 0 when `iterations == 0`.

I can confirm that the issue has been resolved! Thanks for the swift updates.

**Comment by james77777778** [comment]
This issue has been resolved.
