### ISSUE TITLE
remove reliance on this (or alternatively, turn it on by default).

### ISSUE THREAD

**Issue by ghost** [keras-team/keras#18946]
https://github.com/keras-team/keras/blob/e70f28ff3f3b2060b83c23a1aabc85b4ccece991/keras/ops/nn_test.py#L27

**Comment by SuryanarayanaY** [comment]
Hi @pakapong777 ,

It's a TODO to the Keras developer team. Not a concern to users. Could you please explain your problem if any ?

Thanks!
