### ISSUE TITLE
 Cloning a TextVectorization Layer with Split Function Doesn't Work

### ISSUE THREAD

**Issue by rlcauvin** [keras-team/keras#18950]
I believe I've found a bug in `tf.keras.layers.TextVectorization.from_config()`. I am using TensorFlow version 2.14, but I don't see any code changes in later versions.

The following code is intended to to set up a vectorizer for pipe-delimited text and then clone the vectorizer.

```
import tensorflow as tf

@tf.keras.saving.register_keras_serializable(package = "__main__")
def pipe_split_fn(
  input: Text) -> Text:

  return tf.strings.split(input, sep = "|")

text_dataset = tf.data.Dataset.from_tensor_slices([
                                                   "this|is|some|pipe-delimited|text", 
                                                   "some|more|pipe-delimited|text", 
                                                   "yet|more|pipe-delimited|text"])
vectorizer = tf.keras.layers.TextVectorization(
    max_tokens = 10,
    standardize = None,
    split = pipe_split_fn)
vectorizer.adapt(text_dataset)

tf.keras.models.clone_model(vectorizer)
```
Output:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[230], line 11
      5 vectorizer = tf.keras.layers.TextVectorization(
      6     max_tokens = 10,
      7     standardize = None,
      8     split = pipe_split_fn)
      9 vectorizer.adapt(text_dataset)
---> 11 tf.keras.models.clone_model(vectorizer)

File ~/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages/keras/src/models/cloning.py:555, in clone_model(model, input_tensors, clone_function)
    546     raise ValueError(
    547         "Arguments clone_function and input_tensors "
    548         "are only supported for Sequential models "
   (...)
    552         f"input_tensors={input_tensors}"
    553     )
    554 # Note that a custom object scope may be required in this case.
--> 555 return model.__class__.from_config(model.get_config())

File ~/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages/keras/src/layers/preprocessing/text_vectorization.py:538, in TextVectorization.from_config(cls, config)
    534     config["standardize"] = deserialize_keras_object(
    535         config["standardize"]
    536     )
    537 if config["split"] not in (WHITESPACE, CHARACTER):
--> 538     config["split"] = deserialize_keras_object(config["split"])
    539 return cls(**config)

File ~/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages/keras/src/saving/serialization_lib.py:619, in deserialize_keras_object(config, custom_objects, safe_mode, **kwargs)
    617     return config
    618 if not isinstance(config, dict):
--> 619     raise TypeError(f"Could not parse config: {config}")
    621 if "class_name" not in config or "config" not in config:
    622     return {
    623         key: deserialize_keras_object(
    624             value, custom_objects=custom_objects, safe_mode=safe_mode
    625         )
    626         for key, value in config.items()
    627     }

TypeError: Could not parse config: <function pipe_split_fn at 0x7f0a624d56c0>
```

As you can see, it is failing to deserialize the split function of the instance of `tf.keras.layers.TextVectorization`. If I instead construct the instance of `tf.keras.layers.TextVectorization` with the default "whitespace" for the split parameter, cloning works fine.

Inspecting the code for `TextVectorization` (https://github.com/keras-team/keras/blob/master/keras/layers/preprocessing/text_vectorization.py#L491) and `deserialize_keras_object` (https://github.com/keras-team/keras/blob/master/keras/saving/serialization_lib.py#L392), I see that there is no way the proper logic for deserializing the split function will run. The deserialization code looks for `if module_objects is not None:`, but `TextVectorization.from_config()` doesn't pass a `module_objects` parameter to `deserialize_keras_object`, so that code block doesn't execute.

As a workaround, I extended the `tf.keras.layers.TextVectorization` class with:

```
class PatchedTextVectorization(tf.keras.layers.TextVectorization):

  @classmethod
  def from_config(cls, config):
    if not isinstance(config["standardize"], str):
      config["standardize"] = tf.keras.saving.deserialize_keras_object(config["standardize"])
    if not isinstance(config["split"], str):
      config["split"] = tf.keras.saving.deserialize_keras_object(config["split"], module_objects = [])

    return cls(**config)
```

Cloning an instance of `PatchedTextVectorization` constructed with the split function works fine. You can see I shoehorned `module_objects = []` into its invocation of `tf.keras.saving.deserialize_keras_object`.

**Comment by SuryanarayanaY** [comment]
Hi @rlcauvin ,

I have tested the code with keras3 and its executing fine. Could you please verify the attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/b138bf67f043cdd0e0830ebe12f20670/18950_keras3.ipynb).

**Comment by rlcauvin** [comment]
Thank you. I have confirmed in this [gist]([url](https://colab.research.google.com/drive/1tIS0Ynjck80kKGWv1tTQ6oCc8Nj1xnNa?usp=sharing)) that it does not work in tf.keras-2.15.0.

Is there any work being done on that branch, or is Keras 3 the only active branch now?

**Comment by SuryanarayanaY** [comment]
Hi @rlcauvin ,

It is an issue with `tf-keras` package. Could you please report the issue at [tf-keras](https://github.com/keras-team/tf-keras/issues) repo as Keras2 (tf.keras) issues will be handled there separately.

**Comment by SuryanarayanaY** [comment]
Hi @rlcauvin ,

Starting with TensorFlow 2.16, doing pip install tensorflow will install Keras 3. When you have TensorFlow >= 2.16 and Keras 3, then by default from tensorflow import keras ([tf.keras](https://www.tensorflow.org/api_docs/python/tf/keras)) will be Keras 3. Refer the documentation [source](https://keras.io/getting_started/#tensorflow--keras-2-backwards-compatibility) also.

This means this will not be an issue with TF2.16v onwards.I have tested with current tf-nightly(2.16.0-dev20240130) and it works fine and attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/c130ca8d9985dec528263439044ce07e/18950_tf-nightly.ipynb) for same.

From TF2.16 onwards `tf_keras` package has no role as Keras3 is default for Tf2.16v and replacement for `tf.keras` which means this issue not related to Keras3. As you already filed an issue in `tf_keras` can you close it here and track there?

Thanks!
