### ISSUE TITLE
data_batch_1 not found in cifar10 dataset

### ISSUE THREAD

**Issue by naobi123** [keras-team/keras#18953]
[Errno 2] No such file or directory: 'C:\\Users\\rajku\\.keras\\datasets\\cifar-10-batches-py\\data_batch_1'

How do i solve this problem?

**Comment by sachinprasadhs** [comment]
Hi, 

Could you please provide more context on the issue with some sample reproducible code.

For loading `cifar10` dataset follow below code.

`(x_train, y_train), (x_test, y_test) = keras.datasets.cifar10.load_data()`
