### ISSUE TITLE
CI improvements

### ISSUE THREAD

**Issue by aaarrti** [keras-team/keras#18989]
This is a continuation of a discussion about CI here https://github.com/keras-team/keras/pull/18986#issuecomment-1868443531. 

## Problems

- sometimes failing test can not be reproduced
- because of the number of tests in the CI, it is very hard to see through in case few of them fail.
- Keras supports multiple python versions, but CI checks use only py39

## Suggested changes
- Run CI tests on all supported python versions (py39, py310, py311)
- add a test report to the CI, e.g. https://github.com/vsoch/pytest-github-report. I've experimented a bit with it in my fork https://github.com/aaarrti/keras/actions/runs/7309335728. I found it very helpful for debugging not reproducible (locally) test failures.

@fchollet what do you think?

**Comment by sampathweb** [comment]
We already run CI for all backends so adding Python versions to the mix will increase the current 3-4 jobs (on CPU) to 12.  We generally prefer to run CI on the minimum python version so we don't use any features that doesn't exist in the lower end of Python version supported.

**Comment by sampathweb** [comment]
On the `pytest-github-report` outputs, it looks good and will be a value add, but that Repo is over 2 years old.  Feel free to experiment with it and create a PR if that's a useful way to debug test failures.

**Comment by aaarrti** [comment]
> We already run CI for all backends so adding Python versions to the mix will increase the current 3-4 jobs (on CPU) to 12. We generally prefer to run CI on the minimum python version so we don't use any features that doesn't exist in the lower end of Python version supported.

I agree, 12 jobs would be to much.

**Comment by aaarrti** [comment]
> On the `pytest-github-report` outputs, it looks good and will be a value add, but that Repo is over 2 years old. Feel free to experiment with it and create a PR if that's a useful way to debug test failures.

The only reason I suggested this plugin is the fact, that I've encountered not reproducible (locally) test failures during CI runs. I don't think it is reasonable to design CI around one exceptional case.

**Comment by aaarrti** [comment]
I will close the ticket, since there is no real need for those changes.
