### ISSUE TITLE
keras version

### ISSUE THREAD

**Issue by URWASHANZA** [keras-team/keras#18987]
File ~\anaconda3\envs\Python310\lib\site-packages\keras_vggface\models.py:16
     12 from keras.layers import Flatten, Dense, Input, GlobalAveragePooling2D, \
     13     GlobalMaxPooling2D, Activation, Conv2D, MaxPooling2D, BatchNormalization, \
     14     AveragePooling2D, Reshape, Permute, multiply
     15 from keras_applications.imagenet_utils import _obtain_input_shape
---> 16 from keras.utils import layer_utils
     17 from keras.utils.data_utils import get_file
     18 from keras import backend as K

ImportError: cannot import name 'layer_utils' from 'keras.utils

**Comment by sachinprasadhs** [comment]
Hi,

Thanks for reporting the issue.

There is no layer_utils in the Keras 3, please migrate your code to be compatible with the Keras 3 by following the guide here  https://keras.io/guides/migrating_to_keras_3/
