### ISSUE TITLE
model.get_weights() method seems returning pointer instead the values 

### ISSUE THREAD

**Issue by oevcim** [keras-team/keras#19000]
Hi
I am getting weights and storing them into a list(multiple times). But during training process whole weights in the list changing like all weights are one instance.
How can i fix that.

**Comment by sampathweb** [comment]
You could use `np.copy` to copy the weights.  But in general, this behavior shouldn't happen.  For example - 

```
a = model.get_weights()
print(a)
model.fit(x, y, epochs=2)
print(a) # Should not change
model.get_weights() # Will give new weights
```
If this is still an issue, please re-open with an colab example.
