### ISSUE TITLE
model trainable params have changed after saving and reloading

### ISSUE THREAD

**Issue by innat** [keras-team/keras#19019]
Shortly

- [env Keras V2] I have keras model in `.h5` format and SavedModel format.
- [env Keras V2] I saved keras model in `.weights.h5` format.
- [env Keras V3] I loaded `.weights.h5` fromat (**model_a**) and inference matched properly with previous  `.h5`.
- [env Keras V3] I saved `.weights.h5` loaded Keras V3 model in `.keras` format (**model_b**). It saved and later reloaded properly.
- **Issue 1** is, the model's parameter of **model_a** and **model_b** are different despite being the same arch, initialized with same input. How best way to inspect these weights? Further, if I saved **model_a** to SavedModel format using `tf.saved_model.save` and reloaded with `keras.layers.TFSMLayer`, it remains safe unlike `.keras` format. So, shortly using Keras V3, the  `.weights.h5` and SavedModel file works fine but not in `.keras` format.
- **Issue 2** is, with `torch` backend, the inference with `.weights.h5` format works as expected but changing to `tensorflow` and `jax` give different logits. I can ensure the low-level ops are properly set. So, I'm wondering, is there any known fact we need to care while using keras API with different backend? In other word, I used  `keras.ops`, `keras.layers` which suppose to behave same for different backend, or no!

**Comment by sachinprasadhs** [comment]
@nkovela1 , Could you please take a look into this issue. Thanks!

**Comment by innat** [comment]
It looks like in `.keras` format, user has to implement the `get_config` method. For example, in the following code, where the init variables are directly used in the init layers, and not passing them to `get_config` makes `.keras` unable to recognize them.

```python
class SubModel(keras.Model):
    def __init__(self, num_layer_norm, **kwargs):
        super().__init__(**kwargs)
        self.dense_layers = [
            layers.Dense(64, activation='relu') for i in range(num_layer_norm)
        ]
        self.layer_norms = [
            layers.LayerNormalization() for _ in range(num_layer_norm)
        ]
        self.output_layer = layers.Dense(32, activation='relu')

    def call(self, inputs):
        x = inputs
        for i, (dense, layer_norm) in enumerate(
            zip(self.dense_layers, self.layer_norms)
        ):
            x = dense(x)
            x = layer_norm(x)
        output = self.output_layer(x)
        return output


@keras.saving.register_keras_serializable('combined.model')
class CombinedModel(keras.Model):
    def __init__(
        self, num_submodels, num_layer_norm, num_classes=1000, **kwargs
    ):
        super().__init__(**kwargs)
        self.submodels = [
            SubModel(num_layer_norm) for _ in range(num_submodels)
        ]
        self.combine_layer = (
            layers.Dense(num_classes, name="head", dtype="float32")
            if num_classes > 0
            else layers.Identity()
        )

    def call(self, inputs):
        submodel_outputs = [submodel(inputs) for submodel in self.submodels]
        combined_output = ops.concatenate(submodel_outputs, axis=-1)
        final_output = self.combine_layer(combined_output)
        return final_output
```
```python
num_submodels = 5
num_layer_norm = 10
model = CombinedModel(num_submodels, num_layer_norm, num_classes=10)
model(ops.ones(shape=(2, 100)))
model.summary()
Total params: 237,930
```

In `.keras` format it saved properly (no erro). 

```python
model.save('custom_model.keras')
```

But loading will report an error

```python
loaded_model = keras.saving.load_model("custom_model.keras")
TypeError: <class '__main__.CombinedModel'> could not be deserialized properly. Please ensure that components that are Python object instances (layers, models, etc.) returned by `get_config()` are explicitly deserialized in the model's `from_config()` method.
```

But TensorFlow SavedModel saved and reloaded properly 

```python
# saved
tf.saved_model.save(model, 'saved_model')

# reload
saved_model = keras.Sequential(
    [
        keras.layers.TFSMLayer(
            "saved_model", call_endpoint="serving_default"
        )
    ]
)
saved_model(ops.ones(shape=(2, 100)))
saved_model.summary() 
Total params: 237,930
```

This looks a like limitation of `.keras` format, no!
