### ISSUE TITLE
Exclude bad images from keras `image_dataset_from_directory`

### ISSUE THREAD

**Issue by tqdo** [keras-team/keras#19026]
I wonder whether there is a way to excluse bad/corrupt images when reading images from a directory using image_dataset_from_directory. In the [tutorial](https://keras.io/examples/vision/image_classification_from_scratch/#filter-out-corrupted-images), it suggests deleting those corrupt images but that's not what I want. I want to keep those images in the folder, but ignore them when Keras load them. Appreciate any help.

**Comment by SuryanarayanaY** [comment]
Hi @tqdo ,

I suggest you to move the corrupted images to new directory incase you don't want to delete them.

Since the API `image_dataset_from_directory` expects all then images in the directory are preprocessed.
