### ISSUE TITLE
Keyword learning_rate vs lr not returning same loss function in keras.optimizers.Adam

### ISSUE THREAD

**Issue by richtnyc** [keras-team/keras#19025]
This code snippet:

model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(Dense(1))
optimizer = keras.optimizers.Adam(lr=1e-5)
model.compile(optimizer=optimizer, loss='mse')

# fit model
model.fit(X, y, epochs=50, validation_split=0.2, verbose=1)

does not show the same loss values as:

model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(Dense(1))
optimizer = keras.optimizers.Adam(learning_rate=1e-5)
model.compile(optimizer=optimizer, loss='mse')

# fit model
model.fit(X, y, epochs=50, validation_split=0.2, verbose=1)

learning_rate consistently gives values around .47 while lr rsults in .03. 

The .03 seems more correct even though it is the deprecated syntax.

tensor and keras were installed this week and I am using VS2022 on Windows 10

**Comment by richtnyc** [comment]
I see now in another thread from December 2022 that lr is supposed to now create an exception but apparently is still just a warning but the warning does not say lr is ignored as opposed to being backward compatible

**Comment by sachinprasadhs** [comment]
Hi, 

If you try the code using Keras 3, you will see the exception when using `lr` as an argument.

Install Keras 3 using `!pip install -U keras`

Below is the sample code which throws an exception when `lr` is used.

```python
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

model = Sequential()
model.add(Dense(units=64, input_dim=10, activation='relu'))
model.add(Dense(units=1, activation='sigmoid'))
learning_rate = 0.001
model.compile(loss='binary_crossentropy', optimizer=Adam(lr=learning_rate), metrics=['accuracy'])

print(model.summary())
```

`ValueError: Argument(s) not recognized: {'lr': 0.001}`
