### ISSUE TITLE
The fit with steps_per_epoch crashes with a DataLoader.

### ISSUE THREAD

**Issue by foxik** [keras-team/keras#19038]
Hi,

the latest `keras-nightly-3.0.3.dev2024010803` crashes when the `fit` method gets `steps_per_epoch` and a `DataLoader`. An example to reproduce:
```python
#!/usr/bin/env python3
import os
os.environ.setdefault("KERAS_BACKEND", "torch")

import keras
import numpy as np
import torch

d = np.random.uniform(size=[70*10*3, 1])
ds = torch.utils.data.StackDataset(d, d)
dl = torch.utils.data.DataLoader(ds, batch_size=10, shuffle=True)

m = keras.Sequential([keras.layers.Dense(1)])
m.compile(keras.optimizers.Adam(), loss=keras.losses.MeanSquaredError())
m.fit(dl, steps_per_epoch=70, epochs=10)
```

The resulting error is
```
Traceback (most recent call last):
  File "/ha/home/t/t/keras_torch_test.py", line 15, in <module>
    m.fit(dl, steps_per_epoch=70, epochs=10)
  File "/home/t/venvs/keras-torch/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 123, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/t/venvs/keras-torch/lib/python3.10/site-packages/keras/src/trainers/epoch_iterator.py", line 98, in enumerate_epoch
    data = next(self._current_iterator)
TypeError: 'DataLoader' object is not an iterator
```

The problem is that the `_get_iterator` of an `EpochIterator` is overloaded by `TorchEpochIterator` at https://github.com/keras-team/keras/blob/85c9a58892d4626d0a37a6fdc13113a6dbb301d8/keras/backend/torch/trainer.py#L498-L507 however, the `self.data_adapter.get_torch_dataloader()` is not really an iterator, just a dataloader.

Maybe the line 503 in the above file should look like `return iter(self.data_adapter.get_torch_dataloader())`?

And probably there should be a test to verify that `DataLoader` works with `steps_per_epoch`, which I assume is currently not the case (otherwise this would have been caught).

Cheers!

**Comment by SuryanarayanaY** [comment]
This seems to be a regression issue. The code executes fine with kears 3.0.2 but fails with keras-nightly.Attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/e64d1280a588cae6bb6ae348125cca6e/19038.ipynb) for reference.

@foxik ,If you want to contribute please feel free to do so. Thanks!
