### ISSUE TITLE
Using Keras 3.0 JAX with Gymnasium / RL

### ISSUE THREAD

**Issue by Sharpz7** [keras-team/keras#19032]
https://github.com/Farama-Foundation/Gymnasium

Hey folks, I know there are some old RL examples in the docs. https://keras.io/examples/rl/

With Keras now supporting JAX, this is a major opportunity to lower the barrier to entry to using JAX for RL Researchers - who could see 10-20x speedups depending on how much of their environment is put into JAX.

I was wondering what the maintainers think compatibility looks like right now. Over the coming weeks, I will try myself but I imagine it won't work perfectly.

My goal with this ticket is to scope out what does and doesn't work, and see how much effort it would take to get it working. Hopefully it's minimal changes / nothing at all :)) My hunch however is that a bunch of wrapper code will need to be written and a separate (KerasRL) repository needing to be created.

I imagine using https://github.com/luchris429/purejaxrl as a baseline to see if the speed improvements carry over.

**Comment by SuryanarayanaY** [comment]
Hi @Sharpz7 ,

I hope you want to convert the mentioned RL tutorials to support with Jax backend. For this first step you need to do is to export the backend to Jax. Please refer the attached [documentation](https://screenshot.googleplex.com/8nv2pCKLza5sJKK) for same.

Then you need to replace TF APIs with the corresponding Jax APIs. You may refer this custom training loop with [Jax](https://keras.io/guides/writing_a_custom_training_loop_in_jax/) for a demo.

Thanks!

**Comment by Sharpz7** [comment]
Okay - I will give this a go over the coming weeks. Thanks!
