### ISSUE TITLE
Steps_per_epoch cannot be easily used with DataLoader/ndarray, because there is no .repeat

### ISSUE THREAD

**Issue by foxik** [keras-team/keras#19037]
Hi,

if a `torch.utils.data.DataLoader` or a `np.ndarray` is used in `fit` together with `steps_per_epoch`, then when it runs out of data, a warning is generated and the epoch interrupted:

https://github.com/keras-team/keras/blob/85c9a58892d4626d0a37a6fdc13113a6dbb301d8/keras/trainers/epoch_iterator.py#L103-L113

However, while with `tf.data.Dataset` it was trivial to just add `.repeat()` to the dataset, this is not the case with a `DataLoader` or an `ndarray`. It would be much more useful if the `EpochIterator` just created a new iterator for the `DataLoader`/`ndarray`. Of course, there could be an option to do it only when requested; but I believe the reasonable default is to create the new iterator unconditionally, because the user opted in by specifying non-default `steps_per_epoch`.

The fix would not be complicated, in the lines linked above, instead of the warning and the two lines, one would just use a single line `self._current_iterator = self._get_iterator(return_type)` and the `self._insufficient_data` could be removed.

**Comment by grasskin** [comment]
Hi @foxik, we agree that it's not as straightforward to repeat in torch nor in numpy (you would have to manually deal with these). That being said we don't want to assume users should want the same dataset repeated. For the time being we will keep defaults but feel free to reopen if this gets more interest. Thank you!

**Comment by hertschuh** [comment]
Hi @foxik , looking at this again. Once https://github.com/keras-team/keras/pull/19176 is submitted, you can use a `torch.utils.data.DataLoader` with a custom `torch.utils.data.IterableDataset` that internally loops forever. This will have the same effect as `tf.data.Dataset.repeat()`. Then, you can (and must) set the `steps_per_epoch`.

**Comment by foxik** [comment]
Hi @hertschuh , thanks for the response :+1: And thanks for adding support for the `IterableDataset` :rocket: 

Although from my point of view, even if it is possible to use the `IterableDataset`, it is still much less comfortable than just adding a `.repeat()` to a `tf.data.Dataset`, and I still think that when `steps_per_epoch` is set, the dataset should be iterated repeatedly.

BTW, in our case, we ended up creating a custom sampler that just iterates a given dataset in random permutations as many times as needed (and remembers unused data between iterations). That way we have a `MapDataset` with a-priori known size (and the batching is done by the `DataLoader`), but instead of giving the `steps_per_epoch` to the `.fit` method, we give it to the sampler when creating the `DataLoader`.

**Comment by hertschuh** [comment]
@foxik , oh yes, a custom sampler is a really good solution for this.
