### ISSUE TITLE
Module 'pydot' has no attribute 'InvocationException'

### ISSUE THREAD

**Issue by novalex9800** [keras-team/keras#19040]
The error occured using plot_model with the latest newly installed versions of pydot and graphviz. I tried to follow the instructions in issue 3210 to no avail. Specifically I tried

pip install pydot-ng
pip install pydot==1.0.2 --upgrade (but not sudo pip install pydot==1.0.2 --upgrade because I do not have administrative priveledges on this system)

**Comment by SuryanarayanaY** [comment]
Hi @novalex9800 ,

The error indicates the installed version of pydot might be older and don't have attribute `InvocationException`.

You might need pydot_ng ~=2.0.0 with keras3. I tested installing pydot_ng=1.0.0 & 2.0.0 , pydot=1.4.2 and called `pydot.InvocationException()` which is success.Please refer attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/672a9fb9bcb3956048c2ec49fa49186a/none.ipynb#scrollTo=x31kScOSZWuj).

You might need to ensure latest `pydot_ng` and make sure it was imported. Please submit the version of pydot_ng imported. May be you can create a separate environment of your own.

**Comment by ayodejimb** [comment]
I got the same error when trying to use the 'plot_model' function of Keras in TensorFlow. This function uses both pydot and graphviz,  and I solved the problem by properly installing graphviz. I installed graphviz (on Windows OS) using the executable file that can be found here - https://forum.graphviz.org/t/new-simplified-installation-procedure-on-windows/224

I hope this helps!!

**Comment by iamtekson** [comment]
The issue still persists!

**Comment by TahaSherif** [comment]
Same here, the issue still persists for me!

**Comment by ztsv-av** [comment]
possible solution: I installed pydot==2.0.0 and graphviz and the issue still persisted for me. However, after just simply restarting the pc, the issue was gone. Not sure if this simple solution helps, but you can try it :) good luck!

**Comment by Nourine-Nadir** [comment]
Please refer your **tensorflow version** when you ask about these packages issues, because most of the time it is just **version compatibility**.
For me i just had to close the pycharm project and reopen it to get it work.

**Comment by MrOxMasTer** [comment]
tensorflow 2.16.1. The problem still exists
![image](https://github.com/keras-team/keras/assets/59291123/afa1984d-32ea-486a-9042-339fcd90b43c)

**Comment by MrOxMasTer** [comment]
I installed pydot version 1.4.2 and now there is another error
```
You must install graphviz (see instructions at https://graphviz.gitlab.io/download/) for `plot_model` to work.
```

**Comment by MrOxMasTer** [comment]
I installed version 2.46 of graphviz and rebooted the computer. Everything worked

**Comment by syedalimohsinbukhari** [comment]
I had the same issue, I have python3.9, and what worked for me was

```
pip install pydot==2.0.0
sudo apt install graphviz
```

**Comment by vmlstandard** [comment]
for Mac: 
brew install graphviz

**Comment by 0xAtlxolotlz** [comment]
I'm using `tensorflow 2.16.1` with a Conda environment on macOS. The following worked for me:

```
pip install pydot
conda install graphviz
```

**Comment by gayanlanke** [comment]
I'm using `'Windows-10-10.0.22631-SP0'` with `tensorflow 2.16.1`, `keras 3.4.1` in Conda environment. I had the same issue, and was fixed with the following:

```
pip install pydot # 2.0.0
conda install graphviz # 2.50.0

**Comment by Leo-jiahao** [comment]
I'm using tf 2.16.1 and keras 3.4.1  with ubuntu2204.I had the same issue, and fixed.
`pip install pydot # 2.0.0
sudo apt install graphviz
`

**Comment by AnushangaWimalasena** [comment]
For Mac M2
Keras: 3.4.1
pydot: 1.4.2
brew install graphviz

**Comment by FynnGilbert** [comment]
> I had the same issue, I have a conda environment with `python3.11.9`, and what worked for me was
> 
> ```
> pip install pydot==2.0.0
> sudo apt install graphviz
> ```

On Ubuntu 22.04.4 and `sudo apt install grphviz` worked for me

**Comment by ali-kanbar** [comment]
> tensorflow 2.16.1. The problem still exists ![image](https://private-user-images.githubusercontent.com/59291123/335601651-afa1984d-32ea-486a-9042-339fcd90b43c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNTg2NzcsIm5iZiI6MTcyMTA1ODM3NywicGF0aCI6Ii81OTI5MTEyMy8zMzU2MDE2NTEtYWZhMTk4NGQtMzJlYS00ODZhLTkwNDItMzM5ZmNkOTBiNDNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDE1NDYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5N2ViN2I5NzBhZDA0N2M5Y2Q0MzA2ZTE5YjJjZmZlZGM2ZWVhNmJjNGU1OWJlZjM2OGExNDFkY2MwMzNmYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mqYEUXQQKbLCJDyheEE2T8JnjWHoGQSxKQiEws5Vyds)

Hi,
Did you solve the issue??
if yes, could you tell me how??

**Comment by abkhoshk** [comment]
for me with conda and tensorflow 2.17 on gpu RTX4060

this code from [gayanlanke](https://github.com/gayanlanke) worked !!

pip install pydot # 2.0.0
conda install graphviz # 2.50.0

**Comment by HieronymusEsteban** [comment]
I have a the same problem in a docker container (downloaded image like so: FROM python:latest) on an M1 mac.
