### ISSUE TITLE
Likely misbehaving keras.ops.triu()

### ISSUE THREAD

**Issue by gtikhonov** [keras-team/keras#19043]
**Describe the bug**
`keras.ops.triu(x, k)` nullifies only elements below main diagonal as if it always treats the `k` argument as if it is negative.

**To Reproduce**
```
import numpy as np
import keras
print(np.__version__, keras.__version__)
print(np.triu(np.ones([5,5]), k=1))
print(keras.ops.triu(keras.ops.ones([5,5]), k=1))
print(keras.ops.triu(keras.ops.ones([5,5]), k=-1))
```

**Expected behavior**
`keras.ops.triu(x, k)` would act according to its documentation for all integer `k` values.

**Additional context**
Numpy v1.23.5 
Keras v3.0.2

**Comment by dugujiujian1999** [comment]
keras.ops.triu Actually calls keras.backend.tensorflow.numpy when backend is tensorflow.
I am check it right now.
I think this causes https://github.com/keras-team/keras/issues/19045

**Comment by dugujiujian1999** [comment]
Looks like the bug was introduced in this pr:
https://github.com/keras-team/keras/commit/ef339e8adf005e24508fe2c2d1a885576be1378e

**Comment by dugujiujian1999** [comment]
I am working on a fix to solve this.
