### ISSUE TITLE
Model parallelism with Keras 3 model

### ISSUE THREAD

**Issue by haohuanw** [keras-team/keras#19049]
(this is more like an inquiry)

i am trying to get a high level understanding on whether and how model/tensor parallel training could work with keras model.

for jax, i think it should be doable through jax mesh and partition keras's trainable weights but it would be great if some examples could be shared on developer guides.

for pytorch, i don't have much clue on using torch's model parallelism method (eg. [FSDP](https://pytorch.org/docs/stable/fsdp.html)) since it takes a `nn.Module` as input. i am guessing i can probably have an inverse of `keras.layers.TorchModuleWrapper` that makes keras model's variable traceable in `nn.Module` so that torch FSDP can partition the weights.

another alternative I could think of is to wrap the torch module into keras and then leverage the distributed lib?

I am looking for suggestions, some examples if possible and thanks in advance!

**Comment by haohuanw** [comment]
i just found keras model inherits layer and then inherits backend layer. for torch backend layer it is inherits nn.Module so in theory any torch specific distributed training utility can directly wrap a keras model and should work out of the box.

just want to double check with the keras team if this is a correct understanding.

**Comment by qlzh727** [comment]
Thanks for the question. Keras 3 model actually support DDP and FSDP as of today. You can see more details in https://keras.io/guides/distributed_training_with_torch/.

The current Keras distribution API only has jax backend implemented, and we will add Pytorch and TF backend soon. The Pytorch backend will probably be backed by torch.xla or torch.dtensor.
