### ISSUE TITLE
Stable diffusion is broken since Keras 3.0.2. Works fine with older versions of keras.

### ISSUE THREAD

**Issue by divyashreepathihalli** [keras-team/keras#19045]
Stable diffusion is broken since Keras 3.0.2. Works fine with older versions of keras.
Repro colab : https://colab.sandbox.google.com/drive/1CLsnhWJEa8ulwMXQ1SPN4tRU-LvkD9bf#scrollTo=Vo_YuNKb0DBj

I have narrowed it down to this part of the code 
this line is returning NaNs for keras 3.0.2 https://github.com/keras-team/keras-cv/blob/master/keras_cv/models/stable_diffusion/stable_diffusion.py#L123
calling predict_on_batch with TextEncoder class defined here https://github.com/keras-team/keras-cv/blob/master/keras_cv/models/stable_diffusion/text_encoder.py#L21

**Comment by dugujiujian1999** [comment]
Fixed.
Check out my pr:
https://github.com/keras-team/keras/pull/19046
