### ISSUE TITLE
Where to add CUDA implementation for keras.optimizers.Lion

### ISSUE THREAD

**Issue by Lifann** [keras-team/keras#19047]
Hi. I'm using H100 to train my model for rec-sys. And the Lion optimizer shows good convergence.

But I found the GPU SM occupancy is super low in current implementations, which is combination of tf APIs.

I've implemented a CUDA version of Lion. Where should I send the pull requests? Since I haven't found any directory in keras for cpp file to contribute with.

**Comment by grasskin** [comment]
Hi @Lifann, would you be able to share a code repository/colab with your implementation? Would this work for our multibackend (TF, torch, jax, numpy) system? We're interested in considering custom CUDA/potentially custom triton implementations in Keras. Thank you.
