### ISSUE TITLE
Layer objects have no attribute `input_shape` or `output_shape`

### ISSUE THREAD

**Issue by Pierre-Am** [keras-team/keras#19052]
I am trying to migrate from `tf.keras` to `keras` but have an error on the following line due to missing `input_shape` and `output_shape` attributes for `Layers` objects:

```python
shapes = {model.layers[0].name: model.layers[0].input_shape[0]}
for layer in enumerate(model.layers[1:]):
    shapes[layer.name] = layer.output_shape
```

Does anyone know how to do this with `keras.layers.Layer` instead of `tf.keras.layers.Layer` ?

Thanks

**Comment by SuryanarayanaY** [comment]
Hi @Pierre-Am ,

If you might have using `tf.keras.layers.InputLayer` which have `input_shape` argument, the equivalent in keras3 is `keras.layers.InputLayer` and instead of `input_shape` just use `shape`.

Please refer the source code for more details.
https://github.com/keras-team/keras/blob/c4dd4fab5bd9491b32b4ab1e360d290ad8e8a238/keras/layers/core/input_layer.py#L24-L27

**Comment by SuryanarayanaY** [comment]
If you are looking for more please submit a reproducible code snippet.Thanks!

**Comment by james77777778** [comment]
Hi @Pierre-Am 

Here is a workaround to manually compute the shape (if your model is `Sequential`):

```python
import keras

keras_model = keras.Sequential(
    [
        keras.layers.Dense(2, activation="relu", name="layer1"),
        keras.layers.Dense(3, activation="relu", name="layer2"),
        keras.layers.Dense(4, name="layer3"),
    ]
)

x = keras.ops.ones((3, 3))
y = keras_model(x)

input_shape = x.shape
for layer in keras_model.layers:
    output_shape = layer.compute_output_shape(input_shape)
    print(
        f"{layer.name}, "
        f"input_shape={input_shape}, "
        f"output_shape={output_shape}"
    )
    input_shape = output_shape

```

Should give you:

```bash
layer1, input_shape=(3, 3), output_shape=(3, 2)
layer2, input_shape=(3, 2), output_shape=(3, 3)
layer3, input_shape=(3, 3), output_shape=(3, 4)
```

**Comment by SuryanarayanaY** [comment]
Hi @Pierre-Am ,

With Keras3 you can use it like below:

```
for layer in keras3_model.layers:
      print(layer.input.shape)
      print(layer.output.shape)
```

Please refer attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/a1e83c0281b0ce81b1ec692dde0460ce/19052.ipynb).

**Comment by Pierre-Am** [comment]
Hi @SuryanarayanaY, that solved my issue, thanks !

**Comment by prabhash-monash** [comment]
use the attributes like this:

`layer.input.shape[-1]`
