### ISSUE TITLE
The initializer GlorotUniform is unseeded and being called multiple times

### ISSUE THREAD

**Issue by HripsimeS** [keras-team/keras#19068]
@sachinprasadhs @SuryanarayanaY Hello!

Can you please check my issue. I am trying to run the following script and I received the error below.
https://github.com/Yaxin-Cui/Graph-Neural-Network/blob/main/code/graphstellar_updated.py

Can you please help me to figure our what I should modify in the code to run it without that error. Thanks a lot in advance!

![keras](https://github.com/keras-team/keras/assets/42246765/fa299864-768c-4316-8f83-acfa51542ee4)

**Comment by SuryanarayanaY** [comment]
Hi @HripsimeS ,

It seems you are using Keras2. Can you upgrade it to Keras3 using pip install keras --upgrade and then replace import `tensorflow.keras as keras` with `import keras`.

Alternatively if you want to use tf.keras only first you need to import `tf-keras` package using `pip install tf-keras`
and then set environment variable `os.environ["TF_USE_LEGACY_KERAS"]="1"`.  Then you can import keras from tensorflow.

**Comment by HripsimeS** [comment]
@SuryanarayanaY thanks for your reply. According to the repository I can't use the keras directly, I need to import it from tensorflow. I followed your guide to use **pip install tf-keras** and then added **os.environ["TF_USE_LEGACY_KERAS"]="1"** under **tensorflow.keras as keras** line, but I am still getting exactly the same error I shared above. 

Please can test the code above to see how to fix the issue with the initializer GlorotUniform. Look forward to hearing from you!

**Comment by SuryanarayanaY** [comment]
It seems you are still using older keras version only. Since the error seems generating from initializers_v2.py file that won't exists in keras>=2.12v.

Try uninstalling the tensorflow and keras first and try with fresh installations as stated above. For keras either you go with tf-keras package in which case you can import keras as tf.keras.

Please cross check tensorflow and keras versions in use.

**Comment by HripsimeS** [comment]
@SuryanarayanaY please find below the versions of packages I have currently and still getting the error related to initializer GlorotUniform. Do you know which versions I need to install so I can import keras from tensorflow and not get that error?

import keras
keras.__version__
'**2.13.1**'

import tensorflow
tensorflow.__version__
'**2.13.0**'

from tensorflow.python import keras
 keras.__version__
'**2.6.0**'

**Comment by HripsimeS** [comment]
@sachinprasadhs @SuryanarayanaY Hello!

I updated to Keras3 but still getting the same error. As you can see **initializers_v2.py** is replaced with **initializers.py**. 
Do you know what is going on and why I am getting that error for this line of code?

**prediction = link_classification(output_dim=1, output_act="relu", edge_embedding_method='ip')(x_out)**

![image](https://github.com/keras-team/keras/assets/42246765/02e11880-dead-47bf-81dd-95db98ad64cb)
