### ISSUE TITLE
Is there a multi-backend way of doing identifying a tensor in Layer call method?

### ISSUE THREAD

**Issue by anas-rz** [keras-team/keras#19065]
Hi! I am trying to port an existing model to Keras 3 and want to check if the inputs are tensors or other iterators in Python. The sample code is as follows:
```
if isinstance(x, (list, tuple)):
    if len(x) != 2:
        raise ValueError("Expecting a list of length 2")
    x0, x1 = x
elif isinstance(x, tf.Tensor):
    if int(x.shape[self.axis]) != 2:
        raise ValueError(
            "Expecting a tensor of shape 2 along specified axis"
        )
    x0, x1 = tf.unstack(x, axis=self.axis)
else:
    raise TypeError("Expected a list, tuple, or Tensor as input")
```

Is there a multi-backend equivalent of this?

**Comment by sachinprasadhs** [comment]
Hi, 

You can use below methods in Keras 3 for Tensor operations.
```
import keras
from keras import ops
```
1. To check whether the given object is a tensor.
`ops.is_tensor(x)`
2.  To Unstack:
`ops.unstack(x)`
