### ISSUE TITLE
Renormalization module of BatchNormalization in torch backend is not implemented.

### ISSUE THREAD

**Issue by caolonghao** [keras-team/keras#19063]
It seems that the Renormalization module of `BatchNormalization` in torch backend is not implemented. 
Running `layers.BatchNormalization(axis=bn_axis, epsilon=1.001e-5, renorm=True, name=name + '_bn')` with pytorch backend results in
`ValueError: Unrecognized keyword arguments passed to BatchNormalization: {'renorm': True}`, but everything goes well with tensorflow backend.

**Comment by sachinprasadhs** [comment]
Thanks for reporting the issue.

`Renorm` is not implemented in any of the backend and it is not in the list of allowed arguments of BatchNormalization here https://keras.io/api/layers/normalization_layers/batch_normalization/

**Comment by caolonghao** [comment]
Thank you for your reply. Well, that is a little weird then, I'm reproducing a keras code and the author used 'Renorm' in BatchNormalization. 
In fact, if I run the code with TensorFlow backend, it goes well as expected. But when I do it with pytorch backend, it will have the error I mentioned above. If I delete the 'renorm', there will be some mismatching when loading model parameters.

**Comment by qlzh727** [comment]
Thanks for filing this issue. In keras 3, we removed some the flags from BN layer that was previously backend specific (eg renorm, virtual batch size, etc). So the renorm param is not supported by the tf backend as well.

Could you share your code snippet that produce this issue, as well as all the installed tf/keras package version?

Thanks.

**Comment by caolonghao** [comment]
Thanks for your reply. The repository of the code I want to reproduce is https://github.com/jpviguerasguillen/corneal_endothelium_TVST. The part including `renorm` is:
```python
def conv_block(x, growth_rate, name, data_format='channels_last'):
    """ A building block for a dense block.
    # Arguments
        x:          input tensor.
        growth_rate: float, growth rate at dense layers.
        name:       string, block label.
    # Returns
        Output tensor for the block.
    """
    bn_axis = 1 if data_format=='channels_first' else 3
    x1 = layers.Conv2D(growth_rate, 4, activation=None, padding='same',  
                       use_bias=False, data_format=data_format, 
                       name=name + '_conv')(x)
    x1 = layers.BatchNormalization(axis=bn_axis, epsilon=1.001e-5,
                                   renorm=True, name=name + '_bn')(x1)  
    x1 = layers.Activation('elu')(x1)
    x1 = layers.Dropout(rate=0.2, name=name + '_drop')(x1)
    x  = layers.Concatenate(axis=bn_axis, name=name + '_conc')([x,x1])    
    return x

def down_block(x, out_channels, name, data_format='channels_last'):
    """ The downsampling block, which contains a feature reduction layer, 
    (Conv1x1) + BRN + ELU, and a average pooling layer.
    # Arguments
        x:            input tensor.
        out_channels: float, number of output channels.
        name:         string, block label.
    # Returns
        Output tensor for the block.
    """
    bn_axis = 1 if data_format=='channels_first' else 3
    x = layers.Conv2D(out_channels, 1, activation=None, padding='same',  
                      use_bias=False, data_format=data_format, 
                      name=name + '_conv')(x)
    x = layers.BatchNormalization(axis=bn_axis, epsilon=1.001e-5,
                                  renorm=True, name=name + '_bn')(x)  
    x = layers.Activation('elu')(x)
    x = layers.AveragePooling2D(2, padding='same', 
                                data_format=data_format)(x)  
    return x
```

The version of tensorflow is `2.15.0`

**Comment by qlzh727** [comment]
l see. Then you probably have to change the renorm=False in this case since it is not supported by the keras 3.0. Its also unclear to me whether the renorm is necessary or critical in this case.
