### ISSUE TITLE
Accuracy and loss graphs are very different. What could be the reason for this?

### ISSUE THREAD

**Issue by feridesecil13** [keras-team/keras#19087]
![Figure 2024-01-23 114913](https://github.com/keras-team/keras/assets/74592798/1895cbb0-bfd9-4798-aed3-b3179ec7c0ed)
![Figure 2024-01-23 114922](https://github.com/keras-team/keras/assets/74592798/6bf4c257-d07a-45ee-b402-f64feaa58287)

**Comment by sachinprasadhs** [comment]
Hi, The IoU graph and it's ranges does not look right, there might be something you're missing in the code.
Could you please clarify on the metric you are using and if possible please provide sample reproducible code.
