### ISSUE TITLE
Input_length keyword parameter in the Embedding Layer of Keras 3

### ISSUE THREAD

**Issue by longsc2603** [keras-team/keras#19094]
<img width="563" alt="image" src="https://github.com/keras-team/keras/assets/56826526/250585ba-2b4c-4eb5-b48e-9484a6620cf7">

In this Keras 2 doc page, there is a keyword parameter named 'input_length', which is not the case for the Keras 3 doc page in the below image.
<img width="564" alt="image" src="https://github.com/keras-team/keras/assets/56826526/93ec5709-f590-43f3-835a-948cb904c863">

However, the example shown below that function definition of Keras 3 also shows an argument 'input_length', maybe this is a problem.
<img width="566" alt="image" src="https://github.com/keras-team/keras/assets/56826526/e4b21eb9-0a60-4286-bd83-48e35a5f7170">

The link for the Keras 2 documentation page: https://keras.io/2.15/api/layers/core_layers/embedding/
and Keras 3 documentation page: https://keras.io/api/layers/core_layers/embedding/

Also, since the new Keras 3 Embedding class has no 'input_length' parameter, I am having a problem trying to use a Keras 2-trained model with Keras 3. Can anyone help? Thank you so much.

**Comment by SuryanarayanaY** [comment]
Hi @longsc2603 ,

In Keras2 implementation either you can provide sequence length to `input_length` parameter or you can pass `input_shape` as kwargs. If both provided input_shape will be considered by the API. 

In Keras3 implementation the parameter `input_length` is removed as it is redundant as you can use `input_shape` as kwarg. Even if you  won't provide `input_shape` the API can infer it from the input being passed to model.

Please refer the attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/f9c7b558969391b5cdcbd8019bacb181/19094_embedding_layer.ipynb) for demo.

Hope it helps. Thanks!

**Comment by longsc2603** [comment]
I seem to have passed that problem, since you are already here, could you help me solve another problem related to keras 3 and tf 2?
I got a part of the code below that is not working properly, the error is shown below 
<img width="746" alt="image" src="https://github.com/keras-team/keras/assets/56826526/0ec6b907-03d6-4090-8ef6-f2a1db481b79">

I searched online and come to think that this maybe due to tensorflow graph as defined below
<img width="255" alt="image" src="https://github.com/keras-team/keras/assets/56826526/32e6bbb0-14ff-4b39-b9ca-0edb0d2ed664">

The part of the code that is showing error:
<img width="569" alt="image" src="https://github.com/keras-team/keras/assets/56826526/54103f48-0870-4858-a775-60e22e5d1a5b">

I don't know how exactly to overcome this, many suggestions were for Keras 2 and I am using Keras 3, can you help? Thank you

**Comment by SuryanarayanaY** [comment]
Hi @longsc2603 ,

If you are using TF1.x graph then I afraid we are not supporting it anymore. You need to migrate to TF2.x style coding which is compatible with Keras3. Thanks!

**Comment by longsc2603** [comment]
@SuryanarayanaY, can you please elaborate on how could I do that effectively, I'm not very familiar with the Tensorflow coding style. If you could give a complete tutorial link, that is also okay. Thanks

**Comment by SuryanarayanaY** [comment]
Hi @longsc2603 ,

There are lot of guides for migrating from TF1.x to TF2.x. Please refer the guides here at [migrate to Tf2.x](https://www.tensorflow.org/guide/migrate). 

I recommend to stick to keras2 only by setting the environment variable TF_USE_LEGACY_KERAS=1 as the migration is for TF2.x(i.e Keras2) and not sure compatibility with Keras3.

**Comment by skeeperloyaltie** [comment]
> Hi @longsc2603 ,
> 
> In Keras2 implementation either you can provide sequence length to `input_length` parameter or you can pass `input_shape` as kwargs. If both provided input_shape will be considered by the API.
> 
> In Keras3 implementation the parameter `input_length` is removed as it is redundant as you can use `input_shape` as kwarg. Even if you won't provide `input_shape` the API can infer it from the input being passed to model.
> 
> Please refer the attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/f9c7b558969391b5cdcbd8019bacb181/19094_embedding_layer.ipynb) for demo.
> 
> Hope it helps. Thanks!

I think this works..
