### ISSUE TITLE
[Performance regression] Since keras==3.0.3, using ArrayDataAdapter with PyTorch is much slower

### ISSUE THREAD

**Issue by foxik** [keras-team/keras#19120]
Since `keras==3.0.3`, using numpy data with `Model.fit` is much slower in PyTorch

Consider a very simple example:
```python
import os
os.environ["KERAS_BACKEND"] = "torch"
import keras
(x_train, y_train), _ = keras.datasets.mnist.load_data()
model = keras.Sequential([keras.layers.Flatten(), keras.layers.Dense(10, activation="softmax")])
model.compile(optimizer=keras.optimizers.Adam(), loss=keras.losses.SparseCategoricalCrossentropy(), metrics=[keras.metrics.SparseCategoricalAccuracy()])
model.fit(x_train, y_train, batch_size=200, epochs=5)
```

The following Colab https://colab.research.google.com/drive/1iLD7N_koi816EX0gVhRnkB0Vbl1k6ysV?usp=sharing shows the following timigs:
- Keras 3.0.2: ~3s per epoch
- Keras 3.0.3: ~7-8s per epoch
- keras-nightly-3.0.4.dev2024013003: ~7-8s per epoch.

I have traced the problem to the updates in the ArrayDataAdapter, specifically to the `ArrayDataset` used in PyTorch: https://github.com/keras-team/keras/blob/088f0fcf09c991475a3eb7b814d2d453bbf0a6e4/keras/trainers/data_adapters/array_data_adapter.py#L259-L304

If instead of using `ArrayDataset` you use the `torch.utils.data.StackDataset`, i.e., you replace the last line in the above snippet `dataset = ArrayDataset(self._inputs) ` with
```python
dataset = torch.utils.data.StackDataset(*self._inputs)
```
then the training in Keras 3.0.3 gets back to speeds of Keras 3.0.2.

However, a proper fix would be more complicated, because the `self._inputs` might have a more complex structure (the elements of `self._inputs` can be lists or dictionaries) -- but I presume the elements of `self._inputs` can be just non-nested lists and dictionaries, so calling `StackDataset`  (optionally several times) should be probably enough to cover all cases...

**Comment by SuryanarayanaY** [comment]
Hi @foxik ,

I have replicated the issue and acknowledge the drop in performance wrt Keras3.0.2 vs latest. Attaching [gist](https://colab.research.google.com/gist/SuryanarayanaY/61b1020e1f51b9bae34236f8fc2445a5/19120_arraydataadapter-with-pytorch-got-slower.ipynb) for same.

If you are willing to contribute please feel free to do and Team will help on same. Thanks!

**Comment by hertschuh** [comment]
@foxik , thank you for the bug report.

For the fix, I ended going a different route than `StackDataset` to easily handle arbitrary nested structures.

**Comment by hertschuh** [comment]
Fix should be in keras-nightly.
