### ISSUE TITLE
TorchDataLoaderAdapter is not compatible with torch.utils.data.IterableDataset (no __len__() dataset)

### ISSUE THREAD

**Issue by ixig** [keras-team/keras#19156]
The PyTorch DataLoader supports supports both map-style and iterable-style datasets -- the latter, IterableDataset, is used for data streams, and hence its length is unknown, and as such, has no `__len__()` method implemented. This is not unlike tf.data.Dataset, which also does not require that the dataset's length is known.

However, using an PyTorch IterableDataset fails with Keras -- at least it does when a PyTorch DataLoader created from an IterableDataset is passed as an argument to `validation_data` in `keras.Model.fit()`. There are (at least two) reasons:

1. In JAXTrainer.fit(), there is a conditional statement `if validation_data:` -- this causes Python to implicitly call __len__() on PyTorch'es `DataLoader.__len__()`, which in turns call PyTorch'es `IterableDataset.__len__()`
2. In TorchDataLoaderAdapter.__init__(), there is an explicit call: `self._size = len(dataloader)`

Also, an IterableDataset will return a batch of examples (instead of a single example) at a time, and as such. the associated DataLoader will be instantiated with `batch_size=None` (i.e. automatic batching disabled). As such, in TorchDataLoaderAdapter.__init__(), the following will fail:
```
self._batch_size = dataloader.batch_size
...
self._partial_batch_size = len(dataloader.dataset) % self._batch_size
```

**Comment by hertschuh** [comment]
@ixig ,

Thank you for the report. These 3 issues were indeed preventing the use of `IterableDataset`.

I'm adding support for it, `__len__` can be implemented or not and the batch size can be `None` or defined.

**Comment by hertschuh** [comment]
@ixig the fix will be in `keras-nightly` tomorrow.

Thanks!
