### ISSUE TITLE
enable_lora() API introduces new weights with a different path than other model weights

### ISSUE THREAD

**Issue by martin-gorner** [keras-team/keras#19163]
Here is an excerpt from a model where LoRA was enabled on query and value layers:

```
decoder_block_0/pre_attention_norm/scale                    (2048,)           PartitionSpec()
decoder_block_0/attention/query/kernel                      (8, 2048, 256)    PartitionSpec(None, 'model')
query/lora_kernel_a                                         (8, 2048, 4)      PartitionSpec(None, None, None)
query/lora_kernel_b                                         (4, 256)          PartitionSpec()
decoder_block_0/attention/key/kernel                        (1, 2048, 256)    PartitionSpec(None, 'model')
decoder_block_0/attention/value/kernel                      (1, 2048, 256)    PartitionSpec(None, 'model')
value/lora_kernel_a                                         (1, 2048, 4)      PartitionSpec(None, None, None)
value/lora_kernel_b                                         (4, 256)          PartitionSpec()
decoder_block_0/attention/attention_output/kernel           (8, 256, 2048)    PartitionSpec(None, None, 'model')
```

Notice that LoRA weights have a name that does not start with `decoder_block_0/attention` as all other weights in this Transformer model.

**Comment by fchollet** [comment]
Weight names reflect the name scope hierarchy at the time the weight was created. Lora weights are created under the layer's name scope only.

**Comment by martin-gorner** [comment]
Can't the LoRA weights take on the scope of the original kernel they are lora-fying?
decoder_block_0/attention/query/kernel =>
decoder_block_0/attention/query/lora_kernel_a
decoder_block_0/attention/query/lora_kernel_b

**Comment by fchollet** [comment]
I fixed by "recording" the path the first time a weight gets created, so that subsequent weights all use the same path.
