### ISSUE TITLE
Keras just for load_model

### ISSUE THREAD

**Issue by marcelo-bn** [keras-team/keras#19167]
Hey guys!

I only need to load a model into a production environment, but to do this I need to install the entire Keras library and consequently the entire tensorflow library. All these packages cost me almost 1.5 GB and my resources are limited.

So I need a simple version of Keras just to load my model. Is there any way to do this?

**Comment by lxzheng** [comment]
@marcelo-bn 
You can try tf serving. It is designed specifically for serving models in production.
