### ISSUE TITLE
BackupAndRestore callback does not work as in the example

### ISSUE THREAD

**Issue by N4321D** [keras-team/keras#19179]
I noticed that the backup and restore callback does not reduce the number of epochs that are being trained / restore the last trained epoch number. The example suggest that this should be the case [link:](https://keras.io/api/callbacks/backup_and_restore/)

system info:
OS: Pop Os 22.04 LTS
keras version: 3.0.1
keras backend: tested with torch and tensorflow
python version: 3.10.13 (in anaconda)

```
import keras
import numpy as np

class InterruptingCallback(keras.callbacks.Callback):
   def on_epoch_begin(self, epoch, logs=None):
     if epoch == 4:
       raise RuntimeError('Interrupting!')
callback = keras.callbacks.BackupAndRestore(backup_dir="/tmp/backup")
model = keras.models.Sequential([keras.layers.Dense(10)])
model.compile(keras.optimizers.SGD(), loss='mse')
try:
   model.fit(np.arange(100).reshape(5, 20), np.zeros(5), epochs=10,
             batch_size=1, callbacks=[callback, InterruptingCallback()],
             verbose=0)
except Exception as e:
   print(e)
history = model.fit(np.arange(100).reshape(5, 20), np.zeros(5),
                     epochs=10, batch_size=1, callbacks=[callback],
                     verbose=0)
len(history.history['loss'])
```
ouput:
```
Interrupting!
10  
```

It does 10 epochs in the last model.fit call even though the example suggest that it would remember the interruption at epoch 4 and continue from there.

**Comment by sachinprasadhs** [comment]
Thanks for reporting the issue.

I was able to replicate the issue here [![](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.sandbox.google.com/gist/sachinprasadhs/eca8195ad59de2ff5a9f73a227c626d0/19179.ipynb)

**Comment by fchollet** [comment]
Thanks for the report -- I just fixed it. Please check that the build at HEAD works for your use case.

**Comment by N4321D** [comment]
![image](https://github.com/keras-team/keras/assets/35295509/1f796409-679b-4d69-92ea-f4689322830e)

Thank you it works!
