### ISSUE TITLE
Keras: Backend, does it support numpy?

### ISSUE THREAD

**Issue by abhaskumarsinha** [keras-team/keras#19171]
I was just checking the codebase for the Backend of the Keras

https://github.com/keras-team/keras/blob/08c4b0414ccad56c286bb30fff6d7a97c5721e0a/keras/backend/__init__.py#L40C1-L41C52

```
elif backend() == "numpy":
    from keras.backend.numpy import *  # noqa: F403
```

Does it support Numpy without TF, PyT, and JAX backend for now?

From what I've been able to gather (sorry I'm a bit confused), to get any backend deep learning engine into Keras, I'd have to start with `./keras/backend/` and write each module like PyTorch, and TensorFlow using that backend engine to get everything with Keras?

Right?

Make a dir: `./keras/backend/[custom framework]/` and port each module accordingly. 
This is because we are working on some special CNN accelerator hardware and that requires special software written for that specific processing system, if we can get that into Keras, then it'd be easy to open source things (tho, we might not open source the code for now, given technical limitations).

**Comment by abhaskumarsinha** [comment]
Hello @sachinprasadhs 

Thank you for the response. From what I understand Keras 3 currently supports only three: `jax, tensorflow, pytorch`. 

I was wondering if one needs to add support for the newer framework, then what are the core folders/files and configurations that one would need to look into?

I want to understand the codebase of Keras and how the lower level of framework code is interacting with higher-level Keras abstraction in the code. This is the objective for me currently to understand.

Thank You.

**Comment by sachinprasadhs** [comment]
You can look into the backend directory here for all the backend implementations https://github.com/keras-team/keras/tree/master/keras/backend

**Comment by abhaskumarsinha** [comment]
Ah, thanks. I got it. 
I'm closing this issue now.
