### ISSUE TITLE
TorchModuleWrapper directly calls to .forward

### ISSUE THREAD

**Issue by gilfree** [keras-team/keras#19182]
Hi,

The `TorchModuleWrapper` class directly calls to the torch module `.forward` of the wrapped torch module, I do not know if this is intentional, but calling the `forward` and not `__call__` skips some torch code that is useful - it has hooks, it handles some interaction with dynamo in more. (I discovered it when some hooks stopped running)

This line:

https://github.com/keras-team/keras/blob/d5a452155a415d5fcbe568eb2a8441f64e57aa90/keras/utils/torch_utils.py#L113

Could probably be:

```py
return self.module(*args, **kwargs)
```

If there is a good reason to avoid the `__call__` , then all good (What is the reason?)
But, it might be just an oversight, and trivially fixable. (the unit tests on  keras/utils/torch_utils_test.py pass with the change).

Thanks!

**Comment by fchollet** [comment]
Thanks for the report. This was just an oversight. I fixed it.
