### ISSUE TITLE
Typo in Weights-only saving

### ISSUE THREAD

**Issue by ankitmaurya001** [keras-team/keras#19187]
There is a typo in the Weights-only saving [example.](https://keras.io/getting_started/faq/#what-are-my-options-for-saving-models)
`model.save_weights('my_model.weights.5')`
 It should be:
 `model.save_weights('my_model.weights.h5')`

Please let me know I can raise a PR.

**Comment by sachinprasadhs** [comment]
Thanks for reporting the issue. I have linked the PR here with correction.
