### ISSUE TITLE
Enhancing UpSampling2D for Exact Size Resizing

### ISSUE THREAD

**Issue by willyfh** [keras-team/keras#19192]
Currently, the `UpSampling2D` function only allows us to resize input by a certain factor using the size parameter. But sometimes, we need to resize to an exact size instead. For example, if we have an input size of 100x100 pixels and want to upscale it to a target size of 250x250 pixels, a problem arises when the target size doesn't neatly divide the input size. In such cases, the upscaling process doesn't work well even when we set `size = target_size/original_size` because decimal values are rounded. As users, of course we can customize the UpSampling2D by overriding the layer, or just create a custom layer. However, adding this feature directly to UpSampling2D would simplify the implementation and make it easier for the user.

**Comment by SuryanarayanaY** [comment]
Hi @willyfh ,

I think you might use the [keras.layers.Resizing](https://keras.io/api/layers/preprocessing_layers/image_preprocessing/resizing/) layer for that.Upsampling won't work in the way you wanted but Resizing may works. Please check and confirm.

**Comment by willyfh** [comment]
@SuryanarayanaY Oh great! Yeah, it seems the `Resizing` also works fine to be used as a hidden layer. I only checked this page https://keras.io/api/layers/reshaping_layers/ before, I thought everything related to reshaping/resizing would be there😅. Thanks for your answer!
