### ISSUE TITLE
error: A deterministic GPU implementation of AdjustContrastv2 is not currently available 

### ISSUE THREAD

**Issue by NKM999** [keras-team/keras#19197]
Hello,

os.environ['TF_DETERMINISTIC_OPS'] = '1' is not working with layers.experimental.preprocessing.RandomContrast.

I am using "layers.experimental.preprocessing.RandomContrast" in my custom CNN model for data augmentation. However, I observed the following error: A deterministic GPU implementation of AdjustContrastv2 is not currently available.
	 [[{{node model[/sequential_1/random_contrast/adjust_contrast](http://localhost:8888/sequential_1/random_contrast/adjust_contrast)}}]] [Op:__inference_train_function_4097]
	 
	 Due to the above error, I am not able to use os.environ['TF_DETERMINISTIC_OPS'] = '1', and hence, not able to get the reproducible results with the model.
	 
	 Please provide a solution. 
	 
	 Thanks and Regards

**Comment by sachinprasadhs** [comment]
Hi, Could you please provide the reproducible code to replicate the reported behavior. Thanks!
