### ISSUE TITLE
StringLookup Layer not working with sequences when output mode is one-hot

### ISSUE THREAD

**Issue by pinsondg** [keras-team/keras#19191]
I am reviving this error when trying to use the 'one-hot' output mode on a string lookup layer.
`When output_mode is not 'int', maximum supported output rank is 2. Received output_mode one_hot and input shape (None, 30), which would result in output rank 3.`

I am trying to input a sequence of strings using a `tf.data.Dataset`. The length of the sequence is 30. Here is what the element spec looks like for my dataset object.
```python
((TensorSpec(shape=(None, 30, 25), dtype=tf.float64, name=None),
  TensorSpec(shape=(None, 30), dtype=tf.string, name=None),
  TensorSpec(shape=(None, 30), dtype=tf.string, name=None),
  TensorSpec(shape=(None, 30), dtype=tf.int32, name=None),
  TensorSpec(shape=(None, 30), dtype=tf.string, name=None),
  TensorSpec(shape=(None, 30), dtype=tf.int32, name=None),
  TensorSpec(shape=(None, 30), dtype=tf.string, name=None),
  TensorSpec(shape=(None, 30), dtype=tf.string, name=None),
  TensorSpec(shape=(None, 30), dtype=tf.string, name=None),
  TensorSpec(shape=(None, 28), dtype=tf.float64, name=None),
  TensorSpec(shape=(None,), dtype=tf.string, name=None),
  TensorSpec(shape=(None,), dtype=tf.string, name=None),
  TensorSpec(shape=(None,), dtype=tf.string, name=None),
  TensorSpec(shape=(None,), dtype=tf.string, name=None)),
 TensorSpec(shape=(None,), dtype=tf.int32, name=None))
```

I the StringLookup layer is being passed as the first layer in my model. It seems like the batch dimension is being taken into account in the rank calculation, which is causing my model to fail. I also notice this comment in the[ code](https://github.com/keras-team/keras/blob/7ce3d62af7cc6959fc5a5841cfe17043dfcb8615/keras/utils/tf_utils.py#L75). Is this still on the docket to remove this rank restriction?

**Comment by sachinprasadhs** [comment]
Hi, Could you please provide the sample reproducible code to replicate the reported behavior. Thanks!

**Comment by pinsondg** [comment]
Hi @sachinprasadhs here is a basic example where this problem can be reproduced.
```
import tensorflow as tf

# Dataset of a sequence of strings
ds = tf.data.Dataset.from_tensor_slices([["a", "b", "c"] * 20]).repeat(150)
# Dummy labels
mock_labels = tf.data.Dataset.from_tensor_slices([1]).repeat(150)
# Combine datasets
ds = tf.data.Dataset.zip((ds, mock_labels)).cache().batch(32)
print(len(ds))
print(ds.element_spec)
# Define String Lookup Layer in One Hot Mode
string_lookup_layer = tf.keras.layers.StringLookup(output_mode="one_hot")
string_lookup_layer.adapt(ds.map(lambda x, y: x))
print(string_lookup_layer.get_vocabulary())

# Define basic model
model = tf.keras.Sequential([
    string_lookup_layer,
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(1, activation='linear')
])

# Try to compile model -> this will fail with error message: When output_mode is not `'int'`, maximum supported output rank is 2.
model.compile(optimizer='adam', loss='mean_squared_error')
model.summary()
model.fit(ds, epochs=5)
```

**Comment by sachinprasadhs** [comment]
I was able to reproduce the issue here [![](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/gist/sachinprasadhs/fc5be3e7cac24bdea94d6f7cf9a1eab7/19191.ipynb)
