### ISSUE TITLE
How to save only the weights of trainable parameters?

### ISSUE THREAD

**Issue by inconnu11** [keras-team/keras#19208]
I am using the low-rank adaptation to train my keras model. The base model is frozen and only lora linear layers are trained. I want to save the trainable lora-related parameters instead of the whole model. How to do this? Are there some apis behaving like  `torch.save(state_dict, filepath)` ?

**Comment by SuryanarayanaY** [comment]
Hi @inconnu11 ,

In Keras `model.save` saves complete model and `model.save_weights` saves only weights of the model layers that includes frozen layers also.AFAIK, There is no direct method to store only the trainable weights.

However you can get trainable parameters using `model.trainable_weights` which gives list of trainable_weights.

Also you can use layer.get_weights method to save the model trainable layers wieigths.You can use something like below.

```
weights=[]
for layer in model.layers:
  if layer.trainable:
    weights.append(layer.get_weights())
```

**Comment by fchollet** [comment]
> I want to save the trainable lora-related parameters instead of the whole model. How to do this? 

Assuming this is with a KerasNLP backbone, you can do:

```python
backbone.save_lora_weights(filepath)
```

You can then reload by:

1. Instantiating the base model (with the weights you started from, before fine-tuning)
2. Calling `backbone.load_lora_weights(filepath)`

**Comment by inconnu11** [comment]
Thanks for the prompt response :) 
I am rewriting the torch version [LoraWrapperRoberta](https://github.com/Montinger/Transformer-Workbench/blob/main/LoRA-from-scratch/LoraWrapperRoberta.py#L178C7-L178C25) into keras. I don't know how to implement funtion [replace_multihead_attention_recursion ](https://github.com/Montinger/Transformer-Workbench/blob/main/LoRA-from-scratch/LoraWrapperRoberta.py#L273C9-L273C46) in keras. 

Instead of class `RobertaSelfAttention` in the original repo, I used `TFElectraSelfAttention` which is importred as `from transformers.models.electra.modeling_tf_electra import TFElectraSelfAttention`.  My `replace_multihead_attention_recursion` implement is followed. But it doesn't  seem to be working and reports erros.

`  def replace_multihead_attention_recursion(self, model):

        for layer in model.submodules:
            print('submodel', layer)

            if isinstance(layer, TFElectraSelfAttention):
                self.nr_replaced_modules += 1

                # Create a new LoraMultiheadAttention layer
                new_layer = LoraTFElectraSelfAttention(rank=self.lora_rank, config=self.model_config)

                # Get the state of the original layer
                # state_dict_old = layer.state_dict()

                # Load the state dict to the new layer
                # new_layer.load_state_dict(state_dict_old, strict=False)
                new_layer.load_weights(layer.weights, by_name=True)  # 注意：Keras中的load_weights方法需要指定by_name=True来匹配层的名称和权重。

                # Get the state of the new layer
                # state_dict_new = new_layer.state_dict()

                # Compare keys of both state dicts
                # keys_old = set(state_dict_old.keys())
                # keys_new = set(k for k in state_dict_new.keys() if not k.startswith("lora_"))
                # assert keys_old == keys_new, f"Keys of the state dictionaries don't match (ignoring lora parameters):\n\tExpected Parameters: {keys_old}\n\tNew Parameters (w.o. LoRA): {keys_new}"

                # Replace the original layer with the new layer
                # setattr(model, name, new_layer)
                setattr(self.model, layer.name, new_layer)  # 注意：Keras中设置属性时需要使用layer.name来获取层名。
            else:
                # for name, sublayer in layer.layers.items():  # 注意：Keras中子层的获取方式与PyTorch不同，需要使用layer.layers属性。
                self.replace_multihead_attention_recursion(layer)  # 对子层递归执行替换操作。`

Could you please help me with the keras implement of funtion `replace_multihead_attention_recursion` ?

**Comment by inconnu11** [comment]
> Hi @inconnu11 ,
> 
> In Keras `model.save` saves complete model and `model.save_weights` saves only weights of the model layers that includes frozen layers also.AFAIK, There is no direct method to store only the trainable weights.
> 
> However you can get trainable parameters using `model.trainable_weights` which gives list of trainable_weights.
> 
> Also you can use layer.get_weights method to save the model trainable layers wieigths.You can use something like below.
> 
> ```
> weights=[]
> for layer in model.layers:
>   if layer.trainable:
>     weights.append(layer.get_weights())
> ```


Thanks for the prompt response :)  
What format should the variable `weights` be saved in? 
And how can I load this saved file?

**Comment by SuryanarayanaY** [comment]
Hi @inconnu11 ,

Did you referred the above [comment](https://github.com/keras-team/keras/issues/19208#issuecomment-1960520461) also as you are enabling lora ? Please provide more context. Thanks!

**Comment by inconnu11** [comment]
> KerasNLP backbone

Hi, my model is not KerasNLP backbone. I saved all the weights and re-assigned the lora parameters one by one.
