### ISSUE TITLE
Add ESN (echo state network) to Recurrent layers

### ISSUE THREAD

**Issue by Shchipunov** [keras-team/keras#19210]
Hello,
Since TensorFlow Addons project is deprecated and does not work in the last Keras versions is it possible to move ESN (https://www.tensorflow.org/addons/api_docs/python/tfa/layers/ESN) from TensorFlow Addons to Keras (Recurrent layers)?
Thanks.

**Comment by SuryanarayanaY** [comment]
Hi @Shchipunov ,

Would you able to contribute for this in Keras3?

**Comment by divyashreepathihalli** [comment]
@Shchipunov this is currently not on our teams priority at the moment.  But here is a Keras extension library you can possibly add this to - https://github.com/anas-rz/k3-addons/
