### ISSUE TITLE
Build in Keras3 Model will not build sub-layers

### ISSUE THREAD

**Issue by edwardyehuang** [keras-team/keras#19229]
In Keras 2,  the `keras.Model` has implemented `build` methods that try to run the `call()` to build sub-layers https://github.com/keras-team/keras/blob/601488fd4c1468ae7872e132e0f1c9843df54182/keras/engine/training.py#L541-L552

However, such implementation is missing in keras 3

**Comment by innat** [comment]
that is intended in keras 3, [src](https://github.com/keras-team/keras/issues/18823#issuecomment-1824865969).

**Comment by edwardyehuang** [comment]
> that is intended in keras 3, [src](https://github.com/keras-team/keras/issues/18823#issuecomment-1824865969).

Can the same usage (e.g., manually build sublayers instead of calling `super.build`) be applied to Keras 2?

**Comment by innat** [comment]
Yes, but not as much strict as of now.
