### ISSUE TITLE
(feat) Implement the deprecated `ctc_decode` function in Keras v3

### ISSUE THREAD

**Issue by lpizzinidev** [keras-team/keras#19227]
## What
Implement the deprecated [`ctc_decode`](https://github.com/keras-team/keras/blob/1137074a9a1c237473f2fe57ab277c697892c6f1/keras/legacy/backend.py#L715) function in [`keras.losses`](https://github.com/keras-team/keras/blob/master/keras/losses/losses.py) and make it backend-agnostic.

To achieve this we'll need to implement the following functions in [`keras.ops.nn`](https://github.com/keras-team/keras/blob/master/keras/ops/nn.py):
* [`tf.nn.ctc_greedy_decoder`](https://github.com/keras-team/keras/blob/1137074a9a1c237473f2fe57ab277c697892c6f1/keras/legacy/backend.py#L725)
* [`tf.compat.v1.nn.ctc_beam_search_decoder`](https://github.com/keras-team/keras/blob/1137074a9a1c237473f2fe57ab277c697892c6f1/keras/legacy/backend.py#L729)

After the implementation, update the related [`Automatic Speech Recognition using CTC`](https://keras.io/examples/audio/ctc_asr/) example on the [keras-io](https://github.com/keras-team/keras-io/blob/master/examples/audio/ctc_asr.py) repo and make it compatible with all backends, if possible.

## Results
* The `tf.nn.ctc_greedy_decoder` function is implemented in `keras.ops.nn` with related test coverage
* The `tf.compat.v1.nn.ctc_beam_search_decoder` function is implemented in `keras.ops.nn` with related test coverage
* The `ctc_decode` function is implemented in `keras.losses` with related test coverage
* The `Automatic Speech Recognition using CTC` example is updated with the new `ctc_decode` function and compatible with all backends

**Comment by divyashreepathihalli** [comment]
@lpizzinidev  are you interested in contributing a PR for this issue?

**Comment by lpizzinidev** [comment]
@divyashreepathihalli 
Sure 👍 
I'm working on a PR for migrating a `keras-io` example to v3. 
Once that's pushed I'll pick up this one ✅

**Comment by fchollet** [comment]
This is being implemented in https://github.com/keras-team/keras/pull/19366

**Comment by sachinprasadhs** [comment]
Closing the issue as it is already implemented in the above linked PR.
