### ISSUE TITLE
can't run keras-nlp quickstart?

### ISSUE THREAD

**Issue by rbelew** [keras-team/keras#19223]
i'm following the quickstart example here

https://keras.io/keras_nlp/

all the IMDB data and BERT model load, but then:

>   File ".../src/torch-kerasNLP.py", line 82, in main
>     classifier.fit(imdb_train, validation_data=imdb_test)
>   File .../lib/python3.11/site-packages/keras_nlp/src/utils/pipeline_model.py", line 201, in fit
>     return super().fit(
>            ^^^^^^^^^^^^
>   File ".../lib/python3.11/site-packages/keras/src/utils/traceback_utils.py", line 123, in error_handler
>     raise e.with_traceback(filtered_tb) from None
>   File ".../lib/python3.11/site-packages/keras/src/backend/torch/nn.py", line 564, in one_hot
>     output = tnn.one_hot(maximum(x, 0), num_classes)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> RuntimeError: Class values must be smaller than num_classes.

For reference:

>>> import torch
>>> import os
>>> os.environ["KERAS_BACKEND"] = "torch"
>>> import keras
>>> keras.__version__
'3.0.5'
>>> import tensorflow_text
>>> tensorflow_text.__version__
'2.15.0'
>>> import keras_nlp
>>> keras_nlp.__version__
'0.7.0'
>>> torch.__version__
'2.1.0.post100'
>>> import torchtext
>>> torchtext.__version__
'0.16.1'
>>> import tensorflow
>>> tensorflow.__version__
'2.15.0'

**Comment by rbelew** [comment]
I'm quite sure this has to do with `tfds.load()`also  downloading the **UNSUPERVISED** reviews, `.../tensorflow_datasets/imdb_reviews/plain_text/1.0.0/imdb_reviews-unsupervised.tfrecord-00000-of-00001` and this generating **THREE** classes

**Comment by sachinprasadhs** [comment]
I was able to run the example in the Nvidia_L4 GPU instance with the latest keras-nlp and keras package.
Below is the outcome of it.

 
![image](https://github.com/keras-team/keras/assets/73069040/fbc53e19-1671-4c49-9e1b-2e97198b0d19)
