### ISSUE TITLE
CompileMetrics.build should check y_pred.name instead of assigning None to output_names 

### ISSUE THREAD

**Issue by edwardyehuang** [keras-team/keras#19237]
`CompileMetrics.build`  should check `y_pred.name` instead of assigning None to `output_names`

https://github.com/keras-team/keras/blob/93ce335a942e92681568e37d7ea008bec6ebb947/keras/trainers/compile_utils.py#L178-L183

**Comment by divyashreepathihalli** [comment]
@edwardyehuang if `y_pred` is a dict/list/tuple like we are checking here, it will not have the name attribute.

**Comment by divyashreepathihalli** [comment]
@edwardyehuang can you help us understand what is your use case and when you might encounter a y_pred that has a name attribute?

**Comment by edwardyehuang** [comment]
I will go back to this issue later, currently I am handling some other issues in keras 3

**Comment by divyashreepathihalli** [comment]
There actually isn't a valid case where y_pred would have a name attribute. I will be closing this issue, if you do decide to get back please reopen the issue.
