### ISSUE TITLE
Bug in LayerNormalization when assigning axis to other than -1 while using a keras.utils.Sequence data generator

### ISSUE THREAD

**Issue by jrnjf** [keras-team/keras#19239]
when using a datagenerator (`keras.utils.Sequence` ) to fit your data. you cannot set the `LayerNormalization` axis to anything other that -1 
I have tested this on `BatchNormalization` and it produces the same error
so first here is my simple demo data generator
```python
class DataGenerator(keras.utils.Sequence):
    def __init__(self, X1,  y1, batch_size):
        self.X1 = X1
        self.y1 = y1
        self.batch_size = batch_size

    def __len__(self):
        
        return int(np.ceil(len(self.y1) / self.batch_size))

    def __getitem__(self, idx):
        batch_x1 = self.X1[idx * self.batch_size:(idx + 1) * self.batch_size]
        batch_y1 = self.y1[idx * self.batch_size:(idx + 1) * self.batch_size]
        
        return batch_x1 , batch_y1

```

and here is the demo model

```python
shape = (30,90,30,1)
input_shape = (90,30,1)

input = keras.layers.Input((90,30,1),name='input_a')

output = keras.layers.LayerNormalization(epsilon=1.3456e-8,axis=-2')(input)


mod = keras.Model(input,output)
data = np.random.random(shape)
y = np.random.random(shape)

dataset = DataGenerator(data,y,10)

mod.compile(keras.optimizers.Adam(0.001),'mse')
```
Now this is all fine if you set `axis` to -1 with `model.fit(dataset)` or if you set axis to `-2`,`-3` for `model.fit(data,y)` it will complete the training... 
but if you set `axis` to `-2` with `model.fit(dataset)` this is going to produce this error 

```bash
    File "C:\Users\moh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\keras\src\engine\training.py", line 1401, in train_function  *
        return step_function(self, iterator)
    File "C:\Users\moh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\keras\src\engine\training.py", line 1384, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\moh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\keras\src\engine\training.py", line 1373, in run_step  **
        outputs = model.train_step(data)
    File "C:\Users\moh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\keras\src\engine\training.py", line 1150, in train_step
        y_pred = self(x, training=True)
    File "C:\Users\moh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None

    TypeError: Exception encountered when calling layer 'layer_normalization' (type LayerNormalization).

    Failed to convert elements of [1, 1, None, 1] to Tensor. Consider casting elements to a supported type. See https://www.tensorflow.org/api_docs/python/tf/dtypes for supported TF dtypes.

    Call arguments received by layer 'layer_normalization' (type LayerNormalization):
      • inputs=tf.Tensor(shape=(None, None, None, None), dtype=float32)
```

I found a work around this 
# Reshape the input with its original shape!
This is not Ideal and if anyone reads my code he will think I am crazy but it seems to do the job
```python
shape = (30,90,30,1)
input_shape = (90,30,1)

input = keras.layers.Input((90,30,1),name='input_a')
reshape = keras.layers.Reshape(input_shape)(input)
output = keras.layers.LayerNormalization(epsilon=1.3456e-3,axis=-2)(input)


mod = keras.Model(input,output)
 ```

**Comment by sachinprasadhs** [comment]
I was able to run the code successfully by setting axis=-2 and -3 without any errors using Keras 3.

Here is the attached Gist [![](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.sandbox.google.com/gist/sachinprasadhs/4faacb53072a8689b7f920a967f821a0/19239.ipynb#scrollTo=uPbLQTxA7cDP)  and let me know if I'm missing something.

**Comment by jrnjf** [comment]
Yes! , it was a bit strange when I ran it on colab, then I realized we were working on different versions of keras. I ran the code on my local machine on keras==2.15.0 I think tensorflow requires that specific version-not sure- but you're welcome to correct me

anyway , I added one line to it and it produced the same error `!pip install keras==2.15.0`

**Comment by sachinprasadhs** [comment]
It is suggested to use `Keras 3`, from Tensorflow 2.16 it also uses Keras 3 as a backend, TensorFlow 2.16 will be released in a week or so.
I think we can close this issue.

**Comment by jrnjf** [comment]
No ,
This is a valid bug and needs fixing, you said tensorflow 2.16 will be released in a week or so , it’s been two weeks now
This is not

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sachinprasadhs** [comment]
@jrnjf , TensorFlow 2.16.1 is out few days back, could you please test it using the specified version and let us know the outcome. Thanks!
