### ISSUE TITLE
return of `compute_output_shape`

### ISSUE THREAD

**Issue by innat** [keras-team/keras#19259]
The `compute_output_shape` return is changed. Following sample code, works in Keras 2 but breaks in Keras 3. The thing is, in the following code, as stated there, what are the difference of those returns.

```python
class ReshapeLayer(keras.layers.Layer):
    def __init__(self, new_shape, **kwargs):
        super(ReshapeLayer, self).__init__(**kwargs)
        self.new_shape = new_shape
    def build(self, input_shape):
        super(ReshapeLayer, self).build(input_shape)
    def call(self, inputs):
        return tf.reshape(inputs, self.new_shape)
    def compute_output_shape(self, input_shape):
        # option 1 # works in keras 2 and 3.
        # return (input_shape[0],) + self.new_shape 

        # option 2 #  < ---- works in keras 2 but not 3
        return ( 
            input_shape[0],
            self.new_shape
        )
    
input_shape = (None, 10)  
new_shape = (5, 2)
model = keras.Sequential([
    keras.layers.Dense(20, input_shape=input_shape),
    ReshapeLayer(new_shape)
])
model.summary()
```

Also, In some official layers, for example [multi-head-layer](https://github.com/Pouyanpi/keras/blob/1d68a60bcf39a433186797f8ad6f25ecf72cc7ca/keras/layers/attention/multi_head_attention.py#L700-L707), or [conv3d layer](https://github.com/keras-team/keras/blob/c57dcf8bbe4ced27c65e0d3e8d4dd5c5242eaa42/keras/layers/convolutional/conv3d_transpose.py#L343-L344), and also from [docstring](https://github.com/keras-team/keras/pull/16955/files), the `tf.TensorShape` is used in `compute_output_shape` func. But doesn't it bring requirement to have tensorflow for other backends or any equivalent `keras.ops`?

**Comment by sampathweb** [comment]
Option 2 seems to return a Tuple of tuples instead of single value. So not sure if they are equivalent.

Also, the code references, you pointed to for `tf.TensorShape` don't exist in the main Keras Repo. It looks like its pointing to a forked repo that may not be updated. Can you check again?

**Comment by innat** [comment]
@sampathweb 
> Option 2 seems to return a Tuple of tuples instead of single value. So not sure if they are equivalent.

What I meant is their type (tuple). Regardless any approaches, option 2 used to work with keras 2. Now, in keras 3, I faced an issue with this approaches, specifically on `tf` and `jax` backend but successful on `torch` backend. Please, check [this workflow](https://github.com/keras-team/keras-cv/actions/runs/8169217490/job/22332837128).

```python
# with tensorflow

        if dtype not in ALLOWED_DTYPES:
>           raise ValueError(f"Invalid dtype: {dtype}")
E           ValueError: Exception encountered when calling VideoSwinBasicLayer.call().
E           
E           Invalid dtype: <property object at 0x7fe799453e00>
E           
E           Arguments received by VideoSwinBasicLayer.call():
E             • args=('<KerasTensor shape=(None, 4, 56, 56, 96), dtype=float32, sparse=False, name=keras_tensor_14086>',)
E             • kwargs=<class 'inspect._empty'>
```
```python
# with jax

        if dtype not in ALLOWED_DTYPES:
>           raise ValueError(f"Invalid dtype: {dtype}")
E           ValueError: Exception encountered when calling VideoSwinBasicLayer.call().
E           
E           Invalid dtype: ArrayImpl
E           
E           Arguments received by VideoSwinBasicLayer.call():
E             • args=('<KerasTensor shape=(None, 4, 56, 56, 96), dtype=float32, sparse=False, name=keras_tensor_14075>',)
E             • kwargs=<class 'inspect._empty'>
```

To address it, returning the ouput shape info wrapping around `tf.TensorShape` did work for all backend, [like this](https://github.com/keras-team/keras-cv/blob/aab1a6c9ff3cae1022372ee35415eabfcd8d82e6/keras_cv/layers/video_swin_layers.py#L714-L723). Not sure, if it's the ideal approach. 


> Also, the code references, you pointed to for tf.TensorShape don't exist in the main Keras Repo. It looks like its pointing to a forked repo that may not be updated. 

You're right, my bad. I should double check for muliti-head (forked) and conv3 (old keras master). But about [docstring](https://github.com/keras-team/keras/pull/16955/files), I think it's recent and stated about using `tf.TensorShape` and using that solves the above mentioned workflows.
