### ISSUE TITLE
bug on model splicing + Flatten

### ISSUE THREAD

**Issue by martin-gorner** [keras-team/keras#19270]
Repro Colab: https://colab.research.google.com/drive/18Fna4m_WDGr0lVjFeGlqOUX5Id2a_ljb

Repro step: uncomment line `#y = keras.layers.Flatten(y)` then run the Colab

Error message:
`ValueError: The `data_format` argument must be one of {'channels_first', 'channels_last'}. Received: data_format=<kerastensor shape=(none, none, none, 12), dtype=float32, sparse=false, name=keras_tensor_43>`

**Comment by SuryanarayanaY** [comment]
I have replicated the issue with inclusion of line `y = keras.layers.Flatten(y)`. Attaching [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/266999cfb25cf78547f9717dd09367aa/19270.ipynb) for reference.
Need to look into the issue.

**Comment by SuryanarayanaY** [comment]
Hi @martin-gorner ,

We missed this part. We need to call the flatten layer like this `y = keras.layers.Flatten()(y)`. What we have done actually we are passing the output tensor from Conv2d layer to the Flatten layer constructor and hence the error. Please refer modified [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/524ca6f220d0594b7cbf9be5e16cb4ad/19270_r1.ipynb).

Thanks!
