### ISSUE TITLE
CategoryEncoding is missing the sparse argument

### ISSUE THREAD

**Issue by bgweber2** [keras-team/keras#19285]
**System information.**
- Have I written custom code (as opposed to using a stock example script provided in Keras): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Databricks on GCP
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): pypi 2.14.0
- Python version: 3.9.5
- Bazel version (if compiling from source):
- GPU model and memory:
- Exact command to reproduce:

**Describe the problem.**
The Keras 2 API provides a sparse argument to the CategoryEncoding layer. This argument is missing in the Keras 3 API. 

**Describe the expected behavior.**
With Keras 2 API, I used variable length features as follows:
```
var_input = tf.keras.layers.Input(shape=(1), name="var_feature", dtype=tf.int64)
var_sparse = tf.keras.layers.CategoryEncoding(num_tokens=10000, output_mode="multi_hot", sparse=True)(var_input)
```

This results in the following output:
```
KerasTensor(type_spec=SparseTensorSpec(TensorShape([None, 10000]), tf.float32), description="created by layer 'category_encoding_1'")
```
The input data is TF Records, where `var_feature` is defined as `"var_feature": tf.io.VarLenFeature(tf.int64),`

**Describe the current behavior.**
I tried to get the same result with Keras 3 as follows:
```
var_input = tf.keras.layers.Input(shape=(1,), name="var_feature", dtype=tf.int64, sparse = True)
var_sparse = tf.keras.layers.CategoryEncoding(num_tokens=10000, output_mode="multi_hot")(var_input)
```

But the output is no longer sparse:
```
<KerasTensor shape=(None, 10000), dtype=float32, sparse=False, name=keras_tensor>
```

**Further Information**

[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md).

Do you want to contribute a PR? (yes/no): yes, if this argument is something that the team wants to support

**Comment by sachinprasadhs** [comment]
Thanks for reporting the issue.

I'm not sure why the `sparse` argument was dropped in Keras 3. 
Let's wait to hear it from the team. 

Keras 2 implementation: https://www.tensorflow.org/api_docs/python/tf/keras/layers/CategoryEncoding

**Comment by bgweber2** [comment]
Thanks @sachinprasadhs @hertschuh and @fchollet !
