### ISSUE TITLE
Custom loss and casting

### ISSUE THREAD

**Issue by shkarupa-alex** [keras-team/keras#19283]
I've got an issue during porting loss from keras v2 to v3.
The issue comes from here https://github.com/keras-team/keras/blob/master/keras/losses/loss.py#L39

In keras v2 loss wrapper does not change dtype of y_true and y_pred. But not in keras v3...
Is it possible to keep loss_fn arguments unchanged?

For example it may be required to do one_hot encoding of labels.
With keras v3 this requires to convert labels back to int

**Comment by mattdangerw** [comment]
Talked with the team, and I think this is basically expected in Keras 3.

The line you linked will cast to float, and https://github.com/keras-team/keras/blob/master/keras/backend/jax/nn.py#L449 is an example of where we cast back.

You could probably override `__call__` on a custom loss to avoid this behavior.
