### ISSUE TITLE
Scatter update variable in TF optimizer

### ISSUE THREAD

**Issue by shkarupa-alex** [keras-team/keras#19281]
In TensorFlow there is a cool (fast) variable update operation - scatter_update (like "assign" for dense variables).
It would be cool if you override assign operation for such cases (i think it should looks like https://github.com/keras-team/keras/blob/master/keras/backend/tensorflow/optimizer.py#L45 )

P.S.
Found such case during migration of Keras v2 custom optimizer.

**Comment by hertschuh** [comment]
@shkarupa-alex , thanks for the report. This was an omission. The fix is in `keras-nightly`, you can now just do `self.assign(variable, update)` within the optimizer.
