### ISSUE TITLE
New Keras optimizers are slower than legacy optimizers when using GPU

### ISSUE THREAD

**Issue by amaiya** [keras-team/keras#19307]
Reproducible example on Google Colab:  [link](https://colab.research.google.com/drive/1JslPZSYi-06y41Gy5u9Rd72lWOfpc-LH?usp=sharing)

- As shown in the Google Colab link above, the new Adam optimizer is significantly **slower** than the legacy version of Adam.
- The performance degradation seems to only happen when using a GPU (e.g., T4 on Google Colab).
- It happens on both `keras` and `tf.keras` (where legacy optimizers were replaced in TensorFlow 2.11).

**Comment by fchollet** [comment]
Thanks for the report. The times for the Keras 2.11-2.15 optimizer on T4 do indeed look alarmingly slow.

However, the latest version is Keras 3, not Keras 2.15. We are not making any further changes to Keras 2.

I tried with Keras 3 and I get 3ms/step on T4, which is 40% faster than the 5ms/step you got with the "fast" legacy optimizer. This is with the TF backend. Code: https://colab.research.google.com/drive/1TzbDAAeZ2W-dsUAbmdQUWDYilk_r8qpP#scrollTo=x1Fvw2QTfpot

Please update to Keras 3 and enjoy faster training times on GPU.

**Comment by amaiya** [comment]
Fantastic - thanks, @fchollet
