### ISSUE TITLE
`keras.ops.average_pool` API inconsistent across all backends.

### ISSUE THREAD

**Issue by ariG23498** [keras-team/keras#19301]
I see that the `keras.ops.average_pool` API is not consistent with all the backends.

I have tested the following code with TF, JAX, and Torch backends and reported in this attached [Colab Notebook](https://colab.research.google.com/gist/ariG23498/805d40e3ed2c5b961abf7d972323dbbf/scratchpad.ipynb)

```python
inputs = keras.ops.ones(shape=(32000, 14, 14, 256))
outputs = keras.ops.average_pool(inputs, pool_size=(1, 2, 2, 1), strides=(1, 2, 2, 1), padding='VALID')

print(inputs.shape)
print(outputs.shape)
```

**Comment by haifeng-jin** [comment]
Hi @ariG23498,
Thanks for the issue!
According to the documentation I attached below, `pool_size` and `strides` for a input of shape `(32000, 14, 14, 256)` should be tuples of two ints, like `pool_size=(1, 2), strides=(1, 2)`.
The `inputs_spatial_shape` for your inputs is `(14, 14)`.
The `inputs` should be of shape  `(batch_size,) + inputs_spatial_shape + (num_channels,)`.

```py
    """Average pooling operation.

    Args:
        inputs: Tensor of rank N+2. `inputs` has shape
            `(batch_size,) + inputs_spatial_shape + (num_channels,)` if
            `data_format="channels_last"`, or
            `(batch_size, num_channels) + inputs_spatial_shape` if
            `data_format="channels_first"`. Pooling happens over the spatial
            dimensions only.
        pool_size: int or tuple/list of integers of size
            `len(inputs_spatial_shape)`, specifying the size of the pooling
            window for each spatial dimension of the input tensor. If
            `pool_size` is int, then every spatial dimension shares the same
            `pool_size`.
```
