### ISSUE TITLE
Lambda.compute_output_shape generates wrong shape

### ISSUE THREAD

**Issue by AGFACBNNR** [keras-team/keras#19324]
When I use compute_output_shape() to help with shape inferencing, I found the Lambda layer may generate a wrong shape.
The code reproducing it:

```
from keras.layers import Lambda
import numpy as np
L=Lambda(lambda x:x**2, output_shape=[6])
x=np.zeros((3,2))
print(L(x).shape)
print(L.compute_output_shape(x.shape))
```

The results would be:
(3, 2)
(3, 6)

**Comment by nkovela1** [comment]
Hi @AGFACBNNR , since the output_shape was specified to 6, compute_output_shape will return that corresponding shape (3,6). Please try removing the output_shape argument from the Lambda layer. Thanks!

**Comment by sampathweb** [comment]
Hope this addresses this issue.  If you still think its open, please re-open it.
