### ISSUE TITLE
ValueError: Could not interpret metric identifier: loss

### ISSUE THREAD

**Issue by williamhunterwilson** [keras-team/keras#19334]
I am trying to implement a GridSearchCV over only a few hyperparameters but hit a block. I have spent so long combing over the Scikeras and tensorflow.keras compatibilities and just landed on using only Scikeras. There still seems to be some incompatibility issue and I don't know where.

```
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import tensorflow as tf
import keras
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import GridSearchCV
from scikeras.wrappers import KerasClassifier
from skopt import BayesSearchCV
from skopt.space import Real, Categorical, Integer

# ... (Your code for loading and merging DataFrames goes here) ...

# outcome_labels: Array of win/loss/draw results
outcome_labels_a = pd.read_csv('a_form.csv').T
outcome_labels_b = pd.read_csv('b_form.csv').T

# Assuming you have:
# team_a_data: DataFrame for Team A
# team_b_data: DataFrame for Team B
df_a_disposals = pd.read_csv('a_disposals.csv').T
df_a_disposals = df_a_disposals.drop(index = 'Player')
df_a_kicks = pd.read_csv('a_kicks.csv').T
df_a_kicks = df_a_kicks.drop(index = 'Player')
df_a_tackles = pd.read_csv('a_tackles.csv').T
df_a_tackles = df_a_tackles.drop(index = 'Player')
df_a_pplayed = pd.read_csv('a_pplayed.csv').T
df_a_pplayed = df_a_pplayed.drop(index = 'Player')

df_b_disposals = pd.read_csv('b_disposals.csv').T
df_b_disposals = df_b_disposals.drop(index = 'Player')
df_b_kicks = pd.read_csv('b_kicks.csv').T
df_b_kicks = df_b_kicks.drop(index = 'Player')
df_b_tackles = pd.read_csv('b_tackles.csv').T
df_b_tackles = df_b_tackles.drop(index = 'Player')
df_b_pplayed = pd.read_csv('b_pplayed.csv').T
df_b_pplayed = df_b_pplayed.drop(index = 'Player')

# Concatenate dataframes
team_a_data = pd.concat([df_a_disposals, df_a_kicks, df_a_tackles, df_a_pplayed], axis = 1)
team_b_data = pd.concat([df_b_disposals, df_b_kicks, df_b_tackles, df_b_pplayed], axis = 1)
print(team_a_data.shape)
print(team_b_data.shape)
# Combine player data for both teams
combined_data = pd.concat([team_a_data, team_b_data], axis=0)

# Merge with outcomes data
team_a_merged = pd.merge(team_a_data, outcome_labels_a, left_index = True, right_index = True)
team_b_merged = pd.merge(team_b_data, outcome_labels_b, left_index = True, right_index = True)
merged_data = pd.concat([team_a_merged, team_b_merged], axis=0)
print(team_b_merged.head())

x = merged_data.drop(columns = ['0_y'])
y = merged_data['0_y']

# Splitting initial 70%
x_train, x_remaining, y_train, y_remaining = train_test_split(x, y, test_size=0.3, random_state=42) # Splitting initial 70%
# Further split remaining 30%
x_val, x_test, y_val, y_test = train_test_split(x_remaining, y_remaining, test_size=0.5, random_state=42)

# Create the model (simplifying for illustration)
def create_model(hidden_layer_dim=32, loss='binary_crossentropy', optimizer='adam', learning_rate=0.01):
    model = Sequential([
        Dense(units=32, activation='relu', input_shape=(x_train.shape[1],)), # Adjust 'units' for hidden layer size
        Dense(units=16, activation='relu'), 
        Dense(units=1, activation='sigmoid') 
    ])
    model.compile(optimizer=keras.optimizers.Adam(learning_rate=learning_rate), 
                  loss='binary_crossentropy', 
                  metrics=['accuracy'])
    
    return model

# Parameter grid
param_grid = {
    "hidden_layer_dim": [50, 100, 200],
    "loss": ["binary_crossentropy"],
    "optimizer": ["adam", "sgd"],
    "optimizer__learning_rate": [0.0001, 0.001, 0.1],
}

model = KerasClassifier(model = create_model, hidden_layer_dim=50, epochs=20, batch_size=32)

# Create a GridSearchCV object
grid = GridSearchCV(estimator=model, param_grid=param_grid, cv=3, scoring = 'accuracy')  # Consider cross-validation 

# Fit the grid search to your training data
grid_result = grid.fit(x_train, y_train)

# Best model
print(grid_result.best_params_, grid_result.best_score_)
```

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[54], [line 28](vscode-notebook-cell:?execution_count=54&line=28)
     [25](vscode-notebook-cell:?execution_count=54&line=25) grid = GridSearchCV(estimator=model, param_grid=param_grid, cv=3, scoring = 'accuracy')  # Consider cross-validation 
     [27](vscode-notebook-cell:?execution_count=54&line=27) # Fit the grid search to your training data
---> [28](vscode-notebook-cell:?execution_count=54&line=28) grid_result = grid.fit(x_train, y_train)
     [30](vscode-notebook-cell:?execution_count=54&line=30) # Best model
     [31](vscode-notebook-cell:?execution_count=54&line=31) print(grid_result.best_params_, grid_result.best_score_)

File [c:\Users\will_\Code\.venv\lib\site-packages\sklearn\base.py:1474](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/base.py:1474), in _fit_context.<locals>.decorator.<locals>.wrapper(estimator, *args, **kwargs)
   [1467](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/base.py:1467)     estimator._validate_params()
   [1469](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/base.py:1469) with config_context(
   [1470](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/base.py:1470)     skip_parameter_validation=(
   [1471](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/base.py:1471)         prefer_skip_nested_validation or global_skip_validation
   [1472](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/base.py:1472)     )
   [1473](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/base.py:1473) ):
-> [1474](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/base.py:1474)     return fit_method(estimator, *args, **kwargs)

File [c:\Users\will_\Code\.venv\lib\site-packages\sklearn\model_selection\_search.py:970](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/model_selection/_search.py:970), in BaseSearchCV.fit(self, X, y, **params)
    [964](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/model_selection/_search.py:964)     results = self._format_results(
    [965](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/model_selection/_search.py:965)         all_candidate_params, n_splits, all_out, all_more_results
    [966](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/model_selection/_search.py:966)     )
    [968](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/model_selection/_search.py:968)     return results
--> [970](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/model_selection/_search.py:970) self._run_search(evaluate_candidates)
    [972](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/model_selection/_search.py:972) # multimetric is determined here because in the case of a callable
    [973](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/model_selection/_search.py:973) # self.scoring the return type is only known after calling
    [974](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/model_selection/_search.py:974) first_test_score = all_out[0]["test_scores"]

File [c:\Users\will_\Code\.venv\lib\site-packages\sklearn\model_selection\_search.py:1527](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/model_selection/_search.py:1527), in GridSearchCV._run_search(self, evaluate_candidates)
   [1525](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/model_selection/_search.py:1525) def _run_search(self, evaluate_candidates):
   [1526](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/model_selection/_search.py:1526)     """Search all candidates in param_grid"""
-> [1527](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/model_selection/_search.py:1527)     evaluate_candidates(ParameterGrid(self.param_grid))

File [c:\Users\will_\Code\.venv\lib\site-packages\sklearn\model_selection\_search.py:947](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/model_selection/_search.py:947), in BaseSearchCV.fit.<locals>.evaluate_candidates(candidate_params, cv, more_results)
    [940](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/model_selection/_search.py:940) elif len(out) != n_candidates * n_splits:
    [941](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/model_selection/_search.py:941)     raise ValueError(
    [942](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/model_selection/_search.py:942)         "cv.split and cv.get_n_splits returned "
    [943](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/model_selection/_search.py:943)         "inconsistent results. Expected {} "
    [944](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/model_selection/_search.py:944)         "splits, got {}".format(n_splits, len(out) // n_candidates)
    [945](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/model_selection/_search.py:945)     )
--> [947](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/model_selection/_search.py:947) _warn_or_raise_about_fit_failures(out, self.error_score)
    [949](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/model_selection/_search.py:949) # For callable self.scoring, the return type is only know after
    [950](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/model_selection/_search.py:950) # calling. If the return type is a dictionary, the error scores
    [951](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/model_selection/_search.py:951) # can now be inserted with the correct key. The type checking
    [952](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/model_selection/_search.py:952) # of out will be done in `_insert_error_scores`.
    [953](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/model_selection/_search.py:953) if callable(self.scoring):

File [c:\Users\will_\Code\.venv\lib\site-packages\sklearn\model_selection\_validation.py:536](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/model_selection/_validation.py:536), in _warn_or_raise_about_fit_failures(results, error_score)
    [529](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/model_selection/_validation.py:529) if num_failed_fits == num_fits:
    [530](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/model_selection/_validation.py:530)     all_fits_failed_message = (
    [531](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/model_selection/_validation.py:531)         f"\nAll the {num_fits} fits failed.\n"
    [532](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/model_selection/_validation.py:532)         "It is very likely that your model is misconfigured.\n"
    [533](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/model_selection/_validation.py:533)         "You can try to debug the error by setting error_score='raise'.\n\n"
    [534](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/model_selection/_validation.py:534)         f"Below are more details about the failures:\n{fit_errors_summary}"
    [535](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/model_selection/_validation.py:535)     )
--> [536](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/model_selection/_validation.py:536)     raise ValueError(all_fits_failed_message)
    [538](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/model_selection/_validation.py:538) else:
    [539](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/model_selection/_validation.py:539)     some_fits_failed_message = (
    [540](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/model_selection/_validation.py:540)         f"\n{num_failed_fits} fits failed out of a total of {num_fits}.\n"
    [541](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/model_selection/_validation.py:541)         "The score on these train-test partitions for these parameters"
   (...)
    [545](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/model_selection/_validation.py:545)         f"Below are more details about the failures:\n{fit_errors_summary}"
    [546](file:///C:/Users/will_/Code/.venv/lib/site-packages/sklearn/model_selection/_validation.py:546)     )

ValueError: 
All the 54 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
54 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\will_\Code\.venv\lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\will_\Code\.venv\lib\site-packages\scikeras\wrappers.py", line 1491, in fit
    super().fit(X=X, y=y, sample_weight=sample_weight, **kwargs)
  File "c:\Users\will_\Code\.venv\lib\site-packages\scikeras\wrappers.py", line 760, in fit
    self._fit(
  File "c:\Users\will_\Code\.venv\lib\site-packages\scikeras\wrappers.py", line 928, in _fit
    self._fit_keras_model(
  File "c:\Users\will_\Code\.venv\lib\site-packages\scikeras\wrappers.py", line 536, in _fit_keras_model
    raise e
  File "c:\Users\will_\Code\.venv\lib\site-packages\scikeras\wrappers.py", line 531, in _fit_keras_model
    key = metric_name(key)
  File "c:\Users\will_\Code\.venv\lib\site-packages\scikeras\utils\__init__.py", line 111, in metric_name
    fn_or_cls = keras_metric_get(metric)
  File "c:\Users\will_\Code\.venv\lib\site-packages\keras\src\metrics\__init__.py", line 204, in get
ValueError: Could not interpret metric identifier: loss
```

**Comment by rashika-dabas** [comment]
Same error on my side as well

**Comment by SuryanarayanaY** [comment]
Hi @williamhunterwilson ,

It seems the source of error is from below piece of code from your error stack which is from scikeras.

```
  File "c:\Users\will_\Code\.venv\lib\site-packages\scikeras\utils\__init__.py", line 111, in metric_name
    fn_or_cls = keras_metric_get(metric)
```

Here  `scikeras` seems passing the string `'loss' `to the argument `metric` in the above function `keras_metric_get(metric)` instead of a metric name that Keras accepts.

**Comment by xahram** [comment]
Use the tensorflow==2.14.1. I was using the version as mentioned, it was working perfectly. Today, I ported my project to ec2 and tried to run the notebook. Ended up getting the error. I believe TensorFlow have released new version 2.16. So it might not be compatible yet with libraries like SciKeras.

**Comment by williamhunterwilson** [comment]
> Use the tensorflow==2.14.1. I was using the version as mentioned, it was working perfectly. Today, I ported my project to ec2 and tried to run the notebook. Ended up getting the error. I believe TensorFlow have released new version 2.16. So it might not be compatible yet with libraries like SciKeras.

I tried uninstalling tensorflow and reinstalling version 2.14.1 as you tried but still got the error. I don't think the error is with tensorflow as I don't actually use it anywhere, I just imported it for good measure. Maybe it is a compatibility issue with keras and scikeras??

**Comment by xahram** [comment]
Can you check your Keras version? I'm using TensorFlow's Keras API, and the Keras version installed with it is 2.14. 

So my working project has 
Keras : 2.14.0
SciKeras: 0.12

**Comment by williamhunterwilson** [comment]
![Screenshot 2024-03-25 113516](https://github.com/keras-team/keras/assets/42662130/c4824e9c-c5e0-4237-8b6c-0d9a72d12769)

**Comment by williamhunterwilson** [comment]
> Can you check your Keras version? I'm using TensorFlow's Keras API, and the Keras version installed with it is 2.14.
> 
> So my working project has Keras : 2.14.0 SciKeras: 0.12

I reinstalled the versions you used but still got the error that all my fits failed.

![Uploading Screenshot 2024-03-25 113516.png…]()

But the models were still tested???
![Screenshot 2024-03-25 113928](https://github.com/keras-team/keras/assets/42662130/782caea6-edb1-4fc2-bb83-c02a7dddfe06)

**Comment by matteotoma98** [comment]
> > Can you check your Keras version? I'm using TensorFlow's Keras API, and the Keras version installed with it is 2.14.
> > So my working project has Keras : 2.14.0 SciKeras: 0.12
> 
> I reinstalled the versions you used but still got the error that all my fits failed.
> 
> ![Screenshot 2024-03-25 113516](https://private-user-images.githubusercontent.com/42662130/316356177-665f68ee-71bd-42f7-90ed-43fac3f7a423.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNzIzNTMsIm5iZiI6MTcxMTM3MjA1MywicGF0aCI6Ii80MjY2MjEzMC8zMTYzNTYxNzctNjY1ZjY4ZWUtNzFiZC00MmY3LTkwZWQtNDNmYWMzZjdhNDIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDEzMDczM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliMjZkYzdkNDEwZjlkYmE4MzJlZWYyNjljYzVmNmY0ZWVmNDU3ZmM4YzJkYzJhMzU1YjI3MzE2MzVkZTcyMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4L-QuWLRV75k--p-3aSGJZC6_58WkDop7PpAOhZ21OY)
> 
> But the models were still tested??? ![Screenshot 2024-03-25 113928](https://private-user-images.githubusercontent.com/42662130/316356081-782caea6-edb1-4fc2-bb83-c02a7dddfe06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNzIzNTMsIm5iZiI6MTcxMTM3MjA1MywicGF0aCI6Ii80MjY2MjEzMC8zMTYzNTYwODEtNzgyY2FlYTYtZWRiMS00ZmMyLWJiODMtYzAyYTdkZGRmZTA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDEzMDczM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxODljZDFhYmY1YmM1NTFjMDU5ODZhZWY4OWIxODViMTM4NzY1ZjRkNDU1YjM2ZTY2MGRmYzE1OTM2NTNhM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IBqY-WEn5aQY_X6n61GFEdDwewWCijIaqP714pkHVpE)
> 
> Please don't mind the horrible accuracy and loss values, it's all just test values 😅


I have this code
!pip install sklearn-deap
!pip install tpot
%pip install scikeras
%pip install keras
%pip install --upgrade pip
# Anything above 2.10 is not supported on the GPU on Windows Native
%pip install "tensorflow<2.11"


and i solved the error 'ValueError: Could not interpret metric identifier: loss'
with the last line. (%pip install "tensorflow<2.11")

**Comment by n1neteen-hundred** [comment]
> > > Can you check your Keras version? I'm using TensorFlow's Keras API, and the Keras version installed with it is 2.14.
> > > So my working project has Keras : 2.14.0 SciKeras: 0.12
> > 
> > 
> > I reinstalled the versions you used but still got the error that all my fits failed.
> > ![Screenshot 2024-03-25 113516](https://private-user-images.githubusercontent.com/42662130/316356177-665f68ee-71bd-42f7-90ed-43fac3f7a423.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNzIzNTMsIm5iZiI6MTcxMTM3MjA1MywicGF0aCI6Ii80MjY2MjEzMC8zMTYzNTYxNzctNjY1ZjY4ZWUtNzFiZC00MmY3LTkwZWQtNDNmYWMzZjdhNDIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDEzMDczM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliMjZkYzdkNDEwZjlkYmE4MzJlZWYyNjljYzVmNmY0ZWVmNDU3ZmM4YzJkYzJhMzU1YjI3MzE2MzVkZTcyMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4L-QuWLRV75k--p-3aSGJZC6_58WkDop7PpAOhZ21OY)
> > But the models were still tested??? ![Screenshot 2024-03-25 113928](https://private-user-images.githubusercontent.com/42662130/316356081-782caea6-edb1-4fc2-bb83-c02a7dddfe06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNzIzNTMsIm5iZiI6MTcxMTM3MjA1MywicGF0aCI6Ii80MjY2MjEzMC8zMTYzNTYwODEtNzgyY2FlYTYtZWRiMS00ZmMyLWJiODMtYzAyYTdkZGRmZTA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDEzMDczM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxODljZDFhYmY1YmM1NTFjMDU5ODZhZWY4OWIxODViMTM4NzY1ZjRkNDU1YjM2ZTY2MGRmYzE1OTM2NTNhM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IBqY-WEn5aQY_X6n61GFEdDwewWCijIaqP714pkHVpE)
> > Please don't mind the horrible accuracy and loss values, it's all just test values 😅
> 
> I have this code !pip install sklearn-deap !pip install tpot %pip install scikeras %pip install keras %pip install --upgrade pip
> 
> # Anything above 2.10 is not supported on the GPU on Windows Native
> %pip install "tensorflow<2.11"
> 
> and i solved the error 'ValueError: Could not interpret metric identifier: loss' with the last line. (%pip install "tensorflow<2.11")

That's correct ths mate

**Comment by williamhunterwilson** [comment]
> import pandas as pd
> import numpy as np
> from sklearn.model_selection import train_test_split
> import tensorflow as tf
> import keras
> from keras.models import Sequential
> from keras.layers import Dense
> from sklearn.model_selection import GridSearchCV
> from scikeras.wrappers import KerasClassifier
> from skopt import BayesSearchCV
> from skopt.space import Real, Categorical, Integer

This worked! I had to play around with my environments and play around with the order of the installs but YES
Thank you!!

**Comment by SuryanarayanaY** [comment]
Hi @williamhunterwilson ,

Could you please confirm whether you have tested with Older TF and whether it works . Please confirm this is issue with keras3 and submit a repro code for same.

Thanks!

**Comment by SuryanarayanaY** [comment]
This seems not an issue with keras3. If other libraries using Keras make sure the version it is used and install the same.

**Comment by williamhunterwilson** [comment]
> Hi @williamhunterwilson ,
> 
> Could you please confirm whether you have tested with Older TF and whether it works . Please confirm this is issue with keras3 and submit a repro code for same.
> 
> Thanks!

I think the issue may be with Scikeras and the newer versions of TF

I have tested with:
Keras 2.10.0
Tensorflow 2.10.1
Scikeras 0.12.0

I used to test in a jupyter notebook with these csv files:

[a_disposals.csv](https://github.com/keras-team/keras/files/14879868/a_disposals.csv)
[a_form.csv](https://github.com/keras-team/keras/files/14879870/a_form.csv)
[a_kicks.csv](https://github.com/keras-team/keras/files/14879871/a_kicks.csv)
[a_pplayed.csv](https://github.com/keras-team/keras/files/14879872/a_pplayed.csv)
[a_tackles.csv](https://github.com/keras-team/keras/files/14879873/a_tackles.csv)
[b_disposals.csv](https://github.com/keras-team/keras/files/14879874/b_disposals.csv)
[b_form.csv](https://github.com/keras-team/keras/files/14879875/b_form.csv)
[b_kicks.csv](https://github.com/keras-team/keras/files/14879876/b_kicks.csv)
[b_pplayed.csv](https://github.com/keras-team/keras/files/14879877/b_pplayed.csv)
[b_tackles.csv](https://github.com/keras-team/keras/files/14879878/b_tackles.csv)

**CODE**
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import tensorflow as tf
import keras
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import GridSearchCV
from scikeras.wrappers import KerasClassifier
from skopt import BayesSearchCV
from skopt.space import Real, Categorical, Integer

outcome_labels_a = pd.read_csv('a_form.csv').T
outcome_labels_b = pd.read_csv('b_form.csv').T

# Assuming you have:
# team_a_data: DataFrame for Team A
# team_b_data: DataFrame for Team B
df_a_disposals = pd.read_csv('a_disposals.csv').T
df_a_disposals = df_a_disposals.drop(index = 'Player')
df_a_kicks = pd.read_csv('a_kicks.csv').T
df_a_kicks = df_a_kicks.drop(index = 'Player')
df_a_tackles = pd.read_csv('a_tackles.csv').T
df_a_tackles = df_a_tackles.drop(index = 'Player')
df_a_pplayed = pd.read_csv('a_pplayed.csv').T
df_a_pplayed = df_a_pplayed.drop(index = 'Player')

df_b_disposals = pd.read_csv('b_disposals.csv').T
df_b_disposals = df_b_disposals.drop(index = 'Player')
df_b_kicks = pd.read_csv('b_kicks.csv').T
df_b_kicks = df_b_kicks.drop(index = 'Player')
df_b_tackles = pd.read_csv('b_tackles.csv').T
df_b_tackles = df_b_tackles.drop(index = 'Player')
df_b_pplayed = pd.read_csv('b_pplayed.csv').T
df_b_pplayed = df_b_pplayed.drop(index = 'Player')

# Concatenate dataframes
team_a_data = pd.concat([df_a_disposals, df_a_kicks, df_a_tackles, df_a_pplayed], axis = 1)
team_b_data = pd.concat([df_b_disposals, df_b_kicks, df_b_tackles, df_b_pplayed], axis = 1)
# Combine player data for both teams
combined_data = pd.concat([team_a_data, team_b_data], axis=0)

# Merge with outcomes data
team_a_merged = pd.merge(team_a_data, outcome_labels_a, left_index = True, right_index = True)
team_b_merged = pd.merge(team_b_data, outcome_labels_b, left_index = True, right_index = True)
merged_data = pd.concat([team_a_merged, team_b_merged], axis=0)

x = merged_data.drop(columns = ['0_y'])
y = merged_data['0_y']

# Splitting initial 70%
x_train, x_remaining, y_train, y_remaining = train_test_split(x, y, test_size=0.3, random_state=42) # Splitting initial 70%
# Further split remaining 30%
x_val, x_test, y_val, y_test = train_test_split(x_remaining, y_remaining, test_size=0.5, random_state=42)

# Create the model (simplifying for illustration)
def create_model(hidden_layer_dim=32, loss='binary_crossentropy', optimizer='adam', learning_rate=0.01):
    model = Sequential([
        Dense(units=32, activation='relu', input_shape=(x_train.shape[1],)), # Adjust 'units' for hidden layer size
        Dense(units=16, activation='relu'), 
        Dense(units=1, activation='sigmoid') 
    ])
    model.compile(optimizer=keras.optimizers.Adam(learning_rate=learning_rate), 
                  loss='binary_crossentropy', 
                  metrics=['accuracy'])
    
    return model

# Parameter grid
param_grid = {
    "hidden_layer_dim": [50, 100, 200],
    "loss": ["binary_crossentropy"],
    "optimizer": ["adam", "sgd"],
    "optimizer__learning_rate": [0.0001, 0.001, 0.1],
}

model = KerasClassifier(model = create_model, hidden_layer_dim=50, epochs=20, batch_size=32)

# Create a GridSearchCV object
grid = GridSearchCV(estimator=model, param_grid=param_grid, cv=3, scoring = 'accuracy')  # Consider cross-validation 

# Fit the grid search to your training data
grid_result = grid.fit(x_train, y_train)

# Best model
print(grid_result.best_params_, grid_result.best_score_)

**OUTPUT:**
{'hidden_layer_dim': 200, 'loss': 'binary_crossentropy', 'optimizer': 'sgd', 'optimizer__learning_rate': 0.001} 0.6606060606060606

**Comment by SuryanarayanaY** [comment]
Hi @williamhunterwilson ,

If Sci_keras is using Keras internally then it has to be made compatible with new version. IMHO this needs to be addressed at `sci_keras` . I am not sure what is the latest TF/Keras version it was tested.

Keras3 is made compatible for tensorflow ,torch and jax libraries as backend. We can't address compatibilities with other libraries since `sci_keras` is not a dependency for Keras.

Can you test the model with Keras as standalone package with any of the above 3 backends and still having issue then please comeback with the report.

Thanks!
