### ISSUE TITLE
unable to load model what should i do

### ISSUE THREAD

**Issue by jayashri17092002** [keras-team/keras#19330]
Traceback (most recent call last):
  File "C:\Users\jayas\APT_Detection\application.py", line 182, in <module>
    ae_model = load_model(r'C:\Users\jayas\APT_Detection\models\autoencoder_39ft.hdf5')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jayas\APT_Detection\venv\Lib\site-packages\keras\src\saving\saving_api.py", line 183, in load_model
    return legacy_h5_format.load_model_from_hdf5(filepath)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jayas\APT_Detection\venv\Lib\site-packages\keras\src\legacy\saving\legacy_h5_format.py", line 155, in load_model_from_hdf5
    **saving_utils.compile_args_from_training_config(
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jayas\APT_Detection\venv\Lib\site-packages\keras\src\legacy\saving\saving_utils.py", line 143, in compile_args_from_training_config
    loss = _deserialize_nested_config(losses.deserialize, loss_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jayas\APT_Detection\venv\Lib\site-packages\keras\src\legacy\saving\saving_utils.py", line 202, in _deserialize_nested_config
    return deserialize_fn(config)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jayas\APT_Detection\venv\Lib\site-packages\keras\src\losses\__init__.py", line 124, in deserialize
    return serialization_lib.deserialize_keras_object(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jayas\APT_Detection\venv\Lib\site-packages\keras\src\saving\serialization_lib.py", line 570, in deserialize_keras_object
    return deserialize_keras_object(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jayas\APT_Detection\venv\Lib\site-packages\keras\src\saving\serialization_lib.py", line 671, in deserialize_keras_object
    return _retrieve_class_or_fn(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jayas\APT_Detection\venv\Lib\site-packages\keras\src\saving\serialization_lib.py", line 805, in _retrieve_class_or_fn
    raise TypeError(
TypeError: Could not locate function 'mse'. Make sure custom classes are decorated with `@keras.saving.register_keras_serializable()`. Full object config: {'module': 'keras.metrics', 'class_name': 'function', 'config': 'mse', 'registered_name': 'mse'}

**Comment by SuryanarayanaY** [comment]
Hi @jayashri17092002 ,

From the error log it seems you have a custom loss function `'mse'` which is not serialized. Custom loss functions or classes have to be serialized explicitly by registering  the class/function with `@keras.saving.register_keras_serializable()` decorator. For custom classes you might need additional work to implement `get_config` and/or `from_config` methods explicitly.

Please refer to the attached [guide](https://keras.io/guides/serialization_and_saving/) for more details on custom objects.

**Comment by jayashri17092002** [comment]
Thank you for the clarification.

**Comment by SuryanarayanaY** [comment]
Hi @jayashri17092002 ,

COuld we mark this issue as resolved ? Please feel free to close the issue if your issue resolved. Thanks!

**Comment by mauricio-repetto** [comment]
Hi @jayashri17092002, I faced the same issue with 'mae' metric while I was loading a model (.h5) saved with an older version of keras. Looking at the issue I noticed that the custom_objects parameter wasn't being passed when using the `load_model_from_hdf5` function to load the model under the hood and thus causing the mentioned exception. What worked for me was the following:

```
from keras.src.legacy.saving import legacy_h5_format

model = legacy_h5_format.load_model_from_hdf5("path to model", custom_objects={'mae': 'mae'})
```

This is only useful if you just want to use the model only for inference like it was my case.

**Comment by mindspark7** [comment]
How to solve this problem
TypeError: Could not locate function 'mse'. Make sure custom classes are decorated with `@keras.saving.register_keras_serializable()`. Full object config: {'module': 'keras.metrics', 'class_name': 'function', 'config': 'mse', 'registered_name': 'mse'}

**Comment by mindspark7** [comment]
keras.models problem

**Comment by mauricio-repetto** [comment]
@mindspark7 did you check my previous message? if you are loading it just to use the model, that will solve your issue, if you need to keep retraining it, then you don't have other option than recreate it and serializing it properly as it's commented in earlier comments.

**Comment by mindspark7** [comment]
How to solve this keras.model problem please help me by providing any code
or suggestions pleass help me

**Comment by Bleo2018** [comment]
@mauricio-repetto
I got the same error and your solution solved my problem. Thank you very much!

**Comment by msshojaei90** [comment]
> Hi @jayashri17092002, I faced the same issue with 'mae' metric while I was loading a model (.h5) saved with an older version of keras. Looking at the issue I noticed that the custom_objects parameter wasn't being passed when using the `load_model_from_hdf5` function to load the model under the hood and thus causing the mentioned exception. What worked for me was the following:
> 
> ```
> from keras.src.legacy.saving import legacy_h5_format
> 
> model = legacy_h5_format.load_model_from_hdf5("path to model", custom_objects={'mae': 'mae'})
> ```
> 
> This is useful if you just want to use the model only for inference like it was my case.

This does not work for me and I have still the same error. Do you have any other suggestion?

**Comment by mauricio-repetto** [comment]
is the error message the same @msshojaei90? and also are you trying to use this model just for inference? if that's the case I'm out of ideas..
