### ISSUE TITLE
tf.data dataset becomes float32 after applying FeatureSpace even though dataset is float64 and default keras precision is set to float64

### ISSUE THREAD

**Issue by sibyjackgrove** [keras-team/keras#19345]
I created a `FeatureSpace `definition and am applying it to my tf.data dataset using map:
`dataset = dataset.map(feature_space)
`
The dataset contains `float64 `elements. However, after the feature space is applied the dataset elements are converted to `float32`. I set the default precision to float64 using `keras.config.set_floatx("float64")`. But still the dataset is converted to `float32 `after the featurespace is applied.

**Comment by sachinprasadhs** [comment]
Hi, Could you please provide some sample reproducible code to investigate on the reported behavior. Thanks

**Comment by sibyjackgrove** [comment]
Please find below:

```
import keras

keras.config.set_floatx("float64")
feature1_data = [1, 2, 3, 4, 5,6]
feature2_data = [10, 20, 30, 40, 50,60]

dataset = tf.data.Dataset.from_tensor_slices({
    'feature1': feature1_data,
    'feature2': feature2_data
})
feature_space_definitions = {}
feature_space_definitions.update({"feature1":keras.utils.FeatureSpace.float(),"feature2":keras.utils.FeatureSpace.float()})
feature_space = keras.utils.FeatureSpace(features=feature_space_definitions,output_mode="dict")
feature_space.adapt(dataset.take(5)
dataset = dataset.map(feature_space)
print(dataset.element_spec)
```

**Comment by sachinprasadhs** [comment]
Thanks for your input, the output datatype is basically coming from `tf.data` where `Keras` does not have any control on it to modify.

`tf.data.Dataset.from_tensor_slices` will produce the type based on the user provided input or type of values in `feature1_data` which gets converted based on the logic here https://github.com/tensorflow/tensorflow/blob/5bc9d26649cca274750ad3625bd93422617eed4b/tensorflow/python/framework/tensor_conversion_registry.py#L164

This is not a bug, you can close this issue. Thanks!

**Comment by sibyjackgrove** [comment]
Thanks for the clarification. So to fix this, I need to make sure the tf.data element is float64?

**Comment by sachinprasadhs** [comment]
> Thanks for the clarification. So to fix this, I need to make sure the tf.data element is float64?

Correct.
