### ISSUE TITLE
Input 0 of layer "dense_2" is incompatible with the layer: expected axis -1 of input shape to have value 16384, but received input with shape (None, 65536)

### ISSUE THREAD

**Issue by coder-monishr** [keras-team/keras#19367]
Hey there!! This is the issue I get 

ValueError: Exception encountered when calling Sequential.call().

Input 0 of layer "dense_2" is incompatible with the layer: expected axis -1 of input shape to have value 16384, but received input with shape (None, 65536)

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=(None, 256, 256, 3), dtype=float32)
  • training=True
  • mask=None

code is here!
`history = model.fit(x=training_set,validation_data=validation_set, epochs=10)`

**Comment by coder-monishr** [comment]
@sachinprasadhs help me out

**Comment by sachinprasadhs** [comment]
Could you please provide reproducible code in a colab Gist to understand more on the issue. Thanks!

**Comment by coder-monishr** [comment]
@sachinprasadhs yeaa 

https://colab.research.google.com/drive/1QyLNRMwOhuMpZ_4_eJ5m3pKh2Np_wG7g?usp=sharing

**Comment by sachinprasadhs** [comment]
You are restricting the `input_shape` for each convolution operation to be `128,128,3`, which does not fit to the actual data size which you are passing which is `256,256,3`,  replacing your code with below code should work.

```python
from keras.layers import Dense, Conv2D, MaxPool2D, Flatten
from keras.models import Sequential

model = Sequential()

model.add(Conv2D(filters=32, kernel_size=3, padding="same", activation="relu",input_shape=[256,256,3]))
model.add(Conv2D(filters=32, kernel_size=3, padding="same", activation="relu"))
model.add(MaxPool2D(pool_size=2,strides=2))

model.add(Conv2D(filters=64, kernel_size=3, padding="same", activation="relu"))
model.add(Conv2D(filters=64, kernel_size=3, padding="same", activation="relu"))
model.add(MaxPool2D(pool_size=2,strides=2))


model.add(Conv2D(filters=128, kernel_size=3, padding="same", activation="relu"))
model.add(Conv2D(filters=128, kernel_size=3, padding="same", activation="relu"))
model.add(MaxPool2D(pool_size=2,strides=2))

model.add(Conv2D(filters=256, kernel_size=3, padding="same", activation="relu"))
model.add(Conv2D(filters=256, kernel_size=3, padding="same", activation="relu"))
model.add(MaxPool2D(pool_size=2,strides=2))

model.add(Flatten())

model.add(Dense(units = 1024, activation="relu"))

model.add(Dense(units = 1024, activation="relu"))

model.add(Dense(units = 38, activation="softmax"))

model.compile(optimizer = "adam", loss ='categorical_crossentropy', metrics=['accuracy'])
```

**Comment by sachinprasadhs** [comment]
It is basically the number of classes you are using, if the data is a binary classification  then you need to change the output layer to something like `model.add(Dense(units = 1, activation="sigmoid"))`

**Comment by coder-monishr** [comment]
Thank you so much bro solved
