### ISSUE TITLE
Rplacement for ImageDataGenerator

### ISSUE THREAD

**Issue by Aydinhamedi** [keras-team/keras#19365]
In Keras 3, the [**_ImageDataGenerator_** ](https://github.com/keras-team/keras/blob/master/keras/legacy/preprocessing/image.py)has been deprecated. Is there a replacement for it?

**Comment by coder-monishr** [comment]
ohhhh thats y it didnt work for me, thanks folk i got to know that its been deprecated...😅

**Comment by sachinprasadhs** [comment]
`image_dataset_from_directory` is the replacement of the `ImageDataGenerator`, for augmentation you need to use preprocessing layer separately.
For more details on API usage, visit https://keras.io/api/data_loading/image/#image_dataset_from_directory-function

**Comment by WisarutBholsithi** [comment]
How can I find the way to replace ImageDataGenerator function with image_dataset_from_directory if ImageDataGenerator function has been set up as follows:
```
image_gen = ImageDataGenerator(rotation_range=20, # rotate the image 20 degrees
                               width_shift_range=0.10, # Shift the pic width by a max of 5%
                               height_shift_range=0.10, # Shift the pic height by a max of 5%
                               rescale=1/255, # Rescale the image by normalzing it.
                               shear_range=0.1, # Shear means cutting away part of the image (max 10%)
                               zoom_range=0.01, # Zoom in by 10% max
                               horizontal_flip=True, # Allow horizontal flipping
                               fill_mode='nearest' # Fill in missing pixels with the nearest filled value
                              )
RandomTransformImage = image_gen.random_transform(Anthracnose_leaf_img)
plt.imshow(RandomTransformImage)
```
