### ISSUE TITLE
Initializing classes inside random_initializers.py with a seed value of 0 ignores the seed

### ISSUE THREAD

**Issue by untilted** [keras-team/keras#19361]
If one of the classes in `random_initializers.py` is initialized with the `seed` parameter set to 0, the code will ignore the seed and choose a random seed instead, resulting in non-deterministic results. I don't think this is intended, since it isn't documented and seems to have worked as expected in earlier versions.

The cause of this is the inadvertent use of `seed` as a boolean, e.g., in `RandomNormal`:
https://github.com/keras-team/keras/blob/ba43e3b876d1053cd0388e4fc2c9599eeb44b394/keras/initializers/random_initializers.py#L50
The same bug exists for other classes in this file as well (e.g., `TruncatedNormal`, `RandomUniform`, etc`).

**Comment by sachinprasadhs** [comment]
Thanks for reporting the bug, I have created a PR to handle this edge case scenario.
