### ISSUE TITLE
keras-3:  saving weights in legacy h5 format fails for custom layer containing two sub-layers of the same type.

### ISSUE THREAD

**Issue by agreenbe0505** [keras-team/keras#19375]
Keras-3 assigns short names to weights, which is handy, but when it saves weights in legacy h5 format it picks names as:
     weight_names = [w.name.encode("utf8") for w in weights]

instead of:
      weight_names = [w.value.name.encode("utf8") for w in weights]  # old naming 

The file is:    **/keras/src/legacy/saving/legacy_h5_format.py**
function:     **save_subset_weights_to_hdf5_group()**

See the stack trace and a sample for the failure reproduction.

[stack.log](https://github.com/keras-team/keras/files/14743068/stack.log)

[reproduction.py.txt](https://github.com/keras-team/keras/files/14743221/reproduction.py.txt)

**Comment by sachinprasadhs** [comment]
Hi, As the warning suggests, `HDF5` is a legacy format, it is suggested to use `.keras` for saving the model.

> WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. 

If you change the code `model_file = "/tmp/model_weights.hdf5"` to `model_file = "/tmp/model_weights.keras"` it will solve the issue. Thanks

**Comment by agreenbe0505** [comment]
Do you say by this that the old keras2 saving format is unsupported in keras3?

**Comment by sachinprasadhs** [comment]
> Do you say by this that the old keras2 saving format is unsupported in keras3?

It is supported, but it is suggested to use .keras format since it works seamlessly.

**Comment by agreenbe0505** [comment]
So what about backward compatibility with the legacy keras models?
I tried to load the old keras model with Keras3 and if fails with the error

TypeError: Could not locate class 'Functional'. Make sure custom classes are decorated with `@keras.saving.register_keras_serializable()

Is there a way in keras3 to load legacy model?

**Comment by agreenbe0505** [comment]
OK, we could leave with that, loading old models saved in legacy format and saving the in the new format.
But this also does not work when legacy custom layers exist in the model.
Atttached 2 short snippets to demonstrate the problem.
One which stores the model is running in tf-2.8 
The other which loads ther model is running in keras-3 tf-2.15
The load crashes with the error: AttributeError: 'CircleLayer' object has no attribute '_self_tracked_trackables'
[load_legacy_model.py.txt](https://github.com/keras-team/keras/files/14915479/load_legacy_model.py.txt)
[save_legacy_model.py.txt](https://github.com/keras-team/keras/files/14915481/save_legacy_model.py.txt)

**Comment by sachinprasadhs** [comment]
Saving in older version and loading it in Keras 3 may not work as expected, it is highly recommended to save the model in .keras and load it back in the same format, since it has all the model config details.
Note: From Keras 3, the only saving format is .keras

**Comment by fchollet** [comment]
Thanks for the report. I have fixed the issue with the legacy h5 format at HEAD.

**Comment by sachinprasadhs** [comment]
Reference commit: https://github.com/keras-team/keras/commit/2c30d86711184b88009643cb206bdab4562f790e
