### ISSUE TITLE
Model summary print_fn got an unexpected keyword argument 'line_break'

### ISSUE THREAD

**Issue by Raychani1** [keras-team/keras#19371]
Hello I'm currently working on a model where I'm logging all sorts of creation and setup processes, but ran into a minor issue when trying to use a custom print function which allows me to redirect the model summary to the respective loggers and log files.

Tried multiple approaches including:
[Option 1](https://stackoverflow.com/a/53668338/14319439)
[Option 2](https://stackoverflow.com/a/53937848/14319439)
[Option 3](https://stackoverflow.com/a/50077092/14319439)

The problem is caused by line [363 in summary_utils.py](https://github.com/keras-team/keras/blob/f40e443279cc89198dc15712d334d0806e4c6e92/keras/utils/summary_utils.py#L363C39-L363C57). Tried to remove it locally in the Python environment, and the whole logging just worked. 

Is that parameter crucial there? Or have anybody else experience similar issues, when redirecting the model summary output?

Thanks in advance. 

Currently using version 3.1.1.

**Comment by sachinprasadhs** [comment]
Hi, To understand more on the issue, could you please provide sample reproducible code and make sure you're using latest `Keras` version 3.1.

**Comment by Raychani1** [comment]
Hello I've just put together a small use-case in this [gist](https://gist.github.com/Raychani1/81ca78982e67f8c05eea2cac18cd7ae5) with aforementioned options. Added also the output of `pip freeze` to check library versions.
