### ISSUE TITLE
ValueError occurred when building cascaded model with loaded sub-model

### ISSUE THREAD

**Issue by keisen** [keras-team/keras#19374]
Hi, keras team!

I'm facing a error when build cascaded model with sub-model loaded from a file.
It's okay if the sub-model is NOT loaded from file, just created on memory.
This behavior appeared form keras 3+. Until keras 2.x, it didn't exist definitely.

I wrote the code to reproduce error, please refer to notebook below:
https://gist.github.com/keisen/4703d6508a950ff6a35d84da73e335b8

Please improve this issue or let me know how to work around with keras 3.x....

Thanks!

**Comment by SuryanarayanaY** [comment]
Hi @keisen ,

I have replicated the issue with Keras3(TF2.16v) and attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/1646d93c579d26e2a1ac149c6343e429/19374_issue-error_occurred_building_cascaded_model-2-16v.ipynb) here. With Keras2 it works fine and attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/f209b5997d05030cda61c5ddd08e4e2b/19374_issue-error_occurred_building_cascaded_model-2-15v.ipynb) here.

This seems a regressions issue for me.Will check and update. Thanks!

**Comment by SuryanarayanaY** [comment]
Hi @keisen ,

I did some debugging and find out the reason for this error.Basically the output of child model is Keras Tensor whereas `loaded_child_model` it is Tensor but wrapped in the list. I have verified both model configs and they are same. 

It's quite interesting why the `loaded_child_model` is wrapping the Tensor in a list.

Sharing the [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/c72e0c03c3e6d36a77979b5bb079d79b/19374_error_cascaded_model-2-16v.ipynb) with the debug info so far.

**Comment by keisen** [comment]
@SuryanarayanaY 

> It's quite interesting why the loaded_child_model is wrapping the Tensor in a list.

Yep, That's why I asked you to resolve this issue.
Before posting, I've also tried the test you did then got the same as you got, and in addition, you may also already try,  I ran the code below:

```python
X = tf.random.normal((1, 8, 8, 3))

print('child_model       :', child_model(X))
print('loaded_child_model:', loaded_child_model(X))
```

Then I got the output below:

```
child_model       : tf.Tensor([[0.3972141 0.6027859]], shape=(1, 2), dtype=float32)
loaded_child_model: tf.Tensor([[0.3972141 0.6027859]], shape=(1, 2), dtype=float32)
```

As you can see above, The result of `loaded_child_model` is not a `list` object.

Before posting, I was going to debug and hack to work around this issue,
but, after seeing this, I gave up completely then decided to ask you and your team.
This problem is definitely over my head lol.

I'm looking forward to hearing good news from you!
Best regards,
keisen

**Comment by SuryanarayanaY** [comment]
Hi @keisen ,
 
I also have tested with numpy array and predictions are same for both . It seems this is happening with Keras Tensor(placeholder) only. You can notice the same on gist. I am also looking into it for the root cause.Its taking time apparently.

**Comment by fchollet** [comment]
It appears I have fixed this issue as the same issue was previously reported in a different ticket. Please check that Keras at HEAD works for you.
