### ISSUE TITLE
`BackupAndRestore` callback fails to restore optimizer variables in case of complete restart

### ISSUE THREAD

**Issue by briango28** [keras-team/keras#19389]
The [`BackupAndRestore`](https://github.com/keras-team/keras/blob/master/keras/callbacks/backup_and_restore.py) callback loads model variables from disk when its [`on_train_begin()`](https://github.com/keras-team/keras/blob/v3.1.1/keras/callbacks/backup_and_restore.py#L100) method is called.
However, if a machine was shutdown and restarted, or the keras model re-initialized for any other reason, `BackupAndRestore` fails to load optimizer variables from disk due to the variables not having been built yet.
This logic can be found in [`BaseOptimizer.load_own_variables()`](https://github.com/keras-team/keras/blob/v3.1.1/keras/optimizers/base_optimizer.py#L538).

A workaround is to pre-build the optimizer by calling `self.model.optimizer.build(self.model.variables)`, but this should ideally be done automatically.

The following notebook illustrates the issue
https://colab.research.google.com/drive/1fYxwTWLFw5csjnziuJ1pQVp1oN3YBEny?usp=sharing

Note that cells no. 10 & 11 are cells no. 6 & 8 with `BackupAndRestore` replaced with `AltBackupAndRestore` implemented in cell no. 9, and that cells 6 & 10 are supposed to raise a `RuntimeError` and will naturally interrupt any "run all" functionality.

I'm not sure whether or not this is intended behavior, nor if the above implementation is optimal.

**Comment by fchollet** [comment]
Thanks for the report. I fixed it at HEAD.

**Comment by sachinprasadhs** [comment]
Reference commit: https://github.com/keras-team/keras/commit/cf8ca3c7be849aa87eeddd51530bfd47caa225d6
