### ISSUE TITLE
Avoid rank promotion throughout the codebase

### ISSUE THREAD

**Issue by romanngg** [keras-team/keras#19394]
Accidental rank promotion can lead to silent bugs.

JAX can be configured to raise an error on rank promotion, to catch these bugs in the user codebase:
https://jax.readthedocs.io/en/latest/rank_promotion_warning.html

For this to be useful, the libraries used should not have rank promotion within their codebases, which is the case in JAX, FLAX, and many other libraries in the ecosystem.

Unfortunately Keras performs rank promotion (e.g. addition of bias), so this setting is not usable:
https://colab.research.google.com/gist/romanngg/e771c164db3f8e9ed4ba7a7893890ee1/keras_rank_promotion.ipynb

It would be great to have no rank promotion in Keras as well, thank you!

**Comment by grasskin** [comment]
Hi @romanngg - thank you for looking into this! Because of our multibackend functionality this is complicated to implement on our side. Given that this is a JAX specific issue we're unable to target this at this time.
