### ISSUE TITLE
Facing Issue while installing Keras

### ISSUE THREAD

**Issue by carrycooldude** [keras-team/keras#19390]
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. 
This behaviour is the source of the following dependency conflicts.
tensorflow 2.13.1 requires keras<2.14,>=2.13.1, but you have keras 3.1.1 which is incompatible.
```

**Comment by SuryanarayanaY** [comment]
Hi @carrycooldude ,
It seems you have TF2.13 installed in your environment. Please upgrade it to TF2.16v if you want to use Tensorflow at backend.

**Comment by carrycooldude** [comment]
> Hi @carrycooldude ,
> It seems you have TF2.13 installed in your environment. Please upgrade it to TF2.16v if you want to use Tensorflow at backend.

I also did that but facing the issue on the same.

**Comment by markodjordjic** [comment]
@carrycooldude Do you have any specific reason for not using Keras 3 and TF2.16?

**Comment by SuryanarayanaY** [comment]
> > Hi @carrycooldude ,
> > It seems you have TF2.13 installed in your environment. Please upgrade it to TF2.16v if you want to use Tensorflow at backend.
> 
> I also did that but facing the issue on the same.

Please print the tensorflow version and submit the logs here. It should work.

**Comment by carrycooldude** [comment]
Sure I got it, it just some version issues on my laptop. Thanks for helping me
