### ISSUE TITLE
Custom loss trackers not working for JAX backend

### ISSUE THREAD

**Issue by water-vapor** [keras-team/keras#19402]
Here is a toy example modified from [the example here](https://github.com/keras-team/keras/blob/a063684e1128944461809d923758f9a684e721de/keras/trainers/trainer.py#L276). When I use `tensorflow` or `torch` backend, the code runs fine. But when I use the `jax` backend, it gives an error:

```
File ~/miniconda3/envs/[redacted]/lib/python3.11/site-packages/keras/src/backend/common/variables.py:130, in KerasVariable.value(self)
    123         return self._maybe_autocast(value)
    124 if self._value is None:
    125     # Uninitialized variable. Return a placeholder.
    126     # This is fine because it's only ever used
    127     # in during shape inference / graph tracing
    128     # (anything else would be a bug, to be fixed.)
    129     return self._maybe_autocast(
--> 130         self._initializer(self._shape, dtype=self._dtype)
    131     )
    132 return self._maybe_autocast(self._value)

TypeError: 'NoneType' object is not callable
``` 

Further investigation shows that the error comes from the `count` and `total` variables from the `metrics.Mean` class. They were properly initialized to 0.0 upon the `__init__` call, and were still intact after the first `reset_metrics` call. However, when the training loop enters the `compute_loss` function, their values are lost, resulting in the error above. I am not familiar with Jax, so locating the bug alone is difficult. Any help or fixes would be appreciated.

Example Code:
```python
import os
os.environ["KERAS_BACKEND"] = "jax"


import numpy as np
import keras
from keras import layers, ops, Model, metrics
from keras.optimizers import SGD

keras.config.disable_traceback_filtering()

class MyModel(Model):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.loss_tracker = metrics.Mean(name='loss')
        

    def compute_loss(self, x, y, y_pred, sample_weight=None, allow_empty=None):
        loss = ops.mean((y_pred - y) ** 2)
        self.loss_tracker.update_state(loss)
        return loss

    def reset_metrics(self):
        self.loss_tracker.reset_state()

    @property
    def metrics(self):
        return [self.loss_tracker]

inputs = layers.Input(shape=(10,), name='my_input')
outputs = layers.Dense(10)(inputs)
model = MyModel(inputs, outputs)

optimizer = SGD()
model.compile(optimizer, loss='mse')
x_train, y_train = np.random.random((100, 10)), np.random.random((100, 10))
model.fit(x_train, y_train, epochs=2, batch_size=10)
```
Keras version: 3.1.1

**Comment by SuryanarayanaY** [comment]
Hi @water-vapor ,

Thanks for reporting. I have replicated the error with Jax backend and confirms that the same works with TF and torch backends. Attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/fa10db861073c50c77d33da9f20b3e45/19402.ipynb) for reference.I will try to dig more and keep you update. Thanks!

**Comment by water-vapor** [comment]
Thanks for the update. I had some time today to dig a bit more into this issue. It appears the problem might be more complex than a simple bug. Its roots seem to lie in the stateless nature of jax.

There are two direct workarounds for this issue sacrificing multiple-backend compatibility. One is using `StatelessScope` to guard the `update_state`, and another is using `stateless_update_state` instead. However, both require access to `metrics_variables`,making the code jax-specific.  I initially aimed to avoid a custom `train_step` function to maintain backend flexibility.

After inspecting the jax backend trainer code, I found that the `compute_loss` function is only scoped with `trainable_variables` and `untrainable_variables`, while the `compute_metrics` includes `metrics_variables`. Ideally, if `metrics_variables` is also included in the scope of [the `compute_loss` function](https://github.com/keras-team/keras/blob/d7f4605935614150863e1aa8508702599b28601a/keras/backend/jax/trainer.py#L56), there would be no issue with my code example. However, this would require a change of signature of `compute_loss_and_updates` which may not align with the project's design. 

An alternative without changing the source code, is putting the `update_states` in `compute_metrics`: 
```python 
    # add this function to my example code, and remove the update_state in the compute_loss function
    def compute_metrics(self, x, y, y_pred, sample_weight=None, allow_empty=None):
        loss = ops.mean((y_pred - y) ** 2)
        self.loss_tracker.update_state(loss)
        return {}
```
However, this approach calculates the loss twice, as it's already computed in the `compute_loss` function. And I have not found a way to carry the result over. 

Out of curiosity, I searched and looked through the examples in the `keras-io` repo. It seems that `update_state` is only used in Keras 2 or TensorFlow-specific Keras 3 examples. The `stateless_update_state` approach appears exclusive to JAX examples within custom `train_step` functions that access `metrics_variables`. Given the prevalent need to log custom metrics during the loss calculation process, I hope there is a backend-agnostic solution without the limitations of the workarounds I found.

**Comment by fchollet** [comment]
An update here: this issue keeps coming up, and the discrepancy between JAX behavior (no metrics updates in compute_loss) and other backends (where this actually works) is turning out to be problematic. As a result I updated the JAX trainer to be able to update metrics variables in `compute_loss_and_updates`. So at HEAD you should be able to update loss trackers in `compute_loss` in a backend-agnostic fashion.
