### ISSUE TITLE
AttributeError: module `pydot` has no attribute `InvocationException`

### ISSUE THREAD

**Issue by carrycooldude** [keras-team/keras#19408]
I am going through the [Functional API Doc](https://keras.io/guides/functional_api/#introduction) and using pydot I don't know why it is showing error even though I have updated keras and pydot too.Here is some ScreenShots:
![Screenshot from 2024-03-30 17-31-11](https://github.com/keras-team/keras/assets/41143496/c3a571cc-0f2d-468c-803a-0c46043f972b)

![Screenshot from 2024-03-30 17-31-52](https://github.com/keras-team/keras/assets/41143496/b1539405-446e-4a6d-af19-afd8afece50e)

![Screenshot from 2024-03-30 17-32-18](https://github.com/keras-team/keras/assets/41143496/fa3e8a0d-8773-47ec-a257-ca9c39b3eae3)

**Comment by SuryanarayanaY** [comment]
Hi @carrycooldude ,

This is fixed in nightly. Please refer tested [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/b5e8f37c3e5a2fa139d3b19c7026fbb1/functional_api.ipynb). Thanks!

**Comment by carrycooldude** [comment]
Thanks @SuryanarayanaY , will definetly check this out

**Comment by abkhoshk** [comment]
this worked for me 

pip install pydot # 2.0.0
conda install graphviz # 2.50.0
