### ISSUE TITLE
Numpy Ops function nonzero(x) appers to be missing check for symbolic tensors

### ISSUE THREAD

**Issue by kfeldman** [keras-team/keras#19407]
In updating  code from Keras 2 to 3, we noticed that nonzero function continues to throw errors for use of KerasTensor in TF functions, even when run though tf.keras.ops

Digging into the source, it appears that this function does not receive the check for any_symbolic_tensors(), and thus no instantiation of the NonZero() class. In turn failing when used with a KerasTensor

https://github.com/keras-team/keras/blob/42a1535ed7d3d75711a11d295f58a2dc9a59fdae/keras/ops/numpy.py#L3976

**Comment by grasskin** [comment]
Thank you for filing this! Submitted a fix to allow for symbolic nonzero calls but feel free to reopen/open a new issues if you run into anything further.
