### ISSUE TITLE
Metrics for YOLOv8 model

### ISSUE THREAD

**Issue by alejones** [keras-team/keras#19416]
Will User metrics ever be supported for YOLOV8 or is it expected that I use a COCO callback?

### Current Behavior:

When I compile a YOLOv8 model with metrics I get an error
``` python
model.compile(
    classification_loss="binary_crossentropy",
    box_loss="ciou",
    optimizer=optimizer,
    metrics = [keras.metrics.Recall(), keras.metrics.Precision()]
)
````
```
ValueError: User metrics not yet supported for YOLOV8
```

### Expected Behavior:
Adding the requested metrics

### Steps To Reproduce:
[Gist](https://colab.research.google.com/gist/alejones/88475939e40e0d14f7096b240b65624f/yolo_keras_cv_metrics.ipynb)

### Version:
Keras version: 3.1.1
Keras_cv version: 0.8.2

**Comment by SuryanarayanaY** [comment]
Hi @alejones ,

I have replicated the reported behaviour and attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/3199eb9336af5800361c092c8b91c571/19416_yolo_keras_cv_metrics.ipynb). These metrics seems not yet supported for YOLO. IMO, this should be reported at [keras_cv](https://github.com/keras-team/keras-cv/issues) as we have separate repo for same.

**Comment by grasskin** [comment]
Hi @alejones, thank you for opening the bug in keras-cv. Closing this for now and we'll address this in our domain package.
