### ISSUE TITLE
Can you provide an official implementation of FSDP based on keras distributed API?

### ISSUE THREAD

**Issue by pass-lin** [keras-team/keras#19420]
I want to train gemma-7b, but I can't achieve fsdp. Hope keras-team can provide an implementation

**Comment by SuryanarayanaY** [comment]
Hi @pass-lin ,

Could you please refer [data_parallel](https://keras.io/api/distribution/data_parallel/) API and also [distribution](https://keras.io/guides/distribution/) and let us know if it helps.

**Comment by innat** [comment]
FSDP https://pytorch.org/tutorials/intermediate/FSDP_tutorial.html

**Comment by pass-lin** [comment]
> Hi @pass-lin ,
> 
> Could you please refer [data_parallel](https://keras.io/api/distribution/data_parallel/) API and also [distribution](https://keras.io/guides/distribution/) and let us know if it helps.

Hello, based on your information, I implemented the following code (single-machine multi-card environment)
```python
devices = np.array(jax.devices()).reshape(1, -1, 1)
mesh = keras.distribution.DeviceMesh(devices.shape, ('dp', 'fsdp', 'mp'), devices=jax.devices())
layout_map = keras.distribution.LayoutMap(mesh)
parallel = keras.distribution.ModelParallel(mesh, layout_map)
keras.distribution.set_distribution(parallel)
```
But this is incorrect and cannot run. I want to know why this is the case.

**Comment by SuryanarayanaY** [comment]
Hi @pass-lin ,

Could you please submit a minimal repro code for this ? Thanks!

**Comment by pass-lin** [comment]
> Hi @pass-lin ,
> 
> Could you please submit a minimal repro code for this ? Thanks!
I’m not quite understanding why these commands above are resulting in errors
