### ISSUE TITLE
Jax Backend on Colab

### ISSUE THREAD

**Issue by sherpan** [keras-team/keras#19423]
Im looking at the following [colab](https://colab.research.google.com/github/keras-team/keras-io/blob/master/guides/ipynb/keras_core/getting_started_with_keras_core.ipynb#scrollTo=NzGdFzgkc0eM) and using `keras.backend.backend()` to verify Keras3 is using JAX. But it is printing tensorflow

![Screenshot 2024-04-02 at 1 16 52 PM](https://github.com/keras-team/keras/assets/16737376/9db0538f-8d9a-4dc8-903b-51d10cf78a45)

**Comment by sachinprasadhs** [comment]
Hi, 

You need to set the backend first before importing any of the package.

Below code should work.

```python
import os
os.environ["KERAS_BACKEND"] = "jax"

import numpy as np
import keras

print(keras.backend.backend())
```

**Comment by sherpan** [comment]
got it! that works. I believe this[colab](https://github.com/keras-team/keras-io/blob/master/guides/ipynb/keras_core/getting_started_with_keras_core.ipynb#scrollTo=_9ePvKWYQBzS) is from the keras team. it might be worth updating it!

**Comment by sachinprasadhs** [comment]
This colab is under `keras_core` directory, which is no longer used to render tutorials in keras.io since the time keras_core became Keras 3.
For all the tutorials, you can find it directly here https://github.com/keras-team/keras-io/tree/master/guides/ipynb

**Comment by sachinprasadhs** [comment]
I removed the directory which you are referring in the PR here https://github.com/keras-team/keras-io/pull/1818
Feel free to close the issue.
