### ISSUE TITLE
Any plan to add type annotations?

### ISSUE THREAD

**Issue by gmdzy2010** [keras-team/keras#19453]
It's very strange as I noticed:
```python
from keras import layers, models

model = models.Sequential()

...
```
The type checker(of vscode) would consider the type of `model` instance as 
```
(variable) model: Functional | Unknown
```
as a result, the code completion didn't work well even for some simple case:
```python
...
layer_conv2d_1 = layers.Conv2D(
    32,
    (3, 3),
    activation="relu",
    input_shape=(28, 28, 1),
)

model.add(layer_conv2d_1)
...
```
method `add` couldn't be found.

`type annotation` may help us deal with those above.

Or some work around?

**Comment by fchollet** [comment]
It looks like VSCode is not able to determine that `Sequential` has a method `add()` -- even though it's right there in the `Sequential` class definition. Type annotations wouldn't help here. I would expect the code completion feature for properties/methods to use `dir()` and filter for public (no underscore) entries. Which should work here.

Are you able to pinpoint what exactly is causing this?

**Comment by fchollet** [comment]
This should now be fixed!
