### ISSUE TITLE
How to import existing trained pytorch model to keras 3

### ISSUE THREAD

**Issue by sunilsarolkarcds** [keras-team/keras#19451]
We have Openpose model written in pytorch https://github.com/Hzzone/pytorch-openpose . The model is present in the pth file format and model structure is defined using pytorch api. We want to use the openpose model in our new project which we plan to use keras 3 with pytorch backend. We want to use the existing openpose model with freezed parameters and add our layers on top of it. Can you please help how can we convert existing pth file into keras model format.

We tried converting the pytorch model to onnx and then convert it to keras format using keras2onnx but seems like keras2onnx has hard dependency on tensorflow, we need to use pytorch as backend for keras 3. Can you please help regarding the same

**Comment by fchollet** [comment]
You can try `keras.layers.TorchModuleWrapper`, see this example: https://colab.research.google.com/drive/1tWJNm3g_EnRdZIkKZk_FGwUU7LMf8vb5

**Comment by sunilsarolkarcds** [comment]
Thanks @fchollet  its working perfectly fine
