### ISSUE TITLE
TypeError: Exception encountered when calling Bidirectional.call(). can only concatenate list (not "tuple") to list

### ISSUE THREAD

**Issue by mpetteno** [keras-team/keras#19478]
Hi everyone,

I have an error while creating a simple `Bidirectional` layer with `return_state=True` and printing the summary of the model.
The error is the one in the title of the issue, here the complete stacktrace.

> Error
> Traceback (most recent call last):
>   File "test.py", line 172, in test_bid
>     model = keras.Sequential([
>             ^^^^^^^^^^^^^^^^^^
>   File ".venv/lib/python3.11/site-packages/keras/src/models/sequential.py", line 70, in __init__
>     self._maybe_rebuild()
>   File ".venv/lib/python3.11/site-packages/keras/src/models/sequential.py", line 135, in _maybe_rebuild
>     self.build(input_shape)
>   File ".venv/lib/python3.11/site-packages/keras/src/layers/layer.py", line 223, in build_wrapper
>     original_build_method(*args, **kwargs)
>   File ".venv/lib/python3.11/site-packages/keras/src/models/sequential.py", line 195, in build
>     raise e
>   File ".venv/lib/python3.11/site-packages/keras/src/models/sequential.py", line 176, in build
>     x = layer(x)
>         ^^^^^^^^
>   File ".venv/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
>     raise e.with_traceback(filtered_tb) from None
>   File ".venv/lib/python3.11/site-packages/keras/src/layers/rnn/bidirectional.py", line 190, in compute_output_shape
>     return [output_shape] + state_shape + copy.copy(state_shape)
>            ~~~~~~~~~~~~~~~^~~~~~~~~~~~~
> TypeError: Exception encountered when calling Bidirectional.call().
> 
> can only concatenate list (not "tuple") to list
> 
> Arguments received by Bidirectional.call():
>   • args=('<KerasTensor shape=(None, 5, 10), dtype=float32, sparse=None, name=keras_tensor_5>',)
>   • kwargs={'mask': 'None'}

How to reproduce it:

```
model = keras.Sequential([
    keras.Input(shape=(5, 10)),
    keras.layers.Bidirectional(keras.layers.LSTM(10, return_state=True))
])
model.summary()
```

The problem is in the `compute_output_shape` method of the `Bidirectional` class: while returning the state, `output_shape` is wrapped into a list and then concatened with `state_shape` which is a tuple.

**Comment by fchollet** [comment]
Thanks for the report -- this is fixed at HEAD. You can just install the latest version of Keras.
