### ISSUE TITLE
AttributeError: 'list' object has no attribute 'dtype' while using keras.utils.plot_model

### ISSUE THREAD

**Issue by mpetteno** [keras-team/keras#19480]
Hi everyone,

I want to report a problem using `keras.utils.plot_model` with multi-ouput models.
The stacktrace is:

> Error
> Traceback (most recent call last):
>   File "test.py", line 163, in test_bid
>     keras.utils.plot_model(
>   File "/.venv/lib/python3.11/site-packages/keras/src/utils/model_visualization.py", line 424, in plot_model
>     dot = model_to_dot(
>           ^^^^^^^^^^^^^
>   File "/.venv/lib/python3.11/site-packages/keras/src/utils/model_visualization.py", line 284, in model_to_dot
>     node = make_node(layer, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/.venv/lib/python3.11/site-packages/keras/src/utils/model_visualization.py", line 160, in make_node
>     node = pydot.Node(str(id(layer)), label=make_layer_label(layer, **kwargs))
>                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/.venv/lib/python3.11/site-packages/keras/src/utils/model_visualization.py", line 121, in make_layer_label
>     dtype = layer.output.dtype
>             ^^^^^^^^^^^^^^^^^^
> AttributeError: 'list' object has no attribute 'dtype'
> 

How to reproduce it:

```
model = keras.Sequential([
    keras.Input(shape=(5, 10)),
    keras.layers.Bidirectional(keras.layers.LSTM(10, return_state=True)),
])
keras.utils.plot_model(
    model,
    show_shapes=False,
    show_layer_names=True,
    show_dtype=True,
    to_file="./model.png"
)
```

The error occurs either setting `show_shapes=True` or `show_dtype=True` and it is due to the fact that `layer.output` is a list when the model has multiple outputs.

Thanks for your support.

**Comment by fchollet** [comment]
This is fixed, just update to the latest Keras version.
