### ISSUE TITLE
Loading saved frozen model fails

### ISSUE THREAD

**Issue by breuderink** [keras-team/keras#19491]
I am finetuning a model that consists of a head on top of a frozen base. When I save checkpoints using `ModelCheckpoint` I can't load the model. I have isolated the problem to saving a model with a frozen `Conv1D` layer:

```
import keras
 
model = keras.Sequential(
    [keras.Input((10, 3)), keras.layers.Conv1D(5, kernel_size=3, name="conv")],
)
model.get_layer("conv").trainable = False
model.save("model.keras")
 
loaded_model = keras.saving.load_model("model.keras")
 
# ValueError: A total of 1 objects could not be loaded. Example error message
# for object <Conv1D name=conv, built=True>:
#
# Layer 'conv' expected 4 variables, but received 2 variables during loading.
# Expected: ['kernel', 'bias', 'kernel', 'bias']
#
# List of objects that could not be loaded: [<Conv1D name=conv, built=True>]
```

I believe this is a bug. I am running Keras v3.2.0 with the Jax backend.

**Comment by fchollet** [comment]
Thanks for the report. This bug has been fixed previously, so you can just upgrade to the latest Keras version.
