### ISSUE TITLE
image_dataset_from_directory: Shuffle buffer size arbitrarily set to 1024 when batch_size is None

### ISSUE THREAD

**Issue by gaetanbahl** [keras-team/keras#19502]
Hello,

I am trying to read 12MP images one by one to apply custom pre-processing (per-image random crop) and batch them later without any pre-fetch or caching to save memory.

However, in image_dataset_from_directory, setting batch_size to None while shuffling is enabled will automatically use a buffer size of 1024, which completely fills my memory (exactly what I was trying to avoid).

Instead of shuffling at the "image" level, I would expect this class to shuffle at the "file name" level, i.e. shuffle *before* loading the images.

https://github.com/keras-team/keras/blob/f77b020e497a353b644df3aeebc97c831c8057fc/keras/utils/image_dataset_utils.py#L347

What would be the appropriate solution? Thanks.

**Comment by fchollet** [comment]
> Instead of shuffling at the "image" level, I would expect this class to shuffle at the "file name" level, i.e. shuffle before loading the images.

Upon first reading this I thought, well if we just shuffle the file names before making the dataset, the images will be shuffled for one epoch, but then the same pattern will repeat at every following epoch, that's not random.

But then I paused for a second and I thought, wait, we can shuffle the file paths inside the tf.data pipeline! That is indeed much more efficient than shuffling the images.

I fixed at HEAD. Thanks for the report.
