### ISSUE TITLE
TrackedList type error for appending NamedTuple

### ISSUE THREAD

**Issue by cliu-nuro** [keras-team/keras#19503]
To append a NamedTuple object to a list, we will encounter TypedError due to this line of code https://github.com/keras-team/keras/blob/master/keras/utils/tracking.py#L90
```
        if isinstance(attr, tuple):
            wrapped_attr = []
            for e in attr:
                wrapped_attr.append(self.track(e))
            # This should cover tuples and nametuples
            return attr.__class__(wrapped_attr)
```

Basically, for `typing.Named` tuple, we need to unwrap the attributes to properly construct the object:`return attr.__class__(*wrapped_attr)`

**Comment by sachinprasadhs** [comment]
Could you please provide reproducible code to replicate the reported behavior. Thanks

**Comment by fchollet** [comment]
Thanks for the report, I fixed it at HEAD. Namedtuples needed to be special-cased as such:

```python
        if isinstance(attr, tuple) and hasattr(attr, "_fields"):
            # Named tuple case.
            wrapped_attr = {}
            for name, e in attr._asdict().items():
                wrapped_attr[name] = self.track(e)
            return attr.__class__(**wrapped_attr)
```

**Comment by sachinprasadhs** [comment]
Reference commit: https://github.com/keras-team/keras/commit/5187fac82ab979e7dbf39e16ea31c87d075029a5
