### ISSUE TITLE
Newly introduced `weights` in `Embedding` layer breaks the downstream layers such as `ReversibleEmbedding` in KerasNLP

### ISSUE THREAD

**Issue by james77777778** [keras-team/keras#19505]
The `__init__` explicitly calls `self.build()` which causes issues with `ReversibleEmbedding` because it requires `self.tie_weights` to be set before `self.build` is called.

I propose that only call `self.build()` if `weights` is specified.

```python
        if weights is not None:
            self.build()  # <- move to here
            if not (isinstance(weights, list) and len(weights) == 1):
                weights = [weights]
            self.set_weights(weights)
``` 

cc @mattdangerw

**Comment by fchollet** [comment]
Thanks for the suggestion, I applied it.
