### ISSUE TITLE
keras/preprocessing/text module is missing in Keras 3

### ISSUE THREAD

**Issue by veeramanikandanvv** [keras-team/keras#19517]
when i am trying to utilize the below module,
from keras.preprocessing.text import Tokenizer

we found out the text module is missing in Keras 3. Please help us in utilizing the text module. Please help.

tensorflow version: 2.16.1
keras: 3.21

**Comment by fchollet** [comment]
It was deprecated many years ago (in 2020 or 2021 I think?) and removed from the API in Keras 3. It was kept in `tf.keras` for backwards compatibility. It has been removed from the docs around 2021 or 2022.

You can use `keas.layers.TextVectorization` instead.
