### ISSUE TITLE
function object mismatch in TFOpLambda in Keras functional model

### ISSUE THREAD

**Issue by elad-c** [keras-team/keras#19525]
### Description:
The function object stored in the `function` attribute of a `TFOpLambda` in a functional model doesn't match the original tensorflow function I used to build the model. This happens for `tf.add`, `tf.multiply` & `tf.matmul`. Doesn't happen for `tf.subtract` and `tf.divide`.

This behaviour started in version 2.15.

### Code:
```
import tensorflow as tf
import keras
from keras.src.layers.core import TFOpLambda

_in = tf.keras.layers.Input((8,))
out = tf.add(_in, 4)
out = tf.subtract(out, 4)
model = keras.Model(inputs=_in, outputs=out)

print(f'1) layer match: {isinstance(model.layers[1], TFOpLambda)}')
print(f'2) add match: {model.layers[1].function is tf.add}')
print(f'3) subtract match: {model.layers[2].function is tf.subtract}')

```
### Output for TF 2.15:
```
1) layer match: True
2) add match: False
3) subtract match: True

```
### Output of TF 2.14:
```
1) layer match: True
2) add match: True
3) subtract match: True

```

**Comment by sachinprasadhs** [comment]
Hi, Could you please migrate your code to Keras 3 and `TFOpLambda` is not available in Keras 3.
You can refer the migration guide for more details: https://keras.io/guides/migrating_to_keras_3/

**Comment by elad-c** [comment]
Hi @sachinprasadhs ,
Unfortunately, migrating the code to **_Keras 3_** is not an option for me. Is there a way to solve mt issue in _**keras 2.15.0**_?

**Comment by SamanehSaadat** [comment]
Hi @elad-c !

Does this cause any issues with the output?

**Comment by fchollet** [comment]
They're two references to the same function: https://colab.research.google.com/drive/1V2TsgcVmwST9KAfUdzFWZmg2E5o6JDku?usp=sharing

Everything is working normally here.
