### ISSUE TITLE
[Docs] I cannot find the documentation on `keras.utils.Sequence`

### ISSUE THREAD

**Issue by Akhil-CM** [keras-team/keras#19532]
I might not be looking properly but I cannot find the official documentation on `keras.utils.Sequence` anywhere on the main website. I apologize if this is known to the team and they are slowly working on it or looking for PRs about it.

**Comment by fchollet** [comment]
`Sequence` was modified in Keras 3 and is now exported as the `keras.utils.PyDataset` class. It is still found in the API as `keras.utils.Sequence`, but that name is now deprecated. https://keras.io/api/utils/python_utils/#pydataset-class

**Comment by Akhil-CM** [comment]
Thanks for info. If you [search](https://keras.io/search.html?query=keras.utils.Sequence) for `keras.utils.Sequence` you'll get these results. In the first result on [Model training APIs](https://keras.io/2.15/api/models/model_training_apis/) `keras.utils.Sequence` is mentioned as a possible input `x` to the `fit` method of the `model`. Maybe indicate here or another place([PyDataset](https://keras.io/api/utils/python_utils/#pydataset-class)) that the sequence class is renamed?
