### ISSUE TITLE
it is no longer possible to see the input shape of a layer with keras.utils.plot_model when setting `show_shapes=True`

### ISSUE THREAD

**Issue by Rygone** [keras-team/keras#19536]
Is it possible to add the possibility to show the input shape as now we can only see the output shape with show_shapes=True

_Originally posted by @Rygone in https://github.com/keras-team/keras/issues/19460#issuecomment-2044271855_

**Comment by fchollet** [comment]
Thanks for the suggestion. This used to be visible in Keras 2. I have added it back, since it can be useful in some cases.
