### ISSUE TITLE
no `select` in keras.ops

### ISSUE THREAD

**Issue by jonbarron** [keras-team/keras#19548]
Hi all, `keras.ops` is missing the `select()` function in numpy, can you please add it? You can express it as a series of nested np.where() calls, if this is helpful:
```
def select(condlist, choicelist, default=0):
  result = default
  for cond, choice in zip(condlist[::-1], choicelist[::-1]):
    result = jnp.where(cond, choice, result)
  return result
```
though I expect this is not particularly efficient.

**Comment by fchollet** [comment]
Yes, that's in scope for Keras, we can add it.

**Comment by fchollet** [comment]
This is completed.
