### ISSUE TITLE
no `argpartition` op in keras.ops

### ISSUE THREAD

**Issue by jonbarron** [keras-team/keras#19547]
Hi all, I'm trying to use Keras 3 as a drop-in replacement for numpy, but several ops are missing, such as `argpartition`. Can this be added? A viable workaround in case torch doesn't have an equivalent op would be to have the torch backend just call np.sort(), as this is sufficient to satisfy the conditions for `argpartition` (it's a quicksort pivot basically, so fully-sorting the list is overkill but not "wrong").

**Comment by fchollet** [comment]
This is now in the API at HEAD.
