### ISSUE TITLE
Can `keras.ops` get a `keras.ops.linalg`, so it's equivalent to `np`?

### ISSUE THREAD

**Issue by jonbarron** [keras-team/keras#19546]
Hi, I'm trying to use Keras 3's `keras.ops` interface as a drop-in replacement for numpy, so that I can write JAX and Pytorch compatible numpy. But I'm using `np.linalg.*` in my code, and `keras.ops` doesn't have a `.linalg` field. A lot of the functionality in `np.linalg` is in `keras.src.ops.linalg`. Can y'all just put an alias to `keras.src.ops.linalg` in `keras.ops.linalg`? This would make Keras 3 a drop-in replacement for numpy.

Here's my current workaround, if it's helpful:

```
import keras.ops as knp
from keras.src.ops import linalg as keras_linalg

class KnpExtended:
    def __init__(self):
        self.knp = knp
        self.linalg = keras_linalg

    def __getattr__(self, name):
        if hasattr(self.knp, name):
            return getattr(self.knp, name)
        elif hasattr(self.linalg, name):
            return getattr(self.linalg, name)
        raise AttributeError(f"module 'KnpExtended' has no attribute '{name}'")

jnp = KnpExtended()
```

**Comment by fchollet** [comment]
There is `keras.ops.linalg`:

```python
from keras import ops

for name in dir(ops.linalg):
    if not name.startswith("_"):
        print(name)
```

Outputs:

```
cholesky
det
eig
inv
lu_factor
norm
qr
solve
solve_triangular
svd
```

**Comment by jonbarron** [comment]
Ah sorry, looks like this was fixed since I first encountered this.
