### ISSUE TITLE
Pickle support via __reduce__ API

### ISSUE THREAD

**Issue by LukeWood** [keras-team/keras#19554]
Hello -

I've written a monkey patch that uses Keras' standard saving logic to support pickling of keras models.  I think this is good because if we simply use the standard saving logic, there shouldn't really be any maintenance burden to preserve the pickling support.

The way it works is pretty easy:

```
def _depickle_model(bytesio):
  with tempfile.TemporaryDirectory() as d:
    with open(d + '/model.keras', 'wb') as f:
      f.write(bytesio.getbuffer())
    return keras.models.load_model(d + '/model.keras')

def __reduce__(self):
  with tempfile.TemporaryDirectory() as d:
    self.save(d + '/model.keras')

    with open(d + '/model.keras', "rb") as fh:
        buf = io.BytesIO(fh.read())
  return (_depickle_model, (buf,))

keras.Model.__reduce__ = __reduce__
```

Basically in its current version this code is not very good because it relies on an intermediary tempfile to pass all of the checks in keras' `save()` function, but if we could use library internal functions such as `_save_model_to_fileobj` we could then save directly to a `bytesIO` object and make this pretty seamlessly work end to end.

---

Why:  this is useful for orchestration tools such as
https://joblib.readthedocs.io/en/stable/

---

Here's a colab to showcase this: https://colab.research.google.com/drive/1NcFxKfU-O6GUacEYyIxuJS15Ss7Ms9kQ?usp=sharing

---

If the team is interested I'd be happy to very happy to contribute this and add the unit tests needed to cover it.  I've always wanted pickle support for Keras models, but I've never been able to come up with a good solution

**Comment by fchollet** [comment]
Sounds good -- this is definitely something that can be useful. Please open a PR.
