### ISSUE TITLE
Cannot load nested model / model with sub-model

### ISSUE THREAD

**Issue by a-mch** [keras-team/keras#19559]
Loading a previously saved Keras model, which contains a sub-model, throws an error.

Here is a very basic example. This may or may not be related to [#19304](https://github.com/keras-team/keras/issues/19304)

```
# Create basic sub-model
input_1 = keras.layers.Input(shape=(1,))
model_1 = keras.models.Model(input_1, input_1)

# Create outer model
input_2 = keras.layers.Input(shape=(1,))
output_2 = model_1(input_2)
model_2 =  keras.models.Model(input_2, output_2)

# Save
model_2.save('model.keras')

# Load
keras.models.load_model('model.keras')
```

Error message is:
functional.py", line 556, in get_tensor
    layer_output_tensors = layer._inbound_nodes[node_index].output_tensors
                           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
IndexError: list index out of range

Saving and loading `model_1` works fine.

Keras version: 3.2.1
Backend: pytorch 2.1.2+cu121

**Comment by fchollet** [comment]
Thanks for the report. This issue has been fixed some time ago. You can install keras-nightly to get the fix.
