### ISSUE TITLE
Support for np.vectorize?

### ISSUE THREAD

**Issue by jonbarron** [keras-team/keras#19550]
Hi all, `np.vectorize` (https://numpy.org/doc/stable/reference/generated/numpy.vectorize.html) is *extremely useful*, it basically provides all of the functionality as jax.vmap but with a much easier to understand interface. I have a lot of JAX code that I can't run in Keras 3 because `keras.ops` doesn't have `vectorize()`. Is this something you could add?

**Comment by fchollet** [comment]
Also, note that Keras currently has `ops.vectorized_map`, which can accomplish the same. We'll add `vectorize` in a bit.

**Comment by fchollet** [comment]
Added `ops.vectorize` with `signature` argument.
