### ISSUE TITLE
Complex numbers?

### ISSUE THREAD

**Issue by carlthome** [keras-team/keras#1956]
Does Keras support complex numbers? For example, given FFT data, is there a natural way of including both the magnitudes and phases of the FFT?

My current model looks like this, but only handles magnitudes at the moment:

``` Python
model = Sequential()
model.add(LSTM(input_dim=n, output_dim=n, return_sequences=True))
model.add(LSTM(input_dim=n, output_dim=n, return_sequences=True))
model.add(LSTM(input_dim=n, output_dim=n, return_sequences=True))
model.add(TimeDistributedDense(input_dim=n, output_dim=n))
model.add(Activation('sigmoid'))
model.compile(loss='mean_squared_error', optimizer='rmsprop')
```

Is it sensible to double the input pattern size and just input all bins' magnitudes and phases as floats? Does this preserve the structure of the complex numbers or would it turn out completely bonkers?

**Comment by carlthome** [comment]
Any thoughts on this? Is it possible to double the input pattern size and use the additional neurons for phase information? Does this preserve the structure of the complex numbers or would it be completely bonkers?

**Comment by carlthome** [comment]
Simply concatenating the real and imaginary parts and doubling the model's neurons works fine.

**Comment by drewm1980** [comment]
@carlthome Could this be re-opened and labeled as an enhancement request or something?

Tensorflow supports complex numbers, although the api is unstable right now. Probably Theano too, though I haven't tried yet. Several recent deep learning paper dealing with rotation equivariance can't be implemented in keras cleanly yet due to lack of complex number support.

Thanks!

**Comment by Keerthikan** [comment]
@carlthome I am currently in the same situation, and what "other frameworks" are you using?

**Comment by wzm2256** [comment]
Please reopen the issue.
I think its necessary to use K.variable(a, dtype=complex), or K.variable(a, dtype=tf.complex64), but currently this feature is not supported

**Comment by zwep** [comment]
What is the status of this issue atm?

**Comment by thecosta** [comment]
Any update on this would request would be much appreciated!

**Comment by OmranKaddah** [comment]
Updates please

**Comment by NEGU93** [comment]
Please, I would like also for keras to support complex numbers.

**Comment by musicbyjing** [comment]
What's the status of this issue?

**Comment by carlthome** [comment]
Alright people. Here we go! :smiley:
