### ISSUE TITLE
`keras.ops.nan_to_num` doesn't have a `nan` argument

### ISSUE THREAD

**Issue by jonbarron** [keras-team/keras#19573]
nan_to_num() only has the ability to output `0` when the input is nan, but numpy's nan_to_num() has a handy `nan=0` kwarg that lets you turn nans into any float you like. Can this be added? It's hard to approximate this behavior without having this functionality, the closest strategy I'm aware of is something like computing `nan_to_num(x - nan) + nan` but this will presumably have some weird numerical behavior if nan is large.

**Comment by innat-asj** [comment]
https://github.com/keras-team/keras/blob/29130d3a14d4b673339cbdaddb464359b84ba9c7/keras/backend/numpy/numpy.py#L692

**Comment by fchollet** [comment]
Good call. This is now added. I also added the related arguments `posinf` and `neginf`.
