### ISSUE TITLE
There seem some differences between the source code from PyPI and that tagged with v3.2.1 in GitHub.

### ISSUE THREAD

**Issue by Zhaopudark** [keras-team/keras#19587]
Hello. Thank you for your contributions and maintenance for the best Keras.

A few days ago, I posed an issue [#19471](https://github.com/keras-team/keras/issues/19471). And now I find it has been solved in the latest version keras-3.2.1.

That's a problem with `keras.backend.clear_session` function. So, I try to find the latest source code to check the modification. 

However, I found the source code of keras-3.2.1 from PyPI is different from the one with tag v3.2.1 from GitHub. Specifically, the `keras.backend.clear_session` function in PyPI's  keras-3.2.1 source code is located in `keras/src/backend/common/global_state.py` while the one from tag v3.2.1 of repo is located in `keras/backend/common/global_state.py`. The differences are as:
```diff
diff --git a/./pypi_keras_321/keras/src/backend/common/global_state.py b/./github_tag_keras_321/keras/backend/common/global_state.py
index 65fb60c..1f47636 100644
--- a/./pypi_keras_321/keras/src/backend/common/global_state.py 
+++ b/./github_tag_keras_321/keras/backend/common/global_state.py
@@ -46,7 +46,7 @@ def clear_session():
     GLOBAL_SETTINGS_TRACKER = threading.local()

     if backend.backend() == "tensorflow":
-        from keras.src.utils.module_utils import tensorflow as tf
+        from keras.utils.module_utils import tensorflow as tf

         tf.compat.v1.reset_default_graph()
         if tf.executing_eagerly():
@@ -60,7 +60,4 @@ def clear_session():

         # reset's torchdynamo's cache so that  cached guards, compiled fn, etc
         # do not persist between clear_session() calls
-        dynamo.reset()
-
-    # Manually trigger garbage collection.
-    gc.collect()
\ No newline at end of file
+        dynamo.reset()
\ No newline at end of file
```

I'm a little confused about these differences. 

Thanks in advance.

**Comment by sachinprasadhs** [comment]
Hi, The issue has been resolved with the commit here https://github.com/keras-team/keras/pull/19530.

Now you can see the file listed under` keras/src/backend/common/global_state.py` in the 3.3.2 release. 
https://github.com/keras-team/keras/blob/e123d898349fa768f515544d0b670d0c3d56bcba/keras/src/backend/common/global_state.py#L24

**Comment by Zhaopudark** [comment]
Thanks. 😆 I see.
