### ISSUE TITLE
Misspelled link.

### ISSUE THREAD

**Issue by albert-github** [keras-team/keras#19593]
https://github.com/keras-team/keras/blob/3ebb36fce26c37b5095853a605f07c5f18b57597/SECURITY.md?plain=1#L62

The link reference should not be:
```
(#using-Keras-securely)
```
but
```
(#using-keras-securely)
```
so with lowercase `k`.

(I'm not using Keras or having a fork of it so no PR from my side).

**Comment by fchollet** [comment]
Fixed.
