### ISSUE TITLE
Conv3D crash when the data_format is 'channels_first' and using Tensorflow backend

### ISSUE THREAD

**Issue by AGFACBNNR** [keras-team/keras#19591]
According to the [document](https://keras.io/api/layers/convolution_layers/convolution3d/) of Conv3D in keras website, Conv3D should accept inputs with data format 'channels_first' or 'channels_last'.
While in this [colab](https://colab.research.google.com/drive/1LO942GsMBb_lXxvodBLj4VwRRK_p8yOl?usp=sharing), I got the following results. 
![image](https://github.com/keras-team/keras/assets/20224019/99613a56-6c19-4db3-a38e-273791df05ed)

**Comment by fchollet** [comment]
According to the error message, the lack of support is only on CPU -- GPU should work fine. There's no CPU kernel for channels_first Conv3D. We can't fix that on the Keras side except by doing a transpose/counter-transpose in that case, which would be very inefficient.

**Comment by AGFACBNNR** [comment]
Got it. I'll try it on GPU.

**Comment by AGFACBNNR** [comment]
Surprisingly, I found that sometimes Conv3D can get an output when data_format is 'channels_first'.
In this [colab](https://colab.research.google.com/drive/1BUYEDhCGHguSYxZ_0pZuQQM1i2CeQk5G?usp=sharing), l1 and l2 have the same parameters, except for 'groups'. However, l1 can generate an output while l2 meets an error, as shown in the following. This is very strange. I thought 'groups' would not influence the data format of inputs.
![image](https://github.com/keras-team/keras/assets/20224019/a145f62f-60e3-4de6-8985-eee7efb436ca)
