### ISSUE TITLE
imdb.load_data function returns a python list instead of ndarray object

### ISSUE THREAD

**Issue by amletodisalle** [keras-team/keras#19596]
In Keras 3.2.1 the imdb.load_data function returns a Python list instead of a ndarray object as described in the function documentation. 
In Keras 2.15 the train and test data are converted to a ndarray using the following statements before returning the tuple.
x_train, y_train = np.array(xs[:idx], dtype="object"), labels[:idx]
x_test, y_test = np.array(xs[idx:], dtype="object"), labels[idx:]

In Keras 3.2.1 the conversion is not applied, i.e., 
x_train, y_train = xs[:idx], labels[:idx]
x_test, y_test = xs[idx:], labels[idx:]

**Comment by SuryanarayanaY** [comment]
Hi @amletodisalle ,

Thanks for reporting this. I have proposed a fix for it.
