### ISSUE TITLE
Add support for jnp.linalg.slogdet

### ISSUE THREAD

**Issue by jonbarron** [keras-team/keras#19605]
Could `slogdet()` please be added? It seems to exist in JAX (https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.linalg.slogdet.html) and pytorch (https://pytorch.org/docs/stable/generated/torch.linalg.slogdet.html).

**Comment by fchollet** [comment]
It appears to be built-in in all backend frameworks so that's an easy addition.

**Comment by fchollet** [comment]
Done
