### ISSUE TITLE
The source code URL in the documentation leads to a non-existent page.

### ISSUE THREAD

**Issue by shadi-danhash-elte** [keras-team/keras#19620]
Issue:
The source code URL in some documentation pages leads to a non-existent page.

Reproduction Steps:

- Go to: https://keras.io/api/layers/core_layers/embedding/
- Click on [source]

Expected Behavior:
The source link should direct to https://github.com/keras-team/keras/tree/v3.3.2//keras/src/layers/core/embedding.py#L14 instead of https://github.com/keras-team/keras/tree/v3.3.2//keras/layers/core/embedding.py#L14.

**Comment by fchollet** [comment]
Thanks for the report. We've updated it, the website will reflect the new links within 48 hours.
