### ISSUE TITLE
keras.ops.cross doesn't propagate input sizes

### ISSUE THREAD

**Issue by jonbarron** [keras-team/keras#19631]
Hi all, there seems to be an issue with the implementation of keras.ops.cross
https://github.com/keras-team/keras/blob/b41f687d7b0760ce42c158566e4f6793962db5ba/keras/src/backend/tensorflow/numpy.py#L929
where it doesn't propagate the shapes of the inputs into the output: they should be the same, but instead they are `<unknown>`

Here's a repro:

```
import os

os.environ['KERAS_BACKEND'] = 'tensorflow'

import numpy as np
import keras.ops as jnp
import tensorflow as tf

x, y = np.arange(6, dtype=np.float32).reshape((2, 3))

@tf.function
def fn_tf(x, y):
  z = tf.linalg.cross(x, y)
  print(z.shape)
  return z

fn_tf(x, y);


@tf.function
def fn_tf(x, y):
  z = jnp.cross(x, y)
  print(z.shape)
  return z
  
fn_tf(x, y);
```
Running this gets you the following in stdout:
```
(3,)
<unknown>
```

So tensorflow is correctly propagating x and y's shape to z, but keras.ops isn't! This is causing a problem for me because it breaks the ability to compile functions that use keras.ops.cross with tf.function.

**Comment by fchollet** [comment]
Thanks for the report, this is now fixed at HEAD. Note, `tf.linalg.cross` and `np.cross` aren't the same thing -- they have different signatures, different assumptions, and different behaviors. They only have partial overlap.
