### ISSUE TITLE
RaggedTensor

### ISSUE THREAD

**Issue by markub3327** [keras-team/keras#19646]
Hi @fchollet,

I try to implement Embedding layer with RaggedTensor in TF 2.16.1:

    inputs = tf.keras.layers.Input(shape=[None], dtype=tf.int64, ragged=True)
    x = tf.keras.layers.Embedding(input_dim=vectorize_layer.vocabulary_size(), output_dim=16)(inputs)
    m = tf.keras.Model(inputs=inputs, outputs=x)

where is vectorize_layer = tf.keras.layers.TextVectorization(..., ragged=True). I need a different size of sentences as input to the model. For more info here is docs: https://www.tensorflow.org/guide/ragged_tensor#tensorflow_apis

The issue is:
> TypeError                                 Traceback (most recent call last)
> Cell In[6], line 1
> ----> 1 inputs = tf.keras.layers.Input(shape=[None], dtype=tf.int64, ragged=True)
>       2 x = tf.keras.layers.Embedding(input_dim=vectorize_layer.vocabulary_size(), output_dim=16)(inputs)
>       3 m = tf.keras.Model(inputs=inputs, outputs=x)
> 
> TypeError: Input() got an unexpected keyword argument 'ragged'

Thanks for your reply.

**Comment by fchollet** [comment]
Keras 3 does not support Ragged tensors at this time. You should drop the `ragged` argument.

**Comment by markub3327** [comment]
It is not an option that I need. Does not exist the path to I can solve it? I would like to have a different sentence length. Without padding it is consuming the memory unnecessarily. Thanks.

**Comment by fchollet** [comment]
You can bucket your inputs by sequence length and reduce your batch size in order to minimize padding requirements. With small batch sizes and sufficient bucketing padding becomes pretty much unnecessary.

**Comment by sachinprasadhs** [comment]
@markub3327 , Could you please mark the issue as closed if you don't have any additional questions, for support on RaggedTensors, you can track it here https://github.com/keras-team/keras/issues/18414

**Comment by markub3327** [comment]
Ok. Thank you.
