### ISSUE TITLE
TextVectorization does not convert Cyrillic characters to lowercase

### ISSUE THREAD

**Issue by Ybisalt** [keras-team/keras#19668]
keras.layers.TextVectorization does not convert Cyrillic characters to lowercase with 'lower_and_strip_punctuation'.
Deprecated keras.preprocessing.text.Tokenizer does this.

```
#==========================================

from tensorflow.keras.layers import TextVectorization

tokenizer = TextVectorization(split='character', standardize='lower_and_strip_punctuation')

tokenizer.adapt(["Zz, Aa"])   # Latin
print(tokenizer.get_vocabulary())   # ['', '[UNK]', 'z', 'a', ' ']

tokenizer.adapt(["Яя, Аа"])   # Cyrillic
print(tokenizer.get_vocabulary())   # ['', '[UNK]', 'я', 'а', 'Я', 'А', ' ']

from tensorflow.keras.preprocessing.text import Tokenizer  # deprecated
tokenizer = Tokenizer(char_level=True)
tokenizer.fit_on_texts(["Яя, Аа"])   # Cyrillic
print(tokenizer.index_word)   # {1: 'я', 2: 'а', 3: ',', 4: ' '}

#==========================================
```

**Comment by fchollet** [comment]
The lowercasing is simply does via the TensorFlow operation `tf.strings.lower`, and since it needs to be a TF op, we are not at liberty to change it. You could open the same issue on the TensorFlow repo instead. A workaround you could use is to expressing lowercasing via a regex and then use `tf.strings.regex_replace`, inside your own `standardize` function passed to `TextVectorization`.

**Comment by Ybisalt** [comment]
Can someone check if TextVectorization does pass the encoding argument to tf.strings.lower() ?

**Comment by mehtamansi29** [comment]
Hi @Ybisalt -

TextVectorization doesn't pass the encoding argument to tf.strings.lower(). But you can create custom_standardize method using tf.string.lower() and pass in standardize argument inside TextVectorization.
Here example will help you regarding the same. 

```
def custom_standardize(text):
    text = tf.strings.lower(text,encoding='utf-8')
    return text
tokenizer = TextVectorization(
    split='character',
    standardize=custom_standardize
)
tokenizer.adapt(["Яя, Аа"])  # Cyrillic
print(tokenizer.get_vocabulary())  #['', '[UNK]', 'я', 'а', ' ']
```
