### ISSUE TITLE
No module named 'keras.src.engine'

### ISSUE THREAD

**Issue by UmerElsaharty** [keras-team/keras#19677]
i got the error in the title while importing libraries for training my Vit model , i tried to install vit_keras , tensorflow_addons , keras-nightly and made sure that the KERAS_BACKEND environment variable is set to "tensorflow". and still shows up 
i train my model on kaggle .

**Comment by sachinprasadhs** [comment]
@UmerElsaharty , Could you please provide the reproducible code.

vit_keras is not released by Keras team, you can probably reach out to the author mentioned in the PyPi page of package.

**Comment by UmerElsaharty** [comment]
sure here is the code : 

https://github.com/xRedik/Master_Thesis/blob/main/code/model/VIT/VIT_model.ipynb

**Comment by sachinprasadhs** [comment]
Could you please upgrade the Keras version using `pip install -U keras` and use the keras import directly as import keras, which uses latest Keras.

**Comment by UmerElsaharty** [comment]
the error is still there , a message has been shown to me saying that the pip cant install some components of the packages
can this has a relation with the error ?

**Comment by sachinprasadhs** [comment]
You need to maually resolve those version conflict dependency, but I don't think the error is due to Keras, check with `vit_keras`, which we are not releasing.

**Comment by UmerElsaharty** [comment]
i think the issue is with kaggle itself  because the code is running so well on google colab , could you please tell me recommendation of how to check with vit_keras !

**Comment by sachinprasadhs** [comment]
You can contact author mentioned in the page here https://pypi.org/project/keras-vit/ and close thew issue here. Thanks!

**Comment by Adamya113** [comment]
This solves the issue:
`pip uninstall tensorflow tf-keras tensorflow-probability`
then
` pip install tensorflow==2.15.0 tf-keras==2.15.0 tensorflow-probability==0.22 `

**Comment by mw66** [comment]
```
pip install tensorflow==2.15.1 tf-keras==2.15.1
```

worked as well.
