### ISSUE TITLE
Add backend-agnostic worker-process data loading

### ISSUE THREAD

**Issue by LarsKue** [keras-team/keras#19692]
Worker-process data loading is an integral part of many training applications. Exposing the API provided in `keras.utils.PyDataset` to backends other than tensorflow would be a valuable addition.

As an alternative, flags like `workers`, `use_multiprocessing`, and `max_queue_size` could be added to `Model.fit`, but this may be confusing when the user passes data that is fully in memory.

**Comment by fchollet** [comment]
> Exposing the API provided in keras.utils.PyDataset to backends other than tensorflow would be a valuable addition.

`PyDataset` is usable with any backend. Nothing about it is TF-specific. Did you encounter an issue?

**Comment by LarsKue** [comment]
Interesting, for me, the import does not work under the torch backend. I thought this was the intended behaviour:

```bash
conda create -y -n test-py-tensorflow python=3.11
conda activate test-py-tensorflow
pip install -U tensorflow keras
conda env config vars set KERAS_BACKEND=tensorflow
conda deactivate
conda activate test-py-tensorflow
python -c "import keras.utils.PyDataset"
```
works fine, whereas

```bash
conda create -y -n test-py-torch python=3.11
conda activate test-py-torch
pip install -U keras
conda install torch torchvision torchaudio cpuonly -c pytorch
conda env config vars set KERAS_BACKEND=torch
conda deactivate
conda activate test-py-torch
python -c "import keras.utils.PyDataset"
```
yields

```py3
ModuleNotFoundError: No modle named 'keras.utils.PyDataset'
```


After doing some more testing in a clean env, this is now actually the case for both tensorflow and torch on all my machines. Perhaps the export is broken?

**Comment by fchollet** [comment]
The import pattern should be `from keras.utils import PyDataset` or `import keras; keras.utils.PyDataset`.

**Comment by LarsKue** [comment]
Sorry, that was a mistake I put in when creating a minimal example.

The issue seems to be a little bit deeper. When I install keras with conda, I get the above issue:

```py3
from keras.utils import PyDataset
>>> ImportError: cannot import name 'PyDataset' from 'keras.utils'
```

When I install with pip (as recommended by keras), I instead now get:

```py3
ModuleNotFoundError: No module named 'packaging'
```

**Comment by SuryanarayanaY** [comment]
Hi @LarsKue ,

Please install the packaging module using pip install packaging and try again.

**Comment by SuryanarayanaY** [comment]
The library packaging is a dependency for Keras. Please check here.
https://github.com/keras-team/keras/blob/da83683f5e92fa24a0ad7bf5dc034ea596346d21/requirements-common.txt#L20

**Comment by LarsKue** [comment]
@SuryanarayanaY thanks, this fixes the issue. `packaging` should probably be auto-installed when running `pip install -U keras` though. Would also be nice to have the conda repos updated so that the latest torch-compatible keras version is newer than 3.1.0, which has the issue of the missing PyDataset.
