### ISSUE TITLE
Resizing layer meets division by zero crash with jax backend

### ISSUE THREAD

**Issue by AGFACBNNR** [keras-team/keras#19725]
As shown in this [colab](https://colab.research.google.com/drive/1P-z9KrXKhxsxLXgcnT_JJkArHQE--a9q?usp=sharing), Resizing meets a 'division by zero' crash with jax backend.
This is triggered when 'height' is large and crop_to_aspect_ratio=True.
According to the error message, it seems that after the preprocessing in Keras, jax receives an image whose dimension list contains a zero, which is directly used as a divisor in jax.
Currently the output is:
![1715930082639](https://github.com/keras-team/keras/assets/20224019/352c5582-0e49-4e8e-9a10-c4c04b92112b)
where we can observe that the API can execute successfully when  crop_to_aspect_ratio=False or 'height' is small, while meets a crash in the third time.

**Comment by AGFACBNNR** [comment]
The symptom looks similar to issue #19723, but I'm not sure whether the reasons behind are same too.
Besides, I also found this problem in RandomCrop layer. 
Please let me know if you need a code snippet to reproduce the crash in RandomCrop.

**Comment by mehtamansi29** [comment]
Hi @AGFACBNNR 

Thanks for reporting the issue. I have tested the code snippet and reproduces the reported behaviour. Attached [gist](https://colab.sandbox.google.com/drive/1TgLDFTJBf3I2TkDcGiZmn50fOZXfvrlp?resourcekey=0-PyF_IClRt7CNFf_ij1crcg#scrollTo=TfPSad7CAgeU) file for reference.

We will look into the issue and update you the same.

**Comment by sachinprasadhs** [comment]
This issue is now fixed with the above linked PR and here is the working Gist in the `keras-nightly` version [![](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.sandbox.google.com/gist/sachinprasadhs/13dd7921f1f5cd58a6f8b4a4bec09711/jax_resizing.ipynb)
