### ISSUE TITLE
CenterCrop meets a division-by-zero with jax backend

### ISSUE THREAD

**Issue by AGFACBNNR** [keras-team/keras#19723]
As shown in this [colab](https://colab.research.google.com/drive/1e5H7NEdw58OgxScH-PcUgmV1rQMvUxWv?usp=sharing),  I have an image of size (11,3). Using CenterCrop   I can resize it to (7,17) and (5,4), but I meet a crash when trying to resize it to (5,17).
According to the error message, it seems that Keras generates an scaled image of height 0 and passes it to backends.
I've tried to change the backend and the same problem also shows up with tensorflow and torch backend. 
The only difference is that tensorflow and torch checks the existence of 0, while jax directly uses it as a divisor.
Currently the output is:
![1715918255039](https://github.com/keras-team/keras/assets/20224019/2667b137-6eac-4bea-a49b-3b5d33b0beee)

**Comment by mehtamansi29** [comment]
Hi @AGFACBNNR 

Thanks for reporting the issue. I have tested the code snippet and reproduces the reported behaviour. Attached [gist](https://colab.sandbox.google.com/gist/mehtamansi29/9d27d62f369dbb89673b20030e0641f2/19723-centercrop-meets-a-division-by-zero-with-jax-backend.ipynb) file for reference.

We will look into the issue and update you the same.

**Comment by mattdangerw** [comment]
Just running you colab, I actually see a failure on all backends, jax/tf/torch. So this might just be a general bug.

Either way, open for contributions if someone want to take this on. I'll take a look later too to see if its an easy fix.

Thanks for filing!

**Comment by sachinprasadhs** [comment]
Hi, The issue has been fixed and I can see the proper output in the keras-nighlty version, attaching the Gist here for reference [![](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.sandbox.google.com/gist/sachinprasadhs/f2289467afb9e85e93e2e15c9ff483e7/jax_centercrop.ipynb)
