### ISSUE TITLE
"Keras.wrappers" <module not found error> in 'python IDLE 3.12.0'

### ISSUE THREAD

**Issue by minqichen12138** [keras-team/keras#19747]
I was trying to apply a L layer neutral network training and testing with a dataset, however there is some issues when importing keras.wrappers (keras.models and keras.layers were fine when I try to import them) 

In CMD I have exercised:
pip install --upgrade keras
pip install --upgrade tensorflow
pip install --upgrade scikit-learn

pip show keras #version 3.3.3
pip show tensorflow #Version: 2.16.1
pip show scikit-learn #Version: 1.5.0

In python
from keras.models import Sequential #no problem running this code
from keras.layers import Dense #no problem running this code

problem starts here:
from keras.wrappers.scikit_learn import KerasClassifier 
#ModuleNotFoundError: No module named 'keras.wrappers'

from tensorflow.keras.wrappers.scikit_learn import KerasClassifier 
#ModuleNotFoundError: No module named 'tensorflow.keras.wrappers'

from keras.scikit_learn import KerasClassifier
 #ModuleNotFoundError: No module named 'keras.scikit_learn'

I have sklearn also installed,  to use the cross_val_score model, does that conflict with installation package with keras/tensorflows?

**Comment by minqichen12138** [comment]
tried different codes to import keras.wrappers but all failed, the versions of keras, tensorflow and scikit_learn are the most updated, please help xDDDDD

**Comment by chunduriv** [comment]
@minqichen12138,

Could please try to install `scikeras` using `pip install scikeras` and then import `from scikeras.wrappers import KerasClassifier`?

**Comment by minqichen12138** [comment]
> from scikeras.wrappers import KerasClassifier

it works!!! thank you !!!!

**Comment by JAI0705** [comment]
It is still not working for me, I isntalled scikeras but it is still giving errors

**Comment by whitemountainanalytics** [comment]
--------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[20], line 1
----> 1 from scikeras.wrappers import KerasClassifier

File /opt/anaconda3/lib/python3.11/site-packages/scikeras/wrappers.py:35
     33 from scikeras.utils import loss_name, metric_name
     34 from scikeras.utils.random_state import tensorflow_random_state
---> 35 from scikeras.utils.transformers import ClassifierLabelEncoder, RegressorTargetEncoder
     38 class BaseWrapper(BaseEstimator):
     39     """Implementation of the scikit-learn classifier API for Keras.
     40 
     41     Below are a list of SciKeras specific parameters. For details on other parameters,
   (...)
    124         The number of features seen during `fit`.
    125     """

File /opt/anaconda3/lib/python3.11/site-packages/scikeras/utils/transformers.py:12
     10 from sklearn.base import BaseEstimator, TransformerMixin
     11 from sklearn.exceptions import NotFittedError
---> 12 from sklearn.pipeline import make_pipeline
     13 from sklearn.preprocessing import FunctionTransformer, OneHotEncoder, OrdinalEncoder
     14 from sklearn.utils.multiclass import type_of_target

File /opt/anaconda3/lib/python3.11/site-packages/sklearn/pipeline.py:16
     13 import numpy as np
     14 from scipy import sparse
---> 16 from .base import TransformerMixin, _fit_context, clone
     17 from .exceptions import NotFittedError
     18 from .preprocessing import FunctionTransformer

ImportError: cannot import name '_fit_context' from 'sklearn.base' (/opt/anaconda3/lib/python3.11/site-packages/sklearn/base.py)

**Comment by whitemountainanalytics** [comment]
above is on macOS

**Comment by sachinprasadhs** [comment]
@whitemountainanalytics , Could you please create a new issue. Thanks

**Comment by YifeiUSC2023** [comment]
same question
ImportError: cannot import name '_fit_context' from 'sklearn.base' (/opt/anaconda3/lib/python3.11/site-packages/sklearn/base.py)

**Comment by loveenrique** [comment]
> same question ImportError: cannot import name '_fit_context' from 'sklearn.base' (/opt/anaconda3/lib/python3.11/site-packages/sklearn/base.py)

sameeeeeeeeeeeee
