### ISSUE TITLE
ModuleNotFoundError: No module named 'keras.utils.generic_utils'

### ISSUE THREAD

**Issue by rbbks** [keras-team/keras#19744]
I dont know why this code generate this error can you help me ???

from rl.agents import DQNAgent
from rl.memory import SequentialMemory
from rl.policy import LinearAnnealedPolicy, EpsGreedyQPolicy

def build_agent(model, actions):
    policy = LinearAnnealedPolicy(EpsGreedyQPolicy(), attr='eps', value_max=1., value_min=.1, value_test=.2, nb_steps=10000)
    memory = SequentialMemory(limit=1000, window_length=3)
    dqn = DQNAgent(model=model, memory=memory, policy=policy,
                  enable_dueling_network=True, dueling_type='avg', 
                   nb_actions=actions, nb_steps_warmup=1000
                  )
    return dqn

**Comment by fchollet** [comment]
That's a private namespace -- you cannot access it. Perhaps you meant to use `keras.utils`?
