### ISSUE TITLE
Recommendation for writing tests for ModelParallel distribution

### ISSUE THREAD

**Issue by martin-gorner** [keras-team/keras#19757]
A customer mentioned that the ModelPrallel API in Keras is prone to breakage when multiple team members work on the same model. It is easy to make a model or layer modification that impacts the way the LayoutMap regexes match layers and break the ModelParallel Layout map.

We experienced such a breakage ourselves: https://github.com/keras-team/keras/issues/19496

The solution is to write tests for ModelParallel LayoutMaps. Listing layers and their LayoutMaps is not an issue. We document it in the Gemma [distributed training docs for example](https://ai.google.dev/gemma/docs/distributed_tuning). However, it is not clear to me how to turn this into a unit test.

In the Gemma example, scaling layers are not explicitly partitioned by the user, yet, they display the layout PartitionSpec(None,). How should users test that layers that have not been assigned any partition spec explicitly, do not unexpectedly receive one (like happened to us in issue 19496 when LoRA layers unexpectedly received a partition spec).

Also, the error message on a mismatched partition spec was not very helpful.

**Comment by grasskin** [comment]
Would you mind suggesting something here @qlzh727? Thank you!

**Comment by qlzh727** [comment]
You can follow https://github.com/keras-team/keras/blob/6ae7898e4bd464c407de035ed8dc7632eec7d7ee/keras/src/backend/jax/distribution_lib_test.py#L231 as and e2e test example if user would like to verify the weights layout explicitly. If the model is quite large, this will require user to trim down the model size to fit for the hardware limitation.

For layers that receive an layout unexpectly, I think user can catch this via unit test (eg by verify the lora weights is not partitioned.)

**Comment by martin-gorner** [comment]
assuming that the correct way to "verify the weights are not partitioned" is to compare their weight._value.sharding.spec to (None, )
