### ISSUE TITLE
Specifying shape of normal sampling with partially empty keras tensor

### ISSUE THREAD

**Issue by lcs-crr** [keras-team/keras#19766]
Hi,
I’ve been migrating my code from keras 2 using tf to keras 3 based on torch.
For part of my model I need to sample a tensor of shape like Z_mean, where Z_mean is a keras tensor of dynamic batch size and shape (None, 1024, 12).
When I exectute my code (and the minimal working code below) I get the following error:
Traceback (most recent call last):

_File “/lhome/USER/.cache/JetBrains/RemoteDev/dist/8af836b5b190f_pycharm-professional-2024.1.1/plugins/python/helpers-pro/pydevd_asyncio/pydevd_asyncio_utils.py”, line 117, in _exec_async_code
result = func()
File “<‘input’>”, line 1, in 
File “/lhome/USER/PycharmProjects/PROJECT_NAME/venv/lib/python3.10/site-packages/keras/src/random/random.py”, line 27, in normal
return backend.random.normal(
File “/lhome/USER/PycharmProjects/PROJECT_NAME/venv/lib/python3.10/site-packages/keras/src/backend/torch/random.py”, line 37, in normal
return torch.normal(
TypeError: normal(): argument ‘size’ must be tuple of ints, not tuple_

Minimal working code:
`import keras`
`ko = keras.ops`
`Z_mean = keras.Input(shape=(1024, 12), batch_size=None)`
`eps = keras.random.normal(shape=ko.shape(Z_mean))`

Sampling a partially None-shaped tensor worked fine in Keras 2, what am I doing wrong?

**Comment by fchollet** [comment]
You cannot create an eager random tensor with an undefined shape (here, `(None, 1024, 12)`). This has never worked before it is conceptually impossible. I am not sure what setup you are referring to when you say, "this used to work", but in any case that's not it.

You can simply use a layer to do what you describe. Like this.

```python
import keras


class MyLayer(keras.Layer):
    def __init__(self, **kwargs):
        super().__init__()
        self.seed_generator = keras.random.SeedGenerator(seed=1337)

    def call(self, z_mean):
        eps = keras.random.normal(shape=keras.ops.shape(z_mean), seed=self.seed_generator)
        return z_mean + eps


z_mean = keras.Input(shape=(1024, 12))
z_mean_plus_eps = MyLayer()(z_mean)
```

**Comment by lcs-crr** [comment]
Thank you for your reply and a proposed solution. 
I realised that perhaps I simplified my question too much.
When I said that

> Sampling a partially None-shaped tensor worked fine in Keras 2

I was refering to the following "old" code, running on tf==2.10:
`import tensorflow as tf`
`Z_mean = tf.keras.layers.Input(shape=(1024, 12))`
`eps = tf.random.normal(shape=tf.shape(Z_mean))`

If I didn't make a mistake, the keras==3.x equivalent should be:
`import keras`
`Z_mean = keras.Input(shape=(1024, 12))`
`eps = keras.random.normal(shape=keras.ops.shape(Z_mean))`
which, as you pointed out, does not work.
Why so? What would be the working equivalent of the "old" code?

**Comment by fchollet** [comment]
That worked because `tf.random.normal` can operate over symbolic TF tensors. To write equivalent code, just make a `Normal()` Keras layer -- since layers can operate over symbolic tensors too. But in practice I think you're going to want to put more logic in your layer than a single RNG call, for good factoring.
