### ISSUE TITLE
Question: Best practice for direct variable initialization

### ISSUE THREAD

**Issue by LarsKue** [keras-team/keras#19767]
Some layers require explicit initialization of the whole variable tensor. What is the best practice for doing this? Currently, I am passing the tensor as the `value` argument to `keras.initializers.Constant`, but this seems like a hacky work-around, since the docs never explicitly mention using `Constant` with non-floats, and the value is also unnecessarily multiplied with a tensor of ones on initializer call.

For reference, I am doing something like this (there is no built-in initializer for rolling indices):

```py3
class SomeLayer(keras.Layer):
    def build(self, input_shape):
        indices = keras.ops.roll(keras.ops.arange(input_shape[-1]), shift=input_shape[-1] // 2)
        
        self.indices = self.add_variable(shape=input_shape[-1], initializer=keras.initializers.Constant(indices), trainable=False)
```

**Comment by fchollet** [comment]
The most explicit, idiomatic way would be to create an `Initializer` subclass.

```python
@keras.saving.register_keras_serializable("my_package")
class RollInitializer(keras.Initializer):
    def __call__(self, shape, dtype=None):
        return keras.ops.roll(keras.ops.arange(shape[-1]), shift=shape[-1] // 2)


@keras.saving.register_keras_serializable("my_package")
class SomeLayer(keras.Layer):
    def build(self, input_shape):
        self.indices = self.add_variable(shape=(input_shape[-1],), initializer=RollInitializer(), trainable=False)
```

**Comment by james77777778** [comment]
We can also use a lambda expression to initialize, which is how `quantize` is done in `Dense`:
https://github.com/keras-team/keras/blob/master/keras/src/layers/core/dense.py#L553-L568

Note: it is not recommended to use `keras.initializers.Constant` for arrays because it cannot release the `value` inside:
https://github.com/keras-team/keras/blob/master/keras/src/initializers/constant_initializers.py#L31

In your case:
```python
class SomeLayer(keras.Layer):
    def build(self, input_shape):
        indices = keras.ops.roll(
            keras.ops.arange(input_shape[-1]), shift=input_shape[-1] // 2
        )

        self.indices = self.add_variable(
            shape=input_shape[-1],
            initializer=lambda shape, dtype: indices,  # <-----
            trainable=False,
        )
```

**Comment by LarsKue** [comment]
Thank you for the suggestions. As a feature request, would it be possible for keras to allow passing the initializing value directly? I think this would be a nice addition to reduce the verbosity of the interface. I.e.,

```py3
self.constants = self.add_weight(shape=..., initializer=7)
indices = keras.ops.roll(....)
self.indices = self.add_weight(shape=..., initializer=indices)
```

to replace

```py3
self.zeros = self.add_weight(shape=..., initializer=keras.initializers.Constant(7))
indices = keras.ops.roll(...)
self.indices = self.add_weight(shaep=..., initializer=lambda shape, dtype: indices)
```

**Comment by LarsKue** [comment]
I see some possibility for this within `initializers.get(initializer)`. I could whip up a PR if such a feature would be appreciated.

**Comment by grasskin** [comment]
Thank you @LarsKue! Do you think we should add this @fchollet?

**Comment by nkovela1** [comment]
@fchollet Do you have any thoughts on this feature request?
