### ISSUE TITLE
ops.linspace broken in Tensorflow when num is a tf.Tensor

### ISSUE THREAD

**Issue by gustavoeb** [keras-team/keras#19772]
When using ops.linspace with Tensorflow backend, if the `num` argument is a tf.Tensor the code will break here:
https://github.com/keras-team/keras/blob/a243d91e43b4c43fe8d184b541b608b6ddd80f71/keras/src/backend/tensorflow/numpy.py#L1332

Because `start` and `stop` are required to be `floats`, `num` is required to be `int` and TF won't auto cast a tf.Tensor, computing the step like this will cause the issue.

To test you can run this:
`ops.linspace(0.0, 1.0, ops.conver_to_tensor(10))`

And a mere cast should do for the fix.

**Comment by SuryanarayanaY** [comment]
Hi @gustavoeb ,

Thanks for the report. I have reproduced the issue and attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/4bab4d097a48b487f32c28a1e89a2d9f/19772.ipynb) here. The Op `linspace` is breaking when the value of `num` is `int` or `float`

**Comment by grasskin** [comment]
Hi @gustavoeb - thank you for reporting this. Would you be interested in contributing the fix? 

I believe it should just be adding `num = convert_to_tensor(num, dtype=tf.int64)` under https://github.com/keras-team/keras/blob/a243d91e43b4c43fe8d184b541b608b6ddd80f71/keras/src/backend/tensorflow/numpy.py#L1323 but you would have to confirm execution works.

**Comment by gustavoeb** [comment]
@grasskin seems like it is already close now, maybe next time :)
