### ISSUE TITLE
Most of the outbound links are broken in Tensorflow documentation

### ISSUE THREAD

**Issue by kelixirr** [keras-team/keras#19784]
Hello, I noticed that most of the outbound links mentioned in the Tensorflow documentation are broken. I am getting this: 

```404 - page not found
The 
v3.3.3 branch of  Keras

 does not contain the path 
keras/metrics/f_score_metrics.py.
```
For example, you can visit this link below and click on view the source on GitHub, you will be taken to the 404 page. It seems the directories are moved to a new location while links are not updated. 
https://www.tensorflow.org/api_docs/python/tf/keras/metrics/F1Score

**Comment by chunduriv** [comment]
@kelixirr, Currently there is a known bug and it will be fixed soon.

**Comment by chunduriv** [comment]
@kelixirr,

The issue has been fixed. Please see the attached screenshots for more details.

![image](https://github.com/keras-team/keras/assets/74177924/39715b29-e5c6-4df0-b990-4fa594e25327)

![image](https://github.com/keras-team/keras/assets/74177924/9af299cc-b047-455d-9ce1-f0f99c8ef1fb)

**Comment by kelixirr** [comment]
Yes. I checked a few others too. It is working now. I hope all the other links are working as well.
