### ISSUE TITLE
[Question] When is it absolutely necessary to use a `Lambda` layer?

### ISSUE THREAD

**Issue by miticollo** [keras-team/keras#19791]
Reading Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow by Aurélien Géron I noticed that to use a preprocess function (like [`preprocess_input`](https://github.com/keras-team/keras/blob/f6c4ac55692c132cd16211f4877fac6dbeead749/keras/src/applications/resnet.py#L497-L506)) it is necessary to put it inside a `Lambda` layer if you build a `Sequential` model otherwise an [error](https://github.com/keras-team/keras/blob/f6c4ac55692c132cd16211f4877fac6dbeead749/keras/src/models/sequential.py#L94-L99) is raised.

Now, the question is **this requirement is required also for `Functional` model?**

It seems no. Digging into Keras' repos I found three examples:
- [DeeplabV3Plus](https://github.com/keras-team/keras-core/blob/3a464f904dc8dd09de9c51d248a7fe7c575d7f3e/examples/keras_io/vision/deeplabv3_plus.py#L183-L209) that uses `preprocess_input` without `Lambda`.
- [video_transformers](https://github.com/keras-team/keras-core/blob/3a464f904dc8dd09de9c51d248a7fe7c575d7f3e/examples/keras_io/vision/video_transformers.py#L130-L143) like the previous one.
- [ddim](https://github.com/keras-team/keras-core/blob/3a464f904dc8dd09de9c51d248a7fe7c575d7f3e/examples/keras_io/tensorflow/generative/ddim.py#L201) use `Lambda` (maybe?) because `preprocess_input` occurs inside a `Sequential` model.

Furthermore, I discovered that [Functional API can also include raw Keras 3 ops](https://github.com/keras-team/keras/blob/v3.3.3/keras/src/models/functional.py).

If possible, I would want to add to my `Functional` model `tf.expand_dims`, but in this case I suppose(?) that I must use a `Lambda` layer. To be sure I could always use a `Lambda` layer (or even better a custom one), but I would want to understand when a `Lambda` layer is strictly necessary.

**Comment by sachinprasadhs** [comment]
`Lambda` layer allows you to apply custom function to the input data, ex: `preprocess_input`, 
One of the example from the sequential model is https://keras.io/examples/generative/ddim/#kernel-inception-distance

`Lambda` can be used in both `Functional` and `Sequential` models. 
For more details on Lambda you can refer https://keras.io/api/layers/core_layers/lambda/

You can also use preprocess_input in the custom function like below.

```
def preprocess(image, label):
      resized_image = tf.image.resize(image, [224, 224])
      final_image = keras.applications.xception.preprocess_input(resized_image)
      return final_image, label
```
