### ISSUE TITLE
Clearer errors for `add_metric`

### ISSUE THREAD

**Issue by DLumi** [keras-team/keras#19804]
1) It's really weird to drop `add_metric` when you still have `add_loss`, but alright
2) If you are not planning to improve compatibility with 'niche functionality' of the past, then please produce clearer errors that it does not work. Right now when you try passing any parameters to `add_metric`, it fails with a type error:

```
TypeError: Exception encountered when calling MyMetric.call().

Layer.add_metric() takes 1 positional argument but 2 were given

Arguments received by MyMetric.call():
  • y_true=tf.Tensor(shape=(2, 6), dtype=int32)
  • y_pred=tf.Tensor(shape=(2, 8), dtype=int32)
  • args=<class 'inspect._empty'>
  • kwargs=<class 'inspect._empty'>
```

From this error it's not exactly clear that the method:
1) takes no arguments
2) is deprecated / not implemented

To actually understand that the method is not even supposed to work you have to either inspect the source code, or rummage through the github, none of which is super obvious. 

Suggestions: 
1) remove the method altogether (if it's not supported, why have it in the first place?)
2) make it accept anything (*args, **kwargs), and then throw a `NotImplementedError`, possibly add suggestions on how to use the updated API instead

A Colab notebook for reference: https://colab.research.google.com/drive/1FO-GstSFwU0V0cTeCCjtCuL2NUmFB2tq

**Comment by Grvzard** [comment]
This is a legacy problem of keras 2, keras 3 does not have this problem.

**Comment by grasskin** [comment]
Hi @DLumi, thank you for filing this issue. I agree this could be more readable. The method is being kept for backwards compatibility but a better error is an improvement here.
