### ISSUE TITLE
ValueError when trying to load a .keras model created using Functional API

### ISSUE THREAD

**Issue by iamsoroush** [keras-team/keras#19803]
create an encoder-decoder model:

```Python
def get_encoder(input_shape):
    input_tensor = keras.Input(input_shape, dtype='float32')
    x1 = keras.layers.Conv2D(8, 3, padding='same')(input_tensor)
    x2 = keras.layers.Conv2D(16, 3, padding='same')(x1)
    return keras.Model(input_tensor, [x1, x2])

def get_decoder(inputs):
    x1 = keras.layers.Conv2D(8, 3, padding='same')(inputs[0])
    x2 = keras.layers.Conv2D(8, 3, padding='same')(inputs[1])
    x = keras.layers.Concatenate()([x1, x2])
    return keras.Model(inputs, x)


input_shape = (512, 512, 3)
encoder = get_encoder(input_shape)

inputs = keras.Input(input_shape, dtype='uint8')
encoded = encoder(inputs)
x = keras.layers.Conv2D(4, 3, padding='same')(encoded[-1])
x = keras.layers.Conv2D(4, 3, padding='same')(x)
skips = encoded[:-1]
skips.append(x)
decoder = get_decoder(skips)
decoded = decoder(skips)
model = keras.Model(inputs, decoded)
model.summary()
```

extract a bottleneck model and save it as a `.keras` model:
```Python
bottleneck = keras.Model(model.layers[2].input, model.layers[3].output)
bottleneck.save('model.keras')
```

when trying to load the saved model, throws an error:
```Python
loaded = keras.saving.load_model('model.keras')

ValueError: Layer node index out of bounds.
inbound_layer = <Conv2D name=conv2d_45, built=True>
inbound_layer._inbound_nodes = []
inbound_node_index = 0
```

**Comment by sachinprasadhs** [comment]
I was able to replicate the reported behavior here https://colab.sandbox.google.com/gist/sachinprasadhs/d40631f9ee4702a0b93a69c143f8c3a6/19803.ipynb

**Comment by Jaimin020** [comment]
I am currently working on this bug

**Comment by iamsoroush** [comment]
any updates?

**Comment by Jaimin020** [comment]
Hi @iamsoroush,
I’m currently working on it, and it will be done in the coming days.

**Comment by mehtamansi29** [comment]
Hi @iamsoroush-

You can use `model.layers[1].output[-1]` instead of `model.layers[2].input` while extract a bottleneck model. Because `model.layers[1].output[-1]` has same tensorshape `KerasTensor shape=(None, 512, 512, 16), dtype=float32` as `model.layers[2].input`.

Attached [gist](https://colab.sandbox.google.com/gist/mehtamansi29/0be3f0b281a683008e0dc104378e9ee2/19803-valueerror-when-trying-to-load-a-keras-model-created-using-functional-api.ipynb) here for the reference.
