### ISSUE TITLE
Error in masked BatchNormalization with > 3 dimensions

### ISSUE THREAD

**Issue by drasmuss** [keras-team/keras#19818]
```
import keras

x = keras.ops.ones((1, 2, 3, 4))
mask = keras.ops.ones((1, 2), dtype="bool")
y = keras.layers.BatchNormalization()(x, mask=mask, training=True)
```
gives
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: Exception encountered when calling BatchNormalization.call().

{{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Incompatible shapes: [1,2,1] vs. [1,2,3,4] [Op:Mul] name: 

Arguments received by BatchNormalization.call():
  • inputs=tf.Tensor(shape=(1, 2, 3, 4), dtype=float32)
  • training=True
  • mask=tf.Tensor(shape=(1, 2), dtype=bool)
```

**Comment by Grvzard** [comment]
According to the example above, I think what we should do in Keras is automatically expand the mask from shape (1, 2) to (1, 2, 3) right?

**Comment by fchollet** [comment]
You should generally make sure that the mask only has one less dimension than the input, e.g. in this case `mask = keras.ops.ones((1, 2, 1), dtype="bool")`

**Comment by pandyah5** [comment]
This raises an exception and explains the mismatch in dimensions. Is this a bug to be fixed on the Keras side? I believe it's more of an expected exception right?

**Comment by Grvzard** [comment]
> Is this a bug to be fixed on the Keras side?

As mentioned above. What we can do is make the exception message clearer.

**Comment by pandyah5** [comment]
Gotcha! I can try modifying it tonight

**Comment by drasmuss** [comment]
I'm not sure if this is under the control of the Keras team, but the docs here https://www.tensorflow.org/guide/keras/understanding_masking_and_padding#mask-generating_layers_embedding_and_masking, explicitly state that masks will be shape `(batch_size, sequence_length)`. It would be nice to update that to clarify that they should actually be `input.ndims - 1`.

**Comment by drasmuss** [comment]
While implementing @fchollet suggested fix here https://github.com/keras-team/keras/issues/19818#issuecomment-2156142266 I ran into a different issue. The mean/variance calculations are incorrect when that mask is specified:
``` python
import keras

x = keras.ops.ones((1, 2, 3, 4))
layer = keras.layers.BatchNormalization()
layer.build(x.shape)
print(layer._moments(x, None))
print(layer._moments(x, keras.ops.ones((1, 2, 1), dtype="bool")))
print(layer._moments(x, keras.ops.ones((1, 2, 3), dtype="bool")))
```
gives output
```
(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 1., 1., 1.], dtype=float32)>, <tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>)
(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([3., 3., 3., 3.], dtype=float32)>, <tf.Tensor: shape=(4,), dtype=float32, numpy=array([12., 12., 12., 12.], dtype=float32)>)
(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 1., 1., 1.], dtype=float32)>, <tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>)
```
We can see that a mask with shape `(1, 2, 1)` gives incorrect mean/variance, but `(1, 2, 3)` gives correct output. It wasn't a problem for me to add trailing size-1 dimensions to the mask, but if I have to add a fully-tiled dimension to all the non-sequence axes of my sequence mask that will dramatically increase the memory usage of the model, as those dimensions are quite large.

Is the intended behaviour for the sequence masks that they need to be fully specified for all dimensions except the last (like `(1, 2, 3)`)? Or should `(1, 2, 1)` be working, and this is just a bug in the mean/variance calculations in `BatchNormalization`?

**Comment by pandyah5** [comment]
@drasmuss That's an interesting observation, given its a tensor of ones, we should not expect a mean greater than 1. I believe the error lies here: https://github.com/keras-team/keras/blob/efaaf85e19113400f23462cbafcef433cd95ad9c/keras/src/layers/normalization/batch_normalization.py#L299

**Comment by pandyah5** [comment]
The reason we are getting a mean of three is as follows:

- If the tensors in Keras behave the same way as NumPy then the mask is being implicitly broadcasted from (1, 2, 1, 1) to (1, 2, 3, 4) in this line: https://github.com/keras-team/keras/blob/efaaf85e19113400f23462cbafcef433cd95ad9c/keras/src/layers/normalization/batch_normalization.py#L303

- As seen from the screenshot above this does not cause any masking and the input remains the same and we get [6, 6, 6, 6].

- However, the sum of weights is 2, because in the tensor of shape (1, 1, 2, 1) we just have two ones hence the 2.

This gives us a mean of 3. @fchollet I'll need some advice over here, but the issue seems like the mask is not doing its job to trim down the input. Let me know if I am on the correct path :)

**Comment by drasmuss** [comment]
#19829 doesn't fix the bug in the mean/variance calculations. Would you rather I open a different issue for that bug?

**Comment by pandyah5** [comment]
HI @drasmuss I would recommend opening a new issue for this to make it more tractable. If possible you could also include the triage information I provided before to provide a lead to the contributors.
