### ISSUE TITLE
Keras 3.0 load h5 model with Orthogonal initializer fails

### ISSUE THREAD

**Issue by mahnehsilla** [keras-team/keras#19828]
Hi guys, 

I'm trying to load an h5 model that was working in earlier versions.

* This is a small part of the h5 file, where you can see (last part of the snippet) a recurrent initializer with a classname of **Orthogonal**.

```
{"name": "decoder_gru0", "class_name": "GRU", "config": {"name": "decoder_gru0", "trainable": true, "return_sequences": true, "return_state": false, "go_backwards": false, "stateful": false, "unroll": false, "implementation": 0, "units": 488, "activation": "tanh", "recurrent_activation": "hard_sigmoid", "use_bias": true, "kernel_initializer": {"class_name": "VarianceScaling", "config": {"scale": 1.0, "mode": "fan_avg", "distribution": "uniform", "seed": null}}, "recurrent_initializer": {"class_name": "Orthogonal", "config": {"gain": 1.0, "seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}
```

* The error returned is:

```bash
  File "..../keras/src/initializers/__init__.py", line 118, in get
    raise ValueError(
ValueError: Could not interpret initializer identifier: {'class_name': 'Orthogonal', 'config': {'gain': 1.0, 'seed': None}}
```

## Addition

I then added the Orthogonal initializer to the custom objects, and it seems to go further, but gets stuck here:

```bash
    raise ValueError(
ValueError: Unrecognized keyword arguments passed to GRU: {'implementation': 0}
```

Any ideas on how to fix this @mehtamansi29 ?

**Comment by mehtamansi29** [comment]
Hi @mahnehsilla -

Thanks for raising the issue. Can you share the code snippet and h5 model with me where you are getting this error ? So I can reproduce it and try to help you on this.

**Comment by james77777778** [comment]
Hey @mahnehsilla 

I have proposed a PR for this issue in #19844 
However, I don't have your h5 model to verify it.  Maybe you could try the branch of my fork to double-check this?

```bash
# Install
pip3 install --no-deps --force-reinstall git+https://github.com/james77777778/keras.git@fix-legacy
```

**Comment by mahnehsilla** [comment]
@james77777778  I tried, and it works, just some other layer crashes, but that one is fine. Thank you.

**Comment by james77777778** [comment]
@mahnehsilla 
Maybe you could provide the complete config file for debugging, if it is not confidential.

**Comment by mahnehsilla** [comment]
> @mahnehsilla Maybe you could provide the complete config file for debugging, if it is not confidential.

I've been modifying the code since yesterday so I can share it and it's easy to reproduce the errors. But some got fixed on the way so I'll wait some more days before raising the issue.
