### ISSUE TITLE
Keras in Google Colab and in Rstudio Python Script

### ISSUE THREAD

**Issue by SantiagoD999** [keras-team/keras#19839]
Good morning, 

Comparing the output of a simple neural network when setting the same specifications (random seeds, network architecture, keras package version ,etc.), I obtain slightly different results when running the code on Google Colab and when running it on the RStudio Python script of an M1 MacBook Air. Nevertheless, when running the code on an Intel MacBook Air the results are the same as the ones obtained on Google Colab. Does anyone know why there is a difference between the outputs of these two MacBooks?

The difference can be seen in: print(mean_squared_error(y_test, model_linear.predict(x_test, verbose=1))). This is the code:

```python
from sklearn.datasets import make_friedman1
from sklearn.model_selection import train_test_split
from keras import *
from sklearn.metrics import mean_squared_error
import numpy as np 

# Set seeds for reproducibility
np.random.seed(1)

# Create dataset
X, y = make_friedman1(n_samples=5000, n_features=5, noise=1, random_state=1)

# Split the data into train and test sets
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=1)

# Set random seed for keras
utils.set_random_seed(1)

# Define the model architecture
model_linear = Sequential([
    layers.Input(shape=(X.shape[1],)),
    layers.Dense(1)
])

# Compile the model
model_linear.compile(loss='mean_squared_error', optimizer='sgd')

# Train the model
model_linear.fit(x_train, y_train, epochs=50, verbose=0)

# Evaluate the model
print(mean_squared_error(y_test, model_linear.predict(x_test, verbose=1)))
```

GOOGLE COLAB: 6.872613224177549
RSTUDIO PYTHON SCRIPT (Intel MacBook Air): 6.872613224177549
RSTUDIO PYTHON SCRIPT (M1 MacBook Air): 6.8726134513483235

Thank you very much.

**Comment by sachinprasadhs** [comment]
Precision error which is in the range of `1e-7` can be safely ignored since it does not cause much difference.

Sometimes the differences can be due to the different Kernels.

**Comment by SantiagoD999** [comment]
Thank you for your reply.

**Comment by sachinprasadhs** [comment]
@SantiagoD999 , Could you please close the issue if you don't have any further question. Thanks
