### ISSUE TITLE
What are the migration replacements for this operations?

### ISSUE THREAD

**Issue by mahnehsilla** [keras-team/keras#19837]
I've not been able to find replacements after reading the migration guide:

* `K.in_train_phase`
* `permute_dimensions` (I guess numpy's transpose goes here?)
* `cast_to_floatx`: seems to have been for converting a data type.
* `ndim`: which I think was computing a rank.

I do see that it was deprecated, [even in the tf side.](https://www.tensorflow.org/api_docs/python/tf/keras/backend/cast_to_floatx)

Can you hint what would be a possible replacement @sachinprasadhs ?

**Comment by fchollet** [comment]
> K.in_train_phase

This hasn't done anything in many years. You just pass a Python boolean `training=` arg when calling models/layers now. This is a Keras 1 API, it was deprecated in 2019.

like, `y = model(x, training=True)`

> permute_dimensions

`ops.transpose`

> cast_to_floatx

`ops.cast`, or if you want the exact same, `ops.cast(x, dtype=keras.config.floatx())`

> ndim

`len(x.shape)`

**Comment by mahnehsilla** [comment]
thank you, that was very useful.
