### ISSUE TITLE
Preprocessing API Deprecated

### ISSUE THREAD

**Issue by kelixirr** [keras-team/keras#19865]
Hello, as I can see in th documentation the APIs within the preprocessing sections are deprecated. What could be the reason? 
https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing. 

Especially, one of the most used APIs: https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/image/ImageDataGenerator. 

Are there any new APIs for them?

**Comment by sachinprasadhs** [comment]
[image_dataset_from_directory](https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/image_dataset_from_directory) is a utility based on tf.data.Dataset, meant to replace the legacy ImageDataGenerator. It takes you from a structured directory of images to a labeled dataset, in one function call. Note that it doesn't perform image data augmentation (which is meant to be done using preprocessing layers).

**Comment by kelixirr** [comment]
Got it.
