### ISSUE TITLE
having error in executing object detection module

### ISSUE THREAD

**Issue by gguy145** [keras-team/keras#19888]
C:\Smart-Traffic-Management-Using-Deep-Learning-master\cnn model>python trained_Model.py
Loaded model from disk
Traceback (most recent call last):
  File "C:\Smart-Traffic-Management-Using-Deep-Learning-master\cnn model\trained_Model.py", line 36, in <module>
    result_x = loaded_model.predict_classes(image)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Sequential' object has no attribute 'predict_classes'. Did you mean: 'predict_step'?

**Comment by mehtamansi29** [comment]
Hi @gguy145- 

Can you try to predict class using loaded_model.predict(image) instead of loaded_model.predict_classes(image) ?
