### ISSUE TITLE
`Sequential`-model for data augmentation within `tf.data.Dataset` with JAX backend not working

### ISSUE THREAD

**Issue by MathiesW** [keras-team/keras#19895]
I want to implement my own data loading pipeline for image data. For data augmentation, I want to use `layers.RandomFlip` and `layers.RandomRotation`. I know from Tensorflow, that you can simply add a `Sequential` model to the `tf.data.Dataset` pipeline. However, this is not possible in Keras 3.0 with JAX backend. It throws the error `NotImplementedError: Cannot convert a symbolic tf.Tensor (concat:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported.`

If I reduce the augmentation pipeline to the bare minimum (i.e. a passthrough via `Sequential([layers.Lambda(lambda x: x)`), the error remains, which leads to the conclusion that the `Sequential`-model within the pipeline causes the problem; without the additional `Sequential`-model, the pipeline works fine.

From the error I understand that it tries to convert the Symbolic Tensor to a numpy array when using JAX backend. When I switch the backend to Tensorflow, it works as intended and I receive rotated and flipped images!

I followed the tutorial on [image data loading](https://keras.io/api/data_loading/image/) and reviewed the code, but unfortunately there is no data augmentation step here.

**Comment by fchollet** [comment]
You cannot use a `Sequential` model with the JAX backend inside a tf.data pipeline. That's because JAX ops are not supported inside a tf.data pipeline.

You can instead do something like:
```python
layers = [...]  # Data augmentation layers with TF support
def augment(x):
    for layer in layers:
        x = layer(x)
    return x

dataset = dataset.map(augment, num_parallel_calls=8)
```
