### ISSUE TITLE
Conv1D on custom shaped data

### ISSUE THREAD

**Issue by Wasim04** [keras-team/keras#19900]
Hi,

Just wondering if there is a way to use Conv1D in a heapix data. That is, it can handle, resolution(nside) and pixel orientation (nested or ring). 

Many Thanks
Wasim

**Comment by mehtamansi29** [comment]
Hi @Wasim04 - 

Healpix stands for Hierarchical Equal Area isoLatitude Pixelization of a sphere where partitioning sphere at higher resolutions. So this partition of sphere surface has different size pixels and which is represented as  2D array. So it is better to use Conv1D and Conv2D both are not suitable for healpix image data. [Conv1D](https://keras.io/api/layers/convolution_layers/convolution1d/) can create convolution on single dimension data while [Conv2D](https://keras.io/api/layers/convolution_layers/convolution2d/) can create convolution on two dimensional data.  

 [JAX library](https://github.com/google-research/spherical-cnn/tree/main?tab=readme-ov-file) is better option to implement spherical CNNs. 

Definitely we can do experiment with Conv1D with healpix data(by projecting MNIST dataset onto HEALPix), but it will not generate good result for large spherical data.

Let me know if you required more details. Thanks..!!

**Comment by Wasim04** [comment]
@mehtamansi29 Thanks for your suggestion. Healpix by design is a 1D array of pixels. Each pixel can carry some value to provide a global localised representation of some data (atmospheric or astrophysical etc) since we can use Theta and Phi as pixel coordinates. The problem arises when these pixels are oriented in a particular way. That is, nested or ring, that I was wondering in my first query. Because a Conv1D will construct a kernel which will be 1D array likey in squared pixel shape and the stride will guide the kernel movement.

I am looking for some suggestions if there is a way to address this pixel orientation in the kernel of a traditional Keras Conv1D. Essentially a kernel that follows a nested or ring scheme. 
Thanks for the jax suggestion, I shall look into it. 

Many Thanks
Wasim

**Comment by mehtamansi29** [comment]
Hi @Wasim04 -

Keras doesn't have direct parameter to address pixel orientation in the kernel, but you can use kernel_initializer to specify weights of kernel should be verified.
