### ISSUE TITLE
Adding `ops.associative_scan`?

### ISSUE THREAD

**Issue by SeKim12** [keras-team/keras#19904]
Hello! 

I was looking for the equivalent of [jax.lax.associative_scan](https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.associative_scan.html). This is an important operation for recent state space models, e.g. [S5](https://arxiv.org/abs/2208.04933), [Mamba](https://arxiv.org/abs/2312.00752).

Maybe it's there and I'm missing it. Otherwise, I could start working on it. Thanks!

**Comment by fchollet** [comment]
Yes, we could definitely add this op. Do you think it can be supported in all backends? Are you able to start a PR?

**Comment by SeKim12** [comment]
From what I could tell, it's supported in [tensorflow](https://www.tensorflow.org/probability/api_docs/python/tfp/math/scan_associative), jax (above), but not yet in PyTorch or Numpy.

I'd be interested in working on this op. I also see a lot of great torch implementations on this thread as well: https://github.com/pytorch/pytorch/issues/95408

**Comment by fchollet** [comment]
This has been added -- thanks for the contribution!
