### ISSUE TITLE
keras tensorflow tf.keras.layers.Lambda issue returns AttributeError: Exception encountered when calling Lambda.call().  'TrackedList' object has no attribute 'items'

### ISSUE THREAD

**Issue by fedhere** [keras-team/keras#19926]
system and versions:
keras.__version__ ->'3.4.1'
tf.__version__ -> '2.16.1'
OS MacOS 12.6 
Chip Apple M2

Problem: I can create a neural network that compiles but keras demands the use of `layers.Lambda()` for custom layers. conversely, the `layers.Lambda()` function returns an 
_AttributeError: Exception encountered when calling Lambda.call().  'TrackedList' object has no attribute 'items'_ 

```python
input_layer = tf.keras.layers.Input(shape=(784,), name="input_layer")
output_layer = tf.keras.layers.Input(shape=(128,), name="output_layer")

def custom_layer(tensor, n_filters):
    return tensor + 2

lambda_layer = tf.keras.layers.Lambda(custom_layer, arguments = [128], name="lambda_layer", 
                                      output_shape = (None, 128))(input_layer)

testnn = keras.Model(input_layer, lambda_layer)

testnn.compile(optimizer = tf.keras.optimizers.Adam(learning_rate=learningrate1),
                          loss=tf.keras.losses.MeanSquaredError())

with tf.device('/device:GPU:0'):
    print(random.seed(10))

    testnn.fit(np.random.randn(78400).reshape((100,784)), 
                np.random.randn(12800).reshape((100,128)), #x,y
                                        epochs= 40,  
                                        batch_size=2,
                                        shuffle=True,
                                        validation_split = 0.2)

``` 
Error happens at the first epoch of training. Full error stack: 

AttributeError                            Traceback (most recent call last)
Cell In[116], line 18
     15 with tf.device('/device:GPU:0'):
     16     print(random.seed(10))
---> 18     testnn.fit(np.random.randn(78400).reshape((100,784)), 
     19                 np.random.randn(12800).reshape((100,128)), #x,y
     20                                         epochs= 40,  
     21                                         batch_size=2,
     22                                         shuffle=True,
     23                                         validation_split = 0.2)

File /opt/anaconda3/envs/replumes/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py:122, in filter_traceback.<locals>.error_handler(*args, **kwargs)
    119     filtered_tb = _process_traceback_frames(e.__traceback__)
    120     # To get the full stack trace, call:
    121     # `keras.config.disable_traceback_filtering()`
--> 122     raise e.with_traceback(filtered_tb) from None
    123 finally:
    124     del filtered_tb

File /opt/anaconda3/envs/replumes/lib/python3.11/site-packages/keras/src/layers/core/lambda_layer.py:115, in Lambda.call(self, inputs, mask, training)
    112 def call(self, inputs, mask=None, training=None):
    113     # We must copy for thread safety,
    114     # but it only needs to be a shallow copy.
--> 115     kwargs = {k: v for k, v in self.arguments.items()}
    116     if self._fn_expects_mask_arg:
    117         kwargs["mask"] = mask

AttributeError: Exception encountered when calling Lambda.call().

'TrackedList' object has no attribute 'items'

Arguments received by Lambda.call():
  • inputs=tf.Tensor(shape=(2, 784), dtype=float32)
  • mask=None
  • training=True

**Comment by fchollet** [comment]
The `arguments` dictionary is supposed to be a dict, but you passed a list, hence the error.

More importantly, what is the point of using a `Lambda` layer here? You're aware that you can just do `x + 2`, right?

Replace

```
def custom_layer(x):
    return x + 2

x = tf.keras.layers.Lambda(custom_layer)(x)
```

With

```
x = x + 2
```

If you have a lot of logic in your `custom_layer` function, just make a layer subclass, which is simpler and strictly better than using a `Lambda`. In general you should never use `Lambda` layer, the only reason they still exist is for backwards compatibility.
