### ISSUE TITLE
Keras Image data loader returns tf.Data object on JAX backend

### ISSUE THREAD

**Issue by mohammad0081** [keras-team/keras#19933]
Hello , i recently decided to use JAX as keras backend for every task i am supposed to do . for some image classification task which needs to load images from directory , i use keras image_dataset_from_directory , but it returns tensorflow data.Dataset object , even on JAX backend . i recently initialized a local work station that tensorflow isnt installed on it , i complete every task Based on JAX and Keras high level APIs . 
for our project which is quarantined only on JAX and Keras , we prefer that Keras image_dataset_from_directory return a JNP.array or something that doesnt involve Tensorflow into the project ( because of our resource policies ) 

correct me if im wrong 
thanks

**Comment by fchollet** [comment]
`tf.data` is the data preprocessing API used by pretty much all JAX projects out there. JAX does not have its own data preprocessing & streaming API.

If you want to load data without installing TF, you can simply pass numpy arrays, or a `keras.utils.PyDataset` instance to your model.

**Comment by mohammad0081** [comment]
Thanks Mr. Chollet , Well Explained
