### ISSUE TITLE
Can't load a saved model, Keras 3.4 regression

### ISSUE THREAD

**Issue by nyh** [keras-team/keras#19959]
When I create a model
```python
base_model = keras.applications.ResNet50V2(include_top=False, weights='imagenet')
base_model.trainable = False
model = keras.Sequential()
model.add(layers.Input(shape=image_size+(3,)))
model.add(layers.RandomFlip("horizontal"))
model.add(layers.RandomRotation(0.1))
model.add(layers.Rescaling(scale=1/127.5, offset=-1))
model.add(base_model)
model.add(layers.GlobalAveragePooling2D())
model.add(layers.Dense(384, activation='relu'))
model.add(layers.Dropout(0.25))
model.add(layers.Dense(7, activation='softmax'))
```
train it, and finally save it to a ".keras" file (in my case using keras.callbacks.ModelCheckpoint), when I try to load it back with 
```
keras.models.load_model("filename.keras")
```
The load_model fails, saying that a "Dense" layer expects one tensor input and got two.

Exactly the same code works on Keras 3.3.3.
Interestingly, when I saved the model on Keras 3.4.1 and then downgraded to Keras 3.3.3, it could read the saved model just fine.

There is a three-month old issue complaining about a similar problem on the Tensorflow github - https://github.com/tensorflow/tensorflow/issues/63853 - but interestingly, on my system I can only reproduce the problem on Keras 3.4 (released just two weeks ago) and Keras 3.3.3 works just fine.

**Comment by fchollet** [comment]
Thanks for the report. Looking into it.

**Comment by fchollet** [comment]
Fixed the bug. The fix will be in the next release. Until then you can keep using 3.3.3, or otherwise refactor your model so that it isn't subject to the bug (e.g. use a Functional instead of a Sequential model).
