### ISSUE TITLE
LAMB optimizer for keras3

### ISSUE THREAD

**Issue by huberb** [keras-team/keras#19965]
Is there any up to date LAMB optimizer implementation for keras3?
Previously I've used tfa.optimizers.LAMB from tensorflow_addons, which is deprecated

I've found tensorflow_models, which has an implementation here : https://www.tensorflow.org/api_docs/python/tfm/optimization/lamb/LAMB

But this seems to be incompatible with keras3:

```
import tensorflow_models as tfm
import keras
import numpy as np

model = keras.Sequential([
    keras.layers.Input(shape=(10,)),
    keras.layers.Dense(10),
    keras.layers.Dense(10),
    keras.layers.Dense(1),
])

opt = tfm.optimization.lamb.LAMB()
model.compile(optimizer=opt, loss='mse')

x = np.random.normal(0, 1, (100, 10))
y = np.random.normal(0, 1, (100, 1))

model.train_on_batch(x, y)
```

ValueError: Could not interpret optimizer identifier: <official.modeling.optimization.lamb.LAMB object at 0x7f3efa4d8890>

**Comment by fchollet** [comment]
I'd recommend writing your own -- it's easy to make new multi-backend optimizers, you just have to implement `build()` (to create the optimizer state variables) and `update_step()`. Here's `Adam`, for example: https://github.com/keras-team/keras/blob/master/keras/src/optimizers/adam.py#L81-L150

**Comment by huberb** [comment]
Thanks, seems doable. I'll give it a try this week and report back

**Comment by huberb** [comment]
Added a PR here: https://github.com/keras-team/keras/pull/19981

**Comment by huberb** [comment]
closed after merge
