### ISSUE TITLE
Keras 3.4.2 release

### ISSUE THREAD

**Issue by serena-ruan** [keras-team/keras#19976]
Hey maintainers, is there any timelines for releasing keras 3.4.2 to include this fix https://github.com/keras-team/keras/pull/19927 ? MLflow CI test on tensorflow 2.16.2 is broken with keras 3.4.1 due to this bug.

**Comment by mehtamansi29** [comment]
Hi @serena-ruan -

For now, you can try to use nightly.

**Comment by serena-ruan** [comment]
Hi @mehtamansi29 Thanks we can use nightly as temp fix, but wondering when will be the next release?

**Comment by mattdangerw** [comment]
@serena-ruan probably within the next month, but no exact date.

I would either pin to an older version, or use nightly for now!

**Comment by VladOnMyOwn** [comment]
Any updates?
