### ISSUE TITLE
Assign doesn't return a value

### ISSUE THREAD

**Issue by markomitos** [keras-team/keras#19997]
When assigning a placeholder value to a KerasVariable I get returned a None type as there is no return in assignment, where as when assigning to a tf.Variable I get returned the proper assign operation.

This is the code in keras.Variable:
```
def _direct_assign(self, value):
        self._value.assign(tf.cast(value, self._value.dtype))
```

And here in the KerasVariable:
```
    def assign(self, value):
        value = self._convert_to_tensor(value, dtype=self.dtype)
        if not shape_equal(value.shape, self.shape):
            raise ValueError(
                "The shape of the target variable and "
                "the shape of the target value in "
                "`variable.assign(value)` must match. "
                f"variable.shape={self.value.shape}, "
                f"Received: value.shape={value.shape}. "
                f"Target variable: {self}"
            )
        if in_stateless_scope():
            scope = get_stateless_scope()
            scope.add_update((self, value))
        else:
            self._direct_assign(value)
```

Link to Keras implementation: https://github.com/keras-team/keras/blob/f9501f53fa15fe6286ca834618a6bcf10f86f7e8/keras/src/backend/common/variables.py#L224

**Comment by grasskin** [comment]
Hi @markomitos, what is your use case for this? In general KerasVariables are used as an internal representation tool for cross-backend Jax functionality. As a user they are also created after calling `self.add_weight()` inside of a layer scope. Any placeholder value should be assigned as an `self.add_weight(initializer=...)`.

**Comment by markomitos** [comment]
Hi @grasskin, thanks for the response. My use case is that I am adding keras 3 support to TensorFlow Federated and I ran into an issue here: 

```
      def assign_placeholder(v):
        p = tf.compat.v1.placeholder(dtype=v.dtype)
        return v.assign(p), p
```
[link to the code](https://github.com/google-parfait/tensorflow-federated/blob/0ca2550e62ca7728e5e9a45edca1feedc6bc065f/tensorflow_federated/python/learning/models/functional.py#L528)

The issue is that the TensorFlow 2 variable assign implementation returns the operation while in the keras 3 implementation it does not return anything. Is it possible to add a return for the value of the assignment in KerasVariable and Keras.Variable, as it is present on the lower levels of the implementation. This would solve my problem and not change the behaviour of the functions while also keeping consistent with the tensorflow implementation.
