### ISSUE TITLE
Custom layers with default layers composition hide their weights

### ISSUE THREAD

**Issue by shkarupa-alex** [keras-team/keras#20004]
Here is an example with Keras 2 vs 3 https://colab.research.google.com/drive/1WKUPCbG14Hdn39pQLigfW81-0Asw9Shr?usp=sharing

As result model pretrained weights can't be loaded.

**Comment by mehtamansi29** [comment]
Hi @shkarupa-alex -

You can create custom layers this it will load pretrained weights in keras3. 

```
from keras import layers, models

class MyCompostionLayer(layers.Layer):
  def __init__(self, input_shape):
    super(MyCompostionLayer, self).__init__()
    self.fc1 = layers.Dense(int(input_shape[-1] * 4), name='fc1')
    self.fc2 = layers.Dense(input_shape[-1], name='fc2')

  def call(self, inputs):
      outputs = self.fc1(inputs)
      outputs = self.fc2(outputs)
      return outputs

  def compute_output_shape(self, input_shape):
    return input_shape

x = layers.Input(shape=(None, 4), dtype='float32')
y = MyCompostionLayer(x.shape)(x)

m = models.Model(x, y)
print('Number of weights:', len(m.weights))
print(m.weights)
m.summary()

```

Attached [gist](https://colab.sandbox.google.com/gist/mehtamansi29/1cbc21a6bea188687702424907d7d987/20004-custom-layers-with-default-layers-composition-hide-their-weights.ipynb) for your reference.

**Comment by shkarupa-alex** [comment]
> Hi @shkarupa-alex -
> 
> You can create custom layers like this, it will load pretrained weights in keras3.
> 
> ```
> from keras import layers, models
> 
> class MyCompostionLayer(layers.Layer):
>   def __init__(self, input_shape):
>     super(MyCompostionLayer, self).__init__()
>     self.fc1 = layers.Dense(int(input_shape[-1] * 4), name='fc1')
>     self.fc2 = layers.Dense(input_shape[-1], name='fc2')
> 
>   def call(self, inputs):
>       outputs = self.fc1(inputs)
>       outputs = self.fc2(outputs)
>       return outputs
> 
>   def compute_output_shape(self, input_shape):
>     return input_shape
> 
> x = layers.Input(shape=(None, 4), dtype='float32')
> y = MyCompostionLayer(x.shape)(x)
> 
> m = models.Model(x, y)
> print('Number of weights:', len(m.weights))
> print(m.weights)
> m.summary()
> ```
> 
> Attached [gist](https://colab.sandbox.google.com/gist/mehtamansi29/1cbc21a6bea188687702424907d7d987/20004-custom-layers-with-default-layers-composition-hide-their-weights.ipynb) for your reference.

This is not a solution for the case when custom layer requires some information about inputs (like number of channels in input_shape)

**Comment by mehtamansi29** [comment]
Hi @shkarupa-alex -

If want to get some information about inputs (like number of channels in input_shape) in custom layer like this:

```
class MyCompostionLayer(layers.Layer):
  def __init__(self, input_shape):
    super(MyCompostionLayer, self).__init__()
    print(f'Input Shape:{input_shape[1:]}')       # Input Shape:(None, 4)
    print(f'No. of channels:{input_shape[-1]}')      #No. of channels:4
    self.fc1 = layers.Dense(int(input_shape[-1] * 4), name='fc1')
    self.fc2 = layers.Dense(input_shape[-1], name='fc2')

  def call(self, inputs):
      outputs = self.fc1(inputs)
      outputs = self.fc2(outputs)
      return outputs

  def compute_output_shape(self, input_shape):
    return input_shape

x = layers.Input(shape=(None, 4), dtype='float32')
y = MyCompostionLayer(x.shape)(x)

m = models.Model(x, y)
print('Number of weights:', len(m.weights))
print(m.weights)
print(f'Input Shape:{x.shape[1:]}')    #Input Shape:(None, 4)
print(f'No. of channels:{x.shape[-1]}')     #No. of channels:4
m.summary()
```

Please let me know if you need more help. Thanks..!!

**Comment by james77777778** [comment]
Hey @shkarupa-alex 

This should meet your needs:

```python
from keras import layers
from keras import models


class MyCompostionLayer(layers.Layer):
    def build(self, input_shape):
        self.fc1 = layers.Dense(int(input_shape[-1] * 4), name="fc1")
        self.fc2 = layers.Dense(input_shape[-1], name="fc1")

        # Manually build sublayers
        self.fc1.build(input_shape)
        input_shape = self.fc1.compute_output_shape(input_shape)
        self.fc2.build(input_shape)
        super().build(input_shape)

    def call(self, inputs):
        outputs = self.fc1(inputs)
        outputs = self.fc2(outputs)
        return outputs

    def compute_output_shape(self, input_shape):
        return input_shape


x = layers.Input(shape=(None, 4), dtype="float32")
y = MyCompostionLayer()(x)
m = models.Model(x, y)

print("Number of weights", len(m.weights), "\n")
m.summary()

```

The idea is that we need to manually build the sublayers if we instantiate them in `build`.
Just like:
https://github.com/keras-team/keras/blob/dfc4f788720ee58322c927ef061501b48a47eac3/keras/src/layers/attention/multi_head_attention.py#L234-L243

Another approach is to feed the inputs to build them:

```python
from keras import layers
from keras import models
from keras import ops


class MyCompostionLayer(layers.Layer):
    def build(self, input_shape):
        self.fc1 = layers.Dense(int(input_shape[-1] * 4), name="fc1")
        self.fc2 = layers.Dense(input_shape[-1], name="fc1")

    def call(self, inputs):
        outputs = self.fc1(inputs)
        outputs = self.fc2(outputs)
        return outputs

    def compute_output_shape(self, input_shape):
        return input_shape


x = layers.Input(shape=(None, 4), dtype="float32")
y = MyCompostionLayer()(x)
m = models.Model(x, y)

m(ops.ones((1, 1, 4)))  # Eager call to build sublayers

print("Number of weights", len(m.weights), "\n")
m.summary()

```

**Comment by shkarupa-alex** [comment]
Resolved within TestCase.run_layer_test
