### ISSUE TITLE
Sum Metrics reset_state only supports float types

### ISSUE THREAD

**Issue by markomitos** [keras-team/keras#20012]
Because the asign in the Sum Metrics reset_state function passes a float value (0.0) instead of an int value (0) - as was the case in keras 2, the dtype of custom Models derived from this class can only be of type float without overwriting the function itself.
```
    def reset_state(self):
        self.total.assign(0.0)
```

**Comment by mehtamansi29** [comment]
Hi @markomitos -

Could you please provide detailed code to reproduce this issue ?

**Comment by Grvzard** [comment]
https://github.com/keras-team/keras/blob/f9501f53fa15fe6286ca834618a6bcf10f86f7e8/keras/src/backend/common/variables.py#L224-L225

**Comment by markomitos** [comment]
When making a new class from keras.metrics.Sum it was neccessary for me to overide the reset_state function to support int:
 ```
class KerasNumExamplesCounter(keras.metrics.Sum):
  
  def __init__(self, name='num_examples', dtype=tf.int64):  # pylint: disable=useless-super-delegation
    super().__init__(name, dtype)

  def update_state(self, y_true, y_pred=None, sample_weight=None):
    del y_pred  # Unused
    # In case we have multiple labels, we use the first dimension of the first
    # label to compute the batch size.
    labels = tf.nest.flatten(y_true)
    if not all(tf.is_tensor(l) or isinstance(l, np.ndarray) for l in labels):
      raise ValueError(
          'NumExamplesCounter only works with `numpy.ndarray` or '
          '`tensorflow.Tensor` types. Received a structure with '
          'other values; consider using `np.asarray` or '
          f'`tf.convert_to_tensor`. Got: {labels}'
      )
    return super().update_state(tf.shape(labels[0])[0], sample_weight=None)

  def reset_state(self):
    self.total.assign(0)
```

Here is the permalink to the original code i sent:
https://github.com/keras-team/keras/blob/f9501f53fa15fe6286ca834618a6bcf10f86f7e8/keras/src/metrics/reduction_metrics.py#L89

**Comment by Grvzard** [comment]
ok now i can reproduce it.
