### ISSUE TITLE
Unexpected saving/loading `.h5` weights behavior on Keras 3+.

### ISSUE THREAD

**Issue by abhaskumarsinha** [keras-team/keras#20019]
Hello there,

Here's a strange problem. Loading the model from `.h5` weights file after saving:

```python
# load the model
try:
    print(f"\nStart loading model {savepath}", flush=True)
    model_loaded = load_model(savepath)
    print(f"Done loading model {savepath}", flush=True)
    model_loaded.summary()
except Exception:
    import traceback

    print(f"\nloading model {savepath} failed.", flush=True)
    print(traceback.format_exc(), flush=True)
```

The above code works in TensorFlow versions of Keras but not in Keras 3+.

## Colab Gist

- *TensorFlow*: https://colab.research.google.com/gist/jeffDebug/149b36c7b9eceb94c8bd9bc773364e2c/untitled0.ipynb#scrollTo=fiEeXoJyDLJm
- *Keras 3+*: https://colab.research.google.com/gist/abhaskumarsinha/5acbddd6632c5ee4b6bb7836f37647f9/untitled0.ipynb

Authors: @jeffDebug

Link: #19967

Thank You.

________________________

https://github.com/keras-team/keras/discussions/19967

**Comment by abhaskumarsinha** [comment]
Jeff here: #19967

**Comment by ghsanti** [comment]
Did you meant to use keras 3+ in the second link? they are the same link currently

**Comment by abhaskumarsinha** [comment]
Hello @ghsanti ,

> Did you mean to use Keras 3+ in the second link? they are the same link currently, and use Keras 2.

Thanks, I've updated the links...

**Comment by ghsanti** [comment]
idk if you replace `.h5` by `.keras` it saves fine, and only `.keras` is supported as I cited above.

**Comment by ghsanti** [comment]
The new colab that you linked @abhaskumarsinha shows:

```bash
Start loading model ./model/test.h5
Done loading model ./model/test.h5
```
