### ISSUE TITLE
Keras distributed fine tuning - TypeError: ModelParallel

### ISSUE THREAD

**Issue by ranasaurus9** [keras-team/keras#20039]
I am trying to fine tune gemma 2 using model parallelism on TPU. Reference notebook - https://colab.research.google.com/drive/1bEivD7tSwbFMtPbNEcZxilZvN_dGzgbU?usp=sharing

I am getting the below error when I trying to configure ModelParallel on Keras distribution.

`model_parallel = keras.distribution.ModelParallel(device_mesh, layout_map, batch_dim_name="batch")
keras.distribution.set_distribution(model_parallel)`

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-47-bbe6b4743dd2> in <cell line: 1>()
----> 1 model_parallel = keras.distribution.ModelParallel(device_mesh, layout_map, batch_dim_name="batch")
      2 
      3 
      4 keras.distribution.set_distribution(model_parallel)

TypeError: ModelParallel.__init__() takes 1 positional argument but 3 positional arguments (and 1 keyword-only argument) were given
```

Name: keras
Version: 3.4.1
Summary: Multi-backend Keras.
Home-page: https://github.com/keras-team/keras
Author: Keras team
Author-email: [keras-users@googlegroups.com](mailto:keras-users@googlegroups.com)
License: Apache License 2.0
Location: /usr/local/lib/python3.10/dist-packages
Requires: absl-py, h5py, ml-dtypes, namex, numpy, optree, packaging, rich
Required-by: tensorflow

**Comment by Grvzard** [comment]
> `model_parallel = keras.distribution.ModelParallel(device_mesh, layout_map, batch_dim_name="batch")`

=> `model_parallel = keras.distribution.ModelParallel(device_mesh=device_mesh, layout_map=layout_map, batch_dim_name="batch")`

**Comment by ghsanti** [comment]
adding some context, that behaviour changed from [3.3.3](https://github.com/keras-team/keras/blob/v3.3.3/keras/src/distribution/distribution_lib.py#L488) to [3.4.1](https://github.com/keras-team/keras/blob/v3.4.1/keras/src/distribution/distribution_lib.py#L488)

now it's as @Grvzard  suggested

**Comment by sachinprasadhs** [comment]
Here is the commit which caused the change https://github.com/keras-team/keras/commit/0ee33b5a8c2b1eaeabe539c6f81ef5ac7f6d1bb1
