### ISSUE TITLE
Are different "set of batches" selected at each epoch when using `steps_per_epoch` ?

### ISSUE THREAD

**Issue by ghsanti** [keras-team/keras#20030]
This fits the model using 10 batches of 64 samples per epoch:

```py
model.fit(train_data, epochs=5, steps_per_epoch=10)
```

If the Dataset is `.batch`ed with 64 samples, but has more than 640 samples (say 2000), are all those remaining samples used at all ?

**Comment by mehtamansi29** [comment]
Yes @ghsanti -

All remaining samples are used for training at all. Here there is 64 samples means batch size is 64 and steps_per_epoch is 10. This means model iterate through the dataset 10 times in one epoch. So for example in first step first 64 sample will train, then second step next 64 samples and so on upto 2000 samples will use for training.

**Comment by ghsanti** [comment]
thanks !
