### ISSUE TITLE
Land PR #19969

### ISSUE THREAD

**Issue by mattdangerw** [keras-team/keras#20045]
We had to roll this back the PR as it was breaking some TPUStrategy runs.

Specifically the change was breaking some training runs in the following way...

- `fit()` called (outside of scope)
- leading to the new `_symbolic_build` being called
- leading to an error when variables are created out of scope... `RuntimeError: Need to be inside "with strategy.scope()" for <google3.third_party.tensorflow.python.distribute.tpu_strategy.TPUStrategyV2 object>`

**Comment by mattdangerw** [comment]
@haohuanw fyi

**Comment by haohuanw** [comment]
@mattdangerw are there any actions i should take? i *think* the proper workflow should be either of the following?

1. call build with the scope and then fit outside of the scope
2. call fit within the scope

i think the main issue is around lazy variable creation in this case..?

**Comment by mattdangerw** [comment]
Was just trying to make a reproduction. I think this covers it...

https://colab.research.google.com/gist/mattdangerw/f87eb771991bd97c74f0d97712682b13/repro.ipynb

There's something still up with this colab; adapted it from a keras.io. If I run the lastest Keras training will succeed for a few train steps, but eventually fail with some issue communicating with the CPU.

However if you run it on the commit before the rollback, you see an instant crash on the first train step due to creating variables outside the scope.

Anyway, not the best repro, but hopefully enough to get started.

**Comment by mattdangerw** [comment]
I'm not super familiar with the tf.distribute codebase, so I'm not actually sure what the best fix is here.

But in general, you will see a model created and compiled inside the strategy scope, and `fit()` called outside the strategy scope. I don't think we can guarantee that the model has been manually built inside the scope, nor can we demand that `fit()` be called inside the scope (that would be a very breaking change).

cc @fchollet and @hertschuh in case they have thoughts on the best way to fix this.

But at a high level let's make sure this works:

```python
with strategy.scope():
    model = ...

model.fit(dataset)
```

**Comment by fchollet** [comment]
I think the fix here is easy: we have a handle on the distribution strategy (it's at `self.distribute_strategy`, and might be `None` if unset). So if it is set, we can open a scope when calling `_symbolic_build` (which might create new variables).

**Comment by mattdangerw** [comment]
sgtm!

**Comment by haohuanw** [comment]
> I think the fix here is easy: we have a handle on the distribution strategy (it's at `self.distribute_strategy`, and might be `None` if unset). So if it is set, we can open a scope when calling `_symbolic_build` (which might create new variables).

i can try it if you haven't start working on it

**Comment by fchollet** [comment]
> i can try it if you haven't start working on it

Please open a PR if you're able! It think it would be the original PR, with just an added open scope (`with self.distribute_strategy.scope():`) around `symbolic_build` in the case `if self.distribute_strategy is not None`
