### ISSUE TITLE
Is 2D CNN's description correct ?

### ISSUE THREAD

**Issue by ghsanti** [keras-team/keras#20052]
>   This layer creates a convolution kernel that is convolved with the layer
    input over a single spatial (or temporal) dimension to produce a tensor of
    outputs. If `use_bias` is True, a bias vector is created and added to the
    outputs. Finally, if `activation` is not `None`, it is applied to the
    outputs as well.

[keras docs](https://github.com/keras-team/keras/blob/v3.4.1/keras/src/layers/convolutional/conv2d.py#L5)

Isn't convolved over *2 spatial dimensions* ?

**Comment by mehtamansi29** [comment]
Hi @ghsanti - 

Thanks for pointing this issue. We have raised an internal fix for updating the description for 2D and 3D CNN. Soon it will be reflected in the documentation as well. Thanks.
