### ISSUE TITLE
Issue with Loading Sequential Models

### ISSUE THREAD

**Issue by xchen99sdr** [keras-team/keras#20074]
https://github.com/tensorflow/tensorflow/issues/70757 

Reposting per tensorflow developer's recommendation. 

I am encountering the same issue with pip version 2.17

Thank you

**Comment by RaulCastillo547** [comment]
I'm the original poster of the tensorflow issue. Thank you xchen99sdr for reposting it.

**Comment by james77777778** [comment]
A minimal reproducible script:

```python
from keras import layers
from keras import models
from keras import ops
from keras import saving

CONV_WIDTH = 3
model = models.Sequential([layers.Lambda(lambda x: x[:, -CONV_WIDTH:, :])])
x = ops.ones((1, 10, 4))
y = model(x)
model.save("model.keras")
revived_model = saving.load_model("model.keras", safe_mode=False)  # <- failed

```

A workaround is to directly assign the value instead of using variables in `layers.Lambda`. I don't know why it caused the issue.

```python
from keras import layers
from keras import models
from keras import ops
from keras import saving

model = models.Sequential([layers.Lambda(lambda x: x[:, -3:, :])])  # Not using `CONV_WIDTH`
x = ops.ones((1, 10, 4))
y = model(x)
model.save("model.keras")
revived_model = saving.load_model("model.keras", safe_mode=False)

```

I have submitted a PR #20076  to ultimately fix it. You can also wait for it.
