### ISSUE TITLE
module 'keras.utils' has no attribute 'PyDataset'

### ISSUE THREAD

**Issue by Sticcolet** [keras-team/keras#20098]
I have correctly installed version 3.0.5 of keras and used pytorch for the backend, but it always prompts module 'keras. utils' has no attribute' PyDataset '. How can I solve this problem?

**Comment by ghsanti** [comment]
@Sticcolet did you try with newer versions of keras (ideally `3.4.1` or keras-nightly) and could you share a colab to check the issue?

You can also make sure about the version used (in case you are in a complex env) doing `print(keras.__version__)`
On colab both of these work (in those versions)

> from keras.api.utils import PyDataset
> from keras.utils import PyDataset

**Comment by mehtamansi29** [comment]
Hi @Sticcolet -

PyDataset is implemented and supported from keras 3.3.0 version. So try to upgrade your keras from 3.0.5 to keras3.3.0 or higher version. Then this command will work without attribute error.

`from keras.utils import PyDataset`

**Comment by Sticcolet** [comment]
Since I initially installed keras using conda, I could only install version 3.0.5. Later, I updated it to 3.4.1 using pip to solve this problem. In fact, I saw that the source code of 3.0.5 contains the content of keras.utils.PyDataset, is it impossible to reference it?

**Comment by mehtamansi29** [comment]
Hi @Sticcolet -

Here you can find [PyDataset](https://github.com/keras-team/keras/blob/v3.3.3/keras/src/trainers/data_adapters/py_dataset_adapter.py) is implemented after keras 3.3.0.

**Comment by Headshake** [comment]
I'm using Keras 3.3.3
