### ISSUE TITLE
Testing functional models as layers

### ISSUE THREAD

**Issue by shkarupa-alex** [keras-team/keras#20118]
In keras V2 it was possible to test functional models as layers with TestCase.run_layer_test

But in keras V3 it is not due to an issue with deserialization https://colab.research.google.com/drive/1OUnnbeLOvI7eFnWYDvQiiZKqPMF5Rl0M?usp=sharing

The root issue is input_shape type in model config is a list, while layers expect a tuple.

As far as i understand the root issue is json dump/load in serialization test. Can we omit this step?

**Comment by nkovela1** [comment]
Hi @shkarupa-alex, what is the purpose of using TestCase.run_layer_test or TestCase.run_serialization_test? This is not public API, so we cannot guarantee stability of your usage here.

**Comment by shkarupa-alex** [comment]
> Hi @shkarupa-alex, what is the purpose of using TestCase.run_layer_test or TestCase.run_serialization_test? This is not public API, so we cannot guarantee stability of your usage here.

This is my frequent use case for testing custom layers. Just like keras itself tests it't own layers, i test my own.
