### ISSUE TITLE
Are the docs correct for the RNN description of `batch_shape` ?

### ISSUE THREAD

**Issue by ghsanti** [keras-team/keras#20111]
[In the description the RNN it says](https://github.com/keras-team/keras/blob/933579d3c4a585f236982d05d3a74921f9567415/keras/src/layers/rnn/rnn.py#L105-L110) it says:

>     If sequential model:
>        `batch_input_shape=(...)` to the first layer in your model.

Yet seems that the parameter `batch_input_shape` will fail since it does not exist in most layers.

Is a user supposed to be adding an **Input** layer instead of that parameter, with the parameter `batch_shape` (note that the names don't match either.) ?

Should the description instead be the same for Functional or Sequential, or am I misunderstanding something ?

This is a follow up [from this thread ](https://github.com/keras-team/keras/issues/20106) in case you need more context.

**Comment by sachinprasadhs** [comment]
batch_input_shape is part of `**kwargs` and it will be treated as batch_shape in the Input layer.
Below is the part where it is handled.

https://github.com/keras-team/keras/blob/816d219c04b2bdb7de81081fa14eac63000dac30/keras/src/layers/core/input_layer.py#L30-L31

**Comment by ghsanti** [comment]
> batch_input_shape is part of `**kwargs` and it will be treated as batch_shape in the Input layer.
> Below is the part where it is handled.
> 
> https://github.com/keras-team/keras/blob/816d219c04b2bdb7de81081fa14eac63000dac30/keras/src/layers/core/input_layer.py#L30-L31

But why not here then? 


https://github.com/keras-team/keras/issues/20106#issue-2458530621

**Comment by sachinprasadhs** [comment]
I have replied to the thread with the comment https://github.com/keras-team/keras/issues/20106#issuecomment-2287920055 which accepts `batch_input_shape` for the `InputLayer`

**Comment by ghsanti** [comment]
> I have replied to the thread with the comment https://github.com/keras-team/keras/issues/20106#issuecomment-2287920055 which accepts `batch_input_shape` for the `InputLayer` 

Thank you, i didnt know inputlayer and input were different.
