### ISSUE TITLE
Keras should support bitwise ops

### ISSUE THREAD

**Issue by kaiyuanw** [keras-team/keras#20139]
Numpy has bitwise ops https://numpy.org/doc/stable/reference/routines.bitwise.html
TensorFlow has bitwise ops https://www.tensorflow.org/api_docs/python/tf/bitwise
Jax has bitwise ops https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.bitwise_and.html
PyTorch has bitwise ops https://pytorch.org/docs/stable/generated/torch.bitwise_and.html

So it seems natural for Keras to support bitwise ops as well.

**Comment by james77777778** [comment]
What a coincidence! They were added last week in this PR https://github.com/keras-team/keras/pull/20126
You can try them by installing the nightly version.

```bash
pip install keras-nightly
```

**Comment by nkovela1** [comment]
Since these were added in https://github.com/keras-team/keras/pull/20126, closing this issue for now.
