### ISSUE TITLE
Would Keras support unique function? 

### ISSUE THREAD

**Issue by cqwangding** [keras-team/keras#20140]
Jax unique: https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.unique.html
TF unique: https://www.tensorflow.org/api_docs/python/tf/unique

**Comment by mehtamansi29** [comment]
Hi @cqwangding -

Keras doesn't have unique function. As keras is high level API on the top of tensorflow,jax,numpy,torch. 
And this unique function is for data manipulation which can be done before keras models.
 
So all these keras backends(tensorflow,jax,numpy,torch) has seperate unique functions. 

tensorflow: [tf.unique](https://www.tensorflow.org/api_docs/python/tf/unique)
jax: [jax.numpy.unique](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.unique.html)
torch: [torch.unique](https://pytorch.org/docs/stable/generated/torch.unique.html)
numpy: [numpy.unique](https://numpy.org/doc/stable/reference/generated/numpy.unique.html)

**Comment by haifeng-jin** [comment]
@mehtamansi29 This feature request is from AdBrain. They may use it in the model instead of the data pipeline. Not exactly sure about which model they are using though.

**Comment by mattdangerw** [comment]
I believe @hertschuh is working on a unique op. Though he is out for two weeks, so we can expect more action on this when he is back!

**Comment by hertschuh** [comment]
Per offline discussion, this is no longer needed.
