### ISSUE TITLE
Wrong file permissions when loading model.

### ISSUE THREAD

**Issue by RaydelMiranda** [keras-team/keras#20146]
When loading a model, Keras seem to open the *.keras file with the mode `"r+b"`. There are some instances in which this could be undesired, for instance, when working in AWS SageMaker with custom containers the folder "/opt/ml/model" is mounted as read-only, and trying to load the model from that folder results in an error.

The error message itself is very misleading ("FileNotFound"). The following code reproduces this:

```python
import os
from stat import S_IREAD

import tempfile
import tensorflow as tf
import keras

# Very simple model.
model = keras.models.Sequential([tf.keras.layers.Dense(1)])
model.build()

with tempfile.TemporaryDirectory() as path:

    model_path = f"{path}/model.keras"
    
    # Save the model with keras format.
    model.save(model_path)
        
    # Make the folder the model is in read-only.
    # Comment next line to see the model loaded successfully.
    os.chmod(path, S_IREAD)

    # Try to load the model.
    try:
        model = keras.models.load_model(model_path)
    except Exception as err:
        print(err)
    else:
        print("model.keras loaded!") 
```

The error message would be something like: 

> File not found: filepath=/tmp/tmp4zmqzf8p/model.keras. Please ensure the file is an accessible `.keras` zip file.

If we are loading the model, there should not be problem in this kind of scenarios.

**Comment by Grvzard** [comment]
For the example above, error occurs because `os.chmod(path, S_IREAD)` makes the DIRECTORY become read-only, which denies access. The correct way to 'reproduce' it is either:
1. `os.chmod(path, S_IREAD | S_IEXEC)`
2. `os.chmod(model_path, S_IREAD)`

and after that you'll find that it works fine because:
https://github.com/keras-team/keras/blob/befa049bdd04545892354bbad54d86cf3ce45c86/keras/src/saving/saving_lib.py#L364

> when working in AWS SageMaker with custom containers the folder "/opt/ml/model" is mounted as read-only

Are you sure the directory is mounted correctly, or could something else be wrong here?

**Comment by james77777778** [comment]
@RaydelMiranda  what version of Keras are you using?
There was a bug in `<=3.4.1`, but your script should work fine with the latest version (`3.5.0`).

```python
import os
import tempfile
from stat import S_IREAD

import keras

model = keras.models.Sequential([keras.layers.Dense(1)])
model.build()

with tempfile.TemporaryDirectory() as path:
    model_path = f"{path}/model.keras"
    model.save(model_path)
    os.chmod(model_path, S_IREAD)  # Ensure the file is read-only.
    model = keras.models.load_model(model_path)
    print("model.keras loaded!")

```

In details, there is a try-except block to ensure that loading will only use read permission if any errors occur:

https://github.com/keras-team/keras/blob/befa049bdd04545892354bbad54d86cf3ce45c86/keras/src/saving/saving_lib.py#L452-L476

**Comment by RaydelMiranda** [comment]
Hi again everyone and thanks for the quick response.

@james77777778 , Indeed I am using version `3.2.1` which I see is far behind the last version, I actually installed Keras indirectly by installing TensorFlow 2.16.1.

I did updated Keras to 3.5.0 and all is working fine, Thanks!

**Comment by RaydelMiranda** [comment]
I am closing this since this is a bug that was already addressed.
