### ISSUE TITLE
Use Keras to load dataset

### ISSUE THREAD

**Issue by jawi289o** [keras-team/keras#20193]
How can I use keras with pytorch backend to load my custom dataset. I also want to use the data augmentations that are available in the preprocessing layers. My model is written in pytorch. 
Can anyone guide me about this?

**Comment by ghsanti** [comment]
`x,y` parameters in `fit` shows which data-formats are supported.

Here: https://keras.io/api/models/model_training_apis/

**Comment by fchollet** [comment]
Right -- you can use a wide variety of formats to training the model. `tf.data` is usually a solid option, regardless of what backend you're using.

**Comment by jawi289o** [comment]
@fchollet may be you didn't understood my question clearly. I want to load data and apply augmentations which are available in keras how can I pass it to my model which is written in pytorch?
