### ISSUE TITLE
Nested sequentials broken in 3.5

### ISSUE THREAD

**Issue by JackDunnNZ** [keras-team/keras#20203]
The following reduced example gives an error in Keras 3.5.0 but worked in 3.4.1 and earlier:

```python
import keras

model = keras.Sequential()
model.add(keras.Input(shape=(16,)))
keras.Sequential([model])
```

```
ValueError: Sequential model 'sequential' has no defined input shape yet.
```

The cause is the introduction of the `hasattr` call to check for the `input_shape` property here: https://github.com/keras-team/keras/blob/fa6be07ce86b3f8c5072a3d5ff355b4266baa32d/keras/src/models/sequential.py#L141

Since `hasattr` simply calls `getattr` and checks for an `AttributeError`, this call to `hasattr` actually raises a `ValueError` as though we were trying to call `.input_shape` instead of returning false like was intended.

**Comment by ghsanti** [comment]
Isn't this the same issue as fixed here?

https://github.com/keras-team/keras/issues/20155#issue-2482970454

You may test using keras-nightly
