### ISSUE TITLE
ISSUE : Sequential model 'sequential_1' has already been configured to use input shape (None, 224, 224, 3). You cannot build it with input_shape [None, 224, 224, 3]

### ISSUE THREAD

**Issue by thayyilakul** [keras-team/keras#20214]
Currently learning tensorflow with keras and got this error while loading saved model which is saved in keras extension.
`ValueError: Sequential model 'sequential_1' has already been configured to use input shape (None, 224, 224, 3). You cannot build it with input_shape [None, 224, 224, 3]`

Below is my model creation function
```
def create_model(input_shape = INPUT_SHAPE, output_shape = OUTPUT_SHAPE, model_url = MODEL_URL):
  print('Building model with: ',MODEL_URL)

  hubs_layer = hub.KerasLayer(MODEL_URL)
  model = tf.keras.Sequential([
       tf.keras.layers.Lambda(lambda x: hubs_layer(x)), # Layer 1 (input layer)
      tf.keras.layers.Dense(units = OUTPUT_SHAPE,
                            activation = 'softmax') # Layer 2 (output layer)
  ])
  model.compile(
      loss = tf.keras.losses.CategoricalCrossentropy(),
      optimizer = tf.keras.optimizers.Adam(),
      metrics = ['accuracy']
  )
  model.build(INPUT_SHAPE)
  return model`
```

MODEL_URL is just a kaggle dataset mobilenet-v2

Below is my load model function 
```
# Create a function to load a trained model
def load_model(model_path):
  '''
  Loads a saved model from a specified path
  '''
  print(f'Loading saved model from: {model_path}')

  # Enable unsafe deserialization
  # tf.keras.config.enable_unsafe_deserialization()

  # model = tf.keras.models.load_model(model_path, 
  #                                    custom_objects = {'KerasLayer' : hub.KerasLayer})
  model = tf.keras.models.load_model(model_path)
  return model
```

Below is how i am calling load function
```loaded_1000_image_model = load_model('filename.keras')```

**Comment by mehtamansi29** [comment]
Hi @thayyilakul -

Thanks for reporting this issue. Can you please let me know exactly at which line you are getting error ? I am not able to get error while  running this function(create_model()). Attached [gist](https://colab.sandbox.google.com/gist/mehtamansi29/7d639df34e51f903312055e0d35d730b/20214-issue-sequential-model-sequential_1-has-already-been-configured-to-use-input-shape-none-224-224-3-you-cannot-build-it-with-input_shape-none-224-224-3.ipynb) for the reference.

**Comment by thayyilakul** [comment]
Hi, thank you for your reply, well it's happening when i call  the function load_model() after i save the model.

**Comment by mehtamansi29** [comment]
Hi @thayyilakul -

Here in this [gist](https://colab.sandbox.google.com/gist/mehtamansi29/4da7d31ec4da664a7049746d091d9717/20214-issue-sequential-model-sequential_1-has-already-been-configured-to-use-input-shape-none-224-224-3-you-cannot-build-it-with-input_shape-none-224-224-3.ipynb) you can find successfully load model with custom_objects and without custom_objects.

**Comment by metnbyar** [comment]
çözebildiniz mi
