### ISSUE TITLE
MultiHeadAttention is using unoptimised einsum equations

### ISSUE THREAD

**Issue by tendulkar** [keras-team/keras#20220]
https://github.com/keras-team/keras/blob/v3.5.0/keras/src/layers/attention/multi_head_attention.py#L737 is building einsum equation for query, key, values
it's building equations of the form `abc,cde-->abde`, which does dot product b/n last axis of first matrix, and first axis of last matrix. The last axis is data is stored in sequence in memory, but first axis data (for second matrix) is stored in fragmented way. This leads to inefficiencies in call method (in einsum calculation). Added tests to showcase the behaviour (tested on Google colab T4 GPU). We can see that `abc,cde-->abde` `abc,dce-->abde` and `abc,dec-->abde` are equivalent, but their performance difference is significant for large matrices. The equation `abc,dec-->abde` wins here due to data locality. 
For large matrices the performance benefit will be around 50%. 
<img width="691" alt="image" src="https://github.com/user-attachments/assets/d7f5ba5b-abb7-42a0-9bfb-448e8d81e53b">
For small matrices, the performance difference is not significant at all.
<img width="689" alt="image" src="https://github.com/user-attachments/assets/1888580d-6db4-4d71-9b09-0cc00c4dd73e">

**Comment by sanskarmodi8** [comment]
Hi @tendulkar ,
I have created a pull request regarding the same - https://github.com/keras-team/keras/pull/20230

**Comment by tendulkar** [comment]
Any reason for raising the duplicate request ?

**Comment by sanskarmodi8** [comment]
Sorry @tendulkar  , I didn't noticed that you have created a pull request for the same. I have closed my PR. BTW, Thanks for the valuable change.

**Comment by fchollet** [comment]
Discussed on the PR -- the conclusion is that this is a clever observation, but in practice we're not seeing the expected speed benefits after compilation -- the current code is actually faster.
