### ISSUE TITLE
Add 'pip install -r requirements.txt' to devcontainer.json to reduce contribution efforts

### ISSUE THREAD

**Issue by joehiggi1758** [keras-team/keras#20238]
In the `CONTRIBUTING.md` file there is a sub-section for setting up local environments as follows...

```
git clone https://github.com/YOUR_GITHUB_USERNAME/keras.git
cd keras
pip install -r requirements.txt
```

This section could be removed entirely by updating the `devcontainer.json` file to include `"postCreateCommand": "sh ./.devcontainer/setup.sh && pip install -r requirements.txt",`. As the `pip install -r requirements.txt` portion will be handled automatically by instantiating the dev container. 

I believe this would reduce superfluous steps to contribution and speed up local environment set ups!

**Comment by fchollet** [comment]
Done
