### ISSUE TITLE
"replication_pad1d" not implemented for 'Half'

### ISSUE THREAD

**Issue by MilkFiish** [keras-team/keras#20236]
This error report was obtained when I executed codes with function `keras.layers.MaxPooling1D` dynamically, but statically with shape output.
The version info is keras 3.5.0 with PyTorch 2.4.0

```
import os
import re
import torch
import numpy as np
os.environ['KERAS_BACKEND']='torch'
import keras

layer = keras.layers.MaxPooling1D(
    pool_size=2,
    strides=1,
    padding="same",
    data_format="channels_first",
    trainable=True,
    dtype="mixed_float16",
    autocast=True,
)

result_static = layer.compute_output_shape([3, 5, 4])

result_dynamic = layer(
    inputs=np.random.rand(*[3, 5, 4]),
)
```

For the static result, I got shape `(3, 5, 4)`. However, for the dynamic one, I obtained this error report
```
...\torch\nn\functional.py:4552, in pad(input, pad, mode, value)
   4545         if mode == 'replicate':
   4546             # Use slow decomp whose backward will be in terms of index_put.
   4547             # importlib is required because the import cannot be top level
   4548             # (cycle) and cannot be nested (TS doesn't support)
   4549             return importlib.import_module('torch._decomp.decompositions')._replication_pad(
   4550                 input, pad
   4551             )
-> 4552 return torch._C._nn.pad(input, pad, mode, value)

RuntimeError: Exception encountered when calling MaxPooling1D.call().

"replication_pad1d" not implemented for 'Half'
```

I don't think it's reasonable for dynamic and static output to be different.
Furthermore, dynamic error messages are not clear enough, at least there is no `Half` in the codes.

**Comment by fchollet** [comment]
This issue is at the level of the backend, PyTorch. Sometimes, some operations aren't supported by a specific backend, but are supported by others, and thus the backend-agnostic part of the code (like `compute_output_shape`) should not raise an error.
