### ISSUE TITLE
Question about Memory Leak (all backends)

### ISSUE THREAD

**Issue by ghsanti** [keras-team/keras#20245]
There is an issue here in tf-keras about [memory leaks](https://github.com/keras-team/tf-keras/issues/286).

There are [several workarounds](https://github.com/keras-team/keras/issues/5345), but the problem does not have a clear solution.

I've gathered some observations:

1. Still happens in Keras 3
2. Happens with all backends
3. It is not related to `tf.data.Dataset`
4. It seems rather related to weights not being released.
5. Happens in most (or all) model types (I tested Sequential and Subclassing.)
6. Tested in Colab only (so it could be a Colab issue as well.)

_Is there any obvious or recommended way to delete a model and the weights so that the RAM memory is freed?_

[GIST](https://colab.research.google.com/gist/ghsanti/f050ed70edd082f2ef8c3f60ae96b1d2/memory_leak.ipynb)

<details>
<summary>
Or just take a look at the code here.
</summary>

```py

import keras
import numpy as np 
import os

# import tensorflow
# os.environ['KERAS_BACKEND']='tensorflow'

# import jax
# os.environ['KERAS_BACKEND']='jax'

import torch
os.environ['KERAS_BACKEND']='torch'

# class MyModel(keras.Model):

#   def __init__(self):
#     super().__init__()
#     self.dense1 = keras.layers.Dense(1000, activation=keras.activations.relu)
#     self.dense2 = keras.layers.Dense(10000, activation=keras.activations.softmax)
#     self.dense3 = keras.layers.Dense(10000, activation=keras.activations.softmax)
#     self.dense4 = keras.layers.Dense(10, activation=keras.activations.softmax)
  
#   def call(self, i):
#     x = self.dense1(i)
#     x = self.dense2(x)
#     x = self.dense3(x)
#     x = self.dense4(x)
#     return x


# ds = tf.data.Dataset.from_tensor_slices((keras.random.uniform((64*4, 1000)), keras.ones((64*4))))

x = np.random.standard_normal((64,1000))
y = np.ones((64,))

for r in range(0, 10000):
    # model = MyModel() #comment for sequential test.
    model = keras.models.Sequential([
        keras.layers.Dense(1000, activation=keras.activations.relu),
        keras.layers.Dense(10000, activation=keras.activations.relu),
        keras.layers.Dense(10000, activation=keras.activations.relu),
        keras.layers.Dense(10, activation=keras.activations.softmax)])
    model.call(np.random.standard_normal((1,1000))) # seful for seq.
    model.summary()
    model.compile(optimizer='sgd', loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True))

    model.fit(x,y)
    keras.backend.clear_session()
    del model

```

</details>

**Comment by fchollet** [comment]
Thanks for the report. I tested it with all backends and found:

- This is CPU RAM rather than GPU RAM. Can you confirm?
- It happens with all backends. This means there's a Keras-side cause.
- It does *not* happen with `run_eagerly=True`. So it has to do with the compilation infra.

**Comment by ghsanti** [comment]
> Thanks for the report. I tested it with all backends and found:
> 
> - This is CPU RAM rather than GPU RAM. Can you confirm?
> - It happens with all backends. This means there's a Keras-side cause.
> - It does *not* happen with `run_eagerly=True`. So it has to do with the compilation infra.

Confirm 1) and 2), can't test 3 now and didn't realise earlier but that's an extra finding.

**Comment by fchollet** [comment]
I think it's possible that it is linked to circular references in the compilation functions. It may be helpful to try to list which objects are occupying memory.

**Comment by fchollet** [comment]
Also -- I cannot repro the leak when running locally with JAX or PyTorch.

When running locally I only see the leak with TF + compilation.

I've identified the source of the leak in this case, and it's a TF bug. Basically when we create TF functions their resources never get garbage collected. Even if we keep a reference to the functions created and we manually delete them, the memory isn't freed.

JAX and PyTorch do not appear to have any such problems. I can run the script with no memory accumulation with JAX + XLA compilation for instance.

**Comment by ghsanti** [comment]
I re-tested, you are correct, I used the `os.environ` after the keras import, so it was using tf.

In fact is quite neat to see with torch and jax how the memory oscillates; for torch between 2.6 and 3 GB, for jax 2.2 and 2.6. In both cases the network used has 400Mb parameters size.

I'm closing then!

**Comment by ghsanti** [comment]
Actually, it does seem to me that this code collects the garbage correctly?

```py
import keras
import numpy as np
import os
import gc

gc.set_debug(15)

model = keras.models.Sequential([
        keras.layers.Dense(1000, activation=keras.activations.relu),
        keras.layers.Dense(10000, activation=keras.activations.relu),
        keras.layers.Dense(10000, activation=keras.activations.relu),
        keras.layers.Dense(10, activation=keras.activations.softmax),
])

x = np.random.standard_normal((64,1000))
y = np.ones((64,))

for r in range(0, 10000):

    model = keras.models.Sequential([
        keras.layers.Dense(1000, activation=keras.activations.relu),
        keras.layers.Dense(10000, activation=keras.activations.relu),
        keras.layers.Dense(10000, activation=keras.activations.relu),
        keras.layers.Dense(10, activation=keras.activations.softmax)])
    model.call(np.random.standard_normal((1,1000))) # seful for seq.
    model.summary()
    model.compile(optimizer='sgd', loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True))

    model.fit(x,y)

    print(gc.garbage)
```

**Comment by fchollet** [comment]
> Tried this as well tf.Graph.Dismantle(model) but got:

This is an interesting idea, you would need to call it with the graphs associated with each of the tf.functions created by the model. Right now they're not referenced though.

**Comment by Husseinshtia1** [comment]
🚨 **Memory Issues in TensorFlow? We've engineered a battle-tested fix.**

Hi all — if you're experiencing:

- Orphaned background threads post-training
- Dynamic tensor shapes breaking graph conversion
- CUDA memory not released after session end
- Unexplained GPU memory fragmentation in long runs

You're not alone. These aren't edge bugs — they're systemic *Eclipse Leaks*.

A recent study (arXiv:2502.12115) shows these hidden residues can cause **10–25% GPU waste**, costing AI pipelines billions annually.  
📄 [Read the study](https://arxiv.org/pdf/2502.12115)

---

### ✅ **Introducing: CollapseCleaner**

A standalone diagnostic & repair SDK built from advanced runtime collapse analysis in WaveMind AI systems.

#### Core Fixes:
- `clean_orphaned_threads()` — Clears zombie threads left by DataLoaders or TF workers.
- `freeze_tensor_shape(model)` — Prevents shape-shifting tensors that break ONNX export or conversion tools.
- `detect_unreleased_cuda_contexts()` — (Beta) Flags memory pools not reclaimed after training.

---

### 🧠 Use Cases (Backed by WaveMind + arXiv):
- Stabilize PyTorch & TensorFlow memory in CI/CD pipelines
- Prevent memory collapse in 24/7 serving environments
- Debug intermittent GPU memory fragmentation
- Stop silent leaks after `fit()` or `train_on_batch()` sessions

🔗 **Origin & architecture breakdown in our LinkedIn post:**  
https://www.linkedin.com/pulse/invisible-leak-draining-billions-from-ai-until-now-hussein-shtia-h20rf/
