### ISSUE TITLE
TextVectorization returns 'int64' vs 'float32' in TF 2.7 / nightly + Training simple unigram/bigram models much slower than in 2.15

### ISSUE THREAD

**Issue by jchwenger** [keras-team/keras#20249]
Hi there,

I'm running into issues when proofreading some teaching materials based on @fchollet  *Deep Learning With Python* & [repo](https://github.com/fchollet/deep-learning-with-python-notebooks). 

Running [this Colab notebook](https://drive.google.com/file/d/130cVhEsJT6J-z6f180I3S6DbOb5W8kAa/view?usp=sharing), (which is chapter 11, first part, but fleshed out for teaching, this should be runnable out of the box) is *much* slower in the current versions of TensorFlow (2.17, or nightly), than in 2.15. I am unsure as to where this comes from, as the nets used in this are just fully-connected layers on unigrams/bigrams (XLA compilation seems to play a role, although that seems a lot). The slowness is particularly striking during the `evaluate()` step, where the XLA acceleration happening after the second epoch of training does not happen. I'm wondering if there's something obvious that's wrong in the code, or in the update...

Also, I notice that the `TextVectorization` layer seems to be returning `int64` in TF 2.17 and nightly, as opposed to `float32` previously. I did not find any mention of this in the documentation. Is this the desired behaviour?

Thanks in advance!

(First submitted on the [Tensorflow repo](https://github.com/tensorflow/tensorflow/issues/75423), they redirected me here.)

**Comment by fchollet** [comment]
Thanks for the report. It seems we had a slow implementation of multihot encoding for TF. I fixed it at head.

**Comment by jchwenger** [comment]
Thanks for this!
