### ISSUE TITLE
Allow to pass **kwargs to optimizers.get

### ISSUE THREAD

**Issue by manuelblancovalentin** [keras-team/keras#20251]
https://github.com/keras-team/keras/blob/f6c4ac55692c132cd16211f4877fac6dbeead749/keras/src/optimizers/__init__.py#L72-L97

When dynamically getting an optimizer by using tf.keras.optimizers.get(<OPT_NAME>), it would be extremely useful if one could also pass extra arguments to the function, so that the optimizer gets initialized properly. See below a test example of the behavior I would like to see: 

```python
optimizer_name = 'adam'
opt_params = {'learning_rate': 3e-3, 'beta_1': 0.9, 'beta_2': 0.999, 'epsilon' : 1e-07, 'amdsgrad': True}

import tensorflow as tf 
opt = tf.keras.optimizers.get(optimizer_name, **opt_params)

assert(opt.learning_rate == opt_params['learning_rate']), "Opt learning rate not being correctly initialized"

```

**Comment by fchollet** [comment]
You can achieve the same via

```python
opt = getattr(optimizers, "Adam")(**opt_params)
```
