### ISSUE TITLE
Error: ValueError: Cannot get result() since the metric has not yet been built during model.fit()

### ISSUE THREAD

**Issue by rohitcodism** [keras-team/keras#20273]
### 1. **Title:**
**Error: ValueError: Cannot get result() since the metric has not yet been built during model.fit()**

## Summary
I encountered a `ValueError: Cannot get result() since the metric has not yet been built` when trying to train my model using `model.fit()`. This happens in the first epoch, and the error is thrown from `compile_utils.py`.
```markdown
## Error Traceback
```plaintext
Epoch 1/10
Traceback (most recent call last):
  File "path/to/train.py", line 85, in <module>
    model_test_1.fit(
  File "C:\Path\to\Python312\Lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Path\to\Python312\Lib\site-packages\keras\src\trainers\compile_utils.py", line 356, in result
    raise ValueError(
ValueError: Cannot get result() since the metric has not yet been built.
```

## Environment Details
- **TensorFlow Version**: 2.17.0
- **Keras Version**: 3.5.0
- **Python Version**: 3.12.4

## Additional Information
I am using a model with two inputs, and I have defined the metrics as part of `model.compile()`. However, I am still encountering the above error.

Any guidance on what could be causing this issue would be appreciated. Thank you!

**Comment by sachinprasadhs** [comment]
Could you please provide some sample reproducible code to debug. Thanks!

**Comment by james77777778** [comment]
@rohitcodism 
This should be fixed in the master branch. If you encounter the same issue: https://github.com/keras-team/keras/issues/20188

You can test it by installing the latest version of keras:
```bash
pip3 install keras-nightly
```

**Comment by rohitcodism** [comment]
The issue is resolved when using 
Tensorflow 2.15.0

but 
Tensorflow 2.17.0 still has the issue.

**Comment by sachinprasadhs** [comment]
@rohitcodism , Use keras directly for your model, since the above linked fix will be available in Keras-nightly version, where Tensorflow 2.17.0 uses Keras >=3.2 
Example:
```
!pip install keras-nightly
import keras
from keras.layers import Dense
```

**Comment by rohitcodism** [comment]
Okay, I have resolved the issue, Thank You !!
