### ISSUE TITLE
Model build uses incorrect input shape, TF 2.16.1 and 2.17 with keras3

### ISSUE THREAD

**Issue by ml-inr** [keras-team/keras#20299]
Suppose that you have a model that splits its input as follows:
```
x = intuts[:,:,:-1]
mask = intuts[:,:,-1:]
```
Let further `x` be used in a custom layer, `y=layer(x)`. This layer should be build using the shape of x. However, since TF version 2.16.1, the layer fails to be build correctly (using `keras3`, not `tf-keras`). See [this ](https://colab.research.google.com/drive/1ULMSpyTnkCFmg0OZYa_8hte2rnqY6iVx?usp=sharing) very simple example on google collab.

It was verified that using `tf-keras` resolves the issue. So that the bug is in keras3 or its compatibility with TF. See also the [corresponding issue ](https://github.com/tensorflow/tensorflow/issues/76576) at TF.

**Comment by mehtamansi29** [comment]
Hi @ml-inr-

There is conflict  for defining name(matrix and bias) in add_weight method. In keras3, add_weight method can accept name like this `name=<name of layer>`.

By changing the naming declaration in add_weight method will resolve the error. 
```
self.matrix_layer = self.add_weight(name="matrix", shape=(num_fs, self.out_dim), initializer="glorot_uniform")   
self.bias = self.add_weight(name="bias", shape=(self.out_dim,), initializer="zeros")                       

```
Attached [gist](https://colab.research.google.com/gist/mehtamansi29/1eebb8cf2183eef3502ef8b1577b0334/20299-model-build-uses-incorrect-input-shape-tf-2-16-1-and-2-17-with-keras3.ipynb) for your reference.

**Comment by ml-inr** [comment]
Hi @mehtamansi29 !
Using keyword `name` in the `add_weight` does resolve the issue, thanks! This follows [Keras documentation](https://keras.io/api/layers/base_layer/#addweight-method) on Layer class, my bad. 
Shouldn't, however, my initial code yield an error that I'm not properly using the Layer class (non-keyword arguments)?

**Comment by mehtamansi29** [comment]
> Shouldn't, however, my initial code yield an error that I'm not properly using the Layer class (non-keyword arguments)?

Yes. Your initial code yielding error because declaring name without using keyword. So while building the layer it tries to take `"matrix"` in  `self.matrix_layer = self.add_weight("matrix", shape=(num_fs, self.out_dim), initializer="glorot_uniform")` as shape.
