### ISSUE TITLE
Webpage not rendering correctly

### ISSUE THREAD

**Issue by dkgaraujo** [keras-team/keras#20297]
Please see the attached image. As you can see, the documentation for the `Attention` layer is not rendering correctly.

![Screenshot 2024-09-27 at 13 43 06](https://github.com/user-attachments/assets/0ba55cef-51ac-4223-b350-0118d52b079d)

**Comment by mehtamansi29** [comment]
Hi @dkgaraujo-

Can you please let me know what kind of documentation for the Attention layer is not rendering correctly ? I am able to render the page correctly [here](https://keras.io/api/layers/attention_layers/attention/).
