### ISSUE TITLE
Problem with 'name' attribute when subclassing keras.losses.Loss

### ISSUE THREAD

**Issue by caiuspetronius** [keras-team/keras#20366]
I get the following error when subclassing the Loss class. 
lib/python3.9/site-packages/keras/src/losses/loss.py", line 40, in __init__
    self.name = name or auto_name(self.__class__.__name__)
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
I'm following keras docs and overwrite the Loss call() as follows:
        class MeanAdversarial( keras.losses.Loss ) : 
            def call( self, logits_real, logits_fake ) :
                loss_real = ops.mean( ops.relu( 1. - logits_real ), axis = -1 )  # larger than 1 gives zero loss
                loss_fake = ops.mean( ops.relu( 1. + logits_fake ), axis = -1 )  # smaller than -1 gives zero loss
                return 0.5 * ( loss_real + loss_fake )  # mean of the hinge loss for reals and fakes

**Comment by mehtamansi29** [comment]
Hi @caiuspetronius -

Thanks for reporting the issue. Here created MeanAdversarial() custom loss function with init and call method like this will work fine with model. 
```
class MeanAdversarial(keras.losses.Loss):
  def __init__(self, name = 'mean_adversarial'):
    super().__init__(name = name)
  
  def call( self, logits_real, logits_fake):
    loss_real = ops.mean( ops.relu( 1. - logits_real ), axis = -1 ) # larger than 1 gives zero loss
    loss_fake = ops.mean( ops.relu( 1. + logits_fake ), axis = -1 ) # smaller than -1 gives zero loss
    return 0.5 * ( loss_real + loss_fake )
```

Attached [gist](https://colab.sandbox.google.com/gist/mehtamansi29/e2ac21b8f949a1b3990cbfb9d38dde6b/20366-problem-with-name-attribute-when-subclassing-keras-losses-loss.ipynb) for your reference with MeanAdversarial() custom loss and simple model.

**Comment by caiuspetronius** [comment]
Ah, this is getting worse. I got the same error while using the build in Hinge loss:
    loss_pos = keras.losses.Hinge(  ops.ones_like( logits_real ), logits_real )
  File "/home/petrovy1/.conda/envs/py39/lib/python3.9/site-packages/keras/src/losses/losses.py", line 349, in __init__
    super().__init__(hinge, name=name, reduction=reduction, dtype=dtype)
  File "/home/petrovy1/.conda/envs/py39/lib/python3.9/site-packages/keras/src/losses/losses.py", line 21, in __init__
    super().__init__(name=name, reduction=reduction, dtype=dtype)
  File "/home/petrovy1/.conda/envs/py39/lib/python3.9/site-packages/keras/src/losses/loss.py", line 44, in __init__
    self.name = name or auto_name(self.__class__.__name__)

**Comment by caiuspetronius** [comment]
I installed keras-nightly last night

**Comment by caiuspetronius** [comment]
Sorry, my bad: I forgot empty parentheses after the class name call: oss_pos = keras.losses.Hinge()( ops.ones_like( logits_real ), logits_real ). It was the same mistake with the custom class, all is working now. Thanks.

**Comment by mehtamansi29** [comment]
Hi @caiuspetronius -

You can create the Hinge loss like this formula **loss = maximum(1 - y_true * y_pred, 0)** which you can find [here](https://keras.io/api/losses/hinge_losses/).

```
class HingeLoss(keras.losses.Loss):
  def __init__(self, name = 'hinge_loss'):
    super().__init__(name = name)

  def call(self, y_true, y_pred):
    y_true = tf.cast(y_true, dtype=tf.int32)
    y_true = tf.one_hot(y_true, depth=10)
    loss = ops.mean(ops.maximum(1 - y_true * y_pred, 0), axis=-1)
    return loss 
```

Attached [gist](https://colab.sandbox.google.com/gist/mehtamansi29/fa678c711eff0113b8eb0a38f0d2fe26/20366-problem-with-name-attribute-when-subclassing-keras-losses-loss.ipynb) for your reference with MeanAdversarial() custom loss and simple model with keras-nightly.

**Comment by caiuspetronius** [comment]
Thanks, this issue is resolved now. I simply forgot to add () after the custom class name during the call.
