### ISSUE TITLE
train_on_batch() outputs progress bar

### ISSUE THREAD

**Issue by aedavids** [keras-team/keras#20361]
I am training a trival GAN using train_on_batch() it does not have a verbose argument. it produced a mount of out put of the form

```
$ head *.out
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step 
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 771us/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 731us/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 770us/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 726us/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 724us/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step
```

setting the following did not resolve the issue
```
tf.get_logger().setLevel('ERROR')
tf.autograph.set_verbosity(0)
tf.config.set_soft_device_placement(False)
```

Python 3.11.10
$
 conda list tensorflow
tensorflow                2.17.0          cpu_py311h6ac8430_2    conda-forge
tensorflow-base           2.17.0          cpu_py311h0e3e7eb_2    conda-forge
tensorflow-estimator      2.17.0          cpu_py311h331965b_2    conda-forge

 $ conda list keras
# Name                    Version                   Build  Channel
keras                     3.4.1              pyhd8ed1ab_2    conda-forge

please see attached test script

Kind regards

Andy

[08_complete_example.py.txt](https://github.com/user-attachments/files/17387565/08_complete_example.py.txt)

**Comment by Grvzard** [comment]
line 68:
```
X = generator.predict(x_input, verbose=0)
```

**Comment by aedavids** [comment]
nice catch. 

This is a code example I copied from a book

**Comment by aedavids** [comment]
nice catch. 

This is a code example I copied from a book
