### ISSUE TITLE
scikit-learn wrappers in keras

### ISSUE THREAD

**Issue by adrinjalali** [keras-team/keras#20399]
`tf.keras.wrappers` used to have scikit-learn wrappers, which were then deprecated and https://github.com/adriangb/scikeras was born at the same time.

However, scikeras doesn't seem to be maintained much at the moment (https://github.com/adriangb/scikeras/issues/329), and keras has left TF namespace in the meantime. I was wondering if you'd consider adding those wrappers back. I'd be happy to help (as a scikit-learn maintainer) if y'all decide to add them again.

I couldn't find this discussion in the repo, sorry if I've missed it.

**Comment by fchollet** [comment]
Thanks for the suggestion! I think these wrappers do provide value to the community.

> I'd be happy to help (as a scikit-learn maintainer) if y'all decide to add them again.

Maybe you could take over the scikeras repo / package if the initial author is ok with that? I still think this functionality works better as a 3rd party package. But also open to have it in core Keras if there's a good reason for that.

**Comment by adrinjalali** [comment]
It seems a major part of the work on the `scikeras` part has been to keep it up-to-date with the latest `keras` versions, and seems challenging to support multiple versions of `keras` at the same time. One can of course lock the versions against `keras` versions, but it seems an easier thing to maintain if it were inside the `keras` repo and released together. This way whatever code in the wrapper, needs to support only a single version of `keras` since they're packaged together; so that's something to consider.

**Comment by fchollet** [comment]
Ok, that's a good argument. If you'd like to open a PR, we'll review it.

**Comment by adrinjalali** [comment]
Cool. Will work on a PR then. Thanks 🙏🏼

**Comment by adriangb** [comment]
Thanks folks.

François I appreciate your help maintaining SciKeras over the years.

Unfortunately I find myself not having used Keras or SciKeras in years not for a day job so I agree someone else taking over the project or it being moved back into Keras would be best. I think the latter is the better move, if it can be done.
