### ISSUE TITLE
The model is traced for each `steps_per_execution` step (Jax backend)

### ISSUE THREAD

**Issue by nicolaspi** [keras-team/keras#20411]
The model is traced for each `steps_per_execution` steps (using Jax backend), increasing the jit compilation time and memory usage proportionally.

This [gist](https://colab.research.google.com/gist/nicolaspi/22e6b66f93a01d2259484015e10268b9/untitled3.ipynb#scrollTo=cMQKuTDqIYX0) demonstrates the issue on `MobileNetV2`:

```
steps_per_execution = 1, model retracing count: 1, memory usage: 622MB, compilation overhead 4.11 seconds.
steps_per_execution = 5, model retracing count: 5, memory usage: 1610MB, compilation overhead 8.10 seconds.
steps_per_execution = 10, model retracing count: 10, memory usage: 3185MB, compilation overhead 14.54 seconds.
steps_per_execution = 20, model retracing count: 20, memory usage: 6337MB, compilation overhead 30.39 seconds.
```

**Comment by fchollet** [comment]
Thanks for the report. I would guess that the would to improve compilation performance is to use something like `scan` https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.scan.html

**Comment by nicolaspi** [comment]
I am preparing a PR for that issue. I tried using `scan`, but it is not the solution because of the memory footprint.
