### ISSUE TITLE
AttributeError: 'KerasHistory' object has no attribute 'layer'

### ISSUE THREAD

**Issue by Neta-Robinzon-Butbul** [keras-team/keras#20423]
I'm encountering the error "AttributeError: 'KerasHistory' object has no attribute 'layer'"

while working with a Keras model.

I'm trying to access layer information, but it seems I'm referencing the wrong object. the version of TensorFlow is 2.17.0 I tried to change the name layer to operation but it's not working.

this is the code:

import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.initializers import glorot_uniform
from tensorflow.keras.layers import Input, ZeroPadding2D, Conv2D, MaxPooling2D, BatchNormalization, Activation, Add, AveragePooling2D, Flatten, Dense, Dropout

input_shape = (96, 96, 1)

X_input = Input(input_shape)

X = ZeroPadding2D((3,3))(X_input)

X = Conv2D(64, (7,7), strides= (2,2), name = 'conv1', kernel_initializer= glorot_uniform(seed = 0))(X)
X = BatchNormalization(axis =3, name = 'bn_conv1')(X)
X = Activation('relu')(X)
X = MaxPooling2D((3,3), strides= (2,2))(X)

X = res_block(X, filter= [64,64,256], stage= 2)

X = res_block(X, filter= [128,128,512], stage= 3)

X = AveragePooling2D((2,2), name = 'Averagea_Pooling')(X)

X = Flatten()(X)
X = Dense(4096, activation = 'relu')(X)
X = Dropout(0.2)(X)
X = Dense(2048, activation = 'relu')(X)
X = Dropout(0.1)(X)
X = Dense(30, activation = 'relu')(X)

model_1_facialKeyPoints = Model( inputs= X_input, outputs = X)
model_1_facialKeyPoints.summary()

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-366-fd266d53d661> in <cell line: 34>()
     32 
     33 
---> 34 model_1_facialKeyPoints = Model( inputs= X_input, outputs = X)
     35 model_1_facialKeyPoints.summary()

4 frames
/usr/local/lib/python3.10/dist-packages/tensorflow/python/keras/engine/functional.py in _validate_graph_inputs_and_outputs(self)
    692       # Check that x is an input tensor.
    693       # pylint: disable=protected-access
--> 694 
    695       layer = x._keras_history.layer
    696       if len(layer._inbound_nodes) > 1 or (

AttributeError: 'KerasHistory' object has no attribute 'layer'

**Comment by mehtamansi29** [comment]
Hi @Neta-Robinzon-Butbul -

Thanks for reporting the issue. Here I am not able reproduce the issue in tensorflow 2.17.0. 
Attached [gist](https://colab.sandbox.google.com/gist/mehtamansi29/f3825880d93e2e88ef50046514835bdd/20423-attributeerror-kerashistory-object-has-no-attribute-layer.ipynb) for the reference.

**Comment by Neta-Robinzon-Butbul** [comment]
![Screenshot_20241029-203247_Chrome.jpg](https://github.com/user-attachments/assets/797b7ff9-f0e3-4304-b34a-0184237d036c)

**Comment by Neta-Robinzon-Butbul** [comment]
Thank you!
