### ISSUE TITLE
Deep Learning Model building error

### ISSUE THREAD

**Issue by bankarrohan09** [keras-team/keras#20449]
InvalidArgumentError                      Traceback (most recent call last)
Cell In[88], line 1
----> 1 history = model.fit(
      2     train_ds,
      3     epochs=EPOCHS,
      4     batch_size=BATCH_SIZE,
      5     verbose=1,
      6     validation_data=val_ds
      7 )

**Comment by mehtamansi29** [comment]
Hi @bankarrohan09 -

Can you provide the sample/dummy code to reproduce this issue ?
