### ISSUE TITLE
About mask layer 

### ISSUE THREAD

**Issue by xiaohua6689** [keras-team/keras#20440]
## model
a = Input(shape=[5])
b = Input(shape=[10])
emb_a = Embedding(8, 5, mask_zero=True)(a)
emb_b = Embedding(20, 5, mask_zero=True)(b)
cat = Concatenate(axis=1)([emb_a, emb_b])
lstm = LSTM(16)(cat)
dense = Dense(1)(lstm)
model = Model(inputs=[a, b], outputs=[dense])
##data
seed_value = 33
np.random.seed(seed_value)
tf.random.set_seed(seed_value)
input_a = np.random.randint(0, 8, size=(1, 5))  # [0, 7]
input_b = np.random.randint(0, 20, size=(1, 10))  # [0, 19]
## Error information
ValueError: Exception encountered when calling BroadcastTo.call().

Attempt to convert a value (None) with an unsupported type (<class 'NoneType'>) to a Tensor.

Arguments received by BroadcastTo.call():
  • x=tf.Tensor(shape=(1, 5, 1), dtype=bool)

**Comment by mehtamansi29** [comment]
Hi @xiaohua6689 -

Thanks for reporting the issue. Here you are getting `ValueError: Exception encountered when calling BroadcastTo.call().` error because mismatch in input layer shape of model  and provided data(input_a,input_b). 
Here simple using Reshaping layer to emb_a and emb_b output with reshape provided data will resolve the error. 

```
emb_a = Reshape((5, 5))(emb_a)
emb_b = Reshape((10, 5))(emb_b)
```

Attached [gist](https://colab.sandbox.google.com/gist/mehtamansi29/a8eef56ddca749ad2e438ef5bb003680/20440-about-mask-layer.ipynb) for the reference.

**Comment by xiaohua6689** [comment]
Using Rashape layer encountered new Error " UserWarning: Layer 'reshape' (of type Reshape) was passed an input with a mask attached to it. However, this layer does not support masking and will therefore destroy the mask information. Downstream layers will not see the mask." 
New information for you, the version of tensorflow installed on my pc is 2.18.0, when i back the version of tensorflow to 2.10.0, the  code run well.

> Hi @xiaohua6689 -
> 
> Thanks for reporting the issue. Here you are getting `ValueError: Exception encountered when calling BroadcastTo.call().` error because mismatch in input layer shape of model and provided data(input_a,input_b). Here simple using Reshaping layer to emb_a and emb_b output with reshape provided data will resolve the error.
> 
> ```
> emb_a = Reshape((5, 5))(emb_a)
> emb_b = Reshape((10, 5))(emb_b)
> ```
> 
> Attached [gist](https://colab.sandbox.google.com/gist/mehtamansi29/a8eef56ddca749ad2e438ef5bb003680/20440-about-mask-layer.ipynb) for the reference.

**Comment by mehtamansi29** [comment]
Hi @xiaohua6689 -

Here you can use separate keras.layers.Masking layer along with embedding layer. Embedding layer represent the integer into dense vectors and masking is used to handle variable length sequences. 

```
a = Input(shape=[5],dtype=tf.int32)
b = Input(shape=[10],dtype=tf.int32)
emb_a = Embedding(8, 5)(a)
emb_b = Embedding(20, 5)(b)

mask_a = Masking(mask_value=0)(emb_a)
mask_b = Masking(mask_value=0)(emb_b)

emb_a = Reshape((5, 5))(emb_a)
mask_a = Reshape((5, 5))(mask_a)
emb_b = Reshape((10, 5))(emb_b)
mask_b = Reshape((10, 5))(mask_b)

cat = Concatenate(axis=1)([emb_a, emb_b])
lstm = LSTM(16)(cat)
dense = Dense(1)(lstm)
model = Model(inputs=[a, b], outputs=[dense])
model.compile(optimizer='adam', loss='mse')
model.summary()
```

Attached [gist](https://colab.sandbox.google.com/gist/mehtamansi29/a5543374f9eba52d6ab921bc826f9f0b/20440-about-mask-layer-1.ipynb) for the reference.
