### ISSUE TITLE
Need to explicitly specify `x` and `y` instead of using a generator when the model has two inputs.

### ISSUE THREAD

**Issue by danica-zhu** [keras-team/keras#20518]
tf.__version__: '2.17.0'
tf.keras.__version__: '3.5.0'

for a image caption model, one input is vector representation of images, another is caption of encoder.
```python
def batch_generator(batch_size, tokens_train, transfer_values_train, is_random_caption=False):
       # ...
        x_data = \
        {
            'transfer_values_input': transfer_values, #transfer_values
            'decoder_input': decoder_input_data # decoder_input_data
            
            
        }

        y_data = \
        {
            'decoder_output': decoder_output_data
        }
        
        yield (x_data, y_data)
```

then train on this is not work, it mistake the "decoder_input"  or "decoder_output" as the "transfer_values_input" for the model, even with right parameters name in the model.
```python
decoder_model.fit(x=flick_generator,
                  steps_per_epoch=flick_steps_per_epoch,
                  epochs=20,
                  callbacks=flick_callbacks)
```
only explicitly specify `x` and `y` will work.

```python
from tqdm import tqdm 
for epoch in tqdm(range(2)): 
    for step in range(flick_steps_per_epoch):
        x_data, y_data = next(flick_generator)

        decoder_model.fit(
            x=x_data,
            y=y_data,
            batch_size=len(x_data[0]), 
            verbose=0, 
        )

    print(f"Epoch {epoch+1} completed.")
```

**Comment by dhantule** [comment]
Hi @danica-zhu,
Thanks for reporting this. It seems like your `batch_generator` is yielding a tuple of dictionaries, which is being incorrectly interpreted by `model.fit`. Could you please share the standalone code along with the error message you're receiving to reproduce the issue? Thanks!
