### ISSUE TITLE
EarlyStopping instance is not reusable

### ISSUE THREAD

**Issue by maciejbiesek** [keras-team/keras#20521]
From my observations it seems that we cannot use the same instance of EarlyStopping callback when training multiple models. My assumption is that it saves the best value from one training and uses it to compare during the training of the next model.

In `on_train_begin` we have comment "# Allow instances to be re-used", however the value `self.best` is not cleared. I think it should be reinitialized with ` self.best = (float("inf") if self.monitor_op == ops.less else -float("inf"))` as in `__init__()`.

**Comment by hertschuh** [comment]
@maciejbiesek ,

Thank you for the report. The fix is in and should be in the `keras-nightly` pip package tomorrow.
