### ISSUE TITLE
Problem with GRU simulation

### ISSUE THREAD

**Issue by kokhazade** [keras-team/keras#20535]
Hello,

I am going to implement the GRU computations in my code and compare the results with the output of a GRU layer. To this end, I am using a same input for both cases and get the weights of GRU and pass it to my_GRU_simulation function. By using the following code for inner gates calculations, I get two different outputs for these two cases.
Is there any extra calculations (rather than following) that I have missed?
How can I create the exactly same output as a GRU layer?

```
        import tensorflow as tf
        from keras import backend

        GRU_layer_input = tf.squeeze(GRU_layer_input, axis=1)
        matrix_x = backend.dot(tf.convert_to_tensor(GRU_layer_input), tf.convert_to_tensor(gru_layer_weights[0]))
        matrix_x = backend.bias_add(matrix_x, gru_layer_weights[2][0])
        x_z, x_r, x_h = tf.split(matrix_x, 3, axis=1)

        matrix_y = backend.dot(tf.convert_to_tensor(previous_gru_output), tf.convert_to_tensor(gru_layer_weights[1]))
        matrix_y = backend.bias_add(matrix_y, gru_layer_weights[2][1])
        recurrent_z, recurrent_r, recurrent_h = tf.split(matrix_y, 3, axis=1)

        z = tf.sigmoid(x_z + recurrent_z)
        r = tf.sigmoid(x_r + recurrent_r)
        hh = tf.tanh(x_h + r * recurrent_h)

        h = z * h_tm1 + (1 - z) * hh
        new_state = [h] if tf.nest.is_nested(previous_gru_output) else h
```

previous_gru_output is all zero with GRU units size.
I am using tensorflow and keras version 2.11.0

**Comment by kokhazade** [comment]
Hi @sachinprasadhs,
Can you help me with finding the difference source?

**Comment by mattdangerw** [comment]
Just by eye, your implementation looks like it could be correct given the write settings to the GRU layer.

Probably easiest to actually go op by op in the call graph to debug where things get off. Keras 2.11 is quite old at this point (many years old), but you can find the implementation on the 2.11 tag on the Keras repo on github. Here's the GRU code. https://github.com/keras-team/keras/blob/e6784e4302c7b8cd116b74a784f4b78d60e83c26/keras/layers/rnn/gru.py#L308-L350

If I were trying to track this down, I'd give myself an isolated example and get an environment where I could hack up the layer code in GRU. Maybe start be running eagerly, and add a bunch of prints for intermediate computation values, see if that's helps triangulate, go from there.

**Comment by mattdangerw** [comment]
Going to close this as this doesn't seem like a bug, but feel free to reopen if one is encountered.
