### ISSUE TITLE
How to enable Flash-Attn in the PyTorch backend.

### ISSUE THREAD

**Issue by pass-lin** [keras-team/keras#20556]
The 3.7.0 update documentation states that the PyTorch backend is optionally invoked. I now want to call the BERT model from keras_hub. How do I start Flash Attn?

**Comment by mehtamansi29** [comment]
Hi @pass-lin -

Flash attention is used to speed up the GPU by minimizing memory read/writes and accelerate Transformer training and inference.
If you need to use Flash attention with Pytorch backend then you can start from [here](https://github.com/Dao-AILab/flash-attention). 

For more details regarding Flash attention in other backends(Jax or tensorflow), you can follow [this](https://github.com/keras-team/keras/issues/19418). 

And as in keras3.7.0 API changes, need to add `flash_attention` argument to `keras.ops.dot_product_attention` and to `keras.layers.MultiHeadAttention`.  

[Here](https://keras.io/api/layers/attention_layers/multi_head_attention/) define how can add `flash_attention` argument  in  `keras.layers.MultiHeadAttention`
