### ISSUE TITLE
How to run all test cases and generate a coverage report for Keras?

### ISSUE THREAD

**Issue by angiolye24** [keras-team/keras#20583]
Hello,

I am working with the Keras source code and would like to know how to run all the tests in the repository and generate a code coverage report. 

What is the correct command to execute to achieve this?
I am using this command:
```
python3.12 -m pytest keras -n 20 --cov=keras --cov-report=term-missing --cov-branch
```
Thank you in advance.

**Comment by mehtamansi29** [comment]
Hi @angiolye24 -

Using this command you can generate code coverage report of all test run in repository. 
`pytest keras --ignore keras/src/applications --cov=keras --cov-config=pyproject.toml`

**Comment by mehtamansi29** [comment]
Hi @angiolye24 -

For create coverage report as .txt file, you can use [Coverage.py](https://coverage.readthedocs.io/en/7.6.8/) via below commands.
```
coverage run -m pytest keras --ignore keras/src/applications --cov=keras --cov-config=pyproject.toml
coverage report > test_report.txt
```

**Comment by mehtamansi29** [comment]
@angiolye24 - Keras repository doesn't have specific level of parallelism for running tests. If you want to get parrellelism for running tests check jobs/statergy in `.yaml` file in https://github.com/keras-team/keras/tree/master/.github/workflows path.
