### ISSUE TITLE
tf.keras.models.Sequential

### ISSUE THREAD

**Issue by moeinnm-99** [keras-team/keras#20648]
hi dear.

i have problem:
model = tf.keras.models.Sequential([
mobile_net,
### ann layer
tf.keras.layers.Dense(1, activation='sigmoid') #[0, 1] or [1, 0]
])

in new versions of tensorflow and keras it has problme :

ValueError: Only instances of keras.Layer can be added to a Sequential model. Received: <tensorflow_hub.keras_layer.KerasLayer object at 0x77d2995e4680> (of type <class 'tensorflow_hub.keras_layer.KerasLayer'>)

what should i do can you solve it?

this is my code even if you want you can take a look!
thanks

![Screenshot From 2024-12-12 14-47-00](https://github.com/user-attachments/assets/106c142a-24a3-4330-9455-29d679eb5c52)

**Comment by dhantule** [comment]
Hi @moeinnm-99, 

Thanks for reporting this. The error seems to be arising due to some compatibility issue. In `keras 3` you can load the pre trained` MobileNet` model using `mobile_net=keras.applications.MobileNet()`, this will resolve the error. 
Attached [gist ](https://colab.sandbox.google.com/gist/dhantule/39c8b85f4474fb659af053bfaef6f349/tf-keras-models-sequential-20648.ipynb) for your reference.

**Comment by moeinnm-99** [comment]
thanks for your reply ❤️could you show me the edited code ? you mean the problem is on mobile_net? I think it's from model.
-------- Original message --------From: Jasmine Dhantule ***@***.***> Date: 12/16/24  12:38 PM  (GMT+03:30) To: keras-team/keras ***@***.***> Cc: Moein ***@***.***>, Mention ***@***.***> Subject: Re: [keras-team/keras] tf.keras.models.Sequential (Issue #20648) 
Hi @moeinnm-99,
Thanks for reporting this. The error seems to be arising due to some compatibility issue. In keras 3 you can load the pre trained MobileNet model using mobile_net=keras.applications.MobileNet(), this will resolve the error.
Attached gist  for your reference.

**Comment by dhantule** [comment]
Hi @moeinnm-99, if you add the  `mobile_net=keras.applications.MobileNet()` line to your existing code, it should work fine.  Please refer this colab [gist](https://colab.sandbox.google.com/gist/dhantule/39c8b85f4474fb659af053bfaef6f349/tf-keras-models-sequential-20648.ipynb).
```
# Add this line to load the mobilenet model
mobile_net=keras.applications.MobileNet()

# Build a Sequential model
model = keras.Sequential([
    mobile_net,
    keras.layers.Dense(1, activation='sigmoid')
])

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Print the model summary
model.summary()
```

**Comment by moeinnm-99** [comment]
Hello again my friend.  Thanks for your very good help. I am very grateful to you and I hope that whenever you have a problem, it will be solved and if you need help, you can tell me.  Please give me your GitHub and LinkedIn ID so that I don't suddenly lose you.  Thank you again for your help.  Only if you can, please guide me how to learn essential Python libraries like tensorflow and etc as well as you:), and if you have any projects in this field like this (brain tumor detection), I will be glad to share them with me, thank you❤️
-------- Original message --------From: Jasmine Dhantule ***@***.***> Date: 12/16/24  6:45 PM  (GMT+03:30) To: keras-team/keras ***@***.***> Cc: Moein ***@***.***>, Mention ***@***.***> Subject: Re: [keras-team/keras] tf.keras.models.Sequential (Issue #20648) 
Hi @moeinnm-99, if you add the  mobile_net=keras.applications.MobileNet() line to your existing code, it should work fine.  Please refer this colab gist.
# Add this line to load the mobilenet model
mobile_net=keras.applications.MobileNet()

# Build a Sequential model
model = keras.Sequential([
    mobile_net,
    keras.layers.Dense(1, activation='sigmoid')
])

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Print the model summary
model.summary()

**Comment by dhantule** [comment]
Hi @moeinnm-99, 

You can learn more about` tensorflow ` [here](https://www.tensorflow.org/guide/basics) and about `Keras` [here](https://keras.io/getting_started/). You can find deep learning models like `MobileNet` for your projects [here](https://keras.io/api/applications/). Please close this issue if your original error is resolved, feel free to open another one if you need more assistance.

**Comment by moeinnm-99** [comment]
surethanks for your all supports
-------- Original message --------From: Jasmine Dhantule ***@***.***> Date: 12/18/24  10:09 AM  (GMT+03:30) To: keras-team/keras ***@***.***> Cc: Moein ***@***.***>, Mention ***@***.***> Subject: Re: [keras-team/keras] tf.keras.models.Sequential (Issue #20648) 
Hi @moeinnm-99,
You can learn more abouttensorflow here and about Keras here. You can find deep learning models like MobileNet for your projects here. Please close this issue if your original error is resolved, feel free to open another one if you need more assistance.

**Comment by moeinnm-99** [comment]
Thanks toour friend that help us for this issue
it was happened because of the changes in keras3:/
