### ISSUE TITLE
Keras API reference has not been updated yet

### ISSUE THREAD

**Issue by shashaka** [keras-team/keras#20675]
Even though Keras 3.7.0 has been released, it seems the API reference has not yet been updated.
For example, I couldn't find the CELU activation function listed on [the activations page.](https://keras.io/api/layers/activations/)
Please feel free to let me know if I have misunderstood something.

Thank you!

**Comment by fchollet** [comment]
Thanks for the report! All documented API symbols have to be listed in `keras-io/scripts/api_master.py`. If any symbol is missing, you can open a PR to `keras-io` to edit the `master` files to add the symbol.

**Comment by shashaka** [comment]
Ok, I will open a PR for that. Thanks
