### ISSUE TITLE
ValueError: creating distributed tf.Variable with aggregation=MEAN and a non-floating dtype is not supported, please use a different aggregation or dtype

### ISSUE THREAD

**Issue by innat** [keras-team/keras#20700]
It happens while using [keras-models](https://keras.io/api/applications/) in kaggle tpu.

**Comment by Thorballer** [comment]
It happened to me too and I have no idea how to fix it.

**Comment by kkoperskidg** [comment]
I downgraded keras to 3.6.0 and it seems to fix the issue (althought something else popped up)
