### ISSUE TITLE
How Would I add a Noise Input To Hidden Layers In a Graphical Model?

### ISSUE THREAD

**Issue by neillpatterson** [keras-team/keras#2162]
Imagine your favourite NN architecture, and say some internal layer has 10 hidden units.  Let's say you want to add noise to each of those 10 hidden units, but you want the back prop algorithm to account for this noise when computing gradients. This is something I can do in pure TensorFlow, but I'm to do it in Keras with a  Theano backend for speed purposes.

Here's a very simple example code that is just doing linear regression y = Wx + b and then adds noise.

```
model = Graph()
model.add_input(name="x_input", input_shape=(2,))
model.add_input(name="noise_input", input_shape=(1,))
model.add_node(Dense(input_dim=2, output_dim=1), name="dense", input="x_input")

#The next line generates an error. Exception: Unknown identifier: noise_input
model.add_output(name='output', inputs=['dense', 'noise_input'], merge_mode='sum')
model.compile(loss={'output':'mse'}, optimizer='sgd')
```

Can anyone help me out here?  Does it not liking on inputs directly?  

If there is a sequential model way of doing this, that would probably be even easier.

**Comment by neillpatterson** [comment]
For reference, here's some code in pure TensorFlow that does the same thing with this simple linear regression model:

`# Setup placeholders
x = tf.placeholder(dtype=np.float32, shape=(None, 2), name='x')
y = tf.placeholder(dtype=np.float32, shape=(None, 1), name='y')
noise = tf.placeholder(dtype=np.float32, shape=(None,1), name='noise')

# Setup trainable variables
W = tf.Variable( np.random.rand(2,1).astype(np.float32), name='W')
b = tf.Variable(np.random.rand(1,1).astype(np.float32), name='b')

# Setup operations
y_ = tf.add( tf.matmul(x,W)  , b  , name='y_')
loss = tf.reduce_mean(tf.square(y - y_), name = 'mse')
optimizer = tf.train.GradientDescentOptimizer(0.5)
train = optimizer.minimize(loss, name='train')
grad = tf.gradients(y_, x, name='grad')
`

**Comment by jpeg729** [comment]
You just add a GaussianNoise layer in between layers.
http://keras.io/layers/noise/

Something like...
```
model = Sequential()
model.add(Dense(10))
model.add(GaussianNoise( how_much_noise ))
model.add(Dense(10))
...
```

GaussianNoise can be used as the first layer in which case you may need to specify the input_shape, or in between layers.

**Comment by apacha** [comment]
Are there any examples or best-practises, how much noise should be added, i.e. in which range `how_much_noise` should be?

**Comment by Ac2zoom** [comment]
@apacha The original Dropout paper (https://www.cs.toronto.edu/~hinton/absps/JMLRdropout.pdf around pg. 17) describes the optimal dropout percentage being 50%, though a range of 20%-80% is considered.

**Comment by UpCoder** [comment]
Hi, I am using Functional Model. When I write the code
```
inputs = tf.keras.Input([512, 512, 1], batch_size=None, name='x-input', dtype=tf.float32)
GaussianNoise(stddev=0.01)(inputs)
```
Then, there will be a error, the message as followed:
```
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 589, in __call__
    previous_mask = _collect_previous_mask(inputs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 2799, in _collect_previous_mask
    mask = node.output_masks[tensor_index]
AttributeError: 'Node' object has no attribute 'output_masks'
```
The way I call the Noise layer in functional model is wrong?

**Comment by ferreirafabio** [comment]
same issue here

**Comment by UpCoder** [comment]
```
from keras.layers import Input
from keras.layers.noise import GaussianNoise
inputs = Input(shape=(512, 512, 1), name='x-input', dtype=tf.float32)
GaussianNoise(stddev=0.01)(inputs)
```
It works, I guess the reason may be the version of keras packaged in tensorflow is not matched.

**Comment by ferreirafabio** [comment]
```
from keras.layers import Dense, Input
from keras.layers.noise import GaussianNoise

inp = Input(tensor=self.X_ph)
noised_x = GaussianNoise(stddev=self.x_noise_std)(inp)
x = Dense(15, activation='elu')(noised_x)
x = Dense(15, activation='elu')(x)
self.estimator = x
```
this code doesn't produce the expected noise when I check with:
`noised_x = self.sess.run(self.X_ph, feed_dict={self.X_ph: X, self.y_ph: Y})` since `np.allclose(noised_x, X)` returns true (it's not a precision problem)

**Comment by ferreirafabio** [comment]
maybe someone can help out here:
https://stackoverflow.com/questions/49435335/check-if-noise-is-really-used-during-training-with-keras-edward-and-tensorflow
