### ISSUE TITLE
Requests for contribution

### ISSUE THREAD

**Issue by fchollet** [keras-team/keras#3617]
A few items that are up for grabs right now! If you're looking to contribute to Keras, working on one of these would be a great place to start.
- An example script of feedforward neural doodle (e.g. [this](https://github.com/DmitryUlyanov/online-neural-doodle)).
- An example script to generate reasonable-sounding MIDI tracks using a LSTM trained on an open MIDI dataset.
- Create versions of the weights files of VGG16, VGG19, ResNet50 and Inception V3 fine-tuned on a face dataset.
- [DONE] Test improvements: stricter PEP8 checks in our PEP8 test. That's an easy one. In particular, we need to check for missing spaces after commas, trailing spaces, this kind of thing.

**Comment by dolaameng** [comment]
I am interested. Will take a look at each and try to contribute if possible.

**Comment by 0bserver07** [comment]
* [MIDI-LSTM] There is a [music_rnn project](https://github.com/jamong/music-rnn/blob/master/rnn_lstm_jzs1_eng/train_piano.py) that generates decent Midi piano, seems that Keras is used for this bit of the model.

  Would a simplified version of this work?

* For the feedforward neural doodle, Here is a clear [model layout in Lua](https://github.com/DmitryUlyanov/online-neural-doodle/blob/master/feedforward_neural_doodle.lua) as you posted I can try out with the VGG being available to load in Keras, but I have to see if I can replicate the same results.   
  * Also this example being available, makes it easier to create for [neural_style_transfer](https://github.com/fchollet/keras/blob/master/examples/neural_style_transfer.py)

**Comment by fchollet** [comment]
> Would a simplified version of this work?

Yes. We would have to:
- package a dataset to be automatically downloaded and used by default
- provide the ability to specify a folder where to find the MIDI files, so that users can train on their own data

> For the feedforward neural doodle, Here is a clear model layout in Lua as you posted I can try out with the VGG being available to load in Keras, but I have to see if I can replicate the same results.

Sounds good.

**Comment by dolaameng** [comment]
I am thinking about porting this [neural-doodle](https://github.com/alexjc/neural-doodle) by alexjc from lasagne to keras. It is using a simpler model compared to DmitryUlyanov's online doodling in Torch. What do you think?

**Comment by kemaswill** [comment]
I think [LSTMetallica](https://github.com/keunwoochoi/LSTMetallica) is quite a good implementation for the MIDI task, I will implement the MIDI example based on it.

**Comment by kemaswill** [comment]
The Example for MIDI is almost done, still tuning the parameters to get the result as good as those posted on [soundcloud](https://soundcloud.com/kchoi-research/sets/lstmetallica-drums) by Keunwoo Choi , please see [here](https://github.com/kemaswill/keras/blob/MIDI_Example/examples/midi_lstm.py) for the current example.

**Comment by kemaswill** [comment]
Have tuned the models many times in order to reach the performance claimed by the authors, but the result is still disappointed w.r.t. both performance and training time.

**Comment by Don86** [comment]
Hi, I'm new to contributing in general, and would like to give these shot.

**Comment by mzaradzki** [comment]
Hi,
For VGG-Face, I wrote this Notebook that translate *MatConvNet* weight file into a Keras ConvNet : 
https://github.com/mzaradzki/neuralnets/blob/master/vgg_faces_keras/vgg_faces_demo.ipynb

The weights are translated using the *scipy.io.loadmat* function.

I also added a demo of pre-processing with OpenCV to extract the face box to improve the model prediction.

**Comment by bzamecnik** [comment]
As for MIDI generation in Keras I've done some project like this before. Possibly I could simplify some code and package it as an example.

**Comment by gabrieldemarmiesse** [comment]
@fchollet do you still want the MIDI example and the fine tuning on a faces dataset? If yes I'll close this issue and open two new ones. It will be easier for contributors to find topics where they can help.
