### ISSUE TITLE
error in importing keras with theano  

### ISSUE THREAD

**Issue by moh3th1** [keras-team/keras#3794]
I am using anaconda with python 2.70 on windows 10_64X , but when I import keras I still get this error. I am using theano and keras tell me it's Tensorflow ?!!
_`import theano 

import keras
Using TensorFlow backend.
Traceback (most recent call last):

  File "<ipython-input-2-c74e2bd4ca71>", line 1, in <module>
    import keras

  File "C:\Users\moh\Anaconda2\envs\keras_env\lib\site-packages\keras__init__.py", line 2, in <module>
    from . import backend

  File "C:\Users\moh\Anaconda2\envs\keras_env\lib\site-packages\keras\backend__init__.py", line 64, in <module>
    from .tensorflow_backend import *

  File "C:\Users\moh\Anaconda2\envs\keras_env\lib\site-packages\keras\backend\tensorflow_backend.py", line 1, in <module>
    import tensorflow as tf

ImportError: No module named tensorflow`_
![image](https://cloud.githubusercontent.com/assets/15180702/18604772/1f107c00-7c81-11e6-8406-faaa467e4c5c.png)

**Comment by keunwoochoi** [comment]
https://keras.io/backend/, check out the setting in  `~/.keras/keras.json`.

**Comment by NaderNazemi** [comment]
I am having the same problem as "moh3th1"
I looked for "keras.json" 
But the file does not exist. 
Thank you

**Comment by ch3ll0v3k** [comment]
If you dont have a file in your home directory. 

Then just make it and put this in there. If you want you use Theano. See doc page for TensorFlow
https://keras.io/backend/

$ nano ~/.keras/keras.json

{
    "image_dim_ordering": "th",
    "epsilon": 1e-07,
    "floatx": "float32",
    "backend": "theano"
}

**Comment by nrj89** [comment]
Thanks to ch3ll0v3k...
it solved my issue...

**Comment by KManish9011** [comment]
i create file on this C:\Users\Manish\Anaconda2\Lib\site-packages\keras path by the name of keras.json and write the same code json code : 
{
"image_dim_ordering": "th",
"epsilon": 1e-07,
"floatx": "float32",
"backend": "theano"
}

But the error is'nt gone. Please Tell me the solution of this problem.

![untitled1](https://cloud.githubusercontent.com/assets/26160684/23544081/624560b2-001b-11e7-8c11-ac17e221f186.png)

**Comment by Ubikas** [comment]
Hi,

after update to keras 2.0.1 I've updated keras.json attribute "image_dim_ordering" to
"image_dim_ordering": "channels_first", but keras still takes as "channels_last"

I've done it manually:
import keras
from keras import backend as K
K.set_image_data_format('channels_first')

**Comment by mikelibg** [comment]
I tried chaning the keras.json file but it did not help me.
What solved the issue for me was setting the KERAS_BACKEND env variable to "theano":
>>> export KERAS_BACKEND=theano
This env variable is overriding the keras.json settings.

**Comment by sozykin** [comment]
@Ubikas, you should use "image_data_format": "channels_first" instead of "image_dim_ordering": "channels_first".

**Comment by Ubikas** [comment]
@sozykin , thanks, yes, it had been fixed long ago, just forgot to update the issue description. Anyway with theano background it doesn't work anyway :(

**Comment by CharuniKaushalya** [comment]
I had the same issue. I am using anaconda with python 3.6 on windows 10. 
I rewitre the file on this C:\Users\USERNAME\.keras path by the name of keras.json  :
{
    "floatx": "float32",
    "epsilon": 1e-07,
    "backend": "theano",
    "image_data_format": "channels_last"
}
Then i run` conda install -c anaconda libpython=2.0 ` to install libpython.
It works for me. Thanks

**Comment by yashfujifilm** [comment]
{
  "epsilon": 1e-07,
  "image_data_format": "channels_first",
  "floatx": "float32",
  "backend": "cntk"
} 

This is the data in my keras.json file, but I still get the error saying that 'no module named 'tensorflow' '

**Comment by grvjn06** [comment]
@yashfujifilm change backend to theano, that worked for me!

**Comment by mojtaba-Hsafa** [comment]
I am using Anaconda and I had similar problem I fixed it by going to : \Anaconda3\etc\conda\activate.d folder and modifying the content of keras_active with following:
set "KERAS_BACKEND=tensorflow"

**Comment by wt-huang** [comment]
Closing as this is resolved
