### ISSUE TITLE
Predict_generator problem - could not broadcast input array

### ISSUE THREAD

**Issue by MCin22** [keras-team/keras#3896]
Hi there! (I'm up-to-date with the master branch of Keras and using latest TensorFlow on Python 3.4). I'm trying to use predict_generator. Here is my generator (that converts data from scipy sparse to dense matrix):

```
def batch_predict_generator(X, batch_size):
    number_of_batches = X.shape[0]//batch_size
    while 1:
        for i in range(number_of_batches):
            yield X[i*batch_size:(i+1)*batch_size].todense()
```

I'm using fit_generator that is similar to this generator to fit my data into MLP network and everything is fine. Here is my network model:

```
    model = Sequential()
    model.add(Dense(128, batch_input_shape=(None, x_size,)))
    model.add(Activation('relu'))
    model.add(Dropout(0.2))
    model.add(Dense(64))
    model.add(Activation('relu'))
    model.add(Dropout(0.2))
    model.add(Dense(2)) # amount of classes
    model.add(Activation('softmax'))
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=["accuracy"])
```

batch_size is equal 256, x_size is equal 20573.

However I'm getting the following error when using predict_generator like this:
`pred_y = model.predict_generator(generator=batch_predict_generator(X_test, batch_size), val_samples=X_test.shape[0])`

**ValueError: could not broadcast input array from shape (256,2) into shape (238,2)**

It weird, because fit_generator and evaluate_generator are working correctly. I'm using it like this

`score = model.evaluate_generator(generator=batch_generator(X_test, Y_test, batch_size), val_samples=X_test.shape[0])`

Could anybody help me? What wrong with predict_generator?
During fitting my model I'm getting this warning:

> UserWarning: Epoch comprised more than `samples_per_epoch` samples, which might affect learning results. Set `samples_per_epoch` correctly to avoid this warning.
>   warnings.warn('Epoch comprised more than '

**Comment by MCin22** [comment]
I found a solution - to get this val_samples for model.predict_generator:

`val_samples=X_test.shape[0] - X_test.shape[0]%batch_size`

Though it doesn't explain, why fit_generator and evaluate_generator were working and predict_generator didn't.

**Comment by AllardJM** [comment]
I have the same issue. Did you ever get resolution? Doesn't the solution you show here just ignore some of the test set?

**Comment by MCin22** [comment]
Sorry, I have only this solution I have written. It ignore some of the test set, but if you work on big data and the batch size is for example 1024, the you lose only little part from the set.

I haven't checked, whether new versions of Keras has fixed this issue.

**Comment by burgalon** [comment]
can we reopen this?

**Comment by kirk86** [comment]
I'm facing the same issue. I don't know why `predict_generator` is behaving this way.

**Comment by kirk86** [comment]
This error is driving me crazy. I tried the solution of @MCin22 but didn't got far. I think its related to the batch size of `ImageDataGenerator`. I think that anything above 64 as batch_size will through an error. I'm testing this hypothesis now.

Another thing that is missing from the wiki regarding the `ImageDataGenerator` is the information regarding the `nbr_train_samples` and `nbr_valid_samples` indicating that they should be a number multiple of `batch_size` in order to avoid the user warning every time we run the `fit_generator`.

```
Traceback (most recent call last):
  File "train.py", line 405, in <module>
    num_folds)
  File "train.py", line 331, in train_model
    valY_pred = model.predict_generator(validation_generator, nb_valid_samples)
  File "/home/user/miniconda2/lib/python2.7/site-packages/keras/engine/training.py", line 1683, in predict_generator
    all_outs[i][processed_samples:(processed_samples + nb_samples)] = out
ValueError: could not broadcast input array from shape (128,8) into shape (34,8)
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/home/user/miniconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/user/miniconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/user/miniconda2/lib/python2.7/site-packages/keras/engine/training.py", line 436, in data_generator_task
    time.sleep(wait_time)
AttributeError: 'NoneType' object has no attribute 'sleep'
```

**Comment by s5kufabi** [comment]
I tried the solution of MCin22, too. Unfortunately it did not work for me neither. I had a look at /keras/engine/training.py and changed line 1777:

`all_outs[i][processed_samples:(processed_samples + nb_samples)] = out`

to

`all_outs[i][processed_samples:(processed_samples + nb_samples)] = out[:min(val_samples - processed_samples, nb_samples)]`

This works even if the sample size is not a multiple of the batch size. But use with caution! I am not familiar with the code at all!

**Comment by EvenOldridge** [comment]
Thanks @s5kufabi that fixed the issue for me too.  Likewise I don't understand the codebase well enough to integrate, but I'd suggest that this be looked at by a keras developer.

**Comment by esamghaleb89** [comment]
if you have a similar problem, check the number of the samples in data generator and the one you provide in predict generator, they must be the same. That was the problem source for me.

**Comment by IWichakam** [comment]
It's weird. I've got the same problem with _predict_
`Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         (None, 30, 512, 512, 1)   0         
_________________________________________________________________
conv3d_1 (Conv3D)            (None, 10, 170, 170, 4)   112       
_________________________________________________________________
batch_normalization_7 (Batch (None, 10, 170, 170, 4)   16        
_________________________________________________________________
activation_2 (Activation)    (None, 10, 170, 170, 4)   0         
_________________________________________________________________
conv3d_2 (Conv3D)            (None, 3, 56, 56, 8)      872       
_________________________________________________________________
batch_normalization_8 (Batch (None, 3, 56, 56, 8)      32        
_________________________________________________________________
activation_3 (Activation)    (None, 3, 56, 56, 8)      0         
_________________________________________________________________
conv3d_3 (Conv3D)            (None, 1, 18, 18, 16)     3472      
_________________________________________________________________
batch_normalization_9 (Batch (None, 1, 18, 18, 16)     64        
_________________________________________________________________
activation_4 (Activation)    (None, 1, 18, 18, 16)     0         
_________________________________________________________________
conv3d_transpose_1 (Conv3DTr (None, 3, 56, 56, 8)      9608      
_________________________________________________________________
batch_normalization_10 (Batc (None, 3, 56, 56, 8)      32        
_________________________________________________________________
activation_5 (Activation)    (None, 3, 56, 56, 8)      0         
_________________________________________________________________
conv3d_transpose_2 (Conv3DTr (None, 10, 170, 170, 4)   3204      
_________________________________________________________________
batch_normalization_11 (Batc (None, 10, 170, 170, 4)   16        
_________________________________________________________________
activation_6 (Activation)    (None, 10, 170, 170, 4)   0         
_________________________________________________________________
conv3d_transpose_3 (Conv3DTr (None, 30, 512, 512, 2)   602       
_________________________________________________________________
batch_normalization_12 (Batc (None, 30, 512, 512, 2)   8         
_________________________________________________________________
activation_7 (Activation)    (None, 30, 512, 512, 2)   0         
_________________________________________________________________
zero_padding3d_1 (ZeroPaddin (None, 30, 514, 514, 2)   0         
_________________________________________________________________
conv3d_4 (Conv3D)            (None, 1, 512, 512, 1)    541       
_________________________________________________________________
reshape_1 (Reshape)          (None, 512, 512, 1)       0         
_________________________________________________________________
activation_8 (Activation)    (None, 512, 512, 1)       0         
=================================================================

Traceback (most recent call last):
  File "test.py", line 220, in <module>
    test.train(steps=1000, batch_size=1)
  File "test.py", line 170, in train
    outs = self.generator.predict(inputs)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 902, in predict
    return self.model.predict(x, batch_size=batch_size, verbose=verbose)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1585, in predict
    batch_size=batch_size, verbose=verbose)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1221, in _predict_loop
    outs[i][batch_start:batch_end] = batch_out
ValueError: could not broadcast input array from shape (24,512,512,1) into shape (1,512,512,1)

`

**Comment by civilinformer** [comment]
I also have this problem with prediction but not with training:

```
/covnet_v65.py in make_submission()
    571         start = finish
    572         finish = finish+batch_size
--> 573         predicted = model.predict(sample, verbose=2)
    574         print("Predicting Test data with sample size: {}...".format(sample.shape))
    575         predicted = predicted.reshape((sample.shape[0],60))

~/py3/lib/python3.5/site-packages/keras/engine/training.py in predict(self, x, batch_size, verbose)
   1515         f = self.predict_function
   1516         return self._predict_loop(f, ins,
-> 1517                                   batch_size=batch_size, verbose=verbose)
   1518 
   1519     def train_on_batch(self, x, y,

~/py3/lib/python3.5/site-packages/keras/engine/training.py in _predict_loop(self, f, ins, batch_size, verbose)
   1148 
   1149             for i, batch_out in enumerate(batch_outs):
-> 1150                 outs[i][batch_start:batch_end] = batch_out
   1151             if verbose == 1:
   1152                 progbar.update(batch_end)

ValueError: could not broadcast input array from shape (22,1,60) into shape (23,1,60)

```

**Comment by zhenbangchen** [comment]
Same here. This is so weird. Basically it is because the number of your samples cannot divide the batch size, for example if you have 600 samples while the batch size is 32, then you will get this error. Because in the last batch there's only 24 samples, while 32 is required.

**Comment by civilinformer** [comment]
That's right. The solution is to pad the rows of your data with zeros so that # samples % batch size == 0. This is OK for prediction, just ignoring the padded rows in the output.

**Comment by veronicamorfi** [comment]
Had the same issue recently. Turns out it was caused because I was training a 4-GPU model. 
I saved the weights for all 4 instances, but should have loaded only one of them for evaluation instead of all for. Basically, I was trying to evaluate on the parallel model and keras was expecting to be able to split the batches between 4 GPUS. 
Loading just the weights of one model and evaluating on that worked for me.

**Comment by RitwikGupta** [comment]
@veronicamorfi Could you tell me how you loaded weights for only one of the instances? I assume you saved the weights with `save_weights`, which outputs to one file, even for a GPU parallel model.

**Comment by veronicamorfi** [comment]
@RitwikGupta I load the weights I saved to the model (this is the parallel one) and then load one of the instances into model1. I hope it helps.

`model.load_weights('path_to_saved_weights.h5')
model_index = number_of_gpus+1
model1 = Model(inputs=model.input,outputs=model.layers[model_index].get_output_at(0))
`

**Comment by serser** [comment]
I've checked the Keras source, it seems the follow line caused it. See [link](https://github.com/keras-team/keras/blob/master/keras/engine/training.py#L1336)

The `outs` get  shape from `shape = (num_samples,) + batch_out.shape[1:]`. However it dropped out the first dimension (batch size) and replaced with the number of samples (prediction input), while in my case, I had a `Concatenation` layer which had `2*num_sample`, which failed prediction. In order to get rid of this, I pull out the last layer, and split it into two.

    desc = model.get_layer("desc_output").output
    left = Lambda(lambda x: x[:1,:,:,:])(desc)
    right = Lambda(lambda x: x[1:,:,:,:])(desc)

    desc_model = Model(model.input, [left, right], name="new-model")
    desc_model.compile(optimizer='adam', loss="binary_crossentropy")

The the prediction is done on the new model `desc_model`. Hope this helps.

**Comment by wt-huang** [comment]
Closing as this is resolved

**Comment by csteel45** [comment]
> I also have this problem with prediction but not with training:
> 
> ```
> /covnet_v65.py in make_submission()
>     571         start = finish
>     572         finish = finish+batch_size
> --> 573         predicted = model.predict(sample, verbose=2)
>     574         print("Predicting Test data with sample size: {}...".format(sample.shape))
>     575         predicted = predicted.reshape((sample.shape[0],60))
> 
> ~/py3/lib/python3.5/site-packages/keras/engine/training.py in predict(self, x, batch_size, verbose)
>    1515         f = self.predict_function
>    1516         return self._predict_loop(f, ins,
> -> 1517                                   batch_size=batch_size, verbose=verbose)
>    1518 
>    1519     def train_on_batch(self, x, y,
> 
> ~/py3/lib/python3.5/site-packages/keras/engine/training.py in _predict_loop(self, f, ins, batch_size, verbose)
>    1148 
>    1149             for i, batch_out in enumerate(batch_outs):
> -> 1150                 outs[i][batch_start:batch_end] = batch_out
>    1151             if verbose == 1:
>    1152                 progbar.update(batch_end)
> 
> ValueError: could not broadcast input array from shape (22,1,60) into shape (23,1,60)
> ```

I am now having the same issue. I can't seem to get a combination of inputs and outputs to work. Has anyone been successful with Stateful LSTMs? With batch_sizes greater than 1?
