### ISSUE TITLE
New datasets and application examples

### ISSUE THREAD

**Issue by fchollet** [keras-team/keras#39]
We're very interested in adding new datasets and new example scripts. 

If you've used Keras to do something neat with open data, we would love to check it out, and possibly include your script or/and add support for the dataset.

**Comment by srepho** [comment]
Really impressed by the straightforward nature of the code and the documentation of the project. I am only a novice at Deep Learning but will hopefully have some posts utilising Keras over the coming weeks to try and give something back. I am just wondering if it is worth setting up a Google Group for Keras to assist people with questions and issues?

**Comment by fchollet** [comment]
Sure, I think it would be useful to have a mailing list of some kind, as opposed to relying on Github notifications for everything. Is it something you want to take care of?

**Comment by srepho** [comment]
Done https://groups.google.com/forum/#!forum/keras-users

**Comment by fchollet** [comment]
Cool, thank you. We probably want to make it open to all, as manually approving memberships seems like a pain, and we don't have any reasons to ever reject one (I would assume Google is pretty good at spam filtering?).

**Comment by srepho** [comment]
Good point - changed settings and have made you an owner to give you full control over the group.

**Comment by jfsantos** [comment]
I mentioned this in #47, but maybe it makes sense to talk about it here too. I implemented a simple class to use data in HDF5 datasets without having to load them into memory, and it works well with keras (except for the issue reported in #47). Code is here: https://gist.github.com/jfsantos/14ae9631716a2aa328c4. Is there any interest in adding it to keras?

**Comment by fchollet** [comment]
I'm looking at your issue... in any case, I think that would definitely be useful to have. Only problem I see is that it increases the list of dependencies (HDF5 + h5py).

I wonder where it could fit... we already have `save_array` and `load_array` functions in `np_utils`, so perhaps we need a `keras.utils.io_utils` module?

**Comment by jfsantos** [comment]
Yes, it adds a small overhead. We could add it as an optional feature with its own dependencies, as shown [here](https://pythonhosted.org/setuptools/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) if that is a big concern.

`io_utils` sounds like a good submodule name, as you are keeping `datasets` for classes that map to actual datasets.

**Comment by ganarajpr** [comment]
@fchollet : If I may suggest, could you have a gitter room ( www.gitter.im ) for keras ? 

Its much more one-on-one in gitter and gives a more slack like communication channel for people to communicate ?

**Comment by dhilton** [comment]
Given this is over two years old is it worth keeping open? Is there still a requirement for new open dataset examples?

**Comment by prakritidev** [comment]
I'm thinking to develop documentation of example code in keras, I feel like there is no documentation of codes. I'm also working on open source data set available on http://deeplearning.net/datasets/

If someone wants to work on documentation or on the data set please let me know.

**Comment by marc-moreaux** [comment]
I have a code to download the audio of Wavenet from youtube videos and a generator to deliver the audio. 
I haven't seen example of datasets yielding data with generators in [datasets](https://github.com/fchollet/keras/tree/master/keras/datasets). Any idea on what should I do ?

As of now it looks like [this ](https://github.com/marc-moreaux/audioset_raw), yet'll be happy to make it more compatible to keras standards.

**Comment by morenoh149** [comment]
I think this issue is resolved by https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md#adding-new-examples it's also not an actionable issue as this project will probably always welcome new examples. It's better addressed by the CONTRIBUTING.md

**Comment by gabrieldemarmiesse** [comment]
As @morenoh149 says, this issue is resolved by the `CONTRIBUTING.md`.
