### ISSUE TITLE
where can i download keras documentation???

### ISSUE THREAD

**Issue by litingsjj** [keras-team/keras#4466]
thank you !!!!!!!

**Comment by litingsjj** [comment]
i want to print it!!!!

**Comment by JGuillaumin** [comment]
- download keras from GitHub (with `docs/` folder)
- install MKdocs to generate documentation
- install mkdocs-pandoc (https://github.com/jgrassler/mkdocs-pandoc) to generate a PDF ! 

I can't test this solution right now ! 
I well try this evening.

**Comment by litingsjj** [comment]
it worked?

**Comment by litingsjj** [comment]
Can you send me a copy??  ting.li.0209@gmail.com  thank you!!!

**Comment by JGuillaumin** [comment]
It didn't work ... 
MKdocs and mkdocs-pandoc work well, but it failed during the generation of the PDF with pandoc.

**Comment by litingsjj** [comment]
Can I print it with MKdocs?

**Comment by Thatfreesky** [comment]
@litingsjj Dose you have a PDF now? If yes, can you send it to me? 18207481578@163.com

**Comment by AdityaSoni19031997** [comment]
A pdf will be really helpful for offline  access as well as reading the docs while traveling a lot(in my case)..

**Comment by AdityaSoni19031997** [comment]
Still we don't have any PDF?

**Comment by pcko1** [comment]
anyone has a complete pdf of the documentation found on the official website? if yes, can you send also to kotsias.pan@gmail.com :) ? tyvm!

**Comment by JGuillaumin** [comment]
Hi, you can find a PDF version of `keras==2.1.6`  in the releases section ! 
https://github.com/JGuillaumin/keras-doc-pdf/releases
(I'm still writing code to automatically generate a PDF for any version of Keras)

**Comment by AdityaSoni19031997** [comment]
Thanks

**Comment by pcko1** [comment]
Thanks a lot!

**Comment by slerman12** [comment]
Any chance one could be generated for the latest release?
