### ISSUE TITLE
Failing to Implement a Custom Objective Function

### ISSUE THREAD

**Issue by kumkee** [keras-team/keras#4920]
I am trying to implement a metric involving K.abs() function, and I encounter the following runtime error:

>  File "hosdays_mlp.py", line 54, in <module>
    verbose=1, validation_data=(X_test, Y_test))
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 664, in fit
    sample_weight=sample_weight)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1143, in fit
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 849, in _fit_loop
    callbacks.on_batch_end(batch_index, batch_logs)
  File "/usr/local/lib/python2.7/dist-packages/keras/callbacks.py", line 64, in on_batch_end
    callback.on_batch_end(batch, logs)
  File "/usr/local/lib/python2.7/dist-packages/keras/callbacks.py", line 192, in on_batch_end
    self.progbar.update(self.seen, self.log_values)
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/generic_utils.py", line 140, in update
    if abs(avg) > 1e-3:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

> 
It seems to be an internal error of keras.
I later found out that some keras-provided metrics also use abs(). An example is keras.objectives.mean_absolute_error. So I try using keras.objectives.mean_absolute_error as one of my metrics. The same error occurs. 
Please note that if I use string value "mean_absolute_error", everything runs smoothly.

**Comment by linxihui** [comment]
It is obvious from the last line of the error that `avg` is an array. Make sure that your metric return a scalar instead of an array.  Also, for people to know better the issue, please try providing your code.

**Comment by kumkee** [comment]
Thanks @linxihui here is my code:

` from __future__ import print_function
import numpy as np

import pandas as pd
import patientdata
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation
from keras.optimizers import SGD, Adam, RMSprop
from keras.utils import np_utils

import keras.backend as K

import tensorflow as T

n_H_units = 2**11
seed = 1337#1337
dropout = 0.2
np.random.seed(seed)  # for reproducibility

def accuracy_losse(y_true, y_pred):
    diff = K.abs(y_true - y_pred)
    return K.mean(diff, axis=-1)
    #return K.mean(K.less(K.abs(y_true - y_pred), 2), axis=-1)

csv_prediction = 'hospitaldays_prediction_mlp.csv'

batch_size = 128
nb_epoch = 80

pdata = patientdata.PatientData()
(X_train, Y_train), (X_test, Y_test) = pdata.load_data()

n = X_train.shape[1]

print(X_train.shape[0], 'train samples')
print(X_test.shape[0], 'test samples')

model = Sequential()
model.add(Dense(n_H_units, input_shape=(n,)))
model.add(Activation('relu'))
model.add(Dropout(dropout))
model.add(Dense(n_H_units))
model.add(Activation('relu'))
model.add(Dropout(dropout))
model.add(Dense(n_H_units))
model.add(Activation('relu'))
model.add(Dropout(dropout))
model.add(Dense(n_H_units))
model.add(Activation('relu'))
model.add(Dropout(dropout))
model.add(Dense(1))
model.add(Activation('linear'))

model.summary()

model.compile(loss='mean_squared_error',
              optimizer='adam',
              metrics=[accuracy_losse])
              #metrics=['mean_absolute_error'])

history = model.fit(X_train, Y_train,
                    batch_size=batch_size, nb_epoch=nb_epoch,
                    verbose=1, validation_data=(X_test, Y_test))
score = model.evaluate(X_test, Y_test, verbose=0)
print('Test score:', score[0])
print('Test accuracy:', score[1])

X = pdata.df.as_matrix()
Y = model.predict(X)
#Y_series = pd.Series(Y, index=pdata.df.index)
isTest = [1 if c in pdata.testIDs else 0 for c in pdata.df.index]

df_prediction = pd.DataFrame({'is_test': isTest, 'prediction': Y.transpose()[0]}, index=pdata.df.index)
df_prediction[pdata.target.name] = pdata.target

df_prediction.to_csv(csv_prediction)

y_test_predict = model.predict(X_test)
err = abs(y_test_predict.flatten() - Y_test)
m = float(Y_test.shape[0])
print('Test losse accuracy:', (err <= 2).sum()/ m )
print('Test strick accuracy:', (err <= 1).sum()/ m )`

**Comment by linxihui** [comment]
@kumkee the return value of a metric should be scalar not an array. In your code
```
def accuracy_losse(y_true, y_pred):
    diff = K.abs(y_true - y_pred)
    return K.mean(diff, axis=-1)
````
`y_pred` is Batch x 1, so `K.mean(axis=-1)` returns an tensor of shape B. Try `K.mean(diff)`.

**Comment by kumkee** [comment]
@linxihui It works without `axis=-1` ！！
Now why passing string value 'mean_absolute_error' works (but passing objectives.mean_absolute_error doesn't) becomes a new mystery, because there is `axis=-1` in the source code of mean_absolute_error' https://github.com/fchollet/keras/blob/master/keras/objectives.py

Nevertheless, at least my custom metric is now working. Thank you, and I am closing the issue.

**Comment by kumkee** [comment]
I have to reopen the issue, as I am not able to use my custom metric as the loss.
Here is my custom loss function, `error_strick`:
```
def custom_metric(y_true, y_pred, strick=1, err=1):
    diff = K.abs(y_true - y_pred)
    bound = 1. if strick else 2.
    comp_func = K.greater_equal if err else K.lesser
    return K.mean(comp_func(diff, bound))

def accuracy_loose(y_true, y_pred):
    return custom_metric(y_true, y_pred, strick=0, err=0)

def accuracy_strick(y_true, y_pred):
    return custom_metric(y_true, y_pred, strick=1, err=0)

def error_loose(y_true, y_pred):
    return custom_metric(y_true, y_pred, strick=0, err=1)

def error_strick(y_true, y_pred):
    return custom_metric(y_true, y_pred, strick=1, err=1)
```
The function `accuracy_loose` and `accuracy_strick` from the same group work as the metrics.
My new `model.compile` looks:
```
model.compile(loss=error_strick,#'mean_squared_error',
              optimizer='adam',
              metrics=[accuracy_loose, accuracy_strick])
              #metrics=['mean_absolute_error'])
```

**Comment by kumkee** [comment]
this seems to be a problem of tensorflow:
https://github.com/tensorflow/tensorflow/issues/3208

**Comment by sbaurdlp** [comment]
Same problem here with custom loss function

**Comment by souvick91** [comment]
Same here...literally struggling with this

**Comment by vthorey** [comment]
same here

**Comment by yushuinanrong** [comment]
same .....

**Comment by jntorres** [comment]
same ...

**Comment by jntorres** [comment]
same here!

**Comment by Lan1991Xu** [comment]
same

**Comment by souvick91** [comment]
The sizes have to be equal to batch sizes. It works if you use y_true and y_pred, i.e. if the sizes of features are equal to batch sizes.

**Comment by Lan1991Xu** [comment]
sorry, what means of the size should be equal to batch size?
