### ISSUE TITLE
ValueError: setting an array element with a sequence while using sparse matrix

### ISSUE THREAD

**Issue by eromoe** [keras-team/keras#4984]
Hello!

I found that using `sparse matrix` would cause `ValueError: setting an array element with a sequence`

## Version:
Keras (1.2.0)
tensorflow (0.12.1)

## Input data
```
X <9516x28934 sparse matrix of type '<type 'numpy.float64'>'
	with 946932 stored elements in Compressed Sparse Row format>

y numpy.ndarray  (9516,)
```

## Code

```
from keras.models import Sequential
model = Sequential()

from keras.layers import Dense, Activation

model.add(Dense(output_dim=64, input_dim=X.shape[1]))
model.add(Activation("relu"))
model.add(Dense(output_dim=2))
model.add(Activation("softmax"))

from keras.utils.np_utils import to_categorical
# would convert to one-hot
y_binary = to_categorical(y)

model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])
model.fit(X, y_binary, nb_epoch=20, batch_size=32)
```

## Log
```
Epoch 1/20


ValueErrorTraceback (most recent call last)
<ipython-input-37-894211790f97> in <module>()
     14 
     15 model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])
---> 16 model.fit(X, y_binary, nb_epoch=20, batch_size=32)
     17 
     18 # https://github.com/fchollet/keras/issues/4865

/usr/local/lib/python2.7/dist-packages/keras/models.pyc in fit(self, x, y, batch_size, nb_epoch, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, **kwargs)
    662                               shuffle=shuffle,
    663                               class_weight=class_weight,
--> 664                               sample_weight=sample_weight)
    665 
    666     def evaluate(self, x, y, batch_size=32, verbose=1,

/usr/local/lib/python2.7/dist-packages/keras/engine/training.pyc in fit(self, x, y, batch_size, nb_epoch, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch)
   1141                               val_f=val_f, val_ins=val_ins, shuffle=shuffle,
   1142                               callback_metrics=callback_metrics,
-> 1143                               initial_epoch=initial_epoch)
   1144 
   1145     def evaluate(self, x, y, batch_size=32, verbose=1, sample_weight=None):

/usr/local/lib/python2.7/dist-packages/keras/engine/training.pyc in _fit_loop(self, f, ins, out_labels, batch_size, nb_epoch, verbose, callbacks, val_f, val_ins, shuffle, callback_metrics, initial_epoch)
    841                 batch_logs['size'] = len(batch_ids)
    842                 callbacks.on_batch_begin(batch_index, batch_logs)
--> 843                 outs = f(ins_batch)
    844                 if not isinstance(outs, list):
    845                     outs = [outs]

/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.pyc in __call__(self, inputs)
   1601         session = get_session()
   1602         updated = session.run(self.outputs + [self.updates_op],
-> 1603                               feed_dict=feed_dict)
   1604         return updated[:len(self.outputs)]
   1605 

/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.pyc in run(self, fetches, feed_dict, options, run_metadata)
    764     try:
    765       result = self._run(None, fetches, feed_dict, options_ptr,
--> 766                          run_metadata_ptr)
    767       if run_metadata:
    768         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.pyc in _run(self, handle, fetches, feed_dict, options, run_metadata)
    935                 ' to a larger type (e.g. int64).')
    936 
--> 937           np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
    938 
    939           if not subfeed_t.get_shape().is_compatible_with(np_val.shape):

/usr/local/lib/python2.7/dist-packages/numpy/core/numeric.pyc in asarray(a, dtype, order)
    480 
    481     """
--> 482     return array(a, dtype, copy=False, order=order)
    483 
    484 def asanyarray(a, dtype=None, order=None):

ValueError: setting an array element with a sequence.
```

Though convert sparse matrix to np array can walk through, I think it would be better to support it.

**Comment by jakubLangr** [comment]
I have the same issue with `tf 1.0.0` and `keras 1.2.2` and following the (I presume otherwise working) example from:
http://machinelearningmastery.com/tutorial-first-neural-network-python-keras/

**Comment by hitchhiker744** [comment]
Try doing the one-hot encoding of y with scikit learn OneHotEncoder:

`
from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder(sparse=False) # Key here is sparse=False!
y_categorical = enc.fit_transform(y.reshape((y.shape[0]),1))

model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])
model.fit(X, y_categorical, nb_epoch=20, batch_size=32)
`

**Comment by eromoe** [comment]
@hitchhiker744 `X` is sparse, not `y`. Convert `X` to normal matrix would take much larger memory, so I am suggesting add `sparse`

**Comment by leriomaggio** [comment]
I got exactly the same error with `Keras 2` and `tensorflow 1.0.1`. 

IMHO this is one important feature to add: with my data, `todense()` is definitely not the case as it won't fit in memory.

**Comment by dbetteridge** [comment]
does anyone have a few steps one can take to actually fix this? I receive the below

ValueError                                Traceback (most recent call last)
<ipython-input-1-a7b20b4a10bd> in <module>()
     16 cartest = cartest.reshape(cartest.shape[0], 224, 224, 3).astype('float32')
     17 
---> 18 model = load_model('model.h5')
     19 
     20 model.fit(cartrain, classtrain, validation_data=(cartest, classtest), epochs=10, batch_size=70, verbose=1)

C:\...\Continuum\Anaconda3\lib\site-packages\keras\models.py in load_model(filepath, custom_objects)
    241 
    242     # set weights
--> 243     topology.load_weights_from_hdf5_group(f['model_weights'], model.layers)
    244 
    245     # instantiate optimizer

C:\...\Continuum\Anaconda3\lib\site-packages\keras\engine\topology.py in load_weights_from_hdf5_group(f, layers)
   2912                              ' elements.')
   2913         weight_value_tuples += zip(symbolic_weights, weight_values)
-> 2914     K.batch_set_value(weight_value_tuples)
   2915 
   2916 

C:\...\Continuum\Anaconda3\lib\site-packages\keras\backend\theano_backend.py in batch_set_value(tuples)
   1088 def batch_set_value(tuples):
   1089     for x, value in tuples:
-> 1090         x.set_value(np.asarray(value, dtype=x.dtype))
   1091 
   1092 

C:\...\Continuum\Anaconda3\lib\site-packages\numpy\core\numeric.py in asarray(a, dtype, order)
    529 
    530     """
--> 531     return array(a, dtype, copy=False, order=order)
    532 
    533 

ValueError: setting an array element with a sequence.

and im build a small model on top of resnet50

x = base_model(keras_input)
x = Flatten()(x)
x = Dense(2048, activation='relu')(x)
x = Dropout(0.5)(x)
x = Dense(1024, activation='relu')(x)
x = Dropout(0.5)(x)
predictions = Dense(197, activation='softmax')(x)

**Comment by lanking520** [comment]
Try With batches, it works fine:

def samples(x_source, y_source, size):
    while True:
        for i in range(0, x_source.shape[0], size):
            j = i + size
            
            if j > x_source.shape[0]:
                j = x_source.shape[0]
                
            yield x_source[i:j].toarray(), y_source[i:j].toarray()
model.fit_generator(samples(x_train, x_train, nb_batch),x_train.shape[0], nb_epoch, verbose=1)
Saves a great a lot on memory
nb_batch is the number of batches.

**Comment by maximsch2** [comment]
You should try using the functional API and creating an input layer with `sparse=True`. That solved an issue for me

**Comment by cod3licious** [comment]
I'm having the same problem. With theano you can easily define your input matrix as a sparse matrix by using `x = theano.sparse.csr_matrix('x')` instead of `x = theano.tensor.matrix('x')` and tensorflow seems to have a solution for sparse tensors as well so it would be really great if the input layer could be passed the additional argument specifying that the input will be sparse. 
At the very least, until support for sparse matrices is implemented, this error message should be more explicit by implementing an additional check whether the input matrix is sparse and warning the user accordingly that sparse matrices are not (yet) supported.

**Comment by Raj-JainHC** [comment]
@maximsch2 Can you please show how you were able to do it? I tried doing that but failing terribly. Full details here: https://stackoverflow.com/questions/46579164/use-sparse-input-in-keras-with-tensorflow

**Comment by Raj-JainHC** [comment]
@cod3licious Can you please comment too? You seem to have solved it in the same way! Full details here: https://stackoverflow.com/questions/46579164/use-sparse-input-in-keras-with-tensorflow

**Comment by cod3licious** [comment]
@Raj-JainHC I've only used sparse input matrices and not spare targets, I'm guessing your error message relates to that? I haven't checked yet whether you can specify sparse outputs as well and use them in the cost function, I'm guessing that's a lot more complicated than allowing sparse inputs, since it changes the way the error function is computed everywhere, etc...

**Comment by karl-schelhammer-td** [comment]
I'm running into the same issue.

**Comment by ebuildy** [comment]
Is there a tutorial about Keras that ... just works?

**Comment by roywei** [comment]
Try using `InputLayer(sparse=True)`  in Sequential model instead of Input() in Functional models.

**Comment by wt-huang** [comment]
@roywei is correct, InputLayer(sparse=True) would solve this.

**Comment by abracadabrac** [comment]
> @hitchhiker744 `X` is sparse, not `y`. Convert `X` to normal matrix would take much larger memory, so I am suggesting add `sparse` support.

What do you mean ?

**Comment by abracadabrac** [comment]
> @hitchhiker744 `X` is sparse, not `y`. Convert `X` to normal matrix would take much larger memory, so I am suggesting add `sparse` support.

I am sorry I don't understand.

**Comment by diego898** [comment]
@wt-huang @roywei Why would we expect this to work in the Sequential model, but not the Functional model?
