### ISSUE TITLE
Request for contributions: docstring improvements

### ISSUE THREAD

**Issue by fchollet** [keras-team/keras#4992]
We need docstrings for every single function, class or method that is longer than 5 lines.

Every docstring should include an `# Arguments` section (if applicable), a `# Returns` section (if applicable), and a `# Raises` section describing every exception raised by the function (if any). Classes should also include a `# Properties` section for their public properties.

I've started working on this yesterday. Would anybody like to help? It's going to be a lot of work.

Thanks!

**Comment by keunwoochoi** [comment]
You know I'm up for it ;) what would be the best docstrings for an example?

**Comment by fchollet** [comment]
Most Keras docstrings already follow these conventions (except for `# Raises`), so any docstring with the sections mentioned can serve as an example. Mostly this is about adding docstrings where they are still missing, or filling in the sections mentioned where they are missing or incomplete.

Thanks!

**Comment by nzw0301** [comment]
I tried to write a docstring example for `Raises` of [Xception](https://keras.io/applications/#xception) based on TensorFlow API page.


```markdown
# Reruns
    A Keras model instance.

# Raises
  - `ValueError`: `weights` argument is neither `imagenet` nor `None`.
  - `RuntimeError`: If backend is not TensorFlow.
```

May it be a reference this example?

**Comment by fchollet** [comment]
@keunwoochoi please focus on tensorflow_backend.py, that would be super hepful.

As a reference:

```
# Raises
    ValueError: if `weights` argument is neither `imagenet` nor `None`.
    RuntimeError: if backend is not TensorFlow.
```

**Comment by keunwoochoi** [comment]
@fchollet Okay, I'll work on adding `Raises`. 

A bit off-topic: `tensorflow_backend.py` has 3000+ lines with 149 functions, seems like quite a lot. I'd expect it will split in version 2?

**Comment by meharig** [comment]
Disclosure I am `the beginner` on contributing. I would love to give back to keras very much. Point me your priority/choice.

**Comment by meharig** [comment]
@fchollet is this issue closed :)

**Comment by gabrieldemarmiesse** [comment]
This issue seems to be resolved. Especially `tensorflow_backend.py`. We'll reopen another one if necessary.
