### ISSUE TITLE
Masking doesn't work with TimeDistributed

### ISSUE THREAD

**Issue by cbaziotis** [keras-team/keras#5212]
I have an NLP problem in which i want to classify sentences in a document. So for each document i embed each sentence using an Embedding Layer then i feed each sentence to an RNN and then i feed the representations of each sentence in another RNN and finally i do the classification. This is my code (it runs!):

```python
 x = Input(shape=(MAX_SENTS, MAX_SENT_LENGTH,))

emb_words = TimeDistributed(embeddings_layer(max_length=MAX_SENT_LENGTH, embeddings=embeddings, masking=True))(x)

emb_sents = TimeDistributed(GRU(100, return_sequences=False))(emb_words)

emb_docs = GRU(100, return_sequences=True)(emb_sents)

scores = Scoring()(emb_docs)

model = Model(input=x, output=scores)
```
The problem is that the mask is not passed trhough. For example if a document has 8 sentences and the `MAX_SENTS=10` the last 2 rows will be zero padded. But the mask is empty. And i noticed that is empty in every layer not only the last. Here is the code i used to check the mask:

```python
    def get_input_mask(model, layer, X_batch):
        get_input_mask = K.function([model.layers[0].input, K.learning_phase()], model.layers[layer].input_mask)
        input_mask = get_input_mask([X_batch, 0])
        return input_mask
```

Then i check for the mask in a Callback on `on_batch_end`. How can i fix this? Is it a bug or am i doing something wrong?

To be clear i care for the mask for the sentences.

**Comment by nigeljyng** [comment]
@cbaziotis I'm having the exact same problem. It seems like `TimeDistributed` not supporting masking is a known issue #4786. I implemented a hierarchical attentional RNN model, and a consolation is that even though every document will have `MAX_SENTS` sentences (regardless of how many sentences it actually has), the model learns to assign a small (but non-zero) attention weight to the padding sentences. So perhaps it won't adversely impact model performance apart from training time?

**Comment by cbaziotis** [comment]
@nigeljyng The training time is not going to be reduced, even if the `TimeDistributed` worked.
The problem is the non-zero weights for the padded sentences.
