### ISSUE TITLE
Request for contributions: writing and testing API conversion decorators.

### ISSUE THREAD

**Issue by fchollet** [keras-team/keras#5623]
In Keras 2 (branch `keras-2`), the API for pretty much every layer has changed. We will keep supporting the Keras 1 API, and we will do so via **API conversion decorators**.

As an example, I have written the conversion decorator for the `Dense` layer. It was done in this commit: https://github.com/fchollet/keras/commit/5516c8fb42f01622c9a4a31c19cb46ae68cfa0f6
The decorator code is here: https://github.com/fchollet/keras/blob/keras-2/keras/legacy/interfaces.py#L15
The test for it is here: https://github.com/fchollet/keras/blob/keras-2/tests/keras/legacy/interface_test.py#L8

In order to launch Keras 2, we will need such decorators for every layer (and also for training routines and model constructors). If you want to contribute, please add these decorators (in `keras/legacy/interfaces.py`, with tests in `tests/keras/legacy/interface_test.py`). You just need to follow the template laid out with the `Dense` layer decorator.

You can leave out the `Conv*D` layers for now, since they will require special handling due to a positional/keyword argument conflict.

Thanks a lot!

**Comment by Sentient07** [comment]
Hi, I had previously seen on twitter that you were looking for developers to fix failing theano tests. Are they fixed? Else, can I start working on them?

**Comment by fchollet** [comment]
The Theano tests are fixed. Please focus on porting the examples (some still need porting) and writing the conversion interfaces.

**Comment by jihobak** [comment]
@fchollet 
I would like to check UserWarning message.

`old_layer = keras.layers.Dense(2, bias=False, init='normal',
                                   W_regularizer='l1',
                                   W_constraint='max_norm', name='d')`

makes warning below

`UserWarning: Update your `Dense` layer call to the Keras 2 API: `Dense(2, kernel_initializer="normal", kernel_regularizer="l1", kernel_constraint="max_norm", use_bias=False)`
  'to the Keras 2 API: ' + signature)
`

There is '+ signature' in bottom of warning message, which we don't expect.
isn't it?

**Comment by jihobak** [comment]
@fchollet 

Also, I have a question.
In test, 
`old_layer = keras.layers.Dense(input_dim=3, output_dim=2, name='d')` dose not make any warning message.

Shouldn't we show warning message about using output_dim(even, this is not keyword argument)?

**Comment by dupsys** [comment]
Hi @fchollet,

I am trying to implement this paper https://arxiv.org/pdf/1605.03481.pdf with the following code.

`# define the symbol alphabet, including the padding symbol '#' and create mapping of unique chars to integers
chars = 'X'+ ''.join(sorted({c for s in raw_text for c in s}))
char_to_int = {c:i for i,c in enumerate(chars)}
# compute the size of our alphabet e.g.,length of vocabulary (letters) size in the training dataset
n_chars = len(raw_text)
# maximum length of distinct characters in the vocabulary much more than 26 in the alphabet.
max_length = max(map(len, raw_text.split()))
  
#decoding and encoding
def encode_string(s): 
    return [char_to_int[c] for c in s]
def decode_string(a): 
    return ''.join(chars[i] for i in a)
def encode_and_pad(words):
    return pad_sequences(list(map(encode_string, words)), padding='post', maxlen=max_length)
# Our inputs (x) will be the participles
padded_input = encode_and_pad(chars)

# load the dataset but only keep the top n words, zero the rest
X_train, X_test = train_test_split(padded_input, test_size=0.20, random_state=seed)
X_train = sequence.pad_sequences(X_train, maxlen=max_length)
X_test = sequence.pad_sequences(X_test, maxlen=max_length)

#model construction
sequence_length = X_train.shape[1]
vocabulary_size = len(chars)
embedding_dim = 256
decoder_size = 128
# filter_sizes = [7,3]
num_filters = 256
drop = 0.5

nb_epoch = 10
batch_size = 5

# we define what the input shape looks like:
inputs = Input(shape=(sequence_length, vocabulary_size), name='input', dtype='float32')

# all the convolutional layers...
conv = Convolution1D(num_filters, filter_length=filter_sizes[0],
                         border_mode='valid', activation='relu',input_shape=(sequence_length, vocabulary_size))(inputs)
pool = MaxPooling1D(pool_length= filter_sizes[1])(conv)
conv1 = Convolution1D(num_filters, filter_length=filter_sizes[0],
                         border_mode='valid', activation='relu')(pool)
pool2 = MaxPooling1D(pool_length= filter_sizes[1])(conv1)
conv3 = Convolution1D(num_filters, filter_length=filter_sizes[0],
                         border_mode='valid', activation='relu')(pool2)
conv4 = Convolution1D(num_filters, filter_length=filter_sizes[0],
                         border_mode='valid', activation='relu')(conv3)
# encode with LSTM
encoding_layer = LSTM(conv4, embedding_dim, return_sequences=True)
rep_in = RepeatVector(encoding_layer)
l_decoder_1 = LSTM(rep_in, decoder_size, name='decoder1')
l_decoder_2 = LSTM(l_decoder_1, decoder_size, name='decoder2')
l_reshape = Reshape(l_decoder_2, (-1,[2]), name='l_reshape')`

The objective is to reshape decoders LSTM to define the actual input text or synonym replacement of the early text. Running this code, i got the following:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-393-456c7e8a7fd4> in <module>()
     55 l_decoder_1 = LSTM(rep_in, decoder_size, name='decoder1')
     56 l_decoder_2 = LSTM(l_decoder_1, decoder_size, name='decoder2')
---> 57 l_reshape = Reshape(l_decoder_2, (-1,[2]), name='l_reshape')

TypeError: __init__() takes exactly 2 arguments (4 given)

**Comment by fredtony** [comment]
@fchollet I'll knock some out. Is there any specific naming convention? I'm assuming, for example, that  a legacy BatchNormalization layer wrapper might be named legacy_batchnormalization_support . Is that correct?

**Comment by fchollet** [comment]
@fredtony sure, that's fine.

**Comment by abhaikollara** [comment]
It'd be great if people could mention what they're working on, to avoid duplicate efforts.

**Comment by abhaikollara** [comment]
@fchollet I'm trying to convert the `BatchNormalization` legacy interface, but I can't figure out what happened to the `weights` and `mode` arguments

**Comment by fredtony** [comment]
@abhaikollara I was working on BatchNormalization a few days ago and the `mode` argument complicated the conversion interface, so fchollet advised not to worry about this API conversion interface for now. The `weights` argument actually goes to the parent class Layer which will take that argument for any layer, so you don't need to worry about it if you see it in any layer conversions. I'm working on layers in local.py currently.

**Comment by abhaikollara** [comment]
@fredtony Thanks for the info !

**Comment by fredtony** [comment]
@fchollet Did this get fully completed? I know all the layers were completed, but did all of the training routines and model constructors that you mentioned get converted? Gonna help proofreading docs if so.

**Comment by fchollet** [comment]
Yes, this work is complete. Proofreading docs is helpful, and so is testing Keras 1 code with Keras 2 in order to make sure we are still mostly compatible.

**Comment by gabrieldemarmiesse** [comment]
It seems that this issue is resolved.
