### ISSUE TITLE
get warnings for tensorboard : summary name is illegal

### ISSUE THREAD

**Issue by hanzlfs** [keras-team/keras#5746]
After I add tensorboard into callbacks, it shows warning of summary name format is illegal. I suspect it could be caused by the keras model summary format. 

#### warnings
```
INFO:tensorflow:Summary name convolution2d_1_W:0 is illegal; using convolution2d_1_W_0 instead.
```

#### code
```
tensorboard = keras.callbacks.TensorBoard(
    log_dir='tensorboard/esc_example/' + name + '/', 
    write_graph=True,
    histogram_freq=1
)
```

**Comment by GeeshangXu** [comment]
Got same problems, when add TensorBoard callback to the example https://github.com/fchollet/keras/blob/master/examples/cifar10_cnn.py  

tensorflow (1.0.1)
Keras (2.0.0)

INFO:tensorflow:Summary name conv2d_1/kernel:0 is illegal; using conv2d_1/kernel_0 instead.
INFO:tensorflow:Summary name conv2d_1/kernel:0 is illegal; using conv2d_1/kernel_0 instead.
INFO:tensorflow:Summary name conv2d_1/bias:0 is illegal; using conv2d_1/bias_0 instead.
INFO:tensorflow:Summary name conv2d_1/bias:0 is illegal; using conv2d_1/bias_0 instead.
INFO:tensorflow:Summary name conv2d_2/kernel:0 is illegal; using conv2d_2/kernel_0 instead.
INFO:tensorflow:Summary name conv2d_2/kernel:0 is illegal; using conv2d_2/kernel_0 instead.
INFO:tensorflow:Summary name conv2d_2/bias:0 is illegal; using conv2d_2/bias_0 instead.
INFO:tensorflow:Summary name conv2d_2/bias:0 is illegal; using conv2d_2/bias_0 instead.
INFO:tensorflow:Summary name conv2d_3/kernel:0 is illegal; using conv2d_3/kernel_0 instead.
INFO:tensorflow:Summary name conv2d_3/kernel:0 is illegal; using conv2d_3/kernel_0 instead.
INFO:tensorflow:Summary name conv2d_3/bias:0 is illegal; using conv2d_3/bias_0 instead.
INFO:tensorflow:Summary name conv2d_3/bias:0 is illegal; using conv2d_3/bias_0 instead.
INFO:tensorflow:Summary name conv2d_4/kernel:0 is illegal; using conv2d_4/kernel_0 instead.
INFO:tensorflow:Summary name conv2d_4/kernel:0 is illegal; using conv2d_4/kernel_0 instead.
INFO:tensorflow:Summary name conv2d_4/bias:0 is illegal; using conv2d_4/bias_0 instead.
INFO:tensorflow:Summary name conv2d_4/bias:0 is illegal; using conv2d_4/bias_0 instead.
INFO:tensorflow:Summary name dense_1/kernel:0 is illegal; using dense_1/kernel_0 instead.
INFO:tensorflow:Summary name dense_1/kernel:0 is illegal; using dense_1/kernel_0 instead.
INFO:tensorflow:Summary name dense_1/bias:0 is illegal; using dense_1/bias_0 instead.
INFO:tensorflow:Summary name dense_1/bias:0 is illegal; using dense_1/bias_0 instead.
INFO:tensorflow:Summary name dense_2/kernel:0 is illegal; using dense_2/kernel_0 instead.
INFO:tensorflow:Summary name dense_2/kernel:0 is illegal; using dense_2/kernel_0 instead.
INFO:tensorflow:Summary name dense_2/bias:0 is illegal; using dense_2/bias_0 instead.
INFO:tensorflow:Summary name dense_2/bias:0 is illegal; using dense_2/bias_0 instead.

**Comment by catta202000** [comment]
I have the same issue.

**Comment by liyi193328** [comment]
same issue, this error results to the variable's summary can't display.

**Comment by lk1983823** [comment]
I have the same issue

**Comment by codeisnotcode** [comment]
Same issue when doing this to track shifts in trainable parameters during training by monitoring their mean value:
for v in tf.trainable_variables():
     vrm = tf.reduce_mean(v)
     tf.summary.scalar(v.name, vrm)

**Comment by HappyStorm** [comment]
Same issue here

**Comment by hipoglucido** [comment]
I am having also this issue. But I only get that when I am running on Jupyter notebook. I don't see any of that while running from a .py script

**Comment by sivagnanamn** [comment]
Same issue here

**Comment by studynon** [comment]
same issues in tensorflow, not only in keras.

**Comment by SeaFX** [comment]
The same issue, sorted out by replacing variable.name with variable.name.replace(':','_')

The summary names do not like :

**Comment by post2web** [comment]
Don't add spaces or other special chars in the summary name. For example instead of:
```
tf.summary.scalar('classify loss', classify_loss)
```
do:
```
tf.summary.scalar('classify_loss', classify_loss)
```

**Comment by wt-huang** [comment]
Closing as this is resolved
