### ISSUE TITLE
SpatialDropout is missing from the documentation

### ISSUE THREAD

**Issue by Dapid** [keras-team/keras#5907]
It should be a core layer but it doesn't show up on the website, nor the search function picks it up:

https://keras.io/layers/core/

I can use it without warnings, so I wouldn't expect it to be deprecated.

**Comment by Dapid** [comment]
SpatialDropout is still not showing up.

**Comment by Dapid** [comment]
Still missing.

**Comment by RaananHadar** [comment]
Missing still.
