### ISSUE TITLE
Cannot merge with a sequential model

### ISSUE THREAD

**Issue by stschubert** [keras-team/keras#6357]
Hi,
when I try to run something like
```
model1 = keras.models.Sequential()
model1.add(keras.layers.Dense(100, input_shape=(100,)))

model2 = keras.models.Sequential()
model2.add(keras.layers.Dense(100, input_shape=(100,)))

model3 = keras.models.Sequential()
model3.add(keras.layers.Multiply([model1, model2]))
```
the program simply throws an error. Apparently, it's currently not possible to merge the outputs of two models in a sequential model, is it? How can I implement it correctly?

Btw.: a solution like 
`Merge([model1, model2], mode='mul')`
is deprecated.

Thanks.

**Comment by karimpedia** [comment]
How about using the Functional API:

```
model1 = keras.models.Sequential()
model1.add(keras.layers.Dense(100, input_shape=(100,)))

model2 = keras.models.Sequential()
model2.add(keras.layers.Dense(100, input_shape=(100,)))


iL = [keras.layers.Input(shape=(100,)), keras.layers.Input(shape=(100,))]
hL = [model1(iL[0]), model2(iL[1])]
oL = keras.layers.Multiply()(hL)

model3 = keras.models.Model(inputs=iL, outputs=oL)
```

**Comment by stschubert** [comment]
Basically you are right, and I use the Functional API. However, one of my students is using the Sequential Model; and as the sequential model exist, there has to be a working solution for a merge/multiplication in this type of API.

**Comment by zted** [comment]
I have the same question as @stschubert. With Functional API it works of course, but why does it take 3 lines of code to do something that the Merge took care of with 1 line? If Add/Multiply/Concat is like this, why not just keep Merge instead of deprecating it?

**Comment by hugohrosa** [comment]
Any ideas on this topic? I too am having the same problem. Specially since Functional model can't be used with the KerasClassifier wrapper to perform GridSearchCV on it... 
Thanks!

**Comment by Apple3142** [comment]
depreciating Merge seems to be a backwards step

**Comment by JerryKurata** [comment]
Any update on how to use the merge layers methods with the Sequential Model?

**Comment by lzfelix** [comment]
According to the tests on [keras/tests/keras/layers/merge_test.py](https://github.com/keras-team/keras/blob/master/tests/keras/layers/merge_test.py) it seems that merge can only be done via the functional API now 😞.
