### ISSUE TITLE
Issue with passing a callback to keras classifier wrapper

### ISSUE THREAD

**Issue by ghost** [keras-team/keras#6368]
I'm trying to adopt a drop based learning rate decay strategy to my categorical data classification task.
Everything goes fine until I pass the callback to the KerasClassifier wrapper. 

# Drop-Based Learning Rate Decay
import numpy
from pandas import read_csv
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from keras.utils import np_utils
from pandas import read_csv
import numpy
import math
from sklearn.preprocessing import LabelEncoder
from keras.callbacks import LearningRateScheduler

# learning rate schedule
def step_decay(epoch):
    initial_lrate = 0.2
    drop = 0.5
    epochs_drop = 10.0
    lrate = initial_lrate * math.pow(drop, math.floor((1+epoch)/epochs_drop))
    return lrate

# fix random seed for reproducibility
seed = 7
numpy.random.seed(seed)

dataframe = read_csv("Book1.csv", header=None)
dataset = dataframe.values
X = dataset[:,0:15].astype(float)
Y = dataset[:,15]
#One hot encoding or creating dummy variables from a categorical variable (class)
# encode class values as integers
encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)
# convert integers to dummy variables (i.e. one hot encoded)
dummy_y = np_utils.to_categorical(encoded_Y)

# create model
def baseline_model():
    # create model
    model = Sequential()
    model.add(Dense(50, input_dim=15, kernel_initializer='normal', activation='relu'))
    model.add(Dense(3, kernel_initializer='normal', activation='sigmoid'))
    sgd = SGD(lr=0.0, momentum=0.9, decay=0, nesterov=False)
    model.compile(loss='categorical_crossentropy', optimizer=sgd, metrics=['accuracy'])
    return model
    
#learning schedule callback
lrate = LearningRateScheduler(step_decay)
callbacks_list = [lrate]
estimators = []
estimators.append(('MinMaxScale', MinMaxScaler()))
estimators.append(('standardize', StandardScaler()))
estimators.append(('mlp', KerasClassifier(build_fn=baseline_model, epochs=100,
batch_size=5, callbacks=[lrate], verbose=1)))
pipeline = Pipeline(estimators)
kfold = StratifiedKFold(n_splits=2, shuffle=True, random_state=seed)
results = cross_val_score(pipeline, X, encoded_Y, cv=kfold)
print("Standardized: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))
When I run the code, exactly after passing the callback to the kerasclassifier wrapper (at estimators.append(('mlp', KerasClassifier(build_fn=baseline_model, epochs=100,
batch_size=5, callbacks=[lrate], verbose=1))), I get the error:
"Cannot clone object <keras.wrappers.scikit_learn.KerasClassifier object at 0x0000000042582AC8>, as the constructor does not seem to set parameter callbacks"
I would like to get this code corrected with the right way of passing callbacks to the wrapper. thanks in advance.

**Comment by FelipeMarcelino** [comment]
I have the same problem, someone can help us??

**Comment by bgokden** [comment]
I also have the same problem, I think this happens since fit accepts callbacks but predict does not accept this parameter, we can add a check in predict parameter in KerasClassifier that can fix it.

**Comment by tachyon663** [comment]
I'm facing a similar issue with getting callbacks to work inside a Pipeline. I suspect it has something to do with the fact that somehow the code calls the set_model() method of the Callback class to associate it with the Sequential model. When the model is embedded in a pipeline, it doesn't associate the model correctly. I tried digging through the code for the Callback class and the various other callback classes, but couldn't figure it out.

If you press tab after "your_callback_instance". it should show you what attributes have been set for the callback instance.

**Comment by KPLauritzen** [comment]
I had a related problem with getting `callbacks` to work with `GridSearchCV`. I ended up modifying `BaseWrapper` as explained here https://github.com/keras-team/keras/issues/4278#issuecomment-258922449

**Comment by kishoreiitd** [comment]
@KPLauritzen I also tried to modify BaseWrapper class as mentioned in #4278. However I am getting an error which is as follows:-
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
Did you also encountered this error as well? Let me know.

Thanks!

**Comment by KPLauritzen** [comment]
@kishoreiitd No.

I had to stop using this approach for unrelated reasons, but when I used it I didn't see that error.

**Comment by kishoreiitd** [comment]
@KPLauritzen Thanks a lot for your quick reply, I encountered this error when I inserted EarlyStopping to GridSearchCV using this fit_params={'callbacks': [EarlyStopping]}). However when I inserted using fit_params={'callbacks': [EarlyStopping()]}), it gives me an error which is:-
'EarlyStopping' object is not callable

Any help in this case would be highly appreciated.
Thanks again!

**Comment by KPLauritzen** [comment]
@kishoreiitd I don't think I can help you with this. Sorry
