### ISSUE TITLE
Why is there a default target_size in flow_from_directory ?

### ISSUE THREAD

**Issue by rdelassus** [keras-team/keras#6416]
target_size=(256, 256) seems arbitrary. When I don't want my images to be resized, I pass nothing and I expect that nothing will happen. I was very surprised to see that they were resized !

- [X] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [X] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [X] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by rdelassus** [comment]
This default parameter is still there. There is still no reason for it to be there.

**Comment by adrianodennanni** [comment]
@rdelassus did you find any workaround so `flow_from_directory` won't resize my pictures?

**Comment by rdelassus** [comment]
@adrianodennanni I've stopped using it. I've regrouped all my images in one hd5 file.
