### ISSUE TITLE
Incompatibility between Tensorflow and Theano models using Conv1D layers

### ISSUE THREAD

**Issue by fferroni** [keras-team/keras#6427]
Hello, I am trying to save a portable definition of a network using Conv1D layers. By portable I mean being able to save an .h5 file that I can load on different Keras instances using different backends.

However, despite the documentation on Conv1D not giving any indication that it is dependent on particular backends, I run into issues.

To replicate the issue:
keras.__version__ : '2.0.3'
tensorflow.__version__ : '1.1.0'
theano.__version__ : '0.9.0'

```
"""
{
    "image_dim_ordering": "tf",
    "epsilon": 1e-07,
    "floatx": "float32",
    "backend": "tensorflow"
}
"""

from keras.models import Sequential
from keras.layers import Conv1D, Flatten, Dense

model = Sequential()
model.add(Conv1D(filters=6, kernel_size=3, input_shape=(15,1), padding="same"))
model.add(Flatten())
model.add(Dense(3))
model.compile("adam","categorical_crossentropy")

model.save("test.h5")
```

I then restart, using theano backend...

```
"""
{
    "image_dim_ordering": "th",
    "epsilon": 1e-07,
    "floatx": "float32",
    "backend": "theano"
}
"""

from keras.models import load_model

model = load_model("test.h5")
```

However, I get the following error:

ValueErrorTraceback (most recent call last)
<ipython-input-1-85df9e4ef9a1> in <module>()
     10 from keras.models import load_model
     11 
---> 12 model = load_model("test.h5")

/usr/local/lib/python2.7/dist-packages/keras/models.pyc in load_model(filepath, custom_objects)
    241 
    242     # set weights
--> 243     topology.load_weights_from_hdf5_group(f['model_weights'], model.layers)
    244 
    245     # instantiate optimizer

```
/usr/local/lib/python2.7/dist-packages/keras/engine/topology.pyc in load_weights_from_hdf5_group(f, layers)
   2898                                                        weight_values,
   2899                                                        original_keras_version,
-> 2900                                                        original_backend)
   2901         if len(weight_values) != len(symbolic_weights):
   2902             raise ValueError('Layer #' + str(k) +

/usr/local/lib/python2.7/dist-packages/keras/engine/topology.pyc in preprocess_weights_for_loading(layer, weights, original_keras_version, original_backend)
   2839                        'Conv2DTranspose']
   2840         if layer.__class__.__name__ in conv_layers:
-> 2841             weights[0] = conv_utils.convert_kernel(weights[0])
   2842         if layer.__class__.__name__ == 'ConvLSTM2D':
   2843             weights[0] = conv_utils.convert_kernel(weights[0])

/usr/local/lib/python2.7/dist-packages/keras/utils/conv_utils.pyc in convert_kernel(kernel)
     80     """
     81     if not 4 <= kernel.ndim <= 5:
---> 82         raise ValueError('Invalid kernel shape:', kernel.shape)
     83     slices = [slice(None, None, -1) for _ in range(kernel.ndim)]
     84     no_flip = (slice(None, None), slice(None, None))

ValueError: ('Invalid kernel shape:', (3, 1, 6))
```

In the documentation, it says:

```
Input shape

3D tensor with shape: (batch_size, steps, input_dim)

Output shape

3D tensor with shape: (batch_size, new_steps, filters) steps value might have changed due to padding or strides.
```
So the way that the input shape is defined is fixed. I don't understand why it fails then.

Is this a bug?

**Comment by fabianmurariu** [comment]
Did you manage to figure this one out?

```
...
    raise ValueError('Invalid kernel shape:', kernel.shape)
ValueError: ('Invalid kernel shape:', (5, 50, 128))
```

**Comment by sandeepsingh** [comment]
Same error please help how to resolve this:

Error log:  
  model = load_model('/data/sandeep/TLDClassification/tld_classification_model.h5')
  File "/data/tensorflow/local/lib/python2.7/site-packages/keras/models.py", line 243, in load_model
    topology.load_weights_from_hdf5_group(f['model_weights'], model.layers)
  File "/data/tensorflow/local/lib/python2.7/site-packages/keras/engine/topology.py", line 2957, in load_weights_from_hdf5_group
    original_backend)
  File "/data/tensorflow/local/lib/python2.7/site-packages/keras/engine/topology.py", line 2898, in preprocess_weights_for_loading
    weights[0] = conv_utils.convert_kernel(weights[0])
  File "/data/tensorflow/local/lib/python2.7/site-packages/keras/utils/conv_utils.py", line 83, in convert_kernel
    raise ValueError('Invalid kernel shape:', kernel.shape)
ValueError: ('Invalid kernel shape:', (5, 300, 128))

**Comment by raviranjan-innoplexus** [comment]
Upgrading to keras 2.0.5 solves the issue

**Comment by ahmedshah202** [comment]
I am still facing the same even though I have keras 2.1.6 version
