### ISSUE TITLE
The "using-pre-trained-word-embeddings-in-a-keras-model" achieve an acc just 0.75??

### ISSUE THREAD

**Issue by zhhengcs** [keras-team/keras#6458]
I download the code and dataset described on  the section "using-pre-trained-word-embeddings-in-a-keras-model" ,trained it with keras2.0 backend tensorflow1.1 。The author says in his blog that he got an acc 95%[(https://blog.keras.io/using-pre-trained-word-embeddings-in-a-keras-model.html)](https://blog.keras.io/using-pre-trained-word-embeddings-in-a-keras-model.html) But,the acc i got  is just 0.75。 I want to know whether it is my mistake or author's careless?

**Comment by DL-Chang** [comment]
Hi, I met the same problem as you, Do you know how to solve this problem now? thx.
