### ISSUE TITLE
Keras not exporting tensor names when freezing TensorFlow graph/model

### ISSUE THREAD

**Issue by curiousily** [keras-team/keras#6552]
Hi,

I am trying to export Keras model (with TensorFlow backend) for an Android app. Here are the steps to reproduce it: 

First, obtaining the TensorFlow session:

```python
sess = K.get_session()
```

The model itself:

```python
X = tf.placeholder(tf.float32, shape=(None, N_TIME_STEPS, N_FEATURES),  name="input")

model = Sequential()
model.add(InputLayer(input_tensor=X))
model.add(LSTM(32))
model.add(Dense(N_CLASSES, activation='softmax', name='y_'))
```

Training & exporting the graph:

```python
optimizer = RMSprop(lr=0.01)
model.compile(loss='categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])

class TFCheckpointCallback(keras.callbacks.Callback):
    def __init__(self, saver, sess):
        self.saver = saver
        self.sess = sess

    def on_epoch_end(self, epoch, logs=None):
        self.saver.save(self.sess, 'freeze/checkpoint.ckpt', global_step=epoch)

tf_graph = sess.graph
tf_saver = tf.train.Saver()
tfckptcb = TFCheckpointCallback(tf_saver, sess)

model.fit(sequences, labels, validation_split=0.05, batch_size=1024, 
                    epochs=2, shuffle=True, callbacks=[tfckptcb])

tf.train.write_graph(tf_graph.as_graph_def(),
                     'freeze', 'graph.pbtxt', as_text=True)
tf.train.write_graph(tf_graph.as_graph_def(),
                     'freeze', 'graph.pb', as_text=False)
```

This executes without any problem. Finally, freezing the graph:

```python
from tensorflow.python.tools import freeze_graph

MODEL_NAME = 'har'

input_graph_path = 'freeze/graph.pbtxt'
checkpoint_path = './freeze/checkpoint.ckpt-1'
restore_op_name = "save/restore_all"
filename_tensor_name = "save/Const:0"
output_frozen_graph_name = 'frozen_'+MODEL_NAME+'.pb'

freeze_graph.freeze_graph(input_graph_path, input_saver="",
                          input_binary=False, input_checkpoint=checkpoint_path, 
                          output_node_names="y_", restore_op_name="save/restore_all",
                          filename_tensor_name="save/Const:0", 
                          output_graph=output_frozen_graph_name, clear_devices=True, initializer_nodes="")
```

I got the following error after executing the lines above:

```
AssertionError: y_ is not in graph
```

Is there another way to name the output tensor?

**Comment by haydenth** [comment]
Having a similar issue here as well.

**Comment by chaine09** [comment]
Anyone solved this?

**Comment by haydenth** [comment]
So I think you want to use y_/MatMul or something like that. Haven't figured out exactly which one you want but take a look at the nodes named y_/* that gets created in your pbtext

**Comment by curiousily** [comment]
You can basically print all your nodes (all had some generated name) and use the one you like.

**Comment by nyoshimura** [comment]
`[print(n.name) for n in sess.graph.as_graph_def().node]`
Then name of nodes will be printed out.

**Comment by waynesuzq** [comment]
Is "y_/Softmax" correct? 

I used @nyoshimura 's method to print all the layers and found this.

**Comment by nyoshimura** [comment]
(I'm not sure but) I think so if your output is like this:
`model.add(Activation('softmax', name='y_'))`

**Comment by nyoshimura** [comment]
FYI:
[Run your Keras models in C++ Tensorflow](http://www.bitbionic.com/2017/08/18/run-your-keras-models-in-c-tensorflow/)

**Comment by chris-smith-zocdoc** [comment]
You can get the tensorflow op names like this

```py
[x.op.name for x in model.outputs]
```

**Comment by woshiwanglitao** [comment]
did you solve it ? @curiousily

**Comment by progfiles** [comment]
try this before saving model
`del tf.get_collection_ref(tf.GraphKeys.TRAIN_OPS)[:]  `

**Comment by BBarbosa** [comment]
Hi @progfiles! Which version of TensorFlow are you using?
