### ISSUE TITLE
Training slower on Titan Xp (Pascal) vs. Titan X (Maxwell)

### ISSUE THREAD

**Issue by bfarzin** [keras-team/keras#6640]
Hello,
  I am not totally sure if this is the right place to post/ask about this so please re-direct me if there is a better spot to ask the question.  I tried on the Slack "tipsandtricks" channel but did not hear back from anyone over three days. 

  I have two boxes, one running a Titan X (Maxwell) and one a Titan Xp (Pascal) card.  I believe that the new Xp card should be faster and a [simple RNN benchmark test case](https://github.com/glample/rnn-benchmarks/blob/master/theano/rnn.py) on my boxes show that to be true.  

However, my production problem is slower on the Pascal card and I want to know if I am missing something that would speed it up.  There are a lot of small differences in the machines and I have tried to line them up but get the same results. The current comparison (below) has some small differences:  Keras 1.1 vs. Keras 2, CUDA 7 vs. CUDA 8, etc. What I suspect is that the problem has to do with how the [Maxwell cards page the memory rather than pin to the RAM location for the copy.](http://stackoverflow.com/questions/39782746/why-is-nvidia-pascal-gpus-slow-on-running-cuda-kernels-when-using-cudamallocmana)  

  Below is a very small and simple example of my problem with nonsense data but that replicates the steps and the performance differences.  It is the performance (40% slower on Maxwell) that I also see in my bigger problem.  

  A valid question is "How do you know that it is the mem copy" and to that I have to say I am not totally sure.  I run the nvprof and get the outputs that follow.  Maybe someone can help me to understand  those calls better?

  **What can I check/build/do to try and get a speed up on my Pascal card?**

Titan Xp (Pascal) card (Keras 2, Ubuntu 16.04, CUDA 8.0)
Output:
```
$THEANO_FLAGS='device=gpu1' python example_fit_gen_k2.py 
Using Theano backend.
Using gpu device 1: Graphics Device (CNMeM is disabled, cuDNN 5005)
(250, 800, 3)
Num Samples Per Epoch: 640000
Epoch 1/1
160/160 [==============================] - 160s - loss: 0.0000e+00 

< separate run >

==11596== API calls:
Time(%)      Time     Calls       Avg       Min       Max  Name
 58.20%  108.308s    637313  169.94us  3.1430us  34.256ms  cudaThreadSynchronize
 11.65%  21.6789s   2466108  8.7900us     698ns  3.0919ms  cudaLaunch
 10.42%  19.3967s  21059291     921ns       0ns  4.0050ms  cudaSetupArgument
  8.97%  16.6957s    637482  26.190us     838ns  14.014ms  cudaMalloc
  4.50%  8.38032s    637315  13.149us     769ns  654.71ms  cudaFree
  3.08%  5.73604s    507873  11.294us  3.3530us  30.472ms  cudaMemcpy
  1.59%  2.95857s   3050114     969ns     558ns  518.51us  cudaGetLastError
  1.33%  2.48032s   2466108  1.0050us     558ns  529.27us  cudaConfigureCall
  0.16%  300.07ms       754  397.97us  259.74us  5.8696ms  cudaGetDeviceProperties
  0.06%  106.35ms      5126  20.747us     768ns  425.62us  cudaMemset
  0.02%  44.860ms     10240  4.3800us  1.6070us  1.4768ms  cudaBindTexture
  0.01%  17.654ms     10240  1.7240us     698ns  406.34us  cudaUnbindTexture
  0.00%  1.9572ms       356  5.4970us     698ns  218.33us  cuDeviceGetAttribute
  0.00%  1.2343ms         4  308.58us  98.618us  543.17us  cuDeviceTotalMem
  0.00%  765.19us       751  1.0180us     628ns  15.645us  cudaDriverGetVersion
  0.00%  748.16us       751     996ns     629ns  18.648us  cudaRuntimeGetVersion
  0.00%  160.92us         4  40.229us  33.804us  46.655us  cuDeviceGetName
  0.00%  32.895us        16  2.0550us  1.7460us  4.1200us  cudaEventDestroy
  0.00%  22.140us        16  1.3830us  1.1870us  2.5840us  cudaEventCreateWithFlags
  0.00%  13.899us         5  2.7790us     838ns  7.0540us  cudaGetDevice
  0.00%  13.689us         1  13.689us  13.689us  13.689us  cudaSetDevice
  0.00%  12.505us        11  1.1360us     978ns  1.9560us  cudaDeviceGetAttribute
  0.00%  10.686us         8  1.3350us     768ns  2.0950us  cuDeviceGet
  0.00%  6.0760us         4  1.5190us     768ns  3.1430us  cuDeviceGetCount
  0.00%  6.0760us         2  3.0380us  1.6760us  4.4000us  cudaGetDeviceCount
  0.00%  3.9810us         1  3.9810us  3.9810us  3.9810us  cuInit
  0.00%  1.1170us         1  1.1170us  1.1170us  1.1170us  cuDriverGetVersion

```
Titan X (Maxwell) card (Keras 1.1, Ubuntu 14.04, CUDA 7.0)
Output:
```
$ python example_fit_gen_k2.py 
Using Theano backend.
Couldn't import dot_parser, loading of dot files will not be possible.
Using gpu device 0: GeForce GTX TITAN X (CNMeM is disabled, cuDNN 4007)
(250, 800, 3)
Num Samples Per Epoch: 640000
Epoch 1/1
640000/640000 [==============================] - 114s - loss: 0.0000e+00  

< separate run >
==15110== API calls:
Time(%)      Time     Calls       Avg       Min       Max  Name
 49.49%  63.6606s    445918  142.76us     900ns  171.24ms  cudaMemcpy
 23.91%  30.7547s    495331  62.089us  1.6680us  41.029ms  cudaThreadSynchronize
 13.05%  16.7882s   1995842  8.4110us  6.0480us  2.3525ms  cudaLaunch
  6.60%  8.48816s    495736  17.122us  6.5550us  2.1770ms  cudaMalloc
  3.42%  4.40081s    495333  8.8840us  4.7850us  145.08ms  cudaFree
  2.19%  2.81672s  16619044     169ns     131ns  415.93us  cudaSetupArgument
  0.46%  590.05ms   1995842     295ns     165ns  244.27us  cudaConfigureCall
  0.43%  558.49ms   2492163     224ns     129ns  262.47us  cudaGetLastError
  0.12%  151.97ms       833  182.44us  157.84us  6.3401ms  cudaGetDeviceProperties
  0.12%  148.65ms         1  148.65ms  148.65ms  148.65ms  cudaThreadExit
  0.10%  131.02ms         1  131.02ms  131.02ms  131.02ms  cudaDeviceSynchronize
  0.06%  76.257ms      6080  12.542us  7.6150us  160.31us  cudaMemsetAsync
  0.02%  21.903ms      1618  13.537us  7.9420us  53.619us  cudaMemset
  0.01%  18.517ms      6400  2.8930us  1.2720us  109.59us  cudaBindTexture
  0.01%  12.597ms      6080  2.0710us  1.3090us  15.245us  cudaEventQuery
  0.01%  7.3868ms      6080  1.2140us     889ns  14.869us  cudaEventRecord
  0.01%  6.7764ms      6400  1.0580us     483ns  105.42us  cudaUnbindTexture
  0.00%  380.18us         2  190.09us  188.24us  191.95us  cuDeviceTotalMem
  0.00%  343.60us       166  2.0690us     155ns  72.302us  cuDeviceGetAttribute
  0.00%  228.85us       830     275ns     189ns  3.2550us  cudaDriverGetVersion
  0.00%  169.02us       830     203ns     149ns  6.3840us  cudaRuntimeGetVersion
  0.00%  42.945us         2  21.472us  19.485us  23.460us  cuDeviceGetName
  0.00%  19.617us        16  1.2260us     886ns  4.3770us  cudaEventDestroy
  0.00%  16.158us        16  1.0090us     479ns  7.2680us  cudaEventCreateWithFlags
  0.00%  14.784us         2  7.3920us  1.5910us  13.193us  cudaSetDevice
  0.00%  11.638us         5  2.3270us     497ns  6.8900us  cudaGetDevice
  0.00%  4.8410us        10     484ns     302ns  1.3930us  cudaDeviceGetAttribute
  0.00%  3.3750us         3  1.1250us     514ns  1.9080us  cudaGetDeviceCount
  0.00%  1.5860us         3     528ns     246ns  1.0050us  cuDeviceGetCount
  0.00%     887ns         3     295ns     201ns     393ns  cuDeviceGet
  0.00%     671ns         1     671ns     671ns     671ns  cuInit
  0.00%     402ns         1     402ns     402ns     402ns  cuDriverGetVersion

```

And the simple python file I am running (slight changes for Keras 2.0)

```
import sys
import numpy as np
from keras.models import Model
from keras.layers.core import Dense
from keras.layers import LSTM, Input
from keras.optimizers import Adam
from keras.utils.generic_utils import Progbar

import ipdb
        
def by_date_generator(rnn_X,rnn_y,n_days_back=100,n_days_other=20,shuffle=True):
    '''Generate the dataset as needed for the fit'''
    shuffled_dates = range(n_days_back+n_days_other*n_days_other,len(rnn_X))
    if shuffle:
        np.random.shuffle(shuffled_dates) #applied inplace
    i = 0
    n_symbols = rnn_X.shape[1]
    while 1:
        dt_i = shuffled_dates[i]
        this_X = np.zeros( (n_symbols*n_days_other,n_days_back,rnn_X.shape[2]) )
        this_y = np.zeros( (n_symbols*n_days_other) )
        yield this_X,this_y
        i += 1
        i = i % len(shuffled_dates)
    
def keras_nn_opt(verbose=0):
    num_epochs = 1
    rnn_X = np.random.rand(250,800,3)
    rnn_y = np.random.rand(250,800)
    print rnn_X.shape
    
    n_days_back = 90 
    n_days_other = 5
    n_symbols   = rnn_X.shape[1] 
    n_channels  = rnn_X.shape[2] 

    lstm_n_units = 6
    init_type_name = 'normal'

    main_input = Input(batch_shape=(n_symbols*n_days_other,n_days_back,n_channels))
    lstm_2 = LSTM(lstm_n_units,stateful=True,return_sequences=True,init=init_type_name)(main_input)
    lstm_2 = LSTM(lstm_n_units,stateful=True,return_sequences=True,init=init_type_name)(lstm_2)
    lstm_2 = LSTM(lstm_n_units,stateful=True,return_sequences=False,init=init_type_name)(lstm_2) 
    pred   = Dense(1,init='uniform',activation='tanh')(lstm_2)
    
    model = Model(input=main_input,output=pred)
    opt = Adam(lr=0.01,decay=0.0005)
    model.compile(loss="mse",optimizer=opt)
        
    num_samples   = (len(rnn_X)-n_days_back)*n_symbols*n_days_other
    print "Num Samples Per Epoch: %s" % num_samples

    try:        
        #fit_generator
        # second input goes to (len(rnn_X)-n_days_back) for Keras 2.0 fit_generator style
        train_hist = model.fit_generator(by_date_generator(rnn_X,rnn_y,n_days_back,n_days_other),\
                                         num_samples,\
                                         nb_epoch=num_epochs,\
                                         verbose=verbose)
    except KeyboardInterrupt:
        print "\n Shutdown requested with Ctrl-C..."
        sys.exit(0)
if __name__ == "__main__":
    keras_nn_opt(verbose=1)
```

Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [ x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by bfarzin** [comment]
This is still an issue/problem.  Maybe a bump here if anyone has insight?

Moving my code to PyTorch I not only got the same speed but got a speed up.
PyTorch uses the native CuDNN libraries while Keras has rolled-their-own.  I believe that accounts for the major difference.  When I go to the non-CuDNN version on PyTorch I get a similar slowdown on the Titan Xp.

**Comment by ronamit** [comment]
I am experiencing similar slowdown with Titan Xp (compared to GTX 1080).
Have you found a solution?

**Comment by bfarzin** [comment]
This is still a problem.  It is unfortunate that there is not been any comment from core developers to resolve or even address the problem.

After much work and research I came to realize the source of the problem is in how Keras implements the RNN and how that was formerly dependent on the Maxwell architecture.   After many painful steps and tests I came to the conclusion that I should try another library.

Moving over to PyTorch has been a revolution for me.  I got a 10x speed up in my particular case because PyTorch uses the cuDNN implementation of the LSTM stacked layers.   I also feel the dynamic graph is much easier to debug and understand than the static graph of Theano and TensorFlow.

If you have a particular problem, I can help you to convert it to PyTorch and I suspect you will see the speed up.  Let me know the best way to get in touch with you and I will make that happen.

**Comment by ronamit** [comment]
Thanks!
I will check out PyTorch .
Have you installed it form source?
What version of CUDA and CuDNN did you use?

**Comment by bfarzin** [comment]
From the homepage you can pick out the version you want to use.  
http://pytorch.org/
I have a few boxes some on CUDA 7.5, some on 8.0
I have installed via pip, but if you use conda that is recommended.

I did not find the examples as useful as they could have been.  There is a big leap to get to sequence-to-sequence learning which glosses over some details.  I would suggest creating a toy problem and then testing that you can match those results in a sequence.

Good luck, I think you will enjoy the change!

**Comment by ronamit** [comment]
Great, thanks!
