### ISSUE TITLE
BUG in topology.py: self.is_placeholder should be always True

### ISSUE THREAD

**Issue by lc82111** [keras-team/keras#6662]
I guess the self.is_placeholder should be True when input layer is init with a tf.placeholder, see 
[topology.py#L1338](https://github.com/fchollet/keras/blob/bc9dbc5de0fec911ab8b6cae9696641da9c13d5c/keras/engine/topology.py#L1338)

Because the is_placeholder = False will cause the self._feed_input_names == [], see [topology.py#L1605](https://github.com/fchollet/keras/blob/bc9dbc5de0fec911ab8b6cae9696641da9c13d5c/keras/engine/topology.py#L1605)
Which cause inputs error!

**Comment by chenliu0831** [comment]
+1 for this. It could cause confusing error message when the input tensor is wrapped with `Input`.

**Comment by alidastgheib** [comment]
> I guess the self.is_placeholder should be True when input layer is init with a tf.placeholder, see
> [topology.py#L1338](https://github.com/fchollet/keras/blob/bc9dbc5de0fec911ab8b6cae9696641da9c13d5c/keras/engine/topology.py#L1338)
> 
> Because the is_placeholder = False will cause the self._feed_input_names == [], see [topology.py#L1605](https://github.com/fchollet/keras/blob/bc9dbc5de0fec911ab8b6cae9696641da9c13d5c/keras/engine/topology.py#L1605)
> Which cause inputs error!

If someone always defines the network's inputs by using `tensorflow.keras.layers.Input` or `tensorflow.keras.layers.InputLayer`, then he/she would not encounter the error you mentioned (or the graph confusion you mentioned). @lc82111 , is this statement right? Thank you.
