### ISSUE TITLE
A bug in Conv2DTranspose's build function.

### ISSUE THREAD

**Issue by jichen3000** [keras-team/keras#6793]
Hello there,

I really like the Keras, since it save my lots of time to write Deep Learning network.

But when I used Conv2DTranspose, it would report:

`ValueError: input channels does not match filter's input channels.`

Then I checked the code of Conv2DTranspose, and found there is a bug in keras/layers/convolutional.py  line no:722

`kernel_shape = self.kernel_size + (self.filters, input_dim)`

but it should be:

`kernel_shape = self.kernel_size + (input_dim , self.filters)`

When I changed as above, my code passed.

And also, I checked other build functions and they all put input_dim before self.filters.

Please review and confirm it.

Thanks.

**Comment by divamgupta** [comment]
This issue came due to the same reason mentioned above 
https://github.com/fchollet/keras/issues/6777

**Comment by jichen3000** [comment]
divamgupta, thanks to confirm this issue.

**Comment by vadym-wix** [comment]
Any updates on this bug?
Or how to overcome it?
