### ISSUE TITLE
Any multi-GPU solution for Theano backend?

### ISSUE THREAD

**Issue by mycrazycracy** [keras-team/keras#6857]
Hey guys,
    I used keras 2.0.4 for weeks, and found it really convenient to build my idea. I once use tensorflow backend until I found theano is faster than tensorflow on my server. I double checked my installation and I think there is no problem. I also found many people report theano is actually faster in the forum. Anyway, I change my backend to theano now.
    Now, the problem is there is NO OUT-OF-BOX SOLUTION for theano backend to use multiple GPUs. As I have 8 K40s in my server, I would definitely like to utilize them by either data or model parallelism. 
    I searched all the issues here (or google it) and just found a way to use multiple GPUs for tensorflow backend (e.g. https://github.com/fchollet/keras/issues/2436). But almost one year passed, there is still no such solution for theano. I would very very appreciate it if anyone could help me for this issue!

**Comment by mycrazycracy** [comment]
I would wonder nobody face this problem or just because I miss something?
I think multi-gpu training is critical in the deep learning software society. Isn't it?
Anyone could help?

**Comment by edmondja** [comment]
Maybe this can help for multi-gpu https://github.com/Microsoft/CNTK/issues/797.

**Comment by mycrazycracy** [comment]
Still, it seems like there is no clear answer for this problem. Oooops...

**Comment by JeniaNovellusDx** [comment]
4 months passed and no one could help this poor lad? I'm also wondering what's the issue with that slower tensorflow backend and why there's no multi gpu support in keras
