### ISSUE TITLE
No module named keras.preprocessing.image

### ISSUE THREAD

**Issue by AUREBORN** [keras-team/keras#692]
I just study keras for a few days and I have met this problem. Is there anyone willing to help me to solve this problem.Thanks very much!

**Comment by ludwikbukowski** [comment]
I have the same issue

**Comment by xring** [comment]
@ludwikbukowski 
```
sudo pip install keras
Requirement already satisfied: keras in /usr/lib/python2.7/site-packages
Requirement already satisfied: theano in /usr/lib/python2.7/site-packages (from keras)
Requirement already satisfied: pyyaml in /usr/lib64/python2.7/site-packages (from keras)
Requirement already satisfied: six in /usr/lib/python2.7/site-packages (from keras)
Requirement already satisfied: numpy>=1.7.1 in /usr/lib64/python2.7/site-packages (from theano->keras)
Requirement already satisfied: scipy>=0.11 in /usr/lib64/python2.7/site-packages (from theano->keras)
```
`sudo pip install keras` do not work

**Comment by clockwiser** [comment]
I have similar problem.
Import error: No module named keras.preprocessing.text

**Comment by mabdrabo** [comment]
I have the same problem.
module 'keras.preprocessing' has no attribute 'text'

**Comment by mabdrabo** [comment]
It worked after updating keras, tensorflow and importing from keras.preprocessing.text specifically
I know updating alone wasn't enough, but I don't know if it could have worked with just the import.

pip install -U pip tensorflow 

from keras.preprocessing.text import Tokenizer

**Comment by chakpongchung** [comment]
same problem here, see what I have did and my environment:





which python
pip install keras
conda install keras
conda list
python -c "import keras; print(keras.__version__)" 




+ which python
/home/cpchung/anaconda2/bin/python
+ pip install keras
Requirement already satisfied: keras in /home/cpchung/.local/lib/python2.7/site-packages
Requirement already satisfied: six in /home/cpchung/.local/lib/python2.7/site-packages (from keras)
Requirement already satisfied: pyyaml in /home/cpchung/.local/lib/python2.7/site-packages (from keras)
Requirement already satisfied: theano in /home/cpchung/.local/lib/python2.7/site-packages (from keras)
Requirement already satisfied: numpy>=1.9.1 in /home/cpchung/.local/lib/python2.7/site-packages (from theano->keras)
Requirement already satisfied: scipy>=0.14 in /home/cpchung/.local/lib/python2.7/site-packages (from theano->keras)
+ conda install keras
Fetching package metadata .........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /home/cpchung/anaconda2:
#
keras                     2.0.2                    py27_0  
+ conda list
# packages in environment at /home/cpchung/anaconda2:
#
_license                  1.1                      py27_1  
alabaster                 0.7.9                    py27_0  
anaconda                  4.3.1               np111py27_0  
anaconda-client           1.6.0                    py27_0  
anaconda-navigator        1.5.0                    py27_0  
anaconda-project          0.4.1                    py27_0  
argcomplete               1.0.0                    py27_1  
astroid                   1.4.9                    py27_0  
astropy                   1.3                 np111py27_0  
babel                     2.3.4                    py27_0  
backports                 1.0                      py27_0  
backports_abc             0.5                      py27_0  
beautifulsoup4            4.5.3                    py27_0  
bitarray                  0.8.1                    py27_0  
blaze                     0.10.1                   py27_0  
bokeh                     0.12.4                   py27_0  
boto                      2.45.0                   py27_0  
bottleneck                1.2.0               np111py27_0  
cairo                     1.14.8                        0  
cdecimal                  2.3                      py27_2  
cffi                      1.9.1                    py27_0  
chardet                   2.3.0                    py27_0  
chest                     0.2.3                    py27_0  
click                     6.7                      py27_0  
cloudpickle               0.2.2                    py27_0  
clyent                    1.2.2                    py27_0  
colorama                  0.3.7                    py27_0  
conda                     4.3.21                   py27_0  
conda-env                 2.6.0                         0  
configobj                 5.0.6                    py27_0  
configparser              3.5.0                    py27_0  
contextlib2               0.5.4                    py27_0  
cryptography              1.7.1                    py27_0  
curl                      7.52.1                        0  
cycler                    0.10.0                   py27_0  
cython                    0.25.2                   py27_0  
cytoolz                   0.8.2                    py27_0  
dask                      0.13.0                   py27_0  
datashape                 0.5.4                    py27_0  
dbus                      1.10.10                       0  
decorator                 4.0.11                   py27_0  
dill                      0.2.5                    py27_0  
docutils                  0.13.1                   py27_0  
entrypoints               0.2.2                    py27_0  
enum34                    1.1.6                    py27_0  
et_xmlfile                1.0.1                    py27_0  
expat                     2.1.0                         0  
fastcache                 1.0.2                    py27_1  
flask                     0.12                     py27_0  
flask-cors                3.0.2                    py27_0  
fontconfig                2.12.1                        2  
freetype                  2.5.5                         2  
funcsigs                  1.0.2                    py27_0  
functools32               3.2.3.2                  py27_0  
futures                   3.0.5                    py27_0  
get_terminal_size         1.0.0                    py27_0  
gevent                    1.2.1                    py27_0  
glib                      2.50.2                        1  
greenlet                  0.4.11                   py27_0  
grin                      1.2.1                    py27_3  
gst-plugins-base          1.8.0                         0  
gstreamer                 1.8.0                         0  
h5py                      2.6.0               np111py27_2  
harfbuzz                  0.9.39                        2  
hdf5                      1.8.17                        1  
heapdict                  1.0.0                    py27_1  
icu                       54.1                          0  
idna                      2.2                      py27_0  
imagesize                 0.7.1                    py27_0  
ipaddress                 1.0.18                   py27_0  
ipykernel                 4.5.2                    py27_0  
ipython                   5.1.0                    py27_0  
ipython_genutils          0.1.0                    py27_0  
ipywidgets                5.2.2                    py27_1  
isort                     4.2.5                    py27_0  
itsdangerous              0.24                     py27_0  
jbig                      2.1                           0  
jdcal                     1.3                      py27_0  
jedi                      0.9.0                    py27_1  
jinja2                    2.9.4                    py27_0  
jpeg                      9b                            0  
jsonschema                2.5.1                    py27_0  
jupyter                   1.0.0                    py27_3  
jupyter_client            4.4.0                    py27_0  
jupyter_console           5.0.0                    py27_0  
jupyter_core              4.2.1                    py27_0  
keras                     2.0.2                    py27_0  
lazy-object-proxy         1.2.2                    py27_0  
libffi                    3.2.1                         1  
libgcc                    4.8.5                         2  
libgfortran               3.0.0                         1  
libgpuarray               0.6.4                         0  
libiconv                  1.14                          0  
libpng                    1.6.27                        0  
libprotobuf               3.2.0                         0  
libsodium                 1.0.10                        0  
libtiff                   4.0.6                         3  
libxcb                    1.12                          1  
libxml2                   2.9.4                         0  
libxslt                   1.1.29                        0  
llvmlite                  0.15.0                   py27_0  
locket                    0.2.0                    py27_1  
lxml                      3.7.2                    py27_0  
mako                      1.0.6                    py27_0  
markupsafe                0.23                     py27_2  
matplotlib                2.0.0               np111py27_0  
mistune                   0.7.3                    py27_0  
mkl                       2017.0.1                      0  
mkl-service               1.1.2                    py27_3  
mock                      2.0.0                    py27_0  
mpmath                    0.19                     py27_1  
multipledispatch          0.4.9                    py27_0  
nbconvert                 4.2.0                    py27_0  
nbformat                  4.2.0                    py27_0  
networkx                  1.11                     py27_0  
nltk                      3.2.2                    py27_0  
nose                      1.3.7                    py27_1  
notebook                  4.3.1                    py27_0  
numba                     0.30.1              np111py27_0  
numexpr                   2.6.1               np111py27_2  
numpy                     1.11.3                   py27_0  
numpydoc                  0.6.0                    py27_0  
odo                       0.5.0                    py27_1  
openpyxl                  2.4.1                    py27_0  
openssl                   1.0.2k                        1  
pandas                    0.19.2              np111py27_1  
partd                     0.3.7                    py27_0  
path.py                   10.0                     py27_0  
pathlib2                  2.2.0                    py27_0  
patsy                     0.4.1                    py27_0  
pbr                       1.10.0                   py27_0  
pcre                      8.39                          1  
pep8                      1.7.0                    py27_0  
pexpect                   4.2.1                    py27_0  
pickleshare               0.7.4                    py27_0  
pillow                    4.0.0                    py27_0  
pip                       9.0.1                    py27_1  
pixman                    0.34.0                        0  
ply                       3.9                      py27_0  
prompt_toolkit            1.0.9                    py27_0  
protobuf                  3.2.0                    py27_0  
psutil                    5.0.1                    py27_0  
ptyprocess                0.5.1                    py27_0  
py                        1.4.32                   py27_0  
pyasn1                    0.1.9                    py27_0  
pycairo                   1.10.0                   py27_0  
pycosat                   0.6.1                    py27_1  
pycparser                 2.17                     py27_0  
pycrypto                  2.6.1                    py27_4  
pycurl                    7.43.0                   py27_2  
pyflakes                  1.5.0                    py27_0  
pygments                  2.1.3                    py27_0  
pygpu                     0.6.4                    py27_1  
pylint                    1.6.4                    py27_1  
pyopenssl                 16.2.0                   py27_0  
pyparsing                 2.1.4                    py27_0  
pyqt                      5.6.0                    py27_2  
pytables                  3.3.0               np111py27_0  
pytest                    3.0.5                    py27_0  
python                    2.7.13                        0  
python-dateutil           2.6.0                    py27_0  
pytz                      2016.10                  py27_0  
pyyaml                    3.12                     py27_0  
pyzmq                     16.0.2                   py27_0  
qt                        5.6.2                         3  
qtawesome                 0.4.3                    py27_0  
qtconsole                 4.2.1                    py27_1  
qtpy                      1.2.1                    py27_0  
readline                  6.2                           2  
redis                     3.2.0                         0  
redis-py                  2.10.5                   py27_0  
requests                  2.12.4                   py27_0  
rope                      0.9.4                    py27_1  
ruamel_yaml               0.11.14                  py27_1  
scandir                   1.4                      py27_0  
scikit-image              0.12.3              np111py27_1  
scikit-learn              0.18.1              np111py27_1  
scipy                     0.18.1              np111py27_1  
seaborn                   0.7.1                    py27_0  
setuptools                27.2.0                   py27_0  
simplegeneric             0.8.1                    py27_1  
singledispatch            3.4.0.3                  py27_0  
sip                       4.18                     py27_0  
six                       1.10.0                   py27_0  
snowballstemmer           1.2.1                    py27_0  
sockjs-tornado            1.0.3                    py27_0  
sphinx                    1.5.1                    py27_0  
spyder                    3.1.2                    py27_0  
sqlalchemy                1.1.5                    py27_0  
sqlite                    3.13.0                        0  
ssl_match_hostname        3.4.0.2                  py27_1  
statsmodels               0.6.1               np111py27_1  
subprocess32              3.2.7                    py27_0  
sympy                     1.0                      py27_0  
tensorflow                1.1.0               np111py27_0  
terminado                 0.6                      py27_0  
theano                    0.9.0                    py27_0  
tk                        8.5.18                        0  
toolz                     0.8.2                    py27_0  
tornado                   4.4.2                    py27_0  
traitlets                 4.3.1                    py27_0  
unicodecsv                0.14.1                   py27_0  
wcwidth                   0.1.7                    py27_0  
werkzeug                  0.11.15                  py27_0  
wheel                     0.29.0                   py27_0  
widgetsnbextension        1.2.6                    py27_0  
wrapt                     1.10.8                   py27_0  
xlrd                      1.0.0                    py27_0  
xlsxwriter                0.9.6                    py27_0  
xlwt                      1.2.0                    py27_0  
xz                        5.2.2                         1  
yaml                      0.1.6                         0  
zeromq                    4.1.5                         0  
zlib                      1.2.8                         3  
+ python -c 'import keras; print(keras.__version__)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "keras.py", line 28, in <module>
    from keras.preprocessing.text import Tokenizer
ImportError: No module named preprocessing.text

**Comment by ulfaslak** [comment]
I have the same problem with `.text`. All the files are however inside `preprocessing` (`image.py`, `sequence.py`, `text.py`) but only sequence can be imported.

**Comment by controlly** [comment]
you can update the keras to the lastest version.

**Comment by AsmaZgo** [comment]
> It worked after updating keras, tensorflow and importing from keras.preprocessing.text specifically
> I know updating alone wasn't enough, but I don't know if it could have worked with just the import.
> 
> pip install -U pip keras tensorflow
> 
> from keras.preprocessing.text import Tokenizer
this worked for me too!

**Comment by nkwarrior84** [comment]
AttributeError                            Traceback (most recent call last)
<ipython-input-59-d02d711d342b> in <module>()
      1 m,n,r = bgr_image.shape
----> 2 arr = keras.preprocessing.image.reshape(m*n, -1)
      3 df = pd.DataFrame(arr, columns=['b', 'g', 'r'])
      4 df.describe()

AttributeError: module 'keras.preprocessing.image' has no attribute 'reshape'

**Comment by nkwarrior84** [comment]
I am getting this error

**Comment by nkwarrior84** [comment]
> I am getting this error

Using Colab

**Comment by Euphoria08** [comment]
I am getting error in importing any module from tensor.keras in my colab notebook.
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.preprocessing import image
I am getting a module not found error in the above line of codes.

**Comment by syam37** [comment]
> 

i am getting the same

**Comment by LURADU** [comment]
same problem just i write keras.preprocessing without tensorflow and working

**Comment by Sagarmadli** [comment]
from keras.preprocessing.image import img_to_array
ImportError: cannot import name 'img_to_array' from 'keras.preprocessing.image'

**Comment by SkyisjustTheBeginning** [comment]
I am also getting an error - 

`ImportError: cannot import name 'pad_sequences' from 'keras.preprocessing.sequence'`

Versions - 

Ubuntu 20.04
Keras - 2.9.0
Tensorflow - 2.9.0

My code so far - 

`from keras.utils import to_categorical
from keras.layers import Dense, Dropout, Conv1D, MaxPool1D, GlobalMaxPool1D, Embedding, Activation
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential`

**Comment by calvincheunghk** [comment]
https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing
it is no longer supported in v2.12.0

you can try to downgrade the TF and keras to 2.7.0
following is a code example

!pip install tensorflow==2.7.0
!pip install keras==2.7.0

from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer
import pandas as pd
import numpy as np

**Comment by calvincheunghk** [comment]
according to the TF document, there is new equivalent like TextVectorization (refer to the link at the bottom)

https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/text/Tokenizer

https://www.tensorflow.org/api_docs/python/tf/keras/layers/TextVectorization

**Comment by chaitanyakulkarni2k2** [comment]
pip install -U pip keras tensorflow

Not working this at my side.

**Comment by yayunl** [comment]
Use  !pip install Keras-Preprocessing to install the package in colab

**Comment by vishalverma781** [comment]
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 2
      1 from keras.utils import to_categorical
----> 2 from keras_preprocessing.image import load_img
      3 from keras.models import Sequential
      4 from keras.layers import Dense, Conv2D, Dropout, Flatten, MaxPooling2D

ModuleNotFoundError: No module named 'keras_preprocessing'

this problem i will phase how to solve please help anyone !
