### ISSUE TITLE
Broken: variational_autoencoder.py example with tensorflow distribution of keras not working

### ISSUE THREAD

**Issue by PaulDufort** [keras-team/keras#6950]
Hi, trying to run the variational_autoencoder.py example with the tensorflow distribution of keras. The first couple of problems can be fixed with minor edits:

1) Need to change all "from keras.X import Y"  import statements to "from tensorflow.contrib.keras.python.keras.X import Y". No problem there.

2) Need to remove the "output_shape=(latent_dim,)" parameter from line 36 so it becomes "z = Lambda(sampling)([z_mean, z_log_var])". No problem there either.
 
But then the following output is generated:

C:\Users\paul.dufort\AppData\Local\Continuum\Anaconda3\envs\tensorflow\lib\site-
packages\tensorflow\contrib\keras\python\keras\engine\topology.py:1504: UserWarning: Model inputs must come from a Keras Input layer, they cannot be the output of a previous non-Input layer. Here, a tensor specified as input to "model_1" was not an Input tensor, it was generated by layer custom_variational_layer_1. Note that input tensors are instantiated via `tensor = Input(shape)`.
The tensor that caused the issue was: input_1:0
  'The tensor that caused the issue was: ' + str(x.name))
C:\Users\paul.dufort\AppData\Local\Continuum\Anaconda3\envs\tensorflow\lib\site-
packages\tensorflow\contrib\keras\python\keras\engine\training.py:740: UserWarning: Output "custom_variational_layer_1" missing from loss dictionary. We assume this was done on purpose, and we will not be expecting any data to be passed to "custom_variational_layer_1" during training.
  '" during training.')
Traceback (most recent call last):
  File "variational_autoencoder.py", line 81, in <module>
    validation_data=(x_test, x_test))
  File "C:\Users\paul.dufort\AppData\Local\Continuum\Anaconda3\envs\tensorflow\l
ib\site-packages\tensorflow\contrib\keras\python\keras\engine\training.py", line
 1426, in fit
    batch_size=batch_size)
  File "C:\Users\paul.dufort\AppData\Local\Continuum\Anaconda3\envs\tensorflow\l
ib\site-packages\tensorflow\contrib\keras\python\keras\engine\training.py", line
 1305, in _standardize_user_data
    exception_prefix='model target')
  File "C:\Users\paul.dufort\AppData\Local\Continuum\Anaconda3\envs\tensorflow\l
ib\site-packages\tensorflow\contrib\keras\python\keras\engine\training.py", line
 118, in _standardize_input_data
    'Found: array with shape ' + str(data.shape))
ValueError: The model expects 0 input arrays, but only received one array. Found
: array with shape (10000, 784)

This seems to suggest that on line 65 "vae = Model(x, y)", it is taking y to be the input. Any ideas?

Thanks,
Paul

**Comment by acorbe** [comment]
same problem here

**Comment by gaborgulyas** [comment]
It worked for me, seemingly. But at the end it turned out that the model didn't learn :(
So there might be more fundamental issues with this.

**Comment by PaulDufort** [comment]
Thanks for checking. I wonder if there are differences between the version of keras incorporated into tensorflow and the standalone version? I was using the one packaged with tf.

Anyway, I ended up falling back to a pure tensorflow implementation based on Miriam Shiffman's post,

http://blog.fastforwardlabs.com/2016/08/22/under-the-hood-of-the-variational-autoencoder-in.html

and managed to get that working well.

**Comment by fgvenegas** [comment]
Same problem here, [this version](https://github.com/fchollet/keras/blob/master/examples/variational_autoencoder.py) doesn't work with the same problem of Paul and [this other](https://blog.keras.io/building-autoencoders-in-keras.html) doesn't learn :( I think the problem could be the loss function maybe

**Comment by falaktheoptimist** [comment]
This has been resolved with https://github.com/fchollet/keras/blob/keras-2/examples/variational_autoencoder.py Not sure when this will be made part of the master branch.

**Comment by dbl001** [comment]
Same problem.
```
import keras
keras.__version__
'2.0.3'
```

**Comment by dbl001** [comment]
Correct.  It’s working with 2.0.8.
Thank You!

**Comment by dbl001** [comment]
With CPU Keras/Tensorflow the model loss increases at around epoc 46. Does this happen with GPU?

Epoch 43/50
60000/60000 [==============================] - 39s - loss: 228.1965 - val_loss: 211.7813
Epoch 44/50
60000/60000 [==============================] - 41s - loss: 231.2153 - val_loss: 194.3453
Epoch 45/50
60000/60000 [==============================] - 39s - loss: 378.1528 - val_loss: 208.3385
Epoch 46/50
60000/60000 [==============================] - 41s - loss: 52502.6612 - val_loss: 14091533.7113
Epoch 47/50
60000/60000 [==============================] - 42s - loss: 1622085526136.4717 - val_loss: inf
Epoch 48/50
60000/60000 [==============================] - 41s - loss: nan - val_loss: nan  Epoch 49/50   
60000/60000 [==============================] - 37s - loss: nan - val_loss: nan
Epoch 50/50
60000/60000 [==============================] - 40s - loss: nan - val_loss: nan

In [4]: keras.__version__
Out[4]: '2.0.8'

In [5]: tensorflow.__version__
Out[5]: '1.0.1'

In [6]:
