### ISSUE TITLE
How to build a Dense layer for every timestamp of a RNN and feedback every Dense's output into RNN ?

### ISSUE THREAD

**Issue by slkingxr** [keras-team/keras#6951]
![dense_with_lstm1](https://user-images.githubusercontent.com/19548110/27017892-9a100f50-4f5e-11e7-9830-2e665c07df19.png)
As the figure shows, I need to get the state of every Lstm timestamp and apply them to a dense layer for a supervised learning. Then using the output of this dense layer together with the state for next timestamp of Lstm.  In general , I want to apply supervised-learning for every step of RNN and feedbackthe output to next timestamp. How can I implement this In Keras?

**Comment by asalekin** [comment]
Have you got any solution for this?
