### ISSUE TITLE
Lambda Layer giving "ValueError: None values not supported" when trying to fit model

### ISSUE THREAD

**Issue by raymond-yuan** [keras-team/keras#6953]
Hello, 

I've written a lambda layer in Keras to sparsify an input:

    def sparsify(x, percent_zero_dims):
        k_val = int((1.0 - percent_zero_dims / 100.0) * K.int_shape(x)[1])

        values, indices = tf.nn.top_k(x, k=k_val, sorted=False)
        # We need to create full indices like [[0, 0], [0, 1], [1, 2], [1, 1]]
        my_range = tf.expand_dims(tf.range(0, K.shape(indices)[0]), 1)  # will be [[0], [1]]
        my_range_repeated = tf.tile(my_range, [1, k_val])  # will be [[0, 0], [1, 1]]

        # change shapes to [N, k, 1] and [N, k, 1], to concatenate into [N, k, 2]
        full_indices = tf.concat([tf.expand_dims(my_range_repeated, 2), tf.expand_dims(indices, 2)], 2)
        full_indices = tf.reshape(full_indices, [-1, 2])
        output = tf.sparse_to_dense(full_indices, K.shape(x), tf.reshape(values, [-1]), default_value=0.,
                            validate_indices=False)
        return output
I'm calling the lambda layer in my model by:

    sparse = Lambda(lambda x: sparsify(x, sparse_perc))(relu)

The input shape is (None, 32) and (None, 32) is getting output for this layer. I've also written this lambda layer as a custom layer, which throws the same error. If I set the model output to relu, it trains fine, but when I use sparse as my output, the model throws

    line 360, in make_tensor_proto
    raise ValueError("None values not supported.")

I can predict on the model, compile, without issues and get the expected results, but when I try fitting it, the model throws an error. I believe it's related to invalid loss getting generated from this output as seen in the stack trace:

    line 1014, in _make_train_function
    self.total_loss)...

I've tried removing any nans from the output of the sparse layer (which I know isn't good practice but I'm just tyring to figure out where/how it's breaking):

    Lambda(lambda x: tf.where(tf.is_nan(x), tf.zeros_like(x), x))(sparse)

This happens to me on a couple of other custom layers in the model, but not all of them, which is why I'm confused, and I'm not sure what I'm doing differently.

specs: python 3.5

mac osx

Keras 2.0.4

tf 1.1.0

**Comment by nk-shruti** [comment]
I"ve a similar issue ^

**Comment by tc-yue** [comment]
same problem

**Comment by jonathanglima** [comment]
Same here. Code as follows:

https://github.com/jonathanglima/deepranking_keras/blob/master/deep_ranking.ipynb
