### ISSUE TITLE
Merge Batch Renormalization implementation

### ISSUE THREAD

**Issue by StefanoD** [keras-team/keras#6984]
At the moment (version 2.0.5) there is no implementation of Batch Renormalization, but in [keras contrib](https://github.com/farizrahman4u/keras-contrib/pull/28).
Is there any intention to merge this?

**Comment by StefanoD** [comment]
Still not merged.

**Comment by unnir** [comment]
Any updates?

**Comment by bryan831** [comment]
i would like to have this as well ~

**Comment by wosiu** [comment]
+1 !

**Comment by PhilipMay** [comment]
+1

**Comment by PhilipMay** [comment]
Well. There still seem to be bugs in this implementation: 
https://github.com/keras-team/keras-contrib/blob/master/keras_contrib/layers/normalization.py#L224
