### ISSUE TITLE
Installation with both CPU/GPU tensorflow modules

### ISSUE THREAD

**Issue by KiddoZhu** [keras-team/keras#6997]
It is said in the document that keras will automatically run on GPU with tensorflow backend.

However, I found Keras depends on the installation order of tensorflow modules. It seems that keras always use the module installed last. For example,

`pip install tensorflow-gpu tensorflow`

Keras will use CPU under this circumenstance.

**Comment by ziky90** [comment]
I have experimented with this a bit on my machine and it seems to me that the default behaviour working directly with `tensorflow==1.1.0` is following:

If I perform the installation in the following order:
```
sudo pip install tensorflow
sudo pip install tensorflow-gpu
```
then GPU version is being used
But if I install it in the opposite order:
```
sudo pip install tensorflow-gpu
sudo pip install tensorflow
```
then CPU version is being used.

I have performed the experiment not using keras, just importing tensorflow directly (the same way keras does it in the tensorflow backend module). And I have installed it directly to the root python 2.7. on Ubuntu 16.04.2.

**Comment by KiddoZhu** [comment]
> I have performed the experiment not using keras, just importing tensorflow directly (the same way keras does it in the tensorflow backend module).

Yep. It seems the bug is caused by the new tensorflow. Maybe the document only tested on tensorflow 0.x.

**Comment by nguyenvo09** [comment]
It seems using below code does not force Keras 2.0 to use CPU any more. Any comment?
import os
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"   # see issue #152
os.environ["CUDA_VISIBLE_DEVICES"] = ""

**Comment by lxbcd94** [comment]
As a new user of Keras, I was curious about how could I know which tensorflow is uesd in Keras?

**Comment by KiddoZhu** [comment]
@lxbcd94 
If you use the default tensorflow and CUDA settings, the program should print some lines about GPU info when using tensorflow-gpu. Although it is clumsy, it works in all cases for me.

**Comment by mudigonda** [comment]
Was there a fix for this?

**Comment by JuliB15** [comment]
This question has been answered multiple times before. You can force tensorflow-gpu ins keras to use cpu with

#disable GPU
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"   # see issue #152
os.environ['CUDA_VISIBLE_DEVICES'] = '-1'     # -1 !!!!

**Comment by GoingMyWay** [comment]
> This question has been answered multiple times before. You can force tensorflow-gpu ins keras to use cpu with
> 
> #disable GPU
> import os
> os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID" # see issue #152
> os.environ['CUDA_VISIBLE_DEVICES'] = '-1' # -1 !!!!

It works.

**Comment by ymodak** [comment]
Closing this issue since its solved. Feel free to reopen if it still persists.

**Comment by Daya-Jin** [comment]
useful, mark
