### ISSUE TITLE
Load_model() does not work when architecture contains submodels merged into the main model

### ISSUE THREAD

**Issue by ben0it8** [keras-team/keras#7013]
Hi! 

Given is the following type of architecture:
```
submodels = []
        for kernel_size in [3,4,5]: #
            submodel = Sequential()
            submodel.add(Embedding(nb_words,
                                   embedding_dim,
                                   weights=embedding_m,
                                   input_length=max_len,
                                   trainable=False))
            submodel.add(Dropout(d1))
            submodel.add(Conv1D(nb_filters,
                                kernel_size,
                                padding='valid',
                                activation='relu',
                                strides=1))
            submodel.add(GlobalMaxPooling1D())
            submodels.append(submodel)
model = Sequential()
model.add(Merge(submodels, mode="concat"))
model.add(LSTM(lstm_units, return_sequences=False))
model.add(Dropout(d2))
model.add(Dense(num_labels, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=[
            'categorical_accuracy', 'top_k_categorical_accuracy'])
```
When I try to re-load the saved .h5 model, I get the following error:

> ValueError                                Traceback (most recent call last)
> <ipython-input-37-cd6b49ad1258> in <module>()
> ----> 1 model = load_model('model.h5')
> 
> /Users/d069049/anaconda/envs/sapnlu/lib/python2.7/site-packages/keras/models.pyc in load_model(filepath, custom_objects)
>     241 
>     242     # set weights
> --> 243     topology.load_weights_from_hdf5_group(f['model_weights'], model.layers)
>     244 
>     245     # instantiate optimizer
> 
> /Users/d069049/anaconda/envs/sapnlu/lib/python2.7/site-packages/keras/engine/topology.pyc in load_weights_from_hdf5_group(f, layers)
>    2941                          'containing ' + str(len(layer_names)) +
>    2942                          ' layers into a model with ' +
> -> 2943                          str(len(filtered_layers)) + ' layers.')
>    2944 
>    2945     # We batch weight value assignments in a single backend call
> 
> ValueError: You are trying to load a weight file containing 12 layers into a model with 3 layers.

Obviously, the compiled model variable stores 3 layers, whereas in reality the whole model comprises of 3x3 more, a total of 12.
Do you know a workaround to be able to save and load this type of merged models as well?

**Comment by MicBA** [comment]
similar problem here.. 
any news?

**Comment by LukasMasuch** [comment]
I have the same problem, is there any workaround?

**Comment by fchollet** [comment]
Please post a code example that other people can run to reproduce the issue (including model definition, saving, and loading).

**Comment by MicBA** [comment]
Hi @fchollet  

when i run this code: 

from keras.models import Sequential, load_model
from keras.layers import Conv2D, MaxPooling2D, AveragePooling2D, LeakyReLU
from keras.layers import Dense, Dropout, Flatten, Activation
from keras.layers import Merge

alpha = 1/5.5
img_rows, img_cols = 33, 33
nb_conv1 = 5
print("bulid 2CNN model")
left_branch = Sequential()
left_branch.add(Conv2D(filters=64,
                       kernel_size=(nb_conv1, nb_conv1),
                       padding='valid',
                       data_format='channels_first',
                       input_shape=(1, img_rows, img_cols)))
left_branch.add(Activation('relu'))
left_branch.add(Conv2D(filters=128,
                       kernel_size=(3, 3),
                       padding='valid',
                       data_format='channels_first'))
left_branch.add(Activation('relu'))
left_branch.add(MaxPooling2D(pool_size=(2, 2),
                             data_format='channels_first'))
left_branch.add(Dropout(0.25))

right_branch = Sequential()
right_branch.add(Conv2D(filters=64,
                        kernel_size=(nb_conv1, nb_conv1),
                        padding='valid',
                        data_format='channels_first',
                        input_shape=(1, img_rows, img_cols)))
right_branch.add(Activation('relu'))
right_branch.add(Conv2D(filters=128,
                        kernel_size=(3, 3),
                        padding='valid',
                        data_format='channels_first'))
right_branch.add(Activation('relu'))
right_branch.add(MaxPooling2D(pool_size=(2, 2),
                              data_format='channels_first'))
right_branch.add(Dropout(0.25))

model = Sequential()
model.add(Merge([left_branch, right_branch], mode='concat', concat_axis=1))
model.add(Conv2D(filters=32,
                 kernel_size=(3, 3),
                 padding='valid',
                 data_format='channels_first'))
model.add(Activation('relu'))
model.add(AveragePooling2D(pool_size=(2, 2),
                           data_format='channels_first'))
model.add(Flatten())
model.add(Dropout(0.25))
model.add(Dense(512))
model.add(Activation('relu'))
model.add(Dropout(0.25))
model.add(Dense(128))
model.add(Activation('relu'))
model.add(Dropout(0.25))
model.add(Dense(32))
model.add(Activation('relu'))
model.add(Dropout(0.25))
model.add(Dense(1, activation='sigmoid'))
model.summary()

model.save('model.h5')

del model

model = load_model('model.h5')

i get: 

C:\keras\keras\engine\topology.py:1242: UserWarning: The `Merge` layer is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
  return cls(**config)
Traceback (most recent call last):
  File "I:/PycharmProjects/convert_old_to_new_API.py", line 69, in <module>
    model = load_model('model.h5')
  File "C:\keras\keras\models.py", line 249, in load_model
    topology.load_weights_from_hdf5_group(f['model_weights'], model.layers)
  File "C:\keras\keras\engine\topology.py", line 2981, in load_weights_from_hdf5_group
    str(len(filtered_layers)) + ' layers.')
ValueError: You are trying to load a weight file containing 9 layers into a model with 5 layers.

as i see it.. the function that build the model from .h5 with the weights in sequential case don't take in count the Merge function that holds 2 (or more ) sequential models in it 
when trying to insert the weights 

run with:
keras - 2.0.5
tf - 1.2.0 
OS -  windows 

Thanks

**Comment by jorgecarleitao** [comment]
FYI, a minimal working example:

```
from keras.models import Sequential, load_model, save_model
from keras.layers import Conv1D, Merge

submodels = []
for kernel_size in [3, 4, 5]:
    submodel = Sequential()
    submodel.add(Conv1D(1, (1,), activation='relu', input_shape=(2, 2)))
    submodels.append(submodel)
model = Sequential()
model.add(Merge(submodels, mode="concat"))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['categorical_accuracy'])

model.save('foo.h5')
model = load_model('foo.h5')
```

> ValueError: You are trying to load a weight file containing 3 layers into a model with 0 layers.

**Comment by jorgecarleitao** [comment]
What I got so far: the reason for the discrepancy is that `Merge` is being interpreted as `needs_legacy_support` and thus, in `save_model.get_json_type` at `models.py`, the `model_layers` passed to `topology.save_weights_to_hdf5_group` are the layers of the Merge.

However, when loading the model, those layers will appear in the list of layers of the parent model, and will not be loaded as part of the Merge. Because the parent model has no layers (why?), it complains.

Not yet sure how to solve this or if it is worth addressing since Merge is deprecated.

**Comment by ben0it8** [comment]
Using the functional API and layers.merge.Concatenate layer on the output tensors of the convolutions solved the problem for me.

**Comment by Erechtheus** [comment]
Another option is to save the model configuration and the weights individually, using `model.to_yaml()` and `model.save_weights()`. However, the solution of @ben0it8 is better, as it avoids the deprecated Merge call.

**Comment by nadavb** [comment]
Same problem here. That's the model I use:

```
modelRight = Sequential()
modelLeft  = Sequential()
model = Sequential()

modelRight.add(LSTM(100, input_shape=(20, 50), 
               return_sequences=False, name='right_input'))

modelLeft.add(LSTM(100, input_shape=(20, 50), 
               return_sequences=False, name='left_input'))

model.add(Merge([modelRight, modelLeft],mode='concat'))

model.add(Dropout(0.5))

model.add(Dense(2, activation='softmax'))

```

I also get the deprecation warning for Merge. I'll try to get rid of it and see if it works.

**Comment by j-o-d-o** [comment]
Example on how to use Functional API and concatenate:

```python
    from keras.models import Model    
    from keras.layers import Conv2D, concatenate, Input

    submodels = []
    inputs = []
    for i, kernel_size in enumerate([3, 4, 5]):
        submodel = Sequential()
        in_layer = Input(shape=(32,32,3))
        inputs.append(in_layer)
        x = Conv2D(64, (3, 3), activation='relu')(in_layer)
        submodel = Model(inputs=in_layer, outputs=x)
        submodels.append(submodel.output)
        
    c = concatenate(submodels)
    model = Model(inputs=inputs, outputs=c)
```

**Comment by HelmiRifai** [comment]
You can create the model structure from code and then call model.load_weights(path_to_saved_model) and proceed to compile and continue training or use to evaluate. Tested and works with the deprecated Merge layers.
