### ISSUE TITLE
Define center loss which stores an un-trainable variable 

### ISSUE THREAD

**Issue by sun9700** [keras-team/keras#7076]
I am trying to implement center loss in keras
Center loss based on the paper "A Discriminative Feature Learning Approach for Deep Face Recognition"
 (http://ydwen.github.io/papers/WenECCV16.pdf)

It needs an un-trainable variable to store center which is  updated every batch like:

label = tf.reshape(label, [-1])
centers_batch = tf.gather(centers, label)
diff = (1 - alfa) * (centers_batch - features)
 centers = tf.scatter_sub(centers, label, diff)

a custom loss or regularizer function can not store centers.
I have tried custom layer like image_ocr example, but the un-trainable variable can not be updated manually every batch.

I also tried the callbacks to update the centers, but it can not get labels at batch begin/end

Is there any elegant implementation in keras?

**Comment by tslater** [comment]
@sun9700, have you found a solution for using center loss on Keras?

**Comment by ChristopherLu** [comment]
@sun9700 Any solutions for updating the center loss? Also meet with this problem.
