### ISSUE TITLE
ImportError: cannot import name ChainCRF 

### ISSUE THREAD

**Issue by jlfu** [keras-team/keras#7100]
**when i run the code:**
from keras.layers import ChainCRF

**it throw out the problem:**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name ChainCRF

I have tried the method ： https://github.com/fchollet/keras/issues/4090
but the problem is still there.  Does someone know how to fix it?

**Comment by jlfu** [comment]
the version of keras is 2.0.5

**Comment by rozenmoon** [comment]
same here :( 
Did you fix it?

**Comment by vino5211** [comment]
package keras.layers doesn't have chaincrf ?

**Comment by Dragon615** [comment]
Have you resolved this issue?
I have the same problem.

**Comment by N0vel** [comment]
pip3 uninstall keras
git clone https://github.com/phipleg/keras.git
cd keras
checkout crf
python setup.py build
python setup.py install

**Comment by Amling2017** [comment]
> **when i run the code:**
> from keras.layers import ChainCRF
> 
> **it throw out the problem:**
> Traceback (most recent call last):
> File "", line 1, in
> ImportError: cannot import name ChainCRF
> 
> I have tried the method ： #4090
> but the problem is still there. Does someone know how to fix it?

Have you resolved this issue?
I have the same problem.

the version of keras is 1.2.2
python2.7
