### ISSUE TITLE
keras lstm shape mismatch

### ISSUE THREAD

**Issue by nirsisense** [keras-team/keras#7124]
I am running keras over tensorflow, trying to implement a multi-dimensional LSTM network to predict a linear continuous target variable , a single value for each example(return_sequences = False).
My sequence length is 10 and number of features (dim) is 11.
This is what I run:
import pprint, pickle
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.layers import LSTM

# Input sequence
wholeSequence = [[0,0,0,0,0,0,0,0,0,2,1],
                 [0,0,0,0,0,0,0,0,2,1,0],
                 [0,0,0,0,0,0,0,2,1,0,0],
                 [0,0,0,0,0,0,2,1,0,0,0],
                 [0,0,0,0,0,2,1,0,0,0,0],
                 [0,0,0,0,2,1,0,0,0,0,0],
                 [0,0,0,2,1,0,0,0,0,0,0],
                 [0,0,2,1,0,0,0,0,0,0,0],
                 [0,2,1,0,0,0,0,0,0,0,0],
                 [2,1,0,0,0,0,0,0,0,0,0]]

# Preprocess Data:
wholeSequence = np.array(wholeSequence, dtype=float) # Convert to NP array.
data = wholeSequence
target = np.array([20])

# Reshape training data for Keras LSTM model
data = data.reshape(1, 10, 11)
target = target.reshape(1, 1, 1)

# Build Model
model = Sequential()
model.add(LSTM(11, input_shape=(10, 11), unroll=True, return_sequences=False))
model.add(Dense(11))
model.add(Activation('linear'))
model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(data, target, nb_epoch=1, batch_size=1, verbose=2)

and get the error ValueError: Error when checking target: expected activation_1 to have 2 dimensions, but got array with shape (1, 1, 1)
Not sure what should the activation layer should get (shape wise)
Any help appreciated
thanks

**Comment by stawo** [comment]
Hi @nirsisense ,
I think I came across your same problem just now.
Can you try to set `unroll=False` in your LSTM layer? Strangely enough, in my case, if I do that the network works.
It would be good if we can pinpoint the problem.

**Comment by phanphuong6** [comment]
I just started to install and try keras and tensorflow on MacBook Pro this week and i got the same problem. I still could not find out solution although i searched everywhere I could.
Any help would be very much appreciated.

**Comment by stawo** [comment]
Hi @phanphuong6,
what is the keras code you wrote?
Did you try to set `unroll=False` in your LSTM layer? Does it still give errors?
Can you post the keras code you used to define your network?
