### ISSUE TITLE
Should GpuArraySharedVariable be a valid keras tensor?

### ISSUE THREAD

**Issue by kgullikson88** [keras-team/keras#7139]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [*] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [ ] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [*] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

I ran into an issue today trying to pass a constant tensor to a keras layer, and got an error saying the constant isn't a symbolic tensor. The code snippet below gives the error on the latest keras and theano:

    from keras.layers import Input, Dense
    from keras import backend as K

    constant_input = Input(tensor=K.eye(10))
    output = Dense(10)(constant_input)

The error is:

    ValueError: Layer dense_1 was called with an input that isn't a symbolic tensor. Received type: <class 'theano.gpuarray.type.GpuArraySharedVariable'>. Full input: [/variable]. All inputs to the layer should be tensors.

I noticed that if I update `keras/backend/theano_backend.py`, in the `is_keras_tensor` function to have:

    if not isinstance(x, (T.TensorVariable,
                              theano.gpuarray.type.GpuArraySharedVariable,  # this is the new part
                              T.sharedvar.TensorSharedVariable)):
            raise ValueError('Unexpectedly found an instance of type `' + str(type(x)) + '`. '
                             'Expected a symbolic tensor instance.')
    return hasattr(x, '_keras_history')

I don't get that error. My question is, should the GpuArraySharedVariable be in that list, or is there a reason it isn't currently?

**Comment by dmaniry** [comment]
This breaks most uses of directly using the theano backend with current versions. It's an easy fix and I don't understand why this stays broken for months. could as well deprecate the theano backend.
