### ISSUE TITLE
 Exception: All input arrays (x) should have the same number of samples.

### ISSUE THREAD

**Issue by jlfu** [keras-team/keras#7156]
I am trying to train a muti-task network, and i use different dataset, so the number of samples  is different in different task. 
So i get the problem:  Exception: All input arrays (x) should have the same number of samples. When i run the  procedure. 
Any one can help me ?

**Comment by souvick91** [comment]
same question

**Comment by WJY0101** [comment]
I have the same question. Do you solve this problem?

**Comment by harshini-gadige** [comment]
Is this still an issue ?  Are you tensorflow backend ?
