### ISSUE TITLE
Can fit_generator() declare an epoch by the whole data in a generator (finite number of data) instead of steps_per_epoch?

### ISSUE THREAD

**Issue by Jie317** [keras-team/keras#7217]
`fit_generator()` does a good job to pre-load data batches, avoid the problem of memory insufficiency, and fit for continuously available data. I was wondering, when passing a generator with finite number of outputs, is it possible to add an option to `fit_generator()` so that it can behavior like the `fit()` function which declares all the data as an epoch instead of using `steps_per_epoch`? Because I have no idea if the whole data are seen total epochs or something like 5.6 epochs when I use `fit_generator()`, and if I use train_on_batch, I need a thread to pre-load the batches because the preprocessing costs time.

Thanks.

**Comment by fabriciorsf** [comment]
I think that yes!
See: https://github.com/fchollet/keras/issues/7462
