### ISSUE TITLE
Keras callback for Tensorboard seems to write duplicate parts of the graph

### ISSUE THREAD

**Issue by tranhungnghiep** [keras-team/keras#7294]
The graph visualization is confusing. There are too many nodes on the graph compared to the actual model, seems the nodes are repeatedly logged many times.

For example, see parts of the graph of a simple 0-hidden layer network:
![screen shot 2017-07-23 at 12 18 48](https://user-images.githubusercontent.com/4527536/28496230-4a663a7a-6fa1-11e7-939d-6dc14c83879a.png)

**Comment by tranhungnghiep** [comment]
Can anyone confirm the issue?

**Comment by xerxandi** [comment]
I got the same issue. 
Restarting the python kernel before the training solved it for me.

**Comment by tranhungnghiep** [comment]
@xerxandi So it seems a caching/free memory problem, that is when keras runs it is making duplicate graphs.

**Comment by AdrienDeliege** [comment]
Same problem here. I use Keras with Spyder and restarting the kernel does not seem to work. Did someone fix this?

**Comment by tranhungnghiep** [comment]
This problem happens because `keras` uses one default graph. So Variables/Operators get accumulated when we modify layers and rebuild the model.

The solution is using a new graph every time we rebuild the model, which could be set explicitly as:
```
from keras import backend as K  
graph = tf.Graph()  
K.set_session(tf.Session(graph=graph))  
with graph.as_default():  
    # Define layers and compile model.
```

Easier solution is to use the built-in clear_session() as:
```
from keras import backend as K  
K.clear_session()
# Define layers and compile model.
```
