### ISSUE TITLE
Attention Layer

### ISSUE THREAD

**Issue by yashk2810** [keras-team/keras#7341]
Having an Attention layer in the API like the Bidirectional Layer would be great. It is very difficult to create custom layers in Keras.

**Comment by hypathia** [comment]
This has been widely discussed in #4962, check it out.

**Comment by zafarali** [comment]
Implementing custom layers can be tricky. You can find an example implementation of the Attention Layer here: https://github.com/datalogue/keras-attention/blob/master/models/custom_recurrents.py

**Comment by andhus** [comment]
I've laid out a API Design suggestion for supporting recurrent attention in core keras: https://github.com/fchollet/keras/issues/7633
Please give feedback!

**Comment by hamelsmu** [comment]
Bumping this.  There are many threads discussing attention and many disparate code examples on how to implement it Keras.  However, I think the spirit of this issue is to discuss merging an attention layer into the Keras API as a first class citizen, rather than something you can add yourself.
