### ISSUE TITLE
LSTM layer fails when number of units = 1 (theano backend)

### ISSUE THREAD

**Issue by baogorek** [keras-team/keras#7402]
Keras 2.0.6 on a Theano 0.9.0 backend, Windows 10.

Trying a dirt simple LSTM with one unit. The following example works when you change LSTM(1) to LSTM(2), but otherwise provides a TypeError (TypeError: The broadcast pattern of the output of scan (TensorType(float32, 3D)) is inconsistent with the one provided in `output_info`). This must be related to https://github.com/Lasagne/Lasagne/issues/730 (from which I borrowed the title). Apparently that was going to lead to a change in Theano itself, but it [doesn't look like it ever happened](https://github.com/Theano/Theano/issues/5224). Perhaps it will be useful to have this as an open issue for keras, in case there's some way to code around it. The ability to use a single unit is nice for learning purposes.

```
from keras.layers import LSTM, Input, Dense
from keras.models import Model
import numpy as np

y = np.float32(np.reshape(np.random.normal(0, 1, 100), (100, )))
x = np.float32(np.reshape(np.array([0] * 100), (100, 1, 1)))

input_layer = Input(shape = (1, 1))
lstm_layer = LSTM(1)(input_layer)
dense_layer = Dense(1)(lstm_layer)
model = Model(input = input_layer, output = dense_layer)
model.compile(optimizer = 'sgd', loss = 'mean_squared_error')
model.fit(x, y, epochs = 1, batch_size = 1, verbose = 2)
```

**Comment by bhashithe** [comment]
Looks like theano still has this bug, were you able to get this resolved?
