### ISSUE TITLE
Can't use multiple instances of InceptionV3 in the same model

### ISSUE THREAD

**Issue by notnil** [keras-team/keras#7412]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

```python
from keras.applications import InceptionV3
from keras.applications import Xception
from keras.preprocessing import image
from keras.models import Model
from keras.layers import concatenate
from keras.layers import Dense, GlobalAveragePooling2D, Input, Embedding, LSTM
from keras import backend as K
from keras.applications.inception_v3 import preprocess_input
from keras.preprocessing.image import img_to_array
from keras.preprocessing.image import load_img

f1_base = InceptionV3(weights='imagenet', include_top=False)
for layer in f1_base.layers:
    layer.trainable = False    
f1_x = f1_base.output
f1_x = GlobalAveragePooling2D()(f1_x)
f1_x = Dense(1024, activation='relu')(f1_x)

f2_base = InceptionV3(weights='imagenet', include_top=False)
for layer in f2_base.layers:
    layer.trainable = False    
f2_x = f2_base.output
f2_x = GlobalAveragePooling2D()(f2_x)
f2_x = Dense(1024, activation='relu')(f2_x)

x = concatenate([f1_x, f2_x])
x = Dense(1024, activation='relu')(x)
x = Dense(1024, activation='relu')(x)
x = Dense(5, activation='sigmoid', name="main_output")(x)
model = Model(inputs=[f1_base.input, f2_base.input],outputs=[x])
model.compile(loss="categorical_crossentropy", optimizer="sgd")

print "DONE"
```

Produces the error
```
RuntimeError: The name "mixed0" is used 2 times in the model. All layer names should be unique.
```

I want to run the inception model on multiple frames of a video clip and create a model of the result.  I currently can't do that because of layer naming conflicts.

**Comment by fchollet** [comment]
I suggest you copy the InceptionV3 code in your own project and remove all instances of `name="..."` in the layers. Then unique names will be autogenerated.

**Comment by notnil** [comment]
@fchollet ok that makes sense.  Will the weights align correctly in that case?

**Comment by fchollet** [comment]
If you're using the same code and only changing layer names, weight loading
will still work. It's not name-based.

**Comment by jmhessel** [comment]
I've run into this as well a few times. maybe there should be a parameter in the keras.applications models to let you automatically append a string to the layer names? like

```
f1_base = InceptionV3(weights='imagenet', include_top=False, name='f1_base')
```

and then the name gets postpended to each layer name?

**Comment by micklexqg** [comment]
@notnil ,why the added fc is 1024(f2_x = Dense(1024, activation='relu')(f2_x))?

**Comment by ymodak** [comment]
Closing this issue due staleness. Feel free to reopen if the issue still persists and provide any additional information if any. Thanks!

**Comment by sasjafor** [comment]
Can confirm this is still happening with tensorflow 2.5.0

**Comment by 80Ultraman** [comment]
> Can confirm this is still happening with tensorflow 2.5.0

still happening with tensorflow==2.4.0

**Comment by bundasma** [comment]
Setting the model's _name attribute to something unique works for me, I hope it works for others too. 

`
def create_invc3(input_img, name):
    
    
    model = InceptionV3(include_top = False, input_shape = (256,256,3))
    model._name = name
    

    for layer in model.layers:
        
        layer.trainable = True
        #layer.name = layer.name + str("_" + str(name))
        
    model = model(input_img)
        
    return model
`

**Comment by andresgiovanni21** [comment]
Try this for each instance, works for me:

`f1_base = InceptionV3(weights='imagenet', include_top=False)
 for layer in f1_base.layers:
      layer._name = layer._name+"f1_base"`

**Comment by MyEyeAndEar** [comment]
@andresgiovanni21 Thank you!
