### ISSUE TITLE
LSTM for Sentence Classification with Multiple Channels 

### ISSUE THREAD

**Issue by ndrmahmoudi** [keras-team/keras#7414]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [*] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [*] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [*] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [*] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

Hi all,

I am trying trying to feed multi-channel word embedding layer (Glove + word2vec) into a LSTM for sentence classification. I know that I can implement 2D Convolution using conv2d. But, what about lstm? The error that I get is so logical: `ValueError: Input 0 is incompatible with layer lstm_1: expected min_ndim=3, found ndim=4`. The input for tensor for lstm should be 3D. How can I transform the 4D (batch_size, channel, maxlen, embedding_dim) to 3D tensor before calling LSTM layer? 

Thanks in advance for your responses.
Nader

This is the code if you want to take a look:
`main_input = Input(shape=(maxlen, ), dtype='int32', name='main_input')`
`embedding=[]`
`for item in embedding_layer:`
`         embedding.append(item(main_input))`
`embedding = Concatenate(axis=-1)(embedding)`
`embedding = Reshape((len(embedding_layer), maxlen, embedding_dim))(embedding)`
`embedding = Dropout(0.50)(embedding)`
`x = LSTM(100, activation='relu')(x)`
`x = Dropout(0.10)(x)`
`output = Dense(2, activation='softmax', name='output')(x)`
`model = Model(inputs=main_input, outputs=output)`
`model.compile(loss='binary_crossentropy',`
`         optimizer=Adadelta(lr=0.95, epsilon=1e-06),`
`         metrics=["accuracy"])`

**Comment by AritzBi** [comment]
Have you been able to implement this? I'm having a similar issue. In my casi, my input is the following: 4D (batch_size, time_steps, maxlen, embedding_dim)
