### ISSUE TITLE
The speed of using multi gpus with tf as backend.

### ISSUE THREAD

**Issue by freshmanfresh** [keras-team/keras#7449]
I use Tensorflow as the backend. And I use code here https://github.com/kuza55/keras-extras/blob/master/utils/multi_gpu.py to achieve multi-gpus training.  However, I find that the speed of using two gpus is almost same with using one gpu. Besides, I find when I use one gpu, the usage of gpu is almost 100%; but using two gpus, the usage og each gpu is about 40%-60%.  How can I solve the problem?

My environment: 
    CPU: 40x Intel E5-2630 v4
    Mem: 384GB
    GPU: 4x NVIDIA GTX 1080 Ti

**Comment by raghakot** [comment]
Maybe your batch size isn't large enough?

**Comment by freshmanfresh** [comment]
Using a larger batch means that the model need more epochs to achieve the best performance, that is, it would cost more time...

**Comment by gaotianxiang** [comment]
I have the same situation
