### ISSUE TITLE
Suggest model.save() add oss api

### ISSUE THREAD

**Issue by bts-webber** [keras-team/keras#7477]
HI,
   I use the Ali cloud machine learning platform to run Keras.In the GPU environment, I have to read or save data from the OSS.But Keras's model.save () doesn't support OSS, which means I can't save and load my model from OSS.So I suggest adding this utility function.

**Comment by FierceKing** [comment]
Me too, having the same concern.

**Comment by FierceKing** [comment]
hi @bts-webber , I found a very straight forward way and might be the easiest way to solve this problem.
just save the file using model.save('filename.h5'), then open and save it again using functions that support HDFS file system. for example.

```
model.save('model.h5')
with open('model.h5', 'rb') as f:
	f_content = f.read()
tf.gfile.FastGFile(HDFS_prefix + 'model1.h5', 'wb').write(f_content)
```
Already tested on Aliyun, it worked.
