### ISSUE TITLE
Conv1d with Error: expected dense to have shape (None, 800, 1) but got array with shape (200, 1, 1)

### ISSUE THREAD

**Issue by ksy1113** [keras-team/keras#7544]
I try to build a conv1d model, and my code is as follows:

#my train data is (X,Y) with the shape: X.shape=(200,2000,1), Y.shape=(200,1,1)
# create model
model=Sequential()
model.add(Conv1D(filters = 5, kernel_size=400, activation='relu', input_shape=X.shape[1:]))
model.add(Dropout(0.4))
model.add(Activation('sigmoid'))
model.add(MaxPooling1D())
model.add(Dense(1, activation='sigmoid'))
# Compile model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
# Fit the model
model.fit(X, Y, epochs=150, batch_size=10,  verbose=2)

But the errors are as follows:

ValueError                                Traceback (most recent call last)
<ipython-input-119-61165facbb5e> in <module>()
     33 model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
     34 # Fit the model
---> 35 model.fit(X, Y, epochs=150, batch_size=10,  verbose=2)
     36 # calculate predictions
     37 #predictions_NCS = model.predict(X2)

C:\Program Files\Anaconda3\lib\site-packages\keras\models.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, **kwargs)
    861                               class_weight=class_weight,
    862                               sample_weight=sample_weight,
--> 863                               initial_epoch=initial_epoch)
    864 
    865     def evaluate(self, x, y, batch_size=32, verbose=1,

C:\Program Files\Anaconda3\lib\site-packages\keras\engine\training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, **kwargs)
   1356             class_weight=class_weight,
   1357             check_batch_axis=False,
-> 1358             batch_size=batch_size)
   1359         # Prepare validation data.
   1360         if validation_data:

C:\Program Files\Anaconda3\lib\site-packages\keras\engine\training.py in _standardize_user_data(self, x, y, sample_weight, class_weight, check_batch_axis, batch_size)
   1236                                     output_shapes,
   1237                                     check_batch_axis=False,
-> 1238                                     exception_prefix='target')
   1239         sample_weights = _standardize_sample_weights(sample_weight,
   1240                                                      self._feed_output_names)

C:\Program Files\Anaconda3\lib\site-packages\keras\engine\training.py in _standardize_input_data(data, names, shapes, check_batch_axis, exception_prefix)
    138                             ' to have shape ' + str(shapes[i]) +
    139                             ' but got array with shape ' +
--> 140                             str(array.shape))
    141     return arrays
    142 

ValueError: Error when checking target: expected dense_63 to have shape (None, 800, 1) but got array with shape (200, 1, 1)

I couldn't understand the error and don't know how to solve this problem. Can someone help me? Thank you!

**Comment by MMatlacz** [comment]
Output of your network has output (None, 800, 1) but your target value Y has shape (None, 1, 1).
(None means that number of examples in batch is variable).
You can use GlobalMaxPool1D in place of MaxPooling1D,  it will change output shape to (None, 1).
Before that you should reshape your target value to (None, 1) ( Y.reshape(-1, 1) )

`model=Sequential()
model.add(Conv1D(filters = 5, kernel_size=400, activation='relu', input_shape=X.shape[1:]))
model.add(Dropout(0.4))
model.add(Activation('sigmoid'))
model.add(GlobalMaxPool1D())
model.add(Dense(1, activation='sigmoid'))`
