### ISSUE TITLE
Have anyone replicated Karpathy char learning in Keras?

### ISSUE THREAD

**Issue by maxima120** [keras-team/keras#7555]
I am referring to the Unreasonable Effectiveness blog post by Karpathy : http://karpathy.github.io/2015/05/21/rnn-effectiveness/

There is torch implementation of it which reproduces the results.

Is there an open source project on Keras with same results?

**Comment by kaushalshetty** [comment]
https://github.com/fchollet/keras/blob/master/examples/lstm_text_generation.py

http://machinelearningmastery.com/text-generation-lstm-recurrent-neural-networks-python-keras/

**Comment by TheErk** [comment]
I know this isssue is in stale mode but may be it will be useful to somebody to know that 
there is this one as well: https://github.com/ekzhang/char-rnn-keras
