### ISSUE TITLE
No attribute ifelse

### ISSUE THREAD

**Issue by KOLANICH** [keras-team/keras#7580]
The line importing that module was removed in 788c56b. Please add it back.

**Comment by mahnerak** [comment]
Actually, it was working only with theano backend and was accessible as `K.ifelse` by mistake.
You may consider using `K.switch(condition, then_expression, else_expression)`. This one will work with all backends.

**Comment by ericwu09** [comment]
Is there a fix for this out yet? theano.ifelse() is still throwing an error when adding Dropout layers, for instance.

**Comment by mahnerak** [comment]
@ericwu09 what version of Keras do you use?

**Comment by ericwu09** [comment]
I'm using version 2.0.6.

**Comment by mahnerak** [comment]
I've tried it on two workstations.
The same Keras and Theano versions.
The workstation with OSX raises `AttributeError: 'module' object has no attribute 'ifelse'`, while th e one with Ubuntu doesn't.
Do you use OSX?

**Comment by ericwu09** [comment]
I do use OSX, thanks for testing it.

**Comment by fayeshine** [comment]
I still have this issue on dev version.

**Comment by jonathanglima** [comment]
Same here. OSX with Theano==1.0.0 and Keras==2.1.1

**Comment by fchollet** [comment]
This has been fixed at master.

**Comment by edmondja** [comment]
Merci François ! ;)

**Comment by wt-huang** [comment]
Closing as this is resolved
