### ISSUE TITLE
Layer convolution1d_1 does not support masking

### ISSUE THREAD

**Issue by yftah89** [keras-team/keras#7588]
I want to stack a conv layer on top of lstm layer and I get the following error "Layer convolution1d_1 does not support masking", I'm not using the most updated version of keras(I know I know its in the posting rules) because I don't want to update all my code until I will be sure that by doing so I will solve my problem.
In https://github.com/fchollet/keras/issues/411 @fchollet  wrote that "This will be resolved by the upcoming TimeDistributed layer; closing." and I would like to know if this actually happend (this post is from 2015)

If it didn't, how can I overcome this error?

Thanks in advenced :)

**Comment by makkarpov** [comment]
Do not close it, it's important. +1 for masking a convolution.
