### ISSUE TITLE
fit_generator() unexpected behavior

### ISSUE THREAD

**Issue by cbakeicecream** [keras-team/keras#7622]
I have a highly dimensional dataset too large to fit into memory (a mix of one-hot encoded text data and other categorical data). I store it sparsely encoded on disk, then want to create a python generator and use fit_generator() for training. This way I can generate a few numpy arrays at a time that are small enough to fit in memory. However, I'm experiencing unexpected behavior.

I'm unable to get a very basic generator to work correctly. In this dummy example, I have data that is 20 rows, 5 cols. The generator returns 2 rows at a time, 10 times. The issue I have is, fit_generator() seems to request more rows than are available.  "Overflow" should never print. However, it does. It also overflows a different number of times each execution. 

```python
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Activation

def mygenerator():
    X = np.zeros((2,5),dtype=np.float32)
    y = np.zeros(2,dtype=np.float32)
    for i in range(10):
        print("Yielding: ",i)
        yield X,y


    i = 0
    while True:
        print("Overflow: ",i)
        yield X,y
        i += 1

model = Sequential([
                    Dense(1, input_dim=5),
                    Activation('sigmoid'),
        ])

model.compile(optimizer='sgd',
              loss='mse',
              metrics=['accuracy'])

model.fit_generator(mygenerator(), 10)
```

Testing using Python 2.7.13 and 3.5.3; Keras-2.0.6; Tensorflow 1.2.1 with and without GPU.

**Comment by StripedBanana** [comment]
IIRC `fit_generator` attempts to pre-load batches, by using all the available threads on your machine. Maybe it's just trying to pre-fetch batches outside of your range, thought that may not actually be an issue.
