### ISSUE TITLE
NN model implementation in examples/babi_memnn.py

### ISSUE THREAD

**Issue by KomonoLi** [keras-team/keras#7643]
I was looking at the example code in examples/babi_memnn.py and found that the model structure is a little different from the original paper, especially in the part of the memory representation output. 
In the paper (- Sainbayar Sukhbaatar, Arthur Szlam, Jason Weston, Rob Fergus, "End-To-End Memory Networks", http://arxiv.org/abs/1503.08895) it says,

***"the output, O ('response' in code), is a sum over the transformed inputs, c ('input_encoded_c' in code), weighted by the probability vector ('match' in code)"***

So i assume here should be an element-wise multiplication between 'match' and 'input_encoded_c'. However, in the code it is the sum of the two. 

`response = add([match, input_encoded_c])  # (samples, story_maxlen, query_maxlen)`
`response = Permute((2, 1))(response)  # (samples, query_maxlen, story_maxlen) `

I might be wrong but I would be appreciated if anyone could explain it a little bit here.

Thanks.

**Comment by buddhikaum** [comment]
I have the same concern. Appreciate if someone can clarify this. Equation (2) in the original paper is no implemented in the code.
