### ISSUE TITLE
Tensorflow fail

### ISSUE THREAD

**Issue by aminought** [keras-team/keras#7653]
Hello. I try to train simple CNN with tensorflow backend, but keras gives me something strange:
https://gist.github.com/aminought/9a78cf0573cd14ed43f97946753f1555
Theano and CNTK haven't any problems.

**Comment by ymodak** [comment]
Closing this issue due to staleness. Please test against the latest version of TF to see if the issue still persists. We will reopen the issue if required. Thanks!
