### ISSUE TITLE
Reconstruction probability with VAEs

### ISSUE THREAD

**Issue by skeydan** [keras-team/keras#7672]
Hi,

I was wondering if anyone has implemented (even if not officially) reconstruction probability for VAEs (for use in anomaly detection, as described in the paper 

http://dm.snu.ac.kr/static/docs/TR/SNUDM-TR-2015-03.pdf

)

I see there was an issue about adding a variational layer to Keras once (issue #1163), - instead the VAE example code was added. This is of course very helpful, but it would be great if anyone (@EderSantana, perhaps, who wrote the original VAE code if I'm correct :-) ?) had an implementation for reconstruction probability :-)

I see that deeplearning4j has a variational layer with reconstruction probabilities for different distributions, but having this in Keras too would be awesome :-)

best,
Sigrid

**Comment by maxi1192** [comment]
did anyone already find an implementation for reconstruction probability for VAE? How did you progress in finding an implemenation @skeydan ?

**Comment by skeydan** [comment]
Hi @maxi1192, AFAIK there's no implementation/custom code for Keras. The algorithm is well described in the paper, but an implementation would probably have to use an MCMC sampler like PyMC.
On the other hand, from my (very limited!) tests with DL4J I'm not sure whether reconstruction probability really works so much better than reconstruction error... but I really tested on a single dataset only and with default settings, so I can't really say.

**Comment by anphunl** [comment]
@skeydan : I am also finding the implementation for that paper in any programming language. Do you have any update with this? Thank you very much!
