### ISSUE TITLE
Variable-size input and output  to convolutional layer

### ISSUE THREAD

**Issue by shay86** [keras-team/keras#7700]
Hi,
I have sequence of different lengths: some of them is about 20 sequence length while some is about 2000 lengths the same is for its output"Lables" have the same input length. Depending on this github problem "https://github.com/fchollet/keras/issues/1920" I could solve entering problem, but now I am phasing the output problem now. I made my data have same sequence length for every batch, but when the model move to the next batch it gives me this error:
ValueError: Error when checking target: expected dense_1 to have shape (1, 20) but got array with shape (1, 21)
If i stop using Dense layer the GlobalMaxPooling layer gives same error 
do you have any suggestion for solving this problem??
thanks

**Comment by syeddanishkazmi** [comment]
@shay86 please can you share the code or some useful link so that i can implement  i am new to deep learning.
Thanks in advanced
