### ISSUE TITLE
Error when loading a model but not compiling and training?

### ISSUE THREAD

**Issue by ericwu09** [keras-team/keras#7708]
Hi,
I have a model that compiles, trains, and predicts perfectly fine, but when I save the model into a json file and then load it again, it returns an error:

`ValueError: 'Concatenate' layer should be called on a list of inputs`

It seems that the concatenate layer is receiving only one input after I debug a bit, but when I check the json file, the entry includes two as expected:
`{"class_name": "Concatenate", "config": {"trainable": true, "name": "concatenate_71", "axis": 1}, "inbound_nodes": [[["input_mask", 0, 0, {}], ["up_sampling2d_30", 0, 0, {}]]], "name": "concatenate_71"}`

Is there a reason why loading the model from a json file might be missing both inputs?

Thanks!

**Comment by nicolewhite** [comment]
What version of Keras are you on? Can you share the full piece of code to reproduce this error?
