### ISSUE TITLE
Embedding layer masking value (proposal)

### ISSUE THREAD

**Issue by nehz** [keras-team/keras#7710]
Currently in Embedding layer, the value for masking is 0 which is a bit clunky as you need to shift all your indexes up by 1, which can also cause error prone code.

Proposal to introduce field to `masking_value` which will let you specify what value is used for masking.
For example
`Embedding(..., masking_value=-1)` 
`Embedding(..., masking_value=np.nan)`
`Embedding(..., masking_value=0)  # for backwards compatibility`

**Comment by YashSinha1996** [comment]
This, please. If not this, then at least add support for the pre-existing masking layer.

**Comment by YashSinha1996** [comment]
@nehz Any updates on this?
