### ISSUE TITLE
ValueError: Cannot feed value of shape (8, 218) for Tensor u'input_1:0', which has shape '(100, 218)'

### ISSUE THREAD

**Issue by HelloTanyaTang** [keras-team/keras#7719]
My train data is 150808X218 and test data 41016X218.Both are formatted as numpy.ndarray
I am running this script https://github.com/fchollet/keras/blob/master/examples/variational_autoencoder.py. Notice that the train and test is 60000 and 10000 in this script. batch_size = 100

However, when running my own data, 
vae.fit(x_train,
        shuffle=True,
        epochs=epochs,
        batch_size=batch_size,
        validation_data=(x_test, x_test))

complains
ValueError: Cannot feed value of shape (8, 218) for Tensor u'input_1:0', which has shape '(100, 218)'
I think it is because 150808= 1508 * 100 + 8
When I changing batch size to a prime factor of 150808 such as 2693, it would complain the test data as 2693 is not a factor of 41016.

I tried batch size = 8 and it worked. Given my data size can vary for different datasets, any fix to this bug? Thanks!

**Comment by HelloTanyaTang** [comment]
any insights?

**Comment by dhaval067** [comment]
In my view, you have to feed data size in multiple of batch_size. As you have different datasets with different values you can make one function which returns a value which divides dataset evenly and supply that value as batch_size.
