### ISSUE TITLE
Layer shape for unknown input size

### ISSUE THREAD

**Issue by mhubrich** [keras-team/keras#7739]
At the moment, I try to implement an [UNet](https://arxiv.org/abs/1505.04597) model with a variable input size. Hence, the `input_shape` of my model is `(None, None, 3)` (for RGB images with TF backend). The UNet pools a specific layer, processes the downsampled result before it gets upsampled to meet the original size. Next, the original layer and the upsampled layer are concatenated. Here is a pseudocode summary of these operations:
```python
# shape of original layer v: (a, b)
w = MaxPooling2D()(v)  # shape of layer w: (a/2, b/2)
x = Conv2D(padding='same')(w)  # shape of layer x: (a/2, b/2)
y = UpSampling2D()(x)  # shape of layer y: ((a/2)*2, (b/2)*2)
z = Concatenate()([v, y])  # shape of layer z: ((a/2)*2, (b/2)*2)
```

While this works perfectly fine when both `(a, b)` are even, I run into problems for an odd shape of `v`. In such a case, `v` and `y` have dissimilar shapes and can't be concatenated. I solved this problem by cropping the layers in case of odd input sizes:
```python
w = MaxPooling2D(padding='same')(v)
x = Conv2D(padding='same')(w)
y = UpSampling2D()(x)
# For w.input_shape = (None, a, b), we crop y by
#    1 row if a is odd, and
#    1 column if b is odd
bottom_crop = 0 if w.input_shape[1] % 2 == 0 else 1
right_crop  = 0 if w.input_shape[2] % 2 == 0 else 1
y2 = Cropping2D(((0, bottom_crop), (0, right_crop)))(y)
z = Concatenate()([v, y2])
```

Now, this works perfectly fine for all input shapes. But here we come back to my original goal. I want to build this model for a variable (thus unknown) input size. The above code throws an error because `w.input_shape[1]` is `None` and thus `if w.input_shape[1] % 2 == 0` won't work.

Has anyone an idea how I could handle this problem? Is there anyway to determine the crop only during runtime?

**Comment by ilmonteux** [comment]
same issue here, were you able to figure it out?

**Comment by sukhoi** [comment]
I believe there is no possible solution for this due to the way Tensorflow/Keras builds the model. :(
