### ISSUE TITLE
When global session is set, always use it instead of default session.

### ISSUE THREAD

**Issue by Ajk4** [keras-team/keras#7740]
Keras will alyways try to use `tf.get_default_session` first even if I explicitly called `keras.set_session(...)`. Global session will be used only after default_session is not available.

Code -  https://github.com/fchollet/keras/blob/master/keras/backend/tensorflow_backend.py#L153

Problem with `tf.get_default_session` is, that it will have different graph for each thread. In my use case I need to modify some tensorflow variables from another thread - `K.set_value(...)` lazily creates TF Assign Op on first use. If I call it for the first time in another thread it will blow up because of graph mismatch.

You can test this behaviour with script https://gist.github.com/Ajk4/789437a8f74b7058ee2bbfafde23b27f

Currently I am working around it by explicitly saving tf.get_default_graph from main thread, and then using in another thread:

```
# main thread
graph = tf.get_default_graph()

# another thread
with graph.as_default():
    K.set_value(model.optimizer.lr, float(new_lr))
```
However, if Keras would have used global_session first whenever defined, I could just call `keras.set_session(tf.Session()) ` once and not worry about it anymore.

Is there any reason why we favor `tf.get_default_session` over explicitly set by user global session? If not, could I submit a Pull Request changing this behavior to use global_session first?

**Comment by csbrown** [comment]
What if the user would like to have more than one `Session`?  The tensorflow paradigm for that is to do `with sess.as_default():`, which only works if keras uses `tf.get_default_session`
