### ISSUE TITLE
[feature] Keras source codes to Tensorflow source codes?

### ISSUE THREAD

**Issue by dragon28** [keras-team/keras#7752]
Hello People,

I apologize if this topic had been mentioned before.

However, are there anyone know any method or python module which can help convert keras source codes into tensorflow source codes? or keras generate tensorflow source codes?

I try to use python "inspect" and "drill" modules, but they were not working as what I am expecting to be....

On the other hand, will there be a feature in future that allowing keras to perform such task?

Thanks

**Comment by Svito-zar** [comment]
I would like to see this feature too
