### ISSUE TITLE
LSTM for multiple time series

### ISSUE THREAD

**Issue by sai19** [keras-team/keras#7761]
Hi,
I have multiple time series(for e.g. web traffic on different wikipedia pages.). I have web traffic history of multiple pages, and I want to fit a LSTM model for these pages. Is there a way in keras to do this? The other issues that I have seen focus on multiple sequences of the same time series. 

Thanks,

**Comment by td2014** [comment]
@sai19 .  You might want to consider the Functional API approach:  https://keras.io/getting-started/functional-api-guide/
where you can create multiple input/output models of general structure.  I hope this helps.  Thanks.
