### ISSUE TITLE
Faster in W10 than Linux(Manjaro with Gnome3)

### ISSUE THREAD

**Issue by set92** [keras-team/keras#7762]
I start a few days ago seeing that the performance in Windows is was much better than Linux, but I always thought people use Linux because it is faster.

My test consisted of 3 tests, [I created a reddit post](https://www.reddit.com/r/MachineLearning/comments/6urcrl/is_windows_better_than_linux/) but no one answer it, and yesterday I formatted the linux partition and try again only installing Anaconda, tensorflow and keras, but is the same than before, in Linux with Keras take ~3000s each epoch and in Windows ~1300s and I don't know why.

Well I thought maybe it was a problem with the processor, because I'm using a CPU skylake and as far I know it has worse drivers in Linux than in Windows.

There are some benchmarks I can run to know better where is the error? In windows I only downloaded anaconda and run it with the default configuration, and in linux I created a virtualenv with mkl and switch to intel channels.

EDIT: I almost forget but the script I used to test the speed in Keras was https://github.com/eliorc/Medium/blob/master/MaLSTM.ipynb

**Comment by arogozhnikov** [comment]
@set92 
No idea about what causes this in particular, but factors that  may influence are MKL, used BLAS and AVX512 support by drivers
