### ISSUE TITLE
Is it possible to convert weights for Conv3D layers trained using Keras 1 to Keras 2 ?

### ISSUE THREAD

**Issue by rohit-gupta** [keras-team/keras#7768]
I am currently trying to use C3D model to extract features from video clips. For this I am trying to use @albertomontesg 's port of the C3D model from Caffee to Keras. However his port is for Keras v1. As a result when I try to use it on Keras 2, I get the following error:

`ValueError: Layer weight shape (3, 3, 3, 3, 64) not compatible with provided weight shape (64, 3, 3, 3, 3)`

Is there a simple way (a numpy function or something like that ?) to convert the layer weights from this format to the other ?

**Comment by coltleese17** [comment]
Try setting data_format=channels_last or data_format=channels_first

**Comment by rohit-gupta** [comment]
@coltleese17 Oh, I had done that before posting this. Actually the thing is Keras 2 internally stores the weight in channels_last format even for Theano. I managed to get this to work by transposing the weights Tensor manually. I am not entirely sure this is mathematically correct, but at least it works.
