### ISSUE TITLE
What is the generator method for probability prediction in Keras?

### ISSUE THREAD

**Issue by meysamgolm** [keras-team/keras#7772]
I want to predict probabilities for a bi-classification problem. Previously I was using model.predict_proba or predict_on_batch for this issue. Now I want to use generators in my scripts, but I can't find a generator such as evaluate_generator or predict_generator. Both of evaluate_generator or predict_generator won't generate probabilities. What is the generator method for probability prediction in Keras?

**Comment by coltleese17** [comment]
I'm a bit confused by your question. predict_generator [does](https://keras.io/models/sequential/#sequential-model-methods) generate probabilities, and it's inputs are batches from a data generator (i.e. ImageDataGenerator).
