### ISSUE TITLE
OCR example input shape parameters in wrong order?

### ISSUE THREAD

**Issue by mangerlahn** [keras-team/keras#7796]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

Hi!

I am using the OCR example by @mbhenry.

While converting the model into a CoreML model, I noticed that the input layer shape (width and height) are flipped during conversion. Apple uses the (C, H, W) format. Keras supports (C, H, W) and (H, W, ℂ).

The expletive however uses (W,H,C).

    if K.image_data_format() == 'channels_first':
            input_shape = (1, img_w, img_h)
        else:
            input_shape = (img_w, img_h, 1)`

According to the Keras documentation:

*For 2D data (e.g. image), "channels_last" assumes (rows, cols, channels) while "channels_first" assumes (channels, rows, cols).*

Is this an issue?

**Comment by stefanhuber** [comment]
I have absolutely the same question! This must be wrong, I haven't tried the example yet, however I wouldn't be able to explain how this could work, only if height and width of the images are of equal size...

The format for `channel_last` ist definitely: `(height, width, channels)`
