### ISSUE TITLE
There may be a bug in keras/keras/layers/merge.py

### ISSUE THREAD

**Issue by dream-chaser** [keras-team/keras#7797]
The Dot Layer's function `compute_output_shape` may have a bug.
The code is in line 461 in "keras/keras/layers/merge.py"
For example: 
`shape1 = [None, 68, 800, 50]`
`shape2 = [None, 68, 50, 3]`
`axes = [3,2]`
The shape of output should be [None, 68, 800, 3]
But this code will give the shape of [None, 68, 800, 68, 3] which maybe wrong.
Because of the above problem, `output.shape` and `output._keras_shape` are not different.

**Comment by facaiy** [comment]
Hi, I'm a newbie for keras. For M * N and N * P vectors, the dot is M * P vector. 

So, we can rewrite `shape1 = [None, 68, 800, 50]` and `shape2=[None, 50, 68, 3]`, it seems straight to get `[None, 68, 800, 68, 3]`. Please correct me if I'm wrong.

**Comment by dream-chaser** [comment]
@facaiy

**Comment by dream-chaser** [comment]
@facaiy

**Comment by dream-chaser** [comment]
@facaiy Your case is right. But it's not my case. Actually my case is `batch_dot`. The `None` is the batch size, and the `68` is the sub-batch size. So the result should be `68` matrices of size `800x3`.

**Comment by dream-chaser** [comment]
@fchollet Please consider my question. The `output.shape` is different from the result of function `compute_output_shape`. Thanks very much!
