### ISSUE TITLE
Dose keras support map (mean average precision) in compile setting?

### ISSUE THREAD

**Issue by micklexqg** [keras-team/keras#7798]
I know there are accuracy and loss metrics in compile. Dose keras support map (mean average precision) in compile setting? Or need we to compute it by ourselves in the end?

**Comment by micklexqg** [comment]
@ahrnbom ，thank you, I am not aware the matter in object detection. but as far as I know, it has only something to do with the final result(output) and the label in classification for computing mAP. Maybe I am
wrong..

**Comment by ahrnbom** [comment]
It might be that in image classification, it is possible to define mAP generally. I have worked very little with classification, so that is beyond my knowledge.

**Comment by pinakinathc** [comment]
any thoughts regarding this? this issue is not attended and personally i think that addition of mAP would be a good idea. any thoughts?
if no one is working on this i would like to submit a PR

**Comment by vin-liao** [comment]
@pinakinathc I would love to have a mAP metric, but I think that creating mAP is a little bit hard since there is no universal consensus on how to organize the ground truth and prediction. I might be wrong though.

**Comment by pinakinathc** [comment]
@vin-liao what if we do the following:
`y_pred = model.predict(x_test)`
now we have y_pred and y_train

now based on y_pred and y_train we find the top_1 precision and recall
similarly we find the top_2 precision and recall.......top_k precision recall

then we have something like this:
<pre>+---------------------------------------+
|   Rank   |   precision   |   recall   |
|---------------------------------------
|   Top_1   |   1.0        |     0.2    |
|   Top_2   |   0.9        |     0.3    |
|   Top_3   |   0.5        |     0.7    |
|.......                                | 
+--------------------------------------+
</pre>
from the above table we can calculate MAP.
The question of how to organize the ground truth and prediction, isn't the difficulty as no matter whatever a model does it must have some measure of *confidence* which can be either a custom function plus we can add some measure like "IOU" or "Edit Distance" like we have some predefined evaluation metric in keras but we can design our own evaluation metric too.
