### ISSUE TITLE
keras.predict function in a vectorized manner 

### ISSUE THREAD

**Issue by Walid-Ahmed** [keras-team/keras#7802]
Hello,
is there is a way to apply the keras.predict function in a vectorized manner so that it can handle more than one input(image) simultaneously?

Thanks

**Comment by grafael** [comment]
Maybe the **predict_generator**  can help you. More information about that you can find here: [model documentation](https://keras.io/models/model/)

**Comment by brittohalloran** [comment]
I believe `model.predict()` will take a numpy array of (for example) Shape (5, 150, 150, 3) -- 5 RGB images sized 150x150px.

What does `model.layers[0].shape` or `model.inputs` return?
