### ISSUE TITLE
Multi Head Attention Layer

### ISSUE THREAD

**Issue by grafael** [keras-team/keras#7803]
I think is a good idea start to think how to implement this sort of layer in Keras.
I know that is a really fresh algorithm, but I believe that's a new cutting edge tech in Deep Learning for the next years.

Paper: **Attention is all you need** (https://arxiv.org/abs/1706.03762)

Blog showing some results: [Google Research Blog](https://research.googleblog.com/2017/08/transformer-novel-neural-network.html?m=1)
Tensor2Tensor library [tensor2tensor](https://github.com/tensorflow/tensor2tensor)
Pytorch implementation [pytorch-t2t](https://github.com/jadore801120/attention-is-all-you-need-pytorch)

**Comment by andhus** [comment]
@grafael Please keep an eye on this https://github.com/fchollet/keras/pull/8296. I'll try to have a look at the specific case to see if it will be covered.

**Comment by grafael** [comment]
Thank @andhus I'll follow the updates

**Comment by utkarshshukla2912** [comment]
@soham97 it would be great if you could i was trying to implement it couldn't get the thing working

**Comment by lvapeab** [comment]
Hi, 

I implemented this some time ago in a [fork](https://github.com/MarcBS/keras/blob/3871c2f4538f7aa28e7a6ae70f4b9483e59b0efb/keras/layers/attention.py#L14). It is somewhat dirty and lacks test suites, but it works ([an NMT example of this](https://github.com/lvapeab/nmt-keras)). 

Cheers.

**Comment by miniwa** [comment]
Whats the status on this?
Seeing OpenAI's success with them made me want to try it.

**Comment by dynamicwebpaige** [comment]
Closing, as there is now a [Keras-friendly multi-head attention layer](https://www.tensorflow.org/addons/api_docs/python/tfa/layers/multihead_attention) in TensorFlow Addons. Thanks for the feature request!
