### ISSUE TITLE
Can I construct model in tensorflow and training in keras?

### ISSUE THREAD

**Issue by pswpswpsw** [keras-team/keras#7828]
I have read the following post "https://blog.keras.io/keras-as-a-simplified-interface-to-tensorflow-tutorial.html" but this only tells the following two things:

1. Calling keras layer module in tensorflow, **still training in tensorflow**
2. Using keras model in tensorflow, **still training in tensorflow (probably)**

Thus, I am exploring the possibility of constructing model in tensorflow, but training in keras.

**Comment by SCP-173-cool** [comment]
Can you run the code in "https://blog.keras.io/keras-as-a-simplified-interface-to-tensorflow-tutorial.html" ?
I met the error:
```
FailedPreconditionError: Attempting to use uninitialized value dense/kernel
	 [[Node: dense/kernel/read = Identity[T=DT_FLOAT, _class=["loc:@dense/kernel"], _device="/job:localhost/replica:0/task:0/cpu:0"](dense/kernel)]]
```
