### ISSUE TITLE
Extracting hidden layer values BEFORE the activation.

### ISSUE THREAD

**Issue by leonardltk** [keras-team/keras#7831]
Hi, I am using Functional API for a basic classifier
```
Inp = Input( shape=(1,969), name='Input' ) 
x = Dense(units=512, activation='sigmoid', name='Hidden')(x)
x = Dense(units=20, activation='softmax', name='Output')(x)
model = Model(Inp, x)
```

After training, i would like to extract the "Hidden" layer BEFORE applying the sigmoid activation.
How to i do that ?

I know for a fact that to extract the layer AFTER applying sigmoid activation will be as follows:
```
        Inp = model.input
        Hidp = model.get_layer('Hidden').output
        curr_layer_model = Model(Inp, Hidp)
        bottle_feature = curr_layer_model.predict(x)
```

But how do i extract BEFORE the sigmoid activation?
`# Note that this is after training, so i prefer not to redefine the architecture hidden layer to  activation='linear' then applying a Nonlinearity layer and then to retrain.`

Thanks

**Comment by jinmel** [comment]
This should get more attention 

https://github.com/keras-team/keras/blob/1df40521857697867922425db7a708a6c6c78289/keras/layers/core.py#L899-L903

we could store the value before activation somewhere
