### ISSUE TITLE
How to get access to the internal gates of an LSTM during the predict process

### ISSUE THREAD

**Issue by lenedor** [keras-team/keras#7834]
Hello everybody,

I know there are many posts very similar to this one. But I failed finding a suitable answer to my issue.

I would like to retrieve the inside gates of my LSTM layer during the predict process.
I do not want to have access to the activations or gates between the layers of a model, but I want to have access to the 4 gates (input, output, forget, cell) inside my LSTM at each steps of the predict method.
For example here, 

```
model = Sequential()
lstm = LSTM(128, input_shape=(40, 26))
model.add(lstm)
model.fit(x, y, ...)
model.predict(x_predict)
#in the last line x_predict.shape() = (1, 40, 26)
#then, i would like to have an access to the 40 * 4 gates used during the predict call
```

I tried some prints in the `step` function of the LSTM class, but I found out that it is called only once when I add the LSTM to the model, but never during the predict process.
I tried to unroll my LSTM in order to get access to the gates of the different cells, but I do not know where to find them.

Any ideas ? Many thanks

**Comment by Cerno-b** [comment]
Have you tried getting the LSTM input and computing the outputs yourself? 

You can get the trained LSTM weights using the get_weights() function on your LSTM layer. You will receive 2 matrices and a bias vector, Each matrix will consist of concatenated 4 LSTM weights matrices of your two internal states. You could do the multiplication and activation by hand.

This is not very convenient I guess, but it's the best I can come up with ;)

**Comment by philipperemy** [comment]
And if you want to get the activations after the RNN layers, consider using:

https://github.com/philipperemy/keras-visualize-activations
