### ISSUE TITLE
how can I get the learning rate value after every epoch?

### ISSUE THREAD

**Issue by sodaGH** [keras-team/keras#7874]
Does anyone know how to get the learning rate of every epoch when I am training my own model? The only way I can get it at present is by using "callbacks( reduce_lr)", but I find the lr history it returns are not correct if I set a large patience of it. I want to write my own callback to monitor the learning rate of every epoch.

**Comment by myutwo150** [comment]
```python
def on_epoch_end(self, epoch, logs=None):
    print(K.eval(self.model.optimizer.lr))
```

**Comment by sodaGH** [comment]
Thanks for your help! I tried it and it returns the learning rate of every epoch. However, I find the learning rate was constant. Take the Adadelta as an example:
when I set the parameters like this: 
`Adadelta = optimizers.Adadelta(lr=1.0, rho=0.95, epsilon=1e-08, decay=0.1)`
during the training process, the learning rate of every epoch is printed:
![adadelta_decay01](https://user-images.githubusercontent.com/18156614/30357297-85a6565e-9870-11e7-8867-13a3c1040161.png)
It seems that the learning rate is constant as 1.0
When I change the decay from 0.1 to 0.01 , the learning rate is recorded as:
![adadelta_decay001](https://user-images.githubusercontent.com/18156614/30357342-c0084848-9870-11e7-8d95-64e1d8231186.png)
It is also constant as 1.0
But since when the value of decay changed, all the value of val_loss, val_acc, train_loss and train_acc are different. I think the learning rate has changed with the variation of the value of decay, but the records of the learning rate are the same. So I wonder whether it record the updated learning rate of every epoch? Or it just record the initial learning rate?
Do thanks for your help again. Looking forward to your reply!

**Comment by myutwo150** [comment]
When using the `decay` option, the learning rate after decay is computed by:
```python
lr = self.lr
if self.initial_decay > 0:
    lr *= (1. / (1. + self.decay * K.cast(self.iterations, K.dtype(self.decay))))
``` 
As you can see, it does not **update** the learning rate variable `self.lr`. If you want the value after decay, you might have to compute it yourself (by replacing `self` with `self.model.optimizer`).

However, if you use `LearningRateScheduler` or `ReduceLROnPlateau`, the learning rate is directly updated by the callback, and the printed value will change after each epoch.

**Comment by sodaGH** [comment]
Could you please tell me more details about how to compute the updated value by myself? In which place should I do the  modification？ In the "optimizer.py" file? I added the code as followed:
![2017-09-14 09 16 53](https://user-images.githubusercontent.com/18156614/30407957-50088cba-992e-11e7-8356-86bdd3e1aee5.png)
But it doesn't work. 
Could you please tell me how to add the code so that the updated learning rate can be printed? Sorry to take your time, and do thanks for your help! Looking forward to your reply!

**Comment by myutwo150** [comment]
No need to modify Keras source code. Use it in a callback.
```python
class MyCallback(Callback):
    def on_epoch_end(self, epoch, logs=None):
        lr = self.model.optimizer.lr
        decay = self.model.optimizer.decay
        iterations = self.model.optimizer.iterations
        lr_with_decay = lr / (1. + decay * K.cast(iterations, K.dtype(decay)))
        print(K.eval(lr_with_decay))
```

**Comment by sodaGH** [comment]
Thanks a lot! 
And I still have a question about the optimizer. From the instruction of Keras, I find that it's recommended to leave the parameters of this optimizer at their default values.
![rms](https://user-images.githubusercontent.com/18156614/30463505-b6e0c40e-99fe-11e7-89b4-c352afeaac44.png)

 So it won't use decay. Does it mean the learning rate will be constant in the training process? If so, what are the differences between different optimizers when they have the same initial learning rate?

**Comment by myutwo150** [comment]
You can google it. E.g. [this article](http://ruder.io/optimizing-gradient-descent/) explains it well.

**Comment by HuangBo-Terraloupe** [comment]
@yuyang-huang 
Hello, one question, if I use ReduceLROnPlateau, how to I get the number of learning rate after every epoch?

I use 
adam = Adam(lr=1e-5, beta_1=0.9, beta_2=0.999, epsilon=1e-8, decay=0.0)
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.1, patience=10, verbose=0, mode='auto', cooldown=0, min_lr=0)

because I set decay = 0.0 in adam, so using your function, the learning rate does not change.
Is there a way to record the learning rate into tensorflow?

**Comment by AustinApple** [comment]
Hello, I use optimizer Adam and try to plot the learning rate in the tensorboard every epoch.
Following is the code I used in the callbacks
~~~~
class SubTensorBoard(TensorBoard):
    def __init__(self, *args, **kwargs):
        super(SubTensorBoard, self).__init__(*args, **kwargs)

    def lr_getter(self):
        # Get vals
        decay = self.model.optimizer.decay
        lr = self.model.optimizer.lr
        iters = self.model.optimizer.iterations # only this should not be const
        beta_1 = self.model.optimizer.beta_1
        beta_2 = self.model.optimizer.beta_2
        # calculate
        lr = lr * (1. / (1. + decay * K.cast(iters, K.dtype(decay))))
        t = K.cast(iters, K.floatx()) + 1
        lr_t = lr * (K.sqrt(1. - K.pow(beta_2, t)) / (1. - K.pow(beta_1, t)))
        return np.float32(K.eval(lr_t))

    def on_epoch_end(self, episode, logs = {}):
        logs.update({"lr": self.lr_getter()})
        super(SubTensorBoard, self).on_epoch_end(episode, logs)
~~~~
the optimizer setting is 
`optimizer = Adam(lr=0.000456, beta_1=0.99)`
and learning rate I plot in the following picture
![batch_2048_lr](https://user-images.githubusercontent.com/42490261/58689920-ee7f8100-83ba-11e9-93b0-340f0b664a3c.png)
However, according to the code, lr_t should be updated every epoch like this
`lr_t = lr * (K.sqrt(1. - K.pow(beta_2, t)) / (1. - K.pow(beta_1, t)))`
the picture would be like
<img width="1100" alt="螢幕快照 2019-05-31 下午3 53 21" src="https://user-images.githubusercontent.com/42490261/58690529-584c5a80-83bc-11e9-8d6f-6673ed3b69f2.png">
The value of learning rate is supposed to decay to the learning rate I set initially. But in my case, it start from a point and slowly increase to the learning rate I set.
It really comfuses me.
Does anyone can explain it? Thanks.

**Comment by ishedesy** [comment]
@yuyang-huang I know this is a very old thread, but could anybody please elaborate on this code, which was posted on 14 Sep 2017: 

`class MyCallback(Callback):
    def on_epoch_end(self, epoch, logs=None):
        lr = self.model.optimizer.lr
        decay = self.model.optimizer.decay
        iterations = self.model.optimizer.iterations
        lr_with_decay = lr / (1. + decay * K.cast(iterations, K.dtype(decay)))
        print(K.eval(lr_with_decay))`

When I type the code exactly like that in a cell, I get an error: 

`
NameError: name 'Callback' is not defined
`

I inserted this right before I compile my model. Thanks a lot!

**Comment by yuyang-huang** [comment]
@ishedesy The parent class `Callback` needs to be imported before creating `MyCallback`.

```python
from keras.callbacks import Callback
```

**Comment by thunguyenth** [comment]
@ishedesy as @yuyang-huang suggested you can implement the learning rate printing function as following:

```
import keras.backend as K
from keras.callbacks import ReduceLROnPlateau, Callback


class MyCallback(Callback):
    def on_epoch_end(self, epoch, logs=None):
        lr = self.model.optimizer.lr
        decay = self.model.optimizer.decay
        iterations = self.model.optimizer.iterations
        lr_with_decay = lr / (1. + decay * K.cast(iterations, K.dtype(decay)))
        print("Learning Rate = ", K.eval(lr_with_decay))


rlrop = ReduceLROnPlateau(monitor='loss', factor=0.1, patience=10)
print_rl = MyCallback() 

# After creating your model
# Add your callbacks at the model training part
model.fit(X_train, y_train, validation_data=(X_val, y_val), callbacks=[rlrop, my_callback])
```

**Comment by babuaditya97** [comment]
> @ishedesy as @yuyang-huang suggested you can implement the learning rate printing function as following:
> 
> ```
> import keras.backend as K
> from keras.callbacks import ReduceLROnPlateau, Callback
> 
> 
> class MyCallback(Callback):
>     def on_epoch_end(self, epoch, logs=None):
>         lr = self.model.optimizer.lr
>         decay = self.model.optimizer.decay
>         iterations = self.model.optimizer.iterations
>         lr_with_decay = lr / (1. + decay * K.cast(iterations, K.dtype(decay)))
>         print("Learning Rate = ", K.eval(lr_with_decay))
> 
> 
> rlrop = ReduceLROnPlateau(monitor='loss', factor=0.1, patience=10)
> print_rl = MyCallback() 
> 
> # After creating your model
> # Add your callbacks at the model training part
> model.fit(X_train, y_train, validation_data=(X_val, y_val), callbacks=[rlrop, my_callback])
> ```

thanks!
