### ISSUE TITLE
ImageDataGenerator and RAM consumption

### ISSUE THREAD

**Issue by Daemon2017** [keras-team/keras#7888]
Hello!

I'm trying to use ImageDataGenerator in two ways (flow_from_directory and flow), but in both ways I'm getting a MemoryError (even if batch size = 1). It's very strange, because without ImageDataGenerator my PC (52 Gb RAM, 8 i7 CPU) works fine with batch size = 10 (each picture is 352*480). Is there a problem in ImageDataGenerator, or I'm making something wrong?

flow_from_directory variant:
https://github.com/Daemon2017/Brumm-Net/blob/flow_from_directory/train.py

> Using TensorFlow backend.
> Number of X and Y in train is the same. Work continues!
> Number of X and Y in test is the same. Work continues!
> Start training? (y or n): y
> Building model...
> Model ready!
> Training...
> Found 367 images belonging to 1 classes.
> Found 367 images belonging to 1 classes.
> Traceback (most recent call last):
>   File "train.py", line 177, in <module>
>     train()
>   File "train.py", line 80, in train
>     train_generator = zip(train_image_generator, train_mask_generator)
>   File "/usr/local/lib/python2.7/dist-packages/keras/preprocessing/image.py", line 1026, in next
>     batch_x = np.zeros((current_batch_size,) + self.image_shape, dtype=K.floatx())
> MemoryError

flow variant:
https://github.com/Daemon2017/Brumm-Net/blob/flow/train.py

> Using TensorFlow backend.
> Number of X and Y in train is the same. Work continues!
> Number of X and Y in test is the same. Work continues!
> Start training? (y or n): y
> Building model...
> Model ready!
> Training...
> Generating training batch 0
> Preparing training file: #0, raw name: 0001TP_006690_raw.jpg, mask name: 0001TP_006690_mask.jpg
> Traceback (most recent call last):
>   File "train.py", line 227, in <module>
>     train()
>   File "train.py", line 172, in train
>     model.fit_generator(generator=batch_generator(),
>   File "train.py", line 107, in batch_generator
>     train_generator = zip(x_train, y_train)
>   File "/usr/local/lib/python2.7/dist-packages/keras/preprocessing/image.py", line 814, in next
>     x = self.image_data_generator.random_transform(x.astype(K.floatx()))
> MemoryError

No augmentation variant:
https://github.com/Daemon2017/Brumm-Net/blob/master/train.py

**Comment by Dref360** [comment]
Could you give your keras version and/or validate that it happens on master as well please?

**Comment by Daemon2017** [comment]
Hello, Dref360!
Yes, no problem - here is the resul of pip list (Keras and TF are up to date):

> backports.weakref (1.0rc1)
> bleach (1.5.0)
> boto (2.38.0)
> chardet (2.3.0)
> crcmod (1.7)
> cycler (0.10.0)
> decorator (4.1.2)
> Django (1.11.4)
> funcsigs (1.0.2)
> functools32 (3.2.3.post2)
> google-compute-engine (2.4.1)
> h5py (2.7.0)
> html5lib (0.9999999)
> image (1.5.11)
> **Keras (2.0.8)**
> Markdown (2.6.9)
> matplotlib (2.0.2)
> mock (2.0.0)
> networkx (1.11)
> numpy (1.13.1)
> olefile (0.44)
> opencv (1.0.1)
> opencv-python (3.2.0.8)
> pbr (3.1.1)
> Pillow (4.2.1)
> pip (9.0.1)
> protobuf (3.4.0)
> pyparsing (2.2.0)
> python-dateutil (2.6.1)
> pytz (2017.2)
> PyWavelets (0.5.2)
> PyYAML (3.12)
> requests (2.9.1)
> scikit-image (0.13.0)
> scipy (0.19.1)
> setuptools (36.4.0)
> six (1.10.0)
> subprocess32 (3.2.7)
> **tensorflow (1.3.0)**
> tensorflow-tensorboard (0.1.6)
> Theano (0.9.0)
> urllib3 (1.13.1)
> Werkzeug (0.12.2)
> wheel (0.30.0)

**Comment by Dref360** [comment]
The issue seems to be with the zip that you do in both cases `zip(x_train, y_train)`.
Iterator are not zippable. This is definitely a bug, I'll look into it.

**Comment by Daemon2017** [comment]
Thank you!
I don't know if something prevents iterator from being zippable, but, as I see in example, it's possible:
`train_generator = zip(image_generator, mask_generator)`
https://keras.io/preprocessing/image/

If in flow version I'm replacing
> return train_generator
with 
> yield train_generator
I'm getting error:
> Epoch 1/10
> Generating training batch 0
> Preparing training file: #0, raw name: 0001TP_006690_raw.jpg, mask name: 0001TP_006690_mask.jpg
> Exception in thread Thread-2:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
>     self.run()
>   File "/usr/lib/python2.7/threading.py", line 754, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.py", line 568, in data_generator_task
>     generator_output = next(self._generator)
>   File "train.py", line 107, in batch_generator
>     train_generator = zip(x_train, y_train)
>   File "/usr/local/lib/python2.7/dist-packages/keras/preprocessing/image.py", line 814, in next
>     x = self.image_data_generator.random_transform(x.astype(K.floatx()))
> MemoryError
> 
> Traceback (most recent call last):
>   File "train.py", line 227, in <module>
>     train()
>   File "train.py", line 179, in train
>     callbacks=[tbCallBack, WeightsSaver(model, 1)])
>   File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 87, in wrapper
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 2011, in fit_generator
>     generator_output = next(output_generator)
> StopIteration

Will the keras-transform work with Model class API?

**Comment by Dref360** [comment]
For the example, try with izip in python2? zip are not lazily evaluated in python2, but they are in python3

keras-transform is just some wrapper functions around a keras.utils.Sequence to do data augmentation. it would work just like a generator and everything is handled by keras.

**Comment by Daemon2017** [comment]
Yes, I'm using Python 2. zip in P3 works like izip in P2, isn't it?
I've added 

> from itertools import izip

and replaced _zip_ with _izip_.

The result for flow_from_directory variant is very strange:

> Using TensorFlow backend.
> Number of X and Y in train is the same. Work continues!
> Number of X and Y in test is the same. Work continues!
> Start training? (y or n): y
> Building model...
> Model ready!
> Training...
> Found 367 images belonging to 1 classes.
> Found 367 images belonging to 1 classes.
> Found 233 images belonging to 1 classes.
> Found 233 images belonging to 1 classes.
> Traceback (most recent call last):
>   File "train.py", line 179, in <module>
>     train()
>   File "train.py", line 131, in train
>     callbacks=[tbCallBack, WeightsSaver(model, 1)])
>   File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 87, in wrapper
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1936, in fit_generator
>     raise ValueError('When using a generator for validation data, '
> ValueError: When using a generator for validation data, you must specify a value for `validation_steps`.
https://github.com/Daemon2017/Brumm-Net/blob/flow_from_directory/train.py

The result for flow variant is strange too:

> Using TensorFlow backend.
> Number of X and Y in train is the same. Work continues!
> Number of X and Y in test is the same. Work continues!
> Start training? (y or n): y
> Building model...
> Model ready!
> Training...
> 2017-09-14 11:44:10.429839: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
> 2017-09-14 11:44:10.429902: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
> 2017-09-14 11:44:10.429909: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
> 2017-09-14 11:44:10.429914: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
> 2017-09-14 11:44:10.429920: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX512F instructions, but these are available on your machine and could speed up CPU computations.
> 2017-09-14 11:44:10.429925: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
> Epoch 1/10
> Generating training batch 0
> Preparing training file: #0, raw name: 0001TP_006690_raw.jpg, mask name: 0001TP_006690_mask.jpg
> Start is 0, end is 1
> Training batch 0 generated!
> Generating training batch 0
> Preparing training file: #0, raw name: 0001TP_006720_raw.jpg, mask name: 0001TP_006720_mask.jpg
> Start is 1, end is 2
> Training batch 0 generated!
> Traceback (most recent call last):
>   File "train.py", line 229, in <module>
>     train()
>   File "train.py", line 181, in train
>     callbacks=[tbCallBack, WeightsSaver(model, 1)])
>   File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 87, in wrapper
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 2017, in fit_generator
>     str(generator_output))
> ValueError: Output of generator should be a tuple `(x, y, sample_weight)` or `(x, y)`. Found: <itertools.izip object at 0x7fcfcba0d908>
https://github.com/Daemon2017/Brumm-Net/blob/flow/train.py

It looks like the easiest way to solve my problems is to rewrite code on Python 3, but I really do not want to do this...

Thank you! Now I'm understand - I was confused by word Sequence and it seemed to me that we are talking about Sequence/Model API's of Keras :)) Waiting for guide!
