### ISSUE TITLE
Pad_sequences throwing error with texts_to_sequence_generator

### ISSUE THREAD

**Issue by ishmeetSRaina** [keras-team/keras#7894]
After creating a text to sequence generator using texts_to_sequences_generator, when that generator object is passed as argument to the pad_sequences. It throws the following error.

ValueError                                Traceback (most recent call last)
<ipython-input-59-3f31b644b254> in <module>()
      1 seq2 = tokenizer.texts_to_sequences_generator(sent)
----> 2 data2 = pad_sequences(seq2,maxlen=maxSeqLength)

/opt/conda/lib/python3.5/site-packages/keras/preprocessing/sequence.py in pad_sequences(sequences, maxlen, dtype, padding, truncating, value)
     35     """
     36     if not hasattr(sequences, '__len__'):
---> 37         raise ValueError('`sequences` must be iterable.')
     38     lengths = []
     39     for x in sequences:

ValueError: `sequences` must be iterable.
```

**Comment by pbamotra** [comment]
I reduced the code to bare minimum for my use case. Assuming post padding and int32 data type.

```python
def pad_sequences(sequences, maxlen):
    for s in sequences:
        if len(s) == 0: yield np.zeros((1, maxlen), dtype='int32')
        s = np.array(s, dtype='int32')
        yield np.expand_dims(np.pad(s[:maxlen], (0, max(0, maxlen - len(s))), 'constant'), axis=0)
```

This doesn't return a matrix rather a generator! So, any of your following step need to take care of that. 
Bonus tip:

To clone generators -- 
Use tee
```python
from itertools import tee
```
