### ISSUE TITLE
About RMSprop Optimizer

### ISSUE THREAD

**Issue by soon-will** [keras-team/keras#7895]
RMSProp optimizer:
```#python
keras.optimizers.RMSprop(lr=0.001, rho=0.9, epsilon=1e-08, decay=0.0)
```
The epsilon is 1e-08 which is default in keras. But I also see someone saying 
> To get more stability of RMSprop, enlarging epsilon (1e-8 is keras default. change 1e-6.) is also a way.

Can anyone show if it's reasonable or not?

Thanks!

**Comment by philipperemy** [comment]
The best thing is for you to try and see if it makes sense.

Also consider using Adam instead! That's the best so far nowadays.
