### ISSUE TITLE
ImageDataGenerator file formats

### ISSUE THREAD

**Issue by Nqabz** [keras-team/keras#7904]
Not a question but perhaps a suggestion that the file formats that are read, when using the image data augmentation module for example a direct read of file on a local directory with ` datagen.flow_from_directory()`, are too specific and no useful message error is communicated back to the user if you happen to read files not included in the `white_list_formats = {'png', 'jpg', 'jpeg', 'bmp', 'ppm'}`. Is it possible to communicate a useful error message if the file format is not part of the list or perhps expose `white_list_formats ` to be set outside the script.

Took me me few hours to figure out why the module wouldn't read my images in `.tiff `format. As you can see from the list above.  'tiff' is not one of the default file formats. Adding it to the list on` line 969` in `keras/preprocessing/image.py` resolves the problem.

**Comment by russell0** [comment]
It also works to change it to '.tif' -- thankfully for me!

**Comment by mmortazavi** [comment]
I have both ".bmp" and ".tif" images, but adding either "tif" or ".tif" to white_list_formats in keras/preprocessing/image.py did not help. The datagen.flow_from_directory() still read only "bmp" images. Any update on this? After I edited that line in image.py, should I do anything? I loaded the keras library again, that is it!

**Comment by osamadel** [comment]
Well, thank you this actually worked for me. I had to add the 'tif' and 'tiff' file extensions to the white_list_formats in small letters and restart Spyder once, and run the code again to make it actually work.

**Comment by mmortazavi** [comment]
For some reasons simply adding them did not help! Finally I updated the keras from git branch, and ran the code again, worked just fine (that is why I deleted my original question because I thought it was perhaps quite obvious that I had to pull it from the main branch). Still wondering how it is possible for some like you simply adding "tif" to  white_list_formats make it work. 
Now keras preprocessing supports {'png', 'jpg', 'jpeg', 'bmp', 'ppm', 'tif', 'tiff'}, nice.

**Comment by benneely** [comment]
I'm interested in learning more about the purpose of `white_list_formats`.  `PILLOW` will handle tifs and many other image formats. Since PIL support for image formats seems to be the rate limiting step, why not just limit to PIL's support of image formats?

**Comment by sarahndudgeon** [comment]
for me it was line 1188

**Comment by maddy023** [comment]
how to edit white_list_formats for colab????

**Comment by bkonk** [comment]
Does this edit work for ".npy" numpy arrays?

**Comment by RichardKirk** [comment]
It would be good to have the ImageDataGenerator read .npy files as though they were another image format. I am working on noise removal, and it is hard to get a real example that might not be harmed by truncating to 8 bits. I have the images in a float format, but reading an preprocessing them in Python is slow (I imaging the standard ImageDataGenerators can pre-fetch  and things like that).

**Comment by Abdullahkhan5** [comment]
> keras/preprocessing/image.py

How can we change it in google colab?
