### ISSUE TITLE
Any chance we can get a more in depth example that shows distributed training with Keras?

### ISSUE THREAD

**Issue by mattdornfeld** [keras-team/keras#7923]
This [blog post](https://blog.keras.io/keras-as-a-simplified-interface-to-tensorflow-tutorial.html#using-keras-models-with-tensorflow) seems to have the beginnings of a distributed training example, but it would be really useful if we could get a full example that setups a parameter server and workers and trains it.

**Comment by harshini-gadige** [comment]
Below link helps you to use dist-keras framework for distributed training of Keras models. Please go through it if you haven't already. Thanks !

[Distributed training of Keras models.](https://docs.databricks.com/applications/deep-learning/distributed-deep-learning/dist-keras.html)
