### ISSUE TITLE
compatibility with dask

### ISSUE THREAD

**Issue by alvarouc** [keras-team/keras#7931]
Is there any efforts on making keras compatible with dask? Currently dask can not serialize any function that contains a keras model. Dask works fine with Tensorflow. 

This has forced me out of keras in favor of building tensorflow.

**Comment by redouanelg** [comment]
I hope we'll get an answer soon.. I'm running into the same problem.

**Comment by Dref360** [comment]
I guess this is related to this PR?
https://github.com/keras-team/keras/pull/10483
