### ISSUE TITLE
Is there a way to feed a BSON file directly into Keras?

### ISSUE THREAD

**Issue by rydevera3** [keras-team/keras#7934]
https://stackoverflow.com/questions/46311506/feed-bson-files-directly-into-keras-python

**Comment by harshini-gadige** [comment]
Hi

If you think this is a feature request/enhancement, please open the issue with clear information on what is expected or required.

To ask questions, please see the following resources :

https://keras.io/
https://keras.io/#support
https://gitter.im/Keras-io/Lobby

Thanks!
