### ISSUE TITLE
Write ModelCheckpoint callback to GCS (Google Cloud Storage)

### ISSUE THREAD

**Issue by sakinaljana** [keras-team/keras#7935]
Dear Keras Folks,

I'm understand that we cannot directly write checkpoint model to GCS because the inability of h5py library to support write to GCS. Is there any workaroud to mitigate this problem? i suggest to implement this:
- first, write the checkpoint model locally,
- then read the saved model using tensorflow.python.lib.io.file_io.FileIO from local path, then write again using same FileIO directly to GCS.

What do you think guys?

**Comment by fchollet** [comment]
Yes, we can add such a feature to model.save(), save_weights, load_model
and load_weights. Unfortunately there's nothing better than this workaround
at this point. Feel free to open a PR

**Comment by dyngts** [comment]
i see. thanks @fchollet for the confirmation.

**Comment by harshini-gadige** [comment]
@dyngts   Any PR is opened for this ?

**Comment by andhus** [comment]
@harshini-gadige I run into the same problem, please see: https://github.com/keras-team/keras/pull/11636
