### ISSUE TITLE
InvalidArgumentError (see above for traceback): Shape [-1,12] has negative dimensions (embeddings)

### ISSUE THREAD

**Issue by achernodub** [keras-team/keras#7948]
The problem occurs time to time during loading the model:

mdl = tf.contrib.keras.models.load_model(join(MODELS_PATH, 'sentiment', 'nn_model.h5'))

The most annoying thing is that sometimes it loads well, but from time to time it shows this error:

InvalidArgumentError (see above for traceback): Shape [-1,12] has negative dimensions
         [[Node: embedding_1_input = Placeholder[dtype=DT_INT32, shape=[?,12], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

**Comment by ymodak** [comment]
Please use the latest version of TensorFlow and test again. Feel free to reopen the issue if it still persists. Thanks!
