### ISSUE TITLE
Progress Bar Logging not displaying properly

### ISSUE THREAD

**Issue by jcomfort4** [keras-team/keras#7970]
I have confirmed that I am running the master branch of keras and tensorflow. I am running on tensorflow-gpu on Windows 10 with Python 3.6.1.

Most of the time running model.fit with verbose=1 properly displays the progress bar logging. However, randomly the progress bar logging goes awry and prints out every update (see image below) -- is there any known cause of this behavior? Typically if I close down my jupyter notebook and restart, the progress bar logging will work the next time (and then eventually cut out).  Ultimately, when this issue arises I can just switch to verbose=2, but then I am never quite sure how much longer an epoch will take so it is less than ideal. Does anybody have any idea why this might be happening? I run K.clear_session() to try to reset everything, but not sure why this progress bar would run into issues.

![image](https://user-images.githubusercontent.com/8152811/30774060-e724436e-a04a-11e7-9019-1436bbb462a5.png)

**Comment by jithurjacob** [comment]
I'm also facing a similar issue with Keras in Windows 10 and Chrome. In Edge the logging is working fine.

![image](https://user-images.githubusercontent.com/7101452/30926346-6f557a2a-a3d2-11e7-97cb-1d1d60ed39d8.png)

**Comment by jcomfort4** [comment]
Interesting - I had not considered that this was specific to Chrome. @jithurjacob does this always happen to you? Mine appears to sometimes work well if I restart a new kernel, but then eventually it runs into issues. Did you find any way around other than using edge?

**Comment by jithurjacob** [comment]
@jcomfort4  I tried restarting the kernel but still, the issue persists in chrome. In Edge, it is working fine.

**Comment by jcomfort4** [comment]
Mine is still having issues in both Edge & Chrome. Looking at your screenshot it looks like we are facing separate issues.

**Comment by ramadawn** [comment]
You can fix the problem simply by making your terminal window bigger

**Comment by jcomfort4** [comment]
@ramadawn This does work if I'm running from command line, but my issue is within jupyter notebook and I haven't found a great way to make the jupyter notebook output window larger.

**Comment by guifereis** [comment]
I also have this exact issue, when running keras on jupyter notebook on firefox 58 on Windows 10 x64, anaconda python 3.6. Have not been able to find a fix or workaround, except using tqdm-keras for methods with callbacks. Interestingly, I do not have this issue running the same versions on Ubuntu.

**Comment by ambigus9** [comment]
I have a similar issue, currently i'm training my model using the following model.fit

```
history = finetune_model.fit_generator(train_generator, epochs=NUM_EPOCHS, workers=1, 
                                         steps_per_epoch=num_train_images // batch_size,
                                validation_data=(x_val, y_val_))
```

And also i'm using the docker image from dockerhub _tensorflow/tensorflow:1.15.0-gpu-py3-jupyter_

Here is the current showing:

```
Epoch 38/40
61/62 [============================>.] - ETA: 0s - loss: 0.4109 - acc: 0.9536Epoch 1/40
420/62 [===========================================================================================================================================================================================================] - 2s 4ms/sample - loss: 0.6136 - acc: 0.7190
```

However in Colaboratory, the output is this:

```
Epoch 38/40
62/62 [==============================] - 13s 212ms/step - loss: 0.4069 - acc: 0.8997 - val_loss: 0.7886 - val_acc: 0.752
```

Any idea how to fix it?
