### ISSUE TITLE
error in keras.layers.merge.concatenate() 

### ISSUE THREAD

**Issue by NikhilShaw** [keras-team/keras#7976]
Code:

```
embedding_size = 300

model1 = Sequential([
       Dense(embedding_size, input_shape=(2048,), activation='relu'),
      RepeatVector(max_len)
      ])

model2 = Sequential([
          Embedding(vocab_size, embedding_size, input_length=max_len),
          LSTM(256, return_sequences=True),
           TimeDistributed(Dense(300))
                    ])

final_model = Sequential([
                        **concatenate([model1, model2], axis=1),**
                        Bidirectional(LSTM(256, return_sequences=False)),
                        Dense(vocab_size),
                        Activation('softmax')
                    ])


final_model.compile(loss='categorical_crossentropy', optimizer=RMSprop(), metrics=['accuracy'])

final_model.summary()
final_model.fit_generator(data_generator(batch_size=128), steps_per_epoch=50000,
                                              nb_epoch=1,
                                              verbose=0)
```

I am unable to debug the following error:

```
Traceback (most recent call last):
  File "/home/rick/.conda/envs/tensorflow-gpu/lib/python3.5/site-packages/keras/engine/topology.py", line 425, in assert_input_compatibility
    K.is_keras_tensor(x)
  File "/home/rick/.conda/envs/tensorflow-gpu/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 403, in is_keras_tensor
    raise ValueError('Unexpectedly found an instance of type `' + str(type(x)) + '`. '
ValueError: Unexpectedly found an instance of type `<class 'keras.models.Sequential'>`. Expected a symbolic tensor instance.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  **File "/home/rick/Downloads/Neural_talk/run.py", line 245, in <module>
    concatenate([image_model, caption_model], axis=1),**
  File "/home/rick/.conda/envs/tensorflow-gpu/lib/python3.5/site-packages/keras/layers/merge.py", line 600, in concatenate
    return Concatenate(axis=axis, **kwargs)(inputs)
  File "/home/rick/.conda/envs/tensorflow-gpu/lib/python3.5/site-packages/keras/engine/topology.py", line 558, in __call__
    self.assert_input_compatibility(inputs)
  File "/home/rick/.conda/envs/tensorflow-gpu/lib/python3.5/site-packages/keras/engine/topology.py", line 431, in assert_input_compatibility
    str(inputs) + '. All inputs to the layer '
ValueError: Layer concatenate_3 was called with an input that isn't a symbolic tensor. Received type: <class 'keras.models.Sequential'>. Full input: [<keras.models.Sequential object at 0x7f8ba413e9e8>, <keras.models.Sequential object at 0x7f8b9dcddf28>]. All inputs to the layer should be tensors.

Process finished with exit code 1
```

**Comment by sanaalshboul** [comment]
I have the same error!!! could you help me to fix the error?

**Comment by sanaalshboul** [comment]
I solved it in this way.
"""Block1"""
    inception_3a_1x1 = Conv2D(64,(1,1),padding='same',activation='relu',name='inception_3a/1x1',kernel_regularizer = regularizers.l2(0.0002))(pool2_3x3_s2)
    
    inception_3a_3x3_reduce = Conv2D(96,(1,1),padding='same',activation='relu',name='inception_3a/3x3_reduce',kernel_regularizer = regularizers.l2(0.0002))(pool2_3x3_s2)
    
    inception_3a_3x3 = Conv2D(128,(3,3),padding='same',activation='relu',name='inception_3a/3x3',kernel_regularizer = regularizers.l2(0.0002))(inception_3a_3x3_reduce)
    
    inception_3a_5x5_reduce = Conv2D(16,(1,1),padding='same',activation='relu',name='inception_3a/5x5_reduce',kernel_regularizer = regularizers.l2(0.0002))(pool2_3x3_s2)
    
    inception_3a_5x5 = Conv2D(32,(5,5),padding='same',activation='relu',name='inception_3a/5x5',kernel_regularizer = regularizers.l2(0.0002))(inception_3a_5x5_reduce)
    
    inception_3a_pool = MaxPooling2D(pool_size=(3,3),strides=(1,1),padding='same',name='inception_3a/pool')(pool2_3x3_s2)
    
    inception_3a_pool_proj = Conv2D(32,(1,1),padding='same',activation='relu',name='inception_3a/pool_proj',kernel_regularizer = regularizers.l2(0.0002))(inception_3a_pool)
    
    inception_3a_output = concatenate([inception_3a_1x1,inception_3a_3x3,inception_3a_5x5,inception_3a_pool_proj],axis=-1,name='inception_3a/output')
    """End of Block1"""

**Comment by sanaalshboul** [comment]
I solved it in this way.


"""Block1"""
    inception_3a_1x1 = Conv2D(64,(1,1),padding='same',activation='relu',name='inception_3a/1x1',kernel_regularizer = regularizers.l2(0.0002))(pool2_3x3_s2)
    
    inception_3a_3x3_reduce = Conv2D(96,(1,1),padding='same',activation='relu',name='inception_3a/3x3_reduce',kernel_regularizer = regularizers.l2(0.0002))(pool2_3x3_s2)
    
    inception_3a_3x3 = Conv2D(128,(3,3),padding='same',activation='relu',name='inception_3a/3x3',kernel_regularizer = regularizers.l2(0.0002))(inception_3a_3x3_reduce)
    
    inception_3a_5x5_reduce = Conv2D(16,(1,1),padding='same',activation='relu',name='inception_3a/5x5_reduce',kernel_regularizer = regularizers.l2(0.0002))(pool2_3x3_s2)
    
    inception_3a_5x5 = Conv2D(32,(5,5),padding='same',activation='relu',name='inception_3a/5x5',kernel_regularizer = regularizers.l2(0.0002))(inception_3a_5x5_reduce)
    
    inception_3a_pool = MaxPooling2D(pool_size=(3,3),strides=(1,1),padding='same',name='inception_3a/pool')(pool2_3x3_s2)
    
    inception_3a_pool_proj = Conv2D(32,(1,1),padding='same',activation='relu',name='inception_3a/pool_proj',kernel_regularizer = regularizers.l2(0.0002))(inception_3a_pool)
    
    inception_3a_output = concatenate([inception_3a_1x1,inception_3a_3x3,inception_3a_5x5,inception_3a_pool_proj],axis=-1,name='inception_3a/output')
    """End of Block1"""

**Comment by sanaalshboul** [comment]
I solved it in this way.


    inception_3a_1x1 = Conv2D(64,(1,1),padding='same',activation='relu',name='inception_3a/1x1',kernel_regularizer = regularizers.l2(0.0002))(pool2_3x3_s2)
    
    inception_3a_3x3_reduce = Conv2D(96,(1,1),padding='same',activation='relu',name='inception_3a/3x3_reduce',kernel_regularizer = regularizers.l2(0.0002))(pool2_3x3_s2)
    
    inception_3a_3x3 = Conv2D(128,(3,3),padding='same',activation='relu',name='inception_3a/3x3',kernel_regularizer = regularizers.l2(0.0002))(inception_3a_3x3_reduce)
    
    inception_3a_5x5_reduce = Conv2D(16,(1,1),padding='same',activation='relu',name='inception_3a/5x5_reduce',kernel_regularizer = regularizers.l2(0.0002))(pool2_3x3_s2)
    
    inception_3a_5x5 = Conv2D(32,(5,5),padding='same',activation='relu',name='inception_3a/5x5',kernel_regularizer = regularizers.l2(0.0002))(inception_3a_5x5_reduce)
    
    inception_3a_pool = MaxPooling2D(pool_size=(3,3),strides=(1,1),padding='same',name='inception_3a/pool')(pool2_3x3_s2)
    
    inception_3a_pool_proj = Conv2D(32,(1,1),padding='same',activation='relu',name='inception_3a/pool_proj',kernel_regularizer = regularizers.l2(0.0002))(inception_3a_pool)
    
    inception_3a_output = concatenate([inception_3a_1x1,inception_3a_3x3,inception_3a_5x5,inception_3a_pool_proj],axis=-1,name='inception_3a/output')
    """End of Block1"""

**Comment by sanaalshboul** [comment]
ZainAmin, you can check it from googleNet in Keras implementation, although it doesn't work for me.

https://gist.github.com/joelouismarino/a2ede9ab3928f999575423b9887abd14

**Comment by ZainAmin** [comment]
Thank you so much sanaalshboul !! It works in my case also
