### ISSUE TITLE
Error in getting representation of hidden layers InvalidArgumentError: Shape [-1,32,32,3] has negative dimensions

### ISSUE THREAD

**Issue by YisenWang** [keras-team/keras#7986]
I am running into a issue when get the representation of hidden layers on cifar10 dataset. 

representation code is here:
def get_deep_representations(model, X):
    get_encoding = K.function(
        [model.layers[0].get_input_at(0), K.learning_phase()],
        [model.layers[-4].get_output_at(0)]
    )
    output = get_encoding([X,0])
    return output

The error is 
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shape [-1,32,32,3] has negative dimensions
	 [[Node: conv2d_1_input = Placeholder[dtype=DT_FLOAT, shape=[?,32,32,3], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Does anyone know why? Thanks

**Comment by harshini-gadige** [comment]
Is this still an issue ?
