### ISSUE TITLE
Is it possible to use image_ocr example for multiple line image? 

### ISSUE THREAD

**Issue by mdshopon** [keras-team/keras#7987]
The image_ocr code that is available in the example section, is it possible to use that code for multiple lines? I mean is this possible to use the code for a single printed document?

**Comment by minyil** [comment]
I have the same question, did you use this example on multiple lines text? Thanks.

**Comment by codeheadshopon** [comment]
@minyil What i did is, used ocropy for segmentation of multiline. Then use the individual images for prediction of each line. See the documentation of OCROPY library in Python.
