### ISSUE TITLE
Create layer that concatenates in alternate fashion

### ISSUE THREAD

**Issue by msuardi** [keras-team/keras#7995]
Good Afternoon.
I'd like to create a Layer that concatenates two previous layers of shape (None,16) in alternate fashion.
For example, with simple arrays, if the inputs are:
a=[[1,2,3],[1,2,3],...]
b=[[4,5,6],[4,5,6],...]
I want this output:
c=[[1,4,2,5,3,6],[1,4,2,5,3,6],...]
How can I do it?
I can't loop on tensors because of unknown shape[0], zip function isn't supported for tensors (tensor object is not iterable).
Thank u all in advance

**Comment by harshini-gadige** [comment]
Hi

This issue isn't related to a bug/enhancement/feature-request or other accepted types of issue.

To ask questions, please see the following resources :

https://keras.io/
https://keras.io/#support
https://gitter.im/Keras-io/Lobby

Thanks!

If you think I made a mistake, please open another issue.
