### ISSUE TITLE
Is it possible to use Keras activation functoin in tensorflow?

### ISSUE THREAD

**Issue by pswpswpsw** [keras-team/keras#8000]
I don't want keras layers in tensorflow, just Keras activation function, to replace 

tf.nn.tanh,

for example.

**Comment by ymodak** [comment]
Hi!
This issue isn't related to a bug/enhancement/feature request or other accepted types of issue.

To ask questions, please see the following resources :

https://keras.io/
https://keras.io/#support
https://gitter.im/Keras-io/Lobby
Thanks!

If you think I made a mistake, please open another issue.
