### ISSUE TITLE
Documentation of kernel_size in Conv2D layer

### ISSUE THREAD

**Issue by Dobiasd** [keras-team/keras#8003]
The docstring of `Conv2D` [states](https://github.com/fchollet/keras/blob/7af02c324004e6a743120c244101f44ce661dcdf/keras/layers/convolutional.py#L361). `kernel_size: An integer or tuple/list of 2 integers, specifying the width and height of the 2D convolution window.`

But in reality is it `(height, width)` and not `(width, height)` if I understand correctly, since this is the same order of these two values as in shapes of images, which is
`For 2D data (e.g. image), "channels_last" assumes (rows, cols, channels) while "channels_first" assumes (channels, rows, cols).` with `rows` == `height` and `cols` == `width`.

Of course this is just a minor issue, but it took me quite some time to find out what I was doing wrong when I blindly trusted the docstring. ;)

**Comment by matthew-z** [comment]
+1.   got the same problem
