### ISSUE TITLE
Multi label classification with binary_crossentropy and class_weight - must contain all classes error

### ISSUE THREAD

**Issue by cinneesol** [keras-team/keras#8011]
Hello, 

I have run into an issue with class_weights and binary_crossentropy for multi label outputs.

In essence:
Output is an ndarray Y with Y.shape[1] the number of label outputs, e.g.:
[[0,0,1,0,1,1,0],
[0,0,1,0,1,1,1],
....
[0,0,0,0,1,0,0]]

I have defined the output layer as follows (method A):
```
...
out_dense=Dense(Y.shape[1], 
                 activation='sigmoid', name='OUTPUT_BINARY')(intermediate_dense)

```
and defined the model:

```
model = Model(inputs=[... some inputs...], outputs=out_dense)
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
```

weight dictionary defined as follows:
`W = {0.0: 0.54356142358280057, 1.0: 6.2390227278685089}
`
Now, when I fit:
`model.fit([...some inputs...], Y, batch_size=64, epochs=1, validation_split=0.25, class_weight={'OUTPUT_BINARY':W}, sample_weight=None)
`
I get the error:

```
/usr/local/lib/python3.5/dist-packages/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, **kwargs)
   1521             check_batch_axis=False,
   1522             batch_size=batch_size)
-> 1523         # Prepare validation data.
   1524         do_validation = False
   1525         if validation_data:

/usr/local/lib/python3.5/dist-packages/keras/engine/training.py in _standardize_user_data(self, x, y, sample_weight, class_weight, check_batch_axis, batch_size)
   1388                           for (ref, sw, cw, mode)
   1389                           in zip(y, sample_weights, class_weights, self._feed_sample_weight_modes)]
-> 1390         _check_array_lengths(x, y, sample_weights)
   1391         _check_loss_and_target_compatibility(y,
   1392                                              self._feed_loss_fns,

/usr/local/lib/python3.5/dist-packages/keras/engine/training.py in <listcomp>(.0)
   1387         sample_weights = [_standardize_weights(ref, sw, cw, mode)
   1388                           for (ref, sw, cw, mode)
-> 1389                           in zip(y, sample_weights, class_weights, self._feed_sample_weight_modes)]
   1390         _check_array_lengths(x, y, sample_weights)
   1391         _check_loss_and_target_compatibility(y,

/usr/local/lib/python3.5/dist-packages/keras/engine/training.py in _standardize_weights(y, sample_weight, class_weight, sample_weight_mode)
    556                              '`class_weight`.'
    557                              % (existing_classes - existing_class_weight))
--> 558         return weights
    559     else:
    560         if sample_weight_mode is None:

ValueError: `class_weight` must contain all classes in the data. The classes {2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 17, 19, 20, 21, 28, 29, 31, 34, 36, 37, 38, 41, 43, 44, 45, 47} exist in the data but not in `class_weight`.

```
I have traced it to :

```
def _standardize_weights(y, sample_weight=None, class_weight=None,
                         sample_weight_mode=None):
...
        if y.shape[1] > 1:
            y_classes = y.argmax(axis=1)
        elif y.shape[1] == 1:
            y_classes = np.reshape(y, y.shape[0])
        else:
            y_classes = y

```

in training.py.

It seems that here keras sees the output as a softmax type one hot encoded and returns the index of the maximum for each row.

The only way I saw to fix this was to create multiple single outputs by using a for loop (method B):

```
outputs=[]
l_weights=[]
for i in range(y_in_service_indicator.shape[1]):
    out_dense=Dense(1, activation='sigmoid', name='O_'+str(1+i))(intermediate_dense)
    outputs.append(out_dense)
    l_weights.append(1.0)

model = Model([...some inputs...], outputs=outputs)
model.compile(loss='binary_crossentropy', loss_weights=l_weights,
              optimizer='adam', metrics=['accuracy'])

```
(I appreciate may not need the loss weights)
and define the outputs as :

```
y_s_binary = []
for i in list(range(Y.shape[1])):
    y_s_binary.append(y_in_service_indicator[:,i])

```
and now fit:

```
model.fit(X_intervals, y_s_binary, batch_size=64, epochs=1, validation_split=0.25,
          class_weight={'OUTPUT_BINARY':W}, sample_weight=None)

```
This works, but it feels to me like I am missing somehting - would appreciate input on how to make Keras work with single defined Y ndarray and model output as  in method A.

**Comment by TobiasNorlund** [comment]
+1 for fixing this! I'm having the same problem!

**Comment by caugusta** [comment]
Could you please explain what is stored in `y_in_service_indicator`?

**Comment by maxim5** [comment]
Here's a workaround (see a [discussion on StackOverflow](https://stackoverflow.com/q/48254832/712995)):
add two artificial classes in `out_dense` in positions `0` and `1` and make

```python
out_dense[:,0] = 0
out_dense[:,1] = 1
```

All actual classes start from index `2` onward. This will force keras think that there are 2 classes.

**Comment by Runze** [comment]
@maxim5 would that change the optimization process though? The model may quickly learn to always predict 0 for the first dummy class and 1 for the second. Together, they drag the aggregate loss down too quickly and I wonder how that would impact the optimization.

**Comment by maxim5** [comment]
@Runze Since the total loss is the sum of the constituent losses, the value will be affected initially until the model learns the constants for the first two labels, after which the effect will diminish and the error signal will backpropagate just as before.

**Comment by sharifza** [comment]
@maxim5  Thanks for the workaround. However, adding dummy classes requires changing codes in evaluations and so on, maybe we should think of fixing the problem within keras ?

**Comment by maxim5** [comment]
@sharifza Of course. That's why this bug is open.

**Comment by alanlisten** [comment]
+1 for fixing this! I'm also have the same problem!

**Comment by goyidao** [comment]
hi, is there any corresponding new api in keras? i get a similar error when setting the class weight with keras version 2.2.0. And my Y is something like:
`[[1,0,0,1],
[1,1,0,0]
[1,0,1,0]]`
so for this multi-class and multi-label problem i set
`class_weight={0.0:0.6,1.0:0.4}` in the model.fit() function,and i get an error message says:
`ValueError: `class_weight` must contain all classes in the data. The classes {2, 3} exist in the data but not in `class_weight`.`

**Comment by goyidao** [comment]
i wonder if there is a certain api like `tf.nn.weighted_cross_entropy_with_logits` in tensorflow ?

**Comment by dominik335** [comment]
I confirm, that I also have the same error on the newest version installed from github  @alanlisten

**Comment by alanlisten** [comment]
@goyidao well, you must give weight to four classes, and you only give weights to the first two categories.
e.g. class_weight={0: 0.1, 1: 0.22, 2: 0.45, 4: 0.35}

**Comment by alanlisten** [comment]
@dominik335 I updated the answer, you can look at it.

**Comment by aradhagan** [comment]
I am also having the error is there a solution or workaround. Below is the error I get when implementing CNN and multilabel multiclass problem.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-40-85541802e5df> in <module>
     32                     validation_data=validation_generator,
     33                     validation_steps=STEP_SIZE_VALID,class_weight=class_wts,
---> 34                     epochs=5
     35 )

/opt/conda/lib/python3.6/site-packages/keras/legacy/interfaces.py in wrapper(*args, **kwargs)
     89                 warnings.warn('Update your `' + object_name + '` call to the ' +
     90                               'Keras 2 API: ' + signature, stacklevel=2)
---> 91             return func(*args, **kwargs)
     92         wrapper._original_function = func
     93         return wrapper

/opt/conda/lib/python3.6/site-packages/keras/engine/training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   1416             use_multiprocessing=use_multiprocessing,
   1417             shuffle=shuffle,
-> 1418             initial_epoch=initial_epoch)
   1419 
   1420     @interfaces.legacy_generator_methods_support

/opt/conda/lib/python3.6/site-packages/keras/engine/training_generator.py in fit_generator(model, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
    215                 outs = model.train_on_batch(x, y,
    216                                             sample_weight=sample_weight,
--> 217                                             class_weight=class_weight)
    218 
    219                 outs = to_list(outs)

/opt/conda/lib/python3.6/site-packages/keras/engine/training.py in train_on_batch(self, x, y, sample_weight, class_weight)
   1209             x, y,
   1210             sample_weight=sample_weight,
-> 1211             class_weight=class_weight)
   1212         if self._uses_dynamic_learning_phase():
   1213             ins = x + y + sample_weights + [1.]

/opt/conda/lib/python3.6/site-packages/keras/engine/training.py in _standardize_user_data(self, x, y, sample_weight, class_weight, check_array_lengths, batch_size)
    799                 for (ref, sw, cw, mode) in
    800                 zip(y, sample_weights, class_weights,
--> 801                     feed_sample_weight_modes)
    802             ]
    803             # Check that all arrays have the same length.

/opt/conda/lib/python3.6/site-packages/keras/engine/training.py in <listcomp>(.0)
    797             sample_weights = [
    798                 standardize_weights(ref, sw, cw, mode)
--> 799                 for (ref, sw, cw, mode) in
    800                 zip(y, sample_weights, class_weights,
    801                     feed_sample_weight_modes)

/opt/conda/lib/python3.6/site-packages/keras/engine/training_utils.py in standardize_weights(y, sample_weight, class_weight, sample_weight_mode)
    518                              ' The classes %s exist in the data but not in '
    519                              '`class_weight`.'
--> 520                              % (existing_classes - existing_class_weight))
    521         return weights
    522     else:

ValueError: `class_weight` must contain all classes in the data. The classes {0, 1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 14} exist in the data but not in `class_weight`.

**Comment by talhaanwarch** [comment]
> puted the weights using sklearn's compute_class

have you find the solution?

**Comment by ALIANS-PRODUCTIONS** [comment]
Multilabel : Binary Classification : Class weights for biased data.
I have similar issue as mentioned in the thread. Wondered if a solution now exists ?
My Y is of of shape :
[[0,0,0,1],
 [0,1,0,0],
 [1,1,1,0]
....
 [0,1,1,1]]

 So its multilabel : binary classification with biased Data.

>if i restrict the problem to just ONE label, binary classfication i.e. y = [ [0],[1],[0]...]
i can set the class_weight= {0: weight_neg, 1: weight_pos} in tf.model.fit()
And the model runs/trains well.
However when i extend it to multiple labels it wont accept a dict of dicts or any variant i have tried.
