### ISSUE TITLE
[Requesting a Feature] Please add more pretrained networks in Applications

### ISSUE THREAD

**Issue by ZFTurbo** [keras-team/keras#8018]
Currently I heavily use different networks with pretrained weights obtained in different locations. Some of them like DenseNet, for example, overperform existing ResNet50 or Inception on some tasks. Keras changes very fast and some of these networks stop working correctly. It's the reason why I'm still mostly use Keras 1.2. I propose to add the following CNNs directly in Keras applications with pre-trained weights:

DenseNet (121, 161, 169): https://github.com/flyyufelix/DenseNet-Keras
ResNet-101: https://gist.github.com/flyyufelix/65018873f8cb2bbe95f429c474aa1294
ResNet-152: https://gist.github.com/flyyufelix/7e2eafb149f72f4d38dd661882c554a6
SqueezeNet: https://github.com/rcmalli/keras-squeezenet
Inception v4: https://github.com/titu1994/Inception-v4/releases

Full list of nets (suitable to Keras 2.0.5 + Tensorflow and Theano):
https://github.com/flyyufelix/cnn_finetune

**Comment by vfdev-5** [comment]
Probably, you've seen this, but anyway you can use another implementation of DenseNet (121, 161, 169) with pretrained weights from [keras-contrib](https://github.com/farizrahman4u/keras-contrib/blob/master/keras_contrib/applications/densenet.py)

**Comment by ZFTurbo** [comment]
**vfdev-5** , didn't see it actually, will try. Thank you.
