### ISSUE TITLE
Loading a pre trained keras model and running in pyspark

### ISSUE THREAD

**Issue by raviranjan-innoplexus** [keras-team/keras#8019]
Hi,
I am facing an issue with an already trained keras model. When I tried to run the model on files that I read in python, the model gave me results as expected. But, when those files were read as an rdd, it threw the following error:
AttributeError("'Model' object has no attribute '_feed_input_names'",)

Is there any different method of running keras models on spark?

**Comment by harshini-gadige** [comment]
@raviranjan-innoplexus  - Is this still an issue ? Are you using tensorflow back-end for this ?
