### ISSUE TITLE
What are the differences between "native keras" and tensorflow keras"

### ISSUE THREAD

**Issue by ophiry** [keras-team/keras#8034]
I had to switch to native keras from tensorflow keras because of a bug fix that isn't yet included in tensorflow.

I experienced some issues when running the same code using the two different versions

The main issue was solved by suplying outputshape to a lambda layer calling a tensorflow function (einsum)

while this issue was solved, I want to know if there are other incompatibilities that may casue issues (errors, or different behaviour)

ther versions I used were tensorflow 1.3.0 and keras 2.0.8

**Comment by harshini-gadige** [comment]
Hi

This issue isn't related to a bug/enhancement/feature-request or other accepted types of issue.

To ask questions, please see the following resources :

https://keras.io/
https://keras.io/#support
https://gitter.im/Keras-io/Lobby

Thanks!

If you think I made a mistake, please open another issue.
