### ISSUE TITLE
Wrong output while predicting sample in image_ocr example

### ISSUE THREAD

**Issue by mdshopon** [keras-team/keras#8036]
In Keras image_ocr example I trained the model for 20 Epochs and the model was almost predicting most of the images perfectly. Then I stopped the training and load the saved weights and used a test function for predicting the validated samples during training. The code that I wrote for prediction is
`   last_layer = Model(inputs=input_data, outputs=model.get_layer('softmax').output)

    last_layer.compile(loss='categorical_crossentropy',
                        optimizer = sgd,
                        metrics = ['accuracy'])

    Output = last_layer.predict(data)`

But while validating the data during training the model predicted the result perfectly. But when I try to load the weights and then try to predict the result the output is coming wrong. Is there anything wrong?

**Comment by pigubaoza** [comment]
do you get this?
ValueError: Error when checking model : the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 4 array(s), but instead got the following list of 1 arrays
