### ISSUE TITLE
What is the purpose of Input class in keras.layers?

### ISSUE THREAD

**Issue by leoliao0129** [keras-team/keras#8043]
I'm new to keras and just follow the tutorial to learn it.
This is the post that I'm learning right now, Using pre-trained word embeddings in a Keras model, [https://blog.keras.io/using-pre-trained-word-embeddings-in-a-keras-model.html](url)
In the phase of building model, a piece of code is written like the following,
`from keras.layers import Input`
`sequence_input = Input(shape=(MAX_SEQUENCE_LENGTH,), dtype='int32')`
But I can't find Input class in keras documentation. So what is the purpose of Input class, and in which module can I find it?

Thank you.

**Comment by harshini-gadige** [comment]
Hi

This issue isn't related to a bug/enhancement/feature-request or other accepted types of issue.

To ask questions, please see the following resources :

https://keras.io/
https://keras.io/#support
https://gitter.im/Keras-io/Lobby

Thanks!

If you think I made a mistake, please open another issue.
