### ISSUE TITLE
Is possible to implement a NeuralNetwork(LSTM) built in Python on Arduino hardware?

### ISSUE THREAD

**Issue by ales222** [keras-team/keras#8046]
Hello!
I'm new keras user.
I tried implementing a LSTM network for Time Series Prediction.
Once network is built , I saved the network with the command :   "model.save('my_model.h5')".

Is now possible to implement this network in a Arduino Hardware (by Serial Comunication)???
In this way I want that the Arduino will be able to make prediction ( to obtain the same results that I obtain in Python environment with the command "model.predict")

Thanks!!

**Comment by mj0lken** [comment]
A very good question! I'm following this thread.

**Comment by bartkowiaktomasz** [comment]
I've built a [tool](https://github.com/bartkowiaktomasz/Headerify-LSTM-cpp) for converting LSTM models from `.h5` to headerfiles `.h`, so you can perform prediction in C++ without reading any file, just by including a headerfile with model parameters. If your Arduino supports reading from files you can use [kerasify](https://github.com/moof2k/kerasify).

**Comment by yang12313** [comment]
> I've built a [tool](https://github.com/bartkowiaktomasz/Headerify-LSTM-cpp) for converting LSTM models from `.h5` to headerfiles `.h`, so you can perform prediction in C++ without reading any file, just by including a headerfile with model parameters. If your Arduino supports reading from files you can use [kerasify](https://github.com/moof2k/kerasify).

Have you tested out what the maximum lstm cells can be used in the neural network as trained model to deployed into Arduino?

**Comment by 1saifj** [comment]
A great question, really wanna find more info!
