### ISSUE TITLE
Keras documentation misses the description of the Input layer

### ISSUE THREAD

**Issue by aburkov** [keras-team/keras#8051]
Hello,

Keras documentation misses the description of the Input layer, while this layer is often used in examples. Would be nice to describe its purpose and the parameters it takes as input, like in:

main_input = Input(shape=(100,), dtype='int32', name='main_input')

**Comment by harshini-gadige** [comment]
Please find the below link which points to the documentation of input layer in keras. Thanks !
[Link to refer](https://keras.io/layers/core/#input)
