### ISSUE TITLE
Error while training a recurrent neural network with LSTM

### ISSUE THREAD

**Issue by gargayush792** [keras-team/keras#8053]
I am getting this error while training my RNN on Keras - 

ValueError: Error when checking model input: expected lstm_1_input to have 3 dimensions, but got array with shape (401, 1)

My code looks like this - 

def rnn_model():
    model = Sequential()
    model.add(LSTM(64, input_shape=(None,97)))
    model.add(Activation('softmax'))
    sgd = SGD(lr=0.5, decay=0.99, clipnorm=5)
    model.compile(loss='categorical_crossentropy', optimizer=sgd)
    return model

rnn_model().fit(input_tensor, output_tensor, epochs=260, batch_size=64)

The input_tensor is a 3D Numpy  array with 400 training examples. Each training example is a one hot encoded 2D array of dimension (X,97) where X varies from example to example.

Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by harshini-gadige** [comment]
Is this still an issue ?
