### ISSUE TITLE
coding Salt and Pepper layer like keras.layers.noise.GaussianNoise

### ISSUE THREAD

**Issue by TakeToh** [keras-team/keras#8054]
Hello

I'm coding a Salt and Pepper Layer based on the code of keras.layers.noise.GaussianNoise.
But I get this, ERROR ( TypeError: len() of unsized object ).
I think its due to the shape of the inputs in the "noised" function.

How can I get the layer to work?
Following is the code.

from keras import backend as K
from keras.engine.topology import Layer
import numpy as np

class SaltAndPepper(Layer):

    def __init__(self, ratio, **kwargs):
        super(SaltAndPepper, self).__init__(**kwargs)
        self.supports_masking = True
        self.ratio = ratio

    def call(self, inputs, training=None):
        def noised():
            r = self.ratio*10
            s = inputs.shape[1]
            n = int( s * r /10 )
            print r
            perm = np.random.permutation(r)[:n]
            inputs[perm] = (np.random.rand(n) > 0.5)
            return inputs

        return K.in_train_phase(noised, inputs, training=training)

    def get_config(self):
        config = {'ratio': self.ratio}
        base_config = super(SaltAndPepper, self).get_config()
        return dict(list(base_config.items()) + list(config.items()))

**Comment by unrealwill** [comment]
Hello 
In K.in_train_phase The type of noised is a function type. You probably intended noised()
