### ISSUE TITLE
Sequential output in recurrent network

### ISSUE THREAD

**Issue by zparcheta** [keras-team/keras#8062]
Hi, 
I'm doing experiments with gestures recognition. I have matrix with gestures information where are a sequence of gestures (not only one). The sequence of gestures can mean whole sentence. All matrix gestures have the same size eg. 3 variables with 3 rows where each row is the information of given frame. 
The output is the sentence eg. "how are you". I have done the one hot vector of each word and finally the output is the matrix of 3x3 (if we consider the vocabulary is 3). I prepared the following network.

`import pickle as cPickle
import numpy as np
from keras.models import Model
from keras.layers import *

trainX = [[[-1.06, -0.13, -0.06],
            [-1.12, -0.09, -0.04],
            [-1.16, -0.03, -0.02]], # "how are you"
           [[-1.08, -1.05, -0.75], 
            [-1.16, -1.04, -0.69],
            [-1.26, -0.97, -0.59]], # "how"
           [[-1.20, -0.12, -0.04],
            [-1.18, -0.08, -0.03],
            [-1.16, -0.04, -0.01]]] # "you are"

trainX = np.array(trainX)       
        
#one-hot vector of words            
trainY = [[[0.,0.,1.],  # "how"
            [0.,1.,0.],  # "are"
            [1.,0.,0.]], # "you"
           [[0.,1.,0.],  # "how"
            [0.,0.,0.],  # null
            [0.,0.,0.]], # null
           [[1.,0.,0.],  # "you"
            [0.,1.,0.],  # "are"
            [0.,0.,0.]]] # null

trainY = np.array(trainY)

input_layer = Input(batch_shape=tuple([3,3,3]))
lstm = LSTM(units=64)(input_layer)
output = Dense(64,activation='softmax',input_dim=trainY.shape)(lstm)
model = Model(inputs=input_layer, outputs=output)
model.compile(loss='categorical_crossentropy',
              optimizer='sgd',
              metrics=['accuracy'])
model.fit(trainX, trainY,batch_size=32)`

But can't resolve the following problem:

> ValueError: Error when checking target: expected dense_1 to have 2 dimensions, but got array with shape (3, 3, 3)

It is because the trainY labels are not a simple classifier. Someone knows how can I fix it?

Thanks

**Comment by lvapeab** [comment]
Hi, 

you may need to build a model similar to the [addition RNN](https://github.com/fchollet/keras/blob/5bd3976e790e6f0b23d372ca2ae01f1f4dfef73f/examples/addition_rnn.py#L150-L174) example. That means, RNNs with `return_sequences=True` and `TimeDistributed(Dense(...))` layers.

Cheers!
