### ISSUE TITLE
LSTM equation in Keras

### ISSUE THREAD

**Issue by beebrain** [keras-team/keras#8072]
I confuse with Lstm in Keras. I try to map Keras code to LSTM equation. I found this weights parameter in Keras code. 

![image](https://user-images.githubusercontent.com/10016227/31258172-999520a6-aa67-11e7-9fc4-ffaa6d646994.png)

I think that It's a weight from current weight of cell and recurrent weight of cell.

In the call function in LSTM Keras code, I found the statement for calculate input ,forget ,cell and output term.

![image](https://user-images.githubusercontent.com/10016227/31258223-e7627d42-aa67-11e7-8810-723bd7a05391.png)

In input term of LSTM equation have W_ci * C_t-1 but I can't find in Keras code.

![image](https://user-images.githubusercontent.com/10016227/31258220-e31a4d32-aa67-11e7-8139-ae91968239ec.png)

Could please anyone explains the LSTM equation and Keras code.

**Comment by unrealwill** [comment]
Where to you take your LSTM equations from ? 
On Wikipedia about original LSTM : 
![image](https://user-images.githubusercontent.com/11304248/31311358-24fc6db8-abab-11e7-8c90-3709e1c70b66.png)

**Comment by tomastheod-ITI** [comment]
In previous Keras versions, the following link was part of the LSTM layer description:

"Long-Short Term Memory unit - Hochreiter 1997. For a step-by-step description of the algorithm, see [this tutorial] (http://deeplearning.net/tutorial/lstm.html)."

It is explained there that this change was performed for computational efficiency.
