### ISSUE TITLE
Trying to define kullback-leilbler(kl) divergence Layer Issues.

### ISSUE THREAD

**Issue by teinhonglo** [keras-team/keras#8074]
Hello!
I am new to Theano and Keras so maybe I am asking something silly but have been a few days trying to get this working and cannot.

I want to build a siamese architecture that takes 3 vectors as inputs and 1 output weather they come from the same source or not. The code I have is something like this:

###  Here is my custom Lambda layer: 
```python
''' Import keras to build a DL model '''
from keras.layers import Dense, Input, Lambda
from keras.layers.core import Reshape, Dense, Activation
from keras.models import Model
from keras import backend as K

''' custom loss function'''
def kl_distance(vects):
    qry_vec, doc_vec = vects
    qry_vec = K.clip(qry_vec, K.epsilon(), 1)
    doc_vec = K.clip(doc_vec, K.epsilon(), 1)
    return K.sum(qry_vec * K.log(doc_vec), axis=-1)

def relative_distance(vects):
    x, y = vects
    return x - y

def kl_shape(shapes):
    shape1, shape2 = shapes
    return (shape1[0], 1)

def rel_shape(shapes):
    shape1, shape2 = shapes
    return (shape1[0], 1)
```
###  Here is my based network
```python
emb_layer = Dense(embedding_dimensionality, activation="linear", name="emb_layer")
rep_layer = Dense(vocabulary_size, activation="softmax", name="rep_layer")

qry = Input(shape=(vocabulary_size,), name="qry_input")
doc_plus = Input(shape=(vocabulary_size,), name="doc_plus_input")
doc_minus = Input(shape=(vocabulary_size,), name="doc_minus_input")

qry_emb = emb_layer(qry)
doc_emb_plus = emb_layer(doc_plus)
doc_emb_minus = emb_layer(doc_minus)

qry_rep = rep_layer(qry_emb)
doc_rep_plus = rep_layer(doc_emb_plus)
doc_rep_minus = rep_layer(doc_emb_minus)

plus_score = Lambda(kl_distance, output_shape=kl_shape, name="qry_plus")([qry_rep, doc_rep_plus])
minus_score = Lambda(kl_distance, output_shape=kl_shape, name="qry_minus")([qry_rep, doc_rep_minus])

predicts = Lambda(relative_distance, output_shape=rel_shape)([plus_score, minus_score])

model = Model(inputs=[qry, doc_plus, doc_minus], outputs=predicts)
model.summary()
```

###  Error message:

ValueError: Input dimension mis-match. (input[1].shape[1] = 1, input[2].shape[1] = 16)
Apply node that caused the error: Elemwise{Composite{(i0 - (i1 * i2))}}(TensorConstant{(1, 1) of 1.0}, Elemwise{sgn,no_inplace}.0, Elemwise{Sub}[(0, 0)].0)
Toposort index: 61
Inputs types: [TensorType(float32, (True, True)), TensorType(float32, matrix), TensorType(float32, row)]
Inputs shapes: [(1, 1), (16, 1), (1, 16)]
Inputs strides: [(4, 4), (4, 4), (64, 4)]
Inputs values: [array([[ 1.]], dtype=float32), 'not shown', 'not shown']
Outputs clients: [[Elemwise{maximum,no_inplace}(TensorConstant{(1, 1) of 0.0}, Elemwise{Composite{(i0 - (i1 * i2))}}.0), Elemwise{Composite{(EQ(i0, i1) * i2 * i3)}}[(0, 0)](Elemwise{maximum,no_inplace}.0, Elemwise{Composite{(i0 - (i1 * i2))}}.0, Elemwise{Composite{((i0 * i1) / i2)}}.0, Elemwise{sgn,no_inplace}.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

**Comment by unrealwill** [comment]
Hello,
This is probably a broadcasting issue relative to theano. 
Your input of shape (16,1) is of type TensorType(float32, matrix) which is not broadcastable. 
You will have to call a theano.tensor.addbroadcast( theproblematicsymbol )
See documentation there : (http://deeplearning.net/software/theano/library/tensor/basic.html)

**Comment by teinhonglo** [comment]
Hello,
Thank you for your advice.
In the model input, I set the following:
### Here is the code:
```python
model.fit([X_train, X_train, X_train], Y_train,
			batch_size=batch_size,
			epochs=epochs,
			verbose=1,
			shuffle=True)
```
where
X_train.shape = (800, 51253)
Y_train.shape = (800, )

But input shape is the same.
This is the issue of broadcast?
I am not clear on it . How can I correct it?
