### ISSUE TITLE
Keras LSTM neural netwotk translation to C

### ISSUE THREAD

**Issue by ales222** [keras-team/keras#8080]
I built a LSTM network for Time Series Prediction, I saved the network with the command : "model.save('my_model.h5')"

Is now possible to translate in C language?

Are there any tools that automatically create a C language code starting from the Python code?

Are there any problems in translation of keras and all the other libraries necessary to run the code and so generate a prediction using the already trained model??

Thanks!!

**Comment by unrealwill** [comment]
Hello,
Hello,
You will have to choose your backend (either tensorflow or mxnet), and follow the instruction they told you to port your model to the various platforms.
For embedded platforms (like Arduino (from your other question) ), you probably are better to write custom code for performance, and copy the weights manually.
