### ISSUE TITLE
Using Tokenizer with num_words

### ISSUE THREAD

**Issue by mpizosdim** [keras-team/keras#8092]
Using `Tokenizer` from `keras.preprocessing.text`. From the following code:

      from keras.preprocessing.text import Tokenizer
      tk = Tokenizer(num_words=2)
      texts = ["my name is far", "my name is","your name is"]
      tk.fit_on_texts(texts)

And applying on it:

      >>> tk.texts_to_sequences(texts)
      >>> [[1], [1], [1]]

But:
   
      >>> tk.word_index
      >>> {'far': 4, 'is': 1, 'my': 3, 'name': 2, 'your': 5}

Why word_index of the tokenizer stores all the words and not only the top `num_words`? Shouldnt it be in that case:

      >>> tk.word_index
      >>> {'is': 1}

Is there a reason that all values are kept?

**Comment by nicolewhite** [comment]
The way I personally use Tokenizer is to initialize a Tokenizer once without a `num_words` argument, fit on the texts, and then change the `num_words` attribute as I see fit. It doesn't make a lot of sense to reinitialize and refit a Tokenizer when you just want to change the number of words, as you've pointed out all the necessary information is stored on the Tokenizer anyway. So my theory as to why it's designed that way is the ability to do this:

```python
In [1]: from keras.preprocessing.text import Tokenizer
In [2]: tk = Tokenizer()
In [3]: texts = ["my name is far", "my name is","your name is"]
In [4]: tk.fit_on_texts(texts)
In [5]: tk.num_words = 2
In [6]: tk.texts_to_sequences(texts)
Out[6]: [[1], [1], [1]]
In [7]: tk.num_words = 3
In [8]: tk.texts_to_sequences(texts)
Out[8]: [[1, 2], [1, 2], [1, 2]]
```

Though I would argue a better design would be to drop the `num_words` argument from `__init__` and move it to the various `texts_to_...` methods as an argument, like so:

```python
tk = Tokenizer()
tk.fit_on_texts(texts)
tk.texts_to_sequences(texts, num_words=2)
```

**Comment by Dobatymo** [comment]
I can confirm this problem

```python
>>> from keras.preprocessing.text import Tokenizer
>>> t = Tokenizer(1)
>>> t.fit_on_texts(["asd asd qwe"])
>>> t.texts_to_sequences(["asd qwe"])
[[]]
```

The error is in these lines:
`                    if num_words and i >= num_words:` in `texts_to_sequences_generator()`
and 
`                if j >= num_words:` in `sequences_to_matrix()`
in `keras/preprocessing/text.py`
it should be `>` as `i` starts at `1`.

**Comment by T3am5hark** [comment]
I'm seeing the same issue.  According to documentation, num_words should limit the number of words mapped by the tokenizer.  I don't see this to be the case...

`from keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer(num_words=10)
tokenizer.fit_on_texts([raw_text])

word_vectors = tokenizer.texts_to_sequences([raw_text])
word_vector = word_vectors[0]

print(len(word_vector))
print('Num words = {0}'.format(len(tokenizer.word_index)))`

yields me 1124 words.  I also tried inserting a num_words between training and sequence conversion, no difference in behavior.  Are there any examples out there illustrating correct or intended use of num_words?

**Comment by nicolewhite** [comment]
I attempted to explain this here: https://github.com/keras-team/keras/issues/8583#issuecomment-346981336

**Comment by se4u** [comment]
Lots of issues have been created about the tokenizer, #8583,  #7551, #7836, #4998  because the code doesn't correctly handle OOVs and the num_words parameters and the documentation and code are out of sync. Here's a small example of how we can achieve the correct behavior. Unfortunately, this truncates the `word_index` outside the class. But as I show below this truncation is necessary. Otherwise the tokenizer drops the OOV tokens even if we give the `oov_token` parameter.

``` python
>> num_words = 3
>> tk = kpt.Tokenizer(oov_token='UNK', num_words=num_words+1)
>> texts = ["my name is far faraway asdasd", "my name is","your name is"]
>> tk.fit_on_texts(texts)
>> print(tk.word_index)
>> print(tk.texts_to_sequences(texts))
>> ## **Key Step**
>> tk.word_index = {e:i for e,i in tk.word_index.items() if i <= num_words} # <= because tokenizer is 1 indexed
>> tk.word_index[tk.oov_token] = num_words + 1
>> print(tk.word_index)
>> print(tk.texts_to_sequences(texts))
{'your': 7, 'my': 3, 'name': 1, 'far': 4, 'faraway': 5, 'is': 2, 'UNK': 8, 'asdasd': 6} 
[[3, 1, 2], [3, 1, 2], [1, 2]]  ## Wrong Behavior. Should not drop OOVs
{'name': 1, 'my': 3, 'is': 2, 'UNK': 4}
[[3, 1, 2, 4, 4, 4], [3, 1, 2], [4, 1, 2]] ## Correct behavior
```

**Comment by NicGian** [comment]
Thanks se4u, I had your same issue and your trick solved it!

**Comment by FrancescoSaverioZuppichini** [comment]
@se4u you save my day. Should they fix it?

**Comment by Paksssssss** [comment]
thanks @se4u I think they should acknowledge this so that it could be fixed.

**Comment by macco3k** [comment]
Any chance this would be fixed? It's a pretty nasty behaviour if you ask me. Just don't drop OOV words unless explicitly requested to do so.

**Comment by ericmclachlan** [comment]
@se4u: You've done a great job of illustrating the problem. 

If you're wanting to preserve the most frequently **used** words, you can replace the following (in @se4u's code)

```Python
    tk.word_index = {e:i for e,i in tk.word_index.items() if i <= num_words} # <= because tokenizer is 1 indexed
```

with

```Python
    sorted_by_word_count = sorted(tk.word_counts.items(), key=lambda kv: kv[1], reverse=True)
    tk.word_index = {}
    i = 0
    for word,count in sorted_by_word_count:
        if i == num_words:
            break
        tk.word_index[word] = i + 1    # <= because tokenizer is 1 indexed
        i += 1
```
(Although, there's almost definitely a more elegant way to do this in Python.)

**Comment by serdarbozoglan** [comment]
> Lots of issues have been created about the tokenizer, #8583, #7551, #7836, #4998 because the code doesn't correctly handle OOVs and the num_words parameters and the documentation and code are out of sync. Here's a small example of how we can achieve the correct behavior. Unfortunately, this truncates the `word_index` outside the class. But as I show below this truncation is necessary. Otherwise the tokenizer drops the OOV tokens even if we give the `oov_token` parameter.
> 
> ```python
> >> num_words = 3
> >> tk = kpt.Tokenizer(oov_token='UNK', num_words=num_words+1)
> >> texts = ["my name is far faraway asdasd", "my name is","your name is"]
> >> tk.fit_on_texts(texts)
> >> print(tk.word_index)
> >> print(tk.texts_to_sequences(texts))
> >> ## **Key Step**
> >> tk.word_index = {e:i for e,i in tk.word_index.items() if i <= num_words} # <= because tokenizer is 1 indexed
> >> tk.word_index[tk.oov_token] = num_words + 1
> >> print(tk.word_index)
> >> print(tk.texts_to_sequences(texts))
> {'your': 7, 'my': 3, 'name': 1, 'far': 4, 'faraway': 5, 'is': 2, 'UNK': 8, 'asdasd': 6} 
> [[3, 1, 2], [3, 1, 2], [1, 2]]  ## Wrong Behavior. Should not drop OOVs
> {'name': 1, 'my': 3, 'is': 2, 'UNK': 4}
> [[3, 1, 2, 4, 4, 4], [3, 1, 2], [4, 1, 2]] ## Correct behavior
> ```

Hello, I have a quick question. My "UNK" index number is 1 interestingly instead of 8. kpt considers as the first token rather than last token. Could could be the reason or how can I fix it? Thank you

**Comment by rjurney** [comment]
@ericmclachlan They're already sorted that way when you fit the Tokenizer.

**Comment by Srikanth421** [comment]
> Using `Tokenizer` from `keras.preprocessing.text`. From the following code:
> 
> ```
>   from keras.preprocessing.text import Tokenizer
>   tk = Tokenizer(num_words=2)
>   texts = ["my name is far", "my name is","your name is"]
>   tk.fit_on_texts(texts)
> ```
> 
> And applying on it:
> 
> ```
>   >>> tk.texts_to_sequences(texts)
>   >>> [[1], [1], [1]]
> ```
> 
> But:
> 
> ```
>   >>> tk.word_index
>   >>> {'far': 4, 'is': 1, 'my': 3, 'name': 2, 'your': 5}
> ```
> 
> Why word_index of the tokenizer stores all the words and not only the top `num_words`? Shouldnt it be in that case:
> 
> ```
>   >>> tk.word_index
>   >>> {'is': 1}
> ```
> 
> Is there a reason that all values are kept?

Hi! The num_words specifies the maximum number of tokens and picks the most common num_words specified. If I change your code:
`from keras.preprocessing.text import Tokenizer
tk = Tokenizer(num_words=2)
texts = ["my name is far", "my name is","your"]
tk.fit_on_texts(texts)` 

Notice what happens:
`tk.texts_to_sequences(texts)`
`[[1], [1], []]` 

The third element in the list doesn't have any common words with the other 2.

**Comment by khaledadrani** [comment]
Since the issue is still open, one would naturally think that it is yet present. Or is there any update in Keras which addressed this issue? For now, I'll be using the answers above but updating this feature of the Keras tokenizer is mandatory. 
Still needed +1.

**Comment by d3lm** [comment]
@fchollet Did you close this issue because it's been addressed?

**Comment by cserranobr** [comment]
Why not just getting the keys as per below?

>>> DIC
{'<UNK>': 1, 'de': 2, 'e': 3, 'é': 4, 'que': 5, 'em': 6, 'eu': 7, 'se': 8, 'meu': 9, 'não': 10, 'com': 11, 'pra': 12, 'vem': 13, 'lá': 14, 'sou': 15, 'me': 16, 'vou': 17, 'vai': 18, 'amor': 19, 'ao': 20, 'tem': 21, 'ô': 22, 'por': 23, 'seu': 24, 'mais': 25, 'quem': 26, 'foi': 27, 'hoje': 28, 'faz': 29, 'te': 32, 'quero': 33, 'o_meu': 34, 'coração': 35, 'minha': 36, 'ver': 37, 'brasil': 38, 'sem': 39, 'à': 40, 'ser': 41, 'carnaval': 42, 'o_povo': 43, 'fez': 44, 'são': 45, 'nossa': 46, 'alegria': 47, 'chegou': 48, 'terra': 49, 'do_meu': 50, 'num': 51, 'mas': 52, 'feliz': 53, 'você': 54, 'cantar': 55, 'onde': 56, 'quando': 57, 'nessa': 58, 'história': 59, 'tão': 60, 'como': 61, 'era': 62, 'só': 63, 'mundo': 64, 'assim': 65, 'oh': 66, 'branco': 67, 'ou': 68, 'gente': 69}

>>> num_words = 10

>>> your_dict = {k:v for k,v in DIC.items() if v <= num_words}

>>> your_dict
{'<UNK>': 1, 'de': 2, 'e': 3, 'é': 4, 'que': 5, 'em': 6, 'eu': 7, 'se': 8, 'meu': 9, 'não': 10}
