### ISSUE TITLE
time series preprocessing for LSTM

### ISSUE THREAD

**Issue by redwrasse** [keras-team/keras#8110]
I'd like to have preprocessing functions for univariate and multivariate time series 
available in Keras to make them suitable as input for LSTM layers. Is there any such thing 
available or interest?

(it should be fairly trivial, but useful)

For example, to prepare time series for an autoencoder:
```
# Given time series samples x with shape 
# (number of samples, time series length, number of dim.)
 x = ...   

def make_lstm_input(x, timesteps, timestep_overlap, dimensions):
      """ Chunks the time series into chunks of size <timesteps> 
            and returns an array of shape 
            (number of samples * number of chunks, timesteps, dimensions)
      """
      ....
      return lstm_x 

# put into an autoencoder


timesteps = ..
timestep_overlap = ...
dim = ...
lstm_x = make_input_lstm(x, timesteps, timestep_overlap, dimensions)
encoding_dim = 2

m = Sequential()
m.add(LSTM(dim, input_shape=(timesteps, encoding_dim)))
m.add(RepeatVector(timesteps))
m.add(LSTM(encoding_dim, return_sequences=True))
m.compile(...)
m.fit(lstm_x, lstm_x,...)



```

**Comment by gorda299** [comment]
Thanks for the question, I'm also interested in this topic. And I have a related question - how can I feed model with intervals which are not connected with each other? For example, I have multivariate time series 01.01.2017 - 10.02.2017 each hour, 10.02.2017 - 21.02.2017 missing data, 21.02.2017 - 01.05.2017 filled data and so on. I can't union this intervals and say that after 10.02.2017 will be 21.02.2017. How should I solve this task?
