### ISSUE TITLE
Extract the weights of a layer

### ISSUE THREAD

**Issue by luciaL** [keras-team/keras#8151]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [ ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [ ] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by luciaL** [comment]
I want to extract the weights of a layer.When i use save_weights and load_weights,I must use it in a model.This is not what i want. I need to extract the weights of the Dense layer and make it into a fully convolution  layers.Please tell me how to do it if you guys know.

**Comment by tRosenflanz** [comment]
https://github.com/fchollet/keras/issues/91

**Comment by karenyun** [comment]
@luciaL, hi, have you solved your problem? During training process, if I want to use the weights of one layer to another, and these two layers are in the same model but different part, do not use save_weights and load_weights, how can I do it? Thanks!
