### ISSUE TITLE
LSTM simultaneous sequence prediction of multiple sequences

### ISSUE THREAD

**Issue by ebirck** [keras-team/keras#8157]
Hello,

Pardon the likely basic question, but I am relatively new to Keras and I'm very confused on how to make this work. So the end goal is I have n time-dependent sequences with equal time steps (the same number of points on each sequence and the points are all the same time apart) and I would like to feed all n sequences into the same network so it can use correlations between the sequences to better predict the next step for each sequence. My ideal output would be an n-element array with array[0] corresponding to the next-step prediction for sequence_1, array[1] for sequence_2, and so on.

I was able to get a working model for each sequence independently using the code at the end of this guide by Jakob Aungiers: 

http://www.jakob-aungiers.com/articles/a/LSTM-Neural-Network-for-Time-Series-Prediction

although my difficulty is adapting it to accept multiple sequences at once and correlate between them (i.e. they must be analyzed in parallel). I believe the issue is related to the shape of my input data, although I could also be completely missing the target here. My code (which is mostly Jakob's, not trying to take credit for anything that isn't mine) presently looks like this:

run.py
```
import lstm
import time
import matplotlib.pyplot as plt
import numpy as np

def plot_results(predicted_data, true_data):
    fig = plt.figure(facecolor='white')
    ax = fig.add_subplot(111)
    ax.plot(true_data, label='True Data')
    plt.plot(predicted_data, label='Prediction')
    plt.legend()
    plt.show()

if __name__=='__main__':
	epochs  = 1
	seq_len = 30

	X_train_a, y_train_a, X_test_a, y_test_a = lstm.load_data('sequence_a', seq_len, True)
	X_train_b, y_train_b, X_test_b, y_test_b = lstm.load_data('sequence_b', seq_len, True)
	X_train_c, y_train_c, X_test_c, y_test_c = lstm.load_data('sequence_c', seq_len, True)
	X_train_d, y_train_d, X_test_d, y_test_d = lstm.load_data('sequence_d', seq_len, True)

	X_train = np.array([X_train_a, X_train_b, X_train_c, X_train_d])
	y_train = np.array([y_train_a, y_train_b, y_train_c, y_train_d])
	X_test = np.array([X_test_a, X_test_b, X_test_c, X_test_d])
	y_test = np.array([y_test_a, y_test_b, y_test_c, y_test_d])

	model = lstm.build_model([4, 50, 100, 4])

	model.fit(
		X_train,
		y_train,
		batch_size=512,
		nb_epoch=epochs,
		validation_split=0.05)

	predicted = lstm.predict_point_by_point(model, X_test)

	plot_results(predicted[0,:], y_test_a)
```
lstm.py
```
import os
import time
import warnings
import numpy as np
from numpy import newaxis
from keras.layers.core import Dense, Activation, Dropout
from keras.layers.recurrent import LSTM
from keras.models import Sequential

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'  # Hide messy TensorFlow warnings
warnings.filterwarnings("ignore")  # Hide messy Numpy warnings


def load_data(filename, seq_len, normalise_window):
    f = open(filename, 'rb').read()
    data = f.decode().split('\n')

    sequence_length = seq_len + 1
    result = []
    for index in range(len(data) - sequence_length):
        result.append(data[index: index + sequence_length])

    if normalise_window:
        result = normalise_windows(result)

    result = np.array(result)

    row = round(0.9 * result.shape[0])
    train = result[:int(row), :]
    np.random.shuffle(train)
    x_train = train[:, :-1]
    y_train = train[:, -1]
    x_test = result[int(row):, :-1]
    y_test = result[int(row):, -1]

    #x_train = np.reshape(x_train, (x_train.shape[0], x_train.shape[1], 1))
    #x_test = np.reshape(x_test, (x_test.shape[0], x_test.shape[1], 1))

    return [x_train, y_train, x_test, y_test]


def normalise_windows(window_data):
    normalised_data = []
    for window in window_data:
        normalised_window = [((float(p) / float(window[0])) - 1) for p in window]
        normalised_data.append(normalised_window)
    return normalised_data


def build_model(layers):
    model = Sequential()

    model.add(LSTM(
        input_shape=(490, 30),            #temporary data associated with test data sequences
        output_dim=layers[1],
        return_sequences=True))
    model.add(Dropout(0.2))

    model.add(LSTM(
        layers[2],
        return_sequences=False))
    model.add(Dropout(0.2))

    model.add(Dense(
        output_dim=layers[3]))
    model.add(Activation("linear"))

    model.compile(loss="mse", optimizer="rmsprop")
    return model


def predict_point_by_point(model, data):
    # Predict each timestep given the last sequence of true data, in effect only predicting 1 step ahead each time
    predicted = model.predict(data)
    predicted = np.reshape(predicted, (predicted.size,))
    return predicted
```
As-is this complains with "ValueError: Error when checking target: expected activation_1 to have shape (None, 4) but got array with shape (4, 490)", I'm sure there are plenty of other issues but I'd love some direction on how to achieve what I'm describing. Anything stick out immediately to anyone? Any help you could give will be greatly appreciated.

Thanks!

-Eric

**Comment by oadele3** [comment]
Hi Eric, Please how did you solve this multi sequence time series? I am trying the same... have 3 values every time step, I want to train on a n samples of data like below and then generate predictions for the next m timesteps.

input: [[1, 0.33, 0.665],
            [1, 0.45, 0.644],
            [0, 0.33, 0.565],
            [1, 0.33, 0.665],
                        ....
                        ....         ]]

predicted output = 
          [[0, 0.37, 0.665],
            [1, 0.47, 0.654],
            [1, 0.33, 0.665],
                        ....
                        ....         ]]

**Comment by ebirck** [comment]
Hi,

Assuming you want to cross correlate the 3 numbers (i.e. allow the network
to look for patterns between the numbers) you want to input them as
'features', so your input shape (X) would be

X.shape = (n, m, 3) where n is the number of predictions and m is the
number of timesteps before each prediction

and output shape (Y) would be

Y.shape = (n, 3) again with n being the number of predictions.

As a clarification, if you are feeding in 30 timesteps and want your
network to predict the 31st step, m = 30, and if you want to do this 500
times in a row with a different 30 inputs each time, n = 500. For more help
please see the basic demonstration of this I posted on my github:

https://github.com/ebirck/lstm_sequence_prediction

since your data seems to already be normalized you can just remove my
normalization functions in lstm.load_data and replace the names of the
files loaded with your own - feel free to ask if you still need any help
getting things to work for you.

Best,

-Eric
