### ISSUE TITLE
no dilation_rate in Conv2DTranspose

### ISSUE THREAD

**Issue by Dobiasd** [keras-team/keras#8159]
The docs of the [`Conv2DTranspose` layer mention `dilation_rate`](https://github.com/fchollet/keras/blob/7610c55bdc046ff0b0d6300af5ea9dcfd0a427cb/keras/layers/convolutional.py#L632) but the [call to the backend](https://github.com/fchollet/keras/blob/7610c55bdc046ff0b0d6300af5ea9dcfd0a427cb/keras/layers/convolutional.py#L768) does not include `dilation_rate`. The [backend function `conv2d_transpose`](https://github.com/fchollet/keras/blob/6b106ab4ec9a1c0eb3e24ae590ce63f84022ad40/keras/backend/tensorflow_backend.py#L3183) would not even support it.
In TensorFlow it would be a call to the separate function [`atrous_conv2d_transpose`](https://www.tensorflow.org/api_docs/python/tf/nn/atrous_conv2d_transpose).
Is there something else going on in Keras that dilates the kernels, perhaps in the base class (i.e. `Conv2D`)?

In the following test at least the output of a `Conv2DTranspose` layer with `dilation_rate == (2, 1)` has the same shape as with `dilation_rate == (1, 1)`.

```python
from keras.models import Model
from keras.layers import Input, Conv2DTranspose
from keras import backend as K
import numpy as np

assert K.backend() == "tensorflow"
assert K.floatx() == "float32"
assert K.image_data_format() == 'channels_last'

kernel_size = (2, 1)
strides = (1, 1)
padding = 'valid'
input_shape = (6, 1, 1)
inp = Input(shape=input_shape)
ct_1_1 = Conv2DTranspose(1, kernel_size, strides=strides,
                         padding=padding, dilation_rate=(1, 1))(inp)
ct_2_1 = Conv2DTranspose(1, kernel_size, strides=strides,
                         padding=padding, dilation_rate=(2, 1))(inp)
model = Model(inputs=inp, outputs=[ct_1_1, ct_2_1])
model.compile(optimizer='rmsprop', loss='mse')

data_in = np.random.random((1, *input_shape))

result = model.predict(data_in)
print('data_in.shape  ', data_in.shape)
print('result[0].shape', result[0].shape)
print('result[1].shape', result[1].shape)
```
output:
```
data_in.shape   (1, 6, 1, 1)
result[0].shape (1, 7, 1, 1)
result[1].shape (1, 7, 1, 1)
```

But if I understand transposed convolution correctly, the output shapes should differ. So perhaps by accident `Conv2DTranspose` currently does not support dilation at all?

**Comment by Dobiasd** [comment]
Small update: The issue is still relevant in Keras 2.1.1 with TensorFlow 1.4.0.

**Comment by CarlOlson** [comment]
It looks like all the backends support this. This really should not be in the documentation if it isn't supported. Can the CI be improved to check for this kind of thing?

I'll look into making a PR this weekend since this isn't getting any attention.
