### ISSUE TITLE
[Suggestion] Document preprocessing function for applications

### ISSUE THREAD

**Issue by alxy** [keras-team/keras#8161]
I think it should be valueable to document how the pretrained models (applications) have been trained, i.e. which augmentation and preprocessing has been used. Specifically the preprocessing function has to be known to apply it to the inputs in an actual use case.

Checking the sources, you can surely find the functions, however it did take me some time. What do you think?

**Comment by jiemojiemo** [comment]
Good suggestion!  
I have some confusion about the pre-trained models(applications) when I applied them to extract features. Most of these confusions are about how to preprocessing the input images. 
the example on https://keras.io/applications/ always preprocesses the input at ''caffe'' mode(preprocess_input default mode is "caffe"). 
Why always use the "caffe" mode? I have no idea.
