### ISSUE TITLE
Extracting low resolution visual features

### ISSUE THREAD

**Issue by ghost** [keras-team/keras#8168]
I would like to create architecture similar to the architecturte prestented in https://arxiv.org/pdf/1404.4661.pdf .
But I have a problem with this extracting low resolution visual features model part, presenten on the figure 3. 
I tried in this way:

```
model = models.Sequential()
model.add(layers.Conv2D(1, (1, 1), strides=(4,4), input_shape=input_shape))
model.add(layers.ZeroPadding2D(padding=(4,4)))
model.add(layers.Conv2D(96,(8,8),strides=4, input_shape=input_shape,activation='relu'))
model.add(layers.ZeroPadding2D(padding=(2, 2)))
model.add(layers.MaxPooling2D(pool_size=(7,7),strides=4,padding='valid'))
model.add(layers.Flatten())
model.summary()
```

but I think it's not the same, becouse of this first convolution layer, which is not the simple subsampling. 
It's possible to recreate this architecture in Kreas? I would be grateful for help.

**Comment by RitwikGupta** [comment]
The first convolution layer on the low resolution feature extractor is a simple subsampling! Your strides would be (8,8), as indicated by the 8:1 ratio on the figure. There would be some padding needed, but you can see how it's simple subsampling.
