### ISSUE TITLE
how to apply different Image Generator for different batches in Keras?

### ISSUE THREAD

**Issue by toseattle** [keras-team/keras#8173]
The training data is read from two .npy files. Say, train_set is regarded as X, and train_label is regarded as Y. Therefore, it is not a multiple input case. My task requires to augment the image patches in different manner. So how to define different Image Generator for different patches? Although there could be a lot of patches, I use 3 patches as an example:

for patch1:

datagen = ImageDataGenerator(rotation_range=20)

for patch2:

datagen = ImageDataGenerator(rotation_range=40)

for patch3:

datagen = ImageDataGenerator(rotation_range=60)

How to apply different generators on different patches, and how may I use the model.fit(...) or model.fit_generator(...) for the described scenario?

Also, Is there a way to rotate the image by a particular degree instead of a range?

Thanks!

**Comment by harshini-gadige** [comment]
Hi

Since this is not a bug/feature request, request you to post these kind of questions in any of the following.

https://keras.io/
https://keras.io/#support
https://gitter.im/Keras-io/Lobby

Thanks!
