### ISSUE TITLE
UpSampling3D Layer does not accept 'None' sized inputs under tensorflow

### ISSUE THREAD

**Issue by kmader** [keras-team/keras#8175]
It appears the UpSampling3D does not support None-sized inputs in Tensorflow
```
ValueError: Axis 1 of input tensor should have a defined dimension, but is None. Full tensor shape: (None, None, None, None, 1). Typically you need to pass a fully-defined `input_shape` argument to your first layer.
```

# 2D case works fine
```
from keras.models import Sequential
from keras.layers import UpSampling2D, UpSampling3D
twod_model = Sequential()
twod_model.add(UpSampling2D((2,2), input_shape = (None, None, 1)))
```
# 3D Case
```
threed_model = Sequential()
threed_model.add(UpSampling3D((2,2,2), input_shape = (None ,None, None, 1)))
```

## One Dimension 
```
threed_model = Sequential()
threed_model.add(UpSampling3D((2,2,2), input_shape = (1 ,None, None, 1)))
```

Error 
```
ValueError: Axis 2 of input tensor should have a defined dimension, but is None. Full tensor shape: (None, 2, None, None, 1). Typically you need to pass a fully-defined `input_shape` argument to your first layer.
```

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by jmj23** [comment]
I am having this issue as well

**Comment by mehrtash** [comment]
Same issue here.
