### ISSUE TITLE
Unable to fit the dataset to keras model 

### ISSUE THREAD

**Issue by Zumbalamambo** [keras-team/keras#8204]
i got the following error while trying to fit

```
ValueError: You are passing a target array of shape (80, 1) while using as loss `categorical_crossentropy`. `categorical_crossentropy` expects targets to be binary matrices (1s and 0s) of shape (samples, classes). If your targets are integer classes, you can convert them to the expected format via:
```

So I converted it to categorical  as follows,

```
from keras.utils.np_utils import to_categorical
y_train_new = to_categorical(y_train_new)
y_val_new = to_categorical(y_val_new)


hist = model.fit(
    X_train_new,
    y_train_new,
    validation_data=(X_val_new,y_val_new),
    batch_size=batch_size,
    nb_epoch = nb_epoch,
    shuffle=True
    )

```

but it throws the following error,
`ValueError: Error when checking target: expected activation_1 to have shape (None, 1) but got array with shape (80, 2)`

**Comment by Anurag14** [comment]
i also am encountering similar problem with fitting mnist data to autoencoder
model.fit(x_train,x_train,batch_size=256, epochs=50, validation_data=[x_test,x_new_test])
keras version 2.0.8 using theano as backend
but it throws the following error 

> TypeError: c_compile_args() takes 1 positional argument but 2 were given

> During handling of the above exception, another exception occurred:

**Comment by raul-jr3** [comment]
@Zumbalamambo try specifying the 'num_classes' in 'to_categorical' function.
@Anurag14 i guess the validation_data takes in a tuple, not a list.
