### ISSUE TITLE
TensorFlow: How to add additional commands to "sess.run([...])"

### ISSUE THREAD

**Issue by kutoga** [keras-team/keras#8211]
Hello

I have some code where I like to add an additional command to the "session.run([..., MY_COMMAND])" function call of tensorflow. How could this be done? If it is not possible (without adding changes / hacks to keras), please mention it (then I can stop trying to find a solution).

Now the reason:
I like to re-implement the following tensorflow code in keras: [https://github.com/godfanmiao/MNIST_CNN_CENTERLOSS_TENSORFLOW/blob/master/MNIST_CNN_BN_CENTERLOSS.ipynb](https://github.com/godfanmiao/MNIST_CNN_CENTERLOSS_TENSORFLOW/blob/master/MNIST_CNN_BN_CENTERLOSS.ipynb)

What does it do? It calculates the center loss (see: [http://ydwen.github.io/papers/WenECCV16.pdf](http://ydwen.github.io/papers/WenECCV16.pdf)) which requires an update of an internal state always when the training was done.

My "problem line" in the linked code is the following:
`_, cen = sess.run([train_op, update_centers], feed_dict = {xs: x_train[j:j+1000], ys: y_train[j:j+1000].values, keep_prob:1.0})`

Thank you very much

**Comment by abhaikollara** [comment]
I don't know if it suits your use case, but according the [docs here](https://keras.io/models/sequential/) you can pass keyword arguments to `model.compile` which gets passed into `tf.Session.run`.

**Comment by kutoga** [comment]
Thank you for the answer. I already tried these additional keywords, but the problem is that keras already generates an input for this first keyword "fetches". If it is added to the "compile"-call, I get this new error:
`TypeError: run() got multiple values for argument 'fetches'`

The value for the "fetches" parameter is an array (that is generated by keras) and I would like to append custom elements to it.
