### ISSUE TITLE
CTC implementation is unstable with toy example

### ISSUE THREAD

**Issue by sun-peach** [keras-team/keras#8216]
**_Hi, dear all,
I use the ctc_batch_cost with a toy example (code is listed as below):_**

batch_size = 32
frame_len = 3600
output_len = 600
nb_feat = 64
nb_class = 63
nb_output = nb_class + 1  # add output for blank
inner_dim = 16
def ctc_lambda_func(args):
    y_pred, labels, input_length, label_length = args
    # the 2 is critical here since the first couple outputs of the RNN
    # tend to be garbage:
    y_pred = y_pred[:, 2:, :]
    scale = 1
    return K.ctc_batch_cost(labels, y_pred, input_length, label_length)
print("Building model...")
input_data = Input(name='the_input', shape=(frame_len,nb_feat))
lstm1 = GRU(inner_dim,return_sequences = True, name='lstm1')(input_data)
y_pred = TimeDistributed(Dense(nb_output,activation='softmax',name='dense1'))(lstm1)
Model(inputs=input_data, outputs=y_pred).summary()
labels = Input(name='the_labels', shape=[output_len])
input_length = Input(name='input_length', shape=[1], dtype='int32')
label_length = Input(name='label_length', shape=[1], dtype='int32')
loss_out = Lambda(ctc_lambda_func, output_shape=(1,), name='ctc')([y_pred, labels, input_length, label_length])
model = Model(inputs=[input_data, labels, input_length, label_length], outputs=loss_out)
data = np.random.uniform(low = -5, high = 5, size = (batch_size, frame_len, nb_feat)).astype('float32')
label = 1 + np.random.randint(nb_class, size = (batch_size, output_len)).astype('float32')
length = np.ones((batch_size,1),dtype='float32')*frame_len
output_length = np.ones((batch_size,1),dtype='float32')*output_len
input_dict = {'the_input':data,'the_labels':label,'input_length':length,'label_length':output_length}
output_dict = {'ctc':np.zeros([batch_size])}
opt = SGD(lr=0.001, decay=1e-6, momentum=0.9, clipnorm=1.,clipvalue=0.5)
model.compile(loss={'ctc': lambda y_true, y_pred: y_pred}, optimizer=opt)
model.summary()
model.fit(input_dict, output_dict, epochs = 2, batch_size = batch_size)`

**_You can see it is random input and output sequences. The only point need be noticed is that the data length is pretty long. I run this toy example for a try because I have the real data with the same size. However, when it compute the CTC loss, the gradients turns to NaN. After checking and debugging, I find the CTC loss computation will lead to inf number. The output from NaNGuardmode is listed as below:_**

AssertionError: Inf detected
Big value detected
NanGuardMode found an error in the output of a node in this variable:
Elemwise{log,no_inplace} [id A] ''   
 |AdvancedIncSubtensor1{no_inplace,inc} [id B] ''   
   |IncSubtensor{Inc;int64::} [id C] ''   
   | |IncSubtensor{Set;:int32:} [id D] ''   
   | | |Subtensor{:int32:} [id E] ''   
   | | | |<TensorType(float64, vector)> [id F]
   | | | |ScalarFromTensor [id G] ''   
   | | |   |Elemwise{Cast{int32}} [id H] ''   
   | | |     |Elemwise{minimum,no_inplace} [id I] ''   
   | | |       |Elemwise{maximum,no_inplace} [id J] ''   
   | | |       | |Elemwise{add,no_inplace} [id K] ''   
   | | |       | | |<TensorType(int32, scalar)> [id L]
   | | |       | | |TensorConstant{1} [id M]
   | | |       | |Elemwise{add,no_inplace} [id N] ''   
   | | |       |   |Elemwise{add,no_inplace} [id O] ''   
   | | |       |   | |MaxAndArgmax{axis=(0,)}.0 [id P] 'max'   
   | | |       |   | | |Join [id Q] ''   
   | | |       |   | |   |TensorConstant{0} [id R]
   | | |       |   | |   |AdvancedSubtensor1 [id S] ''   
   | | |       |   | |   | |<TensorType(int64, vector)> [id T]
   | | |       |   | |   | |Subtensor{int64} [id U] ''   
   | | |       |   | |   |   |Nonzero [id V] ''   
   | | |       |   | |   |   | |Elemwise{lt,no_inplace} [id W] ''   
   | | |       |   | |   |   |   |<TensorType(int64, vector)> [id T]
   | | |       |   | |   |   |   |InplaceDimShuffle{x} [id X] ''   
   | | |       |   | |   |   |     |<TensorType(int32, scalar)> [id L]
   | | |       |   | |   |   |Constant{0} [id Y]
   | | |       |   | |   |TensorConstant{(1,) of -1} [id Z]
   | | |       |   | |TensorConstant{2} [id BA]
   | | |       |   |TensorConstant{1} [id M]
   | | |       |Subtensor{int64} [id BB] ''   
   | | |         |Shape [id BC] ''   
   | | |         | |<TensorType(float64, vector)> [id BD]
   | | |         |Constant{0} [id BE]
   | | |Elemwise{exp,no_inplace} [id BF] ''   
   | | | |Elemwise{sub,no_inplace} [id BG] ''   
   | | |   |Subtensor{:int32:} [id BH] ''   
   | | |   | |<TensorType(float64, vector)> [id BI]
   | | |   | |ScalarFromTensor [id BJ] ''   
   | | |   |   |<TensorType(int32, scalar)> [id L]
   | | |   |InplaceDimShuffle{x} [id BK] ''   
   | | |     |MaxAndArgmax{axis=(0,)}.0 [id BL] 'max'   
   | | |       |Subtensor{:int32:} [id BM] ''   
   | | |         |<TensorType(float64, vector)> [id BI]
   | | |         |ScalarFromTensor [id BN] ''   
   | | |           |<TensorType(int32, scalar)> [id L]
   | | |ScalarFromTensor [id BO] ''   
   | |   |<TensorType(int32, scalar)> [id L]
   | |Subtensor{:int64:} [id BP] ''   
   | | |IncSubtensor{Set;:int32:} [id D] ''   
   | | |Constant{-1} [id BQ]
   | |Constant{1} [id BR]
   |AdvancedSubtensor1 [id BS] ''   
   | |Elemwise{exp,no_inplace} [id BF] ''   
   | |AdvancedSubtensor1 [id S] ''   
   |Elemwise{add,no_inplace} [id BT] ''   
     |AdvancedSubtensor1 [id S] ''   
     |TensorConstant{(1,) of 2} [id BU]

 
Backtrace when that variable is created:

  File "build/bdist.linux-x86_64/egg/keras/backend/theano_backend.py", line 2385, in ctc_batch_cost
    mode=NanGuardMode(nan_is_error=True,inf_is_error=True,big_is_error=None)
  File "/usr/local/lib/python2.7/dist-packages/theano/scan_module/scan.py", line 773, in scan
    condition, outputs, updates = scan_utils.get_updates_and_outputs(fn(*args))
  File "build/bdist.linux-x86_64/egg/keras/backend/theano_backend.py", line 2379, in ctc_step
    return ctc_cost(y_pred_step, y_true_step)
  File "build/bdist.linux-x86_64/egg/keras/backend/theano_backend.py", line 2352, in ctc_cost
    log_probs, mask = ctc_path_probs(predict, ctc_interleave_blanks(Y))
  File "build/bdist.linux-x86_64/egg/keras/backend/theano_backend.py", line 2343, in ctc_path_probs
    mode=NanGuardMode(inf_is_error=True,big_is_error=True,nan_is_error=True,optimizer=None))
  File "/usr/local/lib/python2.7/dist-packages/theano/scan_module/scan.py", line 773, in scan
    condition, outputs, updates = scan_utils.get_updates_and_outputs(fn(*args))
  File "build/bdist.linux-x86_64/egg/keras/backend/theano_backend.py", line 2337, in step
    f_active_next, log_f_next = ctc_update_log_p(f_skip_idxs, zeros, f_active, log_f_curr, log_f_prev)
  File "build/bdist.linux-x86_64/egg/keras/backend/theano_backend.py", line 2308, in ctc_update_log_p
    updated_log_p_prev = T.log(_p_prev) + common_factor

Apply node that caused the error: Elemwise{log,no_inplace}(AdvancedIncSubtensor1{no_inplace,inc}.0)
Toposort index: 34
Inputs types: [TensorType(float64, vector)]
Inputs shapes: [(1201,)]
Inputs strides: [(8,)]
Inputs values: ['not shown']
Outputs clients: [[Elemwise{add,no_inplace}(Elemwise{log,no_inplace}.0, InplaceDimShuffle{x}.0)]]

**_I put the nanguardmode in ctc_path_probs function as below:_**

def ctc_path_probs(predict, Y, alpha=1e-4):
    smoothed_predict = (1 - alpha) * predict[:, Y] + alpha * np.float32(1.) / Y.shape[0]
    L = T.log(smoothed_predict)
    zeros = T.zeros_like(L[0])
    log_first = zeros
    f_skip_idxs = ctc_create_skip_idxs(Y)
    b_skip_idxs = ctc_create_skip_idxs(Y[::-1])  # there should be a shortcut to calculating this
    def step(log_f_curr, log_b_curr, f_active, log_f_prev, b_active, log_b_prev):
        f_active_next, log_f_next = ctc_update_log_p(f_skip_idxs, zeros, f_active, log_f_curr, log_f_prev)
        b_active_next, log_b_next = ctc_update_log_p(b_skip_idxs, zeros, b_active, log_b_curr, log_b_prev)
        return f_active_next, log_f_next, b_active_next, log_b_next
    [f_active, log_f_probs, b_active, log_b_probs], _ = theano.scan(
        step, sequences=[L, L[::-1, ::-1]], outputs_info=[np.int32(1), log_first, np.int32(1), log_first],
        mode=NanGuardMode(inf_is_error=True,big_is_error=True,nan_is_error=True,optimizer=None))
    idxs = T.arange(L.shape[1]).dimshuffle('x', 0)
    mask = (idxs < f_active.dimshuffle(0, 'x')) & (idxs < b_active.dimshuffle(0, 'x'))[::-1, ::-1]
    log_probs = log_f_probs + log_b_probs[::-1, ::-1] - L
    return log_probs, mask

**_The error occurs in ctc_update_log_p function here:_**
def ctc_update_log_p(skip_idxs, zeros, active, log_p_curr, log_p_prev):
    active_skip_idxs = skip_idxs[(skip_idxs < active).nonzero()]
    active_next = T.cast(T.minimum(
        T.maximum(
            active + 1,T.max(T.concatenate([active_skip_idxs, [-1]])) + 2 + 1),
        log_p_curr.shape[0]), 'int32')
    common_factor = T.max(log_p_prev[:active])
    p_prev = T.exp(log_p_prev[:active] - common_factor)
    _p_prev = zeros[:active_next]
    # copy over
    _p_prev = T.set_subtensor(_p_prev[:active], p_prev)
    # previous transitions
    _p_prev = T.inc_subtensor(_p_prev[1:], _p_prev[:-1])
    # skip transitions
    _p_prev = T.inc_subtensor(_p_prev[active_skip_idxs + 2], p_prev[active_skip_idxs])
    updated_log_p_prev = T.log(_p_prev) + common_factor
    log_p_next = T.set_subtensor(
        zeros[:active_next],
        log_p_curr[:active_next] + updated_log_p_prev
    )
    return active_next, log_p_next

**_You can see updated_log_p_prev = T.log(_p_prev) + common_factor has the problem. I doubt this is because some abnormal number from common_factor or _p_prev,  I have used T.clip to control them. However, it does not work and even trigger new errors. Could anyone tell me how to fix this issue?
Thank you very much!_**

Especially @patyork @fchollet

**Comment by sun-peach** [comment]
Is there anyone having the same problem?

**Comment by aayushee** [comment]
I also use a similar model to perform online handwriting recognition and the CTC loss keeps going to NaN while computation. 
If I keep tinkering with number of epochs, then sometimes the loss goes down and everything works. But the NaN loss occurs around 80 percent of the time I run the same script. Nan Guard Mode also doesn't help. And I have tried modifying model architecture, hyperparametets, etc but nothing handles the issue.
Any idea how to fix the issue ?
