### ISSUE TITLE
[API DESIGN REVIEW] K.size(), K.get_size(), K.count_params(), K.int_shape(), K.get_shape()

### ISSUE THREAD

**Issue by ozabluda** [keras-team/keras#8230]
1. `K.size(x)` returning the symbolic number of elements in the tensor, should be introduced for consistency with `tf.size(x)` and `np.ndarray.size`
2. K.count_params(x), returning static size, should be renamed to `K.get_size(x)`.  Then
   `K.get_size(x) <=> K.size(x)` will be analogous to
   `tf.Tensor.get_shape(x) <=> tf.Tensor.shape`. There is no `tf.get_size(x)`
3. `K.int_shape(x)`, returning static shape, should be renamed `K.get_shape(x)` for consistency with `tf.Tensor.get_shape(x)`
- [x] 4. `K.shape(x)` returning dynamic shape already exists and is consistent with `tf.shape(x)`
- [x] 5. `K.x.shape`  returning dynamic shape already exists and is consistent with `tf.Tensor.shape` and `np.ndarray.shape`

- [x] 6.  `K.get_variable_shape()` should be removed. Use `K.get_shape()` instead (https://github.com/fchollet/keras/pull/8276)

Other backends should be adjusted accordingly, as needed.

**Comment by ozabluda** [comment]
Pertinent PRs https://github.com/fchollet/keras/pull/3253, https://github.com/fchollet/keras/pull/3123

**Comment by fchollet** [comment]
> K.size(), returning the symbolic number of elements in the tensor, should be introduced for consistency with tf.size() and np.size().

Sure, ok.

> K.count_params(), returning static size, should be renamed to K.get_size(). Then K.get_size() <=> K.size() will be analogous to tf.get_shape() <=> tf.shape(). (TF doesn't have get_size()).

Why though? `count_params` is very explicit, and it's already there.

> K.get_variable_shape() should be removed. Use K.get_shape() instead.

It exists for historical reasons (it comes from Theano) and cannot be removed, in order to maintain backwards compatibility. But we can stop using it in the codebase.

**Comment by ozabluda** [comment]
>Why though? `count_params` is very explicit, and it's already there.

`count_params()` is indeed very explicit for layers and models (which have params, but not size or shape), and should be preserved for them, llike in
https://github.com/fchollet/keras/blob/master/keras/engine/topology.py#L1254

But here I am talking about "Keras variable or tensor" (which have size and shape, but not params) as in 
https://github.com/fchollet/keras/blob/master/keras/backend/tensorflow_backend.py#L867
https://github.com/fchollet/keras/blob/master/keras/backend/theano_backend.py#L346
https://github.com/fchollet/keras/blob/master/keras/backend/cntk_backend.py#L495

**Comment by ozabluda** [comment]
Before making anything drastic, trying to get API feedback at https://github.com/tensorflow/tensorflow/issues/14047
