### ISSUE TITLE
What is the difference between tf.clip_by_value and the max_norm constraint in keras?

### ISSUE THREAD

**Issue by noeagles** [keras-team/keras#8239]
I am doing a little project that involves the earth mover distance, so is there a difference between these two usages in terms of approximating this distance by a network?

**Comment by harshini-gadige** [comment]
Hi

This issue isn't related to a bug/enhancement/feature-request or other accepted types of issue.

To ask questions, please see the following resources :

https://keras.io/
https://keras.io/#support
https://gitter.im/Keras-io/Lobby

Thanks!
