### ISSUE TITLE
K.eye_like 

### ISSUE THREAD

**Issue by ergysr** [keras-team/keras#8262]
I have a `NxN` distance matrix `D` inside a loss function, and I would like to get the behavior:

`eye = K.eye_like(D)`

I have tried `eye = K.eye(K.get_variable_shape(D)[0])`. It returns the desired identity matrix outside the loss function. When I use it in the loss function I get the following error message: 

>   eye = K.eye(K.get_variable_shape(D)[0])
>   File "C:\Users\Ergys\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 657, in eye
>     return variable(np.eye(size), dtype, name)
>   File "C:\Users\Ergys\Anaconda3\lib\site-packages\numpy\lib\twodim_base.py", line 180, in eye
>     m = zeros((N, M), dtype=dtype)
> TypeError: 'NoneType' object cannot be interpreted as an integer

For now I hardcode the size of the matrix: 
```
N = 72 
eye = K.eye(N)
```
However I would like to infer `N` from `D`. Any suggestions would be appreciated.

**Comment by ozabluda** [comment]
If you use TF, can you check if PR https://github.com/fchollet/keras/pull/8246 fixes your problem?

**Comment by ergysr** [comment]
I am using TF. I substituted `return variable(np.eye(size), dtype, name)` with
```
   if dtype is None:
        dtype = floatx()
        tf_dtype = tf.as_dtype(dtype)

    return variable(tf.eye(size), dtype, name)
```
However there is a new error.

> 
>   File "C:/Users/Ergys/Documents/train/utils.py", line 153, in custom_loss
>     eye = K.eye(K.get_variable_shape(D)[0])
>   File "C:\Users\Ergys\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 661, in eye
>     return variable(tf.eye(size), dtype, name)
>   File "C:\Users\Ergys\Anaconda3\lib\site-packages\tensorflow\python\ops\linalg_ops.py", line 127, in eye
>     diag_shape = array_ops.concat((batch_shape, [diag_size]), 0)
>   File "C:\Users\Ergys\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1034, in concat
>     name=name)
>   File "C:\Users\Ergys\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 519, in _concat_v2
>     name=name)
>   File "C:\Users\Ergys\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 464, in apply_op
>     raise TypeError("%s that don't all match." % prefix)
> TypeError: Tensors in list passed to 'values' of 'ConcatV2' Op have types [int32, <NOT CONVERTIBLE TO TENSOR>] that don't all match.

I also tried casting to a float:

```
N = K.variable(value=K.get_variable_shape(D)[0], dtype='float32')
eye = K.eye(N)
```
but it still complains.

```
    N = K.variable(value=K.get_variable_shape(D)[0], dtype='float32')
  File "C:\Users\Ergys\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 321, in variable
    v = tf.Variable(value, dtype=_convert_string_dtype(dtype), name=name)
  File "C:\Users\Ergys\Anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 197, in __init__
    expected_shape=expected_shape)
  File "C:\Users\Ergys\Anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 248, in _init_from_args
    raise ValueError("initial_value must be specified.")
ValueError: initial_value must be specified.
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x000001CE3E79BBA8>>
Traceback (most recent call last):
  File "C:\Users\Ergys\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 587, in __del__
AttributeError: 'NoneType' object has no attribute 'TF_NewStatus'
```

**Comment by ozabluda** [comment]
what if you use `D.shape[0]` instead of `K.get_variable_shape(D)[0]`?

**Comment by ergysr** [comment]
It still complains:

> 
>   eye = K.eye(D.shape[0])
>   File "C:\Users\Ergys\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 661, in eye
>     return variable(tf.eye(size), dtype, name)
>   File "C:\Users\Ergys\Anaconda3\lib\site-packages\tensorflow\python\ops\linalg_ops.py", line 127, in eye
>     diag_shape = array_ops.concat((batch_shape, [diag_size]), 0)
>   File "C:\Users\Ergys\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1034, in concat
>     name=name)
>   File "C:\Users\Ergys\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 519, in _concat_v2
>     name=name)
>   File "C:\Users\Ergys\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 464, in apply_op
>     raise TypeError("%s that don't all match." % prefix)
> TypeError: Tensors in list passed to 'values' of 'ConcatV2' Op have types [int32, <NOT CONVERTIBLE TO TENSOR>] that don't all match.


`D.shape[0]` returns a dimension and `tf.eye` expects an integer. I tried as well `eye = K.eye(D.shape[0].value)` but it's still the same error (it works outside the loss function though).

**Comment by ozabluda** [comment]
Please, check my corrected comment above. You are using my original erroneous comment (maybe from your email). Your new error looks identical to the previous one (as it should).

**Comment by ergysr** [comment]
Even the corrected comment approach fails:

>   eye = K.eye(K.shape(D)[0])
>   File "C:\Users\Ergys\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 661, in eye
>     return variable(tf.eye(size), dtype, name)
>   File "C:\Users\Ergys\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 321, in variable
>     v = tf.Variable(value, dtype=_convert_string_dtype(dtype), name=name)
>   File "C:\Users\Ergys\Anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 197, in __init__
>     expected_shape=expected_shape)
>   File "C:\Users\Ergys\Anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 301, in _init_from_args
>     self._initial_value)
> ValueError: initial_value must have a shape specified: Tensor("eye_1/MatrixDiag:0", shape=(?, ?), dtype=float32)

**Comment by ozabluda** [comment]
Try passing validate_shape=False to tf.Variable() call here:
https://github.com/fchollet/keras/blob/master/keras/backend/tensorflow_backend.py#L379

Reference:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/variables.py#L256

**Comment by ergysr** [comment]
This breaks the behavior of other layers, e.g. MaxPooling.

**Comment by ozabluda** [comment]
This kind of stuff is why we can't just change `K.eye()`, and I don't think adding `K.eye_like()` to Keras is a good idea unless TF adds is (and even then it would simply extend `K.zeros|ones|eye` vs `K.zeros_like|ones_like|eye_like` insanity. I think that until this area of code/API is fixed, your best bet is to call `tf.eye()` directly, instead of `K.eye()`, especially since you don't need full generality and compatibility, like here (get rid of call to variable()):
https://github.com/fchollet/keras/blob/master/keras/backend/tensorflow_backend.py#L728

**Comment by ergysr** [comment]
Thanks nonetheless @ozabluda, I will continue to hardcode my matrix size `N` since there is no clean way to retrieve it automatically inside the loss.

**Comment by ozabluda** [comment]
You can try something like `tf.eye(D.shape[0])`, assuming `D` is a `tf.Tensor` or something.

**Comment by ymodak** [comment]
@ergysr  Is this still an issue?

**Comment by ergysr** [comment]
At the time of my last comment none of the suggested solutions were working. I haven't checked with the newer version.

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please test against the latest version of TF and check if the issue still persists. We will reopen the issue if required. Thanks!
