### ISSUE TITLE
Implementing FaceNet 'NN1' model using Keras.

### ISSUE THREAD

**Issue by purudpd** [keras-team/keras#8270]
I am trying to implement the FaceNet Deep Learning Model in Keras, specifically the non-inception based NN1 model. [https://arxiv.org/pdf/1503.03832.pdf](url)
![image](https://user-images.githubusercontent.com/18151538/32105612-b9c52bec-bb46-11e7-8c55-ffa47db9c348.png)

Using the functional programming api, I was able to write till the last pooling layer (pool4), but i am not able to understand the next layers **[ concat, fc1 with maxout, fc2 with maxout ]** Is the functionality to implement these functions available in Keras.

**Comment by monktastic** [comment]
I'm not sure why they need a concat layer (but there's a keras.layers.Concatenate). "FC" = "fully connected" = dense.
