### ISSUE TITLE
New API regarding CapsNet is needed!

### ISSUE THREAD

**Issue by noeagles** [keras-team/keras#8283]
Given the outstanding results in [Dynamic Routing Between Capsules](https://arxiv.org/pdf/1710.09829.pdf), I think for that

> Being able to go from idea to result with the least possible delay is key to doing good research.

APIs for building capsules and applying routing-by-agreement mechanism should be included in Keras.

**Comment by XifengGuo** [comment]
I implemented a demo with Keras. Check it out on 
https://github.com/XifengGuo/CapsNet-Keras

**Comment by tobegit3hub** [comment]
Thanks @XifengGuo  and it looks great.

Is that possible to add the helper functions into the core of Keras? And How?

**Comment by sarim-zafar** [comment]
@fchollet can you please incorporate these somehow... It will be much appreciated

**Comment by Neabfi** [comment]
Any news of CapsNet implementation in Keras ?
