### ISSUE TITLE
Ipython kernel dies while importing keras

### ISSUE THREAD

**Issue by A-Jatin** [keras-team/keras#8305]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [ y] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [ y] If running on TensorFlow, check that you are up-to-date with the latest version. The installation 

> instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

![image](https://user-images.githubusercontent.com/30106917/32187012-b61aecd6-bdc9-11e7-9ede-bc76ee8a1a66.png)

I'm getting an error  'kernel dies' whenever i try to import keras. 
Thanks ins advance.

**Comment by JohnLokke** [comment]
Hi there, had the same problem just now. I tried jupyther and spyder and got the same 'kernel died' message. I started spyder from the console in win 10, typing: spyder --show console
Now 'import keras' works well, no idea what the problem was

**Comment by A-Jatin** [comment]
Ok thanks mate , it's working fine on sypder now. But how to fix this on jupyter?

**Comment by JohnLokke** [comment]
Well, it seems to work with jupyter the same way:
Lauch console and type: 'jupyter notebook' , this should open jupyter. If you run 'Import keras' here, it should work fine, at least it did for me.
How to lauch a specific version of the notebook from a specific folder is described here:
http://jupyter-notebook-beginner-guide.readthedocs.io/en/latest/execute.html

**Comment by harshini-gadige** [comment]
@A-Jatin  - Is this still an issue ? Feel free to close if it no longer exists.

**Comment by bdevyansh** [comment]
try importing numpy before keras and tensorflow

**Comment by Derfaut** [comment]
Try to shutdown all running notebooks. Worked out for me
