### ISSUE TITLE
Model file reduced by 90MB after removing inputs

### ISSUE THREAD

**Issue by olalonde** [keras-team/keras#8312]
I use the following script to remove the 2 inputs from a siamese network and the output (a cosine distance layer).

```python
#!/usr/bin/env python

from dir.model import load_siamese_network
import sys


def load_siamese_network(filepath, include_distance=True):
    custom_objects = {
        'contrastive_loss': contrastive_loss
    }
    model = load_model(filepath, custom_objects=custom_objects)
    if not include_distance:
        # layer 0 and 1 are inputs
        tuned_model = model.layers[2]
        return tuned_model
    return model


src = sys.argv[1]
dst = sys.argv[2]
model = load_siamese_network(src, include_distance=False)

model.save(dst)
```

<img width="392" alt="screen shot 2017-10-30 at 16 13 53" src="https://user-images.githubusercontent.com/416585/32200140-5bfca3e8-bd8d-11e7-86b8-f5fad6471f89.png">

Here's the code I use to generate the siamese network from a base network: https://gist.github.com/aeec5b2a6efb1090375d4211aabbed6f

It appears to be working as expected but I was surprised to see that the saved file is twice smaller than the original one (90MB instead of 180MB). How could removing 2 inputs and a distance layer with no weights so dramatically reduce the file size?

Since this is a siamese network, both inputs share the same network + weights so removing an input shouldn't really affect the file size that much. That being said, it's possible that Keras isn't that smart about saving the model to disk and is duplicating the network weights for each input although they really are shared.

Is this what is happening? Or did I setup the siamese network wrong?

**Comment by Zygonie** [comment]
In my case, a 10 layers CNN is just 6MB whereas a 4 layers one is more than 670MB !!! I still dont understand

**Comment by fchollet** [comment]
In both cases, you can try using `model.summary()` to debug what is going on.

You can also inspect the contents of the HDF5 file using the Python h5py API.

**Comment by Zygonie** [comment]
`model.summary()` gives the right thing. I'll see what the h5py will tell me but when I tried with hdfview, I am said that the weights are null, however when Iload the model, weights are not null but have some values. I just hope it is not randomly initialized values. But a 675MB model with hdfview also tells me it has null weights...

**Comment by olalonde** [comment]
@fchollet is it possible that although the weights are shared for both inputs, keras is duplicating the weights in the hdf5 file?
