### ISSUE TITLE
Keras outputting wrong number of trainable parameters (GAN)

### ISSUE THREAD

**Issue by sachinruk** [keras-team/keras#8313]
I am trying to create a GAN below where I stack the generator and discriminator before I train it. However, the line `adversarial_model.layers[1].trainable = False` seems not to be affecting the trainable parameter count. The stranger thing is when I inspect `adversarial_model.trainable_weights` it only outputs the generator variables. So maybe a bug in the counting code?

Full code is available [here](https://github.com/sachinruk/deepschool.io/blob/master/Lesson%2021%20-%20Generative%20Adversarial%20Networks.ipynb):

```
adversarial_model = Sequential()
adversarial_model.add(generator)
adversarial_model.add(discriminator)
adversarial_model.layers[1].trainable = False
adversarial_model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])


adversarial_model.summary()
>>>
Layer (type)                 Output Shape              Param #   
=================================================================
sequential_4 (Sequential)    (None, 28, 28, 1)         903749    
_________________________________________________________________
sequential_5 (Sequential)    (None, 1)                 55489     
=================================================================
Total params: 959,238.0
Trainable params: 958,628.0
Non-trainable params: 610.0```

**Comment by rex-yue-wu** [comment]
This is because `adversarial_model.layers[1] = generator` is not a single layer, but a model. You need to get into `generator` and freeze its weights. I bet you realize this, but keras is not smart enough to provide the shortcut that setting the entire model to not trainable will automatically set to all of its layers not trainable.

**Comment by sachinruk** [comment]
@rex-yue-wu any chance you can comment here: https://stackoverflow.com/questions/47009451/keras-creating-a-gan. I got a feeling that they are one and the same problem.
