### ISSUE TITLE
multi_gpu_model changes the output layer names, interfering with fit_generator labeled output

### ISSUE THREAD

**Issue by IdoZach** [keras-team/keras#8339]
When using fit_generator, it's common to use
` yield ({'input': x0}, {'output': y})`
where 'output' is a named layer in the model. When using 'multi_gpu_model', the name changes, apparently to 'concatenate', raising an exception:
`ValueError: No data provided for "concatenate_1". Need data for each key in: ['concatenate_1']`

This can be replicated using the following code, adapted from the 'multi_gpu_model' example, by switching the flag 'bug=True'. We observe that the layers change:
`('output layers before multi_gpu_model', [<keras.layers.core.Dense object at 0x7f836c66f4d0>])
('output layers after multi_gpu_model', [<keras.layers.merge.Concatenate object at 0x7f836c61cfd0>])`

````
from os import environ
environ['CUDA_VISIBLE_DEVICES']='1,2'

from keras.utils import multi_gpu_model
from keras.models import Sequential, Model, Input, Layer
from keras.layers.core import Flatten, Dense, Dropout, Activation

import numpy as np

num_samples = 1000
height = 224
width = 224
num_classes = 1

bug = True

#~ dummy model
input = Input(shape=(height, width),name='input')
flat = Flatten()(input)
mid = Dense(10,name='middle')(flat)
output = Dense(1,name='output')(mid)

model = Model(inputs=[input], outputs=[output])

if bug:
    parallel_model = multi_gpu_model(model, gpus=2)
else:
    parallel_model = model

parallel_model.compile(loss='mse',optimizer='rmsprop')
print('output layers before multi_gpu_model',model.output_layers)
print('output layers after multi_gpu_model',parallel_model.output_layers)

#~ generate dummy data
x = np.random.random((num_samples, height, width))
y = np.random.random((num_samples, num_classes))

#~ dummy generator
def train_generator(X, Y, mb=16):
    while True:
        for i, t in enumerate(range(0, len(X), mb)):  # zip(imgs,scores)):
            maxt = min(t + mb, len(X))
            x0 = X[t:maxt]
            y = Y[t:maxt]
            yield ({'input': x0}, {'output': y})

#parallel_model.fit(x, y, epochs=20, batch_size=256)
parallel_model.fit_generator(train_generator(x,y), epochs=1, steps_per_epoch=10)
```

**Comment by christian-rauch** [comment]
This bug (renaming the output layers in `multi_gpu_model`) is also a problem when using multiple outputs and output specific loss functions given in a dictionary.

Is there a way to keep the original output names or at least, rename them afterwards?

**Comment by giorgiomondauto** [comment]
> This is fixed in the latest Keras. I copied and pasted the fix myself for an older version.

I can see this issue was closed but I am still getting the same issue with keras 2.5
