### ISSUE TITLE
What is K.function ? how do it passed to GPU ? what is there behind the scene ?

### ISSUE THREAD

**Issue by stavBodik** [keras-team/keras#8347]
What is K.function ? how do it passed to GPU ? what is there behind the scene ?

Thanks !

**Comment by harshini-gadige** [comment]
Hi

This issue isn't related to a bug/enhancement/feature-request or other accepted types of issue.

To ask questions, please see the following resources :

https://keras.io/
https://keras.io/#support
https://gitter.im/Keras-io/Lobby

Thanks!

If you think I made a mistake, please open another issue.
