### ISSUE TITLE
Randomly resize images at run time in Image datagenerator

### ISSUE THREAD

**Issue by ghost** [keras-team/keras#8357]
Can the image data generator handle the random resizing of the input dynamically, meaning, resize the input to one of the given scales like [256,384, 512, 680..]

Most of the codes i checked does  the resizing externally before passing to the image datagenerator. 

The closest one i came across is the 'preprocessing_function' argument in the ImageDataGenerator requires the output tensor to be of same shape of input tensor. Is there a simple implementation to circumvent the problem.

**Comment by harshini-gadige** [comment]
Request you to resubmit a question by filling all the information asked in[ this template.](https://github.com/keras-team/keras/issues/new/choose). Feel free to close if it no longer exists.
