### ISSUE TITLE
flow_from_directory yields batch with incorrect size

### ISSUE THREAD

**Issue by justinledford** [keras-team/keras#8358]
If the number of samples % batch_size != 0, flow_from_directory will return a batch with size != batch_size. For example with 7 samples and batch size of 4, the iterator yields a batch of 4, then a batch of 3.

The docs say that flow_from_directory will loop over data indefinitely (in batches), but should it instead loop over samples so that the batch size is consistent? I would be happy to open a PR for this.

Or maybe at least a warning should be given stating that samples % batch_size != 0?

There is [another issue](https://github.com/fchollet/keras/issues/5406) referencing this issue but it has been stale since August.

**Comment by ozabluda** [comment]
This is the expected behavior, consistent throughout Keras. How else would you ever get those 3 samples?

**Comment by justinledford** [comment]
I agree it makes sense that those last 3 samples shouldn't be skipped, but since the generator is looping indefinitely over all the samples, wouldn't it make sense to place another sample with those last 3 to make a batch of 4?

With architectures expecting a fixed batch size, this can cause problems at the end of an epoch, for example I have been training a net on an image set of ~80K images that crashed after hours of training because the batch size was incorrect.

**Comment by ozabluda** [comment]
Sometimes it would make sense, but not always. It would also contradict a commonly understood definition of epoch.

**Comment by BobNobrain** [comment]
Maybe it should show some kind of warning message in this case?

**Comment by ruifengma** [comment]
I have this issue while using flow from directory which I use batch_size = 32, but in generator, there are few batch samples with batch_size = 9
