### ISSUE TITLE
random_zoom() does not zoom x & y proportionally

### ISSUE THREAD

**Issue by aupilot** [keras-team/keras#8369]
Hi,

It seems that random_zoom() makes two separate zoom rates for x and y, which causes distortion rather than zooming. 

https://github.com/fchollet/keras/blob/master/keras/preprocessing/image.py
line 165

`zx, zy = np.random.uniform(zoom_range[0], zoom_range[1], 2)`

should not it be instead:
`zx = zy = np.random.uniform(zoom_range[0], zoom_range[1])`

Cheers
Kirill Makukhin

**Comment by ozabluda** [comment]
This is intentional, and it was like that from the every first Keras public release. I think some way of  preserving aspect ratio is warranted, but I'd rather wait for Tensorflow API and adopt it. Can anyone point to such or a discussion of such?
