### ISSUE TITLE
Modifying output_shape, but not using

### ISSUE THREAD

**Issue by anirudt** [keras-team/keras#8370]
Why is output_shape modified here, though after which it isn't used anywhere?

https://github.com/fchollet/keras/blob/612f5307b962fb140106efcc50932c292630fda3/examples/variational_autoencoder_deconv.py#L87

I wanted to know if there is a special reason we are doing this.

**Comment by harshini-gadige** [comment]
Hi

This issue isn't related to a bug/enhancement/feature-request or other accepted types of issue.

To ask questions, please see the following resources :

https://keras.io/
https://keras.io/#support
https://gitter.im/Keras-io/Lobby

Thanks!

If you think I made a mistake, please open another issue.
