### ISSUE TITLE
multi_gpu_model doesn't work with stateful models

### ISSUE THREAD

**Issue by visionscaper** [keras-team/keras#8397]
Background:
 - Keras 2.0.9, released three days ago, there seem to be no relevant changes after this release
 - Tensorflow 1.2 

I'm working on a **stateful** stacked RNN model, using the new `CuDNNGRU` as recurrent layers (although I don't think the type of recurrent layer is relevant for this issue).

Applying the `multi_gpu_model` utility results in the following error when trying to train the parallelised model:

    tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [256,75,39] vs. [512,75,39] 	
        [[Node: training/Adam/gradients/loss/concatenate_1_loss/mul_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _class=["loc:@loss/concatenate_1_loss/mul"], _device="/job:localhost/replica:0/task:0/gpu:0"](training/Adam/gradients/loss/concatenate_1_loss/mul_grad/Shape, training/Adam/gradients/loss/concatenate_1_loss/mul_grad/Shape_1)]]
        [[Node: replica_1/sequential_1/dense_1/truediv/_473 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:1", send_device_incarnation=1, tensor_name="edge_3032_replica_1/sequential_1/dense_1/truediv", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

For stateful models it is compulsory to specify the `batch_input_size` in the first layer, this seems to hardwire the batch_size throughout the model, likely resulting in the above error: 

    model.add(InputLayer(
            batch_input_shape=(batch_size, max_seq_length, num_dim)))

This can be seen in the summary of the parallelised **stateful** model:

```
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_1 (InputLayer)            (256, 75, 39)        0                                            
__________________________________________________________________________________________________
lambda_1 (Lambda)               (256, 75, 39)        0           input_1[0][0]                    
__________________________________________________________________________________________________
lambda_2 (Lambda)               (256, 75, 39)        0           input_1[0][0]                    
__________________________________________________________________________________________________
sequential_1 (Sequential)       (256, 75, 39)        7524903     lambda_1[0][0]                   
                                                                 lambda_2[0][0]                   
__________________________________________________________________________________________________
concatenate_1 (Concatenate)     (512, 75, 39)        0           sequential_1[1][0]               
                                                                 sequential_1[2][0]               
==================================================================================================
Total params: 7,524,903
Trainable params: 7,524,903
Non-trainable params: 0
__________________________________________________________________________________________________
```  

When I make my model **NOT stateful**, I'm allowed to state the `batch_input_size` without a hardcoded batch size:

    model.add(InputLayer(
            batch_input_shape=(None, max_seq_length, num_dim)))

This works fine, no error is given and both of my GPUs are used.

The summary of the the parallelised *NOT stateful* model:

```
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_1 (InputLayer)            (None, 75, 39)       0                                            
__________________________________________________________________________________________________
lambda_1 (Lambda)               (None, 75, 39)       0           input_1[0][0]                    
__________________________________________________________________________________________________
lambda_2 (Lambda)               (None, 75, 39)       0           input_1[0][0]                    
__________________________________________________________________________________________________
sequential_1 (Sequential)       (None, 75, 39)       7524903     lambda_1[0][0]                   
                                                                 lambda_2[0][0]                   
__________________________________________________________________________________________________
concatenate_1 (Concatenate)     (None, 75, 39)       0           sequential_1[1][0]               
                                                                 sequential_1[2][0]               
==================================================================================================
Total params: 7,524,903
Trainable params: 7,524,903
Non-trainable params: 0
__________________________________________________________________________________________________
```

I've tried a few workarounds but didn't get the parallelised stateful model to work.

**Is this a bug or is there a way to make `multi_gpu_model` work with stateful models?**

**Comment by dbsevenit** [comment]
I am having the same issue when trying to train a stateful LSTM model.
I use Keras 2.0.9 along with Tensorflow 1.4.

**Comment by cna274** [comment]
I am having same problem. I believe; (copied from keras website) **stateful: Boolean (default False). If True, the last state for each sample at index i in a batch will be used as initial state for the sample of index i in the following batch**. Index i in each batch that is sent to GPUs is not matching. I was wondering if tensorflow has same problem ?

**Comment by visionscaper** [comment]
@cna274 I don't think this is the issue, the batches get sliced in the same way (distributed among the different GPUs in the same way) for each iteration. So, index i of a sub-batch on some GPU k, remains the same with every new sub-batch. Agreed?

**Comment by visionscaper** [comment]
@cna274 Further diving in to the `multi_gpu_model` code made me realise that likely all the replicated models share the same state: the model is not replicated in the sense that a new graph is build. so in that case you would be right, unfortunately.

**Comment by visionscaper** [comment]
I just published an experimental utility, [stateful_multi_gpu](https://github.com/visionscaper/stateful_multi_gpu). To make this utility I adapted the original `multi_gpu_model` source.

It at least seems to work with simple models. I still need to verify if training actually works correctly, but I think it will. I would also like to try more complex models. 

I'm interested to hear if this utility works for anyone looking for a solution for training stateful models on multiple GPUs.

@fchollet I'm also very interested to hear if you also think this could work in general?

The utility is based on the following assumptions:

 * Each model replica maintains its own state
 * Batches can deterministically be split over multiple GPUs:  
    - each sub-batch is always processed on the same GPU,
    - outputs from the different replica's are always combined in the same, correct, order,
    - samples is sub-batches always maintain their order

As a service to the reader a bit more explanation of how to use the util (from the README):

> To make stateful models in Keras you need to provide the batch size you are using.  
`stateful_multi_gpu()` ensures that the right batch size is used throughout the model.

> To use this utility function you need to create a `inputs_generator` method that can make 
inputs for your model, for any batch size, and a `model_generator` method that can make
your model for any batch size.

> For instance, as follows:

```python
def inputs_generator(batch_size):
    rnn_input = Input(
        name="rnn-input-%d" % batch_size,
        batch_shape=(batch_size, seq_len, num_symbols))

    return rnn_input
```

```python
def model_generator(batch_size):
    inputs = inputs_generator(batch_size)

    layer_output = RNNLayer(
        state_size,
        stateful=stateful_model,
        return_sequences=True)(inputs)
    outputs = TimeDistributed(Dense(num_classes))(layer_output)

    return Model(inputs=inputs, outputs=outputs)
```

> `stateful_multi_gpu` uses these generator methods to create model inputs that expect batch size `batch_size` and model replica's (one per GPU) that expect 
batch size `batch_size` // `num_gpus`. E.g.:

```python
parallel_model = stateful_multi_gpu(inputs_generator, model_generator, training_batch_size, num_gpus)
```

Below a summary of a sample two GPU model, created with `stateful_multi_gpu`. 
Notice that the batch sizes are correct for main input and output, and for the replicated model:

```
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
rnn-input-128 (InputLayer)      (128, 30, 50)        0                                            
__________________________________________________________________________________________________
slice_batch_1 (SliceBatch)      (64, 30, 50)         0           rnn-input-128[0][0]              
__________________________________________________________________________________________________
slice_batch_2 (SliceBatch)      (64, 30, 50)         0           rnn-input-128[0][0]              
__________________________________________________________________________________________________
model_1 (Model)                 (64, 30, 10)         238346      slice_batch_1[0][0]              
                                                                 slice_batch_2[0][0]              
__________________________________________________________________________________________________
concatenate_1 (Concatenate)     (128, 30, 10)        0           model_1[1][0]                    
                                                                 model_1[2][0]                    
==================================================================================================
Total params: 238,346
Trainable params: 238,346
Non-trainable params: 0
__________________________________________________________________________________________________
```

**Comment by dolaamon2** [comment]
I wrote a multi_gpu_model to support stateful RNN model
[link](https://github.com/dolaamon2/statefulLSTMwithGPU)

**Comment by Ajk4** [comment]
I used to have the same problem. Trying to make work it was huge pain for me. In the end I can recommend using https://github.com/uber/horovod - horovod was something that finally worked for me.

**Comment by flxw** [comment]
Hi @dolaamon2  or @visionscaper! I am planning to use Multi GPU model training in my thesis and have come upon this bug. Have you tested your solutions further and deem them fit for use?
My network architecture uses two LSTM layers after concatenating the inputs of several Embeddings.

**Comment by dolaamon2** [comment]
> Hi @dolaamon2 or @visionscaper! I am planning to use Multi GPU model training in my thesis and have come upon this bug. Have you tested your solutions further and deem them fit for use?
> My network architecture uses two LSTM layers after concatenating the inputs of several Embeddings.

Hi @flxw   I test some codes as something in your comment. [(#9178)](https://github.com/keras-team/keras/issues/9178).  This code is functioning properly with my patch [(link)](https://github.com/dolaamon2/statefulLSTMwithGPU). I think your complete code should can be executed in the same way. Can you try it? And multi_gpu_model only supports data parallelism so your  batch_size must be greater than the GPU count.  
```
from keras.utils.training_utils import multi_gpu_model
from keras.layers import *
from keras.models import *
import multi_gpu_utils2 as multi_gpu_utils
import os

os.environ["CUDA_VISIBLE_DEVICES"]="1,4,5,6"
import multi_gpu_utils2 as multi_gpu_utils

#set batch_size = 4
model_inputs = [Input(batch_shape=(4,32,2)),Input(batch_shape=(4,32,2))]
#sequence_embedding =
models = model_inputs
main_output = concatenate(models, axis=2)
print(main_output.shape)
main_output = LSTM(25*32, batch_input_shape=(4,), stateful=True)(main_output)
print(main_output.shape)
# main_output = LSTM(25*32, batch_input_shape=(4,25*32), stateful=True)(main_output)

# after LSTM has learned on the sequence, bring in the SP2/PFS features, like in Shibatas paper
#main_output = concatenate([main_output, sequence_embedding])
main_output = Dense(20*32, activation='relu', name='dense_join')(main_output)
#main_output = Dense(len(feature_dict["concept:name"]["to_int"]), activation='sigmoid', name='dense_final')(main_output)
main_output = Dense(10, activation='sigmoid', name='dense_final')(main_output)
ngpus = 4
full_model = Model(inputs=model_inputs, outputs=[main_output])
full_model = multi_gpu_utils.multi_gpu_model(full_model, gpus=ngpus)
full_model.compile(loss='categorical_crossentropy', optimizer='adam')
```

**Comment by dolaamon2** [comment]
Hi @flxw   I test some codes as something in your comment. [(#9178)](https://github.com/keras-team/keras/issues/9178).  This code is functioning properly with my patch [(link)](https://github.com/dolaamon2/statefulLSTMwithGPU). I think your complete code should can be executed in the same way. Can you try it? And multi_gpu_model only supports data parallelism so your  batch_size must be greater than the GPU count.  
```
from keras.utils.training_utils import multi_gpu_model
from keras.layers import *
from keras.models import *
import multi_gpu_utils2 as multi_gpu_utils
import os

os.environ["CUDA_VISIBLE_DEVICES"]="1,4,5,6"
import multi_gpu_utils2 as multi_gpu_utils

#set batch_size = 4
model_inputs = [Input(batch_shape=(4,32,2)),Input(batch_shape=(4,32,2))]
#sequence_embedding =
models = model_inputs
main_output = concatenate(models, axis=2)
print(main_output.shape)
main_output = LSTM(25*32, batch_input_shape=(4,), stateful=True)(main_output)
print(main_output.shape)
# main_output = LSTM(25*32, batch_input_shape=(4,25*32), stateful=True)(main_output)

# after LSTM has learned on the sequence, bring in the SP2/PFS features, like in Shibatas paper
#main_output = concatenate([main_output, sequence_embedding])
main_output = Dense(20*32, activation='relu', name='dense_join')(main_output)
#main_output = Dense(len(feature_dict["concept:name"]["to_int"]), activation='sigmoid', name='dense_final')(main_output)
main_output = Dense(10, activation='sigmoid', name='dense_final')(main_output)
ngpus = 4
full_model = Model(inputs=model_inputs, outputs=[main_output])
full_model = multi_gpu_utils.multi_gpu_model(full_model, gpus=ngpus)
full_model.compile(loss='categorical_crossentropy', optimizer='adam')
```

**Comment by dolaamon2** [comment]
> Hi @dolaamon2 or @visionscaper! I am planning to use Multi GPU model training in my thesis and have come upon this bug. Have you tested your solutions further and deem them fit for use?
> My network architecture uses two LSTM layers after concatenating the inputs of several Embeddings.


Hi @flxw   I test some codes as something in your comment. [(#9178)](https://github.com/keras-team/keras/issues/9178).  This code is functioning properly with my patch [(link)](https://github.com/dolaamon2/statefulLSTMwithGPU). I think your complete code should can be executed in the same way. Can you try it? And multi_gpu_model only supports data parallelism so your  batch_size must be greater than the GPU count.  
```
from keras.utils.training_utils import multi_gpu_model
from keras.layers import *
from keras.models import *
import multi_gpu_utils2 as multi_gpu_utils
import os

os.environ["CUDA_VISIBLE_DEVICES"]="1,4,5,6"
import multi_gpu_utils2 as multi_gpu_utils

#set batch_size = 4
model_inputs = [Input(batch_shape=(4,32,2)),Input(batch_shape=(4,32,2))]
#sequence_embedding =
models = model_inputs
main_output = concatenate(models, axis=2)
print(main_output.shape)
main_output = LSTM(25*32, batch_input_shape=(4,), stateful=True)(main_output)
print(main_output.shape)
# main_output = LSTM(25*32, batch_input_shape=(4,25*32), stateful=True)(main_output)

# after LSTM has learned on the sequence, bring in the SP2/PFS features, like in Shibatas paper
#main_output = concatenate([main_output, sequence_embedding])
main_output = Dense(20*32, activation='relu', name='dense_join')(main_output)
#main_output = Dense(len(feature_dict["concept:name"]["to_int"]), activation='sigmoid', name='dense_final')(main_output)
main_output = Dense(10, activation='sigmoid', name='dense_final')(main_output)
ngpus = 4
full_model = Model(inputs=model_inputs, outputs=[main_output])
full_model = multi_gpu_utils.multi_gpu_model(full_model, gpus=ngpus)
full_model.compile(loss='categorical_crossentropy', optimizer='adam')
```

**Comment by douglas125** [comment]
There seems to be a problem there indeed. Same thing here using CuDNNLSTM.

**Comment by bjourne** [comment]
Do you need the model to the stateful during training? If not, then one workaround is to create a stateless model that is used during training and a stateful one used during inference. Usually inference isn't as computationally expensive as training so it doesn't matter if that runs on the cpu and not the gpu.
