### ISSUE TITLE
Change layer configuration after model definition

### ISSUE THREAD

**Issue by alxy** [keras-team/keras#8413]
I try to change a layer configuration (in this example its regularizer) after the model definition, but before I call the ``compile()`` function. Specifically, I want to add some regularization to keras application models. Consider the following code:

```
base_model = InceptionV3(input_shape=(150, 150, 3), weights='imagenet', include_top=False, pooling='avg')

for layer in base_model.layers:
        if type(layer).__name__ != 'Conv2D':
            continue

        layer.kernel_regularizer = ortho(0.01)

base_model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])
```

I use a custom regularizer here and monitor if it is actually called, however it is not the case. Whenever I compile the model, it calls ``__init__()`` on the regularizer, but ``__call__()`` is never beeing executed. Am I doing something obviously wrong? Setting the ``trainable`` parameter of certain layer of this model does work very well, however setting the ``kernel_regularizer`` does not appear to have any effect at all.

I am using the current keras version (2.0.9).

**Comment by alexhernandezgarcia** [comment]
I have a similar issue, so I'd be interested in knowing how to solve this. A hacky workaround is saving the model in disk and loading it again.

**Comment by samra-irshad** [comment]
similar issue, can't set layer attribute (i.e., kernel_initializer) after model definition
