### ISSUE TITLE
custom loss function when using pretrained model

### ISSUE THREAD

**Issue by jt827859032** [keras-team/keras#8424]
Hi,
   I got an error when using my own loss function.  My net is to produce an RGB image. So I wanna use the pretrained VGG-16 net to extract feature map and compute the 'mse' between predicted image and target image. 
   Here is my code:
   ```python
def VGGloss(y_pred, y_true):  
        vggmodel = VGG16(include_top=False)  
        f_p = vggmodel.predict(y_pred)  
        f_t = vggmodel.predict(y_true)  
        return K.mean(K.square(f_p - f_t)) 
 ```
  and  the error logs:
```
  File "K:/codes/code_demo/demo.py", line 241, in VGGloss
    f_p = vggmodel.predict(y_pred)
  File "I:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 1748, in predict
    verbose=verbose, steps=steps)
  File "I:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 1290, in _predict_loop
    batches = _make_batches(num_samples, batch_size)
  File "I:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 384, in _make_batches
    num_batches = int(np.ceil(size / float(batch_size)))
TypeError: unsupported operand type(s) for /: 'Dimension' and 'float'
```
could someone tell me how to use pre-trained model to compute a custom loss ?

**Comment by sebasvega95** [comment]
Hello :blush: 

I had the same error when trying to implement the perceptual loss described in [this paper](https://arxiv.org/abs/1603.08155). My code is similar to what you're showing. I solved this issue by doing something like

```python
def VGGloss(y_true, y_pred):  # Note the parameter order
     vggmodel = VGG16(include_top=False)  
     f_p = vggmodel(y_pred)  
     f_t = vggmodel(y_true)  
     return K.mean(K.square(f_p - f_t)) 
```

I don't know the technical details, but this is similar to using the [functional API of Keras](https://keras.io/getting-started/functional-api-guide/). Hope this helps!

**Comment by charlesverdad** [comment]
You may want to move the model declaration outside of the function like so:

```
vggmodel = VGG16(include_top=False)
def VGGloss(y_true, y_pred):  # Note the parameter order
     f_p = vggmodel(y_pred)  
     f_t = vggmodel(y_true)  
     return K.mean(K.square(f_p - f_t)) 
```
An alternative to this custom loss function method is to concatenate the vgg16 model at the end of your model, make it untrainable, and use the built-in 'mse' loss function, and call fit on the full model. (As described in https://stackoverflow.com/questions/43914931/vgg-perceptual-loss-in-keras). I'm not sure which one is more efficient though.

**Comment by mrgloom** [comment]
@charlesverdad Why we don't need to make `VGG16` not trainable in this `VGGloss` example?
