### ISSUE TITLE
importing ImageDataGenerator will occupy all the GPU memory

### ISSUE THREAD

**Issue by EncodeTS** [keras-team/keras#8429]
When run `from keras.preprocessing.image import ImageDataGenerator` in keras 2.0.9, it will occupy all the GPU memory, but in 2.0.8 it doesn't occupy memory at all.

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by pstalidis** [comment]
As per #1538  try to use tf code to set GPU before loading any module of the keras such as:

 ```
-------------------------- set gpu using tf ---------------------------
 import tensorflow as tf
 config = tf.ConfigProto()
 config.gpu_options.allow_growth = True
 session = tf.Session(config=config)
 -------------------  start importing keras module ---------------------
from keras.preprocessing.image import ImageDataGenerator
 import keras......
```

**Comment by datumbox** [comment]
There was a bug on 2.0.9 that caused the accidental creation of a TF session during the import of any keras class. This is now fixed on master. A hotfix should be released shortly but for now you can just install with pip the master branch.
