### ISSUE TITLE
Attach a LSTM layer to a conv layer output, dimension mismatch?

### ISSUE THREAD

**Issue by Doodle1106** [keras-team/keras#8442]
Hi,

I tried to feed my conv layer output with size [None, 12, 8, 1024]  to a LSTM layer,  and I tried to use ConvLSTM2D but it said the input dimension should be 7 while my conv output is 4,  apparently I need an extra dimension for time. Is there any workaround so that I don't need to add a time dimension?
 
-----------update-------------------
Now I have a train set with size [None, time, 480, 752, 1] where time = 2 in my case; my label set is of size [None, time, 7] where 7 stands for a vector of dimension 7. What I am trying to achieve is to train a CNN+LSTM model where the output of CNN can provide higher level features to LSTM, and I use a two layer LSTM to generate an output of 7 dimensional vector. I tried my configuration below but got an error.
Following is my model.summary and error, 
_________________________________________________________________
Layer (type)                 Output Shape              Param  
-------------------------------------------------------------------------------------------------------
time_distributed_1 (TimeDist (None, 2, 240, 376, 64)   3200      
_________________________________________________________________
time_distributed_2 (TimeDist (None, 2, 120, 188, 128)  204928    
_________________________________________________________________
time_distributed_3 (TimeDist (None, 2, 60, 94, 256)    819456    
_________________________________________________________________
time_distributed_4 (TimeDist (None, 2, 60, 94, 256)    590080    
_________________________________________________________________
time_distributed_5 (TimeDist (None, 2, 30, 47, 512)    1180160   
_________________________________________________________________
time_distributed_6 (TimeDist (None, 2, 30, 47, 512)    2359808   
_________________________________________________________________
time_distributed_7 (TimeDist (None, 2, 15, 24, 512)    2359808   
_________________________________________________________________
time_distributed_8 (TimeDist (None, 2, 15, 24, 512)    2359808   
_________________________________________________________________
time_distributed_9 (TimeDist (None, 2, 8, 12, 1024)    4719616   
_________________________________________________________________
conv_lst_m2d_1 (ConvLSTM2D)  (None, 2, 6, 10, 64)      2507008   
_________________________________________________________________
conv_lst_m2d_2 (ConvLSTM2D)  (None, 4, 8, 32)          110720    
_________________________________________________________________
conv2d_10 (Conv2D)           (None, 2, 6, 1)           289       
_________________________________________________________________
flatten_1 (Flatten)          (None, 12)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 7)                 91        
--------------------------------------------------------------------------------------------------------
Total params: 17,214,972
Trainable params: 17,214,972
Non-trainable params: 0
_________________________________________________________________

The error I got was
ValueError: Error when checking target: expected dense_1 to have 2 dimensions, but got array with shape (2, 2, 7)

I would appreciate if anyone can help me out, thanks for help.
SHR

**Comment by ceteke** [comment]
Why do you use LSTM if your data is not sequential?

One workaround may be reshaping your data such that there will be only 1 time step.

**Comment by Doodleshr** [comment]
@ceteke My understanding on the problem was wrong and I've decided to add a time axis,  now my input data to Conv layers would be of the shape [num_samples, time, col, row, channels], but the input to the Conv layer shouldn't contain the time axis, should it?  So my problem is how to feed this type of data to Conv layer. Any help would be appreciated, thanks.

**Comment by Doodleshr** [comment]
@ceteke Thanx for the reply, now my problem is the dimension mismatch...

**Comment by directcsd** [comment]
Hi, I have similar issue with the LTSM layer and I think the dimension mismatch is a generic problem, not only in this case.

I have exact the same problem when I tried to change the char-rnn example from @fchollet to match the model structure from the sample from @mineshmathew

I mean, change:

model = Sequential()
model.add(LSTM(128, input_shape=(maxlen, len(chars))))
model.add(Dense(len(chars)))
model.add(Activation('softmax'))

in https://github.com/fchollet/keras/blob/master/examples/lstm_text_generation.py

to:

model = Sequential()
model.add(LSTM(512, input_shape=(maxlen, len(chars)), return_sequences=True))
model.add(LSTM(512, return_sequences=True))
model.add(Dropout(0.2))
model.add(TimeDistributed(Dense(len(chars))))
model.add(Activation('softmax'))

as in https://github.com/mineshmathew/char_rnn_karpathy_keras/blob/master/char_rnn_of_karpathy_keras.ipynb

My notebooks with the errors are here: https://github.com/directcsd/Discord-Bot

**Comment by Doodleshr** [comment]
@directcsd Have you solved the problem yet? I recently discovered that tensorflow 1.4 has support for multi-dimensional LSTM, you can have a try if you want

**Comment by directcsd** [comment]
@Doodleshr I'm using TF 1.4.0 under Keras, but I though that Keras abstracted that for me. What you are proposing is to move the code to native TF? Or did I misunderstand you?
