### ISSUE TITLE
merge layer documentation and architecture  

### ISSUE THREAD

**Issue by shay86** [keras-team/keras#8450]
I built a project using (Merge, merge) layer once, and use share layer in another. The problem I can't find any documentation that explains how merge or share layer works like convolution or max-pooling layers.
I will be grateful if anyone can direct me or suggest some paper to me that helps me to understand how these layers work ???

**Comment by roya0045** [comment]
From the existing documentation and by reading the source code: Merge will take two input tensor and will combine them according to the defined operation, the operation may be of a mathematical nature such as addition, subtraction, getting the maximum or minimum value or can simply concatenate the data by agglomerating the two input tensor in a single one i.e.:  two array of dimensions [2,2] will become [4,2] or [2,4] depending on the axis of concatenation.

Also note that every mathematical operation is performed element-wise.
