### ISSUE TITLE
Model not predicting after loading model using `load_model`

### ISSUE THREAD

**Issue by sandeepnmenon** [keras-team/keras#8465]
I trained a model that takes in (512,512,3) images as input and makes predictions.
The model predicts as expected after training.
But after saving the model in a '.hdf5' format using the `ModelCheckpoint' callback while training, and loading the same using the `load_model` function. Now it gives the following error while running model.predict.

`ValueError: The model expects 5  arrays, but only received one array. Found: array with shape (1, 512, 512, 3)`

The above error is when I am passing one image to predict.

The model is given in this gist [https://gist.github.com/sandeepnmenon/023495c69a877980535a7bf2da1389fa](url)

Thank you

**Comment by roccolocko** [comment]
I have the same problem with this code:

```
model = load_model('model_advanced.h5', custom_objects={"ctcFunction":ctcFunction})

[X_test, y_test, _, _], _  = next(gen(1))
y_pred = model.predict(X_test)
```

Result:
`ValueError: The model expects 4  arrays, but only received one array. Found: array with shape (1, 170, 45, 3)`

**Comment by sandeepnmenon** [comment]
Did you find a solution? @roccolocko

**Comment by roccolocko** [comment]
Yes, Define a model which only recieves one parameter(X) and load the weights of the model you trained:

Model should look something like this:
`model = Model(inputs=input_tensor, outputs=x)`

And then use your trained model to load only the weights and set them to that model:
```
weights = load_model('model_advanced_2.h5', custom_objects={"ctcFunction":ctcFunction}).get_weights()
model.set_weights(weights)
```

After that you can use your new model the way you expected and it will take the info of the one you trained. Of course both models should have the same layers:
`y_pred = model.predict(X_test)`

**Comment by jalilahmed** [comment]
@roccolocko how are you able to tell which probability belongs to which class in y_pred array?

**Comment by roccolocko** [comment]
I don't use any probability in my functionality, in the prediction I get a 5 character string which is the expected result in my case.
Sorry that I can't be of any help.
