### ISSUE TITLE
CNTK backend for recurrent layers fails to recognize `unroll`

### ISSUE THREAD

**Issue by ml-pickle** [keras-team/keras#8484]
https://github.com/fchollet/keras/blob/master/keras/layers/recurrent.py#L1474

`if not kwargs.get('unroll') and (dropout > 0 or recurrent_dropout > 0):`

Causes dropout to be set to 0, even when unroll=True is passed.

Unroll is a named arg and not in kwargs.

**Comment by souptc** [comment]
Has add cntk support for the dropouts, so these check is removed. Please try to test with cntk v2.3.1 release, thanks.
