### ISSUE TITLE
Imagenet preprocess code: why not subtracting "mean pixels" in tf mode?

### ISSUE THREAD

**Issue by olalonde** [keras-team/keras#8487]
https://github.com/fchollet/keras/blob/2.1.1/keras/applications/imagenet_utils.py#L36

I'm a bit confused by the `preprocess_input` in `imagenet_utils.py`. It seems like in `tf` mode it just uses a mean of `255/2` instead of the empirical per-channel means that is used in Caffe mode: ` 103.939, 116.779, 123.68`. It also scales the pixel values to be between `[-1, 1]`, whereas the pixel values are not scaled at all in Caffe mode.  Is there a reason for this that I am missing?

**Comment by olalonde** [comment]
Ah, it appears that the `tf` mode was introduced specifically for the inception and mobilenet models: https://github.com/fchollet/keras/commit/0b3dc16b603a549a20f4a92447c79042fecd0c0b

I suppose other applications should use the default `caffe` mode.

**Comment by ztf-ucas** [comment]
@olalonde 
Hi! I want to know should I scale input pixels between -1 and 1 with tf backend when
I train model with imagenet weight? Or just preprocess like caffe model?
I am very confused what to this？
I I observed that the pretrained VGG weights are mostly decimal.Seem to the input range is (-1-1)?
