### ISSUE TITLE
Syntax error for LeakyReLU for no reason

### ISSUE THREAD

**Issue by RCfun** [keras-team/keras#8535]
Hi, I searched the internet, and I'm pretty sure the syntax of my code is same as what other's did. But it seems only me get this syntax error for LeakyReLU

Is anyone knows why?

```
from keras.layers.advanced_activations import LeakyReLU
model.add(Conv2D(192,(3,3),padding='same', activation='linear')
model.add(LeakyReLU(alpha=.1))
```

**Comment by myutwo150** [comment]
You're missing a right parenthesis at the end of the second line.
