### ISSUE TITLE
tensorboard callback doesn't support images with validation generators

### ISSUE THREAD

**Issue by paragon00** [keras-team/keras#8554]
it seems when using Tensorboard callback with validation generators, TensorBoard Images won't work properly. Following issue https://github.com/fchollet/keras/issues/3358 I got Tensorboard scalars working, but Images were still blank, like this-

![screen shot 2017-11-17 at 2 48 53 pm](https://user-images.githubusercontent.com/31834007/33107116-d2618f2c-cf89-11e7-8cee-6ba1bb50d7ea.png)

Is there a way to get tensorboard images working with validation generators?

**Comment by ahundt** [comment]
They're not actually blank I think those are model weights which are showing up as single pixel "images", if you scroll down you'll see other ones that are more varied.

That said, I'm not sure how useful this current tensorboard images callback is at the moment.

**Comment by saurabheights** [comment]
FYI: To display the images through callback, see https://stackoverflow.com/questions/52469866/displaying-images-on-tensorboard-through-keras/55856716#55856716
and using tensorboard visualization, it displays weights as images. Check https://github.com/chrisranderson/beholder plugin to get more info on why/how you can use visualization of convnet weights.
