### ISSUE TITLE
File path check for /examples/deep_dream.py

### ISSUE THREAD

**Issue by itssmutnuri** [keras-team/keras#8555]
Running the script with `python deep_dream.py <inputpath> <result_prefix>` checks the output result prefix only at the end. It'd be appropriate to do a simple check for the validity of the paths in the beginning because otherwise, any error would only come up after all the processing is done.

<img width="928" alt="screen shot 2017-11-22 at 10 38 20 am" src="https://user-images.githubusercontent.com/20726434/33110940-4fa3615e-cf71-11e7-8c21-9df69e2c82c3.png">

**Comment by x19990416** [comment]
may be you should check the file 'image.png' is exist or not

**Comment by itssmutnuri** [comment]
@x19990416 the file gets created by the code, and the mistake I did was naming my path wrong. It works fine otherwise. What I meant was to have a check of the validity of the paths given as arguments before doing all the processing. That would save a re-run of the entire code just because the output path has been written wrong.
