### ISSUE TITLE
ModelCheckpoint terminates the training process silently in Keras 2.0.8

### ISSUE THREAD

**Issue by tjliupeng** [keras-team/keras#8565]
Hi, Keras guys,

I use 3DConv to train image classifier. 2 ModelCheckpoint instances are defined: one for medels for each epoch; the other one is for the best model.

Before, I use Keras 2.0.6 and Tensorflow 1.2.1, the code runs well. Later, I reinstall the computer and install Keras 2.0.8 and Tensorflow 1.3.0. The code is broken. When the first epoch is finished,  the ModelCheckpoint callback terminates the fit_generator() function and the whole training program, and no any error message is output.

Then I downgrade the Keras and Tensorflow back to 2.0.6 and 1.2.1; the code works again.

Did any guys meet the similar issue before? Does the implementation of ModelCheckpoint has any change between 2.0.6 and 2.0.8?

Thanks
Alan

**Comment by nicolewhite** [comment]
Can you provide a code snippet to reproduce the issue?
