### ISSUE TITLE
Step_per_epoch variable gets overwritten in fit_generator

### ISSUE THREAD

**Issue by GertJanBraeckevelt** [keras-team/keras#8566]
The correct custom value gets displayed in the progress bar, but is silently overwritten by the size of the training dataset divided by the batch size.

**Comment by nicolewhite** [comment]
Can you show an example?

**Comment by JohnEstropia** [comment]
I'm seeing this as well. I downgraded to 2.0.9 for now. The provided `steps_per_epoch` seems to be overwritten by the number of default images (`len(generaror)`?)

**Comment by nicolewhite** [comment]
I believe this was fixed in https://github.com/fchollet/keras/commit/2f3edf96078d78450b985bdf3bfffe7e0c627169. You can either install the latest Keras from GitHub to get the fix or as you suggested downgrade to 2.0.9.

**Comment by GertJanBraeckevelt** [comment]
Thanks for the response!
