### ISSUE TITLE
Support of multiple-input for TimeDistributed?

### ISSUE THREAD

**Issue by hanfeisun** [keras-team/keras#8582]
This issue (https://github.com/fchollet/keras/issues/3057) discusses about a work-around to support multiple-input for TimeDistributed (Concatenate multiple input, and then split them out).

However, this work-around won't work at all if the dtype of multiple-input is different. For example, if input1 uses "int32" and input2 uses "float32", I can't concatenate them.

An example is pasted from that thread:
```

# input sentence
in_sentence = Input(shape=(MAX_LENGTH,), dtype='int32')
# additional sentence-level information (fixed length array - already "embedded")
in_info = Input(shape=(INFO_LENGTH,), dtype='float32')
# first layer (sentence-level)
# word embedding
embedded_sentence = Embedding(len(vocab) + 1,
                            EMBEDDING_DIM,
                            weights=[embedding_matrix],
                     trainable = False)(in_sentence)

recurrent_sentence = GRU(hidden_dim_1)(embedded_sentence)
recurrent_sentence_and_info = concatenate([recurrent_sentence, in_info])
encoded_model = Model([in_sentence, in_info], recurrent_sentence_and_info)

#second layer (document-level)
sequence_input = Input(shape=(MAX_SENTENCES, MAX_LENGTH), dtype='int32')
info_seq_input = Input(shape=(MAX_SENTENCES, INFO_LENGTH), dtype='float32')
seq_encoded = TimeDistributed(encoded_model)([sequence_input, info_seq_input])

# Encode entire sentence
seq_encoded = GRU(hidden_dim_2,return_sequences=True)(seq_encoded)

# Prediction
prediction = Dense(NUM_CLASSES, activation='softmax')(seq_encoded)
model = Model([sequence_input,info_seq_input], prediction)

```

This snippet can't work with TimeDistributed because TimeDistributed doesn't support using list as input. Moreover, the work-around won't work because `sequence_input` and `info_seq_input` have different dtype. Will there be any support of multiple-input for TimeDistributed ?

**Comment by janvdvegt** [comment]
I second this. I have a model that uses multiple inputs and want to weight share this as input for recurrent neural network structures. For a normal RNN I can pass multiple inputs directly without a problem and merge them within there, but if I want to time distribute a full model with multiple inputs it will not let me. The reason I want to use a model is that I'm interested in the interim model for one time step but also use the output for an aggregated result and I want to train both of them at the same time.

**Comment by cipher009** [comment]
I am also facing the same issue! I need to wrap my model in a TimeDistributed layer. No workaround for me too, as I cannot change the model's architecture. If I do so, I won't be able to load the pre-trained weights. Could anyone take a look, would be highly appreciated.

**Comment by cipher009** [comment]
Thank you @Ajk4, but I am currently working on Windows, and it seems not possible to use Horovod there(because of Open MPI).

**Comment by clavel87** [comment]
Hi! Any solution about it? I'm stack trying to do a herarchical LSTM with TimeDistributed but I keep getting some differents errors. I've tried the examples published here but I still doesn't work. Any help will be highly apreciated. 
Thanks
Yisel
