### ISSUE TITLE
ImageGenerator Distorting Image

### ISSUE THREAD

**Issue by singhns** [keras-team/keras#8596]
I am getting artifacts and distortions in many of the medical images im trying to augment.  Finally, I emptied out all of the transforms in the ImageGenerator, yet those artifacts are still present.

I've included the source image along with what was generated and the code that produces the problem.  Im on a mac, development environment is anaconda spyder.   This seems to happen on most images, but not all of them. 

Original
![149_resized](https://user-images.githubusercontent.com/643120/33247147-b6d72376-d2d0-11e7-8c94-364f40897816.jpg)

Generated
![149_0x3generated](https://user-images.githubusercontent.com/643120/33247144-b350a312-d2d0-11e7-8baa-2b7c0fb73cd1.jpeg)

```
testFile = "149_resized.jpg"
dirPath = IMAGEPATH +"/Resized/" +testFile
images = np.array([np.array(Image.open(dirPath))])
labels = [1]
datagen = ImageDataGenerator()
datagen.fit(images,seed=7)

for X_batch, y_batch in datagen.flow(images, labels,batch_size=32):
       newX = [255 - img for img in X_batch]
       break  # otherwise the generator would loop indefinitely
pyplot.imshow(newX[0])
```

- [ x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps
(im on version 2.08)

**Comment by maderafunk** [comment]
What is the reason for the "255 - ..." in
`newX = [255 - img for img in X_batch]`
?
Looks somehow to me that its a data type problem with uint8? E.g  a value of -1 becomes 254 in uint8, which might cause those artifacts.

**Comment by singhns** [comment]
It is something to do with the conversion.  I tried multiple conversions and the above without success.  Finally I made it newX = [0 - img for img in X_batch] and all is well. Sorry for posting it as an issue, though having more options on ImageGenerator to support BGR or RGB would be a great add.
