### ISSUE TITLE
Convert cifar10_cnn model to FCN Model

### ISSUE THREAD

**Issue by talhadar** [keras-team/keras#8600]
Hello,

I want to convert the cifar10_cnn model to FCN (Fully Convolutional Network) so i can run it efficiently and produce a heatmap.
Here is my progress so far using an original image with size (600, 600) and the receptive field is 32x32:
1. Running the model using a for loop on the full image produces the expected results but is slow
2. I attempted to convert the model into a FCN in the following manner:
```
model = Sequential()
model.add(Conv2D(32, (3, 3), padding='same', input_shape=(None, None, 3), name="conv2d_1"))
model.add(Activation('relu'))
model.add(Conv2D(32, (3, 3), name="conv2d_2"))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2), name="max_pooling2d_1"))
model.add(Dropout(0.25, name="dropout_1"))

model.add(Conv2D(64, (3, 3), padding='same', name="conv2d_3"))
model.add(Activation('relu'))
model.add(Conv2D(64, (3, 3), name="conv2d_4"))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2), name="max_pooling2d_2"))
model.add(Dropout(0.25, name="dropout_2"))
model.add(Conv2D(512, (9, 9), name="dense_1"))
model.add(Activation('relu'))
model.add(Conv2D(2, (1, 1), name="dense_2"))
model.add(SoftmaxMap(axis=-1))
```
This runs fast however the output image has significantly reduced the size
How do I apply the FCN such that the output result is equivalent to the for loop in size (600, 600) but
equivalent to FCN in performance?

Thank you

**Comment by brge17** [comment]
Look at the Caffe reference architecture: https://github.com/shelhamer/fcn.berkeleyvision.org/blob/master/voc-fcn8s/net.py

The model you have listed above is absolutely nothing like FCN at all.  You have no deconvolution layers in your network at all --> the receptive field is decreasing in size. In addition you have labeled conv layers as "dense_*"...

There are plenty of Keras repos with an FCN implementation.
