### ISSUE TITLE
Problems with multiple output in a cnn

### ISSUE THREAD

**Issue by Canseco10** [keras-team/keras#8611]
Hello guys,

I'm having trouble to getting my network to running.
I'm trying to pass an image to my convolutional neural network which should predict me 3 parameter. (a regression problem)
There is always a value error: 'The model expects 3 target arrays, but only received one array. Found: array with shape (32,3).'

Does somebody know how to fix that?

My ImageDataGenerator uses the  '.flow()' function with an amout of RGB images and as label an amount of the corresponding arrays with 3 parameter. Means for each image I've got 3 corresponding parameters.

**Comment by mpariente** [comment]
From the little information you give, I guess you have this problem when you call the `fit` method.
From the error message, I would tell you to pass the target arrays as a list. 

Do you really have several outputs? How does your `Model` call looks like?

**Comment by Canseco10** [comment]
```input = Input(shape=(img_width, img_height, 3))  conv = Conv2D(32(5,5) activation ='relu') 
pool1 = MaxPooling2D((2,2)) (conv1)
conv2 = Conv2D(64(5,5) activation ='relu') (pool1)
pool2= MaxPooling2D((2,2)) (conv2)
conv3 = Conv2D(128(5,5) activation ='relu') (pool2)
pool3 = MaxPooling2D((2,2)) (conv3)
conv4 = Conv2D(32(5,5) activation ='relu') (pool3)
pool4 = MaxPooling2D((2,2)) (conv4)
flatten = Flatten() (pool4)
dense = Dense(128, activation='relu') (flatten)
drop = Dropout(0.5) (dense)
dense1 = Dense(512, activation = 'relu') (drop)
drop1 = Dropout(0.5) (dense1)
param1 = Dense(1) (drop1)
param2 = Dense(2) (drop1)
param3 = Dense(3) (drop1)
model = Model(inputs= input , outputs=[param1, param2, param3])
model.compile(optimizer='rmsprop', loss =['mse', 'mse', 'mse'])
imageGenerator = ImageDataGenerator(rescale = 1./255, zoom_range = 0.2, horizontal_flip = True)
imageGenerator.fit(train) # train has a shape (n, img_width, img_height ,3)
train_generator = imageGenerator.flow(train, trainLabels) # train labels has a shape of (n, 1, 3)
model.fit_generator(train_generator , steps_per_epoch=len(train)/32, epochs = 10)
```

`ValueError: The model expects 3 target arrays, but only received one array. Found: array with shape(32,1,3)`

In fact per image I have got 3 parameters. And I want to train my network on several images with these parameters in order to predict the parameters for a test image. Maybe I'm passing a wrong shape for the labels to the flow function? 

I would be grateful if you could help me @mpariente

**Comment by mpariente** [comment]
If you have three parameters you want to predict, just call 
`params = Dense(3) (drop1)`  (think about which activity you want)
The layer will have 3 nodes, each of which will predict one parameter. 
The model you designed predicts 3 outputs : one of size 1, one of size 2 and one of size 3. That's not what you want to do.

**Comment by Canseco10** [comment]
Thank you, that solve it!
