### ISSUE TITLE
can not load_model() or load_from_json() if my model contains my own Layer

### ISSUE THREAD

**Issue by talorwu** [keras-team/keras#8612]
this is my code:
`from keras import backend as K
from keras.engine.topology import Layer
from keras.models import load_model
from keras.layers import Dense
from keras.models import Sequential,model_from_json
import numpy as np

class MyLayer(Layer):

    def __init__(self, output_dim, **kwargs):
        self.output_dim = output_dim
        super(MyLayer, self).__init__(**kwargs)

    def build(self, input_shape):
        # Create a trainable weight variable for this layer.
        self.kernel = self.add_weight(name='kernel',
                                      shape=(input_shape[1], self.output_dim),
                                      initializer='uniform',
                                      trainable=True)
        super(MyLayer, self).build(input_shape)  # Be sure to call this somewhere!

    def call(self, x):
        return K.dot(x, self.kernel)

    def compute_output_shape(self, input_shape):
        return (input_shape[0], self.output_dim)

model = Sequential()
model.add(Dense(32, input_shape=(784,)))
model.add(MyLayer(100))
#this is ok 
model.save('mode_test.h5')

#wrong
model = load_model('mode_test.h5')

json_string = model.to_json()

open('my_model_architecture.json', 'w').write(json_string)

model.save_weights('my_model_weights.h5')

model = model_from_json(open('my_model_architecture.json').read())

model.load_weights('my_model_weights.h5')`

the Error is:
ValueError: Unknown layer: MyLayer

**Comment by bdwyer2** [comment]
From the FAQ:


#### Handling custom layers (or other custom objects) in saved models

If the model you want to load includes custom layers or other custom classes or functions, 
you can pass them to the loading mechanism via the `custom_objects` argument: 

```python
from keras.models import load_model
# Assuming your model includes instance of an "AttentionLayer" class
model = load_model('my_model.h5', custom_objects={'AttentionLayer': AttentionLayer})
```

Alternatively, you can use a [custom object scope](https://keras.io/utils/#customobjectscope):

```python
from keras.utils import CustomObjectScope

with CustomObjectScope({'AttentionLayer': AttentionLayer}):
    model = load_model('my_model.h5')
```

Custom objects handling works the same way for `load_model`, `model_from_json`, `model_from_yaml`:

```python
from keras.models import model_from_json
model = model_from_json(json_string, custom_objects={'AttentionLayer': AttentionLayer})
```

**Comment by stevewyl** [comment]
@bmabey Thanks for the hints!
Still, have problems. I have two attention layer in my model, named as 'AttLayer_1' and 'AttLayer_2'.  
Attention is the custom layer class
`custom_ob = {'AttLayer1':Attention,'Attlayer2':Attention}`
`model = load_model('./model/HAN_20_5_201803062109.h5', custom_objects=custom_ob)`

`with CustomObjectScope(custom_ob):`
        `model = load_model('./model/HAN_20_5_201803062109.h5')`

Neither of two methods failed, return "Unknown layer: Attention"

**Comment by nielspetersen** [comment]
@stevewyl Is the Attention layer defined within the same file?

As far as I know you have to provide the module of the Attention layer, e.g.  `custom_layer.Attention`. 
This is analogue to the import statement at the beginning of the file.

**Comment by singhay** [comment]
It will error out when using ModelCheckpoint Callback

**Comment by SujathaSIyer** [comment]
@stevewyl I am facing the same issue too. Did you get any solution for the issue ?

**Comment by Monduiz** [comment]
I have a similar issue as well. I defined a custom layer like so:


    `class Attention(Layer):
        def __init__(self, step_dim,
                 W_regularizer=None, b_regularizer=None,
                 W_constraint=None, b_constraint=None,
                 bias=True, **kwargs):
        self.supports_masking = True
        self.init = initializers.get('glorot_uniform')

        self.W_regularizer = regularizers.get(W_regularizer)
        self.b_regularizer = regularizers.get(b_regularizer)

        self.W_constraint = constraints.get(W_constraint)
        self.b_constraint = constraints.get(b_constraint)

        self.bias = bias
        self.step_dim = step_dim
        self.features_dim = 0
        super(Attention, self).__init__(**kwargs)

    def build(self, input_shape):
        assert len(input_shape) == 3

        self.W = self.add_weight((input_shape[-1],),
                                 initializer=self.init,
                                 name='{}_W'.format(self.name),
                                 regularizer=self.W_regularizer,
                                 constraint=self.W_constraint)
        self.features_dim = input_shape[-1]

        if self.bias:
            self.b = self.add_weight((input_shape[1],),
                                     initializer='zero',
                                     name='{}_b'.format(self.name),
                                     regularizer=self.b_regularizer,
                                     constraint=self.b_constraint)
        else:
            self.b = None

        self.built = True

    def compute_mask(self, input, input_mask=None):
        return None

    def call(self, x, mask=None):
        features_dim = self.features_dim
        step_dim = self.step_dim

        eij = K.reshape(K.dot(K.reshape(x, (-1, features_dim)),
                        K.reshape(self.W, (features_dim, 1))), (-1, step_dim))

        if self.bias:
            eij += self.b

        eij = K.tanh(eij)

        a = K.exp(eij)

        if mask is not None:
            a *= K.cast(mask, K.floatx())

        a /= K.cast(K.sum(a, axis=1, keepdims=True) + K.epsilon(), K.floatx())

        a = K.expand_dims(a)
        weighted_input = x * a
        return K.sum(weighted_input, axis=1)

    def compute_output_shape(self, input_shape):
        return input_shape[0],  self.features_dim`

I load the model with : 

`load_model('model.h5', custom_objects={'Attention': Attention})`

I get this error:

`__init__() missing 1 required positional argument: 'step_dim'`

**Comment by jnorthrup** [comment]
i have seen this error posted in several places on the internet, and has been fixed in tensorflowjs but not keras or tf python.

my model is culled from early-stopping callback, im not saving it manually.  this appears to be common 

Traceback (most recent call last):
  File "/home/jim/mlcc-exercises/rejuvepredictor/stage4.py", line 175, in <module>
    custom_objects={'kernel_initializer':GlorotUniform}
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 225, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 458, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/usr/local/lib/python3.6/dist-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python3.6/dist-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/sequential.py", line 300, in from_config
    custom_objects=custom_objects)
  File "/usr/local/lib/python3.6/dist-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python3.6/dist-packages/keras/utils/generic_utils.py", line 147, in deserialize_keras_object
    return cls.from_config(config['config'])
  File "/usr/local/lib/python3.6/dist-packages/keras/layers/recurrent.py", line 2298, in from_config
    return cls(**config)
  File "/usr/local/lib/python3.6/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/keras/layers/recurrent.py", line 2178, in __init__
    implementation=implementation)
  File "/usr/local/lib/python3.6/dist-packages/keras/layers/recurrent.py", line 1841, in __init__
    self.kernel_initializer = initializers.get(kernel_initializer)
  File "/usr/local/lib/python3.6/dist-packages/keras/initializers.py", line 508, in get
    return deserialize(identifier)
  File "/usr/local/lib/python3.6/dist-packages/keras/initializers.py", line 503, in deserialize
    printable_module_name='initializer')
  File "/usr/local/lib/python3.6/dist-packages/keras/utils/generic_utils.py", line 138, in deserialize_keras_object
    ': ' + class_name)
ValueError: Unknown initializer: GlorotUniform

**Comment by huxianyin** [comment]
I was having same problem when my model contains customer layers, after few hours of debugging, perfectly worked using:

with CustomObjectScope({'AttentionLayer': AttentionLayer}):
   model = load_model("my_model.h5")

other than:

model = load_model('my_model.h5', custom_objects={'AttentionLayer': AttentionLayer})

maybe bug of keras?
hope to help

**Comment by AdnanRiaz107** [comment]
> From the FAQ:
> 
> #### Handling custom layers (or other custom objects) in saved models
> If the model you want to load includes custom layers or other custom classes or functions,
> you can pass them to the loading mechanism via the `custom_objects` argument:
> 
> ```python
> from keras.models import load_model
> # Assuming your model includes instance of an "AttentionLayer" class
> model = load_model('my_model.h5', custom_objects={'AttentionLayer': AttentionLayer})
> ```
> 
> Alternatively, you can use a [custom object scope](https://keras.io/utils/#customobjectscope):
> 
> ```python
> from keras.utils import CustomObjectScope
> 
> with CustomObjectScope({'AttentionLayer': AttentionLayer}):
>     model = load_model('my_model.h5')
> ```
> 
> Custom objects handling works the same way for `load_model`, `model_from_json`, `model_from_yaml`:
> 
> ```python
> from keras.models import model_from_json
> model = model_from_json(json_string, custom_objects={'AttentionLayer': AttentionLayer})
> ```

Hello! I have tried both but I got the error. "ValueError: Unknown layer: Attention"

**Comment by singhay** [comment]
@AdnanRiaz107 is the name of attention layer `AttentionLayer` or `Attention`? try doing a `model.summary()`

**Comment by Walid-Ahmed** [comment]
This repo shows a simple sample code to build your own keras layer and use it in your model
https://github.com/Walid-Ahmed/kerasExamples/tree/master/creatingCustoumizedLayer
it might help

**Comment by Walid-Ahmed** [comment]
This repo shows a simple sample code to build your own keras layer and use it in your model
https://github.com/Walid-Ahmed/kerasExamples/tree/master/creatingCustoumizedLayer
it might help

**Comment by arunraja-hub** [comment]
I am trying to build my own model_from_json function from scratch as I am working with a custom .json file. My custom json file follows this format:
```
{
  "training_params": {...},
    "architecture":{contains the actual model structure as generated by model.to_json()}
}
```
How can I extract the training_params and model architecture from my custom json to create a model of that architecture and parameters with this line of code
`loaded_model = my_model_from_json(loaded_model_json)` ?
