### ISSUE TITLE
'ModuleNotFoundError' for Keras and TensorFlow 1.4

### ISSUE THREAD

**Issue by Hvass-Labs** [keras-team/keras#8621]
I have just started using Keras and regret I didn't do it sooner. It has really been a nightmare to use the half-baked API's of TensorFlow. Keras is exceptionally well made and I have read some of @fchollet's github and blog-posts with his thoughts on API design and I am deeply impressed by his user-centric approach and pursuit of simplicity and beauty. He really should have been put in charge of TensorFlow's API 1-2 years ago, then TensorFlow would have progressed much further by now, and it would have freed up massive resources for the community who is constantly bogged down by the bizarre TF API. So I am casting my vote that @fchollet is now made the King and Supreme Ruler of the TensorFlow API. A bit of Monty Python is in order: https://www.youtube.com/watch?v=-8bqQ-C1PSE

Anyway, I am having a rookie problem importing Keras in TensorFlow 1.4 using Python 3.6 on Ubuntu 16.04 with Anaconda 4.3.14.

There is a related post on StackOverflow:

https://stackoverflow.com/questions/47262955/how-to-import-keras-from-tf-keras-in-tensorflow

But it is really a hack-around instead of an elegant solution. I think this may be a problem with how Keras exposes itself as modules - but I'm not a Python expert so I can't really say.

I would like to do something like this:

    import tensorflow as tf
    from tf.keras.models import Sequential
    from tf.keras.layers import Dense

    model = Sequential()
    model.add(Dense(256, input_shape=(784,)))

I have tried various ways of importing Keras but I get 'ModuleNotFoundError' except in the last line which has a really long import statement.

    >>> import tensorflow as tf
    >>> tf.__version__
    '1.4.0'
    >>> import tf.keras as keras
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ModuleNotFoundError: No module named 'tf'
    >>> import tensorflow.keras as keras
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ModuleNotFoundError: No module named 'tensorflow.keras'
    >>> import tensorflow.python.keras as keras
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    AttributeError: module 'tensorflow' has no attribute 'python'
    >>> from tensorflow.python.keras.models import Sequential  # THIS WORKS!
    >>> 

But all of those are actually modules if I print them out:

    >>> print(tf.keras)
    <module 'tensorflow.python.keras' from '/home/magnus/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/keras/__init__.py'>
    >>> print(tf.keras.models)
    <module 'tensorflow.python.keras.models' from '/home/magnus/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/keras/models/__init__.py'>

So I imagine that it should be possible to import them like I tried above?

**Comment by teja-bogireddy** [comment]
Try removing 'tf'

from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
model.add(Dense(256, input_shape=(784,)))

We don't need to import tf every-time as tensorflow is defined as backend for keras at the time of installation.
You can change it to theano also.

**Comment by Hvass-Labs** [comment]
Thanks but I don't have a separate installation of Keras. I only have it as a part of TensorFlow 1.4. So if I try to import as you suggest, I get the same error, because Keras is not available in the top-level import-path for modules, it is located under `tensorflow.keras`

    >>> import tensorflow as tf
    >>> from keras.models import Sequential
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ModuleNotFoundError: No module named 'keras'

**Comment by nicolewhite** [comment]
Perhaps you should open an issue under the [tensorflow repo](https://github.com/tensorflow/tensorflow/issues).

**Comment by markmeyerphoto** [comment]
This works for me:

    from tensorflow.python.keras.models import Sequential
    from tensorflow.python.keras.layers import Input
    # etc.

**Comment by rragundez** [comment]
I've open an issue in the tensorflow repo https://github.com/tensorflow/tensorflow/issues/15736

**Comment by Hvass-Labs** [comment]
Discussion moved to tensorflow/tensorflow#15736. I didn't realize the development of the TF version of Keras was separate.

**Comment by Ayesha2788** [comment]
line 4, in  from keras.datasets import mnist ModuleNotFoundError: No module named 'keras' Process finished with exit code 1 can anyone help with this
--

**Comment by Dhivagar44** [comment]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Input In [25], in <cell line: 2>()
      1 from sklearn.model_selection import train_test_split
----> 2 import tensorflow as tf
      3 from tensorflow import keras
      4 from tensorflow.keras import layers

ModuleNotFoundError: No module named 'tensorflow'
