### ISSUE TITLE
Variable length digit recognition with CNN?

### ISSUE THREAD

**Issue by einareinarsson** [keras-team/keras#8623]
I'd like to use Keras for recognizing handwritten digit sequences with CNN but I cannot find any clue how to approach the problem. The segmentation of the image by individual digits is misleading as there is no reliable way to do that (sometimes the bounding boxes are overlapping, sometimes multiple digits are written by one continuous line etc.). I'm considering to feed the whole sequence as a single image to a CNN but I don't know what would be the last layer here, this not being a classification with fix outputs. Neither seq-to-seq seems to be a good idea, having no real "temporal" sequence here. So I'm clueless a bit...

**Comment by mpariente** [comment]
You may want to look at [this article](http://www.cs.toronto.edu/~graves/icml_2006.pdf) on Connectionist Temporal Classification and [a nice post](https://distill.pub/2017/ctc/) on the subject.
