### ISSUE TITLE
Timedistributed concatenation error in siamese CNN and LSTM

### ISSUE THREAD

**Issue by rajatkoner08** [keras-team/keras#8631]
Hi, 
I am implementing [re3 tracker](https://arxiv.org/abs/1705.06368) in Keras using [mobilenet](https://github.com/fchollet/keras/blob/master/keras/applications/mobilenet.py). And for that I need to concatenate feature from mobilenet, and then have to connect Dense layer and LSTM. So I have used  TimeDistributed warper,  so I can't concatenate two features as per [#2271](https://github.com/fchollet/keras/issues/2271) and other solution as its wrapped with TimeDistributed. How can I concatenate these features? 
` # network definition
    mobilenet = MobileNet(input_dim, alpha=1.0, include_top=False,pooling='avg')

    img_t0 = Input(shape=[width,height,3] )
    img_t1 = Input(shape=[width,height,3])
    
    img_feature_t0 = TimeDistributed(mobilenet(img_t0))
    img_feature_t1 = TimeDistributed(mobilenet(img_t1))
   
    # merge output features
    concat = Concatenate(axis=-1)
    merge_images = concat([img_feature_t0,img_feature_t1])
    
    fc = TimeDistributed(Dense(2048, activation='relu', name='EmbededFC'))(merge_images)
    x = LSTM(LSTM_SIZE, recurrent_activation='tanh', stateful=True)(fc6)` 

Error : 

> File "/home/rajat/.local/lib/python2.7/site-packages/keras/engine/topology.py", line 558, in __call__
    self.assert_input_compatibility(inputs)
  File "/home/rajat/.local/lib/python2.7/site-packages/keras/engine/topology.py", line 431, in assert_input_compatibility
    str(inputs) + '. All inputs to the layer '
ValueError: Layer concatenate_1 was called with an input that isn't a symbolic tensor. Received type: <class 'keras.layers.wrappers.TimeDistributed'>. Full input: [<keras.layers.wrappers.TimeDistributed object at 0x7fdddb8e1150>, <keras.layers.wrappers.TimeDistributed object at 0x7fdddafad4d0>]. All inputs to the layer should be tensors.

Picture of the network is : 
  
![image](https://user-images.githubusercontent.com/20337365/33386584-8de5b8c6-d52b-11e7-8c2a-95b49e713648.png)

**Comment by mpariente** [comment]
I believe that changing to this would work : 
` img_feature_t0 = TimeDistributed(mobilenet)(img_t0) `
` img_feature_t1 = TimeDistributed(mobilenet)(img_t1) `

Does it help?
