### ISSUE TITLE
is that possible to do Conv2d with given filter?

### ISSUE THREAD

**Issue by 32nguyen** [keras-team/keras#8633]
Hi,
I would like to know if I can take the advantage for parallel computing on GPU using keras in the case of:
 - I have 16 images (2000x2000 pixels) (for 1 batch_size), I would like to compute the corresponding 16 residual background by using the an average filter (100, 100) and take the 2D convolution on those 16 images. This will take a lot of time so I would like to process it in parallel. 

Bests,

**Comment by gabrieldemarmiesse** [comment]
Hi,

I think it's possible. 
Do you already have the kernels for your convolutions? Also, what do you mean by average filter? 

Thank you.
