### ISSUE TITLE
TypeError: ufunc 'true_divide' output (typecode 'd') could not be coerced to provided output parameter (typecode 'B') according to the casting rule ''same_kind''

### ISSUE THREAD

**Issue by moondra2017** [keras-team/keras#8635]
I'm getting this error when trying to run `preprocess` from

`from keras.applications.inception_v3 import InceptionV3, preprocess_input`

Keras '2.1.1'
Tensorflow 1.4
Windows 7

Full traceback:

> `Traceback (most recent call last):
  File "C:\Users\Moondra\Desktop\Keras Applications\keras_transfer_learning_inception_without_image_generator.py", line 86, in <module>
    norm_x = preprocess_input(x)
  File "C:\Users\Moondra\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\applications\inception_v3.py", line 400, in preprocess_input
    return imagenet_utils.preprocess_input(x, mode='tf')
  File "C:\Users\Moondra\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\applications\imagenet_utils.py", line 33, in preprocess_input
    x /= 255.
TypeError: ufunc 'true_divide' output (typecode 'd') could not be coerced to provided output parameter (typecode 'B') according to the casting rule ''same_kind''`

According to this message:

Keras is using a deprecated numpy function?

https://github.com/numpy/numpy/issues/6464

Thank you.

**Comment by ivona-tooploox** [comment]
Having the same issue with Keras 2.0.8, Tensorflow 1.3

**Comment by stiebels** [comment]
same issue:

Tensorflow 1.3
Keras 2.1.3
Ubuntu 16.04

**Comment by stiebels** [comment]
Provided pull request for fix: https://github.com/keras-team/keras/pull/9360

**Comment by 926122009** [comment]
i had the same problem, and it has been fixed since i changed the type to 'float' through ( X.astype('float') ) command
