### ISSUE TITLE
3D augmentation -keras

### ISSUE THREAD

**Issue by bolgebrygg** [keras-team/keras#8656]
Are there any plans to include 3D image generation (augmentation) like rotating/ squeezing/ flipping 3D cubes realtime for sample generation?

**Comment by fchollet** [comment]
There are no plans at this time.

You could consider replicating some of the functionality found in `keras/preprocessing/image.py` for 3D data. I think most of it could work with only small modifications.

**Comment by Issam28** [comment]
yeah adding 3D data would be so great

**Comment by xuzhang5788** [comment]
I am looking forward to having 3D augmentation implementation soon
