### ISSUE TITLE
Introduction of global metrics (precision and recall)

### ISSUE THREAD

**Issue by Kritikalcoder** [keras-team/keras#8657]

**Comment by brge17** [comment]
Keras computes batchwise metrics in averages.

So those can't be accurately calculated .

See my improvement suggestion:
https://github.com/fchollet/keras/issues/8607

**Comment by fchollet** [comment]
I agree that global metrics like precision and recall are important to have. @Kritikalcoder or @brge17, would you like to work on it?

The general template would be callable metrics classes (similar to layers, but simpler) that maintain weights (a state containing the global metric value). Calling an instance updates the state and returns the current state value. Makes sense?

**Comment by brge17** [comment]
Makes sense, I will give it a shot and raise a PR.

**Comment by fchollet** [comment]
Note that the main change will be to add support for such metrics in `training.py`. We'll need a special case for them because *they will have update ops* and these update ops need to be incorporated into the training function and evaluate function.

**Comment by ozabluda** [comment]
Can we, please, have confusion matrix ASAP (i.e. making sure this new mechanism supports this use case). In fact, maybe precision and recall, etc should be calculated from the confusion matrix for a binary classifier anyway to sync the code. AUC is also an interesting use case (code design wise), probably the same very design can work if and only if it works for precision-recall curve.

In fact, maybe we can just have a single object that accumulates `y_true, y_pred, etc`, then applies whatever function you want to them, which, most of the time will be one of
http://scikit-learn.org/stable/modules/classes.html#module-sklearn.metrics

**Comment by brge17** [comment]
@ozabluda 

The metric class we are describing will wrap any arbitrary metric to make it a global metric.

This includes False Positives, False Negatives, True Positive, True Negative (and there rate counterparts)

Think of it like, global_metric(my_custom_metric(y_pred, y_true))

**Comment by Kritikalcoder** [comment]
These are the global metrics that I think should be introduced:
1. Micro precision
2. Micro recall
3. Micro F-score
4. Macro precision
5. Macro recall
6. Macro F-score
7. Confusion matrix

**Comment by ozabluda** [comment]
For the reference, here is a list of TF metrics, in case we'll (almost certainly) have to wrap both np and TF ones:
https://www.tensorflow.org/api_docs/python/tf/metrics
https://www.tensorflow.org/api_docs/python/tf/contrib/metrics

**Comment by fchollet** [comment]
Maybe we should have metrics classes that look like:

```python

class MyMetric(object):

     def __init__(self, ...):
          self.true_positives = K.variable(...)
          ...

     def __call__(self, y_true, y_pred):
         # will be called in `compile`
         self.updates = [...]   # update state
         return metric_value_so_far

     def reset_state(self):
         # will be called at the beginning of an epoch
         K.batch_set_value([self.true_positives, ...], [0, ...])

    def get_config(self):
        ...

    @classmethod
    def from_config(self, config):
        ...
```

`reset_state` should also be called when resetting model state (`model.reset_state()`, if I recall correctly).

Do we need anything else to make it work?

**Comment by brge17** [comment]
I like that design I was just going to pass the custom metric to the constructor:

`
class GlobalMetric(object):

     def __init__(self, my_metric):
          self.metric_func = my_metric ...



# Define the metric outside the class
def my_metric(y_pred, y_true):
	...
	return score`

**Comment by fchollet** [comment]
> With the idea GlobalMetric could wrap any metric

I believe that would not work in the general case. The nature of the state, how to update it, and how to go from predictions/labels plus state to the current value, are all potentially-custom logic.

**Comment by brge17** [comment]
How I saw global metric wrapper above is it would work for any metric, but potentially be very expensive to compute.

It would essentially cache the predictions in the state, and recompute the metric from scratch. That solves the most general case, but is not necessarily compute efficient for every case.

**Comment by fchollet** [comment]
> It would essentially cache the predictions in the state, and recompute the metric from scratch each time new predictions are available. That solves the most general case, but is not necessarily compute efficient for every case.

That would be expensive, in particular it would consume a lot of memory for large datasets. The streaming approach is preferable -- we typically only need to keep around a few scalars updated at each iteration, for most metrics.

**Comment by brge17** [comment]
In this PR, should the scope be limited to showing how to implement a couple key metrics in the fashion shown above? This will give people a starting point for their own custom metrics and knock out a couple of popular requests.

I was thinking {false positive, false negative, true positive, true negative, precision, recall, auc}.

**Comment by fchollet** [comment]
Yes, exactly. We just want to push out a template, and cover precision/recall since these are very common and useful.

**Comment by ozabluda** [comment]
all those "key metrics" can be extracted from the confusion matrix.  
>Can we, please, have confusion matrix ASAP (i.e. making sure this new mechanism supports this use case). In fact, maybe precision and recall, etc should be calculated from the confusion matrix for a binary classifier anyway to sync the code. AUC is also an interesting use case (code design wise), probably the same very design can work if and only if it works for precision-recall curve.

**Comment by brge17** [comment]
I will probably code it up some time next week during the week.

**Comment by fchollet** [comment]
Great. This is an important feature.

**Comment by brge17** [comment]
Requires a couple more changes:

https://github.com/fchollet/keras/blob/master/keras/engine/training.py
```
                            metric_fn = metrics_module.get(metric)
                            weighted_metric_fn = _weighted_masked_objective(metric_fn)
```
Will apply an average mask.

Also having issues with updating with class member variables (probably a serialization issue).

**Comment by brge17** [comment]
`
class TruePositives(object):

    def __init__(self, threshold=None):

        self.__name__ = "true_positives"
        if threshold is None:
            self.threshold = K.variable(value=0.5)
        else:
            self.threshold = threshold
        self.true_positives = K.variable(value=0.0)

    def __call__(self, y_true, y_pred):
        return self.update(y_true, y_pred)

    def reset_state(self):
        self.true_positives = K.variable(value=0.0)

    def update(self, y_true, y_pred):

        # Slice the positive score
        y_true = y_true[:, 1]
        y_pred = y_pred[:, 1]

        y_pred = K.cast(y_pred >= self.threshold, 'float32')
        # c = correct classifications
        c = K.cast(K.equal(y_pred, y_true), 'float32')
        # tp = number of true positives
        tp = K.sum(c * y_true)

        self.true_positives += tp

        return self.true_positives
`

The positives += tp doesn't seem to work.

**Comment by brge17** [comment]
This requires a couple of ugly changes to the BaseLogger and Progress Bar:

Basically, if metric is a GlobalMetric (turn off batch averaging) else do what currently was happening.

**Comment by brge17** [comment]
I'm not super familiar with Tensor operations, @ozabluda help would especially be appreciated
for 1-2 below.

See fork: https://github.com/brge17/keras/tree/brian-dev

Remaining issues:
1. Find the proper place to reset state (for {train, eval, test}) currently have a hack that doesn't really work.
2. Reset state properly - function is being called but not working.
3. Find least pass of resistance to update BaseLogger, ProgBar. This involves disabling batch averaging selectively for ProgBar etc...

- 

-

**Comment by brge17** [comment]
Still very stuck on the fact that when __call__ is compiled calling reset_states does nothing.

**Comment by brge17** [comment]
```
    def reset_states(self):
        print("Reset States has been called!")
        self.tp = K.update(self.tp, K.variable(value=0.0))

    def update_states(self, y_true, y_pred):
        print("Update States has been called!")
        # Slice the positive score
        y_true = y_true[:, 1]
        y_pred = y_pred[:, 1]

        # Softmax -> probabilities
        y_pred = K.cast(y_pred >= self.threshold, 'float32')
        # c = correct classifications
        c = K.cast(K.equal(y_pred, y_true), 'float32')
        # tp_batch = number of true positives in a batch
        tp_batch = K.sum(c * y_true)

        self.tp = K.update_add(self.tp, tp_batch)
```

```
Starting new epoch resetting Global Metrics
Reset States has been called!
Epoch 1/5
2018-01-02 10:32:47.784896: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
 900/1000 [==========================>...] - ETA: 0s - loss: 0.5988 - true_positives: 1112.8889Reset States has been called!
1000/1000 [==============================] - 2s 2ms/step - loss: 0.5978 - true_positives: 1146.1818 - val_loss: 0.6308 - val_true_positives: 1582.8000
Starting new epoch resetting Global Metrics
Reset States has been called!
Epoch 2/5
 900/1000 [==========================>...] - ETA: 0s - loss: 0.4774 - true_positives: 2038.0000Reset States has been called!
1000/1000 [==============================] - 2s 2ms/step - loss: 0.4684 - true_positives: 2075.8182 - val_loss: 0.4108 - val_true_positives: 2455.4000
Starting new epoch resetting Global Metrics
Reset States has been called!
Epoch 3/5
 900/1000 [==========================>...] - ETA: 0s - loss: 0.3797 - true_positives: 2844.8889Reset States has been called!
1000/1000 [==============================] - 2s 2ms/step - loss: 0.3797 - true_positives: 2885.8182 - val_loss: 0.3933 - val_true_positives: 3277.8000
Starting new epoch resetting Global Metrics
Reset States has been called!
Epoch 4/5
 900/1000 [==========================>...] - ETA: 0s - loss: 0.3356 - true_positives: 3675.0000Reset States has been called!
1000/1000 [==============================] - 2s 2ms/step - loss: 0.3278 - true_positives: 3717.1818 - val_loss: 0.3255 - val_true_positives: 4169.6000
Starting new epoch resetting Global Metrics
Reset States has been called!
Epoch 5/5
 900/1000 [==========================>...] - ETA: 0s - loss: 0.2633 - true_positives: 4609.6667Reset States has been called!
1000/1000 [==============================] - 2s 2ms/step - loss: 0.2717 - true_positives: 4652.6364 - val_loss: 0.3458 - val_true_positives: 5065.2000
```

**Comment by brge17** [comment]
The reset_states is not part of the graph

![screen shot 2018-01-02 at 11 03 59 am](https://user-images.githubusercontent.com/33430930/34496029-b78ad1ca-efac-11e7-906c-cd44be404b2f.png)

**Comment by brge17** [comment]
The most critical issue is that if reset_states() is called after model.compile it does nothing as it isn't added to the graph.

**Comment by hadsed** [comment]
If all metrics will be single numbers, would there be a simple way to make it work with TensorBoard? Part of what's really useful about the metrics argument in fit is that it shows up in the TB web interface.

**Comment by brge17** [comment]
It will work with TensorBoard, I have a private fork that is getting closer to functioning.

-b

**Comment by vsocrates** [comment]
I'm not sure if this thread is still active, but I've implemented precision/recall using the stateful metrics PR given above following from BinaryTruePositives (https://github.com/keras-team/keras/blob/master/tests/keras/metrics_test.py).  Are we working on implementing such requested metrics? 

For anyone that would like it, this is what it looks like so far. I was only able to get it to work by saving the confusion matrix within the class however. 

https://gist.github.com/vsocrates/7ff65268c2ed533a62f8f9f9d86786af

**Comment by GalAvineri** [comment]
I've seen that progress has been made (#9200, #9253), but i'm not sure - is this feature usable now?

**Comment by brge17** [comment]
@GalAvineri yes

**Comment by brge17** [comment]
Here's a working example:


```python
import keras
from keras.layers import Input, Dense
from keras.models import Model

import numpy as np

class BatchCounter(keras.layers.Layer):

        def __init__(self, name="batch_counter", **kwargs):
            super(BatchCounter, self).__init__(name=name, **kwargs)
            self.stateful = True
            self.batches = keras.backend.variable(value=0, dtype="int32")

        def reset_states(self):
            keras.backend.set_value(self.batches, 0)

        def __call__(self, y_true, y_pred):
            updates = [
                keras.backend.update_add(
                    self.batches, 
                    keras.backend.variable(value=1, dtype="int32"))]
            self.add_update(updates)
            return self.batches

# Dummy dataset
X = np.ones((50, 1))
y = np.zeros((50, 1))

# Dummy model
inputs = Input(shape=(1,))
outputs = Dense(1)(inputs)
model = Model(inputs=inputs, outputs=outputs)
model.compile(loss="mse", optimizer="adam", metrics=[BatchCounter()])

model.fit(X, y, batch_size=10, epochs=10, validation_data = (X, y))
```

**Comment by GalAvineri** [comment]
That's a great example! Thank you!
Than it seems that the infrastructure for the global metrics is set! :)
Are there implementations for the metrics requested by @Kritikalcoder ?

**Comment by brge17** [comment]
They are pretty easy to write, I have internal implementations at work that only work for the TensorFlow backend.

You can pretty easily translate any TensorFlow (streaming metric) to a StateFul Metric.

**Comment by GalAvineri** [comment]
For the lazy amongst us, I’ll post the implementations iv'e collected:
The implementation of recall and precision were made by @briannemsick and the f1 score was implemented by the 'keras_metrics' library:
`from tensorflow.keras.layers import Layer
import tensorflow.keras.backend as K
from operator import truediv


class Recall(Layer):
    '''Compute recall over all batches.
    # Arguments
        name: String, name for the metric.
        class_ind: Integer, class index.
    '''
    def __init__(self, name='recall', class_ind=1):
        super(Recall, self).__init__(name=name)
        self.true_positives = K.variable(value=0, dtype='float32')
        self.total_positives = K.variable(value=0, dtype='float32')
        self.class_ind = class_ind

    def reset_states(self):
        K.set_value(self.true_positives, 0.0)
        K.set_value(self.total_positives, 0.0)

    def __call__(self, y_true, y_pred):
        '''Update recall computation.
        # Arguments
            y_true: Tensor, batch_wise labels
            y_pred: Tensor, batch_wise predictions
        # Returns
            Overall recall for the epoch at the completion of the batch.
        '''
        # Batch
        y_true, y_pred = _slice_by_class(y_true, y_pred, self.class_ind)
        true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
        total_positives = K.sum(K.round(K.clip(y_true, 0, 1)))
        # Current
        current_true_positives = self.true_positives * 1
        current_total_positives = self.total_positives * 1
        # Updates
        updates = [K.update_add(self.true_positives, true_positives),
                   K.update_add(self.total_positives, total_positives)]
        self.add_update(updates, inputs=[y_true, y_pred])
        # Compute recall
        return (current_true_positives + true_positives) / \
               (current_total_positives + total_positives + K.epsilon())


class Precision(Layer):
    '''Compute precision over all batches.
    # Arguments
        name: String, name for the metric.
        class_ind: Integer, class index.
    '''
    def __init__(self, name='precision', class_ind=1):
        super(Precision, self).__init__(name=name)
        self.true_positives = K.variable(value=0, dtype='float32')
        self.pred_positives = K.variable(value=0, dtype='float32')
        self.class_ind = class_ind

    def reset_states(self):
        K.set_value(self.true_positives, 0.0)
        K.set_value(self.pred_positives, 0.0)

    def __call__(self, y_true, y_pred):
        '''Update precision computation.
        # Arguments
            y_true: Tensor, batch_wise labels
            y_pred: Tensor, batch_wise predictions
        # Returns
            Overall precision for the epoch at the completion of the batch.
        '''
        # Batch
        y_true, y_pred = _slice_by_class(y_true, y_pred, self.class_ind)
        true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
        pred_positives = K.sum(K.round(K.clip(y_pred, 0, 1)))
        # Current
        current_true_positives = self.true_positives * 1
        current_pred_positives = self.pred_positives * 1
        # Updates
        updates = [K.update_add(self.true_positives, true_positives),
                   K.update_add(self.pred_positives, pred_positives)]
        self.add_update(updates, inputs=[y_true, y_pred])
        # Compute recall
        return (current_true_positives + true_positives) / \
               (current_pred_positives + pred_positives + K.epsilon())


class F1(Layer):
    """Create a metric for the model's F1 score calculation.
    The F1 score is the harmonic mean of precision and recall.
    """

    def __init__(self, name='f1', class_ind=1):
        super().__init__(name=name)
        self.recall = Recall(class_ind=class_ind)
        self.precision = Precision(class_ind=class_ind)
        self.class_ind = class_ind

    def reset_states(self):
        """Reset the state of the metrics."""
        self.precision.reset_states()
        self.recall.reset_states()

    def __call__(self, y_true, y_pred):
        pr = self.precision(y_true, y_pred)
        rec = self.recall(y_true, y_pred)
        return 2 * truediv(pr * rec, pr + rec + K.epsilon())


def _slice_by_class(y_true, y_pred, class_ind):
    ''' Slice the batch predictions and labels with respect to a given class
    that is encoded by a categorical or binary label.
    #  Arguments:
        y_true: Tensor, batch_wise labels.
        y_pred: Tensor, batch_wise predictions.
        class_ind: Integer, class index.
    # Returns:
        y_slice_true: Tensor, batch_wise label slice.
        y_slice_pred: Tensor,  batch_wise predictions, slice.
    '''
    # Binary encoded
    if y_pred.shape[-1] == 1:
        y_slice_true, y_slice_pred = y_true, y_pred
    # Categorical encoded
    else:
        y_slice_true, y_slice_pred = y_true[..., class_ind], y_pred[..., class_ind]
    return y_slice_true, y_slice_pred`

**Comment by ZackHodari** [comment]
> They are pretty easy to write, I have internal implementations at work that only work for the TensorFlow backend.
> 
> You can pretty easily translate any TensorFlow (streaming metric) to a StateFul Metric.

@brge17 
Are you suggesting wrapping the code as follows? In which case what should go in `reset_state`?
```python
def __call__(self, y_true, y_pred):
     metric_val, update_op = tf.contrib.metrics.some_streaming_op(y_true, y_pred)
     self.add_update(update_op, inputs=[y_true, y_pred])
     return metric_val
```

Or did you pull apart tensorflow's streaming metrics and place the relevant logic within a stateful subclass of `Layer` (i.e. "translate")?

**Comment by briannemsick** [comment]
Hi @ZackHodari . @brge17  was the github tag I used for open source contributions at my last job.

I did the latter.

Also worth noting in the forthcoming TensorFlow 2.0.0 release, all of the streaming metrics will work with tf.keras:

https://github.com/tensorflow/tensorflow/commit/ba7f78b9b0535f38e3e12dcb0b095fc7a6e7bca5#diff-09395f6eebca1f408ed2e91c63477511

If you have another metric in mind, I can help.

**Comment by Kritikalcoder** [comment]
Glad to see that this issue has lead to the fruition of something useful. Thank you @briannemsick and everyone else here, for pursuing this. This is my first open source "contribution", if one may call it that.

**Comment by jlee24** [comment]
> For the lazy amongst us, I’ll post the implementations iv'e collected:
> The implementation of recall and precision were made by @briannemsick and the f1 score was implemented by the 'keras_metrics' library:
> 
> ```python
> from tensorflow.keras.layers import Layer
> import tensorflow.keras.backend as K
> from operator import truediv
> 
> 
> class Recall(Layer):
>     '''Compute recall over all batches.
>     # Arguments
>         name: String, name for the metric.
>         class_ind: Integer, class index.
>     '''
>     def __init__(self, name='recall', class_ind=1):
>         super(Recall, self).__init__(name=name)
>         self.true_positives = K.variable(value=0, dtype='float32')
>         self.total_positives = K.variable(value=0, dtype='float32')
>         self.class_ind = class_ind
> 
>     def reset_states(self):
>         K.set_value(self.true_positives, 0.0)
>         K.set_value(self.total_positives, 0.0)
> 
>     def __call__(self, y_true, y_pred):
>         '''Update recall computation.
>         # Arguments
>             y_true: Tensor, batch_wise labels
>             y_pred: Tensor, batch_wise predictions
>         # Returns
>             Overall recall for the epoch at the completion of the batch.
>         '''
>         # Batch
>         y_true, y_pred = _slice_by_class(y_true, y_pred, self.class_ind)
>         true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
>         total_positives = K.sum(K.round(K.clip(y_true, 0, 1)))
>         # Current
>         current_true_positives = self.true_positives * 1
>         current_total_positives = self.total_positives * 1
>         # Updates
>         updates = [K.update_add(self.true_positives, true_positives),
>                    K.update_add(self.total_positives, total_positives)]
>         self.add_update(updates, inputs=[y_true, y_pred])
>         # Compute recall
>         return (current_true_positives + true_positives) / \
>                (current_total_positives + total_positives + K.epsilon())
> 
> 
> class Precision(Layer):
>     '''Compute precision over all batches.
>     # Arguments
>         name: String, name for the metric.
>         class_ind: Integer, class index.
>     '''
>     def __init__(self, name='precision', class_ind=1):
>         super(Precision, self).__init__(name=name)
>         self.true_positives = K.variable(value=0, dtype='float32')
>         self.pred_positives = K.variable(value=0, dtype='float32')
>         self.class_ind = class_ind
> 
>     def reset_states(self):
>         K.set_value(self.true_positives, 0.0)
>         K.set_value(self.pred_positives, 0.0)
> 
>     def __call__(self, y_true, y_pred):
>         '''Update precision computation.
>         # Arguments
>             y_true: Tensor, batch_wise labels
>             y_pred: Tensor, batch_wise predictions
>         # Returns
>             Overall precision for the epoch at the completion of the batch.
>         '''
>         # Batch
>         y_true, y_pred = _slice_by_class(y_true, y_pred, self.class_ind)
>         true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
>         pred_positives = K.sum(K.round(K.clip(y_pred, 0, 1)))
>         # Current
>         current_true_positives = self.true_positives * 1
>         current_pred_positives = self.pred_positives * 1
>         # Updates
>         updates = [K.update_add(self.true_positives, true_positives),
>                    K.update_add(self.pred_positives, pred_positives)]
>         self.add_update(updates, inputs=[y_true, y_pred])
>         # Compute recall
>         return (current_true_positives + true_positives) / \
>                (current_pred_positives + pred_positives + K.epsilon())
> ```

Could you give an example for how to use one of these metrics? Doing something like
```
    model.compile(loss='binary_crossentropy',
    	      optimizer=tf.keras.optimizers.RMSprop(lr=args["lr"], decay=args["decay"]),
    	      metrics=['acc', Precision(), Recall()])
```
unfortunately didn't work.
