### ISSUE TITLE
IndexError when trying to get output of layer in Keras model

### ISSUE THREAD

**Issue by kkworden** [keras-team/keras#8659]
I am trying to see what my data looks like after going through a convolutional layer in my Keras model. I am using the Theano backend. The code I have has been cobbled together from the Keras Github:

    def get_layer0_outputs(model, test_data):
        output = model.layers[0].output
        inputs = [K.learning_phase()] + model.inputs
        func = K.function(inputs, [output])
        return func([0] + [test_data])

What I'm trying to do here is compile a function for the first layer (a Conv2D layer) in my network. The `test_data` argument is an `np.ndarray`. My model is loaded correctly, and I have already trained it with decent accuracy.

However, when I call this function, I get a cryptic stacktrace:

    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/theano/compile/function_module.py", line 884, in __call__
        self.fn() if output_subset is None else\
      File "/usr/local/lib/python3.5/dist-packages/theano/gof/op.py", line 872, in rval
        r = p(n, [x[0] for x in i], o)
      File "/usr/local/lib/python3.5/dist-packages/theano/tensor/nnet/abstract_conv.py", line 1626, in perform
        conv_out = self.conv(img, kern, mode="valid", dilation=self.filter_dilation)
      File "/usr/local/lib/python3.5/dist-packages/theano/tensor/nnet/abstract_conv.py", line 1531, in conv
        dilated_kern[n, im0, ...],
    IndexError: index 1 is out of bounds for axis 1 with size 1

What does this mean? Am I calling my function incorrectly?

I am using Theano 0.9.0, and Keras 2.1.2

**Comment by VishnuDuttSharma** [comment]
You can try the simpler approach for getting a subsection of model:
`temp_model = Model(inputs = model.inputs, outputs=model.layers[0].output)`
Compile `temp_model` and check `temp_model.summary()`  to ensure that you get the right thing.

The error in your code might be due to improper input. check this out: https://stackoverflow.com/a/41712013
