### ISSUE TITLE
Fit_generator multiprocessing workers get killed only after callbacks are executed

### ISSUE THREAD

**Issue by tRosenflanz** [keras-team/keras#8677]
- [X] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [X] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [X] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [X] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

Fit_generator multiprocess workers get killed only after all of the callbacks are finished. This leads to them occupying more RAM than necessary during training. If one of the callbacks requires a lot of RAM as well (lets say ROC AUC evaluator at the epoch end that calls predict_generator) it can lead to out of memory errors although there is no need for "training" workers to be active at callback time. 
This is minor issue though so if it will require any kind of overhaul of Sequence logic it is not worth the effort

**Comment by fargiolas** [comment]
Seen a couple of out of memory crashes lately. Always happen in callbacks with some message about a signal set() non existent method, will take note next time.
I thought I was having a memory leak in my fit_generator implementation, but given I'm doing the very same thing in a callback (AUROC with predict_generator), your analysis seems correct.

**Comment by Dref360** [comment]
would you mind sharing your cb?

**Comment by fargiolas** [comment]
@Dref360 the callback is something like this, `val_gen` is a keras `Sequence`.

Actually I've never seen out of memory crashes anymore after d5a242e9f6c17a60bbbc7bd114b34ba59dfcca29

Sometimes it hangs in the `predict` call though, CPU suspiciously inactive, like some kind of deadlock. Unfortunately I'm not able to share the rest of the code at this moment, will try to come up with a minimal example if time allows.

```
class MetricsCB(keras.callbacks.Callback):
    def __init__(self, val_gen, val_steps, batch_size):
        self.val_gen = val_gen
        self.val_steps = val_steps
        self.batch_size = batch_size

    def on_epoch_begin(self, epoch, logs={}):
        return

    def on_epoch_end(self, epoch, logs={}):
        y_val = []
        y_true = []

        for i in xrange(self.vdata_steps):
            a, b = self.vdata_gen[i]
            y_val.append(a)
            y_true.append(b)

        y_val = np.vstack(y_val)
        y_true = np.vstack(y_true)

        y_pred = self.model.predict(y_val)

        print("AUC score: {:.04f}".format(skmetrics.roc_auc_score(y_true, y_pred)))
```
