### ISSUE TITLE
how to know the inference time in each layer within keras ? 

### ISSUE THREAD

**Issue by daicoolb** [keras-team/keras#8678]
I want  to know the inference time of each layer within keras, how to achieve it ?

**Comment by gabrieldemarmiesse** [comment]
Hi,

You can't achieve that just with keras because models are compiled (and python can't interact with models during the inference).
What you can do is see if there is a profiler for your backend.
 For example : https://www.tensorflow.org/api_docs/python/tf/profiler for Tensorflow.

Hope it helps.
