### ISSUE TITLE
Changing class_weight during training

### ISSUE THREAD

**Issue by mikevoets** [keras-team/keras#8684]
Right now there is no option for changing the class weights `class_weight` during training when using `model.fit_generator`. The class weight variable is inaccessible from the model instance, as this value is not saved as an instance variable. 

I could of course go away from `model.fit_generator` and create my own generator, and use `model.train_on_batch` in order to be able to adjust the class weights dynamically. It would however be a nice if this would be a built-in option.

**Comment by tRosenflanz** [comment]
In a short term you could output sample weights yourself - it can be a little bit more involved than just class_weight but will allow you to control the weights from within the generator
