### ISSUE TITLE
flow_from_directory loads corrupted Images, how to prevent it?

### ISSUE THREAD

**Issue by JoaoLages** [keras-team/keras#8686]
While using keras' `flow_from_directory` to load a dataset (using [ImageDatagenerator](https://keras.io/preprocessing/image/)), I encounter some error while calling the method `fit_generator`. This is because there is/are some image(s) file(s) that is/are corrupt in my data directory. 

How can I check what image is corrupted or how can I tell `flow_from_directory` or `fit_generator` to drop examples that raise and exception?

**Comment by mikevoets** [comment]
I suggest you try to open the images with PIL and remove the image if it raises an exception.

**Comment by JoaoLages** [comment]
That's a solution yeah. I wonder if I could just define that method and pass it somehow to ? flow_with_directory` because it is really useful to use the data augmentation provided by the `ImageDataGenerator` class
