### ISSUE TITLE
MXNET backend in Keras 2

### ISSUE THREAD

**Issue by MohammadSamragh** [keras-team/keras#8688]
Are there any plans to support the MXNET backend in Keras 2? 

I have used Keras 1 with MXNET backend and its performance (training time) for multiple GPUs outperforms Tensorflow. It is also much easier (in terms of coding) to build Keras models for multiple GPU training with the MXNET backend.

Thanks!

**Comment by fchollet** [comment]
Please contact the MXNet developers, I believe they are working on this.

**Comment by MohammadSamragh** [comment]
Thanks a lot @fchollet I just asked my question on their Github :)

**Comment by sandeep-krishnamurthy** [comment]
This issue can be closed in favor of this tracking issue -  https://github.com/keras-team/keras/issues/8697
