### ISSUE TITLE
load_model() function can not load training config 

### ISSUE THREAD

**Issue by StreamerYJTM** [keras-team/keras#8691]
When I trying to save a model by model.save(), we found implementation is 
`def save(self, filepath, overwrite=True, include_optimizer=True):`
 so this function suggest that training configuration(optimizer, etc.) was saved in h5 file
But when I'm trying to load a model by load_model function（which default param of compile is True）:
`def load_model(filepath, custom_objects=None, compile=True):`
it warns:

> /usr/local/lib/python3.5/dist-packages/keras/models.py:252: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '

so I cannot load my training configurations,I think this is a bug or I'm doing something wrong..
keras version 2.1.2 with tensorflow version 1.3.0

**Comment by eunji6546** [comment]
Did you try model.compile() before save it ?
