### ISSUE TITLE
Implementation of Maxout activation after Convolution

### ISSUE THREAD

**Issue by dalmia** [keras-team/keras#8717]
I had been trying to find the implementation for a Maxout activation followed by a Convolution operation. Keras does have one for Dense layer but not for a convolution layer (as far as I know).  It was mentioned in #3102 that #3128 does this but it just provides a max over the list of tensors. There is no support yet for the following operation for e.g. :

```
Input (33, 33, 4)  ----- Conv (7, 7) + Maxout (K) ------> Output (27, 27, 64) 
```
with Maxout done using, say, `K=4`.

I have worked on an implementation of `Maxout + Conv` for one of my projects. Please have a look at it and let me know if it'd be useful to add it as a Layer in Keras so that I can open a pull request.

```python
class MaxoutConv2D(Layer):
    """
    Convolution Layer followed by Maxout activation as described 
    in https://arxiv.org/abs/1505.03540.
    
    Parameters
    ----------
    
    kernel_size: kernel_size parameter for Conv2D
    output_dim: final number of filters after Maxout
    nb_features: number of filter maps to take the Maxout over; default=4
    padding: 'same' or 'valid'
    first_layer: True if x is the input_tensor
    input_shape: Required if first_layer=True
    
    """
    
    def __init__(self, kernel_size, output_dim, nb_features=4, padding='valid', **kwargs):
        
        self.kernel_size = kernel_size
        self.output_dim = output_dim
        self.nb_features = nb_features
        self.padding = padding
        super(MaxoutConv2D, self).__init__(**kwargs)

    def call(self, x):

        output = None
        for _ in range(self.output_dim):
            
            conv_out = Conv2D(self.nb_features, self.kernel_size, padding=self.padding)(x)
            maxout_out = K.max(conv_out, axis=-1, keepdims=True)

            if output is not None:
                output = K.concatenate([output, maxout_out], axis=-1)

            else:
                output = maxout_out

        return output

    def compute_output_shape(self, input_shape):
        input_height= input_shape[1]
        input_width = input_shape[2]
        
        if(self.padding == 'same'):
            output_height = input_height
            output_width = input_width
        
        else:
            output_height = input_height - self.kernel_size[0] + 1
            output_width = input_width - self.kernel_size[1] + 1
        
        return (input_shape[0], output_height, output_width, self.output_dim)
````

Reference: http://proceedings.mlr.press/v28/goodfellow13.pdf

**Comment by DongqinZhou** [comment]
Hi, Thanks for the implementation. I tried this and found a minor pitfall. Correct me if I am wrong. 

The line "output_height = input_height - self.kernel_size[0] + 1" creates a "TypeError: unsupported operand type(s) for -: 'NoneType' and 'int' ". I believe this is because when you build a model, you do not have exact value for input_shape, so you use a None instead. And when input_height or input_width is None, the error appears when subtracting kernel_size.

Therefore, my suggested implementation would be 
       if(self.padding == 'same'):
            output_height = input_height
            output_width = input_width
        
      elif(input_height == None or input_width == None):
           return (input_shape[0], None, None, self.output_dim)

        else:
            output_height = input_height - self.kernel_size[0] + 1
            output_width = input_width - self.kernel_size[1] + 1

With this implementation, I successfully build my model with MaxoutConv2D. Thx :).

**Comment by iperov** [comment]
wrong impl
