### ISSUE TITLE
mnist_tfrecord question

### ISSUE THREAD

**Issue by guoxiaolu** [keras-team/keras#8733]
@athundt , I'm confused with this example. I have read issues referred "how to use tfrecord in keras", but it makes more confused. As this url (https://github.com/indraforyou/keras_tfrecord) shown, when loading mnist dataset, it first convert the ndarray data to tfrecord by "data_to_tfrecord", then get a tfrecord file, when training by keras, using "read_and_decode" to read tfrecord. But in the final example, these two function are discarded, but I also don't find the tfrecord read function in it. This example seems just using tensorflow mnist dataset not keras, it makes me confused.

**Comment by YinghaoHuang91** [comment]
Yeah, exactly. Just like you, I think I can find the way of combing TFRecord with Keras seamlessly. However there is no reading from TFRecords actually happening.

**Comment by guoxiaolu** [comment]
Okay, Happy Chinese New Year~
