### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'fit'

### ISSUE THREAD

**Issue by LastAncientOne** [keras-team/keras#8737]
I am using the latest version of keras on window 10 python 3.5.

I have issues with this:
AttributeError                            Traceback (most recent call last)
<ipython-input-14-8a88bfa62905> in <module>()
----> 1 model.fit(
      2     X_train,
      3     y_train,
      4     batch_size=512,
      5     nb_epoch=500,

AttributeError: 'NoneType' object has no attribute 'fit'

I appreciated the help.

**Comment by gabrieldemarmiesse** [comment]
Hi!

When opening an issue,  please provide the full code you're using as well as the full error message.

With this little information, it's impossible to help. Can you please provide the rest? Thank you.
