### ISSUE TITLE
How to change  weights with different shape?

### ISSUE THREAD

**Issue by cwzat** [keras-team/keras#8740]
I am doing cross_modality_pretrain in keras.
I use InceptionResNetv2 pretrained model, and get weights of conv2d_1, which shape is (3 3 3 32) (height, width, channels, outputs)

    model_base = InceptionResNetV2(include_top=False, weights='imagenet')

    weight = model_base.get_weights()
    weight_conv2d_1 = weight[0]
    weight_conv2d_1 = np.mean(weight_conv2d_1, axis=2, keepdims=True)

I change it to (3 3 20 32)

    for i in range(20):
        if i == 0:
            weight_change = np.concatenate((weight_conv2d_1,), axis=2)
        else:
            weight_change = np.concatenate((weight_change, weight_conv2d_1), axis=2)

Now, i want to set the new weight ,

    weight[0] = weight_change
    model_base.set_weights(weight)
   
But, i get error:
  

    ValueError: Cannot feed value of shape (3, 3, 10, 32) for Tensor u'Placeholder:0', which has shape '(3, 3, 3, 32)'

How can i solve it? Thank you!

**Comment by lucasdavid** [comment]
This issue has been closed for a while, but I had this problem today (related to the HPA-image-classification competition) and maybe I can help somebody else.
So, yes... You can't change the graph once it's created, as far as I know. You need two networks for this:
```py
>>> SIZES = [512, 512]
>>> x=tf.keras.applications.ResNet50V2(weights='imagenet', input_shape=[*SIZES, 3])
>>> y=tf.keras.applications.ResNet50V2(weights=None, input_shape=[*SIZES, 4])
>>> for w in x.weights[:4]:
...   print(w.name, w.shape)
... 
conv1_conv/kernel:0 (7, 7, 3, 64)
conv1_conv/bias:0 (64,)
conv2_block1_preact_bn/gamma:0 (64,)
conv2_block1_preact_bn/beta:0 (64,)
>>>
>>> weights = x.get_weights()
>>> weights[0].shape
(7, 7, 3, 64)
>>> weights[0] = np.concatenate((weights[0], weights[0][..., 0:1, :]), axis=-2)
>>> weights[0].shape
(7, 7, 4, 64)
>>> y.set_weights(weights)
>>> for a, b in zip(x.get_weights()[1:], y.get_weights()[1:]):
...   np.testing.assert_array_equal(a, b)
... 
>>> # OK (tests passed)
>>> y.predict(np.random.rand(32, 224, 224, 4)).shape
1/1 [==============================] - 1s 1s/step
(32, 1000)
```

Cheers.
