### ISSUE TITLE
Pass multiple-input model to a TimeDistributed Layer

### ISSUE THREAD

**Issue by jaskaran1** [keras-team/keras#8744]
I was following the Keras Functional API tutorial and saw how to create a model which accepts two inputs.
So, during model.fit() one passes [x1,x2] as the data argument.

My question is let say I want to use this model in a TimeDistributedLayer  because I will use the output of this model as an input to my LSTM.

`model = Sequential()`
`model.add(TimeDistributed(comb_model,input_shape=(20,2)))`

I get error **IndexError: list index out of range**

The **comb_model** has input shape

`comb_model.input[0].shape,comb_model.input[1].shape`
`(TensorShape([Dimension(None), Dimension(224), Dimension(224), Dimension(3)]),`
 
`TensorShape([Dimension(None), Dimension(9)]))`

**Comment by chenyikuan110** [comment]
Did you solve it? I have the same issue

**Comment by cipher009** [comment]
Same here. Any news?

**Comment by cipher009** [comment]
#11476

**Comment by mohammadAbdolhosseiniMoghaddam** [comment]
any solution?
I am passing the output of a model to TimeDistributed wrapper. the model accepts two inputs:

> 
output_temporal_model=Model([pnnl_temp,pnnl_pressure],output)   
x1 = Input(shape=(224, 200, 1))
x2 = Input(shape=(224, 200, 1))
x=[Input(shape=(224, 200, 1)),Input(shape=(224, 200, 1))]
encoded_frame_sequence = TimeDistributed(output_temporal_model)(x)
Any help is highly appreciated

**Comment by clavel87** [comment]
Hi! Any solution about it? I'm stack trying to do a herarchical LSTM with TimeDistributed but I keep getting some differents errors. I've tried the examples published here but I still doesn't work. Any help will be highly apreciated.
Thanks
Yisel

**Comment by tempdeltavalue** [comment]
Other question how pass any Model to TimeDist.. layer ?
