### ISSUE TITLE
Extracting a shared network from a triplet siamese model

### ISSUE THREAD

**Issue by tomassykora** [keras-team/keras#8748]
I have a triplet architecture model with one shared CNN which takes three images as input (anchor, positive, negative), predicts feature vectors for each of them and distances between anchor-positive and anchor-negative are computed (distances are input to the loss function):

    Layer (type)                    Output Shape         Params      Connected_to
    ==================================================================================================
    input_anchor (InputLayer)       (None, 224, 224, 3)  0
    __________________________________________________________________________________________________
    input_pos (InputLayer)          (None, 224, 224, 3)  0
    __________________________________________________________________________________________________
    input_neg (InputLayer)          (None, 224, 224, 3)  0
    __________________________________________________________________________________________________
    resnet_model (Model)            (None, 512)          24899456    input_anchor[0][0]
                                                                     input_pos[0][0]
                                                                     input_neg[0][0]
    __________________________________________________________________________________________________
    pos_dist (Lambda)               (None, 1)            0           resnet_model[1][0]
                                                                     resnet_model[2][0]
    __________________________________________________________________________________________________
    neg_dist (Lambda)               (None, 1)            0           resnet_model[1][0]
                                                                     resnet_model[3][0]
    __________________________________________________________________________________________________
    stacked_dists (Lambda)          (None, 2, 1)         0           pos_dist[0][0]
                                                                     neg_dist[0][0]
    ==================================================================================================

I trained this architecture and saved it to a file. Now **I want to load the submodel (`resnet_model`) and predict feature vectors of single images** (one image at a time instead of three, for image retrieval). How can I do that?

    from keras.models import model_from_json

    json_file = open('model.json', 'r')
    loaded_model_json = json_file.read()
    json_file.close()
    loaded_model = model_from_json(loaded_model_json)

    loaded_model.load_weights("model.h5")
    
This is my model loaded. Now how can I get this `resnet_model (Model)` part from my architecture (so it would have single input and single output)? I'm not sure if it is even possible in Keras, that's why I'm asking. Regular methods as `get_layer` don't work here as this part of the original model takes multiple inputs and has multiple outputs. But theoretically, it should be possible as it's the main idea of the siamese networks (to train on pairs/triplets of images and then use it on a single one).

This is how the whole architecture was created:

    input_shape=(224,224,3)
    input_anchor = Input(shape=input_shape, name='input_anchor')
    input_positive = Input(shape=input_shape, name='input_pos')
    input_negative = Input(shape=input_shape, name='input_neg')
    
    net_anchor = resnet_model(input_anchor)
    net_positive = resnet_model(input_positive)
    net_negative = resnet_model(input_negative)
    
    positive_dist = Lambda(euclidean_distance, name='pos_dist')([net_anchor, net_positive])
    negative_dist = Lambda(euclidean_distance, name='neg_dist')([net_anchor, net_negative])
    
    stacked_dists = Lambda( 
    			lambda vects: K.stack(vects, axis=1),
    			name='stacked_dists'
    )([positive_dist, negative_dist])
    
    model = Model([input_anchor, input_positive, input_negative], stacked_dists, name='triple_siamese')

**Comment by marcusklaas** [comment]
I am also very interested in this. I've tried returning two models in a `def_model` function, but it seems that training the siamese network doesn't train the subnetwork, even though they share many layers.

**Comment by tomassykora** [comment]
@marcusklaas I did it this way: Just create the model as in the code above, load the weights to the model and then use the `resnet_model` submodel for predicting feature vectors for individual images:

```
.
.
.
model = Model([input_anchor, input_positive, input_negative], stacked_dists, name='triple_siamese')

model.load_weights('./model_weights.h5')

# use resnet_model for predictions here
```

**Comment by chandansheth** [comment]
@tomassykora , can you elaborate how you performed '# use resnet_model for predictions here'. Thanks in advance.

**Comment by tomassykora** [comment]
I meant just `resnet_model.predict(data)`.

**Comment by acc4012** [comment]
I got this error 
```

model.summary()
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_42 (InputLayer)           (None, 100)          0                                            
__________________________________________________________________________________________________
input_43 (InputLayer)           (None, 100)          0                                            
__________________________________________________________________________________________________
input_44 (InputLayer)           (None, 100)          0                                            
__________________________________________________________________________________________________
sequential_16 (Sequential)      (None, 100)          121200      input_42[0][0]                   
                                                                 input_43[0][0]                   
                                                                 input_44[0][0]                   
__________________________________________________________________________________________________
lambda_57 (Lambda)              (None, 1)            0           sequential_16[1][0]              
                                                                 sequential_16[2][0]              
__________________________________________________________________________________________________
lambda_58 (Lambda)              (None, 1)            0           sequential_16[1][0]              
                                                                 sequential_16[3][0]              
__________________________________________________________________________________________________
lambda_59 (Lambda)              (None, 2, 1)         0           lambda_57[0][0]                  
                                                                 lambda_58[0][0]                  
==================================================================================================
Total params: 121,200
Trainable params: 121,200
Non-trainable params: 0

ValueError: Cannot feed value of shape (1000, 2) for Tensor 'lambda_67_target_2:0', which has shape '(?, ?, ?)'
```

How can I fix this? Many thanks in advance

**Comment by lschaupp** [comment]
i get the exact same error ;)

**Comment by loheden** [comment]
This really requires clarification because there is no documentation covering this specific problem.
If the network is trained with multiple inputs (as in the case of siamese networks) but later predictions are to be done based on a single input (image) (maybe because you already saved encodings of anchor images in a database), how do you really save and restore the model, and then make predictions? I am a bit surprized that no one has given a clear answer to the question.

**Comment by agshar96** [comment]
@tomassykora The way i did it was I defined a new_model, which had the same architecture as resnet_model (Model) you are using then I used set_weights to set it's weight equal to trained weights.

The exact method will be:

weights1 = siamese_model.get_layer(model.layers['index of resnet']);
new_model = resnet() #assumed it returns the model of resnet
new_model.set_weights(weights1);

Now, you can use your model separately. :)

**Comment by rafaspadilha** [comment]
None of the methods mentioned above worked for me, however with what @agshar96  said and [this](https://medium.com/randomai/model-surgery-copy-weights-from-model-to-model-a31b1dec7a7a) I could make it work! 
 
Probably there is an easier way to do this, but the pipeline is: 
- Define a blank model (probably with the same code/methods you used to define your network in training), e.g. *targetModel*;
- Load the model/weights of a pre-trained model, e.g. *sourceModel*
- Iterate over the layers of both:
        - *get_weights* from a layer of *sourceModel*
        - *set_weights* to a layer of *targetModel*

```
siamese_model = load_model("path_to_model")

#In my case, this returns me a Model() representing the desired shared network 
# you will need to change index (you can also use name parameter)
sourceModel = siamese_model.get_layer(index=9)  

targetModel = densenet(...) #this returns a blank Model 

#coping the weights
for l_tg,l_sr in zip(targetModel.layers, sourceModel.layers):
        wk0=l_sr.get_weights()
        l_tg.set_weights(wk0)
```

**Comment by abhishirk** [comment]
How are you training this on triplet loss and minimizing the loss function.
I am new to this so please let me know this.
i have to do this in my project as well

**Comment by kleysonr** [comment]
I did:

1. load the siamese saved model.
2. extract the the layer with the desired trained layers
3. create a new model with a new input layer and the extracted layer

```python
trained_model = load_model('mnist_siamese.model', compile=False)
base_model = trained_model.get_layer('model_1')

input_shape = (28, 28)

input = Input(shape=input_shape)
x = base_model(input)

model = Model(input, x)
```

**Comment by MonlinXING** [comment]
I encountered the same problem and my solution is:
1. create the submodel, e.g. `model=resnet_model()`
2. load weigths from h5 file specifying the layer name with 'by_name' parameter, which in your case is `model.load_weights(weightsFile,by_name='resnet_model'`

**Comment by baocareos** [comment]
> I encountered the same problem and my solution is:
> 
> 1. create the submodel, e.g. `model=resnet_model()`
> 2. load weigths from h5 file specifying the layer name with 'by_name' parameter, which in your case is `model.load_weights(weightsFile,by_name='resnet_model')`

the by_name argument of load_weights function is a boolean True or False. Why do you set 'resnet_model' to it ?

**Comment by BalajiB197** [comment]
@kleysonr Thanks I was able to extract features from the trained model.
My input image size is (80, 80, 1) so after extracting feature my output vector size is 6400, now I am trying to register the image features for the sample images. Could you assist in this how-to select only the important 128d vector??
Thanks

**Comment by Ab-Abdurrahman** [comment]
I did it as follows:

My trained siamese model looked like this:
`siamese_model.summary()`
![image](https://user-images.githubusercontent.com/12384166/101898104-854f0f80-3be6-11eb-9a7b-7d2ae877c42b.png)

**Note** that my newly redefined model is basically the same as the one highlighted in yellow

I **then redefined my model which I wanted to use for extracting embeddings** (It should be the same model you defined except now it will not have those multiple inputs like siamese) which looked like this:

`siamese_embeddings_model = build_siamese_model(input_shape)`
`siamese_embeddings_model .summary()`
![image](https://user-images.githubusercontent.com/12384166/101897618-cb57a380-3be5-11eb-9545-41204c0dd556.png)

Then I just extracted the weights from my trained siamese model and set them into my new model
`embeddings_weights = siamese_model.layers[-3].get_weights()`

`siamese_embeddings_model.set_weights(embeddings_weights )`

Then you can supply the new Image to extract the embeddings from the new model
`vector = siamese.predict(image)`
`len(vector[0])` it will print 150 because of my fine dense layer (which are the output vector)

**Comment by shanmukh05** [comment]
This notebook will solve the problem.

[Extracting embeddings from Siamese Network](https://www.kaggle.com/shanmukh05/embeddindgs-extraction-siamese) . Hope it helps.
