### ISSUE TITLE
Keras Embedding layer online training

### ISSUE THREAD

**Issue by NewEnglandML** [keras-team/keras#8758]
Is it possible to retrain the pre-trained Glove weights in Keras with our own dataset?

**Comment by harshini-gadige** [comment]
Hi

This issue isn't related to a bug/enhancement/feature-request or other accepted types of issue.

To ask questions, please see the following resources :

https://keras.io/
https://keras.io/#support
https://gitter.im/Keras-io/Lobby

Thanks!
