### ISSUE TITLE
[Feature Request] Adaptive Layers

### ISSUE THREAD

**Issue by mturnshek** [keras-team/keras#8761]
I've been tinkering around with creating an AdaptiveGaussianNoise layer, as described in [Better Exploration with Parameter Noise](https://blog.openai.com/better-exploration-with-parameter-noise/).

This would, in a classification model, work by adjusting the std_dev of a normal GaussianNoise layer every few steps such that the probability of choosing any specific category varies by a desired amount.

However, it seems that in order to do that, a current custom layer doesn't quite suffice, and you need some meta-monitoring which passes information back to your layer periodically. Any adaptive layer needs access to information about more than itself.

Adding a generalized way to allow layers to look at information about their models could increase the ease of designing new layers. Two questions:

A) What would be the best way to include this in keras?
B) Is this worth including in a generalized fashion, or is it too specific a use-case?

**Comment by gabrieldemarmiesse** [comment]
Hi!

If you want to request a feature, you should look at the keras-contrib repository (it's made for this, you can post an issue there if you want) and close the issue here, you'll have more luck than posting an issue in the keras repository which is more focused on bug reports. 

Hope it helps.
