### ISSUE TITLE
May I change the channel number of the pre-trained model for fine-tune?

### ISSUE THREAD

**Issue by sodaGH** [keras-team/keras#8766]
Thanks for all the sharing!
I have a problem during fine-tune. Does anyone know that can I load the pre-trained model weight to a new model architecture whose input channel has been changed? 
For example, I want to test the 2D resNet on 3D data, the previous input shape was (229*229*3). Now I want to change the input size to (64*64*64), can I load the model weight correctly? If not, does anyone knows how to achieve that aim?
Thanks for the reply!

**Comment by cwzat** [comment]
Hi, you can use `model.get_config()` to build you own model. I remember there is a similar issue.
