### ISSUE TITLE
getting different result from  model.save_weights and  model.model.save

### ISSUE THREAD

**Issue by wailoktam** [keras-team/keras#8773]
I have been using  model.save_weights so far and everything works well except that it appears that I cannot resume training from saved weights. My understanding of the documentation is that I need to use model.save to save everything, do a load_model from the file saved and do model.fit again. 

So I try model.save and do a load_model but it returns different results  from those produced by save weights and load_weights.

Below is my setting.
Keras 2.0.8
Python 3.5.2
Theano 0.9.0

Can anyone give me an explanation for this and tell me how to properly use them?

Thanks.

Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [ ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [ ] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by gabrieldemarmiesse** [comment]
You can absolutely resume training just by using save_weights and load_weight. If it produces different results, it's a bug in the keras codebase. Can you give a script which shows evidence of the results not being the same? As mentioned in the guidelines, a script is useful because otherwise it's hard to reproduce your issue. Thank you!
