### ISSUE TITLE
Shuffling the values of a tensor using Lambda

### ISSUE THREAD

**Issue by ee14b101** [keras-team/keras#8777]
Hello,

I am trying to implement a Lambda layer to reverse the following operation
`out = np.c_[data[::2], data[1::2]]`
where data is a 1D array

Using numpy, I would do it as 
`a = out[:]`
`a[::2] = out[0:len(out)/2]`
`a[1::2] = out[len(out)/2:]`

I tried
`t0 = K.eval(input_data)`
`t1 = t0[:]`
`t1[::2] = t0[0:5163]`
`t1[1::2] = t0[5163:]`
`return K.variable(t1)`

But this returned the error - "You must feed a value for placeholder tensor"

What's the right way to do it?

Thanks

**Comment by Dref360** [comment]
Hi!
This question seems best suited for StackOverflow. Could you post your issue there? Also, remember to close your issue if you do so!
Thanks!
