### ISSUE TITLE
How can i set weights for only some layers of network? 

### ISSUE THREAD

**Issue by harora** [keras-team/keras#8780]
I have a model which has encoder-decoder model followed by a classification model. Now i want to use pre-trained weights for encoder and classification part. Can someone help me on this?

**Comment by mpariente** [comment]
If you named your layers, you can call their methods [get_weights](https://github.com/keras-team/keras/blob/master/keras/engine/topology.py#L1207) and [set_weights](https://github.com/keras-team/keras/blob/master/keras/engine/topology.py#L1170) and transfer only the weights you want.

**Comment by harora** [comment]
@mpariente But set_weights would set the weight for all of my layers together. How do i limit it to few layers

**Comment by mturnshek** [comment]
@harora `get_weights` and `set_weights` are methods for both models and layers.

**Comment by mpariente** [comment]
Exactly, can call them only on the layers you're interested in!

**Comment by harora** [comment]
Thanks @mturnshek  and @mpariente.
