### ISSUE TITLE
ReduceLROnPlateau at line 877 self.lr_epsilon = self.min_lr * 1e-4

### ISSUE THREAD

**Issue by jrounds** [keras-team/keras#8781]
Hi I copied Keras source to write a slightly different callback and one piece of logic started to seem peculiar to me.

**Background**
https://github.com/keras-team/keras/blob/a18aed4f8fcb8e4d6b4433fb56754a4a73f9224a/keras/callbacks.py#L877 

At line 877 there is the assignment:
self.lr_epsilon = self.min_lr * 1e-4

Then that assignment gets used at:
https://github.com/keras-team/keras/blob/a18aed4f8fcb8e4d6b4433fb56754a4a73f9224a/keras/callbacks.py#L904

....

**Issue**

That if statement is mathematically
if old_lr > (1.0004)*self.min_lr:

At no point does the argument epsilon or other user parameter get used in that check
https://github.com/keras-team/keras/blob/master/keras/callbacks.py#L832

So all that is accomplished by adding self.lr_epsilon to self.min_lr is to scale self.min_lr by a hard-coded amount.

There are lots of adhoc things to do here. Either way the current if statement seems a little odd, so I thought I would bounce it off you.

**Comment by gabrieldemarmiesse** [comment]
Thank you for the detailed issue.
 I'll look into it. You can expect a small PR with code simplification if this is confirmed.

**Comment by gabrieldemarmiesse** [comment]
It seems that the lines you're mentioning have already been changed. You can close this issue if you have no more comments. 
Thank you!
