### ISSUE TITLE
ANN Error with Array Shape

### ISSUE THREAD

**Issue by Maza0404** [keras-team/keras#8783]
Hello, new user here. My libraries are updated. I'm having an issue with using an ANN model on a categorical dependent variable with 3 levels (0, 1, 2).  The IV's are all dummys.  I use the following code in python: 

```
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset = pd.read_csv('Risk Score All.csv')
X = dataset.iloc[:, 3:9].values
y = dataset.iloc[:, 0].values

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

import keras
from keras.models import Sequential
from keras.layers import Dense

classifier = Sequential()
classifier.add(Dense(output_dim = 4, init = 'uniform', activation = 'relu', input_dim = 5))
classifier.add(Dense(output_dim = 4, init = 'uniform', activation = 'relu'))
classifier.add(Dense(output_dim = 3, init = 'uniform', activation = 'sigmoid'))
classifier.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])
classifier.fit(X_train, y_train, batch_size = 10, nb_epoch = 100)
```

I receive the following error: 

> ValueError: Error when checking target: expected dense_18 to have shape (None, 3) but got array with shape (50288, 1)

Does anyone have any ideas on how to solve this? Thanks. 

Also any other suggestions about my code are welcome. Unsure if Rectifier is the best fit for a zero inflated dv with 3 categories.

**Comment by Dref360** [comment]
Hi!
This question seems best suited for StackOverflow. Could you post your issue there? Also, remember to close your issue if you do so!
Thanks!

**Comment by Maza0404** [comment]
Will do! Thanks.

https://stackoverflow.com/questions/47803131/ann-error-with-array-shape
