### ISSUE TITLE
Image data generator for segmentation maps of more than 4 channels

### ISSUE THREAD

**Issue by gaborlegradi** [keras-team/keras#8789]
Hi,

I would like to use the robust image augmentation tool of Keras for my PWS segmenter. Unfortunately, Keras can not handle images of more than 4 channels. The following code works fine with 4 channels. However, with 5 channels it results in the following error:
[...] ValueError: NumpyArrayIterator is set to use the data format convention "channels_last" (channels on axis 3), i.e. expected either 1, 3 or 4 channels on axis 3. However, it was passed an array with shape (11, 88, 320, 5) (5 channels).

data_gen_args = dict(
    vertical_flip=True, 
    horizontal_flip=True, 
    height_shift_range=0.05,
    fill_mode='nearest', 
    )

image_datagen = ImageDataGenerator(**data_gen_args)
mask_datagen = ImageDataGenerator(**data_gen_args)

seed = 1
image_datagen.fit(x_trainOK, augment=True, seed=seed)
mask_datagen.fit(x_ref, augment=True, seed=seed)

segmenter_upsampling.compile(optimizer='rmsprop', loss=['categorical_crossentropy'])

epochs = 3200
initial_epoch = 0

segmenter_upsampling.fit_generator(
    zip( 
image_datagen.flow(x_trainOK, y=None, batch_size=11, seed=seed), 
          mask_datagen.flow(x_ref, y=None, batch_size=11, seed=seed)
        ), steps_per_epoch=(len(x_trainOK) // 11), epochs=epochs,  verbose=2,  
    initial_epoch=initial_epoch)

**Comment by gaborlegradi** [comment]
I tried this too, but np.concatenate can not handle iterables:

data_gen_args = dict(
    vertical_flip=True, 
    horizontal_flip=True, 
    height_shift_range=0.05,
    fill_mode='nearest', 
    )

image_datagen = ImageDataGenerator(**data_gen_args)
mask_datagen0 = ImageDataGenerator(**data_gen_args)
mask_datagen1 = ImageDataGenerator(**data_gen_args)
mask_datagen2 = ImageDataGenerator(**data_gen_args)
mask_datagen3 = ImageDataGenerator(**data_gen_args)
mask_datagen4 = ImageDataGenerator(**data_gen_args)


seed = 1
image_datagen.fit(x_trainOK, augment=True, seed=seed)
mask_datagen0.fit(np.expand_dims(x_ref[:,:,:,0], axis=3), augment=True, seed=seed)
mask_datagen1.fit(np.expand_dims(x_ref[:,:,:,1], axis=3), augment=True, seed=seed)
mask_datagen2.fit(np.expand_dims(x_ref[:,:,:,2], axis=3), augment=True, seed=seed)
mask_datagen3.fit(np.expand_dims(x_ref[:,:,:,3], axis=3), augment=True, seed=seed)
mask_datagen4.fit(np.expand_dims(x_ref[:,:,:,4], axis=3), augment=True, seed=seed)

segmenter_upsampling.compile(optimizer='rmsprop', loss=['categorical_crossentropy'])

epochs = 3200
initial_epoch = 0

segmenter_upsampling.fit_generator(
    zip( image_datagen.flow(x_trainOK, y=None, batch_size=11, seed=seed), 
        np.concatenate((mask_datagen0.flow(np.expand_dims(x_ref[:,:,:,0], axis=3), y=None, batch_size=11, seed=seed), 
        mask_datagen1.flow(np.expand_dims(x_ref[:,:,:,1], axis=3), y=None, batch_size=11, seed=seed), 
        mask_datagen2.flow(np.expand_dims(x_ref[:,:,:,2], axis=3), y=None, batch_size=11, seed=seed), 
        mask_datagen3.flow(np.expand_dims(x_ref[:,:,:,3], axis=3), y=None, batch_size=11, seed=seed), 
        mask_datagen4.flow(np.expand_dims(x_ref[:,:,:,4], axis=3), y=None, batch_size=11, seed=seed) ), 
        ), axis=3), steps_per_epoch=(len(x_trainOK) // 11), epochs=epochs,  verbose=2,  
    initial_epoch=initial_epoch)

**Comment by fchollet** [comment]
I think you have an outdated Keras version. Update to the latest one.

**Comment by gaborlegradi** [comment]
Fine. It works. Thanks!
