### ISSUE TITLE
plot_model gives different results using theano and tensorflow

### ISSUE THREAD

**Issue by LeZhengThu** [keras-team/keras#8805]
Hi, when I was using plot_model to view the keras model structure, theano and tensorflow backend gave different results. I wonder if this is normal? Thanks.
![best_model_plot](https://user-images.githubusercontent.com/18341929/34058379-afe8ef68-e18f-11e7-8afe-145331c17ef0.png)
![model_plot](https://user-images.githubusercontent.com/18341929/34058380-b00183b6-e18f-11e7-8470-8cfa2425d490.png)

**Comment by gabrieldemarmiesse** [comment]
Hi! 

When creating an issue, it's very helpful for the people reading to have the code. Could you please provide it? If you can reproduce the issue with a minimum amount of code, it would also accelerate the reviewing process. 

 Thank you.
