### ISSUE TITLE
Transfer farizrahman4u/keras-contrib to keras-team/keras-contrib

### ISSUE THREAD

**Issue by ahundt** [keras-team/keras#8806]
@farizrahman4u @fchollet Would this be an appropriate time to transfer https://github.com/farizrahman4u/keras-contrib/ to https://github.com/keras-team/keras-contrib/? 

I believe this was discussed to some degree when keras-contrib was originally created.

**Comment by fchollet** [comment]
I think so. I opened an issue about it: https://github.com/farizrahman4u/keras-contrib/issues/189

**Comment by ahundt** [comment]
I see it is done, thanks, closing this.
