### ISSUE TITLE
ValueError: Error when checking target: expected model_2 to have shape (None, 256, 256, 1) but got array with shape (300, 128, 128, 3)

### ISSUE THREAD

**Issue by dexter1608** [keras-team/keras#8811]
hi I am building a image classifier for one-class classification in which i've used autoencoder while running this model I am getting this error by this line (autoencoder_model.fit) (ValueError: Error when checking target: expected model_2 to have shape (None, 252, 252, 1) but got array with shape (300, 128, 128, 3).)

    num_of_samples = img_data.shape[0]
    labels = np.ones((num_of_samples,),dtype='int64')

    labels[0:376]=0 
    names = ['cat']

    Y = np_utils.to_categorical(labels, num_class)
    input_shape=img_data[0].shape

    x,y = shuffle(img_data,Y, random_state=2)

    X_train, X_test = train_test_split(img_data, test_size=0.2, random_state=2)

        inputTensor = Input(input_shape)
    x = Conv2D(16, (3, 3), activation='relu', padding='same')(inputTensor)
    x = Conv2D(8, (3, 3), activation='relu', padding='same')(x) 
    x = MaxPooling2D((2, 2), padding='same')(x)
    x = Conv2D(8, (3, 3), activation='relu', padding='same')(x)
    encoded_data = MaxPooling2D((2, 2), padding='same')(x)

    encoder_model = Model(inputTensor,encoded_data)

    # at this point the representation is (4, 4, 8) i.e. 128-dimensional
    encoded_input = Input((4,4,8))
    x = Conv2D(8, (3, 3), activation='relu', padding='same')(encoded_input)
    x = UpSampling2D((2, 2))(x)
    x = Conv2D(8, (3, 3), activation='relu', padding='same')(x)
    x = UpSampling2D((2, 2))(x)
    x = Conv2D(16, (3, 3), activation='relu',padding='same')(x)
    x = UpSampling2D((2, 2))(x)
    decoded_data = Conv2D(1, (3, 3), activation='sigmoid', padding='same')(x)

    decoder_model = Model(encoded_input,decoded_data)

    autoencoder_input = Input(input_shape)
    encoded = encoder_model(autoencoder_input)
    decoded = decoder_model(encoded)
    autoencoder_model = Model(autoencoder_input, decoded)
    autoencoder_model.compile(optimizer='adadelta', loss='binary_crossentropy')

    autoencoder.fit(X_train, y_train,
        epochs=50,
        batch_size=32,
        shuffle=True,
        validation_data=(X_test, y_test),
        callbacks=[TensorBoard(log_dir='/tmp/autoencoder')])

**Comment by vianamp** [comment]
Where is `y_train` defined?

**Comment by dexter1608** [comment]
@vianamp its an autoencoder y_train not needed

**Comment by hasibzunair** [comment]
@vianamp You have to reshape you input to the desired dimensions as given in the error. Refer to [mnist_cnn.py](https://github.com/keras-team/keras/blob/master/examples/mnist_cnn.py) for the conversion. Also always check your input shape before feeding to the model to see if it is correct. 

`x_train.shape, y_train.shape, x_val.shape, y_val.shape`

One thing you can try is by changing the input shape in the model by tweaking this code

`input_shape=img_data[0].shape`

Make this as you input image shape. Not sure this will work though but worth a try.
If your problem is solved you can close the issue.
