### ISSUE TITLE
How to use trained h5 neural network with opencv2 for real time object detection

### ISSUE THREAD

**Issue by Idrees123** [keras-team/keras#8815]
this is my code 

# USAGE
# python real_time_object_detection.py --prototxt MobileNetSSD_deploy.prototxt.txt --model MobileNetSSD_deploy.caffemodel

# import the necessary packages
from imutils.video import VideoStream
from imutils.video import FPS
import numpy as np
import argparse
import imutils
import time
import cv2
from keras.models import load_model
# construct the argument parse and parse the arguments
'''ap = argparse.ArgumentParser()
ap.add_argument("-p", "--prototxt", required=True,
	help="path to Caffe 'deploy' prototxt file")
ap.add_argument("-m", "--model", required=True,
	help="path to Caffe pre-trained model")
ap.add_argument("-c", "--confidence", type=float, default=0.2,
	help="minimum probability to filter weak detections")
args = vars(ap.parse_args())'''

# initialize the list of class labels MobileNet SSD was trained to
# detect, then generate a set of bounding box colors for each class
CLASSES = ["cat","dog"]
COLORS = np.random.uniform(0, 255, size=(len(CLASSES), 3))
fileClosed = 0;
# load our serialized model from disk
print("[INFO] loading model...")
net=load_model("AnnModel.h5")
# net = cv2.dnn.readNetFromCaffe(
#     "C:/Users/osama/PycharmProjects/untitled7/prototxt.txt"    ,
#     "C:/Users/osama/PycharmProjects/untitled7/AnnModel.h5" )

# initialize the video stream, allow the cammera sensor to warmup,
# and initialize the FPS counter
print("[INFO] starting video stream...")
#VdeoStream method is used when we are taking video from webcam
vs = VideoStream(src=0).start()
#cv2.Vdeocapture is used when we are giving input throug computer
# vs = cv2.VideoCapture("C:\\Users\\osama\\Desktop\\RobotWorld 2013- FIRA Robot Soccer - YouTube - Segment1(00_00_44.166-00_00_49.775).mp4")
time.sleep(2.0)
fps = FPS().start()
f = open('cordinate.csv', 'w')
f.write('Object:Confidence,StartX,StartY,EndX,EndY')  # Give your csv text here.
## Python will convert \n to os.linesep
f.write('\n')
# loop over the frames from the video stream
while True:
    # print("in while")
    # grab the frame from the threaded video stream and resize it
    # to have a maximum width of 400 pixels
    frame = vs.read()
    # print("in r", frame)
    frame = imutils.resize(frame, width=400)
    # print("in w")
    # print("======================", type(frame))
    (h, w) = frame.shape[:2]
    # grab the frame dimensions and convert it to a blob
    blob = cv2.dnn.blobFromImage(cv2.resize(frame, (300, 300)),
                                 0.007843, (300, 300), 127.5)

    # pass the blob through the network and obtain the detections and
    # predictions

    # net.setInput(blob)
    detections = net.predict(frame[0][0][0])

    # loop over the detections
    for i in np.arange(0, detections.shape[2]):
        # extract the confidence (i.e., probability) associated with
        # the prediction
        confidence = detections[0, 0, i, 2]

        # filter out weak detections by ensuring the `confidence` is
        # greater than the minimum confidence
        if confidence > 0.4:
            # extract the index of the class label from the
            # `detections`, then compute the (x, y)-coordinates of
            # the bounding box for the object
            idx = int(detections[0, 0, i, 1])
            box = detections[0, 0, i, 3:7] * np.array([w, h, w, h])
            (startX, startY, endX, endY) = box.astype("int")

            # draw the prediction on the frame
            print("class length", len(CLASSES))
            print("index", idx)
            label = "{}: {:.2f}%".format(CLASSES[idx],
                                         confidence * 100)
            f.write(label + ",")
            f.write(str(startX) + ",")
            f.write(str(startY) + ",")
            f.write(str(endX) + ",")
            f.write(str(endY) + ",")
            f.write("\n")
            cv2.rectangle(frame, (startX, startY), (endX, endY),
                          COLORS[idx], 2)
            y = startY - 15 if startY - 15 > 15 else startY + 15
            cv2.putText(frame, label, (startX, y),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.5, COLORS[idx], 2)

    # show the output frame
    cv2.imshow("Frame", frame)
    key = cv2.waitKey(1) & 0xFF

    # if the `q` key was pressed, break from the loop
    if key == ord("q"):
        f.close()
        fileClosed = 1;
        break

    # update the FPS counter
    fps.update()

# stop the timer and display FPS information
if (fileClosed == 0):
    f.close()
fps.stop()
print("[INFO] elapsed time: {:.2f}".format(fps.elapsed()))
print("[INFO] approx. FPS: {:.2f}".format(fps.fps()))

# do a bit of cleanup

cv2.destroyAllWindows()

and I am facing these errors

ValueError: Error when checking : expected dense_1_input to have 2 dimensions, but got array with shape ()

**Comment by mdkhan48** [comment]
I think the problem starts from 'training' side of the code. Have a look at here: https://github.com/keras-team/keras/issues/9986
