### ISSUE TITLE
Help to improve custom layer for normal density prediction

### ISSUE THREAD

**Issue by vianamp** [keras-team/keras#8820]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

Hi. I built a model to predict normal density function of some fake data and to achieve that I created a custom layer. Although the code is working, as you can see in the animation below, I'd appreciate any advices in terms of Keras best practices that would help to improve the code. I also have a couple of questions:

**1) Would it be better to move to the custom layer the _mean_ and _stdev_ prediction performed by the two dense layers? How could this be done?**

**2) The way I am passing the variable GRID to the custom layer seems awkward. Could I instead use `tf.linspace` to generate GRID inside the custom layer? Would this impact performance or this variable will be created only once by the time of computation graph construction?**

**3) Any comments or suggestions are welcomed.**

Example of result:

![prediction](https://user-images.githubusercontent.com/7592099/34078147-7aeaed4e-e2fb-11e7-9abd-7291a0d05528.gif)

My code:

```python
import numpy as np
import tensorflow as tf
from keras import optimizers
from keras import initializers
from keras.models import Model
from keras.engine.topology import Layer
from keras.layers import Input, Flatten, Dense

#
# Custom Layer: takes in two inputs of size (BATCH_SIZE,) corresponding to the
# predicted values of mean and stdev for each sample in the  batch. The layers
# outputs the corresponding normal density (not normalized).
#

class NormalDensity(Layer):

	def __init__(self, grid, array_dim, batch_size, **kwargs):
		self.grid = grid
		self.array_dim = array_dim
		self.batch_size = batch_size
		self.result = None
		super(NormalDensity, self).__init__(**kwargs)

	def build(self, input_shape):
		print(input_shape)
		super(NormalDensity, self).build(input_shape)

	def call(self, inputs, **kwargs):
		m = tf.reshape(inputs[0], (self.batch_size,1,1))
		s = tf.reshape(inputs[1], (self.batch_size,1,1))
		y = tf.multiply(tf.subtract(self.grid,m),tf.reciprocal(s))
		self.result = tf.exp(-tf.pow(y,2))
		return self.result

	def compute_output_shape(self, input_shape):
		return (None,self.array_dim,1)

#
# Sythetic  data  with shape (BATCH_SIZE, ARRAY_DIM, 1).  Each  sample corresponds
# to a normal distribution with mean between [-0.5,0.5] and std between [0.1,0.9].
# The goal is  to  build  a  model  that  will  correctly  reconstruct  the normal
# distributions without knowing the values of mean and std used for generating the
# data.
#

BATCH_SIZE = 3   # Number of samples
ARRAY_DIM  = 128 # Number of points in the grid
GRID = np.linspace(-1.0,1.0,ARRAY_DIM).reshape(1,ARRAY_DIM,1)
GRID = np.repeat(GRID, BATCH_SIZE, axis=0).astype(np.float32)

mean = np.array(np.random.rand(BATCH_SIZE)-0.5, dtype=np.float32).reshape(BATCH_SIZE,1,1)

stdv = np.array(0.1+0.8*np.random.rand(BATCH_SIZE), dtype=np.float32).reshape(BATCH_SIZE,1,1)

XTRUE = np.exp(-np.power((GRID-mean)/stdv,2.0))

#
# Model: Two layers with a single neuron each. They take the input and predicts
# the  values of  mean and std. (I know this could be done using a single dense
# layer, but I built  a  custom  layer that accepts multiple inputs on purpose.
#

input_array = Input(shape=(ARRAY_DIM,1))
flat_input = Flatten()(input_array)
dense_out1 = Dense(units=1, activation='linear', kernel_initializer=initializers.RandomNormal(mean=0.0, stddev=0.05, seed=None))(flat_input)
dense_out2 = Dense(units=1, activation='linear', kernel_initializer=initializers.RandomNormal(mean=0.0, stddev=0.05, seed=None))(flat_input)
output = NormalDensity(grid=GRID,array_dim=ARRAY_DIM,batch_size=BATCH_SIZE)([dense_out1,dense_out2])

model = Model(inputs=[input_array],outputs=[output])
model.compile(optimizer=optimizers.SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True), loss='mse')

#
# Animate the prediction as the model is trained
#

XPRED = model.predict(XTRUE)

import matplotlib.pyplot as plt
import matplotlib.animation as animation

lines = []
fig = plt.figure()
for i in range(BATCH_SIZE):
	obj = plt.plot(GRID[0], XTRUE[i])[0]
	lines.append(obj)
	obj = plt.plot(GRID[0], XPRED[i], '--')[0]
	lines.append(obj)

def init():
	for i in range(BATCH_SIZE):
		lines[2*i+0].set_ydata(XTRUE[i])
		lines[2*i+1].set_ydata(XPRED[i])
	return lines

def animate(i):
	model.fit(XTRUE, XTRUE, epochs=1, verbose=0)
	XPRED = model.predict(XTRUE)
	for i in range(BATCH_SIZE):
		lines[2*i+1].set_ydata(XPRED[i])
	return lines

anim = animation.FuncAnimation(fig, animate, 1, init_func=init, interval=1, blit=False)
plt.show()
```

**Comment by gabrieldemarmiesse** [comment]
Hi!
I'll help the best I can. 

For the specific questions:
1) I don't think it's better to move the dense layers inside your custom layer will do anything except make you write more code.
2) Use the Tensorflow function if you can. I think Tensorflow is smart enough to perform the necessary optimization given it has enought information. You can also create a constant tensor if you want. 
3)You don't need batch_size in your custom layer. Use K.expand_dims instead of tf.reshape(). As a generas advice, prefer using keras backend to Tensorflow functions. It'll make it easier for keras users to understand your code. For example, you can replace tf.pow() and tf.exp() by their keras equivalent.
Also what do you think about fusing the dense layers and slicing afterwards in your custom layer? 

Hope this helps.

**Comment by gabrieldemarmiesse** [comment]
Also, I understand that this sentence can be easily misinterpreted, but "If your issue is an implementation question, please ask your question on StackOverflow or join the Keras Slack channel and ask there instead of filing a GitHub issue." means that people reading issues are looking for bugs in keras codebase, and so you'll get a lot more answers by asking your question on stackoverflow or the keras slack group. I hope you understand.

**Comment by vianamp** [comment]
Thanks @gabrieldemarmiesse. I will post future questions in a more appropriated place.
