### ISSUE TITLE
Config options in Keras with CNTK backend

### ISSUE THREAD

**Issue by BalkanKing** [keras-team/keras#8822]
While writing code in Python with Keras and Theano backend you could setup a config file for Theano specifying the amount of preallocated memory with cnmem attribute. Is there a similar functionality for CNTK backend?

In fact, is there any config functionality for CNTK backend while using only Python?

**Comment by gabrieldemarmiesse** [comment]
Hi!
This question should have more answers on the cntk repository or stackoverflow. Keras doesn't prevent the user from using cntk features. And keras doesn't have functions to configure backend specific options.  So this this the same question as asking "does CNTK have a config file like theano?" which isn't related to keras.
By the way, keras issues on github are used to report bugs in the keras codebase. You'll have more people looking at your questions if you ask on stackoverflow. 
I hope this helped.
