### ISSUE TITLE
Can not get state and memory from LSTM layer when wrap by a Bidirectional layer ?

### ISSUE THREAD

**Issue by astrung** [keras-team/keras#8823]
I have a model to work with LSTM layer. It works fine :
 
    encoder_inputs = Input(shape=(None, num_encoder_tokens))
    encoder = LSTM(latent_dim, return_state=True)
    encoder_outputs, state_h, state_c = encoder(encoder_inputs)

But when i add a wrap by a Bidirectional layer : 

    encoder_inputs = Input(shape=(None, num_encoder_tokens))
    encoder = Bidirectional(LSTM(latent_dim, return_state=True),merge_mode="mul")
    encoder_outputs, state_h, state_c = encoder(encoder_inputs)

It lead me an error : 

    output = y * y_rev
    TypeError: can't multiply sequence by non-int of type 'list'.
So how can i get both output, state and memory with Bidirectional layer ? When i remove `return_state=True` , it also works

**Comment by mpariente** [comment]
[This line](https://github.com/keras-team/keras/blob/master/keras/layers/wrappers.py#L290) takes the output of the layer, which in the case of `return_states=True` , is a list. 
And you cannot multiply the lists (from forward and backward layer) at [this line](https://github.com/keras-team/keras/blob/master/keras/layers/wrappers.py#L301)

My guess is that apart from changing the source code to handle `return_states=True` in the `Bidirectional` wrapper, there is no way around it

**Comment by mpariente** [comment]
@astrung This is a gist showing [my attempt](https://gist.github.com/mpariente/24f1e3b43e5a999acaa97a42df9a4ed9) to fix your problem.
I create a new class, child of Bidirectional, which overrides the method `call` to handle the argument `return_state=True`, and the method `compute_output_shape` to take into account that the states are returned. 

@fchollet  Would it be worth it to add something like this to the source code or is it too specific? 
Should I consider making a PR? (Obviously not adding the class but enabling support for `return_state=True` in the `Bidirectional` wrapper)

**Comment by astrung** [comment]
@mpariente i got an error when use your code :  
   
        if hasattr(self.layer.cell.state_size, '__len__'):
        AttributeError: 'LSTM' object has no attribute 'cell'

**Comment by mpariente** [comment]
If you make an example with random data, I can run it and try to solve the problem.

**Comment by astrung** [comment]
@mpariente i updated the gist code for random data with same error. Please check. I am trying to test some modify model from this seq2seq model : https://blog.keras.io/a-ten-minute-introduction-to-sequence-to-sequence-learning-in-keras.html

**Comment by mpariente** [comment]
I get this error message 
```
ValueError: Dimensions must be equal, but are 512 and 256 for 'lstm_8/MatMul_4' (op: 'MatMul') with input shapes: [?,512], [256,256].
```
Which happens at this line : 
```
decoder_outputs, _, _ = decoder_lstm(decoder_inputs,
                                     initial_state=encoder_states)
```
I cannot get the problem, which goes beyond the backend, and I'm not familiar with tensorflow's source code.

**Comment by astrung** [comment]
@mpariente can you comment `initial_state` to see what happen ?. It may be lead to my problem 

    decoder_outputs, _, _ = decoder_lstm(decoder_input)
                                     ## initial_state=encoder_states)

**Comment by mpariente** [comment]
This compiles and train :
```
decoder_lstm = LSTM(latent_dim, return_sequences=True, return_state=True)
decoder_outputs, _, _ = decoder_lstm(decoder_inputs)
```
I didn't work on these architectures yet so I'm not familiar with them. I don't know if it makes sense but this is what is in the tuto.

**Comment by T-B-F** [comment]
I have the same problem (trying to get the states from the bidirectional lstm).
It seems to be a dimensionality problem:

```
# Define an input sequence and process it.
encoder_inputs = Input(shape=(None, num_encoder_tokens))
# encoder = LSTM(latent_dim, return_state=True)
encoder = MyBidirectional(LSTM(latent_dim, return_state=True), merge_mode="sum")
outputs_and_states = encoder(encoder_inputs)
```

I think the shapes inside outputs_and_states should be 256 but they are 512:
```
[<tf.Tensor 'my_bidirectional_3/concat:0' shape=(?, 512) dtype=float32>,
 <tf.Tensor 'my_bidirectional_3/concat_1:0' shape=(?, 512) dtype=float32>,
 <tf.Tensor 'my_bidirectional_3/concat_2:0' shape=(?, 512) dtype=float32>]  
``` 

The initial_state=encoder_states is required for the seq2seq model has the encoding states are passed to the decoder.

**Comment by T-B-F** [comment]
I made some change to the Bidirectional class which seems to hold the expected dimensionality and with the expected initial_state=encoder_states:
https://gist.github.com/T-B-F/0eaef6b8bb9207a576ffc3e3d3676fc2 

but I got an other error regarding the target_output_data dim:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-84-6ed69e21a6f9> in <module>()
      2           batch_size=batch_size,
      3           epochs=epochs,
----> 4           validation_split=0.2)
      5 

/home/tristanbf/.virtualenvs/pydev3/lib/python3.5/site-packages/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_ep
och, steps_per_epoch, validation_steps, **kwargs)
   1579             class_weight=class_weight,
   1580             check_batch_axis=False,
-> 1581             batch_size=batch_size)
   1582         # Prepare validation data.
   1583         do_validation = False

/home/tristanbf/.virtualenvs/pydev3/lib/python3.5/site-packages/keras/engine/training.py in _standardize_user_data(self, x, y, sample_weight, class_weight, check_batch_axis, batch_size)
   1416                                     output_shapes,
   1417                                     check_batch_axis=False,
-> 1418                                     exception_prefix='target')
   1419         sample_weights = _standardize_sample_weights(sample_weight,
   1420                                                      self._feed_output_names)

/home/tristanbf/.virtualenvs/pydev3/lib/python3.5/site-packages/keras/engine/training.py in _standardize_input_data(data, names, shapes, check_batch_axis, exception_prefix)
    139                                  ' to have ' + str(len(shapes[i])) +
    140                                  ' dimensions, but got array with shape ' +
--> 141                                  str(array.shape))
    142             for j, (dim, ref_dim) in enumerate(zip(array.shape, shapes[i])):
    143                 if not j and not check_batch_axis:

ValueError: Error when checking target: expected dense_6 to have 2 dimensions, but got array with shape (100, 12, 32)

```

**Comment by T-B-F** [comment]
Ok, need to replace 

```
decoder_lstm = LSTM(latent_dim, return_state=True)
```
by

```
decoder_lstm = LSTM(latent_dim, return_sequences=True, return_state=True)
```

(I updated my gist)

**Comment by mpariente** [comment]
You cannot use this implementation of the `Bidirectional` wrapper with `return_state=False`.  
You need to handle states inside of `if return_states:`

**Comment by astrung** [comment]
@mpariente i fixed and updated it. It works now. But i really want to see if i can use it directly from keras
