### ISSUE TITLE
LSTM Keras Next Word Prediction on Movie Keywords

### ISSUE THREAD

**Issue by faisalkhan16** [keras-team/keras#8836]
I have to predict next word in lstm keras..but i am having problam in pre procissing the data for traing and testing..

This is how my dataset look like..where ID represent movie id and keywords associate with those movies..

![image](https://user-images.githubusercontent.com/19284729/34156842-cefbe2bc-e4e0-11e7-83c6-3d96f45a9e2f.png)

**Comment by ymodak** [comment]
Hi!
This issue isn't related to a bug/enhancement/feature request or other accepted types of issue.

To ask questions, please see the following resources :

https://keras.io/
https://keras.io/#support
https://gitter.im/Keras-io/Lobby
Thanks!

If you think I made a mistake, please open another issue.
