### ISSUE TITLE
Schedule Keras over different performance GPU

### ISSUE THREAD

**Issue by RnoldR** [keras-team/keras#8840]
I have tried today to use Keras for multi-GPU use and that was a real simple thing to do. I have a request though, that has to do with the fact I have two different GPU's in my system: a geforce 1060 and a Geforce 1080Ti. The last one is about 3 times as fast. As the workflow is equally divided over two GPU's the actual performance slows down compared with running it at the 1080Ti alone. 

I think that I could have a nice speedup when I could specify my knowledge about the cards, something like

    model = multi_gpu_model(pre_model, gpus={gpu:(0, 0.75), gpu:(1, 0.25)})

In the case above it would allocate 75% of the samples to gpu:0 and 25% to gpu:1. I could run a small benchmark before to measure the actuall speed differences. To reduce the training time with just a 'mere' 1/3 addition can save me 6 hours or more in some cases. Is this a possible addition for the next version?

But apart from this: thanks very much for Keras and the gpu speedups it has.

**Comment by oak-tree** [comment]
Its seems that this line https://github.com/keras-team/keras/blob/0d66dc4252f56bec1214874dbf766bdbb2c9ac10/keras/utils/training_utils.py#L132 set up  an equal size for each gpu. So it is possible to change the method to be able receive different division the data but it requires some small changes.

**Comment by RnoldR** [comment]
Thank you @oak-tree for pointing this out. It seems a bit daunting to try and compile Keras (never dome such a thing before), but a good first try might be something for a rainy christmas day :-)
