### ISSUE TITLE
Queue of validation generator in fit_generator

### ISSUE THREAD

**Issue by ltcmdtuvok** [keras-team/keras#8842]
Hi,

I am using `fit_generator` with a data_generator for validation_data.

The code is:

`history=model.fit_generator(generator=generator_trai,steps_per_epoch=200,epochs=2,validation_data=generator_val,validation_steps=15)`

I set `validation_steps=15`. Because of the default queue_size of 10 I expect the generator to add 25 batches to the queue in the first epoch. 15 of 25 for doing the validation in the first epoch and further 10 for filling up the queue. So far so good. But I am wondering why the generator adds futher 25 batches in the second epoch. In my opinion it should only add the 15 batches that are used for validation in second epoch.

Why is this happening? 

The Training Generator works as supposed. Adding 210 batches in first epoch and futher 200 batches in second epoch.

Thanks in advance.

**Comment by jgrnt** [comment]
I think this happens because the queue for the validation data is recreated at the end of every epoch, as you can see in https://github.com/keras-team/keras/blob/0d66dc4252f56bec1214874dbf766bdbb2c9ac10/keras/engine/training.py#L2163

I would suggest to actual create the `Enqueuer` for the validation outside of the loop over epochs.
If there are no objections, I will prepare a pull request.

**Comment by sccrthlt** [comment]
Can we reopen this issue?  I am experiencing extremely slow evaluation times using the following configuration:

    model.fit_generator(gen_train,
                        validation_data=gen_val,
                        validation_steps=1,
                        steps_per_epoch=1,
                        epochs=epochs,
                        verbose=1,
                        callbacks=[cb_tens, cb_checkpoint, cb_early_stop],
                        use_multiprocessing=False,
                        workers=1)

Additionally, looks like ab97958 failed and therefore this issue has not fixed.
