### ISSUE TITLE
Running custom RNN Cells within the Bidirectional wrapper produces an unknown layer error

### ISSUE THREAD

**Issue by IoDmitri** [keras-team/keras#8847]
I'm having issues with running an RNN that uses a custom cell when it's used with the `Bidirectional(...)` wrapper. [here](https://stackoverflow.com/questions/47899040/keras-bidirectional-layer-with-custom-rnn-cell) is my SO post that details the issue.

**Comment by mpariente** [comment]
You may want to check the link between the [LSTMCell](https://github.com/keras-team/keras/blob/master/keras/layers/recurrent.py#L1568) and the layer [LSTM](https://github.com/keras-team/keras/blob/master/keras/layers/recurrent.py#L1811) which can be used with `Sequential()`. 
If you want more help, you should consider providing the code.

**Comment by IoDmitri** [comment]
@mpariente I've went ahead and provided my code along with a fuller stack trace.
