### ISSUE TITLE
Vis_utils.plot_model doesn't show built-in activation

### ISSUE THREAD

**Issue by Akababa** [keras-team/keras#8870]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

https://github.com/Akababa/Chess-Zero/blob/nohistory/model.png
The dense_1 dense is 

        x = Dense(mc.value_fc_size, kernel_regularizer=l2(mc.l2_reg), activation="relu")(x)

but activation isn't shown on the model.png.

**Comment by gabrieldemarmiesse** [comment]
Hi.
I think this is a decision to avoid bloating the png. If you want to have a more verbose png, I think you need to increase the verbosity of your code and use "Activation" layers instead of using the keyword "activation" while declaring your dense layers. I hope it helps!
