### ISSUE TITLE
Keras LSTM example generating junk on extended training

### ISSUE THREAD

**Issue by shekit** [keras-team/keras#8871]
Hi,

I'm training the keras LSTM example(https://github.com/keras-team/keras/blob/master/examples/lstm_text_generation.py
) on an Nvidia p100. However I am noticing that after training it for several epochs, instead of the generated output improving, it actually becomes worse. It seems to flip from somewhat coherent to complete gibberish after a particular epoch.

This is the output generated at epoch 80 using the nietzche text and temperature 0.2:
`character, he has also his typical experiences and as the fact that is all the spirits of the same the spirits of the conscious of the`

This is the output generated at epoch 81 using the nietzche text and temperature 0.2:
`whatever depth, mystery, disguise, sp a n eot  o id in t t in a en  t te  i fett ao   tatthet t te tie atn t ie  thetn i) tt   fe  h a ant $
 ee tthrtit n ft an nteet, a st ti tin oe ithe ih tre ara i e te tent  ue  f t  aeesn  the he`

I let this training run for 220 epochs but it only became worse.

I have tried this example on my own much larger corpus' of text as well(~7M) and notice the same behaviour, except it starts spewing out gibberish around epoch 5.

Is there any idea as to why it is exhibiting this behaviour? Why does the generated text flip to complete gibberish after one specific epoch? There seems to be a direct correlation between the length of the corpus and how soon it flips over to gibberish.

**Comment by tRosenflanz** [comment]
Overfitting possibly?
