### ISSUE TITLE
980ti vs 1080ti memory usage for each batch 

### ISSUE THREAD

**Issue by nasergh** [keras-team/keras#8872]
Hi
i have two computer 
computer 1 = 8Gig ram , 1Tera HDD, VGA 980 with 4 gig ram. 
computer 2= 16gig ram, 128 SSD, VGA 1080ti with 11 gig ram.
same model run in both computer with same data.
in computer 1 i can set batch size maximum to 16(more than 16 tersor give memory error) mean 4gig/16 = each gig = 4 batch.
but in computer 2 i can only set batch size maximum to 24(and with 25 batchsize it's give memory error) but if we calculate batch size based on 980 then we must can set batchsize = 4*11 = 44 !!  but i can't set it more than 24 !(it's give error of memory)
in computer 1 each batch use 237 MB,
but in computer 2 each batch use 445 MB 
why ?!

**Comment by ozabluda** [comment]
Maybe cuDNN uses faster, but more memory-intensive algorithms on computer 2? You may also have other programs eating GPU memory on computer 2.

**Comment by nasergh** [comment]
yes Cudnn and cuda is different 
cuda 8 and cudnn 5 is on computer 1 
and cuda 9 and cudnn 7 is on computer2
it's mean than new cudnn7 use double memory than cudnn 5 ?!

i check there is no other program to eat the GPU

**Comment by tRosenflanz** [comment]
Get both computers to the same Cuda/Cudnn versions first, it might not be the Keras issue.
