### ISSUE TITLE
LSTM Seq2Seq autoencoder input incompability error

### ISSUE THREAD

**Issue by hkmztrk** [keras-team/keras#8889]
I'm trying to run the Seq2Seq example here, https://blog.keras.io/building-autoencoders-in-keras.html

```
from keras.layers import Input, LSTM, RepeatVector
from keras.models import Model

inputs = Input(shape=(timesteps, input_dim))
encoded = LSTM(latent_dim)(inputs)

decoded = RepeatVector(timesteps)(encoded)
decoded = LSTM(input_dim, return_sequences=True)(decoded)

sequence_autoencoder = Model(inputs, decoded)
encoder = Model(inputs, encoded)
```
My input is categorical encoding, e.g. [1, 23, 6, 12, 4, 0, 0, 0], which has 25 categories and fixed length of 1000.

So, the updated version of the code looks like:

```
    MInput = Input(shape=(MAX_LEN, CATEGORY_NUMS))
    encode_seq = LSTM(32)(MInput)

    decode_seq = RepeatVector(MAX_LEN)(encode_seq)
    decode_seq = LSTM(CATEGORY_NUMS, return_sequences=True)(decode_seq)

    autoencoder = Model(MInput, decode_seq)
    encoder = Model(MInput, encode_seq)
```
However, I'm getting " Input 0 is incompatible with layer lstm_2: expected ndim=3, found ndim=2" error.

Adding return_sequences=True to the first LSTM layer or removing the RepeatVector all give incompability error.

I'm not sure how else I have to prepare my input.

Thanks!

**Comment by gabrieldemarmiesse** [comment]
Hi, Maybe I can help. 
Can you give the complete trace of the error? Also, make sure that the input data that you use to feed the network have 3 dimensions : (samples,  MAX_LEN, CATEGORY_NUMS).
My first guess is that your numpy array isn't this shape. That's why keras is complaining. Your network looks fine. But I don't think your input data is. 

Hope it helps.

**Comment by hkmztrk** [comment]
Thanks @gabrieldemarmiesse !

So I simply changed my code as (3 for time-steps):

```
    **MInput = Input(shape=(3, MAX_LEN, CATEGORY_NUMS))**
    encode_seq = LSTM(32)(MInput)

    decode_seq = RepeatVector(MAX_LEN)(encode_seq)
    decode_seq = LSTM(CATEGORY_NUMS, return_sequences=True)(decode_seq)

    autoencoder = Model(MInput, decode_seq)
    encoder = Model(MInput, encode_seq)
```

But I'm having a similar error to my first one, "Input 0 is incompatible with layer lstm_1: expected ndim=3, found ndim=4"

**Comment by gabrieldemarmiesse** [comment]
Okay, I think I understand your issue. The right network to use in your case is this one:

MInput = Input(shape=(MAX_LEN, CATEGORY_NUMS))
    encode_seq = LSTM(32)(MInput)

    decode_seq = RepeatVector(MAX_LEN)(encode_seq)
    decode_seq = LSTM(CATEGORY_NUMS, return_sequences=True)(decode_seq)

    autoencoder = Model(MInput, decode_seq)
    encoder = Model(MInput, encode_seq)

The difficulty is to make sure that the numpy array you're giving has the right shape.
If I understand correctly, your numpy array is of shape (1000,1000). But your neural network expect an numpy array of shape (1000, 1000, 25). 
So you need to do a one hot encoding to make this last dimension appear on your numpy array before feeding it to your neural network.
In your case, you have to make sure that the numpy array you're giving is one hot encoded and is 3 dimensional. The rest should work out. 

Hope this helps.
