### ISSUE TITLE
Bugs code in tutorial seq2seq

### ISSUE THREAD

**Issue by astrung** [keras-team/keras#8893]
in this tutorial from keras : https://blog.keras.io/a-ten-minute-introduction-to-sequence-to-sequence-learning-in-keras.html, they predict new word without reset states after each sentences. Is it correct ? I think it is wrong . we need to reset encode hidden state after each sequence, or it can lead us to bad result. I meant this code : 

    def decode_sequence(input_seq):
    # Encode the input as state vectors.
    states_value = encoder_model.predict(input_seq)

need to be like this : 

    def decode_sequence(input_seq):
    encoder_model.reset_states() #we reset state after each sequence
    # Encode the input as state vectors.
    states_value = encoder_model.predict(input_seq)

**Comment by astrung** [comment]
hi. can any one check it ?

**Comment by CharlesAuthier** [comment]
I think if you want to change a code ever in the documentation the best is to change it and make a PR with the justification.
