### ISSUE TITLE
Keras prints no output, high memory and CPU usage and GPU is not used when using Tensorflow Callback

### ISSUE THREAD

**Issue by ghost** [keras-team/keras#8896]
Hi all,
I've had an issue with Keras recently and I thought I may post it here, since it may be a bug.
This [question](https://stackoverflow.com/questions/47981775/keras-prints-no-output-high-memory-and-cpu-usage-and-gpu-is-not-used-when-using) on stackoverflow describes the issue in detail.

**Comment by gabrieldemarmiesse** [comment]
Hi! If I can give a wild guess, the doc for tensorboard callback says: write_graph: whether to visualize the graph in TensorBoard. The log file can become quite large when write_graph is set to True. Can you please try with write_graph set to False and tell us if it was the issue? Thank you.

**Comment by vojavocni** [comment]
Hi gabrieldemarmiesse, thanks for the response. Sorry for being a bit late with feedback.
I have tried what you have said, but it still behaves the same. I'll take a look into the TensorboardCallback code when I have time, maybe I find something.

**Comment by gabrieldemarmiesse** [comment]
Thanks!
