### ISSUE TITLE
 'ModuleNotFoundError : no module named tensorflow'

### ISSUE THREAD

**Issue by T-DS** [keras-team/keras#8897]
Hi
I have successfully installed theano, tensorflow and keras but I always get this error each time I try to import keras.

My OS is windows 10
I am now using python 3.5 (was 3.63 but had to reinstall anaconda with python 3.5 when troubleshooting)

Kindly help

Thanks

**Comment by gabrieldemarmiesse** [comment]
Hi! Does the error appear when typing only "import tensorflow" in the interpreter? If it does, then it's not really related to keras and you should try to reinstall Tensorflow from scratch (and open an issue in the Tensorflow repo if really necessary). Please tell us the result of just doing "import tensorflow", it should help. Thank you.

**Comment by T-DS** [comment]
Hi
I have been able to run import keras, import tensorflow and import theano successfully.
However, when I try to run 'from keras.model import Sequential' it threw this error:

ImportError: No module named 'keras.model'

Same issues with 'from keras.layers import Dense'

Thanks once again

**Comment by gabrieldemarmiesse** [comment]
For your first issue, this is because it's keras.models instead of
keras.model.
For the second one, it's a bit strange I must admit. Can you type "from
keras.layers import Dense" in the interpreter and give me the full
stacktrace?

**Comment by T-DS** [comment]
Hi
Thanks a lot for your response. I can confirm that the issue is now resolved. Used from from keras.models import Sequential' and it worked fine.
Also 'from keras.layers import Dense' worked fine.

Many thanks

**Comment by gabrieldemarmiesse** [comment]
Happy to help! Can you close this issue? It helps the other issues readers know what to prioritise. Thank you!

**Comment by struggling-man** [comment]
I have same time with you . Can you tell me how resolved this issue.

**Comment by struggling-man** [comment]
Thanks, I find my trouble , my project name is "keras".
