### ISSUE TITLE
Unable to load VGG16 Weights

### ISSUE THREAD

**Issue by sudhir2016** [keras-team/keras#8905]
Trying to run VGG16 on windows PC using Keras. When the VGG16 weights are downloading after about 33 MB of 58 MB are downloaded there is an error saying ‘An existing connection was forcibly closed by the remote host’. this happens every time like there is a timeout on Github. Suggestions solicited.

**Comment by guoxiaolu** [comment]
download it manually from model zoo

**Comment by sudhir2016** [comment]
Thanks for the prompt response. I did try to download manually and place in Keras model folder but the program still tries to download and errors out. Am I doing something wrong.

**Comment by guoxiaolu** [comment]
two possible reasons: 1, top/no_top, keras.applications.vgg16.VGG16() load the top.
2, check the backend is tf/th, the default backend is th.
you'd better step in the VGG16 function, and it shows clearly.

**Comment by sudhir2016** [comment]
Many thanks. I was making a mistake. It works now.

**Comment by wasifferoze** [comment]
@sudhir2016 can you tell, how you resolve this problem. I am also getting same problem

**Comment by sudhir2016** [comment]
I was putting it in the wrong folder. You need to put in .keras/models folder.  .keras will only be visible if you enable from control panel. Hope this helps.
