### ISSUE TITLE
the output of  TimeDistributed(Dense) layer is  object not  tensor , error occurs 

### ISSUE THREAD

**Issue by guiyuliu** [keras-team/keras#8917]
hello eveyone this is my network ,error occurs in the **TimeDistributed** dense layers 

```
 input_layer=input
  lstm_dt=LSTM(100,return_sequences=True)(input_layer)
  fc_dt=TimeDistributed(Dense(3))  #error occurs

  lstm1=LSTM(100, return_sequences=True)(fc_dt)
  lstm2=LSTM(100, return_sequences=True)(lstm1)
  lstm3=LSTM(100, return_sequences=False)(lstm2)
  flatten=Flatten()(lstm3)`
```
error is 

 Layer lstm_5 was called with an input that isn't a symbolic tensor. Received type: <class 'keras.layers.wrappers.TimeDistributed'>. Full input: [<keras.layers.wrappers.TimeDistributed object at 0x7f295e0bbbd0>]. All inputs to the layer should be **tensors.**

how can I transfer the output object to an tensor>

Thank you!

**Comment by gabrieldemarmiesse** [comment]
Hi!
Maybe try this:

input_layer=input
lstm_dt=LSTM(100,return_sequences=True)(input_layer)
  fc_dt=TimeDistributed(Dense(3)) (lstm_dt)

  lstm1=LSTM(100, return_sequences=True)(fc_dt)
  lstm2=LSTM(100, return_sequences=True)(lstm1)
  lstm3=LSTM(100, return_sequences=False)(lstm2)
  flatten=Flatten()(lstm3)

Note that questions needs to go to stackoverflow.
Github issues in the keras repository are to report bugs in the keras codebase.
Thank you!

**Comment by Tonytony123474** [comment]
No changes b/w this,..
fc_dt=TimeDistributed(Dense(3))  #error occurs
and this..
fc_dt=TimeDistributed(Dense(3)) (lstm_dt)
Error remains the same
