### ISSUE TITLE
Activity regularizer for Conv2D numpy dtype conversion error when input has unknown dimensions (like ex. batch size)

### ISSUE THREAD

**Issue by ghost** [keras-team/keras#8922]
```
# Setup and compile the model.
model = InceptionV3(include_top=False, input_shape=(299, 299, 3))

# Set the model layers to be untrainable
for layer in model.layers:
    layer.trainable = False
    
x = model.output
x = Conv2D(512, 5, activation='relu')(x)
x = Dropout(0.3)(x)
x = Conv2D(120, 1, activation='relu', activity_regularizer=l1(x)
```
Above is given the code that reproduces this error. The following line from function cast_to_floatx in keras/backend/common.py is causing the problem:

`return np.asarray(x, dtype=_FLOATX)`

Debugging this, I have found that the the shape of x has an unknown batch size (x = Tensor("conv2d_287/Relu:0", shape=(?, 4, 4, 120), dtype=float32)), so numpy raises the ValueError: setting an array element with a sequence. It seems this code needs to be changed in order for this to be working properly.

**Comment by tRosenflanz** [comment]
When is the error happening? You might just have a typo in the last line.
This code runs without any problem on my side: 
```
# Setup and compile the model.
from keras.layers import * 
from keras.applications import * 
from  keras.regularizers import *
model = InceptionV3(include_top=False, input_shape=(299, 299, 3))

# Set the model layers to be untrainable
for layer in model.layers:
    layer.trainable = False
    
x = model.output
x = Conv2D(512, 5, activation='relu')(x)
x = Dropout(0.3)(x)
x = Conv2D(120, 1, activation='relu', activity_regularizer=l1(.0001))(x)
```
