### ISSUE TITLE
How to build correctly data with a LSTM NN?

### ISSUE THREAD

**Issue by jrmyyy** [keras-team/keras#8925]
I have a problem with the way of creating my data for a NN with a LSTM layer. I have **many files** containing hundreds of lines. **Each file represents a song** and **each line represents a note with 4 values**. I want the NN read the notes with **a sequence of 10 notes** so that it can predict one note from them. If it is needed, we can fix the number of notes at 5000 per song.

So I just want to know which **shape my input and output data** should have and how to define the first LSTM layer.

 `model = Sequential()`
`model.add(LSTM(32, input_shape=(5000, 4),return_sequences=True))`

To sump up:

 - One file has 5000 lines and 4 columns and represents 1 song.
 
 - One line in a file represent one note with 4 values. 

Thank you for your help.

**Comment by harshini-gadige** [comment]
Hi

This issue isn't related to a bug/enhancement/feature-request or other accepted types of issue.

To ask questions, please see the following resources :

https://keras.io/
https://keras.io/#support
https://gitter.im/Keras-io/Lobby

Thanks!
