### ISSUE TITLE
How to implement models with multiple inputs with different samples [different batch size on different inputs]?

### ISSUE THREAD

**Issue by wonniu** [keras-team/keras#8943]
I would like to implement a model with multiple inputs, where each input may have different number of samples when training the model. I wonder whether there are any ways to implement this, or I have to use other more flexible library, like tensorflow. A similar question has been raised in stackoverflow [https://stackoverflow.com/questions/44101692/implementing-a-multi-input-model-in-keras-each-with-a-different-sample-sizes-ea], but no solution yet.
Here is a figure about possible structure of the model from the stackoverflow question.
![image](https://user-images.githubusercontent.com/29226171/34483160-b5bbc098-eff7-11e7-8976-94ffed66ee1a.png)

Thank you for your help!

================code examples======================
import numpy as np
from keras.layers import Input, add, concatenate
from keras.models import Model 
from keras.optimizers import RMSprop

x = []
for i in range(2):
    x.append(Input(shape=(1,)))
x0 = 2*[x[0]]
x0 = concatenate(x0, axis=0)
y = add([x0, x[1]])
model = Model(inputs=x, outputs=y)
model.compile(loss="binary_crossentropy", optimizer=RMSprop())

input_x1 = np.array([[1], [-1]]).reshape(2, 1)
input_x2 = np.array([[-1], [1], [-1], [1]]).reshape(4, 1)
input_y = np.array([1,1,1,1])

model.train_on_batch([input_x1, input_x2], input_y)
===================================================

-------------------------------------------------------------------------------------------------------------------------------------------ValueError                   Traceback (most recent call last)
<ipython-input-87-6048368f3789> in <module>()
     50 input_y = np.array([1,1,1,1])
     51 
---> 52 model.train_on_batch([input_x1, input_x2], input_y)
     53 
     54 

/root/anaconda2/lib/python2.7/site-packages/keras/engine/training.pyc in train_on_batch(self, x, y, sample_weight, class_weight)
   1634             sample_weight=sample_weight,
   1635             class_weight=class_weight,
-> 1636             check_batch_axis=True)
   1637         if self.uses_learning_phase and not isinstance(K.learning_phase(), int):
   1638             ins = x + y + sample_weights + [1.]

/root/anaconda2/lib/python2.7/site-packages/keras/engine/training.pyc in _standardize_user_data(self, x, y, sample_weight, class_weight, check_batch_axis, batch_size)
   1321                           for (ref, sw, cw, mode)
   1322                           in zip(y, sample_weights, class_weights, self._feed_sample_weight_modes)]
-> 1323         _check_array_lengths(x, y, sample_weights)
   1324         _check_loss_and_target_compatibility(y,
   1325                                              self._feed_loss_fns,

/root/anaconda2/lib/python2.7/site-packages/keras/engine/training.pyc in _check_array_lengths(inputs, targets, weights)
    218         raise ValueError('All input arrays (x) should have '
    219                          'the same number of samples. Got array shapes: ' +
--> 220                          str([x.shape for x in inputs]))
    221     set_y = set(y_lengths)
    222     if len(set_y) > 1:

ValueError: All input arrays (x) should have the same number of samples. Got array shapes: [(2, 1), (4, 1)]
-------------------------------------------------------------------------------------------------------------------------------------------

**Comment by wonniu** [comment]
tensorflow can do that ...

**Comment by siddsuresh97** [comment]
I'm trying to train a keras model with multiple inputs using tfrecords. 
The number of samples in both the inputs are the same but the 4th dimension is different. One input is an optical flow(along x and y axes (so two dimension)) and the other is a frame(with three color channels).

ValueError: Dimension 3 in both shapes must be equal, but are 2 and 3. Shapes are [10,240,320,2] and [10,240,320,3].
	From merging shape 0 with other shapes. for 'stack_1' (op: 'Pack') with input shapes: [10,240,320,2], [10,240,320,3].

Any ideas on how i can proceed?

**Comment by cottrell** [comment]
> tensorflow can do that ...

Can you elaborate a bit? Do you mean one should abandon Keras if you are trying to do multi inputs with different shapes (no shared batch size)? Do you need to abandon all aspects of keras or just some part of it? I have not found a clear path to solve this yet so any advice would be helpful

**Comment by binod132** [comment]
I have same issue

**Comment by cottrell** [comment]
FYI, I think the one true way is now to subclass tf.keras.models.Model and use tensorflow 2.0. 

Only use keras functional API for trivial models.

The below example pattern is pretty good and fully generalizable AFAIK. You could also probably use Layer but Model gives you the trainable variables and you can chain models as layers no problem.

```
class Controller(tf.keras.models.Model):
    def __init__(self, u_dim):
        super().__init__()
        self._layers = [tf.keras.layers.Dense(u_dim)]  # linear

    #@tf.function not sure if you always benefit from this
    def call(self, y, wu):
        for layer in self._layers:
            y = layer(y)
        return y + wu
```

**Comment by czarmanu** [comment]
I have the same issue. Anybody solved it with keras?

**Comment by cottrell** [comment]
@czarmanu Use the keras subclass API as above. Everything is much easier like that. More explicit. Looks more verbose but is worth it.

**Comment by rebeen** [comment]
@cottrell  I am trying to apply two models on two different datasets where only the number of samples are different 

# =====================================================================
headline_data = np.round(np.abs(np.random.rand(12, 180) * 100)).reshape(12,15,12)
print(headline_data.shape)
# additional_data = np.random.randn(12, 180).reshape(12,15,12) # I want to change the number of sample from 12 to N
additional_data = np.random.randn(20, 180).reshape(20,15,12) # let is say N= 20

print(additional_data.shape)
headline_labels = np.random.randn(12, 11)
print(headline_labels.shape)
# additional_labels = np.random.randn(12, 10) #I want to change the number of sample from 12 to N
additional_labels = np.random.randn(20, 10) # # let is say N= 20

print(additional_labels.shape)

**Comment by kealennieh** [comment]
@siddsuresh97  have you solved the problem? I've got the same issue. Any suggestion ?

**Comment by innat** [comment]
Why it is closed without any feedback?
