### ISSUE TITLE
Training a Complex Model

### ISSUE THREAD

**Issue by sezan92** [keras-team/keras#8959]
Hello, I was wondering to work on a project based on Keras. In this project , first i will have to train a model based on some data. After training, I will have to get the cost of the first layer. Then I will have to back propagate the same cost through another architecture and train that architecture based on that cost. 

how can I do that? The model is roughly like following
![aww-board](https://user-images.githubusercontent.com/11025093/34558960-40043cda-f16a-11e7-8401-bc06a35aa368.png)

**Comment by harshini-gadige** [comment]
Hi

Since this is not a bug/feature request, request you to post these kind of questions in any of the following.

https://keras.io/
https://keras.io/#support
https://gitter.im/Keras-io/Lobby

Thanks!
