### ISSUE TITLE
Strange behavior of the '/'-operator in Keras

### ISSUE THREAD

**Issue by Joeman17** [keras-team/keras#8961]
Hello, 
I found some strange behavior of the '/'-operator in Keras.
I'm training a u-net using the inverse Dice-Coefficient defined as follows (the numpy version is exactly 
the same): 

```
smooth = 1.0
def dice_coef(y_true, y_pred):
    y_true_f = K.flatten(y_true)
    y_pred_f = K.flatten(y_pred)
    intersection = K.sum(y_true_f * y_pred_f)
    return (2. * intersection + smooth) / (K.sum(y_true_f) + K.sum(y_pred_f) + smooth)
```
I compared the validation DSC of the fit function to the validation DSC calculated by the evaluate function and by numpy. For each case I got a different result (see table).

As next step I printed the numerator and the denominator of each case and found out that wolframalpha gives the same result for the DSC as the numpy version even using nominator and denominator of the fit() or evaluate() function. 

| function | loss | DSC | numerator | denominator |
| ---------- | ----- | ------ | ------------- | ---------------- |
| fit           | 0.9165 | 0.2834 | 7378 | 11192 |
| evaluate |0.9005 | 0.2993 | 14755 | 22384 |
| numpy | |0.6591 | 118030 | 179064 |

- Why are numerator and denominator different in each case(both approximately divided by the same factor in comparison to the numpy version)? 
- Why are the results of the '/'-operation different in Keras and in numpy?
- Is there a better way to perform a division in Keras as I did?

Thanking you in anticipation
Thomas

**Comment by tRosenflanz** [comment]
Is it possible that you are doing summation along different axes between Keras and Numpy? Just a guess since a difference between the two is within a factor of each other

**Comment by Joeman17** [comment]
The array, respectively the tensor, is 1-dimensional after flatten(). The summation is then performed over all elements. 
Is there maybe some kind of automatic normalization of Tensors in Keras?
