### ISSUE TITLE
Multi gpu model creates duplicate model names for models with multiple outputs

### ISSUE THREAD

**Issue by BAXTER001** [keras-team/keras#8962]
Seems to be caused at the model merge stage:

https://github.com/keras-team/keras/blob/45c838cc7a0a5830c0a54a2f58f48fc61950eb68/keras/utils/training_utils.py#L172_L177

Reproduction of the issue here along with possible change that would suffix the model names running on the GPUs uniquely by index:
https://gist.github.com/BAXTER001/5b2bb9e65b587f893298f09102436ca1
https://github.com/keras-team/keras/compare/master...BAXTER001:patch-1

**Comment by danielegrattarola** [comment]
Any updates on this one?

**Comment by smsaladi** [comment]
bump

**Comment by praveen7728** [comment]
Any updates?
