### ISSUE TITLE
Is keras have save/restore API to save training process periodically?

### ISSUE THREAD

**Issue by scotthuang1989** [keras-team/keras#8963]
I just start using keras. But I train  a model for 5 minutes and at the end of the program, I have a bug. I have to start over.  In tensorflow I usually save training to checkpoint file periodically. I check keras documentation. Don't find anything related to it. 

Does keras have this function?

**Comment by Dref360** [comment]
Please see ModelCheckpoint
https://keras.io/callbacks/

**Comment by scotthuang1989** [comment]
thanks very much. a lot of useful tool in callbacks..
