### ISSUE TITLE
Decode prediction of a non-ImageNet model

### ISSUE THREAD

**Issue by GKalliatakis** [keras-team/keras#8964]
I want to decode predictions from non-ImageNet trained models but [Places 2 Database](http://places2.csail.mit.edu/).

More specifically I want to Classify Places classes with VGG16-places365 taken from https://github.com/GKalliatakis/Keras-VGG16-places365, however the custom  [decode_predictions function ](https://github.com/GKalliatakis/Keras-VGG16-places365/blob/master/places_utils.py)returns the same results always. Any thoughts on this or how to write the necessary custom function?

**Comment by rvinamra** [comment]
Can you please let me as to how did you resolve this issue? I am stuck in a similar problem. Thanks in advance.

**Comment by eOluwumi** [comment]
Same here! I actually need it for several custom models and classification tasks at hand. Looking forward to a Deux Ex Machina :) ;)

**Comment by eOluwumi** [comment]
> Can you please let me as to how did you resolve this issue? I am stuck in a similar problem. Thanks in advance.

@rvinamra if you've found a solution, kindly extend (.ext)
