### ISSUE TITLE
Recurrent Lambda Layer OR Fold Layer

### ISSUE THREAD

**Issue by risajef** [keras-team/keras#8984]
I have a question or a suggestion.

I'm working on an LSTM Network. The output for the LSTM is one float for every time-step.
Now I want to compute a function in the style of fold in functional programming over the time steps depending on the input and the output of the LSTM.
Because there is no loop over the time dimension I don't know how this could be done.
Is this already possible with the lambda layer?
If yes, could you tell me how.
If no, I think it would be useful for many applications and so be worth while implementing. Sadly I am not able to do it myself. I tried to make a custom recurrent layer but I failed.

Here a picture how this should work, where foo is the function given to the fold layer:
In the end I want to maximize M_t.

```
        x_0__               x_1__
         |   |               |   |
         |   V               |   V
         |  LSTM ------------|->LSTM-------- ...
         |   |               |   |
         |  y_0              |  y_1
         |   |               |   |
        _V___V_             _V___V_ 
M_0 -> |__foo__| -> M_1 -> |__foo__| -> M_2  ...
```

edit: I found the k_rnn function in Keras for R ([Link](https://keras.rstudio.com/reference/k_rnn.html)). This seems to be the function I want in python. But maybe not.

**Comment by tRosenflanz** [comment]
https://github.com/farizrahman4u/recurrentshop is what you want. Have a look at the examples - should be very straightforward in your case
