### ISSUE TITLE
Huge text files samples as inputs in LSTM

### ISSUE THREAD

**Issue by eduardoandrade** [keras-team/keras#9007]
My database has files of 6963200 words each (I did a left zero padding in all of them according to the bigger one). The goal is to classify if the file is of type A or B. For this goal, I have to put all the words of all the files into an LSTM. So, I am running out of memory all the time. Doing a reshape for 10000 files, I have (10000, 6963200, 1). But in this way, my input_shape of the LSTM is going to be (6963200, 1), impossible to run. What I want to do is to have an input_shape of lenght = 32, not 6963200, but I do not know how to make this and the LSTM recognize that every 32 words until 6963200 are from the same sample. Is it possible? Maybe I am going to spend more time but less memory, so I can run the LSTM. Thank you.

**Comment by grafael** [comment]
Have you tried changing the batch size? You don't need to feed the network with all "6963200" at once.

**Comment by eduardoandrade** [comment]
Where I can change this parameter? model.add(LSTM(32, input_shape=(6963200, 1))) or history = model.fit(x_train, y_train, batch_size=1, epochs=10, validation_split = 0.2)?

**Comment by grafael** [comment]
This example will help you a lot: https://machinelearningmastery.com/use-different-batch-sizes-training-predicting-python-keras/

**Comment by tRosenflanz** [comment]
There are 2 ways around your problem:
a) Stateful LSTMS
b) Variable length sequences. If majority of your files are much smaller than 6963200 you can batch them by their length (or do batch size=1)

**Comment by eduardoandrade** [comment]
Thank you, grafael.

a) I did stateful=True.
b) But what changes if I do model.add(LSTM(32, batch_input_shape=(1000, 6963200, 1))) for example? This is going to save memory? Consequence is to increase the number of epochs for good results? How can I match each file by their length?

Ok, I will try to open a stackoverflow issue.
