### ISSUE TITLE
K.ctc_decode() memory not released

### ISSUE THREAD

**Issue by LiangHao92** [keras-team/keras#9011]
when using K.ctc_decode() like the code below in a large loop, the memory cost more and more, and time cost longer and longer.

` out = K.get_value(K.ctc_decode(y_pred, input_length=np.ones(y_pred.shape[0])*y_pred.shape[1], )[0][0])[:, :]`

How can I solve it ?

**Comment by fchollet** [comment]
Can you share a large block of your code?

If you are creating Keras models repeatedly in a loop, you should do one of the following:

- Use a TF graph scope (with the TF backend) around your code, inside the loop
- Clear the previous graph and session at the end of each iteration via `K.clear_session()`

**Comment by LiangHao92** [comment]
@fchollet I use 2 TF models and 1 Keras models. I build two graph for the two TF models like that:
` with g2.as_default():
        ...
        saver = tf.train.Saver()        
        saver.restore(sess, models)`
and initialize keras model like:
`model,basemodel = get_model(height=imgH, nclass=nclass)
    basemodel.load_weights(modelPath)`
I initialize the three models, and use theme in the loop. 
I wonder if I need build a graph for the keras model like TF models. When I tried to  use the code like:
`` with g2.as_default():
        ...
        model,basemodel = get_model(height=imgH, nclass=nclass)
        basemodel.load_weights(modelPath)``
The error occurs.

**Comment by LiangHao92** [comment]
@fchollet I use 2 TF models and 1 Keras models. I build two graph for the two TF models like that:
with g2.as_default(): 
`  ...
    saver = tf.train.Saver()
    saver.restore(sess, models)`
and initialize keras model like:
`model,basemodel = get_model(height=imgH, nclass=nclass) 
basemodel.load_weights(modelPath)`
I initialize the three models, and use theme in the loop.
I wonder if I need build a graph for the keras model like TF models. When I tried to use the code like:
`with g2.as_default(): 
    ...
   model,basemodel = get_model(height=imgH, nclass=nclass)
   basemodel.load_weights(modelPath)`
The error occurs.

**Comment by idrisalshikh** [comment]
I have the same problem with one model I'm using [ this code](https://colab.research.google.com/drive/1CdB9rvImJCAl_U9yYVD6HqMFWup_RzpG#scrollTo=jgoI5JMO1zcX)
in one loop I print the time after 100 samples and the result was like this
=100
--- 5.458444833755493 seconds ---
i=200
--- 7.28910493850708 seconds ---
i=300
--- 9.28484296798706 seconds ---
i=400
--- 11.521419763565063 seconds ---
i=500
--- 14.196611166000366 seconds ---

**Comment by soulbyfeng** [comment]
base_pred = self.base_model.predict(x=x_in)
r = K.ctc_decode(base_pred, in_len, greedy=True, beam_width=100, top_paths=1)
r1 = K.get_value(r[0][0])
when i run predict for 100 times  memory is adding
how i solve it ? thx @LiangHao92

**Comment by soulbyfeng** [comment]
@LiangHao92  can you help me
