### ISSUE TITLE
keras.backend.stack not implemented for CNTK backend

### ISSUE THREAD

**Issue by birolkuyumcu** [keras-team/keras#9017]
when using keras.backend.stack function with CNTK backend rises a

> AttributeError: module 'keras.backend' has no attribute 'stack'

i checked code keras.backend.stack not implemented for CNTK backend

**Comment by n17s** [comment]
In CNTK you would do something like
```python
C.splice(*x, axis=C.Axis.new_leading_axis()))
```
to achieve this.

**Comment by gabrieldemarmiesse** [comment]
This has been fixed.
