### ISSUE TITLE
Keras: error training parallel CNN's model (ValueError: Layer model_1 expects 10 inputs, but it received 1 input tensors. Input received: [<tf.Tensor 'model_1_input:0' shape=(?, 30, 125, 1) dtype=float32>])

### ISSUE THREAD

**Issue by tharuniitk** [keras-team/keras#9021]
@farizrahman4u Hello Sir,

I was running the following reproducible script to train a parallel multiple CNN's model each CNN with its own input. I receive the following error when I run the model in keras with tf backend. The screenshot of error is attached. Kindly help. My OS is Ubuntu 14.04, Cuda 8.0. There are issues (https://github.com/kuza55/keras-extras/issues/14) already present on a similar problem but it doesn't solve the error received when I run this script. Please help resolve!!

from keras.models import Sequential, Model
from keras.layers.embeddings import Embedding
from keras.layers.core import Activation, Dense, Dropout
from keras.layers import Merge, Conv1D, Conv2D, Flatten
from keras.layers.recurrent import GRU, LSTM
#from keras.datasets.data_utils import get_file
import tarfile
import numpy as np
from keras.callbacks import EarlyStopping
from workshop_utils import tokenize, parse_stories, get_stories, vectorize_stories
from keras import optimizers
import tensorflow as tf
import scipy.io
from keras import backend as K
from keras.layers import Input

import keras 
nb_filters =20
kernel_size1= [1,64]
kernel_size2= [64,1]

no_parallel_CNN = 10

# create seperate model graph for parallel processing with different filter sizes
# apply 'same' padding so that ll produce o/p tensor of same size for concatination
# cancat all paralle output

#https://stackoverflow.com/questions/43172122/easy-way-of-representing-multiple-inputs-in-keras
input1=np.random.rand(5169,30,125,1)
input2=np.random.rand(5169,30,125,1)
input3=np.random.rand(5169,30,125,1)
input4=np.random.rand(5169,30,125,1)
input5=np.random.rand(5169,30,125,1)
input6=np.random.rand(5169,30,125,1)
input7=np.random.rand(5169,30,125,1)
input8=np.random.rand(5169,30,125,1)
input9=np.random.rand(5169,30,125,1)
input10=np.random.rand(5169,30,125,1)
y1=np.random.rand(5169,1)

input_shape=(30,125,1)
inp1 = Input(shape=input_shape)
inputs_list = [Input(shape=(30,125,1)) for i in range(no_parallel_CNN)]
conv_1_list = [Conv2D(filters = 32, kernel_size = (1,64) , padding = "same" , activation = "relu" )(input_tensor) for input_tensor in inputs_list]
conv_2_list = [Conv2D(filters = 32, kernel_size = (64,1), padding = "same" , activation = "relu" )(input_tensor) for input_tensor in conv_1_list]
print len(inputs_list)
print inputs_list

if no_parallel_CNN > 1:
    out=keras.layers.concatenate(conv_2_list)#out = Merge(mode='concat')(conv_2_list)
else:
    out = conv_2_list[0]

conv_model = Model(input=inputs_list, output=out)

m1=Sequential()
m1.add(conv_model)
m1.add(Dropout(0.2))
m1.add(Flatten())
m1.add(Dropout(0.2))
m1.add(Dense(1000,activation='relu'))
m1.add(Dropout(0.2))
m1.add(Dense(500,activation='relu'))
m1.add(Dropout(0.2))
m1.add(Dense(1, activation='sigmoid'))

m1.compile(loss='mean_squared_error', optimizer='RMSprop')

early_stopping = EarlyStopping(monitor='val_loss', patience=2)
#with tf.device('/gpu:0'):
m1.fit([input1,input2,input3,input4,input5,input6,input7,input8,input9,input10], y1, validation_split=0.5, callbacks=[early_stopping])

![error_layer_expects_multipleinputs_but_receivedone](https://user-images.githubusercontent.com/18737816/34723804-d29fc608-f571-11e7-8f0f-8d345b266608.png)

**Comment by kwkwvenusgod** [comment]
I met the same error with you. Do you have any idea to solve it ?
