### ISSUE TITLE
keras docker: problem installing dependencies

### ISSUE THREAD

**Issue by eduardoandrade** [keras-team/keras#9033]
It happens when I try to build the Dockerfile

...
Installing collected packages: sklearn-pandas
Successfully installed sklearn-pandas-1.6.0
Cloning into '/src'...
fatal: unable to connect to github.com:
github.com[0: 192.30.253.112]: errno=Connection timed out
github.com[1: 192.30.253.113]: errno=Connection timed out

The command '/bin/sh -c conda install -y python=${python_version} &&     pip install --upgrade pip &&     pip install tensorflow-gpu &&     pip install https://cntk.ai/PythonWheel/GPU/cntk-2.1-cp35-cp35m-linux_x86_64.whl &&     conda install Pillow scikit-learn notebook pandas matplotlib mkl nose pyyaml six h5py &&     conda install theano pygpu bcolz &&     pip install sklearn_pandas &&     git clone git://github.com/keras-team/keras.git /src && pip install -e /src[tests] &&     pip install git+git://github.com/keras-team/keras.git &&     conda clean -yt' returned a non-zero code: 128

**Comment by jgrnt** [comment]
Looks like you can't connect to GitHub via git protocol.
To verify you can run ```git clone git://github.com/keras-team/keras.git /tmp/keras``` on your computer.

To fix: change  ```git clone git://github.com/keras-team/keras.git /src``` to ```git clone https://github.com/keras-team/keras.git /src```  and ```pip install git+git://github.com/keras-team/keras.git``` to  ```pip install git+https://github.com/keras-team/keras.git```

**Comment by eduardoandrade** [comment]
Solved, jgrnt! Thank you
