### ISSUE TITLE
ValueError: In a stateful network, you should only pass inputs with a number of samples... 

### ISSUE THREAD

**Issue by AVSuni** [keras-team/keras#9036]
I am trying to train a stateful RNN with 96836083 training samples and 10759565 test samples. My batch size is 512, so  96836083/512 = 189132 and 10759565/512 = 21014.  I get

`< ValueError      Traceback (most recent call last)
<ipython-input-39-ba74ad7cbaad> in <module>()
----> 1 model.fit(X_train, y_train, epochs=3, batch_size = 512, verbose=1, validation_data=(X_test,y_test), shuffle=False, callbacks=[early_stop])
      2 model.save_weights('strawberry.h5')
      3 exp.end()

/home/user/anaconda3/envs/tensorflow/lib/python2.7/site-packages/keras/models.pyc in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, **kwargs)
    958                               initial_epoch=initial_epoch,
    959                               steps_per_epoch=steps_per_epoch,
--> 960                               validation_steps=validation_steps)
    961 
    962     def evaluate(self, x, y, batch_size=32, verbose=1,

/home/user/anaconda3/envs/tensorflow/lib/python2.7/site-packages/keras/engine/training.pyc in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, **kwargs)
   1579             class_weight=class_weight,
   1580             check_batch_axis=False,
-> 1581             batch_size=batch_size)
   1582         # Prepare validation data.
   1583         do_validation = False

/home/user/anaconda3/envs/tensorflow/lib/python2.7/site-packages/keras/engine/training.pyc in _standardize_user_data(self, x, y, sample_weight, class_weight, check_batch_axis, batch_size)
   1434                                  'a number of samples that can be '
   1435                                  'divided by the batch size. Found: ' +
-> 1436                                  str(x[0].shape[0]) + ' samples')
   1437         return x, y, sample_weights
   1438 

ValueError: In a stateful network, you should only pass inputs with a number of samples that can be divided by the batch size. Found: 96836083 samples`

Keras 2.1.2
Tensorflow 1.30

**Comment by tomastheod-ITI** [comment]
@AVSuni You should delete a few samples from your arrays, or add a few samples with all zeros in the test set, so that the samples dimension is a multiple of batch size.
For example, delete a few samples from both arrays so that they have sizes:

189132 * 512 = 96835584
21014 * 512 = 10759168

**Comment by AVSuni** [comment]
@tomastheod-ITI thanks! I made the mistake of doing the division in Python, so I didn't see the decimals.
