### ISSUE TITLE
classes list for xception model

### ISSUE THREAD

**Issue by ink1** [keras-team/keras#9039]
Apologies if this has already been asked but I could not find the answer.
Where can I find a list of classes for the xception and other models when used with the top layer?
Thanks

**Comment by ink1** [comment]
Experimentally, it looks like the classes are sorted alphabetically so this is what I'm going to take forward but it would be still nice if someone can confirm this.
```
classnames = [d for d in os.listdir('train') if os.path.isdir(os.path.join('train', d))]
classnames = sorted(classnames)
```

**Comment by fchollet** [comment]
I don't understand what you mean? Please clarify.

**Comment by ink1** [comment]
Hi François and thank you for all your work. When you run a prediction using a downloaded model you get a list of 1000 probabilities but you don't necessarily know what each category is. I've seen files floating around, e.g. imagenet1000_clsid_to_human.txt and it might be that a canonical list of categories is buried somewhere in image-net.org. What I mean is a list 
```
classnames = ['n01440764',  'n01443537', ... ]
```
Ordering the categories alphabetically is the most natural thing to do and perhaps is taken for granted.

Incidentally I'm trying to reproduce Imagenet training described in your Xception paper using Keras (and will be happy to share the recipe) and have a couple of questions about pre-processing, cropping and training schedule. Unless all this is already detailed somewhere (I could not find any detailed instructions for training on Imagenet from scratch), where would be the most suitable place to ask these sort of questions?
