### ISSUE TITLE
how to convert hd5 file to ckpt

### ISSUE THREAD

**Issue by akshay951228** [keras-team/keras#9040]
I have model build in keras and save in **hd5** file format.How to convert to tensorflow ckpt file

**Comment by fchollet** [comment]
You can load your Keras model (with the Keras backend), then export a TF checkpoint of the TF graph created when loading the Keras model.

In general, I would recommend posting this kind of question on stackoverflow.

Essentially something like:

```python
# Add ops to save and restore all the variables.
saver = tf.train.Saver()
model = keras.models.load_model("model.h5")
sess = keras.backend.get_session()
save_path = saver.save(sess, "/tmp/model.ckpt")
```

**Comment by GustavZ** [comment]
@fchollet is this also working the other way round?
So converting ckpt to h5?
How would that look like?

**Comment by JonathanCMitchell** [comment]
@GustavZ Nope it doesn't. You basically have to load the checkpoint file, extract the weights, save them, and then use `set_weights` to load them into the keras model.

**Comment by santhoshnumberone** [comment]
> 
> 
> You can load your Keras model (with the Keras backend), then export a TF checkpoint of the TF graph created when loading the Keras model.
> 
> In general, I would recommend posting this kind of question on stackoverflow.
> 
> Essentially something like:
> 
> ```python
> # Add ops to save and restore all the variables.
> saver = tf.train.Saver()
> model = keras.models.load_model("model.h5")
> sess = keras.backend.get_session()
> save_path = saver.save(sess, "/tmp/model.ckpt")
> ```

For TensorFlow 2.x

This code worked for me
```
saver = tf.train.Checkpoint()
model = keras.models.load_model('Model.hdf5')
sess = tf.compat.v1.keras.backend.get_session()
save_path = saver.save('model.ckpt')
```
