### ISSUE TITLE
Problem with TensorBoard callback (histogram) when model is called multiple times.

### ISSUE THREAD

**Issue by marmarmarmar** [keras-team/keras#9043]
Problem was first reported [here](https://stackoverflow.com/questions/48192177/keras-with-tensorflow-runs-fine-until-i-add-callbacks)

I found out that when model is compiled multiple times and default session is not cleared, an operation `tf.summary.merge_all()` called while setting a TensorBoard model in a case when one wants also to create a histogram causes an error.

Error doesn't occur when model is compiled the first time, but every next compilation and calling a `fit` method causes the following error:

> 
> ---------------------------------------------------------------------------
> InvalidArgumentError                      Traceback (most recent call last)
> <ipython-input-5-da0151e53370> in <module>()
>       4                     validation_data=(X, Y),
>       5                     shuffle=True,
> ----> 6                     callbacks=[logger])
> 
> /home/marcin/.local/lib/python2.7/site-packages/keras/models.pyc in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, **kwargs)
>     958                               initial_epoch=initial_epoch,
>     959                               steps_per_epoch=steps_per_epoch,
> --> 960                               validation_steps=validation_steps)
>     961 
>     962     def evaluate(self, x, y, batch_size=32, verbose=1,
> 
> /home/marcin/.local/lib/python2.7/site-packages/keras/engine/training.pyc in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, **kwargs)
>    1655                               initial_epoch=initial_epoch,
>    1656                               steps_per_epoch=steps_per_epoch,
> -> 1657                               validation_steps=validation_steps)
>    1658 
>    1659     def evaluate(self, x=None, y=None,
> 
> /home/marcin/.local/lib/python2.7/site-packages/keras/engine/training.pyc in _fit_loop(self, f, ins, out_labels, batch_size, epochs, verbose, callbacks, val_f, val_ins, shuffle, callback_metrics, initial_epoch, steps_per_epoch, validation_steps)
>    1231                             for l, o in zip(out_labels, val_outs):
>    1232                                 epoch_logs['val_' + l] = o
> -> 1233             callbacks.on_epoch_end(epoch, epoch_logs)
>    1234             if callback_model.stop_training:
>    1235                 break
> 
> /home/marcin/.local/lib/python2.7/site-packages/keras/callbacks.py in on_epoch_end(self, epoch, logs)
>      71         logs = logs or {}
>      72         for callback in self.callbacks:
> ---> 73             callback.on_epoch_end(epoch, logs)
>      74 
>      75     def on_batch_begin(self, batch, logs=None):
> 
> /home/marcin/.local/lib/python2.7/site-packages/keras/callbacks.py in on_epoch_end(self, epoch, logs)
>     776                     assert len(batch_val) == len(tensors)
>     777                     feed_dict = dict(zip(tensors, batch_val))
> --> 778                     result = self.sess.run([self.merged], feed_dict=feed_dict)
>     779                     summary_str = result[0]
>     780                     self.writer.add_summary(summary_str, epoch)
> 
> /home/marcin/.local/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in run(self, fetches, feed_dict, options, run_metadata)
>     887     try:
>     888       result = self._run(None, fetches, feed_dict, options_ptr,
> --> 889                          run_metadata_ptr)
>     890       if run_metadata:
>     891         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)
> 
> /home/marcin/.local/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _run(self, handle, fetches, feed_dict, options, run_metadata)
>    1118     if final_fetches or final_targets or (handle and feed_dict_tensor):
>    1119       results = self._do_run(handle, final_targets, final_fetches,
> -> 1120                              feed_dict_tensor, options, run_metadata)
>    1121     else:
>    1122       results = []
> 
> /home/marcin/.local/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
>    1315     if handle is None:
>    1316       return self._do_call(_run_fn, self._session, feeds, fetches, targets,
> -> 1317                            options, run_metadata)
>    1318     else:
>    1319       return self._do_call(_prun_fn, self._session, handle, feeds, fetches)
> 
> /home/marcin/.local/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _do_call(self, fn, *args)
>    1334         except KeyError:
>    1335           pass
> -> 1336       raise type(e)(node_def, op, message)
>    1337 
>    1338   def _extend_graph(self):
> 
> InvalidArgumentError: You must feed a value for placeholder tensor 'dense_1_input' with dtype float and shape [?,10]
> 	 [[Node: dense_1_input = Placeholder[dtype=DT_FLOAT, shape=[?,10], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
> 
> Caused by op u'dense_1_input', defined at:
>   File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py", line 16, in <module>
>     app.launch_new_instance()
>   File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 658, in launch_instance
>     app.start()
>   File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelapp.py", line 477, in start
>     ioloop.IOLoop.instance().start()
>   File "/usr/local/lib/python2.7/dist-packages/zmq/eventloop/ioloop.py", line 177, in start
>     super(ZMQIOLoop, self).start()
>   File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 888, in start
>     handler_func(fd_obj, events)
>   File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 277, in null_wrapper
>     return fn(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
>     self._handle_recv()
>   File "/usr/local/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
>     self._run_callback(callback, msg)
>   File "/usr/local/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
>     callback(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 277, in null_wrapper
>     return fn(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 283, in dispatcher
>     return self.dispatch_shell(stream, msg)
>   File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
>     handler(stream, idents, msg)
>   File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 399, in execute_request
>     user_expressions, allow_stdin)
>   File "/usr/local/lib/python2.7/dist-packages/ipykernel/ipkernel.py", line 196, in do_execute
>     res = shell.run_cell(code, store_history=store_history, silent=silent)
>   File "/usr/local/lib/python2.7/dist-packages/ipykernel/zmqshell.py", line 533, in run_cell
>     return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2718, in run_cell
>     interactivity=interactivity, compiler=compiler, result=result)
>   File "/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2822, in run_ast_nodes
>     if self.run_code(code, result):
>   File "/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
>   File "<ipython-input-2-c7a6754e3cea>", line 11, in <module>
>     model.add(Dense(10, input_dim=10, activation='relu'))
>   File "/home/marcin/.local/lib/python2.7/site-packages/keras/models.py", line 460, in add
>     name=layer.name + '_input')
>   File "/home/marcin/.local/lib/python2.7/site-packages/keras/engine/topology.py", line 1439, in Input
>     input_tensor=tensor)
>   File "/home/marcin/.local/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
>     return func(*args, **kwargs)
>   File "/home/marcin/.local/lib/python2.7/site-packages/keras/engine/topology.py", line 1348, in __init__
>     name=self.name)
>   File "/home/marcin/.local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 497, in placeholder
>     x = tf.placeholder(dtype, shape=shape, name=name)
>   File "/home/marcin/.local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1599, in placeholder
>     return gen_array_ops._placeholder(dtype=dtype, shape=shape, name=name)
>   File "/home/marcin/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3091, in _placeholder
>     "Placeholder", dtype=dtype, shape=shape, name=name)
>   File "/home/marcin/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
>     op_def=op_def)
>   File "/home/marcin/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
>     op_def=op_def)
>   File "/home/marcin/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
>     self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
> 
> InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'dense_1_input' with dtype float and shape [?,10]
> 	 [[Node: dense_1_input = Placeholder[dtype=DT_FLOAT, shape=[?,10], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

It seems that `tf.summary.merge_all()` collects tensors from previous models and this is causing a problem as calling `K.clear_session()` seems to solve the problem.

**Comment by piotrbazan** [comment]
Quick code to reproduce the issue:
```
from keras.models import Sequential
from keras.layers import Dense
import numpy as np
from keras.callbacks import TensorBoard
x, y = np.zeros((1, 5)), np.zeros((1, 1))
m = Sequential([Dense(10, input_shape=(5,)), Dense(1)])
m.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['acc'])
m.fit(x, y, validation_data=(x,y), callbacks=[TensorBoard(histogram_freq=1)])
m = Sequential([Dense(10, input_shape=(5,)), Dense(1)])
m.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['acc'])
m.fit(x, y, validation_data=(x, y), callbacks=[TensorBoard(histogram_freq=1)])
```

**Comment by connection-on-fiber-bundles** [comment]
The mysterious part to me is why `dense_1_input` shows up in the graph of the second model, where keras actually feed values to the expected one, which is `dense_2_input` when evaluating tensors

**Comment by connection-on-fiber-bundles** [comment]
I guess I know why (correct me if I am wrong):

When fitting the first model, `tf.summary.histogram` is called once creating a tensor (let's call it `histogram_a` depending on `dense_1_input`. Then when fitting the second model, `tf.summary.histogram` is called again creating another tensor (let's call it `histogram_b`) depending on `dense_2_input`. However, `tf.summary.merge_all` is called when fitting the second model, which would merge both `histogram_a` and `histogram_b`. As a result, the merged summary tensor would depends on both `dense_1_input` and `dense_2_input`. But from the point of view of 2nd model, there's no `dense_1_input` at all, so there's no way for it to feed value for that input tensor.

@fchollet I feel it's more a bug than a feature. Maybe `tf.summary.merge_all`, which does a global merging, is not suitable here.

**Comment by connection-on-fiber-bundles** [comment]
Maybe we should revisit this PR https://github.com/keras-team/keras/pull/4418?
@fchollet

**Comment by TrentBrick** [comment]
Can I ask what the state of this discussion is? I have just run into this bug and want to know how to get around it. 

Thank you, 
Trenton
