### ISSUE TITLE
Is there implementation of convGRU2D in keras?

### ISSUE THREAD

**Issue by TianKai1993** [keras-team/keras#9048]
hey, guys. As the title, is anybody knows? I am a new comer, thanks for your help!

**Comment by brainnoise** [comment]
Currently, there isn't an implementation of `convGRU2D` in Keras. We haven't added it yet as we want to refactor the existing `ConvLSTM2D` layer before we add new convRNN layers.

There is an item for that in the "request for contributions" list here: https://github.com/keras-team/keras/projects/1

**Comment by NivNayman** [comment]
You are welcome to use my implementation of ConvGRU2D (example added):
https://github.com/NivNayman/ConvGRU2D

P.S. I tried to make a PR many times with no response from the Keras group.
