### ISSUE TITLE
Siamese network forward pass / test accuracy 

### ISSUE THREAD

**Issue by lschaupp** [keras-team/keras#9054]
Question regarding this example file: https://github.com/keras-team/keras/blob/master/examples/mnist_siamese.py

In the contrastive loss layer, the example file is using a margin for setting up the training process.
I would assume that the margin would be the same parameter as the threshold for the accuracy of the model. (here 0.5 in the compute_acc function). What is the reason for using a different threshold?

```
def contrastive_loss(y_true, y_pred):
    '''Contrastive loss from Hadsell-et-al.'06
    http://yann.lecun.com/exdb/publis/pdf/hadsell-chopra-lecun-06.pdf
    '''
    margin = 1
    return K.mean(y_true * K.square(y_pred) +
                  (1 - y_true) * K.square(K.maximum(margin - y_pred, 0)))


def compute_accuracy(y_true, y_pred):
    '''Compute classification accuracy with a fixed threshold on distances.
    '''
    pred = y_pred.ravel() < 0.5
    return np.mean(pred == y_true)

```

**Comment by ozabluda** [comment]
margin has absolutely nothing to do with the threshold, except that `0 < threshold < margin`
