### ISSUE TITLE
[Export Model] Include mapping of true label name to integer value

### ISSUE THREAD

**Issue by hadyan-tvlk** [keras-team/keras#9061]
Dear Keras Fellow,

I'm facing difficulty when trying to use the exported model. The problem is i can't refer the true label name of the yield value returned from predict() function. Is there any way to include the mapping of true label name to encoded value to exported model?

Thank you

**Comment by fchollet** [comment]
`predict` returns floating point probabilities, which you have to map to class names on your own (it could be as easy to a call to `[class_names[i] for i in np.argmax(preds)]`). What is your specific issue?

**Comment by hadyan-tvlk** [comment]
Thanks @fchollet for your response. So my actual issue:
1. Assuming me using the exported model for production usage.
2. Trying to predict the input, yield the outcome (probability value).

The problem is i have no idea how to decode the outcome into the true class label name since i don't have mapping information of the class_name (i only have exported model).

My questions is more like: is there any way to include the mapping class_name into the exported model?

Thank you
