### ISSUE TITLE
Rough estimate of number of parameters and LSTM architecture..

### ISSUE THREAD

**Issue by xrtc21** [keras-team/keras#9076]
Greetings all,

The problem that I am working is a binary classification. I have around 150 sequences, where each sequence has 130000 timesteps, where each timestep has 2 features, shape=(1,130000,2). Each of these sequences is labelled as "1" or "0".  I want to train an lstm network, where at the end, giving it a sequence of 130000 timesteps with 2 features each, will predict "1" or "0". Hence the problem as I have it in my mind is "many to one" right? 

1)If I keep for training 120 of these sequences and the rest 30 for validation, the number of parameters of the model, should be smth like 120x130000x2=31,200,000 parameters?
For example an LSTM layer with ~4000 units?

2)The network should be stateful? or not

The model as I am thinking it is smth like:

```
model = Sequential()
model.add(LSTM(units=4000,batch_input_shape=(1, 130000, 2),return_sequences=False,stateful=True, kernel_initializer='RandomNormal'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='sgd', metrics=['accuracy'])

history = model.fit(X_train, Y_train,validation_data=(X_test, Y_test), shuffle=False, epochs=5, batch_size=1, verbose=1)
```

I tried for one epoch to fit it, but the memory gets quite high! Any recommendations for the whole problem approach?

**Comment by tomastheod-ITI** [comment]
@xrtc21 The LSTM parameters are 4 * (input_dim * output_dim + output_dim * output_dim + output_dim). They do not depend on the number of training samples or the sequence length. In your case they would be 4 * (2 * 4000 + 4000 * 4000 + 4000) = 64,048,000.
The feed-forward (Dense) parameters are input_dim * output_dim + output_dim = 4000 * 1 + 1 = 4,001.

Also, I would advise you to re-think the 130,000 sequence length number. See if you can get it down to a few hundreds at most, not in the thousands.

**Comment by xrtc21** [comment]
What you mean is to have more samples instead and less timesteps for each one?

1. Should I train then the model in batches of 32,64 after this transform? If my dataset has shape X_train.shape=(thousands, hundreds,2)
2. Regarding the stateful status?
3. Regarding the architecture of the model in the approach you mention. In order to decide how many lstm units I need which approach should I follow?

Thanks @tomastheod-ITI

**Comment by tomastheod-ITI** [comment]
@xrtc21 Yes, more samples of shorter sequences. Unfortunately, there is no general answer to your questions. You can choose "reasonable" starting values for your parameters and experiment; one variable at a time.
For example, start with a batch size of 64, stateful = False and 100 LSTM neurons. Choose a sequence length that makes sense for your problem. Trying to predict the next word in a sentence based on the previous 20 words is reasonable; based on the previous 2000 words, not so much.
