### ISSUE TITLE
Image sequence classification using keras

### ISSUE THREAD

**Issue by apsakash** [keras-team/keras#9080]
I want to do classification of a sequence of images using cnn lstm network into 26 classes
I have 779 samples having sequence length of 40 and each image is of size 60X80

My code is:

import numpy
from keras import Sequential
import keras.optimizers
from keras.layers import MaxPool2D, TimeDistributed, Conv2D, Flatten, LSTM, Dense, Activation
from sklearn.model_selection import train_test_split
import import_data

data,labels= import_data.get_data("/home/PycharmProjects/MNIST/data/Lips")

x_train,x_test,y_train,y_test=train_test_split(data,labels,test_size=0.1,random_state=42)

print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

model= Sequential()
model.add(TimeDistributed(Conv2D(filters=64,kernel_size=(2,2),strides=(1,1),activation='relu'),input_shape=(40,60,80,1)))
model.add(TimeDistributed(MaxPool2D(pool_size=(2,2),padding='valid')))
model.add(TimeDistributed(Flatten()))

model.add(LSTM(64,activation='relu'))
model.add(Dense(26))
model.add(Activation('softmax'))

model.compile(loss=keras.losses.categorical_crossentropy,optimizer=keras.optimizers.Adadelta(),metrics=['accuracy'])

model.fit(x_train, y_train,
          batch_size=100,
          epochs=2,
          verbose=1,
          validation_data=(x_test, y_test))

score=model.evaluate(x_test,y_test,verbose=0)
print(score[0],score[1])

x_train has shape of (701,40,60,80,1) and y_train has shape(701,)

Finally i want to classify these sequences into 26 classes....but when I run it gives me the error---
File "/home/dr_aps/PycharmProjects/MNIST/testmodel.py", line 29, in <module>
    validation_data=(x_test, y_test))
  File "/usr/local/lib/python3.6/dist-packages/keras/models.py", line 960, in fit
    validation_steps=validation_steps)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1581, in fit
    batch_size=batch_size)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1418, in _standardize_user_data
    exception_prefix='target')
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 153, in _standardize_input_data
    str(array.shape))
ValueError: Error when checking target: expected activation_1 to have shape (None, 26) but got array with shape (701, 1)

I am new to deep learning and will appreciate if someone can help me out.

**Comment by lamlt2710** [comment]
I think, u need check y_train 's shape. it 's error because y_train u pass has wrong shape
