### ISSUE TITLE
model.add(GRU) then kernel dies

### ISSUE THREAD

**Issue by shitian-ni** [keras-team/keras#9081]
If I run `model.add(GRU(62,return_sequences=True,input_shape=(1,1))))`, it's ok
If I run `model.add(GRU(72,return_sequences=True,input_shape=(1,1))))`, Jupyter Notebook will report kernel dies.
If I run `model.add(GRU(512,return_sequences=True,input_shape=(1,1))))`, jupyter notebook will keep running couldn't be interrupted. If I run the code on python kernel, the kernel will freeze and I can't exit with Ctrl+c

Is it a bug of keras or the computer?
I am running on a supercomputer using latest keras and tensorflow 1.4, Python 2.7.13
GPU is Tesla P100, CPU is Intel Xeon E5-2680 v4 2.4GHz, Linux SUSE,
tried on memories of 60GB and 240GB

**Comment by anj-s** [comment]
I instantiated a Sequential model and added a GRU layer as mentioned above. I am unable to reproduce the issue in my Jupyter notebook. Can you paste more of the code that you are trying to run? Thanks!

**Comment by shitian-ni** [comment]
@anj-s The code above is all it needs. Just import the modules.
I have no problem running the code on AWS, but have the issue when running on my school's supercomputer. I don't know if it is Keras's issue or the hardware's issue. Because it just freezes, unfortunately there is no traceback to debug.

**Comment by teng88** [comment]
Same issue with P100

**Comment by axelstram** [comment]
I had a similar problem. Every time I added a GRU or LSTM with 80 or more units, the kernel crashed. I solved it by updating CUDA to 9.0
