### ISSUE TITLE
Exporting/Importing Keras Model to Tensorflow fails when using multi_gpu_model

### ISSUE THREAD

**Issue by ThaHonzo** [keras-team/keras#9083]
Hey guys,

when I try to export a multi_gpu_model to tensorflow I get the following error:

`AttributeError: Layer model_1 has multiple inbound nodes, hence the notion of "layer input" is ill-defined. Use get_input_at(node_index) instead.`

```python
  input_img = Input(shape=(imgDim, imgDim, 1)) 

  # add several layers to net

  model = Model(input_img, net)

  parallel_model = multi_gpu_model(model, gpus=4)

  parallel_model.compile(optimizer='adam', 
                loss='binary_crossentropy',
                metrics=['accuracy'])

  parallel_model.fit(x_train, y_train,
            epochs=100,
            batch_size=100,
            shuffle=True,
            validation_data=(x_test, y_test))

  # export model rather than parallel_model:
  saveKerasModelAsProtobuf(model, outpath)
```

```python
def saveKerasModelAsProtobuf(model, outputPath):
  signature = tf.saved_model.signature_def_utils.predict_signature_def(
    inputs={'image': model.input}, outputs={'scores': model.output})

  builder = tf.saved_model.builder.SavedModelBuilder(outputPath)                                                                    
  builder.add_meta_graph_and_variables(
    sess=keras.backend.get_session(),                                                                                                                    
    tags=[tf.saved_model.tag_constants.SERVING],                                                                                             
    signature_def_map={
      tf.saved_model.signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY:
      signature    
    }
  )         
  builder.save()

  return
```
To me it looks like it is trying to export the parallel_model rather than the sequential model. However, if I do
`model.summary()`
and
`parallel_model.summary()`

they are different (which I expect). Is this a bug?

Thanks!

**Comment by anj-s** [comment]
It is still exporting model and not parallel_model. The reason you are seeing this error is because model has been called within multi_gpu_model again and hence the number of inputs to the model is no longer 1. The error is thrown when you call model.input on a model that has multiple inputs as seen [here](https://github.com/keras-team/keras/blob/master/keras/engine/topology.py#L925). 

As suggested by the error message you should use get_input_at(0) and get_output_at(0) for setting the inputs and outputs in the saveKerasModelAsProtobuf function.

**Comment by ThaHonzo** [comment]
@anj-s  Thanks you. I tried that, but when I try to import the model in C++ on a different computer with no GPU I get the following error:
`Error reading graph definition. Cannot assign a device for operation 'replica_3/lambda_4/Shape': Operation was explicitly assigned to /device:GPU:3 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Make sure the device specification refers to a valid device. [[Node: replica_3/lambda_4/Shape = Shape[T=DT_FLOAT, _output_shapes=[[4]], out_type=DT_INT32, _device="/device:GPU:3"](input_1)]] `

Do you know how to handle that? Is there a way to actually convert the parallel_model into the sequential model to use it the way I used the sequential model before?

**Comment by bzamecnik** [comment]
Only the weights from the serial model should be saved. It can be loaded back and converted to a replicated model (with a different number of replicas). If weights from the replicas are saved, something is wrong.

**Comment by ThaHonzo** [comment]
Thanks @bzamecnik. Do you have any idea what I'm doing wrong? After digging around on the internet I found that it is possible to set `clear_devices=True` in `builder.add_meta_graph_and_variables()`. If I do that, the computer with no dedicated GPU is able to apply the network onto the data and produces reasonable results (or at least it looks reasonable to me).
