### ISSUE TITLE
Unable to create a custom regularizer on weights of 2 layers.

### ISSUE THREAD

**Issue by pvskand** [keras-team/keras#9100]
Here is small snippet of my code describing my custom regularizer that I want to implement.
```
# Code adapted from https://github.com/keras-team/keras/issues/5563

class CustomRegularization(Layer):
    def __init__(self, **kwargs):
        super(CustomRegularization, self).__init__(**kwargs)

    def call(self ,x ,mask=None):
        ld=x[0]
        rd=x[1]
        reg = K.dot(K.transpose(ld), rd)
        reg_norm = K.sqrt(K.sum(K.square(reg)))
        self.add_loss(reg_norm, x)
        return ld


    def compute_output_shape(self, input_shape):
        return (input_shape[0][0],input_shape[0][1])

def model():
    input1 = Input(shape=(224, 224, 3))
    input2 = Input(shape=(224, 224, 3))

    inp1 = Flatten()(input1)
    inp2 = Flatten()(input2)

    layer1 = Dense(1024, activation="sigmoid")
    x1_1 = layer1(inp1)
    x2_1 = layer1(inp2)

    layer2 = Dense(1024, activation="sigmoid")
    x1_2 = layer2(inp1)
    x2_2 = layer2(inp2)

    # get weights of layer1 and layer2

    layer1_wt = layer1.trainable_weights[0]
    layer2_wt = layer2.trainable_weights[0]

    # This is a regularization term on the weights of layer1 and layer2.
    regularization = CustomRegularization()([layer1_wt, layer2_wt])

    model = Model([input1, input2], [x1_2, x2_2, regularization])

if __name__ == "__main__":
    m = model()

```
This returns the error `AttributeError: 'Variable' object has no attribute '_keras_history'` and is not able to create the model.
I know that this error would be because of incompatible outputs (since inputs are keras Input layer). [For more details refer to @fchollet's comment on issue #7362 ].

The main problem here are the `layer1.trainable_weights[0]` and `layer2.trainable_weights[0]`. These are `tf.Variable` (tensorflow variables) and not Keras Tensors. I would require them to convert to keras tensors. How do I do that?

Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [X] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [X] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by rex-yue-wu** [comment]
I think you should do something like this
```python
def model():
    input1 = Input(shape=(224, 224, 3))
    input2 = Input(shape=(224, 224, 3))

    inp1 = Flatten()(input1)
    inp2 = Flatten()(input2)

    layer1 = Dense(1024, activation="sigmoid")
    x1_1 = layer1(inp1)
    x2_1 = layer1(inp2)

    layer2 = Dense(1024, activation="sigmoid")
    x1_2 = layer2(inp1)
    x2_2 = layer2(inp2)

    # get weights of layer1 and layer2

    layer1_wt = layer1.trainable_weights[0]
    layer2_wt = layer2.trainable_weights[0]

    model = Model([input1, input2], [x1_2, x2_2])
  
    #----------- add regularizer ----------------
    reg_loss = CustomRegularizationFunc([layer1_wt, layer2_wt])
    model.add_loss( reg_loss )
    return model
```

Note, `CustomRegularizationFunc` should not be a custom layer, but a Keras function, see examples `keras/regularizers.py`.

**Comment by zjfheart** [comment]
@rex-yue-wu 

Can you write it in detail about 
```
reg_loss = CustomRegularizationFunc([layer1_wt, layer2_wt])
    model.add_loss( reg_loss )
```

It looks like model.add_loss (reg_loss) will overlap data loss.

**Comment by pvskand** [comment]
I did get a hack to get around this problem by using creating a `callback` and using `on_batch_end` and updating the weights according to the derivative.

**Comment by titubeta** [comment]
Can you share the code snippet of it? @pvskand
