### ISSUE TITLE
Keras 2.1.3: NASNetMobile training error

### ISSUE THREAD

**Issue by jwnsu** [keras-team/keras#9101]
Tensorflow 1.4.1, Ubuntu 16.04, Nvidia 1080 Ti

Same training works fine for other models (i.e. simply replace single line applications.NASNetMobile to vgg/xception/ResNet50). Error:
```
Traceback (most recent call last):
  File "./ictrain-nas.py", line 121, in <module>
    verbose=2)
  File "/home/dsu/tf12/local/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/dsu/tf12/local/lib/python2.7/site-packages/keras/engine/training.py", line 2177, in fit_generator
    class_weight=class_weight)
  File "/home/dsu/tf12/local/lib/python2.7/site-packages/keras/engine/training.py", line 1843, in train_on_batch
    check_batch_axis=True)
  File "/home/dsu/tf12/local/lib/python2.7/site-packages/keras/engine/training.py", line 1430, in _standardize_user_data
    exception_prefix='target')
  File "/home/dsu/tf12/local/lib/python2.7/site-packages/keras/engine/training.py", line 110, in _standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking target: expected activation_188 to have 4 dimensions, but got array with shape (16, 16)

```
Does NASNet require particular training data format?

**Comment by fchollet** [comment]
Please share a standalone code snippet to reproduce this.

The error message points to the fact that the Numpy arrays that you are passing as targets have shape (16, 16), but the model expects shape (num_samples, 4).

CC @taehoonlee

**Comment by jwnsu** [comment]
It's very simple test code. As I mentioned, data should be fine since the same training works fine with vgg/resnet50 etc, code snippet:
----------------
#model = applications.VGG16(weights='imagenet', include_top=False, input_shape=(img_width,img_height,3))

model =  applications.NASNetMobile(classes=len(CLASSES), include_top=False, input_shape=(img_width,img_height,3))

model.compile(loss='categorical_crossentropy',
              optimizer=optimizers.SGD(lr=1e-4, momentum=0.9),
              metrics=['accuracy'])

# prepare data augmentation configuration
train_datagen = ImageDataGenerator(
    rescale=1. / 255,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True)

test_datagen = ImageDataGenerator(rescale=1. / 255)

train_generator = train_datagen.flow_from_directory(
    train_data_dir,
    target_size=(img_height, img_width),
    batch_size=batch_size,
    classes=CLASSES)

validation_generator = test_datagen.flow_from_directory(
    validation_data_dir,
    target_size=(img_height, img_width),
    batch_size=batch_size,
    classes=CLASSES)

model.summary()

checkpoint = ModelCheckpoint(finetune_model_path, monitor='val_acc', verbose=1, save_best_only=True, save_weights_only=False, mode='auto', period=1)

# fine-tune the model
model.fit_generator(
    train_generator,
    steps_per_epoch=nb_train_samples // batch_size,
    epochs=args.nepoch,
    validation_data=validation_generator,
    validation_steps=nb_validation_samples // batch_size,
    callbacks = [checkpoint],
    verbose=2)

**Comment by taehoonlee** [comment]
For all the applications, `include_top=False` always produces a NumPy array of `[sample, width, height, channel]` (e.g., `VGG16(include_top=False): [1, 7, 7, 512], NASNetMobile(include_top=False): [1, 7, 7, 1056]`). I think there is no problem in NASNet.

If you want to conduct transfer learning with labels of `[sample, 16]`, the following codes might help you, @jwnsu.
```python
model = ...
x = GlobalAveragePooling2D()(model.output)
x = Dense(16, activation='softmax')(x)
newmodel = Model(inputs=model.input, outputs=x)
```

**Comment by jwnsu** [comment]
Thx for the explanation, @taehoonlee. It works fine by adding the suggested top.

 One suggestion is to add these two lines in NASNetMobile if include_top is false (#of classes is an input parameter to NASNetMobile.) In fact, NASNet applies global avg if pooling parameter is passed in. 

NASNetMobile is simply a convenience front call for NASNet backend. This will make NASNetMobile behavior consistent with other model, e.g. ResNet50, VGGs etc. Changes in NASNetMobile will not affect NASNet, folks who want more manual setup, they still can go to NASNet directly.

Will keep this thread open for you to see this suggestion, then will close this thread.
