### ISSUE TITLE
Custom Lambda layer for multiple inputs iteration

### ISSUE THREAD

**Issue by JoaoLages** [keras-team/keras#9103]
Using **TF backend**, I want to iterate 2 Tensors at the same time.
These Tensors have the shape `(?, N, M)` when constructing the computation graph, with `N` and `M`  being natural numbers and `?` will be the batch size. 

I need to iterate this 2 Tensors at the same time so that I can apply transformations to them at the same time. If it was only one, this would be easily managed with this layer `Lambda(lambda x: function(x))`. However, since I have 2 Tensors, this can not be done like that, `Lambda(lambda x,y: function(x,y))` raises an error since you can only pass one argument to a `Layer`. If passing [Tensor1, Tensor2] to the `Lambda` layer, an error will be raised since since the `y` variable is not defined. 

How  can I solve this?

**Comment by myutwo150** [comment]
What about `Lambda(lambda x: function(x[0], x[1]))`?

**Comment by JoaoLages** [comment]
@myutwo150 Actually, I was misleading myself by checking the shape of the tensor inside `function`, but it will still be `(?, N, M)`. So your solution might work. 

I will update this issue as soon as I'm able to fix [this issue](https://github.com/keras-team/keras/issues/9111) that I am having inside this `function` that I am using.

**Comment by JoaoLages** [comment]
Indeed @myutwo150 works. Thank you

**Comment by DabuP** [comment]
Tmodel = Sequential()
x = layers.Input(shape=[1,])   # Lambda on single input
out1 = layers.Lambda(lambda x: x ** 2)(x)

y = layers.Input(shape=[1,])   # Lambda on multiple inputs
z = layers.Input(shape=[1,])
def conn(IP):
    return IP[0]+IP[1]
out2 = layers.Lambda(conn)([y,z])

Tmodel = tf.keras.Model(inputs=[x,y,z], outputs=[out1,out2],name='Tmodel')  # Define Model
Tmodel.summary()

# output
O1,O2 = Tmodel([2,15,10])
print(O1)   # tf.Tensor(4, shape=(), dtype=int32)
print(O2)   # tf.Tensor(25, shape=(), dtype=int32)
