### ISSUE TITLE
how to implement gather_nd in keras like tf.gather_nd?

### ISSUE THREAD

**Issue by shawnthu** [keras-team/keras#9109]

**Comment by ymodak** [comment]
I think this [example](https://stackoverflow.com/questions/50820639/keras-how-to-slice-tensor-using-information-from-another-tensor) should help you in implementing tf.gather_nd in keras.

**Comment by rachtibat** [comment]
Here is another solution with Lambda layers
https://stackoverflow.com/questions/62196315/tf-gather-nd-seems-to-be-problematic-when-used-in-a-keras-model-not-suppor
