### ISSUE TITLE
Sample_weight is a misnomer

### ISSUE THREAD

**Issue by caugusta** [keras-team/keras#9118]
There seems to be a lot of confusion around sample_weight and sample_weight_mode (e.g [2594](https://github.com/keras-team/keras/issues/2594), [7120](https://github.com/keras-team/keras/issues/7120), [7497](https://github.com/keras-team/keras/issues/7497)). As explained elsewhere, these apply a weight on the loss, which means if sample_weight_model=temporal then you should have 3D outputs. However, the name 'sample_weight' implies a weight on the samples, which is not what's happening. Should the name be changed? Is there a way to weight the actual samples instead of the loss based on the samples?

**Comment by FitMachineLearning** [comment]
I second that.
