### ISSUE TITLE
Neural Network Trained Model Weights

### ISSUE THREAD

**Issue by mohanrajmit** [keras-team/keras#9123]
Hi,

I have pretrained neural network model weights in .hdf5 file format. I want to use these pretrained weights on FPGA hardware. The pretrained weights are in 32 bit floating point values.

I want to convert the 32bit floating point weights to fixed point.

Please help me on above issues.

**Comment by kaichi040696** [comment]
I have the same problem. If you are able to solve the problem, can please tell me the solution? Thank you

**Comment by lellebebbl** [comment]
We had the same problem. So we exported the weights of the network and implemented our own framework on c++ to make it easier to port it to the fpga
