### ISSUE TITLE
Notebook dying too often.

### ISSUE THREAD

**Issue by Anirudh257** [keras-team/keras#9140]
I am trying to understand the code given here:
![conv_lstm](https://github.com/keras-team/keras/blob/master/examples/conv_lstm.py). 

I have implemented the whole code in a jupyter python notebook linked here:
![LSTM](https://github.com/Anirudh257/Audio-files-extraction/blob/master/UNDERSTANDING%20LSTM%20.ipynb)

When I start training the network, my notebook becomes unresponsive, my firefox browser freezes and crashes after sometime. The kernel dies too.

What can be the reason for this?
Are these 2 arrays **noisy_movies** and **shifted_movies** too large for the notebook to process?
Is anybody else experiencing the same issue as well?

I would be glad if someone can help.

**Comment by anj-s** [comment]
I think this question might have a better home at StackOverflow. I would try running the model with a smaller input size and perhaps reduce the number of layers to see if this is the problem. Thanks.

**Comment by Anirudh257** [comment]
Thanks for replying, @anj-s. I have already tried asking the same question on stackoverflow and tried out all their suggestions. But none of them work for me. I will try to decrease the parameters and run the notebook again.
