### ISSUE TITLE
ValueError: None values not supported. adam.get_updates(loss=K.constant(loss),constraints=[], params=self.model.trainable_weights)

### ISSUE THREAD

**Issue by jlfu** [keras-team/keras#9142]
adam = optimizers.Adam()
updates = adam.get_updates(loss=K.constant(loss),constraints=[], params=self.model.trainable_weights)
self.train_fn = K.function(inputs=[probs,reward],
                                          outputs=[],
                                          updates=updates)

When i run the code, i get the following error:
Traceback (most recent call last):
  File "model.py", line 462, in <module>
    agent.fit(state, chose_arg1, chose_arg2, reward, chose_arg1_probs,chose_arg2_probs)
  File "model.py", line 255, in fit
    updates = adam.get_updates(loss=K.constant(loss),constraints=[], params=self.model.trainable_weights)
  File "/home/jlfu/RLDiscourse/disenv/lib/python2.7/site-packages/keras/optimizers.py", line 398, in get_updates
    m_t = (self.beta_1 * m) + (1. - self.beta_1) * g
  File "/home/jlfu/RLDiscourse/disenv/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 829, in binary_op_wrapper
    y = ops.convert_to_tensor(y, dtype=x.dtype.base_dtype, name="y")
  File "/home/jlfu/RLDiscourse/disenv/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 676, in convert_to_tensor
    as_ref=False)
  File "/home/jlfu/RLDiscourse/disenv/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 741, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/jlfu/RLDiscourse/disenv/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 113, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/jlfu/RLDiscourse/disenv/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/jlfu/RLDiscourse/disenv/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 364, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.

I have print the loss and self.model.trainable_weights.
the loss is: -0.375
the self.model.trainable_weights: self.model.trainable_weights [<tf.Variable 'embedding_1/embeddings:0' shape=(39660, 300) dtype=float32_ref>, <tf.Variable 'embedding_2/embeddings:0' shape=(39660, 300) dtype=float32_ref>, <tf.Variable 'bidirectional_1/kernel:0' shape=(300, 800) dtype=float32_ref>, <tf.Variable 'bidirectional_1/recurrent_kernel:0' shape=(200, 800) dtype=float32_ref>, <tf.Variable 'bidirectional_1/bias:0' shape=(800,) dtype=float32_ref>, <tf.Variable 'bidirectional_1/kernel_1:0' shape=(300, 800) dtype=float32_ref>, <tf.Variable 'bidirectional_1/recurrent_kernel_1:0' shape=(200, 800) dtype=float32_ref>, <tf.Variable 'bidirectional_1/bias_1:0' shape=(800,) dtype=float32_ref>, <tf.Variable 'bidirectional_2/kernel:0' shape=(300, 800) dtype=float32_ref>, <tf.Variable 'bidirectional_2/recurrent_kernel:0' shape=(200, 800) dtype=float32_ref>, <tf.Variable 'bidirectional_2/bias:0' shape=(800,) dtype=float32_ref>, <tf.Variable 'bidirectional_2/kernel_1:0' shape=(300, 800) dtype=float32_ref>, <tf.Variable 'bidirectional_2/recurrent_kernel_1:0' shape=(200, 800) dtype=float32_ref>, <tf.Variable 'bidirectional_2/bias_1:0' shape=(800,) dtype=float32_ref>, <tf.Variable 'time_distributed_1/kernel:0' shape=(400, 2) dtype=float32_ref>, <tf.Variable 'time_distributed_1/bias:0' shape=(2,) dtype=float32_ref>, <tf.Variable 'time_distributed_2/kernel:0' shape=(400, 2) dtype=float32_ref>, <tf.Variable 'time_distributed_2/bias:0' shape=(2,) dtype=float32_ref>]

it seems like the ## constraints=[] raise the error.

The version of my keras is 2.0.2, and i use the tensorflow as my backend. The version of tensorflow is 1.2. Can anybody help me to solve the quesion? Thank you!

**Comment by jlfu** [comment]
I thought maybe the ## self.model.trainable_weights not return the value of weights, but only return the  shape of the weights. I checked the optimizers.py", line 398, in get_updates. The None is raise by     K.gradients(loss, params). the loss is a constant, so the None value come from params. I don't know if the self.model.trainable_weights not returns the value of weights. How can i fix it?

**Comment by PurbashaChatterjee** [comment]
Were you able to solve this issue? I am also getting a similar error. It seems, it occurs whenever bias is added to the trainable weights.

**Comment by fchollet** [comment]
This is due to some op in your model not being differentiable (or not having a gradient implemented), or alternatively, it could be due to requesting a gradient for a variable that isn't part of your computation graph. In either case, it means your model definition has issues.

We have recently improved the error message that occurs in such situations, to make this clearer.

**Comment by iFe1er** [comment]
getting same error here with python 2.7. I am using optimizer from keras.optimizers import RMSprop. And surprisingly, changing the optimizer from  keras.optimizers.RMSprop to "rmsprop" (string) when compiling solve this problem. And I don't know why

**Comment by iFe1er** [comment]
here is the error message using optimizer from keras.optimizers.RMSprop as optimizer:
just to make it clear, I use NO CUSTOM LOSS FUNCTION but only custom metrics.


---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-113-d69af9ac967f> in <module>()
     13               #lr_scehduler(),
     14     ],
---> 15     verbose=0
     16 )

/home/fuhang/.local/lib/python2.7/site-packages/keras/models.pyc in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, **kwargs)
    958                               initial_epoch=initial_epoch,
    959                               steps_per_epoch=steps_per_epoch,
--> 960                               validation_steps=validation_steps)
    961 
    962     def evaluate(self, x, y, batch_size=32, verbose=1,

/home/fuhang/.local/lib/python2.7/site-packages/keras/engine/training.pyc in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, **kwargs)
   1632         else:
   1633             ins = x + y + sample_weights
-> 1634         self._make_train_function()
   1635         f = self.train_function
   1636 

/home/fuhang/.local/lib/python2.7/site-packages/keras/engine/training.pyc in _make_train_function(self)
    988                     training_updates = self.optimizer.get_updates(
    989                         params=self._collected_trainable_weights,
--> 990                         loss=self.total_loss)
    991                 updates = self.updates + training_updates
    992                 # Gets loss and metrics. Updates weights at each call.

/home/fuhang/.local/lib/python2.7/site-packages/keras/legacy/interfaces.pyc in wrapper(*args, **kwargs)
     85                 warnings.warn('Update your `' + object_name +
     86                               '` call to the Keras 2 API: ' + signature, stacklevel=2)
---> 87             return func(*args, **kwargs)
     88         wrapper._original_function = func
     89         return wrapper

/home/fuhang/.local/lib/python2.7/site-packages/keras/optimizers.pyc in get_updates(self, loss, params)
    237             new_a = self.rho * a + (1. - self.rho) * K.square(g)
    238             self.updates.append(K.update(a, new_a))
--> 239             new_p = p - lr * g / (K.sqrt(new_a) + self.epsilon)
    240 
    241             # Apply constraints.

/home/fuhang/.local/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.pyc in binary_op_wrapper(x, y)
    883       if not isinstance(y, sparse_tensor.SparseTensor):
    884         try:
--> 885           y = ops.convert_to_tensor(y, dtype=x.dtype.base_dtype, name="y")
    886         except TypeError:
    887           # If the RHS is not a tensor, it might be a tensor aware object

/home/fuhang/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.pyc in convert_to_tensor(value, dtype, name, preferred_dtype)
    834       name=name,
    835       preferred_dtype=preferred_dtype,
--> 836       as_ref=False)
    837 
    838 

/home/fuhang/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.pyc in internal_convert_to_tensor(value, dtype, name, as_ref, preferred_dtype, ctx)
    924 
    925     if ret is None:
--> 926       ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
    927 
    928     if ret is NotImplemented:

/home/fuhang/.local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.pyc in _constant_tensor_conversion_function(v, dtype, name, as_ref)
    227                                          as_ref=False):
    228   _ = as_ref
--> 229   return constant(v, dtype=dtype, name=name)
    230 
    231 

/home/fuhang/.local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.pyc in constant(value, dtype, shape, name, verify_shape)
    206   tensor_value.tensor.CopyFrom(
    207       tensor_util.make_tensor_proto(
--> 208           value, dtype=dtype, shape=shape, verify_shape=verify_shape))
    209   dtype_value = attr_value_pb2.AttrValue(type=tensor_value.tensor.dtype)
    210   const_tensor = g.create_op(

/home/fuhang/.local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.pyc in make_tensor_proto(values, dtype, shape, verify_shape)
    369   else:
    370     if values is None:
--> 371       raise ValueError("None values not supported.")
    372     # if dtype is provided, forces numpy array to be the type
    373     # provided if possible.

ValueError: None values not supported.

**Comment by iFe1er** [comment]
note: solve the problem by editing optimiser from 
rmsprop=RMSprop(lr=0.001, rho=0.9, epsilon=None, decay=0.0)
to
rmsprop=RMSprop(lr=0.001)

**Comment by korosigSZTE** [comment]
I have the same problem when I change my optimizer form
Adamax(lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=None, decay=0.0)
to
Adamax(lr=0.001)
it solve the problem

**Comment by SounakRay1997** [comment]
> This is due to some op in your model not being differentiable (or not having a gradient implemented), or alternatively, it could be due to requesting a gradient for a variable that isn't part of your computation graph. In either case, it means your model definition has issues.
> 
> We have recently improved the error message that occurs in such situations, to make this clearer.

Is anyone getting the error even after the model is compiling properly. I guess proper compilation means formation of the computation graph. Then why I am getting this error even after proper compilation of my model.

**Comment by kwende** [comment]
I had the same problem, but with Adam. Once I removed the epsilon=None, it worked. Perhaps explicitly setting a named property to None is causing mischief? 

Adam(lr=0.005, beta_1=0.9, beta_2=0.999, **epsilon=None**, decay=0.01)

I'm noticing that as a trend in the comments I'm seeing.

**Comment by LiutongZhou** [comment]
changing 
`model.compile(optimizer=keras.optimizers.Adam())`
to
`model.compile(optimizer='adam')`
solve the problem for me

**Comment by prateeksaurabh** [comment]
> note: solve the problem by editing optimiser from
> rmsprop=RMSprop(lr=0.001, rho=0.9, epsilon=None, decay=0.0)
> to
> rmsprop=RMSprop(lr=0.001)

Thank you this works

**Comment by GarimaZe** [comment]
As I am two models simultaneously, but i am getting the error 
ValueError: None values not supported.

Traceback (most recent call last):
  File "C:/Users/Garima Thakur/Desktop/neuro_v1_jpzh/src/server.py", line 45, in <module>
    nn_zh = NeuroNER(**arguments_zh)
  File "C:\Users\Garima Thakur\Desktop\neuro_v1_jpzh\src\neuroner.py", line 316, in __init__
    model = EntityLSTM(dataset, parameters)
  File "C:\Users\Garima Thakur\Desktop\neuro_v1_jpzh\src\entity_lstm.py", line 214, in __init__
    self.define_training_procedure(parameters)
  File "C:\Users\Garima Thakur\Desktop\neuro_v1_jpzh\src\entity_lstm.py", line 233, in define_training_procedure
    for grad, var in grads_and_vars]
  File "C:\Users\Garima Thakur\Desktop\neuro_v1_jpzh\src\entity_lstm.py", line 233, in <listcomp>
    for grad, var in grads_and_vars]
  File "C:\Users\Garima Thakur\anaconda3\envs\neuro_1\lib\site-packages\tensorflow_core\python\util\dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "C:\Users\Garima Thakur\anaconda3\envs\neuro_1\lib\site-packages\tensorflow_core\python\ops\clip_ops.py", line 79, in clip_by_value
    t.values if isinstance(t, ops.IndexedSlices) else t, name="t")
  File "C:\Users\Garima Thakur\anaconda3\envs\neuro_1\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1184, in convert_to_tensor
    return convert_to_tensor_v2(value, dtype, preferred_dtype, name)
  File "C:\Users\Garima Thakur\anaconda3\envs\neuro_1\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1242, in convert_to_tensor_v2
    as_ref=False)
  File "C:\Users\Garima Thakur\anaconda3\envs\neuro_1\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1297, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\Users\Garima Thakur\anaconda3\envs\neuro_1\lib\site-packages\tensorflow_core\python\framework\constant_op.py", line 286, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "C:\Users\Garima Thakur\anaconda3\envs\neuro_1\lib\site-packages\tensorflow_core\python\framework\constant_op.py", line 227, in constant
    allow_broadcast=True)
  File "C:\Users\Garima Thakur\anaconda3\envs\neuro_1\lib\site-packages\tensorflow_core\python\framework\constant_op.py", line 265, in _constant_impl
    allow_broadcast=allow_broadcast))
  File "C:\Users\Garima Thakur\anaconda3\envs\neuro_1\lib\site-packages\tensorflow_core\python\framework\tensor_util.py", line 437, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.
Exception ignored in: <bound method NeuroNER.__del__ of <neuroner.NeuroNER object at 0x000001D63A9EA048>>
Traceback (most recent call last):
  File "C:\Users\Garima Thakur\Desktop\neuro_v1_jpzh\src\neuroner.py", line 566, in __del__
    self.sess.close()
AttributeError: 'NeuroNER' object has no attribute 'sess'

Process finished with exit code 1
I am using TensorFlow version 1.15.1


Can someone please answer this
