### ISSUE TITLE
Graph disconnected: model with shared layers and multiple inputs results in graph disconnected error

### ISSUE THREAD

**Issue by ChengZY** [keras-team/keras#9146]
IMG_HEIGHT = 256
IMG_WIDTH = 256
IMG_CHANNELS = 3
inputs = Input((256, 256, 3))
inputs2 = Input((256, 256, 3))

def U_net(IMG_HEIGHT, IMG_WIDTH, IMG_CHANNELS):
    inputs = Input((IMG_HEIGHT, IMG_WIDTH, IMG_CHANNELS))
    s = Lambda(lambda x: x / 255) (inputs)
    
    c1 = Conv2D(16, (3, 3), activation='elu', kernel_initializer='he_normal', padding='same') (s)
    c1 = Conv2D(16, (3, 3), activation='elu', kernel_initializer='he_normal', padding='same') (c1)
    p1 = MaxPooling2D((2, 2)) (c1)   

    outputs = Conv2D(1, (1, 1), activation='sigmoid') (c2)
    model = Model(inputs=[inputs], outputs=[outputs])
    return outputs
m1 = U_net(256, 256, 3)
m2 = U_net(256, 256, 3)
m3 = concatenate([m1, m2])
x = Dense(10, activation='relu')(m3)
model = Model(inputs=[inputs, inputs2], outputs=[x])

The error message is:
RuntimeError: Graph disconnected: cannot obtain value for tensor Tensor("input_239:0", shape=(?, 256, 256, 3), dtype=float32) at layer "input_239". The following previous layers were accessed without issue: []

Hi everyone, 
I want to build a NN with multiple inputs with shared layers, but when i run my code, the problem above showed. Any ideal to solve it?

What if I want to define it as a function if the architecture is complex so I can reuse it? What if I hope to use the merged layer above, m3 as inputs of another deep conv layer such as Resnet 50?

Thanks

**Comment by fchollet** [comment]
It means your model topology is invalid. A valid model is one where the outputs passed to `Model` can be computed using the inputs passed to `Model` (and nothing else).
