### ISSUE TITLE
Memory usage exponentialy increases when model compiled inside a loop

### ISSUE THREAD

**Issue by potholiday** [keras-team/keras#9151]
I have a problem in which **I have to** compile the model inside a loop against compiling outside it without resetting the weights.

```
model = Sequential()
.
.
.
model.add(Dense(5))
for i in range(episodes):
      model.compile(loss=Customizedloss, optimizer='rmsprop')
      model.fit(x,y)            
```

My thinking was; when I compile a model  inside the loop it should overwrite the previous model to new one having different parameters with previous models weights.  But when I run the model it started to use memory exponentially and then ran out of memory very fast. Is it supposed to do this?

**Comment by fchollet** [comment]
Two things you could do to fix this:

1) Use TF graph scopes:

```python
for i in range(episodes):
   graph = tf.Graph()
   with graph.as_default():
       model = get_model()
       model.compile(...)
       model.fit(...)
```
2) Use `K.clear_session()`:

```python
for i in range(episodes):
      model = get_model()
      model.compile(...)
      model.fit(...)
      keras.backend.clear_session() 
```
