### ISSUE TITLE
ValueError on Conv3D Autoencoder

### ISSUE THREAD

**Issue by aidinhass** [keras-team/keras#9153]
I've implemented a CONV3D Autoencoder, but got stuck in training.

I am on Theano backend:
```
keras.backend.image_data_format()
Out[79]: 'channels_first'
```
```
ks.backend.image_dim_ordering()
Out[81]: 'th'
```
Here is my model summary for input sample patches of shape (204, 20, 20):
```
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input (InputLayer)           (None, 1, 204, 20, 20)    0         
_________________________________________________________________
conv1 (Conv3D)               (None, 30, 204, 20, 20)   840       
_________________________________________________________________
pool1 (MaxPooling3D)         (None, 30, 102, 10, 10)   0         
_________________________________________________________________
conv2 (Conv3D)               (None, 20, 102, 10, 10)   16220     
_________________________________________________________________
pool2 (MaxPooling3D)         (None, 20, 51, 5, 5)      0         
_________________________________________________________________
conv3 (Conv3D)               (None, 10, 51, 5, 5)      5410      
_________________________________________________________________
conv5 (Conv3D)               (None, 20, 51, 5, 5)      5420      
_________________________________________________________________
pool5 (UpSampling3D)         (None, 20, 102, 10, 10)   0         
_________________________________________________________________
conv6 (Conv3D)               (None, 30, 102, 10, 10)   16230     
_________________________________________________________________
pool6 (UpSampling3D)         (None, 30, 204, 20, 20)   0         
_________________________________________________________________
conv7 (Conv3D)               (None, 1, 204, 20, 20)    811       
=================================================================
Total params: 44,931
Trainable params: 44,931
Non-trainable params: 0
_________________________________________________________________
```
I have used 'same' padding with (2,2,2) for both max pooling and up sampling.
For training, I am reshaping the data samples to 5D tensors where I have the convolution dimension in the last three. Here are the print outs:
```
x_patched_train_h5.shape
Out[83]: (83328, 1, 204, 20, 20)

x_patched_valid_h5.shape
Out[84]: (27776, 1, 204, 20, 20)
```
For me the setup looks right but still as soon as I do start training either with HDF5Matrix dataset or a generator routine, training triggers this ValueError:

```
ValueError: setarray failed
Apply node that caused the error: GpuAlloc<None>(GpuElemwise{Composite{(i0 * (i1 + Abs(i1)))}}[]<gpuarray>.0, Shape_i{0}.0, TensorConstant{20}, TensorConstant{51}, TensorConstant{2}, TensorConstant{5}, TensorConstant{5})
Toposort index: 267
Inputs types: [GpuArrayType<None>(float32, (False, False, False, True, False, False)), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int8, scalar), TensorType(int64, scalar), TensorType(int64, scalar)]
Inputs shapes: [(2, 20, 52, 1, 6, 6), (), (), (), (), (), ()]
Inputs strides: [(149760, 7488, 144, 144, 24, 4), (), (), (), (), (), ()]
Inputs values: ['not shown', array(2), array(20), array(51), array(2, dtype=int8), array(5), array(5)]
Outputs clients: [[GpuReshape{5}(GpuAlloc<None>.0, MakeVector{dtype='int64'}.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```
Am I missing anything here? Appreciate your help.

Thanks
Aidin

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps
```
keras.__version__
Out[5]: '2.1.3'
```

- [ ] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps
```
theano.__version__
Out[3]: u'1.0.1'
```
- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by fchollet** [comment]
I suggest running your code with the TF backend to make it easier to debug. Theano error messages can be very cryptic.

If you want us to help you further, you should a short standalone code snippet to reproduce your issue.

> GpuAlloc

This sounds like it could be a memory error or an internal Theano error.

**Comment by aidinhass** [comment]
I managed run the code on Tensor Flow backend. Thanks for the help.

I'm dealing with huge spectral images, I will post a simplified version of it.

**Comment by aidinhass** [comment]
@fchollet, just reproduced the simplified standalone code and here is the gist:

https://gist.github.com/aidinhass/58f7e9bd2b43778c5b600a0ac397c5df

This runs smoothly on TF backend but keeps crashing on Theano.

**Comment by fchollet** [comment]
If it works with TF, then it is 90% likely to be an internal Theano error (which is consistent with the error message you're getting).

My recommendation is for you to switch to TF for this model. As you know, Theano is no longer being actively developed.
