### ISSUE TITLE
backend.sqrt is always hit tfdbg's has_inf_or_nan.

### ISSUE THREAD

**Issue by mercy0387** [keras-team/keras#9161]
I found misleading `inf` in keras code when I want to solve my `nan` problem.

This is my minimal debug code.
```
from keras.models import Model
from keras.layers import Input, Lambda, Activation
from keras.utils import np_utils
import keras.backend as K
import numpy as np
import tensorflow as tf
from tensorflow.python import debug as tf_debug

sess = tf.Session()
sess = tf_debug.LocalCLIDebugWrapperSession(sess)
K.set_session(sess)

inputs = Input(shape=(5,))
sqrts = Lambda(lambda x: K.sqrt(x))(inputs)
outputs = Activation('softmax')(sqrts)
model = Model(inputs, outputs)
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])

X = np.random.random((10, 5))
y = np_utils.to_categorical([np.random.randint(0,5) for _ in range(10)], num_classes=5)

model.fit(X, y, epochs=100)
```

I execute this code and input `run -f has_inf_or_nan` in debug console.
And soon, I found `inf` at `Const` and it confused me.

After my searching, I found the cause of this problem.
https://github.com/keras-team/keras/blob/master/keras/backend/tensorflow_backend.py#L1447
This model is hit by `has_inf_or_nan` filter because `K.sqrt` always has `inf` tensor.

I didn't search another causes but at least, this is a problem when debugging with tfdbg and has_inf_or_nan filter.

Is there any work around this problem?
If not, I think it should be fixed not to disturb during using tfdbg.

**Comment by mercy0387** [comment]
If `tf.clip_by_value` is needed, I propose that using `np.iinfo(x.dtype).max` or `np.finfo(x.dtype).max` instead of `np.inf` tensor.
Is that problem?

**Comment by fchollet** [comment]
I think the current implementation was meant to work around some issue that may no longer exist. I would recommend switching to implementing `K.sqrt()` simply as `tf.sqrt()`.

**Comment by caisq** [comment]
@mercy0387 It may makes sense to file a feature request for TensorFlow tfdbg to let the `has_inf_or_nan` filter take an optional argument of ignoring op names that match a regex. If you agree, please file one at https://github.com/tensorflow/tensorflow/issues

**Comment by mercy0387** [comment]
@fchollet Thank you for reply.
This is the simplest way to work around! 
And I will make PR to fix `K.sqrt()` implementation if there's no issue as you say. Is that OK?
Or is there any reason to leave it this version's implementation?

@caisq That sounds good idea! Even if I can work around this issue's problem, I'll make a feature request. Thanks.

**Comment by mercy0387** [comment]
@fchollet I found your solution is not enough for me because adam optimizer uses `K.sqrt()` in implementation ( https://github.com/keras-team/keras/blob/master/keras/optimizers.py#L449 ).
So I think more that it should be fixed in keras code.

**Comment by mercy0387** [comment]
@caisq I made new issue about your idea. https://github.com/tensorflow/tensorflow/issues/16619

I think option can be took by `add_tensor_filter` than `has_inf_or_nan` function because filter function should have two args, `datum` and `tensor`, and this args are passed by tfdbg, not user.
