### ISSUE TITLE
 K.one_hot(

### ISSUE THREAD

**Issue by YaDonskov** [keras-team/keras#9166]
I think that  K.one_hot has non-deterministic behaviour - for example when I write such code
`K.eval(K.one_hot([5], 2)) `
output is [0.0, 0.0]

and 
`K.eval(K.one_hot([0], 2))`
output is [1.0, 0. 0]
II think in first case output should be [0.0, 1.0] and in 2nd case it should be [0.0, 0.0]

**Comment by Dref360** [comment]
How is this non-deterministic? It's a pure function.

5 is greater than 2 so of course, the output will be [0., 0.]. You ask for the index 6 to be one, but your array is of length 2. 
It is the expected behavior.

**Comment by YaDonskov** [comment]
Sry, you are right.
