### ISSUE TITLE
batch_dot "Dimensions must be equal"

### ISSUE THREAD

**Issue by Atnas1010** [keras-team/keras#9175]
`batch_dot` does not work when the input is 4D and needs "broadcasting".

```
import keras.backend as K
from keras.layers import Input

x_batch = K.ones(shape=(32, 20, 1, 1))
y_batch = K.ones(shape=(32, 30, 20, 3))

xy_batch_dot = K.batch_dot(x_batch, y_batch, axes=[1, 2])
```
`ValueError: Dimension 1 in both shapes must be equal, but are 20 and 30 for 'MatMul_1' (op: 'BatchMatMul') with input shapes: [32,20,1,1], [32,30,20,3].`

Running on: Windows, tensorflow, CPU

Firstly I would like confirmation that other people agree that this is a bug, before we try fixing it.

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by brainnoise** [comment]
batch_dot uses tensorflow matmul op and that does not support broadcasting yet. Please see [tensorflow issue](https://github.com/tensorflow/tensorflow/issues/216).

You can work around this by reshaping the matrices. 
```
import keras.backend as K
from keras.layers import Input

x_batch = K.ones(shape=(32, 20, 1, 1))
y_batch = K.ones(shape=(32, 30, 20, 3))

x_batch = K.reshape(x_batch, [32, 20, 1])
y_batch = K.reshape(y_batch, [32, 90, 20])

xy_batch_dot = K.batch_dot(x_batch, y_batch, axes=[1, 2])
xy_batch_dot = K.reshape(xy_batch_dot, [32, 1, 30, 3])
```
