### ISSUE TITLE
Model.fit(verbose=0) should print nothing at all

### ISSUE THREAD

**Issue by jhihn** [keras-team/keras#9177]
- [X] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

-Rest omitted because Not Applicable

Issue:
When using Model.fit(verbose=0), Keras still prints:
`4/4 [==============================] - 0s 10ms/step`
at the end of the fit() function. 

Expected:
From the docs:
`verbose: 0, 1, or 2. Verbosity mode. 0 = silent, 1 = progress bar, 2 = one line per epoch.`
IMHO, verbose=0 should mean print _nothing_at_all. I like to do my own stats, and I have all these bars lines cluttering the logs.

**Comment by fchollet** [comment]
Can't repro; `fit(..., verbose=0)` prints nothing.

**Comment by jhihn** [comment]
Doh, Nevermind. it's evaluate, and that's got it's own verbose.
