### ISSUE TITLE
Am I applying keras.utils.to_categorical correctly for one-hot encoding in a 2D image semantic segmentation problem?

### ISSUE THREAD

**Issue by dimjones82** [keras-team/keras#9180]
I am working on a 2D RGB pixel-based image classification problem via convolution neural networks (CNN). I will fully describe my problem and provide as much details as possible.

I split my training and validation as follows:

`x_trn, x_val, y_trn, y_val = train_test_split(img, msk,test_size=0.2, random_state=42)
`

where `img `is an array of` (number_of_image_patches x image_rows x image_columns x number_of_image_channels)`. So I have 200 RGB(i.e., 3 channels) image patches at `128x128` each. Thus, the `img `array is a `(200 x 128 x 128 x 3)`.

Also, `msk `is an array containing the class labels of each image patch that will be used to train the CNN and has a size of `(200 x 128 x 128)`. Each `msk `patch is a `128x128` array with the class labels. In my problem, I have `7 classes`.

Since my problem is a multi-class classification, I am using `categorical_crossentropy `as my loss function. And `softmax `as my activation function for output results. My full CNN model can be found [here](https://gist.github.com/anonymous/8871bec87bcdd5375326e9511cec0718).

The shape of `y_trn `is `(160 x 128 x 128)` and `y_val `is `(40 x 128 x 128)`.

Now, `categorical_crossentropy `requires that the `y_trn `and `y_val `variables to be one-hot encoded. I do this as follows:

```
from keras.utils import to_categorical
y_trn= to_categorical(y_trn, num_classes=len(np.unique(y_trn)))
y_val= to_categorical(y_val, num_classes=len(np.unique(y_val)))

```
The new shape of `y_trn `after applying one-hot encoding is `(2621440 x 7)` due to the fact that I have `7 classes`. The `2621440 `comes from the multiplication of `160x128x128`

Afterwards, I do the following to train/fit the CNN model:

```
model =  my_CNN_unet()

model_checkpoint = ModelCheckpoint('unet6_test_{epoch:02d}.hdf5')
model.fit(x_trn, y_trn, batch_size=50, epochs=3, verbose=1, shuffle=True,
          callbacks=[model_checkpoint], validation_data=(x_val, y_val))
```
But I get the following error:

`ValueError: Error when checking target: expected conv2d_138 to have 4 dimensions, but got array with shape (2621440 , 7)`

This means that my one-hot encoding is obviously not being applied correctly as it expects a the one-hot array to be `4D`. I am assuming the correct size of y_trn should be: `(160 x 128 x 128 x 7)`.

I am new to both Python and Keras and not sure how to overcome this error. Any insights are welcome

**Comment by rex-yue-wu** [comment]
I think the problem here is that `to_categorical` is supposed to work with vectors instead of tensors. To work around this, you can simply `reshape`

```python
import numpy as np
from keras.utils import to_categorical

def to_categorical_tensor( x3d, n_cls ) :
      batch_size, n_rows, n_cols = x3d.shape
      x1d = x3d.ravel()
      y1d = to_categorical( x1d, num_classes = n_cls )
      y4d = y1d.reshape( [ batch_size, n_rows, n_cols, n_cls ] )
      return y4d

num_classes = 7
y_trn= to_categorical_tensor(y_trn, num_classes=num_classes)
y_val= to_categorical_tensor(y_val, num_classes=num_classes)
``` 
Note, it is tricky to compute number of classes, and the way that you did is problematic and might cause issues. 

In short, 
- `num_classes` should not be recomputed for validation. Otherwise, you can't guarantee this one-hot encoding is done in the exactly same way as in training.
- the implicit assumption of `to_categorical` is that `y` is a class vector, which means `y` should only contains elements in `[0, 1, ..., num_classes-1 ]`. If not, you have to convert `y` to the correct format first.
- if your `y` is a class vector, then `num_classes = np.max( y ) + 1`
