### ISSUE TITLE
Running only specific subset of the model

### ISSUE THREAD

**Issue by r-kellerm** [keras-team/keras#9184]
Hello,

Can I do in Keras something equivalent to [Net::ForwardFromTo](http://caffe.berkeleyvision.org/doxygen/classcaffe_1_1Net.html#ae5354c03371d4cb7b18988561790e676) in Caffe - forwarding only a subset of the model, from layer x to layer y?

Thanks!

**Comment by brainnoise** [comment]
You cannot specify subset of layers of an existing model. You can however create a new model pretty easily using the layers you already have. 

- Create new input
- Apply the layers from x to y
- Create model with the new input and the output of layer y

Hope this helps!
