### ISSUE TITLE
ValueError: Error when checking input: expected input_6 to have 4 dimensions, but got array with shape (23, 512, 512)

### ISSUE THREAD

**Issue by Deba-tintin** [keras-team/keras#9196]
I am absolutely new to deep learning, image processing, Github world. Please check my code in the given collabedit.com link and help me to overcome the error. I have provided the error message too along with the code.Thanks in advance.

http://collabedit.com/knu9t

**Comment by rex-yue-wu** [comment]
It will be helpful if you can print out model summary, because it is hard to figure out which is the problematic layer named `input_7`.

**Comment by Deba-tintin** [comment]
The issue has been resolved. I was passing wrong parameters in model.fit().
