### ISSUE TITLE
Exception on train_on_batch with flat arrays

### ISSUE THREAD

**Issue by fru** [keras-team/keras#9209]
Hey team keras,

after updating to version 2.1.3 I get an exception after calling train_on_batch with a flat int array. 

The following commit should be the cause: https://github.com/keras-team/keras/commit/8ed57c168f171de7420e9a96f9e305b8236757df#diff-299cfd5886683a4b012f286403769fc1

I have added a comment to the new line 76 that when data is a flat list of integers x.ndim will throw an exception.

I dont undestand the commit, so can't really help with a fix, sorry.

Anyway, thanks for an awesome tool :-)

**Comment by fchollet** [comment]
This has been fixed in https://github.com/keras-team/keras/commit/db0707b7b25d16d3a26c8c9651987a7d0a441e5b
