### ISSUE TITLE
Strange error during training: Assertion failed (scn == 3 || scn == 4) in cvtColor

### ISSUE THREAD

**Issue by Longbowman** [keras-team/keras#9217]
I've got weird error using keras for image recognition. 
Do I need some preprocessing for image in attachment? 

code files used in development are derived from this project. [https://github.com/d4nst/RotNet](url)
https://gist.github.com/Longbowman/d23ba81b75494a9928f9b3a52d4bc58c
https://gist.github.com/Longbowman/d5140a27301d769b84945096f308bc57
https://gist.github.com/Longbowman/bbcd4d2c57cceb3c142ea5c07a242abe

train files are 
[newtest.zip](https://github.com/keras-team/keras/files/1670713/newtest.zip)

file examples are 
![2](https://user-images.githubusercontent.com/4450907/35479256-5a1ed51c-040c-11e8-9b78-d2def1134bf4.png)
![3](https://user-images.githubusercontent.com/4450907/35479257-5ae2797c-040c-11e8-87db-99e3097a2165.png)
![4](https://user-images.githubusercontent.com/4450907/35479258-5b8f6358-040c-11e8-9de1-cca7de578541.png)

this is an error 
Epoch 1/200
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /home/agogorishvili/opencv/opencv-3.3.0/modules/imgproc/src/color.cpp, line 10606
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /home/agogorishvili/opencv/opencv-3.3.0/modules/imgproc/src/color.cpp, line 10606
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /home/agogorishvili/opencv/opencv-3.3.0/modules/imgproc/src/color.cpp, line 10606
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /home/agogorishvili/opencv/opencv-3.3.0/modules/imgproc/src/color.cpp, line 10606
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /home/agogorishvili/opencv/opencv-3.3.0/modules/imgproc/src/color.cpp, line 10606
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /home/agogorishvili/opencv/opencv-3.3.0/modules/imgproc/src/color.cpp, line 10606
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /home/agogorishvili/opencv/opencv-3.3.0/modules/imgproc/src/color.cpp, line 10606
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /home/agogorishvili/opencv/opencv-3.3.0/modules/imgproc/src/color.cpp, line 10606
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /home/agogorishvili/opencv/opencv-3.3.0/modules/imgproc/src/color.cpp, line 10606
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /home/agogorishvili/opencv/opencv-3.3.0/modules/imgproc/src/color.cpp, line 10606
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /home/agogorishvili/opencv/opencv-3.3.0/modules/imgproc/src/color.cpp, line 10606
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /home/agogorishvili/opencv/opencv-3.3.0/modules/imgproc/src/color.cpp, line 10606
Traceback (most recent call last):
  File "train_funcaptcha.py", line 91, in <module>
    verbose=1
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 2115, in fit_generator
    generator_output = next(output_generator)
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.py", line 557, in get
    six.raise_from(StopIteration(e), e)
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 737, in raise_from
    raise value
StopIteration: /home/agogorishvili/opencv/opencv-3.3.0/modules/imgproc/src/color.cpp:10606: error: (-215) scn == 3 || scn == 4 in function cvtColor

-----------------------------------------------------------------------------
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by Dref360** [comment]
This is an issue from your generator, not from Keras.
Please close
