### ISSUE TITLE
pandas HDFStore conflicts with keras?!

### ISSUE THREAD

**Issue by qclijun** [keras-team/keras#9224]
Hello, When i use **pandas HDFStore** with keras, Python program collapsed.

```
import pandas as pd
print(pd.__version__)
df = pd.DataFrame({'a': [1, 2, 3]})
df.to_hdf('data.h5', 'table')
print(df)

import keras
print(keras.__version__)
```

The code is OK if i comment the line `df.to_hdf('data.h5', 'table')`.

-----------------------
System: Win10 x64
Pandas: 0.20.3
keras: 2.1.3

**Comment by CharlesAuthier** [comment]
What is your error message when your program collapse?
Because if I run those lines the error message  that gets me out is:
`ImportError: HDFStore requires PyTables, "No module named 'tables'" problem importing`
And this is not a Keras issue.

**Comment by CharlesAuthier** [comment]
Can you show the error message?
