### ISSUE TITLE
Keras, Tensorflow and memmap files

### ISSUE THREAD

**Issue by zurkin1** [keras-team/keras#9228]
I am trying to read a large dataset to train on a simple network on one GPU. I am using 5 large NumPy files (one for each feature) using e.g.:

user_id = np.load('data\user_id.npy', mmap_mode='r')

Both Tensorflow and Keras don't like it (meaning model.fit is running very slow). If I read the files directly to memory (no mmap_mode parameter) everything works fine. The problem is of course I cannot read large files this way.

Any suggestion?

**Comment by anj-s** [comment]
If you using Tensorflow the suggested way to import data is to use tf.data.dataset APIs found [here](https://www.tensorflow.org/api_docs/python/tf/data/Dataset).

Here is a [Keras example](https://github.com/keras-team/keras/blob/master/examples/mnist_dataset_api.py) that uses this API.

This should help speed up the model performance and aid in reading large files.

**Comment by ozabluda** [comment]
Did you try benchmarking with numpy? It likely has nothing to do with Keras/TF. Are you on Windows?

**Comment by zurkin1** [comment]
Yes I use Windows. What do you mean benchmarking with numpy? just looping and reading chunks from the same file using mmap_mode? hadn't tried it but surely this would be only slightly slower than reading the whole file (the TF .fit is much much slower).

**Comment by ozabluda** [comment]
Yes on chunks of the same size as one minibatch. You can't read the whole 5 file at once, they are too big by your description. The 5 file should also be exactly the same ones as for Keras. Flush the cache before benchmark. Use system monitoring tools to make sure it's doing what you think it's doing.
