### ISSUE TITLE
NCHW vs NHWC on pretrained network

### ISSUE THREAD

**Issue by jonilaserson** [keras-team/keras#9234]
I'm working with TF backend using CUDA and CUDNN.
I'm reading [here](https://github.com/ilkarman/DeepLearningFrameworks) and also in [PR #8021](https://github.com/keras-team/keras/pull/8021) that NCHW should be much faster than NHWC.

However, when I'm loading one of the pre-trained model, for example inception-v3, I'm being informed that: "For best performance, set `image_data_format="channels_last"`"

So which is it?  What is the optimal way to run the networks in `keras.application` ?

**Comment by fchollet** [comment]
Have you tried benchmarking it for your application?

**Comment by jonilaserson** [comment]
With the current inception implementation, NHWC is much faster than NCHW, but it's probably because the model was built to work natively on NHWC.
