### ISSUE TITLE
[User Problem] Convert V-net from Keras 1 to Keras 2

### ISSUE THREAD

**Issue by FiReTiTi** [keras-team/keras#9254]
Hi,

I am trying to convert a V-net code I found from Keras 1 to Keras 2. I've updated everything, but I have a problem with the following class:

    class Deconv3D(Layer):
        def __init__(self, nb_filter, kernel_dims, output_shape, strides):
            assert K.backend() == 'tensorflow'
		self.nb_filter = nb_filter
		self.kernel_dims = kernel_dims
		self.strides = (1,) + strides + (1,)
		self.output_shape_ = output_shape
		super(Deconv3D, self).__init__()
		
	def build(self, input_shape):
		assert len(input_shape) == 5
		self.input_shape_ = input_shape
		W_shape = self.kernel_dims + (self.nb_filter, input_shape[4], )
		self.W = self.add_weight(W_shape, initializer=functools.partial(initializers.glorot_uniform), name='{}_W'.format(self.name))
		self.b = self.add_weight((1,1,1,self.nb_filter,), initializer='zero', name='{}_b'.format(self.name))
		self.built = True
											
	def get_output_shape_for(self, input_shape):
		return (None, ) + self.output_shape_[1:]
													
	def call(self, x, mask=None):
		return tf.nn.conv3d_transpose(x, self.W, output_shape=self.output_shape_, strides=self.strides, padding='same', name=self.name) + self.b

When I call it using `Deconv3D(128, (2, 2, 2), (1, 16, 16, 8, 128), (2, 2, 2))(X)`, I get the following error that I don't understand:

    Traceback (most recent call last):
      File "V-net.py", line 118, in <module>
    downsample_5 = Deconv3D(128, (2, 2, 2), (1, 16, 16, 8, 128), (2, 2, 2))(prelu_5_1) # Check the 8
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/keras/engine/topology.py", line 569, in __call__
    self.build(input_shapes[0])
      File "V-net.py", line 35, in build
    self.W = self.add_weight(W_shape, initializer=functools.partial(initializers.glorot_uniform), name='{}_W'.format(self.name))
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/keras/engine/topology.py", line 391, in add_weight
    weight = K.variable(initializer(shape), dtype=dtype, name=name)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 321, in variable
    v = tf.Variable(value, dtype=_convert_string_dtype(dtype), name=name)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 200, in __init__
    expected_shape=expected_shape)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 278, in _init_from_args
    initial_value(), name="initial_value", dtype=dtype)
    TypeError: __call__() missing 1 required positional argument: 'shape'

What am I doing wrong?
Thank you for your help.

**Comment by vessemer** [comment]
Hi, @FiReTiTi, it's possibly due to the differences in Keras versions, for the `version==2.1.2` this class should be rewritten as follows:
```python
class Deconvolution3D(Layer):
    
    def __init__(self, nb_filter, kernel_dims, output_shape, subsample, **kwargs):
        self.nb_filter = nb_filter
        self.kernel_dims = kernel_dims
        self.strides = (1, ) + subsample + (1, )
        self.output_shape_ = output_shape
        assert K.backend() == 'tensorflow'
        super(Deconvolution3D, self).__init__(**kwargs)
        
    def build(self, input_shape):
        assert len(input_shape) == 5
        self.W = self.add_weight(shape=self.kernel_dims + (self.nb_filter, input_shape[4], ),
                                 initializer='glorot_uniform',
                                 name='{}_W'.format(self.name),
                                 trainable=True)
        self.b = self.add_weight(shape=(1, 1, 1, self.nb_filter,), 
                                 initializer='zero', 
                                 name='{}_b'.format(self.name),
                                 trainable=True)
        super(Deconvolution3D, self).build(input_shape) 

    def call(self, x, mask=None):
        return tf.nn.conv3d_transpose(x, self.W, output_shape=self.output_shape_,
                                      strides=self.strides, padding='SAME', name=self.name) + self.b

    def compute_output_shape(self, input_shape):
        return (input_shape[0], ) + self.output_shape_[1:]
```

**Comment by FiReTiTi** [comment]
Thanks a lot for your help, it works!!!

**Comment by FiReTiTi** [comment]
It seems that I have an error :-(

    Using TensorFlow backend.
    Traceback (most recent call last):
      File "/eppec/storage/sw/conda/envs/ThibaultPython35/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
      File "/eppec/storage/sw/conda/envs/ThibaultPython35/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
      File "/eppec/storage/sw/conda/envs/ThibaultPython35/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
    tensorflow.python.framework.errors_impl.InvalidArgumentError: Conv3DBackpropInput: input and out_backprop must have the same batch size
         [[Node: deconv3d_1/deconv3d_1 = Conv3DBackpropInputV2[T=DT_FLOAT, data_format="NDHWC", padding="SAME", strides=[1, 2, 2, 2, 1], _device="/job
    :localhost/replica:0/task:0/device:GPU:0"](deconv3d_1/deconv3d_1/output_shape, deconv3d_1/deconv3d_1_W/read, p_re_lu_11/add)]]
         [[Node: loss/mul/_515 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_5083_loss/mul", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

I took a look online and it seems that be an old error that was fixed on Keras, but I probably something wrong with the output dimensions.
Any idea?
