### ISSUE TITLE
Attentive Convolution

### ISSUE THREAD

**Issue by stoney95** [keras-team/keras#9263]
Hi,

I've implemented a layer that is doing attentive convolution like described in this paper: https://arxiv.org/pdf/1710.00519.pdf.
You can see the code for it at: https://gist.github.com/stoney95/9c71bb7f7008b7d01dcf8f6bf3afaeff

I'm new to implementing custom layers and it is still very slow. I'm using a lot of tf.map_fn and i think this is the reason why it's so slow, but I don't know a different way to do this.
It would be nice if someone has some tips how to improve the layer or general tips on implementing custom layers like how to avoid backend (tensorflow) functions.

I'm using keras 2.1.3 and tensorflow 1.5 as backend. 

Thanks

**Comment by HalaKuwatly** [comment]
Hi, I am interested in the implementation. any luck?

**Comment by stoney95** [comment]
Hi,

more or less :D I have an implementation but I'm not quite sure if it works properly. But I will provide it for, so you can decide on your own if you want to use it:

https://gist.github.com/stoney95/3fc4216db7af0675df4d6326adb8aee0

This gist provides two files. One is the implementation of a custom Attention-layer the second one is how it is used in a cnn-implementation. If you have questions about the implementation feel free to ask but I implemented this some time ago
