### ISSUE TITLE
Concatenate tensor with constant vector in new axis

### ISSUE THREAD

**Issue by agamemnonc** [keras-team/keras#9265]
I am sure this must be a trivial thing but I can't find the answer online I am afraid.

Suppose that I have a tensor and want to concatenate it with some constant (it is fixed so I would rather avoid the burden of having to provide it as input every time) on a new axis. I have tried using a combination of Concatenate, Reshape and RepeatVector layers with no luck.

Here is an example:

```python
import numpy as np
from keras.layers import Input, Reshape, Concatenate, RepeatVector
import keras.backend as K

inputs = Input(shape=(10,)) # (?,10)
constant = K.variable(np.random.randn(10,)) # (10,)
X = Concatenate(axis=-1)([Reshape((-1,1))(inputs), RepeatVector(K.shape(inputs)[0])(Reshape((-1,))(constant))])
```

This will throw a ValueError:
```
ValueError: `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 10, 1), (10, <tf.Tensor 'strided_slice_7:0' shape=() dtype=int32>, 1)]
```

I think the problem is due to the fact that  `RepeatVector(K.shape(inputs)[0])(Reshape((-1,))(constant))` has `shape (10, ?, 1)` instead of `(?, 10, 1)`, as is also the shape of `Reshape((-1,1))(inputs)`.

What am I missing?

**Comment by ruslanasa** [comment]
Any luck?
