### ISSUE TITLE
VAE example, run TypeError: compile() takes at least 3 arguments (2 given)

### ISSUE THREAD

**Issue by doujiang-zheng** [keras-team/keras#9266]
https://github.com/keras-team/keras/blob/85f011df5a5c0fcf1f01b39eca338eb6b7e58401/examples/variational_autoencoder.py#L58

I take a look at **keras/engine/training.py**, and find that compile function do not need 3 arguments, so may be it's my version fault? 

I simply change the line of code to

`vae.compile(loss=None, optimizer='rmsprop')`

Will this change do some harm or strange behavior?

My packages are listed below:
Python=2.7.13
Keras=2.1.2
tensorflow==1.4.1
tensorflow-gpu==1.4.1

**Comment by tristanwietsma** [comment]
There is a Keras blog post that references the code (2016), however the implementation is slightly different. The loss function implementation is different. I tried this:

```python
# Compute VAE loss
def vae_loss(x, x_decoded_mean):
    xent_loss = original_dim * metrics.binary_crossentropy(x, x_decoded_mean)
    kl_loss = - 0.5 * K.sum(1 + z_log_var - K.square(z_mean) - K.exp(z_log_var), axis=-1)
    vae_loss = K.mean(xent_loss + kl_loss)

vae.compile(optimizer='rmsprop', loss=vae_loss)
```

However, I'm running into this traceback now:

```
Using TensorFlow backend.
Traceback (most recent call last):
  File "vae.py", line 50, in <module>
    vae.compile(optimizer='rmsprop', loss=vae_loss)
  File "/home/tristan/conda/lib/python3.6/site-packages/keras/engine/training.py", line 827, in compile
    sample_weight, mask)
  File "/home/tristan/conda/lib/python3.6/site-packages/keras/engine/training.py", line 439, in weighted
    ndim = K.ndim(score_array)
  File "/home/tristan/conda/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 606, in ndim
    dims = x.get_shape()._dims
AttributeError: 'NoneType' object has no attribute 'get_shape'
```

**Comment by pvskand** [comment]
@doujiang-zheng I removed the error by editing this:

`vae.compile(optimizer='rmsprop', loss=None)`
The loss is set to be `None`, because we are already adding the loss in the line:
`vae.add_loss(vae_loss)`. 
Hope this helps
