### ISSUE TITLE
Use Python logging instead of directly writing to stderr

### ISSUE THREAD

**Issue by mitar** [keras-team/keras#9272]
When running Keras on Tensorflow, it prints out such message:

```
Using TensorFlow backend.
```

This is currently done by [directly writing to stderr](https://github.com/keras-team/keras/blob/6f3e6bb6fc97e706f37dc078ae821f490b78035b/keras/backend/__init__.py#L82). When running in different environments it is sometimes better to use `logging` Python interface where you can configure different handlers and way to store such messages. For example, in our case, we can then collect all messages in a centralized location and process them accordingly.

I would suggest that such messages do something like `logger.info("Using TensorFlow backend.")` instead.

**Comment by maggyero** [comment]
I totally agree.

**Comment by mitar** [comment]
Why closing this issue?
