### ISSUE TITLE
Error in Tensorflow backend combining stateful RNN into a larger model

### ISSUE THREAD

**Issue by CPBridge** [keras-team/keras#9274]
I have been trying to create a model that combines a simple recurrent model followed by a feedforward network, but keep coming up against an error when using the Tensorflow backend even when I have reduced the problem to a minimum working example. The fact that **exactly the same example works as expected with the Theano backend** leads me to conclude that this is probably a bug not a user error.

The premise of the example is as follows: there are two submodels defined by the sequential API that define a recurrent submodel (using a stateful RNN) and a feedforward submodel. The two submodels are combined together to create a "full" model. (In my particular application I need to have separate submodels due to the way these components are used later, but this is not illustrated by this minimal example and is beyond the scope of this issue).

When you then try to use the recurrent submodel in isolation, I get what seems to be a low-level tensorflow error.

Here is the minimal example with some inline comments:

```python

import numpy as np
from keras.models import Sequential, Model
from keras.layers import Dense, Input, GRU
from keras.optimizers import RMSprop

# Various parameters (changing them makes no difference
# as far as this issue is concerned)
n_hidden_states = 5
n_inputs = 10
n_timesteps = 1
batch_size = 1

# If stateful is set to false, the error goes away
stateful = True

# A very simple recurrent submodel consisting of a single gru layer
# (using LSTM seems to create the same issue)
def get_recurrent_submodel():

    model = Sequential()
    model.add(GRU(n_hidden_states,
                  input_shape=(n_timesteps, n_inputs),
                  batch_size=batch_size,
                  stateful=stateful))
    return model

# A very simple feedforward model, consisting of a single, dense layer
def get_feedforward_submodel():

    model = Sequential()
    model.add(Dense(10, input_shape=(n_timesteps, n_hidden_states)))
    return model

# The combined model is simply the recurrent model, followed
# by the feedforward model
def get_combined_model(feedforward_model, recurrent_model):

    # Inputs
    x_in = Input(shape=(n_timesteps, n_inputs),
                 batch_shape=(batch_size, n_timesteps, n_inputs))

    # Recurrent submodel layer
    recurrent = recurrent_model(x_in)

    # Feedforward submodel
    out = feedforward_model(recurrent)

    # Create a new model
    model = Model(inputs=x_in, outputs=out)
    return model


# Create the submodels
recurrent_model = get_recurrent_submodel()
feedforward_model = get_feedforward_submodel()

# Combine the models into a full model
# If the following line is commented out, the error goes away
full_model = get_combined_model(feedforward_model, recurrent_model)

# A random input to test the model
test_input = np.random.normal(size=(batch_size, n_timesteps, n_inputs))

# Use the recurrent model for inference (even though it is untrained
# in this illustrative example)
# This line causes the error
out = recurrent_model.predict(test_input)
print(out)
```

When I execute this script, I get the following output:

```
Using TensorFlow backend.
2018-01-31 21:54:10.760287: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
Traceback (most recent call last):
  File "/home/chris/Developer/envs/keras_bug/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1350, in _do_call
    return fn(*args)
  File "/home/chris/Developer/envs/keras_bug/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1329, in _run_fn
    status, run_metadata)
  File "/home/chris/Developer/envs/keras_bug/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [1,1,10]
         [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[1,1,10], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "debug.py", line 67, in <module>
    out = recurrent_model.predict(test_input)
  File "/home/chris/Developer/envs/keras_bug/lib/python3.5/site-packages/keras/models.py", line 1028, in predict
    steps=steps)
  File "/home/chris/Developer/envs/keras_bug/lib/python3.5/site-packages/keras/engine/training.py", line 1803, in predict
    verbose=verbose, steps=steps)
  File "/home/chris/Developer/envs/keras_bug/lib/python3.5/site-packages/keras/engine/training.py", line 1303, in _predict_loop
    batch_outs = f(ins_batch)
  File "/home/chris/Developer/envs/keras_bug/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2475, in __call__
    **self.session_kwargs)
  File "/home/chris/Developer/envs/keras_bug/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/chris/Developer/envs/keras_bug/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1128, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/chris/Developer/envs/keras_bug/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1344, in _do_run
    options, run_metadata)
  File "/home/chris/Developer/envs/keras_bug/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1363, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [1,1,10]
         [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[1,1,10], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'input_1', defined at:
  File "debug.py", line 59, in <module>
    full_model = get_combined_model(feedforward_model, recurrent_model)
  File "debug.py", line 40, in get_combined_model
    batch_shape=(batch_size, n_timesteps, n_inputs))
  File "/home/chris/Developer/envs/keras_bug/lib/python3.5/site-packages/keras/engine/topology.py", line 1455, in Input
    input_tensor=tensor)
  File "/home/chris/Developer/envs/keras_bug/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/chris/Developer/envs/keras_bug/lib/python3.5/site-packages/keras/engine/topology.py", line 1364, in __init__
    name=self.name)
  File "/home/chris/Developer/envs/keras_bug/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 504, in placeholder
    x = tf.placeholder(dtype, shape=shape, name=name)
  File "/home/chris/Developer/envs/keras_bug/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 1680, in placeholder
    return gen_array_ops._placeholder(dtype=dtype, shape=shape, name=name)
  File "/home/chris/Developer/envs/keras_bug/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3141, in _placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "/home/chris/Developer/envs/keras_bug/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/chris/Developer/envs/keras_bug/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3160, in create_op
    op_def=op_def)
  File "/home/chris/Developer/envs/keras_bug/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'input_1' with dtype float and shape [1,1,10]
         [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[1,1,10], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

```

I am using the latest commit of Keras at the time of writing (fb1887d132a8ce8548ff53d868a6ba531cd63b34) on KDE NEON 5.11 (Ubuntu 16.04) using python 3.5. Here is my python environment (output of pip freeze):

```
absl-py==0.1.10
bleach==1.5.0
futures==3.1.1
html5lib==0.9999999
Keras==2.1.3
Markdown==2.6.11
numpy==1.14.0
protobuf==3.5.1
PyYAML==3.12
scipy==1.0.0
six==1.11.0
tensorflow==1.5.0
tensorflow-tensorboard==1.5.0
Theano==1.0.1
Werkzeug==0.14.1
```
To reiterate, the example works as expected (prints 5 random numbers) when I set `KERAS_BACKEND=theano`.

Big thank you to all Keras contributors!

**Comment by DeepWolf90** [comment]
I 'm having the same problem @CPBridge 

i traind stacked autoencoder in greedy layerwise, then in fine-tuning phase i get this weird error.

    # load three lstm layers
    layer1 = load_model('encoder1.h5')
    ayer2 = load_model('encoder2.h5')
    layer3 = load_model('encoder3.h5')

    # rename layer2 and layer3
    layer2.name = 'model_3'
    layer3.name = 'model_4'

    # built forecasting model
    timesteps = x_train.shape[1]
    input_dim = x_train.shape[2]
    inputs = Input(batch_shape=(1,timesteps, input_dim))
    lstm_1 = layer1(inputs)
    reshape = Reshape((1,19))(lstm_1)
    lstm_2 = layer2(reshape)
    reshape = Reshape((1,13))(lstm_2)
    lstm_3 = layer3(reshape)
    outputs = Dense(1)(lstm_3)

    model = Model(inputs,outputs)

    model.compile(loss='mean_squared_error', optimizer='Adam')

    for i in range(num_epochs):
    print("Epoch ",i,":")
    model.fit(x_train, y_train, epochs=1, batch_size=1, verbose=1,shuffle=False)
    model.reset_states()


    # evaluate model with validation data
    mse = model.evaluate(x_valid,y_valid,batch_size=1)
    rmse = sqrt(mse)
    print("RMSE = ",rmse)


this is my error:

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'input_1_2' with dtype float and shape [1,1,13] [[Node: input_1_2 = Placeholderdtype=DT_FLOAT, shape=[1,1,13], _device="/job:localhost/replica:0/task:0/device:CPU:0"]]

**Comment by CPBridge** [comment]
Thanks for confirming @DeepWolf90 . It would be useful to know whether your problem also goes away with the Theano backend, if you are in a position to try this. (Just set the environment variable like this before running your python script)

```bash export KERAS_BACKEND=theano```

as this would strengthen the case that this is a bug that needs attention, and not just user error on our parts!

**Comment by CPBridge** [comment]
Also @DeepWolf90 can you give a bit more detail about your trained encoders? Are they stateful LSTMs?

**Comment by DeepWolf90** [comment]
@CPBridge  Actually the problem goes with theano backend also, and yes the encoders are stateful.

**Comment by CPBridge** [comment]
Seems like this might be related to a previous issue #9174 
Possibly going back to a previous version of Keras < 2.0.9 will fix this in the short term. I will try later

**Comment by CPBridge** [comment]
I can confirm that the bug was already present in Keras 2.0.8

**Comment by MrMathias** [comment]
I get the same error when implementing a stateful verison of the [multi input/output example in Keras](https://keras.io/getting-started/functional-api-guide/#multi-input-and-multi-output-models)

* Keras 2.1.2
* tensorflow 1.3.0

`InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'lstm_1_input' with dtype float and shape [1,1,1]
	 [[Node: lstm_1_input = Placeholder[dtype=DT_FLOAT, shape=[1,1,1], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]`

**Comment by kbhardwa** [comment]
Any update on this? How to fix this problem of "You must feed a value for placeholder tensor 'input_1' with dtype float and shape [something]"??? I am facing similar issue for knowledge-distillation kind of setup too: e.g., transfer soft-logits from one model to another as described in Hinton's paper (https://arxiv.org/pdf/1503.02531v1.pdf). That is, I am compiling 2 models in the same keras code with tensorflow backend.
