### ISSUE TITLE
Getting shape error

### ISSUE THREAD

**Issue by tetra7** [keras-team/keras#9282]
```
data = pd.read_csv("mk.csv")
dataset = data.values



x = dataset[:,0:3]
y = dataset[:,3]
model = Sequential()

model = Sequential()
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(3, activation='softmax'))
 
model.compile(optimizer=Adam(lr=0.1),loss=binary_crossentropy,metrics=['accuracy'])
model.fit(x,y,epochs=505)
```

x:
> array([[500,   6,  72],
>        [300,   5,  50],
>        [700,   5,  50],
>        [600,   5,  50],
>        [500,   5,  50],
>        [300,   5,  50],
>        [300,   5,  50],
>        [300,   5,  50],
>        [300,   5,  50],
>        [300,   5,  50]], dtype=int64)
> 

y:

> array([19, 12, 12, 12, 12, 12, 12, 12, 12, 12], dtype=int64)

My dataset:

`array([[500,   6,  72,  19],
       [300,   5,  50,  12],
       [700,   5,  50,  12],
       [600,   5,  50,  12],
       [500,   5,  50,  12],
       [300,   5,  50,  12],
       [300,   5,  50,  12],
       [300,   5,  50,  12],
       [300,   5,  50,  12],
       [300,   5,  50,  12]], dtype=int64)`

When i run the program, i get the error : "Error when checking input: expected dense_76_input to have shape (None, 4) but got array with shape (10, 3)"
Thanks for any help

**Comment by brainnoise** [comment]
Your input is a 3 dimensional vector so setting input_dim=3 should fix this. Here is more information about [specifying input shape](https://keras.io/getting-started/sequential-model-guide/#specifying-the-input-shape).

**Comment by souptc** [comment]
`model.add(Dense(8, input_dim=4, activation='relu'))`

you define your input dimension with 4 but the data you feed in is with dimension 3.
