### ISSUE TITLE
Large Model Zoo for Keras along like Caffe2 but even better for the community of contributors

### ISSUE THREAD

**Issue by shyamalschandra** [keras-team/keras#9284]
Why doesn't the Keras team have an "official" and "large" model zoo like Caffe2 [https://github.com/caffe2/caffe2/wiki/Model-Zoo]?

I see the following repositories on Github but they are indeed insufficient:

https://github.com/albertomontesg/keras-model-zoo
https://github.com/Yoctol/yoctol-keras-layer-zoo
https://github.com/david-vazquez/keras_zoo
https://github.com/GKalliatakis/Keras-Application-Zoo

What is the best way to get people to start sharing pretrained models in terms of the following:
1. opening up an issue
2. discussing this over the mailing list
3. having you send an email to the major contributors of keras or even the committers

Please let me know if you have any further questions or concerns.

Thanks!

**Comment by DonaldTsang** [comment]
Same https://github.com/keras-team/keras/issues/9276
