### ISSUE TITLE
ValueError: cannot reshape array

### ISSUE THREAD

**Issue by pranitapradhan91** [keras-team/keras#9285]
Dear all,

I want to use VGG16 model with Theano backend on CPU.  When I load the model I get an error as below

![image](https://user-images.githubusercontent.com/25509717/35724234-4e17d71a-07fd-11e8-88de-4c74b8d561ae.png)

I have updated keras (version 1.0.0) and theano (2.0.9) version. Any suggestions?

**Comment by brainnoise** [comment]
Can you share the settings in your `$HOME/.keras/keras.json` file and also the values for num_channel, img_rows and img_cols. 

I tried the following code snippet and it works:
```
from keras import applications
from keras.layers import Input

image_input = Input(shape=(3, 224, 224))
model = applications.vgg16.VGG16(include_top=True, weights='imagenet', input_tensor=image_input)
model.summary()
```

**Comment by pranitapradhan91** [comment]
Thank you for your reply.
Its working for me too.
