### ISSUE TITLE
Resource leak of file handles

### ISSUE THREAD

**Issue by bzamecnik** [keras-team/keras#9287]
There's at least one resource leak of file handle in `keras.engine.topology.save_weights()`:

```python
 f = h5py.File(filepath, 'w')
save_weights_to_hdf5_group(f, self.layers)
f.flush()
f.close()
```

When `save_weights_to_hdf5_group()` raises an exception the file doesn't get closed.

The easiest fix is idiomatic:

```python
with h5py.File(filepath, 'w') as f:
    save_weights_to_hdf5_group(f, self.layers)
    f.flush()
```

We should check for other similar occurrences. Eg.:

- `keras.models.load_weights()`
- `keras.models.save_weights()`
- `keras.engine.topology.load_weights()`
- `keras.engine.topology.save_weights()`
- `keras.utils.HDF5Matrix`
  - the file handle is stored in the class, so the class itself should act as a context manager, or we should check its usage
- `tests`/`keras.utils.io_utils_test.create_dataset()`
- examples/babi_rnn: `tarfile.open()` not closed at all
- examples/mnist_acgan: `open()` not closed at all
- keras.backend.__init__: `open()` not closed at all
- `keras.datasets.cifar.load_batch()`
- `keras.datasets.imdb.get_word_index()`
- `keras.datasets.reuters.get_word_index()`
- `docs.autogen` - several instances of `open()` not being closed

Also there are some docs examples with unsafe usage of `open()`:

- `keras.models.Sequential.fit_generator()`
- `keras.engine.training.fit_generator()`
- `keras.callbacks.LambdaCallback`

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by bzamecnik** [comment]
I can fix that within next few days.

**Comment by bzamecnik** [comment]
`HDF5Matrix` holds references to open `h5py.File`s in a class attribute. The user of this class has no proper way how to close the open files. Moreover multiple instances of `HDF5Matrix` can point to the same open `h5py.File`. A user trying to close the file by peeking into the class attributes may close file shared with another instance. There's no reference counting.

**Comment by mrtj** [comment]
Hello, do you have any news regarding to the resource leak of hdf5 file handlers in HDF5Matrix? It seems it was not fixed yet. Should we open a separate issue for that bug?
