### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by ishihiroki** [keras-team/keras#9295]
My environment

python 3.5.2 anaconda (use pyenv)
keras 2.3.0
tensorflow 1.4.1
theano 1.0.1
cntk 2.3

When backend is tensorflow, TypeError occurs just before learning is finished.

TypeError: 'NoneType' object is not callable

Is there a solution?

**Comment by ishihiroki** [comment]
I'm sorry...

keras version is 2.1.3

**Comment by brainnoise** [comment]
Can you please share a standalone code snippet that can help reproduce the problem?

**Comment by chethh** [comment]
Same problem happens using github/keras/examples/neural_doodle.py.

**Comment by chethh** [comment]
Using latest nvidia, cuda 9.0, tensorflow 1.5, keras installed by current pip3.

**Comment by AlexanderKUA** [comment]
The same issue with

**Comment by hfawaz** [comment]
same issue

**Comment by noirmist** [comment]
I had the same issue. But I tried it again, and it is working fine. It's weird.

**Comment by alexlao** [comment]
I've been getting this issue as well. It only happens sometimes. It's unfortunate for it to happen after a long training session, as this prevents me from being able to save my models.

**Comment by YunheFeng** [comment]
the same issue on tensorflow:1.7.1-devel-gup-py3 docker tags. Sometimes it works, while sometimes the issue occurs.

**Comment by xiaohk** [comment]
Same issue

**Comment by tgamauf** [comment]
Same here.

Python 3.5.2
Keras 2.1.5
Tensorflow 1.7

**Comment by AsimSaif001** [comment]
same issue 
python 3.5
keras 2.1

**Comment by nguyenvulong** [comment]
same here
python 3.5.2
tensorflow 1.10.1 (with built-in keras)
pip 18.0

**Comment by kk2491** [comment]
As a workaround you can fix the error by writing the below 2 lines of code at the end of training code. 
```
import gc
gc.collect()
```

**Comment by morpheusthewhite** [comment]
Same here
python 3.5
tensorflow 1.10
keras 2.2.4

**Comment by clappis** [comment]
I had the same issue. In my case, delete the \_\_pycache\_\_ was a workaround. 
`rm -rf /usr/lib/{PYTHON_VERSION}/__pycache__/`

**Comment by supratik-bhattacharya-2020** [comment]
Same here
python 3.6.9
tensorflow 1.9

**Comment by anoopkdcs** [comment]
Try with (must enable the GPU)
tf.__version__ == **2.4.0** 
keras.__version__ == **2.4.3**
!python --version == **Python 3.6.9**
print(tf.config.list_physical_devices('GPU')) == [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

for me also the same error occurs when I run without enabling the GPU.
but after enabling GPU with the same tf, keras, and python 3.6. It works fine.

**Comment by 100rab-S** [comment]
I also faced the same issue. In my case I had a multi output model which was creating the problem. In compile method I had two different metrics for each output layer. But as soon as I replaced the metric with a single metric, the error was gone. Sometimes the error might be from something that doesn't seem to be obvious as can be seen in my case.

**Comment by Armanasq** [comment]
Same problem here

tf.version == 2.9.1
keras.version == 2.9.0
python --version == Python 3.8
