### ISSUE TITLE
Multiple inputs, multiple outputs passing through a dense layer, training is not as expected

### ISSUE THREAD

**Issue by timprepscius** [keras-team/keras#9300]
Firstly, I have googled for this answer, and I'm not finding it.  If this is a repeat question, I apologize.
I am using the tensorflow backend.

I have a network with this overall structure:
```
input1 = Input(...)
input2 = Input(...)

sharedDense = Dense(...)
dense1 = sharedDense(input1)
dense2 = sharedDense(input2)

output1 = Dense(...)(dense1)
output2 = Dense(...)(dense2)

inputs = [input1, input2]
outputs = [output1, output2]
loss = keras.losses.mean_squared_error

model = Model(inputs=inputs, outputs=outputs)
model.compile(
    loss=[loss, loss],
    optimizer=keras.optimizers.Adadelta()
)

```
I run it with an appropriate generator.

I have two input->output sets which get sent out via the generator.
Let's call them the "where is the BANANA" in/out and "where is the APPLE" in/out

So, if I train this network with 
BANANA, APPLE

(meaning the input1->output1 is paired with BANANA and the input2->output2 is paired with the APPLE)

Only the APPLE is trained.  The banana actually gets a bit better, but I think it is happenstance.

If I train the network with
APPLE, BANANA

Only the BANANA is trained

---

Is there anyway I can verify that keras is attempting to train backpropagating up both input to output paths?

Is there a best way I can debug this?  I have spent time verifying my inputs and outputs of course.  However I am not as of yet comfortable saying this is a keras bug and not my bug.

I'm looking for a way to verify explicitly that backpropagation of both is ocuring and one is not "overwriting" the other.

Thanks for your help!

**Comment by crvogt** [comment]
Hi there, did you ever find a way to verify your structure? I'm attempting to do something vaguely similar.

**Comment by gnujosh** [comment]
Not sure if you are still working on this problem, but maybe you could save out the initial of each non-shared dense layer, and after training see write them out again to verify that both sets of weights are are changing.
