### ISSUE TITLE
Adding an LSTM between dense layers.

### ISSUE THREAD

**Issue by farzaa** [keras-team/keras#9314]
Hi everyone! I think what I'm trying to do is pretty simple, but I mat just be overthinking it. I keep getting the error:  `ValueError: Input 0 is incompatible with layer lstm_layer: expected ndim=3, found ndim=2`

Below is an example of where I'd like to place an LSTM. My output is always related to the previous output and learning that dependency is what I'm trying to do with this LSTM. This LSTM should output a single value. 

Any help on the code for actually putting an LSTM there or advice about the placement of the LSTM in my net for my task would be amazing :) 

```
model.add(Conv2D(24, (5,5), strides=(2,2), input_shape=(height, width, channels)))
model.add(Flatten())
model.add(Dropout(0.5))
model.add(Dense(1164))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(100))
model.add(Activation('relu'))
* add LSTM here*
model.add(Dense(1))
model.add(Activation('Linear'))
```

**Comment by brge17** [comment]
Use time distributed, see this issue: https://github.com/keras-team/keras/issues/4172
