### ISSUE TITLE
fit_generator throws error on validation data being float data type

### ISSUE THREAD

**Issue by adityak6798** [keras-team/keras#9326]
[(https://github.com/Ning-Ding/Implementation-CVPR2015-CNN-for-ReID)](url)

I'm trying to run CUHK03 Person Re-ID script by Ning-Ding ( Implementation of Ahmed et. al.'s paper using Keras) . Error text reads as follows:

TypeError                                 Traceback (most recent call last)
<ipython-input-24-6d5b2f1a499c> in <module>()
----> 1 main("E:\DL\cuhk-03.h5")

<ipython-input-23-a32d04236c16> in main(dataset_path)
     17     model = generate_model()
     18     model = compile_model(model)
---> 19     train(model, dataset_path)
     20 
     21 def train(model,

<ipython-input-23-a32d04236c16> in train(model, h5_path, weights_name, train_num, one_epoch, epoch_num, flag_random, random_pattern, flag_train, flag_val, which_val_data, nb_val_samples)
     39                 rand_x = np.random.rand()
     40                 flag_train = random_pattern(rand_x)
---> 41             model.fit_generator(Data_Generator.flow(f,flag = flag_train),one_epoch,epoch_num,validation_data=Data_Generator.flow(f,train_or_validation=which_val_data,flag=flag_val),nb_val_samples=nb_val_samples)
     42             Rank1s.append(round(cmc(model)[0],2))
     43             print (Rank1s)

~\Anaconda3\lib\site-packages\keras\legacy\interfaces.py in wrapper(*args, **kwargs)
     89                 warnings.warn('Update your `' + object_name +
     90                               '` call to the Keras 2 API: ' + signature, stacklevel=2)
---> 91             return func(*args, **kwargs)
     92         wrapper._original_function = func
     93         return wrapper

~\Anaconda3\lib\site-packages\keras\engine\training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   2023         epoch = initial_epoch
   2024 
-> 2025         do_validation = bool(validation_data)
   2026         self._make_train_function()
   2027         if do_validation:

TypeError: 'float' object cannot be interpreted as an integer

I am using Jupyter Notebook in Anaconda on Windows 10(x86). 
Keras version 2.1.3
Python version 3.6.3
Tensorflow backend (1.4.0)

**Comment by lemairecarl** [comment]
I hacked this line and now it works
https://github.com/keras-team/keras/blob/6b2a04f3af0eb53d4cd9abcbf60593c0e086c027/keras/engine/training.py#L2080

Seems like `bool()` on a Sequence is not a good idea

**Comment by Dref360** [comment]
Basically, calling bool on an object will call __nonzero__ or __len__ if any of them is defined. In our case, Sequence implements __len__ so it checks `if len(Sequence) == 0`. Your issue is that __len__ returns a float (which is an error) so when it tries to convert it in a bool, it fails.

Assert that __len__ returns an int.

**Comment by lemairecarl** [comment]
Great, thanks!

Please make sure the docs (https://keras.io/utils/#sequence) gets updated.

**Comment by adityak6798** [comment]
Thanks guys, helped a lot!

**Comment by kevgeo** [comment]
@adityak6798  @lemairecarl @Dref360 Hi guys, I tried editing the line given below as suggested by lemairecarl.
https://github.com/keras-team/keras/blob/6b2a04f3af0eb53d4cd9abcbf60593c0e086c027/keras/engine/training.py#L2080

I simply edited as  `do_validation = 1` but I still get the same error even after importing keras again.

**Comment by MarioG7z** [comment]
Hi!, how do you guys resolve this, I have noticied that len funcntion on my code returns a 'float', then I try to convert it to 'int', but now I got this:


Epoch 1/100

---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/dortizg/anaconda3/envs/DeepLTF/lib/python3.6/site-packages/PIL/Image.py", line 2584, in open
    fp.seek(0)
AttributeError: 'numpy.ndarray' object has no attribute 'seek'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dortizg/anaconda3/envs/DeepLTF/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/dortizg/anaconda3/envs/DeepLTF/lib/python3.6/site-packages/keras/utils/data_utils.py", line 401, in get_index
    return _SHARED_SEQUENCES[uid][i]
  File "<ipython-input-15-d8749e38f0d3>", line 17, in __getitem__
    for file_name in batch_x]), np.array(batch_y)
  File "<ipython-input-15-d8749e38f0d3>", line 17, in <listcomp>
    for file_name in batch_x]), np.array(batch_y)
  File "/home/dortizg/anaconda3/envs/DeepLTF/lib/python3.6/site-packages/skimage/io/_io.py", line 62, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "/home/dortizg/anaconda3/envs/DeepLTF/lib/python3.6/site-packages/skimage/io/manage_plugins.py", line 214, in call_plugin
    return func(*args, **kwargs)
  File "/home/dortizg/anaconda3/envs/DeepLTF/lib/python3.6/site-packages/skimage/io/_plugins/pil_plugin.py", line 39, in imread
    im = Image.open(fname)
  File "/home/dortizg/anaconda3/envs/DeepLTF/lib/python3.6/site-packages/PIL/Image.py", line 2586, in open
    fp = io.BytesIO(fp.read())
AttributeError: 'numpy.ndarray' object has no attribute 'read'
"""

The above exception was the direct cause of the following exception:

AttributeError                            Traceback (most recent call last)
~/anaconda3/envs/DeepLTF/lib/python3.6/site-packages/keras/utils/data_utils.py in get(self)
    577             while self.is_running():
--> 578                 inputs = self.queue.get(block=True).get()
    579                 self.queue.task_done()

~/anaconda3/envs/DeepLTF/lib/python3.6/multiprocessing/pool.py in get(self, timeout)
    643         else:
--> 644             raise self._value
    645 

AttributeError: 'numpy.ndarray' object has no attribute 'read'

The above exception was the direct cause of the following exception:

StopIteration                             Traceback (most recent call last)
<ipython-input-21-5cf8d2ede097> in <module>
      7                               workers = 16,
      8                               max_queue_size = 32,
----> 9                               callbacks = [checkpoint])

~/anaconda3/envs/DeepLTF/lib/python3.6/site-packages/keras/legacy/interfaces.py in wrapper(*args, **kwargs)
     89                 warnings.warn('Update your `' + object_name +
     90                               '` call to the Keras 2 API: ' + signature, stacklevel=2)
---> 91             return func(*args, **kwargs)
     92         wrapper._original_function = func
     93         return wrapper

~/anaconda3/envs/DeepLTF/lib/python3.6/site-packages/keras/engine/training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   1424             use_multiprocessing=use_multiprocessing,
   1425             shuffle=shuffle,
-> 1426             initial_epoch=initial_epoch)
   1427 
   1428     @interfaces.legacy_generator_methods_support

~/anaconda3/envs/DeepLTF/lib/python3.6/site-packages/keras/engine/training_generator.py in fit_generator(model, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
    153             batch_index = 0
    154             while steps_done < steps_per_epoch:
--> 155                 generator_output = next(output_generator)
    156 
    157                 if not hasattr(generator_output, '__len__'):

~/anaconda3/envs/DeepLTF/lib/python3.6/site-packages/keras/utils/data_utils.py in get(self)
    582         except Exception as e:
    583             self.stop()
--> 584             six.raise_from(StopIteration(e), e)
    585 
    586     def _send_sequence(self):

~/anaconda3/envs/DeepLTF/lib/python3.6/site-packages/six.py in raise_from(value, from_value)

StopIteration: 'numpy.ndarray' object has no attribute 'read'

**Comment by CubicrootXYZ** [comment]
I am experiencing this issue with a CNN in Keras. It only appears with one of my 2 datasets and only with cross validation (sklearn KFold).

The error gets thrown here:
```
history = model.fit(x_tr, y_tr,
                        batch_size=batch_size,
                        epochs=epochs,
                        verbose=1,
                        validation_data=(x_te, y_te))
```

I do not see any way to fix that in this thread here. 

Keras 1.0.8 with TensorFlow 2.1.0 and tensorflow-gpu package.

**Comment by CubicrootXYZ** [comment]
> Keras 1.0.8 with TensorFlow 2.1.0 and tensorflow-gpu package.

Sorry got that wrong, it is keras version 2.3.1

**Comment by CubicrootXYZ** [comment]
Solved it. Epochs was an float due to some conversions.
