### ISSUE TITLE
Batch processing and ImageDataGenerator not parallelized?

### ISSUE THREAD

**Issue by FiReTiTi** [keras-team/keras#9332]
Hi,

the way I understood it, I thought that the ImageDataGenerator generates/transforms a new batch while the GPU is processing the current batch.
I placed some `print` to confirm that, and I found out that everything is sequential:

    idg = IDG_test.ImageDataGenerator()
    gen = idg.flow_from_directory("./DatasetTest/1x52x52/", target_size=(50, 50), batch_size=4, color_mode='grayscale', class_mode='binary')

    for i in range(5):
    	print("Ask for data")
    	sys.stdout.flush()
    	X, Y = gen.next()
    	print("Data received. Let's sleep.")
    	sys.stdout.flush()
    	time.sleep(3)

And here are the outputs:

    Ask for data
    Before lock
    Lock passed
    Transforming data
    Data Transformed
    Data received. Let's sleep.
    Ask for data
    Before lock
    Lock passed
    Transforming data
    Data Transformed
    Data received. Let's sleep.

If things were parallelized, this sequence `Data received. Let's sleep... Ask for data` would not have happened. In a parallelized mode, I should have got a `Transforming Data` in the middle of the previous outputs.

Am I right or is there something that I don't understand?

If I am right, how can I modify the ImageDataGenerator to generate and transform a new batch while Keras is working on the previous batch?

Regards,

**Comment by Dref360** [comment]
It's paralyzed in fit_generator. ImageDataGenerator just creates the data.

**Comment by FiReTiTi** [comment]
Ok, thanks!

Is there a way to check that it's correctly parallelized? Because I need to modify the ImageDataGenerator for my own purposes, and I would like to make sure that I don't mess up with the parallelism.

**Comment by Dref360** [comment]
You can use your own `keras.utils.OrderedEnqueuer`
```python
enqueuer = OrderedEnqueuer(your_data,
                                                           use_multiprocessing=use_multiprocessing)
enqueuer.start(workers=workers, max_queue_size=max_queue_size)
gen = enqueuer.get()
for k in gen:
    # Your data is here
    ...
```

**Comment by FiReTiTi** [comment]
@Dref360: Thank you for your answer.
I have to test a data generator and I must make sure it's correctly parallelized.
I don't understand the variable `your_data` in the code your shared. My understanding is the ImageDataGenerator should handle the data. Am I wrong?
What are the `workers` in your code, how can I create one?
