### ISSUE TITLE
How to train multiple Keras models at the same time?

### ISSUE THREAD

**Issue by sheiy** [keras-team/keras#9333]
thanks, The backend is tensorflow

**Comment by brainnoise** [comment]
Are you looking to do something like #3287 ?

**Comment by ivan-marroquin** [comment]
I have the same question - as the one posted in #3287

If I use Theano as backend to Keras, I would use set the "base_compiledir" configuration parameter to use a different folder for each of the scripts that I want to run. With this option, I can simultaneously run three scripts to train three different MLPs.

Do you have a suggestion?

Many thanks,
Ivan

**Comment by ivan-marroquin** [comment]
I meant when tensorflow is used as backend to Keras
