### ISSUE TITLE
How to fuse outputs of the same network when two different input images are given

### ISSUE THREAD

**Issue by ruqayya** [keras-team/keras#9341]
I want to implement a self-supervised network as in this [paper ](https://arxiv.org/abs/1505.05192)using Keras (Tensorflow). I want to concatenate the outputs of the same network when two different images are given as an input to the network and then give that concatenated tensor to a fully connected layer. Could someone please guide me.

`def CaffeNet(inputs):          
    x = Conv2D(96, (11, 11), strides=(4, 4), activation='relu', name='conv1')(inputs)
    x = MaxPooling2D((3, 3), strides=(2, 2), name='pool1')(x)
    x = Flatten(name='flatten')(x)
    x = Dense(4096, activation='relu', name='fc6')(x)
    return x

def SS(caffenet_inputs1,caffenet_inputs2):
    caffenet_stack_1 = CaffeNet(caffenet_inputs1)
    caffenet_stack_2 = CaffeNet(caffenet_inputs2)
    merged_caffenet_stack = concatenate([caffenet_stack_1, caffenet_stack_2])
    fc7 = Dense(4096, activation='relu')(merged_caffenet_stack)
    return fc7

caffenet_inputs_1 = Input(shape=(patchSize, patchSize, 3))
caffenet_inputs_2 = Input(shape=(patchSize, patchSize, 3))
fuse_output = SS(caffenet_inputs_1,caffenet_inputs_2)
final_output = Model([caffenet_inputs_1,caffenet_inputs_2], fuse_output, name='caffenet')`

**Comment by brainnoise** [comment]
I am not very sure I understand the question. If you mean sharing multiple layers for multiple inputs, you can do that by creating the layers first and then calling them with the inputs. 

```
dense1 = Dense(32)
dense2 = Dense(32)
output1 = dense2(dense1(input1))
output2 = dense2(dense1(input2))
```
Please see [info](https://keras.io/getting-started/functional-api-guide/#shared-layers) on shared layers.
