### ISSUE TITLE
Error: Conv3DBackpropInput: input and out_backprop must have the same batch size

### ISSUE THREAD

**Issue by FiReTiTi** [keras-team/keras#9348]
Hi,

I am implementing a Deconvolution (upsampling+convolution) class to Keras 2. Here is the code:

    class Deconv3D(Layer):
	def __init__(self, nb_filter, kernel_dims, output_shape, subsample, **kwargs):
		self.nb_filter = nb_filter
		self.kernel_dims = kernel_dims
		self.strides = (1,) + subsample + (1,)
		self.output_shape_ = output_shape
		assert K.backend() == 'tensorflow'
		super(Deconv3D, self).__init__(**kwargs)
	
	def build(self, input_shape):
		assert len(input_shape) == 5
		self.input_shape_ = input_shape
		W_shape = self.kernel_dims + (self.nb_filter, input_shape[4], )
		self.W = self.add_weight(shape=W_shape, initializer='glorot_uniform', name='{}_W'.format(self.name), trainable=True)
		self.b = self.add_weight(shape=(1,1,1,self.nb_filter,), initializer='zero', name='{}_b'.format(self.name), trainable=True)
		#self.built = True
		super(Deconv3D, self).build(input_shape)
	
	def compute_output_shape(self, input_shape):
		return (input_shape[0], ) + self.output_shape_[1:]
	
	def call(self, x, mask=None):
		return tf.nn.conv3d_transpose(x, self.W, output_shape=self.output_shape_, strides=self.strides, padding='SAME', name=self.name) + self.b
	
I can create my model and compile it, but during the first epoch I get this error:

    Epoch 1/1
    Using TensorFlow backend.
    Traceback (most recent call last):
      File "/eppec/storage/sw/conda/envs/ThibaultPython35/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
      File "/eppec/storage/sw/conda/envs/ThibaultPython35/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
      File "/eppec/storage/sw/conda/envs/ThibaultPython35/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
    tensorflow.python.framework.errors_impl.InvalidArgumentError: Conv3DBackpropInput: input and out_backprop must have the same batch size
         [[Node: deconv3d_1/deconv3d_1 = Conv3DBackpropInputV2[T=DT_FLOAT, data_format="NDHWC", padding="SAME", strides=[1, 2, 2, 2, 1], _device="/job
    :localhost/replica:0/task:0/device:GPU:0"](deconv3d_1/deconv3d_1/output_shape, deconv3d_1/deconv3d_1_W/read, p_re_lu_11/add)]]
         [[Node: loss/mul/_515 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_5083_loss/mul", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

I read online that this error used to happen Keras 1 and that it has been fixed since, but I don't understand why I get it here.

Any idea?
Thanks for your help.

**Comment by leekyungmoon** [comment]
@FiReTiTi , Is there any progress?

**Comment by FiReTiTi** [comment]
No, I gave up and switched  to PyTorch.
