### ISSUE TITLE
Cell States of a LSTM

### ISSUE THREAD

**Issue by LuckyOwl95** [keras-team/keras#9351]
Hi there,

I have a problem with LSTMs. I need to get the cell states out of a LSTM for each time step. Unfortunaly it is only possible to get the output for each time step with return_sequences=True. return_state=True only gives me the cell state for the last time step...

Is there any hack/modification to get the cell states for each time step?

Greetings

**Comment by farizrahman4u** [comment]
During prediction you can get the states for each time step by unrolling the RNN - basically you do a for loop over the LSTMCell instead using TF/Theano scan ops which are called by K.rnn.

```python
maxlen = 10
input_dim = 10
units = 55

inputs = Input((maxlen, input_dim))

cell = LSTMCell(units)

states = [] # list of (h, c) tuples
outputs = []

def get_zeros(x, units):
    z = K.zeros_like(x[:,0, :1])
    z = K.tile(z, [1, units])
    return z

zeros_layer = Lambda(get_zeros, arguments={'units': units}, output_shape=(None, units))
h = zeros_layer(inputs)
c = zeros_layer(inputs)

for t in range(maxlen):
    input_t = inputs[:, t, :]
    states.append((h, c))
    output_t, (h, c) = cell(input_t, (h, c))
    outputs.append(output_t)
```

Caveat - Ignores masking.

**Comment by brain1995** [comment]
Thanks for your answer, I think this will help me. Did you test your code? Unfortunately, it doesn't work: `output_t, (h, c) = cell(input_t, (h, c)) 
TypeError: __call__() takes 2 positional arguments but 3 were given`.

Additionally, how can I add the weights of a trained model with this approach? I have a Seq2Seq model, but I'm only interested in the cell states of the encoder, which means that I initialized my script with: 
`loaded_model = load_model('.../model_epoch_50.h5')`
`encoder = Sequential()`
`encoder.add(LSTM(128, weights=loaded_model.layers[0].get_weights(), input_shape=(x_train.shape[1], x_train.shape[2])))`

**Comment by farizrahman4u** [comment]
updated

**Comment by brain1995** [comment]
Now there's 
`
  File "...\engine\topology.py", line 717, in _add_inbound_node
    output_tensors[i]._keras_shape = output_shapes[i]`
`AttributeError: 'tuple' object has no attribute '_keras_shape'`

**Comment by xiping-fu** [comment]
After each timestamp, here is an exemplary code for accessing all of the states:
import keras.backend as K
statesAll=[]
for layer in model.layers:
    if getattr(layer,'stateful',False):
        if hasattr(layer,'states'):
            for state in layer.states:
               statesAll.append(K.get_value(state))

**Comment by farizrahman4u** [comment]
Hmm.. seems Cells cant be called as such, I have updated to to use LSTM layer instead. Can you try now?

**Comment by brain1995** [comment]
Thank you so much for your patience and support! It doesn't return any error, so I will try to modify it for my problem. Thank you! :)

**Comment by Imorton-zd** [comment]
@brain1995 @farizrahman4u Hi, I have another relevant question that how can I optimize on mini-batch when computing on each time-step. Specifically, we compute the output of every LSTMCell with each word of an sentence, and I want to add all the losses of a batch to optimize. Therefore, where can I add the batch parameter in above example code. Thanks!

**Comment by PedroFerreiradaCosta** [comment]
@farizrahman4u  is  _state_ supposed to be a list? Also, where do you provide the desired training/testing set to the model? Thanks for the help!

**Comment by LittleBella** [comment]
What does the function "Lambda" mean above ?

**Comment by LittleBella** [comment]
I knew it, thanks .

**Comment by Nicolabo** [comment]
Could you help me translate your chunk of code into tensorflow? I was trying several options but still got an error:

```
import keras
from keras.layers import Input, LSTM, Lambda
import tensorflow as tf

inputs = Input((maxlen, input_dim), dtype = tf.float32)

rnn = LSTM(units, return_state=True)

def get_indexer(t):
    return Lambda(lambda x, t: x[:, t, :], arguments={'t':t}, output_shape=lambda s: (s[0], s[2]))

def expand(x):
    return keras.backend.expand_dims(x, 1)

expand_layer = Lambda(expand, output_shape=lambda s: (s[0], 1, s[1]))
state = tf.Variable(tf.zeros([10]))
states = tf.TensorArray(dtype=tf.float32, size=0, dynamic_size=True, name='states')
iters = tf.constant(10, name='iters')

def cond(i, iters, states):
    return tf.less(i, iters)

def body(i, iters, states):
    input_t = get_indexer(i)(inputs)  # basically input_t = inputs[:, t, :]
    input_t = expand_layer(input_t)
    output_t, h, c = rnn(input_t, initial_state=state)
    temp_state = h, c
    assign_op = tf.assign(state, temp_state)
    states = states.write(step, state)
    return states

states = tf.while_loop(cond, body, [0, iters, states])
```

```
ValueError: Initializer for variable while_18/lstm_6/kernel/ is from inside a control-flow construct, such as a loop or conditional. When creating a variable inside a loop or conditional, use a lambda as the initializer.
```

**Comment by alexmaehon** [comment]
> I knew it, thanks .

what is it ???

**Comment by alexmaehon** [comment]
I have exactly the same question !!!
And I don’t know how to use K.rnn to do this? Can you give me a example?

**Comment by alexmaehon** [comment]
Please tell me how to use K.rnn to get those states from Lambda layer

**Comment by alexmaehon** [comment]
a burning question for a newbie

**Comment by alexmaehon** [comment]
or how to input actual values into this Lambda layer

**Comment by alexmaehon** [comment]
Is this result I get from model.predict correct???  :

time_steps = 11
input_dim = 17
units = 128

inputs = Input((time_steps, input_dim))

rnn = GRU(units, return_state=True)

states = [] # list of (h, c) tuples
outputs = []

state = None
def get_indexer(t):
    return Lambda(lambda x, t: x[:, t, :], 
                  arguments={'t':t}, 
                  output_shape=lambda s: (s[0], s[2]))

def expand(x):
    return K.expand_dims(x, 1)

expand_layer = Lambda(expand, output_shape=lambda s: (s[0], 1, s[1]))
for t in range(time_steps):
    input_t = get_indexer(t)(inputs)  # basically input_t = inputs[:, t, :]
    input_t = expand_layer(input_t)
    output_t, h = rnn(input_t, initial_state=state)
    state = h
    states.append(state)
    outputs.append(output_t)

modelX =  Model(inputs,states)
every_time_step_states = modelX.predict(My_real_data_input)

**Comment by alexmaehon** [comment]
> During prediction you can get the states for each time step by unrolling the RNN - basically you do a for loop over the LSTMCell instead using TF/Theano scan ops which are called by K.rnn.
> 
> ```python
> maxlen = 10
> input_dim = 10
> units = 5
> 
> inputs = Input((maxlen, input_dim))
> 
> rnn = LSTM(units, return_state=True)
> 
> states = [] # list of (h, c) tuples
> outputs = []
> 
> state = None
> def get_indexer(t):
>     return Lambda(lambda x, t: x[:, t, :], arguments={'t':t}, output_shape=lambda s: (s[0], s[2]))
> 
> def expand(x):
>     return K.expand_dims(x, 1)
> 
> expand_layer = Lambda(expand, output_shape=lambda s: (s[0], 1, s[1]))
> for t in range(maxlen):
>     input_t = get_indexer(t)(inputs)  # basically input_t = inputs[:, t, :]
>     input_t = expand_layer(input_t)
>     output_t, h, c = rnn(input_t, initial_state=state)
>     state = h, c
>     states.append(state)
>     outputs.append(output_t)
> ```
> 
> Caveat - Ignores masking.

Is the below results I get from model.predict is the state of each time steps ??? 

time_steps = 11
input_dim = 17
units = 128

inputs = Input((time_steps, input_dim))

rnn = GRU(units, return_state=True)

states = [] # list of (h, c) tuples
outputs = []

state = None
def get_indexer(t):
    return Lambda(lambda x, t: x[:, t, :], 
                  arguments={'t':t}, 
                  output_shape=lambda s: (s[0], s[2]))

def expand(x):
    return K.expand_dims(x, 1)

expand_layer = Lambda(expand, output_shape=lambda s: (s[0], 1, s[1]))
for t in range(time_steps):
    input_t = get_indexer(t)(inputs)  # basically input_t = inputs[:, t, :]
    input_t = expand_layer(input_t)
    output_t, h = rnn(input_t, initial_state=state)
    state = h
    states.append(state)
    outputs.append(output_t)

modelX =  Model(inputs,states)
every_time_step_states = modelX.predict(My_real_data_input)

**Comment by alexmaehon** [comment]
> > During prediction you can get the states for each time step by unrolling the RNN - basically you do a for loop over the LSTMCell instead using TF/Theano scan ops which are called by K.rnn.
> > ```python
> > maxlen = 10
> > input_dim = 10
> > units = 5
> > 
> > inputs = Input((maxlen, input_dim))
> > 
> > rnn = LSTM(units, return_state=True)
> > 
> > states = [] # list of (h, c) tuples
> > outputs = []
> > 
> > state = None
> > def get_indexer(t):
> >     return Lambda(lambda x, t: x[:, t, :], arguments={'t':t}, output_shape=lambda s: (s[0], s[2]))
> > 
> > def expand(x):
> >     return K.expand_dims(x, 1)
> > 
> > expand_layer = Lambda(expand, output_shape=lambda s: (s[0], 1, s[1]))
> > for t in range(maxlen):
> >     input_t = get_indexer(t)(inputs)  # basically input_t = inputs[:, t, :]
> >     input_t = expand_layer(input_t)
> >     output_t, h, c = rnn(input_t, initial_state=state)
> >     state = h, c
> >     states.append(state)
> >     outputs.append(output_t)
> > ```
> > 
> > 
> > Caveat - Ignores masking.
> 
> Is the below results I get from model.predict is the state of each time steps ???
> 
> time_steps = 11
> input_dim = 17
> units = 128
> 
> inputs = Input((time_steps, input_dim))
> 
> rnn = GRU(units, return_state=True)
> 
> states = [] # list of (h, c) tuples
> outputs = []
> 
> state = None
> def get_indexer(t):
> return Lambda(lambda x, t: x[:, t, :],
> arguments={'t':t},
> output_shape=lambda s: (s[0], s[2]))
> 
> def expand(x):
> return K.expand_dims(x, 1)
> 
> expand_layer = Lambda(expand, output_shape=lambda s: (s[0], 1, s[1]))
> for t in range(time_steps):
> input_t = get_indexer(t)(inputs) # basically input_t = inputs[:, t, :]
> input_t = expand_layer(input_t)
> output_t, h = rnn(input_t, initial_state=state)
> state = h
> states.append(state)
> outputs.append(output_t)
> 
> modelX = Model(inputs,states)
> every_time_step_states = modelX.predict(My_real_data_input)

but each prediction gets different results, it must be wrong?

**Comment by alexmaehon** [comment]
but each prediction gets different results, it must be wrong???

**Comment by tinyxuyan** [comment]
@alexmaehon  Have you solved the issues? I am trying to obtain the cell state of LSTM of the already trained model, too.
