### ISSUE TITLE
preprocess images with pretrained model

### ISSUE THREAD

**Issue by chaohuang** [keras-team/keras#9354]
I'm trying to fine-tune the VGG16 model in Keras for a medical imaging application.

Because medical images are gray images, I copy each gray image into RGB channels (3 channels have the same gray image), such that they can be used as the inputs to the VGG model. Let's call them "RGB" images (with quotation marks).

But, if I use the `preprocess_input` function from `keras.applications.vgg16` to preprocess the "RGB" images, then because the the default mode is 'caffe' in `preprocess_input`, it will subtract mean RGB values [103.939, 116.779, 123.68], which were calculated from the training dataset in Imagenet, from each "RGB" image I created.

However, in my "RGB" images, all 3 RGB channels should have the same mean value, and more importantly because mine are medical images, the mean value should be different from the ones from Imagenet.

So in this case, how should I preprocess my "RGB" images to fine-tune the VGG16 model with pretrained 'Imagenet 'weights?

Also, just to make sure, the pretrained 'Imagenet' weights in Keras were trained with data that were preprocessed in 'caffe' mode, right?

**Comment by grig-guz** [comment]
For preprocessing:
1. Split your dataset into training, validation and test parts
2. Assuming you want to just zero-center it, find the mean, m_tr, of your training data
3. Subtract this m_tr from your training, validation and testing datasets.
You only use mean of your training dataset to avoid information leaks from validation and test datasets.

**Comment by Ambssharma** [comment]
> For preprocessing:
> 
> 1. Split your dataset into training, validation and test parts
> 2. Assuming you want to just zero-center it, find the mean, m_tr, of your training data
> 3. Subtract this m_tr from your training, validation and testing datasets.
>    You only use mean of your training dataset to avoid information leaks from validation and test datasets.


Dear grig-guz,
I am not clear about why are we subtracting m_tr(mean of training images) from validation and test datasets. Shouldn't we separately find the mean of validation and test datasets??
