### ISSUE TITLE
[API DESIGN REVIEW] TimeSeriesSequence for timeseries data generation

### ISSUE THREAD

**Issue by srjoglekar246** [keras-team/keras#9364]
Doc link: https://docs.google.com/document/d/1GcMWE4sEf205Fbklt3w1l3HL1URSYc7lJIZ3AGh3EA0

> Inspired by fchollet@’s proposal on the Projects page, this doc proposes implementation of TimeSeriesSequence as a subclass of keras.utils.Sequence. Given a time-series prediction problem (such as this example), TimeSeriesSequence would take in the temporal dataset and various parameters such as step-size, prediction-delay, lookback etc. to produce data in accordance with Sequence’s interface.

**Comment by Dref360** [comment]
Would this allow "classification" tasks?
Otherwise, seems great!

**Comment by srjoglekar246** [comment]
I guess that would be possible by providing targets as a separate input to the initializer, instead of the current proposal of using a subset of the training-data's dimensions. Will work that in :-)

**Comment by sipemu** [comment]
@srjoglekar246 the link to the doc file is dead.

**Comment by srjoglekar246** [comment]
@sipemu Oops. I do see someone else on the doc though, and the Sharing settings seem fine :-/. Is there some Google Docs magic I am missing? Currently updating it based on fchollet@'s comments though...
