### ISSUE TITLE
'Resource exhausted' when using flow_from_directory / Automatic Resizing of images

### ISSUE THREAD

**Issue by Nimi42** [keras-team/keras#9368]
Hey there,

I'm trying to use the preprocessing to do some data augmentation. 
Atm. I'm working with Cifar and I use **the flow method, which works fine!!!**

I thought that the flow_from_directory method would be more convenient, since
Keras would take care of creating the batches and loading the data into memory.
For some reason though the images get rescaled to 256 by 256.

The images in Cifar are usually 32 by 32. Do I have to specifiy a target size? I'm baffled
by this behaviour.

**Comment by Dref360** [comment]
As you can see in the doc : 
https://keras.io/preprocessing/image/

`flow_from_directory` takes an argument `target_size`
