### ISSUE TITLE
Deconvolution with Conv?Dtranspose

### ISSUE THREAD

**Issue by FiReTiTi** [keras-team/keras#9374]
Hi,

I wanted to use the layer `Conv2Dtranspose` and `Conv3Dtranspose` in order to do deconvolution.
I can get my model built and compiled, but the upsampling part does not seem to work, even when I modify the parameter `dilate_rate`.

Any idea how to do the upsampling part using ConvXDtranspose?
Or am I misunderstanding how this layer works?

**Comment by carlthome** [comment]
When you say deconvolution, do you mean [this](https://en.wikipedia.org/wiki/Deconvolution) or just getting a bigger output by doing transposed convolution?

**Comment by rex-yue-wu** [comment]
The parameter to control the upsampling rate in `Conv2DTranspose` is not `dilate_rate` but `strides`.

**Comment by FiReTiTi** [comment]
Does `UpSample2D + Conv2D` produce exactly the same effect/result as `Conv2DTranspose`?

**Comment by rex-yue-wu** [comment]
Conceptually yes, but in practice not. `Upsample2D` enlarges an input tensor by repeating its rows and columns, while `Conv2DTranspose` not.

**Comment by FiReTiTi** [comment]
Thanks!

Last question to make sure I understand how it works: If `strides` is the parameter that controls the upsampling, how do we control the strides? In other words, how to I do `Conv2D(strides=(1,1))+UpSampling2D(2)` with `Conv2DTranspose`?

**Comment by carlthome** [comment]
You can't. For a transposed convolution to result in a larger output you have to have holes (similar to how strided convolutions are an alternative to pooling). This is one of the reasons it doesn't make sense to call them deconvolution layers.

**Comment by carlthome** [comment]
https://datascience.stackexchange.com/a/12110

**Comment by FiReTiTi** [comment]
thanks a lot.
