### ISSUE TITLE
LSTM version

### ISSUE THREAD

**Issue by natasasdj** [keras-team/keras#9387]
Which exactly version of LSTM is implemented in Keras?

**Comment by 0bserver07** [comment]
```
Docstring:
Long-Short Term Memory unit - Hochreiter 1997.

For a step-by-step description of the algorithm, see
[this tutorial](http://deeplearning.net/tutorial/lstm.html).
```
try using `ipython` and then run this command to get more info:

```
from keras.layers import LSTM

LSTM?
```

**Comment by natasasdj** [comment]
Docstring:
Long-Short Term Memory unit - Hochreiter 1997

This is exactly why I am confused. The LSTM paper from 1997 is difficult to read, but it seems to me that this version of LSTM does not contain the forget gate. Also the paper "LSTM: A Search Space Odyssey" - Greff 2017 also states that the LSTM version from 1997 has only input and output gates but not a forget gate.
Looking a little bit into the Keras code of LSTMCell as well as the arguments into the LSTM layer (unit_forget_bias), it seems to me that the LSTM version implemented into Keras has a forget gate. Hence, this can't be the LSTM version from the 1997 paper referenced in the documentation.
According to what I have read, the advancement of the original LSTM from 1997 in the addition of the forget gate makes a difference in the learning capabilities of the LSTM.
