### ISSUE TITLE
TF-backend is 5x slower than theano-backend/pytorch for MLP prediction

### ISSUE THREAD

**Issue by JiaweiZhuang** [keras-team/keras#9388]
For a simple 2-hidden-layer MLP, Keras with TF backend is 5x slower than theano backend, and 6x slower than pytorch using the same architecture. This is only for **prediction**, not training, and it is only on **CPU**.

Please see [this gist](https://gist.github.com/JiaweiZhuang/c3350f7a89db3d5a98c6a2c0228ceea9) for timing. This should be mainly a TensorFlow problem, since the raw TF implementation is still 3~4x slower than theano/PyTorch.

For reproducibility, the test was done on EC2 c5.large, deep learning AMI (ami-e07e779a). Got somewhat similar results on my own Mac, with all packages installed by conda.

My questions are:
1. Is this performance difference expected? Or there can be something wrong with TensorFlow installation?
2. Any way to speed-up the TF backend?

Not sure if this is the correct place to ask performance issue. Please feel free to close. Thanks.

**Comment by fchollet** [comment]
Yes, your TensorFlow installation appears to be broken. I suggest you raise the issue on the TensorFlow repo.

If you have a performance problem for TensorFlow specifically, you can use a different backend, such as Theano or CNTK.
