### ISSUE TITLE
Replace PIL with pillow

### ISSUE THREAD

**Issue by morenoh149** [keras-team/keras#9397]
https://github.com/keras-team/keras/blob/master/keras/preprocessing/image.py#L25

PIL is not maintained. Is it okay to replace with `pillow` which is maintained?

On osx for example, the PIL installation requires python 2.5 to be installed on the system, http://effbot.org/downloads#pil , I _really_ don't want to do this.

**Comment by morenoh149** [comment]
Well I was finally able to get PIL working my doing sudo install and installing cImage (https://wp.stolaf.edu/it/installing-pil-pillow-cimage-on-windows-and-mac/) but moving to a supporting lib is still probably a good idea.

**Comment by bzamecnik** [comment]
Actually `Pillow` also provides the `PIL` module. But there's no dependency on `PIL`/`Pillow` specified in `setup.py`.

**Comment by morenoh149** [comment]
hmm, ok.

**Comment by tengerdata** [comment]
In my conda env I am using python 3.6 which is conflicting with PIL. Thus, I installed Pillow instead of PIL which should work, but I am still getting this error:
`ImportError: Could not import PIL.Image. The use of `array_to_img` requires PIL.`

**Comment by morenoh149** [comment]
do you mean in your kaggle kernel, this repo only concerns the kaggle kernel environment. Based off @bzamecnik PIL should be picked up transparently in 2.7 and 3.6 and use the correct library under the hood.
