### ISSUE TITLE
External  Data generator for Audio files

### ISSUE THREAD

**Issue by Jamesswiz** [keras-team/keras#9399]
I have a very large audio dataset with 300hr of data.
There is a 'Data' folder with multiple sub-folders, and a text file specifying train-test-validation protocol.

I need help with data_generator function so that I can read a batch of wave files process them and pass them to keras .fit() function for model training.

I am new to python, so any help will be appreciated.

Thanks

**Comment by Dref360** [comment]
Hi!
This question seems best suited for StackOverflow. Could you post your issue there? Also, remember to close your issue if you do so!
Thanks!
