### ISSUE TITLE
Use oov_token for low frequency tokens in Tokenizer

### ISSUE THREAD

**Issue by tswr** [keras-team/keras#9409]
If both num_words and oov_token are specified in Tokenizer init, then low frequency tokens are going to be skipped. Isn't it better to replace them with oov_token instead?

https://github.com/keras-team/keras/blob/c476792e366626bec3b5a44b642c315239311516/keras/preprocessing/text.py#L275

**Comment by vijay39312** [comment]
Was thinking exactly the same. There should at least be an argument for enabling this in texts_to_sequences
