### ISSUE TITLE
layers.add vs concatenate

### ISSUE THREAD

**Issue by sanjay51** [keras-team/keras#9413]
Related to this line:
https://github.com/keras-team/keras/blob/d3301fae7ef22801780d0f79a7a0a32c34507a09/examples/babi_rnn.py#L208

Seems like we are adding the [encoded_sentence, encoded_question] layers here, but looking at the keras documentation for merge, https://keras.io/layers/merge/ , should concatenate not be the right operation?

Thanks.

**Comment by rex-yue-wu** [comment]
Do you mean it is better to concatenate these two features instead of adding them up? If so, why not train a new model using concatenation and compare the performance difference.
