### ISSUE TITLE
Windows: Keras/CNTK GPU detection not working

### ISSUE THREAD

**Issue by apiszcz** [keras-team/keras#9420]
I am interested in changing from the TensorFlow backend to CNTK due to build challenges with the latest TensorFlow and CUDA 9.1/CUDNN 7.0.5. Is there a parameter not set properly in my command line python environment? The very last line of the status message states GPU has been selected, then I have a CALL STACK. Perhaps I have an environment or path issue.
Thank you for adding CNTK as a backend option to KERAS.

The environment variable is set
KERAS_BACKEND=cntk

Using CNTK API from Jupyter shows:
```
from cntk.device import try_set_default_device, gpu
import cntk as C
print(C.device.all_devices())
print(C.device.try_set_default_device(cntk.device.gpu(0)))
print(C.device.use_default_device())

(GPU[0] Quadro K5100M, CPU)
True
GPU[0] Quadro K5100M
```

However when I add the following lines in my Keras python program i get two messages
1. Selected CPU as the process wide default device.
2. The 'frozen' message.

import cntk as C
if C.device.try_set_default_device(C.device.gpu(0)):
    print("GPU")

==
2018-02-19T07:54:53.607208> lib\python\python -Wignore lib/test/keras/mmi.py  --image_folder=C:\g\usera\jobid\extract\file1

Using CNTK backend
Selected CPU as the process wide default device.
CPU

This message is caused the try_set... attempt.
Traceback (most recent call last):
  File "lib/test/keras/mmi.py", line 20, in <module>
    if C.device.try_set_default_device(C.device.gpu(0)):
  File "C:\g\test\lib\cntk\device.py", line 149, in try_set_default_device
    acquire_device_lock)
RuntimeError: Process wide default device cannot be changed since it has been frozen by being implicitly used as the default device in a CNTK API call; Current default = CPU, **New default = GPU[0] Quadro K5100M**.

[CALL STACK]
    > std::enable_shared_from_this<Microsoft::MSR::CNTK::MatrixBase>::  operator=
    - CNTK::DeviceDescriptor::  TrySetDefaultDevice
    - PyInit__cntk_py (x2)
    - PyCFunction_Call
    - PyEval_GetFuncDesc
    - PyEval_EvalFrameEx (x2)
    - PyEval_GetFuncDesc (x2)
    - PyEval_EvalFrameEx (x2)
    - PyRun_FileExFlags (x2)
    - PyRun_SimpleFileExFlags
    - PyRun_AnyFileExFlags

**Comment by apiszcz** [comment]
Modifying keras\backend\cntk_backend.py from the initial device setup to instead try the GPU appears to resolve the issue:

```
if C.device.try_set_default_device(C.device.gpu(0)):
    print("GPU")
else:
    warnings.warn(
        'CNTK backend warning: GPU is not detected. '
        'CNTK\'s CPU version is not fully optimized,'
        'please run with GPU to get better performance.')
```

```
-> import keras
Using CNTK backend
GPU
Selected GPU[0] Quadro K5100M as the process wide default device.
```

**Comment by Dref360** [comment]
You could submit a PR
