### ISSUE TITLE
i don't know what I am doing wrong ;(

### ISSUE THREAD

**Issue by niklaseeeee** [keras-team/keras#9448]
Here is my Code:

```


import pandas as pd
import numpy as np
from keras.layers.core import Dense, Activation, Dropout
from keras.layers.recurrent import LSTM
from keras.models import Sequential
import lstm, time #helper libraries

def main():

    np.random.seed(0)

    print("Loading data...")
    # Load the data from the CSV files
    training_data = pd.read_csv('numerai_training_data.csv', header=0)
    prediction_data = pd.read_csv('numerai_tournament_data.csv', header=0)


    features = [f for f in list(training_data) if "feature" in f]
    X = training_data[features]
    Y = training_data["target"]
    x_prediction = prediction_data[features]
    ids = prediction_data["id"]


    model = Sequential()
    
    model.add(LSTM(
            input_dim=len(X),
            output_dim=50,
            return_sequences=True))
    model.add(Dropout(0.2))

    model.add(LSTM(
            100,
            return_sequences=False))
    model.add(Dropout(0.2))

    model.add(Dense(
            output_dim=1))
    model.add(Activation('linear'))
    
    print("Compiling ....")
    model.compile(loss='mse', optimizer='rmsprop')

    print("Training...")

    model.fit(
            X,
            Y,
            batch_size=512,
            nb_epoch=1,
            validation_split=0.05)
    
    print("Predicting...")
   
    y_prediction = model.predict_proba(x_prediction)
    results = y_prediction[:, 1]
    results_df = pd.DataFrame(data={'probability':results})
    joined = pd.DataFrame(ids).join(results_df)

    print("Writing predictions to predictions.csv")

    joined.to_csv("predictions.csv", index=False)


if __name__ == '__main__':
    main()




```

here is the console log.

Loading data...
Compiling ....
Training...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    exception_prefix='input')
  File "C:\Users\famil\Anaconda3\lib\site-packages\keras\engine\training.py", line 113, in _standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected lstm_12_input to have 3 dimensions, but got array with shape (393613, 50)
>>>   File "C:\Users\famil\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)
  File "C:\Users\famil\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)
  File "C:/Users/famil/Desktop/NumerAI/example_model.py", line 74, in <module>
    main()
  File "C:/Users/famil/Desktop/NumerAI/example_model.py", line 59, in main
    validation_split=0.05)
  File "C:\Users\famil\Anaconda3\lib\site-packages\keras\models.py", line 963, in fit
    validation_steps=validation_steps)
  File "C:\Users\famil\Anaconda3\lib\site-packages\keras\engine\training.py", line 1637, in fit
    batch_size=batch_size)
  File "C:\Users\famil\Anaconda3\lib\site-packages\keras\engine\training.py", line 1483, in _standardize_user_data

**Comment by ceteke** [comment]
You directly feed the data you read from the csv therefore, your training data is not sequential, LSTM wants sequential data.

PS: 512 is too big of a minibatch size
