### ISSUE TITLE
__call__ function in Custom Constraint in Conv2D in Keras not working

### ISSUE THREAD

**Issue by za13** [keras-team/keras#9454]
Let's say I want the matrix of weights to be equal to it's transpose So w_ij = w_ji

I tried to write my own custom constraint as

    conv1 = Conv2D(1, (3,3), padding='same', input_shape=(1, 500, 500), kernel_constraint = CustomConstraint())
    model=Sequential()
    model.add(conv1)
    model.compile(loss='mse' ,...)
    output = model.predict(train)
    for l in model.layers()
        weights = l.get_weights()
    w = np.array(weights[0])
    print(w)
    

    class CustomConstraint(Constraint):
        def __init__(self):
            print("INIT")

        def __call__(self, w):
            print("CALL")
            return .5*(w+K.transpose(w))

the problem is that `INIT` is being displayed, but `CALL` is not

the resulting weight matrix also is still not symmetric

I think the problem is with `kernel_constraint` because if I use `init=CustomConstraint()` instead, at least `CALL` shows up

**Comment by Dref360** [comment]
As stated in the doc, a constraint is only called after an optimizer update.
Please see : https://keras.io/constraints/
This works : 
```
from keras import Sequential
import keras.backend as K
from keras.constraints import Constraint
from keras.layers import Conv2D
import numpy as np
class CustomConstraint(Constraint):
    def __init__(self):
        print("INIT")

    def __call__(self, w):
        print("CALL")
        return .5*(w)

conv1 = Conv2D(1, (3,3), padding='same', input_shape=(50, 50,1), kernel_constraint = CustomConstraint())
model=Sequential()
model.add(conv1)
model.compile('sgd','mse')

model.fit(np.ones([10, 50, 50,1]), np.ones([10, 50, 50,1]), batch_size=10)
```

**Comment by za13** [comment]
if I'm supposed to use `fit`, then why do you use `np.ones([10, 50, 50,1])` for both `x` and `y`?

This isn't a classification problem. I'm not labeling each image as a classification (such as dog or cat). The goal is to generate the computed kernel using CNN and compare it with the actual filter used to blur the image

If I try

    model.fit(train, np.ones([1, 50, 50,1]), batch_size=1)

then I get

    ValueError: Dimension 2 in both shapes must be equal, but are 1 and 3. Shapes are [3,3,1,1] and [3,3,3,3]

even though I already confirmed `X.shape` to be `1, 50, 50, 1`

**Comment by Dref360** [comment]
This was just an example. If you don't train, use an initializer instead.

You Constraint change the shape of the weight so when it gets updated the gradient shape isn't right.

**Comment by za13** [comment]
you mean I don't have to include `fit` and can just rewrite `Conv2D` as 

    conv1 = Conv2D(1, (3,3), padding='same', kernel_initializer='random_normal', input_shape=(1, 500, 500), kernel_constraint = CustomConstraint()

I tried that and now I don't see `CALL`
