### ISSUE TITLE
[Feature Request] Lattice layers

### ISSUE THREAD

**Issue by zachmayer** [keras-team/keras#9466]
I'm not sure how to make a feature request, but [lattices in tensorflow](https://github.com/tensorflow/lattice) look really cool, and I'd love to see lattice layers in keras.

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by mmilanifard** [comment]
Hey Zach. We are working on a Keras layer implementation of the TF Lattice library. It will have TF backend with both TF 2.x eager support and TF 1.x legacy support.

**Comment by zachmayer** [comment]
That is awesome!  Thank you!

**Comment by zachmayer** [comment]
For those from the future reading this, here are some lattice + keras examples: 
https://www.tensorflow.org/lattice
https://www.tensorflow.org/lattice/tutorials/keras_layers

They're pretty cool and it's nice to have keras support (@mmilanifard thanks!)
