### ISSUE TITLE
Weight matrix isn't circular/Toeplitz

### ISSUE THREAD

**Issue by za13** [keras-team/keras#9469]
For CNN, the weight matrix is supposed to be a circular/Toeplitz, according to Page 329 of this: http://www.deeplearningbook.org/contents/convnets.html

So why is that if you print out the weights of Conv2D in Keras, the matrix doesn't look circular at all?

**Comment by isaacgerg** [comment]
A convolutional matrix can be expressed 2 ways. 1. As a toeplitz matrix, 2. As simply the convolutional kernel.  Keras does the later.
