### ISSUE TITLE
Simple doubt about LSTM model.add

### ISSUE THREAD

**Issue by eduardoandrade** [keras-team/keras#9470]
If I have a sample with 64 elements

[1, 0, 1, 1, ...]

and put it through the model:

model.add(LSTM(32, batch_input_shape=(1, 64, 1), stateful=True))

I want the LSTM to read them by 32 bits per 32 bits, like a 32-bits word. Is this idea correct? If not, how can I change it to do the right understanding of the sample?

P.S: The problem is from sentiment analysis context.

**Comment by sairajk** [comment]
The LSTM can be thought of a mapping function between two spaces of same or different dimensionality.  Your input data is of type (1, 64, 1) [ (batch_size, timesteps, input_dim) ] which means your batch size is 1, your input is 64 timesteps long and lies in a 1D space. 

Now the 32 you entered into the LSTM arguments is the dimensionality of the output space, i.e if you make the "return sequences" argument of LSTM to be true, you would be getting an output at every timestep for the number of instances you have in your batch (in your case that is 1). Therefore the output with "return sequences = True" would be of dimension (1, 64, 32) [ (batch_size, timesteps, output_dim) ].

> I want the LSTM to read them by 32 bits per 32 bits, like a 32-bits word. Is this idea correct?

No, you are not. Hope you understood why from the above explanation. The number 32 you entered is the output dimension and no way related to the way LSTM reads them.
The LSTM always reads inputs one by one, i.e one timestep at once.

**Comment by eduardoandrade** [comment]
Thank you. So, I have changed (1,64,1) for (1,2,32) but how to make the label.reshape works with this modification? My actual label.reshape is (1750,1) for a binary classification (model.add(Dense(1, activation = 'sigmoid'))).

**Comment by sairajk** [comment]
I couldn't get the second part, can you please elaborate or explain your
problem with more details ?
