### ISSUE TITLE
Error "Tensor conversion requested dtype int32 for Tensor with dtype float32" while training

### ISSUE THREAD

**Issue by krupach** [keras-team/keras#9472]
I'm getting the error "Tensor conversion requested dtype int32 for Tensor with dtype float32" during the training phases

Running the latest Keras (2.1.3) and TensorFlow (1.5) through Conda.

Here is the minimum code that reproduces the error:

```
from keras.layers import Input, Conv2D, GlobalAveragePooling2D
from keras.models import Model

import keras.backend as K
import numpy as np

def test_loss(y_input, x_input):
   
    x1 = K.cast(x_input, dtype='int32')
    y1 = K.cast(y_input, dtype='int32')
    
    loss = K.square(x1 - y1)

 
    reduced_loss = K.cumsum(loss)
    
    return reduced_loss

train_data = 10*np.random.rand(1600, 18,18,512)
validation_data = 10*np.random.rand(200, 18,18,512)

Y_train = np.random.rand(1600, 803)
Y_test = np.random.rand(200, 803)

#model
inputs = Input(shape=train_data.shape[1:])
x = Conv2D(803, (1,1), activation='sigmoid')(inputs)
predictions = GlobalAveragePooling2D(input_shape=train_data.shape[1:])(x)
model = Model(inputs=inputs, outputs=predictions)

model.summary()

model.compile(optimizer='adam', loss=test_loss,  metrics=['accuracy'])

model.fit(train_data, Y_train,
              epochs=200,
              batch_size=1,
              validation_data=(validation_data, Y_test))
```

**Comment by ymodak** [comment]
Hi!
This issue isn't related to a bug/enhancement/feature request or other accepted types of issue.
To ask questions, please see the following resources :
[StackOverflow](http://stackoverflow.com/questions/tagged/keras)
[Keras Slack channel](https://keras-slack-autojoin.herokuapp.com)
[Keras.io support](https://keras.io/#support)
[Gitter](https://gitter.im/Keras-io/Lobby)
Thanks!
If you think we made a mistake, please open another issue explaining your request in detail.
