### ISSUE TITLE
Unableto resume training after loading models in Keras

### ISSUE THREAD

**Issue by avithal** [keras-team/keras#9481]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [ ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [ ] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by avithal** [comment]
I am saving model after  more than 'x'iterations and  using callbacks in keras .But  when I try to  load it , it does not take the  learned weights, it starts training from the begenning. Why?

**Comment by sairajk** [comment]
I have used callbacks in the past but never faced such a problem. Ensure that you are loading the right model and right weights.

Why don't you manually save the model and weights once to see if the problem still continues?

**Comment by mpariente** [comment]
What are you loading? 
Is it the .json or the .h5 file? 
If my understanding in correct, the .json contains the architecture but not the weights, the weights are saved (and should be loaded from) in the .h5 file.
