### ISSUE TITLE
Callbacks for evaluate() and evaluate_generator()

### ISSUE THREAD

**Issue by guifereis** [keras-team/keras#9484]
Keras Model functional API allows fit() and fit_generator() to have a callback. This is useful to record logging history or temporary information, or for use with tools such as keras-tqdm. However, evaluate() and evaluate_generator() can also take a long time (30mins+ on my current dataset), and so would seem a priori to be good candidates to also take a list of callback functions.

I've searched but found no discussion on this. Is there a reason this would not be feasible to implement?

Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [ y] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [ y] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [n/a ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by bertsky** [comment]
I believe this is already being discussed in #4185. 

(If we can get callbacks for validation, then we will also have them for evaluation: Either `evaluate()` or `evaluate_generator()` is called by `fit_generator()` for validation. And `test_loop()` is called by both `evaluate()` and `fit_loop()`, which is called by `fit()`.)
