### ISSUE TITLE
Train LSTM using both cell state and output layer simultaneously

### ISSUE THREAD

**Issue by eygrr** [keras-team/keras#9494]
I am looking to train an LSTM such that it learns from its cell state as well as learning from a output layer. To be more specific, I want to use the final cell state of the LSTM layer as one output, and a traditional output layer as another output, and to train them simultaneously. 

In this post: http://colah.github.io/posts/2015-08-Understanding-LSTMs/ the cell state is labelled c_t, and the output state is labelled h_t. The cell state that I want to use as one output is c_t, and the output state is the one that's used as input to the traditional output layer.

![image](https://user-images.githubusercontent.com/10671070/36686383-28fa2f26-1b1e-11e8-9c1e-e979ca55a3c8.png)

To clarify, this means that I'll have two outputs (y_1, y_2) to optimize towards, y_1 which is an array the size of the LSTM units, which is used to train the cell state, the other y_2 is a single binary output layer. Which trains the whole network as normal.

Here's an example of what I mean:

```
model = Sequential()

model.add(Embedding(input)) # The input layer

model.add(LSTM(units)) # The LSTM layer that has the cell state I want to use as an output 

model.add(Dense(1)) # The binary output layer
```

How can I achieve this in Keras?

**Comment by carlthome** [comment]
When you're calling `model.fit` the cell state will already be trained as everything before it (like the gate parameters, the input projection's weight matrix, as well as all previous layers) producing it in the forward pass are (hopefully) improved by gradient descent with backprop. Do you mean that you also have labels for what the cell states should be and want additional loss terms for this?

**Comment by eygrr** [comment]
That's exactly it. I have labels for the cell states and want additional loss terms, where the cell state is directly used as input to that loss.

**Comment by carlthome** [comment]
Interesting. What are you trying to do exactly?

Anyway, try the functional model API instead of `Sequential` and you could get the state tensor easily:

```py
from keras.models import *
from keras.layers import *

timesteps = None
features = 100
input_sequence = Input((timesteps, features))
output_sequence, cell_state, last_output = LSTM(32, return_sequences=True, return_state=True)(input_sequence)

model = Model(input_sequence, [output_sequence, cell_state])
```

**Comment by eygrr** [comment]
Thanks! This looks like exactly what I was looking for. I tried to implement my own version, but I'm getting an error that I don't understand.

```
from keras.models import *
from keras.layers import *

features = 10
dimensions = 5

y = np.random.randint(low=0, high=2, size=(features), dtype=np.int64)
y_cell = np.random.randint(low=0, high=2, size=(features, dimensions), dtype=np.int64)
x = np.random.random(size=(features, dimensions))

input_sequence = Input(shape=(features, dimensions))
output_sequence, cell_state, last_output = LSTM(dimensions, return_sequences=True, return_state=True)(input_sequence)
output_layer = Dense(1)

model = Model(input_sequence, [output_sequence, cell_state])

model.compile(loss='binary_crossentropy',
                          optimizer='adam',
                          metrics=['accuracy'])

model.fit(x, [y, y_cell])
```

This results in the following error: 

`ValueError: Error when checking input: expected input_1 to have 3 dimensions, but got array with shape (10, 5)`

From my understanding, the input layer should have two dimensions. The first is the amount of features, the second the dimensionality of the input. But here it expects 3, which is odd. Are there additional inputs for functional models, or is this just a mistake?

**Comment by carlthome** [comment]
See `TimeDistributed` in wrappers.

**Comment by eygrr** [comment]
Thanks, I'll close the issue.
