### ISSUE TITLE
discussions of triplet loss inputs

### ISSUE THREAD

**Issue by Ao-Lee** [keras-team/keras#9498]
I have fine-tuned a pre-trained network with triplet loss. after training, the network predicts exactly the same results no matter what inputs we feed. I have done troubleshooting for half a week and found that the root cause is the multiple inputs structure of the network. After tons of experiments, I found that this phenomenon will only arise if the network has multiple inputs. It has nothing to do with data and loss. Since any dataset and any loss function can reproduce the phenomenon, I use a fake triplet loss and a fake dataset to illustrate the problem, just for simplification and better understanding.

I use python3.5 on win7, with up-to-date keras with up-to-date tensorflow backend.
the cuda library is cuda9.0 for windows 

```
batch_size = 8
image_size = 224
embedding_dim = 5

def identity_loss(y_true, y_pred):
    return K.mean(y_pred - 0 * y_true)

A = np.ones([batch_size,embedding_dim])
A /= embedding_dim
A = K.variable(A)
    
def fake_loss(X):
    item, _,_ = X
    # item = X
    loss = K.sum(A * item, axis=-1, keepdims=True)
    return loss
    
############## Model ########################### 
def GetBaseModel():
    base_model = ResNet50(weights='imagenet', include_top=False)
    x = base_model.output
    x = GlobalMaxPooling2D()(x)
    x = Dropout(0.5)(x)
    dense_1 = Dense(embedding_dim)(x)
    normalized = Lambda(lambda  x: K.l2_normalize(x,axis=1))(dense_1)
    base_model = Model(base_model.input, normalized, name="base_model")
    return base_model

def GetMyModel(base_model):
    input_1 = Input((image_size,image_size,3))
    input_2 = Input((image_size,image_size,3))
    input_3 = Input((image_size,image_size,3))

    r1 = base_model(input_1)
    r2 = base_model(input_2)
    r3= base_model(input_3)

    loss = Lambda(fake_loss)([r1,r2,r3]) 
    model = Model(inputs=[input_1, input_2, input_3], outputs=loss)
    model.compile(loss=identity_loss, optimizer=Adam(0.000003))
    # print(model.summary())
    return model
```
	
It can be seen that, before training, each data generate a different loss, which is normal and which is what we expected:

```
base_model = GetBaseModel()
model = GetMyModel(base_model)
print(model.predict_on_batch(batch[0]))
```

the result is:
```
[[0.09356911]
 [0.08442864]
 [0.04717201]
 [0.06100047]
 [0.08477053]
 [0.07589568]
 [0.06031361]
 [0.05517637]]
```
 
after training, the model always predicts a fixed result no matter what input is.
 
```
 model.fit_generator(train_generator, 
                    validation_data=test_generator, 
                    epochs=5, 
                    verbose=2, 
                    workers=4,
                    steps_per_epoch=20, 
                    validation_steps=30)

print(model.predict_on_batch(batch[0]))

[[0.08818615]
 [0.08818615]
 [0.08818615]
 [0.08818615]
 [0.08818615]
 [0.08818615]
 [0.08818615]
 [0.08818615]]
```
Someone may argue that my fake loss could be a reason. Actually, I used triplet loss, and the network generated the same thing.  But if we change the input of the model and let the model only accept one vector, everything gets back to normal. the code and the output is here
 
 ```
def fake_loss(X):
    item = X
    loss = K.sum(A * item, axis=-1, keepdims=True)
    return loss
	
 def GetMyModel(base_model):
    input_1 = Input((image_size,image_size,3))
    r1 = base_model(input_1)

    loss = Lambda(fake_loss)(r1,) 
    model = Model(inputs=input_1, outputs=loss)
    model.compile(loss=identity_loss, optimizer=Adam(0.000003))
    # print(model.summary())
    return model

model.fit_generator(train_generator, 
                    validation_data=test_generator, 
                    epochs=5, 
                    verbose=2, 
                    workers=4,
                    steps_per_epoch=20, 
                    validation_steps=30)

print(model.predict_on_batch(batch[0]))

[[-0.395428  ]
 [-0.41014406]
 [-0.4061373 ]
 [-0.3003529 ]
 [-0.40376177]
 [-0.31965423]
 [-0.23563485]
 [-0.35777506]]
```
generating same predictions for any input data is  a very unreasonable behavior, and I cannot solve it alone. It would be very greatful if someone can solve it
thank you in advance

The whole runnable script can be found here
https://github.com/Ao-Lee/Shares/blob/master/standard%20inputs.py
https://github.com/Ao-Lee/Shares/blob/master/triplet%20inputs.py

**Comment by Ao-Lee** [comment]
I think other users have met the same problem, plz see 
https://stackoverflow.com/questions/41075993/facenet-triplet-loss-with-keras

**Comment by Ao-Lee** [comment]
it is fixed:
the problem is caused because of a bad implementation of triplet loss.

```
def triplet_loss(inputs, dist='sqeuclidean', margin='maxplus'):
    anchor, positive, negative = inputs
    positive_distance = K.square(anchor - positive)
    negative_distance = K.square(anchor - negative)
    if dist == 'euclidean':
        positive_distance = K.sqrt(K.mean(positive_distance, axis=-1, keepdims=True))
        negative_distance = K.sqrt(K.mean(negative_distance, axis=-1, keepdims=True))
    elif dist == 'sqeuclidean':
        positive_distance = K.mean(positive_distance, axis=-1, keepdims=True)
        negative_distance = K.mean(negative_distance, axis=-1, keepdims=True)
    loss = positive_distance - negative_distance
    if margin == 'maxplus':
        loss = K.maximum(0.0, 1 + loss)
    elif margin == 'softplus':
        loss = K.log(1 + K.exp(loss))
    return K.mean(loss)
```

I change K.mean to K.sum to fix it

```
def triplet_loss(inputs, dist='sqeuclidean', margin='maxplus'):
    anchor, positive, negative = inputs
    positive_distance = K.square(anchor - positive)
    negative_distance = K.square(anchor - negative)
    if dist == 'euclidean':
        positive_distance = K.sqrt(K.sum(positive_distance, axis=-1, keepdims=True))
        negative_distance = K.sqrt(K.sum(negative_distance, axis=-1, keepdims=True))
    elif dist == 'sqeuclidean':
        positive_distance = K.sum(positive_distance, axis=-1, keepdims=True)
        negative_distance = K.sum(negative_distance, axis=-1, keepdims=True)
    loss = positive_distance - negative_distance
    if margin == 'maxplus':
        loss = K.maximum(0.0, 1 + loss)
    elif margin == 'softplus':
        loss = K.log(1 + K.exp(loss))
    return K.mean(loss)
```

the root reason is that the norm2 distance between embedding vectors are baddly implemented. further more I think it is better to discuss it on stack over flow than github issues, since this is not a keras bug

**Comment by lillykumari** [comment]
The embeddings/predictions are basically the bias corresponding to the last layer. You can get rid of it by using a Normalization layer. 
[https://stats.stackexchange.com/questions/248511/purpose-of-l2-normalization-for-triplet-network/263363]

**Comment by sainimohit23** [comment]
> 
> 
> I have fine-tuned a pre-trained network with triplet loss. after training, the network predicts exactly the same results no matter what inputs we feed. I have done troubleshooting for half a week and found that the root cause is the multiple inputs structure of the network. After tons of experiments, I found that this phenomenon will only arise if the network has multiple inputs. It has nothing to do with data and loss. Since any dataset and any loss function can reproduce the phenomenon, I use a fake triplet loss and a fake dataset to illustrate the problem, just for simplification and better understanding.
> 
> I use python3.5 on win7, with up-to-date keras with up-to-date tensorflow backend.
> the cuda library is cuda9.0 for windows
> 
> ```
> batch_size = 8
> image_size = 224
> embedding_dim = 5
> 
> def identity_loss(y_true, y_pred):
>     return K.mean(y_pred - 0 * y_true)
> 
> A = np.ones([batch_size,embedding_dim])
> A /= embedding_dim
> A = K.variable(A)
>     
> def fake_loss(X):
>     item, _,_ = X
>     # item = X
>     loss = K.sum(A * item, axis=-1, keepdims=True)
>     return loss
>     
> ############## Model ########################### 
> def GetBaseModel():
>     base_model = ResNet50(weights='imagenet', include_top=False)
>     x = base_model.output
>     x = GlobalMaxPooling2D()(x)
>     x = Dropout(0.5)(x)
>     dense_1 = Dense(embedding_dim)(x)
>     normalized = Lambda(lambda  x: K.l2_normalize(x,axis=1))(dense_1)
>     base_model = Model(base_model.input, normalized, name="base_model")
>     return base_model
> 
> def GetMyModel(base_model):
>     input_1 = Input((image_size,image_size,3))
>     input_2 = Input((image_size,image_size,3))
>     input_3 = Input((image_size,image_size,3))
> 
>     r1 = base_model(input_1)
>     r2 = base_model(input_2)
>     r3= base_model(input_3)
> 
>     loss = Lambda(fake_loss)([r1,r2,r3]) 
>     model = Model(inputs=[input_1, input_2, input_3], outputs=loss)
>     model.compile(loss=identity_loss, optimizer=Adam(0.000003))
>     # print(model.summary())
>     return model
> ```
> 
> It can be seen that, before training, each data generate a different loss, which is normal and which is what we expected:
> 
> ```
> base_model = GetBaseModel()
> model = GetMyModel(base_model)
> print(model.predict_on_batch(batch[0]))
> ```
> 
> the result is:
> 
> ```
> [[0.09356911]
>  [0.08442864]
>  [0.04717201]
>  [0.06100047]
>  [0.08477053]
>  [0.07589568]
>  [0.06031361]
>  [0.05517637]]
> ```
> 
> after training, the model always predicts a fixed result no matter what input is.
> 
> ```
>  model.fit_generator(train_generator, 
>                     validation_data=test_generator, 
>                     epochs=5, 
>                     verbose=2, 
>                     workers=4,
>                     steps_per_epoch=20, 
>                     validation_steps=30)
> 
> print(model.predict_on_batch(batch[0]))
> 
> [[0.08818615]
>  [0.08818615]
>  [0.08818615]
>  [0.08818615]
>  [0.08818615]
>  [0.08818615]
>  [0.08818615]
>  [0.08818615]]
> ```
> 
> Someone may argue that my fake loss could be a reason. Actually, I used triplet loss, and the network generated the same thing. But if we change the input of the model and let the model only accept one vector, everything gets back to normal. the code and the output is here
> 
> ```
> def fake_loss(X):
>    item = X
>    loss = K.sum(A * item, axis=-1, keepdims=True)
>    return loss
>    
> def GetMyModel(base_model):
>    input_1 = Input((image_size,image_size,3))
>    r1 = base_model(input_1)
> 
>    loss = Lambda(fake_loss)(r1,) 
>    model = Model(inputs=input_1, outputs=loss)
>    model.compile(loss=identity_loss, optimizer=Adam(0.000003))
>    # print(model.summary())
>    return model
> 
> model.fit_generator(train_generator, 
>                    validation_data=test_generator, 
>                    epochs=5, 
>                    verbose=2, 
>                    workers=4,
>                    steps_per_epoch=20, 
>                    validation_steps=30)
> 
> print(model.predict_on_batch(batch[0]))
> 
> [[-0.395428  ]
> [-0.41014406]
> [-0.4061373 ]
> [-0.3003529 ]
> [-0.40376177]
> [-0.31965423]
> [-0.23563485]
> [-0.35777506]]
> ```
> 
> generating same predictions for any input data is a very unreasonable behavior, and I cannot solve it alone. It would be very greatful if someone can solve it
> thank you in advance
> 
> The whole runnable script can be found here
> https://github.com/Ao-Lee/Shares/blob/master/standard%20inputs.py
> https://github.com/Ao-Lee/Shares/blob/master/triplet%20inputs.py

I i'm trying to implement triplet loss for face recognition. Here's part of my code:

`def triplet_loss(y_true, y_pred, alpha = 0.2):    
    anchor, positive, negative = y_pred[0], y_pred[1], y_pred[2]
    pos_dist = tf.reduce_sum(tf.square(tf.subtract(anchor, positive)), axis=-1)
    neg_dist = tf.reduce_sum(tf.square(tf.subtract(anchor, negative)), axis=-1)
    basic_loss = tf.add(tf.subtract(pos_dist, neg_dist), alpha)
    loss = tf.reduce_sum(tf.maximum(basic_loss, 0.0))

    
    return loss


FRmodel = faceRecoModel(input_shape=(3, 96, 96))
load_weights_from_FaceNet(FRmodel)
for layer in FRmodel.layers:
    layer.trainable = False
    
FRmodel.get_layer("dense_layer").trainable = True

input_1 = Input((3, 96, 96))
input_2 = Input((3, 96, 96))
input_3 = Input((3, 96, 96))

pred1 = FRmodel(input_1)
pred2 = FRmodel(input_2)
pred3 = FRmodel(input_3)

t_loss = triplet_loss(0, [pred1, pred2, pred3])
model = keras.models.Model(inputs=[input_1, input_2, input_3], outputs= [t_loss])
`


I'm getting this error: 

> TypeError: Output tensors to a Model must be Keras tensors. Found: Tensor("Sum_11:0", shape=(), dtype=float32)

Do you know why this is happening?

**Comment by elluck91** [comment]
Did anyone figure this out?

**Comment by ale152** [comment]
I believe this issue is related to a bug in the batchnormalization layer that only shows up when more than 2 inputs are fed into the network:

https://github.com/keras-team/keras/issues/11927

This bug basically prevents the implementation of any triplet loss model that uses batchnormalization in the encoder. 

Hopefully someone will fix it soon!
