### ISSUE TITLE
one_hot gives different encodings for the same words

### ISSUE THREAD

**Issue by peter-pogorelov** [keras-team/keras#9500]
Just noticed that one_hot function can give different results for the same word (actually I thought that hash function can give the same _value_ for different words but not vice versa). I found that it happens when you feed a long string (> 200 words) to a function and compare it with the result when you feed just a single word. 

Here is a code (pandas is required).

1) We define a long list of words which contain cyrillic characters.

`word_indices_1 = ['доносительств', 'низк', 'казнокрадк', 'корна', 'плеш', 'патриархальн', 'земельн', 'деревя', 'парков', 'чечерск', 'заклин', 'кардиобольн', 'лжебанкрот', 'рах', 'рахитичк', 'спаива', 'уразумет', 'возн', 'пересыха', 'бреха', 'вензаболеван', 'дистон', 'урезон', 'поздравляшк', 'нетрудоустроен', 'заключен', 'паранаркотик', 'забастовк', 'тревог', 'пароксизм', 'поджигател', 'текучк', 'суш', 'наводнен', 'фол', 'брыка', 'заляпаный/заляпан', 'инакомысл', 'храпет', 'жжен', 'негат', 'мат-перемат', 'убойн', 'похитител', 'дневн', 'самозахват', 'потряст', 'загуб', 'обязательн', 'коленопреклонен', 'градобит', 'должник', 'тугоух', 'спасительн', 'нелицензион', 'превышен', 'конфисковыва', 'поколачива', 'наркотоксикоман', 'привилег', 'самогонщик', 'растеря', 'модернизацион', 'мстительниц', 'подробн', 'мародерствова', 'перет', 'субъективизм', 'расправ', 'разумен', 'всуч', 'многоэтажн', 'блева', 'встряхива', 'смертоубийств', 'зараз', 'протрезвлен', 'удав', 'допингов', 'интригова', 'соучастниц', 'демократ', 'подвод', 'оргпреступн', 'взаимовыручк', 'запротестова', 'пересушк', 'прилипчив', 'угора', 'неотъемлим', 'занос', 'митинск', 'черв', 'лезт', 'пеня', 'шизофреник', 'жирн', 'техническ', 'незавершенк', 'гепатопат', 'простреля', 'наглота', 'парализац', 'торгов', 'вспыхнут', 'плешивет', 'энцефал', 'залипнут', 'передов', 'прыщ', 'апоплексическ', 'интересова', 'комик', 'независим', 'бездействова', 'загажива', 'глаукомн', 'ужал', 'солнечн', 'гэмблинг', 'загрязнен', 'пищан', 'ложн', 'дикост', 'драматическ', 'памятн', 'финт', 'ящур', 'взыскан', 'резн', 'склеротическ', 'наркоточк', 'мародерк', 'наркобизнесм', 'пробивн', 'наружн', 'беспамятств', 'косяк', 'погреба', 'цепля', 'наркопреступник', 'разворовыван', 'взлом', 'отчисля', 'очеред', 'сопротивлен', 'леденет', 'уголовно-наказуем', 'поруш', 'молод', 'отстойн', 'шумн', 'протрезв', 'дипломат', 'уясня', 'заигрыва', 'действен', 'мета', 'захвора', 'массивн', 'бомбардировк', 'наркокриминальн', 'сочувствова', 'просажива', 'исправля', 'замерзнут', 'похож', 'выматер', 'браконьерствова', 'гроз', 'отдален', 'помоч', 'оплешивет', 'храмов', 'преследовательниц', 'хакерств', 'завоевател', 'клептома', 'поджигательниц', 'взлет', 'бомжих', 'покаян', 'обокраст', 'некуря', 'подь', 'опоздан', 'стачечниц', 'шоков', 'голода', 'меценатск', 'сед', 'холодн', 'ваххабистск', 'обременен', 'поост', 'дифтерийн', 'отторгнут', 'исправлен', 'наркогрупп', 'запута', 'засух', 'тюремн', 'соответств', 'разбазарива', 'зап', 'перегрузк', 'машиностроительн', 'непьющ', 'припоздн', 'наркотрафик', 'загн', 'кибершпионаж', 'гангр', 'убивиц', 'угод', 'умертвля', 'тряст', 'клещ', 'ропот', 'онкобольн', 'наркоперевозчик', 'досад', 'подворовыва', 'урага', 'шантажирова', 'дефектн', 'фистульн', 'ваххаб', 'застоя', 'набег', 'таракан', 'невольниц', 'отлупцева', 'поражен', 'наркотизм', 'чавкан', 'провальн', 'недофинансирован', 'перемира', 'переоцен', 'наушнича', 'наркоиндустр', 'директивн', 'чесоточн', 'запрет', 'извоз', 'экстремистск', 'натиск', 'подельник', 'синяк', 'алкоголизац', 'заболеван', 'люб', 'суицидн', 'метан', 'стекля']`

2) Encode them with one_hot function and store the result to pandas dataframe

`d = pd.DataFrame(list(zip(one_hot(' '.join(word_indices_1), 500000), word_indices_1)), columns=['a', 'b'])`
`d[d.a == 243671]`

and got the following result: 243671 | суицидн

3) Call the function with a single word:

`one_hot(word_indices_1[250], 500000), word_indices_1[250]`

Which outputs: ([243671], 'алкоголизац')

We got different words with the same one hot encoding. Please correct me if I made a mistake somewhere.

**Comment by mewwts** [comment]
Hi @peter-pogorelov,

The issue here is that `one_hot` uses the Python `hash` function which is not stable across runs. See https://github.com/keras-team/keras/blob/master/keras/preprocessing/text.py#L96.

You could easily switch out `one_hot(x, n)` by `hashing_trick(x, n, hash_fuction='md5')` and see the consistent results.
