### ISSUE TITLE
keras is not working on docker container and not throwing errors though

### ISSUE THREAD

**Issue by Chuck-Aguilar** [keras-team/keras#9503]
I'm having a weird problem with keras. 

I commented the problem in this question: [stack question](https://stackoverflow.com/questions/49006686/keras-is-not-working-on-docker-container-but-not-throwing-errors-though)

and that's it.

I'm trying to run [this example](https://raw.githubusercontent.com/keras-team/keras/master/examples/mnist_mlp.py) just to test keras on a docker-container. And `model.fit` or `model.evaluate` are not working at all, it just gets stock without throwing any error. 

![image](https://user-images.githubusercontent.com/15911477/36732361-d16ed2ba-1bcd-11e8-9b56-2e3ae48f84ef.png)

it just stopped there. 

Outside the docker container it works properly though. 

My dockerfile is [here](https://gist.github.com/Chuck-Aguilar/348e47a5764526bd0c00cff51d3d8eff)

And I call it this way:

```
@app.route('/ocr/test_keras', methods=['GET'])
def test_keras():
    Thread(target=continue_test_keras, args=()).start()
    return jsonify('Success')

def continue_test_keras():
    tk.run()
    print('tests done')
```

where tk is [this gist](https://gist.github.com/Chuck-Aguilar/0db4a72ffcea1b8aac484305ed311c09)

it would be nice at least having an error log or an exception. But just stocking there, I don't have a clue, what I could be. 

I read this [issue](https://github.com/keras-team/keras/issues/9497), but I'm using tensorflow, and as I use a dockerfile, it reinstalls always everything again. 

```
{
    "floatx": "float32",
    "epsilon": 1e-07,
    "backend": "tensorflow",
    "image_data_format": "channels_last"
}
```

**Comment by Chuck-Aguilar** [comment]
I'm closing this, because I found out, that it doesn't have to do with the docker container. I entered to the docker container and executed there the code, and it worked. 
So, I suppose it has to do with flask. 

I'm gonna open another issue, because I tried everything from here: [2397](https://github.com/keras-team/keras/issues/2397) and it still no working with tensorflow as backend

**Comment by Chuck-Aguilar** [comment]
Well I'm gonna write the answer here, because it's easier.

The problem was with uwsgi. Somehow Keras didn't work there.

I just followed the instructions [of this github repo](https://github.com/jsmits/keras-inception-service) and now it's working.

**Comment by Maximilian-Fuchs** [comment]
I'm having the same issue with a keras/tensorflow/flask/docker combination

**Comment by MarkRatFelt** [comment]
is your project public? 
Or could you provide a bit more information? 
If your project is not public, maybe you can upload a gist
