### ISSUE TITLE
Can anyone run cifar10_cnn_tfaugment2d.py successfully?

### ISSUE THREAD

**Issue by FrancisYizhang** [keras-team/keras#9504]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [Y] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [Y] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [N] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [Y] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

I can not run [cifar10_cnn_tfaugment2d.py](https://github.com/keras-team/keras/blob/master/examples/cifar10_cnn_tfaugment2d.py) successfully.

> My env
> Win7
> CUDA9.0
> Cudnn 7.0.4 and 7.0.5
> temsorflow 1.4 and 1.5
> keras-master
> Quadro K4000M

However, I can run [cifar10_resnet.py](https://github.com/keras-team/keras/blob/master/examples/cifar10_resnet.py) successfully.

The reporting is listed following:

> 2018-02-27 22:29:01.415988: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\common_runtime\gpu\gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Quadro K4000M, pci bus id: 0000:01:00.0, compute capability: 3.0)
> 2018-02-27 22:29:03.007079: E C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\stream_executor\cuda\cuda_dnn.cc:385] could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
> 2018-02-27 22:29:03.007079: E C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\stream_executor\cuda\cuda_dnn.cc:352] could not destroy cudnn handle: CUDNN_STATUS_BAD_PARAM
> 2018-02-27 22:29:03.007079: F C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\kernels\conv_ops.cc:717] Check failed: stream->parent()->GetConvolveAlgorithms( conv_parameters.ShouldIncludeWinogradNonfusedAlgo<T>(), &algorithms)

**Comment by FrancisYizhang** [comment]
@treszkai

**Comment by FrancisYizhang** [comment]
@treszkai 
Could you help me?
thanks in advance!

**Comment by ghostplant** [comment]
@FrancisYizhang 
Hi, I just tested this examples using latest framework:
1) keras==2.1.5
2) tensorflow-gpu==1.5.0
3) cuda: 9.1.85
3) cudnn: 7.0.5

And every thing is fine, so I think you may have environmental issue related to CUDNN library according to your logs.

**Comment by FrancisYizhang** [comment]
@ghostplant 
Hi, thank you very much. I am sorry to say my OS is Win7, and the latest CUDA version is 9.0.

**Comment by FrancisYizhang** [comment]
@ghostplant 
Do you install CUDA from source?

**Comment by ghostplant** [comment]
@FrancisYizhang The CUDA installation is via official Ubuntu local deb.
I search the logs through the internet and here are some possible reasons:
1) no enough GPU memory for CUDNN to allocate;
2) compute compatibility < 3;
3) wrong tensorflow compilation;
