### ISSUE TITLE
variational_autoencoder_deconv.py: 'NoneType' object has no attribute 'shape' 

### ISSUE THREAD

**Issue by ptleskin** [keras-team/keras#9521]
Hi,

I'm trying to run the code variational_autoencoder_deconv.py. Both keras (2.1.4) and tensorflow (1.5.0) should be up to date. 
In the first place I get an error at line vae.compile(optimizer='rmsprop'). If I fixed that like for instance by adding loss='mean_squared_error', the code ends up with the next error: AttributeError: 'NoneType' object has no attribute 'shape' at line 140: vae.fit(x_train, shuffle=True, epochs=epochs, batch_size=batch_size, validation_data=(x_test, None)).

Anyone else being experiencing similar problems?

Petri Leskinen

**Comment by yaobofd** [comment]
Just rewrite "vae.compile(optimizer='rmsprop')" to "vae.compile(optimizer='rmsprop', loss=None)"
