### ISSUE TITLE
Variational Autoencoder Custom Loss function

### ISSUE THREAD

**Issue by Pranav-Goel** [keras-team/keras#9526]
In running the variational_autoencoder.py file in keras/examples/, the following error is encountered - 
TypeError: compile() missing 1 required positional argument: 'loss'

On adding the vae_loss as the loss parameter in compile (i.e., vae.compile(optimizer='rmsprop'), loss=vae_loss) instead of vae.add_loss(vae_loss)), the following error is encountered - 

TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use TensorFlow ops such as tf.cond to execute subgraphs conditioned on the value of a tensor.

I think the problem is that we need to define a custom loss function for Keras in terms of a Python function that acts on y_pred and y_true, and this is not being done here.

**Comment by rex-yue-wu** [comment]
simply use `compile(loss=None)`
