### ISSUE TITLE
fit_generator with Sequence uses only one core/CPU

### ISSUE THREAD

**Issue by mpariente** [keras-team/keras#9531]
Hi, I'm training a model using `fit_generator` on GPU with a `keras.utils.Sequence` object as the data generator but whatever the number of `workers` I use, `Sequence` won't use more than one core (over 20).
Here is my call : 
```
history = self.model.fit_generator(self.generator,
                                   epochs=self.epochs,
                                   validation_data=(X_val, Y_val),
                                   callbacks=callback_list,
                                   workers=4,
                                   steps_per_epoch=len(self.generator),
                                   max_queue_size=8,
                                   use_multiprocessing=True).history 
```
Do you have any idea of a reason why?
Any help appreciated.

**Comment by minaessam2015** [comment]
I'm having the same issue too, I use it with 12 cores CPU and the same issue appears, moreover it leaks memory. For every new epoch the ram size it holds doubles.
