### ISSUE TITLE
Add inplace oov_token replacement in tokenizer

### ISSUE THREAD

**Issue by newbiesitl** [keras-team/keras#9540]
the text_to_seq() function in tokenizer class:

    def texts_to_sequences_generator(self, texts):
        """Transforms each text in texts in a sequence of integers.

        Only top "num_words" most frequent words will be taken into account.
        Only words known by the tokenizer will be taken into account.

        # Arguments
            texts: A list of texts (strings).

        # Yields
            Yields individual sequences.
        """
        num_words = self.num_words
        for text in texts:
            seq = text if self.char_level else text_to_word_sequence(text,
                                                                     self.filters,
                                                                     self.lower,
                                                                     self.split)
            vect = []
            for w in seq:
                i = self.word_index.get(w)
                if i is not None:
                    if num_words and i >= num_words:
                        continue
                    else:
                        vect.append(i)
                elif self.oov_token is not None:
                    i = self.word_index.get(self.oov_token)
                    if i is not None:
                        vect.append(i)
            yield vect

ignores out of vocabulary words during processing:

    i = self.word_index.get(w)
    if i is not None:
        if num_words and i >= num_words:
            continue

but in some scenarios, we need a unknown token placeholder for oov words, such as:

            i = self.word_index.get(w)
            if i is not None:
                if num_words and i >= num_words:
                    vect.append(self.word_index.get(self.oov_token))

can we add this option to Tokenizer constructor or text_to_sequence() function? something like: 

    def texts_to_sequences_generator(self, texts, inplace_oov=False):
        """Transforms each text in texts in a sequence of integers.

        Only top "num_words" most frequent words will be taken into account.
        Only words known by the tokenizer will be taken into account.

        # Arguments
            texts: A list of texts (strings).

        # Yields
            Yields individual sequences.
        """
        num_words = self.num_words
        for text in texts:
            seq = text if self.char_level else text_to_word_sequence(text,
                                                                     self.filters,
                                                                     self.lower,
                                                                     self.split)
            vect = []
            for w in seq:
                i = self.word_index.get(w)
                if i is not None:
                    if num_words and i >= num_words:
                        if inplace_oov:
                             i = self.word_index.get(self.oov_token)
                             if i is None:
                                continue
                       else:
                              continue
                    vect.append(i)        # <==== if we have oov_token reserved, we set it to oov, otherwise ignore
                elif self.oov_token is not None:
                    i = self.word_index.get(self.oov_token)
                    if i is not None:
                        vect.append(i)
            yield vect

**Comment by stikbuf** [comment]
Was thinking exactly the same. Similar in issue #9409.
