### ISSUE TITLE
cifar10_resnet.py Multi-gpu is slower than mono gpu 

### ISSUE THREAD

**Issue by TParcollet** [keras-team/keras#9543]
Hi everyone,

On a personal project, the bi-gpu was slower than mono-gpu. Therefore, I wanted to check if the problem was my project or something else. Using the cifar10_resnet.py model, I just added
`model = multi_gpu_model(model, gpus=2)`
Just before the model compilation annnnnnd:

1 GPU, 1 epoch = 27 sec
2 GPUs, 1 epoch = 32 sec

Any ideas ?

Thanks you !

**Comment by ghostplant** [comment]
You can try `version = 2` in this code since the new model has a better scalability.
