### ISSUE TITLE
w-categorical-crossentropy-function-keras-tensorflow

### ISSUE THREAD

**Issue by moustafaalaa** [keras-team/keras#9547]
I am trying to write custom loss function using Keras and tensorflow as backend. I checked similar questions but can't figure how to convert numpy code to tensorflow

Below

**y_true**: is the actual class it has the size 1*12 (one hot encoded) example : [0,0,0,0,0,0,0,0,0,0,0,1]
**y_pred**: is the model output predictions.
**classes_dest**: it include array n*1 (12*1) with number of observation per class. Example [10,20,30,40,50,50,30,90,30,10,10,30]
**unique_classes**: 12*12 array include unique index for each class such as y_true with different combinations
**den_total_sample** : integer number
What I am trying to do get the class index from the unique_classes let's name it idx. Then get the number of observation from classes_dest[idx] let's name it n. I wrote the below function

```

def w_categorical_crossentropy(y_true,y_pred,classes_dest,unique_classes,den_total_sample):

    print(unique_classes.shape)#(12,12)
    b=K.cast(y_true,dtype='float64')   
    wh = K.tf.where(K.tf.equal(unique_classes,b))
    print(wh.shape)#(?, 2)
    n = classes_dest[wh]#filter for output index
    return K.categorical_crossentropy(y_pred, y_true) * ((1/n) / den_total_sample ) 
```
but got the below error as I can't filter numby array with tensor

```
n = classes_dest[wh]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

**Comment by lxkain** [comment]
#9549 may be related?

**Comment by MostafaAlaa2016** [comment]
Yes, I am trying to index into a tensor. 

I opened Stackoverflow question for this point https://stackoverflow.com/questions/49088206/w-categorical-crossentropy-function-keras-tensorflow
