### ISSUE TITLE
ModelCheckpoint cannot save multi-gpu model

### ISSUE THREAD

**Issue by shinichiro-hamada** [keras-team/keras#9548]
The document of multi_gpu_model says below:
# On model saving
    To save the multi-gpu model, use `.save(fname)` or `.save_weights(fname)`
    with the template model (the argument you passed to `multi_gpu_model`),
    rather than the model returned by `multi_gpu_model`.

But modelCheckPoint applied to the multi-gpu model tries to save multi-gpu model
itself in each epoch end, so it fails.

**Comment by concerttttt** [comment]
Same here! Help wanted!

**Comment by evictor** [comment]
See https://github.com/keras-team/keras/issues/8463

**Comment by truenicoco** [comment]
Help wanted here too, see https://github.com/keras-team/keras/issues/8463#issuecomment-435911352
