### ISSUE TITLE
Spatial pyramid pooling layer

### ISSUE THREAD

**Issue by 53X** [keras-team/keras#9556]
There isn't any keras inbuilt function for the Spatial Pyramid Pooling Layer .

**Comment by harshini-gadige** [comment]
Hi

If you think this is a feature request/enhancement, please open the issue with clear information on what is expected or required.

To ask questions, please see the following resources :

https://keras.io/
https://keras.io/#support
https://gitter.im/Keras-io/Lobby

Thanks!

If you think I made a mistake, please update the issue. We will reopen it.
