### ISSUE TITLE
ValueError: Cannot feed value of shape (96, 784) for Tensor u'input_26:0', which has shape '(128, 784)'

### ISSUE THREAD

**Issue by tchaton** [keras-team/keras#9572]
Hello there,

I am training a neural network on mnist using the fit function. I defined my batch_shape as (128, 784). But somehow, during the inference (evaluation on the test set), the batch size change.

../../tools/v2/pipeline/ml_core.py:486: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  verbose=verbose)

Train on 60000 samples, validate on 10000 samples
Epoch 1/100
59904/60000 [============================>.] - ETA: 0s - loss: 2.3072 - acc: 0.1007

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-76-56c597b15a0a> in <module>()
----> 1 sc.train([x_train, y_train] , [Y_train],          [x_test, y_test[...,np.newaxis]] , [Y_test],          100,         128)

/home/thomas/virtualens/imagification2.7/Imagification/tools/v2/pipeline/ml_core.pyc in train(self, x_train, x_train_filtered, x_test, x_test_filtered, epochs, batch_size, log_dir, stop_early, verbose, learning_scheduler, plot)
    484                                              validation_data=(x_test, x_test_filtered),
    485                                              callbacks=callbacks,
--> 486                                              verbose=verbose)
    487 
    488     def encode(self, x):

/usr/local/lib/python2.7/dist-packages/keras/engine/training.pyc in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, **kwargs)
   1710                               initial_epoch=initial_epoch,
   1711                               steps_per_epoch=steps_per_epoch,
-> 1712                               validation_steps=validation_steps)
   1713 
   1714     def evaluate(self, x=None, y=None,

/usr/local/lib/python2.7/dist-packages/keras/engine/training.pyc in _fit_loop(self, f, ins, out_labels, batch_size, epochs, verbose, callbacks, val_f, val_ins, shuffle, callback_metrics, initial_epoch, steps_per_epoch, validation_steps)
   1233                         ins_batch[i] = ins_batch[i].toarray()
   1234 
-> 1235                     outs = f(ins_batch)
   1236                     if not isinstance(outs, list):
   1237                         outs = [outs]

/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.pyc in __call__(self, inputs)
   2473         session = get_session()
   2474         updated = session.run(fetches=fetches, feed_dict=feed_dict,
-> 2475                               **self.session_kwargs)
   2476         return updated[:len(self.outputs)]
   2477 

/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.pyc in run(self, fetches, feed_dict, options, run_metadata)
    887     try:
    888       result = self._run(None, fetches, feed_dict, options_ptr,
--> 889                          run_metadata_ptr)
    890       if run_metadata:
    891         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.pyc in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1094                 'Cannot feed value of shape %r for Tensor %r, '
   1095                 'which has shape %r'
-> 1096                 % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
   1097           if not self.graph.is_feedable(subfeed_t):
   1098             raise ValueError('Tensor %s may not be fed.' % subfeed_t)

ValueError: Cannot feed value of shape (96, 784) for Tensor u'input_26:0', which has shape '(128, 784)'

<matplotlib.figure.Figure at 0x7fe447987dd0>

**Comment by Dref360** [comment]
60000 % 128 = 96.
Don't specify the batch_shape, just the shape. Your first layer should be Input([784])

**Comment by tchaton** [comment]
Hello there,

Unfortunately I can't. I am creating a custom layer.
Inside of it, I loop over the activations inside the batch. Without defining it. Keras will send me an error saying that it can't iterate over a 'NoneType' which is normal.
In order to bypass that, I used batch_shape=(batch_size, dim_in).

It works perfectly during training, but when it gets to validation, batch_size changed for validation set (I think it is a proportional or maybe last batch).
Anyway, it breaks.
Do you have any idea how to solve it.
I will try to hack keras iterators if not :)

Thank you for the answer.

Best Regards, Thomas Chaton.

-----------------------
Thomas CHATON
Senior AI Researcher at Fujitsu AI Advanced Labs, London
Tel : +33 (0) 6 46 57 50 65

----- Mail original -----
De: "Frédéric Branchaud-Charron" <notifications@github.com>
À: "keras-team/keras" <keras@noreply.github.com>
Cc: "Thomas Chaton" <thomas.chaton@telecom-paristech.fr>, "Author" <author@noreply.github.com>
Envoyé: Mardi 6 Mars 2018 14:31:17
Objet: Re: [keras-team/keras] ValueError: Cannot feed value of shape (96, 784) for Tensor u'input_26:0', which has shape '(128, 784)' (#9572)

60000 % 128 = 96.
Don't specify the batch_shape, just the shape. Your first layer should be Input([784])

**Comment by tchaton** [comment]
Hello there,

I think I found how to solve it. I have to use an int for batch_size which divide both train samples and test samples. It will try it out tomorrow and inform you.

Best Regards, Thomas Chaton.

-----------------------
Thomas CHATON
Senior AI Researcher at Fujitsu AI Advanced Labs, London
Tel : +33 (0) 6 46 57 50 65

**Comment by tchaton** [comment]
A solution can be to define a batch_size that divide both train_samples and test_samples
