### ISSUE TITLE
docs correction: https://keras.io/activations/

### ISSUE THREAD

**Issue by denfromufa** [keras-team/keras#9576]
https://keras.io/activations/

It appears the last line is redundant here:

> ```
> from keras import backend as K
> 
> model.add(Dense(64, activation=K.tanh))
> model.add(Activation(K.tanh))
> ```

Otherwise this contradicts to previous paragraphs in that page:

> ```
> from keras.layers import Activation, Dense
> 
> model.add(Dense(64))
> model.add(Activation('tanh'))
> ```
> 
> This is equivalent to:
> ```
> model.add(Dense(64, activation='tanh'))
> ```

**Comment by fchollet** [comment]
Thanks, this is fixed (will be updated on the website soon).
