### ISSUE TITLE
Error with BatchNormalization while setting the default float type to 'float16'

### ISSUE THREAD

**Issue by flow-ra** [keras-team/keras#9582]
Hi,

I am trying to train a basic network on Keras with a float16 precision. However it looks like there is a bug with BatchNormalization.

For example, if I run the simple following code:
```
import keras
keras.backend.set_floatx('float16')

input_layer = keras.layers.Input(shape=(16,16,3))
x = keras.layers.BatchNormalization(axis=3)(input_layer) # <<Fails here
x = keras.layers.Conv2D(32, (3,3))(x)
```

I have the following error (entire output error at the end of this message):
> TypeError: Value passed to parameter 'scale' has DataType float16 not in list of allowed values: float32

If I suppress all BatchNormalization layers and only leave Conv2D, Activation, MaxPooling and Dense, I have no error and the training runs fine. Same if I switch 'float16' to 'float32'

I use Keras 2.1.4 with Tensorflow 1.4.0 as a backend, on a Linux machine with python 3.5.2.

Thank you for your help.

> Traceback (most recent call last):
>   File "test_BN_fp16.py", line 6, in <module>
>     x = keras.layers.BatchNormalization(axis=3)(input_layer) # <<Fails here
>   File "/usr/local/lib/python3.5/dist-packages/keras/engine/topology.py", line 617, in __call__
>     output = self.call(inputs, **kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/keras/layers/normalization.py", line 181, in call
>     epsilon=self.epsilon)
>   File "/usr/local/lib/python3.5/dist-packages/keras/backend/tensorflow_backend.py", line 1824, in normalize_batch_in_training
>     epsilon=epsilon)
>   File "/usr/local/lib/python3.5/dist-packages/keras/backend/tensorflow_backend.py", line 1799, in _fused_normalize_batch_in_training
>     data_format=tf_data_format)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/nn_impl.py", line 831, in fused_batch_norm
>     name=name)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 2296, in _fused_batch_norm_v2
>     is_training=is_training, name=name)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 609, in _apply_op_helper
>     param_name=input_name)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 60, in _SatisfiesTypeConstraint
>     ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
> TypeError: Value passed to parameter 'scale' has DataType float16 not in list of allowed values: float32
>

**Comment by Dref360** [comment]
This seems like a restriction from Tensorflow, could you move the issue to their repo, please?

**Comment by bradklingensmith** [comment]
This is not a restriction from Tensorflow. This is a case of Keras not using the Tensorflow API properly. The scale and offset variables should be float32, even when the data is in float16. See https://github.com/tensorflow/tensorflow/issues/8535. And Tensorflow implements it like this, because that's what NVIDIA recommends: http://docs.nvidia.com/deeplearning/sdk/mixed-precision-training/index.html.

**Comment by flow-ra** [comment]
Okay thank you for the infos. Is there a way to modify the dtype of layer variables in Keras ? I'm guessing the only way is to create a custom BatchNorm layer and specify that scale and offset are defined as float32.

Also, do you know why Nvidia recommends to save scale and offset in float32? There doesn't seem to be any clear explanation.

**Comment by bradklingensmith** [comment]
You do have to create a custom BatchNorm layer. Although, I would recommend simply fixing the existing BatchNorm layer to use float32 scale and offset when K.floatx() is float16. There are a couple other problems that you'll run into:
1. add_weight will respect the dtype when creating the variable, but does not properly set the dtype when calling the initializer. You'll have to fix that. https://github.com/keras-team/keras/blob/master/keras/engine/topology.py#L413
2. The optimizers create their variables in K.floatx() rather than the dtype of the parameters. So you'll have to fix the optimizer that you're using or write your own.

As to why NVIDIA recommends it, my impression is that the updates made to the offset and scale become so small that a float16 doesn't have the required precision i.e. the updates would round down to zero and the offset and scale would not be changed.

**Comment by flow-ra** [comment]
Great ! Thank you for the infos.

But what do you mean about "simply fixing the existing BatchNorm" ? Just creating a Lambda Layer with tf.layers.batch_normalization ? Or modify the source code directly ?

**Comment by bradklingensmith** [comment]
I was suggesting modifying the source code directly since you'll need to modify the source directly anyway to fix add_weight. I'll try to clean up my local copy and get something pushed up to my fork.

**Comment by flow-ra** [comment]
Okay sure, I'll  try to do modify the source code as well. Thank you for your advice.

**Comment by bradklingensmith** [comment]
I've got float16 support for the tensorflow backend working fairly well here: https://github.com/bradklingensmith/keras/tree/batchnorm_float16_support

**Comment by flow-ra** [comment]
Hi,
I've pulled your fork and it works great ! I only had an issue with a custom metric with top_k_categorical_accuracy.
Thanks again !

**Comment by flow-ra** [comment]
Hi again,
Looks like I was a bit presumptuous, but I've got another error. The loss always outputs "nan", while the metric computation seems fine.
I'm trying to train a basic encoder for classification task, so the compilation is defined the most basic way as:
`model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])`

I tried to look at the code and do some modifications (cast the loss to K.floatx() for example) but I always have "nan". Of course, when I use float32 I don't have this problem.

Do you have any idea where is the issue ? Thanks!

**Comment by lexxxel** [comment]
@flow-ra Hi,
have you changed the epsilon in your keras.json, too. I had problems with losses always going to 0.0 very fast when my epsilon was on the default: 1e-7. Without much testing, a value of 1e-3 worked for me.

**Comment by bhack** [comment]
Is there a PR?

**Comment by bhack** [comment]
Any news on this?

**Comment by aurotripathy** [comment]
I'm blocked and need help. 

@bradklingensmith , your branch works for the following (which is great). Kudos. 

```
import keras
keras.backend.set_floatx('float16')

input_layer = keras.layers.Input(shape=(16,16,3))
x = keras.layers.BatchNormalization(axis=3)(input_layer) # <<Fails here
```

Doesn't work for a resnet50 train session with https://github.com/keras-team/keras/blob/master/examples/cifar10_resnet.py

My settings
```
{
    "floatx": "float16",
    "backend": "tensorflow",
    "image_data_format": "channels_last",
    "epsilon": 1e-07
}
```

**Comment by bradklingensmith** [comment]
@aurotripathy , my first thought is that your epsilon value seems too small for float16. I'd try 1e-04 or 1e-05. But that would probably just cause poor performance rather than an outright failure. What's the specific error message?

**Comment by aurotripathy** [comment]
@bradklingensmith . Thank you for taking a look. Should have posted the first time around. 
I'm using Python3.5. 


```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/data_utils.py", line 578, in get
    inputs = self.queue.get(block=True).get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/data_utils.py", line 401, in get_index
    return _SHARED_SEQUENCES[uid][i]
  File "/usr/local/lib/python3.5/dist-packages/keras/preprocessing/image.py", line 1007, in __getitem__
    return self._get_batches_of_transformed_samples(index_array)
  File "/usr/local/lib/python3.5/dist-packages/keras/preprocessing/image.py", line 1134, in _get_batches_of_transformed_samples
    x = self.image_data_generator.random_transform(x.astype(K.floatx()))
  File "/usr/local/lib/python3.5/dist-packages/keras/preprocessing/image.py", line 884, in random_transform
    fill_mode=self.fill_mode, cval=self.cval)
  File "/usr/local/lib/python3.5/dist-packages/keras/preprocessing/image.py", line 264, in apply_transform
    cval=cval) for x_channel in x]
  File "/usr/local/lib/python3.5/dist-packages/keras/preprocessing/image.py", line 264, in <listcomp>
    cval=cval) for x_channel in x]
  File "/usr/local/lib/python3.5/dist-packages/scipy/ndimage/interpolation.py", line 458, in affine_transform
    output, order, mode, cval, None, None)
RuntimeError: data type not supported

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "cifar10_resnet.py", line 406, in <module>
    callbacks=callbacks)
  File "/usr/local/lib/python3.5/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 2192, in fit_generator
    generator_output = next(output_generator)
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/data_utils.py", line 584, in get
    six.raise_from(StopIteration(e), e)
  File "<string>", line 3, in raise_from
StopIteration: data type not supported

```

**Comment by bradklingensmith** [comment]
@aurotripathy , that looks like the ImageDataGenerator (or more specifically, one of its data augmentation functions) doesn't support float16. The easiest solution I see to that is to disable the augmentation or to write your own generator around ImageDataGenerator that requests the data from ImageDataGenerator in float32 and then converts it to float16 before passing it on.

**Comment by ldm314** [comment]
I've ran into this issue trying to use float16 as well. Is there a timeline for something to be released to make float16 usable?

**Comment by JeniaNovellusDx** [comment]
> I've got float16 support for the tensorflow backend working fairly well here: https://github.com/bradklingensmith/keras/tree/batchnorm_float16_support

Hi.. I've tried your implementation and I'm still getting the following error:

`ValueError: Tensor conversion requested dtype float32 for Tensor with dtype float16: 'Tensor("Conv_BN/Const:0", shape=(32,), dtype=float16)'
`

why?

**Comment by awmack** [comment]
I'm encountering the same error as @Golbstein (`ValueError: Tensor conversion requested dtype float32 for Tensor with dtype float16: 'Tensor("batch_normalization_1/Const:0", shape=(3,), dtype=float16)'`)

**Comment by varkonyidavid91** [comment]
Thanks, https://github.com/Golbstein/KerasExtras/blob/master/BN16.py worked! :)

**Comment by picagrad** [comment]
Hi, so I'm using the code from: https://github.com/Golbstein/KerasExtras/blob/master/BN16.py
Yet I'm still getting a "nan" loss after the first batch.
I am able to get one batch to calculate loss so I'm suspecting it has something to do with optimizer.
I tried to simplify and use SGD instead of ADAM but still nan losses.

I'm using a ImageDataGenerator, but it's only used as a loader. attaching some code snippets for clarification:
Classifier definition (based on given parameters for architecture):

```
Y = Input(batch_shape = (None, 224,224,3))
c = Conv2D(feature_sizes[0], kernel_size=kernel_sizes[0], padding = 'same', strides = (2,2))(Y)
c = BNlayer()(c)
x = LeakyReLU(alpha = 0.2)(c)	
for fs, ks,ds,spl,mrg in zip(feature_sizes, kernel_sizes,down_sample, res_split, res_merge):
	if not ds:
		c = Conv2D(fs, kernel_size=ks, padding = 'same', strides = (1,1))(x)
	else:
		c = Conv2D(fs, kernel_size=ks, padding = 'same', strides = (2,2))(x)
	c = BNlayer()(c)
	c = LeakyReLU(alpha = 0.2)(c)
	if spl:
		s = c
	if mrg:
		x = Add()([s,c])
	else:
		x = c	
	x = Dropout(0.2)(x)		
x = GlobalMaxPooling2D()(x)
x = Dropout(0.5)(x)
out = Dense(1, activation = 'sigmoid' )(x)
model = Model(inputs = Y, outputs = out)
model.summary() 
return model
  
```     

Setting up generator and training:


```
K.set_floatx('float16')
K.set_epsilon(1e-5)
print(K.floatx())
	
train_datagen = ImageDataGenerator()
		
val_datagen = ImageDataGenerator()

trn_gen = train_datagen.flow_from_directory(
			trn_path,
			target_size = target_size,
			shuffle = True,
			batch_size = batch_size,
			class_mode = 'binary')
val_gen = val_datagen.flow_from_directory(
			val_path,
			target_size=target_size,
			batch_size=batch_size,
			class_mode='binary')
	
classifier = create_classifier(fs,ks,ds,spl,mrg , dct = False)	
classifier.compile(loss = 'binary_crossentropy', optimizer = 'sgd', metrics =['accuracy'])
classifier.fit_generator(trn_gen, steps_per_epoch = trn_len // batch_size, epochs = epochs,
							validation_data = val_gen, validation_steps = val_len // batch_size,
							callbacks = [ModelCheckpoint(model_path,save_best_only=True,verbose=1, monitor = 'val_acc')],
							)

```

**Comment by picagrad** [comment]
To investigate this further I have also removed all batchnorm and dropout layers from my network and still loss goes to nan after one epoch!

**Comment by lminer** [comment]
I think this is a problem with training in fp16. I thought mixed precision training was supposed to make it easier to get convergence, but I'm still unclear as to whether keras has mixed precision or half-precision training.
