### ISSUE TITLE
Tying encoder weights to decoder while implementing autoencoder in keras

### ISSUE THREAD

**Issue by renukachittimalla** [keras-team/keras#9592]
How can I use the transpose of my encoder weight matrix as the decoder in autoencoder model in Keras? Can it be done for convolutional layer? I have created an autoencoder like vgg-16 and used vgg-16 weights for the encoding part but the weights of the decoder remains untrained.Is there any way that I can transpose the weights and provide to decoder.

**Comment by mpariente** [comment]
Do you want the corresponding layers to have the same weights during training or only for inference? 
If it's only for inference, I think you can find a much simpler solution than if it's for training.

**Comment by renukachittimalla** [comment]
Yes its only for training the autoencoder and i use the encoder part for classification task.

**Comment by mpariente** [comment]
Can you provide code of the model's definition please? 
I think what you need is more the pseudo inverse than the transposed weight matrix and I'm not sure it's trivial to implement using the backend.
