### ISSUE TITLE
A model saved with Python3.5 cannot be loaded in Python3.6

### ISSUE THREAD

**Issue by Dapid** [keras-team/keras#9595]
... at least if it includes a Lambda layer.

Minimal example:

Run save_model.py on Python3.5:

```
from keras.layers import Input, Lambda
from keras.models import Model

def noop(x):
    return x

inp = Input(shape=(None, 1))
output = Lambda(noop)(inp)

model = Model(inputs=inp, outputs=output)
model.save('result.h5')
```

Loading the model from Python3.5 also works:
```
from keras.models import load_model
load_model('result.h5')
```

But Python3.6 raises a SystemError:

```
XXX lineno: 7, opcode: 0
Traceback (most recent call last):
  File "load_model.py", line 3, in <module>
    load_model('result.h5')
  File "/home/david/.virtualenvs/py36/lib/python3.6/site-packages/keras/models.py", line 243, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/home/david/.virtualenvs/py36/lib/python3.6/site-packages/keras/models.py", line 317, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "/home/david/.virtualenvs/py36/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/home/david/.virtualenvs/py36/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 144, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/david/.virtualenvs/py36/lib/python3.6/site-packages/keras/engine/topology.py", line 2524, in from_config
    process_node(layer, node_data)
  File "/home/david/.virtualenvs/py36/lib/python3.6/site-packages/keras/engine/topology.py", line 2481, in process_node
    layer(input_tensors[0], **kwargs)
  File "/home/david/.virtualenvs/py36/lib/python3.6/site-packages/keras/engine/topology.py", line 619, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/david/.virtualenvs/py36/lib/python3.6/site-packages/keras/layers/core.py", line 663, in call
    return self.function(inputs, **arguments)
  File "save_model.py", line 7, in self_outer
    return x
SystemError: unknown opcode
```

Contrary to what was stated in bug #7297, the problem is indeed in Keras, since the error is triggered before any call to the backend. The problem appears in both Tensorflow and Theano. Also, both in Keras 2.1.5 and master.

**Comment by tadbeer** [comment]
Similar issue occurs when loading a python 3.5 built model on a python 3.6 notebook in Google Colab. Is there any workaround?
Also, does doing the procedure other way round cause errors too, i.e. loading a python 3.6 built Keras model on python 3.5.
I need to operate in a python 3.5 anaconda environment built on my local machine only, because tensorflow-gpu is currently supported for python 3.5 only.

**Comment by Dapid** [comment]
@tadbeer the best way is to save the architecture as code, and the weights in an h5. This will be compatible across versions.

Saving on yaml or json will only work across versions if you don't have Lambda layers.

**Comment by HenryJia** [comment]
Is there any workarounds when saving the model as code is difficult or awkward to do?

**Comment by fchollet** [comment]
A Lambda layer contains arbitrary code. That is not safely serializable, at all.

We serialize this arbitrary code on a best-effort basis. There are no guarantees whatsoever that it will be loadable on a different system or a different Python version.

In order to safely serialize a custom expression, you need to store its code somewhere. Not as bytecode -- you need the original source code.

So you can do:

1) Keep the code around and just save the weights. As you said:

> save the architecture as code, and the weights in an h5. This will be compatible across versions

2) Create a custom layer with a `get_config` method that serializes it (optionally a custom `from_config`). When you load the model's config, use a `CustomObjectScope` to specify your custom layer class.

**Comment by Ab-Abdurrahman** [comment]
Hi!
In my case, I had a Lambda layer as I built a siamese network. I have tried to save model architecture as a JSON and model weights separately but still, I was receiving errors when loading both models from JSON and its weights (model.load_weights('siamese_model.h5')) even though I trained and test the model on TensorFlow 2.3.0 with python 3.8.

The workaround was to rebuild my architecture and then use model.load_weights('trained_model.h5'). More detailed in [here](https://blog.paperspace.com/working-with-the-lambda-layer-in-keras/)

Detailed example
# Training the model
![image](https://user-images.githubusercontent.com/12384166/101754878-2ff3ff00-3b0f-11eb-8320-ae7b280d4727.png)

# do preprocessing of your inputs
.....
# Then compile the model
![image](https://user-images.githubusercontent.com/12384166/101755811-4b133e80-3b10-11eb-9282-63edcceafcb1.png)

# do the training
![image](https://user-images.githubusercontent.com/12384166/101755292-a690fc80-3b0f-11eb-9fe2-e56b54172ae2.png)

# save your trained model weights
![image](https://user-images.githubusercontent.com/12384166/101755351-b7da0900-3b0f-11eb-98c4-6fa59b2c97af.png)

# to load the model for future use first rebuild ur model again
![image](https://user-images.githubusercontent.com/12384166/101755865-59615a80-3b10-11eb-8fdd-95f7a70a256b.png)

# and then call model.load_weights('')
![image](https://user-images.githubusercontent.com/12384166/101756086-9c233280-3b10-11eb-8d6f-18af0a9dc540.png)

The important part is model.save_weights('trained_model.h5'), rebuilding the architecture from codes and model.load_weights('trained_model.h5')

**Comment by bigorange-1** [comment]
> Hi! In my case, I had a Lambda layer as I built a siamese network. I have tried to save model architecture as a JSON and model weights separately but still, I was receiving errors `(SystemError: unknown opcode)` when loading both models from JSON and its weights (model.load_weights('siamese_model.h5')) even though I trained and test the model on TensorFlow 2.3.0 with python 3.8.
> 
> The workaround was to rebuild my architecture and then use model.load_weights('trained_model.h5'). More detailed in [here](https://blog.paperspace.com/working-with-the-lambda-layer-in-keras/)
> 
> Detailed example
> 
> # Training the model
> ![image](https://user-images.githubusercontent.com/12384166/101754878-2ff3ff00-3b0f-11eb-8320-ae7b280d4727.png)
> 
> # do preprocessing of your inputs
> .....
> 
> # Then compile the model
> ![image](https://user-images.githubusercontent.com/12384166/101755811-4b133e80-3b10-11eb-9282-63edcceafcb1.png)
> 
> # do the training
> ![image](https://user-images.githubusercontent.com/12384166/101755292-a690fc80-3b0f-11eb-9fe2-e56b54172ae2.png)
> 
> # save your trained model weights
> ![image](https://user-images.githubusercontent.com/12384166/101755351-b7da0900-3b0f-11eb-98c4-6fa59b2c97af.png)
> 
> # to load the model for future use first rebuild ur model again
> ![image](https://user-images.githubusercontent.com/12384166/101755865-59615a80-3b10-11eb-8fdd-95f7a70a256b.png)
> 
> # and then call model.load_weights('')
> ![image](https://user-images.githubusercontent.com/12384166/101756086-9c233280-3b10-11eb-8d6f-18af0a9dc540.png)
> 
> The important part is model.save_weights('trained_model.h5'), rebuilding the architecture from codes and model.load_weights('trained_model.h5')
> 
> Addition: To extract embedding from the trained model please see my post [#8748 (comment)](https://github.com/keras-team/keras/issues/8748#issuecomment-743154533)

hello, i read your code. But i can't understand why you use the ModelCheckpoint callback function. it seems you don't use the ".ckpt". Could you tell me the reason? Thanks
