### ISSUE TITLE
RuntimeError: CUDNN_STATUS_MAPPING_ERROR

### ISSUE THREAD

**Issue by TeeyoHuang** [keras-team/keras#9604]
>>> torch.__version__
'0.3.0.post4'
Ubuntu 16.04
Python 3.6

My program will get this RuntimeError at a random iteration, like this time it breaks at the the 23rd iteration, but other time it may break at another iteration, I don't know why it happens at a random iteration?
-------------------------------------------------------------------------------------------------------------
epoch: 1 --iterations:  =  20 of  20000  completed,  loss =  [ 4.19366646]

(poly lr policy update)-- learning rate 0.00024978623984333654

epoch: 1 --iterations:  =  21 of  20000  completed,  loss =  [ 7.06229877]

(poly lr policy update)-- learning rate 0.00024977498874587285

epoch: 1 --iterations:  =  22 of  20000  completed,  loss =  [ 2.3464725]

(poly lr policy update)-- learning rate 0.00024976373759209717
Traceback (most recent call last):
  File "train_msc.py", line 288, in <module>
    main()
  File "train_msc.py", line 261, in main
    loss.backward()
  File "/share1/home/Teeyo/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/share1/home/Teeyo/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: CUDNN_STATUS_MAPPING_ERROR

**Comment by xiaozhi0689** [comment]
I think the problem is that your **GPU is too old** to supported by PyTorch. I got the same error before and I notice that there was an UserWarning in the middle part of my log. It was solved after I changed my GPU from K420 to GTX1050Ti.
