### ISSUE TITLE
How to cleanup the GPU memory after any execution?

### ISSUE THREAD

**Issue by fgsuned** [keras-team/keras#9626]
Aftre to run form R and with KERAS library a script, the VRAM memory of the GPU is not free; if I run nvidia-smi, the VRAM of the GPU still is allocated, and it is not posible to run again the script (or any other script that uses the VRAM). I tried to cleanup the VRAM with the 'k_clean-session()' function, but VRAM still is not deallocated: Are there any way to cleanup the VRAM memory after any execution from the R/KERAS environment?

**Comment by tRosenflanz** [comment]
It is not. The only way is to shutdown the process- this is a Tensorflow issue not Keras

**Comment by Dref360** [comment]
Tensorflow always uses all the memory by default. When you call k.clear_session(), the GPUs is "cleared" so there are no ops on it, but the memory is still allocated. You can create a new graph in the same script.

**Comment by fgsuned** [comment]
That means I can run a new script/graph after the execution of K_clean_session() function? A different question: Are there any way to limit the size of the VRAM allocated by KERAS?
