### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by and-rewsmith** [keras-team/keras#9630]
**I am running Ubuntu 14.04. The exact same code works on Ubuntu 16.04. I am using python3.**

**I have tried solutions from [this issue](https://github.com/tensorflow/tensorflow/issues/17411) with no luck.**

I have tried using tensorflow 1.6, 1.5, and 1.4.

+ When using tensorflow 1.6: I'm relatively sure (no line number error) I get this output when importing keras.
+ When using tensorflow 1.5 and 1.4: I get the error at this line: 

```python
    model.add(LSTM(128, input_shape=(layers[1], layers[0]), return_sequences=True))
```

Here is some further context:

```python
def build_model(layers):
    d = 0.2
    model = Sequential()
    model.add(LSTM(128, input_shape=(layers[1], layers[0]), return_sequences=True))
    model.add(Dropout(d))
    model.add(LSTM(64, input_shape=(layers[1], layers[0]), return_sequences=False))
    model.add(Dropout(d))
    model.add(Dense(16, kernel_initializer="uniform"))
    model.add(LeakyReLU(alpha=0.3))
    model.add(Dense(layers[2], kernel_initializer="uniform"))
    model.add(LeakyReLU(alpha=0.3))
    #adam = optimizers.Adam(lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=0.0)
    model.compile(loss='mse', optimizer="rmsprop", metrics=['accuracy'])
    return model
```

**Comment by tRosenflanz** [comment]
Is this PowerPc (Minsky) by any chance? Do you get the core dump if you do lstm of size 1? How about of size 2000?

I spent along time debugging a similar issue - I think BLAS was at fault which was extremely hard to pinpoint

**Comment by and-rewsmith** [comment]
I stopped using a virtualenv and everything started working with tensorflow 1.5. No idea why.
