### ISSUE TITLE
https://keras.io/backend/: rendering bug

### ISSUE THREAD

**Issue by jeehoonkang** [keras-team/keras#9633]
In https://keras.io/backend/, it seems the phrase "Reset graph identifiers." is rendered bigger than expected.  I'm attaching a screenshot.

![reset-graph-identifiers](https://user-images.githubusercontent.com/1201316/37323283-14f3a2b0-26c6-11e8-9fd5-24bd493abbc9.png)

**Comment by skrcode** [comment]
This is the intended layout. "Reset graph identifiers" is of type h2 and "reset_uids" and "clear_session" are of type h3. "clear_session" is a subcategory of "Reset graph identifiers" and "reset_uids" is a subcategory of "Backend functions".

**Comment by jeehoonkang** [comment]
@skrcode I'd like to say "Reset graph identifiers." should be the description of the `reset_uids` backend API, not a higher-level item in the documentation.  Other higher-level items are "Keras backends", "Backend functions", etc:

![image](https://user-images.githubusercontent.com/1201316/37859533-618f622c-2f58-11e8-818b-026b120e0e6a.png)
