### ISSUE TITLE
Keras expand_dims error : no attribute named _keras_history

### ISSUE THREAD

**Issue by shantanusingh16** [keras-team/keras#9636]
Hi,

I'm currently using keras (2.1.5) with tensorflow(1.5.0) as backend.
I'm trying to use the functional api of keras to build a model and for one of the layers, I use the expand_dims function of the keras.backend. This function returns a tensor that has no attribute named '_keras_history' which causes error when creating the model object.

```
from keras.backend import expand_dims
from keras.layers import Input
a = Input(shape=[2,2])
b = expand_dims(a,-1)
print(b._keras_history)
```

Regards,
Shantanu

**Comment by Dref360** [comment]
Use a Lambda layer to wrap this function
