### ISSUE TITLE
Optimizing multi_gpu_model

### ISSUE THREAD

**Issue by srjoglekar246** [keras-team/keras#9647]
Opening this to discuss possible optimizations to `multi_gpu_model`.

Based on the [code](https://github.com/keras-team/keras/blob/master/keras/utils/multi_gpu_utils.py), heres a few ideas I could think of:

1. Limiting the number of GPUs to a fewer number, in case the model is small (<400k params, as described in the [analysis doc](https://github.com/rossumai/keras-multi-gpu/blob/master/blog/docs/measurements.md)). However, this might not fit well for users who still want to try out parallelization (maybe provide an `optimize` param?)

2. As far as I understand, the ops created in `def get_slice(data, i, parts)` get added to individual GPUs as a result of `with tf.device`. Would it make sense to place them on the CPU instead? (and only do the core model running on the GPUs)

Are there any other ideas on how to go about this?
There's also the idea of auditing TF behavior to check if sub-batches indeed run on the devices they were assigned to. I could not find any documentation on how/why to achieve this.

I am kinda new to Keras, so I might be missing something trivial :-)

**Comment by srjoglekar246** [comment]
@fchollet FYI

**Comment by pusj** [comment]
For analysis of time series unsing LSTM's and ,  `get_slice()` does work as intended when >1 GPU is used (which is sort of the idea...). Sequence bucketing might be a way to solve this (https://arxiv.org/ftp/arxiv/papers/1708/1708.05604.pdf) but is this is an optimal way of doing this requires more analysis.
