### ISSUE TITLE
How to keep some of the layers of a Keras model, and save as a new model?

### ISSUE THREAD

**Issue by Derekkk** [keras-team/keras#9648]
For example, I trained a siamese network. Now I want to abandon Embedding layer, what should I do?

I tried code as following:

```
model = load_model(model_path)
input_a = Input(shape=[None, 30, 256], dtype='int32') # Keep the shape the same as following layer
input_b = Input(shape=[None, 30, 256], dtype='int32') # Keep the shape the same as following layer
non_embed_model = Model(input=[input_a, input_b], output=model.output)

```
but it doesn't work. So anyone knows how to do this? Thanks a lot!

**Comment by Vijayabhaskar96** [comment]
You should connect those input layers to the loaded model first.

**Comment by Derekkk** [comment]
@Vijayabhaskar96 Thanks for replying, but can you please give some more detailed explanations? Still quite confused. Thank you

**Comment by Vijayabhaskar96** [comment]
Well, Load the model, get the layers(if you don't know the exact layer names,print the model summary) that are connected to the embedding layers, assign the input_a and input_b as the input of those layers, For example,if layerX1 and layerX2 are the successive layers of embedding layers 1 and 2, then assign 
`model.get_layer("layerX1").input=input_a`
`model.get_layer("layerX2").input=input_b`
then,  `non_embed_model = Model(input=[input_a, input_b], output=model.output)`

**Comment by lucasdavid** [comment]
@Vijayabhaskar96 solution raised the following error for me:
```
    model.get_layer('fc1').input = meta_input
AttributeError: can't set attribute
```

@Derekkk I had this very problem once. My Siamese model's legs were InceptionV3 networks and It was getting pretty difficult to fit everything in memory with an acceptable `batch_size`. I haven't found easy solutions for this and I don't **think** they exist: simply replacing the inputs would violate the immutability principle common in functional paradigm in which tensorflow/keras are built.

The way I solved this: I rebuilt the shared part of the network, layer by layer. For example, let's say your siamese `model` looks like this:
```python
from keras import Input, Model
from keras.layers import Dense, merge
from keras.applications import InceptionV3

a, b = Input(shape=(299, 299, 3)), Input(shape=(299, 299, 3))
base = InceptionV3(weights='imagenet')
ya, yb = base(a), base(b)
y = merge([ya, yb], mode='concat', name='joint')
y = Dense(4096, activation='relu', name='fc1')(y)
y = Dense(4096, activation='relu', name='fc2')(y)
y = Dense(4096, activation='softmax', name='predictions')(y)
model = Model(inputs=[a, b], outputs=y)
```
So what you need to do is find the first layer that would receive your new inputs (`joint`, in my example) and re-call each layer one by one:
```python
ya, yb = Input(shape=(2048,)), Input(shape=(2048,))  # new inputs.
y = x = [ya, yb]

shared_starts_at = model.layers.indexof(model.get_layer('joint'))
for layer in model.layers[shared_starts_at:]:
    y = layer(y)
model = Model(inputs=x, outputs=y)
```

This can become a mess if you have multiple outputs too, but it's still doable.

**Comment by gabrieldemarmiesse** [comment]
The right solution is in the documentation https://keras.io/applications/

```python
from keras.applications.vgg19 import VGG19
from keras.preprocessing import image
from keras.applications.vgg19 import preprocess_input
from keras.models import Model
import numpy as np

base_model = VGG19(weights='imagenet')
model = Model(inputs=base_model.input, outputs=base_model.get_layer('block4_pool').output)

img_path = 'elephant.jpg'
img = image.load_img(img_path, target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

block4_pool_features = model.predict(x)
```

You can get the layer by index too by doing `model.layers[10].output` for example.

**Comment by Derekkk** [comment]
@Vijayabhaskar96 Yea, I got the same error as @lucasdavid said. The solution provided by Lucas seems tricky for me, I'll give a try.

**Comment by Derekkk** [comment]
@gabrieldemarmiesse Thanks for replaying, but I think the code you provided is about how to get the outputs of the intermediate layer. What I want to ask is how to abandon the Embedding layer and change the Input. For example, the model is trained by an embedding layer, but when I call the model, I want to abandon embedding layer and write the embedding on my own. I tried to define an Input layer and connect it to the layer after embedding, but it doesn't work. So I wonder if there is any other ways to solve this. Massive thanks for replying tho.

**Comment by gabrieldemarmiesse** [comment]
Sorry, I didn't understand the question. As inputs to keras models must be Input layers, it seems impossible to do it automatically at the moment. So your best bet is to do it manually. It's sad because the function run_internal_graph in keras.engine.topology.py would do exactly what you want, but if it's impossible to create a model, it's impossible to use this function. Maybe a PR would solve this.

**Comment by lucasdavid** [comment]
@gabrieldemarmiesse I think this would be a very useful addition.

**Comment by gabrieldemarmiesse** [comment]
I can't really do it right now. Maybe someone from the keras team could put a label on this issue 'contributions welcome'?

**Comment by Derekkk** [comment]
@gabrieldemarmiesse Intuitively I feel like it should work. The saved model contains graph and weights. So I think as long as I can feed the vectors with the same shape to some intermediate layer, it should work. But I haven't read the source code of this part so this is just a guess. But as @lucasdavid mentioned, this should be a very useful function.
