### ISSUE TITLE
preprocessing images

### ISSUE THREAD

**Issue by hainguyenct** [keras-team/keras#9668]
Dear all,
I am wondering what are differences between preprocess_input of VGG (vgg16,vgg19) and resnet50?
(https://faroit.github.io/keras-docs/1.2.2/applications/)
Why do we need to use preprocess_input? I experimented with images using preprocess_input and without using it on 6 datasets. 4 of them used preprocess_input gave better results while the others showed worse performance.
Any one could explain these? Thank you.

**Comment by korytmar** [comment]
Hi,
I'd like to enlarge this issue. My questions are:
Should I always use preprocess_input, when I am fine-tuning pre-trained net?
Should I preprocess all my data or just training set?

According to http://cs231n.github.io/neural-networks-2/, data preprocessing is applied only on training set, but I'm not sure, if this is the case.
Thanks in advance.
- - - 
It is obvious, if you feed your net with values, which range is different to range which was used for training, that result is supposed to be worse. Your experiment just proved that.

**Comment by hainguyenct** [comment]
For images, you could preprocess_input for each image separately
