### ISSUE TITLE
TimeseriesGenerator usage

### ISSUE THREAD

**Issue by JustM57** [keras-team/keras#9669]
It's great that preprocessing sequences for lstm is so easy now, but how actually to use the result? I mean, each element of it actually returns 2 numpy arrays. The first one is reshaped features batch and the second is y batch. We can adress each of the arrays by doing this indexing: reshaped_data[rand_int][0 or 1], but trying to split the data into features tensor and y tensor doesn't word. This object doesn't support slices. After that I've tried to put it to Keras model as it is: model.fit(data_gen, validation_data = 0.075, shuffle = False), but got an error: AttributeError: 'TimeseriesGenerator' object has no attribute 'ndim'
Could you add an example how to use it during the model fit?

**Comment by Dref360** [comment]
A Sequence cannot be split. You need to create 2 TimeseriesGenerator : 1 for train and 1 for validation.

**Comment by lucasdavid** [comment]
Also, you need to use `model.fit_generator` instead of `model.fit`.
