### ISSUE TITLE
Is it possible to customize Keras Tokenizer language to take into account French peculiarities

### ISSUE THREAD

**Issue by ahmedbesbes** [keras-team/keras#9681]
Hello,

I'm trying to build a sentiment analysis model in french using Keras on top of Tensorflow. 

However, Keras doesn't handle french tokenization (unlike Spacy for instance)
The Tokenizer object only handles english words.

I tried to plug Keras to Spacy but there's no clear and understandable documentation on that.

Basically this is what I want to perform in french:

```python
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(num_words=MAX_NB_WORDS)

tokenizer.fit_on_texts(data['clean_text'].head(n)) # here's where the english tokenization takes place.  there seems no way to easily adapt it to french

train_sequences = tokenizer.texts_to_sequences(data['clean_text'].iloc[:n])
test_sequences = tokenizer.texts_to_sequences(data['clean_text'].iloc[n:])

```
Any help would be appreciated.

**Comment by jwross24** [comment]
Sorry for the very untimely reply, but I've been running into the same issue with trying to tokenize/segment Chinese text. You can supply the `Tokenizer` object with a custom `analyzer` function to return a list of tokens according to your specified language.

For example:
```
def my_tokenize_function(text):
    # tokenize text according to your language
    token_list = ...
    return token_list

tokenizer = Tokenizer(num_words=MAX_NB_WORDS, analyzer=my_tokenize_function)
```

**Comment by KhanShahed1NWPU** [comment]
> Sorry for the very untimely reply, but I've been running into the same issue with trying to tokenize/segment Chinese text. You can supply the `Tokenizer` object with a custom `analyzer` function to return a list of tokens according to your specified language.
> 
> For example:
> 
> ```
> def my_tokenize_function(text):
>     # tokenize text according to your language
>     token_list = ...
>     return token_list
> 
> tokenizer = Tokenizer(num_words=MAX_NB_WORDS, analyzer=my_tokenize_function)
> ```

can you give me your full function?
I am kinda lost doing the same thing with Chinese language
