### ISSUE TITLE
Multiple Input Load Model Problem- Missing Input

### ISSUE THREAD

**Issue by e181978** [keras-team/keras#9688]
Hello,
I builded two inputs and one output model. After some epoch, i saved model with below code.
`model.save('weightedModel.h5')`.

Then, i  try to load model with below code.
`model = load_model("weightedModel.h5", custom_objects={'loss': w_categorical_crossentropy(w_array) }) `

This is my generator:
```
def generate_data_generator(generator, X1, X2, Y, batch_size):
    genX1 = generator.flow(X1,Y ,seed=7, batch_size = batch_size)
    while True:
      Xi = genX1.next() 
      yield [Xi[0],X2[:Xi[0].shape[0],:]], Xi[1]
```

After calling load_model, above generate_Data_generator functions gives error :

>  "ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 1 array(s), but instead got the following list of 2 arrays:"

When i changed to  last lines of generate_data_generator function to `yield [Xi[0],Xi[1]]`, it doesn't give any error. Problem is that  my defined model has two inputs, but after loading model, it works only one input. What is the reason of this? 

Thanks in advance.

**Comment by hr0nix** [comment]
@e181978 Did you manage to fix the problem?
