### ISSUE TITLE
Applying LSTM after CNN for EEG signals

### ISSUE THREAD

**Issue by jdhurwitz** [keras-team/keras#9695]
I am doing 4-class classification on EEG signals. I have the following data:
2558 trials
22 channels of data (from 22 electrodes)
1000 time steps per trial.

I've tried just raw LSTM with some basic preprocessing, including discrete wavelet transform and my validation accuracy doesn't get over 27%. I'd like to use a 2D conv layer to do feature selection on my data before passing it to a recurrent layer. However, I'm not sure how I should reshape my data to work with keras. My first thought was just to create a dummy channel of size 1 in order to make the tensor 4D with the following dims: 
(2558, 1, 22, 1000)

In this reshaped tensor, height is the number of channels and width is the time steps. I'm not sure if that's an optimal config but I figured it would be an ok starting point.

But I got the following error:

> Negative dimension size caused by subtracting 3 from 1 for 'time_distributed_4/convolution' (op: 'Conv2D') with input shapes: [?,1,22,1000], [3,3,1000,32].

I read online that then expects dimensions NCHW, but keras + tf backend expects NHWC. So I tried reshaping into NHWC: (2558, 22, 1000, 1). The error went away but now I have a new one:

> ValueError: Error when checking input: expected time_distributed_34_input to have 5 dimensions, but got array with shape (2046, 22, 1000, 1)

I'm not sure what the 5th dimension would be?

------
Here is the code I attempted:

```
num_filters=32
kernel=(3,3)
output_classes=4
batch_size=64

model=Sequential()

model.add(TimeDistributed(
    Conv2D(num_filters, kernel), input_shape=[2558,22,1000,1])
    )
model.add(TimeDistributed(Activation("relu")))
model.add(TimeDistributed(MaxPooling2D(pool_size=(2,2))))
model.add(TimeDistributed(Flatten()))
model.add(TimeDistributed(Dropout(0.25)))
model.add(LSTM(units=100))
model.add(Dense(output_classes))
model.add(Activation("softmax"))
```

**Comment by birolkuyumcu** [comment]
this is not isuue
try 1D conv
