### ISSUE TITLE
use multi-cores for keras cpu

### ISSUE THREAD

**Issue by hainguyenct** [keras-team/keras#9710]
Dear all,
I would like to use 10 cores of cpu to run my model keras. 
However, when I run my code, only two - three cpus are using 100%, the others is sleeping
![screen shot 2018-03-20 at 11 54 19](https://user-images.githubusercontent.com/17986080/37650561-937dfcc4-2c35-11e8-967e-02541f2756db.jpg)

Anyone know the way to distribute the work to all cores?
Thank you.

**Comment by frankgh** [comment]
If you are using TF as the backend you can try the following:

```
config = tf.ConfigProto(device_count={"CPU": 8})
keras.backend.tensorflow_backend.set_session(tf.Session(config=config))
```

Let me know if that works

**Comment by frankgh** [comment]
You could also try this: 
https://stackoverflow.com/questions/41588383/how-to-run-keras-on-multiple-cores

**Comment by hainguyenct** [comment]
"8" means the number of distributed cores?

**Comment by frankgh** [comment]
correct

**Comment by hainguyenct** [comment]
I tried with 
```
if options.nthread>0:
    config = tf.ConfigProto(device_count={"CPU": options.nthread})
    kr.backend.tensorflow_backend.set_session(tf.Session(config=config))
    sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
    print sess
```
but the result does not improve
![screen shot 2018-03-20 at 22 28 04](https://user-images.githubusercontent.com/17986080/37683840-2194b6e4-2c8e-11e8-9cef-715b03ce490a.jpg)

**Comment by sicklife** [comment]
any update? my code on aws deep learning machine also meet with this problem.

**Comment by ivanlen** [comment]
I am having the same issue under using different versions of python and keras in different machines.
I can't configure it to use all the resources.

**Comment by tuskiomi** [comment]
Again same issue. Perhaps certain elements are single core only (eg convolution)?

**Comment by wangyexiang** [comment]
any update?

**Comment by Jonathanpro** [comment]
I have the same problem.
I use Tensorflow 2.0 rc with the keras backend.
But I faced the same issue on Tensorflow 1.4 using Tensorflow only without Keras

**Comment by Bee-zest** [comment]
Same problem here

**Comment by georgy7** [comment]
I think I found solution. Keras actually uses multiple cores out of the box, but you may have a bottleneck in the generators.

Steps to fix this:

1. Make your generators thread-safe.
2. Don't use global variables in your generators (because of GIL).
3. Ensure, your generators fast enough.

Example:

```
class DataPurpose(Enum):
    TRAINING = 1
    VALIDATION = 2

class RandomBlockSource:
    # You may use global variables only on an object instansiation.
    # If you need some global collection here, just copy it.
    # For instance:
    my_list = global_list.copy()

    def get_data(self, purpose: DataPurpose):
        pass  # TODO

def multithreaded_get_training_block(i):
    block_source = RandomBlockSource()
    return block_source.get_data(DataPurpose.TRAINING)


def multithreaded_get_validation_block(i):
    block_source = RandomBlockSource()
    return block_source.get_data(DataPurpose.VALIDATION)

@threadsafe_generator
def training_generator(batch_size):
    pool = ThreadPool()
    while (True):
        inputs, outputs = numpy.zeros((batch_size, INPUT_BLOCK_HEIGHT, INPUT_BLOCK_WIDTH, 1)), \
                          numpy.zeros((batch_size, OUTPUT_BLOCK_HEIGHT, OUTPUT_BLOCK_WIDTH, 1))

        # The bottleneck.
        pairs = pool.map(multithreaded_get_training_block, range(batch_size))

        for i, pair in enumerate(pairs):
            inputs[i][:, :, 0] = pair[0]
            outputs[i][:, :, 0] = pair[1]

        yield inputs, outputs


@threadsafe_generator
def validation_generator(batch_size):
    pool = ThreadPool()
    while (True):
        inputs, outputs = numpy.zeros((batch_size, INPUT_BLOCK_HEIGHT, INPUT_BLOCK_WIDTH, 1)), \
                          numpy.zeros((batch_size, OUTPUT_BLOCK_HEIGHT, OUTPUT_BLOCK_WIDTH, 1))

        # The bottleneck.
        pairs = pool.map(multithreaded_get_validation_block, range(batch_size))

        for i, pair in enumerate(pairs):
            inputs[i][:, :, 0] = pair[0]
            outputs[i][:, :, 0] = pair[1]

        yield inputs, outputs

history = model.fit_generator(
    training_generator(16), steps_per_epoch=200, nb_epoch=epochs,
    validation_data=validation_generator(8), validation_steps=4, validation_freq=1,
    workers=8)
```

**Comment by georgy7** [comment]
Also, instead of using complex generators, you may create an index on data set in a database and then:

```
select ... limit batch_size
```

**Comment by liduang** [comment]
Dear sir，how to solve this problem?@hainguyenct。I have the same problem

**Comment by koestlerWang** [comment]
tensorflow serving for keras may solve this problem

**Comment by tuskiomi** [comment]
I can confirm that tensorflow does speed up the process, but the bottleneck remains.

**Comment by VoSiLk** [comment]
Is there some progress in this topic, because I face the same problem and don't know how to solve it.
