### ISSUE TITLE
ValueError: None values not supported. - Custom Loss Function.

### ISSUE THREAD

**Issue by Polychemy** [keras-team/keras#9712]
Im getting this error on my custom loss function :  _ValueError: None values not supported._

The out put is a 2d array of binary digits (2000,2).
 I need to calculate the accuracy on certain entries only, not the entire set.

Here's my loss function and how i did it:

```
def getBalance(x_true, x_pred):

    ##Selected entries for calculation
    trade_index = K.tf.not_equal(x_pred[:,1], 0 )
    
    x_true_tradeable  = K.tf.boolean_mask(x_true[:,0], trade_index)
    x_pred_tradeable  = K.tf.boolean_mask(x_pred[:,0], trade_index)
    
    
    cm = K.tf.confusion_matrix(x_true_tradeable, x_pred_tradeable)
    
    
    correctPredictions = cm[0,0]+cm[1,1]
    wrongPredictions = cm[1,0]+cm[0,1]
    TotalTrades = correctPredictions+wrongPredictions
    Accuracy = (correctPredictions/TotalTrades)*100
    
    
    Accuracy = K.tf.cast(Accuracy, K.tf.float32)
    
    return Accuracy
```

I get the above mentioned error. Here is my model for reference:

```
model = Sequential()
model.add(Dropout(0.4, input_shape=(train_input_data_NN.shape[1], train_input_data_NN.shape[2])))
model.add(LSTM(30, dropout=0.4, recurrent_dropout=0.4,  return_sequences=False))
model.add(Dense(2))
model.compile(loss='getBalance', optimizer='adam')
history = model.fit(train_input_data_NN, outputs_NN, epochs=50,  batch_size=64, verbose=1, validation_data=(test_input_data_NN, outputs_NN_test))
```

The inputs are a multi-variant multi-timestep time series.
What might be wrong?

**Comment by Polychemy** [comment]
Ok i solved it, my outputs were pandas data-frame instead of numpy array.
I convert the data-frame to numpy and it worked. Like so:

outputs_NN_test = np.array(outputs_NN_test )

**Comment by Dref360** [comment]
You loss is not differentiable

**Comment by Polychemy** [comment]
what does that mean? Is it possible to make a loss to archive this type of objective?

**Comment by Dref360** [comment]
To perform gradient descent, you need a differentiable loss.
This : 
`cm = K.tf.confusion_matrix(x_true_tradeable, x_pred_tradeable)` isn't differentiable.

I'll close since it's not a Keras issue.
