### ISSUE TITLE
Handle a lot of data

### ISSUE THREAD

**Issue by mgp1994** [keras-team/keras#9714]
Hello,

I am doing a two stream neural netowork where my data are videos and  feature vectors. I have got more than 50.000 samples and apart from that I have to do a preprocess. I am using Spyder IDE and when I load 5.000 samples into a matrix it shows that I am close to out of memory ram. 

Is there any form to load into a matrix all data without out of memory?

Thanks!!

**Comment by nthakor** [comment]
Try [Tensorflow Dataset API](https://www.tensorflow.org/programmers_guide/datasets)
[Here](https://medium.com/@chengweizhang2012/an-easy-guide-to-build-new-tensorflow-datasets-and-estimator-with-keras-model-9b0f6b4c1b0d) is a quick tutorial to integrate tf.data with keras.

**Comment by Dref360** [comment]
You can use `fit_generator` instead of `fit`, you just need to implement the keras.utils.Sequence which will handle your dataset.
