### ISSUE TITLE
Different input shape of model and dataset does not matter

### ISSUE THREAD

**Issue by korytmar** [keras-team/keras#9720]
I use pre-trained architecture from https://keras.io/applications/ with default input shape, but my images have different dimensions. I think that prediction must fail because of wrong input shape, but nothing happens and model has started predicting.

Is it bug or Keras does any weird things behind that I don't know?

**Comment by Ricocotam** [comment]
Tell me if I misunderstood

You built a model with input shape (x1, x2) and gave as input something different ? And it didn't fail ?

I already tried that out and I got issues. Didn't you use a generator and set parameters to have a resize ?

**Comment by korytmar** [comment]
Yeah, that's exactly what I did, but how is it possible to resize smaller image to bigger one?

Does keras fill rest with zeros or something like that?

**Comment by Ricocotam** [comment]
Could you show your code ? I'm not exactly sure what you did

**Comment by korytmar** [comment]
I have already resolve it. 

In ImageDataGenerator class is argument fill_mode, which does that miracle.
