### ISSUE TITLE
Time metric for the first epoch is not accurate

### ISSUE THREAD

**Issue by ghostplant** [keras-team/keras#9726]
Usually, for multi-epoch fitting, the first epoch usually displays around 1.5 times larger than subsequent 2nd/3rd/.. epoch on time cost. This is mainly because the first `train_on_batch()` includes the model compiling time instead of training time, so it is expected to skip metric this step.

**Comment by skrcode** [comment]
Yes. It does take more time initially to compile the model.
training.py Line: 1236 `outs = f(ins_batch)`
What do you reckon is the right approach to skip this? It would not be right to skip it in the first epoch, since we would lose the delta(total time - compile time = time taken to get `outs`) along with it.

**Comment by tRosenflanz** [comment]
Is it possible to do 1 predict_on_batch before training and output 2 lines for the first epoch:
`Compilation time: X seconds`
`Epoch 1: Y seconds`

**Comment by ghostplant** [comment]
According my try, doing 1 predict_on_batch along doesn't help, but doing 1 train_on_batch will fix it, however, it is possible to update the weights of model with 1 extra mini-batch.

**Comment by ghostplant** [comment]
I think the ugly but working solution to satisfy all existing procedure, is to do things as follows at the beginning of the first epoch:

1) pre-fetch one mini-batch from generator as `insA`;
2) store the current model weights;
3) train_on_batch(insA);
4) recovery the current model weights;
5) do formal training afterwards while marking the first mini-batch training to use pre-fetched `insA` instead of generating a second batch from generator;
