### ISSUE TITLE
Question about building DeconvNet

### ISSUE THREAD

**Issue by kagan94** [keras-team/keras#9735]
Hello.

I've tried to build a similar network to **DeconvNet** for the image segmentation, but I stacked on defining the fully connected layers in the middle of the net.  
![image](https://user-images.githubusercontent.com/11237421/37824271-ba2b2822-2e94-11e8-8f93-4c0895ac70bc.png)
  
The structure of the net I am trying to build is taken from [this article](https://arxiv.org/pdf/1505.04366.pdf)  
![image](https://user-images.githubusercontent.com/11237421/37824224-982875cc-2e94-11e8-956d-0084aab52d9e.png)
  
My code is the following:  
`def build(width, height, depth, classes):
    inputShape = (height, width, depth)
    if K.image_data_format() == "channels_first":
        inputShape = (depth, height, width)

    kernel = 3
    pool_size = (2, 2)
    # droprate = 0.25

    encoding_layers = [
        Conv2D(64, (kernel, kernel), padding='same', input_shape=inputShape),
        Activation('relu'),
        Conv2D(64, (kernel, kernel), padding='same'),
        Activation('relu'),
        MaxPooling2D(pool_size),

        Conv2D(128, (kernel, kernel), padding='same'),
        Activation('relu'),
        Conv2D(128, (kernel, kernel), padding='same'),
        Activation('relu'),
        MaxPooling2D(pool_size),

        Conv2D(256, (kernel, kernel), padding='same'),
        Activation('relu'),
        Conv2D(256, (kernel, kernel), padding='same'),
        Activation('relu'),
        Conv2D(256, (kernel, kernel), padding='same'),
        Activation('relu'),
        MaxPooling2D(pool_size),

        Conv2D(512, (kernel, kernel), padding='same'),
        Activation('relu'),
        Conv2D(512, (kernel, kernel), padding='same'),
        Activation('relu'),
        Conv2D(512, (kernel, kernel), padding='same'),
        Activation('relu'),
        MaxPooling2D(pool_size),

        Conv2D(512, (kernel, kernel), padding='same'),
        Activation('relu'),
        Conv2D(512, (kernel, kernel), padding='same'),
        Activation('relu'),
        Conv2D(512, (kernel, kernel), padding='same'),
        Activation('relu'),
        MaxPooling2D(),

        Flatten(), # todo: double-check
        Dense(4096),
        Activation("relu"),

        Dense(4096),
        Activation("softmax"),
    ]

    model = Sequential()
    model.encoding_layers = encoding_layers

    for l in model.encoding_layers:
        model.add(l)
        print(l.input_shape, l.output_shape, l)

    decoding_layers = [
        # Deconv2D(512, (7, 7)),
        UpSampling2D(size=(2, 2)),  # (!!!) this throws the error

        Deconv2D(512, (kernel, kernel), padding='same'),
        Activation('relu'),
        Deconv2D(512, (kernel, kernel), padding='same'),
        Activation('relu'),
        Deconv2D(512, (kernel, kernel), padding='same'),
        Activation('relu'),
        UpSampling2D(size=(2, 2)),

        Deconv2D(512, (kernel, kernel), padding='same'),
        Activation('relu'),
        Deconv2D(512, (kernel, kernel), padding='same'),
        Activation('relu'),
        Deconv2D(256, (kernel, kernel), padding='same'),
        Activation('relu'),
        UpSampling2D(size=(2, 2)),

        Deconv2D(256, (kernel, kernel), padding='same'),
        Activation('relu'),
        Deconv2D(256, (kernel, kernel), padding='same'),
        Activation('relu'),
        Deconv2D(128, (kernel, kernel), padding='same'),
        Activation('relu'),
        UpSampling2D(size=(2, 2)),

        Deconv2D(128, (kernel, kernel), padding='same'),
        Activation('relu'),
        Deconv2D(64, (kernel, kernel), padding='same'),
        Activation('relu'),
        UpSampling2D(size=(2, 2)),

        Deconv2D(64, (kernel, kernel), padding='same'),
        Activation('relu'),
        Deconv2D(64, (kernel, kernel), padding='same'),
        Activation('relu'),

        UpSampling2D(size=(2, 2)),
        Conv2D(classes, (1, 1), padding='valid'),
    ]
    model.decoding_layers = decoding_layers
    for l in model.decoding_layers:
        model.add(l)
        print(l.input_shape, l.output_shape, l)

    model.add(Reshape((classes, height * width)))
    model.add(Permute((2, 1)))
    # model.add(Activation('softmax'))  # activation_26 (Activation)   (None, 65536, 2)
    # model.add(Reshape((classes, img_h,  img_w)))

    return model`
  
The code above throws an error while trying to build the model. In particular, when adding the first layer from decoding layers.  
  
Any advice/help is appreciated 👍   
  
The error message is the following:  
```Traceback (most recent call last):  
  
  File "../code/deep_cnn/pixelwise_cnn.py", line 55, in <module>
    model = SegNet.build(img_w, img_h, depth, classes)  
  
  File "../code/deep_cnn/model_2.py", line 128, in build
    autoencoder.add(l)  
  
  File "E:\Programs\Anaconda3\lib\site-packages\keras\models.py", line 455, in add
    output_tensor = layer(self.outputs[0])  
  
  File "E:\Programs\Anaconda3\lib\site-packages\keras\engine\topology.py", line 511, in __call__
    self.assert_input_compatibility(inputs)  
  
  File "E:\Programs\Anaconda3\lib\site-packages\keras\engine\topology.py", line 413, in assert_input_compatibility
    str(K.ndim(x)))
  
ValueError: Input 0 is incompatible with layer up_sampling2d_1: expected ndim=4, found ndim=2

**Comment by MarioMontano** [comment]
Did you try to remove the leading "512" from the input shape of the Deconv2d layer?
 --> input_shape=(512, 7, 7), --> input_shape=(7, 7).

**Comment by kagan94** [comment]
@MarioMontano But it does not reach this layer. It throws an error on the first layer from deconv. layers, namely on this:
`UpSampling2D(size=(2, 2)), `

**Comment by MarioMontano** [comment]
It may need
`(UpSampling2D(size=(2, 2))` --> `(UpSampling2D(size=(2, 2), data_format, input_shape=(_, _, _,_), output_shape=(_, _, _,_)`

You are only giving `size` and the automatic data format which is `channels_last`

I am guessing this is why it returns `expected ndim=4, found ndim=2`

**Comment by mcps5601** [comment]
https://github.com/dongmeixu/Keras-DeconvNet-Segmentation/blob/debug/DeconvNet.py

This page may solve your problem.
