### ISSUE TITLE
class_weight should support lists

### ISSUE THREAD

**Issue by christian-rauch** [keras-team/keras#9737]
At the moment, `class_weight` (e.g. in `fit_generator`) is a mapping between a class id and its weight. A list also provides this mapping, i.e. the dict `{0:0.3, 1:0.5, 3:1.6}` provides the same mapping as the list `[0.3, 0.5, 1.6]`.

However, at the moment calling `fit_generator` with a list of class weights is silently ignoring the weights and continues as if no weights have been given. There should be a warning that mapping weights to classes via lists is not supported and will be ignored. In future, it would be great is class weight mapping via lists could be supported.

**Comment by mohapatras** [comment]
Yes. Keras silently moves forward ignoring it. However in general after calculating class weights I `zip` the array and convert them in to a dictionary `dict` before feeding them into the `fit_generator `. Then it works.

**Comment by christian-rauch** [comment]
@fchollet Has this been solved or is this just closed because of inactivity?
