### ISSUE TITLE
Improve Keras Documentation User Experience for Long Code Snippets By Removing The Need For Horizontal Slide Bars

### ISSUE THREAD

**Issue by jaradc** [keras-team/keras#9741]
**Category**: documentation user-experience
**Comment**: modify highlight.js <code></code> to wrap long documentation code snippets
**Why**: eliminates the need for a user to manually click and slide a horizontal slider just to get a quick sense of what available parameters and their default values are

**Context**
While reading the documentation, and coming from a scikit-learn background, I really like how their documentation shows all the class and method parameters ([example page](http://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html)). It's very helpful to quickly be able to see the default parameters.

Take [Dense](https://keras.io/layers/core/#dense) for example. If the documentation looked like this (imagine this a code block, not individually highlighted lines):

`keras.layers.Dense(units, activation=None, use_bias=True, kernel_initializer='glorot_uniform', bias_initializer='zeros', kernel_regularizer=None, bias_regularizer=None, activity_regularizer=None, kernel_constraint=None, bias_constraint=None)`

Benefits:
- easy to read
- no scrolling a horizontal slider
- immediately tells me the available parameters and their default values

Compare that experience to the current Keras experience:

```
keras.layers.Dense(units, activation=None, use_bias=True, kernel_initializer='glorot_uniform', bias_initializer='zeros', kernel_regularizer=None, bias_regularizer=None, activity_regularizer=None, kernel_constraint=None, bias_constraint=None)
```

Disadvantages:
- requires scrolling horizontally to see the rest
- easy to lose track of where you are while scrolling
- requires physical action to see everything

The Keras team no-doubt is busy with much bigger concerns than documentation formatting. One could say that the "Arguments" are all listed below or by clicking the "Source". True, however the key point I'm trying to make is usability, and quick readability. Reading through an "Argument"'s verbose description, or having to scroll horizontally is not quick nor an optimal experience.

I'm not going to make a case for why making documentation easy-to-read is important. I think the Keras documentation **content** itself is outstanding.

**Comment by fchollet** [comment]
Feel free to try to implement something like this (see `docs/autogen.py`), and if the results look better than the current setup, we'll merge it.
