### ISSUE TITLE
valueerror when using someone's code on machine learning

### ISSUE THREAD

**Issue by AnthonyTheKoala** [keras-team/keras#9747]
I like to learn about LSTMs, and following the code on that has worked for others, but not for me at https://machinelearningmastery.com/time-series-prediction-lstm-recurrent-neural-networks-python-keras/#comment-433162.  

As soon as I typed the following line:
model.fit(trainX, trainY, epochs=100, batch_size=1, verbose=2)

I get a series of valueerrors - this is the cut-down version of the error output.

TypeError: c_compile_args() takes 1 positional argument but 2 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File “C:\Python34\lib\site-packages\theano\tensor\blas.py”, line 443, in _ldflags
t0, t1, t2 = t[0:3]
ValueError: need more than 1 value to unpack

During handling of the above exception, another exception occurred:
lots of files from the Theano package were mentioned (cut out of the edit)

ValueError: (‘The following error happened while compiling the node’, forall_inplace,cpu,scan_fn}(Elemwise{maximum,no_inplace}.0, Subtensor{int64:int64:int8}.0, IncSubtensor{InplaceSet;:int64:}.0, IncSubtensor{InplaceSet;:int64:}.0, Elemwise{Maximum}[(0, 0)].0, Subtensor{::, int64:int64:}.0, InplaceDimShuffle{x,0}.0, Subtensor{::, int64:int64:}.0, Subtensor{::, :int64:}.0, InplaceDimShuffle{x,0}.0, Subtensor{::, :int64:}.0, Subtensor{::, int64:int64:}.0, InplaceDimShuffle{x,0}.0, Subtensor{::, int64:int64:}.0, Subtensor{::, int64::}.0, InplaceDimShuffle{x,0}.0, Subtensor{::, int64::}.0), ‘\n’, ‘The following error happened while compiling the node’, Dot22(, ), ‘\n’, ‘invalid token “=” in ldflags_str: “-LC:openblas -lopenblas;gcc.cxxflags = -shared -Ic:ming64winclude -Lc:python34libs -lpython34 -DMS_WIN64″‘)

This occurs even when I uninstalled Theano and successfully reinstalled using the git method on my Windows PC using the git/bash/mingw program:
pip install git+https://github.com/Theano/Theano.git#egg=Theano     

source "bleeding edge installation" at http://deeplearning.net/software/theano/install_windows.html

Any idea please.
Thank you,
Anthony from Sydney

**Comment by Dref360** [comment]
Hi!
This issue isn't related to a bug/enhancement/feature request or other accepted types of issue.

To ask questions, please see the following resources : 
* https://keras.io/
* https://keras.io/#support
* https://gitter.im/Keras-io/Lobby

Thanks!

If you think I made an error, please re-open this issue.

**Comment by AnthonyTheKoala** [comment]
I'm just a user. So how do I know whether the error output is a bug in keras or something else?  Or in other words, why cannot this be answered in this forum.
Thank you, merci
Anthony from Sydney
