### ISSUE TITLE
documentation for Dense layer doesn't list input_dim among costructor parameters

### ISSUE THREAD

**Issue by giuscri** [keras-team/keras#9755]
see https://keras.io/layers/core/#dense generated at 709f791af201caaab4aa180bda259989087cfe47

**Comment by vkk800** [comment]
In the code I find:
```
if 'input_shape' not in kwargs and 'input_dim' in kwargs:
    kwargs['input_shape'] = (kwargs.pop('input_dim'),)
```

It seems to be just a redundant way of defining the input_shape. I don't think anyone would ever need it since instead of using it you could just call Dense(input_shape=(input_dim,) instead. Maybe it's there for legacy reasons or something.
