### ISSUE TITLE
zoom_range in ImageDataGenerator uses different scales for x and y

### ISSUE THREAD

**Issue by ale152** [keras-team/keras#9758]
I noticed that ImageDataGenerator, when setting the parameter zoom_range, uses a different random transformation for the horizontal and vertical axis, which produces images with a random aspect ratio.

I checked the source code ([here](https://github.com/keras-team/keras/blob/master/keras/preprocessing/image.py#L853)) and the zoom transformation is indeed random for the horizontal and vertical axis. I think this is counterintuitive because I'm expecting a "zoom" transformation to simply magnify (or unmagnify) the input image. Instead, the output of zoom_range are images which are randomly stretched horizontally or vertically.

I suggest introducing an additional parameter like a boolean "zoom_keep_ar" (aspect ratio) which if True, keeps the aspect ratio constant (simple magnification, zx=zy=random), if False it also randomly change the aspect ratio (zx=rand, zy=rand).

**Comment by rsnitsch** [comment]
I agree. I just had the same problem. I expected the images to be only zoomed-in/zoomed-out versions of the original images, but instead the aspect ratio is manipulated.

**Comment by waylonflinn** [comment]
Just a note, for people looking for the code. It has been moved [here](https://github.com/keras-team/keras-preprocessing/blob/master/keras_preprocessing/image/image_data_generator.py).

**Comment by allaedding** [comment]
the problem still not fix ? I was shocked when I saw the result

**Comment by szetakyu** [comment]
Still not fixed in keras-gpu 2.3.1. My sample image of a circle is changed into a oval.

**Comment by tobidelbruck** [comment]
Yes, the offending lines are 801-807:
```python
        if self.zoom_range[0] == 1 and self.zoom_range[1] == 1:
            zx, zy = 1, 1
        else:
            zx, zy = np.random.uniform(
                self.zoom_range[0],
                self.zoom_range[1],
                2)
```
Any easy suggestion to work around this?

**Comment by tobidelbruck** [comment]
Also the documentation is a bit misleading, a zoom >1 minifies the resulted image, not magnifies it as I assumed.
