### ISSUE TITLE
shuffle is very slow when using fcn 

### ISSUE THREAD

**Issue by fayeshine** [keras-team/keras#9762]
when I turn on shuffle on training, the speed become 1/3 .
I use fully connected network, with 5m sample, 300 feature

**Comment by ghostplant** [comment]
It is recommended to create a generator and shuffle inside it, then turn off the shuffle in fit_generator which is implemented to be very slow.

https://github.com/keras-team/keras/pull/9704/files provides an `_array_list_generator` examples to shuffle inside and using `shufffle = False` to turn off outside shuffle.
