### ISSUE TITLE
Keras TF backend hangs when save_weights on cifar10_resnet200v2.py

### ISSUE THREAD

**Issue by ghostplant** [keras-team/keras#9774]
The Keras version I use is 2.1.5 and Tensorflow version is 1.5.0;

The example is chosen from keras example `cifar10_resnet.py` and I change `version = 2` and `n = 33` to build a Resnet200v2 model.

However, after several-epoch training and I want to save_weight on this large model, the keras framework hangs, and when I press `Ctrl + C` to kill the application, it is able to see that the whole application was stuck in line `weight_values = K.batch_get_value(symbolic_weights)` which never finished and it keeps CPU to be 100% usage and GPU 0% usage.

Besides, when `version = 2` and `n = 3` from same `cifar10_resnet.py` to build a short Resnet20v2 model, there is no longer any hangs.

**Comment by jonilaserson** [comment]
Also has this issue.
