### ISSUE TITLE
TimeSeriesGenerator fix & new features

### ISSUE THREAD

**Issue by JustM57** [keras-team/keras#9778]
I found this new method very useful, but it seems to be that we are loosing 2 data points and lack of some functionality. Main problem was splitting the data for train and test as it become non trivial issue. So I've made a function, which has the same constructor as TSGen and also test_size. Moreover, sometimes it may be useful to see what our generated batches are, but we can only see 1 item. So I've added slicing functionality for batches. I'm not sure if it deserve a pool request and absolutely sure it may be done in another way but this worked for me. So want a little bit of discussion

Maybe I'm a noob and made useless thing
[My notebook](https://github.com/JustM57/keras_add_features/blob/master/SplitGenerator.ipynb)

**Comment by JustM57** [comment]
@fchollet
@srjoglekar246

**Comment by srjoglekar246** [comment]
Can you expand a little bit on the _changes_ that you propose in the class' API, and how it will affect behavior? It would be good to get a high-level overview here before we dig into the code :-)
