### ISSUE TITLE
get_config on keras.models.Sequential model returns list, but get_config on keras.engine.training.Model returns dict

### ISSUE THREAD

**Issue by ghop02** [keras-team/keras#9783]
I noticed a weird difference in the Model API.  the `keras.models.Sequential` class inherits `keras.engine.training.Model`, but changes the signature of the `get_config` function.   Is there a reason for this? Seems like those two APIs should be consistent. 

https://github.com/keras-team/keras/blob/eb97bc385599dec8182963fe263bd958b9ab0057/keras/models.py#L1355-L1363
vs.
https://github.com/keras-team/keras/blob/eb97bc385599dec8182963fe263bd958b9ab0057/keras/engine/topology.py#L2326

**Comment by gabrieldemarmiesse** [comment]
This issue has been fixed in #11133. You'll be able to see the changes in the next keras release.
