### ISSUE TITLE
Composed neural networks model from two networks

### ISSUE THREAD

**Issue by mjaber01** [keras-team/keras#9784]
I am using Keras with Tensorflow to implement my model (M). Lets suppose that I have the following input features F = {x,y, a1, a2, a3, ..., an} I want to build a deep model (M1) using only x and y. Then, the output of (M1) with all the remaining features (a1, a2, ..., an) will be the input of another model (M2).

x,y --> M1 --> z, a1, a2, ..., an --> M2 --> final output

How can I build such model in Keras?

**Comment by gabrieldemarmiesse** [comment]
Yes, you need to look into functional models with multiple inputs. There is a section in the docs for this.
