### ISSUE TITLE
Feature request: In-plane locally-connected 2D convolutions

### ISSUE THREAD

**Issue by tsoernes** [keras-team/keras#9787]
I'm requesting a convolution that works on each channel separately using the same filter (as https://www.tensorflow.org/versions/r1.2/api_docs/python/tf/contrib/layers/conv2d_in_plane), and but uses different filters spatially (like LocallyConnected2D).

One approach would be to modify `LocallyConnected2D`:
``` 
individual_channels = tf.split(inputs, inputs.shape[3], -1)
convs = []
for channel in individual_channels:
    conv = K.local_conv2d(channel, self.kernel, self.kernel_size, self.strides,
       (self.output_row, self.output_col), self.data_format)
    convs.append(conv)
outputs = tf.concat(convs, -1)
```
where
```
self.kernel_shape = (output_row * output_col,
    self.kernel_size[0] * self.kernel_size[1], 1)
```
But the above approach is very slow.

**Comment by yuval-meir** [comment]
I want to request same exact thing as @tsoernes asked above. 
A locally connected layer that works on each channel separately (can use the same filter or not), without summation over the different colors of the previous layer.
