### ISSUE TITLE
How can I freeze of individual neurons in a layer and not the entire layer itself

### ISSUE THREAD

**Issue by shubham14** [keras-team/keras#9790]

**Comment by tchaton** [comment]
Maybe you have to pass a mask somehow.

**Comment by shubham14** [comment]
@tchaton : Could you please elaborate on how to use this for training CNNs

**Comment by tchaton** [comment]
I have never tried. I am just telling you that mask seems to be something to dig on. I am also look into it for a pruning project.

**Comment by AmirAlavi** [comment]
Hi,
I needed something similar for a project, and implemented a simple solution in the form of a layer that freezes some connections.
Repo: https://github.com/AmirAlavi/sparsely-connected-keras
PyPi: https://pypi.org/project/sparsely-connected-keras/
A blog post explaining how it works: http://amiralavi.net/blog/2018/07/29/vnn-implementation
Hope this helps someone.

**Comment by tchaton** [comment]
Hi,

Awesome, we did the same things, except I created a wrapper ;) Thank you
very much.

Best,
Thomas

2018-07-29 17:50 GMT+00:00 Amir Alavi <notifications@github.com>:
