### ISSUE TITLE
Verbose option not working for fit_generator

### ISSUE THREAD

**Issue by akshay-raj-dhamija** [keras-team/keras#9791]
Hello,

I am using a fit_generator to train my model using multiple GPUs as follows:
```
parallel_model = multi_gpu_model(model, gpus=[0,1])
parallel_model.compile(optimizer='rmsprop', loss={'pred':'categorical_crossentropy'},metrics=['acc'])
parallel_model.fit_generator(
                            generator=training_generator,
                            validation_data=validation_generator,
                            use_multiprocessing=False,
                            max_queue_size=50,
                            epochs=no_of_epochs,
                            verbose=0,
                            workers=1,
                            steps_per_epoch=training_generator.get_no_of_batches,
                            validation_steps=validation_generator.get_no_of_batches
                            )
```

As you see above I have set verbose as 0. The above code works seemlessly, but if I use verbose=1, I am greeted by the following error:
```
Traceback (most recent call last):
  File "InceptionV3.py", line 117, in <module>
    validation_steps=validation_generator.get_no_of_batches,
  File "/home/adhamija/anaconda2/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/adhamija/anaconda2/lib/python2.7/site-packages/keras/engine/training.py", line 2251, in fit_generator
    callbacks.on_batch_end(batch_index, batch_logs)
  File "/home/adhamija/anaconda2/lib/python2.7/site-packages/keras/callbacks.py", line 113, in on_batch_end
    callback.on_batch_end(batch, logs)
  File "/home/adhamija/anaconda2/lib/python2.7/site-packages/keras/callbacks.py", line 331, in on_batch_end
    self.progbar.update(self.seen, self.log_values)
  File "/home/adhamija/anaconda2/lib/python2.7/site-packages/keras/utils/generic_utils.py", line 358, in update
    numdigits = int(np.floor(np.log10(self.target))) + 1
AttributeError: 'function' object has no attribute 'log10'
```

I am using Tensorflow backend
```
keras-gpu                 2.1.4                    py27_0    defaults
tensorflow-gpu            1.4.1                         0    defaults
tensorflow-gpu-base       1.4.1            py27h01caf0a_0    defaults
tensorflow-tensorboard    1.5.1            py27hf484d3e_0    defaults
```

Any help would be greatly appreciated!

**Comment by alphaCTzo7G** [comment]
So I figured out why this is happening.

In the 2.1.4 releaes (and also in the current branch), there is this code block

	if self.verbose == 1:
	   if (now - self._last_updatr < self.interval and
			   self.target is not None and current < self.target):
		   return

	   prev_total_width = self._total_width
	   if self._dynamic_display:
		   sys.stdout.write('\b' * prev_total_width)
		   sys.stdout.write('\r')
	   else:
		   sys.stdout.write('\n')

	   if self.target is not None:
		   numdigits = int(np.floor(np.log10(self.target))) + 1
		   barstr = '%%%dd/%d [' % (numdigits, self.target)
		   bar = barstr % current
		   prog = float(current) / self.target
		   prog_width = int(self.width * prog)

Here the error happens in the line:
	
   numdigits = int(np.floor(np.log10(self.target))) + 1

I am guessing for your case the value of
	
	self.target > 10^19

as a result `self.target` exceeds the maximum size that Python can represent as
`integers`, and falls back to `unlimited integer representation`. However, 
numpy doesnt support `unlimited integer` types, thus leading to this error. 

You can reproduce the problem by just using the following code

	import numpy as np; numdigits = int(np.floor(np.log10(10**20))) + 1 ## this will give the error about log10

and 

	import numpy as np; numdigits = int(np.floor(np.log10(10**19))) + 1 # this wont give any error

This can be easily solved if we just convert `self.target` to float first. 
Since this occurs in the `ProgBar` class which is not evaluated very frequently,
a easy way to avoid this probem would be to change the line as follows:

	numdigits = int(np.floor(np.log10(float(self.target)))) + 1 

What do you guys think?

**Comment by alphaCTzo7G** [comment]
I have modified the code base and added this to the branch in my repo: https://github.com/alphaCTzo7G/keras/blob/ce4eebdb56fe35e2914441b8b5c4907c07d4f755/keras/utils/generic_utils.py#L361

Also modified the tests for tests here: https://github.com/alphaCTzo7G/keras/blob/master/tests/keras/utils/generic_utils_test.py

If this looks good, I will create a PR this coming weekend
