### ISSUE TITLE
Add Layers to pretrained model in keras

### ISSUE THREAD

**Issue by vishutorvi** [keras-team/keras#9809]
Hi,
Can anyone help me in solving this issue which i have been facing from past 1 week couldnt able to find any solution to it.
This is my thesis work, my usecase is:
    1) I have to train the LSTM model using the following code,
         My train data shape is: (340759, 50, 9),      y_train = (340759, )
          model.add(LSTM(X_train.shape[1], input_shape=(X_train.shape[1], X_train.shape[2]), 
          return_sequences=True))
          model.add(Dropout(0.2))
          model.add(LSTM(int(X_train.shape[1]), input_shape=(X_train.shape[1], X_train.shape[1]), 
          return_sequences=False))
          model.add(Dense(1))
          model.compile(loss='binary_crossentropy', optimizer=adam,metrics=['accuracy'])
          # fit network
          history = model.fit(X_train, y_train_keras, epochs=10, batch_size=1000, verbose=2, shuffle=False)

    2) After training, Further i need to add extra layer to it and train it again with other set of data by 
       making existing layers trainable = False
        Next set of training data shape:   (63632, 50, 9)   and   y_train = (63632, )
         del model.layers[-1]       //Deleting Last Dense Layer in the previous model
         model.layers[0].trainable = False       //FIRST LSTM LAYER trainable to false
         model.layers[2].trainable = False       //SECOND LSTM LAYER trainable to false

         model.add(LSTM(X_test_train.shape[1], input_shape=( X_test_train.shape[1], X_test_train.shape[1]), 
            return_sequences=False))
         model.add(Dense(1))
         model.fit(X_test_train, y_test_train, epochs=10, validation_data = (X_test, 
                                                                y_test_new),batch_size=1000, verbose=2, shuffle=False)

When i train for the second time as per (2),  I'm getting this error:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-86-ff1bc54945fe> in <module>()
      1 #model.add(Dropout(0.2))
----> 2 model.add(LSTM(X_test_train.shape[1], input_shape=([None, X_test_train.shape[1]]), return_sequences=False))
      3 model.add(Dense(1))
      4 model.compile(loss='binary_crossentropy', optimizer=adam,metrics=['accuracy'])
      5 model.fit(X_test_train, y_test_train, epochs=10, validation_data = (X_test, y_test_new),batch_size=1000, verbose=2, shuffle=False)

ValueError: Input 0 is incompatible with layer lstm_24: expected ndim=3, found ndim=2         

Can anyone help me in finding solution for this.

If you cannot understand it please let me know i can give much more details.

Thank you!

**Comment by rex-yue-wu** [comment]
Of course, this error is expected, because your 2nd LSTM uses `return_sequences=False` indicating its output is 2D instead of 3D. How come it could be used in your new LSTM which expects a 3D tensor input?

**Comment by vishutorvi** [comment]
Thank you for the help, I got to know my mistake..Appreciate your help !
