### ISSUE TITLE
Cannot load NASNetLarge

### ISSUE THREAD

**Issue by korytmar** [keras-team/keras#9812]
My code is:

m = NASNetLarge(include_top=False,weights='imagenet',input_shape=(224,224,3)) 

But this line of code gives me this error: 

ValueError: When setting`include_top=True` and loading `imagenet` weights, `input_shape` should be (331, 331, 3).

It only works with shape (331,331,3) but for larger inputs like (640,640,3) does not work again.

**Comment by gabrieldemarmiesse** [comment]
This is normal. The NASNetLarge isn't made to accept different input sizes, like the VGG16 or VGG19 for example. The documentation states:

The default input size for the NASNetLarge model is 331x331 and for the NASNetMobile model is 224x224

**Comment by korytmar** [comment]
I know that, but this default values are also for other models.

In docs NASNetLarge:

'It should have exactly 3 inputs channels, and width and height should be no smaller than 32. E.g. (200, 200, 3) would be one valid value.'

According to this, I think it should work or am I misunderstanding?

**Comment by gabrieldemarmiesse** [comment]
I see what you mean. Sorry, I misread you the first time. I'm going to dig in, but I get the same error, and it's true that it makes no sense! Thanks for insisting!

**Comment by gabrieldemarmiesse** [comment]
You are right, I did a check in more depths. A PR is going to be made. It'll take quite some time to make it in the stable release.
