### ISSUE TITLE
Rebuild needed for multi-gpu

### ISSUE THREAD

**Issue by hoonkai** [keras-team/keras#9820]
Hi

I'm looking at getting a second GPU for my Z370-P. I'm already running Keras on a 1050 Ti quite fine, but I'm not sure whether things will break if it runs on multi-gpu. Anyone know if Keras/Tensorflow will need to be rebuilt to support multi-gpu?

Thanks

**Comment by gabrieldemarmiesse** [comment]
No, you don't have to worry. Tensorflow detect what gpus are available when you import it, not when you install it. You can even "hide" gpus from tensorflow by using the environement variable CUDA_VISIBLE_DEVICES, it's proof that tensorflow doesn't keep logs about your hardware setup.
