### ISSUE TITLE
ImportError: `save_model` requires h5py.

### ISSUE THREAD

**Issue by FirefoxMetzger** [keras-team/keras#9822]
When saving a model using the `keras.callbacks.ModelCheckpoint` I've encountered a missing dependency. I assume the same is true for a direct call to `model.save(...)`.

Since this is a direct (or indirect) dependency is it worth adding to Keras' dependencies? I'm new to the code base and couldn't find where you are tracking them. If somebody points me to the location, I'm happy to submit a PR.

If it isn't worth tracking, could we instead update the docks to __very__ clearly state that this is a dependency? I can see somebody careless (like me xD) running an expensive model only to find it crashing after 1 hour, because they try to save it.

**Comment by gabrieldemarmiesse** [comment]
The documentation states in the installation page states:

HDF5 and h5py (required if you plan on saving Keras models to disk).

But I do agree that your case is fustrating and we wouldn't like that such a case happen again if possible.

Keras can't make this a real dependency because some people save models with the saving fucntion of the backend (for example, tensorflow has its own way of saving graphs).

What could be done, is checking if it's possible to import h5py in the `__init__()` of the model checkpoint callback, and raise an importError at this point. I can't garantee 100% that this small change is going to get accepted by the keras team, but you can do a pull request on it if you don't want it to happen to other people.

**Comment by FirefoxMetzger** [comment]
I get the argument regarding the custom save function via the backend.

Given that this is, as you say, an arguably small and also very specific change, how about I update the docs? My idea would be to add something like

    "Note: This function requires you to `pip install h5py` manually."

to `keras.callbacks.ModelCheckpoint`, `keras.models.save_weights` and `keras.models.save_model`. Am I missing a function?

Thoughts?

**Comment by gabrieldemarmiesse** [comment]
You are right. let me see what nees to me changed.

**Comment by gabrieldemarmiesse** [comment]
https://keras.io/getting-started/faq/#how-can-i-save-a-keras-model

https://keras.io/models/about-keras-models/  (bottom of the page)

https://keras.io/callbacks/#modelcheckpoint

You would have to add a note at those three places in the documentation. I think that should be everything!

**Comment by FirefoxMetzger** [comment]
PR is made. I will leave this issue open for now in case there is more to be done.

**Comment by gabrieldemarmiesse** [comment]
Thanks!

**Comment by FirefoxMetzger** [comment]
But this is a different error. Keras is unable to open the file / location to save it. Seems to be a permissions issue.

**Comment by BlcaKHat** [comment]
@FirefoxMetzger true. working.

**Comment by wt-huang** [comment]
Closing as this is resolved

**Comment by mojimich2015** [comment]
Have the same issue. 
My Code: 
```

import pandas as pd
from keras.models import Sequential
from keras.layers import *

training_data_df = pd.read_csv("sales_data_training_scaled.csv")

X = training_data_df.drop('total_earnings', axis=1).values
Y = training_data_df[['total_earnings']].values

# Define the model
model = Sequential()
model.add(Dense(50, input_dim=9, activation='relu'))
model.add(Dense(400, activation='relu'))
model.add(Dense(50, activation='relu'))
model.add(Dense(1, activation='linear'))
model.compile(loss='mean_squared_error', optimizer='adam')

# Train the model
model.fit(
    X,
    Y,
    epochs=50,
    shuffle=True,
    verbose=2
)

# Load the separate test data set
test_data_df = pd.read_csv("sales_data_test_scaled.csv")

X_test = test_data_df.drop('total_earnings', axis=1).values
Y_test = test_data_df[['total_earnings']].values

test_error_rate = model.evaluate(X_test, Y_test, verbose=0)
print("The mean squared error (MSE) for the test data set is: {}".format(test_error_rate))

# Save the model to disk
model.save("trained_model.h5")
print("Model saved to disk.")

```

**Comment by mojimich2015** [comment]
> Have the same issue. My Code:
> 
> ```
> 
> import pandas as pd
> from keras.models import Sequential
> from keras.layers import *
> 
> training_data_df = pd.read_csv("sales_data_training_scaled.csv")
> 
> X = training_data_df.drop('total_earnings', axis=1).values
> Y = training_data_df[['total_earnings']].values
> 
> # Define the model
> model = Sequential()
> model.add(Dense(50, input_dim=9, activation='relu'))
> model.add(Dense(400, activation='relu'))
> model.add(Dense(50, activation='relu'))
> model.add(Dense(1, activation='linear'))
> model.compile(loss='mean_squared_error', optimizer='adam')
> 
> # Train the model
> model.fit(
>     X,
>     Y,
>     epochs=50,
>     shuffle=True,
>     verbose=2
> )
> 
> # Load the separate test data set
> test_data_df = pd.read_csv("sales_data_test_scaled.csv")
> 
> X_test = test_data_df.drop('total_earnings', axis=1).values
> Y_test = test_data_df[['total_earnings']].values
> 
> test_error_rate = model.evaluate(X_test, Y_test, verbose=0)
> print("The mean squared error (MSE) for the test data set is: {}".format(test_error_rate))
> 
> # Save the model to disk
> model.save("trained_model.h5")
> print("Model saved to disk.")
> ```

No worries, Just used the default saving model with pb format.
