### ISSUE TITLE
Do keras have plan to support deep complex netowrk?

### ISSUE THREAD

**Issue by agangzz** [keras-team/keras#9823]
Do keras have plan to support deep complex netowrk?
such as "Deep Complex Networks" in https://arxiv.org/abs/1705.09792

**Comment by gabrieldemarmiesse** [comment]
It's not really up to keras to support it or not. This kind of feature depends on the backend. So the real question is more: "Do theano/ tensorflow/ CNTK/ MXNet have plans to support deep complex networks?". You could ask on the github page of those projects to know, I suppose.
