### ISSUE TITLE
Tensorboard callback fail 

### ISSUE THREAD

**Issue by guillem74** [keras-team/keras#9828]
When calling Tensorboard callback, at epoch end

It throws an error at line 862:

**summary_value.simple_value = value.item()
AttributeError: 'int' object has no attribute 'item'**

This is my code:

_callbacks = TensorBoard(log_dir='.')
dqn.fit(env, callbacks=[callbacks], nb_steps=150000, visualize=False, verbose=0, log_interval=100)_

**Comment by Dref360** [comment]
I guess you use keras-rl? You would have to take it to them. 
https://github.com/keras-rl/keras-rl/blob/35f9b50c3b35f52722d740e8ee42e33c1750e44a/rl/core.py#L44

**Comment by guillem74** [comment]
@Dref360 Thanks for the answer. As it is said on the keras-rl docs, callbacks can be a  list of either rl callbacks or original Keras callbacks, and it is an issue with the Keras TensorBoard callback.

Also, keras-rl support is almost dead.

**Comment by guillem74** [comment]
@Dref360 I mean the TensorBoard() function is directly imported from Keras callbacks.

**Comment by Dref360** [comment]
Keras' logs have a specific type. 
```python
log = {'key':np.scalar}
```

keras-rl provides an int where they should provide a np.int.

**Comment by guillem74** [comment]
@Dref360 So, is there a way to address that?

**Comment by guillem74** [comment]
@Dref360 This can be closed! I found that by changing rl/core.py at line 209.

From this:

 episode_logs = {
                        'episode_reward': episode_reward,
                        'nb_episode_steps': episode_step,
                        'nb_steps': self.step,
                    }

To this:

 episode_logs = {
                        'episode_reward': np.float_(episode_reward),
                        'nb_episode_steps': np.float_(episode_step),
                        'nb_steps': np.float_(self.step),
                    }

So, like you said, it was more an issue with keras-rl, than with keras at all.
