### ISSUE TITLE
Is OrderedEnqueuer bound by GIL?

### ISSUE THREAD

**Issue by hoonkai** [keras-team/keras#9835]
It seems to me that `OrderedEnqueuer` can utilise multiple threads whilst `GeneratorEnqueuer` cannot. For instance, when I use a generator that is of type `Sequence`, `workers=n` where `n > 1`, more than 1 core is utilised. However, when the generator is not of type `Sequence`, only 1 core is used regardless of the number of workers. Is this valid observation? If so, how come `OrderedEnqueuer` isn't bound by GIL?

**Comment by Dref360** [comment]
(Author of OrderedEnqueuer)
A Sequence is a read-only structure so a mutex is useless.
A generator cannot be iterated over by multiple threads at the same time so we wrap a mutex around it.
This explanation holds only for `use_multiprocessing=False`

In any case, Generators should be avoided if possible.
