### ISSUE TITLE
How to feed input of previous time_step to the “Decoder” of “Sequence-to-Sequence” model?

### ISSUE THREAD

**Issue by diptam-in** [keras-team/keras#9837]
I am developing a **sequence-to-sequence** model for text generation. I am **not using 'teacher-forcing"** at the decoder side, i.e. output of decoder at **t0** is fed to input of decoder at time **t1**.

Now, in reality, output of a decoder (LSTM/GRU) is passed through a Dense layer, which in tern generates the index of the word, which is considered as the output of the decoder.
But, for feeding the output to next layer, I had to apply __arg_max()__ to find the index of the "word", but, while I am trying to feed to next time_step, it says

`ValueError: An operation has `None` for gradient. Please make sure that all of your ops have a gradient defined (i.e. are differentiable). Common ops without gradient: K.argmax, K.round, K.eval.`

I understand that, since I am applying this function, it is not differentiable, , So, Is there any way to do it ??
I am following [this](https://blog.keras.io/a-ten-minute-introduction-to-sequence-to-sequence-learning-in-keras.html) tutorial for encoder-decoder model.

here is what I have written:
```
o_t= output_layer(o_t) # output of  Dense Layer ()
converter_o_t=lookup(o_t) # lookup is Lambda Layer, written for conversion
input_=converter_o_t # assign to next input 
```

**Comment by jonathanking** [comment]
Is it possible for you to skip the argmax step until you need to make predictions? I imagine that the network will be able to train without the argmax just fine. This way, your model will make predictions with some dimension. Then, create a decoding function which takes the sequence of vectors and returns a sequence of their argmaxes.
