### ISSUE TITLE
K.batch_dot cannot handle the default axes=None

### ISSUE THREAD

**Issue by shadiakiki1986** [keras-team/keras#9847]
- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

In [backend/tensorflow_backend.py#L1144](https://github.com/keras-team/keras/blob/master/keras/backend/tensorflow_backend.py#L1144), the case when `axes=None` by default breaks the ` if axes[0] == axes[1]:`

Example script to reproduce

```
from keras import backend as K
x_batch = K.ones(shape=(32, 20))
y_batch = K.ones(shape=(20, 32))
xy_batch_dot = K.batch_dot(x_batch, y_batch, axes=[0, 1])
print(K.int_shape(xy_batch_dot))

xy_batch_dot = K.batch_dot(x_batch, y_batch) # <<< fails

```

Traceback

```
Traceback (most recent call last):
  File "test_keras_batchdot.py", line 7, in <module>
    xy_batch_dot = K.batch_dot(x_batch, y_batch) # <<< fails
  File "/home/ubuntu/.local/share/virtualenvs/TEST_KERAS/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 1144, in batch_dot
    if axes[0] == axes[1]:
TypeError: 'NoneType' object is not subscriptable
```

ATM, latest Keras version = 2.1.5

**Comment by vkk800** [comment]
I made a pull request that changes the behaviour to default to dotting over the axis index 1 if no arguments is provided. Your example case would still fail since the shapes of the tensors are not compatible with this behaviour (and the error message would also inform you about this), but a more common case of two 2D-tensors with the same shape should work with my fix.
