### ISSUE TITLE
Composite models of RNNs cause None gradients

### ISSUE THREAD

**Issue by AtR1an** [keras-team/keras#9854]
Hi,

I am having some problems with recurrent layers and composite networks.
See this gist for an example of what I am trying to do: [https://gist.github.com/AtR1an/9a2f4ceb2ca830ce7344ebe6544cea05](https://gist.github.com/AtR1an/9a2f4ceb2ca830ce7344ebe6544cea05)

This is a modified (and simplified) version of the sequence to sequence [example script](https://github.com/keras-team/keras/blob/master/examples/lstm_seq2seq.py) where I decomposed the network into an encoder and a decoder network which are then combined in an encoder_decoder model.
The problem is that the training fails with `ValueError: An operation has None for gradient. Please make sure that all of your ops have a gradient defined (i.e. are differentiable). Common ops without gradient: K.argmax, K.round, K.eval.`
Some debugging shows that the gradients of the encoder model are None.
Note that the same issue is present if one uses GRUs instead of LSTMs.
Interestingly, everything works fine if the CuDNN versions of those layers are used (which is unfortunate if you only have a CPU available). It also works if you use a normal LSTM in the encoder and a CuDNNLSTM in the decoder.

I tested this with different configurations:
- Windows 10 with Python 3.5.4, Keras 2.1.5 and TensorFlow 1.3.0 (CPU)
- Windows 7 with Python 3.5.4, Keras 2.1.3 and TensorFlow 1.4.0 (GPU Cuda 8.0 CuDNN 6)

I also tried an older Keras version with which the problem doesn't occur:
- Windows 10 with Python 3.6.2, Keras 2.0.6 and TensorFlow 1.3.0

This could be the same issue as in this StackOverflow [question](https://stackoverflow.com/questions/49462794/keras-gets-none-gradient-error-when-connecting-models).

It's also fairly possible that I messed something up during the model construction so feel free to correct me if I did anything stupid.

Thanks for your time and support,

Adrian

**Comment by owsd** [comment]
My proposed fix:
https://github.com/tensorflow/tensorflow/pull/23197
