### ISSUE TITLE
Does keras support different size images or don't?

### ISSUE THREAD

**Issue by MityuraDM** [keras-team/keras#9863]
UNet, I have a list of 670 different size RGB images(X_train) tensorflow backend

X_train=[]
img = imread(path  + '/images/' + id_ + '.png')[:,:,:3]
X_train.append(img)
inputs = Input((None, None, 3))

if i use
results = model.fit(np.array(X_train), np.array(Y_train),  
                 validation_split=0.1, batch_size=8, epochs=30)
then i get
Error when checking input: expected input_14 to have 4 dimensions, but got array with shape (670, 1)
if i use
results = model.fit(X_train, Y_train,  
                 validation_split=0.1, batch_size=8, epochs=30)
then i get
Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 1 array(s), but instead got the following list of 670 arrays

Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by nuric** [comment]
It seems like a data processing problem rather than a Keras issue. You are more likely to get a better answer on [StackOverflow](http://stackoverflow.com/questions/tagged/keras). Briefly, when you call np.array on X_train, the images must of same shape to create a tensor, otherwise NumPy will create an array of objects, specifically an array of 670 to 1 image object which contains imread value. You either need to pad the images to the same shape, or use a generator that feeds images of different sizes in predict_generator.

**Comment by Dref360** [comment]
A batch needs to have the same dimension. But a model can handle different image size. You can specify this behavior with a None in your input_shape.

As nuric said. It's not a Keras issue so I'll close
