### ISSUE TITLE
How to realize combination of U-net and Bidirectional convolutional LSTM?

### ISSUE THREAD

**Issue by percyfan** [keras-team/keras#9868]
I'm a rookie to coding and I noticed there is an interesting network architecture for semantic segmentation, which combine the U-net and Bidirectional convolutional LSTM, just like the image url below:

[https://www.hindawi.com/journals/complexity/2018/4185279/fig10/]

and here is the original paper

[https://www.hindawi.com/journals/complexity/2018/4185279/]

I'm using the u-net code from [https://github.com/zhixuhao/unet], but have no idea how to combine BDCLSTM to it, can anyone offer some help? or is there existing code for this ?

**Comment by Dref360** [comment]
Hi!
This issue isn't related to a bug/enhancement/feature request or other accepted types of issue.

To ask questions, please see the following resources : 
* https://keras.io/
* https://keras.io/#support
* https://gitter.im/Keras-io/Lobby

Thanks!

If you think I made an error, please re-open this issue.
