### ISSUE TITLE
Unused Variable.

### ISSUE THREAD

**Issue by mainanick** [keras-team/keras#9871]
Was reading through the embedding layer and came across an unused variable `mask` on `combine_mask` function.
https://github.com/keras-team/keras/blob/736b7a705db802d63ddcee1cd0687f806ef2d495/keras/layers/embeddings.py#L108

**Comment by farizrahman4u** [comment]
It still needs to maintain the function signature since it will be called by Keras topology as `output_mask = layer.compute_mask(inputs, None)`
