### ISSUE TITLE
fit_generator error with multiprocessing = True and workers >= 1

### ISSUE THREAD

**Issue by RLstat** [keras-team/keras#9874]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

I wrote a generator to feed into fit_generator, and it works fine when using multiprocessing = False, or workers = 0. However, if I use multiprocessing = True, and workers >= 1, then it will create errors. 

Following are my code and error message:
```python
def data_generator(dataset, masks, shuffle=True, augment=True, 
                   batch_size=1):
    
    image_index = -1 #overall image index for ecah epoch
    datasize  = dataset.shape[0]
    b = 0 #batch index
    
    while True:
        try: 
            image_index = (image_index + 1) % datasize
            if shuffle and image_index == 0:
                dataindex = np.random.permutation(datasize)
           
            image_id = dataindex[image_index]
            image = dataset[image_id]
            mask  = masks[image_id]
            
            image, mask = load_image_gt(image, mask, augment=augment)
            if np.sum(mask) == 0:
              continue            
            
            if b == 0:
                batch_image = np.zeros((batch_size, ) + image.shape)
                batch_mask  = np.zeros((batch_size, ) + mask.shape)
                
            batch_image[b] = image
            batch_mask[b]  = mask
            
            b += 1
            if b >= batch_size:
                inputs = [batch_image]
                outputs = [batch_mask]
                b = 0
                yield inputs, outputs
        except (GeneratorExit, KeyboardInterrupt) as err:
          print(err)
          raise     
          
```

```python
train_generator = data_generator(train_img, train_mask, batch_size = 8)
```

```python
print("\nTraining...")
u_net.fit_generator(train_generator, steps_per_epoch=120, epochs=100, workers = 1, use_multiprocessing = True)

Training...
---------------------------------------------------------------------------
EOFError                                  Traceback (most recent call last)
<ipython-input-39-f2f017d18837> in <module>()
      1 print("\nTraining...")
----> 2 u_net.fit_generator(train_generator, steps_per_epoch=120, epochs=100, workers = 1, use_multiprocessing = True)

/usr/local/lib/python3.6/dist-packages/keras/legacy/interfaces.py in wrapper(*args, **kwargs)
     89                 warnings.warn('Update your `' + object_name +
     90                               '` call to the Keras 2 API: ' + signature, stacklevel=2)
---> 91             return func(*args, **kwargs)
     92         wrapper._original_function = func
     93         return wrapper

/usr/local/lib/python3.6/dist-packages/keras/engine/training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   2174                                                  use_multiprocessing=use_multiprocessing,
   2175                                                  wait_time=wait_time)
-> 2176                 enqueuer.start(workers=workers, max_queue_size=max_queue_size)
   2177                 output_generator = enqueuer.get()
   2178             else:

/usr/local/lib/python3.6/dist-packages/keras/utils/data_utils.py in start(self, workers, max_queue_size)
    701             self.max_queue_size = max_queue_size
    702             if self._use_multiprocessing:
--> 703                 self._manager = multiprocessing.Manager()
    704                 self.queue = self._manager.Queue(maxsize=max_queue_size)
    705                 self._stop_event = multiprocessing.Event()

/usr/lib/python3.6/multiprocessing/context.py in Manager(self)
     54         from .managers import SyncManager
     55         m = SyncManager(ctx=self.get_context())
---> 56         m.start()
     57         return m
     58 

/usr/lib/python3.6/multiprocessing/managers.py in start(self, initializer, initargs)
    515         # get address of server
    516         writer.close()
--> 517         self._address = reader.recv()
    518         reader.close()
    519 

/usr/lib/python3.6/multiprocessing/connection.py in recv(self)
    248         self._check_closed()
    249         self._check_readable()
--> 250         buf = self._recv_bytes()
    251         return _ForkingPickler.loads(buf.getbuffer())
    252 

/usr/lib/python3.6/multiprocessing/connection.py in _recv_bytes(self, maxsize)
    405 
    406     def _recv_bytes(self, maxsize=None):
--> 407         buf = self._recv(4)
    408         size, = struct.unpack("!i", buf.getvalue())
    409         if maxsize is not None and size > maxsize:

/usr/lib/python3.6/multiprocessing/connection.py in _recv(self, size, read)
    381             if n == 0:
    382                 if remaining == size:
--> 383                     raise EOFError
    384                 else:
    385                     raise OSError("got end of file during message")

EOFError: 
```
Additionally, it is quite unclear to me about the difference between workers = 0 and workers = 1 here, and why one works fine while the other would create issue.

**Comment by RLstat** [comment]
Additionally, I understand that using keras.utils.Sequence() is a safer way for multiprocessing. But in my particular case it would hard to use. Specifically, I am doing random processing/augmentation on the fly, but the processing can generate unusable sample occasionally. So in my generator, I will pass on to the next sample, as in here:
```python
image, mask = load_image_gt(image, mask, augment=augment)
if np.sum(mask) == 0:
    continue 
```
However, in keras.utils.Sequence(), it will requite each batch being pre-determined by batch index, and if an unusable sample is generated in a batch, it will result in difference in the number of samples in each batch (which is probably undesirable and cause errors). 

Please let me know if I misunderstood the usage of keras.utils.Sequence() or there are ways to work around that. 

Thanks and have a good weekend.

**Comment by Dref360** [comment]
Can you try the following : 
```python
import multiprocessing
manager = multiprocessing.Manager()
queue = manager.Queue(maxsize=10)
```

Python isn't able to start a process. Do you have non-pickable variables in your scope?

**Comment by RLstat** [comment]
Hi, @Dref360 , Thanks for the response! I've tried 
```python
import multiprocessing
manager = multiprocessing.Manager()
queue = manager.Queue(maxsize=10)
```
and python is able to start a process. However, since the data_generator is not imported as a module, it may not be pickable as stated here: https://docs.python.org/3/library/pickle.html#what-can-be-pickled-and-unpickled. Do you think that would be the reason? I will try to repeat it through import and see whether I could get it fixed. 

A more important question to me now is my comment following the original post regarding the keras.util.Sequence class. Is it possible for the Sequence class to have dynamic batch size or number of batches, depending on the results of preprocessing on the fly?

**Comment by wl2776** [comment]
@RLstat, different batches can have different sizes. 

See https://keras.io/models/sequential/#fit_generator: 

> This tuple (a single output of the generator) makes a single batch. Therefore, all arrays in this tuple must have the same length (equal to the size of this batch). *Different batches may have different sizes.* For example, the last batch of the epoch is commonly smaller than the others, if the size of the dataset is not divisible by the batch size.
