### ISSUE TITLE
The LSTM does not generate reproducible results, but GRU does

### ISSUE THREAD

**Issue by MyVanitar** [keras-team/keras#9876]
I can not get reproducible results by just using the LSTM, but GRU is Okay.

Let me explain what happens.

if I train an identical LSTM, 10 times in a loop, for the first 6 run it handles MSE equal to value `a` and for the rest 4 run it handles MSE value `b`. weird isn't?
Just value `a` OR `b`. it means an identical LSTM can handle two MSEs by random and just two MSE values.

and if I just replace the LSTM with GRU, all 10 runs handle identical MSEs.

I use Tensorflow 1.7 and Keras 2.1.5, I run on the CPU.

**Comment by abrad1212** [comment]
@VanitarNordic would you mind posting your code in a **[Gist](https://gist.github.com/)** and link it back here.

**Comment by VanitarNordic** [comment]
The code is not something special, just a loop and Keras guides to make reproducible results:



```python-traceback

import os
os.environ['PYTHONHASHSEED'] = '0'
import numpy as np
np.random.seed(12)
import random as rn
rn.seed(123)
import tensorflow as tf
tf.set_random_seed(1234)

session_conf = tf.ConfigProto(intra_op_parallelism_threads=1, inter_op_parallelism_threads=1)
from keras import backend as K
sess = tf.Session(graph=tf.get_default_graph(), config=session_conf)
K.set_session(sess)
.
.
..... some other initialization and code
.

for cnt in range(0, 10):    
            
    model = Sequential()        
    model.add(LSTM(10, input_shape=(lag, num_parameters), return_sequences=False))
    model.add(Dense(1, activation = "linear")) 
    model.compile(loss='mse', optimizer='adam')
    model.summary()
    history = model.fit(train_X, train_y, epochs=5, batch_size=1, validation_data=(test_X, test_y), 
                    verbose = 2, shuffle = False, callbacks=[tbCallBack])          
  
    del model
    K.clear_session() 
    np.random.seed(12)    
    rn.seed(123)    
    tf.set_random_seed(1234)

```

**Comment by VanitarNordic** [comment]
@abrad1212 

no idea?
