### ISSUE TITLE
Keras Seq2seq (many to many) model predicts same output for any input (> 50 words)

### ISSUE THREAD

**Issue by asksonu** [keras-team/keras#9882]
I am trying to build a seq2seq model using LSTM in Keras.I have run on 147k dataset with input less than 10 words with 5 epochs and the results vary for every input. 

However now I am running same model with another dataset with input and output sequences containing average no of words as 170 and 100 respectively after cleaning (removing stopwords and stuff). This dataset has around 30k records and if i run even with 50 epochs, the results are same again for every test sentence. So what are my next options for me to try. I was expecting atleast different output for different inputs (even if it is wrong) but same output is adding more frustration whether the model is not learning properly.

Full desc of issue - 
https://stackoverflow.com/questions/49638685/keras-seq2seq-model-predicting-same-output-for-all-test-inputs

Any inputs would be appreciated. Thanks.

**Comment by ElozinoEgonmwan** [comment]
Hi @asksonu did you find a solution yet. I am currently experiencing same issue. Thanks

**Comment by hwdong-net** [comment]
I have the same problem
