### ISSUE TITLE
CNN + LSTM problem

### ISSUE THREAD

**Issue by 0just0** [keras-team/keras#9887]
Hi, I'm trying to build a model for video classification. I'm treating videos as a sequence of images, so the model takes features from pre-trained cnn and passes them to lstm layer.

```
video  = Input(shape=(None, 256,256,3),name='video_input')
face_encoder = MobileNet(weights=None, include_top=False, input_shape=(256, 256, 3))
face_encoder.load_weights('vgg2_mobilenet.h5')
# add a global spatial average pooling layer
face_encoder.trainable = False
# wrap cnn into Lambda and pass it into TimeDistributed
encoded_frame = TimeDistributed(Lambda(lambda x: face_encoder(x)))(video)
encoded_vid = LSTM(256)(encoded_frame)
outputs = Dense(7, activation='relu')(encoded_vid)
model = Model(inputs=[video],outputs=outputs)
```
but while running I got a following error message:

```
2018-04-09 02:04:45 PST encoded_vid = LSTM(256)(encoded_frame)
2018-04-09 02:04:45 PST File "/usr/local/lib/python3.5/site-packages/keras/layers/recurrent.py", line 262, in __call__
2018-04-09 02:04:45 PST return super(Recurrent, self).__call__(inputs, **kwargs)
2018-04-09 02:04:45 PST File "/usr/local/lib/python3.5/site-packages/keras/engine/topology.py", line 552, in __call__
2018-04-09 02:04:45 PST self.assert_input_compatibility(inputs)
2018-04-09 02:04:45 PST File "/usr/local/lib/python3.5/site-packages/keras/engine/topology.py", line 451, in assert_input_compatibility
2018-04-09 02:04:45 PST str(K.ndim(x)))
2018-04-09 02:04:45 PST ValueError: Input 0 is incompatible with layer lstm_1: expected ndim=3, found ndim=5
```

I have no idea how to fix it, need your help :)

P.S.

I'm also using ImageDataGenerator for fitting, maybe the problem is here?
```
train_datagen = ImageDataGenerator(
    shear_range=0.2, zoom_range=0.2, horizontal_flip=True)
test_datagen = ImageDataGenerator()
train_generator = train_datagen.flow_from_directory(
    train_data_dir,
    target_size=(img_height, img_width), )

validation_generator = test_datagen.flow_from_directory(
    validation_data_dir,
    target_size=(img_height, img_width), )
```

Thank you!

- [X] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [X] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [X] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by nuric** [comment]
You have a shape mismatch, not an issue with Keras. To get a better answer try [StackOverflow](http://stackoverflow.com/questions/tagged/keras). In short, the tensor returned from face_encoder is not (samples, timesteps, features). You can print(face_encoder) to see what shape the symbolic tensor is, you know it is 5 dimensional from the error message. And you don't need lambda layer as models can be used as layers already.
