### ISSUE TITLE
Keras 2.1.5 breaks Tensorflow GPU 1.4.1 when calling K.l2_normalize(x, self.axis)

### ISSUE THREAD

**Issue by juiceboxjoe** [keras-team/keras#9900]
Thanks to the keras team for your work.

I'm following tutorials from [here](https://github.com/pierluigiferrari/ssd_keras/blob/master/ssd300_training.ipynb) and the code uses a custom Keras Layer who's call() implementation calls `K.l2_normalize(x, self.axis)` like so:

```
def call(self, x, mask=None):
        output = K.l2_normalize(x, self.axis)
        return output * self.gamma
```

This breaks tensorflow-gpu with the following error message:

```
/path/to/ssd_keras/keras_layers/keras_layer_L2Normalization.py in call(self, x, mask)
     61 
     62     def call(self, x, mask=None):
---> 63         output = K.l2_normalize(x, self.axis)
     64         return output * self.gamma
     65 

/path/to/ssd_keras/ssd_venv/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py in l2_normalize(x, axis)
   3149         A tensor.
   3150     """
-> 3151     return tf.nn.l2_normalize(x, axis=axis)
   3152 
   3153 

TypeError: l2_normalize() got an unexpected keyword argument 'axis'
```
The error message is pretty clear: tf.nn.l2_normalize() doesn't have a parameter named axis in your version of TensorFlow, implying that you are using a version of TensorFlow that is too old.

I'm using tensorflow-gpu 1.4.1 which has already been updated to use `axis`. I'm was also using Keras 2.1.5.

Keras 2.1.5 seemed to be the problem and downgrading to Keras 2.1.4 fixed it. This problem was elusive and an ongoing discussion can be found [here](https://github.com/pierluigiferrari/ssd_keras/issues/83).

**Comment by fchollet** [comment]
`l2_normalize` features an `axis` argument: https://www.tensorflow.org/api_docs/python/tf/nn/l2_normalize

It used to be named `dim`, but has been renamed `axis` (a better name).

It seems you are using an older version of TF. Try printing out the version number.
