### ISSUE TITLE
Keras 2.1.5: UnicodeDecode Error : 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

### ISSUE THREAD

**Issue by kkarnatak** [keras-team/keras#9906]
Hi

I  am trying to load a model from json and getting the UnicodeDecode error. I have reinstalled keras many times and replaced the generic_utils.py file even manually ( as I found some fixes on github ).
However, nothing works.

At first, I was trying to load an old model ( saved from keras 2.1.1 ) and it didnt work ( gave same unicodedecode errors ). Thus I re-run the network using keras 2.1.5 and saved new json model. However, the error remains.

@fchollet I even referred to https://github.com/keras-team/keras/issues/8738 and replaced the generic_utils.py but no change,

The error is as below:

```
kk@kk-VirtualBox:/media/sf_KK$ python test_network.py model_kk.h5
Using TensorFlow backend.
Traceback (most recent call last):
  File "test_network.py", line 101, in <module>
    model = model_from_json(jfile.read())
  File "/home/kk/miniconda3/envs/myenv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
```

I am saving the model in the following way:
```
 model.save_weights('./model.h5')
    json_string = model.to_json()
    with open('./model.json', 'w') as f:
        f.write(json_string)
```

I am reading the model in the following way:

```
if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Test network')
    parser.add_argument('model', type=str,
    args = parser.parse_args()
    #args.model contains the model filename "model.h5"
    with open(args.model, 'r') as jfile:
           model = model_from_json(jfile.read())

```

Header of the model.h5 from vi
```
<89>HDF^M
^Z
```

```

>>> import keras
Using TensorFlow backend.
>>> print(keras.__version__)
2.1.5
>>> 

```
- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by kkarnatak** [comment]
I reinstalled everything on different machine and was able to get rid of this error. not sure what caused it.

**Comment by Monolitho** [comment]
Same issue with faulty code 0x80. Don't know why.
