### ISSUE TITLE
Can't add a ResNet50 to a Sequential Model

### ISSUE THREAD

**Issue by engineer1982** [keras-team/keras#9909]
Hello everyone :)

I am trying to load a ResNet50 with no top, add it to a new Sequential model, then add a Dense layer on top of it. I have all updated (anaconda, spyder, keras, tensorflow, etc...)

After loading the ResNet50, I start to add layers to the new Sequential Model. At 4th layer, which is a batch norm, I get an error. Below is the code and the error. Tried to google it, but with no luck. Thanks in advance!

`base_model = applications.ResNet50(weights='imagenet', include_top=False, classes=8,
                                input_shape=(224,224,3), pooling='avg')`
`model = Sequential()`
`for layer in base_model.layers:
    model.add(layer)`

Error:
ValueError: Variable bn_conv1/moving_mean/biased already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:

  File "C:\Users\adminvale\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1269, in __init__
    self._traceback = _extract_stack()
  File "C:\Users\adminvale\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Users\adminvale\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)

**Comment by anovik** [comment]
I had the similar error with the very similar Keras model. Tested with different Keras versions and tested 2.1.2 and earlier versions work fine and 2.1.3 and later versions give this error. 

Setting reuse = True for Tensorflow backend doesn't solve this problem, BTW, it starts complaining that you should set reuse to None.

**Comment by mmagnuski** [comment]
I had the same problem but it disappeared when upgrading to tensorflow 1.8. See if updating tensorflow works for you too.

**Comment by jadevaibhav** [comment]
In sequential API, each node need to have one input and one output. In ResNet model, it has skip-connections. I think the problem arises due to it. Either use function API or use linear model like VGG19. Hope this helps.
