### ISSUE TITLE
[image_ocr.py] Unwanted characters predicted instead of blank/no label in CNN-RNN-CTC network

### ISSUE THREAD

**Issue by mailcorahul** [keras-team/keras#9916]
I am training a **CNN-RNN-CTC** network for predicting a word in an image. Accuracy(edit distance - 0) is around 75-80%. One of the problems i have encountered from the beginning is the prediction of unwanted characters in place of a no label(blank label as mentioned in CTC) either at the start or at the end of an image.

For example, an image containing a word "**Hello**" might be predicted as "**IHello**" or "l**Hello**" or "**Helloi**". This error varies for every epoch (each epoch might introduce a different character - '_' for one and '**I**' for another. Hence I am forced to choose a model with the least error insertion rate. Can anyone help me try to find what's going wrong??

**Comment by jawadrasool** [comment]
Were you able to solve this issue? If yes, can you let me know how? thanks!
