### ISSUE TITLE
delete please

### ISSUE THREAD

**Issue by virtualdvid** [keras-team/keras#9924]

**Comment by Dref360** [comment]
You can close the issue yourself by clicking the Close issue button.

**Comment by virtualdvid** [comment]
I'm sorry @Dref360. I was reading the rules to post an issue and accidentally I press <kbd>Enter</kbd> and it created an issue. I already posted my question on [stackoverflow](https://stackoverflow.com/questions/49806821/how-to-load-a-second-key-in-a-dictionary-in-hdf5matrix) thank you!
