### ISSUE TITLE
TimeseriesGenerator

### ISSUE THREAD

**Issue by TanguyUrvoy** [keras-team/keras#9929]
Hi,

`TimeseriesGenerator()` does not work if `sampling_rate` is not a multiple of `length`.
I submitted a PR on `keras_contrib` which fixes this issue by changing the semantic of the length parameter. It also proposes a few enhancements (prediction gap, shifted sequence as output, dtype for text RNNs).

Regards,

Tanguy

```
from keras.preprocessing.sequence import TimeseriesGenerator
data = np.array([[i] for i in range(50)])
gen = TimeseriesGenerator(data, data, length=10, sampling_rate=3)
gen[0] # error! (length must be a multiple of sampling_rate)

```

**Comment by rushabhpatil** [comment]
For length 10 in your example, first batch (of size 1) with sampling rate 2 will have inputs as 0,2,4,6,8. Sampling rate is the rate at which iterator takes values in that given length. To avoid data missed in learning, length/sample_rate must be an integer

**Comment by TanguyUrvoy** [comment]
Hi,
Indeed, that was precisely the point of my message.
A simple option to fix that problem is to add an exception in the `__init__` method when `length` is not a multiple of `sampling_rate`, another option that I suggested was to replace progressively `length` by `hlength`: the effective length of history after subsampling.

Regards,

Tanguy
