### ISSUE TITLE
Procedure entry point, ucrtbase.terminate could not be located in api-ms-win-crt-runtime-l1-1-0.dll

### ISSUE THREAD

**Issue by FaizSayyid** [keras-team/keras#9930]
OS: Windows 7
Backend: Tensorflow
Language: R

When specifying the NN structure like this:

````
model = keras_model_sequential() %>% 
  layer_dense(units = 16, activation = "relu", input_shape = ncol(encoded), kernel_regularizer = regularizer_l2(l = 0.6)) %>% 
  layer_dense(units = 1) 
````

I receive the following error message:

![image](https://user-images.githubusercontent.com/3586561/38730743-a4459b2e-3f0f-11e8-8c5f-96f9ac659b5b.png)

This only happens in R. In python I don't have any problems with Keras.

Details:

- [y ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [y ] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [y ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

````
library(insuranceData)
library(onehot)
library(keras)

data(AutoClaims)

response = AutoClaims$PAID
predictors = AutoClaims[,1:4]

encoded = onehot(predictors, stringsAsFactors = FALSE, addNA = FALSE, max_levels = 50)
encoded = as.matrix(predict(encoded,predictors))

#this is the line that causes the error:
model = keras_model_sequential() %>% 
  layer_dense(units = 16, activation = "relu", input_shape = ncol(encoded), kernel_regularizer = regularizer_l2(l = 0.6)) %>% 
  layer_dense(units = 1) 
````

The console returns:
````
Error in py_initialize(config$python, config$libpython, config$pythonhome,  : 
  C:/Users/faizsayyid/AppData/Local/CONTIN~1/ANACON~1/python36.dll - The specified procedure could not be found.
````

**Comment by Dref360** [comment]
Hi,
R related issues and questions should be posted to this GitHub repo: https://github.com/rstudio/keras/issues

We also have a community forum that supports discussion of ML and DL more broadly here (https://community.rstudio.com/c/ml).

Thanks!
