### ISSUE TITLE
Does Keras update learning rate decay every batch or epoch?

### ISSUE THREAD

**Issue by seanxh** [keras-team/keras#9938]
In some other frameworks, always learning rate decay every epoch. Like this formula 

lr = lr_0 \* 1/(1+decay_rate \* epoch_num)

But i see in keras [get_updates](https://github.com/keras-team/keras/blob/master/keras/optimizers.py#L312)，the updates variable looks will be called every batch[_fit_loop](https://github.com/keras-team/keras/blob/master/keras/engine/training.py#L1236).

Does that means  keras update learning rate decay between every batch??

**Comment by tchaton** [comment]
On every epoch

**Comment by tchaton** [comment]
But you can create your own callback where you can do it on every batches

**Comment by gattia** [comment]
[this](https://github.com/keras-team/keras/issues/2808) says it updates per batch.

**Comment by seanxh** [comment]
Thx~ @gattia .  It seems @joelthchao confirm Learning Rate is update every batch. I just curious why keras implement learning decay in this way.

**Comment by gattia** [comment]
I cant say I have the real answer as to why, but I would assume it is to be more flexible. By allowing update per batch, it is easy to make a calculation to allow a certain effect per epoch. However, if it is only updated per epoch, there is no way to have any updates prior to the finish of an epoch. If someone is using lots of data, epochs might be very slow to update.

**Comment by tchaton** [comment]
It is written on on_epoch_begin, so lr is updated every epochs class
LearningRateScheduler(Callback):
"""Learning rate scheduler.
# Arguments
schedule: a function that takes an epoch index as input
(integer, indexed from 0) and current learning rate
and returns a new learning rate as output (float).
verbose: int. 0: quiet, 1: update messages.
"""
def __init__(self, schedule, verbose=0):
super(LearningRateScheduler, self).__init__()
self.schedule = schedule
self.verbose = verbose
def on_epoch_begin(self, epoch, logs=None):
if not hasattr(self.model.optimizer, 'lr'):
raise ValueError('Optimizer must have a "lr" attribute.')
lr = float(K.get_value(self.model.optimizer.lr))
try: # new API
lr = self.schedule(epoch, lr=lr)
except TypeError: # old API for backward compatibility
lr = self.schedule(epoch)
if not isinstance(lr, (float, np.float32, np.float64)):
raise ValueError('The output of the "schedule" function '
'should be float.')
K.set_value(self.model.optimizer.lr, lr)
if self.verbose > 0:
print('\nEpoch %05d: LearningRateScheduler reducing learning '
'rate to %s.' % (epoch + 1, lr)

2018-04-16 13:08 GMT+01:00 Anthony <notifications@github.com>:

**Comment by gattia** [comment]
You are correct that learningRateScheduler works that way. But the question was not about learningRateScheduler, but instead about the decay parameter that is part of essentially all of the learning optimizers.

**Comment by seanxh** [comment]
@tchaton  your comprehension is wrong. The LearningRateScheduler is just a callback that model can adjust learning rate when you add a LearningRateScheduler implentation to callbacks.

**Comment by tchaton** [comment]
What I was meaning, is that you can implement a weight decay over epoch is
you want to.

2018-04-17 7:30 GMT+01:00 seanxh <notifications@github.com>:
