### ISSUE TITLE
Wierd behaviour from summary()

### ISSUE THREAD

**Issue by tchaton** [keras-team/keras#9940]
My model is : 
![save_error](https://user-images.githubusercontent.com/12861981/38773885-ef225a10-404f-11e8-9818-030eea95fed7.PNG)
I have trained for few epochs with vgg16 weights frozen .
Then I call the following code
```
for layer in model.layers[1].layers:
     layer.trainable = True
```
And I got this wierd summary
And I don't really know if the training is done correctly afterward.

**Comment by nuric** [comment]
After changing trainable property you need compile model again as the error message suggests. Otherwise the training graph is not constructed correctly and the weights are left untrained causing a "Discrepancy" in the number weights you think are trained and are actually trained.

**Comment by tchaton** [comment]
thanks you ! it works, but yet I have a very wierd result. Every
optimization collapse when vgg16 is unfrozen except yellowFin

2018-04-15 11:42 GMT+01:00 nuric <notifications@github.com>:

**Comment by jtboing** [comment]
Is there any updates on this issue?
