### ISSUE TITLE
Why we cannot pass None As  parameter in reshape

### ISSUE THREAD

**Issue by rachitg15** [keras-team/keras#9959]
model.add(Conv2D(64, (3, 3), input_shape=(32, None,1),padding='same', activation='relu',strides=(1,1)))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(128, (3, 3),padding='same', activation='relu',strides=(1,1)))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(256, (3, 3),padding='same', activation='relu',strides=(1,1)))

model.add(Conv2D(256, (3, 3),padding='same', activation='relu',strides=(1,1)))
model.add(MaxPooling2D(pool_size=(1, 2),strides=(2,2)))

model.add(Conv2D(512, (3, 3),padding='same', activation='relu',strides=(1,1)))
model.add(BatchNormalization())

model.add(Conv2D(512, (3, 3),padding='same', activation='relu',strides=(1,1)))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(1, 2),strides=(2,2)))

model.add(Conv2D(512, (2, 2), activation='relu',strides=(1,1)))

model.add(Reshape((None, 512)))

I want width of an image to be variable but it is giving error in reshape

**Comment by Dref360** [comment]
You need to use -1 just like with Numpy.

This issue isn't related to a bug/enhancement/feature request or other accepted types of issue.

To ask questions, please see the following resources : 
* https://keras.io/
* https://keras.io/#support
* https://gitter.im/Keras-io/Lobby

Thanks!

If you think I made a mistake, please re-open this issue.

**Comment by rachitg15** [comment]
I have done this:
model.add(Reshape((-1,512)))

But it is still giving the following error:
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by Dref360** [comment]
This works for me on master.

```python
import os

os.environ['CUDA_VISIBLE_DEVICES'] = ''

from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, BatchNormalization, Reshape
import numpy as np

model = Sequential()
model.add(Conv2D(64, (3, 3), input_shape=(32, None, 1), padding='same', activation='relu', strides=(1, 1)))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(128, (3, 3), padding='same', activation='relu', strides=(1, 1)))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(256, (3, 3), padding='same', activation='relu', strides=(1, 1)))

model.add(Conv2D(256, (3, 3), padding='same', activation='relu', strides=(1, 1)))
model.add(MaxPooling2D(pool_size=(1, 2), strides=(2, 2)))

model.add(Conv2D(512, (3, 3), padding='same', activation='relu', strides=(1, 1)))
model.add(BatchNormalization())

model.add(Conv2D(512, (3, 3), padding='same', activation='relu', strides=(1, 1)))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(1, 2), strides=(2, 2)))

model.add(Conv2D(512, (2, 2), activation='relu', strides=(1, 1)))

model.add(Reshape((-1, 512)))
model.compile('sgd', 'mse')
model.summary()
model.fit(np.ones([10, 32, 32, 1]), np.ones([10, 4, 512]), 10)

```
