### ISSUE TITLE
Is there a nice way to do 2D embedding? #1693 - REVISITED 

### ISSUE THREAD

**Issue by faltinl** [keras-team/keras#9961]
The [post ](https://github.com/keras-team/keras/issues/1693) mentioned in the header dealt with the problem to find a way to do a 2D embedding layer. This question has been answered by @wxs with
> Just reshape your X to 2d, use a normal embedding, and then reshape its output via http://keras.io/layers/core/#reshape 

I must, however, confess that I don't understand this answer. An embedding layer in Keras needs a 2D input of shape (batch_size, sequence_length) to produce an output of shape (batch_size, sequence_length, output_dim). Thus, if my X has shape (batch_size, dimA, dimB) I can easily reshape it into a 2D input of shape (batch_size, (dimA * dimB)), with sequence_length=(dimA * dimB), but reshaping it back to get an X with same size as before will not be possible since the embedding layer produces an output shape of (batch_size, sequence_length=(dimA * dimB), output_dim). 

How do I deal with output_dim at that point in order to be able, as an example, to add a 2D-convolution layer? 

I would appreciate if @wxs or somebody else could comment on that - thanks in advance!
Leo

**Comment by nuric** [comment]
The Embedding layer does work with higher rank tensors. Shape (samples, dimA, dimB) can be embedded to return (samples, dimA, dimB, embedding_size) without a problem (at least in the TensorFlow backend). Do you have a specific case in which this fails in the latest version?

**Comment by faltinl** [comment]
Tnx for fast reply - this might be a valuable hint: I'm using Keras/KerasR with Tensorflow 1.4.3 under Anaconda. The standard update check under Rstudio tells me, that this version is up-to-date (but who really knows!-) 
From [Tensorflow webpage](https://www.tensorflow.org/get_started/os_setup) I conclude that this version is already newer than their v1.0. Which version do you use - and if it's newer, where did you get it?
