### ISSUE TITLE
Unknown elements appear in validation_data

### ISSUE THREAD

**Issue by ishalyminov** [keras-team/keras#9966]
My model is compiled with `sample_weight_mode=temporal`, I train it with `fit_generator` returning tuples <X, y, sample_weight>, and evaluating it on the full devset passed as `validation_data=(X_dev, y_dev, weights_dev)`. My model has 2 inputs so `X` is a list of 2 numpy arrays.

Now, in [my custom callback](https://stackoverflow.com/a/49832560/932818) at `on_epoch_end`, I check `len(self.validation_data)` and see that it's 5..

OK, the first extra element is `X_dev` flattened from a sublist into 2 elements of the new validation data (although I have no idea why it happens).

But the second extra element is actually just a scalar `0.0` appended to `self.validation_data`! 
Where does it even come from???

**Comment by deakkon** [comment]
Hi,

Im writing my own evaluation callbacks and need to access valdiation_data and having the same question. 

Did you figure this out? Any ideas whats happening here?

**Comment by ishalyminov** [comment]
Hi @deakkon. Sorry I don't recall having found the solution..
