### ISSUE TITLE
Memory leak on web server

### ISSUE THREAD

**Issue by MoyanZitto** [keras-team/keras#9967]
Hi @fchollet 

We noticed that Keras model suffers remarkable memory leak when running on a (Flask) web server. 

This is a very serious problem and perhaps your team should try to fix it.

**Comment by Dref360** [comment]
Could you provide a minimal example/steps to reproduce?

**Comment by MoyanZitto** [comment]
@Dref360 
I can provide some evidence.
Here's the server's memory usage:

![_15241908008157](https://user-images.githubusercontent.com/10725096/39027470-a4bd4ad2-4484-11e8-93c0-db9bf61f7003.png)

Some server code:
```python
# prepare for serve
model_name = "mymodel.h5" 
model = load_model("./models/"+model_name)
graph = tf.get_default_graph()

def predict(graph, model, feat):
	with graph.as_default():
		result = model.predict(feat)
		result = np.squeeze(result)
		if result>0.5:
			return 1, result
		else:
			return 0, 1-result
```

and we call predict on the received data under the flask framework.  

The clients extract features and send json messages to server, we noticed that the cpu usage is at a low level, so the memory increase cannot caused by too many requests.

That's why I think there're memory leak at server side. 

Any suggestions?

**Comment by Dref360** [comment]
I removed the `with graph.as_default():` and I don't get the memory leak. I don't think this has nothing to do with keras itself or Flask.

Read the documentation of `as_default`, you do not use it correctly.

**Comment by MoyanZitto** [comment]
@Dref360  Ok, I'll have a try, thanks a lot. I'll reply here later.

**Comment by wangyexiang** [comment]
Hi, have you solve your problem? I meet a similar issue. if I load my model several times in a loop， I find remarkable memory leak. could you point me to a solution? Thank you. @MoyanZitto

**Comment by MoyanZitto** [comment]
@wangyexiang Hi I've solved this problem. @Dref360 is correct.

loading model in a loop will cause memo leak. Try to use K.clear_session().
