### ISSUE TITLE
How to merge two DirectoryIterator?

### ISSUE THREAD

**Issue by Golbstein** [keras-team/keras#9969]
Hi, I'm looking at the example here:
[https://blog.keras.io/building-powerful-image-classification-models-using-very-little-data.html](url)

They create 3 iterators: for train, validation and test.
```
test_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
        'data/train',  # this is the target directory
        target_size=(150, 150),  # all images will be resized to 150x150
        batch_size=batch_size,
        class_mode='binary')  # since we use binary_crossentropy loss, we need binary labels

validation_generator = test_datagen.flow_from_directory(
        'data/validation',
        target_size=(150, 150),
        batch_size=batch_size,
        class_mode='binary')
```

My question is whether it's possible to merge\combine train_generator with validation_generator to a single generator that contains images from both train and validation folder.

THX

**Comment by nuric** [comment]
They both return generators that return the data points for training. Have you tried joining the generators using Python ```itertools.chain()``` ? There is [this post](https://stackoverflow.com/questions/3211041/how-to-join-two-generators-in-python) on StackOverflow that might help.

**Comment by Metete** [comment]
After merging the two iterators via itertools, the result is not anymore a DirectoryIterator but just an iterator. Since the parent (Iterator) would not have the same properties of the child (directoryIterator), we can not use DirectoryIterator's functionality anymore. However, some custom casting can be done.

**Comment by Metete** [comment]
Thanks @Dref360 for your answer. 

I tried your approach. However, while feeding the neural network at the step with fit_generator, it stucks at the 1st batch of the 1st epoch and after waiting some time I get memory error.

This issue does not occur when I feed the neural network using seperate DirectoryIterators without merging them. However, I need to merge them on the fly somehow.

Current implementation:

```
#training data folds
flow_fold1 = image.ImageDataGenerator(preprocessing_function= keras
                                             .applications.mobilenet.preprocess_input).flow_from_directory(fold1_path, target_size=(224, 224), batch_size=10)
    
flow_fold2 = image.ImageDataGenerator(preprocessing_function= keras
                                             .applications.mobilenet.preprocess_input).flow_from_directory(fold2_path, target_size=(224, 224), batch_size=10)

#validation data fold
flow_fold0 = image.ImageDataGenerator(preprocessing_function= keras
                                             .applications.mobilenet
                                             .preprocess_input).flow_from_directory(fold0_path, target_size=(224, 224), batch_size=10)

#merged iterators
my_seq = MySequence(flow_fold1, flow_fold2)

training_history = modified_architecture.fit_generator(my_seq, steps_per_epoch=10, validation_data=flow_fold0 , validation_steps=10, epochs=18, verbose=1) 
```

**Comment by Dref360** [comment]
Try reducing the batch size, if it still doesn't work, try setting workers=0.

**Comment by Metete** [comment]
Thank you @Dref360 for your prompt answer.

I reduced the batch size from 10 to 2 and even 1 but it still stucks at the 1st epoch and I think it does not even get the first batch as the input. This is the output when workers = 1:

```
Found 1597 images belonging to 8 classes.
Found 1531 images belonging to 8 classes.
Found 1597 images belonging to 8 classes.
Epoch 1/18
```

When I set the workers = 0, I receive the below error:
```
in <module>
training_history = modified_architecture.fit_generator(my_seq, steps_per_epoch=10, validation_data=valid_batches, validation_steps=10, epochs=18, verbose=1, workers = 0)

  File "C:\Users\metete\Anaconda3\envs\tensorflow\lib\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\metete\Anaconda3\envs\tensorflow\lib\site-packages\keras\engine\training.py", line 2089, in fit_generator
    enqueuer.stop()

  File "C:\Users\metete\Anaconda3\envs\tensorflow\lib\site-packages\keras\utils\data_utils.py", line 520, in stop
    self.stop_signal.set()

AttributeError: 'NoneType' object has no attribute 'set'
```

I am using the exact same MySequence class that you mentioned.

**Comment by vipuljain-17** [comment]
Did you solve this issue?
