### ISSUE TITLE
While installing through pip getting Fatal error in launcher

### ISSUE THREAD

**Issue by Saini-96** [keras-team/keras#9974]
(base) C:\Users\hp 1>pip install --upgrade keras
Fatal error in launcher: Unable to create process using '""c:\program files\anaconda3\python.exe"  "C:\Program Files\Anaconda3\Scripts\pip.exe" install --upgrade keras'

what to do for this

**Comment by harshthaker** [comment]
Did you try pip3 install --upgrade keras ?

**Comment by Saini-96** [comment]
Yup but for this also it does not work

**Comment by harshthaker** [comment]
And how about 'python -m pip install --upgrade keras ' ?

**Comment by Saini-96** [comment]
It's working....
thanks mate!!
