### ISSUE TITLE
Backend declaration problem

### ISSUE THREAD

**Issue by poffemre** [keras-team/keras#9978]
Dear keras team,

I am newcomer to deeplearning side. 
When I run below code 

`from keras import backend as K`
`K.clear_session()`

I'm getting an error like ;
Using Theano backend.
```
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    from Learner import Model_Builder
  File "~\Learner.py", line 13, in <module>
    K.clear_session()
AttributeError: module 'keras.backend' has no attribute 'clear_session'
```
I guess I can not get theano from 'backend'. 
Where the problem could be ? 
Thanks in advance.

**Comment by Dref360** [comment]
Theano doesn't use Session, only Tensorflow does.
