### ISSUE TITLE
Keras installation with conda issues

### ISSUE THREAD

**Issue by gandroz** [keras-team/keras#9984]
I have an issue with the installation of Keras with conda package manager. There are several channels where keras is hosted, the most popular one being `conda-forge`. When using `cond-forge`, a script is added and launched when activating a virtual environment where the variable `KERAS_BACKEND` is set to `theano` by default, overwriting any configuration in the `keras.json` file.

The second issue come when installing keras with the default channel `conda install keras`. Here again, an environment variable `KERAS_BACKEND` is set to `theano` by default, but I did not found where it is set. The only workaround I found was to tweak the `keras.backend.__init__.py` file and commenting the environment variable import.

My question is then, do you work with `conda` to package keras or is it their own initiative ?

**Comment by gabrieldemarmiesse** [comment]
The recommended way to install keras is with pip. Anaconda distributions aren't done by the maintainers of this repo. You likely have an outdated version of keras if you installed it with conda install.

**Comment by gandroz** [comment]
ok thank you for the answer, I thought conda was also a trustful package manager for keras....

**Comment by VanitarNordic** [comment]
You can use  `conda install -c hesi_m keras ` to install the latest version of Keras (2.1.6) and Tensorflow(1.8) for you.

**Comment by VanitarNordic** [comment]
Now, You can use `conda install -c hesi_m keras` to install the latest version of **Keras (2.2.0)** and **Tensorflow(1.8.0)** for you.

**Comment by Banerjee1996** [comment]
I am facing the same problem.
At first i used this command
 conda install -c conda-forge keras tensorflow
but the command prompt closes abruptly diplaying this code
python %CONDA_PREFIX%\etc\keras\load_config.py > temp.txt
set /p KERAS_BACKEND=<temp.txt
del temp.txt

:: Try to use the default Keras backend.
:: Fallback to Theano if it fails (Theano always works).
python -c "import keras" 1> 2>&1
if errorlevel 1 (
    ver > nul
    set "KERAS_BACKEND=theano"
    python -c "import keras" 1> 2>&1
 
I used this link to solve the problem ,

https://stackoverflow.com/questions/53483685/keras-breaks-anaconda-prompt?noredirect=1&lq=1

But now none of the conda integrated Ides would open.
(VStudio and Jupyter). 
I am using Anaconda distibution on windows.

**Comment by rchiodo** [comment]
I believe this is the root cause of an issue we're having in the VS Code python extension as well:
https://github.com/Microsoft/vscode-python/issues/5259
