### ISSUE TITLE
ValueError: Transfer Learning with VGG16, error when applied to image.

### ISSUE THREAD

**Issue by mdkhan48** [keras-team/keras#9986]
I am using transfer learning with VGG16 based on [https://github.com/fchollet/deep-learning-with-python-notebooks/blob/master/5.3-using-a-pretrained-convnet.ipynb](url)
Here is the final 2 layers '**Training'** code:
```
model = models.Sequential()
model.add(layers.Dense(256, activation='relu', input_dim=4 * 4 * 512))
model.add(layers.Dropout(0.5))
model.add(layers.Dense(3, activation='softmax'))

model.compile(optimizer=optimizers.RMSprop(lr=2e-5),
              loss='sparse_categorical_crossentropy',
              metrics=['acc']

model.save('5_3_VGG16.h5')
```
I used the following code to detect from an image **'Testing'** code:

```
model = load_model('5_3_VGG16.h5')
img_path = '/home/sayem/Desktop/weed_video_detect/other.803.jpg'
img = image.load_img(img_path, target_size=(150,150))


x = image.img_to_array(img)
orig = x.copy()

x = np.expand_dims(x, axis=0)

result = model.predict(x)[0]
print (result)

if result[0] == 1:
    prediction = 'cat'
elif result[1] == 1:
    prediction = 'dog'
else:
    prediction = 'other'

print (prediction)
```
Got the following error:
File "/home/sayem/Desktop/weed_video_detect/testkeras.py", line 27, in <module>
    result = model.predict(x)[0]
  File "/home/sayem/video_detect/lib/python3.5/site-packages/keras/models.py", line 1025, in predict
    steps=steps)
  File "/home/sayem/video_detect/lib/python3.5/site-packages/keras/engine/training.py", line 1817, in predict
    check_batch_axis=False)
  File "/home/sayem/video_detect/lib/python3.5/site-packages/keras/engine/training.py", line 113, in _standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking : expected dense_1_input to have 2 dimensions, but got array with shape (1, 150, 150, 3)

Help me solve it.

**Comment by vamshi-indla** [comment]
1. Link is not opening, update it: https://github.com/fchollet/deep-learning-with-python-notebooks/blob/master/5.3-using-a-pretrained-convnet.ipynb

2. input_dim is not required here, as it is a new layer addition to a vgg16 model. You can delete it and try. 
```model.add(layers.Dense(256, activation='relu', input_dim=4 * 4 * 512))```

3. Add below code after  ```x = np.expand_dims(x, axis=0)```
```x = preprocess_input(x)```

4. I do not see vgg16 model load, this is required, immediately after ```model = models.Sequential()```
```model = VGG16(weights='imagenet', include_top=False)```

**Comment by mdkhan48** [comment]
1. Here is the code I used for 'Training':

```
from keras.applications import VGG16
conv_base = VGG16(weights='imagenet',
                  include_top=False,
                  input_shape=(150, 150, 3))
base_dir = '/home/agbot/Desktop/3animaltest/3animal'

train_dir = os.path.join(base_dir, 'train')

validation_dir = os.path.join(base_dir, 'validation')

test_dir = os.path.join(base_dir, 'test')

datagen = ImageDataGenerator(rescale=1./255)
batch_size = 20
def extract_features(directory, sample_count):
    features = np.zeros(shape=(sample_count, 4, 4, 512)) 
    labels = np.zeros(shape=(sample_count))
    generator = datagen.flow_from_directory(
        directory,
        target_size=(150, 150), #input size
        batch_size=batch_size,
        class_mode='sparse') #what will be class mode for 3 weeds?
    i = 0
    for inputs_batch, labels_batch in generator:
        features_batch = conv_base.predict(inputs_batch)
        features[i * batch_size : (i + 1) * batch_size] = features_batch
        labels[i * batch_size : (i + 1) * batch_size] = labels_batch
        i += 1
        if i * batch_size >= sample_count:
    return features, labels

train_features, train_labels = extract_features(train_dir, 2400)
validation_features, validation_labels = extract_features(validation_dir, 300)
test_features, test_labels = extract_features(test_dir, 300)
train_features = np.reshape(train_features, (2400, 4 * 4 * 512))
validation_features = np.reshape(validation_features, (300, 4 * 4 * 512))
test_features = np.reshape(test_features, (300, 4 * 4 * 512))


model = models.Sequential()
model.add(layers.Dense(256, activation='relu', input_dim=4 * 4 * 512))
model.add(layers.Dropout(0.5))
model.add(layers.Dense(3, activation='softmax')) #different for 3 weeds

model.compile(optimizer=optimizers.RMSprop(lr=2e-5),
              loss='sparse_categorical_crossentropy',
              metrics=['acc'])

history = model.fit(train_features, train_labels,
                    epochs=30,
                    batch_size=20,
                    validation_data=(validation_features, validation_labels))
model.save('5_3_VGG16.h5')

```
2nd part of the code (mentioned in original question) is for 'Testing'. 

2. So you are suggesting I train again deleting the line from 'Training" code?
`model.add(layers.Dense(256, activation='relu', input_dim=4 * 4 * 512))`

3. I tried it before posting it here. No luck.

4. As I have leaded my saved model '5_3_VGG16.h5' in 'Testing' part of the code, I thought I dont have to load imagnet because all the weights are saved in '5_3_VGG16.h5'. I maybe wrong. Let me know.

**Comment by vamshi-indla** [comment]
Here is the corrected code. As this is not a keras issue, you can close it and open it in stackoverflow for any follow up questions.

https://github.com/vamshi-indla/Image_Recognition_Classifier/blob/master/Transfer_Learning_Vgg16_New_Classes.ipynb

**Comment by mdkhan48** [comment]
What you have posted is a different solution. This is a training code which is possible on GPU. What I wanted to do in my training, is to do it on CPU. But I am guessing adding the `layers.flatten()` after dropout would solve my problem. I will try that. Thanks.
