### ISSUE TITLE
entity-level sentiment analysis using Keras models

### ISSUE THREAD

**Issue by monajalal** [keras-team/keras#9991]
I am interested in entity-level sentiment analysis using Keras (ex. using Char RNN with LSTM/BiLSTM modules or other possible models). Can you please link me to proper code snippets?

**Comment by Dref360** [comment]
Hi!
This issue isn't related to a bug/enhancement/feature request or other accepted types of issue.

To ask questions, please see the following resources : 
* https://keras.io/
* https://keras.io/#support
* https://gitter.im/Keras-io/Lobby

Thanks!

If you think I made a mistake, please re-open this issue.
