### ISSUE TITLE
[feature] Support for same padding in locally connected layers

### ISSUE THREAD

**Issue by cancan101** [keras-team/keras#9998]
Right now locally connected layers only support `"valid"` padding. There is a comment that `"same"` padding may / will be supported in the future however there seems to be no ticket tracking this.

2D:
https://github.com/keras-team/keras/blob/05fe6076a117a184781c2c2dce087189995bf4d6/keras/layers/local.py#L214-L215

1D:
https://github.com/keras-team/keras/blob/05fe6076a117a184781c2c2dce087189995bf4d6/keras/layers/local.py#L48-L49

**Comment by hfawaz** [comment]
Is this feature going to be added in the near future ?
